### ISSUE TITLE
 IOU Request - Error "Invalid onyxMethod mergecollection in Onyx update." appeared in Console

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into NewDot as user 1
2. Start a chat with a user 2 (a user you have not chatted with before)
3. Create an IOU request (either from within the chat, or from the LHN menu)
4. Tap the IOUPreview to open the IOU Details Modal

## Expected Result:
No error in Console logs.

## Actual Result:
Error "Invalid onyxMethod mergecollection in Onyx update." appeared in Console

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:**  v1.1.85-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="994" alt="Bug5654537_Screen_Shot_2022-07-19_at_12 15 03_PM" src="https://user-images.githubusercontent.com/43996225/179814687-6fc5e9d5-6250-4c55-8156-0e2a96a95220.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
It looks like we're not using the latest version of Onyx since the check was recently updated [here](https://github.com/Expensify/react-native-onyx/blob/49a2b825099fa89e78d4692d63e05aeaef3b2b2a/lib/Onyx.js#L820).

**Comment by mountiny** [comment]
Ah, we have bumped to 1.0.8 here https://github.com/Expensify/App/pull/9877, but that used `mergeCollection` and then the update to `mergecollection` has been in later version, which failed to bundle https://github.com/Expensify/react-native-onyx/pull/160.

So we should update to 1.0.10 :/ https://github.com/Expensify/react-native-onyx/pull/162

@neil-marcellini re you able to create the PR and run npm install?

**Comment by neil-marcellini** [comment]
Yep I was just about to say that. I'll have a PR up very soon. I might have some integrity changes as well but I'll have to see. Could we manually omit those changes?

**Comment by mountiny** [comment]
I am not sure tbh :/ if it is just a few of them then it is fine. But for me, AFAIK because of the intel having different architecture it creates like hundreds lines big diff :/

**Comment by Julesssss** [comment]
Thanks for fixing this @neil-marcellini!
