### ISSUE TITLE
Messages are being lost and fail to send

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#10000]
# Problem

CC @cead22 @Expensify/mobile-deployers 

Messages are disappearing and not being sent in NewDot. This is extremely annoying and is wasting all of our time. We need to figure out which issue introduced the regression, or locate the bug and fix it.
___

## Action Performed:
It's not consistently reproducible, but these are the rough steps we have been following:
1. In NewDot (`staging.new.expensify.com`) Switch to a different chat
2. Type a message and hit enter
3. Sometimes the message disappears instead of sending. 

## Expected Result:
The message should send.

## Actual Result:
The message is lost, no draft is kept, and no notification is received by the other user. 

## Workaround:
It works most of the time, but occasionally is being triggered. No known workaround exists yet. 

## Platform:

Where is this issue occurring?

So far, we have only been able to reproduce on web.

- [x] Web 
- [ ] iOS (unknown)
- [ ] Android (unknown)
- [ ] Desktop App (unknown)
- [ ] Mobile Web (unknown)

**Version Number:** v1.1.85-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unknown
**Email or phone of affected tester (no customers):** any user
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 N/A
**Notes/Photos/Videos:** Any additional supporting documentation N/A, everytime I record, I have been unable to reproduce
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658243988953749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
<img width="693" alt="Screen Shot 2022-07-19 at 11 22 54 AM" src="https://user-images.githubusercontent.com/2838819/179811644-271aa6f9-2805-4b48-95c3-26ea6f7de2eb.png">

```
web.min.js:1 Uncaught Error: Invalid undefined key provided in Onyx update. Onyx key must be of type string.
    at web.min.js:1:11206
    at Function.kt (each.js:14:7)
    at Object.$ [as update] (web.min.js:1:10986)
    at _l (API.js:23:14)
    at Qm (Report.js:1011:5)
    at Report.js:1040:5
    at n.value (ReportScreen.js:148:9)
    at n.value (ReportActionCompose.js:465:20)
    at n.value (ReportActionCompose.js:408:18)
    at r.forwardRef.ve.onKeyDown (index.js:278:7)
(anonymous) @ web.min.js:1
kt @ each.js:14
$ @ web.min.js:1
_l @ API.js:23
Qm @ Report.js:1011
(anonymous) @ Report.js:1040
value @ ReportScreen.js:148
value @ ReportActionCompose.js:465
value @ ReportActionCompose.js:408
r.forwardRef.ve.onKeyDown @ index.js:278
qe @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Er @ react-dom.production.min.js:100
Or @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ie @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
```

**Comment by Julesssss** [comment]
Thanks, that's great. Sounds like there's an issue with the Onyx update occuring in [the AddComment API](https://github.com/Expensify/App/blob/258c26843fff3726980c36de9033aafcab7f0f8a/src/libs/actions/Report.js#L965-L979). CC @marcaaron

**Comment by marcaaron** [comment]
Setting a key of `undefined` in Onyx throws an error? Hmm well that would certainly break things... maybe it should log instead 👀

**Comment by mvtglobally** [comment]
@Julesssss @marcaaron  Our team noticed somewhat similar issue, but its not consistently repro. Should we log a new issue or this is same root cause? 

https://user-images.githubusercontent.com/43995119/179812889-6f149017-f21a-42e3-a100-a5edd8439b6f.mp4

**Comment by marcaaron** [comment]
It's this here: 

https://github.com/Expensify/App/blob/258c26843fff3726980c36de9033aafcab7f0f8a/src/libs/actions/Report.js#L954

**Comment by marcaaron** [comment]
The ONYXKEYS.MY_PERSONAL_DETAILS was removed here -> https://github.com/Expensify/App/pull/9560

And this was hard to reproduce because you need to wait 5 minutes so the timezone updating logic runs.

**Comment by mountiny** [comment]
That one key slipped out review 😬 

this is the related PR https://github.com/Expensify/App/pull/9560

**Comment by luacmartins** [comment]
Issue #10000, such a milestone 😄

**Comment by marcaaron** [comment]
>In the process of sending a message, previous messages are temporarily not displayed.

@mvtglobally that looks like something else.

**Comment by mvtglobally** [comment]
We retested and it seem to be no longer repro
