### ISSUE TITLE
Web - Chat - When hit (CTRL+K) after opening global action button,  Global action button and search modal opens

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Click on the "Global action" button 
3. Press on CTRL + K

## Expected Result:
The first modal  should be closed when the second is opened

## Actual Result:
Both Global action button and search modal opens

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.85-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5654645_Screenshot_2022-07-19_213258](https://user-images.githubusercontent.com/43996225/179831068-895e3e02-103f-424d-8fed-10d0d7ac6e59.png)

https://user-images.githubusercontent.com/43996225/179831074-abed4adb-d791-4e0e-9237-d6b7ef9288ae.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Not a huge deal. Setting as monthly!

**Comment by kbecciv** [comment]
@Gonals One of the tester experienced a similar issue. When open the New room through the FAB menu and press the spacebar on the keyboard, then the FAB menu will additionally open again.

https://user-images.githubusercontent.com/93399543/183112315-1524c471-8f5f-4786-be08-de92fe5b39cc.mp4
