### ISSUE TITLE
Web - Search window/Currency selection - Jerk when moving between the first and last point

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10012]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Click on the "Global action" button/Request money
3. Сlick on the currency to change it
4. When you are on the first point, press the "up" key, and when you are on the last one, press the "down" key
(the same situation in the search window between the first and last participant)

## Expected Result:
The transition should be smooth
## Actual Result:
Jerk when moving between the first and last point

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.85-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** iuliiaherets@gmail.com / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/179832938-281ad60d-225e-4382-9253-542a66cf7ba7.mp4

**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
It looks like smooth scrolling is making this smoother than it should be in this case (should just jump).

https://user-images.githubusercontent.com/87341702/179900918-717d9b2b-e52e-461d-8c28-efaeab18e6f7.mov

 I'm going to just close this because I'm not really convinced that this is unwanted behaviour and it doesn't look important
