### ISSUE TITLE
Preferences - Notifications status is "subscribed" by default for the newly created accounts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9697
## Action Performed:
1. Create an account
2. Login to the App
3. Go to  Settings > Preferences > Notifications 

## Expected Result:
Verify that Notifications is not subscribed

## Actual Result:
Notifications is subscribed for new accounts.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.85-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** rybkina+0719xc@gmail.com / Qwerty123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="999" alt="Bug5654649_notifications" src="https://user-images.githubusercontent.com/43996225/179832301-08ed0c38-3e22-4cb3-a33d-8eec3e248cb0.png">

https://user-images.githubusercontent.com/43996225/179832314-7f7ce71a-ced6-49dd-8ffe-8fbb29096df2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I think we do want notifications enabled by default. I'll double check in Slack.

**Comment by sakluger** [comment]
This is the correct/expected behavior! We do want notifications to be enabled by default.
