### ISSUE TITLE
[$500] Web - OldDot Transition - if few NewDot tabs are opened, some/all may crash after Workspace creation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10017]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the OldDot and delete all Polices/Workspaces
2. Open 2-3 other tabs with NewDot: any user or just a login page
3. Trigger new Workspace creation by selecting the Free plan

## Expected Result:
The user should be able to create new Workspace by selecting free plan without any issues

## Actual Result:
Some NewDot tabs will be crashed with an error, other will load but slowly
Some times all tabs will crash with an error

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179868222-95a500e8-7f51-4c7b-a7ed-36639ff53826.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment]
Leaving for another week to see if we can get repro before adding to Upwork

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by pecanoro** [comment]
I am going to close since this is not reproducible anymore.
