### ISSUE TITLE
iOS - IOU - Preview component - Crash after tapping on the' Pay' or 'View details' buttons

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send only one request to the user A
2. Login in iOS app as user A
3. Open the DM, tap on the "View details' or 'Pay' button

## Expected Result:
The user should be able in interact with payment preview component without any issues

## Actual Result:
If the user has only one payment request - the App will crash after tapping on the 'Pay' or 'View details button'
if the user has few payment request - not all comments and request will be visible after tapping on the 'Pay' or 'View details button'
This scenario also present in the Web

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.85-5

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/179853753-9b6842a3-f053-4931-b42a-ef79c49845d0.mp4

https://user-images.githubusercontent.com/43996225/179853766-bd14e670-fafd-4b23-a850-5a951b71cfba.mp4
[Bug5654858_crash_-_view_details.txt](https://github.com/Expensify/App/files/9144919/Bug5654858_crash_-_view_details.txt)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
@kavimuru I don't see the app crashing in your video, I assume it crashed at the last screen?

**Comment by mountiny** [comment]
cc @Julesssss seems like this could be regression from our refactoring https://github.com/Expensify/App/pull/9878

**Comment by kavimuru** [comment]
@iwiznia  I have attached crash video too.
https://user-images.githubusercontent.com/43996225/179853766-bd14e670-fafd-4b23-a850-5a951b71cfba.mp4

**Comment by Julesssss** [comment]
Ugh. I spent all day on[ this other](https://github.com/Expensify/App/issues/10024) deploy blocker and didn't get around to this. If nobody has picked up it by tomorrow I'll be able to start on it

**Comment by Julesssss** [comment]
CC @chiragsalian

**Comment by mountiny** [comment]
This _might_ be fixed with [this CP](https://github.com/Expensify/App/pull/10043), havent got around to test this.

**Comment by mountiny** [comment]
I have tested it now with the new main after the timezone fix and it seems fixed.

@kavimuru can you retest it with the latest Staging CP?

**Comment by mountiny** [comment]
Tested in the App, I can't seem to reproduce so I will close this but still ask for double checking from Applause!

**Comment by mountiny** [comment]
Thanks!
