### ISSUE TITLE
Request Money - Report Status shows paid when clicked on view details after request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on any user
4. Tap on Plus button - Request Money
5. Select amount and tap Request button
6. Tap on view details

## Expected Result:
Report Status shows open when clicked on view details after request

## Actual Result:
Report Status shows paid when clicked on view details after request

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/179901820-d7b32ca4-0204-47b2-8cd0-7bb2fdd8fc07.mp4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause-Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
cc: @Julesssss Not sure if this might be related to: https://github.com/Expensify/App/pull/9878

**Comment by Julesssss** [comment]
Yeah, quite possibly. Taking a look this morning.

**Comment by Julesssss** [comment]
Strange that this didn't come up during testing as this was a test case... Anyway, the fix is to add the data to the Web-E layer which I'll do now

**Comment by Julesssss** [comment]
Okay, so I've fixed the original issue. But ran into a new one, which I'm solving [here](https://github.com/Expensify/App/pull/9836) as it's also occurring on this linked issue.

**Comment by Julesssss** [comment]
WIP Pr: https://github.com/Expensify/Web-Expensify/pull/34366

**Comment by Julesssss** [comment]
Ran out of time, will be finishing this tomorrow morning

**Comment by Julesssss** [comment]
Raised a PR and I'll request a CP to prod once it's approved and merged.

**Comment by Julesssss** [comment]
Confirmed resolved with this [CP'd PR](https://github.com/Expensify/Web-Expensify/pull/34366)

**Comment by Julesssss** [comment]
@Expensify/applauseleads please retest this one. I have removed the blocker label in the meantime.

**Comment by mvtglobally** [comment]
Issue is fixed.

https://user-images.githubusercontent.com/43995119/180299987-a558c038-b1f1-4b52-9de5-000357ebb885.mp4

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week) @Julesssss  @MariaHCD  Are we ok to close this?

**Comment by Julesssss** [comment]
Yep, thank you!
