### ISSUE TITLE
Desktop - Money request - Onyx JS errors after few requests to the new user and blank chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10038]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10008 

## Action Performed:
1. Create and validate fresh NewDot user
2. Login as other user to the Desktop App
3. Start chat with newly created user
4. Send first money request and click on the "View details"
5. Send second money request and click on the "View details"

## Expected Result:
The user should be able to send money requests and check details without any issues
No JS errors should be present in the console

## Actual Result:
After second money request - JS Onyx error, not all information visible in details
Once details is opened - chat window cleared, all new messages not visible

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** yuriy.turbo+ch5@gmail.com/Aa111111

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180061241-144ab76a-0f4f-4171-9cb5-49d67c622059.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Ooo yikes that's a bad one directly related to the fix for the last deploy blocker. Thank you for catching it in QA! I'll start taking a look.

**Comment by neil-marcellini** [comment]
The root problem here is that you [cannot spread an object into an array](https://stackoverflow.com/questions/52789340/in-javascript-why-can-any-value-be-spread-in-an-object-but-not-in-an-array) unless it implements the iterable protocol. We are trying to spread the `mergeValue` object into the array `data`.

Maybe the if statement condition should be `&&` not `||` @marcaaron ?
```javascript
if (_.isArray(data) || _.every(mergeValues, _.isArray)) {
        // Array values will always just concatenate
        // more items onto the end of the array
        return _.reduce(mergeValues, (modifiedData, mergeValue) => [
            ...modifiedData,
            ...mergeValue,
        ], data || []);
    }
```

Instead of diving into Onyx I think the best solution is to make sure that the data we are merging in is an object instead of an array.

**Comment by neil-marcellini** [comment]
The quick fix would be to revert https://github.com/Expensify/App/pull/9878/

**Comment by marcaaron** [comment]
>The root problem here is that you [cannot spread an object into an array](https://stackoverflow.com/questions/52789340/in-javascript-why-can-any-value-be-spread-in-an-object-but-not-in-an-array) unless it implements the iterable protocol.

Before you go down that rabbit hole. Earlier today we discovered that we are sending the wrong data type from the backend. Debugged this with @Julesssss  this morning and we added a change in this PR...

https://github.com/Expensify/Web-Expensify/pull/34278/commits/9bb9e3bce65bc44a773c3db1f4c80f2df3e3145c
https://github.com/Expensify/Web-Expensify/pull/34278/commits/1585a4894ed38b4fe25d59d519b192632225df3a

Are you on the latest `main` for Web-Expensify?

**Comment by marcaaron** [comment]
If I'm right, instead of reverting the App change - we could CP [this PR](https://github.com/Expensify/Web-Expensify/pull/34278) to production since it is `Production QA` anyway and nothing else is using the `OpenPaymentDetailsPage` yet.

**Comment by neil-marcellini** [comment]
Ooooh, thanks, I had no idea. I'll close the revert PR.
> Earlier today we discovered that we are sending the wrong data type from the backend. Debugged this with @Julesssss this morning and we added a change in this PR...

**Comment by neil-marcellini** [comment]
Now that I have the latest changes for Web-E I can't reproduce on dev, so yeah CP for that PR sounds like a good idea.

**Comment by mountiny** [comment]
Yeah, let's CP that Web-E PR, it makes it hard to identify other deploy blocker as problems cause by that Api changes keep showing up (but are misleading :D)

**Comment by mountiny** [comment]
@Expensify/applauseleads Can you please retest this one? It should be hopefully fixed.

**Comment by mvtglobally** [comment]
Issue is Fixed 

https://user-images.githubusercontent.com/43995119/180304394-f953e939-66ee-43db-b812-474838010251.mp4

**Comment by mountiny** [comment]
Thanks!
