### ISSUE TITLE
Log in/Log out - Console error are showing when log in and than log out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open the browser Console
3. Type your credentials
4. Go to Setting - Sign out

## Expected Result:
No Console error are showing when log in and than log out

## Actual Result:
Console error are showing when log in and than log out

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180442456-6e2fe38c-14c6-44a1-8e90-6d98f2614884.mp4

https://user-images.githubusercontent.com/93399543/180442458-d369d95b-3856-4c66-8b24-553bb94176ec.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I have confirmed locally that this has been fixed by this PR https://github.com/Expensify/App/pull/9956

We will CP it to staging now!
