### ISSUE TITLE
Web - Login/Logout - JS console errors are seen during login/logout

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Reload login page and check for JS console errors
2. Login with creds
3. Log out and check for JS console errors

## Expected Result:
There should be no JS console error during login/logout

## Actual Result:
Once login page is reloaded - JS console error is present.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):**  yuriy.turbo+ch5@gmail.com / Aa111111
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180492210-4fac2ef4-9356-45f9-b3dc-b29c168b475f.mp4

![Bug
![Bug5658747_Screenshot_2022-07-22_at_18 35 56](https://user-images.githubusercontent.com/43996225/180493097-8bca06f2-f2e3-43cd-a316-0ecf7954c1c4.png)
5658747_Screenshot_2022-07-22_at_18 41 49](https://user-images.githubusercontent.com/43996225/180492735-c0905b62-2559-45f9-b197-ec9ca2b92164.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![Bug5658747_Screenshot_2022-07-22_at_18 35 56](https://user-images.githubusercontent.com/43996225/180493281-731344b6-ca72-47e5-975f-e15b83545e21.png)

**Comment by kbecciv** [comment]
Duplicate https://github.com/Expensify/App/issues/10052
