### ISSUE TITLE
Create a generic "you don't have access" page

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#10067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# Problem
When you navigate to any page that you don't have access to, such as a report, we don't handle the situation gracefully. In some cases we show a growl message which we are trying to move away from because it can easily be missed.

# Solution
Create a generic "you don't have access" page. To start, make this page show when the user navigates directly via URL to a report that they don't have access to. When the user clicks the close button or the back button it will redirect back to the home page with either the last chat open or the concierge chat.

[Slack conversation](https://expensify.slack.com/archives/C02HWMSMZEC/p1658513093027329?thread_ts=1658422334.955699&cid=C02HWMSMZEC)

<img src="https://user-images.githubusercontent.com/26260477/180583765-228cdef3-f8bb-48c0-826a-73dad15cc175.png" width="200"/>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
Overall I like the approach. Though does the copy in the screenshot fit all situations? What if a non-admin accesses a page they don't have access to?

**Comment by neil-marcellini** [comment]
Today I figured out that we recently created very similar component in [this issue](https://github.com/Expensify/App/issues/9522). After some discussion [here](https://expensify.slack.com/archives/C02HWMSMZEC/p1658780985371179) we have decided to use that component instead and adapt it slightly for this use.
