### ISSUE TITLE
Workspace - User is unable to invite a new member under Manage members, invite message box is automatically scrolling up

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

#### Action Performed:
1. Go to staging.new.expensify.com
2. Log in with expensifail account
3. Go to Setting - Workspace
4. Click the Invite button

#### Expected Result:
User is able to invite a new member under Manage members, invite message is not moving up.

#### Actual Result:
User is unable to invite a new member under Manage members, invite message is moving up.

#### Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.1.86.0
**Reproducible in staging?:**  y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** any expensifail account
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** ![](https://user-images.githubusercontent.com/43996225/180879602-dd7a8387-a994-4ccf-ba6e-26dc4791ae3a.mp4)
**Issue reported by:** Applause internal team

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
also seems also related to the KeyboardAvoidingView thing.

**Comment by marcaaron** [comment]
Uh lol

https://user-images.githubusercontent.com/32969087/180894611-8713621e-19b5-4d41-a5f0-d4b32a8b21db.mp4
