### ISSUE TITLE
 Payments - User is taken to production flow for adding Personal bank account and VBA - Toggling staging server has no effect

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and login
2. Go to settings > preferences > toggle "use staging server"
3. Click payments > Bank account
4. Look for "Wells Fargo"
5. Search for the "Wells Fargo" and initiate

## Expected Result:
User should see "Wells Fargo" option and able to continue

## Actual Result:
Bank name is not available in the list and searching and continuing triggers production flow
NOTE: Looks like toggling staging server is not effective. (We are blocked with all the regression test case which require adding VBA)

## Workaround:
Unknwon

## Platform:

Where is this issue occurring?

- Web
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** n/a
**Email or phone of affected tester (no customers):** applausetester+0716mn@applause.expensifail.com /  Utest123
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180878819-ef9e9530-dcb2-4f65-8f44-c6e42bc95e3d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
I'm not fully sure we would hide something on staging servers. Will ask this in slack.

**Comment by danieldoglas** [comment]
This is related to this PR: https://github.com/Expensify/App/pull/9423

Since we moved plaid's logic from web-s to web-e, changing the flag to use staging on web-s won't do anything in this flow anymore. 

I'm putting this into a discussion that's happening right now about using staging env for web-e.

**Comment by luacmartins** [comment]
@danieldoglas So should this be tested in production now?

**Comment by danieldoglas** [comment]
I don't think Applause will have credentials for testing in production. There's a discussion ongoing right now. I think we'll actually send builds from staging pointing to staging soon. https://expensify.slack.com/archives/C03TQ48KC/p1658415135702599

**Comment by luacmartins** [comment]
Sounds good! So we are either fixing it by pointing our staging build to staging API or doing internal prodQA for these?

**Comment by danieldoglas** [comment]
moving this to weekly since it's in discussion

**Comment by iwiznia** [comment]
I think this will be solved by https://github.com/Expensify/App/issues/10163 right?

**Comment by danieldoglas** [comment]
it will! I'll close this and relate it on the other issue.

**Comment by danieldoglas** [comment]
Yep, that’s it!
