### ISSUE TITLE
Web - Line breaks & Text from code editor do not appear correctly within chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any valid account
3. Proceed to any chat
4. Copy and Paste "Text with Line breaks" and send in chat
5. Copy and paste "Text from a code editor" and send in chat

## Expected Result:
The user expects the text in chat preview to be exactly as copied.

## Actual Result:
The text does not comply with the correct format for either case

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** emilio.utest+293@gmail.com / Emilio98 or (Any email)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180883861-d9dd810e-edfc-464a-84ca-bb791b358119.mp4
https://user-images.githubusercontent.com/43996225/180883843-b69a379d-46b3-48dd-8b75-dc8041cf7033.mp4
https://user-images.githubusercontent.com/43996225/180883850-cdec387b-987b-4601-b735-874cc2308b87.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmdshrif** [comment]
@ctkochan22 to fix this we should  replace this line 
https://github.com/Expensify/App/blob/d1fda9f0b2da4db98e1e0d2c2b2f74f86d09e869/src/pages/home/report/ReportActionItemFragment.js#L123

with this 
```ts
      {StyleUtils.convertToLTR(Str.htmlDecode(text))}
```

this change start in this pr https://github.com/Expensify/App/pull/9834/files

**Comment by luacmartins** [comment]
@ctkochan22 any updates here?

**Comment by ctkochan22** [comment]
The recommendation by @ahmdshrif looks good. Just making sure it doesn't conflict with the PR that introduced it

**Comment by ctkochan22** [comment]
So the original issue was that when editing a message for a language written left to right, the `(edited)` splices the text right in half. 

Issue: https://github.com/Expensify/App/issues/9709
PR Fix: https://github.com/Expensify/App/pull/9834

I don't know why they would replace `props.fragment.text`
