### ISSUE TITLE
Android - Chat - Compose box is moving up when tap on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Select any chat
4. Tap on compose box

## Expected Result:
Compose box is not moving up when tap on it

## Actual Result:
Compose box is moving up when tap on it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180885917-f4214c85-77ff-4892-bf49-c8d4cffc9c10.mp4

https://user-images.githubusercontent.com/93399543/180887204-600ebbde-f68f-42f7-aed9-b32358643fa0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Seems possibly related to the KeyboardAvoidingView stuff. @jasperhuangg ?

**Comment by marcaaron** [comment]
I am having a hard time testing that theory because reverting [this PR](https://github.com/Expensify/App/pull/9895) comes with conflicts

**Comment by luacmartins** [comment]
Thanks for the updates @marcaaron. I think @jasperhuangg comes back from ooo tomorrow and will be able to assist us in reverting this?

**Comment by luacmartins** [comment]
This seems to have been fixed by [this revert](https://github.com/Expensify/App/pull/10113). Closing.

**Comment by marcaaron** [comment]
ah nice was just about to do this 🎉
