### ISSUE TITLE
[HOLD for payment 2022-08-11] [$250] Web - LHN - The wrong chat opens after resizing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Resize the window to a smaller view
4. Chat with any user and go back
5. Select one of the options (search, new group, request or send money) and press ESC

## Expected Result:
User is returned to LHN

## Actual Result:
User is returned to previously opened chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.86-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** Any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180893145-71c388af-9a26-4c35-a520-65b3f58214bf.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment]
I think this can be worked on externally.

**Comment by puneetlath** [comment]
External upwork job: https://www.upwork.com/jobs/~01abd25790afa78577
Internal upwork job: https://www.upwork.com/ab/applicants/1552030017614761984/job-details

**Comment by dave-amit** [comment]
I can fix it, don't know how at the time, but by exploring code I can fix it.

**Comment by syedsaroshfarrukhdot** [comment]
**Proposal**

https://github.com/Expensify/App/blob/151ec1ad3355cfa162ad490030f19a7134bbc076/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js#L44
https://github.com/Expensify/App/blob/151ec1ad3355cfa162ad490030f19a7134bbc076/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js#L48

The problem is the defaultStatus was set in intial state but was never updated  when screen resizes  to width of  isSmallScreenWidth which leads to the drawer close everytime 

**Solution**
We need to add componentDidUpdate and update defaultStatus on screen rezise to width of isSmallScreenWidth

  componentDidUpdate(prevProps) {
    // You don't have to do this check first, but it can help prevent an unneeded render
    if (prevProps !== this.props) {
      this.setState({
        defaultStatus: Navigation.getDefaultDrawerState(
          prevProps.isSmallScreenWidth,
        ),
      });
    }
  }

Before Video

https://user-images.githubusercontent.com/81307212/181160905-f1c4e7a0-8a80-4667-a238-101db3c25e84.mov

After Fixing
https://user-images.githubusercontent.com/81307212/181161187-304e6496-0fa4-4aa5-9e54-23ab48254a12.mov

**Comment by rushatgabhane** [comment]
@syedsaroshfarrukhdot the expected result is that the user is returned to LHN (Left hand navigator / page with all the chats)

But your proposal returns to a chat

**Comment by syedsaroshfarrukhdot** [comment]
> @syedsaroshfarrukhdot the expected result is that the user is returned to LHN (Left hand navigator / page with all the chats)
> 
> But your proposal returns to a previously opened chat

I Have Added Both Before And After Video Somehow After Solution Video Preview Is Not Working On First Comment So Adding It Again Here. It Is Returning To LHN With All Chats.

https://user-images.githubusercontent.com/81307212/181254844-dc6877cd-7c6c-4c7f-8ceb-137745af9147.mov

**Comment by rushatgabhane** [comment]
Oh haha
@syedsaroshfarrukhdot's proposal looks good!

@Julesssss C+ reviewed 🎀 👀 🎀

**Comment by syedsaroshfarrukhdot** [comment]
I have applied to the job in upwork hopefully the PR will be ready for review by tommorow (29th July 2022). I will be posting on GitHub issue once PR is ready.

**Comment by Julesssss** [comment]
Thanks @syedsaroshfarrukhdot, sounds good!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment]
Paid @syedsaroshfarrukhdot. 

Sent contract to @rushatgabhane for C+.

**Comment by puneetlath** [comment]
Everyone has been paid. Thanks everyone!
