### ISSUE TITLE
Android - Setting - Page is jumping after tap "Add email" and unable to close account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Go to Setting - Profile
4. Tap on Add phone number or Add email Address ( app is jumping)
5. Go to Security - Close account
6. Tap on enter email field ( keyboard is dismissing)

## Expected Result:
App is not jumping after tap "Add email" and able to close account

## Actual Result:
App is jumping after tap "Add email" and unable to close account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com / Feya86Katya (or) any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/180901295-fb4b4280-ae03-44d8-89fa-713a3e45b037.mp4

https://user-images.githubusercontent.com/43996225/180901297-95d8fea3-d149-454b-9380-28e09e587759.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Possibly related to https://github.com/Expensify/App/pull/9895? @jasperhuangg

**Comment by luacmartins** [comment]
@jasperhuangg I'll assign you for now, feel free to reassign if it ends up not being related to your PR.

**Comment by marcaaron** [comment]
ya seems related to KeyboardAvoidingView stuff.

**Comment by luacmartins** [comment]
This seems to have been fixed by [this revert](https://github.com/Expensify/App/pull/10113). Closing!
