### ISSUE TITLE
Web - LHN - User name with quotes is displayed incorrectly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre condition : The chat must have users whose name contains quotation marks
1. Go to URL https://staging.new.expensify.com/
2. Turn off your wifi
3. Turn on your wifi

## Expected Result:
The user whose name contains quotes (" ") should be displayed correctly

## Actual Result:
The user whose name contains quotes (" ") is initially displayed with strange characters

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180888608-38d59929-8f06-4d38-9253-fb03c7b60182.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
I can reproduce this, working on it. For some reason, the issue occurs when we display `displayName` which get displayed incorrectly then the code switches to displaying `firstName`.

![Screen Shot 2022-07-28 at 01 15 37](https://user-images.githubusercontent.com/9680864/182672172-d1c70608-63d3-4aba-a57d-94aabaa05e89.png)
.

**Comment by youssef-lr** [comment]
@Gonals sorry was meaning to unassign myself and I unassigned you!

**Comment by thienlnam** [comment]
Thanks for the investigation @youssef-lr! It looks like we're sanitizing the quotes and they're being converted into &quot; in the display name. Ideally we want to fix that first but also the switching from first to display name is also weird.

Will look into it later this week

**Comment by thienlnam** [comment]
Haven't had time to look into this, there's likely a bug that causes a switch from displayName to first name when going offline / back online.

**Comment by sobitneupane** [comment]
This issue might be related to this bug I posted few days ago in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1662394376243499). It is reproducible without going offline. Quotes are appearing as `&quot;` in LHN, header, details page, Settings Page and Profile Page but working fine in Chat or Report.

**Screenshots:**
**Working fine in chat/report**
<img width="350" alt="Screen Shot 2022-09-26 at 11 53 46" src="https://user-images.githubusercontent.com/25876548/192204949-e019db33-f376-497b-a5ad-d23d61d5f941.png">
**Bug exists in Header, LHN, Details Page and Profile Page**
<img width="350" src="https://user-images.githubusercontent.com/25876548/192204809-31fe95a5-bab6-4925-accd-f5519ed67d05.png" />
<img width="1440" alt="Screen Shot 2022-09-26 at 11 54 40" src="https://user-images.githubusercontent.com/25876548/192205111-0c17d733-8f99-4026-a58c-597a536d5a47.png">

**Comment by iwiznia** [comment]
OH GOD NO!!! 
Why are we doing [this](https://github.com/Expensify/Web-Expensify/pull/21441/files#diff-6eb37b3ba564b40f518fdd0caf70c67595ca8e5dd51a580d6f8da8c762657110R45). That's wrong. API should never HTML escape/quote/specialchars the data it returns, that's the responsibility of the frontend.

I think now we will need to:
- Undo that change
- Ensure we escape the name everywhere in oldDot

There's no issue in newDot really, it is doing what it should.

**Comment by johnmlee101** [comment]
Oh yeah that was a weird XSS bug where the pentesters would split a problematic XSS into 2 parts, like `<script` and `>executebadCode()` in the first and last name fields, where when we would combine them in the front end it would end up injecting code. 

I think the idea was that it was a faster fix for something that was very critical than trying to find all references to personal details and patch the front end. My recommendation is we could open up unescaped characters like we do for the whitelist but instead for NewDot, patch OldDot so that front end escapes these characters, then finally open everyone up to the unescaped details?

**Comment by iwiznia** [comment]
Thinking about it, I see 2 alternatives:
1. We fix oldDot code (the way you propose it sounds fine)
1. We apply a hack only for newDot and then when we eventually kill oldDot remove the hack

Maybe we should just do 2? It's shitty, but oldDot will be eventually replaced.

**Comment by johnmlee101** [comment]
Yeah # 2 and make a nice comment explaining why and what to do during reunification 😄

**Comment by iwiznia** [comment]
Taking it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Closing
