### ISSUE TITLE
Chat- OpenApp does not return an Onyx update object for key: fakePolicyID with value: null after refreshing the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9906
## Action Performed:
1. Open your browser console
2. Sign in to the App
3. Verify that OpenApp returns an Onyx update object, i.e. key: policy_<POLICY_ID> for each policy in your test account
4. Disable internet connect and enable it again
5. Verify that ReconnectApp returns an Onyx update object, i.e. key: policy_<POLICY_ID> for each policy in your test account
6. Refresh the App and verify that OpenApp returns an Onyx update object for key: fakePolicyID with value: null

## Expected Result:
OpenApp should returns an Onyx update object for key: fakePolicyID with value: null

## Actual Result:
OpenApp isn't returns an Onyx update object for key: fakePolicyID with value: null

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.86-0

**Reproducible in staging?:**  Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img width="1126" alt="Bug5662949_Screen_Shot_2022-07-25_at_8 34 20_PM" src="https://user-images.githubusercontent.com/43996225/180914035-59b36882-91ee-4bf9-81a8-dd13ac042dd4.png">
<img width="1115" alt="Bug5662949_Screen_Shot_2022-07-25_at_8 36 40_PM" src="https://user-images.githubusercontent.com/43996225/180914038-49fa93c9-82f3-4ccd-b2b7-47e119f9cbfe.png">

https://user-images.githubusercontent.com/43996225/180914042-e7a3ad7d-1312-42b9-9b93-dd5442d680fa.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Hmm this is likely to the fact that we pass an empty list to the server [here](https://github.com/Expensify/App/blob/99d5dc3970c1ec62b55ef767349cef3fddc863ed/src/libs/actions/App.js#L130). We should probably fix that and only send non-empty lists. @marcochavezf do you want to take this one?

**Comment by marcochavezf** [comment]
Sure! I will take this one, thanks for pointing out where we should check the empty list!

**Comment by marcochavezf** [comment]
Ah the `fakePolicyID` with value `null` only appears when it's tested locally by following step 7 of https://github.com/Expensify/App/pull/9906. This works as expected when `fakePolicyID` is hardcoded from the local server as stated in the instructions:

<img width="884" alt="Screen Shot 2022-08-02 at 14 59 01" src="https://user-images.githubusercontent.com/6829422/182462454-4eaf4f4d-b214-4581-b452-f600ade7034e.png">
