### ISSUE TITLE
Workspace - Spanish - Decimal separator comma is missing on the keyboard and dot is non functional on keyboard 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10108]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #9800
## Action Performed:
1. Launch App and login with Expensify account
2. Change language to Spanish
3. Open Settings > Workspace > Reimburse expenses

## Expected Result:
Verify that it's possible to enter a decimal number with three digits after the comma into Rate input

## Actual Result:
Impossible to enter a decimal number into Rate input since comma  is not available in the keyboard. The dot is non functional on the keyboard.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.86-1 

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

<img src="https://user-images.githubusercontent.com/43996225/181038269-a2a3d7f9-ac66-489a-8880-66da17da7579.jpeg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/181038279-76b63343-ce2b-4a81-a2a7-9c32c2a9f25f.jpeg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Santhosh-Sellavel** [comment]
I've already found it check [here](https://github.com/Expensify/App/issues/9497#issuecomment-1190658490) this will be addressed in a followup PR.

**Comment by yuwenmemon** [comment]
Okay great, assigning to you @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
Not overdue

**Comment by Santhosh-Sellavel** [comment]
Not overdue discussion going on in slack

**Comment by Santhosh-Sellavel** [comment]
Not overdue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Santhosh-Sellavel** [comment]
PR is live

**Comment by Santhosh-Sellavel** [comment]
Not overdue PR is up

**Comment by Santhosh-Sellavel** [comment]
PR is up already

**Comment by Santhosh-Sellavel** [comment]
PR is yet to be merged.

**Comment by Santhosh-Sellavel** [comment]
PR is deployed

**Comment by Santhosh-Sellavel** [comment]
Fixed now, and should be closed!
