### ISSUE TITLE
[$250] Update electron-builder package to latest version 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#10119]
## Action Performed:
Check which version of electron builder is [here](https://github.com/electron-userland/electron-builder/releases/tag/v23.3.1). (You can csee what version we are using by running the command `npm list ejs`)

## Expected Result:
The version used by Expensify should match the latest version listed [here](https://github.com/electron-userland/electron-builder/releases/tag/v23.3.1)

## Actual Result:
Expensify currently uses electron-builder version 22.13.1

## Workaround:
na

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)"

**Comment by MitchExpensify** [comment]
Hey @Christinadobrzyn! This [issue](https://github.com/Expensify/Expensify/issues/218330#issuecomment-1188231841) was discussed here as likely a great external candidate

**Comment by Christinadobrzyn** [comment]
Just running this past eng per our triage workflow! If it's good for a contributor please add the External label!

**Comment by Gonals** [comment]
I think it can be!

**Comment by Christinadobrzyn** [comment]
I think the original post has all the needed information for the contributor (thanks Mitch!) so created job in Upwork

- Internal job posting - https://www.upwork.com/ab/applicants/1552305715407474688/job-details
- External job positing - https://www.upwork.com/jobs/~018f65f7ebd618c2c9

waiting for proposals!

**Comment by dennismunene** [comment]
PROPOSAL :

Bumping the version in package.json should do the trick. 

https://github.com/Expensify/App/blob/53bff65ad45e59348d506538b9b8226751bcea01/package.json#L154

to 

```
    "electron-builder": "^23.3.1",

```
After Running `npm list ejs`
<img width="481" alt="Screenshot 2022-07-28 at 22 06 20" src="https://user-images.githubusercontent.com/4717301/181618505-f45e925e-e158-4093-8628-3e1e14219a6e.png">

**Comment by parasharrajat** [comment]
Ok. I see. This is straightforward. I like @dennismunene's proposal. You will have to provide the following on the PR. 
1. Changelog in a comment. 
2. Research data if upgrading has affected any of the features that we are using. 
3. Test videos and steps for all the things that depend on this. 

Do then the app signing. It should not break.

**Comment by Beamanator** [comment]
Agreed with the requirements mentioned by @parasharrajat ^ - let's do this!

**Comment by dennismunene** [comment]
Raised PR https://github.com/Expensify/App/pull/10159

**Comment by Christinadobrzyn** [comment]
Hired @dennismunene for the fix in Upwork ($250)
Hired @parasharrajat as the C+ in Upwork ($250) 

PR in review - https://github.com/Expensify/App/pull/10159

**Comment by Christinadobrzyn** [comment]
working on the [PR](https://github.com/Expensify/App/pull/10159)

**Comment by Beamanator** [comment]
@Christinadobrzyn I believe this is ready to be paid out and closed! It was mentioned [here](https://github.com/Expensify/App/pull/10159#issuecomment-1232679296) that the changes worked, in production 👍

**Comment by Christinadobrzyn** [comment]
Thanks @Beamanator! 

- Paid @dennismunene $250 for the job & @parasharrajat $250 as C+ in Upwork. 
- Closed job in Upwork
- Closing this GH as complete
