### ISSUE TITLE
New lines are stripped out and forced into a single line

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. Write a message with new line breaks

## Expected Result:
Sent message should have new line breaks

## Actual Result:
New lines are forced into single line

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.86-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/181281689-bfa64741-d2b9-4d69-a907-ffb59150cc6a.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @johnmlee101  @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658850192431019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is not reproducible in the latest staging build!

**Comment by luacmartins** [comment]
Reproduced on v1.1.86-0, but not on 1.1.86-5. It seems to have been fixed! Gonna close this issue!
