### ISSUE TITLE
Toggling Show/hide password for couple of times selecting below component text automatically- Reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in browser (Chrome, Safari)
2. Open setting drawer go to Security -> Change Password
3. Type password or even on empty password field -> Press show/hide password (couple of times)

## Expected Result:
Should no select any text

## Actual Result:
Toggling password select’s below component text automatically

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/182293257-1121dfaa-fc49-4498-95e2-8877baae13e3.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657598555928569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
Honestly this seems very small priority. cc @Julesssss wondering if you agree and we should just close this out

**Comment by Julesssss** [comment]
Yeah, totally agree.
