### ISSUE TITLE
Composer text not aligned vertically centre for native app - reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in iOS app
2. Go to any chat
3. Type message in composer notice text written is aligned more to bottom rather than centre vertically

## Expected Result:
Text should be proper aligned to vertically centre

## Actual Result:
Text not aligned to vertically centre

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="653" alt="textAlign" src="https://user-images.githubusercontent.com/43995119/182295342-6e30a445-a577-4df7-8306-33366d1149bc.png">
![Screenshot_20220728-052649](https://user-images.githubusercontent.com/43995119/182298645-32277681-3ae3-4792-87dc-79ac980b0789.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** dhairyasenjaliya @roryabraham  
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657875961211239
https://expensify.slack.com/archives/C01GTK53T8Q/p1659011710209859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
For the avoidance of doubt, can we confirm in the OP for the contributor what the padding should be? it's 6px top and bottom isn't it? CC: @shawnborton 

I'm also curious what PR broke this, I took a cursory look at recent ones and perhaps [this](https://github.com/Expensify/App/pull/9839)?

**Comment by trjExpensify** [comment]
😱 whaaaat is going on?

**Comment by Julesssss** [comment]
STOP

**Comment by dhairyasenjaliya** [comment]
oh my bot haha

**Comment by trjExpensify** [comment]
Deleted the comment, didn't work.

**Comment by Julesssss** [comment]
hmm, did it stop by itself 8 minutes ago?!

**Comment by trjExpensify** [comment]
Due to Melv's antics this morning, closing this out and recreated it here to test the fix for the comment loop: https://github.com/Expensify/App/issues/10202
