### ISSUE TITLE
[$1000] User is able to scroll forever after opening Android app 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10187]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Scroll the chats

## Expected Result:
User should be able to scroll to the top 

## Actual Result:
User is able to scroll down forever

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![WhatsApp Image 2022-07-28 at 3 52 46 PM (1)](https://user-images.githubusercontent.com/43995119/182299319-51562843-55cb-4178-9ec1-545bf43c77cf.jpeg)

https://user-images.githubusercontent.com/43995119/182299332-ad9ca318-261d-4c18-ae8e-44066e8c3aeb.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Justicea83 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659023678387269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This can be External

**Comment by Christinadobrzyn** [comment]
Job posted in Upwork! 

External posting - https://www.upwork.com/jobs/~01d0dc6f6881cebc48
Internal posting - https://www.upwork.com/ab/applicants/1554595091182915584/job-details

**Comment by Christinadobrzyn** [comment]
price increase to $500 - still waiting on proposals

**Comment by Christinadobrzyn** [comment]
Price doubled to $1000

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Gonals** [comment]
Not overdue! (And maybe already gone!)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by wildan-m** [comment]
Not reproduceable at commit 41ec9bd371c4f2c2ea63a1ecf922abb6e9789bd5

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Are we ok to close?

**Comment by Gonals** [comment]
Yeah! Let's do it

**Comment by Christinadobrzyn** [comment]
Closed the job in Upwork. @rushatgabhane please feel free to let me know if you did any work on this issue that should be compensated. Thanks!
