### ISSUE TITLE
Copying formatted code is not working as expected

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Copy code from a code block comment (text surrounded by 3 backticks)
2. Try pasting it without formatting (CMD+SHIFT+OPTION+V in os X)
3. See how it includes the 3 backticks

## Expected Result:
user should be able to send code 

## Actual Result:
the format is being included as text, you can't paste it with format anywhere and you can't really paste it without format either.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="826" alt="Screen Shot 2022-08-02 at 1 44 09 AM" src="https://user-images.githubusercontent.com/43995119/182300622-33204ccb-87a7-47bc-b52a-69855d02f59d.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659120334379329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment]
Happening on 1.1.86-5 as well. Looks good to go external

**Comment by parasharrajat** [comment]
The PR with the fix is just merged on https://github.com/Expensify/App/pull/9880. It should be fixed soon.

**Comment by arielgreen** [comment]
Are we ok to close this, then?

**Comment by arielgreen** [comment]
Merged so closing.
