### ISSUE TITLE
the monthly statement is still using incorrect fonts

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Wait for the monthly statement to arrive 
2. Check the statement 

## Expected Result:
Fonts should match design docs 

## Actual Result:
The option rows seem wrong, but the paragraph text is okay

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659322153586889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
cc @thienlnam

**Comment by thienlnam** [comment]
Internal since the statement is hosted from OldDot

**Comment by thienlnam** [comment]
No update - been prioritizing N7 items

**Comment by thienlnam** [comment]
Actually, going to unassign for someone else to take - if it's not assigned by then I'll pick it up again

**Comment by thienlnam** [comment]
Not a priority

**Comment by puneetlath** [comment]
@thienlnam I removed and re-added the bug label to get a BZ team member added who can help move this forward.

**Comment by greg-schroeder** [comment]
Hmm - seems like this is `Internal` based on the earlier discussion, so I suppose I should just re-assign `Engineering` in that case. 🤔

**Comment by greg-schroeder** [comment]
What are your thoughts on potential progress here @thienlnam? Would it be helpful to get someone else on the team on this?

**Comment by kevinksullivan** [comment]
Going to change this to monthly to avoid pings. As someone that worked on p2p I agree this does not need to be fixed right now.

**Comment by JmillsExpensify** [comment]
Rather than change this to monthly why don't we just close this? No one is going to run into this bug for a really long time, so I struggle to say it's a bug at all. Another benefit of closing this is that it's easy for everyone to find the actual bugs that need to be worked on.

**Comment by thienlnam** [comment]
Yeah thats fine, let's revisit this once P2P is back on the horizon but we can close this for #focus on WAQ
