### ISSUE TITLE
Android - Settings-Time zone is not updating after Saved changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/9696 

## Action Performed:
1. Launch the app
2. Log in with account
3. Go to Setting - Profile
4. Unselect the check mark " Set my time zone automatically"
5. Select any other time zone
6. Tap Save 
7. Go back to Setting  - Profile
8. Check your timezone

## Expected Result:
Time zone is updating after Saved changes

## Actual Result:
Time zone is not updating after Saved changes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182480084-b29a1883-6d08-4678-8145-d700f8153c6f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment]
@Beamanator wondering if you have any insight into this...

**Comment by Beamanator** [comment]
Oofda yeah I'll look into this :'(

**Comment by Beamanator** [comment]
Aah ok so it's not re-rendering when this is updated - if you refresh the new values are shown

**Comment by Beamanator** [comment]
I can take over this one
