### ISSUE TITLE
Security - Close Account - No growl is received when closing an account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10224]
### If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com OR open the desktop mac app
2. Sign into a public domain account
3. Click on the Profile icon > Security > Close account
4. Input the correct information in the fields and proceed with the "close account" button in red.

## Expected Result:
The user expects to be navigated to the Sign in page and receive a growl so that they may now their actions were successful.

## Actual Result:
The user is redirected correctly but no growl was received.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** No
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182512465-4264e6be-1062-493b-a158-db2479da0a52.mp4

https://user-images.githubusercontent.com/93399543/182512469-b3120476-bc91-40a7-8e2f-8edb54332a88.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
@Beamanator looks like it is coming from https://github.com/Expensify/App/pull/9635
I think it would be better to display growl in this case that action is successful. What do you think?

**Comment by MonilBhavsar** [comment]
cc @Julesssss as it appears like Alex is OOO today and this is hourly issue

**Comment by parasharrajat** [comment]
There was a confirmation modal.

**Comment by Beamanator** [comment]
I was ooo most of yesterday, back today! I'm not sure this growl was necessary, i'll take a look at the design doc where this refactor happened to see if this detail was missed or if it's expected we don't show the growl

**Comment by Beamanator** [comment]
Ok the confirmation Growl wasn't specifically discussed in the doc, but I don't think the Growl is necessary. We automatically redirect the user to the sign in screen when they close their account, that should be good enough. I would say we just need to update the regression test steps to not look for the growl anymore

**Comment by Julesssss** [comment]
> There was a confirmation modal.

Yeah, there was. IIRC the 'type your account details' was a replacement for this step though. 

I also kinda think the growl should exist though. Regardless, it shouldn't be a deployblocker.

**Comment by Beamanator** [comment]
> Yeah, there was. IIRC the 'type your account details' was a replacement for this step though.

I think you're right about this one. In the PR you can see that the only modal I changed was the error modal, not any confirm modal

> I also kinda think the growl should exist though. Regardless, it shouldn't be a deployblocker.

Agree it should be a deploy blocker, the growl could make sense too - I think we are mainly trying to avoid growls now'days because they're only showing for a limited time and .. some other reasons I forget? But if you close your account, you get logged out and it doesn't really matter if you don't see the growl right?

**Comment by Julesssss** [comment]
I view this as an exception to the no growl rule as closing an account is an incredibly rare and important event. Also, when testing I did notice that there wasn't any feedback and it felt a bit odd -- almost like there had been an error.

**Comment by Beamanator** [comment]
I'm ok with either way - growl or no growl. I don't find it confusing that "close account" takes you back to the sign in page w/out a growl but I wouldn't be opposed to adding one there

**Comment by MonilBhavsar** [comment]
Agree 👍 this seems like a "no growl" exception and we should add one to indicate that action succeeded.

**Comment by MonilBhavsar** [comment]
Engaged in N07, will update soon

**Comment by MonilBhavsar** [comment]
Will get back next week!

**Comment by MonilBhavsar** [comment]
Working on it now!

**Comment by MonilBhavsar** [comment]
I had a look at the User_Delete flow and the [design doc](https://docs.google.com/document/d/1i8YQApRXOC1vWl4LMBUq4vHmA-58rNtVwn8gWpvLao0/edit#). I thought of displaying a growl after we make a Write request [here](https://github.com/Expensify/App/blob/c9fb793477266498bb4c407fe66dc7674f6ee4f4/src/libs/actions/User.js#L79) but realized we can't be optimistic that account will be deleted every time as we many checks [here](https://docs.google.com/document/d/1i8YQApRXOC1vWl4LMBUq4vHmA-58rNtVwn8gWpvLao0/edit#heading=h.1868o6ru867s) before deleting the account. So, I think the only way to add a growl is to make it use makeRequestWithSideEffects instead of Write. I'm not sure if we really want to change request type just to display growl.
@Beamanator @Julesssss thoughts? Should I bring this in slack, or :donothing:?

**Comment by Beamanator** [comment]
I think this could be a good convo to bring to slack, since:
1. As you mentioned, we try not to use `makeRequestWithSideEffects` when possible
2. Some people are adamant about not using Growls in our product, so maybe there's some other kind of message / notification we can display to the user

**Comment by MonilBhavsar** [comment]
Discussing here https://expensify.slack.com/archives/C03TQ48KC/p1663931636325039

**Comment by MonilBhavsar** [comment]
So when we push onyx update to clients, we can pass a message in ACCOUNT Onyx key and display it to user.

Here I tried displaying it on Login page.

<img width="952" alt="Screenshot 2022-10-07 at 3 30 48 PM" src="https://user-images.githubusercontent.com/32012005/194528577-5b4b6de9-9ed0-4e8d-928e-774fe9e9d446.png">

@Expensify/design Please review and share your thoughts.
Context: When user closes their account and it is successful, they're redirected to login page. We want to display a message to tell them that their account is closed.
As in the screenshot above, I think we can display a message on the login page, Or make a new page with a message and a button to redirect to signin page.

**Comment by Beamanator** [comment]
FYI we have an onyx key `closeAccount` so maybe we can use that instead of ACCOUNT?

**Comment by MonilBhavsar** [comment]
Yeah, that will be better 👍

**Comment by michelle-thompson** [comment]
Does `closeAccount` mean the account was deleted or the user logged out?

**Comment by michelle-thompson** [comment]
I think the above screenshot looks good 👍
