### ISSUE TITLE
[Performance] Sidebar Performance at Scale

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#10248]
## What performance issue do we need to solve?

OptionsListUtils and SidebarLinks are pretty slow and the issues get worse as you increase the number of reports. 

As recently discovered in [this fire](https://expensify.slack.com/archives/C03SYCHD988).

## What is the impact of this on end-users?

Slow boot time, slow chat switching, in some extreme cases inability to use the app.

## Proposed solution (if any)

Steps we should take in order of priority...

- Memoization can help with performing unnecessary re-calculations
- Make more holistic improvements to how options are calculated to remove other bottlenecks
- Long term we need to implement some kind of pagination

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platform:

I assume everywhere.

**Version Number:** v1.1.87-8
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by CortneyOfstad** [comment]
@marcaaron Just checking to see if this is still occurring, or if this can be closed? Thanks!

**Comment by CortneyOfstad** [comment]
@marcaaron appears to be OoO. Closing until they return. 

Feel free to reopen if issue is still occurring!
