### ISSUE TITLE
Login - There is No phone number is +15005550006 at the error when typed 2 digits and continue

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/8511

## Action Performed:
1. Go to staging.new.expensify.com
2. Type 2 digits and continue
3. Verify that the phone number is +15005550006 at the error

## Expected Result:
There is phone number is +15005550006 at the error when typed 2 digits and continue

## Actual Result:
There is No phone number is +15005550006 at the error when typed 2 digits and continue

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** none

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://user-images.githubusercontent.com/93399543/183114396-82f697dd-c4a5-4f2c-ab43-abf5406b917f.mp4

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
@kbecciv the video evidence for this is for a different issue? I cannot reproduce otherwise

**Comment by kbecciv** [comment]
@johnmlee101 Sorry about that, updated correct video.

**Comment by johnmlee101** [comment]
Okay to clarify the issue is that the error message doesn't pop up for invalid numbers, not that "No phone number is +15005550006"

**Comment by johnmlee101** [comment]
I think this is caused by https://github.com/Expensify/App/commit/cd4081848a849e9b9821509e86a21477057660d1 cc @yuwenmemon

**Comment by yuwenmemon** [comment]
Okay looked into this for a bit, but a lot has changed (and is changing) with regards to error handling and Onyx so I'm just going to revert that previous PR to get the error handling right

**Comment by yuwenmemon** [comment]
Reverted the offending PR
