### ISSUE TITLE
iOS/Safari - The smart banner is NOT shown on all pages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #10070
## Action Performed:
1. Open the app in mWeb Safari
2. Check for availability The smart banner

## Expected Result:
The smart banner is shown on all pages

## Actual Result:
The smart banner is NOT shown on workspace settings page and from FAB (New chat, New group and New room)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** v1.1.88-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/183096603-5c48b920-7bc1-4c5a-9af6-5ffbf861c62f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
We are reverting the PR so we can close this one https://github.com/Expensify/App/pull/10070
