### ISSUE TITLE
Workspace - The "Get started" modal does not popup in the workspace when redirected from OldDot

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #10172 

## Action Performed:
1. Sign up with new account on OldDot
2. Select "Get Started" in WelcomeUser inbox task
3. Get directed to NewDot

## Expected Result:
 "Get Started" in the new workspace modal and the "Add bank account" modal will pop up

## Actual Result:
 "Get Started" modal does not appear 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.88-1
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1058" alt="Bug5676876_Screen_Shot_2022-08-05_at_9 16 39_AM" src="https://user-images.githubusercontent.com/43996225/183108060-72674b2c-edb1-4b91-a960-760d67653909.png">

https://user-images.githubusercontent.com/43996225/183108069-a336eac8-1452-4ef2-8c6a-7fb7e4abaf9b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
Spoke to @marcaaron. The linked PR did not cause any issues. And the modal does necessarily show up all the time.
