### ISSUE TITLE
Workspace Navigation - Tapping back arrow from features page takes user to workspace initial page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10278]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and login
2. Go to workspace > Reimburse expenses
3. Click on "Connect bank account"
4. Tap back arrow

## Expected Result:
User is taken back to "Reimburse expense"

## Actual Result:
User is taken back to workspace editor page
NOTE: This happens with Pay bills, send invoices, book travel pages

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183158666-2a7f9036-7994-43e4-a95e-a3e6c5fca087.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
I'm able to reproduce the issue. Updating the issue title to make it a general issue

**Comment by MonilBhavsar** [comment]
Made a quick fix while investigating the issue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by MonilBhavsar** [comment]
Closing this issue. Feel free to reopen if we see this issue again.
