### ISSUE TITLE
mweb - Old dot - User gets infinite loading when opening a WS from "Current Plan" option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User already has an existing workspace created
1. Open the Old Dot app
2. Sign into a valid account (Expensifail)
3. Navigate to "Settings" and tap on "View all" on the policies section
4. Tap on the "Group" tab
5. Tap on the "Edit" button next to a Workspace
6. Tap on the "Current Plan" option inside the workspace settings

## Expected Result:
The user is redirected to NewDot on mWeb with the correct workspace settings page open.

## Actual Result:
The user receives infinite loading and the workspace is not created.
EXTRA: Happens when the user is signed out of New dot, signed in with the same account or signed in with a different account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applauseteser+emilio@applause.expensifail.com/Emilio98

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183218489-60693c93-75cb-4a17-9eca-467e3fef2dc4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
I was able to reproduce this from scratch with the following steps:
1. Create a new user in olddot web
2. Validate the account
3. Create a Free plan Workspace/Policy
4. Log into the olddot app with the new test account
5. Navigate to Settings > Policies > View All > Edit (on the workspace policy) > Current Plan
6. User is redirected to mobile web and is shown an endless spinner

Because this is reproducible from scratch, I am applying the Demolition label and un-assigning myself.

**Comment by stitesExpensify** [comment]
No update yet, i'll probably get a chance to look at it this week

**Comment by stitesExpensify** [comment]
No update

**Comment by stitesExpensify** [comment]
No update. Focused on n7

**Comment by stitesExpensify** [comment]
Same as :that:

**Comment by stitesExpensify** [comment]
No update

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by stitesExpensify** [comment]
No update, but seems un-reproducible. We'll wait and see if it comes back

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Closing
