### ISSUE TITLE
[$250] When deleting an emoji flag in the Last Name settings field, it changes from the national flag to black on

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App on Web (I used chrome)
2. Navigate to Settings > Profile 
3. Click on Last Name 
4. Enter last name with either Scottish, English or Welsh flags (subdivision of emojis https://emojipedia.org/emoji-tag-sequence/)
5. Click backspace to Delete emoji  

## Expected Result:
Clicking a backspace once will delete the emoji

## Actual Result:
When deleting an emoji flag in the Last Name settings field, it changes from the national flag to black on and then you have to click delete 6 times (presumably the number of chars the emoji is represented with) to actually delete the flag emoji.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/183333017-3847e2dd-03a0-4604-845d-650d666484b2.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659275951857989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Sorry Bondy, got pinged because I reported this. This can definitely be External issue so moving it on to get exported! Thanks!

**Comment by Christinadobrzyn** [comment]
Hey @mountiny I can't seem to replicate this. I'm using Version 1.1.87-9 (1.1.87-9) - most updated available version for me. Is that maybe the reason why?

**Comment by mountiny** [comment]
@Christinadobrzyn interesting, what platform you using, flag flag/emoji you trying?

**Comment by mountiny** [comment]
Ah I can still replicate on staging using a Scottish flag, I think you need to use non-standard flag.

I looked into this a bit more and it is Only Scotland, England, Wales 😂  https://emojipedia.org/flags/ https://emojipedia.org/emoji-tag-sequence/

<img width="644" alt="image" src="https://user-images.githubusercontent.com/36083550/183380671-b2d91a47-8aba-477c-9434-b185106d3718.png">


I think we should still try to look into fixing this, but I will make this monthly and update the issue description

**Comment by KingStar1001** [comment]
https://manzoorwani.dev/how-we-brought-down-github-actions-workflow-execution-time-from-20-minutes-to-5-minutes/
This will be helpful for this issue.

**Comment by mountiny** [comment]
@KingStar1001 I am afraid this is an incorrect link :/

**Comment by KingStar1001** [comment]
@mountiny What do you mean? is it not working?

**Comment by mountiny** [comment]
The article linked is about Github CI, this issue is about flag emojis

**Comment by KingStar1001** [comment]
@mountiny Oh, sorry. I have a mistake. this is solution for [other issue.](https://github.com/Expensify/App/issues/10289).

**Comment by mountiny** [comment]
Np, thanks!

**Comment by Christinadobrzyn** [comment]
> @Christinadobrzyn interesting, what platform you using, flag/emoji you trying?

I wasn't able to replicate in staging on: 

- Desktop app > choosing the Australia flag
- iphone app > choosing the Scotland flag

**Comment by Christinadobrzyn** [comment]
Created job in Upwork! 

Internal posting - https://www.upwork.com/ab/applicants/1556854078691786752/job-details
External posting - https://www.upwork.com/jobs/~010f6df374de0fee0f

**Comment by mountiny** [comment]
This has picked you Aldo, because I am ooo in the calendar, but I can take this on as CME 🙌

**Comment by mountiny** [comment]
@Christinadobrzyn I cannot repro on iOS either, but I can still repro in web Chrome using the native mac emoji keyboard.

I will update the description.

I will keep this monthly and I think we should not increase the price here as this is very low priority 😄

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mountiny** [comment]
@mvtglobally I can still repro in staging  :/

**Comment by mvtglobally** [comment]
@mountiny You are right, its repro. It doesn't happen with all emojis it seems, so team got a bit confused with flags

**Comment by mountiny** [comment]
Correct as the Issue body says:

> Enter last name with either Scottish, English or Welsh flags (subdivision of emojis https://emojipedia.org/emoji-tag-sequence/)

It is few flags 😄 hence this is monthly

**Comment by mountiny** [comment]
Still waiting for proposals, no need to raise the price here due to low importance

**Comment by mountiny** [comment]
Ok, closing this one out as this is really extreme edge case and it does not break the app so I think we can do nothing at the moment. Thanks!

**Comment by priyeshshah11** [comment]
@mountiny I have a solution for this, are you open to proposals?

**Comment by mountiny** [comment]
@priyeshshah11 hello! This issue is closed and not a priority now. Once we would open this later in future (possibly), please share the proposal there. Thank for understanding

**Comment by mountiny** [comment]
@priyeshshah11 hello! This issue is closed and not a priority now. Once we would open this later in future (possibly), please share the proposal there. Thank for understanding
