### ISSUE TITLE
[HOLD for payment 2022-11-04] [$250] Touching/clicking on emoji picker in edit message closes the keyboard - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10290]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Website in mWeb
2. Open chat > send a message > edit message
3. Click/Touch on emoji picker.

## Expected Result:
It should directly open the emoji picker instead of closing keyboard.

## Actual Result:
It closes the keyboard.

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/183329931-cf9a3c39-a84a-4543-a333-18ae01bb5669.mov

**Expensify/Expensify Issue URL:** 
related to https://github.com/Expensify/App/issues/9252

**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654979150171379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
Looks like this can be external.

**Comment by Tushu17** [comment]
I want to clarify a thing here, the bug [#9252](https://github.com/Expensify/App/issues/9252) and this bug are completely different bugs as:- 
1.  [#9252](https://github.com/Expensify/App/issues/9252) is only present in android app & this bug is present in mWeb in both android and Ios.
2. [#9252](https://github.com/Expensify/App/issues/9252) isn't a focus related issue, as after selecting emoji the edit message input field is in focused state but the keyboard isn't showing up. while in this issue, emoji box isn't opening up after first click( on first click the input field gets unfocused and on the second click it opens the emoji box)

We can fix this bug just by using `true` instead of `false` at:-
https://github.com/Expensify/App/blob/dbfd0eb5ae2cd321db5075f088492f87ff1e8860/src/pages/home/report/ReportActionItemMessageEdit.js#L207
Screen recording:-

https://user-images.githubusercontent.com/89839952/188009044-11a5cf56-df4f-4636-81c0-f5bdc178bce9.mov

cc- @parasharrajat

**Comment by michaelhaxhiu** [comment]
@parasharrajat do you think our ongoing issue https://github.com/Expensify/App/issues/9252 will include a fix for this bug, too? Or should we treat as it's own scope and fix it separately?

**Comment by arielgreen** [comment]
@parasharrajat can this be taken off hold now?

**Comment by arielgreen** [comment]
@parasharrajat [bump](https://github.com/Expensify/App/issues/10290#issuecomment-1270387180) -- I'm not sure what is needed here

**Comment by arielgreen** [comment]
Raised thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1665625230893549).

**Comment by parasharrajat** [comment]
Yeah, we don't need to hold this.

**Comment by michaelhaxhiu** [comment]
We have 2 valid proposals that were already provided above, and ready for review @mananjadhav / @srikarparsi

**Comment by mananjadhav** [comment]
@michaelhaxhiu I don't have the bandwidth right now for this one. Can you please assign another C+?

**Comment by michaelhaxhiu** [comment]
Sure thing, thanks for the heads up @mananjadhav

**Comment by Santhosh-Sellavel** [comment]
Will not be able to get this soon @michaelhaxhiu can you reassign another C+ here, thanks!

**Comment by sobitneupane** [comment]
Looks like we already have few proposals:
https://github.com/Expensify/App/issues/10290#issuecomment-1234768885
https://github.com/Expensify/App/issues/10290#issuecomment-1265925665
https://github.com/Expensify/App/issues/10290#issuecomment-1280776283

Will review them tomorrow(Wednesday) morning NPT.

**Comment by sobitneupane** [comment]
@aimane-chnaif's [proposal](https://github.com/Expensify/App/issues/10290#issuecomment-1265925665) looks convincing. He is proposing to extend an existing logic (used for Save button and Cancel button) to emoji button as well. So, for consistency I am tilted towards his proposal.

But @aimane-chnaif few queries:

- Why is this issue existent only on mWeb and not on native apps?
- What is the affect of the proposed change on native apps?

**Comment by sobitneupane** [comment]
> You can confirm that onBlur is never called when click Cancel or Save button on native.

@aimane-chnaif I tested it and `onBlur` is being called on native. And `toggleReportActionComposeView()` is also being triggered but cancel and save button are clickable unlike mWeb.

**Comment by arielgreen** [comment]
Offers sent in Upwork

**Comment by arielgreen** [comment]
PR in progress

**Comment by arielgreen** [comment]
Awaiting merge

**Comment by arielgreen** [comment]
Payment due tomorrow

**Comment by arielgreen** [comment]
Paid.
