### ISSUE TITLE
Profile - The save button remains inactive when the photo is removed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to profile settings
4. Upload a photo if you don't have one
5. Remove the photo

## Expected Result:
The user expects to see an active save button to confirm the remove of the photo

## Actual Result:
The save button is not active, the user does not confirm the remove of the photo, but the changes are saved automatically

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183747477-91dc95ea-cf20-4d99-8439-9dcf31a5b916.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Not sure that it's a bug, though it is slightly inconsistent. I'm asking in Slack to see if people agree with this, but also CC @zanyrenney & @twisterdotcom as perhaps we cover similar cases in N7: Account settings?

**Comment by Julesssss** [comment]
Actually, I'm not posting in Slack. I don't think we should change this feature -- it kinda makes sense that you should confirm a new photo upload. Also, we'll be working on these pages in N7 AS anyway. 

@ted @zanyrenney -- feel free to reopen if you disagree though.
