### ISSUE TITLE
[HOLD for payment 2022-09-08] [$250] The green CTA button height is 64px, which is way taller than our tallest button, which is 52px

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10335]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 
2. Navigate to Settings > Payments 
3. check Green CTA height 
4. Navigate through Request money flow 
5. Check NEXT button height 

## Expected Result:
Let’s make the green portion of the green button CTAs at 52px to match our big buttons, and with 6px vertical padding the green row will take up the same height as a standard option row in a list. 

## Actual Result:
The green CTA button height is 64px, which is way taller than our tallest button, which is 52px

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
Here that is side-by-side for comparison, and then a second screenshot to show how that will compare to other large buttons in the app.
![image - 2022-08-09T233826 906](https://user-images.githubusercontent.com/43995119/183807846-e9d1d40d-87f9-4ce0-b60f-cf917ac33501.png)
![image - 2022-08-09T233821 188](https://user-images.githubusercontent.com/43995119/183807851-5df52e69-cdad-45ad-ac30-86f3da529b10.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660088139670819?thread_ts=1654608378.533319&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Looks like a good external issue.

**Comment by thesahindia** [comment]
### Proposal 

If we wanna use 52px height then we won't be needing `extraLarge` button, we can remove it from Button.js and instead just change these buttons to large (line 234) and pass the padding in the style (line 230)
(will have to do the same at other places)
https://github.com/Expensify/App/blob/f5f076a13bb4a991dbeaf32a8f7a7b0625e8a3cc/src/pages/ReimbursementAccount/BankAccountStep.js#L225-L234

**Comment by amyevans** [comment]
Looks like @NicMendonca got unassigned here accidentally

**Comment by neil-marcellini** [comment]
Oh thanks, my bad!

**Comment by NicMendonca** [comment]
Job posting: https://www.upwork.com/jobs/~016bb2597fced2095a

**Comment by hamzashakeel348** [comment]
`<Button
                            icon={Expensicons.Bank}
                            text={this.props.translate('bankAccount.connectOnlineWithPlaid')}
                            onPress={() => BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID)}
                            disabled={this.props.isPlaidDisabled || !validated}
                            style={[styles.mt5, styles.mh3]}
                            iconStyles={[styles.mr5]}
                            shouldShowRightIcon
                            success
                            extraLarge
                        />`
                        
[https://github.com/Expensify/App/blob/f5f076a13bb4a991dbeaf32a8f7a7b0625e8a3cc/src/pages/ReimbursementAccount/BankAccountStep.js#L225-L234](url)

@rushatgabhane  I mentioned the code lines here and the link to the code block as well. As per mentioned issue, we have to add paddings and height to this button in order to make it align with the div.

 padding: 6px 0px ( it will add the vertical padding to the button ).

**Comment by Beamanator** [comment]
Thanks for your proposal @hamzashakeel348 but since there was already a good proposal before yours we'll go with that one

**Comment by hamzashakeel348** [comment]
@Beamanator could you please mention the proposal which is going to be accepted?

**Comment by hamzashakeel348** [comment]
No problem @Beamanator, I would love to help extensively with future issues.

**Comment by Beamanator** [comment]
@shawnborton do you mind checking out the results of this PR? https://github.com/Expensify/App/pull/10470

What I'm a bit concerned about is that it looks like the button text on the newly sized green buttons are not always aligned with menu items below / above the button.

For example: In this screenshot it looks like the right arrows aren't aligned perfectly, and even the main button text isn't perfectly aligned. Is that something we should fix? I'm thinking yes?
<img width="410" alt="Screen Shot 2022-08-23 at 11 22 38 AM" src="https://user-images.githubusercontent.com/3885503/186122373-b5b75825-2bf1-4a71-ab93-47bcfde714ab.png">

**Comment by shawnborton** [comment]
I agree with you. The text should line up perfectly no matter if it's green or standard: 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2319350/186212704-3c64946d-d30d-4e0d-b52c-04d41a3a0ddb.png">

**Comment by NicMendonca** [comment]
Latest PR update [here](https://github.com/Expensify/App/pull/10470#issuecomment-1233956806)

**Comment by NicMendonca** [comment]
@thesahindia @rushatgabhane can you please accept the offers when you get a sec? Thanks!

**Comment by thesahindia** [comment]
Accepted 🚀

**Comment by NicMendonca** [comment]
paid! thanks, both!
