### ISSUE TITLE
Tracking for bug reporting react-native update for @tomivs

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#10338]
Going to compensate @tomivs $250 for bug reporting, details here https://expensify.slack.com/archives/C01GTK53T8Q/p1659765865205259

Upwork issue
https://www.upwork.com/jobs/~01434c202c18a1556e

**Comment by tomivs** [comment]
Applied to Upwork job.

**Comment by mallenexpensify** [comment]
Hired, please accept offer and I'll get ya paid @tomivs 
https://www.upwork.com/jobs/~01434c202c18a1556e

**Comment by tomivs** [comment]
> Hired, please accept offer and I'll get ya paid @tomivs https://www.upwork.com/jobs/~01434c202c18a1556e

Accepted.

**Comment by mallenexpensify** [comment]
Paid, faster ever for job creation to closed! 
Thanks for the help @tomivs
