### ISSUE TITLE
Android - Keyboard appears on the main screen - reported by @

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Kill Expensify if you have it in the background and re-open it.
2. go to any chat
3. edit any comment.
4. Go back to home screen
5. Send app to background
6. Open app again

## Expected Result:
 keyboard shouldn't appear on the home page.
 
## Actual Result:
Keyboard appears when entering  app again

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.85-8
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y  
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184204582-9788a7b7-84f3-4452-96da-fac4f1d47098.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658150742046479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This was on an old version of the app, we're now on 1.187-9. Tested this, not reproducible on prod or staging.

**Comment by ahmdshrif** [comment]
@stephanieelliott  the issue gets fixed after I report it. 
will I be eligible for a reward bonus?
