### ISSUE TITLE
[$250] Deleting a workspace doesn't delete its room if it is pinned. It is blank and you can't even unpin the room because it is not accessible - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Pin its announce room
3. Delete the workspace
4. See that the workspace remains pinned (and _archived_)

## Expected Result:
The room is removed

## Actual Result:
The room is not removed, shows a blank page, and couldn't unpin

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184212053-7c18511f-6885-41e5-bd59-9b8f895ae1ac.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658386423918479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
The error here is that unpinning from the LHN doesn't work. You can unpin from the room settings (top right) itself:

https://user-images.githubusercontent.com/9133401/184241414-6a2113b6-5206-41c8-b4c4-b481d43acb35.mp4

**Comment by adeel0202** [comment]
@twisterdotcom, in my case, the chat screen is all blank (there is no unpin icon on the top right). Please check the video attached with the issue.

**Comment by twisterdotcom** [comment]
Huh, that is odd. Can you still recreate it @adeel0202?

**Comment by adeel0202** [comment]
Yes, I just tried again on chrome and safari and I'm able to reproduce on both.

**Comment by Justicea83** [comment]
@michaelhaxhiu can this be external?

**Comment by michaelhaxhiu** [comment]
@Justicea83 I'm not sure, but if you feel any issue is fixable by external engineers then you can always label it `external`. 

In this case, are you asking if it's eligible to be fixed externally? Or are you saying that you know it can be fixed externally and asking if that's ok to do?

**Comment by Justicea83** [comment]
Am asking if it's eligible to be fixed externally

**Comment by Justicea83** [comment]
I agree with @twisterdotcom after testing this. I can't replicate this, am unassigning myself so someone else can take a look.

**Comment by michaelhaxhiu** [comment]
>Am asking if it's eligible to be fixed externally

@Justicea83 Got it! This is a decision that's made by the assigned engineer based on your knowledge of the code base, and so I'm not able to decide that. [This s/o post has some more guidance on the topic](https://stackoverflow.com/c/expensify/questions/4319/8577#8577). But if you are in doubt, you can likely post in #engineering-chat or #expensify-open-source

**Comment by adeel0202** [comment]
@michaelhaxhiu, this issue has no assignee.

**Comment by michaelhaxhiu** [comment]
@Justicea83 Sorry I think we are missing a step to move this forward. 

Can you help discern if this is fixable `internally` or `externally`, and label it accordingly? If you aren't sure, can you post in #contributor-management and @`contributor-management-engineering` for help?

I just tested this on my side and am certain it's reproducible. I made a recording of me reproducing it here (sorry it's in spanish but you get the idea).


 https://recordit.co/oIbO8bJpr4

**Comment by Justicea83** [comment]
I think this needs to be internal

**Comment by michaelhaxhiu** [comment]
Thank you!

**Comment by michaelhaxhiu** [comment]
@adeel0202 as a heads up, you are eligible for the bug reporting bonus _after_ this has been fixed. It will need to be picked up internally by an engineer and that's subject to our prioritization. Just sharing the context in case it's helpful.

**Comment by Gonals** [comment]
Taking a look!

**Comment by Christinadobrzyn** [comment]
Job crated in Upwork 

Internal - https://www.upwork.com/ab/applicants/1564988436490932224/job-details
External - https://www.upwork.com/jobs/~01b8fa79adb0533172

Hired @adeel0202 as bug reporter

**Comment by puneetlath** [comment]
@Christinadobrzyn let's make sure @rushatgabhane get's paid out for C+ on this one. It closed immediately since its an internal issue.

**Comment by Christinadobrzyn** [comment]
Thanks for the heads up @adeel0202!
I sent a payment through Upwork yesterday to you and @rushatgabhane. Let me know if you have any questions!

**Comment by adeel0202** [comment]
I have got the payment @Christinadobrzyn. Thanks 😊
