### ISSUE TITLE
IPAD:  floating button moved with textInput - reported by @ahmdshrif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app ( iPad  portrait)
2. focus text input

## Expected Result:
Only text input move above the keyboard.

## Actual Result:
The floating button  also moved with text input

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184211086-8e474c2c-1c1e-4de1-af21-dc53adedc9ec.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658383366185759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Looking to see if this is the correct behaviour internally https://expensify.slack.com/archives/C03U7DCU4/p1660553762368969

**Comment by Julesssss** [comment]
Not a bug
