### ISSUE TITLE
The width for attachment isn't set. We should have a fix width and if the name is longer, then we should use ellipsis like slack - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Send different mp4 files with short and long names

## Expected Result:
The attachment should have same width.

## Actual Result:
The width for attachment isn't set.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1064" alt="Screenshot 2022-07-22 at 12 39 20 PM" src="https://user-images.githubusercontent.com/43995119/184215213-f3be7a79-2f70-492e-b343-79b5a2d805b2.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658474655102339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
I'd like some input from design here! Should we have a set width for attachments and if so, what would be the value for that set width and would that accommodate different screen sizes?

**Comment by shawnborton** [comment]
Let's discuss in the Slack thread!

**Comment by shawnborton** [comment]
We decided to just close this one out - the variable length file names are expected.
