### ISSUE TITLE
[$500] Can't find the download PDF's on the iOS. - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app on iOS
2. Send a PDF document.
3. Open the PDF document.
4. Click on the download icon.
5. Click :heavy_plus_sign:  icon to add an attachment.
6. Select Choose a document.
7.Browse to find the download PDF.

## Expected Result:
Download PDF should be visible on user's device.

## Actual Result:
Can't find the PDF anywhere on the files.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184214765-06ab078a-fd96-4882-8dcb-1773fce7297d.MP4

**Upwork URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658428707694039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Apologies for the delay, Melvin. I've been OoO! The iOS app keeps crashing on me this morning, so I can't attempt to reproduce this myself.

@mvtglobally @parasharrajat, the first couple of reproduction steps in the OP are: 

>open app on iOS
>Send a PDF document.

Does that mean you already have the PDF saved on your iOS device, upload it, and then try to re-download it? Are we sure that iOS simply doesn't save the same PDF twice or something? It might be good to try and eliminate that possibility by trying the initial upload via Web as well: 

>1. Head to new.expensify.com on the web and send a PDF document
>2. Open app on iOS and navigate to the chat you sent the PDF document in
>3. Open the PDF document.
>4. Click on the download icon.
>5. Observe the "Downloaded!" success modal and tap `Ok`
>6. Click ➕ icon to add an attachment.
>7. Select Choose a document.
>8. Browse to find the downloaded PDF.

In the meantime, passing this along to keep the `engineering` triage moving.

**Comment by alex-mechler** [comment]
@parasharrajat Are you still able to download that PDF from other clients like Web or Desktop, or is this just impacting iOS?

**Comment by alex-mechler** [comment]
Awesome, thanks for the info! Based on that I'm guessing that this is something clientsided, so going to send this external!

**Comment by trjExpensify** [comment]
Upwork URL: https://www.upwork.com/jobs/~019f7f04f94b126efd

**Comment by MadPharaoh** [comment]
proposal: Ahmed Badiwy 
I think 
```
RNFetchBlob.config(configOptions)
.fetch('GET', url)
    .then((res) => {
        if (Platform.OS === "ios") {
            RNFetchBlob.fs.writeFile(config.path, res.data, 'base64');
            RNFetchBlob.ios.previewDocument(config.path);  
        }
        });
```
should do the trick i guess

**Comment by Santhosh-Sellavel** [comment]
@MadPharaoh 

Using Platform.OS is not recommended & against our [Philosophy 5](https://github.com/Expensify/App#philosophy:~:text=native%2Donyx.-,Philosophy,-This%20application%20is). 

So if that's the only way, write a new proposal with all the changes you are proposing following [Philosophy 5 iii](https://github.com/Expensify/App#philosophy:~:text=native%2Donyx.-,Philosophy,-This%20application%20is).

Thanks!

**Comment by trjExpensify** [comment]
👋 doubled on Upwork! https://www.upwork.com/jobs/~019f7f04f94b126efd

**Comment by MadPharaoh** [comment]
### Proposal
https://github.com/Expensify/App/blob/ed4628a40e0196ee2fc9d0829acf615aafe3d321/src/libs/fileDownload/index.ios.js#L28 #
 }).fetch('GET', fileUrl).then((resp) => {
        RNFetchBlob.ios.openDocument(resp.data);
}); 
prompts user to save file on all apps

**Comment by Santhosh-Sellavel** [comment]
@puneetlath @trjExpensify 

Sorry this should have been caught earlier, actually, the file is available we are looking at `iCloudDrive`, it is downloaded in `On My iPhone`, so we are good to close this one out, cc: @parasharrajat Can you check, please?

https://user-images.githubusercontent.com/85645967/186991029-48cacc22-662e-49d2-b7d7-0e6d46830d0a.MP4

**Comment by Santhosh-Sellavel** [comment]
@parasharrajat Verified on both Device & simulator!

**Comment by Santhosh-Sellavel** [comment]
@parasharrajat 
[Recording here](https://github.com/Expensify/App/issues/10357#issuecomment-1228952638) is from my personal device, 

## Simulator

https://user-images.githubusercontent.com/85645967/186995266-b8842588-848e-4959-a55f-7224763199b8.mp4

**Comment by puneetlath** [comment]
I just tested it and it did download into the Expensify folder for me. So I'm going to go ahead and close the issue. Thanks everyone!

**Comment by trjExpensify** [comment]
>The iOS app keeps crashing on me this morning, so I can't attempt to reproduce this myself.

^^ my lesson learnt that I should have got to the bottom of that and reproduced first-hand. 

Job is down off Upwork!
