### ISSUE TITLE
Unsupported file error doesn't get dismiss until user refreshes the page - Reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open web/mWeb
2. Go to Chat > Send a .heic or other unsupported attachment.

## Expected Result:
Error should get dismiss after a while.

## Actual Result:
Error doesn't get dismiss

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184218828-5ffaf6a9-5658-40a5-9196-9a2e0aff2c9a.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658776953105819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
It's known that this file type isn't supported (https://github.com/Expensify/Expensify/issues/216891) but I don't see an issue referring to the error message persisting indefinitely, so I'll send to the Eng.

**Comment by tgolen** [comment]
Hm, when I try that locally on an updated `main`, I get this error instead (which is what I expect) and it can be dismissed.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1228807/184402263-16b2e780-e913-4304-bb5e-373fd532a30d.png">

That is a fairly new error message, so maybe it hasn't been updated on staging let. Let's try this again after the next deploy and see if this new error is there.

**Comment by tgolen** [comment]
@mvtglobally Can someone retest this please?

**Comment by mvtglobally** [comment]
Sure we will Check in a bit

**Comment by tgolen** [comment]
@mvtglobally Were you able to retest this?

**Comment by mvtglobally** [comment]
@tgolen sorry totally forgot to update with the last weeks daily deploy changes. Issue is not longer repro. We checked multiple platforms just in case 

https://user-images.githubusercontent.com/43995119/187685229-e2e5c6c1-2386-44fb-a172-16b48ea242cc.mp4

https://user-images.githubusercontent.com/43995119/187685232-663f3a0f-ef90-448b-910d-67f780ee8234.mp4

https://user-images.githubusercontent.com/43995119/187685222-69188fd0-0a1e-4f09-91d5-c4a290be9e28.mp4

**Comment by tgolen** [comment]
Great, thank you! I will go ahead and close it out then.
