### ISSUE TITLE
[$250] Some Unnecessary view is added above keyboard when it is active in android - reported by @Santhosh-Sellavel

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to chat window and tap on compose box
3. Or Perform any operation that opens native keyboard

## Expected Result:
No Unnecessary blocking view

## Actual Result:
Some blocking view is added

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.85-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_1658677626](https://user-images.githubusercontent.com/43995119/184218346-2d2cd86c-db76-458e-8a2b-d6e33c7ef19e.png)
![Screenshot_1658677379](https://user-images.githubusercontent.com/43995119/184218349-7a24a121-35ae-4f6d-8e8c-da1d18749531.png)
![Screenshot_1658677358](https://user-images.githubusercontent.com/43995119/184218354-3f1f4472-695f-4e11-a04a-ca6ca216ebef.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658677663185129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment]
Unable to recreate on my app. I'm not sure what could cause this. It looks like a code issue based on what I can find about it online. https://stackoverflow.com/questions/62051371/react-native-android-keyboard-empty-space. I'm hoping an engineer can help us figure it out.

**Comment by iwiznia** [comment]
So there's a huge space between the keyboard and the content? And this is in all androids? And it is in production?
If so, how did this get past QA @mvtglobally ?

**Comment by ntrepanier** [comment]
It's not on all androids. Mine is fine, which is why at first I thought it must be a local issue but nothing I found on it pointed to that.

**Comment by JmillsExpensify** [comment]
Ok so QA can reproduce but @ntrepanier can't? In that case, I don't think it's a fire and we can use the normal contributor process.

**Comment by JmillsExpensify** [comment]
Upwork job is here: https://www.upwork.com/jobs/~014b1754d939b81c86

**Comment by Santhosh-Sellavel** [comment]
Not reproducible for me now.

**Comment by vladnobenladen** [comment]
The reporter @Santhosh-Sellavel tested on v1.1.85-8 but this issue is gone from v1.1.86-2 (generated on Jul 26)

This caused android keyboard issue: https://github.com/Expensify/App/pull/9895 (Jul 20)
And reverted: https://github.com/Expensify/App/pull/10113 (Jul 26)
Therefore, from v1.1.85-6 (on Jul 21) to v1.1.86-1 (Jul 25) was having this keyboard issue

**Comment by NikkiWines** [comment]
Sounds like this bug may no longer be an issue. @mvtglobally can you confirm whether or not QA is able to reproduce this still?

**Comment by JmillsExpensify** [comment]
Let's proactively close until Applause is able to reproduce on the latest build. Please re-open if it fails the next round of QA. Thanks!
