### ISSUE TITLE
[HOLD for payment 2022-09-26] [$250] Loading indicator isn't in center - Reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Payments > Add payment method
2. Click on bank account

## Expected Result:
The loading indicator should be in the center 

## Actual Result:
The loading indicator isn't in center

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184221323-af3606a4-ad11-4653-9247-40938666aa9a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658840250275259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment]
Doesn't seem like a priority but adding the engineering label.

**Comment by flaviadefaria** [comment]
@jliexpensify is on leave so will reapply the label.

**Comment by kadiealexander** [comment]
https://www.upwork.com/ab/applicants/1565628956228489216/job-details
https://www.upwork.com/jobs/~01141ec09bdbf1fab9

**Comment by RanaAwais3553** [comment]
Hi, could you try to give full screen height and width to the parent of indicator and position absolute then marginBottom:screenHeight/2
MarginLeft:screenWidth/2.
Try this Using this way your indicator in center.
Style={{marginLeft:ScreenWidth/2,marginBottom:screenHeight/2, width:screenWidth, height: screenHeight}}

**Comment by onliwer** [comment]
My proposal is to wrap AddPlaidBankAccount at line 168 in another View containing the style 'styles.flex1', this centers the ActivityIndicator.

**Comment by onliwer** [comment]
Proposal : Wrap AddPlaidBankAccount at line 168 in another View containing the style 'styles.flex1', this centers the ActivityIndicator.

**Comment by liyamahendra** [comment]
# Proposal

## Issue
The `ActivityIndicator` is already configured to display in the centre of the screen by using `alignItems: 'center'` and `justifyContent: 'center'` however it displays at the top because the parent element containing the `ActivityIndicator` isn't having height / width equal to the screen. 

This is evident if we try adding the `backgroundColor` to the `ActivityIndicator` container. See the screenshot below:
![Simulator Screen Shot - iPhone 11 - 2022-09-03 at 20 18 54](https://user-images.githubusercontent.com/911879/188276067-90f391d0-8e43-4632-97f3-9747fd221600.png)


## Solution

The fix to this issue is to ensure the container of `AddPlaidBankAccount` is expanded to full screen height width. 

The actual fix is addition of `styles.flex1` to the view containing `AddPlaidBankAccount` in `src/pages/AddPersonalBankAccountPage.js` i.e.

Change:
```
<View style={[styles.mh5, styles.mb5]}>
                            <AddPlaidBankAccount
```

to

```
View style={[styles.mh5, styles.mb5, styles.flex1]}>
                            <AddPlaidBankAccount
```

Attached is the screencast of the fix:

https://user-images.githubusercontent.com/911879/188276392-1fb1c672-47fe-496c-9ea6-596f9071aa32.mp4

**Comment by Santhosh-Sellavel** [comment]
@jasperhuangg 
@onliwer @liyamahendra suggesting something similar. 

@onliwer suggests wrapping in another View and adding `flex1` style. That's unnecessary. Also, the proposal is not clear enough.

@liyamahendra Adding style existing View itself should be fine. Also, their proposal is detailed. So let's hire @liyamahendra for this one!

Also, the same issue could occur when adding a bank account via workspace. It should be handled there too!

🎀 👀 🎀 
C+ Reviewed

**Comment by varshamb** [comment]
@Santhosh-Sellavel I guess you missed to review my proposal posted first (13 days ago).

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel I guess you missed to review my proposal posted first (13 days ago).

Yeah I missed out that, yours was the first right proposal.

It's easy to miss when proposal is sent before applying external label. In case if you submitted earlier please make sure to reminder as soon as Help wanted label is added.

**Comment by Santhosh-Sellavel** [comment]
@jasperhuangg

@varshamb @onliwer @liyamahendra suggesting something similar. 

@onliwer suggests wrapping in another View and adding `flex1` style. That's unnecessary. Also, the proposal is not clear enough.

@varshamb @liyamahendra are suggested adding style to existing View itself should be fine.

Let's go with first proposal and hire @varshamb for this one!

Also, the same issue could occur when adding a bank account via workspace. It should be handled there too!

🎀 👀 🎀 
C+ Reviewed

**Comment by jasperhuangg** [comment]
I agree, let's go with @varshamb on this one, thanks!

**Comment by kadiealexander** [comment]
Just adding a note that I'll be OOO for the next 9 days, until September 21st. If you need a CM in that time, please re-add the  `external` label.

**Comment by jasperhuangg** [comment]
> @kadiealexander Thanks for the update, the PR was just merged so I think I'll reassign the label since payout will need to be handled 👍

@arielgreen Just so you're aware!

**Comment by Santhosh-Sellavel** [comment]
PR is merged

**Comment by arielgreen** [comment]
@Santhosh-Sellavel @thesahindia @varshamb please check your Upwork inboxes

**Comment by Santhosh-Sellavel** [comment]
Thanks, @arielgreen!

**Comment by arielgreen** [comment]
Paid.
