### ISSUE TITLE
rtf file is corrupted in the preview. The inside text changes - Reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website.
2. Go to Chat > Send a .rtf attachment.
3. Preview the attachment

## Expected Result:
It shouldn't get corrupted.

## Actual Result:
It gets corrupted.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184222042-ecc8db3d-7724-4c5e-8180-8b638398e3da.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658854329649929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
It seems like the file gets corrupted after being processed by our server. Downloading the file and trying to open it results in an error as well, so it's not only the preview. I add the internal label and release this back to the pool!

**Comment by youssef-lr** [comment]
We seem to create thumbnails for text files too, I think we should limit creating thumbnails to PDFs and images only. I will keep this assigned to me as I'm working on file uploads. I will also post in slack for some input about what types we wanna create thumbnails for.

**Comment by puneetlath** [comment]
@youssef-lr I removed and re-added the bug label to get a BZ team member added who can help move this forward.

**Comment by puneetlath** [comment]
Though actually, it looks like a PR was already merged. Is this done? And if so, can we close it?

**Comment by youssef-lr** [comment]
Yeah this has been fixed, I just tested again in production. Closing!

**Comment by Tushu17** [comment]
Reporting compensation is pending here.
cc- @puneetlath @sakluger

**Comment by Tushu17** [comment]
@sakluger Bump.

**Comment by puneetlath** [comment]
Paid! Thanks for your patience and thanks for the bug report.
