### ISSUE TITLE
 Extra spacing below Add phone number - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings > Profile

## Expected Result:
There shouldn't be too much space

## Actual Result:
There's extra spacing below Add phone number

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="372" alt="Screenshot 2022-07-26 at 7 42 05 PM" src="https://user-images.githubusercontent.com/43995119/184221647-0542806e-1d9b-4956-8b22-8884cfb362bc.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658844763409589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal
We should change this to 
`style={this.props.login.partnerUserID ? styles.mb6 : styles.mb4}`
https://github.com/Expensify/App/blob/9cb1452ae18456116901b69ff32f8fafbc9b9c94/src/pages/settings/Profile/LoginField.js#L91

not sure if it should be mb4 or mb3

mb4           |  mb3
:-------------------------:|:-------------------------:
<img width="374" alt="Screenshot 2022-08-12 at 10 05 30 AM" src="https://user-images.githubusercontent.com/101883770/184285864-b1ce14f5-472b-47f2-81a5-28b660f09bdc.png">  |  <img width="374" alt="Screenshot 2022-08-12 at 10 06 11 AM" src="https://user-images.githubusercontent.com/101883770/184285875-bee4ae82-5a9d-4bac-a8b7-5679c913e389.png">

**Comment by jasperhuangg** [comment]
@stephanieelliott Before we export this, @Expensify/design do we think this change is necessary? It honestly looks fine to me, not sure if it needs to be fixed.

**Comment by shawnborton** [comment]
This is definitely not a bug, and furthermore, we'll be reworking this section soon. Going to close.
