### ISSUE TITLE
[Hold] Allow emojis to be saved in Profile page inputs

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#10376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Add an emoji to first or last name

## Expected Result:
Emoji should show in the field

## Actual Result:
Entire field is wiped out

## Workaround:
Don't add emojis or other strange characters to your first name, last name

## Platform:

Where is this issue occurring?

- Web 
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** Current
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Notes/Photos/Videos:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660554149987989?thread_ts=1660553818.508299&cid=C01GTK53T8Q
**Issue reported by:** @laurenreidexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660553818508299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
This happened due to: https://github.com/Expensify/Web-Expensify/pull/34450/files

I added stricter input pattern matching for `firstName`, `lastName`, and `pronouns`. I will loosen the restrictions for `firstName` and `lastName` so that they're like the custom `pronouns` field, where emojis and other special characters can be added

**Comment by Beamanator** [comment]
Actually I might see what other people advise on this one, a few things to consider:
1. I believe we do want to allow emojis to be added to personal details first & last name (we had this working before and it wasn't causing problems)
2. Should I make new inputrules params for these, which allow for emoji characters? Or should I modify existing `firstName` and `lastName` params?

**Comment by rafecolton** [comment]
Just noting that I think we should allow this, it was a very helpful workaround for not having a status field.

**Comment by rafecolton** [comment]
Oh, also noting that there should be some kind of feedback, like an error modal if a field fails to save.

**Comment by JmillsExpensify** [comment]
One thing that strikes me about @rafecolton's comment is that we're using these emojis as a clutch for something else we feel the app lacks.

**Comment by JmillsExpensify** [comment]
In general, I'm fine with emojis in the display first and last name. But where it gets tricky is for KYC or legal cases, such as name on a bank account, name for IRS and payroll purposes, etc. So I think we also need to consider the holistic use cases here as well.

**Comment by rafecolton** [comment]
> One thing that strikes me about @rafecolton's comment is that we're using these emojis as a clutch for something else we feel the app lacks.

This is a good point @JmillsExpensify. We discussed it somewhere when talking about online status - @michaelhaxhiu do you remember where that discussion is? This could be a case where our use case is not the common one just yet and we have to wait to prioritize this feature until we're ready to support business chat. One alternative could be to add a simple status field that's just a free text field and not tied to online availability. It might not be used by most but it would solve this problem for us.

**Comment by Beamanator** [comment]
I also remember that conversation happening a while back, I think there was a P/S but it was either pushed to the future (not critical at the moment) or something like that?

I also like the idea of the status field, but then I think it would still be useful to provide some feedback to the front end when characters are stripped (either due to WAF think it's some XSS or even filtering via `_inputrules`) - seems weird to me that we either allow ANY character to be stored in a name, OR we strip some characters that don't match a regex and we don't provide any warning to the user that what they sent in the form has been altered.

**Comment by michaelhaxhiu** [comment]
>but it was either pushed to the future (not critical at the moment) or something like that?

That's spot on. I got the [non-technical design doc](https://docs.google.com/document/d/1YpYDi3ZWjaYRThPa94Zx48zlweOYTIBG43HK4LHIhb4/edit?disco=AAAAYvmtg4w) all ready to go as we discussed, but there's been a lot of changes since then and we likely need to update the design doc. The refactor and n7 have taken total priority for all technical (engineering) projects. My plan was to bring this up for n10 when it's timely.

**Comment by michaelhaxhiu** [comment]
Furthermore... the GBR/RBR project is using 🟢 🔴 green/red status dots as an indicator (and we initially intended to use the 🟢 as an availability status). So we have a confliction now. I can't say for sure but IMO, it's likely wise to close down the availability indicator altogether and lean into the customer status field instead. 

In that world, we include add emoji support in the custom status field and use it for a multitude of purposes.

**Comment by JmillsExpensify** [comment]
I put a hold on this, as I'd prefer to see us align on status and our plan moving forward.

**Comment by michaelhaxhiu** [comment]
>like if we want to start having some kind of custom "status" field instead of using the existing last name field

Just chiming in. I think this coming in the future, and I'll personally volunteer to lead up the DD when it's time! The availability indicator design doc was put on ⏸️ and we'll very likely have to re-jig that proposal to solely be a "custom status field" instead (since the RBR/GBR are now using a green/red indicator, and that obviates the design of the OG availability indicator solution). 

But I think this can wait until we master the quality aspect of chat and so I agree with considering this "polish". Maybe we can tackle it together when it's time @Beamanator 😃

**Comment by Beamanator** [comment]
Agreed on all points :D I'm very interested to help work on this once the time comes! 👍 👍

**Comment by mountiny** [comment]
@Beamanator @michaelhaxhiu  looking through this issue I am confused what exactly is the goal. AFAIK my name in NewDot has Emoji in it so this works. If this is mean to be feature request to add a Slack-like status option with maybe an emoji AND a status text. 

We should probably update the body to clearly state what the goal here is or close this one out. Thanks for help!

**Comment by Beamanator** [comment]
Oh yeah, emojis seem to be working totally fine now 😅

**Comment by rafecolton** [comment]
Sure do!
