### ISSUE TITLE
Desktop - Slide text at the right is not appearing when the login container is resized

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

*Issue found during executing PR:* https://github.com/Expensify/App/pull/10158

## Action Performed:
1. Go to Login page Expensify App
2. Decrease the screen width (height must be under 854 px )

## Expected Result:
When resized the right side slide text displayed at the bottom of the login container

## Actual Result:
When resized right side slide text not appearing at the bottom of the login container

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** mnata.utest@gmail.com/Utest123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184993600-e34d41d8-9e5f-4527-8300-a872571500b7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
@kbecciv After watching the video, I'm still not sure what the problem is. Would you mind clarifying?

**Comment by kbecciv** [comment]
@Luke9389 The slide text at the right is not appearing when resizing the screen, not sure if its expected. 

![image](https://user-images.githubusercontent.com/93399543/186943595-d01d4f75-7460-4d0f-a3a0-6444c3a01d17.png)

**Comment by Luke9389** [comment]
By slide text, do you mean this? 

<img width="683" alt="Screen Shot 2022-08-29 at 11 37 22 AM" src="https://user-images.githubusercontent.com/49007721/187172056-ba8ca53b-50bb-4821-aee4-c09504ef0284.png">

**Comment by kbecciv** [comment]
Correct

**Comment by Luke9389** [comment]
Ah ok cool. That's the intended behavior. Thanks for stickin with me @kbecciv!
