### ISSUE TITLE
Web - Login - "Enter" key doesn't work for sing in to account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Enter login name and password
3. Put Enter key in keyboard

## Expected Result:
User logged into your account

## Actual Result:
There is no login, the system does not respond to pressing the enter key

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184997541-40b608cc-abce-412a-9d35-d3018b1cb751.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause- Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
This is the offending commit:https://github.com/Expensify/App/pull/10269/commits/979fbf57dfdea53178ba1dd6ef7b9f631bef7c18

Investigating on Slack.

**Comment by yuwenmemon** [comment]
Looks like we're calling `BeginSignIn` when hitting the enter key instead of calling `Authenticate`:
<img width="1505" alt="Screen Shot 2022-08-17 at 8 04 32 AM" src="https://user-images.githubusercontent.com/4741899/185005866-871e7efd-9f61-4606-bb0d-ab55a987c16e.png">
