### ISSUE TITLE
[$250] mWeb/safari - Chat - If user taps on the keyboard, they can scroll to show blank spaces

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid user
3. Access any chat on mobile
4. Tap on the input field
5. With the keyboard open, scroll the screen up and down

## Expected Result:
The user expects the screen not to show blank elements and to adjust to the users keyboard opened correctly

## Actual Result:
The screen UI seems to "Break", if the user scrolls downwards, there is a huge blank space shown and the header can some times be "shakey" and if the user scrolls upwards after doing this, some elements of the UI can be hidden.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184993973-10a37d5a-6ce9-435e-bc8a-27fe8e55573e.mp4

https://user-images.githubusercontent.com/93399543/184993977-7f90a752-6ed8-4556-9387-edb23e241062.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
I'm pretty sure that this is a mobile web only issue. It doesn't occur on iOS. We'll have to test Android. It won't happen on Desktop or Web because there is not an on screen keyboard. It looks pretty bad on mobile web so we should fix it.

**Comment by puneetlath** [comment]
External upwork job: https://www.upwork.com/jobs/~01c4fa4158f879a239
Internal upwork job: https://www.upwork.com/ab/applicants/1560314167990468608/job-details

**Comment by MadPharaoh** [comment]
proposal:Ahmed Badiwy
this issue with safari only Using any position: fixed on the dragable area so changing the position is the ideal solution

**Comment by Santhosh-Sellavel** [comment]
@MadPharaoh Can you elaborate your more also with code changes you are proposing. Also explain why it's the only ideal solution?

**Comment by Santhosh-Sellavel** [comment]
Waiting proposals

**Comment by Santhosh-Sellavel** [comment]
Thanks, @parasharrajat for jumping in here can you recall any previous issue ids which we can link here?

**Comment by Santhosh-Sellavel** [comment]
@puneetlath What do you say then?

**Comment by puneetlath** [comment]
I agree we should close in favor of https://github.com/Expensify/App/issues/10273.
