### ISSUE TITLE
Web - Profile - The text in quotes ("text") disappears from the profile name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10404]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to settings>Profile
3. Enter first name and second name, if this has not been done before
4. Put the first name and the second name in quotation marks

## Expected Result:
The first name and the second name must appear in quotation marks

## Actual Result:
The first name and second name disappear and appear blank

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com/Yulia1986Gerets

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184993093-0b2f8098-b104-4cdb-876b-7084b3ce86cb.mp4

https://user-images.githubusercontent.com/93399543/184998653-781a7ef9-0b68-4cd1-8887-dd137e7c14e4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
It seems this is coming from the back-end, we use this regex `(\\w+([\\s_\\-\\.]+\\w+)*)(\/\\w+([\\s_\\-\\.]+\\w+)*)*`. Maybe we should add this validation to the front-end as well instead of sending it through to the API.

**Comment by pecanoro** [comment]
Then that is a discussion to have with the rest of the team since we usually don't want to ease regex rules. I will post in the channel.

**Comment by mallenexpensify** [comment]
Holding on posting the job per discussion. 

> I will post in the channel.

@pecanoro , do you have a link to where you posted?!?!

**Comment by pecanoro** [comment]
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1661172941760109

**Comment by pecanoro** [comment]
So we are probably changing this in the backend instead. I will take care and change the labels for it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
