### ISSUE TITLE
[HOLD #11768] Web- Chat - Transition using the back button does not work correctly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with an account that has multiple chats
3. Open any chat
4. Open a different chat
5. And any other again
6. Click the browser's back button

## Expected Result:
The transition back must be consecutive in the reverse order

## Actual Result:
Transition using the back button does not work correctly

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184999559-881cb44b-0e6d-4d9e-aa9a-ee0a80f3c2d7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Seems like this happens on production, so I don't think it should be a deploy blocker.

**Comment by marcaaron** [comment]
I am pretty sure this is a duplicate and related to some issues we have that are on hold so going to put this one on HOLD as well.

**Comment by johncschuster** [comment]
@marcaaron do you feel this issue should still be on `HOLD`? I'm on both the Triage Team and the BugZero team, so I can manage this one – just want to get a sense of where we should be.

**Comment by marcaaron** [comment]
yes, I would lump this in with the other navigation issues and work with @puneetlath in the navigation tracking issue

**Comment by johncschuster** [comment]
OK perfect, I just checked that GH – looks like this issue is already in the tracking list. I'm going to downgrade the label of this issue to `Weekly` and keep it bumping so it doesn't erode and close.

**Comment by puneetlath** [comment]
Added to the tracking issue and re-assigned to @JmillsExpensify.

**Comment by JmillsExpensify** [comment]
Check the tracking issue for the latest updates.

**Comment by JmillsExpensify** [comment]
Updated to weekly given the hold.

**Comment by JmillsExpensify** [comment]
Still holding.

**Comment by JmillsExpensify** [comment]
Still held as this initiative goes through the design process.

**Comment by JmillsExpensify** [comment]
Still holding on the larger react navigation project.

**Comment by JmillsExpensify** [comment]
Still held on the larger navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation. No ETA.

**Comment by JmillsExpensify** [comment]
Same same.

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Coming off hold very soon!

**Comment by JmillsExpensify** [comment]
Working on testing this week.

**Comment by JmillsExpensify** [comment]
Still trying to make time. Low priority.

**Comment by JmillsExpensify** [comment]
> The transition back must be consecutive in the reverse order

Just re-tested and this works perfectly!

**Comment by JmillsExpensify** [comment]
Reported by QA so nothing due for issue reporting.
