### ISSUE TITLE
Web - Forgot password - If the username is long, the password input field is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the sign in page of new Expensify
2. Enter your login details but not your password (use long login name)
3. Press Forgot? on the password page

## Expected Result:
The structure of the password input window should not be disturbed

## Actual Result:
If the username is long, the password input field is broken

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/185015600-553d95cc-543e-490a-a391-80079e2cc165.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Offending PR: https://github.com/Expensify/App/pull/10265
Offending Commit: https://github.com/Expensify/App/commit/a3e8e2e68affb7264e64efb9df032c326dc95907
