### ISSUE TITLE
[$1000] Web - Sign in - The banner size changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. On Sign in type your username
3. Type your password
4. Type wrong 2FA
5. Tap on Sign in

## Expected Result:
The page size not changing

## Actual Result:
The banner size changes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/185096701-f91dce4e-cf70-4f96-b078-1cd3ea4feb24.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01e96adbe9e8d8f9b0

**Comment by wildan-m** [comment]
## Proposal

### Problem
Not sure, but I guess the layout resized when the validation message toggled.

### Workaround

According to this link:

https://www.geeksforgeeks.org/how-to-define-two-column-layout-using-flexbox/#:~:text=Approach%3A%20To%20create%20a%20two,all%20will%20come%20as%20columns. 

We are required to add `100vh` height to create two column layout with a flexbox.

### Implementation

1. Add new `100vh` sizing item:

```diff
diff --git a/src/styles/utilities/sizing.js b/src/styles/utilities/sizing.js
index 52d4520a1..13e6bf22a 100644
--- a/src/styles/utilities/sizing.js
+++ b/src/styles/utilities/sizing.js
@@ -47,4 +47,8 @@ export default {
     wAuto: {
         width: 'auto',
     },
+
+    hvh100: {
+        height: '100vh',
+    },
 };
```

2. Apply 100vh 

```diff
diff --git a/src/pages/signin/SignInPageLayout/index.js b/src/pages/signin/SignInPageLayout/index.js
index 523b22fa7..5262ce7ea 100644
--- a/src/pages/signin/SignInPageLayout/index.js
+++ b/src/pages/signin/SignInPageLayout/index.js
@@ -31,6 +31,7 @@ const SignInPageLayout = (props) => {
         <SignInPageContent
             welcomeText={props.welcomeText}
             shouldShowWelcomeText={props.shouldShowWelcomeText}
+            style={styles.hvh100}
         >
             {props.children}
         </SignInPageContent>
@@ -43,6 +44,7 @@ const SignInPageLayout = (props) => {
             style={[
                 styles.flex1,
                 StyleUtils.getBackgroundColorStyle(backgroundStyle.backgroundColor),
+                styles.hvh100,
             ]}
             onPress={() => {
                 Link.openExternalLink(backgroundStyle.redirectUri);
```

Demo:

https://user-images.githubusercontent.com/11847279/189296490-cf87add5-407c-4d0b-83eb-db3cb8a250b6.mp4

**Comment by laurenreidexpensify** [comment]
@puneetlath can you please take this one over for @NikkiWines who is OOO this week. Thanks

**Comment by Santhosh-Sellavel** [comment]
I'm not sure why would we need this?

**Comment by Santhosh-Sellavel** [comment]
No this would cause regressions in iPads!

**Comment by laurenreidexpensify** [comment]
now $500

**Comment by wildan-m** [comment]
# Proposal Update (3rd)

@Santhosh-Sellavel, please have a look at my 3rd workaround here.

In this workaround, we dynamically set the graphic column with dimension. This way its height will not affect the left column height and I think it will not create regression.

```diff
diff --git a/src/pages/signin/SignInPageLayout/index.js b/src/pages/signin/SignInPageLayout/index.js
index ebe72e30e..0febe0edc 100644
--- a/src/pages/signin/SignInPageLayout/index.js
+++ b/src/pages/signin/SignInPageLayout/index.js
@@ -1,6 +1,6 @@
 import _ from 'underscore';
 import React from 'react';
-import {View, Pressable} from 'react-native';
+import {View, Pressable, Dimensions} from 'react-native';
 import PropTypes from 'prop-types';
 import SignInPageContent from './SignInPageContent';
 import withWindowDimensions, {windowDimensionsPropTypes} from '../../../components/withWindowDimensions';
@@ -38,11 +38,14 @@ const SignInPageLayout = (props) => {
 
     const hasRedirect = !_.isEmpty(backgroundStyle.redirectUri);
 
+    const screenHeight = Dimensions.get('window').height;
+
     const graphicLayout = (
         <Pressable
             style={[
                 styles.flex1,
                 StyleUtils.getBackgroundColorStyle(backgroundStyle.backgroundColor),
+                {height: screenHeight},
             ]}
             onPress={() => {
                 Link.openExternalLink(backgroundStyle.redirectUri);
```

**Comment by Santhosh-Sellavel** [comment]
We already have height using withWindowDimensions, I am not sure **why** height must be set here. 

Please include this in proposal
What's causing?
Why this fix?, how will it address the issue?

**Comment by Santhosh-Sellavel** [comment]
@puneetlath Please bump it down to weekly thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by wildan-m** [comment]
@mvtglobally, please try to zoom in on the screen until the left column content overflowed the browser height.

Just check it in staging and the banner size still changes.


https://user-images.githubusercontent.com/11847279/192677258-84a56267-b05e-4f91-9861-3ed93696580e.mp4

**Comment by laurenreidexpensify** [comment]
Price doubled

**Comment by mvtglobally** [comment]
Still Issue not reproducible during KI retests. (Second week)

**Comment by wildan-m** [comment]
@mvtglobally, Its size does not change now, but it will move when the left side overflows. Is that expected behavior? Please watch my video here:

https://user-images.githubusercontent.com/11847279/192677258-84a56267-b05e-4f91-9861-3ed93696580e.mp4
