### ISSUE TITLE
Desktop - Error message appears when update workspace settings in offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App with new user
2. Navigate to General settings
3. Go offline
4. Change the workspace currency and name
5. Tap on Save

## Expected Result:
A message about  Offline should appear.

## Actual Result:
Error message "An error occurred updating the workspace. please try again." is displayed if try to update the workspace offline.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.1.88-13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Bug5691836_Screen_Shot_2022-08-16_at_9 14 51_PM" src="https://user-images.githubusercontent.com/43996225/185024494-58f71587-933a-4bf2-b88d-860be311d457.png">

https://user-images.githubusercontent.com/43996225/185024500-c546953a-9a2c-4197-81d9-ad5fd7cb724c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Closing as we are currently refactoring this and it should be fixed soon-ish™️
