### ISSUE TITLE
[$250] iOS - Split Bill - The selected user email is covered by comment input when keypad opens

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app iOS and login
2. Click on the green plus button in the LHN, then Split Bill
3. Enter an amount and then Next
4. Select a couple of attendees from the list
5. Focus on the field to add a comment

## Expected Result:
The comment field should not cover the contact selected

## Actual Result:
The comment field covered by the contact selected

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** v1.1.88-13
**Reproducible in staging?:** y
**Reproducible in production?:** y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/185137713-29dd0ec7-51f8-4cd8-977a-eb92f9797782.png" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/185138686-107d63c8-6e2b-4a90-bfb6-c44a43e56d5c.MP4

**Upwork job URL:** https://www.upwork.com/jobs/~01d17ff01e6965e6f4
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Good candidate for external!

**Comment by michaelhaxhiu** [comment]
@parasharrajat are you saying this should be closed, or do you mean it's a feature-request?

**Comment by NikkiWines** [comment]
Sounds like we're in agreement that this isn't work fixing / modifying at the moment. Closing!
