### ISSUE TITLE
[$250] Create a new linter to find missing translated errors

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#10449]
Context https://expensify.slack.com/archives/C03TQ48KC/p1660838478754859

# Problem

In actions files we are adding some default error messages. Given we are not in a react component, it's easy to forget the error messages need to be localized and them being errors and some very uncommon, it will be very hard for anyone to notice they are not localized.

# Solution

Figure out if we can build a linter that fails whenever we have a call to `DateUtils.getMicroseconds()` and not a call to `Localize.translateLocal`.  Code usually looks [like this](https://github.com/Expensify/App/pull/10374/files#diff-5fd7c80f3a9b43595640753f4037ca2b7d0bebeca557a20c4a06f89dc5028ccfR526):
```
                        errors: {
                            [DateUtils.getMicroseconds()]: "Your changes couldn't be saved. The workspace was modified while you were offline, please try again.",
                        },
```

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1560412237747277824/job-details)
[external](https://www.upwork.com/jobs/~01180b998fec75b136)

**Comment by Sheharyar566** [comment]
I'd love to take on this issue. Submitted proposal on Upwork

**Comment by iwiznia** [comment]
@Sheharyar566 please follow [the instructions](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) for proposals

**Comment by mdneyazahmad** [comment]
## Proposal

1. We need to create a custom rule in `eslint-config-expensify`.
2. Install the package in the app.
3. Add localization message in `en.js` and `es.js` file.
4. Fix the linting error by replacing hard coded string with `Localize. translateLocal`.

```javascript
const _ = require('underscore');
const {isInActionFile} = require('./utils');

const message = require('./CONST').MESSAGE.PREFER_LOCALIZATION;
const astUtil = require('./utils/astUtil');

/**
 * @param {Object} node
 * @returns {Boolean}
 */
function isDateUtilsUsedAsProperty(node) {
    const dateUtilsProperties = _.filter(node.properties, (property) => {
        const keyNode = property.key;
        const valueNode = property.value;

        if (!astUtil.isCallFromObject(keyNode, 'DateUtils')) {
            return false;
        }
        
       // Maybe, we do not need this check
        if (astUtil.getMethodName(keyNode) !== 'getMicroseconds') {
            return false;
        }

        if (astUtil.isCallFromObject(valueNode, 'Localize')) {
            return false;
        }

        return true;
    });

    return dateUtilsProperties.length;
}

module.exports = {
    create: context => ({
        ObjectExpression: (node) => {
            if (!isInActionFile(context.getFilename())) {
                return;
            }

            if (!isDateUtilsUsedAsProperty(node)) {
                return;
            }

            context.report(node, message);
        },
    }),
};
```

#### I have few questions:
1. Do we need to explicitly check for `getMicroseconds` or any property will produce the error?
2. `Localize` has 3 methods `translate, translateLocal, arrayToString`. Do we only need to allow `translateLocal`?

### Result
<img width="909" alt="Screenshot 2022-08-19 at 8 18 38 PM" src="https://user-images.githubusercontent.com/77761491/185645480-e498e89f-33d3-491b-822a-c57d89752745.png">


### Fixed
<img width="834" alt="Screenshot 2022-08-19 at 8 03 01 PM" src="https://user-images.githubusercontent.com/77761491/185644696-27e4e75f-d36c-4c61-9d04-a187275f0d2b.png">

commit: https://github.com/mdneyazahmad/eslint-config-expensify/commit/e4aa6d0ffeff60827eb6b76704cba1bf5902518b

**Comment by iwiznia** [comment]
> Do we need to explicitly check for getMicroseconds or any property will produce the error?

Explicitly

> Localize has 3 methods translate, translateLocal, arrayToString. Do we only need to allow translateLocal?

Oh, this is a linter, so just people developing will see it, so no need to localize, we only require localizing things used in the app itself that could be seen by users.

The proposal looks good to me, @rushatgabhane what do you think?

**Comment by mdneyazahmad** [comment]
@rushatgabhane PR is raised.

**Comment by adelekennedy** [comment]
@mdneyazahmad will you apply to the job [here](https://www.upwork.com/jobs/~01180b998fec75b136)?

**Comment by iwiznia** [comment]
Oh sorry!

**Comment by adelekennedy** [comment]
Reposted [here](https://www.upwork.com/jobs/~01538d536232972b67) - @mdneyazahmad and @rushatgabhane please apply!

**Comment by rushatgabhane** [comment]
@adelekennedy applied, thanks

**Comment by mdneyazahmad** [comment]
@adelekennedy offer accepted, Thank you!

**Comment by adelekennedy** [comment]
Paid!
