### ISSUE TITLE
[$500] Enforce minimum password length on NewDot

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#10493]
### Problem

We require that passwords are minimum 3 characters, but the NewDot password form does not enforce this requirement therefore when someone submits the form with a password < 3 characters, usually by mistake we receive an internal error. 

### Why is this important?
Wastes engineering time to look into issues that aren't real issues

### Solution

Implement the requirement for passwords to be greater than 3 characters on the NewDot form. 

associated issue: https://github.com/Expensify/Expensify/issues/224143

**Comment by Christinadobrzyn** [comment]
Created Job in Upwork

Internal posting - https://www.upwork.com/ab/applicants/1562124375160983552/job-details
External posting - https://www.upwork.com/jobs/~014ed615faba3ad0cc

**Comment by Christinadobrzyn** [comment]
I hope I did this right, moving an Expensify/Expenisfy [job](https://github.com/Expensify/Expensify/issues/224143) to Expensify/App. Let me know if any of this is wrong!

**Comment by varshamb** [comment]
### Proposal

There are two places where there is no password validation on the frontend.
i.e. `PasswordPopover` and `AddSecondaryLoginPage`

We need to use `ValidationUtils.isValidPassword()` before submitting the form and we're good to go!

**Comment by Christinadobrzyn** [comment]
Added a design label to this GH for design input!

**Comment by michelle-thompson** [comment]
I think this could be an opportunity for push to page. In either case, the error can easily be missed as it is. So we should use the brick road pattern here. cc @Expensify/design 

![image](https://user-images.githubusercontent.com/43361905/187155236-19c402e6-24e7-45f4-81d6-ef1b2a97bd68.png)

Another suggestion is copy - if the minimum password length is the problem then the error message should reflect that.

**Comment by ctkochan22** [comment]
Ooo I like that our guidelines for BrickRoad is lightly discussed here: https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern

**Comment by shawnborton** [comment]
I agree, I don't think we realized that we'd prompt for a password inline with the button when we first designed this. So I do like the idea of pushing out to a new page with the form input.

**Comment by shawnborton** [comment]
I think we'd want to use that same red brick road error message styling here as well. I think it should be available as a component soon once a separate PR gets merged cc @jasperhuangg

**Comment by ctkochan22** [comment]
I can look and see if what PR that is

**Comment by ctkochan22** [comment]
Crazy week, will look tomorrow

**Comment by jasperhuangg** [comment]
Hey @rushatgabhaneI sorry I missed your message! The PR is definitely on prod now, you wanna look for usages of the `DotIndicatorMessage` component.

**Comment by Christinadobrzyn** [comment]
doubled price - $500

**Comment by rushatgabhane** [comment]
@Christinadobrzyn price is good

**Comment by jasperhuangg** [comment]
Yup, I agree that the price is good, should be super simple to implement–just adding some validation [here](https://github.com/Expensify/App/blob/cadec8cf43067da16b58c4910f8d40d0801f38f7/src/pages/settings/NewPasswordForm.js#L53-L55) and [here](https://github.com/Expensify/App/blob/cadec8cf43067da16b58c4910f8d40d0801f38f7/src/pages/SetPasswordPage.js#L83-L95)

**Comment by thesahindia** [comment]
Found a bug related to password and was searching the GH to check if there are any existing issue and here I am. 

We have 3 places where this should be implemented. Two are already mentioned [here](https://github.com/Expensify/App/issues/10493#issuecomment-1255351385) third one is at add bank account page

https://user-images.githubusercontent.com/83179295/192365618-8521f1e8-edee-4d79-9a40-e6da09fae914.mov

We aren't checking if it's a valid password and sending the api request also the field isn't red.  Can include this as well?

**Comment by thesahindia** [comment]
Also few questions:- 
1. Are we planning to use push to page for password popover?
2. How are we planning to use red dot indicator for error when there are two fields? Let's take the example of add secondary login page. There are two fields on that page: email/phone and password. 
When there's an error at email/phone field where should we show the error message below that field with red dot indicator or should we display error for both the field at the same place (just a little below the last field, the same as image below but with the red dot indicator) 
<img width="376" alt="Screenshot 2022-09-27 at 1 24 06 AM" src="https://user-images.githubusercontent.com/83179295/192367618-03dd8782-37b7-4969-ba79-7ac6749a199b.png">

**Comment by shawnborton** [comment]
If a specific field has an error, I think we should:

- Make the outline of that field red
- Place the red brick/dot indicator style error message below it

**Comment by shawnborton** [comment]
If there is an error related to the form submission itself, then that would appear directly above the submit button.

**Comment by ctkochan22** [comment]
All the questions are answered yeah? Thanks @shawnborton

**Comment by ctkochan22** [comment]
No proposals

**Comment by mvtglobally** [comment]
Can you guys check issue https://github.com/Expensify/App/issues/11348. Someone recommended to close it in favor of this issue. Should I close it?

**Comment by ctkochan22** [comment]
Punting. Still want to outline the instances this is used and make a clear plan of action

**Comment by JmillsExpensify** [comment]
Should we do this at all now that we're removing passwords in favor of magic links?

**Comment by ctkochan22** [comment]
Yeah, some of it would be easy like updating submitting a password for CreateBankAccount, but the rest would be unnecessary changes for somethign that won't exit soon

**Comment by ctkochan22** [comment]
I say we close and can revisit later if it still an issue

**Comment by JmillsExpensify** [comment]
Ok cool, let's close then.

**Comment by JmillsExpensify** [comment]
Updating the UX on the password page? We're going to deprecate this page soon with passwordless.
