### ISSUE TITLE
Web - App crashes in group participant page @rushatgabhane

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Go to a group
3. Click on the group header to open participant page

## Expected Result:
Participant page is opened in RHN

## Actual Result:
App crashes 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:**  1.1.88-14
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** any
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="reproduced" src="https://user-images.githubusercontent.com/43996225/186217531-9c607ef3-da21-43c7-9310-9798eb018b8f.png">

https://user-images.githubusercontent.com/43996225/186217567-98e158b0-73d9-467f-ad1b-74c2a3d4dd2d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
See thread https://expensify.slack.com/archives/C01GTK53T8Q/p1661266519633919 but we are unable to easily reproduce this error, it might require getting an account in some specific state, so going to remove deploy blocker for now.

**Comment by arosiclair** [comment]
New repro steps we're given in that don't work unfortunately:

https://user-images.githubusercontent.com/6833644/186519177-43b62f2d-6c03-4dd3-ac6e-e7fe287b0864.mov

This seems like a rare edge case so I can't reproduce this. However, I'll add some safety code to at least ensure this specific crash doesn't occur again

**Comment by jboniface** [comment]
@laurenreidexpensify @rushatgabhane needs reporting bonus job

**Comment by AndrewGable** [comment]
@Expensify/contributor-management - I think both might be OOO, can someone please handle this? Thanks

**Comment by mallenexpensify** [comment]
I gotcha @rushatgabhane , thanks for the group ping @AndrewGable 
Rushat, please accept and confirm in a comment when you have https://www.upwork.com/jobs/~01b4093820c34c57f7

**Comment by mallenexpensify** [comment]
All paid!!
