### ISSUE TITLE
[HOLD #11768] Navigating Back takes the user to the home screen on the web - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Steps WEB:
  1. Open the app from the home URL (https://staging.new.expensify.com/).
  2. Opening a new Chat from RHN (NewChat Page)
  3. Go Back.
Steps mWEB:
  1. Open the app from the home URL (https://staging.new.expensify.com/) on Android Chrome.
  2. Opening a new Chat from RHN(NewChatPage).
  3. Navigate back via pressing the Hardware Back button.
  
## Expected Result:
The user should not leave the app.

## Actual Result:
User is taken out of the app.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Potentially related to https://github.com/Expensify/App/issues/10506

https://user-images.githubusercontent.com/43995119/186317032-d1f85f18-d364-45c8-92ea-704ffa95d62d.mp4

https://user-images.githubusercontent.com/43995119/186317068-ae78c9d6-3119-4939-9977-85df2018d659.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659433481366129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Looks like a good external issue

**Comment by trjExpensify** [comment]
@marcaaron hip check on this navigational issue. Should it go on hold pending the navigation 2.0 doc?

**Comment by marcaaron** [comment]
Yes I'm going to put this on HOLD. I am pretty sure why this is happening and the fix for it won't be straightforward.

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by trjExpensify** [comment]
Still on hold for the wider react-navigation revisit.

**Comment by Beamanator** [comment]
I wonder if this can be taken off hold or reassigned?

**Comment by trjExpensify** [comment]
Hm, but @puneetlath is still working on the plan for navigation and that will take care of this issue?

**Comment by Beamanator** [comment]
True trueeee... Ok I'll assign Puneet and unassign myself :D

**Comment by JmillsExpensify** [comment]
Check the tracking issue for the latest updates.

**Comment by JmillsExpensify** [comment]
Still holding.

**Comment by JmillsExpensify** [comment]
Still held as the linked issue goes through the design process.

**Comment by JmillsExpensify** [comment]
Still holding on the larger react navigation project.

**Comment by JmillsExpensify** [comment]
Still held on the larger navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation. No ETA.

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Coming off hold very soon!

**Comment by JmillsExpensify** [comment]
Alrighty, I just got in and tested this one. Good news, I think we're done here! After a fresh sign-in I landed in the workspace chat (in this case). I think opened a new chat. Upon pressing the browser's back button, I was taken to the first chat. Pressing back again did take me out of the app, but that was consistent with the history for this tab, which is our design.

**Comment by JmillsExpensify** [comment]
I'm going to file this one in the payout part of this project and I'll come back to it later this week.

**Comment by JmillsExpensify** [comment]
Still working through this.

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
@parasharrajat Do you mind re-testing this one? I'm working through a backlog of issues and I'd like to get this one closed out and make sure you're paid. Thanks!

**Comment by JmillsExpensify** [comment]
In the future make sure to record for posterity. It's fine for now given how closely you work with Expensify. 

Payment summary: $250 for issue reporting.

**Comment by JmillsExpensify** [comment]
$250 payment approved for @parasharrajat based on summary above.
