### ISSUE TITLE
[Payment Pending] User Typing... area gets hidden after entering multiple lines - Reported by @Santhosh-Sellavel by 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open new dot and open any chat
2. Enter multiline text in the composer

## Expected Result:
User Typing area should be available, and composer should not shift up and down.

## Actual Result:
The user Typing area is taken by the composer box after entering multiple lines. so when the user typing appears composer shifts up and down,

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186325601-3605917a-0d3f-42fc-84b3-2facd1040937.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659980797019179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Seems like I'm unable to reproduce this issue right now in production or staging cc @Santhosh-Sellavel
Can we maybe provide some more detailed reproduction steps? 

#### Prod
https://user-images.githubusercontent.com/31285285/186539302-da9055c2-8220-4517-8e8a-5b1656a3780f.mov

#### Staging

https://user-images.githubusercontent.com/31285285/186539623-f21c7c17-e814-496c-9016-373a7235eafa.mov

**Comment by Santhosh-Sellavel** [comment]
@jasperhuangg 

Refer the video in Issue description and the issue still exists refer your video too.

The space below composer should be available.

Before typing anything in the composer box, there is fixed space below the composer.

After typing multiple lines, space below is missing.

**Comment by jasperhuangg** [comment]
> @jasperhuangg 
> 
> Refer the video in Issue description and the issue still exists refer your video too.
> 
> The space below composer should be available.
> 
> Before typing anything in the composer box, there is fixed space below the composer.
> 
> After typing multiple lines, space below is missing.
> 

@Santhosh-Sellavel gotcha, sorry I misunderstood what the problem was.

Seems like this can be exported.

**Comment by jasperhuangg** [comment]
> ## Proposal
>  Screen.Recording.2022-08-24.at.7.55.12.PM.mov 
> As we can see parent component has min height of 90 (`styles.chatItemComposeWithFirstRow`), timezone area 15 + 10(margin) and composer 40, , rest (90 - 40 -25) = 25 is free.
> 
> https://github.com/Expensify/App/blob/cd2f5692f9e054fb1cb8662c6c0680ae2a7a351d/src/pages/home/report/ReportActionCompose.js#L680-L684
> 
> When `ReportTypingIndicator` and `ExceededCommentLength` return null and `OfflineIndicator` is not rendered. There is no content in the view and it is empty so it does not occupy any space.
> 
> When there is only one line composer height is 40 and 25 will be free so there is space to render typing... so there is no shifting. When composer height increases it occupies the empty space and there is no space after composer. When user starts typing.... It does not have any space to the bottom and now when the typing... is rendered it shift the composer.
> 
> We need to apply a fixed height to reserve the space for displaying the typing... or other messages as inside the component.
> 
> ```
> <View style={[styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter, {height: 25}]}> 
> ```
> 
> We can apply the height directly or create a style object and apply it here. We can find a better value for the height 25 seems fine during my testing.
> 
> ### Result
>  Screen.Recording.2022-08-24.at.8.26.55.PM.mov

Can we see how it would look with the offline indicator? Turn your wifi off.

**Comment by Puneet-here** [comment]
### Proposal 

We just have to use `styles.chatItemComposeSecondaryRow` ( it was removed ) below
https://github.com/Expensify/App/blob/fe39ef8dbf1cf3b1faea811091e32dda9ba62b49/src/pages/home/report/ReportActionCompose.js#L680

**Comment by jasperhuangg** [comment]
@Puneet-here Ah yes, I was actually the one to remove that [here](https://github.com/Expensify/App/pull/10140/files#diff-7fa482b2895f4e36a2a3ad8233496489c6de1256a8c992524e2fc072aaba43f8L676-R680), reason being it was causing a display issue for the Global Offline Indicator on mobile. If we were to just add it back directly, then it would mess up the offline indicator (notice the extra spacing)
<img width="375" alt="Screen Shot 2022-08-26 at 4 32 13 PM" src="https://user-images.githubusercontent.com/31285285/186859614-877f8833-1ad3-4420-9cc2-c7fec2e75649.png">

I can actually just snag this and open up a PR fixing this since I was the one to cause this regression.

**Comment by jasperhuangg** [comment]
Opened up a PR fixing the issue since I was the one to cause it in a PR that was deployed a few weeks ago.

Regardless, thank you for your proposals @mdneyazahmad @Puneet-here 

Let's make sure to get @Santhosh-Sellavel compensated for discovering the regression @NicMendonca

**Comment by Santhosh-Sellavel** [comment]
> Let's make sure to get @Santhosh-Sellavel compensated for discovering the regression @NicMendonca 

@NicMendonca  bump!

**Comment by NicMendonca** [comment]
Let's keep these Open while there's still a deliverable so that we can access via K2 :) 

@Santhosh-Sellavel can you please accept[ the offer ](https://www.upwork.com/jobs/~013736493b99eda689)I sent?

**Comment by NicMendonca** [comment]
@Santhosh-Sellavel paid! sorry for the delay!

**Comment by Santhosh-Sellavel** [comment]
@jasperhuangg 
Issue still reproducible in Mobile Apps

**Comment by Santhosh-Sellavel** [comment]
bump @jasperhuangg

**Comment by jasperhuangg** [comment]
@Santhosh-Sellavel sorry for the delay, https://github.com/Expensify/App/pull/11217 should fix the issue and was just merged
