### ISSUE TITLE
[HOLD for payment 2022-09-28] [$250] Prevent SVG images from being uploaded as profile pictures - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to profile
 2. Tap on avatar > Upload photo
 3. Use svg
 
## Expected Result:
We should prevent the svg from being uploaded

## Actual Result:
The svg shows up correctly at profile page after you upload it but it shows up as black everywhere and changes to black in profile page after you close it and come back

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186324370-cd43db1a-779c-4833-9bd7-3b75957f7202.mov

**Upwork URL:** https://www.upwork.com/jobs/~01e573794d911ea020
**Issue reported by:** @Puneet-here
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal 

We can create a function for validation -
```js
    isValidExtension(image) {
        const {fileExtension} = FileUtils.splitExtensionFromFileName(image.name);
        return _.contains(CONST.AVATAR_ALLOWED_EXTENSIONS, fileExtension);
    }
```
We have `splitExtensionFromFileName` function here, we can move it to [FileUtils](https://github.com/Expensify/App/blob/main/src/libs/fileDownload/FileUtils.js)
https://github.com/Expensify/App/blob/cd2f5692f9e054fb1cb8662c6c0680ae2a7a351d/src/components/AttachmentModal.js#L115-L120

Call `isValidExtension` here -
https://github.com/Expensify/App/blob/cd2f5692f9e054fb1cb8662c6c0680ae2a7a351d/src/components/AvatarWithImagePicker.js#L157-L163
```js
        if (!this.isValidExtension(image)) {
            this.showErrorModal(
                this.props.translate('avatarWithImagePicker.imageUploadFailed'),
                this.props.translate('avatarWithImagePicker.notAllowedExtension'),
            );
            return;
        }
```

We have to decide the error text and extensions that we don't wanna allow.

**Comment by kadiealexander** [comment]
>We have to decide the error text and extensions that we don't wanna allow.

Great point @thesahindia, I've brought that to Slack for discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661338683100219) if you'd like to weigh in!

**Comment by kadiealexander** [comment]
Still waiting on answers in Slack.

**Comment by kadiealexander** [comment]
Bumped again!

**Comment by kadiealexander** [comment]
As discussed in Slack, we need to determine the list of file types allowed. @ctkochan22 it was suggested that you might be able to hunt this down?

**Comment by ctkochan22** [comment]
So these are the files we accept in OldDot: `['jpg', 'jpeg', 'png', 'gif', 'bmp']` 
[Source](https://github.com/Expensify/Web-Expensify/blob/70428f2085b43278101202e816373fa5a98ef140/site/app/settings/userDetailsForm.jsx#L190)

**Comment by trjExpensify** [comment]
Job on Upwork here: https://www.upwork.com/jobs/~01e573794d911ea020

**Comment by mananjadhav** [comment]
I didn't see that the proposal was already posted. @ctkochan22,  @thesahindia's [proposal](https://github.com/Expensify/App/issues/10514#issuecomment-1225380562) looks good to me. 

@thesahindia Once assigned can you get the error message copy from the slack channel?

🎀 👀 🎀 
C+ reviewed

**Comment by trjExpensify** [comment]
👋 @thesahindia can you accept please? https://www.upwork.com/jobs/~01e573794d911ea020

**Comment by thesahindia** [comment]
> 👋 @thesahindia can you apply please? https://www.upwork.com/jobs/~01e573794d911ea020

Applied. Thanks.

**Comment by trjExpensify** [comment]
offer sent, @thesahindia.

**Comment by thesahindia** [comment]
Asked for the error message [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662668904628029)

**Comment by trjExpensify** [comment]
I've bumped the thread to see if we have this error message on OldDot already to re-use in English, and then obtain a Spanish translation for.

**Comment by trjExpensify** [comment]
Kewl. As discussed in the thread, we're going to follow a similar format to this ([English](https://github.com/Expensify/App/blob/9ad6ec950b4dd7231376649093b667f24879a1ad/src/languages/en.js#L125)/[Spanish](https://github.com/Expensify/App/blob/9ad6ec950b4dd7231376649093b667f24879a1ad/src/languages/es.js#L125)).  Thanks, @iwiznia. 

`Profile picture must be one of the following types: jpg, jpeg, png, gif, bmp.`
`La foto de perfil debe ser de uno de los siguientes tipos: jpg, jpeg, png, gif, bmp.`

**Comment by trjExpensify** [comment]
@thesahindia - paid $250 for the fix! 
@mananjadhav - paid $250 for C+! 
@Puneet-here - sent you an offer for reporting, please accept and I'll settle up.

**Comment by trjExpensify** [comment]
Awesome, settled up with you now @Puneet-here. Thanks, everyone! 🎉
