### ISSUE TITLE
[HOLD for payment 2022-09-15] [$250] Cursor should be pointer on :large_green_circle: in image edit modal - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to profile
 2. Tap on avatar > Upload photo
 3. Hover over the :large_green_circle:
 
## Expected Result:
The cursor should be pointer

## Actual Result:
The cursor is default

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186323952-c9e46ed4-76ed-4a55-941b-e044c8b378fd.mov

**Upwork URL:** https://www.upwork.com/jobs/~015a8a755e0530fbd6
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659715906489109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
### Proposal

`cursor: pointer` need to be set on page `AvatarWithImagePicker.js`

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- Need to set `cursor: pointer` at `/src/components/AvatarCropModal/Slider.js` in styles.sliderBar
https://github.com/Expensify/App/blob/334bd7da06d3221035994328fda7dd4afeb62730/src/components/AvatarCropModal/Slider.js#L31

- change here 

https://github.com/Expensify/App/blob/334bd7da06d3221035994328fda7dd4afeb62730/src/styles/styles.js#L2635

add : `cursor: pointer` into style 

**Result**

**Comment by trjExpensify** [comment]
Upwork job: https://www.upwork.com/jobs/~015a8a755e0530fbd6

**Comment by Harshdeepjoshi** [comment]
### Proposal
replace https://github.com/Expensify/App/blob/334bd7da06d3221035994328fda7dd4afeb62730/src/components/AvatarCropModal/Slider.js#L31
to this
`<View style={[styles.sliderBar, styles.cursorPointer]}>`

**Comment by Puneet-here** [comment]
The issue is incomplete. The expected result is seeing cursor pointer at green slider know and the cursor should be grab type when grabbing image.

**Comment by Puneet-here** [comment]
Hmm we can add `cursor: 'grabbing'` here 
https://github.com/Expensify/App/blob/e504cc3d883a51294a3aca375dee28e66596edf4/src/styles/styles.js#L2635-L2638

but we still have second part left. Here the cursor should be grab type when you grab and drag the image.
I will try finding the solution for it.

https://user-images.githubusercontent.com/101883770/186486466-ba5eeb53-c1ad-4e60-8610-4741d528bbc3.mov

**Comment by dhairyasenjaliya** [comment]
Do we need to change the cursor inside image drag as in the issue it is not mentioned if yes then I need to update the proposal https://github.com/Expensify/App/issues/10513#issuecomment-1225265727

**Comment by varshamb** [comment]
Updated Proposal

We should use `cursor: 'grab'` in `sliderKnob` and not `sliderBar`. Because clicking on `sliderBar` does nothing, and hence it should not have cursor of type grab.

https://github.com/Expensify/App/blob/334bd7da06d3221035994328fda7dd4afeb62730/src/styles/styles.js#L2625

And for the image, we can add `cursor: grab` in styles.imageCropContainer

https://github.com/Expensify/App/blob/334bd7da06d3221035994328fda7dd4afeb62730/src/styles/styles.js#L2617

**Comment by mananjadhav** [comment]
@varshamb's proposal looks good to me here as it covers the slider as well as the image container4

With just one question @Luke9389 @trjExpensify , does it make sense to use `cursor: move` for the imageCropContainer?

🎀 👀 🎀 
C+ reviewed

**Comment by Puneet-here** [comment]
We should see grab cursor only when we are inside the circle (where we can actually grab) and grabbing when we grab the image. We does the same at attachment modal.

**Comment by trjExpensify** [comment]
Hm, actually.. I think `move` kinda' makes sense for the image container. Curious for @shawnborton opinion on that.

**Comment by dhairyasenjaliya** [comment]
Also by simply adding cursor: 'grab' into `styles.imageCropContainer` will not work as expected In safari when we drag the image it changes the edit cursor somehow 

Safari 

https://user-images.githubusercontent.com/47522946/186738946-05ff1adc-76a6-46c5-92cf-9cad0d530373.mov

chrome  

https://user-images.githubusercontent.com/47522946/186739422-cfe1b026-db1b-4ec9-b207-58465e2fc2cf.mov

**Comment by shawnborton** [comment]
The move cursor makes sense to me for moving the image around. Then in terms of the range slider, I think the pointer makes sense - just taking a look at [bootstrap](https://getbootstrap.com/docs/5.0/forms/range/) for inspiration on that one.

**Comment by mananjadhav** [comment]
> We should see grab cursor only when we are inside the circle (where we can actually grab) and grabbing when we grab the image. We does the same at attachment modal.

@dhairyasenjaliya  @Puneet-here you might be right, but as I mentioned in the comment before and other feedback, inside the circle, I feel it is appropriate to use `move` rather than `pointer` or `grab`.

@varshamb Can you update your proposal to handle this please?

**Comment by trjExpensify** [comment]
Oh, I do like that animation on the range slider to provide feedback when it's selected @shawnborton.

**Comment by Puneet-here** [comment]
I am fine with the move cursor but we shouldn't be seeing move cursor where you can't move the image. The move cursor should only be shown in the circle because we can only move the image there not outside

**Comment by shawnborton** [comment]
That makes sense to me.

**Comment by mananjadhav** [comment]
Ahhh I get what you mean now.  Thanks for clarifying @Puneet-here.

@varshamb The cursor shouldn't be visible in the arcs where we don't move the image. 

Uploading Screen Recording 2022-08-26 at 9.04.08 AM.mov…

**Comment by varshamb** [comment]
> cursor shouldn't be visible in the arcs where we don't move the image

@mananjadhav we can move the image in the arcs as well. So i think we should show the cursor there as well.

[Screencast from 26-08-22 08:20:42 PM IST.webm](https://user-images.githubusercontent.com/111683206/186933935-1e314c4d-1a48-456b-9ae6-784763bf9c7a.webm)

**Comment by varshamb** [comment]
> Can you update your proposal to handle cursor: move please?

@mananjadhav sure, let's use `cursor: move` for `imageCropContainer` and `cursor: grab` for `sliderKnob`.

**Comment by Puneet-here** [comment]
@mananjadhav we can move the image in the arcs as well. So i think we should show the cursor there as well.

Hmm 🤔 I didn't know about it. Didn't expect that.

**Comment by Luke9389** [comment]
I think it's fine to use `move` for the whole thing. The circle is showing us what your image will look like, not blocking us from using that part of the UI. Does that make sense? 

It seems we all agree on pointer for the slider, so that's good.

**Comment by varshamb** [comment]
@mananjadhav okay, that works as well.


cursor: move for imageCropContainer and cursor: pointer for sliderKnob.

**Comment by mananjadhav** [comment]
Yeah @varshamb this looks fine. 

@Luke9389 we can go ahead with @varshamb's proposal.

**Comment by Luke9389** [comment]
OK cool. Thanks @mananjadhav. @varshamb you've got the 🟢 green light 🟢 to make a PR. Thanks!

**Comment by trjExpensify** [comment]
@varshamb - can you apply here when you get a second? https://www.upwork.com/jobs/~015a8a755e0530fbd6 Thanks!

**Comment by shawnborton** [comment]
Not overdue

**Comment by trjExpensify** [comment]
@varshamb @mananjadhav - can you accept the offers on Upwork please?

**Comment by Puneet-here** [comment]
@trjExpensify, I have applied also applied to the job.

**Comment by trjExpensify** [comment]
Excellent!

**Comment by mananjadhav** [comment]
Accepted @trjExpensify

**Comment by varshamb** [comment]
@trjExpensify  Accepted.

**Comment by trjExpensify** [comment]
Settled up with everyone, thanks guys! 🎉
