### ISSUE TITLE
Browserslist: caniuse-lite is outdated - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Reason:
Reason: caniuse-lite is used to correctly transpire the code to support the necessary browsers based on the data. When this is outdated, we may be pushing more poly-fills than needed to the build. This increases the bundle size.

## Expected Result:
we should find the dependent package and upgrade that.

## Actual Result:
Browserslist: caniuse-lite is outdated 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="644" alt="Screen Shot 2022-08-23 at 11 36 30 PM" src="https://user-images.githubusercontent.com/43995119/186323253-8decbc77-c3b7-4e0a-931e-95d852396c4a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659581404283719?thread_ts=1644345175.637679&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Pretty sure this goes to engineering > external

**Comment by danieldoglas** [comment]
I think this was updated with [this PR](https://github.com/Expensify/App/pull/10439)

**Comment by danieldoglas** [comment]
@mallenexpensify in this case we just need to pay the contributor for reporting. It was solved recently with our update for NPM

**Comment by mallenexpensify** [comment]
Thanks @danieldoglas (and Rajat for reporting)
@parasharrajat , can you accept the job here please https://www.upwork.com/jobs/~01e710c0363c442812.  Comment here when done and I'll pay you (sidenote... did payment as a milestone cuz testing something... paid amount will be the same, $250)

**Comment by mallenexpensify** [comment]
Paid! Thanks @parasharrajat
