### ISSUE TITLE
[$250] Mac / Safari  - Unread favicon - No unread favicon in the browser tab

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10528]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10041 

## Action Performed:
1 Login to the ND under Web/Safari as user A.
2. send DM to the user A
3. Observe favicon for the corresponding tab in the browser

## Expected Result:
The user should see a new Favicon if there are unread messages

## Actual Result:
Describe what actually happened
Favicon has no Unread mark if unread messages are present

Only on Safari. Chrome is OK

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web -  Safari

**Version Number:** v1.1.89-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5702224_Screenshot_2022-08-24_at_16 28 02](https://user-images.githubusercontent.com/43996225/186440610-01f6e6a8-d2b9-4188-b464-99d48247296d.png)

https://user-images.githubusercontent.com/43996225/186440595-879d66ba-440e-4587-860f-bc550275a525.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
Monthly - because even if the "unread" icon is not visible, there is that (x) suffix in the tab title which lets the user know that there are unread messages.

Other than that, @robertjchen I know you changed the favicon recently. Do you have more context on this? I think this could be externalised, what do you think?

**Comment by robertjchen** [comment]
Yeah, that's odd. I don't think swapping out the favicon could've caused this. Maybe it's a Safari-related bug? Let's externalize this for further investigation 👍

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~017abb228469426c2f)

**Comment by wildan-m** [comment]
It wouldn't be possible.

They purposefully don't allow dynamic changes/animations to the favicon

https://stackoverflow.com/questions/63781987/cant-change-favicon-with-javascript-in-safari

https://bugs.webkit.org/show_bug.cgi?id=75877

Other dynamic favicon samples that work on Chrome but will not work on Safari:
https://mathiasbynens.be/demo/dynamic-favicons
http://lab.ejci.net/favico.js/example-simple/

**Comment by robertjchen** [comment]
Got it, thanks for looking into this!

**Comment by bfitzexpensify** [comment]
OK, since this won't be possible to fix, we'll go ahead and close it out.
