### ISSUE TITLE
[HOLD] Web - Chat - "New" message indication is not showing for new messages that arrived

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Send a message from device B to device A to simulate the arrival of a new message
4. On device A, open the new chat

## Expected Result:
User expects there to be a message stating "New" with a green line indicating where the new message is

## Actual Result:
There is no "New" indication within the new chat.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:**  v1.1.89-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/186416416-f65507c8-b5a8-49d2-a97c-cf19e49c555c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@marcaaron is this something that would be covered by the project you're working on for the unread indicator?

**Comment by marcaaron** [comment]
I think it's more likely a recent bug but can put it on HOLD and/or assign it to me. Should be `Internal` either way.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
