### ISSUE TITLE
Web - User detail - Unable to copy the email address

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and login
2. Navigate to any chat tap on photo
3. Tap on copy icon

## Expected Result:
User is able to copy the email address

## Actual Result:
User is not able to copy the email address, clicking on it does not turn green

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.89-0

**Reproducible in staging?:**  Y

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/186425027-367f83a2-d6ad-4adc-b27d-30a5580dc9c7.mp4
<img width="1169" alt="Bug5702163_green" src="https://user-images.githubusercontent.com/43996225/186425053-3f8b3a87-fea2-43ba-a44c-261aea911cd7.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad & Applause internal team

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661324080933109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment]
Yes this is broken, and it is a deploy blocker -> easy to reproduce, and can't reproduce in Prod but can in Staging

**Comment by JmillsExpensify** [comment]
Depending on how we get on, I'd be fine with deploying with this issue and fixing in the next release.

**Comment by sketchydroide** [comment]
ok, there is still a workaround and it's not that hard, so that makes sense

**Comment by trjExpensify** [comment]
Yeah, I agree that I wouldn't hold the deploy on this issue. Should we remove the DB label then?

**Comment by sketchydroide** [comment]
yeah let's

**Comment by AndrewGable** [comment]
Fix incoming

**Comment by aneequeahmad** [comment]
@kavimuru oh i see this issue has been fixed and deployed on staging and prod. Am i eligible for reporting bonus ?

**Comment by AndrewGable** [comment]
@Expensify/contributor-management - Can someone pay @aneequeahmad for reporting the issue? Thanks

**Comment by mallenexpensify** [comment]
I'm on it. 
https://www.upwork.com/jobs/~016dc48f3d2b89154f
@aneequeahmad , please apply here and confirm in a post on this issue once you have. Thx

**Comment by mallenexpensify** [comment]
Reopen so I don't forget to pay :)

**Comment by aneequeahmad** [comment]
@mallenexpensify  I have applied, Thanks for mentioning.

**Comment by mallenexpensify** [comment]
Hired @aneequeahmad , let me know when you've accepted and I'll pay.

**Comment by aneequeahmad** [comment]
@mallenexpensify I have accepted the offer.

**Comment by mallenexpensify** [comment]
Paid! Thanks again for the help @aneequeahmad
