### ISSUE TITLE
Web - Login - Infinite spinner when logging in to the specified account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with the specified account

## Expected Result:
Login to the account should be without problems

## Actual Result:
Infinite spinner displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** iheretsutest+0102@gmail.com/Yulia1986Gerets

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://user-images.githubusercontent.com/93399543/186442337-2c2f64e1-6fe3-4950-8b8c-8474c5f693b9.mp4

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I can reproduce

**Comment by JmillsExpensify** [comment]
This one is bad. Let's keep the deploy blocker label.

**Comment by AndrewGable** [comment]
Discussing in Slack but our current understanding is it's related to this issue: https://github.com/Expensify/App/issues/9382

**Comment by AndrewGable** [comment]
@marcaaron fixed this in https://github.com/Expensify/Web-Expensify/pull/34671
