### ISSUE TITLE
Web - Workspace- User receives error message in JS console when offline in General settings

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10432
## Action Performed:
1. Access staging.new.expensify.com
2. Login and create a workspace
3. Navigate to the initial Workspace settings page
4. Go offline
5. Open the General Settings page
6. Verify the network tab in the JS console

## Expected Result:
User expects no error messages in the JS Console

## Actual Result:
User receives error messages

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** **1.1.89-0**
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/186474453-c3ce3033-3c53-4565-853f-b10cbfa3162a.mp4

https://user-images.githubusercontent.com/43996225/186474460-10fdd2c5-dc8a-4cba-90ab-81f7644bf161.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment]
This isn't a JS error message, this is only showing that we made an API call that failed (because we don't have a network connection)

It's possible that we may not have detected that the network connection wasn't working before we made the API call, but as far as I can tell after my first brief look there's no error here

**Comment by sketchydroide** [comment]
yeah I would agree

**Comment by luacmartins** [comment]
I agree and I think we should close the issue for the reason Carlos stated above

**Comment by cead22** [comment]
Thanks
