### ISSUE TITLE
Workspace - New workspace created after use the "Free Plan" on price page from OldDot.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to NewDot and Log out
2. Navigate to OldDot and sign in with any account that has an existing Workspace
3. Navigate to staging.expensify.com/pricing and select the "Free Plan"
4. Verify you're redirected to NewDot > Workspace settings of a pre-existing workspace
5. Verify that you're logged in with the same account as in OldDot
6. Return to OldDot Tap on the back button

## Expected Result:
No Workspace was created. This is a regression step (https://expensify.testrail.io/index.php?/tests/view/2318945&group_by=cases:section_id&group_id=228848&group_order=asc)   "Logged out of NewDot"
## Actual Result:
Workspace was created.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.89-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Bug5702714_Screen_Shot_2022-08-24_at_2 40 03_PM" src="https://user-images.githubusercontent.com/43996225/186516509-a8e330a5-b289-4dc1-b931-232965913d4f.png">

https://user-images.githubusercontent.com/43996225/186516499-cd164bba-a893-4dc2-9b59-71b3b1818456.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
cc @aldo-expensify This is a consequence of this PR https://github.com/Expensify/Web-Expensify/pull/34547

I see this is confusing here, I think we would not want to create a new workspace when there already is one, but also this might be fine for now, I will ask in product!

**Comment by aldo-expensify** [comment]
yes, lol, the opposite was reported in this GH issue at the time: https://github.com/Expensify/Expensify/issues/221105

**Comment by mountiny** [comment]
@kavimuru @mvtglobally Would you be able to confirm this change in the expected result of the regression test?

**Comment by mvtglobally** [comment]
@mountiny we will update TC

**Comment by mountiny** [comment]
Thank you, closing this then!
