### ISSUE TITLE
 Login - Wrong error message for Password field after trying to login with wrong 2FA code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the test app
2. Enter the correct email for the account with 2FA enabled
3. Enter the correct password
4. Enter an incorrect 2FA code and try to log in -> Error message about the wrong 2FA code is displayed
5. Tap the Go Back link at the bottom of page
6. Enter the correct email for the same account with 2FA enabled
7. Enter the correct password
8. Observe the error message for the Password field

## Expected Result:
Error message about wrong 2FA code for the Password field is not displayed after the user enters the correct password.
Able to continue to the 2FA code field.

## Actual Result:
Error message about wrong 2FA code for the Password field is displayed after the user enters the correct password.
The 2FA code field is not displayed after entering the correct password.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any accounts with 2FA sets up

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186709867-b20cda7a-e38a-4e1d-82b9-0904838e82a1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
Reproduced in dev. My guess is that probably we are not clearing properly some error state in Onyx?

**Comment by varshamb** [comment]
### Proposal

We need to change this to `incorrectPassword`

https://github.com/Expensify/App/blob/22a0cba7aaeaa786f04a63a5ad74c650c4c35001/src/pages/signin/PasswordForm.js#L109

**Comment by trjExpensify** [comment]
Hm, @robertjchen is this perhaps related to the `authenticate` API refactors? If so, does it need to remain internal?

**Comment by thesahindia** [comment]
Hmm I was trying to enable two factor authentication at https://www.expensify.com/ but when I enter the code from my authenticator app, I get invalid code error. 
<img width="601" alt="Screenshot 2022-08-30 at 8 29 18 PM" src="https://user-images.githubusercontent.com/83179295/187471210-7d3c6fe3-7a75-4f55-956c-c57a7b834476.png">

**Comment by trjExpensify** [comment]
([Internal ref](https://expensify.slack.com/archives/C02HWMSMZEC/p1661871608028319?thread_ts=1661796380.199039&cid=C02HWMSMZEC)) - Keeping this one `internal` as it's likely due to the `authenticate` refactors. 

CC: @robertjchen @MonilBhavsar

**Comment by youssef-lr** [comment]
So I've managed to fix this by clearing the local state of `PasswordForm` as it was kept saved even when we click "Go back". Which resulted in the password form sending the 2FA code as well instead of just the passowrd. PR ready for reviews if anyone wants to chime in!

**Comment by youssef-lr** [comment]
Not a regression.
