### ISSUE TITLE
[$250] mWeb - Copied checkmark not working in "Copy links" - reported by @puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open 1:1 chat with any message received. then tap and holp in message.
2. On the modal list tap in "Copy link"

## Expected Result:
Copied checkmark should occur when using Copy link function.

## Actual Result:
Copied checkmark not working in "Copy links"

Checkmark are showing different behaviors in each section.
-Copy to clipboard- Working good
-Copy link- No checkmark is displayed
-Mark as unread -its fast showing in the latest moment.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186773854-67083ce7-6e62-4001-8af8-f48a3ac2ac63.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01bd58b89ae0bb08ec

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
This looks like a bug. The "Copy Link" shouldn't show up if we tap on some text that doesn't include a link. Hence why there's no feedback afterwards as there's no link to copy. Looking into it.

**Comment by Puneet-here** [comment]
Hi I had reported it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1656528217864119?thread_ts=1655914131.049009&cid=C01GTK53T8Q)

**Comment by Puneet-here** [comment]
Hi @youssef-lr, can you please reopen and apply external label here so that reporting bonus can be paid as this was reported on slack and eligible for the reporting.

**Comment by michaelhaxhiu** [comment]
Exported to Upwork and job link is here - https://www.upwork.com/jobs/~01bd58b89ae0bb08ec

**Comment by Puneet-here** [comment]
> @Puneet-here should apply for the job and I'll pay/close it.

Thank you @michaelhaxhiu, I have applied now.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Puneet-here** [comment]
Bump @michaelhaxhiu

**Comment by Puneet-here** [comment]
Bump @michaelhaxhiu

**Comment by michaelhaxhiu** [comment]
@Puneet-here paid, sorry for the delay.
