### ISSUE TITLE
Desktop - Chat - Sending a misspelled word doesn't return autocorrected and doesn't highlight

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10583]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR**  https://github.com/Expensify/App/pull/10457

## Action Performed:
1. Open the Expensify Desktop app
2. Sign into a valid account
3. Open any chat
4. Type missed spell word that the spell checker actually highlights
5. Wait for spellcheck to turn into a blue color word (First issue here)
6. Now send immediately with the blue color word (Second issue here)

## Expected Result:
You will notice that it will replace missed spelled words and keep the auto-correct word after the message sent

## Actual Result:
The misspelled word will underline red, however it will not highlight "blue" by itself, the user has to click on top of the word to activate this. Also, after sending the word that is highlighted blue it does NOT auto-correct itself and will continue to display misspelled in chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186773345-361b224f-4f37-4cbb-acda-a6ea6ff58e67.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
Hm i don't think this is an issue as spell check functionality is only validate in iOS not support for any other platform

**Comment by joelbettner** [comment]
I agree that this isn't an issue. I'm going to close this for now. Perhaps we will come back to it later.
