### ISSUE TITLE
Web - Secondary acc validation - No validation error for the expired link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10026

## Action Performed:
1. Add secondary account via OldDot and validate it
2. Logout form the NewDot
3. Try to use validation link with staging.new.expensify.com domain

## Expected Result:
in Case 4, an error message would displayed below the password field stating: "This set password link is invalid or has expired...",

## Actual Result:
There is no expiration error

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** yuriy.turbo+ch5@gmail.com/Aa111111

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186915749-8b8a8918-00e1-437f-abbd-eff5bf4413e2.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
Not sure what priority this issue has, @robertjchen could you please help? I see you worked on ValidateLogin refactor and I thought you might have some context.

**Comment by cristipaval** [comment]
After looking at this [SO](https://stackoverflow.com/c/expensify/questions/4319), I think the issue isn't a daily because this isn't
> a bug that prevents many users using the product

**Comment by robertjchen** [comment]
I believe this is resolved here: https://github.com/Expensify/App/issues/10754
