### ISSUE TITLE
iOS/Android/Desktop - Manage members - Admin user disappears if accessing workspace offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User already has workspace created
1. Open the New Expensify app (iOS, Android or Desktop)
2. Sign into a valid account
3. Turn off internet connection
4. Tap on Profile > Workspace > Manage members while offline

## Expected Result:
User expects to see themselves in the members list as "Admin"

## Actual Result:
The "Admin" user does not show when accessed offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Desktop App

**Version Number:** 1.1.92.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186978618-aa88c3eb-d380-4c08-93dd-50dcd3fb0515.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
Hm. I'm not sure we pre-load workspace users before accessing it. Looking for it

**Comment by danieldoglas** [comment]
I'm talking about this issue to @arosiclair since it may be related to the Workspace API refactors he's been working on

**Comment by arosiclair** [comment]
There shouldn't be any expectation that the user would see themselves in the Manage members page while offline. The list of users displayed on this page while offline is the same list that was displayed while previously online. If the user has never browsed this page while online, there will be no data displayed while offline.
