### ISSUE TITLE
Web - Login 2FA - The cursor stays in the password input field after pressing "Enter" key in the keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. In the log in screen enter an account that has 2FA enabled
3. Enter the correct password in the password field and press "Enter" key in the keyboard

## Expected Result:
After pressing the "Enter" key, the cursor disappears from the password input field

## Actual Result:
The cursor stay in the password input field after pressing "Enter" key

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/186945052-0abf35b1-77d1-466c-9e03-eb20fa502dd1.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
Seems easy enough, I'll tackle this
