### ISSUE TITLE
IOS - JSON erroe when sending message with special characters 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat 
2. Send multiple messages with special characters

## Expected Result:
User should be able to send any message on IOS 

## Actual Result:
User gets JSON error in some cases. Not consistently repro 
We are probably using substr instead of mb_substr somewhere in the add comment command

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![File (2)](https://user-images.githubusercontent.com/43995119/187056869-31bf50e4-4a40-4d6c-872e-94c40103a393.jpg)
<img width="447" alt="image - 2022-08-28T000331 872" src="https://user-images.githubusercontent.com/43995119/187056870-e26f8831-824f-423e-b525-564fb4ed608a.png">
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton @JmillsExpensify 
**Slack conversation:** [
](https://expensify.slack.com/archives/C01GTK53T8Q/p1661524227615799) 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I got a fix for this.

**Comment by luacmartins** [comment]
This should be fixed! Closing.
