### ISSUE TITLE
[HOLD for payment 2022-10-05] [$250]  Edit avatar screen doesn’t open up a a rightDocked modal

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to app and login
2. Open Settings > Profile 
3. Click on Photo > Upload Photo 

## Expected Result:
Edit avatar screen should open up a a rightDocked modal

## Actual Result:
Edit avatar screen doesn’t open up a a rightDocked modal

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="864" alt="image - 2022-08-28T234448 569" src="https://user-images.githubusercontent.com/43995119/187119134-e98fb12f-a7af-4fe3-bb71-cb78779b6ab1.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660684286312709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 

We have to replace this with `CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED`
https://github.com/Expensify/App/blob/89e7e7db469d2f222ebceb7aefa72cb4add0de78/src/components/AvatarCropModal/AvatarCropModal.js#L269

**Comment by puneetlath** [comment]
External upwork post: https://www.upwork.com/jobs/~01b2ee159ae607c80e
Internal upwork job: https://www.upwork.com/ab/applicants/1564883307443179520/job-details

**Comment by puneetlath** [comment]
@srikarparsi is going to take CME on this one.

**Comment by Harshdeepjoshi** [comment]
### Proposal
To make this a right docked modal, we will replace this 

https://github.com/Expensify/App/blob/ffa839ee30b7f7c32ed203195535818c12f4f938/src/components/AvatarCropModal/AvatarCropModal.js#L266-L273
with 
``` jsx
       <Modal
            onClose={props.onClose}
            isVisible={props.isVisible}
            type={CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED}
            containerStyle={!props.isSmallScreenWidth ? styles.avatarCropModalContainer : null}
            onModalHide={resetState}
            statusBarTranslucent={false}
        >
```
and since there is a back button on all rightDocked modal, we will also replace this

https://github.com/Expensify/App/blob/ffa839ee30b7f7c32ed203195535818c12f4f938/src/components/AvatarCropModal/AvatarCropModal.js#L275-L278
with 
```jsx
            <HeaderWithCloseButton
                title={props.translate('avatarCropModal.title')}
                shouldShowBackButton
                onBackButtonPress={props.onClose}
                onCloseButtonPress={props.onClose}
            />
```
[Screencast from 01-09-22 08:51:40 PM IST.webm](https://user-images.githubusercontent.com/88710727/187954633-5880bcf9-ee39-4857-8e7f-5138ad913236.webm)

**Comment by Santhosh-Sellavel** [comment]
@shawnborton / @Expensify/design

Need confirmation do we need a back button here?

**Comment by puneetlath** [comment]
I would think so, yes.

**Comment by Puneet-here** [comment]
I don't think we need a back button here because it's just an edit modal but If we want then I can update my [proposal](https://github.com/Expensify/App/issues/10627#issuecomment-1230731037), We have to change the code like below -

https://github.com/Expensify/App/blob/11761bea9de7604febd17da05797c62caf2a2f6b/src/components/AvatarCropModal/AvatarCropModal.js#L275-L278
```js
            <HeaderWithCloseButton
                title={props.translate('avatarCropModal.title')}
                shouldShowBackButton
                onBackButtonPress={props.onClose}
                onCloseButtonPress={Navigation.dismissModal}
            />

```

**Comment by puneetlath** [comment]
Let's show it based on the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662461482336989).

**Comment by Santhosh-Sellavel** [comment]
@srikarparsi  

@Puneet-here proposal looks good and meets our expected OP as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662461482336989). 
So let's hire him for this one!

🎀 👀 🎀 
C+ Reviewed

Thanks!
cc: @puneetlath

**Comment by Santhosh-Sellavel** [comment]
Review in progress

**Comment by puneetlath** [comment]
@Santhosh-Sellavel @Puneet-here sent you both hiring offers in Upwork. Please accept when you have a chance.

**Comment by Santhosh-Sellavel** [comment]
Done thanks!

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
