### ISSUE TITLE
keyboard shows for sometime even after changing screen - Reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go To Profile
2. Click on Add Phone Number
3. Immediate go back to profile

## Expected Result:
keyboard should not show

## Actual Result:
keyboard shows even after changing screen

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/187120398-b39d7b97-b897-459b-8958-e727aec19878.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660805436185959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
My android phone is back at my hotel room. I will get to replicating this later today. Sorry for the wait @mvtglobally!

**Comment by twisterdotcom** [comment]
Okay, I finally got around to trying to reproduce today and could not with these steps on the latest build:

> 1. Go To Profile
> 2. Click on Add Phone Number
> 3. Immediate go back to profile

Is this still an issue @gadhiyamanan

https://user-images.githubusercontent.com/9133401/188698472-515c0201-cfb3-441b-b869-43609ea99621.mp4

**Comment by twisterdotcom** [comment]
What's weird about the flow I was trying to replicate is that I couldn't do it without an email already added - how is that the case from the OP video?

**Comment by gadhiyamanan** [comment]
@twisterdotcom yes, still able to reproduce sometimes https://user-images.githubusercontent.com/54790231/188700881-f7f0cc1e-6fa1-40af-a346-db09a19a0874.mp4

**Comment by twisterdotcom** [comment]
Okay, sending to engineering to see if even want this to be fixed right now as per https://stackoverflow.com/c/expensify/questions/4319/8577#8577

**Comment by robertjchen** [comment]
I'd agree with @parasharrajat on this one- it's pretty edge case, and given the difficulty of reproducing it, I'd say we can close it for now. 👍
