### ISSUE TITLE
[HOLD for payment 2022-10-07] [$250] On entering wrong password the error says Incorrect login or password - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to login page
 2. Add your email > continue
 3. Enter wrong password

## Expected Result:
The error should say Incorrect password. Please try again.

## Actual Result:
The error says  Incorrect login or password. Please try again

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="375" alt="Screenshot 2022-08-09 at 11 17 03 PM" src="https://user-images.githubusercontent.com/43995119/187113551-794efd02-d214-4063-b75c-ba24dad8b45f.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660163992841699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal

Need to replace incorrectLoginOrPassword with `incorrectPassword`

https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/pages/signin/PasswordForm.js#L105

https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/languages/en.js#L473

**Comment by Puneet-here** [comment]
@thienlnam, this issue is different. When you enter a wrong password the error message says "Incorrect login or password. Please try again" instead it should say "incorrect password" because the password that the user entered isn't correct. We already have this error message here we just have to use it (as mentioned [here](https://github.com/Expensify/App/issues/10623#issuecomment-1229734651)).
https://github.com/Expensify/App/blob/e21736d87cc1ed95c1f64a54040ce242ced7ebc0/src/languages/en.js#L473

**Comment by thienlnam** [comment]
Ah yeah good point, should be a pretty small change

Looks like the current error message is unused https://github.com/Expensify/App/blob/22a0cba7aaeaa786f04a63a5ad74c650c4c35001/src/languages/en.js#L473-L473

**Comment by kadiealexander** [comment]
@thienlnam please don't change the frequency label until the `help wanted` label is there! I missed this for a month because it wasn't a daily.

**Comment by kadiealexander** [comment]
https://www.upwork.com/ab/applicants/1574594452289884160/job-details
https://www.upwork.com/jobs/~01306bf3e6383968c3

**Comment by mananjadhav** [comment]
@Puneet-here 's proposal is fine by me and its a straight forward fix.

@thienlnam 

🎀 👀 🎀 
C+ reviewed

**Comment by Domnic95** [comment]
Hello  team Expensify 
I got the issue and I can solve it right now.
READY TO START RIGHT NOW.

At a glance, it looks like there is just a message printing issue.

Let me take this opportunity to introduce myself first. I have been working as a Mobile app developer for the last 5 years[React Native 3 YEAR], and I made 17+ apps on that platform[REACT NATIVE ESPECIALLY] to check that app kindly unfold the below link.

Reachout (Online Support App for Chronic disease support groups)
https://itunes.apple.com/app/id1068993034
https://play.google.com/store/apps/details?id=com.reachout

I can help you out in the same as I have extensive experience in React Native app development. I've also experienced Git, Zira, Firebase, SDK, design patterns, and software architecture.

If the above offer sounds like something you would be interested in, I’d love to hear from you.

Regards,
Domnic

**Comment by getusha** [comment]
There is two messages inside the en.js which is for _incorrectLoginOrPassword_ and _incorrectPassword_
there exist different languages so we should not edit the text but switch it to the right err variable.
https://github.com/getusha/App/blob/1e0df337b75263e015a4aa2d63a6ede27bf3acd0/src/libs/ErrorUtils.js#L14-L15

**Comment by vankar47** [comment]
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> ## Action Performed:
> 1. Go to login page
> 2. Add your email > continue
> 3. Enter wrong password
> 
> ## Expected Result:
> The error should say Incorrect password. Please try again.
> 
> ## Actual Result:
> The error says Incorrect login or password. Please try again
> 
> ## Workaround:
> unknown
> 
> ## Platform:
> Where is this issue occurring?
> 
> * Web
> * iOS
> * Android
> * Desktop App
> * Mobile Web
> 
> **Version Number:** 1.1.91-0 **Reproducible in staging?:** Y **Reproducible in production?:** Y **Email or phone of affected tester (no customers):** **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Notes/Photos/Videos:** Any additional supporting documentation <img alt="Screenshot 2022-08-09 at 11 17 03 PM" width="375" src="https://user-images.githubusercontent.com/43995119/187113551-794efd02-d214-4063-b75c-ba24dad8b45f.png">
> 
> **Expensify/Expensify Issue URL:** **Issue reported by:** @Puneet-here **Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660163992841699
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

seems like you guys are using a generalised message for login error which occurs on invalid credentials regardless of which is incorrect email or password. 
This will require a simple condition to determine which field is incorrect and display a different message based on the output of the condition.

**Comment by thienlnam** [comment]
My bad @kadiealexander, will watch out for that next time

Also the proposal from @Puneet-here was first and it looks good, 🟢

**Comment by kadiealexander** [comment]
Offers sent to @Puneet-here and @mananjadhav, please let me know once these are accepted.

**Comment by mananjadhav** [comment]
Accepted @kadiealexander

**Comment by Puneet-here** [comment]
Accepted.

**Comment by thienlnam** [comment]
cc @kadiealexander Looks like this is ready for payment!

**Comment by kadiealexander** [comment]
Sorry for the delay team! Everyone is paid, thanks for your work on this!
