### ISSUE TITLE
Clicking on internal link (which has invalid route) does nothing - Reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message which contain [new.expensify.com/index](http://new.expensify.com/index)
2. Click on the link.

## Expected Result:
It should open or show a growl message. (Expected result to be decided on issue).

## Actual Result:
It does nothing. It throws an error on the console as /index is not a valid route in App.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/187114789-f653114d-016a-4b23-957f-602bd9531ef2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660321906420899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
@mvtglobally I am not exactly clear on what the issue is. From testing on my end, the [new.expensify.com/index](http://new.expensify.com/index) link sends me to the expected sign-in page. Can you clarify in more detail what should happen?

**Comment by davidcardoza** [comment]
Since this is a duplicate issue, let’s centralize convo in the other GH.
