### ISSUE TITLE
No desktop push notifications are sent for Concierge chats received in NewDot

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send message to Concierge to prompt a response
2. Click into another tab
3. Check back a few minutes later to see if Concierge responded
4. Now, send a message to someone who isn't Concierge asking for a response
5. Click into another tab

## Expected Result:
You should get a push notification when user or Concierge respond

## Actual Result:
No desktop push notifications are sent for Concierge chats received in NewDot

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.89-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1100" alt="Screen Shot 2022-08-28 at 11 35 26 PM" src="https://user-images.githubusercontent.com/43995119/187118071-7acd042a-ecb9-4c60-8790-5d693ba824fa.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660573368623459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
I believe this should have been the engineering tag rather than triage

**Comment by tylerkaraszewski** [comment]
Unassigning myself after reproducing the issue. I think this is an internal issue.
