### ISSUE TITLE
Paid IOU still shows as unpaid in the red pill on the upper-right and on the LHN

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Receive IOU 
2. Check LHN display
3. Pay it 
4. Verify it is no longer displayed in LHN with  red indicator 

## Expected Result:
Once Paid, IOU should not displayed with red indicator in LHN

## Actual Result:
Paid IOU still shows as unpaid in the red pill on the upper-right and on the LHN. Refresh doesn't help 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1062" alt="image - 2022-08-29T002049 704" src="https://user-images.githubusercontent.com/43995119/187122712-ed0d2e32-fe98-4306-a489-f89c9e3bdb3b.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661429205885209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Sorry for the delay, taking a look today!

**Comment by yuwenmemon** [comment]
No longer able to reproduce on Prod - yaaay it fixed itself 😅 🎉

**Comment by yuwenmemon** [comment]
<img width="814" alt="Screen Shot 2022-09-28 at 2 03 44 PM" src="https://user-images.githubusercontent.com/4741899/192888332-58e722fd-5a10-456f-85c4-0b48175eea32.png">
