### ISSUE TITLE
Web app crashing after a while

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#10649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Open the app

## Expected Result:
Describe what you think should've happened

The app should load without crashing

## Actual Result:
Describe what actually happened

The app crashes with console error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

None

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661773256971749

![image](https://user-images.githubusercontent.com/36083550/187216981-eb582a4a-454b-4189-a7de-881a486fcfa0.png)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
I'm not quite sure what is causing this, but I'm guessing that props.policies in AvatarWithIndicator looks something like this, where one of the policies is null. To fix this I will check for if the policy exists in the policy util method.
```javascript
const policies = {
    1234: null,
    12344: {},
};
```

**Comment by mountiny** [comment]
Havent linked it before, this is coming from https://github.com/Expensify/App/pull/10400
