### ISSUE TITLE
Web - Workspace - App Crashed when deleting the Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings>Workspace>Delete Workspace>Delete

## Expected Result:
No crash when deleting the Workspace

## Actual Result:
App Crashed when deleting the Workspace

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.93.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187217983-09bd90cf-5cee-4c3f-93d8-514fb7927acd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
https://github.com/Expensify/App/pull/10400/ Causing this most likely

**Comment by mountiny** [comment]
PR to fix this is a review
