### ISSUE TITLE
Desktop - All inputs aren't grayed out when switched to  offline and no offline indication message too

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10400 
## Action Performed:
1. Open App and login
2. Go offline
3. Update the workspace name

## Expected Result:
All inputs should be grayed out when the Desktop App is offline.

## Actual Result:
None of the inputs are grayed out when the Desktop App is offline and no message about it.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.1.93-4
**Reproducible in staging?:**  y
**Reproducible in production?:** Y ( Its a new feature, so infinite loading when switched to offline in production)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1060" alt="Bug5709590_offline" src="https://user-images.githubusercontent.com/43996225/187273719-9abe2e32-cd59-48f2-a293-c87a27e9b51f.png">

https://user-images.githubusercontent.com/43996225/187273761-22781a4f-4c8e-4c15-bf2b-6235b87fa590.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  Applause internal tester
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
@neil-marcellini Looks like this is related to https://github.com/Expensify/App/pull/10400, gonna assign ya

**Comment by neil-marcellini** [comment]
The only problem here is that the app is not detecting when were are going offline, so I'm going to close this and keep the offline indicator issue open https://github.com/Expensify/App/issues/10524.
