### ISSUE TITLE
Web - General settings - No confirmation growl after saving changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test app and sign in to applause.expensifail account
2. Click on Create a New Workspace if it does not exist
3. Navigate to the Workspace editor page
4. Navigate to the General Settings page
5. Change the Workspace name and Default currency to anything you want
6. Tap the Save button

## Expected Result:
The Confirmation growl appears at the top mentioning that changes are saved.

## Actual Result:
The Confirmation growl does not appear at the top mentioning that changes are saved.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

-Web
- Android

**Version Number:** 1.1.93.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187246191-0ad2e847-b1e5-40b2-9534-81700da50d8a.mp4

https://user-images.githubusercontent.com/93399543/187246940-a16b124c-c385-4509-aaa5-2fd1075f7b84.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@kbecciv this is the new expected behavior! Successful updates will no longer have a growl. If the request fails, we should see [this error](https://user-images.githubusercontent.com/26260477/186429938-33a44e96-3869-4ccf-ab5c-3955a4eab129.mp4). cc @neil-marcellini

**Comment by luacmartins** [comment]
Closing this issue!

**Comment by kbecciv** [comment]
@luacmartins Thank you
