### ISSUE TITLE
[$250] Web -Workspace - Rate amount is not reflecting after changing units under Reimburse expenses

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Go to Settings - Workspace - Reimburse expenses
4. Change the unit to different one

## Expected Result:
Rate amount is reflecting after changing units under Reimburse expenses

## Actual Result:
Rate amount is not reflecting after changing units under Reimburse expenses

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.93.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187239422-cf6f6fa8-779a-4c1c-978f-e66b5839c07a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
[Discussion in Slack](https://expensify.slack.com/archives/C07J32337/p1661848422598019)

**Comment by Julesssss** [comment]
Missed this one somehow. It's not always reproducable, but let's open it up to see if anyone can propose a fix. This is our best guess: 

> I see, the bug in the second video only happens when I reload the page and I’m already on the WorkspaceReimburseView, so I’m guessing the call to openApp must return after we retrieve the full policy contents.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment]
I'm not able to repro this anymore either, seems like this has been fixed!
