### ISSUE TITLE
Deprecate REPORT_DRAFT_COMMENT and REPORTS_WITH_DRAFT Onyx keys

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#10679]
### Problem
We have some redundancies in Onyx:

- `REPORT_DRAFT_COMMENT` stores the draft comments for individual reports
- `REPORTS_WITH_DRAFTS` is essentially a list of boolean values to list out reports that have drafts

This leads to unnecessary extra storage, and (more importantly) confusing code.

### Solution
Eliminate the `REPORTS_WITH_DRAFTS` Onyx key and standardize on `REPORT_DRAFT_COMMENT`.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014cdfad339adcdb73</li>
        <li>Upwork Job ID: 1615121451893055488</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
HOLD on https://github.com/Expensify/App/pull/10619

**Comment by roryabraham** [comment]
bumping this back to weekly

**Comment by roryabraham** [comment]
Taking this off hold

**Comment by roryabraham** [comment]
I kind of think this should be rolled up with [this issue](https://github.com/Expensify/App/issues/5536)

**Comment by roryabraham** [comment]
No update from me

**Comment by tjferriss** [comment]
I'm reviewing this issue as part of the weekly bug review chore. Is the plan to roll this into the [other issue](https://github.com/Expensify/App/issues/5536)or fix here? This is becoming one of our older bugs so it'd be great to sort out what needs to happen here.

**Comment by roryabraham** [comment]
Putting this on HOLD for now for WAQ.

**Comment by roryabraham** [comment]
Still on HOLD, but would be good to get this out before we push forward through N7

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Still on HOLD

**Comment by roryabraham** [comment]
Taking this off HOLD

**Comment by trjExpensify** [comment]
@roryabraham, jusssst checking.. this is `internal` right? Neither of the external/internal labels are applied currently.

**Comment by JmillsExpensify** [comment]
Also I don't think this issue qualifies as a bug. It looks like the `bug` label was accidentally added to this one and should be removed.

**Comment by roryabraham** [comment]
Also, I don't think I still completely agree with the proposed solution, especially in light of the discussion in https://github.com/Expensify/App/issues/5536. So I'm going to amend it.

**Comment by roryabraham** [comment]
Actually, after reviewing this old issue I can see that my proposed solution has already been implemented by someone. So we can close this out.
