### ISSUE TITLE
[HOLD for payment 2022-09-15] [$250] Chat - Error message is received when attaching files with extension in caps

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10694]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Open any chat
4. Attempt to add any attachment through "+" or "Drag & Drop" with the type in CAPS (For example: .PDF or .PNG)

## Expected Result:
User expects the attachment to be added with no issues

## Actual Result:
The user receives an error message if the attachment type is in CAPS

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:**  1.1.94-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/187495523-b24a409f-2aa0-4aba-aedf-ea826b6a2136.mp4

**Upwork URL** https://www.upwork.com/jobs/~01d1500d5c8671f017
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by theTrozen77** [comment]
PROPOSAL

I was able to reproduce the issue and fix it.
It is a simple fix. Just convert the extension string to lowercase using .toLowerCase() method when the file extension is separated from the complete file string.
`        const fileExtension = splitFileName.pop().toLowerCase();
`

Thankyou

**Comment by trjExpensify** [comment]
Woof, nice catch. Job is on Upwork here: https://www.upwork.com/jobs/~01d1500d5c8671f017

**Comment by theTrozen77** [comment]
Hi. Who should be applying to this since my solution is also relevant?

**Comment by stitesExpensify** [comment]
Hi @theTrozen77, We're going to go with @varshamb's proposal here (and they will be implementing it). While your proposal came first and they are similar, I think that @varshamb's is more accurate in this case which is typically how we judge the "best" solution.

**Comment by trjExpensify** [comment]
Not overdue, payment due tomorrow. 

@varshamb @parasharrajat - can you both accept the offer please?

**Comment by varshamb** [comment]
@trjExpensify Accepted.

**Comment by trjExpensify** [comment]
Settled up with you both. Thanks! 🎉
