### ISSUE TITLE
[$250] Web - Spanish - Multiple phrases are not changing to Spanish on Expensifail account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com (Or dekstop app)
2. Sign into a valid Expensifail account
3. Click on Profile > Preferences > Languages
4. Change Language to Spanish
5. Navigate to conversation where money has been "Requested" and/or "Split"

## Expected Result:
User expects the entire app to now be in Spanish

## Actual Result:
User can still see strings of English like "Requested XX from you" OR "Split XX with...."

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.94.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187512611-1f9d2321-27f1-4d60-93b7-db9627c702c6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
internal: https://www.upwork.com/ab/applicants/1564965263733084160/job-details
external: https://www.upwork.com/jobs/~0147b4a23127f2c895

**Comment by mountiny** [comment]
I am not sure if this is the right time, but we could I assume. At the same time I am sure we will need a bigger overhaul of how to localize server error messages and that might come later. Curious for Ioni's thoughts

**Comment by dylanexpensify** [comment]
Ah yep, closing out!

**Comment by iwiznia** [comment]
Yep, this is not the right time

**Comment by dylanexpensify** [comment]
Closed
