### ISSUE TITLE
mWeb - IOU - Shifted selection in field What's it for? appears after returning to this screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10698]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login at staging.new.expensify.com
2. Click the FAB button again and select `Request Money`
3. Input any amount and click Next
4. Select any user account
5. Input any text in the field "What's it for?"
6. Click "Back" button <
7. Select any user account again

## Expected Result:
The field "What's it for?" contains the previously entered text

## Actual Result:
The field "What's it for?" contains the previously entered text, which is selected and this selection has an offset relative to the text

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web Safari

**Version Number:** 1.1.94-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/187521824-217c591e-6380-483d-a7b6-af663879a272.mp4

<img src="https://user-images.githubusercontent.com/43996225/187521911-97dff458-c638-48b6-9912-e313a9a36e15.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Confirmed I'm able to reproduce this. @NicMendonca let's get an Upwork job created for this. Bumping to Daily just to get the job up and the `Help Wanted` label added, then we can make this a weekly.

**Comment by NicMendonca** [comment]
job posting: https://www.upwork.com/jobs/~0121916a664f05173f

**Comment by Uros787** [comment]
### Proposal
The issue here is that we are not waiting for transition of the screen to end. There is already implementation of shouldDelayFocus prop on BaseOptionsSelector.js

So all we have to do is add shouldDelayFocus prop on [IOUConfirmationList.js](https://github.com/Expensify/App/blob/2ba241194706300e8e748acb4e9636e2e659f274/src/components/IOUConfirmationList.js) on OptionsSelector

![Screenshot 2022-10-11 at 00 22 35](https://user-images.githubusercontent.com/70144379/194961074-0cafdd4c-0610-4521-8518-446524e75e4d.png)

https://user-images.githubusercontent.com/70144379/194961096-c741801d-a82f-448c-a00e-b785f5e9cec4.mov

**Comment by Uros787** [comment]
I have applied for a job on upwork, i will create a PR probably today if not tommorow

**Comment by roryabraham** [comment]
Pr merged

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by NicMendonca** [comment]
latest update [here](https://github.com/Expensify/App/pull/11718#issuecomment-1281240942)

**Comment by mallenexpensify** [comment]
@Uros787 , apologies for the delay, we have automation that posts in this issue when the PR is deployed (and updates the title) but it didn't work.  I just paid you, closing.
