### ISSUE TITLE
Web - Manage Members - User receives error message when removing others while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click Profile > Workspace > Manage members
4. Invite a user
5. Disable internet connection
6. Remove the user that was invited while offline and wait around 10-15 secs.
7. Enable internet connection again

## Expected Result:
The user expects the member to be removed with no issues

## Actual Result:
The member is not removed and the user receives an error message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.94.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187534142-57131d5e-fc89-49f0-bfca-9ef9ae99a5bd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
@kbecciv Could we get the email of the tester account?

**Comment by kbecciv** [comment]
@MariaHCD emilio.utest@gmail.com/Emilio98

**Comment by MariaHCD** [comment]
Great, thanks! I'll look into this asap.

**Comment by MariaHCD** [comment]
No obvious errors in the [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22Policy_Employees_Remove%22%20AND%20email%3A%22emilio.utest%40gmail.com%22%20AND%20timestamp%3A%5B2022-08-29T00%3A00%20TO%202022-08-31T23%3A59%5D). Will look into it further.

**Comment by MariaHCD** [comment]
Ah, looks like we haven't refactored the Policy_Employees_Remove command yet which is why it doesn't work correctly offline. 

https://github.com/Expensify/Expensify/issues/211560

cc: @iwiznia 

We can retest this once the refactor for this API command is complete.
