### ISSUE TITLE
Profile - The photo with a gray background does not appear

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10235

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Click on the avatar picker and upload an avatar
3. Be ready to turn off your device wifi very quickly, click on the avatar picker and upload an avatar, but IMMEDIATELY turn off your device WiFi before avatar can finish uploading.

## Expected Result:
The avatar should become grayed out if the Internet connection is turned off during loading

## Actual Result:
The photo with a gray background does not appear

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.94-4

**Reproducible in staging?:** Y

**Reproducible in production?:** N (New feature)

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/187543212-8144334b-cf84-490b-b04a-71b803408cf0.mp4

https://user-images.githubusercontent.com/43996225/187543221-c7785b5c-013e-419b-b1c0-b045b1ae39f3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Taking a look since this was related to my PR

**Comment by jasperhuangg** [comment]
So I think in the OP they're not actually turning off the device wifi fast enough, you need to do it within a half second otherwise the upload will complete:
https://user-images.githubusercontent.com/31285285/187614879-90351ac6-3564-4c0e-8fa2-c702340d8067.mov

Closing this out
