### ISSUE TITLE
Renaming workspace does not reflect updated name immediately on chat’s (sidebar page)

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#10725]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a workspace by clicking the green plus and then New Workspace (if needed)
2. Hit the green plus button, New Room, fill out the form and click Create Room
3. Pin the room to the sidebar by clicking the pin icon at the upper right
4. Click the avatar to go to settings, click the workspace you created the room under, General settings
5. Update the workspace name and click save

## Expected Result:
The workspace name should be updated under the pinned room in the left hand navigation (LHN)
## Actual Result:
The workspace name in the left side bar is not updated
## Workaround:
Refresh on web, re-open the app on desktop, or leave the LHN and come back on mobile to refresh the side bar.
OR
Send a chat in the room so that the workspace name is longer displayed in the LHN

## Platform:

All Platforms
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.95-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
https://user-images.githubusercontent.com/26260477/187690054-d0cd93b5-ce93-4ec4-b713-381b9c6e8d37.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660805427935789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Not a deploy blocker since it's already in production https://github.com/Expensify/App/pull/10400#issuecomment-1232951708.

**Comment by neil-marcellini** [comment]
The problem is that `calculateSidebarOptions` is memoized [here](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L785) so it only runs when its arguments change. A quick fix would be to pass in `policies` so that it runs as soon as the policies change. Or better yet pass in only the policy names. It's kind of weird to pass an argument just to make this update, so maybe there's a better way.

**Comment by neil-marcellini** [comment]
Discussing with @tgolen.

**Comment by neil-marcellini** [comment]
This should be fixed by this PR where the memoization is being removed https://github.com/Expensify/App/pull/10800.

**Comment by neil-marcellini** [comment]
That PR is under review so I'll also put the label on this issue.

**Comment by dhairyasenjaliya** [comment]
Hello @neil-marcellini  bug reporting upwork job missing

**Comment by neil-marcellini** [comment]
Thanks for the reminder! @Expensify/contributor-management could someone please create the bug reporting upwork job here? 🙏

**Comment by mallenexpensify** [comment]
Based on [this SO](https://stackoverflow.com/c/expensify/questions/11343/11425#11425), adding `Internal` to an E/App issue should assign a CM but it doesn't look like it's happening. 
@Beamanator or maybe @mountiny , do you know why this isn't so? I'll assign myself for now so this doesn't get _lost_

**Comment by mountiny** [comment]
Correct, we check for reported by as that is the reason to assign CM in a first place

**Comment by mountiny** [comment]
Ahh, yeah that as well it should be in the title too

**Comment by mountiny** [comment]
@neil-marcellini We could but it will require bigger refactor (the body always includes the reported-by part if it is coming from App repo)

**Comment by mallenexpensify** [comment]
Thank @mountiny and @Beamanator .  I don't think we need to invest time to update now, we can deal with manually if needed for edge cases

**Comment by dhairyasenjaliya** [comment]
hello @mallenexpensify @neil-marcellini this one is on production for 8 days I think we can close this one!

**Comment by dhairyasenjaliya** [comment]
@mallenexpensify reporting upwork job missing

**Comment by neil-marcellini** [comment]
FYI I confirmed that this is fixed on prod.

**Comment by mallenexpensify** [comment]
Please accept here @dhairyasenjaliya , reopening til paid
https://www.upwork.com/jobs/~019eea3ce79f6b4622

**Comment by dhairyasenjaliya** [comment]
accepted thanks @mallenexpensify

**Comment by mallenexpensify** [comment]
Thanks for the quick response @dhairyasenjaliya , paid!
