### ISSUE TITLE
Web/Desktop - Workspace - Delete/Create popup is overlapping the border

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Create the Workspace under Fub menu
4. Click on ... dots

## Expected Result:
Delete/Create popup is not overlapping the border

## Actual Result:
Delete/Create popup is overlapping the border

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop

**Version Number:** 1.1.95.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (36)](https://user-images.githubusercontent.com/93399543/187755367-c3066702-ab8d-4b94-9464-75f746a9e6b6.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
I agree, I'll close this issue.
