### ISSUE TITLE
Web- LHN - The user does not move to its previous location in LHN after delete the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10734]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10619 

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Type text in the chat positioned in the middle of LHN. 
3. Reload the page.
4. Delete the text for that contact

## Expected Result:
User appears in the middle again 

## Actual Result:
The user does not move to its previous location in LHN after delete the message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.95.4

**Reproducible in staging?:** Yes

**Reproducible in production?:**Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187795523-103bd8e3-331b-4b6f-85d7-f6e89ddbf4bd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
That video shows exactly what I would expect to happen so I don't think this is a bug or a regression. If the behavior indeed has changed, then it's possible some of my recent changes fixed a bug that was there.
