### ISSUE TITLE
Log in - Missing re-sent link message when you click Forgot password

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. In log in page enter your username
3. Click continue
4. Click Forgot Password

## Expected Result:
Re-sent link message should be appears when you click Forgot password

## Actual Result:
Missing re-sent link message when you click Forgot password

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187963788-bafce402-199e-40b2-aa09-1efbef756106.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
I can easily reproduce this in staging, however the reset email is still sent without issue so I don't think this is a blocking issue.

**Comment by arosiclair** [comment]
cc @jasperhuangg it looks like your refactor PR was the last to touch this

**Comment by bondydaa** [comment]
> I can easily reproduce this in staging, however the reset email is still sent without issue so I don't think this is a blocking issue.

be careful here, when you click `Forgot Password` we trigger 1 email automatically. 

Clicking the Resend button should send a second one.

**Comment by bondydaa** [comment]
This is _probably_ from Jasper's / my PR https://github.com/Expensify/App/pull/10556

we refactored a component in there - let me take a deeper look.

**Comment by luacmartins** [comment]
I have a fix for it, testing now.

**Comment by bondydaa** [comment]
Just to update slightly there will be another small regression here where clicking the `Forgot?` button will automatically show the Green Brick Road message when it takes you to the next step for the time being like this: <img width="1203" alt="image" src="https://user-images.githubusercontent.com/4073354/188121739-8107f8c9-52ab-45ce-b4dd-1d95d9c5a3c1.png">

This is fine and expected for now, we are cleaning it up on https://github.com/Expensify/App/issues/10785
