### ISSUE TITLE
mWeb - Log in- Error message appears on the first attempt of tapping "Resend Link"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10556

## Action Performed:
1. Launch the app
2. Enter an email address which does not have
3. Tap "Resend link"

## Expected Result:
"Link resent" message appears and link is resent

## Actual Result:
Error message appears as "maximum attempts" reached

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187981653-895a3fd1-20d5-4b9a-8dcb-8235a396f2b1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
I believe this is related to https://github.com/Expensify/App/issues/10754 and should be resolved by that fix
