### ISSUE TITLE
Web- Conversation - Attachment removal is not smooth, still appears after deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to any conversation
3. Add an attachment
4. Delete an attachment

Attachment used for testing:
![1f98b (1)](https://user-images.githubusercontent.com/93399543/187979457-2e0dec0c-2740-46b4-84c6-d35b63555acc.png)
![1f9d0 (1)](https://user-images.githubusercontent.com/93399543/187979459-9908fd4b-c7a5-480a-be40-c13e80024b48.png)

## Expected Result:
The attachment should be deleted immediately

## Actual Result:
 Attachment removal is not smooth, still appears after deleted

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187960816-47d9662f-0ef3-4a8f-9e26-e062c256275f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is noticed the same behavior for deleting the comment, please attach video

https://user-images.githubusercontent.com/93399543/187982810-7e1036dc-64d9-489d-845d-e55531e14898.mp4

**Comment by Julesssss** [comment]
Removing the label as this is not a critical enough issue to hold the release any further.
