### ISSUE TITLE
Web - LHN - The fab button becomes highlighted in blue

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on the green plus button in the LHN and select `New Room`
4. Зress the Esc key on the keyboard

## Expected Result:
The fab button should not be highlighted in blue

## Actual Result:
The fab button becomes highlighted in blue

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187993534-d72d46fb-bb01-4de0-9850-5e4ab96520cf.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment]
asked about this in our internal slack here https://expensify.slack.com/archives/C02HWMSMZEC/p1662109135616809 will update once we get some more confirmation.

**Comment by bondydaa** [comment]
still working on resolving this convo in the thread

**Comment by bondydaa** [comment]
dropping this down to weekly since it doesn't seem that pressing and we haven't really come to a conclusion in the thread.

**Comment by bondydaa** [comment]
I think we can close this out 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4073354/191063850-0933bc35-4229-4800-93ae-19c107e95d2d.png">
