### ISSUE TITLE
[Performance] Optimise navigation 

### ISSUE THREAD

**Issue by Szymon20000** [Expensify/App#10789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
Startup time can be improved

## What is the impact of this on end-users?
app boot time

## List any benchmarks that show the severity of the issue
boot time in debug mode improved by ~400ms after optimising AppNavigator so expect much better results once every navigators/conditionally rendered screens are optimised in a similar way

## Proposed solution (if any)
before
<img width="801" alt="Screenshot 2022-09-02 at 13 02 59" src="https://user-images.githubusercontent.com/12784455/188126111-f458e0ec-20d8-464d-9c56-94a70c3aa447.png">
after
<img width="591" alt="Screenshot 2022-09-02 at 13 05 02" src="https://user-images.githubusercontent.com/12784455/188126409-65c8291a-fe91-4565-a8a7-80cd30313524.png">

What it does is basically postponing evolution of the js code until it's actually used. 
Of course you need to get rid of corresponding  imports from the beginning of the file.

#### How to do it in navigators?
```js
<Stack.Screen
  name="Profile"
  getComponent={() => require('./ProfileScreen').default}
/>
```
instead of 
```js
<Stack.Screen
  name="Profile"
  component={ProfileScreen}
/>
```

Such solution should be used for every navigator/screens the app has.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platform:
Where is this issue occurring?

- [ ] Web
- [x] iOS
- [x] Android
- [ ] Desktop App
- [ ] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by roryabraham** [comment]
Agree that we _can_, but I don't know if our bundle size is big enough to be problematic yet. Last I checked it was about 6MB

**Comment by marcaaron** [comment]
I can hop on the review for this when a PR is up.

**Comment by roryabraham** [comment]
Looks like we've got a PR up with a healthy number of reviews: https://github.com/Expensify/App/pull/10986

**Comment by trjExpensify** [comment]
@Szymon20000 are we all done here and can close this issue out?

**Comment by marcaaron** [comment]
yeh, seems like this is on production now.
