### ISSUE TITLE
[Performance] md5.js takes a lot of time

### ISSUE THREAD

**Issue by Szymon20000** [Expensify/App#10794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
md5.js takes a lot of time according to Hermes profiler
Looks like it's used by ReportUtils.js -> getDefaultAvatar
Not sure how much users with default avatars the average user has.

## What is the impact of this on end-users?
Slower app

## Proposed solution (if any)
Find a cheaper way for getting default avatar? Persist it?
Replace md5.js by react-native-quick-crypto hash API 
It's possible that using md5 for small inputs and react-native-quick-crypo for bigger once will perform better.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platform:
Where is this issue occurring?

- [ ] Web
- [ ] iOS
- [x] Android
- [ ] Desktop App
- [ ] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by roryabraham** [comment]
Switching this to weekly

**Comment by aldo-expensify** [comment]
Is the point of getting the md5 to try to distribute emails across the 8 possible default avatars? Wouldn't work to do something like to get things well-enough distributed?

```
const bucket = (accountID * 31) % 8;
```

31 is just a prime number to help things distribute more uniformly

**Comment by roryabraham** [comment]
That sounds like a good solution to me, assuming we have access to the accountID wherever we use `getDefaultAvatar`, which I'm 90% sure we do

**Comment by aldo-expensify** [comment]
Yes, since this is not important from a security point of view, we can use simple hash functions that do a decent job at distributing stuff uniformly in the buckets.

**Comment by aldo-expensify** [comment]
👋  @Szymon20000 , can you help me setting up some benchmarks to test this locally and provide results once I make the changes? I'm not familiar with how to do this in Android/React native environment

**Comment by aldo-expensify** [comment]
Created a draft pull request: https://github.com/Expensify/App/pull/11400 replacing the md5 hashing function by a simpler hashing function. Just looked up online and took the one Java uses for String.hashCode which should be enough for this case.

Would be good to be able to measure performance in our main branch and with the changes in the [aldo_hashcode-avatar](https://github.com/Expensify/App/tree/aldo_hashcode-avatar) branch

**Comment by roryabraham** [comment]
Why did you diverge away from this super simple solution?

```js
const bucket = (accountID * 31) % 8;
```

**Comment by aldo-expensify** [comment]
> Why did you diverge away from this super simple solution?
> 
> ```js
> const bucket = (accountID * 31) % 8;
> ```

because I needed the accountID which didn't seem to be easily available everywhere we call `getDefaultAvatar`. I thought it was just much easier to keep doing it with the email and use a faster string hash. For example, when you are searching for emails, we pick default avatars for accounts that don't even exist.
