### ISSUE TITLE
Android - Chat - Deleted message is displayed for brief moment after back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10780

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Select any user
4. Send message
5. .Go offline and delete that message
6. The message should not disappear but instead appear with a strike-through
7. Go online, the message should disappear

## Expected Result:
Deleted message should disappear after back online

## Actual Result:
Deleted message is displayed for brief moment after back online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No -new feature

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188166297-95d68c2c-091e-48f4-8c48-2806e03e7ba5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment]
Hey @tgolen, I think we can quickly fix this by using the reportAction's  `pendingAction` field inside the reportActionItem or reportActionItemFragment or maybe OfflineWithFeedback.

We can check if the reportAction is a comment and something like `pendingAction === styles.offlineFeedback.deleted && !props.network.isOffline` and render the text as an empty string in that case!

I can take this if that's ok or it can be an External issue too!

**Comment by tgolen** [comment]
@PauloGasparSv Feel free to gab and work on it

**Comment by PauloGasparSv** [comment]
Same issue from here: https://github.com/Expensify/App/issues/10753
