### ISSUE TITLE
New Contributor Checklist is running on issue comments

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#10802]
## Problem
The new contributor checklist should only be running on PRs, not on issues. https://github.com/Expensify/App/runs/8160318360?check_suite_focus=true

## Solution
Update when the contributor checklist test is running here: https://github.com/Expensify/App/blob/main/.github/workflows/testChecklists.yml#L13

**Comment by AndrewGable** [comment]
Been testing solutions, I can confirm the logic here is not working.

**Comment by AndrewGable** [comment]
For @mananjadhav - It seems like `issue_comment` is not running.

**Comment by AndrewGable** [comment]
Never mind- Looks like actually everything is working from what I can see.

@mananjadhav for your issues:
1. https://github.com/Expensify/App/pull/10769#pullrequestreview-1096909501 is passing ✅ 
2. https://github.com/Expensify/App/pull/10455#issuecomment-1234626155 is passing ✅ 
3. https://github.com/Expensify/App/pull/10503#issuecomment-1237417889 was using an outdated checklist. Updated it to the recent one and now it works. ✅ 

I would say, give the checks a ~minute to start running. Sometimes I think they aren't running, but they actually just took a minute to start up.

**Comment by mananjadhav** [comment]
Ohh thanks for checking this out @AndrewGable.
