### ISSUE TITLE
Web - LHN - Email address of the user is displayed instead of the last message with that user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Pay attention to the LHN and the display of the latest messages under each contact

## Expected Result:
The last message should be displayed under each contact

## Actual Result:
Last message is not displayed under the name, but the email address of that account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.97-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5718581_Untitled](https://user-images.githubusercontent.com/43996225/188482228-71af63cc-595b-4808-88a8-13e388c0c99b.png)

**Expensify/Expensify Issue URL:** applausetester+ihchat4@applause.expensifail.com / Yulia1986Gerets or Any

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
This was fixed yesterday.
