### ISSUE TITLE
Android - Global Unread Indicator - There is no Global Unread Indicator in Android App

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10739 

## Action Performed:
1. Launch the app
2. Login with any account (User A), ensure User A is not looking at the chat
3. Start a chat between User A and User B
4. Leave a comment on the chat as User B
5. Leave another comment

## Expected Result:
There is Global Unread Indicator in Android App

## Actual Result:
There is no Global Unread Indicator in Android App

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.97.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any
 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188522247-1df322c4-e297-4da8-9766-007922160798.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Interna Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
There isn't an unread indicator in the android app?

**Comment by Julesssss** [comment]
Yeah, this doesn't sound like a bug. @kbecciv is this issue suggesting that we don't have an unread counter on the app icon like iOS does?

**Comment by kbecciv** [comment]
@Julesssss @marcaaron Yes, there is no indicator in the Android app. I can check IOS app with build 1.1.96.5 (not update it yet to 1.1.97.2)

**Comment by Julesssss** [comment]
> @Julesssss @marcaaron Yes, there is no indicator in the Android app. I can check IOS app with build 1.1.96.5 (not update it yet to 1.1.97.2)

By 'In the Android app', do you mean while the app is opened, in the List of user chats? Or in the Android OS Home Screen, where you see the app icons? Because if it's the latter then there's no bug here. Android has notification badges, which uses notifications to show a dot on the icon, but the count that iOS has is not supported by Android.
