### ISSUE TITLE
[$250] Red dot is missing on workspace settings page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Do Onyx.merge('policy_8C6BF17C3E92D600', {pendingAction: 'add', errorFields: {avatar: {1: 'This is an error'}}}); in the console
2. Notice red dot on your profile image, click it
3. Notice red dot on your workspace name, click it
4. Issue: there is no RBR in the workspace settings
5. Click General Settings and see the red dot by the avatar

## Expected Result:
RBR should display on workspace settings page

## Actual Result:
RBR is missing on workspace settings page

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img width="359" alt="image - 2022-09-06T002403 516" src="https://user-images.githubusercontent.com/43995119/188546669-3b8a9641-8a59-4d5c-8750-a326f79d32dc.png">
<img width="367" alt="image - 2022-09-06T002402 251" src="https://user-images.githubusercontent.com/43995119/188546671-ca83234d-38d9-41a4-9ac5-a597fea88a12.png">
<img width="364" alt="image - 2022-09-06T002400 839" src="https://user-images.githubusercontent.com/43995119/188546676-e0c4d6e5-3ff5-4c18-b52f-f188f79260d4.png">

**Upwork job URL:** https://www.upwork.com/jobs/~014435583ac8f1a5c4
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662106163497789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
### Proposal

We are checking wrong key for errors ( `avatarURL` )
https://github.com/Expensify/App/blob/a944496cfd9cd21b799c82a8128964b05dd50b42/src/pages/workspace/WorkspaceInitialPage.js#L85

We have to check replace it with `avatar`

**Comment by danieldoglas** [comment]
@mvtglobally the API is actually returning `avatarURL` and not `avatar`. Can you point to me where you got that testing steps from? We'll probably need to update it

**Comment by puneetlath** [comment]
@danieldoglas that was from me when I was testing a different PR. So if I had that wrong, then we're all good.

**Comment by danieldoglas** [comment]
Got it! so I think we can close this one out! thanks @punee

**Comment by thesahindia** [comment]
Hi @danieldoglas, I think we should reopen this issue. 

Steps to repro the issue -
1. Add a photo in your workspace "xyz"
2. Open a new tab and visit https://www.expensify.com/admin_policies and delete that "xyz" workspace
3. Go back to the tab where new dot is open and try removing the image from "xyz" workspace
4. Check you see an error
5. Now press back and check if you are seeing the red indicator

We get the avatar related errors at `errorFields.avatar` but we are checking for the errors at `errorFields.avatarURL` we can solve this by replacing `avatarURL` with `avatar` as proposed [here](https://github.com/Expensify/App/issues/10831#issuecomment-1237734638).

**Comment by thesahindia** [comment]
https://user-images.githubusercontent.com/83179295/188857601-ca2e10c3-5214-4300-aa3e-cd1f9d7b5bd1.mov

**Comment by danieldoglas** [comment]
@thesahindia @puneetlath it seems like we're using `avatar` and `avatarURL`, depending on the requests. So it was my mistake here on closing this.

in this specific case, it seems like we should check for both, so I would adjust your proposal to do that, @thesahindia. I'll export this.

At the same time, tagging @Gonals to give his opinion on standardizing the name for avatar/avatarURL in all methods.

**Comment by danieldoglas** [comment]
Also, this situation only happens because the Workspace was delete before editing. I think we're not doing the right requests here to guarantee that we're actually using a valid workspace when accessing it. @arosiclair might be able to give more context upon this.

**Comment by thesahindia** [comment]
I thought we only get the error at `avatar` and not at `avatarURL` because [here](https://github.com/Expensify/App/blob/c8018b296ec6c1d84a7d5d8013feefb7d2a558de/src/pages/workspace/WorkspaceSettingsPage.js#L106) we are only checking `avatar` key for the error. If we also get the error at avatarURL then I think we will have to make the same change to check both keys here too
https://github.com/Expensify/App/blob/c8018b296ec6c1d84a7d5d8013feefb7d2a558de/src/pages/workspace/WorkspaceSettingsPage.js#L106

**Comment by Gonals** [comment]
I like `avatarURL`, but I'm fine with either

**Comment by arosiclair** [comment]
> Also, this situation only happens because the Workspace was delete before editing. I think we're not doing the right requests here to guarantee that we're actually using a valid workspace when accessing it.

I don't think we get Pusher updates from OldDot so the policy doesn't get removed in NewDot until you refresh (`OpenApp` / `ReconnectApp` commands). If we're offline, the policy will stay until you reconnect.

**Comment by danieldoglas** [comment]
@arosiclair  When we open a policy page, we're not doing a GET for that policy today?

**Comment by arosiclair** [comment]
> @arosiclair When we open a policy(workspace) page, we're not doing a GET for that policy today?

We are until [this PR I'm working on](https://github.com/Expensify/App/pull/10873) get's merged

**Comment by thesahindia** [comment]
> @thesahindia @puneetlath it seems like we're using avatar and avatarURL, depending on the requests. So it was my mistake here on closing this.

@danieldoglas, are there any steps to repro an error for avatarURL?

**Comment by danieldoglas** [comment]
@thesahindia No, just for avatar. It is already treating avatarURL, as seen [here](https://github.com/Expensify/App/blob/a944496cfd9cd21b799c82a8128964b05dd50b42/src/pages/workspace/WorkspaceInitialPage.js#L85), so we shouldn't have any errors.

**Comment by thesahindia** [comment]
I was trying to produce an error for avatarURL key, I wanted to check the general settings page when we get error at `avatarURL` because we aren't checking `avatarURL` for errors at general settings ([Code](https://github.com/Expensify/App/blob/c8018b296ec6c1d84a7d5d8013feefb7d2a558de/src/pages/workspace/WorkspaceSettingsPage.js#L106))

So just to confirm, we will be adding another OR operator here https://github.com/Expensify/App/blob/c8018b296ec6c1d84a7d5d8013feefb7d2a558de/src/pages/workspace/WorkspaceSettingsPage.js#L106

and will check for errors at avatar `!_.isEmpty(lodashGet(this.props.policy, 'errorFields.avatar, {}))`

And we will be adding one OR operator here to also search for errors at `avatarURL` because we are only checking `avatar` for errors at this page https://github.com/Expensify/App/blob/c8018b296ec6c1d84a7d5d8013feefb7d2a558de/src/pages/workspace/WorkspaceSettingsPage.js#L106

**Comment by danieldoglas** [comment]
@thesahindia yes, that makes sense to me!

**Comment by michaelhaxhiu** [comment]
@thesahindia nice catch on this GH and pushing to keep it open!

I just made the job in upwork here - https://www.upwork.com/jobs/~014435583ac8f1a5c4.

@danieldoglas is it safe to say we are hiring @thesahindia for the fix?

**Comment by danieldoglas** [comment]
@michaelhaxhiu for me yes, but @Julesssss has the final word in this case :D

**Comment by Julesssss** [comment]
Yeah, hiring @thesahindia

**Comment by Julesssss** [comment]
I also think we should merge the keys, but that's out of scope for this PR and requires backend changes.

**Comment by michaelhaxhiu** [comment]
@thesahindia invited you to job in case you missed this initially.

**Comment by thesahindia** [comment]
> I also think we should merge the keys, but that's out of scope for this PR and requires backend changes.

Hey @Julesssss, I also believe we should merge the keys, I can wait for the backend change.

**Comment by thesahindia** [comment]
> @thesahindia invited you to job in case you missed this initially.

Applied! Thanks.

**Comment by thesahindia** [comment]
> Hey @Julesssss, I also believe we should merge the keys, I can wait for the backend change.

Let me know if we can wait for the backend change. If not I can raise the PR today.

cc: @Julesssss

**Comment by Julesssss** [comment]
@thesahindia let's forget about that for now and create a new refactor issue for merging the keys

**Comment by Julesssss** [comment]
Ah yes. @michaelhaxhiu let's just pay out the job.

**Comment by thesahindia** [comment]
> Ah yes. @michaelhaxhiu let's just pay out the job.

Hmm, I don't think it's eligible for the payment because no PR was created.

**Comment by michaelhaxhiu** [comment]
Yep I agree with paying it @Julesssss. I think this was unforseen. All good with me proceeding rn?

**Comment by Julesssss** [comment]
> Yep I agree with paying it @Julesssss. I think this was unforseen. All good with me proceeding rn?

Yeah 👍

**Comment by michaelhaxhiu** [comment]
done, closing ✌️

**Comment by thesahindia** [comment]
Thank you ♥️

**Comment by michaelhaxhiu** [comment]
weird, this didn't close initially when I thought it did.
