### ISSUE TITLE
[HOLD #6527] WorkSpace photo not updating after navigating away - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to Workspace General Settings
 2. Upload photo
 3. Go  to previous screen before uploading complete
 4. Go back to  General Settings
 
## Expected Result:
it should show updated photo

## Actual Result:
 it shows old photo

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/188785160-37a3019c-9fa7-4b14-8d81-867d537a4c67.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661248919359519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
i think this is good to be sent to eng

**Comment by roryabraham** [comment]
I think in order for this to work we'll need code in place to serialize images and save them in Onyx. Some of the groundwork for that has been laid, but I don't think this is something we should try to roll out without going through the WN/design doc process.

**Comment by roryabraham** [comment]
We should probably create a tracking issue for this class of issue/feature request (dependent upon images being loaded into Onyx), and the project needs a champion. In the meantime, I'm going to HOLD this on https://github.com/Expensify/App/issues/6527 and slap the planning label on it

**Comment by jasperhuangg** [comment]
The behavior shouldn't be like this anymore.. we update the workspace photo optimistically and the loading spinner shouldn't show anymore.

**Comment by jasperhuangg** [comment]
Just confirmed on prod on iOS that this doesn't happen, closing.

https://user-images.githubusercontent.com/31285285/191599139-a70fb19b-8d9d-4923-b667-a4f91fca38ae.mov
