### ISSUE TITLE
[HOLD for payment 2022-10-31] [$250] Payment methods have wrong height - reported by @rushatgabhane

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Go to Settings -> Payments

## Expected Result:
Payment methods have a height of 64px

## Actual Result:
Payment methods have a height of 64.5px

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="392" alt="image - 2022-09-06T234836 704" src="https://user-images.githubusercontent.com/43995119/188784701-8ff06aed-0bf1-4e45-9554-35648df95597.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661196724356509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 

We need to pass `styles.lh16` here

https://github.com/Expensify/App/blob/85172f72f1abbf1976e6abd3c08f5f74c04ae1b6/src/components/MenuItem.js#L55

**Comment by flaviadefaria** [comment]
Adding the engineering label but doesn't seem like a priority.

**Comment by MonilBhavsar** [comment]
Not priority, coming back

**Comment by MonilBhavsar** [comment]
Not priority, coming back

**Comment by Puneet-here** [comment]
@MonilBhavsar, this can be fixed by only adding a style as proposed [here](https://github.com/Expensify/App/issues/10848#issuecomment-1239058273).

**Comment by sobitneupane** [comment]
Adding [styles.lh16](https://github.com/Expensify/App/issues/10848#issuecomment-1239058273) will be enough to make Payment methods height 64. But I am not sure what is the expected output here. Want to have some feedback from Design team before moving forward.

cc: @MonilBhavsar, @shawnborton

**Comment by shawnborton** [comment]
I think that should do it, yeah. We will just want to be sure to test this with various platform zooms, etc.

**Comment by sobitneupane** [comment]
Thanks @shawnborton.

@MonilBhavsar [Proposal](https://github.com/Expensify/App/issues/10848#issuecomment-1239058273) from @Puneet-here looks good to me.


🎀👀🎀 C+ reviewed

**Comment by flaviadefaria** [comment]
Internal job post - https://www.upwork.com/ab/applicants/1579798560037728256/job-details
External post - https://www.upwork.com/jobs/~0102289ba6d99dee28

**Comment by flaviadefaria** [comment]
@MonilBhavsar I think we're just waiting on you now to move forward with the proposal.

**Comment by MonilBhavsar** [comment]
@shawnborton a suggestion: How about having preferred CSS stylings/dimensions in a doc and include that in our PR Review checklist?

**Comment by shawnborton** [comment]
Yeah, I think ideally this row component would be documented in some kind of style guide. Not sure how that works with a PR checklist but I do think that we should require a design review on all PRs - I will propose that soon!

**Comment by MonilBhavsar** [comment]
I mean If a new UI component is added, verifying its dimensions are as per our standard (Not sure, but may be a multiple of 8 always)

**Comment by flaviadefaria** [comment]
I'll come back to this in the next days.

**Comment by MonilBhavsar** [comment]
@flaviadefaria I think we're good to issue payment to everyone

**Comment by sobitneupane** [comment]
@flaviadefaria Waiting for payment.

**Comment by flaviadefaria** [comment]
Sorry for the delay here. I'll process the payment now.

**Comment by flaviadefaria** [comment]
@sobitneupane @Puneet-here you haven't applied so I invited you two to the job please accept and comment here when you have done so. Thanks!

**Comment by sobitneupane** [comment]
@flaviadefaria Accepted.

**Comment by flaviadefaria** [comment]
All three people have been paid, the contract has been completed, and the Upwork post has been closed.
