### ISSUE TITLE
Navigating directly to url https://new.expensify.com/iou/split throws 404 error - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Navigate to https://new.expensify.com/iou/split

## Expected Result:
Split page should load without any errors 

## Actual Result:
Split page Loads with 404 error in console 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.97-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

![Screen Shot 2022-09-07 at 12 16 09 AM](https://user-images.githubusercontent.com/43995119/188787610-7999c747-8b56-49a2-8770-282508f94c56.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661264738181509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Closing as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661280139050409)
