### ISSUE TITLE
https://new.expensify.com/settings throws console 404 error - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Navigate to https://new.expensify.com/settings 

## Expected Result:
No Console errors should display 

## Actual Result:
Console error displayed after navigating to https://new.expensify.com/settings 

Locally app crashes on navigating to http://localhost:8080/settings and throws error TypeError: Cannot read properties of undefined (reading 'replace') as seen in screenshot attached.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.97-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  

![Screen Shot 2022-09-07 at 12 29 44 AM](https://user-images.githubusercontent.com/43995119/188789089-795013bf-22b1-4b2d-85dc-25363e4f556b.png)

<img width="1440" alt="Screenshot 2022-08-23 at 8 03 45 PM" src="https://user-images.githubusercontent.com/43995119/188789303-161221ed-d407-481e-8544-ef0cc4b9bdc3.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661267145297999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
leaving myself assigned as I can take on contributor management side of this!

**Comment by Julesssss** [comment]
Closing as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661280139050409)
