### ISSUE TITLE
[HOLD for payment 2022-10-07] [$250] Web - Hover over emoji is not working as expected @mdneyazahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report
3. Click on emoji icon on composer
4. Type arrow
5. Try to hover on emojis and observe the style applied to emoji in the corner.

## Expected Result:
Hover style should be removed when cursor is removed from the emoji.

## Actual Result:
Hover style is not removed when cursor is removed from the emoji.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188884484-1116f06f-4811-46e0-abbc-52e2133de5a9.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @mdneyazahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661256134588919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Agreed. I think this might be related to edge detection. It happens for me when I type `arrow` as well. However, if I also type something like `smile`, I'm seeing the same behavior, but only when a hover over an emoji at the edge of the grid of available emojis. 

![2022-09-07_16-18-02 (1)](https://user-images.githubusercontent.com/54866469/188916421-b55eca4c-82d4-4ecc-9110-913566f6c509.gif)

**Comment by puneetlath** [comment]
Internal Upwork job: https://www.upwork.com/ab/applicants/1567839053011177472/job-details
External Upwork job: https://www.upwork.com/jobs/~014411ca93fc9955e5

**Comment by stitesExpensify** [comment]
It's not harmful to the physical function but it is good polish IMO. The expected UX for all other apps I use (github, whatsapp, slack, etc) stop hover when you aren't hovering

**Comment by quidam93** [comment]
### Proposal

**Cause of the issue**
I will explain the issue. There is an option in Hoverable component for the "hover out" and "hover in" events. However in EmojiPicker component, only hover in callback is used. 

**Solution**
We tried to implement the hover out callback as well. 

Highlighted items are controlled with a state in the component as "highlightedIndex". It is set to -1 if nothing is highlighted. We used this hover out callback to set the state to -1 and the emoji picker component is now working as expected.

Changes are only done in EmojiPicker component so there will be no change in the other components that uses Hoverable(If there are any).

**Desired scenario**
Arrow is not visible in the video but highlight functionality can be seen.
![10865 (1)](https://user-images.githubusercontent.com/26013008/189128129-51523d0d-cfd5-457d-b157-739c58c4809f.gif)

**Test**
Only tested in the web platform. Will make the remaining tests once the job starts.

**Comment by quidam93** [comment]
@mdneyazahmad Thanks for the heads up! Also fixed that issue with a check before setting highlightedIndex to -1.

![10865_2](https://user-images.githubusercontent.com/26013008/189143876-3accf4f1-6271-47e6-8e2b-ace1cafd3a9f.gif)

**Comment by mollfpr** [comment]
### Proposal

**Root cause**
When hovering on an item we set the index of the item to `this.state.highlightedIndex`. When we not hovering on the item, the last item set to `this.state.highlightedIndex` is still remaining.

https://github.com/Expensify/App/blob/1718572434eafd9c3a816653c6eb8a95054e958c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L442

**Solution**
On `EmojiPickerMenuItem` define new props `onHoverOut`. Now we can handle it when we hover out the item and set `this.state.highlightedIndex` to `-1` (none of any item index). I also added padding horizontal to the emoji items to fix the issue when hovering from right to left.

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenuItem.js b/src/components/EmojiPicker/EmojiPickerMenuItem.js
index ee24d689f..06428ca38 100644
--- a/src/components/EmojiPicker/EmojiPickerMenuItem.js
+++ b/src/components/EmojiPicker/EmojiPickerMenuItem.js
@@ -17,6 +17,9 @@ const propTypes = {
     /** Handles what to do when we hover over this item with our cursor */
     onHover: PropTypes.func,
 
+    /** Handles what to do when the hover is out */
+    onHoverOut: PropTypes.func,
+
     /** Whether this menu item is currently highligh
ted or not */
     isHighlighted: PropTypes.bool,
 };
@@ -33,7 +36,7 @@ const EmojiPickerMenuItem = props =
> (
             styles.emojiItem,
         ])}
     >
-        <Hoverable onHoverIn={props.onHover}>
+        <Hoverable onHoverIn={props.onHover} onHover
Out={props.onHoverOut}>
             <Text style={[styles.emojiText]}>
                 {props.emoji}
             </Text>
@@ -46,6 +49,7 @@ EmojiPickerMenuItem.displayName = '
EmojiPickerMenuItem';
 EmojiPickerMenuItem.defaultProps = {
     isHighlighted: false,
     onHover: () => {},
+    onHoverOut: () => {},
 };
 
 // Significantly speeds up re-renders of the EmojiPi
ckerMenu's FlatList
```

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenuItem.js b/src/components/EmojiPicker/EmojiPickerMenuItem.js
index ee24d689f..235dd5673 100644
--- a/src/components/EmojiPicker/EmojiPickerMenuItem.js
+++ b/src/components/EmojiPicker/EmojiPickerMenuItem.js
@@ -17,6 +17,9 @@ const propTypes = {
     /** Handles what to do when we hover over this item with our cursor */
     onHover: PropTypes.func,
 
+    /** Handles what to do when the hover is out */
+    onHoverOut: PropTypes.func,
+
     /** Whether this menu item is currently highlighted or not */
     isHighlighted: PropTypes.bool,
 };
@@ -28,12 +31,13 @@ const EmojiPickerMenuItem = props => (
             pressed,
         }) => ([
             styles.pv1,
+            styles.ph1,
             StyleUtils.getButtonBackgroundColorStyle(getButtonState(false, pressed)),
             props.isHighlighted ? styles.emojiItemHighlighted : {},
             styles.emojiItem,
         ])}
     >
-        <Hoverable onHoverIn={props.onHover}>
+        <Hoverable onHoverIn={props.onHover} onHoverOut={props.onHoverOut}>
             <Text style={[styles.emojiText]}>
```


**Result**

https://user-images.githubusercontent.com/25520267/189147084-6f8da53e-3ca3-4d86-86c5-43829777c408.mov

**Comment by quidam93** [comment]
> @quidam93 thanks for your proposal! This is a tough call, but @mollfpr's proposal also handles hovering from right to left.
> 
> @stitesExpensify I like @mollfpr's proposal 🎀 👀 🎀 C+ reviewed

In my opinion, extra padding can cause visual bugs on different devices and my solution doesn't change anything in the UI but it is of course your decision. Thanks for the consideration!

**Comment by quidam93** [comment]
@rushatgabhane good to hear! Have a nice day.

**Comment by mollfpr** [comment]
Here's the code to fix skin tone hover.
```diff
diff --git a/src/components/EmojiPicker/EmojiSkinToneList.js b/src/components/EmojiPicker/EmojiSkinToneList.js
index 45dc28755..0b9389a47 100644
--- a/src/components/EmojiPicker/EmojiSkinToneList.js
+++ b/src/components/EmojiPicker/EmojiSkinToneList.js
@@ -85,6 +85,7 @@ class EmojiSkinToneList extends Component {
                                     <EmojiPickerMenuItem
                                         onPress={() => this.updateSelectedSkinTone(skinToneEmoji)}
                                         onHover={() => this.setState({highlightedIndex: skinToneEmoji.skinTone})}
+                                        onHoverOut={() => this.setState({highlightedIndex: -1})}
                                         key={skinToneEmoji.code}
                                         emoji={skinToneEmoji.code}
                                         isHighlighted={skinToneEmoji.skinTone === this.state.highlightedIndex}
```

https://user-images.githubusercontent.com/25520267/189976363-76acff3c-939f-46d8-8ed3-d65d01886100.mov



cc @rushatgabhane @stitesExpensify

**Comment by mollfpr** [comment]
Bump @puneetlath 👀

**Comment by puneetlath** [comment]
The proposal sounds good to me. Let's do it. 

@mollfpr @mdneyazahmad @rushatgabhane can you all apply to the upwork job if you haven't already?

**Comment by mollfpr** [comment]
@puneetlath Applied, thank you!

**Comment by puneetlath** [comment]
Conversation ongoing on PR.

**Comment by puneetlath** [comment]
@mollfpr paid. 

@rushatgabhane hiring offer sent.

**Comment by puneetlath** [comment]
@rushatgabhane paid. 

Also sent hiring offer to @mdneyazahmad. Sorry, almost forgot about you!

**Comment by puneetlath** [comment]
All paid now. Thanks everyone!
