### ISSUE TITLE
Mileage rate is 0.00 for the newly created workspace instead of the rate set in the policy

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10692
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Create a New Workspace
3. Go to to Settings -> [Workspace] -> Reimburse expenses
4. Try to change the mileage rate and the mi/km selector

## Expected Result:
1. Mileage rate should display the value you have in your policy
2. The mileage rate should be editable
3. The miles/km selector must be operational

## Actual Result:
1. A new workspace is created with 0.00 milage rate (the rate is set in this policy)
2. When you try to edit the mileage rate, you get an error
3. Cannot change miles to kilometers

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Mobile Web

**Version Number:** v1.1.97-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com  / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**  https://user-images.githubusercontent.com/43996225/188964955-fd47cd77-6122-44e9-b33b-956300963889.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Damn, this is a new regression occurring from another blocker fix. 

@Expensify/mobile-deployers

**Comment by yuwenmemon** [comment]
Looks like the workspace is undefined in Onyx when we first create it?
<img width="1539" alt="Screen Shot 2022-09-07 at 1 25 10 PM" src="https://user-images.githubusercontent.com/4741899/188971589-f009e78d-bf94-49ea-a79e-3f0359528cd8.png">

When I refresh the page and open the page again, the mileage rate shows and can be updated:

<img width="1535" alt="Screen Shot 2022-09-07 at 1 33 07 PM" src="https://user-images.githubusercontent.com/4741899/188971769-8633dd3f-c8d5-4415-b98b-d5b72315d482.png">

**Comment by yuwenmemon** [comment]
Oh, interesting. The PolicyID changed for the workspace...

**Comment by yuwenmemon** [comment]
Actually wait no, I think the problem is that there are two custom units on the initially created policy...
<img width="690" alt="Screen Shot 2022-09-07 at 1 40 49 PM" src="https://user-images.githubusercontent.com/4741899/188973542-0febadfa-f691-49db-ab7d-0adbc4995037.png">

**Comment by yuwenmemon** [comment]
So somewhere we're not keying the customUnit by the ID when we update Onyx 🤔

**Comment by yuwenmemon** [comment]
I would guess it's this line: https://github.com/Expensify/App/blob/367b662a37dbc470b665bb48203fbedde74e60d1/src/libs/actions/Policy.js#L91

**Comment by yuwenmemon** [comment]
Hm no actually it's coming from the `CreateWorkspace` API command:
![Screen Shot 2022-09-07 at 2 19 42 PM](https://user-images.githubusercontent.com/4741899/188982978-b90784ce-01b6-4a99-84f5-60987d76a12b.png)

**Comment by yuwenmemon** [comment]
Hm yeah - so the problem is that the structure with which we hold Custom Units in OldDot is as an array:

<img width="844" alt="Screen Shot 2022-09-07 at 2 25 22 PM" src="https://user-images.githubusercontent.com/4741899/188984163-54218416-33cf-4304-887e-a8de7b6ce47b.png">

But in NewDot we want it to be an object keyed by the CustomUnitID:
<img width="642" alt="Screen Shot 2022-09-07 at 2 26 51 PM" src="https://user-images.githubusercontent.com/4741899/188984477-527a51df-3cd9-4423-9dfb-f5fec3944efa.png">

**Comment by yuwenmemon** [comment]
Ah yep, so @amyevans @jasperhuangg we just missed one spot [here](https://github.com/Expensify/Web-Expensify/pull/34587) - we also want to do the data massaging we do in [Getting](https://github.com/Expensify/Web-Expensify/blob/9f57a97882368e3b85092c3382816ccdc07ad2a5/lib/GetAPI.php#L154-L160) the policy when we Create the policy as well.

**Comment by Julesssss** [comment]
Thanks so much, this works perfectly 😍 

https://user-images.githubusercontent.com/10736861/189005727-0a6b35f4-9ea8-4946-ad43-653e52dbb86a.mov

![Screenshot_20220908-010228](https://user-images.githubusercontent.com/10736861/189005817-9729b208-fcc7-40c9-8451-62a6882615a1.png)

**Comment by amyevans** [comment]
Oh goodness, thanks for fixing @yuwenmemon and @Julesssss ❤️
