### ISSUE TITLE
Workspace - Unable to create Workspace while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10749

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with new expensifail account
3. Turn off the internet
4. Click on Fub menu
5 Select Create a New Workspace

## Expected Result:
Able to create Workspace while offline

## Actual Result:
Unable to create Workspace while offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188992657-1f32fca9-42ce-46e9-b972-0ba552ade68c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Can you test this again on staging? The PR that just enabled this was added to staging 7 hours ago https://github.com/Expensify/App/pull/10723

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment]
Closing as this should be resolved as mentioned in this comment https://github.com/Expensify/App/issues/10878#issuecomment-1240386319
