### ISSUE TITLE
[Hold for Payment] Url is broken when /settings/security/password or /settings/security/closeAccount is closed - Reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open web app https://new.expensify.com/
2. Click on user icon on LHN to open setting.
3. Click on security on RHN.
4. Click change password or close account.
5. Close RHN by clicking cross or clicking outside.

## Expected Result:
Url should be r/reportID

## Actual Result:
Url is /settings/security

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/189034676-3153dd7b-7600-46de-8981-af669adbd541.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661287351063199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
back from OOO, looking at this now

**Comment by sonialiap** [comment]
I'm not able to reproduce the steps in this issue, but I am able to reproduce the steps in this one https://github.com/Expensify/App/issues/10952 which covers the same or very similar issue. Closing in favor of #10952

**Comment by aneequeahmad** [comment]
@sonialiap  This navigation issue is fixed in latest production. Reporting bonus payment is pending as per this [comment](receipts@expensify.com)
 
 Attaching screen recording for verification. Thanks
 
 

https://github.com/Expensify/App/assets/36359331/44eaa105-ac5d-42e4-a5c9-0427543cd372

cc: @jasperhuangg

**Comment by jasperhuangg** [comment]
Feel free to close out the issue if payment was issued/no next steps need to be taken.

**Comment by sonialiap** [comment]
@aneequeahmad the link you shared is to a GH search rather than a comment. Could you please share the correct link so that I can take a look?

**Comment by aneequeahmad** [comment]
@sonialiap apologies here is the link of [comment](https://github.com/Expensify/App/issues/11111#:~:text=I%20think%20we%20can%20still%20compensate%20you%20for%20reporting%20each%20of%20the%20issues%20separately%2C%20since%20I%20do%20recognize%20that%20it%20requires%20some%20time%20to%20find%20them%20even%20if%20they%20have%20the%20same%20source.).

**Comment by sonialiap** [comment]
@aneequeahmad Thanks! Offer sent

Reporting $50 - offer sent

https://www.upwork.com/jobs/~01da946f1c0e7020a1

**Comment by aneequeahmad** [comment]
@sonialiap Shouldn't the offer be $250 ? since at the time of reporting bug this was the amount for each bug report.

**Comment by sonialiap** [comment]
Apologies, I didn't pay attention to the year the issue was opened, what a delay in payment request! You're correct, the reporting bonus is $250 for this. I've updated offer to $250

**Comment by aneequeahmad** [comment]
@sonialiap Great, Accepted the offer. Thanks for mentioning.

**Comment by sonialiap** [comment]
Paid ✔️
