### ISSUE TITLE
iOS - Members - Member added when offline, appear without avatar image returning online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10896]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR #10668 
## Action Performed:
1. Log in an new account
2. Create a new user
3. Create a new workspace
4. While online, navigate to the workspace members page (Workspace > Manage members) and verify the owner is in the list
5. Add a new member to the workspace
6. Navigate back to the workspace members page and verify they were added
7. Go back to the home page
8. Disconnect connectivity
9. Verify we can navigate to the workspace members page

## Expected Result:
Added offline members should show up with an avatar image when returning online

## Actual Result:
Added offline members appear without avatar image when returning online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.98
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 

https://user-images.githubusercontent.com/43996225/189117570-73306c46-56ea-4518-8679-f9db9025569f.mp4

**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
I wasn't able to reproduce this either on my iOS device build 1.1.98 or locally on the `main` branch:

https://user-images.githubusercontent.com/7277067/189550470-85c9ea0c-d0e1-47a4-8943-40ccf82c647a.mov

@kavimuru could you retest and let me know if you can still reproduce?

Also just a note that I'll be OOO through 9/20 (but will check in periodically).

**Comment by kbecciv** [comment]
@amyevans Issue is still reproduceable with build 1.1.99.2

https://user-images.githubusercontent.com/93399543/189729580-be5a91ac-c51a-4dc4-baf7-4065b533d549.mp4

**Comment by amyevans** [comment]
Back from OOO today but ran out of time to dig back in here. It's on my radar for tomorrow.

**Comment by amyevans** [comment]
I've tested again, both on simulator and physical device, and cannot reproduce:

https://user-images.githubusercontent.com/7277067/191631144-6fddf7c0-3ba3-457e-a96e-753158567194.mov

Given this is either an extreme edge case or not a bug, I don't think it's worth devoting additional resources to so am going to close.
