### ISSUE TITLE
 Email - Additional lines added to the message when replying via email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10898]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.newt.expensify.com and log in as account A
2. As account A send some messages to an account that must be a main email address without the +. Wait 10 minutes. This will trigger an email notification to this account.
3. Log out of Account A
4. After 10 min has passed, check the main account email inbox and open the mail with this name "Chat between <A> and <B>".
5. Answer to the email with any message.
6. Wait a minute or 2 and log into both accounts (A and main account).
7. Verify the message you sent via email is displayed

## Expected Result:
There is no additional lines added to the message when replying via email

## Actual Result:
Additional lines added to the message when replying via email

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.98.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189128940-091a72ae-dc0c-4c80-9b6c-4573b37ec315.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hm, I wasn't able to reproduce this on my side. This is what it looked like when I sent one via email: 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1371996/190002454-1a1c188a-ddc0-4cb2-b6e3-24a0e569717f.png">

Going to close.
