### ISSUE TITLE
[$250] IOU - User can enter a number with few leading zeros like 0000.12 in money request field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Click the FAB button and select `Request Money`
3. Enter a number with a few leading zeros, like 000000.12 or 0000012.12

## Expected Result:
The user cannot enter a number with a few leading zeros, like 0000.12

## Actual Result:
User can enter a number with few leading zeros, like 0000.12 and this number will be saved when user returns to this screen.

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/189175060-d8471ffd-b092-4100-b48a-51cb2f64b112.png" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/189175076-3044c87d-8ef3-4af0-a22a-bd9bce46ac25.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- In that case, whereby the user cannot add leading zeros we should disable the save button to restrict saving those values 

**Changes**

`isDisabled={!this.state.amount.length || parseFloat(this.state.amount) < 1} `

https://github.com/Expensify/App/blob/c9b41bff8b728073db85f38782b591a0fd4a9772/src/pages/iou/steps/IOUAmountPage.js#L276-L284

**Results**

<img src=https://user-images.githubusercontent.com/47522946/189269387-fcababb5-2c55-4dac-a52a-583d090aa37b.png  width=50%>

**Comment by varshamb** [comment]
### Proposal

We should add REGEX to check the entered value on `IOUAmountPage` and also give message or error message if entered value doesn't match REGEX.

**Comment by sketchydroide** [comment]
Let's make this external

**Comment by NicMendonca** [comment]
Job post: https://www.upwork.com/jobs/~01d42e47c2501ce865

**Comment by m-usman-yousuf** [comment]
**Proposal**
I will solve the issue by using  javascript functions that will replace zeroes with null so if you keep entering zeroes the function will replace the value with null ,hence, not allowing user to enter leading zeroes.

**Comment by m-usman-yousuf** [comment]
@parasharrajat I have gone through the contribution guideline  and edited my proposal.If I am missing something again kindly guide.

**Comment by m-usman-yousuf** [comment]
@parasharrajat i have come from upwork and it says that the proposal should not include the code
![Screenshot_20220916-020820_Freelancer - Upwork](https://user-images.githubusercontent.com/52995752/190509124-7012b7ba-78a3-4460-8fa2-0dee11e0a0ed.jpg)

**Comment by dimasna** [comment]
Proposal :

Using Regex  /^0+(?!\.|$)/ in striptCommaFromAmount function : 
````diff
/**
     * Strip comma from the amount
     *
     * @param {String} amount
     * @returns {String}
     */
    stripCommaFromAmount(amount) {
+        return amount.replace(/^0+(?!\.|$)/, '');
    }
````
with adjustment cursor position : 
```diff

getNewSelection(oldSelection, prevLength, newLength) {
+        if (oldSelection.start < newLength && oldSelection.end < newLength) {
+            return { start: oldSelection.start + 1, end: oldSelection.end + 1 };
+       } else {
+           return { end: newLength, start: newLength };
+       }
    }

```
```diff
updateAmountNumberPad(key) {
        // Backspace button is pressed
        if (key === '<' || key === 'Backspace') {
            if (this.state.amount.length > 0) {
                this.setState((prevState) => {
+                    const selectionStart =  prevState.selection.start - 1;
                    const amount = `${prevState.amount.substring(0, selectionStart)}${prevState.amount.substring(prevState.selection.end)}`;
                    if (!this.validateAmount(amount)) {
                        return prevState;
                    }
+                    return { amount, selection: {start: selectionStart, end: selectionStart} };
                });
            }
            return;
        }
        
        this.setState((prevState) => {
            const amount = this.addLeadingZero(`${prevState.amount.substring(0, prevState.selection.start)}${key}${prevState.amount.substring(prevState.selection.end)}`);
+            const formattedAmount = this.stripCommaFromAmount(amount)
+            if (!this.validateAmount(formattedAmount)) {
                return prevState;
            }
+            const selection = this.getNewSelection(prevState.selection, prevState.amount.length, formattedAmount.length)
+            return { amount: formattedAmount, selection };
        });
    }
```

```diff
updateAmount(text) {
        this.setState((prevState) => {
+ const amount = this.stripCommaFromAmount(this.addLeadingZero(this.replaceAllDigits(text, this.props.fromLocaleDigit)));
            return this.validateAmount(amount)
+                ? { amount: amount }
                : prevState;
        });
    }
```

```diff
<TextInputWithCurrencySymbol
                        formattedAmount={formattedAmount}
                        onChangeAmount={this.updateAmount}
                        onCurrencyButtonPress={this.navigateToCurrencySelectionPage}
                        placeholder={this.props.numberFormat(0)}
                        preferredLocale={this.props.preferredLocale}
                        ref={el => this.textInput = el}
                        selectedCurrencyCode={this.props.iou.selectedCurrencyCode || CONST.CURRENCY.USD}
                        selection={this.state.selection}
                        onSelectionChange={(e) => {
+                           if (e.nativeEvent.selection.start <= formattedAmount.length && e.nativeEvent.selection.end <= formattedAmount.length) {
+                                this.setState({ selection: e.nativeEvent.selection });
+                            } else {
+                               this.setState({ selection: { end: formattedAmount.length, start: formattedAmount.length } });
                            }
                        }}
                    />
```
Result : 

https://user-images.githubusercontent.com/30913369/190551824-bad7e63a-4de7-4b0c-be2c-1292ec132a7b.mp4

**Comment by dimasna** [comment]
@parasharrajat how about my proposal?

**Comment by parasharrajat** [comment]
yeah, I guess so.

**Comment by sketchydroide** [comment]
closing
