### ISSUE TITLE
Web - Send money - User is not directed in correct chat after send money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to any account
3. Click on the green plus button in the LHN.
4. Select `Send money`
5. Enter an amount in the big number pad page
6. Click on the next button
7. Select an attendee from the list (that you have access to)
8. Add a comment, then select the confirmation button
9. Select Pay as I'll settle up elsewhere option

## Expected Result:
User is directed in correct chat after send money

## Actual Result:
User is not directed in correct chat after send money

## Workaround:
Unknown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.98.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189162636-06d75212-ff23-4a32-80c4-5ee3f5a4fc12.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
It is expected, It was logged before [here](https://github.com/Expensify/App/issues/9084).

**Comment by madmax330** [comment]
Commented in another issue where this was already fixed
