### ISSUE TITLE
[Hold for payment 2022-10-04] [$250] Add a rotating slate of placeholder text for Concierge chat

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#10923]
Creating this issue as a mirror to this E/E issue, so that the ContirbutorPlusReview label can be used. 

https://github.com/Expensify/Expensify/issues/209924

**Comment by puneetlath** [comment]
@Santhosh-Sellavel sorry for the confusion. You can go ahead and review the PR here: 

I'll get an Upwork job created for you: https://github.com/Expensify/App/pull/10899

**Comment by puneetlath** [comment]
PR is in review by @Santhosh-Sellavel.

**Comment by Santhosh-Sellavel** [comment]
@puneetlath What's the process here for payment?

**Comment by puneetlath** [comment]
@Santhosh-Sellavel sent you a hiring offer! Reopening the issue so I remember to pay out.

**Comment by Santhosh-Sellavel** [comment]
@puneetlath Accepted the offer, thanks!!

**Comment by puneetlath** [comment]
Paid!
