### ISSUE TITLE
[$250] Emojies - Change default skin tone option returns to its original color

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to any conversation
4. Click emoji
5. Сhoose skin ton 

## Expected Result:
The color of the skin must remain the one chosen.

## Actual Result:
Change default skin tone option returns to its original color

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189386062-e001c0eb-66ef-4830-9bc2-1a30ae2634e5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here & Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661506058979819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
So the main issue is that `this.props.preferredSkinTone` bounces between a number and a string. 

1. We have a preferred skintone set, either a number `0,1,2,3,4` or a string `"default"`. 
2. When we first load the emoji modal, [EmojiSkinToneList](https://github.com/Expensify/App/blob/a0765727dcc92d729ebf0b6acc47a41df728b681/src/components/EmojiPicker/EmojiSkinToneList.js#L38) will get the preferred skinTone saved in the NVP. If its a number, it will be an int. If its the "default", it will be a string.
3. When we then pick a non-default skin-tone, the options are `1` through `4`. So we pass the API call [User.updatePreferredSkinTone](https://github.com/Expensify/App/blob/42ab4338df2cf22eee5b4399dacfecbaab9e5e34/src/libs/actions/User.js#L386) a number. Lets say we pick 🖐🏼 (whose index is 4)
4. When it makes it to php, it turns into a string.
5. And when its passed back to Onyx, we set the key `PREFERRED_EMOJI_SKIN_TONE` to the string `"4"`
6. We search through the skin town list for "4", when that skinTone is indexed by an int. So `string === int` will always return false. 
    <img width="282" alt="image" src="https://user-images.githubusercontent.com/12980144/189728137-82691a28-15d5-4fbe-b274-e145ca25184d.png">
7. Having not ben able to find a skintone that is indexed by the string `"4"`, we always show the default skintone.
8. When we refresh, the onyxkey `PREFERRED_EMOJI_SKIN_TONE` value is properly set to a number. So it will be fixed on a hard refresh

**Comment by ctkochan22** [comment]
Why do we index every skinTone by number, except for the "default"? I feel like we should just have an index number for all of them.

@mananjadhav, @stitesExpensify  you handled the original PR. What do you think? Can we just switch the default to an index number? We can even set it to `-1`. 

<br/>

On the php side, we pass the index with a generic key `value`. The WAF inputRules for that is "anything". Keeping it just numbers will allow us to add a stricter input rules for updating skintone preference.

**Comment by mananjadhav** [comment]
```
{
        code: '👍',
        keywords: [
            '+1',
            'body',
            'hand',
            'thumb',
            'thumbs up',
            'up',
        ],
        types: [
            '👍🏿',
            '👍🏾',
            '👍🏽',
            '👍🏼',
            '👍🏻',
        ],
    },
```
@ctkochan22 Thanks for the ping.  Yeah `-1` makes sense.   The default skin tone (yellow), picks from `code`. If we have any skintone other than the default we pick the emojis from `types` where being an array the indexing starts with 0. 

I honestly don't remember why I set `default` and not `-1`

**Comment by Puneet-here** [comment]
I had reported it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661506058979819).

**Comment by mvtglobally** [comment]
Updated

**Comment by akshayasalvi** [comment]
**Proposal**

Just changing the default skintone to -1 won't help because when we retrieve the value from Onyx, it is in string format. Here are the changes that needs to be done:

1. Change `CONST.DEFAULT_SKIN_TONE` to `-1` from `default`
2. In `src/components/EmojiPicker/getSkinToneEmojiFromIndex`, update the _.find call so that it checks the right now.

```
return _.find(Emojis.skinTones, emoji => emoji.skinTone === parseInt(skinToneIndex, 10)) || Emojis.skinTones[0];
```

But there's a catch, for a lot of existing users who haven't changed the skin tone will have `preferredEmojiSkinTone: default`. This should get handled mostly because we have ` || Emojis.skinTones[0]` in `getSkinToneEmojiFromIndex`.

**Comment by ctkochan22** [comment]
@akshayasalvi thanks for your input. I decided it would be best to fix the root issue on the server side. If we get an int value, never pass it back to onyx as a string (unless its the 'default').

**Comment by ctkochan22** [comment]
Oh this is fixed. I think we should probably change up the indexes, but not a priority. So lets leave it as is. Its fixed for now

**Comment by Puneet-here** [comment]
Hey @ctkochan22, can we reopen and assign a CM as it is eligible for the reporting, I had reported it [here](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q).

**Comment by Puneet-here** [comment]
@ctkochan22, I think we need external label to assign a CM

**Comment by ctkochan22** [comment]
@JmillsExpensify I fixed the issue, but we need a pay out for @Puneet-here

**Comment by JmillsExpensify** [comment]
@Puneet-here I've created an Upwork job here and hired you: https://www.upwork.com/jobs/~012334b946691937c5. I'll circle back on payment as soon as you accept.

**Comment by Puneet-here** [comment]
> I'll circle back on payment as soon as you accept.

 Done, I have accepted the offer.

**Comment by JmillsExpensify** [comment]
Offer/contract paid via Upwork! Closing this one out.
