### ISSUE TITLE
iOS - Workspace - App crashes when making changes to Track distance units in offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Create a workspace while offline
2. Choose Reimburse expenses
3. In the Track distance section, I change the unit from miles to km

## Expected Result:
In app, units of measure must be selectable

## Actual Result:
App crashes after changing miles to km offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS 
- Android

**Version Number:** 1.1.99 -2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/189362228-d372d1da-0775-4836-acaa-798bd74bb26e.mp4
[Bug5724572_logs_0909.log](https://github.com/Expensify/App/files/9535949/Bug5724572_logs_0909.log)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
@jasperhuangg Cold be related to your issue?

**Comment by puneetlath** [comment]
@0xaim thanks so much. We appreciate your investigation, but unfortunately, this is not something we compensate for. We recommend waiting to jump into issues until the `Help Wanted` label has been added. You can read more in our contributing guidelines here: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

Thanks!
