### ISSUE TITLE
Workspace settings - Changes saved offline are not saved when connected to the Internet

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to settings->Workspace->General settings (create a workspace if it hasn't already been created)
3. Kill the internet connections
4. Change the workspace name and save
5. Go back online

## Expected Result:
Changes made offline must be saved

## Actual Result:
Changes saved offline are not saved when connected to the Internet

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189395749-e00b3f51-93e5-49cd-bf82-85960343ed68.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I wasn't able to reproduce this on staging web. @kbecciv is this consistently reproducible by the team?

**Comment by youssef-lr** [comment]
I wasn't able to reproduce this either.

**Comment by Julesssss** [comment]
I wasn't able to reproduce on web or mWeb either. As the third person to report this I'm going to remove it as a deploy blocker and we can keep the issue open to investigate further. 

I briefly saw the old workspace name flash up when my connection was established, maybe that's a hint for why this issue occurs for some users.

**Comment by jboniface** [comment]
I was also not able to repro this on staging on web. @kbecciv please retest.

**Comment by kbecciv** [comment]
@jboniface Checking with team, will update you shortly.

**Comment by kbecciv** [comment]
@jboniface @luacmartins @youssef-lr Unable to reproduce it with build 1.1.99.4 

https://user-images.githubusercontent.com/93399543/189724150-484185f3-7be9-455d-8e74-0284e23c3eac.mp4

**Comment by jboniface** [comment]
thanks, closing!
