### ISSUE TITLE
[$1000] 2FA input automatically inserts dashes and breaks

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#10947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign out (if needed)
2. Enter an email that has 2FA enabled
3. Click Sign in
4. Enter the password
5. Click Sign in
6. Type a 2FA code
7. Click Sign in

## Expected Result:
The 2FA code shows in the input properly and you are signed in

## Actual Result:
The 2FA code includes a '-' character in the input, a loading indicator shows, and then nothing happens.

## Workaround:
Delete the code and type a new one in, then click Sign in again.

## Platform:

Where is this issue occurring?
- Web, Chrome/ MacOS
Needs testing on:
- iOS?
- Android?
- Desktop App?
- Mobile Web?

**Version Number:** v1.1.98-1
**Reproducible in staging?:** N
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663013593365679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
This is likely a good external issue.

**Comment by mallenexpensify** [comment]
Triaged for @miljakljajic , added to [RCA sheet](https://docs.google.com/spreadsheets/d/1u73RE8J1DdX3mDohV1RXgulF6_cke3N_a15Sk-UUdQo/edit#gid=0) too cuz the field wasn't showing the `-` before.

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~018fa81aa98b59f150)

**Comment by bfitzexpensify** [comment]
Unassigning as I'm heading ooo for 2 weeks. No proposals yet, due to be doubled in 2 days.

**Comment by jliexpensify** [comment]
Doubled, sorry was OOO!

**Comment by Uros787** [comment]
Managed to activate 2fa but couldnt reproduce the error
Chrome - macOS - production
Also couldn't repro on staging
Also couldn't reproduce on android or ios
https://user-images.githubusercontent.com/70144379/194878507-fa198256-8e66-4329-acb4-5968b1657534.mov

**Comment by jliexpensify** [comment]
@neil-marcellini - mind checking if this issue still exists? I'm seeing the same as @Uros787 's video.

**Comment by neil-marcellini** [comment]
Sure. I'm not able to reproduce this issue on Web, Chrome/macOS. I will close this and we can re-open if needed.

**Comment by jliexpensify** [comment]
Upworks job removed. Cheers Neil!
