### ISSUE TITLE
Web - Dragging the large green circle for zoom drags the save button text save instead of green button @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting
4. Click on any workspace > general settings > edit photo > upload photo.
5. Drag the large green button for zoom.

## Expected Result:
Should drag the green button

## Actual Result:
Should drag the green button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189779849-651c068f-f574-4016-a587-0f62feb9e13d.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661419922708289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
I was able to reproduce.

**Comment by Justicea83** [comment]
Am not able to reproduce it.

https://user-images.githubusercontent.com/26106822/190123437-58da77ed-6142-4e11-b0c8-b3e6860bed2f.mp4

**Comment by varshamb** [comment]
This is not reproducible.

**Comment by arielgreen** [comment]
Cannot reproduce.
