### ISSUE TITLE
Web - VBA - Wrong URL when connect to bank account manually page is closed @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10952]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com or new.expensify.com
2. Log in with any account
3. Click on use icon to open setting page.
4. Click on workspace > issue cards > connect bank account
5. Click on back arrow on connect account page.
6. Click on connect bank account > connect manually.
7. Click the X to close the modal
8. Observe the web URL is incorrect (i.e the workspace URL)

## Expected Result:
Should show the url r/reportId

## Actual Result:
Url is changed to workspace/workspaceId

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189783744-45a157d1-5571-4731-9167-d3bc37970b02.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661443887135869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
👋 Zany, I think this was supposed to go to `Engineering` yeah? Adding the label.

**Comment by jasperhuangg** [comment]
I can't seem to reproduce this in either staging or prod:

https://user-images.githubusercontent.com/31285285/189995973-447b4ca2-9e8b-4afd-b71e-b4076ceb770f.mov

**Comment by aneequeahmad** [comment]
@jasperhuangg Issue is reproducible in production

**Action performed:**

- Go to staging.new.expensify.com
- Log in with any account
- Click on use icon to open setting page.
- Click on workspace > issue cards > connect bank account.
- Click on back arrow on connect account page.
- Click on connect bank account > connect manually.
- Click on cross icon on connect manually page.

**Video:**


https://user-images.githubusercontent.com/36359331/190029327-49cd07bc-a13f-4161-959c-aa7d22618e66.mov

**Comment by zanyrenney** [comment]
@trjExpensify sorry ya, I added the wrong label! thank you.

**Comment by trjExpensify** [comment]
Yeah, this isn't consistent, but it's reproducible. It's something to do with if you close the modal after being on a settings page first, as opposed to coming from a chat report I think. 

1. Go to staging.new.expensify.com
2. Log in with any account
3. **Click into a chat report in your LHN**
4. Click on use icon to open setting page.
5. Click on workspace > connect bank account.
6. Click on connect manually 
7. Click the `X` to close the modal 
8. Observe the web URL is correct (i.e the chat report) 


Versus 

1. Go to staging.new.expensify.com
2. Log in with any account
3. Click on use icon to open setting page.
4. **Click on workspace > issue cards > connect bank account**
5. Click on back arrow on connect account page.
6. Click on connect bank account > connect manually.
7. Click the `X` to close the modal 
8. Observe the web URL is incorrect (i.e the workspace URL)

That's how I was able to reproduce it. Reopening.

**Comment by jasperhuangg** [comment]
Got it, so it wasn't that I opened it from a chat report, it was actually that I missed the step to click "back" first before entering the connect account page again and clicking close.

This is definitely a good candidate for an external contributor, gonna mark as `External`

**Comment by jasperhuangg** [comment]
Ahh I think my wifi connection was spotty so the `External` label didn't get applied when I clicked it ooops

**Comment by michaelhaxhiu** [comment]
I'm largely in agreement @parasharrajat. 

>The real issue is with the nested level of RHN modals. This GH is just talking about different pages.

Do we have a parent issue to track this? If not yet, it would be helpful to create one and link these issues there, then close the individual GHs.

**Comment by jasperhuangg** [comment]
I can create one! Are this issue and https://github.com/Expensify/App/issues/10939 the only two places that it's happening?

**Comment by jasperhuangg** [comment]
https://github.com/Expensify/App/issues/11111 @parasharrajat

**Comment by michaelhaxhiu** [comment]
Baller, thanks @jasperhuangg!

**Comment by jasperhuangg** [comment]
@michaelhaxhiu sounds good!

**Comment by aneequeahmad** [comment]
@jasperhuangg This has also been fixed and the reporting compensation is pending.

**Comment by aneequeahmad** [comment]
Also another `broken URL` issue https://github.com/Expensify/App/issues/10887

These are the only 2 issues left for reporting bonus payment.

**Comment by jasperhuangg** [comment]
@aneequeahmad I reached out to @sonialiap to get that sorted for you, thanks for making me aware.

**Comment by jasperhuangg** [comment]
> @jasperhuangg This has also been fixed and the reporting compensation is pending.

@michaelhaxhiu was this issue created before we removed reporting bonuses?

**Comment by jasperhuangg** [comment]
Feel free to close out the issue if payment was issued/no next steps need to be taken.

**Comment by aneequeahmad** [comment]
@jasperhuangg I can see that @michaelhaxhiu account is deactivated in Slack #expensify open source. I think you can assign this to someone else for issuing payment. Thanks

**Comment by jasperhuangg** [comment]
@adelekennedy Let's pay out $250 to @aneequeahmad as the reporting bonus for this issue (it was created when reporting bonuses still existed).

**Comment by adelekennedy** [comment]
@aneequeahmad sent offer on Upwork!

**Comment by adelekennedy** [comment]
Payment made! @jasperhuangg anything else that needs to be done for this issue or can we close it out?

**Comment by jasperhuangg** [comment]
I think we're good here, thanks for sorting that out!
