### ISSUE TITLE
[$1000] [HOLD for payment 2022-12-02] [N7 Account Settings] Convert `LOGIN_LIST` from Array to Object

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#10960]
Tracking issue: https://github.com/Expensify/Expensify/issues/182122

# Problem

Currently we store logins in Onyx as an Array of logins.

As outlined in the [N7 Account Settings doc](https://docs.google.com/document/d/17akqrbC-w8FqEoDLvcLmrX6iw4uaVrT_xlwAl-IhEzE/edit#), in the near future we'll need to be able to associate errors / loading states with individual logins (in the future we'll call them "contact methods"). If we keep this data as an array, we aren't able to update individual logins so we'll have to re-set the entire login list any time we add error messages, remove them, set loading states, etc.

# Solution

Update the logins in `LOGIN_LIST` to be an object / dictionary of logins. The keys will be the login (`partnerUserID`) and the values will be the full login details as they exist today. This will make it very easy to use Onyx to add / modify / remove keys to individual logins.

~We'll need to write a migration for this so that any existing user with an array loginList will be converted to an object.~
- Note: We agreed no migration is needed for this

Additionally, we'll have to look into our backend to update the format of any API commands returning loginList data. Examples:
- https://github.com/Expensify/Web-Expensify/blob/d5ff4d26afeeb8a91eb985ccf2bd7485eeb689b9/lib/AppInit.php#L202-L207
- https://github.com/Expensify/Web-Expensify/blob/d5ff4d26afeeb8a91eb985ccf2bd7485eeb689b9/lib/UserAPI.php#L1517-L1521
## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~011f9400b21a7267d9
- Upwork Job ID: 1600173411787558912

**Comment by Beamanator** [comment]
Possibly don't need migration, can just tell everyone to log out / log in 🤷

**Comment by Beamanator** [comment]
In doc comments we agreed this isn't needed, so closing

**Comment by Beamanator** [comment]
Reopening b/c this is needed, just no migration is necessary

**Comment by Beamanator** [comment]
Taking off hold b/c we want to start working on N7 Account Settings again, at least the profile pages

**Comment by Beamanator** [comment]
PRs in review:
- https://github.com/Expensify/App/pull/10959
- https://github.com/Expensify/Web-Expensify/pull/35282
- One more to clean up App (since we shouldn't have to handle arrays coming back from server after ^

**Comment by Beamanator** [comment]
2 PRs to go!

**Comment by Beamanator** [comment]
The Web-E PR just got merged, so now only 1 left - cleaning up App!

**Comment by Beamanator** [comment]
Last PR is up! https://github.com/Expensify/App/pull/12919

**Comment by Beamanator** [comment]
Adding Bug to get a bug-zero assigned to help pay out @thesahindia who tested the PR!

**Comment by alexpensify** [comment]
@Beamanator - is this project complete? I see one PR went live about a week ago. Are we good to move to payment, then close out this GH?

**Comment by Beamanator** [comment]
Yeah agree this is good to go 👍

**Comment by thesahindia** [comment]
Accepted, thanks @alexpensify

**Comment by alexpensify** [comment]
Payment has been sent via Upwork
