### ISSUE TITLE
Desktop/ Web- Production server is displayed even if the staging server is enabled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #10935 
## Action Performed:
1. Open app on web
2. Go to Settings -> Preference
3. Use staging server is toggled ON
4. Open dev tool
5. Go to Network tab.
6. Focus on app and send some message.

## Expected Result:
Verify that the request in Fetch/XHR is of staging server https://staging.expensify.com/

## Actual Result:
The request shows always production server

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/189965104-49b6c59b-2564-47e5-932d-280b22a3e69b.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
Hmm, I don't see how to enable the staging server on web. Is this an error in the issue description @kavimuru?

**Comment by francoisl** [comment]
Hmm confused by this one, https://github.com/Expensify/App/pull/10690 and https://github.com/Expensify/App/pull/10935 are the same PR, and the former was reverted in https://github.com/Expensify/App/pull/10920

https://github.com/Expensify/App/pull/10935 should be included in 1.2.0.0, but somehow it doesn't seem to be. Still looking.

**Comment by mountiny** [comment]
This is a problem with our GH CD/CI  which we encountered already once before. Discussing in [Slack here](https://expensify.slack.com/archives/C07J32337/p1663114901154789)

**Comment by francoisl** [comment]
This should be fixed now, waiting for Applause to finish testing https://github.com/Expensify/App/pull/10935 again.

**Comment by mountiny** [comment]
It was checked off by Applause, closing https://github.com/Expensify/App/issues/10958#issuecomment-1248436384
