### ISSUE TITLE
Web - Attachment -Link copied from image doesn´t open.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat and sent any image attachment.
2. Copy image URL and paste in chat using NewDOt chat copy feature.
3. Click in generated link.

## Expected Result:
Image should open after link URL is clicked.

## Actual Result:
No action occurs after link is clicked after paste URL.
If user open the image and copy the link using the OS copy feature the image is correctly opened in a new browser tab.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190034145-b8c55035-b58a-40d8-9cc0-29d4aa7f4678.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@chiragsalian I think the `Copy link` feature is supposed to link to the specific message in the chat and not to the actual image file, is that correct?

**Comment by luacmartins** [comment]
Bumping @chiragsalian - https://github.com/Expensify/App/issues/10983#issuecomment-1246902162

**Comment by luacmartins** [comment]
No updates

**Comment by chiragsalian** [comment]
Ah copy link is supposed to work for both messages and images. But yes the feature won't do anything right now since comment linking is not live. The copy link functionality is behind a beta so only specific accounts can see and use it but it won't do anything else for now.

I would say we can close out this issue since its a feature behind a beta and the complete functionality isn't done yet.

**Comment by luacmartins** [comment]
Sounds good! Thanks for the input. Closing this issue!
