### ISSUE TITLE
[$250] Bug: New Dot Chronos is sending multiples of the same message

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#10985]
Platform - version: Desktop, Version 1.1.96-5 (1.1.96-5)

Action Performed (reproducible steps): no action taken on my part, Chronos just automatically sends a good morning message daily (I think around 8am), but now sends multiple of the same

Expected Result: Chronos posts once saying good morning and letting me know all the gossip about whose ooo

Actual Result: Chronos is needy and posts it several times (6-8) one after the other

Notes/Photos/Videos:
![image](https://user-images.githubusercontent.com/38236554/190073040-7c52673a-44ca-4d0b-b37e-eb4c5b4d2320.png)

Logs - JS/Android/iOS (if applicable): May not be useful (or the right thing), but: reportID: 746e95fe0d0adc39-SAN
![image](https://user-images.githubusercontent.com/38236554/190073062-94f11501-463b-4b79-a43a-74fd9bfb8a36.png)

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~01b79fcc59dd4550bd)

**Comment by Santhosh-Sellavel** [comment]
This could be internal @luacmartins, external contributors will not have Chronos access. 

Also doesn't look like changes might be on the client side.

**Comment by luacmartins** [comment]
@Santhosh-Sellavel correct, this should be internal!

**Comment by luacmartins** [comment]
Created the [issue](https://github.com/Expensify/Expensify/issues/228432) in the E/E repo. Closing this one.
