### ISSUE TITLE
Bug - jpeg images dont have their height and width set properly in report action onyx

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#10996]
Report by - [luciobertinchavez@gmail.com](mailto:luciobertinchavez@gmail.com)

## Action Performed:
1. In newDot attempt to upload a "jpeg" attachment to someone
2. Check its onyx reportAction data.

## Expected Result:
The onyx reportAction originalMessage.html should contain the proper image height and width for `data-expensify-width` & `data-expensify-height`. Eg:
```
<img src=\"https://www.expensify.com.dev/chat-attachments/1542015177849258349/w_f845f61af969ae700e06cad9f4ad29008a233d45.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com.dev/chat-attachments/1542015177849258349/w_f845f61af969ae700e06cad9f4ad29008a233d45.jpg\" data-name=\"pic1.jpeg\" data-expensify-width=\"1000\" data-expensify-height=\"667\" />
```

## Actual Result:
The onyx reportAction originalMessage.html contains 0 for image height and width. Eg:
```
<img src=\"https://www.expensify.com.dev/chat-attachments/7138062052586745215/w_3a14ad0a30c5c2868381d48cf6ea71c217794cea.jpg.1024.jpg\" data-expensify-source=\"https://www.expensify.com.dev/chat-attachments/7138062052586745215/w_3a14ad0a30c5c2868381d48cf6ea71c217794cea.jpg\" data-name=\"pic1.jpeg\" data-expensify-width=\"0\" data-expensify-height=\"0\" />
```
This can lead to janky upload animations since the loader doesn't have the proper dimensions

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** luciobertinchavez@gmail.com
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663031938075239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
@mallenexpensify, how do we handle payment for this bug? Its a valid bug. Its not external and I'll be fixing it internally soon on this one.

**Comment by mallenexpensify** [comment]
I assigned myself to compensate the reporter once done.  Normally there'd be a few other/different steps to assign a CM, not worth fussing with now

**Comment by chiragsalian** [comment]
The code for this went live a while back. @mallenexpensify, will you be able to compensate the reporter and then close out the issue?

**Comment by mallenexpensify** [comment]
@LucioChavezFuentes please accept the job and confirm in a comment here once you have. https://www.upwork.com/jobs/~01dc47b2a6551f4d1b
Can you also include your GH handle in your Slack profile so that QA can add it to any issues you report? Thx

**Comment by LucioChavezFuentes** [comment]
Thank you @mallenexpensify, just have one question. What should I put on the following Upwork proposal fields?:
-Cover Letter
-IMPORTANT: Have you submitted your proposal in the GitHub issue? Note: you will *not* be considered for hire until you have done this.
- What date do you estimate to be able to submit a pull request containing the fix for this issue?

**Comment by mallenexpensify** [comment]
@LucioChavezFuentes , it doesn't matter what you put in, Github is the source of truth for us, we only use Upwork for payments.

**Comment by LucioChavezFuentes** [comment]
Thank you! I accepted the offer on Upwork.

**Comment by mallenexpensify** [comment]
Paid, thanks for the help @LucioChavezFuentes
