### ISSUE TITLE
All workspace member are showing with green avatar - Reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11019]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app and login
2. Go to settings
3. Go to workspace
4. Go to Manage members
5. Click on invite

## Expected Result:
Avatars should load 

## Actual Result:
All avatars displayed green 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1183" alt="Screen Shot 2022-09-15 at 4 26 11 PM" src="https://user-images.githubusercontent.com/43995119/190502141-cd77d996-98a1-4a0e-af86-5e38c1da0229.png">
<img width="1190" alt="Screen Shot 2022-09-15 at 4 24 18 PM" src="https://user-images.githubusercontent.com/43995119/190502142-321d7191-435d-4475-a206-8ef1b2231fd3.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663257422571899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
I was able to reproduce this on staging only. Looking into it.

**Comment by thesahindia** [comment]
Ahh, sorry for the late comment but this one also needs settlement.

cc: @mallenexpensify

**Comment by mallenexpensify** [comment]
Thanks @thesahindia , we're in the process of reviewing and updating our process for jobs reported by contributors and fixed internally.  Please keep your 👀 peeled for any, like this, that you run across.  Please accept the job 
https://www.upwork.com/jobs/~019a567577f0eaf2c4 and comment on this issue and I'll pay

**Comment by thesahindia** [comment]
> Thanks @thesahindia , we're in the process of reviewing and updating our process for jobs reported by contributors and fixed internally. Please keep your 👀 peeled for any, like this, that you run across. 

Yeah, for sure.

> Please accept the job https://www.upwork.com/jobs/~019a567577f0eaf2c4 and comment on this issue and I'll pay

Accepted, Thanks.

**Comment by thesahindia** [comment]
@mallenexpensify bump ^^

**Comment by mallenexpensify** [comment]
Paid @thesahindia !  Thanks
