### ISSUE TITLE
No emails are shown on the member Invite page - Reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open settings page.
2. Select any workspace(create new if doesn't exists).
3. Click Members from the menu items.
4. Press invite button.

## Expected Result:
There should be emails/description under the contacts name on the Invite member page

## Actual Result:
There is not description available on the contacts where we used to show emails (mostly)

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image - 2022-09-15T165004 080](https://user-images.githubusercontent.com/43995119/190506331-c1bb97e0-acb9-48df-a2a7-d61ce5f52139.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663273697996389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Ah, good question. I'm not super familiar with the process, @mallenexpensify would you be able to assist please?

**Comment by mallenexpensify** [comment]
@parasharrajat can you apply please and confirm here once you have?
https://www.upwork.com/jobs/~01c28bfad13126d387

**Comment by mallenexpensify** [comment]
Paid! Thanks @parasharrajat

**Comment by mallenexpensify** [comment]
Hired, let me know when you've accepted and I'll pay Rajat
