### ISSUE TITLE
[Hold for Payment 23 Sept] Attachment is displayed blank after uploading Issue reported by: @varshamb

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Select any user and click on plus button
4. Select Add Attachment
5. Pick any attachment and click Send

## Expected Result:
Attachment is not displayed blank after uploading

## Actual Result:
Attachment is displayed blank after uploading

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190539182-9be87bfe-4155-4a4a-a8b0-931402cec1c4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause- Internal Team/@varshamb 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663232936099099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
Yesterday this was reported by me on Slack.

https://expensify.slack.com/archives/C01GTK53T8Q/p1663232936099099

**Comment by mountiny** [comment]
Adding External label @laurenreidexpensify to make sure we will pay out @varshamb for reporting this regression.

**Comment by mountiny** [comment]
Cannot reproduce locally but getting following errors in console
<img width="1119" alt="Screenshot 2022-09-16 at 11 05 37" src="https://user-images.githubusercontent.com/36083550/190615020-94aa9a97-aef7-4f92-81a7-59ce6d1bba9f.png">

**Comment by mountiny** [comment]
Works in production, this must be related to the staging api servers and some settings we need to update there as well to be able to process images.

**Comment by laurenreidexpensify** [comment]
Job on upwork for payment https://www.upwork.com/ab/applicants/1570720016829329408/job-details

**Comment by mountiny** [comment]
Reopening this for now to wait until the server changes are deployed and we can confirm the change worked

**Comment by mountiny** [comment]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/36083550/190646543-911f19f9-7138-4936-b548-21b21039bd53.png">

Confirmed in staging this is fixed!

**Comment by varshamb** [comment]
@laurenreidexpensify Can you please reopen the issue and send the correct upworks link. Thank you.

**Comment by laurenreidexpensify** [comment]
@varshamb invited to job!

**Comment by mountiny** [comment]
@laurenreidexpensify I think since this was reported as valid bug - deploy blocker even - there does not need to be a regression period included for the payment. I think we can pay @varshamb as soon as you get a chance.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
Issue not reproducible anymore, removing the DeployBlocker label

**Comment by laurenreidexpensify** [comment]
@varshamb The hire offer is pending in Upwork - I can issue payment as soon as you accept :) Thanks!

**Comment by varshamb** [comment]
@laurenreidexpensify Applied on 16Sep, Please resend hire offer if needed.

**Comment by laurenreidexpensify** [comment]
@varshamb oh weird, it's showing on my side on Upwork that you still need to accept the offer. Can you take a look and doublecheck nothing is pending there on your account? Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by varshamb** [comment]
@laurenreidexpensify  Accepted the offer.

**Comment by laurenreidexpensify** [comment]
Payment issued Thanks!
