### ISSUE TITLE
Migrate setNativeProps to state in OptionsSelector

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#11053]
Coming from https://github.com/Expensify/App/issues/8503, enabling Fabric requires us to migrate off setNativeProps. We should move usages of setNativeProps to state in OptionsSelector

**Comment by roryabraham** [comment]
Can't promise anything, but I'm going try looking into this a bit

**Comment by luacmartins** [comment]
>The following reasons make me think that it's a purely performance related issue. 

I think this is correct. There's a noticeable delay between user input and state update, which was not present with `setNativeProps` since that updated the component directly. There's some discussion in [this issue](https://github.com/facebook/react-native/issues/34391#issuecomment-1249693384), but no conclusion yet. It seems like this performance regression is still experienced with Fabric enabled.

>we'll lose the feature that selects the search text when a option is selected

I'm fine with this. FWIW we already have inconsistent behavior with the Split Bill page for example, where selecting a participant completely clears the input. 

https://user-images.githubusercontent.com/22219519/194401063-973c0ffc-6fef-436e-bbf1-6494243f6d54.mov

**Comment by roryabraham** [comment]
> we'll lose the feature that selects the search text when a option is selected

Agree that this is an acceptable cost.

> It seems like this performance regression is still experienced with Fabric enabled.

Agree, though it might be possible that this performance regression could be further alleviated by using `startTransition` instead of `setState` (only possible after Fabric upgrade)

**Comment by roryabraham** [comment]
I don't feel great about losing that feature, let's be sure to create a follow-up issue to try re-implementing after Fabric is enabled

**Comment by hannojg** [comment]
Hey, just want to add to the discussion that TextInputs have a undocumented function called `setSelection` (I am not sure, but for web it might be `setSelectionRange`), so you can call e.g.:

```js
this.textInputRef.setSelection(start, end)
```

This way we can avoid having controlled inputs which are bad for performance + preserve the highlight functionality.

(note: sorry if I am writing out of context, was just quickly glimpsing and thought this information might adds value)

**Comment by hannojg** [comment]
Yes, i can give it a shot, although I am heavily focused on mobile, but will def try!

**Comment by hannojg** [comment]
Sorry @rushatgabhane but where is the PR where you started working on it? Would like to continue from there

**Comment by stitesExpensify** [comment]
Not sure why this isn't closed, but we can close it! https://github.com/Expensify/App/issues/8503#issuecomment-1281309960
