### ISSUE TITLE
Details - Closed account displayed with infinite spinner on Details Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Click on the green + button
4. Click on the "New group" option
5. Select a pair of users from the search list. The account of one of the users must be closed.
6. Open this group chat.
7. Open Details page

## Expected Result:
A deleted user should be displayed as all users

## Actual Result:
The closed account is not displayed in the group details

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** andreylazutkinutest+123@gmail.com/w323052760Qwerty

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190660598-81798db1-0994-49eb-ba19-ae71d0a1e79e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aneequeahmad** [comment]
is this issue the same as i reported [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661462019061489) ?

cc: @kbecciv

**Comment by tylerkaraszewski** [comment]
staging.new.expensifail.com isn't a thing, this needs to be done at staging.new.expensify.com.

The reproductino steps are fairly complex, see the video for how this is done.

This looks like a front end video where something is likely not checked for `null`. I will mark it as internal.

**Comment by MitchExpensify** [comment]
I am unable to reproduce this, the closed account shows ins in Details:
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/36425901/196809969-541439df-9f6c-4312-8041-84f223b04057.png">
