### ISSUE TITLE
[$250] Need a C+ review for https://github.com/Expensify/App/pull/10452

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#11067]
Creating this issue to trigger auto assigner for a review on https://github.com/Expensify/App/pull/10452

**Comment by iwiznia** [comment]
Ohhh, a CM needs to create an issue. Thought the assigner was not working properly, sorry about that double assignment.

**Comment by jliexpensify** [comment]
Posted. 

Internal - https://www.upwork.com/ab/applicants/1570937596735205376/job-details
External - https://www.upwork.com/jobs/~010b9ddf39e530428a

**Comment by jliexpensify** [comment]
Hired @Santhosh-Sellavel

**Comment by pecanoro** [comment]
@iwiznia I am not completely sure what we need to do here. I got assigned but I have no clue if you are looking for a CME or C+ to review the PR.

**Comment by iwiznia** [comment]
Sorry, that was the auto assigner, you are not needed here @pecanoro

**Comment by Santhosh-Sellavel** [comment]
@iwiznia @jliexpensify 

Can we keep this open until payment is issued?

**Comment by jliexpensify** [comment]
According to @luacmartins - it looks like there wasn't actually an issue in https://github.com/Expensify/App/issues/11503? So we're not reducing @Santhosh-Sellavel 's pay here right?

**Comment by luacmartins** [comment]
@jliexpensify that's correct!

**Comment by jliexpensify** [comment]
Not overdue.

**Comment by Santhosh-Sellavel** [comment]
@jliexpensify This is due for payment, and deployed to production 12 days ago!

**Comment by jliexpensify** [comment]
@Santhosh-Sellavel apologies, just looked at the other issue. Paying now.
