### ISSUE TITLE
Android - Manage members - some time Warning message doesn't show or is gone in a less than second @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to settings > workspace > manage member
4. Tap on your name multiple time
5. Check error message

## Expected Result:
It should show warning message

## Actual Result:
Some time Warning message doesn't show or is gone in a less than second

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190922912-2719e2f4-a977-4be8-abac-9367e2104818.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @gadhiyamanan

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1661510149113449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Tested on Samsung on v1.2.0-8 and was not an issue.

**Comment by gadhiyamanan** [comment]
@RachCHopkins still able to reproduce on v1.2.0-8 https://user-images.githubusercontent.com/54790231/190960051-fddadebb-8a3c-405e-b7df-a31d7d122c7c.mp4

**Comment by arosiclair** [comment]
@kbecciv this looks to be an Android only issue however all platforms are listed in the Platforms section in the OP.

On Android 1.2.0-0 the growl notifications for this seem to be largely working without issue. They do look to be throttled somewhat if you attempt to spam presses on an admin, but I don't see how that is a real use case we want to support. I'm seeing pretty much 0 ROI on attempting to fix this so I'll close this out as not an issue.
