### ISSUE TITLE
Web - Chat -When you change the language on the computer, the keyboard shortcut does not work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2.Log in with any account
3. Change the language on your computer
4. Press Ctrl+SHIFT+K and the New Group Page should open.

## Expected Result:
The New Group Page should open.

## Actual Result:
The New Group Page is not opening.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190744310-eee0a96d-3da0-4543-9a72-3b7a552aae4b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment]
From the video it doesn't look like you're pressing Ctrl+SHIFT+K after switching the language, as the keyboard keys are not placed in the same positions. So, closing.
