### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Spacing at the top in skeleton ui at iPad - Reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Search icon
2. Navigate to a chat
3. Look at the skeleton ui

## Expected Result:
There shouldn't be extra space

## Actual Result:
There is extra space at the top

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![IMG_0055 (1)](https://user-images.githubusercontent.com/43995119/190952087-17c0d4bb-c15d-4353-aa46-3990fbc7442b.PNG)
![IMG_0057](https://user-images.githubusercontent.com/43995119/190952088-6dc3e53b-1e4e-4eab-96e2-1a4d099555b5.PNG)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661707814174879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment]
I think this can be external.

**Comment by stephanieelliott** [comment]
Posted to Upwork: https://www.upwork.com/jobs/~01ee96f86077f15321

**Comment by marcochavezf** [comment]
Hi @rushatgabhane, what do you think about this [proposal](https://github.com/Expensify/App/issues/11088#issuecomment-1251412257)?

**Comment by marcochavezf** [comment]
Thanks for the review @rushatgabhane, I'm going to change the priority to Weekly and wait for a better proposal

**Comment by stephanieelliott** [comment]
@marcochavezf have you checked out the updated propsal in https://github.com/Expensify/App/issues/11088#issuecomment-1261309929?

**Comment by marcochavezf** [comment]
Ah sorry, I was a little confused with the last review I thought it was a no-go 😄 I read again the conversation and the proposal LGTM, my apologies.

Thanks @rushatgabhane for the review, assigning @aimane-chnaif 🚀

**Comment by stephanieelliott** [comment]
Hey @aimane-chnaif @rushatgabhane please grab the job on Upwork when you have a chance! https://www.upwork.com/jobs/~01ee96f86077f15321

**Comment by stephanieelliott** [comment]
C and C+ have been paid up!  Just waiting on @thesahindia to accept the job on Upwork so we can pay the reporting bonus to close this out.

**Comment by marcochavezf** [comment]
Hi @stephanieelliott, would be ok to close this out?

**Comment by stephanieelliott** [comment]
Oh yep, this was paid! Closing
