### ISSUE TITLE
[$4000] iPad (safari) - Change password, new chat & new group page the field gets focused but the keyboard doesn't open - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Go to settings > security > change password

## Expected Result:
The keyboard should open

## Actual Result:
The keyboard doesn't open

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Mobile Web iPad (safari)

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190952432-d072befe-c01d-404e-92fd-b6c71ff230c9.mov

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661709051676959 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I can replicate the behavior 👍

**Comment by JmillsExpensify** [comment]
Also replicated the behavior. It's reproducible on Safari across all iOS platforms. I've created a job in Upwork here: https://www.upwork.com/jobs/~01f0a06e71a7da3f54. We're open for proposals!

**Comment by JmillsExpensify** [comment]
Removing the Exported label from this issue in light of a recent process change.

**Comment by JmillsExpensify** [comment]
Still open for proposals!

**Comment by JmillsExpensify** [comment]
Still open for proposals. Doubling this issue to try and get more proposals.

**Comment by JmillsExpensify** [comment]
Actually you know what. I can't reproduce this anymore on mWeb iPad. I'm going to try again and see if I still can't reproduce tomorrow, at which point I'll close.

**Comment by jeet-dhandha** [comment]
Tested this not Reproducible.

**Comment by thesahindia** [comment]
It's still reproducible for me.

**Comment by JmillsExpensify** [comment]
Woah, yes, I can reproduce this now. That said, I think this is a symptom of our larger keyboard issue and should be put on hold while we work through that initiative first. Tracking issue is [here](https://github.com/Expensify/App/issues/10273). Sound good?

**Comment by JmillsExpensify** [comment]
That's a good point. I was specifically thinking of this mention in the problem statement.

> For example, we have some screens where we use timeouts to wait for navigation transitions to finish before opening the keyboard

But I think you're right, being sluggish and opening slowly is different than not opening (on Ipad mWeb) at all.

**Comment by JmillsExpensify** [comment]
We're open for proposals again!

**Comment by JmillsExpensify** [comment]
Ah yes, all good! I like the idea of trying to verify one way or another via proposals.

**Comment by JmillsExpensify** [comment]
Doubling the price in the hopes of getting more proposals.

**Comment by JmillsExpensify** [comment]
Alright, doubling the price again. We still lack proposals.

**Comment by sketchydroide** [comment]
closing as duplicated of https://github.com/Expensify/App/issues/10414 more details [here](https://github.com/Expensify/App/pull/11794#issuecomment-1280776271) and [here](https://github.com/Expensify/App/issues/10414#issuecomment-1294953650)
