### ISSUE TITLE
[$250] Attachment - Sender can't preview .tiff file while sending @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1, Open Website/App NewDot
2. Go to chat.
3. Send a .tiff attachment.

## Expected Result:
Attachment should open in preview while sending.

## Actual Result:
Attachment isn't opening in preview.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/190924403-cc71c750-0e30-4880-90f7-094e02adc571.mov

**Upwork job URL:** https://www.upwork.com/jobs/~01a3c765f8e54550bc

**Issue reported by:** @Tushu17

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661515549359619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Triaged - replicated exactly in my test account on new dot web. 
![image](https://user-images.githubusercontent.com/32854888/190945469-82cdcdca-9455-483c-8ee4-8f4f90eeb620.png)

**Comment by kakajann** [comment]
It works on iOS. **Platform** in the description should be updated
<img width="618" alt="Screen Shot 2022-09-19 at 9 49 45 AM" src="https://user-images.githubusercontent.com/11542415/190951610-68d99862-564e-4a74-8e41-c2244d8da685.png">

**Comment by dhairyasenjaliya** [comment]
@michaelhaxhiu no one assigned here

**Comment by michaelhaxhiu** [comment]
https://www.upwork.com/jobs/~01a3c765f8e54550bc

@dhairyasenjaliya sorry, I was unassigned! Job exported to upwork and C+ is now assigned to review your proposal

**Comment by michaelhaxhiu** [comment]
wait.... auto assignment logic didn't work, where is the C+ 🤔

**Comment by stitesExpensify** [comment]
Agreed. Should we just close this out then?
