### ISSUE TITLE
Clicking on concierge@expensify.com link opens the mail app instead of redirecting to the DM.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11097]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Check Monthly statement 
2. Navigate to questions 
3. click on concierge@expensify.com link

## Expected Result:
It should redirect user to DM 

## Actual Result:
Clicking on concierge@expensify.com link opens the mail app instead of redirecting to the DM.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** need repro 
**Reproducible in production?:** Need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="370" alt="image - 2022-09-19T013849 745" src="https://user-images.githubusercontent.com/43995119/190955445-ec2373e3-189a-46b5-baf9-85573d0e92ff.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662115983865449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This is since it's a webview from OldDot.  We'll have to update the handling so that clicking on that email actually redirects to the chat instead

**Comment by thienlnam** [comment]
Will have to be internal since this is on beta currently

**Comment by thienlnam** [comment]
Have not looked into this yet, low priority since we're still in beta

**Comment by thienlnam** [comment]
I have PRs in review

**Comment by thienlnam** [comment]
Re-opening this, the app PR was reverted and needs to be added again

**Comment by thienlnam** [comment]
These are internal PRs / internal reporter - no need to pay out anyone here
