### ISSUE TITLE
[HOLD #11768] Wrong URL when new chat is selected from new chat list - Reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open web app and see the opened chat and its URL.
2. Click on + icon in LHN > new chat.
3. Select any chat in the New Chat list.
4. See the URL and opened chat.
5. Refresh the page. 

## Expected Result:
Chat URL should be of new chat opened.

## Actual Result:
Chat URL is of old chat and not of new chat opened.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
 

https://user-images.githubusercontent.com/43995119/190953346-3053daa4-1cca-44fc-8bc8-c0e9e5c07b1c.mov
 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661801189415899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Oh interesting! Sending to eng for a second opinion on getting this job in Upwork - seems worth it

**Comment by pecanoro** [comment]
I reproduced this, the problem here is that when you create a new chat, the URL does not get updated and the one with the previous chat stays.

**Comment by Santhosh-Sellavel** [comment]
@arielgreen or @NikkiWines 

Busy with other items, also limited availability for next couple weeks So un-assigning this one. Can you reassign this to another C+ by reapplying label. 

Thanks!

**Comment by arielgreen** [comment]
@parasharrajat can you review https://github.com/Expensify/App/issues/11092#issuecomment-1257032680 please?

**Comment by arielgreen** [comment]
Still on hold cc @puneetlath correct?

**Comment by puneetlath** [comment]
Yes, still on hold. Feel free to assign any navigation issues over to me and @JmillsExpensify.

**Comment by JmillsExpensify** [comment]
Yes, thanks! Updated the [Hold] for clarity and also linked this issue to the main tracking initiative.

**Comment by JmillsExpensify** [comment]
Check the linked issue for the latest.

**Comment by JmillsExpensify** [comment]
Still holding.

**Comment by JmillsExpensify** [comment]
Still held as we go through the design process.

**Comment by JmillsExpensify** [comment]
Still held on navigation re-write.

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Coming off hold very soon!

**Comment by JmillsExpensify** [comment]
Working on testing this week.

**Comment by JmillsExpensify** [comment]
Still trying to make time. Low priority.

**Comment by JmillsExpensify** [comment]
@aneequeahmad Same here. Please retest your reproduction steps above and confirm that you receive the expected result. At that point we can confirm that it's fixed and pay you for reporting.

**Comment by JmillsExpensify** [comment]
Same as above.

**Comment by aneequeahmad** [comment]
@JmillsExpensify Tested the reproduction steps. Results are as expected. Video is attached for verification

https://github.com/Expensify/App/assets/36359331/b04b0f63-af50-449f-aacd-5b7d8cd1d97a

**Comment by aneequeahmad** [comment]
@JmillsExpensify please verify the video attached above and lets close this issue. Thanks

**Comment by JmillsExpensify** [comment]
Thanks for closing the loop. I've sent the offer, please prioritize accepting it so we can get this closed out.

**Comment by aneequeahmad** [comment]
@JmillsExpensify accepted the offer. Thanks

**Comment by JmillsExpensify** [comment]
Thanks, all paid out.
