### ISSUE TITLE
[HOLD for payment 2022-10-24] [$250] Cursor disappear if we choose the same currency from the currency selector - reported by @daraksha-dk

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat > Send Money
2. Choose the currency which is already selected

## Expected Result:
The focus should not disappear

## Actual Result:
The focus gets disappear

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.1-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190954428-6067637e-ad68-405b-8880-195716487c87.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661875896119079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
### PROPOSAL
This issue can be fixed like the `TextInput` focused in AddSecondaryLoginPage.js

[App/src/pages/settings/AddSecondaryLoginPage.js](https://github.com/Expensify/App/blob/3e410ef9deebf3ee700f0f98d30989abf1a859e8/src/pages/settings/AddSecondaryLoginPage.js#L95-L101)

Lines 95 to 101 in [3e410ef](https://github.com/Expensify/App/commit/3e410ef9deebf3ee700f0f98d30989abf1a859e8)

 <ScreenWrapper onTransitionEnd={() => { 
     if (!this.phoneNumberInputRef) { 
         return; 
     } 
  
     this.phoneNumberInputRef.focus(); 
 }}

**Comment by sobitneupane** [comment]
**Proposal**
When component updates without change in currency code, it is being returned without focusing text input.
https://github.com/Expensify/App/blob/3335b188ce86ba413f4098f6905926e737870ce3/src/pages/iou/steps/IOUAmountPage.js#L74-L80
```diff
    componentDidUpdate(prevProps) {
-        if (this.props.iou.selectedCurrencyCode === prevProps.iou.selectedCurrencyCode) {
-            return;
-        }
-
        this.focusTextInput();
    }
```

**Comment by sobitneupane** [comment]
@davidcardoza No one is assigned for this isssue.

**Comment by NikkiWines** [comment]
The cursor re-appears if you click in the area once more, so this is a really small and unobtrusive bug but looks good for `External`. Applying the label 👍

**Comment by NicMendonca** [comment]
Job posting: https://www.upwork.com/jobs/~0188e61c5a9ca99f39

**Comment by onliwer** [comment]
Proposal

This issue is caused on the IOUAmountPage, the componentDidUpdate function returns before the textInput is focused.
My proposal is to move the focusTextInput to the beginning of the componentDidUpdate function, so it focuses the textInput even when the same currencyCode is selected.

https://github.com/Expensify/App/blob/3335b188ce86ba413f4098f6905926e737870ce3/src/pages/iou/steps/IOUAmountPage.js#L74-L80

```
    componentDidUpdate(prevProps) {
        this.focusTextInput();

        if (this.props.iou.selectedCurrencyCode === prevProps.iou.selectedCurrencyCode) {
            return;
        }
    }
```

And the result:
[Screencast from 19-09-22 16:31:07.webm](https://user-images.githubusercontent.com/11609254/191057170-1b57c847-415a-459d-bcc8-27507348d539.webm)

**Comment by sobitneupane** [comment]
Here is my proposal: https://github.com/Expensify/App/issues/11095#issuecomment-1250643247

**Comment by Ollyws** [comment]
Proposal

This issue is caused on the IOUAmountPage, the componentDidUpdate function returns before the textInput is focused.
My proposal is to remove the if statement as it seems redundant in this case.

https://github.com/Expensify/App/blob/3335b188ce86ba413f4098f6905926e737870ce3/src/pages/iou/steps/IOUAmountPage.js#L74-L80

Solution:
```
    componentDidUpdate(prevProps) {
        this.focusTextInput();
    }
```
And the result:
[Screencast from 19-09-22 16:31:07.webm](https://user-images.githubusercontent.com/11609254/191063579-4c0c6782-28f0-46ed-848c-bbcb98f0d33c.webm)

**Comment by thienlnam** [comment]
It's looking like the fix could be related to the bug reported here: https://github.com/Expensify/App/issues/10693

**Comment by sobitneupane** [comment]
This proposal solves this issue and https://github.com/Expensify/App/issues/10693.
**Proposal**
When component updates without change in currency code, it is being returned without focusing text input.
https://github.com/Expensify/App/blob/3335b188ce86ba413f4098f6905926e737870ce3/src/pages/iou/steps/IOUAmountPage.js#L74-L80
```diff
    componentDidUpdate(prevProps) {
-        if (this.props.iou.selectedCurrencyCode === prevProps.iou.selectedCurrencyCode) {
-            return;
-        }
-
-      this.focusTextInput()
+      this.textInput.focus();
    }
```

**Comment by NicMendonca** [comment]
bump @parasharrajat on these proposals ☝️

**Comment by thienlnam** [comment]
cc @parasharrajat could you please check the proposals above?

**Comment by parasharrajat** [comment]
Lol. Sorry for the delay, I wasn't working much the last few days. Reviewing it now.

**Comment by parasharrajat** [comment]
Thanks for waiting everyone. I have done my analysis. |

 @sobitneupane's proposal will fire a focus event on each state change which is not a good idea. :x: 
 @varshamb 's proposal is incomplete :x: 
 
 @aimane-chnaif good explanation but missing a few details or cases. Questions:
 1. I think autofocus will open the V-keyboard on the mobile web which we don't want for this page. 
 2. How will you access to navigation prop? 
 3. Why `focus` event? can't we listen to transitionEnd?

**Comment by parasharrajat** [comment]
Thanks. I will respond tomorrow.

**Comment by parasharrajat** [comment]
Reviewing...

**Comment by parasharrajat** [comment]
Thanks for waiting. @aimane-chnaif 's [proposal](https://github.com/Expensify/App/issues/11095#issuecomment-1251267647) looks good to me. 

cc: @thienlnam 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by thienlnam** [comment]
Wow, that proposal looks great! Thanks for also considering the performance impact and cleaning up some existing code

**Comment by NicMendonca** [comment]
@parasharrajat @aimane-chnaif please accept the offer when you can. Thanks!

**Comment by NicMendonca** [comment]
@daraksha-dk & @aimane-chnaif - paid, thank you!

**Comment by NicMendonca** [comment]
@parasharrajat just waiting on you to accept the offer so I can issue payment 😊

**Comment by parasharrajat** [comment]
@NicMendonca Please put this on weekly or monthly, there will be some time before I can accept the offer, it is probably the second week of Nov.

**Comment by NicMendonca** [comment]
@parasharrajat don't forget about this offer, please 🙏

**Comment by parasharrajat** [comment]
Thanks for the bump. @NicMendonca Accepted.

**Comment by NicMendonca** [comment]
everyone is paid! closing!
