### ISSUE TITLE
Picker UI is not consistent at safari - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > preferences

## Expected Result:
The picker is not consistent and looks broken

## Actual Result:
Describe what actually happened

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.99-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="374" alt="Screenshot 2022-08-29 at 2 47 51 PM" src="https://user-images.githubusercontent.com/43995119/190952566-27acda13-0cf6-428d-9607-851ae173b7ef.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661765012423859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Unable to repro on v1.2.2-0, @mvtglobally are you still able to repro this?

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/31225194/192557064-610efa5e-8663-4ed9-b104-58a92faf19ed.png">
