### ISSUE TITLE
Room Settings - User is able to type anything in the field when the field is disabled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11121]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with the expensify account
3. Click on FAB button and create a New Room
4. Tap on "Settings"
5. Disable the internet connection on the device
6. Change the name of the #Room and Click/tap Save
7. Try to change name again

## Expected Result:
It should not be possible to type anything in the field when the field is disabled

## Actual Result:
User is able to type anything in the field when the field is disabled

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** expensifail accounts

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191127749-1fb61687-ffe7-4d7c-9023-e7798299625c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
The field is not disabled, is showing as greyed out, indicating the action is pending and your changes did not save yet on the server.
We know the grey color is a but confusing as it looks disabled and will be addressing that in our upcoming overhaul of the visual design.
