### ISSUE TITLE
[$1000] iOS 16 - IOU - Request money - The cursor jumps to the first digit for a moment while adding other digits.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Click on the FAB button and select request money
3. Enter an amount

## Expected Result:
The cursor must remain on the last digit when adding digits

## Actual Result:
The cursor moves to the first digit while adding other digits.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS ( only in iOS 16)

**Version Number:** v1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191329547-091ebb27-880e-43d9-bf12-271d58b8dc5d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Pending proposals

**Comment by Uros787** [comment]
### Proposal
At first, I thought the problem was with the heavy checking we are doing on every click.
BUT, it turns out it's something new introduced in react native 0.70.0
https://github.com/facebook/react-native/issues/34695

The solution is to remove the selection prop from [IOUAmountPage.js](https://github.com/Expensify/App/blob/6551eb9d07f54c222bd6cb7411b7613f3ccd03b4/src/pages/iou/steps/IOUAmountPage.js#L255-L270)

I've tested the behavior on android and ios and there is no more flickering.

IOS:

https://user-images.githubusercontent.com/70144379/194812300-84eaacd1-490d-4866-83b6-0ac68b69cd44.mov

ANDROID:

https://user-images.githubusercontent.com/70144379/194812344-be96ced2-4fbb-418f-8fde-bf424bd9f722.mov

**Comment by Santhosh-Sellavel** [comment]
@Uros787,
Thanks, but this is a temporary workaround, not a solution. 

If you could solve the linked issue https://github.com/facebook/react-native/issues/34695 by submitting a PR then that's a solution.

cc: @thienlnam

**Comment by Santhosh-Sellavel** [comment]
Selecting and copying the amount or replacing the selected amount with another amount.

**Comment by Uros787** [comment]
right, but if it works fine without it I believe its not needed.
Maybe someone could test this with my proposal and verify?

**Comment by Santhosh-Sellavel** [comment]
@Uros787 Let's not rush here, we might missing something in the context. If it's not needed it would not be added here, if possible look into the PR where it was added to know more about why it was added.

**Comment by thienlnam** [comment]
@Uros787 We've actually been trying to move off of setNativeProps to upgrade to fabric. 
 Additional context here: https://github.com/Expensify/App/issues/11053.  But we can't just remove the selection prop

It actually seems like the bug we're running into here seems to be related to changes we're working on here: https://github.com/Expensify/App/issues/11053 so I am going to put this issue on hold

**Comment by Santhosh-Sellavel** [comment]
on Hold!

**Comment by thienlnam** [comment]
Seems like we've closed a lot of related issues - is this bug still occuring @kavimuru?

**Comment by kavimuru** [comment]
@thienlnam Will check with team and update here.

**Comment by kavimuru** [comment]
@thienlnam Issue is still able to reproduce.

https://user-images.githubusercontent.com/43996225/201786176-0991c523-3a7d-43b6-8977-bff120e8fc54.mp4

**Comment by thienlnam** [comment]
Thank you @kavimuru, going to remove the hold on this issue so we can get some proposals

**Comment by thienlnam** [comment]
Issue is back open for proposals!

**Comment by laurenreidexpensify** [comment]
Bumped in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668512461125889)

**Comment by hannojg** [comment]
Would we be open for a proposal where we remove the selection prop? I think I can make it work without the selection prop. Or do we want a upstream RN fix?

**Comment by fedirjh** [comment]
### Proposal

#### Problem 

There is an extra state update to `selection` that's triggered `onSelectionChange` even when `this.state.selection === e.nativeEvent.selection` . `onChangeAmount` (which update state of `selection`) is fired before `onSelectionChange` which also will update the same state when user is adding digits

### Solution

We have to prevent extra state updates if values are equal

https://github.com/Expensify/App/blob/6551eb9d07f54c222bd6cb7411b7613f3ccd03b4/src/pages/iou/steps/IOUAmountPage.js#L264-L269

```diff
-       if (!this.shouldUpdateSelection) {
+       if (!this.shouldUpdateSelection || _.isEqual(e.nativeEvent.selection, this.state.selection)) {
            return;
        }
```

#### Before

https://user-images.githubusercontent.com/36869046/201993547-fdba948e-f1f3-43d2-941b-5bc2270b4e21.mp4

### After

https://user-images.githubusercontent.com/36869046/201996075-1cb707d4-f1b1-4b61-8560-f65c9e2c5aad.mp4

**Comment by laurenreidexpensify** [comment]
As per this update, am closing this issue out. 
![2022-11-16_15-25-51](https://user-images.githubusercontent.com/62073721/202221971-492c7aa9-c20c-4ddf-b282-4175cee68c54.png)
