### ISSUE TITLE
Web - Request money - The second request money is interrupted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11158]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click FAB button/Request money
4. Enter the amount and choose any user
5. Сomplete the request for money
6. Immediately repeat steps 3 and 4

## Expected Result:
The following process of request money should take place

## Actual Result:
The request is aborted

## Workaround:
Unknown

Where is this issue occurring?

- Web

**Version Number:** v1.2.3-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191376351-8365ec8e-4643-4948-9b0d-88dbbab3515c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
@kavimuru could you please test again. I'm unable to reproduce the issue

**Comment by kavimuru** [comment]
@MonilBhavsar Will check with the team and update you.

**Comment by kavimuru** [comment]
@MonilBhavsar Sorry for the delayed response. Tester is still able to reproduce.
Account credentials : [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com) / Yulia1986Gerets

https://user-images.githubusercontent.com/43996225/192008344-aeed9405-5c9a-4b18-9cda-40321d841eb1.mp4

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment]
Keeping it open for a while to see if we can reproduce the issue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
