### ISSUE TITLE
Offline- Changing language English to Spanish in offline in device 1 is not updated in Device 2 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In the main testing device, Navigate to Settings > Preferences
2. Disable the internet connection in the device
3. Change the Language Settings - Verify the app text changes in languages (EN to ES)
4. Go back online
5. Check the language on the secondary device

## Expected Result:
Verify the language change occurs on the secondary device logged in to the same account

## Actual Result:
The language change occurs on the secondary device logged in to the same account doesn't change..

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191366692-a2c73e2b-d083-47ca-bbf1-ded4528a6d87.mp4
<img width="1261" alt="Bug5740877_En_Es" src="https://user-images.githubusercontent.com/43996225/191366702-5426f1fc-cce0-4b70-9be6-5bacbc9ca828.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
Lets bring this to a daily. I'm not sure if its external, i feel like its a pusher issue?

**Comment by ctkochan22** [comment]
Should have a chance this week

**Comment by ctkochan22** [comment]
The API command we are using: `UpdatePreferredLocale`

**Comment by ctkochan22** [comment]
Can you try again? Following the tests steps, I'm unable to repdroduce.

**Comment by ctkochan22** [comment]
@kavimuru

**Comment by ctkochan22** [comment]
Closing for now, please re-open if you can reproduce!

**Comment by kbecciv** [comment]
Issue is reproduced in build 1.2.21.4

https://user-images.githubusercontent.com/93399543/198613096-ca6963dc-126e-4d34-8ff1-f3366ad6658a.mp4

**Comment by ctkochan22** [comment]
@kbecciv Does this only affect mobile devices? Across iOS and android and vice versa?

**Comment by kbecciv** [comment]
@ctkochan22 Checking with a team, will update you shortly.

**Comment by kbecciv** [comment]
Issue is not affect Android and IOS devices.

![IMG_A1C099681565-1](https://user-images.githubusercontent.com/93399543/199292972-418ef93a-6637-4602-81ba-8befe9c3cc2b.jpeg)
<img width="1223" alt="Screen Shot 2022-11-01 at 11 29 57 AM" src="https://user-images.githubusercontent.com/93399543/199292975-524e7597-de85-4394-8633-00dc50bbaab0.png">

https://user-images.githubusercontent.com/93399543/199292980-d3417b43-97b6-4f5d-9c11-963d18317169.mp4

**Comment by ctkochan22** [comment]
So does it only affect mobile web? Trying to determine how its repoduce in comment: https://github.com/Expensify/App/issues/11153#issuecomment-1295006404

**Comment by ctkochan22** [comment]
bump

**Comment by ctkochan22** [comment]
I am OOO this week with a family issue. Please reassign or else I'll get to this next week

**Comment by ctkochan22** [comment]
Coming back from an unexpected amount of family leave. Looking into this this week

**Comment by ctkochan22** [comment]
Working on this week once other WAQ go out

**Comment by ctkochan22** [comment]
@kbecciv trying to nail down this question: https://github.com/Expensify/App/issues/11153#issuecomment-1299597156

Can you tell me specifically how to reproduce? You said [here](https://github.com/Expensify/App/issues/11153#issuecomment-1298840116) that it does not affect iOS and Android?

**Comment by ctkochan22** [comment]
Closing until we have clear repro steps

**Comment by kbecciv** [comment]
@ctkochan22 Checking with QA team, will update you here.

**Comment by kbecciv** [comment]
Issue is not reproductible 

https://user-images.githubusercontent.com/93399543/213007330-257591e8-eb65-4caa-9cf3-92210eb36310.mp4


https://user-images.githubusercontent.com/93399543/213007332-e9ee9111-3df7-47d3-9a65-3d495f64af26.mp4
