### ISSUE TITLE
Desktop - Error after trying to set new password via email link (forgot password)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/10969

## Action Performed:
1. Open Desktop app
2. Fill up the email field and cluck on the Forgot password button
3. Clink on the link form the email (or copy with adding staging domain)

## Expected Result:
The user should be able to use forgot password functionality without any issues

## Actual Result:
"We were unable to set your new password. We have sent you a new password link to try again." error appears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.3.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191538147-7af650bb-637c-45e0-b4d9-d44761701b7f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment]
cc: @MonilBhavsar

**Comment by shehroz147** [comment]
Hello,
I believe the issue can be due to the following reasons
When the user clicks the link and move to the screen to set up new password
The system isn't able to match which user has requested to change his password and hence database isn't updated

**Comment by MonilBhavsar** [comment]
PR's are merged and issue is fixed. So closing this out.
Tracking cleanup task in the main issue here https://github.com/Expensify/App/issues/11168
