### ISSUE TITLE
Reset password doesn't work when coming from the Desktop or mobile Apps

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#11168]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

More context in [this thread](https://expensify.slack.com/archives/C03TQ48KC/p1663774730098529)
Issue is described [here](https://expensify.slack.com/archives/C03TQ48KC/p1663777109064019?thread_ts=1663774730.098529&cid=C03TQ48KC)

## Action Performed:
1. Log out of any sessions you have open on Web
2. On Desktop, enter the email of a validated account
3. Tap `Forgot?`
4. Open your email and tap the link
5. Enter a new password and tap `Set password`

## Expected Result:
Password should be reset and user should be logged in

## Actual Result:
We get the error below:
![Screen Shot 2022-09-21 at 9 26 20 AM](https://user-images.githubusercontent.com/22219519/191558476-c3fa82c0-15fc-4d3e-8ab2-860d89ba3e93.png)

## Workaround:
Start the full flow from Web

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Things to do before closing issue:

- [ ] Merge Web-E https://github.com/Expensify/Web-Expensify/pull/34915
- [ ] Merge App #11198 
- [ ] Deprecate SetPasswordForNewAccountAndSignin API command and make App only call one command - UpdatePasswordAndSignin

**Comment by MonilBhavsar** [comment]
This is done
