### ISSUE TITLE
Login - Two messages displayed after tap on back button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Put you new email address in Sign in page
3. Tap Continue
4. Tap twice on Resent Link button
5. Go back to you email and find email from Expensify Concierge
6. Should arrived a several emails due to hitting Resent link twice
7. Tap on first one(oldest one), which is invalid already
8. Type password
9. Hit Set Password several times
10. Tap on back button

## Expected Result:
Should be no error messages at all

## Actual Result:
Two messages (Link has been re-sent and Password link invalid error message) displayed after tap on back button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.4-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191617891-d0894441-6a38-4351-9dcd-87bdf9bcee24.mp4
<img src="https://user-images.githubusercontent.com/43996225/191618020-147a088f-2437-40db-8b0b-ba6fd73364e0.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I have a fix for this [here](https://github.com/Expensify/App/pull/11165)

**Comment by luacmartins** [comment]
Working on a PR to fix this today!

**Comment by luacmartins** [comment]
I see that we had the same issue reported [here](https://github.com/Expensify/App/issues/11114) and it was already fixed [here](https://github.com/Expensify/App/pull/11145), but it can use some cleanup.
