### ISSUE TITLE
[$1000] mWeb/Safari - Split Bill - After splitting a bill, the screen UI is moving back and forth

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap the "+" icon > Split Bill >Proceed with the flow and select a couple of users

## Expected Result:
User expects that after splitting the bill, they are redirected to "Chat" with all the users and that the page loading is clean

## Actual Result:
The page layout UI jumps to the side before resizing

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Mobile Web (Safari)

**Version Number:** 1.2.4.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191733920-e0c0ca23-4a0f-4b22-8f75-c691649b319a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
[internal](https://www.upwork.com/ab/applicants/1573448294974300160/job-details)
[external](https://www.upwork.com/jobs/~012cc4ddcc4b38ba27)

**Comment by sheggietyn** [comment]
AS REQUESTED ON UPWORK -- THIS IS MY PROPOSAL

Even without seeing the code for the app yet, I observed that the animation to the Page layout having issues could be the cause, this might be a problem with the React Navigation animation used. 

-- This Issue can be solved if animation is removed from the page, and I hope a Safeareaview was added, i will like to see the code, I'm sure i can solve the problem

**Comment by mananjadhav** [comment]
@sheggietyn Thanks for the comment, but please refer these [contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) guidelines to see the process of adding the proposal.

And the code is already open sourced in this repository. You can fork and checkout the readme to setup the app to see it for yourself.

**Comment by mananjadhav** [comment]
@sheggietyn Thanks for the comment, but please refer these [contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) guidelines to see the process of adding the proposal.

And the code is already open sourced in this repository. You can fork and checkout the readme to setup the app to see it for yourself.

**Comment by adelekennedy** [comment]
Still waiting proposals!

**Comment by ctkochan22** [comment]
Waiting on proposals

**Comment by mananjadhav** [comment]
Waiting on proposals.

**Comment by adelekennedy** [comment]
We're at the doubling point @mananjadhav @ctkochan22 should this issue be doubled or is it not worth 1k?

**Comment by mananjadhav** [comment]
I think we should and then cap at 1K. What do you think @ctkochan22 ?

**Comment by sheggietyn** [comment]
i have downloaded the project, but i need to be assured that i will be paid before working on it, because the project looks like an opensource project already

**Comment by parasharrajat** [comment]
Good question, I think the first thing that you can check to make sure is to look at the spending on Upwork.
![image](https://user-images.githubusercontent.com/24370807/194751870-97684d46-4790-40b2-96fd-10c4f6cdc059.png)

If this is not sufficient. I would suggest taking a look at old jobs.

**Comment by adelekennedy** [comment]
@mananjadhav doubling then!

**Comment by sheggietyn** [comment]
i will work on it this afternoon, i hope to be done in 48 hours please get my payment ready 

thanks

**Comment by jayeshmangwani** [comment]
is this issue still happening?
I am not able to reproducible it in the simulator.


https://user-images.githubusercontent.com/35371050/194914146-891ad827-f87d-4415-8187-35e3084a0cd4.mp4


cc: @adelekennedy @mananjadhav

**Comment by adelekennedy** [comment]
@sheggietyn please review the [Contributor Guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) before you begin working on this, as far as I can tell you have not been awarded the job yet @mananjadhav @ctkochan22 (you should also review the payment guidelines to make sure that they work for you)

**Comment by mananjadhav** [comment]
Yes you're right @adelekennedy.

@sheggietyn Please review the contributor guidelines before working on this. I went through your comments and I don't see any solid technical proposal which describes what part of the component will you specifically change.

**Comment by adelekennedy** [comment]
Still reviewing proposals!

**Comment by adelekennedy** [comment]
capping at 1k!

**Comment by adelekennedy** [comment]
Still waiting for proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by ctkochan22** [comment]
I also could not reproduce on prod staging or dev. Going to close for now.
