### ISSUE TITLE
[$500] Update pages listening for `network.isOffline` in `componentDidUpdate()` to use `NetworkConnection.onReconnect()`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#11190]
# Problem

- Various components are currently subscribing to changes in the network key to determine whether some logic needs to run as part of a "reconnect". 

- The network key doesn't tell us if one or more of the requests we are running in these places has failed to occur because the authToken expired.

# Solution

The `NetworkConnection.onReconnect()` will now run some callbacks when either of these things happen.
We can also unsubscribe these callbacks in `componentWillUnmount()`

We must refactor and then test all the screens we are updating.

**Comment by NicMendonca** [comment]
Job posting: https://www.upwork.com/jobs/~01b9eea0566c82c750

**Comment by NicMendonca** [comment]
@marcaaron just to confirm, should I be assigning a C+ to this issue?

**Comment by marcaaron** [comment]
It's supposed to happen automatically. I'm not sure why it did not and will have to look into it.

**Comment by marcaaron** [comment]
Just gonna take this internal for now. Sorry @NicMendonca not sure why the C+ assignment didn't work and will have to check it out in another issue.

**Comment by marcaaron** [comment]
I'm guessing the `Exported` label has been deprecated and these kinds of issues are now tagged as `Internal` & `External` 🤔

**Comment by mananjadhav** [comment]
I got a few issues assigned yesterday which I already started reviewing. Can we please assign someone else here? @laurenreidexpensify @marcaaron

**Comment by laurenreidexpensify** [comment]
@marcaaron can you confirm if this is internal or external? the conflicting labels aren't clear :)

**Comment by marcaaron** [comment]
I think it's expected and issues can have both labels (not my idea). This is being worked on "internally" and we need an external review.

**Comment by laurenreidexpensify** [comment]
Marc was OOO last week, not overdue

**Comment by marcaaron** [comment]
Sorry about this, but I'm going to close this issue and create some follow up `External` issues instead. It can be done externally and I'm not able to prioritize working on this.
