### ISSUE TITLE
IOS - Picture is not displayed after using camera to update avatar - reported by @chauchausoup

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 
2. Navigate to Settings > Profile
3. Click on avatar to change profile pic
4. Select upload from Camera
5. Take a photo 

## Expected Result:
Picture should display after taking 

## Actual Result:
Camera popup is not appearing full screen

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.4-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  

https://user-images.githubusercontent.com/43995119/191661779-3f08c974-4b7c-46c6-9860-026e46228538.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662272938247309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chauchausoup** [comment]
@JmillsExpensify actually the proper Bug description as per Slack thread is :
`Whenever I try to take image for profile pic section via camera, I get a non full screen pop up  of camera interface rather than a full screen camera interface which I see in other standard apps.`

**Comment by JmillsExpensify** [comment]
Gotcha, so this is more of a product/design preference. I wouldn't call this a bug. I personally think this is fine and not a priority, so I'm included to close this issue. Further, we're going to redo this entire flow soon. Curious if you agree on closing @shawnborton @michelle-thompson?

**Comment by trjExpensify** [comment]
Yeah, I agree with that. @Gonals @roryabraham, aren't we going to rip out this camera component and use a new one when we get to the Scan Receipts project as well?

**Comment by shawnborton** [comment]
Yeah, I think we can close this one personally. I agree that once we build our own camera system, we'd just reuse that here.

**Comment by JmillsExpensify** [comment]
Awesome, thanks! Closing.

**Comment by roryabraham** [comment]
> aren't we going to rip out this camera component and use a new one when we get to the Scan Receipts project as well?

Not confirmed, but I think there's a good chance we might use https://mrousavy.com/react-native-vision-camera/
