### ISSUE TITLE
Room - Created room does not appear in LHN after sending the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot with a High traffic account that has a existing Workspace
2. Click on the green + button
3. Click on the "New Room" option
4. Create a new room
5. Send message in this room
6. Go to LHN

## Expected Result:
The room should be displayed in the LHN when the message was sent

## Actual Result:
Created room does not appear in LHN after sending the message

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.4.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191749301-b2a1908b-ee66-4449-8dcd-491af7776602.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
cc @neil-marcellini Looks related to the new API changes for AddWorkspaceRoom

**Comment by thienlnam** [comment]
I am testing this locally and cannot reproduce on Web - can you confirm this is still happening @kbecciv ?

**Comment by thienlnam** [comment]
Actually, it looks like the changes https://github.com/Expensify/App/pull/10863 were deployed Yesterday so I imagine the new refactor fixed this so I will close - feel free to reopen if you still notice it happening
