### ISSUE TITLE
Leave room button does nothing

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#11208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace by clicking the green plus, New workspace (if needed)
2. Create a workspace room by clicking the green plus, New room (if needed)
3. Click the header of the room to open the settings
4. Click Leave room

## Expected Result:
You leave the room

## Actual Result:
Nothing happens

## Workaround:
None

## Platform:

All platforms
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.4-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/26260477/191796342-b6684769-2a1c-4c24-8f4f-00f85fd6cbb8.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663862416907349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
This is expected. There was a project for this that was paused and will be resumed after n7.
