### ISSUE TITLE
Web -LHN - Crash after scrolling down in LHN expensifail account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in [applausetester+0704sveta@applause.expensifail.com](mailto:applausetester+0704sveta@applause.expensifail.com) / w323052760We
2. Scroll down in LHN

## Expected Result:
LHN should scroll all the scroll down and all chats should be visible

## Actual Result:
Crash after scrolling down in LHN expensifail account:
[applausetester+0704sveta@applause.expensifail.com](mailto:applausetester+0704sveta@applause.expensifail.com) / w323052760We

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+0704sveta@applause.expensifail.com / w323052760We
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191838994-9ed8ad91-a123-4af6-9ee1-89f787da1c57.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
huh, the console makes it seem like an avatar issue?

**Comment by ctkochan22** [comment]
```
react_devtools_backend.js:4026 TypeError: Cannot read properties of undefined (reading 'avatar')
    at HU (SidebarUtils.js:318:91)
    at KU (OptionRowLHN.js:59:24)
    at gi (react-dom.production.min.js:166:137)
    at dl (react-dom.production.min.js:289:386)
    at su (react-dom.production.min.js:279:379)
    at au (react-dom.production.min.js:279:310)
    at ou (react-dom.production.min.js:279:170)
    at Yl (react-dom.production.min.js:272:245)
    at Bo (react-dom.production.min.js:127:105)
    at Zl (react-dom.production.min.js:265:461)
```

`personalDetails` is undefined, and so its erroring out as we are trying to get `personalDetails.avatar`.

**Comment by ctkochan22** [comment]
Looks like it all crumbles when there is a room with 0 participants:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/12980144/191868391-67aae4c6-6695-4ea0-8b70-ab79c6b12679.png">

**Comment by ctkochan22** [comment]
Okay, so rooms with 0 participants is what breaks it. 
1. We pull the report data we need for the LHN object - [source](https://github.com/Expensify/App/blob/7fbe704ac8291944a7a8533bbcfa1df0e207b182/src/components/LHNOptionsList/OptionRowLHN.js#L59)
2. We get the participant list from the report object then pass it into `getPersonalDetailsForLogins() to get personal details --- [source](https://github.com/Expensify/App/blame/60ca87e88dacaaae64feddba1eee166df4b532b2/src/libs/SidebarUtils.js#L250)
3. For 0 participants, the method will return an empty object. When we try to get the [values](https://github.com/Expensify/App/blame/60ca87e88dacaaae64feddba1eee166df4b532b2/src/libs/SidebarUtils.js#L251) for the object, which returns an empty array
4. We then try to[ get the first element](https://github.com/Expensify/App/blame/60ca87e88dacaaae64feddba1eee166df4b532b2/src/libs/SidebarUtils.js#L252) of the array here, which returns undefined. So perstonalDetails is undefined
5. Then we try to get `personalDetail.avatar` from undefined which breaks everything.

cc @tgolen
