### ISSUE TITLE
mWeb - The error message is displayed 2 times and sometimes not displayed with a dot

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11222]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #11037 
## Action Performed:
1.Click on green fab icon (+)
2.Create a new room with the name "foo"
3.Repeat step 1, and create a new room with the name "bar" in the same workspace as room "foo".
4.Go to room "bar" -> Room settings
5.Rename it to "foo"
6. Click Save multiple times

## Expected Result:
The error message should appear with a dot and not double

## Actual Result:
The error message is displayed 2 times and sometimes Dot is not displayed for the error message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191864711-7af0fc20-7319-410c-bc70-18eea0346a6f.mp4
<img src="https://user-images.githubusercontent.com/43996225/191864752-f82d7b3e-b3ce-4e24-bd7c-c512473f6161.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Sorry, was out sick last week. This should be a relatively straightforward fix.. we're duplicating the error displaying somewhere, I can look into this.
