### ISSUE TITLE
[HOLD #10765] [$250] iOS - Chat -Scroll position incorrect after editing comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with the same expensifail account
3. Select any user
4. Type a couple messages
5. Hold your finger in the message
6. Select Edit comment
7. Save edit comment

## Expected Result:
Scroll position should allow the last edited message to be visible

## Actual Result:
Scroll position hides the last edited message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.5.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/1918

<img src="https://user-images.githubusercontent.com/43996225/191873439-806a1b52-1c16-4ff1-9877-4d034ae1283e.jpg" width="40%" height="40%">
73432-13653064-564f-432a-ae82-0a5f2edcda9e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment]
I can reproduce this but it's not as bad as it sounds, the message is simply scrolled slightly down. Marking as external.

https://user-images.githubusercontent.com/705000/191945342-c9dbe4cd-635c-459c-9781-231a30c6062f.mov

**Comment by Santhosh-Sellavel** [comment]
Could be related to this https://github.com/Expensify/App/issues/10765

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01759c89ecc6414c9e

**Comment by jasperhuangg** [comment]
> Could be related to this #10765

True, let's HOLD this on that issue, see if it fixes things, and then decide if we want to take proposals on this one.

**Comment by laurenreidexpensify** [comment]
This is [Hold] so not overdue

**Comment by Santhosh-Sellavel** [comment]
Can you bump this to `weekly` while we wait thanks!

**Comment by Santhosh-Sellavel** [comment]
on Hold

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment]
Not overdue, on hold

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by laurenreidexpensify** [comment]
still on hold

**Comment by laurenreidexpensify** [comment]
still on hold

**Comment by laurenreidexpensify** [comment]
Two weeks and nor reproducible in KI testing, closing.
