### ISSUE TITLE
[HOLD for payment 2022-10-07] [$250] IOS - Chat -Create Group button is hidden than unhidden when tap on field with finger

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with the same expensifail account
3. In app - tap on Fub menu
4. Select New Group
5. Type any email
6. Hold your finger when cursor at the end

## Expected Result:
Create Group button should be always visible

## Actual Result:
Create Group button is hidden than unhidden when tap on field with finger

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.5.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191865076-9bfa52e4-c4e2-4001-92f4-57b58de4431a.mp4

https://user-images.githubusercontent.com/43996225/191865081-47b33e91-f0df-41a0-891f-f35d040d21fd.mp4

**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Corroborated that's happening on iOS, it's working fine on Android though. Applying the `External` label.

**Comment by marcochavezf** [comment]
Thank you @rushatgabhane for the review! Assigning @aimane-chnaif 🚀

**Comment by JmillsExpensify** [comment]
Thanks for the quick work! While we wait for the regression period to pass, @aimane-chnaif and @rushatgabhane, can both of you apply to the Upwork job here: https://www.upwork.com/jobs/~015deb84070d50816b.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment]
Hired contributors in the linked job while we wait until the regression period is over.

**Comment by JmillsExpensify** [comment]
Regression period has passed, so I'm issuing payouts in Upwork for contributors and then I'm closing out this issue.

**Comment by JmillsExpensify** [comment]
Contributors - payments are out! Let me know if you have any issues or questions.
