### ISSUE TITLE
[HOLD for payment 2022-10-05] [$250] IOS - Chat - User get highlighted in grey when message is sent

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with the same expensifail account
3. Select user and send message
4. Select another user and send message
5. Back to LHN

## Expected Result:
User should not get highlighted in grey when message is sent

## Actual Result:
User get highlighted in grey when message is sent

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS 

**Version Number:** 1.2.5.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**  applausetester+09162022abb@applause.expensifail.com / Feya86Katya
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/191873237-542e69ff-9000-4d26-ae82-59c90eac6e92.jpg" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/191873243-e0627296-745b-4a2a-8f69-ac669fc83e90.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Yeah that's odd. Sending external.

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- If we want to remove highlighted then we need to remove the below block 

`focusedIndex={_.findIndex(optionListItems, (
                        option => option.toString() === this.props.currentlyViewedReportID
                    ))}`

https://github.com/Expensify/App/blob/b75faf0f6f5dcf8eab5e3734345f56256c7f3815/src/pages/home/sidebar/SidebarLinks.js#L152-L169

**Result**

https://user-images.githubusercontent.com/47522946/192078974-b12b84c7-c591-4bad-af5e-320d1f2cfe96.mp4

Note: I don't maybe its an issue or just new UI functionality

**Comment by mollfpr** [comment]
### Proposal

**Root cause**
We have option `disableFocusOptions` but not implemented on `LHNOptionsList`. The prop is used to determine should the option row has focused or not.
https://github.com/Expensify/App/blob/b75faf0f6f5dcf8eab5e3734345f56256c7f3815/src/pages/home/sidebar/SidebarLinks.js#L165

It's already implemented on the `OptionList` component.
https://github.com/Expensify/App/blob/b75faf0f6f5dcf8eab5e3734345f56256c7f3815/src/components/OptionsList/BaseOptionsList.js#L176-L177

**Solution**
Use `disableFocusOptions` from `SidebarLinks` to determine the option row focused.
```diff
diff --git a/src/components/LHNOptionsList/LHNOptionsList.js b/src/components/LHNOptionsList/LHNOptionsList.js
index 941057579..1b39dc546 100644
--- a/src/components/LHNOptionsList/LHNOptionsList.js
+++ b/src/components/LHNOptionsList/LHNOptionsList.js
@@ -26,6 +26,9 @@ const propTypes = {

     /** Callback to execute when the SectionList lays out */
     onLayout: PropTypes.func.isRequired,
+
+    /** Disable focus options */
+    disableFocusOptions: PropTypes.bool,
 };

 class LHNOptionsList extends Component {
@@ -69,7 +72,7 @@ class LHNOptionsList extends Component {
             <OptionRowLHN
                 reportID={item}
                 viewMode={this.props.optionMode}
-                isFocused={this.props.focusedIndex === index}
+                isFocused={!this.props.disableFocusOptions && this.props.focusedIndex === index}
                 onSelectRow={this.props.onSelectRow}
             />
         );
@@ -100,5 +103,8 @@ class LHNOptionsList extends Component {
 }

 LHNOptionsList.propTypes = propTypes;
+LHNOptionsList.defaultProps = {
+    disableFocusOptions: false,
+};

 export default LHNOptionsList;
```

**Result**

https://user-images.githubusercontent.com/25520267/192109852-bb84b2c5-e2ac-4e73-aa1a-07fcfc86f9a5.mov

**Comment by Puneet-here** [comment]
### Proposal

isFocused is being used to know which option is focused and we apply styles to the focused option. We want this functionality to work for LHN at big screens but not for small screens.

We can use withWindowDimensions to know the screen width and we can just check if it's a small screen width device

Replace this line 72 with 
 ```js 
isFocused={!this.props.isSmallScreenWidth && this.props.focusedIndex === index}
```


https://github.com/Expensify/App/blob/b75faf0f6f5dcf8eab5e3734345f56256c7f3815/src/components/LHNOptionsList/LHNOptionsList.js#L72

This way we won't see the highlighted row in the mobiles

**Comment by luacmartins** [comment]
@mollfpr your proposal looks good. Assigning you to the issue!

**Comment by mollfpr** [comment]
@luacmartins @rushatgabhane PR raised!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by arielgreen** [comment]
@mollfpr @rushatgabhane sent Upwork invite, please accept and I will remit payment

**Comment by mollfpr** [comment]
@arielgreen Accepted, thank you!

**Comment by arielgreen** [comment]
Paid.
