### ISSUE TITLE
[$250] [OptionsSelector] The cursor moves to the start of the input making typing hard

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#11239]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1663949837316499)
 
## Action Performed:
1. Tap `+ > Request money`
2. Type a contact name fast
3. Notice that the cursor moves to the beginning and end of the text, making typing random

## Expected Result:
User should be able to type without issues

## Actual Result:
Typing is erratic because the cursor changes position

## Workaround:
Type slowly

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya and @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663824664105649 and https://expensify.slack.com/archives/C01GTK53T8Q/p1663949837316499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can reproduce locally and reverting https://github.com/Expensify/App/pull/11036 fixes it.

**Comment by luacmartins** [comment]
This is done. Closing!

**Comment by dhairyasenjaliya** [comment]
hello @luacmartins @rushatgabhane  am I eligible for reporting this issue as I have posted this issue in slack first here but somehow got missed and also I have mentioned this might be a deploy blocker  https://expensify.slack.com/archives/C01GTK53T8Q/p1663824664105649

**Comment by luacmartins** [comment]
@dhairyasenjaliya of course! Sorry that we missed your posting on Slack. I'm gonna reopen this issue and assign a contributor manager to process the payment. Thanks for bringing this up.

**Comment by adelekennedy** [comment]
@dhairyasenjaliya will you apply here? I'l hire and pay out the reporting bonus!

**Comment by dhairyasenjaliya** [comment]
@adelekennedy job seems to be "Only invited users can find, view and apply to the job"

**Comment by adelekennedy** [comment]
Updated and refreshed @dhairyasenjaliya!

**Comment by dhairyasenjaliya** [comment]
Done  @adelekennedy

**Comment by luacmartins** [comment]
@dhairyasenjaliya @adelekennedy can we close this issue?

**Comment by dhairyasenjaliya** [comment]
@luacmartins applied to the job , yet to be accepted @adelekennedy

**Comment by adelekennedy** [comment]
done!

**Comment by dhairyasenjaliya** [comment]
Offer accepted

**Comment by adelekennedy** [comment]
Paid
