### ISSUE TITLE
Web - App crashed after logged out from expensifail account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps1. Go to sstaging.new.expensify.com
2. Log in with HT account
3. Select any user and request money
4. Select another user and request the money
5. Go to Settings - Sign out

## Expected Result:
User is successfully logged out from expensifail account

## Actual Result:
App crashed after logged out from expensifail account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.5.0

**Reproducible in staging?:** Yes/Occasionally

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191967504-fa915a20-7f09-448b-beb9-5ac3ee2e9569.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@kbecciv the credentials shared in the issue don't seem to work. I see the error below. Can you please verify if they are correct?

![Screen Shot 2022-09-23 at 8 51 36 AM](https://user-images.githubusercontent.com/22219519/191989368-4cd8a290-a1c5-483a-a2e2-be80fc8bf61f.png)

**Comment by kbecciv** [comment]
@luacmartins Sorry, overtyped email. Correct one is applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Comment by luacmartins** [comment]
I can repro this in prod (slightly different error at times, line 318 vs line 250), but the code that caused the crash in the QA video is also in prod. 

I'm assigning @tgolen since this is part of his `SidebarLinks` clean up. I left some comments [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1663938674288959) as I investigated this issue.

![Screen Shot 2022-09-23 at 9 43 40 AM](https://user-images.githubusercontent.com/22219519/192000778-2ff1a8fe-0350-488c-853d-792b9954e887.png)
