### ISSUE TITLE
[$500] Web - OldDot Transition - The created workspace appears, disappears, and reappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to NewDot and log in with a existing account
2. Navigate to OldDot and log in with the same account from the previous step
3. Navigate to Settings > Policies > Group and note the number of free policies
4. Click on the "New Policy" button/"Free" option
5. Verify you're redirected to NewDot, that you're logged in with the same account
6. Verify that only 1 new Workspace has been created

## Expected Result:
The new workspace should not disappear

## Actual Result:
The new workspace disappears for a while

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.5.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191968263-ddb0e095-e15d-46a3-af31-a02d39035429.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Oh damn yes, so odd.

**Comment by deetergp** [comment]
I think this _should_ have the `External` label and be weekly now. Is that right?

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~010fc860cadd7c3ac7

**Comment by deetergp** [comment]
I've added back the `External` label, which I think is the right one since it has been deemed contributor worthy and is currently awaiting proposals.

**Comment by kevinksullivan** [comment]
Not overdue, waiting on proposals.

**Comment by deetergp** [comment]
Not overdue, still awaiting proposals.

**Comment by parasharrajat** [comment]
May be it needs doubling

**Comment by kevinksullivan** [comment]
doubled

**Comment by kevinksullivan** [comment]
Not overdue, waiting on proposal and recently doubled.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
