### ISSUE TITLE
[$250] Ditch underscore, standardize on lodash

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11255]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
We currently use both underscore and lodash very prevalently throughout this project. However:

- Lodash is a superset of underscore, so it’s a drop-in replacement. We need features of lodash that aren't present in underscore such as `merge`, but there's nothing in underscore that's not in lodash
- According to [these benchmarks](https://www.measurethat.net/Benchmarks/Show/2825/0/lodash-vs-ramda-vs-underscore-190#latest_results_block), lodash is faster
- Using only one or the other reduces our bundle size (yes by a small amount)
- Having `_.get` instead of `lodashGet` everywhere will make our code prettier and more consistent
- It’s one fewer dependency to manage, so issues like [this one](https://expensify.slack.com/archives/C07J32337/p1663962955871119) will be less likely

### Solution
Replace usages of underscore with usages of lodash throughout the app.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Turns out lodash doesn't support `pluck` or `contains`, so I'm actually going to just close this because it's not as simple as just a find/replace.

**Comment by luacmartins** [comment]
They do have alternatives as `pick` or `includes` but I'm not sure if those methods are the same.
