### ISSUE TITLE
IOS/Android - Workspace - Rate and Unit got switch for a brief moment under Reimbursable expenses

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11155

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go Setting - Workspace - Reimbursable expenses

## Expected Result:
Rate and Unit got not switch for a brief moment under Reimbursable expenses

## Actual Result:
Rate and Unit got switch for a brief moment under Reimbursable expenses

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android ( switching from 0 to amount set)

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192109579-08c6ae1a-0ff7-4ebc-b819-50546d90bbd7.MP4

https://user-images.githubusercontent.com/93399543/192109817-6ade647e-ab40-4b22-99c7-52f34df941ae.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
This is expected behavior. There is no data for the custom unit until you visit this page for the first time. The rate and unit will be populated after the data syncs. I mentioned this in the testing steps "Verify the policy's distance rate displays **after a moment**"
