### ISSUE TITLE
mweb - Old dot - Creating a workspace from "Join" crashes the tab with different account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has another tab open on staging.new.expensify.com signed into account B
1. Access staging.expensify.com on another tab
2. Tap email > Input a new account different from Account B (Lets call this account A)
3. Tap join > Set up my company for free

## Expected Result:
User expects a staging.new.expensify.com tab to open on Account A's workspace and when returning to the tab with account B, that that tab is still functional

## Actual Result:
The tab with Account B crashes once the user "Joins" with account A

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192121430-5199ef3b-79a2-4a0e-ac1f-8ec503a10ef5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment]
I think that's wanted, as we don't want the 1st tab to appear connected whereas the active user on the browser is someone else now.
