### ISSUE TITLE
Web - Changing profile photo by pressing enter/return key changes the profile photo but also sets unnecessary focus on it @adeel0202

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile
3. Upload a new photo
4. Save photo by pressing enter/return key on the Edit photo modal

## Expected Result:
Profile photo changes without any focus

## Actual Result:
Profile photo changes with an unnecessary focus on it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192278403-1eb24ed9-d6b5-478e-8ca9-d1bac68638a8.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662366506340679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
Proposal
Use PressableWithoutFocus in AvatarWithImagePicker.

https://github.com/Expensify/App/blob/386c5ad8369a351528a70374dd7b92f1f9ec49cb/src/components/AvatarWithImagePicker.js#L234

Is it duplicate issue?
https://github.com/Expensify/App/issues/10599

**Comment by muttmuure** [comment]
I'm not sure what unnecessary focus is, but I added a new avatar and it looks fine to me.

**Comment by adeel0202** [comment]
@muttmuure I have attached the screenshot of the focus/outline on the avatar after pressing the enter key.
<img width="139" alt="Screenshot 2022-10-03 at 2 00 40 PM" src="https://user-images.githubusercontent.com/13783842/193539463-cfac8e20-5c1a-41a0-8dc6-b85e0593e2cd.png">

**Comment by adeel0202** [comment]
But looks like it is already known and going to get fixed in [another issue](https://github.com/Expensify/App/issues/10599) so you can keep this one closed.
