### ISSUE TITLE
[$500] Use disabled cursor on pending-deletion workspace

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into a new account.
1. Create a workspace.
1. Go offline.
1. Open the workspace `Settings -> Workspace`
1. Click on the "three dots menu", and select `Delete Workspace`
1. Confirm the deletion of the workspace.
1. Open the settings menu again.
1. Hover over the workspace, which should be displayed with strikethrough.

## Expected Result:
You can't click on this menu item anymore, so the cursor should adopt the "not-allowed" cursor style: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

## Actual Result:
The cursor remains as a mouse.

## Workaround:
n/a

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~01622e11116ab954f9

**Comment by roryabraham** [comment]
> I think the expected and actual results got swapped. Right? @roryabraham

Whoops! You are correct – fixing this now

**Comment by kevinksullivan** [comment]
Doubled price

**Comment by roryabraham** [comment]
Let's cap this issue here at $500

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- If we want to keep `disabled={props.disabled}` into `<Pressable>` without replacing `<TouchableOpacity>` then we can add `pointerEvents="auto"` into `<View>` that is inside `<Pressable>`

- CSS won't allow cursor event on the disabled button but adding `pointerEvents="auto"` enable that and also we are using `pointerEvents` in multiple components as well

- also need to add condition to check if workspace not available and add this `props.disabled && {cursor: styles.cursorDisabled}`

- We might need to add the same condition on `iconRight` (optional)

https://github.com/Expensify/App/blob/828588823d02df453f1891cc91f6498918dc5797/src/components/MenuItem.js#L82

<img width="1297" alt="Screenshot 2022-10-06 at 10 44 36 AM" src="https://user-images.githubusercontent.com/47522946/194219896-80c33920-8739-40ff-a138-df4268f1339e.png">

**Results**

https://user-images.githubusercontent.com/47522946/194220241-15cb5641-99fa-4fb6-b57a-bc64ea1b29ba.mov

**Comment by dhairyasenjaliya** [comment]
Yes i guess we can, but will test and update soon

**Comment by dhairyasenjaliya** [comment]
@rushatgabhane yes worked well even on passing `pointerEvents: "auto"` as a style
- we should create files the same as `styles.pointerEventsNone`


https://user-images.githubusercontent.com/47522946/194599518-b993c674-6e75-47ea-a2d7-4fe6e04d8ebb.mov

**Comment by kevinksullivan** [comment]
Hired @rushatgabhane for c+ and @dhairyasenjaliya for the fix. @dhairyasenjaliya when can we expect a PR?

**Comment by dhairyasenjaliya** [comment]
hello thank you for reminding me, forget to draft the PR doing now :) @kevinksullivan @rushatgabhane

**Comment by roryabraham** [comment]
PR merged 🚀

**Comment by roryabraham** [comment]
PR deployed to production yesterday in `1.2.18-10`, @kevinksullivan we should pay this out on 2022-11-01

**Comment by kevinksullivan** [comment]
Thanks for the bump @dhairyasenjaliya . Paid!
