### ISSUE TITLE
iPad Pro send money panel - user panel not visible

### ISSUE THREAD

**Issue by lbaldy** [Expensify/App#11302]
## Action Performed:
1. Login
2. Click on + icon
3. Click on send money
4. Enter amount
5. Click on next
6. See the contact search/picker isn't shown, only blank sidebar is visible

## Expected Result:
In point 6 it should show the user search panel

## Actual Result:
In point 6 it shows blank panel

## Workaround:
I don't think the user can progress in this flow on ipad.

## Platform:

Where is this issue occurring?

- Mobile Web (only iPad Pro)

**Version Number:**  1.2.6-0 and Current Production on (26Sep2022) 
**Reproducible in staging?:** N/A
**Reproducible in production?:** YES
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/7595998/192386687-1d926ba2-e336-4d63-b379-a25558f78ece.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
@lbaldy Please report this on slack.
