### ISSUE TITLE
Unable to sign in with email/password/2fa on staging web

### ISSUE THREAD

**Issue by cead22** [Expensify/App#11305]
To reproduce you must have an account with 2fa required
- Go to staging.new.expensify.com
- Enter your email
- Enter your password

## What actually happens:
An error is shown saying you must login with email and password

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/165133/192392000-821aa920-2592-4a8f-8143-115a89e8dec4.png">

## What I expect to happen:
The 2FA field should be visible and there should not be any error

Platforms:
- Staging web

**Comment by tgolen** [comment]
@MonilBhavsar Is this possibly related to your change in https://github.com/Expensify/Web-Expensify/pull/34757 ? I see that is the most recent change in this area. Did it also need a front-end change?

**Comment by MonilBhavsar** [comment]
This should be related to https://github.com/Expensify/App/pull/10811. Co-assigning and looking into it

**Comment by MonilBhavsar** [comment]
Requested a CP here https://expensify.slack.com/archives/C07J32337/p1664288355879469
It works now on staging.
But we need to CP it first to production before deploying App. So not removing `DeployBlocker` label.

Sorry for not noticing it earlier 🙇

**Comment by danieldoglas** [comment]
@MonilBhavsar just to confirm but is it possible that this is related to https://github.com/Expensify/Expensify/issues/230643?

**Comment by roryabraham** [comment]
I was never able to reproduce this, but it looks like https://github.com/Expensify/Web-Expensify/pull/34964 was CP'd to production. Can we determine if we are good to close this out or not?

**Comment by cead22** [comment]
I just tested this on staging and it's working fine

**Comment by MonilBhavsar** [comment]
> @MonilBhavsar just to confirm but is it possible that this is related to https://github.com/Expensify/Expensify/issues/230643?

I don't think so as we haven't updated the olddot code.
