### ISSUE TITLE
[Bug] Chat - Offline - The new messages aren't displayed in the conversation history.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into Expensify on desktop with Device A
2. On Device B, any platform, log in to another account
3. Disable your internet connection on Device A. WiFi > OFF
4. On Device B, send a message to the account logged in device A
5. On Device A, navigate to LHN (mobile) or to another conversation (Desktop/Web)
6. Enable the internet connection on Device A.
7. Ensure the message you sent via Device B is received on Device A
8. Disable the internet connection on Device A
9. Click/tap on the bold chat in LHN in Device A

## Expected Result:
Verify the new messages are displayed in the conversation history on Device A

## Actual Result:
The new messages aren't displayed in the conversation history Device A

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.2.7-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/192401124-8930448a-558a-4d2b-b719-d8049f1bb7cb.png" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/192401110-7791482d-77b7-4f56-b194-56e41569aa9f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment]
This issue is reproducible but not always! I can reproduce it if I toggle the internet really quickly on steps 5 to 7.

Both the reportActions and the report data are updated at the [same time here](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportUtils.php#L1931). This means we are sending both the `lastMessageText` (LNH message preview) and the chat messages back to the user without any delay from our servers, so I'm not sure why this is happening.

 After this [slack discussion](https://expensify.slack.com/archives/C02HWMSMZEC/p1664382041186289) I see that two requests are made when toggling the network, one for `ReconnectApp` and one for `OpenReport`:
 
`ReconnectApp`: Has all report data without the reporActions and has the updated `lastMessageText`
`OpenReport`: Returns the entire report history of reportActions with the new messages despite the fact they are being ingored.

**Comment by PauloGasparSv** [comment]
Summarizing the discussion so far:

It is possible to reproduce the error following the steps in the issue body. I replicated it on Web.

When the offline user reconnects to the internet, the App make some API calls to retrieve chat data that would have been received via pusher had it been online. In this case, the app calls the `ReconectApp` and `OpenReport` commands to update the reports and the reportActions.

<img src="https://user-images.githubusercontent.com/6564265/192867409-2af9241b-a177-4de1-b4c6-2b5a9b7f71e0.png" width="300"/>

The behaviours we've found so far and need investigations are:
1) Sometimes the `OpenReport` request is successful but doesn't add the messages to the chat. I can't replicate this every time but here is an example:
    <img src="https://user-images.githubusercontent.com/6564265/192868871-71b1520c-2d29-459f-b7e2-6766986da59c.png" width="1000" />
    This could mean we are receiving the data but we are not merging it in Onyx.

2) The `OpenReport` request isn't made for the chat with new messages but is made for other chats.

**Comment by JmillsExpensify** [comment]
Floating this yesterday in #whatsnext and #engineering-chat. Going to do that again today and then start reaching out to individuals.

**Comment by JmillsExpensify** [comment]
Still no takers, yikes! It's a tragedy of the commons. 😦

**Comment by grgia** [comment]
I can try and take a look at this tomorrow!

**Comment by grgia** [comment]
I'm on staging v1.2.12-3 and so far I am not able to reproduce

**Comment by JmillsExpensify** [comment]
Added myself. I'll try to reproduce sometime today.

**Comment by JmillsExpensify** [comment]
Sorry, I got back up. I'll have to circle back on this one tomorrow.

**Comment by JmillsExpensify** [comment]
Alright trying to reproduce this one now for real.

**Comment by JmillsExpensify** [comment]
@grgia I was able to reproduce this one. I also updated the testing steps. Essentially, the message appeared in the LHN and that chat was bolded, but that message (as well as the rest of the chat history wasn't loaded).

This is what I see when I complete the testing steps at step 9.
LHN
<img width="409" alt="Screen Shot 2022-10-17 at 10 42 07" src="https://user-images.githubusercontent.com/1127863/196207259-2e0d7877-b35b-48e9-b4d8-73066d0fe30c.png">

Main chat window
<img width="786" alt="Screen Shot 2022-10-17 at 10 37 39" src="https://user-images.githubusercontent.com/1127863/196207156-62e290f3-1107-4c9d-9eb8-f0ae5c676b3e.png">

Then when I turn the internet back on I see both the message bolded in the LHN as well as the history.
<img width="774" alt="Screen Shot 2022-10-17 at 10 43 19" src="https://user-images.githubusercontent.com/1127863/196207558-7697e9df-320a-4e55-b371-646ed676252a.png">

**Comment by grgia** [comment]
I retested, I can replicate. The new chat appears in LHN but not in the main chat

**Comment by grgia** [comment]
oop I just updated to staging 1.2.16-5 and am not able to replicate

**Comment by JmillsExpensify** [comment]
Checking on 1.2.16-5. Report back shortly.

**Comment by JmillsExpensify** [comment]
I ended up checking on 1.2.17-4. I *think* this might have happened the first time, but then I couldn't reproduce the second and third time. @trjExpensify do you mind double checking this and see if you can reproduce the first time (essentially before we cache the chat history).

**Comment by trjExpensify** [comment]
Yeah, I can reproduce it: 

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/16232057/196449916-96a5f4f2-69d1-4927-9116-cb073494b2db.png">

**Comment by JmillsExpensify** [comment]
Ok cool. Yeah I thought I was seeing double. This still happens to me too, but only the first time for that person. Screenshots below.

When I was offline (step 9)
<img width="787" alt="Screen Shot 2022-10-18 at 09 44 45" src="https://user-images.githubusercontent.com/1127863/196450356-c1e922c0-6e3d-4c44-80b5-5c743b3f7bc0.png">

Then after coming back online, I the message I sent online finally shows up in the chat history. 
<img width="778" alt="Screen Shot 2022-10-18 at 09 45 07" src="https://user-images.githubusercontent.com/1127863/196450544-0a97e9e6-e02b-41c4-9ef4-be334e578795.png">

**Comment by grgia** [comment]
Tested again and I can reproduce on staging desktop `v 1.2.16-5 ` with a user that Device A has chatted with- Ican also reproduce more than once!

**Comment by grgia** [comment]
As for a user I have never chatted with, I:
1. Went offline on Web
2. Sent a message from mobile from a new account 
3. Went back online on Web, no update to LHN
4. Went offline on Web a second time
5. Sent a second message from mobile to new account
6. Back online on web, LHN is bold with new chat
7. Offline once more on web, open bold chat. New message is loaded, but only the second message sent.
8. Online on web, both messages load but loading screen is not replaced.

after opening bold LHN chat offline (step 7):
<img width="1385" alt="Screen Shot 2022-10-18 at 12 01 53 PM" src="https://user-images.githubusercontent.com/38015950/196521515-e4d0a6e2-d553-406d-9983-da9bdb1d5f15.png">

after coming online (step 8):
<img width="1383" alt="Screen Shot 2022-10-18 at 12 02 05 PM" src="https://user-images.githubusercontent.com/38015950/196521667-0716de18-05e0-4251-9003-39f0945b5f0d.png">

**Comment by grgia** [comment]
I've been messing around with this, but I haven't been able to tweak the steps to get it to reliably reproduce. There's definitely something here, because it does occasionally happen, but most of the time both LHN and the chat history are being updated when a new chat is received

**Comment by grgia** [comment]
Looks like it's still working with a new chat too- going to close for now! 
https://user-images.githubusercontent.com/38015950/197304167-8c7ad8c3-a842-4342-8567-d310ddc2fd87.mov
