### ISSUE TITLE
[$500] Chat - Pasting copied text with CMD+SHIFT+V does not work in Safari

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11312]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot in Safari
2. Copy the text with markdown and navigate to NewDot chat
3. Paste the message that was previously copied with CMD+SHIFT+V

## Expected Result:
Message that was previously copied pasted successfully with CMD+SHIFT+V

## Actual Result:
Nothing happens. Pasting copied text with command CMD+SHIFT+V does not work.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web -  Safari

**Version Number:** 1.2.7-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192414201-047600dd-e0c8-46bc-bbcf-ba3aa19427a7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal tester

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
@kavimuru shouldn't you be using "CMD + SHIFT + V" for pasting in mac os instead of "CTRL"?

**Comment by kavimuru** [comment]
@aldo-expensify Yes, we used "CMD + SHIFT + V" and it wasn't working. Will update the steps and title.

**Comment by aldo-expensify** [comment]
@kavimuru are you sure? I can see in the video that the person is pressing "CTRL" and not "CMD"

**Comment by aldo-expensify** [comment]
No overdue, waiting for confirmation from @kavimuru

**Comment by kavimuru** [comment]
@aldo-expensify Sorry for the late reply. Still able to repro.

https://user-images.githubusercontent.com/43996225/193597448-f04bbebd-2a1c-458f-907a-bead012be7e1.mp4

**Comment by aldo-expensify** [comment]
Ahhh I was missing to test this in Safari instead of Chrome 🥲 , sorry for the confusion. I was able to reproduce that CMD + SHIFT + V is not working in Safari, and maybe it never did 🤷 

Labeling external!

**Comment by jliexpensify** [comment]
Posted

Intenral - https://www.upwork.com/ab/applicants/1577082589604179968/job-details
External - https://www.upwork.com/jobs/~018f5420dd5647ca64

invited @mananjadhav

**Comment by jliexpensify** [comment]
Going to double tomorrow if we get no proposals Melvin

**Comment by tgolen** [comment]
Still waiting on proposals.

**Comment by mollfpr** [comment]
It's `option+shift+cmd+v` on my Safari `Version 16.0 (17614.1.25.9.10, 17614)`.

<img width="382" alt="Screen Shot 2022-10-14 at 20 09 15" src="https://user-images.githubusercontent.com/25520267/195854873-a41275f3-2183-4cbe-bb3c-515e366291a0.png">

**Comment by tgolen** [comment]
Oh, no. I don't think this is about overwriting the shortcuts, no.

**Comment by mananjadhav** [comment]
@kavimuru Can you confirm testing this once with `Cmd + Opt + Shift + V`?

**Comment by jliexpensify** [comment]
Doubled - https://expensify.slack.com/archives/C01GTK53T8Q/p1665953394734899

**Comment by kavimuru** [comment]
@aldo-expensify Issue is fixed with` Cmd + Opt + Shift + V`

https://user-images.githubusercontent.com/43996225/196473909-a7d367df-f302-4a48-b5c2-1335e19273ad.mp4

**Comment by jliexpensify** [comment]
Great, closing as per @aldo-expensify 's recommendation!

**Comment by jliexpensify** [comment]
Upworks job removed.
