### ISSUE TITLE
When sending message on low WIFI, own messages ends up getting marked as unread in the LHN

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat 
2. Send few messages on low WIFI 
3. check LHN 

## Expected Result:
Unread messages should stay

## Actual Result:
Describe what actually happened

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.3-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663777725226859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Reproduced

https://expensify.slack.com/archives/C01GTK53T8Q/p1664384892862209?thread_ts=1663777725.226859&cid=C01GTK53T8Q

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~0175cbde3d2eb4e80a

**Comment by puneetlath** [comment]
@kevinksullivan it sounds like based on that thread this will be handled by sequence numbers though?
