### ISSUE TITLE
[$250] Web - Drag and drop - The page is jumping

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11329]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to any conversation
3. Reduce the size of the window
4. Drag-and-drop an image into the compose box in a chat
5. Resize the window to the maximum size

## Expected Result:
There should be no jump on the page

## Actual Result:
There is a jump on the page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.7.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192514847-288057f9-9233-4cbf-bf76-8b4cae4b63d1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
Still waiting for proposals right?

**Comment by sobitneupane** [comment]
Yes. Waiting for Proposals.

**Comment by jasperhuangg** [comment]
Hey, just seeing this issue–is this actually a bug? I feel like the jump could just be the web browser being slow. This should happen for all modals if that's the case. I'm gonna drop a note in #engineering-chat to clarify.

**Comment by jasperhuangg** [comment]
Closing, not sure this is a priority right now, or even a bug for that matter
