### ISSUE TITLE
mWeb - Chat -Drafted message is not moving to the top after made drafted message, only after refresh the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11332]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11211

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with the expensifail account
3. Make sure you are in default view mode
4. Make sure you have several pinned chats
5. Verify the group of pinned chats are sorted alphabetically in the LHN
6. Pin a new chat
7. Verify it gets added in the proper alphabetical order in the LHN
8. Make sure you have draft chats
9. Verify the group of draft chats are sorted alphabetically in the LHN
10. Add a new draft to a new report

## Expected Result:
Drafted message is moving to alphabetical order in the LHN after made drafted message

## Actual Result:
User need to refresh the page in mWeb to make drafted message is moving to alphabetical order in the LHN

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.7.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192517196-b04e50b2-7e9e-4ea9-9472-7366f2a9e216.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I think this is by design. We purposefully don't change the order of the active chat when adding drafts (to keep the LHN from jumping around, which can be jarring to the user).
