### ISSUE TITLE
"Make default payment method" option shown for account that hasn't been verified - reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to bank account > add info > company step > personal information
2. Dismiss the modal by pressing cross
3. Go to settings > Click on bank account with the same account number you just used

## Expected Result:
"Make default payment method" option shouldn't be shown for unverified bank account ( or maybe we shouldn't be showing the bank account in payments method until it gets verified

## Actual Result:
 "Make default payment method" is shown and when you try going through the flow you get error

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** need PROD account 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192598687-c67cebfa-a7b6-4c4f-ac9b-bc5c75cf0d95.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662752720733889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
Honestly not sure what we're supposed to show here; [asking for thoughts in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1664415151609369).

**Comment by ctkochan22** [comment]
That is not expected behavior. @nkuoch @MariaHCD 

Is the payment method supposed to show an incomplete VBA?

**Comment by MariaHCD** [comment]
> Is the payment method supposed to show an incomplete VBA?

No, I don't think we should be showing a VBA that's being setup in the payment method list. Does the OpenPaymentsPage API filter out bank accounts that are in the setup state?

**Comment by ctkochan22** [comment]
Must not, I'll fix it today

**Comment by ctkochan22** [comment]
This should probably be put in another GH for discussion, but it could be nice to have a "PENDING" option here. Its grey'd out and when you click it, it takes you back to the VBA flow

**Comment by MariaHCD** [comment]
This PR fix will ensure that withdrawal accounts that are being setup will not show in the payment method list: https://github.com/Expensify/Web-Expensify/pull/35076/files#r993071292

**Comment by Puneet-here** [comment]
@nkuoch, I think it's eligible for reporting bonus.

**Comment by arielgreen** [comment]
@Puneet-here -- just sent over the offer in Upwork! Once you've accepted I'll pay it out.

**Comment by Puneet-here** [comment]
@arielgreen, accepted. Thanks!

**Comment by arielgreen** [comment]
Excellent, paid.
