### ISSUE TITLE
Web -Attachment - Password autofill suggestion at password field for protected PDF @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2.  Log in with any account
3. Send protected PDF file
4. Click "enter the password"
5. Click on password field

## Expected Result:
There shouldn't be any autofill suggestion as this password field is for protected PDF fie

## Actual Result:
 There is password autofill

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192625027-9c553e4f-1e29-4dbb-abb7-95e5b19ab0ac.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662481363758199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
I'm on v1.2.8-0 and can't get the "add attachment" button to do anything.

**Comment by stitesExpensify** [comment]
Any thoughts @lschurr?

**Comment by stitesExpensify** [comment]
Closing this as I don't think it's really an issue
