### ISSUE TITLE
Workspace general settings save button does not have visual feedback Action performed: - reported by @mdneyazahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Settings -> Workspace -> General settings
3. Change name or default currency
4. Click save

## Expected Result:
Save button does not have visual feedback when the changes are saving.

## Actual Result:
Save button should have visual feedback when the changes are saving.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192687677-e64f440d-cd08-4ae0-bc25-7d31ae4edd46.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663135200801149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chauchausoup** [comment]
I think this issue is similar to this one.
https://github.com/Expensify/App/issues/11195#issuecomment-1258666293

**Comment by Luke9389** [comment]
I think we should ask @Expensify/design if this is expected, and if not, what to do about it. I guess we could show a success message above the save button?

**Comment by shawnborton** [comment]
I think we should close this because I believe this page is ripe to be revamped a bit with push to page. CC @trjExpensify

**Comment by trjExpensify** [comment]
Yeah, agreed. I suspect the growl was deprecated with the workspace API refactors as we're moving away from growls in App.

**Comment by shawnborton** [comment]
Okay, then I say we just close this one out for now. Reopen if you disagree!
