### ISSUE TITLE
Web - Connect bank account - The system returns to the previous page after returning online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/10987

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to Settings>Workspace>Connect Bank Account
3. Select "Connect Manually"
4. Go offline
5. Restore internet connection

## Expected Result:
The system should stay on the same page

## Actual Result:
The system returns to the previous page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.8.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192786486-7770d723-43be-4ade-a50a-b2d757c64598.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I'm not 100% sure this is a bug, do we have a test stating that it should stay on the same page? cc-ing a few others for some opinions @luacmartins @ctkochan22 @Julesssss

**Comment by Julesssss** [comment]
I'm not sure either, but I'm leaning towards 'bug', as it would be annoying to be kicked out of the flow if you temporarily lose connection after typing in your bank details.

**Comment by luacmartins** [comment]
I'm pretty sure this is a bug. We are supposed to override the server response with the locally stored `step` and `subStep` [here](https://github.com/Expensify/App/blob/7c29d89afe94b8e2f178e55b8f0137c91b1283c8/src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js#L175-L179). However, we set the `reimbursementAccount` key [here](https://github.com/Expensify/App/blob/7c29d89afe94b8e2f178e55b8f0137c91b1283c8/src/libs/actions/ReimbursementAccount/fetchFreePlanVerifiedBankAccount.js#L168) which empties both `step` and `subStep`. I put up a [draft PR](https://github.com/Expensify/App/pull/11422), if you wanna take a look.

**Comment by luacmartins** [comment]
That being said, these two statements seem conflicting to me:

>We are using set here since we will rely on data from the server (not local data) to populate the VBA flow and determine which step to navigate to.

>If we already have a substep stored locally then we will add that to the new achData

**Comment by luacmartins** [comment]
Nvm my comment above, I think they make sense as in we use server data for `step` but we can use local data for `subStep`
