### ISSUE TITLE
 Console error - Uncaught (in promise) TypeError: Cannot convert undefined or null to object - reported by @aimane

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Visit https://staging.new.expensify.com/
2. Inspect / Console

## Expected Result:
No console error

## Actual Result:
Console error - Uncaught (in promise) TypeError: Cannot convert undefined or null to object

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y (need repro) 
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="540" alt="console error" src="https://user-images.githubusercontent.com/43995119/192842655-397fdaab-e7c9-42ac-b213-04e9945a15cc.png">

https://user-images.githubusercontent.com/43995119/192842662-ae230865-507c-48fb-846b-d4bbcb2b5e05.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663221267406669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
@aimane-chnaif are you able to still reproduce this?  I was not.

**Comment by slafortune** [comment]
Closing for now - if you are able to reproduce this again @aimane-chnaif feel free to reopen this.
