### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] IOS - Keyboard doesn't persist taps and closes on taping from one to another on Rate or Unit field in Reimburse expenses page @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open IOS app user icon to open settings.
2. Select any workspace > reimburse expenses.
3. Tap on Rate text-field so that it gets focus and keyboard opens.
4. Tap on Rate drop down

## Expected Result:
Tap should do the action like opens drop down or focus Unit text-field

## Actual Result:
Tap is causing the keyboard or dropdown to close and have to tap again to do the action

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192881840-9d48488e-33a6-401f-aea4-e1667e4223f9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1663236134908079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Replicated in iOS! Moving to engineering.

**Comment by sobitneupane** [comment]
@aimane-chnaif Does this issue exist in Android and mWeb as well?

**Comment by sobitneupane** [comment]
@marcochavezf [proposal](https://github.com/Expensify/App/issues/11388#issuecomment-1262745992) from @aimane-chnaif  looks good to me. 

@aimane-chnaif Please do check other components which make use of `WorkspacePageWithSections` to make sure they work as expected and no regression caused.

🎀👀🎀 
C+ reviewed

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~011b32241123d1fcc0

Hired @sobitneupane for C+ and invited @aneequeahmad for reporting. @aimane-chnaif please apply to the job when you get a chance!

**Comment by marcochavezf** [comment]
Thank you @sobitneupane for the review, assigning @aimane-chnaif 🚀

**Comment by kevinksullivan** [comment]
@aimane-chnaif bump to apply for the job when you get a chance. 

https://www.upwork.com/jobs/~011b32241123d1fcc0

**Comment by kevinksullivan** [comment]
Sorry all, I missed this one over the weekend + with OOO. @aimane-chnaif just hired you for the job. Can you let me know when you accept so I can pay? @sobitneupane and @aneequeahmad are all set with payments.
