### ISSUE TITLE
[$1000] Enlarged View of avatar/profile picture is of low resolution (probably thumbnail) reported by @sobitneupane

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on any user’s avatar from chat.
2. Again click on avatar from the Details page.

## Expected Result:
The picture should have higher resolution.

## Actual Result:
The picture has lower resolution.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Screen Shot 2022-09-06 at 20 32 58" src="https://user-images.githubusercontent.com/43996225/192863125-51acca40-7db3-4b33-845a-df0a4b47d187.png">
<img width="1440" alt="Screen Shot 2022-09-27 at 06 30 11" src="https://user-images.githubusercontent.com/43996225/192863140-4b90a368-38cb-4527-97c1-aea8c13c70cc.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sobitneupane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662476149722849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment]
@kavimuru
Screen Recording demonstrating this issue.

https://user-images.githubusercontent.com/25876548/192866133-e1fc655d-7009-495b-aff5-eccbd29878b2.mov

**Comment by slafortune** [comment]
Reproducible with our own Chronos image - 

![image](https://user-images.githubusercontent.com/11725910/197276297-bae0cc43-a5fe-4ece-9a7f-62aade05227c.png)

**Comment by MariaHCD** [comment]
@rushatgabhane Doesn't the app have access to the high res image url as well?

**Comment by iwiznia** [comment]
Hmmm, it's possible we have the original, but still will probably not be much larger and stretching it out will make it look bad like Rushat said.

**Comment by sobitneupane** [comment]
I remember having high resolution image before. It must be a regression.

**Comment by mananjadhav** [comment]
> I remember having high resolution image before. It must be a regression.

I am assuming this changed after we added the Image editor/cropper on profile picture upload?

I am in for closing this one out. What do you think @iwiznia ?

**Comment by iwiznia** [comment]
I am honestly not sure. If the image we save is large and we have it, then I agree we can show the large image. On the other hand if we only save the small image, then we should close.

**Comment by slafortune** [comment]
Seems like the consensus here is that this should move forward - that the photo uploaded is high resolution but the one shown when selecting the avatar is not?

**Comment by slafortune** [comment]
Doubled price!

**Comment by mmjindal2555** [comment]
@slafortune , @iwiznia 

RCA - Seems the large(possibly original size) images are also present and accessible.

Example - 
The avatar URL currently being used - https://d1wpcgnaa73g0y.cloudfront.net/aae19548a867de39bf3a74394fdc376331da8cff_128.jpeg

The original image (can be fetched by removing _128 from the above URL) - 
https://d1wpcgnaa73g0y.cloudfront.net/aae19548a867de39bf3a74394fdc376331da8cff.jpeg

I can dig deeper into how to gracefully use the original image, otherwise, I guess removing _128 from the URL shall also work

**Comment by mmjindal2555** [comment]
Another example - 
Avatar URL - 
https://d1wpcgnaa73g0y.cloudfront.net/f0808018b91d553747aa87529366713e8139f44a_128.jpeg

Original Image URL - 
https://d1wpcgnaa73g0y.cloudfront.net/f0808018b91d553747aa87529366713e8139f44a.jpeg

**Comment by mananjadhav** [comment]
@mmjindal2555 Thanks for the findings. The enlarged image is available if you don't crop with the image editor we have on the App.

Please check one such example.

https://d1wpcgnaa73g0y.cloudfront.net/07224468a845eaae17169b21165b2ae3e073db38_128.jpeg

I don't see backend sending high res image to the API. @iwiznia Are you aware about it? and are we okay to show it for some images like @mmjindal2555's example?

**Comment by mananjadhav** [comment]
I am not sure of what the next actions should be here? @iwiznia Can we get a confirmation if we have the high resolution image stored in the backend which can be sent to the FE?

**Comment by iwiznia** [comment]
Looking at the code, we have the original image, in JPEG format saved. If you look for example at the personalDetails. You'll see that it has 2 properties: `avatar` and `avatarHighResolution`. The latter is the original one (or rather looking at the code, I think is the original one in jpeg).

**Comment by mananjadhav** [comment]
I checked that. The difference between `avatarHighResolution` and `avatar` URLs is `_128` appended in the URL for low res. But for the edited images the resolution is the same.

**Comment by iwiznia** [comment]
What do you mean by "edited images"?

**Comment by mananjadhav** [comment]
Images cropped from the Image editor before uploading. 

For instance, check my avatar. Both of them are same. 
`avatar`: https://d1wpcgnaa73g0y.cloudfront.net/07224468a845eaae17169b21165b2ae3e073db38_128.jpeg
`avatarHighResolution `: https://d1wpcgnaa73g0y.cloudfront.net/07224468a845eaae17169b21165b2ae3e073db38.jpeg


<img width="377" alt="image" src="https://user-images.githubusercontent.com/3069065/200341151-44132fc2-67e6-4277-98d1-28404af8fb77.png">

**Comment by iwiznia** [comment]
Ah yes, we don't save the original original 😄

**Comment by mananjadhav** [comment]
> Ah yes, we don't save the original original 😄

Yeah! I guess we don't edit/zoom, it stores a large image.

**Comment by mananjadhav** [comment]
@iwiznia then are we confirmed that we don't have the high res image?

**Comment by iwiznia** [comment]
We have the image you uploaded if you did not edit it and the edited image if you did.

**Comment by iwiznia** [comment]
So, what do we want to do here? Close?

**Comment by mananjadhav** [comment]
We can do that unless we want to handle the subset of the cases?

**Comment by iwiznia** [comment]
I don't think it's worth it, given it is probably a very small amount of users. Going to close. Reopen if you disagree.
