### ISSUE TITLE
[$250] IOS - Keyboard closes when tap on any other input field, drop down or take a photo in Workspace General settings - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open IOS app user icon to open settings.
2. Select any workspace > general settings
3. Tap on Name text-field so that it gets focus and keyboard opens.
4. Tap on Default currency or User image/take a photo

## Expected Result:
 Tap should do the action like opens drop down

## Actual Result:
Tap is causing the keyboard to close and have to tap again to do the action

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.5-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192873626-7dc1a584-efda-4287-a163-57c0a6c55ec1.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663235720727599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Yeah, I agree. This is very annoying. Let's start getting some proposals on it.

**Comment by strepanier03** [comment]
Thank you for the update @aimane-chnaif and for linking in those other issues. Cheers!
