### ISSUE TITLE
[HOLD for payment 2022-10-24] [$250] Text below composer does not always have same position - reported by @mdneyazahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Send message to User B
3. Observe below the composer in User B device. It should be "Name is typing...." Observe the padding on the left
4. Copy a long text of message and paste in the composer. It will display the error. Observe the padding on the left

## Expected Result:
Padding with and without an error should be same

## Actual Result:
Padding with and without an error is different

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.4-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img width="491" alt="web2" src="https://user-images.githubusercontent.com/43995119/192865800-0ce4fbd1-b8cf-406d-aa1a-5dc46bccd41a.png">
<img width="622" alt="web4" src="https://user-images.githubusercontent.com/43995119/192865805-b7484c96-b5a6-45a2-b02e-9a99322edb41.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663244169759019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 
We should be displaying the character limit error at the right because when user types it keeps changing the position.
To move it to the right we can create a style with `marginLeft: 'auto'` and we have to use it below
https://github.com/Expensify/App/blob/35e4606d21e3eccfeb0738ce96a8963fce81a93b/src/components/ExceededCommentLength.js#L18

**Comment by joekaufmanexpensify** [comment]
Reproduced in production, confirmed typing indicator and error message are not aligned:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/54866469/193079110-036efc19-afa8-4ae2-b440-6c8831206811.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54866469/193079124-58d58553-5d81-4e8c-a311-e602650a2ead.png">

**Comment by Gonals** [comment]
Good candidate for external!

**Comment by Puneet-here** [comment]
I have proposed the solution [here](https://github.com/Expensify/App/issues/11386?notification_referrer_id=NT_kwDOBhKferQ0NDk2ODMxNzM2OjEwMTg4Mzc3MA#issuecomment-1261414468).

**Comment by thesahindia** [comment]
@Ollyws, your proposal is dupe. It is already proposed by @Puneet-here.

@Puneet-here, you proposal looks good but we have to decide about the design here.

**Comment by thesahindia** [comment]
> We should be displaying the character limit error at the right because when user types it keeps changing the position. To move it to the right we can create a style with `marginLeft: 'auto'` and we have to use it below

@ctkochan22, can we ask design team for their opinion. I also feel that we should keep this at the right side.

**Comment by kadiealexander** [comment]
https://www.upwork.com/jobs/~010cb71c0ae4de50f7
https://www.upwork.com/ab/applicants/1575702465210789888/job-details

**Comment by kadiealexander** [comment]
cc: @Expensify/design could you please review @thesahindia's request above?

**Comment by shawnborton** [comment]
The bottom right side makes sense to me 👍 let's move it over there.

**Comment by kadiealexander** [comment]
With that in mind, @thesahindia are you happy with @Puneet-here's proposal?

**Comment by thesahindia** [comment]
Yeah @Puneet-here's [proposal](https://github.com/Expensify/App/issues/11386#issuecomment-1261414468) (the first approach) looks good to me.

🎀 👀 🎀 C+ reviewed

cc: @ctkochan22

**Comment by ctkochan22** [comment]
Looks good @kadiealexander can you hire @Puneet-here

**Comment by Puneet-here** [comment]
Can I start working on this? I am not hired yet.

**Comment by thesahindia** [comment]
> Can I start working on this? I am not hired yet.

@kadiealexander, let's hire @Puneet-here and assign them to this issue.

**Comment by Puneet-here** [comment]
> Can I start working on this? I am not hired yet.

Should I create the PR? The hiring process can be done later.

**Comment by thesahindia** [comment]
> Should I create the PR? The hiring process can be done later.

Yeah let's move forward.

**Comment by kadiealexander** [comment]
Sorry for the delay @Puneet-here, I've sent you a contract in Upwork now. :)

**Comment by kadiealexander** [comment]
Payment issued to @Puneet-here 

@thesahindia and @mdneyazahmad, please accept the contracts I just sent across and I'll get you two paid as well :)

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by kadiealexander** [comment]
Everyone is paid!
