### ISSUE TITLE
Web - Chat - SendPerfomanceTiming calls still shown under Networking

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/11280

## Action Performed:
1. Navigate to staging
2. Open the network tab in console
3. Switch to a different report
4. Open the Networking tab

## Expected Result:
There is no SendPerfomanceTiming calls show up in the network tab

## Actual Result:
SendPerfomanceTiming calls show up in the network tab.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1130" alt="Screen Shot 2022-09-28 at 12 52 13 PM" src="https://user-images.githubusercontent.com/93399543/192848177-3fd21777-e49d-4bad-abd5-e677a7fab90c.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Interna Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Those were just bad QA steps in https://github.com/Expensify/App/pull/11280. We still have timing calls that are executed when switching reports, like here: https://github.com/Expensify/App/blob/f1dc53487835f580eb7e6c1c69a3082c5848e9ce/src/pages/home/report/ReportActionsView.js#L332

Gonna just close this out!
cc @iwiznia

**Comment by iwiznia** [comment]
Ahhh sorry, at first I was removing them all, but then I saw some were used in graphs and left those in. Sorry!

Just QAed this and looks good
