### ISSUE TITLE
[mWeb] Blue line around plus button reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in safari
2. Click plus button
3. Close option list without selecting any option

## Expected Result:
Should not be blue line around plus button

## Actual Result:
Shows blue line around plus button

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Safari

**Version Number:** v1.2.9-0
**Reproducible in staging?:** Y (Needs preproduction)
**Reproducible in production?:** Y (Needs preproduction)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/192858497-9c068f24-6397-4c53-800f-371681819529.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663230829892489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mananjadhav** [comment]
@kavimuru I didn't report this. It must be someone else.

**Comment by gadhiyamanan** [comment]
@kavimuru it's me ✋

**Comment by kavimuru** [comment]
@mananjadhav Sorry. Will fix it.

**Comment by Puneet-here** [comment]
I think it same as https://github.com/Expensify/App/issues/11382 and only happens at older versions.

**Comment by slafortune** [comment]
Can't reproduce
iOS 16
https://user-images.githubusercontent.com/11725910/196786402-c4c9beee-a50a-41c3-b307-0ec6346203d8.MP4
