### ISSUE TITLE
[$500] Web -Set Password - Autofill suggestion shows up for password field at set password page @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Put new email address under log in 
3. Click continue
4. Click Resent - Link
5. Go to you email
6. Copy the email into new browser and add staging before url
7. Focus on the field

## Expected Result:
Autofill suggestion shouldn't be shown

## Actual Result:
Autofill shows up

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
<img width="373" alt="Screenshot 2022-09-15 at 6 02 41 PM" src="https://user-images.githubusercontent.com/93399543/192884786-0905f85c-3967-410f-ba53-87fdce794286.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663245567576029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@Julesssss  , is it possible to disable the autofill suggestions on the set password page? If so, then it makes sense to me to fix this.

**Comment by Julesssss** [comment]
It _should_ be possible, though some password managers actively ignore the prop that we can set to prevent password managers from showing. 

Let's try to solve for Chrome and Safari password managers, with the understanding that 3rd party solutions are out out of scope here.

**Comment by mananjadhav** [comment]
Still looking for proposals.

**Comment by Julesssss** [comment]
@puneetlath could we please double the bounty? Thanks!

**Comment by puneetlath** [comment]
Updated to $500! 

External upwork job: https://www.upwork.com/jobs/~01c664c9b077916369
Internal upowrk job: https://www.upwork.com/ab/applicants/1582732633604943872/job-details

**Comment by albrimpaqarizi** [comment]
Hello!

Just add the `autoComplete="off"` in form element

**Comment by Julesssss** [comment]
Lol, yep that sounds simple enough 😄 

Would you like to work on this PR @albrimpaqarizi? Your message doesn't quite seem like a proposal so I just wanted to check before assigning this to you.

**Comment by mallenexpensify** [comment]
@albrimpaqarizi , check https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md for more details about submitting a proposal, if interested.

**Comment by mananjadhav** [comment]
@mallenexpensify @Julesssss Time to double?

**Comment by puneetlath** [comment]
@johnmlee101 will this page become obsolete with #passwordless?

**Comment by johnmlee101** [comment]
Yess it should 😄 let's put a HOLD on this at a minimum

**Comment by puneetlath** [comment]
Ok I'm going to close this out then since this page is about to go away. @thesahindia I sent you a hiring offer for the reporting bonus since it is a current bug.

**Comment by thesahindia** [comment]
Thanks @puneetlath but I am not sure if this is eligible since we aren't compensating unless the issue gets fixed. 
Also just curious what's "#passwordless", are we planning to remove passwords?

**Comment by puneetlath** [comment]
Yes, we are planning to remove passwords. Which is effectively a fix for this bug, so I think it qualifies.

**Comment by thesahindia** [comment]
Cool thanks for clarifying. I have accepted the offer.
I think we can also close https://github.com/Expensify/App/issues/11403?
