### ISSUE TITLE
[$250] mWeb/Chrome - Cursor color is (black) not the same as the mobile app (blue) @jayeshmangwani

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to chat and check the cursor color at composer

## Expected Result:
It should be of blue color, the same the mobile app

## Actual Result:
Cursor color is black

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Android/Chrome)

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Andoid mobile app](https://user-images.githubusercontent.com/93399543/192886285-93c7f15d-400c-48b9-9456-fe4fc7d5d26d.jpg)
![Android web](https://user-images.githubusercontent.com/93399543/192886288-54343bc9-cace-463e-b576-64efd8de4c6e.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663248561928939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
@laurenreidexpensify - are you okay if i reassign this one to you? lmk if not!

**Comment by laurenreidexpensify** [comment]
waiting for confirmation of external label

**Comment by cristipaval** [comment]
Hey @laurenreidexpensify , yes this could be marked external. What I can add is that this happens in Chrome on Android only, not reproducible on iOS.

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~013fe6eb65708a20e5

**Comment by parasharrajat** [comment]
Interesting issue.

**Comment by parasharrajat** [comment]
Thanks for the proposal @Ollyws. Please follow - [CONTRIBUTING Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to propose a proposal to help us manage things easily.

--- 
`caretColor` seems like a non-standard RN-style property. Will it issue a warning?

**Comment by parasharrajat** [comment]
Thanks for the proposal everyone. We decided to do nothing here as changing the cursor will add unnecessary overhead. By default, the platform should select the best cursor color for its users.
