### ISSUE TITLE
The email of setup specialist shows up in the LHN instead of the name on receiving the first message reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Go to admin room

## Expected Result:
The name should be shown

## Actual Result:
Email shows up in the LHN, but you can see the name in the chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1323" alt="Screenshot 2022-09-15 at 10 08 06 PM" src="https://user-images.githubusercontent.com/43996225/192898476-eef740ee-bea7-4d56-b799-fdfb8df5cc82.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1663259931587589
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Not able to recreate - 
![image](https://user-images.githubusercontent.com/11725910/197221439-1a3383f0-de16-4d6b-a55f-7e9a1cf6facb.png)
