### ISSUE TITLE
Clicking on the full page image takes to the oldDot reported by @parasharrajat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the web app.
2. Refresh the page a few times until you see image as per the screenshot.
3. click anywhere on the image area.

## Expected Result:
There should be a dedicated button or link for navigation.

## Actual Result:
Clicking anywhere on the image area, takes you away from the web app. This bad as image takes 70% of the screen. And This feels like click jacking or advertisement.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web 

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/192903053-21a422be-b68e-4fc1-86b5-65238d6a96b2.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663239052415099

https://user-images.githubusercontent.com/43996225/192903053-21a422be-b68e-4fc1-86b5-65238d6a96b2.mp4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1664805159598329?thread_ts=1663239052.415099&cid=C01GTK53T8Q

This isn't a bug, we are advertising an oldDot feature on newDot. So when you click it, we route you to oldDot.

It's not an ideal flow necessarily, but this isn't a priority to fix yet.
