### ISSUE TITLE
Search - Searching expensify.sms displays numbers in search result @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Go to Search page.
3. Search combination of these letters "e, x ,p, e, n, s, i, f, y".

## Expected Result:
It should not show phone numbers in search result.

## Actual Result:
Phone Numbers are showing up in search result.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193050618-2009c765-fe4c-4ac9-bd82-d199a2b56170.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Tushu17

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1663611942078499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
Phone numbers are showing up by design, because the phone numbers a tied to @Expensify.sms email addresses.
