### ISSUE TITLE
The form error message isn't showing up correctly in spanish - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to preference and change preferred language to spanish.
3. Go to Request call page/Connect bank account page.
4. Submit unfilled form

## Expected Result:
Error message shouldn't leave any blank space on side.

## Actual Result:
It is leaving blank space on side.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

<img width="403" alt="Screenshot 2022-09-16 at 2 04 04 PM" src="https://user-images.githubusercontent.com/43995119/192936188-0c6af6a3-04ba-4a4d-a8eb-0081c4dc6152.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663317764966639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment]
### Proposal 
we need to keep Text component as a parent in 
https://github.com/Expensify/App/blob/3e03f0827c1109a050c50605b2484fbd2d6b20f5/src/components/FormAlertWrapper.js#L66-L80

````diff
-                           <>
                            <Text style={styles.mutedTextLabel}>
                                {`${props.translate('common.please')} `}
-                            </Text>
                            <TextLink
                                style={styles.label}
                                onPress={props.onFixTheErrorsPressed}
                            >
                                {props.translate('common.fixTheErrors')}
                            </TextLink>
-                            <Text style={styles.mutedTextLabel}>
                                {` ${props.translate('common.inTheFormBeforeContinuing')}.`}
                            </Text>
-                        </>
````

OR

````diff
-                          <>
+                         <Text>
                            <Text style={styles.mutedTextLabel}>
                                {`${props.translate('common.please')} `}
                            </Text>
                            <TextLink
                                style={styles.label}
                                onPress={props.onFixTheErrorsPressed}
                            >
                                {props.translate('common.fixTheErrors')}
                            </TextLink>
                            <Text style={styles.mutedTextLabel}>
                                {` ${props.translate('common.inTheFormBeforeContinuing')}.`}
                            </Text>
-                        </>
+                       </Text>
````

**Comment by akshayasalvi** [comment]
**Proposal**

I would go with replacing the `<>` with `View`. So in `FormAlertWrapper`, I would do this:

```
+ <View style={[styles.dInline, styles.w100]}>
    <Text style={styles.mutedTextLabel}>
        {`${props.translate('common.please')} `}
    </Text>
    <TextLink
        style={styles.label}
        onPress={props.onFixTheErrorsPressed}
    >
        {props.translate('common.fixTheErrors')}
    </TextLink>
    <Text style={styles.mutedTextLabel}>
        {` ${props.translate('common.inTheFormBeforeContinuing')}.`}
    </Text>
</View>
```


Because based on my experience, having nested `Text` especially with link, have issues with accessibility.

**Comment by bondydaa** [comment]
hmm I've had a few style/design things come up on various views (this is the other one https://github.com/Expensify/App/issues/11148) 

cc @Expensify/design can you take a look and confirm how the spacing should look for Brick Road errors on this and https://github.com/Expensify/App/issues/11148 

Then we can take care of all of these in one go instead of playing wack-a-mole with styles on one view that then breaks another view that then breaks another view.

**Comment by shawnborton** [comment]
Well I think two things are happening here:
- In the example above, the blue link is causing a line break after it, and thus the weird space afterwards 
- We should switch over to the new red brick road/dot indicator for this error message

**Comment by akshayasalvi** [comment]
@shawnborton Yes, because the blue link is using `TextLink` component and hence I recommended to use `dLine` style in my proposal https://github.com/Expensify/App/issues/11410#issuecomment-1261993956.

Also for the second point do you mean replacing the red exclamation mark with the red brick road? That would mean the replacing the following line in `FormAlertWrapper`  as mentioned in the code block.

https://github.com/Expensify/App/blob/6748e8a6c5363a626490e436c84ecd53df7266c6/src/components/FormAlertWrapper.js#L59

```diff
- <Icon src={Expensicons.Exclamation} fill={colors.red} />
+ <Icon
+      src={Expensicons.DotIndicator}
+      fill={colors.red}
+      height={variables.iconSizeSmall}
+     width={variables.iconSizeSmall}
+  />



```

**Comment by shawnborton** [comment]
Instead of replacing `FormAlertWrapper` with the code you mentioned, is there a way we can just reuse the red dot indicator component? cc @iwiznia @jasperhuangg for thoughts there.

**Comment by akshayasalvi** [comment]
I can do that if that's what is expected, but `FormAlertWrapper` is used on all the forms,

1.  that would require QA for all the forms.
2. `FormAlertWrapper` supports three types of messages (and DotIndicator only supports an array of Text messages): 
      a. HTML messages with `RenderHTML`
      b. Messages passed in props shown as `Text`
      c. No message passed (used in Form), with default error message as a combination of `Text`, `TextLink` and `Text`.
3. We don't support blue `TextLink` format in `DotIndicatorMessage`

We can either  change the whole component with all the above points or just put the Red indicator like previous proposal.

**Comment by iwiznia** [comment]
hmmmm besides the points made above, the behavior also feels quite different for both components, so not sure if unifying them is good.

**Comment by shawnborton** [comment]
Got it. I'm mostly just saying that the exact style/format of the red dot indicator with message should be used here, so maybe there is a way to DRY it up. Either way works for me though, but from a design standpoint, they should look the same.

**Comment by akshayasalvi** [comment]
So what is expected here @iwiznia @shawnborton ? Are we good with the red dot indicator here https://github.com/Expensify/App/issues/11410#issuecomment-1265318914?

**Comment by iwiznia** [comment]
I think so

**Comment by Puneet-here** [comment]
I think we should refactor the `DotIndicatorMessage` so that we can reuse `DotIndicatorMessage` at most places. We are also going to use it for normal errors so it makes sense to refactor it. We just need to move `FormAlertWrapper` render functionality to `DotIndicatorMessage`

**Comment by Puneet-here** [comment]
I believe it can be done without hacks because we can use props to tell about what type of message dotIndicator needs to show or we can check what type of message is being sent inside dot indicator to decide how we wanna render it. For example when we want a label with links we send a prop `LabelComponent` and the the message in the form of component to the CheckboxLabel and then it renders it as it is.

> one supports just one message and apparently html (?) and the other supports multiple ones and no html
IIRC DotIndicatorMessage currently renders the error messages passed as an object and the FormAlertWrapper renders html, strings and a message with link in it when no error message is being passed.

**Comment by bondydaa** [comment]
Ionatan has been OOO for most of this week so will wait for him to get back to help us decide how we want to approach this.

**Comment by iwiznia** [comment]
If we can reuse, then sounds better, but not exactly sure I follow the LabelComponent proposal

**Comment by shawnborton** [comment]
Not overdue, but what's the latest update here?

**Comment by shawnborton** [comment]
That works for me! Will comment over there shortly.

**Comment by Tushu17** [comment]
Reporting compensation is pending here.
cc- @shawnborton @bondydaa

**Comment by JmillsExpensify** [comment]
I'll handle that, one second.

**Comment by JmillsExpensify** [comment]
Upwork issue is here for reporting: https://www.upwork.com/jobs/~01fce977f1f5d66b7a. Please apply and I'll issue payment.

**Comment by Tushu17** [comment]
> Please apply and I'll issue payment.

Okay applied, Thanks @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Offer extended via Upwork.

**Comment by Tushu17** [comment]
@JmillsExpensify Thanks, Offer accepted

**Comment by JmillsExpensify** [comment]
Thanks! I issued payment in Upwork, so I'm closing the issue again.
