### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Connect Bank Account - The checkbox is already checked off under Connect manually @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to settings > workspace > connect bank account
3. Click Connect manually

## Expected Result:
The checkbox shouldn't be in the checked state

## Actual Result:
The checkbox is already checked off under Connect manually 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
<img width="200" alt="Screenshot 2022-09-20 at 8 55 49 PM" src="https://user-images.githubusercontent.com/93399543/193060577-bac374e7-13a7-4f6a-9a95-452bf0b80748.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663687990703219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal

I already have added the proposal in the thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664446949045039?thread_ts=1663687990.703219&cid=C01GTK53T8Q)
Copy/Pasting it here:

We need to change the default value from true to false
https://github.com/Expensify/App/blob/35e4606d21e3eccfeb0738ce96a8963fce81a93b/src/pages/ReimbursementAccount/BankAccountManualStep.js#L36

**Comment by varshamb** [comment]
### Proposal

We should replace below with `acceptTerms: false`,

Let's say if we change it from true to false in `acceptTerms: ReimbursementAccountUtils.getDefaultStateForField(props, 'acceptTerms', false),` and user has checked off the checkbox, it will be be in checked off even we came out from that page. It's always better not to checked it off whenever the use lands to this page.

https://github.com/Expensify/App/blob/35e4606d21e3eccfeb0738ce96a8963fce81a93b/src/pages/ReimbursementAccount/BankAccountManualStep.js#L36

**Screenshot:**
1. Only Changed to `false`

https://user-images.githubusercontent.com/111683206/193123279-05dcadd7-0c6d-4d33-8e57-29e19083a663.mov

2. changed to `acceptTerms: false` (as I Proposed)

https://user-images.githubusercontent.com/111683206/193123921-1df88506-4bd8-47ff-ae4b-3c287091f836.mov

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~014461b30c7f09cff2

@parasharrajat looks like we have a few proposals already!

**Comment by parasharrajat** [comment]
@chiragsalian Thoughts :arrow_up: ?

**Comment by chiragsalian** [comment]
Yup i was just reading this. I think we should set it to false for the terms here but I'm no expert on this. I'll ask on slack to get more eyes and confirm on this.

**Comment by parasharrajat** [comment]
Ok. Thanks for the input. Putting up a slack discussion now.

**Comment by chiragsalian** [comment]
Asked on Slack, the decision is to have it false/unchecked by default.

**Comment by parasharrajat** [comment]
@Puneet-here 's [proposal](https://github.com/Expensify/App/issues/11419#issuecomment-1262387067) looks good to me. It was the first based on timestamps from slack/Gh.

cc: @chiragsalian 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by chiragsalian** [comment]
LGTM too. Feel free to create the PR @Puneet-here.

**Comment by arielgreen** [comment]
@Puneet-here @parasharrajat check your Upwork inboxes please

**Comment by arielgreen** [comment]
Paid.

**Comment by arielgreen** [comment]
@parasharrajat for some reason there were two contracts for you, so I closed one and paid the other.
