### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Text is going out of the border - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Preferences
2. Change language to español
3. Go back > About > Keyboard shortcuts

## Expected Result:
Text shouldn't overlap with the border

## Actual Result:
It is overlapping with the border

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="608" alt="Screenshot 2022-09-16 at 3 37 29 PM" src="https://user-images.githubusercontent.com/43995119/192936958-21925364-e9f0-415a-94b6-9e889a532621.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663322861694949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
**Porposal**

remove `styles.flex1` from below code 
https://github.com/Expensify/App/blob/1bed3e5bc8c895eb630206e19c0aa82970f890f1/src/components/KeyboardShortcutsModal.js#L56-L61

After Fix

![Screenshot 2022-09-29 at 10 24 29 AM](https://user-images.githubusercontent.com/54790231/192942143-7a34e448-b951-44be-a938-c9fbff57eda5.png)
![Screenshot 2022-09-29 at 10 25 10 AM](https://user-images.githubusercontent.com/54790231/192942216-918b2cc2-cab4-4eb4-9614-04372bb1c635.png)

**Comment by danieldoglas** [comment]
Yep, we can export this.

**Comment by akshayasalvi** [comment]
I honestly don't remember @aimane-chnaif. Its been quite long that I worked, but mostly it had to do with the heights of the table and the rows.

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/11411#issuecomment-1261752028) from @gadhiyamanan tested well on Web and Desktop. As keyboard shortcuts are not shown in native devices, I didn't test it on native devices.

@Julesssss [Proposal](https://github.com/Expensify/App/issues/11411#issuecomment-1261752028) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
Cool, given that we're unsure about the flex prop removal let's ensure we test the PR thoroughly.

**Comment by gadhiyamanan** [comment]
@sobitneupane [PR](https://github.com/Expensify/App/pull/11532) raised , let me know if i missed anything

**Comment by MitchExpensify** [comment]
[Upwork Job](https://www.upwork.com/jobs/~0115986e6067b7ce58)

**Comment by Julesssss** [comment]
Merged, awaiting deployment to staging.

**Comment by gadhiyamanan** [comment]
> [Upwork Job](https://www.upwork.com/jobs/~0115986e6067b7ce58)

@MitchExpensify This job is no longer available.

**Comment by MitchExpensify** [comment]
Ugh I hate how Upwork auto closes jobs.

I've invited you to [a duplicate post here](https://www.upwork.com/jobs/~010c3ed2a100dee31c) @gadhiyamanan 

And I'll use the [original Upwork job](https://www.upwork.com/jobs/~0115986e6067b7ce58) to issue payment to you both @thesahindia & @sobitneupane

**Comment by MitchExpensify** [comment]
All paid and contracts ended! Thanks everyone
