### ISSUE TITLE
[Hold #11768] mWeb- Connect Bank Account - Pressing back button at android in the middle of a step takes you back to the workspace page instead of going back to the previous step @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Go to bank account > add info > company step
3. Press back button of mobile

## Expected Result:
ou should be navigated back to the previous step

## Actual Result:
You will be navigated to the workspace page

## Workaround:
Unknow

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193102567-8d812de1-7932-4f37-9cfb-d59b118b642c.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663792588717789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I don't have an android phone, but worked with @pecanoro to reproduce this in an android device.

**Comment by joekaufmanexpensify** [comment]
Discussing ideal behavior for how this should work [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664563787011049?thread_ts=1663792588.717789&cid=C01GTK53T8Q).

**Comment by joekaufmanexpensify** [comment]
In the meantime, going to pass to engineering to review. Also, based on this [post](https://expensify.slack.com/archives/C01GTK53T8Q/p1664378120241209?thread_ts=1663792588.717789&cid=C01GTK53T8Q), whatever solution we do decide on is going to be on hold pending completion of this [issue](https://github.com/Expensify/Expensify/issues/221853).

**Comment by MariaHCD** [comment]
Demoting priority and adding to project: https://github.com/Expensify/App/projects/2

**Comment by tjferriss** [comment]
I'm not able to reproduce this on web staging (v1.2.18-2) or on my iPhone app (v1.2.15-3). I am successfully taken back to the previous step. Are we sure this is still broken?

**Comment by Puneet-here** [comment]
Hi @tjferriss, it's still reproducible. You have to repro this on Android and you will need to press native back button.

**Comment by tjferriss** [comment]
@MariaHCD I'm looking for your advice here based on your [previous comments](https://github.com/Expensify/App/issues/11429?notification_referrer_id=NT_kwDOAH6I0rI0NTA0NjMwMDI0OjgyOTI1NjI#issuecomment-1265419232). If this is still reproducible should I toss it back into the engineering pool?

**Comment by MariaHCD** [comment]
@tjferriss I see that it is reproducible if you use the native back button on an Android device. However, I don't believe we have a solution for this yet and should continue to remain on hold as part of https://github.com/Expensify/App/issues/11768. I think there's no need for another engineer to take a look at this.

**Comment by tjferriss** [comment]
Ok we'll hold on for now :)

**Comment by tjferriss** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Snagging this now that I'm on the tracking issue.

**Comment by JmillsExpensify** [comment]
Still on hold for the tracking issue.

**Comment by JmillsExpensify** [comment]
Thanks Melvin, though we're still on hold as noted above. Adding the weekly label instead.

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Still held as we go through the design process.

**Comment by JmillsExpensify** [comment]
On hold per the larger react navigation initiative.

**Comment by JmillsExpensify** [comment]
Still on hold for the larger navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation.

**Comment by JmillsExpensify** [comment]
Held on navigation revamp.

**Comment by JmillsExpensify** [comment]
Switching out weekly for monthly given that the navigation project is large and has no defined ETA.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation reboot.

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by JmillsExpensify** [comment]
Coming off hold very soon!

**Comment by JmillsExpensify** [comment]
Working on testing this week.

**Comment by JmillsExpensify** [comment]
Still trying to make time. Low priority.

**Comment by JmillsExpensify** [comment]
@Puneet-here do you mind re-testing this one and confirming that it's no longer an issue? At that point we can pay you for reporting the issue.

**Comment by Puneet-here** [comment]
It's still reproducible.

**Comment by JmillsExpensify** [comment]
Thanks! @mountiny is the BBA flow potentially a special case that we didn't cover for the react-navigation project? Perhaps just as relevant: What's the expected behavior for a multi-step flow in a modal? Just thinking generally on this, I'm kind of doubting that each step has it's own route, and thus back would correctly close the modal.

**Comment by mountiny** [comment]
Yeah this is because each step is most likely not its own screen. I think however we can close this since this project will probably change this completely https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit?usp=sharing

**Comment by JmillsExpensify** [comment]
Ok cool. I'll still go ahead and pay out @Puneet-here for reporting, since we will fix this.

**Comment by JmillsExpensify** [comment]
Offer sent. Please accept and we can get this closed out @Puneet-here!

**Comment by Puneet-here** [comment]
Accepted!

**Comment by JmillsExpensify** [comment]
All paid out! Thank you, have a great weekend.
