### ISSUE TITLE
 Compose box not consistent when user edit comment after reopen chat reported by @Github.com/dimasna

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to chat (Concierge)
2. Add a comment
3. Edit and leave it empty (here main compose box disappear)
4. Refresh the page with go back and open the chat again (here edit comment still exist with main compose box)

## Expected Result:
compose box consistent appear/disappear when user edit comment after reopen chat

## Actual Result:
compose box not consistent appear/disappear when user edit comment after reopen chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.9-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193063627-3dfc42eb-d9db-4d08-92af-155011255eef.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Github.com/dimasna
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663246445709649
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Hmm not sure I agree that the edit should go away?

**Comment by AndrewGable** [comment]
Closing until I hear more!
