### ISSUE TITLE
Shows error message in English while selected language is Español reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Preferences
2. Change language to Española
3. Click on + icon > new chat
4. Type any random number
5. Check error message

## Expected Result:
Error message should be in Española

## Actual Result:
Error message shows in English

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/193105151-5cb8d50d-2752-4e8d-9bbe-67f6f04179c2.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663327900607679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
The message is from the backend, there are more issues like this and I think they will be handled together. I vote to close this  issue. For more info: https://github.com/Expensify/App/issues/8714#issuecomment-1111163015 

cc: @tgolen
