### ISSUE TITLE
Web - Chat - Sending a message of exactly 60000 characters shows an error Auth CreateReportAction returned an error. @Tushu17

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11432]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Go to chat
3. Send a message of 60000 characters.

## Expected Result:
t shouldn't show any error as the limit is 60000 characters.

## Actual Result:
It shows an error Auth CreateReportAction returned an error and user can't delete that message from chat.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193107602-202336a1-fd46-4bbd-9a4e-c90b5a6c4475.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Tushu17

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1663249840530639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Crafted a message with exactly 60,000 characters:

![image](https://user-images.githubusercontent.com/59587260/193192045-f3e8ae16-2b7d-4c24-92c5-63db33b8e23a.png)
![image](https://user-images.githubusercontent.com/59587260/193192053-f28f9d5b-470b-469c-ad77-9a6ea1808856.png)

Reproduced this error:

![image](https://user-images.githubusercontent.com/59587260/193192033-792aa0c4-170c-45fe-8af2-452c1ddb2423.png)

**Comment by pecanoro** [comment]
Hmm, interesting, by checking the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22752a4d0b6bdba882-SJC%22)+AND+timestamp:[2022-09-30T03:44:01.603Z+TO+2022-09-30T05:44:01.603Z]&index=logs_expensify-018809), I see `Exceeded maximum allowed size of message. Size: 61332, max: 60000`. I think this is due to the message having some line breaks and such that add to the number of characters.

**Comment by pecanoro** [comment]
Discussing it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664559337865919).

**Comment by pecanoro** [comment]
Still discussing this, I will close the convo tomorrow so we can decide on a specific solution.

**Comment by pecanoro** [comment]
There is no straightforward solution to this problem since there is metadata we need to store along the message, but we decided to cut the limit to 15k since there is no reason why we should allow messages as long as 15 pages.

**Comment by Tushu17** [comment]
Reporting compensation is pending here. 
cc- @pecanoro @kadiealexander

**Comment by pecanoro** [comment]
@kadiealexander Could you create a job in Upwork to pay for reporting the bug?

**Comment by kadiealexander** [comment]
https://www.upwork.com/ab/applicants/1585807723520548864/job-details
https://www.upwork.com/jobs/~013c1ccce08cdae51d

@Tushu17 I've sent you an Upwork contract, could you please let me know when it's accepted and I'll issue your reporting bonus? Thanks!

**Comment by Tushu17** [comment]
@kadiealexander Offer accepted, Thanks!

**Comment by kadiealexander** [comment]
Done! Thanks Tushar :)
