### ISSUE TITLE
[$250] [Performance] MainDrawer re-renders unnecessarily reported by @vladamx

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#11447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

inefficient React component rendering

## What is the impact of this on end-users?

slightly slower speeds to render a report

## List any benchmarks that show the severity of the issue

**Before**

Timing:expensify.cash.switch_report.cold 222
Timing:expensify.cash.switch_report.cold 210
Timing:expensify.cash.switch_report.cold 222

## Proposed solution (if any)

Prevent the Main drawer from re-rendering by only allowing it to re-render if we do not yet have the initial params.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

**After** 

Timing:expensify.cash.switch_report.cold 176
Timing:expensify.cash.switch_report.cold 190
Timing:expensify.cash.switch_report.cold 175

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:** 1.2.9-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Upwork URL:** https://www.upwork.com/jobs/~01c2ba78197b3488bc
**Reported by**: @vladamx 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by marcaaron** [comment]
This was reported by @vladamx so I think we should give them first dib on this.

**Comment by trjExpensify** [comment]
Sounds good! Job is on Upwork here: https://www.upwork.com/jobs/~01c2ba78197b3488bc

**Comment by vladamx** [comment]
## Intro
MainDrawerNavigator calculates initial report to open and therefore subscribes to _reports_ which can change many times during the lifecycle of the app even though the data is only needed initially - on app launch. 

**Profiling done below is just for the use case when user is adding a message to any _report_ where you can see the savings of around 120ms only for the add message to chat.** 

Greater savings are achieved if you take into account all mutations that can happen on reports.

### Profiling - Before
<img width="926" alt="Screenshot 2022-09-30 at 13 46 50" src="https://user-images.githubusercontent.com/11381171/193264408-55445ee3-e3ca-40cc-96e2-c717769b733f.png">
<img width="926" alt="Screenshot 2022-09-30 at 13 46 37" src="https://user-images.githubusercontent.com/11381171/193264412-5b53aa17-bc4d-429d-b896-348714488544.png">
<img width="926" alt="Screenshot 2022-09-30 at 13 46 06" src="https://user-images.githubusercontent.com/11381171/193264413-75546a3b-4317-475b-9c3e-f7a0e331c9a4.png">

As you can see MainDrawer is re-rendered 3 times during adding a message to chat with a penalty of 3 * 42.5ms = 127.5ms

### Profiling - After memoization on initialReport calculation
<img width="926" alt="Screenshot 2022-09-30 at 13 51 34" src="https://user-images.githubusercontent.com/11381171/193264678-33c9438e-7f21-4077-9def-17fc266f5abc.png">
<img width="926" alt="Screenshot 2022-09-30 at 13 51 26" src="https://user-images.githubusercontent.com/11381171/193264679-1ab34e2a-9a4b-4c8b-9ee6-b6f464ecff82.png">
<img width="926" alt="Screenshot 2022-09-30 at 13 51 15" src="https://user-images.githubusercontent.com/11381171/193264680-479bbc4f-25f0-4083-9ca4-2625e70cbd4c.png">

3 x 0.5 ms = 1.5ms

So we  achieved savings of 126ms of render time only for adding new message which is significant when you take into account how small render budget is.

**Comment by vladamx** [comment]
Proposal sent to Upwork. 

PR 1.10.2022

**Comment by trjExpensify** [comment]
Hired! 🎉

**Comment by vladamx** [comment]
PR: https://github.com/Expensify/App/pull/11506#issuecomment-1264426694

**Comment by trjExpensify** [comment]
PR is in active review.

**Comment by trjExpensify** [comment]
C+ reviewed. Over to @deetergp now and we should be good to go!

**Comment by trjExpensify** [comment]
Deployed to staging. Once it hits prod, the payout clock begins! 🎉

**Comment by vladamx** [comment]
Am I eligible for reporting bonus as well?

**Comment by trjExpensify** [comment]
Yep! When I go to pay you out, I'll add that.

**Comment by trjExpensify** [comment]
Yeah, interesting. Any idea why the title didn't update with the payment date? 

@vladamx - paid + reporting bonus. 
@rushatgabhane - sent you the offer.

**Comment by trjExpensify** [comment]
Gotcha. Alrighty, all settled up here. Thanks everyone! 🎉
