### ISSUE TITLE
[Performance] Remove `withOnyx()` subscription in `ReportActionItem`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#11440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

inefficient React component rendering

## What is the impact of this on end-users?

Slow to render chat. Takes more time to appear.

## List any benchmarks that show the severity of the issue

Each `ReportActionItem` needs to retrieve data for the `blockedFromConcierge` key which can add significant overhead when rendering many comments in a chat.

## Proposed solution (if any)

Like we did with the report action drafts we can use Context API for these subscriptions and it will have a slight impact on chat switching times.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

**Before**

Timing:expensify.cash.switch_report.cold 231
Timing:expensify.cash.switch_report.cold 223
Timing:expensify.cash.switch_report.cold 214

**After** 

Timing:expensify.cash.switch_report.cold 171
Timing:expensify.cash.switch_report.cold 206
Timing:expensify.cash.switch_report.cold 191

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:** 1.2.9-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment]
Much needed change.

**Comment by marcaaron** [comment]
Oh that's a good point though. There might be some subscriptions like this in the context menu...

**Comment by marcaaron** [comment]
Yep there's a subscription to `betas` here:

https://github.com/Expensify/App/blob/b058975f68c53904a9724d1ccccb265f451f3649/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L74-L78

I bet we can improve that as well.
