### ISSUE TITLE
Native - Cannot get rid of error message when X button is pressed when we try to send an unsupported attachment reported by @dhairyasenjaliya 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any conversation
2. Try to send unsupported attachment (For E.g: .heic , .tiff)
3. Notice Upload Attachment error
4. Try to dismiss error by press X icon
5. Notice we can’t press or remove error

## Expected Result:
On press X icon should remove error message

## Actual Result:
Nothing happens On press X icon

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** v1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/193158618-9e705792-df0e-482d-94df-6b60b2364f4f.MP4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664269061152669
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment]
Posted in slack to find the correct way forward. Use [this link](https://expensify.slack.com/archives/C03TQ48KC/p1664545297622469) to join the conversation.

**Comment by Justicea83** [comment]
This is internal, so I'll take it

**Comment by Justicea83** [comment]
Investigating more today!

**Comment by dhairyasenjaliya** [comment]
hello, @Justicea83 reporting Upwork job missing here might need to add the appropriate label!

**Comment by Justicea83** [comment]
Hey @dhairyasenjaliya I took this one. No need for an upwork job!

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~01ccec92f2ed873595 job created - please apply @dhairyasenjaliya

**Comment by dhairyasenjaliya** [comment]
@zanyrenney milestone received but need to close job as complete on upwork

**Comment by zanyrenney** [comment]
Paid!

**Comment by Justicea83** [comment]
Thanks Zany
