### ISSUE TITLE
[HOLD #11768] - Pressing X closes the chat in mobile web reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to concierge > Tap on call icon
2. Press X

## Expected Result:
Request call page should close

## Actual Result:
The chat also closes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195627070-ebda43df-6928-4cd7-b1cc-a3274d6073d2.mp4

https://user-images.githubusercontent.com/43996225/195627144-73dd663c-86c1-40c1-b650-62c882f09927.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664280561381979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal

Just pasting my proposal here from the slack thread

Remove true from the lines below
https://github.com/Expensify/App/blob/c942b3e3eb788a52b06f3e97d8c8312bd4a60c8f/src/pages/NewChatPage.js#L220
https://github.com/Expensify/App/blob/c942b3e3eb788a52b06f3e97d8c8312bd4a60c8f/src/pages/RequestCallPage.js#L255
https://github.com/Expensify/App/blob/c942b3e3eb788a52b06f3e97d8c8312bd4a60c8f/src/pages/SearchPage.js#L175

**Comment by michaelhaxhiu** [comment]
@kavimuru can you re-upload your video please?

**Comment by michaelhaxhiu** [comment]
Once we get a video, I'll add this to https://github.com/Expensify/App/issues/11768

**Comment by kavimuru** [comment]
@michaelhaxhiu added new videos

**Comment by michaelhaxhiu** [comment]
Nice, thank you!

**Comment by puneetlath** [comment]
Jason will be the BZ person for navigation issues, so assigning to him.

**Comment by JmillsExpensify** [comment]
Still on hold. I've updated the title to clarify where to look for updates related to the larger initiative.

**Comment by JmillsExpensify** [comment]
Still holding on the linked initiative. Also commented there to align on game plan and next steps.

**Comment by JmillsExpensify** [comment]
Still on hold Melvin.

**Comment by JmillsExpensify** [comment]
Still held as we go through the design process.

**Comment by JmillsExpensify** [comment]
On hold per the larger react navigation initiative.

**Comment by JmillsExpensify** [comment]
Still on hold for the larger react navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation.

**Comment by JmillsExpensify** [comment]
Held on navigation revamp.

**Comment by JmillsExpensify** [comment]
Switching out weekly for monthly given that navigation project is larger and has no defined ETA.

**Comment by JmillsExpensify** [comment]
Still hold on the navigation reboot.

**Comment by JmillsExpensify** [comment]
Same same.

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Coming off hold very soon!

**Comment by JmillsExpensify** [comment]
Working on testing this week.

**Comment by JmillsExpensify** [comment]
So for this one, we ended up deprecating this flow. Given that we accepted this bug at the time, I'm going to award the bug bounty.

**Comment by JmillsExpensify** [comment]
@Puneet-here Offer sent. Please let me know when you've accepted and we'll get this one paid out.

**Comment by Puneet-here** [comment]
Accepted!

**Comment by JmillsExpensify** [comment]
Thanks! Offer paid.
