### ISSUE TITLE
[$250] Dev - dev console error on Reimburse expenses page reported by @aimane-chnaif

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Login to any account

1. Go to Settings
2. Go to any workspace detail
3. Tap "Reimburse expenses" item

## Expected Result:
No console error

## Actual Result:
Console error:  Warning: Failed prop type: The prop `policyID` is marked as required in `WorkspaceReimburseView`, but its value is `undefined`.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1038" alt="web" src="https://user-images.githubusercontent.com/43996225/193160904-1e6755f0-bc8b-447e-bc82-db379e4970d5.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663959174170539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
Ok I think I was able to reproduce this one. The app looks fine, but I'm seeing this error in the JS console.

<img width="1109" alt="Screen Shot 2022-10-20 at 2 13 54 PM" src="https://user-images.githubusercontent.com/8292562/197059425-9afc2b3b-dfd5-41c5-ab73-839208c20a1e.png">

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~013bb051933f6848a4)

**Comment by bfitzexpensify** [comment]
Waiting for proposals

**Comment by MahmoudHemaid** [comment]
@bfitzexpensify This issue has been solved in this [commit](https://github.com/Expensify/App/commit/e2336d1c140c4064f8f6b2428dd1c8854f586617). So it's not reproducible now

**Comment by bfitzexpensify** [comment]
Oh, nice! OK, let's close this out then. @aimane-chnaif, I invited you to a reporting job on Upwork, I'll pay that out once you accept.
