### ISSUE TITLE
Profile - Copy option not displayed on long press in save button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #11367 
## Action Performed:
1.Launch the expensify app
2.Log in to any account
3.Go to Settings ->Profile
4.Long press the Save button

## Expected Result:
Notice on long press top header component should not highlight and text can be copied

## Actual Result:
Unable to copy the text and copy option not displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Desktop App

**Version Number:** 1.2.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193154309-eecb7923-30c7-452c-8037-d4a3323ff8b8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Sorry, I am not following this one...

> top header component should not highlight and text can be copied

Which top header component? Which text can be copied?

**Comment by flodnv** [comment]
@kavimuru ?

**Comment by kavimuru** [comment]
@flodnv  This is the PR step 5 of this #11367 which is a fix of #10973. The header "Profile" should not highlight.

**Comment by Julesssss** [comment]
This is not a bug. There is no use case for this and it makes the button worse, as users can accidentally long press instead of just clicking it.
