### ISSUE TITLE
Web - Connect Bank account - User is hitting Onfido flow when connecting BA through the Plaid option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has a Workspace created
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap Profile > Workspace > Connect Bank account
4. Select "Connect with Plaid" and Proceed with the "Fidelity" flow until the end

## Expected Result:
User expects to be able to connect to the bank account through VBA

## Actual Result:
User is hitting Onfido flow when connecting BA through the Plaid option

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.2.10.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193172920-7f0ebf99-e72f-44b8-885c-2bcfd276dcb7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@nkuoch could this possibly be related to https://github.com/Expensify/App/pull/11232 ?
