### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Ensure the page not found error message is properly centered in the chat view

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#11473]
# Problem

In this PR https://github.com/Expensify/App/pull/10452 we've started using the `FullPageNotFoundView` component in the chat view. Seems the component is not quite centered:
![image](https://user-images.githubusercontent.com/521248/193323351-d0318284-f3da-464e-93d3-da2e5ce54596.png)

# Solution

Investigate why (either due to the header or because the centering is optimized for the sidebar) and fix it

**Comment by dhairyasenjaliya** [comment]
**Proposal**

**Cause**
- Currently component is not quite center just because we have two components (HeaderWithCloseButton + BlockingView)
- As  BlockingView is already centered but due to HeaderWithCloseButton component height, combining both components does not get actually centered view

**Fix**

- In order to fix centered `<BlockingView/>` we need to add paddingBottom same height as HeaderWithCloseButton height
- here in below `<View>` component we need to add `paddingBottom: variables.contentHeaderHeight` 
https://github.com/Expensify/App/blob/607f8e936a28a774a600c2185d66da5d9479e88c/src/components/BlockingViews/FullPageNotFoundView.js#L58-L64

**Result**

<img width="1440" alt="Fix" src="https://user-images.githubusercontent.com/47522946/193344853-db418e6d-c44b-45f5-ba54-722a300efb61.png">

**Comment by chauchausoup** [comment]
**Proposall**:

**Cause** : With reference to View, BlockingView is centered but with presence of HeaderWithCloseButton the parent DOM is not centered. 
**Solution**:
We can enforce centerStyle wrapper that will center any component with respect to the browser DOM despite the associated components. Such wrapper can come handy in later stages of development too.

Wrapper CSS:
````
    centerStyle: {
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
    },
    ```
   Add this style to View Component as 
   
`                   <View style={[styles.flex1, styles.centerStyle]}>`

Before the wrapper:

<img width="1680" alt="Screen Shot 2022-10-01 at 12 29 06" src="https://user-images.githubusercontent.com/34975245/193397058-51ab884f-4d1c-4708-acd6-4b3628b1792e.png">

After the wrapper:

<img width="1680" alt="Screen Shot 2022-10-01 at 12 28 58" src="https://user-images.githubusercontent.com/34975245/193397046-b934b51b-ef56-4094-8c8f-790b60115d67.png">

**Comment by sketchydroide** [comment]
not overdue, we are still receiving proposals

**Comment by eVoloshchak** [comment]
@chauchausoup's [proposal](https://github.com/Expensify/App/issues/11473#issuecomment-1264267931) messes with the layout a bit (subtitle is broken into two lines instead of one) and, most importantly, crashes on mobile platforms

**Comment by sketchydroide** [comment]
sorry, assigned the wrong person initially, fixed that now, thanks @eVoloshchak, assgined @dhairyasenjaliya

**Comment by MitchExpensify** [comment]
[Upwork Job](https://www.upwork.com/jobs/~019cf93d72153690d1)

**Comment by dhairyasenjaliya** [comment]
will create PR soon :)

**Comment by dhairyasenjaliya** [comment]
PR is ready but it needs to have QA steps, bit confused about what steps should I add in order to generate a page not found error can you do you have any suggestions regarding that @eVoloshchak @sketchydroide

**Comment by eVoloshchak** [comment]
> PR is ready but it needs to have QA steps, bit confused about what steps should I add in order to generate a page not found error can you do you have any suggestions regarding that @eVoloshchak @sketchydroide

I think https://github.com/Expensify/App/pull/10452 contains the necessary steps

**Comment by dhairyasenjaliya** [comment]
QA steps updated thank you,PR ready for review :) @eVoloshchak

**Comment by MitchExpensify** [comment]
Paid @dhairyasenjaliya 

[Offer sent here](https://www.upwork.com/ab/applicants/1583172157784010752/job-details) @eVoloshchak

**Comment by MitchExpensify** [comment]
Paid all!
