### ISSUE TITLE
iOS - Extra space appears beneath message when chatting with concierge

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11476]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Concierge chat 
2. Receive message from concierge 
3. respond to the message 

## Expected Result:
There should be no extra blank spaces 

## Actual Result:
Blank space displayed between messages 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.5-0
**Reproducible in staging?:** need repro.  (few users reported it, but we are not able to repro. not sure if it depends on type of the messages) 
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![File (3)](https://user-images.githubusercontent.com/43995119/193341128-47541032-1b30-41e5-9742-5aa25ee7da9b.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664330336672539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
If anyone can lay out consistent reproduction steps we're considering paying a bounty as an experiment on this issue

**Comment by MitchExpensify** [comment]
Still waiting on consistent reproduction steps

**Comment by MitchExpensify** [comment]
[Looking at this SO](https://stackoverflow.com/c/expensify/questions/14418) @puneetlath, am I right in saying the "Needs reproduction" label is prompting Applause or is that on me? Not 100% sure

**Comment by puneetlath** [comment]
@MitchExpensify I think the move would be to assign it back to the issue reporter (in this case @roryabraham) and close the issue.
