### ISSUE TITLE
[HOLD for payment 2022-11-24] [$250] [Feature Request] [mWeb] - Remove email hyperlink in user details page reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem: 
The email is shown as normal text but clicking on it opens the email at gmail app

## Solution: 
Remove the hyperlink from the text to match web. Discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665168495433459?thread_ts=1664289824.630449&cid=C01GTK53T8Q). We don't really need this text to be a hyperlink when we have the clipboard and would prefer to match web.

## Action Performed:

1. Open mWeb/Ios/Android
2. Go to chat
3. Go to profile detail page click on email

## Expected Result:
Email shouldn't be an hyperlink in any platform

## Actual Result:
It is behaving as hyperlink in mobile.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/193368987-2c345843-6f94-46fb-a65c-f504ba2f1f92.mov
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664293277801499?thread_ts=1664289824.630449&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~019bd31e40927b679d
- Upwork Job ID: 1595514548715728896

**Comment by varshamb** [comment]
###Proposal

Add styles.link or styles.textBlue and may be we can change cursor also.


https://github.com/Expensify/App/blob/2bef1705d5aac60c9463cc0f080155dc9925d033/src/
pages/DetailsPage.js#L155

**Comment by Puneet-here** [comment]
### Proposal

This is only hyperlink at small screen so we don't wanna show it as blue on big screen when there's no functionality so I propose we use `withWindowDimensions` to get screenWidth and use `this.props.isSmallScreenWidth` to decide when to display text as blue
https://github.com/Expensify/App/blob/9ff60c3a220c9d05001007b2c0dfe0d954623edb/src/pages/DetailsPage.js#L145
 ```js 
<Text numberOfLines={1} style={this.props.isSmallScreenWidth ? styles.textBlue : {}}>
```
but because this will still be shown as hyperlink at desktop in decreased screen state, so I prefer using `canUseTouchScreen()` (or We can use `this.props.isSmallScreenWidth` and `canUseTouchScreen()` together)

We will use the same condition here as well https://github.com/Expensify/App/blob/9ff60c3a220c9d05001007b2c0dfe0d954623edb/src/components/CommunicationsLink.js#L45-L47

**Comment by tjferriss** [comment]
These links appear to be imposed on us by the mobile OS. We don't have links on web. I also don't think we want to highlight this "feature" so I'm inclined to close this issue and do nothing for now.

**Comment by tjferriss** [comment]
@Puneet-here has pointed out that we're actually applying these links ourselves. You can find it [here](https://github.com/Expensify/App/blob/a7203176e8521474197b428eb1c4e28f3cf4e4cb/src/pages/DetailsPage.js#L150). My suggestion would be to standardize on the web approach and eliminate this link on mobile rather than highlight it blue.

**Comment by tjferriss** [comment]
Forgot to add `engineering` last week. Got it now. I also updated the OP to reflect the new solution to remove the hyperlink from the text on mobile.

**Comment by aldo-expensify** [comment]
Confirming in the [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1665704579577719?thread_ts=1664289824.630449&cid=C01GTK53T8Q) what was the desired behaviour

**Comment by aldo-expensify** [comment]
@Santhosh-Sellavel the second part of @Puneet-here 's proposal seems to be going toward the updated expected outcome of the issue.

**Comment by aldo-expensify** [comment]
@Santhosh-Sellavel opened a discussion on slack about this: https://expensify.slack.com/archives/C01GTK53T8Q/p1666027750882039?thread_ts=1664289824.630449&cid=C01GTK53T8Q

No other updates

**Comment by aldo-expensify** [comment]
@CortneyOfstad I understand that the vote resolved to do option 1️⃣  which would be to remove the hyperlink from the email when on mobile to have consistency across platforms. The next steps would be:

- Create the Upwork job
- @Santhosh-Sellavel has to review the proposed solutions. I think the only one to review is @Puneet-here solution [here](https://github.com/Expensify/App/issues/11487#issuecomment-1264475393) (the second part)

**Comment by aldo-expensify** [comment]
@CortneyOfstad please HOLD, I'm asking @JmillsExpensify opinion since @Santhosh-Sellavel still thinks it may be better to do nothing.

**Comment by Santhosh-Sellavel** [comment]
This can come off hold @CortneyOfstad.

@Puneet-here Can you submit an updated proposal again please include a screenshot before and after the new change. 

Thanks!

cc: @aldo-expensify

**Comment by CortneyOfstad** [comment]
@Santhosh-Sellavel Sounds good! I'll get the Upwork job created right away tomorrow morning 👍 Thanks for the heads up!!

**Comment by CortneyOfstad** [comment]
Job created! — https://www.upwork.com/ab/applicants/1583103833177513984/job-details

**Comment by Puneet-here** [comment]
### Proposal
At Details page instead of the [CommunicationsLink](https://github.com/Expensify/App/blob/70efb00eeb6e9617ecfa478e6348a252d4ac13f4/src/pages/DetailsPage.js#L155) I will use `CopyTextToClipboard` 
Here's the changes we need -
at [DetailsPage.js](https://github.com/Expensify/App/blob/main/src/pages/DetailsPage.js)

```diff
                                 {details.login ? (
                                     <View style={[styles.mb6, styles.detailsPageSectionContainer, styles.w100]}>
-                                        <Text style={[styles.formLabel, styles.mb2]} numberOfLines={1}>
+                                        <Text style={[styles.formLabel, styles.mb1]} numberOfLines={1}>
                                             {this.props.translate(isSMSLogin
                                                 ? 'common.phoneNumber'
                                                 : 'common.email')}
                                         </Text>
-                                        <CommunicationsLink
-                                            type={isSMSLogin ? CONST.LOGIN_TYPE.PHONE : CONST.LOGIN_TYPE.EMAIL}
-                                            value={isSMSLogin ? getPhoneNumber(details) : details.login}
-                                        >
-                                            <Tooltip text={isSMSLogin ? getPhoneNumber(details) : details.login}>
-                                                <Text numberOfLines={1}>
-                                                    {isSMSLogin
-                                                        ? this.props.toLocalPhone(getPhoneNumber(details))
-                                                        : details.login}
-                                                </Text>
-                                            </Tooltip>
-                                        </CommunicationsLink>
+                                        <CopyTextToClipboard
+                                            text={isSMSLogin ? getPhoneNumber(details) : details.login}
+                                            iconSize={variables.iconSizeNormal}
+                                            textStyles={styles.mr2}
+                                        />
                                     </View>
```
at [CopyTextToClipboard.js](https://github.com/Expensify/App/blob/main/src/components/CopyTextToClipboard.js)

```diff
 
+    /** Size of cliboard icon */
+    iconSize: PropTypes.number,
+
     ...withLocalizePropTypes,
 };
 
 const defaultProps = {
     textStyles: [],
+    iconSize: variables.iconSizeSmall,
 };
 
 class CopyTextToClipboard extends React.Component {
@@ -63,8 +67,8 @@ class CopyTextToClipboard extends React.Component {
                     <Icon
                         src={this.state.showCheckmark ? Expensicons.Checkmark : Expensicons.Clipboard}
                         fill={this.state.showCheckmark ? themeColors.iconSuccessFill : themeColors.icon}
-                        width={variables.iconSizeSmall}
-                        height={variables.iconSizeSmall}
+                        width={this.props.iconSize}
+                        height={this.props.iconSize}
                         inline
                     />
                 </Tooltip>
```
We need to change the clipboard icon size so I have added a new prop.

Before -
<img width="797" alt="Screenshot 2022-10-24 at 2 55 06 AM" src="https://user-images.githubusercontent.com/101883770/197419009-5a72318c-8aa0-4b90-a3bc-c0737a6c8705.png">

After -
<img width="797" alt="Screenshot 2022-10-24 at 2 55 21 AM" src="https://user-images.githubusercontent.com/101883770/197419019-be6bb90c-c89f-496b-bf72-d299d22c55d5.png">

Observe that the Clipboard icon is inline with the text like at Reimburse expenses page. I am not making other changes to keep it in the center because it will break the text position at Reimburse expenses page

The icon has position absolute when we pass the prop `inline` and we use `IconWrapperStyles` to keep it inline with the text if we want it in the center then we can create a new prop to pass different value 
https://github.com/Expensify/App/blob/70efb00eeb6e9617ecfa478e6348a252d4ac13f4/src/components/Icon/index.js#L51

**Comment by Santhosh-Sellavel** [comment]
@Puneet-here Let's maintain the design as its already, can you send the updated proposal thanks!

**Comment by Puneet-here** [comment]
If we wanna keep the design same then let's just remove the hyperlink logic and keep using `CommunicationsLink` 

```diff
--- a/src/components/CommunicationsLink.js
+++ b/src/components/CommunicationsLink.js
@@ -1,14 +1,11 @@
 import React from 'react';
-import {View, Pressable, Linking} from 'react-native';
+import {View} from 'react-native';
 import PropTypes from 'prop-types';
 import styles from '../styles/styles';
-import compose from '../libs/compose';
 import * as Expensicons from './Icon/Expensicons';
 import Clipboard from '../libs/Clipboard';
 import ContextMenuItem from './ContextMenuItem';
 import withLocalize, {withLocalizePropTypes} from './withLocalize';
-import withWindowDimensions, {windowDimensionsPropTypes} from './withWindowDimensions';
-import CONST from '../CONST';
 
 const propTypes = {
     /** Children to wrap in CommunicationsLink. */
@@ -18,13 +15,9 @@ const propTypes = {
     // eslint-disable-next-line react/forbid-prop-types
     containerStyles: PropTypes.arrayOf(PropTypes.object),
 
-    /** Decides Tap behaviour. */
-    type: PropTypes.oneOf([CONST.LOGIN_TYPE.PHONE, CONST.LOGIN_TYPE.EMAIL]).isRequired,
-
     /** Value to be copied or passed via tap. */
     value: PropTypes.string.isRequired,
 
-    ...windowDimensionsPropTypes,
     ...withLocalizePropTypes,
 };
 
@@ -42,18 +35,7 @@ const CommunicationsLink = props => (
         ]}
         >
             <View style={styles.flexShrink1}>
-                {props.isSmallScreenWidth
-                    ? (
-                        <Pressable
-                            onPress={() => Linking.openURL(
-                                props.type === CONST.LOGIN_TYPE.PHONE
-                                    ? `tel:${props.value}`
-                                    : `mailto:${props.value}`,
-                            )}
-                        >
-                            {props.children}
-                        </Pressable>
-                    ) : props.children}
+                {props.children}
             </View>
             <ContextMenuItem
                 icon={Expensicons.Clipboard}
@@ -72,7 +54,4 @@ CommunicationsLink.propTypes = propTypes;
 CommunicationsLink.defaultProps = defaultProps;
 CommunicationsLink.displayName = 'CommunicationsLink';
 
-export default compose(
-    withWindowDimensions,
-    withLocalize,
-)(CommunicationsLink);
+export default withLocalize(CommunicationsLink);
```

**Comment by Santhosh-Sellavel** [comment]
Looks Good! @aldo-expensify

**Comment by aldo-expensify** [comment]
Yes, that looks good for me too

**Comment by aldo-expensify** [comment]
Friendly bump @Puneet-here , when do you think we can have a PR?

**Comment by Puneet-here** [comment]
Really sorry I missed the notification. I will raise the PR today.

**Comment by aldo-expensify** [comment]
Thanks!

**Comment by Puneet-here** [comment]
I have raised the PR.

**Comment by aldo-expensify** [comment]
PR merged

**Comment by CortneyOfstad** [comment]
Hello! I got an email from UpWork that the job posting for this is about to expire. Is there any additional action that needs to be taken, or do I let it expire?

This is my first time coming across this, so reaching out for clarification.

**Comment by JmillsExpensify** [comment]
@CortneyOfstad I'd take that question to #bug-zero.

**Comment by CortneyOfstad** [comment]
Asking for clarification [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1669124393385879)

**Comment by CortneyOfstad** [comment]
Since the old job essentially expired, recreated it, based on the suggested provided in Slack — https://www.upwork.com/jobs/~01c0b57325bd142204

**Comment by CortneyOfstad** [comment]
@Puneet-here and @Santhosh-Sellavel I sent over the contract in UpWork for this. @Puneet-here will get double due to both reporting and prosing the fix for this issue 👍 

Also, I have to unassign this for it to be paid tomorrow, as Nov. 24 is Thanksgiving and I am OoO. Thanks!

**Comment by Puneet-here** [comment]
Accepted the offer, thanks!

**Comment by JmillsExpensify** [comment]
I'll handle this since @arielgreen recently helped me with something and I happen to be online to pay out by contributors now. Both @Puneet-here and @Santhosh-Sellavel have been paid out!

**Comment by JmillsExpensify** [comment]
I've also just closed the duplicate Upwork job that was just created by removing and re-applying the `External` label.
