### ISSUE TITLE
[$250] [Bug] Clean up confusing logic for when a report is exempt from being filtered out of the LHN

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#11481]
# Problem
Coming from https://github.com/Expensify/App/pull/10863#discussion_r975881233

The logic there is confusing and difficult to reason about.

# Why is this important?
This makes the code hard to maintain.

# Solution
Simplify and extract the logic to a separate method or break down the logic into several easier-to-read booleans.

**Comment by tgolen** [comment]
@JmillsExpensify can we get a C+ review for this, please?

**Comment by JmillsExpensify** [comment]
Created the Upwork here: https://www.upwork.com/jobs/~01f59be4a13ee28103

**Comment by JmillsExpensify** [comment]
Wait, @tgolen did we have a C+ review on this PR? I created an Upwork job but I'm not seeing any review in the linked PR.

**Comment by parasharrajat** [comment]
No it was merged before that.

**Comment by JmillsExpensify** [comment]
Cool. I'll close out the Upwork then, thank you!
