### ISSUE TITLE
[Bug] Incorrect emojis are highlighted reported by @rushatgabhane

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open emoji picker
2. Type “a” in search
3. Try to hover first row of emojis.

## Expected Result:
Correct hovered emoji is highlighted

## Actual Result:
Incorrect emojis are highlighted

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193377770-ff048c9a-08c3-4ba3-aa26-74488895590c.mp4
https://user-images.githubusercontent.com/43996225/193377763-8657c33a-b4f7-4436-b966-08a9e8729227.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664435639605849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
The hover is off, but the emoji selection is accurate. I'm gonna close this as low value but we may reopen in the future!
