### ISSUE TITLE
BUG: Multiple workspaces generated in web once created from IOS and web at the same time reported by @chauchausoup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a workspace from web and IOS at the same time

## Expected Result:
Single workspace should have been created

## Actual Result:
Multiple workspace are being created

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS

**Version Number:** 1.2.11-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193432794-90ad35b1-c30c-4019-8225-53b444f3f476.mov
https://user-images.githubusercontent.com/43996225/193432800-efbfbad3-589a-4bc0-9a70-15a8daf957a1.MP4
https://user-images.githubusercontent.com/43996225/193432806-b90481cb-713f-4d98-9dda-98c683a91edd.mp4
<img src="https://user-images.githubusercontent.com/43996225/193432837-ce4b9bca-1b61-4ee6-a00c-b9dc2697a72b.PNG" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/193432839-e692f45e-183d-4a2d-b7df-ef92b526b7dd.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664619300782149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by madmax330** [comment]
Discussed here: https://expensify.slack.com/archives/C03TQ48KC/p1664968493411569

This is a feature, not a bug because you're allowed to have more than one workspace

**Comment by chauchausoup** [comment]
@madmax330 if you look into the original slack issue reporting video record then the actual issue is found. You can see multiple (in my instance 3) workspace being generated after a delay when workspace creation is clicked at the same time in two platforms.
