### ISSUE TITLE
Connect Bank Account - Unable to proceed in VBA flow after change the correct account number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11026

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Workspace - Connect Bank account
4. Click connect manually and use 011401533 as routing number and 011401533 as account number
5. Turn off wifi
6. Verify that the Save & continue button is disabled (and that you see the offline message below the button on mobile)
7. Turn on wifi
8. Click Save and Continue ( you will receive the error message about routing and account number should not be the same)
9. Now update the account number to 1111222233331111
10. Click Save and Continue
11. The fields in the Company information step should be filled out
12. Tap Save & continue

## Expected Result:
Able to proceed in VBA flow after change the correct account number

## Actual Result:
Error message is appeared, unable to proceed in VBA flow after change the correct account number

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193423681-e15504ea-99d6-4450-a1ae-c7f833e7db7e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Keeping this one as Internal, as it may be refactor-related
