### ISSUE TITLE
mWeb/Safari -The PDF file cannot be viewed when the user is offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/w323052760We
2. Login with applausetester+0704sveta@applause.expensifail.com
3. Kill the internet connection
4. Navigate the chat
5. Open PDG file in conversation.

## Expected Result:
I can view the PDF file offline

## Actual Result:
The PDF file cannot be viewed when the user is offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0704sveta@applause.expensifail.com/w323052760We

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193455830-18ad2123-03af-443a-8c4a-d8152326b331.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
I don't think there's any expectation to support this, since the larger format would be taxing to store each copy locally.
