### ISSUE TITLE
[HOLD #10894][Image] mWeb/Safari -Settings - Avatar is displayed a grey color when went back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with [applausetester+0704sveta@applause.expensifail.com/w323052760We
3. Kill the internet connection
4. Navigate the chat
5. Go back online

## Expected Result:
Avatar should not displayed with grey color

## Actual Result:
Avatar is displayed a grey color when went back online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.11.1.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0704sveta@applause.expensifail.com/w323052760We

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193423873-2d18b22e-e168-4006-9b01-b040ec38307b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Sorry, which avatar is showing grey?

**Comment by mountiny** [comment]
Waiting fro proposals

**Comment by Beamanator** [comment]
This issue looks very related to the project [Image-related feature request and improvements](https://github.com/Expensify/App/issues/10894#top), I'm going to put this on hold for now & remove `Help Wanted` - sound ok? :D

**Comment by mountiny** [comment]
Nice, thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
@NicMendonca Snaggin' from you cuz I got the tracking issue assigned to me
[Tracking] [Polish] Image-related feature request and improvements #10894

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Are we ok to close this?

**Comment by mountiny** [comment]
Yes, lets close this, thanks!
