### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Payments -  Pressing :x: doesn't dismiss the modal  @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open :expensify: at staging
2. Navigate to settings > Payments
3. Add payment method > Bank account > Go through the flow
4. Select bank account> Enter password
5. Click Save & continue button
6. Press :x: at the confirmation screen

## Expected Result:
The RHN should be closed

## Actual Result:
You get navigated to the payments page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193459637-56addbba-e5c5-489b-8674-4d128de08139.mov

https://user-images.githubusercontent.com/93399543/193459652-910a4a9f-182a-4aaa-a647-b2f79b0f7ce9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664222753554019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal                                            
We need to use `Navigation.dismissModal` at `onCloseButtonPress`        https://github.com/Expensify/App/blob/9ff60c3a220c9d05001007b2c0dfe0d954623edb/src/pages/AddPersonalBankAccountPage.js#L133

**Comment by davidcardoza** [comment]
Tested and confirmed on staging, the RHN does not close.

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~01eb5f4bae4147b60c)

Reporting job [here](https://www.upwork.com/jobs/~01d2f79cedd4dcbb61) @thesahindia

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/11518#issuecomment-1264659085) from @Puneet-here looks good to me.

cc: @iwiznia 

🎀👀🎀 C+ reviewed

**Comment by bfitzexpensify** [comment]
Looks like the PR was deployed to staging.

**Comment by Sami-Shafi** [comment]
Proposal: 
Checked the complete code and the onCloseButtonPress prop. We have to make the changes there. We need to put a function that will properly close the modal.

As @Puneet-here 's code didn't work, we have to write a better function. I found another function that will close all the modals and we have to check if that works.

As you mentioned on Upwork, I am not including my code in the proposal and hopefully, we will start working on this and fix it quickly. Thank you.

**Comment by Sami-Shafi** [comment]
Proposal: 
Checked the complete code and the onCloseButtonPress prop. We have to make the changes there. We need to put a function that will properly close the modal.

As @Puneet-here 's code didn't work, we have to write a better function. I found another function that will close all the modals and we have to check if that works.

As you mentioned on Upwork, I am not including my code in the proposal and hopefully, we will start working on this and fix it quickly. Thank you.

**Comment by sobitneupane** [comment]
@Sami-Shafi Thanks for your proposal.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md)

This issue is resolved. You can find other [open jobs here.](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
All payments finalized. Thanks everyone!
