### ISSUE TITLE
Web - Selecting the Autofill popup in Add phone no on Profile page replaces the text in Profile page First name or Last name  @aneequeahmad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch web app.
2. Click on settings > profile > add phone no > click on any text-field.
3. Select autofill popup to autofill the text-input (phone no or password)

## Expected Result:
Shouldn't update text on profile page First name or Last name

## Actual Result:
Updates text on profile page First name or Last name with autofill selected in Phone no page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193470049-01cc1ac1-9f5e-4040-9dfb-b94441461028.mov

https://user-images.githubusercontent.com/93399543/193470069-b5f50256-d90a-4160-bbc4-267d9e9ba900.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664408160844459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
This entire part of the app is being refactored. I'm closing this issue because: 1) it's not a priority; 2) The code in this part of the app is actively being re-written; and 3) The input styles are changing completely.

**Comment by aneequeahmad** [comment]
@JmillsExpensify, Yeah make sense. Could i ask if i'm eligible for reporting bug bonus ?

**Comment by aneequeahmad** [comment]
- Link to bug report : https://expensify.slack.com/archives/C01GTK53T8Q/p1661272228750899
- Bug Reporting time: Aug 23rd at 9:30:28 PM
- Decided [this](https://github.com/Expensify/App/issues/11523#:~:text=on%203%20Oct-,This%20entire%20part%20of%20the%20app%20is%20being%20refactored,-.%20I%27m%20closing%20this) that this part of app should be refactored (3rd Oct, 2022).

cc: @mallenexpensify

**Comment by JmillsExpensify** [comment]
Here's my perspective: The bug report you linked was marked as a dupe when reported, so I don't think that one qualifies. We've also been refactoring this part of the app for quite some time, I simply acted on the bug report when assigned.

**Comment by aneequeahmad** [comment]
@JmillsExpensify Yeah, make sense i didn't know this refactor was already planned and going. 

Thank you for you comment.

**Comment by JmillsExpensify** [comment]
Ok cool, thank you for understading!
