### ISSUE TITLE
[$250] Searching for someone will incorrectly show a contact you've never spoken with (reported by @Puneet-here)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with account A
2. Search account B > Open the chat > Logout
3. Log in with account B
4. Go to search page and try finding user A in the list

## Expected Result:
 User A shouldn't be shown in the contact list at search unless you have talked with them or searched for them

## Actual Result:
User A shows up in contact list at search for account B

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193469550-4370d1a7-b6ed-4dbd-85ec-37a3d772ce43.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664399150196209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~013dfcb838d49a2f0d

**Comment by Santhosh-Sellavel** [comment]
Waiting for proposals seems like might be a backend change to me.

**Comment by tienifr** [comment]
# Proposal

##This issue is updated
- Action Performed: login into User A --> Searching user B --> Logout --> login into user B
- Before: User A only shown in the contact list at search and is not shown in the sidebar
- Now: User A shown in both the contact list at search and the sidebar (see attached evidence)

## Problem
According to the expected result, We only display users whom you have talked with them or searched for them. Now, the data is used in both the contact list at search and the sidebar is getting from Onyx storage and data in Onyx storage is updated by this API: http://localhost:8080/api?command=OpenApp. But this API is returning even those who searched for the user (in the above example: when logging into user B, API: http://localhost:8080/api?command=OpenApp is returning both user A in the key: "report_", see image 1). Although User B didn't search/talk with User A, in response from API still has the report of user A. In addition, when seeing report_A in user B and report_B in User A, we could not distinguish who search who so we can't filter out User A in User B

## Solution
We should update the API in BE so that the API only returns the user whom you have talked with them or searched for them.

## IMAGE 1
<img width="890" alt="Screen Shot 2022-10-06 at 17 02 47" src="https://user-images.githubusercontent.com/113963320/194474119-e0a8af76-78d6-41b5-97fc-3013f43d4719.png">

##EVIDENCE


https://user-images.githubusercontent.com/113963320/194474334-6a521ea3-2c37-424a-9b57-24749dee0c7b.mp4

**Comment by bernhardoj** [comment]
### **Proposal**
I think we can just change `includePersonalDetails` to `false`. We ignore personal details because it does not contain any chat.

_**OptionsListUtils**_
```diff
function getSearchOptions(
    reports,
    personalDetails,
    searchValue = '',
    betas,
) {
    return getOptions(reports, personalDetails, {
        betas,
        searchValue: searchValue.trim(),
        includeRecentReports: true,
        includeMultipleParticipantReports: true,
        maxRecentReportsToShow: 0, // Unlimited
        prioritizePinnedReports: false,
        prioritizeDefaultRoomsInSearch: false,
        sortByReportTypeInSearch: true,
        showChatPreviewLine: true,
        showReportsWithNoComments: true,
-       includePersonalDetails: true,
+       includePersonalDetails: false,
        forcePolicyNamePreview: true,
    });
}
```

### **Result**

https://user-images.githubusercontent.com/50919443/194694322-10c65522-44df-4fb3-b936-25ff69078b87.mp4

**Comment by tienifr** [comment]
# Updated Proposal


## Problem
In list sections that display in the contact list at search, we are taking from 3 states: recentReports, personalDetails, userToInvite in getSections function as below:

```diff
    getSections() {
        const sections = [];

        if (this.state.recentReports.length > 0) {
            sections.push(({
                data: this.state.recentReports,
                shouldShow: true,
                indexOffset: 0,
            }));
        }


        if (this.state.personalDetails.length > 0) {
            sections.push(({
                data: this.state.personalDetails,
                shouldShow: true,
                indexOffset: this.state.recentReports.length,
            }));
        }



        if (this.state.userToInvite) {
            sections.push(({
                undefined,
                data: [this.state.userToInvite],
                shouldShow: true,
                indexOffset: 0,
            }));
        }

        return sections;
    }
```
I see that recentReports contains the sections that user talked with or searched for before, personalDetails contains sections that we do not want to display in the contact list at search like who searched for this user

## Solution
we only need to display sections that user talked or searched before. So we can remove personalDetails from the section list as below
Please view the changed code in this sample PR: https://github.com/tienifr/App/pull/9/

##Result

https://user-images.githubusercontent.com/113963320/194824370-83bdfe0a-31a1-498b-aa10-656a9d1930b2.mp4

**Comment by kevinksullivan** [comment]
@Santhosh-Sellavel have you had a chance to review proposals?

**Comment by Santhosh-Sellavel** [comment]
@ctkochan22 I think this might be a backend bug

**Comment by kevinksullivan** [comment]
@Santhosh-Sellavel @ctkochan22 so is this one internal then?

**Comment by Santhosh-Sellavel** [comment]
@ctkochan22 Have you checked this one?

**Comment by Santhosh-Sellavel** [comment]
Personal details should not be received here, as the user doesn't initiate the chat.

**Comment by ctkochan22** [comment]
Not yet, but looking at it briefly again. I'm not 100% sure if this is a bug yet. Or something we care about. Asking in slack again

**Comment by Santhosh-Sellavel** [comment]
@ctkochan22 bump!

**Comment by Santhosh-Sellavel** [comment]
@ctkochan22 any development?

**Comment by ctkochan22** [comment]
Got some bandwidth to this over this week. Going to follow up with the last person who worked/introduced `includePersonalDetails`.

Slack [link](https://expensify.slack.com/archives/C01GTK53T8Q/p1666826953647119?thread_ts=1664399150.196209&cid=C01GTK53T8Q) for transparency. Verdict was that this is very low priority

**Comment by ctkochan22** [comment]
Looking here: https://expensify.slack.com/archives/C07J32337/p1665508847515969?thread_ts=1665416806.084149&cid=C07J32337

"also, [@tom](https://expensify.slack.com/team/U0G3AKY3Z) and [@jason](https://expensify.slack.com/team/U03TDU520)
 as I was writing the tests for this archived report logic, I realized that we no longer need any logic for if a report is empty or not. The rules are very simple:
In GSD mode
- Things are shown if: unread, pinned, draft, hasOutstandingIOU (regardless if they are archived or not)

In default mode
- Archived chats are always shown (regardless if they have comments on them or not)"
PR -- https://github.com/Expensify/App/pull/11725/files#diff-65c096044d5f69b35bcdec14c99c4fda4580759df9b1a7c36650d58eea276f1dL934

I think the same logic here applies to search. I think we've concluded its not a bug for LHN. So I don' t think it should be a bug for search. 

cc @tgolen

**Comment by trjExpensify** [comment]
Can we continue that [discussion here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669139030140559), I have a few concerns/clarifications with that proposal.

**Comment by tjferriss** [comment]
Following instructions for the [weekly update chore](https://stackoverflow.com/c/expensify/questions/8208):

@ctkochan22 this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:

- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by marcaaron** [comment]
Hold up, it doesn't seem like this is actually a bug. The "Search" function does not only show "reports" or conversations that you have open. AFAIK it has _always_ shown both existing chats and potential people to chat with (that is populated by `personalDetails` which can pull users from policies, reports, etc). It's a feature - not a bug.

**Sidebar:** Yes, only chats should show up here
**Search:** No, chats and and personalDetails are shown in here

It has always worked this way...

**Comment by trjExpensify** [comment]
Yeah, I commented the same in the linked thread, @marcaaron: https://expensify.slack.com/archives/C01GTK53T8Q/p1669202893636769?thread_ts=1669139030.140559&cid=C01GTK53T8Q

Outstanding question for me is around invites to new users via `Search`. The vid illustrates that you can invite and start a chat with a new user via Search by typing in a full valid email address or phone number. AFAIK, that was only possible via `New Chat`.

**Comment by marcaaron** [comment]
Originally it was only those flows, but we added that feature in [this PR](https://github.com/Expensify/App/pull/1706).

**Comment by trjExpensify** [comment]
Thanks! How time flies..
