### ISSUE TITLE
LHN- "You don't have access to this chat" message is not displayed after change the URL to http://staging.new.expensify.com/r/hello

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10452

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with your account
3. Navigate to a report url with an invalidID like http://staging.new.expensify.com/r/hello, check you see the You don't have access to this chat message

## Expected Result:
User can see the "You don't have access to this chat" message after navigate to a report url with an invalidID like http://staging.new.expensify.com/r/hello

## Actual Result:
"You don't have access to this chat" message is not displayed after change the URL to http://staging.new.expensify.com/r/hello

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193611228-e6c48224-5620-4cef-972a-5dd2c7c90bc9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Ah, this seems similar to the drawer closing thing that @marcaaron and @luacmartins were talking about [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664404003728569)

**Comment by yuwenmemon** [comment]
And then later identified by @chiragsalian [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665074857897569) as well

**Comment by yuwenmemon** [comment]
@chiragsalian based on the above am I correct in thinking that this issue is to be handled as a part of the Comment Linking solution?

**Comment by chiragsalian** [comment]
Ah yup the issue here is that closing the drawer on a reportID or reportActionID doesn't work currently and yes this will be tackled in comment linking. I'd say to just close this out since its a known problem which will be tackled in comment linking.

**Comment by kbecciv** [comment]
QA team is having problem with it on build 1.2.30.0

https://user-images.githubusercontent.com/93399543/203549273-546026d5-24ea-400c-a1fb-aebef46628a2.mp4

**Comment by chiragsalian** [comment]
well `r/1234` does not sound like a valid reportID so routing to the LHN actually looks good to me 😅

And if you do enter a valid reportID, the drawer will still close so yes it's a valid problem but it's something that will be tackled in the [comment linking issue](https://github.com/Expensify/Expensify/issues/147480).
