### ISSUE TITLE
Web - Connected VBA flow through the OldDot - Congrats message is not showing under Connect Bank Account option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to OldDot and log in with account
2. Go to Setting - Account -Payments
3. Add VBA
4. Go to NewDot
5. Log in with the same account as you used in OldDot
6. Go to Setting - Workspace
7. Select Connect Bank Account

## Expected Result:
Connected VBA flow the through OldDot - Congrats message is showing under Connect Bank Account

## Actual Result:
Connected VBA flow the through OldDot - Congrats message isn't showing under Connect Bank Account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193590180-395ae86d-7eb9-48e9-b62b-6a0e9bbce17e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
I'm confused about the expected results here. Where are these expected steps coming from? Is this a regression?

**Comment by roryabraham** [comment]
Tagging in @trjExpensify here ... do you know what @kbecciv is referring to here?

I see we have a "congrats page" that shows up when you've successfully set up a personal bank account (PR that added that [here](https://github.com/Expensify/App/pull/10072)), but I'm not sure if it's expected that the same thing would happen within a workspace. Can you connect multiple bank accounts into a free plan workspace?

Also cc @kbecciv – where did this expected result come from?

**Comment by trjExpensify** [comment]
Is it the `All Set!` page of the EnableStep? I can see it referenced here: https://github.com/Expensify/App/blob/9ab001cee05f0846edfd5e80de65b0df32188b21/src/pages/ReimbursementAccount/EnableStep.js#L114-L119

![image](https://user-images.githubusercontent.com/16232057/194971776-87c4f5c1-3158-4e1d-93ef-5d8957678544.png)

>Can you connect multiple bank accounts into a free plan workspace?

Not unless we've added that enhancement recently. CC: @kevinksullivan?

**Comment by trjExpensify** [comment]
@kbecciv - I'd be curious to know if the bank account showed up as added to the workspace after you refreshed the page? I agree that shouldn't really be required, but it would help determine here whether it's not recognising the bank account is added at all or if it needs a kick.

**Comment by kevinksullivan** [comment]
Yeah, this is still the MVP of the Free Plan, and we don't associate a VBA added in OldDot with a workspace in NewDot, unfortunately.  So there is no bug here. I'm going to close out for now, but let me know if there are other issues here!
