### ISSUE TITLE
[HOLD for payment 2022-11-04] [$250] Add Workspace name label next to room name in the chats list

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#11543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
As soon as you have multiple workspaces, it becomes impossible to decipher from a glance which rooms belong to which workspaces when you look at the LHN. As a result, you have to click into each chat to obtain that information in the chat header.

cc @trjExpensify 

## Actual Result:
![image](https://user-images.githubusercontent.com/2319350/193647120-ea0c8db1-39d6-4819-bf04-26e8ec28777a.png)

## Proposed Change:
Let's add a small pill style label next to the room name to indicate which workspace the room belongs to. 
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/2319350/193647248-2b766cbb-e487-429b-905c-bc4b8fbcc164.png">

## Platform:
Where is this issue occurring?

- All Platforms

**Upwork URL:** https://www.upwork.com/jobs/~01d70c28c08ade2a30
**Slack conversation:** [Internal link](https://expensify.slack.com/archives/C042KQL7963/p1664762603094779)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akshayasalvi** [comment]
**Proposal**

We need to update the `DisplayNames` component to accept nodes instead of `Proptypes.string`.

https://github.com/Expensify/App/blob/ce740fedbcd9a8b334d3fb8e36bce76a542cb577/src/components/LHNOptionsList/OptionRowLHN.js#L162-L166

```diff
<DisplayNames
    accessibilityLabel="Chat user display names"
-    fullTitle={optionItem.text}
+    fullTitle={(
+        <View style={[styles.flexRow]}>
+            <Text>{optionItem.text}</Text>
+           <View style={styles.pillContainer}>
+                <Text style={styles.textMicro}>{optionItem.subtitle}</Text>
+            </View>
+        </View>
+   )}

```


and add in styles.js:
```
   pillContainer: {
     ...styles.pv1, 
     ...styles.ph2, 
     ...styles.mh2, 
     backgroundColor: colors.gray2,
     borderRadius: variables.componentBorderRadiusCard
  },
```

Here's how it looks like after implementing, and I can update the styles if I get some design feedback.

![image](https://user-images.githubusercontent.com/57435789/193656627-bee31af2-e1a7-4620-b6d1-a1f568d59bab.png)

**Comment by shawnborton** [comment]
Ideally the pill should only be 20px tall, and we'll want to make sure it doesn't get cut off like it currently is.

**Comment by akshayasalvi** [comment]
@shawnborton Pill with 20px height.


<img width="364" alt="image" src="https://user-images.githubusercontent.com/57435789/193731051-73a7a965-32a6-4904-9060-7d65f6f5bfbf.png">


What do we do about the text overflowing when the workspace name is too long (second last row in the screenshot)

**Comment by mananjadhav** [comment]
@akshayasalvi's proposal here https://github.com/Expensify/App/issues/11543#issuecomment-1265892820 looks good. Will still wait for @shawnborton's comment on text overflow.

🎀 👀 🎀 
C+ reviewed

**Comment by shawnborton** [comment]
I think we should truncate the workspace name inside of the pill, and keep the full pill visible (not cut off like it is currently shown):
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/2319350/193857519-68d04194-2264-471b-8385-930275586d40.png">


Also, the bottom of the pill is cut off in your screenshots too so we'll need to address that one as well.

**Comment by akshayasalvi** [comment]
Can you tell me the max width for the pill? I'll update it.

> bottom of the pill is cut off in your screenshots too so we'll need to address that one as well.

Yeah I can work with it on the PR

**Comment by shawnborton** [comment]
It isn't so much that the pill has a max-width, it's just that the entire row of content has a max-width depending on how wide the device is.

**Comment by marcochavezf** [comment]
@mananjadhav thanks for the review, @akshayasalvi could you update the proposal to consider this requirement?

> It isn't so much that the pill has a max-width, it's just that the entire row of content has a max-width depending on how wide the device is.

**Comment by bernhardoj** [comment]
**Proposal**

Hi, I would like to share my approach to this problem.
We can put a new text (to show the chat room name) next to the DisplayName. The text will be applied with a textPill style

**_styles.js_**
```
textCapsule: {         
    ellipsizeMode: 'end',
    backgroundColor: colors.gray2,
    borderRadius: 50,
    paddingVertical: 2,
    flexShrink: 1,
    fontSize: variables.fontSizeLabel,
    ...spacing.ph3,
}
```

And here is the structure of the component
```
<View style={[styles.flexRow, styles.alignItemsCenter]}>
    <DisplayNames
        accessibilityLabel="Chat user display names"
        fullTitle={optionItem.text}
        displayNamesWithTooltips={displayNamesWithTooltips}
        tooltipEnabled
        numberOfLines={1}
        textStyles={displayNameStyle}
        shouldUseFullTitle={optionItem.isChatRoom || optionItem.isPolicyExpenseChat}
    />
    {optionItem.isChatRoom && 
        <Text 
            style={[styles.textCapsule, styles.ml2]} 
            numberOfLines={1}
            accessibilityLabel="Chat room name"
        >
            {optionItem.subtitle}
        </Text>}
</View>
```

I take a different approach than @akshayasalvi did, because I think the text pill (or capsule) does not belong to the DisplayName, the same thing done at the HeaderView component at line 133.

https://github.com/Expensify/App/blob/ce740fedbcd9a8b334d3fb8e36bce76a542cb577/src/pages/home/HeaderView.js#L124-L145

Here is the result of the changes
Compact             |  Not Compact
:-------------------------:|:-------------------------:
![WhatsApp Image 2022-10-06 at 16 14 17 (1)](https://user-images.githubusercontent.com/50919443/194258907-6b7754e3-1c45-45aa-a7d3-cb83b4e4e8ec.jpeg)  |  ![WhatsApp Image 2022-10-06 at 16 14 17](https://user-images.githubusercontent.com/50919443/194258918-05218cc9-223c-46fe-9eff-73216e45cfde.jpeg)

**Comment by mananjadhav** [comment]
Irrespective of the update from @akshayasalvi, I am more inclined towards @bernhardoj's proposal as it is much cleaner, and we really don't need to mix up `DisplayNames` with the Pill. 

My only recommendation would be to create a new component say `TextPill` so that we can reuse it later.

@shawnborton Can you confirm if there's anything else needed from the design perspective.

cc - @marcochavezf 

🎀 👀 🎀 
C+ reviewed

**Comment by shawnborton** [comment]
I agree, @bernhardoj 's proposal looks great and agree with you about a reusable pill. There are some minor design things we can chat about when this becomes a PR - for example, I think the pill can have a little bit less horizontal padding.

**Comment by bernhardoj** [comment]
Speaking of design, here is how it looks on web when the chat is selected:
![web_same_color](https://user-images.githubusercontent.com/50919443/194796950-2a556f0d-ecef-4f1e-b4ea-846c26096875.png)

The background color of the pill is the same as the background color of the selected chat and yeah, we can chat more about the design changes.

Btw, here is how the new TextPill component looks like
```
const propTypes = {
    /** Text to show */
    children: PropTypes.string,

    /** Text additional style */
    style: stylePropTypes,
};

const defaultProps = {
    children: '',
    style: [],
};

const TextPill = props => (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <Text {...props} style={[styles.textPill, props.style]} numberOfLines={1}>{props.children}</Text>
);

TextPill.propTypes = propTypes;
TextPill.defaultProps = defaultProps;
TextPill.displayName = 'TextPill';

export default TextPill;
```

**Comment by shawnborton** [comment]
> The background color of the pill is the same as the background color of the selected chat and yeah, we can chat more about the design changes.

Yeah, for the selected row, we should darken the pill background color to use our icon color variable at 50% opacity.

**Comment by mananjadhav** [comment]
@shawnborton Are we good with the proposal then? We can work out the kinks in the PR implementation?

**Comment by shawnborton** [comment]
Let's have an engineer take a look at the technical parts of the proposal - @marcochavezf what do you think?

**Comment by marcochavezf** [comment]
Yeah, I also agree with what @mananjadhav commented [here](https://github.com/Expensify/App/issues/11543#issuecomment-1269580881). The pill shouldn't belong to the DisplayName component and we can tweak the design details in the PR. Assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
I have applied the Upwork's job. I will open the PR ASAP, in today or tomorrow.

**Comment by trjExpensify** [comment]
@bernhardoj - offer sent! 
@mananjadhav - invite to job sent!

**Comment by bernhardoj** [comment]
Hi, the pull request is opened. Here is the pull request https://github.com/Expensify/App/pull/11799. Kindly review it! Thanks!

**Comment by mananjadhav** [comment]
Done with one round of review, have raised comments. Once resolved, I'll review once again and then Test.

**Comment by mananjadhav** [comment]
@bernhardoj Let me know once it is ready for the next round of review. I can see some comments are not resolved yet. Also can you sync with the latest `main` branch?

**Comment by bernhardoj** [comment]
I have pulled the latest changes from main and commit the newest changes. Kindly review it again. Thanks!

**Comment by trjExpensify** [comment]
@mananjadhav looks like we just need your re-review here and then this one is good to go. Can you get to it this week, please? It's a huge quality of life issue this one for our onboarding Guides. Thanks!

**Comment by mananjadhav** [comment]
@trjExpensify @marcochavezf this is done.

**Comment by trjExpensify** [comment]
Excellent, thanks! @marcochavezf can you get this reviewed now, please?

**Comment by trjExpensify** [comment]
Settled up!
