### ISSUE TITLE
[HOLD for payment 2022-12-15] [N7 Account Settings] Create Timezone pages

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#11577]
Tracking issue: https://github.com/Expensify/Expensify/issues/182122

Detailed section of doc: https://docs.google.com/document/d/17akqrbC-w8FqEoDLvcLmrX6iw4uaVrT_xlwAl-IhEzE/edit#heading=h.734gbh8x59o1

Note: This can only be implemented after `UpdateAutomaticTimezone` and `UpdateSelectedTimezone` commands have been created (see https://github.com/Expensify/Expensify/issues/238724)

**Comment by Beamanator** [comment]
On hold for WhatsApp Quality

**Comment by Beamanator** [comment]
Still on hold for now, might pick this up next week as discussions from here (https://github.com/Expensify/App/issues/11795) are indicating this could be useful to implement sooner rather than later

**Comment by Beamanator** [comment]
@cristipaval assigning you too since you're helping getting this PR out the door 👍

**Comment by Beamanator** [comment]
Bumped #bugzero for someone to help pay this out

**Comment by JmillsExpensify** [comment]
P.S. In the future, just add the `Bug` label and someone will be automatically assigned. Assigned myself for now.

**Comment by Beamanator** [comment]
@JmillsExpensify ok will do, I still feel weird adding `Bug` on issues that aren't actual bugs, but will do next time - thanks for jumping on this one 👍

**Comment by JmillsExpensify** [comment]
Yeah, agreed. It's weird. We should probably streamline this at some point, because it's come up as a recurring point of confusion and ultimately delays payments to contributors. All good though, we can take that convo to bug-zero in Slack.

**Comment by JmillsExpensify** [comment]
@rushatgabhane is officially all paid out, so I'm going to close this one out. 🙌🏼
