### ISSUE TITLE
[HOLD #11578] [N7 Account Settings] Hook up rest of new pages to Profile page

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#11582]
Tracking issue: https://github.com/Expensify/Expensify/issues/182122

Detailed section of doc here: https://docs.google.com/document/d/17akqrbC-w8FqEoDLvcLmrX6iw4uaVrT_xlwAl-IhEzE/edit#heading=h.jl7alj505ji8

Note: Holding on completely implementing some of the new profile pages. Some of them were included in WAQ project and hooked already. See [this issue](https://github.com/Expensify/App/issues/12952).

**Comment by Beamanator** [comment]
Unassigning since k2 is not liking that i have so many issues assigned to me on hold, will get back to this once N7 Account Settings if off hold

**Comment by Beamanator** [comment]
Little update: Contact methods pages are still holding on `#passwordless` & private personal details are holding on WAQ, but Display name, Pronouns, and Timezone pages are not on hold!

**Comment by Beamanator** [comment]
@cristipaval If you want, we could break this issue into 2 issues - one for hooking up Display Name, Pronouns, Timezone pages, and one for the rest - since half is blocked, half isn't... Let me know if you think that's better? If so, feel free to create the other issue

**Comment by cristipaval** [comment]
Great idea! I created [this issue](https://github.com/Expensify/App/issues/12952).

**Comment by cristipaval** [comment]
We're going to tackle this soon, as per discussions [here](https://github.com/Expensify/Expensify/issues/182122#issuecomment-1353171827)

**Comment by cristipaval** [comment]
still on hold

**Comment by cristipaval** [comment]
I think this one could be now closed, @Beamanator ?
