### ISSUE TITLE
Look into mocking the localize library better

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#11585]
Coming from https://github.com/Expensify/App/pull/11226/files#r982844771

I need to investigate why the localize lib is returning `undefined` for a translation and see about mocking it so that it will return an empty string instead.

**Comment by tgolen** [comment]
This doesn't need to be a daily. I've got a few irons in the fire before I can get to this.

**Comment by tgolen** [comment]
I'm dropping this to monthly now since I've gotten a lot of dailies assigned to me.

**Comment by JmillsExpensify** [comment]
Sounds good. I'll kick this off later today. Focused on the weekly updates first.

**Comment by JmillsExpensify** [comment]
Alright, circling back here. @tgolen I've updated the BZ checklist with our respective todos. Given that this is an internal issue and no C+ is on the linked PRs, we're good there. Do you mind confirming your todos/bullets? 

In the meantime, I see the following QA tests in the linked PRs:

**Chats in the LHN / Ordering**
1. In the LHN, make sure that reports are ordered by Pinned > Outstanding IOUs > Drafts > the rest of reports
2. Verify that changing any report in those groups will update the LHN properly
3. Verify that new unread chats show up in the LHN

**Search**
1. Click on the search button
2. Verify that you can search for chats and click on them to access them

Workspace archiving
1. Create a workspace
2. Archive the workspace
3. Verify that the LHN shows archived chats (Need to be in "most recent" view mode)

I checked TestRail and these test cases already look covered. That said, I've asked for a second opinion from BZ and will circle back to close.

**Comment by tgolen** [comment]
@JmillsExpensify Thanks! I've done my checklist items. This wasn't technically a "bug", it was just a code cleanup task, so some of those items don't apply.

**Comment by JmillsExpensify** [comment]
Ok thanks! Circling back on the regression tests now.

**Comment by JmillsExpensify** [comment]
Alright, regression test is created above. I also CCed you in the issue, so please give it a look to make sure I didn't miss anything!

**Comment by JmillsExpensify** [comment]
We're all set here. I'm closing.
