### ISSUE TITLE
Web - Workspace - Error message "There was a problem adding this workspace member" displayed when adding non-existing account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with your account
3. Go to Setting - Workspace.
4. Click Manage members.
5. Click on Invite.
6. Add a non-existent user and click Invite.

## Expected Result:
No error message "There was a problem adding this workspace member" and console error when adding non-existing account

## Actual Result:
Error message "There was a problem adding this workspace member when adding non-existing account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193934498-6c47bcab-78a5-47c7-b0fc-671764855782.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
It looks like this most likely has to do with inviting a member on a Domain Controlled domain, so will need to be Internal.

**Comment by puneetlath** [comment]
Still expecting to get to this this week.

**Comment by puneetlath** [comment]
PR sent.

**Comment by puneetlath** [comment]
PR has been merged.

**Comment by puneetlath** [comment]
This was deployed to production yesterday.
