### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] BUG: "A room with this name already exists" message appears saving room name without making any change

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot and login 
2. Click on any room created
3. Tap the room name to see the details
4. In settings click "Save" for room name without making changes

## Expected Result:
Nothing should happen

## Actual Result:
"A room with this name already exists" message appears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dangrous 
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/43996225/194080748-f8208b13-38e5-4603-991b-a99e3bf8d97a.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/43996225/194080778-addc964f-8cad-4ae1-8ed8-5708ca2802f6.png">

**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1664923596295109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Yep this is a legit bug that fell through the cracks when refactoring renaming the rooms. It will be a good external issue and I like this proposal https://github.com/Expensify/App/issues/11606#issuecomment-1268561526.

**Comment by parasharrajat** [comment]
@Puneet-here 's [proposal](https://github.com/Expensify/App/issues/11606#issuecomment-1268561526) looks good to me. 

cc: @aldo-expensify 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by aldo-expensify** [comment]
The proposal looks good to me too, it itches me a bit that the `validate` function is just returning `false` in this case and doesn't add any error like in the other cases... but I think that is the behaviour we want. Maybe we can add a comment explaining why we didn't add an error in this case.

**Comment by aldo-expensify** [comment]
Thanks for the proposal @Puneet-here, assigned you to this GH issue!

**Comment by parasharrajat** [comment]
https://github.com/Expensify/App/issues/11606#issuecomment-1270495241

I had same thoughts but it was giving me the same itching thinking to put it in `submit`. At least now `submit` will look clean so I decided to move with it.

**Comment by aldo-expensify** [comment]
> [#11606 (comment)](https://github.com/Expensify/App/issues/11606#issuecomment-1270495241)
> 
> I had same thoughts but it was giving me the same itching thinking to put it in `submit`. At least now `submit` will look clean so I decided to move with it.

hehe yeah, I also thought about putting it in `submit`... but it is also a validation, so it may be ok to stay in `validate`. 🤷 , I guess it doesn't matter much

**Comment by sophiepintoraetz** [comment]
Created an external posting [here](https://www.upwork.com/jobs/~01661c45925ad5edf7) on Upwork

**Comment by sophiepintoraetz** [comment]
Payment to @Puneet-here - reminder for @parasharrajat to apply!

**Comment by parasharrajat** [comment]
@sophiepintoraetz I already did a few days back. Also, I think it is helpful to keep the issue open until all the payments are done. You can put it back to weekly if needed.  

A few of my trackers depend on the status of the issue.

**Comment by sophiepintoraetz** [comment]
@parasharrajat Unfortunately, I also have a number of weekly issues that are more pressing, so I close out issues to keep my tracker tidy but I'll keep this in mind. In any case, dropping a comment here confirming when you have applied would help as well!  (I've accepted your application, thanks)

**Comment by parasharrajat** [comment]
Thanks. You can even put it to Monthly if that helps. I am facing some issues on the Upwork side so can't take immediate action.

**Comment by sophiepintoraetz** [comment]
Looks like you accepted, so closing this issue with payment, thanks!

**Comment by neil-marcellini** [comment]
@0xmiroslav that looks like a legit issue to me. Please report it in #expensify-bugs in Slack.
