### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Feature Request: After entering the six authentication numbers for 2FA, log in user without having to click `return`

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
With 2FA enabled, after you type in the numbers you have to click `return`. this final step shouldn't be necessary

## Solution:
Once the 6 numbers are entered the user should be logged in without needing to click `return`

## Context/Examples/Screenshots/Notes: 

Many apps function this way, there's no 'benefit' to making users take additional steps to login. If you need an example, logging out/in of Slack while having 2FA enabled should be a good one
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664918771771259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Do you think this is a feature that a contributor would be able to compete?

**Comment by francoisl** [comment]
Yes we can open this to contributors, anyone can enable 2FA from https://www.expensify.com/settings for testing.

**Comment by mananjadhav** [comment]
@aimane-chnaif's proposal looks good to me https://github.com/Expensify/App/issues/11607#issuecomment-1269269205

cc - @srikarparsi @greg-schroeder 

🎀 👀 🎀 
C+ reviewed

**Comment by srikarparsi** [comment]
yup, also looks good to me

**Comment by greg-schroeder** [comment]
Okay, working on getting this posted!

**Comment by greg-schroeder** [comment]
Internal: https://www.upwork.com/ab/applicants/1578205480301780992/job-details

External: https://www.upwork.com/jobs/~01d06283fe580ac75c

cc @mananjadhav @aimane-chnaif - Apply here!

**Comment by mallenexpensify** [comment]
Thanks for the headsup @aimane-chnaif , you're assigned now

**Comment by mananjadhav** [comment]
@greg-schroeder Quick bump on the payment here

**Comment by greg-schroeder** [comment]
@mananjadhav @aimane-chnaif - Hey team, sorry was OOO last week! I've just hired you via Upwork, so go ahead and accept it and I'll finalize the payment. 👍

**Comment by mananjadhav** [comment]
Accepted @greg-schroeder
