### ISSUE TITLE
BUG :  In focus mode pinned / drafted items not shown in LHN 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and login
2. Click avatar > preferences > select focus in priority

## Expected Result:
In the LHN draft, Pinned message and unread messages are shown

## Actual Result:
Pinned and drafted messages are not shown 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web
- Android

**Version Number:** 1.2.11-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1112" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/194187935-5f1cec58-e1ac-454a-a6b8-f2a8266b6536.png">

https://user-images.githubusercontent.com/43996225/194187945-fd0d44d9-898d-4637-916b-ea867f9fa008.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @cead22 
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1665014762126469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I'm looking into this.

**Comment by tgolen** [comment]
PR is up
