### ISSUE TITLE
Android - Workspace - After error window, the system redirects you to the LHN page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings->Workspaсe
4. Kill the internet connection
5. Open any options of workspase and click "Connect bank account"
6. Close the window about error

## Expected Result:
The system should redirect you to the previous page

## Actual Result:
The system redirects you to the LHN page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** v1.2.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194419353-9bf487eb-bb93-47c5-ab7b-fd7d1403e441.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Closing this because we're working on a big refactor to the navigation code. The x button is going to be removed.
