### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Bug: The error message is incorrect, it says "And unexpected error..." instead of "An unexpected error..." reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Payments > Add payment method
2. Bank account > Plaid flow
3. While in Plaid Sanbox mode, enter any data
4. You'll be brought back to Expensify
5. Select a bank account in the dropdown
6. Use a wrong password > Click Save & continue

## Expected Result:
The error message should be correct without spelling mistake

## Actual Result:
Error message appears with spelling mistake `And` appears instead of `An`

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** Can't check bank account flow
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="375" alt="Screenshot 2022-10-06 at 9 12 15 PM" src="https://user-images.githubusercontent.com/43996225/194425586-7a9effbc-a6a1-49d7-a877-1cde574881b3.png">
<img width="960" alt="1 (2)" src="https://user-images.githubusercontent.com/43996225/194425602-79d93bbb-0b1e-4704-a108-22f7e05fdfba.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665071905275049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
This one is a good find. I was able to reproduce and I updated the testing steps. Also a note, we need to change this message in Spanish too, as that is also wrong. 
![Screen Shot 2022-10-06 at 22 34 59](https://user-images.githubusercontent.com/1127863/194462735-d5d6bc47-8323-4313-8a6a-c3bf0380e00b.png)

**Comment by JmillsExpensify** [comment]
I'll keep this assigned to myself, as I intend to fix it.

**Comment by Puneet-here** [comment]
### Proposal

We need to change the error here https://github.com/Expensify/App/blob/b65b1329f622bfc06aa2da9c4976023eb85d99d7/src/languages/en.js#L415
https://github.com/Expensify/App/blob/0e8fc0274f101453ddeda06158b589b0391e2994/src/languages/es.js#L415

**Comment by JmillsExpensify** [comment]
Oh if you want to take it then by all means @Puneet-here. I'm happy to have you take it. 

Also the marketing team won't be able to help with the Spanish translation. Luckily the fix is easy, I can help with that. The Spanish text should remove the "Y" (which means "and" in Spanish) and instead begin with "Ocurrió un error...."

I'll go ahead and create an Upwork job for you and add the external label.

**Comment by JmillsExpensify** [comment]
@eVoloshchak @ctkochan22 This should be a pretty straightforward one. @Puneet-here's proposal is above and he just needs to change the text files he's already highlighted above. I'm happy to review the PR for the Spanish part.

**Comment by ctkochan22** [comment]
Yeah lets hire @Puneet-here . Had this fixed in a larger PR, but that one never went out

**Comment by ctkochan22** [comment]
@JmillsExpensify did we hire @Puneet-here ?

**Comment by eVoloshchak** [comment]
PR is in review

**Comment by JmillsExpensify** [comment]
All Contributors hired via Upwork.

**Comment by JmillsExpensify** [comment]
Linked PR is merged and on staging. It should reach production soon, at which point the regression period begins before payment is issued.

**Comment by JmillsExpensify** [comment]
No regressions at this point, so tomorrow I'll circle back on payment.

**Comment by JmillsExpensify** [comment]
@Puneet-here and @eVoloshchak have been paid out via Upwork.

**Comment by JmillsExpensify** [comment]
@thesahindia I've created a separate reporting bonus for you here: https://www.upwork.com/jobs/~0162a345d0a7efe93b. Mind applying and we can close this out?

**Comment by thesahindia** [comment]
Applied🚀

**Comment by eVoloshchak** [comment]
@slickroot, this one is already solved, but there are a [bunch of open issues](https://github.com/Expensify/App/labels/Help%20Wanted) you can submit a proposal for!

If you're new here, please take a look at [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and welcome :)

**Comment by JmillsExpensify** [comment]
> Applied🚀

Nice! Let me know once you've accepted the offer, then I'll issue payment and close this issue.

**Comment by JmillsExpensify** [comment]
Actually I saw you already accepted and I've just issued payment. I'm closing this one out. Thank you all!
