### ISSUE TITLE
Bug: Endless scrolling and white spaces when scrolling chats at homepage in mWeb reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open NewDot at mobile browser
2. Login with an account which contains multiple chats (more than 15)
3. Refresh and try scrolling

 ## Expected Result:
There shouldn't be any white space

## Actual Result:
White space between contacts

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194424118-bbe3f2eb-6075-4569-b9af-a1b0ab7a9412.mp4

https://user-images.githubusercontent.com/43996225/194424175-a245e78d-cbe5-4d2a-835d-19265de64479.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665067716768829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Closing, I haven't been able to reproduce on my mWeb on staging or production
