### ISSUE TITLE
[HOLD #11330][$250] IOS - LHN - Chats are not reordering properly as per the group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11226 

## Action Performed:
1. In the LHN, make sure that reports are ordered by Pinned > Outstanding IOUs > Drafts > the rest of reports
2. Open any chat and draft message in the compose box

## Expected Result:
Should update in the LHN in the order and it should be grouped with Drafts section

## Actual Result:
It is not moving until opening the another report

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12.2.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194551731-34b4607d-35b8-45e3-bc8f-1b8b1c4d5490.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Is this issue only on iOS?

**Comment by parasharrajat** [comment]
No proposals

**Comment by tsa321** [comment]
Related to https://github.com/Expensify/App/issues/11330, In  the issue, there is a discussion to immediately move the report with recently made draft to move up. 
If report already at the top section/draft section, the report will move down immediately if draft is removed.

If this behavior accepted, the this issue will be resolved too. But there is still ongoing discussion there.

**Comment by parasharrajat** [comment]
Thanks for linking that @tsa321. We will keep tracking that.

**Comment by zanyrenney** [comment]
Discussing unifying this with some of the other issues: https://expensify.slack.com/archives/C01SKUP7QR0/p1666318536729249

**Comment by zanyrenney** [comment]
On hold for: https://github.com/Expensify/App/issues/11330

**Comment by mallenexpensify** [comment]
Thanks Zany, I removed the `Help Wanted` label too since it's on hold

**Comment by zanyrenney** [comment]
This is on hold. @Luke9389 what do you think about updating this to weekly whilst we are still on hold?

**Comment by Luke9389** [comment]
I think that's fine 👍

**Comment by zanyrenney** [comment]
Still on Hold, not overdue.

**Comment by zanyrenney** [comment]
On hold.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by flodnv** [comment]
So let's close?
