### ISSUE TITLE
Web - Payment - An error when trying to mark any payment method as default

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition : You should have 2 or more methods of payments
1. Go to URL https://staging.new.expensify.com/

2. Log with any account
3. Go to Settings->Payments
4. Mark any payment method as default

## Expected Result:
The payment method was marked as the default

## Actual Result:
An error when trying to mark any payment method as default

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194445462-4149df3c-9d1c-4aaf-bb5b-4c615544cdee.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
FYI - This happens on both staging and production, so I do not think that it was introduced by https://github.com/Expensify/App/pull/11533

**Comment by MariaHCD** [comment]
Logs [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227569b979895dc3af-SEA%22)+AND+timestamp:[2022-10-07T20:28:05.401Z+TO+2022-10-07T22:28:05.401Z]&index=logs_expensify-018931). This bug will be fixed with the deploy of the Auth PR: https://github.com/Expensify/Auth/pull/7110

This issue should not block the App deploy.

**Comment by MariaHCD** [comment]
The fix was already deployed to production: https://github.com/Expensify/Auth/pull/7110#issuecomment-1273325675

@kavimuru Could you retest?

**Comment by kavimuru** [comment]
@MariaHCD Sure, checking with team and get back to you.

**Comment by kavimuru** [comment]
@MariaHCD Issue is fixed.

https://user-images.githubusercontent.com/43996225/197261877-f7a77a96-8622-4221-b6ed-77fdbb80da60.mp4

**Comment by MariaHCD** [comment]
Great, thanks for retesting @kavimuru!
