### ISSUE TITLE
Web - IOU are not getting sync between the devices

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11226

## Action Performed:
1. Launch the app and login with account A in device 1
2. From another account send request money
3. After an hour login to another device

## Expected Result:
All the IOU should appear in the LHN

## Actual Result:
Not showing in the LHN

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194550924-2205c591-69f9-44bf-a99c-2daed370bc78.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Okay, confirmed that this only happens if the second device is not running the app when the IOU is created

**Comment by roryabraham** [comment]
I don't seem to be able to reproduce this on dev, however

**Comment by roryabraham** [comment]
Ok, jk I _can_ reproduce this on dev

**Comment by roryabraham** [comment]
Got a PR up to fix this: https://github.com/Expensify/Web-Expensify/pull/35118

**Comment by roryabraham** [comment]
PR updated and still in review

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by roryabraham** [comment]
This was fixed in https://github.com/Expensify/Web-Expensify/pull/35118
