### ISSUE TITLE
Android - The archived room opened empty and did not disappear from the LHN page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11631

## Action Performed:
1. Go to URL https://staging.new.expensify.com/ and login
2. Have multiple pinned reports
3. Have some chats which are not pinned that have unread messages
4. Change the focus view mode in preferences
5. Find the archived room in LHN (Note: the workspaces of those rooms have already been deleted)
6. Tap on any of this rooms

## Expected Result:
The archived room opens with conversation in past and should disappear from the LHN page when tap on it

## Actual Result:
The archived room opened empty and did not disappear from the LHN page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.12.2.

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194581888-44784229-3e57-42df-89e2-e0046b992038.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
@kbecciv what happens if you do a clean sign out and come back in, does it still occur?

**Comment by johnmlee101** [comment]
Also is that archived chat still pinned in this case? Or is it unpinned?

**Comment by johnmlee101** [comment]
If the chat is still pinned in this case, this is expected functionality and not a regression!

**Comment by johnmlee101** [comment]
Will wait for your response before closing this out

**Comment by johnmlee101** [comment]
Closing this out
