### ISSUE TITLE
BUG: Right side section moving when pressing "sign in " in the password page with error message reported by @wildan-m

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Make blocked account by performs failed login attempts numerous times.
2. Go to login page and fill username
3. Zoom in the browser until the left column content height overflow the browser height
4. Fill password and login

## Expected Result:
There should be no visible jerk or movement in the right-hand side (carousel)

## Actual Result:
 When the error validation toggled, right-hand carousel is moving

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194621520-d64c8a4b-b314-44a5-aec8-0d611605dd5a.mp4
https://user-images.githubusercontent.com/43996225/194621539-55d86d4f-797a-4c09-8779-1d3f28feffe2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @wildan-m
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665100293073979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
@kavimuru or @wildan-m - can you clarify whether you mean the right-hand side containing the carousel for images **or** the left-hand side that contains the logo (you mention both in the **expected result**, which makes it hard to know what you're referring to).

**Comment by wildan-m** [comment]
@sophiepintoraetz, I mean, when the validation toggled, the right logo shouldn't moving, right?

**Comment by sophiepintoraetz** [comment]
hmm, but the logo is on the left? There is no right-hand logo?
<img width="950" alt="image" src="https://user-images.githubusercontent.com/42940078/195506903-22b494ce-1112-44b9-8edd-ac52a18c0b5b.png">

**Comment by wildan-m** [comment]
@sophiepintoraetz, I mean the image on the right side. "Corporate cards..."

**Comment by wildan-m** [comment]
@sophiepintoraetz, numerous times (not sure exactly), or you can use my dummy email

wildevemail@gmail.com
type any password on the password form

**Comment by sophiepintoraetz** [comment]
All right, I just tried the wrong password 20 times for your email address and wasn't able to bring up the prompt (albiet, in incognito browser, though that shouldn't affect this bug flow). @wildan-m, can you confirm:
1. How many times you are entering the wrong password
2. Whether you can produce this in an incognito browser
<img width="614" alt="image" src="https://user-images.githubusercontent.com/42940078/197096163-eeebaac5-55ab-4da3-9d9f-4a1db200d7da.png">

**Comment by wildan-m** [comment]
@sophiepintoraetz please use this correct password

mJIJ(83j#@#

Please let me know when you've copied the password

**Comment by sophiepintoraetz** [comment]
I have done so!

**Comment by sophiepintoraetz** [comment]
@kavimuru and @wildan-m - can you please add more specific reproduction steps? I'm unable to reproduce this error so will reopen once we've got reproducible steps.

**Comment by wildan-m** [comment]
@sophiepintoraetz, I don't know the backend logic to create a banned account, but here is another way to reproduce the same issue.

1. Go to the login page and fill new email
2. Zoom in the browser until the left column content height overflow the browser height
3. Click resend validation login more than three times

Please watch the attached video
https://user-images.githubusercontent.com/11847279/197675627-d9ee53d7-8398-4c8a-bcb6-e45044d41f80.mp4

**Comment by wildan-m** [comment]
@sophiepintoraetz, can you reproduce it with the above steps?

**Comment by sophiepintoraetz** [comment]
@wildan-m - to be clear, are you referring to the issue where the _Corporate Cards, Reimbursements, Receipt Scanning_ text jumps up and down every time you click **`Resend link`**? If so, you will need to update the OP instructions.

**Comment by wildan-m** [comment]
@sophiepintoraetz, yes, you are right. How to update OP instructions? did you mean to update Action Performed in this post?

@kavimuru, can you update the action performed step with this one?

> 1. Go to the login page and fill new email
> 2. Zoom in the browser until the left column content height overflow the browser height
> 3. Click resend validation login more than three times

> Please watch the attached video
https://user-images.githubusercontent.com/11847279/197675627-d9ee53d7-8398-4c8a-bcb6-e45044d41f80.mp4

**Comment by kavimuru** [comment]
@wildan-m Updated the action performed steps.

**Comment by wildan-m** [comment]
Thanks @kavimuru. @sophiepintoraetz does it work?
