### ISSUE TITLE
[$250] BUG - First contact is highlighted when start a new chat or group

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot and login
2. Click Global Fab and select New chat / New group

## Expected Result:
1st row shouldn't be highlighted by default

## Actual Result:
1st row highlighted by default

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194630195-dbcf7c34-34ff-4e6f-9991-084837774cdd.mp4

![12345](https://user-images.githubusercontent.com/43996225/194630217-684ff2dc-f0d9-4cd4-accb-03c90dcc3982.gif)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @michaelhaxhiu 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665066139780689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Not overdue -- weekend, will look today.

**Comment by grgia** [comment]
Summarizing slack thread here:
The highlighting was intentional for arrow navigation, but we agree that the first user shouldn't be highlighted by default. 
The solution is to only highlight rows once the user has pressed arrow down/triggered arrow navigation.

**Comment by michaelhaxhiu** [comment]
PS in the future, let's be sure the title & body of the GH summarizes the expected/desired behavior cc @zanyrenney

**Comment by Julesssss** [comment]
> I think we should also keep the row highlighted when we search for something. Otherwise it won't be obvious what will happen when the Enter key is pressed.

I'm not sure I agree. I would have thought 'Enter' would do nothing until a down arrow is used to select an item. Curious if you agree @grgia @zanyrenney

**Comment by dylanexpensify** [comment]
not overdue - moving to weekly while we hold discussion
