### ISSUE TITLE
Search - Room and Workspace does not displayed for invited user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
in maim and incognito windows and login with different Expensify users (A and B)
2. Create a workspace with user A
3. Go to the Manage members tab of the workspace, invite user B
4.  Log in with account B
5. Verify that the invited member (B) can see the workspace and room

## Expected Result:
The workspace and room should be available

## Actual Result:
the workspace and room is not available

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194730725-f6d581ea-72ff-47ca-b227-001a0ea33161.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Can you confirm you can see the rooms once you do a refresh and/or log in again? (I do see the new rooms in this case) It's possible this isn't connected to pusher yet.

**Comment by AndrewGable** [comment]
So interestingly, I see the room as the "User B" but not "User A"

**Comment by mvtglobally** [comment]
@AndrewGable here is the retest result 

https://user-images.githubusercontent.com/43995119/194947024-5f57256d-4dac-4141-9413-f23683004654.mp4

**Comment by marcaaron** [comment]
Sorry I was OOO yesterday but can look into this today. Looks like this was assigned on a Saturday.

**Comment by tgolen** [comment]
@marcaaron I think my PR is going to fix this too. I'd like to group them together, so I will grab this from you.
