### ISSUE TITLE
Feature Request :The push notification gets cleared if I read the message on desktop

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to same account in 2 devices (Web and iOS)
2. Send a message from another account
3. Get notification in both the devices and read the message in Web

## Expected Result:
Notification cleared in mobile devices

## Actual Result:
Not cleared

## Platform:

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664405879860479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I'm not sure I understand this issue. So you're saying that the notification is cleared in the mobile device if you're active on desktop and read the message there? If so, I think that's a feature more so than a bug.

**Comment by puneetlath** [comment]
No, I think the wording is confusing. Right now, we don't clear the mobile push notification if the message is read on desktop. This is a feature request to make it so that we do.

**Comment by JmillsExpensify** [comment]
Ah, gotcha. Missed the feature request in the title. Honestly, I'm pretty on the fence with these feature requests at the moment. I think we should actively be trying to close every issue in this repo, because it's a bug that shouldn't exist. So the more we keep these feature requests around right now, the more distracted we are from our core goal.

**Comment by trjExpensify** [comment]
I wonder how much this will get solved by the notifications project @Julesssss is working on anyhow?

**Comment by arielgreen** [comment]
> I'm pretty on the fence with these feature requests at the moment. I think we should actively be trying to close every issue in this repo, because it's a bug that shouldn't exist.

Agree with this. I'm going to close for now. As a new feature, I think we would be implementing this internally anyway, so if anyone disagrees, feel free to reopen. I think this makes sense, but it feels pretty low priority to me.

**Comment by Julesssss** [comment]
Agree with this being closed. 

This is definitely a nice feature to implement eventually, but it seems pretty low priority for now. I'm not planning on implementing this feature (yet, please raise in the DD if you disagree). But regardless, once the notifications project has been completed it should be relatively trivial to implement.

**Comment by puneetlath** [comment]
Works for me.
