### ISSUE TITLE
Workspace- No member shows up for brief moment when clicking manage members reported by@Puneet-here  

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Workspace
2. Manage members

## Expected Result:
A loader should be shown instead of showing blank list

## Actual Result:
Blank list is shown

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11-4 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194926395-76cadac8-8b48-4c37-bfac-66f8e9dafbd2.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here  
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665263020435209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
Hi @kavimuru, I'm unable to reproduce:

https://user-images.githubusercontent.com/31258516/196672271-fca4f2f3-19da-46c9-b8e0-a6e4123a35ed.mp4
