### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Bug: In Request Call Page, space(' ‘) is considered as valid First name and Last name reported by @sobitneupane

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on :telephone_receiver: symbol from Concierge chat.
2. Enter space (’ ’) as First name and Last name.

## Expected Result:
Error should be shown requesting user to enter valid name

## Actual Result:
No error message displayed and user is able to request call.
## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="506" alt="Screen Shot 2022-10-10 at 21 05 00" src="https://user-images.githubusercontent.com/43996225/194933237-777c67cc-7cf9-408e-85ed-9cfeb1c77384.png">
<img width="506" alt="Screen Shot 2022-10-10 at 21 03 58" src="https://user-images.githubusercontent.com/43996225/194933238-5a8775a9-9dd7-4404-b121-e38dd471693e.png">

https://user-images.githubusercontent.com/43996225/194933268-8f39cccb-66d9-4e32-b5dd-5ec316ff16af.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sobitneupane
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665415051145589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal

Use `trim` like below
```
values.firstName.trim()
```

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/RequestCallPage.js#L216

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/RequestCallPage.js#L220

**Comment by JmillsExpensify** [comment]
Jumping in to test this one first, then I'll make it available via Upwork. Thanks for already jumping on a proposal!

**Comment by JmillsExpensify** [comment]
Ok so I can reproduce that, but I vaguely remember that this was a purposeful design decision. I looked at the linked Slack thread where this was reported and I wasn't able to find any further context. @trjExpensify Can you clarify if this was a purposeful change?

**Comment by trjExpensify** [comment]
Not at all. That's a bug! We need a name so the Guides know who to ask for.

**Comment by JmillsExpensify** [comment]
Ok cool! Moving this through the process.

**Comment by idawoodhashmi** [comment]
Hi, We can fix this easily. We will apply regex for validation and that will solve the issue. Kindly let us proceed with the changes to be done and you'll not be disappointed.

**Comment by thesahindia** [comment]
I like @Puneet-here's [proposal](https://github.com/Expensify/App/issues/11709#issuecomment-1273699772). `trim` method will do the job. 

C+ reviewed 🎀👀🎀

cc: @MonilBhavsar

**Comment by thesahindia** [comment]
@idawoodhashmi, thanks for showing interest but you have to propose a solution with the code changes that you will make. You can check other proposal on this issue to understand the process. Feel free to post proposals on other issues. 

You can also checkout [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md), if you haven't already.

**Comment by MonilBhavsar** [comment]
> I like @Puneet-here's https://github.com/Expensify/App/issues/11709#issuecomment-1273699772. trim method will do the job.

Looks good to me too 👍

**Comment by JmillsExpensify** [comment]
Awesome! @Puneet-here @thesahindia upwork job is here: https://www.upwork.com/jobs/~011d1ecd1dde653fb3. Please apply.

**Comment by JmillsExpensify** [comment]
@thesahindia is hired and I've just invited @Puneet-here. The linked PR is merged and on staging, at which point the regression period will begin before payment is issued.

**Comment by JmillsExpensify** [comment]
No regressions at this point so tomorrow I'll circle back on payment.

**Comment by JmillsExpensify** [comment]
@thesahindia has been paid out. @Puneet-here has been hired. @sobitneupane please make sure to add yourself to the Upwork posting as well for the reporting bonus.

**Comment by sobitneupane** [comment]
@JmillsExpensify Applied for the job.

**Comment by JmillsExpensify** [comment]
Thanks offer sent!

**Comment by sobitneupane** [comment]
> Thanks offer sent!

Offer Accepted.

**Comment by JmillsExpensify** [comment]
Thanks paid out! Now we're down to @Puneet-here.

**Comment by Puneet-here** [comment]
I have accepted the offer, thanks!

**Comment by JmillsExpensify** [comment]
Everyone should be paid out now. Thank you!
