### ISSUE TITLE
Bug: No focus after click "fix the errors" link on form submit error message reported by @aimane-chnaif 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create new workspace
2. Go to Settings -> new workspace -> Connect bank account
3. Leave "Routing number" empty
4. Enter "1234" in "Account number"
5. Accept terms of service
6. Click "Save & Continue" button
7. Click "fix the errors" link

## Expected Result:
"Routing number" input should be focused

## Actual Result:
No focus on "Routing number" input

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195200739-1cd46f24-b1ca-4319-b586-a289f4f9c73b.mov

https://user-images.githubusercontent.com/43996225/195200868-ccde7adb-e12e-4a77-a8d6-9a1bd5c906bb.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665507784776589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I was able to replicate the error. This looks ready for engineering. The only item I'm confused on is what the expected result would actually look like. I asked for a clarification in the Slack [thread.](https://expensify.slack.com/archives/C01GTK53T8Q/p1665535130006169?thread_ts=1665507784.776589&cid=C01GTK53T8Q). I'm guessing we would show something to draw attention back to the routing number. I agree it's an error that the clicking or tapping the link does nothing right now.


<img width="413" alt="Screen Shot 2022-10-11 at 5 40 35 PM" src="https://user-images.githubusercontent.com/8292562/195223234-90c6554c-5c56-4a38-a0c2-5a824e35d459.png">

**Comment by varshamb** [comment]
Okay, in that case original bug should be reopened.

https://github.com/Expensify/App/issues/11424

**Comment by Luke9389** [comment]
Closing in favor of https://github.com/Expensify/App/issues/11424

**Comment by mallenexpensify** [comment]
@aimane-chnaif this is def an edge case but, based on your comment above, and other in this issue, it appears you are eligible because there was a big at the time of reporting that wasn't actively being worked on or reported.  @Luke9389, can I get a gut check?  Assigned ot me too

**Comment by mallenexpensify** [comment]
Thanks @Luke9389 
Please accept the job and I'll get ya paid @aimane-chnaif 
https://www.upwork.com/jobs/~015dafabfe5221f956

**Comment by mallenexpensify** [comment]
Paid @aimane-chnaif !
