### ISSUE TITLE
BUG: Text inside menu list is highlighted when FAB action button is quickly clicked @mdneyazahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Goto https://staging.new.expensify.com/
2. Click on FAB action button to open
3. Now quickly click two times. It will close the list and open again, but everything on the list will be highlighted.

## Expected Result:
The text is not highlighted

## Actual Result:
The text is highlighted. However, the text is not highlighted when clicked slowly.

## Workaround:
N/A

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665483676791649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/195196392-404b252b-60c9-465f-bbde-521eb224ee0e.mov

https://user-images.githubusercontent.com/43996225/195196515-30e609a4-26fd-4f15-8968-1d680284f559.mp4

**Comment by jliexpensify** [comment]
Tested on 1.2.12-3 (staging), can reproduce.

**Comment by jliexpensify** [comment]
@MonilBhavsar happy for me to make an Upworks job?

**Comment by MonilBhavsar** [comment]
@jliexpensify I wasn't sure if this is really an issue so asked here https://expensify.slack.com/archives/C03TQ48KC/p1665643321931409

**Comment by jliexpensify** [comment]
Seems like a no from @Beamanator - close this one?

**Comment by MonilBhavsar** [comment]
Yes, It doesn't seem like an issue and we want to fix it. So closing this for now.
