### ISSUE TITLE
Speed up webpack builds

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
Webpack builds are slow.

### Why this is important
It take up developer time. Saving each of us 5-10 minutes per day will pay dividends in the long run.

### Solution
Make them faster!

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kidroca** [comment]
I would like to work on this task as a hourly item and explore the following 

- enable FS cache 
- configure bundle splitting 
- anything else that might boost build speed 

If you want to I can test swapping Webpack for Vite for the web project and post a build times

**Comment by roryabraham** [comment]
All that sounds great, though I'm a little hesitant about bundle splitting and think that we would want to have a wider conversation about the pros and cons of that.

**Comment by kidroca** [comment]
Some metrics from the current `main` branch (069424538ad9ac0e03ec2af4f73c3b6c02e32e26)

Running `npm run web` to start web development

| **Item**                       |          **time** | **processed module count** |
|:--------------------------------|------------------:|---------------------------:|
| General output time            |  3min, 12.15 secs |                        n/a |
| babel-loader                   | 3 mins, 1.65 secs |                       2775 |
| babel-loader and eslint-loader | 1 min, 52.95 secs |                        629 |
| modules with no loaders        |  1 min, 6.45 secs |                         20 |
| @svgr/webpack                  |        41.85 secs |                        130 |
| file-loader and babel-loader   |        13.26 secs |                          1 |
| file-loader                    |         6.21 secs |                          8 |
| css-loader                     |         1.97 secs |                          2 |
| html-webpack-plugin            |         1.46 secs |                          1 |
| style-loader and css-loader    |        0.033 secs |                          2 |

- _some items run in parallel so the total time is not a sum of all times_
- these measurements were captured with: https://github.com/stephencookdev/speed-measure-webpack-plugin/

**Comment by kidroca** [comment]
Removing `eslint-loader` reduced "General Output time" with a whole minute 

Everything else being the same, the total build time is reduced to times between 1 min, 55.11 secs and 2min, 5 secs (from 3 min, 12secs)

I don't think we're gaining much by including eslint in webpack

#### For production
- merged code should already be satisfying lint rules

#### For development:

Eslint in Webpack, does not help as much as eslint in the IDE 
Mostly everybody uses eslint inside their IDE and errors are highlighted directly in the source code. 
For anyone already having eslint integrated in their IDE, having webpack run eslint, is like running eslint 2x times

We also have inconsistent behavior:
- running `npm run web/desktop` watches and lints code
- running `npm run android/ios` does not use eslint

We're not monitoring eslint live for android/ios, so why should we do it for web?

Can we instead:
- suggest people enable Eslint in their IDE, promoting overall productivity
- (optionally) enforce code style through commit/push hooks (this covers not only web, but also android & ios)
- ultimately we still enforce code style through PR actions

**Comment by kidroca** [comment]
I'm getting much better results on my M1 
- current (no changes): General output time - 50sec 
- without eslint - 21sec

**Comment by roryabraham** [comment]
> (optionally) enforce code style through commit/push hooks (this covers not only web, but also android & ios)

People won't go for this, but that's okay.

> suggest people enable Eslint in their IDE, promoting overall productivity

I'd personally be fine with this, but as a backup for our hardcore vim users maybe we can just set up a separate lint script using https://www.npmjs.com/package/eslint-watch? Maybe that's not needed ... I'm sure there's a vim plugin for eslint for those hardcore vim users 🤷🏼

**Comment by roryabraham** [comment]
Overall I'm down to turn off the webpack eslint plugin, but would like to replace it with a separate eslint-watch script that can be optionally used instead 👍🏼

**Comment by kidroca** [comment]
> Overall I'm down to turn off the webpack eslint plugin, but would like to replace it with a separate eslint-watch script that can be optionally used instead 👍🏼

Ok, this makes sense, and unlike now, you would be able to have a linter running while developing android/ios as well

**Comment by kidroca** [comment]
Enabling file system cache reduced the initial build time down to 5s for me 

- current (no changes): General output time - 50sec
- ➖ without eslint - 21sec
- ➕ with Webpack file system cache - 5s

**Comment by roryabraham** [comment]
Whoa, that is faster than I expected! Couple general questions about the webpack FS cache:

- When do you have to clear the cache, if at all?
- How can you clear the cache?

**Comment by kidroca** [comment]
> * When do you have to clear the cache, if at all?

You don't need to, cache resets when there are changes in `node_modules/` (e.g. packages being updated)

> * How can you clear the cache?

Deleting `node_modules` or just `node_modules/.cache` would work

**Comment by roryabraham** [comment]
This was mislabeled. It was never a bug, just an awesome QOL improvement. Thanks so much for working on this @kidroca!
