### ISSUE TITLE
[HOLD for payment 2022-11-09] [$250] Bug: old message not loading while switching from offline to online reported by @gadhiyamanan 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11737]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go any chat which has lots of messages
2.  go to offline
3.  go back to online try to load old messages

## Expected Result:
messages should load

## Actual Result:
 old message not loading

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195211614-553a84b6-d8c3-4415-9a72-6a51f36585ed.mp4

https://user-images.githubusercontent.com/43996225/195211618-48ca49dc-ca98-4d7f-9955-264b5b5f3ac5.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665499460172419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
I actually can't even scroll at all - regardless of being offline > online again when I test this in my own account on STG.
![2022-10-12_12-18-48 (1)](https://user-images.githubusercontent.com/56830058/195329697-51d5b6dd-2c24-4792-9abe-17f1f8cb7e8b.gif)

But I can still scroll when I test this on PROD:
![2022-10-12_12-21-07 (1)](https://user-images.githubusercontent.com/56830058/195330083-c763b2d3-00c0-4634-95e0-558a02409470.gif)

Are we tackling the general issue with scrolling more broadly? I can't see it in Opensource or GH yet. Thanks eng team, this one is ready for your eyes!

**Comment by madmax330** [comment]
Yep looks like when we get back online we stop calling the command to get more chats

**Comment by madmax330** [comment]
I can repro this on my account in staging

**Comment by tienifr** [comment]
# Proposal

## Problem

- Currently, in https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/pages/home/report/ReportActionsView.js#L263  when user scroll to get old message, in function `loadMoreChats`, `ReadOldestAction` will be called and update `isLoadingMoreReportActions=true`. After that when API is successfully called or error return by BE, will update `isLoadingMoreReportActions=false`. 

``` diff
  API.read('ReadOldestAction',
        {
            reportID,
            reportActionsOffset: oldestActionSequenceNumber,
        },
        {
            optimisticData: [{
                onyxMethod: CONST.ONYX.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
                value: {
                    isLoadingMoreReportActions: true,
                },
            }],
            successData: [{
                onyxMethod: CONST.ONYX.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
                value: {
                    isLoadingMoreReportActions: false,
                },
            }],
            failureData: [{
                onyxMethod: CONST.ONYX.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
                value: {
                    isLoadingMoreReportActions: false,
                },
            }],
        });
```

- In offline mode, `ReadOldestAction` will be called first and update `isLoadingMoreReportActions=true`, but API not called => `responseData =undefined` and in function `SaveResponseInOnyx` will return void without update Onyx. So `isLoadingMoreReportActions` still being true, at this case in function `loadMoreChats` `ReadOldestAction` won't be called when user back to online and scroll to get old message.

``` diff
function SaveResponseInOnyx(response, request) {
    return response
        .then((responseData) => {
            const onyxUpdates = [];
            if (!responseData) {
+           we dont't have responseData
                return;
            }
            if (responseData.jsonCode === 200 && request.successData) {
                onyxUpdates.push(...request.successData);
            } else if (responseData.jsonCode !== 200 && request.failureData) {
                onyxUpdates.push(...request.failureData);
            }
           ...
        });
}
```

## Solution

In https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/libs/actions/Report.js add function `resetLoadMoreReportActions` to set `isLoadingMoreReportActions` in this report to false

```diff
+ function resetLoadMoreReportActions(reportID) {
+    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, { isLoadingMoreReportActions: false })
+ }
```

```diff
export {
    ...
+   resetLoadMoreReportActions
}
```
In https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/pages/home/report/ReportActionsView.js in `shouldUpdateComponent` lifecycle, when user come back online mode, we'll check `this.props.report.isLoadingMoreReportActions`, if true we'll change `isLoadingMoreReportActions` in this report to false.

```diff
if (lodashGet(nextProps.network, 'isOffline') !== lodashGet(this.props.network, 'isOffline')) {
+            if (!lodashGet(nextProps.network, 'isOffline') && this.props.report.isLoadingMoreReportActions) {
+                Report.resetLoadMoreReportActions(this.props.report.reportID)
+            }
            return true;
        }
```

https://user-images.githubusercontent.com/113963320/196002715-acf6db4f-5d44-45ee-9f68-0674d2ea04bb.mp4

**Comment by thienlnam** [comment]
@tienifr That's a great investigation - thanks for that! That's a well described issue, so we optimistically set isLoadingMoreReportActions to true. `ReadOldestAction` is not requeued when the user is back online since it's a read request, but when we reconnect, we should be calling Report.reconnect [here](https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/pages/home/report/ReportActionsView.js#L163-L175) which should reset our isLoadingReportActions to false after a successful/failed request. At that point, isLoadingMoreReportActions would be updated and then we wouldn't need to it override it here.  Could you try to investigate why that isn't happening?

**Comment by parasharrajat** [comment]
I am preoccupied with some other stuff. @thienlnam Please assign this to someone else. Thanks.

**Comment by tienifr** [comment]
@thienlnam In [here](https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/pages/home/report/ReportActionsView.js#L163-L175), `isLoadingReportActions` will be updated but `isLoadingMoreReportActions` is not updated in `Report.openReport` and `Report.reconnect`
https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/libs/actions/Report.js#L695-L725
https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/libs/actions/Report.js#L732-L758
## Solution 2
If you want to update `isLoadingMoreReportActions`  in https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/pages/home/report/ReportActionsView.js#L163-L175, we must pass `isLoadingMoreReportActions: false` to value of optimisticData in function  `openReport` and `reconnect`.

```diff
function openReport(reportID) {
    API.write('openReport',
            ...
             optimisticData: [{
                ...
                value: {
                    isLoadingReportActions: true,
+                  isLoadingMoreReportActions: false,
                },
            }],
            ...
}
``` 

```diff
function reconnect(reportID) {
    API.write('ReconnectToReport',
             ...
             optimisticData: [{
                ...
                value: {
                    isLoadingReportActions: true,
+                  isLoadingMoreReportActions: false,
                },
            }],
            ...
        });
}
```

## Solution 3
A simpler way, https://github.com/Expensify/App/blob/7044ab2b96067081c8f67191e51fa859dba66d91/src/pages/home/report/ReportActionsView.js#L263 in function `loadMoreChats` if user in offline mode we'll immediately return.

``` diff
loadMoreChats(){
       if (this.props.report.isLoadingMoreReportActions || lodashGet(nextProps.network, 'isOffline')) {
            return;
        }
        ...
}
```

**Comment by tienifr** [comment]
@thienlnam Could you please send the Upwork link that I can apply to? thanks

**Comment by slafortune** [comment]
@tienifr  - here ya go!  https://www.upwork.com/ab/applicants/1582472084181204992/suggested

**Comment by tienifr** [comment]
Thanks @slafortune, I applied to the job and the PR will be ready by October 21

**Comment by gadhiyamanan** [comment]
@slafortune Upwork job missing for reporting bonus

**Comment by tienifr** [comment]
hi @slafortune I applied to the job a while ago as in https://github.com/Expensify/App/issues/11737#issuecomment-1285231203 but haven't received the offer for the job yet, can you please help check?
thanks

**Comment by thienlnam** [comment]
cc @slafortune Looks like we're missing some payments here

**Comment by slafortune** [comment]
Sorry for my delay on this - looking for some help [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1668471936417209) and will get this done by tomorrow!

**Comment by slafortune** [comment]
@thesahindia @gadhiyamanan I've sent you both an offer for this, let me know once you've accepted that and I'll get this paid out - sorry for my delay!

**Comment by gadhiyamanan** [comment]
@slafortune applied 🎉

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by slafortune** [comment]
@thesahindia  I’m trying to wrap up this GH and am looking for the original PR that caused the issue, can you help me out with that?

**Comment by thesahindia** [comment]
> @thesahindia I’m trying to wrap up this GH and am looking for the original PR that caused the issue, can you help me out with that?

Oh sorry, I didn't see the comment. Let me check.

**Comment by thesahindia** [comment]
I think it was missed in the refactors as it was an edge case. Also it's hard to tell which specific PR should have handled this 

cc: @thienlnam

**Comment by thienlnam** [comment]
Yeah that's correct, this was likely missed during an internal refactor as an edge case.  It's been a while but it was probably this one? https://github.com/Expensify/App/pull/11439
