### ISSUE TITLE
[$250] Bug: "Hmm... it's not here" view is showing up with back and dismiss button while the page already has those buttons reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login at new dot and create a workspace
2. Open new tab > Go to old dot > log in > delete newly created workspace
3. Go back to new dot and navigate to Reimburse expenses

## Expected Result:
Back and dismiss button shouldn't be shown twice

## Actual Result:
Back and dismiss button are shown twice

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195203194-1c72fd0e-7466-44fd-9725-4407d5b366b5.mp4

https://user-images.githubusercontent.com/43996225/195203211-4bba1e86-4664-4b74-a240-d56eaf8968a1.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665509133039339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 
We need to remove FullPageNotFoundView from this component
https://github.com/Expensify/App/blob/4ff239ef81b0b06b94f00efd4026881de1465055/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L192
instead use it here to wrap https://github.com/Expensify/App/blob/d99d7c81ca9b02edf6c0151a311f881f4eea9633/src/pages/workspace/WorkspacePageWithSections.js#L97

**Comment by isabelastisser** [comment]
I was able to reproduce:


https://user-images.githubusercontent.com/31258516/196668634-4487633c-1044-46bb-b643-b91d53f09a73.mp4

**Comment by Puneet-here** [comment]
`WorkspaceReimburseView` is a child of `WorkspacePageWithSections` which contains a header 
https://github.com/Expensify/App/blob/b1e0bd64b6d99ba626f1fd9490a0a17bb729051c/src/pages/workspace/reimburse/WorkspaceReimbursePage.js#L25-L33

At `WorkspaceReimburseView` we check if `this.props.policy` is empty (it will be empty when it's deleted) and showing `FullPageNotFoundView ` which has it's own header so that's why we are seeing two headers https://github.com/Expensify/App/blob/b1e0bd64b6d99ba626f1fd9490a0a17bb729051c/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L192

we can also create a prop and use it `FullPageNotFoundView` to hide the header but I believe when a user clicks at any section inside a deleted workspace they should see not found page not only at members page and Reimburse View

**Comment by stitesExpensify** [comment]
Looks good to me! @NicMendonca can you create an upwork job so that @Puneet-here can apply? Thanks!

**Comment by NicMendonca** [comment]
Opps, sorry! Job post here: https://www.upwork.com/jobs/~011a3d442964c96c36

**Comment by Puneet-here** [comment]
> @Puneet-here how's it looking?

I was waiting for the upwork job. I have applied to the job and raised the PR.

**Comment by NicMendonca** [comment]
@Puneet-here @rushatgabhane hired :)

**Comment by NicMendonca** [comment]
@Puneet-here is working on PR - this isn't overdue

**Comment by NicMendonca** [comment]
I am about to go OOO for a week, so re-assigning.

**Comment by isabelastisser** [comment]
Hey @Puneet-here , can you please provide an update on your progress? Thanks!

**Comment by isabelastisser** [comment]
OOO, reassigning.

**Comment by sakluger** [comment]
Sorry for the delay everyone! Everyone has been paid out for this one, and the Upwork post is closed.

**Comment by Puneet-here** [comment]
@sakluger, It's also eligible for the reporting bonus. I only received $250 for the fix.

**Comment by Puneet-here** [comment]
@sakluger, can you please look at the comment above?

**Comment by Puneet-here** [comment]
Bump @sakluger

**Comment by dylanexpensify** [comment]
Will look into this for ya Puneet!

**Comment by dylanexpensify** [comment]
@Puneet-here sent you the bonus! Sorry for the delay here!

**Comment by dylanexpensify** [comment]
@sakluger can we make sure to get the [checklist here](https://github.com/Expensify/App/issues/11730#issuecomment-1302539162) completed when ya get a chance! TY! 🙇‍♂️

**Comment by Puneet-here** [comment]
Thank you @dylanexpensify
