### ISSUE TITLE
App crashes when trying to open IOU details - reported by @adeel0202

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#11754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
1. Open any chat with IOU
1. Click on View details to open details

## Expected Result:
Describe what you think should've happened

1. IOU details open

## Actual Result:
Describe what actually happened

1. App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

No

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.13-2 (Staging) 
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665579836146209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I am getting report action which is undefined 
![image](https://user-images.githubusercontent.com/36083550/195373392-ebe77ca9-a08e-47d4-9a42-bcbcfcbbf88e.png)


I have narrowed down the issue to the react-onyx-bump in which we have refactored the way we merge stuff and it seems like mergeCollection action is not working as expected or as it worked before this change. https://github.com/Expensify/react-native-onyx/pull/186

coming from this PR https://github.com/Expensify/App/pull/11723

**Comment by mountiny** [comment]
cc @Szymon20000 @luacmartins

**Comment by adeel0202** [comment]
@mountiny I'm expecting reporting bonus.

**Comment by adeel0202** [comment]
Also, I'm still able to reproduce it so not sure why it is closed.

**Comment by michaelhaxhiu** [comment]
https://www.upwork.com/jobs/~01dadf0587f9dca0fe

**Comment by adeel0202** [comment]
@michaelhaxhiu I have applied.

**Comment by michaelhaxhiu** [comment]
Paid.

**Comment by marcaaron** [comment]
What about the changes in Onyx broke merging? Can you leave some more detailed investigation here?

**Comment by marcaaron** [comment]
@vitHoracek @luacmartins

**Comment by tgolen** [comment]
Yeah, I think we should be actively looking to figure out what is broken in Onyx and fixing it at the source rather than just reverting it.

**Comment by mountiny** [comment]
I completely agree, I have opted for quicker solution as I did not see clearly what is wrong and it was getting toward the end of the day. Since the revert fixed it, I opted for that. 

Good job spotting the key issue @marcaaron

**Comment by mountiny** [comment]
Haha, thanks, the other account is also me and I get email notifications for those tags so I wont miss it :D knew this would happen
