### ISSUE TITLE
[$250]  mWeb/safari -The transition to conversation is not smooth when using fingers from right to left

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.epensify.com/
2. Sign in with any account
3. Click any conversation
4. Close NewDot
5. Open NewDot
6. Open the chat by swiping from right to left.

## Expected Result:
The conversation should open smoothly and without showing doubling pages

## Actual Result:
The transition to conversation is not smooth when I use my fingers from right to left

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.13.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195377865-0c6996a0-4420-42c0-a1ec-7fb71ab5aab5.MP4

https://user-images.githubusercontent.com/93399543/195377871-8b74c74e-1d1c-41bf-94da-f6132363f2d8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Veeeery interesting, this seems like a difficult one to debug but let's see if some contributors can figure it out 👍 👍

**Comment by Beamanator** [comment]
Wow great catch thanks @aimane-chnaif !
