### ISSUE TITLE
Chat- Crash when trying to open IOU details

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any chat
3. Click on + button/Request money
4. Finish the request money process
5. Click on IOU

## Expected Result:
IOU details should open

## Actual Result:
App crashed all the time

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.13-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195373584-6a1b03e3-a876-4559-94d8-6bac2e8f8557.mp4
[Bug5773563_Crash_1210.txt](https://github.com/Expensify/App/files/9765990/Bug5773563_Crash_1210.txt)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
Already reported #11755. Closing this one.

**Comment by mountiny** [comment]
Handled here https://github.com/Expensify/App/issues/11754
