### ISSUE TITLE
Web - Workspace -Delete and New Workspace options go beyond the conversation history

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with your account
3. Go to Setting - Workspace
4. Select " ... " dots

## Expected Result:
Delete and New Workspace options should not go beyond the conversation history

## Actual Result:
Delete and New Workspace options go beyond the conversation history

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.13.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![WS](https://user-images.githubusercontent.com/93399543/195384644-b0670763-6882-4fef-acd6-70e9e2399a10.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Not worth fixing.
