### ISSUE TITLE
mWeb - Chat - Display mode switches from portrait to landscape when turning phone horizontally

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/9143

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open any chat
3. Turn the phone to horizontal position

## Expected Result:
According to iPhone requirements for PR 9143 (link https://youtu.be/kuv9in8vtbk and attached videos) nothing should happen upon turning device.

## Actual Result:
iPhone switches to landscape mode from portrait mode upon turning device with chat opened, which is not expected.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.13.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195392510-f0a65a86-e3d4-4ea8-88fe-ca6d95e2f109.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
So I am not sure I agree that this is a bug and I think it warrants a larger discussion on how we want to handle rotation. I agree that the PR said it should not rotate, but I think it's fine that it is rotating for now. Closing for now!
