### ISSUE TITLE
[HOLD for payment 2022-11-04] [$250] Desktop - Split Bill “What’s it for?” is highlighted if double tap on the selected user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login as HT user
2. Select Split bill > Enter amount > Next > Select some user
3. Select next
4. Double tap on any user

## Expected Result:
Nothing should happen

## Actual Result:
“What’s it for?” is hightailed if double tap on the selected user
"Who Was There?" is highlighted if douple tap on the requestor

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.2.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="859" alt="Bug5774001_what" src="https://user-images.githubusercontent.com/43996225/195429565-b5fadf76-ee17-4ba8-bd9c-aa451073aa30.png">

https://user-images.githubusercontent.com/43996225/195429569-7f728966-64d9-44a4-9c7f-acb866b43647.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment]
So I was able to replicate. but this seeems to be happening in more than just the `split bill`, I was able to replicate in the `Request Money` and the `Send Money` as well.
Also if you douple tap the requestor (me in my case) it also highlights the `WHO WAS THERE`.
I'm updating the description and the title

**Comment by sketchydroide** [comment]
Also this is happening in Web and Desktop, but was not able to replicate on Android.

**Comment by sketchydroide** [comment]
setting this as an external

**Comment by mollfpr** [comment]
### Proposal

Adding `user-select: none` to the text input label style to prevent selected/highlighted style to the label.
```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 4363f1825..aa9853773 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -704,6 +704,8 @@ const styles = {
         fontFamily: fontFamily.GTA,
         width: '100%',
         textAlign: 'left',
+        userSelect: 'none',
+        WebkitUserSelect: 'none',
     },

     textInputLabelBackground: {
```

https://user-images.githubusercontent.com/25520267/195786582-7e06a465-feab-44aa-a877-9abd560002b3.mov


https://user-images.githubusercontent.com/25520267/195787003-8af2e558-4a48-4447-96cc-b8a80cee744a.mp4



https://user-images.githubusercontent.com/25520267/195787864-9bc523c4-514e-4dc4-be3d-9de68c4272cd.mov

**Comment by bernhardoj** [comment]
**Proposal**

The problem is each row of user is not selectable because the `TouchableOpacity` is disabled. So, when we double click, it will try to select other near text (even though it's not always the nearest one). Instead of making the **What’s it for?** and **Who Was There?** unselectable, we can make the row become selectable.

**_OptionRow.js_**
```diff
<TouchableOpacity
    ...
   disabled={props.isDisabled}
   style={[
       styles.flexRow,
       styles.alignItemsCenter,
       styles.justifyContentBetween,
       styles.sidebarLink,
       styles.sidebarLinkInner,
       StyleUtils.getBackgroundColorStyle(props.backgroundColor),
       props.optionIsFocused ? styles.sidebarLinkActive : null,
       hovered && !props.optionIsFocused ? props.hoverStyle : null,
       props.isDisabled && styles.cursorDisabled,
+       styles.userSelectText
    ]}
>
...
</TouchableOpacity>
```

**Result**

https://user-images.githubusercontent.com/50919443/196033801-9c19cc41-12e3-42be-a2de-f3e06f6ec59b.mov

**Comment by thesahindia** [comment]
@mollfpr, your proposal doesn't fix the highlighting of "WHO WAS THERE?".
@bernhardoj, I am not sure if we wanna make the text selectable for option row, we are using it at many places and it will/can cause problems e.g. at invite members page if a user selects a contact and then tries to unselect it then the text will be selected and user will have to press again to unselect the user

**Comment by mollfpr** [comment]
### Updated Proposal
Adding `user-select: none` to `Hoverable` component with props `containerStyles`. This will prevent the user selection from the upper component on `TouchableOpacity`.
```diff
diff --git a/src/components/OptionRow.js b/src/components/OptionRow.js
index 0a6a9f7b7..3a93806ca 100644
--- a/src/components/OptionRow.js
+++ b/src/components/OptionRow.js
@@ -131,7 +131,11 @@ const OptionRow = (props) => {
     const avatarTooltips = props.showTitleTooltip && !props.option.isChatRoom && !props.option.isArchivedRoom ? _.pluck(displayNamesWithTooltips, 'tooltip') : undefined;

     return (
-        <Hoverable>
+        <Hoverable
+            containerStyles={[
+                props.isDisabled && styles.userSelectNone,
+            ]}
+        >
             {hovered => (
                 <TouchableOpacity
                     ref={el => touchableRef = el}
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 4363f1825..fd111c360 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -2674,6 +2674,11 @@ const styles = {
         userSelect: 'text',
     },

+    userSelectNone: {
+        userSelect: 'none',
+        WebkitUserSelect: 'none',
+    },
+
     screenCenteredContainer: {
         flex: 1,
         justifyContent: 'center',
```

I'm using `props.isDisabled` just in case if we only want the prevent user-select on disabled `TouchableOpacity`.

**Result**

https://user-images.githubusercontent.com/25520267/196119914-a5176a52-6e6b-43b9-b894-a0baaea6b7b9.mov

**Comment by bernhardoj** [comment]
> @mollfpr, your proposal doesn't fix the highlighting of "WHO WAS THERE?". @bernhardoj, I am not sure if we wanna make the text selectable for option row, we are using it at many places and it will/can cause problems e.g. at invite members page if a user selects a contact and then tries to unselect it then the text will be selected and user will have to press again to unselect the user

I see. In that case, the `user-select` value should be `none` like what @mollfpr does. But I would prefer to put the style on `TouchableOpactiy`.

**Comment by thesahindia** [comment]
> I see. In that case, the user-select value should be none like what @mollfpr does. But I would prefer to put the style on TouchableOpactiy.

That doesn't work.

@sketchydroide, I like @mollfpr's new [proposal](https://github.com/Expensify/App/issues/11771#issuecomment-1280438737). We will be making the changes [here](https://github.com/Expensify/App/blob/f0735d8cda7d97fafb4af748ccc644a001b485ef/src/components/OptionRow.js#L134).

C+ reviewed 🎀👀🎀

@mollfpr, try to link the code file in your proposals.

**Comment by tjferriss** [comment]
Upworks job posting is live https://www.upwork.com/jobs/~01b4d1935870536df3

Internal posting - https://www.upwork.com/ab/applicants/1582498976580591616/job-details

**Comment by sketchydroide** [comment]
not overdue

**Comment by tjferriss** [comment]
@mollfpr and @thesahindia can you please both apply for the job in Upworks? https://www.upwork.com/jobs/~01b4d1935870536df3

**Comment by mollfpr** [comment]
@tjferriss Applied, thank you!

**Comment by tjferriss** [comment]
I've hired @thesahindia as Contributor + and @mollfpr to fix the issue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sketchydroide** [comment]
not overdue

**Comment by tjferriss** [comment]
Payments have been issued to @thesahindia and @mollfpr, the contract has been completed, and the Upwork post has been closed. Great job everybody!
