### ISSUE TITLE
[HOLD for payment 2023-02-01] Investigate overuse of Onyx in VBBA setup flow

### ISSUE THREAD

**Issue by nkuoch** [Expensify/App#11777]
Coming from https://github.com/Expensify/App/issues/11770#issuecomment-1276723757

**Comment by nkuoch** [comment]
Will try to work on it next week

**Comment by nkuoch** [comment]
No time for this yet

**Comment by nkuoch** [comment]
No update

**Comment by JmillsExpensify** [comment]
My two cents: This isn't technically a bug as much as much as a performance improvement. I removed the `bug` label as a result.

**Comment by nkuoch** [comment]
It's because we save in Onyx after each key types in the input field. Alternative would be to put it in the state while we type, and in onyx only on blur .. but not sure it's worth fixing.

**Comment by nkuoch** [comment]
Nothing from Contributor. Closing.
