### ISSUE TITLE
[$250] mWeb/Safari - Workspace - Page jumps up and hides the search field when I focus in "Add a personal message" field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11776]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login
2. Go to Settings->Workspase->Manage members->Invite
3. Enter the email in the search field
4. Focusing in "Add a personal message" field

## Expected Result:
Page shouldn't jumps up 

## Actual Result:
Page jumps up and search field disappear unlike the app

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2-13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195432978-7a0a873d-8ffa-470c-98b4-4b18cc3037d9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
We will move this field to a new page after implementing push to page.

**Comment by AndrewGable** [comment]
cc @tgolen for keyboard bugs

**Comment by tgolen** [comment]
I've added a HOLD to this and added it to the tracking issue: https://github.com/Expensify/App/issues/10273

**Comment by sophiepintoraetz** [comment]
@tgolen - new to the BZ (old contributor) process - what's the best practise managing issues that are on hold? Do we still need to source proposals?

**Comment by sophiepintoraetz** [comment]
I'm going to close for now, we can reopen when it's time to action!

**Comment by JmillsExpensify** [comment]
Opening this back up now that related PR is merged. Let's re-test this and see if it's still a thing.

**Comment by sophiepintoraetz** [comment]
Hmm, i don't think this particular issue is happening any more but I do think there's a non-intuitive flow in expecting the user to scroll down to the welcome message (if you don't know it's there, how do you know to scroll down to look for it?) But I think that's a separate issue.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/42940078/199172346-ea2a57dd-04ad-49b9-a4aa-df620bc0ee8c.png">

https://user-images.githubusercontent.com/42940078/199172259-0332ff82-2fa1-4348-b1e6-121565c628bd.MP4

**Comment by JmillsExpensify** [comment]
Awesome, thanks for re-testing! And agreed, that's a separate issue though it will be resolved in the move to push to page in N8.
