### ISSUE TITLE
BUG: Copy & pasting the link in Composer field duplicates the link reported by @aneequeahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app in browser.
2. Click on any LHN report having Link message.
3. Copy link message using option copy to clipboard
4. Paste the copied link in Composer/message-input-field.

## Expected Result:
Link should be pasted just once.

## Actual Result:
Link is shown twice when pasted in Composer/message-input-field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195477299-c4f11a42-209b-4f01-a7ee-bbc8450d6a5c.mp4

https://user-images.githubusercontent.com/43996225/195477316-e83b859d-9609-43ed-9216-06f9c7425691.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665547942629219?thread_ts=1663376534.991039&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Guys, I ready to report bugs but I can't do that here, can you guys invite me to slack, I emailed but I didn't saw the response yet, my email is hungvv193@gmail.com

**Comment by mateocole** [comment]
@kavimuru actually i am not able to reproduce this on chrome, hmmm... perhaps try clearing your cache and see if this persists?

**Comment by roryabraham** [comment]
This is not a bug, it's a feature request. You're just seeing the markdown format of the link like `[text](url)`, but when the text and url are the same it looks like `[url](url)`. So the new feature would be something like "strip markdown links from pasted text if the text portion of the url matches the full url"

Will ask whether this is a change we want to push forward

**Comment by roryabraham** [comment]
Chatting internally about this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1665768733905399)

**Comment by mateocole** [comment]
@roryabraham It looks like in lieu of that convo and building towards whatsapp quality vs slack for now, we are not going to support markdown at the moment, is that correct?

**Comment by roryabraham** [comment]
Yeah, I think the consensus here was `:donothing:`
