### ISSUE TITLE
Web - New Chat - Spaces in the search field are highlighted in blue after pressing the Enter key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on FAB button->New Group
4. Type a few spaces in the search field and press Enter

## Expected Result:
Spaces shouldn't be highlighted in blue

## Actual Result:
Spaces are highlighted in blue

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195636038-1f704c26-76e4-4a10-bd12-cbc4bd858542.mp4

![Untitled (1)](https://user-images.githubusercontent.com/93399543/195636126-bcfdb891-249c-477b-a13c-5b9091affa15.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
According to https://github.com/Expensify/App/pull/11805#issuecomment-1277818962 this is a feature, not a bug, so that the user can start typing a new name and it will clear out what was entered.
