### ISSUE TITLE
Android- Workspace -Save and Continue button is hidden or partially visible when Connect manually

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with your account
3. Go to Setting - Workspace
4. Select Connect Bank Account
5. Select Connect manually
6. Type routing number
7. Than type account number

## Expected Result:
Save and Continue button should be fully visible when Connect manually

## Actual Result:
Save and Continue button is hidden or partially visible when Connect manually

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195632696-e78891e9-b666-4d69-9b11-90564b0e5903.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
I'm a little confused on the expected behavior here - there just isn't enough space on the screen for the continue button and it's not like the button can just float there since then you would get overlap in the input field

cc @Expensify/design What do you think about this?

**Comment by shawnborton** [comment]
This is not a bug - this is the desired behavior. We don't want the Save and Continue button to block the form control, so it sits right below it.
