### ISSUE TITLE
[HOLD for payment 2022-11-04] [$250] BUG: Enter password field shows on add bank account page while trying to add bank accounts consecutively reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings > Payments
2. Click Add payment method > Bank account
3. Complete the process on Plaid to add a new bank account
4. On Add bank account page, choose an account
5. Enter your password
6. Click save & continue
7. Click Continue
8. Again click Add payment method > Bank account (Notice Enter Expensify password field shows on add bank account page)
9. Again complete the process on Plaid to add another bank account (Notice Enter Expensify password field shows on add bank account page without choosing an account)

## Expected Result:
Enter Expensify password field doesn't show until an account is chosen

## Actual Result:
Enter Expensify password field shows even when the account is not chosen

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** Could not test in Production
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195675423-3483ed67-9c3a-41eb-8270-7a766b9ef3b5.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665648921463259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/195675445-955d7ecd-ce90-4718-9ee5-0e7780c94532.mov

**Comment by sakluger** [comment]
I was able to reproduce this issue, although it's easy to miss, since the password field only shows in the RHN briefly before the Plaid modal pops up. Passing along to engineering.

**Comment by mountiny** [comment]
I see so the problem is that the password page flashes there for a second when doing it second time. I think this issue can be External

**Comment by sobitneupane** [comment]
**Proposal**
**Reason:** 
https://github.com/Expensify/App/blob/e38df100d62d197689bb16888a3ac7859f157681/src/pages/AddPersonalBankAccountPage.js#L63-L70

Here, `componentDidMount` clears `personalBankAccount` currently being setup. But before that, state `selectedPlaidAccountID` gets its value from `this.props.personalBankAccount`. 

Solution:
```diff
this.state = {
-         selectedPlaidAccountID: this.props.personalBankAccount.plaidAccountID, 
+         selectedPlaidAccountID: '', 
}
```
This change was recently made in [this PR](https://github.com/Expensify/App/pull/11750) by @nkuoch. Might be an intended change.

cc: @nkuoch

**Comment by parasharrajat** [comment]
Hmm, my intuition says that we can't just do this change as above. I will take a look at that PR and try to understand the matter.

**Comment by parasharrajat** [comment]
Let me review it first.

**Comment by parasharrajat** [comment]
Ok, it seems that we can remove the state initialization. We are clearing the data on `componentDidMount` thus this does not make sense together. Also, every time we open the connect account page/add a bank account, the process is started again. So the user will select the bank account each time. 

@sobitneupane's [proposal](https://github.com/Expensify/App/issues/11816#issuecomment-1279768978) looks good to me. 

cc: @mountiny 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by mountiny** [comment]
Thank you @parasharrajat! @sobitneupane Feel free to start the PR!

**Comment by alexpensify** [comment]
Job has been created here: https://www.upwork.com/ab/applicants/1583559459428450304/job-details
External Link: https://www.upwork.com/jobs/~01f174bbce556e4071

**Comment by thesahindia** [comment]
EEP! None of us noticed that we have a dupe issue https://github.com/Expensify/App/issues/11874. We also have a [PR](https://github.com/Expensify/App/pull/11959) for it.

cc: @MonilBhavsar

**Comment by mountiny** [comment]
Thanks for the ping, gonna look into that

**Comment by parasharrajat** [comment]
Waiting on the signal from Vit.

**Comment by mountiny** [comment]
Signal sent @parasharrajat

**Comment by alexpensify** [comment]
Based on the hold notice, I'll check tomorrow!

**Comment by mallenexpensify** [comment]
@sobitneupane @parasharrajat @adeel0202 can you apply for the job here then comment on this issue? https://www.upwork.com/jobs/~01f174bbce556e4071

**Comment by sobitneupane** [comment]
@mallenexpensify Applied.

**Comment by mountiny** [comment]
@mallenexpensify will pay this out today.

**Comment by mallenexpensify** [comment]
All hired, please accept and I'll pay out

**Comment by mallenexpensify** [comment]
Everyone's paid!
