### ISSUE TITLE
[HOLD for payment 2022-11-09] [$250] Bug: Space after emoji doesn't get added for edit field like main composer reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat > Send message > Edit
2. Click on emoji button and select an emoji

## Expected Result:
The space should be added after emoji like composer

## Actual Result:
Space doesn't get added after adding emoji

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** https://user-images.githubusercontent.com/43996225/195677511-af2c2bc9-0443-44db-bcd3-37445b0206b6.mp4
https://user-images.githubusercontent.com/43996225/195677500-769c3c7d-6497-4561-91c5-6dd2b328e982.mov
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665670095261569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal
We need to add a new variable emojiWithSpace and need to use it like this:
```js
    addEmojiToTextBox(emoji) {
        const emojiWithSpace = `${emoji} `;
        const newComment = this.state.draft.slice(0, this.state.selection.start)
            + emojiWithSpace + this.state.draft.slice(this.state.selection.end, this.state.draft.length);
        this.setState(prevState => ({
            selection: {
                start: prevState.selection.start + emojiWithSpace.length,
                end: prevState.selection.start + emojiWithSpace.length,
            },
        }));
        this.updateDraft(newComment);
    }
```
https://github.com/Expensify/App/blob/44c75aada4405bbff7b1c992e690b616c2c659d4/src/pages/home/report/ReportActionItemMessageEdit.js#L158
we also do the same at [reportActionCompose.js](https://github.com/Expensify/App/blob/44c75aada4405bbff7b1c992e690b616c2c659d4/src/pages/home/report/ReportActionCompose.js#L319)

**Comment by parasharrajat** [comment]
@Puneet-here 's [proposal](https://github.com/Expensify/App/issues/11818#issuecomment-1278034294) looks good to me. 

cc: @sketchydroide 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by sketchydroide** [comment]
not overdue...

**Comment by sketchydroide** [comment]
@davidcardoza I think no regressions were found, so I think we are good to follow with the payment.

**Comment by davidcardoza** [comment]
Offer sent to @parasharrajat for payment

**Comment by hammad-6304** [comment]
@kavimuru I Have read the proposal on UpWork so i head to this issue. As per above discussion I can see the issue has been resolved already. Can you please confirm me is it still open & need to fix in an enhanced manner? 
Please let me know just looking forward to hear from your side. 
Thanks

**Comment by kavimuru** [comment]
@hammad-6304 Yes, it is fixed now.

**Comment by sketchydroide** [comment]
@davidcardoza anything for us to do here?

**Comment by Puneet-here** [comment]
Hi @davidcardoza, could you please send me an offer or provide the job link since it qualifies for fixing and reporting bonus.

**Comment by davidcardoza** [comment]
@Puneet-here Sent

**Comment by parasharrajat** [comment]
There was no Upwork job created for this @davidcardoza. C+ is still waiting for payment on this.

**Comment by davidcardoza** [comment]
@parasharrajat I sent you a payment on Upwork for the job. Can you accept?
https://www.upwork.com/jobs/~015fc187d3b8e60dfa

**Comment by Puneet-here** [comment]
@davidcardoza, I only received $250. I believe the total amount should be $500, $250 for the fix and $250 for the reporting

**Comment by Puneet-here** [comment]
Bump @davidcardoza

**Comment by davidcardoza** [comment]
@Puneet-here i processed an additional $250

**Comment by Puneet-here** [comment]
I have accepted the offer, thanks

**Comment by parasharrajat** [comment]
@davidcardoza I am still awaiting payment on this.

**Comment by parasharrajat** [comment]
Bump :arrow_up:

**Comment by davidcardoza** [comment]
@parasharrajat I am showing a $250 payment was processed and accepted by you on the job - https://www.upwork.com/jobs/~01cfb61bdcd6543656

<img width="1764" alt="image" src="https://user-images.githubusercontent.com/6643649/203454439-cdf23efb-23c2-491f-89f8-1b4d055b7522.png">

**Comment by parasharrajat** [comment]
@davidcardoza  I have only accepted the offer. You still need to complete the payment and complete it.

**Comment by davidcardoza** [comment]
Ah my bad, I processed the payment now.

**Comment by parasharrajat** [comment]
Thank you.

**Comment by Puneet-here** [comment]
@davidcardoza, the payment is due. Can you please approve the milestone ([job](https://www.upwork.com/jobs/Space-after-emoji-doesn-get-added-for-edit-field-like-main-composer-11818_~01cfb61bdcd6543656))

**Comment by davidcardoza** [comment]
Done.
