### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Bug: At policy expense chat the welcome message in spanish contains : tada: instead of 🎉 reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Create a workspace
2. Go to preferences > change language to espanol
3. Go to policy expense chat

## Expected Result:
The emoji should be shown instead of the alias

## Actual Result:
alias is shown in spanish copy instead of :tada:

## Workaround:
visual

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="Screenshot (245)" src="https://user-images.githubusercontent.com/43996225/195678582-a249d89b-9b9c-4af2-8ef8-43caffdb86a7.png">
<img width="1064" alt="Screenshot 2022-10-13 at 7 45 50 PM" src="https://user-images.githubusercontent.com/43996225/195678608-8b9f52f0-bf88-4a44-8340-f150b60e3501.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665671884337269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
###Proposal

We need to add :tada: instead of `:tada:` here
https://github.com/Expensify/App/blob/44c75aada4405bbff7b1c992e690b616c2c659d4/src/languages/es.js#L213

**Comment by davidcardoza** [comment]
Coming back from OOO. Puneet laid out what needs to be updated - replacing :tada: with the  🎉 emoji. Assigning out to engineering.

**Comment by cead22** [comment]
I'm actually not sure if we should hardcode the emoji, or fix whatever logic should be rendering it. But it seems reproducible so going to send to Demolition. If you think this should be fixed by contributors feel free to assign to them

**Comment by Puneet-here** [comment]
> I'm actually not sure if we should hardcode the emoji, or fix whatever logic should be rendering it. 

@cead22, we are using emoji at all the places, I think we used alias by mistake. 
Here in the english copy we are using the emoji
https://github.com/Expensify/App/blob/ca501d965217c42ddc30f3516c1db7c10361c461/src/languages/en.js#L213
we need to use the same at es.js instead of ` :tada: `
https://github.com/Expensify/App/blob/ca501d965217c42ddc30f3516c1db7c10361c461/src/languages/es.js#L213

**Comment by stitesExpensify** [comment]
Yep I think it was just a copy/paste gone wrong. I'll make a quick pr

**Comment by Puneet-here** [comment]
Can I raise the PR we just need to make the change like proposed [here](https://github.com/Expensify/App/issues/11820#issuecomment-1278032652)

**Comment by stitesExpensify** [comment]
Go for it! We'll need to make an external job and stuff though

**Comment by stitesExpensify** [comment]
@davidcardoza can you make an upwork job for @Puneet-here please?

**Comment by parasharrajat** [comment]
Do we need C+ for this? Please unassign me if not needed.

**Comment by Puneet-here** [comment]
@stitesExpensify, I have raised the [PR](https://github.com/Expensify/App/pull/12002).

**Comment by stitesExpensify** [comment]
Not needed IMO. Thanks @parasharrajat

**Comment by stitesExpensify** [comment]
bump @davidcardoza

**Comment by davidcardoza** [comment]
Job posted -  https://www.upwork.com/jobs/~014b66e3d5dca7e737

**Comment by Puneet-here** [comment]
Applied to the job.

**Comment by davidcardoza** [comment]
Hired @Puneet-here to fix the issue.

**Comment by davidcardoza** [comment]
@Puneet-here the job post is here - https://www.upwork.com/jobs/~017f9db81a3fa55760 can you apply?

**Comment by Puneet-here** [comment]
Applied!

**Comment by davidcardoza** [comment]
accepted

**Comment by davidcardoza** [comment]
Yes payment to @Puneet-here was processed via Upwork.

**Comment by Puneet-here** [comment]
@davidcardoza, I believe this is also eligible for reporting, I only got the fixing compensation.

**Comment by davidcardoza** [comment]
@Puneet-here You're right, I re-hired you for the same job to apply an additional $250 payment.

**Comment by Puneet-here** [comment]
@davidcardoza, I have accepted the offer.

**Comment by davidcardoza** [comment]
Paid.
