### ISSUE TITLE
BUG: Web / Chrome - Add attach button doesn't do anything

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NetDot and login
2. Open any chat
3.  Click on  `+` in compose field  > "Add attachment" 

## Expected Result:
Should open file selector from the computer

## Actual Result:
Does nothing

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.14-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/43996225/195706630-42f688b2-eaa4-4df4-8a9e-18637321cee1.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665683715227409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
Unable to reproduce it. @kavimuru 


https://user-images.githubusercontent.com/31258516/197184087-125466af-7742-4851-9eca-563a87dfd6b0.mp4

**Comment by kavimuru** [comment]
@isabelastisser I was not able to reproduce. Please check this thread https://expensify.slack.com/archives/C01GTK53T8Q/p1665683715227409
