### ISSUE TITLE
[HOLD for payment 2022-11-16] [$500] ios -Conversation - Offline - `Save changes` button is disabled when opened  to edit the comment for the second time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in an any account
2. Disable the internet connection in the main testing device
3. Click/Tap on the Pencil icon to activate the edit message box
4. Edit the message to something new and save the changes
5. Open the message editing function again

## Expected Result:
`Save changes` button should not be disabled as it was active in step 3

## Actual Result:
The `Save changes`  button is disabled when it was opened for the second time to edit the message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS 

**Version Number:** 1.2.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/93399543/195699074-432cc03e-216e-4b69-9cd5-f7e0ed3eaeda.mp4

<img src="https://user-images.githubusercontent.com/43996225/195692216-745d16f1-9b3c-4914-a856-c827ed6b0e9e.jpg" width="40%" height="40%">
**Expensify/Expensify Issue URL:** 

**Issue reported by:** applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
Hey @kavimuru - can you clarify the expected/actual results? From your video (and my testing) it looks like the **actual** result is that the button IS greyed out, and the **expected** would be that it isn't - so the reverse of what you've written. Is that correct?

**Comment by hungvu193** [comment]
I also can't reproduce this on iPhone 14 pro and Iphone 12, tested on latest code on main branch.

**Comment by kavimuru** [comment]
@dangrous Sorry for the late reply. I have edited the title and steps.

**Comment by dangrous** [comment]
No worries! With the updates, this is definitely happening. Seems like something that can be worked on externally, and will switch to weekly.

**Comment by abekkala** [comment]
https://www.upwork.com/ab/applicants/1582812257322721280/job-details

https://www.upwork.com/jobs/~012285a32f32921c68

**Comment by abekkala** [comment]
testing the `External` label

**Comment by abekkala** [comment]
Changed to $500
https://www.upwork.com/nx/job-post/custom/preview?uid=1582812257322721280

**Comment by furkanuzundev** [comment]
# Proposal

No matter how much it seems to be caused by the button, the root of the problem lies in the `<OfflineWithFeedback /> `component.

When user offline and edit a message, `isOfflinePendingAction` is returning **true** and it's trigger `needsOpacity` variable.So when i press second time, it still think need opacity because `isOfflinePendingAction` still return true even if you already edit and save changes.


# Workaround

1. Pass 'draftMessage' to <OfflineWithFeedback /> component as a props from `<ReportActionItem /> `.

```javascript
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index 6c6a85269..0157d126e 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -198,6 +198,7 @@ class ReportActionItem extends Component {
                                     pendingAction={this.props.action.pendingAction}
                                     errors={this.props.action.errors}
                                     errorRowStyles={[styles.ml10, styles.mr2]}
+                                    draftMessage={this.props.draftMessage}
                                 >
                                     {!this.props.displayAsGroup
                                         ? (
```

2. Add draftMessage into needsOpacity condition.

```javascript
diff --git a/src/components/OfflineWithFeedback.js b/src/components/OfflineWithFeedback.js
index c02441f61..7de34dc04 100644
--- a/src/components/OfflineWithFeedback.js
+++ b/src/components/OfflineWithFeedback.js
@@ -49,11 +49,16 @@ const propTypes = {
     /** Additional style object for the error row */
     errorRowStyles: stylePropTypes,
 
+    /** User draft to update message */
+    // eslint-disable-next-line react/forbid-prop-types
+    draftMessage: PropTypes.any,
+
     ...withLocalizePropTypes,
 };
 
 const defaultProps = {
     pendingAction: null,
+    draftMessage: null,
     errors: null,
     shouldShowErrorMessages: true,
     onClose: () => {},
@@ -85,7 +90,7 @@ const OfflineWithFeedback = (props) => {
     const isOfflinePendingAction = props.network.isOffline && props.pendingAction;
     const isUpdateOrDeleteError = hasErrors && (props.pendingAction === 'delete' || props.pendingAction === 'update');
     const isAddError = hasErrors && props.pendingAction === 'add';
-    const needsOpacity = (isOfflinePendingAction && !isUpdateOrDeleteError) || isAddError;
+    const needsOpacity = (isOfflinePendingAction && !isUpdateOrDeleteError && !props.draftMessage) || isAddError;
     const needsStrikeThrough = props.network.isOffline && props.pendingAction === 'delete';
     const hideChildren = !props.network.isOffline && props.pendingAction === 'delete' && !hasErrors;
     let children = props.children;
```

3. Bingo!

https://user-images.githubusercontent.com/30953070/199100899-2f89fd34-fbe7-42b3-b516-b0c3995bf3cb.mov

**Comment by Valliappan21** [comment]
### Proposal

1. active Network state is maintained in props.network.isOffline
2. Refernce issue  [https://github.com/Expensify/App/blob/6522435ef9d6c1a7f47b89750e022503a3a61c12/src/pages/home/report/ReportActionItemMessageEdit.js#L257](url)

**Solution**

- Toggle button disable state based on props.network.isOffline
- So when network state change-> state variable gets updated-> button state toggle from enable/disable

**Comment by dangrous** [comment]
@furkanuzundev (and @eVoloshchak) - agreed, this looks great! I will go ahead and assign you.

Only comment I have - when you're making the PR, would love to see if there's a way to not have to use `eslint-disable-next-line react/forbid-prop-types`. Thanks!

**Comment by furkanuzundev** [comment]
@eVoloshchak @dangrous Thanks for your feedback .

`when you're making the PR, would love to see if there's a way to not have to use eslint-disable-next-line react/forbid-prop-types`

It's removed and pushed with the PR.

I have submit a proposal from upwork and PR is ready to review as you can see. 🎀

**Comment by abekkala** [comment]
@eVoloshchak @dangrous  can I get a quick update here?

**Comment by abekkala** [comment]
eVoloshchak and furkanuzundev have been hired via Upwork

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by abekkala** [comment]
Can you identify the PR that caused this bug? and link it here?

**Comment by furkanuzundev** [comment]
@abekkala https://github.com/Expensify/App/pull/12426
