### ISSUE TITLE
[$250] Bug: Draft message is persisted across chats

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#11840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Open any chat
2) Type a message but do not send it
3) Switch to another chat

## Expected Result:
4) No draft message is shown in other chats (or a different draft message should show)

## Actual Result:
4) The draft message from step 2 is shown in every chat

## Workaround:
Yes, but this is still bad. Other draft messages are being overwritten

## Platform:

Where is this issue occurring?

- Web ✅ 
- iOS ❓ 
- Android ✅ 
- Desktop App ❓ 
- Mobile Web ✅ 

**Version Number:** `v1.2.15-2`
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Notes/Photos/Videos:** Added below:
**Reporter:** Tushu
**Slack:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665739959841639

https://user-images.githubusercontent.com/10736861/195832292-7bdf90f8-d66a-4a4c-8a00-69cba3a4740f.mov

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Okay so yeah. [This PR](https://github.com/Expensify/App/pull/11550/) seems to optimize rendering when switching between reports, but has introduced an issue where the draft is persisted, and then set for the new report.

**Comment by Julesssss** [comment]
Looking at the [library](https://github.com/software-mansion/react-freeze/), I'm not sure what the best solution is here. Commenting out [this line](https://github.com/Expensify/App/pull/11550/files#diff-7f24c59a03f8aced02f27c1a5916af530a7e2355b4afe765c9939c7bb20b28a9R134) solves the bug (as well as reverting), but I think we have time to await a true fix given that a Friday deploy is unlikely.

**Comment by marcaaron** [comment]
Leaving a fix for this up - but not feeling well today. If anyone wants to take over testing for it feel free otherwise I'll pick it up on Monday.

**Comment by yuwenmemon** [comment]
Sure thing! Feel better @marcaaron!

**Comment by Tushu17** [comment]
Reporting compensation is pending here. can you reopen this issue.
cc- @Julesssss

**Comment by Julesssss** [comment]
Hey @sakluger could you please create an UpWork job to pay @Tushu17 the bug raise bounty? Thanks

**Comment by thesahindia** [comment]
Hey @Julesssss, can you confirm if it is eligible for the C+ review compensation. I am not sure because I was late and you already had reviewed the PR before me.

**Comment by Julesssss** [comment]
Oh yes of course. Sorry, I didn't check the PR for C+ reviewers.

**Comment by sakluger** [comment]
Thanks for the bump @Julesssss. I am creating the UpWork job, but please bear with me as I am new to the process.

**Comment by sakluger** [comment]
@Tushu17 @thesahindia I sent you the offer in the Upwork job: https://www.upwork.com/jobs/~01d12df3246d798d2d

**Comment by thesahindia** [comment]
Accepted. Thanks!

**Comment by sakluger** [comment]
This isn't overdue.

**Comment by thesahindia** [comment]
@sakluger, we can close the contract and this issue.
