### ISSUE TITLE
Workspace - No growls in workspace option when the user is offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New expensify app
2. Sign into a valid account
3. Tap on Profile > Workspace - Reimburse expense
4. Turn ON airplane mode to simulate loss of connection
5. Tap on options ( view all receipts,) within the workspace while offline

## Expected Result:
User expects to receive a growl (toast message) stating that they are offline and no tab should be opened

## Actual Result:
The user receives no growls and a blank tab is open every time

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195902658-233f0d68-3779-43dd-a869-3a8e8dbaef24.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
This is expected behavior as a result of this PR: https://github.com/Expensify/App/pull/11614
