### ISSUE TITLE
 Bug: Composer isn't getting auto focused on switching chatsreported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Try switching chats

## Expected Result:
The composer should get auto focused

## Actual Result:
It isn't getting auto focused

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.15-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195909292-0152bf90-da22-4002-9ca9-b999b6025583.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665759644497429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/195909314-e1661d34-4033-45dd-8169-b2ddef909828.mp4

**Comment by thesahindia** [comment]
Will be fixed at https://github.com/Expensify/App/pull/11853

**Comment by kavimuru** [comment]
Will be fixed here  #11853, so closing this one as per this [comment ](https://expensify.slack.com/archives/C01GTK53T8Q/p1665769546497809?thread_ts=1665759644.497429&cid=C01GTK53T8Q)
