### ISSUE TITLE
Android - New Room - The name of the room is underlined when creating

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with Expensify account
3. Click on FAB button->New Room
4. Start typing a name for the room

## Expected Result:
The name of the room should not be underlined

## Actual Result:
The name of the room is underlined

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android
- Mobile Web - Android chrome

**Version Number:** v1.2.15-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195929540-13e94a3f-80ff-41bd-8dac-7075c888fd7c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Hmm I think this is the default behavior for inputs on Android because the text is also underlined in other fields. Also if you type a number first the text is not underlined.

**Comment by marcochavezf** [comment]
Yup, tested on other apps (like Airbnb, Whatsapp, and Gmail) and the behavior is the same. Closing it
