### ISSUE TITLE
Web - LHN - The red dot appears in the chat after opening it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Navigate to any chat
4. Leave a draft in the input
5. Navigate to another chats

## Expected Result:
1. The draft from the previous chat does not persist in the new chat
2. The red dot should not appear in any chat after opening it

## Actual Result:
The red dot appears in the chat after opening it

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** v1.2.15-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):**  applausetester+2409@applause.expensifail.com / Yulia1986Gerets and andreylazutkinutest+qqq@gmail.com /  w323052760Qwerty
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195937823-22a26abc-a130-4b15-8e5c-ad925d5bf309.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
@kavimuru Could you please open the chat with the red error indicator and see if it loads and displays any errors? Also opening the devtools (command+option+i) and clicking the Network tab before opening the report would be great.

The reportID is `7327969733890982`. If I supportal into [applausetester+2409@applause.expensifail.com](mailto:applausetester+2409@applause.expensifail.com) on staging and go to this URL, then it loads forever.
https://staging.expensify.com/report?param={%22pageReportID%22:%227327969733890982%22,%22keepCollection%22:true}

I see an error with the `Report_GetHistory` command, so I think this is probably a backend error related to the PHP 8.1 upgrade.
![image](https://user-images.githubusercontent.com/26260477/195943761-9057866b-0196-4942-8bd8-c2ea33fc342d.png)


If I supportal in on production I can view the report just fine.
![image](https://user-images.githubusercontent.com/26260477/195943669-200b6f71-320f-47bc-9e31-a7dfc5c52e9a.png)

I don't think this is a deploy blocker for App, but it is a problem that we need to fix on Web-E.

**Comment by neil-marcellini** [comment]
I'm seeing if someone else can pick this up in Slack.

**Comment by neil-marcellini** [comment]
We decided to close this [here](https://expensify.slack.com/archives/C07J32337/p1665782063552299?thread_ts=1665782015.562949&cid=C07J32337).

**Comment by kavimuru** [comment]
@neil-marcellini Sorry for the late reply.
I don't see any red dot in this account applausetester+2409@applause.expensifail.com 

https://user-images.githubusercontent.com/43996225/196051110-2e208cb1-fd57-4a16-999a-dd08be093a08.mp4

now.
