### ISSUE TITLE
mWeb- IOU -Focus dismissed in the window "What is it for?"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with your account
3. Click the FAB button again and select Request Money
4. Input any amount and click Next
5. Select any user account
6. Input any text in the field "What's it for?"
7. Click "Back" button <
8. Select any user account again
9. Verify that the cursor is in right

## Expected Result:
The cursor is in right place

## Actual Result:
Focus dismissed in the window "What is it for?"

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Safari

**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195987023-22176024-172b-4780-9299-298d43f3251c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Is this a regression? If so, when did we add the test that this failed? I'm not sure if this is the correct behavior or not so unsure whether it is valid. Going OOO for a week, but it doesn't seem urgent so I'll triage when I return.

**Comment by marcaaron** [comment]
I don't think this is a bug. Not everyone is going to add a "What's it For" comment to an IOU. Closing, but feel free to reopen if you disagree.
