### ISSUE TITLE
Web -Chat - Unable to split bill, error message is displayed.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11884]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login
2. Tap on FAB > Split bill
3. Select currency and enter amount
4. Select users
5. Tap on Next

## Expected Result:
Bill should be split.

## Actual Result:
Error displayed. Unable to split the bill.
App is crashed when trying split bill in chat conversation

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** v1.2.16-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195989021-0094704c-7ee7-4215-9bc3-706125118152.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="1440" alt="Bug5778177_Screen_Shot_2022-10-15_at_9 02 39_AM" src="https://user-images.githubusercontent.com/43996225/195989024-64614c14-c0c5-4a5c-a75f-794ab32848f4.png">
![Bug5778177_Image_10-15-22_at_9 22_AM](https://user-images.githubusercontent.com/43996225/195989027-0ea6efda-255e-4f10-acd4-525de441ff7f.jpg)

**Comment by youssef-lr** [comment]
Looking into this.

**Comment by sketchydroide** [comment]
The error says a string is being passed
```
{"jsonCode":0,"message":"abs(): Argument #1 ($num) must be of type int|float, string given","requestID":"75b96b523e7b9501-LIS"}
```

**Comment by sketchydroide** [comment]
Not a App blocker this is on the Web side

**Comment by iwiznia** [comment]
This should be fixed, can you retest @kavimuru

**Comment by iwiznia** [comment]
@kavimuru so did this work?

**Comment by kavimuru** [comment]
@iwiznia We have retested and it's fixed. Sorry for the late reply.

https://user-images.githubusercontent.com/43996225/197080512-b25524cd-ae07-4088-8411-7af43759f662.mp4
