### ISSUE TITLE
[$500] Web - Workspace - After selecting the "Start over" function, the system redirects incorrectly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Workspace->Connect bank account->Connect online with Plaid
4. Start the process of connecting the bank account-> interrupt it at the final stage (Personal Settings)
5. Go to Connect bank account->Start over

## Expected Result:
The system should be directed to Connect bank account page

## Actual Result:
After selecting the "Start over" function, the system redirects incorrectly

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1,2.16.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196001346-32a293b4-b362-4fe0-8331-ede17b07404f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Just to confirm, @kbecciv - are you thinking the App should redirect to this page?

<img width="375" alt="Screen Shot 2022-10-17 at 1 33 33 PM" src="https://user-images.githubusercontent.com/3885503/196166901-7513bda3-f1fe-4214-824c-de6425a419d2.png">

**Comment by Beamanator** [comment]
Also is there a TestRail step saying which page we should be redirected back to?

**Comment by kbecciv** [comment]
@Beamanator 
Yes, we have TR steps saying that _Verify you are redirected to the  Connect bank account screen displaying the options to connect via Plaid or connect manually_.
![image](https://user-images.githubusercontent.com/93399543/196213476-ac42692e-1ca2-4c78-94bb-fd50294c52f1.png)

**Comment by Beamanator** [comment]
Thanks for confirming, @kbecciv! It also looks like those steps in TestRail were the desired result when implementing the `RestartBankAccountSetup` here: https://github.com/Expensify/App/pull/9831

Making `External` since this most likely is a front-end redirect issue and can be worked by contribs

**Comment by sakluger** [comment]
I can't reproduce this one. @kbecciv Could you please clarify how far I need to go in the connect bank flow, and which bank you used to trigger the issue?

**Comment by Beamanator** [comment]
I was able to reproduce, it looks like to answer your question:
- Bank = Fidelity, Checking
- How far = Personal Information

**Comment by sakluger** [comment]
Ahhhh, I missed the video in the issue description. I can't verify this one myself because I don't have Fidelity, and I can't connect to Chase in Staging at the moment, but I'll take your word for it.

I've now created an Upwork job posting:

Internal Upwork post link: https://www.upwork.com/ab/applicants/1583143327161978880/job-details
External Upwork post link: https://www.upwork.com/jobs/~014b66e3d5dca7e737

**Comment by Beamanator** [comment]
Hmm I just used the username & password from https://stackoverflow.com/c/expensify/questions/342/525#525 (even though I think it mentions you should use Wells Fargo)

**Comment by sakluger** [comment]
It's been a week, time to update the price to $500.

**Comment by jayeshmangwani** [comment]
I think this issue has been solved now, I am not able to reproduce this on latest staging

**Comment by Beamanator** [comment]
Ooh that's very good to know, I'll test this as well thanks for the heads up @jayeshmangwani

**Comment by Beamanator** [comment]
Ok I agree this isn't reproducible anymore, time to close!
