### ISSUE TITLE
IOS -Security- The Close Account button cannot be clicked when the keyboard is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in with any account
3. Navigate to Settings > Security
4. Enter the email in the input and click/tap on "close account" with open keyboard
5. Click on Close account button

## Expected Result:
The close account button can be clicked when the keyboard is open

## Actual Result:
The Close Account button cannot be clicked when the keyboard is open

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.16.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196001613-36f517db-6f23-476d-a4bc-785f5be3f0e4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
<b>Proposal</b>
I think this normal action, we can fix this or not, that's fine. In this case, we can click the close button because we didn't set the `keyboardShouldPersistTaps` for the ScrollView in:
https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/pages/settings/Security/CloseAccountPage.js#L68-L74
<b>Solution</b>
Add `keyboardShouldPersistTaps="handled"` to our ScrollView will resolve the problem:
```diff
    <ScrollView
+                  keyboardShouldPersistTaps="handled"
                    contentContainerStyle={[
                        styles.flexGrow1,
                        styles.flexColumn,
                        styles.p5,
                    ]}
                >

```

**Comment by dangrous** [comment]
This is indeed happening, but as @hungvu193 noted I think this is normal and as of now desired, so I'm going to go ahead and close this for now. Not sure if this was the goal, but it's a flow that prevents any mistaken taps of the close button which I think is probably good.
