### ISSUE TITLE
Bug: On Change password page Save button show infinite spinner if user try to change password offlinereported by @Tushu17

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Website/App
2. Go to settings > Security > Change password page
3. Disconnect from internet
4. Fill both Current and New password input
5. Press Save button.

## Expected Result:
Button should be disabled.
## Actual Result:
Button isn't disabled.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:**y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196056889-3c95f59a-eefd-4e2a-b9a0-9739360d1bf3.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665937602385219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/196056891-17e60a84-8cb4-4e86-a432-d200b68b75ef.mp4

**Comment by gadhiyamanan** [comment]
**Proposal**

add `isDisabled={this.props.network.isOffline}` to below code

https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/pages/settings/PasswordPage.js#L218-L223

wrap component with `withNetwork()`

add prop `network: networkPropTypes.isRequired`
https://github.com/Expensify/App/blob/363d98fd3a3567c102c5359ba5257c67f95c60d0/src/pages/settings/PasswordPage.js#L23-L39

**Comment by alexpensify** [comment]
I'll review this one tomorrow.

**Comment by alexpensify** [comment]
Assigning to Engineering, I'm unable to replicate but let's see if someone else can. 

![image](https://user-images.githubusercontent.com/8107070/196569082-b46c6eb7-5022-4def-a0d1-dfc7d9ffb776.png)

**Comment by srikarparsi** [comment]
code's done, my vm isn't working after the upgrade so will test as soon as I get it working.

**Comment by srikarparsi** [comment]
hey @gadhiyamanan! In the future, it would be better to wait until the external label is applied before posting a solution. I implemented something similar to your proposal but kept it consistent with our other buttons: https://github.com/Expensify/App/blob/main/src/components/SettlementButton.js#L115

**Comment by Puneet-here** [comment]
I believe instead of disabling the button like this, we should do a form refactor since the form button already has this logic and we will be doing it in th future.
cc: @luacmartins

**Comment by luacmartins** [comment]
Yea, I agree that eventually we will refactor this to use the Form component.

**Comment by strepanier03** [comment]
Discussed internally [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1667504417832909). 

----

In light of the current and rapid development to replace passwords with magic sign-in links, we are not going to pursue fixing this bug. Should something change that makes fixing this a priority I will reopen it and action it accordingly.
