### ISSUE TITLE
[HOLD for payment 2022-11-18] [$500] Standardize form error styles

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#11908]
**Problem:**
Right now we have mutliple different ways of styling a form error.
![image](https://user-images.githubusercontent.com/2319350/196229958-b7735327-43e8-42ba-affa-d565e8fd6cf0.png)

**Solution:**
Let's standardize on how we style these form errors. Ideally this should follow the red brick road (dot indicator) style. 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2319350/196286581-1547327e-6148-4118-b0b9-5f3c217ac99d.png">

Details:
- Let's standardize on the dot indicator component we have as the main way to show an error
- Let's update this component to use all red text (except things like links) instead of gray text

**Comment by shawnborton** [comment]
After some [brief Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1666040517101589), let's move forward with making the error text all red as well. I have updated the original comment in this issue with the desired outcome.

**Comment by Puneet-here** [comment]
### Proposal
We can reuse `DotIndicatorMessage` here, we will also need to add a new prop `textStyle` we will use it for passing styles for text here
https://github.com/Expensify/App/blob/124ab4296f3d04ee276efbf0d74ff6eceb544898/src/components/DotIndicatorMessage.js#L61

And we just have to make changes in [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js)
```diff
 class BaseTextInput extends Component {
     constructor(props) {
@@ -198,7 +199,6 @@ class BaseTextInput extends Component {
         const inputProps = _.omit(this.props, _.keys(baseTextInputPropTypes.propTypes));
         const hasLabel = Boolean(this.props.label.length);
         const inputHelpText = this.props.errorText || this.props.hint;
-        const formHelpStyles = this.props.errorText ? styles.formError : styles.formHelp;
         const placeholder = (this.props.prefixCharacter || this.state.isFocused || !hasLabel || (hasLabel && this.props.forceActiveLabel)) ? this.props.placeholder : null;
         const textInputContainerStyles = _.reduce([
             styles.textInputContainer,
@@ -304,10 +304,13 @@ class BaseTextInput extends Component {
                             </View>
                         </TouchableWithoutFeedback>
                     </View>
-                    {!_.isEmpty(inputHelpText) && (
-                        <Text style={[formHelpStyles, styles.mt1, styles.ph3]}>
-                            {inputHelpText}
-                        </Text>
+                    {(!_.isEmpty(this.props.hint) && _.isEmpty(this.props.errorText)) && (
+                    <Text style={[styles.formHelp, styles.mt1, styles.ph3]}>
+                        {inputHelpText}
+                    </Text>
+                    )}
+                    {!_.isEmpty(this.props.errorText) && (
+                        <DotIndicatorMessage messages={{0: inputHelpText}} type="error" textStyle={[styles.formError, styles.mt1]} />
                     )}
                 </View>
```

We can also use a variable `shouldShowHint` to check if we can show the hint and we can use it like this 
```js
                    {shouldShowHint && (
                        <Text style={[formHelpStyles, styles.mt1, styles.ph3]}>
                            {inputHelpText}
                        </Text>
                    )}
```

For bottom error we need to pass `themeColors.textError` at https://github.com/Expensify/App/blob/124ab4296f3d04ee276efbf0d74ff6eceb544898/src/components/FormAlertWrapper.js#L63
https://github.com/Expensify/App/blob/124ab4296f3d04ee276efbf0d74ff6eceb544898/src/components/FormAlertWrapper.js#L67
https://github.com/Expensify/App/blob/124ab4296f3d04ee276efbf0d74ff6eceb544898/src/components/FormAlertWrapper.js#L76
and for icon we can use - <Icon src={Expensicons.Exclamation} fill={colors.red} />
```js
<Icon src={Expensicons.DotIndicator} fill={colors.red} height={variables.iconSizeSmall} width={variables.iconSizeSmall} />
```
https://github.com/Expensify/App/blob/124ab4296f3d04ee276efbf0d74ff6eceb544898/src/components/FormAlertWrapper.js#L59
FormAlertWrapper component will be refactored soon with the red dot in https://github.com/Expensify/App/issues/11410 so I think we should leave this part to get fixed there.

**Comment by dylanexpensify** [comment]
Reviewing now!

**Comment by parasharrajat** [comment]
@Puneet-here either customize the `DotIndicatorMessage` completely to fit here or create a new simple component for the same.

 
![image](https://user-images.githubusercontent.com/24370807/196486261-ee67491c-65bb-4eee-bd1a-63733b3517b0.png)

To me, this issue is exported first and completely focuses on the styling and mentioned the requirements so it should be done as part of it.

**Comment by dylanexpensify** [comment]
Upwork: https://www.upwork.com/jobs/~01f4b150900a44d8e0

**Comment by thienlnam** [comment]
Going to be OOO next week so I'm going to re-assign so this can keep moving along

**Comment by mountiny** [comment]
@parasharrajat @Puneet-here thanks, waiting for a full proposal

**Comment by dylanexpensify** [comment]
Not overdue!

**Comment by dylanexpensify** [comment]
Going to double

**Comment by mountiny** [comment]
Waiting for proposals

@Puneet-here interested in updating yours?

**Comment by Puneet-here** [comment]
I am working on some other issues right now and I will be busy this week because of festivals so I won't be able to look into it.

**Comment by mountiny** [comment]
No problem!

**Comment by parasharrajat** [comment]
Thanks for the proposal @0xmiroslav. It looks fine but I think it will create issues in FormAlertWrapper. `RenderHTML` contains View(block elements) View does not render well in Text. You may have to make it more dynamic. I think the best thing to do would be to use another prop called `text` and when passed using the current text rendering logic that you have in FormHelpMessage. And overwrite everything with children when passed. 

I think we can move forward with @0xmiroslav's proposal as this is a UI issue and it needs to go through a few iterations before we reach the desired UI. This can be done during the PR review. 

cc: @mountiny 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by mountiny** [comment]
Thank you very much @parasharrajat 

@0xmiroslav can you please raise your PR and accomodate it with recordings of all the paltforms so we can see how it looks?

**Comment by dylanexpensify** [comment]
@0xmiroslav any updates here

**Comment by dylanexpensify** [comment]
@0xmiroslav can you let us know when your PR will be ready for review?

**Comment by dylanexpensify** [comment]
Any updates here @parasharrajat

**Comment by mountiny** [comment]
This is now in staging @dylanexpensify 🎉

**Comment by mountiny** [comment]
It hasnt been that complex but I appreciate the PR grew in size. I think we can offer a $250 bonus for this work cc @dylanexpensify and @parasharrajat

**Comment by parasharrajat** [comment]
I think we missed one location in the app to check. I did during testing as well. 
the PasswordForm for protected PDF attachment. 
![Screenshot 2022-11-08 03:26:21](https://user-images.githubusercontent.com/24370807/200423838-fc9cae1b-66d8-474b-8411-d73a4b493f50.png)

There is a new issue which is related to this page but not the same issue https://github.com/Expensify/App/issues/12520. 

@mountiny Should we create a follow up and fix it or ask on the other issue to take care of this?

**Comment by parasharrajat** [comment]
I think let just do it here. @0xmiroslav Could you please raise a follow up PR to fix this as well?

**Comment by mountiny** [comment]
> I think let just do it here. @0xmiroslav Could you please raise a follow up PR to fix this as well?

I agree, that should be simple enough. No need to CP either.

**Comment by dylanexpensify** [comment]
Do we have an ETA when we could get the add-on PR raised?

**Comment by mountiny** [comment]
@dylanexpensify lets not forget to increase the bounty here for $750 given @0xmiroslav had to work on this one a bit more. Not sure how you keep track of these, maybe update a title

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
@parasharrajat @0xmiroslav please apply [here](https://www.upwork.com/jobs/~01f4b150900a44d8e0)! TY!

**Comment by dylanexpensify** [comment]
Offers sent! @parasharrajat @0xmiroslav

**Comment by mountiny** [comment]
@0xmiroslav @parasharrajat Has this been all paid up?

**Comment by NicMendonca** [comment]
@parasharrajat @0xmiroslav paid! (keeping this opened for the rest of the checklist)

**Comment by mountiny** [comment]
I think this was not a bug per se but more so a follow up to our Form refactor and aligning on the styles in other forms/inputs hence I am not linking any PR since this was not a regression. 

And therefore we dont have to add any new test into testrail either given this is not regression and there are tests covering forms and failure.s

**Comment by parasharrajat** [comment]
I think I was not paid the correct amount as per https://github.com/Expensify/App/issues/11908#issuecomment-1311494259. @NicMendonca

**Comment by dylanexpensify** [comment]
@parasharrajat sent over amount missing!
