### ISSUE TITLE
[Bug] App shows chats list from another user - reported by @0xmiroslav 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to user A
2. Verify that A's chats list is showing
3. Logout A
4. Login to user B
5. A's chats list is still showing
6. Logout B
7. Re-login B
8. Now B's chats list is showing correctly

## Expected Result:
App should always show logged in user's chat list

## Actual Result:
App shows previously logged out user's chat list

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.15-2
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/196141579-c24fd09d-d895-4e9b-bc39-e5a76ce8ca3f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661786986244689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I've not been able to reproduce this bug.

**Comment by abekkala** [comment]
I was still not able to reproduce this - taking the same steps outlined in the OP. 

@mvtglobally and @0xmiroslav can you clarify reproduction steps and/or to check the reproduction steps again.

**Comment by fedirjh** [comment]
@abekkala flow these steps , still able to reproduce

1. Login to this user : [applausetester+0901abb@applause.expensifail.com](mailto:applausetester+0901abb@applause.expensifail.com) / Feya86Katya 
2. Verify that A's chats list is showing 
3. Logout A and close tab after singing page shows
4. Open new tab and Login to user B (use new account with no chats)
5. A's chats list is showing in user B

**Comment by tgolen** [comment]
FYI, I tried this:

> HT(High Traffic) account is the key to reproduce. Please use this for A account: [applausetester+0901abb@applause.expensifail.com](mailto:applausetester+0901abb@applause.expensifail.com) / Feya86Katya

and it appears like the password is no longer accurate and I can't get logged in. I'd like to test this account out if I can have access to it please.
