### ISSUE TITLE
[HOLD for payment 2022-10-31] Software keyboard hides when you scroll the chat

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
1. Click on the compose input to open the keyboard
1. Scroll the chat

## Expected Result:
The keyboard should stay open.

## Actual Result:
The keyboard closes.

## Workaround:
None, this is a pain point for users and a critical regression.

## Platform:
Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.16-4
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** n/a
**Issue reported by:** (I don't know their GH name)
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665991322162069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
Previously, we added this so that the user is able to see the whole list instead of a few items. 

So the thought was that if a user is trying to scroll the list, the user probably wants to see the items below the keyboard. This kind of helped on small screens.

**Comment by roryabraham** [comment]
Working on this ... currently blocked by infra process [here](https://expensify.slack.com/archives/C094TGUTZ/p1666036297632469). Once that's done hopefully we can push this forward quickly

**Comment by roryabraham** [comment]
Currently blocked on https://github.com/Expensify/Expensify/issues/234445

**Comment by roryabraham** [comment]
WIP PR: https://github.com/Expensify/App/pull/11944

**Comment by roryabraham** [comment]
PR ready for review. I'm choosing not to CP it so that it gets to undergo a full regression suite.

**Comment by mountiny** [comment]
I will open this to pay @aimane-chnaif for reporting this in Slack first https://expensify.slack.com/archives/C01GTK53T8Q/p1665991623386559?thread_ts=1665991322.162069&cid=C01GTK53T8Q

**Comment by mountiny** [comment]
Assigning @dylanexpensify who kindly agreed to help out with paying out this bonus to @aimane-chnaif in weeks time

**Comment by dylanexpensify** [comment]
@aimane-chnaif [here's](https://www.upwork.com/jobs/~01759bf321620ed16c) the job post for you to apply!

**Comment by dylanexpensify** [comment]
Offer sent @aimane-chnaif !

**Comment by dylanexpensify** [comment]
Payment sent, contract ended, posting closed
