### ISSUE TITLE
[$500] BUG: Workspace room name input not grayed out when pending update fails

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#11914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. Create a workspace from the green plus (if needed)
3. Create a workspace room from the green plus (if needed)
4. Go offline
5. Click the header of the workspace room to open the room details page
6. Click "Settings"
7. Rename the room (`#examplerename`) and hit save
8. Verify that the input is grayed out (50% opacity)
9. Sign into the same account on another device or incognito window
10. Create another workspace room on the same workspace with the same name (`#examplerename`)
11. Go back to the other device and go back online
12. Verify that there is a red dot and an error message saying "A room with this name already exists".
13. Verify that there is a red dot on the LHN

## Expected Result:
The name input on the workspace room settings page is grayed out (50% opacity)

## Actual Result:
The name input on the workspace room settings page is not grayed out (50% opacity)

## Workaround:
Ignore it.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.15-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
![image](https://user-images.githubusercontent.com/26260477/196237293-0b7f745f-3f64-44e2-ad22-2717c392154c.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment]
I'm OOO for the next couple days driving home so I'm reassigning so this gets looked at properly.

**Comment by MitchExpensify** [comment]
@neil-marcellini when you say "Verify that the input is grayed out" in step 8, where are you referring to? I see the input is not grayed after sacing in this example if you are referring to the text field input:

Verify that the input is grayed out:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/36425901/196816784-c7205c42-db4d-43fd-ad7f-8dd19f0ec525.png">

**Comment by neil-marcellini** [comment]
I have updated the steps to clarify that both inputs should be grayed out (50% opacity). They will only be grayed out if you are offline and you have saved an updated workspace name. It should look like this, which I just tested on prod.
![image](https://user-images.githubusercontent.com/26260477/197013741-0ae81e3f-b15b-4131-a00d-01b21f882171.png)

**Comment by neil-marcellini** [comment]
I simplified the reproduction steps so hopefully they are more clear now.

**Comment by MitchExpensify** [comment]
I got to 12 and do not see a red dot or message:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/36425901/197594957-a855493f-dff0-4e3f-856a-8bd478f2867a.png">

**Comment by MitchExpensify** [comment]
Reproduced:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/36425901/197595655-d7e0dd17-85c1-4b43-8a1b-27bbaffdc5d8.png">

This is probably a good external candidate right @neil-marcellini ?

**Comment by neil-marcellini** [comment]
> This is probably a good external candidate right @neil-marcellini ?

Yep. I looked at the code a bit myself and I'm actually not sure why it isn't working right now. I don't think it will require any backend changes. The errors and pendingAction passed to OfflineWithFeedback are set correctly, but for some reason the opacity is not applied.
https://github.com/Expensify/App/blob/83676c1036299ffecbf82f4b829a7f8cbd741cd7/src/pages/ReportSettingsPage.js#L165-L169

**Comment by MitchExpensify** [comment]
not overdue.. waiting for proposals

**Comment by parasharrajat** [comment]
No proposals.

**Comment by MitchExpensify** [comment]
[Upwork Job](https://www.upwork.com/jobs/~012f8833a82489f411)

**Comment by Luke9389** [comment]
Still waiting on proposals.

**Comment by MitchExpensify** [comment]
Doubled! [Upwork Job](https://www.upwork.com/jobs/~012f8833a82489f411)

**Comment by JmillsExpensify** [comment]
We should consider taking this one internal, as it's blocking a test script from being added to TestRail. In the meantime, maybe doubling the price again will help encourage contributor proposals!

**Comment by Luke9389** [comment]
Once I'm done with my current bug, I'll come back if this one is still up for grabs.

**Comment by varshamb** [comment]
@neil-marcellini @Luke9389 @parasharrajat 
I am trying to reproduce the BUG. After doing Step 7, the input is grayed out (50% opacity) and this is expected result. Can you please help me to understand the bug.


https://user-images.githubusercontent.com/111683206/201394320-261e13ba-59d0-4e18-8484-10f73ceba7e9.mov

**Comment by parasharrajat** [comment]
I am also confuse a bit here. what does the workspace settings page has to do with Room renaming?

> The inputs on the workspace settings page are grayed out (50% opacity)
And when should this happen? after which step? 

cc: @neil-marcellini

**Comment by JmillsExpensify** [comment]
> The inputs on the workspace **room** settings page are grayed out (50% opacity)

We're missing the word **room** in the expected/actual result, but that's the meaning as it's also the language used in the reproduction steps.

**Comment by JmillsExpensify** [comment]
> And when should this happen? after which step?

The reason that this should happen is that the app is offline in this state, and this is a "pending action" which cannot be saved until the app comes back online. Here's another example for the workspace settings page, simply because I have that mock handy. Notice the second input? That's what we should be going for. 

![image](https://user-images.githubusercontent.com/1127863/201412244-3d09fdeb-361b-4675-8327-c5dbcdc84f73.png)

**Comment by parasharrajat** [comment]
Ok, so you are saying that input should be grayed out in below image. I got confused but the expected and actual result as well as https://github.com/Expensify/App/issues/11914#issuecomment-1285884724
![image](https://user-images.githubusercontent.com/24370807/201416485-0bacd205-069f-4c47-8faf-cdfde77bb96a.png)

**Comment by JmillsExpensify** [comment]
> Ok, so you are saying that input should be grayed out in below image

Yes, exactly. 

@neil-marcellini Are you saying that the notification preferences (first input) should be greyed out? I would have thought that's Pattern A (no failure case offline), but maybe there's a case you have in mind.

**Comment by neil-marcellini** [comment]
The name input on the workspace room settings page should be grayed out when there was an error updating it. I'll edit the issue description to make it more clear.

**Comment by MitchExpensify** [comment]
@Luke9389 Hows your bandwidth looking at the moment for this one to take it internally?

**Comment by parasharrajat** [comment]
@varshamb So the issue is asking that at step 13 as well as the red dot.

**Comment by varshamb** [comment]
### Proposal

We can make workspace room settings page grayed out by adding `hasErrors`, when there is an error.

const needsOpacity = (isOfflinePendingAction && !isUpdateOrDeleteError) || isAddError || hasErrors;

https://github.com/Expensify/App/blob/cfd0a081a9565f0d3bec6cc8d893028b181f48df/src/components/OfflineWithFeedback.js#L88

<img width="376" alt="Screenshot 2022-11-15 at 8 56 37 AM" src="https://user-images.githubusercontent.com/111683206/201820020-d55f1f5b-510d-4c72-887a-21dbb66914a0.png">

**Comment by parasharrajat** [comment]
We only want the opacity on Room name input.

**Comment by varshamb** [comment]
@parasharrajat 
We'll have to remove the Save button as a child of `OfflineWithFeedback` or we'll have to add conditional prop in `OfflineWithFeedback` which would make any child not to use the opacity when it has errors.

**Comment by parasharrajat** [comment]
I don't know why it's not overdue. Sorry, I thought that the whole page is grayed in your attachment. 

I am fine with graying the save button as well. 

Raised a discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1668718224575409

**Comment by parasharrajat** [comment]
Raised a discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1668718224575409

**Comment by neil-marcellini** [comment]
My bad, this is not an issue. Thanks to @parasharrajat for pointing that out. Inputs should only be grayed out while online if there was a creation error. This code is correct.
https://github.com/Expensify/App/blob/376c3327bdc58e0fb15ff31fa7ebba819a680206/src/components/OfflineWithFeedback.js#L88

**Comment by JmillsExpensify** [comment]
Thanks so much for raising this in Slack. That discussion worked exactly as intended.
