### ISSUE TITLE
BUG: Updating a room name on two devices causes an error

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#11913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. Create a workspace from the green plus (if needed)
3. Create a workspace room from the green plus (if needed)
4. Go offline
5. Click the header of the workspace room to open the room details page
6. Click "Settings"
7. Rename the room and hit save
8. Verify that the input is grayed out
9. Sign into the same account on another device or incognito window
10. Open the workspace room and click the header of the workspace room to open the room details page
11. Click "Settings"
12. Rename the room and hit save
13. Go back to the other device and go back online

## Expected Result:
The room name input is no longer grayed out signaling that the name was update successfully.

When updating the room name we throw an error [here](https://github.com/Expensify/Web-Expensify/blob/fd22abeb2b34b05fc5331d6dfe47b6c39bc1a640/lib/ReportAPI.php#L1814) if there's already a room with that name, but we should only throw an error if it is a **different** room that has the same name.

## Actual Result:
There is a red dot and an error message saying "A room with this name already exists".

## Workaround:
Dismiss and ignore the error

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.15-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
![image](https://user-images.githubusercontent.com/26260477/196235645-3c3b41fa-78e5-40c6-8bfe-56521241508b.png)
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
This was fixed [here](https://github.com/Expensify/Web-Expensify/pull/35303). Closing
