### ISSUE TITLE
Web - Chat - Last message in chat is open for edit upon pressing Up arrow button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11935]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login with any account
2. Open any chat with at least one message from current account ( or send it)
3. Click on new message field
4. Press Up Arrow button on the keyboard

## Expected Result:
I would expect that nothing happens and cursor stays on New Message field

## Actual Result:
Last message from current account in chat is open for edit.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5780948_screenshot_15](https://user-images.githubusercontent.com/43996225/196288780-53f9763b-581e-42b1-b18b-b40adf7843bc.jpg)

https://user-images.githubusercontent.com/43996225/196288784-c9b47918-18d7-4768-b5d3-374519fd9ded.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
This is not a bug, that's exactly how it should work. You press UP to edit your last message
