### ISSUE TITLE
[$250] BUG: When a new message arrives while drafting a message in the compose field, field gets cleared

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND and login as account A
2. Start composing a message to any user Account B
3. Send a message from the account B

## Expected Result:
User should continue typing the message in the compose field

## Actual Result:
Compose field gets cleared

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.16-4
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196316973-f79ec345-80f2-4eea-be97-05137a35e57a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @conorpendergrast 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665165533707169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Upwork job is [here](https://www.upwork.com/jobs/~01b9737568fafa446e)

**Comment by thienlnam** [comment]
Going OOO next week so re-assigning

**Comment by pecanoro** [comment]
Waiting for proposals!

**Comment by techievivek** [comment]
Can't seem to reproduce this, @Justicea83 can you give it one more try?

**Comment by Justicea83** [comment]
I can no longer reproduce this on my version of main, I vote we close this and see if it's reported again.

**Comment by bfitzexpensify** [comment]
Cool, agreed, closing.
