### ISSUE TITLE
[HOLD #11768] [$1000] Login - After creating a new account the user is not brought to Concierge conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. In the email field, enter a gmail email address for a new account
3. Press continue
4. Set a password that follows the password requirements
5. After setting the password, verify user is brought to Concierge conversation

## Expected Result:
After creating a new account the user is brought to Concierge conversation

## Actual Result:
After creating a new account the user is not brought to Concierge conversation

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2,17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196317411-f4fbc586-07eb-4057-8565-036c6d358e0b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment]
I was able to reproduce this on staging when when the width of the viewport is at most 800*915. This is an external fix

**Comment by dylanexpensify** [comment]
Upwork: https://www.upwork.com/jobs/~010696c2ee4726b141

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
@rushatgabhane what do you mean by RCA? 😂

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
doubled

**Comment by dylanexpensify** [comment]
not overdue, will put some more $$$ to it if no updates by Monday

**Comment by dylanexpensify** [comment]
doubling

**Comment by jayeshmangwani** [comment]
I have a doubt about this issue, 
we have created an [issue](https://github.com/Expensify/App/issues/10232) in the past that for a new user we should open the FAB menu,

so how can we handle this scenario in mobile view for a new user who should open the FAB menu and also navigate to Concierge conversation?

cc: @eVoloshchak @dylanexpensify

**Comment by Gonals** [comment]
I'd say we should prioritize navigating to the Concierge conversation over opening the Fab menu.

**Comment by jayeshmangwani** [comment]
# Proposal

as we have to navigate to Concierge for mobile devices as web is working fine, we have to make 2 changes here

1. we have to check if a mobile device 
we have to pass isSmallScreenWidth here, for checking mobile device in Welcome actions

https://github.com/Expensify/App/blob/952e5c39e4be989bd4aaea251ce5d3c4c64faa7a/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js#L62
  ```diff
-          Welcome.show({routes, showCreateMenu: this.showCreateMenu});
+          Welcome.show({routes, showCreateMenu: this.showCreateMenu,isSmallScreenWidth: this.props.isSmallScreenWidth });

  ```
2. then navigate to the Concierge chat

     1. in welcome page we have to import Report actions for accessing navigateToConciergeChat function
     ```diff
     +import * as Report from './Report';
     ```
     
     2. pass one more param in show function for accessing isSmallScreenWidth
     https://github.com/Expensify/App/blob/952e5c39e4be989bd4aaea251ce5d3c4c64faa7a/src/libs/actions/Welcome.js#L98
     ```diff
     -function show({routes, showCreateMenu}) {
     +function show({routes, showCreateMenu, isSmallScreenWidth}) {

     ```
     3. at last when we are showing create a menu, rather than need to check if isSmallScreenWidth then navigateToConciergeChat
     https://github.com/Expensify/App/blob/952e5c39e4be989bd4aaea251ce5d3c4c64faa7a/src/libs/actions/Welcome.js#L123-L125
     ```diff
     -            showCreateMenu();
     +            if(isSmallScreenWidth) {
     +               Report.navigateToConciergeChat(); 
     +            } else {
     +               showCreateMenu();
     +           } 
     
     ```
     
## Video After Fix


https://user-images.githubusercontent.com/35371050/200774718-1f2f0578-186d-4a1b-8dd0-bd7ce131630e.mov

**Comment by eVoloshchak** [comment]
@jayeshmangwani, thanks for the proposal!
It is based on @Ollyws's proposal with the exception of using Report.navigateToConciergeChat(), which in turn also just calls  `DrawerActions.closeDrawer()`, so the proposals are identical

**Comment by eVoloshchak** [comment]
> @jayeshmangwani, thanks for the proposal! It is based on @Ollyws's [proposal](https://github.com/Expensify/App/issues/11948#issuecomment-1307260394) with the exception of using Report.navigateToConciergeChat(), which in turn also calls `DrawerActions.closeDrawer()`, so the proposals are identical

**Comment by eVoloshchak** [comment]
I'm talking about this case

https://user-images.githubusercontent.com/9059945/200853314-5a1dd839-5e82-4979-b4ce-ba4deb58dee8.mov

> if we were to make the drawer close on every report route the user would be presented with a chat instead of the sidebar every time they open expensify web on small screens.

Seems like expected behavior, currently it just navigates to the main screen ignoring `reportID` in the URL

@Gonals, could you please take a look at this? I'm not entirely sure what is the expected behavior here

**Comment by Gonals** [comment]
Hmmm. It makes sense to me that, if we are providing a reportID, we should direct the user to the chat, even in small screens, rather than the main menu. 

@marcaaron, do you have an opinion on this?

**Comment by marcaaron** [comment]
We are discussing deprecating the drawer navigator so this should not be a problem in the future. I'd suggest we do nothing for now and close this issue or put it on hold and add it to the long list of bugs related to the drawer navigator.

**Comment by madmax330** [comment]
@marcaaron can we also add HOLD to the title ?

**Comment by dylanexpensify** [comment]
added to title, @madmax330 !

**Comment by dylanexpensify** [comment]
not overdue - moving to weekly

**Comment by tjferriss** [comment]
Reviewing the issue based on the [weekly bug update chore](https://stackoverflow.com/c/expensify/questions/8208):

@Gonals this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:
- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by Gonals** [comment]
@tjferriss, this is on HOLD :)

**Comment by JmillsExpensify** [comment]
Taking over this issue as part of the larger navigation project. Also linking to the main tracking issue.

**Comment by JmillsExpensify** [comment]
Still on hold for the larger react navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation revamp.

**Comment by JmillsExpensify** [comment]
Switched out weekly for monthly as the project is large and has no defined ETA.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation project.

**Comment by Gonals** [comment]
Getting there, but still on HOLD

**Comment by eVoloshchak** [comment]
Still on HOLD

**Comment by Gonals** [comment]
This is actually working as expected now. Closing
