### ISSUE TITLE
[$250] Android/IOS - Chat - After sent the message the composed box is not focused and cursor is not appear.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Select any user
4. Send message

## Expected Result:
After sent the message the composed box is focused and cursor is appeared

## Actual Result:
After sent the message - composed box is not focused and cursor is not appear.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196318036-0c249a5f-b9dd-4b8c-a4c5-aac86deaabcb.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
Can't run iOS current, but repro'd in Android v1.2.16-5. Marking External

**Comment by parasharrajat** [comment]
We can close this one then if duplicate.

**Comment by mountiny** [comment]
Closing this out as a duplicate, thank you for the message @aimane-chnaif I have commented in the relevant PR to hopefully speed it up https://github.com/Expensify/App/pull/11944
