### ISSUE TITLE
Web - Chat - Composed box is not sticked to the bottom when user is using collapse and expend options.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to any chat
4. Use Shift +Enter key a couple times to go to new line
5. Type any messages
6. Use Shift +Enter key a couple times to go to new line
7. Select Expand and Collapse option

## Expected Result:
Composed box should not move when user using collapse and expend options.

## Actual Result:
Composed box is not sticked to the bottom when user is using collapse and expend options.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.17.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![calape and expend](https://user-images.githubusercontent.com/93399543/196508418-82f4c079-df1f-47ae-9f2f-c308803e36f0.png)

https://user-images.githubusercontent.com/93399543/196508422-44c046e6-295f-4d81-b7d3-6bfe177fe74f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Thanks! Keeping it on HOLD then

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment]
PR was merged. Keeping issue open for a while to ensure it is not reproducible

**Comment by JmillsExpensify** [comment]
We should assign someone from Bug Zero to test this one now that #11437 is merged.

**Comment by MonilBhavsar** [comment]
Okay 👍 Reapplying Bug label

**Comment by JmillsExpensify** [comment]
Haha, that's quite ironic. I will test this weekend.

**Comment by JmillsExpensify** [comment]
![Screenshot 2022-11-06 at 14 02 37](https://user-images.githubusercontent.com/1127863/200192347-5a7f5e7a-5a08-4230-8dd6-796b5d72033b.png)

I wasn't able to reproduce this issue, so I'm closing.
