### ISSUE TITLE
[$250] BUG:  First name invisible on Android Chrome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. Click your avatar in the header, click Profile
3. Enter your first name

## Expected Result:
First name is visible

## Actual Result:
First name is invisible 

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.14-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
 
**(Issue occurs only in Emulator not able to reproduce in the physical device)**

https://user-images.githubusercontent.com/43996225/196497777-a53d7ec2-ec72-499b-aee5-e5f72d3550e1.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665767617996569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
I was able to reproduce it on the simulator. Applying the `External` label.

**Comment by marcochavezf** [comment]
Changing to `Weekly`. Waiting for proposals

**Comment by huzaifa-99** [comment]
Is this still reproducible in `v1.2.23-9`?

**Comment by muttmuure** [comment]
I just got access to Test Rail so I can try to reproduce this tomorrow

**Comment by muttmuure** [comment]
I don't have an android so I'm not sure how I can reproduce this. I'm asking Hax

**Comment by kavimuru** [comment]
@muttmuure I was not able to reproduce. So added `Need reproduction ` label. It was reported by @neil-marcellini. @neil-marcellini are you still able to reproduce?

**Comment by neil-marcellini** [comment]
I'm no longer able to reproduce this bug, which only occurred on the emulator, so I'll close this issue.

https://user-images.githubusercontent.com/26260477/201728225-e19f3437-96a6-4523-9c5f-aec3ab5213ea.mov
