### ISSUE TITLE
[HOLD for payment 2022-11-07] [$250] Bug: Android- Firefox the date picker label and placeholder overlaps reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11973]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open expensify in Firefox browser on android mobile
2. Go to settings > Workspace > Connect bank account
3. Choose any option and fill the data
4. Check the incorporation date picker at company information step

## Expected Result:
label and placeholder shouldn't overlap

## Actual Result:
It overlaps

## Workaround:
visual

## Platform:

Where is this issue occurring?

- Mobile Web - Firefox Android

**Version Number:** 1.2.17-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/196549499-3dd8fcd1-4077-4338-8379-95362879ffb9.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/196549547-fad02e7c-2ba7-4bbe-a951-993f5a492131.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665915696977869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
### Proposal
We need to set true for web.

https://github.com/Expensify/App/blob/ca501d965217c42ddc30f3516c1db7c10361c461/src/components/DatePicker/index.js#L71-L72

**Comment by techievivek** [comment]
This can be worked on externally and also @varshamb has already put in a proposal that needs a review.

**Comment by strepanier03** [comment]
Upwork job created: https://www.upwork.com/ab/applicants/1583182295728840704/suggested
External job post: https://www.upwork.com/ab/applicants/1583182295728840704/job-details

**Comment by strepanier03** [comment]
@rushatgabhane - based on your comment [here](https://github.com/Expensify/App/issues/11973#issuecomment-1285824062) are we accepting the proposal by @varshamb?

**Comment by strepanier03** [comment]
Sounds great! @varshamb - I've posted the Upwork job. If you apply for it, please post here with your Upwork profile so I can be sure I'm hiring the right person. Thank you!

**Comment by strepanier03** [comment]
@rushatgabhane That's odd, I have the option to make it private still and when I view the job details it's visible to everyone on upwork. 

<img width="1048" alt="2022-10-20_15-35-33" src="https://user-images.githubusercontent.com/10925636/197071843-4f79d575-23ef-4d8f-939f-b53b2d63615f.png">
<img width="820" alt="2022-10-20_15-35-18" src="https://user-images.githubusercontent.com/10925636/197071849-86f2bb16-20bc-4aa8-86a6-9953b2dd7a8e.png">

Can you attach a screenshot of what you see?

**Comment by marcochavezf** [comment]
> On android, Firefox shows `mm / dd / yyyy` but Chrome doesn't.
> 
> So I think it's fair to always activate the label.

That makes sense, let's do it.

> @marcochavezf I like @varshamb's [proposal](https://github.com/Expensify/App/issues/11973#issuecomment-1284269374). 🎀 👀 🎀 C+ reviewed

Thank you for the review @rushatgabhane! Assigning @varshamb 🚀

**Comment by strepanier03** [comment]
@rushatgabhane can you try this one? https://www.upwork.com/jobs/~01a8fdb4689abc1f23

That's the only other link I can find to send.

**Comment by strepanier03** [comment]
Great, thank you for testing and confirming. I'll share that link moving forward when making job, I appreciate your help. 

@rushatgabhane and @varshamb - let me know once you've applied to the job and if you can share a link to your Upwork profile I can be confident I'm hiring the right person.

**Comment by strepanier03** [comment]
@rushatgabhane I have hired you for this job. @varshamb - I'll keep an eye out for your application when it comes through.

**Comment by strepanier03** [comment]
@varshamb - Please apply for this [job](https://www.upwork.com/jobs/~01a8fdb4689abc1f23) as soon as you can so that when the pay hold is over I can pay the job. Thanks!

**Comment by strepanier03** [comment]
I was able to locate @varshamb in Upwork and hired them for this job.

**Comment by strepanier03** [comment]
@thesahindia - As the reporter please apply for the job [here](https://www.upwork.com/jobs/~01a8fdb4689abc1f23).

**Comment by thesahindia** [comment]
I already have applied to the job.

**Comment by strepanier03** [comment]
@thesahindia can you link me to your Upwork profile so I can be sure I'm hiring the right person? I see a few different applications and I just want to make sure. 

Thanks!

**Comment by thesahindia** [comment]
Sure, https://www.upwork.com/freelancers/~0107fb10c8087f6a5a

**Comment by strepanier03** [comment]
Thank you! I have hired you now and appreciate you working with me.

**Comment by strepanier03** [comment]
You can ignore that!

**Comment by strepanier03** [comment]
@rushatgabhane - Can you please complete the steps 2-4 of the BugZero checklist [here](https://github.com/Expensify/App/issues/11973#issuecomment-1294368133)?

I am on-pause for step 1 until I have Test Rail access and then I'll do step 1.

**Comment by strepanier03** [comment]
@rushatgabhane - Just a friendly bump on the BugZero checklist for locating the PR that introduced the bug. I'll check back in tomorro.w

**Comment by strepanier03** [comment]
@rushatgabhane - Thank you so much. I've added the links to the checklist and marked off those steps. I've also paid you for this job on Upwork.

@thesahindia - Thank you for working on this and for your proposal and prompt replies. I have paid you for this job on Upwork.

@varshamb - I have sent you a contract offer in Upwork. Please accept that and let me know here so I can pay you for this. Thank you!

**Comment by varshamb** [comment]
@strepanier03 Contract accepted in Upwork.

**Comment by strepanier03** [comment]
@varshamb - All done and paid as well. Thank you everyone for the hardwork!
