### ISSUE TITLE
Safari - "Paste as plain text" command is not in the context menu (right button click)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a chat app that supports Markdown (For example: Slack)
2. Copy the text with markdown and navigate back to NewDot
3. Paste this text without any markdown by right clicking and selecting "Paste as plain text"
Comment: For Safari only. Chrome and Desktop App have such a command.

## Expected Result:
Copied text can be pasted into the compose box using "Paste as plain text" from the context menu (right button click)

## Actual Result:
"Paste as plain text" command is not in the context menu (right button click)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196770913-6ac59248-ef33-461e-99a2-7cc5c1ada7ac.mp4

![Screen Shot 2022-10-19 at 11 02 57 AM](https://user-images.githubusercontent.com/93399543/196771240-c461008d-781f-40da-b6fa-fcdb682dc5af.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
@kbecciv Are you saying that "Paste as plain text" used to be an option but no longer appears?

**Comment by deetergp** [comment]
Bump @kbecciv

**Comment by mvtglobally** [comment]
Double checking..

**Comment by mvtglobally** [comment]
@deetergp 
See the difference. on Safari you can only PASTE. There is no other option 

<img width="412" alt="Screen Shot 2022-10-23 at 5 31 06 AM" src="https://user-images.githubusercontent.com/43995119/197384781-a4717148-a872-46e8-a4ae-cae9999000c3.png">
<img width="628" alt="Screen Shot 2022-10-23 at 5 30 59 AM" src="https://user-images.githubusercontent.com/43995119/197384785-a64c86df-89ee-4c50-8ad4-e3fd164d6e3e.png">

**Comment by deetergp** [comment]
@mvtglobally I guess what I am trying to figure out is, did we have this in Safari at one point but lost it because a bug was introduced, or did we never have it and are just noticing it now?

**Comment by deetergp** [comment]
I'm closing this as not valuable. Nobody can say that it was a thing that existed then went away, so it isn't really a bug.
