### ISSUE TITLE
#admins rooms tied to Collect or Control policies not showing in search or LHN for assigned Guides 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#11991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: ([How do I test 121 assigned guides on dev?](https://stackoverflow.com/c/expensify/questions/14339)) 
1. Non paying user creates a Collect or Control policy and is assigned a Guide (Guide gets added as a policy admin)
2. The #admins room tied to that policy shows in LHN for the Guide logged in New.expensify using their team.expensify.com account
3. The Guide uses the search feature in NewDot, typing the policy name, to find the #admins room of the Collect or Control policy 

## Expected Result:
1. The #admins room tied to the Collect or Control policy shows in LHN for the Guide logged in new.expensify using their team.expensify.com account
2. The #admins room tied to the Collect or Control policy is discoverable via search for the Guide logged in new.expensify using their team.expensify.com account

## Actual Result:
1. The #admins room tied to the Collect or Control policy does not show in LHN for the Guide logged in new.expensify using their team.expensify.com account
2. The #admins room tied to the Collect or Control policy is not discoverable via search for the Guide logged in new.expensify using their team.expensify.com account

## Workaround:
They can find assignments be logging into expensify.com and looking at their policies list. They can then follow up via email. 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** Yes 
**Email or phone of affected tester (no customers):**  

Guides:
alexandra.ivelisse@team.expensify.com
george.hayakawa@team.expensify.com
simone.avent@team.expensify.com
paige.smith@team.expensify.com
rebeccas.norris@team.expensify.com

Customers:
lisa.barker@aduroadvisors.com 
abdulhamid.janat@expensify.partnerhero.com
ac.sloafhouse@gmail.com
andreylazutkinutest+101016@gmail.com
andreylazutkinutest+190920@gmail.com
andreylazutkinutest+230970@gmail.com
krvmznpgq9@privaterelay.appleid.com
jaleman@rosebowlaquatics.org
jeff@runyonrental.com
so@hollywooddivineinc.com
yuriy.turbo+expenses.23.09@gmail.com
marlyn.mathew@zurabio.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/36425901/196747864-15a5631b-359c-4d5a-90c6-3f86676bc173.png)

![image](https://user-images.githubusercontent.com/36425901/196747897-f82418ce-338f-4ee3-b6e3-406b69ffccab.png)

**Issue reported by:** Mitch
**Slack conversation:** [Reports from Guides here](https://expensify.slack.com/archives/C036S0BVAHH/p1666065186104609) and [more reports from Guides here](https://expensify.slack.com/archives/C036S0BVAHH/p1666030082051379)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
cc @alex-mechler for thoughts on this as he is one of the closest to the code

**Comment by MitchExpensify** [comment]
Asked if this is a fire here - https://expensify.slack.com/archives/C03U7DCU4/p1666201675400019

**Comment by alex-mechler** [comment]
1:1'd Puneet, taking this over since I think i know what is happening here
