### ISSUE TITLE
BUG: Selecting a new chat from should provide grey background feedback reported by @chauchausoup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Go to new chat modal after pressing the green plus button.
Press any of the below mentioned chat profiles.

## Expected Result:
Grey background should have changed after pressing other profile.

## Actual Result:
Grey background doesn’t changes after pressing other profile.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2. 18-1

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196769249-dfc10780-890d-454d-8ac6-b1271a0689ff.MP4

https://user-images.githubusercontent.com/43996225/196769257-36986c90-937a-485e-862c-fd5952579f0b.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @chauchausoup

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664516111937949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment]
OOO for the next couple of days. Reassigning.

**Comment by JmillsExpensify** [comment]
Jumping in to test this one now.

**Comment by JmillsExpensify** [comment]
Closing this issue. I'm not clear what the bug is either reading the thread and the reproduction steps in this issue. Adding the `Needs reproduction` label.

**Comment by chauchausoup** [comment]
<img width="296" alt="Screen Shot 2022-10-25 at 10 20 04" src="https://user-images.githubusercontent.com/34975245/197683688-61c795a2-94ee-4c6f-a34a-b6c69483eea4.png">

@JmillsExpensify the as shown grey backgorund in the above image is not changing if one tap holds or even taps on the user profile in the **New Chat** section. Such feedback mechanism (design pattern) is validated in other sections of the mobile app like when you tap hold on items after opening the Green Plus button. 

The grey background region as shown above should be dynamic.
