### ISSUE TITLE
Android - Security - User needs to tap twice on "Close" button to close the account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11994]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to Setting - Security
4. Tap Close Account
5 Enter email address
6. Tap Close button

## Expected Result:
User should be able to tap only one time to close account

## Actual Result:
User needs to tap twice on "Close" button to close the account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.18.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196759184-765fc4cb-9728-4650-841e-aa22809c8bc0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
**Proposal**

add `keyboardShouldPersistTaps="handled"` prop to ScrollView https://github.com/Expensify/App/blob/ca501d965217c42ddc30f3516c1db7c10361c461/src/pages/settings/Security/CloseAccountPage.js#L74-L80

**Comment by thesahindia** [comment]
The refactor will be done at https://github.com/Expensify/App/issues/11341
