### ISSUE TITLE
[$250] BUG: [attachment] message still being shown even after attachment being deleted reported by @chauchausoup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to chat
2. upload an unsupported attachment
3. go back to LHN

## Expected Result:
you shouldn’t see [attachment] message in the LHN

## Actual Result:
you will find [attachment] message there in the LHN

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1,2,18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196776231-cdd13085-f93c-48f5-b0cf-df05b60ebeed.MP4

https://user-images.githubusercontent.com/43996225/196776259-5e247871-72a2-4658-93af-8b9e07064505.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664382344847229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment]
Was able to reproduce in both production and staging.

**Comment by Julesssss** [comment]
This is actually desired behavior as we want to direct users toward any errors that occur. The message and red dot ensures that users take action with these failures, or at least acknowledge them.
