### ISSUE TITLE
 Workspace editor - 'Save' button is not grayed out while offline after changing the name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot Desktop App
2. Turn the network off
3. Try to rename the WS and click on the save button

## Expected Result:
 The Save button and the text input is now grayed out

## Actual Result:
'Save' button is not grayed out

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196805417-9c135dee-57be-4ffc-b594-4254f9412c5c.mp4
![Screenshot 2022-10-19 at 20 42 11](https://user-images.githubusercontent.com/93399543/196805567-9131aa59-1631-4577-8510-f383cd58cf24.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
Nice catch. closing then
