### ISSUE TITLE
Web - App crashes when login 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Your account needs to have a default room
3. Enter email and password and click "Sign in "

## Expected Result:
User is able to login successfully

## Actual Result:
App crashes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Desktop

**Version Number:** 1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** kavi.utest+chatd@gmail.com, kavi.utest+chati@gmail.com, kavi.utest@gmail.com. Password: Test1234 kbecciv@gmail.com / Feya86Katya
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196965150-ef4e411f-4930-45d4-9fe2-bdf59006f753.mp4

https://user-images.githubusercontent.com/43996225/196963131-5046de5e-450c-472d-b4f2-d693a77f0b01.mp4
<img width="960" alt="new" src="https://user-images.githubusercontent.com/43996225/196963171-48e180d0-9a36-4b0b-ae7e-68c37cbb8f5b.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666250636656419
https://expensify.slack.com/archives/C01GTK53T8Q/p1666253733144749
https://expensify.slack.com/archives/C01GTK53T8Q/p1666271735578619
https://expensify.slack.com/archives/C01GTK53T8Q/p1666215056542569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I think it's this PR: https://github.com/Expensify/App/pull/12013/files

CC: @alex-mechler

**Comment by mountiny** [comment]
PR is up and in review.

**Comment by mallenexpensify** [comment]
Is this issue specific to Expensify Guides only? I had issues logging in yesterday, was getting blank page, but I haven't seen any other non-guides reporting that

**Comment by mountiny** [comment]
>Is this issue specific to Expensify Guides only? I had issues logging in yesterday, was getting blank page, but I haven't seen any other non-guides reporting that

This happens to anyone who had default rooms/admins rooms

**Comment by trjExpensify** [comment]
It's if you have default rooms. Fix has been CP'd to staging though now.

**Comment by mallenexpensify** [comment]
Thanks.  I wasn't able to reproduce on production for my mallen@expensify.com and [manager.allen@expensicorp.com](mailto:manager.allen@expensicorp.com) accounts.  I think mine issue was random af ¯\_(ツ)_/¯

**Comment by mallenexpensify** [comment]
hmmm...
signed out of my test account on chrome, [staging.new.expensify.com](http://staging.new.expensify.com/)
signed back into test account
:loading_circle_of_doom:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/22508304/197013670-a952318c-092e-4290-96df-3e3d91c11023.png">

refresh and hard refresh are working

**Comment by mallenexpensify** [comment]
Also, same is happening on firefox for staging.new.expensify.com

**Comment by mallenexpensify** [comment]
Reopening cuz if 
> Fix has been CP'd to staging though now.

It should be working, right?

**Comment by mallenexpensify** [comment]
And... both now loading after refresh :)
And... both now loading without needing to refresh :ohnothing:

**Comment by mallenexpensify** [comment]
NOPE!  hahahahaah
<img width="897" alt="image" src="https://user-images.githubusercontent.com/22508304/197016029-04c35792-fb7e-47cf-9ba2-0e56f0efdb15.png">

Errors in logs
<img width="460" alt="image" src="https://user-images.githubusercontent.com/22508304/197016117-f91a324f-0f4b-4147-baa0-a1d6568fab25.png">

<img width="577" alt="image" src="https://user-images.githubusercontent.com/22508304/197016125-f9ed77e1-ff88-4efd-8456-b4a5ca4991bd.png">

**Comment by mountiny** [comment]
@mallenexpensify Can you please do a new issue for this, it is a different error
