### ISSUE TITLE
[HOLD for payment 2022-11-16] [$250] Bug: [Staging] On add Paypal page, the add Paypal button isn't working correctly reported by @Tushu17 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Web/mWeb staging.new.expensify
2. Go to settings > Payments > Add Paypal page
3. Write invalid Paypal name and click add Paypal button.
4. Empty input field.

## Expected Result:
Button should be disabled if input field is empty

## Actual Result:
Button doesn't get disabled.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- [X] - Web
- [X] - iOS
- [ ] - Android
- [X] - Desktop App
- [X] - Mobile Web

**Version Number:** 1.2.18-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197045452-b3995f8b-ad8b-4dac-b4dd-057a48efd0f4.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666284006608739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/197045517-2ba701b8-08a6-49e0-9975-ab11f4d45858.mp4

**Comment by Tushu17** [comment]
### Proposal 
We just need to change:-
https://github.com/Expensify/App/blob/1bca7a4e6f0affb2a13e4697aa5803820cfeb863/src/pages/settings/Payments/AddPayPalMePage.js#L103

with 

``` isDisabled={this.state.payPalMeUsername === this.props.payPalMeData.description || !this.state.payPalMeUsername.length} ```

**Comment by Puneet-here** [comment]
### Proposal
The button will be enabled if user uses empty space so we need to check if a value exists by using `_.isEmpty(this.state.payPalMeUsername.trim())`
I believe we can also remove the current check since the user don't have any option to edit username unless they visit this page by url
https://github.com/Expensify/App/blob/07fc7d7fb6569b8705e50144a1e32fa3a941d1ba/src/pages/settings/Payments/AddPayPalMePage.js#L103
So we can use `_.isEmpty(this.state.payPalMeUsername.trim())` only or add it in the current logic like this 
```js
isDisabled={(this.state.payPalMeUsername === this.props.payPalMeData.description) || `_.isEmpty(this.state.payPalMeUsername.trim())`} 
```

**Comment by mallenexpensify** [comment]
@sophiepintoraetz  new BZ chore SO is [here](https://stackoverflow.com/c/expensify/questions/14418), we want to ensure BZ stays assigned to all issues so we can get to BugZero,

**Comment by sophiepintoraetz** [comment]
@kavimuru - please make sure you're filling out this section here in your issues
![image](https://user-images.githubusercontent.com/42940078/197663563-8825a131-3904-4625-9694-23fec6cb7629.png)

**Comment by sophiepintoraetz** [comment]
![2022-10-25_14-48-04 (1)](https://user-images.githubusercontent.com/42940078/197663606-0405aa96-8846-4c45-8cec-acf9df49ed0a.gif)

Also, I am able to replicate the issue on web and iOS so sending over to engineering.

**Comment by Santhosh-Sellavel** [comment]
@pecanoro 
@Puneet-here Proposal looks good!

C+ Reviewed
🎀 👀 🎀

**Comment by sophiepintoraetz** [comment]
[Job posted](https://www.upwork.com/jobs/~01af97f4666c7ddbf4)!

**Comment by pecanoro** [comment]
@Puneet-here Assigned!

**Comment by sophiepintoraetz** [comment]
Job posted [here ](https://www.upwork.com/jobs/~010284720003f4ea09)

**Comment by michaelhaxhiu** [comment]
Hey @sophiepintoraetz, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out. 

cc @Puneet-here and @Santhosh-Sellavel how far away do we think this is? I see updates to the PR as recent as yesterday and curious if this is coming close yet?

**Comment by Santhosh-Sellavel** [comment]
Requested changes yesterday. The Recent changes had been done 10 hours ago. Waiting for my review will get to it tomorrow!

**Comment by Santhosh-Sellavel** [comment]
@Puneet-here Please post a message once the requested changes are done, not sure if is this ready for review again.

**Comment by michaelhaxhiu** [comment]
Excellent! I'll leave it to @pecanoro from here to help move it forward.

**Comment by Puneet-here** [comment]
> @Puneet-here Please post a message once the requested changes are done, not sure if is this ready for review again.

It's ready.

**Comment by Santhosh-Sellavel** [comment]
Not overdue PR is waiting for review from @pecanoro

**Comment by sophiepintoraetz** [comment]
@Santhosh-Sellavel - would you mind answering the following please:
 - The PR that introduced the bug has been identified. Link to the PR:

**Comment by sophiepintoraetz** [comment]
@Tushu17 and @Santhosh-Sellavel - can you please apply for the [Job posted](https://www.upwork.com/jobs/~01af97f4666c7ddbf4)! Then we can close this one out!

**Comment by sophiepintoraetz** [comment]
Bump @Santhosh-Sellavel (offer is in your inbox, @Tushu17!)

**Comment by sophiepintoraetz** [comment]
All right - closing the issue coz payment is done! @Santhosh-Sellavel - feel free to reach out to me and/or respond to the offer in Upwork.

**Comment by sophiepintoraetz** [comment]
@Santhosh-Sellavel - apologies! I could have sworn I did but anyways, here we are
![image](https://user-images.githubusercontent.com/42940078/203431260-55f561bd-348b-4198-80e4-a9950e2ac13a.png)

**Comment by Santhosh-Sellavel** [comment]
@sophiepintoraetz You could hire me straight away as you have an option to do so.

I get it you might have invited me earlier too. Only when you hire me I will receive an offer, which will show up on messages.

**Comment by Santhosh-Sellavel** [comment]
Applied for the job now!
