### ISSUE TITLE
Bug: Accessibility labels aren’t localized reported by @rushatgabhane 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to login page
2. Change language to spanish.
3. Use [VoiceOver](https://support.apple.com/guide/voiceover/turn-voiceover-on-or-off-vo2682/mac) on web
4. In login page, change focus to “Número de teléfono o email” input using Tab key.

## Expected Result:
VoiceOver calls out “Login form” in Spanish

## Actual Result:
VoiceOver calls out “Login form” in English
Also happening in SidebarLinks, ReportActionsList, ReportActionItemCreated, ReportActionItem, OptionRowLHN, UnreadActionIndicator

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197048052-8fcb2bd3-5ff0-4003-bf10-9570f07d94dc.mov

https://user-images.githubusercontent.com/43996225/197048127-cecf4d67-334d-4a1e-9c08-778111199cde.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666217749050159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
### Proposal 

In LoginPage, ReportActionItem, OptionRowLHN, UnreadActionIndicator etc.
Use `props.translate()`

https://github.com/Expensify/App/blob/261c712e1b8118de955bd31e6cf5b070dd285b3d/src/pages/signin/LoginForm.js#L158

**Comment by mallenexpensify** [comment]
@zanyrenney  new BZ chore SO is [here](https://stackoverflow.com/c/expensify/questions/14418), we want to ensure BZ stays assigned to all issues so we can get to BugZero,

**Comment by zanyrenney** [comment]
I'm OOO, reassigning.

**Comment by zanyrenney** [comment]
didn't assign anyone, will keep and do when i'm back.

**Comment by mallenexpensify** [comment]
@rushatgabhane Gonna close this now, I added it to the [Accessibility Audit milestone](https://github.com/Expensify/App/milestone/4) so we can address and reopen if/when needed.
