### ISSUE TITLE
Settled IOUs are not being cleared for the receiving user

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#12052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Send another user an IOU
- The other user settles the IOU
- I see the 'user2 paid you' component message

## Expected Result:
- The IOUBadge should also be cleared

## Actual Result:
- The IOUBadge was **NOT** be cleared

## Workaround:
User can sign out and back in again

## Platform:

Where is this issue occurring?

- Web ✅ 
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.18-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** No, but this is because of [THIS bug](https://github.com/Expensify/Expensify/issues/229735)
**Email or phone of affected tester (no customers):** all
**Notes/Photos/Videos:** Any additional supporting documentation

**UI**
<img width="975" alt="Screenshot 2022-10-21 at 10 37 52" src="https://user-images.githubusercontent.com/10736861/197165778-e6268f78-329a-4d6b-9316-2bc86e40ee5a.png">

**Onyx**
- chatReport should NOT have a total
- both reports should not have an outstanding iou
<img width="812" alt="Screenshot 2022-10-21 at 10 41 41" src="https://user-images.githubusercontent.com/10736861/197165995-4be9f01d-6a66-458d-8f5b-bb461beeaa0c.png">
<img width="414" alt="Screenshot 2022-10-21 at 10 42 03" src="https://user-images.githubusercontent.com/10736861/197165997-08c24f55-88db-4cb0-a7d8-3ff6193badb0.png">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I just tested this out and I wasn't able to reproduce it.

<img width="1137" alt="Screen Shot 2022-10-21 at 3 09 02 PM" src="https://user-images.githubusercontent.com/8292562/197295887-cbfa15f6-af32-4141-a627-a262fc527229.png">
