### ISSUE TITLE
BUG:  All contacts disappear from LHN on adding a user to workspace reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings
2. Open a workspace > Manage members
3. Click on Invite > Select a contact and invite
4. Check the LHN

## Expected Result:
The contacts shouldn't disappear

## Actual Result:
The contacts disappear

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-5
**Reproducible in staging?:** y
**Reproducible in production?:** No (This is inconsistent tester was able to reproduce in Production when logged this issue #12020)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

Contributor was able to reproduce in Web, but not our team. It seems inconsistent. Please double check if its not repro in production

https://user-images.githubusercontent.com/43996225/197291752-265bce31-629d-4a56-9918-77f162a91436.mov

https://user-images.githubusercontent.com/43996225/197292415-a796730d-2032-47cb-8a9b-67b5d28be7af.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666380873125949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
I was not able to reproduce it on staging or production. Can you retest @kavimuru or @thesahindia? I feel like if we cannot consistently reproduce it should not be a deploy blocker and should instead just be an issue to investigate.

**Comment by chiragsalian** [comment]
Also looks like luke is OOO so i'll take over this issue from him.

**Comment by chiragsalian** [comment]
Odd, i am able to get it consistently on your account. On your account, i get the issue only on staging and not on production. Very weird.

**Comment by kavimuru** [comment]
@chiragsalian Our team can reproduce only in Android not in Web, mWeb and iOS

https://user-images.githubusercontent.com/43996225/197605499-4e74e970-ed73-40d6-ab41-d0d25051d83a.mp4

**Comment by chiragsalian** [comment]
Shall retest once the code hits staging.

**Comment by mallenexpensify** [comment]
@thesahindia please accept the job offer here for $250 payment for reporting https://www.upwork.com/jobs/~014351831b357edb55

Comment on this issue once you have and I'll pay

**Comment by chiragsalian** [comment]
Retested and it LGTM, i'm moving forward with deploy. Keeping this issue open for payment.

**Comment by thesahindia** [comment]
> Comment on this issue once you have and I'll pay

Accepted. Thanks!

**Comment by mallenexpensify** [comment]
Paid @thesahindia , thanks!
