### ISSUE TITLE
Bug: Message only partially being read as a link reported by @begadtarek

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  Send a message of more than two words, with periods between them (no spaces)
  (Examples: "Fairmont.data.rooms", "[This.com](http://this.com/).mumbo.jumbo", "Decent.data.something")

## Expected Result:
All message would be registered as hyperlinked

## Actual Result:
Only part of the message would be registered as a link and hyperlinked

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/197562908-8c950194-268f-4517-b519-110fc57bfbb4.jpeg" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/197562940-b5b4b49b-62a3-4412-a77f-0eb7c82f770c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @BegadTarek
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666602954056209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment]
> Reviewing this, it appears that we're just looking for common urls/Domains, which is why not all of the entries are being linked.

This is right. .data, .eg, .uk, and .me are all valid top level domains, so those are valid URLs even if they lead to nowhere, just like `thereisnowebsiteonthisdomain.com` would
