### ISSUE TITLE
[$250] Vertical keyboard padding is shown beneath input when opening chat

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#12114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

- Navigate to Settings > Profile
- Tap the 'First name' input field
- Without manually closing the keyboard, close the modal with the 'x' button
- Navigate to any chat

## Expected Result:
- There should not be padding beneath the input

## Actual Result:
- There is keyboard-sized vertical padding beneath the input

## Platform:

Where is this issue occurring?

- iOS: iPhone 7, iOS 13.3 

<img width="375" alt="Screenshot 2022-10-25 at 11 35 16" src="https://user-images.githubusercontent.com/10736861/197753801-52e37860-6fcf-4299-8121-d61d0d311b36.png">

**Version Number:** `v1.2.18-8`
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
@flaviadefaria please hold on making this external for now. It seems related to a keyboard refactor that @tgolen is working on, so I'd like to first get his opinion.

**Comment by tgolen** [comment]
I've added a HOLD to this and added it to the master tracking GH for now. I'll have to take a look at this on my branch and see if it's fixed yet or not.

**Comment by flaviadefaria** [comment]
@Julesssss should I delete the Upwork post then?

**Comment by Julesssss** [comment]
Thanks, @tgolen. 

@flaviadefaria I'm not sure how UpWork posts work in practice, but I assume it's fine to keep it up for now until it has been confirmed.

**Comment by tgolen** [comment]
OK, I just tried it out with my branch and it is still broken there. Let's keep this issue on HOLD until my PR is merged though (so we can get proposals based on the right code). If we can't pause the Upwork job, then maybe it is best to delete it for now.

**Comment by flaviadefaria** [comment]
Oh we're actually good, I confused the GH issues 😅  I had another one with Jules for which I posted the job in Upwork this morning, but I had not posted one for this issue. I'll switch this one to weekly then until it's removed from hold.

**Comment by tgolen** [comment]
This is no longer on hold and can have proposals created for it with the new code.

**Comment by Julesssss** [comment]
Awaiting proposals

**Comment by parasharrajat** [comment]
Do we have to worry about iOS 13.3?

**Comment by JmillsExpensify** [comment]
@flaviadefaria Given that we're still early and no proposals have been accepted, I'm assigning myself per the new BZ process: https://stackoverflow.com/c/expensify/questions/14597/14598#14598.

**Comment by JmillsExpensify** [comment]
> Do we have to worry about iOS 13.3?

That's a great question. I don't think we do or should, as that is quite a ways back in supporting older OS that aren't seeing active development. @Julesssss do we have a list of iOS versions that we officially support? I wouldn't expect this one to be on it, that's 4 years old, right?

**Comment by parasharrajat** [comment]
I recently faced this issue on iOS 15. This is a very serious issue. Let's prioritize this.

**Comment by Julesssss** [comment]
> do we have a list of iOS versions that we officially support? I wouldn't expect this one to be on it, that's 4 years old, right?

I don't believe we have. Our Android support goes far back also and while we should restrict this eventually it's a separate discussion than needs context on the version market share. Having said that, I don't think we should be blocking devices that are still receiving OS security updates from Apple/Google.

> I recently faced this issue on iOS 15. This is a very serious issue. Let's prioritize this.

Anyway, seems like this is occurring on newer devices too 👍

**Comment by JmillsExpensify** [comment]
Ok moving on now, I'm not able to reproduce on iOS 16, which is fine, but I kind of wonder if this issue is a dupe of https://github.com/Expensify/App/issues/11858?

**Comment by Julesssss** [comment]
@JmillsExpensify ah nice spot. That does seem very similar.

**Comment by Julesssss** [comment]
Closing as a dupe of https://github.com/Expensify/App/issues/11858. I added the screenshot and additional reproduction steps and info to the other issue.

**Comment by Julesssss** [comment]
@JmillsExpensify or @flaviadefaria would you mind closing the UpWork job? Thanks

**Comment by JmillsExpensify** [comment]
Cool, cool. Yep all good. Closed it out.
