### ISSUE TITLE
[$1000] [Performance] Pressing the FAB on the start screen doesn't open the menu immediately

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#12119]
## What performance issue do we need to solve?

When pressing the FAB on the start screen there is a noticeable delay until the menu opens. It gets more noticeable the weaker the device is.

See this video:

https://user-images.githubusercontent.com/16821682/196205400-e5a4746a-f32c-477b-b166-d5a1b44dad8f.mp4

## What is the impact of this on end-users?

Frustration. The action that follows an interaction shouldn't take any longer than 100 to max 200ms. Otherwise, the user will notice the wait time and gets a poor sense of quality.

## List any benchmarks that show the severity of the issue

- Time from interaction to action: ~2 seconds (From the video above)
- Worst UI Thread FPS: 55.7
- Worst JS Thread FPS: 0
- Time the JS thread froze: ~ 1 seconds 

## Proposed solution (if any)

In general, we want to avoid doing unnecessary work like rerendering components that don't have to.

- https://github.com/Expensify/App/pull/11907

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

https://user-images.githubusercontent.com/16821682/196205539-cd3c876e-09f3-4753-9829-391bc95585dd.mp4

The feedback comes immediately after pressing the FAB. And as there is no frozen JS thread we also can see the animation of the FAB.

- Time from interaction to action: 0 s (there is probably some, but it's not "eye measurable")
- Worst UI Thread FPS: 56.2
- Worst JS Thread FPS: 46.5
- Time the JS thread froze: 0 ms

<img width="1277" alt="Screenshot 2022-10-28 at 15 58 36" src="https://user-images.githubusercontent.com/16821682/198628444-19de7630-6038-47d7-acc8-2719dbb2b944.png">

<img width="1250" alt="Screenshot 2022-10-28 at 15 58 43" src="https://user-images.githubusercontent.com/16821682/198628513-9759c72f-bd9c-443d-8ad7-535f37890334.png">

(You can see that the JS thread is very less busy, which is a good improvement!)

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:** 1.2.19-1
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01a90182453cb9e09e
- Upwork Job ID: 1599653517257056256

**Comment by hannojg** [comment]
PR is ready for review

**Comment by mountiny** [comment]
This one might be on topic

**Comment by hannojg** [comment]
As https://github.com/Expensify/App/pull/12369 its merged this issue can be closed (or it can be tested and verified that the issue got fixed, not sure what's the procedure is here)

**Comment by mountiny** [comment]
This will be automatically updated once the PR hits production.

**Comment by Santhosh-Sellavel** [comment]
@mountiny Can you assign me this one to track payment for PR review, thanks!

**Comment by mountiny** [comment]
This has hit production one week ago so we can pay @Santhosh-Sellavel for reviewing internal PR, this was  bit more involved. What do you suggest is a fair compensation?

cc @alexpensify

**Comment by alexpensify** [comment]
@mountiny - I've been OOO since November 19. Do you need me to start a convo about payment or start a job here? Thanks!

**Comment by mountiny** [comment]
@alexpensify I think we dont need and internal convo for the compensation, we can just ask @Santhosh-Sellavel what they think was reasonable compensation for the testing of that PR.

as far as I recall this PR has been quite involved with testing from Santosh side, what do you suggest @Santhosh-Sellavel ?

**Comment by Santhosh-Sellavel** [comment]
@mountiny 
Considering the effort on this PR which is quite a lot, I am requesting consider a minimum of $2K and I think it's fair for the work done. If you feel otherwise, I am happy to take the Flat $1000 price which is the new price! And feel free to add bonuses 😀 , thanks!

**Comment by mountiny** [comment]
I agree with the $2000, this has been an External PR which went a bit outside of the classic track, but due to the importance of this issue I thin $2000 would be appropriate at least for this issue so as C+ reviewer this makes sense to me

@alexpensify Would you be able to create a job for this? Thank you!

**Comment by alexpensify** [comment]
Ok, I'll deal with this one tomorrow!

**Comment by alexpensify** [comment]
I've started the process to pay via Upwork, please accept. Thanks!

**Comment by mountiny** [comment]
Removed, thanks

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - Payment has been sent via Upwork
