### ISSUE TITLE
Remove Reanimated patch

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This issue is just a reminder to remove the Reanimated patch we've got in this repo whenever:

- [This PR](https://github.com/software-mansion/react-native-reanimated/pull/3717) is merged, OR
- We enable Fabric, making the change in the patch no longer needed

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665437638531509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
PR was merged but not yet released

**Comment by roryabraham** [comment]
The PR was released in https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.0-rc.4, so we can do this at any time

**Comment by roryabraham** [comment]
PR up and ready for review: https://github.com/Expensify/App/pull/12921

**Comment by dhairyasenjaliya** [comment]
hm also here  https://github.com/Expensify/App/issues/12152 we are updating Reanimated + Remove patch to fix the error `Console error: Warning: RCTBridge required dispatch_sync to load REAModule. This may lead to deadlocks`
PR awaiting review: https://github.com/Expensify/App/pull/12817
@roryabraham

**Comment by roryabraham** [comment]
This was done in https://github.com/Expensify/App/pull/12817, just awaiting production deploy

**Comment by roryabraham** [comment]
Deployed to production, closing this out.
