### ISSUE TITLE
Android - VBA - Let's finish in chat screen is displayed on finish of Pending account flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Manual method to add a bank account
6. Use the "Pending State Withdrawal Account" credentials
7. When Onfido triggered complete all the steps

## Expected Result:
Verify that when you finish the flow - the modal asks for 3 amounts of test transactions

## Actual Result:
"Let's finish in chat!" screen is displayed when finishing the 'Pending state withdrawal accoun' flow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** Can't check
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198099671-692123e4-2a96-4da3-b825-d8689dd5798c.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment]
I don't understand this issue and the screenshot doesn't match the description of the problem. Can I get some clarification as to what is happening and why that's incorrect?

**Comment by kavimuru** [comment]
@tylerkaraszewski Sorry about the wrong attachment. Uploaded the correct video

**Comment by kbecciv** [comment]
Issue is reproduced with build 1.2.26.0

https://user-images.githubusercontent.com/93399543/201097896-927cfdb2-533c-4c20-a840-9130233ae8fb.mp4

**Comment by tylerkaraszewski** [comment]
Lol, immediately overdue. Not looked at yet.

**Comment by tylerkaraszewski** [comment]
Still haven't looked.

**Comment by JmillsExpensify** [comment]
Closing per the related Slack convo. This isn't a bug.
