### ISSUE TITLE
[$250] Android - Workspace - App is crashed when creating a new Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12171]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to Setting - Workspace
4. Select ... dots
5. Tap on New Workspace

## Expected Result:
New Workspace is created

## Actual Result:
App is crashed when creating a new Workspace

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.20.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198172853-a7398af7-aac3-42a8-911d-d5ff6acb6f65.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Not reproducing in v1.2.19-1, will try 1.2.20.0

**Comment by Beamanator** [comment]
Installed 1.2.20.0, clicked on Settings, app crashed 😅

**Comment by Julesssss** [comment]
[See here ](https://github.com/Expensify/App/issues/12173#issuecomment-1293276920)for the likely cause. I believe all these Android regressions are caused by the same issue.

**Comment by Beamanator** [comment]
@Julesssss looks like you're looking into this so I'll stop 😅 let me know if you need help testing or anything 👍

**Comment by Julesssss** [comment]
Fixed: https://github.com/Expensify/App/pull/12176

**Comment by Julesssss** [comment]
I'm going to ask Applause to retest this one, once the Android fix is CP'd to the deploy checklist

**Comment by Julesssss** [comment]
This was first reported by @aimane-chnaif [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666823962016809). Adding someone to help open the UpWork job and pay the reporting bonus.

**Comment by Julesssss** [comment]
Hey @maddylewis 👋 

This issue was already fixed, but could you please create an UpWork job to pay out the reporting bonus for @aimane-chnaif. Thanks!

**Comment by maddylewis** [comment]
Hey @Julesssss - on it!

**Comment by maddylewis** [comment]
okay, here is the job posting - https://www.upwork.com/jobs/~01cc9c85b0ce6b42d2

**Comment by maddylewis** [comment]
and then, i think im rehiring Aimane C to the job? 
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/38016013/198670117-c65d2413-45d9-457d-bb6c-aa1c7a31635c.png">

and then paying them from there?

**Comment by maddylewis** [comment]
ok i paid $250 to Aimane Chnaif via Upwork.

**Comment by maddylewis** [comment]
welcome!
