### ISSUE TITLE
Upgrade RN fork to latest

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12177]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
A [recent commit](https://github.com/Expensify/react-native/commit/9ac437f25b51b9a7fc8134d17c69b64ae90d508d) in the react-native upstream introduced Fabric support for modals. We don't have that code in our fork yet.

### Solution
Two parts:

1. Upgrade and republish our fork (I will do this)
1. Then upgrade E/App to the new version of the fork (most likely this will shadow `0.70.4`, released two days ago) (I will likely make this part external)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Ran into a snag where [this commit](https://github.com/Expensify/react-native/commit/9ac437f25b51b9a7fc8134d17c69b64ae90d508d) has not been included in any upstream release yet

**Comment by roryabraham** [comment]
Going to just manually perform that commit in the `Expensify-0.70.4-alpha` branch, so that we can get it included in the release without me trying to build off a non-stable release

**Comment by roryabraham** [comment]
Upgrade helper diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.1&to=0.70.4

**Comment by AndrewGable** [comment]
PR In review
