### ISSUE TITLE
Connect Bank Account - App is crashed when adding a Verified Bank Account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal (Workspace settings > Add bank account)
4. Verify the Add bank account modal is displayed with 2 options to add bank accounts (Log in and Manual)
5. Select the Connect with plaid method to add a bank account
6. On the bank account list select "Fidelity"
7. Enter the credentials "user_good / pass_good"
11. Select "Plaid Saving" account
12. Click Save and Continue
13. In the company information verify all fields are working as expected
14. Fill out the fields with the required test credentials
15. Verify you're able to continue to the personal information step.
16. In the Personal information verify all fields are working as expected
17. Fill out the fields with the required test credentials
18. Verify you're able to continue.
19. In the beneficial owners step toggle the last 2 checkboxes (terms and conditions and true information)
20. Confirm you're able to continue and reach the validate step.
21. Verify the bank account was added to the workspace

## Expected Result:
App is not crashed when adding Verified Bank Account

## Actual Result:
App is crashed when adding a Verified Bank Account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.20.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198173153-51b0e71a-c12f-4f88-9fb7-b45089facde2.mp4

https://user-images.githubusercontent.com/93399543/198173218-043f8abb-a294-4f9a-bfeb-dfbc315496ed.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
I tried to reproduce it but it is not crashing for me, it works just fine, can someone else test it as well?

**Comment by NikkiWines** [comment]
Also unable to reproduce on staging as well

**Comment by Julesssss** [comment]
It's possibly linked to [these](https://github.com/Expensify/App/issues/12173) [two](https://github.com/Expensify/App/issues/12171) crashes, reported at the same time. We're about to CP a fix and then will retest this one to see if it's still occurring.

**Comment by Julesssss** [comment]
I'm going to ask Applause to retest this one, once the Android fix is CP'd to the deploy checklist

**Comment by Julesssss** [comment]
Asked Applause to retest [here](https://github.com/Expensify/App/issues/12165#issuecomment-1293512140)

**Comment by Julesssss** [comment]
Excellent, thank you!

**Comment by kbecciv** [comment]
Issue have been reproduced with build 1.2.21.4 with two testers.

https://user-images.githubusercontent.com/93399543/199027164-12dafbfb-e578-4135-85f0-d81e1597c023.mp4

**Comment by Julesssss** [comment]
Hi, thanks for the report but the issue is different. Could you please open a new issue?

The stack trace is: 

```
Account not found in EnableStep in u.value (EnableStep.js:77:19)
```

**Comment by Julesssss** [comment]
Hey @kbecciv, is this only reproducible on the latest version?

**Comment by kbecciv** [comment]
Here is the link for new GH issue https://github.com/Expensify/App/issues/12308
