### ISSUE TITLE
Android - LHN - App is crashed when tap on Send/Request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on Fub menu
4. Tap Send/Request money

## Expected Result:
User can procced with request/send money flow

## Actual Result:
App is crashed when tap on Send/Request money

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.20.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198173613-8daa8615-9bc5-45cf-a8ab-67cadcbe8609.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rafecolton** [comment]
For some context on 10 "random" people being assigned: https://expensify.slack.com/archives/C03TQ48KC/p1666842111537709?thread_ts=1666838060.530049&channel=C03TQ48KC&message_ts=1666842111.537709

**Comment by Gonals** [comment]
Hmmm. I can't seem to reproduce the issue. What about the rest of you?

**Comment by techievivek** [comment]
Me neither.

**Comment by Julesssss** [comment]
I can't reproduce the crash on this page, but I'm seeing a crash every time I open the app and stay on the LHN page. Both on a Pixel 4a `Android 13` and Nexus 5X `Android 8.1`

 

https://user-images.githubusercontent.com/10736861/198248892-e3735743-41c2-4480-b335-64ac11bfbd4b.mp4

**Comment by Julesssss** [comment]
I can only reproduce this on version `1.2.20-0`. Possibly triggered by the reanimated library, which for some reason is passing a null reference to a Double conversion function in the Java library.  I'm going to look further into this, but likely will suggest that we simply revert the PR that introduced this -- it's a pretty major regression. 

**Logs** 
<img width="1084" alt="Screenshot 2022-10-27 at 10 41 54" src="https://user-images.githubusercontent.com/10736861/198251897-6af10cc3-b438-42a5-8c0d-2338b9c4a04c.png">

**Likely cause of crash**
<img width="570" alt="Screenshot 2022-10-27 at 10 52 32" src="https://user-images.githubusercontent.com/10736861/198253494-8c22c9e4-d15b-4a1d-99cb-0ceb2cfb9b1a.png">

**Comment by bondydaa** [comment]
hmm crap sorry didn't reload this page before trying to un-assign myself

**Comment by marcaaron** [comment]
I'm also seeing a crash similar to this on `main` and it's blocking me from testing a PR to update `react-native-onyx` to the latest version.

Should we re-open? Seems not fixed.

**Comment by marcaaron** [comment]
@kbecciv those errors look different

**Comment by marcaaron** [comment]
Gonna try to clean the build folder actually.. 1 sec.

**Comment by marcaaron** [comment]
nvm definitely was running an out of date build :oh-nothing: thanks for tuning in everyone!
