### ISSUE TITLE
Connect bank account  -User doesn't land to correct Onfido page after saved the Personal information

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12113

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Log into an account that has a workspace set up with no bank account
3. Navigate to Settings > [Workspace] > Connect bank account
4. Connect manually: Routing number 011401533 and Account number 1111222233331111
5. In the Company information form enter Alberta Bobbeth Charleson for the company name and fill out any data in the other fields.
6. Click Save & Continue
7. In the Personal information form enter any data and click Save & Continue
8. Verify you land on the Onfido page

## Expected Result:
User land to correct Onfido page

## Actual Result:
User doesn't land to correct Onfido page after saved the Personal information, there is error message appeared after refresh.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.20.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198343167-fa81c1bf-c6c4-4c6f-977f-3dc7c78cd9b4.MP4

https://user-images.githubusercontent.com/93399543/198343170-7356ab66-5fbe-46d7-9c8b-d24788e75c5f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
This is not a Deploy Blocker. 

Also @kbecciv can you test this with the recommended credentials (Alberta Bobbeth Charelson) instead of your own?

**Comment by Luke9389** [comment]
I think you need to use the recommended credentials, get all the way to step 3 of 5 and then turn your internet connection off.

**Comment by Luke9389** [comment]
I don't think this is actually an issue. The behavior above looks expected to me.
