### ISSUE TITLE
[$250] Chat - Two editing windows open at the same time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Log in with any account
3. Open any chat
4. Kill the internet connection
5. Send the message
6. Turn on the Internet
7. Click on the last message and choose "Edit comment"

## Expected Result:
Only one editing window should be open at the same time

## Actual Result:
Two editing windows open at the same time

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198368986-44911ff5-fcbb-4ad2-b217-2fc22deac51d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
I was able to reproduce on iOS. Moving this to external.

**Comment by michaelhaxhiu** [comment]
Heyo @davidcardoza, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out :)

Has this job been posted to upwork yet? If not, let's do that as a first step here to increase visibility of this job posting to the public.

**Comment by huzaifa-99** [comment]
I wanted to give a reproduction test (to possibly submit a proposal) but getting [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1667573885470069) issue when building on ios/android. Any guesses what might be causing this?

**Comment by davidcardoza** [comment]
I have been OOO. Job posted - https://www.upwork.com/jobs/~0183e621ff73890860

**Comment by thienlnam** [comment]
Hey @huzaifa-99, please keep all setup/configuration issues in #expensify-open-source channel so we can keep the discussion specific to this issue only

**Comment by thienlnam** [comment]
Waiting for proposals, cc @davidcardoza could we double this issue?

**Comment by davidcardoza** [comment]
Price doubled to $500

**Comment by puneetlath** [comment]
@thienlnam To help us clear out the large backlog of /App bugs, we're putting the spotlight every bug in the repo already than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:  
 
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by puneetlath** [comment]
This actually should be solved by sequence numbers so I'm going to go ahead and close it. @davidcardoza @thienlnam feel free to reopen if you disagree. 

Thanks for looking into everyone. Looking forward to having you contribute on other issues.
