### ISSUE TITLE
mWeb - Chat - The edited message disappears in chat conversation after tap save

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12207]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12087

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Send a message of 20000 characters. You can use Array(15000).fill('a').join('') to get a string of this size.
5. Hold with your finger and select Edit 
6.  Tap Save

## Expected Result:
The edited message displays in chat conversation after tap save

## Actual Result:
The edited message disappears in chat conversation after tap save. 
Also composed box is missing when selecting edit option.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198367818-486c5c4d-11c0-41b2-bff8-d9fb3b86001c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This seems very edge case -- 20000 chars is ~10 pages typed at single space. Will close this for now, I don't think this is a bug that someone will reasonably run into.
