### ISSUE TITLE
Web - New group - Console error when creating new group

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with any account
3. Click on FAB button/New Group
4. Select multiple users
5. Click "Create group"

## Expected Result:
There should not be any errors in the console

## Actual Result:
An error appears in the console

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.20-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5795228_image__21_](https://user-images.githubusercontent.com/43996225/198358299-70f8a164-8dcf-4c1b-b4e3-f4276e6e3f05.png)

https://user-images.githubusercontent.com/43996225/198358301-bfe4789c-0d80-499b-a051-06aaafef1273.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
I can reproduce this. This is most likely an issue coming from the server, I will investigate this more when I'm done with an API refactor.

**Comment by michaelhaxhiu** [comment]
>This is most likely an issue coming from the server

Does that mean `internal` in this case? Let's get the appropriate label assigned so Adele can help drive it forward per this process to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out

**Comment by michaelhaxhiu** [comment]
PS all bugs should be `daily`

**Comment by youssef-lr** [comment]
@michaelhaxhiu I just added the internal label. Unassigning myself as I'm busy with an API refactor.

**Comment by adelekennedy** [comment]
internal now - @youssef-lr what are next steps to add an engineer to this issue?

**Comment by arielgreen** [comment]
Adding demolition per [this thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064935349459).

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment]
That's good it's not reproducible this week. But this doesn't have a BZ assigned and it should 🤔 .

**Comment by alexpensify** [comment]
@michaelhaxhiu - I'm confused with this one. Do I need to create a job in Upwork? I see it's internal, so I don't think creating a job is the right step. Any feedback will help!

**Comment by Gonals** [comment]
> Ok, confirmed this is an Internal one. @Gonals flagging that this one looks similar to this GH:
> 
> #12637
> 
> One difference is the other GH is for inviting members instead of creating a group. If yes, I think we should close one and merge them together. Thoughts?

They seem different to me. The displayed error is not the same, so the underlying cause (and the fix) is likely different.

I'll take a look and see if we can still reproduce this. If we can, I'll fix it. Otherwise, I'll just go ahead and close it
