### ISSUE TITLE
Split Request - User receives a long wait time with no spinner after tapping on "Split Bill"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Open the New expensify beta app
2. Sign into a valid user
3. Tap on "+" > Split Bill
4. Proceed with the flow until you reach the final page.
5. Tap on "Split" green button

## Expected Result:
User expects the response to be immediate or for the app to display a loading spinner if there is a wait time

## Actual Result:
Nothing happens at first when you tap on the button, no loading spinner is shown. After a couple of seconds the app will redirect correctly but if the user tapped on the button multiple times when "waiting" then there will be multiple "split bill" messages in the chat.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.20.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198357478-0ee91386-8db8-48f2-af9b-5a3b17e94836.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
CreateIOUSplit is taking ~1.5s to return and the UI sits still while we wait. I couldn't see any recent changes to CreateIOUSplit in App or Web-E. We did make changes to the Auth command that hit prod 7 days ago though, maybe that slowed things down.

This issue should be solved with https://github.com/Expensify/App/pull/11597, since we will start creating the reports and IOU splits optimistically and don't have to wait on the API request. 

I'm not sure that this should be a blocker

**Comment by luacmartins** [comment]
I took a look at the total time taken to process this command over the past 30 days and it seems like this is consistent with the mean times before those Auth changes went live:

![Screen Shot 2022-10-27 at 12 00 06 PM](https://user-images.githubusercontent.com/22219519/198364649-738021ea-1d9c-499b-861d-47e3f7db1342.png)

**Comment by Julesssss** [comment]
Nice fix @luacmartins. I agree this won't be a problem for much longer 🤞
