### ISSUE TITLE
Improve Android FlatList performance with FlashList

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#12236]
### Problem

React Native performance on Android lists is abysmal compared to native apps. This needs to be improved for a better user experience. 

### Solution

Investigate the implementation of Shopify's [FlashList](https://shopify.github.io/flash-list/docs/) -- a FlatList replacement that [vastly improves performance](https://shopify.engineering/instant-performance-upgrade-flatlist-flashlist), especially on Android.

There are some [minor limitations](https://shopify.github.io/flash-list/docs/known-issues#2-onendreached-event-doesnt-have-distancefromend), but they say they are open to looking into these if they are important. We should simply pay someone to apply fixes if necessary.

**Comment by Justicea83** [comment]
I've used the Recylcerview for my native applicaitons, so I think the react native version will also be great:https://github.com/Flipkart/recyclerlistview

**Comment by Julesssss** [comment]
Yeah, RecyclerView is the absolute standard for native Android apps. It's annoying that FlatList doesn't implement the native RecyclerView as it clearly is inferior as an alternative.

**Comment by roryabraham** [comment]
Obviously, rebuilding bidirectional pagination in FlashList is a concern, but not an insurmountable one. Some of the work (i.e: `maintainVisibleContentPosition` Android implementation) will be reusable, and we should have a much better idea what will be involved in building it out in a new library. Would be willing to work on this piece if we validate that this library is a viable option for E/App

**Comment by Julesssss** [comment]
No action required here. We're awaiting the release of another list lib. Keeping this open in the meantime though

**Comment by roryabraham** [comment]
Marc Rousavy brought up their list component in slack this morning: https://expensify.slack.com/archives/C035J5C9FAP/p1668526367116569

**Comment by Julesssss** [comment]
Missed this notification somehow 😕 

Thanks! Their component is looking great

**Comment by Julesssss** [comment]
Closing, as it seems like Margelo has a good alternative. We can revisit later
