### ISSUE TITLE
[HOLD for payment 2022-11-24] [$500] Implement a SplashScreen on web

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new incognito window
1. Open the developer console, network tab
1. Throttle your network connection to Slow 3G
1. Go to NewDot web (production or staging)

## Expected Result:
For the ~55 seconds while the app bundle is downloading, you should see a splash screen while the site is loading.

## Actual Result:
For the ~55 seconds while the app bundle is downloading, you just see a blank white screen.

## Platform:
We already have this on iOS and Android, just needed on:

- Web
- Mobile Web

**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666947230935069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
On narrow screens (i.e: mWeb) – the splash screen should exactly match the native splash screen on iOS and Android

**Comment by vladamx** [comment]
**Proposal**

The idea is to show the splash as soon as possible and then wait for React to mount the root element with content which will replace the splash screen with app content. 

In the alternative solution, the idea is similar but we are controlling the display of the splash by making sure React is done mounting and minTime has passed.

Solution 1:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/11381171/198684569-8ae7b2fa-5c7b-4f6c-88a2-b604fdc630c6.png">

Solution 2:

Controlling the minimum splash time

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/11381171/198684353-1331af8e-e6d4-41a5-a418-9d3eae46d25f.png">

**Comment by roryabraham** [comment]
Awesome, solution 2 looks good to me, though I think if we could use an `svg` instead of a `png` that would be ideal 👍🏼 

> If we don't want this feature on desktop we could detect if we are running in Electron by inspecting window instance

No need, we can have this work the same on web/desktop.

**Comment by vladamx** [comment]
PR 31.10.2022

**Comment by davidcardoza** [comment]
Sorry I have been out of the office. Job is posted - https://www.upwork.com/jobs/~0190eba7fee32bdedd

**Comment by vladamx** [comment]
@davidcardoza I think you've mistakenly put 20 000$ instead of 250$ in the job description?

**Comment by parasharrajat** [comment]
Oh lol, Lucky mistake...

**Comment by vladamx** [comment]
PR is up

**Comment by OleksiiBieliaievDev** [comment]
To resolve this problem I would integrate a splash screen inside of the root div in index.html      <div id="root">    </div>. (“./web/index.html”)
That gives us a possibility to replace our splash screen with our app after our bundle has been loaded.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/117184445/199250477-2bf99de7-3212-4581-ba68-05f76d337f4e.png">

**Comment by VolodymyrBarybinDev** [comment]
Proposal:
1. To use the :empty pseudo-class
The spinner will be visible, as long as nothing is rendered into the container. As soon as react renders something other than comment, the loader will disappear.
2. Pass splashScreen "handlers" as props
To create two functions `showSplashScreen` and `hideSplashScreen`, and pass them to the root container via props. The functions can manipulate the DOM, or do whatever needed to control the splashScreen.

**Comment by davidcardoza** [comment]
>I think you've mistakenly put 20 000$ instead of 250$ in the job description?

Fixed

**Comment by roryabraham** [comment]
Discussing in the PR. It works as-is, we just need to decide if it's cleaner to implement it with some webpack plugins so we can extract the js and css to separate files and use a more modern code style.

I'm torn, but now leaning towards the webpack-based implementation. If @vladamx doesn't want to do that, we can probably merge the PR as-is

**Comment by vladamx** [comment]
@roryabraham

I can implement webpack inlining for a bonus, if everyone agrees.

**Comment by parasharrajat** [comment]
We use babel and browser list to transpile the code to support mostly all browsers.

**Comment by roryabraham** [comment]
> We use babel and browser list to transpile the code to support mostly all browsers.

Not for JS scripts inlined in `web/index.html` – all the transpiled code comes in the main JS bundle, which is still downloading when we show the splash screen.

**Comment by roryabraham** [comment]
Cool, let's double this to $500 and have @vladamx implement it using webpack 👍🏼

**Comment by parasharrajat** [comment]
Yeah, inline scripts are the exception. :+1:

**Comment by roryabraham** [comment]
PR almost done, but @rushatgabhane caught a style bug that we'll need to address

**Comment by roryabraham** [comment]
PR was merged, waiting for deploy & QA now

**Comment by roryabraham** [comment]
@aimane-chnaif is correct that the solution for this caused a regression in staging.

**Comment by davidcardoza** [comment]
I will begin processing payment on the 24th if no regressions come up.

**Comment by roryabraham** [comment]
Bump for payment @davidcardoza

**Comment by davidcardoza** [comment]
payment to @vladamx is processed.

**Comment by davidcardoza** [comment]
@rushatgabhane an offer was sent to you via upwork.

**Comment by davidcardoza** [comment]
@rushatgabhane moving forward please add `C+ reviewed` in issues and PRs for my team to locate the Contributor+ to pay.
