### ISSUE TITLE
[$250] Update react-native-svg library once released

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#12233]
Currently we point the react-native-svg library to a specific commit. Once [this upstream PR](https://github.com/software-mansion/react-native-svg/pull/1903) is merged and released, we need to bump our version to match it.

**Comment by Julesssss** [comment]
PR: https://github.com/Expensify/App/pull/12374

**Comment by Julesssss** [comment]
Hey @isabelastisser, this is already complete but could we please create an UpWork issue to pay out the contributor for their review? I'm going to assign you to [the PR](https://github.com/Expensify/App/pull/12374) also.

**Comment by puneetlath** [comment]
@Julesssss To help us clear out the large backlog of /App bugs, we're putting the spotlight every bug in the repo already than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:  
 
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by Julesssss** [comment]
Hi @isabelastisser, could you please create an UpWork issue to pay out @Santhosh-Sellavel please?

**Comment by isabelastisser** [comment]
Internal job posting: https://www.upwork.com/ab/applicants/1595083283153248256/job-details

External job posting: https://www.upwork.com/jobs/~017e99e729590faba2

**Comment by Santhosh-Sellavel** [comment]
Done @isabelastisser thanks!

**Comment by Santhosh-Sellavel** [comment]
@isabelastisser bump

**Comment by isabelastisser** [comment]
Sorry for the delay! Offline now but will make the payment by EOD today.

**Comment by isabelastisser** [comment]
@Santhosh-Sellavel I sent you the offer in Upwork, please accept it and I will issue the payment. Thanks!

**Comment by Santhosh-Sellavel** [comment]
Thanks, Accepted! @isabelastisser

**Comment by isabelastisser** [comment]
Paid! 

The contract ended and the job is closed.
