### ISSUE TITLE
Chat - Skin Tone and Frequently used Emojis not persistent when going offline/online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
on two devices.
2. On primary device, tap on any chat.
3. On Secondary device, open same chat.
4. On primary device, change default skin tone selector and send some angry emojis
5. On primary device, disconnect from Wi-fi
6. On primary device, wait until you see bottom message "You appear to be offline"
7. On primary device, go online (turn-on wi-fi).
8. On secondary device, make sure changes are persistent.

## Expected Result:
In both primary and secondary devices we should see same changes after going offline/online.

## Actual Result:
Skin Tone and Frequently used Emojis not persistent when going offline/online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198676968-6af4ac3f-17a4-4947-bb14-a6d074a148cb.mp4

https://user-images.githubusercontent.com/93399543/198676976-336c6c63-6b99-4541-94e1-e4cbcc2ae574.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@kbecciv , I only have one phone to test with right now, does this require two? I tried to do a simple check with one but couldn't reproduce

**Comment by kbecciv** [comment]
Yes, it requires two two devices.

**Comment by mallenexpensify** [comment]
@kbecciv if it requires two phones being used at/around the same time with one on and the other offline, can you think of use cases where a user would encounter this in the _real world_?

**Comment by kbecciv** [comment]
I don't think so.

**Comment by mallenexpensify** [comment]
K, thanks. I'm gonna close for now then
