### ISSUE TITLE
Implement attaching .txt file to send more than 15 K characters reported by @rushatgabhane 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem:
you can't send more than 15k chars.

## Solution:
Attach a .txt file when a user pastes more than 15k chars.
## Platform:
Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web
Version Number:
Reproducible in staging?: Y
Reproducible in production?: Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="21" src="https://user-images.githubusercontent.com/43996225/198685015-a9138392-3f92-45d4-b7a0-f7333b818b4b.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666957808027799?thread_ts=1666892266.003079&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Reproduced, unique labelling eng. I'm not sure if we should commit to the txt file without more eye on the issue and considering other options

**Comment by flodnv** [comment]
I think this is indeed a feature request that needs consideration in a wider audience proposal.
