### ISSUE TITLE
[$1000] Update IOU Preview Card Styles

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12258]
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project. 

**What is it:**
Small design updates to the IOU request line and preview card to match our new brand ingredients. Note that we’ll save any major IOU report view changes for N7.

![image](https://user-images.githubusercontent.com/2319350/198700477-3c3f632b-29b8-4e55-9346-1fef4d1f4d27.png)

**Does it require a mini design doc:**
No, minor style changes

**Design finished:**
Yes

cc @GabiHExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117247f0ce11c22f0</li>
        <li>Upwork Job ID: 1602386119748538368</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
@grgia What do next steps look like from here?

**Comment by shawnborton** [comment]
I don't think this one should need a Design doc, it should just be a pretty straightforward pull request. If we use our existing color variables, then we'll get the new branding ingredients added here for free when that project completes.

**Comment by grgia** [comment]
@shawnborton  could you link the figma here?

**Comment by shawnborton** [comment]
Yup! [Here ya go](https://www.figma.com/file/OgM6vzR98Qnr1gdmZOQPKz/Implement-Our-New-Brand?node-id=0%3A1).

**Comment by shawnborton** [comment]
@grgia in terms of implementation, [I left a comment](https://github.com/Expensify/App/pull/12419/files#r1012940098) over in @dangrous's PR for workspace editor illustrations about making a new entry into our theme file for the cardBG color. I think we can hopefully share that style between these two items.

**Comment by grgia** [comment]
I started this but stopped to implement core branding changes. Planning on coming back to this one once I get the colors/logo PRs completed today/tomorrow!

**Comment by grgia** [comment]
Update, I started working on this again on Friday- I'll get a WIP PR up sometime today to track progress

**Comment by grgia** [comment]
Do we have a mockup that includes the IOU on the desktop/dark theme?

**Comment by shawnborton** [comment]
Chatted in Figma but here they are again for posterity:
![image](https://user-images.githubusercontent.com/2319350/202061924-d6fb51c8-546b-4c43-8a49-02489e53716a.png)

**Comment by grgia** [comment]
Closing as completed!

**Comment by grgia** [comment]
Reopening for PR Review Payment. @puneetlath could you help with that?

**Comment by puneetlath** [comment]
Yep. @parasharrajat sent you a hiring offer.

**Comment by puneetlath** [comment]
Paid.
