### ISSUE TITLE
Update our app store listings

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12255]
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project. 

What is it:
Updating the [Apple](https://apps.apple.com/us/app/expensify-cash/id1530278510) and [Google](https://play.google.com/store/apps/details?id=com.expensify.chat&hl=en_US&gl=US) app store listings for NewDot

![image](https://user-images.githubusercontent.com/2319350/198699389-c7414bb6-92eb-4eca-adc7-8ce36d8932e7.png)

Does it require a mini design doc:
No, no code changes needed to implement this

Design finished: No, we could use some help from marketing before finalizing design

**Comment by GabiHExpensify** [comment]
I added the `waiting for copy` label since it sounds like design can't really move this forward until marketing suggests some copy updates, and it auto-assigned @CherylWalsh... I was planning to work on this, but equally happy to collab or let you take the reigns if you want @CherylWalsh! Just lmk :) 

We need to:
- [Most important, since design depends on it]: Review the mock-ups that Shawn posted in the OP, suggest some copy updates, or think through whether there's a totally different way we want to show this off. (It might help to do some quick research on the app store and see what other cool apps are doing these days.)
- [Less important, since it's not needed for design to move forward here, so we could probably move this into a separate GH]: Update the copy in our app store listing, it's been a loooong minute since we've even looked at it.

**Comment by CherylWalsh** [comment]
@GabiHExpensify I'm still catching up from OOO and given this is urgent, I'd like to unassign myself if that is OK as I'm a bit behind.

**Comment by GabiHExpensify** [comment]
Okay, gonna spin the copy wheel again then!

**Comment by davidcardoza** [comment]
I am catching up from being out of the office from the Xero roadshows last week and I have a short week this week too. I don't want to drop the ball on this because of my limited bandwidth. i am going to spin the copy wheel to reassign.

**Comment by davidcardoza** [comment]
@GabiHExpensify Not sure if you have the bandwidth to take this, I know you had assigned the issue out, feel free to reapply the `Waiting for copy` label again.

**Comment by StefStavri** [comment]
Removing myself and the waiting for copy level as there is no verbiage written yet to polish :)

Discussing here! https://expensify.slack.com/archives/C03SSAQG5/p1667405454496479?thread_ts=1667396648.336749&cid=C03SSAQG5

**Comment by sketchydroide** [comment]
happy to help with this one as I know the process

**Comment by LLPeckham** [comment]
Since you're here @trjExpensify 😏 -- For NDR -- should we only show that on US app stores? Or is this something we're expecting to have with the next update? I thought it was further out so just wanted to confirm.

**Comment by trjExpensify** [comment]
Ah yeah, I didn't notice we're showing copy from the `Reimburse expenses` page here. If the focus is on the Expensify Card, then I would have thought that would show the `Issue cards` workspace settings page?

**Comment by shawnborton** [comment]
Yeah sorry, those screens are all placeholders for the time being!

**Comment by shawnborton** [comment]
Once we sort out copy, I'll create the correct screenshots to go with them.

**Comment by LLPeckham** [comment]
@trjExpensify - I'm just trying to get a feel of what we're actually wanting to promote for the next app store update. I'll bring my question to Slack to have a larger discussion since I'm not actually sure if we want to focus on the card or tout any of the features (mileage, reimbursement, etc. -- if those will be done in time for the next update). Thanks!

**Comment by trjExpensify** [comment]
Yeah, great idea. FWIW, the free plan workspace editor is already live in NewDot so you can do mileage, reimbursement etc.

**Comment by JmillsExpensify** [comment]
Not sure the best place to have this discussion, but I'm pretty torn between the most important high-level message. Essentially:

 - Is New Expensify focused on the consumer angle more than anything else?
 - Or should the business angle be the focus?
 - Or even alternatively, should we keep both messages like we have now?

I'm speaking out loud here, but I would think we should still try to thread the needle on both. Maybe that gives us this?

 - Request money
 - Collaborate with friends and colleagues
 - Issue company credit cards
 - Reimburse expenses

**Comment by LLPeckham** [comment]
@JmillsExpensify - was just going to drop a discussion in #Product to discuss the angles, but am chatting with @trjExpensify - and the latter might make sense as well. I think it's ok to focus on both for now - I feel like it's not quite ready to deep dive into only consumer-focused, so I like mixing in both. I will take this to Slack!

**Comment by JmillsExpensify** [comment]
Thank you!

**Comment by LLPeckham** [comment]
Will work on some copy proposals for this to bring to #marketing for a pre-design tomorrow.

**Comment by LLPeckham** [comment]
**Need to update:**

- [ ] Google slides
- [ ] Google Description
- [ ] App Store slides (for iPad and iPhone)
- [ ] App store description

Remaining question(s)
- Do we want blurbs at the top of each slide? We currently do not.

**Comment by LLPeckham** [comment]
Drafting blurbs this morning and then will share for review.

**Comment by LLPeckham** [comment]
Posted copy discussion [here](https://expensify.slack.com/archives/C03SSAQG5/p1667858930911229).

**Comment by LLPeckham** [comment]
Just about done! Chatting last tweaks [here.](https://expensify.slack.com/archives/C03SSAQG5/p1668030348211029?thread_ts=1667858930.911229&cid=C03SSAQG5)

**Comment by LLPeckham** [comment]
@shawnborton - I think we're good to go with the latest changes in [the doc ](https://docs.google.com/document/d/1SRLWycdfGV994kl1LuyWlib1GlwSKMl_W_Z43EKw4VI/edit)(and as seen in your mock [here](https://expensify.slack.com/archives/C03SSAQG5/p1668031563016749?thread_ts=1667858930.911229&cid=C03SSAQG5)) 

You can find all the slides with their corresponding titles and blurbs, as well as the updated App Store description.

**Comment by GabiHExpensify** [comment]
Does this still need to be a `Daily`? I know we wanted the copy daily, but I'm not sure what the level of urgency is on the design + deploying them.

**Comment by shawnborton** [comment]
I think we can remove waiting for copy and I will switch to Weekly as well, though this is definitely on my priority list!

**Comment by shawnborton** [comment]
Here is what I have for the rest of the platforms (smaller iPhone, iPad. Note that Android uses the same taller images as iPhone)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/2319350/203116469-4b93fffd-c53b-4a3a-a667-141766be055f.png">


Then it sounds like @sketchydroide can help us deploy these once we're ready to release some of the new color changes.

**Comment by LLPeckham** [comment]
I believe we're still waiting for the green light to release these?

**Comment by shawnborton** [comment]
I think once we get a couple more brand ingredients into NewDot (fonts, input styles, etc) we can release this. We're also waiting to finish up the font agreement with Newlyn too. So let's keep holding but maybe next week we can launch these?

**Comment by LLPeckham** [comment]
Don't think this is overdue, Melv.

**Comment by LLPeckham** [comment]
Still not

**Comment by shawnborton** [comment]
Not overdue

**Comment by LLPeckham** [comment]
Not overdue

**Comment by shawnborton** [comment]
I think we can go ahead and release these... thoughts? @sketchydroide let me know what you need to make that happen. Images are all here: [App Store Images.zip](https://github.com/Expensify/App/files/10410781/App.Store.Images.zip)

**Comment by sketchydroide** [comment]
was OOO will get to it this week

**Comment by JmillsExpensify** [comment]
Agree with releasing. Would love to cross this todo off this week.

**Comment by shawnborton** [comment]
Any update @sketchydroide? We'd love to release these ASAP.

**Comment by sketchydroide** [comment]
doing it now

**Comment by sketchydroide** [comment]
one of the ipad images had the wrong dimensions, already DM @shawnborton and we will sort it today

**Comment by shawnborton** [comment]
Okay, let's try these: [App Store Images.zip](https://github.com/Expensify/App/files/10466643/App.Store.Images.zip)

I fixed that fourth iPad image, let me know if it works!

**Comment by shawnborton** [comment]
Nice, Google is live 🎉 
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/2319350/213747041-8d449eb5-5d9e-40bb-a79d-eb7557c82907.png">

Now just waiting for Apple to hit once we have our next deploy.

**Comment by shawnborton** [comment]
Well crap, looks like I gave you a bad screenshot for the second "Split bills" for just the iPhone 6.5 version :(

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/2319350/214160901-926f6fad-174a-4eb3-9762-ab07584d910b.png">


Mind uploading new images? Here they are: [App Store Images.zip](https://github.com/Expensify/App/files/10484014/App.Store.Images.zip)

**Comment by sketchydroide** [comment]
for some reason this lost my assignment?

**Comment by sketchydroide** [comment]
yeah will do it now

**Comment by sketchydroide** [comment]
Update Android, need to wait iOS finishes review, so we can then create the new version and update images

**Comment by shawnborton** [comment]
Sounds great, thank you!

**Comment by sketchydroide** [comment]
Ok update the iOS ones as well, we will need to wait for deploy today hopefully

@luacmartins CCing you since you are deploying today

**Comment by luacmartins** [comment]
Deploy is happening now. Was there any action required from my part?

**Comment by shawnborton** [comment]
I don't think you have to do anything additional from my understanding, since Andre has the new images already queued up?

**Comment by sketchydroide** [comment]
Yep I think this is done automatically with the deploy if there is already a version with the correct build number on the AppStoreConnect, I honestly did not know how the deploy script would handle it the first time, but it seems it was very straigh forward, might write a SO for it.

**Comment by sketchydroide** [comment]
I think we can close this one right @shawnborton?

**Comment by shawnborton** [comment]
Yup, we can close. Thanks everyone!
