### ISSUE TITLE
[$1000] [Hold for payment 2022-12-06] Update workspace editor illustrations

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12257]
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project. 

**What is it:**
Updating the illustrations found in the workspace editor. We will also update the sections of the editor to look like “cards” 

![image](https://user-images.githubusercontent.com/2319350/198700146-641a8210-71bd-4e8c-a2be-014c69c9a6e8.png)

**Does it require a mini design doc:**
No, minor style changes

**Design finished:**
Yes

cc @GabiHExpensify 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191db9c76490e36ff</li>
        <li>Upwork Job ID: 1601066729371267072</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Are we going to implement these changes asap? I vote yes, even if that means they go live before everything else.

**Comment by shawnborton** [comment]
Yeah, I don't see why we can't get started on a PR for this sooner than later. @dangrous how do you feel about that?

**Comment by dangrous** [comment]
Yep! I can get started this week (hopefully today!) To confirm what we discussed in newDot, to start, that would cover everything except changing the fonts and the background color (would have the capsule around the task, just in our current BG color)?

**Comment by shawnborton** [comment]
Exactly, we can use the current gray BG color we have to create the card style. And then we can also update the illustrations. I think that's really all we'd need to do for now.

**Comment by dangrous** [comment]
Just adding this here so I can close the tab - here's the Figma https://www.figma.com/file/OgM6vzR98Qnr1gdmZOQPKz/Implement-Our-New-Brand?node-id=97%3A13461

**Comment by dangrous** [comment]
Been catching up on some chores (and also moving cross country?!?!) - should have time/energy to finish this up tomorrow.

**Comment by dangrous** [comment]
This is now in review! It looks great now with the existing theme/colors, but we should discuss how/when we want to merge it, since it'll likely need some (hopefully small adjustment) once the new stuff is live.

I currently have it on hold, but what do we think is the best order?
* Push now and make a separate PR to clean up once the theme is live
* Keep it on hold until the theme is live, and make the adjustments in this PR before pushing

**Comment by shawnborton** [comment]
cc @Luke9389 @grgia - curious for your thoughts on Daniel's comments above ^

**Comment by Santhosh-Sellavel** [comment]
@dangrous Please assign this to me for tracking payment for this [PR](https://github.com/Expensify/App/pull/12419)

**Comment by JmillsExpensify** [comment]
@dangrous Does @Santhosh-Sellavel need to be paid out for the PR review now? Assigning myself to help out with that.

**Comment by dangrous** [comment]
Yep, ready to pay (past 7 days on prod) - thanks @JmillsExpensify !

**Comment by JmillsExpensify** [comment]
@Santhosh-Sellavel Job is above. I also invited you as well, so just confirm when you've been able to accept and we'll keep the process moving forward.

**Comment by Santhosh-Sellavel** [comment]
Done thanks!

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by JmillsExpensify** [comment]
All handled. Closing this one.
