### ISSUE TITLE
Scrollbar is overlapping with the text in composer reported by @puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat> Paste a big paragraph
2. Scroll the text and hover over the scroll bar

## Expected Result:
The text should be visible

## Actual Result:
The scrollbar overlaps with the text

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Screenshot 2022-10-28 at 15 26 58](https://user-images.githubusercontent.com/43996225/198730767-ebd15e70-6e24-403f-b7cd-a2b2e353bd22.png)
<img width="820" alt="Screenshot 2022-10-28 at 3 43 21 AM" src="https://user-images.githubusercontent.com/43996225/198730768-e1a62815-091c-42e4-9af3-8fa196331f39.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666910633735899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
I'm not able to reproduce this even if I zoom in lots - 
![image](https://user-images.githubusercontent.com/11725910/199101847-6374dbb4-168d-458f-9f74-47f2b5165591.png)

**Comment by Puneet-here** [comment]
@slafortune, It is reproducible. Can you keep the browser at full width and paste the text given below

af;jalskf;slf;jsaf;ljasf;ksjldf;saf;jasdjkf;sdjlf;sjf;skjdf;slkjf;slf;jskf;djskf;slkf;jslkf;jslf;kjaslf;jaskf;jsalf;jslkf;jslkdf;jslkf;jslkdf;jslkf;jsldf;kj
consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretiumAdipiscing elit pellentesque habitant morbi tristique senectus et. Porttitor leo a diam sollicitudin tempor. Nibh ipsum consequat nisl vel pretium

**Comment by Puneet-here** [comment]
bump @slafortune
