### ISSUE TITLE
[$1000] Web- Chat - Action's menu is truncated when going to minimum page size

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to any chat
4. Click on the FAB `+` (Action menu) and verify that it is open
5. Minimize browser's page

## Expected Result:
The action menu should be located at the bottom of the page on its full width, and stay dynamically fixed in position.

## Actual Result:
Action's menu is truncated and shows up in the wrong position.

## Workaround:
>Unknown
N/A - this is a UI deficieincy. 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Minimal](https://user-images.githubusercontent.com/93399543/198708334-91cec46d-a4cd-4a85-81b8-6fa167ebbe69.png)
![Full](https://user-images.githubusercontent.com/93399543/198708336-4637e858-c452-4b41-b8c4-63b74a27a2cd.png)

https://user-images.githubusercontent.com/93399543/198708337-89c678de-3633-40d7-9e4e-85746bb7efa0.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01164e6332e6335039

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Exported to Upwork. Job is publically available.

**Comment by michaelhaxhiu** [comment]
@AndrewGable I feel pretty certain this is `external` but you can veto that if you disagree

**Comment by AndrewGable** [comment]
I agree it seems external

**Comment by michaelhaxhiu** [comment]
Doubling price.

**Comment by michaelhaxhiu** [comment]
Doubling price

**Comment by michaelhaxhiu** [comment]
Still waiting for interest. Contemplating making this $1k bounty sooner rather than later.

**Comment by Someone-here** [comment]
I did some digging and found out that the thing causing the problem, the root cause is the prop `isDrawerOpen`. Whenever this is true, the message screen loses focus when the window shrinks and when this is false, everything works correctly.

**Comment by michaelhaxhiu** [comment]
@Someone-here that's an exciting lead, but we'll need you to frame it into a proposal. Did you have a chance to read this firstly? https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

Within that page is a subsection about making proposals. Take a look if you have a moment.

**Comment by Someone-here** [comment]
Yes @michaelhaxhiu, thank you for your concern. I am aware of the the proposal workflow. I was just wondering the exact use of `isDrawerOpen` prop and once I figure that out, I will draft it into a proposal.

**Comment by Someone-here** [comment]
https://user-images.githubusercontent.com/77237602/201459890-bdce09d9-c543-415e-8f51-01658f819301.mp4

Doesn't work when isDrawerOpen: true

https://user-images.githubusercontent.com/77237602/201459917-1efe9caa-cb61-48d9-9a18-de2d255545f1.mp4

Works when isDrawerOpen: false

It is almost random for it to be true of false when clicked on any chat. For some it is true and some false

**Comment by michaelhaxhiu** [comment]
@Someone-here are you still interested in solving this job? If so can you address @rushatgabhane's question about?

**Comment by michaelhaxhiu** [comment]
`Helped wanted` label was stripped away, re-adding that as this is still fair game for a winning proposal. @Someone-here has a proposal in the works but needs to address the latest question from @rushatgabhane.

**Comment by Someone-here** [comment]
Yes, @michaelhaxhiu I am still trying to solve this issue. I think I have figured out why you are using `isDrawerOpen` prop, for the chats menu on small screens and it works fine there. But the problem is that when the user once clicks on a chat from the menu in widescreen mode, it sometimes doesn't shift focus to the chat area and it thinks that the drawer is open on a small screen, causing this glitch. The user has to click the chat icon twice in order to shift focus properly. 
So this seems to be a problem in the hook that we are using to get the status of the drawer as it is not updating properly on widescreen.

**Comment by s77rt** [comment]
Hi,
is this still valid? it seems I can't reproduce from my side (1.2.28-1)

**Comment by puneetlath** [comment]
@AndrewGable To help us clear out the large backlog of /App bugs, we're putting the spotlight every bug in the repo already than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:  
 
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by AndrewGable** [comment]
Agree with @s77rt - Seems to be fixed 🎉 


https://user-images.githubusercontent.com/2838819/202564394-59ce0b7d-f7ba-467f-aed3-c98d25d7b190.mov

Reopen if you disagree.
