### ISSUE TITLE
Create a custom platform sound

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12262]
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project. 

What is it:
Create custom brand sounds to use for things like notifications and when messages are received.

(Old issue for reference: https://github.com/Expensify/Expensify/issues/196381)

Does it require a mini design doc:
Yes

Sounds finished:
No

**Comment by shawnborton** [comment]
Adding a note that as part of [this conversation here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667277018509469), we've decided to remove this one from the WAQ Project. That doesn't mean we shouldn't do this, but let's prioritize all other WAQ issues first before moving onto this one.

**Comment by GabiHExpensify** [comment]
Discussed collaborating on this with TCW: https://expensify.slack.com/archives/C03KN50J0PM/p1669855558618889

**Comment by shawnborton** [comment]
Still holding but we can ping TCW about this again.

**Comment by shawnborton** [comment]
Not overdue

**Comment by JmillsExpensify** [comment]
Where does this one fit in your opinion? I think it'd be good to pick up after TCW gets through the gauntlet of upcoming conferences.

**Comment by shawnborton** [comment]
Yeah I agree with that.

**Comment by cristipaval** [comment]
Assigned this one to me after discussing with @Julesssss and @arosiclair about Notification project.

**Comment by shawnborton** [comment]
Let me kick this off again with TCW, going to ask in the channel now.

**Comment by cristipaval** [comment]
@shawnborton , any update on this one?

**Comment by shawnborton** [comment]
No update, will check in with TCW on this [here](https://expensify.slack.com/archives/C03KN50J0PM/p1681835182634759?thread_ts=1680101981.577719&cid=C03KN50J0PM)

**Comment by cristipaval** [comment]
Still waiting for TCW

**Comment by shawnborton** [comment]
Let's close this issue out and move this back to internal (Expensify/Expensify) while we create the sounds. https://github.com/Expensify/Expensify/issues/196381
