### ISSUE TITLE
Search - User is unable to find the name of the workspace he/she just created for public account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12272]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new public account (gmail) and validate it
3. Go offline
4. Create a new workspace from the green plus, New workspace.
5. OR if you already have a workspace click the avatar in the header to open the settings, click the name of an existing workspace click the 3 vertical dots in the header, New workspace.
6. Close the workspace page
7. Click the search icon in the header and enter the name of the workspace you just created

## Note:
User is able to find the name of the workspace he/she just created for expensifail accounts

## Expected Result:
User is able to find the name of the workspace he/she just created

## Actual Result:
User is unable to find the name of the workspace he/she just created for public account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** kbecciv+1028abb6@gmailcom/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198734106-810252fa-ee69-47a4-a44b-1396036c5d58.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
I wasn't able to reproduce this on staging web, the workspace was searchable for me:

https://user-images.githubusercontent.com/59587260/198937525-f9aa4359-0fdd-433d-9497-35ee23e5a6dc.mp4

@Expensify/applause could you please try again and let me know if it's still reproducible?

**Comment by kbecciv** [comment]
@kadiealexander Can you please try with gmail account (public)?
