### ISSUE TITLE
Dev - dev console error on IOU request reported by @aimane-chnaif

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to any account
2. Request money to someone
3. Upon successful request, console error shows

## Expected Result:
No console error

## Actual Result:
Console error:  Warning: Failed prop type: Invalid prop `iouReport.chatReportID` of type `number` supplied to `IOUDetailModal`, expected `string`.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.21-4

**Reproducible in staging?:** N

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Reproduced only in Dev 

https://user-images.githubusercontent.com/43996225/198735050-74958dc9-ecee-43c3-948b-c6fb267abee2.mov

https://user-images.githubusercontent.com/43996225/198735080-6cc2a913-3215-4f3c-9563-82c7344747ab.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aimane-chnaif 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666979568765499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
@vitHoracek, I think we can close this since we will be switching for strings?

**Comment by thesahindia** [comment]
@mountiny, I think we can close this since we will be switching for strings?

**Comment by mountiny** [comment]
That is correct, these errors are kinda expected at the moment as we are in the middle of switching to strings for the ids. That also means we wont be issuing report bonus unfortuntealy.
