### ISSUE TITLE
[HOLD] [$250] IOS - LHN - The Global create menu is not automatically displayed after you log in for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12281]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Create a new applause.expensifail account/gmail
3. Verify that after you log in for the first time, the Global create menu is automatically displayed and open (showing the Request Money, New Chat, ect options)

## Expected Result:
The Global create menu is automatically displayed after you log in for the first time

## Actual Result:
The Global create menu is not automatically displayed after you log in for the first time

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.21.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/198835111-7b60bc8a-3219-4738-8f88-ed958bf3dcb0.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@Julesssss Hmm I can see the FAB in the screenshare, what is the issue here @kbecciv ?
<img width="360" alt="image" src="https://user-images.githubusercontent.com/36083550/199039974-b8a5493e-0005-4188-bb3d-31676254ea7c.png">

**Comment by Julesssss** [comment]
@mountiny on first-open the Fab should show in the open state, so you should see the list of options, like Send Money, Request Money, ect

**Comment by mountiny** [comment]
Ah, I see, that was not clear to me from the instructions.

**Comment by Julesssss** [comment]
I updated the description to make this more obvious

**Comment by mountiny** [comment]
@Julesssss can you repro locally? there is [this refactor of the Popover](https://github.com/Expensify/App/pull/11907) which brings some performance gains hopefully and maybe this would be fixed there.

**Comment by Julesssss** [comment]
I was able to reproduce it, but not consistently. It seems to work as expected for me at the moment:

**Web - staging**
https://user-images.githubusercontent.com/10736861/199047426-c1e1f833-f136-45c7-8848-3197607e35b5.mov


**Web - prod**
https://user-images.githubusercontent.com/10736861/199046704-50a8e4b2-29d2-49ac-bff6-c98fe17f2883.mov

**Comment by kbecciv** [comment]
Issue is reproduced in Web with build 1.2.22.1

https://user-images.githubusercontent.com/93399543/199125778-e40feb4e-21fe-4ac3-92b7-0d796d9bbc34.mp4

**Comment by Julesssss** [comment]
@tylerkaraszewski we removed this as a deploy blocker as it wasn't always reproducible. Personally, I think we should ask Applause to retest.

**Comment by tylerkaraszewski** [comment]
Applause, please re-test and see if this is reproducible or not.

**Comment by mountiny** [comment]
cc @kavimuru @isagoico

**Comment by isagoico** [comment]
Checking with the team at the moment

**Comment by kbecciv** [comment]
@mountiny Issue is reproduced with build 1.2.24.4

https://user-images.githubusercontent.com/93399543/200597680-522db4e7-d83f-470a-a4af-1fc8e735fbd9.mp4

**Comment by mountiny** [comment]
cc @hannojg since you might have some idea about this as you have refactored the button.

**Comment by pecanoro** [comment]
@MelvinBot not overdue!

**Comment by mountiny** [comment]
Actually, lets put this on hold for https://github.com/Expensify/App/issues/12281

**Comment by mountiny** [comment]
@kbecciv @kavimuru Could you please retest this in staging Android? Seems like a C+ tried this and wasnt able to repro anymore https://github.com/Expensify/App/pull/12369#issuecomment-1311795606

**Comment by kavimuru** [comment]
@mountiny This was reproducible in iOS. Will retest in both Android and iOS and update here.

**Comment by kbecciv** [comment]
Issue is not reproduced for both Android and iOS apps.

https://user-images.githubusercontent.com/93399543/201687397-be43c8c1-70b1-4b9b-8330-be62048c1aad.mp4


https://user-images.githubusercontent.com/93399543/201687403-a7a69e5b-ecaa-4045-a21e-50a047d043f6.MP4

**Comment by mountiny** [comment]
Ok, I think given this is so unreliably reproducible we can disregard this and potentially come back to this issue if it becomes reliably reproducible issue.

Thank you @kbecciv
