### ISSUE TITLE
There Should Be An Extra Space After The Selected Currency In Send Money Dialog reported by huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click the 'New' button
2. Select 'Send money'
3. Click on currency (picker)
4. Select any currency ending with 'O' (there are only 2 of those, NIO-NIO and MRO-MRO)
5. Enter a 0 (or multiple)
6. The currency and the amount are not distinguishable very well

## Expected Result:
There should be an empty space between the currency and the amount (for selected currencies at least or for currencies with no symbol)

## Actual Result:
There is no empty space between the currency and the amount

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.21-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img width="960" alt="currency" src="https://user-images.githubusercontent.com/43996225/199019064-22b51a95-6976-4e7b-b9e6-caafbf8c48e0.png">

https://user-images.githubusercontent.com/43996225/199019099-29d1da02-7150-4ec5-913f-84925c46a151.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @huzaifa-99

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667171527208099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Closing after discussing in https://expensify.slack.com/archives/C01GTK53T8Q/p1667171527208099
