### ISSUE TITLE
[HOLD for payment 2022-11-18] [$250] Download icon stays green after downloading and can't download the image again

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Log in with any account
3. Go to any chat
4. Send an attachment
5. Click to "Download" badge in chat to downloading attachment
6. Try clicking to "Download" badge again without clicking outside the download tab

## Expected Result:
The attachment should be able to be re-downloaded

## Actual Result:
Re-downloading attachment is not possible

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199121338-d88619ec-8c24-40c1-bbe8-7d356844b03f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
I was able to reproduce the issue on staging, but not on production. Sending out to external

**Comment by eVoloshchak** [comment]
@0xmiroslav, thanks for the proposal!

@iwiznia, @0xmiroslav's proposal looks good to me

🎀👀🎀 C+ reviewed!

**Comment by iwiznia** [comment]
Looks good. Do we have any places where autoReset is being passed as `false`?
And even if so, should we change the default to true? Sounds like in most cases that's the correct behavior?

**Comment by iwiznia** [comment]
Based on the data above, I think we should change it to be the default, since only one of all those really needs it set to false.

**Comment by iwiznia** [comment]
@eVoloshchak what do you think?

**Comment by eVoloshchak** [comment]
> @eVoloshchak what do you think?

Agree, making it `true` by default is better

**Comment by iwiznia** [comment]
Awesome, yes @0xmiroslav go ahead. @davidcardoza please hire @0xmiroslav

**Comment by iwiznia** [comment]
Not overdue, waiting for assignment

**Comment by davidcardoza** [comment]
Sorry for the delay, I was out of the office. @0xmiroslav I hired you for the job via upwork - https://www.upwork.com/jobs/~01f46034d3f5da6f39

**Comment by eVoloshchak** [comment]
PR was deployed to production

**Comment by davidcardoza** [comment]
@iwiznia Am I good to go processing payment?

**Comment by iwiznia** [comment]
> @iwiznia Am I good to go processing payment?

No, do what Melvin says.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by davidcardoza** [comment]
Payments processed to @eVoloshchak and @0xmiroslav

**Comment by davidcardoza** [comment]
Bonus was sent.

**Comment by eVoloshchak** [comment]
@davidcardoza, this Upwork job is still active for me and I can't find any payments made on 18th of November.
Could you double-check it please?

**Comment by davidcardoza** [comment]
Check again, payment sent.

**Comment by eVoloshchak** [comment]
> Check again, payment sent.

Received, but without the bonus payment. C+ are also eligible for the bonus

**Comment by davidcardoza** [comment]
C+ bonus sent

**Comment by davidcardoza** [comment]
Bonus sent.
