### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] Cursor moves to the end of the message when inserting an emoji in between the words reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Type something in the composer e.g. "hello there"
3. Now type :wave: in between "hello" and "there"

## Expected Result:
The cursor is positioned at the end of the emoji

## Actual Result:
The cursor is positioned at the end of the message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22-1

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![2022-11-01_12-09-31 (1)](https://user-images.githubusercontent.com/62073721/199229477-cded2f73-4838-4105-8534-bdf08631a802.gif)

https://user-images.githubusercontent.com/43996225/199127521-33318600-d63e-4c04-a751-30c2dc7c57e3.mp4
https://user-images.githubusercontent.com/43996225/199127573-9bac7276-3186-4e2e-8401-5c148d47b9eb.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667226062750359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01ee82e558b5ff525a

**Comment by cokacode** [comment]
this should have been closed by now, the proposal @hungvu193 has provided works.

**Comment by AndreasBBS** [comment]
**Proposal**
It appears that the `e.nativeEvent.selection` values are being set to the end of the string in the `onSelectionChange` handler when the emoji is replaced.

My proposed solution is, when the emoji is replaced, to get the cursor position from previous state and set the selection value in the new state.

In the `ReportActionCompose.js` function `updateComment(comment, shouldDebounceSaveComment)` would look like this:
```diff
  const newComment = EmojiUtils.replaceEmojis(comment);
+ this.setState((prevState) => {
+     let newState = {
+         isCommentEmpty: !!newComment.match(/^(\s|`)*$/),
+         value: newComment
+     }
+ 
+     if(comment !== newComment) {
+         const remainder = prevState.value.slice(prevState.selection.end).length
+         newState.selection =  {
+             start: newComment.length - remainder,
+             end: newComment.length - remainder
+         }
+     }
+ 
+     return newState
  });
```

In the `ReportActionItemMessageEdit.js` function `updateDraft(draft)` would look like this:
```diff
  const newDraft = EmojiUtils.replaceEmojis(draft);
+ this.setState((prevState) => {
+     let newState = {draft: newDraft}
+
+     if(draft !== newDraft) {
+         const remainder = prevState.draft.slice(prevState.selection.end).length
+         newState.selection =  {
+             start: newDraft.length - remainder,
+             end: newDraft.length - remainder
+         }
+     }
+
+     return newState
+ });
```

Here's a video of this code taking effect:

https://user-images.githubusercontent.com/12399440/199389127-fbe710af-c641-4e9b-a56e-cd5707cbeca6.mov

**Comment by laurenreidexpensify** [comment]
@rushatgabhane bump ^^

**Comment by hungvu193** [comment]
@rushatgabhane yeah, it worked on all platforms, I tested them all. 
Let me see if we can use selection as a state.

**Comment by hungvu193** [comment]
yeah, that's right. If I use selection props, it will look like:

```javascript
 this.setState(() => {
            const newState = {
                isCommentEmpty: !!newComment.match(/^(\s|`)*$/),
                value: newComment,
            };
            if (latestIconPosition !== -1) {
                newState.selection = {
                    start: latestIconPosition,
                    end: latestIconPosition,
                };
            }
            return newState;
        });
```

**Comment by AndreasBBS** [comment]
@hungvu193 Both our approaches work the same when writing an emoji, the big difference is how the paste is handled.
Let's say we're pasting the string `:wave: friend ` in the string `Hello nice to meet you` between the word "Hello" and "nice": `Hello |nice to meet you` (representing the cursor with the char "|")
- Using your approach, after you paste; the cursor would be left at the end of the string: `Hello 👋 friend nice to meet you|`
- Using your approach before your update, after you paste; the cursor would be left after the emoji: `Hello 👋| friend nice to meet you`
- Using my approach the cursor would be left where it was before the paste, behind the word nice: `Hello 👋 friend |nice to meet you`

**Comment by laurenreidexpensify** [comment]
@ctkochan22 bump here 👍 for this solution Thanks

**Comment by AndreasBBS** [comment]
Hi. I'm writing here trying to get an update. I already submitted the proposal on Upwork. Is there something on my side holding up? It's my first time contributing to this project, if there's anything on my side that needs to be done just let me know :smiley:

**Comment by ctkochan22** [comment]
Man, hard to keep track of so many of these. Good work here everyone! @rushatgabhane I'm good with your recommendation. @AndreasBBS 's solution looks good. 

@laurenreidexpensify lets hire and move forward
 

> I then realized that there's also a branch main and that's the one I originally had tested for the bug.

Second @AndreasBBS , we no longer use the `master` branch. We moved over to using `main`. So its now, `main` -> `staging` -> `production`

**Comment by laurenreidexpensify** [comment]
@AndreasBBS I've hired you in Upwork now, if you can let us know when you're aiming to have the PR up? Feel free to ask any questions in Slack as you go : )

**Comment by AndreasBBS** [comment]
I just discovered a strange behavior in the Android app that I'm trying to understand if it was causes by my changes. It's why it's taking me a while to make the PR. I want to make sure I don't create another problem trying to solve. Thanks for your patience.

**Comment by laurenreidexpensify** [comment]
Everyone has been paid now, apols!
