### ISSUE TITLE
[IOS] Delete workspace crash

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

I get this crash in the IOS simulator, the crash seems to come from here:

https://github.com/Expensify/react-native-onyx/blob/91aabb7219ddc8722cc2955de0398b1ae70c546d/lib/Onyx.js#L1089

When we get an Onyx update setting a deleted workspace to `null`.

From the AsyncStorage.multiMerge [documentation](https://reactnative.dev/docs/asyncstorage#multimerge), it seems like for a pair of key / value, it is expected that the value is a string (stringified JSON).

I'm wondering if we should be calling `JSON.stringify` on the value if the value is `null` (JSON.stringify(null) === 'null'). Alternatively, maybe if the value is `null` we should be clearing the keys from the storage using `Storage.multiClear`.

## Action Performed:
1. Login in IOS
2. Create a workspace
3. Delete the workspace

## Expected Result:
Workspace get deleted, no error

## Actual Result:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/87341702/199134636-64d8dbc5-0dee-4828-8b69-21d5ba906865.png">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
Thanks to @aimane-chnaif I have a good idea on how to fix this in the backend. Taking it internally.

**Comment by aldo-expensify** [comment]
PR up and ready for review: https://github.com/Expensify/Web-Expensify/pull/35386

**Comment by sobitneupane** [comment]
@aldo-expensify [This issue](https://github.com/Expensify/App/issues/11266) just reopened. Do you think it is related to this issue? It was previously closed believing it was related to https://github.com/Expensify/App/issues/10975

**Comment by aldo-expensify** [comment]
@sobitneupane it does look very similar the error and the [PR](https://github.com/Expensify/Web-Expensify/pull/35386) fixing this has not been deployed yet. I'll try to see if I can find more info on the crash to see if it the same.

**Comment by aldo-expensify** [comment]
I looked at crashlytics, but there is no extra information on the data that may have caused the crash. I would say, lets wait for that PR to be deployed.

The crash happened 4 times today, but it was the same device every time, so it is not something common/widespread.

**Comment by aldo-expensify** [comment]
The [PR](https://github.com/Expensify/Web-Expensify/pull/35386) fixing this was deployed a while ago, not sure why this remained open. Closing!
