### ISSUE TITLE
[HOLD for payment 2022-11-18] [$250] Workspace - No scroll bar to navigate a long list of members 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Go to workspace > Manage members

## Expected Result:
There should be a scroll bar to navigate to a member

## Actual Result:
No scroll bar appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.22-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="6" src="https://user-images.githubusercontent.com/43996225/199252866-1eb6d3f1-638f-4980-8852-b7364190036b.png">

https://user-images.githubusercontent.com/43996225/199252923-a9d5dfd9-3bf4-4ee0-a4e4-15ad1fe8daf5.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667241349993479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment]
**Proposal**

If we need to add Vertical Scroll Bar In Manage Members We Need To Set showsVerticalScrollIndicator={true} in FlatList 


https://github.com/Expensify/App/blob/151ec1ad3355cfa162ad490030f19a7134bbc076/src/pages/workspace/WorkspaceMembersPage.js#L315

After Fix :-


https://user-images.githubusercontent.com/81307212/199288734-f8d29bd5-821b-41b7-9004-35308171c7cd.mov

**Comment by tjferriss** [comment]
Upworks job posting can be found here - https://www.upwork.com/jobs/~019e7d15837d51f5f4. 

@rushatgabhane looks like we already have a proposal above. Can you review?

**Comment by devadarsann** [comment]
Like in the Android contacts applications, instead of scroll, show alphabets there and when the users scroll through the alphabets it will act like a scrollbar.

**Comment by ahmdshrif** [comment]
I think this scrollbar should be on the web only. and it's not a good thing to add in native. 
and in this case, we can make it like this.
src/pages/workspace/WorkspaceMembersPage.js
```ts
 <FlatList
                              ...
      showsVerticalScrollIndicator={Os.platform == "Web"}
/>
```
or  if we do not prefer to use Os.platfom 

we can split the file into 2 files WorkspaceMembersPage.native.js and WorkspaceMembersPage.js
________

another way we can add scroll only if we do not have a touch screen. 

so in this case . we can use it 
```ts
import canUseTouchScreen from '../../libs/canUseTouchscreen';
...
   
   showsVerticalScrollIndicator={canUseTouchScreen()}
```

**Comment by mountiny** [comment]
Asking in slack to clarify what is the desired outcome here https://expensify.slack.com/archives/C01GTK53T8Q/p1667481625045649?thread_ts=1667241349.993479&cid=C01GTK53T8Q

I think scrollbar should be there from accessibility perspective, but I agree this looks better without it.

**Comment by tjferriss** [comment]
Bumped the Slack thread to arrive at a conclusion.

**Comment by mountiny** [comment]
@shawnborton Will assign you later, but san you please confirm the looks of list with scrollbar? I am more worried about how this looks like on Windows, but I guess we dont have to worry about this now.

**Comment by syedsaroshfarrukhdot** [comment]
@rushatgabhane Yes, we can do that by refactoring styling on WorkspaceMembersPage.js as it is due to padding=20 applied to parent view.

https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceMembersPage.js

```diff 
-                   <View style={[styles.pageWrapper, styles.flex1]}>
-                       <View style={[styles.w100, styles.flexRow]}>
+                   <View style={[styles.w100,styles.alignItemsCenter,styles.flex1]}>
+                      <View style={[styles.w100, styles.flexRow, styles.pt5, styles.ph5]}>
                            <Button
                                medium
                                success
                                text={this.props.translate('common.invite')}
                                onPress={this.inviteUser}
                            />
                            <Button
                                medium
                                danger
                                style={[styles.ml2]}
                                isDisabled={this.state.selectedEmployees.length === 0}
                                text={this.props.translate('common.remove')}
                                onPress={this.askForConfirmationToRemove}
                            />
                        </View>
                        <View style={[styles.w100, styles.mt4, styles.flex1]}>
-                            <View style={[styles.peopleRow]}>
+                            <View style={[styles.peopleRow, styles.ph5]}>
                                <View style={[styles.peopleRowCell]}>
                                    <Checkbox
                                        isChecked={this.state.selectedEmployees.length === removableMembers.length && removableMembers.length !== 0}
                                        onPress={() => this.toggleAllUsers()}
                                    />
                                </View>
                                <View style={[styles.peopleRowCell, styles.flex1]}>
                                    <Text style={[styles.textStrong, styles.ph5]}>
                                        {this.props.translate('workspace.people.selectAll')}
                                    </Text>
                                </View>
                            </View>
                            <FlatList
                                renderItem={this.renderItem}
                                data={data}
                                keyExtractor={item => item.login}
-                               showsVerticalScrollIndicator={false}
+                              showsVerticalScrollIndicator
+                              style={[styles.ph5,styles.pb5]}
                            />
                        </View>
```

After Fixing :- 


https://user-images.githubusercontent.com/81307212/200558675-6543d14e-5ddd-48ab-b93e-fe616efe8544.mov

**Comment by mountiny** [comment]
@rushatgabhane @syedsaroshfarrukhdot Would these design changes influence the design on mobile devices? can you show screen of that as well so @shawnborton can confirm this looks fine? Thank you!

**Comment by syedsaroshfarrukhdot** [comment]
@mountiny No, they don't influence design on mobile devices. It look same across the board.

Desktop:- 

https://user-images.githubusercontent.com/81307212/200606043-01dc185c-e251-4e1f-ba8f-185fd9b5a9be.mov


Web:-

https://user-images.githubusercontent.com/81307212/200606101-1aa4960c-35c4-4590-b539-afadc84349ad.mov

IOS:-

https://user-images.githubusercontent.com/81307212/200606156-3363de63-cf0c-47e9-baf3-daf2c4120a72.mov

mWEB Safari :-

https://user-images.githubusercontent.com/81307212/200606222-ec8aff92-38bf-478f-adea-89920096d2fa.mov

mWeb Chrome :- 


https://user-images.githubusercontent.com/81307212/200606341-bc87af33-2577-4eb7-a0d7-b94d5ebeeaf5.mov

**Comment by mountiny** [comment]
I will go ahead and assign you @syedsaroshfarrukhdot. I think your solution does the job. Can you please raise the PR so we can test and see all how this change influences other designs.

**Comment by syedsaroshfarrukhdot** [comment]
@mountiny Thanks for assigning. Applied on Upwork. Will be raising a PR in next few minutes.

**Comment by mountiny** [comment]
@syedsaroshfarrukhdot I am sorry but in this case I will have to accept I made a mistake and overlooked the similarities. Given @0xmiroslav has proposed solution which is very similar earlier, I think they should be assigned.

Apologies for the confusion, I have overlooked this.

@syedsaroshfarrukhdot I appreciate your help and sharing the videos and screenshots

**Comment by syedsaroshfarrukhdot** [comment]
> @syedsaroshfarrukhdot I am sorry but in this case I will have to accept I made a mistake and overlooked the similarities. Given @0xmiroslav has proposed solution which is very similar earlier, I think they should be assigned.
> 
> Apologies for the confusion, I have overlooked this.
> 
> @syedsaroshfarrukhdot I appreciate your help and sharing the videos and screenshots

@mountiny  Fundamentally both proposals are quite different from  eachother @0xmiroslav is moving FlatList out of parent view whereas my proposal keeps the FlatList in the View and it fixes the issue. The difference b/w my proposal and @0xmirosla is quite significant. 

Before:-
![Screen Shot 2022-11-08 at 9 35 43 PM](https://user-images.githubusercontent.com/81307212/200623674-6e2df266-337d-4b74-8193-53736bb3402d.png)

After My Fix :-
![Screen Shot 2022-11-08 at 9 35 21 PM](https://user-images.githubusercontent.com/81307212/200623722-32e2bf76-f8ee-496c-a413-e8c5e7da1550.png)

After @0xmiroslav  Fix:-
![Screen Shot 2022-11-08 at 9 37 15 PM](https://user-images.githubusercontent.com/81307212/200624070-4079fc04-7a56-4918-ae6b-14a43a415200.png)

The Options view is cut in his proposal

@mountiny  Please could you review both proposals and compare their differences and then assign the job to any of us ?

**Comment by mountiny** [comment]
@syedsaroshfarrukhdot Sorry but the proposals are very similar.

I have compared them even before and the only visual difference comes down to the padding at the bottom. The border line will most likely get cut off in you proposal to it just depends on how the row is aligned.

Hence that is the only design difference, I will defer to @shawnborton decision about the padding. It is not specified in the issue body, I dont mind it being removed.

@0xmiroslav Can you please wait a bit before we decide this so this does not feel fair to anyone, thanks.

**Comment by shawnborton** [comment]
I think I would just add a standard 20px padding to the very bottom of the list view so that the very last item always comes up fully into view.

**Comment by shawnborton** [comment]
So basically, this one looks correct to me: 
![image](https://user-images.githubusercontent.com/2319350/200636068-0a0bdcad-00cb-400b-94d5-63ece1f71900.png)

Though we probably could _slightly_ reduce the padding under the fixed Select All row.

**Comment by mountiny** [comment]
Great thanks! @syedsaroshfarrukhdot Please make sure you can also add the padding so the Select all is not so close to the list content.

thank you!

**Comment by shawnborton** [comment]
@syedsaroshfarrukhdot make sure to tag me in your PR for design review too, thanks!

**Comment by syedsaroshfarrukhdot** [comment]
@mountiny Sure will take care of it. Thanks

@shawnborton Sure, will be tagging you as well in the PR. 😃

**Comment by shawnborton** [comment]
Yes, I agree with that last video.

**Comment by syedsaroshfarrukhdot** [comment]
Bump For Payment

**Comment by mountiny** [comment]
@tjferriss bumping this one for payment to the contributors 🙌

**Comment by tjferriss** [comment]
@rushatgabhane @syedsaroshfarrukhdot sorry for the delay. Can you please accept the offer in Upworks and comment here when you do? Then I'll process the payment.

**Comment by syedsaroshfarrukhdot** [comment]
@tjferriss Offer Accepted on Upwork. I believe as this PR was merged within 3 business days. I am also eligible for 50% bonus here. 🎉

**Comment by syedsaroshfarrukhdot** [comment]
@tjferriss bumping for payment

**Comment by mountiny** [comment]
sorry, asking internally, lots of people are out for Thanksgiving

**Comment by NicMendonca** [comment]
@syedsaroshfarrukhdot @rushatgabhane paid! (keeping this open for the rest of the checklist)

**Comment by syedsaroshfarrukhdot** [comment]
@NicMendonca Thanks received payment. I am also eligible for 50% bonus here as my PR was merged in 3 business days. Not received bonus yet.

**Comment by syedsaroshfarrukhdot** [comment]
Bumping for bonus.

**Comment by dylanexpensify** [comment]
Will sort this now!

**Comment by dylanexpensify** [comment]
@syedsaroshfarrukhdot sent bonus payment!

**Comment by syedsaroshfarrukhdot** [comment]
> @syedsaroshfarrukhdot sent bonus payment!

Thanks Received

**Comment by mountiny** [comment]
Wohhooo, thank you very much guys!

**Comment by tjferriss** [comment]
@NicMendonca and @dylanexpensify thank you for the assist on processing payment :)
