### ISSUE TITLE
Tracking issue to pay C+ for internal PR reviews (before updated process)

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#12354]
I need to pay C+ for reviewing internal PRs, will use this GH for tracking.  Main spreadsheet is [here](https://docs.google.com/spreadsheets/d/1GSOIuYXcDePpJpEi_ci5vqv_WGgQ7Ttb6_onuBtCI0U/edit?usp=sharing)

@mananjadhav 
- 3 jobs - total $1000 
- Upwork Job

@Santhosh-Sellavel 
- 4 jobs - $1000
- Upwork Job

@sobitneupane 
- 2 jobs - $500
- Upwork Job

**Comment by mallenexpensify** [comment]
@mananjadhav @Santhosh-Sellavel @sobitneupane 
Will you please except the Upwork job then I'll pay? I set it at $250, will bonus the difference to equal the amounts in the OP that came from the sheet.  Updating the sheet too
https://www.upwork.com/jobs/~0151f7ed511c47bbc0

Also updating[ the Slack thread ](https://expensify.slack.com/archives/C02NK2DQWUX/p1667333777293729?thread_ts=1665685158.152769&cid=C02NK2DQWUX)about the payments.

**Comment by bluesky0724** [comment]
Hello Matt.
I saw the job posting in upwork.
I am interested in this opportunity.

**Comment by bluesky0724** [comment]
I just left my previous company.
I worked as a backend developer and I worked closely with QA team.
I reviewed PR from others as well as writing code.
I am sure that I could excel in this project.

**Comment by Santhosh-Sellavel** [comment]
@bluesky0724 
Please check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!

Please read the above guidelines to understand our process. 

Also to get started check our [readme ](https://github.com/Expensify/App#readme) to set up and know more about our app repo, code practices, etc.

When you are ready we have a lot of open jobs [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mananjadhav** [comment]
Done @mallenexpensify

**Comment by mallenexpensify** [comment]
Thanks for the promptly accepting the proposals. All paid the amounts in the OP!
