### ISSUE TITLE
[HOLD] [$250] IOS - Settings - Changes displayed after closing and reopen app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12125 

## Action Performed:
1. Launch the app
2. Log in any account
3. Navigate to Settings > Profile
4. Disable the internet connection in the device
5. Modify first name, last name, and your timezone
6. Save and verify everything looks like it updated correctly
7. Click back button to go back to settings page
8. Click profile and verify changes are preserved
9. Click back button to go back to settings page again
10. Go back online
11. Click on the Profile and check

## Expected Result:
Changes should be displayed after go back online.

## Actual Result:
Changes displayed after closing and reopen app

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.22.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199348959-5a756591-438c-48b3-8b32-e51c69b29b1d.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment]
Internal link - https://www.upwork.com/ab/applicants/1589978535629422592/job-details
External link - https://www.upwork.com/jobs/~0189d0bc78f110af85

**Comment by mountiny** [comment]
Putting this on Hold as I tihnk there is already issue for the settings not being saved correctly

**Comment by mountiny** [comment]
This is indeed just a regression from https://github.com/Expensify/App/issues/11632

**Comment by mountiny** [comment]
I will close this one in favour of the original https://github.com/Expensify/App/issues/11632!

**Comment by jasperhuangg** [comment]
Tried the reproduction steps on dev and it appears to be working, so this might be fixed with the next App deploy, stay tuned..


https://user-images.githubusercontent.com/31285285/200623848-368f34e2-508a-451e-af2e-8eaad8a327ad.mov

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mountiny** [comment]
Also wasnt able to repro on the latest Staging iOS. @jasperhuangg seems like caught it right.

**Comment by mountiny** [comment]
We have not been able to reproduce this issue in staging and production anymore. The values save correctly, although in some testing tries the old values flickers/appears temporarily in the product before the correct saved values settle.

This is most likely related to order of the read/write requests which go to the server once we get online https://github.com/Expensify/App/pull/12219

**Comment by flaviadefaria** [comment]
Closed the UW post!
