### ISSUE TITLE
[Hold WAQ #239140] Implement Custom Avatar Picker

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12362]
Note: This issue is part of the greater [Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140) project.

**What is it:**
Let's add the ability for users to choose their own avatar + color. We'll wait until after WAQ to implement this one. 

![image](https://user-images.githubusercontent.com/2319350/199370627-75c518b7-38d5-4e64-8e74-eb5d66b09023.png)

**Does it require a mini design doc:**
Yes

**Design finished:**
Yes

cc @GabiHExpensify

**Comment by shawnborton** [comment]
Still holding this one

**Comment by shawnborton** [comment]
Still holding

**Comment by shawnborton** [comment]
Not overdue

**Comment by shawnborton** [comment]
Yup - we have some updated mocks and expected behavior after some internal discussion @zanyrenney are we good to share new screenshots here?

**Comment by vladamx** [comment]
Any news here?

**Comment by shawnborton** [comment]
Not overdue

@zanyrenney thoughts on my comment above?

**Comment by vladamx** [comment]
Bump @zanyrenney

**Comment by shawnborton** [comment]
Hey @zanyrenney curious what you think about this one now that the waves reshuffled some things. Thanks!

**Comment by zanyrenney** [comment]
Hey! sorry I didn't get these pings as I wasn't assigned to the issue and my workflow is to use my K2! Looking now.

**Comment by zanyrenney** [comment]
I think we can close this out and tackle the updates to the avatars as part of onboarding. As you mention @shawnborton - the design is different from this one above and I think the Onboarding design, currently in re-review - detailed draft is the most up to date agreed design. (From #N7 to #Product discussions).

**Comment by shawnborton** [comment]
Cool, that works for me!
