### ISSUE TITLE
Web- New Room - Changes made offline on another device are displayed there only after refreshing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Sign in with any Expensifail account
3. Create a workspace from the green plus (if needed)
4. Create a workspace room from the green plus (if needed)
5. Go offline
6. Click the header of the workspace room to open the room details page
7. Click "Settings"
8. Rename the room and hit save
9. Verify that the input is grayed out
10. Sign into the same account on another device or incognito window
11. Open the workspace room and click the header of the workspace room to open the room details page
12. Click "Settings"
13. Rename the room and hit save
14. Go back to the other device and go back online
15. Confirm the name is changed and no errors are shown

## Expected Result:
The name should be changed on two devices

## Actual Result:
Changes made offline on another device are displayed there only after refreshing

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.22.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199514143-8a1be0e0-f3ad-4059-bf58-ba5af56ad1fe.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Oh haha that's an interesting case. Weird that we update both devices once offline mode is disabled. I would expect the most recent change to take precedence even when made in offline mode.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by nkuoch** [comment]
Closing then. Let's reopen if it occurs again.
