### ISSUE TITLE
Clicking on link on "October statement"opens the app in web instead of opening it within the current app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Go to Concierge chat
3. Click on "October 2022 expensify statement"

## Expected Result:
Opens within the app

## Actual Result:
Opens in web

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.22-1

**Reproducible in staging?:** Need reproduction

**Reproducible in production?:** Need reproduction

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/43996225/199565530-293f39e0-b33b-4234-b375-0fd08289eaa4.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @puneetlath 

**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667333672813869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
I believe this issue will also be taken care of by https://github.com/Expensify/Expensify/issues/234459

**Comment by puneetlath** [comment]
Ah cool. Let's close this then. Thanks y'all.
