### ISSUE TITLE
Reporting bonus for @puneet-here

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#12394]
Coming from this #expensify-open-source slack https://expensify.slack.com/archives/C01GTK53T8Q/p1665759644497429
and... internal discussion here https://expensify.slack.com/archives/C02NK2DQWUX/p1666111162201699?thread_ts=1665598030.501879&cid=C02NK2DQWUX

@Puneet-here is due $250 so creating this GH!

**Comment by mallenexpensify** [comment]
@Puneet-here , please accept the job and add a comment here once you have
https://www.upwork.com/jobs/~01a1b7d8d6592b2d9c

**Comment by Puneet-here** [comment]
I have accepted the offer. Thanks!

**Comment by mallenexpensify** [comment]
Paid!  Thanks for reporting bugs and for all the other help.
