### ISSUE TITLE
Failed workflow comments in slack do not have the correct URL

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have a failed GitHub Actions workflow ping in Slack.
1. Click on the link to the failed workflow.

## Expected Result:
You should be taken to the failed workflow.

## Actual Result:
You are taken to the GitHub Actions dashboard and have to look for the failed workflow manually.

## Workaround:
n/a

## Platform:
GitHub Actions

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Since this is internal, I'm going to remove @conorpendergrast as an assignee.

**Comment by roryabraham** [comment]
Screw you melvin, this should be a weekly, at best.

**Comment by mallenexpensify** [comment]
@roryabraham , we're wanting BZ assigned for internal bugs and for them to remain daily, does the OP have everything needed to be worked on? Also.. I'm double checking here on the exact process [here ](https://expensify.slack.com/archives/C01SKUP7QR0/p1667662020687219?thread_ts=1667064948.124109&cid=C01SKUP7QR0)for engineers.

**Comment by conorpendergrast** [comment]
@roryabraham Second bump!

**Comment by roryabraham** [comment]
The OP does indeed have everything it needs to be worked on imo

**Comment by conorpendergrast** [comment]
Ok, great! So now we just... leave ourselves assigned, and this set to Daily, until.. what?

**Comment by roryabraham** [comment]
Created a PR against the upstream actions/slack repo to add a feature to make this more convenient: https://github.com/8398a7/action-slack/pull/230

**Comment by roryabraham** [comment]
Also so we don't have to wait around with this issue open, I created a workaround that _should_ fix this in our repo: https://github.com/Expensify/App/pull/12873. That way we don't have to deal with a fork or wait for the maintainer to review + release my new feature in the upstream. I will get notified if my PR is merged and then I can pretty easily do a follow-up to use the upstream feature, if we even want to. The fix in our repo might be fine

**Comment by roryabraham** [comment]
> So now we just... leave ourselves assigned, and this set to Daily, until.. what?

Sass noted btw, @conorpendergrast 😆

**Comment by conorpendergrast** [comment]
Hah, sorry - genuinely not sass, just total confusion


Conor Pendergrast
Concierge Team, Expensify

**Comment by roryabraham** [comment]
My [upstream fix](https://github.com/8398a7/action-slack/pull/230) was merged over the weekend. I'll keep this open for now to switch from the workaround to the upstream fix.

**Comment by roryabraham** [comment]
Final cleanup PR ready for review: https://github.com/Expensify/App/pull/13121
