### ISSUE TITLE
Clicking "fix the errors" on Company information page does not set focus on the first error field reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions performed:

1. Go to Profile > Workspace > Connect a bank account > Connect manually
2. Enter a valid routing number and account number
3. Click save & continue
4. On Company information page, click save & continue without filling in any field
5. Click on "fix the errors"

## Expected Result:
Scrolls to the first error field and sets focus on it

## Actual Result:
Scrolls to the first field but does not set focus on it

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.23-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/199803438-341e7cd6-1367-45c4-9ffa-5073b01e0d77.mov

https://user-images.githubusercontent.com/43996225/199803495-31088511-25e1-46ae-9739-b71154d72b4e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667484994623239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
hey @kavimuru - i'm unsure how this is an actual bug. will you elaborate on "not setting focus on it" and how that is buggy behavior? 

i appreciate it!

**Comment by varshamb** [comment]
### Proposal

We need to use `onFixTheErrorsLinkPressed` instead of 
`onFixTheErrorsPressed`

I will update detailed proposal in some time.

**Comment by maddylewis** [comment]
thanks for those details @0xmiroslav. 

>Or just close this one and thoroughly test on https://github.com/Expensify/App/pull/10741.

based on this suggestion, I'm going to close this one out for now. 👍
