### ISSUE TITLE
mWeb/Safari -Change password - Cursor does not autofocus Change password page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12439]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Navigate to settings by clicking on the user avatar over LHN
3. Click on Security > Change password

## Expected Result:
The cursor must be present in section Change password

## Actual Result:
Cursor is not autofocused  in section Change password

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - iOS Safari

**Version Number:** 1.2.23-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/199808618-27b80060-f0af-4ca2-899a-bb5b6cc93d93.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aneequeahmad** [comment]
This one is already a known issue for IOS safari and has been discussed before and i guess decided not to do anything about it or remove focus on mWeb. 

cc: @parasharrajat

**Comment by parasharrajat** [comment]
Correct both of you. @kavimuru Could you please mention this issue on https://github.com/Expensify/App/issues/10414 and close this one. Thanks.

**Comment by kavimuru** [comment]
Closing this issue as this can be linked with #10414
