### ISSUE TITLE
Hitting "cmd +R" when an attachment was taking longer to upload, multiple attachments are loading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login
2. Open any chat
3. Upload an attachment with bigger size
4. When uploading takes longer and stays in "uploading attachment " hit "Cmd+R"

## Expected Result:
Either should still show "uploading attachment" or once it gets uploaded.

## Actual Result:
Multiple times images are being uploaded message appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.21-4
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="693" alt="Screen Shot 2022-11-02 at 11 32 31 AM (1)" src="https://user-images.githubusercontent.com/43996225/199764418-d75ba72d-b7ea-4d97-9af3-177def6f321f.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667414010939499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Will review today

**Comment by greg-schroeder** [comment]
I haven't been able to reproduce this 🤔 I tried uploading an attachment just under the 24mb size limit and refreshing the desktop app didn't cause the repetition shown in the screenshot in the OP

**Comment by JmillsExpensify** [comment]
Agreed, this is linked to sequence numbers. Taking it over as part of the tracking issue.

**Comment by JmillsExpensify** [comment]
Still on hold for sequence numbers.

**Comment by JmillsExpensify** [comment]
On hold for sequence numbers, though that initiative is hopefully wrapping up before EOY.

**Comment by JmillsExpensify** [comment]
Still on hold for sequence numbers.

**Comment by JmillsExpensify** [comment]
Hold means hold Melvin.

**Comment by JmillsExpensify** [comment]
Still on hold for sequence numbers.

**Comment by JmillsExpensify** [comment]
Removed the hold and re-running through the testing steps.

**Comment by JmillsExpensify** [comment]
No longer an issue! Works like a charm now that sequence numbers are deprecated. Adding the reproduction label and closing.
