### ISSUE TITLE
[HOLD for payment 2022-11-22] [$250] App crashes when try to open workspace manage members page after login from deeplink url reported by @0xmiroslav 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to any account
2. Go to Settings -> Workspaces -> select any workspace -> Manage members page
3. Copy url link
4. Logout
5. Visit copied url link
6. Login to same account

## Expected Result:
Manage members page shows

## Actual Result:
App crashes

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.23-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199802418-d4749c1b-f8b8-4a1a-9606-82a82923fe34.mp4

https://user-images.githubusercontent.com/43996225/199802451-bb84f9ca-7fa8-48cd-aa53-8bce55e0709f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667468386668709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
👍 reproducible 

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/24947345/199852592-ef635174-acad-47e9-a616-24acca2d8655.png">

**Comment by NicMendonca** [comment]
Job posting: https://www.upwork.com/jobs/~01449e67e1aa0a0f9d

**Comment by tienifr** [comment]
# Proposal

## Problem

In https://github.com/Expensify/App/blob/533e63ce8b13e573024784836cef0bb7e859e937/src/pages/workspace/WorkspaceMembersPage.js#L294
we get the `details` from `personalDetails`, but when we visit this page directly after login, `personalDetails` is undefined (response from service has not been returned yet)

## Solution
We need to check `personalDetails` is undefined. if yes we'll fallback to using the default default value

```diff
-            const details = this.props.personalDetails[email] || {displayName: email, login: email, avatar: Expensicons.FallbackAvatar};
+            const details = (this.props.personalDetails && this.props.personalDetails[email]) || {displayName: email, login: email, avatar: Expensicons.FallbackAvatar};
```

https://user-images.githubusercontent.com/113963320/199895066-4a4f1e60-a3ed-4824-a573-480d137c8fef.mp4

**Comment by thesahindia** [comment]
Thanks for looking into it @tienifr. Proposal looks good but can you please share an updated proposal using `lodashGet`

**Comment by thesahindia** [comment]
`FullPageNotFoundView` can be seen at other pages too.
If you follow the steps below can see this at workspace initial page
Steps:- 
1.Go to settings
2. Go to to workspaces > open a workspace
3. Copy the URL
4. Sign out > paste the URL and press enter
5. Now login

 I don't think displaying the loading indicator at only workspace members page will do any good.

@NikkiWines, should we deal with this issue here?

**Comment by tienifr** [comment]
# Updated proposal
## Solution
We need to check personalDetails is undefined. if yes we'll fallback to using the default default value

```diff
-            const details = this.props.personalDetails[email] || {displayName: email, login: email, avatar: Expensicons.FallbackAvatar};
+            const details = lodashGet(this.props.personalDetails, 'email') || {displayName: email, login: email, avatar: Expensicons.FallbackAvatar};
```

**Comment by tienifr** [comment]
@thesahindia Thank for your review, I updated my proposal above.

**Comment by NicMendonca** [comment]
@thesahindia bump on reviewing @tienifr's updated proposal ☝️ thanks!

**Comment by thesahindia** [comment]
I am waiting for @NikkiWines thoughts at https://github.com/Expensify/App/issues/12435#issuecomment-1304359257

**Comment by NikkiWines** [comment]
Sorry for the delay @thesahindia, I've been OOO. 

> I don't think displaying the loading indicator at only workspace members page will do any good.
> @NikkiWines, should we deal with this issue here?

While both are definitely problems, I think we should handle them in separate issues. The app crashing issue is specific to the workspace members page, but the momentary "Hmmm...it's not here"  issue is a problem for all workspace pages. 

In which case, the expectation for the correct behavior for this issue would be that the "Hmm... it's not there" page shows briefly before the manage members page loads as expected.

**Comment by thesahindia** [comment]
Posted the other issue on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1667978507958729). 
Let's fix the crash.

@tienifr, you aren't using the `lodashGet` correctly.

**Comment by thesahindia** [comment]
@NikkiWines, let's assign @tienifr since they proposed a working [solution](https://github.com/Expensify/App/issues/12435#issuecomment-1302982422) we just need to use `lodashGet`

C+ reviewed 🎀👀🎀

**Comment by tienifr** [comment]
@thesahindia You're right, change to use `lodashGet` like: 
`const details = lodashGet(this.props.personalDetails, email, {displayName: email, login: email, avatar: Expensicons.FallbackAvatar});` is the best solution. Thanks

**Comment by thesahindia** [comment]
Umm, my bad. I didn't look at the console. 

@NikkiWines, let's assign @0xmiroslav ? As their [proposal](https://github.com/Expensify/App/issues/12435#issuecomment-1308389932) will also fix console errors.

C+ reviewed 🎀👀🎀

**Comment by NikkiWines** [comment]
Yep, sounds good. Agreed we want to fix console errors. @NicMendonca can you hire @0xmiroslav for this role, please? Thanks!

**Comment by NicMendonca** [comment]
@0xmiroslav please apply for the job [here ](https://www.upwork.com/jobs/~01449e67e1aa0a0f9d)

**Comment by michaelhaxhiu** [comment]
Can we make sure to always hire the Contributor on the GH itself next time @NicMendonca ?

**Comment by michaelhaxhiu** [comment]
This is due for payment on Nov 22, but we need to address the BZ checklist. Sorry I didn't have time to get to it before going OOO.

**Comment by MitchExpensify** [comment]
[Asked in #bug-zero about the placement for the regression test](https://expensify.slack.com/archives/C01SKUP7QR0/p1668816600353089)

**Comment by MitchExpensify** [comment]
Invites sent to the [New Upwork job](https://www.upwork.com/jobs/~01d72e2380c0fbfcf2) as the old one expired.

**Comment by MitchExpensify** [comment]
Yep! Had that noted, reminders never hurt though!

**Comment by thesahindia** [comment]
@MitchExpensify, I didn't get the 50% bonus. It also applies to the C+ reviewer

**Comment by MitchExpensify** [comment]
Fixed and paid 50% bonus for both now, thanks!
