### ISSUE TITLE
[HOLD for payment 2022-12-07] Update New Dot Colors

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#12440]
Tracking Issue: https://github.com/Expensify/App/issues/12251
Design Doc Section: https://docs.google.com/document/d/197fXHLlHM_RJA4-3MITwdu0N5e0HX5Q74sA4W80YMD8/edit#bookmark=id.zh5fku1wwmp2

### Color Swaps

Here’s a list of color values that will change:
App Background: #FFFFFF → #061B09
Highlight Background: #FAFAFA → #002E22
Borders: #ECECEC → #1B5744
Icons: #C6C9CA → #8B9C8F
Supporting Text: #7D8B8F → #C9D3C5
Text: ##0B1B34 → #FFFFFF
Danger (Red): #FC3826 → #FC3826
Default Button Text: #0B1B34 → #FFFFFF
Danger Button BG: #FC3826 → #FC3826
Link Color: #0185FF → #8DC8FF

All of these colors are currently stored in a file called [colors.js](https://github.com/Expensify/App/blob/main/src/styles/colors.js). Each of the current values in that file will be switched according to the scheme above.

### Ghost UI

We also need to change the colors on the loading Ghost UI. 
![Screen Shot 2022-11-03 at 12 05 25 PM](https://user-images.githubusercontent.com/49007721/199811859-80f2f4ae-99fb-4147-8cdb-d42d0d23609d.png)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103cf97848a39b3c9</li>
        <li>Upwork Job ID: 1606463587928702976</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by Luke9389** [comment]
Sorry for the noise @Christinadobrzyn, this is not a Bug :)

**Comment by shawnborton** [comment]
Hey @grgia for link color, let's try bumping them up just a shade darker. So that goes us:

Link: #5AB0FF
Link Hover: #8DC8FF

**Comment by shawnborton** [comment]
How is progress going on this one? Can you provide an update @grgia @Luke9389? Thanks!

**Comment by grgia** [comment]
The colors are pretty much done right now, I'll likely need to merge main and do some final tweaking when everything is ready and we decide to merge in all the core branding.

**Comment by shawnborton** [comment]
Sounds great. Do you have an ETA for when you'll be done with the final tweaking?

**Comment by grgia** [comment]
It can be done today if needed!

**Comment by shawnborton** [comment]
Sounds good. Maybe we can shoot to have everything merged early next week, like on Monday? That would give us the rest of the week to wrap things up, cc @Luke9389 

I'll post a weekly update today and we can discuss these things further though.

**Comment by grgia** [comment]
Are we good to close this out?

**Comment by shawnborton** [comment]
Yeah, I think we're in a good spot now with colors. Thanks for all of the work getting these changes implemented, the app looks great ✨

**Comment by shawnborton** [comment]
Err actually, just want to cn

**Comment by mallenexpensify** [comment]
@parasharrajat , I believe you're do $1000, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0103cf97848a39b3c9

**Comment by mallenexpensify** [comment]
Paid @parasharrajat $1000, thanks. 
Closing
