### ISSUE TITLE
[HOLD for payment 2022-12-15] Update New Dot Fonts

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#12443]
Tracking Issue: https://github.com/Expensify/App/issues/12251
Design Doc Section: https://docs.google.com/document/d/197fXHLlHM_RJA4-3MITwdu0N5e0HX5Q74sA4W80YMD8/edit#bookmark=id.h4aw0750hafm

### Update Fonts

Adding fonts to a React Native project requires a few steps for each platform, which are spelled out [here](https://stackoverflow.com/c/expensify/questions/6831).

Body Font
Our new body font will be Expensify Neue. We only need four weights: Regular, Regular Italic, Bold, and Bold Italic

Monospaced Font
Our new monospaced font (used for code blocks and inline code) will be Expensify Mono. We only need two weights: Regular and Bold. 

Headline Font
Our new headline font is Expensify New Kansas. We only need two weights: Medium and Medium Italic. We currently do not have a separate headline font in the NewDot repo, so this will be a new addition.

**Comment by Luke9389** [comment]
Hey @shawnborton, I fiddled around in Figma for a while to see if I could get the font files out of it, but alas, I could not. 

Would you be willing to provide them here?

**Comment by shawnborton** [comment]
Can you let me know the exact font files we're currently using? I think I see that Android and iOS need `.otf` font files - is that right? For web/desktop/mWeb, I am guessing we need .woff files or something like that?

**Comment by shawnborton** [comment]
In the meantime, here are the files. You'll have to grab the exact ones you need from these folders, but I think it should be self-explanatory. 

Expensify Mono: https://www.dropbox.com/sh/yp1s3pdnbwak5mc/AABLu3m4Fw0MZhctS5DS1w01a?dl=0
Expensify Neue: https://www.dropbox.com/sh/ek37aaosgsh84oh/AACBRBNB7Fk2Gngn8C6EhuGba?dl=0
Expensify New Kansas (note: only .otf files are there currently, waiting to get the other types): https://www.dropbox.com/sh/lkz4saovcora67e/AAAWmQPqIYHPBH8-pPp_hF0Za?dl=0

**Comment by Luke9389** [comment]
That first PR was to add the fonts as assets. Now I'll begin switching them out.

**Comment by Luke9389** [comment]
I'm realizing that we do indeed need the New Kansas .eot files.

**Comment by Luke9389** [comment]
Holding. Reason in above comments

**Comment by shawnborton** [comment]
Yup, still waiting to get the final formats for New Kansas once we sign the EULAs and pay final licensing. Will keep you posted!

**Comment by shawnborton** [comment]
If it's a pain, we could always follow up with New Kansas in a different PR?

**Comment by shawnborton** [comment]
@Luke9389 thinking more on this, I think we can probably follow up with a separate PR for New Kansas. Thoughts on that?

**Comment by Luke9389** [comment]
I think that'd be fine!   The Help Site should probably hold til all 3 are done since its external. Do you agree?

**Comment by shawnborton** [comment]
I think it would be fine if the help site uses Expensify Neue for headlines for the time being.

**Comment by Luke9389** [comment]
OK one other thing is that the new "logo" of expensify help looks like this:

<img width="232" alt="Screen Shot 2022-11-09 at 5 24 47 PM" src="https://user-images.githubusercontent.com/49007721/200977601-604ccff3-8bdf-424a-b37b-0ab8579c325b.png">


If you made an svg out of that, I could use it, or I could have that "Help" part be in Expensify Neue as well.

**Comment by Luke9389** [comment]
I'm just realizing that I think I'll need `.eot` files for Expensify Mono and Expensify Neue as well.

**Comment by shawnborton** [comment]
I think I already added the new help site logo to the Help Site issue. 

Curious why you need .eot files? It's pretty standard to just use woff files for web/mWeb.

**Comment by Luke9389** [comment]
> I think I already added the new help site logo to the Help Site issue.

Oh sick! Sorry bout missing that. I see those now. 

> Curious why you need .eot files? It's pretty standard to just use woff files for web/mWeb.

Honestly, I don't really know anything about font file types n' stuff. 

But I do see that we have [an .eot reference for every font in the app](https://github.com/Expensify/App/blob/main/assets/css/fonts.css#L8). Idk, if we need these exactly, but I'm assuming we do bc they're there. I dunno.

You know more about this than me so lmk what you think.

One thing is that this code isn't just for web and mWeb, it's compiling to iOS and Android.

**Comment by shawnborton** [comment]
I think Android and iOS end up using .otf font files, so we should be good there. 

Then for web/mWeb, yeah - let's try to only use woff files and see what happens.

**Comment by Luke9389** [comment]
Ok I just did some reading and it looks like `.eot` is really only supported/used in Internet Explorer.

I know you're OOO, and we can just add them later. For now I'll continue w the PR.

**Comment by shawnborton** [comment]
Could we please try just implementing the woff files? I think it's pretty standard practice to only use these file types for serving up web/mWeb fonts.

**Comment by Luke9389** [comment]
Still working on this one.

**Comment by roryabraham** [comment]
@Luke9389 I was working on a [related issue](https://github.com/Expensify/App/issues/12267) and came up with a draft PR which hosts the fonts on NewDot. It uses `.otf` fonts for iOS/Android also preloads the `.woff2`/`.woff` fonts on web/Desktop.

**Comment by shawnborton** [comment]
@roryabraham that sounds great. Hopefully we can have this font PR merged ASAP.

**Comment by roryabraham** [comment]
If anyone wants to do further testing, add screenshots, etc... while I'm OOO feel free. Otherwise I'll pick this back up on Monday

**Comment by Luke9389** [comment]
This one should be getting merged very soon (hopefully today)

**Comment by Luke9389** [comment]
Looks like there was a problem with the fonts on android. @grgia is looking into it and may include the fix on her PR [here](https://github.com/Expensify/App/pull/13415).

**Comment by Luke9389** [comment]
Idk why this one says `Awaiting Payment`. Closing now.

**Comment by sobitneupane** [comment]
@Luke9389 @grgia I am C+ in the [PR](https://github.com/Expensify/App/pull/12656). Can you please help me with the payment.

**Comment by Luke9389** [comment]
Sorry about that @sobitneupane, I'll get a CM assigned right now.

**Comment by Luke9389** [comment]
Hey, @jliexpensify, would you be willing to pay @sobitneupane above? Looks like there was never a CM for this one.

**Comment by jliexpensify** [comment]
@sobitneupane - invited you. Once you accept, I can get the $1000 payment sorted :)

**Comment by sobitneupane** [comment]
@jliexpensify Thanks. Submitted proposal.

**Comment by jliexpensify** [comment]
Paid and job closed!

**Comment by Luke9389** [comment]
Thanks @jliexpensify!
