### ISSUE TITLE
Update ExpensifyHelp to Match New Dot Styles

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#12446]
Tracking Issue: https://github.com/Expensify/App/issues/12251
Design Doc Section: https://docs.google.com/document/d/197fXHLlHM_RJA4-3MITwdu0N5e0HX5Q74sA4W80YMD8/edit#bookmark=id.wectpruo06vv

### Update ExpensifyHelp

We also need to update the styles on the ExpensifyHelp site. All of the code for this site is in the App/docs/ directory. It has its own style sheets in App/docs/_sass/, which need to be replaced. We can’t use the same styles that we use in the App because ExpensifyHelp is not made with React Native. It’s just a web page, so we opted to use vanilla JS. This means that the scss files for ExpensifyHelp use actual css syntax, where the styles.js file used in App uses json.

![Screen Shot 2022-11-03 at 12 36 05 PM](https://user-images.githubusercontent.com/49007721/199817684-d4f9fb03-be1a-4a2b-bb93-e53d7426b976.png)

**Comment by roryabraham** [comment]
Also might need to update `App/docs/assets/images` with the new image assets 🙂

**Comment by Luke9389** [comment]
workin on this one this week. PR is pretty much there, just held on some font PRs.

**Comment by Luke9389** [comment]
Still prioritizing the other PRs over this one right now.

**Comment by Luke9389** [comment]
Going to be working on this one today. It looks like there's an unresolved issue with the new fonts on android, so it's possible the same fix will need to be applied here once it's found.

**Comment by Luke9389** [comment]
Finally resolved the jekyll error I was experiencing. I'll commit the fix w this PR.
