### ISSUE TITLE
[HOLD for payment 2022-12-02] Update New Dot Buttons

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#12444]
Tracking Issue: https://github.com/Expensify/App/issues/12251
Design Doc Section: https://docs.google.com/document/d/197fXHLlHM_RJA4-3MITwdu0N5e0HX5Q74sA4W80YMD8/edit#bookmark=id.bolh6znlwq1x

### Update Buttons

Our buttons will become pill shapes instead of the rounded-corner boxes we have now. This can be achieved by setting the correct border radius for buttons in styles.js. Note that we have a few standard sizes for buttons, each with their own style, so this change will involve changing all of those styles. We’ll also need to increase the horizontal padding of the buttons to accommodate the fully rounded corners. 

![Screen Shot 2022-11-03 at 12 22 22 PM](https://user-images.githubusercontent.com/49007721/199815112-afd02408-e0ab-4cf5-9d3e-5c37d1278765.png)

**Comment by grgia** [comment]
Not overdue, adding reviewing label

**Comment by Luke9389** [comment]
This issue is complete.
