### ISSUE TITLE
[$1000] [HOLD for payment 2022-12-08] Update New Dot Icons

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#12442]
Tracking Issue: https://github.com/Expensify/App/issues/12251
Design Doc Section: https://docs.google.com/document/d/197fXHLlHM_RJA4-3MITwdu0N5e0HX5Q74sA4W80YMD8/edit#bookmark=id.og7olthv53yu

### Update Icons

All of the icons from `./assets/images/ will be replaced with the following icons. 
![Screen Shot 2022-11-03 at 12 15 17 PM](https://user-images.githubusercontent.com/49007721/199813725-0b525f14-2bb7-4ef6-bf07-ecb9a0185528.png)

Our icons are 20px x 20px svgs that use all black for color, as color is controlled by our styles. The old icons simply need to be overwritten with new icons. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d920bbb90eafe3a4</li>
        <li>Upwork Job ID: 1603540402436399104</li>
        <li>Last Price Increase: 2022-12-16</li>
    </ul>
</details>

**Comment by Luke9389** [comment]
@shawnborton are we holding on this to finalize the icons?

**Comment by shawnborton** [comment]
Still holding but hopefully we'll have these done soon!

**Comment by shawnborton** [comment]
@Luke9389 here is a big batch of new icons you can get started with: [New Icons.zip](https://github.com/Expensify/App/files/9975953/New.Icons.zip)

You may have to adjust some file names, etc. I'm also still waiting on a few more and I'll drop them here as soon as I have them. Let me know what else you run into as well!

**Comment by Luke9389** [comment]
Oh great! Thanks

**Comment by grgia** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/38015950/202782414-8bfad5a1-19ea-4a9f-82b1-b17e26f10a49.png">
looking good so far!

**Comment by Luke9389** [comment]
Oh, my bad @aimane-chnaif, I'll reopen this and assign a CM to get you paid.

**Comment by Luke9389** [comment]
Hi @laurenreidexpensify, I used the External label to assign you so that we could pay @aimane-chnaif for their review of the [linked PR](https://github.com/Expensify/App/pull/12796).

**Comment by Luke9389** [comment]
Pls ignore this @eVoloshchak

**Comment by laurenreidexpensify** [comment]
@aimane-chnaif have hired you in Upwork for the review, as soon as you accept will issue payment and we can close this out.
