### ISSUE TITLE
Web - New Group - When creating a new group, a console error is displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in to NewDot with any type of account
3. Click on the "New group" option
4. Search for 4 users and add them to the group.

## Expected Result:
Console error should not be displayed when creating a new group

## Actual Result:
When creating a new group, a console error is displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.23.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199865099-42f80971-e3e3-4cf5-b740-6f67631cdecc.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
I was not able to reproduce this in newdot. No console errors are present when I create a new group. Adding Eng for a second pair of eyes.

**Comment by danieldoglas** [comment]
@lschurr sorry, I'm OOO, not sure why melving added me. Can you please reassing?

**Comment by Julesssss** [comment]
Also unable to reproduce. Please reopen if we discover the additional steps (or specific account) that makes this reproducable
