### ISSUE TITLE
Unable to delete a comment right after copying it to the clipboard reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions performed:

1. Go to any chat
2. Right-click/long-press on any comment
3. Click on Copy to clipboard
4. Click on Delete comment before the popup closes
5. Click Delete

## Expected Result:
The comment is copied and then deleted

## Actual Result:
The comment is copied but not deleted

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.23-9

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200005544-6575138a-1636-4812-8f02-0a2c12e0de9e.mp4

https://user-images.githubusercontent.com/43996225/200005769-925a374f-10f0-4ed2-a244-7a4a11c1d9fe.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667568533583239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
It's already reported on [github here](https://github.com/Expensify/App/issues/11086) but it was closed

I also [commented](https://github.com/Expensify/App/issues/11086#issuecomment-1260529522) to repoen issue

**Comment by muttmuure** [comment]
I've been able to reproduce this on web. Let's reopen the original

**Comment by muttmuure** [comment]
Closing in favour of https://github.com/Expensify/App/issues/11086
