### ISSUE TITLE
[$250] Web - Chat - Email address is superimposed with user's avatar when the mouse clicks on the chat's name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Hover the mouse cursor over the chat username

## Expected Result:
Email address shouldn't be superimposed with the user's avatar

## Actual Result:
Email address is superimposed with user's avatar

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.24.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![0411](https://user-images.githubusercontent.com/93399543/200095239-91da2962-4157-40a7-af9d-0848ef54fbff.png)

https://user-images.githubusercontent.com/93399543/200095241-1c67b071-292c-404b-9eb6-1a5412b975f9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
Reproducible and doesn't seem to be a duplicate - moving forward

**Comment by fadlizaini** [comment]
**Proposal**

Remove imported `<Tooltip />` components in avatar's component or make a condition in avatar's component if it used by another page with tooltip required
[https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/components/MultipleAvatars.js#L58-L128](https://github.com/Expensify/App/blob/91acada3b65af8c465febe6853bcc7d37995f0f4/src/components/MultipleAvatars.js#L58-L128)

https://user-images.githubusercontent.com/85979206/200521258-8f64d08c-1caf-42b8-bbd5-dae923c16ef9.mov

**Comment by parasharrajat** [comment]
I don't think this is a bug. we can increase the space between the tooltip and the report title on the header so that it does not lay over the avatar but that feels unnecessary. Tooltips can lay over anything, it does not create a issue for the user.

@Expensify/design Any inputs?

**Comment by shawnborton** [comment]
Yeah I agree, I don't think this one is a bug.

**Comment by shawnborton** [comment]
Going to close this out!
