### ISSUE TITLE
[$250] Payments - After adding the “PayPal.me",it does not appear immediately on the second device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: You must be signed in to the same account on 2 devices (Web-secondary device/ mWeb- my main testing device)
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings > Payment
4. Click/Tap on "Add Payment Method" and Click/Tap on "PayPal.me"
5. Enter any PayPal.me name
6. Click “Add PayPal account” - Verify the account is added and displayed
7. Verify that the data you updated also updates on the secondary devices logged in to the same account (without the need to refresh)

## Expected Result:
PyPal.me should be seen immediately on the second device. No need to refresh the page or go back to settings.

## Actual Result:
PayPal.me can seen only by returning to the settings and then go back to payments.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200186844-13bc59c6-5af9-46da-aafe-5851fd4f0788.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
I am OOO, reassigning to get coverage on the bug issue.

**Comment by CortneyOfstad** [comment]
Working on this today!

**Comment by CortneyOfstad** [comment]
After reviewing this, I'm not sure if this is a bug. You have to refresh the page in some way in order for the changes to appear (not sure what the threshold is for automatic refresh on the browser). 

However, going to add the #engineering label to get some additional guidance on whether this needs to be fixed and if it needs to be external or internal.

**Comment by srikarparsi** [comment]
I agree @CortneyOfstad, I don't think this is a bug that we need to fix as I haven't seen anything like this in the past that we've focused on. Just to get a second set of eyes before closing this out though, @puneetlath is this good to be closed or do you think it's worth fixing?

**Comment by puneetlath** [comment]
Hm, I believe with 1:1:1 this should automatically update on all devices. The flow should be similar to this:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1371996/202223860-cb60ba29-d3d6-4a35-ae79-0f26254f4c9f.png">

So in theory for this flow it should be: 
1. User adds paypal.me 
2. We optimistically show that in the UI
3. Send the API call to store it
4. Server pushes response

Step 4 should push the update into any connected device, so if it isn't doing that it sounds like there is a bug somewhere.

**Comment by srikarparsi** [comment]
ah ok that makes sense. Marking it external so that it can be worked on.

**Comment by flodnv** [comment]
This is an internal bug. Taking it.

**Comment by flodnv** [comment]
Fix is deployed
