### ISSUE TITLE
IOU - Cannot select numbers for cut/copy reported by @aimane-chnaif

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. Click FAB menu -> Request money
3. Enter amount using keyboard
4. Select the numbers to highlight

## Expected Result:
Selected numbers should be highlighted and show cut/copy/paste context menu

## Actual Result:
When select numbers, highlight status keeps changing. And sometimes shows context menu and immediately closed.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/200348144-c11921ee-d406-470f-9bb6-6b17ab333e82.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667791907935039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
Thanks for identifying the dupe @rushatgabhane. I'm going to close this one out in favor of the other issue.
