### ISSUE TITLE
Ability to request zero amount of money from Split Bill reported by @kerupuksambel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Click + > Split Bill
3. Enter 0.01 as its amount
4. Select at least 3 people for the split bill recipient
5. Click Send

## Expected Result:
The split bill should be invalid since the amount split is 0

## Actual Result:
The split bill is validated and the recipients got requested with zero amount of money

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200350630-217e4fb5-ad14-4e3f-a058-8a7604ff50df.mp4

https://user-images.githubusercontent.com/43996225/200350657-00a15128-2207-413f-a5f5-044ce600281a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667792460122249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment]
Confirming in the Slack thread if we should close this (as per the Slack discussion linked).
