### ISSUE TITLE
Android build `1.2.24-1` crashes on launch

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#12522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Android build `1.2.24-1` crashes on launch, reported [here](https://github.com/Expensify/App/issues/12476#issuecomment-1305856066).

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
This is the first time I was assigned an hourly engineering issue so I talked to Jules in the chat and since this is a pretty critical internal issue, there's no action needed from me.

**Comment by Julesssss** [comment]
Trying this [fix](https://github.com/facebook/react-native/issues/35210#issuecomment-1305860027). If it doesn't work we should just go ahead and merge the React Native `0.70.5` hotfix changes into our fork and deploy. But first, let's try this quicker solution.

**Comment by Julesssss** [comment]
Here's more context about the [original issue](https://github.com/Expensify/App/pull/12510).

**Comment by Julesssss** [comment]
PR is ready, I'm just compiling the release build for testing. I ran into an OOM error on the first attempt 😓

**Comment by Julesssss** [comment]
[PR in review](https://github.com/Expensify/App/pull/12525)

**Comment by yuwenmemon** [comment]
Closing this out! `1.2.24-4` is not crashing on launch! 🎉
