### ISSUE TITLE
BUG: Adding a personal bank account causes a crash

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#12530]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with any account
2. Go to Settings, Payments, Add payment method, bank account
3. Connect through Plaid with a test account
4. After the connection succeeds click continue

## Expected Result:
The bank account is added and shows up in the app

## Actual Result:
There is a loading spinner for a while and then the app crashes

## Workaround:
No

## Platform:

Probably all platforms but we need to check.

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.24-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/26260477/200402670-20de4977-46ca-4296-8fc5-82ae5bb6ddf0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1667851355646509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
As decided in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667857000329679?thread_ts=1667585603.394289&cid=C01GTK53T8Q) we will hold this on https://github.com/Expensify/App/issues/12308 and see if we can reproduce after it is fixed.

**Comment by alexpensify** [comment]
I've asked if we should move this to a weekly or leave it as a daily.

**Comment by alexpensify** [comment]
I've confirmed it's possible to move to weekly and I'm setting a reminder to check the status.

**Comment by alexpensify** [comment]
I checked and it looks like this one is still under review. Setting another reminder for Friday and might have to reassign due to being OOO next week.

**Comment by nkuoch** [comment]
[The other one](https://github.com/Expensify/App/issues/12308) seems not be reproducible. Can anyone check if this one is reproducible? I personally couldn't reproduce it.

**Comment by alexpensify** [comment]
I tested per @nkuoch request and was able to replicate in my al@expensify.com account using @neil-marcellini's steps. 

![image](https://user-images.githubusercontent.com/8107070/202795426-df471fc1-d03f-485b-9fff-cd2765c71a30.png)

When I log back in, the bank account is not there. 

![image](https://user-images.githubusercontent.com/8107070/202795518-9af0d29c-361f-4dee-87df-7fcc067a05c0.png)

**Comment by nkuoch** [comment]
I can't reproduce it, but seems like we're getting:

> alXt] NewExpensify crash caught by error boundary - Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. ~~ errorInfo: '{"componentStack":"\n    at a (app:\/\/-\/main-6415f669a262c0246388.bundle.js:2:5127210)

Which leads to:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by nkuoch** [comment]
@alexpensify are you testing from chrome? Do you have the same error after you clear your cookies? If yes, would you mind sharing your credentials with me so I can hopefully reproduce myself?

**Comment by nkuoch** [comment]
Yes please

**Comment by nkuoch** [comment]
@neil-marcellini as al is ooo, could you test on chrome and tell me if you still have the issue? If yes, does clearing our your cookies fix it? Yes no, could you share your credentials with me so I can reproduce and investigate?

**Comment by neil-marcellini** [comment]
Sure I'll try it now.

**Comment by neil-marcellini** [comment]
I'm no longer able to reproduce, we can close this 🙂
