### ISSUE TITLE
Android / iOS - User Should be able to zoom in/ out the Avatar or any other icon using fingers on touch devices reported by @aneequeahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
User friendly and expected behaviour in almost all the apps where image is uploaded for identification(UX)

## Solution: 
Should implement in our app for better User Experience.

## Platform:

Where is this issue occurring?

- iOS
- Android

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200580214-55a0e39c-d83c-4638-8bac-34dc99dbc7c7.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @aneequeahmad 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667091216580059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aneequeahmad** [comment]
### PROPOSAL:



We can implement the feature using RNGH 2.0 (react-native gesture handler). By adding this we can also replace the older implementation of `PanGestureHandler` which is no longer actively maintained as advised by RNGH official doc [here](https://docs.swmansion.com/react-native-gesture-handler/docs/2.3.0/api/gestures/pinch-gesture#:~:text=which%20is%20no%20longer%20actively%20maintained.)

**Code changes:**


These lines of code will be added in `AvatarCropModal.js`

```
    const pan = Gesture.Pan().onChange(({ translationX, translationY }) => {
        translateX.value = translationX;
        translateY.value = translationY;
      });
      const pinch = Gesture.Pinch().onChange((event) => {
        scale.value = event.scale;
      });
      const gesture = Gesture.Race(pan, pinch);
```

Changes in file `ImageCropView.js`

_**FROM:**_

https://github.com/Expensify/App/blob/51fac62203f87a27a454d49071913cb9319cfaf5/src/components/AvatarCropModal/ImageCropView.js#L67-L74

**_TO:_**

```
        <GestureDetector gesture={props.gesture}>
                <Animated.View style={[containerStyle, styles.imageCropContainer]}>
                    <Animated.Image style={[imageStyle, styles.h100, styles.w100]} source={{uri: props.imageUri}} resizeMode="contain" />
                    <View style={[containerStyle, styles.l0, styles.b0, styles.pAbsolute]}>
                        <Icon src={Expensicons.ImageCropMask} width={props.containerSize} height={props.containerSize} />
                    </View>
                </Animated.View>
            </GestureDetector>      
      
```

**Comment by aneequeahmad** [comment]
@kavimuru bump

**Comment by marcaaron** [comment]
Going to close this. I don't think it's something we will prioritize any time soon.
