### ISSUE TITLE
Chat - Room is stuck on my gmail account and it shows a white screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in andreylazutkinutest+123@gmail.com/w323052760We
3. Navigate to a conversation (conv 1)
4. Click on the Pin icon on top right to pin the conversation to the top of LHN
5. Navigate to another conversation (conv 2)
6. Write something on compose box and navigate away from the conversation to leave a drafted message
7. Click on preferences
8. Click on the Priority Mode option and select “#focus”
9. Click room #ttt

## Expected Result:
Gmail account should not have a room

## Actual Result:
Room is stuck on my gmail account and it shows a white screen

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200700439-01e211b7-e8de-4551-bb3b-c9fdce735126.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
ty @aimane-chnaif closing this
