### ISSUE TITLE
When a chat becomes archived, automatically hide it from the LHN. It should still be discoverable via search but should be “permanently unpinned” in the LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a bill from OldDot from account A and sent it to account B who does not have shared policy.
2.  Account B see the comment in LHN (NewDot)

## Expected Result:
When a chat becomes archived, mark it as read and automatically hide it from the LHN

## Actual Result:
It shows up all the way at the bottom of LHN, so  have to scroll to find it, and  cannot actually mark it read.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.24-4

**Reproducible in staging?:** Need reproduction

**Reproducible in production?:** Need reproduction

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img width="800" alt="Screen Shot 2022-11-04 at 2 16 38 PM" src="https://user-images.githubusercontent.com/43996225/200716994-777fc988-2084-4afa-ac11-87fb146c8e3c.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @rafecolton 

**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667596774515129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@kevinksullivan, I'm a bit at a loss as to what this issue is about. You added the `New Feature` label, any ideas?

**Comment by kevinksullivan** [comment]
My read of this thread (while skimming many) during the resync is [this was a new idea](https://expensify.slack.com/archives/C01GTK53T8Q/p1667603661228129?thread_ts=1667596774.515129&cid=C01GTK53T8Q), but on looking again it seems this should have always been the case. Is that right? So we can label as `Bug` + `Extenral`?

**Comment by trjExpensify** [comment]
Ah gotcha, so this is just about archived chats in the LHN? Let's close it. It's intended that archived chats remain in your LHN, since all the sidebar logic got simplified and cleaned up. Related discussion worth looking at from [here](https://expensify.slack.com/archives/C07J32337/p1665446134918719?thread_ts=1665416806.084149&cid=C07J32337)
