### ISSUE TITLE
Follow up: Implement proper fix for android textinput selection workaround

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#12587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Context
In https://github.com/Expensify/App/pull/11684 there was a workaround introduced. See this conversation for more detail:

https://github.com/Expensify/App/pull/11684/files#r1013587630

It's about the android TextInput not updating its selection correctly.

## Action Performed:
Select a range of text, then call `textInput.setSelection(5, 5)` on a text selection (for example).

## Expected Result:

The android text input selection should just work as it does on web or iOS.

## Actual Result:

Under some circumstances, the selection won't get updated actually on Android.

## Workaround:

Already in place

## Platform:
Where is this issue occurring?

- Android

**Version Number:** 1.2.25-0
**Reproducible in staging?:** /
**Reproducible in production?:**  /
**Email or phone of affected tester (no customers):**  /
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hannojg 
**Slack conversation:** /

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment]
@roryabraham please reopen 🍀

**Comment by roryabraham** [comment]
Assigning to @hannojg to work on the upstream fix, but @hannojg let us know if you don't have time or get stuck

**Comment by alexpensify** [comment]
@roryabraham - do I need to create a job in Upwork too?

**Comment by roryabraham** [comment]
No, @hannojg will invoice us separately

**Comment by alexpensify** [comment]
@hannojg - any update? How are things going?

**Comment by alexpensify** [comment]
@hannojg - how's it going here?

**Comment by hannojg** [comment]
Hey, I am currently stuck in trying to create a bug ticket on the android framework AOSP. Will reach out to my internal network and trying to reach an android engineer from google to help me with that ticket. 
As far as I understand the bug, there is nothing we can really fix, but it has to be fixed in the android framework.

**Comment by roryabraham** [comment]
Chatted in slack [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1670624941253179)

**Comment by roryabraham** [comment]
@hannojg Let us know what issues you've run into creating the Android bug ticket, maybe we can crowdsource a solution in #expensify-open-source?

**Comment by hannojg** [comment]
Hey @roryabraham the issue is that after creating the issue you don't seem to get access to it (but neither its in a review queue, its just gone it seems).

You can see screenshots of the issue here (also if you continue reading the comments you will find more screenshots):

https://github.com/facebook/react-native/issues/35350#issuecomment-1326184026

My idea now is to try to reach the google team (I already tried but weren't successful yet).

**Comment by JmillsExpensify** [comment]
Here's my two cents on this issue: I think we should remove the `Bug` label and instead add the `Planning` and `Weekly` labels. The thing is, we already solved the "bug" in the linked issue, and this is effectively a research issue on how to potentially solve Android bugs. So yes, I think that's great, but I also don't think this is really within the scope of WAQ given that we have something that has resolved the bug for now.

**Comment by alexpensify** [comment]
Thanks for the feedback. I'm going OOO until January 3 and will catch up then to identify if there is any movement here.

**Comment by alexpensify** [comment]
I'm still OOO and plan to review next week when I'm back online.

**Comment by alexpensify** [comment]
I've asked for feedback here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1673049231644019?thread_ts=1671463643.046229&cid=C01GTK53T8Q

**Comment by alexpensify** [comment]
No update, still in the planning stage

**Comment by alexpensify** [comment]
No update

**Comment by hannojg** [comment]
Follow up: the react native team has recognised this issue and reopened the issue we opened for it: 

- https://github.com/facebook/react-native/issues/35350

I am pretty sure they will help forward the issue to the android engineering team, will keep this issue updated !

**Comment by alexpensify** [comment]
Thank you for this update!

**Comment by roryabraham** [comment]
> Can we get a minimal repo that shows the issue? Then we can fix it.

@hannojg Do you still have your minimal reproduction in a native Android app? Any chance you can share that?

**Comment by alexpensify** [comment]
@hannojg when you get a chance this week, can you answer @roryabraham's question? Thanks!

**Comment by alexpensify** [comment]
@hannojg any update here?

**Comment by roryabraham** [comment]
Let's close this for now and move on to bigger and better things. I'll subscribe to the upstream issue and reopen this if it is ever resolved in Android itself.
