### ISSUE TITLE
[HOLD] Language picker can’t be focused via keyboard reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to login screen
2. Try focusing on the language picker with Tab
3. Notice it is not capturing focus

## Expected Result: 
Language picker should be able to capture focus

## Actual Result: 
Language picker is not capturing focus

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.24-4

**Reproducible in staging?:** Need reproduction

**Reproducible in production?:** Need reproduction

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200724192-3ef7406e-ae5c-4784-b474-aaf94e3abf2a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @huzaifa-99

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667952261507929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pelkonator** [comment]
**Proposal**
https://github.com/Expensify/App/blob/main/src/styles/styles.js
convert **pickerSmall** object to a function

```diff
- pickerSmall: {
+ pickerSmall: (disabled = false, error = false, focused = false) => ({
        ...
        inputWeb: {
            fontFamily: fontFamily.GTA,
            fontSize: variables.fontSizeSmall,
            paddingLeft: 9,
            paddingRight: 25,
            paddingTop: 6,
            paddingBottom: 6,
            borderWidth: 1,
            borderColor: themeColors.border,
            borderStyle: 'solid',
            borderRadius: variables.componentBorderRadius,
            color: themeColors.text,
            appearance: 'none',
            height: variables.componentSizeSmall,
            opacity: 1,
-          cursor: 'pointer',
+         cursor: disabled ? 'not-allowed' : 'pointer',
            backgroundColor: 'transparent',
+         ...(focused && {borderColor: themeColors.borderFocus}),
+         ...(error && {borderColor: themeColors.badgeDangerBG}),
        },
        ...
-}
+})
```

This will match current implementation of the **picker** function in the same file:
```
   picker: (disabled = false, error = false, focused = false) => ({
        iconContainer: {
            top: 16,
            right: 11,
            zIndex: -1,
        },
        inputWeb: {
            appearance: 'none',
            cursor: disabled ? 'not-allowed' : 'pointer',
            ...picker,
            ...(focused && {borderColor: themeColors.borderFocus}),
            ...(error && {borderColor: themeColors.badgeDangerBG}),
        },
        inputNative: {
            ...picker,
            ...(focused && {borderColor: themeColors.borderFocus}),
            ...(error && {borderColor: themeColors.badgeDangerBG}),
        },
    }),
```

**Comment by thesahindia** [comment]
We tackled this at https://github.com/Expensify/App/pull/12500, so let's put this on hold.

cc: @roryabraham

**Comment by mateocole** [comment]
Moved to hold

**Comment by roryabraham** [comment]
This should be fixed once #12500 is deployed to staging

**Comment by mateocole** [comment]
Tested - fixed, added to testrail.

@roryabraham @conorpendergrast I am not totally sure how the payout works with this issue, since this was already resolved from a separate issue, and there appears to be a separate payout commencing from https://github.com/Expensify/App/issues/11852, can this be closed?

**Comment by roryabraham** [comment]
Yes, we can just close this since no contributor was hired to fix it.
