### ISSUE TITLE
Keyboard is covering the `Save` button after an error message in workspace settings page reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to settings > Workspaces
2. Select a workspace
3. Delete the name and press save
4. Now focus at the name field again

## Expected Result:
The button should be completely visible

## Actual Result:
`Save` button is covered by keyboard

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android
- Mobile Web

**Version Number:** 1.2.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200723405-f4901ec6-cfd5-4e9f-8b23-f8ae87c50f62.mp4

https://user-images.githubusercontent.com/43996225/200723429-75fcc0b5-6788-427c-8ecb-10ab8a5b5949.mp4

https://user-images.githubusercontent.com/43996225/200723431-3519d817-c50a-429b-9bf0-9976b7934142.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667947885714449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Expected behavior here is not entirely clear to me. Closing pending solution/clarity in[ this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1668116607125399?thread_ts=1667947885.714449&cid=C01GTK53T8Q).
