### ISSUE TITLE
iOS - Sending a jpg image throws error as "Unsupported PDF format" 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app
2. Go to any chat
3. Tap add an attachment and select a jpg image
4. Upload the image

## Expected Result:
Image gets uploaded

## Actual Result:
"Unsupported PDF format" error message appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200721375-14937322-b500-4c3d-be93-a603e33742f6.MP4
<img src="https://user-images.githubusercontent.com/43996225/200721393-c6966423-73a5-41e9-9b65-2fbe6c11b320.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/200721394-c0532d29-9f41-4348-8bcc-f362f4eaf14b.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rosegrech 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667940506846659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Asking whether this is already being handled in another GH [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668013421324619?thread_ts=1667940506.846659&cid=C01GTK53T8Q).

**Comment by kevinksullivan** [comment]
Duplicate as discussed in slack ^

**Comment by kevinksullivan** [comment]
Being discussed in https://github.com/Expensify/App/issues/12283#issuecomment-1308495045, for reference.
