### ISSUE TITLE
Connect Bank Account - Page directed to the Workspace Setting after use "Back" button under Test Transactions Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Create Workspace if you don't have one
4. Go to Settings- WS - Connect Bank Account
5. Select Connect Manually > Connect Bank Account > Company Information > Personal Information > Additional Information
6. Use back button in Test Transactions page

## Expected Result:
After using "Back" button should go to previous page.

## Actual Result:
Page directed to the Workspace Setting after use "Back" button under Test Transactions Page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200864476-e886bac6-c7fa-4304-bff9-16b97f82deb1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
<b>Proposal</b>
In our current code we are go back when press back in ValiationStep:
https://github.com/Expensify/App/blob/17f7a0ac9dbfd43ff60c0f681e77ef3fffbe3df2/src/pages/ReimbursementAccount/ValidationStep.js#L126
<b>Solution</b>
Instead of `goBack`,  we move the user to the previous page, to do that we need to update the `onBackButtonPress` function in `ValidationStep.js`.
```diff
 <HeaderWithCloseButton
                    title={isVerifying ? this.props.translate('validationStep.headerTitle') : this.props.translate('workspace.common.testTransactions')}
                    stepCounter={{step: 5, total: 5}}
                    onCloseButtonPress={Navigation.dismissModal}
-                   onBackButtonPress={() => Navigation.goBack()}
+                  onBackButtonPress={() => +BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.ACH_CONTRACT)}
                    shouldShowGetAssistanceButton
                    guidesCallTaskID={CONST.GUIDES_CALL_TASK_IDS.WORKSPACE_BANK_ACCOUNT}
                    shouldShowBackButton
                    shouldShowStepCounter={!isVerifying}
                />
```

**Comment by conorpendergrast** [comment]
- [x] The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead).
- [ ] The bug is reproducible, following the reproduction steps - > Stuck on this, [getting help](https://expensify.slack.com/archives/C01SKUP7QR0/p1668068189490209) with the test VBA.

**Comment by conorpendergrast** [comment]
I have reproduced now, but I'm not convinced that this is a bug. Once the bank account has been set up and the validation amounts have been sent, I don't think we want to allow editing the submitted bank account, company and personal details. 

I'm going to check and confirm that

**Comment by conorpendergrast** [comment]
Checking via Slack, in [the expensify-bugs channel](https://expensify.slack.com/archives/C049HHMV9SM/p1668383086423159)

**Comment by conorpendergrast** [comment]
I'm going to close this for now, and will reopen if there's disagreement!
