### ISSUE TITLE
Settings - Profile image disappears after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12374 

## Action Performed:
1. Open app
2. Upload a new profile image
3. Verify the image is not updating immediately
4. Reload the page (Cmd+R)

## Expected Result:
Image should be updated immediately in step 3

## Actual Result:
After refreshing the page image should not disappear

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200835205-12ad5ad0-54c5-4960-9e95-02140d87a799.mp4

https://user-images.githubusercontent.com/93399543/200835254-dc9f6d7d-3459-4ec8-8f8d-289168febbc4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
I already fixed this with https://github.com/Expensify/Web-Expensify/pull/35507- closing!
