### ISSUE TITLE
[Hold #219254] iOS - Push notification leads to blank screen if the app not running at the background

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Kill the App (dismiss App's card)
2. Sent message to the user
3. Tap on the notification

## Expected Result:
The user should be able to view chat after tapping on the notification when App was killed (not running at the background)

## Actual Result:
Bank screen after logo appears

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200917754-3022b919-e600-46ac-bac1-f229e0e10222.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Yep - i'm able to reproduce this

https://user-images.githubusercontent.com/42940078/200965507-d70fada7-6617-4543-a07b-d526351c62ff.MP4

**Comment by puneetlath** [comment]
@Julesssss would this be part of the notifications project?

**Comment by Julesssss** [comment]
Oh, pretty sure this is a regression -- a RCA and testing older versions should locate the regression here. Will discuss this with Andrew though.

**Comment by puneetlath** [comment]
@Julesssss @AndrewGable what do you think? Should this be handled separately from your notifications project?

**Comment by Julesssss** [comment]
It's @arosiclair FYI, but yeah, i think this definitely falls under the reliability umbrella.

**Comment by Julesssss** [comment]
I added it to the tracker and will discuss with Andrew 1:1

**Comment by sophiepintoraetz** [comment]
Imma close this one out until we reopen and decide to do something with it!
