### ISSUE TITLE
"Crash" issues - clean-up and next steps

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#12609]
Coming from [this discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1668016773579309). 

- [ ] Only open a "crash" issue after it happens more than `10` times 
- [ ] For existing crashes logged, update the reopen logic to see if the crash count is less than 10 before reopening
- [ ] Remove the $500 price cap on crash issues
- [ ] Implement source maps to aid with investigating these issues ([GH](https://github.com/Expensify/App/issues/9293))
- [ ] Close the loop on people running staging builds locally sending false positives ([GH](https://github.com/Expensify/Expensify/issues/230440))
- [ ] Improve the documentation for how to approach these issues, and link the readme in the crash issue creation template

CC: @AndrewGable @JmillsExpensify @michaelhaxhiu @roryabraham

**Comment by JmillsExpensify** [comment]
Should we throw a `Bug` label on this, on someone assign themself? I'm thinking yes since some of those todos are BZ tasks.

**Comment by trjExpensify** [comment]
I don't think it's a `bug` really, it's a process improvement. 

I'll assign myself anyway and take on this one: 

>Remove the $500 price cap on crash issues

**Comment by JmillsExpensify** [comment]
Ok cool. Mainly I think someone from BZ should assign themselves.

**Comment by iwiznia** [comment]
There's already an issue for the source maps https://github.com/Expensify/App/issues/9293
Not sure if we want to close that out or remove that part from this isssue.
FWIW I think adding the source map should be the first step, because without it, some crashes are impossible to diagnose.

**Comment by trjExpensify** [comment]
It's linked to this issue in the OP.

**Comment by AndrewGable** [comment]
Focused on the [source maps](https://github.com/Expensify/App/issues/9293) as the first priority for this, then will get to this.

**Comment by AndrewGable** [comment]
Closing per https://github.com/Expensify/Expensify/issues/243479, tl;dr we are turning off Firebase crashes for the time being.
