### ISSUE TITLE
The next message is getting "unread" when you mark a message as "unread" and refresh the page reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to a chat
2. Send two messages
3. Right click on the first message and click Mark as unread
4. Navigate to another chat and refresh the page

## Expected Result: 
You should see the new message indicator above the first message

## Actual Result: 
You will see the new message indicator above the second message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App
- Mobile Web

**Version Number:** 1.2.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200955941-d3f3db8f-0646-4b87-a70a-234e97c4b81f.mp4

https://user-images.githubusercontent.com/43996225/200955963-76ba6321-62e7-4f03-b871-7b4cfbbac388.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667987219406859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Reproduced on web production: 

![2022-11-10_16-23-06 (1)](https://user-images.githubusercontent.com/54866469/201210821-480ed02f-2536-4e0d-baff-b1b862c67f24.gif)

**Comment by joekaufmanexpensify** [comment]
Passing to engineering for confirmation that this can be external prior to making upwork job!

**Comment by joekaufmanexpensify** [comment]
Pending confirmation of being an external issue.

**Comment by nkuoch** [comment]
I think it should be internal. Will try to fix it myself.

**Comment by thesahindia** [comment]
@nkuoch, can we reopen this? The reporting compensation is pending. 

cc: @sakluger

**Comment by nkuoch** [comment]
Not overdue. Cc @sakluger

**Comment by sakluger** [comment]
Created Upwork job:

Internal post - https://www.upwork.com/ab/applicants/1597392944240934912/job-details
External post - https://www.upwork.com/jobs/~01a859778666a353d0

@thesahindia I hired you for the job, once you accept I can pay out. Thanks!

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by sakluger** [comment]
Paid, thanks everyone!
