### ISSUE TITLE
VBA - Selecting Chase bank directs to  First Platypus Bank 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12621]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Go to Settings > Workspace > Connect bank account > Connect online with Plaid
3. Click Continue, then select Chase, and click Continue again

## Expected Result: 
After step 3, the new window should show a Chase login 

## Actual result: 
A new window opens up showing a login for FPB First Platypus Bank 

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.26-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="801" alt="image (3)" src="https://user-images.githubusercontent.com/43996225/200960106-7fe838ef-aef6-4417-943a-1c395ee2f60b.png">
<img width="792" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/200960112-a914663c-4a98-4bd2-8d69-9e93cdc23ec2.png">

https://user-images.githubusercontent.com/43996225/200960129-7f6815e2-e0e2-40a4-bba2-0ed5973668d6.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666230207938749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
- I can reproduce this 
- The Slack [chat](https://expensify.slack.com/archives/C01GTK53T8Q/p1666230207938749), sounds like First Platypus bank is the Plaid sandbox account
- This only happens in staging and not production
- [Dev: Connect to bank account is not opening Sandbox page on dev server, redirects to real bank website reported by @parasharrajat](https://github.com/Expensify/App/issues/12315) might be related 
- I think this can be internal - and maybe can be combined with https://github.com/Expensify/App/issues/12315

**Comment by francoisl** [comment]
Yes this is normal, First Platypus Bank is a sandbox (test) bank from Plaid (see https://plaid.com/docs/sandbox/institutions/) and our staging servers are configured to connect to Plaid's sandbox API ([internal ref](https://github.com/Expensify/Salt/blob/cf14b63bb8a/www/files/www-config.php.template#L1988))

You should be able to connect to the real bank by disabling the "Use staging server" option in your account settings.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2229301/201233385-18fa6059-af5f-4451-80f5-683b49922d58.png">
