### ISSUE TITLE
[$250] IOS - Chat - After pasting any emoji in the middle of the text additional spaces get added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12529

## Action Performed:
1. Open the App and login
2. Go to any chat
3. Type "test test" then paste an emloji, for this example it was used an :apple:, in the middle

## Expected Result:
NO additional space gets added around the emoji

## Actual Result:
Additional spaces get added around the emoji

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201179835-cc7e5f7f-a1e3-42b7-8d58-dff5b3ee34a5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
@kbecciv just bumping the question above

**Comment by kbecciv** [comment]
@bfitzexpensify Checking, update you shortly

**Comment by kbecciv** [comment]
@bfitzexpensify I have the default keyboard in my testing IOS device and I was able to paste in the middle of the word.

https://user-images.githubusercontent.com/93399543/201678695-06550e3e-0164-4a3e-825e-54311b608290.MP4

**Comment by bfitzexpensify** [comment]
Thank you! OK, I was able to reproduce

**Comment by sketchydroide** [comment]
I'm not sure if this is a feature or not @stitesExpensify you might know a bit about this, but if it's a bug I would say that this can be an external

**Comment by sketchydroide** [comment]
also is this specific to the 🍎 emoji or any emoji, the specificity here is a bit weird. @kbecciv can you guys check or answer that? Thanks :)

**Comment by bfitzexpensify** [comment]
All emojis, updated the title to be clearer

**Comment by kbecciv** [comment]
@bfitzexpensify Thank you for updating the title.

**Comment by sketchydroide** [comment]
I think this might be an automatic thing, but I tested the same behaviour on other apps (namely Whatsap) and this does not happen so it shouldn't happen to us as well.
Setting this as a External

**Comment by bfitzexpensify** [comment]
Job on Upwork:

Expensify [link](https://www.upwork.com/ab/applicants/1593206438401196032/job-details)

Contributor [link](https://www.upwork.com/jobs/~019002706fe5a6f651)

**Comment by Pujan92** [comment]
I think this is not the application level bug, in the ios wherever we paste text(not only emoji) in a single word it creates the adjacent space.

**Comment by mollfpr** [comment]
@sketchydroide @bfitzexpensify Should the expected also apply to the regular text or only when pasting emoji? WhatsApp doesn't add extra space on text or emojis.

**Comment by bfitzexpensify** [comment]
No spaces should be added whether pasting regular text or an emoji

**Comment by grgia** [comment]
I'll take this one!

**Comment by grgia** [comment]
Looking into this

**Comment by grgia** [comment]
Fixed by https://github.com/Expensify/App/pull/12529.
