### ISSUE TITLE
Log in - There’s No message saying that a Magic Link has been sent to the email address

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In the email field enter a email that has an active Expensify account and click on continue
3. Disable the internet connection in the device
4. Verify the Sign in button is disabled and there's a message indicating the user is offline.
5. Verify the link "Not ? Go back." is still enabled when offline
6. Click/tap on “Forgot?”

## Expected Result:
Verify there’s a message saying that a Magic Link has been sent to the email address

## Actual Result:
There’s No message saying that a Magic Link has been sent to the email address

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201144329-96e44b8d-4bdb-431f-80bd-ca8c6387cd38.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is failing step 5. Verify there’s a message saying that a Magic Link has been sent to the email address in TestRail 

![image](https://user-images.githubusercontent.com/93399543/201144824-b814aef3-5cbc-4332-b5e2-75f834e66821.png)

**Comment by dylanexpensify** [comment]
reviewing today Mel! Jeez!

**Comment by thesahindia** [comment]
> There’s No message saying that a Magic Link has been sent to the email address

In the video after pressing "forgot?" It clearly says that the link has been sent. I don't think this is a bug.

**Comment by dylanexpensify** [comment]
Agree, video shows everything working as should, closing
