### ISSUE TITLE
[HELD on regression test checklist] [$250] [mWeb] keyboard type wrong on login page reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open login page
2. click on phone or email
3. check keyboard type

## Expected Result:
should show email keyboard

## Actual Result:
shows default keyboard

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
!<img src="https://user-images.githubusercontent.com/43996225/201191154-9ef6c95b-1a98-4c7e-92d3-d0daefa5b126.jpg" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/201191178-4b17c4a9-1e1c-4243-896d-f76c2556b61a.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1668067650251919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
**Proposal**

use `CONST.KEYBOARD_TYPE.EMAIL_ADDRESS` instead of `getEmailKeyboardType()` and remove `getEmailKeyboardType()`
https://github.com/Expensify/App/blob/599f1b9c806cfb612b74a3b9378f0d988d29b889/src/pages/signin/LoginForm.js#L180

"*OR*"

change keyboard type in the below file from `default` to ` email-address ` and remove [index.native.js](https://github.com/Expensify/App/blob/main/src/libs/getEmailKeyboardType/index.native.js) file
https://github.com/Expensify/App/blob/599f1b9c806cfb612b74a3b9378f0d988d29b889/src/libs/getEmailKeyboardType/index.js#L6

**Comment by stephanieelliott** [comment]
I am able to repro, seems like a good issue for an external contributor!

**Comment by stephanieelliott** [comment]
We have a proposal already, @aimane-chnaif can you please review it? https://github.com/Expensify/App/issues/12649#issuecomment-1310961683

**Comment by gadhiyamanan** [comment]
@stephanieelliott you can unassign me as it's not yet approved by @roryabraham

@roryabraham any thoughts on https://github.com/Expensify/App/issues/12649#issuecomment-1314869104

**Comment by stephanieelliott** [comment]
Oops, jumped the gun here -- thanks @gadhiyamanan!

**Comment by roryabraham** [comment]
Sorry for the delay @gadhiyamanan, I thought I already assigned this to you. Anyways, PR is approved and now we'll just want @aimane-chnaif to review, then I can merge it. Thanks!

**Comment by stephanieelliott** [comment]
@aimane-chnaif those are the same job 😃, everyone should be paid up now!

**Comment by gadhiyamanan** [comment]
@stephanieelliott please close the upwork contact
