### ISSUE TITLE
[$250] mWeb/Safari - Log in - The cursor does not focus on the password input field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12640]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go to https://staging.new.expensify.com/
2. Enter the email on the email field
3. Click continue

## Expected Result:
The cursor should be focus on the password section

## Actual Result:
The cursor does not focus on the password input field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Safari

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201133721-a89de99f-7fd5-4138-a6a0-753b15bc0703.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~016a5c80040608f342

**Comment by loganbek** [comment]
My plan is to ensue the dispatch action target is set properly in Navigation.js. (151: navigationRef.current.dispatch(StackActions.pop()) looks like it may need a conditional. If not, I'll debug further in DrawerAction.js, BrowserAction.js, or there imports. @arielgreen, I can have an update in 3 days. Let me know if you need anything else before I commence.

**Comment by sobitneupane** [comment]
Based on this [discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1667944956842919?thread_ts=1667850311.631759&cid=C02NK2DQWUX), this issue can be closed.

cc: @techievivek

**Comment by techievivek** [comment]
Aaah yes, we don't need to look into this one because we are deprecating it.
