### ISSUE TITLE
Android - Attachments - Mark as unread option doesn't work if you just attached the photo from Gallery

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Attach any photo
4. Hold your finger by the attachment 
5. Select option " Mark as unread"

## Expected Result:
Mark as unread option works if you just attached the photo from Gallery

## Actual Result:
Mark as unread doesn't work if you just attached the photo from Gallery

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201135044-37486bdf-7c25-43eb-9da1-945b1a914589.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I don't have an android device - still not clear what to do in these situations

**Comment by muttmuure** [comment]
Posted asking for help [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1668514415891219)

**Comment by techievivek** [comment]
I am unable to reproduce this. I tried uploading the image right from the gallery and then marking it unread and worked smoothly.
<img width="422" alt="Screenshot 2022-11-15 at 6 15 29 PM" src="https://user-images.githubusercontent.com/35863227/201922871-51b7265c-fd47-4eee-9544-07c326b1ed80.png">

**Comment by muttmuure** [comment]
Unable to repro @kbecciv! Feel free to close if this is no longer an issue

**Comment by kbecciv** [comment]
Checking with current build

**Comment by kbecciv** [comment]
Unable to reproduced with build 1.2.29.5 

https://user-images.githubusercontent.com/93399543/202731638-6d72b6fb-1215-4dc0-857b-699cd7ebd43d.mp4
