### ISSUE TITLE
There is an extra outer border on a protected pdf in chat reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a protected pdf in any chat (a protected pdf sample is attached: Pass Ccccccc11)
2. Notice it has an extra outer border in the chat

## Expected Result: 
The outer border should not exist (or at-least be rounded the same as the inner border)

## Actual Result: 
There is an extra outer border with a different border radius (Visible after zoom in the page)

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.26-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/201203546-3e235951-a71a-45bb-bff1-79d62bc5fa8e.mp4
<img width="960" alt="3" src="https://user-images.githubusercontent.com/43996225/201203559-4ff5f10f-c2d4-47f9-b517-9ddb7f5a886d.png">
[sample-protected.pdf](https://github.com/Expensify/App/files/9984530/sample-protected.pdf)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668111547203699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Dupe https://github.com/Expensify/App/issues/11520

**Comment by kavimuru** [comment]
Dupe #11520
