### ISSUE TITLE
[$500] [HOLD for payment 2023-09-07] - Group chat - Selecting a user with tab adds the first user in the list as well  reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on the plus icon and select new group chat
2. On the group chat creation menu, Tab to a user after the first user (lets say tab to user-2 that is after user-1)
3. Then Enter to select that user (user-2) as chat participant
4. Notice the previous user (user-1) is also selected as a chat participant

## Expected Result:
Only the selected (Tab+Enter’ed) user should be added as chat participant

## Actual Result:
The previously tabbed user (or the first user in the list) is also added as a chat participant

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201365423-fdd63702-584c-4c32-beb9-96e45d4d2294.mp4

https://user-images.githubusercontent.com/43996225/201365452-e2db67d5-17a0-44f2-af0e-68b886c84a41.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668120797180049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b28f9ab1fce6c44</li>
        <li>Upwork Job ID: 1699654638568853504</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Keeping on hold as mentioned.

**Comment by mountiny** [comment]
Apologies, I should have commented before. AS listed in the title this is on hold for https://github.com/Expensify/App/issues/11795 which is tracking similar issues related to option list selectors like this one. We plan to take a step back and predesign how this should behave and look throughout the App.

**Comment by kadiealexander** [comment]
Sounds good, thank you!

**Comment by kadiealexander** [comment]
Still on hold, Melvin.

**Comment by kadiealexander** [comment]
Movement is happening on the PR that is holding this up.

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
@mountiny I can't see any latest updates in the linked issue, could you please give me a rough idea of what's happening here?

**Comment by mountiny** [comment]
Yeah so this will be on hold for WAQ and then we need to design how the option lists should work across the App and this navigation would be in there I think you can make this Monthly just fine 🙌

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Still on hold (https://github.com/Expensify/App/issues/11795 still being worked on)

**Comment by kadiealexander** [comment]
Still on hold.

**Comment by kadiealexander** [comment]
Same as above!

**Comment by kadiealexander** [comment]
Still on hold.

**Comment by kadiealexander** [comment]
Still on hold

**Comment by kadiealexander** [comment]
Still on hold!

**Comment by kadiealexander** [comment]
@mountiny would you happen to know where we are at with this one?

**Comment by mountiny** [comment]
cc @thiagobrez would you be able to check out this bug and give ETA of when if this will be resolved with the refactor?

**Comment by thiagobrez** [comment]
Hey @mountiny! This is already handled by the new implementation, so it should be just a matter of switching the old list component for the new one. I actually already have this page replaced in a local branch for phase 3 of the refactor. I could be sending the fix for this as soon as Monday, due to the rest of this week being off to RNEU, does that sound good?

**Comment by mountiny** [comment]
Sounds great, I actually think we can just go ahead with paying out the reporting bonus here $250 to @huzaifa-99 cc @kadiealexander and then close this one out

**Comment by mountiny** [comment]
Ready for payment

**Comment by kadiealexander** [comment]
Sorry @mollfpr was just needing the Upwork link!

**Comment by kadiealexander** [comment]
@huzaifa-99 please let me know when you've accepted the offer!

**Comment by thiagobrez** [comment]
@mountiny There's a small issue here. I could easily replace the list with the new component to fix the mentioned bug, but that would imply the New Group list following the new designs. @shawnborton mentioned [here](https://github.com/Expensify/App/issues/20353#issuecomment-1618266645) and [here](https://github.com/Expensify/App/issues/20354#issuecomment-1649909567) that we shouldn't use it for the New Group page yet.

Shawn, sorry for bothering again with this. Do we have any updates, or how do you guys want to proceed?

As a last resort I could leave the old list component and just apply the patch to make the Tab selection work correctly, but I don't think that's ideal. I would prefer transitioning to the new component in as many places as possible, so we could deprecate/remove the old one sooner and avoid two sources of bugs.

**Comment by mountiny** [comment]
@thiagobrez I actually think it might be worth waiting for an updated global create in this case. I think you can focus on other tasks in the refactor and this one leave for later, we will pay this out for reporting and rest can be discussed on your issue, I think

**Comment by thiagobrez** [comment]
Works for me @mountiny. Just a final clarification, so I should also hold on the New Chat replacement, because there will be a global create for both chats and groups, right?

**Comment by mountiny** [comment]
Yes

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @huzaifa-99

Upwork job is [here](https://www.upwork.com/jobs/~014b28f9ab1fce6c44).
