### ISSUE TITLE
Request a call - User receives two error messages after inputting an invalid number & deleting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New Expensify App
2. Sign into a valid user with a workspace
3. Tap on Profile > Workspace > "?" icon
4. Tap on Request a setup call
5. Input an invalid number in the Phone number section (For example: 1111111) and tap Call me button
6. Delete the number leaving only one digit

## Expected Result:
The user expects to receive only one error message for invalid number during the entire process

## Actual Result:
The user ends up receiving a second error message for no apparent reason

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201394212-c941b984-6a49-4f52-a121-6b07a88e0a9e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Doesn't look like a bug to me.

**Comment by trjExpensify** [comment]
Same. I'm confused how this is a bug? They didn't clear the invalid input fully and resubmit the form, so the error message remained?

**Comment by thesahindia** [comment]
> They didn't clear the invalid input fully and resubmit the form, so the error message remained?

Correct, let's close this?

**Comment by trjExpensify** [comment]
Yup, closing!
