### ISSUE TITLE
Remove all uses of FetchFreePlanVerifiedBankAccount

### ISSUE THREAD

**Issue by ctkochan22** [Expensify/App#12684]
Replaced all the uses of FetchFreePlanVerifiedBankAccount in app for the API Refactors: https://github.com/Expensify/Expensify/issues/226858

Now remove all the unused code and tests

**Comment by ctkochan22** [comment]
There is a deploy blocker that may have been caused by one our PRs. I'm currently looking into that before removing methods: https://github.com/Expensify/App/issues/12670

**Comment by JmillsExpensify** [comment]
Gotcha, thanks for closing the loop. Makes sense.

**Comment by ctkochan22** [comment]
Blocker might have been due to something else, and we are deploying app. Drawing up this PR now.

**Comment by JmillsExpensify** [comment]
Thanks so much for closing the loop here!
