### ISSUE TITLE
Clicking on context menu item does nothing.

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#12685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is a soon to be deploy blocker.

## Action Performed:

On `main` only (so far)

1. Go to a chat
2. Hover over a message
3. Click copy link

## Expected Result:
Link should be copied
## Actual Result:
Link isn't copied and context menu re-renders itself.

## Workaround:
NA

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** v1.2.27-0
**Reproducible in staging?:** No
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/29673073/201416177-bb5e2f61-6512-4036-8abd-f6711d8c236c.mov

Upwork job post: https://www.upwork.com/ab/applicants/1598818260996956160/job-details
External upwork post: https://www.upwork.com/jobs/~0102eb28ae713f73b5

**Comment by kbecciv** [comment]
QA team is reported in there end as well.

https://user-images.githubusercontent.com/93399543/201421920-b10394dd-4f40-4d30-9dbb-e671b0f21ec8.mp4

**Comment by kbecciv** [comment]
Thank you @rushatgabhane Going to do that now

**Comment by getusha** [comment]
@rushatgabhane  Unable to reproduce after applying the fix.

**Comment by getusha** [comment]
[Screencast from 11-11-2022 11:25:04 PM.webm](https://user-images.githubusercontent.com/75031127/201426115-637852f9-1ef0-4adc-a4ec-dc5ca78a8499.webm)

**Comment by parasharrajat** [comment]
Don't forget to comment on the the original issue which caused this regression.

**Comment by getusha** [comment]
@rushatgabhane  is this issue producible after applying the fix?

**Comment by parasharrajat** [comment]
That works too.

**Comment by sakluger** [comment]
@rushatgabhane what's the status here?

**Comment by sakluger** [comment]
Perfect, thanks so much for the summary @rushatgabhane. I've created the Upwork job (https://www.upwork.com/jobs/~0102eb28ae713f73b5) and hired Aimane.

@aimane-chnaif once you accept the job in Upwork, I can pay out the reporting bonus.

**Comment by sakluger** [comment]
Thanks! All paid up.
