### ISSUE TITLE
Chat- Unable to select any option in mini content, the menu moves up when trying to hover over it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12606

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Select any user and send few messages
4. Hover over some messages in the report
5. Select any option from mini content

## Expected Result:
 Able to select any option in mini content, the menu doesn't  move up when trying to hover over it

## Actual Result:
 Unable to select any option in mini content, the menu moves up when trying to hover over it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.27.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201424873-97cc5ebf-5c51-49e4-9d51-3ab73a0cd040.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This bug is kind of funny 😆 the escaping menu

**Comment by kbecciv** [comment]
Sorry, I don't have access to Slack.

**Comment by sakluger** [comment]
So sorry @adeel0202, not sure how I missed these alerts. Here's the Upwork job post, I've sent you an offer:

Internal: https://www.upwork.com/ab/applicants/1599883398869901312/job-details
External: https://www.upwork.com/jobs/~01ae3def7b7322b4de

**Comment by sakluger** [comment]
The reporting bonus has now been paid, so I think we're all set here!
