### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] The error when enter invalid debit card information still appear after reload the page reported by @hans

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to Profile > Payment, click "Add payment method", choose "Debit card"
2. Enter some random information and press "Save", you will see the error appear at the bottom, reload the page.
3. Notice that the error still appear.

## Expected Result:  
Error text at the bottom should disappear after reload the page

## Actual Result: 
Error text at the bottom still appear after reload the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201453294-396f1eba-a6ba-449d-8486-4a8647cb085a.mov

https://user-images.githubusercontent.com/43996225/201453301-a1ad84d3-32ba-4c80-b723-8629e23384c2.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @hans

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668187065943279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal


We clear the error at componentWillUnmount but it doesn't get invoked on refresh
https://github.com/Expensify/App/blob/0d653cad15c32150c302ac12dc0acdbca1ece18b/src/pages/settings/Payments/AddDebitCardPage.js#L58-L59

we need to add  `PaymentMethods.clearDebitCardFormErrorAndSubmit();` at constructor to fix this

**Comment by CortneyOfstad** [comment]
Definitely appears to be an issue. Going to assign engineering to see if this needs to be Internal or External. Thinking External, but want a second pair of eyes to be sure.

**Comment by NikkiWines** [comment]
Looks like a good external issue! Applying the appropriate label

**Comment by thesahindia** [comment]
@Puneet-here's [proposal](https://github.com/Expensify/App/issues/12693#issuecomment-1312396358) looks good, but I don't have my mac right now so I haven't tested it. I will test this in the morning.

**Comment by hungvu193** [comment]
Hello there, I'm the reporter of this bug, can you assign me as well?
Seem @kavimuru tagged the wrong person. Here's the slack thread (https://expensify.slack.com/archives/C049HHMV9SM/p1668187065943279).
Should I change my slack name to the same with github name to avoid this?

**Comment by thesahindia** [comment]
@luacmartins, I like @Puneet-here's [proposal](https://github.com/Expensify/App/issues/12693#issuecomment-1312396358).

C+ reviewed 🎀👀🎀

**Comment by thesahindia** [comment]
> The PR that introduced the bug has been identified. Link to the PR:

Not applicable ? It was an edge case  ( more of a feature request ) and it was missed in the refactor

**Comment by CortneyOfstad** [comment]
Tackling my checklist today 👍

**Comment by hungvu193** [comment]
Can I have reporting bonus for this issue?

**Comment by CortneyOfstad** [comment]
Will have this paid by EOD today 👍

**Comment by CortneyOfstad** [comment]
Job posting — https://www.upwork.com/jobs/~018c9998e3f5f89303

@hungvu193 @thesahindia @Puneet-here — I've sent over the contracts. Once those are accepted, I will get that payment sent out by EOD today 👍 

Thanks!

**Comment by CortneyOfstad** [comment]
Payments have been sent! Thanks!

**Comment by Puneet-here** [comment]
@CortneyOfstad, this is eligible for 50% bonus.

**Comment by CortneyOfstad** [comment]
@Puneet-here Who is it eligible for? Sorry, this is my first time doing a payment.

**Comment by Puneet-here** [comment]
For reviewer and contributor who fixed this issue. 
It is written in this [section](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions)
<img width="858" alt="Screenshot 2022-11-30 at 6 49 58 PM" src="https://user-images.githubusercontent.com/101883770/204806771-497ad0f7-9825-472c-9a1b-93c34fbfa3ef.png">

**Comment by CortneyOfstad** [comment]
Sorry about that! @Puneet-here @thesahindia — I extended another contract for the bonus amount. I'll keep an eye on my email to see when you accept and I'll get that paid ASAP 👍

**Comment by Puneet-here** [comment]
Accepted the offer, thanks!

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by CortneyOfstad** [comment]
Thank you!! Both have been paid for the bonus 👍

**Comment by thesahindia** [comment]
Let's close the issue.
