### ISSUE TITLE
 Being assigned 1-2-1 users when not logged into New Dot Reported by Guides Team

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12694]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  signed out of New Dot yesterday around 6 PM EST 

## Expected Result: 
To not be assigned a user while out of New Dot

## Actual Result: 
I was assigned several users from 6pm until 5 am this morning

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Screenshot (151)](https://user-images.githubusercontent.com/43996225/201453671-201b6458-fa00-4157-9ef9-5f8eb8a4587f.png)
![Screenshot (150)](https://user-images.githubusercontent.com/43996225/201453673-1b9631b7-d2a2-43ca-ae71-921a113e9061.png)
![Screenshot (149)](https://user-images.githubusercontent.com/43996225/201453674-dad2efb5-a577-4e53-872d-6dacbad01cbd.png)
![Screenshot (148)](https://user-images.githubusercontent.com/43996225/201453676-3878147f-97b9-4f75-b3ff-f876f13f3077.png)
![Screenshot (147)](https://user-images.githubusercontent.com/43996225/201453678-4bd4f7c7-d013-49f1-b01e-ac2dd67034f0.png)
![Screenshot (146)](https://user-images.githubusercontent.com/43996225/201453679-d1e075a5-22c1-4722-a3a4-7dfcaf626214.png)
![Screenshot (145)](https://user-images.githubusercontent.com/43996225/201453680-558bc480-e808-4773-a2fc-5e6258977e0a.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Guides Team
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1668102491670949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Not overdue. Just assigned last night.

**Comment by joekaufmanexpensify** [comment]
Not sure this is actually a bug. Chatting with the guide in the [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1668102491670949) where this was raised. If it is actually a bug I will re-open.
