### ISSUE TITLE
Payment with PayPal.me could be labelled as paid without any payment issued from PayPal reported by @kerupuksambel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/) from an account (Account A)
2. Set a PayPal.me account in Account A
3. Request some amount of money to another account (Account B)
4. From Account B, pay the account with using PayPal.me
5. After the PayPal.me tab showed up, close the tab

## Expected Result : 
The money request shouldn't be labelled as paid, since there are no transaction occurred from PayPal side

## Actual Result : 
The money request labelled as paid

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:**y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201694269-d0e72b59-252c-43d3-b4af-519e4438c4fb.mp4

https://user-images.githubusercontent.com/43996225/201694342-3e0e2eb2-3dbe-4df3-a34f-76aff27e768e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668300730482609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
OK, so for the invoice to be marked immediately as paid is expected based on this [Community](https://community.expensify.com/discussion/7428/how-to-pay-get-paid-for-invoices-and-bills-using-paypal-me-and-expensify) article. At the bottom of the article:

>Please note, the invoice will be marked as PAID as soon as you click the green button. Do not select Pay until you're ready to follow through with the payment!

I tested this flow and it works the same as OldDot — when payment is made, the user is sent to their PayPal.me link:

https://user-images.githubusercontent.com/38236554/201943407-49f92223-ef1a-4dc4-9715-3d45232b0c0a.mp4

**Comment by bfitzexpensify** [comment]
When we created the PayPal integration, we did so knowing that it wasn't possible to bring across the payment status via PayPal. I don't think that's changed, so this is working as it should, going to close.

**Comment by JmillsExpensify** [comment]
Agree with @bfitzexpensify. This is not a bug, it's the design as this is not an API integration.
