### ISSUE TITLE
[$250] No offline feedback on changing details at profile page reported by @thesahindia

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Disconnect the internet connection
2. Navigate to settings > Profile page
3. Change name > Save

## Expected Result: 
The opacity should decrease like other pages (e.g. workspace settings)

## Actual Result: 
The opacity doesn't change

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201706899-6b8702d6-3ab8-4725-a8a5-abe2cc3815bb.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668374685167069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/201706931-28bd4288-6da8-439b-8f3c-7e34326056bc.mp4

**Comment by stephanieelliott** [comment]
Posted to Upwork: https://www.upwork.com/ab/applicants/1592349112071221248/job-details

**Comment by markarmanus** [comment]
Proposal

Wrapp the fields in the ProfilePage.js under the  the ` <OfflineWithFeedback />` component passing it the proper data from loadash as the pendingAction

This would replicate the behaviour in the Workspace Settings page.

**Comment by tienifr** [comment]
# Proposal

## Problem

We don't mark pendingFields === update when updating the profile and we only wrap avatar under the <OfflineWithFeedback /> component, we should wrap all ProfilePage under the <OfflineWithFeedback /> component

## Solution

when user update profile
in Expensify/App/src/libs/actions/PersonalDetails.js
```diff
function updateProfile(firstName, lastName, pronouns, timezone) {
    API.write('UpdateProfile', {
        firstName,
        lastName,
        pronouns,
        timezone: JSON.stringify(timezone),
    }, {
        optimisticData: [{
            onyxMethod: CONST.ONYX.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS,
            value: {
                [currentUserEmail]: {
                    firstName,
                    lastName,
                    pronouns,
                    timezone,
                    displayName: getDisplayName(currentUserEmail, {
                        firstName,
                        lastName,
                    }),
+                    pendingFields: {
+                       profile: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
+                    },
                },
            },
        }],

```

and then /Expensify/App/src/pages/settings/Profile/ProfilePage.js
we wrap all the rest by the <OfflineWithFeedback /> component like that
```diff
+    <OfflineWithFeedback
+                        pendingAction={lodashGet(this.props.currentUserPersonalDetails, 'pendingFields.profile')}
+                    >
                        <Text style={[styles.mt6, styles.mb6]}>
                            {this.props.translate('profilePage.tellUsAboutYourself')}
                        </Text>

                        <View style={[styles.flexRow, styles.mt4, styles.mb4]}>
                            <View style={styles.flex1}>
                                <TextInput
                                    inputID="firstName"
                                    name="fname"
                                    label={this.props.translate('common.firstName')}
                                    defaultValue={lodashGet(currentUserDetails, 'firstName', '')}
                                    placeholder={this.props.translate('profilePage.john')}
                                />
                            </View>
                            <View style={[styles.flex1, styles.ml2]}>
                                <TextInput
                                    inputID="lastName"
                                    name="lname"
                                    label={this.props.translate('common.lastName')}
                                    defaultValue={lodashGet(currentUserDetails, 'lastName', '')}
                                    placeholder={this.props.translate('profilePage.doe')}
                                />
                            </View>
                        </View>
                        <View style={styles.mb6}>
                            <Picker
                                inputID="pronouns"
                                label={this.props.translate('profilePage.preferredPronouns')}
                                items={pronounsList}
                                placeholder={{
                                    value: '',
                                    label: this.props.translate('profilePage.selectYourPronouns'),
                                }}
                                defaultValue={pronounsPickerValue}
                                onValueChange={this.setPronouns}
                            />
                            {this.state.hasSelfSelectedPronouns && (
                                <View style={styles.mt2}>
                                    <TextInput
                                        inputID="selfSelectedPronoun"
                                        defaultValue={this.pronouns}
                                        placeholder={this.props.translate('profilePage.selfSelectYourPronoun')}
                                    />
                                </View>
                            )}
                        </View>
                        <LoginField
                            label={this.props.translate('profilePage.emailAddress')}
                            type="email"
                            login={this.state.logins.email}
                            defaultValue={this.state.logins.email}
                        />
                        <LoginField
                            label={this.props.translate('common.phoneNumber')}
                            type="phone"
                            login={this.state.logins.phone}
                            defaultValue={this.state.logins.phone}
                        />
                        <View style={styles.mb3}>
                            <Picker
                                inputID="timezone"
                                label={this.props.translate('profilePage.timezone')}
                                items={timezones}
                                isDisabled={this.state.isAutomaticTimezone}
                                value={this.state.selectedTimezone}
                                onValueChange={selectedTimezone => this.setState({selectedTimezone})}
                            />
                        </View>
                        <CheckboxWithLabel
                            inputID="isAutomaticTimezone"
                            label={this.props.translate('profilePage.setMyTimezoneAutomatically')}
                            defaultValue={this.state.isAutomaticTimezone}
                            onValueChange={this.setAutomaticTimezone}
                        />
+                    </OfflineWithFeedback>
```


### Result 

https://user-images.githubusercontent.com/113963320/201854195-842aa033-b13d-43ca-afe3-d2295954d510.mp4

**Comment by Puneet-here** [comment]
### Proposal

When the user updates the profile details we have to add `profileSettings` and set its value to "update" in optimisticData value and when we get 200 response we can set it to null so that when user turns his internet and the profile gets updated it doesn't stay contain value "update". If we don't change the value to null after success we will see the offline feedback whenever user goes offline without even changing anything at profile 

We can make these changes at [PersonalDetails](https://github.com/Expensify/App/blob/376c3327bdc58e0fb15ff31fa7ebba819a680206/src/libs/actions/PersonalDetails.js#L272)
```diff
 function updateProfile(firstName, lastName, pronouns, timezone) {
-    API.write('UpdateProfile', {
-        firstName,
-        lastName,
-        pronouns,
-        timezone: JSON.stringify(timezone),
-    }, {
-        optimisticData: [{
-            onyxMethod: CONST.ONYX.METHOD.MERGE,
-            key: ONYXKEYS.PERSONAL_DETAILS,
-            value: {
-                [currentUserEmail]: {
+    const optimisticData = [{
+        onyxMethod: CONST.ONYX.METHOD.MERGE,
+        key: ONYXKEYS.PERSONAL_DETAILS,
+        value: {
+            [currentUserEmail]: {
+                firstName,
+                lastName,
+                pronouns,
+                timezone,
+                displayName: getDisplayName(currentUserEmail, {
                     firstName,
                     lastName,
-                    pronouns,
-                    timezone,
-                    displayName: getDisplayName(currentUserEmail, {
-                        firstName,
-                        lastName,
-                    }),
+                }),
+                pendingFields: {
+                    profileSetting: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
                 },
             },
-        }],
-    });
- 
+        },
+    }];
+    const successData = [{
+        onyxMethod: CONST.ONYX.METHOD.MERGE,
+        key: ONYXKEYS.PERSONAL_DETAILS,
+        value: {
+            [currentUserEmail]: {
+                pendingFields: {
+                    profileSetting: null,
+                },
+            },
+
+        },
+    }];
+    API.write('UpdateProfile', {
+        firstName, lastName, pronouns, timezone: JSON.stringify(timezone),
+    },
+    {optimisticData, successData});
```

We need to add `<OfflineWithFeedback
                        pendingAction={lodashGet(this.props.currentUserPersonalDetails, 'pendingFields.profileSetting')}
                    >` before line 265
https://github.com/Expensify/App/blob/376c3327bdc58e0fb15ff31fa7ebba819a680206/src/pages/settings/Profile/ProfilePage.js#L265
and `</OfflineWithFeedback>` after line 338 https://github.com/Expensify/App/blob/376c3327bdc58e0fb15ff31fa7ebba819a680206/src/pages/settings/Profile/ProfilePage.js#L338

**Comment by flodnv** [comment]
@eVoloshchak what are your thoughts on these proposals?

**Comment by JmillsExpensify** [comment]
I just commented in the linked issue, so bringing my commentary here. The issue here is that this part of the app isn’t re-factored for offline yet. We are just getting to this refactor, though that hasn’t happened yet, so I wouldn’t consider this a bug. I think we should close this issue.

**Comment by Puneet-here** [comment]
@JmillsExpensify, I think it was already refactored because changing profile details works offline.

**Comment by JmillsExpensify** [comment]
I don't think that's correct, or perhaps more accurately, we are in the midst of re-factoring this entire part of the app. I think we should put this issue on HOLD. @Beamanator can you weigh in as well?

**Comment by Beamanator** [comment]
Yeah the Profile page "has been refactored" when we refactored API commands and it should be working offline (so maybe we need to update this issue title?) but there's another big refactor coming for the Profile page, where we won't have any updating / saving on this page directly

**Comment by Beamanator** [comment]
Also in Slack (see linked thread in OP) we decided we wanted to hold on this right?

**Comment by flodnv** [comment]
We can HOLD on `another big refactor coming for the Profile page, where we won't have any updating / saving on this page directly`, right? If yes, where's that being tracked?

**Comment by Beamanator** [comment]
Technically the tracking issue is here: https://github.com/Expensify/App/issues/11582

This is for all of the Profile page updates, but right now we're only focusing on updating the Display name, Pronouns, and Timezone since contact method changes are holding on #passwordless, and private personal details are not needed for WQA

**Comment by JmillsExpensify** [comment]
I'm kind of one the fence what the best path forward is. I agree with @thesahindia that the current page is not appropriately reflecting "pending" (50% opacity) in the form. However, actually...hmm now that I think of it, isn't the profile Pattern A? Like in what case could updating your name truly fail? Is there one? If not, then no "pending" UX is needed, because we'll always be able to update the name/profile when coming back online. If I'm right there, then closing the issue would be the best path forward. @Beamanator can you confirm whether I have a terrible memory haha, or whether Pattern A is where we landed for this case?

**Comment by Beamanator** [comment]
> can you confirm whether I have a terrible memory haha, or whether Pattern A is where we landed for this case?

Confirming! 👍 So far updating display name, timezone, pronouns are all Pattern A (since they basically can't fail - we have front-end validation to prevent very long display names from being saved). Secondary logins / contact methods will be mainly Pattern B because they "can" fail much easier. So ya I'd say we can close this too 👍

**Comment by JmillsExpensify** [comment]
Awesome, glad to see my memory isn't that bad haha.
