### ISSUE TITLE
Workspace - Paybills - Hovering on example.com@expensify.cash shows as a URL in the bottom left corner and redirects to a page reported by @0xmiroslav

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. Go to Settings -> Workspaces -> Pay bills page
3. Hover example.com@expensify.cash

## Expected Result: 
There should be no URL link shown at the bottom left as it is an email 

## Actual Result: 
Pay bills page url (https://staging,new.expensify.com/workspace/xxx/bills) shows

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/43996225/201740551-2b45c57c-0553-4dfb-beda-14b92647d5b7.png)
<img width="960" alt="Screenshot (99)" src="https://user-images.githubusercontent.com/43996225/201740577-62324e3b-d24e-4ead-a06e-dc5074c7cc39.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668426810134239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
I was not able to reproduce taking the steps outlined above.

@0xmiroslav @kavimuru 
Can you clarify reproduction steps and/or to check the reproduction steps again.

**Comment by abekkala** [comment]
Chrome was used when attempting to reproduce

**Comment by kavimuru** [comment]
@abekkala Video here.

https://user-images.githubusercontent.com/43996225/201760419-31d00408-3c75-48da-910e-1083a58d1e0d.mp4

**Comment by abekkala** [comment]
I am in Chrome Staging taking the same steps provided. I do not receive a URL link shown at the bottom:
![2022-11-15_11-25-08 (1)](https://user-images.githubusercontent.com/11966460/201986240-33e7633e-1056-442a-ad73-abef789ebacb.gif)
