### ISSUE TITLE
Not able to open context menu for a message with right click if one is already open for another message reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12711]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to any chat
2. Right click on a message (the custom context menu will open)
3. Right click on another message (the browser context menu opens)

## Expected Result: 
When right clicked on a different message the previous custom context menu should close and a new one should open for the selected message

## Actual Result: 
The browser context menu opens if the custom context menu is already open and when right clicked on a different message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201715082-eeb2d947-7d5d-4389-ab3f-d4b8d29c2b19.mp4

https://user-images.githubusercontent.com/43996225/201715105-0ab65500-ecf1-4479-a5fe-4a3c8595d399.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668378442909859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
I think we disabled that intentionally for some reason. I can't remember the PR or details. Please do that the old PR which disabled it.

**Comment by sophiepintoraetz** [comment]
CHecking [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1668566564869639).

**Comment by JmillsExpensify** [comment]
Commented in Slack. I have a similar memory as @parasharrajat, though I can't remember the specifics other than this was a cross-platform implementation consideration.

**Comment by parasharrajat** [comment]
Here are the details as promised. 

The issue : https://github.com/Expensify/App/pull/8815#pullrequestreview-957629194
Suggested : https://github.com/Expensify/App/pull/8815#issuecomment-1114895399
Decided: https://expensify.slack.com/archives/C01GTK53T8Q/p1651508643094319 https://github.com/Expensify/App/pull/8815#issuecomment-1117653182

**Comment by sophiepintoraetz** [comment]
Agreed in the slack thread that this is a trade off we actively decided on (due to this issue [here](https://github.com/Expensify/App/issues/12711#issuecomment-1319160728), we decided that the user has to manually close the right-click modal)  - so closing this issue out
