### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] [Cleanup] Remove unnecessary BasePicker component

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
The `Picker` component has an internal `BasePicker` component that's not necessary / serves no purpose, since `Picker` itself does not provide multiple platform-specific implementations.

### Solution
Remove the `BasePicker` component and just implement its functionality directly in `Picker`.

Note you really only need to provide testing steps and screenshots for [this draft PR](https://github.com/Expensify/App/pull/12725)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
@roryabraham , can I test this?

**Comment by davidcardoza** [comment]
Job posted - https://www.upwork.com/jobs/~015fc187d3b8e60dfa

**Comment by Puneet-here** [comment]
I have raised the PR and applied to the job.

**Comment by davidcardoza** [comment]
Hired @Puneet-here

**Comment by roryabraham** [comment]
@davidcardoza do we need to reopen this for payment once https://github.com/Expensify/App/pull/12736 has been deployed to prod for a week?

**Comment by roryabraham** [comment]
I'm not exactly sure why melvin closed this issue when he did

**Comment by davidcardoza** [comment]
@roryabraham Yeah we do. Thanks for reopening.

**Comment by roryabraham** [comment]
This is ready for payment

**Comment by davidcardoza** [comment]
payment sent @Puneet-here

**Comment by eVoloshchak** [comment]
@davidcardoza, I reviewed the [PR](https://github.com/Expensify/App/pull/12736), but didn't get the payment.
This is the first PR I reviewed that hit production, so I'm not familiar with the process. Should I tag CME (BZ?) in the issue I reviewed the PR for?

**Comment by roryabraham** [comment]
Reopening for C+ payment.

@eVoloshchak the BugZero assignee handles payments, so they're the best person to tag. I recommend tagging people in the issue, not the pull request.

**Comment by eVoloshchak** [comment]
> @eVoloshchak the BugZero assignee handles payments, so they're the best person to tag. I recommend tagging people in the issue, not the pull request.

Thanks for clarifying!

**Comment by davidcardoza** [comment]
@eVoloshchak sent

**Comment by eVoloshchak** [comment]
> @eVoloshchak sent

Accepted
