### ISSUE TITLE
Keyboard doesn't disappear when switch screen mode from landscape to portrait reported by @aimane-chnaif

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in landscape 
2. Open a chat and type something in the compose box
3. Switch to portrait 

## Expected Result:
Keyboard disappear

## Actual Result:
Keyboard does not disappear

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS - iPad

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201757323-5fe59b37-b38a-4948-9e45-6027465abef5.MP4
https://user-images.githubusercontent.com/43996225/201757362-a86430a7-e7da-4673-8220-bc7130bda037.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668436413524359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://www.upwork.com/jobs/~012fa3bae9c27d0eb4

**Comment by kevinksullivan** [comment]
@aimane-chnaif sent offer for reporting!

**Comment by IvanDuran02** [comment]
Using the keyboard and Dimensions component from react-native library we can check the dimensions of the device. If the device is longer than tall we can assume its landscape and vice versa. From there we can add an eventListener to close the keyboard when the dimensions change.

I have a working prototype in my fork.

**Comment by RoshaanAli** [comment]
Proposal
I will check orientation using react-native dimensions builtin library. Then when orientation get change i will add listener which will going to close the keyboard... It will work in all scenarios when ever screen orientation changes

**Comment by JmillsExpensify** [comment]
Based on our discussion [in the community](https://expensify.slack.com/archives/C01GTK53T8Q/p1668811497897899?thread_ts=1668640125.477709&cid=C01GTK53T8Q), I'm going to close this issue. Given that tablets are not an officially supported platform, this issue is more accurately a new feature request than a bug.

**Comment by kevinksullivan** [comment]
@aimane-chnaif I will pay reporting but you have to accept. Please comment once you've done so.

**Comment by kevinksullivan** [comment]
All set.
