### ISSUE TITLE
[$750] Clean Up Comments in PaymentMethods.js and Remove NewDot personal bank account password field

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#12731]
This has already been finished, opening this issue to track payments for C+ who has reviewed and tested this PR https://github.com/Expensify/App/pull/12297

Previously we had this internal issue https://github.com/Expensify/Expensify/issues/233288 but we cannot assign C+ to it.

@mananjadhav What is the compensation appropriate for the PR review? 

Lets also pay Mana for this issue https://github.com/Expensify/Expensify/issues/238629 and its [associated PR](https://github.com/Expensify/App/pull/12175) which he has reviewed and tested.

**Comment by mananjadhav** [comment]
@mountiny I think 250$ is fine, this was a small PR.

But I also have this one https://github.com/Expensify/App/pull/12175 where I put more effort in testing the workflow. Are we tracking that in a separate issue? Because that is also an internal issue but I haven't got any response yet.

**Comment by mountiny** [comment]
@mananjadhav apologies for that, I thought we have gone with open contracts solution for the reviews. For any PR review/testing is you compensation part of the App issue it is linked to?

**Comment by mountiny** [comment]
I have updated the PR and this issue to reflect that this will cover payment for that C+ review too

**Comment by mananjadhav** [comment]
I've got multiple PRs for which payment is pending but none of them have got linked issues (not atleast on the App side). Except these two I guess the others are being addressed.

**Comment by mountiny** [comment]
Ok, I thought this was fleshed out better, hopefully there is not many PRs which only have Expensify repo issues.

Howe much do you reckon for the other PR?

**Comment by mananjadhav** [comment]
> Ok, I thought this was fleshed out better, hopefully there is not many PRs which only have Expensify repo issues.

Yeah I thought so too.

> Howe much do you reckon for the other PR?

I think for that one 500$ should be fine, because it required the whole Bank Account flow to be tested and it takes few rounds to test multiple scenarios.

**Comment by mountiny** [comment]
@flaviadefaria Could we please create UW contract for Manan for $750 for reviewing and testing https://github.com/Expensify/App/pull/12175 and https://github.com/Expensify/App/pull/12297? 🙌 thanks

**Comment by mountiny** [comment]
@mananjadhav sorry, Flavia has been ooo Monday and Tuesday, should have checked that. She should be back today

**Comment by flaviadefaria** [comment]
Internal post - https://www.upwork.com/ab/applicants/1592815895728955392/job-details
External post - https://www.upwork.com/jobs/~018dcdf3bf43a9755f

**Comment by flaviadefaria** [comment]
@mananjadhav can you please apply to the job using the external link above? Thanks!

**Comment by flaviadefaria** [comment]
@mananjadhav I just paid you so closing this issue.
