### ISSUE TITLE
[HOLD for retest] Remove html from Close Account errors

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#12747]
# Problem:

In the past, we didn't show errors that occurred when a user tries to close their account. Instead, we displayed a generic error modal. As of this issue: https://github.com/Expensify/App/issues/11341, we're planning to get ride of that modal and show the error that occurred. Some of these error messages have `<p>` before / after the error message ([example](https://github.com/Expensify/Web-Expensify/blob/22fc89cef86dcaafeaedcbcd3b39c637cdbceff4/lib/Error/User/Undeletable.php#L46-L47)), which doesn't look good in NewDot

# Solution

Let's make sure that Close Account error messages that are shown in NewDot look good!

**Comment by Beamanator** [comment]
Maybe this should be WAQ? Since these errors will now show directly in NewDot? cc @JmillsExpensify (also do you prefer being tagged like this or just having the issue directly added to WAQ project?)

**Comment by JmillsExpensify** [comment]
I'm fined being tagged! It's good to keep track of these kinds of discussions. Also tagging @trjExpensify as we have alternating holiday time between now and the end of the year, and will be subbing in and out for each other.

**Comment by JmillsExpensify** [comment]
In general, I think this is a good candidate for WAQ, because the refactors precede WAQ from a roadmap perspective, and that makes this an existing issue that should be fixed.

**Comment by JmillsExpensify** [comment]
That said, I do wonder if it's better to not solely focus on the close account errors, but instead, errors more generally. I can only imagine that this problem with HTML formatting is going to surface in more parts of the app. I pretty much bet it is.

**Comment by Beamanator** [comment]
> That said, I do wonder if it's better to not solely focus on the close account errors, but instead, errors more generally. I can only imagine that this problem with HTML formatting is going to surface in more parts of the app. I pretty much bet it is.

Fair, but I'm also potentially thinking that refactoring errors elsewhere is only "necessary" once those errors start showing up in the App. Similar to how we only did API refactors for commands that we use in the App. Know what I mean? Or is this way different since this issue is a much much smaller scope (just making sure HTML tags get stripped from error messages heading to NewDot) :D 

Thinking a bit while typing, I actually think we could probably have a pretty simple generic solution that would do ^ (any errors sent to NewDot would have HTML tags stripped from the beginning & end)

**Comment by trjExpensify** [comment]
I agree with that. One thing to add to this is that in the past we haven't been able to add server errors in-line on forms. @ctkochan22 has been working on an issue where we're making that happen, but if we're updating error messages let's make sure they are placed contextually in-line.

**Comment by Beamanator** [comment]
> One thing to add to this is that in the past we haven't been able to add server errors in-line on forms.

Good to know, hadn't thought about that before.

> So are we saying that we should redo this entirely and bring the error in-line instead?

Also a good question, the original purpose of this issue was to keep the form errors where they are, just remove the HTML tags from them (as luck would have it, Applause just created this issue (https://github.com/Expensify/App/issues/13153) which has a video of Close Account errors with HTML tags). 

@trjExpensify are you suggesting we move where the error shows or were you just pointing that out for context?

**Comment by trjExpensify** [comment]
Yeah, so I think it's fine to separate out the initiatives if we want to fix the HTML tags on all error messages we display in App as a first step. You're right it's probably better to split up the work and do that first, before updating the placement. 

On that though, we do have growing inconsistency in NewDot now, and we should address that at some point:

- Front-end errors are displayed in-line
- Pattern B's "pending > failed" red brick road errors are displayed in-line
- Server-side errors are anchored to the bottom of forms

**Comment by Beamanator** [comment]
> - Pattern B's "pending > failed" red brick road errors are displayed in-line

Woah, really? Just wondering do you have an example of this happening right now? I thought Pattern B errors were from the server-side so I assumed they were also anchored to the bottom of forms - but maybe i've been staring at Account Settings & Image changes for too long 😅

**Comment by Beamanator** [comment]
Ohhh ok I was taking "in-line" and assuming you were saying like "in-line in a Form" (woah you took a screenshot of a video... I was confused why it wouldn't play). The interesting thing about the error you just showed, is it's a generic error that comes from the front end ([here](https://github.com/Expensify/App/blob/eb0110d8d2bc2d1ed00828a1c9efdcbb6a8929d7/src/languages/en.js#L861)) but we also throw an error from the back end ([here](https://github.com/Expensify/Web-Expensify/blob/b62316e37f9d7f52c6c6a8a5a8146c9223c8d46c/lib/PolicyAPI.php#L1080-L1082)) so that's a bit funky

**Comment by Beamanator** [comment]
> I think that should be WAQ agreed, and we can proceed with that in isolation for the time being.

Ok sweet I added this to WAQ

@trjExpensify let me know if there's something else we were discussing about inline errors vs not that you'd like a reply on, I'm a bit lost with that part of the convo sorry 😅

**Comment by Beamanator** [comment]
Unassigning myself to be able to put more focus on my other tasks - dropped a note in #engineering-chat to try to get more 👀

**Comment by neil-marcellini** [comment]
Hey @robertjchen I wasn't aware of this issue until I saw it in your Slack WAQ status. I'm currently reviewing [this PR](https://github.com/Expensify/Web-Expensify/pull/35198) which is solving this issue.

**Comment by JmillsExpensify** [comment]
So should we put this issue on HOLD until your PR hits and then re-test? Or close this issue outright?

**Comment by robertjchen** [comment]
Oh nice, thanks for the heads up! I've added this GH issue to the list in the PR (which doesn't seem to be tied to an issue at the moment) and will re-test things once it goes out. Will add a HOLD for now 👍

**Comment by robertjchen** [comment]
PR went out, going to re-test and close after confirmation.
