### ISSUE TITLE
[Hold #12775] Workspace - Add/removed a member offline flickers before getting disappeared when back online reported by @daraksha-dk

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app > Open any Workspace > Go to Manage members
2. Go offline
3. Invite and remove a member while offline
4. Go online
5. The deleted member will > 1. disappear 2. appear 3. disappear

## Expected Result:
Deleted members should be removed once they are online without flickering

## Actual Result : 
It is flickering after being deleted

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Mobile Web

**Version Number:** 1.2.27-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202005836-8a92633b-6a99-40f3-9de9-2edd23491eb0.mp4

https://user-images.githubusercontent.com/43996225/202005862-a05e6128-63c7-4a2e-bac4-31da358f5453.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668527213425219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Have asked about this internally [here](https://expensify.slack.com/archives/C03U7DCU4/p1668563781304899) to ensure the solution aligns with our agreed framework.

**Comment by JmillsExpensify** [comment]
Putting this issue on hold for the time being. Please see [tracking issue](https://github.com/Expensify/App/issues/12775) for more context.

**Comment by JmillsExpensify** [comment]
See the linked issue recent commentary.

**Comment by JmillsExpensify** [comment]
Still on hold based on the linked tracking issue.

**Comment by JmillsExpensify** [comment]
Still on hold for WAQ.

**Comment by JmillsExpensify** [comment]
Still held

**Comment by JmillsExpensify** [comment]
Still on hold, same as the tracking issue.

**Comment by trjExpensify** [comment]
Still held on the linked tracking issue.

**Comment by trjExpensify** [comment]
No change, Melv.

**Comment by neil-marcellini** [comment]
Fixed!


https://github.com/Expensify/App/assets/26260477/1c8333f0-9f3a-4442-869d-ff49c6204329
