### ISSUE TITLE
[Plan] Think about having new Pronoun & Timezone pages scroll to selected items on render

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#12757]
Idea from @thesahindia here: https://github.com/Expensify/App/pull/12301#issuecomment-1315758878

Holding on implementation of new timezone pages: https://github.com/Expensify/App/pull/12201

**Comment by Beamanator** [comment]
Possibly useful SO for scrolling: https://stackoverflow.com/questions/43452859/react-native-sectionlist-scroll-to-section

**Comment by cristipaval** [comment]
Wait, Melvin! Start counting a month from now.

**Comment by cristipaval** [comment]
I'll get back to this soon, most probably I'll offload this to Callstack

**Comment by cristipaval** [comment]
This is already implemented.
