### ISSUE TITLE
[$1000] Web-  Chat - Markdown styles (Bold, Italic) are not retained if copy-paste message from draft

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open any chat
3. Copy message from Slack compose box with Bold and Italic markdown
4. Past it to NewDot compose box

## Expected Result:
Markdown styles (Bold, Italic) should be the same after copy-paste message from Slack

## Actual Result:
Markdown styles (Bold, Italic) are not the same if copy-paste message from draft. However they are kept the same when copy a sent message.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.28.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202209938-e61b178b-3222-47e4-8e54-e808b94b8229.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01d2b138ae1bc9b751
- Upwork Job ID: 1594824268879978496

**Comment by thesahindia** [comment]
Thanks @eh2077, I agree this isn't a bug. I am seeing the same behaviour on https://stackedit.io/app#

**Comment by s77rt** [comment]
Should this be closed?

**Comment by thesahindia** [comment]
@jasperhuangg @tjferriss, let's close this.
