### ISSUE TITLE
Web - Chat - Only one file is uploaded when several together are dragged and dropped

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open any chat
3. Select several files in the folder and drag&drop them to chat

## Expected Result:
All chosen files should be uploaded into the chat

## Actual Result:
Only one file is uploaded into the chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.28.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202207564-f682beec-405f-4d85-aa5f-121c2142240a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Not a bug, we don't support this yet (so this is expected). We discussed this last a [few months ago ](https://expensify.slack.com/archives/C01GTK53T8Q/p1651010043230409) and though we're anticipating doing it at some point, that suggestion hasn't been made yet, and will warrant a bigger discussion re:priority internally.
