### ISSUE TITLE
 No splash screen appears when opening the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #12334
## Action Performed:
1. Open the application on web or desktop

## Expected Result:
Verify that splash screen appears for 1.5s and no blank screen is visible

## Actual Result:
No splash screen appears for 1.5s and blank screen is visible.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App - Blocked with blocker issue, could not check
- Mobile Web

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202272111-39fb84d3-7260-4fed-a39a-db3bee7ae62d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
I don't think this is a bug, the splash screen is there while things load, if in web/desktop things load so fast the splash screen is not needed, then that's great.
I think we should close this.

**Comment by johncschuster** [comment]
I agree with you, @iwiznia. It looks like the page loaded so quickly that the splash screen didn't have time to load.

I'm going to close the issue.
