### ISSUE TITLE
[HOLD] [$250] Blockquote markdown is inconsistent between platforms reported by @0xmiroslav 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account on iOS app
2. Go to any chat room
3. Type and send this message: ( Leave a blank line in between "Test1" and ">Test2)
Test1

> Test2
4. Visit https://staging.new.expensify.com/, go to this chat room and check this message

## Expected Result:
Should appear with a blank line in between  "Test1" and ">Test2

Test1

> Test2

## Actual Result:
Appears with a line break

Test1
> Test2

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
<img width="960" alt="Screenshot (101)" src="https://user-images.githubusercontent.com/43996225/202245195-0c5cfe16-d202-4be7-842e-7edc52cc5294.png">

https://user-images.githubusercontent.com/43996225/202245258-d00268a7-6b7c-4f40-8829-fe279f711e45.mov

 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668592487046109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Not sure why the Bug label didn't auto-assigned. Re-applied so that we get an assignment.

**Comment by abekkala** [comment]
@alex-mechler I wanted to quickly assign the engineering label to get your opinion on this irt if this is something we care enough about to move forward. it seems rather low priority to me but would like your input.

**Comment by JmillsExpensify** [comment]
@abekkala did you see my comment in the linked Slack thread? It's a bug, we need to fix it.

**Comment by alex-mechler** [comment]
Based on some limited testing, I think this is actually a bug with iOS, not web. When I send 

```
test 1

> test 2
```
from desktop > web or vice versa, it shows with no space between the two on both platforms. I think its iOS that is improperly displaying it. I'm curious to see if this persists on iOS _after_ refreshing the chat. I will test that today

**Comment by alex-mechler** [comment]
Okay, after some testing on android and iOS, both show the blank line 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/22447860/202516766-65916fd7-af65-41d5-8595-32605132c2f4.png">

Given that a test with _no_ blank line in the middle properly shows as not having an extra blank line, it does actually feel like Web / Desktop are the problem here. Will update OP to add desktop, and then this can be worked on externally, as it's a display issue with web / desktop

**Comment by abekkala** [comment]
https://www.upwork.com/ab/applicants/1593298869518106624/job-details

**Comment by fabiocberg** [comment]
Hi, my name is Fabio, I've been working as a web, backend and mobile developer for over 16 years.
I can help you blockquote markdown issue.
It's necessary to change the break line character according to the platform.

Best regards,
Fabio Bergmann

**Comment by JmillsExpensify** [comment]
@alex-mechler thanks a ton for helping us down the right path. 

@fabiocberg Sounds great! Can you make sure to follow [our guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) for posting an idea, and specifically a proposal for this issue?

**Comment by bernhardoj** [comment]
I think this issue is part of this [issue](https://github.com/Expensify/App/issues/12120).

**Comment by MonilBhavsar** [comment]
@robertjchen @Santhosh-Sellavel Please hold on this as there is a similar issue https://github.com/Expensify/App/issues/12120 and we might want to fix this issue there only.

**Comment by robertjchen** [comment]
Looks like the other issue https://github.com/Expensify/App/issues/12120 was closed out as not being a bug, does this apply here as well?

**Comment by JmillsExpensify** [comment]
Yes, agreed. When this bug was originally filed, we didn't have this understanding and agreement in place. 

> so long as the edited version is semantically the same as the original (eg, both produce the same HTML), it's not a bug

Accordingly, I think we should close this one as well based on our updated discussion and approach.
