### ISSUE TITLE
[HOLD for payment 2022-11-29] [$1000] App crashes when create new chat with the contact who has deprecated pronoun - reported by @aimane-chnaif

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#12795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Click FAB icon -> New chat
3. Enter kbecciv+1031abb2@gmail.com (has deprecated pronoun - Ze/hir) and select that contact

## Expected Result:
New chat created with that user

## Actual Result:
App crashes

## Workaround:
None (well, get the person to change their pronouns presumably)

## Platform:

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.28-2 (reproducible in dev only but will be deploy blocker soon)
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/16232057/202279299-60484fd0-e325-41e6-8331-095e578047d5.mp4

Regression from [this PR](https://github.com/Expensify/App/pull/12301) CC: @Beamanator 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668625056676409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Based on [this discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1668625056676409), @aimane-chnaif want to add your proposal here so we can keep this moving before it gets to staging and becomes a deploy blocker?

**Comment by AndrewGable** [comment]
Can you add a space? Otherwise yes: `zeHirHirs: 'Ze / hir',`

**Comment by Beamanator** [comment]
Agreed & Let's capitalize `Hir` but I'd say we're ready for PR 👍

**Comment by trjExpensify** [comment]
Neat! @aimane-chnaif can we get a the PR up and merged for this right away today? Happy to increase the bounty to $1k if we can.

**Comment by AndrewGable** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Alrighty, ready to pay this one out @aimane-chnaif. We quick stepped it, so there wasn't a job for it. Just sent you a contract to accept on Upwork.

**Comment by trjExpensify** [comment]
Cool, paid! 🎉
