### ISSUE TITLE
Create an S3 bucket for ad-hoc app builds

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#12791]
Coming from https://expensify.slack.com/archives/C04878MDF34/p1668609733417379

### Problem

We are exploring solutions to make testing PRs on all platforms easier and faster via a CI workflow that does ad-hoc builds for all PRs. We need a place to store these ad-hoc builds – using the App stores and/or TestFlight presents a lot of hurdles, limitations, and slows things down.

### Solution
Create an S3 bucket to store ad-hoc app builds. After this issue is completed, we should have three S3 buckets related to app deploys:

- Production bucket (already in use to host production web and desktop apps)
- Staging bucket (already in use to host staging web and desktop apps)
- Ad-hoc bucket (new)

**Comment by AndrewGable** [comment]
Let's call it `s3://ad-hoc-expensify-cash/` ?

**Comment by roryabraham** [comment]
Lol,  RIP Expensify.cash

**Comment by AndrewGable** [comment]
Agree, but we can stay consistent 🤠

**Comment by nathanmetcalf** [comment]
OK, I've created the new bucket, however I'm not sure what we do for access permissions? How does this work? 

I've compared the new bucket to `staging-expensify-cash` and it appears the same. Is this enough? 
![image](https://user-images.githubusercontent.com/86330361/202318051-9033a749-46f3-49fe-9a57-732f5dd79dc8.png)

**Comment by AndrewGable** [comment]
Yes, same permissions should be OK!

**Comment by nathanmetcalf** [comment]
OK, I'll close this off then. If there is any further action, please feel free to re-open :)

**Comment by AndrewGable** [comment]
@nathanmetcalf - The key isn't working: https://expensify.slack.com/archives/C094TGUTZ/p1669938449985649

Can we double check the config? Thank you!

**Comment by coleaeason** [comment]
Updated the existing policy to include the new bucket, can you test again?
