### ISSUE TITLE
Web: Firefox: Dropping an image from a webpage on the Report chat list/composer does not open the attachment Modal.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account on web.
2. Open any report.
3. Open [https://media.istockphoto.com/photos/young-female-student-in-examination-picture-id9292[…]170667a&w=0&h=u4OGq5jCAPb0HBf91DET10vF97gSfqiRxm7uQ7NglMg=](https://media.istockphoto.com/photos/young-female-student-in-examination-picture-id929218914?b=1&k=20&m=929218914&s=170667a&w=0&h=u4OGq5jCAPb0HBf91DET10vF97gSfqiRxm7uQ7NglMg=)  in a new tab.
4. Drag and drop the image over the report messages list.

## Expected Result:
Send Attachment modal should open with that image.

## Actual Result:
Nothing happens.  It works on chrome.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Firefox

**Version Number:** 1.2.28-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202325342-c4ad3cb7-1af3-4e76-ae27-c9425bd33dd7.mp4

https://user-images.githubusercontent.com/43996225/202325357-764a057f-c6d9-4fa4-b77b-e108cd1fe719.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668635432661349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I can't seem to reproduce this one on FireFox. It's workin as intended as far as I can tell. 

https://user-images.githubusercontent.com/1127863/202751446-3c75e877-05e7-4a2b-a279-a08c31241c77.mov

**Comment by JmillsExpensify** [comment]
Woah this seems like a feature to me. Do we support this on any browser?
