### ISSUE TITLE
Text color appears black for all the buttons in the site - Reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Check the display of buttons in the program

## Expected Result:
The text in the buttons should be white

## Actual Result:
The text in all program buttons is black

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.29-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5824693_1711](https://user-images.githubusercontent.com/43996225/202477874-1f2da2e2-5440-48bd-bc4b-c1691adb7ed8.png)

https://user-images.githubusercontent.com/43996225/202477878-efec469f-1779-4e9d-b3ff-efa941ee21aa.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya  & Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668665477914149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0125057940417ca326
- Upwork Job ID: 1596133416959213568

**Comment by mountiny** [comment]
cc @grgia I think this is most likely coming from here https://github.com/Expensify/App/pull/12478

**Comment by michaelhaxhiu** [comment]
Bug reporting bonus should go to the contributor dhairyapatel143@gmail.com right?
https://expensify.slack.com/archives/C049HHMV9SM/p1668665477914149

**Comment by grgia** [comment]
Looking into this! It's not from that commit though, they were changed back in the final

**Comment by grgia** [comment]
Okay, I found the problem. I'll open a PR to fix

**Comment by sketchydroide** [comment]
I just tested, this is now fixed, closing

**Comment by dhairyasenjaliya** [comment]
Hello @sketchydroide upwork job for reporting bonh

**Comment by sketchydroide** [comment]
@greg-schroeder can you please create the job at upwork for @dhairyasenjaliya reporting?

**Comment by mountiny** [comment]
Just so this is not forgotten 🙌

**Comment by sketchydroide** [comment]
bumping @greg-schroeder

**Comment by sketchydroide** [comment]
bumping @greg-schroeder :) not overdue

**Comment by laurenreidexpensify** [comment]
Was using label to get Upwork job to be created - apols for false pings

**Comment by laurenreidexpensify** [comment]
offer sent in Upwork to @dhairyasenjaliya

**Comment by dhairyasenjaliya** [comment]
Accept @laurenreidexpensify

**Comment by neil-marcellini** [comment]
There's no help wanted here correct?

**Comment by grgia** [comment]
Yep this was already fixed in this [PR](https://github.com/Expensify/App/pull/12829), I'll remove the label

**Comment by sketchydroide** [comment]
@dhairyasenjaliya let us know if/when everything is done so we can close this :)

**Comment by dhairyasenjaliya** [comment]
@sketchydroide waiting for @laurenreidexpensify to close the upwork contract so that we can close this one :)

**Comment by sketchydroide** [comment]
@laurenreidexpensify not sure if this is something you can do now, or we are waiting for something :)

**Comment by sketchydroide** [comment]
still waiting, hopefully this will be closed soon

**Comment by laurenreidexpensify** [comment]
Hey folks 👋 @greg-schroeder is the assigned Bug Zero person here :) I think I stepped in to help get the contract on Upwork. I'll pay this now though as it's on my radar again

**Comment by laurenreidexpensify** [comment]
Payment done 👍🏽

**Comment by sketchydroide** [comment]
> Hey folks 👋 @greg-schroeder is the assigned Bug Zero person here :) I think I stepped in to help get the contract on Upwork. I'll pay this now though as it's on my radar again

Thanks for the context, will ask the BZ instead next time, thanks for jumping in though :)
