### ISSUE TITLE
[HOLD] iPad / Safari - Context menu does not open on long press reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to any chat
2. Long press on a message

## Expected Result: 
User should be able to open the context menu

## Actual Result: 
User can't open the context menu

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS - iPad / Safari

**Version Number:** 1.2.29-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202453611-88a2019d-ccf7-4fb8-86cb-f2a921fb8077.MP4

https://user-images.githubusercontent.com/43996225/202453659-e1e63cf4-58fc-4681-8f4a-02f44ac95d35.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668618695787659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mateocole** [comment]
OOO reassign

**Comment by JmillsExpensify** [comment]
Based on our discussion [in the community](https://expensify.slack.com/archives/C01GTK53T8Q/p1668811497897899?thread_ts=1668640125.477709&cid=C01GTK53T8Q), I'm going to close this issue. Given that tablets are not an officially supported platform, this issue is more accurately a new feature request than a bug. Closing.
