### ISSUE TITLE
iOS testflight beta keeps expiring

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#12828]
Every couple days I get this with the iOS testflight. I have to delete and reinstall when this happens which is a pain. Seems to be hitting others as well (context [here](https://expensify.slack.com/archives/C07J32337/p1668704333341659?thread_ts=1668535748.927339&cid=C07J32337)). 

@Expensify/mobile-deployers 

![IMG_0176](https://user-images.githubusercontent.com/1371996/202527396-9f489e1f-189b-476a-aee5-f0430f201ef9.png)

**Comment by joekaufmanexpensify** [comment]
Discussing whether there are reproduction steps [here. ](https://expensify.slack.com/archives/C07J32337/p1668716497734089?thread_ts=1668535748.927339&cid=C07J32337)

**Comment by AndrewGable** [comment]
Seems like maybe it's an Apple bug: https://developer.apple.com/forums/thread/720033

**Comment by joekaufmanexpensify** [comment]
Assigning to andrew per discussion in Slack.

**Comment by AndrewGable** [comment]
I posted in the Apple thread and will follow along for any updates.

**Comment by roryabraham** [comment]
Is anyone still seeing this issue?

**Comment by sketchydroide** [comment]
I never got it again, seems gone

**Comment by AndrewGable** [comment]
Agree I haven't seen it either 👻
