### ISSUE TITLE
Chat - Spaces, brackets are eliminated from attachment file name once uploaded to the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open any chat
3. Upload any file with brackets and/or spaces in its name

## Expected Result:
File name after upload to chat should stay the same.

## Actual Result:
Filename changes. Spaces, brackets are eliminated from attachment file name once uploaded to the chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.29.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202582510-2bdaced3-5fd3-47b0-80db-4ce3330d139a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Going to close this because this is a low value bug... or even a feature. Nothing really is broken with the changed name.
Please reopen if you disagree.
