### ISSUE TITLE
Log in - When clicking on Resent Link, the error message is displayed instead of “Link has been resent” with a green dot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In the login screen, enter an email that doesn't have an Expensify account yet
2. In the "Resent link" page - Disable the internet connection in the device
3. Verify the "Resend link" button is disabled and there's a notice that the user is currently offline
4. Go back online and click/tap on the "Resend Link" button

## Expected Result:
User should see  “Link has been resent” with a green dot on the left after click on "Resend Link" button

## Actual Result:
When clicking on Resent Link, the error message is displayed instead of “Link has been resent” with a green dot

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.29.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202714526-aa71fe0e-e570-4e31-a416-aca870e1f6bd.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
I can't reproduce this bug and I assume it is because it is not a bug, it's a feature that does not allow you to login/ask for reset link more than X times in Y period of time.
