### ISSUE TITLE
[$1000] [Performance] App not running at 60 FPS when just being idle on the home screen / reports list

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#12885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

When you open the (release) app on android the app doesn't run at 60 FPS, even when you are just idle on the home screen. Something going on reduces the UI thread performance to something like ~45 FPS. 

The same is true for iOS, but due to the fact that iOS devices have more resources/power the issue is less noticeable.

## What is the impact of this on end-users?

- The app isn't running at 60 FPS which is perceived by the user as "slowness" (low quality feeling)
- The app drains the device's resources quicker (gets hotter, higher power consumption) 

## List any benchmarks that show the severity of the issue

- Open the app in release mode
- Let it open for a few seconds to settle down
- Measure with a tool like [android-performance-profiler](https://github.com/bamlab/android-performance-profiler)
- Notice how the app isn't running at 60 FPS:

<img width="2558" alt="Screenshot 2022-11-21 at 12 35 09 PM" src="https://user-images.githubusercontent.com/16821682/203041441-2708222e-d0b2-421c-9005-a2c11a73932e.png">

(The issue can also be seen in dev mode. There the UI thread seems to run at 60 FPS, however, you can notice periodic fluctuations on the JS thread). 

## Proposed solution (if any)

The issue is that we are _constantly rendering Skeleton views, which we are animating_, even if those aren't in the viewport (they are e.g. the placeholder for the freeze view):

https://github.com/Expensify/App/blob/17b14f683b31ac3eadd07ac2f22afa020e617a47/src/pages/home/ReportScreen.js#L219-L234

So I see two solutions:

- Keep the current implementation and just prevent the skeleton views from animating when not being in the view port
- Replace the current implementation with reanimated, which can handle these simple animations way more efficient (however it's still a bit of a waste of resources).

I'd even say we can do both:

- First, change the implementation to only animate when necessary
- Then, swap the implementation of the animation with a more efficient one

What do you think? 

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

I just removed the skeleton view and ran the app again in release mode its running at 60 FPS again!

## Platform:
Where is this issue occurring?

- [ ] Web
- [x] iOS
- [x] Android
- [ ] Desktop App
- [x] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~019226ba444ebdd0c4
- Upwork Job ID: 1594873871348228096

**Comment by mountiny** [comment]
@hannojg 

> I'd even say we can do both:

> - First, change the implementation to only animate when necessary
> - Then, swap the implementation of the animation with a more efficient one

> What do you think?


I think that sounds like a good plan to me. Can you create a PR for this?

**Comment by hannojg** [comment]
Yes, will do! Will first see what's the other reason for it not to run at 60 FPS. Once I know I will put up Pas 😊 👍

**Comment by mountiny** [comment]
Thank you  🙇

**Comment by hannojg** [comment]
Just wondering, if the issue is now open for any contributors? Because Margelo is already working on this one 😄

**Comment by hannojg** [comment]
First PR is up: https://github.com/Expensify/App/pull/12926

The next one will be replacing the current implementation with reanimated. Also I noticed that the animation sometimes isn't even showing (on main) as the app is so super busy, that it can't schedule the animation on the JS thread.

**Comment by mountiny** [comment]
This issue is hard to define as regression. This might have been introduced with the Skeleton view and we havent tested for performance then.

These performance issues are hard to test on since we dont measure fps objectively so I am not sure if any regression test should be added here. Let me know if you disagree @sakluger 

Nobody needs to be paid here, we are good.
