### ISSUE TITLE
Incorrect name being displayed for Chat Rooms

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#12883]
## Action Performed:
1. If needed, create a workspace
2. Create a workspace room
3. Navigate to the room in the LHN

## Expected Result:
The name of the room should be displayed correctly

## Actual Result:
- The name of the room is displayed as `Chat Report` for a second before changing to the correct one. 
- In the LHN, it remains displaying incorrectly until you leave the room. 
- If offline, the incorrect name displays permanently

## Workaround:
Not needed

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number: 1.2.29-6
**Reproducible in staging?: YES
**Reproducible in production?: YES

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment]
Reported on Slack

https://expensify.slack.com/archives/C049HHMV9SM/p1668485291380349

**Comment by lschurr** [comment]
Can this stay internal since you've already put up a fix @Gonals?

**Comment by JmillsExpensify** [comment]
Same root cause as the original bug report here: https://expensify.slack.com/archives/C01GTK53T8Q/p1668041691611749.

**Comment by lschurr** [comment]
Do we need this to stay open or it's being fixed elsewhere?

**Comment by Gonals** [comment]
> Do we need this to stay open or it's being fixed elsewhere?

Let's keep it open. It should close automatically on deploy

**Comment by neil-marcellini** [comment]
Hi there, when it comes time to do the Bug-Zero checklist, please note that the first 2 steps are done here https://github.com/Expensify/App/issues/12629#issuecomment-1325568618.

**Comment by lschurr** [comment]
Hm, this was closed so I wasn't aware we needed to issue any payment. @Gonals can you confirm what's needed here?

**Comment by lschurr** [comment]
Thanks for your patience @parasharrajat - could you apply to the job in Upwork? https://www.upwork.com/jobs/~01217e56876e8229f2

**Comment by lschurr** [comment]
Hm I think I made it public.. can you try again @parasharrajat?

**Comment by lschurr** [comment]
@parasharrajat - offer sent in Upwork!

**Comment by lschurr** [comment]
@parasharrajat - just confirming that I sent that offer to the right contributor. Could you confirm you got it?

**Comment by lschurr** [comment]
Great, paid!
