### ISSUE TITLE
[Dark mode] Checkboxes always look checked in dark mode

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start adding a VBA, get to the company step
2. The checkbox at the bottom about restricted industries always look checked

## Expected Result:
When the checkbox is not checked, it shouldn't have a check. Also, the blue background doesn't seem correct either

## Actual Result:
The checkbox always have a check. I one of the states, it has a blueish background.

https://user-images.githubusercontent.com/87341702/203184791-3ecebbe2-b57b-436d-8063-bbce24616d84.mov

## Workaround:
By brute force you can find out which state is the right one to continue

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
cc @grgia

**Comment by grgia** [comment]
cc @shawnborton do we have a mockup with a checkmark?

**Comment by grgia** [comment]
I'm happy to fix this one if so! 

Here's the old checkbox for reference
https://user-images.githubusercontent.com/38015950/203185404-4cd748a3-a2c8-4d6f-854f-af5774dce520.mov

**Comment by shawnborton** [comment]
Whoa - strange that a checkmark appears even when it is not checked. Is there a way to just get rid of that white inner checkmark when this is not in the checked state?

**Comment by grgia** [comment]
yep! besides removing the checked, is the blue outline/fill okay?

**Comment by shawnborton** [comment]
If we're able to change that to our brand green (both outline and fill), that would be great!

**Comment by shawnborton** [comment]
Also @grgia just wanted to make you aware of this issue in case it's related at all: https://github.com/Expensify/App/issues/11283

**Comment by grgia** [comment]
https://user-images.githubusercontent.com/38015950/203417583-8e18e564-a664-41be-9ce1-9a3f8ebf6a5b.mov

How do we feel about this?

**Comment by shawnborton** [comment]
That works for me. Is it easy to change that color to green though? I know for CSS, we can do something neat like this:

```
input[type="checkbox"] {
    accent-color: desired-color
}
```

**Comment by grgia** [comment]
Yep! Do you want to change the green to a different color?

**Comment by aldo-expensify** [comment]
> Yep! Do you want to change the green to a different color?

I think he means the blueish background to green :P

**Comment by shawnborton** [comment]
Yup, that's what I mean! So we keep the green outline, and then ideally the check fill is green too.

**Comment by grgia** [comment]
https://user-images.githubusercontent.com/38015950/203444302-fd24f258-38d5-431e-a1f6-fb5eaf5fc4fe.mov

How's this?

**Comment by shawnborton** [comment]
Perfect!!

**Comment by grgia** [comment]
Should be fixed with dark mode merge. (currently in DEV)
