### ISSUE TITLE
[Dark mode] Workspace icon inconsistent color

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#12915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have a workspace
2. Go to Settings > Workspaces
3. Notice that the workspace icon is green with a **black** building
    ![image](https://user-images.githubusercontent.com/87341702/203197602-f68b1b5f-8254-41d7-aa5c-979a99b6b8d5.png)
5. Click the workspace
6. Notice that the big workspace icon is green with a **white** building
    ![image](https://user-images.githubusercontent.com/87341702/203197576-323efe68-6358-446f-b7c2-2698dd32a025.png)

## Expected Result:
I would expect these icons to be the same

## Actual Result:
They have different color

## Workaround:
N/A, just costmetic

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
cc @grgia

**Comment by aldo-expensify** [comment]
@shawnborton is my expectation for the color of the building to be the same correct?

Bonus: Is this icon expected to have a black border?

![image](https://user-images.githubusercontent.com/87341702/203197801-1467c4ab-b157-4f74-b452-982f97462fc4.png)

**Comment by shawnborton** [comment]
Good catch - I think the outline currently behaves like that (even not in dark mode) but I think it's worth fixing everywhere.

**Comment by grgia** [comment]
Yep, I can take this one too

**Comment by grgia** [comment]
This should be fixed with the dark mode merge. (currently in DEV)
