### ISSUE TITLE
Incorrect red color in the light scheme

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#12922]
Coming from https://expensify.slack.com/archives/C049HHMV9SM/p1669040297102959

@Puneet-here Should be rewarded for the reporting bonus, the issue was fixed internally in this PR. https://github.com/Expensify/App/pull/12898

**Comment by mountiny** [comment]
@sophiepintoraetz Would you be please able to pay out @Puneet-here a reporting bonus for this issue?

**Comment by sophiepintoraetz** [comment]
Sure - job created [here](https://www.upwork.com/jobs/~01f655ac1d303ea712) and I've invited you, @Puneet-here!

**Comment by Puneet-here** [comment]
Applied to the job, thanks!

**Comment by sophiepintoraetz** [comment]
WE're good!
![image](https://user-images.githubusercontent.com/42940078/203874325-584c9ae9-79c7-4286-bb92-02c669ac3589.png)
