### ISSUE TITLE
Console error shows on login Invalid prop ....role of value user supplied to AvatarWithIndicator, expected one of [“admin”]

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#12920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Launch the app

## Expected Result:
Not seeing this console error

## Actual Result:
Seeing the console error 

## Workaround:
Does not seem to affect anything 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669099212581009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
<b>Proposal</b>
Since we have new role "user" in `policies` object inside `AvatarWithIndicator.js` this warning happened.
<img width="559" alt="Screen Shot 2022-11-22 at 19 27 28" src="https://user-images.githubusercontent.com/16502320/203313753-739a2325-07fa-498c-b7f2-105cea170191.png">
<b>Solution</b>
To avoid this warning, we can update the `AvatarWithIndicator` PropTypes by adding new role "user" inside `CONST.js`.

```diff
    POLICY: {
        TYPE: {
            FREE: 'free',
            PERSONAL: 'personal',
            CORPORATE: 'corporate',
            TEAM: 'team',
        },
        ROLE: {
            ADMIN: 'admin',
+            USER: 'user',
        },
        ROOM_PREFIX: '#',
        CUSTOM_UNIT_RATE_BASE_OFFSET: 100,
        OWNER_EMAIL_FAKE: '_FAKE_',
    },
```

**Comment by flodnv** [comment]
Thanks @hungvu193 but this GH does not have the 'Help wanted' label. It was my plan to do this, but another reason I also took it is because we also need another role in there (or else we'll be fixing the same "bug" in a few months).

**Comment by davidcardoza** [comment]
@flodnv This is what I see when I launch NewDot on web and open the console. Let me know if I am missing a step here, my error doesn't match with the error message in the linked Slack thread. 

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/6643649/203453705-344a5a72-918a-4465-ba1b-d8d3e4a9d955.png">

**Comment by flodnv** [comment]
@davidcardoza this stumped me for a bit. The logged in user has to be a part of another policy as a user (not admin)

**Comment by dhairyasenjaliya** [comment]
Hello @flodnv upwork job for bug reporting missing

**Comment by flodnv** [comment]
Thanks for the bump, can you handle this @davidcardoza please?

**Comment by goddev999** [comment]
Hi @flodnv 
I am interested in this error, 
How did you get this error, web building or mobile app?
I can fix this error.

**Comment by dhairyasenjaliya** [comment]
Applied @davidcardoza

**Comment by flodnv** [comment]
Yes, this bug is fixed @davidcardoza .... we just need to pay @dhairyasenjaliya for reporting

**Comment by davidcardoza** [comment]
Contract extend @dhairyasenjaliya please accept and I will process payment.

**Comment by dhairyasenjaliya** [comment]
Accepted @davidcardoza

**Comment by flodnv** [comment]
Can we close this @davidcardoza ?

**Comment by davidcardoza** [comment]
Yeah, payment sent. Sorry for the delay I was OOO for a conference.

**Comment by dhairyasenjaliya** [comment]
Received and also please close the upwork contract @davidcardoza
