### ISSUE TITLE
Homepage/Chat - "You appear to be offline" message blocks to login/chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

## Expected Result:
User should be able to login

## Actual Result:
"You appear to be offline" message blocks login

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203438866-391e600c-0778-47a3-8b81-878ca750a38c.mp4

![image (3)](https://user-images.githubusercontent.com/93399543/203438880-2cd03371-b235-49c7-8974-042e207c9699.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:* Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I think the main site (and therefore API) just went down for a moment?

**Comment by marcaaron** [comment]
I was able to login fine on staging just now so I'm going to close this.

**Comment by aldo-expensify** [comment]
> I think the main site (and therefore API) just went down for a moment?

yes, it was probably that

**Comment by luacmartins** [comment]
Agree with the assessment above!
