### ISSUE TITLE
[N7 Account Settings] Hook up new Display name, Pronouns and Timezone pages to Profile page

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#12952]
Tracking issue: https://github.com/Expensify/Expensify/issues/182122

Detailed section of doc here: https://docs.google.com/document/d/17akqrbC-w8FqEoDLvcLmrX6iw4uaVrT_xlwAl-IhEzE/edit#heading=h.jl7alj505ji8

Note: The rest of the new pages are on hold. They are covered by [this issue](https://github.com/Expensify/App/issues/11582) when the hold is removed.

This is part of WAQ project because we want to [Align on how list selection works across platforms](https://github.com/Expensify/App/issues/11795#top)

**Comment by cristipaval** [comment]
I'm on it. Aiming to open a PR today

**Comment by cristipaval** [comment]
This is held on [New timezone pages](https://github.com/Expensify/App/pull/12201) PR

**Comment by cristipaval** [comment]
Going to open a PR today.

**Comment by cristipaval** [comment]
@MelvinBot, please pay more attention on what you have to do.

**Comment by cristipaval** [comment]
Hey @slafortune! The PR for this issue was merged today. I added the `Bug` label just to make sure that the C+ will get paid for the review.

**Comment by slafortune** [comment]
@cristipaval Thanks for doing that!  Just want to make sure I have this right -  today I can pay Sobit $1000?

**Comment by cristipaval** [comment]
I have a question [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1672922875426909) related to the payment for the PR. I'll keep you posted.

**Comment by cristipaval** [comment]
Hey @slafortune ! Looks like PR review payment [should be docked 50%](https://expensify.slack.com/archives/C01SKUP7QR0/p1672922875426909).

**Comment by cristipaval** [comment]
@slafortune Feel free to close this issue when the payment is done.

**Comment by slafortune** [comment]
Created job and invited Sobit to it -  https://github.com/Expensify/App/pull/13290

**Comment by slafortune** [comment]
Paid!
