### ISSUE TITLE
After Deleting a workspace it directly navigates to main setting page instead of workspace list page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :

1. Login in any expensify account
2. Press on avatar icon (profile)
3. Navigate to workspaces
4. Go to any workspace
5. Press three dot on right
6. Delete Workspace
7. Notice it directly navigates to main settings page instead of (all workspace list) where we actually came from

## Expected Result : 
It should navigate back to workspace setting page (All workspace list)

## Actual Result : 
It directly navigate to main setting page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203615518-9cf94956-741b-45d8-9d9a-c97db3521f80.mov
https://user-images.githubusercontent.com/43996225/203615546-4c8b8111-e5ad-43ff-ac0d-4bcc6d37b002.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669213692511709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- In order to navigate to workspace list we need to change in function `confirmDeleteAndHideModal `

https://github.com/Expensify/App/blob/ece97e2e90ca4977ef10fa65024f30e9bdf81840/src/pages/workspace/WorkspaceInitialPage.js#L78-L83

Changes

```diff
    confirmDeleteAndHideModal() {
        const policyReports = _.filter(this.props.reports, report => report && report.policyID === this.props.policy.id);
        Policy.deleteWorkspace(this.props.policy.id, policyReports);
        this.toggleDeleteModal(false);
-       Navigation.navigate(ROUTES.SETTINGS);
+      Navigation.navigate(ROUTES.SETTINGS_WORKSPACES);
    }
```

**Result**


https://user-images.githubusercontent.com/47522946/203600492-27dbf4c3-932a-43cf-bf0e-e6fb0151ffc8.mov

**Comment by jasperhuangg** [comment]
Hey @dhairyasenjaliya sorry I already had some changes locally from before, I'm gonna snag this one.

In the future please only comment proposals on issues that have the `Help Wanted` label on them.
https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+label%3A%22Help+Wanted%22

**Comment by adelekennedy** [comment]
@jasperhuangg should this issue be `Internal`now?

**Comment by adelekennedy** [comment]
@jasperhuangg confirming you're working on this one internally? If so then I'll pay out @dhairyasenjaliya for the reporting bonus

**Comment by jasperhuangg** [comment]
Hey @adelekennedy Sorry I submitted a PR for this issue and totally just forgot to update its status, my bad 😓  

but yes! this issue is internal and was fixed in https://github.com/Expensify/App/pull/12971. Let's be sure to get @dhairyasenjaliya paid out for reporting this issue.

**Comment by dhairyasenjaliya** [comment]
bump for Upwork job @adelekennedy

**Comment by jasperhuangg** [comment]
not overdue, still waiting to pay out the reporting fee

cc @adelekennedy

**Comment by jasperhuangg** [comment]
Hey hey not overdue, still waiting for payment on this one, pretty sure people are out for the holidays so gonna erode to Weekly, sorry @dhairyasenjaliya for the delay!

cc @adelekennedy

**Comment by dhairyasenjaliya** [comment]
can understand no issue :) @jasperhuangg 
friendly bump @adelekennedy

**Comment by adelekennedy** [comment]
Hi whoops - I was ooo and missing these pings after I unassigned myself. @dhairyasenjaliya just sent you an offer

**Comment by adelekennedy** [comment]
and done!
