### ISSUE TITLE
iOS - App Crashes when we click "Fix Errors" if the only thing left are the Terms

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#12986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with Expensifail account
3. Go to Settings => Payments => Add a debit card
4. Enter all data, but don't accept the terms
5. Click "Save"
6. Click on 'fix the errors' button

## Expected Result:
7. System should focus on the terms box

## Actual Result:
Crash

## Workaround:
Don't click the 'Fix Errors' button
## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.29-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Similar issue here: https://github.com/Expensify/App/issues/12508

**Comment by Gonals** [comment]
Ah, same one. Closing as duplicate
