### ISSUE TITLE
Console error when clicking 'Fix Errors' for State select input

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#12989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with Expensifail account
3. Go to Settings => Payments => Add a debit card
4. Fill all data up until the State
5. Without entering any data, click "Save"
6. Click on 'fix the errors' button

## Expected Result:
No errors should show in the console

## Actual Result:
An error shows up in the console:
<img width="914" alt="Screen Shot 2022-11-24 at 12 41 07 PM" src="https://user-images.githubusercontent.com/19366280/203776347-91ba8955-98dc-4a39-aa21-0750ec88663f.png">

## Workaround:
Not needed

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.31-2
**Reproducible in staging?:**  Yes
**Reproducible in production?:**  Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Similar-ish to [this one](https://github.com/Expensify/App/issues/12508), but different underlying issue and reproducible in Staging/Prod

**Comment by miljakljajic** [comment]
I was able to reproduce this:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/28715117/203831420-7700304a-67b5-4302-8033-0e11e9afd174.png">

Could this be worked on by an external contributor?

**Comment by miljakljajic** [comment]
I was able to reproduce this:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/28715117/203831956-1175bd9b-1269-4ccb-8f11-fe1ebcb10215.png">

Could this be worked on by an external contributor?

**Comment by mdneyazahmad** [comment]
## Proposal

`ref` is not passed properly in https://github.com/Expensify/react-native-picker-select/blob/7f09b2c15ffae320d769788f75bdf8948714bb10/src/index.js#L8

Form stores a reference of all input elements in `inputRefs`. When the `fix the errors` button is pressed it execute the `focus` method on the reference element.

https://github.com/Expensify/App/blob/dd3757552acde24535621cdb31d79dc070978fe0/src/components/Form.js#L262-L266

The reference element here does not reference the `select` element, and there does not exist `focus` method. Therefore the issue appears in `console`.

https://github.com/Expensify/App/blob/dd3757552acde24535621cdb31d79dc070978fe0/src/components/Picker/index.js#L177-L182

### Solution

Forward ref in `RNPickerSelect` component.

https://github.com/Expensify/react-native-picker-select/blob/7f09b2c15ffae320d769788f75bdf8948714bb10/src/index.js

```diff
+export default React.forwardRef((props, ref) => {
+    return <RNPickerSelect innerRef={ref} {...props} />;
+});
```

https://github.com/Expensify/react-native-picker-select/blob/7f09b2c15ffae320d769788f75bdf8948714bb10/src/index.js#L541

```diff
+                   ref={this.props.innerRef}
```

**Comment by Gonals** [comment]
Ah, @miljakljajic, @mdneyazahmad , I linked the fix PR yesterday, so this doesn't need to be worked on

**Comment by mdneyazahmad** [comment]
@Gonals I missed that linked PR, sorry for that. I believe after the PR clicking on the button, it will do nothing. If you go ahead with my proposal, It will focus the internal select element. Thanks!

**Comment by Gonals** [comment]
RNPickerSelect is an external component, though, and since [this PR](https://github.com/Expensify/App/pull/12954) will take us to the right element anyways, I think it is fine to just avoid the console error here.

**Comment by miljakljajic** [comment]
Do we need to keep this open? Is there anything left to be done?

**Comment by alex-mechler** [comment]
FYI, this PR hid the problem with https://github.com/Expensify/App/issues/15290, as we no longer were attempting to call `focus` on a component that did not have that method, instead of fixing the fact that there was no `focus`
