### ISSUE TITLE
Profile - Image stuck at the edge and takes a while to appear when uploading large image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Open Setting, click on Avatar to open Profile Page
3. Click on Edit photo and choose an image from local
4. Notice that the Edit Photo page transition is slow for a while before becoming fully visible.

## Expected Result:
 Edit Photo page transition need to be smooth without any delay.

## Actual Result:
Edit Photo page transition is delayed and stuck for a while.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.31-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203828765-102dd822-68f9-4f26-85d1-eee11f7e8dcc.mov

https://user-images.githubusercontent.com/43996225/203828791-47b957b1-fb66-40e1-b7bc-35aa0c37ad23.mp4
Image used : 
![kinnd-02 (1)](https://user-images.githubusercontent.com/43996225/203829213-8abe910e-1263-40c1-a586-9e0ca838f1ab.png) or from http://unsplash.com/

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669089246330699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@kavimuru - I tested this a number of times on staging and didn't see any huge delays. Here's an example video:

https://user-images.githubusercontent.com/30815269/203865159-30e3beb1-839f-4db0-a58d-633627e429ac.mp4

I'm definitely not seeing what you're seeing and cannot reliably reproduce. Closing, but please reopen if you are still experiencing this behaviour after clearing cache/cookies.

**Comment by jliexpensify** [comment]
Just also want to add that @kadiealexander tested this as well and did not see any issues.

**Comment by kavimuru** [comment]
@jliexpensify Can you check with the image attached in the bug?

**Comment by jliexpensify** [comment]
@kavimuru I'm not understanding this logic of using one specific image: isn't the purpose of a bug meant to show consistent incorrect behavior? So it shouldn't matter what image is used - as any image used should result in the bug, which isn't what myself and my colleague are seeing.
