### ISSUE TITLE
mWeb- The Payment option is hidden after selecting one of the payment option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with HT account (A) in wWeb/safari
3. Log in with different account (B) in Web and request money from Account A
4. Back to Account A in mWeb/safari
5. Select Pay button
6. Choose the option from drop down

## Expected Result:
The Payment option should be visible after selecting one of the payment option

## Actual Result:
The Payment option is hidden after selecting one of the payment option

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Safari ONLY

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203840227-70a29ba4-1d14-4f7a-a09c-393858029402.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can reproduce this, but it's also present in prod so I'll remove the deploy blocker label. I'll still look into a fix for the top scroll after selection.

**Comment by luacmartins** [comment]
I'll investigate this week

**Comment by Puneet-here** [comment]
Same bug as https://github.com/Expensify/App/issues/13011 (notice that the whole screen scrolls)

**Comment by luacmartins** [comment]
Revert was deployed. Closing issue.

**Comment by trjExpensify** [comment]
@luacmartins confirming we have nothing to do here, right?

**Comment by luacmartins** [comment]
@trjExpensify Should I still fill the [checklist](https://github.com/Expensify/App/issues/13009#issuecomment-1329711804) in this case?

**Comment by luacmartins** [comment]
Ah yea, no payments.

**Comment by trjExpensify** [comment]
Cool, so wrt to a regression test for this. I don't think it's required for a mWeb-only issue, would you agree?

**Comment by luacmartins** [comment]
I think that's fine and not seeing the button (like it happened here) will prevent the agent from going through with the flow. So I think we are good!
