### ISSUE TITLE
Web - Login - The empty welcome page + error in console after login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account

## Expected Result:
Welcome page is not empty after log in

## Actual Result:
1. The empty welcome page opens after login
2. The Onyx error in console is visible

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203867692-0722fdf4-89dd-4123-9ea7-ec68090f16ed.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Dupe https://github.com/Expensify/App/issues/13000

**Comment by luacmartins** [comment]
This is the same as https://github.com/Expensify/App/issues/13000. Closing.

**Comment by kbecciv** [comment]
@luacmartins QA team is experienced an error in console after login in HT account with build 1.2.34.0

Do we need to open a new ticket?

![image (5)](https://user-images.githubusercontent.com/93399543/204795290-f46fc7e5-3eed-4448-8e7a-228f84373c3f.png)

**Comment by luacmartins** [comment]
@kbecciv please open a new issue since they are different. Closing this one

**Comment by kbecciv** [comment]
@luacmartins Will do, thank you
