### ISSUE TITLE
New Room - The "Save" button does not work from the first click

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13033]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with the Expensifail account
3. Create New Room (if it has not been created before)
4. Open the room -> Details -> Settings
5. Change the room's name and click "Save"

## Expected Result:
The "Save" button should be work from the first click

## Actual Result:
The "Save" button does not work from the first click

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.31.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203877391-1afec02f-a5df-41ee-a9a5-2da6cb5c60cc.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- We need to add `keyboardShouldPersistTaps="handled"` inside `<Scrollview>` 
- In the below page 
https://github.com/Expensify/App/blob/39b2f9924060c7381b2ff37563a5af88360b0d9d/src/pages/ReportSettingsPage.js#L152

```diff
- <ScrollView style={styles.flex1} contentContainerStyle={styles.p5}>
+ <ScrollView keyboardShouldPersistTaps="handled" style={styles.flex1} contentContainerStyle={styles.p5}>
```

**Result**

https://user-images.githubusercontent.com/47522946/203912290-a59feef4-ecc5-460a-94fa-573b418afcb4.mp4

**Comment by Puneet-here** [comment]
It's a duplicate. Check https://github.com/Expensify/App/issues/13003

**Comment by flaviadefaria** [comment]
Ok closing this for https://github.com/Expensify/App/issues/13003.
