### ISSUE TITLE
OpenPaymentDetailsPage displays console error

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#13048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In App, login into account A and request money from account B
2. Log into account B
3. Open the browser console
4. Tap `Pay` and verify that you don't see the console error below:

![Screenshot 2022-11-25 at 11 48 36 AM](https://user-images.githubusercontent.com/22219519/204041483-ac6bed4f-332c-4d9d-beee-26a924791e13.png)

## Expected Result:
No errors

## Actual Result:
Error is displayed

## Workaround:
N/A

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Hi @luacmartins and @kevinksullivan - I don't have a Gold Wallet set up, and when I did some digging, it looked like [No SSN = inability to use the Wallet](https://expensify.slack.com/archives/C02HWMSMZEC/p1661858968322329?thread_ts=1661858613.132929&cid=C02HWMSMZEC). Reassigned this one for someone else to test!

**Comment by luacmartins** [comment]
We fixed this internally and the fix is merged already.

**Comment by kevinksullivan** [comment]
@luacmartins sorry just to clarify, we fixed this bug internally already? Or the issues related to not having a gold wallet?

**Comment by luacmartins** [comment]
@kevinksullivan this was fixed internally already
