### ISSUE TITLE
mWeb/Safari - Chat - Long pressing on an image causes text selection

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Open any chat
3. Long press on any picture

## Expected Result:
The blue screen should not appear when long pressing on the picture

## Actual Result:
A blue screen appears when you long press on the image

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/safari

**Version Number:** 1.2.31.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203986247-92472f28-a8d6-4904-ae5c-74dd75249502.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I think "blue screen" in this case means "text selection"? We could do better for the "expected" part of this before choosing to take action. What is expected here? Why is the user long pressing and what is their goal?

**Comment by muttmuure** [comment]
Going out of office so this shouldn't be blocked on me - reassigning

**Comment by kadiealexander** [comment]
@kbecciv what is the expected behaviour when you long-press on a picture?

**Comment by kbecciv** [comment]
@kadiealexander Context Menu should be shown and no blue boxes.

**Comment by kadiealexander** [comment]
@kbecciv please update your original issue to reflect the desired outcome.

**Comment by kbecciv** [comment]
Updated expected results
