### ISSUE TITLE
Profile Debit Card - Name On Card Field Should Be AutoFocused

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on Avatar
2. Click On Payments
3. Click On Add Payment Method
4. Select Debit Card

## Expected Result:
Name On Card Field Should Be AutoFocused Like All Other Forms

## Actual Result:
Name On Card Field Is Not Focused

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204148663-7260ccdb-598d-4ad8-b647-07f89593c5c9.mp4

https://user-images.githubusercontent.com/43996225/204148672-d0217f1f-6f7b-450c-8e2c-18d4c433b1a0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669474623882369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment]
Proposal

Need to pass **autoFocus** props in addDebitCardPage to the Name On Card Field.

**Comment by Puneet-here** [comment]
### Proposal 
I don't think we need autofocus here but If this needs to be fixed we have to pass `autoFocus` to focus the input automatically and `shouldDelayFocus` (The  shouldDelayFocus needs to be imported from [here](https://github.com/Expensify/App/blob/main/src/libs/shouldDelayFocus/index.android.js) so that it only delays the focus at android.)
 ```jss
<TextInput
autoFocus
shouldDelayFocus={shouldDelayFocus}
```
It needs to passed here -
https://github.com/Expensify/App/blob/17c34e3d0d255210b3c8598869cda25879c1f4e8/src/pages/settings/Payments/AddDebitCardPage.js#L125

**Comment by greg-schroeder** [comment]
Shoot, sorry, reviewing now

**Comment by greg-schroeder** [comment]
>I don’t feel strongly that we need to do this. We don’t really have any UX “rules” that say a field should always be auto-focused when we visit a page.

I'm going to close this for now given the discussion above in Slack
