### ISSUE TITLE
Opening a chat that was not opened recently while being offline seems to take forever to load

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#13088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to newDot.
2. Navigate to one of the chats and from the network tab select `offline` mode.
3. Now click on any other chat and it will load forever.
<img width="1703" alt="Screenshot 2022-11-28 at 7 45 55 PM" src="https://user-images.githubusercontent.com/35863227/204326541-8566ee86-6a5f-495d-bdd5-43a94d522b07.png">

## Expected Result:
Users should alteast be allowed to take any optimistic actions though the chat is not loaded locally in ONYX.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/35863227/205002792-55a734a7-e5d2-453a-be68-7164a5a51098.png">

## Actual Result:
The chat seems to take forever to load.
## Workaround:
No workaround at least when we are offline. When you are online you can manually go to each chat report to make sure ONYX has the data saved for all the chats and now if you go offline it would read stale data from ONYX.
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1669644904805489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~012b395e85cfcc6b49
- Upwork Job ID: 1598232191671402496

**Comment by s77rt** [comment]
I don't think the expected results make sense.
What if you had a chat with that user but you are just in another device?

I don't think this qualifies as a bug

**Comment by techievivek** [comment]
@s77rt Please catch the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669644904805489) and feel free to put your thoughts.

**Comment by techievivek** [comment]
Working on it today, adding the external label so a C+ can be assigned who will review the PR.

**Comment by techievivek** [comment]
Going to remove the `external` and `help wanted` labels as I will be working on this internally.

**Comment by alexpensify** [comment]
@techievivek - If it's eternal should I remove the job in Upwork?

**Comment by techievivek** [comment]
@alexpensify  Yes, please.

**Comment by alexpensify** [comment]
Done!

**Comment by techievivek** [comment]
PR is up but we are having some discussions about how should we handle cases like these. More info [here](https://github.com/Expensify/App/pull/13233#discussion_r1037479713).

**Comment by alexpensify** [comment]
Thanks for the update @techievivek!

**Comment by alexpensify** [comment]
It looks like there is still movement in the PR.

**Comment by techievivek** [comment]
Ohh, yes, I will wait for the @yuwenmemon to fix the online behaviour for this issue: https://github.com/Expensify/App/issues/13074, and only then I proceed with my PR as it would require the changes from there.

**Comment by alexpensify** [comment]
Thanks for the update! While we wait, I'm moving this to a weekly since it's on hold for the online behavior fix.

**Comment by alexpensify** [comment]
Still on hold-- looks like the PR is under review.

**Comment by Santhosh-Sellavel** [comment]
Unassigned me as I'm not a C+ reviewer in the PR!

**Comment by alexpensify** [comment]
I'm still OOO and plan to review next week when I'm back online.

**Comment by alexpensify** [comment]
It looks like https://github.com/Expensify/App/issues/13074 is in production, @techievivek are you able to review this GH again? Thanks for the update!

**Comment by alexpensify** [comment]
I noticed your OOO status. Feel better and we can review when you are back to 100%.

**Comment by techievivek** [comment]
Update on the issue: PR is up and has been reviewed. While reviewing the PR we noticed certain anti-patterns in our existing code and my solution was built on top of it which will definitely make the overall code complex to understand or make changes in future. So keeping that in mind I will open a discussion in the open-source channel to figure out what should be the best course of action to fix the issue and how we fix the existing anti-patterns.

**Comment by techievivek** [comment]
Started a discussion in #open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673246681648109).

**Comment by alexpensify** [comment]
It looks like this conversation is still moving forward in the Slack thread above. Thanks, @techievivek for the update!

**Comment by marcaaron** [comment]
Left a comment on the linked PR. But I think a good path forward could be to close this issue + linked PR and use https://github.com/Expensify/App/issues/14223 to discuss proposals before we code anything else. I think that we didn't start with a super clear Problem/Solution in this issue, started coding too soon, and we're not really making much progress in the Slack thread.

**Comment by yuwenmemon** [comment]
I think we should close this out as this behavior of the App is no longer happening anymore. This is what you see now if you open a chat that was not opened recently while being offline:
<img width="639" alt="Screenshot 2023-01-17 at 2 13 37 PM" src="https://user-images.githubusercontent.com/4741899/213024732-ba1ec1be-f95e-444f-80ef-7b007f8ed934.png">

**Comment by alexpensify** [comment]
This was found internally, so no payment will be dispersed for this GH.
