### ISSUE TITLE
[HOLD for payment 2022-12-15] [$1000] Light background colour is shown when navigating between right docked modal pages

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#13086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Open a right docked page on web or desktop
- Navigate deeper into another right docked modal
- Navigate back and forth between them

## Expected Result:
- We shouldn't see an obviously incorrect colour as the background

## Actual Result:
- We see an obviously incorrect colour as the background (this existed before, but is much more jarring with the darker colours.)

<img width="80%" alt="Screenshot 2022-11-24 at 11 44 47" src="https://user-images.githubusercontent.com/10736861/203777700-b95a0e9a-f7a4-45e0-a84e-933d98e2d866.png">

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Reproducible in staging?:** yes
**Reproducible in production?:** yes, pretty soon
**Email or phone of affected tester (no customers):** all

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01f7b6e9d9a74ed27a
- Upwork Job ID: 1598132781569765376

**Comment by tienifr** [comment]
# Proposal
## Problem
In https://github.com/Expensify/App/blob/13970529db79931c2371f7a0b6d5f96792e08c60/src/libs/Navigation/NavigationRoot.js#L19
we're setting background of navigation is `#002E22`

## Solution

In https://github.com/Expensify/App/blob/13970529db79931c2371f7a0b6d5f96792e08c60/src/libs/Navigation/NavigationRoot.js

```diff
const navigationTheme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
-        background: themeColors.highlightBG,
+        background: 'transparent',
    },
};
```


https://user-images.githubusercontent.com/113963320/204513280-ab104b3c-19a8-4a06-a2e4-16bf71e1a0a0.mov

**Comment by isabelastisser** [comment]
Not overdue.

**Comment by shonsirsha** [comment]
## Proposal

A lighter bg colour is shown when navigating between right-docked modal pages, e.g: Workspaces.

**To fix this, we could introduce a minimal change - which is the following:**

In `src/libs/Navigation/NavigationRoot.js`:
```diff
const navigationTheme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
-        background: themeColors.highlightBG,
+        background: themeColors.appBG,
    },
};
```

This maintains the background colour of `NavigationContainer` to be the same as the `ModalStackNavigators`, therefore a different (incorrect) colour won't be shown.

Web:

https://user-images.githubusercontent.com/28676406/204963154-84ce6172-bc75-4289-bf50-d90ecfd14d90.mov



Desktop:

https://user-images.githubusercontent.com/28676406/204963167-5d6a912a-2af7-441a-8adf-254ace42dcd1.mov

A lighter bg colour is not shown anymore ✅ 

Thanks! 🙂

**Comment by shawnborton** [comment]
Nice, yeah I agree we should use the appBG color here

**Comment by Julesssss** [comment]
Ideal 👍

**Comment by tienifr** [comment]
Hi @rushatgabhane  I just created [The PR](https://github.com/Expensify/App/pull/13242). Please help to review it

**Comment by Julesssss** [comment]
Merged awaiting deployment

**Comment by isabelastisser** [comment]
Update:

@tienifr and @rushatgabhane, I hired both of you for the job in Upwork.

**Comment by Julesssss** [comment]
> This was always present, right? The color difference just became more apparent when we switched to dark mode

Yeah, correct.

**Comment by isabelastisser** [comment]
Update: @tienifr and @rushatgabhane were paid!

The contract ended in Upwork.

**Comment by isabelastisser** [comment]
@Julesssss @rushatgabhane can you please update the checklist above? Thanks!

**Comment by Julesssss** [comment]
Hi @isabelastisser, I didn't check the boxes initially because it's not relevant here. This wasn't a regression and I think the checklist is often incorrectly added to every issue.

**Comment by isabelastisser** [comment]
Thanks for the heads up, @Julesssss ! Closing the issue then.

**Comment by isabelastisser** [comment]
@tienifr @rushatgabhane yes, I issued the bonus now. Thank you!
