### ISSUE TITLE
[HOLD #13230] Android: scrollToIndex out of range

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#13107]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On Android, send messages to a user until the chat becomes scrollable and you see the `New message` floating badge at the top
2. Mark the last message sent as unread
3. Delete the last message
4. Scroll up and tap the `New message` floating badge
5. Notice the error below
![Screenshot 2022-11-28 at 3 12 00 PM](https://user-images.githubusercontent.com/22219519/204392400-bcc718ea-cb28-4540-83f4-ecbafc0269b1.png)

## Expected Result:
No errors

## Actual Result:
Error shows up

## Workaround:
Yes

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
We are holding this as per [this comment](https://github.com/Expensify/App/pull/13089#issuecomment-1332584823)

**Comment by sakluger** [comment]
@luacmartins do you need me to do anything on this one? Given that there's no external reporters or contributors, and you already have a linked PR, I think I should likely be unassigned from this one.

**Comment by luacmartins** [comment]
@sakluger np! We can close this since we reverted the offending PR and this issue is no longer needed. Thanks for checking!
