### ISSUE TITLE
[$1000] Make background color of image previews in chat match dark app BG color

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
When viewing an image preview/thumbnail tile in chat, the background of the tile is white. You can see this when there is transparency of the image in the preview. We should make this color match the dark BG of the app instead of using white.

![image](https://user-images.githubusercontent.com/2319350/204385392-c802a72d-4d03-4117-a789-2b8ea13548f7.png)

## Expected Result:
Image preview thumbnail area should use dark app background color. 

## Actual Result:
Image preview thumbnail area uses white background.

## Workaround:
No workaround needed. 

## Platform:
Where is this issue occurring? All platforms

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01eb0a8e777b226bf9
- Upwork Job ID: 1597734936355745792

**Comment by Christinadobrzyn** [comment]
Ah interesting! Testing this: 

1. Sign into https://staging.new.expensify.com
2. Open a chat that's in dark mode - the text is not white
3. Click on your profile > the text is white

The text in the profile should match the dark BG of the app instead 

Another interesting note - is this expected @shawnborton 
5. When you open the profile, the text in the chat gets darker 
6. When you close the profile, the text in the chat gets lighter

![2022-11-29_14-32-07 (1)](https://user-images.githubusercontent.com/51066321/204456519-3e3e7a70-fecd-4930-acd5-7a5db88917fa.gif)

**Comment by shawnborton** [comment]
> Another interesting note - is this expected @shawnborton @grgia
> 5. When you open the profile, the text in the chat gets darker
> 6. When you close the profile, the text in the chat gets lighter

That is expected - it's the overlay color showing up on top of the content behind the rightDocked side pane. 

As for the original bug reported, the way to test it is to upload a PNG that has transparency in it. Here is a sample image you can use to test (save to your computer and try uploading it in NewDot):

![image](https://user-images.githubusercontent.com/2319350/204648921-ff7af5c1-eea0-457e-8be6-119140910d21.png)

**Comment by Christinadobrzyn** [comment]
Awesome! thank you @shawnborton! I think this can be an external job so adding all the labels.

**Comment by shawnborton** [comment]
I disagree with that approach. We don't need to manipulate the image in any way, we just need to quickly update the background color of the image thumbnails, and I think @grgia is on it.

**Comment by shawnborton** [comment]
Ahh interesting... I wonder if we should just do nothing here then?

**Comment by shawnborton** [comment]
Yeah, I'm leaning towards just closing this one though... I would imagine this is a bit of an edge case anyways and we can revisit later. Thoughts @JmillsExpensify ?

**Comment by JmillsExpensify** [comment]
Ah yeah, I think we should get through all the imaging and visual brand updates first. I agree with you. Let's close it out. We can circle back on this kind of polish.

**Comment by Christinadobrzyn** [comment]
Sounds like a plan. I'll close the [Upwork job](https://www.upwork.com/jobs/~01eb0a8e777b226bf9) and close down this GH. We can revisit this later. 

@JmillsExpensify or @shawnborton do you happen to know if we have any tracking GHs related to this that I should add this to so it's reconsidered in the future?

**Comment by shawnborton** [comment]
Sounds good, closing the issue now.
