### ISSUE TITLE
Android  -Chat - The compose field is covered by keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app > go to any chat
2. Start to enter message

## Expected Result:
The message field should be fully visible if the keyboard was open.

## Actual Result:
The message field is hidden if the keyboard was open.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/204403723-15d75850-ee86-4860-a242-1fb851c2d0cc.png" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/204403722-6926c346-c447-471f-8474-66e32534e0d9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
@luacmartins I don't know if we want to wait for https://github.com/Expensify/App/pull/13106, but looking through the checklist I think the only change that might've caused this is https://github.com/Expensify/App/pull/12988

**Comment by mananjadhav** [comment]
I am not sure if #12988 can cause the regression, as the code only removes one placeholder. No other change.

**Comment by mountiny** [comment]
Great investigation and fix @0xmiroslav 🙇

**Comment by Julesssss** [comment]
Confirmed this is resolved by [this PR](https://github.com/Expensify/App/pull/13106).

**Comment by luacmartins** [comment]
This is fixed by https://github.com/Expensify/App/pull/13106, closing!
