### ISSUE TITLE
An avatar with a gray background is not displayed in the chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open a group where a member with a gray avatar is present

## Expected Result:
A member with a gray avatar is visible in the group

## Actual Result:
An avatar with a gray background is not displayed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/204403199-93ee855e-e757-4279-9096-4788f85c6aae.jpg" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/204403203-7c6baf3a-a16c-4c0a-873d-a44969410e6e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
Let's see if I can fix this internally to speed this up. @sonialiap I will remove your assignment since the bug was reported by Applause so no bonus here to pay!

**Comment by pecanoro** [comment]
@kavimuru Could you send me the image that is being used for the avatar? I think the issue is related to that specific image.

**Comment by pecanoro** [comment]
Otherwise, I can't reproduce it, gray images work just fine for me.

**Comment by pecanoro** [comment]
@sonialiap Can you see if you can reproduce this one? Otherwise, we can close since I think it was just the format of the image they were using.

**Comment by kavimuru** [comment]
@sonialiap sorry for the delay.  It was a default avatar. This is the tester's acccount:  applausetester+0604lsn@applause.expensifail.com / w323052760We
