### ISSUE TITLE
Sidebar border is not clearly visible when brightness is low

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13147]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Goto https://staging.new.expensify.com/
2. Click on settings

## Expected Result:
Sidebar border is clearly visible

## Actual Result:
Sidebar border is not clearly visible

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** new UI
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Untitled (1)](https://user-images.githubusercontent.com/43996225/204623236-b445b2a6-1af3-435b-a312-23d97d52a001.jpg)
<img width="960" alt="6" src="https://user-images.githubusercontent.com/43996225/204623262-99d1c22f-9759-4a78-a1b1-4a887e67c7c7.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669715152574639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by allroundexperts** [comment]
### Proposal

We can just add a `borderLeft` to the `BaseScreenWrapper` component.

## Fix

```diff
diff --git a/src/components/ScreenWrapper/BaseScreenWrapper.js b/src/components/ScreenWrapper/BaseScreenWrapper.js
index 83408e6a3..e16bff91a 100644
--- a/src/components/ScreenWrapper/BaseScreenWrapper.js
+++ b/src/components/ScreenWrapper/BaseScreenWrapper.js
@@ -86,6 +86,7 @@ class BaseScreenWrapper extends React.Component {
                                 ...this.props.style,
                                 styles.flex1,
                                 paddingStyle,
+                                styles.borderLeft,
                             ]}
                         >
                             <KeyboardAvoidingView style={[styles.w100, styles.h100]} behavior={this.props.keyboardAvoidingViewBehavior}>

```

## Result

https://user-images.githubusercontent.com/30054992/204685791-3a0c476e-ff89-4f6d-b279-cf4f5dfcb365.mov

**Comment by shawnborton** [comment]
How would that look on smaller/mobile devices though? I don't think we want the left border on small devices, so we should consider that in the solution.

**Comment by allroundexperts** [comment]
@shawnborton Updated proposal. The border will show on large screens only.

**Comment by shawnborton** [comment]
Cool, let's wait for one of our engineers to weigh in - thanks!

**Comment by mdneyazahmad** [comment]
## Proposal

Already posted in slack https://expensify.slack.com/archives/C049HHMV9SM/p1669739748264159?thread_ts=1669715152.574639&cid=C049HHMV9SM

We can use the same pattern used in drawer sidebar to add border https://github.com/Expensify/App/blob/b35dba944cff88d5a2d7221dfa626f42d505d1c1/src/styles/StyleUtils.js#L75-L86.

https://github.com/Expensify/App/blob/5f89a98d80a3a25ec786198a97f347dde84bb132/src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js#L3

```diff
diff --git a/src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js b/src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
index 1e3634cff..b9922a218 100644
--- a/src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
+++ b/src/styles/getNavigationModalCardStyles/getBaseNavigationModalCardStyles.js
@@ -1,4 +1,5 @@
 import variables from '../variables';
+import themeColors from '../themes/default';
 
 export default isSmallScreenWidth => ({
     position: 'absolute',
@@ -7,4 +8,6 @@ export default isSmallScreenWidth => ({
     width: isSmallScreenWidth ? '100%' : variables.sideBarWidth,
     backgroundColor: 'transparent',
     height: '100%',
+    borderLeftWidth: isSmallScreenWidth ? 0 : 1,
+    borderLeftColor: themeColors.border,
 });
```

OR

use the function ternary operator as done in left sidebar. `isSmallScreenWidth` ? `styles` : `styles`.

<img width="1440" alt="Screenshot 2022-11-30 at 12 32 22 PM" src="https://user-images.githubusercontent.com/77761491/204729431-eef4ad68-4db1-4033-8c6e-960bcab68df7.png">

**Comment by shawnborton** [comment]
I'm actually wondering if we should just hold off on this. If we use a better overlay color, the sidebar is way easier to to digest and I think this style actually looks better:

![image](https://user-images.githubusercontent.com/2319350/204843332-294a4b9e-4762-4fbf-9f7a-0810a6bddf64.png)


cc @grgia I will spin up an issue for overlay colors today.

**Comment by shawnborton** [comment]
Okay, I'm going to close this one out in favor of a different overlay PR that I think we'll handle internally.
