### ISSUE TITLE
Reimburse expenses shows “Connect bank account” after relogin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace on NewDot
2. Click Connect bank account
3. Follow the steps in SO (internal) to create an OPEN bank account. Note that you must enter the exact information described.
4. After the beneficial owners page you will get to “One more thing”, at that point you have successfully added a bank account to the workspace and you can close the page.
5.  Go to the workspace settings > Reimburse expenses. Notice that you see “Fast reimbursements = happy members!”
6. Go back to the initial settings page and sign out
7. Go the workspace > Reimburse expenses

## Expected Result:
See “Fast reimbursements = happy members!”

## Actual Result:
See “Connect bank account”

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** Could not verify
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204614493-8f762dfb-c6a9-4490-a29e-713efd614b02.mp4

https://user-images.githubusercontent.com/43996225/204614462-eb5033bd-353d-49ca-860c-56257561a045.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669677043176149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
We already have an internal issue for this [here](https://github.com/Expensify/Expensify/issues/244855) so I'm going to close this.
