### ISSUE TITLE
Close Account - HTML tags and confusing wording in when closing account with workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Create a workspace and invite several members
3. Go to Settings/Security and Close account

## Expected Result:
Error message that is displayed when trying to close account with workspace shared with other users should be correctly displayed and should have correct wording.

## Actual Result:
Error message that is displayed when trying to close account with workspace shared with other users is displayed with HTML tags and includes word "policy" which might be confusing for a user that was using only NewDot, but not OldDot.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![screenshot_34](https://user-images.githubusercontent.com/93399543/204634356-655852c5-9318-4f55-8188-3b16a1b1ec4b.jpg)

https://user-images.githubusercontent.com/93399543/204634734-e477d34e-3cbe-4896-918a-d7d5ee2fc5b6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment]
Duplicate https://github.com/Expensify/App/issues/12747

**Comment by Beamanator** [comment]
Thanks for pointing this one out @kbecciv ! As @thesahindia mentioned (thanks!), I made that other issue to keep track of removing those HTML tags in the Close Account errors
