### ISSUE TITLE
[HOLD for payment 2022-12-15] New icon branding doesn't reflect in the link previews

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13155]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Copy the [new.expensify.com](http://new.expensify.com/) / [staging.new.expensify.com](http://staging.new.expensify.com/) link
2. Paste it in the social channels
3. Observe the logo preview

## Expected Result: 
New logo/favicon to show in the previews

## Actual Result: 
Old branding logo shows up

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33-2
**Reproducible in staging?:** Y
**Reproducible in production?:** New UI
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/43996225/204638405-c9e6f27f-914b-44c0-ba43-95d5cc71f433.png">
<img width="387" alt="6" src="https://user-images.githubusercontent.com/43996225/204638420-6276eefb-7329-4082-9a2a-e29f09a2dfd1.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mananjadhav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669721236397389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
@shawnborton do you know if we have or plan on making a new version of https://new.expensify.com/og-preview-image.png? I'm looking in web-static and https://use.expensify.com/press-kit but don't see anything new.

**Comment by shawnborton** [comment]
Here is a new one you can use: ![og-preview-image](https://user-images.githubusercontent.com/2319350/204668103-302c6620-5111-492f-bfaf-e0bb681fa38b.png)

[og-preview-image.png.zip](https://github.com/Expensify/App/files/10118040/og-preview-image.png.zip)

**Comment by francoisl** [comment]
This was only testable in production since the preview image's URL is hardcoded. It works well now.


<img width="643" alt="image" src="https://user-images.githubusercontent.com/2229301/206345051-d44c9b64-fc90-4a3e-814d-e87ae3bc5ff9.png">

**Comment by yuwenmemon** [comment]
https://www.youtube.com/watch?v=LhI88tg1Gqg&ab_channel=u3cL49W518

**Comment by mananjadhav** [comment]
@mateocole this is eligible for C+ review as well as reporting bonus.

**Comment by michaelhaxhiu** [comment]
Summary:
- The change was implemented as an `internal` fix, meaning an Expensify engineer made the actual PR.
- Then, C+ was automatically assigned to the `internal` PR (@mananjadhav) and did their part to review the checklist. They are owed $1000 for that review. 
- The same C+ (@mananjadhav) reported this issue and so they are owed $250 for that find.

Contest is in #expensify-open-source [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668726522584349) if you want to a refresher.

**Comment by mananjadhav** [comment]
That's correct @michaelhaxhiu and I think this is due for payout

**Comment by michaelhaxhiu** [comment]
Cool! 

Due tomorrow, right? 2022-12-15

**Comment by mateocole** [comment]
Alright @mananjadhav! Here is the Upwork: https://www.upwork.com/ab/applicants/1603414440910610432/job-details

**Comment by mateocole** [comment]
okay sent the offer, ill add the bonus once accepted

**Comment by mananjadhav** [comment]
Accepted @mateocole

**Comment by mateocole** [comment]
Good to go! you should see the payment soon.
