### ISSUE TITLE
Workspace - Delete workspace error icon & message do not appear for failed scenario

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13192]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Log into an account that has the necessary pre conditions applausetester@applause.expensifail.com
3. Navigate to Workspaces > Error Test
4. Disable the internet connection in the device
5. Click/Tap on the 3 dots and select "Delete Workspace"
6. Confirm the modal to delete the workspace
7. Verify the workspace is now displayed with a strikethrough indicating it will be deleted when back online
8. Enable the internet connection in the device

## Expected Result:
User should see a red dot on the profile icon and the workspace has an error below indicating "You cannot delete this workspace because it's set as the domain restricted one for a domain security group"

## Actual Result:
The user sees a red dot on the profile icon but the user does not see any error message on the workspace setting. The workspace that was deleted when offline also no longer shows

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204857469-94604769-a801-4194-b61c-881ef8ed5050.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
The backend is responding with the expected error:

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/87341702/204872580-f87c3bac-364a-4eed-b1bf-83beb87aa460.png">

**Comment by aldo-expensify** [comment]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/87341702/204872918-6857c0bf-c33f-4a8e-8e01-115a9df6dbf6.png">

The policy is still in Onyx, with the error, this looks fine...

**Comment by aldo-expensify** [comment]
This may be the PR that caused the regression: https://github.com/Expensify/App/pull/12971

I'm not sure why it is intentionally filtering out workspaces that have pending action 'delete':

**Comment by aldo-expensify** [comment]
Closed by mistake

**Comment by luacmartins** [comment]
Fix was merged. Closing this issue!

**Comment by luacmartins** [comment]
Thanks for the quick work @aldo-expensify!
