### ISSUE TITLE
Web - Login - The error in the console after login in HT account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with high traffic account

## Expected Result:
No error in the console after login in HT account

## Actual Result:
The error in the console after login in HT account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.34.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (6)](https://user-images.githubusercontent.com/93399543/204880373-83eb47f8-344f-4a96-8bd1-2f6bf288084c.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is [known](https://github.com/Expensify/App/pull/12780#issuecomment-1319816325) and will be fixed by  https://github.com/Expensify/Expensify/issues/243532. Closing!
