### ISSUE TITLE
 No space on the last message text LHN when sending blockquote and text from offline to online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to offline
2. Sending a message with blockquote and text
e.g:
>Blockquote
text
3. Go back online
4. Take note of the last message of the chat on LHN

## Expected Result:
The last message on LHN remains the same when sending a message with blockquote

## Actual Result:
The last message on LHN whitespace is missing and added back when the message send

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.32-1
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204971078-7d181b1a-27e7-4867-b193-bf3f790ced74.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mollfpr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669564594408699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mollfpr** [comment]
@kavimuru Sorry, I think the issue I report is the same with https://github.com/Expensify/App/issues/11494

**Comment by aldo-expensify** [comment]
> @kavimuru Sorry, I think the issue I report is the same with #11494

Yes! thanks for catching that.. closing!
