### ISSUE TITLE
Split Bill - Attendees can be selected/deselected on Final Review page of Split Bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login with HT Expensifail account
2. Click FAB
3. Click Split Bill
4. Input any amount and Click Next
5. Select several Attendees and click Next
6. Final Review page is displayed

## Expected Result:
User should not be able to select/deselect the attendees

## Actual Result:
Attendees can be selected/deselected on Final Review page of Split Bill

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/205313220-887ded27-6e90-40c4-8e7d-a6502b757c04.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is Failing on Final Review page section, Step 5 says "Verify that you cannot select/deselect the attendees". 
https://expensify.testrail.io/index.php?/tests/view/2971939

![image](https://user-images.githubusercontent.com/93399543/204956198-c9855eb0-c3a3-40e8-a2f2-7a4024dd73cd.png)

**Comment by marcaaron** [comment]
Linked video appears to be unrelated to the reproduction steps.

**Comment by s77rt** [comment]
### Proposal
```diff
diff --git a/src/components/IOUConfirmationList.js b/src/components/IOUConfirmationList.js
index 4f4eb415ed..1aa94e34f4 100755
--- a/src/components/IOUConfirmationList.js
+++ b/src/components/IOUConfirmationList.js
@@ -275,27 +275,24 @@ class IOUConfirmationList extends Component {
         const shouldShowSettlementButton = this.props.iouType === CONST.IOU.IOU_TYPE.SEND;
         const shouldDisableButton = selectedParticipants.length === 0;
         const recipient = this.state.participants[0];
-        const canModifyParticipants = !this.props.isIOUAttachedToExistingChatReport && this.props.hasMultipleParticipants;
 
         return (
             <OptionsSelector
                 sections={this.getSections()}
                 value={this.props.comment}
-                onSelectRow={canModifyParticipants ? this.toggleOption : undefined}
                 onConfirmSelection={this.confirm}
                 onChangeText={this.props.onUpdateComment}
                 textInputLabel={this.props.translate('iOUConfirmationList.whatsItFor')}
                 placeholderText={this.props.translate('common.optional')}
                 selectedOptions={this.getSelectedOptions()}
-                canSelectMultipleOptions={canModifyParticipants}
-                disableArrowKeysActions={!canModifyParticipants}
-                isDisabled={!canModifyParticipants}
+                disableArrowKeysActions
+                isDisabled
                 hideAdditionalOptionStates
                 forceTextUnreadStyle
                 autoFocus
                 shouldDelayFocus
                 shouldTextInputAppearBelowOptions
-                optionHoveredStyle={canModifyParticipants ? styles.hoveredComponentBG : {}}
+                optionHoveredStyle={{}}
                 footerContent={shouldShowSettlementButton
                     ? (
                         <SettlementButton
```

### Details
`canModifyParticipants` is redundant and not desired as we can go back and modify the participants. Also since it's the confirmation page it's more appropriate to be read only

**Comment by marcaaron** [comment]
@s77rt Please wait until issues are triaged.

**Comment by trjExpensify** [comment]
Happened across this issue. Agree the video reproduction doesn't match, but also, we should confirm this is only a bug with the "global create > Split bill" flow. It's expected in the "Group DM > + > Split bill" flow (where all the chat participants of an existing group chat are preselected and can be deselected).  

Related PR from a while back for reference: https://github.com/Expensify/App/pull/5895

**Comment by kavimuru** [comment]
@trjExpensify @marcaaron Correct video attached.

**Comment by kavimuru** [comment]
@trjExpensify In the PR #5895
> If bill split flow initiated via FAB, we will Not Allow attendee deselection on bill split confirmation page.
> If bill split flow initiated from Group Chat we will Allow attendee deselection on bill split confirmation page.

But it is contradictory, Able to select / deselect attendee if initiated from FAB and not able to if initiated from Group DM

**Comment by trjExpensify** [comment]
Thanks for adding the video! 

>But it is contradictory, Able to select / deselect attendee if initiated from FAB and not able to if initiated from Group DM

It actually says the opposite to that, which is correct, so it's not contradictory to the below?  

>we should confirm this is only a bug with the "global create > Split bill" flow. It's expected in the "Group DM > + > Split bill" flow (where all the chat participants of an existing group chat are preselected and can be deselected).

**Comment by tgolen** [comment]
I'll go ahead and swap the logic for this.

**Comment by sobitneupane** [comment]
@stephanieelliott I am C+ in the [PR](https://github.com/Expensify/App/pull/13279). Can you please help with the payment.

**Comment by stephanieelliott** [comment]
Hey @sobitneupane, sorry for the wait on this! I've created the job in Upwork to make the C+ payment, can you please claim it when you get a chance? https://www.upwork.com/jobs/~0114c5212c5918f200

**Comment by sobitneupane** [comment]
@stephanieelliott Accepted the offer

**Comment by sobitneupane** [comment]
@stephanieelliott
Waiting for the payment.

**Comment by stephanieelliott** [comment]
Thanks for the bump @sobitneupane and sorry for the wait, all paid up!
