### ISSUE TITLE
A refresh of the app is needed in order for "Mark as unread" / "mark as read" to sync between multiple active devices.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Have the app open on 2 devices A & B
2. Mark a message as unread in device A, navigate to another chat
3. Observe that device B still has the message as read. A refresh is needed in order to get the message to show as unread.
4. Repeat the same for "read messages"

## Expected Result:
Message should show unread without refreshing

## Actual Result:
Message shows as unread only after refreshing the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204969770-6748b9f3-fc4e-4743-bdbb-25df4bbda197.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669727667934739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Taking this, but won't get to it before next week.

**Comment by flodnv** [comment]
This is not super important, demoting to weekly for now, in favor of deprecating sequence numbers project.

**Comment by aldo-expensify** [comment]
This gets solved by sending this update on the pusher:

https://github.com/Expensify/Web-Expensify/blob/a69e770c332c80d7345a769774a9618bbb70d237/lib/ReportAPI.php#L4195-L4201


```diff
- $onyxData[] = [
+ Onyx::pushUpdatesToClients([$accountID], [[
    'onyxMethod' => Onyx::METHOD_MERGE,
    'key' => OnyxKeys::COLLECTION_REPORT.$reportID,
    'value' => [
        'lastReadSequenceNumber' => $lastReadSequenceNumber,
    ],
+ ]]);
- ];

```

but then the I have a question. If we are pushing for having the sessions in across multiple devices in sync, should we push everything and never return like this:

https://github.com/Expensify/Web-Expensify/blob/a69e770c332c80d7345a769774a9618bbb70d237/lib/ReportAPI.php#L4241

Each time we choose to return the Onyx update in the request response, we won't be syncing across devices

**Comment by aldo-expensify** [comment]
PR up

**Comment by aldo-expensify** [comment]
Closing, the fix is in production and passed QA
