### ISSUE TITLE
Workspace -View all bills icon does not match the provided screenshots under Pay bills and Send invocies

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13222]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13109 and comment here https://github.com/Expensify/App/pull/13109#issuecomment-1329881610

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Settings- Workspace - Pay bills
4. Check the View all bills icon
6. Go to Send invoices
7. Check the View all bills icon

## Expected Result:
View all bills icon should match the provided screenshot

## Actual Result:
View all bills icon does not match the provided screenshots under Pay bills and Send invoices

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34.0

**Reproducible in staging?:** Yes

**Reducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (10)](https://user-images.githubusercontent.com/93399543/204960551-cd4eca71-f806-4a56-86cf-f24e0204496a.png)

![image (9)](https://user-images.githubusercontent.com/93399543/204960552-1fc7018b-d5bf-4a0d-bd53-b00f8a8dfde4.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mollfpr** [comment]
The reason why the icon is different because when testing the https://github.com/Expensify/App/pull/13109, https://github.com/Expensify/App/pull/12796 is not yet merged where in that PR, where we change the invoice icon.

**Comment by luacmartins** [comment]
Agreed with @mollfpr. The icons are correct in staging right now. Closing this issue.

![invoices](https://user-images.githubusercontent.com/22219519/205097391-cacf09c4-99d6-4ec3-881f-d07e16d401e4.png)
![bills](https://user-images.githubusercontent.com/22219519/205097381-f1c918e9-9655-48d1-b8be-3dd70c6f2a30.png)
