### ISSUE TITLE
C+ review for Migrate from reportAction timestamp to created

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#13234]
This is to track payment to @mananjadhav for reviewing this PR https://github.com/Expensify/App/pull/12540#issuecomment-1333213790 which is linked to this internal issue.

**Comment by mountiny** [comment]
@mananjadhav what is an appropriate payment for that review and testing please?

**Comment by mananjadhav** [comment]
I think this requires a bump because this was a relatively large PR, with 20 files. 

But I would also like to highlight there was a test failure in this issue. (though when I tested I think it did run well don't remember exactly). I am not sure if that counts as a regression. If yes, then the current internal rate should be fine.

**Comment by mountiny** [comment]
> But I would also like to highlight there was a test failure in this issue. (though when I tested I think it did run well don't remember exactly). 

Oh I remember that failure and that is not regression, that was not failing during the review but showed up later.

Apologies fo rnot being clear these processes are updated quite often but I found a Slack post here https://expensify.slack.com/archives/C01GTK53T8Q/p1668726522584349 which mentions the internal PRs are reviewed for flat rate of $1000. Is that good for you? otherwise we would need to start a discussion in #contrbutor-plus, we need to make sure these things have rules which can be followed.

**Comment by mananjadhav** [comment]
I think 1000$ is fine, because I didn't complete the Android Push notification test for the task. Thanks for clarifying.

**Comment by mananjadhav** [comment]
Based on the discussion in the [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1669905679029849), good with the default payout of 1000$

**Comment by mountiny** [comment]
Thanks for raising this @mananjadhav Never be afraid of raising any questions 🙇

**Comment by mananjadhav** [comment]
@isabelastisser Can you help with the payout here?

**Comment by mananjadhav** [comment]
Hence I tagged her with the comment!

**Comment by isabelastisser** [comment]
Sorry for the delay, @mananjadhav ! Working on this now.

**Comment by mananjadhav** [comment]
No worries. Thanks for the help here @isabelastisser

**Comment by isabelastisser** [comment]
Jobs created in Upwork:

https://www.upwork.com/jobs/~016a303c0a3627f286

https://www.upwork.com/ab/applicants/1598642490185367552/job-details

**Comment by mananjadhav** [comment]
Applied @isabelastisser

**Comment by isabelastisser** [comment]
Paid! Thanks @mananjadhav !

**Comment by mananjadhav** [comment]
Thanks for the quick help here @isabelastisser.

And thank you @mountiny for tracking this.
