### ISSUE TITLE
[HOLD for payment 2022-12-20] When you open or create a group chat and tap the Details page (top of page), the last added user in the list blinks and appears.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open or create a group chat with least 4 or 5 people.
2. Tap into the Details page (tap the top of the group, where the list of chat members are shown)
3. Notice that the latest user blinks and appears right after you open the Detail Page.

## Expected Result:
The last user should display as any other user.

## Actual Result:
The last user is the only one that blinks.

## Workaround:
>N/A, this doesn't need a workaround. It's a UI inconsistency.

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y

https://user-images.githubusercontent.com/43996225/205194063-0182b308-5805-40ee-bab7-666d3d8495c5.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669655454960459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01742c10c259cf2467</li>
        <li>Upwork Job ID: 1605247001485320192</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
I wonder whether this is actually a bug, or more of a choice that was made somewhere for performance reasons to limit the number of members rendered in the list ahead of loading the rest of the participants? We should confirm that. 

For example, you can reproduce in a #room with way more than 4/5 participants. It's not the "last participant" that is delayed loading, it's all participants beyond `4`.

**Comment by aldo-expensify** [comment]
> I wonder whether this is actually a bug, or more of a choice that was made somewhere for performance reasons to limit the number of members rendered in the list ahead of loading the rest of the participants? We should confirm that.

> For example, you can reproduce in a #room with way more than 4/5 participants. It's not the "last participant" that is delayed loading, it's all participants beyond 4.

You are right about this being there for performance reasons, but the recommended number is a number that is enough to fill the screen: https://reactnative.dev/docs/flatlist#initialnumtorender. The code is here:

https://github.com/Expensify/App/blob/367119d312f2af3675ecce8fbccf283b41062a42/src/components/OptionsList/BaseOptionsList.js#L232

`initialNumToRender={5}` is too small in my opinion. This depends on the size of the screen, but I think a number around 12 would work better.

**Comment by aldo-expensify** [comment]
I reproduced this in Android so I added it to the list of devices.

**Comment by aldo-expensify** [comment]
I'm trying to figure out if we can calculate this number based on the screen size or if we should just pick a fixed higher number like "12"

**Comment by michaelhaxhiu** [comment]
Hmm if we are going to expand to a number like 12, are we calling this a `New Feature` or `Bug`?


I was able to reproduce this and noticed one of the avatars in the group (Alberto's) also didn't load instantly like the others:


https://user-images.githubusercontent.com/13206896/206470131-7720d349-651c-4de2-a8ca-8b0a519b2118.MP4

**Comment by michaelhaxhiu** [comment]
After brewing a little, I think this is an element of WAQ. I posted in slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1670509449335419?thread_ts=1669655454.960459&cid=C049HHMV9SM) to get input from others!

**Comment by trjExpensify** [comment]
Yeah, we talked about that in thread. I agree to not conflate the two, and I also think it will likely be solved by the image caching PRs.

**Comment by aldo-expensify** [comment]
I'll just go with the simple solution of hardcoding 12 elements (no dynamic calculation). I think that should be enough for most devices. Sounds good?

**Comment by aldo-expensify** [comment]
PR ready for review:  https://github.com/Expensify/App/pull/13425

**Comment by michaelhaxhiu** [comment]
>noticed one of the avatars in the group (Alberto's) also didn't load instantly like the others

I'll check on the related GH here https://github.com/Expensify/App/issues/10792

**Comment by michaelhaxhiu** [comment]
This wasn't a pure bug, but rather something where we expanded existing support in the list of users. No need to add a regression test with that in mind.

**Comment by michaelhaxhiu** [comment]
@hungvu193 can you apply to the upwork job (above) for the $250 reporting bonus?

**Comment by michaelhaxhiu** [comment]
Removing @sobitneupane as that's erroneous. This was already fixed internally.

**Comment by hungvu193** [comment]
> @hungvu193 can you apply to the upwork job (above) for the $250 reporting bonus?

I've just applied

**Comment by mallenexpensify** [comment]
@hungvu193 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01742c10c259cf2467

**Comment by hungvu193** [comment]
> @hungvu193 can you please accept the job and reply here once you have? 
> 
> https://www.upwork.com/jobs/~01742c10c259cf2467
> 
> 

Applied! Thank you

**Comment by mallenexpensify** [comment]
Thanks @hungvu193 , you're all paid.  
I think this one can be closed now.  Comment/reopen if needed
