### ISSUE TITLE
Desktop - Concierge - Distorted screen appears instead of Concierge chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13125

## Action Performed:
1. Launch the app and log in
2. Open console from developer tools and enter this.document.location = "https://staging.new.expensify.com/concierge"

## Expected Result:
The concierge chat is displayed

## Actual Result:
Distorted screen appears instead of Concierge chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.35.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** 

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2022-12-01 at 4 54 01 PM](https://user-images.githubusercontent.com/93399543/205170544-f30d43d0-7740-4910-a936-09d49c7e4f64.png)

https://user-images.githubusercontent.com/93399543/205170546-da8eede0-1863-4611-9d31-0f806c176baa.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I was not able to reproduce this in my local environment. 

https://user-images.githubusercontent.com/1228807/205347911-b6c619c0-177a-4539-b350-3234e56ec4b5.mp4
