### ISSUE TITLE
[HOLD for payment 2023-01-13] Uploading all-black PNG avatar makes it impossible to see the image

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#13266]
Only recently (after fixing [this issue](https://github.com/Expensify/App/issues/11063)) we starting being able to upload `png` images as avatars.

# Problem

We have a solid black background in the Avatar image crop modal, so when all-black PNGs (that have transparent parts) are uploaded, we can't see where the edge of the image is vs the black background (see vid [here](https://github.com/Expensify/App/pull/12549#issuecomment-1334143477)). Also, having an all black background is confusing when uploading PNG images, because it like we converted the transparent background to black, though that was fixed in the issue linked ^

# Solution

TBD. My idea is to use some kind of checkboard background pattern (I believe this is used in most websites that show pngs) so there's no issue where a solid colored PNG gets completely hidden among the background.

**Comment by Beamanator** [comment]
Here's my first attempt, which has solid black & transparent checkboard pattern. This is a big dark in "dark mode" but still works pretty well.

https://user-images.githubusercontent.com/3885503/205261280-ff5af170-0bc2-423c-a376-038a4f2914ab.mov

**Comment by Beamanator** [comment]
@shawnborton asking for your thoughts on this, I was thinking we could brighten up the "light" squares (which are dark gray in this instance)

**Comment by shawnborton** [comment]
Hmm what if we just didn't use pure black for the BG and used the dark green we use for the app BG? I think I would prefer to avoid adding the checkerboard pattern, especially since this is likely a very uncommon occurrence.

**Comment by Beamanator** [comment]
Hmm well to be clear we could make the checkerboard only be visible on the background of PNG images, otherwise the avatar image selected would fill the entire window (no checkerboard). I think it's uncommon that the entire PNG being uploaded is the same as the background (black or even dark green) but I do think it's more common that a part of PNG could match the full background

Also I think it's a bit confusing that the background is solid black or even dark green, but once the PNG loads, the background we show everywhere is gray... So At least those should be consistent, right?

**Comment by shawnborton** [comment]
> but once the PNG loads, the background we show everywhere is gray... 

Can you show me what that looks like?

**Comment by shawnborton** [comment]
Ah I see now. Well if that's the background color we show elsewhere in the app, what if we just reuse that same background color for the upload UI? Then we at least have the consistency there.

**Comment by Beamanator** [comment]
Ya I think that makes the most sense for now 👍

**Comment by shawnborton** [comment]
Okay cool, so let's just do that small change and call it a day?

**Comment by Beamanator** [comment]
That's a good plan! Do you think it makes sense to have the light gray background on all screens **for light mode** & the dark green background on all screens **for dark mode**? Orrrrr maybe it's fine to have the background light gray always. I can make some mockups if you think that would help :D

**Comment by shawnborton** [comment]
Well I guess we don't have light mode right now... so I think for now we can just make the simple change to use the greenIcon color as the BG color for now?

**Comment by Beamanator** [comment]
Haha very true, I'll test that out next week if I have time before heading OOO and we'll see how it looks!

**Comment by shawnborton** [comment]
Not overdue

**Comment by Beamanator** [comment]
PR in review

**Comment by Beamanator** [comment]
@strepanier03 assigned you via the Bug label to please help pay out @eVoloshchak as the C+ who reviewed the PR for this issue: https://github.com/Expensify/App/pull/13925

Thanks!

**Comment by strepanier03** [comment]
@eVoloshchak - Please apply for the job [here](https://www.upwork.com/jobs/~01ef1e6f659894f2d4) and let me know once you do so I can move forward. Thank you!

**Comment by eVoloshchak** [comment]
@strepanier03, applied
The PR wasn't deployed to production yet, the same 1 week regression period applies here too, correct?

**Comment by Beamanator** [comment]
No regression, this is just how it has always worked until now

**Comment by strepanier03** [comment]
Thank you for applying @eVoloshchak - that is correct. The payment is held until 2022-01-12. I have accepted your application and sent the offer.

**Comment by Beamanator** [comment]
Looks like the PR somehow got merged into production twice? 🤷  so marking the latest comments as duplicate & fixing the title

**Comment by strepanier03** [comment]
The contract has been paid in Upwork since today is the 13th. Thank you for the review on this one @eVoloshchak!
