### ISSUE TITLE
[$1000] Create a linter to require descriptions for all javascript files

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#13267]
Context https://expensify.slack.com/archives/C03TQ48KC/p1669802336357159

# Problem

Sometimes, when we add new classes/files, we don't add a description explaining what the file does, forcing people wanting to know what the file does to read the whole code

# Solution

Add a new linter that requires you to add a comment at the top f the file explaining what the file does.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f858786c092eda5</li>
        <li>Upwork Job ID: 1598633913934622720</li>
        <li>Last Price Increase: 2022-12-08</li>
    </ul>
</details>

**Comment by tgolen** [comment]
@iwiznia I'm not really sure we need this. If files require a description to understand what they are for, then I think the problem is in the name or the location of the file. 

Can you give some examples of where this has been a problem?

My biggest concern is that this is going to end up like method descriptions where 95% of the descriptions are pointless and low value.

**Comment by iwiznia** [comment]
I don't have one handy right now, but I know I nodded when @flodnv posted this https://expensify.slack.com/archives/C03TQ48KC/p1669802336357159

**Comment by henriquefalconer** [comment]
### Proposal

A flexible solution, with selection of which type of file should have a linting error, is possible with these alterations:

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index f509613d88..4c0fc88cd2 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -5,6 +5,9 @@ module.exports = {
     env: {
         jest: true,
     },
+    rules: {
+        'file-comment-check': 'error',
+    },
     settings: {
         'import/resolver': {
             node: {
```

```diff
diff --git a/package.json b/package.json
index 849ee69d72..59ecdb6df0 100644
--- a/package.json
+++ b/package.json
@@ -27,7 +27,7 @@
     "android-build": "fastlane android build",
     "android-build-e2e": "bundle exec fastlane android build_e2e",
     "test": "jest",
-    "lint": "eslint . --max-warnings=0",
+    "lint": "eslint . --max-warnings=0 --rulesdir rules",
     "lint-watch": "npx eslint-watch --watch --changed",
     "print-version": "echo $npm_package_version",
     "storybook": "start-storybook -p 6006",
```

And adding a new `rules/file-comment-check.js` file:

```js
const _ = require('underscore');

module.exports = {
    meta: {
        type: 'problem',
        docs: {
            description: 'require descriptive comment on top of file',
        },
        fixable: 'code',
    },
    create(context) {
        return {
            Program(node) {
                if (_.some(node.comments, comment => comment.start === 0)) { return; }

                if (!context.getFilename().match(/\.(native|ios|android|website|desktop)\.js$/)) { return; }

                context.report({
                    node,
                    message: 'File does not contain descriptive comment on top of file.',
                });
            },
        };
    },
};

```

This only reports an linting error when filename ends with `.native.js`, or any other variation. This rule can also be changed so that only the needed examples are reported.

Also, a selection based on file content instead of just filename could be implemented, further using the object `context`.

**Comment by iwiznia** [comment]
Some discussion here https://expensify.slack.com/archives/C049HHMV9SM/p1669979037476299

**Comment by tgolen** [comment]
@henriquefalconer Thanks for working on that proposal! I'm still trying to narrow down what requirements we want, but if we're doing a custom ESLint rule, it should be added to https://github.com/Expensify/eslint-config-expensify. We should also do a little research and see if someone else has created an ESLint rule for this.

**Comment by henriquefalconer** [comment]
Sure thing! From my research, https://github.com/Stuk/eslint-plugin-header seems to be a hit. Still, it doesn't have a file-specific check, so a custom ESLint rule seems to me a pretty reasonable way to solve this. Will await further instructions!

**Comment by AbdulRehmanMehar** [comment]
**Proposal**

I created an eslint plugin according to your needs. Here's the link to it: [eslint-plugin-eslint-file-description](https://www.npmjs.com/package/@abdulrehmanmehar/eslint-plugin-eslint-file-description)

Here's a video that shows it in action: [Recording Link](https://drive.google.com/file/d/1eEDS7PZ9Zq0zKUXoShQQp9Ni0hkmUi10/view?usp=sharing)

**Comment by MitchExpensify** [comment]
Discussion ongoing here https://expensify.slack.com/archives/C03TQ48KC/p1669802336357159

**Comment by AbdulRehmanMehar** [comment]
@MitchExpensify I'm not authorised to see the discussion but do inform me whenever the acceptance criteria is locked.

**Comment by MitchExpensify** [comment]
@grgia did [the Slack discussion](https://expensify.slack.com/archives/C03TQ48KC/p1669802336357159) give us some tangible next steps here? Keen to keep this moving along

**Comment by grgia** [comment]
cc @iwiznia - could you give an update on how you think we should move forward? Or is the conversation still ongoing?

**Comment by MitchExpensify** [comment]
I'm heading ooo so need to reassign a CM - Reapplying the External label (Will remove delete Upwork Job it creates too as we have one already)

**Comment by iwiznia** [comment]
Ah sorry, will update shortly

**Comment by iwiznia** [comment]
Sorry about this, after some discussion, we decided to put this in the checklists instead, so we don't add descriptions for files that don't really need them.
