### ISSUE TITLE
Step 4 of VBA flow has border radius issue. 

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#13287]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

Go through the VBA flow until you hit step 4 and verify that you see this:
<img width="302" alt="Screen Shot 2022-12-02 at 12 11 12 PM" src="https://user-images.githubusercontent.com/49007721/205377522-5f821aa2-959a-45d1-a841-b71cb8c9ecdd.png">

## Expected Result:
Describe what you think should've happened

Looks reasonable ha

## Actual Result:
Describe what actually happened

Looks like screenshot above. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
**Proposal**

If the border isn't required we can take that class out from the view

https://github.com/Expensify/App/blob/835e9d2e25a278ad0d37d47403b1ebdce1f7dac5/src/pages/ReimbursementAccount/ACHContractStep.js#L229

`<View key={index} style={[styles.p5, styles.mb2]}>`

Or if the border is required we can apply
`borderRadius: variables.componentBorderRadius`

https://github.com/Expensify/App/blob/835e9d2e25a278ad0d37d47403b1ebdce1f7dac5/src/styles/styles.js#L619

**Comment by Luke9389** [comment]
Hey y'all I've already spun up a fix for this. Sorry, I should have marked this internal.

**Comment by Christinadobrzyn** [comment]
Shouldn't there be a C+ assigned with this `internal` label? Removed and added it and nothing changed.

**Comment by francoisl** [comment]
Applause finished QAing https://github.com/Expensify/App/pull/13298, closing this blocker.
