### ISSUE TITLE
[HOLD #10312] Chat - Text "New Message" is out alignment in badge.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Navigate to a 1:1 conversation that has a large history of messages.
3. Scroll the conversation a little and tap hold/hover over a message from the other user and mark the message as "Unread"
4. Scroll further up the conversation and verify a "New Messages" button appears

## Expected Result:
All text should be in correct alignment in the app.

## Actual Result:
Text "New Message" is out alignment in badge.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (13)](https://user-images.githubusercontent.com/93399543/205398007-951c4348-099f-4c6a-b5a4-56800c2a2713.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adhamhassan99** [comment]
I also realized something, when I mark a message as unread and focus a different message then come back to the earlier marked message it appears as if it didn't register as unread.

**Comment by aneequeahmad** [comment]
### PROPOSAL

### Problem: 
Css property `styles.alignItemsCenter` was missing in the file `floatingMessageCounter` on `line # 81` in the view which was 

```
 <View style={[styles.flexRow]}> 
```

**Solution:**

Adding `styles.alignItemsCenter ` in line # 81 fixes the issues

https://github.com/Expensify/App/blob/30d5a21d0685d92b694ea608d9ef49a9827cbaf2/src/pages/home/report/FloatingMessageCounter/index.js#L81

Do nothing for this issue as this will be fixed when the version `1.2.36-0` is deployed on production as this problem has been fixed by merging the PR #10312 in the main which is done today in commit #aed921f1f8

**Comment by sonialiap** [comment]
Can confirm the same behavior

<img width="527" alt="image" src="https://user-images.githubusercontent.com/17131195/205675604-c702abf0-ca74-4a25-93d8-6771a217bdb5.png">

**Comment by sonialiap** [comment]
@adhamhassan99 please open a new issue for this
> I also realized something, when I mark a message as unread and focus a different message then come back to the earlier marked message it appears as if it didn't register as unread.

**Comment by PauloGasparSv** [comment]
Thank you very much @aneequeahmad! I just tested main and the changes you suggested that already exist in the P.R.  https://github.com/Expensify/App/pull/10312 align the badge vertically.

Before changes:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6564265/205686659-5f7326a8-f5eb-4fc0-854b-3dab8e8d92b8.png">

After Changes:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6564265/205686678-d713e3c7-094c-44b1-ab66-637a7751a8a7.png">

I'll put the GH on HOLD https://github.com/Expensify/App/pull/10312 is deployed to staging. Then I'll test again but on my physical device and close this if the issue doesn't persist.

**Comment by PauloGasparSv** [comment]
The P.R. was deployed to staging, the Web versions seems fixed:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/6564265/206530051-83850f53-9571-4bf4-94bb-36adeb099b5e.png">

But the mobile version is still not aligned for me here. I'm testing on the iOS and Android emulator to see if the fix only worked for web.

**Comment by PauloGasparSv** [comment]
The emulated latest version of main has the correct alignment (had to confirm that) so it may be a problem with the version in my phone. I'll wait till the next TestFlight version of the app is released to test again and close this.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/6564265/206533373-226b5d9c-ca07-4f4c-a4d4-44f837c69549.png">

**Comment by PauloGasparSv** [comment]
Great, the pill is aligned on my physical device too!
Closing this off : )

**Comment by aneequeahmad** [comment]
@PauloGasparSv Thats great,Good to hear that. Am i eligible for the solution that i suggested ? as it fixes the problem like you said and have tested.

**Comment by aneequeahmad** [comment]
@PauloGasparSv Any thoughts ?

**Comment by PauloGasparSv** [comment]
Oh my, sorry the delay @aneequeahmad! I had to double check with the team to make sure.
 
I believe In this case you are not eligible, sorry : /
