### ISSUE TITLE
Chat - Emojis are switching from big size to small

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12968

## Action Performed:
1. Launch the app
2. Log in with any account
3. Compose a message by:
3.1 Add an emoji
3.2 Add two or more empty lines
3.3.Add an emoji
4. Send it

**Offline testing**
1. Go to a chat
2. Go offline, this way we make sure you are seeing the data produced by the frontend and not what came from the backend
3. Compose a message by:
3.1. Add an emoji
3.2 Add two or more empty lines
3.3 Add an emoji
4. Send the message
6. Back online

## Expected Result:
Emojis should be the same size

## Actual Result:
Emojis are switching from big size to small

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205395655-a35f0880-85d8-429a-a1f2-b26d8b2b5fcd.mp4

https://user-images.githubusercontent.com/93399543/205395684-5f6ea47e-4dec-4346-8d68-54704a053cae.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I don't see anything obvious in the staging PRs list

**Comment by marcaaron** [comment]
Could it be caused by this -> https://github.com/Expensify/App/pull/12968 ?

Not really sure what controls the size of these emojis and will have to look into that first

**Comment by marcaaron** [comment]
Are these fonts? Could it be related to this -> https://github.com/Expensify/App/commit/08fa35d7d2f7525c5464fccc52ebcae8c9c2af12 @Luke9389

**Comment by marcaaron** [comment]
Also cc @stitesExpensify as "the emoji guy" just in case 😄

**Comment by aldo-expensify** [comment]
This is probably self resolved (trying to confirm but staging is slooow).

The Web-Expensify PR https://github.com/Expensify/Web-Expensify/pull/35658 dealing with these changes was deployed just 5 hours ago to staging. The same changes were applied to the front in these two PRs: https://github.com/Expensify/App/pull/12968 and https://github.com/Expensify/expensify-common/pull/474 which made it to production faster. This made the backend and frontend produce inconsistent results when converting from `html` to `text` and when creating `lastMessageText`, but this should not be the case anymore for staging.

**Comment by marcaaron** [comment]
Oh nice so... can we close?

**Comment by Luke9389** [comment]
It looks like we can
