### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Expensify logo appearing twice in desktop notifications

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#13296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Download the electron app
2. Sign into any account (account A) and enable notifications (Settings > Preferences)
3. Switch to another app, such as Chrome
4. Using another account (account B), send a message to account A

## Expected Result:
Notifications have exactly one app logo

## Actual Result:
Notifications have two app logos 
![Screenshot 2022-12-01 at 17 11 58](https://user-images.githubusercontent.com/1127863/205400398-e0b0d619-0f48-48d6-bee4-54dce390f03d.png)

## Workaround:
None

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669936372056859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f01501157ad25355</li>
        <li>Upwork Job ID: 1602286461797154816</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
@shawnborton @grgia Did we want to keep this issue internal? Or shall I triage it out to contributors?

**Comment by JmillsExpensify** [comment]
I see that @aimane-chnaif reviewed the linked PR, so I'm going to go ahead and create an Upwork issue so that we can pay him when that PR hits production. I'll also assign to issue as well! 🙌🏼

**Comment by JmillsExpensify** [comment]
Returning on Tuesday, so perfect timing to close this one out at that point.

**Comment by JmillsExpensify** [comment]
@aimane-chnaif I circled back to pay you out here, but I'm oddly only seeing a "re-hire" option on the Upwork job above. Do you have an existing contract for this issue already?

**Comment by JmillsExpensify** [comment]
While I'm at it, @grgia @shawnborton what is your plan for regression tests around colors, buttons, logos and fonts? My understanding is that we don't have any regression tests for the most recent visual design refresh, but I think part of creating a premium app is making sure that the look/feel stays consistent. I wasn't able to find an existing set of tests for all these things in TestRail, so it'd be good to align.

**Comment by grgia** [comment]
I opened an issue [here](https://github.com/Expensify/Expensify/issues/247948) to start tracking Dark Mode changes for TestRail steps. My thought is we can define the regression steps once the final pieces of core branding (colors/fonts/logos) are completed. This can definitely be worked on now, I've just been focusing on implementing/testing bug fixes recently.

One other option we could think about in the future is some kind of screenshot regression testing, but I think that's better for later on as our branding is still evolving and changing.

**Comment by JmillsExpensify** [comment]
@aimane-chnaif You're all paid out!
