### ISSUE TITLE
 Text field overlaps with compose bar when editing message

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#13303]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a chat
2. Send a message
3. Right click on the message
4. Click edit
5. Check the left border of the edit composer and confirm it does not overlap with the compose bar

## Expected Result:
Text field should display without any overlap 

## Actual Result:
Text field has a rectangular overlap with the compose bar 

![image](https://user-images.githubusercontent.com/16747822/205413433-fa3e318d-1ffe-42c1-b366-4d6e3e0fda2b.png)

## Workaround:
N/A doesn't impact usability 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.36-0 main
**Reproducible in staging?:** No
**Reproducible in production?:** No 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670020210074769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I think this has been merged already. Just not deployed to production. Or maybe it has been deployed and the comment failed?

**Comment by puneetlath** [comment]
Looks like this went to production last week. Just need to pay out @thesahindia for reporting, then close.

**Comment by puneetlath** [comment]
@thesahindia can you accept the hiring offer I just sent? 

For me: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/22700588

**Comment by thesahindia** [comment]
>@thesahindia can you accept the hiring offer I just sent?

Accepted, thanks!

**Comment by puneetlath** [comment]
All paid!
