### ISSUE TITLE
[HOLD for regression tests] New Room-An error message "Invalid reportName" appears when entering a long name for New Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13312]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Put on FAB button -> New Room
4. Enter the long name for New Room
5. Choose the workspace from the dropdown menu
6. Click "Create room"

## Expected Result:
The new room is created

## Actual Result:
An error message "Invalid reportName" appears when entering a long name for New Room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205496845-c0e83bed-fd81-4701-85d0-867741af4203.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01519fd144a2d452d5</li>
        <li>Upwork Job ID: 1606449256443441152</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by s77rt** [comment]
I think you uploaded the wrong video

**Comment by Puneet-here** [comment]
### Proposal 

We get an error when using 80 character long name. It's not possible to add more than 80 characters at room name. 
We can lower this and we should show an error because there isn't any error right now
https://github.com/Expensify/App/blob/2e8d90736a19de0bf0332fb36afc42bab074434f/src/CONST.js#L321

We need to add a validation here
https://github.com/Expensify/App/blob/2e8d90736a19de0bf0332fb36afc42bab074434f/src/pages/workspace/WorkspaceNewRoomPage.js#L91
```js
        if (ValidationUtils.doesFailCharacterLimit(CONST.REPORT.MAX_ROOM_NAME_LENGTH, this.state.roomName)) {
            errors.roomName = this.props.translate('newRoomPage.exceededCharLimit');
        }
```

**Comment by miljakljajic** [comment]
Hey Andrew! What do you think of Puneet's proposal above?

**Comment by dhairyasenjaliya** [comment]
is it reproducible? I'm getting an invalid room while saving with max character 

<img width="370" alt="Screenshot 2022-12-05 at 5 45 48 PM" src="https://user-images.githubusercontent.com/47522946/205635320-252f3d75-61f5-44b2-9440-c0c61f1938f3.png">

**Comment by miljakljajic** [comment]
It's reproducible for me in Chrome: 


<img width="962" alt="image" src="https://user-images.githubusercontent.com/28715117/205645199-ae6af4cc-fbbe-49be-a498-92d41829a9d1.png">

**Comment by Gonals** [comment]
I'll grab this to fix it quickly!

**Comment by mallenexpensify** [comment]
@aimane-chnaif can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01519fd144a2d452d5

**Comment by mallenexpensify** [comment]
Paid @aimane-chnaif 
Leaving open and weekly for regression test steps, @aimane-chnaif and @miljakljajic please check the boxes above.  I'll try to help this week @miljakljajic since I'm around.

**Comment by miljakljajic** [comment]
Thank you for issuing payment, @mallenexpensify ! This seems to be the most [relevant test ](https://expensify.testrail.io/index.php?/cases/view/1971088&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229067) - does it need to be updated to confirm we're showing the error message if the room name is too long? This is the current test:

> - Set the name of the #Room to anything you'd like
> - Take note of the settings in the modal and create the room
> - Verify the room is created, the name and settings are correct and match what was configured in the create room mod

**Comment by mallenexpensify** [comment]
Yea @miljakljajic that looks like the right spot.  I think a new Step 9 and 10
9. Edit the room name to make the name long (~100 characters?). 
10. Verify the new long name works and that there are no errors showing.

**Comment by miljakljajic** [comment]
@Gonals / @aimane-chnaif what does `maxLength={CONST.REPORT.MAX_ROOM_NAME_LENGTH}` mean? I just want to understand how the character limit is being applied so I know how to word the testing correctly.

**Comment by miljakljajic** [comment]
Right, but what is the character limit actually? @mallenexpensify has suggested testing with a 100 character long name, would that be sufficient? 

> 9. Edit the room name to make the name long (~100 characters?)

**Comment by miljakljajic** [comment]
Buddy check here: https://expensify.slack.com/archives/C01SKUP7QR0/p1673536900354209

**Comment by miljakljajic** [comment]
TestRail updated - good to go. Thank you everyone!
