### ISSUE TITLE
Desktop -  new messages are not displayed in chats

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#13327]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open Desktop app 
2. Navigate to any new message from LHN 
3. Send few new messages

## Expected Result:
All the messages should display in chats 

## Actual Result:
Messages display in LHN but not displayed in chat. Only older messages displayed in chat 

## Workaround:
Sign out, and sign back into the app.

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![2cydDe8Hwu](https://user-images.githubusercontent.com/43995119/205696472-9ecd2e52-14c4-4c0e-b0b7-c4a68e63209c.gif)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1670258567349939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
More context [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1670258567349939). I was able to resolve by signing out/in, and can no longer reproduce.
