### ISSUE TITLE
[HOLD for payment 2022-12-20] Text is clipped on iOS sign in page

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#13336]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open New Expensify app. 
2. go to the login page
3. type an email address that has a ‘g’ in it (e.g. user@gmail.com)

## Expected Result:
bottom of ‘g’ *isn’t* clipped

## Actual Result:
bottom of ‘g’ *is* clipped

## Workaround:
N/A user can still use New Expensify 

## Platform:

- iOS

**Version Number:** v1.2.36-1
**Reproducible in staging?:** No
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/16747822/205727892-cf3305fc-a157-4a49-95e7-dc6adad2b3d8.png)

**Expensify/Expensify Issue URL:** N/A

**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** [conversation 1](https://expensify.slack.com/archives/C049HHMV9SM/p1670005270049759), [conversation 2](https://expensify.slack.com/archives/C049HHMV9SM/p1670261113497909)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5cab80b99e5d1f4</li>
        <li>Upwork Job ID: 1600914332989022208</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
<b>Proposal</b>
This cause by the line height of the text input, when the text inside TextInput is bigger than the lineheight, this issue happened.
<b>Solution</b>
We can remove the lineHeight or set it to undefined.
```diff
    baseTextInput: {
        fontFamily: fontFamily.EXP_NEUE,
        fontSize: variables.fontSizeNormal,
+       lineHeight: undefined,
-       lineHeight: variables.fontSizeNormalHeight,
        color: themeColors.text,
        paddingTop: 23,
        paddingBottom: 8,
        paddingHorizontal: 11,
        borderWidth: 0,
    },
```

Result:

![simulator_screenshot_FF649684-CA66-4A11-9AAC-5EC4CEE91DCB](https://user-images.githubusercontent.com/16502320/205796497-36e46e4d-3e76-4957-bfe7-4170fd495fb6.png)
<img width="1024" alt="Screen Shot 2022-12-06 at 09 45 34" src="https://user-images.githubusercontent.com/16502320/205796531-b2910bfc-c0e3-451a-a011-aae77922dd55.png">

**Comment by joekaufmanexpensify** [comment]
Triaging: 

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment]
Reproduced in iOS: 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/54866469/205992814-25120421-8875-44f3-a339-6dd1773c8308.png">

**Comment by joekaufmanexpensify** [comment]
@NikkiWines I'm assuming this one is good to be external?

**Comment by fedirjh** [comment]
### Proposal

I think there was a mistake when refactoring font variables , instead of applying `variables.lineHeightNormal` it was applied `variables.fontSizeNormalHeight`

https://github.com/Expensify/App/blob/8bd81db9546f8d05506e47a3cbd0955917662562/src/styles/styles.js#L734-L740

```diff
    baseTextInput: {
        fontFamily: fontFamily.EXP_NEUE,
        fontSize: variables.fontSizeNormal,
-       lineHeight: variables.fontSizeNormalHeight,
+       lineHeight: variables.lineHeightNormal,
        color: themeColors.text,
        paddingTop: 23,
        paddingBottom: 8,
        paddingHorizontal: 11,
        borderWidth: 0,
    },
```

**Comment by NikkiWines** [comment]
@joekaufmanexpensify was going to handle it myself since it's such an easy fix, hence not applying the labels `External` labels yet. 

@hungvu193, @fedirjh, please be aware that issues that aren't marked as `External` may be worked on internally. For more details please see the [propose a solution for the job](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) section of the contributing readme

**Comment by joekaufmanexpensify** [comment]
PR is up and under review!

**Comment by Santhosh-Sellavel** [comment]
@joekaufmanexpensify I'm eligible for reporting bonus here.

**Comment by joekaufmanexpensify** [comment]
Re-opening to handle payment.

**Comment by joekaufmanexpensify** [comment]
Okay, we need to issue two payments here: 

- $250 reporting payment to @Santhosh-Sellavel 
- $1,000 for PR review to @mollfpr

**Comment by joekaufmanexpensify** [comment]
Temporarily added external label to create upwork job.

**Comment by mollfpr** [comment]
@joekaufmanexpensify applied, thanks!

**Comment by joekaufmanexpensify** [comment]
Great! Hired both of you.

**Comment by joekaufmanexpensify** [comment]
Once the PR is deployed to the product, the 7 day waiting period will begin, and then payment will be issued after that.

**Comment by Santhosh-Sellavel** [comment]
Cool thanks!

**Comment by jatinsonijs** [comment]
In iOS another issue occurred after these changes.
Emoji clipped on iOS on **What’s it for** input

1. Open any chat.
2. Press on plus button and send money.
3. Fill amount and then press next.
4. Fill What’s it for field with text and emoji’s

https://user-images.githubusercontent.com/114683042/206697816-b8042ac1-788a-41a2-92bb-2fb6a7ec3809.mov

**Comment by mollfpr** [comment]
@jatinsonijs What version are you at? I can't reproduce it on `v1.2.37-1`.

https://user-images.githubusercontent.com/25520267/206747442-9e33c5ef-1bec-4ff8-bad7-0a316332407d.mov

**Comment by jatinsonijs** [comment]
@mollfpr 
Version: 1.2.37-1 (Staging)

**Comment by mollfpr** [comment]
Thanks, @jatinsonijs I can reproduce it with iPhone 11.

@NikkiWines @joekaufmanexpensify Any action we should take here?

**Comment by NikkiWines** [comment]
Got it working! I can reproduce on an iPhone 14, they're just everrrrr so slightly cut off. Also tested on an iPhone 12 mini and iPhone 11 and the effect is most pronounced on the iPhone 11. Spinning up a fix now

<img width="378" alt="image" src="https://user-images.githubusercontent.com/16747822/206783798-42651332-8358-461a-bc62-998e8b31e6e0.png">

| iPhone 14 | iPhone 11 |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 14 - 2022-12-09 at 11 28 27](https://user-images.githubusercontent.com/16747822/206783637-a8a9c7da-4f7d-4263-828c-da41d39f0515.png) | ![Simulator Screen Shot - iPhone 11 - 2022-12-09 at 11 38 36](https://user-images.githubusercontent.com/16747822/206783665-2855a38a-9e81-4a39-a8b3-770ce920a08d.png) |

**Comment by NikkiWines** [comment]
Oh actually looking into it further it looks like using emojis on the signin page also has the same issue, here's a screenshot from an iPhone 11. Maybe we should update the input to be `lineHeightLarge` instead of `lineHeightNormal`

**lineHeightNormal - iPhone 11**
<img width="339" alt="Screenshot 2022-12-09 at 11 55 40" src="https://user-images.githubusercontent.com/16747822/206786042-a30703d0-2428-4724-9c18-909626ce3ce8.png">

**lineHeightLarge - iPhone 11**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/16747822/206785820-91e56a8b-3d83-424a-8a67-f6d12fdac870.png">


(Doesn't seem to make a difference on other platforms, so updating it should be fine) 
**lineHeightNormal - Web**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/16747822/206786134-2b21ced9-50c4-4a3e-8692-3796b82800ad.png">

**lineHeightLarge - Web**
<img width="701" alt="image" src="https://user-images.githubusercontent.com/16747822/206785884-bf2856e4-68a3-467d-83e9-0eaff6ce184d.png">

cc: @shawnborton maybe we should increase the height for `lineHeightNormal` if it's causing issues on smaller viewports like the iPhone 11?

**Comment by shawnborton** [comment]
I believe @Luke9389 is looking into this with his inputs PR. Also, just to confirm, this doesn't only affect smaller viewports right? I feel like no matter the viewport, we're still having input issues on iOS.

**Comment by joekaufmanexpensify** [comment]
We're looking into fixing the additional issue here.

**Comment by NikkiWines** [comment]
@shawnborton it seems to be present to various degrees across multiple iOS device sizes. It's barely visible on the `iPhone 14 Pro Max` but definitely still there.

<img width="87" alt="image" src="https://user-images.githubusercontent.com/16747822/207151905-890d3161-3ccf-44e1-b62f-120cd6af89e4.png">


| iPhone 14 Pro Max | iPhone 11 |  iPhone SE (3rd generation) |
| ------------- | ------------- | ------------- |
| <img width="452" alt="Screenshot 2022-12-12 at 12 50 39" src="https://user-images.githubusercontent.com/16747822/207151808-f67cf657-7d1a-4d52-8c49-226772e4acd1.png"> | <img width="476" alt="Screenshot 2022-12-12 at 12 46 47" src="https://user-images.githubusercontent.com/16747822/207151203-09616ebd-45a5-4e99-88ac-57bb45cd51f0.png"> |  <img width="474" alt="Screenshot 2022-12-12 at 12 48 50" src="https://user-images.githubusercontent.com/16747822/207151514-d749617e-5109-4e3e-ad73-3fbbc877db5d.png"> |
| <img width="315" alt="image" src="https://user-images.githubusercontent.com/16747822/207151766-fc172d2c-6f39-4913-8993-cc1ae4276108.png"> | <img width="314" alt="Screenshot 2022-12-12 at 12 47 02" src="https://user-images.githubusercontent.com/16747822/207151268-e5c5b5bc-aadb-4fcc-9ec9-bd083a21ce93.png"> | <img width="321" alt="image" src="https://user-images.githubusercontent.com/16747822/207151477-400ac466-ab8e-45b6-b434-290bc6f20dbe.png"> |

**Comment by Luke9389** [comment]
Yep, can confirm that this is being fixed in [this PR](https://github.com/Expensify/App/pull/12447)

**Comment by jatinsonijs** [comment]
> On iOS another issue occurred after these changes. Emoji clipped on iOS on **What’s it for** input
> 
> 1. Open any chat.
> 2. Press on plus button and send money.
> 3. Fill amount and then press next.
> 4. Fill What’s it for field with text and emoji’s
> 
>  emoji-cut.mov

Hi @NikkiWines just want to confirm it will consider under regression report bonus or not ?

**Comment by NikkiWines** [comment]
@jatinsonijs, yep, I think you should receive a regression report bonus for this. cc: @joekaufmanexpensify

**Comment by shawnborton** [comment]
To clarify, why would @jatinsonijs get a report bonus? I feel like what was reported there was the same thing that @Santhosh-Sellavel originally reported?

**Comment by NikkiWines** [comment]
Similar bugs, not quite the same. Normal text is no longer clipped (here's an iOS screenshot from my PR tests [here](https://github.com/Expensify/App/pull/13389), but emojis.

<details closed>
<summary>iOS Screenshot</summary>
<br>

![image](https://user-images.githubusercontent.com/16747822/207423178-73d7663f-5275-4815-9b8e-39187c9e57e6.png)

</details>

**Comment by Santhosh-Sellavel** [comment]
Recent font changes could also may be a problem, I guess.

**Comment by Luke9389** [comment]
Just want to reiterate that I've got this one covered in this PR: https://github.com/Expensify/App/pull/12447
I see you're doing the RCA, but just putting this here for posterity. 👍

**Comment by joekaufmanexpensify** [comment]
Next step is bug zero checklist

**Comment by joekaufmanexpensify** [comment]
@Luke9389 Just for my own understanding as we finish up this issue, your most recent message means that you're fixing the regression that was reported [here](https://github.com/Expensify/App/issues/13336#issuecomment-1344220792) in the PR you linked, right?

**Comment by joekaufmanexpensify** [comment]
Okay, just summarizing payment next steps as we approach tomorrow: 

- @Santhosh-Sellavel - $250 for reporting the bug originally. 
- @mollfpr - $500 for PR review (This is reduced by 50% from $1000 originally as this PR introduced a regression). 
- @jatinsonijs - bonus for regression reporting. I believe this is also $250, but am confirming internally.

**Comment by joekaufmanexpensify** [comment]
Proposed new regression test [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1671490452675119)

**Comment by joekaufmanexpensify** [comment]
Great, thanks for confirming!

**Comment by jatinsonijs** [comment]
> Okay, just summarizing payment next steps as we approach tomorrow:
> 
> * @Santhosh-Sellavel - $250 for reporting the bug originally.
> * @mollfpr - $500 for PR review (This is reduced by 50% from $1000 originally as this PR introduced a regression).
> * @jatinsonijs - bonus for regression reporting. I believe this is also $250, but am confirming internally.

@joekaufmanexpensify can you plz confirm, should I apply on https://www.upwork.com/jobs/~01c5cab80b99e5d1f4 ?

**Comment by joekaufmanexpensify** [comment]
Yes please do. You'll get $250 regression reporting bonus.

**Comment by jatinsonijs** [comment]
> Yes please do. You'll get $250 regression reporting bonus.

Thanks, done

**Comment by joekaufmanexpensify** [comment]
@jatinsonijs Great! Just extended offer.

**Comment by joekaufmanexpensify** [comment]
@mollfpr $500 payment sent!

**Comment by joekaufmanexpensify** [comment]
@Santhosh-Sellavel $250 payment sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Linked regression test above in BZ checklist. All that's left here is to pay the regression reporting bonus, and then the last few items for @NikkiWines and @mollfpr in the [BZ checklist](https://github.com/Expensify/App/issues/13336#issuecomment-1349858344).

**Comment by jatinsonijs** [comment]
@joekaufmanexpensify I have accepted the contract.

**Comment by mollfpr** [comment]
>  [@mollfpr / @NikkiWines] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Slack thread [here](https://expensify.slack.com/archives/C049HHMV9SM/p1671637209503109)

**Comment by joekaufmanexpensify** [comment]
@jatinsonijs payment sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Job is closed in upwork. @mollfpr and @NikkiWines are working on their [remaining BZ checklist steps](https://github.com/Expensify/App/issues/13336#issuecomment-1349858344), and then we can close this!

**Comment by joekaufmanexpensify** [comment]
I'm going to be OOO from tomorrow - January 2nd. All that's left here is the [engineering section of the BZ checklist](https://github.com/Expensify/App/issues/13336#issuecomment-1349858344). I'm going to change this to weekly in the interim, as this is not urgent. 

@NikkiWines and @mollfpr, if you have a chance to finish up the BZ checklist before then, that's great. If not, I'll change the prioritization back to daily when I'm back so we can finish this up.

**Comment by NikkiWines** [comment]
BZ checklist is completed, any further discussion can happen in [the BZ slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1671637209503109). Closing
