### ISSUE TITLE
[HOLD for payment 2022-12-20] Workspace settings: Wrong color for avatar outline when the `Workspaces` row hovered

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace settings page
2. Hover over `Workspaces`

## Expected Result:
Color should match the dark theme 

## Actual Result:
Incorrect black color appears in the avatar outline

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/43996225/205767209-151ddb6c-8ca4-4e02-95d1-8a8629faf0c7.png">
<img width="960" alt="11" src="https://user-images.githubusercontent.com/43996225/205767231-6fd5847c-47cb-4106-acb8-31b6d75ad27d.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670279508149949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@shawnborton what's the right color to use here? Or are we just going for something like this?

<img width="942" alt="2022-12-05_14-30-45" src="https://user-images.githubusercontent.com/32969087/205776345-937e7274-2cd8-472e-a7f0-cb7dc9ba811c.png">

**Comment by shawnborton** [comment]
Exactly, it should just match the hover or pressed state color. You should also test this one with multiple workspaces too.

**Comment by marcaaron** [comment]
Aha - guessing this is **not** what we want for the multiple workspaces 😄 

<img width="826" alt="2022-12-05_15-01-46" src="https://user-images.githubusercontent.com/32969087/205780063-2463f65e-03a5-413b-b983-167f94aec0f4.png">

**Comment by shawnborton** [comment]
Haha exactly, we want that border overlap effect but we want that border to change colors on hover/press

**Comment by marcaaron** [comment]
https://user-images.githubusercontent.com/32969087/205785514-8ad14fa0-e1ea-4e76-a269-468b9495ae4c.mp4

**Comment by shawnborton** [comment]
:chefkiss:

**Comment by mananjadhav** [comment]
@marcaaron Can you assign someone from the BZ team to help with the upwork payment here? This is due for payment today.

**Comment by sakluger** [comment]
Created an Upwork post: https://www.upwork.com/ab/applicants/1605689986122805248/job-details (External post: https://www.upwork.com/jobs/~01b870c982e69c593d) and sent an offer to @mananjadhav.

**Comment by mananjadhav** [comment]
Accepted offer @sakluger

**Comment by sakluger** [comment]
Paid! Closing out the issue.
