### ISSUE TITLE
Mini context menu Tooltip displayed before the actual element gets hovered

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Take the cursor near to mini context menu item
2. tooltip gets displayed

## Expected Result:
Tooltip should displayed once the menu item element hovered

## Actual Result:
Tooltip displayed by hovering menu item nearer area

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
[9078159e-e186-490b-be75-72b090189043.webm](https://user-images.githubusercontent.com/43996225/205732567-5ca65d57-23b8-4ea4-a909-9a4171bb9d5e.webm)

https://user-images.githubusercontent.com/43996225/205732580-beaec88d-6a64-456a-962d-114e2ffd200b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670246360145559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
**Proposal**

Seems margin is causing the issue as it is provided to the Pressable inside of the Tooltip child. To solve we need an extra parent View wrapper to the Tooltip where we will apply this margin and remove it out from the Pressable in ContextMenuItem.js

**Comment by marcaaron** [comment]
I don't think this is a bug. There's a larger hit box for these elements so if you can hover over it then it should show the tooltip.

**Comment by Pujan92** [comment]
> I don't think this is a bug. There's a larger hit box for these elements so if you can hover over it then it should show the tooltip.

Just to inform the larger marginal part is not clickable even though we are showing the tooltip.

**Comment by marcaaron** [comment]
Sorry, it seems you are right and I am wrong. Though, it's a matter of pixels and I'm not sure if this is worth solving. That said, would not protest if someone feels strongly that we should fix this.

**Comment by Pujan92** [comment]
Ok, as the cursor changes to a pointer and we are not allowing the user to click I think it will be a bad user experience. But in case the team strongly feels to consider it and reopen then kindly consider my proposal. Thanks.
