### ISSUE TITLE
[Hold for payment 2022-12-20] Priority Mode options is not changing to selected language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings - Preference - Change language to Spanish/English
2. Observe Priority Mode Value

## Expected Result: 
Priority Mode Value should be changed to selected language

## Actual Result: 
Priority Mode Value is not changing to selected language

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/205735622-153a1a21-052c-4633-b29a-74cbcfe9280e.mov
<img width="960" alt="7" src="https://user-images.githubusercontent.com/43996225/205735741-2dc8784f-60d1-46f0-95c6-88731532c2b0.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670258478133289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a252bf33ccff5da7</li>
        <li>Upwork Job ID: 1612915826937843712</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I'll work on this one

**Comment by luacmartins** [comment]
Introduced [here](https://github.com/Expensify/App/pull/13299), moving the logic to the constructor prevents the component from updating. I'll work on a fix tomorrow morning.

**Comment by luacmartins** [comment]
@slafortune I believe the only thing left here is the reporting bonus payment to @varshamb. Could you please help with that?

**Comment by luacmartins** [comment]
Created regression test issue [here](https://github.com/Expensify/Expensify/issues/253195). Only missing payment now.

**Comment by luacmartins** [comment]
Bump for payment

**Comment by slafortune** [comment]
Shoot!  Sorry for missing this - on it now!

**Comment by mallenexpensify** [comment]
Apologies @aimane-chnaif , needed to add `Internal` label to get get job created (this is an edge case and shouldn't continue to happen) 

@varshamb can you please accept the job and reply here once you have?   
https://www.upwork.com/jobs/~01a252bf33ccff5da7

**Comment by varshamb** [comment]
> Apologies @aimane-chnaif , needed to add `Internal` label to get get job created (this is an edge case and shouldn't continue to happen)
> 
> @varshamb can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01a252bf33ccff5da7



> @varshamb can you please accept the job and reply here once you have?

Accepted!

**Comment by slafortune** [comment]
Thanks @varshamb ! Paid!
