### ISSUE TITLE
[HOLD for payment 2022-12-20] Update the wordmark to new version

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13379]
It looks like we're using the old wordmark still (on bottom of Sign In page), I think we forgot to add this one to our logo update. 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2319350/206028452-70a10733-a889-41c7-a0a4-e23b34143c08.png">

Here is the correct version to use: [expensify-wordmark.svg.zip](https://github.com/Expensify/App/files/10170477/expensify-wordmark.svg.zip)

Let me know if you plan to take this one internally @grgia 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e66cfed5ec3669d</li>
        <li>Upwork Job ID: 1606447863928066048</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by grgia** [comment]
I'll whip up a PR now!

**Comment by mallenexpensify** [comment]
Disregard @mananjadhav , needed to create a job to pay Sahil
@thesahindia can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~011e66cfed5ec3669d

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by mallenexpensify** [comment]
@thesahindia paid $1000. Closing cuz I don't think we need to add a regression test step and there's not a checklist
