### ISSUE TITLE
Lock /App issues until the `external` label is added

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#13395]
In order to ensure fairness in compensation, and also avoid proposals being added to /App issues before the external label is added – per our contributor guidelines, let's lock all issues upon creation. They can subsequently be unlocked once we're aligned on the path forward, and the work is specifically for external contributors.

**Comment by dylanexpensify** [comment]
@marcaaron any updates on this?

**Comment by dylanexpensify** [comment]
posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670933824757829) to update #expensify-open-source
