### ISSUE TITLE
[$250 Internal] Notifications not being received 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#13392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem

Multiple platforms are not receiving notifications in the production/staging environment. 

## Platform:

Where is this issue occurring?

- Android ✅ 
- iOS ✅ 
- Web?
- Desktop?

**Version Number:**  1.2.33-7 1.2.34-1 1.2.35-0, 1.2.36-2,
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** ALL
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1670408581155829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Given that this already is on prod it should not be a deploy blocker, but it is a major issue that needs to be resolved ASAP

**Comment by Julesssss** [comment]
interestingly I did receive a single push notification from Chronos on the latest prod build. Not receiving messages from other accounts though: 

![Screenshot_20221207_110727](https://user-images.githubusercontent.com/10736861/206234264-805fa140-36f8-46b5-82e8-296766a4b9cb.png)

**Comment by Julesssss** [comment]
I built a debuggable release build and discovered that we're hitting [this condition](https://github.com/Expensify/App/blob/6eca5384fedb19af85e2e4a6b8984b563c34908f/src/libs/actions/Report.js#L1270-L1273). It makes sense that I'm not seeing notifications, but it does seem odd that this wasn't previously an issue. 

![Screenshot 2022-12-07 at 17 34 00](https://user-images.githubusercontent.com/10736861/206250913-65af2a30-15b8-4ff4-ba2b-58a85d388c4b.png)

**Comment by Julesssss** [comment]
> Same to me. I haven't received any notifications recently even on web localhost. I remember this was working before. If this is open to external, I will try to find regression and propose solution.

Thanks, but no this needs to be internal. It's critical, and is likely a backend issue.

**Comment by Julesssss** [comment]
Looking into these PRs: 
- https://github.com/Expensify/Web-Expensify/pull/35748/files - 'Async pusher notification failed', we recently started to see notifications with no data being sent: 
- https://github.com/Expensify/Web-Expensify/pull/35572 - recently changed notification logic
- https://github.com/Expensify/Web-Expensify/pull/35741 - unlikely, but sounded related

I can confirm this is a recent config change issue, as I can receive notifications when directly targeting my device from the Airship console:
 
![Screenshot_20221212_160842](https://user-images.githubusercontent.com/10736861/207095361-2bf64cd2-c2ab-475f-87f9-95dbf5625f59.png)

**Comment by Julesssss** [comment]
Next step is to dive into the logs. I found examples of successful and failed notifications. 

[Here's](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22775cc060ccc723bb-SJC%22)+AND+timestamp:[2022-12-07T09:59:22.482Z+TO+2022-12-07T11:59:22.482Z]&index=logs_expensify-019868) one of the failed messages. Notice that we route it via Pusher instead of Airship. 

![Screenshot 2022-12-12 at 17 04 18](https://user-images.githubusercontent.com/10736861/207107965-5f11295e-24d3-4669-a5a7-6d5fa8bfef27.png)

[Here are logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22775cca76ae6523db-SJC%22)+AND+timestamp:[2022-12-07T10:06:18.153Z+TO+2022-12-07T12:06:18.153Z]&index=logs_expensify-019868) for a successful push notification send (from Chronos). 

____________

### Theories: 

1) Have we rotated keys? 
2) Are we somehow accidentally setting `shouldFailToSend` to true (we recently switched to staging)
3) Send via [Pusher async](https://github.com/Expensify/Web-Expensify/blob/cf4ee3ec8080a609e07d273700d3cca8ffa50f26/lib/Push/API.php#L261), OR just end via [Pusher](https://github.com/Expensify/Web-Expensify/blob/cf4ee3ec8080a609e07d273700d3cca8ffa50f26/lib/Push/Service.php#L99)
 in Web-E because we're using the staging server?! We recently switched from prod to staging...
4) A recent Web-E change. I've been through all PRs from the last week and those [suspicious PRs mentioned above](https://github.com/Expensify/App/issues/13392#issuecomment-1346881820) don't show an obvious bug
5) Other PRs? [A](https://github.com/Expensify/Web-Expensify/pull/35658/files), [B](https://github.com/Expensify/Web-Expensify/pull/35658/files#diff-7a032f7284c8b42392fb9715c5196b05b34ebeb369ee31387f702a26980eb792), [C](https://github.com/Expensify/Web-Expensify/pull/35711/files#diff-7a032f7284c8b42392fb9715c5196b05b34ebeb369ee31387f702a26980eb792)

**Comment by Julesssss** [comment]
Okay, I think I found[ the regression](https://github.com/Expensify/Web-Expensify/pull/35653#issuecomment-1346960703). Just need to confirm before I revert it.

**Comment by Julesssss** [comment]
Just noting that my previous guesses were wrong 😅 

I found the issue and a PR is [in review](https://github.com/Expensify/Web-Expensify/pull/35811)

**Comment by Julesssss** [comment]
Notifications are fixed -- just requires that users sign out and in again. Closing.

**Comment by Christinadobrzyn** [comment]
Upwork job - Internal - https://www.upwork.com/ab/applicants/1603246366811955200/job-details
External - https://www.upwork.com/jobs/~01cc93fd22b5099ef9

Hired @parasharrajat as reporter for the $250 payment. 

@Julesssss or @parasharrajat can you confirm this job is finished and can be paid out/closed? I think it is based on the PR - https://github.com/Expensify/Web-Expensify/pull/35811

**Comment by Julesssss** [comment]
Hey @Christinadobrzyn, yep the issue was resolved and deployed.

**Comment by Christinadobrzyn** [comment]
@parasharrajat when you have a moment, can you please accept the offer so I can pay you? Thanks! 

https://www.upwork.com/jobs/~01cc93fd22b5099ef9

**Comment by Christinadobrzyn** [comment]
Thanks @parasharrajat! I paid you as the reporter, closed the Upwork job and am closing this! Let me know if I've missed anything!
