### ISSUE TITLE
[HOLD for payment 2022-12-20] Failed to load PDF message color should be white for dark theme - reported by Santhosh-Sellavel

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#13406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat with PDF sent as attachment
2. Go offline
3. Try to open attachment
4. Error show

## Expected Result:
The shown error should be visible clearly

## Actual Result:
Not visible clearly as the text is in black

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670440109874269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Posted on the regression test [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1671629995081639)

**Comment by mallenexpensify** [comment]
Hired @rushatgabhane and @Santhosh-Sellavel can you please accept the job and reply here once you have?

**Comment by Santhosh-Sellavel** [comment]
@mallenexpensify I think everyone got paid here, this one is already taken care of by @bfitzexpensify.

**Comment by mallenexpensify** [comment]
I'm a bit confused so I'll wait for @bfitzexpensify to return.  I currently see 
- @rushatgabhane **hasn't** been paid $1000 for https://www.upwork.com/jobs/~01dbe3d022381e671c
- @Santhosh-Sellavel **has** been paid $250 for reporting.

**Comment by bfitzexpensify** [comment]
Good catch @mallenexpensify. Paid and ended the contract for @rushatgabhane.

**Comment by bfitzexpensify** [comment]
Regression test update complete.

**Comment by aldo-expensify** [comment]
Are we ready to close this?

**Comment by mallenexpensify** [comment]
Looks like it!
