### ISSUE TITLE
Formatted link would contains incorrect hyperlink for parameters that has several underscores

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :
Open [staging.new.expensify.com](http://staging.new.expensify.com/)
Open a chat and send this :  `[_example link_](https://www.facebook.com/hashtag/__main/?__eep__=6)`

## Expected Result : 
The link would redirect to `https://www.facebook.com/hashtag/__main/?__eep__=6`

## Actual Result : 
The link would redirect to `https://www.facebook.com/hashtag/em_main/?__eep_/em=6` (some of the underscores has been replaced with em word)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206268848-70469ea3-d055-4072-a72c-1848939fdb6d.mp4

https://user-images.githubusercontent.com/43996225/206268867-d3bb53ea-1884-43c2-bf46-3cb5b3a3d893.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670396697746919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment]
Snagging this one to fix internally

**Comment by alex-mechler** [comment]
expensify-common changes up in review. Will have to bump the version in App after it is merged

**Comment by Santhosh-Sellavel** [comment]
@alex-mechler Assign me this so I can track payment for PR Review thanks!

**Comment by alex-mechler** [comment]
Ah yes, thanks for the reminder!

**Comment by Santhosh-Sellavel** [comment]
@alex-mechler Bump for payment!

**Comment by alex-mechler** [comment]
@muttmuure Can you handle paying out @Santhosh-Sellavel for their pr review? Thanks!

**Comment by alex-mechler** [comment]
@muttmuure Bump :D

**Comment by muttmuure** [comment]
Job is [here](https://www.upwork.com/jobs/~0158751fd16cd5428b) @Santhosh-Sellavel plz apply! 

@kerupuksambel you also get $250 for reporting

**Comment by kerupuksambel** [comment]
@muttmuure , thank you so much. I just applied a job to the link provided.

**Comment by Santhosh-Sellavel** [comment]
Applied thanks @muttmuure

**Comment by muttmuure** [comment]
PR merged within 3 days. Applying bonus

**Comment by muttmuure** [comment]
Everyone has been paid

**Comment by Santhosh-Sellavel** [comment]
@muttmuure bonus is not applicable here as it is an internal PR, So I issued a Refund for 500$, thanks!
