### ISSUE TITLE
[HOLD for payment via NewDot] Localize OS desktop menus

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#13414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
All the context menu items are in English no matter what language you select:

![image](https://user-images.githubusercontent.com/6474442/206306452-ebc3ab37-3293-4511-a53b-6c94afbc9a89.png)

![image](https://user-images.githubusercontent.com/6474442/206306585-cfeed9c6-31b2-487e-a54a-605a34bebe8b.png)

## Expected Result:
If you change the app to Spanish, they should be in Spanish.

## Workaround:
No workaround

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** v1.2.36-2
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1670350765187639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01375d7263acd1db70</li>
        <li>Upwork Job ID: 1605575140684824576</li>
        <li>Last Price Increase: 2022-12-21</li>
    </ul>
</details>

**Comment by pecanoro** [comment]
@kadiealexander No need to do anything here, I will take care internally!

**Comment by pecanoro** [comment]
A lot of progress made in the PR.

**Comment by pecanoro** [comment]
PR is finally ready for final review.

**Comment by pecanoro** [comment]
After dealing with this issue, we realized we probably need to handle these in two PRs since there are a lot of limitations when it comes to desktop menus in Electron:

Step 1: Translate the elements that are appended by us.
Step 2: Localize all default menu items that are appended by the OS.

**Comment by pecanoro** [comment]
@kadiealexander I am assigning you back since I will be assigning the C+ for review

**Comment by pecanoro** [comment]
Sorry @mollfpr, puller bear assigned @sobitneupane to the PR so I am going to switch assignees.

**Comment by pecanoro** [comment]
@MelvinBot Not overdue!

**Comment by pecanoro** [comment]
Removing the reviewing label since there is another PR left. @sobitneupane we should probably compensate you per each PR so don't forget to remind us when we are done with all of this since I am sure I will forget 😄

**Comment by JmillsExpensify** [comment]
Just my two cents, but I think this is more accurately a new feature, because we never implemented this originally. Obviously, let's close the loop and address it, but as a result, I'm swapping out the `bug` label for the new feature label.

**Comment by pecanoro** [comment]
Taking care of this later this week.

**Comment by pecanoro** [comment]
Hmm, now that we work with some agencies, I think this would be a great one to externalize as it's not huge priority and I don't feel super passionate (it requires a big-ish refactor).

**Comment by wojtus7** [comment]
Hi! 
I'm from Software Mansion and would like to take a look at this issue if it is still current 🤗

**Comment by pecanoro** [comment]
Of course, you can take a look since I have more urgent priorities rn, reassigning!

**Comment by roryabraham** [comment]
I'm happy to help review here as well 🙂

**Comment by roryabraham** [comment]
Since @wojtus7 has started working on this, let's make it a weekly

**Comment by pecanoro** [comment]
@wojtus7 Can you copy over the whole menu list in English? I can take care of translating them to Spanish 😄

**Comment by wojtus7** [comment]
@pecanoro This is the full list used right now:

***New Expensify***
About New Expensify 
Check for updates 
View keyboard shortcuts 
Services 
Hide New Expensify 
Hide Others 
Show All
 Quit New Expensify 
 
***File*** 
Close Window  

***Edit*** 
Undo 
Redo
 Cut
 Copy
 Paste 
Paste and Match Style 
Delete 
Select All 
Substitutions 
_ Show Substitutions 
_ Smart Quotes 
_ Smart Dashes 
_ Text Replacement 
Speech 
_ Start Speaking 
_ Stop Speaking 
Start Dictation… 
Emoji & Symbols  

***View*** 
Reload 
Force Reload 
Toggle Developer Tools
 Actual Size
 Zoom In
 Zoom Out 
Toggle Full Screen  

***History*** 
Back 
Forward

  ***Window***
 Minimize
  Zoom
 Tile Widow to Left of Screen
Tile Widow to Right of Screen
Replace Tiled Window
 Bring All to Front

  ***Help*** 
Learn More 
Documentation 
Community Discussions 
Search Issues

**Comment by iwiznia** [comment]
Most of that copy seems wrong, please follow our guidelines https://stackoverflowteams.com/c/expensify/questions/7025/7026#7026 especially WRT capitalization. (ie: it is not ` Tile Widow to Left of Screen`, it is ` Tile widow to left of screen`

**Comment by wojtus7** [comment]
@iwiznia oh, good to know! Thanks for the info ❤️
I was referring to the menus I found in the app and assumed those are correct ._.

https://github.com/Expensify/App/assets/42337257/eb9df2d0-4536-4a05-9d24-951e73e98608

**Comment by iwiznia** [comment]
Oh, maybe those were added before we codified the capitalization rules, let's update them?

**Comment by wojtus7** [comment]
Yup I think this is great opportunity to do it 🤗

**Comment by kadiealexander** [comment]
Just a note while we're tidying things up, are these supposed to be `Widow` or `Window`? 

> Tile Widow to Left of Screen
>Tile Widow to Right of Screen

`Widow` seems out of place but I don't know if it's just a term I haven't heard of.

**Comment by wojtus7** [comment]
Oh sorry - typo 🫠
Should be Window

**Comment by pecanoro** [comment]
I realized I never posted the translations:

```
New Expensify - Nuevo Expensify
About New Expensify - Sobre Nuevo Expensify
Check for updates - Buscar actualizaciones
View keyboard shortcuts - Ver atajos de teclado

Services - Servicios
Hide New Expensify - Ocultar Nuevo Expensify
Hide Others - Ocultar otros
Show All - Mostrar todos
Quit New Expensify - Salir de Nuevo Expensify
File - Archivo
Close Window - Cerrar ventana

Edit - Editar
Undo - Deshacer
Redo - Rehacer
Cut - Cortar
Copy - Copiar
Paste - Pegar
Paste and Match Style - Pegar adaptando el estilo
Delete - Eliminar
Select All - Seleccionar todo
Substitutions - Sustituciones
_ Show Substitutions - Mostrar sustituciones
_ Smart Quotes - Comillas inteligentes
_ Smart Dashes - Guiones inteligentes
_ Text Replacement - Sustitución de texto
Speech - Voz
_ Start Speaking - Empezar a hablar
_ Stop Speaking - Dejar de Hablar
Start Dictation… - Iniciar dictado...
Emoji & Symbols - Emojis y símbolos

View - Ver
Reload - Cargar de nuevo
Force Reload - Forzar recarga
Toggle Developer Tools - Ver herramientas de desarrollo
Actual Size - Tamaño real
Zoom In - Acercar
Zoom Out - Alejar
Toggle Full Screen - Alternar pantalla completa

History - Historial
Back - Atrás
Forward - Adelante

Window - Ventana
Minimize - Minimizar
Zoom - Zoom
Tile Window to Left of Screen - Ajustar ventana la izquierda de la pantalla
Tile Window to Right of Screen - Ajustar ventana a la derecha de la pantalla
Replace Tiled Window - Reemplazar ventana ajustada
Bring All to Front - Traer todo al frente

Help - Ayuda
Learn More - Más información
Documentation - Documentación
Community Discussions - Debates de la comunidad
Search Issues - Buscar problemas
```

**Comment by wojtus7** [comment]
Hi

I tried a lot of different things but always ended up with similar problems that some menu items are auto generated in JS code and use system language. 
For test purpose I changed my Mac language to polish only to realize different Electron app have exactly the same problems. For example those are screenshot from Visual Studio and as you can see some options are in English and some in Polish.

Only real solution I can see is modifying source code or try to make PR to Electron code to make those menu perfect.

<img width="459" alt="Zrzut ekranu 2023-06-12 o 17 08 05" src="https://github.com/Expensify/App/assets/42337257/d8124f95-1e25-48d3-ae38-69603b0d073e">
<img width="291" alt="Zrzut ekranu 2023-06-12 o 17 08 18" src="https://github.com/Expensify/App/assets/42337257/567be80b-6584-419d-8c29-25b53e953f7b">

**Comment by pecanoro** [comment]
@wojtus7 I think when I worked on this for our own items, I ended up discovering that it is possible to build the menu from a template and this was the only solution to our translation problems. Did you look into that option? https://www.electronjs.org/docs/latest/api/menu#menubuildfromtemplatetemplate

**Comment by wojtus7** [comment]
@pecanoro That's exactly the solution I came up with and created but the problem is that if you create the whole template with `Menu.buildFromTemplate` and then put the result template into the `Menu.setApplicationMenu` function it still automatically creates some menu options I haven't asked for. 

It seems that inside that function while creating native menu some thing are auto created based on content of your menu. Eg: If you put `Copy` option inside menu it automagically will add `Start Dictation` and `Emojis and Symbols` options, you have no control over it, but the worst part is that it will create them in your system language. (Below example of removing only "Copy" from template)

![image](https://github.com/Expensify/App/assets/42337257/6be61b2b-58ff-42bf-a302-68db3a0909e3)
![image](https://github.com/Expensify/App/assets/42337257/96e8a517-1aaa-4df8-a4b3-35b8d8b1fc06)

On the other hand when I was looking for solution I found that in [electron_menu_controller.mm](https://github.com/electron/electron/blob/395b608dd56d78155700cab3d4f75250e4d32eb4/shell/browser/ui/cocoa/electron_menu_controller.mm#L4) some titles are even hardcoded in english (like "Services" in line 345)

Also creating patches for this C code is impossible up to my knowledge, because we get this code bundled, and I don't think creating electron fork for problem like this is suitable solution.

So for now I have full templates with English/Spanish labels and creating menu based on it, but there are still some English/Mac language menu options generated I have no control over. :(

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: n/a
Contributor: n/a (internally handled)
Contributor+: $1000 @sobitneupane 

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/ab/applicants/1684092565631750144/hired).

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: n/a
Contributor: n/a (internally handled)
Contributor+: $2000 @sobitneupane

Eligible for 50% #urgency bonus? No

Payment is to be handled via NewDot.

**Comment by kadiealexander** [comment]
Not overdue, awaiting Newdot payment.

**Comment by sobitneupane** [comment]
Requested payment on newdot.

https://github.com/Expensify/App/issues/13414#issuecomment-1652813691

**Comment by JmillsExpensify** [comment]
Reviewed the payment details for @sobitneupane. $2k is approved for payment via NewDot.
