### ISSUE TITLE
[Hold for Payment 2023-01-17] Decline/cancel all outstanding IOUs on account close

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#13416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Request money from Account A to account B
2. Close account A

## Expected Result:

We handle it pretty badly today (see the actual result) which is an oversight. Following the discussion in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1670271674527989), we’re going to prevent it like such:

- When someone is attempting to close an account and they have an iouReport with an outstanding balance (i.e not $0), we’ll show an “Are you sure?” confirmation modal to highlight that
- If they proceed with the action of closing their account, any outstanding money requests will be rejected (“cancelled” or “declined”)

In doing so, we’ll resolve the problems we’re seeing in this issue, as there wouldn’t be a case whereby someone is seeing a “Pay” button on a request from a member with a closed account, because we rejected them when they took the action to close their account.

**Flow:**
1. Member has an iouReport with an outstanding balance (i.e not $0) to settle or be paid back
2. Navigates to Security > Close account
3. Enters email address > click “Close account”
4. An “Are you sure?” confirmation modal appears: “If you proceed with closing your account, any outstanding money requests will be canceled or declined.”
5. Click “Yes, continue”
6. The requests are cancelled/declined adding the reportAction messages to the DM as normal

**Mocks**:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2319350/207230333-e6959ded-3ae4-4f8f-b229-b231c0fb1e47.png">

#### Actual Result:
Unclear error displayed and user is unable to pay, and other downstream bugs like [here](https://github.com/Expensify/App/issues/13634) and [here](https://github.com/Expensify/App/issues/12850#issuecomment-1353816868)

#### Platform:
Where is this issue occurring?
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/151295657-ec6f240f-5545-4583-ab34-74d612a37f42.mp4

**Issue reported by:** @Tushu17 (Will be compensated as part of [this issue](https://github.com/Expensify/App/issues/7435))

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1670271674527989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@shawnborton this needs some dark mode finessing etc, but here's the basic idea of what I was thinking for this one: 

![image](https://user-images.githubusercontent.com/16232057/206545951-846a2c95-b0d7-49c2-a36a-326516067556.png)

**Comment by shawnborton** [comment]
Yeah, that looks good to me! Mind linking me to your file? I can help with dark mode stuff, though I wonder if these screens would be enough to guide implementation?

**Comment by trjExpensify** [comment]
I didn't create a dedicated file for it, it's [here](https://www.figma.com/file/zRGARZWHJxOnubplXR2GHm/Manual-Requests-Doc?node-id=696%3A5808&t=5Cimi9OksOnSTZBC-1) in `_Explorations` in manual requests. Can move it though if needs be.

**Comment by MitchExpensify** [comment]
Seeing as this is internal with Scott assigned, and I'll be OOO from tomorrow for a bit, I'm unassigning myself

**Comment by shawnborton** [comment]
Cool, I think we'd get something like this with the new colors:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2319350/207230333-e6959ded-3ae4-4f8f-b229-b231c0fb1e47.png">

**Comment by trjExpensify** [comment]
Perfecto, works for me - thanks! I'm going to take this off `planning`, it's ready for you @deetergp.

**Comment by shawnborton** [comment]
Not overdue

**Comment by deetergp** [comment]
The submit button on the Close Account page is the built-in submit button we get when we use the `Form` component. I'm not sure there is a way to get a confirmation modal with that element the way it is. I might have to create a new component — something like `FormWithConfirmation` — in order to implement this, but I am willing to bet it will get re-used at some point in the future.

**Comment by trjExpensify** [comment]
Hey @deetergp! I'm not sure if you've been following, but as a result of the work in these two PRs ([Auth](https://github.com/Expensify/Auth/pull/7228)/[Web](https://github.com/Expensify/Web-Expensify/pull/35453)) not working properly/being applied for the [case of a user being owed money](https://github.com/Expensify/App/issues/13634#issuecomment-1353900222) when they close their account, we run into the GetAuthTokenByEmail error on the chat like in the screenshot linked there and a few downstream bugs like: 

1. https://github.com/Expensify/App/issues/13634
2. https://github.com/Expensify/App/issues/12850

As in, you wouldn’t get an infinite loading spinner on sign-in if we canceled the outstandingIOUs when the other DM participant closed their account (like you don’t if the closed account owes you), and you wouldn’t have a stuck IOU badge icon for a broken chat. 

@cristipaval is going to work on fixing that logic in the issue he's assigned to, so we can immediately resolve the errors in that case of being owed money when you close your account. So for this issue, we're just focused on implementing the confirmation modal to surface to the user so they are aware that the action is going to happen if you close your account when there are outstanding IOU transactions.

**Comment by cristipaval** [comment]
[The PR](https://github.com/Expensify/Web-Expensify/pull/35903) with the fix for the logic is in review.

**Comment by deetergp** [comment]
Nice, thanks @cristipaval 👍

**Comment by Santhosh-Sellavel** [comment]
@deetergp or anyone else Assign me this one for tracking, thanks!

**Comment by Santhosh-Sellavel** [comment]
PR is merged and deployed to production yesterday!

**Comment by Santhosh-Sellavel** [comment]
This awaiting payment!

**Comment by trjExpensify** [comment]
@Santhosh-Sellavel sent you an offer for the internal PR review. Can you accept? Thanks!

**Comment by trjExpensify** [comment]
Settled up $1k!
