### ISSUE TITLE
[Regression test steps needed? Design] Fix font CSS so that we display the correct font weights

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13413]
We are not implementing the font CSS correctly. For example, take a look at how we are calling ExpensifyNeue-Regular but setting the font-weight to 700. What’s actually happening here is that the browser is adding a “fake bold” effect to the regular weight font, and the correct bold font files aren’t being used. But if we call the correct bold weight family that we are setting in our [CSS here](https://github.com/Expensify/App/blob/main/assets/css/fonts.css#L9), notice how much more crisp this is.

Wrong:
![image](https://user-images.githubusercontent.com/2319350/206304393-3bdcb97b-fbc8-416d-b685-e8bd38297c81.png)

Right: 
![image](https://user-images.githubusercontent.com/2319350/206304414-39b3fabf-0e9f-44b9-ab57-d7ee070eecb2.png)

Compare:
![image](https://user-images.githubusercontent.com/2319350/206304431-4b559111-a4b6-4efb-980f-2da94e756fcb.png)

**Solution:**
Let's make all of the CSS use the font family ExpensifyNeue-Regular but then we can use things like font-weight: 700 or font-style: italic to get the desired weights/styles we need. This will make sure we're always using the correct font files and thus we won't have the fake browser bolding happening. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013936adee3d2f99bd</li>
        <li>Upwork Job ID: 1608287987603697664</li>
        <li>Last Price Increase: 2022-12-29</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Not overdue, this was just merged!

**Comment by grgia** [comment]
I think we should be good to close as completed!

**Comment by mananjadhav** [comment]
@grgia this still needs to be open for the internal PR Review. Can you please assign someone  (I've also posted on the slack in case we don't want to reopen the issue)

**Comment by mallenexpensify** [comment]
PR - https://github.com/Expensify/App/pull/13415
@mananjadhav can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013936adee3d2f99bd

**Comment by mananjadhav** [comment]
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment]
Paid @mananjadhav 
hmm.... I think this is another we should leave open until we suss out if we want regression test steps for design issues. I'm going to assign myself, update the title and bump to weekly for now.

**Comment by mananjadhav** [comment]
@mallenexpensify I think we've got many issues where we're not updating regression steps. Can you or @shawnborton confirm so that we can close this one out faster?

**Comment by shawnborton** [comment]
Yeah, from my understanding I think we can just close this one out. This wasn't so much a regression but it was just not implemented correctly, so we followed up and fixed it.

**Comment by mallenexpensify** [comment]
We're definitely learning the regression test steps process on the fly.  Gonna close this
