### ISSUE TITLE
DEV: Desktop Development app Crashes

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Run the Desktop from the latest main
2. Use for some time, leave idle

## Expected Result:
The app should not have crashed

## Actual Result:
App crashed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1192" alt="Screenshot 2022-12-07 at 11 18 28 PM" src="https://user-images.githubusercontent.com/43996225/206312600-b93199e1-bdf4-42aa-9ac4-ccfc640cdbc9.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670435613556209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
I cannot test in Dev at this time so I'm going to ask an eng to help. Thanks!

**Comment by strepanier03** [comment]
@joelbettner - Hiya! Any chance you have the bandwidth to test this in Dev? I don't have the ability to do that.

**Comment by joelbettner** [comment]
I've tried this a few times and not had any crash.

**Comment by strepanier03** [comment]
I'm going to close this one out and if we need to reopen we can. 

----

**Head's up**

I am out of the office starting December 17th and will return on January 3rd. During this time, if this GH needs action from a BugZero team member, please post in #expensify-open-source with a link to the GH to ask for some help.

Cheers! ☃️
