### ISSUE TITLE
Can't properly format link with email - reported by @kerupuksambel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Open a chat and send this :  [*my email*]([example@mail.com](mailto:example@mail.com))

## Expected Result : 
The word my email should be bold because of the formatting

## Actual Result : 
The word my email isn't bold and instead the asterisks is still existed (*my email*)

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image](https://user-images.githubusercontent.com/43996225/206326227-6458ed10-54c6-4f19-8a82-0a5057563285.png)

https://user-images.githubusercontent.com/43996225/206326241-93c2f051-3c1f-4a27-b111-8aaceee7c7ed.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670444720498709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fbf3546d1e315c9</li>
        <li>Upwork Job ID: 1607401444323237888</li>
        <li>Last Price Increase: 2022-12-26</li>
    </ul>
</details>

**Comment by tienifr** [comment]
# Proposal

## Problem

When entering [*my email*](exmaple@gmail.com) we are going to run 2 regexes `email` and `bold` like the below code
In /App/node_modules/expensify-common/lib/ExpensiMark.js
```
 {
                name: 'email',
                regex: /\[([^[\]]*)\]\(([a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z]+?(\.[a-zA-Z]+)+)\)/gim,
                replacement: (match, g1, g2) => `<a href="mailto:${g2}">${g1.trim()}</a>`,
 },
```

```
 {
                // Use \B in this case because \b doesn't match * or ~.
                // \B will match everything that \b doesn't, so it works
                // for * and ~: https://www.rexegg.com/regex-boundaries.html#notb
                name: 'bold',
                regex: /(<pre>|<code>|<a>)*\B\*((?!\s).*?\S)\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
                replacement: (match, g1, g2) => (g1 ? match : `<strong>${g2}</strong>`),
 },
```

The `email` regex will be run before and the text will turn into `<a href="mailto:exam@gmail.com">*my email*</a>`. The `bold` regex with `regex: /(<pre>|<code>|<a>)*\B\*((?!\s).*?\S)\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,` will not execute when text is the `<a>`  tag

## Solution 1
I suggest that we should update the `bold` regex
In /App/node_modules/expensify-common/lib/ExpensiMark.js
```diff
                 // Use \B in this case because \b doesn't match * or ~.
                // \B will match everything that \b doesn't, so it works
                // for * and ~: https://www.rexegg.com/regex-boundaries.html#notb
                name: 'bold',           
                - regex: /(<pre>|<code>|<a>)*\B\*((?!\s).*?\S)\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
                + regex: /(<pre>|<code>)*\B\*((?!\s).*?\S)\*\B(?![^<]*(<\/pre>|<\/code>))/g,           
                replacement: (match, g1, g2) => (g1 ? match : `<strong>${g2}</strong>`),
```

From the before update in [this PR](https://github.com/Expensify/expensify-common/pull/463),  I see that adding <a> in regex is unnecessary

## Solution 2
We should execute the `bold` regex before executing the `email` regex by moving 4 regexes `email, link, autoEmail, autolink`  into the bottom of the rule list In /App/node_modules/expensify-common/lib/ExpensiMark.js
Then the `bold` regex will execute before executing the `email` regex

## Result
Both of the above solutions work correctly for me


https://user-images.githubusercontent.com/113963320/206361925-e55b22ae-8fb3-4c50-ab2a-542dce350881.mov

**Comment by Gonals** [comment]
Taking a look at this for #urgency, as it should be a quick fix

**Comment by Gonals** [comment]
I could reproduce this yesterday, but it seems to have been fixed already somewhere else:
<img width="1050" alt="Screenshot 2022-12-09 at 10 59 18 AM" src="https://user-images.githubusercontent.com/19366280/206676347-95bc24ee-cc5d-4b01-8fa2-9ef356bf68fc.png">

<img width="1064" alt="Screenshot 2022-12-09 at 10 59 27 AM" src="https://user-images.githubusercontent.com/19366280/206676364-103af5e1-83dd-4df8-a9e8-fb4c218998a3.png">

Closing for now

**Comment by Gonals** [comment]
This should be fixed already

**Comment by mountiny** [comment]
We need to handle a payment for @kerupuksambel as they have reported this bug

**Comment by mallenexpensify** [comment]
Sorry @eVoloshchak , needed to add the `Internal` label to create the Upwork job, unassigned ya. 
@kerupuksambel , can you accept the job then I'll pay? 
https://www.upwork.com/jobs/~016fbf3546d1e315c9

**Comment by kerupuksambel** [comment]
Thank you so much! Accepted the job offer.

**Comment by mallenexpensify** [comment]
Thanks @kerupuksambel , you're paid.  Thanks @mountiny for the ping.
