### ISSUE TITLE
Form doesn't show inline errors unless we click out or tab

### ISSUE THREAD

**Issue by ctkochan22** [Expensify/App#13424]
## Action Performed:
1. Start with a fresh session. Any account is fine, but log out then log back in.
2. Go to Settings -> Workspace --> Go into a workspace's settings (create one if you need to)
3. Go to "General Settings"
4. Go to workspace name's field. Add a bunch of spaces (which is invalid)
5. Verify that you do not see inline validation error
6. Click somewhere else, and verify that only then you see the error

## Expected Result:
On Step 4, as soon as you add an invalid worksapce name (like all spaces) you should see a validation error. 

## Actual Result:
There is no inline error **until** you click away and move the focus

## Area issue was found in:
Related to `form.js`
Likely related to https://github.com/Expensify/App/pull/11465

## Suggested resolution:
Fix it so that validation errors appear as soon as it fails vaildation

## Platform:
't tested all platforms but so far its happening
- Web
- Desktop App

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Notes/Photos/Videos:** 
Video https://recordit.co/neSGQULPTy
![neSGQULPTy](https://user-images.githubusercontent.com/12980144/206327202-57ae05bb-c0c6-4109-a54a-6de96ccf2762.gif)

Ties into this app issue: https://github.com/Expensify/App/issues/12268
cc @youssef-lr

**Comment by youssef-lr** [comment]
@ctkochan22 I think this is working as expected, we don't show errors until the `onBlur` event is triggered. cc @luacmartins @marcaaron. 
However, if you were to go back to the input and keep typing more spaces, the error will still be shown until the name is valid.

**Comment by luacmartins** [comment]
@youssef-lr is correct! This is working as expected!

**Comment by ctkochan22** [comment]
Okay sounds good!
