### ISSUE TITLE
 Inconsistent link parsing when the link is ended with question mark

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Open a chat and send this :  [google.com](http://google.com/)?
3. Open a chat and send this : ([google.com](http://google.com/)?)

## Expected Result : 
Either both of the question mark should be consistently included or omitted as a part of the hyperlink

## Actual Result : 
The question mark on the first autolink ([google.com](http://google.com/)?) would be omitted as a hyperlink, but the question mark on the second autolink (([google.com](http://google.com/)?)) would be included as a part of the hyperlink

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206491422-da35a3f6-79fe-46e8-94b5-28a76785ee3f.mp4
![Uploading qmark.gif…]()
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670399984468189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mateocole** [comment]
going to have engineering confirm if this is an issue or not, or if it should be resolved in a current issue

**Comment by PauloGasparSv** [comment]
Also not sure if this is an issue, but it happens on all platforms.
Going to ask on engineering-chat if people think we should work on this!

**Comment by PauloGasparSv** [comment]
Coming from the discussion we think this behavior won't be a problem so let's close this off : )
