### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Profile : Upload/Delete Photo popup not hiding 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Go to Settings -> Profile
2. Click Profile Photo
3. Select Upload Photo

## Expected Result:
Should hide options after selecting one of them

## Actual Result:
Not hiding even after selecting one of the options. Need to click outside the options to make it go away

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206460710-d63275e5-357b-4872-a9f6-5f39d4b3fa15.mov

https://user-images.githubusercontent.com/43996225/206460885-24b47a1b-3b13-4f9f-9efb-498b9112c09f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel  / Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670432916695299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a23347fca2f83eaf</li>
        <li>Upwork Job ID: 1600971997335502848</li>
    </ul>
</details>

**Comment by francoisl** [comment]
I can reproduce. @isabelastisser can you please apply the Engineering label to get it assigned. Doesn't work if I do it since I'm already on the engineering team. 

I'll start investigating in the meantime.

**Comment by francoisl** [comment]
Ok I just ran a git bisect, and it seems to come from [this PR](https://github.com/Expensify/App/pull/12031), which makes sense because it changed `PopoverMenu` quite a bit. cc @aimane-chnaif if you have any idea of the specific issue here.

**Comment by francoisl** [comment]
Ok so I managed to fix it by adding a `this.setState({isMenuVisible: false});` [here](https://github.com/Expensify/App/blob/3a3a9fd7954a8891e40e47a60be84e7db1aae224/src/components/AvatarWithImagePicker.js#L225) in each menu item's `onSelected`, but the fact that it broke here for this componenet makes me think it might also be broken in other places we use `PopoverMenu`, so I don't know if it's the best possible fix.

**Comment by marcaaron** [comment]
@0xmiroslav 👏 excellent! 

So the parent `onPress` event of a `Pressable` can be called when the child click happens. I guess even if it is programmatically triggered that event can bubble and should be stopped. On the hidden input this makes perfect sense to me as nothing needs to know about that except the input.

**Comment by marcaaron** [comment]
@thesahindia removing you here as we already have a workable solution

**Comment by allroundexperts** [comment]
@marcaaron The proposal was made before the `External` label was added. Aren't we not disallowing proposals before `External` label is added?

**Comment by marcaaron** [comment]
@allroundexperts I minimized your comment because it's not really germane to this issue. If you have any specific concerns about our process in general feel free to bring those up in Slack, thanks!

**Comment by s77rt** [comment]
@marcaaron https://github.com/Expensify/App/issues/13395

**Comment by marcaaron** [comment]
@s77rt take it to Slack please. It is not relevant to this issue.

**Comment by chiragsalian** [comment]
Not a deploy blocker since the fix was CP-d so I'm removing deployBlockerCash label. I also tested on staging and it looks like the issue is resolved.

**Comment by isabelastisser** [comment]
@0xmiroslav, I sent you an invitation for the job in Upwork, please apply and I will hire you and issue the payment ASAP. Thanks!

https://www.upwork.com/jobs/~01a23347fca2f83eaf

**Comment by isabelastisser** [comment]
@0xmiroslav was paid in Upwork.

The contract has ended.

**Comment by Santhosh-Sellavel** [comment]
@isabelastisser Reporting bonus not issued!

**Comment by isabelastisser** [comment]
@Santhosh-Sellavel sorry about that! I invited you to the job in Upwork now, please accept it and I will extend the contract and issue the payment. Thanks!

**Comment by Santhosh-Sellavel** [comment]
Applied @isabelastisser

**Comment by isabelastisser** [comment]
@Santhosh-Sellavel paid. All set!
