### ISSUE TITLE
iOS - Unable to install the TestFlight testing build

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Delete ND app installed in the device
2. Fresh install the app from the TF

## Expected Result:
App installed successfully

## Actual Result:
Error message appears "This app can not be installed because its integrity could not be verified"
NOTE : When updated the build from the TF ( `"New Expensify" Beta session expired` error message appears)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206479808-ac52e09a-f928-42a8-8fc1-e2e3890e06f3.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<img src="https://user-images.githubusercontent.com/43996225/206479818-5b2ac65d-1dfa-4ab1-8fea-11bed1c8aad2.jpg" width="40%" height="40%">
<img width="447" alt="IMG_3054" src="https://user-images.githubusercontent.com/43996225/206479855-171f0722-1e51-4dd4-aebe-804823b92f6c.PNG">

**Comment by adelekennedy** [comment]
@puneetlath this issue is with downloading TestFlight - I don't think this is something contributors would work on, am I wrong on that?

**Comment by mountiny** [comment]
Probably someone from @Expensify/mobile-deployers will have to look into this one. This needs to be internal yeah

**Comment by AndrewGable** [comment]
Agree internal, looks very similar to https://github.com/Expensify/App/issues/12828 which self resolved as we thought it was an Apple issue.

**Comment by adelekennedy** [comment]
Thanks all - I added the internal label, should this issue stay open or  should this be closed?

**Comment by johnmlee101** [comment]
Currently cannot open NewDot on mobile because the download doesn't complete in TestFlight, so subbing to this

**Comment by AndrewGable** [comment]
@adelekennedy - Let's keep it open

**Comment by mountiny** [comment]
This seems to be resolved per [this comment](https://expensify.slack.com/archives/C01GTK53T8Q/p1670532748074789?thread_ts=1670505849.547919&cid=C01GTK53T8Q)
