### ISSUE TITLE
Login - Different font is displayed by the end of email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13438]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Type long email address applausetester+0901abb@applause.expensifail.com

## Expected Result:
Font should be apply for full email address

## Actual Result:
Different font is displayed by the end of email field

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/93399543/206497118-bba18271-9560-4e7b-9348-cd5026bdeaaf.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Hm, I'm not seeing this on my end.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/33293730/206511321-779f38a5-f693-4956-9411-699907842cda.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/33293730/206511340-385ba2a4-3e8d-4a7c-9308-796d975ca840.png">

**Comment by tgolen** [comment]
I'm not able to reproduce this either. @kbecciv is this reproduced on Chrome for Mac or Windows? Both Lauren and I are testing on Mac and not seeting it. I'm going to close for now, but if we can reproduce it for sure, please reopen.
