### ISSUE TITLE
Notifications - Logos does not appear correctly in the notification

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #13330
## Action Performed:
Perform the following steps both in Desktop and Web: 
1. Go to Account A (Logged in web Chrome)
2. Send a message from B (Logged in Desktop app)
3. Observe the notification in account A (Chrome)
4. Send message from Account A to B
5. Observe the notification in account B (Desktop App)

## Expected Result:
Chrome icon AND the right circular Expensify icon is present. and Logo matches for the Desktop app

## Actual Result:
Incorrectly logo is appearing in both 

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="375" alt="Bug5855138_PR_screenshot" src="https://user-images.githubusercontent.com/43996225/206554015-46ebf831-56ab-43a9-8326-219effa1c96c.png">
![Bug5855138_Screen_Shot_2022-12-08_at_12 25 51_PM](https://user-images.githubusercontent.com/43996225/206554018-c5c8c2d6-bd6e-42f9-9e78-2f8c64522720.png)
![Bug5855134_13330_Web](https://user-images.githubusercontent.com/43996225/206554022-6f0dd808-5613-4901-b6bd-0545b0254c40.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
Your screenshots look correct, the Chrome notifications should have the circular icon, and the desktop notification should have only the square icon (only one icon per notification). Closing this out
