### ISSUE TITLE
Web -Log in - Console error shows when log in with HT account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with applausetester+0901abb@applause.expensifail.com/Feya86Katya

## Expected Result:
No console errors should be displayed

## Actual Result:
Console error shows when log in with HT account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="960" alt="console" src="https://user-images.githubusercontent.com/93399543/206502229-4cebe39d-84d8-4f9d-b276-3f848cce17d0.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment]
logging into staging with my expensifail.com account didn't reproduce that console error. testing with the mentioned error

**Comment by bondydaa** [comment]
hmm i don't see that same console error.

I see one about `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).` 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4073354/206557668-40213f5f-981b-4cd9-b86c-15a611da3b5f.png">


I am using Firefox so let me try chrome.

**Comment by bondydaa** [comment]
hmm interesting if I try to load the same report you have open in your screenshot it now gives me a 404 error and says I don't have access 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4073354/206561494-85f471ef-9d47-43ba-87f3-4cf94c178acb.png">

**Comment by bondydaa** [comment]
@kbecciv are you able to reproduce the console error still? is it related to a specific chat/reportID?

**Comment by bondydaa** [comment]
closing this out for now, if you are able to reproduce please let me know more steps
