### ISSUE TITLE
Log in - Error message “Too many attempts doesn't appeared and info is blinking when tap on resend link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. In the login screen, enter an email that doesn't have an Expensify account yet
3. In the "Resent link" page - Disable the internet connection in the device
4. Go back online and click/tap on the "Resend Link" button
5. Verify you see “Link has been resent” with a green dot on the left
6. Verify you received 2 magic link emails in your email inbox - Do not validate the account yet
7. Back in NewDot, click “Resend Link” a bunch of times
8. Verify you see an error message “Too many attempts, please wait a few minutes and try again” with a red dot on the left

## Expected Result:
An error message “Too many attempts, please wait a few minutes and try again” displays with a red dot on the left

## Actual Result:
Error message “Too many attempts doesn't appeared and info is blinking when tap on resend link

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206574494-168c4c2f-5201-40c3-a8fe-81cdeb499aab.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is Fail steps in TR https://expensify.testrail.io/index.php?/tests/view/2990810

![image](https://user-images.githubusercontent.com/93399543/206574929-9ef41723-f8be-482c-bd21-0e7ae8dfd905.png)

**Comment by Christinadobrzyn** [comment]
I'm not able to reproduce this. Steps I'm taking

1. Go to https://staging.new.expensify.com/ in desktop
2. In the login screen, enter an email that doesn't have an Expensify account yet
3. Click Resend link page 
4. Get a "You've reached the maximum login attempts, which is 3. Please wait a few minutes and try again."
5. This message appears when online or offline - not glitching

![image](https://user-images.githubusercontent.com/51066321/206632399-c8d51516-6bc9-4862-a89d-feeb317e1111.png)

iOS: v1.2.36-4

1. Go to https://staging.new.expensify.com/ in desktop
2. In the login screen, enter an email that doesn't have an Expensify account yet
3. Click Resend link page 
4. Get a "You've reached the maximum login attempts, which is 3. Please wait a few minutes and try again."
5. This message appears when online or offline - not glitching

**Comment by Christinadobrzyn** [comment]
@kbecciv Can you please clarify the steps so I can try and replicate them?

**Comment by kbecciv** [comment]
@Christinadobrzyn This issue reproduced only in IOS and Android app, which environment did you try?

**Comment by kbecciv** [comment]
Steps are listed correct, also you can try using steps following the TR steps as well https://github.com/Expensify/App/issues/13447#issuecomment-1343419057

**Comment by Christinadobrzyn** [comment]
I can replicate following the TR steps. I don't see the 'too many attempts' message is blinking and the red dot seems to indicate an issue (there's a green dot when something is successful). Can you clarify the issue?

 
![2022-12-15_16-10-57 (1)](https://user-images.githubusercontent.com/51066321/207808385-9b1a790e-b96b-4522-8779-9fa00c089225.gif)
