### ISSUE TITLE
New marker line does not show when directly navigating to unread chat in new tab

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#13445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. As User A send a message to User B (User B should have no windows to chats open)
2. As User B navigate directly to the chat with User A in a new tab

## Expected Result:

Chat should be marked as read in the LHN ✅ 
New line indicator should appear over the correct message ❌ 

## Actual Result:

New line indicator is not present at all

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/32969087/206555261-48f215fe-9bd1-49ef-afaa-69f8f27951e2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
Yeah I can definitely reproduce it and was commenting on this issue to someone in a 1:1. (I know I should have filed an issue). @marcaaron Should this go off to an external contributor?

**Comment by marcaaron** [comment]
There's a good chance it's related to the backend and also could possibly be resolved by the **Deprecate `sequenceNumber`** project so I am inclined to keep it `Internal` for now (sorry meant to add that label before)
