### ISSUE TITLE
Workspace / Group chat - Black background appears when there are multiple avatars

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #13351 

## Action Performed:
1. Create multiple workspaces
2. Navigate to /settings
3. Verify that the avatar does not have a black border around it
4. Create a group chat and observe the chat avatars

## Expected Result:
The border matches the background of the containing element

## Actual Result:
Shows black background

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5855145_Untitled](https://user-images.githubusercontent.com/43996225/206555229-9167c055-6308-42b4-96fa-3538f59124be.png)
![Bug5855145_Untitled1](https://user-images.githubusercontent.com/43996225/206555255-293cda23-4018-4a5a-9d25-05af467758c4.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
Hmm..I am not sure this needs to be worked on, I believe there is an internal conversation about revamping the color of dark mode as a whole, which would likely impact the background with multiple avatars. @shawnborton Do you agree or is this a bug?

**Comment by shawnborton** [comment]
We can close this, @grgia is already working on it as part of this one: https://github.com/Expensify/App/issues/13208
