### ISSUE TITLE
react-pdf Document is caching PDFs failure to load

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#13453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from here: https://github.com/Expensify/App/pull/13409#pullrequestreview-1210923388

## Action Performed:
1. Upload a pdf
4. Open the pdf and verify that it loads fine
5. Close the modal
2. Go offline
4. Open the pdf and verify that you see error message
5. Close the modal
6. Go back online
7. Open the pdf

## Expected Result:
The PDF should open successfully now that you are online

## Actual Result:

We keep getting the error after coming back online

https://user-images.githubusercontent.com/87341702/206594057-936d0665-84c1-4f66-85e4-974ce7aeaef3.mov

## Workaround:
Refresh the page?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
I think a next step is create a GH issue in the react-pdf repo: https://github.com/wojtekmaj/react-pdf/issues proving a reproducible example.

There is an [existing issue](https://github.com/wojtekmaj/react-pdf/issues/341) about disabling cache, but it was opened for other reasons and then closed without activity.

**Comment by aldo-expensify** [comment]
When we close and reopen the attachment, I confirmed that the component [PDFView](https://github.com/Expensify/App/blob/3a3a9fd7954a8891e40e47a60be84e7db1aae224/src/components/PDFView/index.js#L13) is getting destroyed/reconstructed.

**Comment by aldo-expensify** [comment]
@muttmuure This issue was mentioned by @rushatgabhane [here](https://github.com/Expensify/App/pull/13409#pullrequestreview-1210923388) when he was reviewing a PR. Just mentioning in case it makes him qualify for reporting compensation.

**Comment by muttmuure** [comment]
Not had chance to get to this yet

**Comment by muttmuure** [comment]
Testing now

**Comment by muttmuure** [comment]
Hey @aldo-expensify I can't reproduce this - I can still load the PDF I uploaded even after I go offline, do you mind checking that the bug still happens for you?

**Comment by aldo-expensify** [comment]
I managed to reproduce, but I noticed that I can only do it using the Chrome dev tools to go offline/online and with `Disable cache` checked. I tried to reproduce without chrome dev tools by disconnecting the wifi and it works fine in that case (which is the normal use case).

I'm going to close it, thanks for trying!
