### ISSUE TITLE
Web - Chat - File drop is not detected if payment details are open in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12056

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Open any chat with IOU
3. Open IOU details
4. Drag and drop file to chat

## Expected Result:
File drop should be detected

## Actual Result:
File drop is not detected if payment details are open in chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206595900-f1ae405f-f33f-4c90-a3c7-efaaf89528fc.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I'm not sure if this is actually a bug, I can't think of a use case for dropping a file into the right-hand panel payment details here.
Going to tag @roryabraham for your opinion since you opened https://github.com/Expensify/App/issues/11823.

**Comment by roryabraham** [comment]
I don't think that this is a bug. Agree with @parasharrajat that when the RHP is open then interactions in the chat view should be disabled.

> I can't think of a use case for dropping a file into the right-hand panel payment details here

Even if we had a separate use-case for dropping a file into the RHP, that would be:

- A new feature
- Another instance of the `DragNDrop` component

Closing this out
