### ISSUE TITLE
[$1000] Android Chrome autofills with login/password on the “Add phone number” screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in
2. Navigate to Settings -> Profile -> Add phone number
3. Tap phone number field

## Expected Result: 
Phone number recommended

## Actual Result: 
Username/password combinations are recommended

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Android chrome)

**Version Number:** 1.2.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/206596359-9f2cee60-5e75-4ca2-b0fb-280624f92615.png" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/206596401-49313fdf-b2af-42f2-a16c-64baff56ddb2.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669693545964079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ced3a25cc203e65</li>
        <li>Upwork Job ID: 1603043549558640640</li>
        <li>Last Price Increase: 2022-12-14</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
reviewing today

**Comment by fedirjh** [comment]
@dylanexpensify per this https://github.com/Expensify/App/issues/8455#issuecomment-1307983899 , I think we should hold / close this issue until refactoring

> Additionally, we should be vigilant to not to open/work on any more bugs relating to this page until we are fully passwordless!

**Comment by mountiny** [comment]
@fedirjh thank you very much for linking that comment

I agree, I will close this issue, also this is super small problem so it definitely does not need to be fixed right now and can wait for the refactor. Then we will see how we can improve these/ if there still will be a need for this.
