### ISSUE TITLE
 iOS - Chat - HEIC images are converted to JPG when sending to chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when execute PR** https://github.com/Expensify/App/pull/13246

## Action Performed:
1 . Go to Settings > Camera > Format > ensure that "high-efficiency" is enabled
2. Open the iOS app and login
3. Go to chat
4. Take a picture with the native iOS camera, ensuring that "live" photo is disabled
5. Tap the grey plus icon to the right of the chat input
6. Select a image from your camera roll (for iOS should be HEIC files by default)
7. Upload the image
8. Verify that the image is uploaded successfully

## Expected Result:
Uploaded image should be HEIC format

## Actual Result:
Uploaded image is converted to JPG

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206594124-2873f628-ea4a-4577-9aed-3a72493e9646.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment]
HEIC images are converted to JPG because the server does not support HEIC files as far as I know
Also HEIC images are not widely supported as JPG

**Comment by sketchydroide** [comment]
Yeah, this seems like a feature, not bug, Otherwise other platforms would not be able to see the picture

**Comment by sketchydroide** [comment]
closing
