### ISSUE TITLE
[HOLD for payment 2022-12-22] [$1000] LHN - Offline created Split Bill Group is not displayed among top chats in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Go offline
3. Create a Split Bill among several accounts

## Expected Result:
Direct messages and Group chat should be displayed among top message in LHN as most recently sent.

## Actual Result:
Group chat is displayed somewhere in the bottom, hard to find, until I go online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206597088-d588644a-1d48-456b-a824-ced951241f47.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120b810b78d008e76</li>
        <li>Upwork Job ID: 1601302501012258816</li>
    </ul>
</details>

**Comment by tienifr** [comment]
# Proposal

## Problem

In https://github.com/tienifr/App/blob/216bbe9ff3995264e08a542d618bcc1db12d946f/src/libs/SidebarUtils.js#L155 we are sorting the reports base on `lastActionCreated` value.
But when we build the optimistic chat report we just let `lastActionCreated` is empty
https://github.com/tienifr/App/blob/216bbe9ff3995264e08a542d618bcc1db12d946f/src/libs/ReportUtils.js#L897

=> the new group is displayed at the end

## Solution

In https://github.com/tienifr/App/blob/216bbe9ff3995264e08a542d618bcc1db12d946f/src/libs/ReportUtils.js#L897

change `lastActionCreated: '',` to `lastActionCreated: DateUtils.getDBTime(),`


https://user-images.githubusercontent.com/113963320/206619716-6baa208a-40a8-4689-a6c0-661ef44ed9ce.mp4

**Comment by priyeshshah11** [comment]
@thesahindia shouldn't the proposals be only submitted after the External label is applied as per the guidelines? The selected proposal was submitted before the External label was applied. I am getting conflicting answers in regards to the proposal rules from the team.

If that's the case then here it is

## Proposal 2: 

https://github.com/tienifr/App/blob/216bbe9ff3995264e08a542d618bcc1db12d946f/src/libs/ReportUtils.js#L897
```diff
- lastActionCreated: '',
+ lastActionCreated: DateUtils.getDBTime(),
```

**Comment by Julesssss** [comment]
Hey @priyeshshah11, we're aware this isn't very clear and are deciding. internally how to apply the rule moving forward.

**Comment by tienifr** [comment]
Thanks, I've applied to the job, the PR will be ready by tomorrow

**Comment by tienifr** [comment]
Hi @thesahindia [The PR](https://github.com/Expensify/App/pull/13552) is ready, please help to review it. Thanks

**Comment by Julesssss** [comment]
This wasn't a regression.

**Comment by kevinksullivan** [comment]
Paid @thesahindia and @tienifr . Thanks everyone!

**Comment by thesahindia** [comment]
@kevinksullivan, it's also eligible for 50% bonus

**Comment by kevinksullivan** [comment]
Sorry for missing that @thesahindia. All set.
