### ISSUE TITLE
Account - Message 'Account closed successfully" doesn't appear

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login
2. Navigate to security > Close account
3. Enter your default contact method
4. Tap on "Close account" button

## Expected Result:
Account should be close and green dot with the message 'Account closed successfully" appeared.

## Actual Result:
Account was closed and only green dot without the message 'Account closed successfully" appeared.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/206614983-6d25475d-7db7-40a5-af4c-31d7f11c5035.png" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/206614984-9932d9cc-04dc-4e87-b04c-73197aedfd71.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Grabbing this!

**Comment by Gonals** [comment]
Not seeing this in web:
<img width="352" alt="Screenshot 2022-12-09 at 4 37 19 PM" src="https://user-images.githubusercontent.com/19366280/206738097-05c07119-e73e-425c-9af8-0e91096ecfc5.png">

**Comment by Gonals** [comment]
Could reproduce it in iOS:
<img width="395" alt="Screenshot 2022-12-09 at 5 00 05 PM" src="https://user-images.githubusercontent.com/19366280/206742398-19665af2-0144-4886-b76b-a0c410ac6fa8.png">

**Comment by chiragsalian** [comment]
Not a deploy blocker since the PR was CP'd to staging. I briefly tested on staging ios and it looks like the issue is resolved for me. removing deploy blocker label.

**Comment by Gonals** [comment]
This was solved internally, so no payments needed
