### ISSUE TITLE
 Chat Should Return Back To LHN With On Screen Gestures

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open A Chat
2. Use On Screen Gesture To Go Back From Chat

## Expected Result: 
Return To LHN

## Actual Result: 
It Quits The App

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.36-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206596919-fa67bb1b-c9c0-4067-a788-92ff5ddaaa41.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670354256663239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Kavi, looks like you're navigating out of the app but aren't closing it completely, correct? 

Test 1
1. Open NewDot on mobile
2. Tap into a conversation 
3. Tap phone's home button to return to desktop
4. Open NewDot again - the app opens to the chat I tapped into

Test 2
1. Open NewDot on mobile
2. Tap into a conversation 
3. Close (clear it out of open apps list) the app
4. Open NewDot again - the app opens to the Chats page

These behaviors don't look buggy to me. This is exactly how other apps work: Whatsapp, Facebook messenger, Slack.

Please reopen if you disagree and you think we should be resetting the view when you navigate out of the app as well as when you close the app.
