### ISSUE TITLE
Dev - mWeb - App crashes on sign in 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND 
2. Sign in 

## Expected Result:
User successfully signed in

## Actual Result:
App crashes

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** Needs reproduction
**Reproducible in staging?:** Occurring in Dev
**Reproducible in production?:** Occurring in Dev 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
[safari_crash.txt](https://github.com/Expensify/App/files/10196422/safari_crash.txt)
[Untitled.txt](https://github.com/Expensify/App/files/10196423/Untitled.txt)

**Notes/Photos/Videos:** 
<img width="428" alt="Screenshot 2022-12-09 at 10 59 01 AM" src="https://user-images.githubusercontent.com/43996225/206746769-87299dd9-a25f-4889-89b4-03917d576a10.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1670528976295469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
Just hopping in to note that this same crash happens to me on desktop web as well - `null is not an object (evaluating 'this.dropZone.getBoundingClientRect')` showing up in the console there, with some pointing to the `DragAndDrop` component

**Comment by francoisl** [comment]
Fixed with [this revert](https://github.com/Expensify/App/pull/13482) - no need to wait on a deploy since the offending PR wasn't deployed to staging yet.
