### ISSUE TITLE
Transition from Report Detail to chat isn't smooth when swiping from left to right

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Click on chat.
2. Click on user avatar to open detail page.
3. Swipe from left to right to go back previous screen.
4. Notice that transition isn't smooth like other screen.

## Expected Result:
The transition should be smooth without any delay

## Actual Result:
 The transition isn't smooth like other screen.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206767999-44e46ef5-46ef-497f-94e2-7e72f6babdd6.MP4

https://user-images.githubusercontent.com/43996225/206768034-de2f52ab-f5fe-4247-87c8-54a57a65867d.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670513955400559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
I was able to replicate and notice that the swipe was not a smooth transition. It started smooth then lagged a bit

**Comment by abekkala** [comment]
But looks to be a duplicate https://github.com/Expensify/App/issues/7737

**Comment by hungvu193** [comment]
It's not duplicate since it's problem with react navigation native or app performance , not web
