### ISSUE TITLE
[HOLD for payment 2022-12-27] Keyboard type wrong on close account page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Action Performed

1.  Go to settings > security > close account
2.   click on default contact method

## Expected Result:
should show email keyboard as it accept email or phone(we are using email keyboard on login page)

## Actual Result:
shows default keyboard

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/206811079-60c29757-7d73-4595-bcea-e8ec9c7f10d1.jpg" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/206811098-b59b7a53-31ff-4517-a5e4-5e8ad955b82f.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670575030039319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
**Proposal**

pass `keyboardType={CONST.KEYBOARD_TYPE.EMAIL_ADDRESS}` and `import CONST from '../../../CONST';`


https://github.com/Expensify/App/blob/168800a386e171882dd2e0a3d9ae57954df6fa5f/src/pages/settings/Security/CloseAccountPage.js#L102-L107

**Comment by sophiepintoraetz** [comment]
@gadhiyamanan - I think you need to wait until it's gone through the review process before we solicit proposals. Please wait until the appropriate time.

**Comment by sophiepintoraetz** [comment]
Hmm, I'm on v1.2.38-1 - to be clear, are we looking for something like this to pop up?
![image](https://user-images.githubusercontent.com/42940078/207182929-afe5467e-db19-47e7-bd04-86e59f626c30.png)

https://user-images.githubusercontent.com/42940078/207182604-900f97ae-0691-4f1e-a9bf-80c77ccc8de3.MP4

**Comment by gadhiyamanan** [comment]
>I think you need to wait until it's gone through the review process before we solicit proposals. Please wait until the appropriate time.

@sophiepintoraetz  According to [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#proposing-a-job-that-expensify-hasnt-posted) ,reporter may suggest a solution for the job.

![Screenshot 2022-12-13 at 9 09 15 AM](https://user-images.githubusercontent.com/54790231/207220807-9c913bee-b164-4edc-8c43-f0376f68b7d2.png)

**Comment by sketchydroide** [comment]
@sophiepintoraetz no that is the autocomplete, the email keyboard has an `@`, which you can see in the same image next to the space.
So in your video this would be a replication of the issue.
I still think this is a Bug, not a huge one, but the correct keyboard for the correct field was alway something that told me the quality of the App. So I'm quite keen on fixing these

**Comment by sketchydroide** [comment]
Sorry @gadhiyamanan there has been a shift with internal engineers picking this kind of issues to help things go faster, and so not posting a fix is mostly for your own benefit of not wasting time/energy on a solution that you will not be payed for.

You will still be payed for finding the bug though.

I think that you brought a good point that we need to discuss internally as well, of when a contributor finds a Bug if it's ok to propose a fix. I would say that the answer at this point is that probably best not to.

In this case it might seem obvious, but we might thingking of changing the way we close accounts, or something else that affects the bug. So it's mostly a risk to you...

**Comment by sketchydroide** [comment]
PR is being reviewed

**Comment by sketchydroide** [comment]
changed the C+ to you @aimane-chnaif

**Comment by sophiepintoraetz** [comment]
Okay so the amount to be paid are (@sketchydroide, appreciate a double-check):
@gadhiyamanan - $250 for reporting thebug
@aimane-chnaif $1000 + $500 bonus for PR being merged within 3 days?

**Comment by sophiepintoraetz** [comment]
Job offers sent!
