### ISSUE TITLE
[HOLD for payment 2022-12-22][$1000] Workspace - general settings -  `Save` Button is not at the bottom

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to settings > Workspaces
3. Open a workspace
4. Go to workspace settings

## Expected Result: 
The button should be at the bottom

## Actual Result : 
The button is not at the bottom

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/206810312-344deeb6-39fb-4ac4-b3f7-54e118eb88bb.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/206810329-40704a44-8b5e-4692-8ec1-bc4f6cc59f75.PNG" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @daraksha-dk 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670351071306529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a8b2e372f1048cf</li>
        <li>Upwork Job ID: 1602417572384657408
<li>Last Price Increase: 2022-12-12</li></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
**Proposal**

Wrap `FormAlertWithSubmitButton` with the `View` and assign flex properties to it so it will take the available full height.

https://github.com/Expensify/App/blob/3fa96a92c2b50b3501af6b75584121d0fa1a076c/src/components/Form.js#L281-L282

```
{this.props.isSubmitButtonVisible && (
<View style={[styles.flex1, styles.justifyContentEnd]}>
    <FormAlertWithSubmitButton
```

<img width="382" alt="Screenshot 2022-12-10 at 5 51 05 AM" src="https://user-images.githubusercontent.com/14358475/206817984-04e728ca-11e1-4a0c-ac63-04d9699bed8e.png">

**Comment by Pujan92** [comment]
> Wrap `FormAlertWithSubmitButton` with the `View` and assign flex properties to it so it will take the available full height.

To point out as this is a common component and used in multiple places it will apply to each place. I am seeing this change seems required on other pages too but in case we only want it for this page(Workspace Settings) then we can pass styles via property from there and apply to `View`. 

**Current Pages**

<img width="381" alt="Screenshot 2022-12-10 at 6 06 09 AM" src="https://user-images.githubusercontent.com/14358475/206819405-279333ff-96c6-4483-a863-9ae1d52f7283.png">
<img width="377" alt="Screenshot 2022-12-10 at 6 07 26 AM" src="https://user-images.githubusercontent.com/14358475/206819409-43367ddd-6ea4-4fa3-8ba6-2d645fc05ef8.png">
<img width="375" alt="Screenshot 2022-12-10 at 6 08 51 AM" src="https://user-images.githubusercontent.com/14358475/206819411-b154f9f8-7e57-4872-ad87-de7f3fd500ba.png">
<img width="380" alt="Screenshot 2022-12-10 at 6 09 40 AM" src="https://user-images.githubusercontent.com/14358475/206819414-385b512b-2a08-42a3-8617-40e8cf287b36.png">


**After Change**

<img width="376" alt="Screenshot 2022-12-10 at 6 12 31 AM" src="https://user-images.githubusercontent.com/14358475/206819626-10857509-0437-4914-ab7c-793fab86d959.png">
<img width="377" alt="Screenshot 2022-12-10 at 6 12 53 AM" src="https://user-images.githubusercontent.com/14358475/206819629-27c81c59-0641-4878-a708-afc1f9114b62.png">
<img width="377" alt="Screenshot 2022-12-10 at 6 13 21 AM" src="https://user-images.githubusercontent.com/14358475/206819631-122ee104-c621-4740-94e2-1bcebb853213.png">
<img width="377" alt="Screenshot 2022-12-10 at 6 13 36 AM" src="https://user-images.githubusercontent.com/14358475/206819632-724062f1-a09d-4fa4-bbbb-fb09c3038de9.png">

**Comment by daraksha-dk** [comment]
### Proposal

We just have to pass `styles.flex1` 
https://github.com/Expensify/App/blob/ed3e2dc507e0f02a30b22a012412fbecc0be2290/src/components/FormAlertWithSubmitButton.js#L56

**Comment by tgolen** [comment]
OK, please make sure that you test the sign-in flows to ensure buttons are all placed properly. If I recall, the reason I removed that was because it was causing a spacing issue on the "resend validation link" form.

**Comment by daraksha-dk** [comment]
@tgolen, yeah I looked at the PR and re-adding `flex1` below was causing spacing issues https://github.com/Expensify/App/blob/ed3e2dc507e0f02a30b22a012412fbecc0be2290/src/components/FormAlertWithSubmitButton.js#L56

that's why I found another solution, which is to pass the flex1 to `FormAlertWithSubmitButton` in `Form` so that it doesn't affect other places. We just have to pass `flex1` below
https://github.com/Expensify/App/blob/ed3e2dc507e0f02a30b22a012412fbecc0be2290/src/components/Form.js#L297

**Comment by chiragsalian** [comment]
Proposal LGTM

**Comment by davidcardoza** [comment]
Should this issue have the external label applied?

**Comment by davidcardoza** [comment]
Applying the external label for review.

**Comment by davidcardoza** [comment]
Job posted - https://www.upwork.com/jobs/~01fa021a1ff96c59c0

**Comment by lordthien** [comment]
Proposal: 
In file: `App/src/components/Form.js`. I add `styles.flex1` into `containerStyles` of `FormAlertWithSubmitButton`
```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 72ee4afc6b..3c41357161 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -294,7 +294,7 @@ class Form extends React.Component {
                                     focusInput.focus();
                                 }
                             }}
-                            containerStyles={[styles.mh0, styles.mt5]}
+                            containerStyles={[styles.mh0, styles.mt5, styles.flex1]}
                             enabledWhenOffline={this.props.enabledWhenOffline}
                             isDangerousAction={this.props.isDangerousAction}
                         />
```
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-12-13 at 10 50](https://user-images.githubusercontent.com/71846803/207222428-cd70e6dc-7c30-4079-ab7b-b081b6e98cd1.png)

**Comment by mananjadhav** [comment]
I just went through the proposals to review and was going to accept @daraksha-dk's proposal but then I saw the PR is already merged.

@chiragsalian do you need a second testing from my side here?

**Comment by chiragsalian** [comment]
Nope, we're good here. We moved a bit fast since deploy blockers are considered hourly. QA is testing this atm.

**Comment by chiragsalian** [comment]
QA tested this and its a pass, removing deploy blocker label

**Comment by daraksha-dk** [comment]
@davidcardoza, I have applied to the job.
Just a note - The job price is $1000 but it's eligible for $1750 (Reporting Bonus + Fix + 50% bonus )

**Comment by davidcardoza** [comment]
Sounds good, I paid out $1750

**Comment by daraksha-dk** [comment]
@davidcardoza, I haven't received the offer. Can you check please?

**Comment by davidcardoza** [comment]
@daraksha-dk I sent the invite again. Did you receive it?

**Comment by mallenexpensify** [comment]
@daraksha-dk , I just hired you, please accept https://www.upwork.com/jobs/~014a8b2e372f1048cf
The bonus will be added, $1750 will be the total.  
I've assigned to issue payment too, I think David might (or should) out of office :)

**Comment by daraksha-dk** [comment]
Thanks @mallenexpensify - I have accepted the offer on Upwork

**Comment by mallenexpensify** [comment]
Paid @daraksha-dk $1750. 
@chiragsalian can you fill out the BZ checklist above plz, Doza already did the TestRail update
https://github.com/Expensify/App/issues/13488#issuecomment-1353792630

**Comment by mallenexpensify** [comment]
oh... sweet.  Sorry I missed that @chiragsalian , closing meow
