### ISSUE TITLE
Network failure showing error notification without message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open setting => Preferences and enable Simulate failing network requests.
2. Open any chat press plus button and then send money.
3. Enter amount, press next and then I’ll settle up elsewhere.
4. Wait for few seconds.

## Expected Result:
It should show some error message or should send money in chat offline and sync when connected.

## Actual Result:
Showing blank error notification.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206816454-5f2f0f80-4ef1-4394-9a6b-c3ae7b0aa34c.mp4

https://user-images.githubusercontent.com/43996225/206816500-d06b6ea3-59f2-498d-81e8-12e14ed8c8b7.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jatinsoni
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670599543934609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
👀

**Comment by CortneyOfstad** [comment]
Not overdue.

**Comment by CortneyOfstad** [comment]
I'm heading OoO for the next two weeks, so going to be unassigning myself, @robertjchen 👍

**Comment by robertjchen** [comment]
Thanks, looking into this!

**Comment by JmillsExpensify** [comment]
I don't think this is a bug anymore, can't reproduce. I'd almost guarantee it was a temporary issue that occurred right when we were refactoring IOUs. Can someone on this issue confirm?

**Comment by AndrewGable** [comment]
I was unable to reproduce the dialog issue.
