### ISSUE TITLE
Log in - "Account closed successfully" message does not disappear until put your log in and click continue.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login
2. Navigate to security > Close account
3. Enter your default contact method
4. Tap on "Close account" button
5.Confirm the "Account closed successfully" message displays correctly
6. Start typing new email address under log in page

## Expected Result:
"Account closed successfully" message should be disappear after start typing new email address

## Actual Result:
"Account closed successfully" message does not disappear until put your log in and tap continue.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206872646-523fe3f6-84d5-436e-be0b-be5cc75a29d9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by markarmanus** [comment]
Proposal:


Issue:

We set the onyx data for ```ONEXKEYS.FORMS.CLOSE_ACCOUNT_FORM``` to be true when the request succeds and we never reset its value.


Solution:
The same way we are reseting account errors when the user starts typing with this code.

```JS
        if (this.props.account.errors) {
            Session.clearAccountMessages();
        }
```

We do the same thing with the account close data.

We create this function which resets the data
```JS
function resetAccountCloseData() {
    Onyx.merge(ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM, CONST.DEFAULT_CLOSE_ACCOUNT_DATA);
}
```


Then we use that function on user input to the email field. 

```JS
if (this.props.closeAccount.success) {
    Session.resetAccountCloseData();
}
```

Here is the full diff 


```diff
diff --git a/src/libs/actions/Session/index.js b/src/libs/actions/Session/index.js
index 13f1eadc5..4dd01d52f 100644
--- a/src/libs/actions/Session/index.js
+++ b/src/libs/actions/Session/index.js
@@ -388,6 +388,9 @@ function clearAccountMessages() {
         isLoading: false,
     });
 }
+function resetAccountCloseData() {
+    Onyx.merge(ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM, CONST.DEFAULT_CLOSE_ACCOUNT_DATA);
+}
 
 /**
  * Calls change password and signs if successful. Otherwise, we request a new magic link
@@ -578,6 +581,7 @@ export {
     clearSignInData,
     cleanupSession,
     clearAccountMessages,
+    resetAccountCloseData,
     validateEmail,
     authenticatePusher,
     reauthenticatePusher,
diff --git a/src/pages/signin/LoginForm.js b/src/pages/signin/LoginForm.js
index e9813c3bf..bf6ec680b 100755
--- a/src/pages/signin/LoginForm.js
+++ b/src/pages/signin/LoginForm.js
@@ -111,6 +111,9 @@ class LoginForm extends React.Component {
         if (this.props.account.errors) {
             Session.clearAccountMessages();
         }
+        if (this.props.closeAccount.success) {
+            Session.resetAccountCloseData();
+        }
     }
 
     /**

```


Video:

https://user-images.githubusercontent.com/33489215/206882059-527c78e2-a66f-44d1-8e90-9e2c5dbbe673.mov

**Comment by Gonals** [comment]
Grabbing this one for #urgency

**Comment by mallenexpensify** [comment]
Thanks for snagging this @Gonals , I'm going to hang tight as BZ for now, let me know if you need help testing or anything.

**Comment by chiragsalian** [comment]
Qa tested the CP [PR](https://github.com/Expensify/App/issues/13498#issuecomment-1349518746) and its a pass, removing deploy blocker label

**Comment by mallenexpensify** [comment]
Testing to see if can close without checking boxes up top

**Comment by mallenexpensify** [comment]
Looks like it, not sure need to address
https://github.com/Expensify/App/issues/13506#issuecomment-1349866615
