### ISSUE TITLE
[HOLD for payment 2022-12-22] [HOLD for payment 2022-12-20]  If user tries to Request money after settling, error message is shown

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User A has requested money from User B
1. Access staging.new.expensify.com
2. Sign into a valid account (User B)
3. Navigate to the conversation with User A
4. Settle up
5. After settling, request a payment from User A

## Expected Result:
User expects the payment request to go through with no issues

## Actual Result:
User receives an error message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206919519-f0b132a1-6ab9-4f23-b75d-6655936c4406.mp4

**Expensify/Expensify Issue URL:** 1.2.38-0
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Taking a look!

**Comment by youssef-lr** [comment]
@Gonals I got a fixed for this in the linked issue by @robertjchen, see this Slack [convo](https://expensify.slack.com/archives/C049HHMV9SM/p1670635392505229)

**Comment by Gonals** [comment]
@youssef-lr, Ah, this was a duplicate, I see! 

I was actually going to create another one to fix the web side too, so let's just keep both! I think we should be doing both things anyways

**Comment by maddylewis** [comment]
okay, working on adding a regression test for this now.

**Comment by maddylewis** [comment]
buddy check if a regression test is needed here - https://expensify.slack.com/archives/C01SKUP7QR0/p1672152149673229

**Comment by Gonals** [comment]
This one got reverted, so checking out all options 🤷

**Comment by maddylewis** [comment]
>This one got reverted, so checking out all boxes 🤷

@Gonals does this mean we should close out the issue? or, should I still be adding a regression test to Test Rail?

**Comment by Gonals** [comment]
Ah, we can close this one. It was kind of a duplicate and it got fixed elsewhere, basically

**Comment by maddylewis** [comment]
okay, great! thanks for the clarification. ill go ahead and close this one out 👍
