### ISSUE TITLE
Unexpected error when money is requested right after settling up a request

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#13513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. User A requests money from User B.
2. User B settles up the request with the option I'll settle up elsewhere.
3. User A requests money again.

## Expected Result:
User should be able to request money.

## Actual Result:
Unexpected error requesting money is shown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:* * v1.2.38-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/9680864/206921374-bbc09357-a9fe-4238-b3e8-2faa435ff8c7.mov

**Issue reported by: @marcochavezf  
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670635392505229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
@mallenexpensify I just wanted to create this issue for record keeping, but I have a fix for it and I'm pushing a PR in a bit.

**Comment by robertjchen** [comment]
Possibly related? https://github.com/Expensify/App/issues/13511

**Comment by youssef-lr** [comment]
Correct @robertjchen, looks like it's the same bug. It can also be fixed in App so I'm not sure what's the better solution: https://expensify.slack.com/archives/C049HHMV9SM/p1670635392505229

**Comment by Gonals** [comment]
> Correct @robertjchen, looks like it's the same bug. It can also be fixed in App so I'm not sure what's the better solution: https://expensify.slack.com/archives/C049HHMV9SM/p1670635392505229

I did the App fix before I realized it was a duplicate! That works, since I think we should do both App and Web, so we can go halfsies 😁

**Comment by youssef-lr** [comment]
That sounds good!

**Comment by youssef-lr** [comment]
Closing this issue in favor of the other one.
