### ISSUE TITLE
Split Bill - Both Split Bills from 2 devices are considered valid instead of error message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with the same account in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. In the secondary device Split a bill with 2 users, this should create a new group and 2 new 1:1 conversations
4. In the main testing device (should be offline) create the SAME split bill with the 2 users
5. Enable internet in the main device

## Expected Result:
Duplicate chat with a red dot on the chat row in the LHN

## Actual Result:
No dup chats. Both Split Bills are accepted.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206942783-5ad98b73-da3e-4d34-b36c-3ce8ac0c7afb.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment]
if this is indeed a bug it should probably be internal as it might involve API changes.
I might just not be receivng the error, but I'm assigning this to me so I can investigate.

**Comment by sketchydroide** [comment]
actually not sure if this is a bug either, I mean we have no way to check if those are the SAME bill... they could be, they could be also 2 different bills with the exact same values, I mean suspicious of duplication, yes, bug, I don't think so...

**Comment by luacmartins** [comment]
I think this is intended.

**Comment by aldo-expensify** [comment]
I would close this, looks like an edge case, and making it smart enough for the optimistic reports to update in the second device that goes online sounds very difficult.

**Comment by sketchydroide** [comment]
Yeah let's close it
