### ISSUE TITLE
[HOLD for payment 2020-01-03] [$2000] Allow Form component to detect children that are Class components

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#13524]
# Problem

Our Form component is built to handle nested components and custom components within the form. That functionality is handled here. It seems, however, if the nested component is a Class component that the children of the class component aren't detected by the Form component. If the nested component is a Functional component, then it seems to work just fine. You can see this example [here](https://github.com/Expensify/App/pull/13515) where I added `Form` to the [WorkspaceNewRoom](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js) page and added two similar test components, one functional and one class based. The functional component is found by the form but the class based one isn't. Context Slack discussion: [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1670710080656329). 

<img width="768" alt="image (4)" src="https://user-images.githubusercontent.com/1371996/207129728-6ca9086d-de47-4c70-92e9-c871722cdc47.png">

# Solution 
Update this Form functionality so that it is able to find and recognize custom class-based sub-components. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019572d1017d216d70</li>
        <li>Upwork Job ID: 1602375844148887552
<li>Last Price Increase: 2023-01-03</li></li>
    </ul>
</details>

**Comment by fedirjh** [comment]
I think when component is class we should render it before we clone elements

```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 72ee4afc6b..7a61bb81df 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -193,6 +193,11 @@ class Form extends React.Component {
                 const nestedChildren = new child.type(child.props);
 
                 if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
+                    if (nestedChildren.render) {
+                        return React.cloneElement(child, {
+                            children: this.childrenWrapperWithProps(lodashGet(nestedChildren.render(), 'props.children')),
+                        });
+                    }
                     return child;
                 }
 

```

**Comment by puneetlath** [comment]
@fedirjh just capturing what we've discussed in Slack so far: when I try with the WorkspaceNewRoom page that doesn't quite work. But doing `children: this.childrenWrapperWithProps(nestedChildren.render())` does. 

However, we have a new problem when we do that where the validation function isn't called when the Class input is changed/blurred (it is called for the functional component).

**Comment by fedirjh** [comment]
@puneetlath After further investigation , i found that custom inputs are not detected due to this line :
 ```jsx
if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
```
if `nestedChildren === true` and `lodashGet(nestedChildren, 'props.children' === false` , this means that we have a valid react element that should be evaluated instead of returning the child as it is , we have also the check if we have a class component , if so we have to render it to get it's children or to check it's a valid react element 

```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 72ee4afc6b..41ef44ee23 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -190,71 +190,92 @@ class Form extends React.Component {
 
             // Look for any inputs nested in a custom component, e.g AddressForm or IdentityForm
             if (_.isFunction(child.type)) {
-                const nestedChildren = new child.type(child.props);
+                let nestedChildren = new child.type(child.props);
 
-                if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
-                    return child;
+                // If the custom component has a render method, use it to get the nested children
+                if (_.isFunction(nestedChildren.render)) {
+                    nestedChildren = nestedChildren.render();
                 }
 
-                return React.cloneElement(nestedChildren, {
-                    children: this.childrenWrapperWithProps(lodashGet(nestedChildren, 'props.children')),
-                });
-            }
+                // If the custom component has children,
+                if (lodashGet(nestedChildren, 'props.children')) {
+                    return React.cloneElement(nestedChildren, {
+                        children: this.childrenWrapperWithProps(nestedChildren),
+                    });
+                }
 
-            // We check if the child has the inputID prop.
-            // We don't want to pass form props to non form components, e.g. View, Text, etc
-            if (!child.props.inputID) {
-                return child;
+                // If the custom component has a single child, use it
+                if (React.isValidElement(nestedChildren)) {
+                    return this.inputWrapperWithProps(nestedChildren);
+                }
+
+                // If the custom component has no children, return the component as is
+                return nestedChildren;
             }
+            return this.inputWrapperWithProps(child);
+        });
+    }
+
+    /**
+     * Wrapper foreach input element that goes inside the Form component
+     *
+     * @param {React.Component} child - input element
+     * @returns {React.Component}
+     */
+    inputWrapperWithProps(child) {
+        // We check if the child has the inputID prop.
+        // We don't want to pass form props to non form components, e.g. View, Text, etc
+        if (!child.props.inputID) {
+            return child;
+        }
 
-            // We clone the child passing down all form props
-            const inputID = child.props.inputID;
-            const defaultValue = this.props.draftValues[inputID] || child.props.defaultValue;
+        // We clone the child passing down all form props
+        const inputID = child.props.inputID;
+        const defaultValue = this.props.draftValues[inputID] || child.props.defaultValue;
 
-            // We want to initialize the input value if it's undefined
-            if (_.isUndefined(this.state.inputValues[inputID])) {
-                this.state.inputValues[inputID] = defaultValue;
-            }
+        // We want to initialize the input value if it's undefined
+        if (_.isUndefined(this.state.inputValues[inputID])) {
+            this.state.inputValues[inputID] = defaultValue;
+        }
 
-            if (!_.isUndefined(child.props.value)) {
-                this.state.inputValues[inputID] = child.props.value;
-            }
+        if (!_.isUndefined(child.props.value)) {
+            this.state.inputValues[inputID] = child.props.value;
+        }
 
-            const errorFields = lodashGet(this.props.formState, 'errorFields', {});
-            const fieldErrorMessage = _.chain(errorFields[inputID])
-                .keys()
-                .sortBy()
-                .reverse()
-                .map(key => errorFields[inputID][key])
-                .first()
-                .value() || '';
-
-            return React.cloneElement(child, {
-                ref: node => this.inputRefs[inputID] = node,
-                value: this.state.inputValues[inputID],
-                errorText: this.state.errors[inputID] || fieldErrorMessage,
-                onBlur: () => {
-                    this.setTouchedInput(inputID);
-                    this.validate(this.state.inputValues);
-                },
-                onInputChange: (value, key) => {
-                    const inputKey = key || inputID;
-                    this.setState(prevState => ({
-                        inputValues: {
-                            ...prevState.inputValues,
-                            [inputKey]: value,
-                        },
-                    }), () => this.validate(this.state.inputValues));
-
-                    if (child.props.shouldSaveDraft) {
-                        FormActions.setDraftValues(this.props.formID, {[inputKey]: value});
-                    }
-
-                    if (child.props.onValueChange) {
-                        child.props.onValueChange(value);
-                    }
-                },
-            });
+        const errorFields = lodashGet(this.props.formState, 'errorFields', {});
+        const fieldErrorMessage = _.chain(errorFields[inputID])
+            .keys()
+            .sortBy()
+            .reverse()
+            .map(key => errorFields[inputID][key])
+            .first()
+            .value() || '';
+
+        return React.cloneElement(child, {
+            ref: node => this.inputRefs[inputID] = node,
+            value: this.state.inputValues[inputID],
+            errorText: this.state.errors[inputID] || fieldErrorMessage,
+            onBlur: () => {
+                this.setTouchedInput(inputID);
+                this.validate(this.state.inputValues);
+            },
+            onInputChange: (value, key) => {
+                const inputKey = key || inputID;
+                this.setState(prevState => ({
+                    inputValues: {
+                        ...prevState.inputValues,
+                        [inputKey]: value,
+                    },
+                }), () => this.validate(this.state.inputValues));
+
+                if (child.props.shouldSaveDraft) {
+                    FormActions.setDraftValues(this.props.formID, {[inputKey]: value});
+                }
+
+                if (child.props.onValueChange) {
+                    child.props.onValueChange(value);
+                }
+            },
         });
     }
 
```

**Comment by mollfpr** [comment]
@puneetlath I just test @fedirjh [proposal's](https://github.com/Expensify/App/issues/13524#issuecomment-1347434092). It seems working just fine for the class component but I think the changes that they made are too much to trace. I am more inclined if can just make small changes to handle the missing `props.children` and use the `render` function for the class component.

I'll leave it to you to decide.

**Comment by fedirjh** [comment]
@mollfpr basically I made change to this code block , the other part I just split the code for rendering form input to `inputWrapperWithProps` , so I can reuse it .

this is the code block I made changes 
```jsx
if (_.isFunction(child.type)) {
    const nestedChildren = new child.type(child.props);

    if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
        return child;
    }

    return React.cloneElement(nestedChildren, {
        children: this.childrenWrapperWithProps(lodashGet(nestedChildren, 'props.children')),
    });
}
```

these are the changes

```jsx
if (_.isFunction(child.type)) {
    let nestedChildren = new child.type(child.props);

    // If the custom component has a render method, use it to get the nested children
    if (_.isFunction(nestedChildren.render)) {
        nestedChildren = nestedChildren.render();
    }

    // If the custom component has children,
    if (lodashGet(nestedChildren, 'props.children')) {
        return React.cloneElement(nestedChildren, {
            children: this.childrenWrapperWithProps(nestedChildren),
        });
    }

    // If the custom component has a single child, use it
    if (React.isValidElement(nestedChildren)) {
        return this.inputWrapperWithProps(nestedChildren);
    }

    // If the custom component has no children, return the component as is
    return child;
}
``

**Comment by sandipanghos** [comment]
[puneetlath](https://github.com/puneetlath)
@[sobitneupane](https://github.com/sobitneupane)
sobitneupane

Is it still open for posting proposal?

**Comment by hungvu193** [comment]
@sandipanghos Yes, I believe that, you can submit proposal until one proposal is selected by the reviewers

**Comment by puneetlath** [comment]
Yes, as long as the `help wanted` label is there, you are free to submit proposals.

**Comment by sandipanghos** [comment]
> Yes, as long as the `help wanted` label is there, you are free to submit proposals.

THANKS

**Comment by sandipanghos** [comment]
> @sandipanghos Yes, I believe that, you can submit proposal until one proposal is selected by the reviewers

THANKS

**Comment by sobitneupane** [comment]
Looks like @mollfpr has worked in the related issue before and has already reviewed a proposal. @mollfpr You can take over C+ role if you want.

**Comment by fedirjh** [comment]
### Updated Proposal

cc @puneetlath , @mollfpr

> @puneetlath After further investigation , i found that custom inputs are not detected due to this line :
> if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
> if nestedChildren === true and lodashGet(nestedChildren, 'props.children' === false , this means that we have a valid react element that should be evaluated instead of returning the child as it is , we have also the check if we have a class component , if so we have to render it to get it's children or to check if it's a valid react element

```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index 72ee4afc6b..fe4a7506a4 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -190,12 +190,17 @@ class Form extends React.Component {
 
             // Look for any inputs nested in a custom component, e.g AddressForm or IdentityForm
             if (_.isFunction(child.type)) {
-                const nestedChildren = new child.type(child.props);
+                const childNode = new child.type(child.props);
+                const nestedChildren = _.isFunction(childNode.render) ? childNode.render() : childNode;
 
-                if (!React.isValidElement(nestedChildren) || !lodashGet(nestedChildren, 'props.children')) {
+                if (!React.isValidElement(nestedChildren) && !lodashGet(nestedChildren, 'props.children')) {
                     return child;
                 }
 
+                if (React.isValidElement(nestedChildren)) {
+                    return this.childrenWrapperWithProps(nestedChildren);
+                }
+
                 return React.cloneElement(nestedChildren, {
                     children: this.childrenWrapperWithProps(lodashGet(nestedChildren, 'props.children')),
                 });

```

**Comment by mollfpr** [comment]
Thanks, @sobitneupane! Yeah, it’s kinda awkward but I’ll let @puneetlath decide 👍

**Comment by mollfpr** [comment]
@fedirjh [proposal](https://github.com/Expensify/App/issues/13524#issuecomment-1352548981) **Solution 2** looks good to me.

Maybe add a comment about the `render()` is used for.

cc @puneetlath

**Comment by puneetlath** [comment]
@sobitneupane yes I think it makes sense for @mollfpr to be the C+ on this one. Thanks!

@mollfpr @fedirjh I agree proposal 2 (with an explaining comment). It's nice and clean. 

@fedirjh how would you like to implement that solution plus refactoring the `WorkspaceNewRoom` component to use the `Form` component in one PR. And we can update the bounty to $2k. 

Then after you've done that, I'll update the form validation as described [here](https://github.com/Expensify/App/issues/12678#issuecomment-1343229696). But for your PR, we shouldn't change any of the form functionality. Just update it to use the `Form` component, which it will now be able to do because your proposal will allow it to detect Class component children.

**Comment by mollfpr** [comment]
>@fedirjh how would you like to implement that solution plus refactoring the WorkspaceNewRoom component to use the Form component in one PR. And we can update the bounty to $2k.

I think it's a great idea. We also can test this issue with the refactor.

**Comment by fedirjh** [comment]
> @fedirjh how would you like to implement that solution plus refactoring the WorkspaceNewRoom component to use the Form component in one PR. And we can update the bounty to $2k.

@puneetlath  That's fair . I am ready to implement that + Refactoring the `WorkspaceNewRoom` in one PR . I will comment here once PR is ready.

**Comment by puneetlath** [comment]
Awesome! 

Upwork job is [here](https://www.upwork.com/jobs/~019572d1017d216d70) as well @mollfpr @fedirjh.

**Comment by fedirjh** [comment]
@puneetlath while refactoring `WorkspaceNewRoomPage` , I found that `RoomNameInput` is used in `ReportSettingsPage` , I think that we have to refactor that component too .
https://github.com/Expensify/App/blob/aa1605483c610f318c90e25ffb137fa9b357190c/src/pages/ReportSettingsPage.js#L194-L201

**Comment by fedirjh** [comment]
`WorkspaceNewRoomPage` Refactor is done , PR will be ready to review once other screenshots are added

https://user-images.githubusercontent.com/36869046/208528274-1dfa2514-1943-4dc4-90f9-bcbb01baf974.mov

**Comment by fedirjh** [comment]
@puneetlath , @mollfpr PR is ready #13713

**Comment by mollfpr** [comment]
The PR is in production. Starting the regression period!

**Comment by puneetlath** [comment]
@mollfpr can you apply here? https://www.upwork.com/jobs/~019572d1017d216d70

**Comment by mollfpr** [comment]
@puneetlath I think the bounty is updated to $2k ref [here](https://github.com/Expensify/App/issues/13524#issuecomment-1356894057) and the PR is eligible for the bonus.

**Comment by mollfpr** [comment]
@puneetlath applied!

**Comment by puneetlath** [comment]
@fedirjh has been paid. 

Offer has been sent for @mollfpr.

**Comment by mollfpr** [comment]
@puneetlath accepted 👍

**Comment by puneetlath** [comment]
All paid with 50% bonus. Thanks y'all!
