### ISSUE TITLE
[$1000] Report list section is empty while sliding.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. Tap on a report
3. Slide to the right to go to home screen

## Expected Result: 
Screen should not be empty

## Actual Result: 
Screen is empty

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.38-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207218692-e973bd26-5f89-4161-a112-d2f7bdece129.mp4

https://user-images.githubusercontent.com/43996225/207218723-9cde55f5-097e-4a93-b26b-687a9d29ecd7.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670861157206459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a4b9a273415b3b1</li>
        <li>Upwork Job ID: 1602531600076718080</li>
        <li>Last Price Increase: 2022-12-13</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I was able to reproduce this on BrowserStack with the latest version of the app.

**Comment by gadhiyamanan** [comment]
@kavimuru it's reported on [slack here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666164789084899)

**Comment by jatinsonijs** [comment]
**Proposal**

I think this one did intensionally to optimise re render when sidebar (LHNOptionsList) not visible should not update them. In this case its replace with null by react-freeze to optimise re-render.

```diff
diff --git a/src/pages/home/sidebar/SidebarLinks.js b/src/pages/home/sidebar/SidebarLinks.js
index 12a09d5e18..8935e40119 100644
--- a/src/pages/home/sidebar/SidebarLinks.js
+++ b/src/pages/home/sidebar/SidebarLinks.js
@@ -169,25 +169,23 @@ class SidebarLinks extends React.Component {
                         />
                     </TouchableOpacity>
                 </View>
-                <Freeze freeze={this.props.isSmallScreenWidth && !this.props.isDrawerOpen && this.isSidebarLoaded}>
-                    <LHNOptionsList
-                        contentContainerStyles={[
-                            styles.sidebarListContainer,
-                            {paddingBottom: StyleUtils.getSafeAreaMargins(this.props.insets).marginBottom},
-                        ]}
-                        data={optionListItems}
-                        focusedIndex={_.findIndex(optionListItems, (
-                            option => option.toString() === this.props.reportIDFromRoute
-                        ))}
-                        onSelectRow={this.showReportPage}
-                        shouldDisableFocusOptions={this.props.isSmallScreenWidth}
-                        optionMode={this.props.priorityMode === CONST.PRIORITY_MODE.GSD ? 'compact' : 'default'}
-                        onLayout={() => {
-                            App.setSidebarLoaded();
-                            this.isSidebarLoaded = true;
-                        }}
-                    />
-                </Freeze>
+                <LHNOptionsList
+                    contentContainerStyles={[
+                        styles.sidebarListContainer,
+                        {paddingBottom: StyleUtils.getSafeAreaMargins(this.props.insets).marginBottom},
+                    ]}
+                    data={optionListItems}
+                    focusedIndex={_.findIndex(optionListItems, (
+                        option => option.toString() === this.props.reportIDFromRoute
+                    ))}
+                    onSelectRow={this.showReportPage}
+                    shouldDisableFocusOptions={this.props.isSmallScreenWidth}
+                    optionMode={this.props.priorityMode === CONST.PRIORITY_MODE.GSD ? 'compact' : 'default'}
+                    onLayout={() => {
+                        App.setSidebarLoaded();
+                        this.isSidebarLoaded = true;
+                    }}
+                />
             </View>
         );
     }

```

If we want to show sidebar always we can remove freeze from LHNOptionsList.

**Comment by jasperhuangg** [comment]
Hangggg on here, I'm not entirely sure this issue needs to be fixed, it sounds like to me that this is an optimization that was very much intentional, and removing this would probably be a regression.

The `Freeze` component was added [here](https://github.com/Expensify/App/pull/11550). Marc outlines [here](https://github.com/Expensify/App/issues/11426#issuecomment-1271878350) how "the only downside is that the frozen elements show as hidden when we are swiping". So it's actually expected that the report list is empty while sliding–it's a side-effect of using the `Freeze` library.

@marcaaron Do you think we should keep this issue open? Is it worth investigating a solution for this? Feels SUPER edge casey to me and also not important to "fix" at all.

**Comment by luacmartins** [comment]
I agree with @jasperhuangg's comment above. @marcaaron could you please confirm if this is expected?

**Comment by marcaaron** [comment]
Yep, this is not a bug. Maybe a feature request - but the freeze component is intentional.
