### ISSUE TITLE
Expensify specialist profile load after refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13562]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create a new user
2. Create new workspace
3. go to #admins
4. go to Expensify specialist profile

## Expected result: 
It should show Expensify specialist profile(email, local time, profile pic ,preferred pronouns, etc…)

## Actual result: 
Some details (local time, profile pic ,preferred pronouns) load after refresh

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.38-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207421404-c23868a8-13e7-4794-a450-04d57d3e493b.mov

https://user-images.githubusercontent.com/43996225/207421459-1e68b3c3-4990-4685-b8ee-1d377496b2e4.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670942773710119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll review this one tomorrow.

**Comment by yuwenmemon** [comment]
I'll take a look at this one

**Comment by alexpensify** [comment]
Thanks @yuwenmemon!

**Comment by yuwenmemon** [comment]
Found it - looks like we need to update the user's local personal details when we add a guide to their policy:
<img width="1421" alt="Screenshot 2022-12-15 at 2 15 51 PM" src="https://user-images.githubusercontent.com/4741899/207978961-3af1e501-b12b-4459-a47a-f7e9a4c993c1.png">

The reason it shows up in the chat is that those messages also come with a copy of the personal details:
<img width="687" alt="Screenshot 2022-12-15 at 2 21 45 PM" src="https://user-images.githubusercontent.com/4741899/207979772-3fa7d500-c7bb-4d8a-b98c-dd701fe08e4d.png">

**Comment by alexpensify** [comment]
Weird but good catch!

**Comment by yuwenmemon** [comment]
Associated PR has gone to prod: https://github.com/Expensify/Web-Expensify/pull/35848

Closing!

**Comment by alexpensify** [comment]
@gadhiyamanan - I've sent an offer for reporting this bug. Please accept in Upwork and I can complete the process.

**Comment by alexpensify** [comment]
Closing - The process has been completed in Upwork.
