### ISSUE TITLE
Update dark mode colors

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13564]
We'd like to make some adjustments to dark mode to make it a bit more friendly on the eyes. The feedback we received was:
- The greens feel a bit too saturated and make the app feel almost too much like a theme or skin
- There is too much contrast between sidebar and chat content
- The white text has too much contrast with the background of the app
- People want to be able to go back to light mode

Before entertaining the last option, we’d like to perfect the dark mode theme first and address the first three bullets. So that being said, let's do this:
- darken white text from #FFFFFF to #E7ECE9
- darken supporting text from #C9D3C5 to #AFBBB0
- darken and desaturate borders from #1B5744 to #1A3D32
- darken LHN/highlight BG color from #002E22 to #07271F
- get rid of the rightBorder on the LHN, and use the inset style with rounded edges to reduce the harshness of the border

That gives us something like this:
![image](https://user-images.githubusercontent.com/2319350/207422981-b7c8c656-ef3e-4a73-b853-4923d0d96f60.png)

Figma is [here](https://www.figma.com/file/OgM6vzR98Qnr1gdmZOQPKz/Implement-Our-New-Brand?node-id=545%3A12457&t=C9lHjlythZ9EyXiP-1).

For the sidebar changes, I had trouble getting rid of the white background behind the sidebar area as a heads up:
![image](https://user-images.githubusercontent.com/2319350/207423124-1624b3b6-bea2-428d-91f0-ba901e37724f.png)

Also for the sidebar:
- we only want the rounded/inset effect to happen on desktop
- to achieve this effect, we just need to give the sidebar a border of 8px using the same color as the appBG. Note that we can try making it so that we only have borderTop, borderLeft, and borderBottom. If we have 0 for borderRight, I think the content will fit snugly against the LHN <img width="806" alt="image" src="https://user-images.githubusercontent.com/2319350/207423484-1da836fb-e30d-473c-a8c5-2f57cd4328d3.png">
- We also might want to consider making the LHN a bit wider since the border will eat up 16px of space. So maybe we bump up the sidebar width from 375px to something like 392px? (I love numbers divisible by 4 hehe)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b424baf5aca597d8</li>
        <li>Upwork Job ID: 1608286351255846912</li>
        <li>Last Price Increase: 2022-12-29</li>
    </ul>
</details>

**Comment by grgia** [comment]
Will all true whites in the app be replaced with #E7ECE9? Or only text/buttons?

**Comment by shawnborton** [comment]
Good question. I think it can't hurt to just update the white variable we are using in colors.js:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/2319350/207427137-d5b3547c-7751-43f5-bfff-b28ad70d6814.png">

**Comment by grgia** [comment]
Quick color check:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/38015950/207428201-1f368486-cd43-4d09-a820-ebfbdba7155a.png">

**Comment by shawnborton** [comment]
Yup, that checks out!

**Comment by grgia** [comment]
Do you know what might cause the sharp corners on the bottom section? I figured I'm applying the style in the wrong place. Pink for visibility :)
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/38015950/207441918-e48200a1-6692-4e36-b03b-925218b43f69.png">

**Comment by grgia** [comment]
Here's where I'm at! For personal reference, I think I might need to add the border to the drawer styles instead
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/38015950/207449396-60fcf0f3-4dec-4706-8199-6243d3705e92.png">

**Comment by grgia** [comment]
While I'm here, do you have an idea of what the RHN would look like? Would it have the same border?

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/38015950/207452190-9fa29334-505c-46d3-86da-6315e0fd7d3a.png">

**Comment by shawnborton** [comment]
Nice! 

For the RHN, I think we can just leave it as-is. 

I have no idea why the bottom is not getting the roundedness that we want, perhaps we need to add `overflow:hidden` to that container?

Also for the top right of the LHN, it doesn't quite look perfectly rounded - any idea what's happening there? 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/2319350/207495758-ebfd39fa-84d4-4b2f-b738-2bc25a13a70b.png">

**Comment by mallenexpensify** [comment]
@mananjadhav can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01b424baf5aca597d8

**Comment by mananjadhav** [comment]
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment]
Paid @mananjadhav $1000. 
Unsure if we want to update regression test steps for this so leaving open (I'm assigned) and bumping to weekly

**Comment by mananjadhav** [comment]
@grgia @shawnborton do we need to add regression steps here? else we can close this one out?

**Comment by shawnborton** [comment]
I think we decided not to add anything for now? cc @grgia @JmillsExpensify

**Comment by mallenexpensify** [comment]
Gonna close until we have a plan for design-related issues.  Otherwise it's updating the test steps "verify new dark mode colors are _everywhere_" which isn't too helpful or actionable.
