### ISSUE TITLE
Standardize on one method for detecting keyboard state

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#13582]
# Problem
There are two ways for components to detect the keyboard state:

1. Using the HOC `withKeyboardState` - this works on native devices, but doesn't have support for mobile web
2. Using `VirtualKeyboard.shouldAssumeIsOpen()` - this appears to work on both native devices and mobile web. Originally added in [this PR](https://github.com/Expensify/App/pull/7390).

Neither option is used consistently, leading to inconsistent behavior in the app. 

# Solution
- Make sure that `VirtualKeyboard` works for mobile web
- Move the functionality from `VirtualKeyboard` into `withKeyboardState`
- Use `withKeyboardState` everywhere
- Remove `VirtualKeyboard`

CC @jasperhuangg @parasharrajat 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e011fc436edaf3d0</li>
        <li>Upwork Job ID: 1608620601075437568</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by tgolen** [comment]
Sorry @flaviadefaria, this is not a bug, just a cleanup issue, so I am removing your assignement.

**Comment by tgolen** [comment]
All right, here is what I found out. Virtual keyboard exports two methods:

1. `isOpen()` - Is always the same as `props.isShown` on all platforms and it's only used in one place [here](https://github.com/Expensify/App/blob/5e297476d5ac1ed10f4151b3bbce0adb5f944d4c/src/components/HeaderWithCloseButton.js#L145). That can easily be replaced with `props.isShown`
2. `shouldAssumeIsOpen()` - Is always the same as `props.isShown` for native devices. It always returns `true` for mobile web platforms. It's used in 4 places and is almost always used as a proxy for "is this mobile web?" which is also the same as `isSmallScreenWidth` (usually)

So, I think that all of this can be refactored to just use the two HOCs we currently have for `withKeyboardState` and `withDimensions` and we can remove the `VirtualKeyboard` lib entirely.

**Comment by tgolen** [comment]
Hm, I'm not sure why GH didn't link the PR with this issue https://github.com/Expensify/App/pull/13629 but this was deployed to production, so I'm going to close this.

**Comment by mallenexpensify** [comment]
@thesahindia can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01e011fc436edaf3d0

**Comment by thesahindia** [comment]
Accepted, thanks!

**Comment by mallenexpensify** [comment]
Paid @thesahindia , closing cuz this shouldn't need regression test steps
