### ISSUE TITLE
[$1000] reportID prop type errors for IOU chats

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#13591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
IOU requests to another user

1. Request money a user
2. Go to the chat with that user
3. Refresh the page

IOU requests from another user

1. With an account A, request money from account B
2. Log in as account B and go to the chat with the request
3. Click on the IOU request to open the details page

## Expected Result:
No console errors appear

## Actual Result:
After IOU requests to another user the following console errors appear.
1. Warning: Failed prop type: Invalid prop `walletTerms.chatReportID` of type
`number` supplied to `AvatarWithIndicator`, expected `string`.
2. Warning: Failed prop type: Invalid prop `walletTerms.chatReportID` of type
`number` supplied to `IOUPreview`, expected `string`. 

After IOU requests from another user the following console errors appear.
1. Warning: Failed prop type: Invalid prop `chatReportID` of type `number`
supplied to `SettlementButton`, expected `string`.
2. react_devtools_backend.js:4012 Warning: Failed prop type: Invalid prop
`chatReportID` of type `number` supplied to `KYCWall`, expected `string`.

## Workaround:
Console errors don't negatively affect the app at all.

## Platform:

All

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.39-0
**Reproducible in staging?:** No, dev only
**Reproducible in production?:** No, dev only
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://user-images.githubusercontent.com/26260477/207697724-c7e74c04-ef4f-4e88-9d9c-8d0aeca0418d.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671046426516899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cd2c068185ca063</li>
        <li>Upwork Job ID: 1616154481973350400</li>
        <li>Last Price Increase: 2023-01-19</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
Today I was working on my monthly issues so I didn't get to this.

**Comment by neil-marcellini** [comment]
Today I was working on my weekly issues so I didn't get to this.

**Comment by neil-marcellini** [comment]
I spent a lot of time on a PR review today so I didn't get to this again. I plan to work on it tomorrow.

**Comment by neil-marcellini** [comment]
I didn't get to this yet again. I've been reviewing a lot of PRs and that's higher priority than my own work.

**Comment by neil-marcellini** [comment]
Now I'm taking a look 👀

**Comment by neil-marcellini** [comment]
I tested again on the latest in my dev environment and I no longer see any prop type errors when sending an IOU request to another user. I do still see errors when the user has received and IOU request.

**Comment by neil-marcellini** [comment]
This was deployed to production last week with this PR https://github.com/Expensify/App/pull/13783. We really need to fix our GH integrations now that the issues are locked. I will bring that up in Slack.

**Comment by arielgreen** [comment]
@sobitneupane offer sent in Upwork, once accepted I will issue payment.

**Comment by sobitneupane** [comment]
@arielgreen Thanks. Accepted the offer.

**Comment by arielgreen** [comment]
Paid, closing.
