### ISSUE TITLE
 Indent formatting in NewDot doesn't apply to email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Typed up a message in NewDot with a custom subject line to be sent to the user's email instantly.
2. In the body of the message I included space indents on the bullet points.

## Expected Result:
The indent spacing should have shown in the message that hit the user's email inbox
## Actual Result:
The body of the message in the user's email inbox didn't translate to the spacing I used in the NewDot message I sent.
Platforms:

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="Untitled1" src="https://user-images.githubusercontent.com/43996225/207714057-d06cd4e9-f5b7-4ed9-af5c-f721009b8cb8.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/207714059-7a0a10e5-a18d-435c-ae8b-ec2155bdf95e.png">
<img width="846" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/207714084-9601bce7-9f47-453e-b6b2-90d3917656ac.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/43996225/207714086-44d27a40-13c7-484a-9e8a-7429e4696894.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670968755788469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
This is internal, fo sho.

**Comment by sophiepintoraetz** [comment]
I was just thinking so too - cool 👍

**Comment by yuwenmemon** [comment]
@kavimuru Do you have a sample text for this? The indents I get from the Concierge compose tool work well...
<img width="483" alt="Screenshot 2022-12-20 at 2 12 04 PM" src="https://user-images.githubusercontent.com/4741899/208768066-07d680c6-abcc-4fad-b5b9-e4ee0cc7cd98.png">

**Comment by sophiepintoraetz** [comment]
I'm able to reproduce this, @yuwenmemon - it can be any text. It's also not from the concierge compose tool, it's from within NewDot:

![image](https://user-images.githubusercontent.com/42940078/208775935-6883cd7d-1fe9-42e6-a067-09478bbbf6df.png)

**Comment by yuwenmemon** [comment]
Okay I see and then to confirm @sophiepintoraetz how are you making those indentations? With tabs or spaces?

**Comment by sophiepintoraetz** [comment]
Spaces - I don't think you can tab indent on NewDot?
>I included space indents on the bullet points.

**Comment by yuwenmemon** [comment]
Okay, hmmm... so this has probably always existed. Here are a couple of sample emails.

---

This first one is sent with a header [via](https://github.com/Expensify/Web-Expensify/blob/45ac16160d44f06fcd0e462217c7ae91b205064c/lib/ReportUtils.php#L1993) [`createCustomSubjectCommentNotifications`](https://github.com/Expensify/Web-Expensify/blob/45ac16160d44f06fcd0e462217c7ae91b205064c/lib/ReportUtils.php#L2032-L2046), which uses this Notification class: [`Notification_Report_CustomSubjectComment`](https://github.com/Expensify/Web-Expensify/blob/8be6c82e68508d8d5bbc33e2a309659ab131a838/lib/Notification/Report/CustomSubjectComment.php):
<img width="1053" alt="Screenshot 2022-12-20 at 4 56 16 PM" src="https://user-images.githubusercontent.com/4741899/208789734-67104f1f-23d4-4815-afa0-9277580b64e2.png">
<img width="344" alt="Screenshot 2022-12-20 at 4 55 18 PM" src="https://user-images.githubusercontent.com/4741899/208789781-74b3b715-b418-48e2-a6cd-cf7f3589274a.png">
```HTML
Hey Yuwen please:<br />- Chill out<br />    - Something else<br />    - some other thing<br />    - Another thing<br />        - Some other other thing<br />
<br />
Switch to <a href="https://www.expensify.com.dev/chat?email=yuwen%40expensify.com&validateCode=JQYXOGTHQ" target="_blank">live chat</a> in Expensify for faster responses.
```

---

This second one is sent with a header [via](https://github.com/Expensify/Web-Expensify/blob/45ac16160d44f06fcd0e462217c7ae91b205064c/lib/ReportUtils.php#L1995) [`createNotifyOfflineUsersAboutActivityJob`](https://github.com/Expensify/Web-Expensify/blob/45ac16160d44f06fcd0e462217c7ae91b205064c/lib/ReportUtils.php#L2104-L2119), which uses this Notification class: [`Notification_Report_Comment `](https://github.com/Expensify/Web-Expensify/blob/3527a9a2636445f270670b9ee012720d17954b5d/lib/Notification/Report/Comment.php):

<img width="832" alt="Screenshot 2022-12-20 at 4 52 57 PM" src="https://user-images.githubusercontent.com/4741899/208790252-39f7bdc7-9ebb-453b-808b-638945a3be31.png">
<img width="471" alt="Screenshot 2022-12-20 at 4 52 49 PM" src="https://user-images.githubusercontent.com/4741899/208790274-fbbc5797-4c14-49bb-816a-003fae7577f9.png">
```HTML
Yuwen Memon: Hello<br />
<br />
Yuwen Memon: hello<br />- One<br />  - Two<br />- Three<br />
<br />
To respond, head over to <a href="https://new.expensify.com/r/65834908" target="_blank">new.expensify.com</a> or reply directly to this message.
```

**Comment by yuwenmemon** [comment]
As seen by this [fiddle](https://texteditor.com/html/editor/?html=%27%3Cp%3EHey%20Yuwen%20please:%3Cbr%20/%3E-%20Chill%20out%3Cbr%20/%3E-%20Something%20else%3Cbr%20/%3E-%20some%20other%20thing%3Cbr%20/%3E-%20Another%20thing%3Cbr%20/%3E-%20Some%20other%20other%20thing%3Cbr%20/%3E%3Cbr%20/%3ESwitch%20to%20%3Ca%20href=%22https://www.expensify.com.dev/chat?email=yuwen%2540expensify.com$**$amp;vali$*$dateCode=JQYXOGTHQ%22%20target=%22_blank%22%3Elive%20chat%3C/a%3E%20in%20Expensify%20for%20faster%20responses.%3C/p%3E&css=), HTML is always not going to play nice with leading spaces. We'll need to add leading `&nbsp;` characters to fix this like so: [fiddle](https://texteditor.com/html/editor/?html=%27%3Cp%3EHey%20Yuwen%20please:%3Cbr%20/%3E-%20Chill%20out%3Cbr%20/%3E$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;-%20Something%20else%3Cbr%20/%3E$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;-%20some%20other%20thing%3Cbr%20/%3E$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;-%20Another%20thing%3Cbr%20/%3E$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;$**$nbsp;-%20Some%20other%20other%20thing%3Cbr%20/%3E%3Cbr%20/%3ESwitch%20to%20%3Ca%20href=%22https://www.expensify.com.dev/chat?email=yuwen%2540expensify.com$**$amp;vali$*$dateCode=JQYXOGTHQ%22%20target=%22_blank%22%3Elive%20chat%3C/a%3E%20in%20Expensify%20for%20faster%20responses.%3C/p%3E&css=)

**Comment by yuwenmemon** [comment]
[Web PR](https://github.com/Expensify/Web-Expensify/pull/35899) for this has been out for a while. Closing!
