### ISSUE TITLE
[HOLD for payment 2023-01-13] `Report no longer exists` error after cancelling and re-requesting money

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#13624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open an existing chat with no IOUs and request money
2. Cancel the request
3. Create a second IOU request

## Expected Result:
The console should be free from errors

## Actual Result:
There's a `Report no longer exists` error in the console

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1512" alt="Screenshot 2022-12-15 at 12 30 24 PM" src="https://user-images.githubusercontent.com/7277067/207928352-b8aacc05-daed-4f8a-9c5e-33944299c35a.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
PRs up for this:
- https://github.com/Expensify/Web-Expensify/pull/35846
- https://github.com/Expensify/App/pull/13625

**Comment by amyevans** [comment]
Unlocking because I _think_ the lock is preventing bot messages from showing up here. The Web-E PR is on production and the App PR has been merged so should be on staging after the next App deploy.

**Comment by amyevans** [comment]
Code is on prod, closing.

**Comment by mananjadhav** [comment]
@amyevans @bfitzexpensify This is still pending for C+ payout.

**Comment by amyevans** [comment]
@mananjadhav thanks for raising, sorry about that! @bfitzexpensify can you handle please?

**Comment by mananjadhav** [comment]
@bfitzexpensify Quick bump on this one.

**Comment by mananjadhav** [comment]
Thanks @bfitzexpensify for the help here.
