### ISSUE TITLE
mWeb (iOS) - Cursor is not visible on New Chat and New Group page,

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. From LHN, click Plus button, choose New Char or New Group.
3. Notice that cursor is not visible on search input and the keyboard is hide.

## Expected Result:
Keyboard should  appear and cursor should be visible on the input

## Actual Result:
cursor is not visible on search input and the keyboard is hide.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web iOS only

**Version Number:** 1.2.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207936011-9757a9fc-ae4d-4c5a-80c8-e8858b926d1b.MP4

https://user-images.githubusercontent.com/43996225/207936040-c4e249bd-f915-4e07-82f7-bb0cc7265ef5.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671031967952909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Closing, this is a dupe and known issue on iOS safari that's in development: https://github.com/Expensify/App/issues/10414
