### ISSUE TITLE
[Hold for payment 2023-01-03] Back Button inside ResendValidationForm isn't displayed as link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to login page
2. Type email and continue to password page
3. Click Forget password
4. Check Back button

## Expected Result: 
Back button should inherit link style and displayed as link

## Actual Result: 
Back button does not inherit link style and isn't displayed as link

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207933170-5955b8be-df98-4052-98f5-abfada558c76.mov

https://user-images.githubusercontent.com/43996225/207933213-5a025a95-51e4-48f7-863c-d3081082a0cd.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @fedirjh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671043886770209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3d91135ab0e997d</li>
        <li>Upwork Job ID: 1612506758739214336</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Gonna work on this one!

**Comment by kadiealexander** [comment]
Sweet! Staying on board so I can issue the reporting bonus to @fedirjh :)

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/13670)

**Comment by kadiealexander** [comment]
I'm going OOO for a family emergency, if this needs action while I'm away please re-add the `bug` label to assign someone.

**Comment by luacmartins** [comment]
@kadiealexander could you please help with the payment for the [PR review](https://github.com/Expensify/App/pull/13670)? This should be a flat $1000 payment to @mollfpr!

**Comment by luacmartins** [comment]
@kadiealexander I forgot this in my last comment, but we also need to pay the reporting bonus to @fedirjh!

**Comment by luacmartins** [comment]
Reassigning since Kadie is ooo

**Comment by luacmartins** [comment]
@kevinksullivan could you please help with payment? 

Reporting bonus $250 to @fedirjh
PR Review bonus $1000 to @mollfpr

**Comment by luacmartins** [comment]
Ah yea, I missed the internal label. Thanks for adding it @mallenexpensify!

**Comment by mallenexpensify** [comment]
Sorry @rushatgabhane , forgot to add @mollfpr before relabeling `Internal` to get the Upwork job created

Hired @mollfpr and @fedirjh, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01a3d91135ab0e997d

**Comment by fedirjh** [comment]
@mallenexpensify Thank you. Offer accepted!!

**Comment by mollfpr** [comment]
@mallenexpensify Accepted!

**Comment by kevinksullivan** [comment]
Paid @mollfpr and @fedirjh ! Upwork is giving me trouble ending the contract with @fedirjh , if you want to try and take care of that @mallenexpensify ? Otherwise I've noted to give it a try again tomorrow.

**Comment by fedirjh** [comment]
@kevinksullivan I got the payment too . You have to cancel the 2nd offer.
