### ISSUE TITLE
[Hold for payment 2023-01-03] Manage member -  Pointer appears when hovering over admin checkbox 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Select any workspace
2. Go to manage members page
3. Observe the owner row checkbox(cursor changes to pointer)

## Expected Result: 
Checkbox should not be clickable and pointer events needs to be none

## Actual Result: 
Checkbox is clickable and cursor changes to pointer

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** `1.2.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207935002-2168a700-a495-48c5-a60a-332fcebabb26.mp4

https://user-images.githubusercontent.com/43996225/207935027-4be8ddf6-1e82-4624-b0e6-c303b335e25c.mov

 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671021630899279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Gonna work on this one!

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/13669)

**Comment by luacmartins** [comment]
Not sure why the title wasn't updated, but this is due for payment since the fix was deployed to production on Dec 27th. @miljakljajic could you please help with the payment for the reporting bonus?

**Comment by luacmartins** [comment]
@miljakljajic it looks like there was an error on our side and @jayeshmangwani [reported this bug on Nov 10th](https://expensify.slack.com/archives/C01GTK53T8Q/p1668096360414929) but we didn't create an issue for it. Given that we missed that, I think that we should pay the reporting bonus to both @jayeshmangwani and @Pujan92.

**Comment by miljakljajic** [comment]
Thank you Carlos - I've been OOO but I will issue these payments now. Apologies for the delay!

**Comment by miljakljajic** [comment]
@jayeshmangwani and @Pujan92 Can you please approve the offers in Upwork and I'll get you paid right away?

**Comment by miljakljajic** [comment]
Paid! Closing.
