### ISSUE TITLE
[Core Branding] Quick update to some arrow icons

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13637]
Some of the arrow icons we recently added were feeling a little bit chunky, so let's update them with some new ones that reduce the thickness a bit:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/2319350/207951033-18a821aa-b664-4913-9d31-563a605adfe1.png">

Those icons are here: [NewIcons.zip](https://github.com/Expensify/App/files/10240089/NewIcons.zip)

cc @grgia & @Luke9389 in case either of you want to grab this one quickly
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01651b1a239a117c02</li>
        <li>Upwork Job ID: 1618331566704562176</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by grgia** [comment]
Will do!

**Comment by puneetlath** [comment]
@kevinksullivan can you help with getting @thesahindia paid out for internal PR review?

**Comment by kevinksullivan** [comment]
@thesahindia offer sent!
