### ISSUE TITLE
[HOLD for payment 2022-12-28] Bottom of FAB does not align with bottom of chat input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot and login

## Expected Result:
Bottom of FAB should align with bottom of chat input

## Actual Result:
Bottom of FAB does not align with bottom of chat input

## Workaround:
visual

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="251" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/207956830-d2e856d4-5ddf-4dfd-a8c3-227868a43391.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/207956884-71d89e94-ff3f-4c16-81cd-ca26b8934dc5.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671133234889739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
PR [up](https://github.com/Expensify/App/pull/13646)

**Comment by luacmartins** [comment]
This one is done! Fix deployed to prod 2 weeks ago. Issue was reported and fixed internally and C+ didn't review the PR. Closing!
