### ISSUE TITLE
iOS - No prompt for not notifications after fresh install and no notifications received

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Fresh install the app from TF or App store
2. Open the app 

## Expected Result:
After fresh install should prompt to get push notification permission
## Actual Result:
After fresh install I don't get push notification permission request on iOS and therefore I don't receive push notifications

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS 

**Version Number:** 1.2.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207942945-5d80457e-45ad-490b-8fa9-d4ed505d99c4.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @cristipaval 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671129176362069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
Hey @dylanexpensify ! I discovered this while working on Push Notification Rework DD. I'm going to spend some time investigating it internally. I'll keep you updated.

**Comment by dylanexpensify** [comment]
Love it, thanks @cristipaval !

**Comment by Julesssss** [comment]
I don't understand why your PR wasn't auto-linked to this issue by Github 😕

**Comment by cristipaval** [comment]
oh, I didn't observe this. But looks like Melvin added `Reviewing` label for me 👀

**Comment by cristipaval** [comment]
@MelvinBot, doing your job here. [The PR](https://github.com/Expensify/App/pull/13674#issuecomment-1358909730) linked to this job was deployed to staging.

**Comment by cristipaval** [comment]
Closing this one because [the PR](https://github.com/Expensify/App/pull/13674#issuecomment-1358909730) was deployed to production.
