### ISSUE TITLE
[HOLD for payment 2023-01-26] Make `getMergeLogsAsJSON` more robust

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#13649]
### Problem

We've got some code [here](https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/.github/libs/GitUtils.js#L11-L49) that logs commit message [using `git log`](https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/.github/libs/GitUtils.js#L12) and then [sanitizes the output and turns it to JSON](https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/.github/libs/GitUtils.js#L38-L47).

This code is fickle, because any symbols included in commit messages that break `JSON.parse` will cause an error. We've seen a number of instances of this happening over the last year, and it seems likely to continue happening until we nail this code down a bit more robustly.

### Solution

1. Extract a small module to `src/libs/sanitizeStringForJSON`, that [escapes special characters](https://github.com/Expensify/App/blob/3620bf2fbeba22429e1497802c183626b5803fad/.github/libs/GitUtils.js#L38-L42) from a string to prepare it to be used in `JSON.parse`
1. Use this library in `GitUtils.getMergeLogsAsJSON`
1. Add a new set of Jest unit tests to cover `sanitizeStringForJSON`.

[Here](https://expensify.slack.com/archives/C07J32337/p1671038078880069?thread_ts=1670871959.612579&cid=C07J32337) are some suggestions to get you started.

**Comment by mallenexpensify** [comment]
Any idea why the `Awaiting Payment` label got added, don't seen a linked PR anywhere, asking cuz wondering if anyone is due compensation

**Comment by roryabraham** [comment]
Idk, @yuwenmemon implemented this so the awaiting payment stuff was not correct in this case

**Comment by yuwenmemon** [comment]
Yeah no one would be due compensation here.

Not sure why we don't see the linked PR as I correctly linked to it here: https://github.com/Expensify/App/pull/14351

Anyway. closing this out!
