### ISSUE TITLE
Editing a message with 3 backticks is being deleted/hidden from the chat history

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a message with 3 backpacks (e.g. ```hello world```)
2. Press edit from context menu
3. Press save changes without editing message
4. The message will be visible for a second and then message will disappear from chat

## Expected Result:
message should visible

## Actual Result:
message being disappear

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** no
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208135559-62744919-1c61-4f93-b419-859ae502bc94.mp4

https://user-images.githubusercontent.com/43996225/208135579-aa6df689-95d6-48e1-9da1-0e5da4b04219.mov

https://user-images.githubusercontent.com/43996225/208136634-3bcae818-13a9-44ea-b6d1-95b28fc28b33.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671137546067359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Auto-posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1671205727057609

@iwiznia - I'm not sure how to figure out which PR caused the bug. Does this stay internal for us to figure out?

**Comment by lschurr** [comment]
Posted here since I'm not sure what to do with this. https://expensify.slack.com/archives/C01SKUP7QR0/p1671215514971019

**Comment by lschurr** [comment]
Asked here as well - https://expensify.slack.com/archives/C03TQ48KC/p1671468234738599

**Comment by yuwenmemon** [comment]
Damn, I'm actually seeing the same issue on Prod. Which means I'll remove the Deploy Blocker and mark this Daily since it seems pretty important to fix.

**Comment by yuwenmemon** [comment]
Okay NVM. This was indeed coming from https://github.com/Expensify/App/pull/13536 so reapplying the Deploy Blocker label.

**Comment by yuwenmemon** [comment]
@lschurr as long as there are no regressions can we pay out the reporting bonus for @jayeshmangwani here?

**Comment by lschurr** [comment]
Yep - I'll create the job in Upwork.

**Comment by lschurr** [comment]
Posted: https://www.upwork.com/jobs/~011787fa571016cf6f

@jayeshmangwani - can you apply to the job in Upwork?

**Comment by lschurr** [comment]
Extended offer in Upwork. Will pay once @jayeshmangwani accepts.

**Comment by lschurr** [comment]
Paid!
