### ISSUE TITLE
iOS -  Google search input has clear button which is not visible on dark mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to Settings > Payments > Add payment method > Add Debit card
3. Search for an address (Billing address)
## Expected Result:  
Icon should be in light colour / or it should be hidden to match across all platform

## Actual Result: 
Icon is in dark colour / icon support only for iOS native

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/208148904-fa51d728-c648-4805-8c4a-f0e3a2a106b5.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/208148953-56c9d90f-712f-4ab5-ad2d-a929a0f74c2d.PNG" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671179953023449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I'm not aware that we ever had an icon/other button here. [Asked](https://expensify.slack.com/archives/C049HHMV9SM/p1671214895591029?thread_ts=1671179953.023449&cid=C049HHMV9SM) some clarifying questions in the thread, and closing for now as I don't think this is a bug. Will re-open if it turns out to be one!
