### ISSUE TITLE
Payment - The "Add payment method" button becomes visible for a while after clicking on "Bank Account"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Payment -> Add payment method -> Bank account/Debit card/PayPal.me

## Expected Result:
The "Add payment method" button should NOT be visible after clicking on "Bank account"

## Actual Result:
The "Add payment method" button becomes visible for a while after clicking on "Bank account"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android
- Mobile Web

**Version Number:** 1.2.41.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/208209791-a64995a3-03e1-4647-98f2-551e858e811b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
This feels similar to https://github.com/Expensify/App/issues/13258 and https://github.com/Expensify/App/issues/12781

**Comment by pecanoro** [comment]
I can't reproduce this on v1.2.42-1. @sophiepintoraetz Can you try and see if you get the glitch in the video when reproducing steps?

**Comment by sophiepintoraetz** [comment]
Yeah, I also can't reproduce this on v1.2.42-1, so I'mma close.

https://user-images.githubusercontent.com/42940078/208772677-bdf517c3-515f-4771-a686-e0f8a511d60e.mov
