### ISSUE TITLE
Chat - Skeleton view is not displayed above the IOU after request money, console error is showing with Report no longer exists.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13546

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in on an account that has a DM chat with many actions
3. Navigate to a chat that is not the aforementioned chat with many actions
4. Log out, so that you clear Onyx
5. Log in.
6. Make a request money from the person you're chatting with on the DM with many actions

## Expected Result:
Skeleton view is displayed above it after request money, and no console error

## Actual Result:
Skeleton view is not displayed above it after request money, console error

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.41.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/208214639-9f5fa752-d9f2-4977-83b3-e6cf63efb33f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Not overdue, I was OOO on Friday.

**Comment by yuwenmemon** [comment]
@kbecciv I don't believe you're following the test steps correctly - can you make sure the chat with many messages is **not** clicked on before you make the money request?

**Comment by kbecciv** [comment]
@yuwenmemon Just re-test the PR, it Pass

https://user-images.githubusercontent.com/93399543/208513094-339b6ebc-680f-4f80-9484-8e66d9d7f357.mp4

**Comment by yuwenmemon** [comment]
Thanks! Will close this out then.
