### ISSUE TITLE
Chat - After tap on "New Messages" button it doesn't scroll to a message that user marked as unread.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Navigate to a 1:1 conversation that has a large history of messages.
4. Scroll the conversation a little and tap hold/hover over a message from the other user and mark the message as "Unread"
5. Scroll further up the conversation and verify a "New Messages" button appears
6. Click/ tap on New Messages button
7. Verify you are scrolled to the message you marked as unread

## Expected Result:
Verify you are scrolled to the message you marked as unread

## Actual Result:
After tap on "New Messages" button it doesn't scroll to a message that user marked as unread.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1,2,41,1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/208209195-df150fbb-c44c-4ae9-9c2f-69b71a2f8859.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is failing steps in TestRail https://expensify.testrail.io/index.php?/tests/view/3010175

![image](https://user-images.githubusercontent.com/93399543/208210234-9da47eae-b563-42de-90a0-1a35c71426c3.png)

**Comment by srikarparsi** [comment]
@davidcardoza, I think we can close out this issue, the new messages indicator should scroll you down to the bottom of the chat, not to the unread message: https://docs.google.com/document/d/1gvPDhGTxdcu-0lQxvruQnQJfJBrAmSjHieKciucV8eo/edit#bookmark=id.o0dy91i0pwwo

**Comment by srikarparsi** [comment]
@kbecciv, could you update the steps in TestRail to reflect this?

**Comment by kbecciv** [comment]
Hi @isagoico Can you please update the steps in TestRail?

**Comment by davidcardoza** [comment]
Closing, sorry for the delay I was OOO.
