### ISSUE TITLE
App closes tapping device back button from the chat screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create new user
2. Create new workspace, user will get notification
3. kill the app and remove it from background
4. click on notification, it will navigate to chat screen
5. Press native back button

## Expected Result: 
should navigate to LHN

## Actual Result : 
App closed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208466657-f799adeb-1d5a-4558-8266-b3afa8bb650d.mp4

https://user-images.githubusercontent.com/43996225/208466809-c3eec380-7118-411c-8b19-bd7b14748758.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671280935011599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Closing this one. We're in the process of redesigning our navigation flows from the ground up and this will behavior will be more clear once we're done.
