### ISSUE TITLE
Spanish - Dropdown options are not translated until page refresh in `room settings` and `track distance` when language changed in another session

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Workspace - Reimburse Expenses
2. Observe Track Distance Unit values
3. Change language in another session
4. Observe Track Distance Unit values
5. Go to room settings
6. Observe the `Notify me about new changes` 
7. Repeat step 3
8. Check the `Notify me about new changes`

## Expected Result: 
Track Distance Unit dropdown values should be changed to new selected language

## Actual Result: 
Track Distance Unit dropdown values are not changing to new selected language

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/208438382-2757761a-1bdd-4a80-adb1-4d14e5fb672e.mov

https://user-images.githubusercontent.com/43996225/208438397-2766a8b5-9b3b-48ca-889f-32f4b112261e.mp4

https://user-images.githubusercontent.com/43996225/208440352-9d5ae039-158f-4449-bce1-f63771c2bea2.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671297275829189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117d024ede160bf14</li>
        <li>Upwork Job ID: 1605032733016178688</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I can work on this!

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/13704)

**Comment by trjExpensify** [comment]
Why didn't the title update on this? @eVoloshchak is due payment for the PR review, right?

**Comment by trjExpensify** [comment]
Offers have been sent to you both @eVoloshchak and @varshamb on [this job](https://www.upwork.com/jobs/~0117d024ede160bf14).

**Comment by trjExpensify** [comment]
Okay settled up: 

@eVoloshchak - $1k for the internal PR review
@varshamb - $250 for the bug report. 

Closing, thanks! 👍
