### ISSUE TITLE
Implement our headline font Expensify New Kansas

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13686]
We finally have font files for New Kansas, woo! So now let's implement it. 

For now, I believe the only weight we use in our brand will be "Medium" and "Medium Italic." I've packaged up both of those in .otf and .woff/.woff2 format here: [ExpensifyNewKansas.zip](https://github.com/Expensify/App/files/10259621/ExpensifyNewKansas.zip)

In terms of implementation, there are a few areas where we'll want to begin with this:

The Chats header in the top left:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2319350/208438179-6fbc8c00-a031-4ba4-9728-06ab54debbef.png">

Workspace editor card titles:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/2319350/208438219-a22051fb-4cca-403d-9912-3387b4a8fa7f.png">

Name in Settings:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/2319350/208438316-08761194-d583-4d0f-a545-7d4a38c143d9.png">

Big Number Pad:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/2319350/208438416-19bfb5f7-70ec-48ad-b234-366e470e0b5b.png">

And the in places like the full screen empty state, as well as some "Success" moments like when you add a bank account, etc (I am having a hard time digging up those screenies though!)

cc @grgia @Luke9389 @roryabraham in case any of you want to take this one for implementation. This is one of the last bits of implementing our core brand.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129e2192610c499ad</li>
        <li>Upwork Job ID: 1618076125316882432</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I can work on this!

**Comment by Luke9389** [comment]
Woohoo! So stoked to see this in action!

**Comment by Luke9389** [comment]
@luacmartins adding new fonts comes along with a few 'gotcha's, so let me know if you run into anything funky.

**Comment by shawnborton** [comment]
Woo, thanks Carlos!

**Comment by shawnborton** [comment]
1. For this one, I think we only want this on the LHN for now. 
2. I like using this again in DetailsPage as well as WorkspaceInitialPage. 
3. It looks something like this: <img width="1198" alt="image" src="https://user-images.githubusercontent.com/2319350/208564681-4e21f175-cd80-4b0a-831a-4750a5a45f6b.png">
4. In these success moments, they kind of look like the screen above however they have a generic "tada" image. Actually maybe if you search the code for `tada.svg` it will lead you to the right place? For these, we just want the headline immediately under the tada image to use the headline font. Similarly, there is a screen we use when we review account details. I think you can find examples of them [here actually](https://github.com/Expensify/App/issues/13151).

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/13714)

**Comment by luacmartins** [comment]
The PR has been on prod for 2 weeks. Adding the Bug label to get a BZ assigned and process payment!

**Comment by luacmartins** [comment]
@alexpensify could you help pay @parasharrajat for the review in [this PR](https://github.com/Expensify/App/pull/13714)? The regression period is over since that PR hit prod 2 weeks ago.

**Comment by alexpensify** [comment]
@parasharrajat - I've submitted an offer via Upwork. Please confirm you received it and I can close out this GH. Thanks!

**Comment by alexpensify** [comment]
@parasharrajat - checking in, I see the offer is still pending in Upwork. When you get a chance, can you please confirm you received it? Thanks!

**Comment by alexpensify** [comment]
Thanks! I've completed the payment process.
