### ISSUE TITLE
Button text is not in center

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > manage members
2. See the invite and remove button text

## Expected Result: 
The text is centered

## Actual Result : 
The text is not in the center

## Workaround:
visual

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.41-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="190" alt="207988825-3cf5b7ae-b2cf-4545-8810-a6501e4d23ea" src="https://user-images.githubusercontent.com/43996225/208416784-58a9351d-30c8-4eba-89dd-76d3623df22b.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/208416816-5000c2c9-15d4-44de-bd2a-cbe496ff01c9.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671218972279019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I'm not entirely sure what the best way is to solve this, but one idea would be to add one more pixel of padding to the bottom of the bottom and remove 1 pixel of padding from the top.

**Comment by luacmartins** [comment]
🤔 they seem to be aligned correctly in my browser
![Screenshot 2022-12-19 at 12 44 34 PM](https://user-images.githubusercontent.com/22219519/208507484-cf2741e8-ea8d-4a99-91f9-7ea568f9639c.png)

**Comment by shawnborton** [comment]
I think technically it is aligned perfectly in the middle, but maybe the line height of the font makes the letters appear to be shifted downwards by just a pixel? So that being said, this probably isn't so much a "bug" but I suppose we could modify this to give it the optical alignment we want.

**Comment by sonialiap** [comment]
Sounds like we have Shawn's blessing to edit the alignment by a pixel or two, passing to engineering

**Comment by marcochavezf** [comment]
I tested by adding 1px to the padding-bottom in the Button text and I think we can achieve the optical centered alignment. This is how it looks, what do you think @shawnborton?

<img width="660" alt="Screenshot 2022-12-21 at 12 51 30" src="https://user-images.githubusercontent.com/6829422/208981675-33c580ec-bbd7-4966-a58b-f70a0e810bd1.png">

**Comment by shawnborton** [comment]
I like it! How does it look for the other button sizes, like 52px (large) and 28px (small)? Curious if we need to make adjustments for those as well.

**Comment by marcochavezf** [comment]
I noticed the icons in the large buttons were a bit misaligned, so I added the 1px as padding-bottom too.

 Without 1px padding-bottom:

<img width="768" alt="Screenshot 2022-12-27 at 16 37 50" src="https://user-images.githubusercontent.com/6829422/209730241-8f80c692-daba-412d-abba-c2b5dfd6ee0d.png">

With 1px padding-bottom:

<img width="767" alt="Screenshot 2022-12-27 at 16 37 59" src="https://user-images.githubusercontent.com/6829422/209730685-25f530f3-d368-40d0-a132-881b9038a48e.png">

**Comment by shawnborton** [comment]
Ah interesting, why would the icons be misaligned without the 1px bump? Maybe you can share some code inspect screenshots?

**Comment by marcochavezf** [comment]
I think were misaligned because of the 1px bump in the Button text, but maybe that's my perspective 😄 but happy to leave them as is:

Without 1px padding-bottom (and with 1px in the Button text):

<img width="761" alt="Screenshot 2022-12-27 at 16 44 40" src="https://user-images.githubusercontent.com/6829422/209731520-8bba94c9-7ab4-4496-b41e-44ac236c72ba.png">

With 1px padding-bottom (and with 1px in the Button text):

<img width="760" alt="Screenshot 2022-12-27 at 16 47 52" src="https://user-images.githubusercontent.com/6829422/209731887-930e8a67-b82e-41c1-b692-202a683ed52d.png">

**Comment by marcochavezf** [comment]
And this is how the other buttons look like with the 1px padding-bottom in the Button text:

<img width="872" alt="Screenshot 2022-12-27 at 16 16 38" src="https://user-images.githubusercontent.com/6829422/209732370-bac8b8ab-5a74-4f54-8641-72fde93195d8.png">

<img width="880" alt="Screenshot 2022-12-27 at 16 16 27" src="https://user-images.githubusercontent.com/6829422/209732389-92a67dbd-a6e7-4a69-bd70-d8a43ad77bfa.png">

<img width="362" alt="Screenshot 2022-12-27 at 16 22 31" src="https://user-images.githubusercontent.com/6829422/209732420-d4a468bb-b4c0-4027-b90c-39138ca86cb9.png">

<img width="366" alt="Screenshot 2022-12-27 at 16 18 40" src="https://user-images.githubusercontent.com/6829422/209732457-02cb7cc7-66f8-4552-8974-e06a4856e215.png">

<img width="362" alt="Screenshot 2022-12-27 at 16 18 05" src="https://user-images.githubusercontent.com/6829422/209732461-eee801c4-1105-4885-b430-faff275c7e01.png">

<img width="367" alt="Screenshot 2022-12-27 at 16 18 17" src="https://user-images.githubusercontent.com/6829422/209732465-c67f8b37-c32b-4a4e-8630-6468dff58213.png">

**Comment by shawnborton** [comment]
I wonder, is there a way we can just give the button text a bottom padding of 1px? This way we don't have to mess with the icons at all?

**Comment by marcochavezf** [comment]
Yeap, I think we can only give the 1px padding button to the text button without impacting the icon. This is how the button with the icon looks (only 1px to the button text and no changes to the icon button style):

<img width="922" alt="Screenshot 2022-12-27 at 17 31 38" src="https://user-images.githubusercontent.com/6829422/209736436-2153e1ef-5e99-4b3c-aaad-324dbdade931.png">

<img width="825" alt="Screenshot 2022-12-27 at 17 32 16" src="https://user-images.githubusercontent.com/6829422/209736458-e8b729ca-5d67-4167-a1df-2ecf1add15a2.png">

**Comment by shawnborton** [comment]
Got it, that is very helpful! So then that makes me wonder, do we technically need to give 1px padding to both the top and bottom of the left icon so that we maintain perfect vertical centering for the icon? Otherwise my fear there is that it technically will sit a half pixel up or down too far?

**Comment by marcochavezf** [comment]
I think with 1px padding in both the top and the bottom looks a bit better.

<img width="923" alt="Screenshot 2022-12-27 at 17 52 38" src="https://user-images.githubusercontent.com/6829422/209737793-f464222f-9cfd-47ab-899f-3e91edcf0836.png">

<img width="737" alt="Screenshot 2022-12-27 at 17 50 18" src="https://user-images.githubusercontent.com/6829422/209737800-8a566814-1526-40d0-aa06-05762ea5d66f.png">

<img width="742" alt="Screenshot 2022-12-27 at 17 51 47" src="https://user-images.githubusercontent.com/6829422/209737801-aa0228f9-70d9-40ea-97e8-c598915bae07.png">

Also, I think since the icon has more space at the top (because of the sharp form of the bank icon) gives the impression that it's not perfect aligned: 

<img width="111" alt="Screenshot 2022-12-27 at 18 00 30" src="https://user-images.githubusercontent.com/6829422/209737915-e172d44d-82d5-496f-8e74-54dd267c0d04.png">

I'm going to look for another example with a more consistent shape icon.

**Comment by marcochavezf** [comment]
This is another example with 1px padding at both the top and the bottom:

<img width="923" alt="Screenshot 2022-12-27 at 18 04 22" src="https://user-images.githubusercontent.com/6829422/209738265-e779b472-313c-4368-98c9-31f89181e6b1.png">

<img width="879" alt="Screenshot 2022-12-27 at 18 05 00" src="https://user-images.githubusercontent.com/6829422/209738305-2311ea09-3df4-44dd-8304-473c7fe5d144.png">

<img width="871" alt="Screenshot 2022-12-27 at 18 06 32" src="https://user-images.githubusercontent.com/6829422/209738311-518df7ce-fc23-4e24-8c23-9f5754d22c6f.png">

**Comment by marcochavezf** [comment]
I added these changes to this [PR](https://github.com/Expensify/App/pull/13764) and I'm going to mark it as "Ready for review". We can address any additional changes there :)

**Comment by shawnborton** [comment]
Sounds good, thanks for exploring this one for me!

**Comment by marcochavezf** [comment]
Re-assigning the `Bug` label to handle the payment for [C+ review](https://github.com/Expensify/App/pull/13764#issuecomment-1385035461).

**Comment by marcochavezf** [comment]
Hi @slafortune, could you pay @sobitneupane for the [C+ PR review](https://github.com/Expensify/App/issues/13682#issuecomment-1385842704)? Thanks!

**Comment by marcochavezf** [comment]
Thanks @slafortune, yeah, closing it out

**Comment by slafortune** [comment]
I missed hiring and paying the reporting contributor for this!  Sorry about that @daraksha-dk thanks for bringing it up - I've sent you an invite to the job - https://www.upwork.com/ab/applicants/1626295120927571968/hires?filter=darak&page=1
