### ISSUE TITLE
[HOLD for payment 2023-01-20] Bank account - Error messages are not translated until page refresh  when language changed in another session

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Workspace - Connect Bank Account - Connect Manually
2. Without enteing any values click `Save & continue`
3. Change language in another session
4. Observer the error message 
5. go till Step 3 of 5 (Personal Information)
6. Press Save & Continue button, Observe error messages for input fields
7. Change language in another session
8. Observe error messages on Personal Information page (everything else changed to new selected language)

## Expected Result:
Error messages should be translated to Spanish

## Actual Result:
Remains in English until the page is refreshed and continued

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows / Chrome 

**Version Number:** 1.2.41-1
**Reproducible in staging?:**y
**Reproducible in production?:** Could not check
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208509424-99851116-836d-4cee-9d73-62bc6d29ed39.mov

https://user-images.githubusercontent.com/43996225/208509441-e8cf2aef-fe0b-40d2-9f86-fc4c70fb9009.mov

https://user-images.githubusercontent.com/43996225/208509481-da291ffe-51c0-4c56-85ec-f326cad9f348.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671296037291689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce00fb68a432cd90</li>
        <li>Upwork Job ID: 1616611494968844288</li>
        <li>Last Price Increase: 2023-01-21</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
Grabbing this one to work on it internally.

**Comment by marcochavezf** [comment]
[Draft PR](https://github.com/Expensify/App/pull/13810) up, I'm just going to add the screenshots for other platforms tomorrow.

**Comment by marcochavezf** [comment]
Re-applying the Bug label to handle the payment for bug reporting.

**Comment by marcochavezf** [comment]
Hi @mallenexpensify TL;DR: this issue was fixed internally, we'd just need to pay @varshamb for reporting the bug @sobitneupane for PR review.

**Comment by mallenexpensify** [comment]
Thanks @marcochavezf , def makes it easier.  Will pay Friday

**Comment by mallenexpensify** [comment]
@varshamb can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ce00fb68a432cd90

@0xmiroslav needed to add `Internal` to create the Upwork job which auto-assigned you, so I unassigned, sorry

**Comment by varshamb** [comment]
> can you please accept the job and reply here once you have?

Accepted.

**Comment by mallenexpensify** [comment]
@varshamb paid $250 for reporting, thanks! 
Closing

**Comment by sobitneupane** [comment]
@mallenexpensify I don't think I am paid for reviewing the [associated PR](https://github.com/Expensify/App/pull/13810) yet.

**Comment by mallenexpensify** [comment]
Sorry @sobitneupane can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01616c8119274bc2c0

I think this example of you not getting assigned is an edge case and should be fixed now.  If you notice other issues you're not assigned to, yet you're reviewing the PR, please post about in #contributor-plus and tag me.  For E/E repo issues, new E/App issues should be create for those now (just hit production)

**Comment by sobitneupane** [comment]
Thanks @mallenexpensify Applied for the job.

**Comment by mallenexpensify** [comment]
Paid @sobitneupane $1000 for C+ review of PR https://github.com/Expensify/App/pull/13810 , Thanks!
