### ISSUE TITLE
Fix typos around the codebase 

### ISSUE THREAD

**Issue by stavares843** [Expensify/App#13737]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Fix typos around the codebase

## Expected Result:
No typos

## Actual Result:
Typos are fixed

**Comment by roryabraham** [comment]
@stavares843 Please refer to our contributing guidelines and report this feature request in slack. Seems like a cool idea.

**Comment by stavares843** [comment]
I sent a email, waiting for the invite, i've added this meanwhile 😄 will do 🔨

**Comment by mountiny** [comment]
The PR is up and going to be merged.

**Comment by mallenexpensify** [comment]
@stavares843 did this bug also get reported in #expensify-bugs? If so, can you provide a link? Thx

**Comment by stavares843** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1671659915253559 - when it got suggested/reported
https://expensify.slack.com/archives/C01GTK53T8Q/p1672101301932599?thread_ts=1671659915.253559&cid=C01GTK53T8Q - when i added a PR with just the typos 


🔨

**Comment by mountiny** [comment]
@mallenexpensify I think we agreed this is a voluntarily contribution and to follow our processes I think we should not compensate for this change at this point. It might set a precedence we

**Comment by mallenexpensify** [comment]
I agree. Thanks @mountiny.  @stavares843 , please follow our bug reporting and PR submission process in [our CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

@stavares843 please apply to the job in Upwork
https://www.upwork.com/jobs/~01e837ad91ae1980a9

**Comment by stavares843** [comment]
thanks! 🔨

**Comment by mallenexpensify** [comment]
Hired @stavares843 , can you please accept the job and reply here once you have?

**Comment by stavares843** [comment]
accepted 🔨

**Comment by mallenexpensify** [comment]
Paid @stavares843 , closing 🔨
