### ISSUE TITLE
Deprecate unused silent notification logic

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#13732]
### Problem

We recently switched to only sending loud Airship notifications to mobile. However, we didn't remove the deprecated logic that was used to determine the `isSilentPush` param. As part of the Reliable Notifications project, we are going to finish this change by removing the unused logic. 

This is part of the [Notification Reliability project and DD](https://docs.google.com/document/d/1pT6pPHc42XfqskZXDp1LcFa-jx2okFKy6GFEyD8a42M/edit?usp=sharing) (see 'When a user receives a message in NewDot, we will send remote push notifications to all of their clients via Airship')

### Solution
- Remove the deprecated logic
- Add tests to confirm the changes don't cause a regression

**Comment by cristipaval** [comment]
Melvin should have closed this one. [PR](https://github.com/Expensify/Web-Expensify/pull/36014) is in production.
