### ISSUE TITLE
[HOLD #11768] Connect bank account manually page shows up on pressing "connect bank account"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > workspaces
2. Open a workspace
3. Click "connect bank account"
4. Choose "connect manually"
5. Press back button of your mobile
6. Tap on "connect bank account"

## Expected Result: 
You should see the page with plaid and connect manually option

## Actual Result: 
You get navigated to connect bank account manually page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.42-1
**Reproducible in staging?:** y
**Reproducible in production?:**y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208778384-f31017e8-6ed9-488b-8394-8e8e771ec87f.mov

https://user-images.githubusercontent.com/43996225/208778403-86e7cf3f-a3c7-43c7-af29-7ac3fd1c1083.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671526757244469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee5b46d51785a445</li>
        <li>Upwork Job ID: 1605345773006626816</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
The [App Navigation reboot](https://github.com/Expensify/App/issues/11768) project should address this. I'm gonna unassign myself since there's nothing to do now.

**Comment by davidcardoza** [comment]
@luacmartins should this issue be closed then?

**Comment by luacmartins** [comment]
Sure, we can close for now!
