### ISSUE TITLE
[HOLD for payment 2023-01-7] [Core Branding] Commas in LHN are white, but should be supporting text color

### ISSUE THREAD

**Issue by grgia** [Expensify/App#13747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open LHN, find a group chat. Commas are white.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/38015950/208785586-0336cdb4-ec4d-4330-87a5-d3d0b2e83c3b.png">

## Expected Result:
Commas should be supporting text color

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139ff73b2279a2334</li>
        <li>Upwork Job ID: 1605344934293299200</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Note: this issue is unlocked but it's internal so no proposals will be accepted at this time. Thanks!

**Comment by JmillsExpensify** [comment]
All good, I'll take it on for the payment. I'll also update the title.

**Comment by JmillsExpensify** [comment]
@aimane-chnaif Mind applying the Upwork job? I've just opened it for public proposals. Here's [the link](https://www.upwork.com/jobs/~0139ff73b2279a2334).

**Comment by JmillsExpensify** [comment]
Awesome, I just sent you a contract. Once you're back online and accept, I can issue payment so we can close this one out! Thanks for your patience on this one.

**Comment by JmillsExpensify** [comment]
Friendly reminder that you'll still need to accept the offer in Upwork so that I can issue payment. Thanks!

**Comment by JmillsExpensify** [comment]
Awesome, thank you! I've paid and closed the contract.
