### ISSUE TITLE
Payment : Empty payments page appears for a brief moment when navigating for the first time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to the app
2. Navigate to the payments page

## Expected Result: 
It should show loader or directly show the payment method list

## Actual Result: 
It shows empty list message for a moment and then renders the list

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows / Chrome 

**Version Number:** 1.2.42-1
**Reproducible in staging?:** y
**Reproducible in production?:**y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208780780-a98803f4-b35c-465d-a1e0-fd32c0d57c88.mov

https://user-images.githubusercontent.com/43996225/208780811-6d2200c3-fc8d-4723-a9f0-3ff6f279ad6a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671549500091539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Closing this since this behavior is expected. From our [design doc](https://docs.google.com/document/d/156RdYbrYQNJQcVRHlJ2DlUl6LRwTlNacR7B9JEb2KqI/edit#bookmark=id.c5i7k768un9o) the pattern to be used is none which means that there should be no loading spinners and we display stale data until new data is loaded.
