### ISSUE TITLE
IOS - Login- App is crashed when log out from one account and log in with different one

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account (5082211196/Feya86Katya)
3. Send the message to account beccivutest@gmail.com
4. Log out
5. Log in with account applausetester+0901abb@applause.expensifail.com/Feya86Katya

## Expected Result:
No crash when log in with account

## Actual Result:
App is crashed when log out from one account and log in with different one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS 

**Version Number:** 1.2.42.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/208794678-35e03a08-4267-4045-9d2f-f061efea5a59.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Fixed with https://github.com/Expensify/App/pull/13758
