### ISSUE TITLE
[HOLD for payment 2023-01-20] Attachment - Drag and drop of application files throws wrong error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account.
2. Choose any report, choose an Application file (Steam, slack,
3. Notice that the validation message says: "Attachment size must be greater than 240 bytes" even the size of attachment is 6MB.

## Expected Result: 
The attachment modal should show correct message.

## Actual Result:  
The attachment modal show incorrect message.

## Workaround:
Move the validation fileExtension on to the top of isValidFile inside AttachmentModal

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome  and Win chrome

**Version Number:** 1.2.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209005262-abd82e65-0e22-4df6-9ace-eee36f4357ca.mov

https://user-images.githubusercontent.com/43996225/209005283-bb40ca8c-5103-4106-b8af-848b4cbcfef0.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671512078960629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aecef138c9bc6ea3</li>
        <li>Upwork Job ID: 1612603999422697472</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
Will take a look at this one.

**Comment by muttmuure** [comment]
Are we sure this is replicable?

**Comment by yuwenmemon** [comment]
@muttmuure Yeah, it's replicable when drag and dropping, not when using the attachment picker:

https://user-images.githubusercontent.com/4741899/211430291-54699d5a-1d41-4cd0-92a9-89e479d75a12.mp4

**Comment by yuwenmemon** [comment]
Although I think this is just related to the OS's file provided when dragging and dropping vs using the image picker, since both flows hit the same logic: https://github.com/Expensify/App/blob/4e915a957e343b30e6a233d80735fe70a42037a4/src/components/AttachmentModal.js#L150-L185

I think a simple solution would be just to check for file type first in [this method](https://github.com/Expensify/App/blob/4e915a957e343b30e6a233d80735fe70a42037a4/src/components/AttachmentModal.js#L150-L185), since that would give us some consistency when we can't control what receive from the OS/browser (unless we can?)

**Comment by hungvu193** [comment]
I have a question, if my solution (Posted in Workaround of this issue) is also the solution that contributor used to fix this bug, should I rewarded? @yuwenmemon  😂

**Comment by mallenexpensify** [comment]
@muttmuure can you issue payment and complete the regression test steps today? Also address @hungvu193 's question above.  If needed, post in #contributor-plus to discuss, thanks.

**Comment by muttmuure** [comment]
Will get to this today - I have a lot of other issues to get through but I will make sure this is done before I log off.

**Comment by muttmuure** [comment]
OK getting to this now

**Comment by muttmuure** [comment]
Posted a buddy check here https://expensify.slack.com/archives/C01SKUP7QR0/p1674236286387249

**Comment by muttmuure** [comment]
I've invited @hungvu193 but @Santhosh-Sellavel isn't showing under our company hires

**Comment by muttmuure** [comment]
You're both invited to apply for the job. Thanks!

**Comment by Santhosh-Sellavel** [comment]
Applied for the job!

**Comment by muttmuure** [comment]
Everyone is paid. Great hustle everybody.
