### ISSUE TITLE
Search - Wrong search results are displayed when using `.,.` with any random text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13766]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed:

1. Open app
2. Tap on search bar on header
3. Type "hhhh.,." (Dot comma dot)

## Expected result: 
There should be no matching result

## Actual result: 
There are many search results

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="Search result" src="https://user-images.githubusercontent.com/43996225/209003440-2ba148f7-10c1-42d8-ac85-e2e4b1e25f3c.png">

https://user-images.githubusercontent.com/43996225/209003639-3fed3a41-e536-4ecc-8d20-88ebb47f3b36.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ekramkhan66
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671535351041409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
I am going to take a quick look at the code to see if there is something we can do about it or if this is some limitation on the search functionality.

**Comment by laurenreidexpensify** [comment]
Confirmed this is reproducible and write up is solid, but just waiting for @pecanoro's take on whether it's a bug or feature

**Comment by pecanoro** [comment]
Sorry for the delay due to the holidays, looking into it tomorrow morning!

**Comment by pecanoro** [comment]
Found the cause, this is [expected](https://github.com/Expensify/App/pull/2958) since we allow using commas to search for group chats so every time we introduce a comma, it will start a search for the next search term, in this case `.`. We return results that match one or more of the search terms.
