### ISSUE TITLE
Test build CI integration should post results in the PR even if one platform fails

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#13784]
### Problem

With the help of @staszekscp, we recently built a CI integration that will run test builds on all PRs, and can be manually dispatched by authorized actors.

When testing this out with https://github.com/Expensify/App/pull/13767, I noticed that [the build succeeded on all platforms except one](https://github.com/Expensify/App/actions/runs/3753136995/jobs/6376107555). However, upon completion there was no comment posted in the [PR](https://github.com/Expensify/App/pull/13767), so it's not easy (or at least not obvious how) to test the platforms that did succeed.

### Solution
Make the [final step that posts the comment](https://github.com/Expensify/App/blob/70027746fba80b6bc10220c3ef5c15ea2628282f/.github/workflows/testBuild.yml#L192-L240) run even if one or more platforms fail. A similar example can be seen [here](https://github.com/Expensify/App/blob/d8841f05813f3f7d82cd7ad4c41fe92a5bb2d560/.github/workflows/platformDeploy.yml#L358-L359), and the resulting comment should be tailored to clearly show for which platforms the build was successful and for which it was not. This is useful information to a PR author and also can help others proactively test the platforms for which the build _was_ successful.

**Comment by roryabraham** [comment]
Slack thread: https://github.com/Expensify/App/issues/13784

**Comment by staszekscp** [comment]
Sure, I'll take care of that!

**Comment by roryabraham** [comment]
PR is in review.

**Comment by roryabraham** [comment]
Just left another review on the PR.

**Comment by roryabraham** [comment]
This was done a couple weeks ago
