### ISSUE TITLE
[HOLD #219254] Notifications- No notification displayed after back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13694

## Action Performed:
1. Sign into the app as userA
2. Enable the Force offline mode under the Preferences
3. On a second client, sign in as userB
4. As userB, send a message to userA
5. As userA, you should not receive a notification as you are offline
6. As userA, disable the Force offline mode
7. As userA, you should then receive the notification

## Expected Result:
Notification is displayed after back online

## Actual Result:
Notification is not displayed after back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209221287-68602cda-fae4-4274-9fe8-e1fca7ba5e34.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I think we should put this on hold given the on-going notifications refactors. CC @Julesssss @arosiclair in case you disagree

**Comment by arosiclair** [comment]
There's just a misunderstanding here. The offline test for https://github.com/Expensify/App/pull/13694 is for Android only. On Web and Desktop, it's expected to not see notifications for messages you missed while offline. cc @kbecciv

**Comment by JmillsExpensify** [comment]
Funny enough, I just read the reliable notifications doc, so I now know this. Thanks for closing the loop in any case!
