### ISSUE TITLE
Mange members - Warning message can be visible and hidden when tapping on over the Workspace owner's

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13669 

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to Setting - Workspace - Manage Members
4. Tap on the Workspace owner's checkbox a lot of times

## Expected Result:
Warning message should be visible when tap on it

## Actual Result:
Warning message can be visible and hidden when tapping on over the Workspace owner's checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android app
- [ ] iOS app

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209239268-fad41c9b-ab6f-44cb-91f8-34f22f8801bd.MP4

https://user-images.githubusercontent.com/93399543/209239273-187a7bbd-7bd3-4e54-846c-dbd7c9222fcb.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@arielgreen this issue is now 3 weeks old. There is one more week left before this issue <a href='https://stackoverflowteams.com/c/expensify/questions/15233/15234#15234'>breaks WAQ</a> and will need to go internal. What needs to happen to get a PR in review this week? Please create a thread in #expensify-open-source to discuss. Thanks!

**Comment by arielgreen** [comment]
Unable to reproduce.

Steps followed:
1. Logged in
2. Created a new workspace
3. Settings > Manage Members
4. Tapped on my own checkbox several times.

Warning pops up, as soon as it disappears it pops up again upon clicking my checkbox. 

cc @kbecciv
