### ISSUE TITLE
Handle HEIC images in web and desktop 

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#13806]
# Problem
Coming from this [slack discussion ](https://expensify.slack.com/archives/C02NK2DQWUX/p1671690637852589?thread_ts=1670874971.108159&cid=C02NK2DQWUX), we don't currently handle HEIC images on web and desktop in NewDot. This is a common file type for files generated on apple devices, so not supporting these is not an ideal user experience, given many NewDot users are on apple devices. 

# Solution 
Add support for HEIC in desktop and web. Based on the Slack discussion, it sounds like the way to go is converting to jpeg so we can display a preview of the files before upload.

**Comment by youssef-lr** [comment]
Hey @joekaufmanexpensify - I'll be closing this in favor of https://github.com/Expensify/App/issues/12531 which tackles the same issue.

**Comment by joekaufmanexpensify** [comment]
sounds good!
