### ISSUE TITLE
[$1000] Android-Change password - The error message about the wrong old password is not fully displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login with any account
3. Go to Settings -> Security -> Change password
4. Enter incorrect information in the "Current password" field
5. Enter the correct information in the "New Password" field
6. Press "Save" button

## Expected Result:
The error message about the wrong old password is displayed in full

## Actual Result:
The error message about the wrong old password is not fully displayed, you have to scroll the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209365594-25dd4320-5d89-46d0-acbd-5b22e6a3e85b.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e4c91b24e8417f7</li>
        <li>Upwork Job ID: 1606325379899723776</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
I can say that's we can hide the keyboard when user press Save, so it will fully show the error message :D

**Comment by priyeshshah11** [comment]
**Proposal**

Hide the keyboard on submit to display all the error messages.

```diff
submit() {
+      Keyboard.dismiss();
        if (!this.validate()) {
            return;
        }
        User.updatePassword(this.state.currentPassword, this.state.newPassword);
    }
```

**Comment by priyeshshah11** [comment]
@hungvu193 sorry, saw your update after posting.

**Comment by hungvu193** [comment]
No worries :) @priyeshshah11

**Comment by thesahindia** [comment]
The page needs a Form refactor but since this page won't be needed after #passwordless, we should just close.

**Comment by abdulrahuman5196** [comment]
Root cause:
Page size is not enough to show error alert in case of small phone sizes
But the alert text is properly shown in case of current generation of medium phone sizes or large phone sizes
![Screenshot_20221223-230029](https://user-images.githubusercontent.com/46707890/209390545-771f9872-9000-48d7-866d-3429d686d32d.png)


Proposal:
Change the showing of alert design by showing native OS alerts or some new design. Might need design inputs for changing the alert style.

**Comment by puneetlath** [comment]
Those are great points @thesahindia. Thanks for pointing that out. Sorry for the false alarm everyone!

**Comment by tamoor08** [comment]
We can use the auto scroll to bottom or we can use dismiss the keyboard after pressing saving button. This is not a big problem to solve.

**Comment by appnwebdeveloper** [comment]
### Proposal ###

I am **Vinay Chudasama**, I will use Keyboard hide On the save button as well as I will disable the auto scroll for large screens. The label should be adjusted above by removing some white space.

Another option is that just instead of the label shows the native or custom alert.

**Comment by bulatgab** [comment]
### Proposal (if the issue ever reopens)
Alternative to hiding the keyboard - scrolling the ScrollView to the end.
```
<ScrollView
  ref={el => this.scrollViewRef = el}
  ...
    <Text
      ref={el => el && this.scrollViewRef.scrollToEnd({animated: true})}
      ...
    >
</ScrollView>
```
The ref callback is called when the Text component gets mounted/unmounted.
