### ISSUE TITLE
C+ Internal PR testing and review payment

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#13814]
We would like to handle a payment $1000 for the internal PR review and testing of this PR https://github.com/Expensify/App/pull/12626

The C+ to pay is @sobitneupane

**Comment by mountiny** [comment]
Unlocked so @sobitneupane can comment, @flaviadefaria thank you very much for handling this.

**Comment by flaviadefaria** [comment]
@sobitneupane contract sent!

**Comment by flaviadefaria** [comment]
Contract paid!
