### ISSUE TITLE
App window flashes at App launch on Android

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#13815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Kill the App
2. Launch the App
3. Watch the splash screen

## Expected Result:
Splash screen should have the dark background

## Actual Result:
Splash screen flashes, from white to dark background

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671685986662779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b593296a186bb13a</li>
        <li>Upwork Job ID: 1606260881665060864</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
@Julesssss isn't this a duplicate report of what we encountered while solving https://github.com/Expensify/App/issues/8236? Not going to triage until we align on whether this is a bug or not.

**Comment by cristipaval** [comment]
I and Jason had a 1:1 call and we concluded that this is a different issue than what the team discussed before. As far as I understood, the previous issue was related to the status bar color, but this one is related to the App window background. Here is a screen recording with the current issue:

https://user-images.githubusercontent.com/18078393/209392752-83dc82a4-5542-48f2-90b8-7b2c52183af4.mp4

As you can see, after killing the App and opening it again, the App screen is white and then dark.

@Julesssss Related to the status bar and also navigation bar. Have we considered to make the App render behind them and add a padding  according to the bars height, to make sure that the App content does not overlap with the bars content? I guess the challenge is when the screen background changes, we have to delegate to the native code to update the activity background color as well, but maybe we could do some brainstorming and find a robust and scalable solution to support this. It would be a great achievement if we raise the Android App ui to the level of the iOS App.

**Comment by JmillsExpensify** [comment]
Super productive call, thank you! Yeah it seems like we still have a couple of improvements left to make when it comes to Android – whether it's the status bar on app load, the background color, the app icon, as well as the bottom border where the swipe action happens. All of those seem to either flash white or are permanently white, so it's inconsistent with the overall branding and our official colors. I agree this is a good one to keep internal, at least until we have a better sense of scope and next steps.

**Comment by JmillsExpensify** [comment]
@cristipaval is out for this week, but he has a good plan for the path forward and this bug is still young, so I'm going to keep him assigned.

**Comment by cristipaval** [comment]
Waiting for @Julesssss, he had some health emergencies, he'll be online tomorrow.

One thing I want to put down here, is that we're about to add the ability for the user to choose between light/dark themes. We need to find a solution for the App window to instantly set the background according to the user preference.

**Comment by Julesssss** [comment]
> I guess the challenge is when the screen background changes, we have to delegate to the native code to update the activity background color as well, but maybe we could do some brainstorming and find a robust and scalable solution to support this. It would be a great achievement if we raise the Android App ui to the level of the iOS App.

Yeah, I agee and [have come up with many solutions](https://github.com/Expensify/App/issues/13001) but unfortunately none of them are ideal. Will be looking into this again soon.

**Comment by Julesssss** [comment]
Interestingly, I'm not seeing this issue on Android 13. I'm on app version `1.2.48-2` and I see the dark window background no matter how the app is opened (from background, fresh open after kill, fresh open after back button press):

https://user-images.githubusercontent.com/10736861/210761018-4c16aed9-d957-469a-9683-5cbb034b484b.mp4

Did I miss something? Else I wonder if this is a device-specific issue.

**Comment by cristipaval** [comment]
Could you switch the theme in your phone settings? Set light theme if possible and try again. I wonder if this is related to the theme of the phone settings.

**Comment by JmillsExpensify** [comment]
Closing this issue per [this Slack convo](https://expensify.slack.com/archives/C049HHMV9SM/p1671685986662779). We're handling it elsewhere.
