### ISSUE TITLE
App is closed when `delete` button is long pressed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. Insert emoji from google keyboard
3. Press `back delete` button

## Expected Result:
Emoji should be removed, and the app should not exit

## Actual Result:
App is exited

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - POCO X3

**Version Number:** 1.2.40-3
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209336256-ce4c1f92-0697-4816-9ad4-f6b756753a6d.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ekramkhan66
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671535081000989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment]
I can't seem to reproduce this one, I attempted on multiple android devices via Browser stack. Can you post in Slack to see if others might be able to reproduce this? Otherwise let's close this.
