### ISSUE TITLE
workspace old name appears for few seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create a new user
2. create anew workspace
3. edit the workspace name
4. check  workspace name in LHN

## Expected Result:
should show workspace new name

## Actual Result:
shows workspace old name for few seconds

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.2.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209566401-934a7a96-ffbd-4bae-ab1d-57af54bd7699.mov

https://user-images.githubusercontent.com/43996225/209566427-ffe347f4-bbc7-4e79-970e-c19a90d06fa2.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672063238228179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176d0c4d41eed4fb7</li>
        <li>Upwork Job ID: 1612494079243243520</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
Will take a look at this one!

**Comment by Christinadobrzyn** [comment]
I'm not quite sure I 100% understand what we're expecting to see here. I can see the workspace name changes for the #admins and #annouce rooms in the videos (I can't seem to recreate this for some reason). 

Where should the workspace name show, otherwise? @kavimuru Can you please give more specific steps to recreate it? 

 Maybe this GH is related? https://github.com/Expensify/App/issues/14120

@JmillsExpensify left a comment in the Slack thread about this. It might be related to a loading delay @tgolen could you confirm if there's another GH/job already open for this?

**Comment by tgolen** [comment]
Oh wow, that's weird. I see it happening. I think this has to do with the length of time it takes for the create workspace API takes to load. There was a [slack thread here](https://expensify.slack.com/archives/C03TQ48KC/p1671463537981269) where @MariaHCD and I were talking about this exact problem and I think she is looking into it and we could probably close this issue as a duplicate to https://github.com/Expensify/Expensify/issues/246016

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @tgolen! I closed the Upwork job.
