### ISSUE TITLE
[HOLD for payment 2023-01-09] iOS - No green border for date picker field when the field is selected

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any page that has DatePicker (ie Connect Bank Account Manually)
3. Focus on any field then focus to the DatePicker
4. Notice that DatePicker doesn't have the border when it's being selected

## Expected Result: 
Date Picker should have the green border

## Actual Result : 
DatePicker doesn't have the border when it's being selected

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Could not check
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209567981-54c0f677-0b92-4b0e-a853-c5c1e4df16ba.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671803870095339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/209568003-66b221cc-b2ef-49c8-8b61-32ba094adc04.MP4

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01040bf570bfa437b1</li>
        <li>Upwork Job ID: 1607686515628589056</li>
        <li>Last Price Increase: 2022-12-27</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
Also happening on Android. Not iOS-exclusive

**Comment by bfitzexpensify** [comment]
Reporting bonus paid out. I believe we're all done here so I'll close this out
