### ISSUE TITLE
Undo fork from #11463

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#13846]
We're forking a fork, which isn't ideal and we should undo and point upstream as soon as the PR mentioned in the HOLD is merged. I'm going to start this off as a monthly and we can re-assess from there. 

Related issue: https://github.com/Expensify/App/issues/11463

**Comment by JmillsExpensify** [comment]
Still on hold and probably will be for quite some time.

**Comment by JmillsExpensify** [comment]
Taking this issue off hold per [this news](https://github.com/Expensify/App/issues/11463#issuecomment-1405122722).

**Comment by flodnv** [comment]
So what do I need to do? 😂 It feels like the only good path forward is to wait for a release and merge that rnw release back into our fork @roryabraham ?

**Comment by flodnv** [comment]
Maybe this PR resolves this issue? 😂 https://github.com/Expensify/react-native-web/pull/14

**Comment by roryabraham** [comment]
To me it doesn't look like [these commits](https://github.com/necolas/react-native-web/pull/2438/commits) are included in https://github.com/Expensify/react-native-web/pull/14.

However, I'm overall I'm confused by this issue because I suspect there are a number of custom changes we have in our react-native-web fork, and we can't go back to using the upstream until all of those changes are merged and released upstream. For example, https://github.com/Expensify/react-native-web/pull/11 was just merged a few days ago and IIRC the maintainer of react-native-web had no plans to review the upstream PR until at least after RNW 0.19 is released.

**Comment by flodnv** [comment]
>To me it doesn't look like [these commits](https://github.com/necolas/react-native-web/pull/2438/commits) are included in https://github.com/Expensify/react-native-web/pull/14.

Yeah he closed the PR with another commit which is indeed included in the merge back: https://github.com/necolas/react-native-web/commit/ccfd936f274ca2105745f9edbbb4aad80725e181

Yes, I have also been confused by this issue since @JmillsExpensify created it. As it stands, I think we can close it?

**Comment by Beamanator** [comment]
FYI the upstream PR for (https://github.com/Expensify/react-native-web/pull/11) is (https://github.com/necolas/react-native-web/pull/2442)
- It looks like the maintainer is actually asking about updates so maybe they're interested in merging this change upstream soon 👍

**Comment by flodnv** [comment]
@Beamanator sorry, what does this have to do with this issue? I am so lost here 😂

**Comment by JmillsExpensify** [comment]
Per this SO, we got here through this process:

> Create an E/App issue to:

> Link the upstream PR while you wait for it to be merged and released: Place the issue on Weekly and prefix the title with: [Hold - Upstream <libraryName> -#IssueID]

> Update the fork and resolve conflicts such that the PR is no longer included in the diff between the fork and the upstream

> If this was the only or last PR in the fork, then update E/App to use the upstream dependency instead of the fork.

> If there are still outstanding changes in the fork that have not been integrated into the upstream, then update E/App to use the updated version of the fork with the PR integrated upstream

So specifically for the last item, we created this issue, there were outstanding changes in our fork that were not integrated into the upstream. If our fork and the upstream are aligned now, then yes we can close this issue.

**Comment by roryabraham** [comment]
> If our fork and the upstream are aligned now

Not yet.

**Comment by JmillsExpensify** [comment]
Ok cool, so then are we clear on why this issue exists?

**Comment by roryabraham** [comment]
Brought this up in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1675204378344359

**Comment by flodnv** [comment]
So I think we can close this given https://github.com/Expensify/react-native-web/pull/14 resolves the forking. Please reopen if I'm mistaken.
