### ISSUE TITLE
Profile - The error text does not change when the data is changed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Profile->Display Name
4. Change your name to include a comma (We see an error about the comma)
6. Added semicolon to the name

## Expected Result:
The error message changes to a message to remove the comma

## Actual Result:
The error message doesn't change

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209738369-4410915f-a3d2-4bc8-941f-bee6a0712590.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
This isn't reproducible on staging web for me - 

![2022-12-28_13-40-12 (1)](https://user-images.githubusercontent.com/62073721/209821066-e7c0439a-e8e3-4fd6-8c3a-cb64ea4676a0.gif)

Closing
