### ISSUE TITLE
Web - Chat - Copied text looks compressed after send it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Copy multiple messages
5. Paste in to compose box and send it

## Expected Result:
Messages sent without modification.

## Actual Result:
Copied text looks compressed after send it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows / Chrome 

**Version Number:** 1.2.44.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209755265-4cd7f841-a9e7-4685-b882-938415d4de9b.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9131e2464702220</li>
        <li>Upwork Job ID: 1608218224152158208</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I'm unable to test this bug given that it's Windows Chrome unfortunately. Going to get a second opinion internally before triaging.

**Comment by AndrewGable** [comment]
Can you try to test via BrowserStack?

**Comment by JmillsExpensify** [comment]
Oh I didn't realize they do desktop testing as well. My b!

**Comment by AndrewGable** [comment]
I'm also not sure this is a bug. Is the expected behavior of copying multiple messages to leave a newline between each message?

**Comment by JmillsExpensify** [comment]
Great question. Like obviously if they are unique messages, then we add our own padding/spacing between each unique message. But this is just copying messages and then sending them as one.

**Comment by JmillsExpensify** [comment]
Just tested Slack. They have the same behavior as above, so I think you're right, we don't need to spend anymore time on this. Now if this is for some reason happening just on Windows and not other platforms, we can re-open, but that's not clear at the moment either.
