### ISSUE TITLE
mWeb/Safari -Workspace- Welcome message is not displayed in the announce room from the newly created workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with expensifail account
3. Create new workspace
4. Open #announce room this new created workspace

## Expected Result:
Welcome message should be displayed in the announcement room from the newly created workspace

## Actual Result:
Welcome message is not displayed in the announce room from the newly created workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209754825-1ddeb138-3a58-4662-9e5c-7754fef77791.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01734e585066aa3446</li>
        <li>Upwork Job ID: 1610437128020480000</li>
        <li>Last Price Increase: 2023-01-04</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Christina is OOO

**Comment by adelekennedy** [comment]
@yuwenmemon do you want this to be an internal issue?

**Comment by yuwenmemon** [comment]
@adelekennedy Yep! I've added the tag as well.

**Comment by adelekennedy** [comment]
ty! I'll unassign myself

**Comment by yuwenmemon** [comment]
Tried to reproduce on both production and dev, but both times was unable to. Closing this out.
