### ISSUE TITLE
Chat - Emoji :hugging_face: not displaying correctly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Start writing a message and use :hugging_face: in your message

## Expected Result:
Emoji must be displayed in the text message.

## Actual Result:
There is no emoji in the message, text only.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209825052-d5ffa007-13cc-4d8e-9f66-88c4e5167615.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
There is another emoji (⁦ ⁦: unicorn_face: ⁦:unicorn_face: ) does not display correctly.

https://user-images.githubusercontent.com/93399543/210285901-6b7d4a69-f57a-47c1-8eda-5ef3eb6f4b09.mp4

**Comment by jasperhuangg** [comment]
It seems we actually do support these emojis, just under a different name:

[unicorn](https://github.com/Expensify/App/blob/2f1c97dcef7284f2bd43c6020d1dd06f92d9becc/assets/emojis.js#L7139-L7144)

[hugging](https://github.com/Expensify/App/blob/jasper-fixLoginPagePicker/assets/emojis.js#L384-L393)

Therefore I think we can close this out, the user can still access those emojis, actually with simpler names.
