### ISSUE TITLE
[HOLD for payment 2023-01-13] Backtick only message is not allowed when sending a message (but allowed when editing)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any chat
3. Write only ` and/or whitespace
4. Try to send it

## Expected Result:
User should be able to send only backticks as a message

## Actual Result:
Can't send backticks as a message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209836511-edbe58c5-e804-4d51-a0b5-b815b6951d53.mp4

https://user-images.githubusercontent.com/43996225/209836533-2c10c020-9bfb-465d-a9ba-3e2a92cde332.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671730547465899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb6a160bee7f24a5</li>
        <li>Upwork Job ID: 1610022717350330368</li>
        <li>Last Price Increase: 2023-01-02</li>
    </ul>
</details>

**Comment by tgolen** [comment]
I'll grab this and fix it

**Comment by tgolen** [comment]
I found that this is expected behavior that was put in place to fix this problem: https://github.com/Expensify/App/issues/7971 but I do think we should allow any content for messages and I would like to look into why the backend struggles with messages that only contain backticks.

**Comment by tgolen** [comment]
I found that allowing backticks seems to work just fine with the backend:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1228807/210279201-7d207cc3-5835-44aa-92a9-11e98ce7a4b9.png">

The messages remain after switching chats and even after refreshing

**Comment by tgolen** [comment]
```

**Comment by sakluger** [comment]
@tgolen you mentioned that you created a PR to fix this, but I don't see it linked to the issue. Mind commenting with the PR link?

**Comment by tgolen** [comment]
Strange, GH doesn't seem to be linking things properly. The PR is here: https://github.com/Expensify/App/pull/13941

**Comment by mountiny** [comment]
Unlocked this.

> Strange, GH doesn't seem to be linking things properly.

This is an issue we are trying to fix somehow, when locked, not even the github linking works and worst, it does not backgil retrospectively

**Comment by sakluger** [comment]
@daraksha-dk and @Santhosh-Sellavel I sent you both offers through Upwork, please accept when you have a chance, thanks!

**Comment by sakluger** [comment]
@daraksha-dk I paid you the reporting bonus, thanks!

@Santhosh-Sellavel thanks for accepting the offer in Upwork, the PR was just deployed to production today so payment will be next Friday as long as there are no regressions.

**Comment by sakluger** [comment]
I paid everyone, ended the contracts, and closed the Upwork post. Thanks everyone!
