### ISSUE TITLE
[HOLD for payment 2023-02-08] Amount and email address seems too close

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any chat (choose a chat with long name)
3. Choose Request Money
4. Enter a large amount
5. Click "Next"
6. You'll notice the amount might be too close to the email
7. You might need to change the currency to FCFA in some cases

## Expected Result:
Some padding/margin should be between these two

## Actual Result:
It's too close to each other

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome

**Version Number:** 1.2.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/209847305-38229cb9-28f9-4432-b90d-544b39b5af37.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/209847307-8e9623f7-61fb-44d8-acc2-e1eb0ddb16b3.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/43996225/209847668-3e334780-e2cc-4a3e-bb08-5cdb11c04eb7.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672076984952519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b4af6adbfc61e40</li>
        <li>Upwork Job ID: 1608409698728001536</li>
        <li>Last Price Increase: 2022-12-29</li>
    </ul>
</details>

**Comment by sketchydroide** [comment]
yeah that seems to close, should be an easy fix though.
@mallenexpensify let me know if you can replicate, if you don't have time I'll try myself tomorrow

**Comment by mallenexpensify** [comment]
My concern is that, for CA $, the amount has to be over $10MM and I'm unsure that'll ever happen.   @sketchydroide @kavimuru and @daraksha-dk do any of you know of currencies where 8 digits or more are used regularly?  (unlocked issue to allow for comments)

**Comment by Pujan92** [comment]
> My concern is that, for CA $, the amount has to be over $10MM and I'm unsure that'll ever happen. @sketchydroide @kavimuru and @daraksha-dk do any of you know of currencies where 8 digits or more are used regularly? (unlocked issue to allow for comments)

It will happen for single digit too, reason - there is not any margin set between the participant name and the amount(descriptive text). So if the email id is long then it will persist.

**Comment by sketchydroide** [comment]
yeah honestly I don't know why they are on top of each other, makes little sense, there is so much space on that screen
I don't see a point on making the email crop, we could have the value on the next line and fix the issue and make this look less crowded
@Expensify/design I know you are maybe away and busy after moving, but what do you think?

We can also post this on slack to have more people chime in

**Comment by sketchydroide** [comment]
ohh, that is new, not sure why we have this here now

**Comment by thesahindia** [comment]
I think it's for the PR review?

**Comment by shawnborton** [comment]
cc @JmillsExpensify

**Comment by sketchydroide** [comment]
ok if this change is part of N7, then it makes sense to just add the 8px padding
I'll get to that later, also giving some time for Jason to answer

**Comment by JmillsExpensify** [comment]
Oh great point @shawnborton! I can tackle those in the midst of updating the Manual Request mocks, so yeah sounds good to go with the 8px solution for now.

**Comment by thesahindia** [comment]
@sketchydroide, I just confirmed that it is working correctly, the C+ will be assigned on adding internal label. Feel free to add me again if this needs a C+

**Comment by mallenexpensify** [comment]
Since this is likely going to be obsolete soon, I'm unassigned @sketchydroide , kept myself assigned, bumped to Monthly and added [HOLD] to title.  @JmillsExpensify , let me know if this funks with tracking of WAQ issues or any others, we can close if so. 

@daraksha-dk this likely won't be eligible for the reporting bonus cuz we're already planning on changing the layout which will render the bug obsolete.

**Comment by sketchydroide** [comment]
Happy to have this dropped if this going to be changed soon, but I'm not sure how soon this would be though, and this would be a pretty small change, likely a one commit PR.
I can also understand that payments might no be release outside of the beta before N7, so this bug might not really be relevant.

**Comment by JmillsExpensify** [comment]
I actually think we should move forward with this now.

**Comment by mallenexpensify** [comment]
Took off hold and bumped to Daily.  @sketchydroide want to work on this? And/or.. can this be External?

**Comment by sketchydroide** [comment]
I can work on it next week, but this should be a relatively small PR anyway so I'll do it

**Comment by mallenexpensify** [comment]
Added you as assignee too @sketchydroide

**Comment by sketchydroide** [comment]
oh thanks, sorry so many things happening that I forgot about this, will work on it soon

**Comment by sketchydroide** [comment]
@mallenexpensify We need to pay @daraksha-dk for bug reporting and @rushatgabhane for PR review
This has been more than a week so. I think we are good

**Comment by mallenexpensify** [comment]
Thanks @sketchydroide,  @daraksha-dk and @rushatgabhane , can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01961115ec35ace4f3

**Comment by mallenexpensify** [comment]
Checking with #qa to see if this better to be added to Testing Guidelines - Design or TestRail 
https://expensify.slack.com/archives/C9YU7BX5M/p1676075210839369

**Comment by mallenexpensify** [comment]
Paid @rushatgabhane $1000 for C+ and @daraksha-dk $250 for reporting.
Double checking on regression test steps 
https://expensify.slack.com/archives/C9YU7BX5M/p1676075210839369

**Comment by mallenexpensify** [comment]
Got [confirmation in #QA](https://expensify.slack.com/archives/C9YU7BX5M/p1676332518372379?thread_ts=1676075210.839369&cid=C9YU7BX5M) to add to the testing guidelines and have done so [here](https://docs.google.com/document/d/1UaWlcieiwLnsKfeKw7iwLF7vgYRmdw_-K8OcY5aPBRU/edit#heading=h.r44oknvea8fx)
