### ISSUE TITLE
[$1000] mWeb/safari -Reimburse expenses-  Drop for Unit field down doesn't work consistently 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings
2. Go to the "Reimburse expenses" setting
3. Under "Track Distance", tap on the input for "Unit" ( you will get the popup under the Unit field)
4. Tap on Rate and than tap on Unit ( you will get the popup above the Unit field)

## Expected Result:
Drop for Unit field down works consistently 

## Actual Result:
Drop for Unit field down doesn't work consistently 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.45.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209881770-b6a47beb-d465-4496-b27d-f2f02ead9183.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7a0075be57920b5</li>
        <li>Upwork Job ID: 1610401681081532416</li>
        <li>Last Price Increase: 2023-01-03</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Hmm, interesting. I suppose this is technically a bug, though I wonder if it's even solvable. Perhaps there is a CSS solution to this. Opening up to external to see if anyone has ideas.

**Comment by syedsaroshfarrukhdot** [comment]
@puneetlath Not able to reproduce by following mentioned steps is there I am missing any steps for reproduction ? 

Steps followed for reproduction are as below:-

1.  Go to Workspace settings
2. Go to the "Reimburse expenses" setting
3. Under "Track Distance", tap on the input for "Unit" ( you will get the popup under the Unit field)
4. Tap on Rate and than tap on Unit ( you will get the popup above the Unit field)


Development :-
https://user-images.githubusercontent.com/81307212/210452577-c47363a2-61d4-4cd2-a4ca-b25001fa7858.mov

Staging :- 

https://user-images.githubusercontent.com/81307212/210452813-13e3821f-b386-4d02-8f3e-a0599cc9a2bf.mov

**Comment by puneetlath** [comment]
@syedsaroshfarrukhdot it happens because of the on-screen keyboard. Looks like you don't have that in your emulator, which is why you aren't seeing it.

**Comment by bernhardoj** [comment]
React native picker uses `<select>` tag to show the picker. We can easily reproduce on any web that has picker and a text field, for example here https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select. I don't think this one is solvable.

**Comment by puneetlath** [comment]
Yes, I agree. I see this as an issue with how <select> works in mobile safari rather than a bug in our platform. I'm going to go ahead and close. Thanks!
