### ISSUE TITLE
Incorrect tooltip position after resize window

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open home page and check tooltip on LHN above users.
2. Resize window to switch on small screen UI (must hide sidebar).
3. Now check tooltip on same place. event after switch to full screen showing on incorrect position. Until page refresh.

## Expected Result:
Tooltip should not impact by size of window.

## Actual Result:
Tooltip position disturb after window resizing.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2. 45-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209897313-995e2201-830e-4cd1-8b41-41e71384040b.mp4

https://user-images.githubusercontent.com/43996225/209897562-31291f46-fc99-41cf-96b1-eec4e12b1375.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672237666860129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Not sure this is a bug - Asking for a buddy check here https://expensify.slack.com/archives/C049HHMV9SM/p1672439534659339?thread_ts=1672237666.860129&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment]
Closing as this doesn't seem that far away from expected behavior and is a low value fix IMO - [Discussion here](https://expensify.slack.com/archives/C049HHMV9SM/p1672439534659339?thread_ts=1672237666.860129&cid=C049HHMV9SM)

**Comment by JmillsExpensify** [comment]
We don't plan on prioritizing browser resizing anytime soon. We're more focused on migrating our existing customers from our old platform to our new platform, which will minimally take the remainder of this year. We can open up this issue in the future if/when this becomes a priority.
