### ISSUE TITLE
Web - LHN content is getting copied 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any chat (easier to repro when the timezone is different)
3. Try to select the last message and hold the cursor down and move slightly towards the LHN
4. The placeholder “Write Something” will also get selected
5. Paste the message
6. You’ll see LHN content pasted

## Expected Result: 
User should not be able to copy LHN content (and the placeholder of composer?)

## Actual Result : 
User is able to copy LHN content

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209894961-43dafcff-9283-4a5e-a7de-e97bcdcf6c05.mp4

https://user-images.githubusercontent.com/43996225/209894967-6a2da404-de9f-4bf1-8afe-75d1feedfc82.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672222408772579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I am unable to reproduce and just don't think this is a bug, the user is copying and pasting something they shouldn't be so they should just highlight what they want to copy and paste.
