### ISSUE TITLE
[Hold for payment 2023-01-20] [$2000] White border on right and bottom of preview image while sending the image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13881]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Attach any image

## Expected Result:
Image should be previewed and right side border should only be visible if scrolling is necessary

## Actual Result:
Image is previewed but white border appears on right and on bottom of the preview image

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] Windows / Chrome

**Version Number:** 1.2.45-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209892993-d55c0d11-ba2a-4161-baa2-4b2e4eb57203.mov

https://user-images.githubusercontent.com/43996225/209893038-4178abee-6e1f-47dc-a653-3ed55cb5245a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672073916214749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3caf73e33e6e0de</li>
        <li>Upwork Job ID: 1608957370249646080</li>
        <li>Last Price Increase: 2023-01-06</li>
    </ul>
</details>

**Comment by allroundexperts** [comment]
Not reproducible.

**Comment by priyeshshah11** [comment]
# Proposal

## Problem
The View inside ImageView is using overflowScroll which makes the scrollbar &/or the white space appear.

## Solution
Instead use `styles.overflowAuto` so that the scrollbar and/or the white space is only shown when the scrollbar is needed.

https://github.com/Expensify/App/blob/d9ec05a2a26c42e865974322a2e9006b327f95d2/src/components/ImageView/index.js#L252

```diff
In src/components/ImageView.js#L252
-  styles.overflowScroll
+  styles.overflowAuto
```

**Comment by dhairyasenjaliya** [comment]
Can't seems to be reproducible and also in latest version scroll bar color is dark and posted video is white

**Comment by bernhardoj** [comment]
### **Proposal**

If we take a look at the style applied to the Image, we set the `overflow` to `scroll` (styles.overflowScroll) and `scrollbarWidth` to `none` (styles.noScrollbars). So, the scroll should not be visible even if it's scrollable. However, `scrollbarWidth` only works on Firefox. We need `::-webkit-scrollbar: { display: none }` to hide the scrollbar on the other browser and `-ms-overflow-style: none` for IE.

https://github.com/Expensify/App/blob/d9ec05a2a26c42e865974322a2e9006b327f95d2/src/components/ImageView/index.js#L247-L256

Because there is no way to target pseudo-elements from js, we need to create a new .css file for `ImageView` (inspired from `DatePicker/styles.css`.

```
.no-scrollbar {
    scrollbar-width: none;
    -ms-overflow-style: none;
}
.no-scrollbar::-webkit-scrollbar {
    display: none;
}
```

Then apply the class to the component.

```diff
componentDidMount() {
    Image.getSize(this.props.url, (width, height) => {
        this.setImageRegion(width, height);
    });
    if (this.canUseTouchScreen) {
        return;
    }
+   this.scrollableRef.classList.add('no-scrollbar');
    document.addEventListener('mousemove', this.trackMovement);
    document.addEventListener('mouseup', this.trackPointerPosition);
}
```

And we don't need `styles.noScrollbars` anymore.

```diff
<View
    ref={el => this.scrollableRef = el}
    onLayout={this.onContainerLayoutChanged}
    style={[
        styles.imageViewContainer,
        styles.overflowScroll,
-       styles.noScrollbars,
        styles.pRelative,
    ]}
>
```

**Result**

https://user-images.githubusercontent.com/50919443/210125562-657b56c4-55a7-4584-a195-81b422b1a576.mov

**Comment by priyeshshah11** [comment]
> can't repro this either
> 
> v1.2.45-0, macOS

@rushatgabhane You need to enable this in system preferences and use a very large image and/or zoom in.

<img width="456" alt="Screen Shot 2023-01-02 at 10 52 51 PM" src="https://user-images.githubusercontent.com/38547776/210227736-2334de1e-7910-4721-be82-964fcbcfc175.png">

**Comment by dhanashree-sawant** [comment]
Try it on windows, same issue exists there too

**Comment by getusha** [comment]
This is what i am seeing,
macOS
<img width="913" alt="Screenshot 2023-01-04 at 9 22 43 AM" src="https://user-images.githubusercontent.com/75031127/210613310-6ae79077-9219-470e-af7e-5268f5d9e90a.png">

Is this still reproducible?

**Comment by MitchExpensify** [comment]
I can not reproduce this anymore

**Comment by bernhardoj** [comment]
That's the issue. @getusha 
It just have a darker color now instead of white scrollbar.

**Comment by MitchExpensify** [comment]
Do you have reproduction steps @bernhardoj? I don't see any scroll bar at all on v1.2.48-2 using theses:

> 1. Open the app
> 2. Open any report
> 3. Attach any image

**Comment by priyeshshah11** [comment]
> Do you have reproduction steps @bernhardoj? I don't see any scroll bar at all on v1.2.48-2 using these:
> 
> > 1. Open the app
> > 2. Open any report
> > 3. Attach any image

@MitchExpensify The last step should be changed to "Attach a large image" large in pixels

**Comment by MitchExpensify** [comment]
Thanks @priyeshshah11  - Tried without success. Can someone share an image file they have used to successfully reproduced this perhaps?

**Comment by priyeshshah11** [comment]
> Thanks @priyeshshah11 - Tried without success. Can someone share an image file they have used to successfully reproduced this perhaps?

I can reproduce it with this image & mac settings set to always display scrollbars

![favicon](https://user-images.githubusercontent.com/38547776/210674520-718c06e5-b7a0-4dd6-8f7c-459d8628f56e.png)

**Comment by dhanashree-sawant** [comment]
On windows, it occurs using any image and without changing any settings

https://user-images.githubusercontent.com/87513216/210687648-8cb16dbf-9425-4282-96da-3e4caeeb083a.mp4

**Comment by getusha** [comment]
@rushatgabhane  In CSS `overflow: scroll` creates a scrollbar whether or not there is content that requires scrolling
`overflow: auto` creates a scrollbar only when the content is too large to fit within the element.

right @priyeshshah11?

**Comment by priyeshshah11** [comment]
> I don't get why this isn't the default even if "always show scrollbar" is enabled.

@rushatgabhane I didn't get what you mean by "this" here but @getusha's comment is correct in terms of the root cause

**Comment by bernhardoj** [comment]
If we are going with @priyeshshah11 proposal, I think we will need to remove `styles.noScrollbar` from the style to make the behavior consistent through all browsers.

**Comment by MitchExpensify** [comment]
@rushatgabhane do the responses above make you feel more comfortable going with @priyeshshah11 's proposal?

**Comment by getusha** [comment]
@rushatgabhane i think it's different thing

**Comment by getusha** [comment]
The native behavior is not overridden, it's a separate functionality
watch this

https://user-images.githubusercontent.com/75031127/211016486-44e107ef-755c-4e79-8a70-14301e8c5ce6.mov

**Comment by priyeshshah11** [comment]
@rushatgabhane IMO we should just use `styles.overflowAuto` that way we only show the scrollbar when it's needed & also respect user's settings/preferences. I don't know the reason why we are hiding the scrollbar in Firefox but I agree that it should be consistent.

**Comment by getusha** [comment]
@rushatgabhane yes you're, it overrides it on firefox

**Comment by vaibhav-OP** [comment]
### Proposal

**issue:** 
overflowing image inside element creating scrollbar

**Solution**
setting the width of scrollbar to 0 or changing its display to none may work but the problem you guys are facing is image is flowing outside of the element. With `overflow: hidden;` you can possibly solve the issue you are facing by simply not showing anything which overflowing, your zoom in and out thingy is using JS to scroll the element hence the `overflow: hidden;`  will not be disturb it.

**Comment by shawnborton** [comment]
Agree, let's solve this with overflow: auto or overflow: hidden, but let's not do anything to change the width or appearance of native scrollbars.

**Comment by priyeshshah11** [comment]
@puneetlath @rushatgabhane Thanks for assigning, will raise a PR by EOD today (i.e. in < 12 hours) Thanks 😄

**Comment by priyeshshah11** [comment]
@puneetlath @rushatgabhane PR is up & have applied on upwork too.

**Comment by MitchExpensify** [comment]
@rushatgabhane @priyeshshah11 hired!

Mind applying for the reporting bonus @dhairyasenjaliya ? Thank you! https://www.upwork.com/jobs/~01b3caf73e33e6e0de

**Comment by priyeshshah11** [comment]
> Hi @MitchExpensify, The issue was actually reported by me. Can you recheck it once with @kavimuru?

maybe that was just a wrong tag by @MitchExpensify 😅

**Comment by MitchExpensify** [comment]
Apologies, yes I just tagged that wrong! I meant to ask you to apply @dhanashree-sawant - Hired you now!

**Comment by priyeshshah11** [comment]
@MitchExpensify Messaged on upwork for payment as this has now successfully passed the 7 day hold period, thanks 😄

**Comment by MitchExpensify** [comment]
Apologies for the delay! Issuing payment now

**Comment by MitchExpensify** [comment]
Payments all made and contracts ended! Thanks everyone!
