### ISSUE TITLE
Payment for E/E #249195 [Refactor] Report.fetchIOUReportByID App API call and clean up syncChatAndIOUReports 

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#13896]
Issue - https://github.com/Expensify/Expensify/issues/249195
PR - https://github.com/Expensify/App/pull/13556
C+ @mollfpr 
Amount $1000

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ddd78a2c274b60f</li>
        <li>Upwork Job ID: 1608614284602720256</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@mollfpr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019ddd78a2c274b60f

**Comment by mollfpr** [comment]
@mallenexpensify Accepted, thank you!

**Comment by mallenexpensify** [comment]
Paid $1000, thanks @mollfpr
