### ISSUE TITLE
[HOLD for payment 2023-01-19] mWeb/Chrome - OldDot transition - The infinite spinner after being redirected to NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the OldDot mobile app and log in with an account that has a existing workspace policy
2. Navigate to "Settings" and tap on "View all" on the policies section
3. Tap on the "Group" tab
4. Tap on the "Edit" button next to a Workspace
5. Tap on the "Current Plan" option inside the workspace settings

## Expected Result:
User is redirected to NewDot on mWeb

## Actual Result:
The infinite spinner after being redirected to NewDot.
Repeat for all 3 scenarios:
- Signed out of NewDot/
- Signed in with a different account in NewDot
- Signed in with the same account in NewDot.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.45.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210021993-da76f113-e6bb-4ba3-8a40-950c3e7defad.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6d1ff001e7a42b4</li>
        <li>Upwork Job ID: 1611145963403091968</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
- [x] bug is a bug
- [x] Not a dupe but related issues:
- https://github.com/Expensify/App/issues/10271
- https://github.com/Expensify/App/issues/13326
- https://github.com/Expensify/App/issues/13026
- [x] Reproducible - confirmed on my Pixel 7 handset
- [x] GH template complete
- [x]  Title and Body are clear 
- [x] Created by QA 
- [x] Old dot - newdot link issue 
- [x] No Slack convo
- [x] This feels like it needs internal review cos of the olddot aspect

**Comment by alex-mechler** [comment]
Interestingly enough, I can only get this on prod, but not on staging. Looking into when we last deployed to see if maybe a fix is already released

**Comment by alex-mechler** [comment]
https://github.com/Expensify/App/pull/13600/files is the only thing I can see that might have impacted this, will retest this after that goes to prod to see if this is fixed

**Comment by alex-mechler** [comment]
Okay, still reproducing this, but I figured out the root cause. Will get a pr up

**Comment by laurenreidexpensify** [comment]
On Staging

**Comment by laurenreidexpensify** [comment]
@aimane-chnaif pls accept job on upwork, thanks!
