### ISSUE TITLE
mWeb - On long pressing `Send` button it selects ".jpg" in the file name is highlighted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to any conversation
3. Add attachment -> Select any file -> On attachment viewer on long press Send button
4. Notice Random text on attachment file is selected

## Expected Result:
On long pressing button no text should be selected

## Actual Result:
On long pressing button random text (".jpg" in the file name) is selected

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210029691-9fb8475c-96fc-4c5b-8794-129903288a76.mp4

<img src="https://user-images.githubusercontent.com/43996225/210029693-17d2ddbf-7920-4178-acf8-3b014e238b15.jpeg" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/210029695-ac37b0eb-f1a7-47a3-80b4-ebaa747cbdc5.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672227021180509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Personally I don't think this really needs to be fixed cc @mateocole

**Comment by mateocole** [comment]
Okay, going to close out
