### ISSUE TITLE
[HOLD for payment 2023-01-12] [$1000] Refactor room settings page to use Form component

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#13915]
Similar to what we did in https://github.com/Expensify/App/issues/13524 we should update the Room Settings page to use the Form component. Once we have done that, we will be able to make the changes needed in https://github.com/Expensify/App/issues/12678. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162731e7a46cb5f16</li>
        <li>Upwork Job ID: 1609248342749614080</li>
        <li>Last Price Increase: 2022-12-31</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@fedirjh would you be interested in taking this on. Offering to you first since you worked with me on https://github.com/Expensify/App/issues/13524

**Comment by fedirjh** [comment]
@puneetlath Thanks for the proposal , I will be happy to take it . I will share the PR once it's done

**Comment by fedirjh** [comment]
PR is ready for review https://github.com/Expensify/App/pull/13923

**Comment by puneetlath** [comment]
This has been deployed to production. @fedirjh @mollfpr if you guys can apply to the Upwork job so that I can get you paid out after the regression period. Thanks!

**Comment by fedirjh** [comment]
Thanks @puneetlath , I applied there.

**Comment by puneetlath** [comment]
Paid both @fedirjh and @mollfpr with 50% bonus. All done here, thanks everyone!
