### ISSUE TITLE
[Branding / Polish] Fix Mono Padding / Highlight

### ISSUE THREAD

**Issue by grgia** [Expensify/App#13914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

<img width="600" alt="image" src="https://user-images.githubusercontent.com/38015950/210108270-7959e6f6-11c4-4a0d-8c21-7d72f99d25bb.png">

Mono needs at least 1px more lower padding to account for `g`

<img width="260" alt="image" src="https://user-images.githubusercontent.com/38015950/210108521-ce808763-b98b-4654-a9e7-3893d2464265.png">

Additionally, Highlight goes outside of bounding box

cc @shawnborton 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017297fa075b8dfe88</li>
        <li>Upwork Job ID: 1608918513250811904</li>
        <li>Last Price Increase: 2022-12-30</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Seems like there is a bunch of horizontal padding there too. 

I wonder if we can make this only 20px high total to match the line height of a standard message? Like if the characters are vertically centered within a 20px tall rounded rectangle, would we be good?

**Comment by grgia** [comment]
I'll give that a go!

**Comment by grgia** [comment]
PR in progress!

**Comment by grgia** [comment]
haven't looked at this in a few days

**Comment by grgia** [comment]
back from OOO, going to make this one weekly while I'm catching up, but I should be able to fix it really quick

**Comment by grgia** [comment]
A little swamped, but I'll fix this after the SEO project stuff

**Comment by grgia** [comment]
Moving to monthly

**Comment by grgia** [comment]
I'll get this done by EOW !

**Comment by grgia** [comment]
Not overdue

**Comment by grgia** [comment]
Not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue
