### ISSUE TITLE
Profile images appear in square when gif is uploaded as profile pic

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and login with user A
2. Open settings and your profile
3. Replace your current profile image with any gif image (attached the gif I used)
4. Open the app and login with same different user in android app
5. Look at user A profile pic

## Expected Result:
Profile pic should appear circular

## Actual Result:
Profile pic appears square in shape

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210095463-be5b6bcb-7d62-4b46-ad43-025bb3ad72c2.mov

https://user-images.githubusercontent.com/43996225/210095488-daa42d92-3103-4305-b2a8-4ccba70d7ba7.mp4

<img src="https://user-images.githubusercontent.com/43996225/210095610-393d756e-b980-45fd-90b8-fceabca85b69.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @dhanashree-sawant

**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1672390984891429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Hmm so I want to keep this on my radar, I'm already planning to stop allowing gif images so we may not have to do anything here, once the update comes through

**Comment by sketchydroide** [comment]
Yeah I would advise to not allow gif images as well, they are supported with some effort on native mobile, so they are not a good idea, and don't really bring anything. I support changing this bug to a GH about disallowing Gifs, or just create a new GH and close this one.

**Comment by sketchydroide** [comment]
assigning both of us so they don't appear unassigned in the list of Bugs.

**Comment by Beamanator** [comment]
Nice thanks @sketchydroide 👍

**Comment by sketchydroide** [comment]
I'm not sure this should have the planning label, as the fix is not directly related to the bug.

**Comment by sketchydroide** [comment]
is there a GH or PR already to stop the gif from being an avatar?

**Comment by Beamanator** [comment]
Good Q, no PR yet but that's coming for this issue: https://github.com/Expensify/App/issues/13038

**Comment by sketchydroide** [comment]
ok we can close this one then, I'll mention it on the other GH
If any one disagrees, we can reopen it.
