### ISSUE TITLE
[Hold for Payment 2023-01-12] DEV - console error  Warning: Failed prop type: Invalid prop...   when select incorporation date on company information page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Install the app (uninstall and reinstall if you have already installed)
 2. Go to Settings >  workspace > Connect bank account > connect manually
 3. enter routing number and account number and click on continue button
 4. on company information page select any incorporation date

## Expected Result:
should not show any console error

## Actual Result:
shows console error on  select incorporation date

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** v1.2.45-0(main branch)
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210185909-bae415c9-fb2e-4f4d-ae4c-4562b3909c42.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672410039453549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3cb968e1a245ad7</li>
        <li>Upwork Job ID: 1610367988882657280</li>
        <li>Last Price Increase: 2023-01-03</li>
    </ul>
</details>

**Comment by tgolen** [comment]
I reproduced this one and I can fix it.

**Comment by trjExpensify** [comment]
Neat, thanks @tgolen!

**Comment by tgolen** [comment]
PR was here: https://github.com/Expensify/App/pull/13936

**Comment by trjExpensify** [comment]
Assigned @thesahindia for the C+ review and sent an offer on this [Upwork job](https://www.upwork.com/jobs/~01e3cb968e1a245ad7).

Also updated the title with the payment date +7 days from today when the linked PR hit prod. 👍

**Comment by trjExpensify** [comment]
Okaaay, settled up! Thanks ya'll. 

- $250 to @gadhiyamanan for the bug report
- $1000 to @thesahindia for the internal PR review
