### ISSUE TITLE
Lock icon on BankAccountSetup has different color and it is not clickable as link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open Any Workspace
3. Open 'Connect Bank Account'
4. Try to click on lock icon besides 'Your data is secure' and inspect its color

## Expected Result: 
Lock icon should be clickable as it seems to be part of  'Your data is secure' link and color for icon should be same as text color

## Actual Result: 
Lock icon is not clickable and it has color: rgb(1, 133, 255) whereas 'Your data is secure' text has color: rgb(90, 176, 255)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210186673-c196ff3d-50ef-4844-aba7-32f51718f95b.mp4

https://user-images.githubusercontent.com/43996225/210252495-3f328433-400a-4e5f-b409-11a39a05fba2.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672415298266079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Seems like a simple fix, will knock it out asap

**Comment by jasperhuangg** [comment]
PR up here: https://github.com/Expensify/App/pull/13924

**Comment by michaelhaxhiu** [comment]
ah this one slipped right by me! I'll handle compensation now, and apologies @dhanashree-sawant!

**Comment by michaelhaxhiu** [comment]
paid.
