### ISSUE TITLE
[Hold - Browser Resizing - #13971] Send button is missing after switch between small screen to large when pdf password input is focused.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Resize the window to get small screen view (hidden sidebar).
2. Open any chat room.
3. Drag / Add password protected pdf file.
4. In modal click on enter the password.
5. Click on input (Must don’t leave input focus).
6. Resize window to full screen.
7. Observe send button is missing even when we click outside or close modal and retry to drag file send button not available.

## Expected Result:
Send button should be visible again on outside click or even it should not hide on desktop.

## Actual Result:
Send button not visible until refresh page or switch chat room.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.2.46-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210260872-6b633c1f-70e3-4fd4-9c3c-2613c5ab375c.mov

https://user-images.githubusercontent.com/43996225/210260898-214fb13c-6f41-45c2-93bb-a1bcb0400433.mp4

**Expensify/Expensify Issue URL:** 
 **Issue reported by:** @jatinsonijs 
 **Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672493456932239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I can reproduce this issue on the latest staging web, but I'm on the fence as to whether it's something we're focused on as it's a unlikely case of resizing the browser window to a very small size in this specific case of a password protected PDF file upload.

@JmillsExpensify @Beamanator for a second opinion on that?

**Comment by trjExpensify** [comment]
Had a convo in[this thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1672783427814329) and I've created [this parent issue](https://github.com/Expensify/App/issues/13971). We should tackle all of these browser resizing issues holistically and need someone to own that plan.

**Comment by trjExpensify** [comment]
Still held.

**Comment by trjExpensify** [comment]
Still held.

**Comment by JmillsExpensify** [comment]
Assigned myself as well so I keep it on my radar in conjunction with the linked issue.

**Comment by trjExpensify** [comment]
No change, Melv.

**Comment by trjExpensify** [comment]
Still on hold for the wider project, that's held on the navigation reboot.

**Comment by trjExpensify** [comment]
@JmillsExpensify @mountiny what are your thoughts on browser resizing? This issue is held on an initiative to tackle it holistically, which was on hold for the nav reboot. Wonder whether that should get picked up now?

**Comment by mountiny** [comment]
@trjExpensify I would wait for this PR to be merged https://github.com/Expensify/App/pull/22437 it will hopefully resolve a bunch of issues with resizing after the nav reboot and then we should be in a better place to look at this one.

Frankly though I think its kind of an edge case which might be more of a distraction than useful value, basically unless its really breaking issue we might want to just leave it for now and focus on these issues maybe with use of agencies (usually it should not require backend changes)

**Comment by mountiny** [comment]
> I agree in isolation, but if we're broadly fixing browser resizing app wide as a project, I think we should fix it everywhere. I love the idea of asking an agency to take that on holistically though.

Oh yeah I mean if we are going to put effort in it, then lets fix it everywhere, I am just questioning of how much time we should dedicate internally, although if we can define the problems and issues, agencies should be able to take care of this

**Comment by JmillsExpensify** [comment]
I think we should tackle browser re-sizing, and minimally have a tracking issue and map all the relevant bugs we find to it, but I agree that it's not really a priority right now. There are a million other things I'd rather we prioritize.

**Comment by JmillsExpensify** [comment]
Same

**Comment by trjExpensify** [comment]
Same!

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
Still not a focus.

**Comment by JmillsExpensify** [comment]
Same

**Comment by trjExpensify** [comment]
Mills, do we want to just close this?

**Comment by JmillsExpensify** [comment]
We don't plan on prioritizing browser resizing anytime soon. We're more focused on migrating our existing customers from our old platform to our new platform, which will minimally take the remainder of this year. We can open up this issue in the future if/when this becomes a priority.
