### ISSUE TITLE
Android - Size of the symbols are not same 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed

1. Open the chat
2. Go to chatting
3. Type symbol from the device keyboared

## Expected results: 
Symbols size should be same

## Actual results : 
Symbols size aren't same

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.47-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210275709-693f8655-53e2-48aa-94ee-bdc0f7bc2950.mp4

https://user-images.githubusercontent.com/43996225/210275715-916a2aa2-0d98-4c26-9f15-fca26ad7d7cf.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ekramkhan66
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672216294616209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e028289600d719d6</li>
        <li>Upwork Job ID: 1613635646625341440</li>
        <li>Last Price Increase: 2023-01-12</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
I can take a look!

**Comment by yuwenmemon** [comment]
FYI this happens on web too: 
<img width="537" alt="Screenshot 2023-01-16 at 12 32 48 PM" src="https://user-images.githubusercontent.com/4741899/212761393-ad4e7829-6764-4985-ba7c-ab86221f9175.png">

**Comment by yuwenmemon** [comment]
I don't think this is a bug, technically those symbols are part of the emoji unicode set: https://www.unicode.org/Public/15.0.0/ucd/emoji/emoji-data.txt

**Comment by yuwenmemon** [comment]
Made a comment on Slack thread here: ⁦⁦⁦https://expensify.slack.com/archives/C049HHMV9SM/p1673904568468629?thread_ts=1672216294.616209&cid=C049HHMV9SM

But to put it another way the `Extended_Pictographic` matching set we're using [here](https://github.com/Expensify/App/blob/f3600bff91acaba87f882e1d6683b9cdf8de3585/src/CONST.js#L771) ensures we match emojis with a picture component. The spade, copyright symbols, etc all fall within that category according to Unicode.

**Comment by yuwenmemon** [comment]
Search for `# All omitted code points have Extended_Pictographic=No` in here https://www.unicode.org/Public/15.0.0/ucd/emoji/emoji-data.txt
