### ISSUE TITLE
[Hold for payment - 2023-01-17] Disparity with the disabled color of some of the danger buttons (Orange/Red)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13946]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### First Example

1. Open Expensify App/Web
2. Go chat setting > security >close account
3. Turn off internet connection
4. View `Close account` button

### Diferent example different color

1. Go to the details of a Workspace
2. Manage Members
3. View `Remove` button

## Expected Result:
Disable Button colour should be consistent across pages.

## Actual Result:
Buttons colour are different.

## Workaround:
Not Relevant

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.47-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="488" alt="Screenshot 2022-12-24 at 1 23 41 PM" src="https://user-images.githubusercontent.com/43996225/210280941-801e1d4c-2cd0-41f1-b5d4-6370a67df03d.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/210280949-6f932df2-5fe6-45aa-b321-6bf28e6eb582.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672179940274299?thread_ts=1672085824.788259&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8eca0393ff2cdbb</li>
        <li>Upwork Job ID: 1610696513619075072</li>
        <li>Last Price Increase: 2023-01-04</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
I've commented in [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1672085824788259) to check this one isn't already on the radar of the peeps working on the branding changes.

**Comment by sketchydroide** [comment]
happy to do the fix if it't not @trjExpensify

**Comment by trjExpensify** [comment]
Cool, nice! It isn't, so that'll be good. I've asked @shawnborton in thread to confirm we want the same opacity as the `remove member` button here: 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/16232057/210618935-11448dc2-4f6b-41ba-be96-b9ece58e4c2a.png">

**Comment by shawnborton** [comment]
I actually think the Close account button might be the more correct one? Basically I think we want disabled buttons to just have a reduced opacity, like 50% opaque. The remove button looks weird because it's almost like we're using a lighter color instead of reducing the overall opacity of the button.

**Comment by sketchydroide** [comment]
I will investigate what is actually happening

**Comment by sketchydroide** [comment]
also for comparison this is the color of the close on not offline mode
<img width="373" alt="Screenshot 2023-01-05 at 16 10 14" src="https://user-images.githubusercontent.com/242568/210827129-fe179adc-522a-4fca-acf0-caf84b30e681.png">

**Comment by sketchydroide** [comment]
I think the close button offline is being set to both opacity 0.5 and the other weird color:
```
    opacity: 0.5;
    background-color: rgb(248, 170, 151);
```

**Comment by shawnborton** [comment]
Nope, we just want to use our standard red color but then have the entire button use a reduced opacity.

**Comment by sketchydroide** [comment]
thanks, I will get that done then

**Comment by sketchydroide** [comment]
So first thing I will see where `redDisabled ` is being used and remove it. and will check if this places are changing the opacity and if not change it.

**Comment by trjExpensify** [comment]
>I actually think the Close account button might be the more correct one? Basically I think we want disabled buttons to just have a reduced opacity, like 50% opaque. The remove button looks weird because it's almost like we're using a lighter color instead of reducing the overall opacity of the button.

Ahhh, the Remove button hasn't been updated to a new style with the branding changes, so that's the incorrect one! Makes sense.

**Comment by sketchydroide** [comment]
This how the 2 buttons now look:
<img width="369" alt="Screenshot 2023-01-06 at 14 11 17" src="https://user-images.githubusercontent.com/242568/211029007-e5822997-dbc7-4004-be95-cebf9fe57c35.png">
<img width="376" alt="Screenshot 2023-01-06 at 14 07 33" src="https://user-images.githubusercontent.com/242568/211029010-27cd06eb-859f-4a3e-96ea-93766bc1d27f.png">

**Comment by trjExpensify** [comment]
Looks good to me! 👍

**Comment by shawnborton** [comment]
Yup, much better!

**Comment by trjExpensify** [comment]
Woop! @sketchydroide is there a PR to link to this issue yet?

**Comment by sketchydroide** [comment]
There is now 😄

**Comment by trjExpensify** [comment]
Not overdue, due payment tomorrow.

**Comment by trjExpensify** [comment]
Offers have been sent to you both on [this private job](https://www.upwork.com/jobs/~01b8eca0393ff2cdbb), can you accept please? Payment summary:

@Santhosh-Sellavel - $1,000 for the C+ review of the internal PR 
@Tushu17 - $250 for the bug report

**Comment by trjExpensify** [comment]
Settled up with you, @Santhosh-Sellavel. @Tushu17, please accept the offer. 👍

**Comment by Tushu17** [comment]
@trjExpensify Offer accepted, Thank you.

**Comment by trjExpensify** [comment]
Excellent. Settled!
