### ISSUE TITLE
Make pending avatars show "pending" everywhere

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#13957]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Upload an avatar

## Expected Result:
I'd expect to see the Pending avatar UI (grayed out avatar) everywhere we show that avatar

## Actual Result:
I only see the pending avatar UI in the Profile page

## Workaround:
None needed

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Latest
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/3885503/210394025-90cab422-2527-49a8-8998-3f460a447aa7.mov

**Issue reported by:** Me 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174784941ed533394</li>
        <li>Upwork Job ID: 1610305348361109504</li>
        <li>Last Price Increase: 2023-01-03</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
PR is here, and already merged: https://github.com/Expensify/App/pull/13185

@thesahindia was the C+ there, so assigning him here so we can pay him out

@lschurr this PR is already in production so let's just pay @thesahindia and close this out?

**Comment by lschurr** [comment]
@thesahindia - can you apply for the job in Upwork? https://www.upwork.com/jobs/~01431b0f3e991c82e6

**Comment by thesahindia** [comment]
@lschurr applied, thanks!

**Comment by lschurr** [comment]
Paid! I assume this can now be closed. Reopen if I'm wrong.

**Comment by Beamanator** [comment]
Groovy thanks @lschurr 👍
