### ISSUE TITLE
mWeb/safari - Emojis- The scrolling bar is dark and almost invisible.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to staging.new.expensify.com
2. Login with any account
3. Go to any chat room
4. In composer, click the Emoji button
5. Verify that the scroll bar looks "well" in the dark mode

## Expected Result:
The scrolling bar is not dark and visible.

## Actual Result:
The scrolling bar is dark and almost invisible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.47.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210285183-c434fc95-6d3f-4d75-8715-729492155e7c.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
cc @grgia @Luke9389 @shawnborton do we need to fix this?

**Comment by shawnborton** [comment]
Personally I don't think this is a bug and we can close it.
