### ISSUE TITLE
Dev -  `Notify me about new messages` settings on workspaces doesn’t update while selecting new options from the dropdown list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Run desktop or web app locally
2. Login with any account
3. Click on profile icon on the top
4. Click on workspaces and create a new one
5. Open newly created workspace from the chat menu
6. Click on profile icon of the workspace and click on settings
7. Try to change the setting ‘’Notify me about new messages’ by selecting either ‘mute’ or ‘daily’ option from the dropdown
8. Go back and again try to view the settings that you made changes to
9. Notice that the selected option doesn’t update on that setting ( Immediately option remains forever no matter how many times you change it to ‘daily’ or ‘mute’ option)

## Expected Result:
‘Notify me about new messages’ settings on a workspace should get updated with the option that user sets from the dropdown list

## Actual Result:
Notify me about new messages’ settings on a workspace doesn’t update in dev environment (Immediately option is selected everytime even if you change it to ‘daily’ or ‘mute’) (Error can only be seen in workspaces and not in #admins and #announce)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Occurring in Dev
**Reproducible in staging?:** 
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210437520-a45fdf67-5353-4031-954f-4e187f0876a3.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672735194174329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
I can't seem to reproduce on dev 


https://user-images.githubusercontent.com/31285285/210506048-febba0dd-3286-49e7-86c4-a82b3ff5bb3b.mov

If we can repro I'd be happy to help look into a fix. @kavimuru Can you open the Inspector `<Command + Option + I>, select the "Network" tab, and provide another screen recording of it failing for you?

**Comment by jasperhuangg** [comment]
Woops, didn't realize the OP also pointed out the issue on desktop. I've tested it after pulling `main` with both the platforms specified in the OP and have not been able to reproduce.

https://user-images.githubusercontent.com/31285285/210757870-2aae5079-6dc2-400c-893f-e51b4fd72885.mov

https://user-images.githubusercontent.com/31285285/210757171-347e440e-7608-4f29-bdf2-49c5bba6e15a.mov

Therefore I'm electing to close this out.
