### ISSUE TITLE
Web - Settings - Message "You appear to be offline" message NOT displayed in Timezone page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13927 

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Go to Setting - Profile
4. Disable the internet connection in the device
5. Go to Timezone

## Expected Result:
Message "You appear to be offline" message displayed at the bottom

## Actual Result:
Message "You appear to be offline" message NOT displayed in Timezone page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome / Safari

**Version Number:** 1.2.48.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![0401](https://user-images.githubusercontent.com/93399543/210626424-96a6fe32-7c46-4922-8d18-766e4235999f.png)

https://user-images.githubusercontent.com/93399543/210626515-6a7af890-4ce0-4cd8-954c-98c9e117b61f.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Just taking this one on as WAQ

**Comment by luacmartins** [comment]
This is expected. The offline message should show under the compose box for large screens and within the modals for small screens. See images below:

![web](https://user-images.githubusercontent.com/22219519/210692956-86d5669a-22e4-4c55-afc5-f0d0dead923a.png)

![Screenshot 2023-01-04 at 8 08 18 PM](https://user-images.githubusercontent.com/22219519/210692960-c8a1db42-a2b0-4591-aa61-47da38390688.png)

The issue that https://github.com/Expensify/App/pull/13927 fixed is that the message was not bottom docked in small screens.

**Comment by mountiny** [comment]
Thanks, I wanted to confirm that @luacmartins

Lets make sure this is correctly captured in the test steps. @kbecciv is there a regression test for this? Or was it raised purely from the PR test steps?

**Comment by mountiny** [comment]
We should still add a regression test for this I guess.

**Comment by mountiny** [comment]
Closing this, I think we should be fine here, it came from the testing steps in the PR
