### ISSUE TITLE
mWeb/safari -Connect Bank Account - "Expensify Terms of service" message disappears when clicking on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR**  https://github.com/Expensify/App/pull/13781

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with any account
3. Open a workspace that does not have a bank account connected yet, then go to Connect Bank Account > Connect Manually
4. Follow the flow to add a "Pending" bank account (routing: 011401533, account number: 1111222233331111, business name: Alberta Bobbeth Charleson)
5. Click "Expensify Terms of service".

## Expected Result:
"Expensify Terms of service" should not disappear when clicking on it

## Actual Result:
"Expensify Terms of service" message disappears when clicking on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.48.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210647029-9562fc65-eb92-43b0-91ad-b09c75bb0cde.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
I'm unable to reproduce this on Chrome and Safari. I tried both the web app and mobile app, and when I click on Terms of Service, a new tab opens with Expensify's Terms of Service.

https://user-images.githubusercontent.com/31258516/211037251-58986d59-c7e4-4dee-b044-ff89da7376e8.mp4
