### ISSUE TITLE
[HOLD for payment 2023-02-07] Make app start TTI more accurate

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#13996]
## Action Performed:

- When the app starts we measure the time it takes until the `SidebarLinks` are rendered, known as "App start TTI".
This measurement is reported to Grafana. Currently any waiting time due to waiting on network data is included in the TTI. This PR changes that, and will only report the TTI when we render the `SidebarLinks` with cached data on the first render.
- Currently when reporting to grafana no information about the environment is included, meaning data from staging and production  is mixed. This PR also adds env info to the grafana logging.

This is an effort towards: https://github.com/Expensify/App/issues/11997

## Expected Result:

- Only report TTI from cached render results (we want to know if we introduced performance regression issues in the code, not whether the API is slow to respond)
- Events reported to grafana include environment information

## Actual Result:

/

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes they can, this is just for internal performance monitoring.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.48-2
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @hannojg 
**Slack conversation:** None, but this issue https://github.com/Expensify/App/issues/11997

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment]
I just created this PR for the issue: https://github.com/Expensify/App/pull/13997

**Comment by abekkala** [comment]
@hannojg did you report this bug in the #expensify-open-source Slack channel? (As you don't directly open issues in this repo)

If so, can you link to that slack conversation please?

**Comment by AndrewGable** [comment]
Confirmed @abekkala - Working with @hannojg on this one. They get paid hourly so no need to worry about upwork.

**Comment by abekkala** [comment]
@AndrewGable I just want to confirm there is still no action needed from me (BugZero) as payments aren't made via Upwork and I don't need to add/edit a Test Rail?

**Comment by AndrewGable** [comment]
Confirmed!

**Comment by AndrewGable** [comment]
@abekkala - Can you please handle? Thanks!

**Comment by abekkala** [comment]
@AndrewGable LOL so I do need to make a payment via Upwork? 
Who is the C+ on this that needs payment? I'm not sure who was considered Margelo and who needs to be paid via Upwork.

**Comment by abekkala** [comment]
Payment has been sent, the contract has been completed, and the Upwork job post has been closed.
