### ISSUE TITLE
[HOLD for payment 2023-01-16] Workspace name is truncated even though there is enough space to fill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14007]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new long name workspace if you don't have one
2. Go to Settings > Workspaces
3. Observe the long workspace name is truncated

## Expected Result:
Workspace name should not be truncated when there is still enough space

## Actual Result:
Workspace name is truncated

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari (resizing the browser)
- [ ] MacOS / Desktop (resizing the browser)

**Version Number:** v1.2.48-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (2)](https://user-images.githubusercontent.com/43996225/210683553-90dbd9ba-7b4b-4087-8214-6211060eb99b.png)
<img width="960" alt="Untitled1" src="https://user-images.githubusercontent.com/43996225/210683569-91fd0fa3-3f90-4457-a4e9-02032b3f1d32.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1672827523060149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bc707bc39462f98</li>
        <li>Upwork Job ID: 1611127456696561664</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
[PR](https://github.com/Expensify/App/pull/14040) up!

**Comment by Pujan92** [comment]
Have doubt, is this needs to consider for the general MenuItems or only for Workspace List?
IMO it should apply to all and 1 more usecase is here

<img width="524" alt="Screenshot 2023-01-06 at 8 54 43 AM" src="https://user-images.githubusercontent.com/14358475/210924068-49ffbdf8-4258-4685-9e7e-9df630230cf9.png">

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 82e9ca8f2..46964ec1d 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1119,7 +1119,6 @@ const styles = {
     popoverMenuText: {
         fontSize: variables.fontSizeNormal,
         color: themeColors.heading,
-        maxWidth: 240,
     },
```

**Comment by mananjadhav** [comment]
Thanks for raising this @Pujan92. I think this can be worked as a separate issue. While the change looks small enough, the `MenuItem` component is used at several places. We will have test all those components for an unrelated change.

But if @luacmartins thinks we can add in this PR, I am fine with that too.

**Comment by luacmartins** [comment]
I considered that, but dismissed it for the same reasons @mananjadhav mentioned. However, it seems like the PR that introduced the fixed width did so to truncate long workspace names. So it might be safe to remove this. I'll come back to test this after the deploy is done!

**Comment by mananjadhav** [comment]
@miljakljajic Can you help me with the payout here? This has crossed the regression period. Been on production for 7 days.

cc - @luacmartins

**Comment by mananjadhav** [comment]
@miljakljajic Quick bump.

**Comment by miljakljajic** [comment]
Paying immediately!

**Comment by miljakljajic** [comment]
Please accept the offer when you have a chance.

**Comment by mananjadhav** [comment]
Thank you so much @miljakljajic. Accepted

**Comment by bernhardoj** [comment]
May I have your help too for the reporting bonus? @miljakljajic

**Comment by miljakljajic** [comment]
Of course! I paid you your bonus @bernhardoj and sent payment to you, @mananjadhav. Thank you for your patience and apologies for the delay.

**Comment by mananjadhav** [comment]
Thanks @miljakljajic for the help here
