### ISSUE TITLE
"A room with this name already exists" message appears on Create New Room page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with account that has policyRooms beta enabled
2. Click FAB -> New Room
3. Don't input anything and just click "Create Room" button
4. "A room with this name already exists" message shows below Room Name input field
5. Type any letter on Room Name field and erase all
6. This time, "Please enter a room name" message shows below Room Name input field

## Expected Result:
Error message should be consistent as "Please enter a room name"

## Actual Result:
"A room with this name already exists" error shows first time

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**v1.2.48-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210688549-978b46b7-d921-4518-bc83-386ef55416f8.mov

https://user-images.githubusercontent.com/43996225/210688565-b85d0f8f-d7e0-48ae-b5b3-84cbda4072af.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672852094448169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01226a954977211217</li>
        <li>Upwork Job ID: 1610968589634461696</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
I can take a look at this one.

**Comment by jatinsonijs** [comment]
@yuwenmemon I have found root case of this issue during testing. If you want I can post here. I'm asking bcz this issue is Internal and not allowed for external contributors.

**Comment by jatinsonijs** [comment]
What I have found is 

 we have added ReportFooter with loading state view. 
 In this PR https://github.com/Expensify/App/pull/13523

/src/pages/home/ReportScreen.js
```
 <>
      <ReportActionsSkeletonView containerHeight={this.state.skeletonViewContainerHeight} />
      <ReportFooter shouldDisableCompose isOffline={this.props.network.isOffline} />
</>
```

We are not passing report in this case. Due to report not exist ReportFooter will use default prop
/src/pages/home/report/ReportFooter.js
LN: 52
report: {reportID: '0'},

and it will pass down to ReportActionCompose
```
<ReportActionCompose
    onSubmit={this.props.onSubmitComment}
    reportID={this.props.report.reportID.toString()}
    reportActions={this.props.reportActions}
    report={this.props.report}
    isComposerFullSize={this.props.isComposerFullSize}
    disabled={this.props.shouldDisableCompose}
/>
 ```
   
   On component mount inside ReportActionCompose updateComponent function will trigger and it will call 
     ```
   // The draft has been deleted.
        if (newComment.length === 0) {
            Report.setReportWithDraft(this.props.reportID, false);
        }
       ```
        
   Now in this case new incorrect report record will created with report_0: { hasDraft: false }
   
   It will impact condition of check room name already exist or not
  
  ```
  function isExistingRoomName(roomName, reports, policyID) {
    return _.some(
        reports,
        report => report && report.policyID === policyID
        && report.reportName === roomName,
    );
}
```

app has incorrect report record report_0: { hasDraft: false }

so it will check report exist true, 
report.policyID === PolicyID will be true bcz both are undefined bcz we don't have default value of room name.
report.reportName === roomName will be true bcz both are undefined.

**Comment by fedirjh** [comment]
I think we should add validation as @0xmiroslav stated , we also have change this block to `if else` statement , the second validation is overwriting the first one

https://github.com/Expensify/App/blob/dee9ac5915ba6d50c6360ce6ed8602c7fd97bba0/src/pages/workspace/WorkspaceNewRoomPage.js#L84-L92

```diff
         // We error if the user doesn't enter a room name or left blank
+        // We error if the room name already exists.
         if (!values.roomName || values.roomName === CONST.POLICY.ROOM_PREFIX) {
             errors.roomName = this.props.translate('newRoomPage.pleaseEnterRoomName');
-        }
-
-        // We error if the room name already exists.
-        if (ValidationUtils.isExistingRoomName(values.roomName, this.props.reports, values.policyID)) {
+        } else if (ValidationUtils.isExistingRoomName(values.roomName, this.props.reports, values.policyID)) {
             errors.roomName = this.props.translate('newRoomPage.roomAlreadyExistsError');
         }

```

and for validation [here](https://github.com/Expensify/App/blob/dee9ac5915ba6d50c6360ce6ed8602c7fd97bba0/src/libs/ValidationUtils.js#L386-L391) I think this is enough 

```diff
 function isExistingRoomName(roomName, reports, policyID) {
-    return _.some(
+    return roomName && _.some(
         reports,
         report => report && report.policyID === policyID
         && report.reportName === roomName,
```

**Comment by dhairyasenjaliya** [comment]
Is this issue open for external? @yuwenmemon

**Comment by yuwenmemon** [comment]
This was fixed with: https://github.com/Expensify/App/pull/13994

Also yes FYI @dhairyasenjaliya @fedirjh @0xmiroslav @jatinsonijs I appreciate the input but do please understand that this issue was tagged **Internal** and not marked either **External** or **Help Wanted**.

**Comment by yuwenmemon** [comment]
I believe that's correct @0xmiroslav but I will defer to @NicMendonca on that point.

**Comment by fedirjh** [comment]
@yuwenmemon I think this has not been fixed yet , now with this #13994 It will always skip the first validation , I still think that validation to same input field should go through an `if - else` : 

1. `if (empty) shows empty error`
2. `else if (invalid name) shows invalid error`
3. `else if (used name) shows already used error`
4. `else if (reserved name) shows reserved error`

I think we can also add this rule to [FORMS](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md) docs.

**Comment by yuwenmemon** [comment]
@fedirjh that's a good observation. I'll make that change, and we can work with @NicMendonca to ensure you get a bug reporting bonus.

**Comment by NicMendonca** [comment]
@fedirjh can you please apply to the job[ here](https://www.upwork.com/jobs/~0155f8c6bfc4758a90)?

**Comment by fedirjh** [comment]
@NicMendonca Thank you, accepted!

**Comment by NicMendonca** [comment]
@fedirjh paid the reporting bonus - thanks!

**Comment by yuwenmemon** [comment]
@NicMendonca @0xmiroslav is correct :+1:

**Comment by NicMendonca** [comment]
@0xmiroslav can you please accept the job offer?

**Comment by NicMendonca** [comment]
Ah, Thank you, I've created a new milestone 😄 Paid for $250

**Comment by NicMendonca** [comment]
bonuses have both been paid ✅

**Comment by thesahindia** [comment]
Hey @NicMendonca, C+ review compensation is due (sorry for the late comment).

**Comment by thesahindia** [comment]
Bump @NicMendonca

**Comment by NicMendonca** [comment]
@thesahindia can you accept the job offer, please?

**Comment by NicMendonca** [comment]
@thesahindia paid!

**Comment by thesahindia** [comment]
I think this can be closed now?
