### ISSUE TITLE
[HOLD for Regression Test] Infinite loading while opening IOU request details deeplink

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. From account A, copy the link of report action, try to open it. Login into account B, open that link.
3. Notice that it opens the Detail page with the infinite loading.

## Expected Result:
There should be an error view if can't find the report.

## Actual Result:
The Detail page keep loading forever.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.48-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210691639-c9738124-3be8-4a4a-8472-37043ab6036d.mp4

https://user-images.githubusercontent.com/43996225/210691692-3a66a1bd-3ec2-46b0-83ca-45e88f5146cc.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672825776826619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6fc36c1e19d5eaa</li>
        <li>Upwork Job ID: 1610968221768388608</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
I can take a look at this one.

**Comment by mollfpr** [comment]
The IOU is `undefined` on account B and we only show the loading spinner when it happens.

https://github.com/Expensify/App/blob/8c675d4d5dfc0407dadb7ae5c750547564606f65/src/pages/iou/IOUDetailsModal.js#L149

https://github.com/Expensify/App/blob/8c675d4d5dfc0407dadb7ae5c750547564606f65/src/pages/iou/IOUDetailsModal.js#L157-L187

---

The loading spinner could be replaced with `FullPageNotFoundView`.

<img width="916" alt="Screen Shot 2023-01-05 at 19 56 33" src="https://user-images.githubusercontent.com/25520267/210785156-4675bbe1-bd51-4075-8bbd-8b39060c25e5.png">

@yuwenmemon

**Comment by mollfpr** [comment]
The PR is on staging 🚀

**Comment by greg-schroeder** [comment]
https://www.upwork.com/jobs/~01b6fc36c1e19d5eaa

@hungvu193
@mollfpr

Do you mind applying for the job? Message me when you do so I can accept the application. 👍

**Comment by mollfpr** [comment]
@greg-schroeder Accepted!

**Comment by mollfpr** [comment]
@greg-schroeder Applied!

**Comment by hungvu193** [comment]
@greg-schroeder just applied:D

**Comment by greg-schroeder** [comment]
Accepting apps now, will take care of payment

**Comment by greg-schroeder** [comment]
Okay hired! @mollfpr @hungvu193

**Comment by mollfpr** [comment]
Thanks, @greg-schroeder I have accepted the offer!

**Comment by greg-schroeder** [comment]
Paid. Will work on regression test now

**Comment by greg-schroeder** [comment]
Filed issue for test
