### ISSUE TITLE
[HOLD for payment 2023-01-13] C+ payment for internal PR review

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#14015]
Can we please pay out $1000 to @mananjadhav for their review in this PR https://github.com/Expensify/App/pull/13329

This will be once the PR is after the 7 days regression period. thank you!

**Comment by stephanieelliott** [comment]
Deployed to prod on 1/6, will issue payment on 1/13

**Comment by stephanieelliott** [comment]
I sent you the offer @mananjadhav, please accept when you get a chance!

**Comment by mananjadhav** [comment]
Accepted @stephanieelliott

**Comment by stephanieelliott** [comment]
All paid up! Thanks @mananjadhav
