### ISSUE TITLE
Set a reasonable min supported Android version 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#14014]
### Problem
We currently support Android devices as far back as Android 5.0. This is very old and requires that we support devices used by less than <1% of our users. This requires additional support for old versions, and sometimes requires that we implement specific code to handle old and new/Android versions differently.

[Android SDK useage](https://apilevels.com/)

### Solution

Set a reasonably valid supported Android version, based on the current amount of users on lower Android versions. Perhaps Android 7 is a good starting point. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fedc73e1218c2523</li>
        <li>Upwork Job ID: 1610955297230606336</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
On hold for now

**Comment by Julesssss** [comment]
Not a priority

**Comment by Julesssss** [comment]
Still not a priority

**Comment by Julesssss** [comment]
Same as above. We talked about this in slack and will likely target 8.0

**Comment by Julesssss** [comment]
Same as above

**Comment by Julesssss** [comment]
Okay, so Android 7.0 still seems like a reasonable minimum supported version: 

<img width="556" alt="Screenshot 2023-07-19 at 16 51 28" src="https://github.com/Expensify/App/assets/10736861/b427f24b-c3cb-4a99-b160-e43021cfd0f5">


<img width="1072" alt="Screenshot 2023-07-19 at 16 49 44" src="https://github.com/Expensify/App/assets/10736861/6003f13e-5ac6-4f21-b685-1de249d1e3a2">

**Comment by Julesssss** [comment]
I'm just not sure we have a true problem here yet...

**Comment by Julesssss** [comment]
No change

**Comment by Julesssss** [comment]
Thank you, I commented on the PR.

**Comment by shubham1206agra** [comment]
Update: RN 0.73 may make minimum sdk version to 23. 
Since https://github.com/facebook/react-native/pull/39671 just got into 0.73.0-rc.5

**Comment by Julesssss** [comment]
Thanks, Android 7.0 (SDK 23) seems reasonable 👍

**Comment by Julesssss** [comment]
No recent updates

**Comment by Julesssss** [comment]
We have discussing SDK 23 as a reasonable minimum [here](https://github.com/Expensify/App/issues/30732#issuecomment-1900125791)

**Comment by mrousavy** [comment]
I'd say 23 is definitely reasonable.

**Comment by Julesssss** [comment]
No current need to bump the min version.

**Comment by mrousavy** [comment]
Yup, VisionCamera V4 will work on minSdk 21

**Comment by Julesssss** [comment]
No need for this bump yet

**Comment by Julesssss** [comment]
Closing, we'll create a new issue for discussion when we actually need to make a bump
