### ISSUE TITLE
[HOLD App Navigation Reboot] React navigation StackNavigator causes screen content to load slowly

### ISSUE THREAD

**Issue by chrispader** [Expensify/App#14036]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
(long lasting LoadingIndicators on many screens)
## Action Performed:

1. Open app
2. Go to "Search"/"New Chat"/"New Group" screen (any Screen that renders an `OptionsSelector`)
3. Wait for the loading spinner to end

## Expected Result:
After the screen transition is done, the screen content should render relatively fast.

## Actual Result:
Instead, even after the screen transition has ended a `LoadingIndicator` keeps spinning for a few (milli-)seconds.

That's because the `OptionSelector` component is waiting for the `transitionEnd` event to be emitted by `react-navigation`. ([here](https://github.com/Expensify/App/blob/3afaaf5349f562dc4a1e38eda285ffdcd68132b3/src/components/ScreenWrapper/index.js#L40)) The transition will end at earliest though, once the screen content is rendered completely.

## Workaround:
This is not blocking any flow.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.49-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** christoph+hightraffic@margelo.io | iPhone 14 Pro (Simulator)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron & @chrispader 
**Slack conversation:** https://expensify.slack.com/archives/C035J5C9FAP/p1669856870089949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chrispader** [comment]
@marcaaron could you add that issue here: https://github.com/Expensify/App/issues/11768

**Comment by jliexpensify** [comment]
Hi @marcaaron did you want a job created and @chrispader hired?

**Comment by marcaaron** [comment]
No the issue is just on hold for now thanks @jliexpensify

**Comment by jliexpensify** [comment]
@marcaaron if this is on HOLD, could this be updated to a Weekly or Monthly?

**Comment by marcaaron** [comment]
Yes 👍

**Comment by jliexpensify** [comment]
Still on hold

**Comment by jliexpensify** [comment]
On hold

**Comment by jliexpensify** [comment]
Not overdue, on HOLD

**Comment by jliexpensify** [comment]
Not overdue, on HOLD

**Comment by jliexpensify** [comment]
Still on hold

**Comment by mountiny** [comment]
@chrispader I think this one can be closed now, please correct me if I am wrong.
