### ISSUE TITLE
Settings - Timezone is highlighted with a blue background

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com
2. Login with any account
3. Navigate to Settings > Profile
4. Click Timezone

## Expected Result:
The timezone in the search field should not be highlighted

## Actual Result:
Timezone is highlighted with a blue background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] Windows / Chrome

**Version Number:** 1.2.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210880425-89397bb8-b183-4c2e-a9df-fd409a0e3cb2.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af8ef889509b6e67</li>
        <li>Upwork Job ID: 1611124354362830848</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I think this is the expected behavior. You can see the same behavior in the [PR](https://github.com/Expensify/App/pull/12201) that introduced this feature ~1 month ago.

**Comment by luacmartins** [comment]
Closing. Please reopen if this is not expected!
