### ISSUE TITLE
[HOLD for payment 2023-01-19] [$1000] Tooltip is not centered when hovering the < (back icon) on modals

### ISSUE THREAD

**Issue by bondydaa** [Expensify/App#14043]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the + icon to create a new IOU
2. Click `Request Money`
3. Enter an amount and click next
4. Hover over the `<` icon at the top of the drawer that slides out and notice the tooltip

Alternatively:
1. Open the app
1. Go to Setting
1.Go to Profile
1. hover on the back button

## Expected Result:
The tooltip should be centered 

## Actual Result:
The tooltip is slightly askew 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** v1.2.48-2, v1.2.49-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/4073354/210903655-d28b8367-87aa-4d11-b81b-44b4a711cf68.png">
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/4073354/210903685-27800318-c4f3-4cc5-ab68-90ea33370c6e.png">

**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672817918639959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Proposal for solution is here: https://github.com/Expensify/App/issues/13940#issuecomment-1371332290
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159b4566d0eb1cb3d</li>
        <li>Upwork Job ID: 1611154096654839808</li>
        <li>Last Price Increase: 2023-01-06</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@daraksha-dk can you comment your proposal over to this follow-up issue so we can assign it to you? Thanks!

**Comment by Pujan92** [comment]
@daraksha-dk Can we also fix one more use case here of Actions(+) tooltip in the composer?  @bondydaa @eVoloshchak can confirm that.

<img width="1059" alt="Screenshot 2023-01-09 at 11 51 19 AM" src="https://user-images.githubusercontent.com/14358475/211251004-5ff09dce-45ca-4fb4-84c4-50b8f37a584e.png">

**Comment by Pujan92** [comment]
> Want to report it on the slack channel and we can get another issue spun up for it, feel free to tag me in the message and I'll try to help stream the process. Did you already look into it and determine if it's basically the same solution of adjusting margins, maybe adding a containing view?

Yes @bondydaa, View is already there but need to set margin to the View and remove it from the Tooltip direct child to make it center.

**Comment by trjExpensify** [comment]
Okay, so this one is due for payment soon. Confirming those as: 

- $1,500 to @eVoloshchak for the C+ review incl. 50% bonus for a 3-day merge
- $1,750 to @daraksha-dk for the fix incl. 50% bonus for a 3-day merge and $250 for reporting the issue.

I've sent you both offers on this job [here](https://www.upwork.com/jobs/~0159b4566d0eb1cb3d). Can you accept? I'm away from tomorrow until Wednesday next week, but let @JmillsExpensify know if we're ready to settle up ahead of that and I'm sure he can help out. 

As for the checklist.. @bondydaa @eVoloshchak can you address the first three, please? For the item on me: 

>[@trjExpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

I don't think a regression test is necessary here, as a visual issue like this will be organically tested by Applause throughout various other flows when navigating in NewDot. Ticking it off, but let me know if you don't agree.

**Comment by JmillsExpensify** [comment]
Cool I'll temporarily assign myself to make sure it's on my radar.

**Comment by eVoloshchak** [comment]
Looking for the offending PR

**Comment by JmillsExpensify** [comment]
@trjExpensify is coming back tomorrow and I haven't gotten to this yet, so I'm going to leave this for him at this point. Thanks for the explanation above by the way!

**Comment by trjExpensify** [comment]
I'm baaack! Taking this over again. Made the payments, and closing it out.
