### ISSUE TITLE
 console error displayed when clicking on archived workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14091]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create a workspace
2. wait for assigning expensify specialist to that workspace
3. delete a workspace
4. go to archived workspace

## Expected Result:  
should not show any console error

## Actual Result:  
shows console error `[Onyx] An error occurred while applying merge for key: report_1355144964678015, Error: TypeError: Cannot convert undefined or null to object`clicking on archived workspace

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Windows / Chrome 

**Version Number:** 1.2.50-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211107729-15433d41-a6d3-4617-83bf-93878ae906a4.mov

https://user-images.githubusercontent.com/43996225/211107769-282ceea0-bfff-4362-9b77-44182a0b5fd9.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672988003994539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment]
I don't get that specific error when I follow those steps: 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/28715117/212360966-c367ebfa-11fb-49cf-b031-2be8c78e9fb0.png">

**Comment by miljakljajic** [comment]
Applying the `Needs reproduction label` to see if anyone else can reproduce this error.

**Comment by yuwenmemon** [comment]
I'll give it a look!

**Comment by miljakljajic** [comment]
How's it going @yuwenmemon - did you manage to have a look at this yet?

**Comment by yuwenmemon** [comment]
And by today I mean ... _today_

**Comment by yuwenmemon** [comment]
Sorry. Keep getting new things thrown at me each morning. Will look at this tomorrow I promise!

**Comment by yuwenmemon** [comment]
Not seeing this error anymore in dev or prod. See what happens when you wait! The stuff works itself out 😅 

https://user-images.githubusercontent.com/4741899/215212932-be23009f-3484-46f8-8235-76af53584f2b.mp4
