### ISSUE TITLE
 Scroll bar appears when first visit app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Google Chrome on Windows
2. Go to https://staging.new.expensify.com/
3. If already visited, clear cache or press Ctrl + F5

## Expected Result:
Scroll bar should not appear before loading main page

## Actual Result:
Scroll bar appears even though no content to scroll (screen before the login screen)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows / Chrome

**Version Number:** v1.2.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211127353-e6ab1453-1349-4b0e-b4bc-8dcb53ba4551.mp4

![image](https://user-images.githubusercontent.com/43996225/211127356-a7e65f47-5837-4b45-9687-facf03338241.png)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673014680749599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@0xmiroslav and @kavimuru, I wasn't able to replicate this. I used a Microsoft Surface device with Windows 11, opening the staging link in a brand new Guest window. Could you please share new steps for reproducing this error?

https://user-images.githubusercontent.com/59587260/212785458-1f765e77-f193-4e04-9927-9e136a7b4ff5.mp4
