### ISSUE TITLE
Web - LHN - Pinned conversation in offline jumps after returning online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Navigate to a conversation that is not near the top on the LHN list
3. Disable the internet connection
4. Click on the pin icon on the top right
5. Verify the conversation is now pinned to the top of LHN
6. Refresh the page
7. Enable the internet connection - you might need to refresh the page in Web
8. Verify the conversation is still pinned to the top of LHN (maintaining the same pinned status)

## Expected Result:
The conversation is still pinned to the top of LHN

## Actual Result:
Pinned conversation in offline jumps after returning online

## Workaround:
Unknwn

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] We / Chrome

**Version Number:** 1.20.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211177743-49ecd83d-9490-479b-87f0-b05e6b841b23.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interna Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
will look into this tomorrow

**Comment by sophiepintoraetz** [comment]
Hmm, I wasn't able to reproduce this on v1.2.52-4 - @kbecciv I've followed your reproduction steps but I don't think this is reproducible? Closing but reopen if you think I'm wrong!
![2023-01-12_16-16-43 (1)](https://user-images.githubusercontent.com/42940078/211967920-eb52c897-6b83-4126-80f8-9032c58aef90.gif)

**Comment by kbecciv** [comment]
Issue is not reproductible any more.

https://user-images.githubusercontent.com/93399543/213007599-d6337881-3f50-4391-ad23-9fd33663a5b2.mp4
