### ISSUE TITLE
iOS - Request money -Unable to submit a request money to a user who does not have an existing account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open app
2. Log in account ([applausetester+0704sveta@applause.expensifail.com/w323052760We
3.Click the green + icon and select request money
4. Enter an amount and click next
5. Enter the email address of a user that doesn't have an existing account and request $x to confirm and send the request
Example: (andreylazutkinutest+070115@gmail.com)

## Expected Result:
Request money sent to a user who does not have an existing account

## Actual Result:
Unable to submit a request money to a user who does not have an existing account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS app

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211177943-716d8650-5a99-442b-b98c-4ecc8e20db2b.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
@kbecciv - Cannot reproduce in iOS in production

https://user-images.githubusercontent.com/14225673/211437582-55e149ae-807a-442d-aa94-2ec75df9cb08.MP4
