### ISSUE TITLE
[HOLD for payment 2023-01-23] [Core Branding] Design follow ups for Help Site

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#14124]
Now that the help site has a fresh coat of paint, let's follow up with a few design improvements that were not implemented in the original issue. 

1. Let's update the h1 font on each page to use our new headline font, Expensify New Kansas. <img width="1509" alt="image" src="https://user-images.githubusercontent.com/2319350/211210726-ceb78dab-ab5f-4eca-8999-a93465158316.png">
2. Let's add link :hover styes to the sidebar links, using the same :hover color/style we use in the rest of the app: <img width="256" alt="image" src="https://user-images.githubusercontent.com/2319350/211210754-85edb96a-87e1-4b73-9bbf-a25077c3b98f.png">
3. When viewports are skinny, let's make the text on the left side of a nav button flow to two lines to make sure the arrow stays on the right: <img width="309" alt="image" src="https://user-images.githubusercontent.com/2319350/211210781-b661e573-4ec1-4b41-add7-0b7fbb559a8d.png">
4. Let's make sure these buttons are the same width on desktop: <img width="771" alt="image" src="https://user-images.githubusercontent.com/2319350/211211000-eed4a882-5f07-4dc5-97cc-943654ae5ab7.png">

cc @Luke9389 @luacmartins @marcochavezf @grgia 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd32b16dab72ecc4</li>
        <li>Upwork Job ID: 1616471919600939008</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I haven't worked with our help site yet and this seems like a good opportunity to get started!

**Comment by shawnborton** [comment]
Awesome, thanks Carlos!

**Comment by luacmartins** [comment]
@shawnborton maybe I'm missing something, but I don't think we have any hover styles in App. Was there any specific style for #2?

https://user-images.githubusercontent.com/22219519/211432732-cac9614b-71a5-4889-aab5-70a426ac947c.mov

**Comment by grgia** [comment]
I think for the sidebar links hover colors, it would follow of of the LHN or menuItem styles?

https://user-images.githubusercontent.com/38015950/211435934-a0f0aa92-8aa2-403c-a8e3-68189feb75fd.mov

**Comment by shawnborton** [comment]
I was thinking that links would have a simple color change behavior on hover. 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2319350/211503384-c293a9b7-b3ec-4679-bb0a-b7e8fb2b7905.png">

**Comment by shawnborton** [comment]
And yeah, my bad - I could have sworn our links had that hover style in the App.

**Comment by luacmartins** [comment]
@shawnborton [these colors](https://github.com/Expensify/App/issues/14124#issuecomment-1376913891) are different than the current light-blue (#8DC8FF) we are using in the helpsite. Should I update the current light-blue color to match the ones above or add them as new colors for the links?

**Comment by luacmartins** [comment]
Discussed 1:1 with Shawn and the correct colors are:

```
colors-link: '#5AB0FF',
colors-link-hovered: '#B0D9FF',
```

**Comment by mallenexpensify** [comment]
Added `Bug` label to assign BZ for payment

**Comment by shawnborton** [comment]
Not overdue

**Comment by luacmartins** [comment]
The PR has been in prod for a week now. Are we still waiting on payments?

**Comment by shawnborton** [comment]
Good question - @mallenexpensify or @michaelhaxhiu do you know the answer to that?

**Comment by mallenexpensify** [comment]
Hired @Santhosh-Sellavel can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01bd32b16dab72ecc4

**Comment by Santhosh-Sellavel** [comment]
Done @mallenexpensify!

**Comment by mallenexpensify** [comment]
@Santhosh-Sellavel paid, closing!
