### ISSUE TITLE
Significant performance improvements get flagged as deploy blockers

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#14123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Merge a PR that causes a statistically significant improvement in our of our performance metrics.

## Expected Result:
The PR should not be marked as a deploy blocker, the new baseline average should adjust.

## Actual Result:
The PR is marked as a deploy blocker.

## Workaround:
Remove the blocker (not possible for non-Expensify employees).

## Platforms:
GH Actions

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
cc @AndrewGable @hannojg: https://github.com/Expensify/App/pull/13714#issuecomment-1374087433

**Comment by roryabraham** [comment]
@flaviadefaria no need to make any upwork job for this, it should be addressed by @hannojg when he's back from vacation.

I also think we can make this a weekly. After all, it's not every day when we make statistically significant performance improvements to the app.

**Comment by AndrewGable** [comment]
Yes, this is done. Let me know if you see it fail again and I am happy to look into it.
