### ISSUE TITLE
mWeb - New Room - 79 characters can be insert in room name instead 80 characters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13994

## Action Performed:
1. Go sto staging.new.expensify.com
2. Log in with expensifail account
3. Tab on Fub button
4. Tap New Room
5. Start typing room name with more than 80 characters

## Expected Result:
80 characters can be insert in room name

## Actual Result:
79 characters can be insert in room name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211229649-f0857116-a573-4389-a017-b17d37d0f711.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
Seems like we are counting the `#` as part of the room name, making it 80 characters including that one.

@lschurr, what do you think about this one? Should we increase the size by one or leave it as-is? (Id doesn't seem like a big deal either way)

**Comment by lschurr** [comment]
Hm, I don't think I have enough context to know if this should be fixed. Asking here: https://expensify.slack.com/archives/C049HHMV9SM/p1673283092238369

**Comment by JmillsExpensify** [comment]
@Gonals clarified that we're consistently counting characters, though we are including # as a character. I don't think we have a bug here as a result, because # is indeed a character.

**Comment by lschurr** [comment]
Sounds like we can close.. feel free to reopen if I'm wrong!
