### ISSUE TITLE
[HOLD for payment 2023-01-17] The text on the edit photo profile modal is not selectable

### ISSUE THREAD

**Issue by mollfpr** [Expensify/App#14121]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Regression from https://github.com/Expensify/App/pull/14048 and soon will be deploy blocker

## Action Performed:
- Login to an account
- Open the settings page
- Go to the profile page by clicking on the profile picture or the account email
- Click on the profile picture and click on the upload photo button
- Select an image from your computer and the upload photo modal will open
- Select the text on the modal `Drag, zoom, and rotate your image to your preferred specifications` by double click the text

## Expected Result:
The text will be highlighted

## Actual Result:
The text is not will be highlighted

## Workaround:
NA

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.2.50-13
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/25520267/211197460-899653de-db49-4022-900e-935eb173b9ef.mov

**Comment by francoisl** [comment]
Marking this a deploy blocker as discussed in the [fix PR](https://github.com/Expensify/App/pull/14115). There is already a staging checklist open so we'll need to CP the fix to staging.

**Comment by Julesssss** [comment]
I'm glad we have a PR open to resolve this unwanted change, but it hardly seems worthy of the deploy blocker label in my opinion. If the other blocker is resolved, I might remove the label here.

**Comment by Julesssss** [comment]
Okay, I resolved the only other blocker, so I'm going to remove the label here. Let's get it merged like a regular issue.

**Comment by mallenexpensify** [comment]
@mollfpr , @jatinsonijs should be added to OP for reporting this regression bug, correct? And they're due $250 for the report
https://github.com/Expensify/App/issues/13146#issuecomment-1384748198

**Comment by mallenexpensify** [comment]
@sophiepintoraetz I added
**Issue reported by:** @jatinsonijs 
Can you please hire and pay @jatinsonijs ?  Thx

**Comment by sophiepintoraetz** [comment]
[Done!](https://www.upwork.com/ab/applicants/1615915842788696064/job-details)

**Comment by sophiepintoraetz** [comment]
Payment is done so is there anything else keeping this issue open?

**Comment by francoisl** [comment]
I don't think so, let's close!

**Comment by jatinsonijs** [comment]
@mallenexpensify I have received reporting bonus, Thank you
