### ISSUE TITLE
mWeb/Chrome - Room - Header is hidden when creating a new room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log i with expensifail account
3. Tap on Plus button
4. Select New Room
5. Put name and select Workspace
6. Tap create room

## Expected Result:
Room header should be visible

## Actual Result:
Header is hidden when creating a new room

## Workaround:
Unknow

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211177994-25751489-588e-4ebe-bfbf-9ba4683c2158.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@kbecciv I wasn't able to follow the reproduction steps because there is no "new room" button. Could you please clarify which one you meant?

![image](https://user-images.githubusercontent.com/59587260/212601428-90def046-dee1-44f4-ae12-904b8dc9e971.png)

**Comment by kbecciv** [comment]
@kadiealexander New Room option is available only for Expensifail account.

**Comment by kadiealexander** [comment]
@kbecciv I was logged in with k.alexander@expensifail.com.

**Comment by kbecciv** [comment]
@kadiealexander New Room option is available for me ( used expensifail account)

![image](https://user-images.githubusercontent.com/93399543/212993530-22090b5c-e523-4008-a32c-8d7bc122525e.png)

**Comment by mvtglobally** [comment]
@kadiealexander Do you have a Workspace created? You will need a workspace o be able to create a room
