### ISSUE TITLE
[$1000] Details - The photo does not load after uploading a new avatar and clicking on details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13185

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go offline
4. Upload a new Avatar to your profile
5. Go online
6. Open any chat and open your own details.
7. Tap on the avatar 

## Expected Result:
The photo loads after uploading a new avatar and clicking on details

## Actual Result:
The photo does not load after uploading a new avatar and clicking on details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211235642-d2273e55-460c-4aeb-a6ba-72f5f74e30d8.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f73795750d847627</li>
        <li>Upwork Job ID: 1612490949757321216</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by thesahindia** [comment]
Will be fixed in https://github.com/Expensify/App/issues/12707
cc: @Beamanator

**Comment by neil-marcellini** [comment]
Thanks for pointing that out @thesahindia. I think we should add these reproduction steps to #12707 and close this issue. I'll let @Beamanator give the final thumbs up on that.

**Comment by Beamanator** [comment]
Good find @thesahindia 👍  Added reproduction steps to #12707 so we can close this out 👍
