### ISSUE TITLE
[$1000] Invite members : member name not appears after removing it from members list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > workspace > manage members
2. click on invite button
3. select the members and invite the members
4. go back to manage members page and remove all the members
5. again click on invite button

## Expected Result:
should show members which is removed

## Actual Result:
does not show members which was removed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.50-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211372431-6786b9e6-9e81-4d62-aed7-cd43af5e354e.mp4

https://user-images.githubusercontent.com/43996225/211372665-3c79cd0b-bd62-4d43-93a1-a7fd3dc79bbd.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672663518491199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121c07efbcabfcb3d</li>
        <li>Upwork Job ID: 1612508710850142208</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by s77rt** [comment]
@syedsaroshfarrukhdot Checking for errors does not make sense in this case, same thing for checking for offline state. I didn't add those intentionally.

**Comment by thesahindia** [comment]
>Checking for errors does not make sense in this case

@s77rt, can you explain a little about why this doesn't make sense. I think it's good to check for errors too 


@syedsaroshfarrukhdot, do you have any specific steps to repro the error case?

**Comment by s77rt** [comment]
### Proposal (Updated)
```diff
diff --git a/src/pages/workspace/WorkspaceInvitePage.js b/src/pages/workspace/WorkspaceInvitePage.js
index b8b2812b23..8a258cb5f6 100644
--- a/src/pages/workspace/WorkspaceInvitePage.js
+++ b/src/pages/workspace/WorkspaceInvitePage.js
@@ -108,7 +108,12 @@ class WorkspaceInvitePage extends React.Component {
     }
 
     getExcludedUsers() {
-        const policyMemberList = _.keys(lodashGet(this.props, 'policyMemberList', {}));
+        let policyMemberList = lodashGet(this.props, 'policyMemberList', {});
+        policyMemberList = _.filter(_.keys(policyMemberList), policyMember =>
+            this.props.network.isOffline
+            || policyMemberList[policyMember].pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE
+            || !_.isEmpty(policyMemberList[policyMember].errors)
+        );
         return [...CONST.EXPENSIFY_EMAILS, ...policyMemberList];
     }

```

### Update
Turns out that in `WorkspaceInvitePage` we also use `<OfflineWithFeedback />` and for that the filter must be based on 3 conditions:
1. Being offline
2. pendingAction is not delete
3. errors are not empty

Basically we need to exclude the users that are shown on the members page. (`WorkspaceMembersPage` also uses `<OfflineWithFeedback />`)

If we don't add the offline condition you will be able to invite a user that is still an actual member as seen in the following video:

https://user-images.githubusercontent.com/16493223/211647207-650cf7af-dab2-4e42-b55b-63f6fec4b563.mp4




This issue is very similar to this one https://github.com/Expensify/App/issues/13615 and we should opt for the same solution.

**Comment by syedsaroshfarrukhdot** [comment]
Update Proposal :- 

As per the problem highlighted by @s77rt with add the offline condition you will be able to invite a user that is still an actual member I have also added offline props in my proposal. This issue very similar but is some what different then in logic from https://github.com/Expensify/App/issues/13615. 

As I believe we would should exclude members from the list only and only if they don't have `pendingAction === delete` and they don't have `errors` in them. 

``` diff 
diff --git a/src/pages/workspace/WorkspaceInvitePage.js b/src/pages/workspace/WorkspaceInvitePage.js
index b8b2812b2..1240e99e1 100644
--- a/src/pages/workspace/WorkspaceInvitePage.js
+++ b/src/pages/workspace/WorkspaceInvitePage.js
@@ -108,7 +108,9 @@ class WorkspaceInvitePage extends React.Component {
     }
 
     getExcludedUsers() {
-        const policyMemberList = _.keys(lodashGet(this.props, 'policyMemberList', {}));
+        let policyMemberList = lodashGet(this.props, 'policyMemberList', {});
+        policyMemberList = _.filter(_.keys(policyMemberList), policyMember => (this.props.network.isOffline
+            || (policyMemberList[policyMember].pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && _.isEmpty(policyMemberList[policyMember].errors))))
         return [...CONST.EXPENSIFY_EMAILS, ...policyMemberList];
     }
```

@thesahindia the proposal was inspired from the accepted proposal https://github.com/Expensify/App/issues/13615 here. So I think it would be better to check for errors also along with it but I will work for the test case with errors and will update you if I find one specifically for it.

**Comment by Julesssss** [comment]
> > The fix is not to exclude members that are already queued to be deleted so we can add them again.
> 
> @Julesssss, is this what we want as the expected result?

Yeah, that makes sense to me

**Comment by thesahindia** [comment]
I like @s77rt's [proposal](https://github.com/Expensify/App/issues/14142#issuecomment-1377765165) 
> If we don't add the offline condition you will be able to invite a user that is still an actual member as seen in the following 

it was the first proposal to handle the offline case and I think @syedsaroshfarrukhdot's proposal will fail in the case where pending action is delete and there is an error.

C+ reviewed 🎀👀🎀

**Comment by s77rt** [comment]
Applied in [Upwork](https://www.upwork.com/jobs/~0121c07efbcabfcb3d).
[PR](https://github.com/Expensify/App/pull/14248) is ready.

**Comment by dylanexpensify** [comment]
Offer sent @s77rt !

@thesahindia will you apply when you get a chance?

**Comment by s77rt** [comment]
@dylanexpensify I received the payment but I think this was done automatically (15 days passed).

I think this issue is due payment anyway, right?

**Comment by Julesssss** [comment]
Hey @dylanexpensify, I;m a bit confused by this one. Do we need to pay out?

**Comment by dylanexpensify** [comment]
Sorry you all, don't know how I missed this!

**Comment by dylanexpensify** [comment]
Offers sent @thesahindia and @gadhiyamanan !

**Comment by gadhiyamanan** [comment]
@dylanexpensify Accepted

**Comment by dylanexpensify** [comment]
all done here, thanks all!

**Comment by dylanexpensify** [comment]
Ahh - thanks for your honesty there @thesahindia - requesting back the delta!

**Comment by s77rt** [comment]
@thesahindia I was confused too by your statement, I though we had a regression that I was not aware of 😅
@dylanexpensify I think I'm as well eligible for the timeline bonus ($500)

**Comment by dylanexpensify** [comment]
Hahaha, sorry team, I see - let me get you both sorted on your bonuses.

**Comment by dylanexpensify** [comment]
@thesahindia @s77rt I've sent both of you your bonus payments!

@thesahindia ignore refund request!
