### ISSUE TITLE
Manage member - Pointer appears when hovering over the select all checkbox when there are no users except admin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Select any workspace
2. Go to the manage members page
3. Remove all the members if any
4. Observe the select all row checkbox(cursor changes to pointer)

## Expected Result:
The checkbox should not be clickable and pointer events need to be none (as there is no user except admin)

## Actual Result:
Checkbox is clickable and cursor changes to pointer

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**  

https://user-images.githubusercontent.com/43996225/211387600-a57bea0e-ca2c-44ee-a374-0ab4c92b94ba.mov

https://user-images.githubusercontent.com/43996225/211387623-4f806146-7321-483e-804f-8836d053c057.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673210148886289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1671179784787169), we are changing this bahavior as part of [this issue](https://expensify.slack.com/archives/C01SKUP7QR0/p1672155840925419) and this issue will no longer exist.

Closing.
