### ISSUE TITLE
[HOLD for payment 2023-01-19] Don't add DeployBlocker label to performance regressions in meaningless changes

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#14159]
# Problem
This PR was labeled a deploy blocker due to a performance regression, however the regression was meaningless in absolute terms (+8.956ms). We discussed [here](https://expensify.slack.com/archives/C07J32337/p1673302597006939) that we don't care about these meaningless changes so we shouldn't apply the label.

# Why is this important
Prevents confusion and extra work to remove labels.

# Solution
Add a 🟡 emoji to meaningless changes
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f9ab7c2f49a4da</li>
        <li>Upwork Job ID: 1612578393923223552</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@luacmartins - do we need an Upworks job for this? I assume no?

**Comment by luacmartins** [comment]
Np! We'll handle this internally

**Comment by luacmartins** [comment]
I don't think the checklist is applicable since this is a new feature that we were still fine tuning and only affected our internal workflows. Closing this issue since there's no one to be paid.
