### ISSUE TITLE
Android- Connect Bank Account manually- Onfido flow doesn't have dark mode when adding bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14158]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log i with expensifail account
3. Go to Setting - WS - Connect Bank Account
4. Select Connect Manually
5. Add routing and account number
6. Go to Company page and add all necessary info
7. Go to personal Page and add all necessary info
8. Tap Nex button
9. Page will take you to Onfido flow

## Expected Result:
Onfido flow has dark mode when adding bank account

## Actual Result:
Onfido low doesn't have dark mode when adding bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native

**Version Number:** 1.2.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![android](https://user-images.githubusercontent.com/93399543/211420907-38b14108-dec8-4803-9106-6fdeee355a1d.jpg)

https://user-images.githubusercontent.com/93399543/211421568-f4c925df-89b6-4e28-89c5-bbfcce452abc.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
We are planning on moving to Onfido API so fixing this shouldn't be a priority - convo [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1673376562681349).
