### ISSUE TITLE
Connect Bank Account- user is taking back to WS setting when clicked on back button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Go to staging.new.expensify.com
2. Log i with expensifail account
3. Go to Setting - WS - Connect Bank Account
4. Select Connect Manually
5. Add routing and account number
6. Go to Company page and add all necessary info
7. Go to personal Page and add all necessary info
8. Go to next page
9. On Test Transaction page tap on back button

## Expected Result:
User is taking back to Personal Page when taped on back button.

## Actual Result:
Connect Bank Account manually - user is taking back to WS setting when taped on back button instead of Personal Page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome
- [ ] iOS / Safari
- [ ] Web / Chrome

**Version Number:** 1.2.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211417101-f2391d7f-eacc-4b63-ac64-13afa3e678b5.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Taking a look!

**Comment by garrettmknight** [comment]
Also referencing [this PR](https://github.com/Expensify/App/pull/13236) as it might change the behavior too.

**Comment by garrettmknight** [comment]
After discussing in [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1673357966547799), it makes more sense for the back button at Step 5 to navigate to the Connect Bank Account page. [This PR](https://github.com/Expensify/App/pull/13236) will fix.

**Comment by garrettmknight** [comment]
Deployed and the updated behavior is showing. Closing.
