### ISSUE TITLE
mWeb/Safari - Chat - No cursor when clicking "Edit comment".

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14165]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Navigate any conversation
4. Tap and hold (Mobile) to view the action menu
5. Tap on the Pencil icon to activate the edit message box

## Expected Result:
Сursor must be in the edit message box.

## Actual Result:
No cursor when clicking "Edit comment".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / Safari

**Version Number:** 1.2.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211430110-bbb9e8d8-03c1-45f4-ac26-e02a4cb47fb7.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Hm I'm confused a little by this one. Why would a cursor appear on mobile web? We never show a cursor/mouse-pointer on mobile web right?

**Comment by michaelhaxhiu** [comment]
@kbecciv mind helping clarify my question?

**Comment by kbecciv** [comment]
This issue happened ONLY in mWeb/Safari, rest environments have cursor when edit comment. 

**mWeb/safari vs IOS/ native**

https://user-images.githubusercontent.com/93399543/215125221-09c399b7-9551-4f5b-9895-cd115a517253.MP4
