### ISSUE TITLE
Chat - Extra lines appear after copy past text to chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login with any account
2. Open any chat
3. Copy text from file "carta familias 2.txt" attached to this report
4. Past to chat
**File** 
[carta familias 2.txt](https://github.com/Expensify/App/files/10377689/carta.familias.2.txt)

## Expected Result:
Text should be pasted without any extra lines appearing.

## Actual Result:
Extra lines appear after copy past text to chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.510

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211429846-d3f4030b-1d88-4f65-9ab3-3d188f813660.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
Hmmm. I don't think this is a bug. Most likely, this is an issue with the txt, rather than our app.
New lines and spaces are hidden special characters. That includes new paragraphs (extra space). I believe that .txt has new paragraphs, but the .txt format can handle them. In fact, if I delete the `new lines` and re-add them, we do not see this behavior anymore.

Pasting the text in Word also adds the paragraphs, confirming my theory. Closing.
