### ISSUE TITLE
[HOLD #11768] Screens are unmounting unnecessarily when navigating between them

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#14173]
On hold for https://github.com/Expensify/App/issues/11768

### Problem

All navigations are kinda unmounting the previous screen, e.g. when navigating from Main -> Chat the contacts list flashes and disappears (probably incorrect usage of react-freeze) [Slack ](https://expensify.slack.com/archives/C035J5C9FAP/p1673051341865969)

### Why is it important

Bad UX and more resource demanding for the device

### Solution

This is probably tied to react-freeze usage and it is a regression. This might get resolved by the navigation refactor so we gonna hold this on that issue.

**Comment by JmillsExpensify** [comment]
Thanks for creating the issue and also linking it in our doozy of a tracking issue!

**Comment by mountiny** [comment]
Not a priority

**Comment by mountiny** [comment]
On hoold

**Comment by mountiny** [comment]
on hold

**Comment by JmillsExpensify** [comment]
Still on hold.
