### ISSUE TITLE
[HOLD for payment 2023-01-30] Inconsistent period at the end of sentences

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and login
2. Click on  avatar
3. Upload an image above 6mb
4. Upload an image less than 80X80
 
## Expected Result:
attachmentPicker, avatarWithImagePicker and some other components have consistent (use dots or do not use dots) dots at the end of the error sentences

## Actual Result:
 attachmentPicker, avatarWithImagePicker and some other components have inconsistent dots at the end of the error sentences

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="561" alt="Снимок экрана 2023-01-09 в 06 22 57" src="https://user-images.githubusercontent.com/43996225/211639530-358dfd4f-e25a-48b1-bff6-f069d169fba3.png">
<img width="340" alt="4096" src="https://user-images.githubusercontent.com/43996225/211639535-0d0dc1ad-081b-4ddd-8d3f-26d24d6d80f7.png">
<img width="383" alt="6mb" src="https://user-images.githubusercontent.com/43996225/211639539-ea3da51c-08d9-4d44-95c4-5796ad0819d7.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/43996225/211639576-b7a8844b-18c4-4c92-ac0a-b3c913a6854d.png">
<img width="960" alt="1" src="https://user-images.githubusercontent.com/43996225/211639579-7918db8f-7024-4b3b-84a8-f8f48088000e.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oesayan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673264032632809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1847d2ba49aeb6d</li>
        <li>Upwork Job ID: 1612914450129612800</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Marked internal based on the linked thread.

**Comment by mountiny** [comment]
Gonna snatch this and ask Marketing team what consistency we want. I assume we want the sentences to end with punctuation, but just to double check before we more on :)

**Comment by zsgreenwald** [comment]
Are we just referring to the image notification, or are there any others?

**Comment by zsgreenwald** [comment]
If I understand correctly, its about the use of punctuation consistently whenever there's a message, and I agree I think we should always be using punctuation. 

If I'm missing something here, can you please elaborate?

**Comment by mountiny** [comment]
> If I'm missing something here, can you please elaborate?

I dont think you are missing anything, I will get a PR for this soon to go through the messages, which might not have punctuation.

**Comment by mountiny** [comment]
Unassigning @mollfpr As this is super simple PR which does not need C+. Thanks!

**Comment by oesayan** [comment]
Sorry to hijack, but I think I should be already be able to apply to the Upwork job? It is still locked for me.
Thank you!

**Comment by oesayan** [comment]
🤠

**Comment by mountiny** [comment]
Bumping this one, the automation here did not help since we had Reviewing label in place still. Sorry for the delay @oesayan @johncschuster

**Comment by johncschuster** [comment]
Thanks for the bump, @mountiny! Yep! I can take care of the reporting bonus. Standby!

**Comment by johncschuster** [comment]
@oesayan, can you apply to the job, [here?](https://www.upwork.com/jobs/~01e1847d2ba49aeb6d)

**Comment by oesayan** [comment]
@johncschuster just did (it was locked before), thank you!

**Comment by johncschuster** [comment]
Great! I've accepted your offer!

**Comment by johncschuster** [comment]
Paid! 🎉

**Comment by johncschuster** [comment]
@mountiny

> do you think this requires a regression test? there is lots of possible errors in the app, I am not sure if regression test can really cover all of them :/

Do you think we need to specifically include new flows to test the inconsistent period, or do you think the existing flows can more or less test for it?

**Comment by mountiny** [comment]
I think this is fine to leave for a regular Applause testing. Thank you very much for help, closing!
