### ISSUE TITLE
E/App issue to pay [Tracking] [Refactor] API Refactors #211669 

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#14203]
Creating this top pay internal issue  
https://github.com/Expensify/Expensify/issues/211669

@aimane-chnaif reviewed https://github.com/Expensify/App/pull/13456 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b04b5423c9f14256</li>
        <li>Upwork Job ID: 1612895659068436480</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01b04b5423c9f14256

@NikkiWines can you confirm @aimane-chnaif is due compensation for https://github.com/Expensify/App/pull/13456? Looks like it, just wanting bonus 👀 cuz the main E/E API refractor issue is a beast.

**Comment by NikkiWines** [comment]
> @NikkiWines can you confirm @aimane-chnaif is due compensation for https://github.com/Expensify/App/pull/13456? Looks like it, just wanting bonus 👀 cuz the main E/E API refractor issue is a beast. 

Yep definitely, @aimane-chnaif should be compensated for https://github.com/Expensify/App/pull/13456 👍

**Comment by mallenexpensify** [comment]
Thanks @NikkiWines and @aimane-chnaif .   All paid!
