### ISSUE TITLE
[HOLD for regression tests 2023-01-25] Font style inconsistency in some areas of the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Open Preferences page, User details page and create new chat screen

## Expected Result:
Small label style font should be consistent everywhere in the app. Ideally we want this to all be at our label size (13px) in our text supporting color using our regular weight font

## Actual Result:
There is a inconsistency in the label style

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="377" alt="image (4)" src="https://user-images.githubusercontent.com/43996225/211669646-6aae7ef9-5c20-46e2-960c-2d1e2fa7c9a2.png">
<img width="375" alt="image (3)" src="https://user-images.githubusercontent.com/43996225/211669648-0a03e1f8-28f8-48d3-8fe3-867a276afc32.png">
<img width="376" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/211669650-7d7b8a17-4103-490f-821a-db4a3f55b741.png">
<img width="374" alt="image (1)" src="https://user-images.githubusercontent.com/43996225/211669651-9dacd910-631b-45c2-8264-a9e70d3f7bbc.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1672827605509459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e365d5cd722c09e2</li>
        <li>Upwork Job ID: 1612961027488239616</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
PR ready for review - https://github.com/Expensify/App/pull/14217

**Comment by miljakljajic** [comment]
No one to be paid (Reported by Shawn, Worked on by Carlos). 

@shawnborton, would you say this [Edit Information in Profile](https://expensify.testrail.io/index.php?/cases/view/1971040&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229064) section would be the best place to add a test to check for font size? Given that from the [slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1672847636780949?thread_ts=1672827605.509459&cid=C01GTK53T8Q), the other sections will soon be refactored?

**Comment by shawnborton** [comment]
Hmm well I suppose the Edit Info in Profile page was already largely correct before this PR, we ended up changing the label font size in other places like Preferences, Payments, as well as the user selector in the Send/Request flows.

**Comment by miljakljajic** [comment]
Would it make more sense then to suggest we add a test that checks the font size across all those flows to confirm we're using the same one?

**Comment by shawnborton** [comment]
I think that could work, yeah. 

To be honest though, this wasn't really a bug. This was just a matter of the various phases of NewDot development happening at different times. For example, the user selector in the Send/Request flow was created a long long time ago it followed a mockup I made that used small letters in all caps and bold. Later on, we started a font in regular letters that wasn't all caps for these kinds of labels. So I would say that everything was implemented as according to the mockups, but over time, we (I) saw some inconsistency in how we were treating those moments and wanted to do something to make everything look consistent.

**Comment by miljakljajic** [comment]
Maybe it isn't really something we'd create a new test for, in that case. I will get some feedback from the rest of the team. Thank you!

**Comment by shawnborton** [comment]
Not overdue

**Comment by luacmartins** [comment]
Waiting on regression period!

**Comment by miljakljajic** [comment]
We've agreed we don't need a regression test for this case [here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1674496474122819?thread_ts=1672827605.509459&cid=C01GTK53T8Q)

Closing - thank you all!

**Comment by shawnborton** [comment]
Hmm, what does it look like with mb1 added to it? And to clarify, this is the hover state you are showing right?

**Comment by shawnborton** [comment]
Got it. It would be my preference to do .mb1 instead of .mb2. @luacmartins let me know what you think.

**Comment by luacmartins** [comment]
`.mb1` looks good to me too!

**Comment by luacmartins** [comment]
@fedirjh do we have a bug report for the issue? If not, can we create one? You can tag me in Slack.
