### ISSUE TITLE
Android - Attachment -Attachment appears with a long delay.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Disable the internet connection in the device
2. Navigate to a chat and upload an attachment
3. Enable the internet connection in the device

## Expected Result:
The attachment appears without any delay

## Actual Result:
Attachment appears with a long delay.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native

**Version Number:** 1.2.52.4

**Reproducible in staging?:**Yes

**Reproducible in production?:** Yes
 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211698216-fe23dddd-4d22-49cb-851b-eb0ef2857751.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Struggling to reproduce this one given I'm using internet for the android browserstack version.

**Comment by sophiepintoraetz** [comment]
Going to find someone with an android to test in APAC

**Comment by kadiealexander** [comment]
This was my experience following the reproduction steps. I'm not sure how instant it should be but the delay doesn't seem very long to me. 

https://user-images.githubusercontent.com/59587260/212803931-77c4c33f-47ba-47df-8d3b-02e49b2d005c.mp4

**Comment by sophiepintoraetz** [comment]
Thanks Kadie! I'm going to close this one out then.
