### ISSUE TITLE
[HOLD for payment 2023-01-20] (front-end) Sort reportActions by timestamp, then action type, then reportActionID

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#14211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem
If multiple reportActions of different types are created in the same millisecond, then there is currently nothing to guarantee that the `CREATED` action will appear first

### Solution
Update the reportActions sorting function to ensure that we sort by three criteria instead of two:

1. Timestamp first
1. Action type
1. reportActionID

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
PR is ready for review: https://github.com/Expensify/App/pull/14213

**Comment by mallenexpensify** [comment]
Should this have auto-closed @roryabraham  cuz it hit production a week ago? https://github.com/Expensify/App/pull/14213#issuecomment-1381720857

Also, doesn't look like C+ reviewed so no payment is due, right

**Comment by roryabraham** [comment]
Yep, looks like we're all set here
