### ISSUE TITLE
Chat - Multiple lines are appearing if message is copied by right-click and select to clipboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13739

## Action Performed:
1. Go to ND and login
2. Click on any chat in the LHN
3. Copy text
I'm around if you are and wanna hop on a call https://meet.google.com/yjx-maas-pku

Nothing specific in mind
4. Paste it without formatting into the chat composer user ctrl+shift+v
5. Verify that it still contains the 4 newlines and no more
6. Send the message
7. Copy the previous message by right-clicking the message and select copy it to clipboard
8. Paste it without formatting into the chat composer user ctrl+shift+v

## Expected Result:
Verify that it still contains the 4 newlines and no more

## Actual Result:
Multiple lines are appearing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome
- [ ] iOS / Safari
- [ ] Web / Chrome

**Version Number:** 1.2.52.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211698802-9435694c-3201-4948-8eb6-7e7eeeda33d7.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
<img width="683" alt="Screenshot 2023-01-11 at 6 57 26 PM" src="https://user-images.githubusercontent.com/1529980/211894089-96b51924-4f34-492c-b16d-450e9c17952f.png">

@kbecciv I couldn't reproduce on staging or prod - in both instances, the ctrl+shift+v into the chat composer maintained 4 lines and even after deleting and repasting like the video it didn't add any additional lines.

**Comment by Julesssss** [comment]
I agree with Garrett and also can't reproduce. Removing this as a deploy blocker from the checklist
