### ISSUE TITLE
OldDot - Free Policy - The WS Setting page closed itself and WS chat is loaded longer than expected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account and validate it
2. Navigate Setting - Policy - Group Policy
3. Select Free Policy and wait until the Chat is loaded ( taking too long)

## Expected Result:
The WS Setting page is not close itself and WS chat is loaded normal

## Actual Result:
The WS Setting page closed itself and WS chat is loaded longer than expected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome 

**Version Number:** 1.2.52.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** any new account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211700788-04dd3f6b-0a44-48f3-8dc6-49f6fd802c55.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Tested on staging and the chat loaded much more quickly than in the attached video. @kbecciv Can you give it another try and see if it's still slow?

**Comment by kbecciv** [comment]
@garrettmknight Did you try with new account?

**Comment by garrettmknight** [comment]
Yep:
1. Created a new account
2. Validated the account w/ code to email
3. Set password
4. Created a new free plan policy
5. RHN settings popped up and chat loaded quickly in the background
