### ISSUE TITLE
[$1000] The top-right and the bottom-right corner radius of mobile number text field doesn’t appear round in contrast to the other two edges

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

 1. Open any workspace
 2. Go to connect bank account
 3. Select connect manually option
 4. Fill routing and account number fields
 5. Complete company information section
 6. Add personal information (Issuing country and documents)
 7. Click on get secure link via sms
 8. Notice that the top-right and bottom-right corner radius are not round unlike top-left and bottom-left edges. Also, there should be margin between the text field and the send link button.

## Expected Result:
Every edge should be consistent with each other. (Top-left, Top-right, Bottom-left and Bottom-right edges should have the same corner radius)

## Actual Result:
Edges are not consistent, thereby having different corner radius.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![text field](https://user-images.githubusercontent.com/43996225/211924119-cece1833-ff23-4521-96f8-ccf3a1817e8d.png)
<img width="960" alt="sms link round shape" src="https://user-images.githubusercontent.com/43996225/211924327-f932653e-c2f1-4b58-becd-2cd37b78eece.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673370239027699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01534ffeb67249133a</li>
        <li>Upwork Job ID: 1654544225014804480</li>
        <li>Last Price Increase: 2023-05-05</li>
    </ul>
</details>

**Comment by anmurali** [comment]
I can reproduce this but when we [implement the Onfido API](https://github.com/Expensify/Expensify/issues/233363) we will take another look at this flow. So putting this bug on hold to be tested again when this is done.

**Comment by anmurali** [comment]
Not overdue but on hold for OnFido

**Comment by anmurali** [comment]
Trying to figure out our plan here as Onfido is punted for now

**Comment by anmurali** [comment]
Since Onfido SDK is here to stay, releasing the hold on these to fix

**Comment by Vishrut19** [comment]
Hey! If this issue is there then please give me a chance to work on it as I am very new here. Please give me a chance to contribute.
