### ISSUE TITLE
[$1000] Email address is being displayed on the IOU preview instead of the last name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open chat of a user that has set only last name (empty first name)
2. Click on the + icon
3. Click on Send Money
4. Enter any amount
5. Click Next
6. Click I'll settle up elsewhere

## Expected Result:
Last name is displayed on the IOU preview like it is displayed everywhere else

## Actual Result:
Email address is being displayed instead of the last name on IOU preview
In LHN it appears with Last name

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211938261-a72cf2a1-9230-45ab-97c7-c3789d432031.mov

https://user-images.githubusercontent.com/43996225/211938324-a844d7cf-f70b-4f28-b07d-6db1bf441253.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673426920016829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0d43c6a348fa48c</li>
        <li>Upwork Job ID: 1613588503429910528</li>
        <li>Last Price Increase: 2023-01-12</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Not a bug because the profile is incomplete so its reasonable to display the email of the user instead of surname

**Comment by MitchExpensify** [comment]
We're actually going to fix this in favor of the consistent pattern that exists today. Namely, showing the last name regardless of not having a first name saved

**Comment by MitchExpensify** [comment]
I sent money to an account with only a last name save and the last name still shows in LHN:

Web:
![image](https://user-images.githubusercontent.com/36425901/212136351-dcbc1396-2b95-4abf-9cc4-d2d730d6dc55.png)

Desktop app:
![image](https://user-images.githubusercontent.com/36425901/212136420-4a530532-cdaf-4c62-ba73-2bdcbc49ef72.png)

Labelling "Needs reproduction"

**Comment by MitchExpensify** [comment]
My mistake! This is indeed reproducible (I was looking at LHN versus the preview, my bad):

Web:
![image](https://user-images.githubusercontent.com/36425901/212137086-53d03fab-a0ed-468f-958e-c7d5794fbaa1.png)


Desktop app:
![image](https://user-images.githubusercontent.com/36425901/212137047-cd26a824-f430-4a30-9205-e1e2e8495b48.png)

**Comment by bernhardoj** [comment]
### **Proposal**

We can add another or condition to get the last name in case the first name is empty.

```diff
diff --git a/src/components/ReportActionItem/IOUPreview.js b/src/components/ReportActionItem/IOUPreview.js
index 1c997119d..1576ee9ba 100644
--- a/src/components/ReportActionItem/IOUPreview.js
+++ b/src/components/ReportActionItem/IOUPreview.js
@@ -120,7 +120,7 @@ const IOUPreview = (props) => {
 
     const managerName = lodashGet(props.personalDetails, [managerEmail, 'firstName'], '')
                         || Str.removeSMSDomain(managerEmail);
-    const ownerName = lodashGet(props.personalDetails, [ownerEmail, 'firstName'], '') || Str.removeSMSDomain(ownerEmail);
+    const ownerName = lodashGet(props.personalDetails, [ownerEmail, 'firstName'], '') || lodashGet(props.personalDetails, [ownerEmail, 'lastName'], '') || Str.removeSMSDomain(ownerEmail);
     const managerAvatar = lodashGet(props.personalDetails, [managerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(managerEmail);
     const ownerAvatar = lodashGet(props.personalDetails, [ownerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(ownerEmail);
     const cachedTotal = props.iouReport.total && props.iouReport.currency

```

**Comment by bernhardoj** [comment]
Using display name will show both first name and last name, but I think we only want to show either the first or the last name (or email if both empty).

**Comment by sobitneupane** [comment]
>Using display name will show both first name and last name, but I think we only want to show either the first or the last name (or email if both empty).

@bernhardoj I think so.

But IOU Quote must also be updated accordingly.
<img width="893" alt="Screenshot 2023-01-13 at 00 12 26" src="https://user-images.githubusercontent.com/25876548/212148993-d866e6ae-3401-4f30-9293-b9bbdcbf6f4b.png">

I am not sure if it is possible to change IOUQuote message from front end.

**Comment by Pujan92** [comment]
I think this(IOU message) also needs to update with the last name, right?

<img width="666" alt="Screenshot 2023-01-12 at 11 57 13 PM" src="https://user-images.githubusercontent.com/14358475/212149238-f0a160d5-917d-4f23-ac2a-b0b73687486a.png">

**Comment by bernhardoj** [comment]
Yeah, I think the message IOU quote is composed on the backend. Here is the params example when we send money through `SendMoneyElsewhere` api.

```
{"chatReportID": "1989942874938753", "clientID": 83, "iouReportID": "6320334089970635", "newIOUReportDetails": "{\"amount\":100,\"currency\":\"IDR\",\"requestorEmail\":\"bernhard.josephus+0000@gmail.com\",\"comment\":\"\",\"idempotencyKey\":\"2302bd1b-fb87-4bf9-9530-ef9fc36fe019\"}", "paymentMethodType": "Elsewhere", "reportActionID": "8939369918308593365", "transactionID": "2870947001874360238"}
```

Anyway, I have an updated proposal which I will post on the next comment.

**Comment by bernhardoj** [comment]
### **Updated Proposal**

We can simplify the condition with just `firstName` and `displayName`

```diff
diff --git a/src/components/ReportActionItem/IOUPreview.js b/src/components/ReportActionItem/IOUPreview.js
index 1c997119d..b90d9ce42 100644
--- a/src/components/ReportActionItem/IOUPreview.js
+++ b/src/components/ReportActionItem/IOUPreview.js
@@ -119,8 +119,9 @@ const IOUPreview = (props) => {
     const isCurrentUserManager = managerEmail === sessionEmail;
 
     const managerName = lodashGet(props.personalDetails, [managerEmail, 'firstName'], '')
-                        || Str.removeSMSDomain(managerEmail);
-    const ownerName = lodashGet(props.personalDetails, [ownerEmail, 'firstName'], '') || Str.removeSMSDomain(ownerEmail);
+                        || lodashGet(props.personalDetails, [managerEmail, 'displayName'], '');
+    const ownerName = lodashGet(props.personalDetails, [ownerEmail, 'firstName'], '') 
+                        || lodashGet(props.personalDetails, [ownerEmail, 'displayName'], '');
     const managerAvatar = lodashGet(props.personalDetails, [managerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(managerEmail);
     const ownerAvatar = lodashGet(props.personalDetails, [ownerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(ownerEmail);
     const cachedTotal = props.iouReport.total && props.iouReport.currency
```
If first name is empty, then display name will only contains either last name or email.

Or,

we can use an existing function to get the name which basically do the same as above.

```diff
diff --git a/src/components/ReportActionItem/IOUPreview.js b/src/components/ReportActionItem/IOUPreview.js
index 1c997119d..7f9844de7 100644
--- a/src/components/ReportActionItem/IOUPreview.js
+++ b/src/components/ReportActionItem/IOUPreview.js
@@ -118,9 +118,8 @@ const IOUPreview = (props) => {
     // Pay button should only be visible to the manager of the report.
     const isCurrentUserManager = managerEmail === sessionEmail;
 
-    const managerName = lodashGet(props.personalDetails, [managerEmail, 'firstName'], '')
-                        || Str.removeSMSDomain(managerEmail);
-    const ownerName = lodashGet(props.personalDetails, [ownerEmail, 'firstName'], '') || Str.removeSMSDomain(ownerEmail);
+    const managerName = ReportUtils.getDisplayNameForParticipant(managerEmail, true)
+    const ownerName = ReportUtils.getDisplayNameForParticipant(ownerEmail, true)
     const managerAvatar = lodashGet(props.personalDetails, [managerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(managerEmail);
     const ownerAvatar = lodashGet(props.personalDetails, [ownerEmail, 'avatar']) || ReportUtils.getDefaultAvatar(ownerEmail);
     const cachedTotal = props.iouReport.total && props.iouReport.currency
```

**Comment by sobitneupane** [comment]
@robertjchen We might need to handle it backend (at least partially) since change in IOUQuote message might not be possible at the front.

**Comment by robertjchen** [comment]
@sobitneupane Got it! That makes sense, I can look into the backend changes- appreciate the discussion here. @bernhardoj 's updated proposal looks good to me 👍

**Comment by sobitneupane** [comment]
Yes, for the frontend change we can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/14228#issuecomment-1381221060) of using existing `ReportUtils.getDisplayNameForParticipant()` function.

**Comment by MitchExpensify** [comment]
@sobitneupane @adeel0202 @bernhardoj [invited to Upwork here](https://www.upwork.com/jobs/~01e0d43c6a348fa48c)! Thanks

**Comment by bernhardoj** [comment]
Should I open the PR now?

@sobitneupane @robertjchen

**Comment by bernhardoj** [comment]
Okay. I thought I need to wait for the assignment first 😅. PR is ready.

**Comment by robertjchen** [comment]
Looks like the change went out to prod last week, going to remove the `Reviewing` label to move this forward to the next step of the process.

**Comment by robertjchen** [comment]
It seems like we may be past the 7-day regression period? cc: @MitchExpensify for clarification on next steps 🙏

**Comment by MitchExpensify** [comment]
All paid out! Thanks everyone
