### ISSUE TITLE
Additional Page -  Incorrect error message for entering 9 fake numbers for SSN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14251]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13170
Attached another video with `Send Money` flow as in the PR and issue is reproducible.
## Action Performed:
1. Go to NewDot and login with expensifail account
2. Go to https://staging.new.expensify.com/enable-payments
3. Fill up the correct information in all the fields in Additional info page with SSN 1234
4. Close the form
5. Visit again https://staging.new.expensify.com/enable-payments
6. Enter 1234 in SSN field and click "Save & continue , then prompted to set all 9 digits of the SSN
7. Enter 123456789 and click save & continue

## Expected Result:
 Correct error message is showing for entering 9 fake numbers for SSN

## Actual Result:
 Incorrect error message for entering 9 fake numbers for SSN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.53.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Bug5893695_13170.mp4…

https://user-images.githubusercontent.com/43996225/212183306-ca1095a0-233a-47d4-88e4-ea60664c15c4.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@lschurr Issue occurs with `send money` flow too

https://user-images.githubusercontent.com/43996225/212183014-4ab718b4-397c-446e-bd66-334bdca022c1.mp4

**Comment by luacmartins** [comment]
@kavimuru what is the correct error message? From the videos, it seems like this is the expected behavior. The user has a valid 4 digit SSN, and we display the server-side error above the submit button.

**Comment by joelbettner** [comment]
This is the desired behavior for the SSN.

The user entered 4 numbers of the SSN. The back end returns an error that we need the entire 9 digits of the SSN for this particular user. We display that message above the "Submit" button. We do not display an error in the SSN field unless the user attempts to submit again without the 9 digits.

Closing this issue.

**Comment by joelbettner** [comment]
For more context, see step 10 of the QA/tests here: https://github.com/Expensify/App/pull/13170

**Comment by kavimuru** [comment]
@joelbettner  Step 13 and Step 14 error messages are different
