### ISSUE TITLE
[HOLD #13807][$1000] No line-height provided to normal text when written in combination with code block (3 backtick block)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Write text plus 3 backtick code block in single message as shown in video
4. Inspect the sent message and inspect normal text message

## Expected Result:
Text in the message should have line-height:20px

## Actual Result:
Line height is not set for text which leaves no gap between text and code block (3 backtick block)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212204774-ae99f8ea-1fe1-4d11-8c3a-04f54ee3afbc.mov

https://user-images.githubusercontent.com/43996225/212204781-024ed826-4f82-475d-a990-9f1e9a520291.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673539333784169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b8ae11aee601d05</li>
        <li>Upwork Job ID: 1613988373079359488</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Reproduced and this checks out.

**Comment by jayeshmangwani** [comment]
### Proposal

we should add line height 20 to pre tag here

https://github.com/Expensify/App/blob/f06b625880c963840d4c46eafadd1af0cdffd21c/src/styles/styles.js#L103-L112

```diff
+            lineHeight:  variables.fontSizeNormalHeight
```

https://user-images.githubusercontent.com/35371050/212414858-dc0bb053-0a51-441f-845d-dd3912d63763.mov

**Comment by abdulrahuman5196** [comment]
**Proposal**

I am not sure if we can set separate line-heights for lines and quotes in single message. I think instead we can set margin for quotes to solve the issue of text and quote nearby.

```diff
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -107,8 +107,8 @@ const webViewStyles = {
             paddingRight: 8,
             paddingLeft: 8,
             fontFamily: fontFamily.MONOSPACE,
-            marginTop: 0,
-            marginBottom: 0,
+            marginTop: 5,
+            marginBottom: 5,
         },

```

I have set margin to 5, instead we can try other values as well.

**Comment by bernhardoj** [comment]
This is possibly fixed in https://github.com/Expensify/App/issues/13807

**Comment by s77rt** [comment]
I agree with @bernhardoj this seems already being fixed in #13807 (I tested and I can confirm this will be auto fixed)
We should at least put this issue on hold.

**Comment by thesahindia** [comment]
@PauloGasparSv, let's close this.

**Comment by PauloGasparSv** [comment]
Closing this off as the padding/height issue really seems to fixed by that P.R!

<img width="300" alt="image" src="https://user-images.githubusercontent.com/6564265/214622765-37ff4d0f-36d5-4951-9872-4dbe75b315ad.png">
