### ISSUE TITLE
 Keyboard doesn’t appear when selecting user the second time.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Open app, login with any account
2. In LHN, Tap on a user that you haven’t chatted before, notice that Keyboard opens. Click back button, click on that user again.
3. Notice that the Keyboard doesn’t show.

## Expected Result:
Keyboard should show if you click on user that you haven’t chatted before.

## Actual Result:
The Keyboard doesn’t show on the second times

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:**  v1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212225992-981be41a-6c56-47e0-b157-982c66f3c13a.MP4

https://user-images.githubusercontent.com/43996225/212226038-5a51eea2-5d4d-4547-b88d-b5c52b14cfad.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673539212428209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Not sure this is unexpected behavior actually, or if we want to change this. If you open a new chat with someone, they're added to the chat switcher and so behave like a stashed chat does.

**Comment by muttmuure** [comment]
Commented in the thread https://expensify.slack.com/archives/C049HHMV9SM/p1674221836615159?thread_ts=1673539212.428209&cid=C049HHMV9SM

**Comment by muttmuure** [comment]
Not overdue, going to discuss in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
We agreed that this isn't a bug.
