### ISSUE TITLE
[PAYMENT - 01-26] Double Tapping On Invite Button Navigates Back To The Selected WorkSpace Menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings
2. Select Workspaces
3. Click On Invite User
4. Select User To Invite
5. Double Tap On Invite Button

## Expected Result:
It should navigate navigate to Manage Members Screen

## Actual Result:
It navigates user back to Workspaces

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212368205-f3893b5b-98f9-4803-825a-56ce9c1e5e0f.mp4

https://user-images.githubusercontent.com/43996225/212368343-b774dd72-c1ff-4dc7-85d1-1c0338ee1219.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @syedsaroshfarrukhdot 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673578313575849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb6bd6d09d862e08</li>
        <li>Upwork Job ID: 1613998991762903040</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
PR [up](https://github.com/Expensify/App/pull/14298)

**Comment by jliexpensify** [comment]
Invited @eVoloshchak via Upworks

**Comment by luacmartins** [comment]
@jliexpensify as you pointed out via 1:1, @sobitneupane was the reviewer for this PR, so I'm reassigning this issue. Sorry about the confusion everyone!

**Comment by jliexpensify** [comment]
Invited @sobitneupane , sorry Eugene!

**Comment by jliexpensify** [comment]
Looks like @sobitneupane qualifies for the bonus

**Comment by sobitneupane** [comment]
@jliexpensify It was an internal PR. Are internal PR reviews eligible for bonus?

**Comment by jliexpensify** [comment]
Good question - let me check that, given it's an internal one. Thanks Sobit!

**Comment by jliexpensify** [comment]
Ok, my mistake @sobitneupane - just a flat rate. Sorry!

**Comment by luacmartins** [comment]
Are we still waiting on payments?

**Comment by jliexpensify** [comment]
I'm OOO tomorrow but will pay once I'm online again

**Comment by jliexpensify** [comment]
Just hired Sobit, once he accepts I'll sort out $

**Comment by syedsaroshfarrukhdot** [comment]
@jliexpensify Pinging for reporting bonus.

**Comment by syedsaroshfarrukhdot** [comment]
> @syedsaroshfarrukhdot - this is you, right?
> 
> ![image](https://user-images.githubusercontent.com/30815269/214958277-65899873-56db-4803-aea4-012c3ac617c1.png)
> 
> 

Yes

**Comment by syedsaroshfarrukhdot** [comment]
Thanks for invitation just accepted the offer.

**Comment by sobitneupane** [comment]
> Just hired Sobit, once he accepts I'll sort out $

Thanks @jliexpensify. Accepted the offer.

**Comment by jliexpensify** [comment]
Paid Sobit, just waiting on Syed to accept. Cheers!

**Comment by syedsaroshfarrukhdot** [comment]
> Paid Sobit, just waiting on Syed to accept. Cheers!

Accepted.

**Comment by jliexpensify** [comment]
Paid, and job closed. Thanks Sobit and Syed!
