### ISSUE TITLE
[HOLD for payment 2023-01-26] Default optional personal message on Invite new members page of Workspace is not changing to new selected language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Setting - Workspaces - Manage Members - Invite new members
2. Observe the optional personal message
3. Change language in another session
4. Observe the optional personal message

## Expected Result:
Optional personal message should be changed to new selected language

## Actual Result:
Optional personal message is not changing to new selected language

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212429746-43d10012-277a-4725-ad69-634dde5e28a2.mov

https://user-images.githubusercontent.com/43996225/212429758-33c6c084-3906-4e5c-b07b-a49e1c38cff8.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673627256241399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01452be321cfa781fc</li>
        <li>Upwork Job ID: 1615118407270477824</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
PR deployed to prod yesterday

**Comment by luacmartins** [comment]
Not overdue. Waiting for the regression period.

**Comment by luacmartins** [comment]
Still waiting for regression!

**Comment by davidcardoza** [comment]
Payment sent

**Comment by mollfpr** [comment]
@davidcardoza accepted thanks!

**Comment by varshamb** [comment]
@davidcardoza waiting for contract of Reporting bonus.

**Comment by davidcardoza** [comment]
@varshamb offer sent.

**Comment by varshamb** [comment]
@davidcardoza Offer accepted.

**Comment by davidcardoza** [comment]
Paid

**Comment by mollfpr** [comment]
@davidcardoza, mine is still hanging 😅

**Comment by davidcardoza** [comment]
Paid
