### ISSUE TITLE
[$1000] Add missing skin tones for handshake emoji

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#14302]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open emoji picker
2. Scroll to handshake (or search for it)
3. Change your skin tone to the darkest shade
4. See that the emoji stays yellow

## Expected Result:
The emoji skin tone is the shade you picked

## Actual Result:
The emoji is yellow

## Workaround:
No

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.51
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** All
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image](https://user-images.githubusercontent.com/42391420/212422485-9bc042af-787a-4ab8-88d9-73968837b2bb.png)

**Expensify/Expensify Issue URL:** n/a
**Issue reported by:** @abdulrahuman5196
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671716760354049?thread_ts=1671716674.530379&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01523d2c03834a76c9</li>
        <li>Upwork Job ID: 1614012452453519360</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
cc @abdulrahuman5196

**Comment by stitesExpensify** [comment]
Coming from this post https://github.com/Expensify/App/issues/13818#issuecomment-1378191741

If you can make another proposal here for posterity that would be great

**Comment by esh-g** [comment]
### Proposal

Solution:
```diff
diff --git a/assets/emojis.js b/assets/emojis.js
index 9a5a2f289..15e8747b0 100644
--- a/assets/emojis.js
+++ b/assets/emojis.js
@@ -2259,6 +2259,10 @@ const emojis = [
             'meeting',
             'shake',
         ],
+        types: [
+            "🤝🏾",
+            "🤝🏿",
+        ]
     },
     {
         name: 'pray',

```
A simple solution

**Comment by esh-g** [comment]
Well that was unfortunate I guess. But anyway, congratulations @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Thank you @stitesExpensify  for opening the issue. 
Providing the proposal from https://github.com/Expensify/App/issues/13818#issuecomment-1377170408 to add the shades for handshake icons.

```diff
--- a/assets/emojis.js
+++ b/assets/emojis.js
@@ -2259,6 +2259,13 @@ const emojis = [
             'meeting',
             'shake',
         ],
+        types: [
+            '🤝🏿',
+            '🤝🏾',
+            '🤝🏽',
+            '🤝🏼',
+            '🤝🏻',
+        ],
     },
```

**Comment by abdulrahuman5196** [comment]
@stitesExpensify  Created a PR for the fix - https://github.com/Expensify/App/pull/14308

**Comment by mananjadhav** [comment]
@abdulrahuman5196 Before I can review the PR can you please update the checklist properly for the PR.

@stitesExpensify @MitchExpensify  Question, why is the scope limited to handshake? why not include other composite emojis like the following?

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3069065/212462519-0a15660e-0f94-45f2-8337-4aa4956c4f21.png">

**Comment by abdulrahuman5196** [comment]
@mananjadhav  I have updated the PR content link, and added a question in the PR. Kindly have a look into it.

>Question, why is the scope limited to handshake? why not include other composite emojis like the following?
It seems currently we unicodes are not available for family composites - Discussed the same on the original issue -https://github.com/Expensify/App/issues/13818

For reference, Even slack doesn't have shades for family emojis.

**Comment by mananjadhav** [comment]
Thanks for the update @abdulrahuman5196. Good to go, I've reviewed the PR. @stitesExpensify @nkuoch All yours to merge.

**Comment by MitchExpensify** [comment]
> Question, why is the scope limited to handshake? why not include other composite emojis like the following?

Good question. It seems like the default skin tone is not expected to be applied to the "family" group of emojis similarly to how the emoji facial expressions don't change based on default skin tone. Whereas all the hand emojis apart from :handshake: change so that feels like a bug.

**Comment by MitchExpensify** [comment]
Invites sent to @abdulrahuman5196 & @mananjadhav

Reminder to myself to pay the reporting bonus as a bonus on @abdulrahuman5196  Upwork contact

**Comment by abdulrahuman5196** [comment]
@MitchExpensify  I would also be eligible for 50% bonus, right? The PR was merged within 3 business days.

**Comment by MitchExpensify** [comment]
> I would also be eligible for 50% bonus, right?

Yes! I'll include that when paying

**Comment by abdulrahuman5196** [comment]
@MitchExpensify  Thank you. I had already accepted the offer 🤩

**Comment by mananjadhav** [comment]
@MitchExpensify @stitesExpensify This one is ready for payout as it was deployed on Jan 18, 2023. Can you please help me with the same? Please note, this is also eligible for the timeline bonus.

**Comment by MitchExpensify** [comment]
All paid out with necessary bonuses! Thanks everyone

**Comment by mananjadhav** [comment]
@MitchExpensify I received the payout but it doesn't have the timeline bonus.

**Comment by MitchExpensify** [comment]
Sorry about that! Paying now

**Comment by MitchExpensify** [comment]
Done @mananjadhav

**Comment by mananjadhav** [comment]
Received the bonus. Thanks for the prompt action!

**Comment by abdulrahuman5196** [comment]
Thank you @stitesExpensify @MitchExpensify  @mananjadhav
