### ISSUE TITLE
Phone number without any email  are searchable by '@expensify.sm'

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open search
3. Create new user with random phone number
4. Open search again and now search with '@expensify.sm'

## Expected Result:
Newly created user using just phone number should not be displayed in results while searching '@expensify.sm' or any substring of that term

## Actual Result:
Newly created user is displayed throughout the search term '@expensify.sm'

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212493087-3032d7bc-c8ce-45c5-a188-20ad803a8b8d.mp4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/212493116-0d5ee93b-297d-4498-bef9-7df1dcdf3636.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673701996087249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Reviewing now

**Comment by greg-schroeder** [comment]
Hmm. Expensify accounts created with a phone number are always provisioned as `phonenumber@expensify.sms`, so searching by that string should pull those up, no?

**Comment by greg-schroeder** [comment]
Hey @johnmlee101 - what do you think about this? I'm not sure if this is something we need to pursue or not. 🤔

**Comment by johnmlee101** [comment]
@expensify.sms shouldn't really be surfaced to the user since its all sneakily done behind the scenes, so I don't think there's much expectation that searching that should do _anything_. I vote we do nothing.

**Comment by greg-schroeder** [comment]
I tend to agree. I think I'm gonna close.
