### ISSUE TITLE
 Login - Error message "This set password link is invalid ..." doesn't appear

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14310]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout of NewDot
2. Log into OldDot with any account and add a Secondary Login from Account Settings e.g. [mypersonal+validateTest@gmail.com](mailto:mypersonal+validateTest@gmail.com)

3. Open validate secondary log in email change to http://staging.new.expensify.com/v/
go to Desktop App
4. Navigate to the compiled link
5. Enter your password and login
6. Log out to NewDot
7. Reuse the link created in step 3

## Expected Result:
Verify you're redirected to Login>Password page with an error message displayed below the password field stating: "This set password link is invalid or has expired..."

## Actual Result:
The error message "This set password link is invalid or has expired..." doesn't appear. Able to log in if reuse the link a second time.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Desktop

**Version Number:** v1.2.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/3072058
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1044" alt="Bug5896005_Login_second" src="https://user-images.githubusercontent.com/43996225/212490350-f888b06c-5001-4c42-be6b-214fc7cc3e68.png">

https://user-images.githubusercontent.com/43996225/212490351-76c23c63-3461-4390-88b9-0af1a52bd30d.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Hi @kavimuru! Apologies, but I don't understand the reproduction steps. Could you please add more detail to explain what to do during each step? I think examples of the "compiled link" from step 4 would be helpful here.
