### ISSUE TITLE
[HOLD for payment 2023-01-26]  inconsistent privacy policy label on workspace connect bank account page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any workspace.
2. Go to Connect bank account.
3. At bottom there is Privacy policy link with label Privacy.

## Expected Result:
Privacy policy label should be consistent across app.

## Actual Result:
Most of the page have label “Privacy policy” but On Connect bank account it is “Privacy”

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="379" alt="Screenshot 2023-01-06 at 9 59 36 AM" src="https://user-images.githubusercontent.com/43996225/212491097-b81c7ce6-fa1f-45c9-8409-3fb7601bfe5e.png">
<img width="379" alt="Screenshot 2023-01-06 at 9 59 25 AM" src="https://user-images.githubusercontent.com/43996225/212491099-4ee7b76d-c360-4ed8-a37f-236f3c459de2.png">

https://user-images.githubusercontent.com/43996225/212491106-56e86ab2-2d36-4f65-b777-a3179f12658b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672979672715059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce48a7188b0db994</li>
        <li>Upwork Job ID: 1615098321100943360</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
PR [up](https://github.com/Expensify/App/pull/14335)

**Comment by luacmartins** [comment]
I changed the C+ to @thesahindia since they got assigned the PR review

**Comment by luacmartins** [comment]
I'm not sure there was any one PR that introduced this. We just used different copy through development, so I'd say that we can check off those steps here.

**Comment by luacmartins** [comment]
Not overdue. Waiting for the regression period.

**Comment by kadiealexander** [comment]
https://www.upwork.com/jobs/~01ce48a7188b0db994 - @thesahindia and @jatinsonijs could you please both apply here so I can issue payment?

**Comment by kadiealexander** [comment]
@luacmartins and I agreed that this does not require an update to TestRail, as it is more a case of polishing inconsistencies than a bug to be fixed.

**Comment by jatinsonijs** [comment]
> https://www.upwork.com/jobs/~01ce48a7188b0db994 - @thesahindia and @jatinsonijs could you please both apply here so I can issue payment?

applied

**Comment by kadiealexander** [comment]
Awesome, have sent you both contracts.

**Comment by kadiealexander** [comment]
Everyone has been paid 🎉
