### ISSUE TITLE
[$1000] Console error on clicking the close button in a password protected pdf popup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14315]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to any chat >send password protected pdf
2. click on the pdf
3. click the close button before load the pdf

## Expected Result:
should not show console error

## Actual Result:
 shows console error Uncaught (in promise) Error: Worker was terminated  click on close button

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** v1.2.54-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212495971-e3eea23f-d69c-4355-ba42-90c66231d8ab.mov

https://user-images.githubusercontent.com/43996225/212497009-73560e6b-2483-4a73-9ed6-61130fd1786a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673535124037299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ad0e7210d0c6170</li>
        <li>Upwork Job ID: 1614912435095961600</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I think these are related GHs:
https://github.com/Expensify/App/issues/14265
https://github.com/Expensify/App/issues/13929

I can't seem to reproduce this Console error so asking @dylanexpensify for a little help!

**Comment by Christinadobrzyn** [comment]
Awesome, with Dylan's help I could reproduce this with the following steps. 

- Go to https://staging.new.expensify.com in a browser
- Find an existing chat
- Click '+' > Add Attachment > attach a password protected PDF 
- click Send
- Click on the sent attachment in the chat
- Close the popup window before it loads
- Console shows error
![2023-01-16_16-56-52 (1)](https://user-images.githubusercontent.com/51066321/212639146-05bd6a52-fb6d-474d-b8ba-c68bd91bcd44.gif)

Given this, I'm not sure if this is a priority and if this will be fixed with this browser resize job - https://github.com/Expensify/App/issues/13929

adding external label to get the opinion of eng & C+

**Comment by s77rt** [comment]
That error message is from https://github.com/mozilla/pdf.js/blob/master/src/core/worker.js#L147-L151

I think it's expected to see that message if you are interpreting the pdf renderer, not something that should be fixed IMO

**Comment by Christinadobrzyn** [comment]
Thanks @s77rt! I kinda feel like this doesn't need to be a job at this time. @madmax330 or @thesahindia would you have input on closing this?
