### ISSUE TITLE
 Red dot appears on account avatar when the workspace delete button is pressed multiple times

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Create a workspace
2. Go to Settings > Workspaces
3. Open workspace
4. Press on the three vertical dots icon
5. Press Delete workspace
6. Press Delete multiple times

## Expected Result:
Red dot does not appear on the account avatar

## Actual Result:
Red dot appears on the account avatar

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.54-2
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212750647-af2c8b24-f7ef-44a2-83c4-31000d4bc162.mp4

https://user-images.githubusercontent.com/43996225/212750762-4a36927a-ef7f-41b9-9566-c684c5dcee45.mp4

 
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673799860371849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Grabbing it as internal

**Comment by marcochavezf** [comment]
PR up [here](https://github.com/Expensify/App/pull/14412).

**Comment by miljakljajic** [comment]
@adeel0202 I sent you a contract on upwork for the reporting bonus, please accept!
