### ISSUE TITLE
Showing strikethrough on informative label (edited) when message deleted offline.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat room.
2. Send new message.
3. Edit newly sent message.
4. Turn off network (Go offline).
5. Delete message.

## Expected Result:
Shouldn’t show strikethrough on (edited) label as it is just information not actual text.

## Actual Result:
Display strikethrough on (edited) label.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212744589-789e5023-d5e3-4361-b03f-c0df771de243.mp4

https://user-images.githubusercontent.com/43996225/212744728-248ffa4b-b80c-4f18-83d7-334742f9c5d2.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jatinsonijs 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673794815864249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
The strikethrough was added by @jasperhuangg 
https://github.com/Expensify/App/issues/13986#issuecomment-1379658717

I'm closing this one in favor of the original https://github.com/Expensify/App/issues/13986
