### ISSUE TITLE
AutoSearch not able to nested scroll fetched results 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14323]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to any workspace settings
3. Navigate to Connect Bank Account -> Connect Manually -> Enter Step 1 Data
4. On Step-2 -> Search On Company address -> Try to scroll inside fetched addresses
5. Notice Can’t able to scroll fetched addresses

## Expected Result:
Should be able scroll fetched addresses (nested)

## Actual Result:
Cannot scroll fetched addresses (nested)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212734273-a6eda722-97d0-463b-b2c2-9c93af836761.mov

https://user-images.githubusercontent.com/43996225/212734399-91c208d1-e180-4577-ba5b-568dbb8c200b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673763251000449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Was able to reproduce pretty easily, I think this is weird behavior and should be fixed.

**Comment by youssef-lr** [comment]
This is the default behavior for the library we use to search for addresses, and it's a limitation from Google which only returns 5 results per query, so there isn't any other results we can scroll to. The workaround is to let the user type more to get more relevant suggestions without having to scroll. More details [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/104#issuecomment-276506126). 

Closing!
