### ISSUE TITLE
Curly brackets turn into square brackets while editing workspace’s name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log with any account
2. Go to Workspace => Workspace Settings, change your workspace name to “{}” press Save.
3. Notice that the workspace name in the header turns into “[]”

## Expected Result:
 Workspace name in the header should be the same with TextInput.

## Actual Result:
The workspace name in the header turns into “[]”

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212776803-0c219736-728e-402b-9135-bb85500d9066.mp4

https://user-images.githubusercontent.com/43996225/212776812-e5750c30-21f0-4b33-bc13-4ffdd47ba658.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673877466933099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cf3148ee47f836a</li>
        <li>Upwork Job ID: 1615148714773934080</li>
        <li>Last Price Increase: 2023-01-17</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
When you force the app offline, it keeps the name as `{}`. Only once you go online does the name get updated to `[]`, so it looks like this is a back-end issue.

**Comment by puneetlath** [comment]
I looked into this a bit more and I think there's not really much we can do here and it's not really a bug since this isn't a realistic workspace name that someone would want to use. Going to go ahead and close, but feel free to reopen if you disagree!
