### ISSUE TITLE
Web/Windows 10/Chrome -The hands in the handshake emoji has different colors

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14356]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14308

## Action Performed:
1. Go to staging.new.expensify.com
2. Log i with any account
3. Click on emoji selector
4. Select darker skin tones
5. Scroll the emojis and search for handshake emoji

## Expected Result:
The hands in the handshake emoji has the same colors

## Actual Result:
The hands in the handshake emoji has different colors

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows 10 / Chrome 

**Version Number:** 1.2.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212930857-d75647ac-45f9-4e67-9852-0a30a717bf32.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
This issue only affect Windows 10/ Chrome.

On Windows 11 Pro - no issue with this emoji. 
 
**Windows 11 Pro/Chrome**

![image](https://user-images.githubusercontent.com/93399543/212931319-370f7d65-81a4-42e4-a470-24594c3538d1.png)

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
I'm not sure what is the issue here; this seems to be expected behavior, no? 

The emojis should default to the selected skin tone.

https://user-images.githubusercontent.com/31258516/212967251-c06d3869-14a8-42ba-a72b-948c31b65e7b.mp4

**Comment by kbecciv** [comment]
@isabelastisser This issue is affect only Windows 10/Chrome.

**Comment by isabelastisser** [comment]
Hey @kbecciv, I cannot reproduce this on Chrome and don't have access to do so on Windows.

Additionally, this seems to be a minor aesthetic issue that might be related to accessibility in Windows and can't be replicated in Chrome.

I will, however, bring this up for discussion in Slack before applying the `External` label or closing the issue.

Thanks!

**Comment by isabelastisser** [comment]
Asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673985799774629).

**Comment by mountiny** [comment]
Agreed, this is not a bug!

**Comment by isabelastisser** [comment]
Thanks @mountiny !
