### ISSUE TITLE
Web- IOU - The cursor disappears after selecting a payment method then a blue bar appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14296

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Click on + icon and choose sent money or request money
4. Enter amount and click on next button
5. Type whitespaces in the What’s it for? input
6. Choose any Payment method
7. Back to the What’s it for? input

## Expected Result:
The cursor should be displayed after selecting a payment method and no blue bar appears

## Actual Result:
The cursor disappears after selecting a payment method then a blue bar appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [x] Windows / Chrome 

**Version Number:** 1.2.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212932953-9ac90d29-dbfd-4567-9c27-345f1bbb46fc.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interna Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
@kbecciv - can you post this bug in #expensify-bugs to confirm it's not a duplicate report? 

please see the contributor guidelines for more info on which Slack channels you should be a part of - https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by maddylewis** [comment]
once you've posted the bug report to #expensify-bugs, please link the conversation and reopen the issue - thanks!

**Comment by kbecciv** [comment]
@maddylewis Sorry, I don't have power to post the issue in #expensify-bugs.

**Comment by maddylewis** [comment]
@kbecciv - ah, those instructions are in the Contributor Guidelines linked above :) 

```
Slack channels

All contributors should be a member of two Slack channels:

#expensify-open-source -- used to ask general questions, facilitate discussions, and make feature requests.
#expensify-bugs -- used to discuss or report bugs specifically.
Before requesting an invite to Slack please ensure your Upwork account is active, since we only pay via Upwork (see [below](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions)). To request an invite to these two Slack channels, email [contributors@expensify.com](mailto:contributors@expensify.com) with the subject Slack Channel Invites. We'll send you an invite!

Note: the Expensify team will not be able to respond to direct messages in Slack.

Note: if you are hired for an Upwork job and have any job-specific questions, please ask in the GitHub issue or pull request. This will ensure that the person addressing your question has as much context as possible.
```

**Comment by kbecciv** [comment]
I am from Applause QA team :)

**Comment by maddylewis** [comment]
ok ok ok my apologies. ill get this one handled today.

**Comment by maddylewis** [comment]
i am able to reproduce this, but I'm not sure it's a bug. i would expect the blank space to be highlighted if I click that field before completing a payment. 

https://user-images.githubusercontent.com/38016013/217330131-279c7b9a-2cbf-444f-9a9d-c53d450c352e.mp4

**Comment by maddylewis** [comment]
confirmed this is not considered a bug here - https://expensify.slack.com/archives/C01SKUP7QR0/p1675794707603569
