### ISSUE TITLE
[Fabric] Android -Chat- First letter is shaking in composed box

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14367]
## Action Performed:
1. Scan the code and install the build
2. Log in with account
3. Select any use
4. Type first letter

## Expected Result:
App should not be shaking

## Actual Result:
 First letter is shaking in composed box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native

**Version Number:** 1.2.49.0 

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211161704-a8da9fb5-1230-4ea7-ba91-0d210e9103cb.mp4

**Issue reported by:** Applause - Internal Team

**Comment by JmillsExpensify** [comment]
This issue is part of the on-going Fabric migration.

**Comment by JmillsExpensify** [comment]
This is not a daily and part of a longer-term project.

**Comment by j-piasecki** [comment]
This should be fixed by https://github.com/WoLewicki/App/commit/cc97ee44ad6b3b3dda7017a2a57d0b54e2249ded.

Related issue: https://github.com/facebook/react-native/issues/35951.

**Comment by JmillsExpensify** [comment]
Closing per the work by Software Mansion above.
