### ISSUE TITLE
Web - Error message does not disappear after deleting existing payment method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14264

## Action Performed:
1. Go to Account Settings -> Payments. Click "Add Payment Method" button and select bank account type
2. Use plaid, choose Chase, select the account that ends with x1111 and submit. Verify that you successfully created a payment method
3. Create a workspace
4. Go to Workspace Settings -> Connect Bank Account
5. Select Plaid. Choose chase. And only select the account that ends in x1111
6. Complete the rest of the plaid steps
7. Verify that you see the error
8. Reload the page like in the issue.
9. Verify that you don't see an infinite spinner.
10. Go to Account Settings -> Payments. And delete the bank account payment method
image
11. Go back to Workspace Settings -> Connect Bank Account

## Expected Result:
Error message should disappear

## Actual Result:
Unable to connect to bank account after deleting payment methods

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome

**Version Number:** 1,2,55,0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212958858-0f9492bf-391c-40a6-adcf-3adec1b6c7c8.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment]
There might be a separate issue with Chase. 

Can you test again with Well Fargo?

**Comment by ctkochan22** [comment]
I just tested it with Chase and it worked fine

**Comment by ctkochan22** [comment]
Closing
