### ISSUE TITLE
[Fabric] Log in - Missing focus in Password field when log in with account

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14368]
## Action Performed:
1. Scan the code and install the build
2. In Log in put your email address
3. Tap Continue

## Expected Result:
Focus should be displayed in Password field when log in with account

## Actual Result:
 Missing focus in Password field when log in with account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native
- [ ] IOS / Native

**Version Number:** 1.2.49.0 

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211161925-bfbec717-7cb0-4ba5-8744-115ed6e66fde.MP4

**Issue reported by:** Applause - Internal Team

**Comment by dylanexpensify** [comment]
Coming from [here](https://github.com/Expensify/App/pull/13767#issuecomment-1374537730). Context [here](https://expensify.slack.com/archives/C035J5C9FAP/p1673373976683909)!

**Comment by JmillsExpensify** [comment]
This is part of the on-going Fabric migration.

**Comment by JmillsExpensify** [comment]
This is not daily, part of a longer-term project.

**Comment by j-piasecki** [comment]
https://github.com/WoLewicki/App/commit/60e47c488ce709954e6ca91425db705f7caba8ad Should fix this issue.

**Comment by JmillsExpensify** [comment]
Closing similar to the other issue, though we can also re-assess later in the implementation process.

**Comment by j-piasecki** [comment]
Password is focused when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/cbd91518-bf46-4704-90d7-dcf7ed5ce227
