### ISSUE TITLE
[Fabric Rollout] iOS - Second keyboard opens when you click on the cursor in Request money

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14372]
## Action Performed:
1. Launch App
2. Enter email. password
3. Click the FAB button and select Request Money
4. Verify that the big number pad (BNP) page appears next
5. Tab on the cursor next to currency

## Expected Result:
There should be only one keyboard

## Actual Result:
Second keyboard opens when you click on the cursor in Request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] IOS / Native

**Version Number:** 1.2.49.0 

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211167008-8c333df1-912b-4a5f-8e9f-a16e2e457692.mp4

**Issue reported by:** Applause - Internal Team

**Comment by dylanexpensify** [comment]
Coming from [here](https://github.com/Expensify/App/pull/13767#issuecomment-1374537730). Context [here](https://expensify.slack.com/archives/C035J5C9FAP/p1673373976683909)!

**Comment by j-piasecki** [comment]
I'm working on this.

**Comment by j-piasecki** [comment]
https://github.com/facebook/react-native/pull/35878 should fix this issue upstream, I also added a patch for the time being [here](https://github.com/WoLewicki/App/commit/2bb8fad9239c33f8319a31648da00ed29105e149).

**Comment by JmillsExpensify** [comment]
Thanks @j-piasecki! I'll create another issue out of band so that we don't forget to update things once the upstream fix is live.

**Comment by JmillsExpensify** [comment]
Moved this to weekly since that's the speed this project is moving at.

**Comment by JmillsExpensify** [comment]
@roryabraham We should agree on the process for these. Given that we have a path in play, what should be our ideal game-plan? Close this and create a follow-up issue to remove the fork with the upstream PR is merged and included in a future release?

**Comment by roryabraham** [comment]
> @roryabraham We should agree on the process for these

I think I'm following your concern here @JmillsExpensify, brought to slack here: https://expensify.slack.com/archives/C01GTK53T8Q/p1675204378344359

**Comment by JmillsExpensify** [comment]
Sounds like we agreed on a GH project in the linked thread, though we still need to put that in motion. I'm pretty back up early this week, though, so unlikely I'll get back to this for a bit.

**Comment by j-piasecki** [comment]
@JmillsExpensify It seems like I cannot access the linked slack thread. Could you post the summary here or add me to the relevant channel?

**Comment by JmillsExpensify** [comment]
Oh sorry about that! Sure thing, we essentially decide that we were going to create a GH project that helps keep track of all our upstream fixes, forks, and what not so that we can better keep track of how to minimize what's specific to Expensify. So the project would have the following stages:

 - Reviewing
 - Merged in fork
 - Merged upstream
 - Released upstream and resolved

@roryabraham I'm going to go ahead and create this project, because I don't think one already exists. I believe we can also make it public for all too in this repo.

**Comment by JmillsExpensify** [comment]
Still part of the Fabric rollout. The next test, which this issue is a part of, is forthcoming.

**Comment by JmillsExpensify** [comment]
Same same.

**Comment by JmillsExpensify** [comment]
Re-testing of Fabric is commencing soon.

**Comment by JmillsExpensify** [comment]
Same as above.

**Comment by JmillsExpensify** [comment]
Same same. Fabric roll out and testing is on-going.

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
At a conference this week, not prioritizing this.

**Comment by j-piasecki** [comment]
It is working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/ba28f8b4-b906-4d29-af81-33e8ebdaf472

**Comment by JmillsExpensify** [comment]
Nice work! Let's close this one out then.
