### ISSUE TITLE
[$1000] Edit Comment input is not focused after closing emoji picker

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open web Mac/Safari
2. Go to any chat
3. Click the edit icon
4. Open emoji picker
5. Close it by clicking the icon

## Expected Result:
The edit text input should be focused 

## Actual Result:
The text input  not focused

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS /  Safari

**Version Number:** 1.2.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213010349-6e1047c1-4511-44e7-9b81-1e933106857c.mov

https://user-images.githubusercontent.com/43996225/213010639-e5a9c0a0-741e-40d4-9e96-4fe6bf1dcf52.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673934348579289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6d93aff7434727e</li>
        <li>Upwork Job ID: 1618218194203824128</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by miljakljajic** [comment]
I was able to reproduce this: 

<img width="1324" alt="image (35)" src="https://user-images.githubusercontent.com/28715117/214098958-9434b14b-6201-456b-bd1e-532d5cfa1001.png">

**Comment by miljakljajic** [comment]
Should this be external or internal?

**Comment by cristipaval** [comment]
This could be external

**Comment by abdulrahuman5196** [comment]
**Proposal**
It is due to focus of textInput called immediately on emoji modal close. We already have a fix for it on report compose, we can implement the same for edit message as well to maintain consistency
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js#L348-L366

**Solution**
```diff
--- a/src/pages/home/report/ReportActionItemMessageEdit.js
+++ b/src/pages/home/report/ReportActionItemMessageEdit.js
@@ -213,6 +213,26 @@ class ReportActionItemMessageEdit extends React.Component {
         }
     }
 
+    focus(shouldelay = false) {
+        InteractionManager.runAfterInteractions(() => {
+            if (!this.textInput) {
+                return;
+            }
+
+            if (!shouldelay) {
+                this.textInput.focus();
+            } else {
+                setTimeout(() => this.textInput.focus(), 100);
+            }
+        });
+    }
+
     render() {
_COMMENT_LENGTH;
         return (
@@ -255,7 +275,7 @@ class ReportActionItemMessageEdit extends React.Component {
                     <View style={styles.editChatItemEmojiWrapper}>
                         <EmojiPickerButton
                             isDisabled={this.props.shouldDisableEmojiPicker}
- actions(() => this.textInput.focus())}
+ actions(() => this.focus(true))}
                             onEmojiSelected={this.addEmojiToTextBox}
                             nativeID={this.emojiButtonID}
                         />

```

Note: even without the 100ms delay I am not seeing this issue. But added it so that it could be consistent with the report compose view and it seems to be added due to some other issue. We can also remove it if its not required now.

**Comment by priyeshshah11** [comment]
## Proposal

We should add setTimeout as that's what we do for the main composer.

```diff
onModalHide={() => {
    InteractionManager.runAfterInteractions(() => {
        setTimeout(() => this.textInput.focus(), 100);
    });
}}
```

**Comment by cristipaval** [comment]
Thanks @fedirjh !
Thank you @abdulrahuman5196 and @priyeshshah11 for your proposals and @fedirjh for linking to the other issue!
