### ISSUE TITLE
[Fabric] Android - Log in - The page blinks when tap "Go back" button"

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14370]
## Action Performed:
1. Open the App
2. Enter email in input field
3. Tap "Continue"
4. Tap "Go back"

## Expected Result:
The page is not blink  when tap "Go back" button"

## Actual Result:
The page blinks when tap "Go back" button"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native

**Version Number:** 1.2.49.0 

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211164088-3d797a63-a699-466b-ad3c-9cab880ec007.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Comment by dylanexpensify** [comment]
Coming from [here](https://github.com/Expensify/App/pull/13767#issuecomment-1374537730). Context [here](https://expensify.slack.com/archives/C035J5C9FAP/p1673373976683909)!

**Comment by JmillsExpensify** [comment]
This is part of the Fabric migration for clarity.

**Comment by JmillsExpensify** [comment]
This is not daily and part of the Fabric project.

**Comment by j-piasecki** [comment]
https://github.com/WoLewicki/App/commit/60e47c488ce709954e6ca91425db705f7caba8ad Should fix this issue.

**Comment by JmillsExpensify** [comment]
Closing this issue now that we have a fix in place, though we can re-open if that doesn't end up being the case.
