### ISSUE TITLE
Dev - Pressing Avatar icon throws multiple console warning/error as below

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to settings (open console)
3. Press Avatar > Notice Error/warning shows

## Expected Result:
No console warning/error should show

## Actual Result:
Showing  console warning/error should show

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.55-0
**Reproducible in staging?:** Occurs in Dev
**Reproducible in production?:** Occurs in Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="674" alt="Screenshot 2023-01-17 at 2 06 23 PM" src="https://user-images.githubusercontent.com/43996225/213240970-112f841a-6009-435b-ac5d-ae9b40f63f07.png">
<img width="676" alt="Screenshot 2023-01-17 at 2 10 32 PM" src="https://user-images.githubusercontent.com/43996225/213240974-bd1df767-dc37-4d27-bf66-f3fc920e28ad.png">
<img width="754" alt="Screenshot 2023-01-17 at 2 06 50 PM" src="https://user-images.githubusercontent.com/43996225/213240978-04470d77-8ba8-477a-abd8-08174fcb9a85.png">
<img width="751" alt="Screenshot 2023-01-17 at 2 11 00 PM" src="https://user-images.githubusercontent.com/43996225/213240985-3f2c3c4b-5d83-4280-b301-bcb41820814d.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673944977870059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3a5ff8ae74879ae</li>
        <li>Upwork Job ID: 1616432997968379904</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
Removing C+ as this is a a one liner fix.

**Comment by garrettmknight** [comment]
Asked @dhairyasenjaliya to apply for the job to pay out for reporting [here](https://expensify.slack.com/archives/C049HHMV9SM/p1675176346773489?thread_ts=1673944977.870059&cid=C049HHMV9SM)

**Comment by garrettmknight** [comment]
Paid @dhairyasenjaliya $250 for reporting - closing.
