### ISSUE TITLE
Tracker to follow up with `react-native-fast-image` patch

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#14382]
Purpose of this issue is to regularly check on the upstream PR so we can ideally get rid of the `patch-package` fix we had to implement in App

- Upstream PRs:
    - https://github.com/DylanVann/react-native-fast-image/pull/953
    - https://github.com/DylanVann/react-native-fast-image/pull/984
- Patch-package fix: https://github.com/Expensify/App/pull/13304
- Expensify Fork: https://github.com/Expensify/react-native-fast-image

**Comment by Beamanator** [comment]
No progress on upstream PR

**Comment by Beamanator** [comment]
No movement on the linked PRs

**Comment by Beamanator** [comment]
No movement on the linked PRs 🤷

**Comment by cristipaval** [comment]
Same.

**Comment by Beamanator** [comment]
Still no progress - when do we close this out? 😅

**Comment by Beamanator** [comment]
I wonder when we should stop tracking these lol

**Comment by Beamanator** [comment]
same

**Comment by Beamanator** [comment]
same

**Comment by cristipaval** [comment]
same

**Comment by cristipaval** [comment]
No progress 😞

**Comment by cristipaval** [comment]
I'm closing this one as it seems that we no longer use fast-image in the App.
