### ISSUE TITLE
Update Onfido SDK UI to the latest version

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#14397]
### Problem

Coming from [this issue](https://github.com/onfido/onfido-sdk-ui/issues/2139) and [this App issue](https://github.com/Expensify/App/issues/13992), we were advised to update the [onfido-sdk-ui](https://github.com/onfido/onfido-sdk-ui) package to the latest version to get rid of the console error.

### Why is it important

We want to keep the console clean from errors and staying up to date with out packages is also important.

### Solution

Let's update the package and make sure the flow works well

**Comment by mountiny** [comment]
cc @nkuoch or @francoisl I know you have worked with Onfido before in case you are interested in taking this one. Otherwise I can do this some time next week.

**Comment by mountiny** [comment]
@twisterdotcom 

> We're building on their API anyway.

What stage are we on with this one? Is it couple months away or more so couple of weeks?

It works now so I assume we are fine, but if it would be couple of months before we use the API it might be worth just trying the udpdate

**Comment by twisterdotcom** [comment]
@MariaHCD, @nkuoch, @kadiealexander and @bfitzexpensify are working on it here: https://github.com/Expensify/Expensify/issues/233363#issuecomment-1386393414

**Comment by mountiny** [comment]
Thanks for the context! I think we can close this one then since the Onfido works now!

**Comment by MariaHCD** [comment]
I'm actually of the opinion that we should upgrade the SDK version now. Considering we're still working on the design doc and implementation may still be a while away. Thoughts, @nkuoch?

**Comment by nkuoch** [comment]
I agree - especially as it's easy to do - and am interested if it might fix some bugs customers are having with the current sdk.

**Comment by nkuoch** [comment]
Seems like someone is already upgrading it? https://github.com/Expensify/App/pull/14353

**Comment by MariaHCD** [comment]
Nice, yeah, looks like our contributors are on it 🚀 We can close this issue, then 👍🏼
