### ISSUE TITLE
Vulnerability payment for E/E #254640

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#14416]
Paying @oesayan $1250 for vulnerability report - https://github.com/Expensify/Expensify/issues/254640
(note: our default amount going forward is $1000 for any security or vulnerability report if we fix it internally or externally, I _messed up_ with adding the extra $250)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df88351909f5a1f5</li>
        <li>Upwork Job ID: 1616168428363796480</li>
        <li>Last Price Increase: 2023-01-19</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Sorry @sobitneupane , a review is not needed, added `Internal` to get Upwork job created

@oesayan can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01df88351909f5a1f5

**Comment by oesayan** [comment]
@mallenexpensify accepted and submitted the job.
Thank you guys for working with me!

**Comment by mallenexpensify** [comment]
Paid! Thanks again for the help @oesayan
