### ISSUE TITLE
Security - Close account -  App is crashed when closing the account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with gmail account
3. Navigate to Settings > Security
4. Enter the email in the input and tap on "close account" button

## Expected Result:
App is not crashed when closing the account

## Actual Result:
App is crashed when closing the account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.57.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/213817815-f8e398b6-fcc6-43fe-bd29-c9d9749136c6.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@chiragsalian Hopefully this PR should fix it https://github.com/Expensify/react-native-onyx/pull/231

**Comment by chiragsalian** [comment]
This looks like a dupe of https://github.com/Expensify/App/issues/14437. Closing this issue out but @marcochavezf can you test this flow as well when your App PR is ready. I imagine you'll need an App PR to bump the react-native-onyx version. Remember to CP it to staging though 🙇‍♂️

**Comment by marcochavezf** [comment]
Confirmed this fixed in the [PR](https://github.com/Expensify/App/pull/14450) that bumps the react-native-onyx version:

https://user-images.githubusercontent.com/6829422/213828047-c47746d9-48e9-41dc-afa5-a73e87287649.mov
