### ISSUE TITLE
[HOLD][$1000]  VBA - Nothing happening click on "Fix the errors" in the additional info page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14451]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot and login
2. Go to workspace > connect bank account
3. Continue up to additional information page (step 4 of 5)
4. Check one of the 2 checkboxes and Save and continue to trigger error message

## Expected Result:
"Fix the errors" shouldn't be hyperlinked or if this is clicked some action should be there

## Actual Result:
Nothing happens
In desktop and Web hovering on "Fix the errors" pointer appears
In iOS and Android it looks like hyperlinks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [x] Web / Chrome
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.57.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/213825697-35995107-92b7-4566-9634-8a11ac68a40d.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a251680dea09ee31</li>
        <li>Upwork Job ID: 1619003545207386112</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
Added the external label, now waiting for proposals 👍

**Comment by esh-g** [comment]
What would be the intended behaviour in such case? Because the top two fields are not required fields

**Comment by PrashantMangukiya** [comment]
**Here is the problem:**
Whenever we show error. we are not considering hasOtherBeneficialOwners checkbox  value. If hasOtherBeneficialOwners checked then we have to show that error, otherwise not. I think this is better solution.

**Proposed Solution:**
If hasOtherBeneficialOwners checkbox checked then show that error line, otherwise not. So we have to update code as shown below.  

_src/pages/ReimbursementAccount/ACHContractStep.js_ add props:
Pass hasOtherBeneficialOwners as props to ReimbursementAccountForm component.
```javascript
<ReimbursementAccountForm
       reimbursementAccount={this.props.reimbursementAccount}
       onSubmit={this.submit}
       hasOtherBeneficialOwners={this.state.hasOtherBeneficialOwners}   // Add this line
     ...
 >
```

Within _src/pages/ReimbursementAccount/ReimbursementAccountForm.js_ add code:
```javascript
const propTypes = { 
   /** Other beneficial owners checkbox checked or not */
    hasOtherBeneficialOwners: PropTypes.bool.isRequired,    // Add this
}

render () {
   const hasErrorFields = _.size(this.props.reimbursementAccount.errorFields) > 0;   // OLD code
   // New Code 
  const hasErrorFields = this.props.reimbursementAccount.errorFields
                                && this.props.hasOtherBeneficialOwners
                                && _.size(this.props.reimbursementAccount.errorFields.beneficialOwnersErrors[0]) > 0;

}
```

**Comment by ali-thowfeek** [comment]
possibly related to https://github.com/Expensify/App/issues/13909

**Comment by robertjchen** [comment]
Thanks for the preliminary investigation here! Let's put this on hold in favor of https://github.com/Expensify/App/pull/13501

**Comment by flaviadefaria** [comment]
Since this is on hold I'll move it to weekly.

**Comment by robertjchen** [comment]
Thanks @thesahindia ! 🙇
