### ISSUE TITLE
 Border does not cover fully the landscape image.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any report, send a landscape image.
3. Notice that the border is not fully cover the image and you can see the report background.

## Expected Result:
Border should be fully cover the image.

## Actual Result:
the border is not fully cover the image and you can see the report background.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.57-2
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213929779-4ac93bcc-a049-46cd-856d-d5d16f7651dd.MP4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/213929790-7d226737-3dd7-4595-befd-f4d62a93e94c.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674309951857249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Hmm, I am also on the newest version but am not seeing this:

![image](https://user-images.githubusercontent.com/30815269/213946146-867cbf37-c739-4292-9611-97bebb378b8f.png)

I can't even produce this with a 16:9 aspect ratio image:

![image](https://user-images.githubusercontent.com/30815269/213946221-8a7aea39-b6d3-49fe-b9cd-04cb65cdc4fa.png)

Please try and repro and re-open if you can still see the issue: might have to take it to the channel for a 2nd opinion?
