### ISSUE TITLE
Search ordering is not correct

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. click search bar
2. Have 2 contacts with different last name(“Abdul Test” and “Abdul Rahuman”)
3. Search for “Abdul R”

## Expected Result:
Highest match(“Abdul Rahuman”) should be the top item

## Actual Result:
Another match(“Abdul Test”) comes at top while “Abdul Rahuman” comes below

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/213926583-350a8e1a-104f-4d94-9f0f-00bded86d988.jpeg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/213926594-0ed19d13-1a3e-4c5e-8e75-79b3a0dce6db.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @abdulrahuman5196 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674238040466929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Confirmed the behavior identified here, but I'm double checking whether that's expected or not in [bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1674486075840079) before confirming it's a bug.

<img width="381" alt="Screenshot 2023-01-23 at 2 57 21 PM" src="https://user-images.githubusercontent.com/1529980/214072644-32d11947-7ae1-4053-b2d7-a5cb12ca5a20.png">

**Comment by garrettmknight** [comment]
Confirmed internally that the search is [ordered by lastActionCreated](https://github.com/Expensify/App/blob/17edc8253c992391c6937e9ba788679b898e99aa/tests/unit/OptionsListUtilsTest.js#L300) rather than pure matching. We might revisit that as part of a search update,
