### ISSUE TITLE
Cancelled amount shows in negative for a brief moment if the requested amount is less than owing amount

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report to which you already owe money
3. Click on plus and open Request Money
4. Type in any amount and click on Request
5. After requesting, cancel the request

## Expected Result:
Cancelled request text should be 'Cancelled the x request' where x is the amount for the request

## Actual Result:
Cancelled request text displays 'Cancelled the -x request' for few seconds after correcting itself

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.58-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214103018-7b5e5a84-b625-47f9-a5db-bb5c01a68ede.mp4

https://user-images.githubusercontent.com/43996225/214103051-764ecbac-96e9-4695-a746-537f20a61adf.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674236652650379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll review this one tomorrow.

**Comment by alexpensify** [comment]
Here is the view on the desktop: 

![image](https://user-images.githubusercontent.com/8107070/214723572-70047c6f-535d-4bfb-a237-606902376198.png)

Android app: 

![image](https://user-images.githubusercontent.com/8107070/214723863-f518cc79-3a93-4b58-aeea-c933a105df2f.png)

I understand that this is a brief blip but I can't replicate it. Both updated quickly to reflect that only $5 is owed.

**Comment by alexpensify** [comment]
@grgia - I've assigned Engineering to see if anyone else can replicate or if there is something in the code slowing down the amount owed refresh. If you can't replicate the experience, then we should close. Thanks!

**Comment by alexpensify** [comment]
@grgia any chance you've reviewed this one, seeing if we should close it out? Thanks!

**Comment by grgia** [comment]
I am unable to replicate as well, closing out!

**Comment by alexpensify** [comment]
Thanks!
