### ISSUE TITLE
Messages disappear and reappear after sending / receiving message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message
2. Have 1:1 chat

## Expected Result:
Messages should not disappear

## Actual Result:
Messages disappear / reappear

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.58-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1674493224458169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3025d2a96e1dfbb</li>
        <li>Upwork Job ID: 1617661890672463872</li>
        <li>Last Price Increase: 2023-01-23</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
Still reliably [happening](https://expensify.slack.com/archives/C01GTK53T8Q/p1674504625371319?thread_ts=1674493224.458169&cid=C01GTK53T8Q) 


I assume this can be external but double checking in thread

**Comment by mallenexpensify** [comment]
Here's a vid from @tgolen (I can't upload files to GH)
https://expensify.slack.com/archives/C01GTK53T8Q/p1674504625371319?thread_ts=1674493224.458169&cid=C01GTK53T8Q  

I'm able to reproduce if anyone needs me to. My steps are
- Send a message to someone
- Wait ~30 seconds and a duplicate message appears. 

Not seeing any errors in console, only warnings - https://www.screencast.com/t/EZ1qrdrc

I've also had other weirdness this morn, stuck chats and an image that disappeared, reappeared

**Comment by mvtglobally** [comment]
Should we mark this Deploy Blocker?

**Comment by mallenexpensify** [comment]
i don't know @mvtglobally , sorry.  Maybe raise in #qa? 

I dropped in the [deprecate sequence number Slack room](https://expensify.slack.com/archives/C04DC6LU2UB/p1674515742859249) for more eyes

**Comment by roryabraham** [comment]
@sketchydroide Stealing this from ya

**Comment by roryabraham** [comment]
@mollfpr It's a back-end fix so nothing a C+ will be able to do here.

**Comment by roryabraham** [comment]
This is fixed
