### ISSUE TITLE
Searching with phone number does not work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and login with user A
2. Link a phone number to user A
3. Logout and login with user B
4. Open search and search with phone number assigned to user A

## Expected Result:
Search result should display user A

## Actual Result:
Search result displays the number and on click of it, 'Report does not exists' error is displayed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.58-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214176671-f21a35ae-aa8a-442a-b303-63232217eac0.mov

https://user-images.githubusercontent.com/43996225/214176691-24ef1db8-3bdb-4428-b111-052ae1e9c0e7.mov

https://user-images.githubusercontent.com/43996225/214176740-cbfeefc8-688f-4aba-bf3c-118b95a30fa6.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674486353465509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
@dhairyasenjaliya Are these accounts on the same workspace or policy?

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
I don't think this is a bug. We only search for people based on their primary login (which may be a phone number). I believe this is done on purpose to prevent information (like the phone number) from being made public if the user doesn't want to.

Closing

**Comment by MitchExpensify** [comment]
Thanks @Gonals !
