### ISSUE TITLE
Notifications - Notification is shown for deleted message in the Notification Centre for user A.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into NewDot on Web or Desktop as user A
2. Send as user B (different device) to user A a message (make sure the chat is NOT already open)
3. User A verify the message is received and a notification displays for the message
4. User B delete the message
5. User A verify no notification is shown for the deleted message

## Expected Result:
No notification is shown for deleted message in the Notification Centre for user A.

## Actual Result:
Notification is shown for deleted message in the Notification Centre for user A.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214172201-79022805-eb81-4fb8-b14c-8d086964b44a.mp4

https://user-images.githubusercontent.com/93399543/214172202-4f850826-bc75-4636-ac7b-599455cba375.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
cc @arosiclair since you worked on this fix https://github.com/Expensify/App/pull/14375

**Comment by arosiclair** [comment]
@kbecciv 

My testing steps weren't clear enough. We needed to verify that a _second_ notification doesn't appear when the message is deleted. So the testing steps should be:

1. Log into NewDot on Web or Desktop as user A
2. Send as user B (different device) to user A a message (make sure the chat is NOT already open)
3. User A verify the message is received and a notification displays for the message
4. User B delete the message
5. User A verify **a second notification does NOT display for the deleted message**

The attached videos match the above behavior so this isn't a bug.
