### ISSUE TITLE
Security - Can't close special account, error message appears 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with the iheretsutest+2101@gmail.com/Yulia1986gerets account
3. Go to Settings -> Security -> Close account
4. Enter the email in the input and click on "Close account"

## Expected Result:
Able to close account without any error message

## Actual Result:
Can't close special account, error message appears 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (2)](https://user-images.githubusercontent.com/93399543/214198285-3f136a90-6e41-4693-aba5-6ae8316a8694.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e23146eaa609166</li>
        <li>Upwork Job ID: 1618276755241353216</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by slafortune** [comment]
Hm - strange!
[LOGS](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=email%3A%22iheretsutest%2B2101%40gmail.com%22%20AND%20timestamp%3A%5B2023-01-24T00%3A00%20TO%202023-01-25T23%3A59%5D)

I do see an error in the logs `TransactionIDs are not converted to string` - there is only one transaction created in the account
Transactions ID - `5299859348761605901`

**Comment by tgolen** [comment]
Looking at the logs, I think the problem is this:

```
API threw ExpError Expensify\Error\User\Undeletable - c65019fc-c2d8-4529-8382-045c9c13d6cf ~~ message: '405 You have an annual subscription'
```

That account has an annual subscription which is why it can't be closed. It would be nice to surface the actual error in that case. This will probably need to be something done internally. I will work on it!

**Comment by tgolen** [comment]
@eVoloshchak This will be a fix only on the API, so there won't be anything for you to review on this one.

**Comment by slafortune** [comment]
Can just remove this Upwork Job @tgolen ?

**Comment by tgolen** [comment]
Yes, that should be fine 👍

**Comment by tgolen** [comment]
The updated error message was deployed to production last week, so I will close this.
