### ISSUE TITLE
LHN- Only name or email is visible in LHN if the sender has a long name or a long email address

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In the secondary testing device, log in as user A with a long name or long email like applausetester+XXXXX@applause.expensifail.com
2. In the main testing device, log in as user B
3. As user A invite the user B to a workspace
4. User A sends some messages in the #Announce room

## Expected Result:
Users A and B see the last sent message in LHN

## Actual Result:
User B sees only the sender's email (or name) and does not see the message if sender has a long email address or a long name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1,2,58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2023-01-20 at 6 53 25 PM](https://user-images.githubusercontent.com/93399543/214181198-9a3fa2ab-07b1-4545-b80b-61214bbd7991.png)

https://user-images.githubusercontent.com/93399543/214181199-f160a948-afa7-434d-9bc3-42d484a32f88.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Hmmm. I don't think this is a bug. The whole information just doesn't fit 😆.

Closing for now, as I think it is fine to display the name there!
