### ISSUE TITLE
Android - Chat- The edit function does not appear immediately after send a message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expenesify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log i with any account
4. Go to any chat
5. Send a message
6. Tab and hold the message to view the action menu

## Expected Result:
The edit function must appear immediately after send a message

## Actual Result:
The edit function does not appear immediately after send a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [x] Android / native

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214325733-368991ae-1f5a-4e2c-b13b-769b3cd197f6.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
I'm a lil behind on this sorry! I tried to reproduce on my Android device but ran into a few hiccups. Should have traction by tomorrow on doing those firmware updates 🙏

**Comment by michaelhaxhiu** [comment]
I tried to reproduce on my Android this morning and it shows the **edit** ability immediately. I tested on:
- Android 11
- Pixel 2 XL
- New Expensify Version 1.2.62-1

@kbecciv I'm going to close this for now - let me know if you can still reproduce somehow!

![image](https://user-images.githubusercontent.com/13206896/216034006-a752861a-aeea-4221-9d59-8875581acc0f.png)
