### ISSUE TITLE
Flags appear in search on windows chrome in unicode form even though we have disabled flags on windows chome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Open emoji picker
4. Search with term 'New'

## Expected Result:
Search results should not have flags or flags in unicode form on windows chrome as we have disabled flags in windows

## Actual Result:
Flags appear in search in unicode form

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows / Chrome 

**Version Number:** 1.2.58-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214430209-a22a3e2f-9f4b-4514-b444-acfccdc90ed0.mp4

https://user-images.githubusercontent.com/43996225/214430559-ad934586-84cb-436c-8a45-1969c103be73.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674567548207959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
We recently agreed that we're punting some non-critical Windows bugs. Going to close.
