### ISSUE TITLE
[HOLD for payment 2023-01-25] Update Emoji Picker Search to use Trie SuggestEmoji method E/E #239099 - payment for @mananjadhav 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#14525]
This issue is linked to our private repo. I'm creating it purely to pay out @mananjadhav 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e10cf2f8e88c0f15</li>
        <li>Upwork Job ID: 1618019097405775872</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
@mananjadhav Mind applying the above Upwork issue for internal PR review? We'll get you squared away.

**Comment by stitesExpensify** [comment]
Thanks for making this! I didn't even realize the other issue was in our private repo

**Comment by mananjadhav** [comment]
@JmillsExpensify tried applying but it says Access Denied

**Comment by JmillsExpensify** [comment]
It's open for you now. https://www.upwork.com/jobs/~01e10cf2f8e88c0f15

**Comment by mananjadhav** [comment]
Applied

**Comment by JmillsExpensify** [comment]
Offer sent.

**Comment by JmillsExpensify** [comment]
All paid out!
