### ISSUE TITLE
[$1000] Web - Security - Close account - Console error is displayed when closed account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14562]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Setting - Security - Close account

## Expected Result:
Console error is not displayed when closed account

## Actual Result:
Console error is displayed when closed account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web/ Chrome 

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Untitled](https://user-images.githubusercontent.com/93399543/214667671-02f83385-c8cf-45a4-a58e-a26176ba123d.png)

https://user-images.githubusercontent.com/93399543/214667683-915ad91e-af23-42b4-89dc-386ac9ba84e0.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127d6eba140b9c56a</li>
        <li>Upwork Job ID: 1618769609192013824</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
@alex-mechler dummy question, can something like this be worked on externally?

**Comment by alex-mechler** [comment]
This should be able to be worked on externally, this is an error related to sending a message on the socket after it has already been closed generally.

**Comment by bernhardoj** [comment]
I think this has the same root cause with this https://github.com/Expensify/App/issues/14350

**Comment by alex-mechler** [comment]
Ah good catch @bernhardoj! Going to remove the help wanted label from this for now to confirm that the fix for https://github.com/Expensify/App/issues/14350 also fixes this issue!

**Comment by alex-mechler** [comment]
Confirmed that its no longer reproducible on dev. Since https://github.com/Expensify/App/issues/14350 has the tracking for payment of @Prince-Mendiratta, and this was reported by Applause, closing this out! Thanks everyone!
