### ISSUE TITLE
Payments - Debit Card- "Name on card" field is not visible after tap on fix the error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14409

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Payments
3. Click "Add payment method" and select "Debit card"
4. Click "Save" without entering any data
5. Verify that all inputs have errors
6. Scroll down and click "fix the errors"
7. Verify that the first input gets focused and you are scrolled until it is fully visible (including the top border)
8. Input something in the first input "Name on card"
9. Scroll down and click again "fix the errors"
10. Verify that the second input gets focused and you are scrolled until it is fully visible (including the top border)

## Expected Result:
"Name on card" field is visible after tap on fix the error

## Actual Result:
"Name on card" field is not visible after tap on fix the error

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214682880-f024fd2e-36d9-4de0-af72-0dcb02ee83e7.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is the correct behavior! From the test steps:

>Verify that the second input gets focused and you are scrolled until it is fully visible (including the top border)

After filling `Name on card`, tapping on `Fix the error` should scroll and focus on the second input, i.e. `Debit card number`, which happens in the video.

Closing this!
