### ISSUE TITLE
[HOLD for payment 2023-02-07] Not opening plaid screen when user click on `connect online with plaid`

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14583]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create a new workspace
2. click on connect back account
3. wait for complete the loading
4. again create a new workspace
5. immediate click on connect back account
6. click on connect online with plaid  option

## Expected Result:
should open plaid screen

## Actual Result:
not opening plaid screen

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214735872-38810b8e-bf22-41cf-a340-7418c0438e22.mov

https://user-images.githubusercontent.com/43996225/214735906-625f4231-c617-495c-9595-06551ce21c87.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674198664819569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014365699878ee35c6</li>
        <li>Upwork Job ID: 1618912244890304512</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
`v1.2.60-0` Web MacOS Chrome:

![plaid](https://user-images.githubusercontent.com/16232057/214971772-ef210820-5ad6-43ff-8f01-9f0be0bca670.gif)

There does seems to be a long delay when trying to connect with Plaid in quick succession after creating a workspace, so I wonder if there's a performance regression here somewhere? 

@MariaHCD @nkuoch @ctkochan22 can this go `external` or would it need to be an `internal` investigation?

**Comment by trjExpensify** [comment]
Same on MacOS Safari for good measure: 

![safari plaid](https://user-images.githubusercontent.com/16232057/214972987-0f450a29-2774-4baf-a2a0-5f8250f3b162.gif)

**Comment by MariaHCD** [comment]
Hmm...this was fixed here: https://github.com/Expensify/App/issues/14505

And I can't seem to reproduce on staging `v1.2.60-0`

**Comment by trjExpensify** [comment]
Ah cool, looks like @nkuoch has figured it out? Nice!

**Comment by MariaHCD** [comment]
> But there might be another issue with the CreateWorkspace call which seems to take quite long

Ah, interesting. Could you expand on this? I've been looking into why CreateWorkspace command takes too long [here](https://github.com/Expensify/Expensify/issues/246016). Haven't been able to find anything conclusive just yet but will continue digging.

**Comment by nkuoch** [comment]
I haven't investigated that one, I just noticed it was the reason the optimisticData to open the reimbursement page happened later (because there was this long call of CreateWorkspace not finished in the queue)

**Comment by gadhiyamanan** [comment]
@trjExpensify accepted

**Comment by trjExpensify** [comment]
Paid! Over to you @0xmiroslav to accept :)

**Comment by trjExpensify** [comment]
Awesome, everyone is paid. Thanks!
