### ISSUE TITLE
Zip code field in "Add Debit Card" form autofills part of the email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: You'll need to have your email/password saved in the browser.
1. Go to Settings -> Payments.
2. Click Add payment method-> Debit Card or go to https://staging.new.expensify.com/settings/payments/add-debit-card

## Expected Result:
Zip code should not be auto filled with part of the email, it shouldn't be auto filled at all.

## Actual Result:
Zipcode is autofilled with part of the email

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] MacOS / Chrome 

**Version Number:** 1.2.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214731179-e401133a-e57a-4d07-ab27-e87b940b9c18.mov

https://user-images.githubusercontent.com/43996225/214731197-9e982491-583c-49bc-ae98-4bc36318bda3.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyeshshah11 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1674225410102319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Commented in the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1674774205958539?thread_ts=1674225410.102319&cid=C049HHMV9SM) and tagged a couple of people for a second opinion. Given our move to passwordless coming real soon, I'm curious if we're going to remove the "auto-complete" on pages like this one to avoid putting the email in the zipcode field and the password in the password field.

**Comment by marcaaron** [comment]
Oh that's a good point. I found a workaround for this but will just leave it here instead of implementing it.

**Comment by trjExpensify** [comment]
Yuuup. Going to close this issue out as it will indeed go away with passwordless.
