### ISSUE TITLE
A slight delay on releasing press is not triggering action while editing comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [new.expensify.com](http://new.expensify.com/)
2. Open any chat
3. Edit comment
4. press and release after several seconds / ms

## Expected Result:
Action should be performed on press out

## Actual Result:
No action has been taken.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214731831-e1c17345-e637-41e1-ba43-7e5bd6f81d46.mp4

https://user-images.githubusercontent.com/43996225/214731846-59e52e7a-c6b1-4749-a973-b5087d0ce56e.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674201318433869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Hey @kavimuru , I'm unable to reproduce this.


https://user-images.githubusercontent.com/31258516/214744965-aaab93b7-b25d-4f97-a230-4c30d55ce4fd.mp4
