### ISSUE TITLE
Desktop - Scroller does not appear when resizing the window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/14409

## Action Performed:
1. Login in New Dot
2. Go to Settings > Payments
3. Click "Add payment method" and select "Debit card"
4. Click "Save" without entering any data
5. Verify that all inputs have errors

## Expected Result:
In the desktop, resize the window enough to have scrolling in the RHN

## Actual Result:
Scrolling does not appear, when scrolling with mouse then scroller appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Desktop

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214864674-dd53dc98-1dce-4725-9c09-08ec368df2f6.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is expected. We don't show the scroll bar in any RHN page. Closing.
