### ISSUE TITLE
App allows to add phone number used by another user and after adding the phone number, it removes the number from previous user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14617]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and login with user A
2. Open settings
3. Open profile
4. Open phone number and add phone number to the profile, then log out
5. Login with user B
6. Open settings
7. Open profile
8. Add same phone number as user A to the profile
9. Log in to A > Settings > profile

## Expected Result:
It is should provide an error that phone number is already used

## Actual Result:
It allows user B to add the phone number and deletes the phone number from user A

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.2.60-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/215004836-d5a04602-4c46-4324-b85d-88dc1314e782.mp4

https://user-images.githubusercontent.com/43996225/215004860-6f80741d-3c8a-46db-86b8-4927a5507250.mp4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/215004898-90aefe3b-e8c5-4de6-9445-8a433ed3467a.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674752202671799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Not sure this is actually a bug. Discussing [here](https://expensify.slack.com/archives/C049HHMV9SM/p1674854023529119?thread_ts=1674752202.671799&cid=C049HHMV9SM) in Slack. Closing for now, but will re-open if we decide this is a bug and want to change the behavior here.
