### ISSUE TITLE
The IOU money request is showing twice even though just one request has been made.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14612]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account.
2. From LHN, click plus button, choose Request Money, try to request money to a new account.
3. Click on that request, click Cancel to cancel the request, reopen the Detail page 2,3 times.

## Expected Result:
The cancel request shouldn’t be duplicate

## Actual Result:
The cancel request is duplicate.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.60-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214998210-9a769ae3-f8a5-4e23-8355-cb503e9647b3.MP4

https://user-images.githubusercontent.com/43996225/214998221-debb5087-4751-43ca-9ecb-6dadfb908c2a.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @vitHoracek 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674645382555109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
According to Vit and Jason Mills in-thread, this isn't reproducible anymore. I can't repro either:

![image](https://user-images.githubusercontent.com/30815269/215007762-7fce9af7-db34-482b-8ed5-218319876d64.png)

![image](https://user-images.githubusercontent.com/30815269/215007768-633abc15-1d1b-4e8c-8a40-3293d8177853.png)
