### ISSUE TITLE
[HOLD for payment 2023-02-07] Fix console errors with Locale Picker

### ISSUE THREAD

**Issue by Luke9389** [Expensify/App#14637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Context
This issue covers the fix for a bug pointed out here: https://github.com/Expensify/App/pull/14526#issuecomment-1405657482
The RCA is accurate and the fix is effective. 
The original PR that caused this is here: https://github.com/Expensify/App/pull/12447#issuecomment-1406156889

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105b02a675ed86a5e</li>
        <li>Upwork Job ID: 1619082690033897472</li>
        <li>Last Price Increase: 2023-01-27</li>
    </ul>
</details>

**Comment by Luke9389** [comment]
@maddylewis, please mark @Prince-Mendiratta as the reporting contributor here and make a reporting bonus Upwork job. Thank you! 🙇

**Comment by maddylewis** [comment]
on it!

**Comment by Luke9389** [comment]
@Prince-Mendiratta, we're going to move forward with paying you the reporting bonus because you provided an RCA and a solution. Please note that this won't always happen. Our guidelines have more details, but essentially, we want to pay you for the urgency and quality of your post here:

https://github.com/Expensify/App/pull/14526#issuecomment-1405657482

Just know that in the future, this type of comment wouldn't actually qualify for payment.

**Comment by Luke9389** [comment]
You would post those as a proposal on this issue. 
But I decided not to make this an External issue because my PR broke it. 

So I would say, don't start with an RCA until there's an External issue for the bug.

**Comment by Luke9389** [comment]
> Not sure why I was not assigned as C+ to handle the RCA as per the process.

My apologies @parasharrajat, this is my fault. @Santhosh-Sellavel was automatically added to the PR by melvin-bot, so I just assigned him here because he already had the context for the problem. 

> That said, this issue does not qualify for C+ payment.

Would you explain why this is the case, please?

**Comment by Luke9389** [comment]
Ah OK. In the future, I'll follow that process. Since I made the mistake, I think we should pay @Santhosh-Sellavel for his review work on the PR. He tested on all platforms and verified the code.

Sorry about that. This will not happen again.

**Comment by maddylewis** [comment]
@Prince-Mendiratta - i've invited you to the job 👍

**Comment by maddylewis** [comment]
@Prince-Mendiratta has been paid. 

@Luke9389 - just making sure we're all set here before i close this one out. this issue was only created to get the reporting bonus processed, ya? lmk!

**Comment by Luke9389** [comment]
Yep, we're good to close this out. Thanks!

**Comment by Santhosh-Sellavel** [comment]
> Ah OK. In the future, I'll follow that process. Since I made the mistake, I think we should pay @Santhosh-Sellavel for his review work on the PR. He tested on all platforms and verified the code.
> 
> Sorry about that. This will not happen again.

bump @Luke9389 @maddylewis

**Comment by maddylewis** [comment]
@Santhosh-Sellavel - will you confirm the amount you're expecting for payment?

**Comment by Santhosh-Sellavel** [comment]
I'm not sure, we usually pay $1000 for internal PR reviews. If you feel the bounty should be reduced let me know the amount, thanks!

cc: @Luke9389 @maddylewis

**Comment by maddylewis** [comment]
okay gotcha. @Santhosh-Sellavel - will you link the issue that [this comment](https://github.com/Expensify/App/issues/14637#issuecomment-1419618988) is on? i just want to make sure im processing this one correctly. ty!

**Comment by Santhosh-Sellavel** [comment]
This issue only here https://github.com/Expensify/App/issues/14637#issuecomment-1409272702

**Comment by Luke9389** [comment]
I'm in agreement here. Sorry, I closed this out prematurely.

**Comment by maddylewis** [comment]
ok great! i'll get that payment processed shortly.

**Comment by maddylewis** [comment]
@Santhosh-Sellavel - will you share the name on your Upwork profile so that I can invite you to the job/process payment?

**Comment by maddylewis** [comment]
okay @Santhosh-Sellavel has been paid! sorry for the confusion!
