### ISSUE TITLE
[Hold for payment 2022-02-03] Payment GH for E/E #169078

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#14643]
@mollfpr reviewed [the PR ](https://github.com/Expensify/App/pull/14530)for [Pressing the Up-Arrow right after sending a message will edit the previous message #169078
](https://github.com/Expensify/Expensify/issues/169078)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011dd4c038531f1fc4</li>
        <li>Upwork Job ID: 1619131621059706880</li>
        <li>Last Price Increase: 2023-01-28</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@mollfpr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~011dd4c038531f1fc4

**Comment by mollfpr** [comment]
@mallenexpensify accepted

**Comment by mallenexpensify** [comment]
Paid! Closing.  Fastest turn-around ever.  Thanks @mollfpr , as stated in #expensify-open-source, i HATED that bug, took ~2 years to fix too 🤯
