### ISSUE TITLE
Connect Bank Account - When returning to the previous page, the focus is automatically on the first field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any workspace -> Connect bank account -> Connect manually
4. Enter the routing and account number -> Mark the checkmark -> Continue (leave the cursor in the account number input field)
5. At the next page click back
6. Change the position of the cursor to the routing number input field -> Continue
7. At the next page click back

## Expected Result:
The cursor remains on the same line it was left on

## Actual Result:
Regardless of which of the fields the focus was left on, when going back, the focus becomes on the first line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.61.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215276387-e7ad3cfe-5cc0-4378-935b-2c7970f05a18.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I don't think this is worth our time right now and not clearly a bug, thanks for reporting though!
