### ISSUE TITLE
Web - The user isn't navigated to the created chat/gr. in case of small window width (one tab)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1, Open any chat
2. Reduce window width when only one tab is available
3. Back to the LHN
4. Start new chat/group via Plus floating button

## Expected Result:
The user should be able to start chat/group without any issues

## Actual Result:
In case of one tab UI (small window with) - tab doesn't change to the newly created chat/group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.61.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215274090-6c2fb899-3ad2-4a41-b94a-c8c0a86740f9.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Whoops, let me close the loop here. Jumping in to test now.

**Comment by JmillsExpensify** [comment]
I wasn't able to reproduce this issue on v1.2.62-1. Adding the needs reproduction and closing.
