### ISSUE TITLE
Web - Login - A console error after login in any account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Enter the email on the email field and continue
3. Enter the password on the password field and continue

## Expected Result:
No console error after login in any account

## Actual Result:
A console error after login in any account

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.62.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (4)](https://user-images.githubusercontent.com/93399543/215589995-ca6506bd-11b0-48a1-b517-ed6175f93fbf.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I can reproduce, looks like it's coming from [this PR](https://github.com/Expensify/App/pull/13997/files). Look into a fix now.

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/issues/14661#issuecomment-1410908018 Resolved!
