### ISSUE TITLE
App crashes tapping on any contact from LHN 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Tap on any contact from LHN

## Expected Result:
User is taken to 1:1 chat with the contact

## Actual Result:
App crashes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] iOS / native

**Version Number:** 1.2.62-0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/215586310-5993dbf1-a668-4c61-ad8e-48082d494bad.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
@tylerkaraszewski I'm not sure how to know which PR from the checklist linked above is causing this bug.

**Comment by tylerkaraszewski** [comment]
Testing in the current staging version (which is newer than reported, 1.2.62-1) and I do not see this:

https://user-images.githubusercontent.com/705000/215852212-33d60bd5-1e77-4db2-a14a-636ae663cd61.mov

So I am going to close this issue.

**Comment by abekkala** [comment]
ah yeah, it looks like it was already in the works to be fixed by another PR
https://expensify.slack.com/archives/C049HHMV9SM/p1675182096726919?thread_ts=1675104877.303769&cid=C049HHMV9SM
