### ISSUE TITLE
DEV : Copied link from chat shows page not found when paste in browser (Dev version)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat in web, iOS, Android etc. (from Dev)
2. Click copy link from menu display at right side of each chat line or Context menu
3. Paste copied link to another tab
4. It should open page belonging to the copied link.

## Expected Result:
It should open chat belonging to the copied link

## Actual Result:
It shows page not found screen as shown in video below

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 61-0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/215569500-4f277999-f8da-426d-8347-395ecbdf42e4.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @PrashantMangukiya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674978380955899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Ah looks like @mountiny says this is due to some comment linking work in progress internally. I'm going to close: https://expensify.slack.com/archives/C01SKUP7QR0/p1675259499083749?thread_ts=1675251470.410809&cid=C01SKUP7QR0
