### ISSUE TITLE
iOS - Sign out - The page jumps after sign out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Sign out

## Expected Result:
Page NOT jumps

## Actual Result:
The page jumps after sign out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.62.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/215768920-0f70ca73-d0a4-462c-8d5d-7122130bf5f5.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
@kbecciv sorry! What do you mean by "jump"?

**Comment by kbecciv** [comment]
@NicMendonca  it makes sudden extra movement when log out from app.

**Comment by NicMendonca** [comment]
we discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1675388060227599) that this is not a bug, so going to close
