### ISSUE TITLE
Ability to send seemingly invisible attachment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Make a random text file and fill it with random string until its size exceed 300 bytes
2. Save the file with .pdf extension
3. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
4. Open a chat and send the file prepared at step 1 and 2

## Expected Result:
 If the file can't be previewed as PDF, either return an error upon uploading, or treat the file as regular file without preview (like .htm or .mp4 file)

## Actual Result:
File uploaded but can't be seen, making it seems to be invisible

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
File used : 
[TEST.pdf](https://github.com/Expensify/App/files/10548886/TEST.pdf)

https://user-images.githubusercontent.com/43996225/215829261-4b53d201-efed-4349-b361-1a9edb3c6faf.mp4

https://user-images.githubusercontent.com/43996225/215829408-7ee44f13-2ad3-4a05-ae4a-9021f6055e9b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675118385660489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I'm not sure this is a bug. The PDF doesn't open normally:

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/36425901/215938674-464e7950-595b-4e4f-adcb-77896b252b70.png">
