### ISSUE TITLE
Error loading PDF uploaded from staging in production

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#14739]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
1. On staging, upload a PDF
2. On production, try to open the PDF

## Expected Result:
Describe what you think should've happened
PDF should load

## Actual Result:
Describe what actually happened
![Screenshot 2023-02-01 at 3 09 19 PM](https://user-images.githubusercontent.com/30609178/216187151-dabb522a-b78f-47c1-bd89-d54c40091623.png)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.63-0
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause QA team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Regression from https://github.com/Expensify/App/pull/14463

cc @mountiny @kidroca @mananjadhav

**Comment by thienlnam** [comment]
There's also a chance this was an issue before https://github.com/Expensify/App/pull/14463#issuecomment-1412875221

**Comment by mountiny** [comment]
I will have to log off soon, but it might be some cors issue, we can also revert that PR unless you can spot what can be causing this issue.

I think everyone involved is at their EOD unfortunately.

**Comment by mountiny** [comment]
I am going to close this issue in favour of this original one and treat it as a regression from there https://github.com/Expensify/App/issues/14227
