### ISSUE TITLE
[HOLD for payment 2023-02-10] [$1000] Bottom margin missing in Payment methods

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to ND.
2. Navigate to Payments Page

## Expected Result:
Payment Methods Title has bottom margin

## Actual Result:
Payment Methods Title's missing bottom margin

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="374" alt="Screenshot 2023-01-31 at 2 22 21 PM" src="https://user-images.githubusercontent.com/43996225/216198830-1734ea15-ee41-4628-b3eb-b55d2a053204.png">
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/216198844-14256087-3b7d-4981-985e-47c78867d283.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675206012491849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ee862b130415d52</li>
        <li>Upwork Job ID: 1620944151393075200</li>
        <li>Last Price Increase: 2023-02-02</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I'm taking this one since it came from a PR I worked on

**Comment by luacmartins** [comment]
@fedirjh wanna make a proposal here since we already discussed it [here](https://github.com/Expensify/App/issues/14208#issuecomment-1410397519)?

**Comment by mollfpr** [comment]
@fedirjh proposal looks good to me 👍 @luacmartins 

🎀👀🎀 C+ reviewed!

**Comment by alexpensify** [comment]
@luacmartins - if this won't require testing, what are the next steps before closing - payment?

**Comment by luacmartins** [comment]
@alexpensify we should still complete the BZ checklist above. @mollfpr would you mind filling the checklist above please?

**Comment by mollfpr** [comment]
@luacmartins Sure! I will work on it!

**Comment by mollfpr** [comment]
Here's the checklist @luacmartins 

 >[@mollfpr / @luacmartins] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/14217

>[@mollfpr / @luacmartins] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/14217#issuecomment-1425892897

>[@mollfpr / @luacmartins] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1676040020503419

**Comment by luacmartins** [comment]
I think the only thing left here is payment.

**Comment by alexpensify** [comment]
Ok, I'll review this one today and prepare the next steps.

**Comment by alexpensify** [comment]
@luacmartins - I asked for a buddy check on the payment in the BZ Slack room to ensure that I pay everyone correctly.

**Comment by alexpensify** [comment]
@fedirjh and @mollfpr - I've started the payment process via Upwork and applied the bonus amounts.

**Comment by mollfpr** [comment]
@alexpensify accepted, thank you!

**Comment by alexpensify** [comment]
Closing! Great work everyone. I've taken these actions in Upwork: 

- Paid @fedirjh and @mollfpr 
- Ended the contracts associated with this job
- Closed the job
