### ISSUE TITLE
Display name is not updated after changing it to a new name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open https://staging.new.expensify.com/
2. Go to settings
3. Click on the profile
4. Click on display name and change it to a new name (Input new first and last name)
5. Go back and again click the display name

Notice that the first name and the last name are not updated in the display name section

## Expected Result:
First and last name should be updated on the display name section after changing it

## Actual Result:
First and the last name are not updated on the display name section (This doesn’t happen on android )

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.64-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/216442503-9ff8bfb7-f51c-4915-990f-2c7465ea411a.mp4

https://user-images.githubusercontent.com/43996225/216442520-5fc00f89-148d-4163-85cd-5b6a5b378a03.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675348988953739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Dupe - https://github.com/Expensify/App/issues/14784

**Comment by Christinadobrzyn** [comment]
Going to close this in favour of https://github.com/Expensify/App/issues/14784 since it's a deploy blocker. I will find out about paying @priya-zha as the reporter.
