### ISSUE TITLE
Request money/send money/split money to primaryLogin phone numbers are displaying '@expensify.sms' after the number in the message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open search and search for random number or open any report of primaryLogin phone number
3. Request money/send money in the chat

 OR

1. Open the app
2. Open group which has primaryLogin phone number user
3. Split any amount of bill with the group members

## Expected Result:
Request money/send money/split bill message should only display phone number of user

## Actual Result:
Request money/send money/split bill message displays '@expensify.sms' after phone number

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/216863325-b8ae0864-f90f-43c2-90f4-f3012fff0769.mp4

https://user-images.githubusercontent.com/43996225/216863335-7df3211d-bb4e-4669-a159-5b8589982bab.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675432415830139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
let me review this one today!

**Comment by maddylewis** [comment]
asking about this here - https://expensify.slack.com/archives/C049HHMV9SM/p1675968863469549?thread_ts=1675060631.104939&cid=C049HHMV9SM

**Comment by maddylewis** [comment]
Problem: you cannot start randomly chatting / requesting IOU / [insert other action here] to a phone number that does not yet exist in Expensify. This is intentional by design, due to SMS fraud.

Workaround: Ask the phone number to signup on Expensify.

Solution:
- Do nothing for now
- If we want when https://github.com/Expensify/Expensify/issues/242614 is done, we can revisit doing something

**Comment by maddylewis** [comment]
based on that discussion, i will close out this issue and we can reopen it once https://github.com/Expensify/Expensify/issues/242614 is done.

**Comment by dhanashree-sawant** [comment]
Hi @maddylewis , I don't have access to mentioned issue so can you let me know whether that issue is completed or not?
