### ISSUE TITLE
Update offline behavior for "Add Payment Method" button

### ISSUE THREAD

**Issue by ctkochan22** [Expensify/App#15263]
Right now you are able to sneak into the "Add Debit Account" or "Add Bank Account" section in Payment methods if you click the button, then go offline. 

Originally brought up in this issue: https://github.com/Expensify/App/issues/14575

And @marcaaron and I wondered [if we should disable the button at all](https://github.com/Expensify/App/issues/14575#issuecomment-1405827206). It kind of goes against convention. We usually let users navigate to a form and just disable the submit button until they are back online. 

However, the only weirdness with enabling the button when offline, is with Paypal. We only let you have one PayPal account set, and if you have one, we dont' let you go into the Paypal form unless you delete that payment method first. 

I kind of think its also against convention to do this? Why wouldn't we just let them click into PayPal and let them simply update/edit it. If they are offline, we'll just disable the button 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/12980144/219811412-950ff9ee-131d-4c51-b81b-5fd28f002557.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/12980144/219811461-514b8947-7d07-48df-9d33-15e9658b599e.png">

**Comment by ctkochan22** [comment]
@marcaaron 

We kind of talked about this. It's not really in convention to disable this button. However, we can't just remove the "isOffline" from the "Add Payment method" button right now because Paypal does not currently have a good offline behavior. Can you take a look and close if you don't think this is relevant right now?

**Comment by marcaaron** [comment]
I think I'm gonna close this one for now. We can always revisit this behavior in the future and probably will when the Payments page is updated to be the Wallets page as part of N7.
