### ISSUE TITLE
Please send Sheena her corrected W2

### ISSUE THREAD

**Issue by strepanier03** [Expensify/App#15322]
### What

I contributed to the 401k so I believe I fall into the category of people who need a corrected W2 - this [post](https://expensify.slack.com/archives/C03SC9DVD/p1675164693472439).

I still haven't gotten my w2c in the mail and would like to go forward with my taxes. 

Can you please send it to me.

**Comment by saracouto** [comment]
I'll double check this week again with taxbandits to see if local taxes are fixed

**Comment by strepanier03** [comment]
Here's the one in our private repo - https://github.com/Expensify/Expensify/issues/264889
