### ISSUE TITLE
[HOLD #15358] [reportActionsCount] Optimistically add reportActionCount in requestMoney

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#15359]
Please see the [tracking issue](https://github.com/Expensify/App/issues/15352) for more. This is held until the sixth step of the roll-out plan is merged.

**Comment by JmillsExpensify** [comment]
@mountiny where does this fit in your queue at the moment? Should we see if anyone else is up for taking it on?

**Comment by mountiny** [comment]
I thought of this as an easy backlog issue, its still on hold https://github.com/Expensify/App/issues/15353

but once the time comes and I wont have time for other stuff I am happy to leave this to someone else

**Comment by JmillsExpensify** [comment]
Ah ok, great point that this is ultimately a backlog issue and on hold. That sounds like a plan.

**Comment by mountiny** [comment]
Still on hold

**Comment by mountiny** [comment]
Still on hold and maybe this might not even be implemented so moving to monthly

**Comment by mountiny** [comment]
on hold and not sure whats thte state of this one so since I got a lot of things on my plate I will unassign

**Comment by luacmartins** [comment]
Closing since this solution is not needed anymore.
