### ISSUE TITLE
[HOLD #15362] [reportActionCount] Don't show DM's with only 1 reportAction in options list (unless it is the currently viewed report)

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#15363]
Please see the [tracking issue](https://github.com/Expensify/App/issues/15352) for more. This is held until the penultimate step of the roll-out plan is merged.

**Comment by JmillsExpensify** [comment]
Still on hold.

**Comment by luacmartins** [comment]
Closing since this solution is not needed anymore - see [tracking issue](https://github.com/Expensify/App/issues/15352).
