### ISSUE TITLE
Payment issue for E/App Issue#15559

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#15592]
I created this issue for paying the reporting bonus to a contributor.

1. The contributor [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1677590122967419) an issue
2. Applause reported the same [issue](https://github.com/Expensify/App/issues/15559) 2 hours later
3. We reverted the PR which introduced the [regression](https://github.com/Expensify/App/issues/15559), so the bug is gone
4. We decided [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1677667729346909) that we want to pay the contributor because he reported the bug before Applause team

**Comment by cristipaval** [comment]
cc @gadhiyamanan

**Comment by dylanexpensify** [comment]
Sent invite for this @gadhiyamanan

**Comment by dylanexpensify** [comment]
We're all paid out and contract closed! Thanks!
