### ISSUE TITLE
Update the `#announce` rooms to only allow policy admins to post in the main channel

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#15822]
### Problem

When hosting large scale discussions with strangers, sometimes you want to just remain in control of the conversation but there is no channel where admins could have all the attention.

### Why is it important

Helps to ensure admins can deliver important information clearly.

### Solution

Let's make the `#announce` room only allow posts from admins.

**Comment by mountiny** [comment]
Havent got around to it yet

**Comment by mountiny** [comment]
Still not a priority

**Comment by mountiny** [comment]
Hopefully gonna start predesgin this week

**Comment by amyevans** [comment]
Got a bit tied up with other issues the past few days, will turn my attention here in earnest later this afternoon and tomorrow.

**Comment by amyevans** [comment]
Not complete, but I've made a good start on research and pre-design questions and am discussing with Vit.

**Comment by amyevans** [comment]
Dug into the data migration aspect today and continued fleshing out detailed design. Will post predesign tomorrow.

**Comment by amyevans** [comment]
Predesign: https://expensify.slack.com/archives/C04QEB4MJEQ/p1683225902753979

**Comment by mountiny** [comment]
I till unassign now but this is going ahead well, after EC3 I think we can follow up on this one faster

**Comment by amyevans** [comment]
Closing in favor of https://github.com/Expensify/Expensify/issues/282865
