### ISSUE TITLE
Vulnerability Report payment for E/E [E/E issue#264739]

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#15859]
- @tienifr payment for vulnerability report in Expensify/Expensify/issues/264739
- $1,000

**Comment by mallenexpensify** [comment]
@tienifr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~011dd8f37c3cb79430

**Comment by mallenexpensify** [comment]
Also.. for any employees seeing the name of the GH issue in the OP, it's not visible to non-employees.  Can you confirm please @tienifr ?

Here's what I see when I view the issue in an incognito window
https://www.screencast.com/t/E2oMyYoowJ9g

**Comment by tienifr** [comment]
@mallenexpensify yes I see the same as your screenshot

**Comment by mallenexpensify** [comment]
Thanks @tienifr , paid.
