### ISSUE TITLE
[$250] Migrate Button.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16121]
### Filenames
- [ ] [src/components/Button.js](https://github.com/Expensify/App/blob/main/src/components/Button.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by kuluruvineeth** [comment]
@marcaaron https://github.com/Expensify/App/blob/main/src/components/Button.js this file is not found in main branch of the repository is it moved to different component or renamed to new component.

**Comment by securitybeautystar** [comment]
### **Proposal**
Hi, I'd like to finish this task.
Certainly, it's a good practice to refactor class components to function components using React Hooks as they make your code cleaner and easier to understand. 
Let's assume your Button.js class component currently looks something like this:

jsx
Copy code
import React from 'react';

class Button extends React.Component {
  componentDidMount() {
    // Some code here
  }

  componentWillUnmount() {
    // Some code here
  }

  render() {
    return (
      <button>{this.props.children}</button>
    );
  }
}

export default Button;
Following the advice from the React documentation you provided, the refactored functional component with hooks might look like this:

jsx
Copy code
import React, { useEffect } from 'react';

const Button = (props) => {
  useEffect(() => {
    // Equivalent to componentDidMount
    // Some code here

    return () => {
      // Equivalent to componentWillUnmount
      // Some code here
    };
  }, []);  // The empty array causes this effect to only run once on mount and unmount

  return (
    <button>{props.children}</button>
  );
};

export default Button;
In this refactored version, we use the useEffect hook. The function passed to useEffect will run after the render is committed to the screen (acting like componentDidMount). If you return a function from useEffect, React will run it when it is cleaning up the component (acting like componentWillUnmount).

Once you have made these changes, you should test the component thoroughly to ensure that no functionality was broken during the refactoring process. This could involve manual testing, or running an existing suite of automated tests if you have them.

**Comment by vdem0115** [comment]
I'd like to work on this issue

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by marcaaron** [comment]
Looks like this file no longer exists so closing this out.

**Comment by fabioh8010** [comment]
@marcaaron Could you reopen this issue and assign to me please? It turns out that [the file still exists](https://github.com/Expensify/App/blob/main/src/components/Button/index.js) and I need to migrate it to function component before migrating to TS. Thanks!

**Comment by marcaaron** [comment]
Sounds good. Feel free to get me for the final merge!

**Comment by fabioh8010** [comment]
@marcaaron PR is now ready to review!

**Comment by marcaaron** [comment]
Thanks for catching that one @parasharrajat - sorry for the delay!

**Comment by marcaaron** [comment]
@dylanexpensify this is not a bug - @parasharrajat just needs payment for the C+ review on the linked PR Thanks!

**Comment by dylanexpensify** [comment]
Ahh apologies! Will get payment going!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @parasharrajat $500

Please request!

**Comment by JmillsExpensify** [comment]
$250 payment approved for @parasharrajat based on summary above.
