### ISSUE TITLE
[$250] Migrate DragAndDrop to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16142]
### Filenames
- [ ] [src/components/DragAndDrop/index.js](https://github.com/Expensify/App/blob/main/src/components/DragAndDrop/index.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175ef7de3aea53b93</li>
        <li>Upwork Job ID: 1691269822034804736</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I'd like to work on this issue

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by KrAbhas** [comment]
I would like to work on this

**Comment by jczekalski** [comment]
Hey! I’m from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by gadhiyamanan** [comment]
i think there is [regression](https://expensify.slack.com/archives/C049HHMV9SM/p1690610169591779) due to [this PR](https://github.com/Expensify/App/pull/23589)
cc: @roryabraham @AndrewGable @allroundexperts

**Comment by roryabraham** [comment]
This is already done, we just need to pay @allroundexperts for reviewing. There were a couple regressions caused by this (my bad), so I think that means we should pay 50%

**Comment by bfitzexpensify** [comment]
Cool. @allroundexperts eligible for internal payment for $1000, to be made via manual request.

**Comment by JmillsExpensify** [comment]
Reviewed the details for @allroundexperts. $1,000 approved for payment in NewDot based on the BZ summary above.
