### ISSUE TITLE
[HOLD][$250] Migrate index.native.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16146]
### Filenames
- [ ] [src/components/EmojiPicker/EmojiPickerMenu/index.native.js](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.native.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by vdem0115** [comment]
I'd like to work on this issue

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by KrAbhas** [comment]
I can work on this

**Comment by shubham1206agra** [comment]
Please close this https://github.com/Expensify/App/pull/23854
