### ISSUE TITLE
[HOLD for payment 2023-06-08] [$250] Migrate ExceededCommentLength.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16149]
### Filenames
- [ ] [src/components/ExceededCommentLength.js](https://github.com/Expensify/App/blob/main/src/components/ExceededCommentLength.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by mountiny** [comment]
Gonna help SWM get this component migrated

**Comment by szebniok** [comment]
Hey, I'll work on this

**Comment by mountiny** [comment]
Assigning Bug to help with payment here. its going to be $250 to @rushatgabhane once we are there, thanks!

**Comment by mountiny** [comment]
Not due for payment yet

**Comment by anmurali** [comment]
@mountiny is this ready to be paid now?

**Comment by mountiny** [comment]
@anmurali now its ready $250 for Rushat

**Comment by mountiny** [comment]
@anmurali Bumping the payment for Rushate here

**Comment by mountiny** [comment]
LEts use this for global reimbursement testing, making this weekly

**Comment by anmurali** [comment]
Paid @rushatgabhane  via New Dot
