### ISSUE TITLE
[$250] Migrate BaseOnfidoWeb.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16177]
### Filenames
- [ ] [src/components/Onfido/BaseOnfidoWeb.js](https://github.com/Expensify/App/blob/main/src/components/Onfido/BaseOnfidoWeb.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by rayane-djouah** [comment]
@hayata-suenaga I would love to take this if you don't have time for it.

**Comment by hayata-suenaga** [comment]
@rayane-djouah I just started working on this but I appreciate your initiative 👍

**Comment by hayata-suenaga** [comment]
waiting for review

**Comment by hayata-suenaga** [comment]
I assigned a C+ member to assist with the review

**Comment by hayata-suenaga** [comment]
getting down on this today

**Comment by hayata-suenaga** [comment]
waiting for review
