### ISSUE TITLE
[HOLD for payment 2023-07-24] [$250] Migrate LHNOptionsList.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16174]
### Filenames
- [ ] [src/components/LHNOptionsList/LHNOptionsList.js](https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/LHNOptionsList.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by alexxxwork** [comment]
I would love to work on this issue

**Comment by Skalakid** [comment]
Hey! I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by anmurali** [comment]
Approved to pay $250 to Rushat on 24th for reviewing https://github.com/Expensify/App/pull/20434

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter: N/A 
-  Contributor that fixed the issue: N/A 
-  Contributor+ that helped on the issue and/or PR: @rushatgabhane $250

Upwork Job: N/A 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: @JmillsExpensify - I was chatting with @srikarparsi and he realized there needed to be a payment summary here. I'm inputting it as a member of BZ. With that said, we are not 100% sure if this one was paid yet. @rushatgabhane can you please confirm if the payment was sent before Anu went on OOO. Thank you!

**Comment by srikarparsi** [comment]
^no longer overdue

**Comment by JmillsExpensify** [comment]
@rushatgabhane I see this one in NewDot, but I can't seem to find the report it's on yet (we just merged the PR where we link to the report from the request, won't be on staging for another day).

**Comment by JmillsExpensify** [comment]
Same btw. @rushatgabhane Please create another request and delete any historical ones if this still doesn't exist on NewDot.

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
@rushatgabhane Did you want to create a request in NewDot for this one?

**Comment by rushatgabhane** [comment]
sorry for the delay, i created a manual request here - https://staging.new.expensify.com/r/6577722882327392

**Comment by JmillsExpensify** [comment]
Great thanks! Payment summary for this issue: $250 for component migration. It's approved for payment in NewDot.
