### ISSUE TITLE
[HOLD for payment 2023-10-16] [$250] Migrate index.website.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16179]
### Filenames
- [ ] [src/components/Onfido/index.website.js](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.website.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d9c5776c6703910</li>
        <li>Upwork Job ID: 1709881299188641792</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 27035470</li>
</ul></li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I would like to work on this issue.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by t1nyTi** [comment]
I hope to work on this task.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mtauhidul** [comment]
I can solve this

**Comment by mtauhidul** [comment]
Contributor details
Your Expensify account email: mislam.tauhidul@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014d7a947089fc4227

**Comment by cubuspl42** [comment]
This issue doesn't have the "Help wanted" label and is already being handled.

**Comment by sakluger** [comment]
Paid @cubuspl42 via Upwork with the speed bonus. Thanks everyone!
