### ISSUE TITLE
[HOLD for payment 2023-09-06] [$250] Migrate BaseOptionsList.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16182]
### Filenames
- [ ] [src/components/OptionsList/BaseOptionsList.js](https://github.com/Expensify/App/blob/main/src/components/OptionsList/BaseOptionsList.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`,`shouldComponentUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01761633017db59b18</li>
        <li>Upwork Job ID: 1691923161377251328</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Migrate BaseOptionsList.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should update https://github.com/Expensify/App/blob/main/src/components/OptionsList/BaseOptionsList.js to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I can work on this issue

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by Vishrut19** [comment]
Can I work on this?

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by SosenWiosen** [comment]
Hi, I'm from Software Mansion, an expert agency. I'd like to work on this.

**Comment by code0406** [comment]
I can work on this task.

**Comment by BEEG3R** [comment]
I'd love to take this task.

**Comment by BEEG3R** [comment]
Contributor details
Your Expensify account email: ybafrank@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01242f81d4a2592f18

**Comment by SosenWiosen** [comment]
PR #25401 ready for review :)

**Comment by blazejkustra** [comment]
@rushatgabhane Could you take a look on the PR? 😄

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @rushatgabhane based on BZ summary.

**Comment by JmillsExpensify** [comment]
@NicMendonca I think that summary is incorrect, right? Why is this $1,000 vs $250?

**Comment by JmillsExpensify** [comment]
$250 payment approved for @rushatgabhane based on BZ summary.
