### ISSUE TITLE
[HOLD][$250] Migrate OpacityView.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16180]
### Filenames
- [ ] [src/components/OpacityView.js](https://github.com/Expensify/App/blob/main/src/components/OpacityView.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I can work on this issue.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by jczekalski** [comment]
@marcaaron This component is already a functional component, so I think this issue can be closed.
