### ISSUE TITLE
[HOLD for payment 2023-07-14] [$250] Migrate BaseTextInput.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16205]
### Filenames
- [ ] [src/components/TextInput/BaseTextInput.js](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by mountiny** [comment]
Margelo is working on [this one](https://github.com/Expensify/App/pull/20186) as its a handy pre-requisite to one performance bug they want to resolve.

**Comment by mountiny** [comment]
Margelo is an expert agency and they will handle this migration as part of fixing a gnarly old bug in the app.

**Comment by hannojg** [comment]
👋

**Comment by mountiny** [comment]
Assigning also Rajat as they have helped with the review too!

**Comment by mountiny** [comment]
Merged

**Comment by mountiny** [comment]
Or actually sorry for the ping, I think the payment will be handled in this issue https://github.com/Expensify/App/issues/16696 which was the main reason for this PR and the bounty is way higher there and can be incorporated I think
