### ISSUE TITLE
[$250] Migrate BaseVideoChatButtonAndMenu.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16215]
### Filenames
- [ ] [src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/main/src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018423f6f3f85f8aca</li>
        <li>Upwork Job ID: 1673400279055613952</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by neonbhai** [comment]
I would like to work on this!

**Comment by olexyt** [comment]
I would like to work on this.

**Comment by asadath1395** [comment]
I would love to work on this. Can i get this assigned?

**Comment by mollfpr** [comment]
@puneetlath Who is going to be the winner?

**Comment by puneetlath** [comment]
Looks like @s-alves10 has 3 active issues assigned currently. So let's go with @neonbhai since they are the earliest poster who isn't currently working on any issues for us.

**Comment by mollfpr** [comment]
@neonbhai Any update on the PR?

**Comment by puneetlath** [comment]
@neonbhai will you be able to raise a PR in the next 48 hours? If not, I'll go ahead and assign someone else. Just let us know. Thanks!

**Comment by neonbhai** [comment]
Hey @mollfpr @puneetlath yes. the PR is almost done. I'm just collecting the testing screenshots. The PR will be up in 24 hours!

**Comment by puneetlath** [comment]
Great!

**Comment by neonbhai** [comment]
Hi @mollfpr @puneetlath, Please review the [PR](https://github.com/Expensify/App/pull/22025)!

**Comment by puneetlath** [comment]
@mollfpr let me know when you think you'll be done reviewing.

**Comment by neonbhai** [comment]
Hi @puneetlath it has been 2+ weeks since the PR was merged! Can I please get paid on upwork?

**Comment by puneetlath** [comment]
Oh, weird, sorry about that! Usually an automation runs to let me know it's time to pay.

**Comment by puneetlath** [comment]
Upwork contracts sent. Sorry again for the delay!

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
