### ISSUE TITLE
[HOLD for payment 2023-08-21] [$250] Migrate ThumbnailImage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16210]
### Filenames
- [ ] [src/components/ThumbnailImage.js](https://github.com/Expensify/App/blob/main/src/components/ThumbnailImage.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by kadiealexander** [comment]
Not overdue, close to having a PR up!

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by kadiealexander** [comment]
Created a draft PR to discuss with @puneetlath next week.

**Comment by marcaaron** [comment]
Taking this one off HOLD.

**Comment by kadiealexander** [comment]
I have a [PR ](https://github.com/Expensify/App/pull/20892)in for this, just need to do a bit of testing :)

**Comment by vdem0115** [comment]
I can work on this issue now.

**Comment by kadiealexander** [comment]
Working through some testing issues that have cropped up, I think due to the new ZT trial.

**Comment by kadiealexander** [comment]
@allroundexperts could you please check [this](https://github.com/Expensify/App/pull/9346#discussion_r1278862036) comment?

**Comment by Christinadobrzyn** [comment]
It looks like we might have a regression of this [here](https://github.com/Expensify/App/issues/24424) - can you check if that's the case?

**Comment by kadiealexander** [comment]
Yeah, that's the case. cc @s77rt @MonilBhavsar

**Comment by s77rt** [comment]
@kadiealexander I have explained the cause of the regression here https://github.com/Expensify/App/issues/24424#issuecomment-1675538625 and we have a fix for that issue already https://github.com/Expensify/App/pull/24466.

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: n/a
Contributor: n/a
Contributor+: $250 @s77rt 

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/ab/applicants/1693802291271536640/hires?filter=Abdel&page=1).

**Comment by s77rt** [comment]
@kadiealexander We had a regression here. Can you please update the price to $125

**Comment by kadiealexander** [comment]
Done, thanks for flagging @s77rt!

**Comment by s77rt** [comment]
@kadiealexander i have accepted the offer. Thanks!

**Comment by kadiealexander** [comment]
All paid!
