### ISSUE TITLE
[HOLD for payment 2023-08-21] [$250] Migrate AdditionalDetailsStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16231]
### Filenames
- [ ] [src/pages/EnablePayments/AdditionalDetailsStep.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/AdditionalDetailsStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddb468a7b05692a6</li>
        <li>Upwork Job ID: 1687529728271044608</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by neonbhai** [comment]
I would like to work on this.

**Comment by dayana7204** [comment]
I am ready to work on this ticket. :)

**Comment by Shubhranshu2000** [comment]
Can I work on this?

**Comment by Shubhranshu2000** [comment]
Contributor details
Your Expensify account email: shubhranshupaidlancer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b80b4cc418e7d5fb

**Comment by vdem0115** [comment]
I can work on this.

**Comment by disha-np** [comment]
I'd like to work on this issue

**Comment by alpeshl** [comment]
can I work on this

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by KrAbhas** [comment]
May I work on this?

**Comment by SosenWiosen** [comment]
Hi, I'm from Software Mansion, an expert agency. I'd like to work on this :)

**Comment by Elyas-Demeke** [comment]
here are the steps I will follow to convert the component to a function component:

Remove the class keyword.
Remove the render() method.
Convert all methods to functions.
Remove all references to this.
Remove the constructor.
Remove event handler bindings.
Replace this.setState() with useState().
Replace lifecycle methods with hooks.

**Comment by codewithwaheed** [comment]
I would like to work on this one

**Comment by Elyas-Demeke** [comment]
Contributor details
Your Expensify account email: nebiyou.elyas11@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018cb7365e0e8298cf

**Comment by Elyas-Demeke** [comment]
here are the steps I will follow to convert the component to a function component:

Remove the class keyword.
Remove the render() method.
Convert all methods to functions.
Remove all references to this.
Remove the constructor.
Remove event handler bindings.
Replace this.setState() with useState().
Replace lifecycle methods with hooks.

**Comment by Muhammad-Awais-Awan** [comment]
Contributor details
Your Expensify account email: [iam4pak@gmail.com](url)
Upwork Profile Link: [https://www.upwork.com/freelancers/~0100ec54dabcbc04f0](url)

**Comment by Muhammad-Awais-Awan** [comment]
Contributor details
Your Expensify account email:  iam4pak@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0100ec54dabcbc04f0

**Comment by Muhammad-Awais-Awan** [comment]
### GENERATED BY GPT : (Its the draft of functional component)
In PR i will provide you complete code with full functionality

import _ from 'underscore';
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { withOnyx } from 'react-native-onyx';
import { View } from 'react-native';
import moment from 'moment/moment';
import { parsePhoneNumber } from 'awesome-phonenumber';
import IdologyQuestions from './IdologyQuestions';
import ScreenWrapper from '../../components/ScreenWrapper';
import HeaderWithBackButton from '../../components/HeaderWithBackButton';
import withLocalize, { withLocalizePropTypes } from '../../components/withLocalize';
import styles from '../../styles/styles';
import Text from '../../components/Text';
import CONST from '../../CONST';
import compose from '../../libs/compose';
import ONYXKEYS from '../../ONYXKEYS';
import TextLink from '../../components/TextLink';
import TextInput from '../../components/TextInput';
import * as Wallet from '../../libs/actions/Wallet';
import * as ValidationUtils from '../../libs/ValidationUtils';
import * as ErrorUtils from '../../libs/ErrorUtils';
import AddressForm from '../ReimbursementAccount/AddressForm';
import DatePicker from '../../components/DatePicker';
import Form from '../../components/Form';
import withCurrentUserPersonalDetails, { withCurrentUserPersonalDetailsPropTypes, withCurrentUserPersonalDetailsDefaultProps } from '../../components/withCurrentUserPersonalDetails';
import * as PersonalDetails from '../../libs/actions/PersonalDetails';
import OfflineIndicator from '../../components/OfflineIndicator';

const propTypes = {
    ...withLocalizePropTypes,
    ...withCurrentUserPersonalDetailsPropTypes,

    // Rest of the propTypes
};

const defaultProps = {
    walletAdditionalDetails: {
        errorFields: {},
        isLoading: false,
        errors: {},
        questions: [],
        idNumber: '',
        errorCode: '',
    },
    ...withCurrentUserPersonalDetailsDefaultProps,
};

const INPUT_IDS = {
    // Rest of the INPUT_IDS
};

const AdditionalDetailsStep = (props) => {
    const [minDate] = useState(moment().subtract(CONST.DATE_BIRTH.MAX_AGE, 'Y').toDate());
    const [maxDate] = useState(moment().subtract(CONST.DATE_BIRTH.MIN_AGE_FOR_PAYMENT, 'Y').toDate());

    const errorTranslationKeys = {
        // Rest of the errorTranslationKeys
    };

    const fieldNameTranslationKeys = {
        // Rest of the fieldNameTranslationKeys
    };

    const validate = (values) => {
        // Rest of the validate function
    };

    const activateWallet = (values) => {
        // Rest of the activateWallet function
    };

    if (!_.isEmpty(props.walletAdditionalDetails.questions)) {
        return (
            <ScreenWrapper
                style={[styles.flex1]}
                keyboardAvoidingViewBehavior="height"
            >
                <HeaderWithBackButton
                    title={props.translate('additionalDetailsStep.headerTitle')}
                    onBackButtonPress={() => Wallet.setAdditionalDetailsQuestions(null)}
                />
                <IdologyQuestions
                    questions={props.walletAdditionalDetails.questions}
                    idNumber={props.walletAdditionalDetails.idNumber}
                />
            </ScreenWrapper>
        );
    }
    const shouldAskForFullSSN = props.walletAdditionalDetails.errorCode === CONST.WALLET.ERROR.SSN;

    return (
        <>
            <HeaderWithBackButton title={props.translate('additionalDetailsStep.headerTitle')} />
            <View style={[styles.flex1]}>
                <View style={[styles.ph5]}>
                    <Text style={styles.mb3}>{props.translate('additionalDetailsStep.helpText')}</Text>
                    <TextLink
                        style={styles.mb3}
                        href="https://use.expensify.com/usa-patriot-act"
                    >
                        {props.translate('additionalDetailsStep.helpLink')}
                    </TextLink>
                </View>
                <Form
                    formID={ONYXKEYS.WALLET_ADDITIONAL_DETAILS}
                    validate={validate}
                    onSubmit={activateWallet}
                    scrollContextEnabled
                    submitButtonText={props.translate('common.saveAndContinue')}
                    style={[styles.mh5, styles.flexGrow1]}
                >
                    <TextInput
                        inputID={INPUT_IDS.LEGAL_FIRST_NAME}
                        containerStyles={[styles.mt4]}
                        label={props.translate(fieldNameTranslationKeys.legalFirstName)}
                        accessibilityLabel={props.translate(fieldNameTranslationKeys.legalFirstName)}
                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
                        defaultValue={PersonalDetails.extractFirstAndLastNameFromAvailableDetails(props.currentUserPersonalDetails).firstName}
                        shouldSaveDraft
                    />
                    {/* Rest of the JSX */}
                    <OfflineIndicator containerStyles={[styles.mh5, styles.mb3]} />
                </Form>
            </View>
        </>
    );
};

AdditionalDetailsStep.propTypes = propTypes;
AdditionalDetailsStep.defaultProps = defaultProps;

export default compose(
    withLocalize,
    withCurrentUserPersonalDetails,
    withOnyx({
        walletAdditionalDetails: {
            key: ONYXKEYS.WALLET_ADDITIONAL_DETAILS,
        },
    }),
)(AdditionalDetailsStep);

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [concierge@expensify.com](mailto:concierge@expensify.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [iam4pak@gmail.com](faction_tall813@simplelogin.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [concierge@expensify.com](faction_tall813@simplelogin.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [fullstack.dev1993@gmail.com](mailto:fullstack.dev1993@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [fullstack.dev1993@gmail.com](mailto:fullstack.dev1993@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Contributor details
Your Expensify account email: [faction_tall813@simplelogin.com](mailto:faction_tall813@simplelogin.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0118a3b63494ce86d7

**Comment by adamzebolsky919** [comment]
Why can I access? I think, I am correct.

**Comment by romitgithub** [comment]
Contributor details
Your Expensify account email: choudharyromit@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by romitgithub** [comment]
Contributor details
Your Expensify account email: [choudharyromit@gmail.com](mailto:choudharyromit@gmail.com)
Upwork Profile Link: https://upwork.com/freelancers/~01b7c2a45e48a0d1d1

**Comment by payal-lathidadiya** [comment]
can I work on this

**Comment by SosenWiosen** [comment]
@allroundexperts Do you mean that Anshu should do this issue? I'm already assigned and working on a PR.

**Comment by marcaaron** [comment]
No. @allroundexperts please look at the issue comment history **in it's entirety** before recommending a hire. Thanks!

**Comment by johncschuster** [comment]
# Summary of payments:

@allroundexperts will request payment of $250 via NewDot

CC @JmillsExpensify

**Comment by marcaaron** [comment]
I think we're all set here? Gonna close. Feel free to reopen if there's anything left!

**Comment by JmillsExpensify** [comment]
Reviewed the details for @allroundexperts. $250 approved for payment in NewDot based on the BZ summary above.
