### ISSUE TITLE
[HOLD for payment 2023-10-12] [$250] Migrate IdologyQuestions.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16233]
### Filenames
- [ ] [src/pages/EnablePayments/IdologyQuestions.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/IdologyQuestions.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01395e41039b03d05d</li>
        <li>Upwork Job ID: 1705098274459115520</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by neonbhai** [comment]
I can work on this if this opens up!

**Comment by dayana7204** [comment]
I am ready to work on this ticket. :)

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by KrAbhas** [comment]
I would like to work on this

**Comment by barttom** [comment]
Hello!
I'm Bartek from Callstack - an expert contributor group and I would like to work on this one.

**Comment by alexxxwork** [comment]
Dibs

**Comment by nebiyuelias1** [comment]
Dibs

**Comment by marcaaron** [comment]
This can be a weekly. We are just waiting for a PR.

**Comment by adelekennedy** [comment]
@marcaaron - is any Upwork/NewDot payment required here? It doesn't look like it to me

**Comment by marcaaron** [comment]
I agree!
