### ISSUE TITLE
[HOLD for payment 2023-07-14] [$250] Migrate NewChatPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16239]
### Filenames
- [ ] [src/pages/NewChatPage.js](https://github.com/Expensify/App/blob/main/src/pages/NewChatPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e875c428c833da0</li>
        <li>Upwork Job ID: 1664707231797780480</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by thienlnam** [comment]
Thanks @marcaaron! I will have to counter your offer, unfortunately I can only do this for the original $1000. Thank you for your consideration and please let me know

**Comment by marcaaron** [comment]
👢

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by Nikhil-Vats** [comment]
Hey @thienlnam 👋, I can take this up if you don't have time for this.

**Comment by thienlnam** [comment]
Thanks for the ping, that would be great actually

**Comment by multijump** [comment]
I would like to take this issue

**Comment by multijump** [comment]
Contributor details
Your Expensify account email: oleh.koziar@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~0168534bdf28bd4cf8

**Comment by multijump** [comment]
Contributor details
Your Expensify account email: multijump2022@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~0168534bdf28bd4cf8

**Comment by multijump** [comment]
Contributor details
Your Expensify account email: oleh.koziar@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0168534bdf28bd4cf8?viewMode=1

**Comment by multijump** [comment]
Contributor details
Your Expensify account email: multijump2022@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0168534bdf28bd4cf8

**Comment by chychkoi** [comment]
I'd like to work on this issue

**Comment by Nikhil-Vats** [comment]
Hi @chychkoi 👋, this one has been already assigned but you can look for other jobs with External and Help wanted labels and if it is a migration issue then the first one who asks gets the job! More info [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by Nikhil-Vats** [comment]
I have applied to this job on upwork and will have the PR ready for review by Monday.

**Comment by MahmudjonToraqulov** [comment]
I'd like to work on this issue

**Comment by twisterdotcom** [comment]
Same as here @MahmudjonToraqulov: https://github.com/Expensify/App/issues/16239#issuecomment-1574202242.

**Comment by Nikhil-Vats** [comment]
Hey @thienlnam @aimane-chnaif @twisterdotcom, I have [created the PR](https://github.com/Expensify/App/pull/20170) and I will add the screenshots/videos for all platforms now but I have left a few comments on some choices I wanted to get your feedback on.

Also, by mistake I clicked the Create PR button before referencing issue so the PullerBear didn't work, so can you assign yourself please?

**Comment by Nikhil-Vats** [comment]
All videos and test proofs added now.

**Comment by Nikhil-Vats** [comment]
@thienlnam @twisterdotcom @aimane-chnaif friendly bump!

**Comment by twisterdotcom** [comment]
@aimane-chnaif would you like this review reassigned?

**Comment by Nikhil-Vats** [comment]
Friendly bump!

**Comment by Nikhil-Vats** [comment]
In review

**Comment by twisterdotcom** [comment]
Waiting for @aimane-chnaif to review. Let me know if this needs reassigning @aimane-chnaif!

**Comment by twisterdotcom** [comment]
Last update was 2 days ago: https://github.com/Expensify/App/pull/20170#issuecomment-1601320119. Just waiting on reviews from @aimane-chnaif and @thienlnam.

**Comment by twisterdotcom** [comment]
Last update was 19 hours ago: https://github.com/Expensify/App/pull/20170#issuecomment-1606116329

**Comment by Nikhil-Vats** [comment]
I will update the PR tomorrow morning.

**Comment by twisterdotcom** [comment]
I am OOO! Adding another BZ for the week.

**Comment by CortneyOfstad** [comment]
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by greg-schroeder** [comment]
C+ review is complete, waiting on @thienlnam to confirm and merge I believe

**Comment by thienlnam** [comment]
Just merged!

**Comment by greg-schroeder** [comment]
Awaiting deploy to prod

**Comment by twisterdotcom** [comment]
@aimane-chnaif not listed here: https://github.com/Expensify/Web-Expensify/blob/main/_devportal/lib/KernelScheduling/Data.php#L242.

Sending Upwork offer: https://www.upwork.com/en-gb/nx/wm/pre-hire/c/8577561/offer/25535772

@Nikhil-Vats - Upwork offer here: https://www.upwork.com/en-gb/nx/wm/pre-hire/c/8577561/offer/25535788

**Comment by Nikhil-Vats** [comment]
Accepted @twisterdotcom

**Comment by twisterdotcom** [comment]
Yes sorry, it's the newDot payment one. Just for my own sanity @aimane-chnaif!

**Comment by twisterdotcom** [comment]
Paid out!
