### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$250] Migrate RequestorOnfidoStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16246]
### Filenames
- [ ] [src/pages/ReimbursementAccount/RequestorOnfidoStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/RequestorOnfidoStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108c7eff871f84756</li>
        <li>Upwork Job ID: 1702336246230073344</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by neonbhai** [comment]
I can work on this!

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by pradeepmdk** [comment]
i will work on this

**Comment by barttom** [comment]
Hi! I'm Bartek from Callstack - an expert contributor group and I would like to work on this one.

**Comment by barttom** [comment]
Contributor details
Your Expensify account email: bartlomiej.tomczyk@callstack.com

**Comment by Rose-Miller-web-dev** [comment]
### Proposal
### Issue
Migration from RequestorOnfidoStep.js class to function

### Solution
Create a function corresponding the class and migrate the functionalities to it in addition to updating the references to the class
for instance if there is some import in a component like below
`import {RequestorOnfidoStep}`
then it should become
`import RequestorOnfidoStep`

Upwork Profile: https://www.upwork.com/freelancers/rosemiller
Expensify Email: thisisrosemiller@gmail.com

**Comment by jliexpensify** [comment]
Someone has already been assigned to work on this

**Comment by jliexpensify** [comment]
This isn't overdue right? Also, is any payment from me needed? Sobit takes New.Dot and @barttom invoices us right?

**Comment by barttom** [comment]
Hey @jliexpensify!
This issue is on me, I just need to merge main branch into mine fetuje branch, but I’m on OOO until end of this week

**Comment by jliexpensify** [comment]
No worries! Thanks for letting us know. @barttom just to confirm that you invoice us for payment, correct?

**Comment by barttom** [comment]
@jliexpensify I’m a part of callstack team, so I afaik they are care of invoices 😉

**Comment by jliexpensify** [comment]
Cool, in that case - Payment Summary:

- Contributor: @barttom Invoiced payment
- C+: @sobitneupane $250 New.Dot payment

No Upworks job needed here.

**Comment by jliexpensify** [comment]
Hi @sobitneupane @barttom just checking: this hasn't been competed/implemented right?

**Comment by barttom** [comment]
@jliexpensify It has been merged

**Comment by Pujan92** [comment]
@barttom As it is still in the regression period, I found a console warning and reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1697636190219869).

Reason: We switched to `useLocalize` and removed `withLocalize` but `StepPropTypes` expects a prop `withLocalizePropTypes` which is now missing.

**Comment by jliexpensify** [comment]
Hmm just to confirm: there's a regression related tot his GH? So payment should be adjusted to $125?

**Comment by jliexpensify** [comment]
Payment Summary (assuming there's a regression)

- Contributor: @barttom $125 (Callstack invoiced payment)
- C+: @sobitneupane $125 (New.Dot payment)

NO UPWORKS JOB

**Comment by sobitneupane** [comment]
@jliexpensify I wasn't assigned to the PR, and I didn't review it. Therefore, no payment is due to me.

**Comment by jliexpensify** [comment]
Fixed, thanks for letting me know!
