### ISSUE TITLE
[HOLD for payment 2023-09-07] [$250] Migrate CompanyStep.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16243]
### Filenames
- [ ] [src/pages/ReimbursementAccount/CompanyStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/CompanyStep.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c608743b932b3bd2</li>
        <li>Upwork Job ID: 1690065179524182016</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26074027</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate CompanyStep.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should update [src/pages/ReimbursementAccount/CompanyStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/CompanyStep.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by MahmudjonToraqulov** [comment]
I'd like to work on this

**Comment by payal-lathidadiya** [comment]
I'd like to work on this migration issue

**Comment by vdem0115** [comment]
I would like to work on this.

**Comment by alpeshl** [comment]
can I work on this?

**Comment by alpeshl** [comment]
Contributor details
Your Expensify account email: lprocksit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0163c63a1aba82906b

**Comment by disha-np** [comment]
I can pick this migration ticket

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by kowczarz** [comment]
Hi @marcaaron! I'm from Software Mansion and I would like to work on this task.

**Comment by expertscoders** [comment]
I'd like to work on this

**Comment by codesrocket** [comment]
I'd like to work on this.

**Comment by BhuvaneshPatil** [comment]
dibs

**Comment by creativebull** [comment]
Hi! I'd like to work on this project. Could you give me a chance to handle it?

**Comment by Mercurial** [comment]
Contributor details
Your Expensify account email: clark_alesna@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019991dec3a2496a79

**Comment by greg-schroeder** [comment]
I think this is being handled by SWM

**Comment by cubuspl42** [comment]
@greg-schroeder In such a case, what's in the scope of my assignment? Will I review the eventual PR?

**Comment by greg-schroeder** [comment]
Hey @marcaaron can you clarify on this one? Is this a SWM issue or do we need to pick a contributor to do this?

**Comment by marcaaron** [comment]
@greg-schroeder correct, it's all assigned out so no need contributors.

@cubuspl42 as C+, please review and test the PR, and tag me when it's ready for me to look at!

Thanks 🙇

**Comment by greg-schroeder** [comment]
PR review is still underway

**Comment by greg-schroeder** [comment]
Awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment]
Processing payments

**Comment by greg-schroeder** [comment]
@cubuspl42 Paid!
