### ISSUE TITLE
[HOLD for payment 2023-12-29] [$250] Migrate SearchPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16251]
### Filenames
- [ ] [src/pages/SearchPage.js](https://github.com/Expensify/App/blob/main/src/pages/SearchPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fa113b288776a75</li>
        <li>Upwork Job ID: 1681356452396900352</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by Piotrfj** [comment]
Hi I'm Piotr from Callstack - expert contributor group - will start investigation in this area

**Comment by disha-np** [comment]
Can I work on this?

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by payal-lathidadiya** [comment]
dibs?

**Comment by disha-np** [comment]
can I work on this

**Comment by alpeshl** [comment]
can I work on this

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by ishpaul777** [comment]
Would love to work on it

**Comment by payal-lathidadiya** [comment]
can i work on this?

**Comment by trjExpensify** [comment]
@marcaaron's what's the situation here? Do we need to remove `help wanted`?

**Comment by amanjaswalia** [comment]
Hello @marcaaron,

Here is my solution for this task in 6 steps :-
1) First we need to change class component into function component
**Example** : class SearchPage extends Component { } **to** const SearchPage = (props) => { };
2) Remove the render method but need to keep everything after including the return.
**Example** : class SearchPage extends Component {  render() { return (<p>Test</p>);} } **to** const SearchPage = (props) => { return (<p>Test</p>); };
3) After that In functional component we need to replace react life cycle method into hooks.
 **Example** :   componentDidUpdate(prevProps) { if (_.isEqual(prevProps.reports, this.props.reports) && _.isEqual(prevProps.personalDetails, this.props.personalDetails)) { return; } this.updateOptions();  } 
    **to**
useEffect(() => {
        updateOptions();
    }, [props.reports, props.personalDetails]);
4)  Convert all method to functions 
**Example** : onChangeText(searchValue = '') { } **to**   const onChangeText = (value) => {    };
5) Remove references to this
 **Example** :   onChangeText(searchValue = '') {
        this.setState({searchValue}, this.debouncedUpdateOptions);
    }
**to** 
 const onChangeText = (value) => { setSearchValue(value); debouncedUpdateOptions();};
 6)Remove event handler binding 
 **Example** : class SearchPage extends Component { 
 constructor(props) { 
    super(props); 
     this.searchRendered = this.searchRendered.bind(this);
     this.selectReport = this.selectReport.bind(this); 
  }
   } 
 **to** 
 const SearchPage = (props) => { 
  const searchRendered = () => {};
    const selectReport = () => {};
 };

**Comment by amanjaswalia** [comment]
Contributor details
Your Expensify account email: amanjaswalia@gmail.com
Upwork Profile Link: https://www.upwork.com/ab/proposals/job/~015fa113b288776a75

**Comment by amanjaswalia** [comment]
Hello @marcaaron ,

Here is my solution for this task in 6 steps :-

1) **First we need to change class component into function component.**
**Example** : class SearchPage extends Component { } **to** const SearchPage = (props) => { };

2) **Remove the render method but need to keep everything after including the return.**
**Example** : class SearchPage extends Component { render() { return (<p>Test</p>);} } **to** const SearchPage = (props) => { return (<p>Test</p>); };

3) **After that In functional component we need to replace react life cycle method into hooks.**
**Example** : componentDidUpdate(prevProps) { if (_.isEqual(prevProps.reports, this.props.reports) && _.isEqual(prevProps.personalDetails, this.props.personalDetails)) { return; } this.updateOptions(); }
**to**
useEffect(() => {
updateOptions();
}, [props.reports, props.personalDetails]);

4) **Convert all method to functions.**
**Example** : onChangeText(searchValue = '') { } **to** const onChangeText = (value) => { };

5) **Remove references to this.**
**Example** : onChangeText(searchValue = '') {
this.setState({searchValue}, this.debouncedUpdateOptions);
}
**to**
const onChangeText = (value) => { setSearchValue(value); debouncedUpdateOptions();};

6) **Remove event handler binding.**
**Example** : class SearchPage extends Component {
constructor(props) {
super(props);
this.searchRendered = this.searchRendered.bind(this);
this.selectReport = this.selectReport.bind(this);
}
}
**to**
const SearchPage = (props) => {
const searchRendered = () => {};
const selectReport = () => {};
};

**Comment by priyagrovr** [comment]
Contributor details
Your Expensify account email: priya.grover1988@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/priyagrover77

**Comment by isabelastisser** [comment]
hey @Piotrfj, what's the process here? Are we waiting for more proposals?

**Comment by isabelastisser** [comment]
Bump, @Piotrfj, can you please follow up? Thanks!

**Comment by isabelastisser** [comment]
Hey @Piotrfj and @marcaaron, I'm not sure what are the next steps for this `New Feature` issue. Are we waiting for more proposals? Should we keep this at `Daily`?

**Comment by marcaaron** [comment]
Looks like the PR is in review [here](https://github.com/Expensify/App/pull/23076)

**Comment by Piotrfj** [comment]
@marcaaron PR is ready, take a look.
https://github.com/Expensify/App/pull/23076

**Comment by Piotrfj** [comment]
@marcaaron lint issues fixed, added back defaultProps.

**Comment by isabelastisser** [comment]
Hey @marcaaron, what are the next steps here? Can you please follow up on @Piotrfj comments above? Thanks!

**Comment by marcaaron** [comment]
Thanks, I'll check it out. Looks like it is has been ready for a review for some time. Usually people tag me on the reviews when things are ready 🙃. 

I also see that @allroundexperts is doing the review so they should be assigned here?

**Comment by marcaaron** [comment]
Oh but we are also in a "merge freeze" that the moment. So, even if the PR is ready I think we are not going to merge it yet 😬

**Comment by marcaaron** [comment]
PR is approved and ready, but HOLD subject to merge freeze see comment [here](https://github.com/Expensify/App/pull/23076#pullrequestreview-1612124332)

**Comment by amyevans** [comment]
Just wanted to close the loop on ^, we reverted the migration PR in https://github.com/Expensify/App/pull/27476

**Comment by marcaaron** [comment]
@Piotrfj let us know if you can look into the related issue that popped up and want to try again?

**Comment by Piotrfj** [comment]
@marcaaron Yeah, I will take a look as soon as i finish current issue, probably today or tomorrow

**Comment by Piotrfj** [comment]
@marcaaron I've fixed the issue, it was about unnecessary search functions calls on component mount, which was quite heavy for the app and could cause some lags.
Linkt to new PR: https://github.com/Expensify/App/pull/27924

**Comment by marcaaron** [comment]
PR is still open it seems. @Piotrfj are you still around? @allroundexperts I assume is ready to prioritize a review. Seems like it just slipped through the cracks.

**Comment by Umesh-Bhati** [comment]
Contributor details
Your Expensify account email: umeshbhati193@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1?s=996364627857502209

**Comment by marcaaron** [comment]
@Piotrfj are you still with us? I will give it a couple more days. But think we may need to treat this one as abandoned...

**Comment by marcaaron** [comment]
Oh no don't close it haha 😸 

We're back in the game and waiting for @allroundexperts now. 🚀 

Let's get to the finish line here!

**Comment by allroundexperts** [comment]
Yep. On my list for tomorrow!

**Comment by isabelastisser** [comment]
@allroundexperts @marcaaron what's next here?

**Comment by allroundexperts** [comment]
@isabelastisser The update is that @koko57 has taken over the PR and has resolved my pending comments. I'll take a look at it again tomorrow.

**Comment by isabelastisser** [comment]
Hey @allroundexperts, please provide an update. Thanks!

**Comment by allroundexperts** [comment]
I've approved the PR. @marcaaron requested some changes which were recently fixed by @koko57. The PR is ready for marc's review again.

**Comment by isabelastisser** [comment]
@allroundexperts please complete this task before I can close the issue. Thanks!

> [@allroundexperts] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

**Comment by isabelastisser** [comment]
Payment summary:

$250 to @allroundexperts for C+ review.

`requires payment through NewDot Manual Requests`

**Comment by isabelastisser** [comment]
Bump @allroundexperts to complete the checklist above.

**Comment by allroundexperts** [comment]
@isabelastisser I don't think that we have checklists for component migrations.

**Comment by JmillsExpensify** [comment]
$250 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/16251#issuecomment-1874376235).
