### ISSUE TITLE
[HOLD for payment 2023-06-21] [$250] Migrate SetPasswordPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16252]
### Filenames
- [ ] [src/pages/SetPasswordPage.js](https://github.com/Expensify/App/blob/main/src/pages/SetPasswordPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by yuwenmemon** [comment]
We're passwordless  now so just going to remove this component.
