### ISSUE TITLE
[HOLD for payment 2023-07-17] [$250] Migrate ReportActionsView.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16267]
### Filenames
- [ ] [src/pages/home/report/ReportActionsView.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`componentDidUpdate`,`shouldComponentUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5211f387b070380</li>
        <li>Upwork Job ID: 1673399672865730560</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by Vishrut19** [comment]
Dibs?

**Comment by wahaha999** [comment]
Can I work this?

**Comment by olexyt** [comment]
I love to work on this issue

**Comment by asadath1395** [comment]
I would love to work on this. Can i get this assigned?

**Comment by bernhardoj** [comment]
NOTE: we migrated `ReportScrollManager` to hook in this [PR](https://github.com/Expensify/App/pull/21227), but `ReportActionsView` is still a class component when we do the hook migration. To anyone that works on this functional migration, please replace `ReportScrollManager` with `userReportScrollManager` hook. Thanks!

**Comment by dayana7204** [comment]
I am ready to work on this ticket :)

**Comment by Elkaramany** [comment]
**Issue Description**
The current implementation of the ReportActionsView component is based on a class component. There is a request to refactor it into a function-based component to align with best practices and improve code readability.

**Proposed Solution**
To address the request, I propose refactoring the ReportActionsView component from a class component to a functional component. This can be achieved by converting the class declaration into a function declaration and rewriting the necessary lifecycle methods and state management logic.

**Refactoring Steps**

1. Remove the class declaration and replace it with a function declaration for the ReportActionsView component.
2. Remove the constructor and any associated state initialization code.
3. Replace the componentDidMount and componentWillUnmount methods with the appropriate useEffect hooks to handle the component's mount and unmount behavior.
4. Rewrite the state management logic using the useState hook to manage the necessary state variables.
5. Update the render method to return JSX directly from the function body.
6. Adjust the usage of this.props to directly reference the props received as function arguments.

Testing
To ensure the refactored component functions correctly, the following tests can be performed:

1. Verify that the refactored component renders without any errors or warnings.
2. Confirm that the functionality of the component remains unchanged after the refactoring.
3. Validate that the refactored component integrates properly with its parent components and passes down the required props.

**Comment by muttmuure** [comment]
@narefyev91 this is yours to pick an assignee. Let me know if you need any help!

**Comment by narefyev91** [comment]
@muttmuure @marcaaron based on this "the fact that no complex bug investigations or proposal are required" - we should choose first one person in thread who wants to work on this - @muxriddinmuqimov77 was the first one https://github.com/Expensify/App/issues/16267#issuecomment-1577956614 - we should assign him to work on this

**Comment by vdem0115** [comment]
I want to work on this issue.

**Comment by muttmuure** [comment]
@muxriddinmuqimov77 this one is yours. Please go ahead and submit your PR

**Comment by muttmuure** [comment]
I will check back every few days to see how this is going

**Comment by muttmuure** [comment]
@Vishrut19 was next. @Vishrut19 are you still available to work on this?

**Comment by Vishrut19** [comment]
Uh!yes I can but I am actually working on another issue. So can I take 2 issues together?

**Comment by muttmuure** [comment]
We prefer if people focus on 1 issue at a time, so I'm going to assign @rayane-djouah.

**Comment by muttmuure** [comment]
@rayane-djouah feel free to DM me in Slack with more details and I'll chat with the team

**Comment by muttmuure** [comment]
All done.
