### ISSUE TITLE
[HOLD for payment 2023-06-19] [HOLD][$250] Migrate ParticipantLocalTime.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16262]
### Filenames
- [ ] [src/pages/home/report/ParticipantLocalTime.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ParticipantLocalTime.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by aldo-expensify** [comment]
@lschurr  , this is a code refactor issue, and you only have to handle the payment to the C+ (@fedirjh) for reviewing the PRhttps://github.com/Expensify/App/pull/20300

**Comment by lschurr** [comment]
Invited you to the job in Upwork @fedirjh - https://www.upwork.com/jobs/~015fb2d6e9e5c0a140

**Comment by lschurr** [comment]
Not overdue. Payment will happen on Monday.

**Comment by lschurr** [comment]
@fedirjh - could you accept the offer for this job so that we can pay and close?

**Comment by lschurr** [comment]
Paid. Closing!
