### ISSUE TITLE
[HOLD][$250] Migrate IOUTransactions.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16277]
### Filenames
- [ ] [src/pages/iou/IOUTransactions.js](https://github.com/Expensify/App/blob/main/src/pages/iou/IOUTransactions.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue when it goes to external

**Comment by aldo-expensify** [comment]
This component doesn't exist anymore.
