### ISSUE TITLE
[HOLD for payment 2023-06-21] [$250] Migrate DisplayNamePage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16292]
### Filenames
- [ ] [src/pages/settings/Profile/DisplayNamePage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/DisplayNamePage.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by dangrous** [comment]
Cool! I can definitely get to this next week.

**Comment by LukaRusadze** [comment]
I can work on this if it's still free

**Comment by dangrous** [comment]
Pretty sure I can knock this out quick and keep it internal, will aim for today or tomorrow.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue when it goes to external

**Comment by dangrous** [comment]
Not a bug - just grabbing you @bfitzexpensify to help out with payment for @s77rt who reviewed the internal PR - thanks!

**Comment by bfitzexpensify** [comment]
`Bug` label works well!

Sent an offer to @s77rt

**Comment by s77rt** [comment]
@bfitzexpensify Accepted!

**Comment by bfitzexpensify** [comment]
All paid out, thanks for the help @s77rt. Closing this out.

**Comment by s77rt** [comment]
@bfitzexpensify This is due only $250 (functional component migration). I have refunded $750.

**Comment by bfitzexpensify** [comment]
Ah, I missed that - thank you @s77rt!
