### ISSUE TITLE
[HOLD for payment 2023-06-15] [$250] Migrate AddressPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16293]
### Filenames
- [ ] [src/pages/settings/Profile/PersonalDetails/AddressPage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/AddressPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196d43197753c4c34</li>
        <li>Upwork Job ID: 1665802136107708416</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by LukaRusadze** [comment]
I'll gladly work on this

**Comment by multijump** [comment]
I would like to take this issue.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by aldo-expensify** [comment]
Swapping C+ assignment because @0xmiroslav is already reviewing

**Comment by aldo-expensify** [comment]
@jliexpensify   , this is a code refactor issue, and you only have to handle the payment to the C+ (@0xmiroslav ) for reviewing the PR https://github.com/Expensify/App/pull/20089

**Comment by aldo-expensify** [comment]
Ping @0xmiroslav

**Comment by aldo-expensify** [comment]
oh, Ping @jliexpensify then :P

**Comment by jliexpensify** [comment]
Sorry sorry, had it on my to-do list but the fire yesterday took up my afternoon. Paying now!

**Comment by jliexpensify** [comment]
@0xmiroslav have hired you, once accepted I'll pay the $250, cheers!

**Comment by jliexpensify** [comment]
Paid and closed job!
