### ISSUE TITLE
[HOLD for payment 2023-06-29] [HOLD] [$250] Migrate WorkspaceMembersPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16306]
### Filenames
- [ ] [src/pages/workspace/WorkspaceMembersPage.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceMembersPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I can work on this issue when it goes to external

**Comment by abdulrahuman5196** [comment]
@Li357  Kindly assign me and BZ for C+ review processing.

**Comment by abdulrahuman5196** [comment]
@Li357 Gentle ping on this https://github.com/Expensify/App/issues/16306#issuecomment-1596101034

**Comment by abdulrahuman5196** [comment]
@Li357 Could you kindly assign the label to assign a BZ on this issue to process payment?

**Comment by abdulrahuman5196** [comment]
No BZ Checklist. We are only doing migration to function component

**Comment by kevinksullivan** [comment]
@abdulrahuman5196 can you apply to this job and let me know wen you've done so?

https://www.upwork.com/jobs/~018a5ff86cf2e66e2c

**Comment by Li357** [comment]
Not overdue, waiting for Upwork application

**Comment by abdulrahuman5196** [comment]
@kevinksullivan thank you. Submitted a proposal on the job.

**Comment by kevinksullivan** [comment]
Thanks @abdulrahuman5196 . One final step on your part is accepting the offer. Let me know when you've done so an I'll wrap this up.

**Comment by abdulrahuman5196** [comment]
@kevinksullivan  accepted the offer

**Comment by kevinksullivan** [comment]
Payment sent and contract ended
