### ISSUE TITLE
[HOLD for payment 2023-07-14] [$250] Migrate WorkspaceNewRoomPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16307]
### Filenames
- [ ] [src/pages/workspace/WorkspaceNewRoomPage.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cabea4a0506dc2c</li>
        <li>Upwork Job ID: 1673400034157887488</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I can work on this issue when it goes to external

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by Vishrut19** [comment]
Dibs?

**Comment by alexxxwork** [comment]
I would love to work on this

**Comment by BhuvaneshPatil** [comment]
Open to work on this

**Comment by olexyt** [comment]
I would like to work on this.

**Comment by wahaha999** [comment]
Can I do this?

**Comment by asadath1395** [comment]
I would love to work on this. Can i get this assigned?

**Comment by supertech0125** [comment]
I can do this task within 12 hrs.

**Comment by dayana7204** [comment]
I am ready to work on this ticket :)

**Comment by sonialiap** [comment]
@fedirjh can we choose someone for the job?

**Comment by vdem0115** [comment]
Hello
I would like to work on this issue.

**Comment by code0406** [comment]
I am eager to take on this task.

**Comment by alexxxwork** [comment]
The [PR](https://github.com/Expensify/App/pull/22015) is ready

**Comment by sonialiap** [comment]
@alexxxwork paid (+bonus) ✔️ 
@fedirjh offer sent (+bonus) ⌛
