### ISSUE TITLE
[$250] Migrate WorkspaceReimburseView.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16312]
### Filenames
- [ ] [src/pages/workspace/reimburse/WorkspaceReimburseView.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/reimburse/WorkspaceReimburseView.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cf503cd0131d957</li>
        <li>Upwork Job ID: 1673399792410345472</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I can work on this if goes to external

**Comment by muxriddinmuqimov77** [comment]
Contributor details
Your Expensify account email: muxriddinmuqimov007@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d01aef4263378596

**Comment by s-alves10** [comment]
I'd love to work on this.
I've a lot of experience in writing function components.

**Comment by KrAbhas** [comment]
I would like to work on this.

**Comment by olexyt** [comment]
I love to work on this.

**Comment by KrAbhas** [comment]
Contributor details
Your Expensify account email: abhaskumar.cs@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ee6dc8955a83a984

**Comment by kevinksullivan** [comment]
@marcaaron are we just looking for proposals here?

**Comment by mollfpr** [comment]
@kevinksullivan no proposal is required. I think we need to assign it to anyone who wants to work on this. Maybe @muxriddinmuqimov77 because they got it first?

**Comment by kevinksullivan** [comment]
Ok, then is @s-alves10 next up?

**Comment by mollfpr** [comment]
Following up from #16215 we @s-alves10 currently have 3 active issues, so pick on the next contributor.

@neonbhai Just got assigned to #16215 

@rayane-djouah still has 1 active on migrating to function component

@KrAbhas hasn't got assigned to any issue.

**Comment by s-alves10** [comment]
I have 2 active issues, one PR is created, and one is hold due to reviewer's OOO

**Comment by mollfpr** [comment]
I think it's better to spread this and let new contributors get their hands on it.

**Comment by olexyt** [comment]
Hello @mollfpr 
I can work on this issue.

**Comment by asadath1395** [comment]
I would love to work on this

**Comment by mollfpr** [comment]
@kevinksullivan just checking again that @KrAbhas hasn't got assigned to any issue. We can let them take this one.

🎀 👀 🎀 C+ reviewed!

**Comment by kevinksullivan** [comment]
Hi @KrAbhas can you apply for the job in upwork? Not sure if I am finding the right profile.

**Comment by KrAbhas** [comment]
Hi @kevinksullivan, I have applied at upwork, you can find the proposal here: https://www.upwork.com/ab/proposals/1674439356925800449?success

**Comment by mollfpr** [comment]
@MonilBhavsar @kevinksullivan let's assign this to @KrAbhas so they can start working on the PR  🚀

**Comment by code0406** [comment]
I am eager to take on this task.

**Comment by MonilBhavsar** [comment]
Do we need a proposal for refactor?

**Comment by vdem0115** [comment]
I would like to work on this issue.

**Comment by kevinksullivan** [comment]
Hired @KrAbhas

**Comment by mollfpr** [comment]
@kevinksullivan Let's assign this issue to @KrAbhas 

@KrAbhas Let me know when the PR is ready, thanks!

**Comment by MonilBhavsar** [comment]
@KrAbhas Any idea when the PR will be ready for review?

**Comment by KrAbhas** [comment]
Thanks @MonilBhavsar for the assignment, I will raise the PR within 24 hours.

**Comment by kevinksullivan** [comment]
PR is still WIP.

**Comment by kevinksullivan** [comment]
Paid out and ended contracts. Just FYI @KrAbhas it looks like we had two contracts for you, so I paid you on one contract and ended them both.
