### ISSUE TITLE
[Hold on #15992] Composer not focused when user leaves/returns an ongoing DM draft

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#16699]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to any chat
2. click on composer
3. click on users name to see the details
4. close the details page

## Expected Result: 
composer should focused (same as web, mWeb)

## Actual Result:  
composer not focused

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.91-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/228643092-728b6ce2-119b-4f2f-958d-0ecd676cb062.mp4

https://user-images.githubusercontent.com/43996225/228643119-13f950d1-3457-47f2-8921-20da7430f05f.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1680088305065359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
@bondydaa do you think we should close this GH or keep it on hold for https://github.com/Expensify/App/issues/15992?

**Comment by michaelhaxhiu** [comment]
Posted in slack here - https://expensify.slack.com/archives/C049HHMV9SM/p1680715074199869?thread_ts=1680301816.029279&cid=C049HHMV9SM

**Comment by bondydaa** [comment]
I think the SOP has been to put a HOLD on any issues created and link it on the tracking GH.

**Comment by michaelhaxhiu** [comment]
Excellent, let's do the same here. Thanks Bondy :)

**Comment by michaelhaxhiu** [comment]
holding, still ⏸️

**Comment by michaelhaxhiu** [comment]
Still held, commented on blocking GH to see if we have any indication of prioritization on this one.

**Comment by michaelhaxhiu** [comment]
No movement, still held

**Comment by michaelhaxhiu** [comment]
same

**Comment by michaelhaxhiu** [comment]
held and no movement on blocking GH

**Comment by michaelhaxhiu** [comment]
still held

**Comment by michaelhaxhiu** [comment]
Note: I'm preparing to go OOO for ~2 weeks, and doubt this will see movement while I'm gone. I'm going to keep it assigned for that reason and not add a buddy. If it gets movement (and I'm wrong), please remove & reapply the bug label.

**Comment by michaelhaxhiu** [comment]
Back from OOO. Still no movement.

**Comment by michaelhaxhiu** [comment]
Not a priority yet.

**Comment by michaelhaxhiu** [comment]
I'm re-assigning the `Bug` label to get a new BZ on this, as my sabbatical starts Friday. 

Next steps:
- Not much! This job is on hold for https://github.com/Expensify/App/issues/15992 so just keep an eye on it.
- I'm leaving this `Monthly` so it's low touch 👍 

Thanks in advance!

**Comment by muttmuure** [comment]
Not a priority yet

**Comment by muttmuure** [comment]
Still on hold

**Comment by mountiny** [comment]
Discussing with @muttmuure I think we can close this one in light of focus on waves and roadmap issues. It is also correctly linked in the tracking issue if we need to come back to this in future. Feel free to reopen if you disagree
