### ISSUE TITLE
[Fabric] - IOS - Sign in - No skeleton appears when log in with account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app using the link https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/13767/index.html
2. Put your credentials

## Expected Result:
Skeleton appears when log in with account

## Actual Result:
No skeleton appears when log in with account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229141258-ebab00d4-f212-417a-be65-be0e776a36b2.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by WoLewicki** [comment]
Hi! I'll be working on this issue.

**Comment by kbecciv** [comment]
@WoLewicki Sending you correct behavior when user signs in, skeleton should be appear while chat is loading.

![Screenshot_20230427_195712_New Expensify](https://user-images.githubusercontent.com/93399543/235014764-5bea82f5-3ea0-4197-aec7-8938e78154c9.jpg)

https://user-images.githubusercontent.com/93399543/235014765-338134ae-dd4e-4f23-99ef-47700f849087.mp4

**Comment by j-piasecki** [comment]
Aside from the 1-frame flicker, it works as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/3af64eb5-4f87-4738-bdd4-cca37912a76f
