### ISSUE TITLE
[Fabric] - IOS - Chat - Unable to download a .docx file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16809]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Navigate to a conversation
4. Click the grey plus button in compose box
5. Click on add attachment
6. Click on choose document
7. Select a .docx file

## Expected Result:
 Able to download a .docx file

## Actual Result:
 Unable to download a .docx file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229155219-53e9b718-d357-45b2-8d08-f1570cae909c.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by j-piasecki** [comment]
Bot downloading and uploading a `.docx` file work as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/13e2c4e4-5ea6-412f-b2a8-bebb64fb9f5f


https://github.com/Expensify/App/assets/21055725/f67e9fc4-044e-439c-ad45-2dbbf668e36b
