### ISSUE TITLE
[Fabric] IOS - Settings- Can not select language and priority mode under Preference page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app using the link https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/13767/index.html
2. Log in with any account
3. Go Settings - Preferences
4. Change the language and priority mode

## Expected Result:
Able to select language and priority mode under Preference page

## Actual Result:
 Can not select language and priority mode under Preference page
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229153330-9da3b577-40eb-49b1-abad-78d5a2cbe407.MP4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by WoLewicki** [comment]
Hi! I'll be working on this issue.

**Comment by j-piasecki** [comment]
It seems to be working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/22ab6296-ee6a-4d2c-b63b-db8429ab9a3c
