### ISSUE TITLE
[Fabric] IOS - Unable to create a Workspace- button is not functional

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app using the link https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/13767/index.html
2. Log in with any account
3. Go Settings - Workspace
4. Tap Create Workspace button

## Expected Result:
Able to create a Workspace- button is functional

## Actual Result:
Unable to create a Workspace- button is not functional

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229143948-6d2974ac-b161-4498-a7e2-e6112e4d68c1.MP4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by WoLewicki** [comment]
Hi! I'll be working on this issue.
