### ISSUE TITLE
[Fabric] - IOS - Sign in - Unable to log in to sms account via the sms link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enter phone number for sign in
2. Got link in sms message to sign in
3. Click on link

## Expected Result:
Able to add a password and sign in to an SMS account.

## Actual Result:
Unable to add a password and sign in to an SMS account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229158361-638850d8-e44a-4d50-9dc0-4daf82a804c8.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by WoLewicki** [comment]
Hi! I'll be working on this issue.
