### ISSUE TITLE
[Fabric] -  iOS - Chat - Emoji are cut off at the top when used in text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#16824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Open any chat
3. Send a message with text and emoji

## Expected Result:
Emoji are displayed correctly when used in text

## Actual Result:
Emoji are cut off at the top when used in text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
- [x] IPAD / native

**Version Number:** 1.2.88.0

**Reproducible in staging?:** NO

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/229192376-6d75db57-5e52-45de-9cca-ac440cc40b58.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
Hi! I'll be working on this issue.

**Comment by WoLewicki** [comment]
Hi! I'll be working on this issue.

**Comment by j-piasecki** [comment]
It is working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

<img width="549" alt="ios-emoji-in-text" src="https://github.com/Expensify/App/assets/21055725/9296aa2c-efdd-4a30-9087-34ee11de0f5e">
