### ISSUE TITLE
[HOLD for payment 2023-05-25] CompleteTask Front-End

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#16858]
https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#bookmark=id.ln5eunmvrizo

**Comment by thienlnam** [comment]
Going to be working with IR on this

**Comment by thienlnam** [comment]
On hold

**Comment by thienlnam** [comment]
Same as above, assigning these out this week

**Comment by thienlnam** [comment]
Auth command has been merged, this is ready to be worked on.

**Comment by cdanwards** [comment]
Starting work on this issue.

**Comment by deetergp** [comment]
I'm going to dig into this first thing tomorrow.

**Comment by thienlnam** [comment]
Chatted with Scott, going to take this over !

**Comment by thienlnam** [comment]
@kevinksullivan This issue is all ready for payment 

C+ review internal PR review for - @fedirjh

**Comment by kevinksullivan** [comment]
@fedirjh offer sent, let me know when you accept

**Comment by kevinksullivan** [comment]
All set
