### ISSUE TITLE
[HOLD] Enable react/destructuring-assignment eslint rule

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#16979]
We are starting to allow props destructuring as part of the Hooks migration project. We will want to enable the eslint rule to "always" so that this is required. However, we don't want to do this until the migration is done because it will cause errors on tons of existing components. This issue is a reminder to do it once the migration is done. 

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md

cc @marcaaron @roryabraham

**Comment by marcaaron** [comment]
I'm good with it, but tagging @tgolen and @iwiznia for visibility. IIRC they have both had some opinions about destructuring in the past so we can give them some chance to chime in.

**Comment by iwiznia** [comment]
IIRC my opinion was that sometimes destructuring makes code less readable.
Can someone give some context on why we want to do this now for hooks or why hooks are different from non hooks that it made us want to enable this now?

**Comment by puneetlath** [comment]
Oh cool, sounds good. Weigh in on this thread @iwiznia @tgolen if you have opinions: https://expensify.slack.com/archives/C01GTK53T8Q/p1680718704040129

**Comment by puneetlath** [comment]
Nevermind!
