### ISSUE TITLE
[HOLD for payment 2023-06-19] [$250] [Group 5][Accessible Pressable] Migrate OffineWithFeedback

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#17048]
HOLD on https://github.com/Expensify/App/issues/16988

### Description

Migrate [OffineWithFeedback](https://github.com/Expensify/App/blob/main/src/components/OfflineWithFeedback.js) to use PressableWithFeedback
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3458373439ee581</li>
        <li>Upwork Job ID: 1666247621907214336</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by Skalakid** [comment]
Can you assign me to this one, please?

**Comment by Waffenffs** [comment]
I want to work on this.

**Comment by Waffenffs** [comment]
Contributor details
Your Expensify account email: waffen.sultanofc@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012d61f168fe09c889

**Comment by mollfpr** [comment]
@Waffenffs This issue is already worked on. You can check another issues with the label `Help Wanted` for the open job.

**Comment by maddylewis** [comment]
reviewing - will issue payment(s) today 👍

**Comment by mollfpr** [comment]
@maddylewis Is this doesn't need the BZ checklist?

**Comment by maddylewis** [comment]
@mollfpr - im not sure why the second BZ checklist didn't populate. i think we should still go through those steps. I'll add it manually.

**Comment by maddylewis** [comment]
@mollfpr - this may not require the standard BZ checklist. also, can you confirm the following payments are correct:
- $250 to @mollfpr 
- $250 to @Skalakid

**Comment by maddylewis** [comment]
this is paid!
