### ISSUE TITLE
[HOLD for payment 2023-06-28] [$250] [Group 6][Accessible Pressable] Migrate ImageView

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#17060]
HOLD on https://github.com/Expensify/App/issues/16988

### Description

Migrate [ImageView](https://github.com/Expensify/App/blob/main/src/components/ImageView/index.js) to use PressableWithoutFeedback
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105ddb835f3fad327</li>
        <li>Upwork Job ID: 1666252080091656192</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by Skalakid** [comment]
Can you assign me to this one, please?

**Comment by roryabraham** [comment]
@tjferriss The only payment due here is $250 to @eVoloshchak for the review. @Skalakid works for SWM

**Comment by tjferriss** [comment]
Thanks for the clarification. @eVoloshchak I just sent you a request for the job in Upworks: https://www.upwork.com/jobs/~0105ddb835f3fad327.

**Comment by techievivek** [comment]
@tjferriss Are we good to close this issue? Is @eVoloshchak paid for reviewing the PR here?

**Comment by techievivek** [comment]
Not overdue, waiting for payment to be done.

**Comment by techievivek** [comment]
Not overdue, going to ping in the bugzero channel to see if can finish the payment here.

**Comment by laurenreidexpensify** [comment]
Payment issued in Upwork - closing
