### ISSUE TITLE
[HOLD for payment 2023-05-25] ReopenTask Front-End

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#17469]
https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#bookmark=id.defzvb9j9kqq
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015929b73027eab42d</li>
        <li>Upwork Job ID: 1662130072732762112</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Held on CreateTask https://github.com/Expensify/App/issues/16855 and also the corresponding Auth command

**Comment by thienlnam** [comment]
This is still holding on the ReopenTask auth command https://github.com/Expensify/Expensify/issues/274091, but the front-end can be worked on in conjunction with the auth PR going out

To trigger a task report view, just force [isTaskReport](https://github.com/Expensify/App/blob/4e0b41839a89e1c3fcc97e84964eec0fb5a0cb97/src/libs/ReportUtils.js#L128-L136) to return true and click on any chat report

**Comment by MariaHCD** [comment]
Working on [Auth PR](https://github.com/Expensify/Auth/pull/7827) so this can be unblocked

**Comment by thienlnam** [comment]
Pushing this forward while Maria is offline

**Comment by MariaHCD** [comment]
I think we're done here?

**Comment by thienlnam** [comment]
Ah we'll actually need to get @fedirjh payment for internal C+ review

**Comment by thienlnam** [comment]
@tjferriss This is ready for payment!

Internal Review (C+) to @fedirjh

**Comment by tjferriss** [comment]
@fedirjh the contract has been extended to you. Once accepted, I'll process payment.

**Comment by tjferriss** [comment]
@fedirjh payment has been sent.
