### ISSUE TITLE
Only send email reminders for customers that don't have any weekly activity

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#17513]
Problem
While the majority of Expensify members haven't implemented Expensify Chat yet, for those the have, the email reminders feel like overkill. For instance, if you're generally active in a given week, then you don't need to also get the same message via email that you also already viewed in-app. At the moment, however, everyone gets an email for any message they haven't seen in 10 minutes, even if they saw that same message in 15 minutes or 30, perhaps even a day or two later. All in all, reminders are only effective and true reminders when you're already not using Expensify Chat at some regular frequency.

Solution
Let's only send email reminders to users that are truly not using Expensify Chat. While that bar may one day be daily, weekly feels like a pretty reasonable place to start for now. Accordingly, let's disable reminders for any users that are minimally logging into Expensify Chat and using it on a weekly basis. If not, at worst they'll receive 52 emails a year, with the big benefit that these help pull those users back into the app and notify them of activity.

**Comment by JmillsExpensify** [comment]
Happy to take this one over as BZ to help clean up my inbox. 😄

**Comment by JmillsExpensify** [comment]
> Will this be a user setting? It seems like that's what we decided in the thread, but not 100% sure

Yes, that's my understanding as well. 

> Will we be:
a. Sending a weekly email on a certain day (e.g. saturday) for each chat that is currently unread at the time of the email OR
b. Sending a daily email for each chat that has been unread for at least a week at the time of the email

Can we utilize the existing userActivityEvaluator for this? Probably not given that it's based on undone inbox tasks right? I do think that's the ideal way to make sure we don't have a bunch of competing systems. Though in any case, to answer your question, I would think it's just like userActivityEvaluator and sends the weekly reminder on a certain day whenever that job runs.

**Comment by JmillsExpensify** [comment]
Based on the above, this needs to be pre-designed and we need to agree on the next steps. @roryabraham this was your post/thread so I wanted if you're passionate to take this? If not, I'm going to raise this in open source and get a volunteer. I don't have bandwidth to push this forward.

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by roryabraham** [comment]
I do think this is pretty valuable. We are power-users so it's more extreme for us, but getting an email for any chat you missed feels very overwhelming. People are easily annoyed by too many emails, and for many skeptical new users it might push them towards ditching New Expensify.

IMO the only reason we don't feel this problem on a daily basis is because we all have email filters that filter these out for us. But we probably don't want to expect that of our users.

**Comment by JmillsExpensify** [comment]
I'm OOO the rest of this week. If you'd like to take it forward and get everyone on the same page on the approach, go for it!

**Comment by JmillsExpensify** [comment]
Back from OOO. Going to find someone to take this, I have too much on my plate.

**Comment by JmillsExpensify** [comment]
Not a priority.

**Comment by JmillsExpensify** [comment]
Last we talked about this in Slack we disagreed on doing this, within the last week, so I'm just going to close for now.

**Comment by roryabraham** [comment]
@JmillsExpensify FWIW Callstack provided some feedback that they receive a huge amount of email notifications from using NewDot, so much so that it feels like "spam"
