### ISSUE TITLE
April 2023 Performance Audit

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#17657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is a tracking issue for another from-scratch performance audit to identify performance bottlenecks in our app.

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment]
Hey, we are still working on this, and will provide results by next week, stay tuned! 😊
