### ISSUE TITLE
Workspace - Profile image not shown some time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#17660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed
1. Click on any workspace/group chat
2. send a message to the any group.

## Notes:
- You can see in the screenshot that "Montu Chirag" posted a message at 4:29 PM.
- Although no one has messaged him since then, at 4:35 PM "Montu Chirag" messages back and his profile picture appears in front of him.
- While between 4:29 to 4:35, his profile photo is not visible in any of the messages.
- My profile should only appear once unless another user sends a message.

## Expected Result:
When a user sends more than one message in a group, his profile picture should appear only once time

## Actual Result:
When a user sends more than one message to a group, their profile picture appears more than once.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.1.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/233123351-b28e510a-31a1-4333-ba75-492475d2c7c7.MP4

https://user-images.githubusercontent.com/93399543/233123708-ba551183-9bab-43c7-b5f3-411b5a450540.MP4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @corange-lab

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1681818443997329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I'm not quite sure I understand the issue asking in Slack chat - I don't think this is a bug, maybe a bigger question of how we want to timestamp user messages

**Comment by Christinadobrzyn** [comment]
I don't think this is a bug, I think this might be intentional so I'll bring it up in Open-source and see if we want to change it.

**Comment by Christinadobrzyn** [comment]
Asking the group for some additional thoughts here - https://expensify.slack.com/archives/C049HHMV9SM/p1682098297597449?thread_ts=1681818443.997329&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment]
Per the ^ slack convo, this is expected. The Profile icon will show after ever 5 mins or so. Closing
