### ISSUE TITLE
Investigate testing iOS push notifications w/o Expensify developer account

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#17808]
### Problem

We currently do not know of a way for external contributors to test push notifications. If it's possible, it's not something we've written down anywhere.

This prevents external contributors from helping out with a whole class of features and bugs in NewDot.

### Solution
Try to get the app building on a physical iPhone and hooked up with UrbanAirship push notifications without using an Expensify Apple developer account. If successful, #writeitdown.

**Comment by AndrewGable** [comment]
Haven't had time for this one yet.

**Comment by AndrewGable** [comment]
I just confirmed with Airship that this actually is not possible.

**Comment by AndrewGable** [comment]
I think we are going to have to circle back to the drawing board on how to support this and for now we can just keep push notifications internal only.
