### ISSUE TITLE
 10am posts are not going through on the first try anymore. Since April 18 and it happens daily.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#17897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Send a 10 am post to Chronos

## Expected Result:
Thanks for the update message appears

## Actual Result:
Chronos says: "Sorry, I don't know how to respond to that."
Then when I copy and paste the same info, after it tells me 10am went out, it then goes through. 
Except for today (shown on 3rd screenshot), it did not go through in my 2nd attempt.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [] MacOS / Chrome / Safari
- [x ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (2)](https://user-images.githubusercontent.com/43996225/234054391-c128bc45-98cb-4cd5-be95-e2bd3568b04c.png)
![image (1)](https://user-images.githubusercontent.com/43996225/234054397-e9f947c3-f298-40a9-9dc0-3052dc936592.png)
![image](https://user-images.githubusercontent.com/43996225/234054400-04df3350-29f2-4f76-a6ef-04a4f330cc1b.png)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rosegrech 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1682331797984339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I am unable to reproduce this. Are you doing anything else when posting your 10ams e.g. copying / pasting? Just looking to identify reliable reproduction steps. Also, what version are you on @rosegrech?

**Comment by rosegrech** [comment]
Thanks @MitchExpensify it's the desktop app - Version 1.3.5-0 (1.3.5-0)
I did copy and paste from previous and so it does not work on the first go but usually on the 2nd attempt even when copying/pasting again. Yesterday was on the 3rd attempt.

Today, I did a test and just typed in my 10am and it 24 mins later I have no response :( 
<img width="623" alt="image" src="https://user-images.githubusercontent.com/32204375/234191541-a83c1aef-fdee-4eef-ab64-fe32456e0ad8.png">

**Comment by rosegrech** [comment]
There were no updates so I quite New Expensify and when I opened it up again there it is, so weird....
<img width="777" alt="image" src="https://user-images.githubusercontent.com/32204375/234191929-b86e7448-3bac-4025-86a0-39e0b5dd0aae.png">

**Comment by rosegrech** [comment]
Tomorrow I will try the copy/paste and see if that works on the first try.

**Comment by MitchExpensify** [comment]
Ok cool, my hunch is that there's a hidden character or something. I type the "10am" and line break manually and it always works. I thiiink I ran into an issue with copy and paste before but can't be sure

**Comment by rosegrech** [comment]
Interesting, so hard to see/notice that. I copied and pasted from yesterday's 10am (since that went through fine) and it went through today on the first attempt. 

I also noticed another [GH](https://github.com/Expensify/Expensify/issues/266743) open on this issue.

**Comment by MitchExpensify** [comment]
Yes it is odd for sure, lets consolidate investigation in that issue as it was created first 👁️  

Good catch!
