### ISSUE TITLE
[HOLD for payment 2023-05-22] [$250] Migrate MagicCodeInput.js to function component

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#18332]
Coming from [here](https://github.com/Expensify/App/pull/16076#issuecomment-1527790439)

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by sumitshinde-84** [comment]
i would like to work on this issue can you please assign it to me .

**Comment by BeeMargarida** [comment]
Update: currently being tested internally by QA

**Comment by BeeMargarida** [comment]
Update: ready for review!

**Comment by cristipaval** [comment]
The above is not applicable to this one. The issue can be closed.
