### ISSUE TITLE
Adding 5 or more users to a new group will show empty chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Click on FAB (+ icon) > Choose "New Group"
3. Add at least 5 members > Create the group
4. You'll notice that an empty chat will be shown without any intro text or description

## Expected Result: 
Intro text/description should be shown
## Actual Result : 
No intro chat is present

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10-4
**Reproducible in staging?:** y ( I can repro only in online)
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236343611-9bee2765-5d4c-44cf-82b3-29cbedef9764.mp4

https://user-images.githubusercontent.com/43996225/236343633-601a62cb-f282-4c22-9a60-d96cdc0c5392.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683219801745669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment]
Tried this on a couple of different Android platforms on Browserstack and it's not reproducible, going to close!

<img width="279" alt="image" src="https://github.com/Expensify/App/assets/28715117/be18f291-3de1-4828-b2ce-2c898674b902">
