### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] 2FA input should have individual entry like sign in screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enter 2FA enabled email in login field
2. Observe the 2FA input field

## Expected Result:
Should have 6 individual field to enter
## Actual Result:
Still showing old format
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.10-4
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="5" src="https://user-images.githubusercontent.com/43996225/236344718-1d3fd3ce-2346-4bfd-92fe-5c829b135242.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683226226189909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfe61519061e6012</li>
        <li>Upwork Job ID: 1655982074781265920</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
I would argue this is a new feature.

**Comment by joelbettner** [comment]
I'm not able to assign people, but I believe @twisterdotcom can.

**Comment by bondydaa** [comment]
was linked here from another issue that I closed as a dupe. just want to confirm that we should be using the component that was refactored here https://github.com/Expensify/App/issues/18332.

**Comment by twisterdotcom** [comment]
Offers of $1k sent.

**Comment by twisterdotcom** [comment]
Payments done!

**Comment by twisterdotcom** [comment]
>Business Days Elapsed between assignment and PR merge: 3

Public holidays got me I guess. Offers sent to you both for the extra $500.
