### ISSUE TITLE
Text composer dissapears and shows up while in editing mode after changing tabs

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Edit a comment
3. Notice the text composer becomes hidden
4. Open another chat or another app and return back to chat (or) click outside

## Expected Result:
Text composer should stay hidden or it should not disappear in the first place.
## Actual Result:
Text composer reappears while in editing mode (or disappears while in editing mode).

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236340518-329c3cc9-1b52-44ab-8272-0bca167e85ad.mp4

https://user-images.githubusercontent.com/43996225/236340581-2c23e6b7-c89c-43b7-8278-9fc0aa8f1887.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683219440561249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I've run out of time this week; I will test over the weekend to continue the process.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
I will test soon.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate. The keyboard remains open for me when moving around between apps or clicking around in Chat.
