### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-22] [Manual Requests] Update ReportScreen to display MoneyRequest Reports

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18474]
Implement [this internal section](https://docs.google.com/document/d/17jFcMsAotXvsMhXivoF3u7fyzeyXkKpRGXR88Ud0oWY/edit#bookmark=kix.nfq9xn66jx27).

1 Reuse the [ReportScreen](https://github.com/Expensify/App/blob/f18e6e9ba9f5cc2a437d4e67888e8464233576f2/src/pages/home/ReportScreen.js) component for this
2. Conditionally render `MoneyRequestHeader` [here](https://github.com/Expensify/App/blob/f18e6e9ba9f5cc2a437d4e67888e8464233576f2/src/pages/home/ReportScreen.js#L276-L282) if `ReportUtils.isMoneyRequestReport ` true, otherwise render `HeaderView`
3. The Expense/IOU reportActions should already be automatically passed to `ReportActionsView`
4. We’ll update ReportActionItemCreated to [return early](https://github.com/Expensify/App/blob/f18e6e9ba9f5cc2a437d4e67888e8464233576f2/src/pages/home/report/ReportActionItemCreated.js#L46) if ReportUtils.isMoneyRequestReport(reportID) is true  so we don’t display the created header
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013db16ecb8981a4db</li>
        <li>Upwork Job ID: 1661761420215586816</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Slack thread for discussion is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1683293899617469)

**Comment by trjExpensify** [comment]
Moving this back to `daily`, as it's a deliverable for EC3 next week. We need to stick to making daily progress if we're going to get the PR merged early this week. @mollfpr can you give us an ETA on the draft PR going into full review? Thanks!

**Comment by mollfpr** [comment]
@trjExpensify It should be ready within an hour, I'm completing the checklist and the screenshot test now.

**Comment by trjExpensify** [comment]
Yeah, thanks for the urgency on this one @mollfpr. Much appreciated!

**Comment by trjExpensify** [comment]
Create the job, Melvin. 😅

**Comment by trjExpensify** [comment]
Okay... so @mollfpr, I've sent you an offer for $1,500 on this job. No C+ payment due, reviewed internally for EC3.

**Comment by trjExpensify** [comment]
Settled up!
