### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-23] [Manual Requests] Display IOU and expense reports in the LHN

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18475]
Implement [this internal section](https://docs.google.com/document/d/17jFcMsAotXvsMhXivoF3u7fyzeyXkKpRGXR88Ud0oWY/edit#bookmark=id.t4azxrk279xb) of the Manual Requests Design Doc. More details to follow.

1. Update [getOrderedReportIDs](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/SidebarUtils.js#L109) passing iouReports to the list of reports.

`const reportsToDisplay = _.filter({...chatReports, …iouReports}, …);`

2. Update [shouldReportBeInOptionList](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/ReportUtils.js#L1470) to stop filtering iou reports and stop checking for the participants as those are missing in expense and iou reports. We will use the [isMoneyRequestReport](https://github.com/Expensify/App/blob/17c1dd8561f217ed3117937a901425d298196873/src/libs/ReportUtils.js#L122-L129) helper method.

```
if (!report || !report.reportID || !report.participants || (_.isEmpty(report.participants) && !isPublicRoom(report) && !isArchivedRoom(report) && !isMoneyRequestReport(report)) || isIOUReport(report))
```

3. Update [getOptionData](https://github.com/Expensify/App/blob/67c76f6dfb44cab18bd597cadd675195ad776e15/src/libs/SidebarUtils.js#L192) to include data for iouReports (subscript avatar, etc)
- Add iouReports [here](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/SidebarUtils.js#L194) (these are both iou and expense)

```
const report = chatReports[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`]
    || iouReports[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`];

```

- Add result.isMoneyRequestReport [here](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/SidebarUtils.js#L230) and [here](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/SidebarUtils.js#L237)
- Update [shouldShowSubscript](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/SidebarUtils.js#L238) to true for iou reports
- Update [getReportName](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/ReportUtils.js#L840) to display the correct `workspaceName owes $X` message as the reportName
- Update [getIcons](https://github.com/Expensify/App/blob/67c76f6dfb44cab18bd597cadd675195ad776e15/src/libs/ReportUtils.js#L669) to return the avatars for the user and Workspace

```
if (isPolicyExpenseChat(report) || isMoneyRequestReport(report)) {
```

4 In [ReportScreen](https://github.com/Expensify/App/blob/30420a19d14bbc021189d9bbfe7b702fcd1c2323/src/pages/home/ReportScreen.js#L276-L282), we’ll check if the report being rendered is an IOU report and conditionally render MoneyRequestHeader or HeaderView if not.
5. We’ll then render the list of money requests and comments on the Expense / IOU report right under the new header component, using the existing ReportActionsView component.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bc7eb53184f8e07</li>
        <li>Upwork Job ID: 1661760310912589824</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by mollfpr** [comment]
>4 In [ReportScreen](https://github.com/Expensify/App/blob/30420a19d14bbc021189d9bbfe7b702fcd1c2323/src/pages/home/ReportScreen.js#L276-L282), we’ll check if the report being rendered is an IOU report and conditionally render MoneyRequestHeader or HeaderView if not.

We can skip this step since already done with https://github.com/Expensify/App/issues/18474

**Comment by mollfpr** [comment]
>Update [getReportName](https://github.com/Expensify/App/blob/4947508bedc2e901082d805c84498f5f394ef655/src/libs/ReportUtils.js#L840) to display the correct workspaceName owes $X message as the reportName

@mountiny I'm confused about this; how does a user or workspace owe or to whom they owe?

**Comment by mollfpr** [comment]
>Update [getIcons](https://github.com/Expensify/App/blob/67c76f6dfb44cab18bd597cadd675195ad776e15/src/libs/ReportUtils.js#L669) to return the avatars for the user and Workspace

We don't need the change here. We will return the user avatar for the IOU report.

https://github.com/Expensify/App/blob/983da48182e158ee5a3df67c04f7d21c8367a2d3/src/libs/ReportUtils.js#L767-L773

But in the `MoneyRequestHeader`, we use the `managerEmail` to get the avatar instead of `ownerEmail`. So I'm not sure which one should be followed.

**Comment by mountiny** [comment]
> I'm confused about this; how does a user or workspace owe or to whom they owe?

So basically you are employee at some company and you go for a conference and you want your boss to pay you back for lunch you bought with your money. you request money from the workspace chat. On the other side is your boss or all other bosses.

So it will be the Workspace rather than just one person owning you this money.

On left on this screenshot is employee view and on the right its the admins view. You can see they have the green dot in the LHN because they have something to do there, pay the request.

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/36083550/236581086-28e14071-8f72-4903-b085-0e7ac6f52fff.png">

> We will return the user avatar for the IOU report.

We have two types of reports which involve money. IOU is between normal people, P2P. Expense report is between an employee and their company/ boss/ employer. We want the subscript only in case of the Expense report (or workspace chat)

**Comment by mountiny** [comment]
Slack thread for discussion [is here](https://expensify.slack.com/archives/C01GTK53T8Q/p1683293923439509)

**Comment by trjExpensify** [comment]
Moving this back to daily, as it's a deliverable for EC3 next week. We need to stick to making daily progress if we're going to get the PR merged early this week. @mollfpr can you give us an ETA on the draft PR going into full review? Thanks!

(sorry yes, It's me, the parrot from the other issue as well! 🦜 😄)

**Comment by luacmartins** [comment]
PR is merged

**Comment by trjExpensify** [comment]
Settled up!
