### ISSUE TITLE
mWeb - Chat - Black screen after deleting first message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Navigate to a conversation (conversation is not very long) in the main testing device
3. Scroll up a bit and choose the first of several messages you already sent back-to-back
4. Verify the chat header with your name appears only appears on your first message
5. Hover over that first message (Web/Desktop) / Tap and hold (Mobile) to view the action menu
6. Click/Tap on the Trash icon to delete the message
7. Verify the message is deleted from the conversation history

## Expected Result:
The user deleted the required message without problems.

## Actual Result:
Users should be able to delete owned messages, but after deleting first message, the conversation scrolls to the beginning and user sees black screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236475494-0e18858d-a9bd-40f7-88d5-bd66e1144be4.mp4

https://user-images.githubusercontent.com/93399543/236475507-209e2275-8bfe-4a6c-aed6-670a0dab19cc.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is not reproductible in Production, attached the video.


https://user-images.githubusercontent.com/93399543/236476667-61a334c8-8a2a-4a86-9e79-2f722de8bd41.mp4

**Comment by roryabraham** [comment]
@kbecciv since I've yet to reproduce this, logs could be very helpful in helping us diagnose this. If you're still able to reproduce it, can you try to capture console logs? Here are [some instructions](https://www.addictivetips.com/android/get-web-console-log-chrome-for-android/) on capturing console logs from a physical device on Android mWeb.

**Comment by roryabraham** [comment]
I'm not able to reproduce this.

**Comment by roryabraham** [comment]
Asked for a retest in slack: https://expensify.slack.com/archives/C9YU7BX5M/p1683307443300569

**Comment by marcaaron** [comment]
Is it exclusive to Android Chrome? What account did we use to reproduce this? @kbecciv

**Comment by marcaaron** [comment]
Tried and also can’t reproduce this once. Just tried on Android web (emulator)

**Comment by isagoico** [comment]
@kavimuru is unable to reproduce the issue anymore. Video below

https://user-images.githubusercontent.com/44479856/236541005-51026525-786b-4455-b7be-32b0c04f4ff9.mp4

**Comment by marcaaron** [comment]
Great! Removed the deploy blocker. 

Slack thread for posterity: https://expensify.slack.com/archives/C9YU7BX5M/p1683311371033179?thread_ts=1683307443.300569&cid=C9YU7BX5M
