### ISSUE TITLE
Personal Details - NYC address is not saved in Personal Details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Expensify Desktop app
2. Sign into a valid account
3. Click on Profile > Personal Details > Home Address
4. Type "NYC" in the Address 1 field and select the first option "NYC Street, Astoria, NY, USA"

## Expected Result:
The user expects to see "NYC Street, Astoria, NY, USA" in the Address field

## Actual Result:
The result changes to 32nd Avenue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236488567-616bf821-f2e3-4129-8a30-b87ac7a933e1.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Hm, I don't think this is a case we need to solve for, as no one would purposely be typing in "NYC Street" -- that street doesn't exist  nor would NYC ever be input into the address field. In the context of an address, it is always written as `New York` or `NY`, seeing as NYC street does not exist  I am going to close this.
