### ISSUE TITLE
 on connect bank account, first page has first field auto focused, while the second page doesn't

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Workspace > connect bank > manually
2. see the first page, fill it and then see second page

## Expected results: 
All pages should have first field auto-focused so that clicking of checkbox can trigger the error messages
## Actual results: 
second page doesn't have desired behaviour causing no triggering of errors on clicking checkbox

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.10.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236542739-a1088796-efe5-430e-972a-556b5090c95c.mp4

https://user-images.githubusercontent.com/43996225/236542741-27984f8a-1291-48c1-84a9-3fd492cdac1d.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683042291079519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Hey @kavimuru can you please fill out the `Platforms` section with all of the affected platforms so that I can test this? Thank you!

**Comment by stephanieelliott** [comment]
I tested this on MacOS / Desktop and can see that the second field does not auto-focus (not sure about which other platforms are affected). However, I disagree that `All pages should have first field auto-focused so that clicking of checkbox can trigger the error messages` is the desired behavior. Clicking `Save & Continue` should be what triggers the errors, it should be possible to complete the items on the page in any order you like without triggering an error. Gonna close this, may reopen if it becomes a priority in the future.
