### ISSUE TITLE
[HOLD for payment 2023-06-08] [HOLD] [Moderation] Create FlagCommentPage

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#18508]
Part of NewDot Moderation - [Tracking Issue](https://github.com/Expensify/Expensify/issues/264987) and [Design Doc](https://docs.google.com/document/d/10n9gcRl_b4MnBQcttlq8KU_xQEEW77gChigIrGgRQEM/edit#heading=h.mnjguil21u0a)

[Design Doc Section](https://docs.google.com/document/d/10n9gcRl_b4MnBQcttlq8KU_xQEEW77gChigIrGgRQEM/edit#heading=h.skxbo2jstz0i)

---

# Routing
Add the new route to [ModalStackNavigators.js](https://github.com/Expensify/App/blob/190b82d2cca8c74acdbdd2878ea27cccedb6c7fa/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L248-L254) with the name 'FlagComment_Root'
Since each report is flagged on a reportAction, we will update the route to include the reportActionID in [ROUTES.js](https://github.com/Expensify/App/blob/190b82d2cca8c74acdbdd2878ea27cccedb6c7fa/src/ROUTES.js#L74-L74) like flag/:reportActionID
Update [linkingConfig.js](https://github.com/Expensify/App/blob/190b82d2cca8c74acdbdd2878ea27cccedb6c7fa/src/libs/Navigation/linkingConfig.js#L275-L279) to use that new route added above

These will be created in a similar manner to our [Settings](https://github.com/Expensify/App/blob/7a16c46cac55cf7a52a62335596f3099ed385f5c/src/pages/settings/InitialSettingsPage.js) page. After a header section:

```
ScreenWrapper includeSafeAreaPaddingBottom={false}>
{({safeAreaPaddingBottomStyle}) => (
<>
<HeaderWithCloseButton
title={this.props.translate('flags.flagAsOffensive')
onCloseButtonPress={() => Navigation.dismissModal(true)}
/>
<View style={styles.pageWrapper}>
<View style={[styles.settingsPageBody, styles.alignItemsCenter]}>
<Text style={[styles.baseFontStyle]}>
{this.props.translate('initialSettingsPage.aboutPage.description')}
</Text>
</View>
</View>
<Text style={[styles.ph5, styles.textLabelSupporting, styles.mb1]}>
{this.props.translate('flags.chooseReasonBelow’}
</Text>
```

We’ll create a list of MenuItems with the appropriate severity and format:

```
<MenuItem
shouldShowRightIcon
title={this.props.translate('flags.spam'}
description={this.props.translate('flags.spamDescription'}
onPress={() => this.FlagComment(CONST.FLAGS.SPAM)}
wrapperStyle={[styles.borderBottom]}
furtherDetails={this.props.translate('flags.sendAnonymousWarning'}
furtherDetailsIcon={Expensicons.CircleFlag}
furtherDetailsIconFill={colors.yellow}
/>
```

A couple new things to point out in that logic:
* We’ll create constants for the severity levels to ensure consistency
* We’ll also create constants for the possible flag states - pending, hidden, removed, rejected
* We’ll include a FlagComment function within the FlagCommentPage component, which will take the severity from the clicked menu item, combine it with the reportID, reportAction and the user, and call Report.FlagComment, detailed [in the design doc](https://docs.google.com/document/d/10n9gcRl_b4MnBQcttlq8KU_xQEEW77gChigIrGgRQEM/edit#heading=h.qlyxafpdzbot). Since everything except the severity will be the same no matter which option is chosen, it makes the most sense to consolidate it into one function. Once it calls FlagComment, it will dismiss the modal by calling Navigation.dismissModal(true).
* We can create an array of the severity levels and map through them to create the necessary MenuItems to not repeat ourselves, but either way the end format will match the above.
* We will be updating MenuItem to take the new optional parameters above - furtherDetails, furtherDetailsIcon, furtherDetailsIconFill - and create the third line of details shown in the mocks. This will be done by adding an additional section to the bottom of the MenuItem text [here](https://github.com/Expensify/App/blob/7a16c46cac55cf7a52a62335596f3099ed385f5c/src/components/MenuItem.js#L159). It will take a similar format:

```
{Boolean(props.furtherDetails) && (
<Text
style={[styles.furtherDetailsStyle]}
numberOfLines={1}
>
<Icon
src={props.furtherDetailsIcon}
fill={props.furtherDetailsIconFill}
               height={variables.iconSizeNormal}
               width={variables.iconSizeNormal}
               style={styles.m2}
          />
{props.furtherDetails}
</Text>
)}
```

The style will be the same as the description text style, but one font size smaller.

**Comment by dangrous** [comment]
will get to this next week!

**Comment by dangrous** [comment]
@shmaxey here's the deets on the copy! https://expensify.slack.com/archives/C03SSAQG5/p1684932257657339

**Comment by shmaxey** [comment]
Reviewing yellow columns here: https://docs.google.com/spreadsheets/d/1TvHXqVjPE8QU62Z546M9ESeGMo1JsCTKP3NBAKQtsW0/edit#gid=0

Done!

**Comment by shmaxey** [comment]
Shoot, sorry @dangrous - I'll leave this 👐

**Comment by dangrous** [comment]
Thank you @shmaxey!

**Comment by dangrous** [comment]
Not a bug, just getting a teammate to help with payment for @eVoloshchak's review

**Comment by isabelastisser** [comment]
@dangrous, please let me know what I need to do next. Create a job in Upwork and pay @eVoloshchak on June 8? What's the payment amount?

**Comment by dangrous** [comment]
I believe internal review is $1k (@eVoloshchak correct me if I'm wrong)! And yep, you got it - job for payment on 6/8.

**Comment by isabelastisser** [comment]
cool, thanks @dangrous ! ;)

**Comment by isabelastisser** [comment]
Not overdue. Payment on June 8!

**Comment by dangrous** [comment]
We're ready for payment @isabelastisser !

**Comment by dangrous** [comment]
@isabelastisser is out until Wednesday - @eVoloshchak are you okay with waiting until then? If it's pressing I can find another team member to help out.

**Comment by eVoloshchak** [comment]
@dangrous, sure, I can wait no problem

**Comment by isabelastisser** [comment]
@eVoloshchak sorry for the delay! I will issue the payment now.
