### ISSUE TITLE
 Removing and adding the same last number in the year in URL seems to act weird in the date of birth field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to profile > Personal information > date of birth
2. Now click on year and change the year to any options available and again click on the year field. See that in the URL, the year field is updated properly
3. But now, go to URL and just remove the last digit in the year , and again add the same digit and hit enter (even though nothing has changed)
4. Now select any other year from the available option and see that even when you have selected a new year field, still some other year is being displayed on the calendar . Additionally, if you check the URL, it shows a different year date.

## Expected Result: 
Removing and adding the same last number in the year in URL should not affect the year field of the date of birth
## Actual Result: 
Removing and adding the same last number in the year in URL seems to act weird in the date of birth field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.4
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236564516-a23dd8f5-0e5b-489a-afd4-fe0a2cb91bdb.mp4

https://user-images.githubusercontent.com/43996225/236564536-705cf844-2302-4ede-bf55-5c9d0f7002a9.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683270119752679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
>I think most users won't be directly updating the url like this and probably its ok

I agree with you @huzaifa-99 that this doesn't feel like a bug to me because this isn't a user flow that we should expect users to take and thus we don't need to support it. 

I'm going to close, but feel free to reopen or comment if anyone disagrees!
