### ISSUE TITLE
The behavior of the emoji reaction modal is inconsistent.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18519]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Website
2. Go to chat and send/request money
3. Hover on the message and open actions modal
4. Click on unread message.

## Expected Result: 
The emoji reaction modal behavior should be consistent.
## Actual Result: 
The behavior of the right side emoji reaction modal is inconsistent.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236588732-9c6a5a56-2e96-4c82-a5fe-1dff089e88b4.mov

https://user-images.githubusercontent.com/43996225/236588746-38521cea-66a2-4bba-b662-0abf7469c0a1.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683286164251049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
@huzaifa-99 Asking the team about what you said, will update soon.

**Comment by greg-schroeder** [comment]
After review I think I agree it's expected based on the different nature of the message types - I'm going to close.

**Comment by Tushu17** [comment]
Hey @greg-schroeder, I think there's a misunderstanding about the bug. The bug here is that the mini action menu will be shown for all the report action items, but when you use an action like mark as unread or copy link, you won't see the mini action menu (it comes for a split second, then disappears). This works fine on a normal text message, but you will see this bug for money messages, attachments, links, etc.


https://github.com/Expensify/App/assets/89839952/3f471d6c-7c20-4d73-a2b9-dedfc12cefda

**Comment by Tushu17** [comment]
@greg-schroeder bump.
