### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-25] Show tasks in LHN

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#18510]
Show 'open' tasks in the LHN
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abe3d089e176d8e5</li>
        <li>Upwork Job ID: 1664711797481693184</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Working on it

**Comment by thienlnam** [comment]
This issue is all ready for payment cc @adelekennedy 

Just one payment to @fedirjh 
Internal C+ review $1000

**Comment by thienlnam** [comment]
@adelekennedy Bump when you get the chance!

**Comment by adelekennedy** [comment]
@fedirjh sent you the offer on Upwork!

**Comment by adelekennedy** [comment]
amazing - ended contract, sent 1k
