### ISSUE TITLE
[HOLD for payment 2023-05-25] Update reaction counter colors to match mentions

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18530]
With mentions we made it so that green is the color to indicate your own mentions. We should update reactions to use the same colors (green100/green600).

Current: 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1371996/236638519-73d67946-778a-4ca0-a000-df0ca820364e.png">

Update to:  
<img width="402" alt="image" src="https://user-images.githubusercontent.com/1371996/236638493-783954f5-ced6-4cc1-8f8a-5e4a3dbf507a.png">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e54bbac501c88946</li>
        <li>Upwork Job ID: 1656793569861054464</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
I'm working on this with @puneetlath as part of our mentorship but I'm a bit blocked on issues with my dev environment, which Puneet has been helping me troubleshoot.

**Comment by kadiealexander** [comment]
Have created the [pull request,](https://github.com/Expensify/App/pull/18819) but I'm still having persistent troubles with my dev environment. Will work through those and update the testing checklist.

**Comment by puneetlath** [comment]
@kadiealexander has a PR that is almost ready.

**Comment by kadiealexander** [comment]
[PR](https://github.com/Expensify/App/pull/18819) is ready for review!

**Comment by kadiealexander** [comment]
Payment issued to @thesahindia. Thanks for reviewing my first NewDot PR!
