### ISSUE TITLE
Text fields not resetting between new input attempts in "Connect bank account" page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Settings > Workspace > Connect bank account
2. Enter a random fake routing number and account number for testing (You can use [this website](https://randommer.io/routing-number-generator) to get random numbers)
3. Click continue
4. Input some text inside of "Legal business name" and "Company address"
5. Click outside of the side bar to close it or click "ESC" key
6. Open "Connect to bank account" page again
7. Generate another random routing number and bank account number using the previous website shared on step 2.
8. Input those new random routing number and bank account number and click "Continue"
9. Notice the "Legal business name" and "Company address" text fields

## Expected Result:
The “Legal business name” and “Company address” fields should be empty for each new bank account attempt
## Actual Result:
The “Legal business name” and “Company address” fields retain the previous input text
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236688265-e8b544b1-80d6-405f-afdc-40516556d643.mp4

https://user-images.githubusercontent.com/43996225/236688271-e1abfeb8-599c-448b-a8e6-2556c334c9e7.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683299598638019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nathan-Mulugeta** [comment]
> I don't think this is a bug, we intentionally save draft values in the form.

@Prince-Mendiratta Don't you think the draft values should reset for new bank account details? It makes sense if the drafts persist when user uses the same bank account details again.

**Comment by sophiepintoraetz** [comment]
I agree with @Nathan-Mulugeta here - if there have been new details entered, it's false to assume that the routing and account number belong to the same company/company address (it _could_ but I don't think it's best practise from a security perspective)

**Comment by sophiepintoraetz** [comment]
I think it's unlikely that a customer will typo **both** the routing and account number but have raised it in bug zero [her](https://expensify.slack.com/archives/C01SKUP7QR0/p1683687633261969)e.

**Comment by sophiepintoraetz** [comment]
All right, we've agreed that because
>This is by design since we store all bank details as drafts

we're going to close this issue. Thank you @Nathan-Mulugeta for bringing it up though!
