### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] On add contact detail page of non-default contact green dot message please enter the magic code sent to is not consistency with current dot Indicator 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Navigate to setting  -> Navigate to profile -> Navigate to contact method
3. Navigate to non-default contact detail page
4. Notice green dot message please enter the magic code sent to

## Expected Result:  
Green dot Indicator message should have same consistency as other places like text colour should be grey and font size small
## Actual Result:  
Green dot Indicator message appears to be in white colour and font size is big

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="959" alt="1" src="https://user-images.githubusercontent.com/43996225/236689317-2acd63c0-c364-4284-91aa-96f78e5e61da.png">

<img src="https://user-images.githubusercontent.com/43996225/236689304-3c6839ad-3a63-480b-b9a5-40a7fca6b6ff.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683310488445319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a230de6d0c5da064</li>
        <li>Upwork Job ID: 1655406066697568256</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
On add contact detail page of non-default contact green dot message please enter the magic code sent to is not consistency with our current dot message display
### What is the root cause of that problem?
Currently we have wrapped message in simple `<View>` with `DotIndicator` icon that looks like `<DotIndicatorMessage>` without same styling as actual component that makes inconsistency with other dot message in app
### What changes do you think we should make in order to solve the problem?
We need to use actual `<DotIndicatorMessage>` to display message with type of `success` that will make consistency with other messages display
Additionally if we want to increase size of font we need to create new props to `<DotIndicatorMessage>` that allows to add text styling as per requirement
```js
//ContactMethodDetailsPage.js
-   <View style={[styles.flexRow, styles.alignItemsCenter, styles.mb1]}>
-     <Icon src={Expensicons.DotIndicator} fill={colors.green} />
-        <View style={[styles.flex1, styles.ml4]}>
-           <Text>
-             {this.props.translate('contacts.enterMagicCode', {contactMethod: formattedContactMethod})}
-           </Text>
-         </View>
-   </View>
+              <DotIndicatorMessage
+                type="success"
+                style={[styles.mb3,]}  // just an example to match margin top we can adjust this styling at PR stage
+                messages={{0: this.props.translate('contacts.enterMagicCode', {contactMethod: formattedContactMethod})}}
+              />
```
 ### What alternative solutions did you explore? (Optional)
- We can apply same styling as `<DotIndicatorMessage>` to current `<View>` (not recommended)
-

**Comment by kadiealexander** [comment]
Able to reproduce:

![image](https://user-images.githubusercontent.com/59587260/236723764-34eb0406-aea4-41f9-91aa-1d315def440a.png)

Assigning @0xmiroslav as C+ as requested.

**Comment by kadiealexander** [comment]
@thienlnam context on this bug is [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683306332985029?thread_ts=1683190809.653859&cid=C049HHMV9SM), @shawnborton and others have decided that this approach would be best for consistency. Please take a look at @dhairyasenjaliya's proposal [here](https://github.com/Expensify/App/issues/18544#issuecomment-1537503420), he was involved in the original discussion and has a lot of context on the issue.

**Comment by thienlnam** [comment]
Sounds good, will let @0xmiroslav review proposals

**Comment by kadiealexander** [comment]
@thienlnam, @0xmiroslav was happy with @dhairyasenjaliya's proposal ([confirmed here](https://github.com/Expensify/App/issues/18544#issuecomment-1537601021)), we're just waiting on your approval!

**Comment by thienlnam** [comment]
Oh yikes - missed that message, thanks for confirming

**Comment by kadiealexander** [comment]
@0xmiroslav any thoughts on the checklist above?

**Comment by kadiealexander** [comment]
Qualifies for a speed bonus!

Assigned: May 11th 10:56am GMT+12
Merged: May 13th 3:32am GMT+12

Sent contracts to @dhairyasenjaliya and @0xmiroslav

**Comment by kadiealexander** [comment]
Paid @dhairyasenjaliya the bounty + speed bonus + reporting bonus ($1750).

**Comment by kadiealexander** [comment]
Everyone is paid, everything is done! Thanks @dhairyasenjaliya and @0xmiroslav!
