### ISSUE TITLE
[$1000]  If users enter wrong magic code multiple times, they can't login even enter the correct magic code.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account. Try to enter incorrectly magic code few times.
2. Try to login with correct magic code.

## Expected Result:
User should be able to login with magic code.
## Actual Result:
User couldn't login with correct magic code.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236690055-c167ac69-d75c-4efb-8c0d-7afc2f891b81.MP4

https://user-images.githubusercontent.com/43996225/236690314-1994e3ee-9a94-4409-8e38-0f927d47cc8a.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683355600779989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d84294d921c80b3</li>
        <li>Upwork Job ID: 1655401577245560832</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Reassigning to Kadie (Android <> ios issue swap)

**Comment by kadiealexander** [comment]
Reproduced on iPhone version 1.3.11:

https://user-images.githubusercontent.com/59587260/236721068-c0d5bd82-dab3-4b38-952d-bde2e2e40bb3.MP4

**Comment by kadiealexander** [comment]
@danieldoglas I was wondering, is it possible we're intentionally limiting the number of login attempts? If so, this would influence the solution/"expected behaviour" here. Any guidance you can give on what is supposed to happen here would be helpful :)

**Comment by wildan-m** [comment]
I believe that there is unexplained information on how long the code will be expired and how many attempts are allowed.

I've inspected the front-end requests and responses. Nothing wrong with the requests but the API response keeps showing the same error message.

For the backend I'd recommend adding a more detailed error when the code has expired or the code submit attempts have reached, so the user can re-request the magic code.

**Comment by pecanoro** [comment]
I posted in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683536790843689?thread_ts=1683355600.779989&cid=C049HHMV9SM.), this is expected to avoid attacks, we can close it!
