### ISSUE TITLE
[$1000] DEV: The characters like < in the description is displayed as &lt in the new money report but is displayed well on the chat report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any single chat on web chrome
2. Try to request money and make sure to add any text in description with <
3. Notice that it displays '&lt' in the new money report down the cash text. But if you notice it is displayed well (<) in the chat report

## Expected Result:
The characters like < in the description should be displayed as < in the new money report in a similar way how it is displayed on the chat report
## Actual Result:
The characters like < in the description is displayed as &lt in the new money report but is displayed well on the chat report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** N/a
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236691616-43086c8e-1bf4-48de-a429-ae4514a0a152.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683357783709189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127198fd6d1af3e0d</li>
        <li>Upwork Job ID: 1656031768026296320</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Reviewing this now!

**Comment by isabelastisser** [comment]
Hey @aimane-chnaif, I can no longer reproduce this after I updated my chat. Thanks for the heads up, closing!
