### ISSUE TITLE
App displays Sent money/Request money message with capital first letter for few seconds before changing to all small letters

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18547]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Click on plus
4. Click on send money/request money, enter any amount and complete the request

## Expected Result: 
App should display send/request money message either with first letter capital or all small letters but it should not switch after few seconds
## Actual Result: 
App displays message in LHN and in report with first letter capital for few seconds and then changes it to all small letters
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236691075-7e73670a-09dc-40a2-9fac-3fbc1ce76b8b.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683195742666969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Thanks for catching @Prince-Mendiratta! I'm closing based on this comment: 

https://github.com/Expensify/App/issues/18359#issuecomment-1533678823
