### ISSUE TITLE
 The Connect bank account page opens again upon clicking the back button in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to web chrome
2. Go offline
3. Go to any workspace
4. Click on connect bank account
5. Now click on back icon
6. Notice that the same page opens again instead of going back on clicking the back button
7. If you follow the same steps in online mode, this problem doesn't persist

## Expected Result:
The Connect bank account page should not be opened again upon clicking the back button in offline mode
## Actual Result:
 The Connect bank account page opens again upon clicking the back button in offline mode (Works well on online mode)

NOTE: (If it is not reproducible on the first try, it gets reproducible on the second try.)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236694400-072eeb77-83a5-4f74-8a68-97e9f8646194.mp4

https://user-images.githubusercontent.com/43996225/236694406-c263a83f-7bf7-4dd1-a590-a1eeb3721c5c.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683380264270409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I feel this is so minor it's not worth prioritizing at this time. Firstly it's pretty edge case as it only happens when adding a bank account offline, second it is only reproducible some of the time, and clicking back a second time reverts to the correct behavior. So I don't think this is worth fixing right now, going to close this but perhaps we might reopen it in the future.
