### ISSUE TITLE
DEV: Requested or sent money message shows default profile picture

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. change Profile picture(if it’s default Profile picture)
2. go to any chat
3. click on + icon
4. select requested or sent money option
5. request or sent any amount
6. check the profile picture in chat

## Expected Result:
should not show default profile picture
## Actual Result:
default profile picture appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236691719-230119e3-6f16-49f5-abf1-0dacb4c1051a.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683357157168249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Discussion on [the thread here](https://expensify.slack.com/archives/C049HHMV9SM/p1683561507399049?thread_ts=1683357157.168249&cid=C049HHMV9SM), closing.
