### ISSUE TITLE
[$1000] Press and hold reaction emoji highlights emoji shortcode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open an existing chat
2. Send message
3. React to the message with emoji
4. Press and hold the reaction emoji
5. The emoji shortcode (:fire) is selectable 

## Expected Result: 
The emoji shortcode shouldn't be selectable

## Actual Result: 
shortcode on the emoji is selected

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:**new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236692550-f502fff4-db9d-4078-bb6f-05aba3f7e991.mp4

https://user-images.githubusercontent.com/43996225/236692556-359da89f-50c4-4e24-bc96-444d65cfb760.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683360430748899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158e77952c96c0f58</li>
        <li>Upwork Job ID: 1655689523583827968</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
When pressing down a button (in this case the emoji reaction), the selection shouldn't happen. We have a discussion and decided to wait for the new version of rn-web here https://github.com/Expensify/App/issues/14139#issuecomment-1379475849 which will completely fix the issue.

We also have a similar issue here https://github.com/Expensify/App/issues/13908 and this selection issue happens on everywhere, except the button that we apply a workaround by disabling the selection.

cc: @parasharrajat

**Comment by Christinadobrzyn** [comment]
Thanks for the insights @parasharrajat I'll close this issue.

**Comment by Natnael-Guchima** [comment]
Hello @parasharrajat @Christinadobrzyn, I see that an issue that have the same nature as I reported here is being fixed [here](https://github.com/Expensify/App/issues/18661), and the one I reported is closed. I am curious to know the difference between the issue I reported here and the one fixed here https://github.com/Expensify/App/issues/18661
