### ISSUE TITLE
Magic code textfield shows navigate textfield arrow with keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18563]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to login screen
2. Enter email -> Click continue
3. Open keyboard to enter magic code

## Expected Result: 
It should not show navigate arrows, If shown it should work to navigate through Code textfields.
## Actual Result: 
It shows textfield navigation arrow -> Clicking on which nothing happens.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236699450-372c375e-709b-451d-a35f-27ae2089c6bd.MP4

https://user-images.githubusercontent.com/43996225/236699539-55105bc8-8e52-422c-b7c7-a5b2d1f16e79.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dinaljivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683418137709749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
https://github.com/Expensify/App/issues/16629#issuecomment-1526104925
