### ISSUE TITLE
Invalid TLDs is allowed in autoemail

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send an email with invalid TLD to a chat (for example, test@google.invalidtlds )

## Expected Result : 
Email with invalid TLD should've treated like URL with invalid TLD, hence the email shouldn't be parsed as autoemail
## Actual Result : 
Email with invalid TLD parsed as autoemail like normal email

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![staging new expensify com_r_2732096450181853](https://user-images.githubusercontent.com/43996225/236700106-1c5e3fcd-e10e-4caf-b28a-d6fe79f92088.png)
<img width="953" alt="4" src="https://user-images.githubusercontent.com/43996225/236700115-74b5d056-d64a-434f-84be-928d69ab241b.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683424560086649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Agree completely. This is a feature really, as we don't validate TLD in the markdown as you note.
