### ISSUE TITLE
Payment issue for E/App PR#18467 and 18148

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#18572]
Issue created to compensate the Contributor+ member for their work on https://github.com/Expensify/App/pull/18467 and https://github.com/Expensify/App/pull/18148
E/E issue linked to the PR - https://github.com/Expensify/Expensify/issues/270587.
Contributor+ member who reviewed the PR - @parasharrajat .

Wait 7 days after the PR is deployed to production before issuing payment in case there are regressions.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a10078882d2c713</li>
        <li>Upwork Job ID: 1655493612896010240</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@kevinksullivan please note that the total is $2000 since there are 2 PR reviews linked to this issue.

**Comment by luacmartins** [comment]
waiting on payment

**Comment by kevinksullivan** [comment]
Offer sent to @parasharrajat . Let me know when you accept!

**Comment by kevinksullivan** [comment]
All set
