### ISSUE TITLE
[HOLD E/E#280523] Update report actions when contact method is set as default

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#18575]
As mentioned in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1683282627072939), [this PR](https://github.com/Expensify/App/pull/16750) has one slight problem: When a default contact method updates, we update the `personalDetails` onyx key fine but we don't update report actions

Right now report actions have personal details in them, and when a contact method is set as default, we don't update report actions. So if you don't have a display name set, when your new contact method is now default, your report actions won't show your new default contact method. Similarly, your contacts (people you've messaged) won't get the update until they refresh.

Now, this is not a huge problem because you can refresh the page to fix this. But it would be best if this could update live

We're going to keep this issue ON HOLD until https://github.com/Expensify/Expensify/issues/280523 moves forward, because in that project we plan to hide a lot of personal contact info in the App so you can't scrape it, and we'll re-key personal details by accountID. So this should help us solve this issue 👍

**Comment by Beamanator** [comment]
still can't prioritize 😬

**Comment by Beamanator** [comment]
still on the list

**Comment by Beamanator** [comment]
same

**Comment by Beamanator** [comment]
same

**Comment by Beamanator** [comment]
@cristipaval i wonder if we should keep this one open 🤔

**Comment by cristipaval** [comment]
I feel like this thing needs a decent amount of effort to get it done for a small benefit that is indeed a nice thing to have, but the effort might bring more value if put on other priorities 🤷

**Comment by Beamanator** [comment]
yeahhhhh i feel ya

**Comment by Beamanator** [comment]
gunna postpone another month and see what happens 🤷

**Comment by Beamanator** [comment]
hmmmm

**Comment by Beamanator** [comment]
ok let's close this one for now since there's a bunch of other priorities still 🙃
