### ISSUE TITLE
Inconsistency between the paste option in mWeb Safari and Native iOS App in iPhone XR /16.4.1

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any website that has an image on the page(I have tested with https://help.expensify.com/),
2. Long press on the image, and press copy
3. Now open the native app and paste it into composer
4. We will see the copied link
5. Now go to safari mWeb and paste to composer
6. It will paste nothing

## Expected Result:
Both platforms should behave the same, if we are parsing the link in iOS native then Safari also should behave the same
## Actual Result:
Nothing happening in the mWeb safari when pressing paste

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari iPhone XR iOS 16.4.1
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236870899-aceff7f5-fb6b-4b3b-a4f8-b4af7af35f22.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1682630641114419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
I'm not able to reproduce this and have a different result with an iPhone 14 Pro. Given the specificity of the model and that people should be downloading the app (vs using the mobile version) I don't think this is something we should look into further.

https://github.com/Expensify/App/assets/42940078/191fea56-06f8-4618-9b88-4526b8a6bba2
