### ISSUE TITLE
[$1000] Composer on android repositioned emojis when copy and paste emojis

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open chat on android app
2. Copy some emojis and paste it on composer
3. Perform same action on chrome

## Expected Result:
Composer isn't repositioning emojis on Android Chrome, it shouldn't be repositioning on the Android app either.
## Actual Result:
Composer on android repositioned emojis when copy and paste emojis but not on android chrome
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236921517-3b9a7082-7b41-42c5-9cd2-78eeb2b900ee.mp4

https://user-images.githubusercontent.com/43996225/236921550-c72b48aa-5743-427b-9532-ef89629bc837.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683484572375849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bc240752e01773d</li>
        <li>Upwork Job ID: 1656022141402427392</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by abekkala** [comment]
still waiting on proposals

**Comment by mountiny** [comment]
I dont think this is worth fixing, its not really a bug sorry. @amyevans @abekkala feel free to reopen if you disagree
