### ISSUE TITLE
The pdf slides along with the vertical scrollbar when using right arrow key of keyboard to slide

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to web chrome
2. Go to any chat
3. Send two pdfs, should be long pdfs with multiple pages (I used the given two pdfs attached in the chat)
4. Click on first pdf and scroll to the bottom of the pdf using mouse
5. Now press the right arrow key on keyboard one after the other (do not use arrow button present on the screen )
6. Notice that the pdfs gets slided horizontally with the vertical scrollbar as well
7. If followed the same process without scrolling the pdfs to the bottom, then this problem doesn't persist. But the problem is seen if pdf is scrolled to bottom and uses right arrow key of the keyboard to slide.

## Expected Result:
The pdf should not be slided along with the vertical scrollbar if the pdf is scrolled to the bottom and uses right arrow key of keyboard to slide
##Actual Result The pdf slides along with the vertical scrollbar if the pdf is scrolled to the bottom and uses right arrow key of keyboard to slide

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236943698-c73aca3a-cfe6-42d6-a69f-24fa26ca10f9.mp4

https://user-images.githubusercontent.com/43996225/236943762-f5212753-0f1a-4969-b769-71660a6f1b88.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683523820067539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I'm not able to repro this on MacOS/ Chrome -- I scroll to the bottom and click the right arrow key on my keyboard, and it just flips to the second PDF (which is expected). @kavimuru can you clarify what the significance of the second PDF is? Does this only occur on PDF 1 when there are 2 x PDFs send in a row?
