### ISSUE TITLE
[Navigation Reboot] Make the UP button more responsive

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18603]
### Problem

Part of https://github.com/Expensify/App/issues/11768

The Up button is slow to begin responsive, when user navigates to chat on iOS and clicks the Up button quickly it does nothing and they need to wait for the chat to load before they can go back to LHN. 

### Why is it important

It creates confusion for the user.

### Solution

Lets make sure this button is as responsive as possible, it should not depend on the chat loading state

cc @staszekscp

**Comment by mountiny** [comment]
Noting this is not actionable yet, SWM will work on this issue and once done we will have to pay C+ for their reviews.

**Comment by garrettmknight** [comment]
Reassigning since I'm headed OOO

**Comment by garrettmknight** [comment]
@NicMendonca nothing to do on this just yet, btw!

**Comment by mountiny** [comment]
Need to test this PR well this week

**Comment by mountiny** [comment]
@staszekscp Could you still look into this one, the UP button does not seem to be super responsive, ie I can see it being rendered but clicking does nothing until more stuff is loaded on the screen

**Comment by mountiny** [comment]
This will be a polish

**Comment by mountiny** [comment]
This was completed by Wojti!
