### ISSUE TITLE
Emoji count indicator does not have hover effect when user has reacted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and hover over the emoji count indicator of a comment that you have not reacted to.
2. Observe that there is a background hover effect on the indicator.
3. React to the comment with any emoji.
4. Hover over the emoji count indicator of your reaction again

## Expected Result:
The emoji count indicator should have a hover effect for user reacted state
## Actual Result:
The emoji count indicator does not have a hover effect when the user has reacted to the comment.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236954466-99c4e176-1a09-4f10-a499-ecd0ca3440a3.mp4

https://user-images.githubusercontent.com/43996225/236954482-d5fc49bc-ebf6-4fbc-ae41-818a339ce552.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683547589938749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Thanks @shawnborton. Closing!
