### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Show up to 4 participant avatars in the IOUPreview for a bill split

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#18641]
### Problem

We introduced the IOUPreview for bill splits https://github.com/Expensify/Expensify/issues/270707. But we are only showing one avatar in the IOUPreview when a bill split is created. Instead, we should show up to 4, or 3 if more than 4 participants are included in the split. 

**Current**
<img width="787" alt="Screenshot 2023-05-09 at 15 35 57" src="https://github.com/Expensify/App/assets/10736861/5209bf2f-ba89-4841-be7a-a8be13ceb17b">

**Desired**
<img width="401" alt="Screenshot 2023-05-09 at 15 34 53" src="https://github.com/Expensify/App/assets/10736861/efa2ca96-f680-44bb-8cca-2cd10f08c302">

In addition, we should make sure the same order is used when the split is created while offline. (So when returning online, the order shouldn't change)

### Solution

Yes please.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a91334bf09c52786</li>
        <li>Upwork Job ID: 1658476194782515200</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by s77rt** [comment]
May be related https://github.com/Expensify/App/issues/15644

**Comment by Julesssss** [comment]
The proposal from @allroundexperts looks good to me. @aimane-chnaif would you mind reviewing this before I assign it? Thanks

**Comment by Julesssss** [comment]
Great, let's get this done

**Comment by flaviadefaria** [comment]
I'm OoO for 8 days so re-adding the BUG label, but keeping myself assigned. I'll be back at work on May 30th.

**Comment by flaviadefaria** [comment]
@aimane-chnaif can you please fill out the checklist above so that I can issue payment? Thanks!

**Comment by flaviadefaria** [comment]
@allroundexperts and @aimane-chnaif I'm sending you offers in UW.
$1000 + $500 bonus = $1500 total payment for each of you.

**Comment by flaviadefaria** [comment]
Everyone has been paid so closing this.
