### ISSUE TITLE
Web - Invite Members - User can not move to another line by pressing Shift + Enter

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2 Log in with any account.
3. Click Setting > any Workspace > Manage members > Invite.
4. Select several users and click Next button
5. Type any message on Message tab and use Shift + Enter key

## Expected Result:
User can type message in new line after pressing Shift + Enter

## Actual Result:
User can not move to another line by pressing Shift + Enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/25cf6b57-3087-42a2-a358-bcf467dbf11d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Closing as a dupe then. Thanks @Ollyws.
