### ISSUE TITLE
Split Bill - Incorrect Split participants list if Spit bill among part of the group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18143

## Action Performed:
1. Login to NewDot
2. Create a group with 5 other accounts
3. Click "+" in the group chat
5. Split any bill between part of the group, for example add 3 participants
6. Observer IOU Preview show your avatar and +3 icon
7. Click on the IOR Preview

## Expected Result:
List of split bill participants should be displayed

## Actual Result:
Whole group list is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/85b75d28-a0df-474e-9eac-56dba9daf9f8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
At Accountex so won't get to triaging this bug for a few days, reassigning.

**Comment by bernhardoj** [comment]
> Tapping it will open the group participants page for now.

Based on the [PR](https://github.com/Expensify/App/pull/18143) details, this is expected for now.

**Comment by puneetlath** [comment]
Closing based on the discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1684174641690159
