### ISSUE TITLE
[$1000] Fix iOS React Native error 'value' is unavailable

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#18653]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem
With the latest Xcode installed, when you run `npm run ios` it fails with the error `'value' is unavailable: introduced in iOS 12.0`

## Importance
All developers needs to be able to easily run the App on iOS. The workarounds for now are to downgrade to an older version of Xcode or manually set the iOS Deployment target to iOS 13.0 for the React-Codegen Pod, as described [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1681932203856889?thread_ts=1680773983.844719&cid=C01GTK53T8Q). These workarounds are time consuming and we don't want to have to do them forever.

To be clear this is a dev only error, not a bug with the App

## Solution
Upgrade our react native installation to at least 0.71.6 which [will fix this error](https://github.com/facebook/react-native/issues/34106#issuecomment-1501129541).

**Issue reported by:** @neil-marcellini

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180b96036d141f4c5</li>
        <li>Upwork Job ID: 1655979058433728512</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
This isn't actually a bug but I wanted to use the label temporarily to kick start the process with external contributors. I think a contributor can fix this.

**Comment by neil-marcellini** [comment]
Awesome thanks for linking that @aimane-chnaif! I figured maybe that was already in the works. I'll hold on the [upgrade issue](https://github.com/Expensify/App/issues/18444) and we can retest once it's done.

**Comment by s77rt** [comment]
Not overdue.
@neil-marcellini Can you add the "HOLD" to the title?

**Comment by flaviadefaria** [comment]
@neil-marcellini when put this on hold can you also switch it to weekly?

**Comment by neil-marcellini** [comment]
Oh yeah on it, I must have gotten distracted last time.

**Comment by flaviadefaria** [comment]
I'm OoO for 8 days so re-adding the BUG label, but keeping myself assigned. I'll be back at work on May 30th if this needs to be actioned before I'm back please re-apply the bug label.

**Comment by s77rt** [comment]
Still on hold

**Comment by neil-marcellini** [comment]
ditto

**Comment by neil-marcellini** [comment]
Holding, I'm making this a monthly.

**Comment by neil-marcellini** [comment]
Still on hold, there's progress.

**Comment by s77rt** [comment]
#18444 is now resolved. I think we can close this.

**Comment by neil-marcellini** [comment]
Oh awesome, yes!
