### ISSUE TITLE
[$1000] The url is blinked when going to Connect bank account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Setting --> Workspace --> Click any  workspace --> connect bank account
2. Observe that the web navigate to route bank-account/?policyID=D7528E69D4F8995C
3.  And immediately navigate to bank-      account/new?policyID=D7528E69D4F8995C

## Expected Result:  
the web should only navigate to bank-account/new?policyID=D7528E69D4F8995C
## Actual Result : 
the web navigate to route bank-account/?policyID=D7528E69D4F8995C And immediately navigate to bank-account/new?policyID=D7528E69D4F8995

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/de6488b1-f67b-4375-a417-41f0796e007a

https://github.com/Expensify/App/assets/43996225/97057b34-f672-4845-aecb-be9c2b1825d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683540276607439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153374c26113a43e4</li>
        <li>Upwork Job ID: 1657049326108028928</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The Connect bank account page opens again upon clicking the back button in offline mode
### What is the root cause of that problem?
In the workspace page, when clicking Connect bank account button we will navigate to route `bank-account/?policyID=D7528E69D4F8995C` and `ReimbursementAccountPage` Component is opened. But in this component
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L159-L162
We immediately navigate to route `bank-account/new?policyID=D7528E69D4F8995C`
### What changes do you think we should make in order to solve the problem?
When clicking the connect bank account, if we don’t have substep we should navigate to `bank-account/new?policyID=D7528E69D4F8995C` directly
in this line
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/ROUTES.js#L24
We should replace by
```
getBankAccountRoute: (stepToOpen = ‘’, policyID = ‘’) => `bank-account/${stepToOpen || ‘new’}?policyID=${policyID}`
```
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
Thank you! Adding the external label.

**Comment by dukenv0307** [comment]
## Proposal
[My proposal](https://github.com/Expensify/App/issues/18657#issuecomment-1540595925)

**Comment by miljakljajic** [comment]
I'm going to be heading to EC3 tomorrow so I'll assign another BZ team member to keep this moving while I'm out!

**Comment by slafortune** [comment]
@0xmiroslav @arosiclair thoughts on the two proposals?

**Comment by arosiclair** [comment]
IMO this is a not an issue. 

@marcaaron it looks like you implemented these redirects originally. Do you think this needs to be changed?

**Comment by marcaaron** [comment]
I don't actually see anything happening in the linked videos that concerns me. I believe the user is just being redirected to different routes in this flow. Without doing a deeper dive here I'd say we should just defensively do nothing for now unless this redirection actually creates some problem for a user trying to set up a bank account. The flows are kind of complex and I don't really want to think about them. 

A proposal like this:

>if we don’t have substep we should navigate to bank-account/new?policyID=D7528E69D4F8995C directly
in this line

Needs more information to back up that we should make this change e.g. why is there no substep? How will `getBankAccountRoute()` be used? More details are required I think to create a complete picture of how this works now and whether the proposed changes are safe or not.

**Comment by arosiclair** [comment]
Yeah the claimed "problem" is that the URL is redirected from `bank-account` to `bank-account/new`. I don't see how this is an issue for the user or even bad UX. Redirects like this happen all the time on many websites.

I vote to close this. @slafortune what do you think?

**Comment by slafortune** [comment]
Yeah - I agree
