### ISSUE TITLE
Intercept `Unsubscribe` messages to mute and whisper the user that they will no longer receive notifications.

### ISSUE THREAD

**Issue by johnmlee101** [Expensify/App#18654]
We have seen in the public SF Lounge  channel that people are replying `unsubscribe` expecting to be unsubscribed from it, without signing in and setting it to `Mute`. 

Let's mute the channel automatically and whisper them that they have been muted, and with recommendations on how to follow-up. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168f017edae4824cc</li>
        <li>Upwork Job ID: 1655981167854067712</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by johnmlee101** [comment]
<img width="878" alt="image" src="https://github.com/Expensify/App/assets/5258036/76081700-bb15-4a38-8c13-eb2421cd359c">

**Comment by johnmlee101** [comment]
This is internal since it requires we intercept these messages in the backend from email and the client, to properly send the whisper and change the mute settings directly

**Comment by johnmlee101** [comment]
@jasperhuangg I think this issue was a dupe then?

**Comment by MitchExpensify** [comment]
Not sure on the dupe being referred to but sounds like @jasperhuangg may know?

**Comment by MitchExpensify** [comment]
Lil bump on the dupe confirmation @jasperhuangg

**Comment by jasperhuangg** [comment]
Hey guys sorry! Didn't get any notifications for this.

This should already be implemented by @NikkiWines so we can close it out. It's a dupe.
