### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000]  Holding down on the plus emoji icon selects the next comment username

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Hold down on the plus emoji icon

## Expected Result:
Should open the emoji selection modal and should not select any text
## Actual Result:
Selects the next comment username

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c8c8799f-3fcc-482c-98cd-6545a26ddea7

https://github.com/Expensify/App/assets/43996225/04577207-cb09-48ca-beca-7cf0b599e578

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683451356614169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118a8a9f35817cb2c</li>
        <li>Upwork Job ID: 1656847351663558656</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by arielgreen** [comment]
Reproduced, this can be handled externally

**Comment by NikkiWines** [comment]
Nice, agreed that @hoangzinh's proposal looks good 👍

**Comment by arielgreen** [comment]
@Nathan-Mulugeta @hoangzinh @parasharrajat please be sure to apply to the posting on Upwork asap, so that once ready we can issue payment. https://www.upwork.com/jobs/~0118a8a9f35817cb2c

**Comment by Nathan-Mulugeta** [comment]
Just applied on upwork.

**Comment by arielgreen** [comment]
@Nathan-Mulugeta @parasharrajat @hoangzinh offers sent in Upwork.

**Comment by Nathan-Mulugeta** [comment]
Offer accepted.

**Comment by Natnael-Guchima** [comment]
Hello @parasharrajat , 
I have reported a bug (https://github.com/Expensify/App/issues/18553) that has a similar nature as the bug being fixed here. You suggested that it shouldn't be fixed here (https://github.com/Expensify/App/issues/18553#issuecomment-1539866674). I am curious if there is a difference in the nature of these two bugs.

Thanks. 
cc: @Christinadobrzyn


https://github.com/Expensify/App/assets/57330233/671fdea8-3746-4798-a817-31e8dce12e19

**Comment by arielgreen** [comment]
Calculating payments:
- 5/15 issue [assigned](https://github.com/Expensify/App/issues/18661#event-9247949988) to @hoangzinh 
- 5/16 PR [merged](https://github.com/Expensify/App/pull/18957#event-9257560836)

1 business days = 50% bonus

$250 to @Nathan-Mulugeta 
$1000 + 50% = $1500 to @hoangzinh 
$1000 + 50% = $1500 to @parasharrajat

**Comment by arielgreen** [comment]
Payments issued to @hoangzinh and @Nathan-Mulugeta. @parasharrajat please complete [checklist](https://github.com/Expensify/App/issues/18661#issuecomment-1552507158).

**Comment by arielgreen** [comment]
I am OOO tomorrow and Monday, reassigning.

**Comment by lschurr** [comment]
Great, I'll spin up a regression test request and we'll get this closed out.

**Comment by lschurr** [comment]
All set.

**Comment by lschurr** [comment]
Ah, thanks @parasharrajat - just issued payment.
