### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Assign Task - An incorrect error message is displayed when clicking confirm task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Go to FAB -> Assign task
4. Enter a title and description and navigate to the next page
5. Click Confirm task without entering Assignee

## Expected Result:
The error asks for a share destination but not a title

## Actual Result:
An incorrect message is displayed.
The title was entered, and the error asks for it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/76a5feda-b685-4440-95d2-154e8be59559

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e12624031ff7035</li>
        <li>Upwork Job ID: 1656738721911836672</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
discussed in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1683831806789709) and going to move forward with solving this here. CC @thienlnam

**Comment by madmax330** [comment]
@aimane-chnaif have you had time to review the proposals?

**Comment by kevinksullivan** [comment]
I'm going to reassign this since I'll be OOO for several days.

**Comment by MitchExpensify** [comment]
> @aimane-chnaif have you had time to review the proposals?

Friendly bump @aimane-chnaif

**Comment by MitchExpensify** [comment]
Bumped @aimane-chnaif 1:1

**Comment by s-alves10** [comment]
I think my proposal is the most effective one among others. We need to remove redundant states because they affect the memory and the performance.

**Comment by madmax330** [comment]
@aimane-chnaif I agree with your recommendation. @MitchExpensify can you update the expected result, I will get the translations and post them here.

**Comment by MitchExpensify** [comment]
Sorry, I am not 100% what the new expected result is. Mind pointing me in the right direction?

**Comment by madmax330** [comment]
Still waiting on the exact translation, should get it today, slack link here: https://expensify.slack.com/archives/C21FRDWCV/p1685089018304109

**Comment by MitchExpensify** [comment]
Looks like the translations came through @madmax330 @aimane-chnaif 

> "Por favor selecciona con quien deseas compartir"

(which is "please select with whom you want to share")

**Comment by MitchExpensify** [comment]
Great! 

Invite sent to @allroundexperts & @aimane-chnaif for eventual payment https://www.upwork.com/jobs/~015e12624031ff7035

**Comment by NickTooker** [comment]
Copy looks good - straight forward. I would put periods on the end of the sentences. Thanks!

**Comment by MitchExpensify** [comment]
Unassigning myself to pass the bug-zero baton back to @kevinksullivan since he's returned from OOO 👍

**Comment by kevinksullivan** [comment]
Hey @aimane-chnaif and @allroundexperts , please finish out the steps above so I can pay this on time. Thanks!

**Comment by kevinksullivan** [comment]
Hi @aimane-chnaif @allroundexperts bumping the above. Please finish this out and then I'll make the payments. Thanks!

**Comment by kevinksullivan** [comment]
Thanks @aimane-chnaif . Payments are made but I am waiting for upwork to let me end the contract 🙃 .

<img width="1422" alt="image" src="https://github.com/Expensify/App/assets/22508290/29f2f7ec-8866-44ca-99db-11adbd1ea528">

**Comment by kevinksullivan** [comment]
Will close this out and set a reminder to check the job for ending contract. Thanks everyone!
