### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] Assign Task - No focus on Description field in Assign task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Go to FAB -> Assign task
4. Enter a title and NOT enter the description -> click Next
5. Open Description tab

## Expected Result:
Focus present on the Description input field

## Actual Result:
No focus on the Description input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5921ba5e-3ea9-49f0-b313-d1856904feb3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117d4766144af9638</li>
        <li>Upwork Job ID: 1656000410323333120</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
Reproduced, and I agree that this is a bug (it's inconsistent with how the _Title_, _Assignee_ and _Share somewhere_ pages work. I'll assume this is external, but @thienlnam , @JmillsExpensify or @shawnborton let me know if you think this should be internal.

**Comment by thienlnam** [comment]
Yeah, let's get this handled externally! Great to introduce contributors to the Assign Task flow

**Comment by brianlee1025** [comment]
How do i create an account with assign task permission in dev env?

**Comment by s77rt** [comment]
@dhairyasenjaliya Sorry I just realised you have a proposal. Will review asap.
@brianlee1025 Can you please ask on Slack instead?

**Comment by s77rt** [comment]
@dhairyasenjaliya Thanks for the proposal. Your RCA is correct (I assume you made a type we are _not_ using autoFocus). Your suggested fix makes sense.

I noticed on `NewTaskTitlePage` we use `autoFocus`, is this broken on Android? For consistency let's either make both `NewTaskTitlePage` and `NewTaskDescriptionPage` focus the text input `onEntryTransitionEnd` or  just add `autoFocus` to `NewTaskDescriptionPage`'s text input.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @luacmartins

**Comment by s77rt** [comment]
@dhairyasenjaliya Thanks for the quick follow up. Let's go with `onEntryTransitionEnd` then :rocket:!

**Comment by s77rt** [comment]
Not overdue. PR is in draft status.

**Comment by s77rt** [comment]
@dhairyasenjaliya Thank for the PR

No, all seems good from my side. Try clear onyx storage is the issue still persist please ask on slack.

**Comment by conorpendergrast** [comment]
I've just sent offers via Upwork, held on deploy and 7-day regression period.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/17992
- The offending PR has been commented on: https://github.com/Expensify/App/pull/17992#issuecomment-1551290419
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1684326161989029
- Determine if we should create a regression test for this bug: No

**Comment by conorpendergrast** [comment]
Pay day, moving to Daily

**Comment by conorpendergrast** [comment]
Paid, contracts ended, [checklist completed](https://github.com/Expensify/App/issues/18660#issuecomment-1551344550). All done, and closing!
