### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] The Home Address State/Province field is autofilled with the country for UK addresses

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to Settings -> Profile -> Personal details -> Home Address
2.  In Address line 1 type "5 New Street" and select the result with "Edinburgh"
3.  Note that the state is "Scotland" which is a country and not a state

## Expected Result:
State/Province field should only be populated with a state or county

## Actual Result:
State/Province field is populated with a country

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="954" alt="1" src="https://github.com/Expensify/App/assets/43996225/fa9d6925-4b06-4147-819d-24c27283599b">

![image](https://github.com/Expensify/App/assets/43996225/adf8d37f-e1bc-465a-a885-8ab2cbbb32cb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jjcoffee 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683624757070259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101458ae8ee232f2f</li>
        <li>Upwork Job ID: 1656130500883591168</li>
        <li>Last Price Increase: 2023-05-10</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Able to reproduce:

![image](https://github.com/Expensify/App/assets/59587260/a2a4e19b-5783-47fb-9d6d-3badc228a36d)

**Comment by kadiealexander** [comment]
@kavimuru could you please tag the person who submitted the proposal in the post?

**Comment by jjcoffee** [comment]
@kadiealexander That one's mine (see [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683625325479429?thread_ts=1683624757.070259&cid=C049HHMV9SM)). I'm going to repost as it looks like some of the formatting went wonky!

**Comment by MonilBhavsar** [comment]
We discussed in the bug report slack thread, and the expected behavior is - For UK addresses, we won't display country(England/Wales/Scotland/Northern Ireland) in state/province field, instead get the real state/province from google API  cc @mollfpr

**Comment by mollfpr** [comment]
@MonilBhavsar checked the @jjcoffee proposal, and it works well. We can go with their proposal!.

🎀 👀 🎀 C+ reviewed!

**Comment by MonilBhavsar** [comment]
Looks good to me too 👍

**Comment by jjcoffee** [comment]
@MonilBhavsar @mollfpr [PR](https://github.com/Expensify/App/pull/19046) is ready!

**Comment by jjcoffee** [comment]
Chill Melv - we're just waiting for production deploy

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is an edge case and improvement for UK addresses.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Regression should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.

Indeed.

>[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Propose regression step

1. Go to Settings -> Profile -> Personal details -> Home Address
2. In Address line 1 type "5 New Street" and select the result with "Edinburgh"
3. Ensure that the state/province field is "Edinburgh"
4. 👍 or 👎

**Comment by kadiealexander** [comment]
Contracts sent to @mollfpr and @jjcoffee :)

**Comment by jjcoffee** [comment]
@kadiealexander Accepted, thanks! Also just to note that the reporting bonus is also due for me.

**Comment by kadiealexander** [comment]
Paid $1750 to @jjcoffee (Job + speed bonus + reporting bonus)
Paid $1500 to @mollfpr (job + speed bonus)

Thanks for the awesome work team!
