### ISSUE TITLE
[$1000] Writing ">" only on a new line after a quoted text does not appear when posted as a comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18680]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and type “>” in the text composer and hit enter
2. Observe that the character “>” is posted as a normal text
3. Type “> Test” in the text composer and hit shift + enter to add a new line
4. Type “>” only on the next line and hit enter to post the comment

## Expected Result:
The character “>” should appear as a normal text on the new line under “Test” in quotes.
## Actual Result:
The character “>” does not appear on the new line under “Test” in quotes. The comment only shows “Test” in quotes.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/535e1c69-dfa3-4e76-b093-3c3bb1bc92b8

https://github.com/Expensify/App/assets/43996225/752470d2-6375-4086-ac66-ea06481699e2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683645798808979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f5712970138ef0b</li>
        <li>Upwork Job ID: 1656378469411139584</li>
        <li>Last Price Increase: 2023-05-10</li>
    </ul>
</details>

**Comment by eh2077** [comment]
This doesn’t look like a bug but a common function of markdown quote syntax, like a quote 
```
> 
> 
> test
> 
> 
> 
```
will also be simplified to 
> test

**Comment by isabelastisser** [comment]
@eh2077 point above makes sense! @AndrewGable , can I close this?

**Comment by isabelastisser** [comment]
Bump @AndrewGable

**Comment by AndrewGable** [comment]
Yes, makes sense to close
