### ISSUE TITLE
[$1000] System displays a technical error message (Auth ResendValidateCode returned an error) when clicking 'Resend magic code' of unlinked secondary login account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Part 1

1. Sign in to `Account A` at https://staging.new.expensify.com/ (I used c.dobrzyn@expensifail.com)
2. Click Profile Icon in LHN
3. Click Profile
4. Click Contact Method
5. Click New Contact Method
6. Add an unverified public email as a secondary login (I used c.dobrzyn+1@gmail.com)> click Add

Part 2

7. Open a new browser tab in Incognito
8. Go to the https://www.expensify.com/ sign-in page
9. Click Email > Enter the unverified public email address
10. Click on Unlink button

Part 3

11. Open the email Inbox of the unlinked account, click on 'the validation link' here to unlink the account
12. Verify that 'Secondary login successfully unlinked' message is displayed

Part 4

13. Go back to `Account A` at https://staging.new.expensify.com/, Profile > Contact Method
14. Click on the unverified email address 
16. Click on 'Resend magic code' link
17. See error
18. Try to remove the failed public email 

## Expected Result: 

System should display an error message that is understandable for user. You should be able to remove the unverified email. 

## Actual Result: 

System displays a technical error message (Auth ResendValidateCode returned an error). You can't remove the unverified email.
Seems to be related to using a public unverified email. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Long video:

![2023-05-10_15-43-03 (2)](https://github.com/Expensify/App/assets/51066321/5e307ce1-1ed1-4c81-b3cb-285a0b8ed945)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683647479085879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a0bde8b0f3f71cb</li>
        <li>Upwork Job ID: 1656784555758092288</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Hum, I'm not getting the error message, I'm seeing a link resent. [Asking](https://expensify.slack.com/archives/C049HHMV9SM/p1683681411432769?thread_ts=1683647479.085879&cid=C049HHMV9SM) the report to test again and tell me what I'm missing. 

![image](https://github.com/Expensify/App/assets/51066321/f8d61145-bc8a-49db-9a2e-56dacdf2c1a6)

**Comment by Christinadobrzyn** [comment]
We _think_ this only happens when you have an unverified public email.

**Comment by mountiny** [comment]
@johnmlee101 Checking in here, are we sure this can be solved externally? it feels like we might have to do some API adjustments here

**Comment by johnmlee101** [comment]
Yeah I think that makes sense

**Comment by johnmlee101** [comment]
the issue is that the unlinked login should have been removed via pusher update when removed via `Unlink`, so that they would have the option to resend the code to an account they have not claimed

**Comment by Christinadobrzyn** [comment]
@johnmlee101 or @mountiny should we change this to an internal job?

**Comment by johnmlee101** [comment]
Yeah I believe so

**Comment by Christinadobrzyn** [comment]
Awesome, sorry for missing that. I made the Upwork private and added the Internal label.

**Comment by Christinadobrzyn** [comment]
Hey @johnmlee101 just checking on this one to resolve the overdue

**Comment by Christinadobrzyn** [comment]
I think we're still working on a PR, is that right @johnmlee101?

**Comment by johnmlee101** [comment]
Yeah will start this week!

**Comment by Christinadobrzyn** [comment]
Removing the `Help Wanted` label - sorry I missed that!

**Comment by Christinadobrzyn** [comment]
Internally work on this, @johnmlee101 feel free to add any extra update!

**Comment by Christinadobrzyn** [comment]
I'm going to move this to weekly while we work on this

**Comment by Christinadobrzyn** [comment]
Hey @johnmlee101 or @rushatgabhane do you have an update on this? Or can you attach a PR so I can track this?

**Comment by Christinadobrzyn** [comment]
Hey @johnmlee101 sorry to keep bothering you about this but can you please add the PR to this GH so I can track that for updates? Should we move this to a weekly label?

**Comment by johnmlee101** [comment]
I'm sorry, I've been stretched thin with our audit tasks. A lot of that is due EOM so hoping to make time after that

**Comment by Christinadobrzyn** [comment]
Working on this!

**Comment by johnmlee101** [comment]
Got a fix incoming!

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're working on the [PR](https://github.com/Expensify/Web-Expensify/pull/38137) and then payment. I'll take this when I'm back if it's still open.

**Comment by johnmlee101** [comment]
Can this be re-tested? This was deployed to production?

**Comment by Natnael-Guchima** [comment]
Re-tested this on production. It seems to be working fine. 


https://github.com/Expensify/App/assets/57330233/163e6b72-8815-4c20-b012-656fb064043a

**Comment by greg-schroeder** [comment]
Just catching up on this - seems the only thing that involved external contributors here was @Natnael-Guchima reporting this in the first place.

**Comment by greg-schroeder** [comment]
Sent offer to @Natnael-Guchima, looks like this can be closed now

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @greg-schroeder
