### ISSUE TITLE
Request Money - Money request preview is displayed twice in chat if there are messages before payment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot and login
2. Under accountA send money request to acountB
3. Send some more messages from A to B after that
4. Under accountB click Pay on preview and submit payment

## Expected Result:
One IOU preview for one requested and paid amount should be in chat

## Actual Result:
IOU preview for the same amount is displayed twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![screenshot_08](https://github.com/Expensify/App/assets/93399543/b6fe4883-400d-4fe5-9a89-aff03b1bb4c8)

https://github.com/Expensify/App/assets/93399543/55c58a77-f374-4b59-9e06-e22d8b08c539

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Putting Deploy Blocker label, issue is not reproductible in provided build https://18652.pr-testing.expensify.com/


https://github.com/Expensify/App/assets/93399543/f2f00b20-be2d-4637-bfea-48d9965ebebf

**Comment by marcaaron** [comment]
Asking for someone involved with Manual Requests project to take a look here. I'm not sure if this is the expected behavior or not, but seems likely related to changes we merged.

**Comment by marcaaron** [comment]
Maybe this PR? https://github.com/Expensify/App/pull/18143

**Comment by JmillsExpensify** [comment]
Coming from Slack, just wanted to clarify that we decided to not block deploys on IOUs/manual requests issues. Stuff will break as we get this update out the door.

**Comment by marcaaron** [comment]
🖖

**Comment by Julesssss** [comment]
This is technically a bug with the `isMostRecentIOU` logic, but let's ignore it as the entire condition is about to be removed [here](https://github.com/Expensify/App/pull/18486) (we'll always show the IOUPreview against an IOUAction).
