### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Assign task - Title and Description in Welcome page is in English in Spanish account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditional: you can use Spanish account
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Click the global create menu and select 'Assign Task'
4. Enter a title and description and navigate to next page
5. Click on the "Assignee" and select and Assignee
6. Click "Confirm Task"

## Expected Result:
Title and Description in Welcome page is in Spanish

## Actual Result:
Title and Description in Welcome page is in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (39)](https://github.com/Expensify/App/assets/93399543/278efe7a-9cd2-400f-8a41-80c8fe124b37)

https://github.com/Expensify/App/assets/93399543/965e244b-34b8-486a-9989-e350d5370af4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5e1781ac0818102</li>
        <li>Upwork Job ID: 1658653285947367424</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
Thanks for the patience here. @allroundexperts's [proposal](https://github.com/Expensify/App/issues/18690#issuecomment-1540988892) looks good to implement here.

@aldo-expensify All yours.

**Comment by aldo-expensify** [comment]
Thanks @mananjadhav . Hiring @allroundexperts

**Comment by mananjadhav** [comment]
@maddylewis Here's the items from the checklist. This is ready for payout today.

https://github.com/Expensify/App/pull/18806 is the PR. We didn't add the translation in the `MenuItemWithTopDescription` components. I've added the comment on the PR https://github.com/Expensify/App/pull/18806#issuecomment-1572361795

> I verified any copy / text shown in the product is localized by adding it to src/languages/* files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)

I don't think we need a discussion in the channel, and we already have an item in the checklist for this.

Also I don't think we need a regression test for this one. @aldo-expensify let me know if you think otherwise.

**Comment by maddylewis** [comment]
### Payments
- no reporting bonus 
- @mananjadhav (C+) - $1000
- @allroundexperts - $1000

**Comment by mananjadhav** [comment]
@maddylewis this is eligible for timeline bonus I guess

**Comment by maddylewis** [comment]
got it - i included bonuses for both @mananjadhav and @allroundexperts

**Comment by maddylewis** [comment]
i believe we're all set here - closing!
