### ISSUE TITLE
[Fabric] - IOS - User can not copy and paste the magic code, also unable to open the keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18719]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Enter sign in > Continue
3. Go to email and copy the magic code
4. Return to app and try to past the magic code
5. Try to open keyboard

## Expected Result:
User can copy and paste the magic code, also able to open the keyboard if needed.

## Actual Result:
User can not copy and paste the magic code, also unable to open the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b32f461-d048-4848-9884-cb8b90cf84a6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
@WoLewicki will also be working on this issue, but he's OOO so I'm tagging him.

**Comment by j-piasecki** [comment]
Fixed in https://github.com/Expensify/App/pull/13767/commits/f4df6be83c3300ba144b97659962bbb1ab530a0f

**Comment by j-piasecki** [comment]
Aside from the 1-frame flicker, it works as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/4d6d90f4-6403-455e-8f2e-c53f90a70cd2
