### ISSUE TITLE
[Fabric] - Android - App is flashing when selecting Fub menu and than tapping outside of the field.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the special build
2. Log in with any account
3. Tap on Fub menu
4. Tap on outside of the field

## Expected Result:
App is not flashing when selecting Fub menu and than tapping outside of the field.

## Actual Result:
App is flashing when selecting Fub menu and than tapping outside of the field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6c735676-3b4f-4a36-b583-6a83b3404fa6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
@WoLewicki will also be working on this issue, but he's OOO so I'm tagging him.

**Comment by j-piasecki** [comment]
Fixed in https://github.com/WoLewicki/App/commit/22a657bf154a46631795147e4b8d1089fd33f9ef.

**Comment by j-piasecki** [comment]
On app build from current(https://github.com/WoLewicki/App/commit/70992f24e718ec6b1ee909358dbeb44e9318b415) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/8495b10f-2461-456d-9027-38d322215436
