### ISSUE TITLE
[Fabric] - Android - Chat - User unable to select any options in Fub menu and conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the special build
2. Log in with any account
3. Go to any chat
4. Tap on Fub menu or go to any conversation
5. Select any options

## Expected Result:
User can select any options in Fub menu and conversation

## Actual Result:
User unable to select any options in Fub menu and conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9a1b62de-1bcd-455f-ad6b-9b89fc950968

https://github.com/Expensify/App/assets/93399543/c458a177-eced-4555-9eff-10ed40373abf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
@WoLewicki will also be working on this issue, but he's OOO so I'm tagging him.

**Comment by j-piasecki** [comment]
It seems to be working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/70992f24e718ec6b1ee909358dbeb44e9318b415) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/7575ad45-d9ed-44e6-8a82-2533d25786fa
