### ISSUE TITLE
[Fabric] - Workspace - User unable to create/open/close the Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the special build
2. Log in with any account
3. Go Setting - Workspace
4. Select Create New Workspace button
5. Tap on any Workspace, try to use < and X  buttons

## Expected Result:
User able to create/open/close the Workspace

## Actual Result:
User unable to create/open/close the Workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fbee130f-2fbf-4505-b0d5-8ad093783204

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
All Settings options are blocked

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
@WoLewicki will also be working on this issue, but he's OOO so I'm tagging him.

**Comment by j-piasecki** [comment]
It seems to be working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/70992f24e718ec6b1ee909358dbeb44e9318b415) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/1287cb6f-d642-4ad9-a1a8-2a4737ac0a9f

https://github.com/Expensify/App/assets/21055725/9586d285-6560-4ceb-90c5-26a8e138fef4
