### ISSUE TITLE
[Fabric] -Android - Chat - Сhat history isn't displayed if you send messages with multiple line breaks(5 and more)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the special build v1.3.11-2
2. Log in with any account
3. Go to any chat with history
4. Copie message in Slack and paste in app( mine: E.g:
I'm a text with

line

breaks

Gggggggg
Test jgucufhchc

Yfhcgdubhzfcjcgxu)

## Expected Result:
It was copied/pasted correctly.

## Actual Result:
Сhat history isn't displayed if you send messages with multiple line breaks (5 and more)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/119316b0-e3c6-4c21-bde6-5ae64fcafbe1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
It seems to be working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/70992f24e718ec6b1ee909358dbeb44e9318b415) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/4ca3d7c3-7036-4890-94de-a4964f24579c
