### ISSUE TITLE
[Fabric] -Android -Chat - Content menu does not work 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the special build v1.3.11-2
2. Log in with any account
3. Go to any chat
4. Press and hold over the message
5. Choose any option

## Expected Result:
The context menu opens and it is possible to select any option.

## Actual Result:
Not works context menu and when it opens it is not possible to select any function.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/004208ce-1c9a-4491-bb3a-be4b68af16c7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
I'm just holding this temporarily so it doesn't get lost in the void. Furthermore, this bug only exists on the Fabric branch

**Comment by roryabraham** [comment]
Added to the GitHub project and pinged in SWM room

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
It seems to be working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/70992f24e718ec6b1ee909358dbeb44e9318b415) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/4167fc2a-30bd-42fa-8659-0c87a722843d
