### ISSUE TITLE
[Fabric] - Android - IOU preview shows default avatars instead of current ones

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18733]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot with account that has non-default avatar
2. Request money (or split bill or send money)
3. Observe IOU preview in direct chat

## Expected Result:
Non-default avatars should be displayed

## Actual Result:
Default avatars are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/1dff7fda98f53e7358ca86851514a96be6cc7906544308e07ba626d38f9e8258

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by WoLewicki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
I'm not sure, but assuming IOUs got moved to the separate chat, it works (I think?):

![android-iou](https://github.com/Expensify/App/assets/21055725/89c0e8c1-41ca-4e96-ba5c-8e1eae4659ca)
