### ISSUE TITLE
[Fabric] - iOS - Payment -Background of the GIF about the successful addition of payment method is lighter

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Payment -> Add payment method -> Bank account
4. Complete the process of adding any BA as payment (can use any bank)

## Expected Result:
The background of the GIF about the successful addition of the payment method is the same as the page background

## Actual Result:
The background of the GIF about the successful addition of the payment method is lighter that the background page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e8a84157-1eee-4746-9e8c-701a5a2f343d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by WoLewicki** [comment]
I'll be working on this issue.
