### ISSUE TITLE
[Fabric] -  iOS - Profile - Avatar image rotates after saving

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18734]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Profile
4. Choose a new profile image by taking a photo or choosing from a gallery

## Expected Result:
Avatar image should NOT rotated after saving

## Actual Result:
Avatar image rotates after saving

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dea8e5bb-f8c4-4726-9198-291651244e5f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
It is working as expected when building the app from the current (https://github.com/WoLewicki/App/commit/e12c1cfd8a9a9eef4bab9471c1c2a0547a4504f5) `andrew-fabric` branch:

https://github.com/Expensify/App/assets/21055725/128ce426-c219-4a75-acb4-51f7437a5b71
