### ISSUE TITLE
The money report seems to have missing ~ if messages are written within this special characters in a single ~

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot
2. Go to any chat
3. Send/Request money
4. On the description field add message within ``
5. Send money
6. Result: On the money report , the first and the end special characters with ~ and * seems to gets disappeared

## Expected Result: 
The money report should not have missing ~ if messages are written within this special characters in a single ~
## Actual Result: 
The money report seems to have missing ~ if messages are written within this special characters in a single ~
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2e5e516f-1aae-4aaf-bac3-c7bd485569c1

https://github.com/Expensify/App/assets/43996225/7e3c41c4-7a6c-4d89-9358-60a014ec2ae1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683700882666639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I think this is the same as this https://github.com/Expensify/App/issues/17798 - asking

**Comment by Christinadobrzyn** [comment]
Confirmed to be related to https://github.com/Expensify/App/issues/17798 closing in favour of 17798.
