### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] Auto-suggester throws console error when scrolling through less than 5 options

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18744]
If you only have one option and you use the arrow keys to scroll through the list, you see a console error. We should fix this. 

https://github.com/Expensify/App/assets/97473779/600eed38-cb03-447b-9d5c-1a33cddf5534

@0xmiroslav did you want to take this one? 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d83c4180a356aaa0</li>
        <li>Upwork Job ID: 1656674431586570240</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@abekkala I'm going to take this one with @0xmiroslav

**Comment by puneetlath** [comment]
@0xmiroslav mind giving an ETA on when you'll have the PR up?

**Comment by Santhosh-Sellavel** [comment]
@0xmiroslav I believe you are aware of the PR which caused this one can you link it if you know, thanks!

**Comment by puneetlath** [comment]
Yep! I included reporting bonus as a milestone in the contract I sent you.

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel / @0xmiroslav] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/14686
> * [x]  [@Santhosh-Sellavel / @0xmiroslav] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/14686#issuecomment-1553405155
> * [x]  [@Santhosh-Sellavel / @0xmiroslav] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A this should be caused based on checklist
> * [x]  [@Santhosh-Sellavel / @0xmiroslav] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel / @0xmiroslav] If we decide to create a regression test for the bug, please propose the [regression test] (https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [ ]  [@puneetlath] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@puneetlath do you agree with above, let me know thanks!

**Comment by puneetlath** [comment]
Looks good to me!

**Comment by puneetlath** [comment]
All paid. Thanks for the quick work y'all!
