### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-02] Include yourself and @here options in mentions auto-suggestion list

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18746]
You have the ability to mention yourself and also to use @here to mention the entire group, but these options don't currently show up in the auto-suggestion box. Let's make it so that they do. 

Today: 
<img width="515" alt="image" src="https://github.com/Expensify/App/assets/1371996/59a971b3-3fdf-4702-8b2b-1f2080435adf">
<img width="369" alt="image" src="https://github.com/Expensify/App/assets/1371996/cb28aa30-57b3-4395-97c5-a9e93eee64bf">

Ideal: 
<img width="403" alt="image" src="https://github.com/Expensify/App/assets/1371996/34d093a7-da0b-4ae0-86ba-79f2394d3623">

@szebniok do you want to take this one? 

Reported by @0xmiroslav 
@dhairyasenjaliya also reported the issue of reports showing up in the list
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124eb9e68a1e7d86b</li>
        <li>Upwork Job ID: 1663295315309010944</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@allroundexperts I'm going to let @szebniok take this if he wants it, since it's a follow-up to the mentions functionality he built. 

A couple thoughts I have: 
1. When you just type `@` with no other input, we should show `@here` first
2. Maybe instead of reusing `OptionsListUtils.getNewChatOptions` we should create a `OptionsListUtils.getMentionsOptions`

**Comment by puneetlath** [comment]
@szebniok mind commenting here so I can assign you?

**Comment by puneetlath** [comment]
I mainly just meant that this should only show actual users. 

<img width="321" alt="image" src="https://github.com/Expensify/App/assets/1371996/0629ca81-c208-4027-8e9d-f46a573b0d0d">

**Comment by puneetlath** [comment]
Thanks @allroundexperts. Reading the proposal, I wonder if actually `getOptions` is overkill for what we're looking to do here. Maybe we don't need to care about reports at all. And we just need to look through the `personalDetails` object and form the list based on what is in there.

**Comment by puneetlath** [comment]
That's cool. And how does sorting of the results work? 

Sidenote, if we go this route, the function probably shouldn't live in `OptionListUtils` since it doesn't anything to do with optionLists anymore.

**Comment by puneetlath** [comment]
No, I don't think so. Was mostly trying to think through it. @eVoloshchak what do you think?

**Comment by eVoloshchak** [comment]
Agree with the approach @allroundexperts is proposing [here](https://github.com/Expensify/App/issues/18746#issuecomment-1542978816)
 > Is there any particular sorting requirement here?

Unless it's already done, I think we need to sort the participants alphabetically

I wonder if to make this faster we need to use something similar to [this](https://github.com/Expensify/App/blob/7d7fa72d83a9c34aeff83eea200297bc2dd10a2c/src/libs/OptionsListUtils.js#L240) with [isSearchStringMatch](https://github.com/Expensify/App/blob/7d7fa72d83a9c34aeff83eea200297bc2dd10a2c/src/libs/OptionsListUtils.js#L493) instead of `.includes`. Or just stop iterating if suggestions array is already full instead of iterating over every participant

**Comment by eVoloshchak** [comment]
> Should we sort by participant name or email?

On other screens we sort by `displayName`, which is name, unless there is no name, then it's just an email

**Comment by puneetlath** [comment]
Agreed.

**Comment by Naveen3Singh** [comment]
Hi! The merged PR #19221 causes the phone number account suggestions to display as `@1234567890@expensify.sms` in the suggestions as well as in the chat.

<img src="https://github.com/Expensify/App/assets/36371707/a8c87d37-7939-4eb9-8062-bdda8c256b83" width=500 />

https://github.com/Expensify/App/assets/36371707/50127c0a-2c87-4617-9b71-bdb346b03a0b

@puneetlath `DeployBlockerCash`?

**Comment by puneetlath** [comment]
It's not really a bug, it's more like something we specifically chose not to include in the v1 launch. So I'm going to go ahead and consider the checklist done. 

I've gone ahead and sent contracts. Will pay on June 2nd if no regressions.

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
