### ISSUE TITLE
Adding the Reply in Thread Button

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#18759]
HOLD for
- https://github.com/Expensify/App/issues/18758

https://docs.google.com/document/d/18uQqP0eTe1kWPrQiQwjv_A6u3cBO3VtiwA55XndjCnY/edit#bookmark=id.5nabie55vpm7
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e32c894d9d1d8e3f</li>
        <li>Upwork Job ID: 1656455632610930688</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
Why is this on hold?

**Comment by chiragsalian** [comment]
closing
