### ISSUE TITLE
[HOLD] Opening the child report in NewDot

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#18758]
HOLD for
https://github.com/Expensify/Expensify/issues/280245
https://github.com/Expensify/Expensify/issues/280246
https://github.com/Expensify/Expensify/issues/280250

https://docs.google.com/document/d/18uQqP0eTe1kWPrQiQwjv_A6u3cBO3VtiwA55XndjCnY/edit#bookmark=id.uarsetc478jh
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128fb16d6243b0623</li>
        <li>Upwork Job ID: 1656454870915112960</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
Should this still be on hold? We already did this right?

**Comment by grgia** [comment]
yep closing
