### ISSUE TITLE
[HOLD for payment 2023-05-23] Updating the report header for thread reports

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#18755]
https://docs.google.com/document/d/18uQqP0eTe1kWPrQiQwjv_A6u3cBO3VtiwA55XndjCnY/edit#bookmark=id.rozkmqxmc7gb
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebf41ba655824e9b</li>
        <li>Upwork Job ID: 1656454552644759552</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
@grgia or @chiragsalian, is it just @s77rt that's awaiting payment? If so, how much?

**Comment by sonialiap** [comment]
@grgia @stitesExpensify or @chiragsalian, bumping Sophie's question

is it just @s77rt that's awaiting payment? If so, how much?

**Comment by s77rt** [comment]
I think it's $500 for this regression https://github.com/Expensify/App/issues/19490 (https://github.com/Expensify/App/pull/18522#discussion_r1204597404).

**Comment by sonialiap** [comment]
Thanks!

@s77rt offer sent

**Comment by s77rt** [comment]
Accepted!

**Comment by sonialiap** [comment]
Paid 💸
