### ISSUE TITLE
[HOLD for payment 2023-05-23] UI updates to threaded reportActions

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#18754]
https://docs.google.com/document/d/18uQqP0eTe1kWPrQiQwjv_A6u3cBO3VtiwA55XndjCnY/edit#bookmark=id.j5zokgrosxqx
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148ad160090916260</li>
        <li>Upwork Job ID: 1656454528233635840</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
I'm OoO for 8 days so re-adding the BUG label, but keeping myself assigned. I'll be back at work on May 30th.

**Comment by sakluger** [comment]
When I looked over the PR, I noticed there were some follow-up PRs being created. @stitesExpensify @grgia just confirming, are we paying the standard $1k for the C+ review, or does payment need to wait for those follow-up PRs?

**Comment by stitesExpensify** [comment]
I think we can just pay. We were rushing the process for ec3 so the follow-ups aren't really the fault of the C+

**Comment by sakluger** [comment]
Hey @parasharrajat I sent you an offer through Upwork, let me know once you've accepted. Thanks!

**Comment by sakluger** [comment]
Paid, thanks!
