### ISSUE TITLE
[$1000] Use HOC in HeaderView and ReportActionItem

### ISSUE THREAD

**Issue by grgia** [Expensify/App#18769]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174f3c35c0f6d69de</li>
        <li>Upwork Job ID: 1656570377315319808</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
in progress

**Comment by grgia** [comment]
will update my PR this week

**Comment by grgia** [comment]
Will look at this PR again this week. It's been lower priority due to other bugs

**Comment by grgia** [comment]
PRs been updated

**Comment by grgia** [comment]
I decided to close the PR, but the checklist was completed. I'll add BZ for payment anyways, thank you @fedirjh!

**Comment by grgia** [comment]
@Christinadobrzyn could you help with $1000 C+ Internal PR Review Payment to @fedirjh ?

**Comment by Christinadobrzyn** [comment]
Yep! Created a new Upwork job 

Internal Job - https://www.upwork.com/ab/applicants/1679925312026189824/job-details
External job - https://www.upwork.com/jobs/~0139abe1effd923d3a

@fedirjh can you apply and I'll pay you you? Thanks!

**Comment by Christinadobrzyn** [comment]
Paid $1000 to @fedirjh in Upwork

I'll close this - let me know if I'm missing anything!
