### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-25] [HOLD for payment 2023-05-23] Improve UI for the LHN workspace request items

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#18773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

We recently merged changes that [show money requests in the LHN](https://github.com/Expensify/App/pull/18537). In the interest of meeting strict deadlines, we're splitting up the UI polish to this issue.

**Tasks** 

**1) Truncate long workspace names** 
<img width="447" alt="237663246-82348d1c-f23b-4d48-a2cc-6edf5189999f" src="https://github.com/Expensify/App/assets/10736861/4c622766-2c06-44a6-9f57-3caa09bf438a">

**2) The border color of the workspace badge on top of the avatar is incorrect**
- It should be lighter to match the header area
- The workspace icon should be hanging off the bottom-right edge by -4px to the bottom and to the right
- The workspace icon should also have a border radius of 4px too.

**Current**
<img width="102" alt="237679316-a969112c-3c39-47e8-9cbb-23bbbf703a80" src="https://github.com/Expensify/App/assets/10736861/e6f22b7c-b462-46e5-a79f-f8dfe6bd61dd">

**Design guide**
<img width="334" alt="237679564-596a2b42-956c-478b-9070-cf1fd7c1c05a" src="https://github.com/Expensify/App/assets/10736861/71af72f6-42c2-43b9-bda8-e571bbdfe692">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** No
**Reproducible in production?:** No
**Issue reported by:** @shawnborton 
**Conversation:** https://github.com/Expensify/App/pull/18537#issuecomment-1543861909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175330523faac43e4</li>
        <li>Upwork Job ID: 1661754958661038080</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@shawnborton would you like to add anything else to this one before I go asking for a C+ volunteer to pick it up.

**Comment by shawnborton** [comment]
@Julesssss can you share more screenshots of what the feature currently looks like and I can go from there?

**Comment by Julesssss** [comment]
hey @shawnborton. This feature should soon be on the staging release, but in the meantime you can get a good idea of the design from the `Screenshots/Videos` section in [this PR.](https://github.com/Expensify/App/pull/18537)

**Comment by Julesssss** [comment]
@shawnborton if this works, it should show you all the screencasts: 

<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/25520267/f60c1808-c89a-4117-a025-7a2ae75cf785


https://github.com/Expensify/App/assets/25520267/7848491e-5b11-4fdd-9fff-0d58540ef513


</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/25520267/5c8293d5-6163-4d4b-820e-99c2b1bfe0dc


https://github.com/Expensify/App/assets/25520267/818cae5c-d044-4240-83ad-81ba350fda7d


</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/25520267/e9057032-a88d-41b3-82bf-8dbe8fb2f50b


https://github.com/Expensify/App/assets/25520267/e4d8f33f-7ac7-453a-b36b-ee3093cf4932


</details>

<details>
<summary>Desktop</summary>



https://github.com/Expensify/App/assets/25520267/14271840-34f5-4e14-88b8-eedaff1c92cc


https://github.com/Expensify/App/assets/25520267/5445c38e-14c8-4278-9cec-44b7fe389ad6


</details>

<details>
<summary>iOS</summary>



https://github.com/Expensify/App/assets/25520267/25b47cac-6b31-454a-b1ef-f562d523cafa


https://github.com/Expensify/App/assets/25520267/db87d915-4843-46a1-a0e7-f2761fec7fd9


</details>

<details>
<summary>Android</summary>



https://github.com/Expensify/App/assets/25520267/823a2358-7da2-4f4c-8820-7f240bba8bb1


https://github.com/Expensify/App/assets/25520267/e298caa9-91c9-4f81-b113-0a238f03371c


</details>

**Comment by shawnborton** [comment]
@Julesssss how is this view possible? 
<img width="577" alt="image" src="https://github.com/Expensify/App/assets/2319350/a18bafb8-27ed-498c-8b62-adf43203572f">

Is that just because we haven't created the actual report view yet?

**Comment by shawnborton** [comment]
Is there a way to get the top status bar area to match the header area of the report?
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/2319350/ea1c2c69-f0ef-4e09-be3d-a415c1387ce6">

**Comment by shawnborton** [comment]
For the header view, I feel like there is too much space below the avatar row:
<img width="299" alt="image" src="https://github.com/Expensify/App/assets/2319350/9170e7bd-49dd-4e15-8245-c09406e3fb1b">


From our mockups, it looks like this:
<img width="694" alt="image" src="https://github.com/Expensify/App/assets/2319350/02f5628e-eac8-41d0-9de4-7c0dd24f24d4">

So 20px on the left of the avatar, and 20px below.

**Comment by s77rt** [comment]
@shawnborton 

> I feel like the gap between "To" and the actual recipient is way too big here - I wonder if we can fix this as well?

This is coming from the `SectionList`. Currently it's set to 54px. https://github.com/Expensify/App/blob/9fa8c89b095d88b4066f209c16d34e3ee261e991/src/styles/variables.js#L86. We can change this but it will effect all sections in `SectionList` throughout the App.

___

> how is this view possible?

As userA create a workspace and invite userB to that workspace.
As ueerB request money from that workspace. (I think you can get same view if you request with userA as well)

___

> Is there a way to get the top status bar area to match the header area of the report?

Yes, we can use `StatusBar` from RN. But I think in our case we will probably have to extend our [CustomStatusBar](https://github.com/Expensify/App/tree/main/src/components/CustomStatusBar).

___

> For the header view, I feel like there is too much space below the avatar row:

There is a 20px for bottom padding, but a nested element also has 12px so it's in total 32px. I'm not sure if we can collapse those since the other element is nested and not adjacent. An alternative solution is to reduce the outer padding to 8px.

**Comment by shawnborton** [comment]
Yeah, let's fix the gap after "To" to look more like this:
<img width="551" alt="image" src="https://github.com/Expensify/App/assets/2319350/b303f1b2-5dd0-41b0-ae6a-b75ce1a29bb6">

> how is this view possible?

I meant, how do we see an empty state view like this? I didn't think report views would have that. @Julesssss and @trjExpensify can confirm please?

> Yes, we can use StatusBar from RN. 

Sounds good!

> There is a 20px for bottom padding, but a nested element also has 12px so it's in total 32px.

Let's make sure we fix this to match the mockups.

**Comment by trjExpensify** [comment]
>I meant, how do we see an empty state view like this? I didn't think report views would have that. @Julesssss and @trjExpensify can confirm please?

Agreed. It's a bug, it should look like this: 

@luacmartins [pointed out](https://github.com/Expensify/App/pull/18537#issuecomment-1543466478 ) on @mollfpr's PR (where that screenie came from) that @aldo-expensify is working on it here: https://github.com/Expensify/Web-Expensify/pull/37388

**Comment by trjExpensify** [comment]
One other thing.. if this is the report view (albeit broken), it seems like we have default welcome text and two avatars showing in the report view. I don't think that should be there, so we should cut that:  

<img width="615" alt="image" src="https://github.com/Expensify/App/assets/16232057/ce1ec38d-dd24-4931-a124-839ef44d5373">

**Comment by trjExpensify** [comment]
Great point!

**Comment by shawnborton** [comment]
Yeah apologies for not being clear in my comment [here](https://github.com/Expensify/App/issues/18773#issuecomment-1544218976), but that is what I was getting at - how did we get a empty state style for the report view.

**Comment by s77rt** [comment]
I don't think the checklist applies here. This is a polish/improvement for a previous [PR](https://github.com/Expensify/App/pull/18537).

**Comment by s77rt** [comment]
No checklist is required here. https://github.com/Expensify/App/issues/18773#issuecomment-1551405330

**Comment by trjExpensify** [comment]
I agree with that. This was manual requests polish for EC3. Alrighty, payment is due. I've sent the following offers on [this job](https://www.upwork.com/jobs/~0175330523faac43e4): 

@s77rt - $1,500 for the fix + #urgency bonus 
@0xmiroslav - $1,500 for C+ review + #urgency bonus

**Comment by trjExpensify** [comment]
Settled up with @0xmiroslav. Awaiting @s77rt.

**Comment by s77rt** [comment]
@trjExpensify Accepted!
