### ISSUE TITLE
 Android - Chat - The underline is broken for [click google.com *here*](google.com) comment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18779]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login with any account
3. Go to a chat and add a comment [click google.com *here*](google.com)

## Expected Result:
The underline is not broken and located at same levels

## Actual Result:
The underline is broken and located at different levels

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8180b1fb-f271-457e-b366-34f3c8b389a5

![Screenshot_2023-05-11-15-21-03-07_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/93399543/134d8e39-34fb-4a30-8095-abea72fc6c6d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Does not seem to be an issue on v1.3.13-1 (Pixel 3a):

![image](https://github.com/Expensify/App/assets/30815269/05b16def-23cd-4cb3-83a0-9aac558cac1a)
