### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] IOUPreview height should adjust based on content 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#18770]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Create an iou request to any user without adding a comment
2) Settle the IOU
3) Create an iou request to any user without adding a comment
4) Settle the IOU

## Expected Result:
- The Card heights should be different

## Actual Result:
- The card heights are the same
- The card without a description has a large gap where the comment would have shown

**Native mobile**
<img width="343" alt="237498360-a96557f5-ee1f-4e71-be23-dd26fc659c7a (1)" src="https://github.com/Expensify/App/assets/10736861/468bb609-439a-4d00-8b26-67745479edcb">

**Web**
<img width="818" alt="237498770-8c0574b2-9517-48a8-b763-46b3c29234f0" src="https://github.com/Expensify/App/assets/10736861/ca66741f-85d0-4333-a585-d21b580c94dc">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13-0
**Issue reported by:** @thesahindia [here](https://github.com/Expensify/App/pull/18698#issuecomment-1542717263)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6ca19ff51a2559a</li>
        <li>Upwork Job ID: 1656655701807489024</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
thanks both. This is pretty straight forward so I'm going with the first passable proposal. Also creating `requestDescription` on a separate line is a bit more readable.

**Comment by Julesssss** [comment]
@huzaifa-99 feel free to make a start on the PR, I'll assign you once the UpWork job has been created 👍

**Comment by Julesssss** [comment]
Actually I don't think anything will break if I do this now

**Comment by Julesssss** [comment]
Okay nevermind, that didn't trigger the automation, I'll do that once Ted gets a chance to review.

**Comment by trjExpensify** [comment]
I'll take this from Teddy.

**Comment by trjExpensify** [comment]
Yup! Done!

**Comment by mountiny** [comment]
Merged

**Comment by trjExpensify** [comment]
Strange, this should have got the `reviewing` label. PR is on staging. 👍

**Comment by Julesssss** [comment]
The issue will remain open until paid, and Tom will be back soon :)

**Comment by trjExpensify** [comment]
Yuuup, I got back today. 👍 Looking at this now, appreciate the patience.

**Comment by trjExpensify** [comment]
Yup, this was when adding a new feature. Regression tests will be updated more broadly for the manual requests redesign.

**Comment by trjExpensify** [comment]
Okay, so my assessment for payments is as follows: 

@aimane-chnaif - $1,500 for the C+ review & #urgency bonus 
@huzaifa-99 - $1,500 for the fix & #urgency bonus 
@thesahindia - $250 for reporting the bug in [this PR](https://github.com/Expensify/App/pull/18698#issuecomment-1542717263)

Does that sound right to everyone?

**Comment by trjExpensify** [comment]
Awesome, settled. Closing!
