### ISSUE TITLE
Web- Profile - Default avatar changes upon selecting different contact method as default

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/16750

## Action Performed:
1. Login with any account with default avatar (or delete previously uploaded picture)
2. Add a secondary login
3. Set secondary login as default contact method

## Expected Result:
User default avatar should not change (as it doesn't even change if I change profile name)

## Actual Result:
Default avatar changes upon selecting different contact method as default.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/42648da3-d574-4790-ba8f-d18c3afddcdc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdbf4b8c69e5612c</li>
        <li>Upwork Job ID: 1658526193290498048</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by therealsujitk** [comment]
This is internal, each email has an avatar associated with, there's no account avatar. So when the default email changes, it uses it's associated email.

**Comment by therealsujitk** [comment]
This is internal, each email has an avatar associated with, there's no account avatar. So when the default email changes, it uses it's associated avatar.

**Comment by adelekennedy** [comment]
@mountiny can i get feedback on the comment [here](https://github.com/Expensify/App/issues/18780#issuecomment-1546668179) on this being internal?

**Comment by mountiny** [comment]
I dont think this is a bug, you dont choose the avatar, they are random. Once you will be able to choose these, this would be a bug. I will close this out, please re-open if you disagree
