### ISSUE TITLE
Request Money -  Account list for New Chat or Request money is not displayed while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Click + New Chat
3. Observe you can see possible contacts
4. Go offline
5. Click + Request money

## Expected Result:
List of possible accounts should be displayed

## Actual Result:
Skeleton is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cf98eccd-db79-4d6e-b3ac-eaf328f57a7b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Hmm I just tried this in staging web, v1.3.13-0 - and I was able to request money no problem while offline

**Comment by Beamanator** [comment]
@PauloGasparSv do you have time to get to this today / soonish? If not, do you mind dropping it in #engineering-chat to see who can investigate quick? 🙏

**Comment by PauloGasparSv** [comment]
Taking a look at this right now @Beamanator : )

**Comment by Beamanator** [comment]
You're the best!!

**Comment by PauloGasparSv** [comment]
>  Hmm I just tried this in staging web, v1.3.13-0 - and I was able to request money no problem while offline

This is also working for me and I can't replicate this. Pretty confused here, only tested Web so far but the video evidence is from Web so IMO that's ok.

https://github.com/Expensify/App/assets/6564265/03a90441-a508-4dd4-85cb-330400bfea99

https://github.com/Expensify/App/assets/6564265/cf40e0fc-a606-432e-8b21-b23ccedd3d3b

Also tested on v1.3.13.0
![image](https://github.com/Expensify/App/assets/6564265/cdad31c7-d364-41b7-a0bb-03e666cf1a51)

@kbecciv can you double-check if this is still happening? If not let's close this : )

**Comment by PauloGasparSv** [comment]
Oh wait a second, this problem may not be happening to everyone according to [this discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1683821308209489?thread_ts=1683794916.311659&cid=C049HHMV9SM) so maybe that's why we can't replicate this @Beamanator

**Comment by PauloGasparSv** [comment]
Yes, sorry for that! This isn't happening to my `paulo@expensify.com` account but happens to `paulo@expensifail.com` in a different session here. 

![image](https://github.com/Expensify/App/assets/6564265/4eaca181-0da5-4bfb-ba05-2f4f8f62e3e0)

Sorry for the [previous comment](https://github.com/Expensify/App/issues/18781#issuecomment-1544390314) @kbecciv, investigating this again here.

**Comment by PauloGasparSv** [comment]
This may have been introduced by https://github.com/Expensify/App/pull/17349. Coming from [this discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1683827697249329?thread_ts=1683794916.311659&cid=C049HHMV9SM) I've assigned @aimane-chnaif here to create fix P.R. (thanks so much)

cc @amyevans

**Comment by PauloGasparSv** [comment]
Waiting on another +1 review for https://github.com/Expensify/App/pull/18788#issuecomment-1545886473

We discussed this review in slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683794916311659) and it was also mentioned [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683904512365909).

**Comment by mountiny** [comment]
This should be fixed in staging, adding Bug label to help with payments 

@aimane-chnaif Can you help us say if there are any payments here, its not clear to me given it was a regression, thanks!

**Comment by mountiny** [comment]
Gotcha, so I will close this issue out and note on the original issue, thank you!
