### ISSUE TITLE
[HOLD for payment 2023-06-15] Update styling in mentions auto-suggestion component

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18795]
Right now, it looks like this: 

<img width="379" alt="image" src="https://github.com/Expensify/App/assets/1371996/e885cbca-c81a-4ad7-9104-bafaf25ebc5e">

We want it to look like this: 

<img width="421" alt="image" src="https://github.com/Expensify/App/assets/1371996/23e5eff3-ac29-4992-b7dd-8625a68afa87">

From Figma: 
Avatar:
```
width: 24px;
height: 24px;
border-radius: 400px;
```
Display name: 
```
width: 82px;
height: 20px;
font-family: 'Expensify Neue';
font-style: normal;
font-weight: 700;
font-size: 15px;
line-height: 20px;

/* Product/Dark/Text */

color: #E7ECE9;
```
Email address: 
```
width: 166px;
height: 20px;
font-family: 'Expensify Neue';
font-style: normal;
font-weight: 400;
font-size: 15px;
line-height: 20px;


/* Product/Dark/Supporting Text */
color: #AFBBB0;
```

Also note, there is no dash between the name and the email address in the figma mockup. 

@szebniok do you want to take this one? 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4639a0ec44a830a</li>
        <li>Upwork Job ID: 1666844506242052096</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
cc @shawnborton in case there's anything you want to change about the style.

**Comment by shawnborton** [comment]
Nope, mock looks good to me!

**Comment by szebniok** [comment]
Hey @puneetlath, I'll take this

**Comment by puneetlath** [comment]
PR is in review.

**Comment by puneetlath** [comment]
Just merged.

**Comment by slafortune** [comment]
Paid!
