### ISSUE TITLE
Pressing ESC key on "start over" confirmation modal  closes "workspace settings"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the Settings > Workspaces > Connect bank account
2. Click on start over button
3.  After that press Esc

## Expected Result
When the 'Start Over' button is clicked, pressing the 'Esc' then just 'Are you sure' modal should be close
## Actual Result
When the 'Start Over' button is clicked, pressing the 'Esc' key exits the 'Workspace Connect' bank account settings instead of closing the 'Are you sure?' modal.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/82244bd1-0210-42b2-873e-4d0abf328aec

https://github.com/Expensify/App/assets/43996225/b1221181-77fc-4988-bc20-352b49e8f1a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683735687149239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment]
This issue maybe duplicated [this one](https://github.com/Expensify/App/issues/18558)

**Comment by s77rt** [comment]
Indeed a dupe. @bfitzexpensify Let's close this one.
