### ISSUE TITLE
Able to proceed to step 3 regardless of whether the checkbox in step 1 is unchecked

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the Settings > Workspace > Connect bank account > Continue with setup
2. Go to the Step 1 of 5
3. Unchecked the checkbox and close the modal
4. Now again go to the Settings > Workspace > Continue with setup
5. You will proceed to step 3 even if the checkbox in step 1 is unchecked

## Expected Result:
If step 1 checkbox is unchecked it should not proceed to step 3
## Actual Result:
After clicking Continue with setup it proceeds to step 3 regardless of whether the checkbox in step 1 is unchecked

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1cd2e01a-705e-4572-8f7e-858ef32d1e55

https://github.com/Expensify/App/assets/43996225/115b7412-5fbe-4926-83dd-9f315ce20131

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683795675878369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Similar to this one (https://github.com/Expensify/App/issues/14107) and the team decided didn't fix it

**Comment by miljakljajic** [comment]
Agree with the reasoning in the previous issue - going to close.
