### ISSUE TITLE
[HOLD for payment 2023-05-25] Create a GH action for seeing if there are style errors in JS

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#18849]
# Problem
Even though Prettier runs as part of the build process, many people edit files without the build process running or without the prettier watcher running. If they don't manually run `npm run prettier`, then this introduces code with bad styles into our codebase.

# Solution
Create a GH action that will:
1. Be triggered anytime the branch is updated
1. Run `npm run prettier` on the branch
2. If a diff is produced, the action fails and tells the user they need to run `npm run prettier`

**Comment by tgolen** [comment]
I'm removing @miljakljajic since this is an internal issue that Andrew is going to do.

**Comment by roryabraham** [comment]
This has been done for a while.
