### ISSUE TITLE
[HOLD for payment 2023-05-25] [HOLD for payment 2023-05-23] [$1000] [Manual Requests] Update the report preview message to use workspaceName, not the admin name. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#18858]
👋 Quick clean up coming from [here](https://github.com/Expensify/App/pull/18486#issuecomment-1545359639). 

When you request money from a workspace, unlike IOUs, the report preview message of the expenseReport in the workspace chat should: 

1. Use the requestor's avatar, with the workspace avatar overlaid in the bottom right corner
2. Read: "%workspaceName% owes %expenseReportTotalAmount%. 

![image](https://github.com/Expensify/App/assets/16232057/b819982b-e042-4afa-8282-f4e7123a492d)

As a result of that linked PR, it will incorrectly reference the name and avatar of the admin, rather than the workspace. This is an important distinction for our EC3 deliverables. Thanks! 

CC: @bondydaa @Julesssss @JmillsExpensify
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d922e045b574dfd</li>
        <li>Upwork Job ID: 1657084791919509504</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@0xmiroslav are you going to work on this one still? If so, let's remove the `help wanted` label. 

It's pretty important to get a fix in for an event we have next week, so we appreciate the fast movement on this!

**Comment by jeet-dhandha** [comment]
Hello I am trying to resolve the issue but to get there first i have to get to this screen given in the screenshot.


I thought this screen comes up when i make `USER A` a part of my work space `WORKSPACE1` created by user `ADMIN-USER A` and then request money from `WORKSPACE1` but i didn't got any workspace in my list even if it shows that `USER A` us part of `WORKSPACE1` under `ADMIN-USER A`'s account.

So how do i go to the above given screen ?

**Comment by jeet-dhandha** [comment]
Contributor details
Your Expensify account email: jeet.dhandha.2511@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01921c050b587a3859

**Comment by trjExpensify** [comment]
>yes, I will work on this during weekend

Thanks, @0xmiroslav! 

@jeet-dhandha the workspace chats are behind a beta flag called `policyExpenseChat`.

**Comment by trjExpensify** [comment]
Nice, thanks for the update! ❤️ Will you be able to get that PR up today?

**Comment by trjExpensify** [comment]
Correct! It's the same for both.

**Comment by Julesssss** [comment]
Merged

**Comment by trjExpensify** [comment]
Adding you to the issue.

**Comment by trjExpensify** [comment]
Settled up with @0xmiroslav. @rushatgabhane let me know what you want me to do here and I'll send your offer.

**Comment by trjExpensify** [comment]
Poor, @tjferriss. 😅 

Excellent, offer sent. 👍
