### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] Disabled cursor briefly shows

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#18862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from https://github.com/Expensify/App/pull/18122#pullrequestreview-1419183889

## Action Performed:
Press on any PressableWithFeedback component.

## Expected Result:
We should not see a flash of the disabled-style cursor.

## Actual Result:
As shown [here](https://github.com/Expensify/App/pull/18122#issuecomment-1534299848), there is a flash of a disabled-style cursor.

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14-0
**Reproducible in staging?:** not yet 😉 
**Reproducible in production?:** not yet 😉 
**Issue reported by:** @hungvu193 
**Slack conversation:** n/a, came from GitHub

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c237b6717f70d48</li>
        <li>Upwork Job ID: 1657100067999002624</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
## Proposal
Don't show the none-select cursor until after a short delay. Hide it immediately if needed.

### Please re-state the problem that we are trying to solve in this issue.
It is expected behavior that:

    - When a PressableWithFeedback becomes disabled, then we show the none-select cursor.
    - When a PressableWithFeedback is pressed, it becomes disabled until onPress completes to prevent multiple repeated interactions.
    
However, when these things both happen in a very short time period, we see a flash of the non-select cursor and it looks janky.

### What is the root cause of that problem?
When a `PressableWithFeedback` becomes disabled, then we show the none-select cursor. Whenever `onPress` returns a Promise, we disable the `PressableWithFeedback` until that promise resolves. When the promise resolves quickly, we see a brief flash of the none-select style cursor.

### What changes do you think we should make in order to solve the problem?
To solve this problem, we should make a simple code change such that:

1. When a `PressableWithFeedback` goes from `!isDisabled` => `isDisabled`, we wait 1000ms before showing the none-select cursor. This will prevent an unsightly flash of the none-select cursor, but provide useful user feedback if the `PressableWithFeedback` is disabled for a longer period of time. I propose 1000ms because that's a reasonable amount of time for a user to wait before they might reasonably attempt to press the button again, after which time if the button is still disabled then the cursor style is helpful feedback.
1. When a `PressableWithFeedback` goes from `isDisabled` -> `!isDisabled`, then immediately hide the `none-select` cursor.
    - note: This does mean that if an `onPress` callback takes for example 1100ms, then we'll see a flash of the `none-select` cursor for 100ms. I think that's unlikely enough that we don't need to worry about it for now. As soon as the button is pressable we should re-enable it and not display the `none-select` cursor.

### What alternative solutions did you explore? (Optional)
We could ensure that, if the none-select cursor is shown, that it's shown for a minimum of say 250ms (or just long enough that it doesn't look janky). I guess I'm not opposed to that, but it's a bit more complex and maybe doesn't seem worth it. What do you think @s77rt?

**Comment by roryabraham** [comment]
Posting this proposal in the hopes that an external contributor will volunteer to implement it. Easy pickin's

**Comment by muttmuure** [comment]
out for 2 weeks

**Comment by roryabraham** [comment]
> We could ensure that, if the none-select cursor is shown, that it's shown for a minimum of say 250ms (or just long enough that it doesn't look janky)

@allroundexperts What's your opinion on this? Should we immediately re-enable the button or use a timeout to prevent a flash in all cases?

**Comment by roryabraham** [comment]
Ok, let's default to immediately re-enabling it 👍🏼

**Comment by roryabraham** [comment]
To clarify though, I am proposing that we use `setTimeout` to wait `1000ms` before showing the none-select cursor.

**Comment by roryabraham** [comment]
Yeah, I think this is a reasonable case to make an exception and use `setTimeout`.

**Comment by laurenreidexpensify** [comment]
@allroundexperts @s77rt offers sent in Upwork

**Comment by s77rt** [comment]
I don't think the checklist applies here. This is coming as a follow up for https://github.com/Expensify/App/pull/18122.

**Comment by laurenreidexpensify** [comment]
@s77rt @allroundexperts paid in upwork + 3 day merge bonus 

@hungvu193 can you accept offer for reporting bounty? 

Just need to pay @hungvu193 and then will close issue

**Comment by hungvu193** [comment]
Thanks @laurenreidexpensify , accepted!
