### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] DEV: Search items show weird undefined texts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open search page
2. Click on the items

## Expected Result:
 Search item should show display name and alternate text correctly

## Actual Result:
Empty display name and undefined alternate text, IOU reports disappear once opened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** DEV only
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/36fab705-b3eb-488a-b8a6-ce502597e3ea

https://github.com/Expensify/App/assets/43996225/14c24511-02f4-4bae-b69d-747bac628bf1

https://github.com/Expensify/App/assets/43996225/45a95516-5ae6-4336-9eee-b110ad34e56e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683816514449429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b54ea2f8c5c60bc1</li>
        <li>Upwork Job ID: 1658052636709498880</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@aimane-chnaif do you have a deeper idea of what's going on here? Also, is this something you want to take on? If we're opening this up external, I think we need to improve these steps. Presumably you need some iou/expenseReports etc? 

1. Open search page
2. Click on the items

**Comment by mountiny** [comment]
@dhairyasenjaliya I cannot repro in staging or locally, any idea to see what is special about these accounts?

**Comment by mountiny** [comment]
Thank you @dhairyasenjaliya Lets get this out fast 🔥 appreciate you stepping up

**Comment by mountiny** [comment]
Discussing this with @trjExpensify

**Comment by trjExpensify** [comment]
Good to go here, related discussion was in the PR and [here in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684158049679109).

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18537
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18537#issuecomment-1551379003
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1684329891045849
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment]
@MelvinBot Checklist provided already https://github.com/Expensify/App/issues/18860#issuecomment-1551394740

**Comment by JmillsExpensify** [comment]
@trjExpensify Can you take payment on this one? I'm headed out of office the rest of this week.

**Comment by trjExpensify** [comment]
Yup, back and looking at it now.

**Comment by trjExpensify** [comment]
Okay, so payments due: 

@aimane-chnaif - $250 for the bug report 
@dhairyasenjaliya - $1,500 for the fix & #urgency bonus 
@s77rt - $1,500 for C+ & #urgency bonus 

Offers have been sent, let me know when you accept and I'll settle up. 👍

**Comment by s77rt** [comment]
Accepted!

**Comment by trjExpensify** [comment]
Settled up with all three of you, closing. Thanks everyone!
