### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-25] Update LHN/Header for threads to be consistent with design doc

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#18863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Create a thread

## Expected Result:
header/lhn should look like this
<img width="802" alt="2023-05-12_13-21-23" src="https://github.com/Expensify/App/assets/42391420/fda11dc1-8498-4a04-9852-d80ece6297ce">

## Actual Result:
Header / lhn looks like this

<img width="800" alt="2023-05-12_13-21-10" src="https://github.com/Expensify/App/assets/42391420/b53077af-227a-40ed-8dbd-0fa1fca0311b">

## Workaround:
Usable, but bad UI

## Platforms:

Which of our officially supported platforms is this issue occurring on?
all

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6dfbcc4cfe1d0e3</li>
        <li>Upwork Job ID: 1663248548043726848</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
Sorry for the pings everyone, I should have made this internal from the beginning. @bfitzexpensify can we please pay the C+ $1000 (@rushatgabhane )

**Comment by bfitzexpensify** [comment]
Paid out and ended contract. Think we're all done here now, going to close this out.
