### ISSUE TITLE
Dev - iOS app crashes on magic code input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. logout if already logged in
2. Enter email
3. Double click any number on each magic code input

## Expected Result:
App doesn't crash

## Actual Result:
App crashes on 5th input

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.13-1
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/65bfef52-a641-473c-a418-d04cc7560383

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683872743466849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS app crashes on magic code input

### What is the root cause of that problem?

After enter full 6 numbers, set `focusedIndex` to `undefined` to blur the input:
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MagicCodeInput.js#L109

And this makes `editIndex` undefined when `Backspace` press event is unnecessarily called ([known bug](https://github.com/Expensify/App/issues/18218)) here:
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MagicCodeInput.js#L210

And this [effect](https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MagicCodeInput.js#L101-L114) is called again since it has `props.value` as a dependency

And finally crashes on this line:
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MagicCodeInput.js#L108

because `inputRefs.current[undefined] = undefined`

### What changes do you think we should make in order to solve the problem?

Add `_.isUndefined(editIndex) ||` condition in early return [condition](https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/MagicCodeInput.js#L105-L107)

**Comment by kadiealexander** [comment]
@situchan, I'm not able to reproduce this on the latest version (1.3.14-0)


https://github.com/Expensify/App/assets/59587260/eab326d5-4c08-4c62-8251-566d87308b02

Could you please test on the latest version of the app, and share updated reproduction steps if you're still running into it?

**Comment by situchan** [comment]
@kadiealexander as the title says, this happens only in developer mode and iOS 16.4 simulator. Not reproducible on staging/production.

**Comment by kadiealexander** [comment]
I can't get the keyboard to appear on my dev simulator. 

https://github.com/Expensify/App/assets/59587260/5950fa69-ea17-4076-8cfc-5f4255902434

Asking for someone else to test [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684302496961549).

**Comment by situchan** [comment]
@kadiealexander from your video, iOS version is 16.2 so not reproducible. Only happens on 16.4

**Comment by kadiealexander** [comment]
Adding the engineering label to get some help reproducing this one, my version of XCode doesn't allow for simulating iOS 16.4 :(

**Comment by kadiealexander** [comment]
@aldo-expensify could you please take a look and help me reproduce this in a iOS 16.4 simulator? I am having trouble with mine and don't want this to stay blocked on me.

**Comment by aldo-expensify** [comment]
I'm trying too, but I'm having problems with IOS in my dev environment at the moment :(

**Comment by aldo-expensify** [comment]
> @aldo-expensify could you please take a look and help me reproduce this in a iOS 16.4 simulator? I am having trouble with mine and don't want this to stay blocked on me.

I got my simulator working now. I was having this problem with my env: https://stackoverflow.com/questions/68565356/xcrun-error-sdk-iphoneos-cannot-be-located

 Posting in case it is useful for you.

**Comment by aldo-expensify** [comment]
@situchan I don't see an IOS 16.4 simulator in Xcode to test this. Are you using a simulator or a real device?

<img width="842" alt="image" src="https://github.com/Expensify/App/assets/87341702/27a727d1-7b36-48fd-bb04-b11b2ca500b8">

**Comment by situchan** [comment]
@aldo-expensify it seems you're still using old Xcode version.
My Xcode is v14.3

**Comment by aldo-expensify** [comment]
Is `My Xcode is v14.3` working fine now? Did you have to modify something to make it work? I remember I had to downgrade back to v14.2 some time ago to get the project working again.

**Comment by situchan** [comment]
This workaround works for me.

![image](https://github.com/Expensify/App/assets/108292595/96a31f6d-f92e-44d2-b5f9-18480308b8ad)

**Comment by aldo-expensify** [comment]
Thanks, I'll give that a try later 😬

**Comment by kadiealexander** [comment]
Have asked for help reproducing this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684816633930499).

**Comment by situchan** [comment]
Another person reproduced and uploaded video: https://github.com/Expensify/App/issues/18218#issuecomment-1558671564

**Comment by kadiealexander** [comment]
Thanks @situchan! Checking in that issue to see if this is a dupe.

**Comment by s77rt** [comment]
@situchan I see that the key to reproduce the bug is the unnecessary Backspace press event, so if that event didn't exist the issue won't be reproducible, is that the case? If so then we should hold on https://github.com/Expensify/App/issues/18218.

cc @kadiealexander

**Comment by situchan** [comment]
yes but fixing crash at least unblocks development and testing on iOS simulator which is @tgolen's [concern](https://github.com/Expensify/App/issues/18218#issuecomment-1544271484).
After that, https://github.com/Expensify/App/issues/18218 may exist longer.

**Comment by s77rt** [comment]
Good point but we don't have to test on iOS 16.4. You can still test using other iOS versions.

**Comment by aldo-expensify** [comment]
Good point @s77rt , and https://github.com/Expensify/App/issues/18218 looks a lot more annoying than this one, and this one should get resolved once we get https://github.com/Expensify/App/issues/18218 fixed.

Closing as duplicate.

**Comment by s77rt** [comment]
@aimane-chnaif Seems working fine from my end. Please double check your pod and project files against these changes https://github.com/Expensify/App/pull/21316/files

https://github.com/Expensify/App/assets/16493223/effe4867-17cf-4908-a758-0c0be1d1887f

**Comment by BeeMargarida** [comment]
> > @aimane-chnaif Double checked right now, I ran `npm run clean` and installed the pods, everything is working correctly.
> 
> Did you run build using command or from Xcode? I used Xcode

Using `npm run ios`
