### ISSUE TITLE
[HOLD for payment 2023-05-25] Clean up Inline Thread Replies Styles (+ handle mobile/small screen sizes)

### ISSUE THREAD

**Issue by grgia** [Expensify/App#18872]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161e0b6f884ecc108</li>
        <li>Upwork Job ID: 1657133399576674304</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

Coming from this comment: https://github.com/Expensify/App/pull/18274#issuecomment-1545930894

On this PR:  https://github.com/Expensify/App/pull/18274 
<img width="400" alt="image" src="https://github.com/Expensify/App/assets/38015950/8d30c0fa-e1bb-442f-9c0f-0dc74ab0768c">

Better mock up:
<img src="https://github.com/Expensify/App/assets/38015950/3cd39bd3-3eab-4bd2-931b-e83e71892bc1" width="400"> 

To do:
- [ ] Handle date for long comments (this should match the date with any normal comment though)
- [ ] Make avatars 28 x 28 
- [ ] Cap number of replies at `99+`
- [ ] Make "Last Reply" -> "Last reply"
- [ ] ...

cc @shawnborton sorry for the double ping on this, moving to it's own issue!

**Comment by grgia** [comment]
@shawnborton happy to fix any and all of the UI things !!!! Hit me with them

relevant:
https://github.com/Expensify/App/pull/18274#issuecomment-1546297408
 https://github.com/Expensify/App/pull/18274#issuecomment-1546307788

**Comment by shawnborton** [comment]
Nice! Let's start with what I have above. 28x28 avatars, overlapping at -4px, with a 2px outer border.

**Comment by grgia** [comment]
<img width="418" alt="image" src="https://github.com/Expensify/App/assets/38015950/42681f6f-7229-4191-bbdc-08f7473e9cf4">
Right now, the border width for this component (multiple avatars) is set to 3px for 28x28, should I change it everywhere to 2px or leave as 3px (pictured)

**Comment by grgia** [comment]
And here's the 99+ preview:
<img width="414" alt="image" src="https://github.com/Expensify/App/assets/38015950/4e36b2e5-c09a-4e6e-bc17-cf201740b31f">

**Comment by shawnborton** [comment]
I say change it globally. And just confirming that the border goes to the
outside?

**Comment by grgia** [comment]
Yep, here's with 2px: 

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/38015950/90e4d4a2-e5c8-4df8-9a64-291f5e89db29">

What is the best path forward for the dates on small screen? On tiny screens it gets a little precarious even if I remove the timestamp from the date. 

<img width="858" alt="image" src="https://github.com/Expensify/App/assets/38015950/9e4b40a4-b6dc-4a3a-95c6-189d883dcb6b">

Although for Today/Yesterday it doesn't provide as much info as chat headers do:
<img width="858" alt="image" src="https://github.com/Expensify/App/assets/38015950/36bd780d-d41b-4a52-ae67-68389c9d0f81">

But leaving timestamps results in:
<img width="858" alt="image" src="https://github.com/Expensify/App/assets/38015950/3590c89b-41a4-47e6-8350-d32da03608ff">

**Comment by grgia** [comment]
@shawnborton any thoughts on the small screen overflow problem (with 4+ participants) ?

https://github.com/Expensify/App/issues/18872#issuecomment-1546409428
some options here, but I'm not sure that the best solution is in there

**Comment by grgia** [comment]
@zanyrenney could you help with C+ internal review payment for this issue (already merged https://github.com/Expensify/App/pull/18876)?

**Comment by zanyrenney** [comment]
Sure, @grgia i have DM'd you as i'm just getting assigned now and more detail would be super helpful please.

**Comment by zanyrenney** [comment]
sent invite to you @aimane-chnaif

**Comment by zanyrenney** [comment]
Going OOO and this is pretty active so needs management by bug0 team member, as per the [new process ](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799)to stay assigned but assign another team member, please can you keep a watch of this. I am OOO until 8th June. Thanks!

**Comment by mallenexpensify** [comment]
Thanks @grgia for the ping. 
@aimane-chnaif , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0161e0b6f884ecc108

**Comment by mallenexpensify** [comment]
@aimane-chnaif paid $1000
This is a small design-related improvement so there shouldn't be a PR that 'caused' the bug nor test case steps that need to be added
