### ISSUE TITLE
Can't scroll on a PDF attachment uploaded using mouse scroll wheel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and upload a PDF with multiple pages
2. Open the PDF after it is done uploading
3. Notice there is a scroll bar on the right and can scroll down using the scroll bar or the down arrow keyboard
4. Try to scroll down using the mouse scroll wheel
5. Hold down on the mouse scroll wheel and glide down and notice it works

## Expected Result:
Scrolling using the mouse scroll wheel should work just as holding down the scroll wheel and gliding down works

## Actual Result:
Using the mouse scroll wheel to scroll down is not allowed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.13-0
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ce62c1c5-b2ad-4795-84bb-fd48a6fde9de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683882074433819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Tested on v1.3.13-5 and I don't think this is an issue anymore.

Scrolling with a mouse is maybe slightly slower than the scroll bar, but it does work. Closing, please re-open if you can reproduce on another device or platform!
