### ISSUE TITLE
[HOLD for payment 2023-06-01] [Regression Hold] The tooltip is not aligned with the arrow if the arrow position is at right edge of the tooltip.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Search page, try to hover the three dot of any chat group that has many member.
2. Notice that there's a space between arrow and the tooltip.

## Expected Result:
Tooltip should be positioned above the arrow

## Actual Result:
The tooltip is not aligned with the arrow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e3080eb9-eb27-4e7f-853c-6ce47d10a482

<img width="960" alt="ffd" src="https://github.com/Expensify/App/assets/43996225/de42f40e-bf78-4cd2-8696-6527523231d4">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683863552205729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
I am unable to recreate this any longer, I created a group with at least 8 individuals as in the Slack thread and still no luck. 

@fedirjh @kavimuru, are you both still able to recreate this? I wonder if we fixed this elsewhere?

**Comment by bernhardoj** [comment]
As this is a regression from my [PR](https://github.com/Expensify/App/pull/18189), I think I should take care of the issue? If yes, I will open the PR to fix the regression.

**Comment by strepanier03** [comment]
@fedirjh -- aaaahaa, I see. I thought that the below was the bug, where it's really not lined up.

<img width="460" alt="2023-05-16_13-49-42" src="https://github.com/Expensify/App/assets/10925636/7f477c3f-2c6e-4b70-8bd8-79fbd8d7c1f6">

**Comment by strepanier03** [comment]
I need to figure out the proper labels to apply here so that this is treated properly since it's a regression @bernhardoj is going to take care of. Will do that as soon as I confirm.

**Comment by bernhardoj** [comment]
Yes, that is correct @strepanier03

**Comment by bernhardoj** [comment]
I have open a PR to handle this regression https://github.com/Expensify/App/pull/19097.

**Comment by strepanier03** [comment]
Weird assignment behavior today, sorry about that everyone.

**Comment by strepanier03** [comment]
@fedirjh - I've hired you to a reporting job for this, please accept when you can and I'll pay out.
