### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Padding above “no result found” error in message input “Emoji- Search bar” is not consistent.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open “Chats”
2. Click “Emoji”.
3. Search an invalid Emoji, so that “no result found” error appear.
4. Observe that the bottom padding of the input field is 8px 16px.
5. Please note that all below search bar reflects padding of 0px 20px 12px on search of an invalid item.
Search bar next to chats.
Send money- select a currency.
Profile- Pronouns
Profile- Timezone
DOB-Year

## Expected Result: 
Padding for the error “No result found” should be consistent among pages.

## Actual Result: 
Padding for the error “No result found” is not consistent among pages.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![1 (1)](https://github.com/Expensify/App/assets/43996225/3efc8944-5e9b-42a1-837a-4e083a74e642)
![2 (1)](https://github.com/Expensify/App/assets/43996225/e1e4bc0a-3a5a-42cc-94cf-a48ebbb9ad98)
<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/5e660750-c3f9-4d4d-acfb-95398647cd87">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684009587168949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01399c717b42532302</li>
        <li>Upwork Job ID: 1658488402800201728</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
be patient Melv, proposals will be reviewed soon.

**Comment by Santhosh-Sellavel** [comment]
@Expensify/design Which is correct where should we change?

**Comment by shawnborton** [comment]
Hmm I think I like 8px better?

**Comment by shawnborton** [comment]
Got it, let's stick with 12 then and just adjust the emoji picker

**Comment by shawnborton** [comment]
Sure, that works for me too.

**Comment by dukenv0307** [comment]
I also agree that we should update all padding below the search input to 12px because there are only 2 places (Emoji Search and Manage Member Page) that are different as I mentioned in [my proposal](https://github.com/Expensify/App/issues/18909#issuecomment-1550117421)

**Comment by Santhosh-Sellavel** [comment]
@dukenv0307 What can you update your proposal with what do with changes (code) as we have the desired outcome now? Thanks!

**Comment by Santhosh-Sellavel** [comment]
Yeah, I saw that. I'm just waiting for @dukenv0307's to make call here

**Comment by dukenv0307** [comment]
@Santhosh-Sellavel Thanks. I jus updated [proposal](https://github.com/Expensify/App/issues/18909#issuecomment-1550117421)

**Comment by cristipaval** [comment]
@Santhosh-Sellavel will continue reviewing

**Comment by Santhosh-Sellavel** [comment]
Discussing this internally!

**Comment by Santhosh-Sellavel** [comment]
Thanks for the proposals @dhairyasenjaliya @dukenv0307

This is pretty much straightforward once we decide on the outcome. As we see @dukenv0307 proposal is an anchoring point for the discussion, we appreciate your help here @dhairyasenjaliya. But we think @dukenv0307 is slightly better with other optional improvements as well for consistency. So we decide to go with them here.

@dukenv0307 Regarding your optional suggestion. We have to wait for @shawnborton or @Expensify/design's input here. 
Once you are assigned get started with other items on PR. Regarding the optional. Please include before & after screenshots for the optional suggestions in a comment. After the design team's input, we can decide what to implement thanks!

cc: @cristipaval

**Comment by dukenv0307** [comment]
@Santhosh-Sellavel I update screenshots for optional

- Before screenshots

![Screenshot from 2023-05-25 10-43-25](https://github.com/Expensify/App/assets/129500732/0ae20498-d1d3-4a4e-9135-840d62b2e397)

![Screenshot from 2023-05-25 10-45-33](https://github.com/Expensify/App/assets/129500732/a14e9dee-545e-442f-8a33-6672bc0e56bf)

![Screenshot from 2023-05-25 10-45-26](https://github.com/Expensify/App/assets/129500732/ced26abe-b513-4652-addd-35729bf000b7)

![Screenshot from 2023-05-25 10-45-02](https://github.com/Expensify/App/assets/129500732/52d40d47-0cdc-436d-9417-f4ad51332321)


- After screenshots

![Screenshot from 2023-05-25 10-41-53](https://github.com/Expensify/App/assets/129500732/729ab4ca-155f-4170-a2fa-08c6494f921c)

![Screenshot from 2023-05-25 10-49-45](https://github.com/Expensify/App/assets/129500732/8f0dbb13-0c69-4972-be61-9c904db38301)

![Screenshot from 2023-05-25 10-49-35](https://github.com/Expensify/App/assets/129500732/d4790dc3-a693-4780-a176-3bbebac2521f)

![Screenshot from 2023-05-25 10-49-21](https://github.com/Expensify/App/assets/129500732/f148dfd3-a547-4b0d-a8cc-34bd6d4be9ac)

**Comment by cristipaval** [comment]
@shawnborton is back but I guess today he is swamped with many pending things as he missed last week.

**Comment by shawnborton** [comment]
The emoji popover is a smaller piece of UI, so I think we should keep the padding at 16px around the content instead of 20. 

As for the space between the search box and the message, I thought we agreed to use 12?

**Comment by cristipaval** [comment]
You're all set @dukenv0307 
cc @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: N/A
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@slafortune] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@cristipaval This is not a regression, styles were intentionally added. I think this is a small UI polish, IMO no need for regression tests as well, let me know your thoughts thanks!

**Comment by slafortune** [comment]
Offers sent to @dukenv0307 @Santhosh-Sellavel and @usmantariq96.

**Comment by usmantariq96** [comment]
@slafortune applied with thanks

**Comment by slafortune** [comment]
Accidentally invited the wrong person - correct that now @Santhosh-Sellavel ! - offer sent.

**Comment by Santhosh-Sellavel** [comment]
Accepted thanks!

**Comment by slafortune** [comment]
All paid 🎉
