### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] Blue bottom border seperator among currencies is not pressent.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open “Actions”
2. Open “Request money”
3. Click “Select a Currency”.
4. Observe there is no separator among currencies.
5. Open “Settings”
6. Open “Profile”
7. Open “Pronouns”.
8. Open “Settings”
9. Open “Profile”
10. Open “Timezone”.

## Expected Result: 
Separator among currencies should be present like Pronouns or Timezone.

## Actual Result: 
Seperator among currencies is not pressent like Pronouns or Timezone.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2133e63d-74bb-4b70-b9c1-93f9eeacff72

<img width="957" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/e10348d7-f7f8-4aa2-a15f-3279390c6ad7">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684006680335189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142b4e1af1a58a18d</li>
        <li>Upwork Job ID: 1658261573115326464</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Offers sent in upwork @dhairyasenjaliya @s77rt @usmantariq96

**Comment by usmantariq96** [comment]
Offer accepted
Thanks

**Comment by kevinksullivan** [comment]
Hi @s77rt please complete the steps above and I'll get this paid out next week assuming no regressions!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: No PR to blame. The currency page  was implemented on May 2021 ([PR](https://github.com/Expensify/App/pull/2194)) and at that time we didn't even have the option to add a separator. The separator feature was added later on Nov 2022 ([PR](https://github.com/Expensify/App/pull/12301)).
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: Not a bug. This is a feature request.
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment]
@kevinksullivan Done!

**Comment by kevinksullivan** [comment]
Thanks for the quick turnaround @s77rt !

**Comment by kevinksullivan** [comment]
Paid everyone. @usmantariq96 I paid you for reporting, but upwork is bugging again and I can't close the contract. I'll try again tomorrow to wrap this up.

<img width="1342" alt="image" src="https://github.com/Expensify/App/assets/22508290/50fc6836-a1b5-417d-8397-94520750eb36">

**Comment by kevinksullivan** [comment]
All set @usmantariq96
