### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Workspace settings page can be opened by any non-admin member of the workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login as user A and create a workspace.
2. Add user B as a member to the workspace.
3. Go to Workspace General Settings and copy the URL for the workspace.
4. Login as user B and open the link you copied previously.

## Expected Result: 
Not found or Permission denied error should be shown
## Actual Result: 
The workspace settings page open and allows the user to see / interact with all the forms.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2c34f9ae-8df6-4e2f-ac43-23ceff65a385

https://github.com/Expensify/App/assets/43996225/7429bc49-08f0-4e3c-926a-fa50f8f7729c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684016823040309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a823356a32c5600</li>
        <li>Upwork Job ID: 1659230141558759424</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
will triage tomorrow

**Comment by sonialiap** [comment]
https://staging.new.expensify.com/workspace/90F7140C34753F91/settings

I can confirm the behavior

1. Login as user A and create a workspace.
2. Add user B as a member to the workspace.
3. Go to workspace settings and copy the URL for the workspace 
4. Login as user B and open the link you copied previously

**Expected result:** a member of the workspace that is not an admin should not be able to access that workspace's settings
**Actual result:** following the URL copied and shared by user A allows user B to access A's workspace settings (but doesn't seem to allow B to change anything)

**Comment by sonialiap** [comment]
@allroundexperts what do you think of instead of throwing an error, redirecting user B to new.expensify.com?

**Comment by victornnaji** [comment]
We can redirect the user to another page. I think, it's good solution.

**Comment by LiaKim07** [comment]
Contributor details
Your Expensify account email: kimdubu07lia@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018b24d677a862774a

**Comment by LiaKim07** [comment]
I think, we can simply redirecting to the new.expensify.com.

**Comment by mananjadhav** [comment]
@sonialiap @yuwenmemon can we confirm the expected result here?

1. Redirect them to the Workspace page/chat page
2. Redirect to Concierge/New Expensify.com (essentially redirecting to the root URL from point 1)
3. Show Page not found error as below.


<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/3069065/aa2243f5-1063-4cad-971a-d47ce528dedb">

**Comment by sonialiap** [comment]
Bringing it up with the team in slack

**Comment by victornnaji** [comment]
Contributor details
Your Expensify account email: nnajivictorr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01502d8d0d1c9927a7?viewMode=1

**Comment by victornnaji** [comment]
Contributor details
Your Expensify account email: [nnajivictorr@gmail.com](mailto:nnajivictorr@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01502d8d0d1c9927a7?viewMode=1

**Comment by sonialiap** [comment]
Let's go with solution #3 - the error message

However, let's specify what's wrong in the error message. Being specific will both help the user resolve their issue on their own without having to reach out to support, and if they do reach out, support will have more info on what's wrong to help the user.

Suggestion for what the error could be:

> Hmm... it's not here
> You do not have access to this page. Are you trying to join the workspace? Please reach out to the owner of this workspace so they can add you as a member!

Though my suggestion assumes the user isn't a member of the workspace, it is possible that the user is a member and the owner is trying to give them access to the workspace settings or add them to a chat 🤔

**Comment by mananjadhav** [comment]
@sonialiap. Thanks for the content. Can you also share the content in spanish?

and now we're open for proposals. Request to contributors instead of updating existing proposals, let's put in fresh comments to avoid any confusions.

**Comment by AyoubMoujane** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace settings page is visible even if the user is not admin

### What is the root cause of that problem?

No checks are done to cover this scenario, in `WorkspaceInitialPage.js` an error wrapper only covers the `NotFound` scenario

```javascript
<FullPageNotFoundView
     shouldShow={_.isEmpty(policy)}
     onBackButtonPress={() => Navigation.navigate(ROUTES.SETTINGS_WORKSPACES)}
                >
... Page code
<FullPageNotFoundView/>
```

### What changes do you think we should make in order to solve the problem?

I would suggest the following steps:

1. creating a new error wrapper for the unauthorised case `<FullPageNotFoundView>`, so this component has it's own translation logic, it's own component image, ...etc. It's easier to maintain like that
2. create a more generic wrapper to compose the different error wrappers, it's better so in the future it will be easier to handle a new error scenario.

Generic error wrapper

```javascript

import React from 'react';
import FullPageNotFoundView from './FullPageNotFoundView';
import FullPageUnauthorizedView from './FullPageUnauthorizedView';
import * as Policy from '../../libs/actions/Policy';

const FullPageErrorWrapperView = ({ policy, onBackButtonPress, children }) => {
    const isNotFoundError = _.isEmpty(policy)
    const isUnauthorized = !Policy.isAdminOfFreePolicy([policy])

    if (isUnauthorized) {
      return <FullPageUnauthorizedView 
      shouldShow={true}
      onBackButtonPress={onBackButtonPress} 
      />;
    } else if(isNotFoundError){
      return <FullPageNotFoundView 
      shouldShow={true}
      onBackButtonPress={onBackButtonPress} 
      />;
    }

  return children
};

export default FullPageErrorWrapperView;

```
4. Use the generic wrapper in the component 

```javascript              
 <FullPageErrorWrapperView
       policy={policy}
       onBackButtonPress={() => Navigation.navigate(ROUTES.SETTINGS_WORKSPACES)}
                >`
... Page code
<FullPageErrorWrapperView/>
```
Looks like that locally

https://github.com/Expensify/App/assets/50808670/c7eadc54-afc3-4f7c-b0e8-5325d4572d2b

### What alternative solutions did you explore? (Optional)

N/A

**Comment by sonialiap** [comment]
@mananjadhav what do you think of the current proposals?

**Comment by mananjadhav** [comment]
While both the proposals have correct RCA and both the solutions will work, I think I'll choose @allroundexperts's [proposal](https://github.com/Expensify/App/issues/18910#issuecomment-1565496510) in this case.

I feel adding another component for Unauthorized case would be an overkill, especially because `shouldShow` is in fact to serve this generic case.

@yuwenmemon what do you think?

**Comment by mananjadhav** [comment]
I agree we don't explicitly handle Unauthorized scenario, but I think it doesn't warrant for a change, when we're again just hiding and having a fallback. Nevertheless, I'll let @yuwenmemon decide. Thank you for the patience here.

**Comment by yuwenmemon** [comment]
Agreed with

> I feel adding another component for Unauthorized case would be an overkill, especially because shouldShow is in fact to serve this generic case.

So will go with @allroundexperts for this one!

**Comment by mananjadhav** [comment]
Please allow me a day to review and test this. I am unwell and would be offline most of the day.

**Comment by sonialiap** [comment]
@allroundexperts @mananjadhav looks like the fix went through without any regressions 🎉 please complete the [checklist](https://github.com/Expensify/App/issues/18910#issuecomment-1588264005) and I'll issue payment

**Comment by mananjadhav** [comment]
@sonialiap @yuwenmemon I couldn't exactly pinpoint which PR should we tag here for offending PR? The Workspace settings page exist since Workspace module, and the related pages have gone through multiple refactors.

I don't see any need to update on the checklist, but I do think we should use the Tests from the PR as a regression suite. Because it isn't just settings page that we added the check too, but also other workspace pages.

**Comment by mananjadhav** [comment]
@sonialiap Quick bump on the payout for this one.

**Comment by sonialiap** [comment]
Thanks for the checklist review, I'll add the issue steps as a regression test.

Offers sent to @mananjadhav and @allroundexperts

**Comment by mananjadhav** [comment]
Thanks @sonialiap. I would also like to highlight that this is also eligible for the timeline bonus.

**Comment by sonialiap** [comment]
I was just opening the PR to review the timeline. You are well within the 3 days. Will add the bonus to both offers during payment 😁

**Comment by sonialiap** [comment]
Both paid ✅ 
Sibtain: reporting and fix + bonus
Manan: review + bonus
