### ISSUE TITLE
 Inconsistent emoji behavior when editing messages with multiple emojis

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat.
2. Write a text.
3. Add four emojis.
4. Add a new text.
## Expected results: 
All four emojis should remain in the message.
## Actual results: 
Only one emoji remains in the message, and the other three emojis are removed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** Mustapha Amin Dhouib
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683882632498589
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
However, I'm unable to reproduce. 

all four of my reaction emoji's stayed
<img width="599" alt="Screenshot 2023-05-15 at 10 48 07 AM" src="https://github.com/Expensify/App/assets/11966460/5406fc48-c6db-47fd-8cf4-e6af18f605c1">

I applied the emoji's differently for each one. 

using each option: 
<img width="497" alt="Screenshot 2023-05-15 at 10 50 00 AM" src="https://github.com/Expensify/App/assets/11966460/05f4dfc1-db79-4c99-9785-55fedc19bed7">
<img width="771" alt="Screenshot 2023-05-15 at 10 50 33 AM" src="https://github.com/Expensify/App/assets/11966460/3dc3594a-78bf-4756-806b-731cad070a38">

Both times all four emoji's remained
