### ISSUE TITLE
Add payment method button either has hover effect on or disabled for brief moment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18917]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open settings
2. Go to payments
3. Observe the Add payment method button

## Expected Result:
button shouldn't take time to load properly like other buttons all over the app

## Actual Result:
 button either has hover effect on or disabled for first few seconds

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d25655e9-b5a7-4ecf-ad55-f3db76828f51

https://github.com/Expensify/App/assets/43996225/4fd87af0-d7f0-45d5-8982-22033da09e42

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683822391188429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
I think we should close the issue as it's [dupe](https://github.com/Expensify/App/issues/14681)

**Comment by strepanier03** [comment]
Closing per https://github.com/Expensify/App/issues/14681 and recommendation. We decided not to fix the issue in the dupe.
