### ISSUE TITLE
The default recommendation address in zipcode for Caroline Street, Canada throws an error for most of the addresses while works for the same address for US

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to web chrome > settings > personal information > address
2. First Type in: Caroline street USA and select addresses that has default zipcode on it and notice that it doesn't throw an error for the same caroline street address
3. But now type in caroline street Canada and select few addresses and notice that the default recommendation address throws an error for the same street for Canada in the zipcode field
4. It doesn't happens with the same street addresses for US with their default zipcode, but throws an error in the zipcode ,if caroline street Canada is set in the address field

## Expected Result:
The default recommendation address for Caroline Street, Canada should not throw an error for most of the addresses related to caroline street Canada in a similar how setting caroline street US doesn't throw an error
## Actual Result:
The default recommendation address for Caroline Street, Canada throws an error for most of the addresses unlike the same street address for US

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/439c270b-773d-4e0c-a9b8-5d80bbfc7ac5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683708639967419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment]
I'll look into this tomorrow

**Comment by flaviadefaria** [comment]
Posted discussion in #bug-zero [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684332698457999).

**Comment by flaviadefaria** [comment]
Got a buddy check in Slack and we agreed this is not something that needs to be fixed.
