### ISSUE TITLE
On opening connect bank account first time after login, app displays 'Almost done' screen first then displays loading and again displays 'Almost done' screen giving glitched UX to user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18923]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. If logged in then log out
3. Log in with any user
4. Open settings
5. Open workspaces
6. Open any workspace
7. Open connect bank account and observe how it loads
8. get back and open connect bank account again and observe how it loads

## Expected Result: 
App should display loading animation first and then display 'Almost done' page as it normally does on loading connect bank account
## Actual Result:
On opening connect bank account first time after login, it loads 'Almost done' page first, then displays loading animation and then again displays 'Almost done' page giving gitched UX

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/798ab9d2-d624-446d-a683-e8c7715f6a74

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683630633030249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Confirmed, not a bug.
