### ISSUE TITLE
[HOLD for payment 2023-05-25] QR code share polish issues

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

3 bugs:

## Action Performed:

Go to settings >Share code

## Expected Result:
should not show any Console error

____

## Action Performed:
1. Go to settings >Profile >Display name
1. type long first and last name
1. Go to settings >Share code
1. check the name in Share code

## Expected Result:
Name cuts both side

## Actual Result:
Name should not cut

____

## Action Performed:
1. Login ND
1. Open Settings

## Expected Result
It is centered

## Actual Result:
It's not

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg @gadhiyamanan twice
**Slack conversation:**

https://expensify.slack.com/archives/C049HHMV9SM/p1684148520784279
https://expensify.slack.com/archives/C049HHMV9SM/p1684146498776949
https://expensify.slack.com/archives/C049HHMV9SM/p1684146466609189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@chrispader

**Comment by chrispader** [comment]
heyoo github 👋🏼

**Comment by robertjchen** [comment]
Got some feedback from Design as well, should be an easy text color tweak. Let me know if I can help! 👍  https://github.com/Expensify/App/issues/18080#issuecomment-1548179869

**Comment by chrispader** [comment]
@mountiny @robertjchen [the PR](https://github.com/Expensify/App/pull/18946) is ready for review!

**Comment by kevinksullivan** [comment]
@mountiny was this an external issue? It seems like yes, and we'll pay out @chrispader for the PR?

**Comment by mountiny** [comment]
@kevinksullivan Chris is from Margelo agency so they will handle payments differently

we just need to pay @aman-atg and @gadhiyamanan for reporting the bugs I believe. I think it would be $250 each

**Comment by gadhiyamanan** [comment]
@kevinksullivan i think offer should be $500 to report two different($250 for each) bugs

**Comment by kevinksullivan** [comment]
@mountiny maybe I misunderstood your input here? Both @gadhiyamanan and @aman-atg  should be paid for reporting two individual bugs?

**Comment by mountiny** [comment]
@kevinksullivan sorry its a bit unclear, I have combined 3 reports to this issue as they were all connected and related to one feature added and the original author fixed them all in one PR.

so we got:
- $250 to @aman-atg 
- $500 to @gadhiyamanan for 2 reports.

**Comment by kevinksullivan** [comment]
@gadhiyamanan can you accept the offer? I'll add $250 to it.

**Comment by kevinksullivan** [comment]
Paid @aman-atg

**Comment by gadhiyamanan** [comment]
@kevinksullivan accepted, thanks!

**Comment by kevinksullivan** [comment]
Paid @gadhiyamanan . Now upwork is giving me the "modal of death" where I can't continue finishing up the contract 🙃 . I'll come back around to closing out the contract.

<img width="1342" alt="image" src="https://github.com/Expensify/App/assets/22508290/63d8127a-af62-4d95-b461-bb1b9cd11c2c">

**Comment by mountiny** [comment]
This is being handled
