### ISSUE TITLE
Request Money - Every RM creates a second chat with own account.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create two accounts, A and B.
2. Make sure both personal policies are set to USD in OldDot (Policy>Report>Currency)
4. Sign into both accounts in NewDot (one on one platform and the other on another platform)
5. Request money from A to B.

## Expected Result:
Request money should be created and only one chat should be appeared.

## Actual Result:
Every RM creates a second chat with own account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ea30f831-a8f9-4db1-98b1-537ad84289b4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is the expected behavior now.

**Comment by yuwenmemon** [comment]
@luacmartins Does this mean this is safe to close out?

**Comment by luacmartins** [comment]
Yes, but I think that we need to update tests in TestRail

**Comment by yuwenmemon** [comment]
Gotcha, okay will bump this down to Daily regardless then

**Comment by tylerkaraszewski** [comment]
How do we update tests in testrail? Do we do this or does Applause do this?

**Comment by tylerkaraszewski** [comment]
Issue to update testrail added here: https://github.com/Expensify/Expensify/issues/287759

**Comment by tylerkaraszewski** [comment]
Waiting on applause for the issue above.

**Comment by luacmartins** [comment]
We already created an issue to add the test to TestRail. I think we can close this one.
