### ISSUE TITLE
LHN - Green dots are displayed after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Open expensifail account: [applausetester+0212lsn@applause.expensifail.com](mailto:applausetester+0212lsn@applause.expensifail.com)
3. Click on each conversation with a green dot to open them all.
4. Refresh the page.

## Expected Result:
The green dots should not be displayed after refreshing the page, 

## Actual Result:
Green dots are displayed after refreshing the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** [applausetester+0212lsn@applause.expensifail.com](mailto:applausetester+0212lsn@applause.expensifail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/93b7b514-81ba-4257-bc00-bb294edb2cf2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@mountiny @luacmartins this is down to the PRs for moving iou actions to the iou/expense reports not being completed yet, right? 

I think we can close this, as it's a consequence of being mid-implementation. Let me know if you agree!

**Comment by luacmartins** [comment]
Yea, we can close this.
