### ISSUE TITLE
[$1000] IOU preview is broken in workspace chat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#18989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A, account B (on another device) with policyExpenseChat beta
2. On A, invite B to any workspace
3. On B, send money request in workspace chat

## Expected Result:
On A, show Pay button and title should be "Cash" in IOU preview

## Actual Result:
No Pay button and title is "Split"

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13-5
**Reproducible in staging?:** No (needs repro)
**Reproducible in production?:** No (needs repro)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![bug](https://github.com/Expensify/App/assets/43995119/5a3a6607-4535-4169-bc3c-a7bfc3fff17e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684093965641869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172070b3426d60c86</li>
        <li>Upwork Job ID: 1658585138463666176</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Closing per team discussion
