### ISSUE TITLE
[$1000] Web - Workspace -All Workspaces highlighted in blue color when clicking the back arrow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to Settings -> Workspaces.
3. Click on New Workspace 3 and more times
4. Click back arrow

## Expected Result:
Workspaces are not highlighted.

## Actual Result:
If user click on New Workspace 3 and more times quickly then by clicking the back arrow everything is highlighted in blue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/782762e7-1417-4f76-8efd-de954db4810a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f68ed4e88bdc4aeb</li>
        <li>Upwork Job ID: 1658903229124943872</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by abekkala** [comment]
I applied external label this morning but there were GH issues.

**Comment by kushu7** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
All workspaces are getting selected.
### What is the root cause of that problem?
Its not a bug as title is selectable. so its getting selected when we double triple mouse button. its default behavior in web browser.
### What changes do you think we should make in order to solve the problem?

Still we want to Fix this then we can add noSelect style to title here https://github.com/expensify/App/blob/main/src/pages/workspace/WorkspacesListPage.js#L168
```js
<MenuItem
    {..other props}
    iconStyles={item.iconStyles}
    titleStyle={styles.noSelect}
    {..other props}  
/>
```
and in styles we have to add extraProperty to noSelect
```
 noSelect: {
        boxShadow: 'none',
        outline: 'none',
        userSelect: 'none'  <-- THIS ONE
    },
```


### What alternative solutions did you explore? (Optional)

None

**Comment by abekkala** [comment]
@Gonals and I have discussed this 
This doesn't seem like something necessary to fix however, if we do decide to proceed with the proposed fix is it known if that fix would then prevent the ability to copy the name of the workspace to the clipboard?
