### ISSUE TITLE
Text mixup when you press F12 and reload page till next click 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Chrome
2. Goto [New.Expensify.com](http://new.expensify.com/)
3. Press F12
4. Reload page by any method

## Expected Result:
Text field should be same

## Actual Result:
Text field mixup

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y  
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/21179ad3-3c2a-4c81-add4-327e28d49937

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @corange-lab
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684137627963199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
agreed, closing
