### ISSUE TITLE
[HOLD for payment 2023-05-25] [HOLD for payment 2023-05-23] senders avatar and name are missing on create new chat and send message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. click on + button
2. select new chat option
3. type email id with whom you don’t have any chat history
4. go to chat
5. send message

## Expected Result: 
senders avatar and name are missing
## Actual Result: 
should show senders avatar and name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.14-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ff5c7366-6a71-48ed-ad40-97f3ca316b8e

<img width="960" alt="5" src="https://github.com/Expensify/App/assets/43996225/3a27262b-46b3-4b6f-8428-0e1d034140df">

https://github.com/Expensify/App/assets/93399543/a11e1225-b154-4422-8c1d-79c24124d33d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan and Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684141166139909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
Thank you for taking care of this guys!

**Comment by arosiclair** [comment]
I don't think any additional regression tests are needed since Applause caught this

**Comment by stephanieelliott** [comment]
I'll had to create an Upwork job manually for payment on this: https://www.upwork.com/jobs/~01d55baf443fdbd072

Seems like @0xmiroslav was C and @rushatgabhane are C+, yeah?

**Comment by gadhiyamanan** [comment]
@stephanieelliott reporting bonus is pending

**Comment by stephanieelliott** [comment]
@0xmiroslav you're been paid! 

@gadhiyamanan and @rushatgabhane I have pending offers for you two, please accept the job on Upwork and I will pay out ASAP. Thanks!

**Comment by gadhiyamanan** [comment]
@stephanieelliott accepted, thanks!

**Comment by stephanieelliott** [comment]
Everyone has been paid! Thank you
