### ISSUE TITLE
Console error appears when pressing enter by not selecting suggested mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19012]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. type @ and an email to get only one item on the suggestion list
3. Press the down key on your keyboard to deselect the item from the list
4. Press Enter

## Expected Result
No error appears on the console
## Actual Result
Uncaught TypeError: Cannot read properties of undefined (reading 'alternateText')    Error appears on the console

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8ac7774-0567-415a-8c70-3849aa260a83

<img width="960" alt="4" src="https://github.com/Expensify/App/assets/43996225/36d89128-15c3-49df-b319-0cf5f269eead">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684179183137189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by perunt** [comment]
thanks for creating the issue, let see if @getusha will confirm the bug

**Comment by sophiepintoraetz** [comment]
I'm not able to produce this bug on staging - despite pressing the down arrow, it's not deselecting.

![2023-05-17_10-33-55 (1)](https://github.com/Expensify/App/assets/42940078/0e040624-b71f-45fe-a3f3-754417567677)

**Comment by sophiepintoraetz** [comment]
Raised [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684313587458439?thread_ts=1684179183.137189&cid=C049HHMV9SM) but I don't think this can be reliably reproduced.

**Comment by sophiepintoraetz** [comment]
Okay, closing this one out - we can reopen if we are able to reproduce/it resurfaces.

**Comment by mountiny** [comment]
@getusha usually if the bug was not reproducible and we havent fixed it intentionally then we dont pay for reporting.

**Comment by mountiny** [comment]
Its case by case for sure, in this case we had lots of features quickly rolling out and some of the bugs had fixes up as the issues were reported as we knew about them. So its a thin line for sure but in general we pay out for a bug if the report has been what sparked the solution. In this case, the bug just disappeared with some change so even if you wouldnt report it, it would get fixed if that makes sense
