### ISSUE TITLE
LHN doesn't update after canceling failing money request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and send any text message
2. Go to settings > Preference and turn on failing network in order to make the bug easily reproducible
3. Send a money request (that will eventually throw error)
4. Notice the LHN shows the last requested money
5. The money request should throw an error then click the cancel icon
6. Notice the LHN still shows the last canceled requested money

## Expected Result:
When user cancels the error throwing requested money the LHN should update and show the last message before the money request
## Actual Result:
The LHN still shows the failing money request
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-0
**Reproducible in staging?:** Needs reproduction  (I can't trigger the error to reproduce)
**Reproducible in production?:** Needs reproduction (I can't trigger the error to reproduce)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e37d0f02-cc22-44df-bec5-613fac7164d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan_mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684138873331449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
Closing until reproduction steps have been added.
