### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] On task description editing page field is showing mandatory when editing an existing task where by actually field should be optional

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Click on FAB button -> Click on Assign task option
3. Enter title & description -> add any assignee -> Click on confirm task -> will navigate to task detail page
4. On task detail page click on Description -> clear title field and press save -> Notice error message is This field is required instead of please enter a title

## Expected Result:
On task description editing page field should be optional user can remove description & can save

## Actual Result:
On task description editing page field is mandatory & user can't remove values

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/8a4a1db8-5d83-40f6-b5d8-d962c197e3be">

<img src="https://github.com/Expensify/App/assets/43996225/0fddc18e-10ee-4410-b327-56817b0d2355" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684138155046919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136c1b2820ecd2721</li>
        <li>Upwork Job ID: 1658850991367442432</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
This is not reproducible so I expect that it has been resolved in a recent deploy:

Testing task - description not required
- no RBR
- no error message
- task is able to be sent without description

![2023-05-17_15-37-18](https://github.com/Expensify/App/assets/56830058/150ad372-53aa-4e8c-a97d-e4f78ad3737e)

![2023-05-17_15-37-09](https://github.com/Expensify/App/assets/56830058/f0538a78-4a66-4efb-b092-d2eb0f43f79f)

![2023-05-17_15-36-39](https://github.com/Expensify/App/assets/56830058/0220c152-d1c5-4b3a-b57b-ea4098fddf1c)

**Comment by zanyrenney** [comment]
checking here in slack too about version numbers : https://expensify.slack.com/archives/C01SKUP7QR0/p1684334987930659

**Comment by zanyrenney** [comment]
Okay, did some more testing and I understand the bug better now. It's that when you _edit_ an existing task description, it is showing the error, not that the description field always throws an error.

**Comment by zanyrenney** [comment]
Thank you @fedirjh ! Bump to @joelbettner please can you give us a 👍🏼 if you agree so we can move forward here please?

**Comment by zanyrenney** [comment]
Going OOO and this is pretty active so needs management by bug0 team member, as per the [new process ](https://expensify.slack.com/archives/CK49UADB9/p1684182291511799)to stay assigned but assign another team member, please can you keep a watch of this. I am OOO until 8th June. Thanks!

**Comment by joekaufmanexpensify** [comment]
I'm actually also going to be OOO next week. So replacing myself as the additional assignee (per this [discussion](https://expensify.slack.com/archives/CK49UADB9/p1685037474828329?thread_ts=1684182291.511799&cid=CK49UADB9)), so someone else who's working next week can help cover this until Zany's back!

**Comment by joekaufmanexpensify** [comment]
I'm actually also going to be OOO next week. So replacing myself as the additional assignee (per this [discussion](https://expensify.slack.com/archives/CK49UADB9/p1685037474828329?thread_ts=1684182291.511799&cid=CK49UADB9)), so someone else who's working next week can help cover this until Zany's back!

**Comment by alexpensify** [comment]
I followed up with Joel in Chat. I'm OOO on Monday but will check in on Tuesday.

**Comment by alexpensify** [comment]
No update

**Comment by joelbettner** [comment]
@dhairyasenjaliya's proposal looks good. 👍 Good call making sure the API updates with an empty value when the user deletes the description.

**Comment by alexpensify** [comment]
Based on @joelbettner's feedback, I'm assigning this GH to @dhairyasenjaliya.

**Comment by alexpensify** [comment]
Still being worked on

**Comment by alexpensify** [comment]
@dhairyasenjaliya - how's it going here?

**Comment by alexpensify** [comment]
Perfect, thank you for the update!

**Comment by alexpensify** [comment]
PR was merged on Friday! Woo!

**Comment by alexpensify** [comment]
Alright, we are waiting for the automation to kick in here.

**Comment by zanyrenney** [comment]
payouts due

**Comment by zanyrenney** [comment]
yep i will add that as the bonus amount :)

**Comment by zanyrenney** [comment]
Agree @fedirjh that sounds like a sensible regression test to add 👍🏼

**Comment by joelbettner** [comment]
On hold. Not overdue.

**Comment by zanyrenney** [comment]
@dhairyasenjaliya - I have paid you in one payment for contribution + reporting bonus + timeline bonus.

**Comment by zanyrenney** [comment]
@fedirjh paid you and the bonus 🎉

**Comment by zanyrenney** [comment]
All good here - I have bumped the regression test to be completed. But I am closing this out now as we are all sorted and regression test has its own issue!
