### ISSUE TITLE
App displays 'incorrect magic code' error for first login try after closing account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Open Security
4. Open Close account
5. Fill in the required details and close the account
6. Again insert same email/ number on login page that was used as primary contact for above closed account
7. Insert the new magic code and observe that app gives 'incorrect magic code' error
8. Resend the code and observe that now it works normally

## Expected Result: 
App should not display 'incorrect magic code' error is correct code is inserted even on first try after closing account
## Actual Result: 
On first try after closing account, even on inserting correct magic code, app displays 'incorrect magic code' error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/469442d1-d24b-4522-b77e-4a24fa1a85f4

https://github.com/Expensify/App/assets/43996225/e5dab16d-fd5c-4c7b-8d41-b0a3c8e1ca5a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684138664128389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, I wans't able to reproduce this. When I just tried it, it worked just fine with the first code. Feel free to comment/reopen if you're able to consistently reproduce.
