### ISSUE TITLE
Share code - The download option is NOT present

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18636

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Share code
4. Check for download button

## Expected Result:
The download function is present

## Actual Result:
No Download function

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/02bd408b-5617-4ed5-b16c-80c67def368a

![18636 Desktop](https://github.com/Expensify/App/assets/93399543/c0ca58b2-d587-4ad1-89c5-e355492472c2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment]
Seems like this is intended behaviour, it's enabled only for native platforms.

```js
const isNative = platform === CONST.PLATFORM.IOS || platform === CONST.PLATFORM.ANDROID;
...
{isNative && (
    <MenuItem
        title={this.props.translate('common.download')}
        shouldShowRightIcon
        icon={Expensicons.Download}
        // eslint-disable-next-line es/no-optional-chaining
        onPress={() => this.qrCodeRef.current?.download()}
    />
)}
```

**Comment by NicMendonca** [comment]
Thanks for checking and confirming that @therealsujitk!
