### ISSUE TITLE
[HOLD for payment 2023-05-29] [HOLD for payment 2023-05-25] Deleting thread replies results in "0 Replies"

### ISSUE THREAD

**Issue by grgia** [Expensify/App#19042]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6f62bce1dabf496</li>
        <li>Upwork Job ID: 1658518218156986368</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

https://expensify.slack.com/archives/C049HHMV9SM/p1684252528337349

Create a thread
Post one message in the thread
Delete the message you created in 2
See an unexpected result (0 replies) on the original room

![Image](https://github.com/Expensify/App/assets/38015950/69650dc9-8f00-4ab7-9bba-bb00601094a1)

**Comment by grgia** [comment]
cc @chiragsalian childCommentorCount not updated when deleting

**Comment by abdulrahuman5196** [comment]
Kindly let me know once the PR is ready. Would be happy to jump in on the review.

**Comment by abdulrahuman5196** [comment]
@grgia I think this issue is updated wrongly. It was already deployment 5 days back and payment due on 25/5.
And could you kindly add label, so that a automatic BZ member is assigned to this issue?

**Comment by grgia** [comment]
@isabelastisser could you help with C+ internal review payment?

**Comment by abdulrahuman5196** [comment]
@isabelastisser  Gentle ping on the payment.

**Comment by isabelastisser** [comment]
Hi @abdulrahuman5196 , I sent you the invite in Upwork. Please accept it and I will hire and process the payment asap. Thanks!

**Comment by abdulrahuman5196** [comment]
@isabelastisser  I have accepted the invite.

**Comment by isabelastisser** [comment]
The payment was made, and we are all set!
