### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] Bug - Threads should be searchable in NewDot

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#19043]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175fc8106faa58316</li>
        <li>Upwork Job ID: 1658609342570344448</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Looks like this is coming from https://expensify.slack.com/archives/C03SC9DVD/p1684248487851519, so not taking any action here as of right now per https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=BugZero%20process%20steps%20for%20feature%20requests

**Comment by greg-schroeder** [comment]
PR is still in progress

**Comment by greg-schroeder** [comment]
PR approved, awaiting merge and deployment

**Comment by greg-schroeder** [comment]
Offer sent to @thesahindia

**Comment by greg-schroeder** [comment]
Complete.
