### ISSUE TITLE
3Eyed todd appears when opening a thread for the first time

### ISSUE THREAD

**Issue by grgia** [Expensify/App#19045]
Create a new thread.
Open it for the first time.
3 eyed todd Report not found will flash for a second

**Comment by grgia** [comment]
https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js#L234-L243

**Comment by jasperhuangg** [comment]
Sorted out the regression in a new PR, all good here!

**Comment by grgia** [comment]
@aimane-chnaif PR was merged https://github.com/Expensify/App/pull/19056
Although it seems this issue may still be occurring on native (separate issue from what was being fixed in the PR)

**Comment by grgia** [comment]
Ah thank you @aimane-chnaif, I'll look into an alternative solution

**Comment by grgia** [comment]
haven't had a chance to look at this one again yet, should be able to this week

**Comment by grgia** [comment]
I plan on looking at this bug today and next week

**Comment by grgia** [comment]
I am unable to reproduce, @chiragsalian I saw in the deploy blocker issue you pushed a fix as well- did that cover this issue?

**Comment by grgia** [comment]
Alright, I'm going to close this one out in that case as I'm also not able to reproduce
