### ISSUE TITLE
[HOLD for payment 2023-06-02] Web - Login - User gets 'Magic Code' instead of 'Abracadabra, you are signed in' message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
**First scenario:**
1. Open staging.new.expensify.com and continue with the log in flow with any account
2. Navigate to the email inbox and look for the magic link email
3. Change the link to staging if needed
4. Open a new tab and paste the link in the URL
5. Verify an "Abracadabra, you are signed in!" page is displayed

**Second scenario**
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new tab and navigate to the staging link
4. Verify the 2FA required page is displayed. Should have a message similar to "Please enter the two-factor authentication code where you are trying to sign in."
5. Navigate back to the original tab - Keep the second tab open
6. Verify the log in flow is now asking the user to enter the 2FA code
7. Enter the 2FA code
8. Verify the user can log in
9. Navigate to the secondary tab
10. Verify the "Abracadabra, you're logged in" page is displayed

## Expected Result:
"Abracadabra, you are signed in!" page is displayed.

## Actual Result:
User gets 'Magic Code' instead of 'Abracadabra, you are signed in' message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
First scenario https://expensify.testrail.io/index.php?/tests/view/3456321
Second scenario https://expensify.testrail.io/index.php?/tests/view/3456319

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ebd7f58b-6efc-455a-bc15-fdf1275d049e

https://github.com/Expensify/App/assets/93399543/dc89506c-97a7-4100-93d3-8c6f180ce49a

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@isagoico

**Comment by isagoico** [comment]
There's a weird behavior on Staging surrounding the Magic link. A few hours ago this was working without issues, video below: 

https://github.com/Expensify/App/assets/44479856/7faa45b2-7cd3-4ce5-bee7-914ee15cc2de

Now, the "abracadabra" page is not being displayed consistently on staging nor production. Will investigate further on the issue🫠 @roryabraham I think that we should be good with removing the deploy blocker label on this one.

**Comment by yuwenmemon** [comment]
Not a blocker for the NewDot deploy since this is also happening on Prod.

**Comment by roryabraham** [comment]
Making this a Daily again

**Comment by roryabraham** [comment]
PR ready for review: https://github.com/Expensify/App/pull/19468

**Comment by Christinadobrzyn** [comment]
Hey @roryabraham would you be able to check on this GH to see if this will be fixed with this implementation?

https://github.com/Expensify/App/issues/19860

**Comment by roryabraham** [comment]
Oh, so this is done / should've been closed already. I'm going to close this but then will check on that other one.
