### ISSUE TITLE
Task - Unable to save task title on first attempt and edit not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18672 

## Action Performed:
1. Launch the app and login
2. Navigate to or create a task report
3. Click on the title component, a form should appear
4. Edit the title content then hit save, it should navigate back to the report
5. Click on the description component, a form should appear
6. Edit the description content then hit save, it should navigate back to the report
7. Edit the assignee content, it should navigate back to the report
8. Verify that messages have appeared on the report indicating the edits

## Expected Result:
After step 4 the title saved
After step 7 all the edits are displayed in chat

## Actual Result:
Title saved only on the second attempt and message not displayed in chat for edits

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.10

**Reproducible in staging?:** Yes

**Reproducible in production?:** New Feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/06b5667b-1844-4ed3-9ce6-8fab264ef4d6

https://github.com/Expensify/App/assets/93399543/1841aafb-a781-4aa3-9c36-5c9b4e451b96

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I can't reproduce this, but I can reproduce something else that I've added here: https://expensify.slack.com/archives/C049HHMV9SM/p1684349723299479
