### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] DEV : console error on open #admins or #announce share code page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to #announce or #admin
2. Go to details page
3. click on share code

## Expected Result: 
should not show any console error
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/555b1287-8c53-466d-bbda-d94d082a1e73

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684156128912459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3a15603b3745d1c</li>
        <li>Upwork Job ID: 1660736628222496768</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
I can't test on Dev so I've asked for a help a few times. Still looking for someone who can reproduce for me and link their results.

**Comment by strepanier03** [comment]
Fresh reach out for a hand [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684520759570209).

**Comment by strepanier03** [comment]
I've reached out a few times for help reproducing this and haven't had any luck. I'm going to send it forward for some help determining if this can be reproduced on DEV and if it should be external/internal. 

Thank you for your help assignees!

**Comment by strepanier03** [comment]
@puneetlath @0xmiroslav - I'm not able to reproduce this since I don't have a dev environment but I don't want to sit on this any longer. Can you help me repro and decide if this should be external/internal.

**Comment by ahmedGaber93** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19051#issuecomment-1550203851)
cover the issue video logs, and reproduce logs [here](https://github.com/Expensify/App/issues/19051#issuecomment-1557896426).

**Comment by abdulrahuman5196** [comment]
Same issue at another place - https://expensify.slack.com/archives/C049HHMV9SM/p1684850796180919
Kindly verify this is also fixed during PR

@0xmiroslav @ahmedGaber93

**Comment by ahmedGaber93** [comment]
@puneetlath @0xmiroslav [PR](https://github.com/Expensify/App/pull/19514) now is ready for review.

**Comment by strepanier03** [comment]
Prepping for hold removal.

----

@0xmiroslav and @ahmedGaber93 - I've hired you for the job in UpWork. Miroslav, feel free to do the checklist and I'll update it and make the reg test GH if needed. 

@gadhiyamanan - I have created a reporting job in Upwork and hired you for it as well.

**Comment by strepanier03** [comment]
Thanks @0xmiroslav, I've updated the checklist!

----

Everyone is paid out so I'm going to go ahead and close. Thank you, everyone, for all the hard work here!
