### ISSUE TITLE
Three dots appear for a fraction of seconds.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to "Chat"
2.  Open Chat with green dot
3.  Notice the three dots appear for a fraction of seconds at top right corner

## Expected Result: 
Three dots shouldn’t appear for a fraction of seconds or remain there permanently.

## Actual Result: 
Three dots appear for a fraction of seconds.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-12
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/837fc508-2043-4b99-a494-61297500be96

https://github.com/Expensify/App/assets/43996225/8e400a20-2acb-49d6-88ce-e0615fca1c8a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684165314600679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
chat has been f'd today. i will try to repro this tomorrow.

**Comment by maddylewis** [comment]
i think this has been resolved from some updates that happened yesterday / it was related to the Task feature deploying. but it's since been fixed. 

https://github.com/Expensify/App/assets/38016013/7bd7c775-93c7-4b50-b969-fc720e78083d
