### ISSUE TITLE
[$1000] Console error appears when pressing enter by not selecting suggested emoji

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. type :smiley_cat
3. Press the down key on your keyboard to deselect the item from the list
4. Press Enter

## Expected Result
No error appears on the console
## Actual Result
Uncaught TypeError: Cannot read properties of undefined (reading 'types')  Error appears on the console

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cdb56fc7-0950-49d6-9b9a-b2b4411be215

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/dfbbbb46-6353-4e79-805d-c183436ce26d">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684179269456589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014561b5a82bcc95ce</li>
        <li>Upwork Job ID: 1658602611817308160</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Yup, I wonder what the expected functionality should be for hitting the down arrow at the bottom of the list? I think you should just _stay_ on the last item, so this would always choose `:smiley_cat:` no matter how many times you hit down.

<img width="1424" alt="image" src="https://github.com/Expensify/App/assets/9133401/78b398d4-0994-4819-8ffc-cece91f63aac">

**Comment by Santhosh-Sellavel** [comment]
Unable to reproduce on the main for me.

**Comment by twisterdotcom** [comment]
Whoah, you're right! It's fixed!
![2023-05-17_10-08-52 (1)](https://github.com/Expensify/App/assets/9133401/35cf5819-1cd2-4978-af91-f7319a74c16f)

This literally threw an error for me like 9 hours ago.
