### ISSUE TITLE
Threads - "Details" in threads show with no information

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18522

## Action Performed:
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Sign into a valid account (expensifail account)
3. Message another user that has been "whitelisted"
4. Send a message, then thread on this message.
5. In the Thread DM, click on "Details"

## Expected Result:
User expects to see the details of the thread, most likely who they are threading with should show

## Actual Result:
No information is shown at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4523cf7a-203b-4259-a63e-57720c0c2146

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
dupe https://github.com/Expensify/App/issues/18757
