### ISSUE TITLE
On mentioned user we are also getting list of report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Go to any conversation
3. On composer try to find any money report by adding @moneyReportName
4. Notice your able to find report name where by we should only render user name to tag

## Expected Result: 
There should be no report on search user (since this is
## Actual Result: 
Search list includes the report as well

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/16dfe44d-226e-485d-b8e8-93e97d1efbd4">
![Screenshot 2023-05-16 at 9 04 07 AM](https://github.com/Expensify/App/assets/43996225/cb7f1da5-0fa3-4419-a3b9-f76178266f98)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684208576403289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I think this will probably end up getting fixed by what we do here: https://github.com/Expensify/App/issues/18746

**Comment by puneetlath** [comment]
@dhairyasenjaliya I added you as an issue reporter on that one ^. I'm going to go ahead and close this out since this is being covered by the PR there.
