### ISSUE TITLE
[HOLD Web-E #37455] Webp images are not loaded but uploads perfectly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19071]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. Go to any chat
3. Click on send attachment
4. Send webp file and send jpeg file
5. Notice that the jpeg file loads properly but the webp file doesn't load

## Expected Result:
Webp file should be loaded properly
## Actual Result:
Webp images are not loaded but uploads perfectly

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/84096afa-e685-42ac-9dca-0739addc60bc

<img width="960" alt="ffd" src="https://github.com/Expensify/App/assets/43996225/316842e2-98bd-4c26-b202-22a0fe49e624">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684216674836249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd5bd12faed785ea</li>
        <li>Upwork Job ID: 1658579099188383744</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
I have a [fix](https://github.com/Expensify/Web-Expensify/pull/37455) for this waiting to be merged. Gonna keep this internal as it's a backend fix.

**Comment by priya-zha** [comment]
@sakluge Thank you. Accepted the offer.

**Comment by sakluger** [comment]
@youssef-lr I see @rushatgabhane assigned to this issue, but not as a reviewer on the linked PR. Was Rushat involved in reviewing the PR, or do we just need to pay @priya-zha as the bug reporter?

**Comment by sakluger** [comment]
Paid @priya-zha, so if there were no other external contributors or C+ reviewers, we're good to close this one out!

**Comment by youssef-lr** [comment]
We only need to pay for the bug report @sakluger!

**Comment by sakluger** [comment]
Cool, removing Rushat's assignment then.

**Comment by sakluger** [comment]
Still just waiting for this to deploy to production. Should happen tomorrow or Tuesday.

**Comment by youssef-lr** [comment]
We're good here @sakluger. Closing!
