### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] URL of Share code treated as email instead of URL

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Share code
2. click on share to copy the share code
3. Go any chat
4. paste the link

## Expected Result: 
should be treated as link
## Actual Result: 
does not treat as URL and on click it opens mail

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-14
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/77f5f5f8-6f91-4756-8fff-1dfde44a82b4

https://github.com/Expensify/App/assets/43996225/f012a66b-6686-41fc-90f1-2b05dcf251b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant 
**Slack conversation:** ~https://expensify.slack.com/archives/C049HHMV9SM/p1684228471954519~ https://github.com/Expensify/App/issues/19039#issuecomment-1561817299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017871c028abb202e9</li>
        <li>Upwork Job ID: 1658796901345894400</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
I think it duplicated https://github.com/Expensify/App/issues/16762

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
URL of Share code treated as email instead of URL
### What is the root cause of that problem?
We didn't encode the param for the share url in here which causes the issue.
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/pages/ShareCodePage.js#L41
### What changes do you think we should make in order to solve the problem?
We should encode the email params of the share url:

```javascript
const url = isReport ? `${CONST.NEW_EXPENSIFY_URL}r/${this.props.report.reportID}` : `${CONST.NEW_EXPENSIFY_URL}details?login=${encodeURIComponent(this.props.session.email)}`;
```

### What alternative solutions did you explore? (Optional)
None

**Comment by tjferriss** [comment]
Easily reproduced.
<img width="985" alt="Screenshot 2023-05-17 at 04 29 02" src="https://github.com/Expensify/App/assets/8292562/bade4208-b606-4fca-9de5-5c16bd26c2b8">
<img width="1346" alt="Screenshot 2023-05-17 at 04 29 41" src="https://github.com/Expensify/App/assets/8292562/dea7c938-8182-4f03-a851-fe16230748a5">

**Comment by AlexanderDmitriev** [comment]
## Proposal
Issue is on **_expensify-common_** lib. In this lib, regex for parsing email is wrong.
![image](https://github.com/Expensify/App/assets/17315937/8e5869a6-5c3f-4c19-ac89-5822700d61d2)
**Solution**
need to update regex so that it can parse comment text exactly as email or link

**Comment by AlexanderDmitriev** [comment]
## Proposal
Issue is on **_expensify-common_** lib. In this lib, regex for parsing email is wrong.
![image](https://github.com/Expensify/App/assets/17315937/8e5869a6-5c3f-4c19-ac89-5822700d61d2)
**Solution**
need to update regex so that it can parse comment text exactly as email or link

Contributor details
Your Expensify account email: alexanderdmitriev1020@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012c8ac9b744c4ad09

**Comment by robertjchen** [comment]
Proposal sounds good to me

**Comment by hungvu193** [comment]
Thanks @robertjchen , what's the next step from here?

**Comment by robertjchen** [comment]
Normally we'd get a signoff from C+ https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md but I think this is simple enough to proceed 🤔  (Though, definitely feel free to chime in @eVoloshchak if you think there's a better approach).

@tjferriss Could you please hire @hungvu193 on upwork to proceed with the implementation of the solution? Thanks!

**Comment by bfitzexpensify** [comment]
@hungvu193 I'm looking at a similar issue in https://github.com/Expensify/App/issues/19344 - will your proposal solve for that problem (when following a share code link to message a user, there is a 'report no longer exists' error)?

**Comment by hungvu193** [comment]
yeah, It will solve it as well. @bfitzexpensify

**Comment by michaelhaxhiu** [comment]
So the fix to this GH will resolve these 3 bug reports:
- This GH - https://github.com/Expensify/App/issues/19076
- https://github.com/Expensify/App/issues/19062
- https://github.com/Expensify/App/issues/19344

**Comment by francoisl** [comment]
@michaelhaxhiu I'm going to add https://github.com/Expensify/App/issues/19039 to your list of fixed bug reports too.

**Comment by Nathan-Mulugeta** [comment]
Hey team, I have a question about the bonus payment for reporting issues. How is it going to be processed? I noticed that my report [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684417113803759?thread_ts=1684417113.803759&cid=C049HHMV9SM) was dated May 15th, which was earlier than this open report. Does that affect the payment?

**Comment by michaelhaxhiu** [comment]
Hmm seems like you reported it 1 day before @gadhiyamanan, so you would be eligible for the bug reporting bonus in that case.

**Comment by Nathan-Mulugeta** [comment]
Ow okay 👍, @michaelhaxhiu thanks for replying.

**Comment by michaelhaxhiu** [comment]
I'm brewing. I can't tell if these bug reports are exactly 1:1 or not 🤔  there's a possibility we pay you both for the bug reports but it'd be helpful to get your input on how they are the same or different cc @Nathan-Mulugeta and @gadhiyamanan

**Comment by Nathan-Mulugeta** [comment]
I was on [this](https://github.com/Expensify/App/issues/19039) issue @michaelhaxhiu and I noticed that the PR for this issue also fixed [#19039](https://github.com/Expensify/App/issues/19039). So I thought the RCA might be the same for both issues. That’s how I got here.

**Comment by therealsujitk** [comment]
@michaelhaxhiu both issues are the exact same, the `url` variable is passed to the QR code and the copy button as a prop. This issue (#19076) references the copy button while the other (#19039) references the QR code. Fixing the `url` variable fixed both issues.

**Comment by gadhiyamanan** [comment]
>I'm brewing. I can't tell if these bug reports are exactly 1:1 or not 🤔 there's a possibility we pay you both for the bug reports but it'd be helpful to get your input on how they are the same or different cc @Nathan-Mulugeta and @gadhiyamanan

I think all 4 issues https://github.com/Expensify/App/issues/19076 https://github.com/Expensify/App/issues/19062 https://github.com/Expensify/App/issues/19344 https://github.com/Expensify/App/issues/19039 have the same RCA and we can combine them. only one issue eligible for reporting bonus which is  https://github.com/Expensify/App/issues/19062 because it was the first which is reported on Slack. what are your thoughts?

cc: @michaelhaxhiu @sonialiap @bfitzexpensify

**Comment by tjferriss** [comment]
An offer has been sent to @eVoloshchak and @Nathan-Mulugeta for the reporting bonus. @hungvu193 I couldn't find you in Upworks. Can you please apply for the job? https://www.upwork.com/jobs/~017871c028abb202e9


@gadhiyamanan I agree with your conclusion on paying the reporting bonus here for all issues.

**Comment by hungvu193** [comment]
> An offer has been sent to @eVoloshchak and @Nathan-Mulugeta for the reporting bonus. @hungvu193 I couldn't find you in Upworks. Can you please apply for the job? https://www.upwork.com/jobs/~017871c028abb202e9
> 
> 
> 
> 
> 
> @gadhiyamanan I agree with your conclusion on paying the reporting bonus here for all issues.

Thanks @tjferriss , I've just applied

**Comment by Nathan-Mulugeta** [comment]
Accepted offer.

**Comment by michaelhaxhiu** [comment]
Agree with ya @gadhiyamanan + @tjferriss on that payment gameplan 👍

**Comment by gadhiyamanan** [comment]
>  I agree with your conclusion on paying the reporting bonus here for all issues.

@tjferriss @michaelhaxhiu In that case , only  @dhanashree-sawant is eligible for reporting bonus as she was the first to report it in slack

**Comment by robertjchen** [comment]
Thanks for sorting this out- are we all set to close out this issue here? 🙏

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18636

-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18636/files#r1212280330

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

-  Determine if we should create a regression test for this bug.

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Go to settings > Share code
2. Click on `Share` to copy the share code
3. Go to any chat
4. Paste the link
5. **Verify the link is displayed correctly, all of the message is formatted as link**

1. Sign in with your phone number
2. Go to Settings > Share code
3. Click Copy URL to clipboard
4. Next, sign in with another account
5. Paste and open the copied URL
6. Click on Message ...
7. **Verify there is no 'Report no longer exists' error** 

**Do we agree 👍 or 👎**

**Comment by tjferriss** [comment]
All payments have been made in Upworks and the regression test has been submitted to Applause.

**Comment by dhanashree-sawant** [comment]
Hi @tjferriss, I have recieved the offer but It is still pending to be approved, can you have a look once you are available?

**Comment by tjferriss** [comment]
Done.
