### ISSUE TITLE
Web - Threads - Functions don't work in Thread DM for the main message but reflect on LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Sign into a valid account (expensifail account)
3. Message another user that has been "whitelisted"
4. Send a message, then thread on this message.
5. Try to edit the main message in the thread DM or Delete it

## Expected Result:
User expects to be able to do this and the changes be reflected in the Thread DM

## Actual Result:
The Thread DM does not reflect the changes but the user can see that in the LHN the changes are applying

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.14

**Reproducible in staging?:** Yes

**Reproducible in production?:** No (new feature)

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dddb094a-e1d3-4648-9610-ba125613ea76

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
known bug, its captured [here](https://github.com/Expensify/Expensify/issues/282991)

**Comment by grgia** [comment]
Closing in favor of https://github.com/Expensify/Expensify/issues/282991
