### ISSUE TITLE
Unable to delete a contact method including capital letters

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#19080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Launch the app -> Login in account
2. Navigate to Avatar > Profile  > contact method
3. Add a new contact email including capital letters i.e DERP@DERP.COM 
4. Delete the contact method you just added

## Expected Result:  
You should be able to delete the contact method 

## Actual Result: 
Attempting to delete the contact method results in this error: `Auth DeleteLogin returned an error`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** `v1.3.14-14`
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/47522946/236903532-b51120b8-5740-4a64-8499-ff3cde0461b8.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://github.com/Expensify/App/issues/18301#issuecomment-1538852132

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c866a623249c0072</li>
        <li>Upwork Job ID: 1658592013696098304</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Removing C+ given that it's a backend issue.

**Comment by Beamanator** [comment]
Gooooooood question @dhairyasenjaliya , I will do some investigation soon, most likely it's just a backend change though

**Comment by Beamanator** [comment]
Alright so specifically with `DeleteLogin`, we do convert the email to lowercase when searching for the login to delete :D
- https://github.com/Expensify/Auth/blob/3787d75cd752227649565e1a2e05919e661434d1/auth/lib/Account.cpp#L47

I believe this also happens when requesting a new magic code for an email with capital letters (not sure if this has been reported yet?)

So this will require some back-end & some front end changes, both should lowercase new logins when:
1. Adding new contact methods
2. Sending magic codes / validating magic codes
3. Deleting contact methods

**Comment by Beamanator** [comment]
It could be a good idea to prevent users from entering capital letters in emails in the front end, but this will be the last step so I'm planning to worry about this later - but I'll come back to your thoughts for sure @dhairyasenjaliya - thanks for your ideas!

FYI I started an internal discussion [here](https://expensify.slack.com/archives/C03TQ48KC/p1684847716724809) to think about a migration we might have to run, making existing contact methods lowercase in the database & Onyx

**Comment by trjExpensify** [comment]
Sure, I think that's reasonable. @dhairyasenjaliya you seem interested, right?

**Comment by Beamanator** [comment]
FYI I made a super quick App PR to try to limit the bleeding: https://github.com/Expensify/App/pull/19520

But I think we should open this up for a wider proposal (probably even lowercase contact methods when setting to default)

**Comment by Beamanator** [comment]
@trjExpensify added notes above 👍

**Comment by Beamanator** [comment]
FYI there was no payment needed, it was resolved internally

**Comment by trjExpensify** [comment]
>Yes I think it's smart to have QA test that adding mixed-case contact methods only actually creates lowercased contact methods 👍

Did you update the script somewhere for the new contact methods rollout or something?

**Comment by Beamanator** [comment]
@trjExpensify we've been doing testrail updates throughout the rollout, we don't have 1 giant script anywhere sadly

**Comment by trjExpensify** [comment]
Okay, but same same.. are you saying the regression test update or that has been accounted for?

**Comment by Beamanator** [comment]
Oh oh like do I think we should add something to the regression tests for this? I think yes! We definitely don't want to be able to add mixed-case logins (primary or secondary) anywhere at the moment 👍

**Comment by trjExpensify** [comment]
Kewl, so can yah do this step or have you somewhere else? (I see it checked off). 

>@Beamanator] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by Beamanator** [comment]
Oh ya sure, sorry I thought the steps would be pretty obvious :D I'm thinking something like:

1. Add a new contact method with some uppercase and some lowercase letters (example: `MYEMAIL@gmail.COM`)
2. Verify the contact method gets added in the "Contact Methods" page, in all lowercase letters (`myemail@gmail.com`)
3. Try removing that newly added contact method
4. Verify everything works as intended

**Comment by trjExpensify** [comment]
Great, amended a touch and created [the issue](https://github.com/Expensify/Expensify/issues/289618) for Applause. 

Presuming as well with the Web-E issue merged and on prod we can close. Reopen if I missed something!

**Comment by trjExpensify** [comment]
Ah, sorry man. @Beamanator throwing me off! 😆 

>FYI there was no payment needed, it was resolved internally

Sent you a contract on [this job](https://www.upwork.com/jobs/~01c866a623249c0072).

**Comment by Beamanator** [comment]
Oh shit that's totally my bad 🙃

**Comment by trjExpensify** [comment]
Paid!
