### ISSUE TITLE
LHN - Each tap on IOU preview creates a new chat in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18760

## Action Performed:
1. As user A create a chat with user B
2. Request money from user B - $10 for lunch
3. Click on the IOU Preview
4. Make sure you have been navigated to a new chat report
5. Tap on IOU preview again

## Expected Result:
No new chat should be created. User can post a message to this chat.

## Actual Result:
Each tap on IOU preview creates a new chat in LHN
If the user gets an error after tries to send a message to each of these chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.14

**Reproducible in staging?:** Yes

**Reproducible in production?:** no (new feature)

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4bcda845-80ae-4704-a242-ed438e8538bb

https://github.com/Expensify/App/assets/93399543/69eca544-9dec-4498-a4df-4c0c9dd7e887

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is expected for now and we are still working on adding the right data to that view. Gonna close this issue.
