### ISSUE TITLE
Task preview doesn't contain a title on fresh sign in

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
1. Create a bunch of tasks
2. Sign out
3. On sign in, open the parent report where the task was created

## Expected Result:
Describe what you think should've happened
The task previews should contain titles
## Actual Result:
Describe what actually happened
Notice that the tasks don't contain titles.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01983c7252a3d7f068</li>
        <li>Upwork Job ID: 1658894653046792192</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
We should be fetching the task report data when we grab the reportAction to show on that preview.  However, this doesn't always seem to be the case

**Comment by Christinadobrzyn** [comment]
hey @thienlnam can this be external?

**Comment by Christinadobrzyn** [comment]
I think we're working on the PR, is that right @thienlnam?

**Comment by thienlnam** [comment]
Yup, PR in progress

**Comment by thienlnam** [comment]
Done - but this is going to be broken for a bit and will be fixed in https://github.com/Expensify/App/issues/19089

**Comment by Christinadobrzyn** [comment]
Awesome! thanks @thienlnam - closed the Upwork job
