### ISSUE TITLE
Non-assignees cannot see the task

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19102]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create the task in a group
2. Don't assign anyone to the task
3. Log into one of the other accounts

## Expected Result:
1. Verify that you can see the task

## Actual Result:
Non assignees cannot see the task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103763065b81285eb</li>
        <li>Upwork Job ID: 1658726147986870272</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Hi @thienlnam - just checking, since this is Internal: we're paying @0xmiroslav to work on this issue?

**Comment by thienlnam** [comment]
Ah no, I labeled internal since it's a back-end issue - shouldn't need anything here besides tracking for other bug reports

**Comment by thienlnam** [comment]
> @thienlnam I also noticed that other accounts cannot see the task after assign someone who is not in the group

Ah yeah good catch - will also include those changes in my backend changes

**Comment by jliexpensify** [comment]
@thienlnam cool, shall I remove the Upworks job then?
