### ISSUE TITLE
Settled expense reports prioritised too high in LHN ordering

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#19105]
### Problem

The ordering of the LHN is incorrect. Settled IOUs remain higher in the LHN ordering than chat reports with newer messages. 

In the following screenshot, 'THIS IS A CHAT REPORT' is the most recent message:

<img width="378" alt="Screenshot 2023-05-17 at 10 33 01" src="https://github.com/Expensify/App/assets/10736861/0824e966-ff91-4cee-89a1-d1254375e811">

### Solution

Yes

**Comment by mountiny** [comment]
Once IOU/Expense report is settled, we should treat it as a normal chat so the order should be based on the last time of some report action.

**Comment by JmillsExpensify** [comment]
Can we float this in C+ this morning?

**Comment by mountiny** [comment]
@Julesssss I believe there was some discussion around this in slack and it might have been that the order is correct, do you recall?

**Comment by Julesssss** [comment]
I don't recall that discussion. Next time I'm testing IOUs locally I'll see if it still exists.

**Comment by Julesssss** [comment]
Think this is resolved, testing with Vit today.

**Comment by Julesssss** [comment]
Yep, I no longer seem to see the reordering: 

<img width="343" alt="Screenshot 2023-06-09 at 14 40 07" src="https://github.com/Expensify/App/assets/10736861/a8922e55-5cd1-41fb-b98a-bbfa408af2d8">

Closing
