### ISSUE TITLE
[HOLD for payment 2023-07-21] Report preview action is not added optimistically when sending money

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19119]
### Problem

When Sending money to another account the report preview action is not added optimistically

### Why is it important

Its a bad UX as they take action and we create the request and iou report, but in the chat where they are at nothing happens

### Solution

Make sure that we correctly create this action when sending money.

**Comment by luacmartins** [comment]
This is the issue for the backend https://github.com/Expensify/Expensify/issues/284588

**Comment by mountiny** [comment]
Thanks for taking this on Cristi

**Comment by cristipaval** [comment]
On hold for [Auth PR #7976](https://github.com/Expensify/Auth/pull/7976) which should be ready soon.

**Comment by cristipaval** [comment]
Addressing now feedback on the Auth PR.

**Comment by cristipaval** [comment]
This is still on hold. I wonder if we should update this issue to also add the logic for when the report action should show the workspace `avatar` and `displayName`, as stated [here](https://github.com/Expensify/Auth/pull/7976#discussion_r1223494714) cc @mountiny

**Comment by mountiny** [comment]
@cristipaval I think we should do this in one go.

**Comment by cristipaval** [comment]
Alright, I feel like Auth PR is in good shape now after a few rounds of reviews. I'm going to open an App PR for this one tomorrow.

**Comment by cristipaval** [comment]
Opened a [draft PR](https://github.com/Expensify/App/pull/20941). For now, I implemented the logic to show the workspace avatar and name for the report preview action when the workspace owes money.

**Comment by cristipaval** [comment]
This will be merged soon.

**Comment by mountiny** [comment]
I think its good to complete this as it would be hard to do once we get back to this

**Comment by JmillsExpensify** [comment]
Agreed.

**Comment by cristipaval** [comment]
Added `Bug` label to have someone for the payments.

**Comment by maddylewis** [comment]
regression period ends on Friday - switching to daily to confirm all of the to-dos are handled 👍

**Comment by maddylewis** [comment]
hm, i'm not seeing an Upwork job link or a payment amount on this issue. 

@cristipaval - is @parasharrajat the only person owed payment on this one? also, what's the payment amount?

**Comment by maddylewis** [comment]
@parasharrajat maybe you know the answer to this - https://github.com/Expensify/App/issues/19119#issuecomment-1645745102

**Comment by maddylewis** [comment]
oh wait, @parasharrajat would be paid via NewDot so i think we can actually close this out.

**Comment by JmillsExpensify** [comment]
@maddylewis Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @parasharrajat's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by maddylewis** [comment]
yeah, i am also unsure on the payment amount (asked here - https://github.com/Expensify/App/issues/19119#issuecomment-1645745102). 

@parasharrajat - can you help confirm whether or not there was a bonus associated with this fix? thanks!

**Comment by maddylewis** [comment]
### Payments:
- no reporting bonus
- $1000 payment to @parasharrajat (paid via NewDot)

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
