### ISSUE TITLE
LHN - Request money from WS shows negative number

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#19147]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a brand new account
2. Create a new workspace
3. Invite a member to the workspace
4. Sign in as the member
5. Tap the + icon and select "Request money" > Enter any amount
6. Tap on Next
7. Enter a description
8. Tap "Request $" button
9. Navigate to the LHN
10. Tap the row that says "so and so's Workspace owes $62.00"

## Expected Result:
Tap the row that says "so and so's Workspace owes $62.00"

## Actual Result:
Request money from WS shown with 'minus" owes a negative number [- $62}

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/44479856/6568936f-b0f6-4a28-8801-5bb66de85373)

https://github.com/Expensify/App/assets/44479856/04fb7f35-a8bc-4222-9c1a-f77984163523

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A https://expensify.slack.com/archives/C049HHMV9SM/p1684342649131059 

Found while executing PR https://github.com/Expensify/App/pull/18695 - CC @marcaaron 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01117d2b821953ca0c</li>
        <li>Upwork Job ID: 1658965798107848704</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I will monitor this one

**Comment by mountiny** [comment]
cped to prod
