### ISSUE TITLE
Remove button is not disabled when removing user from 2nd device in offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19155]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR #18934

## Action Performed:
1. Login app on a device with an account
2. Open Setting > Workspaces
3. Open any workspace that has multiple members
4. Open manage members and switch to offline
5. Login app on another device with the same account in step one and follow steps 2-4
6. On both platforms, select the same user
7. Using any one platform, remove the user selected
8. Verify that the remove button on the other platform is disabled

## Expected Result:
Remove button is disabled

## Actual Result:
Remove button is not disabled in offline
NOTE : only offline test is failing
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.15.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/77c4a8a1-cf04-4f33-8e46-b0a70eb42cb8

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment]
When one device offline, If device offline removes member in workspace, no api is called, BE not updated and no `eventData` send to other device, so that can not update button and list member. If device online removes member, device offline is disconnected with pusher,  it cannot received data from BE through `eventData` so that it cannot update the component

**Comment by slafortune** [comment]
Makes sense - sounds like this should be closed! Thanks @dukenv0307 

Do you agree @kavimuru  - I'm not missing something else, am I?

**Comment by kavimuru** [comment]
@slafortune Yes I do agree, Bug was reported from the PR offline test. Thanks
