### ISSUE TITLE
Task title is not displayed in parent chat after sign out / sign in

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19150]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Create a couple of tasks
3. Mark as complete
4. Sign out
5. Sign in
6. Go to parent chat with tasks

## Expected Result:
Completed task and Reopen task lines in parent chat should have Task title

## Actual Result:
Completed task and Reopen task lines in parent chat do not displayed Task title

P.S. Names appear for example once you click task name checkbox.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.15-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Found when executing PR #18806

https://github.com/Expensify/App/assets/43995119/ca1e14c3-df44-4a87-9e13-1930e333d820

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Closing in favor of https://github.com/Expensify/App/issues/19090
