### ISSUE TITLE
"You don't have access to this chat" is not displayed when opening a deeplink with valid id

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. On the URL change the conversation ID to any combination of 1-4 numbers. E.g https://staging.new.expensify.com/r/1234
## Expected Result:
Verify You see a You don't have access to this chat message in the conversation history
## Actual Result:
Skeleton page is displayed. "You don't have access to this chat message" in the conversation history isn't appeared.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Bug6059151_az_recorder_20230517_182153_mp4](https://github.com/Expensify/App/assets/43996225/4b49d8e6-712b-4ba3-9276-de80ee288939)

https://github.com/Expensify/App/assets/43996225/4e4b5d40-78f7-4a5b-bbe3-eeb40e69de30

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
This was fixed with https://github.com/Expensify/App/pull/19148
