### ISSUE TITLE
[HOLD for payment 2023-06-01] [HOLD for payment 2023-05-29] ReportPreview total is reset to $0.00 after signing out

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#19189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Create a request between any two users
- Pay the request as the recipient
- Both users shouls see a correct ReportPreview in the chat report
- Sign out
- Sign in

## Expected Result:
- The ReportPreview total should be correct

## Actual Result:
- The ReportPreview total is $0.00

**Before sign out**
<img width="1000" alt="Screenshot 2023-05-18 at 10 44 02" src="https://github.com/Expensify/App/assets/10736861/20046381-91b0-4049-85eb-94c2269aee6a">

**After sign out**
<img width="993" alt="Screenshot 2023-05-18 at 10 44 25" src="https://github.com/Expensify/App/assets/10736861/469a3cc8-88f1-4b33-9e5f-b9a121f2e6ba">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2e32055340064c5</li>
        <li>Upwork Job ID: 1659159230614130688</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Hey @miljakljajic, you can ignore I'm keeping this internal

**Comment by Julesssss** [comment]
First pass fix is [here](https://github.com/Expensify/App/pull/19194/files)

**Comment by trjExpensify** [comment]
Alrighty, looking at the PR associated to this issue. @mollfpr did the C+ review, so we need to switch him out for @thesahindia.

**Comment by trjExpensify** [comment]
I've sent you a $1,000 offer [here](https://www.upwork.com/jobs/~01d2e32055340064c5) for the review.

**Comment by mollfpr** [comment]
@trjExpensify accepted, thank you!

**Comment by trjExpensify** [comment]
Settled!
