### ISSUE TITLE
[HOLD for payment 2023-06-19] Fix Header subtitle for workspace chats

### ISSUE THREAD

**Issue by grgia** [Expensify/App#19186]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b9003e769e27cb3</li>
        <li>Upwork Job ID: 1659152498133979136</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

https://github.com/Expensify/App/pull/19117#pullrequestreview-1431318556

Thread header for workspace chat looks like `<Workspace Name> • ` and it should be just  `<Workspace Name>`

**Comment by Santhosh-Sellavel** [comment]
@flaviadefaria For payment I'm just waiting for the internal process, please check [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1687451561563029?thread_ts=1686871517.189609&cid=C02NK2DQWUX). So please wait for further comments thanks!

**Comment by flaviadefaria** [comment]
@grgia can you confirm if payment should be $1000 or less?
@Santhosh-Sellavel since this is already due for payment and the internal process is not live yet then I'll pay this through UW and we can start using Expensify once the process is live.

**Comment by flaviadefaria** [comment]
Offer sent in UW!

**Comment by flaviadefaria** [comment]
@Santhosh-Sellavel can you please accept the offer so we can close this GH? 🙏

**Comment by flaviadefaria** [comment]
@Santhosh-Sellavel I'm closing this as complete. Whenever you want to receive the payment for the work done here please accept the offer in Upwork.

**Comment by anmurali** [comment]
@Santhosh-Sellavel gets paid via manual requests on New Dot. I just approved this request and paid
