### ISSUE TITLE
newDot messages aren't being sent 

### ISSUE THREAD

**Issue by miljakljajic** [Expensify/App#19190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open newDot on a Chrome browser on production
2. Open up a newDot DM 
3. Send a message
4. Refresh the page 

## Expected Result:
The message should have been sent

## Actual Result:
The message is no longer there and the recipient hasn't received it

## Workaround:
No workarounds (other than using mobile), newDot not usable on web

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.15-12
**Reproducible in staging?:** N
**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

milja@expensify.com

**Logs:** 

Logs linked here: https://www.expensify.com/_devportal/tools/logSearch/#query=blob%3A%22Pong%22%20AND%20email%3A%22milja%40expensify.com%22%20AND%20timestamp%3A%5B2023-05-17T00%3A00%20TO%202023-05-18T23%3A59%5D&index=_all

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/28715117/a089f591-32bd-48d8-a997-c025303b3c35

**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Hm, I can't reproduce this on my end. The OOO list command is working for me. @miljakljajic a few questions: 

- Does this happen to non-Chronos messages? If not, then feels more likely to be a Chronos issue. 
- Could you try this on a different platform (like mobile), or an incognito window, or different browser and see if you get the same result? 

Since this is working now, it feels most likely to me that this was a temporary issue with Chronos, but LMK if you're still experiencing this!

**Comment by miljakljajic** [comment]
It is still happening across all DMs and messages. The OOO list command maybe wasn't the best example but it's happening to any message I try to send.

Incognito works fine, but when I tried:

- Clearing OnyxDB
- Clearing local storage 
- Session storage 
- And clearing all browsing data

The issue still persists - it's not happening for _every_ message any more, but it's still happening

**Comment by joekaufmanexpensify** [comment]
Interesting. Is this happening on all platforms too, eg, on mobile? Or on a different browser? I can't reproduce this at all. The fact that you're not experiencing this on incognito makes me think this is likely an issue related to your current session. I'd try signing out and back in if you haven't already as well.
