### ISSUE TITLE
[HOLD for payment 2023-06-01] There’s an unnecessary line space above the report preview message in the chat

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#19201]
There’s an unnecessary line space above the report preview message in the chat. Let's remove it and make sure the preview has the correct margin.

![Screenshot 2023-05-18 at 11 36 46 AM](https://github.com/Expensify/App/assets/22219519/291b9f44-3b21-4b53-b555-bb0afcc23ada)

**Comment by luacmartins** [comment]
Forgot to add the Bug label here. @johncschuster could you please help paying @rushatgabhane for their review [here](https://github.com/Expensify/App/pull/19200)

**Comment by johncschuster** [comment]
@rushatgabhane, I've just sent you an invite via Upwork for this job (see screenshot). Can you accept that and let me know when you've done that so I can issue payment?

![2023-06-06_09-24-28](https://github.com/Expensify/App/assets/5579997/3f0ee55d-83c1-4633-bdfb-40ffadd61bed)

**Comment by johncschuster** [comment]
> Btw, you didn't have to create a new issue. Next time you could just add the External label and it'll automatically create upwork job

Oh sweet. Thanks for calling that out, @rushatgabhane!

**Comment by johncschuster** [comment]
I've sent the offer! Can you ping me again when you've accepted it? Thank you!

**Comment by johncschuster** [comment]
Payment has been issued! 🎉

**Comment by johncschuster** [comment]
@luacmartins, are we good with closing this issue?
