### ISSUE TITLE
[HOLD for payment 2023-06-07] [$1000] DEV: Console error on click Continue button in login page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. logout if you logged in
2. type emaild and click continue button

## Expected Result: 
should not show any Console error
## Actual Result: 
shows Console error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Happening in Dev 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/01ba26bd-fbca-49f0-801b-0c5503264adf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684237638723149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b7e89ee174b9672</li>
        <li>Upwork Job ID: 1660682236329598976</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I'm also not able to reproduce.

**Comment by gadhiyamanan** [comment]
to reproduce the issue type email id which has not been used before. console error appears when a welcome message shown
cc: @puneetlath 

https://github.com/Expensify/App/assets/54790231/0a6c0509-7464-4fbf-9884-8446a4c852fc

**Comment by puneetlath** [comment]
Ah cool. I'm able to reproduce now. Thanks @gadhiyamanan

**Comment by Vishrut19** [comment]
Do I need to submit proposal for this as well?

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on sign in page after enter new email

### What is the root cause of that problem?
`string && <View />` here:
https://github.com/Expensify/App/blob/58ced75b07c9a0c8f60313341e782442ab20081b/src/pages/signin/SignInPage.js#L77
https://github.com/Expensify/App/blob/58ced75b07c9a0c8f60313341e782442ab20081b/src/pages/signin/SignInPage.js#L98

### What changes do you think we should make in order to solve the problem?
wrap with `Boolean` here:
`this.props.credentials.login && this.props.account.primaryLogin`
`(this.props.credentials.login || this.props.credentials.validateCode)`

**Comment by puneetlath** [comment]
@situchan ETA for the PR?

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/App/pull/19639) is ready for review

Note: I also fixed similar issue on task header as commented [here](https://github.com/Expensify/App/issues/19202#issuecomment-1563551904)

**Comment by puneetlath** [comment]
Contracts sent. @0xmiroslav friendly reminder on the checklist.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
