### ISSUE TITLE
DEV: Infinite CreateTask API calls after creating a task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Expensify
2. Open FAB and Create a task

## Expected Result: 
No infinite API calls
## Actual Result : 
Infinite API calls
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Main
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71d352a4-1866-4ed0-9542-8f78e72010c0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1684254555872499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This looks like it was before the API changes were deployed - should be fixed now

**Comment by thienlnam** [comment]
Unfortunately not as we were already aware of the issue and had a fix out
