### ISSUE TITLE
Assign task - An error is displayed when opening the Assign task option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app.
2. To test this make sure Task beta should be enabled.
3. Click FAB > Assign Task.

## Expected Result:
An error is NOT displayed when opening the Assign task option

## Actual Result:
An error is displayed when opening the Assign task option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/c5fb4e5afdf4e267550d49a3ffb0dde74cfd0402bcf473c01285b9d09e73f998

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Same root cause with this one: https://github.com/Expensify/App/issues/17479

**Comment by isabelastisser** [comment]
I will prioritize this today.

**Comment by isabelastisser** [comment]
@kbecciv, please include screenshots or video of the issue, and I will follow the steps and try to reproduce it.

Please reopen the issue when you're ready. Thanks!

**Comment by kbecciv** [comment]
@isabelastisser Can you please tap on link 
![Screenshot_20230522_134531_Samsung Internet](https://github.com/Expensify/App/assets/93399543/ce0674fa-5305-4370-8b1f-cb330c207085)
