### ISSUE TITLE
Settings- Security - Invalid code error persists if close and reopen 2-factor setup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/18576

## Action Performed:
1. Open Expensify Desktop app
2. Click on profile icon
3. Click on "Security"
4. Click on "Two-factor authentication"
5. Click on copy codes / Download
6. Save the codes if needed
7. Click on "Next"
8. Input incorrect code
9. Click on "X"
10. Repeat steps 2-6

## Expected Result:
When user re-opens 2-factor auth setup after entering an incorrect code at the previous try - the error about invalid code is no longer displayed

## Actual Result:
When user re-opens 2-factor auth setup after entering an incorrect code at the previous try - the error about invalid code is STILL displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.3

**Reproducible in staging?:** yes

**Reproducible in production?:** New feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/2a7d18fefa82002513ff35352fa067ef1091f0d748fc784ee06d58b6d5289574

https://platform.applause.com/services/links/v1/external/203f0ffa6c939638434b9997c064fac9ac6f30028986123e096bbcfaedb3a18d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid error code persists for 2-factor setup page when we reopen it

### What is the root cause of that problem?
We are not clearing the account data of onyx once we unmount the component.

### What changes do you think we should make in order to solve the problem?
We need to add the useEffect cleanup function for `BaseTwoFactorAuthForm` component where we will call the function `Session.clearAccountMessages();` which gets executed on the unmount of the component.

**Comment by MonilBhavsar** [comment]
Dupe of https://github.com/Expensify/App/issues/19187
