### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Dev: Only description's text has reduced opacity when it's disabled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to ND
2. Click on FAB
3. Assign a task
4. Mark it as done

## Expected Result: 
The values of both the description and title should be displayed with reduced opacity.
## Actual Result :
Only description's text has reduced opacity

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Main branch
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cd67569d-a39c-4899-9231-8b6291f9ec19

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684262325244699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015756347dcee86389</li>
        <li>Upwork Job ID: 1666089075589812224</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
task header description's text has reduced opacity when it's disabled
### What is the root cause of that problem?
after mark as done we disable the item to prevent edit it.
but we use different style for item disabled here
https://github.com/Expensify/App/blob/2090c0525de9cd87b8c738e9ccb7dafe79a9a229/src/components/MenuItem.js#L72
### What changes do you think we should make in order to solve the problem?
set MenuItem prop titleStyle={styles.colorHeading} here to override disable color here.
https://github.com/Expensify/App/blob/2090c0525de9cd87b8c738e9ccb7dafe79a9a229/src/components/TaskHeader.js#L108-L113



### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment]
I don't think this is a bug. ([Asking in Slack](https://expensify.slack.com/archives/C04QEB4MJEQ/p1684495148662479))

**Comment by Gonals** [comment]
I think @aman-atg proposal looks a bit cleaner, but how come we don't have a C+ on this issue, @johncschuster?

**Comment by johncschuster** [comment]
Oh geez. Cuz I forgot to click the `External` label. 🤦

**Comment by sobitneupane** [comment]
Thanks for the update @aman-atg.

[Proposal (2. No reduced opacity and not-allowed cursor)](https://github.com/Expensify/App/issues/19232#issuecomment-1554008853) from @aman-atg looks good to me.

🎀👀🎀 C+ reviewed
cc: @Gonals

**Comment by johncschuster** [comment]
@sobitneupane Can you complete the BZ Checklist when you get a moment?

**Comment by johncschuster** [comment]
@aman-atg / @sobitneupane can you apply to the Upwork job above? Thanks!

**Comment by johncschuster** [comment]
NVM – I've invited you both!

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18806
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18806#issuecomment-1617573555
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

O think this is resulted by change in design rather than a bug. So, it couldn't have caught earlier.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Login to ND
2. Click on FAB icon
3. Assign a task and add some description.
4. Mark it as done
5. Verify that the opacity for Task's text and Description's text are not reduced & not-allowed cursor is being shown

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
Regression test issue created^

**Comment by johncschuster** [comment]
Payment has been issued!
