### ISSUE TITLE
Show uncompleted tasks in the LHN

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19242]
Creating issue to track the back-end changes for this

**Comment by thienlnam** [comment]
I created a draft PR for this, but having trouble getting a task report returned https://github.com/Expensify/Auth/pull/7989

I believe it is from the query but haven't been able to determine where the problem is

**Comment by thienlnam** [comment]
Thanks @youssef-lr! Appreciate the help

**Comment by flodnv** [comment]
Please make sure you time your queries. Last time @luacmartins and @aldo-expensify did not time their queries, it resulted in an 8 hour fire.

**Comment by youssef-lr** [comment]
Working on this tomorrow.

**Comment by youssef-lr** [comment]
I haven't had time to get to this yet, I will next week.

**Comment by youssef-lr** [comment]
Forgot to link to this issue lol. Closing as it's completed.
