### ISSUE TITLE
[HOLD comment linking] [Search] Implement App changes for Powerful Search

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19248]
Part of [internal] Search project https://github.com/Expensify/Expensify/issues/261800

We will have to make changes to the Search component to implement powerful search into newDot. Most changes are backend but we still need to update the component, make updates to data storage and new API call. 

I will provide more details here in the issue as we will refine them.

**Comment by gedu** [comment]
Hey Edu here, I am from Callstack - expert contributor group

**Comment by mountiny** [comment]
Thanks, closed.

**Comment by danieldoglas** [comment]
Hey @gedu Just to be sure (I didn't see this in the part you wrote in the design doc), but we do need to cover those type of issues in this implementation since we'll still do the local search for the chat switcher.

**Comment by gedu** [comment]
@danieldoglas Awesome I'm working on it, and double-check that this works with the issues mentioned

**Comment by mountiny** [comment]
@gedu works on the detailed section

**Comment by gedu** [comment]
Working on how the search text will be highlighted and how the message will be displayed

**Comment by danieldoglas** [comment]
Awaiting reviews.

**Comment by mountiny** [comment]
Still holding for the comment linking

**Comment by danieldoglas** [comment]
not overdue

**Comment by danieldoglas** [comment]
still hold

**Comment by mountiny** [comment]
Still on hold

**Comment by mountiny** [comment]
Still on hold, the comment linking is going through implementation

**Comment by danieldoglas** [comment]
still on hold

**Comment by danieldoglas** [comment]
still on hold

**Comment by mountiny** [comment]
Still on hold

**Comment by danieldoglas** [comment]
still on hold

**Comment by mountiny** [comment]
Still on Hold

**Comment by mountiny** [comment]
Thsi is still on hold

**Comment by mountiny** [comment]
Still on hold

**Comment by danieldoglas** [comment]
This is being included in Search v1 doc.
