### ISSUE TITLE
ReportPreview Avatar should change when settled

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#19259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Create a request from userA to userB
- UserB should settle the request

## Expected Result:
- The ReportPreview Avatar should switch to the person who settled

## Actual Result:
- The ReportPreview Avatar is the person who requested

**Please appreciate my fat cat:**

<img width="545" alt="Screenshot 2023-05-19 at 12 29 47" src="https://github.com/Expensify/App/assets/10736861/9fbddf7a-3b23-40a0-a549-4dd436af4d2c">
<img width="693" alt="Screenshot 2023-05-19 at 12 32 40" src="https://github.com/Expensify/App/assets/10736861/4b0a0b47-cc82-4f3c-931b-8945c518f0ec">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.16-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec9da10b9656eeb9</li>
        <li>Upwork Job ID: 1659522309042917376</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Hey @cristipaval, looks like you're already working on updating the action. Do you want to take this task too? As I think it should be a [small addition](https://github.com/Expensify/Auth/pull/7976/files#r1200412862) to your current PR.

**Comment by cristipaval** [comment]
yes I can take it

**Comment by Julesssss** [comment]
Thanks. I'm still subscribed to the issue if you have any questions.

**Comment by cristipaval** [comment]
Update:
This is fixed in Auth in [the PR](https://github.com/Expensify/Auth/pull/7976) which also updates the report previews when sending money or paying a money request. The PR is still WIP, I hope that it will be ready for review today. I'm going to open an App PR soon to also fix this when the report preview is optimistically created.

**Comment by trjExpensify** [comment]
Made sure this one was in the issue tracker and project. 👍

**Comment by Julesssss** [comment]
Oh, thanks. Must have missed this one in the chaos last week.

**Comment by cristipaval** [comment]
On hold for [Auth PR #7976](https://github.com/Expensify/Auth/pull/7976) which should be ready soon.

**Comment by puneetlath** [comment]
Moving to weekly until the Auth PR is done.

**Comment by cristipaval** [comment]
The Auth PR is still in review

**Comment by NicMendonca** [comment]
Was only _just_ merged: https://github.com/Expensify/Auth/pull/7976#issuecomment-1599082114

**Comment by cristipaval** [comment]
This is partially fixed. I am closing it though, because it will be complete when [this issue](https://github.com/Expensify/App/issues/19119) is closed. Working on it.
