### ISSUE TITLE
[HOLD for payment 2023-08-09] Remove type-specific avatars from rooms and threads

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#19264]
We currently have a mix of type-specific avatars for things like the #admins, #domains, etc rooms. However, threads just use the same icon as the workspace or the parent chat they were in. 
<img width="371" alt="image" src="https://github.com/Expensify/App/assets/2319350/b904e5a7-ded0-4b24-8b6c-9450a08931aa">

Let's standardize and get rid of room-specific icons. All icons should either be the workspace avatar or the DM/Group chat:
<img width="860" alt="image" src="https://github.com/Expensify/App/assets/2319350/9998e465-8709-4639-b8b9-11a5fc8023fb">

Note that we'll want to add a lock icon next to the room name for private/#admins rooms. This also means we'll remove the workspace badge from the LHN as well and only show it in the chat header:
<img width="990" alt="image" src="https://github.com/Expensify/App/assets/2319350/43c343b1-1c54-4766-9e6a-1706e110fe66">

cc @JmillsExpensify @chiragsalian @MitchExpensify @grgia @stitesExpensify can one of you take this from here?
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165c83124b93ca089</li>
        <li>Upwork Job ID: 1664763778988531712</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by grgia** [comment]
I got this one!

**Comment by grgia** [comment]
@shawnborton could you explain what you mean by `This also means we'll remove the workspace badge from the LHN as well and only show it in the chat header:`? 

<img width="370" alt="image" src="https://github.com/Expensify/App/assets/38015950/4285079e-b6fd-4086-a148-d6fe0590a3f6">
Are we just removing the pill entirely?

**Comment by grgia** [comment]
Also, do we want to keep the archived room one? 
<img width="379" alt="image" src="https://github.com/Expensify/App/assets/38015950/36770379-7766-4372-accc-9e026a72871d">

**Comment by grgia** [comment]
One more question- how about domain rooms? 
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/38015950/343f121a-394b-4897-b557-8318f7a428c7">

**Comment by shawnborton** [comment]
For archived rooms, I think we just keep the name as it is with `(archived)`

For domain rooms, maybe we just use the default workspace avatars where we use the beginning letter of the domain?

**Comment by JmillsExpensify** [comment]
I wanted to quickly confirm that we're removing the pills entirely, right?

**Comment by shawnborton** [comment]
That's my understanding.

**Comment by grgia** [comment]
Started this one

**Comment by grgia** [comment]
Just confirming, we will be keeping the circular trash icon? @shawnborton

**Comment by grgia** [comment]
@michaelhaxhiu could you help with $1000 c+ review payment for internal PR https://github.com/Expensify/App/pull/20512

**Comment by michaelhaxhiu** [comment]
I just invited Miki to the job here https://www.upwork.com/jobs/~0172f3aa691dfa5a36

**Comment by michaelhaxhiu** [comment]
Drop me a comment on this GH when you accept @0xmiroslav

**Comment by michaelhaxhiu** [comment]
yes 👍

**Comment by michaelhaxhiu** [comment]
Making weekly and pushing back payment date to Aug 1 just to ensure i check in

**Comment by michaelhaxhiu** [comment]
@0xmiroslav any update yet for payment?

**Comment by michaelhaxhiu** [comment]
Note: I'm preparing to go OOO for ~2 weeks, and need a BZ buddy to oversee this while I'm gone so that payment gets sent to @0xmiroslav. Thanks in advance for your help.

As a quick recap:
- This job is already complete
- But @0xmiroslav needs a little time to sort out some things with their personal bank
- So, I set an artificial deadline of 08/09 to remind us to check if it's ready to pay & close. 
- If Miki comments before that requesting payment, you can issue it immediately because the job is done!
- No one else needs payment here.

**Comment by MitchExpensify** [comment]
Thanks @michaelhaxhiu! Reminder set to pay out on 8/9 👍

**Comment by MitchExpensify** [comment]
Hi @0xmiroslav ! Just waiting on you to accept this offer to issue you payment https://www.upwork.com/nx/wm/offer/25771950

**Comment by grgia** [comment]
Not overdue, waiting on payment finalization. Were you able to accept the offer @0xmiroslav ?

**Comment by MitchExpensify** [comment]
I believe @0xmiroslav is sorting out a payment issue on their end ([Internal Slack thread for reference]([0xmiroslav](https://github.com/0xmiroslav)))

**Comment by MitchExpensify** [comment]
Fwiw @michaelhaxhiu, I wasn't sure the best route for payment here but that seems to have been resolved based on this comment https://expensify.slack.com/archives/C01SKUP7QR0/p1692226249296529?thread_ts=1691559426.466079&cid=C01SKUP7QR0

**Comment by michaelhaxhiu** [comment]
I invited the friend of @0xmiroslav (who he told me via DM) to issue the $1k payment. Once that's accepted, I'll pay & close.

**Comment by michaelhaxhiu** [comment]
paid. closing.
