### ISSUE TITLE
DEV: message remains highlighted and does not opens options menu on right click of message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. right click on message

## Expected Result :  
should open modal which shows different options
## Actual Result : 
message remains highlighted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3 DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/578878f0-f61a-473d-80b0-9d555f552202

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684475847542959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment]
This is fixed already.
https://github.com/Expensify/App/pull/17477#issuecomment-1554434088

**Comment by luacmartins** [comment]
Ah thanks for letting me know. Gonna remove the label then.

**Comment by gadhiyamanan** [comment]
Am i eligible for reporting bonus as it is reported first in slack ?
Cc: @luacmartins

**Comment by gadhiyamanan** [comment]
i think it was first reported in slack
![Screenshot 2023-05-19 at 7 32 19 PM](https://github.com/Expensify/App/assets/54790231/7d3c4d1a-e920-47c0-9071-a50206fff28e)


![Screenshot 2023-05-19 at 7 32 51 PM](https://github.com/Expensify/App/assets/54790231/022a6085-12cb-474d-a73d-6c79b8ec802f)
