### ISSUE TITLE
Able to assign anyone when assigning a task in a private DM

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19297]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Select "Assign task"
3. Enter title and click "Next" 
4. Click assignee

## Expected Result:
In private DM should not be able to assign task to anyone

## Actual Result:
I can assign anyone, including people who aren’t in the room
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/a9d45351-a310-40a2-8452-f6d2dd902340" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/e9aba418-8d1c-4224-aed2-67cc76929622" width="40%" height="40%">

<img width="957" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/783540db-1165-450c-b73b-f70cfe9bb6f3">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @joaniew 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684311858049629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Can reproduce, asking in Slack if this is unexpected https://expensify.slack.com/archives/C049HHMV9SM/p1684836123565449?thread_ts=1684311858.049629&cid=C049HHMV9SM

**Comment by thienlnam** [comment]
Not a bug - expected! https://expensify.slack.com/archives/C049HHMV9SM/p1684863201382129?thread_ts=1684311858.049629&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment]
Thanks @thienlnam !
