### ISSUE TITLE
 LHN preview line is not updated when deleting a message in an `iou` report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. If you don't have any `iou` reports, request money from any user, it will create a new report for that request (format will be: "username owes $x" in the LHN)
3. Open the iouReport in the LHN
4. Send two messages in it
5. Observe that the LHN preview line updates immediately with each message you send
6. Delete the latest message and observe that the message you deleted remains in the preview message in LHN

## Expected Result: 
When deleting a message on an iouReport (or an expenseReport) it should also be deleted from the LHN preview line, just like messages in regular `chat` report types.

## Actual Result: 
Preview line in the LHN does not update when deleting a message until after a refresh.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes, refresh and it will update correctly. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/445d8d04-da3d-449b-9acb-4c6cb8dfb726

https://github.com/Expensify/App/assets/43996225/ab2ebf75-67f8-4423-95bd-e2c7103987e8

TRJ repro: 

https://github.com/Expensify/App/assets/16232057/5a8e93b0-0a17-4d64-bba8-d31531f4df41

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684307640342069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
@trjExpensify this got assigned after I went ooo - I will pick back up on Monday when I'm back

**Comment by luacmartins** [comment]
@trjExpensify yea, I'll address that on my delete PR.

**Comment by trjExpensify** [comment]
Okay cool, so just confirming we can close this then as it's a known issue? Reopen if I missed something!
