### ISSUE TITLE
Settings - 2FA - ‘Download’ is not translated into Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com or start App
2. Go to Settings > Preferences > Language > Select Spanish
3. Go to Settings > Security > Two-factor authentication
## Expected Result:
All text and all buttons on the page are in Spanish

## Actual Result:
‘Download’ button is not translated into Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Bug6061248_security-2FA-download-spanish](https://github.com/Expensify/App/assets/43996225/d776b853-31cd-4a7d-be4c-e42f8f6a4295)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment]
@michaelhaxhiu  please close this issue, this translation is being handled here  https://github.com/Expensify/App/issues/19187#:~:text=Missing%20Download%20translation%20in%20Spanish%20%2D%20https%3A//expensify.slack.com/archives/C049HHMV9SM/p1684406965776349
