### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] PrimayLogin is displayed on the ReportPreview message when a `displayName` has been set. 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
_Prerequisite: AccountB must have a displayName set in Avatar > Profile > Display Name_

1. Request money from accountA to accountB
2. In the DM between A:B observe that the report preview displays as: "[account B's primaryLogin] owes [amount]"
3. In the LHN preview line, observe that the report preview also displays as: "[account B's primaryLogin] owes [amount]"

## Expected Result:
When a displayName has been set, the report preview message should use the displayName of the person that owes. I.e "Tom Jones owes $50.00". Only if one hasn't been set should we fall back on using the primaryLogin. 

## Actual Result:
The primaryLogin is displayed on the report preview message even though a displayName has been set.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/04366844-1e1c-4e69-ab83-870c1d5d4903)
<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/e76d24e2-ea73-4e8d-8574-977b0f989335">

TRJ:
<img width="1496" alt="image" src="https://github.com/Expensify/App/assets/16232057/537969f9-9f6a-4f7b-9927-0f6d8802bc8e">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684312014916939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019dd2a8bc7f62d54a</li>
        <li>Upwork Job ID: 1660911889282371584</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Pretty sure this was intentional, and @Julesssss was looking at the handling of this.

**Comment by trjExpensify** [comment]
>but this seems like a different issues. The LHN message should be consistent, and the screenshots show us using two different formats.

Ah, I get it now. The preview and in the chat for the report preview we're displaying `primaryLogin`, when there's a `displayName` set. Yeah, I agree that's incorrect and good polish for manual requests. 

I can reproduce this on the latest staging: 
<img width="1496" alt="image" src="https://github.com/Expensify/App/assets/16232057/33f7f7de-4de3-4393-addd-5ce7e5346c31">

**Comment by trjExpensify** [comment]
Updated the OP and issue title a little to make this clearer.

**Comment by trjExpensify** [comment]
@Julesssss are you taking this on?

**Comment by trjExpensify** [comment]
That was @mountiny PR as well, so might have some additional context to provide.

**Comment by Julesssss** [comment]
Thanks Vit, I'm fine to stay assigned.

**Comment by Julesssss** [comment]
Cheers for the review approval tho.

**Comment by Julesssss** [comment]
@thesahindia could you please do a [final review](https://github.com/Expensify/App/issues/19301#issuecomment-1569939881) of this proposal?

**Comment by Julesssss** [comment]
> Because BE returns the lastMessageText including primaryLogin so it displays primaryLogin instead of displayName in LHN

I wonder if a better solution would be to fix this on the backend? I don't see why we wouldn't want to correctly set `lastMessageText` with the users display name? The only downside is that the `lastMessageText` wouldn't update to show the users new name if they change their display name, but that hardly seems like a problem to me.

**Comment by Julesssss** [comment]
Okay, that is a good point. I'd imagine that most messages are non-translateable messages rather than 'Jules requested $50.00 for kittens', but even then only some of the message would be trnaslatable. What do you think @mountiny and @trjExpensify ?

**Comment by trjExpensify** [comment]
@mountiny @Julesssss @thesahindia ^^ bump on the above question.

**Comment by Julesssss** [comment]
@trjExpensify we have been making progress and are close to merging

**Comment by mountiny** [comment]
yep we have been updating in the pr

**Comment by trjExpensify** [comment]
Great!

**Comment by Julesssss** [comment]
Deployed to staging, not yet deployed to prod
