### ISSUE TITLE
mWeb-WS-Unable to delete workspace from applausetester+disabledpolicy@applause.expensifail.com

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with [applausetester+disabledpolicy@applause.expensifail.com](mailto:applausetester+disabledpolicy@applause.expensifail.com)

3. Disable the internet connection in the device
4. Click/tap on the green plus button (FAB) and create a new Workspace
5. Navigate to Workspace settings
6. Verify the settings are grayed out indicating the workspace is pending to be created
7. Verify the default workspace rooms are created and are visible in LHN
8. Refresh the page and back online
9. Enable the internet connection in the device - in web you might need to refresh the page after going back online
10. Verify the workspace rooms aren't displayed in the LHN anymore
11. Verify that the account avatar in the LHN contains a red dot
## Expected Result:
Workspace rooms are displayed in the LHN and account avatar in the LHN not contains a red dot.
## Actual Result:
Workspace rooms aren't displayed in the LHN anymore and this account avatar in the LHN contains a red dot

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5a9b3f91-2f5a-469c-89a5-424ec712e156

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
@kavimuru A few thoughts on this report: 

- The reproduction steps don't seem to match up with the video. The video (and issue title) mention trying to delete a workspace, but the reproduction steps don't mention this at all. 
- Is this only reproducible on applausetester+disabledpolicy@applause.expensifail.com? Or is that just the account that you tested with? 

I'm going to close this for now, as it isn't presently actionable. If there is still a bug here, could you please review the issue, and make sure the reproduction steps exactly match the steps taken in the video and then clarify if this is something that can be tested with any account before re-opening the issue? Thanks!
