### ISSUE TITLE
User can not delete workspace, 'Delete workspace' button is not working.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19312]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start iOS / iPad App
2. Login with any accounts - gmail or expensifail.
3. Create workspace or goto new workspace.
4. Tap '2 dots' button and tap 'Delete workspace'

## Expected Result:
Workspace deleted. User is on the 'Create new workspace' page.

## Actual Result:
The user cannot delete the workspace. After clicking on 'Delete workspace', the application freezes. The workspace is not deleted.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native 
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a5ac4482-5a7c-45fe-8654-339324e510b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Going to fold this into https://github.com/Expensify/App/issues/19310
