### ISSUE TITLE
App is lagging when opening and closing DetailPage.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19329]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account, go to any report and scroll to top until you see the start of conversation.
2. Open detail page by clicking user avatar, click outside to close, after that click on user name to open Detail Page and click outside to close.
3. Repeat step 2 few times.
4. Notice that App is lagging while opening and closing Detail Page.

## Expected Result: 
App shouldn't be lagging while closing and opening Detail Page.
## Actual Result:   
App is lagging while opening and closing Detail Page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15.0
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/51cde91f-8665-4f49-a439-d3f82a693ad9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684318095611069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
@hungvu193 @kavimuru cannot reproduce.
