### ISSUE TITLE
Using a comma after mention doesn't display the blue highlight (but still recommendation is shown)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. Go to any chat
3. Type in @ and select any user
4. Now try to add comma just after the mention name without any space and notice that the blue color highlight disappears but the recommendation is still shown
5. Try to follow the same step with other special characters like dot, slash,dollar, brackets , add, subtract etc sign and notice that the mention suggestion disappears

## Expected Result:
Using a comma after mention should either hide the mention name in a similar way how adding other special characters does OR if a recommendation is shown then it should be highlighted in blue
## Actual Result:
Using a comma after mention doesn't display the blue highlight (but still recommendation is shown). Whereas for other special characters, the recommendation goes away.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/31af180b-e1a5-46fd-9459-d6af48949ffe

https://github.com/Expensify/App/assets/43996225/895cdd54-683a-4b3b-8286-5476ddf8e75d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684323901466969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment]
This issue should be handled in [this PR](https://github.com/Expensify/App/pull/19004) by add `,` to SPECIAL_CHAR_OR_EMOJI regex and MENTION_REPLACER regex
cc @allroundexperts @sakluger

**Comment by sonialiap** [comment]
Thanks @dukenv0307!

**Comment by sonialiap** [comment]
Resolved by https://github.com/Expensify/App/pull/19004

Tested on staging

https://github.com/Expensify/App/assets/17131195/7bc403a5-4e62-41db-a030-a31d6cfc11d7
