### ISSUE TITLE
PAY 06/01 'Report no longer exists' error is displayed when trying to chat with a phone number using the share code URL

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19344]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with your phone number
2. Go to Settings > Share code
3. Click Copy URL to clipboard
4. Next, sign in with some other account
5. Paste and go to the copied URL
6. Click on Message

## Expected Result:
No error is displayed
## Actual Result:
'Report no longer exists' error is displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/90c0606e-577c-4310-a486-f022b76d1db7

https://github.com/Expensify/App/assets/43996225/ce5fcbb2-83a1-4255-a319-9a114d4333a5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684351944659109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Checking in with the contributor providing the solution over in https://github.com/Expensify/App/issues/19076 to confirm this problem will be solved via that solution

**Comment by bfitzexpensify** [comment]
OK, contributor confirmed, we can close this out.

**Comment by bfitzexpensify** [comment]
Hi @adeel0202, yes, I think that is reasonable. I invited you to a reporting job on Upwork. I've subscribed to https://github.com/Expensify/App/issues/19076 and will pay out once that's complete.

**Comment by bfitzexpensify** [comment]
Going to reopen this to help me monitor that payment, too.

**Comment by bfitzexpensify** [comment]
https://github.com/Expensify/App/issues/19076 has been merged, waiting for 7 days post deployment to prod

**Comment by bfitzexpensify** [comment]
Payment on 06/01

**Comment by bfitzexpensify** [comment]
Payment on 6/1, not overdue

**Comment by gadhiyamanan** [comment]
@bfitzexpensify this issue is not eligible for reporting bonus as per https://github.com/Expensify/App/issues/19076#issuecomment-1562256495
cc: @tjferriss

**Comment by bfitzexpensify** [comment]
Thanks for letting me know @gadhiyamanan. Going to close this issue out.

**Comment by bfitzexpensify** [comment]
Sure @adeel0202, I've done that now
