### ISSUE TITLE
@expensify.sms is displayed next to the phone number in the user profile details

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19346]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with your phone number
2. Go to Settings > Share code
3. Click Copy URL to clipboard
4. Open a new tab
5. Paste and go to the copied URL

## Expected Result:
@expensify.sms is not displayed next to the phone number
## Actual Result:
'@expensify.sms is displayed next to the phone number
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d72e7058-e2c7-4c0c-a10d-20fe040bb58e

<img width="958" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/cefed398-dcc8-45ff-a104-2f75e339e18a">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684353586002219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@robertjchen - since you're assigned to https://github.com/Expensify/App/issues/19076, just confirming that your issue will resolve this one? If so, could we close this one? Thanks!

**Comment by robertjchen** [comment]
Hm, this is a bit different- we should be excising the `@expensify.sms` part and we discussed it a bit here: https://expensify.slack.com/archives/C049HHMV9SM/p1684739607316259

I'll take a look at this one 👍

**Comment by jliexpensify** [comment]
Thanks @robertjchen - just assigned you to this, LMK if you want it moved to External.

**Comment by jliexpensify** [comment]
Yep, @adeel0202 you get the $250 - will send you an invite on Upworks.

**Comment by jliexpensify** [comment]
Ok so Upworks won't let me reuse any Job posts, so have to drop the External label - sorry! Will unassign the C+.

**Comment by jliexpensify** [comment]
Cool, tag me when you've accepted and I'll pay ASAP.

**Comment by jliexpensify** [comment]
Paid and Upworks job closed, cheers!
