### ISSUE TITLE
When sending a thread message and then deleting it, the message temporarily disappearing and LHN not updating

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Opened a chat
2. Sent a message to the user
3. Clicked on "Reply in thread" and write a message on the thread
4. Return back to the chat
5. Delete the thread message

## Expected Result:
The deleted thread message should not disappear temporarily and LHN should update
## Actual Result:
When sending a thread message and then deleting it, the message temporarily disappearing and LHN not updating after deleting it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/50e42c6f-8e2b-464e-a6ac-d9158665d3e3

https://github.com/Expensify/App/assets/43996225/44e04121-7d26-41e7-8650-042a2aeb7370

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684354260051229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Bumped @chiragsalian in thread and dropped him a quick DM.

**Comment by chiragsalian** [comment]
Discussing on [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1685487920234439?thread_ts=1684354260.051229&cid=C049HHMV9SM).

**Comment by trjExpensify** [comment]
Closing the loop. This is expected behaviour. The issue with being able to delete a deleted message is a separate bug report, already reported here: https://expensify.slack.com/archives/C049HHMV9SM/p1684412217524939

**Comment by ayazhussain79** [comment]
@trjExpensify the main bug was here "When sending a thread message and then deleting it, the message temporarily disappearing" which is still reproducible

**Comment by trjExpensify** [comment]
Commented in the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1685965494942699?thread_ts=1684354260.051229&cid=C049HHMV9SM), we can centralise any additional clarifications there.
