### ISSUE TITLE
when you add an assignee to a task, then edit the description and save, the assignee changes to _fake_

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign into [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Click '+' > assign a task
3. Assign it to a user
4. Click Confirm Task
5. Click the description for the user
6. Add more text, then save
7. See that the assignee has changed to _fake_

## Expected result: 
the assignee remains the same after changing the description

## Actual result: 
the assignee changes to _fake_

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7b8e78f2-27dd-4be9-bdbb-9a38f38290ca

https://github.com/Expensify/App/assets/43996225/0b7364b8-09a1-421b-a511-18c99fef4435

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684349723299479
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @thienlnam 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01021aafb4470cdf48</li>
        <li>Upwork Job ID: 1660769614666272768</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can replicate this but I'm not sure if it needs to be internal... assigning eng.

**Comment by thienlnam** [comment]
This is done - back end changes are deployed

**Comment by Christinadobrzyn** [comment]
Awesome, I closed the Upwork job as we didn't use any external contributors for the fix. Let me know if I'm missing someone!
