### ISSUE TITLE
[HOLD for payment 2023-06-01] [HOLD for payment 2023-05-29] composer height is bigger in Android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Notice the composer height is bigger compared to other platforms

## Expected Result: 
Composer in Android should have the same height as in other platforms
## Actual Result: 
Composer in Android has bigger height

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/99595657-3a8d-4b94-a9b7-0f3e3e90a5b7" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/b144f483-7992-47de-9c54-f18d25bcd31e" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
I think it's a regression of this https://github.com/Expensify/App/pull/19096, specifically the `textInputCompose` padding is changed to 9 from 0
https://github.com/Expensify/App/pull/19096/files#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253ebR1546-R1554

**Comment by mountiny** [comment]
@dukenv0307 Are you able to fix this regression?

**Comment by mountiny** [comment]
Made a revert PR @rushatgabhane

**Comment by mountiny** [comment]
This is being CPed to staging

**Comment by mountiny** [comment]
@stephanieelliott This is ready for payment to @bernhardoj for reporting, otherwise I believe we should be good as Paulo has tested the PR internally

**Comment by situchan** [comment]
I reported another bug [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684702884273809) with different symptom but offending [PR](https://github.com/Expensify/App/pull/19096) was same.
It was reported before this GH was created so I think I am also eligible.

**Comment by stephanieelliott** [comment]
Not overdue, payment is due on 6/1!

**Comment by stephanieelliott** [comment]
Extended the offer on Upwork, please accept when you get a chance @bernhardoj @situchan https://www.upwork.com/jobs/~013d274bb30ac566e0
