### ISSUE TITLE
Two-Factor section step 2 shows chat for a fraction of seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19367]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the Settings
2. Security
3. Two-factor authentication
4. Click next in step 1
5. Click placeholder in step 2
6. Notice chat appears for a brief time

## Expected Result:
In Two-Factor step 2 chat shouldn't appear for fraction of seconds while clicking on placeholder.
## Actual Result:
In Two-Factor code step 2 chat appears for fraction of seconds while clicking on placeholder
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome (Realme 3 )
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2cd498fc-6b7c-433f-b571-9142adf6f7b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684394792579709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
I am going OOO so re-assigning for a buddy to watch while I am away 💌

**Comment by tjferriss** [comment]
I'm not able to reproduce this one. 

Uploading Screen Recording 2023-05-25 at 21.38.09.mov…

**Comment by tjferriss** [comment]
I'm not able to reproduce this one. 

https://github.com/Expensify/App/assets/8292562/13d3963a-9801-4502-aca7-fa795f8fd560
