### ISSUE TITLE
 In Two-Factor section step 2 on deleting added code flickers the screen.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the Settings
2.  Security
3.  Two-factor authentication
4.  Click next in step 1
5.  Click placeholder in step 2
6. Observe while adding code the app works smoothly
7.  Notice on deletion of added code leads to flickering effect

## Expected Result:
In Two-Factor step 2 like adding, deletion of added code should work smoothly.
## Actual Result:
In Two-Factor code step 2 on deletion of added code leads to flickering effect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d22388e2-13f3-473c-9609-d2a0cdbce707

https://github.com/Expensify/App/assets/43996225/0a890441-6ff6-4f0e-8ddb-8afe56ad56f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684398148705739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
We have a similar issue which get closed [here](https://github.com/Expensify/App/issues/16063#issuecomment-1491659168)

**Comment by tjferriss** [comment]
I'm closing this issue in favor of https://github.com/Expensify/App/issues/19367 which was reported earlier.
