### ISSUE TITLE
Implement Performance Regression Testing with Reassure

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19376]
### Problem

Coming from [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1678890332697469), this is a new feature handled by Callstack.

As the Expensify application continues to grow and evolve, it’s essential to ensure that new updates and changes don’t introduce unintended side effects or break existing functionality. However, it’s all too easy to inadvertently introduce performance regressions that would be caught in production when the app starts to run slowly.

Currently, the project implements automated end-to-end performance tests, which are more reliable than Reassure because they include both JS and native.The problem with these tests is that there are few of them, they take a long time to complete, and it’s hard for developers to add new tests.

Reassure should supplement these basic tests with a more extensive set of performance tests that work only in JS, focusing on problems arising from excessive re-renders and memoization errors.

### Solution

Let's implement some simple component rendering tests using Reassure library as MVP and we can build more usecases on top of that. We will start with SidebarLinks test.

**Comment by mountiny** [comment]
@isabelastisser No need to action here for now, thank you!

**Comment by isabelastisser** [comment]
not overdue.

**Comment by isabelastisser** [comment]
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by mountiny** [comment]
Arek is ooo for two weeks so no progress here

**Comment by tjferriss** [comment]
I'm guessing Arek is still out. It looks like we'll pick this back up next week.

**Comment by mountiny** [comment]
@tjferriss nothing for now, I believe we might need some C+ payments in the end but I would ping you if that would be the case

**Comment by mountiny** [comment]
This project has actually been completed, the testing suite is set up and we can build on top of it. 

The next would be follow ups we need to identify what would be the most valuable components to catch using this suite

**Comment by mountiny** [comment]
@tjferriss there is nobody to pay here so i think i will just go ahead and close this one out, thanks for help
