### ISSUE TITLE
[Navigation Refactor] - Web - Chat - Focus is not automatically set to input field when user selects chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://19263.pr-testing.expensify.com/
2. Open any chat in chat list
3. Press CMD+K
4. Open any chat in chat switcher by clicking on it / pressing Enter / CMD+Enter

## Expected Result:
At step 2,4 when user opens new chat - the chat input field is automatically focused and highlighted

## Actual Result:
At step 2,4 when user opens new chat - the chat input field is NOT focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/c018c73de4eeff73bbf185dd4c28883bc20b2089cf2ac7146b815310c49ee652

https://platform.applause.com/services/links/v1/external/2f32a90c59bde6b9240681d6c3cf1fc984746ce992308844ac9559ec71e7c7e5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Fixed
