### ISSUE TITLE
Email isn't persisted if user reload the Login page and press back.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open login page.
2. Enter any email and press Next.
3. Reload the page and press Back.
4. Notice the email field isn't persisted.

## Expected Result : 
Email should be persisted.
## Actual Result : 
Email should is not persisted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1cf45dbb-f7c4-4acb-8725-66b3c60f4ca5

https://github.com/Expensify/App/assets/43996225/6dab362e-007f-471c-b27c-3fc9eda04c01

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684469185037239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
Proposal from @hungvu193 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Email isn't persisted if user reloads the Login page and press back.
### What is the root cause of that problem?
In LoginForm we're using state for email field, because of that when we reloaded it will be cleared.
### What changes do you think we should make in order to solve the problem?
Migrate LoginForm to use Form  component and add shouldSaveDraft, inputId to username TextInput component. (Also remove unnecessary props).
### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment]
[I'm heading OOO tomorrow](https://expensify.slack.com/archives/C01SKUP7QR0/p1684776773511559) for about a week so adding another BZ member while I'm away to help keep the train moving! 🚂 Thanks @isabelastisser

**Comment by isabelastisser** [comment]
I don't think this is a bug; this is expected behavior. The email should disappear when you reload the page and return to the main page for a new login.
