### ISSUE TITLE
[Navigation Refactor] -Send/Request/Split - Click on "Back" from amount screen closes the side menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://19263.pr-testing.expensify.com/
2. Click on FAB + icon
3. Click on Send money / Request money / Split bill
4. Insert the amount
5. Click on "Next"
6. Select a user
7. Click on "Amount" field to modify it
8. Click on "Back arrow"

## Expected Result:
User lands back in "cash" tab with request details preserved

## Actual Result:
Side menu closes after user clicks on "Back arrow"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/ec60c286625fe846abdf39b11fb45e304f4b5822bfbea6948ffc2acdf3504d9a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by staszekscp** [comment]
I've just pushed a fix for it :)

**Comment by mountiny** [comment]
Fixed
