### ISSUE TITLE
[Navigation Refactor] - Chat - User is transferred to new tab if click on concierge link in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition - Concierge link was sent to a chat - https://19263.pr-testing.expensify.com/concierge
1. Open https://19263.pr-testing.expensify.com/
2. Open chat from the precondition
3. Click on the concierge link

## Expected Result:
User is transferred to the concierge chat within the same tab

## Actual Result:
User is transferred to the concierge chat in a new browser tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
https://expensify.testrail.io/index.php?/tests/view/3466263

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/aceb4cc93d54b0289ccbe79c49b2a8059f038fb4f850333b979629d0d0ae1572

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I believe this is related to the url matching logic and it should be fine on staging/ production

**Comment by staszekscp** [comment]
Yep, I've just checked and https://staging.new.expensify.com/concierge opens the chat correctly :)

**Comment by mountiny** [comment]
Nice, thanks, closing this one
