### ISSUE TITLE
redirects to authenticator code screen again when user clicks go back to change email when 2FA enabled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open login page.
2. Enter email which has 2FA enabled
3. click continue button
4. enter magic code
5. press Go back from authenticator code screen

## Expected Result : 
should remains on enter email screen to change email id
## Actual Result : 
redirects to authenticator code screen again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d4d81fc7-19d1-45a6-b057-6400d5668fe5

https://github.com/Expensify/App/assets/43996225/d9007f40-c70b-4278-ae00-1e540e3a595d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684473360048959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
I cannot reproduce this on the latest staging version:
![2023-05-25_23-07-45 (1)](https://github.com/Expensify/App/assets/9133401/8e54bf9a-5e65-418a-b379-82df8f07b804)

v1.3.18-2, Chrome.

@gadhiyamanan - can you still reproduce?

**Comment by gadhiyamanan** [comment]
@twisterdotcom with the latest version it shows an incorrect magic code error on enter email screen

https://github.com/Expensify/App/assets/54790231/d33ff460-26ad-4f4e-878e-197260f38ec9

**Comment by twisterdotcom** [comment]
>with the latest version it shows an incorrect magic code error

Yup, agree. That is different to what this issue was for though. Previously, it just took you to the Two Factor Code screen. I'm am confirming this doesn't happen any more.

I do agree, it remains a confusing flow though. Let's report and also CC Monil who helped build 2FA.

**Comment by twisterdotcom** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1685094475642229
