### ISSUE TITLE
[Navigation Refactor] - Attachment - "Failed to load PDF file" message appears after send the PDF file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the URL https://19263.pr-testing.expensify.com/
2. Login with any account
3. Open any chat
4. Send PDF file

## Expected Result:
The PDF file should be displayed 

## Actual Result:
"Failed to load PDF file" message appears after open the PDF file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:**  special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/b7f05a5b9fd17c8fbdbb65f017586a8944af20ebc56f33e15996ba96689911b1

https://platform.applause.com/services/links/v1/external/f33162cdab923e320b795aeda2137f3cbeaa0be64fb243d77b4eae2c5ed5ac8d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I believe this one is unrelated to the refactor

**Comment by therealsujitk** [comment]
I've faced this issue too, when I uploaded a new PDF all the other ones got fixed.

**Comment by mountiny** [comment]
Not repro on the latest version
