### ISSUE TITLE
 Including a code block inside a heading shows the '#' and code block on separate lines.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log into an account and open a chat.
2. Type the following message in the composer and send.
3. #```Some heading in a code block```

## Expected Result:
There are 3 possible scenarios:
[Ignore the 3 backticks and display the text as is styled as a heading](https://github.com/Expensify/App/issues/14100#issuecomment-1404371634) like what happens with quotes in a heading.
Show a code block styled as a heading like GitHub does (see attached screenshot)
Display the text all on the same line as regular text i.e. no heading styles applied.
## Actual Result:
The '#' and code block are shown on separate lines.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f5356ef5-d20c-47e6-a5f3-a5df1c93c7f9

https://github.com/Expensify/App/assets/43996225/f1d86582-6520-4945-8bd4-b21ac2d1dbbf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684486639025769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
I'm going to start with adding just the engineer first so it can be decided which option fits best - 

**Expected Result:**
There are 3 possible scenarios:

- https://github.com/Expensify/App/issues/14100#issuecomment-1404371634 like what happens with quotes in a heading.
- Show a code block styled as a heading like GitHub does (see attached screenshot)
- Display the text all on the same line as regular text i.e. no heading styles applied.

**Comment by iwiznia** [comment]
IMO this is not a bug and intebded, you can't combine those 2 formatting options.
