### ISSUE TITLE
message and 'you' text are not vertically aligned when replying to mention with thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with account A
2. Open an existing chat with account B
3. Mention account B in chat
4. Switch to tab where account B is signed in
5. Open message from account A
6. Hover over the mention
7. Click on 'Reply in thread' icon
8. Send message
9. Observe the LHN

## Expected Result:
 'you' and the replied comment should be vertically aligned
## Actual Result: 
'you' and the replied comment are not vertically aligned

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/8b2891b7-3b2d-43da-a49d-e22bd4ca035f)

https://github.com/Expensify/App/assets/43996225/e55ae00f-dd35-426e-9755-fb1c3a28b9a3

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/ff6aa545-6045-49cb-b8e6-9f7e5ec2a4fe">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684485031519269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
<img width="1440" alt="Screenshot 2023-05-22 at 10 14 46 PM" src="https://github.com/Expensify/App/assets/59907218/f35645e5-f410-4845-a3c1-9dd7bdc265e7">
Looks like backend is sending it with space like this ` you`

**Comment by kevinksullivan** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1684869052525249?thread_ts=1684485031.519269&cid=C049HHMV9SM
