### ISSUE TITLE
[Navigation Refactor] - Web - Split bill - IOU preview is not showing in Special account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Sign into a valid account ([emilio.utest@gmail.com](mailto:emilio.utest@gmail.com)
account)
3. Click on "+" > Split Bill
4. Complete the Split Bill flow

## Expected Result:
User expects to be redirected to the DM with the participants and see an IOU preview with the details

## Actual Result:
User is redirected to the DM but the preview does not show for this specific account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** [emilio.utest@gmail.com](mailto:emilio.utest@gmail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/c0157ebc5263f44171bba2b4d921bed0f8916a8fae88efa33968bed60971d1d1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@kbecciv can you confirm this is still a thing in the special account?

**Comment by kbecciv** [comment]
@mountiny Issue is no longer reproduced

https://github.com/Expensify/App/assets/93399543/3c0f29f9-4c9d-4863-8c1a-dbbd12ed2c9c

**Comment by mountiny** [comment]
Thanks
