### ISSUE TITLE
[Navigation Refactor] - Chat - "You don't have access to this chat" appear after clicking the back back button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open special build link https://19263.pr-testing.expensify.com/concierge
2. Login with existing account
3. Close the error message appear on the Concierge chat
4. Tap the back button

## Expected Result:
LHN / Chat view to appear

## Actual Result:
"You don't have access to this chat" appear after clicking the back back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/4b2b00cab642454187e4f1768168c26f33b800273eae2954a2bdc639899f6fcb

https://platform.applause.com/services/links/v1/external/22381d656dae55a3229648ac561335cf463b56e0524563334b78fd11a8cd6021

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
> Close the error message appear on the Concierge chat

@kbecciv How did you close it? I have not seen any click in the video

**Comment by kbecciv** [comment]
@mountiny Please attached the video with external device for this issue. 

https://platform.applause.com/services/links/v1/external/c0c68ca8ddf809ed323279a1f4ef3241510857b4d73fb69ff0bfb5c4380c0df8

**Comment by mountiny** [comment]
This should have been resolved in main by a PR which fixed duplicated concierge chats.
