### ISSUE TITLE
[Navigation Refactor] - Attachment - Missing "Cancel" button when open the attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://19263.pr-testing.expensify.com/ 
2. On a conversation, click on the + button in the compose box.
3. Click on add attachment.
4. Open an attachment.

## Expected Result:
"Cancel" button should be visible when open the attachment

## Actual Result:
Missing "Cancel" button when open the attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/6a83020965abf45bdb0385c708ea5d2c56223a146ebdba0e0989af19806066f9

https://platform.applause.com/services/links/v1/external/4451f6a4265e44afb3fff164e1c04d669a8f99884d15e2ae9d087e7f62f6a7cf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is intended, @kbecciv can you confirm you can close the modal just fine with the `<`?

**Comment by kbecciv** [comment]
Yes, able to close the modal with <

https://github.com/Expensify/App/assets/93399543/60f45c73-1867-4f99-a7f2-759bcc6bbe53

Is it expected to have Cancel button in Web?

**Comment by mountiny** [comment]
@kbecciv No X button should be present in the app anymore

**Comment by kbecciv** [comment]
Thank you @mountiny

**Comment by mountiny** [comment]
I will close this one out, thanks!
