### ISSUE TITLE
[Navigation Refactor] - New Room/Request/Split/Send -Tapping Back navigation after room is created, restarts the "Create Room"/Request/Split/Send flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to a HIGH TRAFFIC (Expensifail) account.
2. Tap on the green plus button (FAB)
3. Select "New room" option
4. Complete new room creation flow.
5. Tap in "Back" button on top left corner.

## Expected Result:
The user should return to LHN

## Actual Result:
Tapping back arrow, the creation room flow will reopen. after new room is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/d16c1f1b03fd55d2b763d2eb812b20377386cc98aa5bdb336ec57f994d55c839

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by WoLewicki** [comment]
I can see there are more options for navigating from RHP to a report screen. Do we want the behavior of always replacing the RHP with the new report? If not, could you list all the exact flows that would need to be handled? cc @mountiny @kbecciv

**Comment by mountiny** [comment]
- all of these flows 
<img width="349" alt="image" src="https://github.com/Expensify/App/assets/36083550/0ca1a0d0-214d-42c9-976d-0f31ad0bb0dd"> when finished then we should dismiss

- new chat - when selected the email - dismiss and navigate to the report
<img width="1120" alt="image" src="https://github.com/Expensify/App/assets/36083550/ec5e627c-8dbc-4adc-9499-ebf066020bc6">

- new group - Create new group - dismiss and navigate to the report
<img width="1125" alt="image" src="https://github.com/Expensify/App/assets/36083550/54ed1f1e-a2e1-4764-8611-12a621d1f9eb">

- new room - Create room - dismiss and navigate to the report
<img width="1447" alt="image" src="https://github.com/Expensify/App/assets/36083550/e66ef6e4-380b-4160-852f-0fee742d4b26">

- all the iou flows and assign task - once you are at the end with the green button - dismiss and navigate to the report
<img width="1448" alt="image" src="https://github.com/Expensify/App/assets/36083550/8dea8bc5-7b29-4819-a75c-e0160fec9962">

- Settings > Profile > Any of those forms / Personal Details and any of those forms there should I believe dismiss "the form stack" on Save 
<img width="709" alt="image" src="https://github.com/Expensify/App/assets/36083550/f1b8c45c-9bde-4d4d-88e9-b8df08ccdce2">

So I see that if we update the personal details name we used drawerGoBack [here](https://github.com/Expensify/App/blob/5cb2b745c52cedb0fd7ae64c0c438953a7d952b0/src/libs/actions/PersonalDetails.js#L118-L147), could we just pop the last screen in this case? 

I think we dont have to catch all of these flows in the first PR. We can ideally find a good solution we can then apply to the other flows we find.

**Comment by mountiny** [comment]
This was fixed
