### ISSUE TITLE
[Navigation Refactor] - IOS - App crashes when opening a chat with a draft message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS App and login with any account
2. Open any chat
3. Go Offline
4. Write message but do not send it and return to LHN
5. Close app, go online and open app again
6. Open chat with draft message from #4

## Expected Result:
Chat opened and draft message is in composer

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/eff2faca59625bfa3a3a5c36a6c06a8e656fa224f1f52bae409cd58da784ea56

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@kbecciv is this not repro on staging?

**Comment by kbecciv** [comment]
@mountiny There is issue on staging

https://github.com/Expensify/App/assets/93399543/4b2f3cb8-26fd-4521-a56f-c6e829af2dcb

**Comment by mountiny** [comment]
> @mountiny There is issue on staging

@kbecciv based on the video it seems like the app did not crash :D

**Comment by kbecciv** [comment]
@mountiny Very sorry, no issue on staging.

**Comment by mountiny** [comment]
Could not reproduce anymore
