### ISSUE TITLE
[Navigation Refactor] - Web - Chat - Not possible to drag and drop attachments to the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19424]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the testing app (special build)
2. Open any chat
3. Try to drag and drop an image from local computer to the composer

## Expected Result:
User should be able to upload an image attachment to the conversation via the drag and drop. A modal should appear once the image is dropped in the chat.

## Actual Result:
Nothing happens, no modal shows up. User is unable to drag/drop an image to the composer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Special build 1.3.16.5

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/58eb7843bdd2756af3c9a8f9cc45f8dff1a274a881b5685dda05c59842e3223a

https://platform.applause.com/services/links/v1/external/d65e4494704995b1470aaca5440abfecb3f2befe42ccdb0dca8ed6dcaf979ae9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This was fixed
