### ISSUE TITLE
Redirect users to sign in on oldDot when SAML is required

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#19423]
## Action Performed:
1. Create an account on expensify.com that has a validated domain 
2. Require SAML on the domain 
3. Navigate to new.expensify.com and try to sign in 

## Expected Result:

1. User should be directed to log in on expensify.com 

## Actual Result:

1. User receives a magic code and attempts to log in with it
2. App displays an `Auth Authenticate returned an error` error message
3. Network request shows `418 Magic code based authentication is disabled for this user`

## Workaround:

N/A - at this time SAML required users cannot log in on new.expensify.com unless they go through oldDot and and click on the concierge link 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.16-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C048ZLJ78P5/p1684529407009859 (internal link) 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc6c56c69620b45b</li>
        <li>Upwork Job ID: 1660811940540665856</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by NikkiWines** [comment]
@adelekennedy sorry, no action required by at this time for you - this is an internal issue

**Comment by NikkiWines** [comment]
same actually for you @mollfpr - there'll only be an internal PR for this I believe. Sorry for the noise!

**Comment by laurenreidexpensify** [comment]
@NikkiWines so just to confirm - is the trigger that if they start a chat with Concierge it will open up in New Expensify?

**Comment by NikkiWines** [comment]
That's right! Clicking on the concierge icon in oldDot now routes the user to newDot, so it's the easiest way to allow SAML-required users to access newDot without having them go through the newDot login flow

**Comment by laurenreidexpensify** [comment]
Okay copy looks 👍

**Comment by NikkiWines** [comment]
Great, thank you!

**Comment by laurenreidexpensify** [comment]
This was deployed to prod 2 weeks ago right @NikkiWines = should we close?

**Comment by ericevenchick** [comment]
We are experiencing this error when inviting a new user via email. When following the link provided by email, they received the `Auth Authenticate returned an error` error. The workaround is to go to https://old.expensify.com, but there is no text to explain this.
