### ISSUE TITLE
[$1000] Clicking on "send message" or the "concierge" icon in the in the "explore help docs" using the mobile web version opens the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Open app
 2. Open workspaces and select one workspace
 3. Click on the "?" button at the top right corner
 4. Click on "explore help docs" button
 5. Click on "send message" button or the concierge icon

## Expected Result:
Clicking on either buttons should immediately open the chat page with concierge on the web platform, for the account that was logged in

## Actual Result:
User is redirected to the app if one is installed on the device and chat with concierge is opened even if the logged in account is different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4f8d0da1-e28a-4f7e-ae28-a2ee5ad37cd5

https://github.com/Expensify/App/assets/93399543/9ba530da-279f-4e31-85d1-33d084d72a2f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684417113803759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b7ec77afdd817fd</li>
        <li>Upwork Job ID: 1661085190586290176</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by flodnv** [comment]
agreed
