### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] LHN logic for threads is wrong (inconsistent with other chats)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat room (non-DM)
2. Thread a message in that chat

## Expected Result: 
The thread appears in the LHN with a preview of the message threaded, followed by the most recent message in the thread.
## Actual Result: 
The thread appears in the LHN with a preview of the message threaded, followed by the workspace name and room name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-19 at 15 31 09](https://github.com/Expensify/App/assets/43996225/d7750d75-08f7-4e5c-8d70-433386293f50)
<img width="955" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/599fe17a-208d-493c-be84-8c768e5017ab">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684503061244619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01422c3862e47a029f</li>
        <li>Upwork Job ID: 1661857447696506880</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
Started looking into this. Right now we are showing the same thing for the header and the lhn which is not intended. This can be external.

**Comment by stitesExpensify** [comment]
cc @aimane-chnaif ^

**Comment by ShogunFire** [comment]
Looks like it was wanted here https://github.com/Expensify/App/issues/18755 , but I don't have access to the word so I don't know why. Here is the PR: https://github.com/Expensify/App/pull/18522

**Comment by tjferriss** [comment]
@aimane-chnaif @stitesExpensify what is the next step here? What do you think of @hoangzinh proposal?

**Comment by stitesExpensify** [comment]
This is what the doc says:

LHN:
<img width="901" alt="2023-06-02_11-08-58" src="https://github.com/Expensify/App/assets/42391420/38847a11-cdcd-4a45-80fe-5be228691eb3">


Header:
<img width="414" alt="2023-06-02_11-09-07" src="https://github.com/Expensify/App/assets/42391420/1e38fae0-e5da-4b65-abe5-f87312da85a4">

**Comment by tjferriss** [comment]
>I asked confirmation here - https://github.com/Expensify/App/pull/18522/files#r1212295913 to avoid any regression.

So reading that thread, it looks like the expected result here is correct.

**Comment by stitesExpensify** [comment]
Makes sense to me

**Comment by tjferriss** [comment]
@hoangzinh @aimane-chnaif I've sent you both an offer in Upworks. You're both eligible for the 50% speed bonus.

@aimane-chnaif can you get started on the checklist?

**Comment by tjferriss** [comment]
Everyone is hired in Upworks. We just need to complete the checklist and pay everyone out after the regression period.

**Comment by tjferriss** [comment]
The payments have been sent via Upworks. @aimane-chnaif can you please complete the checklist?

**Comment by tjferriss** [comment]
Regression test has been created https://github.com/Expensify/Expensify/issues/295396
