### ISSUE TITLE
[$1000] Markdown to HTML Conversion Issue with Code Blocks

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Copy the following text (including code block and surrounding text):
text  ```
some text
```
code block
````
 2. send it to Slack or GitHub message or any app that accepts markdown
 3. copy the text from the message.
 4. past it to Expensify composer
 5. send the message to Expensify.
## Expected Result:
The text "hi" and "some text" should be rendered as normal text, and the code block should be rendered as a separate code block. The code block delimiters (```) should be treated as normal text and not trigger the code block formatting.
## Actual Result:
When the message is sent and rendered in Expensify, "some text" are incorrectly rendered as part of the code block. The code block text and the code block delimiters (```) are not recognized as intended, leading to the incorrect formatting of the message.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:**y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0bf30e11-0b9c-4bbb-b987-410a53fb12a1

https://github.com/Expensify/App/assets/43996225/36e7ef75-773b-48d0-b66c-b9fe45c1e4cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684316680405429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2c3f62fe6eee04f</li>
        <li>Upwork Job ID: 1661561925969117184</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
Proposal: Improve Code Block Matching in Regex
Issue:
The current regex used to match code blocks in our Markdown to HTML conversion process does not check if the opening and closing backticks (```) are on separate lines. This leads to incorrect rendering of code blocks when copying and pasting from external sources.
Current Regex:
regex

/(&#x60;&#x60;&#x60;[\n]?)((?:\s*?(?![\n]?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?)((?=\n?)&#x60;&#x60;&#x60;)/g 
Proposal:
To address this issue, I propose enhancing the regex pattern by adding a check to ensure the opening and closing backticks are on separate lines. This will help us achieve consistent and accurate code block rendering. The proposed modification is as follows:
regex

/(?<=\n|^)(?<!\S)(&#x60;&#x60;&#x60;[\n]?)((?:\s*?(?![\n]?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?)((?=\n?)&#x60;&#x60;&#x60;)/g 
Explanation:
The proposed change uses a positive lookbehind (?<=\n|^) to ensure that the opening backticks are preceded by a newline character or the start of the input. Additionally, a negative lookbehind (?<!\S) is added to ensure there are no non-whitespace characters immediately before the opening backticks. This ensures that the opening backticks are on a separate line.
By incorporating these modifications, the regex will accurately match code blocks based on the expected Markdown convention of having the opening and closing backticks on separate lines.
Please review and consider implementing this proposed modification to enhance the accuracy and consistency of code block rendering in our Markdown to HTML conversion process.
Thank you for your attention to this matter.

**Comment by arielgreen** [comment]
External

**Comment by hasti** [comment]
I Just grab the latest copy and found that the above issue doesn't exist its working fine.

![New Expensify (1)](https://github.com/Expensify/App/assets/140922/9e76236b-1e68-4112-9519-ca11c27e28d7)

**Comment by zanyrenney** [comment]
Don't think this should have assigned me!

**Comment by arielgreen** [comment]
Reassigning, OOO tomorrow/Monday.

**Comment by Beamanator** [comment]
Bump @abdulrahuman5196 - please review the proposal when you get a chance today

**Comment by abdulrahuman5196** [comment]
@Beamanator  Main concern is after pasting the message in expensify, it looks like the below
<img width="996" alt="Screenshot 2023-05-28 at 1 19 21 PM" src="https://github.com/Expensify/App/assets/46707890/595f0016-b166-4740-aba7-77645582ec23">

When we send the message, our markdown considers the first two set of code backticks as code block and uses it to render `some code` as code block not the second hi text.


Do we think this is worth solving? IMO it feels more like a reverse engineered issue trying to break the code than if it will have any customer impact. Just wanted to check on team's stand on this before going further?

**Comment by abdulrahuman5196** [comment]
@ahmdshrif Regarding the proposal here https://github.com/Expensify/App/issues/19446#issuecomment-1559527483 I don't think limiting the code block backticks to be on seperate lines will solve the issue totally.
For ex, consider the below case. The backticks are present in separate lines but even if we copy paste with the proposal, `some text` will be marked as code block.

<img width="399" alt="Screenshot 2023-05-28 at 1 26 18 PM" src="https://github.com/Expensify/App/assets/46707890/7fbac882-cb0f-4736-8770-f235b7dad3cd">

**Comment by jliexpensify** [comment]
Bump @abdulrahuman5196

**Comment by Victor-Nyagudi** [comment]
I think this other [issue involving using 6 backticks in a code block](https://github.com/Expensify/App/issues/17196) is worth mentioning here.

[A conversation was started in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684840420322509) about the expected outcomes and edge cases when writing code blocks, and it was decided nothing would be done. 

This bug could be considered as one of the edge cases, but I may be wrong, so I thought I'd bring it your attention. 

cc: @Beamanator @jliexpensify

**Comment by Beamanator** [comment]
@Victor-Nyagudi thanks for linking that issue, very useful!! I agree this seems like a very random edge case that doesn't necessarily need to be fixed. Though I think it makes sense to keep issues like these in mind for the future so that we can maybe fix all at once instead of one-off markdown fixes.

@abdulrahuman5196 @jliexpensify do y'all think it makes sense to have some kind of markdown tracker for all the little tiny issues like this one & https://github.com/Expensify/App/issues/17196 - so if we have them all together we can try to fix a clump of issues and make sure nothing breaks, instead of thinking a bout these random edge cases 1 by 1?

**Comment by abdulrahuman5196** [comment]
@Beamanator  We can add the cases to a tracking issue and close this one out

**Comment by jliexpensify** [comment]
Awesome, @Beamanator we can close this out then?

**Comment by Beamanator** [comment]
@jliexpensify I think so! Do you mind creating the tracking issue? :D If not, I can make it next week 👍

**Comment by jliexpensify** [comment]
Hmm, I'm honestly not sure what to put in the tracking issue - is there a structure of something I can follow? Or is it a general GH tracking issue linking these 2 GH's?

**Comment by jliexpensify** [comment]
Ok cool, I'm going to close this then - thanks @Beamanator ! I'll also close the Upworks job, given that this is an edge case.
