### ISSUE TITLE
Security - Two Factor authentication - Copy button not change for Copied after pressing on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Security -> Two-factor authentication
4. Press on Copy codes/Download -> Next
5. Press Copy

## Expected Result:
Copy/Download buttons changed for Copied/Downloaded after pressing on it

## Actual Result:
Copy/Download buttons did not change for copied after pressing on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/40439021d04d2d1140a4f6366c2ba20adef7e832b06171961d330d8fd3f8f077

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
I think it will be handled [here](https://github.com/Expensify/App/issues/19180)

**Comment by michaelhaxhiu** [comment]
I'm gonna close this GH as it should be fixed via this ☝️
