### ISSUE TITLE
[$1000] mWeb/Safari - Connect Bank - Inscription Expensify Terms of Service moves

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Navigate to Settings -> Workspaces -> Click on any workspace -> Connect bank account -> Connect Manually
4. Long press on Expensify Terms of Service

## Expected Result:
Inscription Expensify Terms of Service does NOT move (doubles)

## Actual Result:
Inscription Expensify Terms of Service moves (doubles)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/0137a3fdd3dce14d399350ce36f8af5c52ce28e8664b69cfa336f4181a34d52d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e37c553b2b1eed3</li>
        <li>Upwork Job ID: 1661265433902952448</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
Regression from this PR:
https://github.com/Expensify/App/pull/19101
The problem of this issue is when user long press the link, the Form triggered focus change and showed the error, made the link move down a little bit with the original position of it, after user released the mouse, it took a while for the link moved to the original position and then moved back to the new position which caused this issue. If we can keep the first position the same with the last position (when releasing the mouse this issue won't happen).
cc @mananjadhav @marcochavezf

**Comment by laurenreidexpensify** [comment]
@thesahindia do you agree that this is a regression as per @hungvu193's comment above?

**Comment by mananjadhav** [comment]
@laurenreidexpensify It is.

**Comment by laurenreidexpensify** [comment]
Thanks @mananjadhav 

Note to self - asking a question [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1685440540945709) internally about this

**Comment by laurenreidexpensify** [comment]
Regression is fixed in this https://github.com/Expensify/App/pull/19537 so closing
