### ISSUE TITLE
mWeb - Room chat - Copying all messages in Room chat pasts background image later

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open (or create) Room chat
3. Rename room
4. Long press on Rename room line
5. Select all and then Copy
6. Go to any other chat and Paste previously copied messages

## Expected Result:
All messages copied should be pasted

## Actual Result:
Background image is uploaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3d6a2d134b4013cf92291e72b86c45e3f253c0d3f56a05d1195fa520e42e29bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
@kbecciv The reproduction steps, expected result, and actual result above aren't clear to me. Further, there's no video outlining what behavior we think is a bug. I'm going to close this issue for now, and assign it back to you. 

Could you please update the reproduction steps so they include every action the user would need to take to reproduce this bug, add more detail to the expected and actual results, and then add a video outlining what you think is a bug here? 

Then, feel free to re-open and assign to me. TY!
