### ISSUE TITLE
[HOLD for payment 2023-06-05] Thread Attachment is not translated into Spanish In LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences > Language
2. Select Spanish language and go back
3. Now open a Chat
4. Send an Attachment to user
5. Click on "Reply in thread"
6. Check Attachment LHN

## Expected Result:
Thread Attachment should be translated into Spanish In LHN

## Actual Result:
 Thread Attachment is not translated into Spanish In LHN
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (44)](https://github.com/Expensify/App/assets/93399543/da5dbd35-5c0b-4f3d-ad19-45a47afdd629)

![Screenshot_30](https://github.com/Expensify/App/assets/93399543/563fec03-be70-47f3-b703-b664afa939c6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684419305175989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd375ab383f2bad8</li>
        <li>Upwork Job ID: 1661306443832766464</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment]
@maddylewis offer accepted

**Comment by maddylewis** [comment]
@parasharrajat - whenever you have a chance, will you review this checklist to confirm if we need to do any of those steps? thanks!

https://github.com/Expensify/App/issues/19467#issuecomment-1567590328

**Comment by maddylewis** [comment]
Added regression test proposal to for Applause to add to Test Rail. Just waiting for @parasharrajat to accept the offer so i can process payment :)

**Comment by maddylewis** [comment]
paid!
