### ISSUE TITLE
[$1000] Send money and request money message appears after few second

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. send money or request money

## Expected Result :  
should show message immediate
## Actual Result : 
message appears after 2-3 second

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5e0adfed-85fa-4294-9a55-25e1378ab3cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684506444511939
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197e686b516eecafe</li>
        <li>Upwork Job ID: 1661870045991796736</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I was able to reproduce the issue. I didn't see any duplicates in the repo or #expensify-bugs channel, but I did see @JmillsExpensify [comment here](https://expensify.slack.com/archives/C01GTK53T8Q/p1683642447007639) that this feature might be temporarily broken so it's possible we're tracking this somewhere else.

**Comment by mountiny** [comment]
Sorry for the duplication here, but this is known and we already had an issue for this running here, its handled internally by Cristi https://github.com/Expensify/App/issues/19119 we just need to start adding the report preview action optimistically
