### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Contact Method - Validation error message doesn't disappear upon requesting new magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19040

## Action Performed:
1. Login to ND.
2. Go to Settings > Profile > Contact method > New contact method.
3. Add any contact method.
4. Once redirected to the Contact method page, click on the contact method you entered.
5. Enter any random numbers.
6. Ensure you are shown an error.
7. Click on the resend magic code text.

## Expected Result:
Input is cleared and you are focused on the first input box. Error message should disappear.

## Actual Result:
Input is cleared and focused on the first input, but error message still persists requesting a new code and try again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/d3721b2fe38422b24fa746eb47d7892d16fccf9337780c8d13264980a75745e8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b03109026ba1aa6</li>
        <li>Upwork Job ID: 1661075549036351488</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Validation error message doesn't disappear upon requesting new magic code

### What is the root cause of that problem?
While requesting the new magic code we are not cleaning the previous error in the onyx which seems the cause for the issue.

### What changes do you think we should make in order to solve the problem?
Add new entry to make/reset errorFields `validateLogin` null also here.

https://github.com/Expensify/App/blob/228f40961e41549e8fc9755f6f0394a3f669edec/src/libs/actions/User.js#L136-L138

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Validation error message doesn't disappear when requesting new magic code

### What is the root cause of that problem?

The validation error message is passed to this component as `errors` props

https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L154-L159

Here `ErrorUtils.getLatestErrorField(loginData, 'validateLogin')` get errors from `loginData['errorFields']['validateLogin]` as you can see below



### What changes do you think we should make in order to solve the problem?


<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment]
@puneetlath Can you please clarify the expected output?

As of now, when user presses "Resend Magic Code", only after receiving api response, "Link has been re-sent" message is displayed and input in cleared.

So, would we expect the error to be cleared as soon as the user presses "Resend Magic Code"?

IMO, we should clear and refocus the input magic code and clear the error as soon as user presses "Resend Magic Code". And show "Link has been re-sent" message only after user receives the api response.

**Comment by puneetlath** [comment]
@sobitneupane I agree with that. That sounds good.

**Comment by sobitneupane** [comment]
@Pujan92 Would you like to update your proposal to yield [this outcome](https://github.com/Expensify/App/issues/19471#issuecomment-1562731735)?

**Comment by s-alves10** [comment]
@sobitneupane 
My proposal has already the result. Did you check?

**Comment by Pujan92** [comment]
> @Pujan92 Would you like to update your proposal to yield [this outcome](https://github.com/Expensify/App/issues/19471#issuecomment-1562731735)?

@sobitneupane I just updated my [proposal](https://github.com/Expensify/App/issues/19471#issuecomment-1559959557).

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19471#issuecomment-1560705722)

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/19471#issuecomment-1559959557) from @Pujan92 looks good to me.

🎀👀🎀 C+ reviewed
cc: @puneetlath

**Comment by puneetlath** [comment]
Let's do it @Pujan92 💪🏾

**Comment by puneetlath** [comment]
Sent Upwork hiring offers. 

@lschurr adding you for payment since I'll be OOO next week. Thanks!

**Comment by lschurr** [comment]
Not overdue. This will be paid tomorrow.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/15751
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/15751#issuecomment-1588547943
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1686632713430389

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Click on Settings -> Profile -> Contact Method
2. Either add a new contact method or select the existing one where verification is yet to be done
3. Enter incorrect magic code
4. Click on "Resend magic code"
5. Verify the error and the existing code gets cleared as soon as "Resend magic code" is clicked.

Do we agree 👍 or 👎

**Comment by lschurr** [comment]
All set.
