### ISSUE TITLE
Payment issue for E/App PR#19094

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#19474]
Issue created to compensate the Contributor+ member for their work on https://github.com/Expensify/App/pull/19094
E/E issue linked to the PR - https://github.com/Expensify/Expensify/issues/282865.
Contributor+ member who reviewed the PR - @parasharrajat.

Wait 7 days after the PR is deployed to production before issuing payment in case there are regressions.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c69dd84bb38aa4a</li>
        <li>Upwork Job ID: 1661079694867148800</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by amyevans** [comment]
@parasharrajat can you comment please so I can assign you?

**Comment by kevinksullivan** [comment]
@amyevans is this a standard review? So $1,000?

**Comment by amyevans** [comment]
@kevinksullivan Yep!

**Comment by kevinksullivan** [comment]
all set!
