### ISSUE TITLE
Chat- Chat doesn´t scroll automatically when request is received

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19481]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a 1:1 conversation
2. Scroll a moderate amount of the conversation history (at least to the point that the latest message is not visible)
3. On the compose box - Click the + button
4. Click on request money and finish the IOU flow

## Expected Result:
Verify the conversation is scrolled to the bottom and the latest message (IOU) is visible

## Actual Result:
Chat doesn´t scroll automatically to the bottom when request is received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/50daa9010141a62b69cf3aa54a782594d86e48a71a18d00b97b2d24a1c761e62

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
@kbecciv can you confirm if you are still able to reproduce? I cannot.
<img width="563" alt="image" src="https://github.com/Expensify/App/assets/37308300/81947862-7e40-415b-be98-e6ec80795b94">

**Comment by kbecciv** [comment]
@arielgreen Sure, let me check with team, will update you shorly.

**Comment by kbecciv** [comment]
Issue fixed

https://github.com/Expensify/App/assets/93399543/0f81ac56-21f4-4b17-954c-5d280dcc609c

**Comment by kbecciv** [comment]
Issue is still reproductible on build 1.3.19.2

https://github.com/Expensify/App/assets/93399543/c866c7f9-9434-478d-9dc8-aa7538820d9a
