### ISSUE TITLE
[HOLD for payment 2023-06-02] [HOLD for payment 2023-06-01] Connect bank account - Inscriptions are broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Connect bank account
4. Choose any options to add bank accounts (Log in or Manual)
5. Enter all information to connect a bank account
6. Pay attention to the text below on pages Company Information, Personal Information and Additional information

## Expected Result:
Inscriptions are NOT broken

## Actual Result:
Inscriptions are broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/e356218d65aebbe7b1293e333c03799c6da097f6a2cdbc2b3c5dde132e640702

https://platform.applause.com/services/links/v1/external/917116761022de2722cbb3a23126bc30bc1fd88c699340428153bbf94981e20d

https://platform.applause.com/services/links/v1/external/720b7c5a235eb371593a87ccf7cd1e00149bf4d49040ec88b36259d1f8a65e3f

https://platform.applause.com/services/links/v1/external/2879542f20f49eb82ccc3b3b02c0fe6fef1c5182336573c7a64b5fec26b9f9a2

https://platform.applause.com/services/links/v1/external/9317a09417c0110f9c39338d280eaeefe13fbdcc1fd26a1eecac3627d119d1b6

https://platform.applause.com/services/links/v1/external/de76c4635d2f6a5ffc2640fc853a88682952d572a0075c9d1932303637aa7d65

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Hey guys, for more context, this issue came from my PR here: https://github.com/Expensify/App/pull/19101.
Please let me know if I can open a PR to fix it. Thank you!

**Comment by hungvu193** [comment]
PR fixed this regression is ready for review here:
https://github.com/Expensify/App/issues/19482

**Comment by luacmartins** [comment]
PR is merged. Adding bug label to process reporting bonus payment to @situchan.

**Comment by luacmartins** [comment]
@maddylewis could you help making the report bonus payment to @situchan? This was a regression within the regression period, so no other payments are due.

**Comment by maddylewis** [comment]
yep! i will send a reporting bonus payment to @situchan

**Comment by maddylewis** [comment]
will review / process payment tomorrow

**Comment by maddylewis** [comment]
### Payments
- @situchan reporting bonus - $250

sorry for the delay! i was going off of the title of the GH in my K2.

**Comment by maddylewis** [comment]
offer sent
