### ISSUE TITLE
mWeb - Workspace - User avatar without workspace avatar overlay is not displayed for messages after 4 mins

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19230

## Action Performed:
1. Login to NewDot on mWeb
2. Request money from another user + > Request money
3. In the chat view, verify that the report preview only shows the user avatar, there's no extra top margin and the text color is muted.
4. Tap the report preview
5. Verify that you see the user avatar next to the request preview
6. Create a workspace
7. In the workspace, request money
8. Verify that the report preview shows the user avatar and the workspace avatar overlaying it, there's no extra top margin and the text color is muted.
9. Tap the report preview
10. Verify that the user avatar is overlaid by the workspace avatar for request previews
11. Wait 4 minutes
12. Send a message

## Expected Result:
User avatar is displayed for the message and the workspace avatar should not overlay it

## Actual Result:
User avatar is not displayed for the message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/60f1327495caba49c26ad28b1f40043c931592dca75bf732bcac7ef4b34c7325

https://platform.applause.com/services/links/v1/external/77807b438723f5cd7feba886db33068ee6b9b573733eaae9fe19a3ce82150155

https://platform.applause.com/services/links/v1/external/f60f2236b28c96ea8def860f371fa3d65cae31267fc66fec93b2b4a64489039c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I'm having a lot of trouble following this issue is pretty difficult to follow to be honest. Can you explain why steps 1-5 are required in the reproduction steps? It doesn't seem like any of those are related to the purported bug.

Also, can you explain "wait 4 minutes" in a bit more detail? Why that amount of time? What happens if you don't wait for 4 minutes?

cc @kbecciv

**Comment by luacmartins** [comment]
Sorry, the test should specify 5min because before that we group the messages and don't display a new avatar. Another alternative is to just send a message from user B and then from user A send another message.

**Comment by luacmartins** [comment]
Not an issue.
