### ISSUE TITLE
Cleanup: Remove useEmojiReactions param from PHP

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#19529]
- [ ] Held on https://github.com/Expensify/App/pull/17996

When the new emojiReactions property was created to migrate reactions to a new data format, PHP was made to be backwards compatible to support both `reactions` and `emojiReactions`. Now that the front-end fully supports `emojiReactions`, the code from PHP can be cleaned up.

1. Start with the API commands in [api.php](https://github.com/Expensify/Web-Expensify/blob/fc26ad5032d4c4ea7b14b02563a9efb248251f4d/api.php#L804-L822) and remove the comments and the `if` statements
2. Remove the calls to `ReportAPI::addOrRemoveEmojiReaction` and all the code down the path which is no longer used

**Comment by tgolen** [comment]
Oh gosh, these auto-assigners are killing me. Sorry, I am removing you all.

**Comment by tgolen** [comment]
The draft PR for this is here: https://github.com/Expensify/Web-Expensify/pull/37595

**Comment by stitesExpensify** [comment]
holding

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
Starting this this week

**Comment by stitesExpensify** [comment]
I have been focused on other projects. Will get to this next week.

**Comment by stitesExpensify** [comment]
I've been working on this. Hoping to have it done this week

**Comment by stitesExpensify** [comment]
Ended up picking up a few more important issues so this is on the back burner

**Comment by stitesExpensify** [comment]
I've been focused on wave8. I should finally have some time to complete this very soon

**Comment by stitesExpensify** [comment]
no update

**Comment by stitesExpensify** [comment]
Closing for #focus on waves per the new guidelines
