### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-01] Support new emojiReactions in NewDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#19531]
- [x] Held on https://github.com/Expensify/Web-Expensify/pull/37193

The data format for reactions is changing to a new format in https://github.com/Expensify/App/issues/16506.

Because of this, a lot of code needs to be updated to use the new format.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01271e0f2f6be87ab5</li>
        <li>Upwork Job ID: 1687202366562164736</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
https://github.com/Expensify/App/pull/17996

**Comment by stitesExpensify** [comment]
Off hold!

**Comment by stitesExpensify** [comment]
@rushatgabhane we need to pay you here for https://github.com/Expensify/App/pull/17996 correct?

**Comment by rushatgabhane** [comment]
Oh thanks, created a manual request - https://staging.new.expensify.com/r/3627092703830894

**Comment by JmillsExpensify** [comment]
@stitesExpensify Can you confirm in writing that @rushatgabhane should be paid $1,000 for this issue/PR?

**Comment by stitesExpensify** [comment]
Yes, that is correct!

**Comment by conorpendergrast** [comment]
Given that @rushatgabhane has created a ND manual request, and everything else seems to have been wrapped up here, we can close this out, correct @stitesExpensify ?

**Comment by rushatgabhane** [comment]
yes we can close. it'll be tracked on new dot

**Comment by JmillsExpensify** [comment]
Thanks. This is reviewed and approved for payment in NewDot.

**Comment by conorpendergrast** [comment]
Nice, all done. Thanks everyone
