### ISSUE TITLE
[HOLD App/issues/19529] Cleanup: Remove original "reactions" data format code in Auth

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#19534]
- [ ] Held on https://github.com/Expensify/App/issues/19529

When the new `emojiReactions` property was created to migrate reactions to a new data format, Auth was made to be backwards compatible to support both `reactions` and `emojiReactions`. Now that the front-end fully supports `emojiReactions`, the code in Auth can be cleaned up.

1. You can see all the code that was added in https://github.com/Expensify/Auth/pull/7811
1. Modify both `AddEmojiReaction.cpp` and `RemoveEmojiReaction.cpp` to remove the comments and the OLD FORMAT code
1. Update the tests to remove the `reactions` property from everything

**Comment by tgolen** [comment]
Draft PR for this: https://github.com/Expensify/Auth/pull/8000 

Who knows how much code will change by the time it's ready to merge this. Hopefully, there won't be too many conflicts.

**Comment by stitesExpensify** [comment]
holding

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
no update

**Comment by stitesExpensify** [comment]
Closing this for focus on waves
