### ISSUE TITLE
[HOLD App/issues/19534] Cleanup: Remove useEmojiReactions param from NewDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#19535]
- [ ] Held on https://github.com/Expensify/App/issues/19534

As the last part of cleanup for https://github.com/Expensify/App/issues/16506 `useEmojiReactions` parameter can be removed since nothing is referencing it in the API anymore.

1. Search the code for `useEmojiReactions`
2. Remove the two instances where it is used in `lib/actions/Report.js` for adding and removing emoji

**Comment by stitesExpensify** [comment]
holding

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
No update

**Comment by stitesExpensify** [comment]
Closing for now to focus on waves
