### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-02] [HOLD for payment 2023-06-01] Right click to copy URL to clipboard doesn't work for external links and it throws console error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Click F12 if chrome to open console window
4. Right click on 'Help' to open popup for external link
5. Observe console error in console window

## Expected Result:
App should open 'Copy URL to clipboard' popup on right click on external link

## Actual Result:
App does not  open 'Copy URL to clipboard' popup on right click on external links and it provides console error.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-3 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5e687505-80d9-4de5-b29a-6e727a5e8bb5

https://github.com/Expensify/App/assets/43996225/26ba321c-2c47-433e-bde7-00577952f61f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684936840755899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b76a93c06e5bfb6</li>
        <li>Upwork Job ID: 1662153953956110336</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
Code was CP'd to staging. I tested it and it lgtm. Removed the deploy blocker label. Checked it off the QA checklist.

**Comment by puneetlath** [comment]
Was already fixed by @0xmiroslav. Added the external label to get the Upwork job created.

**Comment by puneetlath** [comment]
Contracts sent. 

@aimane-chnaif as the C+ on this one, can you please take care of the checklist? Thanks!

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
