### ISSUE TITLE
[HOLD for payment 2023-06-07] Use Actor Avatar for All Threads 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#19553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

context: https://expensify.slack.com/archives/C04QEB4MJEQ/p1684920485401849

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc07d9825b9d6fdc</li>
        <li>Upwork Job ID: 1661451200968921088</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by abekkala** [comment]
### Payments to be made on May 04:

- C+ PR Review: @0xmiroslav [$1000] 

@0xmiroslav when you have a moment can you complete the checklist above?

**Comment by abekkala** [comment]
Not overdue - payment is scheduled for tomorrow.

**Comment by abekkala** [comment]
@0xmiroslav paid and contract ended - Thank you! 🎉 

Closing
