### ISSUE TITLE
Non-Room Workspace chats are failing when creating threads

### ISSUE THREAD

**Issue by grgia** [Expensify/App#19554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps
   Create a new workspace and add a member ✅
   Send a message in the workspace chat ✅
   Create a thread from that message ❌
   Verify that the header title is the thread parent and the subtitle is ❌

context: https://github.com/Expensify/App/pull/19185#issuecomment-1553317993

## Expected Result:
Thread should be created 

## Actual Result:
OpenReport returns 500 error

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfff36b148a03129</li>
        <li>Upwork Job ID: 1661453695204798464</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
i was OOO for a bit, aiming to tackle hopefully tomorrow.

**Comment by chiragsalian** [comment]
@grgia, i was checking this out today on dev and it worked fine for me i.e.,
- Create a thread from that message
worked for me. Maybe someone else added the fix elsewhere, can you recheck.

But this,
- Verify that the header title is the thread parent and the subtitle is
doesn't show up correct, I see it like this,
![image](https://github.com/Expensify/App/assets/14356145/7c877d7e-7959-49c5-b88c-a9b62b7d6e5e)
which is not ideal, but it makes sense that there is no parent report name to show so its empty. I think if we just don't show the dot after workspace name we should be good to go here.

Thoughts? Let me know if I'm missing something.

**Comment by grgia** [comment]
@chiragsalian fix for the • is in this PR https://github.com/Expensify/App/pull/19185

**Comment by chiragsalian** [comment]
Cool, i guess ill close out this issue since i don't see a backend problem. If anyone is able to reproduce let me know with test steps.
