### ISSUE TITLE
Using the "@" symbol and typing a complete email address in a chat, pressing Enter does not share the email 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19568]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat.
2. Type "@" followed by the complete email address.
3. Press Enter.
4. Notice that the suggestion list closes after the first press of Enter, and the email is shared only after the second press of the Enter key.

## Expected Result: 
The email should be shared, and the suggestion list should close simultaneously when the Enter key is pressed.
## Actual Result: 
The suggestion list closes with a single press of the Enter key, and the email is shared only after pressing Enter for the second time (Works fine if we press send button using mouse).

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/28e57441-9e0d-42d3-8866-b376deedf4af

https://github.com/Expensify/App/assets/43996225/9f6a726c-2c19-475b-b5e6-2097f89304bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684818498899249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment]
This looks like intended behaviour, I don't think it should be a bug.
