### ISSUE TITLE
[HOLD for payment 2023-06-13] Chat - Request Money - Request Money in thread chat between users doesn't show up the request.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19560]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Use Acc A and Acc B
2. Send message from Acc A to Acc B
3, Reply in thread to message sent by Acc A
4. Now Acc A request money from B in Thread chat

## Expected Result:
Proper Request shown for Acc A and Acc B

## Actual Result:
Green Arrow with expand option visible for Acc A (on clicking the expand button Page with Hmmm. not here pops). The request doesn't appear in Acc B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b180671c-8afb-4bad-a390-4a162ed0c0a1

https://github.com/Expensify/App/assets/93399543/c31c330f-d772-46c3-b289-0d3fe88f7c4c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @shivansh9007

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684732827576419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01385bdf0e6ea1b34e</li>
        <li>Upwork Job ID: 1663299541948145665</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by arielgreen** [comment]
Reassigning, OOO

**Comment by MitchExpensify** [comment]
I do not see a similar issue anywhere and can reproduce this

**Comment by MitchExpensify** [comment]
> Should we allow to request/send money in a threadReport? 

Yes I believe so! But cc'ing @mountiny for a buddy check on that

**Comment by mountiny** [comment]
I think we should disallow it for now. I will add it in my PR.

**Comment by mountiny** [comment]
I hope you dont mind @youssef-lr if I will take over

**Comment by MitchExpensify** [comment]
Cal reminder set for payment 👍

**Comment by MitchExpensify** [comment]
Invite sent to @shivansh9007 for reporting payment 👍

**Comment by mountiny** [comment]
@shivansh9007 any update?

**Comment by MitchExpensify** [comment]
@shivansh9007 Can you apply to the job here from your new Upwork profile please? https://www.upwork.com/jobs/~01385bdf0e6ea1b34e Thanks!

**Comment by MitchExpensify** [comment]
Offer sent @shivansh9007 ! Thanks

**Comment by mountiny** [comment]
@shivansh9007 Has this been paid?

**Comment by MitchExpensify** [comment]
Paid! Are we good to close @mountiny ?

**Comment by mountiny** [comment]
I think so, thanks everyone!
