### ISSUE TITLE
checkbox label is not wrapped but truncated

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to Settings > Workspaces > any workspace > Connect bank account
2. Complete Step 1
3. On Step 2, scroll down to bottom and observe checkbox label

## Expected Result:
 "I confirm that this company..." text is displayed multiline and not truncated

## Actual Result:
"I confirm that this company..." text is truncated in single line
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-22 at 9 27 04 PM](https://github.com/Expensify/App/assets/43996225/99920317-c2c6-4a29-b9e1-7d27da43c914)

https://github.com/Expensify/App/assets/43996225/6b51268c-d324-459f-87c7-c81f8fda314c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684816657258979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
Proposal by @situchan 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
checkbox label is not wrapped but truncated
### What is the root cause of that problem?
This came from #19101 where TouchableOpacity is replaced with PressableWithFeedback in CheckboxWithLabel component.
PressableWithFeedback has 2 view layers (GenericPressable, OpacityView) and flex not applied to GenericPressable
### What changes do you think we should make in order to solve the problem?
pass wrapperStyle={[styles.flex1]} [here](https://github.com/Expensify/App/blob/b424edcbe7cea7ed5fe36bc5602f6eb4ed1d78bf/src/components/CheckboxWithLabel.js#L105-L111)

**Comment by situchan** [comment]
This one can be closed. All payments will be handled in https://github.com/Expensify/App/issues/19482.
