### ISSUE TITLE
[HOLD for payment 2023-06-07] [$1000] Pencil icon is not appearing in LHN of the Money Request/Owes chat.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Write anything and notice the pencil icon will appear on LHN as soon as the first letter is typed
3. Now go to any chat of Money Request/Owes.
4. Write anything and notice the pencil icon will not appear on LHN as soon as the first letter is typed but if witch to any other chat it will appear
5. Once the Pencil icon appears, it will not remove even if the user deletes the typed information

## Expected Result: 
Icon should appear on LHN as soon as the first letter is typed in Money Request/Owes chat.
## Actual Result: 
Icon doesn’t not appear on LHN as soon as the first letter is typed in Money Request/Owes chat.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bcca1033-9c47-45ae-81bf-e3ac09136833

https://github.com/Expensify/App/assets/43996225/b8e355e4-b0e4-4aa3-9e6f-0b11da578ebf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684821755647069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132317dd6e85d9c6b</li>
        <li>Upwork Job ID: 1661711412176367616</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Hey @anmurali - I'm heading OOO this week. I've sent out offers to @allroundexperts @parasharrajat @usmantariq96 (including the $500 bonus for this being merged within 3 days of assignment). 

Assuming there are no regressions, this one will need payment in a couple of days so assigning a BZ buddy. Thank you for the help!

**Comment by usmantariq96** [comment]
@bfitzexpensify applied

**Comment by yuwenmemon** [comment]
@allroundexperts bump!

**Comment by bfitzexpensify** [comment]
All payments issued and contracts ended

**Comment by bfitzexpensify** [comment]
Testrail update here https://github.com/Expensify/Expensify/issues/291254

**Comment by bfitzexpensify** [comment]
Think we're all done here. Thanks for the work everyone!
