### ISSUE TITLE
 Cursor is not in correct position in  Two factor authentication Step 2

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to settings
2. then go to security
3. then two factor authentication
4. move to step. 2 after copy code
5. try to add code
6. Observe the cursor

## Expected Result:  
cursor should be accurate, and move according the code

## Actual Result:  
cursor is not accurate, it is stuck on first code

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a65e31a7-be17-499b-99a8-f70179b3aeea

https://github.com/Expensify/App/assets/43996225/80be7a00-9f69-43d4-acbc-887a0c676ac7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1684823108559239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Dupe of https://github.com/Expensify/App/issues/19220 I believe

**Comment by kavimuru** [comment]
@hungvu193 Yeah, seems dupe
