### ISSUE TITLE
 Creating a new group using CTRL + ENTER keyboard shortcut creates two groups

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Click on the + icon on LHN
2. Click on New group
3. Select some contacts to add to the group
4. Press CTRL + ENTER to create the group
5. Observe the newly created group on LHN

## Expected Result: 
Only one group should be created
## Actual Result: 
Two groups are created when pressing CTRL + ENTER to create a new group. Only one group gets created if user clicks on "Create group" button with the mouse instead.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/39fb6554-adfc-496d-b955-6c0ac5f93dd7

https://github.com/Expensify/App/assets/43996225/7e18b33b-dfde-457d-b8c3-05ce228c7496

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684977472641679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
@allroundexperts final verdict - you think it was a regression?

**Comment by michaelhaxhiu** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1685450838377679?thread_ts=1684401315.718349&cid=C049HHMV9SM

**Comment by michaelhaxhiu** [comment]
IMO Keyboard GHs are off the table right now.
