### ISSUE TITLE
[HOLD for payment 2024-07-10] Implement Flashlight tool to the testing suite

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19596]
Coming from [this Slack proposal](https://expensify.slack.com/archives/C01GTK53T8Q/p1684244888190579) which was discussed in the thread.

### Problem
When making changes to our codebase, we aim to identify any performance regressions before they infiltrate the production app. For this purpose, we have end-to-end (e2e) performance regression tests running in our Github actions. (These had been non-functional for a time but are now operational again!)

Recently, a significant performance regression entered the production app unnoticed. Our systems should be robust enough to intercept any form of performance regression. However, the issue slipped through because our system currently only measures one performance metric: Time to Interactive (TTI).

Other performance metrics, such as the app's UI Frames Per Second (FPS), RAM, and CPU usage, can also signal regressions. The recent performance regression would have get caught with these metrics.

Consider this scenario: You've implemented a new image component, and while testing the app, everything appears fast and efficient. The performance regression test suite shows no change in TTI, so everything seems in order. Yet, unbeknownst to you, RAM usage has tripled. Consequently, we begin to see Out of Memory (OOM) crashes on lower-end devices after your pull request is merged. These types of regressions should not go unnoticed, correct?

### Solution
Our existing e2e testing suite is constructed in such a way that we can readily incorporate additional performance metrics into our test flows. I propose that we add a tool called "[Flashlight](http://flashlight.dev/)" to our test suite.

Flashlight will measure the e2e flows for UI FPS, RAM, and CPU usage. We can then include these values in our test reports for comparison.

By employing this approach, we can identify a broader range of regressions. This will give us greater confidence in the updates we introduce to our production environment.

**Comment by hannojg** [comment]
👋

**Comment by lschurr** [comment]
From the Slack proposal, it looks like @hayata-suenaga will be owning this internally. Is that correct? Do we need anything from BZ here?

**Comment by hayata-suenaga** [comment]
No, we don't; sorry I forgot to remove the assignment 🙇

**Comment by hayata-suenaga** [comment]
@hannojg what are some benefits that Flashlight provides that popular end-to-end testing tools such as detox cannot provide?

**Comment by hayata-suenaga** [comment]
changing the priority of this issue to monthly

**Comment by hannojg** [comment]
(Still on my todo list! Probably will start with it by next week)

**Comment by hayata-suenaga** [comment]
@hannojg how is this project going?

**Comment by hannojg** [comment]
Hey, sorry, this project is on HOLD as we are fixing the e2e pipeline at the minute. Project should start next week though once everything is fixed!

**Comment by hayata-suenaga** [comment]
low priority now

**Comment by hayata-suenaga** [comment]
I'll close this for now

**Comment by hannojg** [comment]
I am okay closing that for now - just wanted to note that I still had this on my todo list and we are doing some work in the background to enable this metric capturing for expensify soon!

**Comment by hayata-suenaga** [comment]
ah okay thank you for your work
please comment on this issue once the PR has started so that I can reopen this for you 🙇

**Comment by hannojg** [comment]
@hayata-suenaga Update: @kirillzyusko will now take over this task - can we reopen and assign to him? We are working on a PR for this now!

**Comment by hayata-suenaga** [comment]
@kirillzyusko, can you comment something on this issue so that I can assign you here?

**Comment by hayata-suenaga** [comment]
changing the priority to weekly now that the draft PR is open

**Comment by kirillzyusko** [comment]
@hayata-suenaga sure, I would like to work on this task 🙌

**Comment by hayata-suenaga** [comment]
No payment is necessary for this issue I think

**Comment by kirillzyusko** [comment]
@hayata-suenaga I think the issue can be closed?..
