### ISSUE TITLE
System displays magic code expired, and 2FA error when authenticating with magic link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Verify that your account has 2FA (Precondition)
2. Navigate to staging sign in page
3. Enter email > click on continue button
4. Open email > copy magic link > add staging prefix to the link on browser address bar > press enter key
5. Observe 'Magic code expired' message is displayed
6. Switch tab to where you first signed in with email

## Expected Result: 
System should display Two-factor code is required page, and shouldn't throw 2FA error
## Actual Result: 
System displays Magic cod expired page, and throws 2FA error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6dff7beb-595a-444f-bf29-c61b3a2ab564

https://github.com/Expensify/App/assets/43996225/8681431d-b2c9-4dc0-a1ac-dfb530aee79f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685007013501189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
@kavimuru no reviewer and internal seem to be assigned on this issue.

**Comment by cristipaval** [comment]
This is solved by the fix added for the [this issue](https://github.com/Expensify/App/issues/19636) reported for the mobile native.
