### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Ensure Pay With Expensify option on expense reports uses ACH payment type

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Request money from workspace
2. As admin, navigate to that expense report

## Expected Result:

The Pay with Expensify option on expense reports should use ACH payment type

## Actual Result:

You can see the Pay With Expensify which under the hood uses Expensify payment type

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175c54665980ffe49</li>
        <li>Upwork Job ID: 1661838283621404672</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@mountiny will you update the title and OP of this issue? It sounds scary. I believe the intention is to not allow settling expenseReport on a workspace using the wallet. The `Pay with Expensify` button would exist, but only if there's a VBBA added to the workspace to use to pay expense reports.

**Comment by mountiny** [comment]
Will update it, for me Pay WIth Expensify is a synonym of a wallet.

**Comment by mountiny** [comment]
I can handle this internally

**Comment by mountiny** [comment]
Gonna work on this one soon

**Comment by mountiny** [comment]
mostly ooo today for bank holiday, I will work on this as I come back

**Comment by puneetlath** [comment]
@sobitneupane I sent you a contract in Upwork. 

@mountiny is the checklist needed on this one? 

@kadiealexander I added you to take care of the payment since I'll be OOO next week. Thanks!

**Comment by puneetlath** [comment]
Whoops. Looking at the PR it looks like @allroundexperts was the C+ on this. Thanks for letting me know. 

@sobitneupane I've withdrawn the contract. 

@allroundexperts I've sent you a contract.

**Comment by kadiealexander** [comment]
Not overdue, @mountiny if you could please advise on the checklist that would be great!

**Comment by mountiny** [comment]
@kadiealexander no need for this one, its a new feature essentially.

**Comment by kadiealexander** [comment]
Woo! Thanks Vit. @allroundexperts has been paid, closing this one out!
