### ISSUE TITLE
A Long workspace name is cut off in Details sidebar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on 'Profile' icon
2. Click on 'Workspace' link
3. Click on an existing workspace
4. Rename the workspace name with a long name to 55 to 60 characters
5. Close RHN
6. Open admin room of the corresponding workspace
7. Click on header
8. Verify Details sidebar is opened

## Expected Result: 
Workspace name shouldn't be cut off
## Actual Result: 
Workspace name is cut off
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5a4b3282-01b9-4840-a9f4-79d8b508e8c6

<img width="956" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/a5a381a8-613d-4bd3-98b8-b38f27d72c22">

**Expensify/Expensify Issue URL:**
**Issue reported by:**
@natnael-guchima
**Slack conversation:**
https://expensify.slack.com/archives/C049HHMV9SM/p1684828146658919
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
As noted in the slack thread i dont think this is a bug

**Comment by Natnael-Guchima** [comment]
To reproduce this issue user has to use more than 60 character long Workspace name. 

Ex: 'Neque porro quisquam est qui dolorem ipsum quia dolor siteee lore'

**Comment by kavimuru** [comment]
I was able to reproduce with 58 characters. Should this be more than 60 characters @natnael-guchima?

**Comment by kevinksullivan** [comment]
closing per the slack discussion.

**Comment by zaitsev1** [comment]
[#issuecomment-1636820736](https://github.com/Expensify/App/issues/22894#issuecomment-1636820736)
