### ISSUE TITLE
Details page - Avatars are not on the same level

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19615]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Click on the FAB button -> Request money
4. Choose any user and complete the money request
5. Click view details in the DM

## Expected Result:
Avatars displayed on the same level

## Actual Result:
Avatars are not displayed on the same level

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3e08f3cd55dd55c6ea94ac63a3d3bad6d3f8c1282a482ed5ecc983dd19b4471b

https://platform.applause.com/services/links/v1/external/c00d75d56698056cb111bfae25746a08201b96e5ccf4f5f0370374087338319d

https://platform.applause.com/services/links/v1/external/2997f7d5fbd68ccecf2b7db48fc4d02e215714539a4f5c94375cd2be1c93aaca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm asking for clarification [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1685325562450589). I'm not certain this is a bug.
