### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Unnecessary space between the TopBar and profile image, and profile image and share code button too.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Click on profile icon in the TopBar
3. Take note of the spacing between TopBar and profile image/profile image and share code button
4. Reply to a message in a thread
5. Click on the thread profile icon in the TopBar
6. Note that spacing is now greater between TopBar and profile image/profile image and share code button

## Expected Result: 
There should be same space and alignment compare to other profile information page have.
## Actual Result: 
There is too much Unnecessary space compare to other profile information page have.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d61ddb69-0bf9-46b8-9f84-9667048c19ac

<img width="949" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/89b914d8-9d47-4138-835e-dea6de364810">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684841019052619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128a63176752fccad</li>
        <li>Upwork Job ID: 1661999436656521216</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Reviewing

**Comment by greg-schroeder** [comment]
@aimane-chnaif hey! looks like we had an early bird proposal here: https://github.com/Expensify/App/issues/19627#issuecomment-1563526318 lmk what you think!

**Comment by greg-schroeder** [comment]
Okay! Shawn is OOO til Monday but let's have @bondydaa at least confirm as well in the interim. :)

**Comment by bondydaa** [comment]
👍 yep seems like a solid proposal and agree we should loop in Shawn here. 

Noting for fairness since it's later on a Friday that is also a holiday week for the US that I think we start counting on Monday May 29 for the speed bonus but I'll assign for now.

**Comment by greg-schroeder** [comment]
Offers sent to @aimane-chnaif @dhairyasenjaliya @niravkakadiya25

**Comment by niravkakadiya25** [comment]
Accepted
