### ISSUE TITLE
Recovery codes does not show if user uses the url(https://staging.new.expensify.com/settings/security/two-factor-auth/codes)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Recovery codes page by clicking URL (https://staging.new.expensify.com/settings/security/two-factor-auth/codes)

## Expected Result: 
should show recovery codes
## Actual Result: 
does not show  recovery codes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="958" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/0aba9253-84bb-4ea2-8580-603965ac8525">

https://github.com/Expensify/App/assets/43996225/59ef49a1-307d-4784-ac32-c346877a5de4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684848223312759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kushu7** [comment]
This will be covered in my [proposal#1561940882](https://github.com/Expensify/App/issues/19496#issuecomment-1561940882)  . both are related issue.

**Comment by tjferriss** [comment]
Thanks, @kushu7. I'm closing in favor of https://github.com/Expensify/App/issues/19496

**Comment by gadhiyamanan** [comment]
@tjferriss i think the proposal is not accepted yet and the changes in proposal was made after this issue is reported to solve this issue. It is eligible for reporting bonus.

**Comment by tjferriss** [comment]
@gadhiyamanan because https://github.com/Expensify/App/issues/19496 was reported first we won't be giving a reporting bonus on this issue.
