### ISSUE TITLE
Ensure react/native fork gets updated with latest upstream 

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#19630]
Update our react/native fork to include [this upstream commit](https://github.com/facebook/react-native/commit/e8b4bb0684eed2acdb4648205893ee372f7ac1c7) which was duplicated into our fork here: https://github.com/Expensify/react-native/pull/53 by @hellohublot 

cc @trjExpensify, original issue was https://github.com/Expensify/App/issues/18121

**Comment by jpdriver** [comment]
why _does_ /App use a fork? 🤔

**Comment by flodnv** [comment]
Closing as per https://expensify.slack.com/archives/C01GTK53T8Q/p1686159512184629
