### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-09] Signing in with magic link results in incorrect two factor authentication code

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#19636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open newDot on your mobile device 
Enter the login for an account with 2FA enabled 
Get sent a magic code
Tap the magic link in your SMS or email inbox

## Expected Result:
View should update and user should be prompted for their 2FA code

## Actual Result:

User gets `Incorrect Two Factor Authenticate code. Please try again` error message

## Workaround:

User can copy-paste or manually enter the code from their notification 

## Platforms:
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** nikkiwines@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684946460798249

https://github.com/Expensify/App/assets/16747822/89336f11-6f63-4e4b-bf3d-7abd72c984e7

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015475622e806423d9</li>
        <li>Upwork Job ID: 1661869865818497024</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by Natnael-Guchima** [comment]
I reported a similar issue here https://github.com/Expensify/App/issues/19606. It might need to be closed since the issue is being solved here.

**Comment by cristipaval** [comment]
> I have reported a similar issue here #19606. It might need to be closed since the issue is being solved here.

You're right, they both have the same root.

**Comment by NikkiWines** [comment]
Oh, we need a BZ person on this to issue payment for this don't we - adding the `External` label so we can get this sorted

**Comment by NikkiWines** [comment]
@NicMendonca we just need to pay @parasharrajat for reviewing [this internal PR](https://github.com/Expensify/App/pull/19637) 🙇

**Comment by cristipaval** [comment]
@NicMendonca will pay this soon.

**Comment by NicMendonca** [comment]
@parasharrajat sent you the offer!
