### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Strange UX when creating tasks in a DM 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. A creates a task in the group DM (A,B andC) and assigned it to B
2. Log in as C and there is no indicator it is assigned to B, either in the main chat or in the task thread. But C has access to the task thread, but there's no obvious way for the other participants to know C is included.
3. B initially saw just the checkbox without the Task title next to it. When he clicked into that thread and then back to DM with A, then only able to see the title
4. As user C click the "Mark as Done" button in the task thread.  
## Expected Result:
Able mark as done
## Actual Result:
Tt flashes complete and switches back to the button
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-23 at 9 45 15 AM](https://github.com/Expensify/App/assets/43996225/781375da-b385-4b5a-8f86-ecf1900ee9c4)
![Screenshot 2023-05-23 at 9 42 48 AM](https://github.com/Expensify/App/assets/43996225/569c9a4e-a70d-43a9-b7cb-48d8d3c24b12)

https://github.com/Expensify/App/assets/43996225/cf2550c4-b841-4aaa-bd57-e8eb206de8a5

https://github.com/Expensify/App/assets/43996225/330e585a-11e0-4323-a500-628aa0f2ec0a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684861533207629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0faa4b5ac73262e</li>
        <li>Upwork Job ID: 1663179954798112768</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Adding external label

**Comment by sonialiap** [comment]
@mollfpr what do you think of this proposal?

**Comment by mollfpr** [comment]
Reviewing now!

**Comment by sonialiap** [comment]
@mollfpr How did the review go? 😄

**Comment by mollfpr** [comment]
@sonialiap I still need more time on this. I'll get back to you in the morning 🙏

**Comment by mollfpr** [comment]
>Log in as C and there is no indicator it is assigned to B, either in the main chat or in the task thread

@hoangzinh Now we have the assignee email in the main report but still need the assignee in the thread on the account C.

![Screenshot 2023-06-06 at 23 56 19](https://github.com/Expensify/App/assets/25520267/d88a3707-7494-41c5-8bec-03f3b3f854aa)

![Screenshot 2023-06-06 at 23 56 28](https://github.com/Expensify/App/assets/25520267/ca772a66-9ac9-4668-b920-135e7aaff5f2)

> B initially saw just the checkbox without the Task title next to it. When he clicked into that thread and then back to DM with A, then only able to see the title

@hoangzinh Could you verify if this still reproduces? I see both the task title and the assignee.

> When display "Mark as Done" button, we haven't checked who can see that button yet. So whoever can access the taskReport, they can see that button.

@hoangzinh How are we going to check the button? Is this also apply to disabling or hiding the checkbox as well?

**Comment by mollfpr** [comment]
To summarize, we will fix 2 issues here:

1. Displayed assignee user display name/email in the `TaskHeader` for non-assignee users and not the owner.
2. Hide the _**Mark as Done**_ button for non-assignee users or not the owner

@joelbettner We can go with @hoangzinh proposal. With option 1, we can do the above fix.

🎀 👀 🎀 C+ reviewed!

**Comment by joelbettner** [comment]
@mollfpr yes, we can go with @hoangzinh proposal.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17940
https://github.com/Expensify/App/pull/18806


> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17940/files#r1246167109
https://github.com/Expensify/App/pull/18806#issuecomment-1612496961

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. Account A creates a task in the group DM (account A, account B, and account C) and assigns it to account B
2. Log in as account C, navigate to the task report above
3. **Verify** that account C can see account B displayName in the TaskHeader as an assignee.
4. **Verify** that account C can not click on the "Mark as done" button and account C can not see the three-dot in the top right
5. Log in as account B, navigate to the task report above
6. **Verify** that account B can see account B displayName in the TaskHeader as an assignee
7. **Verify** that account B can click on the "Mark as done" button and can see three-dot in the top right
8. log in as account A
9. Repeat 6->7
10. 👍 or 👎

**Comment by sonialiap** [comment]
@hoangzinh offer sent for fix 
@mollfpr offer sent for review

PR submitted on Jun 13 5:57 PM (Tuesday)
PR merged on Jun 19 12:31 AM (Monday)
By my count that's over 3 days (merge by Friday 5:57 PM would have been 3 days), so no bonus for this issue.

**Comment by sonialiap** [comment]
Both have been paid ✅
