### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Chat - @here doesn't appear among possible mentions if typing with capital H

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19304

## Action Performed:
1. Login to NewDot
2. open any chat
3. Click compose box
4. Type @Here

## Expected Result:
Mention @here should among option in popup

## Actual Result:
Mention @Here with capital H letter doesn't show @here in pop-ip however shows possible email with here.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Yes

**Reproducible in staging?:** New feature

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3f8362fd42a7cdc15bc6cb926d81f64be40e12c6d830a879ec2850fc5c554876

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ff515081d6b94bc</li>
        <li>Upwork Job ID: 1663649838954299392</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - @here doesn't appear among possible mentions if typing with capital H
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/21fefdb19cd7262f9caaad132d30ea426426f017/src/pages/home/report/ReportActionCompose.js#L465

We don't lower case search value when check if it is here mention
### What changes do you think we should make in order to solve the problem?
lower case search value before check if it is here mention like this
 if (CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT.includes(searchValue.toLowerCase())) {

### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment]
@kbecciv - Can you please include screenshots or videos from your testing and recreation when reporting a bug please? This helps reduce testing time on our end and is a critical component to clearing up any confusion we run into when trying to recreate ourselves.

**Comment by strepanier03** [comment]
I'm on iOS/Mac/ Chrome and unable to @here with a lower or upper case H. @kbecciv do you find the same or do you get a mention option with the lower case only?

**Comment by kbecciv** [comment]
@strepanier03 I added the video here
![image](https://github.com/Expensify/App/assets/93399543/7a9c0860-cb91-4a62-9c20-e7cfe218bd05)
But if you need extra reproduction video, please attached mine.

https://github.com/Expensify/App/assets/93399543/47b75e7d-ea23-4821-853b-55fa21ad2dc4

**Comment by strepanier03** [comment]
Thank you @kbecciv - my computer was acting super funny last week and I couldn't get @ here to work with lower or upper. 

However, today I was able to recreate this with no problem on Mac/Chrome. 

<img width="1062" alt="image" src="https://github.com/Expensify/App/assets/10925636/34ffb9c3-fd1d-49f2-96fa-f35b15e7eb95">

**Comment by strepanier03** [comment]
@madmax330 - Bump on the proposal, thank you!

**Comment by strepanier03** [comment]
@dukenv0307 and @fedirjh - I have hired you both to the job in Upwork. I'll check in shortly and pay out when I can.

**Comment by strepanier03** [comment]
I have finished paying and this is ready to close. 

Thank you both @dukenv0307 and @fedirjh for your hard work and the care put into this.
