### ISSUE TITLE
[HOLD for payment 2023-06-13] Update the pay button and settled message language

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19667]
Coming from internal https://expensify.slack.com/archives/C02HWMSMZEC/p1685102729936209?thread_ts=1684769643.018749&cid=C02HWMSMZEC

We will have to update the buttons and messages for the payment functionality on ious and expenses:

ReportPreview message & report action:
- Paid $100.00
- Paid $100.00 elsewhere
- Paid $100.00 using [Paypal.me](http://paypal.me/)

LHN iou/expenseReport title:
- Duraflame paid $100.00 (expenseReport)
- Tom paid $100.00 (iouReport)

Manual settlement option on the pay button:
- `Pay elsewhere`

After the dot separator on the amount field in the request view: 
- Cash * Amount * Paid

After the dot separator in the request preview component: 
- Cash * Paid

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161b85c1d0a339400</li>
        <li>Upwork Job ID: 1662068604121759744</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
If you want a visual ref, @mountiny! 

![image](https://github.com/Expensify/App/assets/16232057/4e989513-5e6a-4897-8020-966323f1469d)

**Comment by mountiny** [comment]
Thanks I will work on this soon

**Comment by mountiny** [comment]
Made a PR in Web and in App, waiting to confirm translations.

**Comment by trjExpensify** [comment]
Niceee!

**Comment by trjExpensify** [comment]
Okay, no checklist on this new feature and $1000 for @allroundexperts for the internal PR review. Offer [here](https://www.upwork.com/jobs/~0161b85c1d0a339400).

**Comment by trjExpensify** [comment]
Paid!
