### ISSUE TITLE
[Navigation Refactor] Implement the Stack navigation into NewDot

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19665]
Last step of https://github.com/Expensify/App/issues/11768

The last PR which entails all the navigation changes so it will deprecate drawer navigation and move to using stack navigation throughout the app.

Thoroughly tested with full regression suite of QA. Tested with contributors too.

**Comment by sakluger** [comment]
Hey @mountiny, need me to do anything here? Looks like the reviewer is from one of Software Mansion which I assume we pay outside of Upwork.

**Comment by WoLewicki** [comment]
Commenting 😅

**Comment by mountiny** [comment]
@sakluger nothing yet, there might be C+ review payment required at the end, thanks!

**Comment by sakluger** [comment]
@mountiny I'm OOO for a week and a half. If any payments need to be made before that, please remove me and add the Bug label to assign another BZ team member.

**Comment by mountiny** [comment]
Alright, this is done!
