### ISSUE TITLE
Dev: console error on create task when user skip Assignee while creating task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on + button
2. choose Assign task option
3. Enter title
4. click on Next button
5. click on share somewhere
6. click on any member from list
7.  click on confirm task

## Expected Result: 
should not show any console error
## Actual Result: 
shows console error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-1
**Reproducible in staging?:** needs reproduction (Occurs in Dev)
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c3c5c895-8300-4519-b0e5-ef6ac3b60e81

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684906837341679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
This is already being fixed in https://github.com/Expensify/App/pull/19639

**Comment by MitchExpensify** [comment]
Not overdue, weighting for https://github.com/Expensify/App/pull/19639 to hit staging to see if its fixed
