### ISSUE TITLE
Request Money - Mentions popup doesn't appear when editing message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Request money from user A to user B
3. Login as user B and open chat of user A
4. Click on IOU preview to open IOU Report
5. Verify the Three Dots Menu is not present in the header for the user because the user is the payer
6. Request money from user B to user A, bigger amount than in step 1

## Expected Result:
User B should have Three Dots Menu only for their requests

## Actual Result:
User B has Three Dots Menu for both requests - the one made by User A and by User B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/76ddd21deced8a2f71972b2fc127fa2379c1ba77b43779b24fc56ad81aa8e868

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Not sure if we can combine this job with this one -https://github.com/Expensify/App/issues/19643
