### ISSUE TITLE
Memeber can add comment in thread, and edit comment on workspace  with 'Admins only' post permission

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign with admin account A
2. Open announce room with multiple member
3. Click on header
4. Click on 'Settings' link
5. Verify that 'All members' option is chosen for 'Who can post' 
6. Shift to tab where member (account B is signed in)
7. Open the announce room
8. Send message
9. Shift to tab where admin is singed in
10. Repeat step 2 - 4
11. Click on 'Who can post' link
12. Change option to 'Admins only'
13. Shift to the tab where member account B is signed in
14. Reply to the sent comment in thread
15. Edit your sent comment
## Expected Result: 
Memeber shouldn't be able to reply in thread, and edit a comment when 'Who can post' access is admins only
## Actual Result: 
Memeber can reply in thread and edit comment

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2ce645c9-bc6c-47eb-80fe-b51ca65fd119

https://github.com/Expensify/App/assets/43996225/d404914b-ee89-42bc-9c79-e038d13e2b9d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684919088103509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Is this expected @amyevans ? Looking at this thread I think it might be but you'll know best! https://expensify.slack.com/archives/C04QEB4MJEQ/p1683225933382699

**Comment by amyevans** [comment]
Yes this is expected behavior. The purpose of the feature is to control the convo/reduce noise in the #announce room, but we're going to start with the _minimum_ amount of control, e.g. disallow members from posting if "Admins only", but they can still thread, react with emojis, or edit prior comments.
