### ISSUE TITLE
Reimbursement - No error message after simultaneously changing ‘Track distance’ off and online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with the same Expensifail account in the main testing device and a secondary device
2. On the main testing device, navigate to Workspace settings > Reimburse expenses
3. Turn off the internet connection on the device
4. Change the Distance rate to any number
6. On the Secondary device, navigate to Workspace settings > Reimburse expenses
7. Change the distance rate
8. On the main testing device - Enable the internet connection
9. Verify there's a message indicating something went wrong and to reload the page and try again

## Expected Result:
User get an error message in the 'Track Distance'

## Actual Result:
No error message after simultaneously changing ‘Track distance’ off and online
(Rate changes correctly)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1,3,19,2

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/3477534

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/2f6f3bf6f72fa0ce1ab82e709d8c2db33950c27d49441803ff9215b75d73474e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is not reproductible in Production
https://platform.applause.com/services/links/v1/external/df916358807f967d79d7d437d605de036ffa6017723a2057e6c5bccff705a685

**Comment by luacmartins** [comment]
I'm ending my day and we won't deploy until Monday. I'll come back to this then.

**Comment by luacmartins** [comment]
Looking into this now

**Comment by luacmartins** [comment]
PR merged. Closing issue.
