### ISSUE TITLE
[HOLD for payment 2023-06-07] [HOLD for payment 2023-06-05]  Reimbursements - The new rate is not grey out when it was changed offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19702]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18454 

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Reimbursements -> Rate
4. Turn off the internet connection
5. Change rate and unit value -> Save

## Expected Result:
The new rate is grey out in Reimbursements page

## Actual Result:
The new rate is not grey out in Reimbursements page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/310d0478d0a3bcb69df82330bcb4b5441ec5bc4eeb4398616079c3090c6550bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Verified on production that we currently gray out the fields if they are changed while offline:

<img width="527" alt="image" src="https://github.com/Expensify/App/assets/5997400/04dd9d41-df51-41b9-a9a3-aecf4bb7229c">

**Comment by sakluger** [comment]
I commented on the PR.

**Comment by ShogunFire** [comment]
I am going to do a PR for this

**Comment by luacmartins** [comment]
I'm addressing this issue in https://github.com/Expensify/App/pull/19748

**Comment by luacmartins** [comment]
Checklist complete

**Comment by luacmartins** [comment]
@sakluger are we still waiting on payment?

**Comment by luacmartins** [comment]
Actually, there are no payments due here since:

- Reporter is Applause
- This was a regression from a contributor's PR, but I submitted a fix
- C+ didn't review the PR

Gonna close. Please reopen if I missed anyhting.
