### ISSUE TITLE
Web - Workspace -  Arrows stop scrolling members list after return from 'Add message' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with Expensifail account and go to workspace or create workspace
2. Go to Workspace > Members
3. Select 'Invite' and scroll members list with keyboards arrows
4. Select some members by Enter key and press Cmd+Enter to go to next page
5. Click to 'Back' button
6. Scroll members list with keyboards arrows

## Expected Result:
The user can scroll through the list using the arrows keys

## Actual Result:
Arrows stop scrolling members list after return from 'Add message' page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/faf93389f96755ab7b62d38c8c446437ba247b9f6f51a629c389050da58ecbc8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PrashantMangukiya** [comment]
This is dup of https://github.com/Expensify/App/issues/19700

**Comment by isabelastisser** [comment]
Dupe, closing!
