### ISSUE TITLE
 'Who can post' setting with no edit access is displayed for split bill participants

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' icon
2. Click on 'Split bill' link
3. Enter amount > click on 'Next' button
4. Search user > select user B > click on 'Next' button > click on 'Split' button
5. Click on 'IOU preview component'
6. Verify a new chat is opened
7. Click on the chat header
8. Click on 'Settings' link
9. Observe that 'Who can post' setting without edit access is displayed
10. Switch to the  tab where user B is signed in
11. Open the sent message
12.  Repeat steps 5 - 9
## Expected Result:
'Who can post' setting should not be available for both participants since none of the participants can change the setting between 'All members' and 'Admins only'. This feature is available on workspace and admin can change the setting from 'All members' to 'Admins only'
## Actual Result:
'Who can post' setting is available for both split bill participants
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d17e7676-0c78-49e6-8456-497299dcf08d

https://github.com/Expensify/App/assets/43996225/e296e267-9559-4dea-8a2d-ebc4850b98b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684956711277149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@Natnael-Guchima 
If `Who can post` isn't actionable, does it _matter_?  
<img width="394" alt="image" src="https://github.com/Expensify/App/assets/22508304/8e40ffee-8c91-41c8-b79d-97792117140f">

>'Who can post' setting should not be available for both participants since none of the participants can change the setting between 'All members' and 'Admins only'.

Technically, `all members` in the split can post, right?  I think the other option would be to just not show 'who can post' which wouldn't be consistent. 

(I'm not trying to sound snarky, apologies if it comes across that way)

**Comment by Natnael-Guchima** [comment]
@mallenexpensify you didn't sound to be snarky😁. I think the flow after [clicking on the IOU preview component](https://github.com/Expensify/App/issues/19715#:~:text=Click%20on%20%27IOU%20preview%20component%27) seems to be changed on the latest release. I am not able to find the settings section with split money flow. I think the issue to remove 'all members' option would be irrelevant if the flow is removed. 



https://github.com/Expensify/App/assets/57330233/797ac121-3a61-471a-a3b3-c7f62d3cf056

**Comment by mallenexpensify** [comment]
OK, thanks @Natnael-Guchima , gonna close then, comment if you (or anyone) disagrees.
