### ISSUE TITLE
Room settings- No option to invite users to room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19714]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing PR #18662
## Action Performed:
1. Launch the app and login
2. Click the global menu > New room
3. Create a public room.
## Expected Result:
Option to invite or add user to room

## Actual Result:
No option to add or invite user to room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0fd850a5-7903-49c8-88a4-7ed440dab8b5

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
This bug report is lacking specific details and the recording is really long winded/slow. I am struggling to follow what steps you actually took.

**Comment by michaelhaxhiu** [comment]
This bug might be critical and worth fixing, but I can't spend time trying to reproduce this in it's current stature.
