### ISSUE TITLE
Chat - Chat disappears in chat switcher after click on IOU for same user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify desktop app
2. Create a new chat with a different user B
3. Navigate to created chat with user B
4. Click on "+"
5. Click on "Request money"
6. Insert amount
7. Click "Next"
8. Click "Request"
9. Press CMD+K
10. Click on IOU created at step 8 (User B owes...)
11. Press CMD+K

## Expected Result:
Chat created at step 2 is displayed in chat switcher

## Actual Result:
Chat created at step 2 disappears from chat switcher, only IOU is displayed in the list. After restarting the app chat doesn't reappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/7889599d3166b9fb83ba0200f7a349c81a6fe6cb6ee94eb53506901e6b34481b

https://platform.applause.com/services/links/v1/external/4eb721d1e86e8de346a500ddddf6d3a5061054352898350cad76321e209cf4bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is done.
