### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Cache is not cleared completely after sign out of the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Perform few actions in the app
2. Sign out of the app
3. Open the app info
## Expected Result:
All data and cache are cleared
## Actual Result:
Still showing 144mb of data cached and 32 mb of user data
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (2)](https://github.com/Expensify/App/assets/43996225/147086f5-c11a-4a43-b71e-b01f59cd9a6b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684945967487669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121d019453eb06be4</li>
        <li>Upwork Job ID: 1663667563279052800</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Confirmed that the cache is not cleared after signing out. I tried sending an image and the cache change to 1.2MB, then I signed out and the cache was still at 1.2 MB.

**Comment by rvenky125** [comment]
I'm willing to fix the issue, can I?

**Comment by mollfpr** [comment]
Reviewing proposal!

@rvenky125 Could you propose a solution? Thanks!

**Comment by behind24proxies** [comment]
full of bugs bruh

**Comment by rvenky125** [comment]
> Reviewing proposal!
> 
> @rvenky125 Could you propose a solution? Thanks!

Can you pls assist me that how can run the project with windows environment. I installed all node modules and if run `npm run android`, I'm getting that the _scripts_ command not found.

**Comment by sakluger** [comment]
Readded BZ label since I'm OOO next week.

**Comment by alex-mechler** [comment]
@mollfpr have you reviewed @allroundexperts's proposal? https://github.com/Expensify/App/issues/19767#issuecomment-1567533987

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

>We can also use [this](https://github.com/sowlutions/react-native-clear-cache) package to clear the app storage on logout. This package is forked from another package which wasn't working for RN > 0.60. If required, we can just copy the native files and use those directly in our code as custom native modules (https://reactnative.dev/docs/native-modules-android)

@alex-mechler I'm inclined to go with the alternative solution of @allroundexperts proposal. The reason is `react-native-fs` seems complicated to implement. What do you think?

**Comment by alex-mechler** [comment]
I agree, the alternative seems more straight forward here. Is there any concern about data we might not want cleared on logout? I don't think there is anything off the top of my head

**Comment by alex-mechler** [comment]
Great point about it being more well maintained. Its certainly preferable to use a well maintained library like that. @mollfpr do you have concerns with `react-native-fs` other than it being more complex @mollfpr?

**Comment by mollfpr** [comment]
I don't have other concerns on `react-native-fs` 😅

**Comment by alex-mechler** [comment]
Sounds good, lets go with @allroundexperts proposal then!

**Comment by sakluger** [comment]
Back from vacation, unassigning @kadiealexander. Also sent offers to @allroundexperts and @mollfpr so when the PR is deployed and settled we can pay out.

**Comment by sakluger** [comment]
Hey @mollfpr could you please make sure to complete the BZ checklist when you have a chance so that I can pay out the contracts tomorrow? Thanks!

**Comment by sakluger** [comment]
Bump @mollfpr on the BZ checklist.

**Comment by mollfpr** [comment]
Sorry for the delay @sakluger 

> [@mollfpr / @allroundexperts] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr / @allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is an improvement for the native app to clean the cache on sign-out.

> [@mollfpr / @allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is not a bug, so a regression test should be enough.

> [@mollfpr / @allroundexperts] Determine if we should create a regression test for this bug.

Yes!

> [@mollfpr / @allroundexperts] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Prerequisites** installed New Expensify app.

**For Android**

1. Go to Settings -> Storage -> Other Apps -> New Expensify
2. Note the cache size, open the app, and log in to any account.
3. Logout and do step 1
4. Verify that the cache size is significantly less.

👍 or 👎

**Comment by sakluger** [comment]
Thanks! Regression test issue created, contracts paid, all done here!

**Comment by mallenexpensify** [comment]
This is happening to me on iOS, I can create a new bug report/issue, want to reopen now to see if anyone knows _why_ it might be happening. 

On iOS, latest staging build, testflight
- Sign out of mallen@expensify.com account
- Sign in with a new test account mallen+1122@expensifail.com
- Observe old chats from mallen@expensify.com in LHN (when click on them I get 404'd)

**Comment by mallenexpensify** [comment]
I guess that means no one knows why it might be happening 🧌 
https://expensify.slack.com/archives/C049HHMV9SM/p1725058768402589
