### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Edited link as thread title shown as ExpensiMark syntax in LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: Switch to `Most Recent` mode under Account > Preferences.
1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send a link to a chat (example : https://google.com/)
3. Make a thread by clicking Reply in Thread
4. Go back to the original chat and edit the link with different title (example [Irrelevant link](https://google.com/))
5. Examine the LHN for the thread title
## Expected Result:
 Thread title in LHN should only contains the link name
## Actual Result: 
Thread title in LHN changed into its ExpensiMark syntax

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2c0748cf-485d-42c5-bc08-114c95428757

https://github.com/Expensify/App/assets/43996225/ba173923-c53f-4134-a34f-8b62d5e45d38

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685095868502049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573a097ca5bd829a</li>
        <li>Upwork Job ID: 1664723514166583296</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
Interesting, this is small but it's valid. Let's fix it, but I'd love a bud check from the C+ on whether or not this will fixed in upcoming thread enhancements. 

My take is - no it will not be fixed independently, so let's do it here.

**Comment by michaelhaxhiu** [comment]
assigned, commenting to remove overdue label

**Comment by michaelhaxhiu** [comment]
Review started today, great progress so far yall :)

**Comment by michaelhaxhiu** [comment]
@thesahindia is this ready for payment now? :)

**Comment by michaelhaxhiu** [comment]
Invited C+ and bug reporter to the job - https://www.upwork.com/jobs/~0196491d359ff7e166

@dukenv0307 can you apply to the job please? Im not able to find your upwork profile

**Comment by kerupuksambel** [comment]
> Invited C+ and bug reporter to the job - https://www.upwork.com/jobs/~0196491d359ff7e166
> 
> @dukenv0307 can you apply to the job please? Im not able to find your upwork profile

Job accepted, thank you!

**Comment by michaelhaxhiu** [comment]
- [ ] C+ @thesahindia $1500
- [ ] Contributor @dukenv0307 $1500
- [ ] Bug reporter @kerupuksambel $250

**Comment by michaelhaxhiu** [comment]
@dukenv0307 lmk when you accept the job offer and I'll issue payment

**Comment by michaelhaxhiu** [comment]
All parties paid. Final step @thesahindia ready to do the checklist?

**Comment by michaelhaxhiu** [comment]
thanks! all set.

**Comment by JmillsExpensify** [comment]
Reviewed the details for @thesahindia. $1,500 approved for payment in NewDot based on BZ summary above.
