### ISSUE TITLE
[$1000] Admins channel not showing the updated rate/uint changes in a new UI

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new workspace
3. Go to admins channel
4. Now go to the workspace and try to edit the workspace name and the default currency and notice that the admins channel shows the updated workspace name and currency message
5. But now try to change the rate/unit of the same workspace and notice that it doesn't display the updated rate/unit message on admins channel
6. (To cross check, since new.expensify has not been updated now , I tried on it and in the older version or in the previous UI, when we used to change the rate/uint of the workspace, it used to give us the updated rate/unit on the admins channel)
## Expected Result:
 The admins channel should display message on updating rate/unit as how it used to do earlier (Or how it shows message when we update the workspace name or currency)
## Actual Result: 
The updated rate/unit message is not displayed on admins channel
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** N (New UI for track rates)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0a89d0a8-6cb0-4c5b-ab00-8baf8290c2d0

https://github.com/Expensify/App/assets/43996225/9d1c9a24-3bc0-4f11-b1c8-5dd7b8ef33aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685093646369479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01252e932ddd3b2115</li>
        <li>Upwork Job ID: 1663411001871712256</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by pecanoro** [comment]
@sakluger Should this one be triggering a message in the admins room?

**Comment by pecanoro** [comment]
@sakluger bump on my previous question 😄

**Comment by pecanoro** [comment]
@sakluger another friendly bump

**Comment by pecanoro** [comment]
@hayata-suenaga Can you guide me to where this happens in the code? This is an internal bug and not external, right?

**Comment by hayata-suenaga** [comment]
The unit used for mileage is part of an attribute of a custom unit.

<img width="300" alt="Screenshot 2023-06-05 at 5 24 53 PM" src="https://github.com/Expensify/App/assets/98560306/554c1b40-08d9-4ab6-b64f-2fd1c5bb7e5a">

it's handled here

https://github.com/Expensify/Web-Expensify/blob/f7f9d92fe2d44fdfb594938fa3bbe8dba65c4c72/lib/Report/Action/PolicyChangeLog/Utils.php#L146

The currency under rate

<img width="300" alt="Screenshot 2023-06-05 at 5 29 04 PM" src="https://github.com/Expensify/App/assets/98560306/99992ede-7e72-4dac-a936-b18b9e3e5031">

and it's handled here

https://github.com/Expensify/Web-Expensify/blob/f7f9d92fe2d44fdfb594938fa3bbe8dba65c4c72/lib/Report/Action/PolicyChangeLog/Utils.php#L255

**Comment by hayata-suenaga** [comment]
if it used be working before, I don't know why it suddenly stopped working...

**Comment by pecanoro** [comment]
Thanks, I will try to debug it and come up with a fix.

**Comment by pecanoro** [comment]
Hmm interesting, the code you [linked](https://github.com/Expensify/Web-Expensify/blob/f7f9d92fe2d44fdfb594938fa3bbe8dba65c4c72/lib/Report/Action/PolicyChangeLog/Utils.php#L146) is not called at all when updating the rate. I will follow the flow.

**Comment by pecanoro** [comment]
@hayata-suenaga I found the problem, it's because we call updateWorkspaceCustomUnitAndRate instead of updateWorkspaceCustomUnit

**Comment by hayata-suenaga** [comment]
Was any change introduced to change the method to call?

**Comment by pecanoro** [comment]
Yes, there was a PR to combine two API requests into one here: https://github.com/Expensify/Web-Expensify/pull/37117 Not sure if your changes or @joelbettner PR got merged first, maybe they were being merged around the same time and forgot to include the changes from each other.

**Comment by hayata-suenaga** [comment]
Would you like me to create a fix PR? or you already started working on the fix?

**Comment by pecanoro** [comment]
I already started working on it, no worries 😄

**Comment by bfitzexpensify** [comment]
Not overdue, PR has been merged and deployed to prod

**Comment by pecanoro** [comment]
It should have been closed automatically, this is done, closing.

**Comment by priya-zha** [comment]
@pecanoro @bfitzexpensify I'm the external reporter for this bug.

**Comment by pecanoro** [comment]
Ahh sorry, @bfitzexpensify can you handle payment for that?

**Comment by bfitzexpensify** [comment]
Payment complete! Let's close this out.
