### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] The name/picture is not dynamically updated if the emoji popup is open but works well with emoji numbers

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go to staging dot on chrome -> User 1
2. From User 1, go to any chat with User 2 and message them
3. React to the same message
4. From User 2 account, react to the same emoji and right click on emoji to openup the popup
5. From User 1 account. unreact to the emoji and see that on User 2 side, the user who reacted to the emoji and the emoji number dynamically updates
6. From User 1, now try to change the display name or the profile picture and see that on the User 2, the display name  doesn't update dynamically on popup (you need to click somewhere else and again right click on the emoji to see the updated display name in the popup)
## Expected Result: 
The profile picture or the display name of the User 1 should be dynamically updated on the emoji reactions list on the popup
## Actual Result: 
The name/picture is not dynamically updated if the emoji popup is open but works well with emoji numbers

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a61316c0-a726-40fa-9c59-81a0c0a1847c

https://github.com/Expensify/App/assets/43996225/3898b038-da56-4169-a937-5a9bbc61ea46

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685097484082299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011746eb5669d607e7</li>
        <li>Upwork Job ID: 1663928154895839232</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by anmurali** [comment]
@fedirjh can you please review @hoangzinh proposal and comment here?

**Comment by dangrous** [comment]
Okay so this proposal makes sense BUT given that we're eventually going to be updating this component from a class to a function, we won't be able to use `shouldComponentUpdate` at that point.

Do you think we can figure out a proposal that would still work once that's updated, or should we move forward with this now and let it be adjusted when the update is made? I'm not sure if there would be an option that would work in both cases or if we'd need to refactor everything. Let me know what you think, @fedirjh and @hoangzinh !

**Comment by dangrous** [comment]
Okay great! That makes sense. Assigning now.

**Comment by dangrous** [comment]
Agreed @fedirjh!

I think we're just waiting on payment then @anmurali - thanks!

**Comment by anmurali** [comment]
Sent offers

**Comment by avi-shek-jha** [comment]
@anmurali Have you sent the offers already? Because just checked my upwork, I haven't received it yet.

**Comment by anmurali** [comment]
@fedirjh @hoangzinh have been paid with bonus. @avi-shek-jha - can you link your Upwork profile? I cannot find you.

**Comment by avi-shek-jha** [comment]
@anmurali Here's my profile: https://www.upwork.com/freelancers/~01a90e548bf808418c

**Comment by anmurali** [comment]
@avi-shek-jha - https://www.upwork.com/nx/wm/offer/25386273

**Comment by avi-shek-jha** [comment]
Thanks. Accepted.
