### ISSUE TITLE
Edit task title is showing as thread reply, but no actual replies are present when clicked

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat
2. Create a task
3. Edit the task title
4. Go back to the chat, notice a reply is shown in the task
5. Click on the reply, notice no replies are shown
## Expected Result: 
No replies should be shown after task edit
## Actual Result: 
A reply is shown after task edit. Clicking on the reply shows nothing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8c95aab4-0ef2-4b24-8e63-1f6273a32ed5

https://github.com/Expensify/App/assets/43996225/b8abc517-9df2-44fa-933d-48d3ad0f0f86

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685153800863179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3a744a82e31ee45</li>
        <li>Upwork Job ID: 1663511445842067456</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Grabbing this to get some practice with tasks!

**Comment by Gonals** [comment]
I noticed we are also NOT updating the task name in-chat 😬

**Comment by laurenreidexpensify** [comment]
Offer sent in upwork @thesahindia

**Comment by Gonals** [comment]
> Do not show Task edit as replies in chat Expensify/Auth#8030

We didn't require C+ review for this one, as the fix was in Auth

**Comment by Gonals** [comment]
Already fixed!
