### ISSUE TITLE
[HOLD for payment 2023-06-08] Fix unnecessary re-renders in the ReportActionItem

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19804]
### Problem

The reportActionItem memoization conditions have been incorrectly refactored when moved to the function component and now they re render more times than needed

### Why is it important?

This leads to worse performace

### Solution

Fix the memo conditions so we do not re-render the component unnecesarily

**Comment by WoLewicki** [comment]
Commenting

**Comment by mountiny** [comment]
Handled by SWM and I will do the checklist so no need for payment through Upwork here.

**Comment by WoLewicki** [comment]
It's been fixed already iirc 😅
