### ISSUE TITLE
Updated mock for v1 of NewDot Search

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19806]
Part of the new dot search v1 https://github.com/Expensify/Expensify/issues/261800, we will be showing the messages results in the Search results. The current mocks for the search results do not include the report in which the message is located but thats an important information for the user to be able to quickly know if its the message they have searched for.

Current mock with the messages: - we would need to add the report name to the result (ie its a message from Shawn in #social room or in group message with Vit and Daniel)

![image](https://github.com/Expensify/App/assets/36083550/ae6daaa4-a033-44de-b898-0a59db96d4ec)

____

Additionally, since the online search is triggered when user presses enter on the search, we should inform the user. As they type, we only show the offline results (chats, loaded threads...), but it might not be clear they have to hit enter to get messages results too. We got a mock up with this change using a similar pattern as if text input validation fails, but grey text error instead. This message disappears once user searches online.

Let us know if the current mock here looks fine

![image](https://github.com/Expensify/App/assets/36083550/7c2abfac-2713-44df-931a-02f8681d6f60)

Here is a link to the [figma file](https://www.figma.com/file/Qv92AGNVwy3sRl9uOY01YH/Search?type=design&node-id=207-1062&t=eZ6DfUKK2sXvmPKH-0)

**Comment by shawnborton** [comment]
I wonder if we should take this one to Slack first? [There is an existing conversation going on](https://expensify.slack.com/archives/C04QEB4MJEQ/p1685421995327269) about how to show threads in the LHN, and it seems like it impacts basically how we show anything in the LHN and the relationship between that and the chat header once you actually view something. 

I am guessing that all results in Search should look identical to how they might show up in the LHN?

**Comment by mountiny** [comment]
It was [this long thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1683069450644149) I believe where we have brainstormed what to do.

> then subsequently hitting enter would yield even more/different results

It would not load different results. The chats/ rooms are same. The only thing we load from backend are messages/ searching through messages.

Hence we show results locally/ offline as you type so you can still use the search as chat switcher but if you want to search through messages you need to hit Enter to fetch the messages.

The problem here is that we cannot make a new API request anytime we 

> I am guessing that all results in Search should look identical to how they might show up in the LHN?

It would probably be identical, cant think of anything where it would differ right now.

**Comment by shawnborton** [comment]
Not exactly sure where we landed, but it seems like the segmented control idea was favored in the Slack thread? That looks like this: 

![image](https://github.com/Expensify/App/assets/2319350/d224074c-a7cc-46d4-b116-7263ea6080fe)

**Comment by mountiny** [comment]
I think for v1 we are going to continue without the segments, I think the details are so small at this point we can nail them down in PR review with you, I am going to close this out thank you very much for help 🙇  feel free to reopen. We will ping you in the PR reviews.
