### ISSUE TITLE
Web - Workspace -Three dots are highlighted with a blue frame when clicking Esc for closing.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to Settings -> Workspaces -> Open any WS
4. Press three dots
5. Press Esc

## Expected Result:
Three dots NOT highlighted

## Actual Result:
Three dots are highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/907e8fd2fb7bf60ebb6d2c01e5ee77318a881481ae76f92eac670399a3612d24

https://platform.applause.com/services/links/v1/external/467e0bcdfcf89f242fa24ffedae6aef3b7b01f4eb69a0a65f5e918181d9b4a9c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
I'm unable to reproduce this!
