### ISSUE TITLE
[HOLD for payment 2023-11-22] [Feature request] Replace the moment library with some lightweight date utility library

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19810]
### Problem

Coming from this [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1684312385467959) and Callstack proposal.

The `moment` library is a powerful library but has performance disadvantages that comes from its OOP design. This design makes it fail working with tree-shaking, so it’s bundle size it’s huge (especially with internalisation or timezone support enabled) - this impacts mostly the web version of Expensify app.

Moreover, the `moment` library is now a “legacy project in maintenance mode” so it is not actively developed anymore.

More about above here: https://momentjs.com/docs/#/-project-status/

### Solution

There are some other powerful yet lightweight date libraries like `day.js` (the most lightweight) or `date-fns` (supports tree-shaking) that could successfully replace the moment library in our app. My personal preference is `date-fns` because of its support for tree-shaking and wider popularity among community, but using `day.js` may be easier from the Expensify codebase perspective because of its API that is quite similar to the moment one (e.g. parsing date strings using constructor or day/month/year getters etc. - please check the link I’ve posted below for more details).

**Context/Examples/Screenshots/Notes:** More about the subject, containing the comparison of the most popular moment replacements can be found here: https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md

- [ ] Add an eslint rule once we are done which will prohibit adding the library back

**Comment by mountiny** [comment]
No need to action here now Anu, Callstack will work on this

**Comment by burczu** [comment]
Hey! It's Bartek from Callstack - expert contributor group - I'll be working on this one.

**Comment by mountiny** [comment]
Thanks, please, first post a plan of how to exectute this migration before you go ahead.

**Comment by mountiny** [comment]
@burczu would you be bale to share a plan for this project and some ETA, thanks!

**Comment by burczu** [comment]
Hey @mountiny! Sorry for being silent in this issue - I'm 100% involved in the Secure Logins issue (migration to use accountID's instead of emails in personal details) right now and had no time for anything else. I'll do my best to share some plan for this issue today or on Monday.

**Comment by burczu** [comment]
Ok, @mountiny my plan is simple actually:

1. Identify all the places where we use the `moment` library
2. Check if that places are covered by unit tests
3. Cover all the places that are not covered with unit tests to, later, make sure that we didn't break anything while doing the refactor
4. Replace all the usages of the `moment` lib with `date-fns` library (I think it is the best choice because of its popularity in the community)
5. Check if tests still passing

In terms of ETA, it depends on how much tests I will need to add as it's the most time consuming task in this plan. I would say more once I check the current coverage.

What do you think?

**Comment by mountiny** [comment]
@burczu thanks for the update, I like including the unit tests, the plan sounds great to me.

**Comment by hannojg** [comment]
Interested in seeing this one as well, as I am looking at the minute at performance issues with momentjs code (which I'd like to replace by date-fns).

**Comment by mountiny** [comment]
This will continue after the secure logins bugs are fixed

**Comment by mountiny** [comment]
Nice, CalendarPicker will be refactored soon not sure if it would be important, but something to keep an eye on

**Comment by burczu** [comment]
Not overdue: I made some progress in writing tests I've planned, but I had to switch to another issue for now. I think I'll be able to get back to this one next week.

**Comment by anmurali** [comment]
@burczu - do you have an update?

**Comment by burczu** [comment]
@anmurali I'm sorry, I had no time for this issue last week - hopefully this week will look better

**Comment by burczu** [comment]
Update: I've done some progress today, but I'll be OOO starting on Monday till July 25th - once I'll be back, I think I'll have the time to 100% focus on this issue because my other issues will be taken over by other Callstackers.

**Comment by mountiny** [comment]
Bartek has been ooo this week

**Comment by waterim** [comment]
Update: 
Covered main files with tests, updated DateUtils and ValidationUtils with date-fns.

**Comment by mountiny** [comment]
@waterim Thats great! Would you be able to open a draft PR? it would also be better to dived this up to couple of smaller PRs to avoid having a large PR which will be super hard to review.

**Comment by waterim** [comment]
@mountiny Sure! Will create a PR after fixing timezone issues I have now after switching from moment. I think 1-2 hours

**Comment by waterim** [comment]
@mountiny Sorry about the delay, got stuck in one test with rewriting from moment()

**Comment by waterim** [comment]
@mountiny Here is adding a [draft PR](https://github.com/Expensify/App/pull/23520/)
Still some moment in tests and it will be deleted asap, but utils were rewrote fully.
I have one question regarding these "a few seconds ago" from moment default **moment(date).fromNow()** and "less than a minute ago" from date-fns default **formatDistanceToNow(new Date(date), {addSuffix: true});**
Question is: Do I need to adjust date-fns to return exactly the same messages as a default function from moment did?
<img width="1347" alt="image" src="https://github.com/Expensify/App/assets/39777589/89bbe0f8-2ff8-4886-a9c6-fe8b52c828df">

**Comment by mountiny** [comment]
@waterim Could we do that in some config or it would require a patch? if we can do this in some config, than yes, but I dont thing this is work making a patch

**Comment by waterim** [comment]
@mountiny We can add some custom function instead of date-fns `formatDistanceToNow` to achieve exact same strings as moment did. 
But Im not sure that the difference in a default behaviour is crucial, like "a minute ago" and "1 minute ago" 

Date-fns is not supporting some custom configs for `formatDistanceToNow` function unfortunately. 
All it has: addSuffix, includeSeconds and locale

**Comment by mountiny** [comment]
@waterim where is this used in the app?

**Comment by waterim** [comment]
@mountiny  Just [here](https://github.com/Expensify/App/blob/104e65a598543c1f6a89e0146d36e0953d73ef81/src/components/withLocalize.js#L74)
And after passing to [LocaleContext.Provider](https://github.com/Expensify/App/blob/104e65a598543c1f6a89e0146d36e0953d73ef81/src/components/withLocalize.js#L144)

**Comment by waterim** [comment]
Hello @mountiny!
My upate: removed fully moment from utils functions and tests, resolved all comments on my PR. 
Now after I started testing the app I found that there are a lot of places in the code where we are using Moment Object functions which on top of the utils functions. 
Something like this: 
`currentUserLocalTime = DateUtils.getLocalDateFromDatetime(props.preferredLocale, null, props.timezone.selected)`
And after we are using:
`currentUserLocalTime.zoneAbbr()` where `zoneAbbr()` is a Moment function. 
Now Im going file by file, line by line to change all these Moment Object functions.

**Comment by mountiny** [comment]
@waterim Could we make sure we can split this up to smaller PRs so before we continue working further I think it would be great to get the PR which sets up the date-fns in the app and adds all the tests in place. Then we can start to slowly migrate over all the usages of Moment and eventually deprecate it and add some ESLint rule which will prohibit people of adding it back

**Comment by waterim** [comment]
@mountiny yes, sure, agree that it will be easier and safer.
Will redo my PR tomorrow to have only tests and new librarY

**Comment by mountiny** [comment]
@waterim appreciate it 🙇

**Comment by waterim** [comment]
@mountiny Hello Vit, can you please assign me to this task?

**Comment by mountiny** [comment]
@waterim Thank you 🙇 assigned and merged, I think we are good to work on the other prs.

**Comment by waterim** [comment]
@mountiny great, thank you)
For the next PR I think we can go with rewriting ValidationUtils to date-fns and all files which are using it

**Comment by mountiny** [comment]
@waterim lets do that

**Comment by mountiny** [comment]
Another one merged 🚀

**Comment by waterim** [comment]
@mountiny nice to hear 🙃

**Comment by waterim** [comment]
@mountiny My update: Moving all usage of moment functions outside of the utils to the DateUtils.
I mean all formattings, using of the moment.zoneAbbr() etc. 
Doing that to have all in one place, for the future it can help with rewriting or changing code related to timezones and dates.

**Comment by waterim** [comment]
Hey @mountiny, here is a PR regarding DateUtils and timezone fixes

**Comment by mountiny** [comment]
Added c+ to the issue and PR

**Comment by mountiny** [comment]
Merged, great job everyone, lets hope there wont be any issues with it

@waterim @burczu should we consider addig some rule for preventing people re-introducing `moment`

**Comment by situchan** [comment]
Regression: https://github.com/Expensify/App/issues/25650

**Comment by waterim** [comment]
@mountiny Here is a [PR](https://github.com/Expensify/App/pull/26248) with tz.guess and polyfills, please test it too :)

**Comment by mountiny** [comment]
@waterim is still working on this one and there is couple of prs left to get us over the finish line and remove moment from the app

**Comment by waterim** [comment]
@mountiny actually I have an update, I have enough capacity on Friday and today to proceed and will create PR today/tomorrow with new changes

**Comment by situchan** [comment]
Heads-up: [PR](https://github.com/Expensify/App/pull/26248) which linked this issue caused regression - https://github.com/Expensify/App/issues/26719
It was fixed in https://github.com/Expensify/App/pull/26902 but reverted in https://github.com/Expensify/App/pull/26248.

**Comment by waterim** [comment]
@mountiny PR is open, last PR will be with datepicker and moment will be removed FULLY from the project!

**Comment by waterim** [comment]
After my last changes, 2 years of history will disappear into oblivion

<img width="663" alt="image" src="https://github.com/Expensify/App/assets/39777589/e524a69b-ae8e-4a30-8895-80956a54b232">

**Comment by waterim** [comment]
For the last changes will be:
1. To remove moment from github actions
2. To remove moment from package.json
3. To remove moment/locale from App.js

**Comment by waterim** [comment]
Hopefully no regression will appear :)

**Comment by mountiny** [comment]
Thanks for continued work on this ❤️

**Comment by mountiny** [comment]
@allroundexperts could you please summarize what needs to be paid here to you, it was couple of PRs.

No Testrail cases are needed fo this, it was a migration of a package for performance reasons and no new behaviour has been added in this issue

**Comment by allroundexperts** [comment]
Hi @mountiny!

It's been a long issue but I've tried to summarise the payment below. Please let me know if I missed something.

1. https://github.com/Expensify/App/pull/26248 (This caused a regression but it was found after 7 days it was deployed to production) -> Flat review ($500)
2. https://github.com/Expensify/App/pull/28175 -> Flat review ($500)
3. https://github.com/Expensify/App/pull/29062 -> Had a regression and was reverted and then redone [here](https://github.com/Expensify/App/pull/29984). The second go had regressions as well. So the penalty doubles. ($125)
4. https://github.com/Expensify/App/pull/31071 -> Flat review ($500)

**Comment by mountiny** [comment]
Sounds good to me, Could you please request $1625 on NewDot and note here, then we can close this issue. Thanks!

**Comment by allroundexperts** [comment]
All done @mountiny!

**Comment by mountiny** [comment]
Thanks, we should be all good here and we can close, thanks @waterim and @burczu and @allroundexperts for the effort here

**Comment by JmillsExpensify** [comment]
$1,625 payment approved based on [this comment](https://github.com/Expensify/App/issues/19810#issuecomment-1827847372).
