### ISSUE TITLE
[HOLD for payment 2023-06-07] [Awaiting bug report payment on June 5th] App crashes when opening report as anonymous user

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#19823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Sign out
- Open a public room (like the [ExpensiConX #announce room](https://staging.new.expensify.com/r/3504895439653267))
- Verify you can see the announce room as an anonymous user (random email).
- Click on Sign in or any action that should not be allowed to an unauthenticated user
- Verify you're redirected to the signin page
- Enter email/phone
- Enter magic code
- Verify you can see the public room in the LHN

## Expected Result:
- App should not crash

## Actual Result:
- App crashed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Reproducible in staging?:**
**Reproducible in production?:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1685451659037849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
CC @situchan

**Comment by Julesssss** [comment]
Removing blocker label as [the fix was CPd](https://github.com/Expensify/App/pull/19818)

**Comment by kadiealexander** [comment]
@Julesssss I'm unclear on who (if anyone) needs to be paid out for this. It seems like it was entirely handled internally?

**Comment by kadiealexander** [comment]
Sent an offer to @situchan!

**Comment by situchan** [comment]
This is not a normal external contributing flow but as I fixed this issue (I am the [PR](https://github.com/Expensify/App/pull/19818) author), I think I am also eligible for normal compensation. Maybe timeline bonus applies as well?

**Comment by kadiealexander** [comment]
Thank you for linking that Slack thread, looks like you did a lot of work on this! Since the PR was merged within a few hours of this issue being opened, I'm happy to pay:

Reporting bonus: $250
Payment for PR: $1000
Speed bonus: $500

@Julesssss would you agree?

**Comment by situchan** [comment]
This was first reported by @mountiny so not eligible for reporting bonus.

**Comment by kadiealexander** [comment]
Thanks for flagging!

**Comment by kadiealexander** [comment]
@Julesssss just bumping for a buddy check on the payment above please!

**Comment by Julesssss** [comment]
> @Julesssss would you agree?

Sorry, yeah that looks good to me!

**Comment by kadiealexander** [comment]
@situchan I've sent you a new offer [here](https://www.upwork.com/ab/applicants/1666323207606398976/offers), please accept and I'll get this paid.

**Comment by situchan** [comment]
@kadiealexander thanks, accepted.

**Comment by kadiealexander** [comment]
All paid! Thanks @situchan.
