### ISSUE TITLE
[HOLD for payment 2023-06-08] [Manual Requests] [Clean up] Remove unused ReportTransactions and IOUTransactions

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#19827]
We changed the layout of IOUs for Manual Requests, which means that ReportTransactions and IOUTransactions are no longer used in the codebase and can be removed.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019273e5c8d5968131</li>
        <li>Upwork Job ID: 1663579380580065280</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug.
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [x]  [@jliexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

Nothing to update just some clean up

**Comment by jliexpensify** [comment]
@luacmartins - this is a $1000 payment for Santhosh right?

**Comment by luacmartins** [comment]
@jliexpensify correct!

**Comment by jliexpensify** [comment]
Heyoo @Santhosh-Sellavel going to pay you now.

**Comment by jliexpensify** [comment]
@Santhosh-Sellavel really sorry but can you apply via this link? https://www.upwork.com/jobs/~019273e5c8d5968131

I've spent the last 10 minutes searching for this job in upworks in your Invite list, but I don't see it.

**Comment by luacmartins** [comment]
Just waiting on payment

**Comment by Santhosh-Sellavel** [comment]
Applied @jliexpensify

**Comment by jliexpensify** [comment]
Offer sent @Santhosh-Sellavel - thanks!

**Comment by jliexpensify** [comment]
Paid, job closed!
