### ISSUE TITLE
[HOLD for payment 2023-06-13] Web - Workspace - Crash when delete WS offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS
4. Turn off the internet connection
5. Click on 3 dots 
6. Click Delete Workspace

## Expected Result:
The workspace should be deleted and the app should like like it does when a Workspace is deleted and you're online (assuming that's possible)
<img width="1120" alt="image" src="https://github.com/Expensify/App/assets/22508304/9e0991e8-3450-499b-94c2-f1383091255e">

## Actual Result:
App crashed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [x] MacOS / Desktop

**Version Number:**1.3.20-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/cc69e6dc7c5b9148cfbdbbfaa6e5ad84f396c9fd74cce7056bc49422ca889fc3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @situchan 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b04e507bd3a3505c</li>
        <li>Upwork Job ID: 1670914877687336960</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Was able to reproduce, I updated the Expected Behaviour to mimic what happens when your online and you delete a Workspace.  @tylerkaraszewski and @allroundexperts, do you agree that should be the expected behaviour? 

@tylerkaraszewski , do you think this can be External?

https://github.com/Expensify/App/assets/22508304/54a2943f-d177-4d45-9958-b351de1cc1bc

**Comment by situchan** [comment]
I [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1685423839340039) this early in slack. As it's within regression period, maybe assigned folks in https://github.com/Expensify/App/issues/15796 will handle this?

**Comment by tylerkaraszewski** [comment]
Is the above checklist relevant for non-regression bugs?

**Comment by mallenexpensify** [comment]
@tylerkaraszewski no, if there's not a previous PR to point to or new regression test steps that should be added.

**Comment by tylerkaraszewski** [comment]
So do we jsut ignore it or just check everything off?

**Comment by mallenexpensify** [comment]
I checked everything off, it's kinda similar to the PR checklist, the boxes should be checked, even if an item isn't directly relevant. I guess it means it was _reviewed_

**Comment by mallenexpensify** [comment]
Closing, I don't think any actions are needed. Rajat was C+ to review the PR https://github.com/Expensify/App/pull/19886 and it was associated with this issue but also https://github.com/Expensify/App/issues/15796

**Comment by situchan** [comment]
@mallenexpensify I am eligible for reporting.

**Comment by mallenexpensify** [comment]
Sorry @s77rt , I added `Internal` to create the Upwork job. 
@situchan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01b04e507bd3a3505c
Sorry I missed ya the first time.

**Comment by mallenexpensify** [comment]
@situchan paid!
