### ISSUE TITLE
[HOLD for payment 2023-06-08] [HOLD for payment 2023-06-07] [$1000] Black screen appears for moment when logout of the android app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of the ND in android app
## Expected Result:
Sign in page appears
## Actual Result:
Black screen appears for a moment before showing sign in page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7776ac7b-0a68-4f5e-ac3b-c8263af66648

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103ef1c6aca759aca</li>
        <li>Upwork Job ID: 1663640574941503488</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
@situchan already has a fix in this [PR](https://github.com/Expensify/App/pull/19841)

**Comment by marcochavezf** [comment]
Hmm it's weird that I can't assign them

**Comment by marcochavezf** [comment]
@0xmiroslav will review https://github.com/Expensify/App/pull/19841 once it's ready cc @situchan

**Comment by Julesssss** [comment]
I removed the blocker label and updated the priority so we can pay out next week

**Comment by anmurali** [comment]
Can I pay this then? 

>Merged PR within 3 business days of assignment - 50% bonus
>Merged PR more than 9 business days after assignment - 50% penalty

Do either of these apply?

**Comment by anmurali** [comment]
Sent offers

**Comment by marcochavezf** [comment]
Since payment was made, I think we can close this one. @0xmiroslav let us know if something else is missing here 👍🏽
