### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Desktop - Console log appears when clicking "continue" in sign in page and creating new task page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19639

## Action Performed:
Scenario1:
1. Logout if already logged in
2. Enter new email and click Continue button
3. Verify that no console errors appear on magic code input page

Scenario 2:
1. Login any account
2. Create new task (Open FAB > Assign task > Enter title > Select assignee > Confirm task)

## Expected Result:
There should be no console error

## Actual Result:
Console error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.20.2

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/e61633511efab782d91f07a9e36c0dccd54fca6a4b21af7e7fae4b2bf8bde0ff
https://platform.applause.com/services/links/v1/external/9d382627ef1173c0ff7f656503f0245073df957cdf011d91eb4710076895d402

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a37a60d035a3de7</li>
        <li>Upwork Job ID: 1663930257949224960</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Slack convo: https://expensify.slack.com/archives/C049HHMV9SM/p1685441927670609

**Comment by puneetlath** [comment]
I'm not aware of it being fixed anywhere else, so if you're still seeing the issue on staging, I'd go ahead and mark external.

**Comment by lschurr** [comment]
I don't see this on web, but I'm asking for more info here - https://expensify.slack.com/archives/C049HHMV9SM/p1685546610952849?thread_ts=1685441927.670609&cid=C049HHMV9SM

**Comment by priya-zha** [comment]
@rushatgabhane According to the slack conversation here https://expensify.slack.com/archives/C049HHMV9SM/p1685441927670609

I reported this bug on May 30. It would be great if you could let me know If I'm the initial reporter for this bug or not . Thanks.

**Comment by kavimuru** [comment]
@rushatgabhane Same console error appears in the following pages:
1. Adding a new secondary contact
2. Adding a paypal account
3. Picking emoji and hit enter

**Comment by lschurr** [comment]
@robertjchen @eVoloshchak - who are we paying for this one? It was a regression that we didn't make external? But it looks like @tienifr worked on the PR, correct?

**Comment by eVoloshchak** [comment]
@lschurr, this was a regression from another PR @tienifr worked on 
So there's only a reporting bonus to be paid (if any) to the person who reported this

**Comment by priya-zha** [comment]
@eVoloshchak It would be great if you could look at this [comment](https://github.com/Expensify/App/issues/19848#issuecomment-1573080827) . I reported the same issue on May 30. Can you please confirm whether I am the initial reporter of this issue or not?

**Comment by mountiny** [comment]
@lschurr Seems like @priya-zha has reported this after noon 
<img width="335" alt="image" src="https://github.com/Expensify/App/assets/36083550/6abd4384-a185-42e4-98d3-bf9ddb0a8a5a">
 and this issue was created in the evening so I believe the only payment here should be $250 to @priya-zha

**Comment by lschurr** [comment]
Great thanks @mountiny! @priya-zha - could you apply for the job here? https://www.upwork.com/jobs/~014a37a60d035a3de7

**Comment by lschurr** [comment]
Paid!
