### ISSUE TITLE
[Pay reporting bonus] App crashes when collapsing composer after returning back to app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19845]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat,
2. Type at least three lines of text,
3. Expand composer,
4. Go to home screen or switch to other app
5. Return to New Expensify app
6. Collapse composer from expanded state

## Expected Result: Composer box 
should collapse
## Actual Result: 
App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/df5c830e-9fc2-42ed-8770-a059f6475dd3

https://github.com/Expensify/App/assets/43996225/4e75f3a1-74dd-413e-8cc6-693d26133d76

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nishancx
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685293536816139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Thank you @allroundexperts! I was able to recreate so I'll follow along for the PR close.

**Comment by strepanier03** [comment]
PR still open so on hold for now.

**Comment by strepanier03** [comment]
PR was deployed to Prod yesterday so I'll test again now.

**Comment by strepanier03** [comment]
@nishancx - I have created a reporting job for you [here](https://www.upwork.com/jobs/~017630f8ea4c1a06a2) but I'm unable to confidently find your profile in Upwork to hire you to the job. 

Please use the link to apply for the job so we can pay you for it and post your upwork profile here when you do. Thanks!

**Comment by strepanier03** [comment]
@greg-schroeder - I'm heading out on sabbatical and wasn't able to complete this payment before I went. Once @nishancx applies for the job and we accept, we can pay out the reporting bonus and close this. 

Thank you for wrapping this up!

**Comment by nishancx** [comment]
@strepanier03 I have applied for the job with my [upwork account](https://www.upwork.com/freelancers/~016f597cba0cf259d0)

**Comment by nishancx** [comment]
@strepanier03 Upwork has set my profile visibility to private due to inactivity, job process should be unchanged though. Sorry for the inconvenience.

**Comment by greg-schroeder** [comment]
Sent offer @nishancx

**Comment by nishancx** [comment]
Accepted @greg-schroeder

**Comment by greg-schroeder** [comment]
Paid

**Comment by nishancx** [comment]
Thank you.
