### ISSUE TITLE
Chronos took longer to respond to 1:1 help

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigated to Chronos chat
2. Sent the message 1:1 help
## Expected Result: 
Chronos should respond immediately with a canned message explaining how to schedule 1:1 meetings with coworkers
## Actual Result: 
Chronos responded with the canned message more than 20 seconds after I sent my message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f4bc310c-480b-468d-b0f2-b0b8a0c85bfd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685119821017509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee9f213f1d2b7cad</li>
        <li>Upwork Job ID: 1664412619267874816</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by arielgreen** [comment]
I'm not able to reproduce this right now. However, I've experienced it before personally, and I do agree it's a problem. 

This needs to be internal.

cc @deetergp

**Comment by arielgreen** [comment]
@deetergp interested in your thoughts on this/how we can debug.

**Comment by deetergp** [comment]
I think this has less to do with Chronos and more to do with the performance of NewDot as a whole.
