### ISSUE TITLE
Having long links displays tooltip in a large distance

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19842]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any chat
3. Send a very long link like around 3-4 lines (For example: go to google , search for flower and again type in flowers and hit enter so that a long link appears)
4. Copy the link and go to chat and paste it into the chat
5. Hover over the link and notice that the tooltip is displayed in a long distance
6. If you copy and paste the same link multiple times and hover over the link, notice that as much as the URL length increase, the tooltip distance also increases
## Expected Result: 
The tooltip distance should not be increased on the basis of the length of the URLs
## Actual Result:
 Having long links displays a tooltip at a large distance
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/11125ffc-9157-451f-904f-a91f12740cf9

https://github.com/Expensify/App/assets/43996225/3eb39e1c-365d-49c3-be3a-0f624560a6be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685121313707479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment]
@kavimuru Not able to reproduce after following the same steps as given. Is there anything specific that is needed for opening staging dot local?

**Comment by priya-zha** [comment]
@sethraj14 you need to hover on the top part of the link to get the tooltip. If you click on the end or on the bottom part, it will not be reproducible.

**Comment by adelekennedy** [comment]
[I'm not sure we need to fix this](https://expensify.slack.com/archives/C049HHMV9SM/p1685510864180629?thread_ts=1685121313.707479&cid=C049HHMV9SM)

**Comment by kavimuru** [comment]
@adelekennedy we have similar issues reported [1](https://expensify.slack.com/archives/C049HHMV9SM/p1685984914609969) and [2](https://expensify.slack.com/archives/C049HHMV9SM/p1685882883758559)
