### ISSUE TITLE
LHN - Public room is not displayed in LHN after sign in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19818

## Action Performed:
1. Sign out
2. Open a public room (like the ExpensiConX #announce room) (https://staging.new.expensify.com/r/3504895439653267
)
3. Verify you can see the announce room as an anonymous user (random email).
4. Click on Sign in or any action that should not be allowed to an unauthenticated user
5. Verify you're redirected to the signing page
6. Enter email/phone
7. Enter magic code

## Expected Result:
Public room should be displayed in the LHN

## Actual Result:
Public room is not displayed in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/fc73d1bdabdacd401a992cc86c8aaace5df94ccbedeff898b1fb09ae821b1680

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is reproduced on both environments IOS and Android app. 
Also there is no # announcement displayed below after tap on pubic link, you need to tap back button to sign in.  
Let me know if we need a separate bug for it.

![Screenshot_20230531_121737_New Expensify](https://github.com/Expensify/App/assets/93399543/a74e0a65-58b2-4edd-83a2-c15db7bdfe45)

https://github.com/Expensify/App/assets/93399543/b53710ab-7db5-4abd-abc7-1d01b947f961

**Comment by kevinksullivan** [comment]
discussing

https://expensify.slack.com/archives/C049HHMV9SM/p1685566633920239
