### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Login - "Magic code sent" below email field after go back from code input page offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Input email into email field
3. Tap "Continue"
4. Disable the internet connection
5. Click "Didn't receive a magic code?"
6. Click "Go back"
7. Enable the internet connection

## Expected Result:
No messages appear in email input screen after going back online

## Actual Result:
A message "Magic code sent!" appears below the email input field after going back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/3d4252eff76baa6e91d6bee9290541864472ccb83d454db8509a2e5b6d7b07a8

https://platform.applause.com/services/links/v1/external/fc6da469ebfd90d76b6b239a7f2a9b7c235e9e50e2d12c1a85ecaa3245110f37

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a43ea4a6751f6484</li>
        <li>Upwork Job ID: 1664315741336629248</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Reproduced and agree that this is a bug. I like @hungvu193's proposal to just remove the "Didn't receive magic link" link when offline, curious to hear @pecanoro and @sobitneupane's thoughts.

**Comment by sakluger** [comment]
I'm going to be OOO all next week, so I'm going to add another BugZero assignee to keep this moving while I'm out.

**Comment by trjExpensify** [comment]
>I like @hungvu193's proposal to just remove the "Didn't receive magic link" link when offline, curious to hear @pecanoro and @sobitneupane's thoughts.

I don't think we should "remove" the link. If it's following [pattern C](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#c---blocking-form-ui-pattern), it should appear disabled. Looking up the offline support in the Passwordless doc it should be following pattern c - so not sure where that got broken. CC: @johnmlee101 @NikkiWines 

(Link on _below_ only accessible by internal employees) 
>Of the existing password flows that exist on NewDot today that aren’t removed with the changes below, those will be changed into Pattern C offline support- meaning that they will require online access to both request the magic link/code, and also enter it into the UI.These flows are outlined in the detailed section [below](https://docs.google.com/document/d/1wQ-LJkiRQB_h19P4w4XN4J2Z45VQLOoLh9NwT0yndGs/edit#bookmark=id.p4bnn24701qk).

**Comment by NikkiWines** [comment]
I agree with @trjExpensify. We should disable the `Didn't receive magic link` link when the user is offline, not remove it.

**Comment by trjExpensify** [comment]
Yes, I suspect the opacity would be reduced to 50%. Though @NikkiWines, how did this look on original implementation from the doc? 

CC: @shawnborton

**Comment by NikkiWines** [comment]
50% opacity sounds good to me, not sure we had specific styling outlined in the doc + the UI has changed a bunch from the original implementation as well 😅

**Comment by sobitneupane** [comment]
@hungvu193 Would you like to update your proposal to match [the expected output](https://github.com/Expensify/App/issues/19867#issuecomment-1579659920)?

**Comment by sobitneupane** [comment]
Thanks @hungvu193.

[Proposal](https://github.com/Expensify/App/issues/19867#issuecomment-1569407915) from @hungvu193 looks good to me.

🎀👀🎀 C+ reviewed
cc: @pecanoro

**Comment by pecanoro** [comment]
Sounds good! Assigning @hungvu193

**Comment by sakluger** [comment]
Thanks for the fast work! This one qualifies for the efficiency bonus. As soon as the 7-day hold is over and the BZ checklist is complete, I can pay out and close.

**Comment by sakluger** [comment]
Hey @sobitneupane mind finishing the BZ checklist so I can complete payment? Thanks!

**Comment by sakluger** [comment]
Bump @sobitneupane

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/13655
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/13655#issuecomment-1604540114
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1687539235356429

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

I don't think we need a separate regression test here.

**Comment by sakluger** [comment]
Thanks! We're all good here 👍
