### ISSUE TITLE
[$1000] iOS - Add bank account - Not able to fill out the form "Personal Information" in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login to ND
3. Navigate to the add bank account modal in Workspace settings
4. Start and follow the flow for adding a fully verified bank account  until the "Personal Information" step
5. Disable the internet connection
6. Verify you're able to fill out the form. Fill out all the fields

## Expected Result:
User able to fill out the form. "Personal Information" in offline.

## Actual Result:
User can not fill out the form "Personal Information" in offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

https://expensify.testrail.io/index.php?/tests/view/3479776

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/927c320a6ff1f43be7addb79dc3ef2ee95d71786d12ae038f25bf5e254cb30f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c56f5e44e92eb6a8</li>
        <li>Upwork Job ID: 1663794483970064384</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Mobile issue swap with Kadie!

**Comment by kadiealexander** [comment]
Able to reproduce! 

https://github.com/Expensify/App/assets/59587260/53e50b69-f67a-48b9-b3bd-e9b61f4dc5df

**Comment by priyeshshah11** [comment]
@kadiealexander This looks intentional as per the code, doesn't look like a bug.

**Comment by kadiealexander** [comment]
Oooh good find @priyeshshah11!! 

@cead22 would you know if this is following the correct Offline Pattern? I wasn't able to find where we defined the offline pattern for adding a VBA and the [Testrail test](https://expensify.testrail.io/index.php?/tests/view/3479776) shows that it should be Pattern A but as @priyeshshah11 noted above, it seems we've coded it to Pattern D. I don't know enough about how VBA setups interact with the server to follow the [flowchart](https://docs.google.com/document/d/1RWPLDgdrJ4eW1KfseVmrYYy_fDUWWDQpek-hmdzAtuM/edit#heading=h.ns12dr1f35rx) correctly.

**Comment by bondydaa** [comment]
as noted here https://github.com/Expensify/App/issues/19863#issuecomment-1577232679 there are currently a few similar bugs all reported and seem to be the same so lets consolidate them into a single bug and get them all addressed.

**Comment by bondydaa** [comment]
closing in favor of https://github.com/Expensify/App/issues/18990
