### ISSUE TITLE
Web - Security - Inconsistency among input field, In “Step 2: Verify” of 2FA

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the "Security" section in the Settings.
2. Navigate to the Two-Factor Authentication option.
3. Do not enter any verification code.
4. Upon hovering over the "next" button, the cursor changes to the "not allowed" symbol, indicating that an error will only appear when the entire code is entered.
5. Press "Enter" and observe that an error message appears even though no code has been entered yet.

## Expected Result:
Upon pressing "Enter," no error message should appear since the "next" button is also disabled, ensuring consistency.

## Actual Result:
An error message appears upon pressing "Enter," despite the "next" button being disabled, resulting in an inconsistent behavior of the system.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/120bac76-65d5-4522-9ec8-55d376b02399

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685177729515949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Similar to the reasoning in https://github.com/Expensify/App/issues/19706#issuecomment-1567209903, I don't think this is worth addressing. It makes sense the button isn't clickable given the fact that no code has been entered, and the error message upon hitting enter also makes sense given the lack of code entered. Going to close this one out.
