### ISSUE TITLE
Web - Composer is not focused after clicking on "Reply in thread"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19881]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Post a comment
2. Hover over the comment and click on the "Reply in thread" icon

## Expected Result:
Composer should be focused after thread opens up

## Actual Result:
Composer is not focused after thread opens up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/442bbb9c-8c90-4b34-bf18-9c9da20dc3c1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684758813986659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I cannot reproduce this either - the composer is focused after creating a new thread. Tested on staging v1.3.20-5.

**Comment by kbecciv** [comment]
Hi @greg-schroeder! Issue is reproductible in IOS app now on build 1.3.43.6, should we reopen it or create a new issue?
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1689889495724859

https://github.com/Expensify/App/assets/93399543/d69595f4-5159-40b3-93b3-5001daccd9a4
