### ISSUE TITLE
Inconsistent tick mark placement for settled IOU messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a money request from account A to account B
2. Settle the money request from account B
3. Open chat with account B from account A and observe the IOU settled message and the tick mark

## Expected Result: 
The tick mark should be placed consistently over different platforms
## Actual Result: 
Tick mark for settled IOU messages are placed at the right corner on mWeb and it is placed just besides the amount on desktop, which is inconsistent
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-2
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/8ae9238d-a851-4686-bd7f-0f9d81840996)
![Screenshot_20230524-160418_Chrome](https://github.com/Expensify/App/assets/43996225/6267b889-1fa6-419e-9829-4386edc74238)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684933606702499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Hm I don't see the problem personally. This feels like a style choice, not a bug.
