### ISSUE TITLE
Unable to delete content inside text composer in IOU description thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat with money request
2. Click on the IOU card to open the description thread
3. Click on the text composer and type something (type something even if the text composer is hidden behind the description and is not visible)
4. Close the keyboard to observe the content inside the text composer
5. Observe the position of the cursor
6. Click on the text composer again and hit the backspace on your keyboard multiple times in order to clear the content inside the text composer
7. Close the keyboard and observe the content inside the text composer
## Expected Result: 
The position of the cursor should not jump to the beginning of the content inside the text composer after user clicks on the text composer. User should be able to delete the content inside the text composer. (I think the reason why user can't delete content is because the cursor jumps to the beginning of the word inside the composer and nothing happens when user hits the backspace since there is no word before the cursor.
## Actual Result: 
The cursor moves to the beginning of the content inside the text composer and hence user can't delete the content inside.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome - Samsung note 10+
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-2
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8628c8e6-d56a-4657-9676-5e5d93383909

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684931958346929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
I notice that caret is at starting of t4ext, can you please try putting it at the end and try again

**Comment by Nathan-Mulugeta** [comment]
Yes @BhuvaneshPatil , that is the issue, the cursor automatically moves to the beginning of the content even after putting it at the end, look at the recording closely.

**Comment by anmurali** [comment]
I cannot reproduce this. I tried it exactly on the device checked here - Samsung Note 20, Chrome.
