### ISSUE TITLE
iOS - Login - "Incorrect 2FA" error if log into new account with expired link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19912]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS app
2. Input email to create a new account
3. Tap "Continue"
4. Tap "Go back"
5. Tap "Continue"
6. Open email with expired magic link received at step 3
7. Copy the magic link
8. Modify copied link to staging
9. Paste the link into other app (e.g. notes)
10. Tap on the link
## Expected Result:
There's an error displayed indicating there was a problem with the magic link in the app
## Actual Result:
User lands in magic code input page with error "Incorrect two factor authentication code. Please try again"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="492" alt="Bug6075997_Screenshot_2023-06-01_at_02 20 28" src="https://github.com/Expensify/App/assets/43996225/7a31ae79-d272-43b1-8f2a-88c864ebbfa4">

https://github.com/Expensify/App/assets/43996225/e4c18426-5d2a-412f-994c-fef37764ab7a

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I haven't been able to reproduce this. Instead, I get the standard _"Incorrect magic code. Please try again or request a new code"_ error. 

<img width="492" alt="Bug6075997_Screenshot_2023-06-01_at_02 20 28" src="https://github.com/Expensify/App/assets/5802477/a4a27656-4335-42cc-849c-ec8fbcc3014e">
