### ISSUE TITLE
[$1000] iOS - Bank account - You are offline modal/page not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Enable staging Web secure server in Account Preferences if disabled
3. Navigate to the add bank account modal in Workspace settings
4. Start and follow the flow for adding a Verifying bank account using the credentials until you reach the Onfido screen
Offline
5. Disable the internet connection

## Expected Result:
The page/modal is blocked with a message saying "You appear to be offline"

## Actual Result:
You are offline modal/page not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.1

**Reproducible in staging?:** yes

**Reproducible in production?:** N/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bc67f4a1-0dea-4f43-b5b6-4504944746e9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec4fa44fcc3c0471</li>
        <li>Upwork Job ID: 1664063817418579968</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Adding Deploy blocker label because QA team is unable to verify bank account on production.

**Comment by marcaaron** [comment]
Does this only affect iOS? What other platforms were tested?

**Comment by marcaaron** [comment]
Checked and this isn't working as expected on iOS release build either so removing the blocker.

**Comment by marcaaron** [comment]
Pretty sure that the solution is something like add some way for the Onfido flow to detect that we are offline and dismiss the presented modal. On web, we just detach the entire view so there is a platform inconsistency here - but it's never worked this way AFAICT.

**Comment by marcaaron** [comment]
This should be testable locally so gonna make it `External`

**Comment by marcaaron** [comment]
argh there is no way to dismiss the modal already... 😖

Ok, we can maybe start by creating an issue in Onfido's react-native repo. I can try to escalate it to their support team... 

Though, I am inclined to agree with this:

>Since this issue didn't affect user experience, we can do nothing :)

The priority is too low for me to motivate myself to work on the issue so I think I'd prefer to close it for now.
