### ISSUE TITLE
Log In - Invalid magic link redirects to login page with error "This password link is expired.." 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#19911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log out if needed
2. Navigate to a expired link code (e.g https://staging.new.expensify.com/v/7453760/722805

## Expected Result:
User is navigated to the "Magic code expired" page. (Web behavior below)
![image](https://github.com/Expensify/App/assets/44479856/1399a78e-e681-4298-9056-c5049d0304e8)

## Actual Result:
User is navigated to log in. Error message mentions "Password link is invalid". Password should not be mentioned as Expensify transitioned to a password less login.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2

**Reproducible in staging?:** Yes 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
<img src="https://github.com/Expensify/App/assets/44479856/32477949-7ca5-44bd-a9b0-8ec9658c188b" width="40%">

In the video below is an example of the behavior in Staging and Prod

https://github.com/Expensify/App/assets/44479856/51beb1e3-3f5d-484c-9630-8b1ec298a72f

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
Interesting, I'm unable to reproduce this on dev, trying on staging now

<img width="622" alt="image" src="https://github.com/Expensify/App/assets/16747822/5ad1c9ef-2264-4e50-8201-d8a372c7fbe5">
<img width="900" alt="image" src="https://github.com/Expensify/App/assets/16747822/d13cda9d-fe3e-4ce6-8a3f-5c2ac24c26a8">

**Comment by isagoico** [comment]
@NikkiWines This is not repro in web. We were able to reproduce consistently on mobile devices (mWeb, iOS and Android)

**Comment by NikkiWines** [comment]
Oh, thanks for catching that @isagoico - trying locally on a mobile device now 🙇

**Comment by NikkiWines** [comment]
Also seems to work fine on dev on safari mWeb locally, trying on staging now to reproduce

<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/21420a43-80df-4ffd-8101-c16a8e954937">

**Comment by NikkiWines** [comment]
I am able to reproduce on staging using the exact same steps 🤔

**Comment by NikkiWines** [comment]
Oh! @isagoico can you confirm that the link used in your testing is `staging.new.expensify.com` and _not_ `new.expensify.com`? When I tested using the exact link from the email (which points to new.expensify.com, even if the action was taken on `staging.new.expensify.com`) I can reproduce the issue. If i use a `staging.new.expensify.com` link I cannot reproduce the issue.

**Comment by NikkiWines** [comment]
@isagoico thanks for confirming. I think I am able to reproduce this, though only when opening the expired link in an incognito tab - working on a fix now

**Comment by NikkiWines** [comment]
FWIW, I can reproduce this on web locally when opening the expired link in an incognito window

**Comment by isagoico** [comment]
Great! Glad you were able to reproduce - let us know if there's anything else we can help with

**Comment by NikkiWines** [comment]
I'm not sure this is a blocker, I think this is coming from where we call `User.validateLogin` after checking `Permissions.canUsePasswordlessLogins()` in `ValidateLoginPage`. If the link is opened in an incognito window, I bet we don't have the betas loaded correctly so it's going through a flow it shouldn't and returning that error. None of that code has changed in several months though. 

cc: @AndrewGable thoughts? I don't think any new code has caused this so I'm not sure it's a blocker.

We should also change some login in the back end so that we're not returning the `set password` error if the user is passworldess.

**Comment by NikkiWines** [comment]
Also looks like I can reproduce this on production 
<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/e646c296-0218-4810-88f9-f317c1759770">

**Comment by Julesssss** [comment]
Reducing priority as this is no longer a blocker.

**Comment by Julesssss** [comment]
Ah, I see. Will keep assigned

**Comment by twisterdotcom** [comment]
I have genuinely no idea what I should be doing on this issue @Julesssss. How do I help here?

**Comment by Julesssss** [comment]
I'm not sure myself either. 

I just retested the steps, but I don't see the mentioned outcome. I see the magic link page and no mention of 'password' which was part of the original problem.

**Comment by twisterdotcom** [comment]
mine just hangs on this page: 
<img width="3300" alt="image" src="https://github.com/Expensify/App/assets/9133401/e0afea5e-f1f4-4166-ada9-e94a70177662">

I think this is working fine.
