### ISSUE TITLE
Android - Link https://staging.new.expensify.com/anything redirects in mWeb instead of Android app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/anything
(with Android app installed on device)

## Expected Result:
Android app should appear. Page not found should be displayed

## Actual Result:
mWeb is opened instead of Android app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/07237b5f-312b-40f8-81c4-06df32229385

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Hm, is this a bug? This is how it is on mWeb safari as well. I suspect it's because that URL isn't recognised as a valid route in the app or something (/anything). For example, if you change it to new.expensify.com/settings it redirects and opens the native App just fine. 

CC: @Julesssss as my resident Android expert.

**Comment by Julesssss** [comment]
Yup I agree. We recognise the [following URLs](https://github.com/Expensify/App/blob/af6fb0768b65e95f8a9feb5e36626ae9df5f2097/android/app/src/main/AndroidManifest.xml#L64-L74) as deep links:

```
<data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/r"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/settings"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/setpassword"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/details"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/v"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/bank-account"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/iou"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/enable-payments"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/statements"/>
            <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/concierge"/>
```

**Comment by Julesssss** [comment]
Not a bug

**Comment by trjExpensify** [comment]
Thanks!
