### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] IOS - Chat - Top of the emoji inside the inline block is cut off

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start iOS App and login with any account
2. Open any chat
3. Post inline block with text and some emoji like ⁦`Text Block Emoji-1 Emoji-2 Emoji-3 ... `

## Expected Result:
The content of the inline block is fully visible

## Actual Result:
Top of the emoji inside the inline block is cut off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1,3,21.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b813fa85-59ab-4383-a517-93ecaa29868b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b27ea19fc8522167</li>
        <li>Upwork Job ID: 1664657301634904064</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by AlexanderDmitriev** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - Chat - Top of the emoji inside the inline block is cut off

### What is the root cause of that problem?
Heights are small for inline code block elements

https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/styles/codeStyles/index.ios.js#L1-L13

### What changes do you think we should make in order to solve the problem?
Adjust `height`, `lineHeight` properly

    const codeWordWrapper = {
        height: 30,
    };

    const codeWordStyle = {
        height: 30,
        top: 4,
    };

    const codeTextStyle = {
        lineHeight: 30,
    };

### Result
![image](https://github.com/Expensify/App/assets/17315937/140c1b46-5ef4-46e1-b456-40936e609bf0)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment]
@AlexanderDmitriev Thanks for the proposal. Your RCA is correct and the fix makes sense to me but let's adjust the values just slightly (18 seems good enough).

:ribbon: :eyes: :ribbon: C+ reviewed

cc @flodnv

**Comment by s77rt** [comment]
@s-alves10 Thanks for the proposal. I don't see how the matrix is relevant here. Can you elaborate on this? As far as I can tell the bug is mostly due to the wrong line height (and height).

**Comment by s-alves10** [comment]
@s77rt 
Please check the below image carefully. Not a simple line height issue

![image](https://github.com/Expensify/App/assets/126839717/415702b7-da2b-4ff2-9b81-82b2631531c0)

**Comment by s77rt** [comment]
@s-alves10 I'm sorry, I don't get it. Can you please rephrase what you are trying to say here? As far as I tested adjusting the height and line height values seems enough, am I missing something here? i.e. what kind of a bug is still existing after those changes?

**Comment by s-alves10** [comment]
@s77rt 
Please check `👌You're welcome` part. text vertical align. They are rendered separately

**Comment by s77rt** [comment]
Oh right. This seems a little different issue but we should probably handle it here. I wonder why each word is rendered separately, that's weird.

**Comment by s-alves10** [comment]
@s77rt 
This was from the beginning of the inline code block implementation. Please check
https://github.com/Expensify/App/blob/465b78814589bffd88a1b90ccd66a7fc86b03900/src/components/InlineCodeBlock/WrappedText.js#L45-L68

**Comment by s77rt** [comment]
@s-alves10 It don't seem to be something from the beginning. This was added by https://github.com/Expensify/App/pull/2307 to fix  https://github.com/Expensify/App/issues/986. Rendering everything in one row makes the text overflows.

| Matrix | Rows Only |
|--------|-----------|
|   <img src="https://github.com/Expensify/App/assets/16493223/f3c157da-473d-4390-a8f4-02cca6c38cf7" />  |   <img src="https://github.com/Expensify/App/assets/16493223/846b776d-5a28-49a2-a42b-68245dc8656b" />        |

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19922#issuecomment-1574025674)

@s77rt 
Yes, you're right. I updated my proposal

**Comment by s77rt** [comment]
@s-alves10 Thanks for the update. Using `\b` as the separator makes sense but this will create more columns than necessary and will cause text to break in places where it should not, example: `test you're you're you're you're you're`.

| Break on spaces | Break on word boundaries |
|-----------------|--------------------------|
|  <img src="https://github.com/Expensify/App/assets/16493223/eef7ffd0-19bb-4c83-a250-80bb0e3e5c28" />               |     <img src="https://github.com/Expensify/App/assets/16493223/21d30ab1-556d-4e16-bdf2-77682f91cbed" />                     |

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19922#issuecomment-1574025674)

@s77rt 

Thank you for your feedback.
Yes, you're right. I was thinking how to optimize the splitting.
I think the updated proposal can solve the issue perfectly.

**Comment by s77rt** [comment]
@s-alves10 Thanks for the quick follow up. So the idea is to split on both spaces and emojis? Your regex seems a little complicated, can you please update it and use our existing [EMOJIS](https://github.com/Expensify/App/blob/754d2ec3a09f4a00c938c6220253ad10f877a6e8/src/CONST.js#L1105) regex or better create a new regex SPACE_OR_EMOJI (similar to SPECIAL_CHAR_OR_EMOJI).

**Comment by s-alves10** [comment]
@s77rt 

We can add the following line to the `CONST.js`

```
        WORDS_OR_EMOJIS: /(([\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3)+|(?!(\\s|([\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|[#*0-9]\uFE0F?\u20E3))+))/gu,
```

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19922#issuecomment-1574025674)

I created a `EMOJI_SPLITTER` in `CONST.js` and used it in `getTextMatrix` function. I think the current logic is robust. Please check

**Comment by s77rt** [comment]
@s-alves10 This seems over engineered. Why can't we just split on spaces and emojis? (in one regex)

**Comment by s-alves10** [comment]
@s77rt 

The logic seems complex but simple. Splitting by emoji and next by space. We have now complex emoji regex and so it looks hard to understand.

In order to meet various cases, I think the current clear logic is the best choice

```
  👌kind👌You're welcome.
  👌# kind 👌(ok_hand) You're welcome.
```

**Comment by s77rt** [comment]
@s-alves10 I don't understand why you are adding the loop, why don't split on spaces and emojis going with something like:
```js
"hi there👌 test: you're".split(/(\s|👌)/)
```

replacing 👌 with the emoji regex.

**Comment by s-alves10** [comment]
@s77rt 
Oops. I was thinking the hardest way? Thank you for teaching me. Yeah, it works

**Comment by s77rt** [comment]
@s-alves10 Awesome. Can you please update your proposal?

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/19922#issuecomment-1574025674)

**Comment by s77rt** [comment]
@s-alves10 Thanks. This is looking better. We can work on the rest details in the PR.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @flodnv

**Comment by flodnv** [comment]
Great! Thanks, go for it @s-alves10 🙇

**Comment by s-alves10** [comment]
Thank you. I'll have a PR ready for review in a few hours

**Comment by s-alves10** [comment]
@s77rt @flodnv 

[PR](https://github.com/Expensify/App/pull/20287) is ready for review.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/2527
- The offending PR has been commented on: https://github.com/Expensify/App/pull/2527#discussion_r1228604764 and https://github.com/Expensify/App/pull/2527#discussion_r1228606071
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1686685325052589
- Determine if we should create a regression test for this bug: No

**Comment by flaviadefaria** [comment]
@s77rt @s-alves10 Issuing payment for you both now for $1000 + $500 (bonus) each.
