### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000]  QR code should show for all rooms no matter the status of the room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new workspace
3. Go to announce and send a message
4. Click on reply thread icon so that a new thread page opens up and send a message on the thread
5. Now delete the workspace
6. Refresh the page to see the square logo of the thread page and click on header and notice that even when it shows 'unavailable workspace', the share QR code is still shown. If the workspace is not available, it shouln't have shown the QR share code in a similar way how it gets disappeared on the announce page of the same workspace
## Expected Result: 
The Share QR code should be shown for all rooms no matter what their status is
## Actual Result: 
The Share QR code is not shown on the announce page of a deleted workspace. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/df1aaabe-efa4-4867-a673-def452079532

https://github.com/Expensify/App/assets/43996225/54f72938-46c4-4d9b-aadc-1bfbfb2601f0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685356464634629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121f15714602fea4b</li>
        <li>Upwork Job ID: 1667256564798566400</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by abekkala** [comment]
@jasperhuangg I notice that we do note **"Unavailable Workspace"** 
<img width="201" alt="Screenshot 2023-06-02 at 6 49 43 AM" src="https://github.com/Expensify/App/assets/11966460/fff33b46-562c-4a52-8142-92509fc15091">

Should we not show the QR at all?

**Comment by abekkala** [comment]
@jasperhuangg do you have a better idea on what the expectation should be. 
Is the `Unavailable workspace` enough or should we be removing the QR all together?

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C01SKUP7QR0/p1686326648096679

**Comment by abekkala** [comment]
This should actually be consistent in that we SHOULD show the QR everywhere. Not remove it from the thread.

https://expensify.slack.com/archives/C01SKUP7QR0/p1686339153500469?thread_ts=1686326648.096679&cid=C01SKUP7QR0

**Comment by BhuvaneshPatil** [comment]
Hi @abekkala , the threads of Slack that you've shared are not accessible to external contributors. can you please give a quick summary about them. Thanks

**Comment by abekkala** [comment]
> 2 things to clarify:
> 
> 1. Should we show QA Code or not in archived workspace chat and its thread chats?
> 
> 2. If workspace is archived, all threads created from that workspace room should be archived as well? I don't see any reason why threads are still active in archived workspace.

1. YES, the QR code should show. 
The code should show for all rooms no matter what their status is

We will then have two separate GH issues for implementing the archive logic for threads that we have already implemented elsewhere and fixing how we display `unavailable workspace` for anyone that can see/find the archived room.

**Comment by abekkala** [comment]
updated title as well to reflect our expected outcome

**Comment by abekkala** [comment]
@jasperhuangg what do you think of @aimane-chnaif recommendation above?

**Comment by jasperhuangg** [comment]
I agree. Both proposals work but it seems @tienifr got there first. Assigning them!

**Comment by abekkala** [comment]
@anmurali Reassigning for Sabbatical
____

### CURRENT STATUS:

We're in the waiting period for payment

* Issue reported by: @priya-zha [$250]
* Selected Proposal for fix: @tienifr [$1000] + [$500 PR bonus will be added to payment] pending no regressions
* C+ Review: @aimane-chnaif [$1000] + [$500 PR bonus will be added to payment]  pending no regressions

I've hired them all in Upwork contract offers to all they just need to be paid out on July 06. 
Priya: https://www.upwork.com/nx/wm/offer/25305003
Tien: https://www.upwork.com/nx/wm/offer/25304974
Aimane: https://www.upwork.com/nx/wm/offer/25304992

If a regression pops up the amount within the contract can be edited accordingly by clicking "**Modify Offer**" vis the offer link.

**Comment by anmurali** [comment]
Holding till the 6th!

**Comment by jasperhuangg** [comment]
@anmurali it's past the 6th, let's get them paid!

**Comment by anmurali** [comment]
Done
