### ISSUE TITLE
[$1000] Long-pressing the empty right section of a message with just a link doesn't show correct options.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account on mobile and open a chat.
2. Type a message into the composer that contains only a link e.g. 'google.com', '# google.com', or '> google.com'.
3. Long-press the empty section on the right side of the link to bring up the message's options.
## Expected Result: 
The options shown in the modal should include, for example, editing the message, deleting the message, replying in a thread, etc.
## Actual Result: 
The only option shown is to copy the link to the clipboard.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0e9628b5-ab5c-4ada-a997-924c42949bb9

https://github.com/Expensify/App/assets/43996225/614aa3d1-b8eb-4b3a-8a7d-498262c1a47f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685357040272429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178d9eb714da9b983</li>
        <li>Upwork Job ID: 1664225537139695616</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Setting as external, as we seem to have a valid proposal already!

**Comment by Victor-Nyagudi** [comment]
Is this issue considered a dupe now based on the above findings?

**Comment by Gonals** [comment]
> Oh, that makes sense that it would be the same RC - I am managing both issues. If you agree that @bernhardoj's proposal fixes both @Gonals, we should just merge them to be honest. This is basically the same issue couched differently, no?

Makes sense to me!

**Comment by greg-schroeder** [comment]
Closing as a dupe. It's essentially the same report couched differently, and will be fixed incidentally.
