### ISSUE TITLE
[$1000] Sign In - Logo is displayed instead Abracadabra page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19952]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of the account
2. Enter the email on the email field and continue
3. Click on "Go Back"
4. Continue with the log in flow
5. Navigate to the email inbox and look for the magic link email
Web/mWeb
6. Change the link to staging if needed
7. Open a new tab and paste the link in the URL

## Expected Result:
Verify an "Abracadabra, you are signed in!" page is displayed

## Actual Result:
Logo is displayed instead Abracadabra page when open a new tab and paste the link in the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/685739f1-3db0-4156-92ea-bc09afd4c981

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4002a99eff1257b</li>
        <li>Upwork Job ID: 1666113960734720000</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Thanks @hungvu193 .  I was able to reproduce
<img width="983" alt="image" src="https://github.com/Expensify/App/assets/22508304/8892ad7b-fda9-4450-98a5-2e31ab8833ec">

@arosiclair , think this can be External?

**Comment by arosiclair** [comment]
Yeah contributors should be able to figure out if this is a frontend issue or not. If it isn't we can mark internal.

**Comment by petromoldovan** [comment]
this issue was fixed on main branch with this MR https://github.com/Expensify/App/pull/20216

**Comment by marcochavezf** [comment]
Thanks @petromoldovan! I'm going to go ahead and close this one
