### ISSUE TITLE
Assign Task - Task name disappears on logout and login again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + icon
2. Select Assign task option
3. Create a new task
4. Go to settings > logout
5. Login again

## Expected Result:
Should show task name

## Actual Result:
Task name disappears on logout and login again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7b6ec887-04e8-4b4d-9508-c3c3be9d8b10

https://github.com/Expensify/App/assets/93399543/8d8e2986-7ed9-4642-a62c-3c54e2565f22

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685357193039949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This is expected right now (due to some recent BE changes that were made), we're fixing this in https://github.com/Expensify/App/issues/19132
