### ISSUE TITLE
 Sender's and recipient's information disappears when deleting an account after Requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon
2. Click on Request money link
3. Enter amount & click on 'Next' button
4. Search user
5. Select user
6. Click on 'Request' button
7. Click on the sent request message
8. Verify that the sender's details and recipient's details are displayed
9. Click on profile avatar > security > close account > enter default contact method and delete the account
10. Verify that the account is deleted
11. Navigate to sign in page > sign in with the deleted account
12. Open the sent IOU

## Expected Result:
The recipient's and sender's details (avatar & name) should be displayed

## Actual Result:
The recipient's and sender's details is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b0e4fbce-096b-433a-a9d8-a48d0d0e0f8b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684746944827149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
This issue seems to be fixed on the latest release. We can close this one out. 


https://github.com/Expensify/App/assets/57330233/8629a778-d1fa-4198-a1c1-c616f3d6f746

**Comment by JmillsExpensify** [comment]
Ah yeah, indeed. Appreciate you following up on this issue. I'm seeing that same. Closing it out!
