### ISSUE TITLE
Edited task title does not update in report screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select Assign task option
3.  Enter title and description
4. Click on Next button
5. Click on confirm task button
6. click on title
7. Edit task title
8. Go back to previous report screen
9. Check the task tile

## Expected Result: 
Task title should be updated
## Actual Result: 
Task title does not updated

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fe447061-3d96-4e6d-9f54-f78b72afb39f

https://github.com/Expensify/App/assets/43996225/e451221d-61f1-4079-b6c4-017d4dd2f83e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685429799658679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Going to be resolved in https://github.com/Expensify/App/issues/19132
