### ISSUE TITLE
[$1000] mp4 files sent by Concierge display in the DM as: "Your browser does not support HTML5 video" 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#19964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the Concierge DM
2. Request that Concierge send you a mp4 file for testing using drag and drop

## Expected Result:
The mp4 file appears in the Concierge DM and is available to download

## Actual Result:
Displays as "Your browser does not support HTML5 video" in written text  

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.21-2
**Reproducible in staging?:** Y 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Found when executing the QA of [this PR](https://github.com/Expensify/App/pull/19724) but might not be related. 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![uploads_1685567315876-2023-05-31_14-08-33](https://github.com/Expensify/App/assets/16232057/0e7cf8e6-541d-4af3-9acf-af04f2a9d126)
<img width="483" alt="image" src="https://github.com/Expensify/App/assets/16232057/2ea16a73-ffc0-4d01-8059-ad58fa214e0d">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**

CC: @kidroca @hayata-suenaga 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187897be4677fb987</li>
        <li>Upwork Job ID: 1668383853323608064</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Nope, not that I'm aware of. Though @alexpensify was my Concierge buddy. Did you send the mp4 file a specific way?

**Comment by alexpensify** [comment]
I'm using drag and drop into the chat. @trjExpensify - I sent another test to you right now, can you check your test account? Thanks!

**Comment by strepanier03** [comment]
Started testing steps now and will follow up shortly.

**Comment by trjExpensify** [comment]
Intereeesting! @chiragsalian as a resident Concierge expert might know what's what here. If it's not an issue in /App though, seems like this will likely need to go `internal`.

**Comment by strepanier03** [comment]
I was having some trouble in Concierge but got it resolved today. 

Confirming that using drag and drop this was easily recreatable. 

On the Concierge side:
<img width="530" alt="image" src="https://github.com/Expensify/App/assets/10925636/21f2d71c-280b-4509-aee6-da03047edaeb">

In Echat:
<img width="1088" alt="image" src="https://github.com/Expensify/App/assets/10925636/55fa8ce9-1b8f-4ee0-aa8c-1a0b1fbf5047">

**Comment by strepanier03** [comment]
@chiragsalian - I didn't set `Internal` or `External` until you had a chance to weigh in. Feel free to let me know which is appropriate or toss the label on yourself, either way, I'll continue following this and help move it forward. Thank you!

**Comment by strepanier03** [comment]
@chiragsalian - Can you review https://github.com/Expensify/App/issues/19964#issuecomment-1577478419 and weigh in? 

Should this go `internal`?

**Comment by strepanier03** [comment]
Not 100% sure if this should be internal or external. @MariaHCD or @narefyev91 can you give it a set of eyes and help me figure out if this should be handled internally or externally?

If it should be external please let me know and I can quickly make the change.

**Comment by narefyev91** [comment]
@strepanier03 should be Internal

**Comment by MariaHCD** [comment]
And when we attach the mp4 as a file instead of dragging and dropping it, the chatBotMessage is a link instead of a `<video>` element:

```
{"html":"<a href=\"https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com-dev/uploads%2F1686659130838-file_example_MP4_480_1_5MG.mp4\" target=\"_blank\" class=\"fr-file\">file_example_MP4_480_1_5MG.mp4</a>"}
```

**Comment by kidroca** [comment]
> Formatted:
> 
> ```html
> <span contenteditable="false" draggable="true" class="fr-video fr-dvb fr-draggable">
>     <video src="blob:https://www.expensify.com.dev/93ddb6c9-99ce-45e0-8f21-ec85fd7b492d" style="width: 600px;" controls="" class="fr-draggable">Your browser does not support HTML5 video.</video>
> </span>
> ```

The `src` attribute in the `<video>` tag is currently set to `blob:https://www.expensify.com.dev/93ddb6c9-99ce-45e0-8f21-ec85fd7b492d`, which appears to be a local blob URL. This should be updated, as it is not accessible to anyone but the sender.

As you rightly pointed out, the message wrapped within the `<video>` tag serves as a fallback for browsers that do not support the `<video>` tag. 

In the current scenario, the backend appears to disregard the entire `<video>` tag, leaving us with just the fallback text.

Even if the server were capable of parsing the `<video>` tag, it would not be able to retrieve the video if the `src` attribute is a local blob URL, as it is inaccessible to anyone but the sender.

To resolve this, we should introduce a logic (for the Concierge App) that:
- Allows the use of the local blob URL for instant video preview on the sender's end, while preventing the message from being sent. 
- Begins the process of uploading the video to an S3 bucket in parallel.
- Once the video upload ends, it should replace the `src` URL with the URL of the uploaded video (this URL might become available even before the upload completes).
- Once the destination URL is secured, the message sending functionality can be enabled. 

It's possible that such logic exists, but it's simply not waited for, so the message is sent with the local blob URL
Apparently the server disregards the `video` anyway 

---

#### About blob urls 

A `blob`: URL, or Blob URL, is a URL that points to a Blob or File object. Blobs are a fundamental data type used for holding a chunk of data. They are often used to represent data that isn't necessarily in a JavaScript-native format. Blobs are typically used to store data for files in browsers.

In the current context, blob:https://www.expensify.com.dev/93ddb6c9-99ce-45e0-8f21-ec85fd7b492d points to a blob object (a video file) that was created within the user's browser. This URL is not accessible outside the context of the user's local session, which means it won't be accessible to anyone else but the sender.

**Comment by strepanier03** [comment]
Thank you, everyone!

**Comment by strepanier03** [comment]
@muttmuure - I am heading out on Sabbatical this evening so I need to reassign the BZ team member. This just switched to Internal and we're not ready for BZ action at this time. 

Thank you for handling!

**Comment by muttmuure** [comment]
Not overdue

**Comment by MariaHCD** [comment]
Thanks, @kidroca! I believe we might have the logic already in use for uploading attachments via Concierge. I will take a closer look here.

**Comment by muttmuure** [comment]
@MariaHCD let me know if you're able to take this one, or if we should ask another engineer to pick it up!

**Comment by MariaHCD** [comment]
I looked into this today and have a WIP PR: https://github.com/Expensify/Web-Expensify/pull/37951

I'll polish and do some more testing.

**Comment by muttmuure** [comment]
Not overdue

**Comment by MariaHCD** [comment]
Internal PR is still a WIP!

**Comment by muttmuure** [comment]
No update needed

**Comment by muttmuure** [comment]
No update needed

**Comment by muttmuure** [comment]
@MariaHCD I know you've got other high priorities but do you think you'll be able to push this one along a bit this week?

**Comment by MariaHCD** [comment]
Going to polish the PR and send it out for review today.

**Comment by MariaHCD** [comment]
Ah, actually, I want to look into this more: https://github.com/Expensify/App/issues/19964#issuecomment-1629216219

And see if the app does support `<video>` tags or not.

**Comment by MariaHCD** [comment]
Continuing on the [PR](https://github.com/Expensify/Web-Expensify/pull/37951) this week but prioritizing some other dailies/chores first.

**Comment by muttmuure** [comment]
Not overdue

**Comment by MariaHCD** [comment]
Going to aim to push the PR out this week.

**Comment by muttmuure** [comment]
Not overdue

**Comment by MariaHCD** [comment]
Polishing the PR today.

**Comment by MariaHCD** [comment]
The fix was deployed to production: https://github.com/Expensify/Web-Expensify/pull/37951#issuecomment-1661180185

One limitation is that dragging and dropping multiple video files at once does not work as expected. I found that using the attachment picker to upload multiple video files does not work either.

I'm not sure if this is something that would be valuable to fix since Concierge agents can upload one video at a time. But if this would be a big QOL improvement, feel free to reopen, I can try to look further into it.
