### ISSUE TITLE
Workspace not sorted correctly while creating room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to "New room"
2. Click on "Workspace" dropdown

## Expected Result:
Workspace should be sorted alphabetically

## Actual Result:
Workspace not sorted alphabetically while creating room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/47dc7df0-a213-4cc4-bdd2-6feb5b1cd559

https://github.com/Expensify/App/assets/93399543/de8a3eb1-a687-4e00-9afe-90b12ed22eea

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685370310524839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
closing based on - https://github.com/Expensify/App/issues/19963#issuecomment-1572303898
