### ISSUE TITLE
Unable to leave a thread when it is initiated and left in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Open any report
3. Send any comment
4. Reply in thread to the comment
5. Send any comment in the thread
6. Click on the thread header
7. Click on Leave thread
8. Go online
## Expected Result: 
The left thread does not reappear on LHN
## Actual Result: 
The left thread reappears on LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bfbcd26e-71f9-4f65-9ea7-889425389366

https://github.com/Expensify/App/assets/43996225/c5e8142f-b35b-41d1-8282-238671316876

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1685430101536709
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll test soon

**Comment by alexpensify** [comment]
I'll test tomorrow

**Comment by alexpensify** [comment]
I'm going to close, this one is very similar to the updates planned for these two GHs: 

https://github.com/Expensify/App/issues/19982

and 

https://github.com/Expensify/App/issues/20197
