### ISSUE TITLE
Workspace name does not change when the room is set to "Public"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "New room" option
2. Enter a room name and select a workspace
3. Set the visibility to "Public" and click on "Create room"
4. Proceed to the settings > Workspace section
5. Attempt to edit the workspace name

## Expected Result:
When a room within a workspace is set to "Public" modifying the workspace name should reflect the changes

## Actual Result:
The workspace name does not change when the visibility is set to "Public" although it works correctly under other conditions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/30bec1ed-a9cc-4ffd-82f2-effe01a7a7df

https://github.com/Expensify/App/assets/93399543/b7be9244-2e0f-4180-9dd3-cf1d2c660aef

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685377661841849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Thanks for letting me know! Closing as duplicate.
