### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Workspace name does not change when the room is set to "Public"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19987]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "New room" option
2. Enter a room name and select a workspace
3. Set the visibility to "Public" and click on "Create room"
4. Proceed to the settings > Workspace section
5. Attempt to edit the workspace name

## Expected Result:
When a room within a workspace is set to "Public" modifying the workspace name should reflect the changes

## Actual Result:
The workspace name does not change when the visibility is set to "Public" although it works correctly under other conditions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/30bec1ed-a9cc-4ffd-82f2-effe01a7a7df

https://github.com/Expensify/App/assets/93399543/b7be9244-2e0f-4180-9dd3-cf1d2c660aef

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685377661841849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155889d32c72672f3</li>
        <li>Upwork Job ID: 1664782872269701120</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I think it makes sense to update optimistically. Does the back-end send a push right now when the workspace is renamed?

**Comment by puneetlath** [comment]
Sounds good to me. 

Reminder for me: we also need to update the back-end to send a pusher update when the name changes.

**Comment by puneetlath** [comment]
@allroundexperts I'll be OOO this week, so if you need Internal help moving this forward during that time please ask in #contributor-plus. Thanks!

**Comment by puneetlath** [comment]
@ayazhussain79 @dukenv0307 can you please apply here: https://www.upwork.com/jobs/~0155889d32c72672f3

**Comment by puneetlath** [comment]
Nvm actually. I found you both and sent offers. 

@allroundexperts friendly reminder about the checklist.

**Comment by ayazhussain79** [comment]
@puneetlath offer accepted, Thank you

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
