### ISSUE TITLE
Log in - Tapping go back on 2FA screen after link redirects to the same screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19637

## Action Performed:
1. Have an account with 2fa enabled
2. Start sign-in
3. Tap on the link in the email that you automatically received
4. 2fa code screen is displayed
5. Tap Go Back

## Expected Result:
Login screen should be displayed

## Actual Result:
2FA screen. Need 2FA code or app reinstall to proceed further

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/02be237e-ebca-420f-bafc-ab0b350e254e

https://github.com/Expensify/App/assets/78819774/d524e8ca-ae66-4760-8917-4d483264d7bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
I think it will be solved here https://github.com/Expensify/App/issues/19712

**Comment by trjExpensify** [comment]
Yeah, I was about to say the same thing. I think we can close this in favour of that issue. The PR shows it working on all platforms.
