### ISSUE TITLE
[$1000] Chat-Sent and deleted offline messages are displayed in the chat after going online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
2. Open a report with no chat history
3. Go offline
4. Send a comment
5. Delete the comment
6. Go back online
7. Wait a few seconds

## Expected Result:
Message not showing in chat because it was deleted

## Actual Result:
Messages displayed in chat and you need to refresh the page then it disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x]  Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/631a0466-3f2a-4b25-94ba-f3f8a748a5a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013822ee09d17a20f8</li>
        <li>Upwork Job ID: 1664504227491889152</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Reproduced in chrome web staging:

https://github.com/Expensify/App/assets/59587260/3d0d1c6f-5bd5-4632-8342-a55f18f87200

**Comment by narefyev91** [comment]
Hey @c3024 ! Your proposal makes sense - can you please clarify one thing: seems that fix with Onyx will fix the same cases in the whole app? And can be potentially fix this issue too https://github.com/Expensify/App/issues/19651?

**Comment by narefyev91** [comment]
@HezekielT @kadiealexander in that case should we close this one? Or put on Hold to be sure that fix will be applied?

**Comment by narefyev91** [comment]
> This issue is actually a duplicate of #17081. So I think we can close it.

cc @mountiny

**Comment by mountiny** [comment]
Agree its a duplicate
