### ISSUE TITLE
App shows the same default avatar for every different account on new chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account on ND
2. Click on FAB and click on split bill
3. Enter amount and click next
4. Enter multiple different account emails and select them to split amount with them
5. Click on FAB and click on new chat
6. Observe the avatars of the recent contacts
7. Open each IOU thread and click on the IOU card to open the description thread. Do this for every account with whom amount was split between
8. Click on the FAB and click on new chat again
9. Observe the avatar of the recent contacts
## Expected Result: 
The default avatar should not revert back to show the same default avatar for every different contact
## Actual Result: 
App shows the same default avatar for every different account on the recent contact list. The default avatar shown is the same as the current user's default avatar.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7fb714ae-824a-4ca0-90b8-33a41379c2bb

https://github.com/Expensify/App/assets/43996225/8fca4355-7d6a-40fb-9de1-fb4d62146953

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685443348773429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
@Nathan-Mulugeta this is basically the same issue with this https://github.com/Expensify/App/issues/19370 where the new chat page shows the "owes you". I think we should just reopen that.

**Comment by tjferriss** [comment]
@Nathan-Mulugeta are you still able to reproduce this issue? 

It looks like this PR is related and should have fixed this: https://github.com/Expensify/App/pull/19392. Could this be a regression? @thienlnam @thesahindia

**Comment by Nathan-Mulugeta** [comment]
Hey @tjferriss I just tested this out on latest version on staging and it is still present.

**Comment by thienlnam** [comment]
I'm not sure I am following what the issue is here - there seem to be different default avatars shown in the videos

**Comment by Nathan-Mulugeta** [comment]
Hey @thienlnam watch the behaviour of the default avatars changing right after 00:53 seconds into the video.

**Comment by Nathan-Mulugeta** [comment]
Hey @thienlnam, if you watch the first attached video, you'll notice that the default avatars undergo a noticeable change at around 00:53 seconds.

**Comment by thienlnam** [comment]
Ah yeah thanks that helped. The linked PR _might_ be related with the changes made in `src/libs/SidebarUtils.js`

**Comment by Nathan-Mulugeta** [comment]
I just tested the latest version on the staging environment, but it seems like the changes made in that PR didn't resolve the issue. Unfortunately, the problem is still there.
