### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Find and remove all instances where we show "You appear to be offline" twice in the UI, such that we only show it once. 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Sometimes our UI displays "You appear to be offline" two times (e.g. once on the page itself, and once at the footer of the page). Here's an example that we recently fixed - https://github.com/Expensify/App/issues/19187

Here's an example of another that's still not fixed:

1. Switch to offline
2. Create new workspace(if not created)
3. Go to any workspace > bank account
4. Select Connect online with Plaid option

## Expected Result: 
We should show only **one** "You appear to be offline" message to the end user.

## Actual Result: 
We show two "You appear to be offline" messages in the UI, which is redundant.

## Workaround:
>Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes you can easily ignore.

## Platforms:
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y

https://github.com/Expensify/App/assets/43996225/8861857c-7472-4535-bfbe-07556e30c82b

<img src="https://github.com/Expensify/App/assets/43996225/b2b96ace-5905-4fe7-9c57-ea3d52989875" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/59bc55bc-6146-4d7d-afc8-28bfe2691c4c" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685455943267169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5da0515d1d2e88e</li>
        <li>Upwork Job ID: 1666461948293591040</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
Hmm. I am torn on this

**Comment by michaelhaxhiu** [comment]
I want more input in #expensify-bugs before we proceed further. Please hold!

https://expensify.slack.com/archives/C049HHMV9SM/p1686149657454899?thread_ts=1685455943.267169&cid=C049HHMV9SM

**Comment by michaelhaxhiu** [comment]
cc'in @MonilBhavsar since you had your ✋s on https://github.com/Expensify/App/issues/19187 and it's similar.

**Comment by MonilBhavsar** [comment]
Since this was a widespread issue, we descoped it from that issue. We can fix it here for all pages 👍

**Comment by flodnv** [comment]
Cool, go for it @dhairyasenjaliya

**Comment by michaelhaxhiu** [comment]
Sure we can add $500 (like an urgency bonus i suppose) to compensate you for the additional scope & work.

And you are asking to claim 1 bug bounty bonus for identifying https://expensify.slack.com/archives/C049HHMV9SM/p1684408727072029 which was fixed via your PR here, right? Seems fair too

**Comment by michaelhaxhiu** [comment]
Since we are gonna do that, let's apply the increase of pay for the C+ too.

@dhairyasenjaliya Contributor work - $1500 + $250 bug report bonus
@thesahindia C+ work - $1500
@gadhiyamanan bug reporter - $250

Invited you all 3 to job, please comment here when you accept.

**Comment by flodnv** [comment]
bump @michaelhaxhiu ?

**Comment by michaelhaxhiu** [comment]
@thesahindia did you get paid via newDot? Next can you please address [the checklist](https://github.com/Expensify/App/issues/20004#issuecomment-1602993467) above 👆

**Comment by michaelhaxhiu** [comment]
Others are paid ✅

**Comment by JmillsExpensify** [comment]
Reviewed the details for @thesahindia. $1,500 approved for payment via BZ summary above.
