### ISSUE TITLE
Tooltip is not dismissed when details URL is opened and link is located at right end

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20006]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write a long message with any user details page link in it (ensure that link is displayed in right half of message) eg: Hello, this is test with user details link in the end https://staging.new.expensify.com/details?login=%2B918779632836%40expensify.sms
4. Hover on link on the right end in a way that details page is opened over that hover as shown in video
5. Observe that app does not dismiss the tooltip and app still have cursor as pointer
## Expected Result: 
App should change the cursor back to normal and dismiss the tooltip when we open details page of any user
## Actual Result: 
App does not dismiss the tooltip and keeps the cursor as pointer if we hover and click on link in the area where details page will open

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/14a49968-e7b2-46bc-bba6-23165f748007

<img width="960" alt="Screenshot (352)" src="https://github.com/Expensify/App/assets/43996225/68c8be59-b124-4c22-a1ef-69172d9fc324">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685459919770219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
I think this will be fixed automatically in the coming navigation reboot. Maybe put this on hold until then?

https://github.com/Expensify/App/assets/77237602/d8a919b2-9850-4c26-95aa-f3c00c42e795

**Comment by stephanieelliott** [comment]
I think this is expected behavior -- the tooltip persists until the cursor is moved, I would not expect the tooltip to dismiss when the details panel is opened. Rather, I would expect it to dismiss only when the cursor is moved.

**Comment by dhanashree-sawant** [comment]
Hi @stephanieelliott, if you try with just URL and click on area which won't be taken up by details panel, it will dismiss the tooltip. It thus creates inconsistency so if we expect tooltip to not be dismissed then we will need to fix this case.

https://github.com/Expensify/App/assets/87513216/394770eb-d7ce-4ea1-857a-e8ea86d32169
