### ISSUE TITLE
[$1000] Web - Payment - Several errors appear in console while adding BA via Payment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Payment -> Add payment method -> Fidelity
4. Complete the process

## Expected Result:
No any errors in console

## Actual Result:
Several errors appear in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/722f83e0-f19a-437f-b6ce-d1bcb741ec83

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01040271199ebf25d6</li>
        <li>Upwork Job ID: 1666204100456837120</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
I don't have a Fidelity account, but I also get that first error when trying to connect a Capital One account
