### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000]Add Storybook Tests

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#20005]
## Problem
Storybook breaks a lot and it slows down development and causes lots of bugs to be created when it breaks

## Solution
Write a test for it as discussed here: https://expensify.slack.com/archives/C02NK2DQWUX/p1685638129053549?thread_ts=1685637992.927889&cid=C02NK2DQWUX

**Comment by AndrewGable** [comment]
@anmurali - Not a traditional bug here, PR is here https://github.com/Expensify/App/pull/19998

PR is held on https://github.com/Expensify/App/issues/19777

**Comment by AndrewGable** [comment]
@anmurali - Can you pay out? No need for regression, this was a new feature we added.

**Comment by anmurali** [comment]
Sent offer, will close this issue after @allroundexperts accepts and I pay.

**Comment by anmurali** [comment]
paid!
