### ISSUE TITLE
[Accessable Pressables] Migrate TaskHeader to use new Pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20019]
### Description

Migrate [TaskHeader](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/components/TaskHeader.js#LL53C24-L53C24) to use the new Pressable components.

**Comment by Skalakid** [comment]
Hi, can you assign me to this one, please? :D

**Comment by kristianbarth** [comment]
import React from 'react';
import { Pressable, StyleSheet, Text } from 'react-native';

const TaskHeader = ({ title, onPress }) => {
  return (
    <Pressable style={styles.container} onPress={onPress}>
      <Text style={styles.title}>{title}</Text>
    </Pressable>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#ddd',
    padding: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
});

export default TaskHeader;

**Comment by roryabraham** [comment]
This is done
