### ISSUE TITLE
Date of birth allows selection of 31st date when the month has only 30 days

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Profile > Personal details > Date of birth
2. Click on the Save button without selecting a date
3. Now keep clicking on the back button of the month
## Expected Result:
When a month with only 30 days is selected, the date picker should not allow the selection of the 31st date. The date options should be limited to 1-30
## Actual Result:
The date picker allows the selection of the 31st date even when the month has only 30 days.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/491b514b-3828-4d89-98c8-a42fcf11f89d

https://github.com/Expensify/App/assets/43996225/970fd088-b9cc-4817-b23d-ca419ac01394

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685478268680039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by SoftEverest** [comment]
### How to solve that issue?

We should implement the logic that calculate the last day of the month whenever change the month on calendar.

**Comment by bernhardoj** [comment]
This is intentional https://github.com/Expensify/App/issues/16514#issuecomment-1492936726

**Comment by Santhosh-Sellavel** [comment]
@strepanier03 This is intentional and we show an invalid date error message. So we are good to close this one!

**Comment by strepanier03** [comment]
Thank you @Santhosh-Sellavel - I appreciate the update and direction 🙌
