### ISSUE TITLE
Chat - __fake__ member in thread for message in Workspace chat of Removed member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Invite a member in Workspace
3. Send a messages in WS chat
4. Create a thread for this message
5. Remove this member from Workspace
6. WS chat is archived but thread stays in LHN
7. Go to thread chat and check members in settings

## Expected Result:
No fake accounts should be displayed

## Actual Result:
Fake account is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/435f1d03-3dd2-4cab-9b95-a599f8802216

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Hi @lanitochka17 , the message should be archived and not be removed from the LHN. If the report is that the message is still in LHN, that isn't a bug. Going to close this but let me know if I am misunderstanding.
