### ISSUE TITLE
[Accessable Pressables] Migrate TaskSelectorLink to use new Pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20020]
Description
Migrate [TaskSelectorLink](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/components/TaskSelectorLink.js#L58) to use the new Pressable components.

**Comment by Skalakid** [comment]
I will do this one

**Comment by Skalakid** [comment]
I saw that a [PR](https://github.com/Expensify/App/pull/20145) removes this component, so should I migrate it?

**Comment by roryabraham** [comment]
Cool cool this is no longer needed
