### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-13] Disallow new uses of Touchable components

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20024]
### Problem

As part of the [Accessible Pressables](https://github.com/orgs/Expensify/projects/29/views/1?layout=board) project, we are trying to remove all uses of the deprecated Touchable components. However, people have been adding new uses in the meantime. This is an inefficient use of our time.

### Solution

Disallow new uses of the Touchable components.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115bb13b6d4f3633b</li>
        <li>Upwork Job ID: 1669888869819305984</li>
        <li>Last Price Increase: 2023-06-17</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This is done, need to pay @sobitneupane for the review.

**Comment by roryabraham** [comment]
@slafortune the only payment due here is $1000 to @sobitneupane for an internal PR review. It's ready to pay immediately and then we can close this out.

**Comment by slafortune** [comment]
@sobitneupane offer sent!

**Comment by slafortune** [comment]
@sobitneupane - when you get a chance, here is the offer - https://www.upwork.com/nx/wm/offer/25111649

**Comment by sobitneupane** [comment]
@slafortune Accepted the offer. Thanks.

**Comment by slafortune** [comment]
Paid
