### ISSUE TITLE
Send money - No IOU preview displayed in offline if send money to new user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS app
2. Disconnect from the network
3. Tap "+" FAB menu
4. Tap "Send money"
5. Insert amount
6. Tap "Next"
7. Insert email of a user you don't have a chat with
8. Select that user
9. Tap "I'll settle up elsewhere"

## Expected Result:
User lands in a new chat and there is an IOU preview showing the correct amount you have sent

## Actual Result:
User lands in a new chat with skeleton loading UI, no iOU preview is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9a95280a-b6df-4d8a-9fbf-df71d9b001e5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Not overdue, reviewing this now.

**Comment by isabelastisser** [comment]
I'm unable to reproduce this!
