### ISSUE TITLE
Web - Warning message is generated for URLs without https but works well if you click on it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20054]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A which needs to be a phone number and create a new workspace and invite User B, which needs to be a phone number as well.
2. Create a room from User A and include the workspace that you created earlier.
3. Select public room and create a room
4. Now click on the room header and click on share code. Copy the URL.
5. Go to the normal chat with User B and send the link
6. From user B, login in another web chrome which also needs to be a phone number and click on the link that was received so that the room gets accessible
7. Now from User A, send a URL like (www.fb.com or www.amazon.in) which needs to be without including https. See that it generates a warning message. If you click on the link , it opens the link. Thus, for a valid URL, it is still showing the warning.
8. But if you type in URL like : https://www.fb.com/ or [https://www.amazon.com,](https://www.amazon.com%2C/) it doesn't show the warning. Both the links with https or without https opens perfectly without errors, therefore, no warnings should have been generated.

## Expected Result:
Warning message should not be generated for valid URLs

## Actual Result:
Warning message is generated for URLs without https but works well if you click on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a6db1718-8afc-4a34-82fa-1269a9b917d2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685513999114339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Came in before the long weekend - will catch up on this tomorrow.

**Comment by sophiepintoraetz** [comment]
I don't think this is a bug, this is working as intended. Have gone back to the slack thread because I also c[annot reproduce.](https://expensify.slack.com/archives/C049HHMV9SM/p1686190155038899?thread_ts=1685513999.114339&cid=C049HHMV9SM)
