### ISSUE TITLE
Contact Method - Previously closed account cannot be set as secondary login for another account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Create a new account A
3. Close this account
4. Login under account B
5. Try to add account A email as secondary login

## Expected Result:
Email is added as secondary login successfully

## Actual Result:
Error message: Existing accounts cannot be added as secondary logins. Please merge the two accounts, or add the user as your Copilot instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/87095540-ff17-4ca3-89ec-a0a7721c01a3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198720c51f9d92ac9</li>
        <li>Upwork Job ID: 1664647476094070784</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Haven't had a chance to look into it yet. Have been focused on SNH.

**Comment by Santhosh-Sellavel** [comment]
Waiting for @puneetlath!

**Comment by puneetlath** [comment]
I will try to take this to the finish line next week after SNH.

**Comment by puneetlath** [comment]
Ah, so I actually reviewed the video again and this is not a bug. When you started the login process with the email address of the account you closed, that reopens the account. Which is why you don't see the option to add it as a secondary login and instead have to merge it. Let me know if that is unclear.
