### ISSUE TITLE
[Secure Logins] Only Reveal Contact Info to Known Users

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20069]
Part of ["Secure Logins in EChat"](https://github.com/Expensify/Expensify/issues/280523) project

Section of doc: [Only Revealing Data to Known Users](https://docs.google.com/document/d/1G1rjhsPT1S_9BEw7yFvwUcw8AQih0yBANPPPpiKzYlk/edit#heading=h.w8k7lnkrzpty)

Goals:
1. Flagging Unknown Users in Auth
2. Updating Personal Details Object in Web
3. Stop sending public room personal details unnecessarily

**Comment by kadiealexander** [comment]
@Beamanator anything I can do to help keep this moving? :)

**Comment by AndrewGable** [comment]
Adding deploy blocker as we want this added into the next release

**Comment by AndrewGable** [comment]
Pr was merged, removing deploy blocker label

**Comment by kadiealexander** [comment]
Hey team! I'm just adding a note that I'll be OOO until June 26th. I don't think any bug0 team actions will come up this week but if you need a bug0 teammate while I'm gone, please reapply the label! Thanks.

**Comment by Beamanator** [comment]
All related changes are in prod now, will keep this open a few more days then we can close!

**Comment by puneetlath** [comment]
I think it's safe to go ahead and call this done!
