### ISSUE TITLE
User is not taken to correct chat from search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As workspace owner invite new user to workspace
2. As invited new user click FAB button
3. Click New chat
4. Select contact from workspace
## Expected Result: 
Chat with selected user should be opened and textfield should be focused on
## Actual Result: 
New chat with selected contact appeared in sidebar but active chat is wrong

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-3
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4021a811-03b7-4813-8551-aca66580b232

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mkarkachov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685478655077139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Closing as it [cannot be reproduced](https://expensify.slack.com/archives/C049HHMV9SM/p1685923890805219?thread_ts=1685478655.077139&cid=C049HHMV9SM). @kavimuru please re-open when you can repro the issue.

In addition, we're also on v1.3.23-6 (staging).
