### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Message to change the primary login to email is not appearing if the 2/5 steps of bank account set up is completed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Login with phone number user
3. Open any workspace
4. Open connect bank account and observe that it displays the message to change the primary login as a valid email
5. If not already added, add secondary email account
6. Make email account as default
7. Open workspace opened in step 3
8. Open connect bank account
9. Click on connect manually and fill in details in first 2 steps and quit in the step 3 (personal information page)
10. Again change default contact to phone number
11. Open connect bank account 

## Expected Result: 
When primary login is phone number, app should  display message to change the primary login on click of connect bank account
## Actual Result: 
When primary login is phone number and app has previous setup for connect bank account, app  does not display the message to change the primary login
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/da89933a-aeeb-43af-84cb-398f4aa58842

https://github.com/Expensify/App/assets/43996225/0920ebc0-0032-40d6-ad59-2abe9433959a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684855894250829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbdf57ee5b67dd8a</li>
        <li>Upwork Job ID: 1665807914510938112</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Reviewing

**Comment by greg-schroeder** [comment]
This is a bit difficult to follow, confirming bug behavior in Slack

**Comment by greg-schroeder** [comment]
Okay so essentially what we're saying here is if your primary login is a phone number you shouldn’t be able to enter the connect bank account flow at all before adjusting to an email primary login, sure.

**Comment by abdulrahuman5196** [comment]
Thank you for pointed out @greg-schroeder 

@allroundexperts proposal here - https://github.com/Expensify/App/issues/20072#issuecomment-1575214353 looks good.

🎀👀🎀
C+ Reviewed

cc: @MariaHCD

**Comment by MariaHCD** [comment]
Nice, @allroundexperts' proposal looks good to me too

**Comment by abdulrahuman5196** [comment]
BZ checklist

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This issue seems to present during the original ContinueStep implementation itself. We wouldn't have noticed it before secondary method implementation and it is also a very corner case.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. I don't think it would be beneficial to add regression test for this corner case.

**Comment by greg-schroeder** [comment]
Offers sent @allroundexperts @abdulrahuman5196 @dhanashree-sawant

**Comment by abdulrahuman5196** [comment]
@greg-schroeder Accepted the offer.

**Comment by greg-schroeder** [comment]
Paid, checklist complete. Closing.
