### ISSUE TITLE
Web - Recipient's name reverts back from the secondary login email to the primary login email when a user sends an IOU to secondary login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
- recipient should have primary login account A, and secondary login account B
- recipient shouldn't have a display name
- Sender and recipient shouldn't have an existing chat
1. Click on FAB icon
2. Click on Request money link
3. Enter amount & click on 'Next' button
4. Search secondary login account B user
5. Select user
6. Click on 'Request' button
7. Observe the LHN

## Expected Result:
LHN should display the primary login email

## Actual Result:
Secondary login email is first displayed then system reverts back to displaying primary login name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1b13330a-4fa3-4d4d-b985-039865701a93

**Expensify/Expensify Issue URL:**

**Issue reported by:** Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684781009285919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
I'm unable to reproduce this! @kbecciv and @Natnael-Guchima, are you still able to reproduce this? Please let me know; thanks.
