### ISSUE TITLE
Room already exists error is not displayed while creating room if we had previously left the same room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on new room
3. Create new room with any name and for any workspace
4. Leave the room created in step 3
5. Again click on plus and click on new room
6. Fill in same details as used in step 3 and observe that app does not provide any error of room already exists

## Expected Result:
App does not provide 'Room already exists' error below room name if room was created before but we left that room

## Actual Result:
mac safari, mac chrome, windows chrome, android chrome, android app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6312db55-5c08-4b81-884a-719313914226

https://github.com/Expensify/App/assets/93399543/0c127f8e-56f1-4874-b534-04278c6c6d04

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685520394362389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
While this is a bug, it's not something we should fix at this time, as it has to do with the fact that we haven't yet built room discoverability. So the front-end doesn't know which rooms exist unless you're already aware of them.
