### ISSUE TITLE
Tooltips not hidden in mobile view window

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to
2. Login with any account
3. Minimize the window
4. Hovering to chat to show the tooltip
5. Click to open the hovering chat
6. Hovering to back button to show the tooltip
7. Click on back button
## Expected Result:
Tooltips are hidden

## Actual Result:
Tooltips not hidden

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.23-6

**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6768202c-e0ad-4899-89cb-06ddc868950e

https://github.com/Expensify/App/assets/43996225/9591a663-f163-47fe-9506-bd6b0bb731b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
Leaving a note:
This is a known issue we discussed [here](https://github.com/Expensify/App/pull/16052#issuecomment-1493269552) and should be resolved by navigation reboot.

**Comment by MitchExpensify** [comment]
> Leaving a note:
This is a known issue we discussed https://github.com/Expensify/App/pull/16052#issuecomment-1493269552 and should be resolved by navigation reboot.

Thanks at @bernhardoj, so this is a dupe and worth closing just to be sure?

**Comment by bernhardoj** [comment]
@MitchExpensify yes, we can close this one

**Comment by MitchExpensify** [comment]
Nice, thanks!
