### ISSUE TITLE
Web - Settings - The DOB error shows inconsistent behavior where the scroll bar only appears in the month of September.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to "Settings."
2. Click on "Profile."
3. Click on " Personal details."
4. Click on " Date of birth."
5. After selecting the 31st of a month, go through every subsequent month and notice that an error appears for the months with 30 days.
6. Notice that when an error occurs, a scroll bar does not appear for any month except for September.

## Expected Result:
In case of an error, the scroll bar should not appear, ensuring consistent behavior across all months.

## Actual Result:
In the case of a Date of Birth (DOB) error, the scroll bar appears only for the month of September, resulting in inconsistent behavior.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bfb396b0-8d0f-4642-8fc6-6e3703438bab

https://github.com/Expensify/App/assets/93399543/587c98ad-b72b-491c-8759-cba03bbb1ce7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685523088991359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I can't reproduce this - there's no scrollbar for any of the months for me 🤔

**Comment by greg-schroeder** [comment]
Asked in Slack about reproduction steps
