### ISSUE TITLE
IOS - Attachment - Can not add attachment via Option Take a photo - gives Console Error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Start new chat
3. Click to PLUS  + icon
4. Add attachment
5. Take a photo

## Expected Result:
Add attachment successfully

## Actual Result:
Console Error : undefined

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0a3005c0-3a72-4aba-ad0e-614d3cbfa436

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685522807949579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by narzullome** [comment]
Contributor details
Your Expensify account email: narzullodev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017c25637b128f327a

**Comment by narzullome** [comment]
Contributor details
Your Expensify account email: narzullodev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017c25637b128f327a

**Comment by abekkala** [comment]
I had no issue taking these steps: 
1. Open the app
2. Start new chat
3. Click to PLUS + icon
4. Add attachment
5. Take a photo


everything worked as expected, unable to reproduce.

**Comment by narzullome** [comment]
@abekkala The bug occurs on simulator check pls
