### ISSUE TITLE
Search - The chat search function is not working correctly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Chat" application.
2. Click on a chat and enter any combination of numbers and letters.
3. Observe that even though the entered number is invalid, the system generates a number based on the country code using the initial numbers.

## Expected Result:
The number should not be generated and should remain as an invalid number.

## Actual Result:
The system generates an actual number when an invalid number is entered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9986c24b-4b3f-4a61-8600-9568e3ec70a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684813710290909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
MacOS Chrome, in Staging
<img width="351" alt="image" src="https://github.com/Expensify/App/assets/14225673/3f8a6f2b-53fd-4109-8dd5-f25efaf86b3b">
vs valid phone number
<img width="361" alt="image" src="https://github.com/Expensify/App/assets/14225673/9a9159f9-6e8b-429e-8f59-88415126b465">
