### ISSUE TITLE
Contact Method - Set a default contact method is missing for expensifail accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20134]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.expensify.com/
2. Login with expensifail account
3. Add a secondary login
4. Try to set secondary login as default contact method

## Expected Result:
User should be able to set any of the contact methods as default

## Actual Result:
Set as default option is missing for secondary logins

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d5058019-ba64-450a-91b9-4a77a2f24cb6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Expensifail accounts don't have default option in contact method.

**Comment by kbecciv** [comment]
Hello @maddylewis! Yes, correct. It only happened with expensifail accounts, works on public (gmail accounts)

**Comment by maddylewis** [comment]
since i didn't hear back on this question, im closing this out for now - https://github.com/Expensify/App/issues/20134#issuecomment-1580907412
