### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Inconsistency of the [Yes] button color between “Contact method” & “Security” modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open your profile.
2. Click on " Contact methods".
3. Click on " New contact method".
4. Click on " Delete" to remove the existing contact.
5. Notice the modal, “Yes” button is highlighted in red.
6. Now go back and click on "Security".
7. Click on " Close account".
8. Enter default contact method
9. Click on " Close account" button.
10. Notice the modal, “Yes” button is highlighted in green.

## Expected Result:
 In both cases, the “Yes” button should be highlighted in red (and it should be this way across all UI elements in newDot).
 
## Actual Result:
In this case, the “Yes” button is highlighted in different color (i.e. green vs red)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:**  yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ca3a00b6-1f36-4746-97e1-a97c4dac1cbc

https://github.com/Expensify/App/assets/93399543/b38fe422-ce69-4487-bd6a-38f3b280d8a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685527140262479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dad0214cbc98129a</li>
        <li>Upwork Job ID: 1666465549069123584</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
Yup, let's fix it.

**Comment by michaelhaxhiu** [comment]
Correct! Updated the GH body to be a little more clear. Thanks for being very detailed like always, @0xmiroslav :)

**Comment by michaelhaxhiu** [comment]
Just `Yes` feels ideal to me. What do you think?

**Comment by michaelhaxhiu** [comment]
I want @Julesssss to weigh in on this piece :)

**Comment by Julesssss** [comment]
Yeah, given how dangerous this action is I think we should stick with 'Yes, Continue'. Though I don't care that much about it if anyone disagrees.

**Comment by Julesssss** [comment]
I think 'cancel' is okay still personally. It's not an answer, but it is clear that you want to stop the process.

**Comment by Julesssss** [comment]
He's OOO, but we can probably wait.

**Comment by shawnborton** [comment]
I agree these should be the same colors. 

@JmillsExpensify or @trjExpensify - do you feel strongly? I guess since this is a scary permanent action, red makes sense for both cases.

**Comment by trjExpensify** [comment]
>@JmillsExpensify or @trjExpensify - do you feel strongly? I guess since this is a scary permanent action, red makes sense for both cases.

Same, I agree red makes sense for both cases and `cancel` for the button copy. 👍

**Comment by michaelhaxhiu** [comment]
Cool! So let us summarize the desired changes in order to ensure this is all fixed in one job. Then I'll update the GH body to make sure it's 100% clear:

**We have two modals that use the same buttons, and so want to have consistency between them:**

modal 1 - **Closing your account cannot be undone** (e.g. we've referred to it as the "Security" modal in this GH so far)
modal 2 - **Remove contact method**

**So our plan is to do the following in both modals:**
1. Change the `[Yes]` button to show `[Yes, continue]` instead - it's a heavy weight decision, and this phrasing helps suggest that notion to the user.
2. Make the `[Yes, continue]` button red.
3. Change the `[No]` button to `[Cancel]`

cc @dhairyasenjaliya @0xmiroslav let me know if you agree 👍

**Comment by michaelhaxhiu** [comment]
We don't have a speed bonus in affect as far as I can tell, right?

**Comment by Julesssss** [comment]
Ready for payment

**Comment by Julesssss** [comment]
Hey @michaelhaxhiu, can we pay out please?

**Comment by michaelhaxhiu** [comment]
I am confused by this: 

>right. PR merged within 3 days, no regressions.
>This is not bug but improvement. I don't think we need regression test.

I think you are saying there *is a speed bonus* in effect - is that right?

I am just trying to make sure. The job was assigned June 9 and PR was merged to staging June 12.

**Comment by michaelhaxhiu** [comment]
Thanks, that was a derp moment for me.

**Comment by michaelhaxhiu** [comment]
Offers sent to all 3

**Comment by Julesssss** [comment]
Can we close this one out?

**Comment by michaelhaxhiu** [comment]
Not yet, need to pay folks first.

**Comment by michaelhaxhiu** [comment]
all paid now.
