### ISSUE TITLE
[HOLD] Archived announce and admin channels dropped to bottom of the list with unread indicator 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to account A
2. Create a workspace
3. Delete workspace

## Expected Result:
Archived announce and admin rooms should not have "unread" indicator and dropped to the bottom of the LHN list
## Actual Result:
The admin and announce channels get archived with a message that marks them as unread. However, they are also dropped to the bottom of the the list, which means unless you have focus mode enabled, you cannot see what chats are unread unless you scroll all the way to the bottom.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.23-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-01 at 9 48 02 PM](https://github.com/Expensify/App/assets/43996225/880c57d8-5da6-4cc7-badc-a1e85a164614)
![Screenshot 2023-06-01 at 9 47 55 PM](https://github.com/Expensify/App/assets/43996225/866401db-6204-43b1-b323-1dc122d5406a)

https://github.com/Expensify/App/assets/43996225/94b3c348-b405-4ede-9658-86c1c2c92aa5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685659497038729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
on hold

**Comment by MitchExpensify** [comment]
Confirmed, still on hold

**Comment by MitchExpensify** [comment]
On hold

**Comment by MitchExpensify** [comment]
Related do still under review https://github.com/Expensify/App/issues/15212

**Comment by MitchExpensify** [comment]
Not overdue, on hold

**Comment by quinthar** [comment]
I don't know anything about the position of the chat changing in the LHN, I use focus mode and haven't noticed anything there. I'm simply talking about how we should not be marking these rooms as unread.

**Comment by MitchExpensify** [comment]
We are close to [merging the mega app PR](https://github.com/Expensify/App/issues/15212#issuecomment-1673096730) so will test this again once it's on staging to see where we stand

**Comment by MitchExpensify** [comment]
Going to retest seeing as "We merged the App PR that fixes most issues last week https://github.com/Expensify/App/pull/18637" ([Latest here](https://github.com/Expensify/App/issues/15212#issuecomment-1686477758))
