### ISSUE TITLE
RHN Views has a weird top padding on Desktop

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND Desktop and Web apps
2. Go to Settings in both web  & Desktop
3. Observe the top padding all pages on RHN
## Expected Result: 
No weird top padding on the Desktop for RHN views.
## Actual Result: 
Weird padding on RHN Views on Desktop

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-02 at 2 04 01 AM](https://github.com/Expensify/App/assets/43996225/7ec16554-75c6-4e4d-b6a7-dcede942192e)

<img width="1440" alt="Screen Shot 2023-06-04 at 6 54 27 PM" 

src="https://github.com/Expensify/App/assets/43996225/8558bd64-501b-450e-bc5e-4eb249825803">
<img width="1440" alt="Screen Shot 2023-06-04 at 6 55 11 PM" src="https://github.com/Expensify/App/assets/43996225/93d7fd49-034e-4eb9-9728-b982f0b70354">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685651968932869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Is this actually a bug? I feel like this is all intentional and it's currently working just fine as-is. Can you help me understand why this was reported as a bug in the first place?

**Comment by shawnborton** [comment]
Yeah, it's intentional because of the top native desktop buttons we need to account for.

**Comment by Santhosh-Sellavel** [comment]
Did we add this recently?

**Comment by shawnborton** [comment]
Works for me!
