### ISSUE TITLE
[$1000] App crashes on deleting the workspace on room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20150]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Desktop web chrome and login with User A and create a new workspace and invite User B to the workspace
2. Create a room from User A and include the workspace that you created earlier.
3. Select Restricted mode and create a room
4. From user A send a message on the room
5. Login with User B on another web chrome and send a message on that room
6. Make sure that both the User A and User B is on the room page only
6. From User A, delete the workspace and see that the app crashes on User B side
## Expected Result: 
App should not crash on deleting the workspace on room
## Actual Result: 
App crashes on deleting the workspace on room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4d6102e8-882e-4d35-b80c-99fdad383d26

https://github.com/Expensify/App/assets/43996225/15817e98-7bdb-4a25-8925-814ba4e8a20e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685680781344459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d362fbe6cd15da7</li>
        <li>Upwork Job ID: 1665806308064649216</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by johnmlee101** [comment]
Yeah I believe this is the same issue. Let's close this out

**Comment by stephanieelliott** [comment]
Good catch, thanks guys!
