### ISSUE TITLE
[HOLD for payment 2023-06-13] [HOLD for payment 2023-06-12] Add null check for optionItem

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#20154]
## Action Performed:
Coming from this comment: https://github.com/Expensify/App/pull/16079#discussion_r1217062817

Sometimes, if optionItem is empty, the app may crash on logout

## Expected Result:
Not crashing

## Actual Result:
Crashes

## Workaround:
None
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a87db5fcbf792bc</li>
        <li>Upwork Job ID: 1665638628612009984</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by situchan** [comment]
I officially reported this bug in bug channel: https://expensify.slack.com/archives/C049HHMV9SM/p1685908818450029

**Comment by Julesssss** [comment]
CP [seemed to be successful](https://github.com/Expensify/App/pull/20161)

**Comment by muttmuure** [comment]
@narefyev91 I can't see your profile on Upwork. Mind applying to this one directly? It should be public: https://www.upwork.com/jobs/~011a87db5fcbf792bc 

I'll give @situchan and @0xmiroslav each a reporting bonus since you both helped triage the PR too.

**Comment by narefyev91** [comment]
@muttmuure Hey! I'm working from Callstack - no needs to do anything with Upwork

**Comment by muttmuure** [comment]
Offers sent to reporters

**Comment by muttmuure** [comment]
We have an open ticket with Upwork:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/cc638bc6-46db-436e-80f5-c728cd8175a2">
