### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-24] Remove deprecated isIOU beta

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#20173]
### Problem

We have deprecated the IOU beta and all users are opted into the beta. Yet code still exists for the beta. This is a bit confusing. 

### Solution

Remove the beta references from App and then the web console. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01741b4f8dda91e0f3</li>
        <li>Upwork Job ID: 1665722659896651776</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
@Julesssss Can you elaborate on what to remove ?
Below is one of the thing i am assuming we are planning to remove.
<img width="453" alt="Screenshot 2023-06-23 at 5 26 50 PM" src="https://github.com/Expensify/App/assets/78416198/aefdf0e1-7b48-46a8-b9c8-f8e5b20bdfdc">

**Comment by Julesssss** [comment]
[WIP PR](https://github.com/Expensify/App/pull/22643). Will add the remaining screenshots tomorrow.

**Comment by Julesssss** [comment]
PR in review

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Contributor+: @Santhosh-Sellavel $1,000

@Santhosh-Sellavel it looks like you're paid via NewDot. Could you please submit a manual request for payment?

**Comment by Santhosh-Sellavel** [comment]
Waiting for existing requests to be paid. Will let you know once done!

**Comment by sakluger** [comment]
@Santhosh-Sellavel can you only submit one request at a time? I wasn't aware of that limitation.

**Comment by Santhosh-Sellavel** [comment]
@sakluger Check the thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1690435510927379) 

> Please hold from adding new money requests to your existing reports until we’re able to pay out what’s currently outstanding. This will help prevent delaying further payment for any issues where the required information is not yet present.

**Comment by Santhosh-Sellavel** [comment]
Requested Payment $1K on ND

**Comment by JmillsExpensify** [comment]
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by sakluger** [comment]
Asking about the proper next steps in Slack https://expensify.slack.com/archives/C01SKUP7QR0/p1690859901336609

**Comment by sakluger** [comment]
The issue can be closed after payment is approved. Closing!
