### ISSUE TITLE
[$1000] Web - Attachment - Gif without extensions upload properly but shows weird in preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to google and search for any gif image and download it with removed extension
3. Drag the file on the chat
4. Notice that the gif image uploads properly but if you click on it, the attachment name is shown on the left hand side whereas the center side of the preview is empty. Such behaviour is not seen with any other attachments where the attachment name is shown at the left in small.

## Expected Result:
Either the app should not support files without extensions OR if it does , it shouldn't show the attachments in left hand side with the center part empty

## Actual Result:
Gif without extensions upload properly but shows weird in preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.23.7

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1e687f1b-3fe4-4dca-94f3-c58fe89a80a3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685764945290769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152e4cb48ab5dbeb1</li>
        <li>Upwork Job ID: 1666490595019886592</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Not overdue!

**Comment by luacmartins** [comment]
@aimane-chnaif left me know when you get a chance to look at the previous proposals

**Comment by bernhardoj** [comment]
There might be a problem in the BE too. When we send a gif image without extension, the image "src" we get does not have any extension (`/staging/chat-attachments/903460980672066870/w_dfb9b49fe5bce7d2527f71bffc7e6cd3395b4b04.`), but if we send a pdf without extension, the BE will return the "src" with pdf extension (`/staging/chat-attachments/8338107981079143648/w_5b75dc5d516b85eff57ea26a79e14dfd93ccc8ca.pdf`).

_log `htmlAttribs` in `ImageRenderer`_

gif:
<img width="944" alt="image" src="https://github.com/Expensify/App/assets/50919443/67f2b942-0be6-4888-9dca-efefe921f256">

pdf:
<img width="983" alt="image" src="https://github.com/Expensify/App/assets/50919443/32e2ec95-61cc-46a1-ad85-eac5f28e465a">

NOTE: I tested send jpg without extension and it does not have this problem.

**Comment by luacmartins** [comment]
@aimane-chnaif the backend checks and performs operations based on the file mimeType, but it returns an anchor tag with the file extension entered by the user.

**Comment by isabelastisser** [comment]
@aimane-chnaif, can you please follow up on [this comment](https://github.com/Expensify/App/issues/20184#issuecomment-1588218864)? Do we need new proposals?

**Comment by luacmartins** [comment]
Still discussing in Slack

**Comment by isabelastisser** [comment]
[Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1686912137101449) is still going; no updates!

**Comment by luacmartins** [comment]
So the inline preview in the composer seems to work fine. Can we update the modal to be consistent without API changes?

**Comment by luacmartins** [comment]
In the chat list, the video shows the GIF working as expected

**Comment by isabelastisser** [comment]
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by luacmartins** [comment]
Thanks for the context @aimane-chnaif. I'll close this issue in favor of the other one then. Thanks for the discussion everyone!
