### ISSUE TITLE
[$1000] Web - Thread - On editing the top message in the thread, the change doesn't reflect without reloading the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
**Scenario1:**
1. Go to a chat
2. Send a message
3. Hover over the message and create a thread
4. Now edit the message
5. Reload the page

**Scenario 2**
1. Go to a chat
2. Send a message
3. Hover over the message and create a thread
4. Check the LHN chat alternate text
5. Edit the message
6. Now check the LHN chat alternate text should have been changed to the edited message

## Expected Result:
Scenario 1: The message should get updated sooner
Scenario 2: Alternate text shouldn't change

## Actual Result:
Scenario 1: The message doesn't get updated until you reload the page
Scenario 2: It changes to the edited message and on reload it goes back to the previous state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.0

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Scenario 1**

https://github.com/Expensify/App/assets/93399543/3e8a2c60-e537-4440-9498-d9041cd30b88

https://github.com/Expensify/App/assets/93399543/a4ec8df5-7992-4d2f-9b87-8dcb2d9dca6d

**Scenario 2**

https://github.com/Expensify/App/assets/93399543/094bad4e-288d-4850-8fb1-2ee38962f15f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685785066771279 and https://expensify.slack.com/archives/C049HHMV9SM/p1685785190010829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188c7f3126f0773dd</li>
        <li>Upwork Job ID: 1666063944639475712</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by will0225** [comment]
I want to work on this.

**Comment by MitchExpensify** [comment]
Great catch @HezekielT, closing this issue in favor of that one!
