### ISSUE TITLE
Dev: Console error on launching the MacOS desktop app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Launch  the MacOS desktop app
2 Check the console

## Expected Result:
No console error on launching the MacOS desktop app

## Actual Result:
 Console error on launching the MacOS desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/98a6b2c6-2093-42c4-a3f5-64b77ee841b1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685784443148379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I don't have a dev environment. [Asked](https://expensify.slack.com/archives/C03TQ48KC/p1686000050194929) for help reproducing

**Comment by narzullome** [comment]
Can I help to reproduce or some one else should reproduce
