### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Web - Connect Bank _ App Fails to Proceed with Similar Routing and Account Numbers Without Error Message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app settings.
2. Navigate to the Workspace section.
3. Click on a workspace
4. Click on the Travel Section
5. Click on Connect Manually option
6. Connect to the bank manually and add similar routing and account numbers. (I used this as an example,  Routing number:-074000078, Account number:-074000078)
7. Check the "I accept the Expensify Terms of Service" box and click on "Continue"

## Expected Result:
The app should display an error message explaining why you cannot proceed to the next step after clicking on "Continue"

## Actual Result:
The app doesn't allow for identical routing and account numbers to proceed to the next step, but it doesn't provide an error message to explain why.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (57).webm](https://github.com/Expensify/App/assets/93399543/fe978a3f-508c-4c19-9d3d-2c8287bba996)

https://github.com/Expensify/App/assets/93399543/cb9f4483-3370-423a-a38e-bdd8d83a8426

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685780270803909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193062cf01d9d9ba8</li>
        <li>Upwork Job ID: 1665962401680740352</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
Reproduced.

https://github.com/Expensify/App/assets/8292562/d5ee1193-f1bf-4150-bbca-8512c3d3c225

**Comment by JavSFDev** [comment]
how to>

**Comment by aldo-expensify** [comment]
Thanks, assigning @tienifr

**Comment by aldo-expensify** [comment]
@tjferriss we are going with the copy:

- The routing number and account number cannot be the same
- El número de ruta y el número de cuenta no pueden ser iguales

**Comment by tjferriss** [comment]
Everyone has been sent an offer via Upworks. @thesahindia can you please get started on the checklist?

**Comment by tewodrosGirmaA** [comment]
Thank you @tjferriss I accepted the offer, Thank you

**Comment by tjferriss** [comment]
I just resent the offer here https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25259791

**Comment by tjferriss** [comment]
@puneetlath I'm heading out on extended OOO. Can you please help with processing the payments?

**Comment by puneetlath** [comment]
Sure thing. @thesahindia friendly bump on the checklist.

**Comment by puneetlath** [comment]
All paid!
