### ISSUE TITLE
Replace logins with accountIDs in policy members list

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#20211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Tracking issue: https://github.com/Expensify/App/issues/19007

## Problem
As part of the [Secure Logins in NewDot project](https://github.com/Expensify/Expensify/issues/280523) we need to remove all contact info sent by the API and stored in Onyx, but we currently key the `COLLECTION_POLICY_MEMBERS_LIST` in the API by primary login. We also expect to read and store data optimistically in that format in NewDot.

## Solution
Migrate `COLLECTION_POLICY_MEMBERS_LIST` to `COLLECTION_POLICY_MEMBERS` and key each member by `accountID`. The process is described in [this design doc section](https://docs.google.com/document/d/1G1rjhsPT1S_9BEw7yFvwUcw8AQih0yBANPPPpiKzYlk/edit#heading=h.mlzuce28p37y).

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5ff67e82d475ff8</li>
        <li>Upwork Job ID: 1665842541659201536</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
Woops not a bug. I still might need a C+ PR review for an App PR though.

**Comment by neil-marcellini** [comment]
I made a ton of commits today and almost finished migrating everything. It's really messy which I don't feel too great about, but since we're trying to move fast on this I think it will have to do for now and I'll be sure to create clean up issues for later.

The reason it's messy is that all of our APIs still operate by passing emails instead of accountIDs, so I have to convert from accountIDs, get the emails from personal details, and then later map those back to accountIDs for the optimistic data. There's more to it, but that's sort of the **tldr**.

cc @Beamanator @puneetlath if you could please lightly review the draft PR linked above I would appreciate your input.

**Comment by Beamanator** [comment]
Awesome @neil-marcellini!

And ya I imagine it wasn't so easy to get all that working without some of the other migration stuff i've been working on :D

I just merged your branch into mine, I'm planning to get my PR merged into `personalDetails-migration` shortly and then we can re-branch to clean things up today so that HOPEFULLY by EOD we're ready to start real testing & bug fixing on `personalDetails-migration`!

**Comment by neil-marcellini** [comment]
Today I finished the migration on another branch since it wasn't quite done before the merge. Then I looked over all the changes and wrote a list of tests that should cover all of them. I found some problems while testing and it took me a while to debug and fix those. Tomorrow I will finish testing, fix any other problems I find, and we can merge it.

**Comment by neil-marcellini** [comment]
The PR merged into the feature branch last week so this is done.
