### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Thread - Crash when opening the thread image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Send an image to the user
5. Click on "Reply in thread" after sending the image
6. Click to preview the image

## Expected Result:
Image opens

## Actual Result:
App is crashed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/75058993-6d5b-4d0e-b622-68cecb2d5941

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team and @priya-zha
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b43bec189a9704e2</li>
        <li>Upwork Job ID: 1665923449380827136</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Super easy to recreate. Moving on.

<img width="2052" alt="image" src="https://github.com/Expensify/App/assets/10925636/7fda8d37-28ac-43db-b897-10bcb9568e19">

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA is correct and the solution looks good to me. Let's pass `report` instead of `reportID`.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @NikkiWines

**Comment by strepanier03** [comment]
Friendly bump @NikkiWines for your review so we can keep good pace on moving this forward 🙌

**Comment by strepanier03** [comment]
PR has been merged so we're just waiting on deploys. All good for now!

**Comment by strepanier03** [comment]
@zanyrenney - I'm leaving for sabbatical this evening and will not be available to pay this on the 21st. Thank you for handling it!

**Comment by zanyrenney** [comment]
Sure thing! Awaiting payment still, not overdue.

**Comment by zanyrenney** [comment]
Looks like the contributors weren't assigned initially, so assigning them now.

**Comment by priya-zha** [comment]
@zanyrenney submitted the proposal. Thanks.

**Comment by s77rt** [comment]
Applied!

**Comment by tjferriss** [comment]
I've hired everyone in Upworks. Once the offers are accepted, I'll process the payments.

**Comment by s77rt** [comment]
Accepted!

**Comment by tjferriss** [comment]
All payments have been sent including the speed bonus.
