### ISSUE TITLE
Profile - Unable to update avatar offline. Avatar updated after back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Navigate to Profile
3. Off WiFi
4. Delete avatar and add new one

## Expected Result:
New avatar should be displayed a little gray out

## Actual Result:
Unable to update avatar offline. Avatar updated after back online

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dfad4754-068f-4a17-9366-fcd0575481f8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
Testing locally to see if it's still present 🤔

**Comment by robertjchen** [comment]
Can no longer reproduce this issue on staging
