### ISSUE TITLE
Profile - Unable to change time zone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20037
## Action Performed:
1. Log in to the app
2. Open report
3. Check the time of the last message
4. Open Settings -> Profile -> Timezone
5. Change the timezone to some completely different one

## Expected Result:
User able to change time zone

## Actual Result:
Unable to change time zone and previously selected time zone displayed

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24.0

**Reproducible in staging?:** Yes 

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35ec3b29-cfed-4449-b32c-909cae70bfcb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
This may have been fixed by https://github.com/Expensify/App/pull/20220 in 1.3.24-4
