### ISSUE TITLE
[CLOSED FOR PROPOSALS] Removes assignee on Edit task title

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign a task
2. Enter title and assign it to a user
3. Click Confirm Task
4. edit task title
## Expected Result: 
should not remove assignee
## Actual Result: 
removes assignee on edit task title

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/29d79626-7681-4299-acb0-e27e0124f213

https://github.com/Expensify/App/assets/43996225/a6d838f0-3df5-44f9-877b-1271643dd62f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685701939045269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ac6c7f678c21778</li>
        <li>Upwork Job ID: 1666888974330671104</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
I'm going to apply the `External` label so an Upwork job can be created for the Bug Report. No other proposals needed.

**Comment by johncschuster** [comment]
Sorry for the pings @narefyev91 and @deetergp. I just applied the `External` label so I could issue payment for the bug report. (Conversation about that, [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1686238268246269))

**Comment by johncschuster** [comment]
@gadhiyamanan I've sent you an invite for the bug report. Can you ping me when you've accepted that? Thanks!

**Comment by gadhiyamanan** [comment]
@johncschuster accepted, thanks!

**Comment by johncschuster** [comment]
Payment has been issued! Thanks, @gadhiyamanan!

**Comment by johncschuster** [comment]
Now that https://github.com/Expensify/App/pull/19990 has been deployed to prod, let's test this behavior again. @gadhiyamanan, would you mind testing the behavior to see if it persists in the new build?

**Comment by gadhiyamanan** [comment]
I think it's fixed. 
https://github.com/Expensify/App/assets/54790231/6d70abf4-4c52-453c-b522-3cd75e5b9ce2

**Comment by johncschuster** [comment]
Great! I'll keep an eye on the PR for a few more days and then close this manually. Thanks for checking, @gadhiyamanan!

**Comment by johncschuster** [comment]
I'm gonna give this a couple more days (stay back, Melvin)

**Comment by johncschuster** [comment]
Melvin likes bumps. bump.

**Comment by johncschuster** [comment]
One more bump for Melvin. I think we'll be good to close this out on Monday.

**Comment by johncschuster** [comment]
Ok! I think it's safe to close the issue. Thanks for your participation, everyone!
