### ISSUE TITLE
[HOLD on prioritizing P2P] IOU - Button doesn't show the expected text "Pay" or "Pay Elsewhere" 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Action Performed:
1. As userA, request $10 from userB
2. As user B, check the button in the IOU

### Expected Result:
The IOU should display only one button with no dropdown option saying simply "Pay". Expected result extracted from this PR. 
https://github.com/Expensify/App/pull/19817

### Actual Result:
The button displays "Pay Elsewhere" instead of "Pay". 

![image](https://github.com/Expensify/App/assets/44479856/4a160f12-af10-41ad-a6fc-55e098d3cdde)

### Action Performed:
1. UserA creates a workspace and invites UserB as a member
1. UserB requests money from this workspace
1. As UserA (admin), go to the expense report
1. Verify you can see Pay elsewhere option and you cannot see I'll settle up elsewhere option

### Expected Result:
The IOU should display only one button with no dropdown option saying simply "Pay Elsewhere". Expected result extracted from this PR. 
https://github.com/Expensify/App/pull/19817

### Actual Result:
The button displays "Pay" instead of "Pay Elsewhere" and when navigating to the IOU, the user can see the option to "Pay Elsewhere" in the dropdown. 
![image](https://github.com/Expensify/App/assets/44479856/c55e37cf-992d-4fa6-9197-037b3ef0123d)

![image](https://github.com/Expensify/App/assets/44479856/5ea3f917-47b1-465f-80c3-729967b70543)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24-1

**Reproducible in staging?:** Yes
**Reproducible in production?:** No, this is a new change to the button

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Issue found while executing PR https://github.com/Expensify/App/pull/19817 - Assigning @mountiny as he was the author of the PR.

**Comment by mountiny** [comment]
@isagoico Thanks for raising it but these are expected, maybe it was not clear in the test steps, sorry it was a lot of changes and hard to describe.

The single Pay button from the chat should show:
- Pay if the methods are Wallet or VBBA which would be used upon click
- Pay with Paypal if the method is paypal
- Pay elsewhere if the method used would be elsewhere

Then the Expense report detail (workspace request) pay button options should be or:
- Pay with Expensify
- Pay elsewhere

In 1:1 request you wont have the Pay elsewhere, but you will have `I'll settle up elsewhere`

**Comment by mountiny** [comment]
I will close this out, I believe there are no testrail steps to update right now, but if yes, please let us know in slack
