### ISSUE TITLE
[HOLD for payment 2023-06-28] Allow Mark as Read/Unread from LHN

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#20249]
Problem: In NewDot, as opposed to most chat/messaging apps, in order to mark a conversation as read/unread, users need to actually open the chat. This is not a huge inconvenience on Desktop/web, but it can be on mobile. Our very own 
[@ted](https://expensify.slack.com/team/U80CDCSBZ)
 has expressed [a need for this feature](https://expensify.slack.com/archives/C01GTK53T8Q/p1685699971639149?thread_ts=1685643152.571629&cid=C01GTK53T8Q) so he can keep being a terrible friend on our platform too!
 
 
Solution: We now have a long-press menu on the LHN to Pin/Unpin chats! Let’s add another option to mark them as read/unread (the last message would be marked as unread)!

Slack proposal [here](https://expensify.slack.com/archives/CC7NECV4L/p1686041548563739)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad862a284f6e0c5e</li>
        <li>Upwork Job ID: 1666024301398683648</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by Gonals** [comment]
> @Gonals This doesn't have an explicit price on the issue, so unless I hear otherwise I'll pay out @0xmiroslav the default $1000

That sounds reasonable!

**Comment by conorpendergrast** [comment]
Offer sent to @0xmiroslav via Upwork: https://www.upwork.com/ab/applicants/1666024301398683648/hired
Once that's accepted, we'll have the wait period until June 28th and then that'll be paid out

**Comment by conorpendergrast** [comment]
Today is the day! Paid @0xmiroslav and ended contract. All done
