### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] IOU has pin option in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20255]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send money request to user B
2. Open the IOU thread
3. Right-click on IOU thread LHN

~4. Click on 'Pin' button
5. Observe that IOU thread is pinned to the top but that there is no pin icon on the LHN~

## Expected Result:
Pin option shouldn't show since the IOU/expense report can't be pinned because it has the green dot. 

~Pin icon should be displayed on LHN when pinning the thread, and the pin icon should be removed when unpinning the thread~

## Actual Result:
Pin option is shown. 

~Pin icon is not displayed when pinning the IOU thread~

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7469e4dd-e630-418f-8aac-45e1f5c75f7c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685772909333819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139b2338fd7598cc2</li>
        <li>Upwork Job ID: 1668415046377648128</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
I think this is expected behaviour but .... ¯\_(ツ)_/¯. 
Checking [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686270715689889?thread_ts=1685772909.333819&cid=C049HHMV9SM)
> Is it expected behavior to NOT show the :pushpin: in LHN for an IOU thread?  Asking because we're currently showing the :greenlight: and the chat is pinned at the top.  ie. the :greenlight: supersedes the :pushpin: since money is owed (and it's pinned at the top of LHN) so therefore we want to continue to show :greenlight: and not :pushpin: .... right?

**Comment by Natnael-Guchima** [comment]
I think @trjExpensify might know the expected behaviour here.

**Comment by mallenexpensify** [comment]
>  the problem here is that there is the option to pin/unpin IOUs from the LHN context menu which shouldn't be there,

@Ollyws , good catch.  It does make sense that, if the chat isn't pin-able, then we shouldn't show the option. I like that better than allowing pinning
<img width="438" alt="image" src="https://github.com/Expensify/App/assets/22508304/16be3ad3-9e1e-4391-b647-3ac6d6f489b3">

I was going to put this on hold pending the below but noticed it hit production a week ago and that worked on the PR for that @Ollyws
- https://github.com/Expensify/App/issues/19438 

I updated the OP, moving this along

**Comment by mallenexpensify** [comment]
@Ollyws , @parasharrajat , @Natnael-Guchima hired in Upwork, please accept https://www.upwork.com/jobs/~0139b2338fd7598cc2

**Comment by Natnael-Guchima** [comment]
Accepted. Thanks @mallenexpensify

**Comment by mallenexpensify** [comment]
Everyone paid!
@parasharrajat can you fill out the checklist above please?

**Comment by mallenexpensify** [comment]
Thanks @parasharrajat , TestRail issue created
https://github.com/Expensify/Expensify/issues/298942
