### ISSUE TITLE
Desktop deploys are flaky

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20283]
HOLDing for new release of electron-builder, which can be monitored at https://github.com/electron-userland/electron-builder/pull/7592

### Problem
We've seen a lot of flakiness with desktop deploys lately. Here's [an example](https://github.com/Expensify/App/actions/runs/5183019720). They have all been failing in the same way:

```
 • electron-builder  version=24.4.0 os=21.6.0
  • loaded configuration  file=/Users/runner/work/App/App/config/electronBuilder.config.js
  • executing @electron/rebuild  arch=x64 version=22.3.7 appDir=/Users/runner/work/App/App/desktop
  • packaging       platform=darwin arch=x64 electron=22.3.7 appOutDir=desktop-build/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v22.3.7/electron-v22.3.7-darwin-x64.zip size=92 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v22.3.7/electron-v22.3.7-darwin-x64.zip duration=2.91s
  • signing         file=desktop-build/mac/New Expensify.app identityName=Developer ID Application: Expensify, Inc. (368M544MTT) identityHash=0633A09738B5C8B1FF97B81A951198CBB50B87A2 provisioningProfile=none
  • notarization successful
  • building        target=macOS zip arch=x64 file=desktop-build/New Expensify-1.3.24-4-mac.zip
  • building        target=DMG arch=x64 file=desktop-build/NewExpensify.dmg
  • Above command failed, retrying 5 more times
  • building block map  blockMapFile=desktop-build/New Expensify-1.3.24-4-mac.zip.blockmap
  • publishing      publisher=s3 (bucket: staging-expensify-cash)
  • uploading       file=New Expensify-1.3.24-4-mac.zip.blockmap provider=s3
  • uploading       file=New Expensify-1.3.24-4-mac.zip provider=s3
  ⨯ Exit code: 16. Command failed: hdiutil detach -force /dev/disk3
hdiutil: couldn't eject "disk3" - Resource busy

hdiutil: couldn't eject "disk3" - Resource busy
  failedTask=build stackTrace=Error: Exit code: 16. Command failed: hdiutil detach -force /dev/disk3
hdiutil: couldn't eject "disk3" - Resource busy
                                                                                                                                                                         hdiutil: couldn't eject "disk3" - Resource busy
                                                                                                                                                                             at /Users/runner/work/App/App/node_modules/builder-util/src/util.ts:133:18
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Solution
TBD. Some ideas are:

- Create a GitHub support ticket. A lot of the advice for this issue is just restart your computer
- Update electron-builder to add more retries wrapping this call to `hdiutil detach`. We just need to figure out which call is failing for us and verify it's not already wrapped in 5 retries.
- Update electron-builder to implement a backoff mechanism for retries rather than just waiting 1 second between retries.
- Start using macos-13 runners?
- Something else / make this external and ask for help?

**Comment by roryabraham** [comment]
Going to start by creating a GitHub Support ticket.

**Comment by roryabraham** [comment]
Created a [PR](https://github.com/electron-userland/electron-builder/pull/7600) in electron-builder, but was struggling to figure out how to build that monorepo correctly in order to use patch-package.

Going to pivot to trying the macos-13 runner

**Comment by roryabraham** [comment]
Currently have two PRs ready for review to try and fix this:

- https://github.com/Expensify/App/pull/20291
- https://github.com/Expensify/App/pull/20292

**Comment by roryabraham** [comment]
macos-13 runners weren't available, going to revert that PR for now.

**Comment by roryabraham** [comment]
Coming from [here](https://github.com/actions/runner-images/issues/7522#issuecomment-1566746364), let's try running `electron-builder` with sudo?

**Comment by blazejkustra** [comment]
@roryabraham I'm not too familiar with `hdiutil` but running it with sudo is worth a try! What's the current status of #20292? Does this workaround resolve the issue, was it already tested?

While searching for alternative solutions, I came across a related thread [here](https://superuser.com/questions/714965/cant-unmount-dmg-keep-getting-resource-busy). It is quite old but wanted to mention it, as it might be helpful.

**Comment by roryabraham** [comment]
> What's the current status of https://github.com/Expensify/App/pull/20292? Does this workaround resolve the issue, was it already tested?

It hasn't been tested yet

**Comment by fabioh8010** [comment]
If we are facing this error due to facing racing conditions (something is still using the disk while trying to eject), the retry logic may be enough to solve the problem. A follow-up action is to investigate our action if there is something that could be causing this blocking.

**Comment by roryabraham** [comment]
@fabioh8010 you have to look at previous runs on that build:

![image](https://github.com/Expensify/App/assets/47436092/614d4849-810d-46a4-abe5-47488e4db874)

It is very flaky and only worked on the 5th retry

**Comment by roryabraham** [comment]
This flakiness _seems_ to have self-resolved. I think it was a problem with some GitHub Runner(s). Maybe they just restarted them or something, since that's what a lot of the advice online for similar issues said (restart your computer)

**Comment by roryabraham** [comment]
My [upstream PR in `electron-builder`](https://github.com/electron-userland/electron-builder/pull/7600) was merged, reopening this to upgrade `electron-builder` with the next release.

**Comment by roryabraham** [comment]
Subscribed to the release issue [here](https://github.com/electron-userland/electron-builder/pull/7592), putting this on HOLD.

**Comment by roryabraham** [comment]
Taking this off HOLD because a new version of electron-builder including my upstream change has been published: https://github.com/electron-userland/electron-builder/releases/tag/v24.5.0

Also, Snyk opened https://github.com/Expensify/App/pull/20911, so I should work on upgrading Electron too while I'm at it

**Comment by roryabraham** [comment]
This issue is no longer occurring / is a non-urgent bug. We should upgrade electron + electron-builder, but it's doesn't need to be a daily

**Comment by roryabraham** [comment]
Updated electron-builder in https://github.com/Expensify/App/pull/21256

**Comment by jliexpensify** [comment]
Hi @roryabraham - changed this to Monthly, LMK if it needs to be a Weekly. Also, can I unassign myself from this issue? I assume no Upworks payments are needed?

**Comment by roryabraham** [comment]
Our last update seems to have resolved this, closing it out
