### ISSUE TITLE
Extra margin over maximum limit reached error on login page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20297]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open contact methods
5. Click on Add
6. Add new contact method
7. Reopen and keep on clicking resend magic code until you see 'maximum limit reached' error
8. Sign out from the app
9. Login again with same user and observe margin above 'Maximum limit reached' error
10. Write any phone number without country code to trigger insert country code error and observe margin above that error
## Expected Result: 
App should keep consistent margin above all the errors displayed on login page
## Actual Result: 
App has 20px more margin on top for 'Maximum limit reached' error then any other errors on login page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/15e2299d-16e9-4f94-8e01-14b8aac982f2

https://github.com/Expensify/App/assets/43996225/c5267e99-eeef-433f-ba64-85e9d7632940

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685719639488529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I can reproduce this. This is a pretty minor issue, but the padding is different here. @shawnborton curious for your take here. We should standardize on less padding here, right? (So using the padding of the phone number error in the [bottom of the two videos in OP](https://github.com/Expensify/App/issues/20297#issue-1744355568))?

**Comment by joekaufmanexpensify** [comment]
Sounds good. Closing!
