### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] The URL displays "/new/task/undefined" for a second when click next button in edit title page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB > Assign task
2. Enter the title, and description and click the next button
3. Click on the title to go to the edit title page
4. Click the next button
## Expected Result: 
The URL should always display "/new/task"
## Actual Result: 
The URL displays "/new/task/undefined" for a second

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23-4
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Screencast from 29-05-2023 11_45_42.webm](https://github.com/Expensify/App/assets/43996225/f80e18e3-d669-483f-8b33-4dfec6e7a508)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685334649233899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9cbf27bced6bc84</li>
        <li>Upwork Job ID: 1668418496227827712</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
not overdue

**Comment by muttmuure** [comment]
Not overdue but @0xmiroslav mind taking a look this week at https://github.com/Expensify/App/issues/20307#issuecomment-1579462440

**Comment by hayata-suenaga** [comment]
@MonilBhavsar I was auto-assigned to this issue by Melvin bot, but I belive you're already assigned to this issue (probably because of the recent process change)

anyway, I gonna unassign mysefl

**Comment by muttmuure** [comment]
Monil was out for a couple of days, just waiting for him to catch up

**Comment by MonilBhavsar** [comment]
Thanks! Looking now...
Sorry for delay

**Comment by MonilBhavsar** [comment]
Looks good to me 👍 Seems like we missed this during initial implementation

**Comment by MonilBhavsar** [comment]
@dukenv0307 I cannot assign you to the issue as you never commented on this issue. Could you please comment on this issue so I can assign you. Also, next time if you could help us by posting the proposal by yourself rather than through applause, it will be great :) Thank you!

<img width="1722" alt="Screenshot 2023-06-29 at 11 01 29 AM" src="https://github.com/Expensify/App/assets/32012005/90eecb9e-3b60-4bf5-9ead-ca6ede15ac70">

**Comment by muttmuure** [comment]
@0xmiroslav ready for your review

**Comment by MonilBhavsar** [comment]
Need to complete checklist and issue payment before we close this

**Comment by MonilBhavsar** [comment]
@muttmuure @MonilBhavsar 👋

**Comment by muttmuure** [comment]
Looking

**Comment by muttmuure** [comment]
@dukenv0307 offer sent

waiting on @0xmiroslav to aply

**Comment by MonilBhavsar** [comment]
@0xmiroslav are we good to issue payment now?

**Comment by MonilBhavsar** [comment]
Can we pay now?

**Comment by MonilBhavsar** [comment]
Sounds good 👍 
@muttmuure is ooo, but yes let's process payment for everyone else except one

**Comment by muttmuure** [comment]
@dukenv0307 apologies for the delay on this one - you have now been paid.

**Comment by muttmuure** [comment]
Please message me in Slack if you have any questions. Thanks!

**Comment by muttmuure** [comment]
Ah, OK. For sure

**Comment by muttmuure** [comment]
I'll apply a bonus on Upwork

**Comment by muttmuure** [comment]
Urgency and reporting bonus added
