### ISSUE TITLE
The share code route naming convention is not consistent with other routes in the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings
2. Go to Share code
## Expected Result: 
The route name should be "/share-code"
## Actual Result: 
The route name is "/shareCode"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-05-30 at 1 22 58 PM](https://github.com/Expensify/App/assets/43996225/ef8a7d91-dfc0-4baa-8c2c-05c0d3822de9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685435628698119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
Thanks for reporting this, @adeel0202! I can see some inconsistency in our route URLs and have asked for clarity on the convention (camelcase with no dashes vs. lowercase with dashes) we'd like to follow in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1686238806882299).

**Comment by johncschuster** [comment]
Asked in the [#open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1686252760637509) room to get a wider range of opinions.

**Comment by johncschuster** [comment]
I've bumped the thread to get opinions.

**Comment by johncschuster** [comment]
This feels like polish rather than a bug and is very low ROI right now. I'm going to go ahead and close the issue.

(Discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686252760637509))
