### ISSUE TITLE
[$1000] Create task - Share Somewhere - Unable to select a user that doesn't have a existing conversation

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found while executing the retest of https://github.com/Expensify/App/pull/19515

## Action Performed:
1. Tap on FAB
2. Select Create Task
3. Select yourself as the assignee 
4. On Share somewhere, select a user that doesn't have a existing conversation 

## Expected Result:
User is able to select a user that doesn't have a existing conversation with 

## Actual Result:
User is not able to select a user that doesn't have a existing conversation in the shared conversation 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24-5

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/44479856/5b6172c0-481f-4c6a-a555-13764818e024

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f165191f0e10d99</li>
        <li>Upwork Job ID: 1666292938755190784</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
Yup, I am able to reproduce!

**Comment by gadhiyamanan** [comment]
@sophiepintoraetz i think this is [dupe](https://github.com/Expensify/App/issues/19678)

**Comment by sophiepintoraetz** [comment]
Ah, you're right, thanks @gadhiyamanan!
