### ISSUE TITLE
[Tracking] Collect small but useful markdown edits & implement all at once

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20304]
# Problem

There's a decent amount of super small, super edge case Markdown edits we may want to make eventually. This isn't a great ROI so most haven't been worked yet and are just closed as they come up

# Solution

Use this issue to keep track of them as they come up, and eventually consider fixing them all at once if the ROI is high enough

## Markdown issues being tracked

- https://github.com/Expensify/App/issues/17196
- https://github.com/Expensify/App/issues/19446
- https://github.com/Expensify/App/issues/26490

**Comment by Beamanator** [comment]
Not enough to fix for now, postponing

**Comment by Beamanator** [comment]
Not enough to fix still

**Comment by trjExpensify** [comment]
Can I get an opinion on adding [this issue](https://github.com/Expensify/App/issues/26490) to the tracker?

**Comment by Beamanator** [comment]
I like that plan 👍 seems super small but useful to get the fix in "eventually" 👍

**Comment by Beamanator** [comment]
Not enough to fix still

**Comment by trjExpensify** [comment]
👋 Alex, I'm curious what "enough" is? It seems like there's a bit of an inconsistency where some [small markdown bugs](https://github.com/search?q=repo%3AExpensify%2FApp+markdown&type=issues&p=1) are going through to be fixed irrespective of this issue to aggregate and tackle them as one. It kinda' makes this a bit redundant if a small fraction are just going to sit on hold while the majority go through and be fixed.

**Comment by Beamanator** [comment]
That's fair, maybe we can just let them all go through and get fixed as normal 🤷  It's similar to the focus issues, it would be nice to try to batch them but nobody has prioritized figuring out a system for that

**Comment by trjExpensify** [comment]
Yeah, there's no point holding a few if everyone isn't following the same path to aggregate them to one issue to handle as a batch.

**Comment by Beamanator** [comment]
yep def agreed 👍 do you want to start a slack convo about this? Or should we just close this one out? :D

**Comment by trjExpensify** [comment]
I think you can close this out and reopen the two issues that were closed. I'll take mine off hold :)

**Comment by Beamanator** [comment]
ok we're moving forward with individual issues, killing this tracker
