### ISSUE TITLE
DEV: Console warning at payments page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to settings > Payments
3. Click on a payment method
4. Check console

## Expected Result: 
There shouldn't be any console warning
## Actual Result: 
We get a console warning
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7fe86741-df66-4bb3-98fd-3d200e228ba1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684868310292979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console warning at payments page
### What is the root cause of that problem?
 It's happening when the value for `shouldShowMakeDefaultButton` is false, resulting `false` being passed to style prop which will cause warning.
### What changes do you think we should make in order to solve the problem?
 To fix this, we can either update style's propType [definition](https://github.com/Expensify/App/blob/bba4458740c6b119812d259a15f469fa292f3e8e/src/components/Button/index.js#L76) to accept boolean values or we can just update [this line
](https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L476) like below:
```js
                   style={shouldShowMakeDefaultButton ? [styles.mt4] : undefined}
```
### What alternative solutions did you explore? (Optional)
We can update the definition to include boolean [here](https://github.com/Expensify/App/blob/2a786a71bc37004824a1012c1fd2fe4225ebf68b/src/styles/stylePropTypes.js#L3) and use `stylePropTypes` [here](https://github.com/Expensify/App/blob/bba4458740c6b119812d259a15f469fa292f3e8e/src/components/Button/index.js#L76)

**Comment by JmillsExpensify** [comment]
Thank you! I wasn't able to reproduce any console errors on the latest, so I do think we're good here. Please re-open if I've missed something.
