### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Welcome message input field not auto focused

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.Go to the chat
2.Send a message to user
3.Click on "Reply in thread"
4.Click on thread header > Settings > Welcome message
## Expected Result: 
Welcome message input field should auto focused when click on "Welcome message"
## Actual Result: 
Welcome message input field not not auto focused

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/943618c1-35dd-4e48-873b-755b6cc7a68e

https://github.com/Expensify/App/assets/43996225/7a188aed-8a9f-49ce-a0b3-47086119ed3c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685303840840829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af6bfe68d473c41b</li>
        <li>Upwork Job ID: 1666483320229822464</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
Duplicated https://github.com/Expensify/App/issues/20140
my proposal [here](https://github.com/Expensify/App/issues/20140#issuecomment-1575274681) before this issue is created with 2 days.

**Comment by tylerkaraszewski** [comment]
Sounds good, go ahead @ahmedGaber93

**Comment by ahmedGaber93** [comment]
@tylerkaraszewski @allroundexperts [PR](https://github.com/Expensify/App/pull/20556) now is ready for review.

**Comment by abekkala** [comment]
@allroundexperts have you had a chance to review the PR yet?

**Comment by mountiny** [comment]
Noting that qa raised this is not fixed on all platforms, asking them for videos/ comment.

**Comment by kavimuru** [comment]
@mountiny Adding video for the failed platform iOS Safari

https://github.com/Expensify/App/assets/43996225/5e0ea2ed-86f7-410e-a867-2e9658c82c3b

**Comment by mountiny** [comment]
I think this might be ios web specific issue which we have seen in other flows before.

**Comment by mountiny** [comment]
the regression above is a known issue on mWeb safari so it should not affect the reward

**Comment by abekkala** [comment]
### Payments to be made on Jun 23:

- Issue reported by: @ayazhussain79 [$250]
- Selected Proposal for fix: @ahmedGaber93 [$1000] + [$500 PR bonus]
- C+ Review: @allroundexperts [$1000] + [$500 PR bonus]

**Comment by abekkala** [comment]
@allroundexperts can you complete the BugZero checklist above?

**Comment by abekkala** [comment]
@ayazhussain79 and @allroundexperts offers have been sent. Once checklist is completed I can process those payments. 

@ahmedGaber93 can you please link your Upwork profile here? I was unable to find you. Once I have your link I can send you the Upwork Payment Offer.

**Comment by ayazhussain79** [comment]
@abekkala offer accepted

**Comment by ahmedGaber93** [comment]
https://www.upwork.com/freelancers/~012883934e2c4dc4e7
@abekkala

**Comment by ahmedGaber93** [comment]
@abekkala Accepted

**Comment by abekkala** [comment]
@ahmedGaber93 payement sent and contracted ended - thank you! 🎉 

Closing this one out!
