### ISSUE TITLE
Clicking on reactions to different comments makes bunch of sticky menus

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Tap the reaction for different comments
## Expected Result:
Moving from one comment to another reaction menu should disappear
## Actual Result:
Tapping it on different comments makes a bunch of sticky menus.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![2023-06-01_12-17-05](https://github.com/Expensify/App/assets/43996225/17139c4d-6012-4fd7-812c-5a6029716cb6)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685658144247959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@marcaaron are you still able to reproduce? I wasn't able to on staging in Chrome, Firefox nor Safari.

**Comment by mallenexpensify** [comment]
Going to close as Kavi and I weren't able to reproduce.  @marcaaron, reopen if you're able to

**Comment by mallenexpensify** [comment]
hmm... we might be updating the process to assign to the reporter and move to the E/E repo ¯\_(ツ)_/¯
https://expensify.slack.com/archives/C01SKUP7QR0/p1686024498712479
