### ISSUE TITLE
Web - Chat - Reason after 'Requested money for' is not shown for description that starts with <

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on new chat and enter email of any user
3. Click on request money and on the description type any sentence that should start with < (There should be no gap between < and sentence). Request the money.
4. On the LHN , notice that on the new request money page chat,  it displays 'Requested money for' , but the text that we inputted earlier is missing after 'for' word

## Expected Result:
Reason after 'Requested money for' should be shown for description that starts with <

## Actual Result:
Reason after 'Requested money for' is not shown for description that starts with <

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.1

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5a89a7c8-c58c-407c-90ec-e0b22606107c

https://github.com/Expensify/App/assets/93399543/7af12685-4356-4bb3-a39c-c5644b8a6c60

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1685794745289299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c18c988b75632a4c</li>
        <li>Upwork Job ID: 1666407451285585920</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by sethraj14** [comment]
@michaelhaxhiu  Done the debugging for this, currently the API is returning incorrect text from the backend. This needs to be fixed in the API itself.
![Screenshot 2023-06-07 at 5 20 38 AM](https://github.com/Expensify/App/assets/14844259/507d839c-22eb-4c00-a19d-b9dda51be2df)

**Comment by spcheema** [comment]
@sethraj14 description is missing in email as well ![image](https://github.com/Expensify/App/assets/19812199/3fe8f037-4b13-490b-a4ad-f55717ed3ffa)

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
No c+ here, as the fix is on the server side

**Comment by roryabraham** [comment]
The PR caused a regression on staging, updated PR to fix it [here](https://github.com/Expensify/Web-Expensify/pull/37784)

**Comment by Gonals** [comment]
This is done!

**Comment by priya-zha** [comment]
@Gonals I'm the external reporter for this bug. Thanks.

**Comment by michaelhaxhiu** [comment]
Paid now.
