### ISSUE TITLE
[$1000] mWeb - Copy to clipboard option not present on the link type: Schedule a setup call

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20321]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Menu > Workspaces > tap into a Workspace
2. Tap on the (?) help icon in top-right
3. Press and hold on the "Scheduled a set up call"

## Expected Result:
Copy to clipboard option should be present for all links

## Actual Result:
Copy to clipboard link is not present for Schedule a setup call

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yas

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e91540dc-639e-4f13-a953-769a7332b80b

https://github.com/Expensify/App/assets/93399543/3911e22e-eb5a-47f0-8e30-664a6efd13a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @chiragxarora

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684778570184059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014701441d97e4e225</li>
        <li>Upwork Job ID: 1666454151545909248</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
 Copy to clipboard option not present on the link type: Schedule a setup call
### What is the root cause of that problem?
Root cause of the problem lies in the `GetAssistancePage` where for the Calendar link, we are not passing the `link` prop to the Calendar link component which we are pushing in menu items list.
https://github.com/Expensify/App/blob/758ef379ed63f5ccbac7f9bba35a497c0d4966f5/src/pages/GetAssistancePage.js#L66-L76
This missing prop prevents the desired behavior on right click/ long press which opens a copy to clipboard popover in other links present in the app.
### What changes do you think we should make in order to solve the problem?
We need to pass the additional `link` prop to the calendar link item in `menu items` before we render it in the component.
By doing this, whenever user is eligible for calls with their guide, `guideCalendarLink` will contain a link which will set the if condition true.
And now we need to pass the link prop with the value as `guideCalendarLink` and we are done.
```js
const guideCalendarLink = lodashGet(props.account, 'guideCalendarLink');
    if (guideCalendarLink) {
        menuItems.splice(1, 0, {
            title: props.translate('getAssistancePage.scheduleSetupCall'),
            onPress: () => Linking.openURL(guideCalendarLink),
            icon: Expensicons.Phone,
            shouldShowRightIcon: true,
            iconRight: Expensicons.NewWindow,
            wrapperStyle: [styles.cardMenuItem],
            link: guideCalendarLink,
        });
    }
```
<details>
  <summary>Results</summary>
</details>
### What alternative solutions did you explore? (Optional)
None

**Comment by chiragxarora** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
 Copy to clipboard option not present on the link type: Schedule a setup call
### What is the root cause of that problem?
Root cause of the problem lies in the `GetAssistancePage` where for the Calendar link, we are not passing the `link` prop to the Calendar link component which we are pushing in menu items list.
https://github.com/Expensify/App/blob/758ef379ed63f5ccbac7f9bba35a497c0d4966f5/src/pages/GetAssistancePage.js#L66-L76
This missing prop prevents the desired behavior on right click/ long press which opens a copy to clipboard popover in other links present in the app.
### What changes do you think we should make in order to solve the problem?
We need to pass the additional `link` prop to the calendar link item in `menu items` before we render it in the component.
By doing this, whenever user is eligible for calls with their guide, `guideCalendarLink` will contain a link which will set the if condition true.
And now we need to pass the link prop with the value as `guideCalendarLink` and we are done.
```js
const guideCalendarLink = lodashGet(props.account, 'guideCalendarLink');
    if (guideCalendarLink) {
        menuItems.splice(1, 0, {
            title: props.translate('getAssistancePage.scheduleSetupCall'),
            onPress: () => Linking.openURL(guideCalendarLink),
            icon: Expensicons.Phone,
            shouldShowRightIcon: true,
            iconRight: Expensicons.NewWindow,
            wrapperStyle: [styles.cardMenuItem],
            link: guideCalendarLink,
        });
    }
```
<details>
  <summary>Results</summary>


https://github.com/Expensify/App/assets/54641656/9a3d4e96-c811-4cab-a27d-f210838805f9




</details>
### What alternative solutions did you explore? (Optional)
None

**Comment by chiragxarora** [comment]
@parasharrajat refer the slack thread, it's been discussed and l agreed to fix.

**Comment by alex-mechler** [comment]
@parasharrajat while this is a CTA, it actually is opening a link when the user presses the button. For consistency, we should add Copy to Clipboard as a result

**Comment by chiragxarora** [comment]
QA one is mine too, I posted the proposal on slack too, that was copied by the QA team

**Comment by chiragxarora** [comment]
[PR](https://github.com/Expensify/App/pull/20557) is ready for review here

**Comment by alex-mechler** [comment]
Hmm, not sure why the automation was failing here, but this is on production now cc @sonialiap

**Comment by sonialiap** [comment]
Thanks, Alex!

**Comment by sonialiap** [comment]
@chiragxarora offer sent for reporting issue + fix (+bonus)
@parasharrajat offer sent for review (+bonus)

**Comment by michaelhaxhiu** [comment]
I'm removing AlexM's assignment, and not going to trigger assignment of a new CME (since this is ready for payment at this stage!).

**Comment by sonialiap** [comment]
Everyone has been paid ✅
