### ISSUE TITLE
Web- Chat - The chat is highlighted with a blue frame 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on any chat in LHN by mouse twice (composer should become NOT active)
4. Press any characters from the keyboard

## Expected Result:
The chat not highlighted with a blue frame

## Actual Result:
The chat is highlighted with a blue frame + error in console appears"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4636173a-f4f1-46ce-b222-18219d9b4343

![image (53)](https://github.com/Expensify/App/assets/93399543/97cc3855-99d6-4aab-b946-46aa19106c51)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Mitch Ward

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685802837970769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Closing as this is a dupe
