### ISSUE TITLE
[HOLD for payment 2023-06-19] [iOS] Enable 120fps refresh rate

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20346]
Coming from [here](https://expensify.slack.com/archives/C04878MDF34/p1686129736247639) (internal)

### Problem

The iOS app does not allow for the 120fps option which is a normal screen refresh rate for new iPhones.

### Why

Allows for smoother animations and puts the app on par with other apps users might be used to

### Solution

Update the info.plist to allow this refresh rate

**Comment by mountiny** [comment]
Straightforward change from SWM 🚀

**Comment by flaviadefaria** [comment]
@mountiny can you confirm if the payment for this should be $1000 or less? Thanks!

**Comment by mountiny** [comment]
Actually no payment required here As the review was handled internally and Tomasz is from SWM who is handling payment differently.

I think we can close this as completed now, thanks!
