### ISSUE TITLE
[HOLD for payment 2023-09-04] Selection List Refactor: Checkbox List

### ISSUE THREAD

**Issue by thiagobrez** [Expensify/App#20353]
This issue keeps track of Phase 2 of the Selection List Refactor, in which we are refactoring all different list component variations into 3 new, clean components:

- Phase 1: Radio Button List
- Phase 2: Checkbox List (this phase)
- Phase 3: Simple Selection List

Thoroughly discussed in the parent issue: https://github.com/Expensify/App/issues/11795#issuecomment-1573880715

**Comment by thiagobrez** [comment]
Correct @cristipaval. I'll send the PR for the [first refactor](https://github.com/Expensify/App/issues/20352) tomorrow. Then I'll start on this one.

**Comment by thiagobrez** [comment]
Starting to investigate this.

**Comment by shawnborton** [comment]
Can you show me what you are referring to? I agree that we need to do a better job of making multiple selections look like checkboxes and single selections (though they don't really exist in the app yet) look like radios.

**Comment by thiagobrez** [comment]
@shawnborton My bad, forgot to attach screenshots 🤦🏻‍♂️ 

This is what I was referring to:
| Workspace manage members | Workspace invite members |
|--------|--------|
| ![image](https://github.com/Expensify/App/assets/26878038/ca99dc21-afe6-48cd-85ef-b4e98f0d7626) | ![image](https://github.com/Expensify/App/assets/26878038/9f875e52-b1e7-4f13-89cf-51d2d3999b75) |

**Comment by shawnborton** [comment]
Got it. I think we should just leave those untouched for now and focus only on existing checkboxes. I think we will examine the overall pattern and relationship between checkboxes and list views at some point in the future.

**Comment by thiagobrez** [comment]
Weekly update: got the base structure working alongside Manage Workspace Members List. Iterated on top of the new component introduced in Phase 1 changes (PR still being reviewed [here](https://github.com/Expensify/App/pull/21048)), so that needs to be merged before raising a PR for this one.

Next week will work on the remaining multiple selection lists, which should be quicker now that the base is ready.

**Comment by thiagobrez** [comment]
Hey @cristipaval! I noticed that I'm not assigned to this issue. Just pointing out because I know you guys use it for internal processes :)

**Comment by cristipaval** [comment]
Good point. You're now assigned.

**Comment by thiagobrez** [comment]
Weekly update: all multiple selection lists are working! 🎉 

That is:
- Workspace members page
- Workspace invite members page
- Split bill page
- New group page

Next steps are to improve the Storybook stories and performance tests built in Phase 1 PR, which is still being reviewed. Once that is merged, I can rebase into this one and raise the PR for Phase 2.

**Comment by thiagobrez** [comment]
@shawnborton Current state of multiple selection lists:

### Workspace members and invite

Before, workspace members page and workspace invite page were using 2 different lists. Members page was using checkboxes while invite page was using radio buttons. Members page had no keyboard controls, while invite page had.

Now, both are standardised using the same component, all checkboxes with keyboard controls.

Would like your input specially regarding disabled items (admin, for example):

- Previous behavior was that it was still selectable, and showed an error when selected. In my opinion this is unnecessary because it's one extra step for the user to discover that his action will not be possible. Also, it causes a weird behavior with the "Select All" checkbox, since you can manually select that item, but when checking "Select All", that item wasn't selected

- Current behavior is that items that can't be selected are disabled upfront (and indicated with opacity style). This makes it obvious for the user that it can't be selected, and prevents any weirdness with the "Select All" checkbox, since it can never be selected

What do you think, do you agree? See videos below

| Before | Current |
|--------|--------|
| <video src="https://github.com/Expensify/App/assets/26878038/897f3789-382d-4e91-9eeb-ab7f4ee9e593" /> | <video src="https://github.com/Expensify/App/assets/26878038/93ee1f1f-e579-4abe-a0a6-73ab268d70e4" /> | 

### Split bill

Standardised using new checkbox list component

<video src="https://github.com/Expensify/App/assets/26878038/f7ed83a1-acc2-4be9-91c8-f1bf0e210eff" />

### New group

Standardised using new checkbox list component

<video src="https://github.com/Expensify/App/assets/26878038/5c9defcb-a683-4cfc-a956-ae9c5c255d45" />

**Comment by shawnborton** [comment]
Hmm I don't think we should make the whole admin row appear "disabled" though - but rather, let's just make the checkbox part look disabled. Otherwise we are competing with some offline patterns we use here, cc @trjExpensify 

As for the others, I don't think we should use these kinds of checkboxes on the split or group pages yet. Let's leave them as-is.

**Comment by thiagobrez** [comment]
>Hmm I don't think we should make the whole admin row appear "disabled" though - but rather, let's just make the checkbox part look disabled. Otherwise we are competing with some offline patterns we use here

Ok, cool 👍🏻 

>As for the others, I don't think we should use these kinds of checkboxes on the split or group pages yet. Let's leave them as-is. I left that https://github.com/Expensify/App/issues/20353#issuecomment-1602670230 for you above.

My mistake, I understood it differently when I read it the first time. Will leave as-is

**Comment by trjExpensify** [comment]
>Otherwise we are competing with some offline patterns we use here, cc @trjExpensify

Totally agree, that's the "pending create" pattern used when adding a member with "offline pattern B". 👍

**Comment by thiagobrez** [comment]
Had to focus on a higher priority issue for the last days. Coming back to this on Monday, very close to raising a PR

**Comment by thiagobrez** [comment]
Update: Draft PR is being reviewed internally

**Comment by thiagobrez** [comment]
Just a heads up: I'll be OOO for the rest of the week, but @ArekChr will be covering for me if anything is needed. Thanks!

**Comment by thiagobrez** [comment]
Update: PR is in final stages of review

**Comment by thiagobrez** [comment]
Update: PR is in final stages of review

I'll be OOO tomorrow and Friday, someone from Callstack will pick up from where I left if needed.

**Comment by cristipaval** [comment]
> ### Bug0 Triage Checklist ([Main S/O](https://stackoverflowteams.com/c/expensify/questions/14418))
> * [ ]  This "bug" occurs on a supported platform (ensure `Platforms` in OP are ✅)
> * [ ]  This bug is not a duplicate report (check [E/App issues](https://github.com/Expensify/App/issues) and [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM))
>   
>   * If it is, comment with a link to the original report, close the issue and add any novel details to the original issue instead
> * [ ]  This bug is reproducible using the reproduction steps in the OP. [S/O](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=The%20bug%20is%20reproducible)
>   
>   * If the reproduction steps are clear and you're unable to reproduce the bug, check with the reporter and QA first, then close the issue.
>   * If the reproduction steps aren't clear and you determine the correct steps, please update the OP.
> * [ ]  This issue is filled out as thoroughly and clearly as possible
>   
>   * Pay special attention to the title, results, platforms where the bug occurs, and if the bug happens on staging/production.
> * [ ]  I have reviewed and subscribed to the linked Slack conversation to ensure Slack/Github stay in sync

Ignore this @slafortune , I added `Bug` label for the payments.

**Comment by Santhosh-Sellavel** [comment]
@cristipaval This is a huge PR and there were 4 follow-ups till two got merged & two were in review two more PRs to come can we increase the bounty to $3k or at least $2K thanks!

**Comment by slafortune** [comment]
Sorry for the delay on this @Santhosh-Sellavel. While the PR was big, it appears to have been more fragmented rather than causing a huge time suck and blocking you on other things.

**Comment by slafortune** [comment]
Payment summary - 

Bug reporter - NA
@thiagobrez does not require payment (Contractor)
@Santhosh-Sellavel is Eligible for Manual Requests and owed $1000

**Comment by Santhosh-Sellavel** [comment]
> Sorry for the delay on this @Santhosh-Sellavel. While the PR was big, it appears to have been more fragmented rather than causing a huge time suck and blocking you on other things.

I disagree it might look like but that's not the case here. It directly affects certain areas covered in this phase, as well affects the changes done in this first phase. So a lot of time of invested in the Review & testing.

cc: @cristipaval Let me know your thoughts, thanks!

**Comment by slafortune** [comment]
@Santhosh-Sellavel We want to clarify that the advertised price for the job is non-negotiable. We do not review or adjust the payment for smaller PRs either. This decision is final, and we will proceed accordingly. If you have any further questions or concerns unrelated to the price, please feel free to discuss them.

**Comment by Santhosh-Sellavel** [comment]
@slafortune 

Fine I'll settle for the $1K here if it's final decision.

But we do change the price based on complexity or it's time consuming. There is no advertised price for the job. We had a fixed price a $1000 C+ per internal/agency PR review at that point. 

Only certain PR qualifies for price revisions if it's approved by CME/BZ. 

Thanks!

**Comment by slafortune** [comment]
Payment Summary -

Bug reporter - NA
@thiagobrez does not require payment (Contractor)
@Santhosh-Sellavel is Eligible for Manual Requests and owed $1000

cc @anmurali @JmillsExpensify

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @Santhosh-Sellavel based on BZ summary.
