### ISSUE TITLE
[HOLD for payment 2023-07-17] Selection List Refactor: Radio Button List

### ISSUE THREAD

**Issue by thiagobrez** [Expensify/App#20352]
This issue keeps track of Phase 1 of the Selection List Refactor, in which we are refactoring all different list component variations into 3 new, clean components:

- Phase 1: Radio Button List (this phase)
- Phase 2: Checkbox List
- Phase 3: Simple Selection List

Thoroughly discussed in the parent issue: https://github.com/Expensify/App/issues/11795#issuecomment-1573880715

**Comment by thiagobrez** [comment]
Update: still on Step 1

>Step 1: Create a new, clean component for the Radio Button List, keeping the old one untouched

**Comment by cristipaval** [comment]
Thanks for the update!

**Comment by thiagobrez** [comment]
Left an update in the [umbrella issue](https://github.com/Expensify/App/issues/11795#issuecomment-1594644949):

>Working on https://github.com/Expensify/App/issues/20352. Got a clean component working with all previous features for one use-case (Timezone selection). Now, for the other use-cases it should be simpler as the base is done, and I might just need to add a few extra props for customisation. Then, I'll create a few Storybook stories to leave it well documented.

**Comment by thiagobrez** [comment]
PR ready to review here: https://github.com/Expensify/App/pull/21048

**Comment by thiagobrez** [comment]
Weekly update: PR waiting for review

**Comment by thiagobrez** [comment]
Weekly update: PR is being reviewed, appears to be close to approval

**Comment by Santhosh-Sellavel** [comment]
@twisterdotcom Actually payment should have been got here, we mixed up on the parent issue and got it there.

https://github.com/Expensify/App/issues/11795#issuecomment-1640709260

We are good to close this one out, thanks!

**Comment by twisterdotcom** [comment]
Oh weird, yes this is kind of a dupe. Okay, we can close this one then.
