### ISSUE TITLE
[HOLD for payment 2023-06-15] Wrong date is being selected on the date of birth page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Sign in with an account without a date of birth
2. Go to Settings > Profile > Personal Details
3. Go to Date of birth
4. Click on Year picker
5. Select any year
6. Click on any date on the calendar

## Expected Result:
Describe what you think should've happened

 Correct date is selected

## Actual Result:
Describe what actually happened

Wrong date is selected

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686139022417219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d02fee1867c8c21d</li>
        <li>Upwork Job ID: 1666422998433857536</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Hey @mountiny do you think this should be resolved in this issue? (they seem a little different but kinda the same too) https://github.com/Expensify/App/issues/16514

**Comment by mountiny** [comment]
Fully handled internally, nothing required for the checklist, the bug is from  major refactor.

**Comment by mountiny** [comment]
yep handling in one issue altogether so we are more efficient

**Comment by mountiny** [comment]
that might be handled separately
