### ISSUE TITLE
[$250] App does not navigate to settings page on click of back button from Workspaces page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20367]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to workspace( you are not member of that workspace) by using URL(like https://staging.new.expensify.com/workspace/46A25F84D69AC16F)
2. click on back button to go Workspaces page
3. again click on back button

## Expected Result:

on click of back button from Workspaces page, it should redirects to settings page

## Actual Result:

Clicking the back button from the Workspace page redirects to the same error you received when using the URL in step 1 of the repro. 

<img width="1247" alt="image" src="https://github.com/Expensify/App/assets/10925636/733890c6-c2bf-4674-b90d-e50ac8490c49">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/36083550/34292763-dc8c-44a2-a748-d3bb56ebfeb1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686120651274409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124d0c174d8abc678</li>
        <li>Upwork Job ID: 1666448453011419136</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
@mountiny - The expected and actual results seem to be worded the same to me. I updated the actual result to match what I experienced during testing and added some visual evidence too.

Will continue to follow along.

**Comment by mountiny** [comment]
I have included the video from Slack in the body which hopefully makes it clearer, thanks!

**Comment by mountiny** [comment]
This was actually resolved so I htink we can proceed with the bug report payment here even now

**Comment by strepanier03** [comment]
Sounds good @mountiny, I'll get that squared away!

**Comment by strepanier03** [comment]
@gadhiyamanan I just hired you to a reporting job, I'll check in before the end of my day to see if it's payable otherwise I'll be back tomorrow.

**Comment by jeet-dhandha** [comment]
This is fixed so can we close this now ?

**Comment by mountiny** [comment]
@gadhiyamanan have you been paid?

**Comment by strepanier03** [comment]
I've finishing paying this out now so we can close. I wasn't able to pay last week before I left because the offer hadn't been accepted yet but we're all good now. 

Thank you @gadhiyamanan, you should be all set.
