### ISSUE TITLE
[$1000] Can't delete IOU money request message

### ISSUE THREAD

**Issue by multijump** [Expensify/App#20369]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money to other user via IOU message.
2. Click the Request money message
3. Click the ... button in left top corner
4. Click the Delete button
<img width="1735" alt="image" src="https://github.com/Expensify/App/assets/35476479/1fe171b0-78be-493a-9e6f-b10829d051a8">

## Expected Result:
Removed message from left panel and canceled money request.

## Actual Result:
Nothing happened.

## Workaround:
Can the user still use Expensify without this being fixed?  - Yes
Have you informed them of the workaround? - Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:Current Staging web app**
**Reproducible in staging?:Yes**
**Reproducible in production?:Not sure**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:Couldn't leave log bc don't have team account** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:

https://github.com/Expensify/App/assets/35476479/6659b1fd-604b-477f-85a7-911ece4aa676

** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:@multijump**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163a58804a019a7ce</li>
        <li>Upwork Job ID: 1678470305852305408</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Issue is reproduced in build 1.3.37.1

https://github.com/Expensify/App/assets/78819774/8cfcd52c-46b3-44d5-b6c3-6816aae30e5b

**Comment by lanitochka17** [comment]
Issue is reproduced in build 1.3.37.1

https://github.com/Expensify/App/assets/78819774/5388c42b-2d85-4df1-b79c-59c33bda1dbd

**Comment by tjferriss** [comment]
@lanitochka17 thanks for catching this. I'm not sure why MelvinBot closed it in the first place, but I definitely missed it last month. I can still reproduce the issue and I don't see it reported anywhere else.

**Comment by multijump** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't delete IOU money request message

### What is the root cause of that problem?
There is no implementation to delete Money Request when click the Delete menu in ThreeDotMenu in MoneyRequestHeader.
https://github.com/Expensify/App/blob/c766c10af81e696e30e63e17770e464a4f57f271/src/components/MoneyRequestHeader.js#L77C40-L77C40
When click `Delete` button, this `onSelected` function executes but this function is empty now.

### What changes do you think we should make in order to solve the problem?

We can add the function body in `onSelected` function and call `deleteMoneyRequest` function in IOU.
https://github.com/Expensify/App/blob/a42c83b7ef45499340428dd4467ea662cda0fb0c/src/libs/actions/IOU.js#L779

### What alternative solutions did you explore? (Optional)
Nothing

**Comment by mountiny** [comment]
This is being actively worked on there is a pr from luacmartins for this. https://github.com/Expensify/App/issues/19066

We can close this issue
