### ISSUE TITLE
[$1000] Web - NewRoom - Structure of App broken with long WS name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondional: you should have WS with a long name

1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Reduce page size
4. Click on FAB -> New Room
5. Open the drop-down for choosing WS

## Expected Result:
The drop-down menu NOT goes beyond the front page

## Actual Result:
Structure of App broken, the drop-down menu goes beyond the front page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6083471_image__111_](https://github.com/Expensify/App/assets/78819774/535bd5a1-19c6-4cad-8505-57461f40a7f2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6a3bf5662771cb7</li>
        <li>Upwork Job ID: 1666469633114157056</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by Shubham1429** [comment]
Contributor details
Your Expensify account email: shubhambhardwaj142@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016f6824fae4b902a0

**Comment by jeet-dhandha** [comment]
How do i get access to `New Room` button. As accessing it using code is a lot of debugging as i have to comment a lot of code.

**Comment by jeet-dhandha** [comment]
# Proposal

## Rephrase the problem: 
- The workspace name is exceeding the window boundaries, so the maximum visible text in the window should be around 35 characters. This was achieved through trial and error.

## Solutions:
(Code below requires modification)

https://github.com/Expensify/App/blob/8415bb243d5bc05f0bf5eb1e6457f6c5a43aa7fd/src/pages/workspace/WorkspaceNewRoomPage.js#L131-L134

- I am utilizing Expensify's common library by importing `Str` for both solutions. 

## Solution 1
- The updated code will truncate the text in the middle and append a trail text.

```
const workspaceOptions = _.map(
    _.filter(this.props.policies, (policy) => policy && policy.type === CONST.POLICY.TYPE.FREE),
    (policy) => ({label: Str.truncateInMiddle(policy.name, 35), key: policy.id, value: policy.id}),
);
```
<img width="1167" alt="Screenshot 2023-06-08 at 2 06 39 AM" src="https://github.com/Expensify/App/assets/78416198/820652b6-e660-45dd-b5e4-2b4bce10ffa6">

## Solution 2
- The updated code will shorten the text from the end and append a trail text at the end.

```
const workspaceOptions = _.map(
    _.filter(this.props.policies, (policy) => policy && policy.type === CONST.POLICY.TYPE.FREE),
    (policy) => ({label: Str.shortenText(policy.name, 35), key: policy.id, value: policy.id}),
);
```
<img width="1165" alt="Screenshot 2023-06-08 at 2 06 15 AM" src="https://github.com/Expensify/App/assets/78416198/8b768c12-d8a6-4f9b-b5ab-3f5bd9ee0c1c">

**Comment by MitchExpensify** [comment]
> How do i get access to New Room button

The New room button should exist on Dev as its just behaind a beta and dev is on all betas by default right @techievivek ?

**Comment by techievivek** [comment]
> The New room button should exist on Dev as its just behaind a beta and dev is on all betas by default right

I think since they talk to PROD directly they won't have access to the betas so they would either need to be given access to these betas or tweak their code https://expensify.slack.com/archives/C01GTK53T8Q/p1685991363179939?thread_ts=1685989204.769519&cid=C01GTK53T8Q

**Comment by situchan** [comment]
> How do I get access to `New Room` button. As accessing it using code is a lot of debugging as i have to comment a lot of code.

https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/libs/Permissions.js#L77-L79

No need to comment lots of code. Only one line change should be enough for testing policy rooms:
```diff
-   return _.contains(betas, CONST.BETAS.POLICY_ROOMS) || _.contains(betas, CONST.BETAS.ALL);
+   return true;
```

**Comment by abdulrahuman5196** [comment]
Will review proposals today

**Comment by jeet-dhandha** [comment]
@abdulrahuman5196 You are correct  👍  we don't even need to fix this. We can close this.
