### ISSUE TITLE
[HOLD for payment 2023-06-19] [HOLD for payment 2023-06-15] Creating a new room with public mode freezes on the screen when pasted the URL

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Go to staging dot on web chrome
2. Create a new workspace and create a room with public mode
3. Click on room header and click on share code and copy the URL
4. Now open a new window and first make sure that on that window, you're are logged out of all the staging and new Expensify accounts
5. Paste the link on a new tab and notice that the screen freezes on that point. I remember, it used to show the chat room and used to ask users to sign in previously. But now, it is stuck at the same point. Since it's a public room, it should have shown the chat room or anything.

## Expected Result:

Creating a new room with public mode should either show the chat room on the screen when pasting the URL or if not, then it should show an error

## Actual Result:

Creating a new room with public mode freezes on the screen when pasted the URL
Platforms: web chrome

## Workaround:

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686141356348729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b6fd77a212706c7</li>
        <li>Upwork Job ID: 1666432124500230144</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@mountiny no payment or regression test needed here?

**Comment by mountiny** [comment]
Lets handle payments for the other 2 issues fixed in this PR here, all are only for bug reports so:
- $250 for https://github.com/Expensify/App/issues/20358 to @adeel0202 
- $250 for https://github.com/Expensify/App/issues/20357 to @Puneet-here 
- $250 for this issue to @priya-zha


No regression checklist required here, this is coming from major refactor

**Comment by jliexpensify** [comment]
Invites sent @Puneet-here , @priya-zha and @adeel0202

**Comment by mountiny** [comment]
No checklist required here, new feature essentially

**Comment by Puneet-here** [comment]
> Invites sent @Puneet-here , @priya-zha and @adeel0202

I have applied to the job @jliexpensify

**Comment by jliexpensify** [comment]
Everyone hired, once accepted I'll pay and close this!

**Comment by jliexpensify** [comment]
Paid Priya and Adeel, waiting on @Puneet-here !

**Comment by Puneet-here** [comment]
@jliexpensify, I have accepted the offer now.

**Comment by jliexpensify** [comment]
Paid, and job removed!
