### ISSUE TITLE
Settings - A deep link to authenticated page navigated you to LHN but not page Settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executting PR** https://github.com/Expensify/App/pull/19263

## Action Performed:
1. In another app write a link to Settings page: https://staging.new.expensify.com/settings
2. Be signed out on the testing device
3. Click on the link
4. Verify you have been navigated to the sign in flow
5. Sign in

## Expected Result:
You have been correctly navigated to the Settings page after signing in

## Actual Result:
You navigated to LHN page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/18022ac1-5a1e-4f57-b985-7af74d4fe752

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Hmm, I cannot repro this on Pixel 3a (v1.3.26-1). I am taken to the Settings page on staging.

Please re-open with new video on the latest version if you can repro @mvtglobally
