### ISSUE TITLE
Dev: Editing comment is not working

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Launch desktop app
2 Open any chat
3 Edit any comment

## Expected Result:
Editing comment is working

## Actual Result:
Editing comment is not working

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/36857dc0-99ac-45fb-9c81-e8070109bcbe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685787149904509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by narzullome** [comment]
ok will try

**Comment by JmillsExpensify** [comment]
I'm going to close. I'm not able to reproduce.

**Comment by narzullome** [comment]
@JmillsExpensify did u checked on dev?

**Comment by narzullome** [comment]
On dev I am still able to  reproduce
