### ISSUE TITLE
Settings - there is no emoji picker in welcome message input like normal message in chat composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and create new room.
2. Open room details.
3. Navigate to Setting then to Welcome message.

## Expected Result:
User should see emoji picker in welcome message input like normal message in chat composer.

## Actual Result:
There is no emoji picker in welcome message input like normal message in chat composer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.25.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @ahmedGaber93

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685845548060519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
I voted to create this issue in slack but thinking about this more I feel like we should close this feature request. Adding an emoji picker wouldn't be consistent with any of our other flows - none of our other push to page inputs have emoji pickers but curious for other thoughts

**Comment by sophiepintoraetz** [comment]
Agreed! Closing for now but we can reopen if there's strong sentiment for it.
