### ISSUE TITLE
Web - Login - Here is your magic code page is displayed instead of 2FA required page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open a new INCOGNITO window and navigate to the staging link
4. Verify the 2FA required page is displayed. Should have a message similar to "Please enter the two-factor authentication code where you are trying to sign in."

## Expected Result:
2FA required page should be displayed. Should have a message similar to "Please enter the two-factor authentication code where you are trying to sign in."

## Actual Result:
Here is your magic code page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d00641fe-9f42-4891-9470-453c88c2ecb7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
[Posted](https://expensify.slack.com/archives/C9YU7BX5M/p1686178884184679?thread_ts=1686084086.585489&cid=C9YU7BX5M) in an internal channel about this but I believe the steps should be as follows: 

1. Enter login in new Expensify and press Continue, triggering a magic link notification
2. Open the magic code link in an INCOGNITO window
3. Confirm you see the Here is your magic code view on the magic link tab
4. Navigate back to the tab you began signing in on and manually enter the magic code
5. Confirm you are shown view to enter your authenticator code
6. Refresh the page and confirm you see the Two-factor authentication required view on the magic link tab
7. Navigate back to the tab you began signing in on
8. Enter your 2FA code and confirm you’re signed in successfully

**Comment by alex-mechler** [comment]
@kbecciv can you retest with the steps that Nikki posted?

**Comment by NikkiWines** [comment]
@kbecciv could you test on staging + prod and see if we get the same behavior (and if the test is still failing) using [these](https://github.com/Expensify/App/issues/20411#issuecomment-1581621426) updated steps please? Thank you very much!! 🙇

**Comment by mountiny** [comment]
I have retested it with the steps from Nikki and I could not reproduce the issue
https://github.com/Expensify/App/assets/36083550/cb0f8d13-d35a-4a93-b544-8124644840bc

**Comment by mountiny** [comment]
I am not sure if this is a blocker or issue even after all

**Comment by mountiny** [comment]
Asking QA to fact check
