### ISSUE TITLE
[HOLD for payment 2023-06-28] [HOLD for payment 2023-06-23] [$1000] IOS - Log in- New user is not navigating to Concierge chat after tap on link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot
2. Navigate to https://staging.new.expensify.com/concierge
3. Sign-up with a new account

## Expected Result:
New user is navigating to Concierge chat after tap on link

## Actual Result:
New user is not navigating to Concierge chat after tap on link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/3490982

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/592bb62b-7bdf-4793-9c03-118faf2dfda2

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158ff64059880717e</li>
        <li>Upwork Job ID: 1666582636407345152</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by mountiny** [comment]
While this is a bug most likely related to the navigation refactor I dont think its a deploy blocker as it only happens with a specific deeplink and on a specific platform. I will ask @koko57 to look at this one since she has experience in this area

**Comment by MitchExpensify** [comment]
Upwork offers sent to @thesahindia and @tienifr for eventual Upwork payment

**Comment by mountiny** [comment]
Thanks for raising

**Comment by MitchExpensify** [comment]
Yes, thanks @tienifr !

**Comment by MitchExpensify** [comment]
Set a reminder to pay in my calednar!

**Comment by MitchExpensify** [comment]
Not overdue - Payment coming tomorrow

**Comment by MitchExpensify** [comment]
Paid @tienifr with bonus 🎉 

Once you accept @thesahindia I'll pay out and close this up 👍

**Comment by MitchExpensify** [comment]
Thanks @thesahindia, Upwork is acting strangely and I don't see the acceptance reflecting there. I've invited you here instead! Sorry about that. https://www.upwork.com/ab/applicants/1676296241268867072/suggested

**Comment by MitchExpensify** [comment]
Wooh, that worked! Paid
