### ISSUE TITLE
App allows to add contact to which we already have communicated before as secondary user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open search
3. Search for new user and send any message to it
4. Open settings
5. Open profile
6. Open contact method
7. Click on 'New contact method'
8. Add the same contact to which you had sent a message in step 3
9. Again add new contact using step 4-7
10. Again open search and search the newly added contact in step 9 and observe that it provides no result found error
## Expected Result: 
App should not allow to add contact to which we already had communicated before like it does not allow to start communication with contact which we have added in contact method
## Actual Result: 
App allows to add contact to which we already had commincated before.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8836f70b-226b-4944-8b50-9f8ab1ee40cb

https://github.com/Expensify/App/assets/43996225/b7c25aab-e915-4478-a118-e11eb7c5f6e6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685889599794029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
I was taking a look at something similar, so I'll investigate this tomorrow!

**Comment by trjExpensify** [comment]
Neat, thanks!

**Comment by trjExpensify** [comment]
@Gonals how'd that investigating go?

**Comment by trjExpensify** [comment]
PRs are in review, Melv. Chill...

**Comment by Gonals** [comment]
One pR merged, one in review!

**Comment by trjExpensify** [comment]
👋 @Gonals, can you confirm both of the PRs for this issue were backend and so the only payout applicable here is for the bug report?

**Comment by Gonals** [comment]
Yep, that's correct!

**Comment by trjExpensify** [comment]
Cool, thanks. An offer has been sent to @dhanashree-sawant for $250.

**Comment by dhanashree-sawant** [comment]
Thanks @trjExpensify, I have accepted the offer, I think you have mistakenly added the title of #21826 on upwork job 😅

**Comment by trjExpensify** [comment]
Ah, you see.. that's what happens when you're so good at reporting loads of bugs! 😉 

Settled up, thanks!
