### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Security - Inconsistent behaviour observed for “copy” in 2FA step 1 and 2.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "Settings" section.
2.  Click the "Security" option.
3. Select the "Two-factor authentication" feature.
4. Notice that in all other pages on clicking “copy” icon, it changes to “copied”, but here only tick appears.

## Expected Result:
The button should convert from “copy + tick” to “copied + tick sign” on click, in the absence of tooltip.

## Actual Result:
The button don’t convert from “copy + tick” to “copied + tick sign” on click, in the absence of tooltip.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e187d6ee-4718-41b9-992d-1bc60913ffdc

https://github.com/Expensify/App/assets/93399543/53bb9fab-9380-46d7-aa14-4374d1f1d806

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96
 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686035501767859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f744e207f5b11a8f</li>
        <li>Upwork Job ID: 1668426697120395264</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
Not overdue

**Comment by alitoshmatov** [comment]
Applied to the job, PR will be ready in couple of hours

**Comment by alitoshmatov** [comment]
PR is ready - https://github.com/Expensify/App/pull/20889

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
[@abdulrahuman5196] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
[@abdulrahuman5196] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. But a miss during original implementation.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. It is a minor case and wouldn't be beneficial to add regression test for this.

**Comment by alitoshmatov** [comment]
We can proceed with this one

**Comment by muttmuure** [comment]
Nice

Offer sent to @alitoshmatov

**Comment by muttmuure** [comment]
@abdulrahuman5196 invite sent

**Comment by abdulrahuman5196** [comment]
@muttmuure sent a proposal on the invite

**Comment by alitoshmatov** [comment]
@muttmuure Would be great if you could complete the payment till the end of the week

**Comment by usmantariq96** [comment]
@muttmuure haven't received any offer yet.

**Comment by muttmuure** [comment]
@usmantariq96 invited!

**Comment by muttmuure** [comment]
Contracts ended for @alitoshmatov and @abdulrahuman5196 

Invite sent to @usmantariq96

**Comment by usmantariq96** [comment]
@muttmuure I think invite is of $1000 while bug bounty is required to be $250.

So can you please share invite via message in Upwork.

**Comment by alitoshmatov** [comment]
@muttmuure I think urgency bonus also applies [here](https://github.com/Expensify/App/issues/20457#issuecomment-1595859615), and I didn't receive it.

**Comment by abdulrahuman5196** [comment]
> @muttmuure I think urgency bonus also applies [here](https://github.com/Expensify/App/issues/20457#issuecomment-1595859615), and I didn't receive it.

Same here @muttmuure

**Comment by usmantariq96** [comment]
@muttmuure thanks I managed to apply with $250.

Thanks

**Comment by abdulrahuman5196** [comment]
Gentle ping on this @muttmuure

**Comment by muttmuure** [comment]
urgency bonuses given to @abdulrahuman5196 and @alitoshmatov 

invite to job sent to @usmantariq96

**Comment by usmantariq96** [comment]
@muttmuure  accepted.

**Comment by muttmuure** [comment]
@usmantariq96 paid. 

Closing out
