### ISSUE TITLE
[HOLD for payment 2023-06-21] [HOLD for payment 2023-06-19] Previewing Concierge shows different image in compared to group chat and search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Search for Concierge and notice that on search, the Concierge is displayed in green color avatar
3. Click on it so that the chat page appears. Click on the Concierge image to preview it and notice that on preview it appears a blue image
4. Even in a group chat, it appears as green avatar but if you try to preview it, it appears as a blue image
## Expected Result: 
Image should be consistent everywhere
## Actual Result: 
Previewing Concierge shows different image in compared to group chat and search
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0e8d8ce1-29af-4a71-814a-42dc5442eb5f

https://github.com/Expensify/App/assets/43996225/c2fce5da-d1b0-490b-8f35-b3d40a91c421

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686250700849029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I can reproduce on staging web

**Comment by AndrewGable** [comment]
Coming from https://staging.expensify.com/api?command=OpenPublicProfilePage

https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png

**Comment by Beamanator** [comment]
PR that created that command: https://github.com/Expensify/Web-Expensify/pull/37712

**Comment by AndrewGable** [comment]
Somehow we need to update Concierge's avatar to this image: https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2022.png

@puneetlath I think it came from your PR: https://github.com/Expensify/App/pull/20144

**Comment by Beamanator** [comment]
I'll help investigate for @puneetlath 👍

**Comment by AndrewGable** [comment]
I think I have access to log into concierge@ in Expensify.com, I could just try setting the avatar in the UI? But I do think this will change the avatar for a lot of different UI elements I might think?

**Comment by Beamanator** [comment]
Hmm that could work but ya I think we hardcode the concierge avatar in App in a lot of places

**Comment by Beamanator** [comment]
one example: https://github.com/Expensify/App/blob/38ba7c8eb29a43552980b09dcdde46ccded35c7e/src/libs/OptionsListUtils.js#L189-L191

**Comment by Beamanator** [comment]
So I think we should either hardcode the concierge avatar everywhere in App, or update Concierge's avatar like you said :D

**Comment by Beamanator** [comment]
Discussing in slack: https://expensify.slack.com/archives/C03TQ48KC/p1686253332687619

**Comment by AndrewGable** [comment]
Sounds like we are preferring to hard code this, I'll look into where is the best to do so

**Comment by AndrewGable** [comment]
CP-ed, removing label

**Comment by avi-shek-jha** [comment]
@AndrewGable Is this new issue regression from this current issue https://expensify.slack.com/archives/C049HHMV9SM/p1686637757270519

**Comment by AndrewGable** [comment]
I fixed this

**Comment by priya-zha** [comment]
@AndrewGable I'm the external reporter for this issue.

**Comment by AndrewGable** [comment]
@sonialiap - Can you please pay @priya-zha the reporting bonus? Thank you

**Comment by sonialiap** [comment]
@priya-zha offer sent

Reopening so that I can keep track of this issue

**Comment by priya-zha** [comment]
@sonialiap Accepted. Thanks.

**Comment by sonialiap** [comment]
Paid ✅
