### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Return the error key rather than the translated string in all forms

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#20472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Description
This is a follow-up to the previous changes made in PR https://github.com/Expensify/App/pull/19324 and PR https://github.com/Expensify/App/pull/20093. While those PRs introduced initial updates to improve error handling by implementing key-based error storage, it was identified that there are still remaining form validation methods that require updates to align with the new mechanism.

The purpose of this follow-up PR is to comprehensively cover all form validation methods and ensure they return the error key rather than the translated string. By doing so, we aim to achieve consistent and streamlined error handling across the entire application, eliminating any remnants of the old translation-based approach.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b859b012a0a1a383</li>
        <li>Upwork Job ID: 1666851678591188992</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
PR is here https://github.com/Expensify/App/pull/20228

**Comment by abekkala** [comment]
@0xmiroslav yes, the speed bonus will still apply - pending no regressions.

**Comment by abekkala** [comment]
### Payments to be made on Jun 23:

- Issue reported by: N/A
- Selected Proposal for fix: @fedirjh [$1000] + [$500 PR bonus]
- C+ Review: @0xmiroslav [$1000] + [$500 PR bonus]

**Comment by abekkala** [comment]
@0xmiroslav can you complete the BugZero checklist above?

**Comment by abekkala** [comment]
@fedirjh and @0xmiroslav Contract offers were sent!

**Comment by abekkala** [comment]
@0xmiroslav payment sent and contract ended - Thank You! 🎉

**Comment by abekkala** [comment]
Closing - thank you!
