### ISSUE TITLE
Change the sender of the policy log when adding an team.expensify.com or expensify.com email as an admin

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#20485]
**Problem:** As discussed [here](https://expensify.slack.com/archives/C03U7DCU4/p1686261747523209), we add a new policy log when we automatically add someone from expensify as an admin to the policy for support purposes.
<img width="776" alt="image" src="https://github.com/Expensify/App/assets/22508290/7502fe9a-e01d-4cd6-8f3a-3235f8b8f4b9">

This is not ideal and degrades trust in our logs, because the admin didn't actually add the user. We did this on their behalf

**Solution:** Remove this policy log message altogether, as it is a technicality, and expensify.com users are not shown in the People table anyways. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by spcheema** [comment]
@kevinksullivan @pecanoro This can be easily controlled from backend message.

**Comment by pecanoro** [comment]
> we add a new policy log when we automatically add someone from Expensify as an admin to the policy for support purposes.

@kevinksullivan How are these admins added? I can't fix it if I don't know how these ged added, I am missing context here.

**Comment by pecanoro** [comment]
> It seems we have the policy owner "add" in the assigned guide, and in certain scenarios, the Guide's mentor. We do this from the policy owner's account, but they are not actually taking the action themselves.

@kevinksullivan How are these added? While being support logged into the account?

**Comment by pecanoro** [comment]
@kevinksullivan Ohh one sec, I think I understand now, so no matter how we add the guide/mentor, we want to show it's coming from Concierge, right? Only for guides and not any other user?

**Comment by kevinksullivan** [comment]
Sorry @pecanoro like I said I updated the OP, so all we want to do is stop sending this message altogether. So we don't want to show a message whenever we are adding a team.expensify.com / expensify.com email on behalf of the customer.

**Comment by pecanoro** [comment]
@kevinksullivan One last question, if I remove the log completely for the `expensify.com` domain, these will stop showing on our policies too, should I check that the policy is not part of our domain so our own workspaces still log this?

**Comment by kevinksullivan** [comment]
ah yes that is a great catch @pecanoro . We don't want this to affect our own use of the product. Only when we're doing this on behalf of other companies for support purposes.

**Comment by pecanoro** [comment]
PR is ready but I need to test it on Monday.

**Comment by pecanoro** [comment]
Not overdue Melvin! Almost done!

**Comment by pecanoro** [comment]
It was already deployed, it seems automation didn't happen, so closing!
