### ISSUE TITLE
[$1000] App displays 'settled up elsewhere' for a moment in  LHN even if there are new messages after it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in any other device or incognito and login with user B
3. From user B, request any amount to user A
4. From user B, send new messages to user A
5. From user A, pay the amount and observe in LHN that it displays 'settled up elsewhere' message
6. Revisit user B chat to observe that app now again displays the latest message from user B in LHN
## Expected Result: 
App should display latest message in LHN
## Actual Result: 
App displays 'settled up elsewhere' message for sometime even though there are new messages after the request amount.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d871125e-0102-4882-bfa7-0f59bef2e435

https://github.com/Expensify/App/assets/43996225/b4268222-9816-4da3-990e-bbe7b6bbda02

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685957476576119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0110bfc1548b5e4</li>
        <li>Upwork Job ID: 1668730898725675008</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by arielgreen** [comment]
pushing this external

**Comment by arielgreen** [comment]
@eVoloshchak please see proposal from @dukenv0307 above

**Comment by arielgreen** [comment]
Reassigning, team change

**Comment by eVoloshchak** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/20489#issuecomment-1583768261) looks good to me!
> We always set lastMessageText and lastMessageHtml to IOU action message without checking whether this is the last action in the main DM or not. That makes the IOU message display in LHN for a second before API returns data

🎀👀🎀 C+ reviewed!
cc: @bondydaa

**Comment by eVoloshchak** [comment]
Not overdue, waiting for @bondydaa's opinion on the [above](https://github.com/Expensify/App/issues/20489#issuecomment-1594926840)

**Comment by jliexpensify** [comment]
Bumped Bondy via DM

**Comment by bondydaa** [comment]
sorry for the delay here, was focused all week on getting deploys out.

I don't actually think there is really a bug here. 

In the video, `hello` and `test` are sent before the `I'll settle up elsewhere` so the IOU settle action happens after those messages and _should_ show as the most recent action.

If a new message is sent after someone clicks "I'll settle up elsewhere" and it isn't shown in the LNH then I think that is a bug but as described I do not think we should change this.
