### ISSUE TITLE
Workspace - RHN reloads when navigating to a Workspace without access 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a workspace link that you don't have access (e.g https://staging.new.expensify.com/workspace/964B74C2A7737B2C)

## Expected Result:
The RHN modal should display the "Hmm it's not here.." page. 

## Actual Result:
The RHN modal reloads after navigating to the lnk 
The "Hmm it's not here.." page is shown briefly, then a loading spinner for a moment then the "Hmm it's not here page.." again.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.26-1 

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/44479856/07835d34-d6c3-47f5-a333-0fd00afa02f1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Found while executing PR https://github.com/Expensify/App/pull/20360 - It's not related or caused by it since this issue is reproducible in prod.

**Comment by maddylewis** [comment]
@hungvu193 - based on this latest reproduction attempt, does it seem like this is still an issue? or, is there a separate fix in the works that's fully resolved this?

**Comment by maddylewis** [comment]
okay going off of this comment, im going to close this one out for now - https://github.com/Expensify/App/issues/20490#issuecomment-1583948588
