### ISSUE TITLE
[$1000]  Assign task - Error in console when open staging.new.expensify.com/new/task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19879

## Action Performed:
Precondition: Login with an account that has the beta permission for tasks
1. Open http://staging.new.expensify.com/
2. Open URL http://staging.new.expensify.com/new/task

## Expected Result:
There are no errors in JS console when opening http://staging.new.expensify.com/new/task

## Actual Result:
There are errors in JS console when opening http://staging.new.expensify.com/new/task:

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6086758_Screenshot_2023-06-09_at_18 05 14" src="https://github.com/Expensify/App/assets/78819774/3aeed40a-10fc-4551-b27b-48fa5da5db20">

https://github.com/Expensify/App/assets/78819774/877ddadc-5191-4917-91aa-46769713aaf3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b1acd5f94dd9de9</li>
        <li>Upwork Job ID: 1667201383416217600</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Reviewing

**Comment by greg-schroeder** [comment]
![image](https://github.com/Expensify/App/assets/29386373/e0c9b1b0-4093-493f-9410-570d06249204)

**Comment by greg-schroeder** [comment]
Hey @iwiznia maybe you can help me out. So this is a console error that comes up when going to the new task URL, even though the operation seems to load. This is behind the `tasks` beta. 

I'm not super familiar triaging console bugs that are behind a beta... do you know if this something an contributor can work on or should it be internal?

**Comment by thienlnam** [comment]
Doesn't seem like this is specific to tasks, I can see the error just on http://staging.new.expensify.com/

<img width="1512" alt="Screenshot 2023-06-09 at 12 38 13 PM" src="https://github.com/Expensify/App/assets/30609178/60302b48-77be-40ed-992d-e83855541820">

**Comment by greg-schroeder** [comment]
Okay, word! I'm happy to close if that's the case. Again, the operation itself seems to work
