### ISSUE TITLE
Web - New Room - Entered name cleared when changing the size of the window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20529]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to any Expensifail account
3. Click on FAB button -> New room
4. Enter some symbols on the Room name input field
5. Change the window size

## Expected Result:
Entered name NOT cleared

## Actual Result:
Entered name cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aaeb5a5d-3a0b-433b-8a0b-27d3e4dce3d7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
Related to https://github.com/Expensify/App/issues/20404.

**Comment by michaelhaxhiu** [comment]
100% agree

**Comment by michaelhaxhiu** [comment]
closing, i think it's 1 in the same
