### ISSUE TITLE
[HOLD for payment 2023-06-21] Make Form's validate prop optional

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#20525]
# Problem
Coming from [this comment](https://github.com/Expensify/App/pull/16919#issuecomment-1583860034), we have a few optional fields that don't need a validate function in Form. Instead of requiring the prop and passing an empty function, we should just make the prop not required and add a default to it.

# Why is this important
Keeps code clean

# Solution
Make the prop optional
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107197fe609fa957e</li>
        <li>Upwork Job ID: 1667193645315923968</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
@thesahindia please complete the checklist and I'll issue payment 😊

**Comment by sonialiap** [comment]
Paid ✅
