### ISSUE TITLE
Chat - "Unable to load pdf file"  notification is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19946

## Action Performed:
1. Go to expensify web and login with User A
2. Go to any chat with User B (Make sure to login with User B on android earlier)
3. From User A account, send two attachments in the order: First send the password protected pdf file and then send any image
4. Very important step- On Android (User B), first select the last attachment (image) and click on left arrow key to navigate to the password-protected pdf (do not slide using fingers). Note: Also, it's important to navigate from different attachments, as we're doing here, then only it will be reproducible
5. From User's A account on web, now delete the pdf file
6. Go to Android(User B) and now click `Enter the password` 

## Expected Result:
'Unable to load pdf file' should be displayed when user try to open the PDF after being deleted by user B

## Actual Result:
The navigation preview is asking to enter the password when the file is already deleted. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e7cdd08e-3385-4762-8f21-a4c21d212a23

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
This one is going to take some time and isn't something that's going to be happening regularly, will get back to once caught with other overdue issues, eeps

**Comment by mallenexpensify** [comment]
Testing for SNH, so this isn't the highest priority :/

**Comment by mallenexpensify** [comment]
Unable to reproduce and the steps are pretty convoluted, going to close

https://github.com/Expensify/App/assets/22508304/82918c10-2473-4c59-b52c-aabdd44877a2
