### ISSUE TITLE
[$1000] Payment issue for #18518 (issuing missed bonuses)

### ISSUE THREAD

**Issue by johncschuster** [Expensify/App#20533]
Coming from https://github.com/Expensify/App/issues/18518, I issued payment but did not issue a bonus. This is strictly to issue a bonus for the contributor and C+ on that issue.

cc @HezekielT and @mananjadhav 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e86b6e2d6f1cac0b</li>
        <li>Upwork Job ID: 1667219929567346688</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
@mananjadhav and @HezekielT, I've invited you in Upwork to the job so I can issue the bonus payment for https://github.com/Expensify/App/issues/18518. Can you accept that invite and ping me when you get a moment?

**Comment by mananjadhav** [comment]
@johncschuster I haven't received the invite. Could you confirm if you sent the invite to my profile?

**Comment by johncschuster** [comment]
Ok! Bonuses have been issued! Thanks for your patience, everyone!
