### ISSUE TITLE
Web - Security - Button Overlaps on List in Two-Factor Authentication Section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app settings.
2. Navigate to the Security section.
3. Select Two-Factor Authentication.
4. Scroll down to the bottom of the section and observe the button overlapping on the list.

## Expected Result:
The button should not overlap on the list in the Two-Factor Authentication section.

## Actual Result:
The Copy codes and Download button are overlapping on the list in the Two-Factor Authentication section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (62)](https://github.com/Expensify/App/assets/93399543/9392269b-1896-447b-82db-d23a97b144a3)

[screen-capture (59).webm](https://github.com/Expensify/App/assets/93399543/1c12a7b2-13ab-4aa8-959a-2edd498536ed)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685785949859089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tewodrosGirmaA** [comment]
Hi @dhairyasenjaliya, I believe the first bug(#20138) report is specific to the iOS app and occurs when the language is changed from English to Spanish. However, the second bug report pertains to the web app and describes a button overlapping issue in the Two-Factor Authentication section on desktop Chrome platform. What are your thoughts on this?

**Comment by tewodrosGirmaA** [comment]
and also In the first bug report, the list was displayed in two columns, while in the second report, the list was displayed in one column and the button overlapped

**Comment by maddylewis** [comment]
im having a hard time reproducing this, and am also trying to double-confirm this isn't a duplicate. i will have next steps lined out by tomorrow.

**Comment by maddylewis** [comment]
it looks like there is a broader fix for this being worked on over here - https://github.com/Expensify/App/issues/20138
