### ISSUE TITLE
[HOLD for payment 2023-06-21] [Regression] Web - Task -User is not able to remove the description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + button
2. Click on Assign task
3. Enter title and description
4. Press next button
5. Click on Assignee and select any assignee
6. Click on confirm task button
7. Go to task thread
8. Click on description
9. Remove description and click on save button

## Expected Result:
Should remove description because it is optional

## Actual Result:
User is not able to remove the description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/40a5b1d9-b1a0-40dd-8694-2480f132127a

https://github.com/Expensify/App/assets/93399543/6ab209db-49a3-4306-9549-ed67cb489618

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686034899013369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d991a6eac7b405e1</li>
        <li>Upwork Job ID: 1668428386254053376</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Ah yup that's the one - thanks
Assigning you and fedirjh to handle this regression

**Comment by thienlnam** [comment]
This is a regression - no payments are due here @kevinksullivan

**Comment by kevinksullivan** [comment]
Sorry for the confusion everyone. Taking down the job post now.

**Comment by kevinksullivan** [comment]
Paid @gadhiyamanan , closing out
