### ISSUE TITLE
[$1000] Can't select text in pdf on native

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20540]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on +
3. Click on add attachment (like this one 
[giving authority to non-Director to sign.pdf](https://github.com/Expensify/App/files/11726587/giving.authority.to.non-Director.to.sign.pdf))
4. Choose a pdf file and send
5. Open the pdf
6. Try selecting the text by long pressing
## Expected Result: 
You should be able to select the text
## Actual Result: 
You can't select the text
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13064cda-a3c4-4db5-bd07-3080226d5cc7

https://github.com/Expensify/App/assets/43996225/5cc4dbbb-dc52-4b21-a0ae-d0b098fef680

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685992095138179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c20748023610bd0</li>
        <li>Upwork Job ID: 1668316421829435392</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
[This is not supported](https://github.com/wonday/react-native-pdf/issues/459) by our dependency, `react-native-pdf`. I can probably be contributed to the upstream, but likely won't be trivial.

**Comment by Christinadobrzyn** [comment]
Ah thanks! Closed the Upwork job
