### ISSUE TITLE
Task description is empty briefly after updating task title

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a assign task with title and description are not empty
2. Edit title of the task
3. Notice the description field in task header
## Expected Result:
Task description shouldn't be changed after updating task title
## Actual Result: 
Task description is empty briefly after updating task title
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 06-06-2023 09_56_24.webm](https://github.com/Expensify/App/assets/43996225/a6ddd756-b533-452f-833f-13b45ae63680)

https://github.com/Expensify/App/assets/43996225/9eaee4b5-71b6-4b34-84f5-3db3b34a4e54

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686020401378739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task description is empty briefly after updating task title
### What is the root cause of that problem?
When updating task title, we call `editTaskAndNavigate` with `description` param is empty
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/pages/tasks/TaskTitlePage.js#L63
And  in `editTaskAndNavigate` function, we update `description` of optimistictData of taskReport with `description` params in here
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/actions/Task.js#L328
So that description is empty until API edit task return data.
### What changes do you think we should make in order to solve the problem?
We sould update `description` of optimisticData of taskReport by the same way we pass description field in here when we call API
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/actions/Task.js#L383
### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment]
Ok, closing this out now as a regression that's already being fixed!
