### ISSUE TITLE
[$2000] Dev: IOS - Chat - Console error on dismiss keyboard without sending message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20552]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on return button for multiples empty line
3. Dismiss the keyboard on click on outside

## Expected Result:
Console error should not show

## Actual Result:
Getting console error on dismiss the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9978241c-5a82-4541-9251-8b5d9345da25

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686059495976739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4b6a6d4dee21067</li>
        <li>Upwork Job ID: 1668483496244523008</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I'm not able to reproduce as I don't have a mobile dev environment with access to the console. @AndrewGable or @sobitneupane are either of you able to reproduce the bug?

Also, if there is a way for me to reproduce the console error on staging or prod, please let me know :)

**Comment by spcheema** [comment]
.

**Comment by spcheema** [comment]
@sobitneupane Actually event is sent once but it occurs when a user press multiple return to simultaneouly.

**Comment by bernhardoj** [comment]
I think @allroundexperts is implementing reanimated into the suggestion component.

**Comment by sobitneupane** [comment]
@allroundexperts Can you please take a look and confirm if you are working on the transition to `react-native-reanimated` on `ReportActionCompose`.

**Comment by DJStartupAgile** [comment]
@allroundexperts 
The warning message you’re seeing seems to be related to a layout animation in React Native. Layout animations can sometimes cause unexpected behavior when they conflict with certain native components, like the keyboard.  In your case, it appears that a layout animation is being triggered at the same time as the keyboard is being dismissed. This could lead to an unstable state and hence the warning message.  To avoid this, you might want to delay the start of the animation until after the keyboard has been fully dismissed. You can use the Keyboard module’s addListener method to listen for the 'keyboardDidHide' event and then start the animation. This way, you ensure the keyboard has fully dismissed before starting the animation, which should prevent the warning

**Comment by DJStartupAgile** [comment]
Contributor details
Your Expensify account email: kayomelese4@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01393ae9100dff9b33

**Comment by DJStartupAgile** [comment]
Contributor details
Your Expensify account email: kayomelese4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/kayowakmelese

**Comment by sobitneupane** [comment]
@allroundexperts Can you please link the issue? So, the issue you are talking about doesn't make change in `ReportActionCompose`?

**Comment by sobitneupane** [comment]
I agree with @tienifr that `LayoutAnimation.configureNext` is no longer required. It was first added in https://github.com/Expensify/App/pull/14686 to animate emoji suggestions which was later moved to current place by https://github.com/Expensify/App/pull/18842 . And it is no longer required since animation is added in `AutoCompleteSuggestion` by https://github.com/Expensify/App/pull/19933.

[Proposal](https://github.com/Expensify/App/issues/20552#issuecomment-1588962291) from @tienifr looks good to me.
🎀👀🎀 C+ reviewed
cc: @AndrewGable

**Comment by tjferriss** [comment]
@AndrewGable are you good with @tienifr proposal?

**Comment by AndrewGable** [comment]
Assigned!

**Comment by sobitneupane** [comment]
@tienifr Any update?

**Comment by sobitneupane** [comment]
@tienifr Can you please post a update here? I think we should open it again for proposal which solves the issue completely.

**Comment by sobitneupane** [comment]
PR raised by @tienifr was unable to handle the issue completely. So, I guess we should reopen the issue for proposals.

cc: @tjferriss @AndrewGable

**Comment by AndrewGable** [comment]
Reopened for new proposals.

**Comment by sobitneupane** [comment]
Waiting for proposals

**Comment by tjferriss** [comment]
@AndrewGable what do you think about doubling the price as this has been ongoing for some time?

**Comment by AndrewGable** [comment]
Sure 👍

**Comment by tjferriss** [comment]
Sorry for the delay. Price has been doubled.

**Comment by DJStartupAgile** [comment]
How do I apply for these contract jobs?

Thank you!
DJ Scott, Technical Product Lead

**Comment by AndrewGable** [comment]
We already doubled, we can wait for a proposal

**Comment by tjferriss** [comment]
@DJStartupAgile take a look at our [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). If you have a proposal for the issue you can submit it as a comment using [this template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

**Comment by tjferriss** [comment]
We're still waiting on proposals to come in

**Comment by AndrewGable** [comment]
@sobitneupane - Any proposals look good?

**Comment by tjferriss** [comment]
I'd like to get @sobitneupane review of the existing proposals before we increase the bounty.

**Comment by arthurmfgtab** [comment]
Hey, team, I'm Arthur from Callstack and I'd like to work on this ticket (if no proposals look good)

**Comment by sobitneupane** [comment]
Thanks for the proposal @ntdiary.

I am not very familiar with the `react-native-reanimated` repo. So, I might need some help to review the proposal. Looks like `react-native-reanimated` is maintained by software-mansion. @tjferriss Can we get someone from software-mansion to review [this proposal](https://github.com/Expensify/App/issues/20552#issuecomment-1675975230)?

**Comment by tjferriss** [comment]
I've asked for help in [#expensify-swm](https://expensify.slack.com/archives/C04878MDF34/p1692310169764269) channel.

**Comment by tjferriss** [comment]
Software Mansion is looking into the issue.

**Comment by tomekzaw** [comment]
Hey, Reanimated maintainer from Software Mansion 👋 

Thanks @ntdiary for your investigation (https://github.com/Expensify/App/issues/20552#issuecomment-1675975230) as well as submitting the proposal. I think this should resolve the underlying issue. I believe we can even go a step further and remove the cleanup block completely:
```objc
    // Clean up
    // below line serves as this one uiManager->_layoutAnimationGroup = nil;, because we don't have access to the
    // private field
    [uiManager setNextLayoutAnimationGroup:nil];
```
Here's the full story. In [#3332](https://github.com/software-mansion/react-native-reanimated/pull/3332/files) we rewrote the mechanism of Layout Animations and used `RCTLayoutAnimationGroup` to control the removal of exiting views (see [here](https://github.com/software-mansion/react-native-reanimated/blob/be4fd9f51df751d847f76f1acaa85465bab40a91/ios/LayoutReanimation/REAUIManager.mm#L56-L60)).

However, in [#3824](https://github.com/software-mansion/react-native-reanimated/pull/3824/files) we got rid of `[[RCTLayoutAnimation alloc] initWithDuration:0 config:@{}]` in favor of another approach. Looks like the cleanup block is no longer necessary.

I will consult this change with the author of the aforementioned PR and most likely submit a PR that removes the problematic call.

**Comment by AndrewGable** [comment]
Wonderful, thank you for the update @tomekzaw!

**Comment by tomekzaw** [comment]
Update: We came up with second fix, it looks like it works better but still sometimes the warning shows up. Working on it.

**Comment by tjferriss** [comment]
Thanks @tomekzaw. When do you expect to have a PR up?

**Comment by tomekzaw** [comment]
@tjferriss I wanted to test out the PR in the Expensify App but at this point I can't even reproduce the original issue on the main branch (53ac4eeed813b1ea355081622dad8a07e4a9539e).

**Comment by tjferriss** [comment]
Agreed. I'm no longer able to reproduce the issue on staging.

**Comment by AndrewGable** [comment]
Let's reopen if we see it again!

**Comment by tomekzaw** [comment]
> Eh, this issue only occurs in the dev environment.

I guess it also happens in the release environment -- it's just that the effect is not visible because `console.warn` in release mode is just a no-op.

> the steps in the OP can no longer be reproduced, but the steps in https://github.com/Expensify/App/pull/20888#pullrequestreview-1494472405 can still be reproduced

Okay, I will check out the other issue you've linked and try to reproduce the problem.

**Comment by tomekzaw** [comment]
@ntdiary Thanks for the response. For some reason, after I pulled the latest main, the default build variant was `Release Production`, that's why there was no warning 🤦 Sorry for the trouble, will look into this issue again.

**Comment by tomekzaw** [comment]
Bumping to 3.5.0 in #27193
