### ISSUE TITLE
Web -Sign in - Abracadabra page turns to Here is your magic code page after signing out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20216

## Action Performed:
1. Sign in to an account with 2fa disabled
2. Click on the magic link received in the email
3. Verify that the tab opened by the magic link displays the Abracadabra page
4. Go to previous tab and sign out
5. Go to tab with Abracadabra page

## Expected Result:
 It should stay Abracadabra page

## Actual Result:
Abracadabra page turns to Here is your magic code page after signing out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/24190c8e-ee69-47e5-a88f-69646eb79769

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
On production it is an issue with non-clickable login page instead of abracadabra page.

https://github.com/Expensify/App/assets/93399543/db749e5c-3e7f-4bb1-ab80-42d8c2338cc6

**Comment by NikkiWines** [comment]
I actually think this might be expected, as the behavior we'd expect to see if you had started a new session (e.g. if you just navigate to the `/v/137/000000` link in an incognito window) is that you'd see the `Here is your magic code` view 

@johnmlee101 curious if you agree

**Comment by johnmlee101** [comment]
Hmm the code on that page is now unusable right? Not sure if we should show a code we know is bad

**Comment by NikkiWines** [comment]
I don't believe we have a particular view that we show the user if their code is invalid.

**Comment by johnmlee101** [comment]
True about the incognito case, yeah we can ignore most likely.

**Comment by NikkiWines** [comment]
Closing this as we decided it wasn't a bug
