### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Settings - Zip/ Pin code validation is case sensitive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open Home address
6. Change country to 'Ascension Island'
7. Insert same format zip code but in lower case and observe that it throws validation error.

## Expected Result:
The Zip/ Pin code should be uppercased on the background without user noticing and then we can run the verification making the case sensitiveness irrelevant.

## Actual Result:
Zip/ Pin code validation is case sensitive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2777023f-6258-413c-a861-162e20d92cac

https://github.com/Expensify/App/assets/93399543/d1ccce92-f01a-465d-a8bd-77aca8db127d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686066243272029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebaa85cf62804d03</li>
        <li>Upwork Job ID: 1668213774703255552</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by eh2077** [comment]
It looks like country zip code is case sensitive and would like to tag @Prince-Mendiratta to confirm as you added the feature https://github.com/Expensify/App/issues/14958

**Comment by mountiny** [comment]
@Prince-Mendiratta Can you please confirm if the case sensitiveness has been intentional and any reason we should not make this case insensitive?

**Comment by mountiny** [comment]
Hmm I am not sure, I know in UK for example sometimes the websites complain if I dont use uppercase so maybe a bit more digging into this should be done. Or we can just simply enfore the uppercase and let users know. Or map it to uppercase as they write it in

**Comment by mountiny** [comment]
I am inclined to overwriting user to uppercase in this case.

**Comment by Beamanator** [comment]
@mountiny I thought we didn't prefer modifying user input as we typed? Example: we don't accept uppercase letters in contact methods, but instead of overwriting user input as they type, we lowercase the text before sending it to the API

**Comment by mountiny** [comment]
Updated the issue op

**Comment by abdulrahuman5196** [comment]
@dukenv0307 proposal here https://github.com/Expensify/App/issues/20569#issuecomment-1586308230 looks good since the expectation is to silently uppercase the zip code during validation and sending to API.

🎀👀🎀
C+ Reviewed

cc: @mountiny

**Comment by abdulrahuman5196** [comment]
Gentle ping on this @johncschuster

**Comment by sakluger** [comment]
Sorry everyone, @johncschuster is out for the week. I just sent offers through Upwork to @dhanashree-sawant, @dukenv0307, and @abdulrahuman5196.

**Comment by abdulrahuman5196** [comment]
@sakluger Thank you. Accepted the job invite.

**Comment by mountiny** [comment]
@dukenv0307 @abdulrahuman5196 and @dhanashree-sawant has this all been paid out?

If yes we can close this

**Comment by abdulrahuman5196** [comment]
@mountiny no. I have accepted the contract. But still waiting on payment release.

**Comment by mountiny** [comment]
Independence day, probably gonna be paid tomorrow, sorry for that

**Comment by abdulrahuman5196** [comment]
No problem. Thought so. Many people would be off this time of the year. 😅

**Comment by johncschuster** [comment]
Payment has been issued! Thanks for your patience, everyone!
