### ISSUE TITLE
Payments - Error message is missing after setting the only bank account as default

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20246

## Action Performed:
1. Log in to the account without the beta wallet
2. Go to Settings > Preferences > enable Use Staging Server
3. Add a new bank account:
- Wells Fargo
- Username: user_good
- password: pass_good
- Mobile verification code: credential_good
- Plaid saving
4. Go to Settings > Payments
5. Click your bank account and then click Make default payment method

## Expected Result:
Error message should be shown

## Actual Result:
Error message is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** N/A

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/815fb904-92c6-4aad-81ea-1dbc2da9eee4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is unable to verify this issue in production.

**Comment by marcochavezf** [comment]
Working on it, I tested locally with a gmail account (without the beta wallet), and the server responded with 200 (no error).

**Comment by marcochavezf** [comment]
Removing the label since if you only have one payment method, it should be set to default automatically. So we shouldn't show the "Make default payment method" in this case. More details [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686604403982479).

**Comment by marcochavezf** [comment]
Closing this one in favor of this [one](https://github.com/Expensify/App/issues/20629).
