### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Offline - Thread - Count reply does not update when completing or reopening a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Create a task
3. Tick checkbox complete task
4. Open the report action task see 1 reply
5. Open parent report see 1 reply under task

## Expected Result:
The number of replies must increase after changing the checkbox

## Actual Result:
Only after opening the report the number of replies increase

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d408a1ba-da84-4614-ab54-b6f60bf9d75a

https://github.com/Expensify/App/assets/93399543/465e36e2-f74e-41bf-92b9-4327d8333b61

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686105205074489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01090ab015f7de42e1</li>
        <li>Upwork Job ID: 1668226471256403968</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Yeah that's a good idea, we will likely also need to do that

**Comment by MariaHCD** [comment]
Oh, actually that internal backend fix doesn't include sending the updated child details so the thread count is still not working as expected. Looking into it.

**Comment by MariaHCD** [comment]
Working on the internal fix here! Once that's done we can prioritize making this work offline as well.

**Comment by MariaHCD** [comment]
The internal fixes are currently in review

**Comment by MariaHCD** [comment]
The internal fixes have been deployed to staging. 

So currently, completing & reopening tasks are working offline but the thread count does not update.

https://github.com/Expensify/App/assets/12268372/c458679c-ebb3-4c0f-9d51-d5752c765bea

So let's focus on fixing that here cc: @aimane-chnaif

This is open for proposals!

**Comment by MariaHCD** [comment]
There's no need for a bounty increase, this was just slightly delayed for the internal fix.

We're now open to external proposals to update the thread count when the user is offline and they complete or reopen a task.

**Comment by bfitzexpensify** [comment]
Not overdue, waiting for proposals. @MariaHCD if we don't get any proposals by end of week, I think we should increase the bounty to $2,000 on Monday - what do you think?

**Comment by bfitzexpensify** [comment]
Sorry @dukenv0307, I scrolled straight past that! @aimane-chnaif, can you review @dukenv0307's proposal when you get a chance - thanks!

**Comment by bfitzexpensify** [comment]
@aimane-chnaif bump to review @dukenv0307's proposal

**Comment by bfitzexpensify** [comment]
@aimane-chnaif are you happy with @dukenv0307's proposal?

**Comment by bfitzexpensify** [comment]
Still waiting on https://github.com/Expensify/App/pull/20762 to be merged

**Comment by bfitzexpensify** [comment]
Thanks @dukenv0307 - @aimane-chnaif, is @dukenv0307's proposal good to move forward with?

**Comment by MariaHCD** [comment]
@dukenv0307's proposal looks good to me too!

**Comment by bfitzexpensify** [comment]
Assigned July 17th, merged July 19th - eligible for the #urgency bonus

**Comment by bfitzexpensify** [comment]
Payments issued for Reporting and Contributor. @aimane-chnaif please complete the BZ checklist https://github.com/Expensify/App/issues/20570#issuecomment-1646082596 and I'll finalise the C+ payment
