### ISSUE TITLE
Web - Thread - The Complete task message appears when the task's checkbox is not assigned

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 accounts A and B on 2 devices
2. A Create a task not assign anyone
3. B open chat and tick checkbox of the task
4. Open task detail
5. Click "Mark on done"

## Expected Result:
The message "completed task" does not appear in task detail when ticking the checkbox and press "Mark as done" on task not assigned.

## Actual Result:
The message "completed task" appear in task detail when ticking the checkbox or press "Mark as done" on task not assigned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/20c52c17-3851-4e4d-b96e-626be7541f70

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1686106877884719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The message “completed task” and “Re open task” does not appear in task detail when ticking the checkbox or press “Mark as done”, “Mark as incomplete” on task not assinged
### What is the root cause of that problem?
Now, Only the task creator and assignee can complete and repoen the task. After calling completeTask and reopenTask, reportAction is saved to Onyx with optimisticData, But after API return permission error, failureData has not deleted reportAction saved above.
https://github.com/Expensify/App/blob/4cad2489f6feb5efb955924764711a0c36439f58/src/libs/actions/Task.js#L204-L208
https://github.com/Expensify/App/blob/4cad2489f6feb5efb955924764711a0c36439f58/src/libs/actions/Task.js#L260-L264
### What changes do you think we should make in order to solve the problem?
To solve this problem we will set reportAction = null if the API returns an error.
In completedTask:
```
{
        onyxMethod: Onyx.METHOD.MERGE,
	key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${taskReportID}`,
	value: {[completedTaskReportAction.reportActionID]: null},
},
```
In reopenTask:
```
{
	onyxMethod: Onyx.METHOD.MERGE,
	key:`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${taskReportID}`,
	value: {[reopenedTaskReportAction.reportActionID]: null},
},
```
Result:
https://github.com/Expensify/App/assets/39086067/90bc3e0f-8c92-42c9-92c9-d049130f3d8b
### What alternative solutions did you explore? (Optional)
Disable button, checkbox where these 2 APIs are called by checking if current user is owner or assigned

**Comment by BhuvaneshPatil** [comment]
Dupe https://github.com/Expensify/App/issues/20542

**Comment by greg-schroeder** [comment]
Closed as duplicate report
