### ISSUE TITLE
[Navigation Refactor] Deeplinking the datepicker with selected year ignores the year

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Deeplink to DateOfBirthPage https://new.expensify.com/settings/profile/personal-details/date-of-birth?year=2007
1. Click on one of the days

https://github.com/Expensify/App/assets/36083550/6066263e-648b-4e8b-808d-67fc09c76ee3

## Expected Result:
Describe what you think should've happened

The year in the route should be selected

## Actual Result:
Describe what actually happened

The year is ignored

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @WoLewicki 
**Slack conversation:** N/A 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ea7083a5007dc5e</li>
        <li>Upwork Job ID: 1668227708773273600</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
@rushatgabhane are you still using a different upwork profile for these jobs? Created the job here so you can apply either way!

https://www.upwork.com/jobs/~01405925b956590f9f

**Comment by mountiny** [comment]
I think we can actually close this one, its an edge case and we are going to work on refactoring the datepicker to be easier to reuse. https://github.com/Expensify/App/issues/20630
