### ISSUE TITLE
[$1000] Chat room doesn't go away and chat composer is still active if eliminated user from room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome on staging and login with first user > Create a new workspace > Invite second user
2. Create a new room using the workspace created in restricted mode > send a message to the room
3. From the second user (login in another window) , send multiple messages to the same chat room
4. From the first user, remove the second user from the workspace and notice that on the second user's window, the header is disabled but the chat composer is still active and we're able to message it even when the user was already removed. It should have disabled the whole room page and the chat composer shouldn't be active in this case.
## Expected Result: 
Chat room should not be shown if user is eliminated from the room
## Actual Result: 
Chat room doesn't go away and chat composer is still active if user is eliminated from room
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1a55d701-0fd5-4cfb-91db-f8d8bd4a1495

https://github.com/Expensify/App/assets/43996225/5c0e19c5-2cd0-4c13-8392-8e4eb9caa301

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686111061585129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ab7442b30c4fdfe</li>
        <li>Upwork Job ID: 1669280930857480192</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Added the external label!

**Comment by priya-zha** [comment]
Not reproducible today (staging).

**Comment by zanyrenney** [comment]
Closing this out as given noone else has reproduced! Heading OOO so if we reopen this, please reassign the bug label!
