### ISSUE TITLE
Web - Thread- Reacting on a deleted thread comment is allowed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start a chat between account A and account B
2. Post a comment from account A to account B
3. Reply in thread to the last comment
4. Delete the reply from step 3
5. Go back to the original chat with account B and delete the comment with a thread
6. Observe a [Deleted message] placeholder appears
7. React to the placeholder
8. Open the deleted thread from LHN and notice the reaction is also present in the deleted thread first comment

## Expected Result:
User should not be able to react on a deleted thread comment (Slack also doesn't allow this)

## Actual Result:
User can react to the [Deleted message] placeholder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/19d33d2d-e91b-4276-ac18-dc59610c35ad

https://github.com/Expensify/App/assets/93399543/07eb7d22-7dff-4fa5-b79c-8b808185da34

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684756127730389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by spcheema** [comment]
.

**Comment by twisterdotcom** [comment]
Not too sure this is a bug: https://expensify.slack.com/archives/C049HHMV9SM/p1686581824264649?thread_ts=1684756127.730389&cid=C049HHMV9SM

**Comment by twisterdotcom** [comment]
Okay, yes. This is intentional. Thanks!
