### ISSUE TITLE
CLEANUP: Remove Flow Babel preset once the TS migration is done

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#20592]
Remove `@babel/preset-flow` from `babel.config.js` once the TS migration is done.

from [this line](https://github.com/Expensify/App/blob/3531af22dcadaa94ed11eccf370517dca0b8c305/babel.config.js#L3)
and from [this line](https://github.com/Expensify/App/blob/3531af22dcadaa94ed11eccf370517dca0b8c305/babel.config.js#L39)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019322a03e0bf0ef98</li>
        <li>Upwork Job ID: 1668271821400170496</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
This is an internal cleanup. PLEASE DO NOT POST PROPOSALS

**Comment by hayata-suenaga** [comment]
this is monthly issue removing the daily label

**Comment by hayata-suenaga** [comment]
the migration is still going on

**Comment by hayata-suenaga** [comment]
TS migration is still going on. This issue is meant to be done after the TS migration is done

**Comment by hayata-suenaga** [comment]
TS migration is still going on

**Comment by hayata-suenaga** [comment]
TS migration is still going on

**Comment by hayata-suenaga** [comment]
the typescript migration is still going

**Comment by hayata-suenaga** [comment]
TS migration is still going on

**Comment by hayata-suenaga** [comment]
TS migration is still going on

**Comment by hayata-suenaga** [comment]
changing this issue to weekly as the TS migration finishes in the App repo! 🚀

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue! 

I think I can do it as part of [this](https://github.com/Expensify/App/issues/39119) issue, wdyt @hayata-suenaga?

**Comment by hayata-suenaga** [comment]
@blazejkustra, I actually opened a PR for this.

However, the reason that we had this babel plugin for Flow was not that we used Flow before, but to do a workaround for [a bug](https://github.com/facebook/react-native/issues/29084#issuecomment-1030732709) with React Native library. However, because this bug is quite old now, I'll try removing the plugin and see if that works.
