### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Update language on Split Preview

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#20597]
To make our Split preview component more accessible to use cases outside of splitting "bills" – which are honestly more likely just receipts – we decide in [this thread](https://expensify.slack.com/archives/CPF3SDYTX/p1686051642167749) to make the following changes to the Split details.

<img width="939" alt="image (19)" src="https://github.com/Expensify/App/assets/1127863/c5eb5c4f-c3cf-4ebb-876e-9f61660a6a83">

 - Update `Who paid?` to `Paid by`
 - Update `Who was there` with `Split with`

Keeping this internal because we had some internal volunteers willing to quickly make the update. 

cc @trjExpensify @StefStavri 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ba3dfd7296d73a6</li>
        <li>Upwork Job ID: 1668292771035025408</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
@JmillsExpensify should I be using the `Enginering` label to assign an internal engineer? Or were you still hoping for a volunteer?

**Comment by eVoloshchak** [comment]
The change is very simple (the hardest part is getting the Spanish translations), I can just open up a PR for this tomorrow if you need volunteers

**Comment by jeet-dhandha** [comment]
Commit: https://github.com/Expensify/App/commit/fd300e2d59ce8f62f95dfb4caa233cc1f43faba5
Will this work ?

**Comment by jeet-dhandha** [comment]
Any updates here ?

**Comment by madmax330** [comment]
From this: 

> Keeping this internal because we had some internal volunteers willing to quickly make the update.


@JmillsExpensify can you assign the people who volunteered? Or make it external?

**Comment by madmax330** [comment]
Bump @JmillsExpensify Removing my assignment because I have a too much on my plate rn.

**Comment by jeet-dhandha** [comment]
Are we still waiting on the PR ?

**Comment by eVoloshchak** [comment]
@JmillsExpensify, could you assign @jeet-dhandha to this issue please?

**Comment by jeet-dhandha** [comment]
@eVoloshchak PR is ready you can merge it whenever you get time.

**Comment by jeet-dhandha** [comment]
Accepted offer. Please let me know on further process.

**Comment by jeet-dhandha** [comment]
Hi, any updates on payment ?

**Comment by NicMendonca** [comment]
@jeet-dhandha you've been paid 🎉 

@eVoloshchak will you be requesting payment via Expensify? Or should I pay via Upwork?

**Comment by jeet-dhandha** [comment]
Upwork would be great.

**Comment by jeet-dhandha** [comment]
Can you also tell me how can i setup my Indian bank’s account in expensify ?

**Comment by jeet-dhandha** [comment]
As i think I won’t have to pay the commission of 10% which upwork charges for every payment.

**Comment by eVoloshchak** [comment]
@NicMendonca, I'll request the payment via NewDot. What should be the amount?

> Can you also tell me how can i setup my Indian bank’s account in expensify

@jeet-dhandha, payments via Expensify aren't yet available to contributors unfortunately

**Comment by jeet-dhandha** [comment]
Okay 👍

**Comment by NicMendonca** [comment]
@jeet-dhandha opps - sorry for the confusion! 


- @jeet-dhandha  - C: $1,000
- @eVoloshchak - C+: $1,500

**Comment by jeet-dhandha** [comment]
Do we not get any bonus 😂

**Comment by NicMendonca** [comment]
> Merged PR within 3 business days of assignment

The PR was *not* merged within 3 business days

**Comment by jeet-dhandha** [comment]
I got offer on 13th of July (Thursday) and opened it that day.
The PR merged on 17th of July (Monday).
And i think we don’t count Saturday and Sunday.

**Comment by NicMendonca** [comment]
@jeet-dhandha sent you offer for bonus

**Comment by NicMendonca** [comment]
The PR was *not* merged within 3 business days, but that was a result of us, not you or @eVoloshchak

**Comment by eVoloshchak** [comment]
Requested the payment via NewDot, thanks to everyone 🎉

**Comment by NicMendonca** [comment]
@jeet-dhandha paid bonus 🎉 


all good here!

**Comment by jeet-dhandha** [comment]
Accepted and thanks.

**Comment by JmillsExpensify** [comment]
Reviewed details for @eVoloshchak. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.
