### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Dev - Android - Console Error on starting of new chat 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + Icon
2. then Go to New Chat
3. Search for new chat
4. Click on that
5. Observe the console Warning
## Expected Result: 
There should not be any console Error
## Actual Result: 
There is console Warning, This Happens only for first time . After that Console warning is not getting.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-4
**Reproducible in staging?:** happening in Dev
**Reproducible in production?:**  happening in Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/52fb579e-2227-45a8-942d-f02348d4c629

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686121832456679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01402ba3bf64c4e966</li>
        <li>Upwork Job ID: 1670780648163078144</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
@allroundexperts can you reproduce this? I am struggling!

**Comment by NicMendonca** [comment]
@allroundexperts I am using BrowserStack - do you know how to open console there? 🙏 But I am not getting that "flash" error like in the OP video

![2023-06-15_15-43-06 (1)](https://github.com/Expensify/App/assets/24947345/ad04d659-4be6-425c-aca7-f6f0f75ecc0d)

**Comment by abdulrahuman5196** [comment]
@allroundexperts It seems the change mentioned by you was added as part of this - https://github.com/allroundexperts/Expensify/commit/9c626fa836c8ac626777c783481d63923384d540.
I don't think we can directly point to react native's flatlist directly with the above change.

**Comment by abdulrahuman5196** [comment]
@NicMendonca  We can remove the needs reproduction label. I was also able to reproduce the issue.

@allroundexperts I am not super inclined towards importing 2 FlatList instance and passing one for the type and another for the actual usage. Same for the alternate solution as well, I wouldn't want to set a generic instance for a FlatList type. But alternative seems to be better in the proposal comparatively.

But I am checking if we have any guideline for defining types of innerRef, In some places we have just used `React.Component` as the alternate suggests. If you have any references, it would be better to check those.

**Comment by abdulrahuman5196** [comment]
@allroundexperts It seems we are using 'React.Component' at many of the forwarded ref component. So it should be fine to replicate the same to have consistency. 
I am also fine to use to this common refPropTypes created recently https://github.com/Expensify/App/blob/main/src/components/refPropTypes.js#L3

@allroundexperts 's proposal here https://github.com/Expensify/App/issues/20591#issuecomment-1587776869 looks good. We can go with one of the option mentioned in this comment


🎀👀🎀
C+ Reviewed

🎀👀🎀 C+ Reviewed

cc: @NicMendonca

**Comment by abdulrahuman5196** [comment]
:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by abdulrahuman5196** [comment]
Hi, @aldo-expensify  the c+ reviewed comment is here https://github.com/Expensify/App/issues/20591#issuecomment-1604757259

**Comment by NicMendonca** [comment]
@twisterdotcom I am going OOO until Wednesday. Can you watch this while I am away? I'll unassign you when I am back. Thank you!

**Comment by twisterdotcom** [comment]
Just waiting on @aldo-expensify to give a 👍

**Comment by aldo-expensify** [comment]
Sorry, I missed the last ping. Let's go with @allroundexperts 's proposal, looks good to me.

**Comment by twisterdotcom** [comment]
@MelvinBot we literally _just_ assigned somebody. Chill.

**Comment by aldo-expensify** [comment]
I'll be out of office next week, I don't think you need any action from me 👋

**Comment by NicMendonca** [comment]
@allroundexperts @abdulrahuman5196 @niravkakadiya25 apply/ accept the offer please! https://www.upwork.com/jobs/~01402ba3bf64c4e966

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/16581

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/16581/files#r1258489686


>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Not required. Since it is a minor type error caused from the navigation reboot PR.

**Comment by abdulrahuman5196** [comment]
@NicMendonca Applied on the job

**Comment by niravkakadiya25** [comment]
@NicMendonca can you send the invitation or job proposal directly?

**Comment by NicMendonca** [comment]
@niravkakadiya25 you are not searchable via GH handle, and your GH doesn't have your full name: 

<img width="305" alt="image" src="https://github.com/Expensify/App/assets/24947345/a8144ee6-a7c8-42e5-926c-a9efda20b1d3">

Can you please apply here or let me know how I can search you? https://www.upwork.com/jobs/~01402ba3bf64c4e966

**Comment by niravkakadiya25** [comment]
@NicMendonca You can search with "Nirav K" In Upwork.
and here is my Upwork profile link.
https://www.upwork.com/freelancers/~01b750750a0d76226c

**Comment by NicMendonca** [comment]
@niravkakadiya25 @abdulrahuman5196 paid!
