### ISSUE TITLE
[HOLD for payment] [$250] [Accessible Pressables] Migrate PressableWithDelayToggle

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20601]
Migrate PressableWithDelayToggle to use new Pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e3dfcea2e115797</li>
        <li>Upwork Job ID: 1668308032502738944</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by syedsaroshfarrukhdot** [comment]
Can i help in migration ?

**Comment by robertKozik** [comment]
Hi! As an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one?
CC. @roryabraham

**Comment by roryabraham** [comment]
@sonialiap The only payment due here is $250 to @aimane-chnaif

**Comment by sonialiap** [comment]
@aimane-chnaif offer sent

**Comment by sonialiap** [comment]
Paid ✅
