### ISSUE TITLE
[HOLD for payment 2023-06-29] [$250] [Accessible Pressables] Migrate PinButton to accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20602]
Migrate PinButton to accessible pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a291515a00d4b8f</li>
        <li>Upwork Job ID: 1668308447044165632</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
I can work on this if possible

**Comment by mallenexpensify** [comment]
@roryabraham can you provide some guidance here?  I see the price got lowered to $250 and that the `Help Wanted` was removed, unsure what I and/or Rajat are supposed to do.

**Comment by roryabraham** [comment]
@mallenexpensify Software Mansion will handle this implementation. Rajat will be awarded $250 for the PR review, and you're here to facilitate that payment. No other payments will be due.

**Comment by roryabraham** [comment]
Additional context:

- https://expensify.slack.com/archives/C02NK2DQWUX/p1686526913675359
- https://expensify.slack.com/archives/C01SKUP7QR0/p1686609528887199

**Comment by robertKozik** [comment]
Hi! As an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one?

**Comment by mallenexpensify** [comment]
@roryabraham, plz review

**Comment by roryabraham** [comment]
Only payment due here is $250 to @parasharrajat

**Comment by mallenexpensify** [comment]
Ready for payment @parasharrajat ?

**Comment by roryabraham** [comment]
Bump @parasharrajat

**Comment by roryabraham** [comment]
Thanks for the extra context @parasharrajat 🙇🏼

**Comment by mallenexpensify** [comment]
Eeeeeps, my first non-Upwork payment! 
@parasharrajat it states in StackOverflow
> If you are assigned an issue that they are the C+ on, you can close the issue as soon as the Contributor and bug reporter and regression steps have been completed. Anu will manage the payment outside of GH directly in newdot, you do not need to co-assign her.

I'm going to bump this to weekly and periodically check in to see if you received payment, cool?
