### ISSUE TITLE
[HOLD for payment 2023-06-29] [$250] [Accessible Pressables] Migrate ReportPreview to use accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20603]
Migrate ReportPreview to use new pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01789015714d12d8b4</li>
        <li>Upwork Job ID: 1668308922414673920</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
Just confirming, are we trying to achieve the below changes ?

<img width="450" alt="Screenshot 2023-06-12 at 11 51 00 PM" src="https://github.com/Expensify/App/assets/78416198/2bd7e39d-6475-42fe-8731-da5e43ef297d">
<img width="846" alt="Screenshot 2023-06-12 at 11 50 43 PM" src="https://github.com/Expensify/App/assets/78416198/ada19764-9f23-4cb6-9f5e-9248139a9aeb">

**Comment by roryabraham** [comment]
Sorry @jeet-dhandha, we've already hired someone for this and all other `[Accessible Pressable]` issues. Also:

- You shouldn't post proposals on issues without the `Help Wanted` label
- For issues that do have the `Help Wanted` label, we have a proposal template, and are encouraged to ignore any proposals that do not follow the template.

**Comment by robertKozik** [comment]
Hi! As an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one?

**Comment by JmillsExpensify** [comment]
PR was deployed to staging two hours ago. Are we waiting the standard regression period on these?

**Comment by roryabraham** [comment]
> Are we waiting the standard regression period on these?

yep

**Comment by JmillsExpensify** [comment]
For this payout, everyone is eligible for $250. @parasharrajat Upwork job [is here](https://www.upwork.com/jobs/~01789015714d12d8b4), do you mind applying? Or alternatively, will you submit this payment via NewDot? Everyone else will be handled via invoice.

**Comment by roryabraham** [comment]
@JmillsExpensify minor clarification ... since this is a new feature related to a project and not a bug, the $250 review bounty for this issue should not be included in the SWM invoice. They should only be invoicing hourly for time spent on projects.

**Comment by roryabraham** [comment]
@JmillsExpensify @parasharrajat what are the next steps here?

**Comment by roryabraham** [comment]
Made a weekly

**Comment by anmurali** [comment]
Approved $250 for Rajat based on https://github.com/Expensify/App/issues/20603#issuecomment-1621695465

**Comment by roryabraham** [comment]
All set here then?

**Comment by JmillsExpensify** [comment]
All set! Thanks
