### ISSUE TITLE
[HOLD for payment 2023-06-23] [$250] [Accessible Pressables] Migrate AttachmentView

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20600]
Migrate AttachmentView to use the new Pressable components
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ece6545b87692f1e</li>
        <li>Upwork Job ID: 1668307585597038592</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment]
I can work on this one

**Comment by jeet-dhandha** [comment]
PR: https://github.com/Expensify/App/pull/20627

**Comment by trjExpensify** [comment]
Can someone bring me up to speed on these issues. Are they flat rate at $250? When do they need to be paid, and to who?

**Comment by roryabraham** [comment]
Here's the TL;DR on these:

- We've been working with Software Mansion to complete this migration, and they're almost done.
- The only reason they're labeled external w/ an Upwork job at all is to auto-assign a C+ and pay them out for the review
- Because they're all the same and quite simple, yes I've been pricing them at $250

**Comment by jeet-dhandha** [comment]
Sorry for the Inconvenience. Didn't knew that i shouldn’t apply on this Issues. 👍

**Comment by Skalakid** [comment]
@roryabraham Hi, as an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one, please?

**Comment by roryabraham** [comment]
@trjExpensify The only payment due here is $250 to @parasharrajat for the review

**Comment by trjExpensify** [comment]
Offer sent to @parasharrajat

**Comment by roryabraham** [comment]
Bump @parasharrajat so you can get your 🤑

**Comment by trjExpensify** [comment]
Totally.

**Comment by trjExpensify** [comment]
Same as Friday, melvin. Did you get this handled through NewDot, @parasharrajat? :)

**Comment by trjExpensify** [comment]
Hm okay, but you should have been able to request by now?

**Comment by roryabraham** [comment]
Just waiting for @parasharrajat NewDot payment

**Comment by anmurali** [comment]
Approved $250 based on https://github.com/Expensify/App/issues/20600#issuecomment-1636584593

**Comment by trjExpensify** [comment]
Neeeat! Thanks, closing! :)
