### ISSUE TITLE
[$250] [Accessible Pressables] Migrate ReportDetailsPage to accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20605]
Migrate ReportDetailsPage to new pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012477e6a2bf0a4d54</li>
        <li>Upwork Job ID: 1668310498985648128</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by kuluruvineeth** [comment]
@roryabraham could you please assign me this task, I would like to work on it, thanks.

**Comment by BhuvaneshPatil** [comment]
I would like to work on this issue

**Comment by Skalakid** [comment]
@roryabraham Hi, as an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one, please?

**Comment by arielgreen** [comment]
Reassigning, team change

**Comment by joekaufmanexpensify** [comment]
@roryabraham @0xmiroslav  LMK who we should go with here, and happy to assign someone!

**Comment by joekaufmanexpensify** [comment]
Ah, okay sounds good. Closing!
