### ISSUE TITLE
[HOLD for payment 2023-06-23] [$250] [Accessible Pressables] Migrate ReportActionItemThread to accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20606]
Migrate ReportActionItemThread to new pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6ed27e6d13a65ce</li>
        <li>Upwork Job ID: 1668310824732831744</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
I would love to work on this issue

**Comment by roryabraham** [comment]
Sorry @s-alves10, we've already hired someone for this and all other `[Accessible Pressable]` issues.

**Comment by Skalakid** [comment]
@roryabraham Hi, as an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one, please?

**Comment by roryabraham** [comment]
@kevinksullivan Just to clarify, the only payment due here is $250 to @narefyev91 for the PR review. No additional payment due to @Skalakid at this time

**Comment by kevinksullivan** [comment]
Ah got it. Sorry for the delay in missing this. @narefyev91 can you apply of the job in upwork? I'm not able to find you by name there.

**Comment by narefyev91** [comment]
> Ah got it. Sorry for the delay in missing this. @narefyev91 can you apply of the job in upwork? I'm not able to find you by name there.

Hey I'm from Callstack - no needs to apply in upwork. Thanks! :-)
