### ISSUE TITLE
[HOLD for payment 2023-06-29] [$250] [Accessible Pressables] Migrate TaskPreview to use accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20604]
Migrate TaskPreview to use new pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c486f3dcaf58647a</li>
        <li>Upwork Job ID: 1668309073450770432</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by nhminhduc** [comment]
I want to work on this :D

**Comment by robertKozik** [comment]
Hi! As an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one?
CC. @roryabraham

**Comment by roryabraham** [comment]
Looks like @robertKozik just put up a draft PR

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @slafortune,  I'll grab this back from you when I return!

**Comment by roryabraham** [comment]
PR merged

**Comment by slafortune** [comment]
@eVoloshchak offer sent 👍 
Robert is part of SWM

**Comment by slafortune** [comment]
Paid
