### ISSUE TITLE
[HOLD for payment 2023-06-23] [$250] [Accessible Pressables] Migrate WorkspaceInviteMessagePage to accessible pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20607]
Migrate WorkspaceInviteMessagePage to new pressables
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01448bef2a5e1e8f7c</li>
        <li>Upwork Job ID: 1668311121647702016</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by kuluruvineeth** [comment]
@roryabraham could you please assign me this task, I would like to work on it, thanks.

**Comment by jeet-dhandha** [comment]
Question:
Are we looking for these changes ? (If yes then count this as a Proposal too).

<img width="849" alt="Screenshot 2023-06-12 at 11 28 22 PM" src="https://github.com/Expensify/App/assets/78416198/280c89f6-b051-400b-bd10-681a3be59416">

Thanks in Advance, 
Jeet Dhandha 

👍

**Comment by jeet-dhandha** [comment]
Proposal PR:
- https://github.com/Expensify/App/pull/20628

**Comment by roryabraham** [comment]
Hi everyone, we've already hired someone to work on this issue, which is why it does not have the `Help Wanted` label.

**Comment by jeet-dhandha** [comment]
Sorry for the Inconvenience. Didn't knew that i shouldn’t apply on this Issues. 👍

**Comment by Skalakid** [comment]
Hi, as an expert contributor from Software Mansion I'd like to get this issue, can you assign me to this one, please?
CC. @roryabraham

**Comment by roryabraham** [comment]
@anmurali The only payment due here is $250 to @Santhosh-Sellavel. Thanks!

**Comment by anmurali** [comment]
This is going to be our first Manual Request payment in the real world ([Conversation](https://expensify.slack.com/archives/C02NK2DQWUX/p1687799951166409?thread_ts=1686871517.189609&cid=C02NK2DQWUX))

Waiting on https://github.com/Expensify/App/pull/21357 to hit Staging

**Comment by roryabraham** [comment]
Ok neat some stuff is happening here 🙃

**Comment by anmurali** [comment]
@Santhosh-Sellavel has been paid
