### ISSUE TITLE
Dev: For Add Debit card Form's zip code are behave deffenrent in Web and IOS Native

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with User A  in Web and User B in IOS Native
2. Go to Profile setting and then go to Payments and select Add Debit card for both User
3. Select "Florida" as State For both User
4. Observe zip code field

## Expected Result:
For Web and IOS both Platform should be same behaviour

## Actual Result:
Web and IOS Native Have different Behaviour(I am able to enter characters in Web but not able to add characters in IOS Native)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cadeef54-6c46-46b3-ae10-2006e06e9678

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686210935688089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
I do think this is a bug since forms shouldn't even allow a letter in fields like zip code. If we only allow numbers in fields like zipcode it will improve the UX and behaviour would also be consistent in all platforms. 

This is not an issue with zip code but with various other fields in all places where the Form component is used.

**Comment by sonialiap** [comment]
US zip codes all numeric (with the occasional `-` followed by a numeric extension). We cannot control what a user enters on their keyboard but we should flag invalid zip codes. Looks like we currently flag invalid input and don't let them proceed so I think it's fine that the user is able to enter letters. 

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/17131195/79de5cca-b4c4-4ca1-bd7c-41609c91970f">

**Comment by niravkakadiya25** [comment]
@sonialiap but In IOS i am not able to enter alphanumeric values
