### ISSUE TITLE
Define TypeScript guidelines

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#20623]
Part of [TS migration](https://github.com/Expensify/App/issues/16665) issues.

- Create the first version of the guideline in `app/contributingGuides/TYPESCRIPT_STYLE.md`.
- A rough overview of the guideline is in [the design doc](https://docs.google.com/document/d/1LNcgYeYyovQ88gNjLIgBqBReLtbLAbxeAbna9QKxeAQ/edit#bookmark=id.pz75s9ij30u2).
- Add succinct code examples as needed.
- Create sub-files if necessary to divide the guideline into sections.
- While writing the guideline, if you encounter any unclear points that should be discussed, post them on the #typescript-new-expensify channel.

**Comment by hayata-suenaga** [comment]
The new guideline is developed in [this google doc](https://docs.google.com/document/d/1CYivl5lGGJ1TgwPAmshJ-pIAClwszIVBYg7hpQCS6to/edit#heading=h.ffi45lc01b3a)

**Comment by fabioh8010** [comment]
@hayata-suenaga The [PR](https://github.com/Expensify/App/pull/21050) is ready to review!

**Comment by hayata-suenaga** [comment]
@fabioh8010 thank you so much for this PR 🎉 I'll take a look at this tomorrow

**Comment by hayata-suenaga** [comment]
the PR is still being worked on and review is still going on

**Comment by hayata-suenaga** [comment]
The PR is actively reviewed and worked on 👍

**Comment by hayata-suenaga** [comment]
https://expensify.slack.com/archives/C03TQ48KC/p1689011336554509

**Comment by hayata-suenaga** [comment]
The PR has been merged. closing this
