### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] OS Safari - All 6 digits visible in first digit slot when using OTP autofill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20642]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to new.expensify.com in Safari on iOS.
2. Enter your phone number.
3. Click on the code that appears in the keyboard autofill.
4. Notice that in the first digit placeholder, all 6 digits are visible but in other slots the correct digits are visible.

## Expected Result: 
Each digit should be visible in its own slot.
## Actual Result: 
All digits are visible in the first slot, in the other slots (2nd to 6th), correct digits are visible.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.24-5
**Reproducible in staging?:** needs reproduction ( I don't have iphone with sim)
**Reproducible in production?:** needs reproduction ( I don't have iphone with sim)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/04172d36-30e1-4a4b-8b01-8a6aaeea6d32

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686154610357189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ac63cca1c7fc022</li>
        <li>Upwork Job ID: 1669104099919405056</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by KALLL** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On OTP autofill all 6 digits are visible on the first field
### What is the root cause of that problem?
The `maxLength` for each individual OTP field has been set to be Length of the OTP = 6

https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/components/MagicCodeInput.js#L315-L321
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/components/MagicCodeInput.js#L68
### What changes do you think we should make in order to solve the problem?
We **don't** have to change the defaultProps `maxLength` value as it is being used for other purposes like ` decomposeString() `
but we can change the maxLength of the TextInput :
Inside the TextInput doing `maxLength={1}` like
```
<TextInput
                                ref={(ref) => (inputRefs.current[index] = ref)}
                                autoFocus={index === 0 && props.autoFocus}
                                inputMode="numeric"
                                textContentType="oneTimeCode"
                                name={props.name}
                                maxLength={1}
```
will solve the problem. 
### What alternative solutions did you explore? (Optional)
Another possible solution is to use the `onChangeText` prop instead of the `value ` prop to handle the autofill logic

**Comment by stephanieelliott** [comment]
I was able to repro this

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @conorpendergrast,  I'll grab this back from you when I return!

**Comment by KALLL** [comment]
@thesahindia Hello, I was wondering if you had a chance to test my proposal for the OTP autofill issue. I would appreciate any feedback or questions you might have.

**Comment by conorpendergrast** [comment]
@thesahindia Can you take a look at the solution that @ginsuma posted? Thank you!

**Comment by conorpendergrast** [comment]
Unassinign @grgia as @neil-marcellini is already assigned (the process has changed in between the two assignments)

**Comment by neil-marcellini** [comment]
> @ginsuma's [proposal](https://github.com/Expensify/App/issues/20642#issuecomment-1599075474) looks good to me!

I agree, hiring! @ginsuma why do we need `transition: 'background-color 9999s',`?

**Comment by neil-marcellini** [comment]
The PR is under review and we'll probably merge it soon.

**Comment by stephanieelliott** [comment]
All reviews completed, PR is undergoing QA now 🎉

**Comment by neil-marcellini** [comment]
Bump @thesahindia

**Comment by stephanieelliott** [comment]
Sent offer to @Nikhil-Vats and @thesahindia on Upwork 
@ginsuma I can't find you on Upwork, can you please propose for the job so that I can hire you? https://www.upwork.com/jobs/~01820b37e46a5ddb5e

**Comment by Nikhil-Vats** [comment]
@stephanieelliott I didn't get any offer so I have applied for the job with the reporting amount.

**Comment by neil-marcellini** [comment]
Not over due, bump @stephanieelliott

**Comment by stephanieelliott** [comment]
Extended offers to @Nikhil-Vats and @ginsuma, will pay this ASAP once you accept!

**Comment by Nikhil-Vats** [comment]
Done @stephanieelliott

**Comment by neil-marcellini** [comment]
Not overdue

**Comment by stephanieelliott** [comment]
@Nikhil-Vats and @ginsuma have been paid
Regression test: https://github.com/Expensify/Expensify/issues/302570
@thesahindia will be requesting payment via newdot

**Comment by JmillsExpensify** [comment]
@stephanieelliott Can you provide amounts on that payment summary? I need this to pay @thesahindia

**Comment by stephanieelliott** [comment]
Sure, here ya go @JmillsExpensify! 

Summarizing payment on this issue: 
 - Issue reporter: @Nikhil-Vats  $250 paid via Upwork 
 - Contributor: @ginsuma $1000 paid via upwork 
 - Contributor+: @thesahindia $1000, please pay via newdot
 
 Upwork job is here, [X] bonus is included on final payout

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @thesahindia based on BZ summary.
