### ISSUE TITLE
The first user tooltip is shown at the bottom on group chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20670]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a group with multiple users
3. Click on user details
4. Hover over the first user and notice that the tooltip is shown at the bottom
5. But now hover over the remaining users and notice that the tooltip is shown at the top

## Expected Result: 
The first user tooltip should be shown at top like other users on group chat
## Actual Result: 
The first user tooltip is shown at the bottom on group chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3ae79da6-0069-4531-bc18-abb14e248182

https://github.com/Expensify/App/assets/43996225/6760edcd-3b6d-4588-9653-7e2d00e851bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686630260368039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Agreed, seems like this is how a tooltip is supposed to behave
