### ISSUE TITLE
[HOLD for payment 2023-06-23] [HOLD for payment 2023-06-21] [$1000] mWeb - Chat - Cancel button must be pressed two times

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20082

## Action Performed:
1. Open http://staging.new.expensify.com/
2. Log in
3. Enter the chat with somebody
4. Edit message and change text
5. Close keyboard
6. Click the cancel button

## Expected Result:
Cancel button must be pressed one time

## Actual Result:
Cancel button must be pressed two times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/041b678f-24f6-4988-8c4c-8379a8a0d6af

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01163231d12c885dff</li>
        <li>Upwork Job ID: 1668684207716220928</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Thanks for the proposal @HezekielT - solution looks good to me and tests well. Could you get a PR up?

**Comment by maddylewis** [comment]
moving to daily since payment is coming up!

**Comment by maddylewis** [comment]
apologies for the delay! reviewing this one now.

**Comment by maddylewis** [comment]
Payments: 
- [ ] @allroundexperts C+ - $1000
- [ ] @HezekielT contributor - $1000

**Comment by maddylewis** [comment]
payments sent - is there anything else needed on this one before I close it out?

**Comment by maddylewis** [comment]
shoot - i wish you would've mentioned being eligible for a reporting bonus when i listed out the payment amounts here - https://github.com/Expensify/App/issues/20682#issuecomment-1607539582

to clarify, @HezekielT was assigned on June 13 and the PR was merged on June 16, correct?

**Comment by maddylewis** [comment]
sent bonuses!

**Comment by maddylewis** [comment]
payments sent - i think we're all set here? closing.
