### ISSUE TITLE
message disappear in LHN after few second when user create a new chat and send message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. switch network to slow 3G
2. click on + icon
3. select new chat
4. type email or phone with whom you don’t have chat history
5. click on the email and send message immediately
6. check the LHN
## Expected Result:
message should show in LHN
## Actual Result:
This is the beginning ... message shows in LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0b1dfdc9-9eab-409e-b3ac-345c5996a86e

https://github.com/Expensify/App/assets/43996225/65f262aa-e0aa-4bd9-a9f0-0c3cda600a8f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686136627542369
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I don't think this is a bug. You're on a slow connection, not offline. So as a result, we optimistically show the message in the LHN but that doesn't mean that it's been received by the server.

**Comment by JmillsExpensify** [comment]
Closing, please comment if you think otherwise.
