### ISSUE TITLE
Make NewDatePicker reusable

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#20698]
# Problem
Coming from [comment 1](https://github.com/Expensify/App/pull/20206#issuecomment-1585075368) and [comment 2](https://github.com/Expensify/App/pull/20206#issuecomment-1585110779) and [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1686344969813909), the NewDatePicker component is quite brittle since we need to the the route for each new usage. That doesn't scale well and leads to a confusing experience.

# Why is this important
We need a reusable "plug and play" date picker component since it'll be used in a lot of flows in App, e.g. bank accounts, requests, etc

# Solution
Discuss and find a solution that accounts for the unique challenges of push to page.

cc @Beamanator @mountiny @ArekChr @TMisiukiewicz @burczu @gedu

**Comment by mountiny** [comment]
Closing this one in favour of previously created https://github.com/Expensify/App/issues/20630, Bartek from Callstack will work on it once we finish the accountID migration
