### ISSUE TITLE
Web - Chat - Copy selected words on right-side copy to clipboard option copies the entire text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20707]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a chat with message
3. Select some words
4. Right click on the words and select Copy to clipboard
5. Paste it on the input field
6. Repeat Step 3
7. Hover over the menu on the right and select Copy to clipboard
8. Paste it on the input field

## Expected Result:
Copy to clipboard on the right hand menu works as expected, which is only the selected words are copied

## Actual Result:
Copy to clipboard on the right hand menu does not work as expected - the entire sentence is copied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/747fba12-cb75-4a64-9392-22eab514e7b1

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  Applause Intrernal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
This seems like expected behaviour and not a bug.

**Comment by twisterdotcom** [comment]
I do not understand what is unexpected about this either. If you choose to use the action menu for "copy", we'll copy everything within that action (ie, the whole comment). If you highlight some text within the action, we'll only copy that.

Reopen if you disagree.
