### ISSUE TITLE
Chat - Space is added after selecting an emoji from dropdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/issues/15951
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Type :wa
4. Select an emoji from the list

## Expected Result:
There is no space added after selecting the emoji

## Actual Result:
Space is added after selecting the emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/71b5c305-660c-4114-8e6f-00b729b2b2c9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
Closing - the space is intentional. Here is the convo: 

https://expensify.slack.com/archives/C049HHMV9SM/p1682386879390169

**Comment by alexpensify** [comment]
Thanks for the feedback @getusha. I'm OOO tomorrow but will start another discussion with the team on Tuesday.

**Comment by alexpensify** [comment]
Thanks for the reminder, I bumped the internal conversation to confirm.
