### ISSUE TITLE
Chat-After changing time zone, the user does not receive and cann't send messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20700]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: mWeb/Chrome - change time zone
second device -Web
1. Open http://staging.new.expensify.com/
2. Log in
3. Enter the chat with somebody on second device(for me -Web)
4. Send message
5. Go to settings>Profile>Timezone
6. Change time zone (not automatically)
7. Send new messages
8. Check second device - No messages received on second device

## Expected Result:
The user can send and receive messages

## Actual Result:
The user sees that he is typing messages but does not receive it, and you need refresh the page to receive messages again.The sent message also does not reach the second user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5636f2b0-515e-4211-87be-718dade64ffc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Reproduced on staging:

https://github.com/Expensify/App/assets/7277067/1015f9e3-b413-4f78-9ba3-0b3ab08457a1

Seeing this in the console:
![Screenshot 2023-06-13 at 2 25 37 PM](https://github.com/Expensify/App/assets/7277067/9f8d8923-54bf-4077-b841-39ea63dd6957)

**Comment by amyevans** [comment]
[Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d6c564168b33b69-SJC%22)+AND+timestamp:[2023-06-13T17:18:35.161Z+TO+2023-06-13T19:18:35.161Z]&index=logs_expensify-022791) for that request show:
```
Push_API - Flushing all pusher messages asynchronously and waiting for them to complete ~~ count: '6308'
```
So we are trying to send pusher events to a lot of accounts (my expensifail account is on the High Traffic policy).

[The last line](https://www.expensify.com/_devportal/tools/logSearch/#sort=desc&size=10000&query=request_id%3A%227d6c564168b33b69-SJC%22%20AND%20timestamp%3A%5B2023-06-13T17%3A18%3A35.161Z%20TO%202023-06-13T19%3A18%3A35.161Z%5D) shows we're hitting the nginx timeout (I think?):
```json
{
  "_index": "logs_expensify-022791",
  "_type": "log",
  "_id": "GtL7tYgBRPBZDqJjqP2d",
  "_score": null,
  "_ignored": [
    "nginx_timestamp"
  ],
  "_source": {
    "type": "web",
    "timestamp": "2023-06-13T18:19:07.250792+00:00",
    "host": "staging-www1.rno",
    "process": "nginx",
    "upstream_header_time": "-",
    "upstream_connect_time": "0.000",
    "upstream_response_time": "32.076",
    "request_time": "32.092",
    "upstream_status": "502",
    "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "body_bytes_sent": "292517",
    "http_status": "502",
    "server_protocol": "HTTP/1.1",
    "request": "/api?",
    "request_method": "GET",
    "nginx_timestamp": "13/Jun/2023:18:19:07 +0000",
    "remote_user": "-",
    "http_host": "staging.expensify.com",
    "remote_addr": "71.192.155.173",
    "request_id": "7d6c564168b33b69-SJC",
    "blob": "",
    "tsb": "2023-06-13T17:19:07.250Z",
    "tsa": "2023-06-13T19:19:07.250Z"
  },
  "sort": [
    1686680347250
  ],
  "type": "web",
  "timestamp": "2023-06-13T18:19:07.250792+00:00",
  "host": "staging-www1.rno",
  "process": "nginx",
  "upstream_header_time": "-",
  "upstream_connect_time": "0.000",
  "upstream_response_time": "32.076",
  "request_time": "32.092",
  "upstream_status": "502",
  "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
  "body_bytes_sent": "292517",
  "http_status": "502",
  "server_protocol": "HTTP/1.1",
  "request": "/api?",
  "request_method": "GET",
  "nginx_timestamp": "13/Jun/2023:18:19:07 +0000",
  "remote_user": "-",
  "http_host": "staging.expensify.com",
  "remote_addr": "71.192.155.173",
  "request_id": "7d6c564168b33b69-SJC",
  "blob": "",
  "tsb": "2023-06-13T17:19:07.250Z",
  "tsa": "2023-06-13T19:19:07.250Z",
  "shortTimestamp": "2023-06-13 18:19:07 250",
  "request_id_html": "7d6c564168b33b69-SJC",
  "timestamp_html": "2023-06-13 18:19:07 250",
  "email_html": ""
}
```

I believe we're temporarily sending 2x the number of pusher events while the Secure Logins refactor project is taking place, so once we stop doing that this should clear up (and it's not reproducible on an account that's part of a smaller policy).

But in any event, this isn't related to a change in App code so isn't a Deploy Blocker.
