### ISSUE TITLE
[HOLD for payment 2023-07-20] Make secondary-login "Delete" always succeed, even if the login didn't exist before

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#20701]
This is a follow-up issue polishing one of the Contact Methods flows. Here is the [tracker issue](https://github.com/Expensify/App/issues/16666).

Coming from [here](https://github.com/Expensify/App/pull/15330/files#r1158936999), we want to change Auth to return success when trying to delete a login that doesn't exist.

cc @Beamanator

**Comment by Beamanator** [comment]
Agreed!

**Comment by flodnv** [comment]
> we want to change Auth to return success when trying to delete a login that doesn't exist.

I am not sure I agree with that.

1. Why is the client trying to delete a login that does not exist?
2. Even if there's a good reason for (1), why isn't the client gracefully handling an error it triggered?

**Comment by cristipaval** [comment]
Hey @flodnv! Thanks for jumping into this one! Please see [this](https://github.com/Expensify/App/pull/15330/files#r1158936999) for more context.

**Comment by cristipaval** [comment]
Nothing happens, OldDot acts as if that secondary login existed and deletes it from the front-end 🤷

**Comment by flodnv** [comment]
Oh, perfect then! 😄

**Comment by cristipaval** [comment]
> Oh, perfect then! 😄

So do you think we can proceed with this solution or do you still think it is an antipattern? 👀

**Comment by cristipaval** [comment]
Ah, sorry, I missed your comment on the PR.

**Comment by NicMendonca** [comment]
@allroundexperts will you request payment via Expensify?

**Comment by NicMendonca** [comment]
in that case, we can close this! @allroundexperts don't forget! 💰

**Comment by JmillsExpensify** [comment]
@NicMendonca Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by NicMendonca** [comment]
- Issue reporter: none
- Contributor: none
- Contributor+: @allroundexperts  $1,000

(cc @JmillsExpensify)

**Comment by JmillsExpensify** [comment]
Reviewed details for @allroundexperts. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
