### ISSUE TITLE
mWeb - Login- Continue button is not clickable after login with link and logout 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20710]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19498

## Action Performed:
1. Open NewDot on mWeb (Chrome/Android)
2. Login to any account using magic link (not code)
3. Logout
4. Input any email and click continue

## Expected Result:
Continue button should be clickable

## Actual Result:
Continue button is not clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7ecce183-1358-4d08-bea1-eec6ef5ea6da

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - interna Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01730de90b9047f66a</li>
        <li>Upwork Job ID: 1678859166743351296</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
asking if this should be separate - https://github.com/Expensify/App/issues/16301#issuecomment-1593510237

**Comment by Christinadobrzyn** [comment]
following - https://github.com/Expensify/App/issues/16301#issuecomment-1594082149

**Comment by Christinadobrzyn** [comment]
Tracking - https://github.com/Expensify/App/issues/16301#issuecomment-1594082149

**Comment by Christinadobrzyn** [comment]
Tracking - https://github.com/Expensify/App/issues/16301#issuecomment-1594082149

**Comment by Christinadobrzyn** [comment]
asking for an update - https://github.com/Expensify/App/issues/16301#issuecomment-1618926826

**Comment by Christinadobrzyn** [comment]
following the PR here - https://github.com/Expensify/App/issues/16301#issuecomment-1619447490

**Comment by Christinadobrzyn** [comment]
Following PR here - https://github.com/Expensify/App/pull/20708

**Comment by abdulrahuman5196** [comment]
@Christinadobrzyn Could you provide information on what this issue is? Only C+ is assigned to internal issue?

**Comment by Christinadobrzyn** [comment]
The [internal label was auto-added](https://github.com/Expensify/App/issues/20710#issuecomment-1631444899) because this issue is 4 weeks old. I was following this https://github.com/Expensify/App/pull/20708 which just went into production and in my testing, it resolved the issue. 

Closing!
