### ISSUE TITLE
Web - Close account - Unable to close specific account, an error appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with [applausetester+ihchat_4_@applause.expensifail.com](mailto:applausetester+ihchat_4_@applause.expensifail.com)

3. Go to Settings -> Security -> Close account
4. Enter the account's email to the input field -> Close account -> Yes for confirm

## Expected Result:
Account closed

## Actual Result:
Error appears: Auth DeletePolicy returned an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6091751_image__113_](https://github.com/Expensify/App/assets/78819774/36c7c72f-409f-4b51-bbcb-4196d100b9d3)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I was not able to reproduce using my tj@expensifail.com test account. I was able to successfully close the account with no errors.

<img width="499" alt="Screenshot 2023-06-13 at 21 25 49" src="https://github.com/Expensify/App/assets/8292562/8e0a9669-1fd5-4b5b-b0fa-f99efa6fa800">
