### ISSUE TITLE
Chat - A line break is resulted from pasting quote message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go offline
4. Edit a message
5. Save the edit
6. Refresh the page
7. Reconnect network
8. Wait for the page to refresh

## Expected Result:
Edit is saved

## Actual Result:
Edit is not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f1510ca8-e2a2-4f43-b32a-2129db6ad8cb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Hey @lanitochka17, could you please make these updates?

 - The issue title doesn't match the content, could you please ensure these are related?
 - The issue isn't reproducible on v1.3.27-6, could you please test on the latest version and let me know if you can still reproduce? Thank you!
