### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] Workspace - Error message when trying to access workspace created with different default contact method.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20406

## Action Performed:
1. Login to NewDot under phone account
2. Add email as secondary login
3. Create a workspace
4. Change default contact from phone to email
5. Try to access settings of workspace from step 3

## Expected Result:
User can open WS 

## Actual Result:
Error message when trying to access workspace created with different default contact method.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52206f5c-02d8-4c89-8b67-82aeec75fffe

https://github.com/Expensify/App/assets/93399543/a3238e50-7b0b-4ab5-a641-72bbdbbda530

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686598989456939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143af88a3b986771d</li>
        <li>Upwork Job ID: 1670867972193251328</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Asking QA if this is indeeed not repro in production as I faced the same issue right now but also in prod

**Comment by kbecciv** [comment]
Issue is not reproductible in production

https://github.com/Expensify/App/assets/93399543/8ea377b6-dee1-4a7e-872d-cc6a01a243ff

**Comment by Beamanator** [comment]
@kbecciv just to be clear, if you sign out / in are you able to access the workspace?

I'm just guessing if you change the default contact method and THEN try to access the workspace you may not be able to, but if you log out / in you may be able to.

I'm going to try all your original steps in production to see if i get the error

**Comment by Beamanator** [comment]
Ya here's what I see on production, which leads me to believe this isn't a deploy blocker:

https://github.com/Expensify/App/assets/3885503/214a20c4-f3b2-499c-99b1-d481be93e5b5

**Comment by Natnael-Guchima** [comment]
@mountiny Yes, it is reproducible on production too. I reported this issue when it was on staging [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686598989456939). 


https://github.com/Expensify/App/assets/57330233/974fb240-5cb5-416c-a854-d12e1068c59d

**Comment by Beamanator** [comment]
Getting a BugZero member here since we can go through the normal process with this one

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An error message is displayed when trying to access a workspace created with a different default contact method.

### What is the root cause of that problem?
The app checks the accessibility of the workspace with `Policy.isPolicyOwner`.
https://github.com/Expensify/App/blob/599f05a801829c4cf9a57bd307acd125195d9437/src/pages/workspace/WorkspaceInitialPage.js#L176-L180

But after changing the default contact, the workspace policy owner is the previous contact and the session email is the current contact, so the check fails and an error is displayed.

### What changes do you think we should make in order to solve the problem?

We should change the `Policy.isPolicyOwner` function to check the user's other contact.

The `loginList` Onyx data contains all the user's contacts, so we can check whether the policy owner is in the login list or not.

Add the following code to `Policy.js`.
```
let loginList;
Onyx.connect({
 key: ONYXKEYS.LOGIN_ LIST,
 callback: (val) = > (loginList = val),
});
```

And modify the isPolicyOwner function as follows.
```
function isPolicyOwner(policy) {
 return _.keys(loginList).includes(policy.owner);
}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by michaelhaxhiu** [comment]
Seems like a valid bug to me. I will go with `External` but correct me if you think otherwise Alex :D

**Comment by narefyev91** [comment]
:ribbon: :eyes: :ribbon: C+ reviewed
LGTM

**Comment by puneetlath** [comment]
@michaelhaxhiu FYI it looks like @dhanashree-sawant actually reported this first in https://github.com/Expensify/App/issues/21142

**Comment by michaelhaxhiu** [comment]
@StevenKKC can you please apply to the job? https://www.upwork.com/jobs/~0143af88a3b986771d

**Comment by StevenKKC** [comment]
@michaelhaxhiu I have applied to the job. Thanks.

**Comment by Beamanator** [comment]
Bump @michaelhaxhiu :D

**Comment by StevenKKC** [comment]
Kindly bump @michaelhaxhiu

**Comment by michaelhaxhiu** [comment]
Damn. Sorry all. This slipped away from me as a loose end and I should've caught it sooner.

Payouts:

- [ ] $250 External issue reporter @dhanashree-sawant
- [ ] $1500 Contributor+ that helped on the issue and/or PR

**Comment by michaelhaxhiu** [comment]
@StevenKKC can you let me know when you accept the offer?

**Comment by StevenKKC** [comment]
@michaelhaxhiu Accepted an offer. Thanks.
