### ISSUE TITLE
Pay out contributors who reported bugs when testing big Onyx refactor PR

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20757]
Pay out contributors who reported bugs in this thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1686587441593309

As mentioned, bug reports are worth $125 each, and ONLY if they're
1. Actual, reproducible bugs
2. Didn't exist on staging / production

In this branch https://expensify.slack.com/archives/C01GTK53T8Q/p1686587441593309 we have asked contributors to test on a feature branch before we merge this to main https://github.com/Expensify/App/pull/20473

The reward has been halved since this is a feature branch and there was supposed to be a lot of bugs but this will help us find them sooner than if only engineers test the app.

The rewards is $125 per one valid reported bug.

they should all be fixed in this PR https://github.com/Expensify/App/pull/20473
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013467787825119c72</li>
        <li>Upwork Job ID: 1679221193126141952</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
All good, thanks!

**Comment by tranvantoan-qn** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1686594249569319?thread_ts=1686587441.593309&cid=C01GTK53T8Q

https://expensify.slack.com/archives/C01GTK53T8Q/p1686594269140449?thread_ts=1686587441.593309&cid=C01GTK53T8Q

**Comment by dhanashree-sawant** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1686594594721189?thread_ts=1686587441.593309&cid=C01GTK53T8Q
https://expensify.slack.com/archives/C01GTK53T8Q/p1686593940309879?thread_ts=1686587441.593309&cid=C01GTK53T8Q
https://expensify.slack.com/archives/C01GTK53T8Q/p1686593894005669?thread_ts=1686587441.593309&cid=C01GTK53T8Q
https://expensify.slack.com/archives/C01GTK53T8Q/p1686593924387069?thread_ts=1686587441.593309&cid=C01GTK53T8Q
https://expensify.slack.com/archives/C01GTK53T8Q/p1686593877239979?thread_ts=1686587441.593309&cid=C01GTK53T8Q

**Comment by tranvantoan-qn** [comment]
Contributor details
Your Expensify account email: [tranvantoan.qn@gmai.com](mailto:tranvantoan.qn@gmai.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by tranvantoan-qn** [comment]
Contributor details
Your Expensify account email: [tranvantoan.qn@gmail.com](mailto:tranvantoan.qn@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by tranvantoan-qn** [comment]
Contributor details
Your Expensify account email: tranvantoan.qn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by priya-zha** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1686597568486069?thread_ts=1686587441.593309&cid=C01GTK53T8Q

https://expensify.slack.com/archives/C01GTK53T8Q/p1686597570781549?thread_ts=1686587441.593309&cid=C01GTK53T8Q

https://expensify.slack.com/archives/C01GTK53T8Q/p1686599248457389?thread_ts=1686587441.593309&cid=C01GTK53T8Q

**Comment by Puneet-here** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1686594344347259?thread_ts=1686587441.593309&cid=C01GTK53T8Q

**Comment by JmillsExpensify** [comment]
I'll get to this one some time this week. Lots of payouts to process!

**Comment by Beamanator** [comment]
Bump to make the payments @JmillsExpensify  :D let me know if you need any help figuring out who needs payment!

**Comment by mountiny** [comment]
Writing a summary for @JmillsExpensify:

- @jayeshmangwani - 1 report - $250
- @tranvantoan-qn - 2 reports - $500
- @dhanashree-sawant - 5 reports - $1250
- @gadhiyamanan  - 3 reports - $750
- @Natnael-Guchima - 3 reports - $750
- @priya-zha - 3 reports - $750
- @avi-shek-jha - 5 reports - $1250
- @Puneet-here - 1 report - $250

**Comment by mountiny** [comment]
Jason is ooo today, hopefully he can get to this on monday

**Comment by JmillsExpensify** [comment]
Alright, there is a lot of you. I think the easiest is to have each of your apply to this [Upwork job](https://www.upwork.com/jobs/~017c54136303efeda0). The minimum payout was $250, so you if you're due more you can request initially or I can pay out the remainder as a bonus. Whatever is easier!

**Comment by tranvantoan-qn** [comment]
Applied to the [job](https://www.upwork.com/jobs/~017c54136303efeda0)

**Comment by dhanashree-sawant** [comment]
@JmillsExpensify, Thanks!
Applied to the job.

**Comment by avi-shek-jha** [comment]
Thanks applied.

**Comment by priya-zha** [comment]
Applied. Thank you.

**Comment by Natnael-Guchima** [comment]
Applied to the job. Thanks.

**Comment by jayeshmangwani** [comment]
Applied to the [job](https://www.upwork.com/jobs/~017c54136303efeda0) , Thank you!

**Comment by JmillsExpensify** [comment]
Thanks for your patience contracts extended to everyone. I'll check back later today and pay out everyone that has accepted the contract.

**Comment by JmillsExpensify** [comment]
Everyone should be paid out as of yesterday. Please let me know if anything is outstanding!
