### ISSUE TITLE
[HOLD for payment 2023-07-05] Removing CP Staging label

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#20764]
# Problem
Coming from [this thread](https://expensify.slack.com/archives/C07J32337/p1685459337386639) and in the spirit of discussing the necessity of each CP, we decided to remove the [CP Staging](https://expensify.slack.com/archives/C07J32337/p1685462294569329?thread_ts=1685459337.386639&cid=C07J32337) label so that NewDot CPs can only be manually CPed by App deployers after a discussion about the real need for that CP.

# Why is this important
Ensures that we always discuss each CP by making authors request the CP in Slack.

# Solution
Remove `CP Staging` label and its functionality

cc @Expensify/mobile-deployers

**Comment by johncschuster** [comment]
Am I needed on this one?

**Comment by roryabraham** [comment]
This will be internal so you're probably good here @johncschuster

**Comment by roryabraham** [comment]
Let's plz try to get https://github.com/Expensify/App/pull/20791 over the finish line before we start implementation on this.

**Comment by AndrewGable** [comment]
Held on https://github.com/Expensify/App/pull/20791

**Comment by roryabraham** [comment]
I think we can take this off HOLD now

**Comment by thienlnam** [comment]
Closing - no payments here to send out here!

There is one linked issue I opened up here: https://github.com/Expensify/App/issues/21763 about the CP process but the CP Staging label is no more!
