### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] Welcome message of custom workspace room translates HTML code to character in offline mode (works fine in online mode)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any custom workspace room or create new by: click on plus->new room->any name, any workspace, any visibility->create room
3. Click on room name to open details page
4. Click on settings
5. Click on welcome message
6. Add any HTML code eg: &#48; and click on save
7. Revisit welcome message to see that it still displays HTML code
8. turn off internet to go offline and revisit welcome message to see that on HTML code is converted to HTML character (In our eg, &#48; will display as 0)

## Expected Result:
App should not convert HTML code to HTML character in room welcome message

## Actual Result:
In offline mode, app converts HTML code to HTML character in room welcome message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.27.6

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c5819b55-e88c-4191-ab29-8e16cafab2f7

https://github.com/Expensify/App/assets/93399543/59543aa9-1690-4f05-8d25-2b43752f6dde

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686214026251619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01187aec34f1d4c1eb</li>
        <li>Upwork Job ID: 1669149753584140288</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment]
I think this could be related to this other [issue when using HTML character codes in the workspace name](https://github.com/Expensify/App/issues/20009).

**Comment by univalchemist** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message of workspace room translates HTML code to character in offline mode(It works fine in online mode)
### What is the root cause of that problem?
The `decode` function of this [package](https://www.npmjs.com/package/html-entities) decodes as `0` in case of wrong `code` entity like `&#48;`
### What changes do you think we should make in order to solve the problem?
`htmlToMarkdown` function of `expensify-common/lib/ExpensiMark` lib should be updated by adding the following condition
```javascript
        const replacedElement = this.replaceBlockElementWithNewLine(generatedMarkdown)
        const decodedHtml = Str.htmlDecode(replacedElement)
        if (decodedHtml && decodedHtml !== '0') return decodedHtml;

        return replacedElement;
``` 
The original codebase is
```javascript
return Str.htmlDecode(this.replaceBlockElementWithNewLine(generatedMarkdown));
``` 

### What alternative solutions did you explore? (Optional)
If this expensify common lib should not be changed, the changes should be in setting the initial value of `welcomeMessage`of component itself `src/pages/ReportWelcomeMessagePage.js`
```javascript
    const parsedMarkdown = parser.htmlToMarkdown(props.report.welcomeMessage)
    const [welcomeMessage, setWelcomeMessage] = useState(parsedMarkdown && parsedMarkdown !== 0 ? parsedMarkdown : props.report.welcomeMessage);
```

**Comment by univalchemist** [comment]
Added video in [proposal](https://github.com/Expensify/App/issues/20783#issuecomment-1592608274)

**Comment by techievivek** [comment]
Bumping @0xmiroslav to have a look at the above proposals.

**Comment by lschurr** [comment]
Hi @0xmiroslav - looks like we're still waiting for your review.

**Comment by univalchemist** [comment]
Ok, thanks but there is a problem in decoding some characters as I showed in video, actually.

**Comment by univalchemist** [comment]
Ok, thanks. @0xmiroslav

**Comment by Beamanator** [comment]
@techievivek I'm unassigning myself b/c you were assigned here first (I think i got assigned because of the new process - C+ approving proposals)

**Comment by lschurr** [comment]
@dukenv0307 @0xmiroslav - could you apply for the job in Upwork? https://www.upwork.com/jobs/~01187aec34f1d4c1eb

**Comment by lschurr** [comment]
@dhanashree-sawant could you also apply for the job in Upwork for the reporting bonus?

**Comment by dhanashree-sawant** [comment]
Thanks @lschurr, if possible, can you invite me to the job?

**Comment by lschurr** [comment]
@dhanashree-sawant could you include your Upwork profile here so that I can invite you to the job?

**Comment by dhanashree-sawant** [comment]
Hi @lschurr, Thanks. 
My profile link: https://www.upwork.com/freelancers/~016c7b8ae165dc0bda

**Comment by lschurr** [comment]
All paid and closed :)
