### ISSUE TITLE
Feature branch QA payment issue

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20799]
In this branch https://expensify.slack.com/archives/C01GTK53T8Q/p1686587441593309 we have asked contributors to test on a feature branch before we merge this to main https://github.com/Expensify/App/pull/20473

The reward has been halved since this is a feature branch and there was supposed to be a lot of bugs but this will help us find them sooner than if only engineers test the app.

The rewards is $125 per one valid reported bug.

they should all be fixed in this PR https://github.com/Expensify/App/pull/20473

cc @Beamanator

**Comment by Beamanator** [comment]
Already created this one for this purpose: https://github.com/Expensify/App/issues/20757

So feel free to close whichever one you want haha

**Comment by mountiny** [comment]
Clsoing in favour of https://github.com/Expensify/App/issues/20757
