### ISSUE TITLE
User name show shown in new user details tooltip

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a 1-1 report with a user that has a username
2. In the report header, hover over username - notice it displays username in tooltip
3. Now hover over user avatar - notice it doesn't display username in tooltip
4. Also notice default avatars in tooltips are different

## Expected Result:
The user details tooltip should show username in avatar & if default avatar, avatars should be the same

## Actual Result:
There is no username in user details tooltip & for default avatars, avatars are different

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686831732424279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Looks like we already have a PR merged for https://github.com/Expensify/App/issues/20801

**Comment by twisterdotcom** [comment]
Issue already closed. Payments being dealt with from here: https://github.com/Expensify/App/issues/20822#issuecomment-1600868439
