### ISSUE TITLE
[HOLD] Chat - Link preview does not appear except google.com

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/17288
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any chat
3. Send any link

## Expected Result:
Link preview appears

## Actual Result:
Link preview does not appear except google.com

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/85f8d6d2-d822-4b40-806a-c9f7491bc31a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Appause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139a876cca4721bb4</li>
        <li>Upwork Job ID: 1669387928143917056</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by flodnv** [comment]
Not a blocker because it's a brand new feature, discussed here: https://expensify.slack.com/archives/C01GTK53T8Q/p1686845846653239?thread_ts=1686840921.260039&cid=C01GTK53T8Q

**Comment by marcaaron** [comment]
Not a deploy blocker.

**Comment by marcaaron** [comment]
@wojtus7 will check the backend for this to see if we need a change there or if there's some other reason this is not working.

**Comment by marcaaron** [comment]
Hmm so on first blush... this is working for me fine locally. 

![2023-06-15_07-19-15](https://github.com/Expensify/App/assets/32969087/33c6e477-09a1-4ffb-bc63-26f28d7b5db1)

But the behavior is different on staging 🤔 which makes me think that we are just getting rate limited as we are still testing on the free tier usage. For now, I will add some more logs.

**Comment by marcaaron** [comment]
Oh yes the soft limit is only 50 requests per day LOL we would break that in 0.00001 seconds.

**Comment by marcaaron** [comment]
Still on my list to look into.

**Comment by marcaaron** [comment]
Still setting up the accounts.

**Comment by MonilBhavsar** [comment]
@marcaaron we're not now seeing link previews for other sites except google. Seems like this issue is fixed? cc @hungvu193

**Comment by marcaaron** [comment]
Hmm can you clarify what exactly you are seeing? Like what platform are you testing on? Show me what you did?

To give an update - the rate limiting issue should be fixed now. But we might have CSP issues to look into on web since we are loading images and content that are outside our domain.

**Comment by MonilBhavsar** [comment]
Sorry, I mean link preview for other sites(except google is seen). I tested right now on production and it worked!

<img width="1353" alt="Screenshot 2023-07-18 at 2 58 14 PM" src="https://github.com/Expensify/App/assets/32012005/94c48d82-567a-4847-84cb-a43581213d02">

**Comment by marcaaron** [comment]
I think we can close this one out then?
