### ISSUE TITLE
[HOLD for payment 2023-06-28] [HOLD for payment 2023-06-21] Update the dismissModal to work with multiple pages in the RHP stack

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20834]
### Problem

Related to  https://expensify.slack.com/archives/C01GTK53T8Q/p1686126333958959

Now the dismissModal does not work well if there is multiple pages in the RHP stack to be popped.

### Why is it important

Its not universally working well.

### Solution

Lets ensure that when we are requesting money for example, we close the RHP modal and on clicking browser back button we are not navigated back to the request money flow.

@Tushu17 is a reporter https://expensify.slack.com/archives/C049HHMV9SM/p1686230588336239

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cc3cbba001fa0d0</li>
        <li>Upwork Job ID: 1669364724974063616</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by WoLewicki** [comment]
Commenting

**Comment by mountiny** [comment]
Maybe good one to focus on now

**Comment by WoLewicki** [comment]
Isn't it resolved by https://github.com/Expensify/App/pull/20815?

**Comment by Tushu17** [comment]
Hey @mountiny, I'm coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1687248582279399?thread_ts=1686230588.336239&cid=C049HHMV9SM). I had reported an issue on Slack ([here](https://expensify.slack.com/archives/C049HHMV9SM/p1686230588336239)) around a week before this issue was created. It seems like the PR for this issue has fixed that as well so I think I'm eligible for reporting compensation.

**Comment by mountiny** [comment]
Updated the op and I agree this should be fixed by the PR

@Christinadobrzyn I think there is nothing to wait for here in terms of reporting payment, could you please pay @Tushu17 $250 for reporting this issue?

**Comment by Christinadobrzyn** [comment]
Sounds good! Hired @Tushu17 in Upwork. 

Internal job: https://www.upwork.com/ab/applicants/1669364724974063616/job-details
External job: https://www.upwork.com/jobs/~013cc3cbba001fa0d0

**Comment by Christinadobrzyn** [comment]
Paid @Tushu17 

@mountiny do we need a regression test?

**Comment by mountiny** [comment]
@Christinadobrzyn I think we could add a regression step for this:

1. Open settings in the Settings
2. Navigate to Profile
3. Navigate to Contact Methods
4. Open the shortcuts modal using CMD + J
5. Hit ESC
6. Verify it closes the Keyboard modal
7. Hit ESC again
8. Verify it closes the RHP too

**Comment by Christinadobrzyn** [comment]
Regression test created - https://github.com/Expensify/Expensify/issues/295388

Closing this!
