### ISSUE TITLE
 Black background behind keyboard can be seen when keyboard closes

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Tap on fab icon > new chat
2. Scroll

## Expected Result: 
You shouldn't see the black background.
## Actual Result: 
Black area behind the keyboard can be seen briefly

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5b0f8c4b-4600-4ad9-8ffc-3ac173a9429c

https://github.com/Expensify/App/assets/43996225/61aea4a3-5e15-466a-ae1e-27ebd8960abf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1686286129368869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
This was already previously reported and determined it would not move forward. 
https://github.com/Expensify/App/issues/18906

@kavimuru you were on that previous GH as well where that was determined.
