### ISSUE TITLE
[HOLD for payment 2023-07-14] Update the subheader UI and enable parent navigation for all report types

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#20844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened
![image](https://github.com/Expensify/App/assets/30609178/3b87802a-dd01-4a66-8795-be2814a0512a)
![image](https://github.com/Expensify/App/assets/30609178/86d48656-ded5-4f33-b854-7533b0b52a0c)

Task header should now:
- Show the creator as the profile picture, and if it was created within a workspace room show the workspace icon
- The header title will now be the task title
- The header will include a parent link in the header 

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01647f0a8e4c9ca872</li>
        <li>Upwork Job ID: 1669462551278919680</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Handling this so we can hopefully get a merge today or tommorow

**Comment by thienlnam** [comment]
After the conversation here: https://expensify.slack.com/archives/C04QEB4MJEQ/p1686808640587439 this issue is now for updating the header for all report types - @chiragsalian will be taking this on! thank ya

**Comment by chiragsalian** [comment]
screenshot for reference
![image](https://github.com/Expensify/App/assets/14356145/7da017e2-ed9f-475b-bad2-8a2e276982e5)

**Comment by chiragsalian** [comment]
I'm not sure for workspace request and thread workspace, why we would want to show,
```
From <parent report name> in <workspace name>
```
This results in workspace showing up twice like,
```
From Duraflame owes $38.05 in Duraflame
```
I'll confirm with tom tomorrow.

**Comment by chiragsalian** [comment]
As [commented](https://github.com/Expensify/App/issues/22351#issuecomment-1624087240) there, i don't think the reported regression was due to the changes here. That regression issue would have occurred even without the code changes here.

**Comment by sonialiap** [comment]
@chiragsalian @0xmiroslav This issue didn't automatically get assigned a price, does $1000 sound fair for the work?

The PR was on feature freeze so if we count from the day the freeze was removed to Miroslav's review, we have 3 days, so by my count the bonus applies. Once the base price for this issue is determined, I will send offer and issue payment with the bonus

**Comment by sonialiap** [comment]
@chiragsalian can you please check if the PR on this issue caused the regression?

If there are no objections then I'll price this issue as base $1000 (+/- if there was a regression/bonus)

**Comment by sonialiap** [comment]
@0xmiroslav has the payment issue been resolved? Can we issue payment?

**Comment by sonialiap** [comment]
@0xmiroslav has your payment issue been resolved?

**Comment by sonialiap** [comment]
Sounds good. Please reopen once you're ready to be paid so that the issue is back on my todo list.
