### ISSUE TITLE
Chat - Broken multiple Emoji icons

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Hover over a text or attachment on the chat
2. move to Add reaction button
3. Click on the Add Reaction button
4. Look at Smiley_face_with_tears emoji icon/image, also disguised_face  and more than 20 others

## Expected Result:
Smiley_face_with_tears icon/ image to be seen.

## Actual Result:
it is just broken icon/image.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.25.7

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50b24a11-0d35-425c-9159-e52ccccedadf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Amnex-08

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686229620862939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
Looks like Window's issue. Unicode for emojis might not be available for windows

**Comment by mallenexpensify** [comment]
Tested on Windows, Edge 13(?) via Browserstack and wasn't able to repro. 
<img width="255" alt="image" src="https://github.com/Expensify/App/assets/22508304/294d9bfc-c186-4011-ac25-9b65a6a9888c">

<img width="392" alt="image" src="https://github.com/Expensify/App/assets/22508304/8f7b6eaf-db4a-4c5b-a652-70065878face">

@Amnex-08, what OS are you on?

**Comment by Amnex-08** [comment]
*I am on Windows 10 version 22H2 and using Google Chrome version 9 Version
114.0.5735.134 (Official Build) (64-bit).*

**Comment by Amnex-08** [comment]
Contributor details
Your Expensify account email: amani.mulu@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/~01d187c1cb0be7fb95)

**Comment by mallenexpensify** [comment]
@kbecciv , can you test to see if you can reproduce?
> I am on Windows 10 version 22H2 and using Google Chrome version 9 Version
114.0.5735.134 (Official Build) (64-bit).*

**Comment by mallenexpensify** [comment]
@kbecciv , can you please test again?

**Comment by kbecciv** [comment]
@mallenexpensify I will do it tomorrow, sorry for delay.

**Comment by kbecciv** [comment]
@mallenexpensify Unable to reproduce it with build 1.3.33.4

https://github.com/Expensify/App/assets/93399543/6284a046-398f-4362-8ea5-61fae736c7e6

**Comment by mallenexpensify** [comment]
K, gonna close then, comment/reopen if disagree

**Comment by lanitochka17** [comment]
Issue reproducible on Windows10/Chrome
Build 1.3.72-9


https://github.com/Expensify/App/assets/78819774/efc1def1-50e4-402f-a1be-d54893a13ce4

![Bug6208959_1](https://github.com/Expensify/App/assets/78819774/e64ee299-8f62-4a69-9d03-860727c4bf77)

**Comment by mallenexpensify** [comment]
Thanks for reopening @lanitochka17 I'm going to put on hold pending the below, since it's a Windows-emoji related issue
- https://github.com/Expensify/App/issues/21923

**Comment by mallenexpensify** [comment]
Still held on 
- https://github.com/Expensify/App/issues/21923

**Comment by mallenexpensify** [comment]
on hold

**Comment by mallenexpensify** [comment]
PR for issue this is held on is up for review
- https://github.com/Expensify/App/pull/30201

**Comment by mallenexpensify** [comment]
Above PR is moving along

**Comment by mallenexpensify** [comment]
Off hold, [the PR](https://github.com/Expensify/App/pull/30201#issuecomment-1805968344) hit production 4 days ago. 

@lanitochka17 can you see if you're able to reproduce the bug on Windows? I don't have a PC available (and using BrowserStack takes a bit, if/when possible)

**Comment by lanitochka17** [comment]
@mallenexpensify Hello 
Issue is not reproducible on the latest build 1.4.0-1
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/f291e33a-fb6e-4aee-a19c-d538ade1e040

**Comment by mallenexpensify** [comment]
Thanks @lanitochka17 , going to close then since it's not reproducible
