### ISSUE TITLE
[$1000] IOS - Attachment - In a group add attachment with option Take a photo and reply in a thread and write something - Exit to main screen - some place remains empty (like keyboard size)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app
2 Go to any group
3 Add attachment > Take a photo
4 To that taken photo - reply in a thread > write something
5 Exit to main screen

## Expected Result:
All Screen visible properly

## Actual Result:
Some parts of screen remains empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/323115f7-cf6b-441d-8b6b-bd7cb5fafa63

![photo_2023-06-08 19 42 25 (1)](https://github.com/Expensify/App/assets/93399543/bf04f35c-5259-480b-bca3-30ccf13eda62)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686235105185539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfc2ce47374b6567</li>
        <li>Upwork Job ID: 1669729990446116864</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Hm, I'm not able to reproduce this in iOS.

**Comment by narzullome** [comment]
@lschurr just to mention just now  I am able to reproduce by the steps which is written above  
iOS version 16.5 
Device name iPhone 12 Pro Max
latest version on testflight v1.3.28-5

**Comment by lschurr** [comment]
Looks like a few others were able to reproduce in the Slack thread as well. Going to add External.

**Comment by ritik-kansal** [comment]
Hi, Does this issue occur even if we "upload from gallery"

**Comment by narzullome** [comment]
> Hi, Does this issue occur even if we "upload from gallery"

Yes

**Comment by tungmt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - Attachment - In a group add attachment with option Take a photo and reply in a thread and write something - Exit to main screen - some place remains empty (like keyboard size)

### What is the root cause of that problem?
I found that this is problem of KeyboardAvoidingView. When you back to previous screen by swipe to go back, the KeyboardAvoidingView keep the padding bottom as the height of previous keyboard.

Video of issue

https://github.com/Expensify/App/assets/7497751/c25fdf7e-45c1-4c36-a623-a3598578e000


### What changes do you think we should make in order to solve the problem?
We can disable KeyboardAvoidingView when the keyboard is hidden, and enable KAW when the keyboard is shown.

Update file: src/components/KeyboardAvoidingView/index.ios.js
``` diff 
+	const [enabled, setEnabled] = useState(false)

+	useEffect(() => {
+		const showSubscription = Keyboard.addListener('keyboardWillShow', () => {
+			setEnabled(true)
+		})

+		const hideSubscription = Keyboard.addListener('keyboardWillHide', () => {
+			setEnabled(false)
+		})

+		return () => {
+			showSubscription.remove()
+			hideSubscription.remove()
+		}
+	}, [])

    // eslint-disable-next-line react/jsx-props-no-spreading
+    return <KeyboardAvoidingViewComponent {...props} enabled={enabled} />;
-    return <KeyboardAvoidingViewComponent {...props} />;
```

Video of working

https://github.com/Expensify/App/assets/7497751/7036d184-2559-4adb-9cdb-9e947e6f7a4b



### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
Looks like we have some proposals to review @mananjadhav.

**Comment by mananjadhav** [comment]
I'll try to reproduce this and then review the proposal.

**Comment by lschurr** [comment]
Still not able to reproduce @mananjadhav? If so, we should close.

**Comment by mananjadhav** [comment]
I will be attempting once again today.

**Comment by tungmt** [comment]
@mananjadhav here is step to reproduce it - in iOS native
1. Open app
2. Go to any group
3. Add attachment > Take a photo. Or just select any Reply Thread (important that in this screen dont open keyboard)
4. To that taken photo - reply in a thread > write something (open keyboard in this screen)
5. Quickly swipe left twice to back to main screen. You will see the issue.

**Comment by tungmt** [comment]
> I haven't been able to reproduce this. Thanks for the proposal @tungmt, and I have some questions.
> 
>     1. What do we mean by  `problem with KeyboardAvoidingView`. Isn't the component supposed to take care of this? The reason is because, if the scope is limited to this screen, then I don't think adding enabled is a good idea. Also if the component itself is problematic, why not fix upstream?
> 
>     2. `When you back to previous screen by swipe to go back`, is it true for this cause? Why is it only being reproducible in threads.

Hi @mananjadhav I spend more time to check about this case and I found this.
- When you from screen A -> go to screen B (not open keyboard) -> go to screen C (open keyboard) : all screen wrapped by ScreenWrapper (that use KeyboardAvoidingView). At this step all screen A, B, C padding bottom is set to keyboardHeight

- You swipe left to go back. Then the paddingBottom of KeyboardAvoidingView in screen B, and screen  C set to 0. However paddingBottom of screen A is remain keyboardHeight

The main cause of this is in KeyboardAvoidingView (react-native)
```diff
_updateBottomIfNecessary = async () => {
    if (this._keyboardEvent == null) {
      this.setState({bottom: 0});
      return;
    }

    const {duration, easing, endCoordinates} = this._keyboardEvent;
    const height = await this._relativeKeyboardHeight(endCoordinates);

+    console.log('------------ should set state keyboard height: ' + height + ' - current height is ' + this.state.bottom + ' - screenKey: ' + this.props.screenKey + ' ?')
    if (this.state.bottom === height) {
      return;
    }

+    console.log('------------ set state keyboard height: ' + height + ' - current height is ' + this.state.bottom + ' - screenKey: ' + this.props.screenKey)

    if (duration && easing) {
      LayoutAnimation.configureNext({
        // We have to pass the duration equal to minimal accepted duration defined here: RCTLayoutAnimation.m
        duration: duration > 10 ? duration : 10,
        update: {
          duration: duration > 10 ? duration : 10,
          type: LayoutAnimation.Types[easing] || 'keyboard',
        },
      });
    }

    this.setState({bottom: height})
  };
```

I added some log easy to see.

+ For case you press button back when you in screen C with keyboard open:

![Screenshot 2023-06-24 at 08 07 22](https://github.com/Expensify/App/assets/7497751/d91b6412-85cd-44f8-9bb3-eb9bdb6085ab)

The keyboard height of screen A is set to 260 success, then it set back to 0 when back from screen C -> screen B

+ For case you swipe left to back

![Screenshot 2023-06-24 at 08 09 19](https://github.com/Expensify/App/assets/7497751/4e0b9e42-c2ed-4575-b858-d5c1885420ef)

The action `this.setState({bottom: height})` when height is 260 is not completed before keyboard dismiss. Therefore when it try to check 
```
if (this.state.bottom === height) {
      return;
}
```
the `this.state.bottom` still 0 now. So in screen A the paddingBottom still 260, not set back to 0.

1. Yes, there is solution to fix this upstream by modify the KeyboardAvoidingView
```diff
+  keyboardHeightSetCompleted = true
  _updateBottomIfNecessary = async () => {
    if (this._keyboardEvent == null) {
      this.setState({bottom: 0});
      return;
    }

    const {duration, easing, endCoordinates} = this._keyboardEvent;
    const height = await this._relativeKeyboardHeight(endCoordinates);
-    if (this.state.bottom === height) {
+    if (this.state.bottom === height && this.keyboardHeightSetCompleted) {
      return;
    }

    if (duration && easing) {
      LayoutAnimation.configureNext({
        // We have to pass the duration equal to minimal accepted duration defined here: RCTLayoutAnimation.m
        duration: duration > 10 ? duration : 10,
        update: {
          duration: duration > 10 ? duration : 10,
          type: LayoutAnimation.Types[easing] || 'keyboard',
        },
      });
    }

+    this.keyboardHeightSetCompleted = false
-    this.setState({bottom: height})
+    this.setState({bottom: height}, () => {
+      this.keyboardHeightSetCompleted = true
+    })
  };
```

This change will allow update `this.state.bottom` when the previous `setState` is not completed yet.

So my proposal https://github.com/Expensify/App/issues/20862#issuecomment-1596183029 is workaround to solve this problem.

2. It will actually happen when you have 3 screen in stack like screen A > B > C with all wrapped by ScreenWrapper. From screen C swipe to back then screen A will has this issue.

**Comment by lschurr** [comment]
Could you review @mananjadhav?

**Comment by mananjadhav** [comment]
Was unwell and OOO, please allow me a day to check this.

**Comment by tungmt** [comment]
> I am probably not doing it fast enough, not able to reproduce this on simulator. I've requested the threads permission on my account so that I can check on my phone.

I can see it happen on simulator also, with slow swipe to back. Just need to make sure you are:
- In third screen in stack (in reply thread screen - for simulator you need to turn off "Connect Hardware Keyboard")
- keyboard is opening while swipe to back
- you dont open keyboard in second screen in stack (conversation screen)

https://github.com/Expensify/App/assets/7497751/4e01d87e-3f5b-445e-85c8-3b0c777d2e81

**Comment by mananjadhav** [comment]
Thanks for being persistent on this one @tungmt. I've tried this in 10+ chats, in different models iPhone 14, iPhone 14 Plus and iPhone 14 Pro.

@kbecciv Are you able to consistently reproduce this?

https://github.com/Expensify/App/assets/3069065/d0992634-a15b-4d38-b5b0-2d0f53679a2c

**Comment by lschurr** [comment]
@mananjadhav are we still having trouble consistently reproducing?

**Comment by mananjadhav** [comment]
Yeah as I mentioned [here](https://github.com/Expensify/App/issues/20862#issuecomment-1611538602) @lschurr. Were you able to reproduce it?

**Comment by narzullome** [comment]
@mananjadhav Can u check on real device just now I was Able to reproduce

**Comment by mananjadhav** [comment]
@narzullome @tungmt I've been trying hard to reproduce this on my physical device. Still not luck.

quick bump @kbecciv if you got a chance to reproduce it your end?

https://github.com/Expensify/App/assets/3069065/852d7717-7be1-4cc0-b573-3af5ea39cb21

**Comment by narzullome** [comment]
> @narzullome @tungmt I've been trying hard to reproduce this on my physical device. Still not luck.
> 
> quick bump @kbecciv if you got a chance to reproduce it your end?
> 
>  RPReplay_Final1688502325.MP4

@mananjadhav the steps are quite different can u check with the steps below
1 Open app
2 Go to any group
3 Add attachment > Take a photo
4 To that taken photo - reply in a thread > write something
5 Exit to main screen

**Comment by tungmt** [comment]
@mananjadhav can you reproduce this issue?

**Comment by mananjadhav** [comment]
@tungmt @narzullome Same result. 

https://github.com/Expensify/App/assets/3069065/c9dc1086-bb8d-49aa-a37d-5637450f6c60

**Comment by lschurr** [comment]
Any update here @mananjadhav?

**Comment by lschurr** [comment]
I also can't reproduce. Going to close.
