### ISSUE TITLE
[$1000] Chat - SMS domain shown in mentions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have some previous chats with phone number
2. Go to any chat
3. Start mentioning phone number

## Expected Result:
Phone number alone should be shown

## Actual Result:
Phone number is shown with expensify sms domain

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (64)](https://github.com/Expensify/App/assets/93399543/b36a73ee-0b96-447e-9414-d4da824b3f35)
![Screenshot 2023-06-08 at 9 23 57 PM](https://github.com/Expensify/App/assets/93399543/ee5a7397-0f3c-4ad4-9987-2ff4eaf3d8e7)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @abdulrahuman5196

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686239745633599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01180378586a3144b1</li>
        <li>Upwork Job ID: 1669613431669092352</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SMS domain shown in mentions

### What is the root cause of that problem?
We are not removing the sms domain from the `alternetText` here.
https://github.com/Expensify/App/blob/38fe17f8a299692966777a53f1b305419d8384c2/src/pages/home/report/ReportActionCompose.js#L465

### What changes do you think we should make in order to solve the problem?
Call `removeSMSDomain` here from the `alternetText` with `Str.removeSMSDomain(detail.login)`

https://github.com/Expensify/App/blob/38fe17f8a299692966777a53f1b305419d8384c2/src/pages/home/report/ReportActionCompose.js#L465

**Comment by bfitzexpensify** [comment]
Couple of proposals ready for review @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
@bfitzexpensify I'll post my review comments tomorrow. Need to check this further.

**Comment by Santhosh-Sellavel** [comment]
@tienifr's [Proposal](https://github.com/Expensify/App/issues/20866#issuecomment-1594440938) here look good to me. Both proposals are mostly similar, but @tienifr's proposal mentioned the highlighting of the phone number which will be missing, so we should go with them.

> (Optional) In case we want to completely eliminate the SMS domain while searching for mentions as in the above proposal, we need to remove SMS domain from detail.login here too:

I think we need to exclude the results while searching with SMS domain

C+ Reviewed
🎀 👀 🎀

**Comment by flodnv** [comment]
@puneetlath can you check this please? It has to do with mentions (and some of it came from https://github.com/Expensify/App/pull/19221)

**Comment by puneetlath** [comment]
This isn't really a bug. This is how it will have to be until we implement handles.
