### ISSUE TITLE
The "I accept the Expensify Terms of Service" checkbox not checked when retuning from step 2

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces > Bank account > Connect manually
2. Checked the checkbox first time
3. Click on "Continue"
4. After that return back to step 1(here you will see checkbox unchecked)
5. Now again continue without checking the checkbox

## Expected Result:
The "I accept the Expensify Terms of Service" checkbox should be checked after returning from step 2 and should displayed error message if unchecked

## Actual Result:
The "I accept the Expensify Terms of Service" checkbox not checked when retuning from step 2 and not throwing an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/445f33c3-a405-4930-a4a6-de86a8901990

https://github.com/Expensify/App/assets/93399543/955d24c5-87b9-4755-b760-3fe774c34e96

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686240081221059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
It's fixed in this PR https://github.com/Expensify/App/pull/20091

**Comment by luacmartins** [comment]
I agree has already been fixed in my PR. Closing.
