### ISSUE TITLE
[$1000] Web - Search - Arrow keys don’t work after page refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test website https://staging.new.expensify.com/
2. Log in
3. Press Ctrl+K for Search open
4. Type in a search query
5. Refresh page
6. Type in a search query again
7. Use the arrow keys to go through the search results

## Expected Result:
I can use the arrow keys to go through the search results after page refresh

## Actual Result:
I can't use the arrow keys to go through the search results after page refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c0a14d96-426c-4704-a517-7f36beb05699

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017143e6351525ef91</li>
        <li>Upwork Job ID: 1670908920637136896</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by anmurali** [comment]
Reproduced, added an external label

**Comment by sobitneupane** [comment]
Thanks for the proposal @hoangzinh.

> we also have arrow key events listener [ThreeDotsMenu](https://github.com/Expensify/App/blob/7b00c47ee7debf7137417ac768efe8d4c6b872d0/src/components/PopoverMenu/index.js#L51) component in the ReportScreen.

Can we navigate through items in ThreeDotsMenu with arrow? I might be missing which ThreeDotsMenu you are talking about.

**Comment by sobitneupane** [comment]
Yup. No longer reproducible.

cc: @anmurali
