### ISSUE TITLE
[$1000]  Android - Attachment - Arrows doesn't appeared when click on screen for PDF preview 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20671

## Action Performed:
1. Log in
2. Enter any chat report
3. Send one image and one pdf file
4. Click the pdf file after both are sent
5. Click anywhere inside opened modal, arrows should appear and disappear on click

## Expected Result:
Arrows should appear and disappear on click

## Actual Result:
Arrows doesn't appeared when click on screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ec53b199-a98d-4963-a99a-decc84ad778a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01098cecbb8efb5000</li>
        <li>Upwork Job ID: 1669639126904033280</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by mountiny** [comment]
from the description and given the SNH urgency for a deploy, I dont think this is a blocker. Also its not clear if this is also not reproducible in production from the steps above. User can still simple close the attachment modal and choose the other PDF.

I will demote this to a normal bug to focus on other blockers and getting the deploy out.

**Comment by mountiny** [comment]
@Skalakid Could you maybe loko at this one, it might be a regression. Temporarily removing the Help Wanted label

**Comment by Skalakid** [comment]
@mountiny @0xmiroslav I can't reproduce this bug too. But I think it can be connected to the bug that @0xmiroslav mentioned above. I found out that somewhat some props aren't passed to `BaseGenericPressable` on Android. To workaround this we can change passing only the rest of the unused props (`{...rest}`) to passing all of them at the beginning of <Pressable> component ({...props}). In this situation, scrolling PDFs starts working fine and maybe on other Android devices there won't be a problem with toggling arrows

**Comment by Julesssss** [comment]
Yeah I think so. The other issue contains the main problem we're discussing here.
