### ISSUE TITLE
[HOLD for payment 2023-07-20] Display money request reports as a card in the chat report

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#20893]
Currently, money request reports are displayed in-chat as plain text like so:
`Potato owes $535.35`

It doesn't look great. Let's change it so it is styled like a card (like individual requests) in preparation for [receipts](https://docs.google.com/document/d/1Il9y1287B6tq0FB5ziXnhBcwn-Lw-n_rSmllZ-AyUVs/edit#bookmark=id.uaha1mqlzbvx)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4227ab04073e43a</li>
        <li>Upwork Job ID: 1669636120412647424</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by Gonals** [comment]
@mallenexpensify, I just realized I forgot to add the newFeature label back when I created this. I think we just need to handle payment for the C+ reviewer

**Comment by shawnborton** [comment]
Is the payment part handled yet?

**Comment by shawnborton** [comment]
Friendly bump @mallenexpensify

**Comment by mallenexpensify** [comment]
Checking on payment formatting [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1692735645572189)

**Comment by mallenexpensify** [comment]
No payment dude, @narefyev91 is with Callstack
