### ISSUE TITLE
Details - Zip code does not shown a error message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20228 Part 3. Personal Details

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Open Settings -> Profile -> Personal details -> Home address
4. Leave all inputs empty.
5. Verify that every input has an error message

## Expected Result:
Every input has an error message

## Actual Result:
Zip code does not shown a error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (66)](https://github.com/Expensify/App/assets/93399543/cbeeed77-d0aa-4f2b-afcc-70e61415d4ed)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I agree that I think this is intentional as not all countries require a zip/ post code. 

[Confirming via Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1686923371209449)

**Comment by conorpendergrast** [comment]
I was wrong! Zip code is now a required field ([internal discussion](https://expensify.slack.com/archives/C03U7DCU4/p1664291292885699?thread_ts=1663932322.880299&cid=C03U7DCU4))

**Comment by conorpendergrast** [comment]
A little more nuanced here:
> We also discussed somewhere that when no country selected, it's treated as if selected country without postal code supported

That was introduced in [this PR](https://github.com/Expensify/App/pull/15880). So, this is not a bug!~
