### ISSUE TITLE
Workspace - Loading spinner is missing on Reimbursement page offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20350

## Action Performed:
1. Login to NewDot
2. Go offline
3. Click the Profile Avatar on top left
4. Click on Workspaces in setting in left panel
5. Choose a Workspace(if you don't have any workspace, create new workspace)
6. Choose Reimbursement

## Expected Result:
Must be showed loading spinner

## Actual Result:
Loading spinner is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/42ed7b30-2904-41e8-9a42-964be6ba8bd0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I dont think this is a bug, I think we should close this. cc @grgia from the refactoring issue, do you agreee?

**Comment by kadiealexander** [comment]
I agree. None of our offline patterns should result in a loading screen, and when I tried to reproduce this it seems to exhibit the offline behaviour I would expect. Closing for now, please reopen if you disagree.
