### ISSUE TITLE
IOS - Security - Default contact method error when closing an account open with phone number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings
2. Go to security
3. Close account
4. Write the the phone number that is the default contact method

## Expected Result:
Writing the phone number that is the default contact method should allow us to close the account

## Actual Result:
Writing the phone number that is the default contact method caused error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.319-7

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/252a5b8d-18e0-4de1-a27a-f05441b72625

**Expensify/Expensify Issue URL:**

**Issue reported by:** requested

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686242248690479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
I will review by EOD.

**Comment by isabelastisser** [comment]
I'm unable to reproduce this when entering my default contact method. For the record, mine is an email. It prompts me to close the account when I enter it in newdot.

**Comment by daveSeife** [comment]
This issue is only reproducable when your default contact method is a Phone number that is outside US. 

As the above proposal suggests, the contact method is formatted with formatPhoneNumber it will include the space, so you only texted your phone without any space, it won't pass the validation. 

Can you please review it again

**Comment by daveSeife** [comment]
Hi, @isabelastisser just following up on the review. I am still able to reproduce this, have you checked my comment? 

https://github.com/Expensify/App/assets/49120316/eb0f440f-77c5-4e74-90d8-2de3153e195b
