### ISSUE TITLE
Web - NewDot is not caching and constantly re-downloading some resources

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Sign into Newdot Web
2. Open the Network tab of the Chrome Dev Tools
3. Hover your mouse over the LHN and move it around passing over multiple chats but not clicking

## Expected Result:
Nothing should really happen

## Actual Result:
We are re-downloading a bunch of assets (jpegs, pngs ...) and they don't look cached.
It isn't a big deal at first but a lot of data is downloaded for no reason after some time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2f1f8827-e0b7-4d19-9693-41c3f4adb928

**Expensify/Expensify Issue URL:**

**Issue reported by:** requested

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686249752434809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I can't repro, asked in Slack for more detail: https://expensify.slack.com/archives/C049HHMV9SM/p1686249752434809

**Comment by greg-schroeder** [comment]
Closing per team discussion
