### ISSUE TITLE
Chat - IOU chat thread parent link looks links From <root report persons name/email> ows/paid $XXX

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20484

## Action Performed:
1. Login to NewDot
2. Open any IOU chat
3. Send message
4. Created thread to message
5. Observe parent link in the header

## Expected Result:
User assume it should be From <root report persons name/email>

## Actual Result:
Parent link looks like From <root report persons name/email> owes/paid $XXXX instead of From <root report persons name/email>
From A owes $10 instead of From A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.5

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2a08fe32-52d9-40bc-9bdc-d0a0793f3210

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is not a deploy blocker cc @grgia or @chiragsalian I assume this is expected now as that is the reportName of the parent report.

**Comment by mountiny** [comment]
Should we even close this issue?

**Comment by grgia** [comment]
I agree, pretty sure this is expected behavior

**Comment by chiragsalian** [comment]
Yup, its expected behavior for now, i.e., from non-policy chat thread it shows `From  <the rootmost report name>`. Closing issue. We will probably update this in time but for now its the design that we've chosen to go ahead with.
