### ISSUE TITLE
Dev: Payments - Console error when checking the list of supported currencies - 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app
2 Go to settings > Payments
3 Add payment method - paypal.me (If not added)
4 Check the list of supported currencies - press to the link

## Expected Result:
No console error

## Actual Result:
Console error - Failed to load resource: the server responded with a status of 404()

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/38846637-90d4-4a8f-bdb7-e8e008d049b1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686377598779909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by narzullome** [comment]
there was similar case - the bug turned out - not expensify bug - but it was reported -  #16497 for example here bug repoted to react/plaid

**Comment by narzullome** [comment]
I think can be reported to PayPal lol

**Comment by sonialiap** [comment]
Agreed, this is not an error on our end. Closing
