### ISSUE TITLE
[HOLD https://github.com/Expensify/App/pull/20762] Emoji counter is innacurate 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#20924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Comment in a public Expensify Chat room 
2. React to it with an emoji (Ideally have multiple accounts take this action)

## Expected Result:
The emoji counter should show the number of distinct accounts that reacted to to the comment 

## Actual Result:
The emoji counter is inaccurate 

## Workaround:
Ignore the inaccuracy 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.27-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** mitch@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

The SF lounge #announce room experienced this issue: https://new.expensify.com/r/8292963527436014

<img width="734" alt="image" src="https://github.com/Expensify/App/assets/36425901/27fd47e0-a350-4853-a3db-33702fb76c9d">

When @coleaeason looked at the database he noticed reactions from the same accounts getting counted multiple times:

[{"emoji":"heart","users":[{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":8505565,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":14680627,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1},{"accountID":5356024,"skinTone":-1}]}]}

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** Internal: https://expensify.slack.com/archives/CLR7QV2DN/p1686929169117319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
A

**Comment by anmurali** [comment]
Per @stitesExpensify comment, adding a [Hold] to this issue to wait for https://github.com/Expensify/App/pull/20473 to hit Staging

**Comment by tylerkaraszewski** [comment]
Was `[HOLD]` supposed to get added?

**Comment by anmurali** [comment]
https://github.com/Expensify/App/pull/20473 has gone to production though, so we can probably pick this fix back up now

**Comment by stitesExpensify** [comment]
I think this could be fixed by https://github.com/Expensify/App/pull/20762 so i'm going to put this on hold for now

**Comment by anmurali** [comment]
On hold

**Comment by stitesExpensify** [comment]
hold

**Comment by stitesExpensify** [comment]
I am no longer able to reproduce this after the GH this was on hold for was completed. Feel free to re-open if you run into this again
