### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Bank Account – Icon on the left of “secure your account” in “validate bank account” section is not turning white like others when hovered.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open "Settings".
2. Click "Workspaces".
3. Click "Bank Account".
4. Click " Connect bank account".
5. Complete all steps until you reach the last step “Validate bank account”.

## Expected Result:
 Icon on the left of “secure your account” in “validate bank account” section should turn white like others when hovered.

## Actual Result:
Icon on the left of “secure your account” in “validate bank account” section is not turning white like others when hovered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/39b9dedb-3c42-4912-93f0-47e967f04bb6

https://github.com/Expensify/App/assets/93399543/70aa4c5f-586f-4773-81a4-48d80deaa720

https://github.com/Expensify/App/assets/93399543/bfdf3cd5-8b44-424a-a1bc-6dc6729e9245

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686379821898329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9d2073930803828</li>
        <li>Upwork Job ID: 1670808482132348928</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by gadhiyamanan** [comment]
> FYI, I posted the solution earlier [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686514094021789?thread_ts=1686379821.898329&cid=C049HHMV9SM).

@allroundexperts i think only bug reporter can propose a solution in slack

**Comment by gadhiyamanan** [comment]
According to (CONTRIBUTING.md)[https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) reporter may optionally propose a solution for that job on Slack and it will be reviewed in GitHub.

**Comment by kevinksullivan** [comment]
Not overdue, C+ is assigned to review proposals

**Comment by kevinksullivan** [comment]
Hi @eVoloshchak can you provide an update on reviewing these proposals?

**Comment by eVoloshchak** [comment]
The fix is pretty straightforward, I think we should proceed with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/20932#issuecomment-1595192857)

🎀👀🎀 C+ reviewed!
cc: @kevinksullivan

**Comment by eVoloshchak** [comment]
> @allroundexperts isn't the reporter of this issue 

Ah, sorry for the confusion everyone
It is indeed against the rules to post a proposal on slack (unless you're the original reporter)

Let's proceed with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/20932#issuecomment-1595192857)

**Comment by kevinksullivan** [comment]
@eVoloshchak what's the latest here? Are we moving forward with @dukenv0307 's proposal? I also think it makes sense if that comment was out of process.

**Comment by eVoloshchak** [comment]
@kevinksullivan, yeah, let's move forward with @dukenv0307's proposal

**Comment by kevinksullivan** [comment]
Offers sent to both @eVoloshchak and @dukenv0307 in upwork!

**Comment by kevinksullivan** [comment]
Looks like we're just waiting on @marcaaron 's review to finish this out 👍

**Comment by marcaaron** [comment]
Merged 👍

**Comment by kevinksullivan** [comment]
@eVoloshchak please complete the steps above so we can pay this out on time. Thanks!

**Comment by eVoloshchak** [comment]
@kevinksullivan, I think PR was created as a draft before @dukenv0307 was assigned to the job

<img width="592" alt="image" src="https://github.com/Expensify/App/assets/9059945/e9394061-2830-404e-952a-a71e119238de">

So this was technically merged in 1 business day, since Jul 1-2 was a weekend

**Comment by kevinksullivan** [comment]
Thanks for clarifying @dukenv0307 @eVoloshchak . @eVoloshchak , I'm still waiting for you to accept the offer. Let me know once you've done so! And same for @usmantariq96 please let me know when you accept.

**Comment by kevinksullivan** [comment]
Paid @dukenv0307 !

**Comment by usmantariq96** [comment]
@kevinksullivan offer accepted with thanks.

**Comment by kevinksullivan** [comment]
Paid @usmantariq96

**Comment by eVoloshchak** [comment]
@kevinksullivan, I requested the payment via NewDot, so this can be closed now if that was the last action here

**Comment by anmurali** [comment]
Approved $1500 for @eVoloshchak based on https://github.com/Expensify/App/issues/20932#issuecomment-1638425083 and https://github.com/Expensify/App/issues/20932#issuecomment-1642014626and

**Comment by kevinksullivan** [comment]
Ah ok. I will cancel that offer and close this out.
