### ISSUE TITLE
No error on selecting the admin in workspace members page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Workspaces
2. Open a workspace > Manage members
3. Select the admin

## Expected Result:
User should see an error saying that you can't remove the admi

## Actual Result:
User don't get any error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/74898da7-d233-4571-89b0-fd07558421de

https://github.com/Expensify/App/assets/93399543/6aa752c4-dbf8-4d48-8782-aa68063d0dec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686946138481389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
I think it's a regression from https://github.com/Expensify/App/pull/20826

**Comment by ashimsharma10** [comment]
Have posted it before .
https://github.com/Expensify/App/issues/20939?fbclid=IwAR3WWjkMvOYJSvX4BHhFStWBWl-JvYRWo_ftY_Q3Wr3PGelSM7SEyAX63HY

**Comment by luacmartins** [comment]
I tested and confirm this has been solved. Closing.
