### ISSUE TITLE
[C+ payment] New group - Users' avatars appear only after some moment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Put on the FAB button -> New Group
4. Choose several users with avatar images -> Create group

## Expected Result:
Users' avatars appear immediately

## Actual Result:
Users' avatars appear only after some moment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a4402720-5b24-4b2b-83e8-262fd8421718

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
@Beamanator I _feel_ like this would be related to the personal details list changes we have been implementing... Are we aware of this bug already or does this need to be dug into?

**Comment by jliexpensify** [comment]
I can repro this on Staging v1.3.29-0, there's a 1 second delay.

@yuwenmemon I'm assuming this will be internally fixed?

**Comment by Beamanator** [comment]
Thanks for the quick fix @yuwenmemon 👍

**Comment by jliexpensify** [comment]
@Beamanator good to close this one? Or best to wait for the other PR to be deployed?

**Comment by luacmartins** [comment]
Fixed [here](https://github.com/Expensify/App/pull/20951).

**Comment by jliexpensify** [comment]
Nice, thanks @luacmartins !

**Comment by jliexpensify** [comment]
@aimane-chnaif please accept https://www.upwork.com/jobs/~01f67eb61672199f64

**Comment by jliexpensify** [comment]
Hi @flaviadefaria I am heading OOO for a few days, and all we need to do is pay @aimane-chnaif for his C+ contribution. I have already added to Upworks and am awaiting acceptance. 

Could you pay this and close the issue once completed? Many thanks!

**Comment by flaviadefaria** [comment]
Paid!
