### ISSUE TITLE
Bank Account – The form in "Additional information" appears, while checkbox is unchecked.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging app on a browser and select any workspace.
2. Click on "Add bank account" and press "connect manually".
3. Complete all the steps until you reach "Additional information" step.
4. Check the checkbox "somebody else owns more than 25% of test".
5. Fill the required fields and proceed to the next step i.e "validate bank account"
6. Go back to the previous step and verify that the form opened due to checking the checkbox "somebody else owns more than 25% of test" is still available but the checkbox is no more checked.

## Expected Result:
The form opened due to checking the checkbox "somebody else owns more than 25% of test" should have disappeared or the checkbox should have remained checked.

## Actual Result:
The form continues to appear although the checkbox causing it to appear has gone unchecked.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b31fa831-0043-4719-85ce-0cf144ab2699

https://github.com/Expensify/App/assets/93399543/bbaa912e-13e2-42ac-8376-70e51bae6c51

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686386080701919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
The other GH linked has been closed. Is this one resolved as well @hungvu193?

**Comment by lschurr** [comment]
Great, let's close!
