### ISSUE TITLE
Security - Endless spinner when try to close account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20955]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open http://staging.new.expensify.com/
2. Log into a new account (expensifail and gmail)
3. Go to Settings > Security > Close account
4. Enter default contact method
5. Tap on "Close account" button

## Expected Result:
Account should be close.

## Actual Result:
Endless spinner is diaplayed when try to close account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/14809f4d-5fdd-492e-a623-72d4b3a13854

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
`Email or phone of affected tester (no customers):`

Please fill this out. If this issue is related to the account you are using it can help us identify the cause.

**Comment by marcaaron** [comment]
I think we can make it a non-blocker as I'm unable to reproduce on staging.

**Comment by slafortune** [comment]
Not able to reproduce - closed stevielafortune@gmail.com successfully
Checking for updates
Chrome Version 114.0.5735.133 (Official Build) (x86_64)
MacOS 13.3.1 (22E261)

**Comment by slafortune** [comment]
@lanitochka17 are you able to reproduce this?

**Comment by lanitochka17** [comment]
@slafortune Not reproduce. Issue fixed

https://github.com/Expensify/App/assets/78819774/ed01ad76-eb4d-4b22-bfa8-553046a6846a
