### ISSUE TITLE
[Hold PR#25935][$1000] Android - Chat - New unread message is marked read when user reads old unread message offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: There is unread message.
1. Launch New Expensify app.
2. Disconnect network.
3. Read the unread message.
4. Return to LHN.
5. As another user on another device, send a message to app user.
6. As mobile app user, reconnect network.

## Expected Result:
The unread message will be marked unread (bold).

## Actual Result:
The unread message is marked unread for a while and then marked read (not bold).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7fcfb0b6-0e46-4de4-8d2e-b42f5162cff0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197d6914a40bd4242</li>
        <li>Upwork Job ID: 1671500870756126720</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
@fedirjh any thoughts on the proposal above?

**Comment by flaviadefaria** [comment]
Thanks for the update looking forward to your review!

**Comment by flaviadefaria** [comment]
@fedirjh do you have an update here?

**Comment by flaviadefaria** [comment]
Cool I put this on hold and added it to the tracking issue so will now switch it monthly to wait until we can revisit this.

**Comment by flaviadefaria** [comment]
Seems like the PR is still being [reviewed](https://github.com/Expensify/App/issues/15212#issuecomment-1747027283).

**Comment by flaviadefaria** [comment]
@trjExpensify I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by trjExpensify** [comment]
Cool, cool! Thankfully, this issue's history is small, but it would be helpful to give BZs you're handing over to some context on the issues you're reassigning with regards to where they're at. Similar to how people do when they go OoO and reassign.

**Comment by trjExpensify** [comment]
Updating the title of this issue to reflect the PR it's held on.

**Comment by trjExpensify** [comment]
@fedirjh is there an update on this one?

**Comment by trjExpensify** [comment]
Got it, seems like it has been in review for quite some time. There's conflicts again now FYI. :)

**Comment by trjExpensify** [comment]
Looks like C+ review is done, so hopefully next time around we can take this off hold.

**Comment by trjExpensify** [comment]
Merged, hasn't hit staging yet. @fedirjh will you be able to retest this one on Android once it does?

**Comment by trjExpensify** [comment]
Excellent. Issue was reported by Applause, closing it out.
