### ISSUE TITLE
[$1000] mWeb - Correct chat is not opened by tapping chat link from external apps

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20958]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Using Android m/Web, login to NewDot with account A and open any DM. Copy the report url from the address bar (like https://staging.new.expensify.com/r/1242891003534332
)
2. Paste it in any external app (Slack or Telegram)
3. Log in with same account (account A) in android app
4. In the android app, open any other chat (not the one you opened in step 1)
5. Go back to the external app and tap link you pasted in external app

## Expected Result:
Chat from step 1 should be opened without any visual issues.

## Actual Result:
Chat from step 4 stays on the screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3d58d3fa-b36d-4a2e-9e87-09ad2fded26c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ba3693591a9ecac</li>
        <li>Upwork Job ID: 1670800776428523520</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
This is not overdue, just reviewing now
