### ISSUE TITLE
Connect Bank Account - Checkbox is checked after returning to previous stage

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue foung when executing PR** https://github.com/Expensify/App/pull/20193
## Action Performed: 
1. Open http://staging.new.expensify.com/
2. Log into a new account
3. Navigate to Workspace > Bank Account
4. Click on "Connect manually"
5. Insert the routing number 011401533 and account number 1111222233331111
6. Check the ToS checkbox
7. Click on "Continue"
8. Click "Back" to return to previous stage
9. Click on "Continue"
10. Fill in the Company information
11. Check the "restricted business" checkbox
12. Click on "Save & Continue"
13. Click "Back" to return to previous stage

## Expected Result:
At steps 8 and 13 the checkbox is not checked

## Actual Result:
At steps 8 and 13 the checkbox is checked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3ce03af9-e47a-4869-8922-f52cc2826db8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause -Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
I think you should remove `defaultValue` and `shouldSaveDraft` or set them to false
https://github.com/Expensify/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/src/pages/ReimbursementAccount/CompanyStep.js#L259-L275

**Comment by SofoniasN** [comment]
Hey guys, I hope all is well i reported a similar bug to this a week ago. Here https://expensify.slack.com/archives/C049HHMV9SM/p1686592692164449?thread_ts=1686592692.164449&cid=C049HHMV9SM
