### ISSUE TITLE
IOS - Search - App is crashed when taping something on search results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Create a new gmail account
3. Tap on magnify glass
4. Search for user

## Expected Result:
App is not crashed

## Actual Result:
App is crashed when taping something on search results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a961a18d-3a2b-4f10-a4f2-ed928764ec59

https://github.com/Expensify/App/assets/93399543/c6050cfb-cfe9-4576-b0e4-68ee760d6650

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team/ @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686988343621529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
I believe this was related to the missing personalDetails onyx data. Also I'm no longer able to reproduce this: 


https://github.com/Expensify/App/assets/10736861/1136c1f9-c845-47aa-b04f-b90a3e7e7947
