### ISSUE TITLE
Web - Split Bill - No details shown on split bill details page of a new user (only profile picture is shown)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a group with some new users that you've not chatted before
3. Click on split bill and enter an amount
4. Notice that on the split money page , no email id or display name is shown and only the picture is shown

## Expected Result:
Details shown on split bill details page of a new user

## Actual Result:
No details shown on split bill details page of a new user (only profile picture is shown)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9b8b6bd-1898-4d49-a780-29e1a1cd2136

https://github.com/Expensify/App/assets/93399543/5fea8676-6620-41de-93cd-f928f73f9ed8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha
 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686991361366049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Gonna remove the blocker label since we've fixed this issue [here](https://github.com/Expensify/App/pull/21113?). We're still working on a polish item, but that's no longer a blocker.
