### ISSUE TITLE
[HOLD for payment 2023-06-29] [HOLD for payment 2023-06-28] Concierge - Concierge icon is not displaying in popup

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20971]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20665
## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Search for concierge
4. Hover on concierge name or avatar

## Expected Result:
User should see the concierge icon along with the email address

## Actual Result:
User only sees the email address and the icon is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6097080_Concierge_icon_is_not_displayed" src="https://github.com/Expensify/App/assets/78819774/7f5a4b0c-f99d-40b6-a71e-b337c7810faf">

https://github.com/Expensify/App/assets/78819774/f3e632aa-f4d5-421d-8501-bda60e4193d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
Agreed, should be handled in https://github.com/Expensify/App/issues/20822

**Comment by Beamanator** [comment]
Contrib has a fix up! ^

**Comment by Beamanator** [comment]
No longer a deploy blocker - fix was pushed to staging

<img width="433" alt="Screenshot 2023-06-19 at 6 05 04 PM" src="https://github.com/Expensify/App/assets/3885503/54b354e0-ec11-4938-af5e-00329d79b01f">
