### ISSUE TITLE
[$1000] Incorrect Order of Messages: User-Generated Messages Override Welcome Message as First Message in Chat Room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A
2. Click profile > create a Workspace
3. Click '+' > New Room
4. Name the room > select a workspace > Visibility - Public (everyone)
5. Click on the Room > Settings > welcome message > write message
6. Go to chat and write a chat message in the room 
7. Go to Room details > share code > copy code > send the code to User B
8. Open the room with User B and verify that welcome message is Not the first message in the room

## Expected Result: 
Welcome message should be the first message in the room as it is a greeting.  User generated messages should follow the welcome message.

## Actual Result: 
Welcome message was not the first message. User generated messages overrode it as the first message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/456edd96-e71e-4b26-80ab-5b18c4dbe9a5

https://github.com/Expensify/App/assets/43996225/dafa89ba-9b43-4d34-a225-9b399ad1d6f5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686353533877299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105c575abaff412de</li>
        <li>Upwork Job ID: 1671261595410546688</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
Looks like the comment action(welcome message) is created when `openReport` API is called first for the reportID. I think this should be fixed in backend

**Comment by arthurmfgtab** [comment]
Hey, I am from Callstack - expert contributor group
Just letting everyone know that I'll start investigating this one 🙋

**Comment by mountiny** [comment]
@arthurmfgtab Pleaase post daily updates and proposal before making a PR, thanks!

**Comment by Christinadobrzyn** [comment]
Hired in upwork
Interal job - https://www.upwork.com/ab/applicants/1671261595410546688/job-details
External job - https://www.upwork.com/jobs/~0105c575abaff412de

@avi-shek-jha reporter
@fedirjh C+

**Comment by arthurmfgtab** [comment]
Thanks for reporting, @fedirjh 
I'll check that out today :)

**Comment by arthurmfgtab** [comment]
@fedirjh regarding new welcome messages being generated every time a new user joins a workspace, well, I'm still investigating this, but this seems to be backend-related, as I don't think we created these welcome messages on the frontend side.

**Comment by pecanoro** [comment]
This is totally expected, the user should actually get the welcome message after they join! We can close it!
