### ISSUE TITLE
[$1000] Divider line is visible even if there is only one message in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20985]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Send message
3. From context menu select the `Reply In Thread`

## Expected Result: 
As there is only one message ( parent message ), there is no need to show divider line
## Actual Result: 
Divider line is visible for a single message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f960dd2c-b317-4e27-b5ab-13d5c57bee8e

<img width="957" alt="a1" src="https://github.com/Expensify/App/assets/43996225/d58da2be-17c1-4134-a794-35fac542a7d1">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686329080109869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9ba5c57be811260</li>
        <li>Upwork Job ID: 1671291940853252096</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Divider line is visible even if there is only one message in thread
### What is the root cause of that problem?
We hide divider only if it overlaps with new messages marker.
https://github.com/Expensify/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/src/pages/home/report/ReportActionsList.js#L119-L120
### What changes do you think we should make in order to solve the problem?
Add case if no replies `sortedReportActions.length === 1` to `shouldHideThreadDividerLine` condition.

```javascript
// shouldDisplayParentAction && sortedReportActions.length > 1 && sortedReportActions[sortedReportActions.length - 2].reportActionID === newMarkerReportActionID;
shouldDisplayParentAction && (sortedReportActions.length === 1 || (sortedReportActions.length > 1 && sortedReportActions[sortedReportActions.length - 2].reportActionID === newMarkerReportActionID));
```

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment]
I reproduced this bug, agree that it's weird and unexpected behavior.

**Comment by sakluger** [comment]
Based on the comment by @benjaminbennet, I'd like to get a second opinion from @Expensify/design to see if this is a bug or not.

**Comment by shawnborton** [comment]
Hm I would say this isn't a bug because we designed it to be this way. I don't feel strongly about removing it though. Thoughts @trjExpensify @JmillsExpensify ?

**Comment by trjExpensify** [comment]
Sounds good to me!
