### ISSUE TITLE
When a person enters a public room for the first time, it looks like a DM for the first couple seconds then updates to the room name.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. I go into a public room created by someone else.
 Note: only the first person to enter the room sees this.

## Expected Result:
The report name reads: Bob, Daniel (first image)

## Actual Result:
Then after a second or two it updates correctly (second image)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (1)](https://github.com/Expensify/App/assets/43996225/c450d781-cc68-4388-bfdd-7ba5655c1599)

![image](https://github.com/Expensify/App/assets/43996225/175fa2f0-1edb-4022-96fb-e6c16af46151)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686336462273589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Unable to repro on Staging v1.3.29-0 either.

Using the URL, I instantly see the room name.

**Comment by danielrvidal** [comment]
@jliexpensify you have to be the first person in the room. Did you have someone open a room and then you be the first person to enter the room?

**Comment by jliexpensify** [comment]
Yes @danielrvidal - I used my Expensify account to create a new room, which I then accessed with my Expensicorp account.

Question though: did you use the URL to access the room, or did you search in the LHN? Because I wasn't able to search for the room in my LHN, so I used the URL, which updated the name instantly.

**Comment by danielrvidal** [comment]
I used a URL but all good if you can't replicate. We changed a lot in the past few days so it might have resolved itself.
