### ISSUE TITLE
 Incomplete Member Information Displayed When Hovering Over Photos in Admin Rooms

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app settings.
2. Go to the workspace section.
3. Create a new workspace.
4. Click the three-dot icon and go to the admin section.
5. Click the header and go to members.
6. Hover over member email and photos. Only email is displayed when hovering over photos, while both name and email are displayed when hovering over email.
Note: Display name must be set in settings>profile>display name with a desired first name to reproduce.
## Expected Result: 
Hovering over member photos should display both name and email like when hovering over email.
## Actual Result: 
Hovering over member photos only displays email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (4).webm](https://github.com/Expensify/App/assets/43996225/61985bf6-f779-4510-8358-75f0283bd467)

https://github.com/Expensify/App/assets/43996225/932bee71-1d37-428b-a543-8b50e686baf3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687003462951499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
@kavimuru confirmed 👍

**Comment by tewodrosGirmaA** [comment]
Greetings @flodnv,  I believe the bug has been resolved. May I know if I am eligible for payment? Kindly inform me. Thank you.

**Comment by tewodrosGirmaA** [comment]
Thank You

**Comment by tewodrosGirmaA** [comment]
Contributor details
Your Expensify account email: israeltesema45@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0142af0eda23e59363

**Comment by tewodrosGirmaA** [comment]
Contributor details
Your Expensify account email: israeltesama45@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0142af0eda23e59363
