### ISSUE TITLE
Room - After creating the room, 504 error appeared in the console for a minute later.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20995]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing Pr** https://github.com/Expensify/App/pull/20750
## Action Performed:
1. Open http://staging.new.expensify.com/
2. Log into a expensifail account
3. Click big green + button > New room
4. Create new room
5. Check the console

## Expected Result:
The error should not appear

## Actual Result:
504 error appeared in the console for a minute later

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6097593_image__2_](https://github.com/Expensify/App/assets/78819774/415231aa-a0a4-4dbe-87ad-e7bf55c5b621)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Could not reproduce. I assume it was a temporary failure. Can you re-check please?

**Comment by kbecciv** [comment]
@iwiznia Issue is not reproductible in build 1.3.29.3

https://github.com/Expensify/App/assets/93399543/02259e8d-14f6-4e12-a183-cfcbfc9c016f
