### ISSUE TITLE
[HOLD for payment 2023-12-06] Add Light Theme Illustrations to App and create Hook for Illustrations

### ISSUE THREAD

**Issue by grgia** [Expensify/App#21017]
https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#bookmark=id.gdjmszsnmgj8

As part of this issue we will:
- Upload the light mode assets
- Create a `useThemeIllustrations` similar to `useThemeStyles` 
- Use the hook in the places where we currently use these assets

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfe5b060f911b101</li>
        <li>Upwork Job ID: 1684527012106264576</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by Shivam7-1** [comment]
Hii
I am Interested In this Project as a Freelancer How can I Contribute in it?

**Comment by Shivam7-1** [comment]
Contributor details
Your Expensify account email: shivam.tiwari00021@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01eb86a64553a3f6cd

**Comment by Shivam7-1** [comment]
How Should I contribute to project do I get assign or I have to direct work on PR

**Comment by grgia** [comment]
@Shivam7-1 if you're interested in contributing check out our jobs with the `Help Wanted` label [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+NOT+Hold+in%3Atitle+sort%3Acreated-desc+label%3ABug). For our theme switching project, we may be creating some external issues and adding the label, and you'll see them there!

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
This won't require C+ Review, sorry for the ping @parasharrajat

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
Hey @dannymcclain I just want to double back on this issue and confirm which illustrations/PNGs we need to switch out for light mode. And also get the files for that.

Right now, the main illustrations from the [original DD section](https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#bookmark=id.gdjmszsnmgj8) are:
- empty state background 
- QR code icon
- Example Check images
(You can see these in the DD) 

Can you confirm if there are any other illustrations (specifically PNGs) we may need to swap on light versus dark

**Comment by grgia** [comment]
@dannymcclain could we get the light mode version of just this one to start?

`assets/images/empty-state_background-fade.png`





<img width="1315" alt="image" src="https://github.com/Expensify/App/assets/38015950/ea2d37fe-05ac-49bb-a7fa-f85d089a3544">

**Comment by dannymcclain** [comment]
Yes sorry! This issue kinda slipped through the cracks for me. I'm working on tracking down the vector version of that image so I can update it for light mode.

**Comment by dannymcclain** [comment]
Ok try this one: [empty-state_background-fade-light.png.zip](https://github.com/Expensify/App/files/13379783/empty-state_background-fade-light.png.zip)

![empty-state_background-fade-light](https://github.com/Expensify/App/assets/7516624/9d4e42f0-ff86-4ff0-820e-42739aa1f94e)

**Comment by grgia** [comment]
@dannymcclain could we get the same one with a transparent background?

**Comment by dannymcclain** [comment]
Yup! Sorry about that. [empty-state_background-fade-light2.png.zip](https://github.com/Expensify/App/files/13380034/empty-state_background-fade-light2.png.zip)

![empty-state_background-fade-light2](https://github.com/Expensify/App/assets/7516624/fd491fe1-932f-48cd-b2c1-5e1ab201a191)

**Comment by chrispader** [comment]
@grgia just create a PR which implements theme dynamic illustrations and adapts all components that use illustrations 🚀 

https://github.com/Expensify/App/pull/31452

**Comment by chrispader** [comment]
> Yup! Sorry about that. [empty-state_background-fade-light2.png.zip](https://github.com/Expensify/App/files/13380034/empty-state_background-fade-light2.png.zip)

the empty state background is also already included in the PR :)

**Comment by shubham1206agra** [comment]
Commenting here as C+

**Comment by dannymcclain** [comment]
@grgia Sorry, our Figma variables weren't updated when I exported the previous check images. Here are the _real_ updated check images for light and dark mode: [UPDATED Example Check Images.zip](https://github.com/Expensify/App/files/13588318/UPDATED.Example.Check.Images.zip)

**Comment by dannymcclain** [comment]
For posterity: 
[Transparent 800x192 Check Images.zip](https://github.com/Expensify/App/files/13589455/Transparent.800x192.Check.Images.zip)

**Comment by dannymcclain** [comment]
Not overdue Melvin. @grgia anything else you need from me for this?

**Comment by shubham1206agra** [comment]
@grgia Is this not eligible for payment?

**Comment by grgia** [comment]
@Christinadobrzyn could you help me out with the $500 C+ Review payment to @shubham1206agra for https://github.com/Expensify/App/pull/31452

**Comment by Christinadobrzyn** [comment]
Payouts due:

Issue Reporter: NA
Contributor: NA
Contributor+: $500 @shubham1206agra 

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~017d8d1f210a013003).

@shubham1206agra can you accept the job offer and I'll pay you through Upwork? (let me know if you are paid through NewExpensify instead)

**Comment by shubham1206agra** [comment]
@Christinadobrzyn Offer accepted

**Comment by Christinadobrzyn** [comment]
Awesome! thanks! I paid you in Upwork based on this payment summary https://github.com/Expensify/App/issues/21017#issuecomment-1861754222

Closing!
