### ISSUE TITLE
[HOLD for payment 2023-07-24] Create theme/styling hooks and context components

### ISSUE THREAD

**Issue by grgia** [Expensify/App#21019]
https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#bookmark=id.i5bkr5mf4hlp

**Comment by chrispader** [comment]
any comment

**Comment by Santhosh-Sellavel** [comment]
@grgia Assign me to the issue, thanks!

**Comment by grgia** [comment]
@garrettmknight could you help with $1000 C+ review payment for @Santhosh-Sellavel's review of https://github.com/Expensify/App/pull/21667

**Comment by Santhosh-Sellavel** [comment]
Will collect via new dot.

**Comment by garrettmknight** [comment]
Contributor+: @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
Request $1K on ND

**Comment by JmillsExpensify** [comment]
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by garrettmknight** [comment]
That's the only payment for this issue so we're good to close.
