### ISSUE TITLE
[HOLD for payment 2023-09-27] Add New Light Theme Colors to App

### ISSUE THREAD

**Issue by grgia** [Expensify/App#21016]
https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#bookmark=id.h9qka5vcpa4g
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016682f4a48205905e</li>
        <li>Upwork Job ID: 1687133226756259840</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by grgia** [comment]
Will work on this this week

**Comment by grgia** [comment]
Sorry for the ping, didn't mean to add the new feature request label

**Comment by grgia** [comment]
@muttmuure silly me, I removed your auto-assignment but forgot about C+ payment (of internal PR) to @allroundexperts. Would you mind helping with the payment?

**Comment by grgia** [comment]
friendly bump :)

**Comment by grgia** [comment]
^

**Comment by muttmuure** [comment]
On it!

**Comment by muttmuure** [comment]
@allroundexperts  C+ - $1000 

Is that right?

**Comment by muttmuure** [comment]
Invite sent to Sibtain

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @allroundexperts based on BZ summary.
