### ISSUE TITLE
Payment issue for E/App PR#18711

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#21025]
Issue created to compensate the Contributor+ member for their work on https://github.com/Expensify/App/pull/18711
There's no issue linked to the PR, which is why I'm creating this
Contributor+ member who reviewed the PR - @0xmiroslav.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010260c8f6f3b5427f</li>
        <li>Upwork Job ID: 1670746495024205824</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
PR came from this slack convo: https://expensify.slack.com/archives/C01GTK53T8Q/p1683719211068359

**Comment by anmurali** [comment]
Sent offer. I think $1000?

**Comment by anmurali** [comment]
Paid
