### ISSUE TITLE
Mirrored requests show negative amounts and appear to have been paid

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#21034]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. A send money request to B
2. Then B send money request back to A (with same amount - maybe)
3. Repeat step # 1 and # 2 few times

## Expected Result:
The requests should be send successfully

## Actual Result:
Negative expenses are shown as paid

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.29-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686888946305709?thread_ts=1686888687.225899&cid=C049HHMV9SM) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687153289980589)

![image (1)](https://github.com/Expensify/App/assets/10736861/b362b72b-a286-4a70-8c68-b92488738ae7) ![image (2)](https://github.com/Expensify/App/assets/10736861/78bdf7fb-9292-4442-8e49-05b0d52db312)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@Julesssss @tranvantoan-qn, I'm having trouble reproducing, any tips?
I did notice that the +/- signs took a few seconds to flip/switch.  

https://github.com/Expensify/App/assets/22508304/97dd28ca-bc80-4969-b5b5-3cd2ca22de6b

**Comment by tranvantoan-qn** [comment]
@mallenexpensify: In your video, it shows negative amounts and appears to have been paid already?

**Comment by mallenexpensify** [comment]
@Julesssss can you clarify or expand the OP? 
> Expected Result:
The requests should be send successfully

I'm unsure exactly what this means. Can you reference my vid above too, if there's a bug?

**Comment by Julesssss** [comment]
so I don't see the negative request bug... but here are the potential issues I can see: 

**1)**  Sending request of equal amount 'settles' the request (the tick shows on IOUs and the preview header)
- I believe this is expected based on our old implementation. Will double check this though

**2)** But, ^ the request still shows in the LHN as unpaid, and the report preview still shows 'x owes £0.00'
- This seems inconsistent. We should align issues 1 & 2 I think

**3)** Both the LHN chat and thread show 'paid £5.00 elsewhere', which is confusing
- I think this is being handled with our planned thread improvements

**Comment by mountiny** [comment]
>  Sending request of equal amount 'settles' the request (the tick shows on IOUs and the preview header)

I think the report preview should just show $0 and we should do nothing about it until people send more requests and pay or delete the requests. I think this is just an edge case we are talking about but if it happens in real life people wont be worried about the $0 amount.

> 2) But, ^ the request still shows in the LHN as unpaid, and the report preview still shows 'x owes £0.00'

I think this is fine, we should just give them ability to "pay this" to settle it but also any other request will add to that report and make it different from 0.

**Comment by Julesssss** [comment]
Okay so actually I think this is expected behavior. As the requests are equal it is effectively paid. Going to close this issue.
