### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-29] Web - Split Bill - Details page is shown empty for old group chat splits

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any old group chat where you splitted the bill (Important- split bill report)
3. Click on it and notice that details page is empty
4. But if you split the bill now in the same group and then click on the split bill report, you'll be able to see the details without any problem. Thus the problem occurs for old split bills and not the new ones.

## Expected Result:
 Details page should be not shown empty for old group chat splits

## Actual Result:
 Details page is shown empty for old group chat splits

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b620810-19eb-4044-9120-6b4c0f94dafb

https://github.com/Expensify/App/assets/93399543/29033e53-6d25-42f3-9c91-a02928c360dc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687167180014059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01034e11a536cbe311</li>
        <li>Upwork Job ID: 1673377762610040832</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment]
I chatted with Alex. B about this and it seems like we didn't migrate the database data. I'll try to prepare a CQ query to migrate.

**Comment by luacmartins** [comment]
Removing the blocker label as per [this comment](https://expensify.slack.com/archives/C05E4M0QHLY/p1687297587873459)

**Comment by luacmartins** [comment]
This was fixed, CPed and deployed to prod. No payments are due. Closing.

**Comment by priya-zha** [comment]
@luacmartins I'm the external reporter for this issue.

**Comment by luacmartins** [comment]
Sorry, I missed that @priya-zha. Reopening and adding Bug label to get payment sorted out.

**Comment by luacmartins** [comment]
@johncschuster we just need to pay the reporting bonus to @priya-zha

**Comment by johncschuster** [comment]
Thanks for the callout, @luacmartins! I'll have a job created so I can pay the reporting bonus.

**Comment by johncschuster** [comment]
Sorry for the ping, @mollfpr. I applied the `External` label just to create the Upwork job to pay the reporting bonus.

**Comment by johncschuster** [comment]
@priya-zha, can you apply for the job above?

**Comment by priya-zha** [comment]
@johncschuster proposal submitted. thanks

**Comment by mentamarindos** [comment]
Hello, I've seen this on Upwork and wanted to make sure it's legit. Are you really paying a thousand dollars to fix this bug?

**Comment by lealobanov** [comment]
Contributor details
Your Expensify account email: lea.lobanov@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0187e5647dc5b9d97e

**Comment by phoenixdevguru** [comment]
Hi team! I want to contribute this issue. Is it possible for me or did I miss the train @MelvinBot?

**Comment by phoenixdevguru** [comment]
Contributor details
Your Expensify account email: legendary.phoenix.icarus@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0174df7a166fa24c54

**Comment by johncschuster** [comment]
Hi @phoenixdevguru, this issue has already been resolved. We're just working on issuing payment to the bug reporter.

**Comment by johncschuster** [comment]
Payment has been issued! I think we're good to close this out.
