### ISSUE TITLE
[$500] [Hold for #16364]Chat - Mention list is dismissed on ESC click to close keyboard shortcut popup (works fine for other shortcuts)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write @ to open mentions list
4. Click CTRL+J to open keyboard shortcut popup
5. Click ESC to close popup and observe that mentions list is now not displayed even though compose box has focus
6. Try similarly with CTRL+K and CTRL+shift+K to observe that mention list remains open for other shortcuts

## Expected Result:
App should display mention list if text is eligible for mention and compose box is in focus

## Actual Result:
On ESC click to close keyboard shortcut popup, mention list is not displayed even though compose box has eligible text and compose box is in focus.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/03211524-56c4-477a-862d-15d27161f9f8

https://github.com/Expensify/App/assets/93399543/1b283931-45c3-4e3a-bd5d-da5557f6bf41

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686474692215229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae198061873956a3</li>
        <li>Upwork Job ID: 1706296536217116672</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Same root cause with https://github.com/Expensify/App/issues/16364

**Comment by NicMendonca** [comment]
@bernhardoj are you saying that once https://github.com/Expensify/App/issues/16364 is fixed, this should as well?

**Comment by bernhardoj** [comment]
Yes, but it's currently on hold for inline suggestion, so we can hold this one too.

**Comment by NicMendonca** [comment]
Still on hold

**Comment by NicMendonca** [comment]
Still on hold

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
same ^^

**Comment by NicMendonca** [comment]
^^ same update

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
^^

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
same update -- https://github.com/Expensify/App/issues/16364 still on hold

**Comment by NicMendonca** [comment]
same update ^^

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/16364 still on hold
