### ISSUE TITLE
[$1000] Username is not updating after renaming

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send money from account A to account B
2. Go to account B and open the IOU thread and click on the IOU card to open the details thread
3. Go to account A and open the IOU thread and click on the IOU card to open the details thread
4. Go to account B and send a message in the details thread
5. Go to account A and observe the LHN
6. Go to account B and rename the account user name
7. Go to account A and observe both the LHN and the username of account B

## Expected Result: 
The new user name of account B should be updated on account A.
## Actual Result: 
The renamed user name of account B is not being updated on account A.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ee93b135-99f9-460d-b113-6ad1521da2c4

https://github.com/Expensify/App/assets/43996225/85fd2e2d-4360-4cef-937b-9988744c9aa7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686305308623989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ad216749dcd0920</li>
        <li>Upwork Job ID: 1671504157890416640</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
External label added

**Comment by flaviadefaria** [comment]
@fedirjh what are your thoughts on this issue?

**Comment by flaviadefaria** [comment]
Same here, so closing this GH.
