### ISSUE TITLE
Delay in displaying user name in LHN when replying on a thread message 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a User2 chat
2. Send a message to User2
3. Click on "Reply in thread" option
4. Open User2's account and open the chat with User1
5. Click on the thread message sent by User1
6. Check the LHN for the thread message with User1's account
## Expected Result: 
The user name should be instantly displayed in the LHN along with the sent message
## Actual Result: 
There is a delay in displaying the user name when User2 replies to the thread message in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4d15d955-6ba8-4825-b61c-fe65870b4409

https://github.com/Expensify/App/assets/43996225/18cd952e-faa0-4632-b420-1a994f6e1382

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686309168445669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I'm not sure what the problem is here, I am not seeing a delay. Please reopen if there is a clearer way to reproduce this

**Comment by ayazhussain79** [comment]
@muttmuure You can see in this video when userB reply on thread userA's account LHN (UserB : hello from user B) "UserB :" Showing after refreshing page


https://github.com/Expensify/App/assets/56740856/52bf9865-681d-4979-9a6d-d92aed91944f

**Comment by muttmuure** [comment]
@ayazhussain79 I'm not sure what you're showing me here

**Comment by muttmuure** [comment]
Could you write out a series of steps if there is another way to reproduce the bug

**Comment by ayazhussain79** [comment]
Please try these steps:

1. Open a UserB chat from UserA account
2. Send a message to UserB
3. Click on "Reply in thread" option and send a message 
4. Open UserB's account and open UserA chat
5. Click "Reply in thread" on message sent by UserA
6. Send a message on thread from UserB
7. Now you have to check UserA LHN 

if userB sent a message in thread like"Hello"  you will see from userA account in LHN last message "Hello"
when you refresh the page last message will be "UserB:Hello"

**Comment by ayazhussain79** [comment]
@muttmuure have you tried these steps: https://github.com/Expensify/App/issues/21056#issuecomment-1607402531

**Comment by muttmuure** [comment]
@ayazhussain79 I'll give it another try when I'm back online tomorrow. Thanks for the extra steps

**Comment by muttmuure** [comment]
Github is having some real problems uploading the gif/video I have of this. 

It looks like this is fixed, I'm not able to reproduce it and there is no delay. 

<img width="338" alt="image" src="https://github.com/Expensify/App/assets/46995600/d823a3d5-2afa-49d0-aa98-03e98dc861c8">

If you are able to find a PR that fixed this issue reported somewhere else, and you were the first to report it, please add it here and I'll see if you're eligible for a bug bounty.
