### ISSUE TITLE
 Deep links are not working when user is signed out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out from the app.
2. Keep the app in background. Don't force kill.
2. Tap on a deep link from New Expensify. ( QR code link, Chat link etc)
3. User is navigated to sign in page.
4. After authentication user is navigated to LHN screen.

## Expected Result:
User should be navigated to the screen corresponding to the deep link that was tapped on.

## Actual Result:
Deep link is not honoured when user is not authenticated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-8

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d842820-ab51-4f76-a3b2-29aa6061f3de

https://github.com/Expensify/App/assets/93399543/f789d484-df7a-434f-b362-6228ffb3e99b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aswin-s

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686537038816699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
I think this is fixed in the latest version @kbecciv can you try to reproduce it again and if you can, reopen this?
