### ISSUE TITLE
Web - Emojis with Two Faces Overlap with Other Emojis

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and type a message.
2. Scroll down to the emojis section and observe that some emojis with two faces are overlapping with other emojis.

## Expected Result:
Emojis with two faces should not overlap with other emojis.

## Actual Result:
Emojis with two faces are overlapping with other emojis.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (80).webm](https://github.com/Expensify/App/assets/93399543/5614095d-fc34-4a15-8154-962aeefabb13)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686465118923619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I can't reproduce this at all and neither can applause

**Comment by tewodrosGirmaA** [comment]
Hi @greg-schroeder  It seems like this bug is a bit of a prankster - it won't stay gone even though it's been marked as closed on GitHub. Another bug reporter even caught it too! Check out the evidence here: 👉 https://expensify.slack.com/archives/C049HHMV9SM/p1687510110129949. Any thoughts on how to give it the boot for good? 😄
