### ISSUE TITLE
[$1000] Admin is selected when Clicking Select all

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in a new account
2. Create a new workspace
3. Go members
4. Click on Select all
5. Notice that admin is also selected. This happens only in staging

## Expected Result:
Admin not selected

## Actual Result:
Admin selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-2

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/65a5155f-316a-4a77-9a28-b2cbb05f9369

https://github.com/Expensify/App/assets/93399543/a92bbf8f-c0d8-4d1a-b584-af6340392ae3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687204191205439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddddf3a7e6da1c76</li>
        <li>Upwork Job ID: 1670911408831201280</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
I was able to a PR's which might have affected this:
- https://github.com/Expensify/App/pull/20826 (was deployed 3 days ago).

**Comment by luacmartins** [comment]
I can't reproduce this

**Comment by Ali-ch88** [comment]
When I click on the "Select all" checkbox, The admin does not select automatically.
![dd](https://github.com/Expensify/App/assets/61835503/fbaed0f1-622a-4af0-9c92-08a30eec0f91)

**Comment by daveSeife** [comment]
Use a New Account to reproduce it, works only for New Account.

**Comment by Ali-ch88** [comment]
Contributor details
Your Expensify account email: <alii.razaa8800@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~012a1375209e7966f9>

**Comment by Ali-ch88** [comment]
Contributor details
Your Expensify account email: alii.razaa8800@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012a1375209e7966f9

**Comment by Ali-ch88** [comment]
@daveSeife Yes, I have checked this one, the issue happened in the stagging site but not in locally.

**Comment by kameshwarnayak** [comment]
@luacmartins I can reproduce the bug with the latest main code.

Attached the screenshot

https://github.com/Expensify/App/assets/2232432/665f7555-5da5-45f4-9b91-9f25803f4eda

Please let me know if I have to look into the fix?

**Comment by bondydaa** [comment]
@luacmartins is this a blocker still then?

**Comment by luacmartins** [comment]
I won't block the deploy on this given it's a minor issue with an easy workaround. That being said, we still have time to fix it before the deploy happens.

**Comment by abdulrahuman5196** [comment]
@Ali-ch88 
Kindly follow our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and propose a solution using the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md)

**Comment by abdulrahuman5196** [comment]
@kameshwarnayak Are you still able to reproduce the issue in latest main?
I am not able to  reproduce the issue in latest main


https://github.com/Expensify/App/assets/46707890/1d06c5f4-bd9f-4324-be67-75320c13ecd7

**Comment by bondydaa** [comment]
sure, feel free to close out an issue if it's no longer reproducible.
