### ISSUE TITLE
Different UI displayed for a brief moment when clicking on Share Code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Click on "Reply in thread"
4. Navigate to the Thread detail
5. Click on "Share Code"
## Expected Result: 
When clicking on "Share Code", the UI should remain consistent without any brief display of a different UI
## Actual Result: 
When clicking on "Share Code", a different UI is briefly displayed for a second before the expected UI appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/39c40725-ed4c-4de9-a4a1-b82e3408bee8

https://github.com/Expensify/App/assets/43996225/f9c92292-def0-4018-a918-fb149b884d93

https://github.com/Expensify/App/assets/43996225/d067b7e8-9deb-4de4-9e7e-95560b20a720

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686566125177409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Is the issue that it ever so briefly shows this?
<img width="1344" alt="image" src="https://github.com/Expensify/App/assets/9133401/66e7d9fd-22ba-46e1-b78f-8e8090c2adcc">

I can't reproduce. I see the whole QR slides in from the right:
![image](https://github.com/Expensify/App/assets/9133401/0fec1951-53fb-46c4-b2ae-2310f458a806)

**Comment by ayazhussain79** [comment]
@twisterdotcom Yes it only appears for a while

**Comment by ayazhussain79** [comment]
you can test it on android app and also on mweb

**Comment by twisterdotcom** [comment]
I have tried on Android. Pixel 6a, Android 13:

Uploading screen-20230619-220828.mp4…

**Comment by twisterdotcom** [comment]
I remain unable to reproduce this I'm afraid. I'm going to close.
