### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000]  not able to show preview of avatr in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message
3. click on reply in thread option
4. click the header of thread
5. click on avatar to see preview
## Expected Result: 
should show preview of avatar
## Actual Result: 
does not show preview of avatar

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7d0ba6ec-c407-4962-a27c-8a6d3bf96828

https://github.com/Expensify/App/assets/43996225/fd3c8223-d7b5-4ab7-9f40-a843dc98ff1b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686560482456669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a875266a3d365a7</li>
        <li>Upwork Job ID: 1671152204532953088</li>
        <li>Last Price Increase: 2023-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26069023</li>
<li>spcheema | Contributor | 26069025</li>
<li>gadhiyamanan | Reporter | 26069029</li>
</ul></li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Hi @aimane-chnaif can you review the proposals above? Thanks

**Comment by kevinksullivan** [comment]
Hi @aimane-chnaif what are your thoughts on the latest proposal?

**Comment by kevinksullivan** [comment]
@aimane-chnaif please let me know when you can review these proposals.

**Comment by kevinksullivan** [comment]
yup, I just said we don't need to add that as a new feature

**Comment by shawnborton** [comment]
Seems like that is a separate bug? Cc @grgia as you implemented workspace avatars, in case you have any ideas there.

**Comment by grgia** [comment]
we need to pass in the workspace name to the avatar

**Comment by grgia** [comment]
@spcheema 

https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/components/Avatar.js#L84

We need to pass the Avatar both the name prop and the type prop

**Comment by shawnborton** [comment]
I'm not really sure what is being asked here. But I think that we should fix the original bug by allowing a user to click on the thread avatar image to see the full image. It doesn't matter if that is a user or workspace avatar - you should still be able to preview it.

**Comment by kevinksullivan** [comment]
@aimane-chnaif can you give an ETA on the review? Otherwise I'll have to get this reassigned.

**Comment by kevinksullivan** [comment]
@sonialiap I am going OOO for the week so tapping you in the interim. Thanks!

**Comment by sonialiap** [comment]
@aimane-chnaif what's the status of this issue? I'm not seeing a PR, but there have been many comments so maybe I missed it, have we selected a proposal?

**Comment by PauloGasparSv** [comment]
Didn't notice this was labeled as internal [here](https://github.com/Expensify/App/issues/21073#issuecomment-1638800944), re-adding the external label

**Comment by kevinksullivan** [comment]
@sonialiap I am back to handle payments when they come up!

**Comment by kevinksullivan** [comment]
Hey @aimane-chnaif please finish out the steps above so we can pay this out after the hold. Thanks!

**Comment by sonialiap** [comment]
@aimane-chnaif please fill out [the checklist ](https://github.com/Expensify/App/issues/21073#issuecomment-1687085799)so that we can issue payment

**Comment by kevinksullivan** [comment]
Paid and contratcs closed!
