### ISSUE TITLE
New Group - Unknown broken contact is added to group when selecting contacts with only avatars

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20951

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)
3. Create a new group chat with multiple people with avatars (not default)
4. Make sure that the icons in the initial group chat are the avatars

## Expected Result:
The group with selected users created

## Actual Result:
Unknown broken contact is added to the group. Sometimes I receive the error message
It happens with 2 accounts:
[applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)

[applausetester+ihchat3@applause.expensifail.com](mailto:applausetester+ihchat3@applause.expensifail.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6099240_2006](https://github.com/Expensify/App/assets/78819774/bd38969d-4af1-47c1-bdea-4cad41bee608)

https://github.com/Expensify/App/assets/78819774/2884de27-0fd1-4717-ab0b-ba01974477ad

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@Beamanator is this the expected behavior if users are unknown?

**Comment by Beamanator** [comment]
Sorry @luacmartins @lanitochka17 it's really not clear to me what the exact problem is here - is it about the profile not showing any details at the end?

**Comment by luacmartins** [comment]
I can't reproduce this.

**Comment by Beamanator** [comment]
Same 🙃

**Comment by luacmartins** [comment]
Ok, removing the deploy blocker label and adding `Needs reproduction`

**Comment by luacmartins** [comment]
Gonna un-assign myself until we can reproduce this issue.

**Comment by Beamanator** [comment]
I thinkkkkk this had to do with selecting options that didn't have `logins` - but that was changed to not be available in the "chat switcher" recently so i thinkkkkk this might not be reproducible anymore

**Comment by twisterdotcom** [comment]
I cannot recreate this anymore:
<img width="744" alt="image" src="https://github.com/Expensify/App/assets/9133401/cc46e0f6-a33c-4dad-aa13-929aac6f99ec">

Let's close and if anybody can reproduce, please comment and I'll reopen.
