### ISSUE TITLE
[$1000] Reacting to a deleted comment brings the comment back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a comment from userA to userB
2. From userB, click on Add reaction icon and keep the emoji picker opened
3. From userA, delete the comment
4. From userB, click on any emoji to add a reaction
## Expected Result: 
Not able to react to the deleted comment and the comment doesn't reappear
## Actual Result: 
Able to react to deleted comment and the comment also reappears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/781aeda2-407c-49f2-a33d-1dc0dd87e1fd

https://github.com/Expensify/App/assets/43996225/30d8c7d4-e9c3-4450-bf57-1c4b50b12a49

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686592438424909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a690c328d0b0ed1</li>
        <li>Upwork Job ID: 1671911701209255936</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by slafortune** [comment]
issue looks good 👍

**Comment by slafortune** [comment]
Sorry - not sure where my comment went - I couldn't reproduce this either 👍
