### ISSUE TITLE
Dev: Android - Connecting bank account page is not opening (loads infinitely)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings > Workspace
3. Open workspace > Bills
4. Click to Connect bank account

## Expected Result:
User able to open  Connecting bank account page

## Actual Result:
 Connecting bank account page is not opening (loads infinitely)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/838a4f38-51da-4027-9d98-8c63e20a063d

**Expensify/Expensify Issue URL:** @narzullome

**Issue reported by:**

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686646377359199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
this functionality is working as expected for me on staging! since @kbecciv also could not repro this, im going to close.
