### ISSUE TITLE
Split bill preview in app shows only 3 candidates, causing confusion when more than 3 are selected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign at the bottom of the screen.
2. Select "Split Bill" and add desired number.
3. Choose more than 5 people to split with and click "Next". Observe that the app only includes 3 of them in the preview and does not indicate that others have been left out, causing confusion.

## Expected Result:
App should display all selected individuals in preview or indicate that some have not been included with three dots.

## Actual Result:
App displays only three candidates in preview when more than 5 or so are selected, causing confusion by not indicating that some have been left out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (91) (1).webm](https://github.com/Expensify/App/assets/93399543/15b1fe92-16a6-4238-89dd-52563cc86057)

https://github.com/Expensify/App/assets/93399543/aeaed34e-24af-4949-8dbc-cd29a7296ea4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686648290378409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
The list is scrollable

**Comment by jeet-dhandha** [comment]
@bernhardoj - I have a proposal to show a indicator arrow at bottom. Like i have done here. This might help at many places to identify scrolls. 

How it works:
1. Indicator arrow is shown only when there is a scroll available.
2. If the scroll is at the bottom, the indicator arrow is not shown.


https://github.com/Expensify/App/assets/78416198/12d24542-4af5-4dbd-8661-039b0f029641

**Comment by sakluger** [comment]
I agree that when the window size cuts off the list exactly between two people, that it's not clear that it's a scrollable list.

It looks fine in this example:

![image](https://github.com/Expensify/App/assets/5997400/1ae813c5-fe6c-4a29-a721-9a5334519931)

But in this example, when I change the window size just slightly, it's not great:

![image](https://github.com/Expensify/App/assets/5997400/983bd7a5-6f72-4110-a77b-d4d37eff73d7)

@Expensify/design I'd love your thoughts on how best to fix this. Do we have an existing pattern for scrollable lists that does a better job indicating when there is more below the fold?

**Comment by shawnborton** [comment]
Hm good question. I don't think we do, so part of me thinks we could just close this? 

We could consider some kind of fade out or something, but I don't feel strongly. Maybe bring this to the open source room for more discussion, or bump the thread?

**Comment by jeet-dhandha** [comment]
@shawnborton @spcheema - Please ping here whenever you get an update.

**Comment by sakluger** [comment]
Thanks @shawnborton, I'll bring up for discussion in open-source and post here with the decision. I think you're probably right that we should close for now, since it's not necessarily a bug, just a design pattern that could be improved.

**Comment by sakluger** [comment]
Actually, we do have a similar design pattern - the LHN. There's no indicator that there are more chats below the fold. Given that we're following the existing design pattern, I'm just going to close this for now.

**Comment by jeet-dhandha** [comment]
@sakluger @shawnborton - Please do assign me this task if you think to implement something in future.
