### ISSUE TITLE
[HOLD for #15212] [$1000] New line Marker appears when requesting money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to chat
3. Send Request money
4. Notice that the new line marker is show for the money requester not for the money requested.
## Expected Result: 
New line marker should appear for the User who receives the money request
## Actual Result: 
New line marker appears for the User you sends the request.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c4bf20a2-6dfe-4f3d-8fda-7d6a1e9a5f0b

<img width="960" alt="IMG_4125" src="https://github.com/Expensify/App/assets/43996225/c7f10ed1-3a75-43b1-acab-8aeaf5f9ff2c">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686593566770089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010baadcea140a56d7</li>
        <li>Upwork Job ID: 1671397340782891008</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Reviewing

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
New line marker appears when money is requested.

### What is the cause of this issue?
The app uses the `ReportUtils.isUnread` function to check whether the report is unread or not, and if the report is unread, a new line marker is displayed.
https://github.com/Expensify/App/blob/18d62d0604501a32f6e7959647a88e93e5330046/src/libs/ReportUtils.js#L1779-L1788

The response from `RequestMoney` API contains `report` information, and `lastReadTime` is smaller than `lastVisibleActionCreated`.

Therefore, the new line marker is displayed.

### What changes do you think we should make to solve the problem?
The new line marker should appear for the user who receives the money request, and in this case `lastReadTime < lastVisibleActionCreated` is correct.
But for the user who sends the request, the new line marker should not appear.

We can pass additional `onyxData` to the `RequestMoney` API request's `successData` to set the `lastReadTime` of the report to empty.
```
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${chatReport.reportID}`,
            value: {
                lastReadTime: '',
            },
        },
```

https://github.com/Expensify/App/blob/18d62d0604501a32f6e7959647a88e93e5330046/src/libs/actions/IOU.js#L148-L217

After API success, the `lastReadTime` of the report is set to zero for the user sending the request, so `ReportUtils.isUnread` returns fail, and the new line marker does not appear.

### What alternative solutions have you investigated? (Optional)
None.

**Comment by greg-schroeder** [comment]
@mananjadhav thoughts on above proposals?

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New line marker appears when sending money request

### What is the root cause of that problem?

We determines if the report is unread by comparing lastVisibleActionCreated and lastReadTime. And we get the `newMarkerReportActionID` by checking created of all actions.
https://github.com/Expensify/App/blob/342d4fd84f3dda933c44a71b9e4d666d26b270c9/src/libs/ReportUtils.js#L2016-L2024

The issue arises here. When sending money request, `REPORTPREVIEW` action is created by the participant and its `created` time is always later than `lastReadTime`. That's why isUnread is true and money request is marked unread.

### What changes do you think we should make in order to solve the problem?

When sending money request, IOU report is created and its `ownerAccountID` is the owner. When getting `newMarkerReportActionID`, check if action's `actionName` is `REPORTPREVIEW`, and lastActorAccountID of linked IOU report is the owner. If this is true, we can think of the action as automatic reply for a money request and ignore.

```
function isIOURequestAutoReply(reportAction) {
    const iouReportID = ReportActionsUtils.getIOUReportID(reportAction);
    if (!iouReportID) {
        return false;
    }

    const iouReport = getReport(iouReportID);
    return iouReport && iouReport.lastActorAccountID === currentUserAccountID;
}
```

### What alternative solutions did you explore? (Optional)
We can update the last read time of the report for the automatic replies in the backend.

**Comment by mananjadhav** [comment]
Will check the proposals today.

**Comment by greg-schroeder** [comment]
Awaiting C+ review

**Comment by mananjadhav** [comment]
sorry for the delay, I was ooo and sick.

I am unable to reproduce this. do we have any pre-requisites?


https://github.com/Expensify/App/assets/3069065/e2394a64-dd3e-445d-b377-57f428375f74

**Comment by mananjadhav** [comment]
@daveSeife I posted the screencast from staging env on Mac Web Chrome.

**Comment by greg-schroeder** [comment]
I also can't reproduce this anymore, even though I could originally. Maybe it was fixed somewhere else?

**Comment by daveSeife** [comment]
@greg-schroeder @mananjadhav 

I think his issue is only present in some platform. 

https://github.com/Expensify/App/assets/49120316/58b9ae2d-bfcd-4774-a065-2b8cc71fe7c3


https://github.com/Expensify/App/assets/49120316/2ef4999f-aeed-4746-9e3d-aba7c9d68549


I have check the latest versions both on iOS and Web Chrome

iOS : v1.3.32-5
Web : v1.3.35-4

here are the results 
/

**Comment by mananjadhav** [comment]
@kavimuru Are we able to consistently reproduce this? and on all platforms? or only some of them? Could you recheck and help us with the correct platforms please?

**Comment by mananjadhav** [comment]
@kavimuru @greg-schroeder quick bump on the previous comment?

**Comment by StevenKKC** [comment]
I can reproduce in Windows/Chrome.
Send Request money and click other LHN option quickly, and then go back to the chat report.

https://github.com/Expensify/App/assets/131836113/def9a510-2818-45f6-adf7-224ef886db17

**Comment by kavimuru** [comment]
@mananjadhav Yes still able to reproduce in Android, iOS, mweb and desktop web

**Comment by StevenKKC** [comment]
@mananjadhav 
Please try below steps.
1. Go to any chat
2. Scroll chat history so the latest message is not visible
3. Click on request money in composer box and finish the flow.

**Comment by mananjadhav** [comment]
Thanks @StevenKKC I am able to reproduce this, by scrolling the chat history.

**Comment by greg-schroeder** [comment]
Awaiting proposal review

**Comment by mananjadhav** [comment]
I've requested some information [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1689097248560249). Will review after that.

**Comment by greg-schroeder** [comment]
Holding per team discussion: https://expensify.slack.com/archives/C02NK2DQWUX/p1689139638273709?thread_ts=1689097248.560249&cid=C02NK2DQWUX

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
""

**Comment by greg-schroeder** [comment]
#15212 still underway

**Comment by greg-schroeder** [comment]
""

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
This one will end up being handled by unread marker redesign and so I don't think we're pursuing it independently.
