### ISSUE TITLE
[HOLD for payment 2023-06-29] [HOLD for payment 2023-06-28] Workspace - App is crashing when added to WS several existing users with names/avatars + new user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensify account
3. Go to or create a Workspace and go to Members list
4. Invite existing users with custom usernames and avatars + new user (that doesn't have a NewDot account)

## Expected Result:
 App is not crashing when added to WS several existing users with names/avatars + new user

## Actual Result:
 App is crashing when added to WS several existing users with names/avatars + new user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.29-6

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e3ab0cc7-f475-4841-835f-4535e20ec186

https://github.com/Expensify/App/assets/93399543/b9820ae0-91fb-47ae-a7d7-d30d44a3954a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
PR up

**Comment by luacmartins** [comment]
This has been fixed by https://github.com/Expensify/App/pull/21150. Removing the blocker lable.

**Comment by aldo-expensify** [comment]
This was fixed.
