### ISSUE TITLE
[$2000] Android - Send Money - The cursor moves to the middle when entering amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Login
3. Tap on the + button
4. Tap on Send money
5. Select a recipient
6. Enter 8 00000 quickly

## Expected Result:
The cursor should always be moved at the end of the digits when entering the amount

## Actual Result:
The cursor auto moves to the middle when entering amount. This causes the user to enter the amount wrongly since a digit that supposed to be at the end will rather be in the middle. For example. Entering the amount 4593000 will rather be 450390 due to the auto movement of the cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.

**Reproducible in staging?:** Yes

**Reproducible in production?:**Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2881e256-3b2b-4927-85c2-acf04029ede9

![Bug6099649_paintastic20230620_084053](https://github.com/Expensify/App/assets/78819774/a856a10d-7d53-4121-9da8-54813fd5bf20)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018846f9cb29c17500</li>
        <li>Upwork Job ID: 1674450506459115520</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
Working on it

**Comment by michaelhaxhiu** [comment]
Real easy to reproduce on my android pixel

**Comment by k1r0s** [comment]
### Proposal

========================================================

I will fix this problem with the `textAlignVertical `of the `TextInput `element.

So the cursor will keep the end position of the input and display correct input values.

Also, It needs to trigger user input and validate the amount as well.

```
<View
                    nativeID={this.amountViewID}
                    onMouseDown={(event) => this.onMouseDown(event, [this.amountViewID])}
                    style={[styles.flex1, styles.flexRow, styles.w100, styles.alignItemsCenter, styles.justifyContentCenter]}
                >
                    <TextInputWithCurrencySymbol
                        formattedAmount={formattedAmount}
                        onChangeAmount={this.updateAmount}
                        onCurrencyButtonPress={this.navigateToCurrencySelectionPage}
                        placeholder={this.props.numberFormat(0)}
                        ref={(el) => (this.textInput = el)}
                        selectedCurrencyCode={this.state.selectedCurrencyCode}
                        selection={this.state.selection}
                        onSelectionChange={(e) => {
                            if (!this.state.shouldUpdateSelection) {
                                return;
                            }
                            this.setState({selection: e.nativeEvent.selection});
                        }}
                    />
                </View>
```

**Comment by k1r0s** [comment]
> 📣 @k1r0s! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

ok, I will add it.

**Comment by k1r0s** [comment]
sure, @rushatgabhane 

I think the `focusTextInput() `function is not triggered properly when the user type an amount.

**Comment by michaelhaxhiu** [comment]
Still fielding proposals. If no bites, will increase the price. But I agree let's find the regression if we can @rushatgabhane 🙏

**Comment by mmaleiter** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem is that when entering an amount quickly the cursor does not appear at the last position.
Additionally the order of the numbers might differ from how the were entered and the cursor might start
to jump between to positions. 

### What is the root cause of that problem?
The root cause seems to be that setState is call in onSelectionChange.
As I do not see the purpose of the implementation of 
```
 onSelectionChange={(e) => {
                                        if (!this.state.shouldUpdateSelection) {
                                            return;
                                        }
                                        this.setState({selection: e.nativeEvent.selection});
                                    }}

```


### What changes do you think we should make in order to solve the problem?

I would remove this block (onSelectionChanged). It  seems to work as expected on android and iOS. 
This also solves the problem of the wrong order. And the jumping cursor.

### What alternative solutions did you explore? (Optional)
I did not try anything else.

**Comment by mmaleiter** [comment]
Here is a video to show the described problems.

https://github.com/Expensify/App/assets/109748065/9a2c3c86-283a-4bb3-a6e4-7186ba4a0de6

**Comment by michaelhaxhiu** [comment]
Doubling

**Comment by michaelhaxhiu** [comment]
:fry:

**Comment by michaelhaxhiu** [comment]
damn i missed that 😢
