### ISSUE TITLE
[HOLD for payment 2023-07-06] Android- Chat- The user is not navigated to the chat screen after opening chat from notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Close the NewDot app
2. Wait for ~1 minute
3. Send a message from B to A. Push notification should appear
4. Double-tap the notification. It should navigate the user to the correct chat, and the new message should be available.

## Expected Result:
The user is expecting that the app opens and then the user is redirected to the chat screen in one-on-one chat bar

## Actual Result:
The user is been sent to the homepage of the app when the app is opened through the chat message received from the notification bar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b318cb16-98b8-429e-80f3-0cf7f9673033

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @Victor-Nyagudi 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169b8f4b5af31c852</li>
        <li>Upwork Job ID: 1671205349345284096</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
This regression reached prod but should have been caught in [regression tests](https://expensify.testrail.io/index.php?/cases/view/1971003&group_by=cases:section_id&group_order=asc&display_deleted_cases=0). Giving Applause the benefit of the doubt, I think this is what happened:

> Maybe they are clicking the notification with the chat already open. Right now, clicking the notification just opens the app and doesn’t navigate. So if they already had the chat open, it’d seem like it worked correctly

**Comment by arosiclair** [comment]
Seems that it works while the app is alive, but not while killed:

https://github.com/Expensify/App/assets/6833644/d6bac860-c7ac-48e8-87a8-9ab486ec7588

**Comment by arosiclair** [comment]
As suspected this was caused by [the navigation reboot](https://github.com/Expensify/App/pull/19263). Specifically, we're no longer waiting for the `NavigationContainer` to be ready. Additionally, we're still making a call to `Navigation.setDidTapNotification()` which does not exist and causes an error ([source](https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js#L28)).

There's a few thing we need to do here:
- [ ] Fix the bug
- [ ] Add logging for notification click handling so we can better debug this in the future
- [ ] Update regression test steps to select a different chat before testing notification click through and also to test click through with the app killed

**Comment by arosiclair** [comment]
Found a fix and posted a PR. Also pinged some knowledgeable navigation folks

**Comment by arosiclair** [comment]
First fix broke initial app startup (boot splash was never dismissed). Just found a better fix for an error when checking the active route during startup. Now out for review!

**Comment by arosiclair** [comment]
Tests passed on staging!

| Android | iOS |
|--------|--------|
| <video src="https://github.com/Expensify/App/assets/6833644/5fd9dc5d-a7c5-4c77-891c-d571a41af1db" /> | <video src="https://github.com/Expensify/App/assets/6833644/44b49da2-2c97-4ac2-8815-e5a0edf8a2a0" /> |

**Comment by arosiclair** [comment]
@mollfpr I think we should propose the regression test steps I wrote on the PR. We should update [these QA steps](https://expensify.testrail.io/index.php?/cases/view/1971003&group_by=cases:section_id&group_order=asc&display_deleted_cases=0) specifically so that there's another section for testing click through after the app is killed. Thoughts?

**Comment by mollfpr** [comment]
Yup, sounds good to me. I guess we only need to add a new section to test on the killed app(?)

**Comment by arosiclair** [comment]
Yeah that and also lets add a step to navigate to the Concierge chat before clicking the notification in each section. Like how I wrote my steps. That will make sure the notification isn't only just re-opening the app with the chat already open.

**Comment by arosiclair** [comment]
@mollfpr can you complete the checklist? Getting those regression tests updated is a very important improvement for this

**Comment by mollfpr** [comment]
Sorry, I'm running out of time 🙏

I'll complete the checklist in the morning.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Thanks to @arosiclair explain here https://github.com/Expensify/App/issues/21120#issuecomment-1601373247

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression steps should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

As suggested by @arosiclair, we should add the new test case here https://expensify.testrail.io/index.php?/cases/view/1971003&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

**_Notification click through (Android & iOS only)_**

1. Log into NewDot
2. Navigate to the Concierge chat
3. Send yourself a message
4. Verify a notification for the message is received
5. Click the notification
6. **Verify** the app navigates to the chat for the message


**_Notification click-through while the app is killed (Android & iOS only)_**

1. Navigate back to the Concierge chat
2. Kill the app by swiping it away in the recent apps view
3. Send yourself another message
4. Verify a notification for the message is received
5. Click the message
6. Verify the app opens and navigates to the chat for the message

**Comment by Victor-Nyagudi** [comment]
@mollfpr The payment date for this issue is July 6th, but I haven't received an offer yet for the reporting bonus.

Cc: @adelekennedy since you're also assigned here in case you're the one I should be asking.

**Comment by mollfpr** [comment]
@Victor-Nyagudi BZ team will take care of the payment, which in this issue is @adelekennedy

**Comment by Victor-Nyagudi** [comment]
Bump @adelekennedy .

I see @MelvinBot also added the `Overdue` label.

**Comment by adelekennedy** [comment]
was ooo Friday as I was sick and then the weekend.

@Victor-Nyagudi $250 reporting
@mollfpr 1k for PR review 

will you apply [here](https://www.upwork.com/jobs/~0169b8f4b5af31c852)?

**Comment by Victor-Nyagudi** [comment]
Sorry to hear that, @adelekennedy. Hope you're feeling better now.

I've applied on Upwork.

**Comment by mollfpr** [comment]
Applied, thank you @adelekennedy

**Comment by mollfpr** [comment]
@adelekennedy Could you end the Upwork contrack please? Thank you!
