### ISSUE TITLE
Web - Сhat – The message is pasted with hyperlink format when select "Paste as plain text"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21122]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the test website https://staging.new.expensify.com/
and Log in
2. Type in some conversation
3. Paste a message with a hyperlink format by right clicking and selecting "Paste as plain text", send it

## Expected Result:
The message is pasted without any hyperlink format

## Actual Result:
The message is pasted with hyperlink format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1a08e4c0-693d-487b-9b18-d7bb7aa2a405

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Taking to slack to get clarity on the issue.

**Comment by kevinksullivan** [comment]
bumping thread

**Comment by kevinksullivan** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1688165086712539?thread_ts=1687354933.343639&cid=C049HHMV9SM
