### ISSUE TITLE
[HOLD for payment 2023-06-29] Context menu doesn't close after clicking on "Reply in thread" as unauthenticated user in public rooms

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#21129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a public room as an unauthenticated user (https://staging.new.expensify.com/r/8813851443373010)
2. Right-click on a comment to display the context menu
3. Click on "Reply in thread"

## Expected Result:
The user is redirected to the sing-in page, and the context menu should be closed

## Actual Result:
The context menu is still open

https://github.com/Expensify/App/assets/6829422/e6563810-5cef-497d-939e-f490d5893791

## Workaround:
Just click on one of the options, but that could case an undesired behavior 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Looks like @fedirjh reviewed the PR and is eligible for PR review payment. @fedirjh I sent you an offer on Upwork
