### ISSUE TITLE
[Hold on https://github.com/Expensify/App/pull/17964] The description when clicked again shows blank

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging. new.expensify on web chrome
2. Select plus icon and select send money
3. Now enter a description and click on save
4. Again click on the description and without performing action just click on back button
5. Notice that now the description is shown as empty
## Expected Result: 
The description when cliked again should not show blank
## Actual Result: 
The description when clicked again shows blank

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/288963ea-c440-48a6-8694-9549feea1d0f

https://github.com/Expensify/App/assets/43996225/bb0c3fb9-001b-4424-a95e-713ce28e7380

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1686595999820919
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
The page is being refactored here https://github.com/Expensify/App/pull/17964 and the issue won't exist anymore.

**Comment by laurenreidexpensify** [comment]
PR has been merged, but not on staging yet

**Comment by laurenreidexpensify** [comment]
PR has been deployed to prod, gonna test now and confirm if we can close

**Comment by laurenreidexpensify** [comment]
Confirmed - this is no longer reproducible. Closing
