### ISSUE TITLE
Chat - Unable to find user monil@expensifail.com

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21135]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21030

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensify account
3. Join #bobs-testing public room (https://staging.new.expensify.com/r/5593084223054221
4. Try to mention user account [monil@expensifail.com](mailto:monil@expensifail.com)

## Expected Result:
User can to mention users account [monil@expensifail.com](mailto:monil@expensifail.com)

## Actual Result:
User [monil@expensifail.com](mailto:monil@expensifail.com)
not showing up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e353bf0b-90f5-49a0-9d91-f400df355856

![IMG_9795](https://github.com/Expensify/App/assets/78819774/5c795ea8-8988-47f1-bed0-fe72fa773460)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I don't think this is a blocker. I could not repro. Additionally, mentions seem to be working fine now. Closing.

https://github.com/Expensify/App/assets/22219519/9f51b74f-115a-46c5-9156-141fdbbe5197
