### ISSUE TITLE
On switching default contact, app doesn't allow to access workspace created by other contacts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user which has verified secondary contact method
2. Open settings
3. Open workspaces
4. Click on new workspace
5. Change default contact to secondary contact method
6. Again open settings
7. Open workspaces and click on workspace created in step 4
## Expected Result: 
App should allow user to access their own workspaces if they change default contact method.
## Actual Result: 
App does not allow user to access their own workspaces if they change default contact method.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a0592395-b84a-4f63-8ce4-cad8cff0f24a

https://github.com/Expensify/App/assets/43996225/1943dd40-515b-4dfb-b9dc-3f7a9ecbd68d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686583034487009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
Seems like a dupe https://github.com/Expensify/App/issues/20741

**Comment by dhanashree-sawant** [comment]
Hi @Natnael-Guchima, the following issue was reported 1 day before on slack then that issue.

**Comment by puneetlath** [comment]
Seems to be fixed, so going to close. Commented in the other issue about the bug report.
