### ISSUE TITLE
App crashes when you search any value on a fresh new public account

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#21149]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create new account which is on public domain
1. Click Search
1. Type in any value
1. The app crashes locally and throws error in staging 

```
OptionsListUtils.js:753 Uncaught TypeError: Cannot read properties of undefined (reading 'searchText')
    at getOptions (OptionsListUtils.js:753:1)
    at Module.getSearchOptions (OptionsListUtils.js:832:1)
    at SearchPage.updateOptions (SearchPage.js:136:36)
    at later (debounce.js:17:1)
```

![image](https://github.com/Expensify/App/assets/36083550/b8a47e3f-0316-402e-a385-f74e845bea92)

## Expected Result:
Describe what you think should've happened

Results should show up

## Actual Result:
Describe what actually happened

The App crashed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.29-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** Internally
**Slack conversation:** https://expensify.slack.com/archives/C07J32337/p1687282960670579?thread_ts=1687190127.488249&cid=C07J32337

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Hiya @mountiny - need anything from BZ on this right now?

**Comment by mountiny** [comment]
Not yet, thank you 🙇

**Comment by mountiny** [comment]
I am now able to repro using staging web api but not with main web-E so I think this is related to what we send in the OpenApp call, investigating further. This is what OpenApp returns:

<img width="912" alt="image" src="https://github.com/Expensify/App/assets/36083550/75f169ce-42e3-42fb-8734-158927a31eca">

**Comment by mountiny** [comment]
But main Web-E is returning:
```
 {
            "onyxMethod": "merge",
            "key": "personalDetails",
            "value": {
                "concierge@expensify.com": {
                    "accountID": 1,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/icons\/concierge_2022.png",
                    "displayName": "concierge@expensify.com",
                    "login": "concierge@expensify.com",
                    "pronouns": "",
                    "timezone": {
                        "automatic": true,
                        "selected": "America\/Los_Angeles"
                    },
                    "firstName": "",
                    "lastName": "",
                    "payPalMeAddress": "",
                    "phoneNumber": "",
                    "validated": true
                },
                "test+21149a@blocker.com": {
                    "accountID": 328,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_9.png",
                    "displayName": "test+21149a@blocker.com",
                    "login": "test+21149a@blocker.com",
                    "pronouns": "",
                    "timezone": {
                        "automatic": true,
                        "selected": "America\/Los_Angeles"
                    },
                    "firstName": "",
                    "lastName": "",
                    "payPalMeAddress": "",
                    "phoneNumber": "",
                    "validated": false,
                    "localCurrencyCode": "CZK"
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "1": {
                    "accountID": 1,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/icons\/concierge_2022.png",
                    "displayName": "concierge@expensify.com",
                    "login": "concierge@expensify.com",
                    "pronouns": "",
                    "timezone": {
                        "automatic": true,
                        "selected": "America\/Los_Angeles"
                    },
                    "firstName": "",
                    "lastName": "",
                    "payPalMeAddress": "",
                    "phoneNumber": "",
                    "validated": true
                },
                "328": {
                    "accountID": 328,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_9.png",
                    "displayName": "test+21149a@blocker.com",
                    "login": "test+21149a@blocker.com",
                    "pronouns": "",
                    "timezone": {
                        "automatic": true,
                        "selected": "America\/Los_Angeles"
                    },
                    "firstName": "",
                    "lastName": "",
                    "payPalMeAddress": "",
                    "phoneNumber": "",
                    "validated": false,
                    "localCurrencyCode": "CZK"
                }
            }
        },
```

So the current staging api is not returning correct format and its missing the `login` in openApp `personalDetailsList`. Looking what PR added this back in Web-E

**Comment by mountiny** [comment]
This Web-E Pr should fix this https://github.com/Expensify/Web-Expensify/pull/37880

**Comment by mountiny** [comment]
Tested again in staging and seems to be fixed 
<img width="1274" alt="image" src="https://github.com/Expensify/App/assets/36083550/9b08a544-9fd1-44c9-a8df-61b081e40a1b">


No console errors, closing
