### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web - random QR code is generated on opening share code of room using URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, click on + button and select New room option
2. Fill the details and click on create room option
3. Click on header of room report screen
4. Go to share code and copy **the URL**
5. From userB (who is not part of room), go to share code using URL ( https://new.expensify.com/r/5701471373675426 )

## Expected Result:
Should show 'hmm it's not there...' as user is not part of room

## Actual Result:
Users share code shows if user is logged in and if user is not logged in it shows random share code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d55477a1-2c03-4094-bb03-3dfc3a9eb690

https://github.com/Expensify/App/assets/93399543/8506cc03-d66b-4930-a5ef-23d5df3cc9a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686722986231259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018651b89a2a819106</li>
        <li>Upwork Job ID: 1673303498370383872</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
shows QR code screen for restricted room to non member while using direct url

### What is the root cause of that problem?
In the shareCodePage we haven't used `FullPageNotFoundView` to restrict the user when the report is not available for them.

### What changes do you think we should make in order to solve the problem?
Use `FullPageNotFoundView` component to wrap here which will show 'hmm it's not there...' page while accessing the invalid room for the user.

https://github.com/Expensify/App/blob/2a5aee6ea8a92fa759dc2d05158b1f56ddf3efde/src/pages/ShareCodePage.js#L52-L53

```
<ScreenWrapper>
                <FullPageNotFoundView shouldShow={!isReport}>
                    <HeaderWithBackButton
```

**Comment by muttmuure** [comment]
Will handle first thing Monday

**Comment by muttmuure** [comment]
Looks like this one is fixed:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/356891ad-afa1-4e30-88cf-616a1d26a12d">

**Comment by muttmuure** [comment]
Looks like this one is fixed:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/b323ee5b-27cb-41ba-b4f5-2b3fe3d45a69">

**Comment by gadhiyamanan** [comment]
@muttmuure still able to reproduce

https://github.com/Expensify/App/assets/54790231/1584f7c1-39be-4768-955d-6a2a7a7ace01

**Comment by muttmuure** [comment]
Updated the reproduction steps because they didn't explicitly mention copying the URL in step 4

**Comment by sobitneupane** [comment]
> shouldShow prop should be !isLoadingReportData && !isReport because when we open with the deep link before signing in we need to wait to report data loads completely to check isReport correctly.

> And if isLoadingReportData is true we should display the loading screen to wait to report data loads completely.

@dukenv0307 Can you please explain a bit about the need of `isLoadingReportData`. If you can attach an example of the issue that can occur if we don't add `isLoadingReportData`, it will be very helpful.

**Comment by sobitneupane** [comment]
Oh yes. Nice catch @dukenv0307.

> And I think we should display loadingPage while report data is loading.

Let's do this as well.

[Proposal](https://github.com/Expensify/App/issues/21157#issuecomment-1600052110) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18636
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18636#issuecomment-1628515178
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1688979049764729
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
Payment Requested on Expensify.

**Comment by muttmuure** [comment]
Looks like @sobitneupane has been paid.

@dukenv0307 I've invited you to apply to the Upwork job

**Comment by gadhiyamanan** [comment]
@muttmuure offer accepted, thanks!

**Comment by muttmuure** [comment]
@dukenv0307 paid

@sobitneupane invited

**Comment by sobitneupane** [comment]
@muttmuure I already received payment through newDot.

**Comment by muttmuure** [comment]
OK, no worries!

**Comment by muttmuure** [comment]
@gadhiyamanan - $250.00

@dukenv0307 - $1,500.00

@sobitneupane - $1,500.00
