### ISSUE TITLE
[$1000] Public Room- Welcome Message inconsistency in Android vs Desktop Chrome

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any old room in public mode or create a new room in public mode
2. Open web and go to room > details > settings > search for welcome message
3. Open Android app > go to room > details > settings > search for welcome message

## Expected Result:
 Welcome message button available in both web and android

## Actual Result:
Welcome message Not available in Web Chrome (Desktop) but available in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![WhatsApp Image 2023-06-13 at 11 59 17 PM](https://github.com/Expensify/App/assets/93399543/84e5d78b-bc40-4a56-8e08-05651fdc3026)

![Screenshot (337)](https://github.com/Expensify/App/assets/93399543/8849b97a-dec9-424b-82b2-6aeec8f89e33)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://applause-ts.slack.com/archives/C037DRM7S1H/p1687261319303209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eed7a535d910cf30</li>
        <li>Upwork Job ID: 1671393157115645952</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I was able to reproduce it. I don't see the welcome message on web.

<img width="1352" alt="Screenshot 2023-06-20 at 22 41 48" src="https://github.com/Expensify/App/assets/8292562/51b1e74c-f8a4-473a-9edf-3b507798c83d">

**Comment by Shivam7-1** [comment]
Hello
I interested in work on this Issue can anyone please let me know how should I give proposal or do I get assign directly with this issue ?

**Comment by rain2o** [comment]
I was able to reproduce this issue, but upon investigating I realized that it's role-based, not device/browser based. The Welcome Message shows according to the user's permission to edit the welcome message. I logged in as the admin of the given workspace in the browser and could see the Welcome Message button then.

Can someone who was able to reproduce confirm if the same user and room were used when testing each device?

**Comment by avi-shek-jha** [comment]
> That makes sense!
> 
> > Can someone who was able to reproduce confirm if the same user and room were used when testing each device?
> 
> @avi-shek-jha, can you look into it?

Hi, upon further examination, I came to the following conclusion;

@rain2o is correct. The inconsistency is not device based. Only the owner of the workspace can use the welcome message feature. The owner of workspace can use the welcome message feature on all devices (android, web, mobile chrome). 

Also, an important thing to note it that if the owner of workspace and owner of room are two different individuals,  the owner of room does not have access to welcome message. He has to request owner of workspace to write the welcome message. I am not sure but perhaps, the one who created the room should have access to the welcome message feature.
