### ISSUE TITLE
"Hmm... it's not here" shown for anonymous users

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#21162]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to public room not signed in: https://staging.new.expensify.com/r/5593084223054221
2. Click on users profile name

## Expected Result:
See the user's name like when you are signed in

## Actual Result:
The page with the message "Hmm... it's not here" is shown

![image (6)](https://github.com/Expensify/App/assets/6829422/b71b63d4-3d87-49f0-a97c-cb6107c22898)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b58092cc3b78516</li>
        <li>Upwork Job ID: 1671274315258183680</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
Removing CM and C+ since this is server issue and will be tested by an internal engineer

**Comment by marcochavezf** [comment]
[Linked PR](https://github.com/Expensify/Auth/pull/8156) already merged. It should be live in the next deployment.

**Comment by Christinadobrzyn** [comment]
Hey @marcochavezf could you confirm if this PR will fix this issue? https://github.com/Expensify/App/issues/21047

**Comment by marcochavezf** [comment]
It won't be fixed with the linked PR. [Commented](https://github.com/Expensify/App/issues/21047#issuecomment-1601629096) on the other issue.

**Comment by marcochavezf** [comment]
Linked PR was already deployed to production last week. Closing it
