### ISSUE TITLE
Incorrect image shown in carousel for mobile Safari

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#21177]
Opening this issue as a continuation of the work done in https://github.com/Expensify/App/issues/18150. 

cc @kidroca 

Outstanding state of things for context, taking @kidroca's comment in https://github.com/Expensify/App/issues/18150#issuecomment-1596793427:

> From my end, I no longer encounter the issue of the carousel showing the wrong image during normal usage. The issue appears to be exclusive to mobile Safari on the simulator when I'm testing the app.
> 
> I've traced this problem back to the modal handling logic in react-native-web. Currently, I am working on developing a standalone bug example to highlight this issue and intend to open a separate ticket upstream.
> 
> If there are no longer reports of the carousel bug, I would propose we close this ticket. We can then initiate a new one specifically to track and monitor the mobile Safari-related issue.

I am also able to reproduce this reliably on mobile Safari

**Comment by bfitzexpensify** [comment]
@kidroca you're not appearing in the assignment list for me — are you able to self-assign?

**Comment by kidroca** [comment]
I think I need to comment on the issue and now you should be able to assign me

**Comment by kidroca** [comment]
Here's the related `react-native-web` issue: 
- https://github.com/necolas/react-native-web/issues/2544

I've found out the problem happens not only on mobile Safari, but on desktop Safari as well 
The bug does not occur on Chrome or the Desktop App which is based on Chromium

**Comment by kidroca** [comment]
I'm closely following the recently created issue in react-native-web:
- https://github.com/necolas/react-native-web/issues/2544

As of now, there has been no response or priority assigned to this ticket. This lack of feedback creates uncertainty, making it challenging to work on a fix. It would be helpful to know if the mentioned issue is already being addressed in an upcoming update or if there are any plans to modify the modal focus lock logic.
