### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] mWeb- Link is not working for Viewing all receipts/Viewing all bills option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings > Workspace >Reimbursements
3. Click to View All receipts

## Expected Result:
Link is working for Viewing all receipts option

## Actual Result:
Link is not working for Viewing all receipts option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99197946-5454-456c-bb89-7ec568f8515c

https://github.com/Expensify/App/assets/93399543/a1246985-0ec2-4657-a1f4-ce8dd7821fd7

https://github.com/Expensify/App/assets/93399543/adcb77fb-c4b2-457a-a8e9-9ea0bdf9912d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686726774076549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9e23c776186a8a6</li>
        <li>Upwork Job ID: 1672142727528816640</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
@parasharrajat proposal from @bernhardoj ready for review when you get a chance - thanks!

**Comment by cead22** [comment]
Nice catch, sounds like this is a regression right? 

The approach looks good to me, but we probably need to do something different in the failure case than `.catch(() => buildOldDotURL(url))`, because in that case we're gonna end up opening a link that doesn't work. In the commit you linked we do `Growl.show(response.message, CONST.GROWL.WARNING);` if the request fails, where I believe the message comes from the exception we throw in the backend and says "Cannot redirect to Expensify.com at the moment, please try again"

**Comment by bernhardoj** [comment]
> sounds like this is a regression right?

Yes

> we do Growl.show

I think we want to [remove all Growls](https://github.com/Expensify/App/issues/13229). I also think redirecting the user without `shortLivedAuthToken` is fine. It just won't auto logging-in the user (if the user is signed out).

**Comment by cead22** [comment]
As long as they land on the right page after signing in, I think that's good!

**Comment by bernhardoj** [comment]
PR is ready.

cc: @parasharrajat

**Comment by bfitzexpensify** [comment]
Offers have been sent out

**Comment by narzullome** [comment]
@bfitzexpensify Accepted thank you

**Comment by bfitzexpensify** [comment]
I like those @parasharrajat. Proposed they be added in https://github.com/Expensify/Expensify/issues/300649. Cool, we're all done here - thanks everyone!

**Comment by JmillsExpensify** [comment]
@bfitzexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @eVoloshchak's and @parasharrajat's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by bfitzexpensify** [comment]
Sorry, was OOO on Friday. 

Payments for each party:

Reporting: $250 for @narzullome, paid via Upwork ✅ 
Contributor: $1,500 (completion + #urgency bonus) for @bernhardoj, paid via Upwork ✅ 
C+: $1,500 (completion + #urgency bonus) for @parasharrajat, which will need to be paid via NewDot

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
