### ISSUE TITLE
Bank Account – User not landing on the same page where left after clicking " Continue with setup".

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open "Settings".
2. Click "Workspaces".
3. Click "Bank Account".
4. Click " Connect bank account".
5. Complete all steps until you reach step 4 “Additional Information”.
6. Now close the account page by clicking outside the page, like by clicking on any chat.
7. Repeat step 1 to 3.
8. Click " Continue with setup".
9. Notice that the user will jump directly to “validate bank account” bypassing step 4 “Additional Information” where he left.

## Expected Result:
User should land on the same page where left after clicking " Continue with setup".

## Actual Result:
User should land to “validate bank account” bypassing step 4 “Additional Information” where he left after clicking " Continue with setup"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/33221f4f-1f6b-4e9b-9887-cec0c09b503b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686379891068029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
Can't reproduce using the provided steps.

<img width="1204" alt="image" src="https://github.com/Expensify/App/assets/13206896/88a56b9e-83ff-474d-8d33-48e84701d7f8">

I followed your steps and click into another DM at "step 4 or 5", and when I clicked "continue setup" it took me right back where I was before.
