### ISSUE TITLE
[$1000] Web - Tooltip is missing on hover of profile pic in assign to me

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + icon and choose Assign task option
2. Enter title and press Next button
3. Click on Assignee
3. Hover on profile pic in Assign to me section

## Expected Result:
It should show tooltip same as we are showing tooltip in Recents section

## Actual Result:
It does not show tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23d5a0f5-5240-479c-99d8-ea1841c8caff

https://github.com/Expensify/App/assets/93399543/7e033561-4ae1-4d2f-942c-828ae70b8307

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686735870119099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d98b226dbfdf63e</li>
        <li>Upwork Job ID: 1673345972560203776</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
Able to reproduce on staging (web) latest desktop version, and web.

**Comment by adelekennedy** [comment]
Moving to external

**Comment by adelekennedy** [comment]
unassigning Joe - I will be back tomorrow
