### ISSUE TITLE
User can copy flagged content by using context menu "Copy to clipboard"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from user A to user B
2. Flag the content as offensive on user A's device
3. After the content has been hidden due to being offensive hover over the content and click on the "copy to clipboard" icon
4. Paste the content in the composer

## Expected Result:
User should not be able to copy hidden offensive content

## Actual Result:
User is still able to copy content to clipboard after being hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99591714-4595-4955-aa23-05dc3d8e70c3

https://github.com/Expensify/App/assets/93399543/223dc479-261a-4656-94b5-d6abeeb2a967

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686729940462759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Hmm - I don't think this is a bug.  If you select to reveal something marked offensive, there is no reason you shouldn't be able to copy that.

**Comment by slafortune** [comment]
Agreed to leave as is - https://expensify.slack.com/archives/C049HHMV9SM/p1686729940462759
