### ISSUE TITLE
Full user details are not shown when clicking avatar in chat header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account and login to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Search for any existing account and open a chat
3. Click on the avatar of the user
4. Observe that profile details are not fully shown only user name and avatar are visible
## Expected Result: 
Account details should be visible when clicking on the avatar
## Actual Result: 
Profile details are not fully shown only user name and avatar are visible
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9cb70d7d-a236-4dba-bbaa-83ba7faa96ac

<img width="949" alt="Screenshot (372)" src="https://github.com/Expensify/App/assets/43996225/c4c14532-d86d-4d9d-bd5a-357eaf2b7ac9">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687325738870599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
The expected behavior is what's happening in staging, production will be updated soon, with the next deploy
