### ISSUE TITLE
[$1000]  Web - The copy to clipboard is seen on the sign in page too on public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new room in public mode
3. Click on room header and copy the URL
4. Open an incognito window and paste the URL (male sure you're not signed on staging before)
5. Right click on 'here' so that 'Copy URL' option opens up
6. Click on the Copy URL option and notice that the 'Copy URl' button is still showing on the sign in page for a period of time

## Expected Result:
The copy to clipboard should not be seen on the sign in page on public room

## Actual Result:
The copy to clipboard is seen on the sign in page too

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/90a7beaf-c5a8-49eb-8134-8f59855e6976

https://github.com/Expensify/App/assets/93399543/1834ceaa-2492-4c8b-88e4-6dc22030e992

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686739229581989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123e154d1a63d268a</li>
        <li>Upwork Job ID: 1671864896761204736</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Thank you for finding the dupe, @fedirjh! I didn't use the right keywords to surface that.
