### ISSUE TITLE
Web - Clicking on 'Contact method' on a public room goes back to the homepage immediately after the sign in page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a room in public mode
3. Click on header of the room and copy the share URL
4. Open an incognito window (make sure you're not signed in earlier)
5. Paste the URL of the room
6. Click on 'here' link so that it opens up the display name page
7. Enter any name click on save
8. Now click on contact method and notice it navigates you to the sign in page
9. Wait for sometimes. and it automatically then navigates you back to the homepage earlier and doesn't allow you to enter sign in credentials

## Expected Result:
Sign in page should remain so that user could enter credentials

## Actual Result:
Clicking on 'Contact method' on a public room goes back to the homepage immediately after the sign in page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dc119b3e-1de4-484e-8834-c1123d64ecd3

https://github.com/Expensify/App/assets/93399543/91354ada-438c-46b6-8c90-c31e4d4b81db

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686741175244719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I don't get the "here" message: 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/c0b275a6-9548-43c3-a93a-d46515725b7c">

**Comment by muttmuure** [comment]
I don't have more time to keep working on this today so I am going to come back tomorrow. There are a lot of bugs with this flow

**Comment by muttmuure** [comment]
Still need to focus on clear reproduction steps

**Comment by muttmuure** [comment]
I'm unable to reproduce this, because the **Here** message doesn't appear at all in step 6. 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/f9ca33ca-b616-41df-8498-baeca4b642ad">
