### ISSUE TITLE
 Needless actions are being shown for the concierge message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Search your another account and send a message
2. Log in to another account
3. Go to the chat and flag the message
4. Hover over the concierge message that gets generated after flagging the message

## Expected Result:
User shouldn't see the option that are not useful i.e. reactions, thread, mark as unread. I think we can also remove copy to clipboard option.

## Actual Result:
We can take different actions just like any other normal message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-14 at 3 27 07 PM (1)](https://github.com/Expensify/App/assets/93399543/3fedd5ef-d920-43bc-b41e-e570e4a3fb04)

![image (76)](https://github.com/Expensify/App/assets/93399543/ee93e52d-fca4-43a8-bd19-e7aca57e858d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686737430900749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
I think based on the discussion on [this slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1686585176474969?thread_ts=1684756127.730389&cid=C049HHMV9SM) maybe we should keep the actions.

**Comment by tjferriss** [comment]
Agreed. I'm going to close the issue based on the conclusion of the Slack thread.
