### ISSUE TITLE
[HOLD Wishlist] mweb - Chat - Page flickers and attachment is swiped further than intended

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any chat with attachments.
3. Tap on the attachment.
4. Swipe through the attachments.

## Expected Result:
No flickering issue or skipping issue when swiping through attachments.

## Actual Result:
Sometimes the page flickers and the attachment is swiped further than intended.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6bda7daf-6b1f-433f-a0b6-14fcc5888d8e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
From the [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1687427798253009) discussion, which should be closed and fixed with changing FlatList for Wishlist

**Comment by mountiny** [comment]
It was raised here, I think we can put this issue on hold for wishlist https://github.com/Expensify/App/pull/20245#issuecomment-1594664744

**Comment by dylanexpensify** [comment]
hold still

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
still hold

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
held

**Comment by dylanexpensify** [comment]
@mountiny should we just close this?

**Comment by mountiny** [comment]
Yeah lets close this
