### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Different sections opened clicking on empty space in thread header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Send message
3. Reply with a thread
4. Open the threaded chat
5. Click on 'From user name' link
6. Verify that user is navigated to the main chat
7. Open the threaded chat again
8. Click on the blank space next to the thread header name
9. Obsereve that the details sidebar is opened
10. Close the sidebar & click on a blank space next to 'From user name' link
## Expected Result: 
Details sidebar should be opened counting all the blank parts of the header as part of the header to avoid confusion. And clicking only the link should navigate user to main chat
## Actual Result: 
User is navigate back to main chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/843eddd9-41cd-4b25-8a7b-ac1b666aa8ff)

https://github.com/Expensify/App/assets/43996225/60f1f2c7-6ec7-4773-bd88-e06281ee726d

https://github.com/Expensify/App/assets/43996225/83140a71-6c80-4212-a396-62079ae46d7e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686816426119499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e25a8a95ef65423b</li>
        <li>Upwork Job ID: 1672116435942555648</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different sections opened clicking on empty space in thread header

### What is the root cause of that problem?
Subtitle expands to full width here.
https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/pages/home/HeaderView.js#L199-L203

### What changes do you think we should make in order to solve the problem?
Just need to add `styles.alignSelfStart`

Change line 200 to -
```javascript
style={[styles.optionAlternateText, styles.alignSelfStart, styles.textLabelSupporting, styles.link]}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different sections opened clicking on empty space in thread header

### What is the root cause of that problem?
By default the align-items is stretch which will makes the subtitle to takes full available width and that is the reason for the issue. 

### What changes do you think we should make in order to solve the problem?
Pass style prop here for `PressableWithoutFeedback` with `style={styles.alignSelfStart}` which will restrict the stretching and takes only required width.

https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/pages/home/HeaderView.js#L192-L198

**Comment by sophiepintoraetz** [comment]
Will look into this tomorrow - overrun with some other chores.

**Comment by sophiepintoraetz** [comment]
![2023-06-23_17-32-09 (1)](https://github.com/Expensify/App/assets/42940078/3aae7d70-3f2c-4ce5-b1c0-75f9b210ff64)


I think this may have come from PR https://github.com/Expensify/App/pull/20484 (cc @chiragsalian)

**Comment by sophiepintoraetz** [comment]
@mananjadhav - we've got a couple of proposals, are you able to review them, please? 🙏

**Comment by mananjadhav** [comment]
Thanks for the proposals folks. I was checking if `max-content/fit-content` will work on all platforms. Basic testing shows it did. I think @Nikhil-Vats's [proposal](https://github.com/Expensify/App/issues/21215#issuecomment-1600981571) looks good.  The `alignSelfStart` won't work as it overflows the content when the text is longer. We would end up adding more fixes, if `max-content` works then it would be a simple fix.




🎀 👀 🎀 C+ Reviewed.

**Comment by Pujan92** [comment]
@mananjadhav fit-content or max-content I think will not work in the native. I updated [my proposal](https://github.com/Expensify/App/issues/21215#issuecomment-1600994031) to overcome the overflow issue with simple change.

**Comment by mananjadhav** [comment]
That's weird, I just checked this on iOS by adding the style and hardcoded text. I'll check once again.

**Comment by mananjadhav** [comment]
Okay for some reason I am unable to reproduce the above error consistently (probably some issue with my iOS build taking cached version). I was able to reproduce the max-content error once. Hence, it won't work.

@MariaHCD Apologies for the confusion, but using @Pujan92's updated [proposal](https://github.com/Expensify/App/issues/21215#issuecomment-1600994031) makes sense.


<img width="437" alt="image" src="https://github.com/Expensify/App/assets/3069065/2dddbe98-15de-4ecc-bb4e-4b15be709499">

**Comment by Pujan92** [comment]
@mananjadhav @MariaHCD  [PR](https://github.com/Expensify/App/pull/21776) is ready for review!

**Comment by sophiepintoraetz** [comment]
@mananjadhav - if you can complete the checklist, that would be great!

**Comment by mananjadhav** [comment]
@sophiepintoraetz thanks for the bump, I'll finish this over the weekend.

**Comment by mananjadhav** [comment]
The offending PR is https://github.com/Expensify/App/pull/20484. I've posted the [comment](https://github.com/Expensify/App/pull/20484/files#r1258583168) in the PR. I think the issue occurred because we copy pasted the Text content, which didn't have the click behavior earlier.

**Comment by sophiepintoraetz** [comment]
Thanks @mananjadhav - I agree if it was lack of attention to detail, there's no update needed here. Thanks for posting the FYI - contracts are out!

**Comment by Pujan92** [comment]
@sophiepintoraetz payment is yet to be received for the contract. Can you plz check once? Thanks!

**Comment by sophiepintoraetz** [comment]
@Pujan92 - some patience would be good here - payments are manually processed so I have to wait until you accept the offer in order to pay you - and there are other pieces of work I am doing!

**Comment by Pujan92** [comment]
I actually accepted the offer earlier. Usually, GH issue gets closed after the payment so thought of putting a message here. Sorry but didn't mean to rush here for payment.

**Comment by mananjadhav** [comment]
@sophiepintoraetz I've requested the payout via NewDot.

Thanks for the patience here @Pujan92.  Have you accepted the offer and paid out now?

**Comment by sophiepintoraetz** [comment]
Yep, he  should have been paid! And yes - I realise that change has just gone live, Anu should be taking care of that.

**Comment by mananjadhav** [comment]
Yes thats right. Thanks for your help here.

**Comment by Pujan92** [comment]
Yes, I got paid. Thanks!

**Comment by anmurali** [comment]
Paid Manan after confirming here.
