### ISSUE TITLE
[HOLD for payment 2023-07-03] __FAKE__ is shown as the actor for the report preview action when requesting money from a workspace

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#21216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As a non-admin member of a workspace, go to the workspace chat
2. Request money
3. Verify that the report preview action has the workspace avatar and display name

## Expected Result:
The workspace should be the actor that owes money

## Actual Result:
__FAKE__ is shown as the actor of the report preview

## Workaround:
No workaround.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
hahah, smart Melvin... assigned the best possible bug zero team member for this one 🤩 

@JmillsExpensify This is occurring because of the big [Auth PR](https://github.com/Expensify/Auth/pull/7976) that we merged. [A PR](https://github.com/Expensify/App/pull/20941) with the fix is ready for review.

**Comment by abdulrahuman5196** [comment]
Hi @cristipaval, Could you kindly assign me to this issue for C+ review?

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Internal changes mentioned here - https://github.com/Expensify/App/issues/21216#issuecomment-1600976030

>Determine if we should create a regression test for this bug.

yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) As member of a workspace, go to the workspace chat
2) Request money
3) Verify that the report preview action has the workspace avatar and display name as the actor

**Comment by abdulrahuman5196** [comment]
@JmillsExpensify Could you kindly close out on the payment for this issue? Pending for 10 days now.

**Comment by abdulrahuman5196** [comment]
@JmillsExpensify / @cristipaval Could you kindly process payment on this issue? Waiting for more than 2 weeks?

**Comment by JmillsExpensify** [comment]
Apologies for the delay. Always feel free to reach out to me on chat. Upwork job [is here](https://www.upwork.com/jobs/~01866d7786b83bea6c) and I've sent over a contract.

**Comment by JmillsExpensify** [comment]
Alright, all paid out. Sorry again!
