### ISSUE TITLE
Dev: Android - Clicking on "Message user1" opens the thread message instead of the main chat when returning from the thread message to the user profile

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Click on "Reply in thread"
4. Click on "From user1"
5. Go to the user profile
6. Click on "Message user1"

## Expected Result:
Clicking on "Message user1" should open the main chat, not the thread message

## Actual Result:
Clicking on "Message user1" opens the thread message when returning from the thread message to the user profile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b91c07b6-1367-4c87-bf7b-93f691238681

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686745427829329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Reviewing

**Comment by greg-schroeder** [comment]
I can't reproduce this - clicking on the message button sends me back to the main chat thread. 🤔
