### ISSUE TITLE
[HOLD #11768] App navigates back to main chat if user clicks on invalid link in reply in thread and refreshes on 'Hmm its not here' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open user B chat
3. Send any message
4. Hover on message and click on reply in thread
5. Send invalid expensify link eg: https://staging.new.expensify.com/r/49350451043078467
6. From any other device, login with user B
7. Open user A chat and click on latest message that has replies in thread
8. Click on replies and click on invalid expensify link sent by user  A
9. Click on back to see that normally it navigates back to thread of reply in thread
10. Again click on invalid link and reload the page
11. Click on back to see that now it navigates back to main thread

## Expected Result:
 App should navigate back to thread of reply in thread if we click on any invalid expensify link in thread and press back

## Actual Result:
App navigates to main thread rather then thread of reply in thread if we click on any invalid expensify link, reload and then press back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9dd96655-73cc-4ecc-a033-dcafd68e594c

https://github.com/Expensify/App/assets/93399543/b4a1769c-f44f-4a15-8fef-1e89ad5416ea

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686754122973049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Putting on hold, commented here
- https://github.com/Expensify/App/issues/11768

**Comment by mountiny** [comment]
I think this is expected. The information about where the UP button in the thread should go will be lost after the refresh as we only know the id of the invalid report.

I dont think this is a bug to work on, basically this is invalid report id which normal users dont get and the up button takes you to valid report.

Closing, feel free to reopen if you diagree
