### ISSUE TITLE
Workspace - If admin located at the end of the list select admin warning appears cut off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20687
## Action Performed:
Precondition - Admin is located at the end of Workspace members list;
There are 8+ members in the Workspace;

1. Open http://staging.new.expensify.com/
2. Open Settings
3. Click "Workspaces"
4. Click on Workspace from the precondition
5. Click on "Members"
6. Click on Admin member at the bottom of the list

## Expected Result:
The warning that appears is completely visible - "You cannot remove yourself or the workspace owner"

## Actual Result:
The warning that appears is cut off at the bottom so user have to scroll the list down a bit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/52b166cb-05d0-4dfc-861a-881768ddfa24

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Hm, I'm not sure if this is a bug. @shawnborton should the page "jump" up so the error is in view? It just looks like the scroll position was maintained to me.

**Comment by shawnborton** [comment]
Yeah, I don't think this is a bug, let's close.

**Comment by trjExpensify** [comment]
Thank yah, kindly!
