### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-02] Dev: Flipper is broken

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#21239]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. `npm run ios`
2. Open Flipper

## Expected Result:
I can see logs, the React component tree, etc, within Flipper

## Actual Result:
I cannot do anything useful in Flipper (such as see logs or the React component tree)

## Workaround:
Manually modify `package.json` as described [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1677948615578189?thread_ts=1677165853.274999&cid=C01GTK53T8Q)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1677948615578189?thread_ts=1677165853.274999&cid=C01GTK53T8Q, https://expensify.slack.com/archives/C01GTK53T8Q/p1680121805775169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0f1d615ce8a1fcb</li>
        <li>Upwork Job ID: 1686681607650160640</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by amyevans** [comment]
Hey @laurenreidexpensify the PR for this is merged already, I just applied the bug label to get help with payment for the C+ PR review. Thanks!

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 offer sent in upwork for payment

**Comment by abdulrahuman5196** [comment]
@laurenreidexpensify Thank you. Accepted the offer.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ review: $1000, payment issued to @abdulrahuman5196 in Upwork
