### ISSUE TITLE
[HOLD for payment 2023-07-17] Hide `Send money` from the front-end

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#21233]
### Problem
`Send money` is a beta feature that we don't have immediate plans to launch, nor it is even finished. The thing is though, we're treating it as part of the platform even despite this, which creates a bunch of extra work and upkeep that sucks focus and urgency from reunification. 

### Solution
Let's hide `Send money` from from global create the only place where it currently exists. In addition, let's remove documentation related to `Send Money` on https://help.expensify.com/hubs/send-money.

**Comment by JmillsExpensify** [comment]
cc @maddylewis what's the process for removing the documentation, once `Send Money` is removed?

**Comment by maddylewis** [comment]
here are the instructions on how to delete an article - https://stackoverflowteams.com/c/expensify/questions/15144

**Comment by maddylewis** [comment]
im not sure how to delete a hub off of the top of my head, but we're planning to delete/restructure the existing hubs so that will happen relatively soon via https://docs.google.com/document/d/1MjTYzA-uo7ShLjo8x3XLA7EkSAhx0Yc9W43PPnKV3co/edit.

i can track down how to delete a hub from the site in the meantime!

**Comment by maddylewis** [comment]
@johncschuster - do you know how to delete a hub on the help site? i _think_ we would need to delete/move the articles from the `Send Money` hub first and then we'd have to the option to delete a hub? 

i was trying to work backwards using these instructions - https://stackoverflowteams.com/c/expensify/questions/15131

**Comment by marcaaron** [comment]
👀  at this 🔜

**Comment by marcaaron** [comment]
@maddylewis I will try to get @marcochavezf to help us with this. I made some edits for the docs if you want to take a look at what I did [here](https://github.com/Expensify/App/pull/22226/files). Mainly just removed all the references to "Send Money".

**Comment by maddylewis** [comment]
@marcaaron - thanks, let me take a look!

**Comment by marcaaron** [comment]
Just a heads up these changes are on staging now so we should be removing "Send money" in the next App release.

**Comment by Santhosh-Sellavel** [comment]
Requested payment on ND

**Comment by anmurali** [comment]
Approved $1k for Santhosh for this PR

**Comment by marcaaron** [comment]
Not Overdue

**Comment by Santhosh-Sellavel** [comment]
@marcaaron We can close this, payments are settled!
