### ISSUE TITLE
Green dot doesn't disappear on User B side, if User A deletes the mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21244]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging on web chrome and login with User A
2. Go to a chat with User B and send a message
3. Login with User B on another web chrome and notice that on LHN it displays as bold text (unseen) and notice no green dot is present for normal texts (Do not open the chat)
4. Now from User A, mention the User B email address and send it on the chat
5. On User B side, notice that a green dot appears for a mention text
6. On User A side, now delete the mentioned email
7. On User B side, notice that the green dot doesn't disappear
8.. Thus, if green dot is only shown for mentioned texts , then it should have disappeared on User's B side when User A deleted the mentioned email text
## Expected Result: 
Green dot shoudl disappear on User B side, if User A deletes the mention
## Actual Result: 
Green dot doesn't disappear on User B side, if User A deletes the mention

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/82bd65cc-43bb-41f5-88af-9e9979be3972

https://github.com/Expensify/App/assets/43996225/625c60a7-97be-4a60-9ba0-4f7c2b513f4b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686818102691209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
Seems a backend change where `lastMentionedTime` of the report needs to be updated when the mentioned unread message gets deleted.

**Comment by NicMendonca** [comment]
Discussed[ here](https://expensify.slack.com/archives/C01SKUP7QR0/p1687479596856679)

This isn’t a bug but a specific choice we made not to support
