### ISSUE TITLE
Send money- Send money message displayed only after page refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21270]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20895
## Action Performed:
1. Open the app
2. Open any report
3. Send any text (Hello)
4. Send money to report

## Expected Result:
Send money message displayed

## Actual Result:
Send money message displayed only after page refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f86bb75d-9596-4395-b505-884d5aafad71

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I'm heading OOO until Tuesday so reassigning until I come back (Staying assigned for that purpose!)

**Comment by trjExpensify** [comment]
We're actively not focusing on send money bugs right now https://expensify.slack.com/archives/C01GTK53T8Q/p1687388507073569

Going to close this.
