### ISSUE TITLE
Correction focus is not applied to checkbox when clicking 'fix the errors' link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Workspaces' link
3. Open an existing workspace
4. Click on 'Cards' link
5. Click on 'Connect bank account' button
6. Click on 'Connect manually' button
7. Enter wrong routing number > remove focus from routing number input field > click on 'fix the errors' link > verify that focus is applied to routing number input field
8. Enter a correct Routing number & Account Number & do not check the checkbox
9. Click on 'Continue' button > verify that error is thrown
10. Click on 'fix the errors' link
## Expected Result: 
Correction focus should be applied to the checkbox in the same manner as Routing number input field
## Actual Result: 
Correction focus is not applied to the checkbox

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ba847232-d1cd-4293-b621-b7343253a2c1

https://github.com/Expensify/App/assets/43996225/7aa20365-ba2c-411e-aff2-567a5b13de78

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686831341996769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
> 1111 is a correct account number so everything works well. Not a bug

The bug is not about the account number, it is about the checkbox. When you don't check the checkbox and click on fix the errors link, the checkbox should be highlighted with green.

**Comment by anmurali** [comment]
Closing since it is being fixed in https://github.com/Expensify/App/issues/20869
