### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Requesting magic code from 'Magic code' page doesn't clear all sign-in errors

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Enter email > click on 'Continue' button
3. Copy expired magic sign-in link from previous interaction
4. Paste to browser > prefix the link with 'staging' text > press enter
5. Verify that 'Magic code expired' page is displayed
6. Switch to the tab where sign-in page is opened
7. Click on Sign-in button
8. Switch to the tab where 'Magic code expired' page is displayed
9. Click on 'request a new code here!' link
10. Switch to the tab where sign-in page is opened
## Expected Result: 
All error messages including 'Please enter your magic code' should be cleared in the same manner as requesting magic code from sign-in page clears all errors
## Actual Result: 
'Please enter your magic code' error message is not cleared

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/55a56e1e-317e-4a19-91c1-50c24150b139

https://github.com/Expensify/App/assets/43996225/2373a403-6e38-42af-b2fb-057a1824a4db

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686836451096149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f0afc70ce23ee77</li>
        <li>Upwork Job ID: 1671920220866732032</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Chatting in Slack on this one. DIdn't realize this could be done. Let's do it!

**Comment by twisterdotcom** [comment]
@aimane-chnaif two proposals to review here. Let's see if we can get this moving and maybe even merged this week!

**Comment by twisterdotcom** [comment]
Bump on this @aimane-chnaif

**Comment by twisterdotcom** [comment]
I am OOO! Adding another BZ member for the week.

**Comment by Natnael-Guchima** [comment]
@JmillsExpensify the link is removed from the page on the latest PR. I don't think there is a need to pursue this issue. 

![image](https://github.com/Expensify/App/assets/57330233/34c3cb6d-15c1-487d-b713-d4a09de09296)

**Comment by twisterdotcom** [comment]
We implemented the timer, but you see, I requested a new code in the tab on the right here, but it didn't clear the error in the tab on the left:
<img width="3289" alt="image" src="https://github.com/Expensify/App/assets/9133401/64b4d5dd-4b55-45a8-b842-064804e34ae4">

I think @tienifr's proposal would do that, which is a neat improvement right? We just need @aimane-chnaif to review it.

**Comment by twisterdotcom** [comment]
Going to reclassify this as nNw Feature though.

**Comment by Natnael-Guchima** [comment]
Contributor details
Your Expensify account email: natnaelguchima12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

**Comment by garrettmknight** [comment]
Following this issue to pay out [this bug report](https://github.com/Expensify/App/issues/22963) when it's fixed.

**Comment by twisterdotcom** [comment]
Payment due tomorrow.

External issue reporter: @Natnael-Guchima due $250: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25751090
Contributor that fixed the issue: @tienifr due $1000: https://www.upwork.com/nx/wm/workroom/34187190/overview
Contributor+ that helped on the issue and/or PR: @aimane-chnaif due $1000: https://www.upwork.com/nx/wm/workroom/34202522/overview

**Comment by twisterdotcom** [comment]
All paid out.
