### ISSUE TITLE
[$1000] Dev: IOS - The assignee's username with a long name overflowing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to Settings > Profile > Display name
2. Enter a long first name and last name
3. Close the popup modal
4. Go to "Assign task"
5. Enter a title and select an assignee with a long username
6. Click on "Confirm task"

## Expected Result:
The assignee's username with a long name should not overflow

## Actual Result:
The assignee's username with a long name is overflowing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e7f25ffc-e103-45c1-a73c-34facb359288

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686780629296329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a30f9356fb072fd6</li>
        <li>Upwork Job ID: 1672349320195309568</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
We're already working on a re-design of the task view here https://github.com/Expensify/App/issues/19330

Let's wait until that is done to see if this is still a problem

**Comment by flaviadefaria** [comment]
Sounds good. I'll switch this to weekly in the meantime. Once we remove this from hold then we can switch it back to daily.

**Comment by flaviadefaria** [comment]
Oh that looks like a super long issue so will switch this to montly.

**Comment by thienlnam** [comment]
The held PR is off hold - I believe we can close this now after paying out the reporter

**Comment by flaviadefaria** [comment]
Offer sent to @ayazhussain79. I'll pay them as soon as they accept the offer!

**Comment by ayazhussain79** [comment]
@flaviadefaria offer accepted, Thank you
