### ISSUE TITLE
[Awaiting payment]Server error when trying to message user from profile page

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#21304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Login to expensify staging using account 1
2. Search for an account that account 1 has no prior chat history with
3. Click on the searched account and go to chat and see concierges this is your first time chatting... message
4. Click on the profile of the searched account
5. Click on message [searched account address] button in the profile page
6. Observe an "Auth GetRestrictedAuthTokenByAccountID returned an error" is shown

## Expected Result:
Describe what you think should've happened
The user should be taken to the chat with out any errors
## Actual Result:
Describe what actually happened
Auth GetRestrictedAuthTokenByAccountID returned an error is shown to the user

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
None
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687409569320379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a340248e36d52495</li>
        <li>Upwork Job ID: 1671842262055833600</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment]
Unassigning C+ as it is server side fix

**Comment by NicMendonca** [comment]
@MonilBhavsar heads up I am going OOO until Wednesday. Please re-assign if action is required before then. Otherwise, I will be back to issue reporter bonus by next week.

**Comment by NicMendonca** [comment]
Looks like the PR has been merged: https://www.upwork.com/jobs/~01a340248e36d52495

@SofoniasN can you please apply to the job for reporting bonus?

**Comment by SofoniasN** [comment]
Hey @NicMendonca the just post is listed as private, hence i cant apply unless invited.

Here is my upwork profile link to make it easier for you for the invite
https://www.upwork.com/freelancers/~01af126bea0cac3ae8.

**Comment by MonilBhavsar** [comment]
Awaiting payment here

**Comment by NicMendonca** [comment]
@SofoniasN sorry! It's public now: https://www.upwork.com/jobs/~01a340248e36d52495

**Comment by SofoniasN** [comment]
@NicMendonca no worries! And I have applied for the job post on upwork.

**Comment by NicMendonca** [comment]
@SofoniasN  paid, thank you!
