### ISSUE TITLE
 Old Dot Transition - Could not finish setting up Bank Account because of currency error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to NewDot and log out
2. Navigate to OldDot and login with an account that has a existing workspace without a bank account setup
3. Navigate to inbox and Search for the inbox task "Finish setting up...", click on "Continue Setup"

## Expected Result:
You should be redirected to NewDot and the "Connect Bank Account" should be displayed in the side bar with the same account as in OldDot

## Actual Result:
The "Connect Bank Account" is not displayed in the side bar. Message that my currency is set to a different currency than USD appears in NewDot even my default currency is set to USD.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8417df00-a368-4394-8248-0e6ad63fe6d9

https://github.com/Expensify/App/assets/78819774/c41663bd-2115-4b58-a075-725564fab1f8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
Seems like it's coming from this commit: https://github.com/Expensify/App/commit/158c34bc07477edcd74db91f000254e2261d5538

**Comment by Li357** [comment]
Discussion here: https://expensify.slack.com/archives/C03TQ48KC/p1687443100548609?thread_ts=1687442201.146869&cid=C03TQ48KC

**Comment by luacmartins** [comment]
Removing the blocker label, since this is not a blocker for App (the fix is in Web-E) and this flow is triggered from Web-E.

**Comment by Li357** [comment]
Not overdue, fix for Web-E deployed to staging
