### ISSUE TITLE
Update RN Reanimated, Gesture handler and Screens packages to newer versions

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#21308]
### Problem

Coming from [here](https://expensify.slack.com/archives/C04878MDF34/p1687434785645949)

We are soon going to update the app to the newly released RN 0.72.  That means we can also update other packages to the latest versions which support up to date RN.

### Why

This helps to get the most out of the packages for us.

### Solution

SWM can help us with this as they are maintainers of the packages.

Update:

react-native-reanimated 3.1.0 -> 3.3.0
react-native-gesture-handler 2.9.0 -> 2.12.0
react-native-screens 3.17.0 -> 3.21.0

**Comment by Skalakid** [comment]
Hey :wave: I’m Michał Skałka from Software Mansion, an expert agency, and I will help close this issue out

**Comment by mountiny** [comment]
@fabioh8010 Could you please bump these libraries as part of this PR too https://github.com/Expensify/App/pull/18507

**Comment by mountiny** [comment]
@Skalakid can help with any issues with the update.

**Comment by Skalakid** [comment]
@mountiny Yes of course :D @fabioh8010 If you have any questions/problems with updating these packages feel free to contact me

**Comment by fabioh8010** [comment]
@Skalakid @mountiny I bumped those libraries in the PR and it seems everything is ok for now 😄

**Comment by mountiny** [comment]
lovely

**Comment by mountiny** [comment]
The PR is still going, its a major change so it takes a bit of time

**Comment by mountiny** [comment]
This is the PR fixing this https://github.com/Expensify/App/pull/18507

**Comment by CortneyOfstad** [comment]
Still waiting on the PR 👍

**Comment by CortneyOfstad** [comment]
No update yet 👍

**Comment by mountiny** [comment]
Hopefully merged soon, I think we can actually close this in favour of https://github.com/Expensify/App/issues/18444 no reason to keep them both open given its all happening in one PR

**Comment by puneetlath** [comment]
The automation didn't work for some reason. Added hold for payment to the title.
