### ISSUE TITLE
[Payment due for bug reporter] Not able to create group chat w/ previously created, closed account

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#21301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. With any User A, create a chat w/ a brand new User B that doesn't exist yet (this will create their account in a closed state)
2. With User A, create a group chat w/ User B & someone else (note: You shouldn't have validated / opened User B's account
3. Send a message in the group

## Expected Result:
Message sent no problem

## Actual Result:
Error b/c the report "doesn't exist"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Latest
**Reproducible in staging?:** Y
**Reproducible in production?:** I think so
**Notes/Photos/Videos:** Any additional supporting documentation
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686830907312449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01795abb17cea37da1</li>
        <li>Upwork Job ID: 1671826853283938304</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
Sorry @thesahindia - unassigning since this is a backend fix

**Comment by Beamanator** [comment]
PR up: https://github.com/Expensify/Web-Expensify/pull/37914

**Comment by Beamanator** [comment]
PR CP'd to staging & prod - will close this once i test in prod

**Comment by Beamanator** [comment]
Closing as this tests well on staging & prod

**Comment by slafortune** [comment]
Offer sent @niravkakadiya25 👍

**Comment by niravkakadiya25** [comment]
Accepted

**Comment by slafortune** [comment]
Paid
