### ISSUE TITLE
 Request Money - Errors happen when sending money requests back and forth between users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21317]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. A send money request to B
2. Then B send money request back to A (with same amount - maybe)
3. Repeat step # 1 and # 2 few times

## Expected Result:
The requests should be send successfully

## Actual Result:
There are some errors happens (view more details in thread)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/947d9027-0988-4bb6-a701-89b4d024c6bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686888687225899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tranvantoan-qn** [comment]
It happens frequently on my side. The main difference between my account and @kbecciv's is the **currency**. My currency is **VNĐ**. When I change my currency to something other than USD (_by changing my IP address_), I also see other issues happen.

So it may have something to do with currencies. Let's try changing it and then reproduce the issue.

![Error](https://github.com/Expensify/App/assets/10254571/6f26cf85-0ed5-4207-985e-1987cff9f6fd)
![Currency Error](https://github.com/Expensify/App/assets/10254571/65e6f129-c64e-4437-94ca-8a862ef36484)

**Comment by marcaaron** [comment]
@mountiny @luacmartins Do we have anything like a milestone for clean up issues related to Manual Requests?

**Comment by luacmartins** [comment]
I've just been adding them to the main tracking issue and the w3 milestone

**Comment by mountiny** [comment]
there is the wave3 project which is handy, added it there

**Comment by michaelhaxhiu** [comment]
Hm I'm having a hard time reproducing. Are we adding this to the milestone because you reproduced @mountiny ?

**Comment by mountiny** [comment]
Nope i havent reporduced, havent tried. if you cannot reproduce we can ask qa to check and close if no luck

**Comment by michaelhaxhiu** [comment]
Ah got it! QA had issues reproducing too initially. Hmm.

**Comment by michaelhaxhiu** [comment]
@tranvantoan-qn can you help me by expanding the steps you took? let's take this back to the slack thread to nail down the reproduction steps.

**Comment by tranvantoan-qn** [comment]
@michaelhaxhiu @mountiny 
After hours of breaking down the issue step-by-step and creating dozens of new test accounts, I was finally able to figure out the clear steps that caused it to happen (though they don't look the same as the original steps but the output is 100% the same)

1. Login 2 fresh accounts A and B (_not required but fewer data will make the flow easier_)
2. From Account A: 
    2.1. Send Money request to B with `amount = XXX` (see video at `0:10`)
    2.2. On LHN: Click on the chat that says `B owes XXX` - the ọne with Green Dot _(this may be optional_) - see video at `0:36`
    2.3. Logout and login to account A again
    2.4. On LHN: Click on the chat that says `B owes XXX` - the ọne with Green Dot again - (see video at `1:21`)
3. From Account B:
    3.1.  Click on the chat that says `B owes XXX` (see video at `1:31`)
    3.2. Click the `I'll settle up elsewhere` button on the header 
4. From Account A: Make another Money request to B with the same amount XXX (see video at `1:50`)

>> Error will appears

**Comment by mountiny** [comment]
Thanks! @michaelhaxhiu are you able to reproduce this with these set of steps?
