### ISSUE TITLE
[$1000] Issue for payment for #19349

### ISSUE THREAD

**Issue by johncschuster** [Expensify/App#21315]
I accidentally blocked some invited contributors from a job in Upwork. I've created this issue to pay them.

(Original issue [here](https://github.com/Expensify/App/issues/19349))

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5a9ff842ec5cddb</li>
        <li>Upwork Job ID: 1671986201630617600</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
@ayazhussain79 and @dukenv0307, can you assign yourselves to this issue? I'm going to create the job automatically after you've been assigned to see if the the label will _not_ assign anyone else.

**Comment by ayazhussain79** [comment]
Ok so upwork job will be created automatically?

**Comment by ayazhussain79** [comment]
I can't either assign myself

**Comment by abdulrahuman5196** [comment]
@johncschuster Gentle note: Contributors don't have permission to assign to issue. Only employees do.

**Comment by johncschuster** [comment]
Hmm... I'm not able to assign this to either @ayazhussain79 or @dukenv0307. I don't even see them in the assignee list. 🤔

Welp... that test didn't go like I thought it would 😂

**Comment by johncschuster** [comment]
I'll go ahead and create the new Upwork job and just kick anyone out that shouldn't be involved.

**Comment by johncschuster** [comment]
@dukenv0307 and @ayazhussain79, can you try applying to the job linked above? Thank you!

**Comment by ayazhussain79** [comment]
@johncschuster applied Thank you

**Comment by abdulrahuman5196** [comment]
@johncschuster should I apply again?

**Comment by situchan** [comment]
> Hmm... I'm not able to assign this to either @ayazhussain79 or @dukenv0307. I don't even see them in the assignee list. 🤔
> 
> Welp... that test didn't go like I thought it would 😂

Another gentle note: They should post at least one comment on GH to appear in assignee list.

**Comment by johncschuster** [comment]
@situchan 

> Another gentle note: They should post at least one comment on GH to appear in assignee list.

Whoa, I didn't know that. Thank you for explaining that!

**Comment by johncschuster** [comment]
@abdulrahuman5196 

> should I apply again? My contract on the original upwork job itself was started. So it should be fine i think. Let me know otherwise.

Nope! I just got you squared away on the original contract. Thanks for checking!

**Comment by johncschuster** [comment]
@ayazhussain79 @dukenv0307 I've just hired you. Can you ping me once you've accepted? I'll get payment issued shortly.

Thanks!

**Comment by ayazhussain79** [comment]
@johncschuster offer accepted, Thank you

**Comment by johncschuster** [comment]
@dukenv0307 paid! 🎉 

Thanks to everyone for being flexible!
