### ISSUE TITLE
[HOLD for payment 2023-07-20] Standardize on the iOS pod version to prevent the useless diff

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#21318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

cc @Expensify/mobile-deployers for your thoughts. Any concerns? Or suggestions for the version we align on?

# Problem

We don't have a standard cocoapods version, so as developers we often see a useless diff that changes the version to match our local version. This is mildly annoying and a bit confusing. 

![Screenshot 2023-06-22 at 15 57 53](https://github.com/Expensify/App/assets/10736861/12d09c5f-b1fe-4519-bb63-6a632deb29b3)

# Solution 

Align on a version, preventing this diff from being generated locally. 

____________

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1687224504406749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Aligning on a version sounds good to me. How are we thinking of enforcing it?

**Comment by lindboe** [comment]
A typical project would align on whatever's in the `Gemfile` (as this will also be updated in future React Native releases if an upgrade is needed).

To enforce that, some ideas, ranked by cost:

1. Using `bundle install` and  `bundle exec pod install` should be documented in the project setup steps
2. We could add an alias of `npm run pod install` that uses `bundle exec pod install`
3. We could create a Makefile system that runs all build setup steps (or permutations of it). This might have other benefits for the dev build experience, like ensuring that `patch-package` is run.
4. Could add a lint step to PRs that ensures either:
  a. re-running `bundle exec pod install` does not generate Podfile.lock changes
  b. that the Podfile.lock pod version matches the version in the Gemfile (requires parsing it)

**Comment by roryabraham** [comment]
Nice! I happened to suggest this same thing in a different context just this morning: https://github.com/Expensify/App/pull/18507#discussion_r1238756870

**Comment by lindboe** [comment]
@Julesssss we haven't worked on issues like this before, is the expectation that we make a proposal/get feedback or just make a PR and get feedback that way?

**Comment by roryabraham** [comment]
I think in this case you can just open a PR and get feedback that way 🙂

**Comment by Julesssss** [comment]
Yeah, no need in this case. Also I tagged everyone on the mobile deploy team, so silence is similar to approval 🙂

**Comment by luacmartins** [comment]
Agreed, just go for a PR here.

**Comment by lindboe** [comment]
Since this was merged to main, should we announce in the open-source channel that it should be used going forward?

**Comment by roryabraham** [comment]
Yep, let's do it 👍🏼

**Comment by lindboe** [comment]
Done: https://expensify.slack.com/archives/C01GTK53T8Q/p1689101140745419

**Comment by rushatgabhane** [comment]
Created a manual request for $1k https://staging.new.expensify.com/r/3818254714959864

**Comment by anmurali** [comment]
@Julesssss can you confirm?

**Comment by Julesssss** [comment]
Hey @anmurali, yep the default $1k is correct 👍

**Comment by Julesssss** [comment]
This isn't a regression, so I hid the regression checklist comment.

**Comment by JmillsExpensify** [comment]
Reviewed details for @rushatgabhane. This is accurate and approved for payment in NewDot.

**Comment by Julesssss** [comment]
Ready for payment

**Comment by Julesssss** [comment]
Not overdue, just awaiting payment

**Comment by Julesssss** [comment]
Hey @anmurali, I forgot to reassign while you were OOO, my bad. Please make the payment when you have a moment 👍

**Comment by anmurali** [comment]
Payments:
 - [ ] External issue reporter N/A
 - [ ] Contributor that fixed the issue @lindboe $1k - Can you please link me your Upwork profile cause I cannot find it to send an offer
 - [ ] Contributor+ that helped on the issue and/or PR - @rushatgabhane has been paid on new Dot
