### ISSUE TITLE
[HOLD] [TS Migration] Write a script that creates GH issues for migration tasks in a GH Project

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#21320]
- Create a GH Project
- Write a script

**Comment by hayata-suenaga** [comment]
Removing myself as @mountiny is working on this in [this PR](https://github.com/Expensify/Web-Expensify/pull/37920)

**Comment by mountiny** [comment]
Script is ready to be run

**Comment by hayata-suenaga** [comment]
The PR is still on HOLD

**Comment by hayata-suenaga** [comment]
still on hold

**Comment by mountiny** [comment]
This is on hold

**Comment by mountiny** [comment]
Not overdues still waiting with creating the issues.

**Comment by hayata-suenaga** [comment]
changing the priority so that you won't be pinged constantly Vit

probably we can run this script next week

**Comment by mountiny** [comment]
Done
