### ISSUE TITLE
navigates to thread instead of open profile details on click of users avatar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message and click on reply in thread option
3. send message in thread
4. go back to previous report screen
5. click on the avatar beside the reply counter
## Expected Result: 
should show profile details on click of the avatar
## Actual Result: 
navigates to reply thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0545f5aa-c1e0-4fee-b6af-c46dfb34e57b

https://github.com/Expensify/App/assets/43996225/a61d7e09-34be-401e-8ec5-33193dc42e6d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687411206897659?thread_ts=1686818499.920609&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
I don't think this behavior is a bug. If we are mirroring Slack's treatment of threads, for example, clicking the avatar of a user on a threaded message would bring you directly into the thread, not show you the user's profile.

![2023-06-26_10-41-43 (1)](https://github.com/Expensify/App/assets/5579997/fa0d91ce-6e68-490d-a283-739bef9ff583)
