### ISSUE TITLE
Web- Chat - Console error when when clicked the message body

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com 
2. Open an existing chat
3. Click on message body

## Expected Result:
No console error when when clicked the message body

## Actual Result:
Console error when when clicked the message body

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.2

**Reproducible in staging?:** y

**Reproducible in production?:** n

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0d1f257d-e672-4947-aa31-a62ce15235ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I just fixed this issue here - https://github.com/Expensify/App/issues/21339#issuecomment-1603165821

**Comment by luacmartins** [comment]
Closing since we have another issue for it.
