### ISSUE TITLE
[HOLD for payment 2023-07-06] ExpandURLPreview is being called for no reason

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#21368]
Steps:
- Open a new chat with someone you never talked
- See ExpandURLPreview being called

I think it also happens on attachments or other actions that have no html

**Comment by iwiznia** [comment]
Link to PR https://github.com/Expensify/App/pull/17288/files#diff-e632f3693dffc58adf371d4fb1289089c0291b6d1d94c44fe91a794dcdae2998R186

I don't think this needs a regression test at all, it was a mistake and it will be hard to reintroduce the bug. Plus nothing was technically broken.

**Comment by dylanexpensify** [comment]
Assigned! will get job post going today!

**Comment by dylanexpensify** [comment]
Post [here](https://www.upwork.com/jobs/~0116c54df986805cd7) to apply!

**Comment by rfwoolf** [comment]
Hi all,

I was not able to reproduce on web version:
>"Open a new chat with someone you never talked"
>"See ExpandURLPreview being called"

However, ExpandURLPreview does get called if you type a URL, e.g. `google.com` - but as far as I can tell, it is not being called using the steps above.

**Comment by rfwoolf** [comment]
Thank you - I hope you can understand my confusion:
6 gours ago, the job was posted on Upwork, and 
7 hours ago dylanexpensify said "Post here to apply!"

**Comment by dylanexpensify** [comment]
@parasharrajat you're paid in ND right?

**Comment by dylanexpensify** [comment]
@parasharrajat to be paid $1,000 for the issue. Cc @anmurali

**Comment by anmurali** [comment]
Approved based on above comment

**Comment by iwiznia** [comment]
Seems this is mostly ready, so not unassigning myself, but if this does not get closed, @dylanexpensify  please unassign and re-assign another engineer since I am going on sabbatical
