### ISSUE TITLE
New Chat/Group Search is focused only first time on iOS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Close the app if open already
2. Open the App
3. Click FAB -> New Chat/Group
4. Close the page
5. Again  Click FAB -> New Chat/Group
## Expected Result: 
The search bar is focused on every time while opening the New Chat or Group page. Like we do for the Chat Search option
## Actual Result: 
Only the first time on every launch the focus is set on the search bar.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Uploading GBTD0208[1].MP4…

https://github.com/Expensify/App/assets/43996225/9c533ba7-5166-4e36-90e3-6704e061610d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686862332446809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Decided to close, this is a dupe.
