### ISSUE TITLE
New Message go-to button does not take to the new message where the new line marker is.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21400]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app
2. Go to previous chats with long conversations.
3. Mark Unread a message that is at the top
4. notice the new line marker and the New Message go-to Button appear.
5. click the New Message go-to button.
6. Notice that clicking the New Message go-to button takes you to the last message, not to the start of the new message.
## Expected Result: 
Clicking the New Message go-to button should take you to the start of the new message.
## Actual Result: 
Clicking the New Message go-to button takes you to the last message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/011125d2-ee3b-4ee2-ad34-adca400376aa

https://github.com/Expensify/App/assets/43996225/498d426c-b76c-4db7-80e2-e19ed0103162

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686595634657789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I don't think this is a bug given that we don't support bi-directional scrolling in the app, though @chiragsalian do you want to confirm my opinion on this one? I think we're touching on a long-standing feature improvement that we hope to get to before end of year.

**Comment by JmillsExpensify** [comment]
Reached out to Chirag via DM.

**Comment by chiragsalian** [comment]
Sort of, more technically the issue here is that we don't currently support comment linking so any solution here would not be a perfect solution.

This is because if onyx does not have the index and we attempt to scroll to specific index then it can break functionality and do nothing. I think we should close out this issue and then revisit this once we have implemented comment linking because at that point we should be able to scroll to a specific comment even if its not in onyx.

**Comment by JmillsExpensify** [comment]
Cool, thanks for the gut check! I agree, closing this one out.
