### ISSUE TITLE
[Hold on #289050] mWeb - C in "connect online with plaid account" is not left aligned with C in "connect manually"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify
2. Go to a workspace
3. Click on bank account
4. Observe the two "connect"s are not properly left aligned

## Expected Result:
The Connect online with plaid account should be left aligned

## Actual Result:
Connect online with plaid account is misaligned with connect manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a 

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![iMarkup_20230616_193009](https://github.com/Expensify/App/assets/93399543/c1ae5971-ad4d-43cf-8115-90f5cbfeb17b)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686933577266069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
I think we should just put this on [Hold] for https://github.com/Expensify/Expensify/issues/289050

**Comment by anmurali** [comment]
Still held

**Comment by anmurali** [comment]
I think I am going to close this. We will certainly fix this as the whole flow is being refactored. I will pay @SofoniasN for reporting the bug! Can you please share your profile?

**Comment by SofoniasN** [comment]
@anmurali here is the link to my upwork profile https://www.upwork.com/freelancers/~01af126bea0cac3ae8

**Comment by SofoniasN** [comment]
@anmurali a humble bump

**Comment by SofoniasN** [comment]
@anmurali another reminder😁

**Comment by SofoniasN** [comment]
Hey @anmurali it has been fifteen days, since any activity could we please close this one out. Thanks

**Comment by SofoniasN** [comment]
@anmurali offer accepted

**Comment by SofoniasN** [comment]
@anmurali a small bump

**Comment by anmurali** [comment]
Done
