### ISSUE TITLE
Inconsistent #admins font styling when marking unread in notifications and messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21443]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app settings.
2. Go to the workspace section.
3. Create a new workspace.
4. Click the three-dot icon and go to the admin section. Observe that the admin is pinned to the left side.
5. Write a message and mark it as unread in pinned notifications by right-clicking on the notification and clicking on "mark unread". Note that the #admins font style changes to bold. When marked unread again, the font size changes to its original size.
6. Go to admin messages and mark them as unread. Note that the #admins font style changes to bold, which is good. However, when marked unread again, the font size of #admins is not changed to its original size like in pinned notifications. This inconsistency causes confusion for users.
## Expected Result: 
The #admins font style should behave consistently when marking unread in pinned notifications and messages.
## Actual Result: 
The #admins font style changes inconsistently when marking unread in notifications and messages, causing confusion for users.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (3).webm](https://github.com/Expensify/App/assets/43996225/ae62f0d4-41c4-409a-957f-80b2597fda74)

https://github.com/Expensify/App/assets/43996225/23128df6-e445-43e7-aa5d-d418e3b96154

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687000597543669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I agree. I don't think this is a bug either. The two actions being compared are not the same.
