### ISSUE TITLE
[Performance] Guides initially loading the app takes a very long time 

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#21446]
## What performance issue do we need to solve?
When guides (who have many policies/reports) load the app initially it can take a very long time (often 10+ minutes) to load all of their chats.

## What is the impact of this on end-users?
Guides can't get into NewDot to work with their leads / see messages. 

## List any benchmarks that show the severity of the issue
(Not sure how to provide benchmarks, let me know if there is something else I can add in here)

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Not sure, but this has been happening for weeks for guides
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** paige.smith@team.expensify.com
**Notes/Photos/Videos:**
In the example linked above

**Comment by iwiznia** [comment]
Taking this since I am trying to diagnose in slack with the guides

**Comment by iwiznia** [comment]
BTW I think this is fake news.

**Comment by iwiznia** [comment]
ok this is indeed fake news. AFAIK this takes around 20s which is not great but not that bad. The real problem is https://github.com/Expensify/App/issues/21444 so closing this one for now.
