### ISSUE TITLE
[HOLD for payment 2023-12-07] [HOLD for payment 2023-10-13] [HOLD for payment 2023-07-14] Onyx migration for personalDetails changes

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#21454]
Part of "Secure Logins in NewDot" Project
- Main [tracking issue](https://github.com/Expensify/Expensify/issues/280523)
- Re-keying [tracking issue](https://github.com/Expensify/App/issues/19247)

As part of this project, we started sending new data to Onyx that was accountID-based (e.g. personalDetailsList, participantAccountIDs, etc). We did not stop sending the old data, but we will be soon. 

As a cleanup item, we should add an Onyx migration for two reasons: 
1. To remove stale data from clients (e.g. to remove the personalDetails object) 
2. To fix stale local data that will cause the app to break (e.g. old reportActions that don't have participantAccountIDs) 

We should have this ready to go-live after https://github.com/Expensify/Expensify/issues/294647 is done. 

This migration will be handled in stages: 

Before updating the back-end: 
- [x] Migrate reportActions that don't have accountID-based data to include it (without removing email-based data)
    - Note: reportActions are the only pieces of data that can be stale in Onyx and might not be overwritten by the API) (https://github.com/Expensify/App/pull/21509)

Once back-end has been updated to stop sending email-based data:
- [x] Update the reportActions migration to clear out any email-based data https://github.com/Expensify/App/pull/22432
- [x] Update migration to remove email-based data from reports 
    - [x] https://github.com/Expensify/App/pull/22811
    - [x] https://github.com/Expensify/App/pull/28555
    - [x] https://github.com/Expensify/App/pull/31664
- [x] Update migration to remove the old policyMembersList https://github.com/Expensify/App/pull/21694
- [x] Update migration to remove the old personalDetails https://github.com/Expensify/App/pull/21844
- [ ] Update migration not to run when it isn't needed

**Comment by puneetlath** [comment]
This migration will be handled in stages: 

Before updating the back-end: 
- [ ] Migrate reportActions that don't have accountID-based data to include it (without removing email-based data)
    - Note: reportActions are the only pieces of data that can be stale in Onyx and might not be overwritten by the API) 

Once back-end has been updated to stop sending email-based data:
- [ ] Update the reportActions migration to clear out any email-based data
- [ ] Update migration to remove email-based data from reports
- [ ] Update migration to remove the old policyMembersList
- [ ] Update migration to remove the old personalDetails

**Comment by puneetlath** [comment]
@s77rt if you want, you can C+ all of them. There will probably be at least 3 or 4 PRs.

**Comment by s77rt** [comment]
@puneetlath That would be great

**Comment by Beamanator** [comment]
Planning to help with `Update migration to remove email-based data from reports` once we have all of the emails out of reports 👍

**Comment by s77rt** [comment]
Ignore the comment ^ I thought Alex is another person :joy:

**Comment by Beamanator** [comment]
Haha no worries! I don't mind if the other alex makes that PR :D

**Comment by puneetlath** [comment]
@s77rt https://github.com/Expensify/App/pull/22432 is for reportActions. We'll also need to do one for reports.

**Comment by s77rt** [comment]
@puneetlath Sorry my bad then :sweat_smile:. Looking forward for those PRs :rocket:

**Comment by puneetlath** [comment]
All good!

**Comment by s77rt** [comment]
Not overdue. Latest PR is hold on E/E

**Comment by s77rt** [comment]
@puneetlath @Beamanator is E/E#294647 still not resolved?

**Comment by puneetlath** [comment]
Not quite. We realized we had to refactor some stuff in order to stop sending a couple of the fields. Getting close though!

**Comment by s77rt** [comment]
Any update on E/E#294647?

**Comment by Beamanator** [comment]
It's moving forward but the last few steps are pretty tough so it's slow :D

**Comment by puneetlath** [comment]
Almost ready for participants. Just one more change to make.

**Comment by s77rt** [comment]
@puneetlath How is E/E#294647 going?

**Comment by puneetlath** [comment]
We're getting closer, but it's slow going. We can pay you out for the PRs that have been completed so far if you'd like.

**Comment by s77rt** [comment]
@puneetlath I can wait. I hope Melvin can too 😅

**Comment by puneetlath** [comment]
Still not ready for the reports migration. Almost!

**Comment by Beamanator** [comment]
getting close still

**Comment by puneetlath** [comment]
@Beamanator is working on the back-end that should unblock the last couple pieces. Hopefully we're very close to the finish line here 🤞🏾

**Comment by puneetlath** [comment]
Getting closer!

**Comment by puneetlath** [comment]
Next (last?) PR is here: https://github.com/Expensify/App/pull/31664

**Comment by puneetlath** [comment]
I believe we're officially done with this now that the last PR was merged 🎉 

@Beamanator @s77rt do you agree that we're done? Or are we still missing something?

**Comment by Beamanator** [comment]
I thinkkkk yes we can finally close this one out!

**Comment by s77rt** [comment]
> - [ ] Update migration not to run when it isn't needed

What about this one?

**Comment by puneetlath** [comment]
Hmm, I can't remember what I meant by that. Is there a way we can know that the migration doesn't need to run and skip it that y'all can think of?

**Comment by Beamanator** [comment]
haha fair point - i don't think we'd have any way of knowing that it already ran unless we set some kind of NVP, but we'd have to have it run for every device where you had logged in to your account - so I don't think we need to do that now, we may need to if we start running too many migrations that end up taking a long time or something?

**Comment by s77rt** [comment]
Agree ^ I think we are good to close for now

**Comment by s77rt** [comment]
- https://github.com/Expensify/App/pull/21509
- https://github.com/Expensify/App/pull/21694
- https://github.com/Expensify/App/pull/21844
- https://github.com/Expensify/App/pull/22432
- https://github.com/Expensify/App/pull/28555
- https://github.com/Expensify/App/pull/31664
- https://github.com/Expensify/App/pull/22811 <-- This does not count since it's a dupe / closed

I found 6 PRs. All are pretty minimal, it should be $250 each. Total: $1500

**Comment by puneetlath** [comment]
Ok that sounds good. Thank you for being so honest and straightforward. Offer here: https://www.upwork.com/nx/wm/offer/27918877

**Comment by s77rt** [comment]
Accepted! Thanks!
