### ISSUE TITLE
Misleading text in assignee's report in LHN after creating a task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account with tasks enabled (tasks are currently in beta, so this'll probably be in DEV).
2. You'll need to have started 2 chats/reports, so create them if need be.
3. Open report A and click on the '+' sign in the composer.
4. Choose 'Assign task' and fill out the title and, optionally, the description.
5. Click on 'Assignee' and then select the user in report B.
6. Click on the green button at the bottom that says 'Confirm task'.
7. Observe the text in the LHN for report B.
## Expected Result: 

The text says, "You assigned a task: [task name here]" or its equivalent since I'm the one assigning the other person the task.
## Actual Result: 
The text says, "Assigned a task to you: [task name here]".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e3e47194-cdfc-4c04-bf03-fb98237d4ca1

https://github.com/Expensify/App/assets/43996225/caeeb406-4f5e-4a12-ba5d-129b6dbd92bd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1687089663535439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Works as expected right now
