### ISSUE TITLE
Didnt receive magic code is clickable and code is sent when the button is clicked while sign-in is loading with a correct magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to expensify staging login
2. Enter an email account
3. Wait for the resend countdown to finish and enter the magic code sent to the email address
4. Immediately after signin button starts loading click on "Didnt receive code" and notice how a new count down is started and another magic code is sent but user is logged in and can now access his account.

## Expected Result:
Once the signin button starts loading user should not be able to click on "didnt receive magic code"

## Actual Result:
User is able to click on didnt receive magic code and a new countdown starts with a new magic code being sent to user despite user logging in

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32.1

**Reproducible in staging?:** yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/01abeb1c-ba1d-4b04-a63f-ad8e124f1a11

https://github.com/Expensify/App/assets/93399543/facd4cdb-8124-4ce8-a39a-92cac3e90431

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687545498379289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@kbecciv The OP steps didn't match the title of the issue, I think you copy/pasted the wrong ones, so I've updated them with what's in the linked Slack thread.  

As for the expected results here, I'm wondering if we need to do anything at all. We typically use the "disabled" state (i.e reduced opacity to 50%) as an offline pattern. Conflating it with when the sign-in is loading in this instance might not be the best thing. 

If you do for some bizarre reason enter a magic code > click sign-in > and then quickly manage to click "Didn't receive a magic code?" to request a magic code again while the sign-in is loading, nothing bad happens as far as I can tell. You sign-in, and you receive another magic code email? 🤷 I'm inclined to leave this as is. 

CC: @shawnborton @JmillsExpensify

**Comment by trjExpensify** [comment]
All good! @shawnborton @JmillsExpensify you good if I close this?

**Comment by shawnborton** [comment]
Works for me!

**Comment by trjExpensify** [comment]
Perf.
