### ISSUE TITLE
An account is mentioned in a new thread but neither see that thread report in LHN nor receive reply notification

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with two accounts on two devices (Account A, Account B)
2. Create a group chat including A and B
3. A mentions B in the group chat
4. A clicks Reply in thread that message
5. Verify that B does not see the Thread report in LHN
6. In that thread report, A replies with any message
7. Verify that B does not receive any reply notification

## Expected Result:
 B sees the new thread report in LHN and receives reply notification

## Actual Result:
 B cannot see the new thread report in LHN and receive any reply notification

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.28-5

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 12-06-2023 12_02_15.webm](https://github.com/Expensify/App/assets/93399543/6574d1fa-6d40-42ed-a3d9-7b821197ce2b)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tienifr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686902707060729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a8b9cd683e7bdd1</li>
        <li>Upwork Job ID: 1672363879867797504</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
@narefyev91 Removing your assignment as this requires a backend fix. 🙏🏼
