### ISSUE TITLE
[HOLD for payment 2023-08-21] [$2000] Hitting enter key on keyboard does not select a pronoun

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND on android
2. Go to settings > Profile > Pronouns
3. Search a pronoun
4. Hit on Enter / tick mark key on keyboard
5. Observe the behavior
6. Open mWeb and do step 2 - 5
## Expected Result: 
The behavior on both mWeb and Android should be the same.
## Actual Result: 
On android hitting the enter key does nothing other than closing the keyboard, but on mWeb hitting the enter key on keyboard selects the searched pronoun
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/be329bdd-0653-4cf6-86cb-586847224fd0

https://github.com/Expensify/App/assets/43996225/c47feb0d-e8d7-4fbd-acce-3098c33dbeaf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687109264930579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01763c040cae5d6f20</li>
        <li>Upwork Job ID: 1673255740814970880</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the "Submit" button is pressed, 

### What is the root cause of that problem?

While we subscribe to "Enter" key presses via `KeyboardShortcut.subscribe`, this doesn't seem to work on Android Native.

### What changes do you think we should make in order to solve the problem?

We should extract the relevant logic and call it...
- From the callback passed to `KeyboardShortcut.subscribe`
- From the `onSubmitEditing` passed to `TextEdit`

Extracted logic:
```js
    selectFocusedOption() {
        const focusedOption = this.state.allOptions[this.state.focusedIndex];
        if (!focusedOption || !this.props.isFocused) {
            return;
        }
        if (this.props.canSelectMultipleOptions) {
            this.selectRow(focusedOption);
        } else if (!this.state.shouldDisableRowSelection) {
            this.setState({shouldDisableRowSelection: true});
            let result = this.selectRow(focusedOption);
            if (!(result instanceof Promise)) {
                result = Promise.resolve();
            }
            setTimeout(() => result.finally(() => this.setState({shouldDisableRowSelection: false})), 500);
        }
    }
``` 

Call from the `KeyboardShortcut.subscribe` callback:

```js
this.unsubscribeEnter = KeyboardShortcut.subscribe(
    enterConfig.shortcutKey,
    () => {
        this.selectFocusedOption();
    },
    enterConfig.descriptionKey,
    enterConfig.modifiers,
    true,
    () => !this.state.allOptions[this.state.focusedIndex],
);
```

Call from the `onSubmitEditing` callback:

```js
onSubmitEditing={()=> {
    this.selectFocusedOption();
}}
```

**Comment by conorpendergrast** [comment]
We see the same behaviour in selecting timezone and currency (during a money request and split) too, by the way! 



| Timezone  | Request - Currency | Split - Currency |
| ------------- | ------------- | ------------- |
| ![image](https://github.com/Expensify/App/assets/5802477/0d40b6aa-935c-4c04-9cd8-2194649f7a95)  | ![image](https://github.com/Expensify/App/assets/5802477/ff51c4f8-54b3-40fb-810c-954e9a441961)  | ![image](https://github.com/Expensify/App/assets/5802477/91d832a9-1258-4d96-b5aa-996046ef92d8) |

**Comment by cubuspl42** [comment]
> > While we subscribe to "Enter" key presses via KeyboardShortcut.subscribe, this doesn't work on Native
> 
> @cubuspl42 We have keyboard shortcuts on native btw. At least for a hardware keyboard. Could you please confirm if we can support this in KeyboardShortcut library itself?

I've just tested it on iOS with (emulated) hardware keyboard attached. It appears that (on `main`) if you press Enter _twice_, the option row **is** selected. The first press unfocuses the text input (and can be handled in `onSubmitEditing`) and the second press can be handled via `KeyboardShortcut` / `react-native-key-command`. If you asked me, it makes sense.

I'd assume it's similar on Android.

I think there's no reason to fight this (and it might be impossible). From my perspective, `onSubmitEditing` is a clear way to get notified about the "Submit" / "Enter" press on Native.

**Comment by conorpendergrast** [comment]
@rushatgabhane Thoughts? Should we get more confident on Android first before confirming the solution?

**Comment by conorpendergrast** [comment]
@rushatgabhane Bump on my question, please!

**Comment by conorpendergrast** [comment]
Bumped [via Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1688730239929349)

**Comment by cubuspl42** [comment]
@rushatgabhane I would guess that `KeyboardShortcut` and `react-native-key-command` are doing their best. I'm not surprised that there are some subtle platform-specific behavioral differences between Web and Native platforms.

On the Web, there's no established concept of "submitting" a text input, while on native iOS and Android, there seems to be one. On the other hand, using a hardware keyboard with mobile devices is extremely rare, so whatever results show up with testing this setup should be taken with a grain of salt.

Summing up, I stand with my perspective that it's not surprising that a native text input "steals" the keyboard, and its submit button press is announced via `onSubmitEditing`. I think that my proposed solution is acceptably clean, possibly as clean as possible (which is always difficult to prove, though).

Please note that I refactor the shared logic, this is not some dirty copy-and-paste.

https://github.com/Expensify/App/blob/d8a32e7172775675b59da029a45aa1eb4ae4f4d2/src/components/OptionsSelector/BaseOptionsSelector.js#L158-L173

**Comment by cubuspl42** [comment]
> > a native text input "steals" the keyboard, and its submit button press is announced via onSubmitEditing
> 
> @cubuspl42 could you please help usd understand why and how this is happening? I don't think we understand the root cause.

The entry point of our keypress handling on iOS is:

https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/ios/NewExpensify/AppDelegate.mm#L98-L100

The entry point of our keypress handling on Android is:

https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/android/app/src/main/java/com/expensify/chat/MainActivity.java#L66-L78

The [entry point for our keypress handling on the Web](https://github.com/Expensify/react-native-key-command/blob/5b093ed48c9bb90f047c7a3f1267e384298c1018/src/KeyCommand/index.js#L199-L200) is:

```js
if (typeof window !== 'undefined') {
    document.removeEventListener('keydown', onKeyDown, {capture: true});
    document.addEventListener('keydown', onKeyDown, {capture: true});
}
```

These entry points have their platform-specific behavior.

In particular, on iOS and Android they are not fired when a respective native text input is focused. On the Web, `document`'s  `keydown` **does** fire even when there's a focused text input element.

This doesn't look like something we control. There doesn't seem to be any simple way of adjusting this behavior on iOS and Android.

**Comment by ShogunFire** [comment]
Hello, maybe I am wrong but could we not use this https://github.com/Expensify/App/blob/main/src/libs/KeyboardShortcut/isEnterWhileComposition.js ?

**Comment by conorpendergrast** [comment]
Looks like discussions on this are ongoing

**Comment by cubuspl42** [comment]
> @cubuspl42 what do you suggest then? I think using `onSubmitEditing` would be a hack

I'm not suggesting anything beyond my original proposal. I can't see other clean and viable solutions here. My explanation was a response to your request to explain the root cause in more depth.

I don't share the perspective that the proposed solution is a hack, so it's difficult for me to take a stand here. I see it as a reasonable compromise in the context of different input models across platforms.

**Comment by rushatgabhane** [comment]
thank you for explaining @cubuspl42 

let's wait for more proposals

**Comment by conorpendergrast** [comment]
Bumping this up to $2000 as we're waiting for more proposals!

**Comment by conorpendergrast** [comment]
I'll move to expert vendor soon, if we still don't have proposals we want to go with

**Comment by cubuspl42** [comment]
@conorpendergrast Actually I felt like like my proposal wasn't labeled as unacceptable, but more like @rushatgabhane wanted to get more eyes on this issue to seek alternative solutions if they exist, but please correct me if I'm wrong.

**Comment by pasyukevich** [comment]
Hi,
I am from Callstack - an expert contributor group
I start to investigate this issue

**Comment by conorpendergrast** [comment]
@pasyukevich Hey! I'm assigning you as the expert contributor group. How has your investigation gone, and what is the ETA on a proposal? Thanks!

**Comment by pasyukevich** [comment]
I continue to work on this issue and am currently checking the native update option as a potential fix. 

After this, I plan to post the proposal.

**Comment by conorpendergrast** [comment]
Thanks for the update!

**Comment by rushatgabhane** [comment]
I agree with the root cause explained by @pasyukevich in their [proposal here](https://github.com/Expensify/App/issues/21472#issuecomment-1660590879).
C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
Looks like we have a new face. Hi @Li357, nice to meet ya!

**Comment by cubuspl42** [comment]
@rushatgabhane 
Well, I agree with that RCA too, but this is basically the same root cause analysis and basically the same solution as I proposed, which you considered a hack. So am I missing something, or is it not possible per the process to select a previous proposal after a proposal from an expert agency?

**Comment by Li357** [comment]
The RCAs do seem similar, @rushatgabhane can you speak on what the differences are?

**Comment by rushatgabhane** [comment]
The RCA is similar but it wasn't clearly explained. I don't know what else to say 😅

**Comment by cubuspl42** [comment]
I expanded the root cause analysis per the request:

- [Explanation part 1](https://github.com/Expensify/App/issues/21472#issuecomment-1608107925)
- [Explanation part 2](https://github.com/Expensify/App/issues/21472#issuecomment-1625449527)

I think that maybe my mistake was that I didn't expand the text of the original proposal; it was possible to miss the extra explanation added afterward at the final review stage. Still, I believe that this still counts as part of the root cause analysis.

I analyzed the behavior on all supported platforms and drew a clear conclusion explaining the difference in the behavior:

> In particular, on iOS and Android they are not fired when a respective native text input is focused. On the Web, document's keydown does fire even when there's a focused text input element.

The other proposal repeats this conclusion focusing only on Android, as if this wasn't affecting iOS.

The decision is up to you guys, I also don't know what else to say.

**Comment by rushatgabhane** [comment]
@cubuspl42 yeah you're right. I'm sorry about this one!

@Li357 i think we should assign @cubuspl42 to this issue

**Comment by cubuspl42** [comment]
> @cubuspl42 yeah you're right. I'm sorry about this one!
> 
> @Li357 i think we should assign @cubuspl42 to this issue

No problem, I should've stuck to the process and done proper proposal updates. Thanks for seeing my perspective, I really appreciate it 😊

**Comment by Li357** [comment]
All yours @cubuspl42!

**Comment by conorpendergrast** [comment]
Contracts sent to @cubuspl42 and @Nathan-Mulugeta in Upwork. @rushatgabhane will be via manual request in ND

**Comment by Nathan-Mulugeta** [comment]
Offer accepted

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
created a manual request incl bonus ($3k) https://staging.new.expensify.com/r/5354089055656094

**Comment by conorpendergrast** [comment]
Payouts due:

- [ ] Issue Reporter: $250 @Nathan-Mulugeta 
- [ ] Contributor: $2000 + 50% urgency bonus = $3000 @cubuspl42 
Contributor+: $2000 + 50% urgency bonus = $3000 @rushatgabhane via [manual request](https://staging.new.expensify.com/r/5354089055656094)

Eligible for 50% #urgency bonus? Yes

Upwork job is [here](https://www.upwork.com/ab/applicants/1673255740814970880/job-details).

**Comment by conorpendergrast** [comment]
All done now, thanks everyone!

**Comment by JmillsExpensify** [comment]
Reviewed the details for @rushatgabhane. $3,000 payment approved via NewDot based on the BZ summary above.
