### ISSUE TITLE
Details - Incorrect amount of members displayed for public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with own account (used [daniel@expensify.com](mailto:daniel@expensify.com))
3. Open a public room https://staging.new.expensify.com/r/5593084223054221
4. Go to Setting - Details

## Expected Result:
Correct amount of members displayed for public room

## Actual Result:
Incorrect amount of members displayed for public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (81)](https://github.com/Expensify/App/assets/93399543/aee4b365-19e3-45f6-829d-f1216921370c)

![image (80)](https://github.com/Expensify/App/assets/93399543/ab98ab8a-2433-4379-9e6d-9c54c5399d98)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Daniel Vidal

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686957228174989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Confirming whether Daniel can still reproduce this on his end after the weekend.

**Comment by joekaufmanexpensify** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1687899022493869?thread_ts=1686957228.174989&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment]
Confirmed in the above thread that this is no longer reproducible for Daniel. Closing as this seems to have self-resolved!
