### ISSUE TITLE
Profile - 404 error displayed when open a user profile on public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Incognito window
2. Open a public room https://staging.new.expensify.com/r/5593084223054221
3. Click on user profile

## Expected Result:
User profile should be displayed 

## Actual Result:
404 error displayed when open a user profile on public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (79)](https://github.com/Expensify/App/assets/93399543/47136c83-f4ff-4c84-85f1-6891c5a5c6e6)

![image (78)](https://github.com/Expensify/App/assets/93399543/a1e4043f-06f5-462d-b6db-ffabee5b711f)

**Expensify/Expensify Issue URL:**

**Issue reported by:** David Barrett

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686956039971669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
I note that the user profile that was clicked was related to:
```
Current User : danrvidal+snhtest6@gmail.com
Account ID : 14886139
```

I just clicked through the users in the chat again and wasn’t able to find which one of Dan’s comments came from that user.
I’m not really sure what to make of that but wanted to call it out.

**Comment by johncschuster** [comment]
Coming from Slack, it sounds like this issue has been resolved. Closing!
