### ISSUE TITLE
Contact/Phone numbers ( NOT emails ) are flagged as violation while mentioning in public rooms

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to '+" -> new room
2. Type in room name -> add workspace
3.  (IMPORTANT STEP) make room as public
4. Now on room page, on room chat, type '@' and mention some contact number ( WORKS WELL WITH EMAILS)
for eg . i did mentioned @+9779866****** phone number
5. Notice that it is flagged automatically

## Expected Result:
Contact numbers should not be flagged as a violation of rule, as in real we might need to mention some user ( which has signed up using phone number)

## Actual Result:
Contact numbers are flagged as violation while mentioning in public rooms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/85a1604d-3df3-4293-a9f4-056bdf3751bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687619050679359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108e1fd1f5b114d4b</li>
        <li>Upwork Job ID: 1673384510798495744</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by ashimsharma10** [comment]
@stitesExpensify

**Comment by thienlnam** [comment]
Stites is OOO, will take this up

**Comment by thienlnam** [comment]
Ah, this would be related to the spam prompt and should be happening on staging and production. Going to remove the blocker and add as an example to https://github.com/Expensify/Expensify/issues/292287

**Comment by thienlnam** [comment]
Haven't updated this yet - planning with rest of AgentZero updates

**Comment by thienlnam** [comment]
Same as above

**Comment by thienlnam** [comment]
Haven't gotten around to this

**Comment by thienlnam** [comment]
Same - hoping to this week

**Comment by thienlnam** [comment]
Have an internal PR up

**Comment by thienlnam** [comment]
This should be live now - checking if this is resolved

**Comment by thienlnam** [comment]
<img width="494" alt="Screenshot 2023-08-01 at 11 49 19 AM" src="https://github.com/Expensify/App/assets/30609178/b4573562-6447-4da4-8aff-e2de0fc80372">

Looks like this is resolved now - just to pay out bug reporter

**Comment by thienlnam** [comment]
cc @tjferriss 

I resolved this bug internally, could we get a payout for the bug reporter?
Issue reported by: @ashimsharma10

**Comment by tjferriss** [comment]
@ashimsharma10 I just sent you an offer via Upworks https://www.upwork.com/jobs/~0158147e2a0ebeea58

**Comment by ashimsharma10** [comment]
@tjferriss Have accepted.

**Comment by tjferriss** [comment]
The payment has been made.
