### ISSUE TITLE
 Payments - User get error message about non-USD currency when clicking Pay with Expensify

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Account A:
1. Login to staging.new.expensify.com with expensifail account as user A
2. Go to Payments and connect bank account
3. Create workspace and select USD as default currency in General settings

Account B:
4. Login to staging.new.expensify.com with expensifail account as user B
5. User B has connected Bank account in Payments
6. Send request money to the user A

Account A:
7. Go to the money request
8. Tap to button 'Pay with Expensify'

## Expected Result:
User able to proceed with payment as bank account already added

## Actual Result:
User A goes to the page 'Connect bank account' with message 'Oops! It appears that your workspace currency is set to a different currency that USD. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/53b00d94-0dfd-4ad0-a365-b95c4e6f24a9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Agreed, closing in favor of https://github.com/Expensify/App/issues/21461.
