### ISSUE TITLE
App crashes when opening a share code link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Open that tab where account B is signed in
3. Flag the message as Harassment
4. Open the tab where account A is signed in
5. Click on 'Reply in thread' icon of the flagged message
6. Click on chat header
7. Click on share code button
8. Click on 'Copy URL to clipboard button
9. Switch to the window where account B is signed in
10. Open new tab > paste the URL to the new tab > press enter

## Expected Result:
App shouldn't crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d6fb9fe-b3ae-459d-b0c1-51aea1aa8530

https://github.com/Expensify/App/assets/93399543/2039fb23-f6ac-4db1-bde4-4f3c66e93a0c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686946104161069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
I cannot reproduce. When I paste the copied URL to a new tab in the same window where user B is signed into, I get asked to sign in and when I do - it opens the correct chat window for me

**Comment by anmurali** [comment]
Uploading Screen Recording 2023-07-03 at 2.18.53 PM.mov…

**Comment by Natnael-Guchima** [comment]
@anmurali your video doesn't seem to finish uploading.
