### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000]  Login page scroll to top on change language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. logout if you already logged in
2. scroll to bottom
3. change language
## Expected Result: 
page position should not be changed
## Actual Result: 
login page scroll to top

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7d04c9c2-a1dc-484f-97bd-d4178bb86d63

Uploading Screen_Recording_20230620_155826_New Expensify.mp4…

https://github.com/Expensify/App/assets/43996225/5f753429-39e6-454f-bfa5-6bf0687e595d

https://github.com/Expensify/App/assets/43996225/1273377d-9cab-413b-9ee2-04b233a83cda

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687257287784129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147a98e8a53297eeb</li>
        <li>Upwork Job ID: 1673447313089499136</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
I agree. Let's test with the steps from [this PR](https://github.com/Expensify/App/pull/17445) where the scrolling code was added to make sure it still works. I think it will because the proposal works well with the existing behavior, but just to be safe.

**Comment by kevinksullivan** [comment]
Hi @parasharrajat please complete the steps above ahead of July 10 so we can pay out on time. Thanks!

**Comment by neil-marcellini** [comment]
Not overdue, waiting for payment to complete.

**Comment by kevinksullivan** [comment]
Offers sent to @mananjadhav @parasharrajat @hoangzinh . Let me know when you accept!

**Comment by gadhiyamanan** [comment]
@kevinksullivan issue is reported by me not @mananjadhav

**Comment by kevinksullivan** [comment]
Sorry @gadhiyamanan , I know that is not my first time making that mistake 🤦 . Sent you an offer, and sent one for @parasharrajat as well.

**Comment by kevinksullivan** [comment]
Paid @hoangzinh + merge bonus

**Comment by kevinksullivan** [comment]
@gadhiyamanan @parasharrajat let me know when you've accepted

**Comment by kevinksullivan** [comment]
This is weird... It seems I had to create a new job to hire you @gadhiyamanan but I don't see it in upwork right now. Do you by chance have a link to the job so I can pay it out?

**Comment by kevinksullivan** [comment]
New job created and offers sent to @gadhiyamanan and @parasharrajat 

https://www.upwork.com/jobs/~0159f24e8eadb04fc9

**Comment by gadhiyamanan** [comment]
@kevinksullivan accepted,thanks!

**Comment by kevinksullivan** [comment]
Paid @gadhiyamanan

**Comment by neil-marcellini** [comment]
Not overdue. Can we close this out?

**Comment by neil-marcellini** [comment]
Same same

**Comment by kevinksullivan** [comment]
@parasharrajat are you getting paid in newdot? Can I close this out?

**Comment by kevinksullivan** [comment]
Ok cool. I will close just to save my overdues here, but let me know how I can help when the time comes @parasharrajat

**Comment by kevinksullivan** [comment]
Payment summary
- Reporter: @gadhiyamanan $250
- Contributor: @hoangzinh $1,500
- C+: @parasharrajat $1,500

**Comment by kevinksullivan** [comment]
@parasharrajat you linked to my previous comment. Are you being paid in upwork or NewDot?

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
