### ISSUE TITLE
[$1000] Pressing the Esc key after opening the context menu over a link creates a blue box around it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigatedto the chat
2. Send a message with a link
3. Open the context menu 
4. Press the Esc key

## Expected Result:

Pressing the Esc key should not create a blue box around the link.

## Actual Result:
Pressing the Esc key after opening the context menu over a link creates a blue box around it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b9d5ee77-f1ba-4f22-9a22-64b25e6d5fc4

https://github.com/Expensify/App/assets/43996225/4faec980-8626-4cc2-822f-c480e8630b31

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687028085933669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154b2e27611249039</li>
        <li>Upwork Job ID: 1673609533740761088</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@Tushu17 can you send over a screenshot of the blue box. I've watched the video a few times and I'm not sure I follow. Thanks!

**Comment by laurenreidexpensify** [comment]
ah I see it now! Okay thanks

**Comment by s77rt** [comment]
@laurenreidexpensify I don't think this is a valid bug. The blue outline is there for accessibility reasons. We closed similar issues https://github.com/Expensify/App/issues/19144 and https://github.com/Expensify/App/issues/17419. I think we can close this one as well.

**Comment by s77rt** [comment]
@Nodebrute I think same above note applies for this case too.

**Comment by laurenreidexpensify** [comment]
Thanks @s77rt
