### ISSUE TITLE
Inconsistent cursor color between android and mWeb

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open ND android
2. Click on FAB > send money
3. Observe the cursor in the amount inout field
4. Open ND on mWeb
5. Do step 2 and 3

## Expected Result:

cursor color should match
## Actual Result:
cursor color is green on android but it is white on mWeb

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/049e0e5e-af37-49ec-9442-be63333b89a4" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/26bfc29e-d782-4a37-9355-30000a10ca28" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/e39bd0ff-726a-4341-b5f5-961d88144eb7" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/9e2c85d0-b15d-4fac-b300-cd2313497784" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687014757186509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Huh, and it's blue on iOS: 

<img src="https://github.com/Expensify/App/assets/5802477/c0bc50a9-fe19-4f8f-aa61-e58003615800" width="300">

**Comment by conorpendergrast** [comment]
Found reference to an earlier conversation on this [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1666374993924389?thread_ts=1663248561.928939&cid=C01GTK53T8Q) (#expensify-open-source channel), and this is not considered a bug. Thanks!
