### ISSUE TITLE
Web -  While the main thread is loading, the LHN displays wrong name of the people who sent the latest message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. User A and B are in the SAME group, B sent the LAST message
2. Login as user A
3. Check the latest message on LHN

## Expected Result:
Name of B should be displayed in LHN instead of A

## Actual Result:
 Name of A is displayed

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.29-2

**Reproducible in staging?:**y

**Reproducible in production?:**y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image (94)](https://github.com/Expensify/App/assets/93399543/9098567a-46f2-4532-be79-48ebe5c560f4)

![image (93)](https://github.com/Expensify/App/assets/93399543/89abb384-377f-40c8-9601-1f9f2fd0b801)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687191384893579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01761e2ab9ad3cb69f</li>
        <li>Upwork Job ID: 1676734116333826048</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment]
Please check this video for more details (I use **Chrome Developer** tool and set **network throttling** to **Fast 3G** for easier reproduction (though it happened quite often for me.
- At '01:10` you can see that the last message is **Dena Martin: And so it begins...** - which is wrong (_the main content seems finished loading too_)
- But when scroll the main content, it shows the last message is **Ernest Cook: And so it begins...** - which is now correct 
- 
https://github.com/Expensify/App/assets/10254571/461c9762-6fae-4265-bc24-a426363e79a8

**Comment by mallenexpensify** [comment]
@tranvantoan-qn , I'm a bit confused here.  Are you saying that, while the content is loading, the LHN should be updated before the main chat so that it never shows an old chat?

**Comment by mallenexpensify** [comment]
@tranvantoan-qn , when you get a moment can you reply to the above, thx

**Comment by mallenexpensify** [comment]
Unable to reproduce in Chrome, web.   Was going to try to test in iOS but my app isn't loading now :/ 
<img width="1570" alt="image" src="https://github.com/Expensify/App/assets/22508304/4356b632-2d97-4591-968a-e88789716595">


@fedirjh can you see if you can reproduce please?

**Comment by tranvantoan-qn** [comment]
Your chat seems doesn't too long so It will be loaded very quickly - I think :smile
Let's try the SNH room for example >> open it  >> then logout >>  re-login (so the it will be opened by default after login) >> and check the **LHN** with main chat content (on the right)

**Comment by mallenexpensify** [comment]
Gonna close since we can't reliably reproduce
