### ISSUE TITLE
[$1000] Mweb - Selected language gets highlighted if pressed for a bit longer than normal.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open “Settings”
2.Open “Preferences”
3.Open “Language”.
4.Select any language and press it for a bit longer so that it highlights
## Expected Result:
On pressing for long the language shouldn’t get highlighted.
## Actual Result:
On pressing for long the language gets highlighted.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0a5ba8cb-e5d8-40aa-bd88-d150d8911365

https://github.com/Expensify/App/assets/43996225/3e3f802e-77f2-49ff-aab4-e57318ec55d2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687255009876259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7d25e72f2cda65c</li>
        <li>Upwork Job ID: 1673806908231282688</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I'm not able to reproduce this issue using BrowserStack. @narefyev91 are you able to reproduce?

**Comment by narefyev91** [comment]
@tjferriss was not able to reproduce on latest main

https://github.com/Expensify/App/assets/28352309/f72fe26f-4fda-46e8-9046-0037af24a23e

**Comment by usmantariq96** [comment]
@tjferriss the same subject issue which was closed, started happening again on Mweb as well as on Windows (Chrome). 
Please find attached latest video for your reference.


https://github.com/Expensify/App/assets/127622389/d3c81c8a-0243-49b4-91a3-bd40b2e6e7ee

**Comment by usmantariq96** [comment]
@tjferriss @narefyev91 any update here please ?

**Comment by narefyev91** [comment]
@usmantariq96 Yes i can reproduce it now

https://github.com/Expensify/App/assets/28352309/f4d24b06-7102-41c1-b330-cd6aa8bfe210

**Comment by tjferriss** [comment]
I'm still now able to reproduce this one on either Chrome or mobile.

https://github.com/Expensify/App/assets/8292562/5fae9e22-2335-42f9-b125-1aeddd2a5428

**Comment by narefyev91** [comment]
> I'm still not able to reproduce this one on either Chrome or mobile.
> 
>  Screen.Recording.2023-07-14.at.13.53.57.mov

Hey - to repro - you need - to long click on item and move cursor down during clicking

**Comment by tjferriss** [comment]
As discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689781474377469?thread_ts=1687255009.876259&cid=C049HHMV9SM), @thiagobrez is going to consolidate this update into the refactor they are working on https://github.com/Expensify/App/issues/20354

@usmantariq96 will still be paid out for reporting the issue. The offer has been sent. Can you respond here once it's been accepted?

**Comment by usmantariq96** [comment]
@tjferriss offer accepted with thanks.
