### ISSUE TITLE
Web -  Tooltip max lines is not enforced in LHN avatar tooltips

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. 2. Log in with account
3. Hover over profiles with long emails in LHN

## Expected Result:
Tooltip content should be restricted up to 3 lines like we have done in other tooltips

## Actual Result:
Tooltip content has no limit for LHN tooltips

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/563df817-a8ba-43e4-b7cc-2646b8ff153e

https://github.com/Expensify/App/assets/93399543/f486e62e-3d73-49f6-b519-52e80da8e66b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687183748825679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
tooltip max lines is not enforced in newly added user-details tooltip.
### What is the root cause of that problem?
Root cause is that in `UserDetailsTooltip` component we have not restricted the text nodes content and we allow all length of data to be rendered. We have a key `TOOLTIP_MAX_LINES` set to 3 defined in our `CONST.js` file which we have used in other tooltips of our app. The newly introduced `UserDetailsTooltip` does not use that.
https://github.com/Expensify/App/blob/599f05a801829c4cf9a57bd307acd125195d9437/src/components/UserDetailsTooltip/index.js#L18-L33
### What changes do you think we should make in order to solve the problem?
Inside `UserDetailsTooltip` component, we should add the `TOOLTIP_MAX_LINES` key to elipsisize the text in the tooltip.
We can do so by first importing the key from `CONST.js` and then sending it as a prop-value to the to `numberOfLines` prop in `<Text/>`.
We shall do this for both the `<Text/>` components for display name and login respectively.
```js
<View style={[styles.alignItemsCenter, styles.ph2, styles.pv2]}>
                <View style={styles.emptyAvatar}>
                    <Avatar
                        containerStyles={[styles.actionAvatar]}
                        source={UserUtils.getAvatar(userDetails.avatar, userDetails.accountID)}
                    />
                </View>
                <Text style={[styles.mt2, styles.textMicroBold, styles.textReactionSenders, styles.textAlignCenter]} numberOfLines={CONST.TOOLTIP_MAX_LINES}>
                    {String(userDetails.displayName).trim() ? userDetails.displayName : ''}
                </Text>
                <Text style={[styles.textMicro, styles.fontColorReactionLabel]} numberOfLines={CONST.TOOLTIP_MAX_LINES}>
                    {String(userDetails.login || '').trim() && !_.isEqual(userDetails.login, userDetails.displayName) ? Str.removeSMSDomain(userDetails.login) : ''}
                </Text>
            </View>
```
<details>
  <summary>Results</summary>
</details>
### What alternative solutions did you explore? (Optional)
None

**Comment by kevinksullivan** [comment]
taking to slack

https://expensify.slack.com/archives/C049HHMV9SM/p1687816422791339?thread_ts=1687183748.825679&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
Deemed feature request and not a bug.
