### ISSUE TITLE
Setting - Help - Unnecessary Active Button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21534]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Setting> Help
2. Click on one of the Options below (e.g. send money).
3. Click on "Expensify help" at the top corner.
4. Returns Back to welcome to Expensify help home page.
5. Observe the  "Expensify help" at the top corner.

## Expected Result:
 It should be Deactivated like "Home" option button at welcome to Expensify help home page.

## Actual Result:
 It is Active and refresh the Help home page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/84896a06-90c7-4d73-9197-4c13ffd59315

https://github.com/Expensify/App/assets/93399543/4dbbcc4a-e9d0-42a8-8b32-0a04931ca9dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** Amanuel Mulugeta Arega
Data Analyst and QA S@Amnex-08
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687182997820449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
I don't think this is a bug since most sites behave the same. But if we have too

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Setting - Help - Unnecessary Active Button
### What is the root cause of that problem?
It is not a bug but a feature request
### What changes do you think we should make in order to solve the problem?
We can conditionally render `a` tag or `span` based on route to make it disabled, like this:
```
{% if page.url == "/" %}
            <span >
    <img src="/assets/images/expensify-help.svg" class="logo" />
  </span>
            {% else %}
            <a href="/">
                <img src="/assets/images/expensify-help.svg" class="logo" />
            </a>
            {% endif %}
``` 

### What alternative solutions did you explore? (Optional)
We can also prevent click events by applying this js code:
```javascript
if (window.location.pathname === '/') {
    // Disable the anchor tag by preventing its default behavior and removing the href attribute
    document.querySelector('a[href="/"]').addEventListener('click', (event) => {
        event.preventDefault();
    });
}
```

**Comment by sonialiap** [comment]
As per the slack discussion, not a bug
