### ISSUE TITLE
[$1000] Web - Avatar displayed when creating a task on a thread without selecting an assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the chat
2. Send a message
3. Click on "Reply in thread"
4. Go to the "Assign task" section within the thread
5. Enter a title for the task and click on the "Next" button
6. Click on the "Confirm task" button.

## Expected Result:
The avatar should not be displayed since no assignee has been selected for the task

## Actual Result:
When creating a task on a thread without selecting an assignee, a different avatar is being displayed instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/169a0b1d-a406-459b-8c0c-48efff491eda

![Screenshot 2023-06-19 at 4 08 05 PM](https://github.com/Expensify/App/assets/93399543/9c00dbcc-d6b2-4d24-ad39-99768450a3b3)

https://github.com/Expensify/App/assets/93399543/ec723dbb-7015-4870-9336-1e4761586cd2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687162712035319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3a2b73ab04acc58</li>
        <li>Upwork Job ID: 1673346550931828736</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by s77rt** [comment]
Hmm, I don't know what should be the expected behaviour here. Is it an empty view?

![Screenshot from 2023-06-26 20-03-15](https://github.com/Expensify/App/assets/16493223/15b21782-3eb7-470d-b251-d5e605bd20e3)

cc @anmurali and @shawnborton
