### ISSUE TITLE
Workspace - Avatar keeps changing for a phone number result when trying to invite a member to a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Create a Workspace or go to an existing Workspace
3. Select the Workspace on the Settings > Workspaces screen
4. Click or tap Members
5. Click on Invite
6. Search for a member by phone number
7. Repeatedly modify the phone number such that it still matches the result, for example, delete and type the leading "0" digit.
8. Observe the avatar for the matching result.

## Expected Result:
The avatar should remain the same for the matching result.

## Actual Result:
The avatar keeps changing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/81347c23-d59c-4300-b6c9-6f8e90081993

https://github.com/Expensify/App/assets/93399543/2a916436-2c90-4c98-aae6-b866cd5e9668

**Expensify/Expensify Issue URL:**
**Issue reported by:** @akinwale
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687232701363919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatar keeps changing for a matching search result when trying to invite a new member to a workspace.

### What is the root cause of that problem?
The `optimisticAccountID` is being used to generate the user icon / avatar. Since this is being randomly generated every time the results change for users not yet in Onyx, a new avatar will always be generated as a result.

https://github.com/Expensify/App/blob/f0c663126a625d7964e724a171ed3854ed84b519/src/libs/OptionsListUtils.js#L783

### What changes do you think we should make in order to solve the problem?
Instead of the `optimisticAccountID`, we can make use of one of `userToInvite.login`, `userToInvite.text` or `userToInvite.alternateText` to generate the avatar. These values tend to be unique enough to be used as a seed for avatar generation.

### What alternative solutions did you explore? (Optional)
None.

**Comment by flaviadefaria** [comment]
I just found out that this is the expected behavior. Every time a valid phone/email is entered, it assigns a random default avatar. It doesn’t remember we showed the green one if you clear some of the input and enter the same valid email/phone again. So closing it.
