### ISSUE TITLE
[$1000]  New User Creation upon after changing contact email & deleting Secondary Email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login from your primary email (test1@gmail,com)
2. Add a secondary email to the user account. (Ex. test2@gmail,com)
3. Set the secondary email as the default and make it the login email.
(After this step, test2 becomes default email and test1 becomes secondary email)
4. Attempt to login using the newly set login email (try both test1 & test2 email). Note the successful login
5. Now, delete the secondary email(test1) from the account.
Try to login again using the deleted secondary email.

## Expected Result:
The login should be successful from both email id since the email cleary says that ‘You can still access Expensify with secondary logins going forward’ and another email that confirms ‘Once you've validated your secondary Expensify login, you can forward receipts and sign in to Expensify using both [Email 1] and [Email 2].

## Actual Result:
A new user account is created using the deleted secondary email as the primary email.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d7c5a637-2f2d-4fe0-857d-ec1a2ddd2886

https://github.com/Expensify/App/assets/93399543/c3d1f89c-ff22-42d7-99c6-9d39a280db01

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687218282148989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015202ee7f8e0a4711</li>
        <li>Upwork Job ID: 1676661496394375168</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by slafortune** [comment]
Looks good 👍

**Comment by Santhosh-Sellavel** [comment]
@slafortune I believe this working as expected only. Can you check with PM or other engineers internally, please?

**Comment by slafortune** [comment]
Ah!  You are correct @Santhosh-Sellavel I miss read the original report.  It is expected that the removed secondary email will create a new account.
