### ISSUE TITLE
Web - Amount sent message not shown after we send the money and remain in the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21559]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a chat with any user
2. Press the + button and send any amount of money to that user
3. The message or the amount sent is not shown in the chat
4. When we change chats and come back to the original chat, only then the message is shown

## Expected Result:
Message should be shown after we send the amount to user

## Actual Result:
Message is not shown until after we change the chat and come back again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-5 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e0b91d59-67ac-434e-a9d1-86c1780782ea

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MohsinAliTanvir
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687176371429829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
reviewing

**Comment by greg-schroeder** [comment]
I cannot reproduce this

**Comment by greg-schroeder** [comment]
Pinged in slack to get more reproduction steps/pre-reqs
