### ISSUE TITLE
Dev - Console error on opening detail page by clicking on mentioned user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any conversation
3. Type @ and mention any user  (open console)
4. Click on any particular mentioned user -> detail page should open
5. Notice on opening details page throw error on console
## Expected Result: 
No console error should appear
## Actual Result: 
Console error appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-21 at 11 16 47 AM](https://github.com/Expensify/App/assets/43996225/bd533aec-026d-44fd-bcf7-6cdbda00d6dd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687326565653439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Dev - Console error on opening detail page by clicking on mentioned user
### What is the root cause of that problem?
The root cause is on `DetailsPage` we are using `PressableWithoutFocus` component and on that we passing style as an array instead of object that the cause of the warning 
### What changes do you think we should make in order to solve the problem?
We should pass style as an object rather than array just like we are passing everywhere else
```diff
// DetailsPage.js
<PressableWithoutFocus
-  style={styles.noOutline}
+  style={[styles.noOutline]}
   onPress={show}
>
```

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on opening detail page by clicking on mentioned user

### What is the root cause of that problem?
`PressableWithoutFocus` component `style` prop is expecting the data of type `array of objects` whereas we are passing only `object` for `DetailsPage`. This is causing the console warning issue.
https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/components/Pressable/PressableWithoutFocus.js#L19
https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/pages/DetailsPage.js#L151

### What changes do you think we should make in order to solve the problem?
We should pass the object within an array that will meet the expected type and the error/console warning gets resolved.
`style={[styles.noOutline]}`

**Comment by ahmedGaber93** [comment]
Console log show two errors, not only one.
```
Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `PressableWithoutFocus`, expected an array.
Warning: Failed prop type: Provide a valid string for accessibilityLabel prop when accessible is true at GenericPressable
```


https://github.com/Expensify/App/assets/41129870/74c742a3-f64a-406f-8136-2d52f8423146



and my proposal here fix the two errors.

## Proposal

[My proposal](https://github.com/Expensify/App/issues/21575#issuecomment-1607652715)

**Comment by dylanexpensify** [comment]
Posting for repro w/dev

**Comment by dylanexpensify** [comment]
bumped request in slack

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment]
@kavimuru is this still occurring?

**Comment by dylanexpensify** [comment]
ok pinging original author for minor fix of brackets.

**Comment by dylanexpensify** [comment]
context https://expensify.slack.com/archives/C01SKUP7QR0/p1687949082476329

**Comment by kavimuru** [comment]
@dylanexpensify this is happening in Dev only and I couldn't check
