### ISSUE TITLE
[$1000] Web - Not able to split money on public room with console error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A ( should be phone account)
2. Create a new room with Public mode
3. Send a message on the room
4. Click on header and copy the share URL
5. In a new window , login with User B, paste the URL so that User B can have access to the room
6. From user A, click on + icon on the room and click on split bill > enter any amount > Finally click on split button
7. Notice that the split button doesn't work. Also, we get a console error. Along with this, if you then hover over description, a disabled cursor will be shown

## Expected Result:
Able to split money on public room with no console error

## Actual Result:
Not able to split money on public room with console error

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f41a40d9-005d-404a-a74c-1ee8458b46a8

https://github.com/Expensify/App/assets/93399543/e02857ea-8251-47d8-bc8d-378fcc94bac9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687777131873059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011256193a0e3df461</li>
        <li>Upwork Job ID: 1674166540947750912</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by abekkala** [comment]
Not overdue - looking for proposals

**Comment by abekkala** [comment]
@abdulrahuman5196 Can you review the proposal that have been provided by @dukenv0307

**Comment by abekkala** [comment]
@kevinksullivan Reassigning for sabbatical

___

### CURRENT STATUS:

Waiting on proposals to be reviewed/accepted. If we don't find a suitable proposal in the next week we can take this to the expert contributors to pick up

**Comment by abdulrahuman5196** [comment]
>Notice that the split button doesn't work. Also, we get a console error. Along with this, if you then hover over description, a disabled cursor will be shown

None of this is happening for me in latest main. @dukenv0307 @kevinksullivan

**Comment by kevinksullivan** [comment]
Same, I'm not having this issue either. Closing out.

**Comment by priya-zha** [comment]
I'm still able to reproduce this issue (dev/staging and prod)

https://github.com/Expensify/App/assets/34065075/ffacfe04-f876-48d5-be16-94ef950a8c6c
