### ISSUE TITLE
Request Money - Unexpected error occurs in IOU when requesting money twice through chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign.
2. Select "New Chat" and search for email.
3. Click on plus sign > Request Money > add desired numbers and click Next.
4. Observe that nothing is previewed, then repeat step 3 and go to IOU.
5. Observe unexpected errors in IOU.

## Expected Result:
No unexpected error should occur when requesting money through chat.

## Actual Result:
An unexpected error occurs in IOU when requesting money twice through chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/753f58c1-24ff-41d3-ac7c-52912ac596af

https://github.com/Expensify/App/assets/93399543/578408fc-c3d5-44c8-a95b-5cc4d4cb9d8c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687416755208539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
Backend is responding with this

<img width="893" alt="Screenshot 2023-06-26 at 6 55 37 PM" src="https://github.com/Expensify/App/assets/59907218/c2946c5f-b428-4360-98d4-64cd74ccb013">

**Comment by sophiepintoraetz** [comment]
Dupe https://github.com/Expensify/App/issues/21208

**Comment by tewodrosGirmaA** [comment]
Hello,  @sophiepintoraetz, I believe the root cause may not be the same. When I press the plus sign and request money, it works fine. However, in my case, the issue occurs when I request money inside a new chat and try to do it twice. I don't think this is the same root cause. I am willing to help if needed, but if you cannot reproduce the issue, please let me know. If you are not convinced, it's okay to leave it as closed.

**Comment by tewodrosGirmaA** [comment]
@sophiepintoraetz  Additional videos 
[screen-capture (66).webm](https://github.com/Expensify/App/assets/118253010/006b8a56-dcba-4eee-a326-4401e5df1302)

**Comment by tewodrosGirmaA** [comment]
even nothing comes on the preview  after splitting the bill inside the new chat
![image](https://github.com/Expensify/App/assets/118253010/09c960ab-33fe-4b0f-92f6-323503630c3b)
