### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Reopened task message does not translate to Spanish in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21563]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences >Language
2. Change Language to Spanish
3. Click on + icon
4. Select  Assign task option
5. Enter and click on next button
6. Click on Assignee and select Assignee
7. Click on confirm task button
8. Go to task thread
9. Click on mark as done
10. Click on three dots and reopen task
11. Check the LHN

## Expected Result:
Message should be in Spanish

## Actual Result:
Message shows in English

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e42c9489-25e0-49dd-bb20-89e9f2b8c3d1

https://github.com/Expensify/App/assets/93399543/679aba6a-e32e-45cd-9c70-fdcf7f2fd320

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687417838617489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01397ba738cd207f7d</li>
        <li>Upwork Job ID: 1673345925242044417</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
I would suggest we hold this issue or close it as we are redesigning task details page.
https://github.com/Expensify/App/issues/19330

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/21563#issuecomment-1607531905) from @Ollyws looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by anmurali** [comment]
@srikarparsi this is blocked on your review/ approval so the selected contributor can fix it.

**Comment by srikarparsi** [comment]
Hey! Sorry for the delay, was OOO yesterday and most of the day before. @Ollyws proposal looks good to me as well, assigning you to the issue. Thanks @sobitneupane!

**Comment by anmurali** [comment]
Not overdue, due for payment tomorrow

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18806
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18806#issuecomment-1648076064
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1690210841559409
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Click FAB button > Assign Task
2. Proceed to create a task
3. Go to task thread
4. Click mark as done
5. Go to Settings > Preferences > Language
6. Change the language to Spanish
7. In the LHN verify that the 'completed task' text is translated to Spanish ('tarea completada').
8. Go to Settings > Preferences > Language
9. Change the language back to English
10. Go to task thread
11. Click on three dots and reopen the task
12. Go to Settings > Preferences > Language
13. Change the language to Spanish
14. In the LHN verify that the 'reopened task' text is translated to Spanish ('tarea reabrir').

**Comment by anmurali** [comment]
@gadhiyamanan and @Ollyws have been paid. 
@sobitneupane waiting on you to accept the offer
@srikarparsi - do you agree with the regression proposal?

**Comment by sobitneupane** [comment]
Payment requested on newDot.

**Comment by JmillsExpensify** [comment]
@anmurali Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @sobitneupane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by JmillsExpensify** [comment]
Reached out via DM

**Comment by anmurali** [comment]
- [x] Issue Reporter @gadhiyamanan  $250
- [x] Contributor @Ollyws $1000 + $500 (speed bonus)
- [ ] Contributor plus @sobitneupane $1000 + $500 (speed bonus)

**Comment by JmillsExpensify** [comment]
Reviewed details for @sobitneupane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by sobitneupane** [comment]
We should be good to close this issue.

**Comment by srikarparsi** [comment]
Thanks @sobitneupane, closing this outl.
