### ISSUE TITLE
Web – Concierge message is highlighted on flagging message as offensive.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any “Chat”
2. Flag any message as offensive
3. Notice that at the bottom, the Concierge message appears and is highlighted.

## Expected Result:
The Concierge message should not be highlighted when a message is flagged as offensive.

## Actual Result:
The Concierge message is highlighted when a message is flagged as offensive.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/01e1af0f-ae16-47ba-9d08-a4044851ac44

https://github.com/Expensify/App/assets/93399543/efbf0227-ab7d-43e0-91ad-195abf25f954

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687419980055589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Confirming expected behavior with Shawn

**Comment by sonialiap** [comment]
Shawn confirmed this is expected. Not a bug
