### ISSUE TITLE
[HOLD #22699] Chat - Change in primary contact method is not displayed dynamically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B (user B will need secondary contact added and verified)
3. Open user B report from user A device and open user B details page
4. From user B device, change contact method from settings->Profile->Contact method
5. Observe in user A device that user B contact method is not changed, revisit user B chat to observe that it is now changed.

## Expected Result:
App should dynamically update contact method in reports and on user details page

## Actual Result:
App does not dynamically update contact method in reports and on user details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d7d6c011-5c27-4163-8f3a-a2a489d1830f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687424671388809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
I am OOO. Going to leave this for you @anmurali

**Comment by shawnborton** [comment]
All good on my end!

**Comment by mallenexpensify** [comment]
Putting on hold pending
- https://github.com/Expensify/App/issues/22699

Removed bug and added NewFeature as discussed in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1688646398596839)

**Comment by anmurali** [comment]
I am also degrading this since it is held

**Comment by anmurali** [comment]
Still on hold.

**Comment by anmurali** [comment]
Still on hold.

**Comment by shawnborton** [comment]
Still holding

**Comment by anmurali** [comment]
Making this a monthly as #22699 is a monthly issue.

**Comment by shawnborton** [comment]
Seems like we're still holding here

**Comment by anmurali** [comment]
This is on hold for https://github.com/Expensify/App/issues/22699, which is marked as not a priority. Should we close this? @shawnborton

**Comment by shawnborton** [comment]
That works for me!
