### ISSUE TITLE
Web - The logic of removing member from workspace's is not is not consistent

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. A is admin, and A invited B
2. User A and B are both in #announce room
    - CASE 1: If "A removed B from workspace when B is opening #announce" >> "hm, not here" displays
   - CASE 2: If "A removed B when B is opening other report" >>> B no longer see the Report
3. CASE 3: If "B closed the browser" and "A removed B":
    - When B opens it again >> it show "Unavailable workspace" in the LHN
    - B can reply to it, but the error show "Report no longer exists"

## Expected Result:
The logic of removing member from workspace's should be consistent

## Actual Result:
The logic of removing member from workspace's is not is not consistent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/010eb64f-ee48-42a9-aaa9-a43b914cb40f

https://github.com/Expensify/App/assets/93399543/cab2bc29-c746-4bd5-99d6-f71cbb045844

https://github.com/Expensify/App/assets/93399543/322ea4a6-1ad3-454c-b611-8e879ae2566b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687427442950349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tranvantoan-qn** [comment]
Screenshot for Case 3 (extracted from the video above)

<img width="1397" alt="Case 3" src="https://github.com/Expensify/App/assets/10254571/d1399436-056e-42cd-af82-3c9b611eb9c4">

**Comment by slafortune** [comment]
Still not able to reproduce.
