### ISSUE TITLE
Dev - Web - Two console error when open user url

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to android
2. Create a new workspace
3. Click on FAB icon and click on new room
4. Enter the room name
5. On workspace, select the newly created workspace from the dropdown and notice that even when we have selected the workspace, it throws an error 'Please select a workspace'
6. If you again select a new workspace from the dropdown, this time no error will be shown

## Expected Result:
No console error.

## Actual Result:
There is two console error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/419e75f8-a380-45cb-9d73-d48807f6e8be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687430016132759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
From: @ahmedGaber93
### Please re-state the problem that we are trying to solve in this issue.
Dev - web - two console error when open user url.
```
Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `PressableWithoutFocus`, expected an array.
Warning: Failed prop type: Provide a valid string for accessibilityLabel prop when accessible is true at GenericPressable
```
### What is the root cause of that problem?
error 1: prop `style` passed as object while it defined in propTypes as array.
https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/pages/DetailsPage.js#L150-L153
error2: GenericPressable has default prop `accessible: true` without having `accessibilityLabel` prop
https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/components/Pressable/GenericPressable/PropTypes.js#L136
### What changes do you think we should make in order to solve the problem?
error1: edit style prop to be array or change prop type to accept object
```javascript
// style={styles.noOutline}
style={[styles.noOutline]}
// or
// style: PropTypes.arrayOf(PropTypes.object)
style: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.object), PropTypes.object])
```
error2: add prop `accessibilityLabel` to `PressableWithoutFocus` and pass it to `GenericPressable`
### What alternative solutions did you explore? (Optional)
error2: remove default prop `accessible: true` from GenericPressable.

**Comment by ahmedGaber93** [comment]
@dhairyasenjaliya This issue has 2 console error, one is a dupe, but the other is not.
Thanks!
