### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Wrong image/email shown in share section of create task when creating a task in money request report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Create a money request report with a user
2. Go into the money request report
3. Create a task, add title and click continue
4. Notice in the 'Share somewhere' section - the user avatar and email are mixed up

## Expected Result:
Correct user details should be shown in share destination of create task in money request report

## Actual Result:
Incorrect user details are shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2afadae1-8140-49e1-8203-7908794968f1

https://github.com/Expensify/App/assets/93399543/3233d5d1-c442-4db1-8e45-27c63b376480

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687436719552939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138cc4c569e7bbc9b</li>
        <li>Upwork Job ID: 1673809747129135104</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong image/email shown in share section of create task when creating a task in money request report.

### What is the root cause of that problem?
If we create a task in report, that report will be set to the parent report and displayed in share section.
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/pages/home/report/ReportActionCompose.js#L423-L429
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/libs/actions/Task.js#L517-L521
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/pages/tasks/NewTaskPage.js#L95-L108

As you can see in the video, the report name is equal to the item in LHN, i.e. the money request report name.
But the report icon is different.
The report icon in LHN item is fetched using below code.
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/libs/SidebarUtils.js#L378
And in share section, the icon is fetched using below code.
https://github.com/Expensify/App/blob/5e6e5cf33e19bea13cb41f7c902c845f977c59d3/src/libs/actions/Task.js#L555
There are no `avatar` and `isPayer` parameter, so the icon is different with one in LHN.
### What changes do you think we should make in order to solve the problem?
We can add `avatar` and `isPayer` parameter in `getShareDestination` just like LHN.
```js
function getShareDestination(reportID, reports, personalDetails) {
    const report = lodashGet(reports, `report_${reportID}`, {});
    const personalDetail = personalDetails[0] || {};
    return {
        icons: ReportUtils.getIcons(report, personalDetails, UserUtils.getAvatar(personalDetail.avatar, personalDetail.accountID), true),
        displayName: ReportUtils.getReportName(report),
        subtitle: ReportUtils.getChatRoomSubtitle(report),
    };
}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by tjferriss** [comment]
I'm able to reproduce this one.

<img width="1058" alt="Screenshot 2023-06-27 at 14 44 47" src="https://github.com/Expensify/App/assets/8292562/19426910-cc76-4800-a6c9-73db3bd0d89d">

**Comment by mollfpr** [comment]
Will leave a review this morning 🙏

**Comment by mollfpr** [comment]
I think showing `x owes $` in the menu item title makes sense here. Because currently, the user tries to create a new task inside the money request report. It matches the current report name. 

The only problem I see is we need to show the right avatar in the menu item.

**Comment by mollfpr** [comment]
@c3024 Share somewhere is not just a person or persons, it means you can share it to any report that happens in your LHN.

> So when the display name is report, whom does it share to?

The current report, no? You create a task from a report not from the global FAB where you can select any report.

> There is no choice to select multiple people as well. So it appeared to me that shareDestination essentially means share to a person.

Not a person but a report.

> Also if the report name is 'x owes y' what should be the correct avatar. The sender's or receiver's?

The avatar is what you have in the LHN of the report.

**Comment by mollfpr** [comment]
We should match the avatar and the report name based on what we have in the LHN. The [proposal](https://github.com/Expensify/App/issues/21582#issuecomment-1608006634) from @StevenKKC looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by StevenKKC** [comment]
@mollfpr @bondydaa PR(https://github.com/Expensify/App/pull/22137) is ready for review.

**Comment by tjferriss** [comment]
It looks like the PR was deployed to staging a couple of days ago.

**Comment by tjferriss** [comment]
@huzaifa-99 I just sent you the offer via Upworks. @mollfpr can you get started on the checklist when you have the time?

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18672

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18672/files#r1268401186

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It's one time bug, so regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Create a money request report with a user
2. Go into the money request report
3. Create a task, add title and click continue
4. **Verify** that the report icon in the 'Share somewhere' section is same to the report icon on LHN
5. 👍 or 👎

**Comment by tjferriss** [comment]
Payments have been sent. We're all good.

**Comment by StevenKKC** [comment]
@mollfpr @bondydaa  Am I not eligible for speed bonus?

**Comment by mollfpr** [comment]
@StevenKKC We are not.

You got assigned on July 4th, and the PR merged on July 10th. Between July 4th and July 10th, there are 5 weekdays (Tuesday to Monday). The bonus is applied to merged PR within 3 business days of assignment.

![Screenshot 2023-07-21 at 22 18 06](https://github.com/Expensify/App/assets/25520267/bf9ffd54-ab1d-4fd1-bc93-9baf71429c71)

![Screenshot 2023-07-21 at 22 18 20](https://github.com/Expensify/App/assets/25520267/3b44e4d1-00f5-4cc6-892a-6b8826e1999c)

**Comment by StevenKKC** [comment]
@mollfpr
I created a PR on July 3 EDT, but you first reviewed on July 8 EDT.
In this case, am I not eligible for speed bonus?
![1](https://github.com/Expensify/App/assets/131836113/2f0320b3-ad87-4810-adf4-ba2ed3af3830)
![2](https://github.com/Expensify/App/assets/131836113/bdd08d8b-1395-40af-959e-419a75f2002e)

**Comment by mollfpr** [comment]
The bonus applies to both the assignee contributor and the C+. I don't think there's a case it's given to only one of them. I apologize didn't take the review earlier, I have more prioritize PR and issues to review at that time.

**Comment by StevenKKC** [comment]
@tjferriss Can you tell me what you think about this case?

**Comment by tjferriss** [comment]
@StevenKKC as @mollfpr outlined, you're not eligible for the bonus. The bonus is team-based between the Contributor and C+.
