### ISSUE TITLE
[Awaiting Payment August 2nd] [$1000]  input is not auto-focused on debit card details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to payments > debit card
## Expected Result: 
first input should be auto-focused
## Actual Result:
is not auto-focused

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b26c3a1b-c2ed-497b-b394-461ed1e66503

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687018369364509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014eff8b5c575ecd53</li>
        <li>Upwork Job ID: 1674171837771591680</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

input is not auto-focused on debit card details page


### What is the root cause of that problem?

Root cause is that in `AddDebitCardPage` for the first input which is `nameOnCard`, we have not added autoFocus prop which makes the input not auto focused.

https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/pages/settings/Payments/AddDebitCardPage.js#L130-L133

### What changes do you think we should make in order to solve the problem?

For solving this, we need to add autoFocus prop to the `nameOnCard` input and in our app we have some transition issues with android because of keyboard opening. So along with the autoFocus, we need shouldDelayFocus too for the android which adds a slight delay which is required because it takes that time to open the keyboard in android.

```js
<TextInput
    inputID="nameOnCard"
    label={this.props.translate('addDebitCardPage.nameOnCard')}
    autoFocus
    shouldDelayFocus={shouldDelayFocus}
/>
```
<details>
  <summary>Results</summary>


https://github.com/chiragxarora/pdf-download/assets/54641656/dffd3454-52a5-4ddb-9bae-57c31bfc0bbb



</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by abekkala** [comment]
Ok, I was able to reproduce this as well.

**Comment by abekkala** [comment]
I agree I don't believe this would fall under a feature request.

@abdulrahuman5196 what do you think of the proposals so far?

**Comment by abdulrahuman5196** [comment]
@chiragxarora 

>I disagree this being a feature request 

This i agree

>we have all other forms in RHP with autoFocus enabled

Could you share which other have?

>debit card was added recenlty and probably missed

I don't agree on this. Debit card step has been present for long time.

**Comment by abdulrahuman5196** [comment]
@abekkala It seems some places we are auto-focusing first field in the form and some places we are not focusing. 
I think auto-focusing the first field is the right way to go and we can figure out other places not doing that and fix those as well part of this issue. 
What do you think? Should we fix this as mentioned above or do nothing?

**Comment by abekkala** [comment]
If all other forms in RHP have autoFocus enabled except the debit card option then we can fix that.

**Comment by abekkala** [comment]
@trjExpensify Reassigning for Sabbatical

___

### CURRENT STATUS

Reviewing proposals/discussing the fix. 
I believe the Debit Card option should auto-focus when opened. If we can't get to a suitable proposal for fix, then we can go to expert contributors.

**Comment by trjExpensify** [comment]
@luacmartins will be a good person to chime in here. Should the first field on the empty debit card form page be auto-focused? I believe it should be!

**Comment by abdulrahuman5196** [comment]
>Should the first field on the empty debit card form page be auto-focused? I believe it should be!

Yes. I second this. Maybe we could also find places that is not doing this and make them do it.

**Comment by luacmartins** [comment]
Yes, that input should be autofocused.

**Comment by trjExpensify** [comment]
>Yes, that input should be autofocused.

Thanks Carlos! 

@abdulrahuman5196 which direction are you liking here?

**Comment by abdulrahuman5196** [comment]
@chiragxarora @dhairyasenjaliya Kindly have all the required information pertaining to your proposal in a single comment i.e to update the original proposal comment. If some information are present in subsequent comments, it is easy to get missed.

**Comment by abdulrahuman5196** [comment]
I have raised an internal slack to get information on the recommended way - https://expensify.slack.com/archives/C02NK2DQWUX/p1688667385284409

Will respond here once I have the answer

**Comment by trjExpensify** [comment]
I've bumped the thread and also asked for @luacmartins's opinion having worked on Forms in the App quite a bit!

**Comment by trjExpensify** [comment]
@abdulrahuman5196 what do you think here?

**Comment by abdulrahuman5196** [comment]
Hi, I am checking on this now

**Comment by abdulrahuman5196** [comment]
Got confirmation on the internal chat and we are going to go with the `onEntryTransitionEnd` option.

@dhairyasenjaliya 's proposal here https://github.com/Expensify/App/issues/21587#issuecomment-1607963168 looks good and works well as per the expectation.

🎀 👀 🎀
C+ Reviewed

cc: @trjExpensify

**Comment by abdulrahuman5196** [comment]
@roryabraham C+ approved comment is here https://github.com/Expensify/App/issues/21587#issuecomment-1634625891

**Comment by abdulrahuman5196** [comment]
@chiragxarora 
`shouldDelayFocus` is internally using setTimeout which we are trying to avoid. 
And AFAIK, the approved proposal is working on reload as well.

**Comment by roryabraham** [comment]
> It does not focus, you can try other pages too where onEntryTransistionEnd is used like assign task page

Just tested a few pages, including `NewTaskTitlePage` and `MoneyRequestDescriptionPage`, that use the `onEntryTransitionEnd` approach to focus a text input. In both cases the text input was auto-focused as expected upon refresh.

**Comment by abdulrahuman5196** [comment]
@chiragxarora I tried multiple times and wasn't able to repro the reload issue in the Fix PR.
You could create a issue in our bugs channel on the same. If there is some issue on `onEntryTransistionEnd` when reload, it will span across multiple pages. So ideally we should what is wrong with `onEntryTransistionEnd` instead of moving away from it IMO as it is the current recommended approach.


We could create a issue like this where focusing is messed up in safari - https://github.com/Expensify/App/issues/10414 and work on a fix. I think focusing is somewhat not stable in mweb itself(Not specific to this issue.)

cc: @roryabraham

**Comment by roryabraham** [comment]
PR to fix this is on staging.

**Comment by trjExpensify** [comment]
Updating the title to reflect the payment date, let me know if that's not correct.

**Comment by trjExpensify** [comment]
Alrighty, payments are due. There was a weekend in this one, but the C+ review was completed within the 72 business hours window, so I'm applying the bonus. 

- @abdulrahuman5196 $1,500 for the C+ review & #urgency bonus
- @dhairyasenjaliya $1,500 for the fix & #urgency bonus 
- @chiragxarora $250 for the bug report

Settled up with you all! Closing.
