### ISSUE TITLE
Web - Link previews do not work correctly (Production & Staging) due to Content-Security-Policy

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21589]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. send a link "google.com"
2. Preview Image is missing
3. open console Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' <URL> <URL> data: <URL> <URL> <URL> <URL> <URL> <URL> blob:".

## Expected Result: 
Image should be displayed without error
## Actual Result: 
Image is displayed with error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-21 at 7 04 12 PM](https://github.com/Expensify/App/assets/43996225/0140c1e1-43e3-4084-b867-37e403f110e9)
![Screenshot 2023-06-21 at 7 03 23 PM](https://github.com/Expensify/App/assets/43996225/e0254b26-703e-43af-a659-81abc7914b5a)
<img width="960" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/48e7a689-86e8-4263-8e95-2cff51c07ef9">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nodebrute
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687355734542809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b28eb78364d0fe58</li>
        <li>Upwork Job ID: 1673386488717828096</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
This will need to be internal as we need to have a discussion about our CSP as it relates to loading dynamic content that might be contained in the link preview metadata.

**Comment by marcaaron** [comment]
Demoting this to weekly. This feature will be largely unavailable until we start paying for API services.

**Comment by marcaaron** [comment]
Not overdue. On HOLD.

**Comment by CortneyOfstad** [comment]
@marcaaron where are we at with this?

**Comment by marcaaron** [comment]
Thanks for the bump @CortneyOfstad. Will give this a look next week. It's on my todo list but at somewhat of a lower priority.

**Comment by CortneyOfstad** [comment]
No worries and sounds good @marcaaron!

**Comment by CortneyOfstad** [comment]
@marcaaron Bump please!

**Comment by marcaaron** [comment]
Making it a weekly. This will happen when it happens.

**Comment by marcaaron** [comment]
It's a "bug" but related to a "New Feature" so I think we are still implementing it... not really WAQ urgency because the thing that is broken is still in development.

**Comment by marcaaron** [comment]
I would assume so.

**Comment by marcaaron** [comment]
Hmm pretty weird but this isn't happening for me anymore. The previews are loading fine on web 🤔 

Does someone have a link available where this is reproducible? @kavimuru can we retest?

**Comment by kavimuru** [comment]
@marcaaron Seems it is fixed and not able to reproduce for me.
![image](https://github.com/Expensify/App/assets/43996225/9ef394b4-9932-49c5-99b1-acbbf26424c7)

**Comment by marcaaron** [comment]
Awesome I'm gonna close it out for now.

**Comment by marcaaron** [comment]
Thanks, but I actually don't manage the payments - please refer to the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions).
