### ISSUE TITLE
[HOLD #16923] Tooltip is not dismissed on opening any link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in mac safari/ mac chrome
2. Open any report
3. Send any link eg: testing.com
4. Hover and click on link
5. Revisit the tab to see that tooltip is not dismissed
6. Try steps 1-5 on windows to see that tooltip is dismissed for same flow in windows
## Expected Result: 
App should dismiss the tooltip when link is opened like it does on windows chrome
## Actual Result: 
App does not dismiss the tooltip when link is opened from a report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b9087e4c-5e03-4e6c-9922-e2fab273930e

https://github.com/Expensify/App/assets/43996225/f29146ee-9f38-4e39-a313-af38f08ffd20

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687342007908939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cubuspl42** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Link's tooltip does not disappear after the link is followed and the new tab opens.

### What is the root cause of that problem?

It seems that in Chrome (at least on macOS) when the new tab is open as a consequence of a link being clicked, that link does not receive `mouseleave` event.

In consequence, `Hoverable` doesn't consider itself being unhovered, so `onHoverOut` is not called.

### What changes do you think we should make in order to solve the problem?

We can detect that the document's _visibility_ changes to _hidden_ and handle unhovering there.

```
    handleVisibilityChange() {
        if (document.visibilityState === 'hidden') {
            this.setIsHovered(false);
        }
    }
```

**Comment by bernhardoj** [comment]
Same root cause with https://github.com/Expensify/App/issues/18675

**Comment by mallenexpensify** [comment]
@parasharrajat , thanks for creating the GH Project
- https://github.com/orgs/Expensify/projects/49/views/1

Is there going to be one main GH to fix these bugs? If so, I can put this issue on hold and link to that

**Comment by mallenexpensify** [comment]
Putting on hold pending
- #16923

**Comment by mallenexpensify** [comment]
Still holding on #16923

**Comment by mallenexpensify** [comment]
Still holding on https://github.com/Expensify/App/issues/16923
