### ISSUE TITLE
User can't sign-in after signining out

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Enter email > click on 'Continue' button > enter magic sign-in code
3. Sign out
4. Repeat step 1 - 2 for till user is no longer able to sign-in. Signing-in and out for 4 or 5 times seems to be creating the issue for me
## Expected Result: 
User should be signed-in
## Actual Result: 
User is not signed-in & endless spinner is displayed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Not reproducible by applause
**Reproducible in production?:** Not reproducible by applause
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/63a05456-dd17-4587-b6fb-f85239d182f9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687342091988009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
I don't think this issue reproducible.

**Comment by slafortune** [comment]
not reproducible
