### ISSUE TITLE
[$1000] Unable to sign in via a new account, error message displayed "Can not get the active policy ID of the user"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot production (new.expensify.com)
2. Type puneet+6.26.23@expensify.com and Continue

## Expected Result:
User is able to log in

## Actual Result:
Unable to sign in via a new account, error message displayed "Can not get the active policy ID of the user"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (100)](https://github.com/Expensify/App/assets/93399543/5cb8d723-2b51-4605-9512-9f4b4d2d85f5)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Puneet Lath

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687451722345759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019eaaf3c2529e5cb6</li>
        <li>Upwork Job ID: 1673615488910049280</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
From the logs:

```
[OOPS!] API Threw: Can not get the active policy ID of the user ExpException - f3188796922f1ae9bc23460c6f176fdf ~~ onyxData: '[0: '[onyxMethod: 'merge' key: 'account' value: '[errors: '[1687886466935362: 'Can not get the active policy ID of the user']']']']' exceptionMessage: 'Can not get the active policy ID of the user' exceptionFile: '/git/releases/expensify.com/a1ca6a0/lib/PolicyStore.php' exceptionLine: '165' exceptionCode: '400'
```

**Comment by PauloGasparSv** [comment]
Well by the looks of the logs [this may be internal](https://github.com/Expensify/App/issues/21609#issuecomment-1609948650) so I'll focus on this in a bit!

**Comment by PauloGasparSv** [comment]
Replicated and generated these [log](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%227de051635d174ee9-SJC%22%20AND%20timestamp%3A%5B2023-06-27T00%3A00%20TO%202023-06-28T23%3A59%5D)

**Comment by PauloGasparSv** [comment]
Could not replicate locally!

Still investigating why that active policy NVP was not found, I think it should have been created before we tried to fetch it but some recent update probably broke that.

**Comment by PauloGasparSv** [comment]
I think we are failing to create [the personal policy](https://github.com/Expensify/Auth/blob/0fb5fd5aa7543febc92652be6c9415529398c78e/auth/lib/Account.cpp#L2720)  for these accounts since I can only see instances of `No personal policy value, not creating it` and no `Created personal policyID` in logs

Trying to figure out why!

**Comment by PauloGasparSv** [comment]
I'm still trying to understand how we create user's first policy when `BeginSignIn` is called.

So far this is the info I have:

1. Not so sure if [the line I mentioned above](https://github.com/Expensify/Auth/blob/0fb5fd5aa7543febc92652be6c9415529398c78e/auth/lib/Account.cpp#L2720) is failing
2. This works locally but not in Prod/Stag
3. In my local tests `CreatePolicy` is also called and it calls `Policy::setActiveID`. Pretty confused on when `CreatePolicy` is called though, I thought the line from item 1 was responsible for setting the active policy id.
4. Signing into OldDot with one of the accounts I used to test leads to the error mentioned [here](https://expensify.slack.com/archives/C049HHMV9SM/p1687451993225119?thread_ts=1687451722.345759&cid=C049HHMV9SM)
    <img width="600" alt="image" src="https://github.com/Expensify/App/assets/6564265/4e38aec0-ebaa-4d15-906f-72975fecf350">


Btw the following screenshot makes me believe my hypothesis of the Policy not being created:
    <img width="300" alt="image" src="https://github.com/Expensify/App/assets/6564265/20d77825-3d31-431f-bb8d-b1214bacab9d">

**Comment by PauloGasparSv** [comment]
I'm clocking off in a bit but since this is a pretty big problem[ I shared it in #engineering-chat](https://expensify.slack.com/archives/C03TQ48KC/p1687901168669319) so someone else can take a look while I'm offline

**Comment by cead22** [comment]
Maybe what's happening is that we're not calling UserAPI::authenticate, which calls `User_FixAccount::fix`, which sets the active policy NVP if one isn't set.

I don't see BeginSignin calling `UserAPI::authenticate`

**Comment by aldo-expensify** [comment]
This looks like the same as this, right? https://github.com/Expensify/Expensify/issues/287904
