### ISSUE TITLE
mWeb - Blue outline on long press after reloading the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Be on 'About' page
2. Refresh the page
3. Long press on one of the items

## Expected Result:
No blue outline on the screen edges

## Actual Result:
There is blue outline the screen edges

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99138e37-3d8d-4742-aa79-e1f030dfca31

https://github.com/Expensify/App/assets/93399543/3321834a-ca26-4716-b33b-4f78f7cd8e86

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eVoloshchak
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687457056485909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I couldn't reproduce this in iOS Safari on v1.3.33-3. Asking for more details in the Slack thread.

**Comment by eVoloshchak** [comment]
I can reproduce this in OS Safari, v1.3.33-3

https://github.com/Expensify/App/assets/9059945/e0b8d6ad-9df6-43f8-90d6-e21f2e97bbfe

**Comment by sakluger** [comment]
I was able to reproduce, but this doesn't affect my usage of Expensify, and I don't feel like it's something we need to fix. I'm going to close for now, feel free to continue the discussion in Slack if you think it's a bug that affects users adversely.
