### ISSUE TITLE
Resend magic code timeout is not implemented on Contact methods section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21619]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the profile avatar
2. Click on 'Profile' link
3. Click on 'Contact method' link
4. Click on 'New contact method' button
5. Enter email & click on 'Add' button
6. Open the newly added email

## Expected Result:
Resend magic code timeout should be implemented as it is implemented on sign-in section

## Actual Result:
Resend magic code timeout is not implemented

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0e006f77-e637-401b-a3ab-40bd394a8a50

https://github.com/Expensify/App/assets/93399543/e909041c-d7de-444f-a71b-60a06503d6b9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687458682548469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
@NikkiWines thoughts on this one?

**Comment by NikkiWines** [comment]
Hmm, it's true it's not consistent with the sign in flow, but I think it's ok. We added the timer in the sign-in flow after [this discussion](https://expensify.slack.com/archives/C048ZLJ78P5/p1685755142102059) as a kind of visual block to prevent users from throttling themselves. We don't see that as often with people validating secondary logins, so I don't think it's necessary to have here. What do you think?

**Comment by muttmuure** [comment]
My personal take is to wait and see how many customer reports we get of this
