### ISSUE TITLE
[$1000] Error shown if a new user (without existing login) and an old user is removed from the workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21612]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new workspace and Invite two users (first user should be an Expensify account holder and the other one should be a random email user without pre-existing login )
3. Then click on 'Select all' checkbox and remove both the users and notice that it throws an error and no members are deleted
4. Again create a new workspace and now just try to add and remove the same random email user (just one non-existing account user that we used earlier) and notice that it doesn't throw an error
5. Again, on the same second workspace, now try to add two users (same random email user used previously  + any existing expensify user). Then after, remove both the users together and notice that, this time, even if you have removed the existent and non-existent user together, it didn't throw an error
6. Thus, for this first time it throws an error whenever we try to remove the existing and non-existent user from the workspace
## Expected Result: 
Users with existing expensify account and a non-existing account should be removed without any error in the first time only
## Actual Result: 
Error shown if a new user (without existing login) and an old user (expensify account) is removed from the workspace

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** not able to reproduce by applause
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ca4f4086-c80b-4e5b-b4b2-821ac72b9c7a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687346938611329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9fb0944d38943ea</li>
        <li>Upwork Job ID: 1673654695476334592</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
Can I pick this?! @kavimuru

**Comment by s77rt** [comment]
@b4s36t4 Please check out our [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). We have a proposal template to follow.

**Comment by b4s36t4** [comment]
Contributor details
Your Expensify account email: maheshvagicherla99438@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f450a49ceab36aa

**Comment by b4s36t4** [comment]
@s77rt I think this issue been fixed, I'm not able to re-produce the same. Can you verify once? if not any specific conditions needed to re-produce?

**Comment by Beamanator** [comment]
This should have already been fixed by a backend PR - https://github.com/Expensify/Web-Expensify/pull/37898

**Comment by Beamanator** [comment]
Oh reopening b/c still I believe @priya-zha is due payment for reporting this bug

**Comment by johncschuster** [comment]
Good shout, @Beamanator!

@priya-zha, can you apply to the above Upwork link when you get a chance?

**Comment by priya-zha** [comment]
Proposal submitted. Thanks.
