### ISSUE TITLE
[iOS] Enter magic code screen is still showing even if user not logged in and app is KILLED before

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Mobile app >> request magic code
2. KILL app (not just put it into background)
3. Open app again
## Expected Result: 
Since the user `hasn't logged in yet and app is KILLED`, the app's session *should be cleared* so when user open app again, they will start the login flow over
## Actual Result: 
Enter magic code screen is still showing (`but no actual magic code is sent`)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/48322c93-cd33-4ecf-8d0d-91016750a8b2

https://github.com/Expensify/App/assets/43996225/2d68dab1-b53d-45c4-9c65-ede1a60e1fda

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1687357492922579
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tranvantoan-qn** [comment]
**Problem with current logic:**
- No actual magic code is sent
- If user opens the app again after a long time then enter the old magic code >>   but that code may be expired

**Comment by sophiepintoraetz** [comment]
I don't think this is a bug, the code **is** sent the moment you are on the waiting page. If the person re-opens the app after some time, the countdown timer should indicate that the code has expired so they can resend another one. Thanks for looking into this but I don't think anything needs to change here, so closing.

**Comment by sophiepintoraetz** [comment]
@tranvantoan-qn the code is sent the second the user clicks `Continue` - if it's not sent, it will be because there is an issue with the email client of the user, not because of a UI experience with Expensify. 
<img width="784" alt="image" src="https://github.com/Expensify/App/assets/42940078/b0f15cdc-6462-4d8a-beac-026a70829f31">

**Comment by sophiepintoraetz** [comment]
>OR at least, do not show the counter, so the user can request the code again without waiting for 30s

This is not possible - we find that users request a new code and hit our throttling limits too quickly, so this is intended. In short, users shouldn't be exiting an app they're about to authenticate.

**Comment by tranvantoan-qn** [comment]
@sophiepintoraetz 
No, it did send the first time use**r enter the email** and **Continue**

I mean in this case:
- I Killed the app
- (Leave it for 5 mins, for example)
- Then reopen the app
- I am re-directed to the "Magic code is sent" >> This is confusing for the user

 `In short, users shouldn't be exiting an app they're about to authenticate.`

>> Yeah, OK. I've seen many issues reported like "user with the name/email is a few lines long - which isn't normal in real life" so I think this kind of issue is also accepted (_let's say if the user didn't exist it intentionally but the app stopped working at that step some how)_
Sorry
