### ISSUE TITLE
Settings Page not scrollable to bottom on Mweb

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings on mWeb
## Expected Result: 
notice that "Open in the New Expensify App" banner pushes the page below the bottom input
## Actual Result:
 "Sign Out button" is nearly unreachable

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:**  not reproducible by applause
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4118ea37-4b73-44e5-b7a5-564672e1adaa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @grgia
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687366958023089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
This is due to the smart banner on top.
I think it can be closed based on the discussion here https://github.com/Expensify/App/issues/8791 and https://github.com/Expensify/App/issues/17381

**Comment by trjExpensify** [comment]
Yeah, commented [here](https://expensify.slack.com/archives/C049HHMV9SM/p1687812038541159?thread_ts=1687366958.023089&cid=C049HHMV9SM). Closing!
