### ISSUE TITLE
[$1000] Clicking on back button to close emoji modal takes user back to LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21629]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Click on emoji icon from the composer
3. Click on back button to close the modal

## Expected Result:
Emoji picker should close
## Actual Result:
Emoji picker closes after taking user back to LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7f0e84b5-9562-46d1-a717-97c75a065e11

https://github.com/Expensify/App/assets/43996225/5af42b10-e583-48da-82e9-5b531e036937

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687373497207199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dea35f22a7048c58</li>
        <li>Upwork Job ID: 1673981484525449216</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Reproduced.

**Comment by absolutezero13** [comment]
This is android hardware back button problem yes?

**Comment by absolutezero13** [comment]
Contributor details
Your Expensify account email: ilker897@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e04a206fe6f84390

**Comment by bfitzexpensify** [comment]
Good call @parasharrajat. Closing this out.
