### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Tooltip breaks on dynamic update of display name in new group list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21622]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app on another device and login with user B
3. In user A device, click on plus, new group, search for user B and hover once on avatar to observe tooltip
4. In user B device, go to settings, profile, display name and change display name to very long first and last name
5. Hover again on user B avatar on user A device to observe that tooltip is not distorted and not positioned properly
6. close new group menu on user A device, again open new group, search for user B and again hover on user B avatar to observe that now it looks right and is positioned properly
## Expected Result: 
App should adjust tooltip width too dynamically to ensure it looks right when display name length changes.
## Actual Result: 
App only updates display name dynamically and not width of tooltip when hovered on user on new group page and that user changes its name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3d003796-a37f-4e65-ab68-6c3a5af6114b

https://github.com/Expensify/App/assets/43996225/7edd02e4-21f2-4f8c-b40b-ba3807406c77

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687356088987299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f7af8c7b650e009</li>
        <li>Upwork Job ID: 1674404124264230912</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the user's display name updates while a component that contains that user's display name in its tooltip is rendered, the tooltip does not update its layout and starts flickering when shown.

### What is the root cause of that problem?

`UserDetailsTooltip` passes `renderTooltipContent` to `Tooltip`, but does not pass any `renderTooltipContentKey`, so the tooltip doesn't know that it should recompute its layout.

### What changes do you think we should make in order to solve the problem?

We should pass elements that could affect the tooltip's layout to `renderTooltipContentKey`.

```jsx
    return (
        <Tooltip
            renderTooltipContent={renderTooltipContent}
            renderTooltipContentKey={[userDetails.displayName, userDetails.login]}
        >
            {props.children}
        </Tooltip>
    );
```

**Comment by CortneyOfstad** [comment]
Was able to recreate on my side as well, so going to get eyes on the proposal 👍

**Comment by CortneyOfstad** [comment]
@aimane-chnaif Any thoughts on the above propsal?

**Comment by mallenexpensify** [comment]
Thanks @allroundexperts 

@aimane-chnaif Can you please review the above proposal, it's been over a week since it was posted :/ 
https://github.com/Expensify/App/issues/21622#issuecomment-1609011303

**Comment by CortneyOfstad** [comment]
@aimane-chnaif any updates on the checklist above?

**Comment by CortneyOfstad** [comment]
@aimane-chnaif Bump on the check list above. I cannot move forward with the regression steps until those are completed 👍

**Comment by CortneyOfstad** [comment]
@aimane-chnaif You have been paid, so all set there!

@cubuspl42 and @dhanashree-sawant — sent contracts to both of you. Please accept them in Upwork and let me know here, so I can get those paid to you ASAP. Thank you!

**Comment by cubuspl42** [comment]
@CortneyOfstad Thanks, accepted. What about [the bonus](https://github.com/Expensify/App/issues/21622#issuecomment-1624020102)? 🙂

**Comment by CortneyOfstad** [comment]
Yep, bonus was applied and both of you have been paid with the contracts ending. Thank you!
