### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Attachments flagged as offensive can be viewed and downloaded from attachements previews 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open expensify app and send an attachement from Account 1 to a group with previous attachement history with Account 2 and 3 as members
2. Go to the attached file using account 2 and flag the attachement "assault"
3. Observe that the attachement is removed from the chat history
4. Now go to account 3 and open the attachement preview by clicking on any other attachements sent prior to the flagged attachement
5. Swipe to the left and observe that the flagged attachement can be viewed and downloaded from attachement preview even if it was removed

## Expected Result:
Flagged attachements shouldnt have been accessed once removed
## Actual Result:
flagged attachement can be viewed and downloaded from attachement preview even if it was removed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/659e6779-e7c2-4c95-a0ca-c857ed92adce

https://github.com/Expensify/App/assets/43996225/31094a50-af7a-4cb2-b48c-5656bb56be0b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687361182231919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cd43a7818c0b639</li>
        <li>Upwork Job ID: 1673619006955368448</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by supertech0125** [comment]
Applied on Upwork with solution. 
https://www.upwork.com/freelancers/~0149a584c5c7e7ca7b

**Comment by supertech0125** [comment]
Contributor details
Your Expensify account email: supertech0125@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0149a584c5c7e7ca7b

**Comment by sonialiap** [comment]
@allroundexperts what do you think of the current proposals?

**Comment by sonialiap** [comment]
not overdue, conversation is ongoing

**Comment by mountiny** [comment]
Sorry for missing this one before, assigning @dukenv0307

**Comment by mountiny** [comment]
@dukenv0307 We should not introduce a change which will potentially lead to crash of the app 😅

**Comment by sonialiap** [comment]
@SofoniasN paid for report ✔️ 
@dukenv0307 paid for fix (+bonus) ✔️ 
@allroundexperts please request via NewDot if you haven't already (+bonus)

**Comment by JmillsExpensify** [comment]
Reviewed details for @allroundexperts. The payment of $1500 is accurate based on summary from Business Reviewer. This is approved for payment in NewDot.
