### ISSUE TITLE
 When a comment has been flagged  the notification to the user who flagged the comment again is incorrect.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Go to https://staging.new.expensify.com/r/5593084223054221
3. Flag a comment as Bullying and wait for the “Only visible to you” comment. It should look normal, like: “Thanks for flagging this comment for the Expensify team to review. They will take the necessary steps to resolve the situation.”
4. Flag the same comment again as Inconsiderate and wait for the “Only visible to you” comment - this time, it should look wrong, like: “Thanks for flagging this comment. The content has been pendingHide by the Expensify team.”

## Expected Result:
Whenever someone flags a comment (whether or not it’s the first time), just return as “Thanks for flagging this comment for the Expensify team to review. 
## Actual Result:
Couple times whisper appears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.3
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/4c0cc9f8-e291-49e3-be7d-efc4ed2444bd">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687378019617069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2d06e1e5230173e</li>
        <li>Upwork Job ID: 1673424502711959552</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Internal fix here: https://github.com/Expensify/Auth/pull/8173

**Comment by thienlnam** [comment]
Merged, pending deploy

**Comment by thienlnam** [comment]
Done! No payments due since reporter and fixer were internal
