### ISSUE TITLE
[HOLD for payment 2023-11-07] [$1000] Appropriate Message is not shown when inviting the secondary contact to members.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a Secondary contact for user A.
2. Open an account Using User B
3. Go to workspace then Members
4. Click the invite button.
5. Now, write the secondary contact of user A.
6. Click on Next and then Invite.
7. Notice that a message appears on the Members list page saying "Member not found. To invite a new member to the workspace, please use the Invite button above."  This message should appear when searching for a member that is not in the list.
## Expected Result:
The user is added to the policy members, and a success message appears indicating that it is a secondary contact
## Actual Result: 
The user is not added to the policy members, and a message saying "Member not found" appears.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/98027744-d117-4b20-b737-5642dfdafe1e

https://github.com/Expensify/App/assets/43996225/f6d09632-7d39-4628-b904-f97aebf37d1f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687378050045829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168b338ffdb8d8f7c</li>
        <li>Upwork Job ID: 1677000650172874752</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by johncschuster** [comment]
> Expected Result:
> A message appears indicating that it is a secondary contact 

I'm not sure this is the expected result. If a user's secondary login email is invited to a workspace, I would think their account would be added as a workspace member and no prompt will be shown.

I'm buddy checking this in [Slack](https://expensify.slack.com/archives/C03U7DCU4/p1687865664365699)

**Comment by johncschuster** [comment]
No response in #product. I'm going to cross-post the thread and bump it.

**Comment by johncschuster** [comment]
Meh, I think #product is the right room for this discussion. I've bumped the thread.

**Comment by coderpradp** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Appropriate Message is not shown when inviting the secondary contact to members.

### What is the root cause of that problem?
When inviting a user with their secondary contact method the API `GET /api?command=AddMembersToWorkspace` returns onyxData as below for key `personalDetailsList` and key `policyMembers_`
```
...,
{
    onyxMethod: "merge",
    key: "policyMembers_2F7B14BEF8B73D2C",
    value: [],
},
...,
{
    "onyxMethod": "merge",
    "key": "personalDetailsList",
    "value": []
},
...
```

<details>
  <summary>Full response data from API </summary>
  
  ```
{
  "jsonCode": 200,
  "requestID": "7e2b024e0b5e9884-KTM",
  "onyxData": [
    {
      "onyxMethod": "merge",
      "key": "report_7710969573617247",
      "value": {
        "reportID": "7710969573617247",
        "maxSequenceNumber": 21,
        "lastVisibleActionCreated": "2023-07-06 21:40:57.322",
        "lastReadTime": "2023-07-06 21:40:57.322",
        "lastMentionedTime": null,
        "lastMessageText": "added photoelectric007+user1sec@gmail.com as a user",
        "lastActorEmail": "photoelectric007+user2@gmail.com",
        "lastActorAccountID": 14961999
      }
    },
    {
      "onyxMethod": "merge",
      "key": "reportActions_7710969573617247",
      "value": {
        "4840190911303924729": {
          "person": [
            {
              "type": "TEXT",
              "style": "strong",
              "text": "User Two"
            }
          ],
          "actorEmail": "photoelectric007+user2@gmail.com",
          "actorAccountID": 14961999,
          "message": [
            {
              "type": "COMMENT",
              "html": "added photoelectric007+user1sec@gmail.com as a user",
              "text": "added photoelectric007+user1sec@gmail.com as a user",
              "isEdited": false,
              "whisperedTo": [],
              "isDeletedParentAction": false,
              "reactions": []
            }
          ],
          "originalMessage": {
            "accountID": -1,
            "email": "photoelectric007+user1sec@gmail.com",
            "lastModified": "2023-07-06 21:40:57.322",
            "name": "",
            "role": "user"
          },
          "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_14.png",
          "created": "2023-07-06 21:40:57.322",
          "timestamp": 1688679657,
          "reportActionTimestamp": 1688679657322,
          "automatic": false,
          "actionName": "POLICYCHANGELOG_ADD_EMPLOYEE",
          "shouldShow": true,
          "reportActionID": "4840190911303924729",
          "lastModified": "2023-07-06 21:40:57.322",
          "whisperedTo": [],
          "whisperedToAccountIDs": [],
          "sequenceNumber": 21,
          "isAttachment": false
        }
      },
      "shouldNotify": true
    },
    {
      "onyxMethod": "set",
      "key": "report_5697814073208219",
      "value": null
    },
    {
      "onyxMethod": "merge",
      "key": "policyMembers_2F7B14BEF8B73D2C",
      "value": []
    },
    {
      "onyxMethod": "merge",
      "key": "report_4982509216725819",
      "value": {
        "participants": [
          "+9779840248444@expensify.sms",
          "photoelectric007+user1@gmail.com",
          "photoelectric007+user2@gmail.com"
        ],
        "participantAccountIDs": [14961999, 14961964, 14961992]
      }
    },
    {
      "onyxMethod": "merge",
      "key": "report_7710969573617247",
      "value": {
        "participants": ["photoelectric007+user2@gmail.com"],
        "participantAccountIDs": [14961999]
      }
    },
    {
      "onyxMethod": "merge",
      "key": "personalDetailsList",
      "value": []
    },
    {
      "onyxMethod": "mergecollection",
      "key": "report_",
      "value": []
    }
  ]
}
  ```
</details>

However, our Onyx store has the value stored as objects of objects for key `personalDetailsList`

![image](https://github.com/Expensify/App/assets/20035221/2e8c3dfb-082b-4fd6-b68f-4c0ebfc5df76)

This causes `Onyx.merge()` to throw error `[Onyx] An error occurred while applying merge for key: personalDetailsList, Error: TypeError: modifiedData is not iterable`

![image](https://github.com/Expensify/App/assets/20035221/286ca0e3-61d1-4ff2-a388-6f4264e92e12)

Since the API response is missing account ID for policy member and also personal details, following template is rendered based on the condition.
https://github.com/Expensify/App/blob/c08882192474585888d3cc8a44a73f6fc16d71ea/src/pages/workspace/WorkspaceMembersPage.js#L489-L493

### What changes do you think we should make in order to solve the problem?
When inviting through second contact method, the API `GET /api?command=AddMembersToWorkspace` should return personal details value (as object) and account ID in policyMeembers collection similar to when user is invited through their primary contact method.

Example Response:

```
...,
{
    onyxMethod: "merge",
    key: "policyMembers_2F7B14BEF8B73D2C",
    value: {
      14961964: {},
    },
},
...,
{
    onyxMethod: "merge",
    key: "personalDetailsList",
    value: {
      14961964: {
        accountID: 14961964,
        avatar:
          "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png",
        displayName: "User Main",
        login: "+9779841111111@expensify.sms",
        pronouns: "",
        timezone: {
          automatic: true,
          selected: "Asia/Katmandu",
        },
        firstName: "User",
        lastName: "Main",
        payPalMeAddress: "",
        phoneNumber: "",
        validated: true,
      },
    },
  },
...
```

<details>
  <summary>Sample full response</summary>
  
  ```
{
  "jsonCode": 200,
  "requestID": "7e2b024e0b5e9884-KTM",
  "onyxData": [
    {
      "onyxMethod": "merge",
      "key": "report_7710969573617247",
      "value": {
        "reportID": "7710969573617247",
        "maxSequenceNumber": 10,
        "lastVisibleActionCreated": "2023-07-06 19:46:44.587",
        "lastReadTime": "2023-07-06 19:46:44.587",
        "lastMentionedTime": null,
        "lastMessageText": "added User Main (984-0248444) as a user",
        "lastActorEmail": "photoelectric007+user2@gmail.com",
        "lastActorAccountID": 14961999
      }
    },
    {
      "onyxMethod": "merge",
      "key": "reportActions_7710969573617247",
      "value": {
        "1481106746744550766": {
          "person": [
            {
              "type": "TEXT",
              "style": "strong",
              "text": "User Two"
            }
          ],
          "actorEmail": "photoelectric007+user2@gmail.com",
          "actorAccountID": 14961999,
          "message": [
            {
              "type": "COMMENT",
              "html": "added User Main (984-1111111) as a user",
              "text": "added User Main (984-1111111) as a user",
              "isEdited": false,
              "whisperedTo": [],
              "isDeletedParentAction": false,
              "reactions": []
            }
          ],
          "originalMessage": {
            "accountID": "14961964",
            "email": "+9779841111111@expensify.sms",
            "lastModified": "2023-07-06 19:46:44.587",
            "name": "User Main",
            "role": "user"
          },
          "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_14.png",
          "created": "2023-07-06 19:46:44.587",
          "timestamp": 1688672804,
          "reportActionTimestamp": 1688672804587,
          "automatic": false,
          "actionName": "POLICYCHANGELOG_ADD_EMPLOYEE",
          "shouldShow": true,
          "reportActionID": "1481106746744550766",
          "lastModified": "2023-07-06 19:46:44.587",
          "whisperedTo": [],
          "whisperedToAccountIDs": [],
          "sequenceNumber": 10,
          "isAttachment": false
        }
      },
      "shouldNotify": true
    },
    {
      "onyxMethod": "merge",
      "key": "policyMembers_2F7B14BEF8B73D2C",
      "value": {
        "14961964": {}
      }
    },
    {
      "onyxMethod": "merge",
      "key": "report_4982509216725819",
      "value": {
        "participants": [
          "+9779841111111@expensify.sms",
          "photoelectric007+user2@gmail.com"
        ],
        "participantAccountIDs": [14961999, 14961964]
      }
    },
    {
      "onyxMethod": "merge",
      "key": "report_7710969573617247",
      "value": {
        "participants": ["photoelectric007+user2@gmail.com"],
        "participantAccountIDs": [14961999]
      }
    },
    {
      "onyxMethod": "merge",
      "key": "personalDetailsList",
      "value": {
        "14961964": {
          "accountID": 14961964,
          "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png",
          "displayName": "User Main",
          "login": "+9779841111111@expensify.sms",
          "pronouns": "",
          "timezone": {
            "automatic": true,
            "selected": "Asia/Katmandu"
          },
          "firstName": "User",
          "lastName": "Main",
          "payPalMeAddress": "",
          "phoneNumber": "",
          "validated": true
        }
      }
    },
    {
      "onyxMethod": "mergecollection",
      "key": "report_",
      "value": []
    }
  ]
}

  ```
</details>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by johncschuster** [comment]
Thanks for calling that out, @allroundexperts! I'll apply the `Internal` label.

**Comment by johncschuster** [comment]
Not overdue, Melvin. I just took this one internal.

**Comment by neil-marcellini** [comment]
I'm going to be OOO tomorrow and Friday and I can pick this up when I get back. I'll also post to engineering chat to see if anyone wants to take it over while I'm out.

**Comment by johncschuster** [comment]
Sweet. Thanks for the heads up, @neil-marcellini!

**Comment by johncschuster** [comment]
Nothing new to report, Melvin. We'll be back at this one shortly.

**Comment by neil-marcellini** [comment]
I haven't had time for this yet but I'll bump it up on my list of priorities.

**Comment by neil-marcellini** [comment]
👀 okay I'm diving in!

**Comment by neil-marcellini** [comment]
I have a fix in progress and it seems to work pretty well, but it is a little confusing that when you add a secondary login, the primary login ends up being added. I took a look at how we solve this on OldDot, and we show an informative message.
![image](https://github.com/Expensify/App/assets/26260477/b01db13e-1c54-4db3-8b24-dfdd3e5715e2)

I think it would be good to do something similar for NewDot, but integrate the messages into the UI a bit more. I'll work on a draft and then post in Slack to get feedback and gain consensus on the UX.

**Comment by neil-marcellini** [comment]
Next time I'll work on the front end PR to show the proper messages.

**Comment by neil-marcellini** [comment]
I'm planning to work on this today.

**Comment by johncschuster** [comment]
Thanks, Melv 👍 

@neil-marcellini, it sounds like you've already got this prioritized. Do you need to offload anything to make this your number one? Is there anything I can do to help/keep Melvin happy?

**Comment by neil-marcellini** [comment]
I would love to offload a bunch of stuff but that hasn't been possible for a long time, everyone is too busy.

I fixed a small mistake I had on the backend PR. My plan for the front end is:
Under each user that was added by a secondary login it could say "Added by secondary login neil+secondary@expensifail.com". There will also be a general status message like "Some users were added with their primary logins" displayed just under the find a member input. It will have a dismiss button which will remove that message and all the primary login notes.

**Comment by neil-marcellini** [comment]
I asked for some [feedback on the plan here](https://expensify.slack.com/archives/C03U7DCU4/p1690329052055139), and design review, before I dig in to the front end changes.

**Comment by neil-marcellini** [comment]
People are[ happy with the plan](https://expensify.slack.com/archives/C03U7DCU4/p1690384693853529?thread_ts=1690329052.055139&cid=C03U7DCU4) so I'm going to implement the front end PR now.

**Comment by neil-marcellini** [comment]
Next time I will clean up the code on the front end and prepare the PRs for review. I've already asked Shawn for some design feedback.

**Comment by neil-marcellini** [comment]
Heads up, I'm going to be OOO Monday and Tuesday next week. I'll ask in Slack if anyone can take over these issues while I'm out.

**Comment by johncschuster** [comment]
Bumping for Melvin.

**Comment by neil-marcellini** [comment]
Thank you for appeasing the relentless Melvin. I'm working on this now 👀.

**Comment by neil-marcellini** [comment]
Ok I got the backend PR up for review, and I'll put the front end PR up as soon as the backend PR is on staging.

**Comment by neil-marcellini** [comment]
Backend PR is on staging, putting the front end PR up for review.

**Comment by johncschuster** [comment]
How's this one going, @neil-marcellini?

**Comment by johncschuster** [comment]
Bumping to keep Melvin happy

**Comment by johncschuster** [comment]
How's the front end PR going, @neil-marcellini?

**Comment by neil-marcellini** [comment]
Wow I totally forgot about this. Please bump me again. I'm going to remove the reviewing label and put the PR into a draft state so that I don't forget again.

**Comment by neil-marcellini** [comment]
I made a little bit of progress on this one today.

**Comment by neil-marcellini** [comment]
I made some more progress this and yesterday morning. I think I can get it up for another round of review tomorrow.

**Comment by neil-marcellini** [comment]
May I please have a design review of the PR [Show info about workspace members added by secondary logins](https://github.com/Expensify/App/pull/23702#top)?

**Comment by dubielzyk-expensify** [comment]
It looks very similar to the initial intended one that @shawnborton gave a 👍 for, so it looks good to me.

**Comment by johncschuster** [comment]
# Payment Summary:

External issue reporter: @daveSeife - $250 - will be paid via Upwork (through [this issue](https://github.com/Expensify/App/issues/31157))
Contributor+ that helped on the issue and/or PR: @allroundexperts - $1000 - Eligible for Manual Requests

**Comment by johncschuster** [comment]
@allroundexperts / @neil-marcellini, do you feel we will need regression test steps for this?

**Comment by neil-marcellini** [comment]
> @allroundexperts / @neil-marcellini, do you feel we will need regression test steps for this?

No I don't think we should bother since it's quite an edge case.

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/21639#issuecomment-1804621170).
