### ISSUE TITLE
Offline Mode: Active 'verify' button on offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings then profile
2. Go to the contact method
3. Click New Contact Method then enter a new contact
4. Click the new account you entered to verify
5. now Be Offline
6. Notice that the Verify button is active
## Expected Result: 
On offline mode Verify button should not be active
## Actual Result: 
On offline mode Verify button is active

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** unable to reproduce by applause
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c134f044-e3b2-4ee5-8535-cfd851cfd48a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687380769632719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
@Beamanator @cristipaval is this one also intentional or is this a bug?

**Comment by Beamanator** [comment]
IIRC this was also intentional, yes - because we thought it was very likely that the user correctly entered the magic code so we would optimistically assume it was entered correctly

**Comment by laurenreidexpensify** [comment]
Okay, so is this one we should confirm is in TestRail or close out?

**Comment by Beamanator** [comment]
Yes please, I think we should also confirm this is in TestRail before closing 🙏

**Comment by laurenreidexpensify** [comment]
Done!
