### ISSUE TITLE
Web - Chat - Bot reply thread lags and messages are shown out of sequence for a while

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send any message in chat with a bot
2. Create a thread from the bot reply and send another message in the thread
3. The message lags. Now send more messages. The latest message is displayed above the pervious message

## Expected Result:
Messages should be quick to display and latest messages should be at the end

## Actual Result:
Initial message takes a lot of time to be displayed and consequent messages are not displayed in sequence

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/62f3e672-8600-42db-83aa-2859d6dfd42d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MohsinAliTanvir
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686762180109169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is not testing anything related to Concierge on both NewDot and OldDot, putting Need reproduction label.

**Comment by sakluger** [comment]
I can't reproduce, asking in the Slack thread.

**Comment by sakluger** [comment]
I still can't reproduce this.

**Comment by sakluger** [comment]
Asked for more details in the Slack thread.

**Comment by sakluger** [comment]
Not reproduceable anymore by the reporter.
