### ISSUE TITLE
Slack #expensify-bugs improvement - Automate GH issue creation for BUG: reports 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#21652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# Problem
For creating a github issue from a slack bug report, Applause has to copy paste from slack to github. This is a repetitive task and we get 10-100 bug reports daily.
With the new [bug report workflow](https://expensify.slack.com/archives/C049HHMV9SM/p1684873862097049) we have bugs in a standard format.

# Feature request
Applause should be able to create a github issue with one command by replying to a bug report workflow.
It should also add a link of the created feature.

___
This was discussed in this thread - https://expensify.slack.com/archives/C01GTK53T8Q/p1684875256446039

Having this automation implemented will greatly help Applause keep up with the amount of BUG: reports raised on a daily basis (>60) and let them focus more on reproduction attempts and bug report quality.

**Comment by yuwenmemon** [comment]
This is a good FirstPick for anyone interested in working on some automation code.

**Comment by AndrewGable** [comment]
Why just internal @yuwenmemon ?

**Comment by yuwenmemon** [comment]
I presume this would require a Slack webhook and that would exist in PHP, right?

**Comment by AndrewGable** [comment]
Do we have a Slack webhook in PHP currently? I couldn't find an example. I guess it will have to run somewhere, which will be our webservers and that will make it internal.

**Comment by yuwenmemon** [comment]
We don't have one currently from what I can tell.

**Comment by m-rafey-qbatch** [comment]
> This is a good FirstPick for anyone interested in working on some automation code.

"Hi, I noticed that this is the FirstPick issue. I'm new to the repository, but perhaps I can offer some assistance?"

**Comment by m-rafey-qbatch** [comment]
Contributor details
Your Expensify account email:m.rafey659@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/rafey
