### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Compose box loses focus on coming back from 'Hmm... its not here' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Copy report URL and paste in compose box
4. Add few numbers to it to make it invalid and send
5. Click on the link, it should open 'Hmm...it's not here' page
6. Click on back to observe that app does not focus back on compose box

## Expected Result:
App should focus back on compose box on revisit of report

## Actual Result:
App does not focus on compose box on coming back from 'Hmm... it's not here' page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4494d76d-9f1d-42fc-b819-9e80db7e4d20

https://github.com/Expensify/App/assets/93399543/ae31f9bc-8120-4c02-a684-b2826cd4a38a

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687509816386599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014471479f4d4b1b97</li>
        <li>Upwork Job ID: 1673840903296954368</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Yep, I can replicate on v.32-5. It'd be good to focus back on the Compose box!

**Comment by narefyev91** [comment]
@ginsuma Nice! I like alternative solution!
🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Invited @dhanashree-sawant for reporting bonus.

@ginsuma and @narefyev91 - what are your Upworks profiles? It would also help if you both put your actual names (in Upworks) in GH, so we can easily find you in the future. Thanks!

**Comment by dhanashree-sawant** [comment]
Hi @jliexpensify, Invite accepted. Thank you!

**Comment by narefyev91** [comment]
> Invited @dhanashree-sawant for reporting bonus.
> 
> @ginsuma and @narefyev91 - what are your Upworks profiles? It would also help if you both put your actual names (in Upworks) in GH, so we can easily find you in the future. Thanks!

Hey @jliexpensify ! I'm from Callstack - no needs to make any payments in Upwork 👍

**Comment by jliexpensify** [comment]
@ginsuma what's your Upworks profile?

**Comment by jliexpensify** [comment]
@ginsuma I have hired you, but please:

1. Take your profile off Private 
2. Add your Upworks name to your GH handle (so we can find you in the future)

Thanks!

**Comment by jliexpensify** [comment]
@narefyev91 - could you complete the checklist please? Thanks!

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was not a regression - mostly code improvement for peace that was not predicted
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - no actions needed

**Comment by jliexpensify** [comment]
Nice ty - going to pay out now + the bonus.

**Comment by jliexpensify** [comment]
Just waiting on @dhanashree-sawant and @ginsuma to accept, then will pay + close job.

**Comment by jliexpensify** [comment]
All paid! Job closed! Thanks everyone!
