### ISSUE TITLE
[HOLD for payment 2024-01-17] [Hold for payment] Add ES-Lint Rules for Color Styles / using Theme Providers

### ISSUE THREAD

**Issue by grgia** [Expensify/App#21671]
https://docs.google.com/document/d/1KwVVu5-DLjmb-2-UwgIw5ElmyKn0ZXs8wUzxcNZjwDc/edit#bookmark=id.b5oz5n587wsb

Prevent these imports and use hooks instead:
``` js
import styles from '@styles/styles';
import themeColors from '@styles/themes/default';
import themeColors from '@styles/themes/light';
import * as StyleUtils from '@styles/StyleUtils';
```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162586586f7d4d344</li>
        <li>Upwork Job ID: 1744829246659751936</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
^

**Comment by grgia** [comment]
@joekaufmanexpensify I just need help to confirm @situchan receives $500 C+ review for https://github.com/Expensify/App/pull/32569

**Comment by joekaufmanexpensify** [comment]
Sounds good! I'll track the PR and pay them after the 7 day regression period

**Comment by joekaufmanexpensify** [comment]
@situchan offer sent for $500

**Comment by joekaufmanexpensify** [comment]
@situchan does this need a regression test? My thinking is probably no, but LMK if you disagree.

**Comment by situchan** [comment]
No need regression test

**Comment by joekaufmanexpensify** [comment]
Cool cool. TY! I will issue payment on the 17th.

**Comment by joekaufmanexpensify** [comment]
@situchan $500 sent and contract ended.

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set!
