### ISSUE TITLE
[HOLD] Web - Canceled task position changed on revisit task thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on + icon
2. select  Assign task option
3. enter and click on next button
4. click on Assignee and select Assignee
5. click on confirm task button
6. go to task thread
7. click on three dots and choose cancel option
8. go to other chat
9. revisit task thread and check canceled task message

## Expected Result:
canceled task message position should not change

## Actual Result:
canceled task message position changes in report screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.31-2 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4ac836e3-9235-4574-8e16-5ffeca60b8e5

https://github.com/Expensify/App/assets/93399543/fa74346e-f87f-4635-abee-45f2ca651fcd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687505952678609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Checking in the linked GH whether this will be fixed with upcoming changes.

**Comment by sophiepintoraetz** [comment]
New changes will remove this bug so holding till https://github.com/Expensify/App/issues/19504#issuecomment-1613802773 goes live!

**Comment by sophiepintoraetz** [comment]
Still holding.

**Comment by sophiepintoraetz** [comment]
Still holding.

**Comment by sophiepintoraetz** [comment]
Still holding.

**Comment by sophiepintoraetz** [comment]
Draft PRs are up.

**Comment by sophiepintoraetz** [comment]
Still reviewing.

**Comment by sophiepintoraetz** [comment]
Stll in review

**Comment by sophiepintoraetz** [comment]
Still in review.

**Comment by sophiepintoraetz** [comment]
Still holding.

**Comment by sophiepintoraetz** [comment]
Still in review

**Comment by sophiepintoraetz** [comment]
Looks like the solution in https://github.com/Expensify/App/issues/19504#issuecomment-1613802773 has gone live so will review this on Monday.

**Comment by sophiepintoraetz** [comment]
@gadhiyamanan are you able to confirm whether you encounter this bug still?

**Comment by sophiepintoraetz** [comment]
Offer sent.
