### ISSUE TITLE
Web – Share code – Padding is not consistent in the section.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21672]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the "Settings" section.
2. Click on the " Share code " option.
3. Notice the inconsistent padding, the "copy URL" icon is positioned more towards the left and is not aligned with the barcode.

## Expected Result:
The padding should be consistent throughout the section.

## Actual Result:
The padding is not consistent throughout the section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-0 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Bug (2)](https://github.com/Expensify/App/assets/93399543/283c3eac-a0f8-44ec-8bba-aad3c1189431)

https://github.com/Expensify/App/assets/93399543/a5f76ada-1f15-4c61-a778-4fb4720cfb13

![photo_2023-06-26_16-57-33](https://github.com/Expensify/App/assets/93399543/f671782c-7a7b-47a9-9ce8-a9439cb9881b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687494466817389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
This is not a bug, this is all working as expected.
