### ISSUE TITLE
Chat-Unable to expand/hide compose box with selected text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Open any chat
3. Enter several lines of text until a button to expand the compose box is visible
4. Highlight text
5. Tap on the button to expand the compose box

## Expected Result:
The user can immediately expand/hide the compose box

## Actual Result:
If text in the compose box is selected, then you can expand/hide the compose box only by pressing the button several times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9defe48a-26c7-4cfb-b0c0-d8e7c3c2a3d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, I just tried this on iOS safari and I'm not able to reproduce it. @lanitochka17 are you able to consistently reproduce? If so, please reopen!
