### ISSUE TITLE
Flagged harassment or assault words show up on LHN after user deletes a posted comment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Flag the comment from account B as Harassment or Assault
3. Observe the word is removed
4. Post a comment from account B
5. Delete the last comment

## Expected Result:
The flagged word should not show up on LHN

## Actual Result:
The flagged word shows up on LHN

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a67cdf79-96d3-4787-86cb-575a5396da67

**Expensify/Expensify Issue URL:**
**Issue reported by:**@Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686944316380929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
asking about this here - https://expensify.slack.com/archives/C049HHMV9SM/p1687977137340509?thread_ts=1686944316.380929&cid=C049HHMV9SM

**Comment by maddylewis** [comment]
it sounds like this was already reported / it's expected behavior https://github.com/Expensify/App/issues/21413#issuecomment-1608149574
