### ISSUE TITLE
Whispers are sent to my email even though they are not intended for me

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21681]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Whispers are sent to my email even though they are not intended for me
## Expected Result: 
I shouldn't receive any Whispers which are not intended for me
## Actual Result: 
Whispers are sent to my email even though they are not intended for me
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-22 at 03 05 31](https://github.com/Expensify/App/assets/43996225/88b815ca-3fb3-4ef5-8602-1f6fa9bd5d9d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687378120907909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ae62f36597077cf</li>
        <li>Upwork Job ID: 1675810934080004096</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment]
This system email was sent to me **randomly** when I am in SNH chat room - even though I didn’t interact with the users mentioned in the email. so I don’t know **when and how it happens**, this email is all I could see.
I asked the team about this first, and David confirmed that it wasn’t expected and asked me to report it. So I can’t provide it with a video

**Comment by bfitzexpensify** [comment]
Hm, I don't know how to attempt to reproduce this. I wonder if we have logs we can look at to find these messages and determine what triggered them to be sent to @tranvantoan-qn. Going to tag engineering to take a look.

@tranvantoan-qn, what is the email address of the Expensify account where you received these whispers?

**Comment by tylerkaraszewski** [comment]
@bfitzexpensify - I am leaving today on sabbatical. Can you please remove and re-apply the `Engineering` label to select a new engineer to finish this issue? Thanks!

**Comment by danieldoglas** [comment]
I've created an internal issue for this since this is related to our API, will put this in hold until that one is finished.

**Comment by pecanoro** [comment]
@danieldoglas DId you manage to reproduce this?

**Comment by pecanoro** [comment]
So we can reproduce this:

![image](https://github.com/Expensify/Expensify/assets/6474442/9a170be3-5ef4-4733-ad2d-954eceac65cf)

![image](https://github.com/Expensify/Expensify/assets/6474442/6aeb7289-5f3a-4076-a733-e40c71343c70)

**Comment by tranvantoan-qn** [comment]
@pecanoro 
It's really hard to reproduce this issue as It happened randomly even though I didn't interact with the room I participated in.

But it looks like it still happens somewhere. I've just seen similar behaviour this morning (_when I was access to a public room as Anonymous user and then login_), the system sent a message for someone but the message say `Only visible to {someone else}`

![image](https://github.com/Expensify/App/assets/10254571/be3accc2-87df-4d29-8aaa-8dcf984a5444)

**Comment by pecanoro** [comment]
@tranvantoan-qn That was probably your anonymous login before you log in with a real account and got cached in Onyx somehow. Does it happen every time you go from anonymous to a created account?

**Comment by danieldoglas** [comment]
@pecanoro is doing the investigation here, so I'm unassigning myself

**Comment by pecanoro** [comment]
> The latest issue I found may be related to Onyx but the original issue here must somehow happen from the backend side - because emails can be sent by backend only

I am sorry, can you elaborate? I am not following what you mean.

**Comment by tranvantoan-qn** [comment]
@pecanoro 
I mean [this one](https://github.com/Expensify/App/issues/21681#issuecomment-1630943193) may be related to Onyx - so clean Onyx cache may help

But **[this one](https://github.com/Expensify/App/issues/21681#issue-1776827416)** (the original report) is handled by the backend - so there is no way for me to check it

**Comment by pecanoro** [comment]
I was looking at the email problem and I was wondering if are grabbing the messages for the email from concierge perspective or something weird like that. Definitely a back-end error but I can't reliably reproduce it.

**Comment by tranvantoan-qn** [comment]
@pecanoro 

I've checked the phrase 'Here's what you missed' in the email content again, and I thought about this scenario:

1. **Account A** joined a chat room (then closed/ left the app).
2. Then **Account B and Account C** also joined; they will get the message which says, `Hi there! If you want to lurk... in this room...`
3. There is a scheduled job at the backend that will send a summary of the messages in the room that **Account A** missed, and we are not excluding the Whispers from that message.

For **# 3**, We are not sure how often this job (if it exists) is scheduled, so perhaps we need help from the Backend team to verify it. Additionally, we can review the logic of generating that email to determine if it's the case

**Comment by pecanoro** [comment]
I will check the back-end to see if this is related to the last read market

**Comment by tranvantoan-qn** [comment]
It looks like someone from **callstack** team is checking something. I got that again
![image](https://github.com/Expensify/App/assets/10254571/b7681dc5-2dd0-4d97-9dab-29f91f72be4a)

**Comment by pecanoro** [comment]
Found the bug, it was due to caching. Created an internal PR to fix it.

**Comment by pecanoro** [comment]
@bfitzexpensify This has been fixed, can you pay @tranvantoan-qn the reporting bonus?

**Comment by bfitzexpensify** [comment]
Sure thing - offer sent @tranvantoan-qn

**Comment by bfitzexpensify** [comment]
OK, all paid out, so we're all done here!
