### ISSUE TITLE
Chat - Mentions of phone numbers that don't have accounts are rendered as plain text and not mentions.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Open a chat and create a new chat with a random number like `+91 9999 8888 33`.
3. Mention the user in any chat using @ symbol.
4. Notice that mention is shown as simple text in chat.

## Expected Result:
Mentions should be shown as mention whether the phone number has an account or not.

## Actual Result:
Phone number mentions are shown as text message if they don't have an account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c559879a-44e9-481a-baf3-21cf6f1510a5

https://github.com/Expensify/App/assets/93399543/238ef14d-088f-4935-8ffa-f5319bdc09c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687512980767079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
I think the second video attached is for a different issue but the first video is correct and shows the issue. 

For emails, mentions are rendered correctly even if account doesn't exist (see 1@2.com in video) but for phone numbers the same doesn't happen.

**Comment by Nikhil-Vats** [comment]
This can be closed based on [this comment](https://github.com/Expensify/App/issues/21790#issuecomment-1612146082). It is a known issue and will be fixed in next iteration.

**Comment by flaviadefaria** [comment]
Good catch @Nikhil-Vats - closing this!
