### ISSUE TITLE
[$1000] mweb - Clicking browser/system back button takes user to the wrong page in 2FA page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND on mWeb
2. Go to settings > security > two factor authentication
3. Copy the code and click next
4. Go offline
5. Click on the back button on top left corner twice to take you to security page
6. Go online
7. Click on two factor authentication
8. Click on system/browser back button

## Expected Result:
App should take user back to the security page

## Actual Result:
App takes user to the step two "two factor authentication"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5fb8f51a-9b5e-4b3d-afa6-8d942f149fef

https://github.com/Expensify/App/assets/93399543/c0d9b38f-0371-4649-82d2-522525ccf491

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687522558210329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bb7da3c3eeb9e97</li>
        <li>Upwork Job ID: 1673772690341146624</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I was able to reproduce the bug both by going offline and without going offline. I'm not sure that step is necessary here.

**Comment by daordonez11** [comment]
Hmmm @WoLewicki I tried to see the code but in terms of navigation everything seems to be working as expected `goBack ` is called as expected and `navigate `called right as well. From my point of view it might be a border scenario of React Navigation and how it handles window.history.
PS: Third time I try to check navigation issue, I might have to desist the topic 😂

**Comment by b4s36t4** [comment]
I see there were few issues with react-navigation and browser's behaviour. have few doubts and need some discussion any help?

**Comment by WoLewicki** [comment]
Does this 2FA flow use `react-navigation` navigation and changes in the URL? Or is it the same as `Request Money` flow was before? If so, it probably is the same issue as https://github.com/Expensify/App/issues/21218, but if not, we would have to dig deeper since probably there is some other bug causing it.

Can we also confirm it only happens on iOS web? Isn't it the same on web with browser back button @kbecciv ?

**Comment by daordonez11** [comment]
Hey @WoLewicki  I can confirm it happens in web as well. This now is not like `Request Money` in this flow `Navigation.navigate` is indeed used. I can confirm it is not the same issue here there is no custom navigation.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by b4s36t4** [comment]
I can't re-produce it again. Maybe fixed?!
