### ISSUE TITLE
Android - Chat - The image preview in the conversation after the upload is zoomed and partially displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On a conversation, click on the + button in the compose box
2. Click on add attachment
3. Upload an image (jpeg or png)
4. Verify a preview of the image is displayed before uploading to the conversation
5. Click on upload
6. Verify the image immediately starts uploading and a black “Uploading Attachment…” text is displayed briefly
7. Verify you can see the image preview in the conversation after the upload is finished

## Expected Result:
The image preview in the conversation is displayed correctlly

## Actual Result:
The image preview in the conversation after the upload is zoomed and partially displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9113dff9-c6b9-47f3-9e13-dd6f0f72cbb1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
Working on reproducing now

**Comment by johncschuster** [comment]
Not reproducible on v 1.3.38-3

**Comment by johncschuster** [comment]
I can't reproduce this on 1.3.33-3 on browserstack.

**Comment by johncschuster** [comment]
@lanitochka17 can you clarify the reproduction steps? Are you able to consistently reproduce this behavior, or are some images showing up non-zoomed?

**Comment by lanitochka17** [comment]
Issue is not reproducible with Build 1.3.38.3

https://github.com/Expensify/App/assets/78819774/df742a90-8749-43fc-a823-be552cbd1bdb
