### ISSUE TITLE
Web - App shows the previous history on the URL after user clicks on browser back button on sign in page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to sign in page on ND
2. Enter an email and go to the magic code page
3. Click on the browser back button

## Expected Result:
App should take user back to the first sign in page/ email page

## Actual Result:
App doesn't do anything except showing the previous history of the user on the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c6993c56-67c0-4743-a4b0-5e087ed9cb80

https://github.com/Expensify/App/assets/93399543/e66d18be-f416-41d3-a217-eb600c5a7ef2

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687532036876489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Can't reproduce this one.

**Comment by Nathan-Mulugeta** [comment]
Can you share a video please, it might help. @muttmuure
