### ISSUE TITLE
 Login - Unable to log in with special High Traffic Expensifail account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Enter the [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)
in input field
3. Press `Continue`

## Expected Result:
Unable to log in with [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)
account, magic code doesn't come

## Actual Result:
Magic code comes and possible to login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/665b7626-0661-40de-9b59-b36446c6e71b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I cleared the Magic Link throttle for that account and IP address. Can you try logging in again with that email?
