### ISSUE TITLE
Task - Back button doesn't close the RHN when selecting assignee from task report header

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Create a task if you don't have a task report else open an already existing task report.
3. Click on assignee. Select assignee modal should open in RHN.
4. Click on back button. Confirm task step is opened instead of closing the RHN.
6. Click on back button again. Task Title and description step is opened.
7. Click on back button, RHN closes now.

## Expected Result:
RHN should close on clicking of back button, it should not navigate to previous steps of assign task journey.

## Actual Result:
RHN is not closed instead user is navigated back to confirm task step of assign task journey.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a7ecf122-60f5-4680-a76f-cd8ec10d1c61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687535283771889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
#21626 reports the same issue but the expectation in the bug report is wrong.

**Comment by s-alves10** [comment]
We should select one of [21626 ](https://github.com/Expensify/App/issues/21626) and this issue, I think. 26126 assumes this issue isn't a bug

**Comment by abekkala** [comment]
If this was already reported via 21626 first then this one can be closed as a dupe and discussion can continue on the one that was reported first.
