### ISSUE TITLE
Web -  Contact information of a new User is seen when requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB
2. Request Money
3. enter amount and click next
4. Now search and choose a new User with no chat history
5. send a request
6. Notice that a chat is created with Concierge saying "This is your first time chatting with this user. Make sure you know this person before you respond. Once you respond, they will be able to see your contact information"
7. now Click on the new User and notice that you can see the Contact information of the New user.

## Expected Result:
 Contact info is hidden

## Actual Result:
Contact info is not hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5872f3fd-c88b-4f2a-833f-dc2a0ab388b6

https://github.com/Expensify/App/assets/93399543/0cfaf662-f525-4ddd-862f-6a8f63755def

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687542559168179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
You entered their email address to send the request, it makes sense that you can see THEIR contact info.

The error says `Once you respond, THEY will be able to see YOUR contact information`. It doesn't say anything about YOU seeing THEIR info

Not a bug
