### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Error message  displayed when User flags a message with no permission in a group chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21719]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA account
2. Go to the “New room” section
3. Enter room name and select userA workspace
4. Select visibility to “Public”
5. Click on “Create room”
6. Send some messages in room chat
7. Go to the room detail
8. Share code > Copy URL to clipboard
9. Go back and click on Settings > Who can post
10. Select Admin only
11. Open other browser and login with userB account
12. Join the room by pasting URL
13 Now click on “flag as offensive”
14. Click on any option
## Expected Result: 
Error message "Auth CreateReportAction returned an error" displayed when UserB flags a message without posting permission in a group chat
## Actual Result: 
The error message "Auth CreateReportAction returned an error" is displayed when UserB flags a message without having permission to post in the group chat
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/61796d4e-a815-4b87-bfd7-246d7d723978

https://github.com/Expensify/App/assets/43996225/f2fc7f63-5cd8-4d23-88c5-892723d71d94

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687621449744259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129a94963f8137bb5</li>
        <li>Upwork Job ID: 1674063676186324992</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
I am OOO! Adding another BZ member for the week.

**Comment by twisterdotcom** [comment]
[Assigned Jul 3, 11:25am](https://github.com/Expensify/App/issues/21719#event-9707216213)
[Merged Jul 4, 12:55pm](https://github.com/Expensify/App/pull/22099#event-9721018024)

Why was there no celebratory this was done within 3 days comment?

**Comment by ayazhussain79** [comment]
@twisterdotcom Offer accepted, Thank you

**Comment by twisterdotcom** [comment]
@allroundexperts is paid via Expensify: https://github.com/Expensify/Web-Expensify/blob/1d8ad948bc605c2c5c5d5b1d72028e2e41bbaf35/_devportal/lib/KernelScheduling/Data.php#L242

@ayazhussain79 paid here: https://www.upwork.com/en-gb/nx/wm/pre-hire/c/8577561/offer/25535486

@hungvu193 paid here: https://www.upwork.com/en-gb/nx/wm/workroom/34086179/overview

**Comment by anmurali** [comment]
@allroundexperts is paid
