### ISSUE TITLE
[Mobile] There is no way to exit Add Bank Account page when the pop-up is loading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDTION: Network connect may need to be slow, so app takes long time to connect to Plaid
1. Go to Payment setting > Add Payment Method
2. Select Bank Account

## Expected Result: 
While the content is loading users should be able to exit Add Bank Account page/ popup (whether by adding the X button or minimize the popup.)
## Actual Result: 
There is no way to exit Add Bank Account page when the page/pop-up is loading

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/788c3cda-cd02-4677-a555-b087fc905798

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687623883584849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
There is a small delay with Plaid loading (even in good connection) but I don't know if this is worth fixing now as I think it would be a feature request - asking the team - https://expensify.slack.com/archives/C01SKUP7QR0/p1687906374015349

**Comment by Christinadobrzyn** [comment]
Talking this over with the team - this is a feature request. 

@tranvantoan-qn if you feel passionate about this update, feel free to repost it as a feature request following the steps in either of these GHs. 

1. https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs
2. https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_CREATE_A_PLAN.md
