### ISSUE TITLE
[$1000] Carousel scrolling arrows move up an down on pdf password protected attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21367
1. Login to NewDot
2. Open chat
3. Tap password protected pdf
4. Tap enter password
5. Tap outside the field to scroll attachments

## Expected Result:
Carousel scrolling arrows should stay on the same place

## Actual Result:

Carousel scrolling arrows move up an down on pdf password protected attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dee0b977-3170-4011-a59a-3e9aef246e2a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01866c34d89d477b1e</li>
        <li>Upwork Job ID: 1678914033144700928</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Unable to reproduce, @lanitochka17 , can you try again to see if you can?


https://github.com/Expensify/App/assets/22508304/2ade4dab-5140-4092-b357-9edc6ba1e63f

**Comment by lanitochka17** [comment]
@mallenexpensify Issue reproducible in mWeb/Chrome.

https://github.com/Expensify/App/assets/78819774/b5643fdb-90fd-439c-8a9a-c27afefe092e

Sorry for confusion.

**Comment by mallenexpensify** [comment]
Unable to reproduce on iOS/Chrome

https://github.com/Expensify/App/assets/22508304/2531a5db-69a6-4ec8-8607-9d4dc6d4cf52


Also unable to reproduce on iOS/Safari


https://github.com/Expensify/App/assets/22508304/aa2a22a8-bacd-46ac-9a35-2d4cc39b86a8

@lanitochka17 , any idea what I might be doing that's not allowing me to reproduce?

**Comment by lanitochka17** [comment]
@mallenexpensify Reproducible in Android/Chrome

**Comment by mallenexpensify** [comment]
D'oh, I just tried in Android on the native app and wasn't able to reproduce, back to try Android/Chrome. 

Was able to reproduce, for me the arrow started higher then immediately dropped back down to the 'normal' area it was supposed to. Seems like this can be external

**Comment by mallenexpensify** [comment]
> I think this is just due to a delay in updating the arrow position when the keyboard gets hidden

Thanks @parasharrajat , this makes me wonder if there are other similar instances in the app.   If so, we could fix potentially fix them at once.  It is weird that it's inconsistent but that _could_ be for a platform/browser I'm unaware of

**Comment by mallenexpensify** [comment]
I think the inconsistency has to do with the browser and not on our end.  And, it's just a slight difference in the timing before the arrow drops, so I'm going to close.  Comment if you disagree.
