### ISSUE TITLE
Chat - Plus sign on composer overflows the container

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21736]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Tap on sign plus and tap request money
2. Fill in amount and tap next
3. Invite a new member
4. Tap on request money
5. On new chat tap to open the reply message
6. Open cash
7. Add 3 empty lines by hitting enter
8. Notice that resize arrows show up
9. Tap on it multiple times

## Expected Result:
Plus sign moves around and is not static

## Actual Result:
Plus sign shouldn't move

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b0f0428-245d-40bf-97a3-f3dc704306f8

https://github.com/Expensify/App/assets/93399543/693eac97-6f95-454b-bf80-6902e8e52650

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687578482681579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I will get to this tomorrow

**Comment by muttmuure** [comment]
Looks like this is cross platform

**Comment by muttmuure** [comment]
can't reproduce this one
