### ISSUE TITLE
[HOLD 20844 19330]Mark as done button is partially or completely hidden when using long names

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to ND
2. Click on FAB > Assign task
3. Enter details and click on Next
4. Choose a user with a very long name as Assignee > Confirm task

## Expected Result: 
Mark as done button is partially or completely hidden
## Actual Result :
 It's not hidden

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ec2e3bd6-45e7-4af6-bb16-56aaefcf4946

<img src="https://github.com/Expensify/App/assets/43996225/885147b1-9adc-4150-be1f-bd3c95b815d8" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684402411646989
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
Task headers are getting updated in #20844 so I think this can be put on hold.
cc @thienlnam

**Comment by thienlnam** [comment]
Yeah thank ya - this is a known issue, and will be resolved once 
https://github.com/Expensify/App/issues/20844 and https://github.com/Expensify/App/issues/19330 are done

**Comment by abekkala** [comment]
@thienlnam if this was a known issue with two previous reports and a fix in place can't this just be closed as a dupe vs. being put on hold?

**Comment by thienlnam** [comment]
I keep seeing this same bug pop up after closing them, so keeping it open so that we don't continue to re-create this bug until we solve it

**Comment by abekkala** [comment]
@sonialiap Reassigning for sabbatical
___
### CURRENT STATUS:

This is on HOLD and no action has been taken yet. 
known issue and will be resolved once
https://github.com/Expensify/App/issues/20844 and https://github.com/Expensify/App/issues/19330 are done

**Comment by sonialiap** [comment]
On hold

**Comment by sonialiap** [comment]
I'm going to move this to Weekly since it doesn't look like those two issues are near completion

**Comment by sonialiap** [comment]
still on hold

**Comment by Nikhil-Vats** [comment]
@sonialiap the PR for the other issues were merged. This should be resolved now.
