### ISSUE TITLE
[HOLD 20841]First email is hidden using @ in the IOU thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat where money has been requested
2. Open keyboard and type @
3. When the mention list appears notice that the first account in the mention list is hidden

## Expected Result: 
First Account in mention list should be fully visible and clickable
## Actual Result: 
First Account  in mention list is hidden

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/97d7e31e-1889-48f0-83f5-a1418896c388

https://github.com/Expensify/App/assets/43996225/5c4390f7-2f1c-48fc-8b28-dd9eb34f209f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687599671927339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
This issue happens because the header height is more in case of IOU reports and mention suggestions don't account for that.

The header for IOU reports (among other reports) will be updated in #20844 and the height of header will be reduced to be same as normal chat header's height. Thus, this issue should be fixed then.

**Comment by thienlnam** [comment]
Thanks - yes the task and money request views are being updated (task update here https://github.com/Expensify/App/pull/20841) and will resolve this

**Comment by sophiepintoraetz** [comment]
Still holding

**Comment by thienlnam** [comment]
Linked PR was merged!

**Comment by sophiepintoraetz** [comment]
[Asking the ](https://expensify.slack.com/archives/C049HHMV9SM/p1689321297634939?thread_ts=1687599671.927339&cid=C049HHMV9SM)reporter to double-check.

**Comment by SofoniasN** [comment]
@sophiepintoraetz Hey there, i have commented on the GH issue and it all seems good.

**Comment by SofoniasN** [comment]
@sophiepintoraetz a humble reminder

**Comment by sophiepintoraetz** [comment]
Offer sent, @SofoniasN !

**Comment by SofoniasN** [comment]
@sophiepintoraetz offer accepted!
