### ISSUE TITLE
"Hmm.. it's not here ..." message shows on click of back button after removing contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21742]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings >Profile >Contact methods
2. click on New Contact method
3. add any email and click on Add button
4. click on that mail from Contact methods list
5. reload the app
6. click on remove button
7. click on back button from Contact methods page
## Expected Result: 
should navigates to Profile page
## Actual Result: 
"Hmm.. it's not here ..." message shows on click of back button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ac02bd1b-9f86-4fe3-a4a5-85a3ca0ae05e

https://github.com/Expensify/App/assets/43996225/f20be02f-3d47-401e-b507-051224e516f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687589075880139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
https://github.com/Expensify/App/assets/14225673/1794e36c-06c1-4bef-be40-2842cc0d0ee3

Cannot reproduce on staging on Mac/Chrome

**Comment by gadhiyamanan** [comment]
@anmurali you need to reaload the app on  on enter magic code page not the contact method list page
