### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Spanish character to room name shows the invalid name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App, Press FAB > New room
2. Add Spanish character to the Room name (e.g. cueva-de-opinión)

## Expected Result: 
We should not get the error of invalid Room name and the Spanish character should be a valid name
## Actual Result: 
Adding a Spanish character shows the error of an invalid room name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8c71790f-4fef-488f-9e78-86e7199cef24

https://github.com/Expensify/App/assets/43996225/46037323-60f2-4df2-aa3a-1e5eac96cae5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687765941593149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01082e3b04cd3dad37</li>
        <li>Upwork Job ID: 1674121959020658688</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
from @jayeshmangwani 

### Please re-state the problem that we are trying to solve in this issue.
Spanish character to room name shows the invalid name.

### What is the root cause of that problem?
Here on the RoomNamePage page, we check the validity of the room name from the isValidRoomName function and

https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/pages/settings/Report/RoomNamePage.js#L52-L54

https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/libs/ValidationUtils.js#L424-L426


isValidRoomName check the valid room name with this regex;

https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/CONST.js#L1135

above regex check the English character from a to z, but it does not allow Spanish character like `é`


### What changes do you think we should make in order to solve the problem?
We have to update the regex here like that it can accept all the valid Spanish characters; we need to add the new range for taking the Spanish characters `à-ÿ` to ROOM_NAME regex.

https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/CONST.js#L1135

```javascript
    ROOM_NAME: /^#[a-z0-9-]{1,80}$/,
    ROOM_NAME: /^#[a-z0-9à-ÿ-]{1,80}$/,
```

### What alternative solutions did you explore? (Optional)
Rather than adding the whole range of the alphabet, we can add only missing Spanish characters to the regex.

https://github.com/Expensify/App/blob/ae8a751c04cd4b371bec1d976da204413b6bb4b9/src/CONST.js#L1135

```javascript
    ROOM_NAME: /^#[a-z0-9-]{1,80}$/,
    ROOM_NAME: /^#[a-z0-9-ñáéíóúü]{1,80}$/,
```

**Comment by laurenreidexpensify** [comment]
@0xmiroslav do any of the proposals above look good?

**Comment by laurenreidexpensify** [comment]
@0xmiroslav bump^^

**Comment by jayeshmangwani** [comment]
@0xmiroslav Do you have any feedback for my [Proposal](https://github.com/Expensify/App/issues/21755#issuecomment-1610257940) ?

**Comment by laurenreidexpensify** [comment]
Sorry folks I broke the order here! Still waiting for @youssef-lr to sign off on the proposal https://github.com/Expensify/App/issues/21755#issuecomment-1618665262

**Comment by jayeshmangwani** [comment]
@0xmiroslav [PR](https://github.com/Expensify/App/pull/22345) is ready for review,

@laurenreidexpensify I have accepted these 2 offers (https://github.com/Expensify/App/issues/21755#issuecomment-1619735243 , https://github.com/Expensify/App/issues/21755#issuecomment-1619735320) before, should I ignore these 2 offers (https://github.com/Expensify/App/issues/21755#issuecomment-1623616663 , https://github.com/Expensify/App/issues/21755#issuecomment-1623616773)?

**Comment by jayeshmangwani** [comment]
@0xmiroslav bump for review

**Comment by laurenreidexpensify** [comment]
Waiting on @0xmiroslav for final steps here

**Comment by youssef-lr** [comment]
Not overdue. Waiting for checklist.

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

-  External issue reporter - @jayeshmangwani $250, paid in Upwork
-  Contributor that fixed the issue - @jayeshmangwani $1000, paid in Upwork 
-  Contributor+ that helped on the issue and/or PR - @0xmiroslav payment still outstanding as job not accepted in Upwork

**Comment by laurenreidexpensify** [comment]
Payment Summary Update:

- External issue reporter - @jayeshmangwani $250, paid in Upwork
- Contributor that fixed the issue - @jayeshmangwani $1000 *AND $500 3 day bonus* paid in Upwork
- Contributor+ that helped on the issue and/or PR - @0xmiroslav payment still outstanding  *$1000 AND $500 3 day bonus*  as per [this comment](https://github.com/Expensify/App/issues/21755#issuecomment-1655730009)

**Comment by laurenreidexpensify** [comment]
@0xmiroslav can we pay this yet?

**Comment by jayeshmangwani** [comment]
@laurenreidexpensify I have been paid for the reporter, but job is showing as `Work in progress` at Upwork , Can you please End contract from your side at Upwork?

**Comment by laurenreidexpensify** [comment]
@jayeshmangwani ah sorry for confusion. I paid everything in one contract, have close out the other contract now.

**Comment by laurenreidexpensify** [comment]
@0xmiroslav are we good to pay this one yet?
