### ISSUE TITLE
[HOLD for payment 2023-07-12][$1000] All task related pages have extra padding between header and content

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on FAB Icon
3. Click on Assign task
4. Notice on assign page Header and content has huge extra spacing then other pages (this can be quick compare by navigating to profile page (from drawer) notice here padding between header and contact does not have extra padding
5. This extra padding gap of (20px) can be found on all task related pages like Assign task, confirm task, task title ,task description pages
## Expected Result: 
There should be no extra padding between header and content just like all other pages (consistency across the similar pages on app)
## Actual Result: 
There is extra padding between header and content on all task related pages
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/96352938-7047-4292-bad5-2796b0bed54c)
![Extra 2706](https://github.com/Expensify/App/assets/43996225/d39c02c0-4401-405a-836f-776b670560b1)
![image](https://github.com/Expensify/App/assets/43996225/9f6192bb-264d-4308-ad95-cec0d02f8750)
![Screenshot 2023-06-26 at 1 05 59 PM](https://github.com/Expensify/App/assets/43996225/1811b568-1ed9-4a4b-95a6-918ae7c33bce)
![Screenshot 2023-06-26 at 1 05 24 PM](https://github.com/Expensify/App/assets/43996225/5c22ecda-435b-4a13-b9f0-ccf5b0b0e30b)
![Screenshot 2023-06-26 at 1 04 50 PM](https://github.com/Expensify/App/assets/43996225/86d021cc-3366-4c42-929c-c02d720e0c1a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687764851615229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5dc2de852edd528</li>
        <li>Upwork Job ID: 1674640685641990144</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
All task related pages have extra padding between header and content
### What is the root cause of that problem?
The root cause is we might have added extra `styles.mt5` to parent view of the all below screens during initial phase which was not required as per code consistency
### What changes do you think we should make in order to solve the problem?
### Solution - 1
We need to remove extra `styles.mt5` padding on below pages as we don’t required since header already has enough padding
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/pages/tasks/NewTaskDetailsPage.js#L87
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/pages/tasks/NewTaskPage.js#L153
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/pages/tasks/NewTaskTitlePage.js#L88
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/pages/tasks/NewTaskDescriptionPage.js#L82
### Solution -2
Apply required padding-top on above files (but mostly solution - 1 is recommend as it makes all this pages consistent with other pages

**Comment by kadiealexander** [comment]
@thienlnam. @shawnborton Just wanted to check that this padding isn't intentional before we fix it, any advice please?

**Comment by shawnborton** [comment]
I agree that we should remove that extra padding to be consistent with other pages. Thoughts @thienlnam ?

**Comment by tylerkaraszewski** [comment]
> @dhairyasenjaliya's [proposal](https://github.com/Expensify/App/issues/21754#issuecomment-1610255532) make sense to me, looks straightforward.
> 
> 🎀 👀 🎀 C+ reviewed

Are you sure that's the correct user? The proposal was posted by @kavimuru

**Comment by tylerkaraszewski** [comment]
@kadiealexander - I am leaving today on sabbatical. Can you please remove and re-apply the `Engineering` label to select a new engineer to finish this issue? Thanks!

**Comment by Julesssss** [comment]
> I am leaving today on sabbatical. Can you please remove and re-apply the Engineering label to select a new engineer to finish this issue? Thanks!

I was assigned the review, so I'll take over, no need to reassign.

**Comment by Julesssss** [comment]
Merged, awaiting deployment

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@fedirjh] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@fedirjh] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@fedirjh] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@fedirjh] Determine if we should create a regression test for this bug.
- [ ] [@fedirjh] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.35-5 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/21981

If no regressions arise, payment will be issued on 2023-07-10. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by kadiealexander** [comment]
🎯 ⚡️ Woah @fedirjh / @dhairyasenjaliya, great job pushing this forwards! ⚡️

The pull request got merged within 3 working days of assignment, so this job is eligible for a 50% #urgency bonus 🎉

- when @dhairyasenjaliya got assigned: 2023-06-30 16:02 UTC
- when the PR got merged: 2023-07-03 07:57 UTC

On to the next one 🚀

**Comment by kadiealexander** [comment]
@fedirjh Please make sure the checklist is complete!

**Comment by Julesssss** [comment]
Hi @kadiealexander, this is ready to be paid out now I think

**Comment by kadiealexander** [comment]
Everyone has been paid :)
