### ISSUE TITLE
 Flag page still shows option with invalid reportID or reportActionID and when chooosing an option, console error appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open with deep link of flag page that contain invalid reportID or reportActionID
2. Notice that flag page still shows option
3. Select any option
4. Notice console
## Expected Result: 
We should display not found page when opening flag page with invalid reportID or reportActionID
## Actual Result: 
1. Flag page still shows option with invalid reportID or reportActionID
2. After selecting any option console error appear

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8a10fe99-c1d6-4ba9-84cf-be68066f2d26

[246756576-44bbc750-d465-4007-869c-fe45ff8aca55 (1).webm](https://github.com/Expensify/App/assets/43996225/15cea3e8-1990-498c-b22a-9f5ee8ad3caf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687583790972699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Flag page still shows option with invalid reportID or reportActionID and when chooosing an option, console error appears
### What is the root cause of that problem?
We don't have any check to display not found page if the report or reportAction doesn't exist
### What changes do you think we should make in order to solve the problem?
We could use `FullPageNotFoundView` to wrap here with `shouldShow` prop is `_.isEmpty(report) || _isEmpty(reportAction)`
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/FlagCommentPage.js#L144
And we should move the logic here first to get the correct reportAction that help the check to display not found page correctly
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/FlagCommentPage.js#L119-L122
```
let reportAction = props.reportActions[`${props.route.params.reportActionID.toString()}`];
  let reportID = getReportID(props.route);
    if (reportAction === undefined || reportAction.reportActionID === undefined) {
        reportID = ReportUtils.getParentReport(props.report).reportID;
        reportAction = ReportActionsUtils.getParentReportAction(props.report);
    }
```
### What alternative solutions did you explore? (Optional) (edited)

**Comment by twisterdotcom** [comment]
I am OOO!

**Comment by MitchExpensify** [comment]
> of flag page that contain invalid reportID or reportActionID

Why would a user ever encounter this? Are you manually editing the URL?

**Comment by MitchExpensify** [comment]
Bump @dukenv0307 on [the above](https://github.com/Expensify/App/issues/21750#issuecomment-1615238335) to understand better. I'm not sure users would ever run into this, or if we'd care to fix it, if we're manually editing the URL

**Comment by MitchExpensify** [comment]
Thanks! I think we gotta close this in that case. I don't think we can count a manually edited URL as causing this unexpected behavior
