### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] DEV: App crash when go to settings of public room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to any public room (e.g. http://localhost:8080/r/8936976277251806)
3. Open settings of public room
## Expected Result: 
App should not crash
## Actual Result: 
App crash when go to settings

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** DEV
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cdd402c2-3a26-4fc1-b2fa-c386cbc8d8e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @PrashantMangukiya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687760658520999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01507221e6e9e02915</li>
        <li>Upwork Job ID: 1676955027897794560</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
DEV: App crash when go to settings of public room
### What is the root cause of that problem?
We are translating visibility description via this code:
https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/pages/settings/Report/ReportSettingsPage.js#L203
Value for this.props.report.visibility comes as 'public_announce'. But we need only 'public' word. So this is the root cause of the problem.
### What changes do you think we should make in order to solve the problem?
We have to remove value after _ as shown code below:
```javascript
// <Text style={[styles.textLabelSupporting, styles.mt1]}>{this.props.translate(`newRoomPage.${this.props.report.visibility}Description`)}</Text> // *** OLD CODE ***
<Text style={[styles.textLabelSupporting, styles.mt1]}>{this.props.translate(`newRoomPage.${this.props.report.visibility.replace(/_.+/g, '')}Description`)}</Text> // *** UPDATED CODE ***
```
### What alternative solutions did you explore? (Optional)
None
<details>
<summary>Result</summary>
https://github.com/Expensify/App/assets/7823358/1af23bfa-1641-4326-9e4a-de5f0722a6c2
</details>

**Comment by johncschuster** [comment]
Not overdue. I was OOO for the holiday and have just come back.

**Comment by Pujan92** [comment]
Not able to reproduce

**Comment by Santhosh-Sellavel** [comment]
Started a internal thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1688759939535989)

**Comment by johncschuster** [comment]
Following the internal thread

**Comment by Santhosh-Sellavel** [comment]
Coming from [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1689096507454499?thread_ts=1688759939.535989&cid=C02NK2DQWUX) 

As it is a different room type., We decided it's best we add a new key here. For now, let's just stick with the same value public room. So let's go with the @hungvu193 [here](https://github.com/Expensify/App/issues/21759#issuecomment-1610380350), thanks!

C+ reviewed
🎀 👀 🎀

**Comment by johncschuster** [comment]
I'm a bit confused, @Santhosh-Sellavel. Are you suggesting in [this comment](https://github.com/Expensify/App/issues/21759#issuecomment-1631224155) that @hungvu193 work on _this_ issue, or is @hungvu193 working on another issue that will also resolve this behavior?

**Comment by Santhosh-Sellavel** [comment]
@johncschuster 

Picked @hungvu193 to work on this based their [proposal](https://github.com/Expensify/App/issues/21759#issuecomment-1610380350), which aligns with our decision.

**Comment by Santhosh-Sellavel** [comment]
@thienlnam We can skip the checklist here for the following reasons

1. The room that causes the bug cannot be created from a new dot client. Refer [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1689017923451119?thread_ts=1688759939.535989&cid=C02NK2DQWUX)
2. This is the [PR](https://github.com/Expensify/App/pull/20500) which causes the regression. It will not be easy to capture as per statement 1 above.

We don't need a regression Test As well.

Let me know your thoughts, thanks!

**Comment by Santhosh-Sellavel** [comment]
@thienlnam bump for the above ☝️

**Comment by Santhosh-Sellavel** [comment]
@johncschuster Can you leave a comment mentioning the amount to be paid here so I can request payment on ND thanks!

**Comment by thienlnam** [comment]
Agree with you statement - no regression test needed

**Comment by johncschuster** [comment]
### Summary of payments:
 External issue reporter - @PrashantMangukiya - $250
 Contributor that fixed the issue - @hungvu193 - $1500
 Contributor+ that helped on the issue and/or PR - @Santhosh-Sellavel - $1500 - to be paid via NewDot

**Comment by johncschuster** [comment]
I have issued payment for @hungvu193. @PrashantMangukiya, I have sent you an invite. Can you accept it? Thanks!

**Comment by PrashantMangukiya** [comment]
@johncschuster invite accepted. Thank you.

**Comment by johncschuster** [comment]
Paid! 🎉

**Comment by johncschuster** [comment]
@JmillsExpensify 
## Summary of payments:
External issue reporter - @PrashantMangukiya - $250
Contributor that fixed the issue - @hungvu193 - $1500
Contributor+ that helped on the issue and/or PR - @Santhosh-Sellavel - $1500 - to be paid via NewDot

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
