### ISSUE TITLE
Setting a lot of data in Onyx is slow

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#21766]
Coming from https://github.com/Expensify/App/issues/21444

Threads with context:
https://expensify.slack.com/archives/C03TQ48KC/p1687893191020179
https://expensify.slack.com/archives/C036S0BVAHH/p1687812903398059

# Problem

Setting a lot of data in Onyx is super slow.

This started/finished is calls to onyx. You can see it takes 20 seconds to set the key 19 and 1 minute 8 seconds the second one.
```
19:58:45.761 web.development.js:1304 started 19 () => mergeCollection(key, value)
19:58:45.762 web.development.js:1304 started 20 () => mergeCollection(key, value)
19:59:06.247 web.development.js:1305 finished 19 () => mergeCollection(key, value)
19:59:53.190 web.development.js:1305 finished 20 () => mergeCollection(key, value)
```

I have a file with the data that's failing, but I think it might contain sensitive information but I can say it's 30MB uncompressed. The 20th call above is the biggest as one might expect.

In order to test this in dev (for internal engineers only) is to change the OpenApp code to (data.json is the file with all the data):
```
    } elseif ($command === 'OpenApp') {
        $response = json_decode(file_get_contents('data.json'), true);
//        $response['onyxData'] = AppInit::openApp($authToken, $_REQUEST['policyIDList'] ?? '');
```

I assume it can also be reproduced by joining 1000s of policies. This user's data:
- 3216 policies 
- 7k personal details (x 2)
- 9k reports

# Solution

Either make onyx be faster or recognize we need to do pagination of policies and reports
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a864f2f0848526ae</li>
        <li>Upwork Job ID: 1676300792032952320</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by iwiznia** [comment]
Updated the data above, just realized that we have 2x the number of personal details that we need to due to the migration to accountIDs, so if we remove that, this will get a bit better, but not nearly enough since most of the time is on the reports.

**Comment by michaelhaxhiu** [comment]
@iwiznia what should i do with this one? Does it go to `Engineering`?

**Comment by michaelhaxhiu** [comment]
Sorry I just mean what did you hope to see for this particular GH that you made? Do you want it to go to `external` or `internal` for now?

**Comment by iwiznia** [comment]
Let's use this issue for ht pagination

**Comment by iwiznia** [comment]
Here's the data.json file I reference 
[data.json.zip](https://github.com/Expensify/App/files/12009408/data.json.zip)

**Comment by michaelhaxhiu** [comment]
Slack convo going on here https://expensify.slack.com/archives/C01GTK53T8Q/p1689036681307159 that was started yesterday

**Comment by marcaaron** [comment]
@AndrewGable Need to move my focus elsewhere and the Guides seem unblocked for now, but here's a summary of my attempts today...

- [This PR](https://github.com/Expensify/react-native-onyx/pull/237) introduced something called `removeItems()` which replaced the call to `Storage.clear()`
- The problem with `removeItems()` is that it just doesn't work for large accounts when they are signing out. Tons of data is left behind. 
- I tried to swap out the method, but it was not as straightforward as I thought and a bunch of tests broke.
- I am moving on to other things for now.

Ideas for what to do next...

- Pass this to a contributor to fix
- Get the contributor who introduced the change to roll it back
- Get an "expert" contributor to figure out why removeItems is not working

**Comment by michaelhaxhiu** [comment]
Note: I'm preparing to go OOO for 2 weeks and removing my assignment. This is an `Improvement` and seems to be moving forward (e.g. I notice @kidroca making moves in https://github.com/Expensify/react-native-onyx/issues/281), but if it needs a BZ assigned can you please apply the `Bug` or `New Feature` label to ensure one is assigned?

cc @AndrewGable

**Comment by maddylewis** [comment]
added `Bug` label based on this comment / it wasn't ever added - https://github.com/Expensify/App/issues/21766#issuecomment-1665740314

i don't totally understand what Onyx is or how it's affecting our users but I have a couple of SR escalated issues having to do with admins not being able to use newdot/chat at all. so wanted to get some action on this issue again just in case that's related.

**Comment by marcaaron** [comment]
>i don't totally understand what Onyx is or how it's affecting our users

attempted to answer this [here](https://stackoverflowteams.com/c/expensify/questions/17534/17535#17535)

**Comment by marcaaron** [comment]
>I have a couple of SR escalated issues having to do with admins not being able to use newdot/chat at all

Whatever these issues are we should escalate and get more 👀 on them. My guess would be that it's not related to this issue.

**Comment by AndrewGable** [comment]
@muttmuure and I [discussed this issue in Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1697019585939189), since it's somewhat a catchall issue with no clear solution, we think we should tackle this issue with our new format of finding specific issues via audits with our external contributors. Please reopen if you disagree.
