### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web - Request money option shouldn't be shown in the task report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB button and Assign Task for account B
2. After task is created >>  task details page will be will be show
3. Click on + button on the left of COMPOSER

## Expected Result:
There should not be a request money option on a task

## Actual Result:
When you reload the page you'll see a request money option. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7af4c114-96ff-46da-bc1a-95c280af450a

https://github.com/Expensify/App/assets/93399543/58569b69-610a-492b-93f5-19d0599216b4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687721973756379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01235f8dee56a999c2</li>
        <li>Upwork Job ID: 1674900454492430336</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Asking in slack if this can be reproduced in staging https://expensify.slack.com/archives/C049HHMV9SM/p1687969709649929?thread_ts=1687721973.756379&cid=C049HHMV9SM

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is Request Money option on task report

### What is the root cause of that problem?
There's no check if report type is task in `ReportUtils.getMoneyRequestOptions`

### What changes do you think we should make in order to solve the problem?
Add one more check here:
https://github.com/Expensify/App/blob/3b721c4cbf1714720d529a9ef5b81f14e1cb699c/src/libs/ReportUtils.js#L2187-L2191
So if `isTaskReport(report)` return []

**Comment by Christinadobrzyn** [comment]
I still can't reproduce this - I think it has something to do with my Desktop app loading when I refresh. Either way there are several reports of this including - https://github.com/Expensify/App/issues/21800

The discussion is we don't want Request Money to be enabled with a task - https://expensify.slack.com/archives/C01GTK53T8Q/p1688073096458079

**Comment by abdulrahuman5196** [comment]
>The discussion is we don't want Request Money to be enabled with a task - https://expensify.slack.com/archives/C01GTK53T8Q/p1688073096458079

Thank you for the references and confirmation on the expectation so far @Christinadobrzyn . Could you also kindly update the title to reflect, **"Request money option shouldn't be shown in the task report"**

Given the last update, @situchan 's proposal here https://github.com/Expensify/App/issues/21788#issuecomment-1613836970 looks good and works well.

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

cc: @Christinadobrzyn

**Comment by abdulrahuman5196** [comment]
@marcochavezf The C+ approved comment is here https://github.com/Expensify/App/issues/21788#issuecomment-1616694770

**Comment by marcochavezf** [comment]
Thanks @abdulrahuman5196, assigning @situchan 🚀

**Comment by tranvantoan-qn** [comment]
Contributor details
Your Expensify account email: tranvantoan.qn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f07ead7068a224c

**Comment by situchan** [comment]
@abdulrahuman5196 [PR](https://github.com/Expensify/App/pull/22244) is ready for review

**Comment by tranvantoan-qn** [comment]
@Christinadobrzyn 
How can I apply for the job as a reporter? I'm pretty sure I posted my Contributor details before on another task. But don't know why the bot asked me again for this task - So I'm not automatically assigned

**Comment by Christinadobrzyn** [comment]
@tranvantoan-qn I'm not sure but I suspect it's related to your Upwork profile being set to private. Maybe our API can't find your profile. 

I can see you are listed as the reported on the OP. Can you send an offer through the [Upwork job](https://www.upwork.com/jobs/~01235f8dee56a999c2) or make your profile public and I can hire you?

Upwork job: 
Internal job: https://www.upwork.com/ab/applicants/1674900454492430336/job-details
External job: https://www.upwork.com/jobs/~01235f8dee56a999c2

Hired: 
@situchan as contributor
@abdulrahuman5196 as C+
@tranvantoan-qn as reporter

**Comment by tranvantoan-qn** [comment]
When I apply for the job, it asked me to:
- Spend 16 Connects to apply
- adjust the Bid (default $1000)
But I thought these steps are handled automatically.

**Comment by tranvantoan-qn** [comment]
Yeah, So if I got the offer sent by BZ, I can also just accept it - then I do not need to spend that 16 Connects? @parasharrajat

**Comment by Christinadobrzyn** [comment]
Thanks for your help @parasharrajat The offer has been sent - 
![image](https://github.com/Expensify/App/assets/51066321/fb9a1f36-464c-4f4c-8582-d78ff5797bd8)

The issue seems to be with how to accept the offer, right @tranvantoan-qn?

**Comment by tranvantoan-qn** [comment]
Yeah
- By applying to the job in the job list with normal Upwork flow
- Or by accepting via **direct offer** sent by BZ

Since this is my first time, so I'm wasn't sure which one is the best fit with the current GH workflow

**Comment by Christinadobrzyn** [comment]
That's a really good question @tranvantoan-qn I'm not super familiar with what the offer looks like in Upwork but I think you'd want to accept the direct offer. I do see that you've been hired so I think everything is back on track? Sorry I'm not more help, let us know if there was any downfall to how you ended up accepting the job!

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the PR and waiting for payment based on https://github.com/Expensify/App/issues/21788#issuecomment-1622446166

@abdulrahuman5196 do we need a regression test for this?

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression, but a miss during task report implementation.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Minor miss during implementation and regression test wouldn't be beneficial here.

**Comment by abdulrahuman5196** [comment]
@Christinadobrzyn / @sonialiap  BZ checklist is complete.

Payment processing could be started on this issue.

**Comment by sonialiap** [comment]
@tranvantoan-qn Offer sent for reporting issue - paid ✔️ 
@situchan for fix (+bonus) - paid ✔️ 
@abdulrahuman5196 for review (+bonus) - paid ✔️
