### ISSUE TITLE
Web - Workspaces invite numbers show duplicate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21782]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Create and login new account
2. Open new chat account B => chat anything
3. Open new chat account C => chat anything
4. Open setting => Workspaces => New workspaces
5. Click members  => Invite
6. Select B and C
7. Next => Invite, Observe that users B and C are duplicated

## Expected Result:
 No duplicate when inviting members

## Actual Result:
Users B and C are duplicated

## Workaround:
Uknonwn

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1ff48df2-b07f-4b1c-a8fc-63cd057bf025

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687706792344839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
Dup https://github.com/Expensify/App/issues/21706

**Comment by sonialiap** [comment]
Thanks Steven! Closing as dupe
