### ISSUE TITLE
[$1000] The Hover action menu doesn’t disappear after closing an attachment using the ESC button or by clicking on empty space.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the desktop web.
2. Navigate to a chat.
3. Send a viewable attachment (PDF/PNG/JPEG).
4. Open the sent attachment.
5. Close the attachment by clicking outside the attachment modal or by pressing the ESC button.
6. Observe that the hover action menu is still present over the attachment in the chat.

## Expected Result:

The hover action menu should disappear once the attachment is closed.

## Actual Result:

he hover action menu remains over the attachment even after it is closed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/433f150f-d6ae-47fc-b107-3ff163ecccc6

https://github.com/Expensify/App/assets/43996225/fb47adc5-4fd9-4427-9547-7f4532f4d354

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687774191624049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b8805f747f9c276</li>
        <li>Upwork Job ID: 1674746144115544064</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
@ginsuma thanks for calling that out! Let's go ahead and close this one in favor of https://github.com/Expensify/App/issues/21621
