### ISSUE TITLE
[HOLD for payment 2023-08-31] not able to send .bmp file

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send bmp file

## Expected Result:
should not show any error
## Actual Result:
error appears (Unexpected error while posting the comment, please try again laterWe were unable to process this file)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/931293f3-edcf-4dec-b0a6-b9fc490d79ea
![Untitled1](https://github.com/Expensify/App/assets/43996225/b0825b4a-2987-43e4-944b-ec82bf994e61)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687772087959949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01912e9c11960ab837</li>
        <li>Upwork Job ID: 1676004160913571840</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Likely an internal issue. Started looking into the back-end code that handles this.

**Comment by puneetlath** [comment]
@youssef-lr you said you might have an idea why this is occuring?

**Comment by youssef-lr** [comment]
I'm gonna take a look now @puneetlath

**Comment by youssef-lr** [comment]
OK as I suspected it's due to this [PR](https://github.com/Expensify/Web-Expensify/pull/38011/files#diff-226c5d32da881d917aecc36ba4f92b77971699b9ed01f2962c14f05995b939d8R317)  where we added a check to see if the filetype coming from the frontend is the same as the one we get from `exec('file -b --mime '..)` in PHP, so here looks like there is a mismatch, the browser sends `image/bmp` but in PHP it's `image/x-ms-bmp`. I can figure out a solution so feel free to assign me! 
cc @MariaHCD

**Comment by puneetlath** [comment]
Ok sounds good. Thanks @youssef-lr!

**Comment by MariaHCD** [comment]
> the browser sends `image/bmp` but in PHP it's `image/x-ms-bmp`

Interesting, so it looks like `image/bmp` is the [official mime type](https://www.iana.org/assignments/media-types/media-types.xhtml) but `image/x-ms-bmp` is an unofficial MIME type specific to Microsoft Windows

**Comment by MariaHCD** [comment]
@youssef-lr I wonder if [my PR](https://github.com/Expensify/Web-Expensify/pull/38011/files#diff-226c5d32da881d917aecc36ba4f92b77971699b9ed01f2962c14f05995b939d8R317) is causing more issues than it is worth 😅 Another example of mismatching mime types is here (full [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227e5ba4b34fcf0483-CDG%22)+AND+timestamp:[2023-07-12T18:20:32.133Z+TO+2023-07-12T20:20:32.133Z]&index=logs_expensify-023273)):

```
7e5ba4b34fcf0483-CDG | virt2.rno | 2023-07-12 19:20:32 133 | hassanardeshir01@gmail.com | Processing file attachment upload ~~ cleanedFileName: 'Andrzej_Ruszczy_ski_-_Nonlinear_Optimization__-Princeton_University_Press__2006_.pdf' fileMimeType: 'application/pdf; charset=binary' fileExtension: 'pdf' uploadedFileType: 'application/octet-stream'
```

The browser detected the pdf as `application/octet-stream` but we got `application/pdf`

From https://www.iana.org/assignments/media-types/application/octet-stream:

> The "octet-stream" subtype is used to indicate that a body contains arbitrary binary data.

**Comment by youssef-lr** [comment]
I think let's revert it and figure it out a different approach for actually invalid files. What do you think?

**Comment by MariaHCD** [comment]
Yup, let's revert it. A potential approach might be to allow sending the file but don't try to render a preview for it: https://github.com/Expensify/App/issues/19728#issuecomment-1633970096

**Comment by proshir** [comment]
I am the one who encountered this pdf problem. The main problem is that sometimes the pdf can be sent, but when its size exceeds a certain limit, it can't. It's as if he wants to squeeze more than a certain limit and it gets bad.

**Comment by proshir** [comment]
Contributor details
Your Expensify account email: hassanardeshir01@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01a9187663aa0cfbb4)

**Comment by proshir** [comment]
Some browsers have limitations on the size of files that can be uploaded via standard HTML form submissions. When a file exceeds this limit, the browser may not accurately determine the MIME type, resulting in a generic application/octet-stream MIME type. To overcome this limitation, you can consider using alternative methods for file upload, such as chunked or asynchronous uploads, or using libraries specifically designed for handling large file uploads.

**Comment by MariaHCD** [comment]
This issue will be fixed once the [revert PR](https://github.com/Expensify/Web-Expensify/pull/38169) is on production. @youssef-lr let's move to https://github.com/Expensify/App/issues/19728 for how to handle disabling previews for invalid files?

**Comment by youssef-lr** [comment]
Still on hold.

**Comment by youssef-lr** [comment]
This should be fixed now.

**Comment by youssef-lr** [comment]
Not sure why this is still open but the fix has been deployed!

**Comment by gadhiyamanan** [comment]
@youssef-lr this is eligible for reporting bonus, csn you reopen the issue?

**Comment by youssef-lr** [comment]
@bfitzexpensify can we please handle the reporting bonus for @gadhiyamanan?

**Comment by bfitzexpensify** [comment]
Sure thing, offer sent @gadhiyamanan

**Comment by gadhiyamanan** [comment]
@bfitzexpensify offer accepted, thanks

**Comment by bfitzexpensify** [comment]
All done!
