### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Web - UserB can still create a task in room chat when UserA changes post permission to "Admins only"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21791]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to UserA account
2. Navigates to the "New room" section
3. Creates a new room by entering a room name and select UserA's workspace
4. Set the visibility of the room to "Public"
5. Clicks on "Create room"
6. Go to the room details
7. Select "Share code" and copy the URL to the clipboard
8. Returns to the previous page and clicks on "Settings" > "Who can post"
9. In another browser, login to UserB account
10. Joins the room by pasting the copied URL
11. Go to the "Assign task" section in the room chat
12. Change the "Who can post" setting to "Admins only" from UserA account
13. Now you can create a task in the room chat

## Expected Result:
When UserA changes the post permission to "Admins only," UserB should not be able to create a task in the room chat

## Actual Result:
Even after UserA changes the post permission to "Admins only," UserB can still create a task in the room chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/041e4387-cb25-4fa0-84f5-0b17c26cb186

https://github.com/Expensify/App/assets/93399543/ba594cfd-cb88-44a3-8751-e49395a45313

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687722646703389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc548bc92bd6afb3</li>
        <li>Upwork Job ID: 1674304197984038912</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Repro'd:

https://github.com/Expensify/App/assets/59587260/dbdee387-fdc5-477e-a427-d129c4bf1dec

**Comment by sobitneupane** [comment]
@dukenv0307 Thanks for your [proposal](https://github.com/Expensify/App/issues/21791#issuecomment-1611294044).

Can we show a page similar to Not Found Page specifying user don't have access to assign task? It will inform user that he/she no longer have access.

**Comment by sobitneupane** [comment]
@dukenv0307 Can you please add an alternative proposal for https://github.com/Expensify/App/issues/21791#issuecomment-1614372669

**Comment by sobitneupane** [comment]
Alternative Solution from @dukenv0307's [proposal](https://github.com/Expensify/App/issues/21791#issuecomment-1611294044) looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
Oh yes. That might be necessary when user tries to create task from LHN.

**Comment by cristipaval** [comment]
I think we should block the task creation in this case on the backend side as well 🤔

**Comment by cristipaval** [comment]
> 📣 @ayazhussain79 You have been assigned to this job! Please apply to this job in Upwork [here](https://www.upwork.com/jobs/~01fc548bc92bd6afb3) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

@dukenv0307 has been actually assigned  to this job.

**Comment by cristipaval** [comment]
Alright, created an [Auth PR](https://github.com/Expensify/Auth/pull/8227) to throw an error in backend.

**Comment by kadiealexander** [comment]
I'm going OOO tomorrow for a long weekend so I need some help with [payment](https://www.upwork.com/ab/applicants/1674304197984038912/hired) on Friday!

**Comment by kadiealexander** [comment]
Thanks for the help Flavia!

**Comment by ayazhussain79** [comment]
@kadiealexander offer accepted, Thank you

**Comment by flaviadefaria** [comment]
@sobitneupane can you please answer the information [here](https://github.com/Expensify/App/issues/21791#issuecomment-1625186283)? Thanks!

**Comment by flaviadefaria** [comment]
Payment issued for @dukenv0307 and @ayazhussain79.

**Comment by ayazhussain79** [comment]
Thank you

**Comment by flaviadefaria** [comment]
@sobitneupane friendy bump here so that we can close this GH.

**Comment by flaviadefaria** [comment]
@sobitneupane are you able to complete this today?

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17992

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17992#issuecomment-1647943102

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is an edge case. So, I don't think this could have been caught earlier in PR review.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Login with user A
2. On another device, login with user B
3. From user B, create a workspace and invite user A to the workspcae
4. From user A, go to announce chat of this workspace
5. Click on plus icon > Assign task
6. Enter title, description and go to next step
7. From user B, go to announce chat of this workspace
8. Change the setting of "Who can post" to "Admins only"
9. From user A, verify that not found page appears, and after clicking on the back button, the modal is dismissed

**Comment by sobitneupane** [comment]
Requested payment on newDot.

**Comment by flaviadefaria** [comment]
Cool once Anu pays you we can close this.

**Comment by flaviadefaria** [comment]
> Requested payment on newDot.
@anmurali, just for your control this should have been $1500.

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.

**Comment by flaviadefaria** [comment]
Great so closing this.
