### ISSUE TITLE
[Reporting bonus] [$1000] Workspace members disappears after adding a user.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with a new account.
2. Navigate to settings.
3. Go to Workspaces and create a workspace.
4. Open manage members page.
5. Tap invite.
6. Invite a new user.
## Expected Result:
The newly added user and admin should appear in the members
## Actual Result:
Admin disappears and newly added user shouldn't disappear
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a0f2d8dd-7ff2-471b-9973-80ce8081cb9a

https://github.com/Expensify/App/assets/43996225/74f7e929-c0af-4375-b681-3895aaaf8a74

**Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687776118282619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4f6364537fafea1</li>
        <li>Upwork Job ID: 1674884524975476736</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
I can't log in with a new account right now: 

<img width="268" alt="image" src="https://github.com/Expensify/App/assets/24947345/f787940a-e03d-4b95-904c-acc294ea9477">


https://github.com/Expensify/Expensify/issues/287904

**Comment by NicMendonca** [comment]
I still can't log in with a new account 😭 

@kbecciv @Tushu17 can you still reproduce?

**Comment by NicMendonca** [comment]
Sorry for the delay! I was able to reproduce 👍

**Comment by NicMendonca** [comment]
@hoangzinh I reproduced with lower case

**Comment by mollfpr** [comment]
@hoangzinh is there any different response from the API with sending lowercase emails?

**Comment by mollfpr** [comment]
This issue is not reproducible, I guess it's already fixed by lowercasing the letter on the options selector.

| 1.3.33-4 |Latest main|
|-|-|
|![Screenshot 2023-07-09 at 22 44 03](https://github.com/Expensify/App/assets/25520267/33085646-5e20-4687-b5f0-dccfdb0ee814)|![Screenshot 2023-07-09 at 22 44 10](https://github.com/Expensify/App/assets/25520267/2278167f-eeef-4b71-9221-b23be34f889d)|

**Comment by Tushu17** [comment]
@NicMendonca It's not a duplicate report; I think this is eligible for reporting compensation. Thank you.

**Comment by NicMendonca** [comment]
@Tushu17 have you applied to the job?

**Comment by Tushu17** [comment]
@NicMendonca Not yet.

> Job added to Upwork: https://www.upwork.com/jobs/~01a4f6364537fafea1

Do I need to apply for this auto-generated job?

**Comment by NicMendonca** [comment]
@Tushu17 yes please! I just invited you to the job also

**Comment by Tushu17** [comment]
@NicMendonca I've applied for the job. Thank you.

**Comment by NicMendonca** [comment]
paid
