### ISSUE TITLE
Sending a DM to closed account results in "Auth GetRestrictedAuthTokenByEmail error"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Created new DM with [argie.goingco@team.expensify.com](mailto:argie.goingco@team.expensify.com) in New Expensify
2. [argie.goingco@team.expensify.com](mailto:argie.goingco@team.expensify.com) has an Expensify Account created in a closed state by Concierge on 2023-06-26.
3. Pasted content into newDot,  edited a few things (including custom subject header) and sent

## Expected Result:
Message should send successfully .
## Actual Result:
Received this error message
"Unexpected error while posting the comment, please try again later
Auth GetRestrictedAuthTokenByEmail returned an error"
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @StefStavri 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687775413798129

![image (1)](https://github.com/Expensify/App/assets/43996225/0081eb1e-504a-4cf7-81bb-1fa1617b7c34)

![image](https://github.com/Expensify/App/assets/43996225/a7beda9a-dfbe-449e-8331-118f0efc3dc3)

![Screenshot 2023-06-28 153932](https://github.com/Expensify/App/assets/43996225/ef05cd2f-32d4-4d48-94d4-c6d4fae6b813)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Hmm, I was able to send a message to closed account and didn't get an error.

**Comment by lschurr** [comment]
Bumped the Slack thread for more eyes.

**Comment by lschurr** [comment]
Ongoing convo: https://expensify.slack.com/archives/C04QEB4MJEQ/p1688146166939669?thread_ts=1687561229.524519&cid=C04QEB4MJEQ

**Comment by Beamanator** [comment]
Is this still not fixed? 😓

**Comment by lschurr** [comment]
Bumped this thread - https://expensify.slack.com/archives/C049HHMV9SM/p1688573563663839?thread_ts=1687775413.798129&cid=C049HHMV9SM

**Comment by lschurr** [comment]
@Beamanator any update here or can we close?

**Comment by Beamanator** [comment]
Heyey! In Slack I mentioned I couldn't reproduce :D Sounds like you tried too and couldn't reproduce, right? Let's close! :D

**Comment by StefStavri** [comment]
<img width="1355" alt="image" src="https://github.com/Expensify/App/assets/22508185/2cefbbc9-30a5-4995-9694-a00e3abb416b">

Same issue here. Trying to send a DM to a closed account for [this](https://github.com/Expensify/Expensify/issues/308535) onboarding SDR agent.

Is this specific to team.expensify.com emails perhaps @Beamanator ?

**Comment by lschurr** [comment]
Just commenting to remove the overdue since this was just reopened today. I'll leave for @Beamanator to take a look.

**Comment by lschurr** [comment]
Bump @Beamanator - is this bug still happening?

**Comment by lschurr** [comment]
I don't think this is ongoing - @StefStavri could you ask in Slack if you're still seeing this?
