### ISSUE TITLE
[$1000] Web - Mention suggestion disappear even when we try to type the full name of the user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any chat and type in  @full_name of user (user name who has first name and last name)
3. Notice that when you finish typing the first name of the user and move on to typing the surname, the mention results gets disappeared
4. If followed the same process on Slack, for a user that has both first and last name, no such problems are seen. We're able to see mention result for a person when we type that person's full name also

## Expected Result:
Mention suggestion should not disappear if typed person's full name (first and last name)

## Actual Result:
Mention suggestion disappears even when we try to type the full name of the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/36b4c132-b770-4bdf-b391-71b016c371e4

https://github.com/Expensify/App/assets/93399543/551ce810-ccc9-46d9-a7d2-7f474c7439ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687839668194259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114e7ef762b1d33db</li>
        <li>Upwork Job ID: 1678458209760714752</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
I agree that we don't attempt to pick up the last name, but I need to figure out what the expected result should actually be. It looks like Slack guesses at who you want to select based on the first name. Slack appears to only look for the name after you add the space.

<img width="472" alt="Screenshot 2023-07-10 at 10 33 34" src="https://github.com/Expensify/App/assets/8292562/37e4c18b-d0aa-4b96-b7d5-afa4ce59520d">
<img width="392" alt="Screenshot 2023-07-10 at 10 34 51" src="https://github.com/Expensify/App/assets/8292562/2ffaa8f7-7e37-41ab-92c1-b812a144eba8">

**Comment by tjferriss** [comment]
I'm [discussing](https://expensify.slack.com/archives/C03U7DCU4/p1689140645083899) this one internally to determine the expected behavior we want.

**Comment by tjferriss** [comment]
I brought this to the internal team and it was determined the actual result is the expected result so there so this is not a bug.
