### ISSUE TITLE
Dev: Web - Error when Request Money after assigning a task for SAME user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign task for user B
2. After the task is created, send Request Money to user B (either from FAB or from the report)

## Expected Result:
 Request Money should be sent successfully to user B

## Actual Result:
Error when Request Money after assigning a task to user B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5ebf3b18-401e-47db-b045-628d2caccebf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687723077547579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
BE return error.
![Annotation 2023-06-28 141118](https://github.com/Expensify/App/assets/131836113/7100c45c-eadc-4702-ae17-d88a420ce619)

**Comment by joekaufmanexpensify** [comment]
I can reproduce. Not sure what expected behavior here is though. Discussing [here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1688073096458079)

**Comment by joekaufmanexpensify** [comment]
Confirmed in Slack that It is expected that requesting money does not work right now. Further, there is already [an existing issue ](https://github.com/Expensify/App/issues/21788) where we plan to make it so the request money button does not appear in tasks (even after reloading). 

That will solve the bug in this issue as well. Based on that, we're going to close this one out, as no action is needed!
