### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] Web - Sender's account doesn't show up along with the message sent on IOU details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from account A to account B
2. Go to account B and open the IOU thread and click on the IOU card to open the details thread
3. Go to account A and open the IOU thread and click on the IOU card to open the details thread
4. Go to account B and send a message in the details thread
5. Go to account A and observe the LHN
6. Send a message on account A
7. Delete the last message you sent from account A

## Expected Result:
The account name then a colon then the message should show up.

## Actual Result:
Only the message sent shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3ac541e1-421c-49d0-afda-3e7c5f8f9b41

https://github.com/Expensify/App/assets/93399543/9c21853a-0e43-4ae2-abb4-c507d8d5af56

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687854592361269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b08a1555ca913175</li>
        <li>Upwork Job ID: 1681956035415707648</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>c3024 | Contributor | 25730129</li>
<li>Nathan-Mulugeta | Reporter | 25730131</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
I was able re-produce this issue on Browser/Mac

**Comment by muttmuure** [comment]
Getting to this tomorrow

**Comment by ayazhussain79** [comment]
@muttmuure please check that https://github.com/Expensify/App/issues/21810 This is the same bug that i have reported and you closed it before this one https://github.com/Expensify/App/issues/21810

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/21810#issuecomment-1612375586) from @c3024 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by marcochavezf** [comment]
Thanks @sobitneupane for the review, assigning @c3024 🚀

**Comment by marcochavezf** [comment]
Not overdue, awaiting for payment

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

There is no specific PR to blame for this issue. On transition from sequence number to time, we might have missed this case. There were many improvements afterwards.

> * [x]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

N/A
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is an edge case and very difficult to detect. So, only way to detect such issues is more testing.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.

> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Send a money request from A to B
2. Open the money request report
3. Send a message from B in the report
4. Send a message from A in the report
5. Delete the comment by A in this report from account A
6. Verify the LHN of A shows the username of B before the message text in LHN of A

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
@muttmuure Could you also summarize the payouts so I can approve the NewDot payment for @sobitneupane

**Comment by muttmuure** [comment]
C+ @sobitneupane - $1500
C @c3024 - $1500 
Reporter  @Nathan-Mulugeta - $250

**Comment by muttmuure** [comment]
@Nathan-Mulugeta paid
@c3024 paid

Waiting for @JmillsExpensify to pay @sobitneupane

**Comment by sobitneupane** [comment]
@muttmuure We are good to close the issue.
