### ISSUE TITLE
IOS -  Cut/Copy/Paste context menu blinks then disappears when double click in words in Task’s description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a task that has a description
2. Click on Description to view the description’s details.
3. Double-click on any word in the description.

## Expected Result:
Cut/Copy/Paste context menu should be displayed

## Actual Result:
Cut/Copy/Paste context menu blinks then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c296cb84-2d0e-4b5e-b87a-f4d638673b5b

https://github.com/Expensify/App/assets/93399543/5de6fa48-0a75-4337-a92a-307aab1e0ef4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687858087672039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment]
This is very likely the same issue as in:

- https://github.com/Expensify/App/issues/16696

and will be fixed with: 

-https://github.com/Expensify/App/pull/20186

I will test this in a few minutes to verify 😊

**Comment by dylanexpensify** [comment]
Sounds like this was fixed then, yeah @hannojg? 😄

**Comment by dylanexpensify** [comment]
bump @hannojg?

**Comment by hannojg** [comment]
Sorry, I edited the message instead of commenting 👀 
I wasn't able to reproduce the issue at all. That means I wasn't able to confirm whether the fix from the mentioned PR will fix this issue.

We can test it again once the PR got merged?

**Comment by dylanexpensify** [comment]
Ahh sorry @hannojg! Didn't see that 🤦, any idea when PR will be merged and we can test again? Considering making this weekly

**Comment by hannojg** [comment]
@dylanexpensify The PR got merged two days ago, you (or the issue creator) can either test from the main branch or wait until its on staging 😊

**Comment by dylanexpensify** [comment]
waiting for pr to be on staging!

**Comment by hannojg** [comment]
@dylanexpensify Its on staging!

**Comment by dylanexpensify** [comment]
WOOOOOO! Will test today!

**Comment by dylanexpensify** [comment]
testing now!

**Comment by dylanexpensify** [comment]
fixed!! 🎉 ty @hannojg!!

**Comment by tranvantoan-qn** [comment]
@dylanexpensify did you check the build for iOS on **main** or staging branch?

I'm checking it too
