### ISSUE TITLE
Web - Chat - Mention options are displayed even when compose box is not in focus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send few messages
4. Edit one of the message
5. In compose box, type @ with some letters to trigger mention options
6. Change and chat and revisit
7. Observe that edit message is in focus but mention options are still displayed on compose box

## Expected Result:
 App displays mention options even when compose box is not in focus

## Actual Result:
Unknown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4a58701c-b9ce-4f1e-95c6-debdca72d341
https://github.com/Expensify/App/assets/93399543/116841d5-4187-49bf-a1f5-5895c4b97267

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687873905467969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment]
I'm not sure this is a bug, as we support editing/creating multiple fields at the same time. I'm going to close though @puneetlath I'm curious if you disagree? Happy to re-open.

**Comment by puneetlath** [comment]
I agree, I think the current behavior is fine.
