### ISSUE TITLE
[$1000] Test Automatic Hires

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#21820]
Testing out the automatic hiring flow

**Issue reported by:** @jayeshmangwani

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbf25352787a3fa3</li>
        <li>Upwork Job ID: 1674090489634684928</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Testing out the automatic hiring flow

**Comment by jayeshmangwani** [comment]
@thienlnam Added proposal for testing

**Comment by thienlnam** [comment]
Will assign @getusha since they commented first but appreciate you both!

**Comment by ayazhussain79** [comment]
@thienlnam  applied for testing

**Comment by thienlnam** [comment]
Lovely! Thank you all
