### ISSUE TITLE
[Performance] Reduce re-renders of `ReportScreen` when re-opening/switching it

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#21831]
## What performance issue do we need to solve?

We want to optimise the performance when switching the chat/report screen.

## What is the impact of this on end-users?

Improved TTI when opening another report.

## List any benchmarks that show the severity of the issue

When using the react-devtools profiler we can track the commits react does. When opening a report screen, we can see that there is this is, after the `ReportScreen` has already been rendered another render. This render is due to the fact that a state variable called `skeletonViewContainerHeight` got changed:

![main](https://github.com/Expensify/App/assets/16821682/fce74535-171f-4e1b-b81d-620561cca13d)

In the current code-design we do need to measure that height once, however, this doesn't need to cause a re-render when we are switching the chat screen.

## Proposed solution (if any)

We are already storing the skeleton height globally to reuse it, all we need to do is stop the setState call.

Here, we store and reuse the height value:

https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/home/ReportScreen.js#L120-L134

Now, all we need to do is to stop the `setState` call [here](https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/home/ReportScreen.js#L314-L326), which could look like this:

```jsx
<View
    nativeID={CONST.REPORT.DROP_NATIVE_ID + this.getNavigationKey()}
    style={[styles.flex1, styles.justifyContentEnd, styles.overflowHidden]}
    onLayout={(event) => {
        // Rounding this value for comparison because they can look like this: 411.9999694824219
        const skeletonViewContainerHeight = Math.round(event.nativeEvent.layout.height);

        // ⚠️👀 PROPOSAL: Only set state when the height changes to avoid unnecessary renders
        if (reportActionsListViewHeight === skeletonViewContainerHeight) return;

        // The height can be 0 if the component unmounts - we are not interested in this value and want to know how much space it
        // takes up so we can set the skeleton view container height.
        if (skeletonViewContainerHeight === 0) {
            return;
        }
        reportActionsListViewHeight = skeletonViewContainerHeight;
        this.setState({skeletonViewContainerHeight});
    }}
```

(Note: another solution would be to turn the `ReportScreen` into a `PureComponent`, however, this if check is should be cheaper then a `PureComponent`)

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

When measuring with the profiler again, we can see that the additional render of the `ReportScreen` is gone (note: only true when opening the `ReportScreen` for the second time):

![Screenshot 2023-06-28 at 19 51 41](https://github.com/Expensify/App/assets/16821682/acdbfed4-4158-4371-8a13-3b15635a5cc8)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number: latest/main**
**Reproducible in staging?: yes**
**Reproducible in production?: yes**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by MariaHCD** [comment]
I don't believe I need to be assigned to this :)

**Comment by mountiny** [comment]
Handling the PR review so assigning to myself
