### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Web- Flagged as a violation message from the concierge can be deleted in room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21842]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any Public room that `User A` has created and `User B` is a member of that group
2. Send a message from `User A`
3. Go to `User B` and Flag it as Violation (Spam).
4. Now go to `User A` and notice that a message from the concierge appears.
5. As `User A`, delete the message from the concierge.

## Expected Result:
Flagged as a violation message from the concierge can't be deleted

## Actual Result:
 Flagged as a violation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6cac7cf6-1ddc-4d87-92bf-0257331a5636

https://github.com/Expensify/App/assets/93399543/8c95e9a5-2246-402c-94d5-f02f911532f5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687896716749819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012848636c2b7e6eeb</li>
        <li>Upwork Job ID: 1676954069734211584</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Sounds like this behavior is still reproducible after #18735 was resolved. ([Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1688663439404079?thread_ts=1687896716.749819&cid=C049HHMV9SM))

**Comment by eVoloshchak** [comment]
While both proposals would resolve the issue, I think @dukenv0307's [proposal](https://github.com/Expensify/App/issues/21842#issuecomment-1621454928) is better

> 
Adding a check directly to `canDeleteReportAction` is better, currently the function isn't doing when the comment says it's supposed to do: `Can only delete if the author is this user and the action is an ADDCOMMENT action or an IOU action in an unsettled report, or if the user is a policy admin`

`Can only delete if the author is this user`, this definitely shouldn't return true for a message sent by Concierge

🎀👀🎀 C+ reviewed!
cc: @johncschuster

**Comment by daveSeife** [comment]
> 📣 @daveSeife 🎉 An offer has been automatically sent to your Upwork account for the Reporter role 🎉 Thanks for contributing to the Expensify app!
> 
> [Upwork job](https://www.upwork.com/jobs/~012848636c2b7e6eeb)

Accepted the offer. Thank you!

**Comment by eVoloshchak** [comment]
Regression Test Proposal

1. Go to any Public room that User A has created and User B is a member of that group
2. Send a message from User A
3. Go to User B and Flag it as Violation (Spam).
4. Now go to User A and notice that a message from the concierge appears.
5. As User A, long press or right-click on the message from concierge
6. Verify there is no option to delete the message

Do we agree 👍 or 👎

**Comment by eVoloshchak** [comment]
@johncschuster, the automation didn't work, but it seems like this qualifies for the speed bonus. Could you confirm that? Thanks

**Comment by eVoloshchak** [comment]
Not overdue, this is waiting for the payments to be settled

**Comment by johncschuster** [comment]
Sorry I missed your request, @eVoloshchak!

> @johncschuster, the automation didn't work, but it seems like this qualifies for the speed bonus. Could you confirm that? Thanks

Yes, I do believe the issue is eligible for the bonus. Thanks for flagging that!

**Comment by johncschuster** [comment]
### Summary of payments:
 External issue reporter - @daveSeife - $250
 Contributor that fixed the issue - @dukenv0307 - $1500
 Contributor+ that helped on the issue and/or PR - @eVoloshchak - $1500 (to be paid via NewDot)

**Comment by johncschuster** [comment]
I have issued payments on Upwork for @daveSeife and @dukenv0307.

@eVoloshchak, can you request your payment on NewDot?

**Comment by eVoloshchak** [comment]
Requested the payment, thanks!

**Comment by JmillsExpensify** [comment]
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
