### ISSUE TITLE
[$1000] Web -  Inconsistent Cursor Icons in IOU Section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign :heavy_plus_sign:
2. Select "Request" and enter the desired number, then click "Next"
3. Add an email and click "Next"
4. In the IOU section, observe the header, where your name and the requested person's name and images are displayed. Hover over your name to see the tooltip, but notice that the cursor icon remains unchanged.

## Expected Result:
When hovering over the name in the IOU section, the cursor icon should change consistently when the tooltip is displayed.

## Actual Result:
 In the IOU section, when hovering over the requested name, the tooltip is displayed, but the cursor icon does not change.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
 

https://github.com/Expensify/App/assets/93399543/2f1b2595-32dc-48a2-b807-f99956bac6f4

https://github.com/Expensify/App/assets/93399543/be85a174-cbcd-4406-b9c5-b648b37eeed2

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687937957812279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01226ed738f57c06d5</li>
        <li>Upwork Job ID: 1674447566960848896</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- There is inconsistency in cursor icon when hovering over to the Avatar of the report and when hovering over to the Avatar of the comment/IOU Preview.

### What is the root cause of that problem?
- The rest of the components are showing `hand` icon as they are Wrapped with either PressableWithFeedback or PressablWithoutFeedback. And the AvatarWithDisplayName is not wrapped with any of these components.

### What changes do you think we should make in order to solve the problem?
- Wrapping the component with PressablWithoutFeedback, gives us the hand icon when hovering over to the Avatar / Name.

```diff
{this.props.shouldShowAvatarWithDisplay && (
+   <PressableWithoutFeedback>
        <AvatarWithDisplayName
            report={this.props.parentReport || this.props.report}
            policies={this.props.policies}
            personalDetails={this.props.personalDetails}
        />
+   </PressableWithoutFeedback>
)}
```

- We can add a prop to show Profile Preview when user presses on the Avatar / Name. ( Optional )

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by lazar-stamenkovic** [comment]
this issue is caused because Avatar component isn't covered by UserDetailsTooltip in AvatarWithDisplayName.js
![Screenshot 2023-06-29 at 13 06 57](https://github.com/Expensify/App/assets/114150992/2042b02c-14d8-4915-a28f-5cff7bbc0133)

**Comment by gitvolo** [comment]
Contributor details
Your Expensify account email: devvolodymyr@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0178098f00493ac910

**Comment by lazar-stamenkovic** [comment]
Contributor details
Your Expensify account email: lsblue1995101@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018c8b6faf87f97c3f

**Comment by lazar-stamenkovic** [comment]
please review my proposal https://github.com/Expensify/App/issues/21860#issuecomment-1613592351

**Comment by Santhosh-Sellavel** [comment]
The user detail ar the top is not clickable. This does not feel like a bug to me, can you check internally @NicMendonca?

@Expensify/design Should we do something here?

**Comment by NicMendonca** [comment]
@Santhosh-Sellavel should it be clickable?

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel should it be clickable?

Not sure whether it's intentionally left unclickable please check with the Product Management team!

**Comment by NicMendonca** [comment]
Thanks @Santhosh-Sellavel! I am going to close. I agree this isn't a bug
