### ISSUE TITLE
Web -  Scroll becomes hidden when writing a long message in IOU section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click on the plus sign :heavy_plus_sign:
2. Select "Request" and enter the desired number, then click "Next"
3. Add an email and click "Next"
4. In the IOU section, click on the requested money.
5. Write a long message (copy and paste the Bug report multiple times in the message). The scroll becomes hidden after reaching a certain height, but the cursor still works.

## Expected Result:
The scroll should not become hidden in the IOU section after writing a long message.

## Actual Result:
In the IOU section, when writing a long message, the scroll becomes hidden after reaching a certain height

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (3)](https://github.com/Expensify/App/assets/93399543/5c8f5e1c-dda4-4c73-8106-e7893694ec8b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687946141841019
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Linking similar issue https://github.com/Expensify/App/issues/19389

**Comment by conorpendergrast** [comment]
Yes, I think we're already addressing this in https://github.com/Expensify/App/pull/21664, so this would count as a duplicate report. Closing!
