### ISSUE TITLE
Web - Does no show any member on invite member to policy

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Click on New workspace button
3. Go to Settings > Workspaces > Members
4. Click on invite button
5. Type email with capital latter and which is not present in list
6. Click on Next button
7. Click on invite button which redirects user to Members screen

## Expected Result:
Should show members which is part of policy

## Actual Result:
Does no show any member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9c7565fc-f743-412f-bfb4-30b07b373cfc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687943695819349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Linking similar issue https://github.com/Expensify/App/issues/21804

**Comment by sophiepintoraetz** [comment]
@kbecciv - you're right - i think this is essentially a dupe so closing in favour of https://github.com/Expensify/App/issues/21804.
