### ISSUE TITLE
Web - inconsistent rendering of error message on magic code component

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out
2. Enter email
3. Enter wrong magic code
4. Login and go to contact methods
5. Enter an email > verify
6. Enter wrong magic code

## Expected Result:
Should or should not have close icon in both the error message boxes

## Actual Result:
Has close icon in contact methods page but not in main login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (2)](https://github.com/Expensify/App/assets/93399543/184a33d8-54b3-42bf-bc09-8e29699b2a75)

https://github.com/Expensify/App/assets/93399543/37037de4-2ef0-4829-89dc-583521f54bee

https://github.com/Expensify/App/assets/93399543/e7156704-7c94-4da1-a16c-82915c1f9bb0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687945919888799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
inconsistent rendering of error message on magic code component (close icon)
### What is the root cause of that problem?
Root cause of the issue is the use of Offline feedback flow in code verification page. `<OfflineWithFeedback/>` gives a close icon to close the error message and we do not have a prop to control this.
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L138-L143
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L166-L171
### What changes do you think we should make in order to solve the problem?
We can create a boolean prop to control the visibility of close icon and render it conditionally.
By replacing this https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/components/OfflineWithFeedback.js#L125-L134
with this
```js
{ props.shouldShowCloseIcon && <Tooltip text={props.translate('common.close')}>
    <PressableWithoutFeedback
        onPress={props.onClose}
        style={[styles.touchableButtonImage]}
        accessibilityRole="button"
        accessibilityLabel={props.translate('common.close')}
    >
        <Icon src={Expensicons.Close} />
    </PressableWithoutFeedback>
</Tooltip>}
```
<details>
  <summary>Results</summary>
https://github.com/chiragxarora/pdf-download/assets/54641656/1e82bbbc-3995-452a-a1f6-92b4f5e9eecb
</details>
### What alternative solutions did you explore? (Optional)
Or we could remove the offline feedback flow all together and we can simply use a `<FormHelpMessage/>` and render the error when there is one. (We do something similar to this on sign in page)

**Comment by muttmuure** [comment]
Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1688404270491189) but I am not sure this is a problem. RBR as a philosophy only engages when you are logged in

**Comment by muttmuure** [comment]
There isn't really a need to be able to dismiss the message on the sign in page.
