### ISSUE TITLE
[$1000] Tooltip position is inverted if we open user avatar, close the avatar and hover on copy to clipboard for contact

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. open any report
3. Click on user avatar to open user details
4. hover and click on 'copy to clipboard' besides user contact
5. Click on user avatar to open avatar in preview
6. Zoom in on the avatar
7. Close the avatar preview
8. Hover again on 'copy to clipboard' besides user contact to observe that tooltip position is now at the bottom, rather than top of the mouse.
## Expected Result: 
App should display tooltip at the top of the mouse hover
## Actual Result: 
App displays the tooltip at the bottom of the mouse hover when we open user avatar in preview, zoom in and close the preview.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9eed21b6-bc0e-420a-ab42-aacad7d612d7

https://github.com/Expensify/App/assets/43996225/0dbcd3b9-d101-42fc-8cb0-be29f024655d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687763166967749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01380d475f1a014bef</li>
        <li>Upwork Job ID: 1675905375165431808</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by anmurali** [comment]
I am not sure why this is a bug. In both cases the tooltip is perfectly readable and associated with the `copy to clipboard` icon clearly. The fact that the tooltip appears on top of the mouse vs. bottom seems trivial.

**Comment by anmurali** [comment]
Ok confirmed that it is not "inverted" but rather we want to show it on top to keep the UI consistent.

**Comment by mentamarindos** [comment]
I wouldn't call it "inverted", but responsive. It adjusts to the height of the screen, which is perfectly fine.

**Comment by anmurali** [comment]
Yea, I agree. I am still conflicted that this doesn't feel like a bug. Asked @mananjadhav for his opinion

**Comment by mananjadhav** [comment]
I think we shouldn't do anything here. Tooltips can open on either direction, and it adjusts the position based on the height, pointer in the viewport, items focused around the hovered object. So we can't really say it has to be uniform on every location. I can see no alignment issues too between the content, the arrow and the bubble.

@anmurali  I think we should just close this one.
