### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000]  Inconsistency - Link previews have different border color than quotes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Send a quote message in any chat. ex - `> hello`.
3. Send a link. ex - `google.com` and wait for the link preview to appear.
4. Notice that the left border has a different color in both cases.

## Expected Result:
 Border color should be consistent for both link previews and quote.

## Actual Result:
Border color is different for both link preview and quote.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/de42dbc7-a466-45f3-84a1-cf3b68ec1c43

**Expensify/Expensify Issue URL:**
**Issue reported by:** ~@Nikhil-Vats~ Bortman
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687966486390789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01034485de0b01882f</li>
        <li>Upwork Job ID: 1676724101797347328</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Left border color for link previews is inconsistent with blockquote's left border color.
### What is the root cause of that problem?
We are using a different color for link previews left border.
https://github.com/Expensify/App/blob/a23d1614c0e60f99dd51cf6f4fd08f65248203d1/src/styles/styles.js#L3364-L3369
https://github.com/Expensify/App/blob/a23d1614c0e60f99dd51cf6f4fd08f65248203d1/src/styles/styles.js#L2680-L2681
### What changes do you think we should make in order to solve the problem?

We should just change the border color used for link previews to be the same as other one - `themeColors.border`.
Optionally, we can also remove the function `getTransparentColor` which was added for link previews border color and is only used there.
### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment]
[My proposal above.](https://github.com/Expensify/App/issues/21882#issuecomment-1613541578)

**Comment by mallenexpensify** [comment]
@Nikhil-Vats you mean these two are different colors, right?
<img width="390" alt="image" src="https://github.com/Expensify/App/assets/22508304/ab17a3be-cc72-44c8-92ef-5640c48f904a">

**Comment by Nikhil-Vats** [comment]
Yes @mallenexpensify .

**Comment by Nikhil-Vats** [comment]
@mallenexpensify This was reported by Shawn [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687864307494929?thread_ts=1687852728.549549&cid=C01GTK53T8Q) and @wojtus7 provided confirmation [here](https://expensify.slack.com/archives/C049HHMV9SM/p1688029001871089?thread_ts=1687966486.390789&cid=C049HHMV9SM).

**Comment by mallenexpensify** [comment]
Thanks @Nikhil-Vats, moving this along

**Comment by mallenexpensify** [comment]
@aimane-chnaif , please review @Nikhil-Vats 's proposal above

**Comment by marcochavezf** [comment]
Thanks for the review @aimane-chnaif, assigning @Nikhil-Vats 🚀

**Comment by Nikhil-Vats** [comment]
@aimane-chnaif @mallenexpensify @marcochavezf [PR](https://github.com/Expensify/App/pull/22677) is ready for review.

**Comment by Nikhil-Vats** [comment]
@thienlnam Melv incorrectly identifies the reporter as it doesn't consider '-' in the GH handle for reporter only (it works well for assignee). Is this a known issue?

@mallenexpensify This issue was actually reported by @shawnborton [here](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1687852728.549549). I just created the bug report for it so you can remove me from the issue description as bug reporter.

**Comment by mallenexpensify** [comment]
Thanks @Nikhil-Vats , I opened an internal GH to address the `-` bug.  Removed  ya from the OP for bug reporter too.

**Comment by mallenexpensify** [comment]
@aimane-chnaif and @Nikhil-Vats paid $1500 each, inc. urgency bonus. Apologies for the delay, I was OOO a couple days.
@aimane-chnaif , please fill out the checklist above.
https://github.com/Expensify/App/issues/21882#issuecomment-1635953496

**Comment by mallenexpensify** [comment]
For auditing, posting the format below

Issue reporter: none
Contributor: @aimane-chnaif $1500 paid via Upwork, inc. urgency bonus
Contributor+: @Nikhil-Vats $1500 paid via Upwork, inc. urgency bonus

@aimane-chnaif can you please fill out the checklist above so we can close this issue? Thx
