### ISSUE TITLE
[HOLD for  #21574] Web - Group participants shows primary contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app (win/chrome)
2. Create a new group, using a secondary email contact as the participant
3. The new group shows the primary contact after pulling information from the backend. The optimistically set data returns the secondary contact.

## Expected Result:
Consistency between the optimistically set and the API-returned participant information. I.e., show the secondary contact if this is what was added by the user.

## Actual Result:
Primary contact information is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bdb4432f-0651-44ba-8a45-e1e2f9c0864e

https://github.com/Expensify/App/assets/93399543/ab5890bd-f281-4e1b-ad34-5a49b8e597fe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687953832748359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
might be related to https://github.com/Expensify/App/issues/21574
cc @parasharrajat

**Comment by maddylewis** [comment]
@Nikhil-Vats - when you say this issue is related to https://github.com/Expensify/App/issues/21574, are you suggesting we wait for a fix for #21574 before this one should be worked on?

**Comment by Nikhil-Vats** [comment]
I think both point out the same issue with different expected behaviour. So if #21574 is fixed this one would be fixed too.
We can put this on hold or even close it. 
@parasharrajat can confirm.

**Comment by maddylewis** [comment]
cool, moving to `weekly` in the meantime.

**Comment by maddylewis** [comment]
@parasharrajat - i see this issue is closed now https://github.com/Expensify/App/issues/21574

what is your recommendation? should we move forward with fixing #21888?

**Comment by maddylewis** [comment]
this has been reopened and is now being treated as a `new feature`. - https://github.com/Expensify/App/issues/21574

**Comment by maddylewis** [comment]
asking about this here - https://expensify.slack.com/archives/C01GTK53T8Q/p1689799369906999?thread_ts=1687975409.953669&cid=C01GTK53T8Q

**Comment by maddylewis** [comment]
closing based on this suggestion - https://expensify.slack.com/archives/C01GTK53T8Q/p1689834453316049?thread_ts=1687975409.953669&cid=C01GTK53T8Q
