### ISSUE TITLE
Web - Incorrect avatar is shown in search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Search for a user you have not interacted with yet (i.e. no chats)

## Expected Result:
The avatar should match what is actually set.

## Actual Result:
The avatar is incorrect: a random avatar is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/30aab99e-620b-4abb-b90c-d93d567e5862

https://github.com/Expensify/App/assets/93399543/f8d37287-af9f-492e-bcff-a28659ff2b1a

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687954685119619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
@trjExpensify / @Beamanator I noticed #20572 seems suspiciously similar to this issue, which makes me wonder if the solution is already being worked on. I'd love your thoughts!

**Comment by trjExpensify** [comment]
I think it's a dupe yeah. I also think we can close that other one. Commented there on that though!
