### ISSUE TITLE
[$1000] Navigating back after leaving A PUBLIC room takes you back to the room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PreCondition: To reproduce this in Desktop Web resize your window to half where only the LHN is displayed so you can get the back button when going into chats.
1. Create a Public Room
2. Go to details of the Room by clicking the header of the room
3. Click on leave room.
4. you will be directed to the Concierge chat.
5. Now Click on the back button on the top.

## Expected Result:
Navigating back does not take you to the room

## Actual Result:
 Navigating back takes you to the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c43fd1cf-e0cf-4962-92b1-f363315ed19c

https://github.com/Expensify/App/assets/93399543/c62b6265-d2ca-4eda-a8e3-97b4f0e04c34

https://github.com/Expensify/App/assets/93399543/b2a74806-b7ea-45a5-a083-7411a8d874fe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687949615574319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ec7bcc38d09ed98</li>
        <li>Upwork Job ID: 1674623225396166656</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Yes, the same thing happens with threads as well when you leave them. cc @mountiny in case you have any thoughts, since this is navigation-related.

**Comment by puneetlath** [comment]
Yep, good catch @Nodebrute. Closing in favor of that issue, since it is much older.
