### ISSUE TITLE
Chat - Deleting threads doesn't remove messages and creates  [Deleted message] title threads

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into new dot
2. Go to any chat and send a message
3. Long press it and click on reply in a thread
4. Send another message in the thread
5. Delete the child message send in the thread
6. Go back to the parent message and delete it too
7. Observe how a [Deleted message] remains in the chat history and also a [Deleted message] thread chat in chat list.

## Expected Result:
Deleting both parent and child messages in threads should delete all messages

## Actual Result:
A [Deleted message] remains in the chat history and also a [Deleted message] thread chat in chat list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3786f457-0cb5-46cf-854f-d55259fdc586

https://github.com/Expensify/App/assets/93399543/51f2c72c-400d-47d5-8f3e-4f3ceb70203b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687968420315699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
> A [Deleted message] remains in the chat history and also a [Deleted message] thread chat in chat list.

That seems like expected behaviour to me! You've deleted two messages, one "normal", one in "thread" so it feels like a good audit trail to display when both have been deleted
