### ISSUE TITLE
[$1000] Sending money to Unregistered users inconsistencies - first shows “sent money” and then shows error on detail page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Search and search for an unregistered phone number (Eg. try this one: +918969862299 if you have none. Its unregistered)
2.  Send few messages
3. Send money.
4.  Request money
5. Verify if you can send and request money
6. Verify if you can see blank on the chat
7. Go to search and verify if you see ‘sent [dollar amount] elsewhere’ message
8. Click on that message
9. Verify if you see the error : “Unexpected error, please try again later”

## Expected Result:
User A should not be able to send or request money from unregistered users

## Actual Result:
User A was able to send money with “sent [dollar amount] message” on search proving money was sent.
There was an error when clicking on detail page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b07d841a-8819-41d7-a3ca-b1018f9b3953

https://github.com/Expensify/App/assets/93399543/fd74cc09-46a6-4151-9f21-5986a3d45aa4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687983017917349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca870d4650f50179</li>
        <li>Upwork Job ID: 1679111421519994880</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Slammed with bug reports. I'll close the loop on these today.

**Comment by multijump** [comment]
When request money to unregistered user(with phone number), backend return error and won't get any data from Onyx.
I think it is correct case  so don't think it is issue.
And send money feature was disabled so we can ignore it.
What do you think? @Santhosh-Sellavel 
If you think it is still issue, I will create proposal.
Thanks.

**Comment by Santhosh-Sellavel** [comment]
Yes @JmillsExpensify We disabled Send money recently, lets close this one out, thanks!

**Comment by JmillsExpensify** [comment]
Haha, initiative led by yours truly. I was actually thinking that the same issues might also exist in `Request Money`, though I agree with ya'll. The issue reporter can create another bug report in Slack if that's the case.
