### ISSUE TITLE
[$1000] Web -  Local time and email details are not being shown for new chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Start a chat with a new contact
2. Click on the header to open the side panel

## Expected Result:
Local time and email should be shown

## Actual Result:
Local time and email is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (5)](https://github.com/Expensify/App/assets/93399543/7131f949-731f-4c01-ae66-e18001092e0c)

https://github.com/Expensify/App/assets/93399543/a35ce7fd-270c-4c53-b6ec-8d7c8fad6d43

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687980385505689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe50ccba1d2af528</li>
        <li>Upwork Job ID: 1675922475956195328</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment]
How about the email?

**Comment by Nathan-Mulugeta** [comment]
Yes both accounts are valid and account B even replied but email is still
not shown. I reproduced it today.  @fedirjh <https://github.com/fedirjh>

**Comment by Nathan-Mulugeta** [comment]
Check this out @fedirjh I just tested this right now, is this expected? 

https://github.com/Expensify/App/assets/111440031/85fb6105-19c0-46b6-ab8e-d7a10d93c1f0

**Comment by Beamanator** [comment]
Yes this is expected - since the users don't "know" each other, we won't share local time, email, or pronouns with each other at this point

@muttmuure I think we might need to add a test rail step for this :D
