### ISSUE TITLE
[HOLD] Web - Cursor gets half hidden on Welcome message page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21905]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace > go to announce > click on header
2. Click on Settings > welcome message
3. Type something and hit enter key

## Expected Result:
Cursor should be fully visible

## Actual Result:
Cursor gets half hidden when a new line is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fecd84dd-f59f-49cb-8bcb-7f7097600ab3

https://github.com/Expensify/App/assets/93399543/d9a41e21-5d65-4426-961d-47c35cd2a234

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687982750576449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e84d49c89d9b9d8e</li>
        <li>Upwork Job ID: 1674610343722532864</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We get the required height of the `TextInput` here
https://github.com/Expensify/App/blob/3b721c4cbf1714720d529a9ef5b81f14e1cb699c/src/components/TextInput/BaseTextInput.js#L384-L394

We use `Text` component and its height doesn't increase when the text is ended with line break.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can add space character to the end of the text if text is ended with `line-break`.

```
    {this.state.value ? this.state.value + (this.state.value.endsWith('\n') ? ' ' : '') : this.props.placeholder}
```

This works as expected.

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)
In stead of above code, we can use add '\n' character to the text.

```
    {this.state.value ? this.state.value + '\n' : this.props.placeholder}
```

**Comment by sophiepintoraetz** [comment]
replicated!
https://github.com/Expensify/App/assets/42940078/20397591-a9ba-4944-8515-9488764d781a

**Comment by Nathan-Mulugeta** [comment]
Isn't that issue on task description but this one is on welcome message page @aimane-chnaif

**Comment by s-alves10** [comment]
[My proposal](https://github.com/Expensify/App/issues/21905#issuecomment-1613869581) is a general solution for auto-grow `TextInput` component

**Comment by sophiepintoraetz** [comment]
I which case, I'll put this issue on hold for https://github.com/Expensify/App/issues/21271 and @Nathan-Mulugeta you can still get the reporting bonus.

**Comment by Nathan-Mulugeta** [comment]
Thanks @sophiepintoraetz that'll be great. Have you noticed that #21271 is closed?

**Comment by fabriziobertoglio1987** [comment]
I was working on this issue during the weekend. I posted my proposal at https://github.com/Expensify/App/issues/21271#issuecomment-1617399591. Thanks

**Comment by sophiepintoraetz** [comment]
Ah, apologies, I've been turned around by the closed issue. Seeing as https://github.com/Expensify/App/issues/21205 did not fix this issue, and the timeline says Applause (22 June) reported this bug before Nathan (29 June), @Nathan-Mulugeta, you are not eligible for the reporting bonus, I'm afraid.

@fabriziobertoglio1987 and @s-alves10 - I see you have dropped proposals in #21271 so let's continue the conversation there.
