### ISSUE TITLE
Web -  Member's list of a PUBLIC room can be accessed by a user if the user is a member of the workspace that is used to create the room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A: Create a new workspace and Add User B as a member
2. user A: Create a PUBLIC room using the new workspace and Invite user B
3. User B: Join the room and go to details of the room and click on members.

## Expected Result:

The expected result is that domain members are only visible to admins not members.

## Actual Result:
The member list is accessed by users that are a member of the workspace

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3945fd45-ca0d-434f-8f7f-138400de2876

https://github.com/Expensify/App/assets/93399543/810c6750-912a-42a3-836e-68dd02476085

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688004402664509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I assume this is expected but I'll check on this!

**Comment by Christinadobrzyn** [comment]
Asking in Slack what we're expecting to see here - https://expensify.slack.com/archives/C049HHMV9SM/p1688156969981679?thread_ts=1688004402.664509&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment]
I assume it's expected that all members of a PUBLIC workspace can see each other but asking the team here - https://expensify.slack.com/archives/C01SKUP7QR0/p1688401880189069

**Comment by Christinadobrzyn** [comment]
It sounds like it is expected that workspace members are visible to all members including admins. So this would be a feature request if you'd like to go ahead with this change feel free to follow the steps here: 

https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_CREATE_A_PLAN.md

or here

https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs
