### ISSUE TITLE
Web - Inconsistency: When inviting a user to a Public room user detail is hidden for new user but not for old users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a public room.
2. invite a new user(no chat history) and an old user to the room
3. Join the room with the new and old users.
4. Now go to the room details by clicking the header and go to members.
5. notice that on the member's list hidden is shown for the New user and the user detail is shown for the old user,

## Expected Result:
Consistency when showing the user detail

## Actual Result:
 Inconsistency when showing the user detail

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/91161ea5-3dde-4808-93d4-815b9d459c1e

https://github.com/Expensify/App/assets/93399543/416b8553-5dde-4213-b700-e849a7fc4755

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688002278899719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Same as [this convo](https://expensify.slack.com/archives/C049HHMV9SM/p1688145026211989?thread_ts=1687865928.997579&cid=C049HHMV9SM), it's expected behaviour to hide the primaryLogin of a member you don't know. Closing!
