### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Compose box is stuck with non removable space if we add space, click on upper arrow to edit and save edited message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Enter space in compose box
5. Click on upper arrow until last message enter edit made
6. Save the edit message with or without any changes
7. Observe that app again focuses to compose box, there is already a space entered in compose box, try to delete it and observe that it is not getting deleted (2 ways to say there is space in compose box, pencil icon is displayed in LHN and 'Write something' placeholder is not displayed)
## Expected Result:
App should allow to remove space in compose box on refocus after editing any message
## Actual Result:
App should allow to remove space in compose box if we add space, click upper arrow to edit any message and save that message with or without any changes
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d6345922-2ffa-4354-9c77-b547d8d9db28

https://github.com/Expensify/App/assets/43996225/d53de273-2fe2-433d-a27d-b81a2e223e4a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687785005400489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f762cbe49f78f72</li>
        <li>Upwork Job ID: 1675898254628552704</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
can't reproduce 

https://expensify.slack.com/archives/C049HHMV9SM/p1688164226012059?thread_ts=1687785005.400489&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
Still getting clarification in thread.

**Comment by kevinksullivan** [comment]
Was able to reproduce with some guidance in slack.

**Comment by s77rt** [comment]
@kevinksullivan Isn't this supposed to be an open issue?

**Comment by monarch228314** [comment]
As an experienced web developer with a diverse skill set and over 13 years of experience, I am confident in my ability to provide an ideal solution for the React Native migration project at Expensify. I have a proven track record of delivering elegant solutions in minimal time, and my expertise in software architecture and user interface design will enable me to effectively address the problems related to the migration. I will thoroughly analyze the GitHub issue and propose a technical explanation of the changes I will make, ensuring that the final solution meets the requirements outlined in the job posting.

**Comment by monarch228314** [comment]
I don't like this way

**Comment by monarch228314** [comment]
I'd like to handle outsite of upwork.

**Comment by monarch228314** [comment]
Here is my solution about your job posting.
As an experienced web developer with a diverse skill set and over 13 years of experience, I am confident in my ability to provide an ideal solution for the React Native migration project at Expensify. I have a proven track record of delivering elegant solutions in minimal time, and my expertise in software architecture and user interface design will enable me to effectively address the problems related to the migration. I will thoroughly analyze the GitHub issue and propose a technical explanation of the changes I will make, ensuring that the final solution meets the requirements outlined in the job posting.

**Comment by s77rt** [comment]
@monarch228314 Please checkout the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by kevinksullivan** [comment]
Sorry @s77rt , missed that this was closed. I opened it.

**Comment by kevinksullivan** [comment]
@monarch228314 thanks, but this is our process, and we don't make exceptions.

**Comment by s77rt** [comment]
@hungvu193 Thanks for the proposal. Your RCA is correct. The solutions make sense, let's go with option 2 (do not allow going to edit mode unless the input is really empty).

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by iwiznia** [comment]
Agree on the solution 2

**Comment by kevinksullivan** [comment]
Offer sent to @dhanashree-sawant

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/8064
- The offending PR has been commented on: https://github.com/Expensify/App/pull/8064#discussion_r1262306002
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1689244886574789
- Determine if we should create a regression test for this bug: No

**Comment by kevinksullivan** [comment]
Paying out tomorrow

**Comment by iwiznia** [comment]
Seems this is mostly ready, so not unassigning myself, but if this does not get closed, @kevinksullivan please unassign and re-assign another engineer since I am going on sabbatical

**Comment by kevinksullivan** [comment]
All set
