### ISSUE TITLE
'Confirm Task' button is not disabled after system throws 'error assigning task' error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat/ start a new chat
2. Click on 'Actions' icon
3. Click on 'Assign task' button
4. Enter title > click on 'Next' button
5. Click on 'Confirm task' button
## Expected Result:
 Confirm task button shouldn't be clickable once the system throws an error saying 'error assigning task'
## Actual Result:
Confirm task button is clickable once system throws an error
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3640439f-6eab-4cc9-aa57-8ed47a75595f

https://github.com/Expensify/App/assets/43996225/0c201d16-ca5b-481b-8d8f-3c1befd596e4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687797690671519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Confirm Task' button is not disabled after system throws 'error assigning task' error message.

### What is the root cause of that problem?
We does not check there is a error or not before click `Confirm task` in `NewTaskPage.js`.

### What changes do you think we should make in order to solve the problem?
We should disable if there is a error.
```js
	<FormAlertWithSubmitButton
		isAlertVisible={!_.isEmpty(errorMessage)}
+   	isDisabled={!_.isEmpty(errorMessage)}
		message={errorMessage}
		onSubmit={() => onSubmit()}
		enabledWhenOffline
		buttonText={props.translate('newTaskPage.confirmTask')}
		containerStyles={[styles.mh0, styles.mt5, styles.flex1, styles.ph5]}
	/>
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by puneetlath** [comment]
Unable to reproduce the error flow. Asking in slack.

**Comment by puneetlath** [comment]
Going to close for now since it's no longer reproducible. I asked @Natnael-Guchima to ping me in the slack thread if he's able to reproduce again and I'll reopen if so.
