### ISSUE TITLE
 Inability to select the composer box by clicking slightly below the "Write something..." text within the box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Click on a message
3. Attempt to select the composer box by clicking just below the "Write something..." text within the box
## Expected Result:
When clicking slightly below the "Write something..." text within the composer box, the box should be selectable and ready for input.
## Actual Result:
The composer box is not selectable when clicking slightly below the "Write something..." text within the box
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/81298fec-4c3f-4c74-8843-98429eb633de

https://github.com/Expensify/App/assets/43996225/9d8e3d30-330d-4bdb-ac48-380ed3aec8fa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687791507178979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
Checking internally - https://expensify.slack.com/archives/C01SKUP7QR0/p1688463967049609 - this sounds like intentional design rather than a bug
