### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] [HOLD] Context menu from LHN is visible even if report page is opened on resize

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Right click an option in LHN.
2. Resize the window to small while the menu is still open
## Expected Result:
 The menu should either stay open and LHN should be visible or the menu should close and report screen should be visible.
## Actual Result:
The menu as well as report screen is visible while the action LHN option is hidden.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fea25aad-b0a1-4257-a240-3976b5440093

https://github.com/Expensify/App/assets/43996225/2623f720-eb64-453f-8a89-1f74a92caaec

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687798787632109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdbc23c40a03345b</li>
        <li>Upwork Job ID: 1681398364212076544</li>
        2023-07-18<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
<li>esh-g | Reporter | 25767058</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
I think we should put this on hold for this issue: https://github.com/Expensify/App/issues/20370#issuecomment-1599370592

**Comment by maddylewis** [comment]
holding for - https://github.com/Expensify/App/issues/20370#issuecomment-1599370592

**Comment by maddylewis** [comment]
okay this is closed now - https://github.com/Expensify/App/issues/20370#issuecomment-1599370592

I'll add the `External` label so a C+ can confirm if we still need to fix this one.

**Comment by maddylewis** [comment]
@sobitneupane - this issue was on hold for https://github.com/Expensify/App/issues/20370

is this something that still needs to be addressed? or, did the fix for https://github.com/Expensify/App/issues/20370 resolve this bug? lmk - thanks!

**Comment by sobitneupane** [comment]
Will review shortly.

**Comment by sobitneupane** [comment]
@spcheema How are we handling it for Report Context Menu. Whenever, I resize the window, the context menu goes away.


https://github.com/Expensify/App/assets/25876548/261f23d0-a8de-4688-b50b-8c9c76180e58

**Comment by stitesExpensify** [comment]
Agreed, @spcheema proposal looks good to me

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Right click an option in LHN to open context menu.
2. Resize the window to small such that LHN is hidden.
3. Verify right click context menu disappeared on window resize.
4. Now go back to LHN menu, again right click on any item to open context menu
5. Resize window from small to wide
6. Verify context menu disappeared.

**Comment by maddylewis** [comment]
### Payments:
- [ ] @esh-g ($250 reporting bonus paid via Upwork)
- [ ] @spcheema (Contributor - $1500 paid via Upwork)
- [ ] @sobitneupane (C+ - $1500 paid via NewDot)
______
- Contributor hired - July 26
- PR merged - July 28
- Eligible for urgency bonus

**Comment by maddylewis** [comment]
@sobitneupane is receiving payment via NewDot so i believe we are all set to close this one out.

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/21929#issuecomment-1679223811

**Comment by JmillsExpensify** [comment]
Reviewed the details for @sobitneupane. $1,500 approved for payment via NewDot based on BZ summary.
