### ISSUE TITLE
Desktop - Concierge notification on phone, but not in the open desktop chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message to concierge

## Expected Result:
See concierge typing a reply, then see their new message in the chat

## Actual Result:
See concierge typing, then receive a notification with the new message on my phone, but I don't see the new message in the chat at all. It only appears after leaving the chat and coming back.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** Neil Marcellini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688013946103199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
QA team is not testing Concierge, added Need Reproduction label. Thank you

**Comment by michaelhaxhiu** [comment]
@neil-marcellini so just to clarify, did you have Concierge open on Desktop & Mobile simultaneously? Mind expanding a little more for me to try and reproduce?

**Comment by neil-marcellini** [comment]
Answered in Slack.

**Comment by michaelhaxhiu** [comment]
I'm struggling to reproduce this one and going to close. Let's re-open or re-post if this happens again 👀
