### ISSUE TITLE
[$1000] Timezone page switch button doesn’t work.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with a new account.
2. Navigate to settings.
3. Go to Workspaces and create a workspace.
4. Open manage members page.
5. Tap invite.
6. Invite a new user.
7. Go to your profile.
8. Open timezone.
9. Tap on the switch button above.
## Expected Result: 
Button should work.
## Actual Result: 
The button doesn't work.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/08fde9d7-a09e-433f-9f32-1afa687b9344

https://github.com/Expensify/App/assets/43996225/bc273597-3368-4fa8-97f6-4b50dabc6258

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687815038784319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b37e4bb195d4a4c8</li>
        <li>Upwork Job ID: 1677436478629629952</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by sakluger** [comment]
@roryabraham is there any chance this is related to https://github.com/Expensify/App/pull/20220? The issue is the same, but the context is completely different, so probably not related but figured I'd ask.

**Comment by sakluger** [comment]
I also asked for more details on the Slack thread around platforms where this occurs.

**Comment by sakluger** [comment]
No response back in Slack.

**Comment by sakluger** [comment]
Reproduced by Applause in Andoid app and Android chrome.

**Comment by alexxxwork** [comment]
Can't reproduce on native android and android chrome (using real device). But noticed slow performance of timezone select page

**Comment by roryabraham** [comment]
> @roryabraham is there any chance this is related to https://github.com/Expensify/App/pull/20220? The issue is the same, but the context is completely different, so probably not related but figured I'd ask.

It's not impossible, but that PR was a revert of a huge migration which has since been re-done. So we can't put the worms back in that can 🙃

**Comment by sakluger** [comment]
Still waiting for proposals.

**Comment by roryabraham** [comment]
Requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1689039353288009?thread_ts=1689034140.689229&cid=C9YU7BX5M

**Comment by Tushu17** [comment]
@sakluger This isn't a duplicate report, So is this bug eligible for reporting compensation?
