### ISSUE TITLE
Cursor is set as pointer on the input field bottom border.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop web.
2. Navigate to search page.
3. Hover over input field bottom border.
4. Observe that cursor is set as 'pointer'.
## Expected Result: 
The cursor should not be set as 'pointer' over the input field's bottom border.
## Actual Result: 
The cursor is set as 'pointer' over the input field's bottom border.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.34-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/05ac6333-b4fe-4108-936c-1f8100841b17

https://github.com/Expensify/App/assets/43996225/28c40a4c-bb11-408c-a8bc-16ce1b82025f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687813658014789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
still reviewing this

**Comment by NicMendonca** [comment]
This feels like it is polish or preference that the cursor should appear a few pixels lower. @honnamkuan looking forward to your update in the other issue, but I think this one can be closed
