### ISSUE TITLE
No tooltip for Copy and download in 2FA page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > 2FA
2. Hover over copy and download buttons
3. Click next and hover over the Copy button and the icon
## Expected Result: 
There should be a tooltip for copy button and icon just as there is everywhere in the app
## Actual Result: 
There is no tooltip for copy button and icon

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8bc5890-3607-4ab3-b038-803c56ada472

https://github.com/Expensify/App/assets/43996225/fb74a93b-511a-48ae-9876-af993338e2e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687822861332979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment]
Why should the buttons have a tooltip? Plenty of buttons in the app don't have tooltips, including `Next` in key creation flows. Closing. Please open a discussion in open-source if you disagree.
