### ISSUE TITLE
iOS: Scanning QR code does not take you to the Scanned page if you are already in another page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app
2. Open any chat
3. Now go out, Open your phone Camera, and scan a public room QR code from another Account.
4. Notice that Scanning the QR code takes you to the App but does not take you to the scanned page.
If you were on the main page before scanning, scanning the QR code will take you to the scanned page.
## Expected Result: 
scanning the QR code will take you to the scanned page.
## Actual Result: 
scanning the QR code does not take you to the scanned page.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/972e2b5b-3326-4f13-a8ec-f36815c42fe2

https://github.com/Expensify/App/assets/43996225/0bc3c8d3-c6ed-475b-8a6a-75d9c8a7c59f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687816327203039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!
