### ISSUE TITLE
[aimane-chnaif please complete] [HOLD for payment 2023-07-26] [$1000] Web - The user added to workspace can see invite page but can't add the members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A - Create a workspace and add user B
2. Now go to workspace's invite member page, copy the url after the base - something like - `/workspace/<workspace id>/invite`
3. Now go to different browser where user B is logged in.
4. Append the copied part to url after the base urls, ex - `https://staging.new.expensify.com/workspace/<workspace id>/invite`
5. Notice the User B can see the invite page
6. Try inviting a user to the workspace by following the workflow

## Expected Result:
If user doesn't have permission to invite new members to workspace, the page should provide the error message

## Actual Result:
User can see the invite page and can invite the user but after adding gives the error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1bbea3b8-510d-4e11-8b5f-3eb1a1e14f59

https://github.com/Expensify/App/assets/93399543/4b32996b-6632-4d13-9ed9-4132900790cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688059822067529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148a57d74a819953e</li>
        <li>Upwork Job ID: 1676321039486058496</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
by @BhuvaneshPatil
### Please re-state the problem that we are trying to solve in this issue.
The user added to workspace can see invite page but can't add the members
### What is the root cause of that problem?
There are two ways to go to invite members page in workspace -
1. Using workspace settings page - go to workspace -> members -> invite
2. Directly pasting the link as mentioned
For the first way, we are checking if the current user has access to workspace settings -
https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/pages/workspace/WorkspaceInitialPage.js#L178-L182
We are providing error if the `props.policy` is empty.
But in the case of directly pasting link we land on `WorkspaceInvitePage` , we don't have any access checks for this.
### What changes do you think we should make in order to solve the problem?
We shall wrap the workspace invite page with `FullPageNotFoundView`, that will display error if `policy` is empty.
We shall create a new error message for `subtitleKey`.
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
> ## Proposal
> 
> by @BhuvaneshPatil
> ### Please re-state the problem that we are trying to solve in this issue.
> 
> The user added to workspace can see invite page but can't add the members
> ### What is the root cause of that problem?
> 
> There are two ways to go to invite members page in workspace -
> 
>     1. Using workspace settings page - go to workspace -> members -> invite
> 
>     2. Directly pasting the link as mentioned
>        For the first way, we are checking if the current user has access to workspace settings -
>        https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/pages/workspace/WorkspaceInitialPage.js#L178-L182
>        
>        We are providing error if the `props.policy` is empty.
>        But in the case of directly pasting link we land on `WorkspaceInvitePage` , we don't have any access checks for this.
> 
> 
> ### What changes do you think we should make in order to solve the problem?
> 
> We shall wrap the workspace invite page with `FullPageNotFoundView`, that will display error if `policy` is empty. We shall create a new error message for `subtitleKey`.
> ### What alternative solutions did you explore? (Optional)

This proposal was written for `WorkspaceInvitePage`, but as pointed by @ChengDzun , if we want to increase the scope for this and add other pages

expanding upon the proposal - 
We can add similar logic to other places as well as suggested above. i.e `WorkspaceInvitePage`

**Comment by sonialiap** [comment]
Expected result: only admin can access workspace sesttings, including the invite page. So anyone else who tries to follow the workspace link would get an error.

I cannot reproduce the reported behavior. When I try to follow the URL from account A's workspace in account B I get the `Oops, this page cannot be found` message

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/17131195/c3196c7b-ae18-4836-b9c5-56204753aad2">

**Comment by sonialiap** [comment]
We had a similar issue here for accessing the Workspace > Settings page via a copied URL. Linking in case it's useful to selecting a solution to this issue https://github.com/Expensify/App/issues/18910

**Comment by sonialiap** [comment]
@aimane-chnaif what do you think of the above proposals?

**Comment by BhuvaneshPatil** [comment]
Sure @aimane-chnaif , I will look through the pages and will update you here.

**Comment by BhuvaneshPatil** [comment]
Here are my findings - 
1. `WorkspaceMembersPage`
2. `WorkspaceInvitePage`
3. `WorkspaceInviteMessagePage`
4. `ReimbursementAccountPage`
https://github.com/Expensify/App/blob/401b4595911afb27bb67144a59e263c08cf352e5/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L333-L343

We can add conditions here, to check if the current user is policy owner.

**Comment by BhuvaneshPatil** [comment]
@sonialiap 

Just to confirm there are two different roles other than user - `Admin` and `Owner`, in the above cases I have mentioned about 4 places where we will add the check. For all 4 places, do we only have to check admin or only owner?

**Comment by BhuvaneshPatil** [comment]
@AndrewGable Friendly bump for further process

**Comment by AndrewGable** [comment]
Agree with @aimane-chnaif

**Comment by sonialiap** [comment]
@BhuvaneshPatil report, fix, bonus ($1750) - paid ✔️ 
@aimane-chnaif review, bonus ($1500) - paid ✔️

**Comment by sonialiap** [comment]
@aimane-chnaif please complete the [checklist](https://github.com/Expensify/App/issues/21998#issuecomment-1642502556)

**Comment by sonialiap** [comment]
@aimane-chnaif bump to complete the [checklist](https://github.com/Expensify/App/issues/21998#issuecomment-1642502556)

**Comment by sonialiap** [comment]
@aimane-chnaif waiting on you to complete the [checklist](https://github.com/Expensify/App/issues/21998#issuecomment-1642502556)

**Comment by sonialiap** [comment]
Thanks!
