### ISSUE TITLE
Assignee not clickable on creating multiple tasks

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on assign task and create a task with some assignee
3. A new page should appear
4. On the new page, click on + icon and click on assign task. This time, leave everything as default and don't assign any assignee. Create a task.
5. On a new page, click below 'To' and notice a right hand sidebar appears and try to select any user and notice it doesn't work.
## Expected Result: 
Either Users should be selected on trying to select an assignee OR the sidebar should not be showed if it can't be selected
## Actual Result: 
Assignee not clickable on creating multiple tasks

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/64e153bd-c8eb-4558-b299-6c18351dc72d

https://github.com/Expensify/App/assets/43996225/1b4c758a-2f28-4289-9400-810d254b8bcf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688098587995069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Asking in thread what the intended design for this is to start

**Comment by thienlnam** [comment]
This looks like a dupe to this: https://github.com/Expensify/App/issues/20898

**Comment by thienlnam** [comment]
The Assignee field is not a required field when creating a task. The only fields that are required are a title and share somewhere. I linked the wrong issue, [this](https://github.com/Expensify/App/issues/21614) is what I meant where the root cause looks the same

**Comment by alitoshmatov** [comment]
@thienlnam I think this issue is different. Here assignee is not clickable if task is opened from another task page.
https://github.com/Expensify/App/issues/21614 in this one share somewhere field is not working.

I think I found a root cause which is when task is opened from another task, `props.task` is still having old task data, but when we try to assign new user `props.task.reportID` and `route.params.reportID` is not matching:
https://github.com/Expensify/App/blob/47a9218781288a820db38596c18624af3e4b6c2b/src/pages/tasks/TaskAssigneeSelectorModal.js#L166
