### ISSUE TITLE
click of name setup link, It is redirecting to the new window

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21995]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on "+" button
2. then click on New room.
3. and create one room with required details
4. Now click on "here" text which is in blue color( that is for adding different name)
## Expected Result: 
the page should be open within the same Tab
## Actual Result: 
The page is opening new window

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/25754732-bc02-4900-94d0-cb037507b7eb

https://github.com/Expensify/App/assets/43996225/e045d4e9-5bfe-4667-8461-92237bb4d755

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688097705925029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
Duplicate - https://github.com/Expensify/App/issues/21932#issuecomment-1615283135

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment]
@parasharrajat can you confirm if this is a duplicate/tied to the issue you're working on [here](https://github.com/Expensify/App/issues/21932)?

**Comment by dylanexpensify** [comment]
ty!
