### ISSUE TITLE
Web - UserB can modify "Who can post" permission by directly accessing the URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to userA's account
2. Create a workspace and invite userB
3. Open the "#announce" chat
4. Go to Details > Settings > Who can post
5. Copy the URL of the "Who can post" page
6. Change the permission to "Admins only"
7. Open a different browser and login to userB's account
8. Open the "#announce" chat
9. Open a new tab
10. Paste the copied URL
11. Change the permission to "All members"

## Expected Result:
Accessing the "Who can post" page directly via the URL should be restricted

## Actual Result:
UserB can access and modify the "Who can post" permission by directly entering the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5ddd1fa1-d2bf-44ac-b108-b026766541bc

https://github.com/Expensify/App/assets/93399543/7d157c0a-3007-4c20-a157-73fc898d55aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688069676341599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- A non-admin user is able to access the `who-can-post` page using the URL directly.

### What is the root cause of that problem?
- The FullPageNotFoundView component is not added to the `who-can-post` (WriteCapabilityPage.js) route.

### What changes do you think we should make in order to solve the problem?
- Cover the WriteCapabilityPage.js component with the FullPageNotFoundView component.
- And for `shouldShow` prop of the FullPageNotFoundView component, we can get the `role` for given report's policyID, by providing policies with `withOnyx`.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by muttmuure** [comment]
Slightly behind. Getting to this tomorrow

**Comment by muttmuure** [comment]
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/606de54c-0a8d-46a5-82dc-05d14c46b4ee">

Not seeing this

**Comment by ayazhussain79** [comment]
@muttmuure did you join userA's room before opening the "Who can post" link? i can still reproduce it

**Comment by ayazhussain79** [comment]
@hungvu193 you can also reproduce it right ?
@muttmuure You can also reproduce it on room here is room steps:

1. Login to the  userA’s account.
2. Navigate to the "New room" section
3. Enter a name for the room and select the userA workspace
4. Set the visibility of the room to "Public"
5. Click on the "Create room" button
6. Go to the room details
7. Share code > Copy the URL to clipboard Go to the details > Settings > Who can post
8. Open another browser and log in with userB account
9. Join the room by pasting the copied room URL Now copy the “Who can post” page url from userA’s account
10. Paste it in UserB’s account Now you


https://github.com/Expensify/App/assets/56740856/8fd1d1ab-58b4-495d-9dd2-bbd834385067

**Comment by ayazhussain79** [comment]
@muttmuure can you please check this again? you can reproduce it on room too using these steps https://github.com/Expensify/App/issues/22011#issuecomment-1622431028
