### ISSUE TITLE
Login page is displayed instead of magic code page scrolled to the top

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21815
## Action Performed: 
1. Log out
2. Enter your phone number or email address and click Continue
3. Scroll until you can hide the input (Web and desktop can be skipped)
4. Click Go back

## Expected Result:
Page should automatically scroll to the top, and without covering the input

## Actual Result:
1. If "Go back" linked tapped, then login page is displayed
2. If go back button is tapped, then keyboard and app are suppressed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5729cc27-7323-4286-a377-aba27da2defb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
This seems to be working as expected
