### ISSUE TITLE
Task - Pin icon is not displayed on LHN for a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select Assign task
2. Enter title and assign it to a user
3. Click Confirm Task
4. Go to task report
5. Click on Pin icon

## Expected Result:
Pin icon is displayed on LHN

## Actual Result:
 Pin icon is not displayed on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/233d17c4-9654-4af2-961e-b101ad8daf9d

https://github.com/Expensify/App/assets/93399543/7fe51e66-f9ef-4942-a0c6-b0e9d37a9edd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688222429336299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Closing per that explanation / linked comment on the design
