### ISSUE TITLE
Checkmark appears in incorrect position for paid IOU thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from user A to user B
2. From user B settle that amount
3. Open the IOU thread
4. Click on the IOU paid card
## Expected Result:
Green checkmark should be beside the amont
## Actual Result:
Appears at the right end 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  v1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![WhatsApp Image 2023-07-01 at 2 20 49 PM](https://github.com/Expensify/App/assets/43996225/2c244dba-74ae-450e-9082-64abd5cb890d)
![WhatsApp Image 2023-07-01 at 2 18 33 PM](https://github.com/Expensify/App/assets/43996225/5453d8de-83de-41f9-806f-89bf0df52071)
<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/2e8a3be1-fa72-4e54-9bd0-21d129bbf347">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @manjesh-yadav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688099500775589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
I'm able to reproduce this! Will stay assigned so I can pay out the reporting bonus
<img width="1120" alt="image" src="https://github.com/Expensify/App/assets/42940078/25f75986-67fb-43d6-a1d1-adff2a80f061">

**Comment by sophiepintoraetz** [comment]
cc @dukenv0307 @cristipaval @mananjadhav - seeing as you were involved with the PR regression (thank you @kushu7!)

**Comment by mananjadhav** [comment]
@sophiepintoraetz I think this was fixed https://github.com/Expensify/App/pull/21936 but not deployed to staging.

**Comment by cristipaval** [comment]
yes, it was fixed but not deployed yet in the PR linked above. Also, we can safely remove the deploy blocker label since it is a styling issue that does not block the user at all.

**Comment by sophiepintoraetz** [comment]
Yup - fixed 
<img width="385" alt="image" src="https://github.com/Expensify/App/assets/42940078/1ce37c72-58a2-4779-bb7d-68f7095f742c">

**Comment by manjesh-yadav** [comment]
> I'm able to reproduce this! Will stay assigned so I can pay out the reporting bonus <img alt="image" width="1120" src="https://user-images.githubusercontent.com/42940078/250414960-25f75986-67fb-43d6-a1d1-adff2a80f061.png">

As this issue is closed I should be compensated for reporting bonus @sophiepintoraetz

**Comment by sophiepintoraetz** [comment]
offer sent @manjesh-yadav

**Comment by manjesh-yadav** [comment]
Offer accepted @sophiepintoraetz
