### ISSUE TITLE
Checkbox appears and disappears for unavailable workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22034]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and invite User B
3. Login with User B on another web chrome
4. Go to announce channel from both user A and user B
5. (Important step)- Close the browser from User B.
6. Now from User A, remove the User B from the workspace.
7. Open the browser and staging dot again from User B . Notice 'Unavailable workspace' is shown
8. From User B , Click on the + icon on 'Unavailable workspace' and click on assign task. Leave everything as default and create a task.
9. Notice that it shows 'Hmm, it's not here'. But now again click on 'Unavailable workspace' and notice a task has been created down. If you click on checkbox, green mark appears and disappears. Also, if you click on the task , it appears 'Hmm it's not here'
10. Thus, if the task doesn't work and if the green mark checkbox appears and disappears, 'Assign task' should not be shown on User B side.
## Expected Result: 
Assign task should not be shown
## Actual Result: 
Checkbox appears and disappears for unavailable workspace

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ca799bc9-f5bb-4dde-a174-e5e500c74e42

https://github.com/Expensify/App/assets/43996225/878b1d24-914e-4b80-9ed8-b9f6476e0e75

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://applause-ts.slack.com/archives/C037DRM7S1H/p1688160165652739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Getting to this tomorrow
