### ISSUE TITLE
[HOLD 19330]Mobile app - Task Title doesn't overflow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22030]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1-Press the plus sign, 
2-Open Assign task, 
3-Give it a long title, 
4-Click in button Next, 
5-Add an assignee
6-choose share somewhere, 
7-Click in button Confirm task, 
8-Click Mark as done
## Expected Result:
Observe that only half of the message is visible
## Actual Result:
message view overflows
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/948b3cc6-f8f0-448a-8aa7-da68cb801724

https://github.com/Expensify/App/assets/43996225/c95becef-8faf-445f-a17d-c00a219556c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688103445957509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I can reproduce it - I think this might be related to https://github.com/Expensify/App/issues/21347#issuecomment-1618987009 asking

**Comment by Christinadobrzyn** [comment]
Alright, we'll hold for https://github.com/Expensify/App/issues/19330

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're on hold waiting to see if https://github.com/Expensify/App/issues/19330 will fix this. I'll take this if it's still open when I'm back.

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
@dhairyasenjaliya still on hold yeah?

**Comment by dylanexpensify** [comment]
perfect, ty!!
