### ISSUE TITLE
[$1000]  The input focus for the magic code does not change when clicking "Next" on the keyboard.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Send magic code
2- click on any number input
3- Click "Next" in keyboard
## Expected Result: 
The input focus should move to the next field in the same way it does when clicking the backspace button (it moves to the previous field)
## Actual Result: 
The field focus remains unchanged when clicking the "Next" button, whereas it changes properly when clicking the backspace button.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/db391708-954b-4b35-8e48-1aa9931d4eb0

https://github.com/Expensify/App/assets/43996225/bac23e05-d119-4e5a-a440-64caba862538

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688134893360619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8c286dff2a88bc9</li>
        <li>Upwork Job ID: 1676986728452608000</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Asking about reproduction here

https://expensify.slack.com/archives/C01SKUP7QR0/p1688413228455539

**Comment by mejed-alkoutaini** [comment]
@kevinksullivan Hi, can't access the link you provided for some reason, can you comment in this thread and I can provide more details about reproduction if needed, https://expensify.slack.com/archives/C049HHMV9SM/p1688134893360619

**Comment by kevinksullivan** [comment]
It was an internal question on testing this. All good to move forward.

**Comment by kevinksullivan** [comment]
Not overdue.

**Comment by sophiepintoraetz** [comment]
(I don't think I need to be here)

**Comment by ShogunFire** [comment]
Can you reproduce with real device ?
I found this comment that could explain why it's acting weird in the emulator:
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/MagicCodeInput.js#L230-L238

**Comment by kevinksullivan** [comment]
I reproduced using browserstack, as I don't have an android device.

**Comment by kevinksullivan** [comment]
Still awaiting proposals.

**Comment by ShogunFire** [comment]
What exactly is the expected behaviour ? I propose that in mweb and android we show submit button and when we click on it we submit, I am not sure next button is usefull, I don't think the user will understand what that does.

**Comment by kevinksullivan** [comment]
Hm still waiting on proposals here @aimane-chnaif ?

**Comment by kevinksullivan** [comment]
Still waiting on proposals

**Comment by kevinksullivan** [comment]
this one has gone silent for a long time. I'm going to bring someone internal in to prioritize it.

**Comment by thienlnam** [comment]
Honestly, I think we should just close this. Not a real use case that a customer would run into and it's specific to Android chrome. Doesn't seem worthwhile to look into. Going to close but if you feel strongly feel free to reopen
