### ISSUE TITLE
Save button color is not changing when user clicks on it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Open workspace chat
2- Click at the workspace name
3- Click at the workspace name again
4- Open settings tab
5- Click Save quickly without hovering on it
## Expected Result: 
The button color should change to dark green to let the user know that the button is clicked successfully
## Actual Result: 
The button color is not changing at all if  the user clicks on it quickly without hovering on it,
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/72d03c9a-97f6-463f-933a-a6fec3d4589a

https://github.com/Expensify/App/assets/43996225/f09169df-7f4f-4d80-baa4-74d524ddee0b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688132884261979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Thanks Bernhard. Agreed, since the delay is intentional this isn't a bug. Closing
