### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Visit the Room welcome message edit page by direct link then click save button, it navigates back to the chatReport instead of Room setting page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22041]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-step: Go to any room that you have permission to update welcome message => Go to Room welcome message paste => Copy the URL => Paste to any chat report
1. Click on the link that you just paste
2. Verify that it open the Room welcome message page
3. Click save button
## Expected Result: 
 It navigates back to Room setting page
## Actual Result: 
 It navigates back to the chat report page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aa1690c3-b61a-49b5-bf64-ad8e1bfb1f1c

https://github.com/Expensify/App/assets/43996225/1d62831a-4bfa-4644-8234-9db015dd6440

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688126512179099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e35dd505b57309c2</li>
        <li>Upwork Job ID: 1684161543399026688</li>
        <li>Last Price Increase: 2023-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26196235</li>
<li>hoangzinh | Contributor | 26196236</li>
<li>hoangzinh | Reporter | 26196237</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Visit the Room welcome message edit page by direct link then click save button, it navigates back to the chatReport instead of Room setting page
### What is the root cause of that problem?
In the action to save the Room's welcome message, we just call `Navigation.goBack`
https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/libs/actions/Report.js#L1142
When we visit the page by direct link, the previous history page is empty => It will navigate to the chat report by default.
### What changes do you think we should make in order to solve the problem?
We should add `fallbackRoute` of room setting page for [Navigation.goBack here](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/libs/actions/Report.js#L1142)
```
Navigation.goBack(ROUTES.getReportSettingsRoute(reportID));
```
So it will navigate to the room setting route when there is no active routes
### What alternative solutions did you explore? (Optional)
Instead of call `Navigation.goBack`, we can call `Navigation.navigate` directly to the room setting route [here](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/libs/actions/Report.js#L1142)

**Comment by dylanexpensify** [comment]
Not a bug here

**Comment by greg-schroeder** [comment]
Seems there are multiple issues being reported around this and so I've closed the dupes and reopened this as this was the original. I checked the convo in Slack but it doesn't seem like we hadn't any engagement from the team. Should we re-bump about this @dylanexpensify?

**Comment by dylanexpensify** [comment]
Agree @greg-schroeder, will bump!

**Comment by s77rt** [comment]
In case we ended fixing this, please make the fix global, we have the same issue reported for different pages.

**Comment by dylanexpensify** [comment]
Agree @s77rt

**Comment by situchan** [comment]
@hoangzinh can you please find out and list all pages across the app where same issue happens?

**Comment by dylanexpensify** [comment]
@hoangzinh can we get an update today please?

**Comment by situchan** [comment]
@hoangzinh's [proposal](https://github.com/Expensify/App/issues/22041#issuecomment-1616422526) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment]
@dylanexpensify just checking, where did this conversation happen in slack?

Wondering b/c I'd be curious to know if we tagged the person / people who added `Navigation.goBack` in lots of places, or basically who was involved in the convo confirming that this isn't something we want - cuz I don't this specific issue is a bad flow necessarioy

**Comment by neil-marcellini** [comment]
@abdulrahuman5196 and I had a [parallel conversation](https://expensify.slack.com/archives/C049HHMV9SM/p1690915949087489) about this and we think that it would be good to add a mandatory route parameter to the function. Idk what y'all are planning but I thought I would mention it and I'll let you guys take it from here.

**Comment by dylanexpensify** [comment]
Ah [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1688469096184469) - @Beamanator what's the best path here in your opinion??

**Comment by Beamanator** [comment]
Ooh I like @neil-marcellini & @abdulrahuman5196  's thoughts in that linked slack thread - I feel like we might need a bit more buy-in before moving forward with that, but it makes sense to make that change first and thennn fix this & other bugs, right?

**Comment by dylanexpensify** [comment]
bump!

**Comment by abdulrahuman5196** [comment]
I think there is a subtle difference on what is being targetted there and what we are targetting here.

1) Here (https://github.com/Expensify/App/issues/22041) deals with how we fix all the existing Navigation.goBack() to have fallback routes.
2) But What I proposed was to handle future cases(since we where thinking of adding it to checklist), like even after this fix is made there is nothing stopping contributors from making the same mistake of just using Navigation.goBack() . So if we make the fallback param mandatory, Navigation.goBack(fallback) would be only way to use the function. So if they don't want any specific screen, they can give home as fallback or they have to give some proper screen as fallback.


So, I think we should implement what we are trying to fix here, and then work on the other issue separately https://github.com/Expensify/App/issues/24291

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Amazing, then @hoangzinh was the proposal we wanted to go with, yes?

**Comment by dylanexpensify** [comment]
bump @abdulrahuman5196

**Comment by dylanexpensify** [comment]
[bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1692193497008679)

**Comment by dylanexpensify** [comment]
@situchan bump on if we proceed with @hoangzinh's proposal?

**Comment by situchan** [comment]
I already approved [here](https://github.com/Expensify/App/issues/22041#issuecomment-1665238759).
@abdulrahuman5196 can we go ahead and fix this separately or should hold until your fix for https://github.com/Expensify/App/issues/24291 is done?

**Comment by dylanexpensify** [comment]
Nice ty! @abdulrahuman5196 let us know and we'll go from there! @Beamanator do you agree with @hoangzinh's proposal?

**Comment by abdulrahuman5196** [comment]
I think we can go separate. Its just that, whoever comes second has to fix merge conflicts 🤒

**Comment by Beamanator** [comment]
Ok catching up, sorry for the delay :D

So I agree with @situchan that @hoangzinh 's proposal looks good for fixing this specific reported bug 👍 

But aren't we planning to try to fix all places we use `goBack`? As they found [here](https://github.com/Expensify/App/issues/22041#issuecomment-1664252944)? So to be clear, we're planning to fix all of these places in this issue, right?

And then @abdulrahuman5196 will work on **requiring** the fallbackRoute in the [other issue](https://github.com/Expensify/App/issues/24291#top), right?

**Comment by situchan** [comment]
@Beamanator right both

**Comment by Beamanator** [comment]
Great, let's do this!

**Comment by Beamanator** [comment]
automation is off... one sec...

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
@hoangzinh when are we thinking the PR will be ready?

**Comment by dylanexpensify** [comment]
Reviewing tomorrow! Sounds good, bump @situchan

**Comment by dylanexpensify** [comment]
@situchan @hoangzinh did you discuss? Mind posting an update?

**Comment by situchan** [comment]
Discussed in PR

**Comment by situchan** [comment]
yeah sorry for back and forth. At first I thought cases @hoangzinh found in proposal are all to fix but after deep looking, there are tons of cases where back button is possible.
So I'd like to see how they are handling them in https://github.com/Expensify/App/issues/24291 and then revisit this issue after that issue is done.

**Comment by jjcoffee** [comment]
@situchan Would I be right in thinking the general fix here would handle #26282 too?

**Comment by situchan** [comment]
> @situchan Would I be right in thinking the general fix here would handle #26282 too?

I think so. Can you suggest that issue to put on hold rather than close?

**Comment by dylanexpensify** [comment]
@situchan mind giving an update here?

**Comment by situchan** [comment]
Let's wait a bit more until holding PR hit production

**Comment by situchan** [comment]
https://github.com/Expensify/App/pull/26710 was deployed to production.
@hoangzinh can you please update PR based on latest codebase?

**Comment by dylanexpensify** [comment]
Nice! @hoangzinh did we get this sorted? cc @situchan

**Comment by dylanexpensify** [comment]
Great! @situchan @hoangzinh what's our ETA on wrapping this up/

**Comment by situchan** [comment]
PR hit staging yesterday. Maybe around Oct 19 will be payment date

**Comment by dylanexpensify** [comment]
Payment upcoming!

**Comment by Beamanator** [comment]
how we doin here? 🙏

**Comment by Beamanator** [comment]
We good here @dylanexpensify ?

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: This is not normal user flow and always existed from the beginning.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1690915949087489
- [x] Determine if we should create a regression test for this bug. In https://github.com/Expensify/App/issues/24291, we made fallback route necessary for navigation goBack method. I think this will help preventing similar bugs in the future.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. I have same thought as https://github.com/Expensify/App/issues/24291#issuecomment-1743106569

**Comment by dylanexpensify** [comment]
done!
