### ISSUE TITLE
Wide emojis cause incomplete highlighting when hovering

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Open the Emoji panel
3. Observe that certain emojis are extra wide, and when hovered the highlighted styling does not cover the emoji.
## Expected Result: 
Complete highlighting of the emoji
## Actual Result: 
Incomplete highlighting of the emoji

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/5802477/059570b2-ee6f-4cfe-904a-0abafac9480d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688127392035469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I've fixed the videos now.

**Comment by conorpendergrast** [comment]
However, this is on Windows (Win10) according to [the Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688127392035469), which is an unsupported platform at the moment. Here's the emojis on OSX: 

<img width="339" alt="image" src="https://github.com/Expensify/App/assets/5802477/c13bed5d-1a6d-4249-96fe-ed147cb0707f">

Closing as Windows is not an officially supported platform yet

**Comment by conorpendergrast** [comment]
Can you show me how to reproduce this OSX? I have not been able to see that so far

**Comment by conorpendergrast** [comment]
I am so confused, how do you have different emojis there @samh-nl?. Here's what I'm seeing on OSX 13.3.1, in Chrome (and the same in Safari too):

<img width="450" alt="image" src="https://github.com/Expensify/App/assets/5802477/f93257e3-20e0-4690-8233-be59a5cd855b">
