### ISSUE TITLE
thread does not show immediately on receiver side in task report screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign a task
2. Enter title and assign it to a user
3. Click Confirm Task
4. go to task report screen and send a message
5. hover on that message and click on reply in thread option
6. go to thread and send a message
7. check the report screen on receiver side at same time
## Expected Result: 
thread should show immediately
## Actual Result: 
thread does not show immediately on receiver side

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6808ff56-d767-4fa5-a601-285ec1d97aad

https://github.com/Expensify/App/assets/43996225/405402a0-a0a9-4158-b4a2-4cce530ecbf5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688134690277149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4dbbdf6fb6c57db</li>
        <li>Upwork Job ID: 1675949463671173120</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by eh2077** [comment]
Looks like a backend issue because no push event received from frontend.

**Comment by flaviadefaria** [comment]
Adding the internal label.

**Comment by flaviadefaria** [comment]
Hm since no engineer was assigned with the internal label I'll add the engineering label too.

**Comment by flaviadefaria** [comment]
Waiting for @johnmlee101 to look into this.

**Comment by johnmlee101** [comment]
No update, will look into this soon!

**Comment by flaviadefaria** [comment]
@johnmlee101 do you have an update for this?

**Comment by flaviadefaria** [comment]
Friendly bump @johnmlee101!

**Comment by johnmlee101** [comment]
Have a WIP auth PR!

**Comment by johnmlee101** [comment]
@kavimuru can this be re-tested?

**Comment by johnmlee101** [comment]
Bump @kavimuru !

**Comment by kavimuru** [comment]
@johnmlee101 I am not able to reproduce now
![image](https://github.com/Expensify/App/assets/43996225/bf972767-9735-4b0c-b3ee-f5039104a58e)

**Comment by johnmlee101** [comment]
Amazing! I think we can mark this as done then

**Comment by flaviadefaria** [comment]
It doesn't seem like @abdulrahuman5196 reviewed this so I think we only need to pay @gadhiyamanan $250 for the referring bonus, is that correct?

**Comment by flaviadefaria** [comment]
@gadhiyamanan offer sent!

**Comment by gadhiyamanan** [comment]
@flaviadefaria offer accepted, thanks

**Comment by flaviadefaria** [comment]
Paid! I think we're all done here so will close the GH. In case I didn't get this right and @abdulrahuman5196 requires payment please reopen the GH and reapply the bug label as I'm going OoO for a week.
