### ISSUE TITLE
Tooltip is not dismissed when returning from Download window.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Hover on any attachment until download tooltip is visible
2. Press on download and wait until the download window opens.
3. Move the mouse to a different position.
4. Press ESC from keyboard and observe the tooltip
## Expected Result: 
Tooltip should be dismissed after closing the window.
## Actual Result: 
Tooltip is not dismissed when returning from Download window.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 13.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6e5a8529-a139-4ea7-b3ff-961b652be894

https://github.com/Expensify/App/assets/43996225/72251b8b-1456-4f38-9bb2-5eb042ea1a13

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688131443836639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment]
I'm not sure I agree this is a bug. Why should the tooltip dismiss if you are moused over?
