### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] "No results found" not translated dynamically

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app in another device and login with user A (device 2)
3. From device 1, tap Search and search term for which 'No results found' is displayed (ex: search for `norsultsfound`)
4. From device 2, change language to spanish and observe in device 1 that all the other terms are translated but not the term 'No results found'
5. From device 2, change it back to english
6. From device 1, open new group and search for term for which 'No results found' is displayed (ex: search for `norsultsfound`)
7. From device 2, change language to spanish and observe in device 1 that all the terms along with 'No results found' is translated

## Expected Result: 
App should dynamically translate 'No results found' on search page as it does on new group page

## Actual Result: 
App does not dynamically translate 'No results found' on search page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.25-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2b19722d-38d2-4d94-bdea-d56ed6abfaf3

https://github.com/Expensify/App/assets/43996225/f6975a86-180c-4395-a6b5-4b813863a0f8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688143646794559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01355acaf446c4a2a9</li>
        <li>Upwork Job ID: 1675929093581258752</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce - adding External

**Comment by Pujan92** [comment]
I think this earlier issue https://github.com/Expensify/App/issues/21537 will solve this one.

**Comment by Christinadobrzyn** [comment]
Asking if https://github.com/Expensify/App/issues/21537#issuecomment-1622401192 will resolve this issue

**Comment by Christinadobrzyn** [comment]
Hiring in Upwork: 

Internal Job: https://www.upwork.com/ab/applicants/1675929093581258752/job-details
External Job: https://www.upwork.com/jobs/~01355acaf446c4a2a9

@dhanashree-sawant as reporter
@thesahindia as C+
@c3024 as contributor 

@c3024 can you send over your Upwork profile so i can hire you?

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're working on the PR and payment based on https://github.com/Expensify/App/issues/22051#issuecomment-1636296050

**Comment by adelekennedy** [comment]
payment due on the 21st! Not overdue

**Comment by adelekennedy** [comment]
will pay out on Friday!

**Comment by adelekennedy** [comment]
@thesahindia will be paid out in ND (1k + speed bonus)

**Comment by JmillsExpensify** [comment]
$1,500 payment for @thesahindia approved based on the comment immediately above this one.
