### ISSUE TITLE
Web -  An appropriate message is not shown when Assigning task to the secondary contact of the task creator

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22057]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Go to Assign task
3. Write a title and click next
4. Go to Assignee and enter the secondary contact of the task creator. Notice that "No result found" is displayed
5. Go to Share somewhere and enter the secondary contact of the task creator. Notice that "No result found" is displayed.

## Expected Result:
A message indicating a Secondary contact should appear or a Task should be assigned using a secondary contact.

## Actual Result:
No result is found

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cde37e37-98ad-423e-b71b-ff32d82ad38e

https://github.com/Expensify/App/assets/93399543/e34c4bbb-a5b7-492a-ace8-7d33be049948

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688187202113939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, I don't think this is a bug. I don't think there's a real-world use-case where someone needs to be able to assign themselves to the task, but using their secondary login. I'm going to go ahead and close this, but feel free to reopen if you disagree.

**Comment by puneetlath** [comment]
Yep, that's fair feedback. Feel free to raise a problem/solution in the #open-source channel if you feel strongly about this!
