### ISSUE TITLE
[HOLD for newdot payment after BugZero checklist is complete] [$1000] Pressing escape on the composer deletes your message, and CMD+Z doesn't bring it back

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Draft a message
2. Press escape
3. Press CMD+Z

## Expected result:
Your draft message should come back
## Actual result: 
Your draft message is gone forever

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4e9f02df-16e0-460a-b077-f1cf86ac52d9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688153029272289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018379455c4980f440</li>
        <li>Upwork Job ID: 1675763769888301056</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
@roryabraham just to confirm the desired behaviour, `ESC` should get rid of the message but you should be able to bring it back with CTRL+Z?

**Comment by oluwagbemigadavid** [comment]
You can store the contents of the message body in a temporal var and listen for the ctrl+z to replace the current msg body with the temporal var value

**Comment by oluwagbemigadavid** [comment]
Contributor details
Your Expensify account email: koningswealth@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c3711093b8c8aeef

**Comment by narefyev91** [comment]
Proposal from @honnamkuan looks good to me https://github.com/Expensify/App/issues/22053#issuecomment-1616351593
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment]
Guys @shawnborton @roryabraham any updates here?

**Comment by dangrous** [comment]
I'm following up in that convo, thank you for the link! Sorry for the delay, I just am still not sold on this behavior

**Comment by dangrous** [comment]
Okay we're updated - new expected behavior is: Esc does NOT clear message. Can you take a quick look at the proposals for me @narefyev91 with that in mind?

**Comment by narefyev91** [comment]
@dangrous based on latest information we can choose @c3024 (and proposal https://github.com/Expensify/App/issues/22053#issuecomment-1616323059) - contributor already point in discussion that we should not remove text clicking on Esc

**Comment by dangrous** [comment]
Lovely! Assigning you now, @c3024!

**Comment by kadiealexander** [comment]
@c3024 I've sent you an Upwork contract, please accept!

@narefyev91 If you're being paid via newdot please let me know, otherwise let me know your upwork details and I'll send across a contract. Also, please don't forget the checklist!

**Comment by kadiealexander** [comment]
It will be paid as a bonus on this Upwork job :) The total payment will be $1500.

**Comment by dangrous** [comment]
I think we're still waiting on the [checklist](https://github.com/Expensify/App/issues/22053#issuecomment-1633405348), anything else needed on this one?

**Comment by kadiealexander** [comment]
Just the checklist and C+ payment :)

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: n/a
Contributor: $1000 @c3024 
Contributor+: $1000 @narefyev91 (pending bug0 checklist)

Eligible for 50% #urgency bonus? Yes, $500

Upwork job is [here](https://www.upwork.com/jobs/~018379455c4980f440).

**Comment by dangrous** [comment]
Hey @narefyev91! Let us know when you have a chance to look at that checklist - thank you!

**Comment by dangrous** [comment]
yep i think that's all right!

**Comment by dangrous** [comment]
I think we're just waiting on the C+ payment here now, right?

**Comment by narefyev91** [comment]
> I think we're just waiting on the C+ payment here now, right?

I'm from Callstack - not needs any additional payments from NewDot or Upwork :-)

**Comment by dangrous** [comment]
Ah, lovely! @kadiealexander when you have time I think we can update the payment checklist to reflect that ^ and then can close!
