### ISSUE TITLE
Expend composer option displayed for a second when opening chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the chat
2. Write a message on composer
3. Press back button
4. Now open that chat again

## Expected Result:
The "Expand Composer" Option Should Not Appear Upon Reopening the Chat
## Actual Result:
Brief display of expend composer option when opening chat
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/52a37ae1-8251-4b49-8588-ccc7f7a18f94

![Screenshot_20230516-230740](https://github.com/Expensify/App/assets/43996225/31830069-67d2-4652-8153-fdc82a6c05ab)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684260173925429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
This bug seems to be 2 months old, and I can't repro this in .35-5 on Pixel 3a.

Please re-test and re-open with a new video/reproduction steps.
