### ISSUE TITLE
Auto populated "share somewhere" field in confirm task page doesn't change when changing the assignee contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in to staging new dot
2. Click on + icon
3. Click on assign task
4. Enter title and click on next
5. Enter an assignee and observe the share message field is auto populated with the contact in the assignee field
6. Click on assignee and change it to another contact
7. Observe that the auto populated contact from earlier is unchanged

## Expected Result:
Account in Share message field should also change when changing assignee

## Actual Result:
The initial auto populated account remains in share message field even after changing assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9aa448a9-7a60-4430-b9e3-c151aeb7621d

https://github.com/Expensify/App/assets/93399543/aa5c1084-847b-4909-a81f-8023a72d0c4b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688201391160259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Auto populated "share message" field in confirm task page doesnt change when changing the assignee contact 
### What is the root cause of that problem?
We are just checking if there is any `shareDestination` which there would be after first selection
https://github.com/Expensify/App/blob/cc1153ad0091a91f83f72a85db749dadd87ad32c/src/libs/actions/Task.js#L493C16-L493C16

### What changes do you think we should make in order to solve the problem?
We can add logic for new 

### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment]
I agree that could cause problems, @bernhardoj.

@thienlnam I've checked [the design doc](https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#heading=h.ns12dr1f35rx) and can't be sure. In the initial design, did we intentionally design for change the assignee *before* creating the task, not also updating the "**Share somewhere**" field?

**Comment by thienlnam** [comment]
Yeah this is intended design so NAB

We only auto populate the 'share somewhere' after you select an assignee so it's one less step to create a task.

However, it is a totally valid use case to decide to change the assignee while leaving it shared in the same spot so there is no bug here

**Comment by conorpendergrast** [comment]
Great, thanks for confirming that
