### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] IOS - Inconsistent error messages when uploading avatar images fail.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting -> Profile
2. Update new avatar image with dimensions outside the allowed range
3. You will see a image upload failed error message

## Expected Result:
The error message should have consistent behavior with the error messages on other pages (Ex: Color of text, red dot)

## Actual Result:
The error message is not consistent behavior with the error messages on other pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.35-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (13)](https://github.com/Expensify/App/assets/93399543/0f67f56d-b731-4c6b-9455-11772b8d873f)
![image (12)](https://github.com/Expensify/App/assets/93399543/7b8cce02-0099-4596-a455-880c64c8e288)

https://github.com/Expensify/App/assets/93399543/9c9eb158-961b-43ac-8074-bee61d2af9a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gemma0110
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688229503251319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b360b6dd28e2931d</li>
        <li>Upwork Job ID: 1684127665048092672</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>dhairyasenjaliya | Contributor | 25790761</li>
<li>gemma0110 | Reporter | 25790764</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment]
I don't think this is a bug. I think it's okay that we have the modal style to use more room to explain exactly what happened with the image upload error. I would just close this one out.

**Comment by flaviadefaria** [comment]
@shawnborton but shouldn't it follow the same sort of design? Something as simple as having the red dot and displaying the error message in red?

**Comment by shawnborton** [comment]
I don't know that it needs to personally. We could add the error below the avatar upload button if we really want it to be perfectly consistent with other form validations. But we use this modal error elsewhere for things like attachments being incorrect, file types being wrong, etc. So I don't think this is an inconsistency bug because it's an acceptable error pattern we use elsewhere.

**Comment by flaviadefaria** [comment]
So you don't think the error messages should either always be written in red text with a dot or always in white text without the dot? Personally having two different ways of showing error messages seems like an inconsistency to me. But then again you are our design guy, so if you want to close this just go for it!

**Comment by shawnborton** [comment]
Well the problem here is that it's a follow up alert modal, it's not an inline error next to the form component. I could see an argument to use our red brick error style and show it directly below the avatar image though.

**Comment by flaviadefaria** [comment]
Ah I see what you mean. Now I understand the difference between the two error types.

>I could see an argument to use our red brick error style and show it directly below the avatar image though.

Do you mean doing this just for this error or all follow-up errors? Maybe it's just easier to keep them different and close this issue. Now that I get the difference I'm not opposed to keeping the two different error message types.

**Comment by shawnborton** [comment]
Thinking more on this - I can see where it makes sense to move this error to use the RBR pattern and display it right below the avatar + camera icon. I think the error appear there after a failed image upload, and then disappear when you leave the page. cc @trjExpensify curious if you agree with that too!

**Comment by trjExpensify** [comment]
Yeah, I tend to agree that the alert modal feels a little out of sorts with our in-line errors for optimistic failures and form field validation errors.

This one would be pretty straightforward to change, we already have an in-line RBR error beneath the avatar image for upload failures when offline we can re-use (just without persisting it with the `X` in this case). That said, if we're going to move away from the alert modal for this variation of an attachment upload failure -- we should probably do the same elsewhere like in the chat view for file type, size etc? Maybe those are a little harder to make work cleanly. I don't think we even go so far as to show a preview when online, so I'm not sure where it would be in-line to. 🤔

**Comment by shawnborton** [comment]
Yeah, I wouldn't exactly know where to put things like file type or file size limit errors given that there is no natural "inline" place to put them, so they make sense to stay as alert modals. 

As for this particular issue though, @flaviadefaria I think we can move forward with having the error message for the avatar be placed right below the avatar itself.

**Comment by flaviadefaria** [comment]
>As for this particular issue though, @flaviadefaria I think we can move forward with having the error message for the avatar be placed right below the avatar itself.

@shawnborton so just to confirm, the desired outcome here is for the inline error message to be place under the avatar with the red dot and error copy saying: Please upload an image larger than....

Is this correct?

**Comment by shawnborton** [comment]
Correct!

**Comment by sobitneupane** [comment]
Thanks for the proposal @dhairyasenjaliya. Overall the proposal looks good to me.

Can you please link the files where are you proposing the changes in each step.

> We need to remove <DotIndicatorMessage> on the image upload success or image removed

Can you please explain a bit about the above step. Which `DotIndicatorMessage` are we talking about? Where was the `DotIndicatorMessage` being shown. What error message are expected to be shown?

**Comment by sobitneupane** [comment]
@dhairyasenjaliya Thanks for the update. 

I am still expecting more details for the following step.

>We need to remove on the image upload success or image removed

Can you please explain a bit about the above step. Which DotIndicatorMessage are we talking about? Where is the DotIndicatorMessage being shown. What error message are expected to be shown?

**Comment by sobitneupane** [comment]
Thanks for the update @dhairyasenjaliya.


[Proposal](https://github.com/Expensify/App/issues/22069#issuecomment-1648234084) from @dhairyasenjaliya looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
Also it sounds like we should remove `Bug` and leave this as a `New Feature`. Thoughts @flaviadefaria?

**Comment by flaviadefaria** [comment]
Payment summary:
@gemma0110 = $250 (UW)
@dhairyasenjaliya = $1000 + $500 = $1500 (UW)
@sobitneupane = $1000 + $500 = $1500 (ND)

@sobitneupane can you fill out the checklist above so that I can issue payment? Thanks!

**Comment by sobitneupane** [comment]
Sorry for the delay @flaviadefaria. I could not get to it today. I will review it tomorrow.

**Comment by flaviadefaria** [comment]
@zanyrenney I'm heading OoO so reassigning this in the meantime. We're basically all done here and only waiting on @sobitneupane to [fill this out](https://github.com/Expensify/App/issues/22069#issuecomment-1664333933) so that payment can be issued as detailed [here](https://github.com/Expensify/App/issues/22069#issuecomment-1672904900).

**Comment by zanyrenney** [comment]
sounds good, thanks @flaviadefaria

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:


Rather than a bug, it's an incosistency issue. So, the checklist doesn't apply here.

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/22069#issuecomment-1672904900

**Comment by gemma0110** [comment]
@zanyrenney  it's still pending for me as well

**Comment by zanyrenney** [comment]
PAID OUT:

@gemma0110 = $250 (paid through UW) 🏁 
@dhairyasenjaliya = $1000 + $500 = $1500 (paid through UW) 🏁 

@sobitneupane - please submit payment through ND. This issue and payouts are now complete.

**Comment by JmillsExpensify** [comment]
Reviewed the details for @sobitneupane. $1,500 payment approved via NewDot based on BZ summary.
