### ISSUE TITLE
[$1000] Web - Error occurs when user tries to split bill after starting a new chat with a new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account
2. Click on FAB > New chat
3. Input a new email and start a chat
4. Click on FAB > Split bill
5. Enter an amount
6. Select the account you started a chat with and then add another one account and split the bill
7. Wait for a while until the error occurs

## Expected Result:
No error should occur

## Actual Result:
Error occurs and user is unable to split a bill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/29e4f9ef-f12c-4e88-b9d4-b793bd416167

https://github.com/Expensify/App/assets/93399543/d12252a1-d981-4cca-b6f5-7d0bb0a6cb84

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688212454190299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a8416f5812bffa0</li>
        <li>Upwork Job ID: 1676572723760885760</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Similar / perhaps related issues: https://github.com/Expensify/App/issues/19235
https://github.com/Expensify/App/pull/20277

**Comment by multijump** [comment]
It seems backend side issue.
When split bill in this case, backend api returned error value.
<img width="1734" alt="image" src="https://github.com/Expensify/App/assets/35476479/7b067fef-cc3a-4355-bce2-cd5aa2f86e34">
<img width="666" alt="image" src="https://github.com/Expensify/App/assets/35476479/868595ee-366b-41e3-bf52-1e263f89e567">
Error message was from api returns.
So before make proposal, I need the confirmation from backend if this error message is normal case or not.
Thanks.

**Comment by multijump** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error occurs when user tries to split bill after starting a new chat with a new account

### What is the root cause of that problem?
When split bill, calls `SplitBillAndOpenReport` api with split info(including accountID).
1. When split bill with new account, didn't find correct accountIDs of participants if there is not any reports from participants which are gonna split bill.
2. Called `SplitBillAndOpenReport` api with wrong accountIDs, then api returns error.
3. This wrong accountID was from Onyx

### What changes do you think we should make in order to solve the problem?

When put the data to Onyx for `personalDetails`, update to put correct accountID though they didn't establish connection  before.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by zanyrenney** [comment]
Hey @eVoloshchak please can you review the proposal from @multijump above so we can move forward with this ?

**Comment by eVoloshchak** [comment]
@zanyrenney, @multijump is correct, this is a back end issue, it should be Internal

> If there is not any account with login in DB, I think error is correct case.

Perhaps we should change the error also, it shouldn't say `There is a previously existing chat between these users.` for a non-existent user account

**Comment by zanyrenney** [comment]
hey @chiragsalian curious for your thoughts here! also aware you are off on parental leave soon so if we should find someone else, please can you reapply the label? Thanks!

**Comment by zanyrenney** [comment]
Assigning another engineer as @chiragsalian is on Parental leave.

**Comment by zanyrenney** [comment]
Did not mean to add overdue label.

**Comment by zanyrenney** [comment]
hey @yuwenmemon have you had the chance to take a look at this one yet? thanks!

**Comment by zanyrenney** [comment]
DM'd @yuwenmemon !

**Comment by Nathan-Mulugeta** [comment]
Hey @yuwenmemon , I was able to consistently reproduce this issue. I will attach a screen recording down below. Look at this [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1690445476675529?thread_ts=1690445476.675529&cid=C01GTK53T8Q) conversation as well. 

https://github.com/Expensify/App/assets/111440031/2471b66c-2639-47c2-925d-0fe3725a6d36
