### ISSUE TITLE
Web -  Clicking on browser back button before closing shortcut modal doesn't close modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND
2. Press CTRL + J to open the keyboard shortcuts
3. Click on browser back button

## Expected Result:
Modal should close

## Actual Result:
Modal stays open while app navigates back to the previous page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fa89f7a3-bc2b-45a7-a812-a0f5c629f8ef

https://github.com/Expensify/App/assets/93399543/6da2013f-69ba-45a2-9996-121103c0a6da

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688220937658199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Thanks @hungvu193. Closing in favor of the earlier issue.
