### ISSUE TITLE
Web - Emoji and send icon do not center align vertically just like the plus icon inside of the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Click inside the composer
3. Press shift + enter to add a new line
4. Observe and compare the plus icon with the emoji and send icons

## Expected Result:
All the icons, i.e the plus icon, the emoji icon and the send icon should be either center aligned vertically or should be aligned to the bottom

## Actual Result:
Only the plus icon becomes center aligned vertically but the emoji and the send icons become bottom aligned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cc8789e5-63e3-436f-8b54-49080be5a425

https://github.com/Expensify/App/assets/93399543/6998058e-f0f0-4cc3-a236-9f595cc8f924

**Expensify/Expensify Issue URL:**
**Issue reported by:** Nathan Mulugeta
React JS development and Quality Assurance (GH @Nathan-Mulugeta)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688221459620419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I think we can close this out, this is expected based on the composer height change we made.
