### ISSUE TITLE
[Ready to pay] Dev - Highlighted border is applied to checkbox after unchecking the checkbox

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
3. Click on 'Workspace'
4. Open a workspace that has members
5. Click on 'Members'
6. Select one of the members
7. Uncheck the selected member

## Expected Result:
Border highlight shouldn't be applied to the unchecked checkbox

## Actual Result:
Border highlight is applied to the unchecked checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9398f308-6c13-407c-883a-fed9b570e391

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688232509791849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I couldn't reproduce this on Staging. Going to see if anyone else can reproduce on Dev

**Comment by conorpendergrast** [comment]
Ah, you reproduced on dev @huzaifa-99 ?

**Comment by conorpendergrast** [comment]
Great, I've already asked [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1688387764888949?thread_ts=1688232509.791849&cid=C049HHMV9SM), and will look out for that. Thanks for the help here you two

**Comment by Natnael-Guchima** [comment]
@conorpendergrast the offending PR that has introduced this bug is being reverted here 2hrs ago https://github.com/Expensify/App/pull/22124

**Comment by Natnael-Guchima** [comment]
Hello @conorpendergrast, the issue that has introduced this bug is reverted based on this another report https://github.com/Expensify/App/issues/22119 which was reported on July 3rd, and mine was reported on July 1st. This is to check if I am eligible for bonus reporting. 
Thanks. 

![Screenshot from 2023-07-05 13-36-56](https://github.com/Expensify/App/assets/57330233/8289e316-b4bc-4555-911b-57d2c6136c7e)
![Screenshot from 2023-07-05 13-37-15](https://github.com/Expensify/App/assets/57330233/bb63b6ad-2fc7-446a-a40b-7ca53c9a195a)

**Comment by conorpendergrast** [comment]
Yep, I agree with that @Natnael-Guchima

**Comment by conorpendergrast** [comment]
Offer sent via Upwork - https://www.upwork.com/nx/wm/offer/25391651

**Comment by Natnael-Guchima** [comment]
Accepted! Thanks @conorpendergrast

**Comment by conorpendergrast** [comment]
Paid via this contract, and contract ended: https://www.upwork.com/nx/wm/workroom/34119626/overview

All done, thanks @Natnael-Guchima!
