### ISSUE TITLE
mWeb - Navigation bug: clicking back button on + icon pop-up menu reloads the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Click on the + icon
3. When the pop up menu is shown click on the phones back button
4. Observe that the page reloads and takes you to another page within expensify
5. Click on the back arrow until you return to the chat list and repeat step 2 and 3
6.  Observe the page reloads again but this time takes you to another page in expensify

## Expected Result:
Clicking the back button should only close pop-up menu

## Actual Result:
Clicking on back button reloads page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f9a6fff1-a120-4357-9491-95090ddbb79b

https://github.com/Expensify/App/assets/93399543/1c3b4737-22a7-4f69-8e9c-d665382b95c7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688237522062879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
@mountiny Curious for your advice on this one as well. I'm not sure this is truly a bug based on the react navigation design. What do you think?

**Comment by mountiny** [comment]
This one is odd, lets add it to the tracking project

@SofoniasN what if you dont open the popover and go back, is the behaviour different?

**Comment by SofoniasN** [comment]
@mountiny The page still loads and takes user to different places despite opening the popover.

**Comment by SofoniasN** [comment]
@mountiny The page still loads and takes user to different places despite opening the popover.
https://github.com/Expensify/App/assets/85386553/3755a21a-56d3-4796-b15b-f9b3d8d496c5

**Comment by mountiny** [comment]
@JmillsExpensify I dont think this is a bug, the modal is not its own page and so the android back button does not interact with whether the modal is open or not. Same as on iOS user can click above the menu to dismiss it.

what do you think?

**Comment by mountiny** [comment]
I think we can close this one
