### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Android - The app incorrectly adds an emoji different from the user's selection.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22091]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Open a chat
2. Type something and select an emoji quickly

## Expected Result:
The app should add the emoji that the user selected.

## Actual Result:
The app incorrectly adds an emoji different from the user's selection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fb228a69-8d3d-4372-a517-cdee53cff014

https://github.com/Expensify/App/assets/93399543/1f4d73b4-b8a6-4784-bf65-203de4cb318d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688244448468399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de3cec3401f33d1b</li>
        <li>Upwork Job ID: 1675653894415933440</li>
        <li>Last Price Increase: 2023-07-02</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Ok, so I can somewhat replicate this on a Pixel 3a. I suspect the issue is that there's a delay with the emoji picker, so when you're trying really fast and choose something, there's a chance the wrong emoji will be selected.

**Comment by waterim** [comment]
Hi!
I'm Artem from Callstack - expert contributor group
Maybe I can help with this one?

**Comment by jliexpensify** [comment]
Have assigned you @waterim

**Comment by waterim** [comment]
Not a proposal.
2 more things I found:
Issue exists on IOS as well
Issue exists even with a fast clicking, emoji hit box is moved to the left for each emoji

**Comment by waterim** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The app adds different(wrong) emoji from the user's selection.
### What is the root cause of that problem?
The issue here is a hitSlop in Pressable component, because of the fast typing and fast opening of the Modal useAutoHitSlop hook is not able to calculate the right hitSlop.
**Files we are working with**:
CategoryShortcutButton.js
EmojiPickerMenuItem.js
### What changes do you think we should make in order to solve the problem?
In order to fix the hitSlop we can disable auto hitSlop just by adding "shouldUseAutoHitSlop" to false.
With that solution we will have a correct hit container for each emoji and category icons.
### What alternative solutions did you explore?
N/A

**Comment by narefyev91** [comment]
Proposal from @waterim looks good to me https://github.com/Expensify/App/issues/22091#issuecomment-1625640321
🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment]
Hi, sorry for the delay in reviewing, I didn't have time. I see there's already a PR and the proposal makes sense, let's go with that.

**Comment by jliexpensify** [comment]
Hired Mejed. @narefyev91 can you add your Upworks name to your GH profile? I can't find you, cheers.

**Comment by narefyev91** [comment]
> Hired Mejed. @narefyev91 can you add your Upworks name to your GH profile? I can't find you, cheers.

@jliexpensify Hey! No worries - i'm from Callstack - no needs payment from Upworks

**Comment by francoisl** [comment]
This was deployed to production already, the automation didn't work because the PR refered to this issue as `$ [#22091](https://github.com/Expensify/App/issues/22091)` instead of `$ https://github.com/Expensify/App/issues/22091`... Going to manually adjust the labels and title.

**Comment by jliexpensify** [comment]
Thanks Franc, appreciate it!

**Comment by jliexpensify** [comment]
On HOLD

**Comment by jliexpensify** [comment]
Oh sorry, I missed this! Summarising payments:

- Bug Reporter: @mejed-alkoutaini $250
- Contributor: @waterim $1000 (Callstack - invoiced separately)
- C+: @narefyev91 $1000 - I can't find you on Upworks, can you apply for the job?

Upworks job [here](https://www.upwork.com/jobs/~01de3cec3401f33d1b).

@francoisl do we need a checklist to be completed?

**Comment by narefyev91** [comment]
> Oh sorry, I missed this! Summarising payments:
> 
> * Bug Reporter: @mejed-alkoutaini $250
> * Contributor: @waterim $1000 (Callstack - invoiced separately)
> * C+: @narefyev91 $1000 - I can't find you on Upworks, can you apply for the job?
> 
> Upworks job [here](https://www.upwork.com/jobs/~01de3cec3401f33d1b).
> 
> @francoisl do we need a checklist to be completed?

Hey! I'm from Callstack no needs any payment in upwork, thanks!

**Comment by francoisl** [comment]
👍 so @jliexpensify we'll just need the Bug Reporter payment I believe.

> @francoisl do we need a checklist to be completed?

I think this was an issue since the original emoji implementation and not a regression per se, so I'd say we can skip the checklist.

**Comment by jliexpensify** [comment]
Looks like I paid Mejed already last week but never ended the contract or closed the job. Doing that now!

![image](https://github.com/Expensify/App/assets/30815269/d4a5cac3-c9c2-44d2-9ed2-9397321eead9)
