### ISSUE TITLE
Inconsistent Margin on Right and Left side of List in birthdate year picker screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to profile -> Personal Details
2. Click Date of birth
3. Click on year to change birth year

## Expected Result:
There should be no margin on both sides like other screens

## Actual Result:
There is margin on both left and right side of birth year list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ed87a70a-1af5-47df-84e3-cc85db18148d

https://github.com/Expensify/App/assets/93399543/dbef6bd2-db6c-4c16-8093-1c0459c4ffe3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688242403351509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by priya-zha** [comment]
https://github.com/Expensify/App/issues/21262 Dupe.

**Comment by sonialiap** [comment]
Selection list are being refactored. Closing this

https://github.com/Expensify/App/issues/11795
