### ISSUE TITLE
[$1000] Web - Clicking on browser back button brings back the removed thread from LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Reply in thread from account B
3. Observe the thread shows up on LHN
4. Delete the reply from account B
5. Click on another chat and observe the thread gets removed from the LHN
6. Click on the browser back button

## Expected Result:
The removed thread should not show up again on the LHN

## Actual Result:
The removed chat shows up again on the LHN even if there is no reply in it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/62c76aa7-2a0f-4186-b8f1-2fc397bb40f3

https://github.com/Expensify/App/assets/93399543/6eed4bf6-aa18-4193-9a24-6a971612239c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688210657901479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f23644d73f19ac7</li>
        <li>Upwork Job ID: 1678872296611127297</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
I can't reproduce. @Nathan-Mulugeta anything I should be doing differently here?


https://github.com/Expensify/App/assets/22508304/8b8ba96e-40df-42a0-89c2-1e3857234ce6

**Comment by Nathan-Mulugeta** [comment]
I am still able to reproduce it, I will attach a video below. One thing I have noticed is that when clicking back the removed thread appears down at the bottom of the chat list on LHN. Have you checked it down the list there? And also it might be easily visible if you test this on a new account, just to minimize any confusion with many of the chats. @mallenexpensify 

https://github.com/Expensify/App/assets/111440031/3e99d041-da53-47b5-9cf5-a5f3fec5268b

**Comment by mallenexpensify** [comment]
Thanks @Nathan-Mulugeta , I was able to reproduce with a fresh account. 
Checking here to see if it's related to 'dynamically updating' or not
https://expensify.slack.com/archives/C01GTK53T8Q/p1689046709870159?thread_ts=1688646398.596839&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689053575554139?thread_ts=1688646398.596839&cid=C01GTK53T8Q) @mountiny posted
> this is different related to navigation refactor

I'm going to move this along via the External tag and we can fix these bugs independently (unless anyone disagrees)

**Comment by ShogunFire** [comment]
What is the expected behaviour when we remove a thread ? Should it appear in the LHN or not ?

**Comment by mountiny** [comment]
If you leave a thread you should not see it in LHN

I thinkI would put his on hold for the SWM work, this has same rootcause as many other issues we got and not sure of the best solution so far

**Comment by mallenexpensify** [comment]
Thanks @mountiny, I'm going to remove Bug too for now since it's on hold and might be a while til we get to.

**Comment by mallenexpensify** [comment]
On hold

**Comment by adamgrzybowski** [comment]
Hey, I am thinking do we really want to remove this thread from the history? 

After deleting the response the user is not redirected to another page. This is still a page that the user can access to write a new response

Same if the user just.
1. Presses reply in thread
2. Select another chat without replying

Should this be removed from history? What would be the exact condition to remove the thread screen from history? 

What if the user opens a thread just to read other people's replies? Should this also be removed from history?

**Comment by mallenexpensify** [comment]
@kbecciv @Nathan-Mulugeta, can you please retest to see if the issue is reproducible?  I took this off hold, the below was closed
- #20908

**Comment by Nathan-Mulugeta** [comment]
Hey @mallenexpensify I just retested this and it is still reproducible. 

https://github.com/Expensify/App/assets/111440031/8ca361c5-00c2-43e6-a601-9d6b654a2a65

**Comment by mallenexpensify** [comment]
Checking here to see if we  have a higher-level plan for back/forward navigation and if we want to put navigation issues on hold 
https://expensify.slack.com/archives/C01GTK53T8Q/p1696255673662679

**Comment by mountiny** [comment]
I think this is not a bug, I am sorry I did not catch this earlier but I think deleting the message and leaving should not clear this from the history and clickign back takes you back to the thread

**Comment by mallenexpensify** [comment]
Thanks Vit
