### ISSUE TITLE
 Android - Html Entity &lt; in title are displayed as special characters in notification (works well if sent via chat))

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to mweb or web and login with User A (Make sure to login with User B on android)
2. From User A, click on FAB icon and click on assign task
3. On title, enter HTML Entity like &lt; or &gt; and on the assignee select User B
4. Create a task and notice that on the notification from User's B side, it displays symbols
5. But if you send the same &lt; via chat, we don't get such symbols on the notification

## Expected Result:
Html Entity shouldn't be converted into symbols

## Actual Result:
Html Entity &lt; in the title are displayed as special characters on notification (works well if sent via chat))

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b3d011a4-a2dc-439b-8749-98aef16fec55

https://github.com/Expensify/App/assets/93399543/dc73ea70-4e40-407c-a8a3-2989e40384ee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688221652276439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Handling tomorrow

**Comment by muttmuure** [comment]
I'm not super convinced this is an unexpected outcome, or one that particularly matters. Happy to discuss in Slack.
