### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Web - Split bill with a new user displays 'undefined owes' on staging

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Click on FAB icon and click on split bill
3. (IMP step)- Now search for a new user that has NO Expensify account and split the bill with the user
4.  Notice that for a small period of time it displays 'undefined' owes on the report
5. Follow the same steps on production ,  no such problem occurs

## Expected Result:
Split bill with a new user should not display 'undefined'

## Actual Result:
Split bill with a new user displays 'undefined owes'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8bc8f761-066f-4d62-8712-c6d615516ca3

https://github.com/Expensify/App/assets/93399543/364d8cf7-4640-4728-8364-626713f3cab2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688373739740659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162160db7d748962b</li>
        <li>Upwork Job ID: 1676900194451750912</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by madmax330** [comment]
Discussed here: https://expensify.slack.com/archives/C03TQ48KC/p1688391023413499?thread_ts=1688389934.788359&cid=C03TQ48KC

Since it is also happening in prod it's not a blocker.

**Comment by Julesssss** [comment]
Thanks, removed it from the [checklist](https://github.com/Expensify/App/issues/21967) 👍

**Comment by madmax330** [comment]
Passing off to @Beamanator since it's related to the accountID migrationl

**Comment by Beamanator** [comment]
Making external b/c it looks like this has to do with optimistic personal details - @narefyev91 looks like you're auto-assigned to review proposals! We already have 1 above it looks like 👍

**Comment by narefyev91** [comment]
> Making external b/c it looks like this has to do with optimistic personal details - @narefyev91 looks like you're auto-assigned to review proposals! We already have 1 above it looks like 👍

No problem at all

**Comment by narefyev91** [comment]
Agree that we should have work with optimistic personal details
Proposal from @allroundexperts looks good to me https://github.com/Expensify/App/issues/22104#issuecomment-1618247771
🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment]
Unassigning you @MonilBhavsar since I was already assigned here :D 👍

**Comment by Beamanator** [comment]
@narefyev91 @allroundexperts just to be clear, if we create a new optimistic entry in Onyx we need to clean it up at some point, right? Maybe in `successData` or `failureData` of the API command(s)?

**Comment by MonilBhavsar** [comment]
May be we can fix this auto assigner issue 👍 😄

**Comment by Beamanator** [comment]
AFAIK we don't ever send the optimistic accountID to the backend, because there's nothing we do with it there - if the account doesn't exist yet, we create it (which automatically assigns a new accountID in sequence) and send that updated data back in Onyx

**Comment by Beamanator** [comment]
Yeah we can fine-tune in the PR 👍  Let's just make sure to watch out for the optimistic data sticking around longer than it should 👍

**Comment by CortneyOfstad** [comment]
@Beamanator and @allroundexperts — where are we at with this? Anything needed from my side? TIA!

**Comment by Beamanator** [comment]
@CortneyOfstad looks like the PR is on staging! https://github.com/Expensify/App/pull/22401#issuecomment-1633424352

**Comment by CortneyOfstad** [comment]
@priya-zha and @allroundexperts I've extended contracts your way — please let me know once you accept in Upwork, and I can get those paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment]
@allroundexperts You do get the bonus, and I'll cancel the contract in UpWork — thank you!

**Comment by CortneyOfstad** [comment]
@priya-zha contract has been paid! Closing this out!

**Comment by anmurali** [comment]
Approved 1500 to Sibtain based on https://github.com/Expensify/App/issues/22104#issuecomment-1646083977
