### ISSUE TITLE
console error (TypeError) when clicking on the logo

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open inspect
2. Click on the Expensify logo
3. See error in console

## Expected Result: 
no error in the console
## Actual Result: 
console error: prevel.js:530 Uncaught TypeError: this.elements[0][cn].split is not a function
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:**
**Reproducible in staging?:** Applause not able to reproduce
**Reproducible in production?:**  Applause not able to reproduce
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/95f0d601-2946-4ab9-994a-d384495c90aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688105097250699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Not reproducible. Have commented on the slack thread asking for clearer steps. @mauri-salazar, feel free to post your steps here.
![2023-07-05_10-43-09 (1)](https://github.com/Expensify/App/assets/42940078/0599990b-ba22-447f-85b0-5e7688938d59)
