### ISSUE TITLE
[HOLD for payment 2023-07-14] [HOLD for payment 2023-07-12] Blue box is seen if you click on the line above the members

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any workspace and invite few members
3. On members page, try to click on the horizontal line above each of the members and notice the blue line box appears
## Expected Result: 
Blue box should not be seen if you click on the line above the members
## Actual Result:
 Blue box is seen if you click on the line above the members

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-1
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71e3ff80-7b2d-4d12-b074-a32b3a213e1d

https://github.com/Expensify/App/assets/43996225/a40d442c-a577-4c05-8421-9f763e9a9309

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688396034796279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@priya-zha here is an Upworks job for your bonus payment https://www.upwork.com/jobs/~01655785911f54442e

**Comment by priya-zha** [comment]
Thanks. Accepted.

**Comment by jliexpensify** [comment]
@iwiznia I've paid Priya and removed the job in Upworks.

Once this blocker is sorted, feel free to close the GH - I don't think I need to do anything else? I'll be OOO the rest of this week :)

**Comment by Julesssss** [comment]
Thanks for the quick fix!

**Comment by iwiznia** [comment]
PR https://github.com/Expensify/App/pull/21399
I don't think we need to add a regression for this, it was a mistake to change this to begin with that stemmed from a misunderstanding

**Comment by iwiznia** [comment]
I am confused why this posted twice. I assume I don't need to do anything else.

**Comment by jliexpensify** [comment]
Yeah, the payment is taken care of [here](https://github.com/Expensify/App/issues/22119#issuecomment-1619474724).

**Comment by jliexpensify** [comment]
Going to close this, as payment is handled and no checklist needs to be completed.
