### ISSUE TITLE
[HOLD for payment 2023-07-14] [HOLD for payment 2023-07-12] Already selected members disappears after you search for new members

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On staging web chrome > Create a new workspace > Invite members
2. Click on Invite
3. Now on search bar, type the email of a new user and select it
4. Now immediately, remove the previous user email and now try to search with the email of a different user and select it and notice that the old user that you selected on step 3 gets disappeared. Now if you click on invite, only the last user gets selected
5. If followed the same on production, the old selected users never disappears
## Expected Result: 
The old selected members should not disappear after you search for new members
## Actual Result: 
The old selected members disapperas after you search for new members

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/09340be8-784b-43d1-b2c2-f0494bee8467

https://github.com/Expensify/App/assets/43996225/eb6987c5-671e-4356-81fa-f5e50ac34687

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688395631136579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b0dacfaa4c2503c</li>
        <li>Upwork Job ID: 1679184518209077248</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by flodnv** [comment]
@s-alves10 can you please check this? https://github.com/Expensify/App/pull/21700#pullrequestreview-1511446993

**Comment by Julesssss** [comment]
PR is in review [here](https://github.com/Expensify/App/pull/22132#pullrequestreview-1512549280)

**Comment by Julesssss** [comment]
PR merged, removing the label

**Comment by Christinadobrzyn** [comment]
@rushatgabhane let me know if we need a regression test for this!

**Comment by Christinadobrzyn** [comment]
- Ready for payment @rushatgabhane do you want to be paid through NewExpensify? 
- Is there a regression test needed for this?

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until July 31st so going to unassign and assign a new teammate. 

At this time, we're just waiting on a response to https://github.com/Expensify/App/issues/22123#issuecomment-1636232289

**Comment by mallenexpensify** [comment]
@rushatgabhane is paid outside of Upwork. 
@avi-shek-jha, can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~012b0dacfaa4c2503c

**Comment by avi-shek-jha** [comment]
> @rushatgabhane is paid outside of Upwork. @avi-shek-jha, can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~012b0dacfaa4c2503c

@mallenexpensify I have applied. Thank You.

**Comment by mallenexpensify** [comment]
Thanks @avi-shek-jha , I've hired you.

**Comment by mallenexpensify** [comment]
@avi-shek-jha paid!  
@rushatgabhane can you please fill out the checklist above?
https://github.com/Expensify/App/issues/22123#issuecomment-1625184077

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
This has been paid on new dot https://staging.new.expensify.com/r/701637755905470

And checklist is complete. This issue can be closed.
