### ISSUE TITLE
Web -  Infinite log api calls on entering wrong magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Signout if you are logged in and open networks tab
2. Enter an email
3. Enter wrong magic code

## Expected Result:
Log api calls shouldn't be made every second like this

## Actual Result:
 Log api calls every second

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ce807ffc-e4be-49fd-8f2b-9b6cabfa9ecd

https://github.com/Expensify/App/assets/93399543/fa89842e-d0d7-439a-a2bf-cac264f0695e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688288272964789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2acfae0eadbcd04</li>
        <li>Upwork Job ID: 1678423102719717376</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
I looked at this earlier - seems internal

**Comment by muttmuure** [comment]
I'm going back and forth on this. I'm not sure it has an end-user impact, and you can just delete the digits to try again.
