### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Web - Still old Thread message is shown on the public room even after deletion

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go to staging dot on web chrome
2. Create a new room in public mode
3. Go to room header, copy the URL
4. Now send a message on the room (let's say hello). Then click on reply thread so that a new thread page opens up and send a new message.
5.  Now open an incognito window and paste the room URL copied earlier
6. On Incognito window, click on "1 Reply thread" of the User's A 'hello' message so that a thread page appears
7. Now from User A, delete the original message (hello in our case)
8. On incognito window, again go to the thread page and notice that 'deleted message' appears everywhere but is not updated on the bottom area. But if you refresh the page, it updates properly.

## Expected Result:
'Deleted message' should be shown on the public room

## Actual Result:
 Old thread message is shown on the thread page of the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2acff7da-b98f-447d-9096-084a96af2945

https://github.com/Expensify/App/assets/93399543/3d8611cd-37bd-474b-b440-1be8a5938349

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688288249670349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012822a83fb249af39</li>
        <li>Upwork Job ID: 1676277777324867584</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
hey @0xmiroslav what do you think of the proposal above from @bernhardoj ?

**Comment by zanyrenney** [comment]
bump @0xmiroslav on reviewing the proposal please?

**Comment by zanyrenney** [comment]
Let me know if there are any blockers here @0xmiroslav happy to help! thanks!

**Comment by zanyrenney** [comment]
bump @0xmiroslav please

**Comment by MariaHCD** [comment]
Evaluating the recommended proposal now!

**Comment by zanyrenney** [comment]
@bernhardoj @0xmiroslav -please accept the invite to this job so I can pay you out for the work + urgency bonus.

**Comment by zanyrenney** [comment]
@0xmiroslav please accept offer.

**Comment by zanyrenney** [comment]
waiting on @0xmiroslav payment.

**Comment by zanyrenney** [comment]
DM'd @0xmiroslav to see how we can progress to close this out.

**Comment by zanyrenney** [comment]
Closing as per @0xmiroslav request!
