### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Secondary contact method page displays 'Hmm its not here' page on opening it using deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should have 1 verified secondary contact method
1. Open the app
2. Open settings
3. Open profile
4. Open contact method
5. Select secondary contact method (non default contact method)
6. Copy the URL and logout
7. Paste the URL and login
8. Observe that it displays 'Hmm its not here' page for few seconds before displaying the proper contact method page

## Expected Result:
App should display contact method with set as default and remove button if we open secondary contact method with deep link

## Actual Result:
App displays 'Hmm its not here' page for few seconds before displaying proper page if we open secondary contact method with deep link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/26882198-683d-4e13-a70c-53913329314f

https://github.com/Expensify/App/assets/93399543/7971d1be-1fa7-4f26-bb66-a2a53a2ca7d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688277743137189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010166f0ecddb53713</li>
        <li>Upwork Job ID: 1676205946766311424</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
@allroundexperts what do you think about the proposals above?

**Comment by joelbettner** [comment]
> We should only show it until we already loaded reportData. Otherwise we can show a loading view or skeleton.

@allroundexperts @hungvu193 I'm a bit confused. Since it is the `loginList` that hasn't loaded yet, why do we need to wait for `reportData` to be loaded before evaluating that conditional?

**Comment by joelbettner** [comment]
Ok, I think I've wrapped my head around that. We are good to go. @allroundexperts we can move forward.

**Comment by flaviadefaria** [comment]
Assigned @hungvu193 to the issue.

**Comment by joelbettner** [comment]
@allroundexperts @flaviadefaria just a gentle bump here.

**Comment by flaviadefaria** [comment]
@dhanashree-sawant can you please do what's requested [here](https://github.com/Expensify/App/issues/22120#issuecomment-1637737365) so that we can pay you?
@hungvu193 you've been paid!
@allroundexperts you're good to make the request in ND

**Comment by dhanashree-sawant** [comment]
Contributor details
Your Expensify account email: dhanashree.dattaram.sawant@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016c7b8ae165dc0bda

**Comment by dhanashree-sawant** [comment]
@flaviadefaria done

**Comment by flaviadefaria** [comment]
Thank you @dhanashree-sawant I just sent you an offer!

**Comment by flaviadefaria** [comment]
We're all set to close this once @allroundexperts gets paid.

**Comment by flaviadefaria** [comment]
Still waiting, will switch this to weekly in the meantime since there's no more action for me to take here.

**Comment by JmillsExpensify** [comment]
Reviewed details for @allroundexperts. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by JmillsExpensify** [comment]
P.S. @flaviadefaria you can close.
