### ISSUE TITLE
Web - Profile picture is not updated on public room even after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22134]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new room in Public mode
3. Send a message in room - very Imp step
4. Click on room header and copy the share room URL
5. Open an incognito window and paste the room URL as an anonymous user
6. Now Go back to User A and change the profile picture of User A
7. On incognito window, notice the profile picture is not updated. Refresh the page and notice that even after refreshing the page, profile picture is not updated.

## Expected Result:
Profile picture should be updated on public room

## Actual Result:
Profile picture is not updated on public room even after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aeb958f0-ce48-4303-a2f5-1cee76fbb40c

https://github.com/Expensify/App/assets/93399543/44a5587a-753b-4d29-a708-1a737bab0143

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688289180818999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
This is ultimately the same issue as https://github.com/Expensify/App/issues/21488. 

Going to go ahead and close as a dupe.
