### ISSUE TITLE
[HOLD #16660] [$1000] Web - "S" label beign selected when clicking on the arrow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on your avatar
2. Go to profile settings
3. Go to personal details
4. Select Date of Birth option
5. Click on the Month arrow

## Expected Result:
The labels shouldn't be selectable and the user should be able to navigate through the months smoothly without "S" label being selected

## Actual Result:
 clicking on the arrow 3 times for example changes the month once and it selects the "S" label, and the user is not able to navigate through the months smoothly without "S" label being selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5903b5d2-a912-46a3-8d8b-10d176ca02ff

https://github.com/Expensify/App/assets/93399543/75adc279-e225-46d5-b8a0-039e44b7101b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688317447895809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b71144b2d92bd9a</li>
        <li>Upwork Job ID: 1676184442338570240</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Putting on hold

**Comment by dylanexpensify** [comment]
@parasharrajat any update on this one?

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
still on hold!

**Comment by dylanexpensify** [comment]
H - O - L - D

**Comment by dylanexpensify** [comment]
on hold, @Santhosh-Sellavel shall we move to weekly?

**Comment by Santhosh-Sellavel** [comment]
@dylanexpensify Yes I guess

**Comment by sophiepintoraetz** [comment]
@parasharrajat - do you have an idea on when the react native upgrade will happen? @ginsuma suggested that we put #23402 on hold because it's a similar behaviour?

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
Reviewing!

**Comment by dylanexpensify** [comment]
Hold - @parasharrajat any update?

**Comment by dylanexpensify** [comment]
TY

**Comment by dylanexpensify** [comment]
still in progress

**Comment by dylanexpensify** [comment]
Holding still!

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
holding

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
Holding

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
@parasharrajat any updates? Shall we see if this is even reproducible now?

**Comment by dylanexpensify** [comment]
yeah can't repro
