### ISSUE TITLE
[$1000]  Task assigned to you appears even if task is not assigned to self

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account
2. Click on FAB > assign task
3. Paste account B's email and assign task to account B
4. Open task thread and click on the assignee
5. Paste account B's email again and select account B
6. Notice a new thread is created on the LHN that says "account B's has assigned a task to you"
## Expected Result: 
Since account B was assigned "Account B has assigned a task to you" should not appear.
## Actual Result: 
Even if account B is still assigned task has been assigned to you appears on the LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/04ae9f3e-6698-443c-9f18-083e07cea20e

https://github.com/Expensify/App/assets/43996225/a7a94542-5dfb-4ae5-b900-f9d4ada376e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688370373333169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e192f7953e61d635</li>
        <li>Upwork Job ID: 1677361842104233984</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
@s77rt - how is the proposal?

**Comment by thienlnam** [comment]
This is NAB - works as intended. If we want to revisit the copy later we will have to update the the BE as well
