### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000]  Main task description updated when Sub-Task description is modified

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22150]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Navigate to the "Assign Task" section
3. Enter the task title and select any user as the assignee
4. Click "Confirm Task" to create the task
5. Click "Assign Task" again to create a sub-task
6. Enter a title for the sub-task and click "Confirm Task"
7. Click on the sub-task description, enter new information, and save
## Expected Result: 
Modifying the sub-task description should not update the main task's description
## Actual Result: 

The main task's description is updated when the sub-task description is changed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3e67afdb-6b16-4ffd-bb03-230df1d5a4e9

https://github.com/Expensify/App/assets/43996225/c779497a-4311-4878-a638-65b4a6197710

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688377792866249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01819f3be17785fa30</li>
        <li>Upwork Job ID: 1676369818952953856</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@thienlnam  This is also task related task

**Comment by sophiepintoraetz** [comment]
Reproduced! @samh-nl, this is more of an FYI as Jack is doing some task polish, but I don't see this being covered by the list of issues https://github.com/Expensify/Expensify/issues/290076 so I think you're good to make a proposal!
![2023-07-05_11-14-40 (1)](https://github.com/Expensify/App/assets/42940078/b26169a2-93e8-4c6d-af20-d82c7d3f690f)

**Comment by narefyev91** [comment]
@tienifr as i see in your video - when user fill sub task and click save - user still stay on the sub task area, and to get to main task you need to open it in the left menu.
Current behaviour - when you fill sub task, and click save - it's automatically redirects your to main task (and you see subtask in the bottom). Can you please clarify @sophiepintoraetz which expected behaviour should be here

**Comment by narefyev91** [comment]
> > Current behaviour - when you fill sub task, and click save - it's automatically redirects your to main task (and you see subtask in the bottom)
> 
> @narefyev91 I think it's our bug. When I reload the page and update the sub task, I still stay on the sub task area. Please check the video below:
> 
>  Screen.Recording.2023-07-05.at.16.58.41.mov

Ohh yup - you are right - well based on all this information proposal of @tienifr looks good to me https://github.com/Expensify/App/issues/22150#issuecomment-1619942135
🎀 👀 🎀 C+ reviewed

**Comment by sophiepintoraetz** [comment]
@tienifr - payment sent!
@ayazhussain79 - reporting offer sent
@narefyev91 - once you've completed the checklist, I can release payment

FYI you were eligible for the timeline bonus.

**Comment by amyevans** [comment]
Nicolay is with Callstack so no Upwork payment 😄. He's also [on vacay the next couple weeks](https://expensify.slack.com/archives/C02NK2DQWUX/p1689181046746099) so I completed his portion of the checklist above. For regression steps, we can use:

1. Open a chat
2. Navigate to the "Assign Task" section
3. Enter the task title and select any user as the assignee
4. Click "Confirm Task" to create the task
5. Click "Assign Task" again to create a sub-task
6. Enter a title for the sub-task and click "Confirm Task"
7. Click on the sub-task description, enter new information, and save
8. Verify that modifying the sub-task description should not update the main task's description
