### ISSUE TITLE
Remove RN patch once upstream PR38074 is merged

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22155]
cc @adamgrzybowski 

In this PR we have added a RN patch which fixed one bug https://github.com/Expensify/App/pull/21124/ and also created an upstream RN fix to get this out to the core codebase https://github.com/facebook/react-native/pull/38074

Lets remove the patch once we update to new RN version including this fix.

**Comment by mountiny** [comment]
holding

**Comment by mountiny** [comment]
Not merged yet

**Comment by mountiny** [comment]
soon should be ready to be removed

**Comment by mountiny** [comment]
@adamgrzybowski How is this one looking, what RN version should this be part of?

**Comment by mountiny** [comment]
@j-piasecki Will this patch be removed in the RN upgrade? Can I assign you if so and close this issue once we merge it?

**Comment by j-piasecki** [comment]
Yes, the PR with RN upgrade will also remove this patch.

> Can I assign you if so and close this issue once we merge it?

Go ahead

**Comment by mountiny** [comment]
This was removed in the PR, closing
