### ISSUE TITLE
Web - The "Edit message" option is not displayed on sent messages after changing the default contact method until reloading the report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22165]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: Account A has some contact methods added
1. Log in as Account A
2. Open any chat report that has messages sent by Account A  
3. check that there is an Edit option on each of these messages
4. Open Profile settings >> select any contact method and “Set as default”
5. Re-check the chat report step #1
6. Hover on these messages to view options

## Expected Result:
Edit message option should still be displayed and there is NO  “Flag as offensive” option

## Actual Result:
The Edit message option is NOT displayed until RELOAD the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2d6efe84-b473-47df-a45b-507b8eefcecf

https://github.com/Expensify/App/assets/93399543/821f917c-ebad-4464-9496-de7158f42324

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688325484455269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tranvantoan-qn** [comment]
@kushu7 
Yeah, It looks like so,

And I'm sorry if it's not appropriate to ask. But since I can provide more information which is "until reloading the report" - it may help fix the issue easier and more comprehensively proposals.  Can I still can get a part of bug bounty?

**Comment by sakluger** [comment]
Yes, this is a dupe, closing in favor of https://github.com/Expensify/App/issues/21948.

@tranvantoan-qn it's fine to ask! Right now, we're only offering a bug reporting bonus to a single reporter for each issue. We expect bug reports to be complete, so while it's sometimes helpful when others add additional details, we can't compensate for that.
