### ISSUE TITLE
Web - Spacing inconsistency - No margin between Copy and copy icon in 2FA Step 1 page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22170]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > security > 2FA
2. Observe the Copy button and the icon beside it
3. Open any chat and click on the  header
4. Observe the email and the copy icon beside it and compare it with step 2

## Expected Result:
Copy icon should have consistent margin through out the app

## Actual Result:
There is no margin between copy and copy icon in 2FA page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/34a9312a-27dd-4a0c-8adc-618e0b2ee8fd

https://github.com/Expensify/App/assets/93399543/37e8a01f-155c-4433-b67b-8f2dbeb8422a

**Expensify/Expensify Issue URL:**
**Issue reported by:** Nathan Mulugeta
React JS development and Quality Assurance (GH @Nathan-Mulugeta)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688457306999739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
^ I agree not a bug
