### ISSUE TITLE
[$1000] Home Address page - Unable to enter more than 50 characters in the First address line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with a brand new account
3. Navigate to Settings -> Profile -> Personal details
4. Navigate to Home address page
5. Start typing address that contain more than 50 characters into Address line 1 field

## Expected Result:
The user should be able to add more than 50 characters into Address line 1 field

## Actual Result:
The user is not able to add more than 50 characters into Address line 1 field.
Also, there is no error message about limit if it is present for this field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6e73f263-1168-4b48-80fe-354fe8060d7e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131ac4e9a67babac9</li>
        <li>Upwork Job ID: 1677157369807974400</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
I agree a growl should be shown but I'm not sure where the rationale for more than 50 chars being allowed is ([also checking internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1688519219004499))

@lanitochka17 - can you confirm why you think more than 50 characters should be allowed?

**Comment by lanitochka17** [comment]
@sophiepintoraetz  According to step 3 in the section Home Address page - US Address in Test Rail:
https://expensify.testrail.io/index.php?/tests/view/3515388
![50 character](https://github.com/Expensify/App/assets/78819774/13d80574-b9ea-4eee-b7d0-c5443d07bf83)

**Comment by sophiepintoraetz** [comment]
@lanitochka17 - can you confirm whether the 50 character limit comes from Google places API?

**Comment by lanitochka17** [comment]
@sophiepintoraetz If it's the expected 50 character limit, then there should be a message that you're over the limit.

**Comment by sophiepintoraetz** [comment]
@lanitochka17 - I am aware of that, but I am asking where the 50 character limit is coming from - I agreed back [here](https://github.com/Expensify/App/issues/22173#issuecomment-1620880609) that there needed to be a growl.

**Comment by sophiepintoraetz** [comment]
From [internal discussions](https://expensify.slack.com/archives/C01GTK53T8Q/p1688700375295979?thread_ts=1686863510.616919&cid=C01GTK53T8Q), it's super unlikely someone is going to need more than 50 chars for the first line so the solution needs to include a growl for 50 characters.

**Comment by s77rt** [comment]
@sophiepintoraetz I'm not sure we want to fix this. Shouldn't we just update the testrail test? It was probably written before limiting the address field.

**Comment by sophiepintoraetz** [comment]
@s77rt how do you mean update the test rail? I think we still want to throw a growl when a user has reached 50 characters, right?

**Comment by sophiepintoraetz** [comment]
Ah, I see - I could have sworn that we had character limits elsewhere but seems like we have changed that - you're right @s77rt! We'll close the issue and I've updated the test case with your suggestion - thank you!!
