### ISSUE TITLE
[HOLD for completion checklist] [$1000]  Invalid number stays in contacts list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start a new chat with an invalid number, for example +916541237890
2. Close the error
3. Click on FAB > New chat
## Expected Result: 
The invalid number should not appear on the contact list
## Actual Result: The invalid number stays in th
e contact list

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ee96c10e-9864-4aa2-be2c-b9528cebd3e5

https://github.com/Expensify/App/assets/43996225/f806b1a3-6bba-40ef-bdd8-8814c4fcc228

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688409641152459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bc8c0b49aadb102</li>
        <li>Upwork Job ID: 1677361800252989440</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by omarirfan68** [comment]
how can i send proposal in github?
to apply for job

**Comment by omarirfan68** [comment]
Contributor details
Your Expensify account email: <REPLACE EMAIL HERE>
Upwork Profile Link: <REPLACE LINK HERE> where to write this !!!

**Comment by omarirfan68** [comment]
Contributor details
Your Expensify account email: omarirfanmuhammad68@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/omarirfan

**Comment by omarirfan68** [comment]
now how can i submit the proposal

**Comment by twisterdotcom** [comment]
Just follow the format like [this](https://github.com/Expensify/App/issues/22209#issuecomment-1620610279).

**Comment by twisterdotcom** [comment]
@narefyev91 - how are the proposals here?

**Comment by narefyev91** [comment]
Proposal of @dukenv0307 looks good to me - https://github.com/Expensify/App/issues/22209#issuecomment-1620610279
🎀 👀 🎀 C+ reviewed

**Comment by danieldoglas** [comment]
Member assigned.

**Comment by twisterdotcom** [comment]
Hiya folks. I'm OOO today, but just today. If you absolutely need payment today, please reach out in the open source slack channel. Otherwise, I'll do these tomorrow. Thanks!

**Comment by twisterdotcom** [comment]
External issue reporter: @Nathan-Mulugeta has a $250 payment offer here: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25751205
Contributor that fixed the issue: @dukenv0307 paid $1500 here: https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/34187160
Contributor+ that helped on the issue and/or PR: @narefyev91 is from Callstack.

@narefyev91 - we need the checklist completing here before this can be closed please: https://github.com/Expensify/App/issues/22209#issuecomment-1638749327
