### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Dev : closing the keyboard shows a warning on dev.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the dev app.
2. Go to any chat.
3. Tab composer to open the keyboard.
4. Hide the keyboard by dragging down.
## Expected Result: 
No warnings are shown.
## Actual Result: 
A warning is shown(See the attachment).

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-02 at 1 47 53 PM](https://github.com/Expensify/App/assets/43996225/98a476d2-9f2f-44cc-a740-4e634994a2c0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688406249179949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135902153bfc14487</li>
        <li>Upwork Job ID: 1678296096048033792</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
posted to slack to get someone with a dev acct to repro this

**Comment by robertjchen** [comment]
Thanks- the proposal makes sense to me! Assigning to @ntdiary

**Comment by dylanexpensify** [comment]
@0xmiroslav can we get an update on proceeding here? TY! 🙇‍♂️

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
@0xmiroslav any update here?

**Comment by dylanexpensify** [comment]
Yes, thanks for the bump. Summarizing pay outs for the issue:
- Issue reporter: @parasharrajat $250
- Contributor: @ntdiary $1000
- Contributor+: @parasharrajat $1000

Upwork job is [here](https://www.upwork.com/jobs/~0135902153bfc14487).

**Comment by dylanexpensify** [comment]
apologies, UPDATE:

Summarizing pay outs for the issue:

Issue reporter: @parasharrajat $250
Contributor: @ntdiary $1500
Contributor+: @0xmiroslav $1500
Upwork job is [here](https://www.upwork.com/jobs/~0135902153bfc14487).

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by dylanexpensify** [comment]
Offer sent @ntdiary!

**Comment by dylanexpensify** [comment]
@ntdiary will send payment for correct amount of $1,500!

**Comment by dylanexpensify** [comment]
Payment sent/contract closed!

**Comment by dylanexpensify** [comment]
@0xmiroslav are you paid in ND? Or upwork still?

**Comment by dylanexpensify** [comment]
got it, moving this to weekly!

**Comment by dylanexpensify** [comment]
still waiting

**Comment by dylanexpensify** [comment]
Yes! TY!

**Comment by dylanexpensify** [comment]
@0xmiroslav do we just need a new upwork job for Volodymyr to apply to?

**Comment by dylanexpensify** [comment]
@0xmiroslav mind having them apply [here](https://www.upwork.com/jobs/~01b5740ea62c4061b5)? 🙇‍♂️

**Comment by dylanexpensify** [comment]
bump on this @0xmiroslav ^ 🙇‍♂️

**Comment by dylanexpensify** [comment]
all done!
