### ISSUE TITLE
[Hold for #12775] Edited message reappears when userB edit the message in offline mode and userA deletes it in the room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to userA's account
2. Navigate to the "New room" section
3. Enter a room name and select userA's workspace
4. Set the visibility to "Public"
5. Click on "Create room"
6. Go to the room details
7. Share code > copy URL to clipboard
8. Open another browser and log in to userB's account
9. Join the room by pasting the room URL
10. Send a message in the room from userB
11. Go offline in the "Preferences" settings
12. Click on the "Edit comment" message
13. Edit the message and click on "Save"
14. Return to userA's account
15. Delete the message sent by userB
16. Switch back to userB's account and go back online
## Expected Result: 
The edited message should not reappear if userA deletes the message in the room and userB edits it in offline mode
## Actual Result: 
The edited message reappears even if userA deletes the message in the room and userB edits it in offline mode

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/70b8d0ac-7198-4155-8df6-5ed72dfb72db

https://github.com/Expensify/App/assets/43996225/fc1f9774-4ca3-49d3-b36a-f93417ddf462

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688419782537229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I think this issue is super similar to https://github.com/Expensify/App/issues/17654, close enough that I am tempted to call it a dup and I think it might be fixed by https://github.com/Expensify/App/issues/12775

Putting this issue on hold for https://github.com/Expensify/App/issues/12775

**Comment by sonialiap** [comment]
Still on hold

**Comment by sonialiap** [comment]
On hold

**Comment by sonialiap** [comment]
On hold

**Comment by sonialiap** [comment]
Still on hold

**Comment by sonialiap** [comment]
Still on hold

**Comment by sonialiap** [comment]
still on hold

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/12775

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/12775

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/12775

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/12775 and there's a mention of getting to it before the end of the year 😂 😭

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/12775
