### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] The emoji picker does not close when UserA deletes the message that UserB is in the process of editing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA’s account
2. Go to the “New room” section
3. Enter room name and select userA workspace
4. Select visibility to “Public”
5. Click on “Create room”
6. Go to the room details
7. Share code > Copy URL to clipboard 
8. Open other browser and login with userB’s account
9. Join the room by pasting room URL 
10. Send a message in room from userB
11. Click on “Edit comment” message after sent
12. Open emoji picker
13. Switch back to UserA's account and delete the message sent by UserB
## Expected Result: 
The emoji picker should close when UserA deletes the message that UserB is editing
## Actual Result:
 The emoji picker does not close when UserA deletes the message that UserB is in the process of editing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8d604fdb-84c2-463b-a7c8-71f48ff57510

https://github.com/Expensify/App/assets/43996225/c38e326b-7fbc-4125-8dfa-e12b3253b5a8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688418131979529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160c5dd36cad866e5</li>
        <li>Upwork Job ID: 1678374584595656704</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by anmurali** [comment]
I am not sure how user A can delete user B's message in a room. I don't see that option at all.
<img width="985" alt="image" src="https://github.com/Expensify/App/assets/14225673/d8703127-dd24-4ebf-93bd-73d605f3eed3">

**Comment by anmurali** [comment]
Ah gotcha!

**Comment by marcaaron** [comment]
I am curious why we are not already passing the `reportAction` to that method. 

Can we also update this method so that it does not have so many default variables?

https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/actions/EmojiPickerAction.js#L15-L15

Seems like the `reportAction` should be _**required**_.

**Comment by marcaaron** [comment]
Not overdue.

**Comment by anmurali** [comment]
- [ ] Reporting bonus @ayazhussain79 $250 - Offer [here](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/26133952)
- [X] Contributor @hoangzinh $1,000 (Paid)
- [ ] Contributor + @allroundexperts $1,000 (eligible for new dot payment)

**Comment by ayazhussain79** [comment]
@anmurali offer accepted, Thank you

**Comment by JmillsExpensify** [comment]
Reviewed the details for @allroundexperts. Approved for payment in NewDot based on the BZ summary above.

**Comment by marcaaron** [comment]
Anything left to do for this one?

**Comment by marcaaron** [comment]
Thanks !

**Comment by ayazhussain79** [comment]
@anmurali Could you please end the contract of this bug job on upwork

**Comment by ayazhussain79** [comment]
@anmurali Kindly close the job on Upwork, it's still in progress
