### ISSUE TITLE
Generic 'No results found' message is shown if one searches for one's own email or display name.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB and click chat
2. Search for your primary or secondary email logins
## Expected Result: 
There should be an error like 'you cannot start a chat with yourself ' instead of 'no results found '
## Actual Result: 
Header message simply says no results found

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6cbe7953-e0ca-4ab7-9569-df4b053ea242

https://github.com/Expensify/App/assets/43996225/b6187115-a27d-4d7a-a77f-92d10de5b59e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688412693131939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There should be a specific message like "You cannot start a chat with yourself` message instead of `No results found` when searching for one's own default and secondary ids.
### What is the root cause of that problem?
This is because the below line shows headerMessage as No results found
https://github.com/Expensify/App/blob/79922cc3d8533864eee55c441dc4632fed1a220a/src/pages/NewChatPage.js#L198C1-L198C58
### What changes do you think we should make in order to solve the problem?
We change the headerMessage to this
```
headerMessage={OptionsListUtils.isSearchStringMatch(searchTerm, '', new Set(_.keys(props.loginList))) ? props.translate("common.noChatWithOneself") : headerMessage}
```
and subscribe to loginList in the NewChat Page,
This will give all logins in loginList to check in the above OptionsListUtils function.
This same change can be applied at other places where we want to show a custom message like this
### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment]
asked about expected behaviour here: https://expensify.slack.com/archives/C01SKUP7QR0/p1688586528073259

**Comment by NicMendonca** [comment]
Discussed in thread ^^ since we're working on the ability to chat with yourself, we don't need to do anything with the current behaviour right now
