### ISSUE TITLE
Tooltip position is inverted in LHN for large emails on pin, unpin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22222]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open report of user with very large email and no display name eg: [thisistestresulttryingtosearchanyrandomemail020120231922@gmail.com](mailto:thisistestresulttryingtosearchanyrandomemail020120231922@gmail.com)
3. If pinned then unpin the user
4. Type anything to enable pencil icon in LHN (Ensure that user has around 4th or 5th position or below in LHN), observe that tooltip is displayed on top on hover
5. Right click on chat and pin the user (Ensure that user has around 4th or 5th position or below in LHN), observe the tooltip again, it should be still on top
6. Scroll to bottom in LHN and scroll back up to report
7. Hover on user again in LHN to observe the tooltip position has now inverted to bottom
## Expected Result: 
App should display tooltip on top in LHN if there is enough space
## Actual Result: 
App inverts the tooltip for very large email (it displays on top in start) if we type anything, pin the user, scroll down and scroll back to user and hover again on user in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** needs reproduction ( I see the tooltip at the top always)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/03d28eed-ae0e-4563-99a0-fb8e9edb7259

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688379316553329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
low priority, bumping to weekly and removing bug label

**Comment by mallenexpensify** [comment]
Not an immediate priority

**Comment by mallenexpensify** [comment]
Don't have time to address now but making a weekly so I can _do something_ soon.

**Comment by mallenexpensify** [comment]
Competing priorities and low value issue.

**Comment by mallenexpensify** [comment]
Maybe/hopefully soon?

**Comment by mallenexpensify** [comment]
Closing this, it's a minor tweak/update and we're focusing more on bugs affecting real users, which i don't think this is one. Comment if you disagree.
