### ISSUE TITLE
"Hmm... its not here" page is displayed when splitting a bill or requesting money from an account not interacted before

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account A and click on FAB > split bill > enter an amount
2. Paste contact email which you have not interacted before and select it > click next
3. Click on the account under "Who was there?"
## Expected Result: 
Profile detail should show up
## Actual Result: 
Hmmm its not here page shows up

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aaacf39d-95ef-4e8b-acc3-2404fd96df11

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688409086474479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/43996225/0b5ce4ae-07f6-412e-a9d8-7357dfd603ec

**Comment by muttmuure** [comment]
This is probably expected as part of the changes to how we decided to handle messages when you don't have a chat history, shared domain or workspace with another user.
