### ISSUE TITLE
[$1000]  Workspace - Workspace chat receives nothing and invitation is not received after changing username

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21895
## Action Performed:
Precondition: Create new accounts for both scenarios.

Scenario 1:
1. Go to staging.new.expensify.com
2. As User A, go to Settings > Workspace > Members > Invite > Enter User B's address > Select User B > Invite User B
3. As User B, send a message and request money in workspace with User A
4. As User A, check the workspace chat

Scenario 2:
1. Go to staging.new.expensify.com
2. Both User A and B change display name
3. As User A, go to Settings > Workspace > Members > Invite > Enter User B's address > Select User B > Invite User B
4. As User B, check the workspace chat

## Expected Result:
Scenario 1: There are two workspace chats - one with user B, one without user B. The workspace without user B should serve some purpose
Scenario 2: User B receives invitation and the invited workspace will show up in LHN

## Actual Result:
Scenario 1: The workspace without user B does not receive any message from user B and does not receive anything
Scenario 2: Workspace chat does not show up in User B's LHN

For Scenario 2, occasionally the workspace shows up on the member (User B) end but admin (User A) does not receive any chat from workspace with user B when user B has sent messages and IOU to admin (User A)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/18d29a90-d64d-4878-99d8-bf56b2859237

Uploading Bug6116215_Scenario_1 (1).mp4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa1c6aabf0bf2b9b</li>
        <li>Upwork Job ID: 1677418686788530176</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
we'll start reviewing proposals next week.

**Comment by mkarkachov** [comment]
I did not reproduce the issue. Works as expected on production and on staging

**Comment by maddylewis** [comment]
thank you @mkarkachov - based on that comment, im going to close this out for now - https://github.com/Expensify/App/issues/22234#issuecomment-1626123199
