### ISSUE TITLE
Web –Inconsistency among “Split Bill” and “Workspace > Members” user search feature and selected members.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign.
2. Go to "Split Bill."
3. Enter the amount.
4. Click "Next."
5. Now select all available users.
6. Enter an invalid name in the search field and observe that an error appears along with the selected users.
1. Open any Workspace.
2. Select "Manage Members."
3. Select "Invite."
4. Select "Invite New Members."
5. Now select all available users.
6. Enter an invalid name in the search field and notice that only an error appears.

## Expected Result:
 Either only "No results found" should appear or "No results found" along with the selected members to maintain consistency.

## Actual Result:
There is an inconsistency between the display of selected members of the Workspace and the Split Bill feature.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1ac8e5ee-cc65-4af4-9b96-821d0a96b733

https://github.com/Expensify/App/assets/93399543/e43ccfbc-64b4-4bb8-8bbc-2aa5c6422356

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688453837185409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This looks fixed already

**Comment by bfitzexpensify** [comment]
Yes, I can no longer reproduce

Workspace:

<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/38236554/fe571ab0-b29d-4cca-aee6-db88625606ec">

Split Bill:

<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/38236554/6c05f126-8f6e-4227-9797-fbf692103fb5">

@usmantariq96 can you still reproduce this?

**Comment by usmantariq96** [comment]
@bfitzexpensify yes now it is fixed.

**Comment by bfitzexpensify** [comment]
Cool, let's close this out then.
