### ISSUE TITLE
Web – Bank Account – User land on the last section of “Connect bank account” i.e. “Validate Bank Account” after sign-in.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22231]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" section in the web application.
2. Navigate to the "Workspaces" tab.
3. Select the "Bank Account" option.
4. Click on "Connect bank account".
5. Follow all the required steps until reaching the "Validate Bank Account" page.
6. Close the account page by clicking outside the page and sign out.
7. Sign in again and repeat steps 1 to 3.
8. Notice that instead of landing on the "Connect bank account" page, the user is directed to the "Validate Bank Account" page.
9. Click outside the page and repeat steps 1 to 3.
10. Now observe that the user correctly lands on the "Connect bank account" page.

## Expected Result:
After signing in, the user should land on the "Connect bank account" page.

## Actual Result:
 After signing in, instead of landing on the "Connect bank account" page, the user is redirected to the "Validate Bank Account" page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50d9d9e0-801e-4aa1-a08f-f21d76e87552

**Expensify/Expensify Issue URL:**
**Issue reported by:**   @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688462339971129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
I believe this is expected behavior, not a bug. We want users to land on the verification page if they still need to finish the bank account setup in the previous session.
