### ISSUE TITLE
Contact methods - Unable to delete added Contact method. Sign "Bloked" is displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login with expense account
2. Tap on Settings > Profile > Contact methods
3. Enter a email with uppercase and lowercase letters but with a correct format (e.g [TeSt@Gmail.com](mailto:TeSt@Gmail.com))
4. Click on the button "Add"
5. Click on the contact method and delete it

## Expected Result:
Verify you're able to delete contact methods that have not yet been verified

## Actual Result:
Unable to delete added Contact method. Sign "Bloked" is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8f133517-9155-42b9-8d7a-37954cab3f6a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cubuspl42** [comment]
Could not reproduce

**Comment by kevinksullivan** [comment]
Can't reproduce either
