### ISSUE TITLE
[$1000] Web - Detail error info is not being shown the first time user inputs an existing email as a secondary contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Copy and email of an account that already has an expensify account
2. Open a new account and click on settings > Profile > Contact method
3. Click on New contact method > Paste the copied email and click Add
4. Notice the error and click on the secondary contact just added and observe the error message
5. Go back and click on add new contact method again
6. Paste the email copied earlier
7. Click on Add
8. Observe the error message

## Expected Result:
 The error message that showed up on Step 8 should be shown on step 3 as well just like it does on step 8 on the current "new contact method" page without going back to "contact methods" page.

## Actual Result:
Generic error message is being shown on step 3 and user is able to click save and go back to the previous page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5ccb35c9-694b-4b12-bd64-ff7fa089d438

https://github.com/Expensify/App/assets/93399543/4794cbb5-653e-404b-9c7f-aeca3130350d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688450172455119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5aa4f7792efefc5</li>
        <li>Upwork Job ID: 1676701622377996288</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
pending review on the proposal above!

**Comment by adelekennedy** [comment]
@parasharrajat what do you think on the proposal above?
