### ISSUE TITLE
[$1000] [HOLD FOR PAYMENT 13-07-23] Web - Repeated copy of contact method URL adds characters in URL triggering its not here page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open contact method
5. Open non default contact method and copy the URL
6. paste URL in any report and send
7. Click on URL and observe that it opens correct contact method page, again copy the URL and send in report
8. Click on URL sent in step 7 to observe that now it provides 'Hmm its not here' page

## Expected Result:
App should not add content to URL while visiting to avoid 'Hmm its not here' page error on recopy and revisit

## Actual Result:
App adds new content in URL of contact method whenever we visit it again by deep link triggering 'Hmm its not here' on 2nd URL copy and visit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5d597128-30ac-439f-a230-93914dc1c35a

https://github.com/Expensify/App/assets/93399543/113ca0ad-611a-4b3e-a88c-7de0ce586ef0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688490569899239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae16ee8b22ed14a7</li>
        <li>Upwork Job ID: 1680122209842212864</li>
        <li>Last Price Increase: 2023-07-15</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Already fixed [here](https://github.com/Expensify/App/pull/22323)

**Comment by situchan** [comment]
@Julesssss can you please assign me to the issue? As I was the author of PR

**Comment by Julesssss** [comment]
Ah wait. I don't think that's right. @dhanashree-sawant raised the bug first and because the issue was a dupe it's not valid for payment for both issues. 

BUT, we can use this issue for payment. As it was the original. 

- Reporter bonus: @dhanashree-sawant
- 1000$ bounty: @situchan

**Comment by situchan** [comment]
Right, I am not eligible for reporting bonus but may be 50% speed bonus.

**Comment by situchan** [comment]
Also I think @thesahindia should be compensated here for C+ review.

**Comment by NicMendonca** [comment]
Sorry! I don't know why this didn't pop to a daily.

**Comment by NicMendonca** [comment]
Can everyone please apply to the job? https://www.upwork.com/jobs/~01ae16ee8b22ed14a7

**Comment by NicMendonca** [comment]
@situchan @dhanashree-sawant - can you please accept the offer so we can issue payment?

**Comment by NicMendonca** [comment]
@thesahindia says he's got this on his to-do! closing!

**Comment by JmillsExpensify** [comment]
@NicMendonca Do you mind adding a payment summary on this issue so that I can pay @thesahindia?

**Comment by NicMendonca** [comment]
- reporter: @dhanashree-sawant - $250
- Contributor: @situchan  - $1,000
- C+: @thesahindia - $1,000

cc @JmillsExpensify ^^

**Comment by situchan** [comment]
$1500 should be correct amount. PR was merged within a day

**Comment by NicMendonca** [comment]
Sorry, you're right! This was quite a long time ago I forgot!

![image](https://github.com/Expensify/App/assets/24947345/2e0a6313-1c39-42d2-a09c-dd5ea7c6df1c)

**Comment by NicMendonca** [comment]
> reporter: @dhanashree-sawant - $250
> Contributor: @situchan - $1,500
> C+: @thesahindia - $1,500

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @thesahindia based on BZ summary.
