### ISSUE TITLE
BUG: Rooms should not show split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Create a workspace
3. Create a room
4. Click on plus option

## Expected Result:
 Split bill option should not appear

## Actual Result:
The split bill option appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Outdated
https://github.com/Expensify/App/assets/93399543/882654a9-110f-4671-becc-fb3adc6de798

[Screencast from 04-07-2023 19_08_57.webm](https://github.com/Expensify/App/assets/93399543/a150721a-3b61-4467-ab90-c111e9828042)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688472505039959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102e4e3f83c0c685e</li>
        <li>Upwork Job ID: 1678602294688821248</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1688579070022409?thread_ts=1688472505.039959&cid=C049HHMV9SM

This may need to be internal

**Comment by mallenexpensify** [comment]
Was able to reproduce, added the Internal label, per Jack's rec

**Comment by mallenexpensify** [comment]
Adding `Engineering` otherwise I don't think an engineer would see it.

**Comment by mallenexpensify** [comment]
@Santhosh-Sellavel can you confirm you're able to reproduce? If so, what are you thoughts on next steps @neil-marcellini ?

**Comment by Santhosh-Sellavel** [comment]
@mallenexpensify You confirmed [here](https://github.com/Expensify/App/issues/22283#issuecomment-1630036883) already

**Comment by mallenexpensify** [comment]
Yeah, I was able to reproduce @Santhosh-Sellavel , for some reason I wanted bonus 👀 , can't remember exactly why.

**Comment by Santhosh-Sellavel** [comment]
@mallenexpensify Yeah I can confirm able to reproduce when login via phone number

<img width="429" alt="Screenshot 2023-07-19 at 7 10 27 AM" src="https://github.com/Expensify/App/assets/85645967/2e890b47-5a19-4678-9aa8-e65754b0c521">

**Comment by neil-marcellini** [comment]
I'm working on a few other internal issues right now, so I'll have to get to this later.

**Comment by neil-marcellini** [comment]
There are still other higher priority issues that I'm working on instead of this.

**Comment by neil-marcellini** [comment]
I took a bit of a look today. Yep @dukenv0307 is right that the back end is returning report.participants as an empty array when you're logged in with a phone number. If you're logged in with an email then it returns a list of participant logins.

Next time I'll look into OpenReport and see what's going on. I think we should probably be using `participantAccountIDs` instead due to the refactor to hide login info. cc @Beamanator @puneetlath do we have any other plans to fix this elsewhere / do you guys have any advice. I want to make sure I'm not working on a duplicate issue.

**Comment by Santhosh-Sellavel** [comment]
@neil-marcellini Check [here](https://github.com/Expensify/App/issues/22283#issuecomment-1641258318) I have logged in with email also facing same issue

**Comment by neil-marcellini** [comment]
Oh interesting. I don't have that problem but maybe because I'm logging in with an email using the account that created the room. The bug has nothing to do with a mobile number then. Please investigate further if you can and nail down the root of the problem.

**Comment by Santhosh-Sellavel** [comment]
I've logged in with a new account that has nothing to do with the room!

**Comment by neil-marcellini** [comment]
Heads up, I'm going to be OOO Monday and Tuesday next week. I'll ask in Slack if anyone can take over these issues while I'm out.

**Comment by mallenexpensify** [comment]
@neil-marcellini is out today/tomorrow, he'll look into once back

**Comment by puneetlath** [comment]
>cc @Beamanator @puneetlath do we have any other plans to fix this elsewhere / do you guys have any advice. I want to make sure I'm not working on a duplicate issue.

Not that I'm aware of. We are working on removing report.participants so that only report.participantAccountIDs remains. And I believe that for public rooms, the participantAccountIDs array will always be empty for non-admins (just as an FYI).

**Comment by puneetlath** [comment]
>Oh interesting. Why? 

Because people in public rooms aren't supposed to know who else is in the room for privacy reasons. I believe only admins of the workspace (or maybe all workspace members) are allowed to know that. So for anyone else, the participantAccountIDs array will be empty. 

Out of curiosity, what purpose does the split bill option serve in rooms? Perhaps an alternate approach would be to have it be there in DMs/Group-DMs and just leave that out of rooms altogether?

**Comment by neil-marcellini** [comment]
> Out of curiosity, what purpose does the split bill option serve in rooms? Perhaps an alternate approach would be to have it be there in DMs/Group-DMs and just leave that out of rooms altogether?

Yes great point, it doesn't really make sense for rooms. When you split a bill with a group it automatically splits it among all members. I don't think that's really the desired behavior for rooms, so I agree let's only add the split bill menu item for groups. I don't think it makes sense for DMs because there's no one to split with.

**Comment by puneetlath** [comment]
I think DMs still make sense. You and I could still split a bill (e.g. I pay for lunch, scan the receipt, and you owe me for half). 

I agree on rooms though. Maybe we should validate in #product just to be sure?

**Comment by neil-marcellini** [comment]
haven't had time

**Comment by neil-marcellini** [comment]
I haven't had time. I'm prioritizing distance requests above this.

**Comment by mallenexpensify** [comment]
@neil-marcellini will be looking at soon

**Comment by neil-marcellini** [comment]
I might have time for this today.

**Comment by neil-marcellini** [comment]
I've been focused on distance requests trying to get it done before the deadline.

**Comment by mallenexpensify** [comment]
@neil-marcellini will address once distance requests is wrapped

**Comment by neil-marcellini** [comment]
I updated the issue title and description based on the direction we're going for.

**Comment by neil-marcellini** [comment]
I put up a draft PR. A few more tweaks and it will be ready.

**Comment by neil-marcellini** [comment]
The PR is up for review, but we're still debating whether it's the right approach [in Slack](https://expensify.slack.com/archives/C03U7DCU4/p1694027982016709).

**Comment by neil-marcellini** [comment]
We're going to merge the split bill option into request money eventually, with teachers unite I think, and once that happens split bill won't show for public rooms and this will be solved. Also this is super edge case and we don't need to worry about it for now.
