### ISSUE TITLE
[HOLD for payment 2023-07-17] [HOLD for payment 2023-07-14] [HOLD FOR PAYMENT - 13th July] User is taken to the first step after changing currency when splitting a bill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Split bill > Enter an amount > Click next > Select users > Click next
2. While on "Cash" page click on Amount
3. Click on currency
4. Select another currency
5. Click next
## Expected Result: 
App should take user back to cash page
## Actual Result: 
App takes user back to the first page

**Second example**
- FAB icon > Split Bill > Enter amount > Click Next >Select any user > Click Next to open up the split bill page ( Do NOT click split button)
- Now click on the user > Click back and see that the split money page is gone
- We shouldn't be persisting the 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6aa05c3e-e6ce-407c-8c20-243aa9b76ae8

https://github.com/Expensify/App/assets/43996225/be5b86d7-addd-4ca2-90c3-2c690e3ee041

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688581054112519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment]
- Regression from https://github.com/Expensify/App/pull/21067
- The `minimalAction` does not contain `path` which is what the `MoneyRequestAmountPage` relies on to detect if we are viewing the amount page as initial view or as edit view.
- Fix: Add `path` to `minimalAction` here https://github.com/Expensify/App/blob/d2de7795edba44a3803f9c10db06ba515a896e69/src/libs/Navigation/linkTo.js#L35-L38

**Comment by bondydaa** [comment]
tagging all the users who are on https://github.com/Expensify/App/pull/21067 @adamgrzybowski @abdulrahuman5196 @mountiny @venture1981 @WoLewicki

can you please let us know what you think? Does the proposal above look good and we can have @s77rt spin something up or do you want to take care of this yourselves?

**Comment by mountiny** [comment]
Solution looks good to me

**Comment by abdulrahuman5196** [comment]
Sorry, I logged in now only.

@bondydaa It seems there was already a PR and got C+ approved to fix the path not present issue here - https://github.com/Expensify/App/pull/22323

**Comment by Julesssss** [comment]
Fixed by [this PR](https://github.com/Expensify/App/pull/22323) ❤️

**Comment by Julesssss** [comment]
Thanks, I just updated the reporter field. My bad, I'm in quite a rush today

**Comment by Julesssss** [comment]
Hi @Nathan-Mulugeta. Sorry, I see now you are correct. The issues are very similar, but they are in fact distinct 😖 

I updated the description and will re-open @Santhosh-Sellavel's issue

**Comment by bondydaa** [comment]
i'm honestly very confused and probably not the best person to fill out the checklist. if someone else more familiar with what went on here can that'd be great.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/21067
- The offending PR has been commented on: https://github.com/Expensify/App/pull/21067#discussion_r1253709178
- A discussion in #expensify-bugs has been started: Not needed. This is a specific bug that could only be caught in tests
- Determine if we should create a regression test for this bug: No

**Comment by Nathan-Mulugeta** [comment]
Hey guys when is this report's Payment going to be processed? I am seeing duplicate hold for payment on the title?  🤔 @juke @stephanieelliott

**Comment by bondydaa** [comment]
yeah sorry not sure what's going on there but we're past all of those dates so @stephanieelliott can we get payment going?

**Comment by stephanieelliott** [comment]
Extended the offer to you in Upwork @Nathan-Mulugeta, once you accept we will pay out ASAP https://www.upwork.com/jobs/~01ad253d7b84b4117d

**Comment by Nathan-Mulugeta** [comment]
Just accepted offer @stephanieelliott

**Comment by stephanieelliott** [comment]
All paid!
