### ISSUE TITLE
Web - When you want to edit the title of the task, the title of the previous task appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click in plus sign
2. Open Assign task
3. Write an title and click button Next
4. Select an email or number phone to Share somewhere
5. Click button Confirm task
6. In the same chat, re-assign a task
7. Click in plus sign and open Assign task
8. Redo step 3 and click in button Confirm task
9. Click on the title of the task to be able to edit it

## Expected Result:
Show the title of the current task to be able to edit it

## Actual Result:
The title of the previous task assigned to the same email or phone number is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/97977a9e-3c98-49ae-b8ad-69276569e2bf

https://github.com/Expensify/App/assets/93399543/c9a66d5b-203c-4bb9-9c83-abd41b5fe728

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688445422449799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
Looks like this should be resolved by https://github.com/Expensify/App/issues/19330
