### ISSUE TITLE
Selecting user doesn't clear input text from search field on Split Bill page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22298]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' icon
2. Click on 'Split bill' link
3. Enter amount & click on 'Next' button
4. Search a user in the input field
5. Select the user
## Expected Result: 
Text from the input field should be cleared
## Actual Result: 
Text from the input field is not cleared

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b60b172b-32b4-4a64-96a6-456c89e94575

https://github.com/Expensify/App/assets/43996225/71f707a8-91e0-4a92-90eb-7d21bd20fb01

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688584083890729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I think this is possibly related to: https://github.com/Expensify/App/pull/20271

cc @multijump @Julesssss @allroundexperts

**Comment by marcaaron** [comment]
@dukenv0307 Are you able to fix this quickly?

@Julesssss I'm not sure, but maybe you will want to just revert that PR to get the deploy unblocked.

**Comment by greg-schroeder** [comment]
Okay so it can't be expected behavior and also a deploy blocker. The thread linked above indicates this is actually expected

**Comment by greg-schroeder** [comment]
I pinged in the thread to get some additional 👀

**Comment by Julesssss** [comment]
Excellent, thanks all.
