### ISSUE TITLE
Implement Top Sticky Headers for our Inverted Flatlist

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#22317]
We want to be able to have things like Tasks scroll with report actions, but then stick to the top of the FlatList once they reach the top. 

React Native's FlatList has a prop called [`stickyHeaderIndices`](https://reactnative.dev/docs/scrollview#stickyheaderindices) which allows you to specify the indices of the children of the Flatlist that should be sticky.

The only problem with this is that our FlatList currently takes the prop `inverted={true}`, which means that `stickyHeaderIndices` will make stuff stick to the bottom of the view, and not the top. That isn't what we want.

We need to implement a custom [`StickyHeaderComponent`](https://reactnative.dev/docs/scrollview#stickyheadercomponent) that allows us to stick stuff to the top of the View for our Inverted FlatList.

NOTE: [`invertStickyHeaders`](https://reactnative.dev/docs/scrollview#invertstickyheaders) doesn't seem to work when the FlatList is already inverted

**Comment by jasperhuangg** [comment]
Hey @shawnborton! This stemmed from [this PR](https://github.com/Expensify/App/pull/20841). Was having the Task stick to the top of the view something you wanted?

**Comment by shawnborton** [comment]
This doesn't sound like something we ever designed or wanted. Basically the task info just scrolls with the content and keeps scrolling as the comments might grow below it, nothing is fixed anymore except for the very top header. 

Just curious where you got the idea from that we wanted it fixed? Perhaps something was lost in translation.

**Comment by jasperhuangg** [comment]
The reviewer thought that was what the design was, and I told him I'd create a follow up and ask you for clarification. Thanks for confirming, we're good to just close it out then.

FWIW I didn't think this was implied by any of your designs.
