### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Remove usage of getReportIDFromRoute

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#22326]
Coming from [this comment](https://github.com/Expensify/App/pull/16581#discussion_r1242912615).

**Problem**
We missed some instances of _ reportIDFromRoute_ during the navigation refactor, which caused a regression.

**Solution**
Remove them
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014254ae0a9d055feb</li>
        <li>Upwork Job ID: 1676859624120598528</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Just a quick issue to keep track of [this PR](https://github.com/Expensify/App/pull/21702) by SWM, so we don't really need to upwork job. Can you close it, @flaviadefaria?

**Comment by abdulrahuman5196** [comment]
Does this require C+? I was assigned and unassigned twice, let me know if something is required from my end.

**Comment by flaviadefaria** [comment]
@Gonals what is required from me here? Does anyone need to be paid or can I unassign myself. Sorry, but I'm a bit confused!

**Comment by Gonals** [comment]
I think you are all good!

**Comment by Gonals** [comment]
I think we can close this
