### ISSUE TITLE
mWeb -  Active mark as unread button does not do anything to concierges "This is you first time chatting..." Message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in to Staging New Dot
2. Click on + icon
3. Click on new chat and search for an account you had not interacted before and click on it
3. Wait for the "This is you first time chatting..." Message from concierge
4. Long press it and click on mark as unread
5. Notice that it doesn't do anything

## Expected Result:
Either the mark as unread button should be removed or the message should be marked as new message

## Actual Result:
Nothing happens when clicking mark as unread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/156c0c0a-23a6-4ddb-9c49-9846f3f44c09

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688528706504299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Lots of high priorities. Getting to this tomorrow

**Comment by muttmuure** [comment]
Still not had time
