### ISSUE TITLE
[HOLD for payment 2023-07-28] Update Expense Request View

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22333]
Part 2 of https://github.com/Expensify/App/issues/20486#issuecomment-1622110749
Related to https://github.com/Expensify/App/issues/20486

![image](https://github.com/Expensify/App/assets/38015950/ba2c7ff7-7df6-430d-b2ef-57273cae3a9d)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b93f70cc206833c</li>
        <li>Upwork Job ID: 1676899872247611392</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by grgia** [comment]
PR Created

**Comment by Santhosh-Sellavel** [comment]
Not overdue PR is merged!

**Comment by Santhosh-Sellavel** [comment]
@grgia Can you or ask a BZ to leave a comment mentioning the amount to be paid for review? So I can request on ND, thanks!

**Comment by Santhosh-Sellavel** [comment]
@grgia bump!

**Comment by Santhosh-Sellavel** [comment]
@Expensify/bug-zero Anyone can up the payment for internal PR review. So I can proceed with the payment request on ND. thanks!

**Comment by Christinadobrzyn** [comment]
I can help with this! 

I don't see that a speed bonus applies to this PR, @Santhosh-Sellavel can you confirm if you qualify for a speed bonus?

**Comment by Santhosh-Sellavel** [comment]
Yes, no speed bonus here @Christinadobrzyn, just the review fee!

**Comment by Christinadobrzyn** [comment]
Thanks @Santhosh-Sellavel So payment would be: 

Payouts due:

Contributor+: $1000 @Santhosh-Sellavel 
Eligible for 50% #urgency bonus? NA - internal

**Comment by JmillsExpensify** [comment]
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
