### ISSUE TITLE
Chat - Several images at once are skipped when switching attachments with arrows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com with Safari
2. Login in any account
3. Go to any chat with multiple attachments
4. Select any attachment
5. Switch attachments with on-screen arrows

## Expected Result:
Only the next attachment is loaded by clicking on the on-screen arrow

## Actual Result:
Several images at once are skipped when switching attachments with on-screen arrows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3eefd96b-c806-4f8a-af08-950587ea89fd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
This issue is already created - https://github.com/Expensify/App/issues/22318

**Comment by bfitzexpensify** [comment]
Yep closing in favour of https://github.com/Expensify/App/issues/22318
