### ISSUE TITLE
[HOLD for payment 2023-07-26] Update Expense Report View 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22332]
Part 1 of https://github.com/Expensify/App/issues/20486#issuecomment-1622110749
Related to https://github.com/Expensify/App/issues/20486

![image](https://github.com/Expensify/App/assets/38015950/e1b13a14-880d-45ec-94d4-1bc6914ae014)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01809b70d955011b47</li>
        <li>Upwork Job ID: 1676899649993342976</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by grgia** [comment]
@trjExpensify @shawnborton right now we don't show the three dots on the report view and only show it on the single transaction view. Is the new design with the three dots correct? What shows when you click them?

**Comment by shawnborton** [comment]
Yeah, I left a similar comment over in the other issue but I think we should stay consistent with the overflow menu on all of the various report type views (chat, thread, task, report, expense, etc). And then in the very least, it always has a pin option but it also might have:
- call
- delete
- etc

**Comment by grgia** [comment]
@conorpendergrast could you help to handle the $1000 C+ payment to @fedirjh for https://github.com/Expensify/App/pull/22484

**Comment by conorpendergrast** [comment]
I would happily to do

**Comment by conorpendergrast** [comment]
Contract sent via Upwork, and I'll be able to see that [here](https://www.upwork.com/ab/applicants/1676899649993342976/offers)

**Comment by conorpendergrast** [comment]
-  External issue reporter: N/A - no one
-  Contributor that fixed the issue: N/A - no one
-  Contributor+ that helped on the issue and/or PR: @fedirjh for $1000. [Offer link](https://www.upwork.com/nx/wm/offer/25859532). Contract link TBC
- Urgency bonus: No

**Comment by conorpendergrast** [comment]
Paid! @grgia Is that everything? If so, close it out
