### ISSUE TITLE
[$1000] Web - Attachment upload is not working when using file with special characters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Choose add attachment from plus button
3. Choose file with contain spaces or special characters 

## Expected Result:
The upload should work correctly

## Actual Result:
Attachment upload is not working when using file with special characters

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6cd1c05d-20bc-4a72-9352-045a43181b7a

https://github.com/Expensify/App/assets/93399543/a768ec30-b8aa-46f2-9e50-6fdc31d0ca1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688624405764869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016db84bcc46127fd6</li>
        <li>Upwork Job ID: 1677359990020440064</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Attachment upload is not working
### What is the root cause of that problem?
Cleaning up file name is not handled correctly, for example here, when creating a new instance of `File` we are not supplying options(third) argument here, which contains `type` and `lastModified` [fields](https://developer.mozilla.org/en-US/docs/Web/API/File/File)
https://github.com/Expensify/App/blob/6c30d95a267aa4eeb5fe3af16090acbcd2f9d1fc/src/components/AttachmentPicker/index.js#L40-L47
The resulting instance does not have type, thus backend is resulting in error. Below you can see before and after state of file, when mentioned action is applied.
<img width=“609” alt=“Screenshot 2023-07-06 at 2 31 09 PM” src=“https://github.com/Expensify/App/assets/59907218/87e1adb1-0e1f-45eb-93d3-5f27d510d439”>
This is issue is not present when dragging file because we are not performing this action there
### What changes do you think we should make in order to solve the problem?
We should provide file `type` and `lastModified`(optional) in the options field, [here](https://github.com/Expensify/App/blob/6c30d95a267aa4eeb5fe3af16090acbcd2f9d1fc/src/components/AttachmentPicker/index.js#L43):
```javascript
file = new File([file], cleanName, {type: file.type, lastModified: file.lastModified});
```
Also we should perform the same when attachment is dragged in, I think here:
https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/pages/home/report/ReportActionCompose.js#L1092-L1094
Also we can do this action right before sending attachment to [backend](https://github.com/Expensify/App/blob/a88967f1a432dc347e0df408faf4ce407e84d2ff/src/libs/actions/Report.js#L336-L338). I think this would be the best approach here
### What alternative solutions did you explore? (Optional)

**Comment by kashn11** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Attachment upload is not working when using file with special characters
### What is the root cause of that problem?
The issue stems from `AttachmentPicker` function that get the file and clean it's name while it clean name and add create new file with new clean name the type of file isn't automatically inferred, which is why we're seeing that the file's type is being lost.
### What changes do you think we should make in order to solve the problem?
To fix this issue we need to manually specify type of file in the third agrugment of File function
 `if (file.name !== cleanName) {
                            file = new File([file], cleanName,{type:file.type});
                        }`

### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment]
Issue looks good 👍
