### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - Clear error message is not shown in close account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > close account
2. Put your default contact method inside the second input field but add a dot "." at the end of the email
3. Click Close account

## Expected Result:
A clear error message should be shown that would help the user correct any mistakes put inside the input box

## Actual Result:
A generic error message is shown and user might not be able to clearly understand what is going wrong

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (15)](https://github.com/Expensify/App/assets/93399543/ca8c7216-d1dd-429d-96b9-3b6e12679aef)

https://github.com/Expensify/App/assets/93399543/63636bc6-4e40-48ad-8a49-5c9752c72f7e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688627237644589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147a52638811e5555</li>
        <li>Upwork Job ID: 1678509423767924736</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@maddylewis Can we fix the dot in the end of contact method as well? or I need a separate bug for it?

![Screenshot 2023-07-06 at 19 45 15](https://github.com/Expensify/App/assets/93399543/dc99e1f3-4942-4c4a-9e5f-1e78222de293)

Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1688647630285239

**Comment by sobitneupane** [comment]
@maddylewis I am not sure if it is even a bug. Here are two issues:
- **A generic error message is shown and user might not be able to clearly understand what is going wrong**
    -> Error message shown is "Please enter your default contact method to close your account." which is pretty clear. It suggests default contact method is expected and what user has typed in is not the default contact method.
- **The dot in the end of contact method as mentioned** [here](https://github.com/Expensify/App/issues/22343#issuecomment-1624298982) 
    -> The dot in the end of contact method is full-stop and it signifies the end of sentence. We can remove it if it is confusing for a user

**Comment by maddylewis** [comment]
interesting! agree with you that the default error message is clear. i say we do nothing there. 

but, sure, let's remove the `.` that shows at the end of an email address. i think that will make things look cleaner 👍

**Comment by sobitneupane** [comment]
Thanks @maddylewis.

[Proposal](https://github.com/Expensify/App/issues/22343#issuecomment-1623655929) from @c3024 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by flodnv** [comment]
I'm very skeptical and on the fence about this being a "bug", but I'll accept the proposal.

**Comment by maddylewis** [comment]
payment tomorrow

**Comment by maddylewis** [comment]
### Payments: 
- [ ] @Nathan-Mulugeta - reporting bonus ($250 paid via Upwork)
- [ ] @sobitneupane - C+ ($1000 paid via NewDot)
- [ ] @c3024 - Contributor ($1000 paid via Upwork)

**Comment by maddylewis** [comment]
@sobitneupane - will you review this checklist and let me know if anything is actionable there? thanks! https://github.com/Expensify/App/issues/22343#issuecomment-1642501883

**Comment by Nathan-Mulugeta** [comment]
Offer accepted @maddylewis , but not paid yet.

**Comment by flodnv** [comment]
None of the checklist applies.

Can we close this @maddylewis ?

**Comment by maddylewis** [comment]
everyone is paid now - closing!
<img width="610" alt="image" src="https://github.com/Expensify/App/assets/38016013/a09ca657-0360-4eda-8f38-5d9bb4b1496a">
<img width="632" alt="image" src="https://github.com/Expensify/App/assets/38016013/8687dcfc-2d0f-49a7-a9ab-a75954a6ce03">

**Comment by sobitneupane** [comment]
Requested payment on newdot.

https://github.com/Expensify/App/issues/22343#issuecomment-1653550260

**Comment by JmillsExpensify** [comment]
Reviewed the payment details for @sobitneupane. $1,500 is approved for payment via NewDot.
