### ISSUE TITLE
[HOLD for payment 2023-08-14] [HOLD for payment 2023-08-07] [$1000] Invite Member - No way to remove RBR from avatar after inviting an invalid number into a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace and go to invite members page
2. Paste an invalid number like "+916541237890" inside the search field and select it
3. Click next > invite
4. Go back to LHN and observe there is a RBR on it
5. Click on avatar > follow the RBR and click on workspace > members

## Expected Result:
There should be a way to remove the RBR from avatar and settings

## Actual Result:
 There is no way to remove RBR from settings after inviting an invalid member into a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6df7a971-b2ea-4bd6-89fe-2e2d8270bde2

https://github.com/Expensify/App/assets/93399543/0c39d983-3e6e-4949-b4c8-25729f2e9885

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688630661683609
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f84973149e5c0ce</li>
        <li>Upwork Job ID: 1678916595916169216</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
might be related to - https://github.com/Expensify/App/issues/20961#issuecomment-1624300468

**Comment by Nathan-Mulugeta** [comment]
Just as an info, this issue was introduced on this week's latest release, I think #20961 was reported 20 days ago. This issue was not there then.

**Comment by Christinadobrzyn** [comment]
Ah okay, thank you @Nathan-Mulugeta! It does sound like it might be separate then but I'll wait to confirm with @PauloGasparSv. Thanks!

**Comment by Christinadobrzyn** [comment]
watching for an update https://github.com/Expensify/App/issues/20961#issuecomment-1627793915

**Comment by Christinadobrzyn** [comment]
Not related to https://github.com/Expensify/App/issues/20961#issuecomment-1629927291 - moving forward with treating this separately! 

I can reproduce but I'm not sure how we want to remove the RBR - any suggestions @Nathan-Mulugeta

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

@JmillsExpensify At this time, we're receiving and reviewing proposals.

**Comment by eVoloshchak** [comment]
Reviewing proposals today

**Comment by eVoloshchak** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/22359#issuecomment-1631699801) looks good to me!

> We need to optimistically add the member details (with login) to personalDetails when we add a member to the workspace.
In successData, we'll clear the above member details since it has the dummy ID, and the back-end already returns correct accountID in personalDetails for that member.

🎀👀🎀 C+ reviewed!

**Comment by NikkiWines** [comment]
Sorry for the delay, agreed that @tienifr's proposal looks good 👍

**Comment by NikkiWines** [comment]
Yep 😅 I did

**Comment by JmillsExpensify** [comment]
@eVoloshchak Can you get us kicked off with the BZ checklist?

**Comment by Christinadobrzyn** [comment]
Back from ooo! Thanks for handling this @JmillsExpensify - I'm happy to take it off your plate!

**Comment by JmillsExpensify** [comment]
@eVoloshchak If you wouldn't mind kicking off the BZ checklist above in the next week, thank you!

**Comment by Christinadobrzyn** [comment]
Payouts due:

Issue Reporter: $250 @Nathan-Mulugeta 
Contributor: $1000 + $500 bonus (need confirmation this is true) @tienifr 
Contributor+: $1000 + $500 bonus (need confirmation this is true) @eVoloshchak 

Eligible for 50% #urgency bonus? Yes - @eVoloshchak @NikkiWines can you confirm? 

Upwork job is [here](https://www.upwork.com/jobs/~012f84973149e5c0ce).
Internal job posting - https://www.upwork.com/ab/applicants/1678916595916169216/job-details

**Comment by eVoloshchak** [comment]
@Christinadobrzyn, this has introduced a regression (https://github.com/Expensify/App/pull/23947), so no urgency bonus, and the bounty should be reduced 50%

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Create a workspace and go to invite members page
2. Paste an invalid number like "+916541237890" inside the search field and select it
3. Click next > invite
4. Verify that there's an error indicator (RBR) for the newly invited account
5. Verify that you can dismiss the error by pressing a `close` button


**Do we agree 👍 or 👎**

**Comment by Christinadobrzyn** [comment]
looks like the regression is resolved and the payment date for this should have been 8/16. I don't know why this didn't revert to a daily for payment but paying this now! 

Payouts due after regression based on https://github.com/Expensify/App/issues/22359#issuecomment-1677417081

Issue Reporter: $250 @Nathan-Mulugeta 
Contributor: $500 
Contributor+: $500

Eligible for 50% #urgency bonus? No - because of regression

Upwork job is [here](https://www.upwork.com/jobs/~012f84973149e5c0ce).
Internal job posting - https://www.upwork.com/ab/applicants/1678916595916169216/job-details

**Comment by Christinadobrzyn** [comment]
It looks like the penalty is based on this comment - https://github.com/Expensify/App/issues/22359#issuecomment-1677417081

We [announced](https://expensify.slack.com/archives/C02NK2DQWUX/p1690487246748689) the regression penalty on July 28th. The [regression](https://github.com/Expensify/App/pull/23947) related to this issue was found on July 31st so I believe the penalty would apply here as this regression was after the announcement.

**Comment by trjExpensify** [comment]
$500 approved for @eVoloshchak.
