### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Chat - Send button disappears when 'No internet connection' banner appears on top of browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any conversation
3. Upload a PDF but do not send it
4. Disconnect network.
5. Wait for about 10 secs until the banner 'No internet connection' appears on top of browser

## Expected Result:
'Send' button does not disappear

## Actual Result:
'Send' button flickers and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1d5e742d-8616-424e-b396-ae5007abac36

![Bug6118759_Screenshot_20230707_014051](https://github.com/Expensify/App/assets/78819774/9f57ed8f-0eb4-45d6-ba6b-fa49f3aecc4c)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017913f22666496afa</li>
        <li>Upwork Job ID: 1678511813762625536</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
I'm not able to reproduce but this is an annoying bug

**Comment by adelekennedy** [comment]
not overdue

**Comment by adelekennedy** [comment]
Not overdue - waiting for PR review!

**Comment by adelekennedy** [comment]
@allroundexperts the steps above make sense but to your point here:
>We already contain a checklist item that states to test both in offline and online mode. Was it something that was overlooked?

I think this _should_ have been tested already with our current steps, right?

**Comment by adelekennedy** [comment]
**Payment Summary:**

External issue reporter N/A
Contributor that fixed the issue - @dukenv0307  - $1000 + $500 3 day speed bonus paid in Upwork
Contributor+ that helped on the issue and/or PR - @allroundexperts  $1000 + $500 3day bonus to be paid in newdot

**Comment by JmillsExpensify** [comment]
Reviewed details for @allroundexperts. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
