### ISSUE TITLE
Web - Email Persistence Issues when Adding Commas after Email in Search Bars

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the plus sign > New chat > write an email from your contacts > add multiple commas.
2. Observe that the email remains persistent in the preview.
3. Write a new email that has never been used before and add multiple commas after it.
4. Observe that the email is not persistent in the preview; instead, it displays as an invalid email.

## Expected Result:
The preview should either display an invalid email for both new emails and contact emails or show both in the preview when multiple commas are added after the email in the search bar.

## Actual Result:
The app shows an invalid email when we search for a new email and add multiple dots after it, but the contact email remains persistent in the preview even after adding multiple commas after writing the email found in our contacts.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ce0d3a59-3a92-4499-938c-6f94e219a307

https://github.com/Expensify/App/assets/93399543/dc2ea65c-d47b-4f8f-afc7-590e46ee2db1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688639380099079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
This is done so that user can search for multiple users like `a@b.com, c@d.com`. So i don't think this is a bug.

**Comment by tewodrosGirmaA** [comment]
@jeet-dhandha if that answer it should work for both for new email and the email in contact. what are your thought on this?

**Comment by jeet-dhandha** [comment]
In new chat we don't have any feature where user can directly start a new chat with comma separated users, it might be more of a feature request.

**Comment by sonialiap** [comment]
will be OOO fri-mon and it's 10pm for me now, reassigning

**Comment by mallenexpensify** [comment]
I think this is working as expected because we want the known email to be persistent and for the unknown, since we don't know it, we don't want to assume it.
