### ISSUE TITLE
Dev  - App crashes when opening a deep link to welcome page - sign-in

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Enter email > click on 'Continue'
3. Copy deep link from the address bar
4. Open a new window where another account is signed in
5. Paste the link in a new tab
6. Press enter
## Expected Result: 
App should navigate to sign-in page
## Actual Result: 
App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev only
**Reproducible in production?:** dev only
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ab3327c0-3f65-4159-a2bf-030a45c58899

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688579460585089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Can't repro. Given that this is only happening in DEV and won't be experienced by an end user, gonna close this  for now
