### ISSUE TITLE
[$1000] Display name not shown for new user in mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging website on chrome (User 1)
2. Login with User 2 as a NEW user on another chrome and change display name
3. From user 1, click on FAB icon and click on new chat and input the User 2 email
4. From user 1, on chat composer, mention User 2 display name and notice that mentioning user 2 display name doesn't show the suggestion (only works if mentioned email)
## Expected Result: 
Mentioning display name of User 2 should show the mention suggestion
## Actual Result: 
Display name not shown for new user in mention

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/507e3db8-68bb-4ab5-9cb3-ee1126c75ec9

https://github.com/Expensify/App/assets/43996225/a1f41142-8de0-42db-b21d-24f1eb46bc6a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688571414432459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136ede1fc01c6d55b</li>
        <li>Upwork Job ID: 1677053774224551936</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Was able to recreate, so going to get eyes on this

**Comment by rain2o** [comment]
We might need to handle this on the backend. I see that when we search for the user, they are given a temporary ID in Onyx personalDetails. When we open the report we receive a number of Onyx actions, one of which includes a merge on personalDetails with the user's correct ID, but it only includes their avatar and display name, as shown in [ginsuma's comment](https://github.com/Expensify/App/issues/22374#issuecomment-1624330412).

We don't really have a way to connect the two on our side that I can see. Perhaps the merge sent in the response data should include the user's email as well, or a SET onyx action before the merge... something to give us a connection between that email and that ID.

**Comment by s77rt** [comment]
@ginsuma and @rain2o Thank you! So let me summarise this from my point of view based on what you said:
When we create a new chat we set an optimistic personalDetails object that contains `login` and that explains why we can mention using the email. Then later on we get another personalDetails object (with a different key since the accountID cannot be pre-determined) that contains the display name but not `login` and that explains why we can't mention using the display name.

So we have two personalDetail objects that are meant to refer to the same thing but they don't since the key is not the same?

**Comment by s77rt** [comment]
@ginsuma Yes and we already allow to be mentioned by the display name. In this case it's not working just because the data is split into two objects (optimistic object and the real server response object).

**Comment by CortneyOfstad** [comment]
Not overdue 👍

**Comment by s77rt** [comment]
Based on the Slack discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1688995928956959 we can close this. cc @CortneyOfstad

**Comment by CortneyOfstad** [comment]
Sounds good — thanks @s77rt!
