### ISSUE TITLE
[HOLD for payment 2023-09-07] Make animations within RHP consistent and reliable

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22372]
### Problem

Navigating between flows in RHP does not have animations. For exmaple if you go from search to new Group using shortcuts or if you navigate to new money request confirmation modal and then you click on details of the recipient there is no animation for the User details page in RHP.

https://github.com/Expensify/App/assets/85645967/109be79c-fd93-464c-9b67-1b8b4053330f

### Solution

Lets make this animations consistent, everytime we push, replace or pop a page within RHP no matter what flow they are at, lets have the same slide in and out animation.

**Comment by mountiny** [comment]
@WoLewicki @adamgrzybowski this will be our next one to tackle after the remounting issue.

@flaviadefaria no need to act on this one, making it weekly, SWM will handle this

**Comment by mountiny** [comment]
This should be partially solved by https://github.com/Expensify/App/pull/22437

**Comment by mountiny** [comment]
The PR is still going through small issues found

**Comment by mountiny** [comment]
I think this will be @adamgrzybowski next topic to explore

**Comment by flaviadefaria** [comment]
@mountiny just catching up, do I need to take any action at all here?

**Comment by mountiny** [comment]
I think this is fine and we can handle the payments here https://github.com/Expensify/App/issues/20404

Also we would make more specific issue for the animation as this is an old issue just for clarity, deployed going to close this out
