### ISSUE TITLE
Dev - Blank chat report, with no LHN item is created when starting chat with secondary contact method of an account for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account B should have secondary login account C, and account A & account B shouldn't have an existing chat history.
1. Open a tab where account A is signed in
2. Click on 'FAB' icon
3. Click on 'New chat' link
4. Enter secondary logging C
5. Click on the suggested result

## Expected Result:
System should start a chat report displaying all header, chat details, and LHN item details with the selected account. The details should be primary account A details.

## Actual Result:
Blank chat report, with no LHN item is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8dbeb7fb-c7f2-4dad-87a4-c22bc7b521ae

**Expensify/Expensify @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688674790243939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
hiya @johnmlee101 - when you have a chance, can you attempt to repro this on dev and report back? i will pick the issue back up once it's confirmed reproducible. ty!

**Comment by johnmlee101** [comment]
I think we just deployed staging 😓 so it might be ready to test

**Comment by johnmlee101** [comment]
<img width="694" alt="image" src="https://github.com/Expensify/App/assets/5258036/ff6a22f5-7fd0-4c9c-a7b6-0f6492c2a788">
on staging its higher, so not sure what we're testing?

**Comment by maddylewis** [comment]
@johnmlee101 - i see so bc the reporter tested this on `Version Number: 1.3.37-3 Dev`, and staging is on `v1.3.38-6`, is this report erroneous at this point?

**Comment by maddylewis** [comment]
got it - in that case, this seems moot. ill close!

**Comment by Natnael-Guchima** [comment]
@maddylewis the issue is reproducible on staging too. 

[Screencast from 2023-07-16 18-19-15.webm](https://github.com/Expensify/App/assets/57330233/2c71ed99-2b36-49fa-912f-21d108e30b8b)
