### ISSUE TITLE
Edit option and other restricted options are not hidden on the first time when deleting the fist thread message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Send message
3. Reply in thread to the sent message
4. Open the reply message
5. Delete the first message on top
## Expected Result: 
Other option without 'mark as read' should be removed from the list of options displayed on hover
## Actual Result: 
All options are available until the user navigates out of thread, and returns back to the thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/53cc6c90-3e64-4ed7-9ec3-037e598e662c

https://github.com/Expensify/App/assets/43996225/09345512-725e-49e8-bb67-6b873471b76f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688580875794009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Agreed, https://github.com/Expensify/App/issues/21103 will make sure the comment is actually deleted, which will in turn address the issue here. Closing.
