### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Dev: After creating a task without assignee “0” displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the “Assign task”
3. Enter title click on “Confirm task”

## Expected Result:
After creating a task without assignee “0” should not be displayed

## Actual Result:
After creating a task without assignee “0” displayed after leaving

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/76f2517a-c8ab-4f05-80ae-9dcb85a4718e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688677922284949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128bb3b4ad89ce372</li>
        <li>Upwork Job ID: 1677273013757554688</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
FYI I kicked off the release less than 5 minutes ago and I'm worried the existence of a new deploy blocker will cause issues. I'll re-add it once the new checklist is up!

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating task without assignee, "0" is displayed

### What is the root cause of that problem?
Issue happens on this line:

https://github.com/Expensify/App/blob/0ee7dfa0dadb6ba11ca4cf08085df9003b0fb452/src/components/TaskHeader.js#L83

`assigneeAccountID` is number and when no assignee, this fallbacks to 0.
And `0 && 0 > 0 && <></>` returns 0

### What changes do you think we should make in order to solve the problem?

remove this redundant condition: `assigneeAccountID &&`

Fixed code will look like this:
```
 assigneeAccountID > 0 && (
```

**Comment by MariaHCD** [comment]
Able to reproduce on dev:

![Screenshot 2023-07-07 at 2 49 34 PM](https://github.com/Expensify/App/assets/12268372/f732656e-dc5d-4868-9288-2c3445ec865d)

@situchan's [proposed solution](https://github.com/Expensify/App/issues/22398#issuecomment-1625202355) seems to fix this.

I see that logic was added in https://github.com/Expensify/App/pull/20689 that was just deployed to staging.

cc: @hoangzinh @mollfpr @joelbettner

**Comment by situchan** [comment]
@MariaHCD this bug existed from the beginning but recent PR just revealed this.
I'd say https://github.com/Expensify/App/pull/20689 is not a regression as the bad logic already existed and deployed to production 2 weeks ago.
```diff
-                               {props.report.managerID && props.report.managerID > 0 && (
+                               {assigneeAccountID && assigneeAccountID > 0 && (
```

**Comment by MariaHCD** [comment]
> `assigneeAccountID` is number and when no assignee, this fallbacks to 0.
> And `0 && 0 > 0 && <></>` returns 0

Confirmed that [getTaskAssigneeAccountID](https://github.com/Expensify/App/blob/0ee7dfa0dadb6ba11ca4cf08085df9003b0fb452/src/libs/actions/Task.js#L648-L659) does indeed return `0` if no assignee is set because the managerID in Onyx is `0`:

![Screenshot 2023-07-07 at 3 04 10 PM](https://github.com/Expensify/App/assets/12268372/549ecc43-8aab-4465-aa2c-7815335b00b6)

Let's prioritize fixing this and go with @situchan's solution!

**Comment by MariaHCD** [comment]
Will still need a C+ to help review and test.

**Comment by MariaHCD** [comment]
Summary: we're going with @situchan's fix as outlined [here](https://github.com/Expensify/App/issues/22398#issuecomment-1625202355) to fix this deploy blocker. Will need @aimane-chnaif's help to review and test!

**Comment by MariaHCD** [comment]
> Before we will return `null` if `childManagerEmail` is a falsy value, but with above change, we might return 0.

Ah, nice catch. Thanks for sharing!

**Comment by Julesssss** [comment]
Thanks for the quick fix all, I'm going to check it off the [deploy checklist](https://github.com/Expensify/App/issues/22399).

**Comment by MitchExpensify** [comment]
Invites sent to @ayazhussain79  @situchan for eventual payment 👍

**Comment by ayazhussain79** [comment]
@MitchExpensify Offer accepted, Thank you

**Comment by MitchExpensify** [comment]
Reminder set to pay out on 7/17 👍 

Lets square off the BZ steps above in advance of that @aimane-chnaif  🚀

**Comment by MitchExpensify** [comment]
Payments issued! Friendly bump on @aimane-chnaif on the BZ steps :)

**Comment by MitchExpensify** [comment]
friendly bump @aimane-chnaif 👍

**Comment by MitchExpensify** [comment]
Awesome, thank you @aimane-chnaif !
