### ISSUE TITLE
Web - Clicking ToS before filling fields in connect bank account throws an error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspaces and click on bank account
2. Click on connect to bank account / "Connect Manually"
3. Click on the Tos checkbox with out filling routing and account number fields
4. Observe that please enter a valid routing number error is thrown
5. Uncheck the Tos check box
6. Fill the routing number filled with a correct routing number and check the ToS check box, observe that no please enter a valid account number error is not thrown

## Expected Result:
Error should either not be thrown or should be consistent to both empty routing number and empty account number

## Actual Result:
Error is thrown when checking Tos while routing and account number field are empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e35eeed3-e87b-4bea-8497-e6f5a536ae4d

https://github.com/Expensify/App/assets/93399543/60810010-8c8d-41e2-9c08-58aa114a1a5d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688640219628169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cubuspl42** [comment]
This looks like an intended behavior. You focused an input and then left in an invalid state. So an error is displayed under that input. Checking the checkbox is not crucial here.

**Comment by SofoniasN** [comment]
@cubuspl42 the problem here is that the error is not consistent in the two fields, the routing number field and the account field. As mentioned in the expected result, either the error throwing should be consistent or no error should be sent when clicking ToS when both fields are not focused

**Comment by cubuspl42** [comment]
@SofoniasN You're suggesting that there's some defined behavior here for checking the ToS checkbox, while I'm not aware of any such defined behavior. 

What matters is that the input is unfocused. When a text input gets unfocused, and is left in an invalid state, an error is displayed under that input. This behavior is consistent between both the "Routing number" and the "Account number" text fields.

While I understand that someone might think that checking the ToS checkbox is somehow special, it's not. It's an input like any other. Only the "Continue" button is special in this matter.

**Comment by sakluger** [comment]
The same thing happens if you start filling out the account number before the routing number, so basically, we just throw a field validation error if you start filling out a form in the wrong order. This is more of a feature request rather than a bug report, so I'm going to close.
