### ISSUE TITLE
[$1000] Web - Inconsistent Enter key behaviour on Split bill page vs Invite members page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Settings > Workspace > Select a workspace > Members > Invite
2. Hit Enter key on keyboard
3. Observe the behavior by hitting enter key repeatedly until all users have been selected and no other user is there to select and hit enter after that as well
4. Go back and click FAB > Split bill > Enter an amount > Next > Do step 2 and 3 here as well and compare the behavior

## Expected Result:
 Enter key should have a consistent action on both split bill and invite members page.

## Actual Result:
 Enter key does different things depending on the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/545870ba-ad65-4435-80dd-1b59630bbcfe

https://github.com/Expensify/App/assets/93399543/55996d5c-48d5-4ab1-a215-e4b1797e7419

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688666077963009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161c0ea65c4194594</li>
        <li>Upwork Job ID: 1678511475953508352</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
reproduced, I think the behavior should be the same!

**Comment by adelekennedy** [comment]
not sure why overdue was added again - commenting to remove!

**Comment by mananjadhav** [comment]
I think before we proceed to review the proposals, @adelekennedy we should define consistency? I mean of the current two disparities, which one is the expected result?

**Comment by adelekennedy** [comment]
great point! I would assume we want to follow the invite flow but I'll discuss in bug-zero

**Comment by adelekennedy** [comment]
huh - I was just re-testing this to post and I see that the behavior is the same now. (hitting enter selects everyone on the list) 

@mananjadhav I think this has been fixed

**Comment by adelekennedy** [comment]
Just tested again on desktop prod - I think we should close this out @Nathan-Mulugeta will be due for the reporting bonus

**Comment by adelekennedy** [comment]
great! Will you apply [here](https://www.upwork.com/jobs/~0161c0ea65c4194594) @Nathan-Mulugeta ?

**Comment by Nathan-Mulugeta** [comment]
Just applied @adelekennedy

**Comment by adelekennedy** [comment]
Offer sent on Upwork

**Comment by Nathan-Mulugeta** [comment]
Offer accepted @adelekennedy

**Comment by adelekennedy** [comment]
and paid!
