### ISSUE TITLE
Web - User email is shown for chats created  offline but not for chats created online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a New chat with a New User
2. Go to the profile by clicking on the header and notice Email is not displayed
3. Force Offline
4. Create a New chat with a New User
5. Go to the profile by clicking on the header and notice Email is displayed.

## Expected Result:
Consistency between online and offline

## Actual Result:
Inconsistency between online and offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/705059fc-cf18-43b2-81e3-d3e88ac24419

https://github.com/Expensify/App/assets/93399543/7c394454-bfb8-48e2-82af-08ca2e993b10

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688671203208689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Will review today!

**Comment by dylanexpensify** [comment]
Reviewing today, got caught up before, sorry!

**Comment by dylanexpensify** [comment]
Unable to repro, seeing email in online and offline. @daveSeife can you confirm if still occurring on current build?

**Comment by daveSeife** [comment]
@dylanexpensify i still can reproduce it too

**Comment by dylanexpensify** [comment]
ahhh I can repro on production, but not staging, which leads me to think it'll be fixed with next deploy!

**Comment by dylanexpensify** [comment]
I'll reopen if not!

**Comment by daveSeife** [comment]
Hi, @dylanexpensify I was able to repro this after the last two deployments can you please check if this issue should be reopened?

https://github.com/Expensify/App/assets/49120316/ad35d211-3cb9-421a-8593-f3abf15b3a3b

**Comment by daveSeife** [comment]
Friendly bumb @dylanexpensify
