### ISSUE TITLE
[HOLD for payment 2023-07-21] [Polish] `I’ll settle up elsewhere` shown on the iouReport header pay button instead of `Pay elsewhere`

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#22429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send an iouRequest from userA to userB
2. As userB, navigate to the DM with userA
3. Observe that the button reads `Pay elsewhere`
4. Now navigate to the iouReport. 
5. Observe that the pay button in the header reads `I’ll settle up elsewhere`

## Expected Result:
`Pay elsewhere` should be displayed in the button. 

## Actual Result:
`I’ll settle up elsewhere` shows in the button.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All

**Version Number:** v1.3.38-3
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1496" alt="Pasted Graphic 4" src="https://github.com/Expensify/App/assets/16232057/04b831ba-c634-4e3b-8bf9-c7ab37e49ee1">

Note: The expenseReport preview and expenseReport header display correctly, as does the iouReport preview. It's just the iouReport header that still seems incorrect. 

**Expensify/Expensify Issue URL:**
**Issue reported by:** trjexpensify
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199c87b0856c6703d</li>
        <li>Upwork Job ID: 1677338574709522432</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by mountiny** [comment]
previously in the pr we wanted to keep this copy for IOU messages https://github.com/Expensify/App/pull/19817#issue-1732380090, if we want to go with Pay elsewhere for IOUs too now, we can do it.

**Comment by trjExpensify** [comment]
Yep, it should be consistent in all places: IOU Report Preview, iouReport header, expense report preview, expenseReport header. 👍

**Comment by mountiny** [comment]
PR is up in review

**Comment by mountiny** [comment]
We just got $1000 to @aimane-chnaif here

**Comment by trjExpensify** [comment]
Sounds good! Will keep it open until the 21st. 👍

**Comment by trjExpensify** [comment]
@aimane-chnaif sent you an offer!

**Comment by trjExpensify** [comment]
Paid!
