### ISSUE TITLE
Web - When deleting the last unread message offline, the New marker briefly appears for a second before disappearing & New Messages notification persists after message is deleted.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22434]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat;
2. Send a new message;
3. Mark it as unread;
4. Be offline
5. Delete the message;
6. Be Online
Notice that the green New marker disappears after a delay. And also Start scrolling up and notice that the New Messages notification is there

## Expected Result:
The new marker disappears with no delay and The New Messages notification is also gone.

## Actual Result:
The new marker disappears after a delay and The New Messages notification is there

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ff524798-a416-4a3b-a060-3af8308f270c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688667094909449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Wrote in slack as I cannot reproduce this either.
