### ISSUE TITLE
Multi line task description is not displayed for userB

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the userA’s account
2. Open a UserB’s chat
3. Go to the “Assign task”
4. Enter title and 5 lines of description and click on “Confirm task”
5. Open another browser and log in with userB account
6. Open userA’s chat ask go to the task detail
## Expected Result: 
Multi line task description should be displayed for userB
## Actual Result: 
Multi line task description is not displayed for userB

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/22b235d6-da6b-427f-8fb9-20b1ff1b3f45

https://github.com/Expensify/App/assets/43996225/da8db5b1-323d-4f90-9b4c-86676e735a95

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688757038314039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@thienlnam  This is assign task bug

**Comment by thienlnam** [comment]
This is a dupe - getting fixed internally https://github.com/Expensify/Expensify/issues/297303
