### ISSUE TITLE
Web -  Inconsistency copy report message to clipboard buttons

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22441]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Select a part of any message
3. In the mini menu context on the right, click on button icon "Copy to clipboard"
4. Cmd+V to paste the result to the chat composer

## Expected Result:
 Only selected text is copied to clipboard and pasted to the chat compose.

## Actual Result:
The whole message is pasted to the chat composer instead of a part of selected text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c410df7b-14a9-4e88-87fa-53068ec54884

https://github.com/Expensify/App/assets/93399543/d74e1469-6a5f-43cf-9f2f-5064b578341f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688716499130479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
I think this isn't a bug, and rather how I would expect the feature to work:

When you select the text and right-click, it makes sense to only take the text that's highlighted. 

When you select the copy function against the entire comment, away from the highlighted text, then copying the entire comment feels correct. 

I'm going to close this out as I don't think we need to correct anything here.
