### ISSUE TITLE
Web - Details page is opened twice on navigating back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22450]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On staging dot create a public room
2. Click on header > Settings > Notify me about new message > Select a different option
3. Click back and notice you're on details page.
4. Again click back and notice again the same details page gets opened

## Expected Result:
Details page should not open twice on navigating back

## Actual Result:
Details page is opened twice on navigating back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d990bf45-6888-4017-ad31-463c01480286

https://github.com/Expensify/App/assets/93399543/3788f235-6e8b-4296-bc19-2b407c61e5f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688725115796579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
All the linked issues are closed. cc @aimane-chnaif since you were on those issues. Any context as to why we haven't resolved this issue?

**Comment by JmillsExpensify** [comment]
@aimane-chnaif bump on that last question.

**Comment by JmillsExpensify** [comment]
Ok great! That is open now, so I'll close this one.
