### ISSUE TITLE
Web - Threads - Unnecessary scrollable empty space in beginning in threads

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and go to any chat.
2. Hover over any message and click on reply in thread.
3. Reply to the thread with a message spanning multiple lines or with like 15-20 messages of 1 line each.
4. Scroll in the chat screen and notice that there is empty space in beginning in chat.

## Expected Result:
Empty space should be visible initially when there are less messages but when messages are sent, empty space should be removed.

## Actual Result:
There is empty space in beginning which is scrollable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.36-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3519d1a2-9d8c-4e53-8b56-67469ed32156

https://github.com/Expensify/App/assets/93399543/b739c1ce-98a2-407d-8e81-e43bd442c2cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688720029425949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Scrollable empty space is visible in the beginning of thread chats.
### What is the root cause of that problem?
For rendering the first message in threads, we use `ReportActionItemParentAction` -
https://github.com/Expensify/App/blob/58f663a2ff05bd06be3dd9a438cad8ad86d3ac68/src/pages/home/report/ReportActionItemParentAction.js#L61-L73
Line 61 and 62 i.e. the two `View` wrappers are responsible for showing the scrollable empty space in the beginning for thread chats which is not needed since there is no background in the beginning like the main chats. This empty space makes the UI look weird for thread chats.
### What changes do you think we should make in order to solve the problem?
We should remove the two `View` wrappers in line 61 and line 62 and directly show the `ReportActionItem` -
```javascript
<OfflineWithFeedback
    pendingAction={lodashGet(props.report, 'pendingFields.addWorkspaceRoom') || lodashGet(props.report, 'pendingFields.createChat')}
    errors={lodashGet(props.report, 'errorFields.addWorkspaceRoom') || lodashGet(props.report, 'errorFields.createChat')}
    errorRowStyles={[styles.ml10, styles.mr2]}
    onClose={() => Report.navigateToConciergeChatAndDeleteReport(props.report.reportID)}
>
    {parentReportAction && (
        <ReportActionItem
            report={props.report}
            action={parentReportAction}
            displayAsGroup={false}
            isMostRecentIOUReportAction={false}
            shouldDisplayNewMarker={props.shouldDisplayNewMarker}
            index={0}
        />
    )}
    {!props.shouldHideThreadDividerLine && <View style={[styles.threadDividerLine]} />}
</OfflineWithFeedback>
```
### What alternative solutions did you explore? (Optional)
NA
Result -
https://github.com/Expensify/App/assets/31413407/8f3386f3-8211-484d-b668-f3fef5f253d1

**Comment by thienlnam** [comment]
This is intended - we're working on adding an empty state graphic up there so this looks less confusing

https://expensify.slack.com/archives/C049HHMV9SM/p1688766023115709?thread_ts=1688720029.425949&cid=C049HHMV9SM
