### ISSUE TITLE
Web - LHN last message shows as multiline after the last message is flagged as Harassment/Assault

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A sends a multiline message to B
2. User B flag the message as Harassment/Assault
3. Observe the LHN last message

## Expected Result:
 Last message shows as a single line text

## Actual Result:
Last message shows as a multiline text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.37-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e036ca84-337f-4f7f-999d-128e996a2224

https://github.com/Expensify/App/assets/93399543/98d1efa0-b9ec-462b-be3d-aa62a2b7d3f0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688727004082269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Lots of high priorities. Getting to this tomorrow
