### ISSUE TITLE
[HOLD for payment 2023-08-10] Match Report Header and LHN Avatars 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22468]
Part of https://github.com/Expensify/App/issues/20486. We want to match the header avatars to the LHN avatar patterns.

Used for both https://github.com/Expensify/App/issues/22333 and https://github.com/Expensify/App/issues/22332 so I am separating out into its own issue.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197cbf143b0f44102</li>
        <li>Upwork Job ID: 1677617651206991872</li>
        <li>Last Price Increase: 2023-07-08</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
**Payment summary:**

$1000 to @parasharrajat via NewDot 

Please go ahead and request the payment @parasharrajat 👍

**Comment by MitchExpensify** [comment]
Based on [this SO](https://stackoverflowteams.com/c/expensify/questions/16949) we can close this out in the meantime seeing as no BZ steps are needed here 🚀

**Comment by JmillsExpensify** [comment]
Reviewed the details for @parasharrajat. This $1,000 payment is approved via NewDot based on the BZ summary above.
