### ISSUE TITLE
Web - More than 4 Avatars are displayed on the A group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Create a group chat with more than 4 users.
notice that all the avatars are displayed on the created group chat page.

## Expected Result:
4th avatar overlaid with the number when there are more than 4 users.

## Actual Result:
 all the avatars are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3439856b-7263-4526-b949-7830e622e077

https://github.com/Expensify/App/assets/93399543/fda0f1a6-b55f-46b5-9bb9-0bf6eace6b2f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688796213466909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
yes, Thank you @allroundexperts! It looks like this is expected.

**Comment by cristipaval** [comment]
@kbecciv could you please update your test cases accordingly?
