### ISSUE TITLE
Web - Notification for Currency Change Does Not Appear in Admin Section Offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22474]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspace and click on the dot to access the Admin section.
2. Navigate to Settings > Preferences and enable the "Force Offline" option.
3. Go to Settings > Workspace and update the default currency.
4. Observe that the notification for currency change does not appear in the admin section.

## Expected Result:
The notification should appear when we change the currency in the admin section while offline.

## Actual Result:
The notification does not appear when we change the currency in the admin section while offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.38-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/39f484d0-884c-4666-8211-30581f73bf1b

https://github.com/Expensify/App/assets/93399543/2ef9ba22-8e7a-4203-a1a0-75d0f96d4886

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688732769895759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
This doesn't appear to be a bug. Workspace Changes require you to be online, and are delivered afterwards if you make any changes when you're offline (which I've just confirmed via testing). Closing!
