### ISSUE TITLE
Dev: Can not search on invite member page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22476]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace
2. Go to members => Invite
3. Try to type something
4. Notice that nothing happens

## Expected Result:
You should text and search without any error

## Actual Result:
Nothing happens and error appears on the console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/772ebcc7-86d1-463f-be7a-faa4876118b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688789657783849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
I was not able to recreate this, and was able to type without issue:

![2023-07-10_07-38-18 (1)](https://github.com/Expensify/App/assets/10926327/84755705-aa98-4a64-abb4-f6384875abcf)

Are they still able to recreate the issue?

**Comment by CortneyOfstad** [comment]
@hungvu193 Let's close this for now, and if you are able to recreate consistently, then feel free to reopen at that time 👍
