### ISSUE TITLE
[$1000] Dev: Web - After deleting a thread message, the message "You" briefly shows up in the LHN before disappearing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task
4. After creating Assign yourself that task
5. Send a thread message and delete it
6. Notice that the message "You" appears briefly in the LHN

## Expected Result:
The message "You" should not appear in the LHN after deleting a thread message

## Actual Result:
After deleting a thread message, the message "You" briefly shows up in the LHN before disappearing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev  v1.3.38-3
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/277c08f4-3219-4307-abe6-50e97e5abb41

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688765209026689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b93ac0fe26c1d0de</li>
        <li>Upwork Job ID: 1678417861188857856</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment]
Updated Step 4:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task
4. After creating Assign yourself that task
5. Send a thread message and delete it
6. Notice that the message "You" appears briefly in the LHN

**Comment by neil-marcellini** [comment]
Not overdue, I'm going to un-assign for now. Please re-assign me when a C+ approves a proposal.

**Comment by bfitzexpensify** [comment]
@aimane-chnaif proposal from @hungvu193 to review in https://github.com/Expensify/App/issues/22487#issuecomment-1628080543

**Comment by bfitzexpensify** [comment]
@aimane-chnaif take a look at the updated proposal in https://github.com/Expensify/App/issues/22487#issuecomment-1628080543 when you get a moment - thanks!

**Comment by bfitzexpensify** [comment]
Bump to review updated proposal @aimane-chnaif - thank you!

**Comment by bfitzexpensify** [comment]
How is https://github.com/Expensify/App/issues/22487#issuecomment-1628080543 looking @aimane-chnaif?

**Comment by jjcoffee** [comment]
Unable to repro on latest main.

**Comment by ayazhussain79** [comment]
i have reported this bug 3 weeks ago so maybe a PR fixed this bug after i reported so am i eligible for reporting bonus ?

**Comment by bfitzexpensify** [comment]
Great, closing this out. @ayazhussain79 since you reported the other bug that led to this fix, we wouldn't pay out the reporting bonus twice.
