### ISSUE TITLE
[Held on #22362] Inconsistency bug - App displays (edited) text in same line for single line link but in new line for multiline link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the app
2. Open any report
3. Send any single line link
4. Edit the link and observe that '(edited)' text is displayed on same line
5. Edit the link again and make it multiline and observe that now '(edited)' text is displayed on new line
## Expected Result: 
App should maintain consistency on displaying (edited) text for same type of content
## Actual Result: 
App displays (edited) text in same line for single line link but shifts to new line for multiline link
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/700609c2-6f38-4429-885e-9968d7eb1649

![Snip - New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/d72e138f-07d1-4803-89c0-c655d354ed4c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688795237173579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01152b5b92985d91f4</li>
        <li>Upwork Job ID: 1687918361686118400</li>
        <li>Last Price Increase: 2023-08-05</li>
    </ul>
</details>

**Comment by anmurali** [comment]
Can reproduce this but @bernhardoj are you saying this is a duplicate?

**Comment by anmurali** [comment]
Ok updated title and degraded to a weekly

**Comment by mollfpr** [comment]
Not reproducible in the latest staging.

![Screenshot 2023-08-06 at 21 33 20](https://github.com/Expensify/App/assets/25520267/5ba36b5c-49d0-4d69-8caf-64da04913667)

**Comment by anmurali** [comment]
Lets close this!
