### ISSUE TITLE
[$1000] The 'Back' button tooltip disappears slower than the page transition in the RHP causing it to appear in the wrong place

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to #announce room of a workspace where you are the admin
2. Click the room header to access the details page
3. Click Settings to go one page deeper in the RHP
4. Click on the back button `<` to navigate back a page

Note: The issue isn't isolated to only the #announce rooms, this was just deemed the most visible example to convey in the bug report. 

## Expected Result: 
The back button tooltip should not appear in limbo after the page transition

## Actual Result: 
The back button tooltip is slower to disappear than the page transition, causing it to appear in the wrong position briefly.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/48787c53-5a0e-40f2-996f-c78986304885

https://github.com/Expensify/App/assets/43996225/dbcd4c35-a2b5-497e-bea5-53be5e9915f5

<img width="605" alt="image" src="https://github.com/Expensify/App/assets/16232057/6d079bf1-f299-431b-82c8-84082e0d82ff">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688795425718309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e037b92cfb2164b</li>
        <li>Upwork Job ID: 1679490580416520192</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Commented in [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688795425718309), I can't seem to see this one. Looks like the back button is aligned underneath the back caret.

**Comment by trjExpensify** [comment]
So it seems like the actual issue here is that the page transition is faster than the tooltip. @ginsuma pointed this out in thread with this helpful screengrab: 

<img width="605" alt="image" src="https://github.com/Expensify/App/assets/16232057/6d079bf1-f299-431b-82c8-84082e0d82ff">

>When we click back button, there is a transition from left to right in the content.
=> The tooltip move from left to right too => the mouse hover on button out => the animation run to hide tooltip  and it takes time.

I find it hard to see this one, but I'm asking whether it's actually isolated to the announce room only versus all secondary+ pages with a back button tooltip and a page transition from left to right.

**Comment by trjExpensify** [comment]
Okay, so it's not isolated to the #announce room only as the bug report suggests, so I've made a note in the OP to convey that. 

@mountiny, wanted to put this on your radar from nav reboot. I can barely notice it IRL myself, but when the frame is paused in a screen recording like the above it's pretty clear. I'm down for someone to look into it for a simple fix to polish it up if possible, but I wouldn't spend much time on this if it's difficult.

**Comment by mountiny** [comment]
removing the help wanted label til we decide

**Comment by trjExpensify** [comment]
>@trjExpensify I dont know I have seen a similar bug report before and rejected it, its really hard to notice and minor. I feel like we could close this one out as well honestly.

That works for me, and it's good we now have this issue here for a historical search in the future. On that note then, closing it out!
