### ISSUE TITLE
[$1000] strikethrough is not displayed on edited link when deleting the link while offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22491]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Send any link
3. Edit the link and make any edits
4. Switch off the internet
5. Delete the link and observe that '(edited)' has strikethrough but not the link
## Expected Result: 
App should strikethrough the message when deleted while offline
## Actual Result: 
App does not strikethrough the edited link when deleted while offline

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fcfa11f6-1de9-4dad-aa5b-2c8e55ddbca4

https://github.com/Expensify/App/assets/43996225/075fd75b-cfdf-4df7-a91f-55e17b15ff2f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688795722435449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faccd901790e501c</li>
        <li>Upwork Job ID: 1678669419144200192</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Repro'd:

![image](https://github.com/Expensify/App/assets/59587260/baae317a-3921-41ff-9006-e008a0890ca2)

**Comment by kadiealexander** [comment]
@thesahindia I'd love your thoughts on [this](https://github.com/Expensify/App/issues/22491#issuecomment-1627649422) please!

**Comment by kadiealexander** [comment]
Closing as per https://github.com/Expensify/App/issues/22491#issuecomment-1636412143
