### ISSUE TITLE
[HOLD for payment 2023-07-20] Dev:  App crashes when creating a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task

## Expected Result:
The App should remain stable and not crash after creating a task

## Actual Result:
After creating a task, the App crashes unexpectedly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.38-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c40fca4c-4c97-4e61-9aba-bf11783990e0

![Screenshot 2023-07-08 at 4 22 20 AM](https://github.com/Expensify/App/assets/93399543/1bbdcd5d-e9f7-4d7b-9049-600a2f1a84ee)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688766194182809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment]
@thienlnam has fixed this in this [PR](https://github.com/Expensify/App/pull/22458)
Here is slack thread message about it https://expensify.slack.com/archives/C049HHMV9SM/p1688775549032519?thread_ts=1688766194.182809&cid=C049HHMV9SM

**Comment by thienlnam** [comment]
We can wait until https://github.com/Expensify/App/pull/22458 passes the 7 day production regression though

**Comment by maddylewis** [comment]
to-dos:
- [ ] wait for 7 day regression period (complete on July 14 i think)
- [ ] Pay $250 reporting bonus to @ayazhussain79

**Comment by maddylewis** [comment]
moved to daily since payment is due tomorrow 👍

**Comment by ayazhussain79** [comment]
@maddylewis Offer Accepted, Thank you
