### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] The "No results found" message in the emoji picker is scrollable

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any chat
3. Open emoji picker
4. Type "tt" in the search input
5. Try to scroll "No results found" message
## Expected Result: 
The "No results found" message should remain fixed in its position
## Actual Result: 
The "No results found" message is scrollable

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/da317857-ffa5-4b5f-ae45-944027c7abb9

https://github.com/Expensify/App/assets/43996225/84567b8e-dde8-48c9-bf44-b8bc0aae84b9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688824480134429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4d1df988507fb8b</li>
        <li>Upwork Job ID: 1678462833490141184</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by sobitneupane** [comment]
Thanks everyone for the proposal.

[Proposal](https://github.com/Expensify/App/issues/22504#issuecomment-1627656978) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
Oh yes. You are right @GItGudRatio. Search list also has the same behavior.

Rather than a bug, it can be considered as polish. I am okay with the present state where "No results found" bounces/scrolls. But If we want to polish it,
[Proposal](https://github.com/Expensify/App/issues/22504#issuecomment-1627627850) from @GItGudRatio looks good to me. 

cc: @puneetlath

**Comment by puneetlath** [comment]
Makes sense to me too. Sorry accidentally unassigned everyone so had to re-assign. Sorry for the noise! 

Looking forward to your PR @GItGudRatio

**Comment by lschurr** [comment]
PR up on July 11th at 12:32pm PT
Merged July 13th at 7:03am PT

Qualifies for bonus.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18221
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18221#issuecomment-1648205714
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is an edge case. I don't think any udpate on the PR review checklist is required.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Login to newDot.
2. Navigate to any chat.
3. Click on the Emoji button in the composer.
4. Enter some random text. Verify that the "No results found" is not scrollable/bouncing.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
@lschurr Payment Requested on newDot.

**Comment by lschurr** [comment]
Offer sent @aman-atg

**Comment by lschurr** [comment]
All set. Closing this one out.

**Comment by JmillsExpensify** [comment]
Reviewed details for @lschurr. This pay of $1500 (base + urgency bonus) is accurate [based on comment](https://github.com/Expensify/App/issues/22504#issuecomment-1648187226) from Business Reviewer and approved for payment in NewDot.
