### ISSUE TITLE
[HOLD for payment 2023-07-20] [HOLD for payment 2023-07-17] Login - Crash when navigating to the concierge chat via deeplink after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot
2. Go to https://staging.new.expensify.com/concierge
3. Verify that you are taken to the login screen
4. Log in to NewDot with any account

## Expected Result:
You're navigated to the concierge chat after login

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0fac22f8-7138-4e71-949d-fe94938b50d9

![Bug6121132_image__129_](https://github.com/Expensify/App/assets/78819774/105b0342-6e40-4d80-8e6d-278a6b8156f1)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdf0596ececb29a0</li>
        <li>Upwork Job ID: 1683603845958860801</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by francoisl** [comment]
@c3024 are you available to submit a PR for this please?

**Comment by francoisl** [comment]
Since this is a deploy blocker, I'm going to submit a PR now.

**Comment by francoisl** [comment]
Yes @c3024 we'll compensate since we used your proposal (tagging a BugZero team member). Also assigning to @thesahindia for the PR review and testing.

**Comment by anmurali** [comment]
Not overdue, will pay tomorrow, which is the 20th!

**Comment by anmurali** [comment]
Payments can be processed now. I am OOO for 10 days so I am going to let someone else on the BZ team take care of this.

**Comment by alexpensify** [comment]
I'm confirming the payment amounts and will prepare them tomorrow. Sorry for the delay!

**Comment by alexpensify** [comment]
Alright, the payment process has started in Upwork. @c3024 please accept and I can complete the payment process. 

Heads up, I didn't include the bonus because we just used the proposal, and an Expensify engineer implemented the code. Let me know if there are other questions. 

--- 

@thesahindia - please update the checklist and within ND, please request payment + urgency bonus since you were involved in the review process.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @c3024 $1000
-  Contributor+ that helped on the issue and/or PR - @thesahindia $1500

Upwork Job: 
https://www.upwork.com/jobs/~01cdf0596ececb29a0

*If applicable, the bonuses will be applied on the final payment

Extra Notes regarding payment: https://github.com/Expensify/App/issues/22502#issuecomment-1650567246

**Comment by alexpensify** [comment]
The payment has been sent to @c3024 via Upwork. 

--- 

@thesahindia please complete the checklist, so we can close this GH. Heads up, please request payment from @JmillsExpensify. Anu is currently OOO. Thank you!

**Comment by alexpensify** [comment]
@thesahindia any update on the checklist here? I'd like to close this out soon. Thank you!

**Comment by alexpensify** [comment]
Thank you for that update! I'm going to close this out now.

**Comment by JmillsExpensify** [comment]
$1,500 payment for @thesahindia approved based on BZ summary.
