### ISSUE TITLE
Group - Username B is not updated when user A searches for it via New Group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22246
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Open the app and log in with user A
3. Open the app on another device and log in with user B
4. Change username B
5. On user A's device, click on the 'Plus' icon, select 'New group', search for user B

## Expected Result:
Changes to username B should be visible to user A

## Actual Result:
Username B is not updated when user A searches for it via New Group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/30d4538a-2d51-411c-9c5e-769a2d7561d2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
This was meant to be, until you have added the User A to the chat and received a message from the User A, the group list won't  have its `name`.

**Comment by johncschuster** [comment]
Thanks for calling that out, @jeet-dhandha! Are you able to point out where we made that behavior intended? I believe you're right, but pointing to where we intended it would be ace!

**Comment by jeet-dhandha** [comment]
@johncschuster - This is mostly done on backend when `User A` first messages to the `User B` then the User A's `login` will be added to `login` key of `report` and thus will show up in Search List for Group.

**Comment by johncschuster** [comment]
Got it. Thanks for spelling that out!

**Comment by johncschuster** [comment]
So in that case, it sounds like we can close this issue out. Does that sound right to you, @jeet-dhandha?

**Comment by jeet-dhandha** [comment]
Aye aye, sir 🫡
