### ISSUE TITLE
[$1000] Dev :  On task view page header Title is not translated on Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on FAB button -> Click Assign task
3. Enter title -> Click Next -> Select Share somewhere -> Click confirm task (Change language to Spanish)
4. This will navigate to created task -> Notice Header of Title field
Expected Result: Title should be translated to Spanish
Actual Result: Title does not translated to Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-08 at 9 23 56 PM](https://github.com/Expensify/App/assets/43996225/0177995a-ad7a-4115-9a15-8a21049a9a23)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688831625416919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011104443f63fd5252</li>
        <li>Upwork Job ID: 1679621464731418624</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
On task view page header Title is not translated on Spanish
### What is the root cause of that problem?
The root cause is we have not add translation key for `title` on `taskView` page
### What changes do you think we should make in order to solve the problem?
We just need to replace plain `title` text to use `props.translate('task.title’)` which will translate as per language here https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/ReportActionItem/TaskView.js#L68C28-L68C28
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jasperhuangg** [comment]
Ahh sorry for the confusion, will fix in my PR!

**Comment by michaelhaxhiu** [comment]
cool, we can pay the bug bonus as it was fixed after reported by timeline of events. upwork job created to pay bug bonus

**Comment by michaelhaxhiu** [comment]
invited you to the job, post here when you accept plz!

**Comment by michaelhaxhiu** [comment]
Sorry for the delay, bug bonus is paid!
