### ISSUE TITLE
[$1000] Keyboard closes while selecting members on invite page on mWeb vs keyboard stays open on android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace and go to invite members page
2. Select users from the list and notice the keyboard behavior on native and on mWeb and compare the two
## Expected Result:
 keyboard behavior should be consistent between android and mWeb
## Actual Result:
 keyboard stays open on native but closes on mWeb

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dcaeda4a-3929-43b3-a1ed-32e416e0da93

https://github.com/Expensify/App/assets/43996225/5d179185-5abc-413a-b478-4dcf60f5f4df

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688834077644289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112a3b6c2cacb43a8</li>
        <li>Upwork Job ID: 1678431603352903680</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Hmm, interesting. I agree this is inconsistent. I wonder if it's because of our own implementation or just the default behavior on native vs browser. In any case I'll mark as external for now for thoughts. 

@Nathan-Mulugeta what happens on iOS?

**Comment by Nathan-Mulugeta** [comment]
I can't test on ios @puneetlath

**Comment by mollfpr** [comment]
Sorry I got a problem with updating the NPM, I'll be posting an update in the morning.

**Comment by mollfpr** [comment]
@tienifr It seems to be working, but on mWeb/Chrome the keyboard now popping up again like https://github.com/Expensify/App/issues/20636

**Comment by mollfpr** [comment]
@tienifr Could you try it on Android Chrome?

**Comment by mollfpr** [comment]
@tienifr Could you attach the diff you use?

**Comment by mollfpr** [comment]
@tienifr The issue https://github.com/Expensify/App/issues/20636 arises again with your solution.

[mwebchrome.webm](https://github.com/Expensify/App/assets/25520267/43b4fee3-bdb3-4fea-a76d-1de00e818664)

On Android, the keyboard is not pop again on pressing the option.

**Comment by mollfpr** [comment]
@tienifr Here is the latest main `v1.3.43-3`.

The step:

1. Open the invite workspace page and make sure that the input is focused and the keyboard is open
2. Press the arrow down button in your Android device to hide the keyboard
3. Press the option select
4. The keyboard shouldn't be pop up again like in the Android app

<details>
<summary>mWeb/Chrome</summary>

[mwebchrome.webm](https://github.com/Expensify/App/assets/25520267/5d8f3f1c-358e-4d99-a7e2-6d48a91150c8)

</details>

<details>
<summary>Android</summary>

[android.webm](https://github.com/Expensify/App/assets/25520267/2a5356ad-16a0-4239-aacd-473e13b20f32)

</details>

**Comment by mollfpr** [comment]
@tienifr Thanks for the update.

Several questions.
- Where is the 100 value come from in `!this.isKeyboardOpen && this.props.windowHeight < prevProps.windowHeight -100`?
- Why it's working differently in mWeb Chrome?

**Comment by mollfpr** [comment]
@tienifr Is there any other way to detect the keyboard open in Chrome? I feel watching the window height is a workaround.

**Comment by mollfpr** [comment]
Sorry for the delay, doesn't have much time left but I'll give an update in the morning.

In summary, I think we can ignore the case where the keyboard is close, and the input still focuses on mWeb Chrome. After all, this issue is regarding the keyboard being close upon selecting the option row.

**Comment by mollfpr** [comment]
Sorry for the delay.

Test the [proposal](https://github.com/Expensify/App/issues/22510#issuecomment-1629984503) from @tienifr, and it does fix this issue. The other case where the keyboard is closed, and the input still focuses is out of the scope of this issue. Let's move forward with the @tienifr solution 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
Friendly bump @puneetlath on this https://github.com/Expensify/App/issues/22510#issuecomment-1660632056

**Comment by puneetlath** [comment]
Hi guys, sorry for the delay here. I've had second thoughts and I don't feel like this is something we should fix. It feels like we're hacking around how that native platforms themselves work and making our code more complex/brittle to do it. My thinking is that we should actually just close this issue and leave this behavior as-is. 

Sorry for the time that was spent getting to this point so far. Please feel free to continue the conversation if you disagree.
