### ISSUE TITLE
[$1000] No error shown if User B leaves the room while splitting the bill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a room in public mode
3. Now on another web chrome login with User B as an Expensify user (Imp step)
4. On User A side, click on + icon on the room and click on split bill option > Enter the amount and click on next so that you get to see the Split money page (Do not split the amount and let the page remain open)
5. From User B, leave the room
6. On User A, now try to split the bill by clicking on the Split money button and notice nothing happens.
## Expected Result: 
It should have shown an error if User B leaves in between while User A tries to split the bill
## Actual Result: 
No error shown if User B leaves the room while splitting the bill

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/67c1ee9d-0bae-4d84-adaa-4a243abb97bc

https://github.com/Expensify/App/assets/43996225/12fdede4-d9ea-4f82-962c-99d0ae3d7e89

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688567897032649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010901a16a9425020c</li>
        <li>Upwork Job ID: 1678420507829661696</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
reproducible!

**Comment by zanyrenney** [comment]
My only question - what is the error you would expect to see based on other error message and patterns?

**Comment by priya-zha** [comment]
Like in the other cases, we can show 'Hmm, it's not here page' OR if not, then the modal can be dismissed on User's B side.

**Comment by zanyrenney** [comment]
Why do we allow split bill in public room? 
- That's part of the design, we want all users (with a validated account) to be able to split a bill. it enables better bottom up adoption.

what should happen when we split a bill with a user , and then he leaves the room ?
- I think we should throw an error message that's friendly but also reminds the user who left the room that they owe money (user B) "  Got a second to pay the [amount] you owe [person you owe] before you leave [room name]?" or something like that! 

If we think this warrants a larger conversation, let's take this to slack!

**Comment by zanyrenney** [comment]
Brought this to slack - here https://expensify.slack.com/archives/C01GTK53T8Q/p1689860314396989
