### ISSUE TITLE
[$1000] Inconsistent Icon Focus and Lack of Color Change in Payment Section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to "Settings" and select "Payments".
2. Click on "Add Payment" and choose "Paypal. me".
3. Hover over the icon behind the link and observe that The icon behind the link in the PayPal.me section does not focus like the icons in other sections. Additionally, the color does not change to a slight white as expected.
## Expected Result: 
The icon behind the link in the PayPal.me section should focus when hovering over it, and the color should slightly change as in other sections.
## Actual Result: 
The icon behind the link in the PayPal.me section does not focus when hovering over it like the icons in other sections. Additionally, the color does not change to a slight white as expected.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fdaed538-b8a9-46bd-97c7-dbe304bd1404

https://github.com/Expensify/App/assets/43996225/4e4d94c8-fd09-45d5-b16b-3c6434b4dc65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688837421146249
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6162338fd196849</li>
        <li>Upwork Job ID: 1678389245042950144</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent Icon Focus and Lack of Color Change in Payment Section.
### What is the root cause of that problem?
there is no handle for hover and press event on the icon.
### What changes do you think we should make in order to solve the problem?
We can handle hover and press event on the whole link or on the icon only and change the icon color based on it.

```javascript
// we will use whole link PressableWithoutFeedback to apply hover on whole link.
// or surround the Icon with new PressableWithoutFeedback to make the change only in icon
<PressableWithoutFeedback>
      {({hovered, pressed}) => (
             ...
             <Icon
                 ...
                  fill={(hovered || pressed) ? themeColors.iconHovered : themeColors.icon}
              />
              ...       
      )}
  </PressableWithoutFeedback>
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by slafortune** [comment]
Bug report looks good!

**Comment by shawnborton** [comment]
I don't think this is a bug, they are different components.
