### ISSUE TITLE
Password PDF Form: Still able to submit even when Form has error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send pdf that has password
2. Click on that pdf and and click confirm button.  Now enter wrong password, press Confirm and the error will show, press the Confirm button couple of times.
3. Notice that user's still able to submit the form even there's error visible.
If Form has error, we shouldn't allow user to submit the form again.
## Actual Result: 
Still able to submit even when Form has error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f3e5f78e-5e45-41f8-b541-5750eeaa8959

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688538758574899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Password PDF Form: Still able to submit even when Form has error
### What is the root cause of that problem?
In out PDFPasswordForm, we're checking the validation here:
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/components/PDFView/PDFPasswordForm.js#L84-L92
If `validate` returned false then we disabled the submit:
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/components/PDFView/PDFPasswordForm.js#L69-L71
As we can see our validation function only validated the empty password, in this case when password was wrong, `validate` function still return true which caused the issue.
### What changes do you think we should make in order to solve the problem?
We also need to check if `isPasswordInvalid` is true then early return in out submit function.

```javascript
    validate() {
        if (!_.isEmpty(this.state.password) && !this.props.isPasswordInvalid) {
            return true;
        }
     // other code
    }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sakluger** [comment]
This is more of a feature request than a bug. I'm going to close the issue, since I don't think we should prioritize this as a new feature.
