### ISSUE TITLE
Sticky reaction menu blocks add reaction btn

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22520]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on any chat and open it
3. Leave multiple reactions to any message (at least 10)
4. Go down and go up to the message that is at the bottom of our first message and hover over it (You will see sticky reaction box blocks first message's add reaction btn)
## Expected Result: 
Sticky reaction menu shouldn't block add reaction btn. Instead, It is good if it appears at the bottom.
## Actual Result: 
Sticky reaction menu blocks add reaction btn

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (13).webm](https://github.com/Expensify/App/assets/43996225/88c8e1c7-77ff-4773-bfb9-59d694fe9b66)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688558783035259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muxriddinmuqimov77** [comment]
I think it's a good idea to show Sticky reaction menu at the bottom in cases like that. 

![Screenshot from 2023-07-09 18-48-51](https://github.com/Expensify/App/assets/101332597/55f66c22-2cfb-478b-a06c-3d3d09082c89)

**Comment by mallenexpensify** [comment]
> Sticky reaction menu shouldn't block add reaction btn. Instead, It is good if it appears at the bottom.

Since a user can easily scroll up a lil more or to the left to access the 'add emoji/reacji' on the line above, I don't think it's a bug or that we need to address.  I'm going to close but tagging @shawnborton from design in case he disagrees. 

<img width="1265" alt="image" src="https://github.com/Expensify/App/assets/22508304/6bc4bf16-a17e-40fe-a859-f83ab8bc68bf">

**Comment by shawnborton** [comment]
Yup, that works for me too!
