### ISSUE TITLE
Message input take longer time to get focused when keep moving mouse

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22525]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > any chat
2. Click on user's avatar to open the settings
3. Click "Message 'Username' " and start to move mouse quickly
4. When message input get focused, repeat the action but this time without moving the mouse when click "Message Username"
## Expected Result: 
Message input take same time to get focused when keep moving mouse and without moving.
## Actual Result: 
Message input take longer time to get focused when keep moving mouse.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Applause not able to reproduce
**Reproducible in production?:** Applause not able to reproduce
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (5).webm](https://github.com/Expensify/App/assets/43996225/af29e8ab-b0f5-472e-a467-ab066a52a56e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688383193809499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muxriddinmuqimov77** [comment]
### Reproduction steps after choosing chat (more understandable):
1. **Click on User's Avatar and open Profile settings**
2. **Click on "Message Username" and before Settings menu is closed, start moving the mouse bottom to top.** (_In this case you see that message box take some time to get focused_) 
Note: Do Second step as fast as you can as you can see in the video
3. **Repeat second step but this time  after  clicking on "Message Username" don't move the mouse.** (_In this case you see that message box don't take time to get focused_)

**Comment by sophiepintoraetz** [comment]
![2023-07-12_13-50-25 (1)](https://github.com/Expensify/App/assets/42940078/ef0c48d3-b9f9-498a-9d20-b2d62b2bc15a)

I'm not able to reproduce this either.
