### ISSUE TITLE
[Awaiting Miro] [$1000] [HOLD for payment 2023-07-20] Minor ReportActionCompose code clean up

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#22547]
apply[ this change](https://github.com/Expensify/App/pull/21962#issuecomment-1627763320)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cd6d7258bdabb06</li>
        <li>Upwork Job ID: 1689204183230226432</li>
        <li>Last Price Increase: 2023-08-09</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
THis was a small update to an existing issue, so I don't believe payment is required: https://github.com/Expensify/App/pull/21962#issuecomment-1627763320

**Comment by Julesssss** [comment]
Oh damn, yeah. We should have assigned to the original C+. I think a payment is fair though

**Comment by Julesssss** [comment]
Hey Tom, please pay a review bonus to @0xmiroslav

**Comment by trjExpensify** [comment]
Done!

**Comment by trjExpensify** [comment]
@0xmiroslav have you been paid here?

**Comment by trjExpensify** [comment]
@0xmiroslav, I'm going to close these!
