### ISSUE TITLE
Web - Chat - + button is outside the composer when refreshing page with expanded composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any conversation
3. Enter enough line so that expand button appears
4. Tap on expand button
5. Close the keyboard
6. Refresh the page

## Expected Result:
There is no visual issue with the composer

## Actual Result:
+ button in composer is outside the box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3
**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/80a92a5d-682d-479a-b683-37fd8a8a746b

https://github.com/Expensify/App/assets/78819774/995bace4-b6b0-4a38-84d9-d21d45a97c32

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
I am able to reproduce this on prod:

<img width="1204" alt="Screenshot 2023-07-10 at 11 12 26 AM" src="https://github.com/Expensify/App/assets/12980971/02ba7e30-91c1-41b9-8ca2-1e558536f0e5">

Removing deploy blocker label
