### ISSUE TITLE
Contact methods - Error appears when changing the default contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22253
## Action Performed:
1. Open the app and login with a phone number user
2. Open the settings -> contact methods and If not already added, add secondary email account
3. Make secondary email as default
4. Go to any workspace and connect a bank account manually, filling details till step 3
5. Again change default contact to phone number
6. Repeat this process for 3 to 4 times

## Expected Result:
User should be able to change the default contact number

## Actual Result:
Getting Auth changeprimaryLogin returned an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/64ed700d-79c8-4f39-9490-e312b44c349c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I imagine this is a back-end bug that is to do with how we require private domains for VBAs

**Comment by muttmuure** [comment]
I think this is expected for now, but we will revisit when we have workspace level feeds.
