### ISSUE TITLE
[HOLD for payment 2023-07-20] tarea reabrir should be renamed to tarea reabierta(past tense)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  config app on spanish
2.  complete a task
3.  read: `tarea completada` (task finished)
4.  mark it as uncomplete
5.  read: `tarea reabrir` (task open) which is not the same as `task opened` .

## Expected Result:
 user should read: `tarea reabierta` o `tarea abierta`
## Actual Result: 
`tarea reabrir`, which does not makes much sense in spanish.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/3959c8ef-a81b-4dc1-94cb-e253e0ed0b22)
![Snip - (62) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/5ab5a40b-ed58-44fd-88d7-ffe029f2c67e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688435517400369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e76a0e15e54c080d</li>
        <li>Upwork Job ID: 1678413074461335552</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by pecanoro** [comment]
I will be taking care of this one since it's a one-word copy change.

**Comment by pecanoro** [comment]
It's really just one word, so I don't even think we need a C+.

**Comment by puneetlath** [comment]
@dan1d can you apply to the job for the reporting bonus: https://www.upwork.com/jobs/~01e76a0e15e54c080d

**Comment by dan1d** [comment]
@puneetlath I'm getting Access denied when I try to apply for the job on upwork

**Comment by dan1d** [comment]
@puneetlath Accepted, thank you!

**Comment by puneetlath** [comment]
Paid, thanks!
