### ISSUE TITLE
Dev: Web - Back button doesn't navigate to the last opened tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any workspace
2. Click on the workspace name
3. Click on the workspace name again
4. Click on the back arrow

## Expected Result:
When the user clicks on the back arrow it should navigate back to the last opened tab

## Actual Result:
Back button doesn't navigate to the last opened tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3 Dev
**Reproducible in staging?:**  n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aa8a0516-917c-44a6-a5e5-4d13bdfc7f16

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688916260358109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
same RC as https://github.com/Expensify/App/issues/21839.

**Comment by alexpensify** [comment]
Closing - I agree that this one is similar to https://github.com/Expensify/App/issues/21839. Thank you for flagging @Nikhil-Vats.
