### ISSUE TITLE
Dev: IOS – Profile – Clicking on Add payment button throws two console warnings on IOS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open “Settings”
2. Open “Profile”
3. Open “Payments”.
4. Click on  “Add Payment Method“
5. Throws Failed Prop Type Console Warning on IOS.

## Expected Result:
Should not throw console warnings.

## Actual Result:
Throws two console warnings.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52daee81-e79b-4336-b434-21dd2061b449

**Expensify/Expensify Issue URL:**
**Issue reported by:** @CuriousProgramer
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688976097885409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@dukenv0307 Hello, thanls for that insight! So I can catch up, can you link me the original bug report and Slack discussion, or GH, around this?

**Comment by jliexpensify** [comment]
Cheers @dukenv0307 - I agree with Lauren's comment [here](https://github.com/Expensify/App/issues/21302#issuecomment-1602581815):

> this is only a bug on dev and not user facing so we don't need to fix.

The other issues were closed without payment, so doing the same to this one. Thanks!
