### ISSUE TITLE
[HOLD for payment 2023-07-28] Payment method not sticky in the expenseReport view. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#22585]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
`policyExpenseChat` beta to have access to the workspace chats.

1. As the member, create a request for $50.00 > send it to a workspace
2. As the admin of the workspace change the settlement method from `Pay with Expensify` to `Pay elsewhere`
3. Pay the report
4. As the member, create another request for $50.00 > send it to the same workspace
5. As the admin of the workspace, navigate to the member's workspace chat
6. Observe the pay button in the report preview displays `Pay elsewhere` ✅ 
7. Click on the report preview to navigate to the expense report 
8. Observe the pay button in the header displays `Pay with Expensify` ❌ 

## Expected Result:
The `Pay elsewhere` settlement method should have been displayed in the expenseReport view as it's "sticky" and it was the last settlement method used by the admin.

## Actual Result:
The pay button in the expenseReport header incorrectly displayed as `Pay with Expensify`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.38-4
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://github.com/Expensify/App/assets/16232057/599d102f-56a5-489a-93c5-dfe3848f6673

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C02HWMSMZEC/p1688744493384329?thread_ts=1688476481.516029&cid=C02HWMSMZEC

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156192fdb8e16398b</li>
        <li>Upwork Job ID: 1678491715975114752</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Yep, had problems with local vm yesterday. Will aim to make a pr today

**Comment by mountiny** [comment]
PR with fix is in a review

**Comment by mountiny** [comment]
@trjExpensify Thanks Fedi, I think we should add this testcase

**Comment by trjExpensify** [comment]
Nice! @mountiny, this bug was for `expenseReports` on a workspace, so I think we should add both. 

### Sticky Payment Method

**IOUs**

1. As UserB set up a PayPal address.
2. As UserB, request money from UserA.
3. As UserA, navigate to the IOU report and choose to `Pay with PayPal.me`
4. Pay the report.
5. Create a new request as UserB, requesting money from UserA.
6. As UserA, navigate to this new IOU report
7. **Verify** that the settlement button defaults to PayPal.
8. Change the payment type to `Pay elsewhere`.
9. Pay the report.
10. Create a new request as UserB, requesting money from UserA.
11. As UserA, navigate to this new IOU report
12. **Verify** that the default method shown is `Pay elsewhere`. 

**Expense Reports**

1. As the member, create a request for $50.00 > send it to a workspace
2. As the admin of the workspace change the settlement method from `Pay with Expensify` to `Pay elsewhere`
3. Pay the report
4. As the member, create another request for $50.00 > send it to the same workspace
5. As the admin of the workspace, navigate to the member's workspace chat
6. Verify the pay button in the report preview displays `Pay elsewhere`
7. Click on the report preview to navigate to the expense report
8. Verify the pay button in the header displays `Pay elsewhere`

**Comment by trjExpensify** [comment]
@fedirjh sent you an offer! 👍

**Comment by trjExpensify** [comment]
QA issue created, paid @fedirjh for the C+ review. Closing!
