### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Tooltip content only have comma in content when hovering group chat with non-register users

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new group chat with non-register users
2. Go to Search page, search the group and hover the subscript avatar of the group chat.
3. Observer the tooltip content.
## Expected Result: 
Tooltip content should have the user email.
## Actual Result: 
Tooltip content only have comma

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e6b155ab-6993-4ae4-a6db-e9cccfd35d7a

https://github.com/Expensify/App/assets/43996225/a9e1d053-4252-4df5-9025-31a980528aa7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688794537559139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f7d4bfbb8b38ac0</li>
        <li>Upwork Job ID: 1678800589651423232</li>
        2023-07-11<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 25797512</li>
<li>hungvu193 | Reporter | 25797513</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
This only happens when the group chat users have not yet validated their Expensify accounts, we should still fix this though.

**Comment by syedsaqib12** [comment]
Please re-state the problem that we are trying to solve in this issue.
Tooltips is not working properly.


What changes do you think we should make in order to solve the problem?
We need to remove tooltip.

**Comment by rushatgabhane** [comment]
reviewing today

**Comment by sakluger** [comment]
I reopened that GH issue and left a comment to try to figure out which way to go from here. Basically, we modified `getOptions` to only use personal details that have logins set because it was breaking certain flows otherwise.

The two options I can think of are to either remove the extra commas, or try to figure out some other way display the email addresses of the unregistered users. I think we'll probably end up removing the extra commas, but let's wait to see until I get an answer.

**Comment by jasperhuangg** [comment]
Not sure if we should get rid of that filter right now. If we do it'll break a whole bunch of other important functionality.

We haven't entirely decided what we want to do yet about that, we should probably have a discussion about this change, and HOLD this issue on that for the time being.

**Comment by jasperhuangg** [comment]
A lot of our Tasks and IOU functionality was written under the assumption that the personalDetails you could look up in their options list always contained logins.

But as a result of a different security project for a conference, we sometimes don't send logins back anymore with certain personal details. As a result, a lot of the options list used in Tasks and IOUs were crashing the app, so we added this filter as a temporary fix, while we sorted out how we were going to rewrite a lot of this functionality to rely on accountIDs (which are always sent back with personalDetails) instead of logins.

**Comment by sakluger** [comment]
@jasperhuangg remind me what exactly this issue is holding on?

**Comment by sakluger** [comment]
@jasperhuangg friendly bump - which issue are we holding this one for again?

**Comment by sakluger** [comment]
Checked in with Jasper via DM.

**Comment by jasperhuangg** [comment]
@sakluger we added the filter where we don't include personalDetails that don't have logins as a temporary fix, and we don't want to remove it now for everything.

Reading through the proposals I think @hoangzinh's proposal [here](https://github.com/Expensify/App/issues/22593#issuecomment-1631636779) makes sense. We'll need to make sure we test it against all the possible OptionsLists to ensure that nothing crashes, but in theory it should work fine.

**Comment by Beamanator** [comment]
This issue is on hold?

@jasperhuangg do you want to take over since you reviewed proposals?

**Comment by rushatgabhane** [comment]
@Beamanator i think we forgot to remove hold from this issue

**Comment by rushatgabhane** [comment]
I think we can lift hold and move forward

**Comment by jasperhuangg** [comment]
HOLD removed, thanks for keeping things moving!

**Comment by jasperhuangg** [comment]
@Beamanator I can take over here, sorry for the delay

**Comment by jasperhuangg** [comment]
@hoangzinh looking forward to reviewing your PR!

**Comment by sakluger** [comment]
I went ahead and paid out the reporter bounty to @hungvu193

@rushatgabhane could you please complete the BZ checklist by tomorrow? That way we can approve your manual payment right away after the 7-day hold.

**Comment by sakluger** [comment]
I checked with @JmillsExpensify and I'm good to close any issue that is only pending the manual request payment, since he sees all payment requests directly in NewDot.

**Comment by JmillsExpensify** [comment]
Can I get a payment summary with amount so that I can pay @rushatgabhane?

**Comment by sakluger** [comment]
@JmillsExpensify here you go!

**Summarizing payouts for this issue:**

Bug reporter: @hungvu193 $250 (paid via Upwork)
Contributor: @hoangzinh $1000 (paid via Upwork)
Contributor+: @rushatgabhane $1000 (Manual Request)

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @rushatgabhane based on summary.
