### ISSUE TITLE
[$1000] Web - Chat - A remote member from the workspace can be tagged in the compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22596]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Login any gmail account
3. Click on "Configuración"(Settings)
4. Click on "Espacios de trabajo"(Workspaces)
5. Select any workspace
6. Click on "Miembros"(members) tab
7. Click on the field and paste the email adress
8. Click on "Invitar"(Invite) button
9. Click on the field and paste the email adress
10. Click on the checkbox
11. Click on "Siguiente"(Next)
12. Click on "Invitar"(Invite) button
13. Choose the member you recent add
14. Click on "Eliminar"(Remove) button
15. Click on the "Announce" chat of that Workspace
16. Write a "@" to tag a member in the compose box

## Expected Result:
Only the current member could be tagged in the chat. This chat is for share information about the workspace

## Actual Result:
You can tag and talk to a removed member in this chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/940c963b-8151-4ea8-962f-e081b181a1f9

![Bug6119818_invalmm](https://github.com/Expensify/App/assets/78819774/7fca711b-df22-43e5-8b23-685ab48c216d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d034906d542fc4f</li>
        <li>Upwork Job ID: 1679471005606608896</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by Muhammad-Bilal-7896** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
The member name is shown even after removal from the member list. When mentionining any member this member should not be shown.
> 
> ### What is the root cause of that problem?
The Root Cause is that the backend is not updating the @ mentions list that is coming from personal details API. 

```jsx
 personalDetails: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
 },
 
 src/pages/home/report/ReportActionCompose.js At this path
```

This is the file code where the data for suggestions for mentions is coming and it is not fetching the correct data i.e this list is not being updated after the removal of member.
```jsx
getMentionOptions(personalDetails, searchValue = '') {
        const suggestions = [];

        if (CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT.includes(searchValue.toLowerCase())) {
            suggestions.push({
                text: CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT,
                alternateText: this.props.translate('mentionSuggestions.hereAlternateText'),
                icons: [
                    {
                        source: Expensicons.Megaphone,
                        type: 'avatar',
                    },
                ],
            });
        }

        console.log('suggestions', suggestions);

        const filteredPersonalDetails = _.filter(_.values(personalDetails), (detail) => {
            // If we don't have user's primary login, that member is not known to the current user and hence we do not allow them to be mentioned
            if (!detail.login) {
                return false;
            }
            if (searchValue && !`${detail.displayName} ${detail.login}`.toLowerCase().includes(searchValue.toLowerCase())) {
                return false;
            }
            return true;
        });

        const sortedPersonalDetails = _.sortBy(filteredPersonalDetails, (detail) => detail.displayName || detail.login);
        _.each(_.first(sortedPersonalDetails, CONST.AUTO_COMPLETE_SUGGESTER.MAX_AMOUNT_OF_ITEMS - suggestions.length), (detail) => {
            suggestions.push({
                text: detail.displayName,
                alternateText: detail.login,
                icons: [
                    {
                        name: detail.login,
                        source: detail.avatar,
                        type: 'avatar',
                    },
                ],
            });
        });

        return suggestions;
    }
```

In the remove users function at this file path src/pages/workspace/WorkspaceMembersPage.js

```jsx
const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

So basically the line `Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);` is updating the code for the members list in the WorkspaceMembersPage component but is not updating the Personal Details List

> 
> When a member is removed from workspace it does not have any impact in suggestions lsit (personal details object)
> 
> ### What changes do you think we should make in order to solve the problem?
In order to fix this issue the best one is to compose the mentions list from the workspace Members List. 
That is the file **ReportActionCompose** at src/pages/home/report/ReportActionCompose.js will need a change to take the members list from the workspace list.

> ### What alternative solutions did you explore? (Optional)
> I have fetched the members list and then compared the suggestion list for mentions with that one and removed the members that are not present in the members list. 

I have also solved this using hard code solution where i have used react native async storage to save the removed members like here
```js
  const storeData = async (key,value) => {
        try {
             const jsonValue = JSON.stringify(value);
            await AsyncStorage.setItem(key, jsonValue);
        } catch (e) {
            // saving error
        }
    };

    const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

And then filtering the current suggestion list and removing the removed members list members. Basically this is a bad solution but this was the first i tried and this is not the one i will use. 

## Solution I will use
> I will use the workspace data members list instead of the people list used in the suggestions. 
OR
> I will implement comparing the suggestion list with the memberlist workspace members data and will remove all that are not part of the workspace array data.

**Comment by mudassar69** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
The member name is shown even after removal from the member list. When mentionining any member this member should not be shown.
> 
> ### What is the root cause of that problem?
The Root Cause is that the backend is not updating the @ mentions list that is coming from personal details API. 

```jsx
 personalDetails: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
 },
 
 src/pages/home/report/ReportActionCompose.js At this path
```

This is the file code where the data for suggestions for mentions is coming and it is not fetching the correct data i.e this list is not being updated after the removal of member.
```jsx
getMentionOptions(personalDetails, searchValue = '') {
        const suggestions = [];

        if (CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT.includes(searchValue.toLowerCase())) {
            suggestions.push({
                text: CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT,
                alternateText: this.props.translate('mentionSuggestions.hereAlternateText'),
                icons: [
                    {
                        source: Expensicons.Megaphone,
                        type: 'avatar',
                    },
                ],
            });
        }

        console.log('suggestions', suggestions);

        const filteredPersonalDetails = _.filter(_.values(personalDetails), (detail) => {
            // If we don't have user's primary login, that member is not known to the current user and hence we do not allow them to be mentioned
            if (!detail.login) {
                return false;
            }
            if (searchValue && !`${detail.displayName} ${detail.login}`.toLowerCase().includes(searchValue.toLowerCase())) {
                return false;
            }
            return true;
        });

        const sortedPersonalDetails = _.sortBy(filteredPersonalDetails, (detail) => detail.displayName || detail.login);
        _.each(_.first(sortedPersonalDetails, CONST.AUTO_COMPLETE_SUGGESTER.MAX_AMOUNT_OF_ITEMS - suggestions.length), (detail) => {
            suggestions.push({
                text: detail.displayName,
                alternateText: detail.login,
                icons: [
                    {
                        name: detail.login,
                        source: detail.avatar,
                        type: 'avatar',
                    },
                ],
            });
        });

        return suggestions;
    }
```

In the remove users function at this file path src/pages/workspace/WorkspaceMembersPage.js

```jsx
const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

So basically the line `Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);` is updating the code for the members list in the WorkspaceMembersPage component but is not updating the Personal Details List

> 
> When a member is removed from workspace it does not have any impact in suggestions lsit (personal details object)
> 
> ### What changes do you think we should make in order to solve the problem?
In order to fix this issue the best one is to compose the mentions list from the workspace Members List. 
That is the file **ReportActionCompose** at src/pages/home/report/ReportActionCompose.js will need a change to take the members list from the workspace list.

> ### What alternative solutions did you explore? (Optional)
> I have fetched the members list and then compared the suggestion list for mentions with that one and removed the members that are not present in the members list. 

I have also solved this using hard code solution where i have used react native async storage to save the removed members like here
```js
  const storeData = async (key,value) => {
        try {
             const jsonValue = JSON.stringify(value);
            await AsyncStorage.setItem(key, jsonValue);
        } catch (e) {
            // saving error
        }
    };

    const removeUsers = () => {
        if (!_.isEmpty(errors)) {
            return;
        }

        const selectedUserNames = selectedEmployees.map((accountID) => {
            const member = props.personalDetails[accountID];
            return member ? member.login || member.displayName : '';
        });

        console.log('Selected Users to be Removed:', selectedUserNames);

        // Store the selected users in AsyncStorage
        storeData("removedMembersList",selectedUserNames);

        // Remove the admin from the list
        const accountIDsToRemove = _.without(selectedEmployees, props.session.accountID);

        Policy.removeMembers(accountIDsToRemove, props.route.params.policyID);
        setSelectedEmployees([]);
        setRemoveMembersConfirmModalVisible(false);
    };
```

And then filtering the current suggestion list and removing the removed members list members. Basically this is a bad solution but this was the first i tried and this is not the one i will use. 

## Solution I will use
> I will use the workspace data members list instead of the people list used in the suggestions. 
OR
> I will implement comparing the suggestion list with the memberlist workspace members data and will remove all that are not part of the workspace array data.

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by Santhosh-Sellavel** [comment]
Already has proposal I might be not able to review this sooner so unassigning!

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
@aimane-chnaif to confirm, we're good to move forward here with this as a bug, or as a new feature? 🙇‍♂️

**Comment by dylanexpensify** [comment]
Perfect, @aimane-chnaif mind reviewing proposals today? 🙇‍♂️

**Comment by dylanexpensify** [comment]
bump @aimane-chnaif

**Comment by dylanexpensify** [comment]
@aimane-chnaif bump!

**Comment by dylanexpensify** [comment]
bumped in slack channel
