### ISSUE TITLE
Tooltip doesn't dismiss when not hover display name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go profile update long display name
2. Open a chat with new user
3. Chat any message
4. Click + in composer
5. Click the "Add attachment" button to make sure the click position is on the same level as the display name on the back
6. After clicking do not move the mouse to see the tooltip appear
7. Then move the mouse to see that the tooltip does not disappear
## Expected Result: 
Tooltip disappears after no more hover
## Actual Result: 
Tooltip doesn't dismiss when not hover display name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/920fca56-a4c2-41c6-bc0d-16ac64560cc3

Uploading Recording #238.mp4…

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689004369998349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
Ah thanks for the catch @hungvu193
