### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000]  Opening legal name from link and login does not display saved legal name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If legal name is not set then set legal name using any value and copy URL, URL should be: https://staging.new.expensify.com/settings/profile/personal-details/legal-name
3. Logout
4. Paste the URL copied in step 2 and then login
5. Observe that previously saved legal name is not displayed
## Expected Result: 
App should display previously saved legal name when we visit legal name page
## Actual Result: 
App does not display previously saved legal name when we visit legal name page by link and login

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/da294b1e-2d7a-4f21-890b-6b55cb5ec007

https://github.com/Expensify/App/assets/43996225/81599a83-c095-4b25-9543-b45cfdc8d3be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689008918453839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01baaf1e728dd0c132</li>
        <li>Upwork Job ID: 1679397167246221312</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Was able to repro this. So the difference is: 

 - When you're **logged in** and navigate to https://staging.new.expensify.com/settings/profile/personal-details/legal-name, the page displays whatever `Legal Name` you have set 
 - When you're **not logged in** and navigate to https://staging.new.expensify.com/settings/profile/personal-details/legal-name, the page displays `Legal first name` and `Legal last name`

**Comment by Santhosh-Sellavel** [comment]
@stephanieelliott This one is new and proposals are already there. I might not be able to look into this sooner, so please assign a new C+ here to take this forward. Thanks!

**Comment by cubuspl42** [comment]
@allroundexperts Wrong person, you meant @c3024

**Comment by dhanashree-sawant** [comment]
Hi @dangrous, no I have just got one offer from service account, all good for this bug.

**Comment by dangrous** [comment]
hi @allroundexperts! Let us know when you have a chance to review the [PR](https://github.com/Expensify/App/pull/22906) - thanks!

**Comment by dangrous** [comment]
Discussion continues on the PR

**Comment by dangrous** [comment]
Shush melvin, we just merged the PR!

**Comment by dangrous** [comment]
Looks good to me! about to chime in in Slack too - I think it would be worth having a checklist item saying something like "I verified that a direct deep link to the part of the App affected by my code change works as expected"

**Comment by stephanieelliott** [comment]
Regression test case issue here: https://github.com/Expensify/Expensify/issues/305639

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: @dhanashree-sawant $250 reporting bonus (paid via Upwork)
 - Contributor: @tienifr $1000 (paid via Upwork)
 - Contributor+: @allroundexperts $1000 (please request in newdot)
 
 Upwork job is [here](https://www.upwork.com/jobs/~01baaf1e728dd0c132), no speed bonus on this one

**Comment by JmillsExpensify** [comment]
Reviewed the payment details for @allroundexperts. This is approved for payment in NewDot.
