### ISSUE TITLE
No gap between IOU preview and user name & background color of preview matches the hover color of whole message.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22615]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Send a Money request in a DM with any user.
3. Observe the preview in the DM.
4. Hover your cursor over the whole preview message in the chat history.
## Expected Result: 
1. Background color of preview should be different from the hover background color of the whole message to make clear distinction between both. Same color hides the preview box.
2. There should be proper gap between the user name and money request preview.
## Actual Result: 
1. Preview has the same background color as the hover background color of the message.
2. Insufficient gap between the user name and request preview box.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (2)](https://github.com/Expensify/App/assets/43996225/47e7afb2-2169-46a2-9930-c37307fda08f)
![image (1)](https://github.com/Expensify/App/assets/43996225/8324c899-f172-4ebb-8951-9ea8c4f54d52)
<img width="953" alt="Screenshot (391)" src="https://github.com/Expensify/App/assets/43996225/025eb5a2-c9ab-4dcc-bc28-6a12c1528f4d">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689033849494849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
Also, I have already addressed the margin/gap issue in my proposal on that issue yesterday.

**Comment by lschurr** [comment]
It sounds like we can close this one for the other.

**Comment by Nikhil-Vats** [comment]
@parasharrajat I reported the bug along with the fix yesterday in my proposal. Since they were closely related, I didn't create a bug report and thought both of these issues can be fixed together.

But I agree, we should update the title and actual/expected outcome of https://github.com/Expensify/App/issues/22582 to reflect both of these.
