### ISSUE TITLE
[HOLD for payment 2023-07-21] Report Preview cards merge with the background when hovered over

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#22625]
**Problem**
Report previews merge with the background when hoverer over:
<img width="501" alt="Screenshot 2023-07-11 at 12 27 05 PM" src="https://github.com/Expensify/App/assets/19366280/a4f578ad-89cd-488d-af65-e0f13311cde4">

**Solution**

Have them look like iouPreviews:
<img width="585" alt="Screenshot 2023-07-11 at 12 27 12 PM" src="https://github.com/Expensify/App/assets/19366280/ef495573-61be-4773-b918-0a4e510b7699">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010af1f6e82f6cd735</li>
        <li>Upwork Job ID: 1678712759318437888</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Quick style change. No need for C+

**Comment by Gonals** [comment]
Seems like the PRs now always get a C+ assigned, so adding them here

**Comment by twisterdotcom** [comment]
@thesahindia - please just request payment on NewDot. Going to complete the checklist as this was internal.

**Comment by JmillsExpensify** [comment]
@Gonals Do you mind confirming how much @thesahindia should be paid for this issue? Ted is out on parental leave.

**Comment by Gonals** [comment]
> @Gonals Do you mind confirming how much @thesahindia should be paid for this issue? Ted is out on parental leave.

They reviewed the PR, so I guess that's $500, right?

**Comment by Gonals** [comment]
True. $1000 it is

**Comment by twisterdotcom** [comment]
@JmillsExpensify is there anything else I can do here? Or do we just need to approve this payment?

**Comment by twisterdotcom** [comment]
@JmillsExpensify I believe this is just waiting on some confirmation from you, after @Gonals provided the answer to your reopening query.

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/22625#issuecomment-1740286349).
