### ISSUE TITLE
[$2000] Desktop - User account gets switched while opening a link on desktop app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to NewDot as 'User 1' on browser
2. Sign in to Desktop app as 'User 2'
3. Click on a report or profile link from an external app like Slack or Notes
4. When bowser gives an option to open the link on Desktop app accept that

## Expected Result:
Link gets opened in desktop app. If the link is accessible to signed in user, navigate to the corresponding page. Otherwise show the not found error.

## Actual Result:
Link gets opened on Desktop app and the signed in user gets automatically switched to 'User 1', who was signed in on the browser.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2c9f2219-c54f-4229-9725-c31a3e99dd80

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689050512542529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afa755f6d218bd56</li>
        <li>Upwork Job ID: 1683560493408079872</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Whoops, sorry for the delay. I was able to reproduce this.

**Comment by ambagape** [comment]
Hi, 

This issue can be solved by using the Electron BrowserView. The link shall be displayed an appropriate component that listens to click events. Upon a click on the link, we shall load the page inside the BrowserView component, which is also an embedded browser for Electron apps.

Thank you.

**Comment by ambagape** [comment]
Contributor details
Your Expensify account email: ambagape@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/~0177a171786613c512?viewMode=1)

**Comment by puneetlath** [comment]
Still waiting on proposals.

**Comment by puneetlath** [comment]
Increased the bounty to try and get more proposals.

**Comment by puneetlath** [comment]
Actually, looks like we've decided in previous discussions that this isn't a bug: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1687552586606009
https://expensify.slack.com/archives/C01GTK53T8Q/p1687552578360189
