### ISSUE TITLE
[HOLD - #21977] Web - Users can download attachments when viewing attachment previews as anonymous users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22638]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout current user or open web app in private mode
2. Open any room as an anonymous user. SNH room for example: https://staging.new.expensify.com/r/5303403427249671
3. HOVER on any attached image in the chat room and click Download option on the context menu
Observer: User is UNABLE to download the image and re-directed to Login page
4. Open that room at step 2 again and CLICK on any attached image
5. Click download button on the Attachment preview
Observer: User is now ABLE to download the image -  this is opposite to the behavior at step 3

## Expected Result:
The behavior of the download attachment function should be consistent between the context menu and attachment preview.

## Actual Result:
Users are unable to download attachments from the context menu, but they are able to download them from the attachment preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c9539f1-3d4a-4e25-b0b3-0e14b01bf479

https://github.com/Expensify/App/assets/93399543/9dc2dc2e-11d8-4717-9365-d7940a2bbfcc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689053816447709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users can download attachments when viewing attachment previews as anonymous users.

### What is the root cause of that problem?
We always allow the user to download the attachment without checking whether or not the user is anonymous.
https://github.com/Expensify/App/blob/staging/src/components/AttachmentModal.js#L305

### What changes do you think we should make in order to solve the problem?
Add a function to check whether or not the user is anonymous:
 - If the user is anonymous: Re-direct user to Signin page
 - If the user is already logged in: Trigger desired action - which is to download the attachment

``` 
/**
     * Checks if user is anonymous. If true, hides the context menu and
     * shows the sign in modal. Else, executes the callback.
     *
     * @param {Function} callback
    */
    const interceptAnonymousUser = (callback) => {
        if (Session.isAnonymousUser()) {
            InteractionManager.runAfterInteractions(() => {
                Session.signOutAndRedirectToSignIn();
            });
        } else {
            callback();
        }
    };
```

Then use that function in onDownloadButtonPress event:
```
onDownloadButtonPress={() => interceptAnonymousUser(() => downloadAttachment(source))}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by PauloGasparSv** [comment]
Hey @alexpensify we are coming up [with a fix for this](https://github.com/Expensify/App/pull/22321#issuecomment-1630846046) in https://github.com/Expensify/App/issues/21977 so I think we can put this on HOLD for #21977.

**Comment by alexpensify** [comment]
Thank you @PauloGasparSv for that update! I've placed this one on hold.

**Comment by alexpensify** [comment]
Looks like the other PR is being reviewed, still on hold here.

**Comment by alexpensify** [comment]
@PauloGasparSv - I think this one is ready for another round of testing or should we close it because the other GH corrected it? Thank you!

**Comment by alexpensify** [comment]
@PauloGasparSv - I think you are back online from vacation. Could you review if we are cleared to close this one? Thanks!

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv - I think you are back online from vacation. Could you review if we are cleared to close this one? Thanks!

Sure thing @alexpensify, sorry for the delay here, I was stuck on some other reviews and issues : /
Checking this out right now!

**Comment by PauloGasparSv** [comment]
Our fix worked!!! @alexpensify we are cleared to close this (not sure if who reported should be compensated first so not closing this myself)

https://github.com/Expensify/App/assets/6564265/ab72ef78-47ff-4ece-a4a8-acc0906f4441

**Comment by alexpensify** [comment]
Thank you! All set, I'm going to close this one out. There is no payment here since it's related to a GH that was open before this one - https://github.com/Expensify/App/issues/21977.

**Comment by PauloGasparSv** [comment]
Thks @alexpensify, maybe this is eligible to compensation though:

We decided to fix this in https://github.com/Expensify/App/issues/21977 since it was also related to the anonymous user logic but this error wasn't reported and wouldn't have been fixed without this issue.

Since this is similar to https://github.com/Expensify/App/issues/22307 (that one is about the copy message button not working) which was also closed because of https://github.com/Expensify/App/issues/21977 and since it was also reported by @tranvantoan-qn I'm not sure if both issues are eligible for compensation though.

IMO since both reported issues are pretty similar we can compensate them once but I may be wrong!

**Comment by alexpensify** [comment]
After reviewing again, since there was a reporting bonus issued to @tranvantoan-qn here https://github.com/Expensify/App/issues/22307. Toan reported this one too but these three GHs are related to anonymous user logic. In this case, we should issue only one reporting bonus and there should have been one OP. I appreciate your understanding!
