### ISSUE TITLE
[$1000] Desktop - Opening deep link on desktop results in infinite spinner

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out of NewDot from browser
2. Sign out of Desktop app
3. Click on a report url or profile URL from an external app like Slack or Notes
4. Accept the browser dialog to open the link in Desktop app

## Expected Result:
Link gets opened in Desktop app. If user is signed out on desktop show sign in page. Otherwise navigate to the corresponding page.

## Actual Result:
Results in an infinite spinner.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/088fdd55-fe9b-4daa-8c0a-08b9e48450bd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689051035475369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d983a3d8e6001e1</li>
        <li>Upwork Job ID: 1678993627054243840</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by tjferriss** [comment]
Thanks for finding that one @hoangzinh
