### ISSUE TITLE
[HOLD for payment 2023-08-08] [Performance] Show cached onyx content right away

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#22644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

We are trying to make Onyx more performant by default. Right now, onyx always starts in a loading state, then collects all the
requested keys and sets them to the component state. This is often times inefficient as all the data is already available in a cache which we can read synchronously.

For exact technical details see: https://github.com/Expensify/react-native-onyx/issues/269

## What is the impact of this on end-users?

- Unnecessary loading states: We often start by default in a loading state, although we could show the content right away. Showing the content directly provides better UX
- Performance impacts due to a lot of re-renders: Due to this architecture a component re-renders a lot until it reached its final loaded state. This comes with a performance cost creating janky transitions to screens.

## List any benchmarks that show the severity of the issue

See: https://github.com/Expensify/react-native-onyx/issues/269

## Proposed solution (if any)

See: https://github.com/Expensify/react-native-onyx/issues/269

Once we have the onyx changes in place we need to update onyx in the app and adjust a few screens to work correctly. Some screens are build with the assumption that we will always start in a loading state.
We will start by adjusting the `ReportScreen`. The following adjustments need to be made ([as discussed here](https://expensify.slack.com/archives/C01GTK53T8Q/p1688580684466919)):

- Defer the loading of new chat messages to the next batch, so it doesn’t block the initial rendering by changing a state variable on the report.
- There was recently a `firstRenderRef` introduced, which delays the real rendering of the report screen after it has been mounted. We want to get rid of it to show the available content right away.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

See: https://github.com/Expensify/react-native-onyx/issues/269

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number: x**
**Reproducible in staging?: yes**
**Reproducible in production?: yes**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by: @hannojg **
**Slack conversation: https://expensify.slack.com/archives/C01GTK53T8Q/p1688580518417739**

**Comment by iwiznia** [comment]
@hannojg I assume you want this assigned to you since you'll be working on it, right?

**Comment by hannojg** [comment]
Yes, correct, thank you!

**Comment by hannojg** [comment]
The PR is ready for review:

- https://github.com/Expensify/react-native-onyx/pull/280

**Comment by hannojg** [comment]
This is on hold as the work and discussions are happening here:

https://github.com/Expensify/react-native-onyx/pull/280#issuecomment-1644245983

**Comment by mountiny** [comment]
This has been deployed to App @hannojg we still need to update the components to work correctly with the change right? Or can we close this?

**Comment by mountiny** [comment]
We need to pay $1000 to @mollfpr for their review and testing

**Comment by slafortune** [comment]
Offer sent @mollfpr https://www.upwork.com/nx/wm/offer/26071692

**Comment by slafortune** [comment]
Paid
