### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-21] [HOLD for payment 2023-07-20] Emoji - Frequently Used emojis display default skintone color instead of selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20828
## Action Performed:
1. Open NewDot
2. Open any chat
3. Open emoji picker
4. Select Non-default skintone
5. Select any emojis supporting skintone
6. Open emoji picker again

## Expected Result:
Frequently used emoji should be displayed with selected skintone

## Actual Result:
Frequently used emoji is displayed with default skintone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a55c01d9-e95c-43c7-abd1-e461f7529a52

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01531da77fbe1c9bc3</li>
        <li>Upwork Job ID: 1683864020992884736</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
This PR caused the regression https://github.com/Expensify/App/pull/20828

**Comment by francoisl** [comment]
The fix was CP'ed to staging and tested there, removing the DeployBlocker label and checking it off the checklist.

**Comment by bfitzexpensify** [comment]
Offer sent @0xmiroslav

**Comment by bfitzexpensify** [comment]
Still held on @0xmiroslav's payment particulars

**Comment by bfitzexpensify** [comment]
Still held

**Comment by stitesExpensify** [comment]
I don't think @0xmiroslav is still holding payment anymore
