### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] Text 'Hidden' in Details Page does not change language when updating language to Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click FAB button
2. Click New Group
3. Search and select new users not interact before
4. Create group
5. Click header of group, Observe the word 'Hidden' below the display name of previously selected non-interactive users
6. Update language to Spanish
7. Click header of group again, observed 'Hidden' untranslated

## Expected Result:
 'Hidden' is translated correctly

## Actual Result:
'Hidden' has not been translated yet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3ae05e30-ff20-4668-ae60-ba2fb28cc185

https://github.com/Expensify/App/assets/93399543/ed4c0cf5-9828-44d5-8106-ade833e58d3d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689071735934159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af2a152b7e858fa7</li>
        <li>Upwork Job ID: 1679134444061982720</li>
        2023-07-12<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>namhihi237 | Contributor | 25718816</li>
<li>namhihi237 | Reporter | 25718820</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
by: @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
'Hidden' is translated correctly
### What is the root cause of that problem?
We are hard coding the text 'Hidden' here `ReportParticipantsPage`:
https://github.com/Expensify/App/blob/38890e2e3c32b52dad11a7dfc09494924519946b/src/pages/ReportParticipantsPage.js#L61-L62
Also, we have the same here:
https://github.com/Expensify/App/blob/e5b7e3a767fcf70498c894c9e5f0f4d190e91fb0/src/libs/PersonalDetailsUtils.js#L23
### What changes do you think we should make in order to solve the problem?
Use translate for them:
```javascript
const getAllParticipants = (report, personalDetails, translate) => {
    const {participantAccountIDs} = report;
    return _.chain(participantAccountIDs)
        .map((accountID, index) => {
            const userPersonalDetail = lodashGet(personalDetails, accountID, {displayName: personalDetails.displayName || translate('common.hidden'), avatar: ''});
            const userLogin = Str.removeSMSDomain(userPersonalDetail.login || '') || translate('common.hidden');
```
In `ReportParticipantsPage`:
```javascript
return displayName || defaultValue || Localize.translateLocal('common.hidden');
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text 'Hidden' is not translated when language is updated.

### What is the root cause of that problem?

The text 'Hidden' is hardcoded at various places in the codebase.

### What changes do you think we should make in order to solve the problem?

Localization key `'common.hidden'` should be used at these places.

### What alternative solutions did you explore? (Optional)
None

**Comment by NicMendonca** [comment]
@sobitneupane can you please review these proposals 🙏 seems like a simple change that we can implement asap

**Comment by sobitneupane** [comment]
Thanks for the proposal @namhihi237.

First things first, why are we showing Hidden instead of email. I believe the issue here is not showing email.

**Comment by sobitneupane** [comment]
Thanks @namhihi237. I have started a discussion on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689331711275839) to confirm if it is expected to show "Hidden".

**Comment by sobitneupane** [comment]
It turns out that it is expected to show "Hidden".

[Proposal](https://github.com/Expensify/App/issues/22659#issuecomment-1631256833) by @namhihi237 looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by NicMendonca** [comment]
@chiragsalian all good to assign here?

**Comment by sobitneupane** [comment]
Waiting @chiragsalian to review https://github.com/Expensify/App/issues/22659#issuecomment-1635705902

**Comment by NicMendonca** [comment]
Chirag is away, so re-assigning

**Comment by NicMendonca** [comment]
- reporter: @namhihi237 $250
- contributor: @namhihi237 $1500
- C+: @sobitneupane $1500

**Comment by NicMendonca** [comment]
@sobitneupane bump on the [BZ checklist,](https://github.com/Expensify/App/issues/22659#issuecomment-1654609639) and don't forget to request payment in Expensify!

**Comment by NicMendonca** [comment]
@namhihi237 you've been paid! 🎉

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20328
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/20328#issuecomment-1670690894
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It should have been caught in PR review.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

I don't think specific regression test is required for the issue as it should be covered by language translation tests.

**Comment by NicMendonca** [comment]
Thank you!! 

Payment summary: https://github.com/Expensify/App/issues/22659#issuecomment-1664726391

**Comment by JmillsExpensify** [comment]
Reviewed the payment details for @sobitneupane. $1,500 is approved for payment in NewDot.
