### ISSUE TITLE
[HOLD #22451 ] [$1000] Web - User able to add or edit assignee even if task was completed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign a task
2. Enter title and assign it to a user
3. Click Confirm Task
4. Go to task report screen
5. Click on assignee and copy url from browser
6. Go back to task report screen and click on mark as done button
7. Paste the url in browser

## Expected Result:
User should not be able to select any assignee as task was completed

## Actual Result:
User able to  select assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0f9f934e-3a48-411d-9ddb-67e6ed187f43

https://github.com/Expensify/App/assets/93399543/3a8b98e1-9f9d-4202-a2e4-6b2a20911c43

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689050935277429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018342c30fcb07be10</li>
        <li>Upwork Job ID: 1679187285795405824</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by situchan** [comment]
I think this should be handled in https://github.com/Expensify/App/issues/22451

**Comment by kevinksullivan** [comment]
holding on https://github.com/Expensify/App/issues/22451 to see if this gets resolved.

**Comment by kevinksullivan** [comment]
Still on hold

**Comment by kevinksullivan** [comment]
On hold

**Comment by kevinksullivan** [comment]
held on https://github.com/Expensify/App/issues/22451

**Comment by kevinksullivan** [comment]
@kbecciv can you re-test this and confirm if it's still an issue?

**Comment by kbecciv** [comment]
Hmm... it's not here page displayed after pasted the URL

https://github.com/Expensify/App/assets/93399543/11290c3b-e2c4-4ccd-b54c-3651500ad935

**Comment by kevinksullivan** [comment]
Got it, going to close out then.
