### ISSUE TITLE
[HOLD for payment 2023-08-16][$1000] Attachment ValidationModal texts  are not translated to Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login in 2 tabs.
2. From the first tab, drag a large video into composer ( > 24MB), the ValidationModal will be showed.
3. From second tab, change language to Spanish.
4. Now go back to the first tab. Notice that ValidationModal 's texts are not translated to Spanish.

## Expected Result:
Modal text (title, prompt) should be translated to Spanish.

## Actual Result:
Modal texts (title, prompt)  aren't translated to Spanish.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/34563312-a72f-4361-b939-97db95296232

https://github.com/Expensify/App/assets/43996225/d2383a91-2f8a-482f-b5f9-4e8bbdff27b0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689006789754909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af42706e42700678</li>
        <li>Upwork Job ID: 1682145330266705920</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25841031</li>
<li>hungvu193 | Reporter | 25841033</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
by @hungvu193
### Please re-state the problem that we are trying to solve in this issue.
Attachment Validation Modal's texts are not translated to Spanish
### What is the root cause of that problem?
We're setting text as title and prompt for the ConfirmModal in here:
https://github.com/Expensify/App/blob/cc4969237677b68e3a569e07bada7fa475b7c33f/src/components/AttachmentModal.js#L184-L207
https://github.com/Expensify/App/blob/cc4969237677b68e3a569e07bada7fa475b7c33f/src/components/AttachmentModal.js#L352-L360
That's why when we changed the language, only Close button text was translated.
### What changes do you think we should make in order to solve the problem?
We should get rid of text, since it's required re-render to make it translated. We should use translate key instead.
So we need to update our `isValidFile` function to use translate key:
```javascript
            if (_.contains(CONST.API_ATTACHMENT_VALIDATIONS.UNALLOWED_EXTENSIONS, fileExtension.toLowerCase())) {
                const invalidReason = 'attachmentPicker.notAllowedExtension';
                setAttachmentInvalidReasonTitle('attachmentPicker.wrongFileType');
                setAttachmentInvalidReason(invalidReason);
                setIsAttachmentInvalid(true);
                return false;
            }

            if (lodashGet(_file, 'size', 0) > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
                setAttachmentInvalidReasonTitle('attachmentPicker.attachmentTooLarge');
                setAttachmentInvalidReason('attachmentPicker.sizeExceeded');
                setIsAttachmentInvalid(true);
                return false;
            }

            if (lodashGet(_file, 'size', 0) < CONST.API_ATTACHMENT_VALIDATIONS.MIN_SIZE) {
                setAttachmentInvalidReasonTitle('attachmentPicker.attachmentTooSmall');
                setAttachmentInvalidReason('attachmentPicker.sizeNotMet');
                setIsAttachmentInvalid(true);
                return false;
            }

```


And finally update the title and prompt to use `props.translate`
```javascript

            <ConfirmModal
               // we should use safe check here to prevent crash because of missing translate key
                title={!!attachmentInvalidReasonTitle ? props.translate(attachmentInvalidReasonTitle) : ''}
                onConfirm={closeConfirmModal}
                onCancel={closeConfirmModal}
                isVisible={isAttachmentInvalid}
                prompt={!!attachmentInvalidReason ? props.translate(attachmentInvalidReason) : ''}
                confirmText={props.translate('common.close')}
                shouldShowCancelButton={false}
            />
```

### What alternative solutions did you explore? (Optional)
N/A

### Result

https://github.com/Expensify/App/assets/16502320/87023509-4e7a-490a-8bd2-49bee6085eb1

**Comment by adelekennedy** [comment]
posted in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1689006789754909) I don't see this as a user problem, it's edge case behavior

**Comment by adelekennedy** [comment]
hmm @hungvu193 it sounds like this is something you think we should fix overall that's leading to related bugs (these are all very edge case behaviors - but I can see an argument for opening one issue to fix them all)

**Comment by adelekennedy** [comment]
Okay! Let's keep this open and close the issues that are coming back to the same root issue

**Comment by adelekennedy** [comment]
not overdue melvin

**Comment by Santhosh-Sellavel** [comment]
@hungvu193 Any Idea where was this broken?

**Comment by Santhosh-Sellavel** [comment]
@hungvu193 By where I mean, in which this got introduced?

**Comment by Santhosh-Sellavel** [comment]
Thanks @hungvu193!

@hungvu193's [proposal](https://github.com/Expensify/App/issues/22665#issuecomment-1643628510) looks good to me

We could use Boolean(attachmentInvalidReasonTitle) instead of !!

C+ Reviewed
🎀 👀 🎀

**Comment by adelekennedy** [comment]
@deetergp can we get a final review on @hungvu193 proposal?

**Comment by Santhosh-Sellavel** [comment]
bump @deetergp!

**Comment by Santhosh-Sellavel** [comment]
@adelekennedy If @deetergp's unavailable please a new CME here thanks!

**Comment by deetergp** [comment]
I'm back and will review this later today!

**Comment by deetergp** [comment]
@hungvu193's proposal sounds reasonable to me too, let's run with it!

**Comment by Santhosh-Sellavel** [comment]
@adelekennedy That makes sense, let's hold this for #23754

**Comment by deetergp** [comment]
I put a hold on this one pending the outcome of https://github.com/Expensify/App/pull/23754. I've also made it a weekly for now.

**Comment by Santhosh-Sellavel** [comment]
Thank you @deetergp!

**Comment by Santhosh-Sellavel** [comment]
@hungvu193 @deetergp 

https://github.com/Expensify/App/pull/23754 is off hold, we can resume the work here.

**Comment by Santhosh-Sellavel** [comment]
@adelekennedy or @deetergp remove the Hold from title thanks!

**Comment by deetergp** [comment]
@Santhosh-Sellavel Done!

**Comment by Santhosh-Sellavel** [comment]
This has been deployed to [production](https://github.com/Expensify/App/pull/24035#issuecomment-1670920772) 2 days ago. Please update labels @adelekennedy

**Comment by adelekennedy** [comment]
huh - annoying that it isn't updating automatically.

**Comment by adelekennedy** [comment]
### Payouts due:


Contributor: $1000 for issue fix, + reporting bonus ($250) @hungvu193 (paid via Upwork)
Contributor+: $1000 for issue fix @Santhosh-Sellavel  (paid via NewDot)

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/ab/applicants/1682145330266705920/hired).

**Comment by adelekennedy** [comment]
@Santhosh-Sellavel will you post the checklist?

**Comment by Santhosh-Sellavel** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/10118
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/10118/files#r1297612561
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A Should have been caught while testing
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A Just a translation
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A 
* [x]  [@adelekennedy ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,500 approved for payment via NewDot based on BZ summary.
