### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] mWeb - Next button is hidden behind the keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign task option
2. Click on title or description to open keyboard

## Expected Result:
Next button should _float_ to the top above the keyboard and not be hidden behind the keyboard

## Actual Result:
Next button is hidden and user have to close keyboard to click on Next button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b8bb7fde-3a8f-435e-a698-1572e95e50c8

https://github.com/Expensify/App/assets/93399543/5a156b48-c2a2-494c-b4eb-d215053d8b03

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689051900984439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156fee52bf18361b2</li>
        <li>Upwork Job ID: 1679934442140999680</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For mWeb task details page Next button isn't shown when keyboard opened

### What is the root cause of that problem?
We are not passing the `shouldEnableMaxHeight` to the `ScreenWrapper` here which won't adjust the maxHeight on updated `windowHeight`.
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/pages/tasks/NewTaskDetailsPage.js#L75-L78

### What changes do you think we should make in order to solve the problem?
Pass `shouldEnableMaxHeight` prop to the `ScreenWrapper` for `NewTaskPage` which will update the `maxHeight` based on the `windowHeight` which makes sure to show the button if the space is available for it.
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/pages/tasks/NewTaskDetailsPage.js#L75-L78
We can pass the `shouldEnableMaxHeight` prop to other pages as well.

**Comment by mallenexpensify** [comment]
Was able to reproduce, updated OP for the expected result to 
> Next button should _float_ to the top above the keyboard and not be hidden behind the keyboard

Example here

![IMG_9536](https://github.com/Expensify/App/assets/22508304/e8556918-b52b-4941-bf36-d7cf46fede7f)
![IMG_9535](https://github.com/Expensify/App/assets/22508304/53c09ec1-582b-462c-a74d-017918ca7f2e)

**Comment by s77rt** [comment]
@Pujan92 Thanks for the proposal. Your RCA is correct and the solution looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/22661#issuecomment-1631384298)

**Comment by mallenexpensify** [comment]
@Beamanator can you review @Pujan92 's proposal above plz?

**Comment by Beamanator** [comment]
@s77rt - the proposal looks great, and I think we should also check if there's other places we need to be adding that prop but aren't 👍

**Comment by Pujan92** [comment]
@s77rt @Beamanator [PR](https://github.com/Expensify/App/pull/23185) is ready for review!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/16443 and https://github.com/Expensify/App/pull/17940
- The offending PR has been commented on: https://github.com/Expensify/App/pull/16443#issuecomment-1650602866 and https://github.com/Expensify/App/pull/17940#discussion_r1274151064
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1690322590131429
- Determine if we should create a regression test for this bug: No

**Comment by mallenexpensify** [comment]
Issue reporter: @gadhiyamanan paid $250 via Upwork
Contributor: @Pujan92 paid $1500 via Upwork, including the urgency bonus
Contributor+: @s77rt paid $1500 via Upwork, including the urgency bonus.
