### ISSUE TITLE
Split bill success after back online with setting room as admins only

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 account with 2 browser
2. Account A create a WS and invite account B
3. 2 account go to announce room
4.  B force offline
5. A go room setting => set Admins only
6. B click + on composer => split bill => Next => Split
8. B online network (off force offline) , Observe that split bill success.
## Expected Result: 
Split bill failed and show error
## Actual Result: 
split bill success.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/505c897f-4381-4690-895e-bfe0fb3b515b

https://github.com/Expensify/App/assets/43996225/403ae59c-b28c-4436-a8ac-b2057c2995eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689011065028709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125ddf7eaa76f7b86</li>
        <li>Upwork Job ID: 1678834128803680256</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The split bill failed and show an error
### What is the root cause of that problem?
- When the user split bill when offline `optimisticData` is saved in Onyx with reportAction to create a task.
- And for now, API does not check error 403 like chat message and create a task when room setting admins only
### What changes do you think we should make in order to solve the problem?
I think the issue need fix first on Backend
- Check the room can access split bill when the room setting is admins only and return error.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by thienlnam** [comment]
Dang, forgot engineers adding the label doesn't auto-assign anyone. cc @anmurali Could you please add the label to auto-assign an engineer to this issue?

**Comment by thienlnam** [comment]
For the internal engineer assigned: We need to prevent split bill in the auth command from creating if they are not an admin on an admin-only report. We added the same check for creating a task [here](https://github.com/Expensify/Auth/blob/3f0aab168cd365befcc51dfad1c4fd24f3ba7695/auth/command/CreateTask.cpp#L110-L115)

**Comment by anmurali** [comment]
@thienlnam - When the offline user comes back online, the error is sent. Is this a bug? I am curious how the app would know, when offline that the room settings have changed! Isn't the design to send requests optimistically?

**Comment by thienlnam** [comment]
@anmurali If an error is sent and the request does not complete successfully then this is working as expected like you mentioned. From the issue description, it seems like it's possible to create the IOU while offline and have it succeed when then come back online. 

I haven't tested it yet so not sure what happens when you try this

**Comment by anmurali** [comment]
>it's possible to create the IOU while offline and have it succeed when then come back online.

@thienlnam - no, when I came back online it errored out. So I think this is working as expected

**Comment by thienlnam** [comment]
Oh nice, in that case - do we just need to add a nice error message on the front-end or are we good to close this?

**Comment by anmurali** [comment]
Unassigning myself and someone else can pick this up when I am OOO

**Comment by tjferriss** [comment]
I tested this issue and I didn't receive an error. It might be obvious, but the reason @namhihi237 expects the error is because user B first sets to admins only before the request while offline. Do I have this right?

**Comment by tjferriss** [comment]
>For the internal engineer assigned: We need to prevent split bill in the auth command from creating if they are not an admin on an admin-only report. We added the same check for creating a task [here](https://github.com/Expensify/Auth/blob/3f0aab168cd365befcc51dfad1c4fd24f3ba7695/auth/command/CreateTask.cpp#L110-L115)

Seems like this is the right solution. I'm going to add the `engineering` label so someone internal can take a further look.

**Comment by tjferriss** [comment]
@youssef-lr are you able to take a look at this one?

**Comment by tjferriss** [comment]
Bump @youssef-lr :)

**Comment by youssef-lr** [comment]
Hey! I can have a backend fix ready by EOW.

**Comment by tjferriss** [comment]
@youssef-lr do you expect you can get to this one this week? :)

**Comment by tjferriss** [comment]
@youssef-lr just bumping this one ahead of the weekend

**Comment by tjferriss** [comment]
@youssef-lr any update here?

**Comment by youssef-lr** [comment]
Working on a fix now @tjferriss so sorry for the delay! I've been heads down working on Wave7.

**Comment by tjferriss** [comment]
No problem @youssef-lr. Do you expect you can provide daily updates on the fix or should we move this to weekly so you can prioritize Wave7?

**Comment by tjferriss** [comment]
@youssef-lr bump on my question above :)

**Comment by youssef-lr** [comment]
@tjferriss I think this can be weekly! Currently focusing on making sure Wave7 works properly ahead of Launch, thank you!

**Comment by tjferriss** [comment]
@youssef-lr sounds like a plan, would still be good to get an update when you have the time.

**Comment by youssef-lr** [comment]
Started on the PR!

**Comment by tjferriss** [comment]
It looks like the PR is under review now.

**Comment by tjferriss** [comment]
PR is still under review.

**Comment by youssef-lr** [comment]
Sorry haven't been able to prioritize completing the PR yet, will get to this tomorrow.

**Comment by youssef-lr** [comment]
Resuming work on the PR today

**Comment by tjferriss** [comment]
@youssef-lr any updates on the PR?

**Comment by youssef-lr** [comment]
On it now @tjferriss

**Comment by youssef-lr** [comment]
PR updated

**Comment by tjferriss** [comment]
It looks like there are still some issues with the PR failing that are being worked through.

**Comment by youssef-lr** [comment]
@tjferriss I think we can issue payment for @namhihi237 and close this out!

**Comment by namhihi237** [comment]
FYI, this issue was created before we applied a new budget so this issue reporter should receive 250$, thank you.

**Comment by tjferriss** [comment]
Offer sent https://www.upwork.com/jobs/~019126f8aca61d10d7

**Comment by namhihi237** [comment]
Thanks accepted

**Comment by tjferriss** [comment]
The payment has been sent via Upworks.
