### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Inconsistency in the security page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > Two factor authentication
2. Observe that the next button is not highlighted or clickable unless you copy or download the codes
3. Go to settings > security > Change password
4. Observe that the save button is highlighted and clickable even though you didn't feed the necessary information and fix error option will show up.
5. Go to settings > security > Close account
6. Observe that the Confirm button is highlighted and clickable even though you didn't feed the necessary information and fix error option will show up.
## Expected Result:
 Button's should be clickable even though the necessary steps are not fulfilled and Fix error options should be shown up instead to keep the app consistency
## Actual Result: 
Button was not clickable when the necessary steps were not fulfilled and Fix error options was not shown
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5eee9283-ab25-46ae-8dbc-510d7bf08dfd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689037540044139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137dd1f2f9d3d3972</li>
        <li>Upwork Job ID: 1679119869039431680
<li>Last Price Increase: 2023-08-18</li></li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 25774623</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in the security page

### What is the root cause of that problem?
Some buttons should not be disabled from the start, but right now, they are.

### What changes do you think we should make in order to solve the problem?
We need to update `Two Factor Authentication Page` where the button starts *disabled*, as to be *enabled* & show the corresponding error if user presses on it without doing anything before. We also need to do this for any other places in which the button starts as *disabled*, but shouldn't(such as on the `Request Money Page`).

**Comment by shawnborton** [comment]
I think we already reported this and were chatting about it yesterday, does that sound right @MonilBhavsar ?

**Comment by Yokabdk** [comment]
@shawnborton yes you were discussing on this issue and it is the same report. 

@shawnborton to minimize duplication of efforts here is the discussion on the slack about this report 
![SC 01 on BR](https://github.com/Expensify/App/assets/137449048/e42897ca-15eb-476f-89c1-dd8d4e4f74e2)

![SC 02 on BR](https://github.com/Expensify/App/assets/137449048/54c8cdda-7baf-4227-b776-e1468d1eb395)

**Comment by CortneyOfstad** [comment]
@Yokabdk bump on the above ^^^ 

Please let us know once those details are added 👍

**Comment by Yokabdk** [comment]
Contributor details
Your Expensify account email: [Yokabdk@gmail.com](mailto:Yokabdk@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e63a00357238a4b6

**Comment by Yokabdk** [comment]
Contributor details
Your Expensify account email: [yokabdk@gmail.com](mailto:yokabdk@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e63a00357238a4b6

**Comment by CortneyOfstad** [comment]
@MonilBhavsar No worries! So in regards to this, where are we at? Are you looking to fix this, or are we holding this? Just checking to see what urgency this has moving forward 👍  TIA!

**Comment by MonilBhavsar** [comment]
Sorry, we can go ahead and fix this. In this [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1689037540044139) we all agreed that submit button should not be disabled as per our [guideline](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#submit-button-disabling), and if pressed without taking any action, it should display an error.

In this case, when pressing "Next" button without copying/downloading recovery codes, we should display an error

**Comment by DanutGavrus** [comment]
@thesahindia
> Waiting for a proposal that handles the expected result mentioned in the [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1689037540044139).

I think [this](https://github.com/Expensify/App/issues/22660#issuecomment-1631249312) follows the Slack thread. 

From Shawn on Slack thread:
> [...] we wouldn’t disable the button but we would return an error if the user pressed it and needed to do another action first.  

Proposal states that we should start with the button enabled instead of disabled in the Two Factor Authentication Page, and then show the corresponding error  if user tries to press on it before doing the required action.
> We need to update Two Factor Authentication Page where the button starts disabled, as to be **enabled** & *show the corresponding error if user presses on it without doing anything before*.  

From Shawn on Slack thread:
> we should fix that in the request money flow too, right now it starts off with a disabled next button  

Proposal also covers that:
> We also need to do this for any other places in which the button starts as disabled, but shouldn't(such as on the **Request Money Page**).

Am I missing something? 😁

**Comment by tgolen** [comment]
👍 on that proposal. Assigning the issue

**Comment by shawnborton** [comment]
FYI typically design doesn't approve the Spanish translation copy. I think that would be something that @laurenreidexpensify would take care of?

**Comment by laurenreidexpensify** [comment]
Copy is fine, checking translations [here](https://expensify.slack.com/archives/C21FRDWCV/p1690818926946699) internally

**Comment by laurenreidexpensify** [comment]
Sorry for the hold up here everyone! I got the translations almost immediately h/t @marcochavezf but forgot to paste them here 🤦‍♀️ and then when @thesahindia bumped me I pasted them on the wrong GH issue (https://github.com/Expensify/App/issues/22335) 🤦‍♀️ 🤦‍♀️ 

Here are the translations - 

> Please copy or download codes before continuing

`Copia o descarga los códigos antes de continuar`

> Please enter a valid amount before continuing.

`Por favor ingresa un monto válido antes de continuar`

**Comment by CortneyOfstad** [comment]
Thanks for the info @dukenv0307 — getting someone on it now!

**Comment by CortneyOfstad** [comment]
Going to keep the urgency as Daily for now 👍

**Comment by studentofcoding** [comment]
Is it opened for External contributor? @CortneyOfstad

**Comment by laurenreidexpensify** [comment]
Please add me back if you need any further details re: the translations and copy

**Comment by CortneyOfstad** [comment]
@Ollyws any updates on this?

**Comment by CortneyOfstad** [comment]
@Ollyws Just checking to see where we're at with this? TIA!

**Comment by CortneyOfstad** [comment]
Just checking to see where we're at with this — TIA!

**Comment by CortneyOfstad** [comment]
Thanks @Ollyws!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
@dukenv0307 — you have been paid in Upwork, so you are all set!

@Ollyws and @Yokabdk — I sent you both offers in Upwork. Please let me know once you accept!

**Comment by CortneyOfstad** [comment]
@Yokabdk Just waiting on your offer acceptance — thank you!

@shawnborton @tgolen thoughts on the regression test [here](https://github.com/Expensify/App/issues/22660#issuecomment-1744497558)? TIA!

**Comment by tgolen** [comment]
They look good to me!

**Comment by Yokabdk** [comment]
@CortneyOfstad offer accepted

**Comment by CortneyOfstad** [comment]
Thank you @Yokabdk! I've gone ahead and gotten that paid!

I'm creating the regression test now and then we're good to close!
