### ISSUE TITLE
Secondary login - Wrong email title is received when requesting code for the 2nd time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to account settings > Profile
2. Click on "Contact Method"
3. Verify the main contact method is the user email
4. Click on "New Contact method"
5. Add a new email
6. Click on the unverified email
7. Click on "Resend Magic code"
8. Navigate to the email inbox of the new contact method
9. Verify there's an email to "Verify secondary email for Expensify"

## Expected Result:
"Verify secondary email for Expensify" to be received when requesting the code for the 2nd time

## Actual Result:
"Your magic sign-in for Expensify" email is received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1c5994e8-b706-4e47-a7a9-239d23c35e4b

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
I didn't have time to repro this yet, sorry, I will do it first thing Monday!

**Comment by zanyrenney** [comment]
I don't think this is a bug. 

The triggers are different which is why the email titles are different. 

In one, the workflow is add secondary email > get verification link for email 
In the second, the workflow is didn't get magic link (when using secondary login) > get magic code.

The copy in the email reflects the trigger for the user to receive the code.
