### ISSUE TITLE
Inconsistent bug: "Invite" button collapses keyboard instead of inviting selected member

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace ( should be have fresh user)
2. Click on members ( There should not be have any invited member)
3. Select any member
4. Click on invite button
## Expected Result: 
On click of invite button, there should be invites the members
## Actual Result: 
Sometimes on click of invite button dismiss the keyboard instead of inviting members

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/628c1abb-a290-48b0-be45-1011358be707

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689099616523039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I cannot reproduce this. I tried the invite step 6 times on the iOS app but it worked every time


https://github.com/Expensify/App/assets/17131195/a077527c-a8f9-46c9-989b-228cfb1a90a8

**Comment by niravkakadiya25** [comment]
@sonialiap have you logged with fresh user?
Please try with fresh user

**Comment by sonialiap** [comment]
Will give it a try

**Comment by niravkakadiya25** [comment]
https://github.com/Expensify/App/assets/100456857/32563b30-daf5-4e58-ac5b-7193f13d3f4d

**Comment by sonialiap** [comment]
Aha, so I think this might be a consistent bug when you try to invite someone who doesn't yet have an Expensify account. 

What I did:
1. I tried to invite existing users three times - worked every time
2. tried inviting email (let's call them A) that doesn't have an account - didn't work
3. tried inviting a different new email (B) - didn't work
4. tried inviting email A again - unsure if worked, A didn't appear in the list at this step but appeared in next step
5. tried inviting email that has an account - worked and A appeared in the list too


https://github.com/Expensify/App/assets/17131195/a67cfbe4-ae5e-446a-a7b1-831fe702bf87

**Comment by sonialiap** [comment]
@kavimuru could you try reproducing this issue with the following steps:

1. Log into your test account
2. Workspace > Members > Invite
3. Type in an email that is not yet associated with an Expensify account
4. Click Next > Invite

Expected result:
Invited email shows up in the members list

Actual result:
Invited email does not show up in the members list

**Comment by kavimuru** [comment]
@sonialiap I am still not able to reproduce.

https://github.com/Expensify/App/assets/43996225/5491063f-04a3-4a0c-97d1-d774d13f4c6d

**Comment by sonialiap** [comment]
Hmm I see the member shows up with a slight delay for you. I'm going to test again

**Comment by sonialiap** [comment]
The email showed up for me on this test. Maybe the user always gets invited but the delay in the email showing up varies? 🤔 

https://github.com/Expensify/App/assets/17131195/38b3dd56-6797-4d73-b466-6c3cc7993061

**Comment by sonialiap** [comment]
I tried testing this two more times and every time the email got added, it just took a moment to appear
