### ISSUE TITLE
Chat - Draft message isn't sync with secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with same account on two devices: Mac/Chrome and iOS App in my case
2. Draft a message in a conversation

## Expected Result:
Secondary device - Verify the pencil icon is displayed in LHN in the conversation
Secondary device - Verify the drafted message is displayed

## Actual Result:
Draft message isn't sync with secondary device. The pencil icon isn't display in LHN in the conversation. The drafted message isn't display

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9ad6ff17-aa1f-4630-85ad-9cba6826999e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
We didn't save draft data in the backend. This looks like a new feature

**Comment by stephanieelliott** [comment]
Yep, this was by design. It was raised a few months ago and discussed in Slack, we opted not to move forward with it: https://expensify.slack.com/archives/C049HHMV9SM/p1682611285926239
