### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Web - [Deleted message] shows even if there is no thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any message
3. Hover on that message and select reply in thread option which will redirect you to thread report screen
4. Go back to main report screen which will remove thread from LHN
5. Delete thar message

## Expected Result:
Should delete completely as there is no thread attached

## Actual Result:
[Deleted message] shows even if there is no thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c11d8c07-3b63-4483-8851-6947df1a3337

https://github.com/Expensify/App/assets/93399543/f89d2724-aa28-44fb-a520-fe32c9cb6122

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689076375456339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019dc97a0bc3822c9f</li>
        <li>Upwork Job ID: 1679007363269394432</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Repro'd:

https://github.com/Expensify/App/assets/59587260/4922bb86-e5c0-45a8-9614-0d5fc5574572

**Comment by dangrous** [comment]
Hi! You're right that the current code in my PR didn't YET fix this, but I just pushed a change that I believe should. I think it makes sense for me to grab this and just fix them both together, let me know if you disagree @fedirjh or @kadiealexander

**Comment by kadiealexander** [comment]
Go ahead @dangrous!!

**Comment by kadiealexander** [comment]
Sent offers to @fedirjh and @gadhiyamanan. 

@fedirjh, please don't forget about the checklist!

**Comment by gadhiyamanan** [comment]
@kadiealexander offer accepted, thanks!

**Comment by kadiealexander** [comment]
Paid @gadhiyamanan. @fedirjh please let us know when you expect to have the checklist completed, and I'll get you paid and close this out.

**Comment by kadiealexander** [comment]
Thanks for the honesty, @fedirjh!! Closing this one out.
