### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Date of birth - Year list is scrolled back to current selection when keyboard disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Personal details > Date of birth
3. Tap on the year to open year list
4. With the keyboard on, scroll up the list

## Expected Result:
When the keyboard disappears, the year list will stay at where it is scrolled up to

## Actual Result:
When the keyboard disappears, the year list is scrolled back to the current selection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7edc7582-0da7-49e6-bae0-0a020ca187e7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01570faed600b40bf8</li>
        <li>Upwork Job ID: 1679174470293659648</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Hi @fedirjh - could you review the proposal on this one?

**Comment by lanitochka17** [comment]
@allroundexperts yes, sure
sorry

**Comment by lschurr** [comment]
Summarizing payments for this issue:

- Contributor: @fedirjh $1500 (to be paid in Upwork)
- C+: @allroundexperts $1500 (please request via NewDot)

**Comment by lschurr** [comment]
@fedirjh @allroundexperts could you work on the checklist and determine if we need a new regression test?

**Comment by lschurr** [comment]
Oops! Updated the comment.

**Comment by lschurr** [comment]
Do we need a regression test @allroundexperts @fedirjh?

**Comment by lschurr** [comment]
Added the regression test request. Closing!

**Comment by JmillsExpensify** [comment]
Reviewed [details](https://github.com/Expensify/App/issues/22689#issuecomment-1658926949) for @allroundexperts. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
