### ISSUE TITLE
Help- Expensify chat playbook for conferences not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22369
## Action Performed:
1. Run the help site, navigate to the Playbooks hub

## Expected Result:
Content Expensify Chat Playbook for Conferences displayed in playbooks

## Actual Result:
Expensify Chat Playbook for Conferences not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7a5f8e59-21f4-48d7-a1b8-a59c8f835b44

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8e805eae7648820</li>
        <li>Upwork Job ID: 1679171488027467776</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Its still on staging..

**Comment by francoisl** [comment]
I think the help site is only testable from production. @MitchExpensify will take care of testing https://github.com/Expensify/App/pull/22369 after the next production deploy.

**Comment by MitchExpensify** [comment]
Thanks @francoisl !

**Comment by MitchExpensify** [comment]
article is live
