### ISSUE TITLE
Assign task - The word `title` is not translated into Spanish in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Change the language of the app to Spanish
4. Click on FAB button -> Create a new task

## Expected Result:
The word `title` is not translated into Spanish as `titulo`

## Actual Result:
The word `title` is not translated into Spanish in chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6124090_1107](https://github.com/Expensify/App/assets/78819774/656048fd-b740-4156-ac9f-f913250a364f)

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This is getting fixed in https://github.com/Expensify/App/pull/22586

**Comment by jasperhuangg** [comment]
known issue, got a fix for it [here](https://github.com/Expensify/App/pull/22586), @NikkiWines gonna close this out since we shouldn't really be blocking deploy on this anyways
