### ISSUE TITLE
Emoji - Emoji search results in English are displayed for account with Spanish language set

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20828
## Action Performed:
1. Open NewDot
2. Switch to Spanish in preferences
3. Open compose box of any chat
4. Type
 ![image](https://github.com/Expensify/App/assets/78819774/761dd6c6-f42c-46b1-811f-67522127d6f7)
## Expected Result:
No results should be displayed as search request is in English and account is in Spanish

## Actual Result:
Under Spanish language in preferences user can see both English and Spanish emoji search results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/47980014-462f-4208-8e92-132876edec85

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Don't think we need to block deploy on this, but definitely a good thing to fix moving forward. Going to remove the `DeployBlocker` label and apply the `Bug` label so this can get triaged.
