### ISSUE TITLE
Web - Starting a new call using google meet is not sending any notification to the other participant in the call

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the call icon on the chat
2. Choose google meeting
3. Check the chat on the other account

## Expected Result:
Expected to find the meeting link sent by default to the other participant in the chat

## Actual Result:
The meeting link is not sent to the other participants and there is no notification that the other person is calling or sent you a link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52757227-5347-4e73-82ac-370e086c3ae8

https://github.com/Expensify/App/assets/93399543/89046af4-3183-436c-a198-3991c1c87b58

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689086373932069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
This is not a bug, this is how the feature was designed.
