### ISSUE TITLE
mWeb - Characters length exceeds the max input length

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on your avatar
2. Click on profile option
3. Click on personal details
4. Click on home address
5. Click on Zip / Postcode
6. Enter more than 10 characters

## Expected Result:
Input should not allow the user to enter more than 10 characters

## Actual Result:
Input allows the user to enter more than 10 characters but it remove them after pressing space or next

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/86826510-13bd-4bb5-8d4f-ac178d535317

https://github.com/Expensify/App/assets/93399543/ac9a1f09-01ee-48a0-8511-4cb9b398381b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689085405429119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mejed-alkoutaini** [comment]
@chiragxarora I believe this bug needs a physical device to reproduce

**Comment by twisterdotcom** [comment]
I also cannot recreate on a physical device. Could you upload another recording showing the latest version and confirm your android version too @mejed-alkoutaini?

**Comment by mejed-alkoutaini** [comment]
@twisterdotcom on another android device 

https://github.com/Expensify/App/assets/79811973/a05a635a-50f2-4e35-a159-5298d3bb967e
