### ISSUE TITLE
 Task - Button does not changes to "Mark as incomplete" when check to complete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22694]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20841
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to + > Assign task & finish the flow for creating the task
3. Click on the title item & change the title to be a really long name
4. Click on the description item & change the title to be a really long name
5. Assign the task to a person with existing chat
6. Click on "Confirm task" button
7. Click the checkmark to complete the task

## Expected Result:
After clicking the checkmark to complete the task - the text in the button above should change to "Mark as incomplete" & when uncheck the checkmark the text in the button above should change to "Mark as done"

## Actual Result:
The text in the button does not change to "Mark as incomplete"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/92d07c3c-0027-41f4-90d8-7736cf268e92

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3

**Comment by francoisl** [comment]
@jasperhuangg is working on several improvements for tasks in https://github.com/Expensify/App/pull/22586, so maybe it's not worth blocking on this. That said, I can reproduce the issue even on the branch from 22586, so this could be something he didn't know about yet.

**Comment by thienlnam** [comment]
Moving the blocker label as it's not really a bug - this seems to expected. The mark as done button is removed after the task is complete
