### ISSUE TITLE
NEWDOT PAYMENT DUE [HOLD for payment 2023-08-17] Add an option for distance requests

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22698]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#bookmark=id.y3vemdts4yol).

**Comment by neil-marcellini** [comment]
I got a draft PR up which is branched off the changes in progress for Scan Receipt. I think I'm almost done with it, but I still need to create the empty optimistic transaction object and set it's ID on the IOU object.

**Comment by neil-marcellini** [comment]
PR is up for review, but held on the PR for scan receipt.

**Comment by neil-marcellini** [comment]
Under review, waiting for C+.

**Comment by neil-marcellini** [comment]
PR just merged!

**Comment by neil-marcellini** [comment]
Oooh let me assign someone who can handle payment.

**Comment by sophiepintoraetz** [comment]
Payouts due:


Contributor: $1000 @allroundexperts


Eligible for 50% #urgency bonus? N - this is a flat review

**Comment by sophiepintoraetz** [comment]
@JmillsExpensify - bump for the ND payment - @allroundexperts can you raise a request, please?

**Comment by JmillsExpensify** [comment]
Reviewed the details for @allroundexperts. $1,000 payment approved via NewDot based on BZ summary.
