### ISSUE TITLE
[Tracking] Dynamically Updating issues

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#22699]
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689052350119119?thread_ts=1687471385.852519&cid=C01GTK53T8Q)
@dhanashree-sawant put together a list of issues that are still open that have to do with the app dynamically updating. I'm going to put the below on hold pending this tracking issue.  (others that are already closed or actively being worked on can be viewed via the link above). 

These are the issues which we can combine and close if needed:
[Workspace custom room members list is not updated dynamically](https://github.com/Expensify/App/issues/20761) (aimane has some opinion so maybe you may need to discuss it once with him)
[Chat - Mention options are not updated dynamically for display name like we update reports](https://github.com/Expensify/App/issues/21816)
[Change in primary contact method is not displayed dynamically](https://github.com/Expensify/App/issues/21569) (already taken up as new feature)
- https://github.com/Expensify/App/issues/21059#issuecomment-1634505350
- https://github.com/Expensify/App/issues/20399 
- https://github.com/Expensify/App/issues/22368
- BUG: Members list isn't dynamically updated ( on addition) in rooms - [Slack link](https://expensify.slack.com/archives/C049HHMV9SM/p1693324979492769)
- https://github.com/Expensify/App/issues/30038

Please add more if found.  
I'm going to compensate @dhanashree-sawant the bug reporting bounty for gathering these issues and keeping tabs on any new ones.

**Comment by sophiepintoraetz** [comment]
Adding!
https://github.com/Expensify/App/issues/22368

**Comment by mallenexpensify** [comment]
Reopening, we likely want to address dynamic updating at some point.  And/or just keep adding examples here

**Comment by isabelastisser** [comment]
Adding to this tracking issue so we can fix this once this is prioritized.

[Timestamp on the message changes based on the new timezone after page reload. #36891
](https://github.com/Expensify/App/issues/36891)
