### ISSUE TITLE
[HOLD for payment 2023-12-06] [DISTANCE] [$500] HIGH: Automatically pan initial map based on current location

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22704]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.fbpvqcxfpb9s). I have pasted the plan below for external viewers so some of the links might not work. Also, please note that contrary to the original plan below, we have already implemented the "Use current location" button, so please try to reuse as much of that code as possible.

### Automatic user location access
The first time a user opens this page we will prompt them to enable location services and then show a map centered on their current location. We’re not going to get the location using the mapping libraries because rnmapbox/maps doesn’t provide a way to access the location permissions. For web, react-map-gl and the underlying Mapbox gl js library don’t provide a way to request the user’s location without forcing them to press a button.

To handle geolocation we will need to platform specific files because [react-native-geolocation](https://github.com/michalchudziak/react-native-geolocation) doesn’t support web. We will create a location folder with platform specific implementations for all the functions handling the user location. At the moment we only need getCurrentPosition.

On native at the top of the file we will set up the configuration via [Geolocation.setRNConfiguration](https://github.com/michalchudziak/react-native-geolocation#setrnconfiguration). In the config we’ll set skipPermissionRequests: false since we’ll be using this function to request permission, authorizationLevel: ‘whenInUse’ because we only need the location when the app is open, and locationProvider: ‘auto’.

getCurrentPosition(success, error, config) will call Geolocation.getCurrentPosition passing the callbacks config through. From the App side we’ll set up a default config with the timeout and the maximumAge set to one minute because it seems like a reasonable maximum time to wait for your location and it’s unlikely that a cached location will be out of date within one minute.

On web getCurrentPosition(success, error, config) will first check if navigator.geolocation exists. If not then we will call the error call back with a [GeolocationPositionError](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError) object with code 2, POSITION_UNAVAILABLE. Otherwise, we’ll call navigator.geolocation.getCurrentPosition passing through the params.

After calling getCurrentPosition  in the ExpensifyMap, in the success callback we will center the map on the user’s location. The error callback will do nothing for this location request, because if we fail to get the user’s location we’ll continue displaying the default map area of San Francisco. We can prompt the user to enable location permission when they ask for it more explicitly on the waypoint editor page.

On native to center the map we’ll use camera.flyTo([lon, lat]); on the [Camera](https://github.com/rnmapbox/maps/blob/main/docs/Camera.md) ref. The Camera component will be a child of the MapView as shown in [this example](https://github.com/rnmapbox/maps/blob/main/example/src/examples/Map/ShowMap.tsx).

On web we will call map.flyTo({center: [lon, lat]}); where the map comes from the [useMap](http://visgl.github.io/react-map-gl/docs/api-reference/use-map) hook.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6a985f453bad073</li>
        <li>Upwork Job ID: 1711808933186453504</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
On hold

**Comment by neil-marcellini** [comment]
Carlos is [focused on wave 3/4](https://expensify.slack.com/archives/C05DWUDHVK7/p1692658158166129?thread_ts=1692658057.934369&cid=C05DWUDHVK7) so we're going to look for another volunteer.

**Comment by thienlnam** [comment]
https://github.com/Expensify/react-native-x-geolocation/pull/8

Should be the last PR for everything to be needed for the App PR

**Comment by thienlnam** [comment]
App PR is in progress and tracked in a different issue - all is done here regarding the new library

**Comment by neil-marcellini** [comment]
I realized that we still haven't implemented this in App, so I'm reopening it and making it external. I'll paste the plan from the design doc into the issue description.

**Comment by neil-marcellini** [comment]
I'm re-opening this because I recently realized that this feature is currently not in the app.

**Comment by thienlnam** [comment]
Closing again as this is being worked on in https://github.com/Expensify/App/issues/25855

This issue was just for adding the methods required in react-native-x-geolocation

**Comment by stephanieelliott** [comment]
Still awaiting proposals!

**Comment by stephanieelliott** [comment]
Seems like the plan is already developed, we just need a hand in implementing it. Posted in #expensify-swm to see if we can get someone to pick this up.https://expensify.slack.com/archives/C04878MDF34/p1698267728113989

**Comment by MaciejSWM** [comment]
Hey! I'm Maciej Dobosz from Software Mansion and I'll be more than happy to help. I'll be switching to this task later today

**Comment by stephanieelliott** [comment]
Awesome, thanks @MaciejSWM! Will go ahead and assign you now.

**Comment by MaciejSWM** [comment]
Link to Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1698404342523299

**Comment by MaciejSWM** [comment]
Having some problems with map + mobile browsers. All the other platforms are working. I'm leaving this last piece for thursday.

**Comment by thienlnam** [comment]
@MaciejSWM Are you still running into issues with the mobile browsers?

**Comment by MaciejSWM** [comment]
@thienlnam I recorded the video for Android Chrome using physical device. I couldn't get the emulator to work - emulator was freezing both on main and on my branch, tried multiple different emulators and API versions.

Anyway, PR is now ready for review ✅

**Comment by stephanieelliott** [comment]
PR changes have been applied, just awaiting approving review.

**Comment by stephanieelliott** [comment]
PR was deployed to staging a few hours ago 🚀

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @MaciejSWM, no payment required
 - Contributor+: $500 - HOLD on BZ checklist, @mananjadhav can you please complete? 
 Upwork job is [here](ttps://www.upwork.com/jobs/~01b6a985f453bad073)

**Comment by mananjadhav** [comment]
@stephanieelliott This was more of a feature request than a bug. 

But I think we should add a regression test. The test steps from the PR are good to be added the regression tests.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.

**Comment by JmillsExpensify** [comment]
@mananjadhav can you please paste the regression/TestRail steps as a comment in this issue?

**Comment by thienlnam** [comment]
Pending regression steps from C+

**Comment by mananjadhav** [comment]
We have three scenarios for the regression test steps. @JmillsExpensify We can use the following scenarios to add to Testrail.

**Regression Test Steps**

**Location Permission is not set**
1. Have the location access reset before you access the app.
2. Login to the app
3. Click on FAB -> Request Money -> Distance.
4. Browser should ask if you want to grant location access. Map should stay in pending state until you choose something.
5. Grant the permission. Map should navigate straight to your current location within 1-2 seconds.
6. Repeat steps 1 to 4, but this time, block the location access. The map should redirect you to default San Francisco location.


**Location Permission is enabled**
1. Load the application with the location access enabled.
2. Start the request money flow by clicking `FAB -> Request Money -> Distance`.
3. It should take you directly to your current location.
4. Update the location in the Dev console by setting:
```
Onyx.set(ONYXKEYS.USER_LOCATION, { longitude: 12, latitude: 12 })
```
5. Repeat the steps 1 and 2. It should change the map location to your current location.
7. Repeat steps 4 and 5, and before it can change to your current location, drag the map. This should keep you at [12, 12] coords and should stop the map from auto-panning to your current location.

**Location Permission is disabled**
1. Load the application with the location access enabled.
2. Start the request money flow by clicking `FAB -> Request Money -> Distance`.
3. The map should redirect you to default San Francisco location.
4. Refresh the page. You should land straight in the San Francisco location.
5. Enable the location and refresh the page to cache the current location in ONYX. 
6. Then disable the location and refresh the page. 
7. You should land in this cached location instead of the default San Francisco location.

**Comment by stephanieelliott** [comment]
Thank you -- issue for regression test here: https://github.com/Expensify/Expensify/issues/349072
