### ISSUE TITLE
[HOLD for payment 2023-09-08] Use current location waypoint editor button

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22707]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.f54rb8cmd9f7).

**Comment by hayata-suenaga** [comment]
assigning myself to this issue and labeling the issue back to weekly

**Comment by tgolen** [comment]
This is off hold and I'm bumping up to daily

**Comment by hayata-suenaga** [comment]
Created an App issue for this: https://github.com/Expensify/App/issues/25855

**Comment by hayata-suenaga** [comment]
The location PR has been reverted and the original contributor that made the PR is working on the second PR that includes fixes for all regressions.

**Comment by hayata-suenaga** [comment]
Closing this issue because this is a dupe of [this issue](https://github.com/Expensify/App/issues/25855).
