### ISSUE TITLE
[HOLD for payment 2023-08-24] Implement a basic list for waypoints and the Add stop button

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22700]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#bookmark=id.lh62nhax46kk).

**Comment by neil-marcellini** [comment]
On HOLD, changing to a weekly while I wait.

**Comment by neil-marcellini** [comment]
On hold

**Comment by neil-marcellini** [comment]
I got started on the PR.

**Comment by neil-marcellini** [comment]
I made a lot of progress on this today and I think I finished the implementation. I'll work on putting it up for review next time.

**Comment by neil-marcellini** [comment]
On Friday I made some tweaks to the scrollable list so that waypoints would fade off the bottom properly when they are different sizes. That took a while. Today I think I can get it up for review.

**Comment by neil-marcellini** [comment]
I spent most of today struggling with running NewDot on the various platforms. It's been a while since I've used anything other than web, and most of the platforms do not work for me right now.

As soon as I get videos on Android, Android Chrome, and desktop I can put the PR up for review.

**Comment by Santhosh-Sellavel** [comment]
@neil-marcellini / @thienlnam Assign me this & also add a BZ when you get a chance thanks!

**Comment by Santhosh-Sellavel** [comment]
@NicMendonca We can skip the checklist as this is a feature, can you leave a payment summary, thanks!

**Comment by NicMendonca** [comment]
- reporter: n/a
- contributor: n/a
- contributor plus: @Santhosh-Sellavel - $1,000

@Santhosh-Sellavel thank you!

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,000 approved for payment in NewDot based on BZ summary.
