### ISSUE TITLE
[HOLD for payment 2023-08-30] [$1000] Create the waypoint editor page and handle the case without autocomplete

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22705]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.nw4ox4euydev).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ace68ebaf46acb9c</li>
        <li>Upwork Job ID: 1692243358570655744</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
On HOLD, changing to a weekly while I wait.

**Comment by neil-marcellini** [comment]
On hold

**Comment by neil-marcellini** [comment]
I'm taking this off hold because we've determined that #22704 is not a critical feature. I'll branch off of the PR #22700 so we'll need to wait for that to be deployed before this is. I plan to get started soon.

**Comment by thienlnam** [comment]
I just picked it up man!!

**Comment by Santhosh-Sellavel** [comment]
@thienlnam Assign me when you get a chance thanks!

**Comment by thienlnam** [comment]
PR just merged, (I handled it internally, and had @Santhosh-Sellavel be the C+ reviewer for the PR)

**Comment by stephanieelliott** [comment]
PR is still on staging, will update with payment date once it hits prod.

**Comment by stephanieelliott** [comment]
Merged to prod on Aug 23, updated payment date to reflect 7-day hold.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor: N/A [internal]
 - Contributor+: @Santhosh-Sellavel $1000, please request via newdot
 
 Upwork job is [here](https://www.upwork.com/ab/applicants/1692243358570655744/job-details), no bonus as this was an internal PR

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,000 payment approved via NewDot based on BZ summary.
