### ISSUE TITLE
Implement displaying a single waypoint

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22706]
Please follow the [plan in the design doc](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.377n4rp3mxa7).

**Comment by neil-marcellini** [comment]
On HOLD, changing to a weekly while I wait.

**Comment by neil-marcellini** [comment]
On hold

**Comment by neil-marcellini** [comment]
Still holding

**Comment by neil-marcellini** [comment]
Holding

**Comment by neil-marcellini** [comment]
Off hold now since Hayata got started

**Comment by hayata-suenaga** [comment]
hello @dannymcclain 👋 

We're working on a new project called "Distance Request" where users can request expenses they spend on gas to be reimbursed through NewDot. We display a map as part of this new feature to indicate the distance the user has driven.

We have design in [this Figma file](https://www.figma.com/file/eGNzYqjcy0HkmrCwE076XE/Distance-Requests-Doc?type=design&node-id=606-2801&mode=design&t=1dB7uBRE74XFhJPM-0). Could you work with @shawnborton to compare the screenshots/videos in [this Pull Request (actual code change)](https://github.com/Expensify/App/pull/25161#issue-1854256016) with the original design and confirm they look okay? 🙇

**Comment by shawnborton** [comment]
We're discussing some finishing touches [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1692583625196909) - looks like we might want to change the style of the markers, assuming that's cool for you all!

**Comment by hayata-suenaga** [comment]
> looks like we might want to change the style of the markers, assuming that's cool for you all!

of course! wow, all options discussed in the thread look good to me 😮

**Comment by hayata-suenaga** [comment]
No need for payment

**Comment by hayata-suenaga** [comment]
I think we can close this one now
