### ISSUE TITLE
[HOLD for payment 2023-09-04] Display a distance request route in App

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22708]
Please follow the plan in the design doc [Display a route](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.tii7s2q6x25e) in App
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c851643e48268ef0</li>
        <li>Upwork Job ID: 1705055119264399360</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
On hold

**Comment by neil-marcellini** [comment]
Still holding

**Comment by neil-marcellini** [comment]
Holding

**Comment by thienlnam** [comment]
Hopping on this from this thread https://expensify.slack.com/archives/C05DWUDHVK7/p1692212912617769?thread_ts=1692139470.932979&cid=C05DWUDHVK7

**Comment by neil-marcellini** [comment]
Off hold since you have started it

**Comment by thienlnam** [comment]
This PR is in review now

**Comment by neil-marcellini** [comment]
@tjferriss would you please handle payment for the C+ so we can close this. C+ hasn't been paid yet right @thienlnam?

**Comment by thienlnam** [comment]
Oh yeah wow - let's get @allroundexperts paid for this one

**Comment by thienlnam** [comment]
Add the internal label so we start the automations for the Upwork job

**Comment by thienlnam** [comment]
@trjExpensify Could you please pay @allroundexperts for a C+ review for this PR? This was before the price change so $1000 for a C+ review

**Comment by trjExpensify** [comment]
[This PR](https://github.com/Expensify/App/pull/25434) yeah?

**Comment by thienlnam** [comment]
Yeeee

**Comment by trjExpensify** [comment]
Cool, so we can close this out then!

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/22708#issuecomment-1730739143).
