### ISSUE TITLE
[HOLD for payment 2023-08-28] Handle distance requests on participants page

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22709]
Please follow the plan in the design doc: Handle distance requests on [participants](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.spw2kmciho05) page

**Comment by neil-marcellini** [comment]
I think we can take this off HOLD and make the change in parallel, before the rest of the flow is ready because it's quite a simple change.

**Comment by marcaaron** [comment]
I'll grab this one and help out with testing when it's ready.

**Comment by marcaaron** [comment]
I also don't see anything in the current code that has a `requestType` so I am thinking we can't really merge this until that exists.

**Comment by marcaaron** [comment]
Got a PR up for this. There's a few things we still need before it can be fully tested.

**Comment by marcaaron** [comment]
I'll take this PR out of draft today.

**Comment by marcaaron** [comment]
I think this can be closed now that it's on production. Not sure why the checklist appeared but it seems not needed.
