### ISSUE TITLE
[HOLD for payment 2023-09-07] Display recent destinations on waypoint editor

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22714]
Please follow the plan in the design doc: Display [recent destinations](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.3cl6mwvdx8xy) on waypoint editor.

**Comment by neil-marcellini** [comment]
This is going to come off hold pretty soon.

**Comment by tgolen** [comment]
I'll start work on this tomorrow.

**Comment by tgolen** [comment]
I have only preliminarily began looking into this and I've been focusing on other CRITICAL tasks. Once those are all done (hopefully today), I will be able to put all my focus into this. ETA is to have it done and ready for review by the end of tomorrow (Friday).

**Comment by tgolen** [comment]
This is all done and nothing else needs to be done
