### ISSUE TITLE
[HOLD for payment 2023-09-11]  Handle distance requests on the confirmation page

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22710]
Please follow the plan in the design doc: Handle distance requests on the [confirmation page](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.rodvrugt6k9i)

**Comment by neil-marcellini** [comment]
On HOLD, changing to a weekly while I wait.

**Comment by neil-marcellini** [comment]
On hold

**Comment by neil-marcellini** [comment]
Still holding

**Comment by neil-marcellini** [comment]
Holding

**Comment by hayata-suenaga** [comment]
[assigning myself per this discussion](https://expensify.slack.com/archives/C05DWUDHVK7/p1692658666442749?thread_ts=1692658057.934369&cid=C05DWUDHVK7)

**Comment by hayata-suenaga** [comment]
this doesn't need payment.

**Comment by situchan** [comment]
@hayata-suenaga I am eligible for internal PR review.

**Comment by hayata-suenaga** [comment]
@situchan completely forgot so sorry

opening for the payment

**Comment by mallenexpensify** [comment]
@situchan can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01d72c2733166be375

**Comment by mallenexpensify** [comment]
and.. another comment to remove `Overdue`

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by mallenexpensify** [comment]
Contributor+: @situchan paid $1000 via Upwork.
