### ISSUE TITLE
[HOLD for payment 2023-10-09] 🟡 Editing distance requests in App

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22715]
~- HELD on https://github.com/Expensify/App/issues/22713~

Please follow the plan in the design doc: [Edit in App](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.cqcm1mfn8c58).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e127650fd78aa6</li>
        <li>Upwork Job ID: 1712170898351742976</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
Held on creating requests. I'll drop this to weekly for the time being.

**Comment by arosiclair** [comment]
Still held

**Comment by arosiclair** [comment]
Still held

**Comment by tgolen** [comment]
Off HOLD

**Comment by jasperhuangg** [comment]
It seems the front-end for this needs the changes from https://github.com/Expensify/App/pull/25707 in order to be implemented

**Comment by jasperhuangg** [comment]
Having some local changes for this that I'm looking to submit for review today!

**Comment by tgolen** [comment]
Jasper requested someone to take this over so I am unassigning it and leaving it in the wave for someone to pick up.

**Comment by tgolen** [comment]
@trjExpensify Could you help me wrap up payment for this? I believe @fedirjh needs to be paid as a C+ for reviewing the PR.

**Comment by trjExpensify** [comment]
Paid, closing!
