### ISSUE TITLE
[HOLD for payment 2023-10-13] 🟡 Implement a DraggableList for waypoints

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22716]
Please follow the plan in the design doc: Implement a [DraggableList](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.acwxu2ur99m1) for waypoints.

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by hayata-suenaga** [comment]
not overdue just assigned myself

**Comment by hayata-suenaga** [comment]
This is on hold

**Comment by hayata-suenaga** [comment]
This is on hold and has less priority.

**Comment by hayata-suenaga** [comment]
The latest update here: https://expensify.slack.com/archives/C04878MDF34/p1692972677966979?thread_ts=1692752442.794829&cid=C04878MDF34

**Comment by hayata-suenaga** [comment]
the latest update here: https://github.com/Expensify/react-native-x-draggable-list/pull/7#issuecomment-1699342985

**Comment by hayata-suenaga** [comment]
Holding [the merge per this discussion](https://expensify.slack.com/archives/C05DWUDHVK7/p1693517519748659?thread_ts=1693516694.049269&cid=C05DWUDHVK7)

**Comment by hayata-suenaga** [comment]
I put HOLD to the second-attempt PR for the "Current Location" feature per [this Slack discussion](https://expensify.slack.com/archives/C05DWUDHVK7/p1693803299962189)

**Comment by hayata-suenaga** [comment]
[The latest discussion here](https://expensify.slack.com/archives/C04878MDF34/p1694508836106459?thread_ts=1692752442.794829&cid=C04878MDF34)

[We have a design decision to make](https://expensify.slack.com/archives/C05DWUDHVK7/p1694509495995009)

**Comment by hayata-suenaga** [comment]
There was a performance regression

**Comment by hayata-suenaga** [comment]
also, [this regression](https://expensify.slack.com/archives/C049HHMV9SM/p1696486346915669) was potentially caused from the PR.

**Comment by hayata-suenaga** [comment]
Payment summary.

@DylanDylann and @situchan reviewed [this PR](https://github.com/Expensify/App/pull/26307) by a SWM engineer.

**Comment by twisterdotcom** [comment]
Apologies folks, who should I be paying here and how much?

**Comment by hayata-suenaga** [comment]
@twisterdotcom both please. This was a big PR and needed several C+'s eyes

**Comment by DylanDylann** [comment]
@twisterdotcom @hayata-suenaga It seems we have a mistake here, I didn't review this PR so I am not eligible for payment here 😄

**Comment by situchan** [comment]
There was only 1 C+ review. Other than efforts, I think original base price (1k) applies here as PR was [raised](https://github.com/Expensify/App/pull/26307#issue-1873987231) 3 hrs before [announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649).

**Comment by twisterdotcom** [comment]
bump @hayata-suenaga.

**Comment by twisterdotcom** [comment]
Offer: https://www.upwork.com/nx/wm/offer/27434574

**Comment by twisterdotcom** [comment]
Paid $1000 to @situchan here: [upwork.com/nx/wm/offer/27434574](https://www.upwork.com/nx/wm/offer/27434574)
