### ISSUE TITLE
Offline support for CreateDistanceRequest

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#22718]
Please follow the plan in the design doc: [Offline support for CreateDistanceRequest](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#heading=h.6wi838fsinja).

**Comment by tgolen** [comment]
Off HOLD

**Comment by tgolen** [comment]
Closing this one in favor of https://github.com/Expensify/Expensify/issues/310081
