### ISSUE TITLE
Web - Duplicated emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22739]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Write ":Superhero" on the text writing bar
3. Observe the results 
Or
1. Go to any chat
2. Click the emoji button
3. Observe that there are two super woman emoji pictures

## Expected Result:
Emojis with different name should result different picture of emojis

## Actual Result:
There are two superwoman emojis with the name "superhero" and "superhero woman"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ef50c44b-80e4-4759-9b51-7cdf83ce59a3

https://github.com/Expensify/App/assets/93399543/dd967157-256c-4e01-9317-cca5194858c0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689108219619609
https://expensify.slack.com/archives/C049HHMV9SM/p1689108541301389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AdekolaThanni** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Superhero emoji duplicates

### What is the root cause of that problem?
This is caused by the duplication of the superhero woman emoji with the superhero emoji at this point in code.
https://github.com/Expensify/App/blob/29ae9421d61c5a05e12408c258f64d4b65c3c2c4/assets/emojis/common.js#L1618

### What changes do you think we should make in order to solve the problem?
This can be solved by deleting the superhero emoji object


### What alternative solutions did you explore? (Optional)
None

**Comment by tjferriss** [comment]
I can't reproduce. I see two distinct emojis for :superhero: and :superhero_woman:  

<img width="189" alt="Screenshot 2023-07-12 at 13 43 05" src="https://github.com/Expensify/App/assets/8292562/2276166e-40b0-4518-95e9-2114c9a1b284">


<img width="391" alt="Screenshot 2023-07-12 at 13 42 56" src="https://github.com/Expensify/App/assets/8292562/0fb1c273-79b4-47b3-b79c-61ac5fe59b71">

**Comment by AdekolaThanni** [comment]
@tjferriss, I think what the bug addresses is technically reflected in your test, the superhero and superhero_man emojis are duplicates. Unless that is the intention?

**Comment by tjferriss** [comment]
I see three distinct emojis.

<img width="563" alt="Screenshot 2023-07-12 at 14 18 56" src="https://github.com/Expensify/App/assets/8292562/5437e7bc-63f0-4117-9407-fb7766947bff">
