### ISSUE TITLE
Web - Unable to load newdot, keeps crashing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logged in, see refresh or logout screen
2. Click refresh, it shows the same page “refresh or logout”
3. Click refresh again, it still shows the same page
4. Click logout, successfully log back in and then it shows refresh/logout screen

## Expected Result:
Should load chats

## Actual Result:
Nothing loads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (24)](https://github.com/Expensify/App/assets/93399543/c764794e-9b5a-47cd-8588-965170873483)
![image (23)](https://github.com/Expensify/App/assets/93399543/ee4950af-5fc3-4b4e-853b-f529d1aa3551)
![image (22)](https://github.com/Expensify/App/assets/93399543/59ea8276-79c8-4e44-8b35-cfa4002a12c4)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Christina Draeger
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689106419837679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by multijump** [comment]
I couldn't reproduce this issue in v1.3.38-7.
