### ISSUE TITLE
Web - The Expand Button does not appear when editing a message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22744]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a message
3. Hover over the reaction menu and click on "edit Comment'
4. On the edit composer press Shift enter a couple of times.

## Expected Result:
The Expand Button appears

## Actual Result:
No expand button when editing messages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6e48ced0-fc6d-4427-9fcd-aa2044a4d9c4

https://github.com/Expensify/App/assets/93399543/f075ea13-1193-4b86-b5f4-acedab2f293f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689117452136389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I don't know that this is a bug, this feels more like a feature request. I feel like having the expand button in the edit view is ripe for more bugs because you can edit multiple messages at once. I would say we just close this.

**Comment by alexpensify** [comment]
I'm not sure why two from `Bug` were assigned here but I'm unassigning myself since I was the second person invited to the party.

**Comment by Nikhil-Vats** [comment]
I agree @shawnborton especially because the edit composer does expand when we add new lines or message length increases -

https://github.com/Expensify/App/assets/31413407/8ead86a9-e6a0-48ff-81df-e90896e4f766

**Comment by shawnborton** [comment]
Cool, let's close then.
