### ISSUE TITLE
[HOLD for payment - MIROSLAV ONLY] [$1000] Web -  Offline - Deleted workspace still shows in the create room dropdown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Force Offline mode
3. Go workspace detail of above workspace
4. Click three dot => Delete workspace
5. Click FAB button
6. Click New room, observe that the workspace just created above is still in the dropdown

## Expected Result:
Workspaces deleted when offline should not be displayed in the dropdown

## Actual Result:
Workspaces deleted when offline are still displayed in the dropdown and can be selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5e09d2c6-5267-4435-9eda-3cb965383aff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688782862280029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b5a6ced3dfb0dd7</li>
        <li>Upwork Job ID: 1679308786376093696</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Workspaces deleted when offline should not be displayed in the dropdown
### What is the root cause of that problem?
The reason is that after deleting the workspace in offline mode, it will update pendingAction = 'delete' in `optimisticData`.
But in the dropdown we have not filtered the workspaces with pendingAction = 'delete'
https://github.com/Expensify/App/blob/67e07f9e698f29b55d41fea72cca923035b36728/src/pages/workspace/WorkspaceNewRoomPage.js#L109-L117
### What changes do you think we should make in order to solve the problem?
We add the condition not to display the workspaces with pendingAction = 'delete'
```javascript
 _.filter(props.policies, (policy) => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE),
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment]
It's a new bug according to Joe: https://expensify.slack.com/archives/C049HHMV9SM/p1689167086002219?thread_ts=1688782862.280029&cid=C049HHMV9SM

**Comment by amyevans** [comment]
Agreed the generalized solution is best here, thanks all! Assigning @tienifr

**Comment by jliexpensify** [comment]
Payments:

- Bug Reporter: @namhihi237 $250
- Contributor: @tienifr $1000 + $500 (bonus) = $1500
- C+: @0xmiroslav $1000 + $500 (bonus) = $1500

Bump @0xmiroslav - I can't pay until the checklist is completed

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to complete the checklist so everyone can be paid, thanks!

**Comment by jliexpensify** [comment]
Bump @0xmiroslav for the checklist!

**Comment by amyevans** [comment]
Bumped in Slack

**Comment by jliexpensify** [comment]
@0xmiroslav can you please write out the proposed Regression Steps? Thanks.

**Comment by jliexpensify** [comment]
Just hired @0xmiroslav , once he accepts I'll issue payment.

@namhihi237 - Can you please update your GH name to reflect the same name in Upworks? Thanks.

**Comment by jliexpensify** [comment]
@0xmiroslav I've sent you an email, please check your Gmail Inbox.

@namhihi237 and @tienifr sorry for the delay here, I am paying you both now!

**Comment by jliexpensify** [comment]
Ok, have resolved payment issues via email with Miroslav. Inviting new profile.

**Comment by jliexpensify** [comment]
Sorted out payment for Miroslav, closing!
