### ISSUE TITLE
Login - "Request new magic code here" is not present on the 'expired magic code' page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Enter email
3. Copy magic code link
4. Change the link to staging.new.expensify.com/..
5. Change one of the characters (magic code) in the link so that the link becomes invalid
6. Navigate to the new URL

## Expected Result:
"Request new magic code here" is present on the 'expired magic code' page

## Actual Result:
"Request new magic code here" is not present on the 'expired magic code' page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e4d62363-ca77-40a6-849b-0f8ba7f1f9f9

![Bug6125037_Screenshot_2023-07-12_at_17 01 39](https://github.com/Expensify/App/assets/78819774/76241ab0-39cb-4379-b615-86de68b07bd8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
@bernhardoj are you suggesting this shouldn't be considered a bug? Or something else?

**Comment by kevinksullivan** [comment]
Thanks for clarifying.
