### ISSUE TITLE
[$1000] Chat - Part `to` in IOU preview money request can be moved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Create money request
4. Open IOU preview
5. Swipe down with your finger

## Expected Result:
Part `to` in the IOU preview money request NOT moves

## Actual Result:
Part `to` in the IOU preview money request can be moved
Split bill the same

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/38a81137-ee7a-4c25-8300-b73c4d897ab6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019548cf7c39f424bc</li>
        <li>Upwork Job ID: 1679207753173835776</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by francoisl** [comment]
I'm going to remove the deploy blocker label, this can be worked on now but isn't stopping from using the app.

PS: @c3024 can you tell if this is a regression from a recent PR?

**Comment by marcochavezf** [comment]
I will apply the `Bug` label here to follow the BZ process

**Comment by marcochavezf** [comment]
Oh thanks @aimane-chnaif, given that's being refactored, I'm leaning towards closing this GH, what do you think?
