### ISSUE TITLE
[$1000] Web - Member`s avatar is 40x40px instead of 32x32px

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Isіue found when executing PR** https://github.com/Expensify/App/pull/20512
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspace -> Create new WS -> Add any user to WS
4. Create a $$ request in a workspace chat, open the created request
5. Verify that the member`s avatar is 32x32px

## Expected Result:
The member`s avatar is 32x32px

## Actual Result:
The member`s avatar is 40x40px

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6125083_image__134_](https://github.com/Expensify/App/assets/78819774/d2adea40-198f-40d9-988d-e06cf6556466)

![Bug6125083_image__133_](https://github.com/Expensify/App/assets/78819774/abad4d60-61c7-41b1-8165-3183fdb5c0da)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c72abdd919a99974</li>
        <li>Upwork Job ID: 1679459962364895232</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Correct, closing.
