### ISSUE TITLE
Admin of a workspace can delete any message of any user in the workspace rooms

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot 
2. Log in with Account A (admin)
3. Go to Settings - Workspace 
4. Go to Members page and invite User B 
5. Send the message to WS room as User A (admin)
6. Send the message to WS room as User B
7. User A (admin) delete the message for User B

## Expected Result:
User should get some feedback that their message was deleted by an admin

## Actual Result:
Admin of a workspace can delete any message of any user in the workspace rooms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5446484d-3867-4d5d-8547-15a9663b265c

**Expensify/Expensify Issue URL:**
**Issue reported by:**@esh-g
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1688573729520919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
From slack: it was decided to go with something along the lines of creating a whisper “Your content was deleted by a workspace admin. If you’re unsure of why, please reach out to the #admins to find out!” but more opinions were needed.

I think whispers will be sent from BE so most probably an internal issue.

**Comment by mallenexpensify** [comment]
Testing Slack
https://expensify.slack.com/archives/C01GTK53T8Q/p1689173724746929?thread_ts=1688573729.520919&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Posted in [the thread ](https://expensify.slack.com/archives/C01GTK53T8Q/p1690334809958929?thread_ts=1688573729.520919&cid=C01GTK53T8Q)
> As far as I can tell, I did not get a notification that the above message was deleted.  When you click it it just takes you to the room on that date but you can't see the message.  I double checked Slackbot too and there's nothing there.

I'll look more into this soon, buried from being OOO a couple days now.

**Comment by shawnborton** [comment]
@mallenexpensify can we please get an update?

**Comment by shawnborton** [comment]
Waiting for an update, bumped @mallenexpensify 1:1

**Comment by mallenexpensify** [comment]
Closing as I consider this expected behavior, I don't think we should update our logic to show a message when an Admin deletes a message (which is the same as Slack)
