### ISSUE TITLE
 Word "Workspace" Disappears Beyond 10 Workspaces

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > workspaces > new workspace
2. Create more than 10 workspaces. First create 5 workspaces and go back to the settings page and verify if you can see the complete word “Workspace”
3. Create remaining 5 workspaces and verify if you can see word “Workspaces”
4. Minimize the window to half (In windows, its windows key+ left arrow) and verify if you can see the entire word “Workspaces”
## Expected Result: 
The word “Workspace” is visible in full window mode.
## Actual Result: 
When there are more than 5 workspaces, half of the word “workspaces” disappears. After 10 workspaces, the entire word “workspaces” disappears. However, when the window is minimized to half size or smaller, the word “workspaces” reappear and become visible again.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c122678f-ab47-412f-8fda-e60ded922cb5

https://github.com/Expensify/App/assets/43996225/e1e95a90-b2bb-4255-a59a-7134609f269c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689188052111969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment]
dupe https://github.com/Expensify/App/issues/22632

**Comment by kavimuru** [comment]
This is dupe of #22632, Closing this issue.
