### ISSUE TITLE
Web - IOU's are being paid before account B pays them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open account A and click on FAB > Request money > Enter an amount > Paste account B's email > click on request money
2. Click on the IOU card preview on account A
3. Go to account B and open the IOU and observe by waiting for a few seconds

## Expected Result:
IOU's should not say paid before account B pays them.

## Actual Result:
IOU's are being shown as paid before account B pays them.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7bf0106c-8863-4d05-976a-b661a7efa3f5

https://github.com/Expensify/App/assets/93399543/8aa1765b-22d4-4acc-9ceb-b299a7896a21

**Expensify/Expensify Issue URL:**
**Issue reported by:** React JS development and Quality Assurance (GH @Nathan-Mulugeta)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689152559795319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Sorry for the delay in triage, I will do it tomorrow

**Comment by sonialiap** [comment]
I cannot reproduce this

**Comment by sonialiap** [comment]
No response in slack. Closing. Please reopen if you can reproduce
