### ISSUE TITLE
Web - For phone login, tooltip's login is not formatted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with phone no.
2. Set a display name
3. Go to any chat
4. Hover over your icon

## Expected Result:
Login should be formatted in the form of `012345 6789`

## Actual Result:
Not formatted, includes +icon and country code
`+911234567890`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ea64fda-efff-4617-a78f-4ed0dd4a7853

https://github.com/Expensify/App/assets/93399543/39ce805f-df4f-4848-b88f-407674e27e3d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689154017647869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

for phone login, tooltip's login is not formatted


### What is the root cause of that problem?

Root cause of the issue is that we are not formatting the phone no. using the `LocalePhoneNumber.formatPhoneNumber()` util which we have made for the very purpose. This util formats the phone no. in a way that for any user, logins local to his country don't show country code and it also styles it

We are not using this util here

https://github.com/Expensify/App/blob/d6b2d073a57d7bb40ad8aea475bd7a8be946ba24/src/components/UserDetailsTooltip/index.web.js#L22-L22

but simply removing the sms domain (expensify.sms) 

Same behavior is in the reactions list page here

https://github.com/Expensify/App/blob/d6b2d073a57d7bb40ad8aea475bd7a8be946ba24/src/pages/home/report/ReactionList/BaseReactionList.js#L86-L86

### What changes do you think we should make in order to solve the problem?

We have to remove the `removeSMSDomain()` method and use the `LocalePhoneNumber.formatPhoneNumber()` since we have standardized on this

<details>
  <summary>Results</summary>


</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by isabelastisser** [comment]
The login format is expected behavior and not a bug.

**Comment by shawnborton** [comment]
I agree with keeping this closed
