### ISSUE TITLE
Web - Uploading file one by one leads the file remains in the sending process with the message Uploading attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new chat
2. Click on plus sign to add a file
3. Select a file (mp4 or image) and send it
4. Repeat this action again

## Expected Result:
Two file uploaded successfully 

## Actual Result:
Uploading file one by one leads the file remains in the sending process with the message Uploading attachment

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8d2c7cad-bb2f-4186-869c-264eacb904f7

https://github.com/Expensify/App/assets/93399543/c279bac3-3c88-4a72-af2e-86a8a95a2862

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689137581256039
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by multijump** [comment]
I couldn't reproduce this issue in new dot v1.3.39-11.

**Comment by twisterdotcom** [comment]
I also cannot reproduce. I kind of don't think you gave it enough time in that recording for the files to upload @eusalazar.

https://github.com/Expensify/App/assets/9133401/5212e111-0361-4bea-aafa-d863cae7f20c

LMK if you think you can still recreate this.

**Comment by eusalazar** [comment]
Hello, I think I did not put it in the description but you must open the console, I just reproduced it in v1.3.40-5. It's a new computer and a new account.  I'll send the video in a moment

**Comment by eusalazar** [comment]
Hi, I didn't put it in the description but you should open the console, I just played it on a new computer and a new v1.3.40-5 account, I'll send the video shortly

**Comment by eusalazar** [comment]
Select a file (mp4 or image) and send it

Uploading reprod - 2023-07-14 12_03_04.mp4…

**Comment by eusalazar** [comment]
https://github.com/Expensify/App/assets/90300459/53d5d4dc-b341-427c-a546-89dab5ee80b0

**Comment by dan1d** [comment]
I couldn't been able to reproduce but I'm seing a few console errors while following the same steps only on SAFARI: I had to upload it on youtube since github only allows for 100 MB videos: https://www.youtube.com/watch?v=jBJCeCV42Ck
First error: 
```
[Onyx] Out of storage. But found no acceptable keys to remove.
(anonymous function) — Expensify.js:42
A — web.min.js:1:2860
te — web.min.js:1:12356
promiseReactionJob
```
second: 
```
Unhandled Promise Rejection: DataCloneError: Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.
clientLoggingCallback — Log.js:54
```

<img width="963" alt="image" src="https://github.com/Expensify/App/assets/3293616/5c0f2840-4b0d-4665-925c-d3713a8741bf">

**Comment by twisterdotcom** [comment]
Okay, I'll take another look next week. Thanks for the vids.

**Comment by eusalazar** [comment]
Hello, could you review this?

**Comment by twisterdotcom** [comment]
I'm sorry @eusalazar - I still cannot recreate this: https://drive.google.com/file/d/1CQr-vXVv_ZnNmpes7jSNXk2vaMdw07i3/view?usp=sharing.

Every time my files make it. I also don't see any of the Onyx errors. I'm going to close, but please, again, do call me out for anything else you can add.
