### ISSUE TITLE
[WAITING ON SLACK] Bottom part of OTP input does not work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out if you are logged in;
2. Input you phone or email and press on Continue;
3. Click on the bottom part of any code input view;
4. Verify that the view does not get focused if pressed on the bottom part.
## Expected Result: 
The code input view which was clicked should focus.
## Actual Result: 
The code input view which was clicked does not focus.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aea9ecdf-d9df-4536-a819-b26e18d95b1c

https://github.com/Expensify/App/assets/43996225/f4b73416-884b-42ba-b907-7954a4f71e98

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DanutGavrus
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689248027917769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Bottom part of OTP input does not work
### What is the root cause of that problem?
This resulted from this [PR](https://github.com/Expensify/App/pull/19653) that added `StyleUtils.getHeightOfMagicCodeInput()` to the wrong `View`.
Right now, we are using 2 `Views` in parallel in a `parent View` inside `MagicCodeInput.js`:
https://github.com/Expensify/App/blob/9e5d4ee9ad4b0711ddb119009d49fa872e662f14/src/components/MagicCodeInput.js#L310-L328
1. As you may see here:
![addtext_com_MTYzNzU3MTMzNzM](https://github.com/Expensify/App/assets/56603839/f97508bb-03d9-4975-902d-9a797e855cf0)
1.1. Our input gets to have a *height of 52px*;
1.2. Its parent gets to have a **height of only 50px** because of a `borderBottomWidth: 2`;
1.3. Its grandparent gets to have a *height of 52px*;
3. Our input can not exceed it's parent's height;
### What changes do you think we should make in order to solve the problem?
We should move `StyleUtils.getHeightOfMagicCodeInput()` in its parent view. After this change, the bottom part of the input works.
This does not cause a regression, as I've re-tested this [issue](https://github.com/Expensify/App/issues/19387).

**Comment by kavimuru** [comment]
@DanutGavrus Green line is not showing when clicked on the bottom line. I have checked already the referenced dupe bug.

**Comment by jliexpensify** [comment]
I think this is fixed on v1.3.40-1 now. @kavimuru can you check this please?

**Comment by jliexpensify** [comment]
@DanutGavrus yes please!

**Comment by DanutGavrus** [comment]
@jliexpensify 

Hope this helps, it's from the latest staging, as of now `v1.3.41-2`:  

https://github.com/Expensify/App/assets/56603839/52458249-5e47-417d-8fb0-73006fcf7f20

**Comment by jliexpensify** [comment]
@DanutGavrus interesting - so I have an explanation here! Basically, you need to hover over the Magic Link lines and ensure that the "|" symbol exists before clicking, otherwise it won't work:

https://github.com/Expensify/App/assets/30815269/b88c1047-b840-4280-a9a4-a192c2d47e29

In your video, only the arrow is appearing, so this behaviour seems intentional.

**Comment by jliexpensify** [comment]
Closing this one out based off my above comments/observations.

**Comment by DanutGavrus** [comment]
@jliexpensify 
> you need to hover over the Magic Link lines and ensure that the "|" symbol exists before clicking  

The arrow changes to "|" symbol automatically when the mouse hovers any "text input" as this is the default browser behavior. Here, on the bottom part, it doesn't.

> this behaviour seems intentional  

*The height of the text input is **not** correctly set, it's **smaller** than its available space*. The other "text inputs" in our and other apps work on the bottom part(try playing with the *new comment field* on GitHub for example, or any other "text input").

I think this should be reopened based on these observations, what do you think?

**Comment by jliexpensify** [comment]
@DanutGavrus thanks for the additional context. Here's what I've said:

> The arrow changes to "|" symbol automatically when the mouse hovers any "text input" as this is the default browser behavior.

You've said:

> Here, on the bottom part, it doesn't.

So you're essentially saying that if you hover over any of the 6 lines (i.e. "_" ) in the Magic Code or Authenticator section, it should go green? Is that correct, or have I misunderstood you?

**Comment by DanutGavrus** [comment]
@jliexpensify 
> So you're essentially saying that if you hover over any of the 6 lines (i.e. "_" ) in the Magic Code or Authenticator section, it should go green? Is that correct, or have I misunderstood you?

![image](https://github.com/Expensify/App/assets/56603839/7b2e74df-4a65-4d7c-84e9-66c5648f6c0c)
What I actually mean is that *hovering* over the black area above the green "\_" line, seen in the previous picture, should change the mouse from *arrow* to | and should allow users to click on it.

**Comment by jliexpensify** [comment]
Thanks for clarifying, Is ee what you're saying now. I can't recall if we ever had this in place, so have asked internally - https://expensify.slack.com/archives/C01SKUP7QR0/p1689722521311609

**Comment by shawnborton** [comment]
Chiming in here, I can see where technically this is a bug. Who made [this proposal](https://github.com/Expensify/App/issues/22807#issuecomment-1634258418)? I'm not sure I understand the proposed solution but the breakdown of 52px height vs 50px height is correct. That being said... this is such an edge case, I'm not sure if it's even worth worrying about.

**Comment by jliexpensify** [comment]
Thanks for weighing in Shawn! Given that we have this input:

> the breakdown of 52px height vs 50px height is correct

and 

> this is such an edge case, I'm not sure if it's even worth worrying about.

I'm going to close this GH again.
