### ISSUE TITLE
Web-VBA-Delete the year for the incorporation date, month and day are also deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to settings>WS>Connect bank account
- Pending state withdrawal account credentials
Click on ""Manually enter account details""
Routing Number: 011401533
Account Number: 1111222233331111
Company: Alberta Bobbeth Charleson
Tax ID: 123456789
First Name: Alberta
Last Name: Charleson
4. Fill out the company information with an incorporation date in the future and proceed
5. Delete year

## Expected Result:
Deleted only year

## Actual Result:
Deleted Year, month and date

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/534bf672-6558-4fe8-9b3b-a509f69db0bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by kadiealexander** [comment]
This is expected behaviour IMO! The field is one singular field, not 3 individual fields. If you disagree, please bring a discussion to Slack about the ideal behaviour here.
