### ISSUE TITLE
Web - "Mark as done button" is grey out when network is offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any task details of opening Task (or create one if you don't have)
2. Turn off network

## Expected Result:
"Mark as done button" should display normally as there is no pending actions and we can click this button to mark Task as complete when network is offline

## Actual Result:
 "Mark as done button" is grey out when network is offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8eb98837-ff5f-4930-a753-70e51465d61d

https://github.com/Expensify/App/assets/93399543/bbf3f933-0f9a-4616-92ff-bf9320f1cf3a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689176053940809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
Same - I think this has been fixed by something upstream. I'm going to close
