### ISSUE TITLE
Security - 2fa input error message shows 'Two Factor Authentication code'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22826]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22651
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Security > Two-factor authentication
3. Click Copy > Next
4. Enter wrong 2fa code

## Expected Result:
The 2fa input error message shows 'two-factor authentication code'

## Actual Result:
The 2fa input error message shows 'Two Factor Authentication code' instead of 'two-factor authentication code'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.40.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f8c19ccc-b587-4e52-9b77-16eaf9a0158f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by Pujan92** [comment]
There is a backend issue opened for this change as per this [comment](https://github.com/Expensify/App/issues/21321#issuecomment-1629780302). Based on that, this is not a front-end change.
cc: @amyevans

**Comment by amyevans** [comment]
Yeah the backend PR is only on staging at this point, not deployed to production. So this is an expected outcome, closing the issue.
