### ISSUE TITLE
Web - Images do not work in link previews

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Log in with any account
3. Send a message including a link to a public GitHub issue such as `https://github.com/Expensify/App/issues/5536`

## Expected Result:
A link preview should appear and the image should be visible.

## Actual Result:
The image is not visible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.4

**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b333180-7e71-438c-a4e5-4d1fda48a3af

**Expensify/Expensify Issue URL:**
**Issue reported by:** Rory Abraham
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689210367443979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
linking similar issue https://github.com/Expensify/App/issues/20832

**Comment by isabelastisser** [comment]
Dupe, and the original issue is internal and on hold.

Closing!
