### ISSUE TITLE
[hold for https://github.com/Expensify/Web-Expensify/pull/38169]  Chat - Unexpected error message when trying to upload a CSV file

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS/Android/Desktop App or navigate to staging.new.expensify.com
2. Login with any account
3. Go to any conversation
4. Select ''+'' button > Add attachment
5. Send an CSV file

## Expected Result:
The user should be able to upload and send a CSV file without errors

## Actual Result:
When attempting to send a CSV file, the app returns an error message stating that the attachment is invalid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.3 

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9f5eec4a-d617-4355-b4fd-fac9ceaefe3f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Aplause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d938cefb22022fc</li>
        <li>Upwork Job ID: 1679935282985816064</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
I can reproduce on web. This seems like maybe it's a regression, as I see @youssef-lr had previously worked on an issue [here](https://github.com/Expensify/App/issues/11189), where I see we added support for CSVs.

**Comment by youssef-lr** [comment]
We merged a PR in the backend that should fix this.

**Comment by joekaufmanexpensify** [comment]
Ah okay cool. @youssef-lr mind linking the PR here so I can take a look?

**Comment by youssef-lr** [comment]
Here you go @joekaufmanexpensify https://github.com/Expensify/Web-Expensify/pull/38169

**Comment by joekaufmanexpensify** [comment]
Sounds great, thanks! I'll leave this open for now. Then, once that PR is deployed, I'll verify that it did in fact fix this bug, and then close out the issue, if so.

**Comment by joekaufmanexpensify** [comment]
I see the above PR was deployed. Just tested this on my end, and this bug is now fixed. Closing as this is all set!
