### ISSUE TITLE
iOS: The app crashes after Deleting a Workspaces and going offline and coming back online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings> Workspace
2. Create a workspace
3. Delete the workspace
4. Be offline
5. Notice the deleted workspaces appear offline
6. Be Online
## Expected Result: 
Deleted Workspaces don't appear offline and the App doesn't crash
## Actual Result: 
Deleted Workspaces appear offline and the App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:**  needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/49141ec4-5c68-46dd-b591-4f8c6c19a885

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689213503592969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm not able to reproduce. The workspace is deleted as expected and I don't see it reappear in the workspace list after I go offline.
