### ISSUE TITLE
[HOLD for payment 2023-07-24] [HOLD for payment 2023-07-21] Transactions key console error on mergeCollection

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Be logged in older account with some requests
2. Navigate to report with some requests
3. You can see errors in the console showing wrong key has been used

https://expensify.slack.com/archives/C049HHMV9SM/p1689120594593919

![image](https://github.com/Expensify/App/assets/36083550/49a372cd-703d-48ba-b935-8f89e33ffbae)

## Expected Result:
Describe what you think should've happened

No errors

## Actual Result:
Describe what actually happened

Errors

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
PR has been merged and deployed, @Santhosh-Sellavel should be eligible for $1000 payment

**Comment by Santhosh-Sellavel** [comment]
The checklist can be skipped here right @mountiny?

**Comment by sophiepintoraetz** [comment]
I think this was duped https://github.com/Expensify/App/issues/22824

**Comment by mountiny** [comment]
Yes we can skip the checklist, this was a new feature and the problem was a combination of backend and frontend changes

**Comment by Santhosh-Sellavel** [comment]
The hold for payment is updated twice. But this is due for payment today

Requested on ND

**Comment by anmurali** [comment]
Approved 1k based on https://github.com/Expensify/App/issues/22853#issuecomment-1635066062

**Comment by twisterdotcom** [comment]
Can we close this now?
