### ISSUE TITLE
[HOLD for payment 2023-10-09] [ECard Settings] - Create the Expensify card page

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22873]
HOLD ON https://github.com/Expensify/App/issues/22872

## Design Doc Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.vqu4l2y6dj9k
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ad3175064113565</li>
        <li>Upwork Job ID: 1679790242871123968</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by marcaaron** [comment]
This one also could be built in isolation for now. Sure, there is no way to navigate to this page in product yet until the issue on HOLD is complete. But we can create the page as a standalone and test it by direct navigation + some mock data.

**Comment by joekaufmanexpensify** [comment]
@pasyukevich mind commenting here so we can assign this to you?

**Comment by pasyukevich** [comment]
Hi!
I'm Eugene from Callstack.
I'd like to work on this.

**Comment by narefyev91** [comment]
> @narefyev91 Checking in to see if you'll be able to review this today?

Hey @joekaufmanexpensify! Absolutely - will be done today 100%

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by pac-guerreiro** [comment]
The PR is available here - https://github.com/Expensify/App/pull/26915

**Comment by narefyev91** [comment]
@pac-guerreiro can you please finish steps to make PR ready - fill the whole checklist - also i see some comments were not addressed - can you please react on them somehow

**Comment by narefyev91** [comment]
@joekaufmanexpensify please take a look on PR - i left comment with next steps! Thanks!

**Comment by joekaufmanexpensify** [comment]
Thanks! I see [the fix](https://github.com/Expensify/App/pull/26915#issuecomment-1720962254) is up already. @narefyev91 should be ready for another review now!

**Comment by grgia** [comment]
not overdue, @joekaufmanexpensify  could you help with $500  C+ review payment to @narefyev91

**Comment by narefyev91** [comment]
> I believe Nicolay is with CallStack, so all of their payment is handled separately. But LMK if that's not correct @narefyev91 !

That's correct - thank you :-)

**Comment by grgia** [comment]
Great, closing this out in that case
