### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [ECARD] CRITICAL: Settings - Activate physical card front end changes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22878]
HOLD ON https://github.com/Expensify/Expensify/issues/299926

## Design Doc Section

https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.hw3o4bkuci7y
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbfe4183c2159f8e</li>
        <li>Upwork Job ID: 1679791633633357824</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by joekaufmanexpensify** [comment]
Assigned!

**Comment by MrMuzyk** [comment]
@shawnborton This is the issue where the magician animation asset is needed

**Comment by shawnborton** [comment]
Here is the animation: https://www.dropbox.com/scl/fi/es03tagv4vhhywzytpitm/Expensify-Magic-Link-alt-091423-kjs-1.json?rlkey=nf5owon3xxexti2stpwpshmko&dl=0

**Comment by grgia** [comment]
In progress

**Comment by joekaufmanexpensify** [comment]
@fedirjh do you think you can review this PR today?

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by MrMuzyk** [comment]
@joekaufmanexpensify 

I want to add an error message which would be displayed to a user when he tries to activate the card without entering all 4 digits.

Here is the preview
<img width="377" alt="image" src="https://github.com/Expensify/App/assets/23487612/420b1446-03fa-4db3-a079-7c95eefd8885">

Error message text Im proposing is:
>Not enough digits.


@fedirjh Instructed me to add a `Waiting for Copy` label on the issue and ask for approval of marketing team. I don't think I have the rights to do so. Can you help me with that?

**Comment by joekaufmanexpensify** [comment]
This error case wasn't in the design doc, but makes sense to me that we'd handle it. CC @kevinksullivan and @grgia so you're aware. Definitely agree that we should loop in marketing on the copy, will do that now. 

As context for the marketing team member assigned, this error arises when a user tries to activate their physical card without entering 4 digits. 

IMO, it could make sense to di something similar to [the copy](https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.a0lo0td9gz86) for when there are 4 digits, but they're wrong. So perhaps something like:

>You didn't enter the last 4 digits of your card. Please try again.

**Comment by kevinksullivan** [comment]
I agree with @joekaufmanexpensify . Let's use the same error message across the board whenever the entry doesn't match.

**Comment by joekaufmanexpensify** [comment]
Cool cool, works for me. If we use the same one, then I don't think we need marketing sign off. As the existing error I linked above was reviewed in the design doc.

**Comment by joekaufmanexpensify** [comment]
@fedirjh could you re-review this one today? TY!

**Comment by joekaufmanexpensify** [comment]
I flagged the thread in Slack, and Shawn responded [here. ](https://github.com/Expensify/App/pull/28313#issuecomment-1747032817)

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
hey @muttmuure no need to do anything fancy here, would you mind helping me out to ensure we've completed the $500 C+ payment to @fedirjh

**Comment by muttmuure** [comment]
@fedirjh I've invited you here: https://www.upwork.com/en-gb/jobs/~010d2b3c8b73965773

**Comment by muttmuure** [comment]
I didn't see this one because it was closed. Apologies. Offer sent here: https://www.upwork.com/en-gb/ab/offer/100265307

**Comment by muttmuure** [comment]
Paid
