### ISSUE TITLE
[ECard Settings] - Add “Report card lost or damaged” page and route

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22879]
HOLD ON https://github.com/Expensify/App/issues/22873

## Design Doc Section

https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.pzrikt6apuww
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1fc285f24bcb4a2</li>
        <li>Upwork Job ID: 1679791944763441152</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Could you assign me to this @grgia ? 😄

**Comment by marcaaron** [comment]
Similarly, I think this can come off hold. We won't be able to navigate to this page in product until the Expensify Card page exists. And we won't be able to call the API until that change is done (maybe it's done). But we can for sure start creating this page now I think.

**Comment by marcaaron** [comment]
Same sentiments here. We can create this page without having the page to navigate to and get something rolling. This whole project is mostly UI so we can build it all. Nobody will be able to access it or use it until the API is ready, but shouldn't block us from building it out.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by JKobrynski** [comment]
Melvin, no overdue here, this issue is waiting for another issue to be merged.

**Comment by grgia** [comment]
In progress

**Comment by grgia** [comment]
not overdue, in progress

**Comment by joekaufmanexpensify** [comment]
@allroundexperts I see you're taking this over. Could you please confirm if you can review today? We'd like to make progress on this asap.

**Comment by joekaufmanexpensify** [comment]
Great, ty!

**Comment by grgia** [comment]
in progress

**Comment by joekaufmanexpensify** [comment]
@allroundexperts as an fyi, looks like this one is ready for re-review!

**Comment by joekaufmanexpensify** [comment]
Great, ty!

**Comment by grgia** [comment]
PR merged
