### ISSUE TITLE
[hold for payment 2023-08-31] [ECard Settings] - Update routes and references to “Payments”

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22870]
## Design Doc Section

https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.8wmzgob805vl

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134c82b64279354e2</li>
        <li>Upwork Job ID: 1679789475904880640</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
@sophiepintoraetz as an fyi, all that's needed here is C+ payment to @allroundexperts on 2023-08-31 for internal PR review

**Comment by sophiepintoraetz** [comment]
@joekaufmanexpensify - @allroundexperts raises payments via NewDot ([see SO](https://stackoverflowteams.com/c/expensify/questions/16949)). Assuming this is just a flat $1000 - so @allroundexperts can raise a request for that in ND.

**Comment by JmillsExpensify** [comment]
$1,000 payment approved via NewDot based on BZ summary.
