### ISSUE TITLE
[HOLD for payment 2023-11-02] [ECARD] CRITICAL: Settings - Add API Calls when clicking “Reveal details” buttons.

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22875]
HOLD ON https://github.com/Expensify/App/issues/22874 https://github.com/Expensify/App/issues/22876 https://github.com/Expensify/App/issues/22877

## Design Doc Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.5n1jn0riblut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd97f7877e21ceed</li>
        <li>Upwork Job ID: 1679790846718205952</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Could you assign me to this @grgia ? 😄

**Comment by marcaaron** [comment]
I think the hold is valid here. But we can start building out the component in https://github.com/Expensify/App/issues/22874

**Comment by lukemorawski** [comment]
Lucas from Callstack. Working on that one.

**Comment by grgia** [comment]
In progress

**Comment by grgia** [comment]
on hold

**Comment by grgia** [comment]
on hold

**Comment by grgia** [comment]
on hold

**Comment by joekaufmanexpensify** [comment]
Taking this one off hold based on [this ](https://expensify.slack.com/archives/C027726KHT4/p1696523020569519?thread_ts=1696522978.336909&cid=C027726KHT4)

**Comment by joekaufmanexpensify** [comment]
@rushatgabhane do you think you can review this today?

**Comment by joekaufmanexpensify** [comment]
@rushatgabhane as an fyi this is ready for re-review now!

**Comment by joekaufmanexpensify** [comment]
@rushatgabhane this one has been updated and is now ready for review again!

**Comment by jliexpensify** [comment]
Payment Summary

- C+: @rushatgabhane $500 (NEW.DOT PAYMENT)

**Comment by jliexpensify** [comment]
@grgia there's no payment on my end (J.Mills will use the summary above to pay Rushat). Feel free to close this GH if it's done!

**Comment by rushatgabhane** [comment]
request here - https://staging.new.expensify.com/r/8726366235397545

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/22875#issuecomment-1800331654).

**Comment by jliexpensify** [comment]
@grgia @joekaufmanexpensify payment for Rushat has been approved, can we close this GH? (sorry I got assigned just to handle payment so am unsure if anything else needs to be done here)

**Comment by joekaufmanexpensify** [comment]
Yep, this one should be all set!
