### ISSUE TITLE
[HOLD for payment 2023-10-24] [ECard Settings] - Add Assigned Card tile & Display Expensify cards

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22872]
HOLD ON https://github.com/Expensify/Expensify/issues/299923

## Design Doc Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.39u16xejrb8c
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab3350fcd013bf5f</li>
        <li>Upwork Job ID: 1679789970416893952</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Could you assign me to this @grgia ? 😄

**Comment by marcaaron** [comment]
I think this one actually can be off HOLD or at least split into two parts. There won't be any cards appearing until the API changes are merged and we start using these components on the "Wallet" page. But we could build most of the UI with mock data.

Maybe we can get started building out the Assigned cards tile component and add a story for it in Storybook.  

@pac-guerreiro does an approach like that work for you?

**Comment by marcaaron** [comment]
I don't think we want to switch over to the new page until the Expensify Cards are actually showing up. But we could also start reviewing and testing the changes so they are ready to ship as soon as the API changes are deployed.

**Comment by marcaaron** [comment]
I'm gonna remove the HOLD on the issue so we can get started. But I'd recommend to put a hold on the PR so it doesn't get accidentally deployed before the API changes.

**Comment by pac-guerreiro** [comment]
@marcaaron the approach you mentioned makes sense to me!

**Comment by joekaufmanexpensify** [comment]
@allroundexperts do you still want us to loop in another C+ here? Asking based on [this](https://github.com/Expensify/App/pull/26862#issuecomment-1745843798).

**Comment by joekaufmanexpensify** [comment]
Sounds good. I will ask in the room!

**Comment by joekaufmanexpensify** [comment]
@akinwale is going to [take over C+ reviewer](https://expensify.slack.com/archives/C02NK2DQWUX/p1696535074128609?thread_ts=1696525824.090429&cid=C02NK2DQWUX) on this one

**Comment by grgia** [comment]
@joekaufmanexpensify can you help to make sure that both @allroundexperts and @rushatgabhane get C+ payments

**Comment by joekaufmanexpensify** [comment]
yes!

**Comment by joekaufmanexpensify** [comment]
Payment summary: 

- @allroundexperts $500 for C+ review on internal PR. 
- @rushatgabhane $500 for C+ review on internal PR.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on BZ summary.

**Comment by joekaufmanexpensify** [comment]
Confirming second payment was issued too

**Comment by joekaufmanexpensify** [comment]
Okay, chatted with Jason and confirmed @allroundexperts payment is still pending being issued. Closing this as payment has been requested.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on summary above.
