### ISSUE TITLE
[HOLD for payment 2023-10-24] [ECard Settings] - Allow users to update the card address via  “Update address” link

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22876]
HOLD ON https://github.com/Expensify/App/issues/22875

## Design Doc Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.22f8lolqi418
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c19b21da848eb3a6</li>
        <li>Upwork Job ID: 1679791069863567360</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Could you assign me to this @grgia ? 😄

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by grgia** [comment]
In progress

**Comment by grgia** [comment]
on hold

**Comment by grgia** [comment]
^

**Comment by grgia** [comment]
^

**Comment by joekaufmanexpensify** [comment]
@narefyev91 do you think you'll be able to review this today?

**Comment by narefyev91** [comment]
> @narefyev91 do you think you'll be able to review this today?

Today unfortunately no - it's already late in my timezone - i can prioritise as a first item in the morning tomorrow

**Comment by joekaufmanexpensify** [comment]
Sounds good, ty!
