### ISSUE TITLE
[ECARD] CRITICAL: Settings - Create the “Empty state” view & Add Bank Accounts + Wallet tile

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22871]
## Design Doc Section

https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.659z4lc0lx22

<img width="288" alt="image" src="https://github.com/Expensify/App/assets/38015950/81923ae3-8ccf-42ae-a4fb-706a161ba4d3">
<img width="253" alt="image" src="https://github.com/Expensify/App/assets/38015950/dacc61ca-b1b3-4ae4-8786-4d4c9c2b7502">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a86de7e4b39b1e4</li>
        <li>Upwork Job ID: 1679789602202013696</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
For this one, we have an animation we can use so we should be able to mimic the page header component that's being used on the Preferences page. 

Then for the icons below it, we should be able to mimic the Lounge access page. 

Happy to help with the assets when this is being worked on, just let me know!

**Comment by marcaaron** [comment]
I think @francoisl should not have been assigned to this issue as it is a "New Feature". Gonna remove that assignment now and see if we can get some volunteers.

**Comment by marcaaron** [comment]
Hmm idk then - I just think that it makes more sense to seek out a volunteer for an issue like this otherwise it might stay assigned to the auto-assigned engineer and cause confusion about whether they are expected to work on it or not.

**Comment by marcaaron** [comment]
fwiw I don't think you did anything wrong by adding the `Engineering` label here. Mostly just felt like it's a case where we have a project that is already being managed by a team and assigning someone random is probably the least ideal thing we can do.

**Comment by bfitzexpensify** [comment]
Cool, gotcha, that makes sense

**Comment by kevinksullivan** [comment]
Sliding this one to daily. @shawnborton let me know if you need any other info on this!

**Comment by shawnborton** [comment]
Asked for clarification in Slack

**Comment by kevinksullivan** [comment]
Should be all set for @grgia now, right?

**Comment by pac-guerreiro** [comment]
I'm Pedro Guerreiro from Callstack, and I'll take this 😄

**Comment by kevinksullivan** [comment]
Not overdue! PR is in review

**Comment by kevinksullivan** [comment]
Still in review

**Comment by joekaufmanexpensify** [comment]
@narefyev91 as an fyi this is ready for re-review now!

**Comment by kevinksullivan** [comment]
Hmm this should stay open, right @grgia ? It's not covered anywhere else? I know the "empty state" is no longer relevant with launch of wallet, but are we using this issue to show wallet + bank account tiles?

**Comment by kevinksullivan** [comment]
Ah I think this is actually just done and didn't close, my bad.
