### ISSUE TITLE
Dev: Web - Infinite loading when changing workspace avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Go to workspace => Setting => Click on avatar and choose "Upload Photo"
3. Choose photo from attachment picker
4. Notice that it's infinite loading after that.

## Expected Result:
User can change photo without any issue

## Actual Result:
 it's infinite loading after picking photo

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5059e3a0-8628-481f-bd32-bfaff94df630

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689315976091129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite loading when uploading attachment
### What is the root cause of that problem?
Problem came from here when our attachment doesn't have URI:
https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/components/AttachmentPicker/index.js#L39-L41

It will cause AvatarCropModal loading infinite because `setIsImageInitialized` is never set.
https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/components/AvatarCropModal/AvatarCropModal.js#L122-L137
### What changes do you think we should make in order to solve the problem?
We should add uri to our file in [here](https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/components/AttachmentPicker/index.js#L39-L41):
```javascript

                    if (file) {
                        file.uri = URL.createObjectURL(file);
                        onPicked.current(file);
                    }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment]
Issue in production now https://github.com/Expensify/App/issues/22897, please close it

**Comment by CortneyOfstad** [comment]
Sounds good! Closing this now!
