### ISSUE TITLE
[HOLD for payment 2023-11-01] [ECARD] CRITICAL: Settings - Update UI to show fraud states

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22881]
HOLD ON https://github.com/Expensify/Expensify/issues/299929

## Design Doc Section

https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.1i6m8he8e79j
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0834be89a7c4cf5</li>
        <li>Upwork Job ID: 1679792329644658688</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Off hold as https://github.com/Expensify/Expensify/issues/299929 was just closed today!

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by pac-guerreiro** [comment]
Could you assign me to this @grgia ? 😄

**Comment by pasyukevich** [comment]
Hi!
I'm Eugene from Callstack, an expert contributor group.
I'd like to work on this.

**Comment by pasyukevich** [comment]
Work in progress. This issue is connected with https://github.com/Expensify/App/issues/22873

**Comment by grgia** [comment]
In progress

**Comment by grgia** [comment]
@pasyukevich do you have a PR up for this?

**Comment by grgia** [comment]
^

**Comment by pasyukevich** [comment]
Dependent on https://github.com/Expensify/App/pull/26862

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to ask you to reassign this issue to me as @pasyukevich is out of office and I have taken over his issues.

**Comment by joekaufmanexpensify** [comment]
@JKobrynski I assigned you. Is @pasyukevich going to take this one back, once they're back from vacation? If so, I will leave them assigned as well.

**Comment by grgia** [comment]
not overdue

**Comment by joekaufmanexpensify** [comment]
@eVoloshchak this is now ready for review. Do you think you'll be able to review this one today?

**Comment by eVoloshchak** [comment]
@joekaufmanexpensify, could you post a payment summary so I can request the payment for this?
I think it's the only action left in order to close this one

**Comment by joekaufmanexpensify** [comment]
Yep! Only payment needed here is $500 to @eVoloshchak for C+ review. Paid via NewDot.

**Comment by grgia** [comment]
Can we close this out @eVoloshchak

**Comment by eVoloshchak** [comment]
@grgia, yes, this one can be closed

**Comment by JmillsExpensify** [comment]
$500 payment approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/22881#issuecomment-1796291987).
