### ISSUE TITLE
[HOLD #23088 Safari-only] Web - When the user clicks on the legal firstname and last name input form, an odd, irregular vertical line appears beneath the letter "g" in safari browser

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Safari in  full screen mode & login to app
2. Go to settings
3. Click  on Profile
4. Click on Personal Details
5. Click on Legal Name
6. Click on Legal firstname as well as lastname
9. Observe that, there appears  a weird irregular  vertical line under the letter "g"

## Expected Result:
There shouldn't appears  a weird irregular  vertical line under the letter "g" when user clicks on legal firstname and last name input field

## Actual Result:
There appears  a weired iregular  veritcal line under the letter "g" when user clicks on legal firstname and last name input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS/Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a892686d-598a-4c10-a1bf-0bf48d61e066

![Screenshot 2023-07-13 at 10 07 54 PM](https://github.com/Expensify/App/assets/93399543/5ee55fb5-d1d0-46d4-ab0f-2321f285126b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689265058827759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01795fda1d3b31d1de</li>
        <li>Upwork Job ID: 1680002062156300288</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Was able to reproduce, only in Safari though, not Chrome.  @thienlnam , did you meant you disliked Safari for some reason this week? Might have been mWeb though. 
https://github.com/Expensify/App/assets/22508304/c55b55a1-50d7-4000-9c60-85260fa0efcb

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
irregular vertical line appears beneath the letter "g" in safari browser

### What is the root cause of that problem?
This is safari transforming issue 

### What changes do you think we should make in order to solve the problem?
`Add transform: 'translateZ(0)' to style`
in `style.js` we need to  add translateZ 
<img width="610" alt="Screenshot 2023-07-15 at 6 15 50 AM" src="https://github.com/Expensify/App/assets/16595846/6c0decb8-f757-4a3a-b1cc-c3e841e3fef4">

**Comment by zaitsev1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix TextInputLabel glitch animation in Safari

### What is the root cause of that problem?
Another Safari CSS Transform Render Bug

### What changes do you think we should make in order to solve the problem?
I managed to avoid this glitch by adding in style.js
`height: '100%' to textInputLabel`

https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/styles/styles.js#L879-L887



https://github.com/Expensify/App/assets/32131367/df16d699-ba4c-4a14-942c-d3957181fc97

**Comment by zaitsev1** [comment]
@pradeepmdk React Native does not natively support 3D transformations like translateZ. The styling system in React Native is based on Flexbox, which primarily focuses on 2D layouts.

**Comment by abdulrahuman5196** [comment]
@pradeepmdk / @zaitsev1 kindly provide more information on the root cause or references if this is already an known issue at multiple places.

**Comment by zaitsev1** [comment]
@abdulrahuman5196 The reason why setting the height of the textInputLabel to “100%” can potentially fix this glitch is that in Safari, when an absolutely positioned element is inside a container with a percentage-based height, the container’s height is calculated based on the height of its content. However, if the container has overflow: hidden applied, Safari may not correctly calculate the height, resulting in glitches or unexpected behavior. By setting the height of the textInputLabel to “100%”, you are ensuring that it occupies the full height of its parent container, regardless of how Safari calculates the height. This can help prevent the glitch by providing a specific height value for the textInputLabel.

We can also use CSS property willChange: "transform" to the element it can fix the glitch. It informs the browser that the element's transform property will be modified, allowing for optimized rendering and smoother animations in Safari. However, its effectiveness may vary, so it's important to test its impact in your specific scenario.

**Comment by pradeepmdk** [comment]
@abdulrahuman5196  this kind of glitch will occur on Safari browser 
Using the `transform` property on elements that are positioned absolutely or fixed

**Comment by thienlnam** [comment]
> @thienlnam , did you meant you disliked Safari for some reason this week? Might have been mWeb though.

Safari specific bugs have caused us many headaches 😅

**Comment by mallenexpensify** [comment]
Checking to see if it makes sense to create a tracking issue for safari-specific bugs 
https://expensify.slack.com/archives/C01GTK53T8Q/p1689623872647439

**Comment by abdulrahuman5196** [comment]
> Checking to see if it makes sense to create a tracking issue for safari-specific bugs https://expensify.slack.com/archives/C01GTK53T8Q/p1689623872647439

What is the plan on this? Should we pause this issue or something like that?

**Comment by mallenexpensify** [comment]
Put on hold pending
- https://github.com/Expensify/App/issues/23088

Removed `Help Wanted` and `Bug`, bumped to `Weekly`

**Comment by mallenexpensify** [comment]
Need to address safari-only bugs soon.

**Comment by mallenexpensify** [comment]
Need to get to soon.

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
