### ISSUE TITLE
[HOLD for payment 2023-07-26] [HOLD for payment 2023-07-24] Workspace - Unable upload picture to Workspace 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go Setting - Workspace
4. Select any WS and upload a picture

## Expected Result:
Able upload picture to Workspace 

## Actual Result:
Unable upload picture to Workspace 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/51423223-bf36-4e89-9051-c2b830668cc9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689315976091129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
Repro in production and dupe, closing here

**Comment by kbecciv** [comment]
I can not reproduce in production, can you please check again @Li357 ? Thank you

https://github.com/Expensify/App/assets/93399543/4ea2b9f4-650d-423d-90e8-dcbc137b94ce

**Comment by alitoshmatov** [comment]
@fedirjh Working on it

**Comment by alitoshmatov** [comment]
@fedirjh 
Created PR - https://github.com/Expensify/App/pull/22903

**Comment by Li357** [comment]
Fix is merged!

**Comment by mountiny** [comment]
I think we can close this one out

**Comment by mountiny** [comment]
As always, forgot to check if the reporter has been paid

@mateocole coul you please pay @hungvu193 $250 for reporting this bug?

**Comment by mateocole** [comment]
@hungvu193 can you apply here: https://www.upwork.com/jobs/~01099e318667c048f1

**Comment by CortneyOfstad** [comment]
Paid! So closing!
