### ISSUE TITLE
Dev: Android - Deep link does not navigate properly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any DM chat.
2. Click profile on the header.
3. Now hit a deep link new-expensify://concierge.
4. Notice that concierge chat is opened.
5. Now press the Arrow back on the header.
6. Notice that user details page shown is shown again.

## Expected Result:
That details modal is closed and then the user navigated to concierge chat on deeplink so that click back arrow on the header takes you back to LHN.

## Actual Result:
Previous details modal is shown on click of back arrow. Then previous report is shown on hitting back arrow on details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-4 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d6c40fda-a47e-458a-9f30-79f815b0d0e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689284661018839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
Chatting to @grgia this is expected behaviour related to updates to the back button we made recently. Closing
