### ISSUE TITLE
[HOLD Web#37764] Investigate incorrect reportID on first render of new transaction thread

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

cc @luacmartins @daordonez11 

The problem issues are on hold for https://github.com/Expensify/App/pull/19095

## Action Performed:
Break down in numbered steps

1. Log this [parentReportAction](https://github.com/Expensify/App/blob/73a58fde8e6e589c49dd8517b440a04ae7072a59/src/pages/home/report/ReportActionsList.js#L164C1-L164C1)
1. + > Request money
1. Tap the REPORTPREVIEW action, you'll be navigated to the IOU report
1. Tap IOU action, you'll be navigated to the transaction thread
1. Verify that the last [parentReportAction](https://github.com/Expensify/App/blob/73a58fde8e6e589c49dd8517b440a04ae7072a59/src/pages/home/report/ReportActionsList.js#L164C1-L164C1) logged is shown as REPORTPREVIEW and not IOU

1. Add a console.log [here](https://github.com/Expensify/App/blob/7e78792881e00f95c660d7ada018c93eb1f0f05b/src/pages/home/ReportScreen.js#L116) to log route.params.reportID
1. Send a message
1. Hover over the message and create a thread
1. Notice that the last reportID logged to the console is not the reportID in the route

OR 

1. Request money
2. Navigate to the IOU report
3. Click on the IOU preview 

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

On the first render the reportId considered is incorrect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1689298312169999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cac5a90fa5e8398</li>
        <li>Upwork Job ID: 1679923546767470592</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by mountiny** [comment]
this sitll needs investigation, removing C+ for now

**Comment by adamgrzybowski** [comment]
I will look into it 👀

**Comment by luacmartins** [comment]
This seems to have been fixed somehow. I just merged main into my PR and the issue I was seeing with the transaction header is gone.

**Comment by mountiny** [comment]
On hold

**Comment by mountiny** [comment]
On hold, probably fixed

**Comment by luacmartins** [comment]
I think this is resolved. We can close this issue.
