### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Web - The created task message is grey when offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new task and share in chat A
2. Go to chat A
3. Go offline

## Expected Result:
The created task message isn't grey

## Actual Result:
The created task message is grey

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7128fe19-38c1-4eb5-b63e-82159b2b91d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689304357404199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a95fa4f470fd93f</li>
        <li>Upwork Job ID: 1680964258185183232</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The created task message is grey when offline
### What is the root cause of that problem?
When creating a new task
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/actions/Task.js#L100-L103
We set pending action for report action in the parent report. But when we don’t remove pending action when success
### What changes do you think we should make in order to solve the problem?
We should remove pending action when creating a new task successfully by adding this code to successData
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/actions/Task.js#L111
```
{
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${parentReportID}`,
            value: {
                [optimisticAddCommentReport.reportAction.reportActionID]: {
                    pendingAction: null,
                },
            },
        },
```
We also should do the same thing here
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/actions/Task.js#L142
```
successData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${assigneeChatReportID}`,
            value: {[optimisticAssigneeAddComment.reportAction.reportActionID]: {pendingAction: null}},
        });
```
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
Not overdue. Just added External.

**Comment by siliconravi** [comment]
We have solved the issue by increasing the opacity to 1 instead of 0.5. For more information about clarity, please refer to the video attached below.
[Screencast from 18-07-23 03_29_46 PM IST.webm](https://github.com/Expensify/App/assets/10083892/7f6aa973-fa6c-42fe-8a7c-f1bd413955a1)

**Comment by siliconravi** [comment]
**Contributor details**
Your Expensify account email: ashish@siliconithub.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ce21269a39056e85

**Comment by siliconravi** [comment]
- **Issue**: Currently, when creating tasks in offline mode, the message appears as grey.
- **Reason**: When the application goes offline, an opacity of 0.5 is applied, resulting in the grey color.
- **Solution**:
    - Remove the opacity entirely.
    - Keep the opacity at a value of 1.

[Screencast from 18-07-23 03_29_46 PM IST.webm](https://github.com/Expensify/App/assets/10083892/5b171f76-9406-4267-87cf-ba8f6429d8c3)

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA is correct and the solution makes sense.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/22907#issuecomment-1636192653)

**Comment by s77rt** [comment]
@dukenv0307 Please leave a comment here

**Comment by s77rt** [comment]
@misgana96 Please checkout the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by s77rt** [comment]
@siliconravi Thanks for the proposal. The RCA does not seem correct. Also for future proposal please follow the proposal template. Contributing guide: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/17992
- The offending PR has been commented on: https://github.com/Expensify/App/pull/17992#discussion_r1273689340
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: We have this test https://expensify.testrail.io/index.php?/cases/view/2649462 that we can modify but I don't think this one needs a test

**Comment by lschurr** [comment]
Thanks for getting the checklist done so quickly @s77rt!

**Comment by lschurr** [comment]
Payout summary:

- Bug reporter + Contributor: @dukenv0307 $1750
- C+: @s77rt $1500

Both will be paid in Upwork tomorrow.

**Comment by lschurr** [comment]
All paid! Closing this one out.
