### ISSUE TITLE
[HOLD for payment 2023-07-18][$1000] Payment for #19508

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#22910]
Payment for https://github.com/Expensify/App/pull/19508

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01472e08484c8b1564</li>
        <li>Upwork Job ID: 1679929649799790592</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by NikkiWines** [comment]
@Santhosh-Sellavel please apply for the job in UpWork 🙇

**Comment by Santhosh-Sellavel** [comment]
@NikkiWines I will collect via NewDot. Thanks for creating an issue.

**Comment by Santhosh-Sellavel** [comment]
@NikkiWines 
Can you update the label & date for payment in the issue title? So I can follow up and collect it. Add Awaiting Payment Label & and remove Help Wanted. Thanks!

**Comment by NikkiWines** [comment]
Updated based on the merge date (2023-07-11) for the PR

**Comment by mallenexpensify** [comment]
Gonna close this, Anu will be handling payment for Santhosh outside of Upwork.

**Comment by Santhosh-Sellavel** [comment]
Requesting this now on ND
