### ISSUE TITLE
Android - App Crash on Android When Repeatedly Clicking Download Button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open the Android app.
2. Navigate to a chat where there is an attachment. (If no attachment is available, first send and receive an attachment from another account)
3. Click on the download button once and let the download be successful
4. Click on the download button multiple times in quick succession.
5. Observe that the app crashes

## Expected Result:
The app should handle multiple clicks on the download button gracefully, without crashing or encountering any issues.

## Actual Result:
The Android app crashes when the download button is clicked multiple times.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.41.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fc843ad8-b87f-4bda-a72e-4b54abbd5b1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689287471971879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
i've not been able to repro this so far

**Comment by maddylewis** [comment]
ok! i was not able to repro this. every time i clicked the DL option, i got a message that said "attachment downloaded successfully" and the app did not crash. 

ill close this one out.

**Comment by avi-shek-jha** [comment]
@maddylewis Hi, sorry for late reply. Did you click on the download button fast (like 5 times in 1 second)? Because the crash only occurs when the user clicks on the download button multiple times and fast. Try this: 
Step 1: download the attachment and let it be successful
Step 2: Click on the download button 5 times within 1 second and verify if it crashes. 

Thank you
