### ISSUE TITLE
Sending balancing requests, and then another request, duplicates the request preview

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#22916]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, request $1 from userB
2. From userB, request $1 (the same amount so that the report total is $0) from userA
3. Go back to userA and reload the page
4. From userA, request another $1 from userB
5. Verify that the report preview action is duplicated

## Expected Result:
Only one report preview action

## Actual Result:
Duplicated report preview action

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x]  MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/22219519/1f7b55c7-fcfd-48f9-b5fd-283159191f37

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ab310cf47f18329</li>
        <li>Upwork Job ID: 1680941195104231424</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
It seems that this is a BE issue.
After `RequestMoney` API success, `OpenReport` API responds `null` `iouReportID`.
![Screenshot 2023-07-15 032410](https://github.com/Expensify/App/assets/131836113/f82a8482-985f-4d5a-9f02-c2bdfdba7e52)

Therefore, when you request money again, new IOU report and report preview action will be created.
https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/libs/actions/IOU.js#L333-L349
https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/libs/actions/IOU.js#L385-L393
As a result, the duplicated report preview action is displayed.

**Comment by conorpendergrast** [comment]
I see it, yep (testing with conor+22916@conorpendergrast.com and conor+22916A@conorpendergrast.com)

<img width="813" alt="image" src="https://github.com/Expensify/App/assets/5802477/08997dbb-209d-40c8-8a91-0fefb8c08338">

**Comment by conorpendergrast** [comment]
As this looks internal (thank you @StevenKKC), moving internal

**Comment by thienlnam** [comment]
@luacmartins Do you want to take this since you're familiar with these flows?

**Comment by luacmartins** [comment]
Sure, I can take this over.

**Comment by luacmartins** [comment]
Got a PR [here](https://github.com/Expensify/Auth/pull/8302)

**Comment by JmillsExpensify** [comment]
Is there another PR to come with this issue, or can we close based on the linked and merged Auth PR?

**Comment by luacmartins** [comment]
We just needed the Auth change. We can close this one. Thanks!
