### ISSUE TITLE
Write down the correct regression guidelines

### ISSUE THREAD

**Issue by conorpendergrast** [Expensify/App#22913]
As discussed in internal Slack ([here](https://expensify.slack.com/archives/C01SKUP7QR0/p1688067825208439), and [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1688038471574029)) our current regression penalties don't correct for contributor behaviour, just contributor+ behaviour. 

- [x] 1. We should write this down in [our public documentation](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) https://github.com/Expensify/App/pull/23112
- [x] 2. We should remove any urgency bonuses is there’s a regression (already done)
- [x] 3. We should apply the penalty to the C and C+ if there’s a regression
- [x] 4. We don’t pay until 7 days after the new PR (to fix the regression) is deployed to production
- [x] 5. We should close [this SO](https://stackoverflowteams.com/c/expensify/questions/13647)
- [x] 6. Update the Upwork job description to include regressions reference https://github.com/Expensify/Web-Expensify/pull/38246
- [x] 7. Communicate in Slack to [contributor-plus](https://expensify.slack.com/archives/C02NK2DQWUX/p1690487246748689),  [expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1690538694397029) and [bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1690487179921079)
- [x] 8. Looking at [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) with the fresh eyes of following a process, I'll create a PR to call out Regressions as a separate sub-heading under [Payment for Contributions](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to make it much easier to follow https://github.com/Expensify/App/pull/24107, and [to clarify when the clock starts for the urgency bonus](https://expensify.slack.com/archives/C01SKUP7QR0/p1691432702583629?thread_ts=1691427583.528829&cid=C01SKUP7QR0)

**Comment by conorpendergrast** [comment]
Yep, I'll do this today

**Comment by conorpendergrast** [comment]
PR created and in review

**Comment by conorpendergrast** [comment]
I've also marked [this SO](https://stackoverflowteams.com/c/expensify/questions/13647) as obsolete, with a link to the contribution guidelines

**Comment by thienlnam** [comment]
Merged both PRs - now that it's official in documentation can we make sure to update the appropriate rooms so everyone is clear about this?

- [ ] contributor-plus
- [ ] expensify-open-source
- [ ] bug-zero

**Comment by conorpendergrast** [comment]
Yep, I can do that today!

**Comment by conorpendergrast** [comment]
Posted to [bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1690487179921079) and [C+](https://expensify.slack.com/archives/C02NK2DQWUX/p1690487246748689), and I'll post to

**Comment by conorpendergrast** [comment]
Posted to [open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1690538694397029). All done!

**Comment by conorpendergrast** [comment]
From [a discussion in bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1690916438197219?thread_ts=1690915913.211339&cid=C01SKUP7QR0) (internal slack channel), I am going to reopen this and rephrase things in the md!

**Comment by conorpendergrast** [comment]
No payment needed here, so I'm closing out as the PR has reached Production. Yay!
