### ISSUE TITLE
Bank account - Images are absent on Onfido setup

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22938]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22628
## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Workspace > any workspace > Bank account > Step 3: Personal information.

## Expected Result:
Images are present on Onfido setup

## Actual Result:
Images are absent on Onfido setup

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c345175e-941c-4aca-8049-b23ee26a4480

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by bfitzexpensify** [comment]
Thanks @allroundexperts. Adding engineering tag for internal review.

**Comment by flodnv** [comment]
@nkuoch I think you recently updated / worked on Onfido? If not, do you know who did?

**Comment by nkuoch** [comment]
I believe will be fixed by https://github.com/Expensify/Cloudflare-Workers/pull/66 cc @francoisl
