### ISSUE TITLE
[$1000] Web - Incorrect "New workspace" and "New room" option in FAB popover after deleting all workspaces

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Create some new workspaces (if necessary)
3. Switch to offline mode
4. Delete all workspaces
5. Click FAB
6. Verify that "New workspace" option is missing
7. Verify that "New room" option is still there

## Expected Result:
"New workspace" should appear and "New room" should not appear when there's no workspace in offline mode.

## Actual Result:
"New workspace" does not appear but "New room" appears when there's no workspace in offline mode.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b8972ddd-e65b-4121-bc09-b563bdcc55b9

https://github.com/Expensify/App/assets/93399543/9970a8ff-1066-47f2-9265-9879e081d331

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689315239330819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010209c0bef3d3cc7a</li>
        <li>Upwork Job ID: 1681559068546109440</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
All workspaces are deleted in offline mode but there's still the "New room" option in the FloatingButton (there shouldn't be because there's no workspace to select); and there's not "New workspace" anymore.
### What is the root cause of that problem?
1. In [here](https://github.com/Expensify/App/blob/67e07f9e698f29b55d41fea72cca923035b36728/src/pages/workspace/WorkspaceNewRoomPage.js#L113), we're not filtering out deleted workspaces before displaying the options
2. In [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/libs/actions/Policy.js#L175), we're using the `.pendingAction` of the policy to check if it's active or not, however in [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L33), we're not including `pendingAction` in the fields to provide to the component, so it's always `undefined` when the `hasActiveFreePolicy` check is run, leading to deleted workspace being counted as 'active'
3. In [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L165), we're not filtering out deleted workspaces before using its length [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L186C14-L186C14) to decide if we want to show the `New room` option.
### What changes do you think we should make in order to solve the problem?
1. We should create a `getActivePolicies` util in `PolicyUtils` to filter out the active policies, which will exclude the pending delete policies
```
function getActivePolicies(policies) {
    return _.filter(policies, (policy) => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE);
}
```
Then use the util [here](https://github.com/Expensify/App/blob/67e07f9e698f29b55d41fea72cca923035b36728/src/pages/workspace/WorkspaceNewRoomPage.js#L113) to filter
2. We should include `pendingAction` field [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/libs/actions/Policy.js#L175)
```
pendingAction: policy.pendingAction,
```
3. We should use the  `getActivePolicies` util to filter [here](https://github.com/Expensify/App/blob/9b205fbb26aeafea690b62412d00fd1aa5529bde/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L165) as well
### What alternative solutions did you explore? (Optional)
NA

**Comment by kadiealexander** [comment]
Repro:

https://github.com/Expensify/App/assets/59587260/67e7ec55-500f-451f-a34f-cdb268576375

**Comment by okaniie** [comment]
Contributor details
Your Expensify account email: okanihero@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ba7d28619662c2f1

**Comment by okaniie** [comment]
To fix this issue :

I'll use state variables to track workspace existence and offline mode.

Use conditional rendering to show/hide components based on states.

Display "New workspace" when offline and no workspaces exist.

Ensure "New room" is hidden in the same condition.

**Comment by kadiealexander** [comment]
Closing this one in favour of https://github.com/Expensify/App/issues/22745. Thanks @tienifr!
