### ISSUE TITLE
Chat - Skeleton page displayed when leaving a room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22787
## Action Performed:
1. Go to staging.new.expensify.com
2. Open a room
3. Click room details and click Leave Room
4. Press the back button until we return to LHN

## Expected Result:
After leaving the room, we must return to LHN

## Actual Result:
After leaving the room, the following pages are displayed: Hmm...its not here then Concierge then Skeleton page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8b32d367-f2ac-4595-8989-9399fb81a262

https://github.com/Expensify/App/assets/78819774/d2a52ecd-5724-452f-9a5b-34caa87b1d2c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by arosiclair** [comment]
Agree with @hungvu193 seems to be an existing issue. Closing this out
