### ISSUE TITLE
Web - Message action menu - The full message is copied when selecting a part of a message to copy

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Into text composer add a message with several words and click Send button
3. Manually select a word of the sent message
4. Click on the copy option on the action menu
5. Paste the message in the compose box

## Expected Result:
When selecting certain part of a message and using the copy option on the action menu, only the selected part should be copied to clipboard

## Actual Result:
The complete message is copied when selecting a just a certain part of a message to copy

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8cf898af-cfe6-49c1-83c7-8fae7a953ed0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by lschurr** [comment]
Closing this as a duplicate.
