### ISSUE TITLE
 Chat - Server message appears when sending any mp4 file in the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Sent any mp4 file

## Expected Result:
No any server message appears

## Actual Result:
Server message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6129286_image__136_](https://github.com/Expensify/App/assets/78819774/149c5a86-f848-4c7d-93ce-4c0cbda79806)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by greg-schroeder** [comment]
Following the lead here: https://github.com/Expensify/App/issues/22933#issuecomment-1637965762
