### ISSUE TITLE
Mweb- Chrome- User landed to previously left conversation page after login instead of LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Tap on a conversation
3. Tap lock icon on top
4. Clear cache and delete cookies
5. Refresh the page
6. Enter email and sign-in

## Expected Result:
The user after log in must land to LHN page

## Actual Result:
The user after login landed in previously left conversation page instead of LHN page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/78819774/3887de41-cdef-40a1-8ae3-68d11b981308

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by joekaufmanexpensify** [comment]
Yeah, it makes sense to me that we'd do that. Closing as this doesn't seem like a bug!
