### ISSUE TITLE
[HOLD for payment 2023-08-24] [HOLD for payment 2023-08-21] [$1000] Split bill - 'No results found' appears after selecting the user in split bill member search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + icon > Split bill > Enter amount > Next.
3. Type an email address.
4. Select the member in search result
## Expected Result:
There is no error message after selecting the member in the search result

## Actual Result:
No results found' appears after selecting the member in the search result

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7f2d84a4-f686-4f5f-b712-57e573250eda

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Interanl Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199d5a89c5f1a937a</li>
        <li>Upwork Job ID: 1681294844527841280</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25952719</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Still waiting on proposals

**Comment by StanislavLavrenchuk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 On the split bill page, after search Name or email and select user, there is an error message like "No results found"
Should be no error message.

### What is the root cause of that problem?
```
const headerMessage = OptionsListUtils.getHeaderMessage(
        newChatOptions.personalDetails.length + newChatOptions.recentReports.length !== 0,
        Boolean(newChatOptions.userToInvite),
        searchTerm,
        maxParticipantsReached,
    );
``` 
This function has no considered the selected members in the search result.
Should consider it.
### What changes do you think we should make in order to solve the problem?
Should consider selected members.

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
@fedirjh can you review @StanislavLavrenchuk 's proposal above please?

**Comment by StanislavLavrenchuk** [comment]
@fedirjh  thanks your review.
we should change only the first param for this feature. no need change function.

**Comment by StanislavLavrenchuk** [comment]
@fedirjh  Thanks for your reply.
I will check again, thanks

**Comment by Luckyman0305** [comment]
From
https://github.com/Luckyman0305/App/blob/82fd2f9f6f10d6580c4e01f9871a0bf3d27503e6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L148-L153
To
```javascript
    const headerMessage = OptionsListUtils.getHeaderMessage(
            newChatOptions.personalDetails.length + newChatOptions.recentReports.length !== 0,
            Boolean(newChatOptions.userToInvite),
            searchTerm,
            maxParticipantsReached,
            participants.length > 0
        );
``` 

From 
https://github.com/Expensify/App/blob/0fec944de6f8014f6a4586c7d4b988ffdf8ea495/src/libs/OptionsListUtils.js#L993-L1029

To

```javascript
/**
 * Helper method that returns the text to be used for the header's message and title (if any)
 *
 * @param {Boolean} hasSelectableOptions
 * @param {Boolean} hasUserToInvite
 * @param {String} searchValue
 * @param {Boolean} [maxParticipantsReached]
 * @param {Boolean} [isSelectedOption]
 * @return {String}
 */
function getHeaderMessage(hasSelectableOptions, hasUserToInvite, searchValue, maxParticipantsReached = false, isSelectedOption = false) {
    if (maxParticipantsReached) {
        return Localize.translate(preferredLocale, 'common.maxParticipantsReached', {count: CONST.REPORT.MAXIMUM_PARTICIPANTS});
    }

    const isValidPhone = parsePhoneNumber(LoginUtils.appendCountryCode(searchValue)).possible;

    const isValidEmail = Str.isValidEmail(searchValue);

    if (searchValue && CONST.REGEX.DIGITS_AND_PLUS.test(searchValue) && !isValidPhone) {
        return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone');
    }

    // Without a search value, it would be very confusing to see a search validation message.
    // Therefore, this skips the validation when there is no search value.
    if (searchValue && !hasSelectableOptions && !hasUserToInvite) {
        if (/^\d+$/.test(searchValue) && !isValidPhone) {
            return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone');
        }
        if (/@/.test(searchValue) && !isValidEmail) {
            return Localize.translate(preferredLocale, 'messages.errorMessageInvalidEmail');
        }
        if(!isSelectedOption)
            return Localize.translate(preferredLocale, 'common.noResultsFound');
    }

    return '';
}
```

**Comment by StanislavLavrenchuk** [comment]
@fedirjh  Please check this, I think this is good.
From
https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L129-L133
To
```javascript
            if (isOptionInList) {
                newSelectedOptions = _.reject(participants, (selectedOption) => selectedOption.accountID === option.accountID);
            } else {
                newSelectedOptions = [...participants, {accountID: option.accountID, login: option.login, selected: true, searchText: option.searchText}];
            }
``` 
From
https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L148-L153
To
    const headerMessage = OptionsListUtils.getHeaderMessage(
        newChatOptions.personalDetails.length + newChatOptions.recentReports.length !== 0,
        Boolean(newChatOptions.userToInvite),
        searchTerm,
        maxParticipantsReached,
        participants.filter(participant => participant.searchText.includes(searchTerm)).length > 0
    );

From
https://github.com/Expensify/App/blob/75e737b91867e01f83b04e4c36e0d02328e5727a/src/libs/OptionsListUtils.js#L994-L1029

To
/**
 * Helper method that returns the text to be used for the header's message and title (if any)
 *
 * @param {Boolean} hasSelectableOptions
 * @param {Boolean} hasUserToInvite
 * @param {String} searchValue
 * @param {Boolean} [maxParticipantsReached]
 * @param {Boolean} [hasMatchedParticipant]
 * @return {String}
 */
function getHeaderMessage(hasSelectableOptions, hasUserToInvite, searchValue, maxParticipantsReached = false, hasMatchedParticipant = false) {
    if (maxParticipantsReached) {
        return Localize.translate(preferredLocale, 'common.maxParticipantsReached', {count: CONST.REPORT.MAXIMUM_PARTICIPANTS});
    }

    const isValidPhone = parsePhoneNumber(LoginUtils.appendCountryCode(searchValue)).possible;

    const isValidEmail = Str.isValidEmail(searchValue);

    if (searchValue && CONST.REGEX.DIGITS_AND_PLUS.test(searchValue) && !isValidPhone) {
        return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone');
    }

    // Without a search value, it would be very confusing to see a search validation message.
    // Therefore, this skips the validation when there is no search value.
    if (searchValue && !hasSelectableOptions && !hasUserToInvite) {
        if (/^\d+$/.test(searchValue) && !isValidPhone) {
            return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone');
        }
        if (/@/.test(searchValue) && !isValidEmail) {
            return Localize.translate(preferredLocale, 'messages.errorMessageInvalidEmail');
        }
        if (!hasMatchedParticipant)
        return Localize.translate(preferredLocale, 'common.noResultsFound');
    }

    return '';
}

**Comment by StanislavLavrenchuk** [comment]
hi @fedirjh  let me know If my proposal is unacceptable.

**Comment by StanislavLavrenchuk** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/22959#issuecomment-1645202830)

**Comment by madmax330** [comment]
Issue is assigned, not overdue

**Comment by StanislavLavrenchuk1** [comment]
> ❌ There was an error making the offer to @StanislavLavrenchuk1 for the Contributor role. The BZ member will need to manually hire the contributor. cc @thienlnam

What should I have to do for solving this issue?

**Comment by luckyman0305** [comment]
I am waiting internal review @madmax330  @mallenexpensify

**Comment by luckyman0305** [comment]
Hello.
Can I get payment today or later?

**Comment by luckyman0305** [comment]
I am waiting to get payment

**Comment by luckyman0305** [comment]
I am waiting payment

**Comment by madmax330** [comment]
@mallenexpensify can you handle the payment 🙏🏽

**Comment by mallenexpensify** [comment]
Sorry for the delay, I was OOO a few days. 

Issue reporter: Applause
Contributor: @luckyman0305 , due $1000
Contributor+: @fedirjh paid $100 via Upwork

@luckyman0305 , I hired you, can you please accept the job and reply here once you have? 
(I'm assuming you're Ben G from the UK).

**Comment by luckyman0305** [comment]
![image](https://github.com/Expensify/App/assets/139998585/268e9fbb-cc17-4d4a-9da5-c96d1e0df065)
Thanks

**Comment by mallenexpensify** [comment]
Updated above, posting here too
Issue reporter: Applause
Contributor: @luckyman0305 , paid $1000 via Upwork
Contributor+: @fedirjh paid $1000 via Upwork

Thanks @luckyman0305 and @fedirjh 
Testrail update GH is [here](https://github.com/Expensify/Expensify/issues/312293)
