### ISSUE TITLE
Web - URL address in link preview marked as null for IP address as URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.expensify.com/
2. Send a message of an IP address as URL (for example https://1.1.1.1/)
3. Wait for the link preview and examine the URL address on the generated preview

## Expected Result:
The URL address should be filled with the IP address, like URL with domain

## Actual Result:
The URL address for the link preview is filled with "null"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (27)](https://github.com/Expensify/App/assets/93399543/f9de4034-2609-4a20-9dde-e098cbabad1d)

![image (28)](https://github.com/Expensify/App/assets/93399543/bc9f588b-bd4a-41d9-a8d5-e5259d3b8d1d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689414673939729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0a74fdeb2df46b3</li>
        <li>Upwork Job ID: 1681728479456423936</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
It's very important to note that this is `"null"`, not `null`. It's not distinguishable from an intended publisher with the name "null", however unlikely. Effectively making it a backend issue, as this `"null"` string does not originate form the front-end.

**Comment by marcaaron** [comment]
@sonialiap several have suggested that this is a backend issue so I am gonna make it `Internal`. Seems kind of on the rare side to enter an ip URL as a preview. I will also ask Microlink.io guys about this to see if they can fix it on their end.

**Comment by sonialiap** [comment]
@marcaaron any update on Microlink taking this on?

**Comment by marcaaron** [comment]
Yeah I will put a HOLD on this for now and assign myself. They are looking into it so no further action needed for now.

**Comment by kerupuksambel** [comment]
Hi, sorry for bumping on this issue, but I found out that this bug is resolved (either by the Microlink or the backend-related fix) in our production version. (v1.3.52.5)
![image](https://github.com/Expensify/App/assets/24503760/051b5026-2d8e-4c37-8025-3e668ad643ab)

**Comment by marcaaron** [comment]
Cool thanks! heads up we are putting this feature behind a beta and won't be accepting new bug reports for it moving forward.

**Comment by marcaaron** [comment]
This issue was resolved by microlink. @sonialiap we may need to just give @kerupuksambel a reporting bonus.

**Comment by strepanier03** [comment]
I am reopening this issue so @sonialiap can issue payment and close when that is completed. 

Sonia, could you please finish up the reporting bonus here for @kerupuksambel? Thanks!

**Comment by strepanier03** [comment]
@sonialiap - Let me know if you want me to take care of the payment here and I will.

**Comment by sonialiap** [comment]
Back from OOO 👋 

@kerupuksambel offer for reporting issue $250

New Upwork link: https://www.upwork.com/jobs/~0171e95f4e3a023942
