### ISSUE TITLE
[$1000] Web - Console error on bank account page when currency is not USD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace that has currency other then USD
5. Open Travel
6. Click on Connect bank account
7. In console, observe there is 'Refused to load' console error

## Expected Result:
 App should not display console error on connect bank account page

## Actual Result:
App displays console error on connect bank account page when currency is not USD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a05640c8-2752-4d1a-8547-f06466b35d0f

https://github.com/Expensify/App/assets/93399543/c347f2ce-2e26-4855-b537-f347bb9d431d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689408301123469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153d494452ca357e6</li>
        <li>Upwork Job ID: 1681550368177741824</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
Might be related to this comment - https://github.com/Expensify/App/pull/22903#issuecomment-1636554544

**Comment by kadiealexander** [comment]
Repro:

https://github.com/Expensify/App/assets/59587260/0c11b786-e9ee-462d-93ed-053ad2bfa268

**Comment by munsuyog** [comment]
Hey, I can do this task. Here is my approach to resolve this issue: 
To fix the "Refused to load the image" issue, I will add the 'data:' scheme explicitly to the allowed image sources in the Content Security Policy. This will enable loading and displaying images with 'data:' URLs without any security violations.

Looking Forward.

**Comment by munsuyog** [comment]
Contributor details
Your Expensify account email: mundhesuyog@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/suyogm

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Console error on bank account page when currency isn't USD

### What is the root cause of that problem?

This error isn't an error specific to bank account page. This is related to the `Content Security Policy`. We're using data: format of images over the entire project and there is no `data:` in `img-src` of policy.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We have to add `data:` to the `img-src` policy of `content-security-policy`.
web/index.html

```
<meta
      httpEquiv="Content-Security-Policy"
      content="base-uri 'self';
      require-trusted-types-for 'script'; 
      trusted-types default dompurify; 
      img-src * blob: data:;
      frame-src 'self' blob:;"
/>
```

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
This should be fine, sorry for this not being closed. I dont think there is aything we have to do about this error https://expensify.slack.com/archives/C01GTK53T8Q/p1689875960719569?thread_ts=1689752461.803139&cid=C01GTK53T8Q
