### ISSUE TITLE
Mweb - Clicking on the profile of a new user while requesting money shows the error page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Website
2. Click on Green + button
3. Request money
4. Search a new user
5. Go to description page
6. Click on user profile.

## Expected Result:
It should navigate user to profile detail page.

## Actual Result:
Clicking on the profile of a new user while requesting money shows the error page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ab5fe3b-74a2-4796-b33d-dd1ca37976fe

https://github.com/Expensify/App/assets/93399543/f16f90ed-7885-4457-a644-36fc9b90946b

**Expensify/Expensify Issue URL:**
**Issue reported by:**@Ad-eeb
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689371726554209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reviewing today

**Comment by dylanexpensify** [comment]
unable to repro - I was taken here when following steps:

<img width="366" alt="Screenshot 2023-07-20 at 10 20 46 AM" src="https://github.com/Expensify/App/assets/60117248/a0522fe0-9e50-4cce-8153-79e6f5214a89">

@ad-eeb @kbecciv mind confirming if you can still repro?

**Comment by dylanexpensify** [comment]
Bump @kbecciv @ad-eeb

**Comment by dylanexpensify** [comment]
Closing unless repro can be shown
