### ISSUE TITLE
Web - Able to split money with both primary and secondary email of a single user, split money box disappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A has a primary and secondary email in contact details
2. User B initiates split money and adds both primary & secondary emails of User A
3. Verify that no warning is shown while adding the secondary email and user is able to add the secondary email successfully
4. Verify that total amount is divided by 3 instead of 2
5. Click on split money
6. Verify split is successful for few seconds and then the split money box disappears

## Expected Result:
User B not able to add the secondary email

## Actual Result:
 User B is able to split money with both primary and secondary email of a single participant. Also, the split money box disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c0002910-f3ec-40d9-b229-185511946cb0

https://github.com/Expensify/App/assets/93399543/5fa32fd2-6198-4dc7-b560-38f4f4ae43b8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689381510156139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Explained reasoning for the close in slack
