### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Android - Older notification messages are not dismissed even after opening them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android and login with user A
2. From any other device, login with user B and open user A report
3. Send few messages to user A
4. From user A device, open the messages from notification and again minimize the app
5. From user B device, again send messages to user A and observe that in user A message notification, it still displays older message which were already clicked and viewed from notification

## Expected Result:
Notification should not display messages that are already opened from notification

## Actual Result:
Notification displays messages (along with new message) that are already opened from notification

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/995f6884-64b0-4c8b-8707-d3e024964232

https://github.com/Expensify/App/assets/93399543/15201a7f-9e5d-46e8-b3a9-494929c409de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689416596763229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e2e450e088c16b7</li>
        <li>Upwork Job ID: 1681207384647168000</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
Either a backend issue or an anomaly, at least that's my guess.

**Comment by stephanieelliott** [comment]
Hey @fedirjh any thoughts? Do you agree this is back end?

**Comment by Julesssss** [comment]
I was unable to triage today, but this seems odd. The cache should clear when a notification is swiped.

**Comment by Julesssss** [comment]
Just confirmed this isn't occurring for me. Can we please check the device model and Android version please?

https://github.com/Expensify/App/assets/10736861/7bb4dcec-916b-4449-8064-3eed54d1e707

**Comment by stephanieelliott** [comment]
I'm not able to repro it on the simulator either, closing but anyone who can reproduce please feel free to reopen.

**Comment by dhanashree-sawant** [comment]
Hi @Julesssss , @stephanieelliott I am still able to reproduce, 
Android version: 13
Device: mi11x
This is how am testing:
1. When message is recieved, tap in notification and open the message and minimize the app
2. Again send messages and repeat step 1, observe that notification will also have the message opened in step 1 along with new message

**Comment by Julesssss** [comment]
Ah I see. So instead of swiping the notification we should just tap it. 

Yeah, I'm able to reproduce!

**Comment by stephanieelliott** [comment]
Still waiting for proposals

**Comment by Julesssss** [comment]
I'll probably solve this one myself.

**Comment by cubuspl42** [comment]
@Julesssss Do you already have an intuition where the solution might be placed (frontend or backend), or do you mean that you'll start investigating that?

**Comment by Julesssss** [comment]
It's fixed in native code. We'll just make sure to clear the notification cache when the notification is tapped. Currently, we just do it when swiped. I'll submit the PR when I have a moment.

**Comment by dhanashree-sawant** [comment]
Hi @arosiclair, @Julesssss, is it eligible for reporting bouns?

**Comment by Julesssss** [comment]
> is it eligible for reporting bouns?

Yeah, we;ll just pay out after the internal PR is merged.

**Comment by stephanieelliott** [comment]
PR is under review

**Comment by stephanieelliott** [comment]
PR still being reviewed

**Comment by Julesssss** [comment]
PR merged, we can pay the reporter bonus 👍

**Comment by Santhosh-Sellavel** [comment]
@stephanieelliott I'll collect via ND, and cancel the offer. Just leave a payment summary comment. Thanks!

**Comment by dhanashree-sawant** [comment]
Thanks @stephanieelliott, I have accepted the offer.

**Comment by arosiclair** [comment]
[PR is on staging](https://github.com/Expensify/App/pull/23825). I forgot to link this issue on the PR originally but it is linked now. Hopefully automations still work

**Comment by Santhosh-Sellavel** [comment]
Got deployed on [production](https://github.com/Expensify/App/pull/23825#issuecomment-1673844067) today!

cc: @arosiclair @stephanieelliott Please update labels here thanks!

**Comment by Santhosh-Sellavel** [comment]
Request on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,000 approved for payment via NewDot based on BZ summary.
