### ISSUE TITLE
[HOLD for payment 2023-08-14] [$1000] Chat - Clicking Outside Link in Link Preview Should Not Open the Link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Login to the application and navigate to any chat.
2. Send a link (e.g., www.google.com) in the chat.
3. In the link preview, click outside the link (next to it) instead of directly on the link itself.

## Expected Result:
Clicking outside the link in the link preview should not open the corresponding link.

## Actual Result:
When clicking next to the link in the link preview, it opens the corresponding link in a new tab or the default browser,

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ca3907b-d9ed-46b1-aca6-8d8363b85ab4

https://github.com/Expensify/App/assets/93399543/664e2bd8-a446-4d7c-8bc0-3c408966b600

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689435841926949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019285d8fb1003132d</li>
        <li>Upwork Job ID: 1681656254083117056</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
by : @ahmdshrif 

### Please re-state the problem that we are trying to solve in this issue.
Clicking next to the link preview click on the link

### What is the root cause of that problem?
By default, we will set align-self or align-items on the parent to stretch  to the View, which stretches the
textLink to take the parent width. 

### What changes do you think we should make in order to solve the problem?
we need to add self-alignment to  start or Baseline the text-link style here 

https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/LinkPreviewer.js#L108-L114

``` js
style={[styles.pv2, StyleUtils.getTextColorStyle(colors.blueLinkPreview), styles.alignSelfStart]}
```

 
### What alternative solutions did you explore? (Optional)

add a container with styles.alignItemsBaseline (or styles.alignItemsStart) to the text link 
or for the preview container. 

### Result :


https://github.com/Expensify/App/assets/21364901/33126c72-ac5c-4643-bbda-e8b8dfb4e681

**Comment by JmillsExpensify** [comment]
This is not a bug in my opinion, as we're still building out the feature and it's debatable how this new feature should work. That said, I think I agree that within the link preview, only the hyperlink within the preview should be clickable. I'll triage.

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.

Chat - Clicking Outside Link in Link Preview Should Not Open the Link

### What is the root cause of that problem?

TextLink is stretched according to It's parent View component, So It is clickable to full width of screen ( out side of title)

### What changes do you think we should make in order to solve the problem?

You need to wrap TextLink inside the View component with styles.flexRow. You need to change [Here](https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/LinkPreviewer.js#L108-L114) like below mention code.

```
<View style={styles.flexRow}>
     <TextLink
        fontSize={variables.fontSizeNormal}
        style={[styles.pv2, StyleUtils.getTextColorStyle(colors.blueLinkPreview)]}
        href={url}
    >
        {title}
    </TextLink>
</View>
```

### Video:

https://drive.google.com/file/d/1mhtv72Ks1rYKFut0ig7JpxEdV-gJO-aT/view?usp=sharing

**Comment by JmillsExpensify** [comment]
@mananjadhav Mind reviewing these proposals in the coming days? Thank you!

**Comment by mananjadhav** [comment]
I'll review this today/tomorrow.

**Comment by mananjadhav** [comment]
Adding `alignSelfStart` should be good to fix this. Hence @ahmdshrif's [proposal](https://github.com/Expensify/App/issues/22979#issuecomment-1637168904) here is good to go.

🎀 👀 🎀  C+ Reviewed.

**Comment by Gonals** [comment]
Hmmm. It seems I can't add @ahmdshrif. Are they not in the repo yet?

**Comment by Gonals** [comment]
There we go! Apparently you have to comment on the issue before I can add you 😁

**Comment by JmillsExpensify** [comment]
@mananjadhav When you get a chance over the next week, let's get this BZ checklist kicked off. Thanks!

**Comment by mananjadhav** [comment]
Yes I'll be doing this by coming weekend.

**Comment by mananjadhav** [comment]
We added the click behavior to the preview links in this [PR](https://github.com/ahmdshrif/App/commit/3551658ff7d5d7703288c9e14b85eb655f941497), but we didn't check the clickable area for the extra padding.

I posted a commented on the PR [here](https://github.com/Expensify/App/pull/21717/files#r1291686606). 

I don't think we need a regression test here.

**Comment by mananjadhav** [comment]
@JmillsExpensify Raising my request on NewDot, can you please comment here with the payment summary?

**Comment by JmillsExpensify** [comment]
Summarizing the payments per the [urgency confirmation](https://github.com/Expensify/App/issues/22979#issuecomment-1661885085) above. 

 - Issue reporter: @ahmdshrif $250
 - Contributor: @ahmdshrif $1,500 (incl. urgency bonus)
 - Contributor+: @mananjadhav $1,500 (incl. urgency bonus, paid via NewDot)

**Comment by JmillsExpensify** [comment]
Separately, I confirm that the payment summary above for @mananjadhav is accurate and ready for payment in NewDot.

**Comment by JmillsExpensify** [comment]
Great thanks! Offer sent

**Comment by JmillsExpensify** [comment]
All paid out and contract closed! Thanks everyone.
