### ISSUE TITLE
Concierge welcome message duplicates when user tries to 'Reply in thread' 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#22989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Create a new account
- Locate the concierge chat
- Tap 'Reply in thread'

## Expected Result:
- Exactly one welcome message should be shown

## Actual Result:
- Two welcome messages are shown
- A new one is duplicated when you enter the thread

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

<img width="1074" alt="Screenshot 2023-07-17 at 11 35 36" src="https://github.com/Expensify/App/assets/10736861/ff10a839-7d84-4a86-976b-781cd6403b4c">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148a7248849f74964</li>
        <li>Upwork Job ID: 1680889346378813440</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
This can only be tested by internal employees.

**Comment by Jahanzaib00** [comment]
I've reproduced the issue and found the issue as well. This is happening due to the component rendering twice. The issue could be fixed by removing the 2 lines causing issue in app.jsx

**Comment by Julesssss** [comment]
@Jahanzaib00 I just fixed this with a backend change, but I'm curious how your solution worked. Maybe there is a second bug?

**Comment by Julesssss** [comment]
[Backend PR](https://github.com/Expensify/Web-Expensify/pull/38180)

**Comment by Jahanzaib00** [comment]
Contributor details
Your Expensify account email: jahanzaibkhursheed2002@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01636befde3d45d50f

**Comment by conorpendergrast** [comment]
Cool, thanks Jules!

**Comment by Julesssss** [comment]
Pr was deployed to production. I reported it so there is nothing to pay out
