### ISSUE TITLE
[HOLD] Web - Suggestion list display different random generated avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to new dot
2. Open a chat and type @ for suggestion list
3. Observe that suggestions list display different avatar as compared to user profile or LHN

## Expected Result:
Avatar in suggestions list and profile should be the same

## Actual Result:
Avatar in suggestion list is different as compared to profile one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b2a4e0d9-ff17-426e-bc35-313efb84a55c

https://github.com/Expensify/App/assets/93399543/941fadc0-4f41-48b1-bef9-104c60ae68ec

**Expensify/Expensify Issue URL:**
**Issue reported by:** @spcheema
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689345755284969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
# Proposed solution
### Please re-state the problem that we are trying to solve in this issue.
Suggestion list displays different random generated avatar as compared to profile.
**What is the root cause of that problem?**
Profile page or LHN is `UserUtils.getAvatar()` method is retrieve default avatar associated with the user profile. But in the case of suggestions list is displaying avatar from report participant details (coming form personal details object)
**What changes do you think we should make in order to solve the problem?**
Use `UserUtils.getAvatar()` to display an avatar associated with the given accountID.
https://github.com/Expensify/App/blob/a2dc004c6342c3b2e1e9a61bdc40b99da4fb647c/src/pages/home/report/ReportActionCompose.js#L493-L499
Here is updated code:
```
    icons: [
        {
            name: detail.login,
            source: UserUtils.getAvatar(detail.avatar, detail.accountID),
            type: 'avatar',
        },
    ],
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexpensify** [comment]
@Beamanator - I noticed your feedback here: https://expensify.slack.com/archives/C049HHMV9SM/p1686831792192539?thread_ts=1686829891.048029&cid=C049HHMV9SM

Is this GH-expected behavior or different? 

At this point, I can't replicate and will continue testing if this is a different issue.

**Comment by Beamanator** [comment]
@alexpensify i'd say this is not expected behavior & is different than that slack thread b/c in that slack thread, the created account's accountID is changing from an optimistic one (super random) to one when the user is created in the DB.

In this case, the accountID should be the same (oh we determine which default avatar to use based on account ID by the way) so we should have the same avatars I believe

**Comment by Beamanator** [comment]
Agreed @spcheema mentions are relatively new, and it's possible @puneetlath is planning to do something to update mentions soon - he's on vacay until next week

**Comment by alexpensify** [comment]
Ok, with this news, I've put this one on HOLD and changed it to Weekly. Also, I set a reminder in my calendar to reopen early next week to continue the discussion. Thanks!

**Comment by alexpensify** [comment]
Thank you for this update @spcheema. With this news, I'm going to close this GH.
