### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] splitting bill with phone account shows @expensify.sms

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. login with an sms account
2. split bill with a few members
3. Check the who paid field's subtitle text
## Actual Result: 
@expensify.sms should is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/050219d3-c177-41b7-b2a2-92168126c7dc

![Snip - (33) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/ea1caa94-b3a7-43e1-a2f2-578d21636736)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688810314872429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128597348b75205c2</li>
        <li>Upwork Job ID: 1682899214742786048</li>
        <li>Last Price Increase: 2023-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>chiragxarora | Contributor | 26071204</li>
<li>chiragxarora | Reporter | 26071208</li>
<li>situchan | Contributor | 26071280</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## PROPOSAL

### Please re-state the problem that we are trying to solve in this issue.

splitting bill with phone account shows @expensify.sms
 
 ### What is the root cause of that problem?

Root cause of the issue is that in split bill flow, when we are fetching the payee's personal details by the method `getIOUConfirmationOptionsFromPayeePersonalDetail`, we have not formatted the text and alternate text which we end up showing in `<MoneyRequestConfirmationList/>` > `<OptionsSelector/>`

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/OptionsListUtils.js#L878-L894

### What changes do you think we should make in order to solve the problem?

We need to format the alternate text and display name fields using `formatPhoneNumber()` method in `LocalePhoneNumber` util
 
### What alternative solutions did you explore? (Optional)

We can find other inconsistencies (if any) and fix them all at once

**Comment by MitchExpensify** [comment]
Commented in Slack

**Comment by MitchExpensify** [comment]
Confirmed @expensify.sms is not expected to be shown anywhere in app

**Comment by KrAbhas** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
If the payee is logged in using phone number, then @expensify.sms should not be displayed while splitting bill after login id.

### What is the root cause of that problem?
The login information is displayed plainly from props without formatting and as it has the format `<phone number>@expensify.sms` 

### What changes do you think we should make in order to solve the problem?
In the function `getIOUConfirmationOptionsFromPayeePersonalDetail` we need to provide check for if there is phone number(sms) based login, then we need to format that phone number by removing `@expensify.sms` in another variable and then put it in `alternateText`.
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/OptionsListUtils.js#L905-L921

### What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment]
One note to the internal engineer eventually assigned - Lets double check if we're actively removing @expensify.sms from the front end or the back end across the board just to be 100% sure

**Comment by MitchExpensify** [comment]
Friendly reminder to review the existing proposals @0xmiroslav 👍

**Comment by MitchExpensify** [comment]
Waiting on @0xmiroslav's review of the existing proposals, Melvin

**Comment by MitchExpensify** [comment]
Friendly bump @0xmiroslav

**Comment by MitchExpensify** [comment]
Sent a friendly bump to @0xmiroslav in Slack DM for their follow up here 👍

**Comment by situchan** [comment]
Coming from @0xmiroslav's [request](https://expensify.slack.com/archives/C01GTK53T8Q/p1691412177003539), I will help review as C+

**Comment by situchan** [comment]
@stitesExpensify can you please assign me too?

**Comment by MitchExpensify** [comment]
Bump on the BZ steps @situchan

**Comment by MitchExpensify** [comment]
**Payment summary:**

Reporting: @chiragxarora $250 (Upwork)
C: @chiragxarora $1500 (Upwork)
C+: @situchan $1500 (Upwork)

**Comment by MitchExpensify** [comment]
Paid!

**Comment by situchan** [comment]
Regarding BZ checklist:
This is minor inconsistent display issue specific to phone users and does not affect any app logic including split bill.
No need regression test.

**Comment by MitchExpensify** [comment]
Great, thanks for confirming @situchan - All done here!
