### ISSUE TITLE
Android - Some characters gets overlapped  by the white underlining in the "Display Name" Inputs field.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open  app in android  & login to app
2. Go to settings
3. Click  on Profile
4. Click on Display name
5. Type random characters which contain  "g" & "y"  in First Name & Last Name input field,  eg: fsfsfsyyyggfsfyygg
6. Observe that, letter "g" & "y" gets  overlapped by the white underlining

## Expected Result:
Characters shouldn't get overlapped by the white underlining

## Actual Result:
Letters "g" & "y" was  overlapped by the white underlining

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-16 at 12 04 44 AM](https://github.com/Expensify/App/assets/93399543/a84a3458-e7e0-44dc-acbb-1b73a6f31c35)
![Screenshot_20230717_074928_Expensify Chat (1)](https://github.com/Expensify/App/assets/93399543/ec8f806c-105d-45c1-904d-eb996f9035e2)
![Screenshot_20230717_074928_Expensify Chat](https://github.com/Expensify/App/assets/93399543/3d4d7eae-0b47-42ee-921b-b90ab11db941)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689445672239799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
agree with @hungvu193 - closing this
