### ISSUE TITLE
Chat - No Concierge message when initiating chat with user with no chat history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + button > New chat
3. Click on the user that has no conversation history

## Expected Result:
'Make sure you know this person before you respond.' concierge message shows up

## Actual Result:
Make sure you know this person before you respond.' concierge message does not show up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/11c48307-ce3f-452b-b382-fd1b81ae66cc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by aditya-ragi** [comment]
'Make sure you know this person before you respond.' we are talking about 'responding', I think this should be the expected behaviour as the message should show up only when we get a message from unknown person, and not when we are SENDING a message to an unknown person.

**Comment by aditya-ragi** [comment]
Your Expensify account email: hireadityaragi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8498acbc5e8f6e4

**Comment by garrettmknight** [comment]
@lanitochka17 When someone you haven't chatted with messages you, you'll receive the message in both staging and prod:

<img width="1375" alt="Screenshot 2023-07-18 at 11 50 59 AM" src="https://github.com/Expensify/App/assets/1529980/aea7af4b-471e-45a0-a103-d46a9ab1f7e2">
