### ISSUE TITLE
[HOLD #23088 Safari-only] A native tooltip is also shown along with the normal user tooltip.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app
2 Hover over the user whose display name is longer and truncated
## Expected Result: 
One type of tooltip should be shown
## Actual Result: 
2 Type of tooltip is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cface4ac-863d-488a-aca8-36dbdb17731c
<img width="1440" alt="Screen Shot 2023-07-17 at 7 39 37 AM" src="https://github.com/Expensify/App/assets/43996225/94a6434c-df4c-403f-b71c-3f4aba42ee11">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688369820557119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This is the default behavior of Safari. Do we still want to remove it?

**Comment by mallenexpensify** [comment]
Was able to reproduce, the tooltips didn't show at the exact same time but there were two tool tips. 
I started a [safari-only tracking issue ](https://github.com/Expensify/App/issues/23088)and added it there.  bumping to weekly for now

**Comment by mallenexpensify** [comment]
Removed bug label since it's on hold, updated the title too

**Comment by mallenexpensify** [comment]
Need to address safari-only bugs soon.

**Comment by mallenexpensify** [comment]
Need to get to soon

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
