### ISSUE TITLE
Web - New Line Restriction in Task Title Editing, Inconsistency with Description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Initiate a task with a dummy name and dummy description
2. Add an assignee and share somewhere
3. In the task thread, try to edit the title by including a new line (Use Shift + Enter to create a new line and add few characters)
4. Verify the new line cannot be saved
5. Try the same with description and verify that you can add new lines into description

## Expected Result:
When editing the task title, the application should allow the use of new lines or line breaks. Users should be able to format the task title with multiple lines if desired, similar to the behavior in the description field.

## Actual Result:
There is a limitation in the task title editing feature that restricts the use of new lines or line breaks which is inconsistent with description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7792eea7-6d4f-4a95-911c-ac7fbdf75ada

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689374879032619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Likely same RCA as https://github.com/Expensify/App/issues/23025

**Comment by thienlnam** [comment]
Actually, looking at this bug report again - going to close since we don't support multi line task titles so this is working as expected
