### ISSUE TITLE
Dev: Web - Task title with multi line not displayed in correct way

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task

## Expected Result:
Task header should be displayed in proper way

## Actual Result:
Task title with multi line not showing in correct way

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.41-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ddfea313-5bf9-4d68-bd34-d7faa5cd320d

![Screenshot 2023-07-15 at 8 24 25 PM](https://github.com/Expensify/App/assets/93399543/f03380a9-fa6a-42b5-ab28-e2549cdc08fa)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689434622196489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Likely same RCA as https://github.com/Expensify/App/issues/23027

**Comment by thienlnam** [comment]
Yeah, going to close this - let's just resolve in the issue that @dhairyasenjaliya linked
