### ISSUE TITLE
Admin Room – User land to chat section directly on reload of “Welcome Message” Section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23036]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Navigate to any "Admin Room."
2.	Click on avatar placed in header to open “Details”
3.	Click “Welcome Message”
4.	Reload the page.
5.	Now click back button
6.	Notice the user lands on chat section directly instead of going back stepwise, mean details and then to chat.
## Expected Result: 
The user shouldn’t land on chat section directly due to reload of “Welcome Message” Section, instead stepwise like going back to details and then chat.
## Actual Result: 
The user lands directly on chat section due to reload of “Welcome Message” Section.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/628baf33-c050-4dbe-ba37-200e1b93f739

https://github.com/Expensify/App/assets/43996225/e3b2931b-0f50-4598-95b6-154620242f74

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689575325159309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Also https://github.com/Expensify/App/issues/22887 seems related? 🤔

**Comment by greg-schroeder** [comment]
Posted there, maybe we consolidate these?

**Comment by greg-schroeder** [comment]
Closing these in favor of the original issue https://github.com/Expensify/App/issues/22041
