### ISSUE TITLE
Task - The cursor isn’t appeared at the end of the text input on title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22586
## Action Performed:
1. FAB > Assign Task
2. Enter a large amount of text into the task title This is a very very long task title that should occupy multiple lines, at the very least., verify that it can occupies multiple lines
3. Finish creating the task with any other values for the other fields
4. In the Task View, click the title

## Expected Result:
Verify that the cursor is at the end of the text input

## Actual Result:
The cursor isn’t appeared at the end of the text input

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8b8c62ca-ef75-4a0e-b287-b629c0daa66d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by jasperhuangg** [comment]
This bug was already previously reported, closing it out
