### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Whole App UI cuts off with company popup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Workspaces
2. Navigate to any Workspace
3. Click Bank Account
4. On Bank setup step 2 -> Click on Company Type
5. Once dropdown is open -> Send app to Background
6. Open app again (It will close popup and refresh which leads to cut off whole app's UI)
## Expected Result: 
This process should only close popup and load the screen properly
## Actual Result: 
Whole App's UI cuts off

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/8dd1608c-dea6-4f6b-a27c-5eb82c1d69f1" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/93c7d8a1-273c-452e-b7fe-9946ec1be2b0" width="40%" height="40%">

https://github.com/Expensify/App/assets/43996225/0b3f72a5-898e-4749-b510-5e77097ea407

https://github.com/Expensify/App/assets/43996225/ba09f351-3e1d-45f4-985a-61499b3b4e6d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689575559714959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfc1471539715421</li>
        <li>Upwork Job ID: 1681301579072643072</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
Nice and reproducible, thanks!

**Comment by s77rt** [comment]
@bernhardoj Thanks for the proposal. Your RCA is correct. The solution makes sense but before moving forward with that, can we assess whether `onRequestClose` would be useful / called in such cases?

**Comment by srikarparsi** [comment]
Looks good to me as well, assigning you to the issue @bernhardoj

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/react-native-picker-select/pull/8
- The offending PR has been commented on: https://github.com/Expensify/react-native-picker-select/pull/8#discussion_r1275523492
- A discussion in #expensify-bugs has been started: I don't think this is needed. Seems like the kind of bug that can be caught during testing, nothing specific needed for the checklist
- Determine if we should create a regression test for this bug: No

**Comment by conorpendergrast** [comment]
@bernhardoj Please remember to [apply to the Upwork job](https://www.upwork.com/jobs/~01bfc1471539715421)!

**Comment by conorpendergrast** [comment]
Payouts due:

- [ ] Issue Reporter: $250 @DinalJivani 
- [ ] Contributor: $1000 + 50% bonus = $1,500 @bernhardoj
- [ ] Contributor+: $1000 + 50% bonus = $1,500 @s77rt 

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/23044#issuecomment-1646254637)

Upwork job is [here](https://www.upwork.com/ab/applicants/1681301579072643072/job-details)

**Comment by conorpendergrast** [comment]
All done!
