### ISSUE TITLE
[$1000] Login Screen - A thin multi-colored line has appeared on the right edge of the animation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop App or start staging.new.expensify.com on Chrome
2. Look at the animation on the login screen
3. Look at the animation on the Settings > Preferences

## Expected Result:
There should not be any extra elements

## Actual Result:
A thin multi-colored line has appeared on the right edge of the animation on Login screen
A thin multi-colored line has appeared on the left and right edges of the animation on Settings > Preferences screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6131681_Desktop-Login-Multicolor-Line](https://github.com/Expensify/App/assets/78819774/0e7f3623-94a2-42a1-86f8-eb304a223fcc)

![Bug6131681_Desktop-Preferences-Multicolor-Lines](https://github.com/Expensify/App/assets/78819774/cee90ac8-895f-4f7a-aec4-3e2238b4c7b8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01505741f5a1e1c7c8</li>
        <li>Upwork Job ID: 1681413334002466816</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
Is it `patches/react-native-web-lottie+1.4.4.patch` that is causing the bug?
Cause both animation use Loitte.

**Comment by jasperhuangg** [comment]
I'm unable to reproduce this on any of the MacOS platforms (Safari, Chrome, Desktop). It looks like the screenshot shows it happening on Mac desktop.

I'm on our latest release on staging is 1.3.42.18 and it appears to be gone https://github.com/Expensify/App/tags

<img width="1523" alt="Screenshot 2023-07-18 at 10 41 26 AM" src="https://github.com/Expensify/App/assets/31285285/9755e376-f05e-4c58-a989-017b4b8c53aa">

<img width="1192" alt="Screenshot 2023-07-18 at 10 41 53 AM" src="https://github.com/Expensify/App/assets/31285285/c4142a85-521f-461f-b3a1-baa3c4d0200d">

<img width="1727" alt="Screenshot 2023-07-18 at 10 44 06 AM" src="https://github.com/Expensify/App/assets/31285285/6596e458-b24b-484c-b610-1cd2723b6f9c">

cc @marcaaron gonna remove the `Deploy Blocker` label and add `Needs Reproduction`

**Comment by trjExpensify** [comment]
Doesn't need two BZs, dropping off.

**Comment by lanitochka17** [comment]
Issue is not reproducible

![Safari-login](https://github.com/Expensify/App/assets/78819774/cf88424d-fe5a-4809-80c5-36060bc796e5)
![Chrome-login](https://github.com/Expensify/App/assets/78819774/05ae1981-4e1a-47f5-97a1-ab01e7dc8e49)
![Desktop-Preferences](https://github.com/Expensify/App/assets/78819774/7a70bf3c-398d-48fa-aa6b-bf048c045e1f)
![Desktop-login](https://github.com/Expensify/App/assets/78819774/1f6b2373-3879-4a94-8f01-bd5de888e570)
