### ISSUE TITLE
[HOLD for payment 2023-07-26] Remove use of withNavigationFocus and withNavigation from ReportScreen to improve performance

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#23065]
### Problem

Using props from `withNavigationFocus` and `withNavigation` caused `ReportScreen` to rerender when opening and closing RHP, leading to performance issues.

### Solution

We found a way to not use these props on this screen.
- To replace props with `withNavigationFocus` we can compare if `topMostReportId` is equal to `reportID` from route
- From `withNavigation`, we only used the screen key to have a unique key for nativeID. Instead, we can just generate a random key
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d56b3a859890e9d</li>
        <li>Upwork Job ID: 1681239609714049024</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by adamgrzybowski** [comment]
Commenting

**Comment by mountiny** [comment]
PR is in a review.

**Comment by mollfpr** [comment]
@mountiny Is this issue needs the BZ checklist since it's another work for navigation refactoring?

**Comment by mountiny** [comment]
@mollfpr $1000 for internal review and testing

@isabelastisser no checklist needed here. thanks!

**Comment by isabelastisser** [comment]
Thanks for clarifying @mountiny! I will process the payment in Upwork tomorrow.

**Comment by isabelastisser** [comment]
Payment made in Upwork, closing!

- $1000 for internal review @mollfpr

**Comment by mollfpr** [comment]
@isabelastisser Accepted the offer on Upwork. Please end the contract, thank you!

**Comment by mollfpr** [comment]
Friendly bump @isabelastisser

**Comment by mallenexpensify** [comment]
I'm showing it as ended @mollfpr. 
<img width="436" alt="image" src="https://github.com/Expensify/App/assets/22508304/db3f1247-7959-48e3-9eab-f4113b88570e">
