### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-26] Web - Unable to drag and select text in any text field or text area

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to any account.
2. Type any text into a text field or text area, such as a chat box or search box.
3. Hold down the left mouse button and drag the pointer over the text to select it.

## Expected Result:
The text should be selected.

## Actual Result:
Unable to select any text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5c3581af-ee5d-4bf1-b3ab-f312b1670912

https://github.com/Expensify/App/assets/93399543/0a11888f-6497-49fe-aeb3-73fa4415947c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689669838867329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01121033f421943618</li>
        <li>Upwork Job ID: 1685915200053477376</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Confirmed this is occurring on Chrome only, not Safari or Firefox. Still a biggie tho

**Comment by Julesssss** [comment]
[This PR ](https://github.com/Expensify/App/pull/22752)introduced the regression, I'm going to revert it to unblock the deploy.

**Comment by Julesssss** [comment]
Deployed to staging after being CP'd. Removing the blocker label

**Comment by Julesssss** [comment]
No payment here

**Comment by Julesssss** [comment]
Hi @adelekennedy could you please just pay reporting bonus to @tranvantoan-qn please.

**Comment by tranvantoan-qn** [comment]
@adelekennedy 
I've applied for the job, thank you!

**Comment by adelekennedy** [comment]
done!

**Comment by tranvantoan-qn** [comment]
Accepted the offer!

**Comment by adelekennedy** [comment]
paid! Can we close this up or are their other payments I should issue?

**Comment by tranvantoan-qn** [comment]
There is no C+ or other contributors for this issue, so only the payment for me is enough
