### ISSUE TITLE
Emoji - Emoji name is autocompleted even wrong word (:smmile:) is used

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Go to any chat
3. Type :smmile:

## Expected Result:
Wrongly written emoji like :smmile: should be unrecognized by app

## Actual Result:
Emoji name is autocompleted even wrong word (:smmile:) is used

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1e6e443b-8a9c-42c6-b59d-28e58327dfdd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by Victor-Nyagudi** [comment]
As @hungvu193 stated, I also noticed autocorrect corrects the spelling which results in the autocompleted emoji. 

I wouldn't consider this to be a bug. If anything, it looks like it could prove useful to the user in situations where they mistype the emoji name, unless maybe this behavior is undesired.

**Comment by anmurali** [comment]
OOO for 10 days

**Comment by JmillsExpensify** [comment]
I don't consider this a bug either, similarly experienced the OS auto-correcting and that accounting for the behavior. Closing.
