### ISSUE TITLE
[Tracking] Safari-only bugs in NewDot

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#23088]
Coming from [here ](https://expensify.slack.com/archives/C01GTK53T8Q/p1689623872647439)and [this bug](https://github.com/Expensify/App/issues/22885), let's gather all Safari-only bug reports here so we can try to fix them upstream and/or more holistically.    
cc @thienlnam 

## Safari-only bug reports
- https://github.com/Expensify/App/issues/22885
- https://github.com/Expensify/App/issues/23001 
- https://github.com/Expensify/App/issues/23142
- https://github.com/Expensify/App/issues/24286
- https://github.com/Expensify/App/issues/25537
- https://github.com/Expensify/App/issues/26049

**Comment by mallenexpensify** [comment]
Added a new one yesterday

**Comment by dylanexpensify** [comment]
@mallenexpensify am I right that we should add safari only bugs here and place them on hold?

**Comment by mallenexpensify** [comment]
@dylanexpensify , yes, please add safari-only bugs here

**Comment by mallenexpensify** [comment]
Tracking issue for now

**Comment by mallenexpensify** [comment]
Need to share this tracking issue in the #contributor-plus so folks know it exists

**Comment by mallenexpensify** [comment]
Still need to address a path/plan for safari-only bugs

**Comment by mallenexpensify** [comment]
Soon

**Comment by mallenexpensify** [comment]
Need to address soon :/

**Comment by mallenexpensify** [comment]
It's Friday at 4:30, hoping to prioritize soon

**Comment by mallenexpensify** [comment]
Proposed a few options in #bug-zero 
https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the individual safari-only issues and keep this tracking issue open.  If/when we decide to work on these, we'll reopen the individual issues.

**Comment by mallenexpensify** [comment]
No action, likely close soon unless I can find a wave/VIP these would be part of
