### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Android - User is able to click on download button on share code page after modal shows up if user is clicks rapidly and app crashes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND on android
2. Go to settings > share code
3. Click on the download button rapidly multiple times
4. Do step 3 until app crashes

## Expected Result:
 User should not be able to click on the download button more than once then the confirmation modal should show up. App should not crash if user clicks on download button multiple of times

## Actual Result:
User is able to click on the download button more than once even after the confirmation modal shows up if user is clicking on the download button rapidly multiple of times. And if user continues to do this for a few seconds app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2daa39f4-cd0c-4eca-8cd8-b94c9618d3ce

https://github.com/Expensify/App/assets/93399543/0b910f37-85f1-466b-8075-77cc936ddf13

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689664399381639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea9db9c8634d571d</li>
        <li>Upwork Job ID: 1681825807519490048</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
<li>Nathan-Mulugeta | Reporter | 25722312</li>
</ul></li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
>So, it's not about quickly pressing the download. We can even reproduce this issue by downloading the same report attachment and 2FA codes > 30 times.

Okay nice. This is a nice legit bug.

**Comment by madmax330** [comment]
Let's do it for all platforms to keep it consistent.

**Comment by twisterdotcom** [comment]
Payment summary:
@parasharrajat will be paid via newDot $1500
@bernhardoj will be paid via Upwork $1500: https://www.upwork.com/nx/wm/offer/26030844
@Nathan-Mulugeta will be paid via Upwork $250: https://www.upwork.com/nx/wm/workroom/34308785/overview

**Comment by twisterdotcom** [comment]
All paid.

**Comment by JmillsExpensify** [comment]
Review the details for @parasharrajat. Approved for payment in NewDot based on the BZ summary above.

**Comment by jasperhuangg** [comment]
@kidroca Thanks! Normally we leave regressions for the person who implemented the solution to fix. @bernhardoj Please fix the regression!
