### ISSUE TITLE
[$1000] Web - Old Paypal username appears even after deleting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Paypal page using link https://staging.new.expensify.com/settings/payments/add-paypal-me
2. Add or edit username and click on save button
3. From payments page click on Paypal username and delete it
4. Click on Add payment method button and choose Paypal option

## Expected Result:
Old Paypal username should not show

## Actual Result:
Old Paypal username appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.42-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c39d4bc9-b7ff-4729-8401-5f1f8be412b5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689660873381289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01564b9340e7c3d9e9</li>
        <li>Upwork Job ID: 1681650980433195008</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by eVoloshchak** [comment]
@hungvu193, could you revert the PR and check if the bug is still present?
If not, yeah, let's spin up the PR to fix it

**Comment by kevinksullivan** [comment]
Was able to reproduce on staging

**Comment by sobitneupane** [comment]
Issue no longer reproducible.

**Comment by kevinksullivan** [comment]
Closing out
