### ISSUE TITLE
[$1000] New chat - Keyboard is closed after selecting an user on search and user selection flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23108]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account
2. Tap on the green + button
3. Select "New group" option
4. In the search field, type a query that has multiple results
5. While the keyboard is open, select a random user from the search list

## Expected Result:
The keyboard remains open and focused after selecting a user from the search list

## Actual Result:
Keyboard is closed after selecting a user from the search list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a7f8457a-cac2-462c-9aea-200e2884c6a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014dcf81d748ab8722</li>
        <li>Upwork Job ID: 1681663127802388480</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Reproduced

**Comment by bfitzexpensify** [comment]
Good call @hoangzinh, agreed. Given the intentional decision there I think we can close this out.
