### ISSUE TITLE
Security  icon's size is not consistent to others icon's size

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23109]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open https://staging.new.expensify.com/ & login to app
2.Go to settings
3.Compare  the size of security lock icon to other icons
4.Observe that, security icons size is not same as other's icon
## Expected Result: 
Security lock icon's size should be exactly same as the other's icons size
## Actual Result: 
Security lock icon's size is different than the , other's icons size

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-17 at 3 15 43 PM](https://github.com/Expensify/App/assets/43996225/f8c4fc49-05a1-4dcb-aba6-d74cdad53bb2)

https://github.com/Expensify/App/assets/43996225/ee8623f4-ac72-4b09-96ab-968b428ab88c

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/fcfa966d-3af2-49d5-bb6a-7a2202c226a7">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689587167568429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Security icon's size is not consistent to others icon's size

### What is the root cause of that problem?
SVG content of Lock Icon is small

### What changes do you think we should make in order to solve the problem?
Use new SVG file

```javascript
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	viewBox="3.5 1 12.5 15" shape-rendering="geometricPrecision" text-rendering="geometricPrecision">
	<path
		d="M13.732666,7.551462v-2c0-2.2-1.8-4-4-4s-4,1.8-4,4v2h-1c-.6,0-1,.4-1,1l-.016631,3.412203c0,1.7.751309,1.939349,2.451309,1.939349h7.186729c1.7,0,2.361962-.239349,2.361962-1.939349l.016631-3.412203c0-.6-.4-1-1-1h-1Zm-2,0v-2c0-1.1-.9-2-2-2s-2,.9-2,2v2h4Z"
		clip-rule="evenodd" fill-rule="evenodd" />
</svg>
```
<img width="324" alt="image" src="https://github.com/Expensify/App/assets/137529618/9692f3cd-f1e5-40b2-8610-230dea8c5c9b">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Nikhil-Vats** [comment]
@shawnborton is this a bug? The size of all icons is 20x20 but the size of each SVG is different. Other SVGs have different widths and heights too.

**Comment by shawnborton** [comment]
This is not a bug, each icon is using a 20x20 box here.
