### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] Web - Unauthorized Task Reopening by Anonymous User in Incognito Mode- Inconsistency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a room in public mode
2. Assign a task to yourself
3. Mark the task to completion
4. Go to share code > copy the link
5. Open the link in incognito mode
6. Open the assign task thread
7. Click on the check button once
8. Verify you receive not authorized message
9. Click on the check button twice (very fast-two clicks) (Very Imp)
10. Verify the task was reopened
11. Verify the “reopened‘ message
12. Go to the actual test account and verify that the task was not opened. (inconsistent)
Note-(Double click on the check button to reopen it, its tricky)

## Expected Result:
 Anonymous users in incognito mode should not have the ability to reopen tasks in the chat interface.

## Actual Result:
Anonymous users in incognito mode able reopen tasks by double clicking on the check button with a task reopened button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (34)](https://github.com/Expensify/App/assets/93399543/89fd6ef7-3548-4a6f-9ac3-7935e24daf76)

https://github.com/Expensify/App/assets/93399543/569a16f1-7554-42fd-bdd3-6bd78b670e73

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689547160425739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011877db7acb0d69f6</li>
        <li>Upwork Job ID: 1681607804571918336</li>
        <li>Last Price Increase: 2023-07-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26118584</li>
<li>avi-shek-jha | Reporter | 26118590</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Okay I misunderstood that comment, adjusted

**Comment by greg-schroeder** [comment]
Awaiting proposal review cc @rushatgabhane

**Comment by rushatgabhane** [comment]
> Unauthorized Task Reopening by Anonymous User in Incognito Mode- Inconsistency

@dukenv0307 @Nodebrute could you please rephrase the problem. I don't understand it

**Comment by rushatgabhane** [comment]
Anyway, I like @dukenv0307's [solution](https://github.com/Expensify/App/issues/23114#issuecomment-1640692011) to nudge the user to login to perform a Task related action.
C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
Agree. Disabling can lead to a confusing UX. We should instead nudge the user that they need to sign in to perform that action.

**Comment by rushatgabhane** [comment]
@Nodebrute both solutions disable action and redirect to login are valid.
But disabling a button implies that the user cannot perform that action, and they'll be left wondering why they cannot click a particular button.

We could instead redirect them to login, so that they can perform a particular action like clicking the button. I hope this makes sense, thanks 🙇

**Comment by greg-schroeder** [comment]
Still on hold

**Comment by luacmartins** [comment]
still holding

**Comment by twisterdotcom** [comment]
Can we unhold this now?

**Comment by rushatgabhane** [comment]
@luacmartins I like @dukenv0307's [proposal](https://github.com/Expensify/App/issues/23114#issuecomment-1640692011)
🎀 👀 🎀

**Comment by luacmartins** [comment]
Agreed that the proposal looks good. Assigning @dukenv0307.

**Comment by greg-schroeder** [comment]
Awaiting deploy to staging > prod

**Comment by greg-schroeder** [comment]
A regression occurred so this is going to reset

**Comment by greg-schroeder** [comment]
Yes I see now, it was just one of the possible options

**Comment by greg-schroeder** [comment]
I'm not sure what's up with the automation... maybe it's delayed for some reason? the date would be 9/4 if it doesn't work

**Comment by greg-schroeder** [comment]
@dukenv0307 payout date would have been 9/4 but that was a holiday. So it's today! I'll take care of it

**Comment by greg-schroeder** [comment]
Issue Participants:

Issue reported by: @avi-shek-jha
Contributor: @dukenv0307
C+: @rushatgabhane 

Was this issue merged in time to be eligible for the speed bonus? ✅ 
Were their any regressions? ❌ 

Payment summary:

Reporter: $250
Contributor: $1,500
C+: $1,500

**Comment by greg-schroeder** [comment]
@rushatgabhane The automation didn't work on this issue for some reason. With that said, can you complete the normal checklist for this re: finding source PR/regression test etc. etc.

**Comment by greg-schroeder** [comment]
Thanks @rushatgabhane

**Comment by JmillsExpensify** [comment]
$1,500 payment for @rushatgabhane approved based on BZ summary.

**Comment by greg-schroeder** [comment]
@rushatgabhane just need to finish up the checklist then we can close this out!

**Comment by greg-schroeder** [comment]
Hey @rushatgabhane do you mind finishing the checklist on this one? been sitting as a wip for a while <3

**Comment by rushatgabhane** [comment]
completed the checklist https://github.com/Expensify/App/issues/23114#issuecomment-1715203559 (finally 😅 )
