### ISSUE TITLE
[$1000] User's name remains in the LHN after deleting their first message in a group chat, requiring a manual refresh to remove it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23122]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to userA's account.
2. Navigate to "New group"
3. Choose userB and other users to create the group.
4. Open another browser and log in to userB's account.
5. Open the group chat.
6. Return to userA's account.
7. Send a message in the group chat and then delete it.
8. Check the LHN from userB's account.
9. Notice that userA's name still appears in the LHN with an empty message.
## Expected Result:
After deleting the first message in the group chat, the user's name should be removed from the LHN, and the message "This is the beginning" should be displayed
## Actual Result: 
The user's name is not removed from the LHN after deleting the first message in the group chat. A manual refresh is required to remove it
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/22bd72a3-ddc4-4654-99ec-aa37c12542ff

![Screenshot 2023-07-17 at 2 46 56 PM](https://github.com/Expensify/App/assets/43996225/2bf1523b-14e8-441a-87c6-fb9a48ad5787)

https://github.com/Expensify/App/assets/43996225/08299974-2a59-4be9-92de-77ff3636b08e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689587169715599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d9840ff7aeaab66</li>
        <li>Upwork Job ID: 1681660488287084544</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment]
its not the same bug you have mentioned

**Comment by ayazhussain79** [comment]
Here is the same bug https://github.com/Expensify/App/issues/21056 that i have reported before https://github.com/Expensify/App/issues/21810 one this https://github.com/Expensify/App/issues/23122 bus is not same

**Comment by s77rt** [comment]
@samh-nl Thanks for the proposal. Your RCA is correct and solution makes sense. I think we need to make the BE fix first. @conorpendergrast Can you please assign an internal engineer here?

**Comment by s77rt** [comment]
@ginsuma Thanks for the proposal. I think it's the same as @samh-nl.

**Comment by s77rt** [comment]
@c3024 Indeed same root cause. I will ask how we should handle this.

**Comment by muttmuure** [comment]
Going to handle it over [here](https://github.com/Expensify/App/issues/21810)

**Comment by ayazhussain79** [comment]
@muttmuure @s77rt please check that this is the root case https://github.com/Expensify/App/issues/21056 i have reported before this one https://github.com/Expensify/App/issues/21810

**Comment by s77rt** [comment]
@ayazhussain79 Looks similar but have a different root cause.
