### ISSUE TITLE
 Login - Infinite loading screen when trying to login after closing account on another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open/login same account on separate devices, device A and device B
2. Using device B, select Settings, Security and then close account
3. User is logged out of device A and enters credentials for different account

## Expected Result:
User is logged in account after entering Magic code

## Actual Result:
After entering magic code, an infinite loading sign is given and user in unable to log in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2a8c6e49-a2d6-4f3e-b712-1d66d9ccc246

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by isabelastisser** [comment]
I cannot reproduce this, I can log into a different account with no issues.
