### ISSUE TITLE
[HOLD ON #22589] [$1000] DEV: Web- Console Error on Display Name Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In Dev go to http://localhost:8080/
2. Open your browser console
2. Navigate to Settings > Profile > Display Name

## Expected Result:
No console error

## Actual Result:
Console error displayed:
Warning: TextInput contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.42-9
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ee0d41d-2354-4cc7-bfb1-d40f53e65d37

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689683515386629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c91f4e75ba03ad5</li>
        <li>Upwork Job ID: 1681414222129561600</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
<img width="1440" alt="Screenshot 2023-07-19 at 2 26 58 AM" src="https://github.com/Expensify/App/assets/78416198/89e1c8c7-8506-472f-9383-8379b0708478">

Reproducible.

**Comment by jliexpensify** [comment]
Hi @danieldoglas I don't have a DEV environment, but are you able to reproduce this and let me know? Thanks in advance!

**Comment by danieldoglas** [comment]
@jliexpensify it is reproducible

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Getting error for using `value` and `defaultValue` props together in TextInput component via `Form.js` file.

### What is the root cause of that problem?
- The root cause of the problem is that we are not removing `defaultValue` prop when cloning the Component in `Form.js` file.

### What changes do you think we should make in order to solve the problem?
- Adding `defaultValue: undefined` to the `Form.js` file's React.cloneElement function fixes the issue and it doesn't break as we are already initializing the `value` prop to `defaultValue` in the `Form.js` file.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jliexpensify** [comment]
Cheers @danieldoglas - if you want to be unassigned as the Engineer, lmk! Otherwise I'll keep you on this for the credit?

**Comment by Nikhil-Vats** [comment]
This is being fixed [here](https://github.com/Expensify/App/pull/22589#issuecomment-1631053037)

**Comment by jliexpensify** [comment]
Awesome, thanks! I might keep this open until it gets deployed - that seems to be the process.

**Comment by s77rt** [comment]
Still on hold

**Comment by jliexpensify** [comment]
Still on hold

**Comment by jliexpensify** [comment]
Awesome, thank you @Nikhil-Vats ! I'll need to pay out @rayane-djouah a reporting bonus though.

**Comment by jliexpensify** [comment]
Ah, thank you @aimane-chnaif - you're correct. Unfortunately, you don't qualify for a bonus @rayane-djouah .
