### ISSUE TITLE
[$500] [HOLD for payment 2023-09-06] [Custom Status] Display status emojis in the LHN (including the user's own status)

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#23132]
# Part of the Custom Status project
Main issue: https://github.com/Expensify/App/issues/16350
Doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit#bookmark=id.dm0yu67h9vq8
Project: https://github.com/orgs/Expensify/projects/59/views/1

# Display status emojis in the LHN
This issue focuses on showing user status in the LHN in 2 places:
1. The user's own status show appear in the top right of the LHN near the profile picture. When pressed, this will bring the user to the custom status page. When hovering this emoji on web/desktop, a tooltip will be shown with the emoji and the status text
<img width="219" alt="2023-07-18_15-06-00" src="https://github.com/Expensify/App/assets/42391420/072f84b7-4a59-4bf8-b855-38b03603c084">
<img width="461" alt="2023-07-18_15-10-13" src="https://github.com/Expensify/App/assets/42391420/e3052bf3-787c-49b5-adb8-75c0f513a019">

2. Other user's statuses will be shown next to their name in the LHN chat list
<img width="222" alt="2023-07-18_15-06-10" src="https://github.com/Expensify/App/assets/42391420/c25314ba-225b-42a8-8703-62f048142c57">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5ffc19f1b06509d</li>
        <li>Upwork Job ID: 1701267094553931776</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
No update here, but work has started on the base PR!

**Comment by stitesExpensify** [comment]
Base PR is in review!

**Comment by stitesExpensify** [comment]
Hey @burczu this hadn't been marked as external when you reviewed the PR. If you want to apply as the C+ we will get it paid out ASAP!

**Comment by burczu** [comment]
Hey @stitesExpensify! I'm from Callstack, so payments via UpWork for my C+ work does not apply. But thanks ;)

**Comment by stitesExpensify** [comment]
Oh 🤦 Thanks!
