### ISSUE TITLE
[HOLD for payment 2023-08-21] [Custom Status] Add Main Custom Status page for setting / manually clearing status

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#23130]
# Part of the Custom Status project
Main issue: https://github.com/Expensify/App/issues/16350
Doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit#bookmark=id.dm0yu67h9vq8
Project: https://github.com/orgs/Expensify/projects/59/views/1

# Main Custom Status Pages
This issue will cover the main pages required to set and clear a status, specifically:
1. Adding the "status" option to the profile page
<img width="207" alt="2023-07-18_14-44-39" src="https://github.com/Expensify/App/assets/42391420/2dd8793a-06d3-4a94-af60-0c3bf3b3e247">

2. Creating the new "CustomStatusPage" page _without the ability to set a clear after time_ but will include the save and manual clear buttons
<img width="213" alt="2023-07-18_14-44-48" src="https://github.com/Expensify/App/assets/42391420/34701aa1-a90f-4314-a168-8567ec7833d9">

3. Creating the new "SetCustomStatusPage" page
<img width="218" alt="2023-07-18_14-45-03" src="https://github.com/Expensify/App/assets/42391420/e82a9bf1-e343-46ae-8dfa-6f4fafb061e6">

4. Creating the new "large emoji picker" page that appears when the user clicks the emoji button
<img width="219" alt="2023-07-18_16-16-20" src="https://github.com/Expensify/App/assets/42391420/41d03c0b-a05f-4e1b-b762-27ef3bee0886">

**Comment by stitesExpensify** [comment]
No action required here @shawnborton you've already been involved in the design doc.

**Comment by stitesExpensify** [comment]
Work on this has started!

**Comment by shawnborton** [comment]
We don't have an animation for this yet, so it will just be a static svg for the time being.

**Comment by perunt** [comment]
Okay got it, thanks!

**Comment by shawnborton** [comment]
Not overdue, waiting for payment to be confirmed.

**Comment by muttmuure** [comment]
Does this need an Upwork payment? Is @perunt from an agency or are they a contributor?

**Comment by muttmuure** [comment]
Ya Taras is from Margelo, so I don't think we need to pay out anything here
