### ISSUE TITLE
[$1000] [Attachment] is displayed for few seconds when we send text and delete after attachment URL

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any image
4. Open the image and while in preview, copy the URL
5. Send the URL as message
6. Send any other message after it
7. Delete the message sent in step 6 and observe in LHN that it displays '[Attachment]' for few seconds
## Expected Result: 
App should display the link in LHN if we delete message sent after link
## Actual Result: 
App displays [Attachment] for few seconds in LHN if we send attachment preview URL, send any message and delete the message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/de82b075-f24f-413a-a2b9-6c6bdda612be

https://github.com/Expensify/App/assets/43996225/0844f2a1-c432-478f-b891-eb63c8202179

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689591097666779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cd286f37f975acc</li>
        <li>Upwork Job ID: 1683459725479931904</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
The backend returns the following result
![image](https://github.com/Expensify/App/assets/126839717/9760a478-6c83-4130-893f-3dddf8eb96ed)

**Comment by NicMendonca** [comment]
reproducible 👍

**Comment by railway17** [comment]
Just want to make sure whether displaying `[Attachment]` after step 5 is correct or not.
Could you confirm here, @kavimuru ?
Thanks

**Comment by NicMendonca** [comment]
@railway17 yes, `[Attachment]` should be in the preview. Is that what you are asking?

**Comment by jjcoffee** [comment]
Looks like a BE issue as it returns [Attachment] as `lastMessageText` for the initial pasted image URL (step 5):

![image](https://github.com/Expensify/App/assets/27287420/cabc28da-ded8-4f58-8a3c-7482cf6374ed)

But then when we delete the message in step 7, the BE response changes `lastMessageText` to the image URL:

![image](https://github.com/Expensify/App/assets/27287420/680f5518-dea9-4e96-90ea-352206a45c49)

FWIW I'm not sure if it makes sense for [Attachment] to display in step 5 as this doesn't happen when pasting other image URLs.

**Comment by NicMendonca** [comment]
Okay, I am going to close. I don't think this is a material impact on how a end user uses the product.

**Comment by dhanashree-sawant** [comment]
For step 5 in LHN, it should actually display the link instead of '[Attachment]'. For this particular issue, end user will see [Attachment] in LHN and would expect it to be downloadable attachment but when they would open the report, they would only see link. It will kind of confuse them, that is the impact currently I think it would be on end user.

**Comment by dhanashree-sawant** [comment]
Hi @NicMendonca, ping your feedback

**Comment by kbecciv** [comment]
Re-open for discussion:
Link of attachment displayed as [Attachment] in LHN
Action Performed:
1- copy a link of any attachment
2- paste it on another chat
Expected Result: LHN should display the plain link
Actual Result: LHN displays [Attachment]
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1692720291552499
[attachment.webm](https://github.com/Expensify/App/assets/93399543/3cff09eb-916b-4aab-8c42-e4159417c8b5)

**Comment by NicMendonca** [comment]
@kbecciv I still don't think this should be prioritised.
