### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] [Custom Status] Display status emojis in chats

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#23134]
# Part of the Custom Status project
Main issue: https://github.com/Expensify/App/issues/16350
Doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit#bookmark=id.dm0yu67h9vq8
Project: https://github.com/orgs/Expensify/projects/59/views/1

# Display status emojis in chats
This issue will cover showing a user's status in chats. When a user has a status set, their chosen emoji will show up next to their name. On web/desktop this will be hoverable and have a tooltip.
<img width="218" alt="2023-07-18_15-15-30" src="https://github.com/Expensify/App/assets/42391420/f4c99d5d-012e-4fd5-9689-a4e4622f5278">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101ef684f004accb9</li>
        <li>Upwork Job ID: 1691901546692476928</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
No update here, but work has started on the base PR!

**Comment by stitesExpensify** [comment]
Base PR is in review!

**Comment by Santhosh-Sellavel** [comment]
@stitesExpensify Assign me issue when you get a chance thanks!

**Comment by greg-schroeder** [comment]
Okay so this isn't a typical issue - looks like Margelo implementation and an internally created issue. Only payment that needs to be done would be fore @Santhosh-Sellavel for reviewing. You can make a request in NewDot for the standard $1k afaict.

**Comment by greg-schroeder** [comment]
Leaving this for @JmillsExpensify to confirm for payment then we can close

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,000 payment approved via NewDot based on BZ summary.
