### ISSUE TITLE
Bank account - Back arrow is missing in the personal info onfido page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23144]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22628
## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Workspace > any workspace > Bank account > Step 3: Personal information.

## Expected Result:
Back arrow should be present

## Actual Result:
No back arrow in the onfido verification page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.21

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6132992_4](https://github.com/Expensify/App/assets/78819774/ff004cc5-ab41-4815-be82-e964f6992cd8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by faizansahib** [comment]
simply use an Image Icon

**Comment by faizansahib** [comment]
simply use an Image Icon
[faizan.akash99@gmail.com](mailto:faizan.akash99@gmail.com)
https://www.upwork.com/freelancers/~01e34ac222e73068fb
