### ISSUE TITLE
[HOLD #23088 Safari-only] iOS - Truncation dots ... doesn’t appear after the word Line 2

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22777
## Action Performed:
1. Login to any account and open the FAB menu by pressing + icon.
2. Click Assign task.
3. Enter a title and the following description:
Line 1
Line 2
Line 3

## Expected Result:
Verify that truncation dots ... appear after the word Line 2

## Actual Result:
Truncation dots ... doesn’t appear after the word Line 2

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.17

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/315376e6-54c9-4a60-bc3f-a97540dab3d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by mallenexpensify** [comment]
![IMG_9599](https://github.com/Expensify/App/assets/22508304/4ba95047-2985-4a29-985c-4550b3dba68f)

iOS app isn't loading for me :(   I was able to test on Safari and got the three dots, the only way I could do was by pasting though, if I tapped `Return`, it went to the next screen vs the next line. 


> This is not a bug. Rather, this is the native behaviour on iOS!

@aimane-chnaif , do you know why iOS is different for Safari and native app?

**Comment by mallenexpensify** [comment]
Added this to the below and putting on hold
- https://github.com/Expensify/App/issues/23088

**Comment by mallenexpensify** [comment]
Still on hold, might raise a 'safari-only' discussion soon-ish

**Comment by mallenexpensify** [comment]
Safari-only bug, on hold

**Comment by mallenexpensify** [comment]
Still on hold
- #23088

**Comment by mallenexpensify** [comment]
still on hold..

**Comment by mallenexpensify** [comment]
Safari-only hold

**Comment by mallenexpensify** [comment]
Still held on safari-only...

**Comment by mallenexpensify** [comment]
Safari-only

**Comment by mallenexpensify** [comment]
Addressed today in #bug-zero internally.

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
