### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] Profile -  OfflineIndicator doesn't appear on AvatarCrop Modal.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23165]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Go to Profile => Click user photo => upload photo => choose any photo.
3. Turn off the internet connection.
4. Notice there's no OfflineIndicator at bottom.

## Expected Result:
OfflineIndicator should appear at the bottom of screen.

## Actual Result:
OfflineIndicator doesn't appear at the bottom

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fb6a9568-8aa4-4321-9323-d7a87d52b116

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689669952378799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f624632378686b5c</li>
        <li>Upwork Job ID: 1681955679382212608</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25948540</li>
<li>hungvu193 | Reporter | 25948542</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We're not wrapping our `AvatarCropModal` inside `ScreenWrapper` which caused the issue:
https://github.com/Expensify/App/blob/ffe659e387502ca446cd3f3088f1e681f2c3d937/src/components/AvatarCropModal/AvatarCropModal.js#L364-L370
### What changes do you think we should make in order to solve the problem?
Wrap the `AvatarCropModal` content inside ScreenWrapper:
```javascript
        <Modal
            onClose={props.onClose}
            isVisible={props.isVisible}
            type={CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED}
            onModalHide={resetState}
        >
      <ScreenWrapper>
      // Modal content
      </ScreenWrapper>
       </Modal>
```

### What alternative solutions did you explore? (Optional)
N/A

<details><summary>Result</summary>
<img width="371" alt="Screenshot 2023-07-18 at 15 58 35" src="https://github.com/Expensify/App/assets/16502320/fab2c7a4-7b0a-4eff-93fd-b0594285f65e">

</details>

**Comment by kamaljitSharma21** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - OfflineIndicator doesn't appear on AvatarCrop Modal

### What is the root cause of that problem?
We Havent added `OfflineIndicator` from components at [bottom after save button](https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/components/AvatarCropModal/AvatarCropModal.js#L436) in AvatarCropModal

### What changes do you think we should make in order to solve the problem?

            ...
            <Button
                success
                style={[styles.m5]}
                onPress={cropAndSaveImage}
                pressOnEnter
                text={props.translate('common.save')}
            />
            <OfflineIndicator containerStyles={[styles.mh5, styles.mb3]} /> // Add OfflineIndicator Component here
        </Modal>

By doing above changes in AvatarCropModal will allow us to show offline indicator.

Result: 
![result-image](https://github.com/Expensify/App/assets/98891986/9de108b8-f540-4888-b2b9-f3003f5d3bf2)


### What alternative solutions did you explore? (Optional)

NA

**Comment by kadiealexander** [comment]
This doesn't need 2 Bug0 teammates! Going to unassign myself since @dylanexpensify was assigned for the new feature, but if anyone needs help, please let me know!

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by kamaljitSharma21** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Profile - OfflineIndicator doesn't appear on AvatarCrop Modal
> 
> ### What is the root cause of that problem?
> We Havent added `OfflineIndicator` from components at [bottom after save button](https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/components/AvatarCropModal/AvatarCropModal.js#L436) in AvatarCropModal
> 
> ### What changes do you think we should make in order to solve the problem?
> ```
>         ...
>         <Button
>             success
>             style={[styles.m5]}
>             onPress={cropAndSaveImage}
>             pressOnEnter
>             text={props.translate('common.save')}
>         />
>         <OfflineIndicator containerStyles={[styles.mh5, styles.mb3]} /> // Add OfflineIndicator Component here
>     </Modal>
> ```
> 
> By doing above changes in AvatarCropModal will allow us to show offline indicator.
> 
> Result:
> 
>  Record_2023-07-19-17-51-56.mp4 
> ### What alternative solutions did you explore? (Optional)
> NA


@benjaminbennet and @dylanexpensify can you please take a look at this proposal?

**Comment by dylanexpensify** [comment]
@eVoloshchak mind reviewing proposal please?

**Comment by dylanexpensify** [comment]
@eVoloshchak bump!

**Comment by dylanexpensify** [comment]
@hungvu193 similar as in dupe?

**Comment by ahmedGaber93** [comment]
# Proposal
https://github.com/Expensify/App/issues/24046#issuecomment-1661948235

My proposal in similar issue is the same as the proposal here, but it covers all other places that have this issue.
1. CountrySelectorModal
2. AvatarCropModal
3. YearPickerModal
4. StateSelectorModal

Last line of my proposal for CountrySelectorModal
> this issue may also need to fixed in this places AvatarCropModal YearPickerModal StateSelectorModal

**Comment by eVoloshchak** [comment]
The fix is pretty straightforward, the first proposal was posted by @hungvu193 on Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689670754777139?thread_ts=1689669952.378799&cid=C049HHMV9SM), proposal looks good to me
(re-posted [here](https://github.com/Expensify/App/issues/23165#issuecomment-1659490197) also)

🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
Next time!

**Comment by eVoloshchak** [comment]
> Based on my calculations, the pull request did not get merged within 3 working days of assignment.

I don't think that's correct, 2023-08-05 and 2023-08-06 weren't business days, this was a weekend

**Comment by dylanexpensify** [comment]
Ah bonus will apply then!

**Comment by dylanexpensify** [comment]
today is the day!

**Comment by dylanexpensify** [comment]
Payment summary:
- Reporter: @hungvu193 $250
- Contributor: @hungvu193 $1,500
- Contributor+: @eVoloshchak $1,500

[Upwork Job](https://www.upwork.com/jobs/~01f624632378686b5c). Please apply!

**Comment by dylanexpensify** [comment]
updating today!

**Comment by dylanexpensify** [comment]
@hungvu193 @eVoloshchak did you apply?

**Comment by dylanexpensify** [comment]
Nice! Payments sent! TY!

**Comment by JmillsExpensify** [comment]
Reviewed the details for @eVoloshchak. $1,500 approved for payment via NewDot based on BZ summary.
