### ISSUE TITLE
Web - A placeholder icon is displayed instead of Concierge icon when opening a share code link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Open that tab where account B is signed in
3. Flag the message as Bullying
4. Open the tab where account A is signed in
5. Click on 'Reply in thread' icon of the flagged message
6. Click on chat header
7. Click on share code button
8. Click on 'Copy URL to clipboard button
9. Switch to the window where account B is signed in
10. Open new tab > paste the URL to the new tab > press enter

## Expected Result:
 * Concierge icon should be displayed
* Thread header with '[Deleted message]' should be displayed

## Actual Result:
 * A placeholder icon is displayed
* Blank thread header is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.41-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 2023-07-19 11-48-26.webm](https://github.com/Expensify/App/assets/93399543/04dce646-a554-48c7-a674-317557877f11)

**Expensify/Expensify Issue URL:**
**Issue reported by:** React JS Developer | Software QA Analyst | GH: @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689522638888119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
@Nodebrute - can you clarify where this is expected behaviour, thank you!

**Comment by sophiepintoraetz** [comment]
Hmm, @Nodebrute - I'm not sure we're talking about the same thing - I don't think we're referring to the share code but the avatar icon here:
<img width="1287" alt="image" src="https://github.com/Expensify/App/assets/42940078/fdc229ff-e785-41ce-be84-0b4af58a5a82">

**Comment by sophiepintoraetz** [comment]
I am not able to reproduce this.
https://github.com/Expensify/App/assets/42940078/146c42b3-d940-407f-9df2-d30906871dbc
