### ISSUE TITLE
Console error displayed when redirected to plaid portal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23177]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #22473

## Action Performed:

1. Create workspace if not created
2. Click on Workspaces in setting in left panel
3. Choose Reimbursement
4. Click the Connect bank account button
5. Click the Connect online with Plaid

## Expected Result:
Verify that it redirect to plaid portal and no error is displayed in console.

## Actual Result:
Console error displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/06c38e0d-ceaa-4c93-991b-a3fbe5cc730f

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
Plaid's "link-initilize.js" is having some kind of issue. Not to handle on our end.

**Comment by laurenreidexpensify** [comment]
agree with @jeet-dhandha, closing
