### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-02] Web - Space between the last message and time is more

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23187]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any message

## Expected Result:
Space between the last message and time should be less

## Actual Result:
Space between the last message and time is more

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (42)](https://github.com/Expensify/App/assets/93399543/8b21f24d-f5c3-4ba1-95b5-5f78fb310f9f)

![image (41)](https://github.com/Expensify/App/assets/93399543/31f41fe3-1ae5-4613-adde-8c5368df7caa)

![Screenshot 2023-07-19 at 4 01 20 PM](https://github.com/Expensify/App/assets/93399543/a70075c8-4681-411a-9502-5e230c557178)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689762849787649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01349987aae27d2cdd</li>
        <li>Upwork Job ID: 1691158136170807296</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
More space between the composer and last message 

### What is the root cause of that problem?
We are not taking out the padding here which we used to do earlier.
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/pages/home/report/ReportActionsList.js#L172

### What changes do you think we should make in order to solve the problem?
As the flex direction is the column-reverse we need to take out the top padding by updating the condition to
`shouldShowReportRecipientLocalTime && styles.pt0`

**Comment by jasperhuangg** [comment]
This looks like a regression, I'm going to see if I can find the PR that caused this and get the original author to fix it cc @marcochavezf 

This also doesn't need to be a deploy blocker since it's a minor display bug

**Comment by jasperhuangg** [comment]
cc @grgia this seems to be a regression from [your PR](https://github.com/Expensify/App/pull/22562), do you mind fixing this in a follow up?

**Comment by grgia** [comment]
PR up

**Comment by gadhiyamanan** [comment]
@grgia @marcochavezf can we assign any BZ member for payment ?

**Comment by marcochavezf** [comment]
Hi @puneetlath, can you make the payment here, please? https://github.com/Expensify/App/issues/23187#issuecomment-1674315212

**Comment by puneetlath** [comment]
Yes, sure thing. If I understand correctly from what I'm seeing this was handled internally, correct? So we need to pay $250 to @gadhiyamanan for the bug report and $1k to @situchan for C+. Does that sound right?

**Comment by situchan** [comment]
> Yes, sure thing. If I understand correctly from what I'm seeing this was handled internally, correct? So we need to pay $250 to @gadhiyamanan for the bug report and $1k to @situchan for C+. Does that sound right?

yes correct

**Comment by puneetlath** [comment]
Ok thanks for confirming. Sent offers.

**Comment by gadhiyamanan** [comment]
@puneetlath offer accepted, thanks!

**Comment by puneetlath** [comment]
All paid!
