### ISSUE TITLE
 Unable to make calls on Zoom and Google Meet.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Launch the new Expensify app.
2.	Open a chat.
3.	Click on the call icon.
4.	Click on Zoom or Google Meet.
## Expected Result: 
The call should be connected to the chat member.
## Actual Result: 
Zoom Application was launched but a call was not made.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7846a729-cbac-4228-b0d6-38bd4bc0b3b0

![Snip - Meet - ~new - Google Chrome](https://github.com/Expensify/App/assets/43996225/a9f7358b-bb2a-493a-809f-36406b8db7e2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** not added by the contributor
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689607954471729
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I don't think this is a bug. The call button creates a new Zoom or Google Meet call, but unless I'm mistaken it's not designed to do anything else like invite the other DM member to the call. 

If I'm missing that, or misunderstanding, we can reopen this!
