### ISSUE TITLE
Desktop- Developer tools option not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Update and launch the desktop app
2. Click view on menu options

## Expected Result:
User see option to enable developer tools

## Actual Result:
No option to enable developer tools

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f36ce4af-4aac-4fa1-99b9-050f3b0be69a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by jasperhuangg** [comment]
Just merged a fix for this here: https://github.com/Expensify/App/pull/23192

gonna have it CP'd
