### ISSUE TITLE
Web - User can access Two-factor authentication (Step 2: Verify) without copying the code, resulting in an empty code being displayed with copy button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23198]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Security > Two-factor authentication.
2. Click on the "Copy" button and proceed to the next step.
3. Copy the page URL and send it to a chat.
4. Open the link from the chat.
5. Observe that the user is able to open the page without copying the code, and an empty code is displayed on both pages.

## Expected Result:
The user should not be able to access the Two-factor authentication page without copying the code. Alternatively, if the user opens the page from the chat without copying the code, copy button should not be displayed

## Actual Result:
The user is able to access the Two-factor authentication (Step 2: Verify) page without copying the code, resulting in an empty code being displayed and also copy button displayed even code is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9ff0f4e0-b53f-43bc-be6f-077fdfef0542

https://github.com/Expensify/App/assets/93399543/ce1228d0-fbd4-41dc-abfc-bf817a04491c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689717017885469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
duplicate
