### ISSUE TITLE
Line number mismatch in task title

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23207]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button => assign task
2. Input multiple line title
3. Next
4. In page confirm task click title section, Observe that the title has only 1 line
## Expected Result: 
Title should be multiple lines when clicking on title
## Actual Result: 
title has only 1 line but when create multiple line

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fe37f432-b77b-49a5-ad60-f94d4da73d2d

https://github.com/Expensify/App/assets/43996225/62eb675a-1758-415c-94a0-e3c1e1f3fe05

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689634358039939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Title should be multiple lines when clicking on the title
### What is the root cause of that problem?
The problem here is that we don't allow multiple lines for input
https://github.com/Expensify/App/blob/ab3d0e876e311ed1ce3cd859ad6dd77a5d8e3cdf/src/pages/tasks/NewTaskTitlePage.js#L95-L102
### What changes do you think we should make in order to solve the problem?
We need to add an attribute to allow multiple line input:
```
autoGrowHeight
textAlignVertical="top"
containerStyles={[styles.autoGrowHeightMultilineInput]}
```
And update onEntryTransitionEnd so that the cursor is at the end
```
<ScreenWrapper
    onEntryTransitionEnd={() => focusAndUpdateMultilineInputRange(inputRef.current)}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment]
Closing this in favor of https://github.com/Expensify/App/issues/23025
