### ISSUE TITLE
Update OpenReport command to accept reportActionID

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23218]
# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.1olneh5hdq7
Project: https://github.com/orgs/Expensify/projects/62/views/1

# <Feature Description>
Update `OpenReport` Auth command to accept a reportActionID parameter. If this parameter is present, it should return the (reportActionsLimit / 2)  reportActions immediately preceding the given reportActionID in the report, and ((reportActionsLimit / 2) - 1) reportActions immediately following the given reportActionID. If no reportActionID is provided, OpenReport will return the latest reportActionsLimit reportActions on the report, as it does today.

# Manual Test Steps
None for now

# Automated Tests
Add tests to OpenReportTest to test this functionality.

**Comment by roryabraham** [comment]
I think this should be on HOLD for https://github.com/Expensify/App/issues/23216 because I'm essentially setting us up to query in both directions instead of just `ASC` or `DESC`

**Comment by roryabraham** [comment]
Picking this back up as a high priority

**Comment by roryabraham** [comment]
Picking this up right meow

**Comment by roryabraham** [comment]
This is supposed to be my top priority but I don't have a PR up yet. Will try to get a PR up either tonight or tomorrow

**Comment by roryabraham** [comment]
Working on this today

**Comment by roryabraham** [comment]
Thanks @aldo-expensify for taking this over. There are actually a few tasks here:

- Update Auth's `Report::getActionList` to implement the `BOTH` direction, such that it will fetch `reportActionsLimit / 2` reportActions in the DESC direction, `reportActionsLimit / 2` reportActions in the ASC direction, concat them together, and return the result.
- In the PHP layer of `OpenReport` right [here](https://github.com/Expensify/Web-Expensify/blob/20a545c1a5f76ff8b7c2d1d38027b3e50ac5b69d/lib/ReportAPI.php#L4974-L4975) we're calling `getHistory` to fetch reportActions for the report. It would be difficult to migrate this to Auth because of all the post-processing that's happening in PHP for that. However, this is problematic because right now it's using the old query. We need it to use the new query for this to work. We can coerce it to use the new query by passing a [reportActionID](https://github.com/Expensify/Web-Expensify/blob/bb7ffadd57651ab64f95e5d54a95d7cb7dda23a7/lib/Report.php#L2858), but right now we're currently using the old (slow) query by default. So we should fix that.
- Finally, in the PHP layer of `OpenReport`, we just need to pass the `reportActionID` and `order=BOTH` to fetch just the page we want somewhere in the middle

**Comment by roryabraham** [comment]
> However, this is problematic because right now it's using the old query. We need it to use the new query for this to work. We can coerce it to use the new query by passing a [reportActionID](https://github.com/Expensify/Web-Expensify/blob/bb7ffadd57651ab64f95e5d54a95d7cb7dda23a7/lib/Report.php#L2858), but right now we're currently using the old (slow) query by default. So we should fix that.

After testing, it turns out this is not true. Even though `reportActionsCreated` is empty, `shouldKeyByReportActionID` is hardcoded to `true` [here](https://github.com/Expensify/Web-Expensify/blob/bb7ffadd57651ab64f95e5d54a95d7cb7dda23a7/lib/Report.php#L4047), so it uses the new query and Auth will find the created [here](https://github.com/Expensify/Auth/blob/main/auth/lib/Report.cpp#L5149-L5156). We could potentially make this more efficient by skipping [this query](https://github.com/Expensify/Auth/blob/f62274461d87aaab82e7f0eda7f2f03733e75f4a/auth/lib/Report.cpp#L5154) and instead set `actionCreated` to:

- The epoch if the order is ASC
- The an ISO time 1000 years in the future if the order is DESC

---

Also @aldo-expensify it's important that `order=BOTH` won't work or make sense if `reportActionID` is missing

**Comment by aldo-expensify** [comment]
Draft PR: https://github.com/Expensify/Auth/pull/8683

**Comment by aldo-expensify** [comment]
Will work on the Web-E  part again tomorrow

**Comment by aldo-expensify** [comment]
Web-E part was merged

**Comment by roryabraham** [comment]
This is done
