### ISSUE TITLE
Create GetOlderActions and GetNewerActions Auth commands

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23217]
# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://github.com/Expensify/App/issues/20282
Project: https://github.com/orgs/Expensify/projects/62/views/1

# <Feature Description>
Create two new Auth commands:

- GetOlderActions
- GetNewerActions

Each command should take the following parameters:

- int reportID
- int reportActionID

and return a page of 50 reportActions on the report older or newer than the given reportAction w/ the given reportActionID.

# Manual Test Steps
None for now

# Automated Tests
We should create automated tests for these Auth commands.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea4951b804e3dc03</li>
        <li>Upwork Job ID: 1681808013506129920</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This is back-end only.

**Comment by roryabraham** [comment]
Was thinking that this needs to be on HOLD for https://github.com/Expensify/Auth/pull/8345, but I guess not actually

**Comment by marcaaron** [comment]
I can dig into this one.

**Comment by marcaaron** [comment]
Started looking into this a bit here: https://github.com/Expensify/Auth/pull/8412/files

Gonna do the "get older" one first since that closely resembles what we already do in NewDot. And then follow up with the `GetNewerActions` (which I'm not sure if there are any existing queries for).

One question I have is whether we will have to support "public reports" or not. These APIs have changed a bit since I last worked on them. But, I'd assume the answer to that question would be... yes. Mostly asking since the closest thing we have to a `GetOlderActions` is probably `ReadOldestAction` and I noticed we are including the personal details [here](https://github.com/Expensify/Web-Expensify/blob/5e6e4f720ac36be372694a8c4aeb3695246483b6/lib/ReportAPI.php#L4619-L4623) for some reason.

**Comment by marcaaron** [comment]
I _think_ for now we don't need to worry about public reports (but might need to in a follow up). I looked at the code and we should still be calling `OpenReport` when it's a public report so I'd presume the user will:

- First call `OpenReport` 
- After, have an `authToken` that can be used to get the action list via `GetNewerActions` or `GetOlderActions`

@marcochavezf I see you implemented some of those changes in `OpenReport` so I'm curious if you know the answer to that question or can think of anything else we might need to return with these actions when we start paginating them in this new style?

**Comment by marcaaron** [comment]
PR for this is ready-ish. I am not sure what else to add to it for now and it looks like it's working correctly.

**Comment by marcaaron** [comment]
>and return a page of 50 reportActions on the report older or newer than the given reportAction w/ the given reportActionID.

@roryabraham does it matter if this is inclusive or exclusive i.e. the reportActionID should be returned with the page? IMO I think it should be inclusive otherwise the API could return nothing at all (which is maybe a bit weird).

**Comment by marcochavezf** [comment]
> I _think_ for now we don't need to worry about public reports (but might need to in a follow up). I looked at the code and we should still be calling `OpenReport` when it's a public report so I'd presume the user will:
> 
> * First call `OpenReport`
> * After, have an `authToken` that can be used to get the action list via `GetNewerActions` or `GetOlderActions`
> 
> @marcochavezf I see you implemented some of those changes in `OpenReport` so I'm curious if you know the answer to that question or can think of anything else we might need to return with these actions when we start paginating them in this new style?

For public rooms, we call `OpenReport` to check if the report is public to then send the authToken and credentials to the user (which is the important data), so they can log in as a regular user (call the same API commands, etc.) but with the restricted anonymous authToken type. 

So I think when an unauthenticated user opens a public room, we can do the pagination as a regular user right after the authToken is sent to the app. And probably, we could ignore the public report data in the initial `OpenReport` call.

**Comment by marcaaron** [comment]
>For public rooms, we call OpenReport to check if the report is public to then send the authToken and credentials to the user (which is the important data in this action), so they can log in as a regular user (call the same API commands, etc.) but with the restricted anonymous authToken type.

👍  awesome thanks for the explanation

>So I think when an unauthenticated user opens a public room, we can do the pagination as a regular user right after the authToken is sent to the app.

👍 

>probably, we could ignore the public report data in the initial OpenReport call.

Not sure if I got the meaning of this part. Which data would we ignore and why?

**Comment by marcaaron** [comment]
Linked PR for this is deployed now. I need to take the Web-E PR off hold now. But that has a different issue so I'll leave updates there!
