### ISSUE TITLE
Update Auth to include previousReportActionID in reportActions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23216]
# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.byjchsk1pmv7
Project: https://github.com/orgs/Expensify/projects/62/views/1

# <Feature Description>
We need to update the following Auth commands to include `previousReportActionID` on all reportActions:

- `OpenReport`
- `Get::reportActionsListByActionIDs`

However, it's important that at this stage this field _is not_ included on reportActions in Onyx.

# Manual Test Steps
Make these calls and verify via PHP logs that the `previousReportActionID` is included on _all_ reportActions fetched (including the oldest one fetched at a time).

# Automated Tests
Update existing Auth tests:

- `OpenReportTest`
- `GetTest`

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcfa55033b96234f</li>
        <li>Upwork Job ID: 1681805631919005696</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This will be back-end only, so removing @rushatgabhane

**Comment by roryabraham** [comment]
Started a draft PR: https://github.com/Expensify/Auth/pull/8345. Probably need to move some of the logic from C++ to SQL

**Comment by roryabraham** [comment]
I'm actively working on this

**Comment by roryabraham** [comment]
Making kind of slow progress here, just debugging the Get test and trying to figure out whyyy it's not giving me what I want 😠 

This is definitely one of my top priorities and I'm _hoping_ that I can get it done before going Wednesday-Friday this week

**Comment by roryabraham** [comment]
Actively working on the PR

**Comment by roryabraham** [comment]
I know it's perhaps seemed like there's been slow progress here, but it's not for lack of trying. I've actually spent a lot of time trying to get this working. I've made a lot of progress and should be close to having the PR ready for review

**Comment by roryabraham** [comment]
At long last the PR is ready for review, it was a doozy: https://github.com/Expensify/Auth/pull/8345

**Comment by roryabraham** [comment]
Requesting a [query timing](https://github.com/Expensify/Auth/pull/8345). Going to use what is probably my longest chat in NewDot as the reportID.

```sql
SELECT r.created,
       r.action,
       r.message,
       a.email,
       a.accountID,
       r.reportActionID,
       rNVP.reportID AS childReportID,
       LAG(r.reportActionID, 1, (
         SELECT reportActionID
         FROM reportActions
         WHERE reportID = 65129373
           AND r.created < '2023-07-01 00:00:00.000'
         LIMIT 1
       )) OVER (
         ORDER BY
           CASE WHEN r.action = 'CREATED' THEN 1 ELSE 2 END,
           r.created ASC,
           r.reportActionID ASC
       ) AS previousReportActionID
FROM reportActions r
INNER JOIN accounts a ON r.accountID = a.accountID
LEFT JOIN reportNameValuePairs rNVP
  ON rNVP.name = 'parentReportActionID'
  AND rNVP.value = CAST(r.reportActionID AS TEXT)
WHERE r.reportID = 65129373
  AND r.created > '2023-07-01 00:00:00.000'
  AND (
    CASE
      WHEN (JSON_VALID(r.message) AND JSON_TYPE(r.message, '$.whisperedTo') = 'array')
      THEN (
        EXISTS (SELECT 1 FROM JSON_EACH(JSON_EXTRACT(r.message, '$.whisperedTo')) WHERE value = 8931541)
        OR r.accountID = 8931541
      )
      ELSE 1
    END
  )
  AND r.action IN ('ADDCOMMENT')
ORDER BY
  CASE WHEN action = 'CREATED' THEN 1 ELSE 2 END,
  created ASC,
  reportActionID ASC
LIMIT 50;
```

**Comment by roryabraham** [comment]
Got the PR finalized and the query timed + optimized on Friday. Now just awaiting review

**Comment by roryabraham** [comment]
@chiragsalian approved but left some notes. Going to work on those changes and hopefully get this merged real soon. Was focused on deploy fires the last couple days

**Comment by roryabraham** [comment]
PR updated and ready for re-review

**Comment by perunt** [comment]
It's not overdue. I hope Chirag will have time to review it.

**Comment by roryabraham** [comment]
This is done
