### ISSUE TITLE
[HOLD for payment 2023-11-02] Implement bidirectional pagination in ReportActionsList

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23223]
HOLD on:

- https://github.com/Expensify/App/issues/23220
- https://github.com/Expensify/App/issues/23221

# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.tgiglcuu8pr9
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1)

# <Feature Description>
For bidirectional scrolling, we need to enable the addition of new data to the chat from both ends. The top end utilizes built-in methods `onEndReachedThreshold` and `onEndReached`. We need to start using `onStartReached` for the bottom end as well.

We should call the `GetOlderActions` API `onEndReached` and `GetNewerActions` API `onStartReached`.

Also, this PR should enable the `CheckForPreviousReportActionID` migration being built [here](https://github.com/Expensify/App/issues/23221).

# Manual Test Steps
TBD

# Automated Tests
TBD

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by roryabraham** [comment]
cc @perunt

**Comment by perunt** [comment]
Here we go! 🚀

**Comment by perunt** [comment]
It's not overdue, the PR is ready and waiting for another perf improvements PRs to be merged.

**Comment by roryabraham** [comment]
We're actively reviewing the PR for this

**Comment by perunt** [comment]
It's not overdue. Currently in reviewing process

**Comment by perunt** [comment]
This PR is actively reviewing

**Comment by roryabraham** [comment]
Assigning new feature and @s77rt for C+ payment

**Comment by roryabraham** [comment]
@sonialiap can you please issue C+ review payment to @s77rt then close this out?

**Comment by sonialiap** [comment]
@s77rt offer sent

**Comment by webmaster1022** [comment]
Hi, How are you?
May I work with this issue?
Thanks!

**Comment by sonialiap** [comment]
@webmaster1022 this issue has been resolved. Please check out the [Open issues with the `Help Wanted` label](https://github.com/Expensify/App/labels/Help%20Wanted) for issues available to be worked on.

**Comment by s77rt** [comment]
@sonialiap Accepted! Please make sure the payment is $125 (for two regressions: https://github.com/Expensify/App/issues/30423 and https://github.com/Expensify/App/issues/30729). Thanks!

**Comment by sonialiap** [comment]
Thanks @s77rt , payment of $125 sent ✔️
