### ISSUE TITLE
Create API commands: GetOlderActions and GetNewerActions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23224]
HOLD on https://github.com/Expensify/App/issues/23217 ✅ 

# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section:
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1)

# <Feature Description>
Add new API endpoints `GetOlderActions` and `GetNewerActions` to use the new auth commands of the same name.

# Manual Test Steps
TBD

# Automated Tests
TBD

**Comment by marcaaron** [comment]
I can grab this too since it's the logical follow up to adding the commands in Auth.

**Comment by marcaaron** [comment]
I think this should be done relatively quickly. Gonna try to get some tests written today and do some more testing to make sure the API endpoints are ready to go for Margelo.

**Comment by marcaaron** [comment]
This was merged I think we are just waiting for it to hit production.

**Comment by roryabraham** [comment]
This is on prod, so I'm going to close it out as I work on a project update. Thanks @marcaaron!
