### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] MEDIUM: New Feature: Support file uploads on mobile (e.g. PDFs, docx, etc.)

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#23228]
We're initially building support for receipt images uploads, but we need to circle back and add the ability to upload PDF or other file types. 

Internal context in [this Slack thread](https://expensify.slack.com/archives/C057F53HR40/p1689801964517139?thread_ts=1689799930.604339&cid=C057F53HR40).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cfad31fbc4738d9d</li>
        <li>Upwork Job ID: 1702030509135847424</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 26877236</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Anything needed from me here?

**Comment by JmillsExpensify** [comment]
Nah, I'll remove you.

**Comment by JmillsExpensify** [comment]
Still clean-up for wave4

**Comment by JmillsExpensify** [comment]
Same same

**Comment by JmillsExpensify** [comment]
For this one, I think we should go in a direction where we prioritize images, but we allow for non-image uploads by choosing a file-type option. Here's how WhatsApp does it and that works pretty well. 

![IMG_E65358CEE961-1](https://github.com/Expensify/App/assets/1127863/a7ea2a38-dba6-456d-b005-166c725e3924)

**Comment by dylanexpensify** [comment]
Agree, I think that approach feels the most intuitive

**Comment by dylanexpensify** [comment]
@sobitneupane can we please review @hoangzinh's proposal?

**Comment by JmillsExpensify** [comment]
Interesting proposal. I could see the argument that this could be easily accommodated via a document upload flow for now, and then we leave it at that for now. @AndrewGable also putting this one on your radar.

**Comment by dylanexpensify** [comment]
thanks @JmillsExpensify! @AndrewGable mind weighing in on this when you have a free moment? 🙇‍♂️

**Comment by AndrewGable** [comment]
I like the proposal, I think it solves the issue in a simple way that is consistent with what we have now 👍

**Comment by sobitneupane** [comment]
Thanks for your [proposal](https://github.com/Expensify/App/issues/23228#issuecomment-1719733151) @hoangzinh.

Overall, proposal looks good to me. I believe it is better not to show "Take Photo" Option. @hoangzinh How will we preview the uploaded files (pdf, docs, etc.)?

**Comment by dylanexpensify** [comment]
Great! @sobitneupane awaiting your 🎀

**Comment by sobitneupane** [comment]
@hoangzinh Thanks for the update.

We have [an open issue](https://github.com/Expensify/App/issues/27680) to handle the case of not loading PDF files. 

[Proposal](https://github.com/Expensify/App/issues/23228#issuecomment-1719733151) from @hoangzinh looks good to me.  We already support file upload on Web. So, we expect the UI to be similar to that of Web.

🎀 👀 🎀 C+ reveiwed

**Comment by johnmlee101** [comment]
Looks great! Assigning!

**Comment by dylanexpensify** [comment]
@sobitneupane we feeling up for this now? Or should we get someone else on it?

**Comment by dylanexpensify** [comment]
paying today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @hoangzinh $500
- Contributor+: @sobitneupane 

Please apply!

**Comment by dylanexpensify** [comment]
Paid!

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/23228#issuecomment-1783390211

Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
@dylanexpensify can you please update your payment summary. It's missing an amount for @sobitneupane

**Comment by dylanexpensify** [comment]
Sorry!

Payment Summary:
- Contributor+: @sobitneupane $500

Please apply!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @sobitneupane based on comment above.
