### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD] Highlight linked comment

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23230]
HOLD on https://github.com/Expensify/App/issues/23229

# Part of the Comment Linking project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#bookmark=id.z8txm8vzzncc
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1)

# Feature Description
As described in the design doc, add a different background color when a comment is linked to (in the URL)

# Manual Test Steps
1. Link to a specific comment
1. Verify that the comment is highlighted

# Automated Tests
None

**Comment by Gonals** [comment]
not overdue

**Comment by peterdbarkerUK** [comment]
@situchan @roryabraham - am I correct here this should be $500 for reviewing https://github.com/Expensify/App/pull/27227?

**Comment by peterdbarkerUK** [comment]
(Switching to daily to make sure it gets paid as a priority)

**Comment by situchan** [comment]
@peterdbarkerUK yes $500 is correct

**Comment by peterdbarkerUK** [comment]
Ah dang it Melvin, this is sitting in my to-do queue this afternoon. Apologies for the delay @situchan, payment incoming.

**Comment by situchan** [comment]
No problem. Take your time. Thanks

**Comment by peterdbarkerUK** [comment]
Thanks Situ! Offer sent :)

**Comment by peterdbarkerUK** [comment]
my b yo

**Comment by situchan** [comment]
@peterdbarker I haven't received payment yet

**Comment by peterdbarkerUK** [comment]
Ugh, Thanks @situchan - payment sent. I know this has happened to you a few times now, I'm really sorry. A good workman shouldn't blame his tools, but damn UpWork's interface is a special kind of torture. Thanks for your patience and the bump!
