### ISSUE TITLE
Log in - Apple icon is not present

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/16723
## Action Performed: 
1. Open https://staging.new.expensify.com/

## Expected Result:
Apple icon is present and clickable, user is able to login using Apple ID

## Actual Result:
Apple icon is NOT present and space under "Sign in with" is not clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6134583_Screenshot_2023-07-20_at_02 26 58" src="https://github.com/Expensify/App/assets/78819774/dfd342a2-5ac0-4992-bd1d-98c743e6a0c6">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by robertjchen** [comment]
Yep!

**Comment by robertjchen** [comment]
We're working on it here: https://github.com/Expensify/App/pull/16723#issuecomment-1642724913

**Comment by jasperhuangg** [comment]
Hey gonna keep this open until a fix is CP'd

**Comment by marcochavezf** [comment]
Apple sign-in PR reverted
