### ISSUE TITLE
[HOLD][Cleanup] Remove unused ReadOldestAction API command

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#23232]
HOLD on all other issues in the Comment Linking project.

# Part of the <Project Name> project
Main issue: https://github.com/Expensify/App/issues/20282
Doc section: n/a
Project: [Comment Linking](https://github.com/orgs/Expensify/projects/62/views/1)

# Feature Description
After the Comment Linking project is completed, the ReadOldestAction API endpoint will be unused. So we can remove it.

# Manual Test Steps
none.

# Automated Tests
remove any associated tests as well

**Comment by AliYar-Khan** [comment]
@roryabraham Can i do this ?

**Comment by AliYar-Khan** [comment]
Contributor details
Your Expensify account email: aliyark145@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01816c0d7c4d888a0b
