### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Chat - Notification is NOT received in the main device after Control policy was created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account in New Dot in the testing device, validate it and stay logged in
2. Navigate to another tab and leave the ND tab in the background
3. Navigate to OldDot and login with account from Step 1
4. Create a Control or Collect policy

## Expected Result:
Notification is received in the main testing device from the #Admin Room

## Actual Result:
Notification is NOT received in the main testing device from the #Admin Room
#admins and #announce chats in ND tab in the background were not created (need a page reload, previously #admins and #announce were created without reload)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a89496c4-205b-4ba4-9abd-c0e18e2c0031

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01065f736ac1027416</li>
        <li>Upwork Job ID: 1683479352616787968</li>
        <li>Last Price Increase: 2023-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26417598</li>
</ul></li>
    </ul>
</details>

**Comment by hannojg** [comment]
This could be a regression from my PR:

- https://github.com/Expensify/App/pull/21406

looking into it!

**Comment by hannojg** [comment]
Taking my words back, the bug is reported on staging. The mentioned PR isn't on staging yet, so it can't have caused the issue!

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/pull/21406#issuecomment-1646352787 is deployed now FYI

**Comment by hannojg** [comment]
I can check later today if this PR caused the regression, yes!

**Comment by NicMendonca** [comment]
@hannojg any update?

**Comment by NicMendonca** [comment]
We're still waiting for proposals here. I am assuming you haven't found anything @hannojg?

**Comment by hannojg** [comment]
I haven't checked yet, no. Does anyone else have time to check, super booked right now

**Comment by NicMendonca** [comment]
@mananjadhav should we update price on this one?

@lanitochka17 are you still able to reproduce?

**Comment by mananjadhav** [comment]
I think we should confirm if it is reproducible, and then increase the price.

**Comment by mananjadhav** [comment]
@lanitochka17 Can you confirm if this is reproducible consistently?

**Comment by lanitochka17** [comment]
Issue reproducible in Build 1.3.57-1

https://github.com/Expensify/App/assets/78819774/15154665-011d-49a9-9b81-31e82916c2c6

**Comment by NicMendonca** [comment]
@mananjadhav any feedback on [this proposal](https://github.com/Expensify/App/issues/23234#issuecomment-1694380919)?

**Comment by mananjadhav** [comment]
Thanks for the bump, I'll review this later today. I'll have to test the proposal.

**Comment by mananjadhav** [comment]
Reviewed and I think @hungvu193's proposal will work. 

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment]
@hungvu193 Any updates on the PR here?

**Comment by NicMendonca** [comment]
@hungvu193 all good here?

**Comment by mananjadhav** [comment]
@hungvu193 Apologies I didn't understand what you mean by getting the link when clicking in OldDot.

**Comment by mananjadhav** [comment]
Thanks @mountiny @hungvu193 for helping on this one.

**Comment by NicMendonca** [comment]
@mananjadhav bump on the[ BZ checklist](https://github.com/Expensify/App/issues/23234#issuecomment-1756773773)!

**Comment by mananjadhav** [comment]
I think we already comment on this [PR](https://github.com/Expensify/App/pull/19053/files#r1346138021) regarding the problematic code. It looks like we've further updated this to `getReportName` in the [main](https://github.com/Expensify/App/blob/fd169e2a8184fd5bcac8535cae2ecc42ef0b6d19/src/libs/Notification/LocalNotification/BrowserNotifications.js#L113-L115).

This doesn't need any update in the process and neither do we need a regression test here.

**Comment by NicMendonca** [comment]
Cool! Thanks!

@hungvu193 you've been paid! @mananjadhav don't forget to request payment via Expensify 


> BZ Payment summary:
> 
> Reporter: N/A
> Contributor: @hungvu193 - $1,000 (paid via Upwork)
> Contributor +: @mananjadhav - $1,000 (paid via Expensify)

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @mananjadhav based on summary above.
