### ISSUE TITLE
[Performance] The Report screen has unnecessary rerenders

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#23253]
### Problem

The Report screen still has some unnecessary re-renders.

https://github.com/Expensify/App/assets/36083550/3e0c444c-aba0-4f2c-bafc-df014bb9d528

### Solution

Profile and diagnose where the re-renders are happening and try to remove the need for them, this will improve the general performance of the app and any animations which might be happening at the same time will be smoother

**Comment by mountiny** [comment]
Sorry for the ping Shawn, I am labelling this as new feature because I dont think its necessarily bug, its more so an improvement to make the performance better.

**Comment by adamgrzybowski** [comment]
👁️ 👁️

**Comment by WoLewicki** [comment]
🚀

**Comment by adamgrzybowski** [comment]
It's possible that the onyx improvements will reduce this problem. If not we could look for other ways e.g. reduce rerenders if the report screen is not on the top of the stack

**Comment by mountiny** [comment]
@WoLewicki Any gameplan on this one as well, what are the next steps/ETA? Should we put this on hold for the onyx improvements?

**Comment by adamgrzybowski** [comment]
Wojtek is OOO today. From our discussion with Wojtek, I think we should wait for Onyx changes. BTW it looks like the video is broken

**Comment by WoLewicki** [comment]
Since onyx changes have been merged, we will take a look at it again after finishing the most urgent issues. cc @adamgrzybowski for us not to forget about it.

**Comment by mountiny** [comment]
Thanks, added this to the project

**Comment by mountiny** [comment]
@WoLewicki How is this one looking now

**Comment by WoLewicki** [comment]
I think the onyx changes have been reverted and we are waiting for the new PR to be merged (https://github.com/Expensify/App/pull/24041) or am I confusing the PRs?

**Comment by mountiny** [comment]
No that is the PR about to be merged again, you are correct. Wasnt sure if you were doing any investigation independent on that

**Comment by twisterdotcom** [comment]
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team.

**Comment by mountiny** [comment]
@kadiealexander not much action needed here so far

**Comment by kadiealexander** [comment]
Still on hold.

**Comment by mountiny** [comment]
@WoLewicki this is no longer on hold, what will be the next steps?

**Comment by WoLewicki** [comment]
Since there have been improvements for `onyx` and some of the unnecessary code has already been removed, with the addition of with the changes from PR mentioned in https://github.com/Expensify/App/issues/22996, I think we are in rather good state currently.

**Comment by mountiny** [comment]
Alright I will close this in favour of https://github.com/Expensify/App/issues/22996
