### ISSUE TITLE
[HOLD for payment 2023-08-01][$1000] Chat - App crashed while clicking on non-existed mention email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat.
2. Mention an non-existed email and press enter to send
3. Click on that mention
4. Notice that app is crashed

## Expected Result:
App shouldn't be crash after clicking mention

## Actual Result:
App crashed while clicking on non-existed mention email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/49f28a20-c9f7-4588-8885-67ca6d8caf58

https://github.com/Expensify/App/assets/93399543/567e8a12-8798-4331-83ca-316a321df013

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689839180058799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01100b87f8a6a775ce</li>
        <li>Upwork Job ID: 1681996917328850944</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Not overdue. Payment will happen tomorrow. I'll review today and note payments amounts.

**Comment by lschurr** [comment]
@sobitneupane - could you work on the checklist for this one?

**Comment by lschurr** [comment]
Payout summary:

- Bug reporter: @hungvu193 $250
- Contributor: @hungvu193 $1500
- Contributor+: @sobitneupane $1500

@hungvu193 will be paid in Upwork
@sobitneupane - be sure to request payment in Newdot.

**Comment by lschurr** [comment]
@sobitneupane could you also work on this checklist so that we can close this out? https://github.com/Expensify/App/issues/23250#issuecomment-1648822162

**Comment by lschurr** [comment]
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1691101805984369

**Comment by sobitneupane** [comment]
Sorry for the delay @lschurr. I will try to get to this issue by EOD.

**Comment by lschurr** [comment]
Just bumping @sobitneupane :)

**Comment by lschurr** [comment]
Thanks @sobitneupane - going to close this one!

**Comment by JmillsExpensify** [comment]
Reviewed the payment details for @sobitneupane. $1,500 is approved for payment in NewDot.
