### ISSUE TITLE
[$1000] IOU - The link in the email to respond to the IOU request from ND redirects to OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Expensify stg application
2. Click on the FAB button
3. Click the "Request Money" button.
4. Enter any amount
5. Click on the "Next" button
6. In the search, enter any mail not previously registered in the application and with the ability to access it
7. Click on the "Request {currency}{amount}" button.
8. In the mail from the account from point 6 check the mail (after 10 minutes)
9. Click on the link in the mail

## Expected Result:
The link in the post should redirect to the domain new.expensify.com

## Actual Result:
The link in the mail redirects to the domain expensify.com

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/25a298af-4c89-40d0-a5d1-e7a4e624d2c2

https://github.com/Expensify/App/assets/78819774/f0f5d22e-984f-441f-87e3-42718612a2c0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a3fb07ef7b36ddd</li>
        <li>Upwork Job ID: 1682369722566324224</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Money requested, waiting on the email notification.

**Comment by himanshuragi456** [comment]
looks like a backend issue, how are emails being sent?

**Comment by situchan** [comment]
@garrettmknight I think this should be fixed in backend. Can you please add Engineering to assign engineer?

**Comment by garrettmknight** [comment]
Yep!

**Comment by thienlnam** [comment]
Haven't gone about updating this internally yet

**Comment by thienlnam** [comment]
Moving this to a weekly since IOUs are only really used internally right now

**Comment by garrettmknight** [comment]
@thienlnam looks like this should have gone overdue last week, have you taken a look?

**Comment by thienlnam** [comment]
Not yet, been prioritizing wave5 stuff. Since IOUs are only used internally, I moved this to a weekly

**Comment by garrettmknight** [comment]
@thienlnam can you get to this one this week? It seems like a pretty simple one.

**Comment by thienlnam** [comment]
Yeah I can take a look this week

**Comment by garrettmknight** [comment]
@thienlnam can you give a lil Friday love to this one?

**Comment by thienlnam** [comment]
Sorry, I had been meaning around to this but now with wave 5 crunch time I'm going to push this off. The logic is a little tricky with how we decide the signature and this is low value right now

https://expensify.slack.com/archives/C05DWUDHVK7/p1692667290100579?thread_ts=1692658684.398019&cid=C05DWUDHVK7

**Comment by garrettmknight** [comment]
Still prioritizing Wave 5, we'll get back to this next week.

**Comment by thienlnam** [comment]
Still involved in other priorities

**Comment by thienlnam** [comment]
Same, though approved team is wrapping up so I can probably get to this end of next week

**Comment by garrettmknight** [comment]
@thienlnam now that we're done with Approved stuff can we get to this?

**Comment by thienlnam** [comment]
Yup, though I'm mostly OOO this week so I can get back to it next week when I'm back

**Comment by thienlnam** [comment]
Welp, looks like my procrastination has paid off. This is already fixed hahah 
<img width="683" alt="Screenshot 2023-10-10 at 3 59 24 PM" src="https://github.com/Expensify/App/assets/30609178/30aa85fd-bb76-45b8-87d9-d43602cee04b">
