### ISSUE TITLE
Contact methods - In offline, after pasting magic code, there is no loading icon on the button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
1. Tap on profile icon
2. Tap on profile
3. Tap on contact method
4. Tap on new contact method with green dot
5. Toggle off internet
6. Paste the magic code
7. Tap on verify button

## Expected Result:
In offline, after pasting magic code, tapping verify button, there must be the loading icon on the button

## Actual Result:
In offline, after pasting magic code, tapping verify button, there is no loading icon on the button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b59d6702-f5cc-44ec-b3d0-a211b222f1f7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by kbecciv** [comment]
@dylanexpensify Can you please request the TR update? TR link https://expensify.testrail.io/index.php?/runs/view/19380&group_by=cases:section_id&group_order=asc&group_id=229064
