### ISSUE TITLE
Connect Bank - The icons for passport and driver's license are not shown on the Personal information

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any workspace
3. Connect bank account
4. Add all bank, company and personal information
5. Observe that the icons for passport and driver's license are not visible

## Expected Result:
The icons should be visible

## Actual Result:
The icons are not visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (43)](https://github.com/Expensify/App/assets/93399543/e9c800df-da9b-4a3c-950a-2e504c7e9d33)

![94D383D4-731A-4C29-871E-BF315F543D2F](https://github.com/Expensify/App/assets/93399543/904aa497-2fba-48e7-af22-80453cf4526e)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689841394176949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Hm, I'm unable to reproduce this. Icons are showing for me on all platforms: 

<img width="272" alt="image" src="https://github.com/Expensify/App/assets/31225194/7a63feb1-fa16-495d-9ec8-44fcf3324010">

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/31225194/1d8501bb-dcf2-4ca2-b052-06f01af31e79">
