### ISSUE TITLE
[$1000] Log in - User able to login without magic code by deep linking

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Confirm you have the Desktop app installed and user is signed out
2. Open the Web app and log into any account that has a secondary login
3. Settings > Profile > Contact method
4. Select secondary contact method (non default contact method)
5. Copy the URL 
6. Open URL in new tab
7. Click "open in app" on the popup

## Expected Result:
Desktop app opens and login screen displayed

## Actual Result:
Desktop app opens and you are logged into the primary login account (without requesting magic link)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/acbadfc6-fa85-4d08-b5f9-a7b1e4eecb3e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec246ccc6dbd6059</li>
        <li>Upwork Job ID: 1683455553057615872</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Reproducible

**Comment by sonialiap** [comment]
Possibly related to (regression of?) https://github.com/Expensify/App/issues/22120

**Comment by shivamsn97** [comment]
Can I work on this?

**Comment by shivamsn97** [comment]
Contributor details
Your Expensify account email: shivamsn97@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~018b5c18feaa45fdce

**Comment by rohngonnarock** [comment]
Contributor details
Your Expensify account email: rohngonnarock@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/rahultheprajapati

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue

**Comment by sonialiap** [comment]
Not overdue, @JKobrynski is working on this 🎉

**Comment by sonialiap** [comment]
Btw, this looks like a system-wide issue, not just Settings > Profile > Contact method. I was able to log into my account with a URL from another page (I don't recall which)

**Comment by JKobrynski** [comment]
@sonialiap 
> Btw, this looks like a system-wide issue, not just Settings > Profile > Contact method. I was able to log into my account with a URL from another page (I don't recall which)

I was just about to ask, are we sure this is an issue? Any url under settings will redirect the user to the desktop app and automatically log him into the app. Should we prevent that from happening when the url contains another email (contact method)?

**Comment by JKobrynski** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We want to prevent users from being automatically logged into the desktop app with deep links. The original issue description mentioned this being the case for `/settings/profile/contact-methods/<email>/details` but according to @sonialiap's comment and my investigation, it happens for every route. 

If user is  logged in, deep links should work as usual. 

### What is the root cause of that problem?

When users are redirected from the web app to the desktop app via deep link, `shortLivedAuthToken` is extracted from the url in `<LogInWithShortLivedAuthTokenPage />` and then used for authentication.

### What changes do you think we should make in order to solve the problem?

We need to add some conditions to `<LogInWithShortLivedAuthTokenPage />` that would verify if user is already signed in or not. There would be two scenarios:

- **default** - if user is **signed in** to the desktop app deep link redirection will work as it used to
- **alternative** - if user is **not signed in** we will redirect to the sign in page

To check if user is signed in, we can use the same solution that was used in `<ValidateLoginPage />`, which is:

`const isSignedIn = Boolean(lodashGet(props, 'session.authToken', null));`

### What alternative solutions did you explore? (Optional)

None

**Comment by JKobrynski** [comment]
Melvin, no "Overdue" here, [proposal](https://github.com/Expensify/App/issues/23271#issuecomment-1655281074) is under review

**Comment by JKobrynski** [comment]
Proposal is awaiting review. @0xmiroslav

**Comment by rushatgabhane** [comment]
Why is this an issue? 

The user is already logged in the web app. I don't know the exact logic but clicking "open in app" passes the auth token to desktop app.

**Comment by sonialiap** [comment]
This is an issue because if user A logs into their account, copies link, shares with user B. Then user B can log into user A's account without knowing their login info. Unless you're copiloting into an account you shouldn't be able to log into someone's account with a link.

**Comment by sonialiap** [comment]
@0xmiroslav what are your thoughts on [my last comment](https://github.com/Expensify/App/issues/23271#issuecomment-1674812164)?

**Comment by sonialiap** [comment]
Sorry about the delay, I was OOO. 

I agree that we should correct this across all platforms. I cannot think of any scenario where we would want to allow this behavior so I don't think we need to have a discussion about it and can just solve it. Are you suggesting a discussion because we would need to build different solutions for every platform (i.e. we can't build one rule to apply to all platforms) so it would increase project scope?

**Comment by sonialiap** [comment]
Thanks for the clarification. I've [asked the team ](https://expensify.slack.com/archives/C01SKUP7QR0/p1693222024032719)for input on whether we should expand scope or open a new issue

**Comment by sonialiap** [comment]
The consensus from the team is to keep the solution to one issue. Ideally we'll find a contributor that can propose a solution to both, but if necessary we can combine a couple proposals

**Comment by sonialiap** [comment]
Still looking for proposals

**Comment by sonialiap** [comment]
Looking for proposals

**Comment by sonialiap** [comment]
looking for proposals. I posted in slack to see if we can get some traction there

**Comment by kacper-mikolajczak** [comment]
Hi @sonialiap I am Kacper from Callstack and I would like to continue working on that issue!

**Comment by kacper-mikolajczak** [comment]
Hi @sonialiap @0xmiroslav I went through discussion and I need a little bit of clarification from your end.

I am not exactly sure how alternative contact methods flow should work. From what I could find it enables:
- user to have multiple email addresses connected to one account, or
- multiple users (email addresses) to use the same account

Those two reasoning are almost identical from a technical point of view, but I am struggling to tell what is the real use case.

What would be the reason behind prohibiting user from logging in with the link that holds auth token (especially from a security standpoint), if the **account is shared by many users**?
If account is not shared, but it is just a convinience tool for user to **log in or access account from multiple email addresses**, then I don't see a reason for preventing user from being logged in at all.

Alternatively, if the reasoning above is a fallacy and the interaction should be held between two separate users ([as Sonia suggested in one of her messages](https://github.com/Expensify/App/issues/23271#issuecomment-1674812164)), then why token that lets user B authenticate creds of user A is passed with a link in the first place?

Thanks a lot for help here!

**Comment by sonialiap** [comment]
I just re-tested this and actually, I think this doesn't pose a risk of being authenticated into someone's primary login.

**test:**
1. log into your account (ex: main@)
2. navigate to Settings > Profile > Contact method
3. if you don't already have, add a secondary login (ex: secondary@)
4. click on secondary login (ex: secondary@)
5. copy the URL (it will include the SL's email: https://new.expensify.com/settings/profile/contact-methods/secondary%40gmail.com/details)
6. open an incognito tab and paste the URL - you will be redirected to the sign in page
7. log into a different account (ex: other@)
8. click "open in app" on the popup

**result:**
The desktop app opens and you're logged into the second account (other@). RHN briefly shows the screen for verifying the SL (secondary@) then changes to an error.

My initial understanding of the problem (from the problem statement and my testing, but now I'm not sure I tested it correctly when triaging this issue in July) was that the URL authenticated you into main@, but that's not the case. So there's no threat of being logged into someone else's primary login. The error in the RHN is a minor issue and the steps are an edge case so I don't think we actually need to do anything here.

Sorry @kacper-mikolajczak for unnecessarily bothering you! 🙈

**Comment by kacper-mikolajczak** [comment]
Hi @sonialiap, no worries at all! :D 

Thanks for double checking, as I am not yet that advanced in the project and needed your assistance here.

**Comment by sonialiap** [comment]
Thanks for questioning the issue. A fresh pair of eyes is always helpful 🙏
