### ISSUE TITLE
Dev: Console error appear when reload Workspace invite message page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Setting > workspaces > Select any workspace > members
2. Click on invite >  select any user > go to invite message page
3. Reload the page
## Expected Result: 
Console error shouldn't appear
## Actual Result: 
Console error appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 19-07-2023 11_11_13.webm](https://github.com/Expensify/App/assets/43996225/02cb75f0-8cb1-4ae3-8104-520a645b61b3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689740116433079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console error appears when reloading Workspace invite message page
### What is the root cause of that problem?
This error occurs because we pass both `defaultValue` and `value` props into TextInput
https://github.com/Expensify/App/blob/5419d9ba7bb33347160ff20fc061e48d914eac6e/src/pages/workspace/WorkspaceInviteMessagePage.js#L226-L227
### What changes do you think we should make in order to solve the problem?
We can remove `defaultValue` prop here to avoid the console error
https://github.com/Expensify/App/blob/5419d9ba7bb33347160ff20fc061e48d914eac6e/src/pages/workspace/WorkspaceInviteMessagePage.js#L226
### What alternative solutions did you explore? (Optional)

**Comment by Nikhil-Vats** [comment]
This is a dupe, it is already found and being fixed [here](https://github.com/Expensify/App/pull/22589#issuecomment-1630601016).
