### ISSUE TITLE
Desktop - Login - Magic link shows page with Magic code instead of prompt to open Desktop App

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Open Desktop App
2. Create new account
3. Got to validation email and copy magic link
4. Open new tab, paste magic link and change it to staging
5. Go to this Magic link

## Expected Result:
Prompt to open the Desktop App should appear

## Actual Result:
Magic code page loads instead of prompt to open Desktop App

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/17e48c22-5b39-4840-984f-1d6745d661df

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Hmm we disable them on unauthorized pages thinking that we were not cases where we prompt the user to open the desktop app there, but it seems there's indeed a case for this. @lindboe I'm afraid that we'd need to move the `DeeplinkWrapper` to `PublicScreens` again or come up with a solution to use them in both `PublicScreens` and `AuthScreens`.

**Comment by iwiznia** [comment]
Reverting the offending PR

**Comment by lindboe** [comment]
Yes, this means we'll need to instead block DeeplinkWrapper from activating on a certain list of routes. I think the ones that make sense are the dedicated desktop sign-in page, and the main sign-in page (to avoid prompting the user to go to the desktop app, then _back_ to the web app if they had wanted to sign in with Apple). I'll try again to confirm in Slack.

**Comment by marcochavezf** [comment]
Closing out since Apple sign-in PR was reverted

**Comment by lindboe** [comment]
I just tried to test this out on prod (new.expensify.com) as well to figure out what we need to support, and I noticed the same behavior of no redirect prompt Firefox on MacOS. Safari _does_ prompt to redirect that link. I'm not sure why the difference yet, as I haven't seen Firefox not trigger a deep link prompt when I would expect one.
