### ISSUE TITLE
Sign in - Apple sign in is looped

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23288]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/16723

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on "Sign in with apple"
3. Complete an Apple sign in process

## Expected Result:
User is logged into account via apple sign in

## Actual Result:
Nothing happens after completing the Sign in with apple - User remains at login screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/04d1629b-9079-4f79-95f0-9eda2e754a29

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal  - Team/ @niravkakadiya25
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
I think this is related to the env configuration for Apple sign-in redirect in staging. @lindboe is working on a fix [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689870357991509?thread_ts=1689837954.286229&cid=C049HHMV9SM).

**Comment by lindboe** [comment]
The fix is to update the redirect URI in config to be dynamic based on the CONFIG object using `NEW_EXPENSIFY_URL`. (Apple sign-in failing to close the window at the end is a sign that either the clientID or redirect URI was wrong.)

**Comment by lindboe** [comment]
Should be fixed for Android as well, but building and testing now

**Comment by marcochavezf** [comment]
Apple sign-in PR reverted
