### ISSUE TITLE
[HOLD for payment 2023-08-14] [$250] Chat - Red underline on some pronouns

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23303]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to profile > pronouns
2. Select something like Fae/Faer
3. Go back and open the pronouns again

## Expected Result:
Pronouns input should not show spelling error

## Actual Result:
Pronouns input shows spelling error by red underline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f2d42901-0a8d-4f2c-b1ba-fecb3dd20576

https://github.com/Expensify/App/assets/93399543/ce6a8fb0-c456-410d-ae1d-b512390b0319

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689845093487019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d19d5efab5b26952</li>
        <li>Upwork Job ID: 1682111824131657728</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>chiragxarora | Contributor | 25679429</li>
<li>chiragxarora | Reporter | 25679430</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Red underline on pronouns indicating error of spellings


### What is the root cause of that problem?

Root cause of the issue is that we are using `<SelectionListRadio/>` to render the pronouns

https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/pages/settings/Profile/PronounsPage.js#L107-L107

which uses a `<TextInput/>`

https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/components/SelectionListRadio/BaseSelectionListRadio.js#L222-L233 

<TextInput/> uses default value of `spellCheck` which it inherits from `autoCorrect` which has default value as true, thus spellCheck is true here

This causes the red underline on some pronouns which have wrong spellings according to the dictionary

### What changes do you think we should make in order to solve the problem?

We need to set spellCheck as false for the pronouns page since it has some non english words too

And we can do it in ways:
- either we can set spellcheck as false in the textinput of selectionlistradio itself, it will be added globally and affect all the lists using radio lists (although globally done won't be a bad choice since its being used in 2 more places with textinput: year picker and timezone select page, both of these can keep the spellcheck as off)
- or we can send a prop from pronouns page and do it conditionally just for the pronouns page
<details>
  <summary>Results</summary>

</details>

### What alternative solutions did you explore? (Optional)

None

**Comment by mountiny** [comment]
Coming from slack, this is really minor bug, making it $250 https://expensify.slack.com/archives/C049HHMV9SM/p1689872197554259?thread_ts=1689845093.487019&cid=C049HHMV9SM

**Comment by sakluger** [comment]
@mountiny @parasharrajat what do you think about @hungvu193's idea to fix multiple similar issues in one go? I like the concept of taking a more holistic approach, but don't have enough context on the issue to know if it makes sense in this situation.

**Comment by sakluger** [comment]
Also @hungvu193 could you link those other similar issues that you saw?

**Comment by mountiny** [comment]
I dont think we have to turn it on for all inputs but I think that it makes sense to do a little audit of inputs in the App and see where are similar inputs which we dont want to spellCheck

**Comment by mountiny** [comment]
That sounds good to me, Address probably could also be added.

All yours @sakluger @grgia 🙇

**Comment by mountiny** [comment]
I think with urgency bonus 50% it could be 375. its the same change just in different files.

**Comment by sakluger** [comment]
All sounds good to me! I'm going to assign @chiragxarora so they can get started on this one.

**Comment by sakluger** [comment]
Paid $500 to @chiragxarora (for bug report and Contributor payment).

@parasharrajat can you please complete the BZ checklist and request payment via newdot if you haven't already? Thanks!

**Comment by sakluger** [comment]
Sorry guys, I didn't notice that this one was ready because it stayed as a weekly.

I add a $125 bonus for @chiragxarora. 

**Summarizing payouts for this issue:**

Reporter and Contributor: @chiragxarora $250 + 375 = $625 (paid via Upwork)
Contributor+: @parasharrajat $375 (payable via Manual Request)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~01d19d5efab5b26952

Assigning @anmurali and @JmillsExpensify to approve NewDot payment.

**Comment by sakluger** [comment]
@JmillsExpensify is handling these, unassigning @anmurali

**Comment by grgia** [comment]
Not overdue, payments are being processed

**Comment by sakluger** [comment]
@parasharrajat just wanted to make sure, did you request yet?

**Comment by sakluger** [comment]
Asked for an update in expensify-open-source [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1693934694884099).

**Comment by sakluger** [comment]
@parasharrajat said he hasn't requested yet but is tracking outstanding payment requests, so we are okay to close.

**Comment by JmillsExpensify** [comment]
$375 payment for @parasharrajat is approved based on BZ summary.
