### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] Attachment - Loading showed every time even there's error displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send pdf that has password
2. Click on that pdf and enter wrong password, press Confirm now the error will show, press the Confirm button couple of times.
3. Notice that user's still able to submit the form even there's error visible.

## Expected Result:
 If there's an error, there shouldn't be a loading every time user clicked the button

## Actual Result:
Loading showed every time even there's error displayed when user click button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/03cbab93-ba1f-4840-9587-2b79a430e091

https://github.com/Expensify/App/assets/93399543/5c380bda-dc10-486e-8c7a-7a59ab11f908

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689849404574009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d38521264e441609</li>
        <li>Upwork Job ID: 1682123558641819648</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25680010</li>
<li>tienifr | Contributor | 25680013</li>
<li>hungvu193 | Reporter | 25680014</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
from @hungvu193 
### Please re-state the problem that we are trying to solve in this issue.
Password PDF Form: Still able to submit even when Form has error
### What is the root cause of that problem?
In out PDFPasswordForm, we're checking the validation here:
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/components/PDFView/PDFPasswordForm.js#L84-L92
If `validate` returned false then we disabled the submit:
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/components/PDFView/PDFPasswordForm.js#L69-L71
As we can see our validation function only validated the empty password, in this case when password was wrong, `validate` function still return true which caused the issue.
### What changes do you think we should make in order to solve the problem?
We also need to check if `isPasswordInvalid` is true then early return in out submit function.

```javascript
    validate() {
        if (!_.isEmpty(this.state.password) && !this.props.isPasswordInvalid) {
            return true;
        }
     // other code
    }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment]
Getting eyes on this 👍

**Comment by mollfpr** [comment]
@hungvu193 On multiple submissions after the password is invalid and clearing the input, it shows the required error.

https://github.com/Expensify/App/assets/25520267/347c5c29-7256-4d55-9ed1-8a0f760a5c9f

Meanwhile, @tienifr looks good and doesn't show any regression. I agree we should only set the password required error only on empty state password to avoid the above issue. Let's go with @tienifr [proposal](https://github.com/Expensify/App/issues/23301#issuecomment-1644908736) then.


🎀 👀 🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment]
bump @mollfpr on the above ^^^

I'm heading OoO until 8/14 so reassigning BZ to keep an eye on this. 

Upwork Job Hires are listed here — https://www.upwork.com/ab/applicants/1682123558641819648/hired; all contracts have been accepted 👍 

Assignment took place to @tienifr on July 21 and PR was reviewed on July 24, so they should be eligible for the 50% bonus

**Comment by mollfpr** [comment]
This issue is eligible for bonus speed. Jul 22 - 23 is the weekend.

The assignment on Jul 22, 2023, 01:00 AM GMT+7
The PR merged on Jul 25, 2023, 05:03 PM GMT+7

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


The regression test should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with any account
2. Go to any chat
3. Send a protected PDF file (i.e. PDF with password set)
4. Press that PDF and enter the wrong password
5. Press Confirm
6. **Verify** that an error appears
7. Press the Confirm button several times.
8. **Verify** that the button does not show loading state

**Comment by trjExpensify** [comment]
👋 Got assigned to cover here, but I've been OoO until today myself! 

Issued payments now, confirmed as being: 

- @hungvu193 $250 for the bug report 
- @mollfpr $1,500 for the PR review & #urgency bonus 
- @tienifr $1,500 for the fix & #urgency bonus 

As for the regression test, we have one for password protected PDFs, so I think we're good here for now 👍 

Closing this out! :)
