### ISSUE TITLE
No system message when editing a task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23302]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task and add assignee
2. Reassign the task to someone
## Expected Result:
Should include a system message indicating that it was reassigned

## Actual Result:
There is no message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/83d09139-3966-439e-87c2-9173326bc6fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689744951886999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecf0cd51093fcffd</li>
        <li>Upwork Job ID: 1682151598616768512</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This will have to be a mix of internal and external (We're currently not showing any system message when you edit the task, but we can surface that and include what was changed)

**Comment by MitchExpensify** [comment]
Reproduced (Task was originally assigned to Franc) 
<img width="475" alt="image" src="https://github.com/Expensify/App/assets/36425901/8a53c4d3-f044-439c-a9b0-93094150d3b0">

**Comment by MitchExpensify** [comment]
> This will have to be a mix of internal and external

What label do you recommend @thienlnam ?

**Comment by thienlnam** [comment]
This is actually a new feature, so let's make it internal first until we're ready to update it externally

**Comment by thienlnam** [comment]
Can handle the internal updates

**Comment by thienlnam** [comment]
We're making some changes to the assignee flow for this internal issue https://github.com/Expensify/Expensify/issues/299956 (Related to the privacy changes we need to make)

So let's hold this PR on that, so we don't have to re-do any of the work there

**Comment by MitchExpensify** [comment]
Still on hold for https://github.com/Expensify/Expensify/issues/299956

**Comment by MitchExpensify** [comment]
> Still on hold for https://github.com/Expensify/Expensify/issues/299956

Same

**Comment by MitchExpensify** [comment]
> Still on hold for https://github.com/Expensify/Expensify/issues/299956

Same

**Comment by thienlnam** [comment]
Same same

**Comment by thienlnam** [comment]
Still on hold for https://github.com/Expensify/Expensify/issues/299956

**Comment by MitchExpensify** [comment]
Still on hold for https://github.com/Expensify/Expensify/issues/299956

**Comment by MitchExpensify** [comment]
Still on hold for https://github.com/Expensify/Expensify/issues/299956

**Comment by thienlnam** [comment]
Linked PR is chugging along

**Comment by MitchExpensify** [comment]
> Linked PR is chugging along

Leave us alone, Melvin

**Comment by MitchExpensify** [comment]
How is the PR coming along at this point @thienlnam ?

**Comment by thienlnam** [comment]
Haven't gotten started on this yet - though the linked issue https://github.com/Expensify/Expensify/issues/299956 is about to be wrapped up so I can start on this soon

**Comment by thienlnam** [comment]
We still want to do this for consistency but it's not really a priority right now so I bumped to a monthly

**Comment by MitchExpensify** [comment]
This doesn't fall into a wave IMO, do you agree @thienlnam ?

**Comment by thienlnam** [comment]
This was being handled under VSB - finish tasks, but not part of a wave

**Comment by thienlnam** [comment]
We didn't finish this by EOY - need to see if we still want to do this

**Comment by thienlnam** [comment]
Spun up a BE PR, after that we can have a contributor handle the FE changes

**Comment by thienlnam** [comment]
Web-E PR merged, need to create a new implementation issue for App

**Comment by MitchExpensify** [comment]
> need to create a new implementation issue for App

Are you on the case for this @thienlnam ?

**Comment by thienlnam** [comment]
Ah, I created one here https://github.com/Expensify/App/issues/36196#issuecomment-1939852656

Wait.. you're assigned to it as well 😆 
I'll close this one so we can consolidate there
