### ISSUE TITLE
[$1000]  routing number paste to compose box instead of input field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. delete all the workspace (if you have any)
2. click on FAB icon
3. select New workspace option
5. which will open RHP
6. go to settings and change the currency to non USD (if currency is USD)
7. click on back button to go previous page
8. click on bank account option which will open workspace currency popup
8. click on update to USD button
9. click on connect manually option
10. paste routing number in input field
## Expected Result: 
should paste routing number in input field
## Actual Result: 
routing number paste to compose box

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8a7996e-92dd-4545-873a-584a80ba0d70

https://github.com/Expensify/App/assets/43996225/dbf7fbcf-3f93-4bc6-85d3-f297f634b479

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689754408457479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ed0e16ea50369c3</li>
        <li>Upwork Job ID: 1682285612094263296</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by rk111** [comment]
I will work on this issue

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump for review of these proposals. Thanks

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump for review pls :)

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump for review ^^ thanks

**Comment by abdulrahuman5196** [comment]
Sorry for the delay from my end. Will close out the review today.

**Comment by abdulrahuman5196** [comment]
@laurenreidexpensify This seems to be a dupe happening at a different place of this issue - https://github.com/Expensify/App/issues/23184
Thanks @samh-nl for pointing it out.

**Comment by laurenreidexpensify** [comment]
Ah you're right. That one was opened first, so closing in favour of that
