### ISSUE TITLE
Web - Avatars of users who are part of the thread are not shown if there are more than 4 users in the reply

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23312]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group chat of more than 4 users
2. Send a message and create a thread reply with more than 4 users in the thread.
3. Notice that only four avatars are shown in the reply avatar

## Expected Result:
Reply avatars are shown for all users who are part of the thread

## Actual Result:
Reply avatars are only shown for 4 users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9b96ecab-62aa-4078-b763-3201b75a0d84

https://github.com/Expensify/App/assets/93399543/6d75a54b-6f0e-4ee1-96f8-1457c517ae1c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689721447687349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
it seem a backend data return only this four users  `"childOldestFourAccountIDs": "14769081,14566648,14645172,14677000",` 
and we use those to get the replies icons.
https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/pages/home/report/ReportActionItem.js#L378

**Comment by muttmuure** [comment]
Catching up from ooo

**Comment by muttmuure** [comment]
I don't think this is a bug. This seems like a feature request
