### ISSUE TITLE
[Awaiting payment in ND] [HOLD for payment 07-26-2023] Tracking issue for payment

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#23314]
@Santhosh-Sellavel helped to review a PR that fixed a few deploy blockers, but he was never paid out. The PR fixed multiple issues that have already been closed out, so I didn't want to confuse people by mentioning this in just one issue.

https://github.com/Expensify/App/pull/22586 is on production already

Can we pay them the reviewer fee? Thanks!

**Comment by Santhosh-Sellavel** [comment]
Will Request via ND on Jul 26

**Comment by trjExpensify** [comment]
Cool, cool. Sounds good!

**Comment by trjExpensify** [comment]
No change, Melv. Chill.

**Comment by Santhosh-Sellavel** [comment]
Requested $1K on ND

**Comment by trjExpensify** [comment]
Not overdue, awaiting payment in NewDot.

**Comment by JmillsExpensify** [comment]
Reviewed details for @rushatgabhane. This is accurate and approved for payment in NewDot.

**Comment by trjExpensify** [comment]
Dope, closing!
