### ISSUE TITLE
[$1000] Input loses focus when using keyboard shortcut

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press CTRL + K to open the search panel
2. Press CTRL + J and then CTRL + K and notice the input filed is still focused
3. Press CTRL + Shift + K to open the new group side panel
4. Press CTRL + J and then CTRL + Shift + K and notice the input filed is still focused
5. Press CTRL + K and then CTRL + J and then CTRL + K and notice the input field
## Expected Result: 
Input field should be focused just as before
## Actual Result: 
Input field loses focus if user presses CTRL + K then CTRL + Shift + K then CTRL + K

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/218a5851-41eb-4c36-af4c-08908b074d96

https://github.com/Expensify/App/assets/43996225/c5806afc-4f6e-4f60-898c-a735a768580a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689759489738269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bee8d7fcd40b4bd</li>
        <li>Upwork Job ID: 1683864787973197824</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Nice, thanks for that call out @dukenv0307. Let's close this out

**Comment by Nathan-Mulugeta** [comment]
Hey @bfitzexpensify , can you take a look at this on slack, I have reported very similar issue on slack long ago but has been ignored can this make me eligible for the reporting bonus? Thanks.

**Comment by bfitzexpensify** [comment]
Hi @Nathan-Mulugeta, please link out to the Slack post

**Comment by Nathan-Mulugeta** [comment]
😅 oh sorry I thought I linked it up. Just edited @bfitzexpensify

**Comment by bfitzexpensify** [comment]
Thanks. Agreed this is eligible for reporting bonus, offer sent

**Comment by Nathan-Mulugeta** [comment]
Offer accepted and thank you 🙂

**Comment by bfitzexpensify** [comment]
OK, all paid out. Closing this out again
