### ISSUE TITLE
[$1000] Anonymous user clicks the checkbox of task, App doesn't redirect to login page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a public room
2. Create a task report in the public room
3. Copy the URL of the public room
4. Sign out and go to the public room with the URL
5. Click on the checkbox of task preview
## Expected Result: 
We should redirect to sign in page
## Actual Result: 
After clicking on the checkbox, API is called and an error appears in task report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 19-07-2023 21_24_32.webm](https://github.com/Expensify/App/assets/43996225/053edf0b-4f8c-4bed-892c-4e8083b4b962)

https://github.com/Expensify/App/assets/43996225/dbbe5f3b-5f0e-4cc8-9fe2-44f5367dccd9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689776655515189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014decaa677c122348</li>
        <li>Upwork Job ID: 1682420800850259968</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Anonymous user clicks the checkbox of task, App doesn't redirect to login page
### What is the root cause of that problem?
We don't check to redirect to sign in page if anonymous user does this action
https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/components/ReportActionItem/TaskPreview.js#L87
And then anonymous user cannot re-open or complete task, and the error appears.
### What changes do you think we should make in order to solve the problem?
We should add `Session.checkIfActionIsAllowed` to redirect to sign in page if anonymous user complete or re-open task
```
onPress={Session.checkIfActionIsAllowed(() => {
    if (isTaskCompleted) {
        Task.reopenTask(props.taskReportID, taskTitle);
    } else {
        Task.completeTask(props.taskReportID, taskTitle);
    }
})}
```
### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment]
bug report looks good!

**Comment by hadi19999** [comment]
Since the user logged out, it should delete the auth token, to avoid login by only entering the link immediately, I think this might cause security issue for the user that logged out because he/she did not actually log out. The solution is by deleting the auth token when clicking on logout.

**Comment by hadi19999** [comment]
Contributor details
Your Expensify account email: hadi.dev.99@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ad1c1774ab89c78f

**Comment by abdulrahuman5196** [comment]
Will check this in a while

**Comment by slafortune** [comment]
Duplicate - closing
