### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web - Link has been re-sent text in verify secondary login is not cleared even reload the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23344]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login any account
2. Go to Settings -> Profile -> Contact method
3. Click "New contact method" button -> Fill in any email that is not Expensify account yet
4. Click on the secondary email that just added to verify it
5. Click on Didn't receive a magic code?
6. Verify that the text "Link has been re-sent" is displaying
7. Click back arrow in top header
8. Click on the secondary email that just added

## Expected Result:
"Link has been re-sent" should be hide when we start to verify secondary login again

## Actual Result:
"Link has been re-sent" is still displaying although we start to verify secondary login again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a8866fbd-b5ef-4879-8b77-c35673cbdb46

https://github.com/Expensify/App/assets/93399543/124fcf53-fe34-4e04-813b-3529e07c860a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689865993497519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcfd004a86329f7b</li>
        <li>Upwork Job ID: 1683648947629244416</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 25741951</li>
<li>hoangzinh | Reporter | 25741954</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Link has been re-sent text in verify secondary login is not cleared even restart the validate secondary login again
### What is the root cause of that problem?
The condition to show the "Link has been re-sent" is from the Onyx key `validateCodeSent` https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L212
Currently, we haven't implemented any logic so that it will reset the key `validateCodeSent` of validating secondary login when the page ContactMethodDetailsPage is unmounted => the "Link has been re-sent" text is alway displayed
### What changes do you think we should make in order to solve the problem?
In the component lifecycle componentWillUnmount of [ContactMethodDetailsPage](https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L93), we need set the Onyx key `validateCodeSent` of validating secondary login to `false` so it will hide the text "Link has been re-sent" when we visit the this page again.
Moreover, we can also clear the error when we click in the text link "Didn't received the magic code" as well if we think it's necessary (usually we won't clear the error). Almost [same as here](https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/actions/User.js#L134-L139)

**Comment by sakluger** [comment]
Yeah I think we should fix this one. Too bad we didn't notice this one when fixing a similar issue (https://github.com/Expensify/App/issues/19471) on the same page, but it's a different flow so it makes sense why we would have missed it.

**Comment by ArekChr** [comment]
The proposal from @kbecciv looks good to me  
🎀 👀 🎀 C+ reviewed

**Comment by flodnv** [comment]
>Moreover, we can also clear the error when we click in the text link "Didn't received the magic code" as well if we think it's necessary (usually we won't clear the error)

Sounds good, let's do both

**Comment by ArekChr** [comment]
> Oh wait, was that actually @hoangzinh [proposal](https://expensify.slack.com/archives/C049HHMV9SM/p1689867843730939?thread_ts=1689865993.497519&cid=C049HHMV9SM)? 😄

From what I know, @hoangzinh and @kbecciv is the same person, right?

**Comment by flodnv** [comment]
If you look at the Slack link, I don't think so 😄

**Comment by ArekChr** [comment]
Okay, so @hoangzinh was first. Could you assign him?

**Comment by flodnv** [comment]
NP! I have also asked @kbecciv to make this clearer in the future, which has been done here now: https://github.com/Expensify/App/issues/23344#issuecomment-1645384195

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Bug reporter + Contributor: @hoangzinh $1500 + $250 = $1750 (hired on Upwork)
Contributor+: @ArekChr - from Callstack, no individual payment

Above payment includes efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~01bcfd004a86329f7b

**Comment by sakluger** [comment]
@ArekChr do you mind completing the [BugZero checklist](https://github.com/Expensify/App/issues/23344#issuecomment-1658922188) so I can close out this issue? Thanks!

**Comment by ArekChr** [comment]
- [x]: The PR that introduced the bug has been identified. Link to the PR: no PR has been identified.
- [x]: The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: no comment.
- [x]: A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: no discussion.
- [x]: Determine if we should create a regression test for this bug. I think we can have a simple unit test for that.

Regression Test Proposal

1. Simulate a contact method that hasn't been confirmed.
2. Navigate to the contact method verification page.
3. Click the "Didn't receive a magic code?" button with mocked function.
4. Unmount the component.
5. Re-mount the component. Validate that the message "Link has been re-sent" doesn't appear.

Before 4 and 5 points, we can add a delay for two scenarios for success and failure cases regarding this [comment](https://github.com/Expensify/App/pull/23601#issuecomment-1653205098) if that will be introduced.

What are your thoughts? Do we agree 👍 or 👎?

**Comment by sakluger** [comment]
@ArekChr thanks! One question - what does "unmount the component" and "re-mount the component" mean? I want to make sure that the regression steps can be understood equally by technical and non-technical testers (I'm mostly non-technical if you couldn't tell 😄).

**Comment by sakluger** [comment]
Got it, thanks for the explanation!

So would it still be correct if we updated steps 4 and 5 to the following?

> 4. Refresh the page.
> 5. Validate that the message "Link has been re-sent" doesn't appear.

**Comment by ArekChr** [comment]
If we were using the React Native Testing Library, the appropriate step might be to 'remount the component'. However, for e2e tests, I concur with the given steps. I've updated the regression test steps.

**Comment by sakluger** [comment]
Perfect, thanks!
