### ISSUE TITLE
mWeb - New Workspace button is not visible correctly after deleting a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to STG ND in Safari on IOS.
2. Create a lot of workspaces by Settings --> Workspaces --> New Workspace.
3. Now open any workspace settings and delete it.
4. Notice the New Workspace button

## Expected Result:
The New workspace button should not change its position and show remain at the same place.

## Actual Result:
The New workspace button is not visible and hides below the browser bar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7062dd48-b241-4b2a-a442-2437b8cb63f8

https://github.com/Expensify/App/assets/93399543/7bb08cd5-f3ba-4b7f-93af-2b9e4c24c3e4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689877033802469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
not reproduced, `new workspace` is above URL. Closing
