### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Web - Workspace name is empty in request money page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Requirement: have policy expense chat beta access and a workspace
1. Press FAB and choose Request Money
2. Enter any amount and press Next
3. Search your workspace and select it as the participant
4. Verify you are brought to the confirmation page

## Expected Result:
Workspace name is shown on the confirmation page

## Actual Result:
Workspace name is not shown on the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/095dc214-b61c-4c86-b7d9-5441be1bbb95

https://github.com/Expensify/App/assets/93399543/f5794fea-e909-4aae-b921-1e627c3b2a64

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689870865032739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f529c8226628bb0</li>
        <li>Upwork Job ID: 1683692732773302272</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25818805</li>
<li>bernhardoj | Contributor | 25818806</li>
<li>bernhardoj | Reporter | 25818807</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Workspace name is empty on money request confirmation page
### What is the root cause of that problem?
The confirmation list item is OptionRow and the title (that should show the workspace name) is retrieved from `this.props.option.text`. The option props data that is shown (for the workspace) on the confirmation page comes from `OptionListUtils.getPolicyExpenseReportOptions`.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/OptionsListUtils.js#L118-L125
We can see that we return `text` with the value from `expenseReport.displayName` and it's been like this for a f few months. The problem is, the `displayName` property does not exist on a report. This might raise a question, if it doesn't exist, why do we just see the issue now? Why it works just fine before?
Short: The answer is, this issue started to happen after this PR https://github.com/Expensify/App/pull/21406.
Long:
Before the above PR, we can access `displayName` from a report object. The `displayName` is available because we are mutating the Onyx `report` object here:
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/SidebarUtils.js#L122-L131
We are still mutating it now, the difference is, the `report` object we are mutating is the cloned `report`. If you notice the code above, we are mutating the `reportsToDisplay` that is the filtered `allReportsDict`.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/SidebarUtils.js#L105-L112
`allReportsDict` is passed from `SidebarLinksData`, which is the `chatReports` as you can see below.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/pages/home/sidebar/SidebarLinksData.js#L71-L72
`chatReports` comes from the Onyx with a selector.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/pages/home/sidebar/SidebarLinksData.js#L177-L180
The selector is the one that clones the object.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/pages/home/sidebar/SidebarLinksData.js#L112-L145
Previously, `reportsToDisplay` comes directly from the `report` object, that is `allReports`.
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/SidebarUtils.js#L28-L33
That's why before the PR, mutating the `report` object will have an effect on every part of the app that uses the object.
So, the current code mutates the cloned object, while the previous code mutates the real object.
NOTE: even though the issue happens after https://github.com/Expensify/App/pull/21406, I wouldn't say it's a regression, but rather we are discovering a hidden bug.
### What changes do you think we should make in order to solve the problem?

Never use the `displayName` property. We also have another issue https://github.com/Expensify/App/issues/22128 that also avoids it now.
Instead, get the name from `ReportUtils.getReportName(expenseReport)`.
We will use the result for both `text` and `name` inside the `icons` array.

**Comment by kadiealexander** [comment]
Reproduced

![image](https://github.com/Expensify/App/assets/59587260/1166de31-44ee-4ed7-a2de-05a9f5ecf4c2)

**Comment by s77rt** [comment]
@bernhardoj Thanks for the update. Given that `getOrderedReportIDs` is only called once on the cloned object let's not worry about that reassignment.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/23348#issuecomment-1645431086)

**Comment by kadiealexander** [comment]
@AndrewGable any thoughts here?

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/12399 and https://github.com/Expensify/App/pull/21406
- The offending PR has been commented on: https://github.com/Expensify/App/pull/12399#discussion_r1284703106 and https://github.com/Expensify/App/pull/21406#discussion_r1284703138
- A discussion in #expensify-bugs has been started: I don't think this is needed. Seems a pretty edge case
- Determine if we should create a regression test for this bug: No

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @bernhardoj
Contributor: $1000 @bernhardoj
Contributor+: $1000 @s77rt

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/23348#issuecomment-1659484206)

Upwork job is [here](https://www.upwork.com/ab/applicants/1683692732773302272/hired).

**Comment by kadiealexander** [comment]
It's cool, we already have a contract in the works! :)

**Comment by kadiealexander** [comment]
Everyone is paid 🎉  thanks for your work on this!
