### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - Deleted Workspace can be accessed after deleting a workspace offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Be offline
2. Go to any workspace > click on the three dots > click on Admins room
3. Go to the Details page by clicking on the Admin room header
4. Go to the workspace by clicking on the workspace name below the #admin
5. Delete the workspace by clicking on the three dots above
6. By Click on the back button you will be taken to the archived #Admin room.
7. Go to the workspace by clicking on the workspace name below the #admin(Archived)

## Expected Result:
Can't access the deleted workspace

## Actual Result:
Can access the deleted workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9a97f296-e1d1-41ef-86d6-451fade885f6

https://github.com/Expensify/App/assets/93399543/c36ff285-37f4-4113-89a6-1ba1211d7224

**Expensify/Expensify Issue URL:**
**Issue reported by:** https://expensify.slack.com/archives/C049HHMV9SM/p1689897130713649
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689897130713649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011eef84994dda9118</li>
        <li>Upwork Job ID: 1683499227112550400</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25908810</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Deleted Workspace can be accessed after deleting a workspace offline

### What is the root cause of that problem?
Our `PressableWithoutFeedback` does not use the `disabled` prop:
https://github.com/Expensify/App/blob/f8bc30500acaed95d4668657cf18558deee79194/src/pages/ReportDetailsPage.js#L162-L174

### What changes do you think we should make in order to solve the problem?
Add `disabled` prop to the `PressableWithoutFeedback` when there's a *pending delete*:
```js
<PressableWithoutFeedback
    disabled={policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE}
```

**Comment by DanutGavrus** [comment]
@fedirjh This seems to produce the same effect as trying to click on the Workspace in the Workspace List, which is, the element is not clickable and also shows the "not allowed" cursor while hovering. I was thinking in terms of "consistency".  

Using the same approach, which is verifying the pending action, we can easily display only the text when it's a deletion! I just didn't know what the desired outcome actually is. Would you say to update my Proposal as such?

**Comment by shawnborton** [comment]
Hmm good question. @trjExpensify do you have an opinion here? 

I guess it makes sense to use the pending delete pattern, which I believe is strikethrough? And then yeah, I would make it so you couldn't click on the workspace link with the disabled cursor.

**Comment by trjExpensify** [comment]
The workspace name will remain after you come back online, as the #admins room access (read-only) is retained by the current admins of the workspace at the time of deleting the workspace. Said differently, the workspace name in the chat header doesn't show as strikethrough and then permanently show as ~Duraflame~ after you delete the policy, so I would think we go with #2 which is disable access to click through to the workspace editor in the room details, but show the name as we do in the chat header.

**Comment by srikarparsi** [comment]
Thanks @fedirjh, assigning you to the issue @DanutGavrus

**Comment by DanutGavrus** [comment]
@fedirjh 
PR ready for review: [PR24096](https://github.com/Expensify/App/pull/24096)

**Comment by kevinksullivan** [comment]
@conorpendergrast I am OOO next week so tapping you to help finish this out. Thanks!

**Comment by conorpendergrast** [comment]
Looks like this is on Staging now. Ongoing!

**Comment by kevinksullivan** [comment]
Set to make the payment tomorrow! @fedirjh can you finish out the steps above so we can pay out on time?

**Comment by conorpendergrast** [comment]
Ah, you're back! Unassigning myself now Kevin

**Comment by daveSeife** [comment]
@kevinksullivan can you please add me as a Reporter?

**Comment by kevinksullivan** [comment]
Paid @fedirjh . @DanutGavrus @daveSeife just sent you both offers. Lmk when you accept!

**Comment by daveSeife** [comment]
@kevinksullivan accepted the offer. Thank you!

**Comment by DanutGavrus** [comment]
@kevinksullivan Offer accepted with updated price as to also include the bonus. Thank you!

**Comment by DanutGavrus** [comment]
Hi, @kevinksullivan! Offer is still in pending, if you have the time. Thanks!

**Comment by kevinksullivan** [comment]
all set
