### ISSUE TITLE
Web - The sign in with apple button is not highlighted when hover over

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com web
2. Observe the first page or 'Get started below' page
3. Hover over the cursor on the sign in with apple button

## Expected Result:
 The sign in with apple button should be highlighted

## Actual Result:
he sign in with apple button is not highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e46a3147-b210-486c-a83e-23419a258c4f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689895328247729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
The Apple sign-in PR was [reverted here](https://github.com/Expensify/App/pull/23295) so this won't happen now and can be closed.

Anyway, we will need to handle it once the Apple sign-in gets reimplemented. @shawnborton what should the hover style look like here? Should there be a border on hover like we show for some avatars? Or can we just ignore showing any hover styles?

cc @marcochavezf @lindboe

**Comment by shawnborton** [comment]
I think we can just ignore hover styles for now.

**Comment by Yokabdk** [comment]
@Nikhil-Vats the apple sign in with 'apple' and 'google' button is now appearing on the front page with no hover over styles. shouldn't this issue be fixed now?
