### ISSUE TITLE
[$1000] Web - Replies number changes for a second after deleting the parent message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat and send a message
2. Go to thread and send two messages
3. Notice that on the main chat page, 2 replies are displayed
4. Go back to the thread and delete the parent message
5. Go back to the main chat page and notice the replies number changes to 1 and goes back to 2.

## Expected Result:
Replies number does not change

## Actual Result:
Replies number changes for a second

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2ba3cf82-341c-4034-88aa-ac4ebe5062a0

https://github.com/Expensify/App/assets/93399543/b89a3e0e-795e-46c2-a2fb-a76e59992229

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689900561098269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2a5e1b8b80f9419</li>
        <li>Upwork Job ID: 1683522757694906368</li>
        <li>Last Price Increase: 2023-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26122995</li>
</ul></li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Reproducible, triaging to external

**Comment by sonialiap** [comment]
@Santhosh-Sellavel any thoughts on the proposal above?

**Comment by Santhosh-Sellavel** [comment]
I'm not able to reproduce this one can you please check @kbecciv @sonialiap?

**Comment by Santhosh-Sellavel** [comment]
Alright, I can reproduce this, without offline itself.

@allroundexperts's [proposal](https://github.com/Expensify/App/issues/23365#issuecomment-1646193700) looks good to me!

C+ Reviewed
🎀 👀 🎀

**Comment by neil-marcellini** [comment]
Sorry @allroundexperts I don't understand the root cause explanation in your proposal. Would you please provide a more detailed step by step description of what is happening as the root cause?

**Comment by Santhosh-Sellavel** [comment]
Waiting for @neil-marcellini.

**Comment by neil-marcellini** [comment]
I was OOO so I have a pretty large backlog. It might take me a few days to get to this.

**Comment by neil-marcellini** [comment]
I'll review the updated proposal today

**Comment by neil-marcellini** [comment]
> The problem here is that for thread titles, we're passing in the reportID of the child report rather than that of the parent report to the `deleteReportComment` function [here](https://github.com/allroundexperts/Expensify/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/actions/Report.js#L874).
> This causes the `getOptimisticDataForParentReportAction` function called [here](https://github.com/allroundexperts/Expensify/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/actions/Report.js#L964C52-L964C90) to change the number of replies since it gets the impression as if we're deleting a child report item while in reality we're deleting the parent report item (ie thread title).

@allroundexperts thanks for explaining more. That makes sense. 

> ### What changes do you think we should make in order to solve the problem?
> We should only call this function if the report action is not the thread title.

I agree that would fix this case, but what about the following case where the thread title is on a report with a parent?
1. Send a message to user B (reportA)
2. Send another message
3. Reply to that message in a thread (reportB)
4. Send two messages
5. Reply to the last message in a thread (reportC)
6. Send two messages
7. Delete the parent message of the current thread

I think instead we want to pass the actual reportID of the thread title action when deleting it. So when deleting the thread title in reportC we pass reportB.reportID vs reportC.reportID.

**Comment by neil-marcellini** [comment]
Bump @allroundexperts

**Comment by neil-marcellini** [comment]
@allroundexperts I reviewed your updated proposal and I think it's still a bit over complicated. Specifically I don't see why this part is needed 
```
const reportID = ((this.state.reportAction.childReportID || "").toString() === this.state.reportID.toString()) ? ReportUtils.getReport(this.state.reportID).parentReportID : this.state.reportID;
```

I'm liking @dukenv0307's [proposal](https://github.com/Expensify/App/issues/23365#issuecomment-1673582030) better since it's the most straight forward. What do you think @Santhosh-Sellavel?

**Comment by Santhosh-Sellavel** [comment]
Yes, @neil-marcellini it's straightforward forward let's with @dukenv0307's proposal, thanks!

**Comment by rojiphil** [comment]
## Proposal

[Proposal is already present here along with other thread issues](https://github.com/Expensify/App/issues/23450#issuecomment-1658337106). Point 3 in the proposal covers this case. We can either fix it along with the thread related issues there or fix this issue here. 

@neil-marcellini @Santhosh-Sellavel If possible, please do consider the above proposal too. Thanks.

**Comment by Santhosh-Sellavel** [comment]
> @sonialiap The PR is deployed to production but thi title doesn't update.

bump @sonialiap

**Comment by sonialiap** [comment]
@Santhosh-Sellavel fix + bonus $1500 - please request in NewDot
@dukenv0307 review + bonus $1500 - paid
@daveSeife report $250 - offer sent

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @Santhosh-Sellavel based on BZ summary.
