### ISSUE TITLE
[$1000] Web – Mention options fail to appear when focus is reverted after closing attachment window in chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat.
2. Type "@" to make the options appear.
3. Click on the plus sign on the left and select "Add Attachment."
4. After the attachment window opens, close it to return the focus to the input field.
5. Notice that the mention options do not appear when the focus is back.

## Expected Result:
The mention options should appear when the focus is reverted.

## Actual Result:
The mention options do not appear when the focus is reverted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f49e0e44-14e3-469f-81d2-e3f6985f289a

https://github.com/Expensify/App/assets/93399543/61a77694-2d75-4014-a0fb-270a456dcf05

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689911521635419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdc9840a8089f470</li>
        <li>Upwork Job ID: 1683530633323237376</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
in that case, let's close!
