### ISSUE TITLE
unread report title on LHN blinks when tapping message...in profile

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click +
2. New chat
3. Search and new chat with new user, Notice that the report title is in bold
4. Click header => Message .....
5. Observed that the report title on LHN stopped being bold and then bolded again
## Expected Result: 
after click Message the report change to read status
## Actual Result: 
the report title on LHN  from unread => read => unread after click Message .

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/16d863b9-5b29-43a3-a7f6-3754b9b0e3c6

https://github.com/Expensify/App/assets/43996225/b5557d97-c5ec-4c7d-8958-94b9b900187e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689773955881249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
the report title on LHN not change style bold
### What is the root cause of that problem?
The problem here is when creating a new report, we have `lastReadTime = null` resulting in `isUnread = true` so the title is bold. When we are in this new report and click on "Message..." here we will reopen this report and dismiss the modal [here](https://github.com/Expensify/App/blob/1580aa92892fa1d8426ef8e519b22bbf671b07f1/src/libs/actions/Report.js#L563C1-L575C1).
At OpenReport we first update `lastReadTime` in `optimisticReportData` [here](https://github.com/Expensify/App/blob/1580aa92892fa1d8426ef8e519b22bbf671b07f1/src/libs/actions/Report.js#L399C1-L400C1) => report isUnread = false, since we pass params participantAccountIDList so the API return `lastReadTime = null`
That's why we see that after clicking we will see the report title blinking in bold
### What changes do you think we should make in order to solve the problem?
We will check if there is already chat then we will not pass participantAccountIDList so API returns lastReadTime as read:
```
    const participantIDs = chat ? [] : participantAccountIDs;
    openReport(reportID, [], newChat, '0', false, participantIDs);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by isabelastisser** [comment]
I can't reproduce this.
