### ISSUE TITLE
Web - Connect Bank Account - Console error when connecting Bank account via Plaid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.expensify.com
2. Log in with any account
3. Go to Setting - Workspace - Connect Bank Account
4. Select Plaid and procced with flow

## Expected Result:
No console error should be visible

## Actual Result:
Console error when connecting Bank account via Plaid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3..44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6137059_image](https://github.com/Expensify/App/assets/78819774/5951e2c8-9706-4a9a-ae8f-3944f0206f86)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rk111** [comment]
Any help required for this issue I am available to work on this issue.

**Comment by NicMendonca** [comment]
CSP error, as discussed here: https://expensify.slack.com/archives/C02NK2DQWUX/p1689956245232069

**Comment by justinpersaud** [comment]
I'll fix this. It's an internal issue.

**Comment by justinpersaud** [comment]
This should be resolved now
