### ISSUE TITLE
Inconsistency bug: Enter in description field triggers next when title is filled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click assign task
3. Type anything in title and description
4. Focus on title field and click on enter, observe that it adds new line
5. Remove the title, focus on description field and press enter, observe that it adds new line
6. Again type any title, focus back on description field and press enter, now rather then adding new line, it will trigger next button
## Expected Result: 
App should add new line whenever we click on enter in title or description field of assign task
## Actual Result: 
App triggers next button if we click on enter in description field and title is filled (Enter click in title field when description field is also filled adds new line and enter click in description field when title is not filled adds new line)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/188c3f80-2b80-44dd-a736-730648708e76

https://github.com/Expensify/App/assets/43996225/6677cc20-0fd6-4a59-ad7e-5945d8b51d22

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689787217883529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Thanks for flagging @Nodebrute! I'll review https://github.com/Expensify/App/issues/23025 to identify if we should put this one on hold.

**Comment by alexpensify** [comment]
@thienlnam - is this related to https://github.com/Expensify/App/issues/23025? If yes, then I'll close. Thanks!

**Comment by thienlnam** [comment]
Yeah, please close this for that issue - thanks!
