### ISSUE TITLE
App displays error of 'Please select one member' on invite message page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open members
6. Click on invite
7. Select any 1 member and click next
8. Reload on invite message page and click invite
9. Again click invite, select any one user and click next
10. Observe that app displays 'Please select one member' error even though user is selected and it allows to invite
## Expected Result: 
App should not display 'Please select one member' error if user is already selected on invite message page
## Actual Result: 
App displays 'Please select one member' error if we select user, reload on invite message page, click on invite, select new user and click next to again visit invite message page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0ebb7147-fd2d-4ada-ad9f-54c458deba36

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689575732247029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhanashree-sawant** [comment]
Yes in this case, both @dukenv0307 and @makiour are correct, I have commented on that issue and I think they will change the reporting name once they are available. We can close this issue.

**Comment by michaelhaxhiu** [comment]
all set

**Comment by michaelhaxhiu** [comment]
thanks for the input yall
