### ISSUE TITLE
Split Bill - Moving through the Split participants is done by jumping when using the arrows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
1. You must be logged in
2. At least 1 group with 4 or more members must be created
Steps:
1. Open https://staging.new.expensify.com/
2. Choose any group with 4 or more members
3. Click on the + button in the compose box.
4. Click on "Split bill" in the action menu
5. Enter any amount of currency
6. Click on "Next" button
7. Click on any participant from the "Split with" list
8. Use the arrows to move through the list of users and apply selected/deselected with "Enter"

## Expected Result:
Moving through the "Split bill" participants with the help of arrows should be smooth and with a clear logic for the user

## Actual Result:
When a user in the "Split bill" members menu clicks on any user from the "Split with" list and tries to use the arrows to navigate through the users using the selected/deselected(Enter) function, there are random jumps through the users when you press Enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2e4cf351-8fd9-45d5-9806-f9c4445d2ef4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause- Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Thanks @dukenv0307 , I'll dig in more soon, not a big priority since it might be on hold pending
- https://github.com/Expensify/App/issues/12668 
or the issue that's held on
- https://github.com/Expensify/App/issues/11795

**Comment by mallenexpensify** [comment]
@cristipaval , do you think this should be put on hold pending the below, it looks like you're leading that. 
- https://github.com/Expensify/App/issues/11795

**Comment by cristipaval** [comment]
@mallenexpensify the thing is that I am not sure this is an issue. See [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1675195615741509?thread_ts=1670238226.611139&cid=C01GTK53T8Q) Slack thread for more info.

**Comment by mallenexpensify** [comment]
I'm going to close this since it has to do with arrow keys and we haven't decided to optimize the app for keyboard nav.  Also, as @cristipaval pointed out, [Mills comment ](https://expensify.slack.com/archives/C01GTK53T8Q/p1675195615741509?thread_ts=1670238226.611139&cid=C01GTK53T8Q)from 7 months ago was keep punting 🏈
