### ISSUE TITLE
Chat - Name not placed in bold to indicate unread messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/issues/23398
## Action Performed:
1. Log into staging.new.expensify.com as User A
2. Login into another account on another device/browser as User B and begin conversation with User B
3. Navigate to other conversation.
4. As User B, send a new message to User A on web

## Expected Result:
After new message is received, the sender's name is placed in bold

## Actual Result:
Nothing happens after receiving new message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/09ab07d6-9049-4531-8100-45365b20e6f9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
I'm going to bump this down to weekly till we decide whether or not int ends up becoming part of the Unread Indicator refactor.

**Comment by deetergp** [comment]
Since there continues to be radio silence on this one, I think I am going to close it. Feel free to re-open if you disagree.
