### ISSUE TITLE
Chat - Mention here appears even in 1-1 DM report.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any 1-1 DM report.
2. Text `@` and observer the mention list
3. Notice that `@here` appears in the mention list.

## Expected Result:
Mention here shouldn't appear in 1-1 DM report

## Actual Result:
Mention here  appears in 1-1 DM report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/88bee05b-2b94-4c68-a69b-4da0ed0b1c2f

![image (1)](https://github.com/Expensify/App/assets/93399543/93c5e978-74c9-43ef-b1eb-fbcc9482abca)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689927162209729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention here appears even in 1-1 DM report.
### What is the root cause of that problem?
We're adding mention here in our suggestion list even that's 1-1 DM report.
https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/home/report/ReportActionCompose.js#L468-L479
### What changes do you think we should make in order to solve the problem?
We should add a check, if it's a 1-1 DM, we shouldn't add mention here to our suggestion list in [here](https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/home/report/ReportActionCompose.js#L468-L479) :


```javascript
if (ReportUtils.isOneToOneDMReport(this.props.report) && CONST.AUTO_COMPLETE_SUGGESTER.HERE_TEXT.includes(searchValue.toLowerCase())) {
 // add mention here to the list
}
```
`isOneToOneDMReport` can be something like this:
```javascript
function isOneToOneDMReport(report) {
    return lodashGet(report, 'participantAccountIDs', []).length === 1;
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by muttmuure** [comment]
Catching up from ooo

**Comment by muttmuure** [comment]
Not a bug
