### ISSUE TITLE
Web - Offline - Email show on profile page when create chat with new user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23404]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Force Offline
2. Click FAB button => new chat
3. Search and new chat with new user never chat before
4. Click header, Observe that the email (login) is displayed

## Expected Result:
 Login information is not displayed for users who have never chatted before.

## Actual Result:
Login information is displayed for users who have never chatted before.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c6ddf51-3a9b-42b5-a16b-d744665efe46

https://github.com/Expensify/App/assets/93399543/865120a6-677e-40f1-a21a-0cad3bbd6e4d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689922398125039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
  by: @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
Login information is not displayed for users who have never chatted before.
### What is the root cause of that problem?
When in offline mode when creating a new chat with a user this user's data will be saved in `personalDetailsList` by optimisticPersonalDetails .
https://github.com/Expensify/App/blob/0acd42d05003dde342caa03cd9a3c469a078e0cd/src/libs/actions/Report.js#L443-L454
Then when open profile page will call API `OpenPublicProfilePage` to get user's profile but when offline it will not get data  from BE to update so it will get data from optimisticPersonalDetails stored before.
### What changes do you think we should make in order to solve the problem?
When we save optimisticPersonalDetails remove `login` from the data.
```javascript
            optimisticPersonalDetails[accountID] = allPersonalDetails[accountID] || {
                accountID,
                avatar: UserUtils.getDefaultAvatarURL(accountID),
                displayName: login,
            };
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by dylanexpensify** [comment]
+1 I think this is intended, not a bug. @aldo-expensify thoughts?

**Comment by aldo-expensify** [comment]
I think this is expected behaviour for now, since you started the chat using the email.

cc @Beamanator to double check since he is more familiarized with this.

**Comment by Beamanator** [comment]
Yeah I think we should :donothing: here - we optimistically stored `login` in the optimistic personal details to fix another bug, so it would be unwise to remove it - and we're discussing elsewhere about not showing optimistic data in the profile page, so we can close this (which already happened lol)
