### ISSUE TITLE
Web - Weird line seen below 'Routing Number' while connecting bank manually in workspace in Safari browser

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify app.
2. Go to settings -> workspaces
3. Click on any workspace.
4. Go to Bank Account and click on 'Connect Manually'

## Expected Result:
Nothing should appear below 'routing number' label.

## Actual Result:
 A weird line is appearing below 'Routing number' label. This is happening only in Safari and not in other browser.
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 11 48 11 AM](https://github.com/Expensify/App/assets/93399543/b07f10b5-d6ed-43dd-bb29-29c1de353b3d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689926018949719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Dupe, closing
