### ISSUE TITLE
[$1000] Web - HEIF image is disabled while uploading profile picture

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Click Profile
2. Upload photo
3. Try to select HEIF image

## Expected Result:
It should allow to select HEIF image

## Actual Result:
It doesn't allow to select HEIF image.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/86046b8a-bed0-43d2-9d55-9865a0f5f3bd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689933994406329

https://expensify.slack.com/archives/C049HHMV9SM/p1689934405429829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b5c172fba15f3b8</li>
        <li>Upwork Job ID: 1683579455663132672</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by KrAbhas** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
HEIF image should be enabled while uploading profile picture

### What is the root cause of that problem?
heif is not a part of extension list

### What changes do you think we should make in order to solve the problem?
In the list of allowed extensions we should provide heif like this:
`AVATAR_ALLOWED_EXTENSIONS: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'heif'],`
And also make changes to allow uploading the image.

### What alternative solutions did you explore? (Optional)
NA

**Comment by DinalJivani** [comment]
@huzaifa-99 
@allroundexperts 

HEIF image is working on iOS/Native app but it's not working on MacOS / Chrome while its allowing HEIF image in MacOS / Safari too. So, It's just a chrome which is affected.

So I think HEIF images are supported but on desktop somehow it's not allowing to pick HEIF image from list.
