### ISSUE TITLE
[$1000] Web - App allows to move to next step even when we keep account no and routing number same

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account->connect manually
3. Enter routing number and account number (keep it different for now) and click continue
4. Fill in details on step 2 and continue
5. Copy link of step 3, go back to step 1 and make account number same as routing number and click on left hand side to close right hand menu (ensure that error is not displayed when we close the right hand menu)
6. Paste and open copied link, fill out step 3 fields and click continue
7. Observe that it allows us to move to next step even though account no and routing number is same, to cross check, use app back button to revisit step 1

## Expected Result:
App should not allow to save and move to next step if account no and routing no are same

## Actual Result:
App allows to save and move to next step even if account no and routing no are same if we open step 3 by deep link and if we close the right hand menu before app triggers the error on step 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ee218111-64b6-4475-8aa0-c0a558580bff

https://github.com/Expensify/App/assets/93399543/e4bdd7a2-9b7d-446d-b2e7-2eab9e3b080f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689931285240149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c191ec47caa63f3</li>
        <li>Upwork Job ID: 1683438280951832576</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by saalimzafar** [comment]
Contributor details
Your Expensify account email: saalimzafar34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8ee2f2da01bcf13

**Comment by laurenreidexpensify** [comment]
@situchan bump to review these proposals please! Thanks

**Comment by laurenreidexpensify** [comment]
@situchan bump for review pls ^^ thanks

**Comment by situchan** [comment]
This was fixed in https://github.com/Expensify/App/pull/23677 and no longer reproducible on main.
The fix will be taken into account on staging upon next deploy.
