### ISSUE TITLE
Onfido | Real identity logo missing 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23425]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Click Workspace
2. Go to any workspace-> Setup bank account
3. On personal info step click on Save & continue
4. Onfido | Real identity logo is missing
## Expected Result:
 Onfido | Real identity logo should be visible
## Actual Result: 
Onfido | Real identity logo not visible

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Image from iOS](https://github.com/Expensify/App/assets/43996225/d06318c1-6bb8-4ac5-95d5-26446940493a)

https://github.com/Expensify/App/assets/43996225/53b06890-212e-43da-b07d-043df7ae94be

![Snip - New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/43996225/57a0bd5e-4236-49b9-867b-9d0ba73f535b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690024776482819
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Closing since this is similar to https://github.com/Expensify/App/issues/23275#issuecomment-1644096900
