### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Parent Message of thread chat on LHN doesn't updated when the parent message is updated

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23424]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to new chat
2. Send New message
3. Go to the thread chat of the above message
4. Send new message on the thread chat
5. Update the parent message
6. See title of thread chat on LHN
## Expected Result: 
Parent Message of thread chat on LHN should be updated
## Actual Result: 
Parent Message of thread chat on LHN doesn't updated

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/519b0650-09fa-4891-b240-d9ad767bc9f2

https://github.com/Expensify/App/assets/43996225/c1d4867c-2743-4649-86fb-21a734561144

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690020315164019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016848c21d8e7b7eeb</li>
        <li>Upwork Job ID: 1683964849932365824</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 25796886</li>
<li>dukenv0307 | Reporter | 25796887</li>
</ul></li>
    </ul>
</details>

**Comment by tjferriss** [comment]
Overdue no more, Melvin. Adding External label.

**Comment by tjferriss** [comment]
PR is merged but held on QA https://github.com/Expensify/App/pull/23777#issuecomment-1658957521

**Comment by tjferriss** [comment]
Payment comment has been updated with contributors and amounts https://github.com/Expensify/App/issues/23424#issuecomment-1664330805

@parasharrajat can you get started on the checklist when you have a chance?

**Comment by tjferriss** [comment]
All set for payment barring regression. @parasharrajat can you grab the checklist when you have a minute?

**Comment by tjferriss** [comment]
@dukenv0307 has been paid via Upworks. Regression test has been submitted https://github.com/Expensify/Expensify/issues/307290


@parasharrajat did you request payment via NewDot?

**Comment by JmillsExpensify** [comment]
Reviewed the details for @parasharrajat. Payment summarized above by BZ member is approved for payment in NewDot.
