### ISSUE TITLE
Web - Sending email with https:// in start break copy email to clipboard and edit logic

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23434]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send email with https:// in start eg: https:[//test@test.com](mailto://test@test.com)
4. Right click on link to open copy email to clipboard popup, observe that popup only displays 'mailto:'
5. Edit the message and observe that link part only displays 'mailto:'

## Expected Result:
App should recognize unwanted characters in start of email like 'https://' and ignore them while displaying email link

## Actual Result:
App considers some part of 'https://' as part of email and breaks the copy email to clipboard and edit logic

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2169101f-0a7a-4272-ba83-cf1334464498

https://github.com/Expensify/App/assets/93399543/40f23a4a-05b5-44cd-b519-a70bf368e19d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689953211650189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
Looks like it's in the backend.
Here is what we send:
![image](https://github.com/Expensify/App/assets/19537677/56f0c6f2-ffa3-4b77-bde3-8b3c301bab31)
Here is what we receive
![image](https://github.com/Expensify/App/assets/19537677/cf128d41-1990-4320-9de8-d44fc2f9b876)

**Comment by StanislavLavrenchuk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
typing email with http:// or https://, should remove "//" and can do email to clipboard.
### What is the root cause of that problem?
If the string include "//" this string might be URL style. so the email is assumed by URL.
We need to fix this.
### What changes do you think we should make in order to solve the problem?
Can Add "//" removing logic on here
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L53

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
@dhanashree-sawant is there a reason anyone would ever send `https://test@test.com` I can't think of ever seeing that used before.

**Comment by dhanashree-sawant** [comment]
Agree, https:// doesn't seems to be the term anyone will use ahead of email. The issue also occurs when we have only '//' in front i.e. `//test@test.com`

**Comment by mallenexpensify** [comment]
Thanks @dhanashree-sawant , I just can't imagine a real-world case where someone would input that so gonna close
