### ISSUE TITLE
[HOLD for payment 2023-08-14] [$1000] Currency changes after refresh although URL has currency params 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app and open any report
2. Click on request money
3. Change currency and notice it has changed in the URL
4. Copy the URL and open it somewhere or just refresh
5. The currency param is there in the URL but changed
## Expected Result: 
Currency should be the one in the URL currency parms.
## Actual Result: 
It changes to the default currency

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bugCurrency-vid.webm](https://github.com/Expensify/App/assets/43996225/2b660193-2e9c-406d-8511-3ed73e7e9da4)

https://github.com/Expensify/App/assets/43996225/81a553ce-1617-4bb6-8994-8ada61da1e59

**Expensify/Expensify Issue URL:**
**Issue reported by:** @makiour
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690050379038969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b122db1f8bca0f1d</li>
        <li>Upwork Job ID: 1683656595572019200</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue here is that we are not keeping the currency selected *although we have it in the link parameters*
We need to keep the selected currency.
### What is the root cause of that problem?
After investigating, there are two main parameters that we need to know when opening money request page:
1. selectedCurrency: This one refers to the currency we are showing.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L181
2. IOU.currency: This one refers to the currency assigned to our profile (it is based on location and comes from BE)
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L41-L45
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L494-L495
The root cause here is that we are handling selected currency change when it occurs to IOU.currency. So, we are keeping track of the selected currency if it has changed. That's good. However, it always changes the selectedCurrency whenever it has changed even after receiving it through data. To be more clear here,
The following useEffect are handling the logic of setting the currency:
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L277-L289
As we can see the first useEffect is handling it correctly and changing the currency when *we send it through URL params*.
However, in the other case, in the second useEffect, we don't handle this, which causes the selectedCurrency to always change
to IOU.currency especially that at first it is initalized to constant.
We need to handle this in here.
### What changes do you think we should make in order to solve the problem?
#### Option 1:
We can just add a condition inside the useEffect to check if we have currency params within the URL, if this is the case, we return:
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/iou/steps/MoneyRequestAmountPage.js#L286-L288
We can add
if (props.route.params.currency) {
            return;
 }
before
setSelectedCurrencyCode(props.iou.currency);
To be like that:
    useEffect(() => {
        if (props.route.params.currency) {
            return;
        }
        setSelectedCurrencyCode(props.iou.currency);
    }, [props.iou.currency]);
#### Option 2:  Simpler and Preferred
Since we understand the logic in which the currency changes, and since we know that useEffect hooks are run according to the order they have been put within the React component, the simplest solution here is to just switch the useEffects and put the second one first in the following way:
useEffect(() => {
        setSelectedCurrencyCode(props.iou.currency);
    }, [props.iou.currency]);

    useEffect(() => {
        if (!props.route.params.currency) {
            return;
        }
        setSelectedCurrencyCode(props.route.params.currency);
    }, [props.route.params.currency]);

**Comment by sophiepintoraetz** [comment]
Yup, able to reproduce!
<img width="1182" alt="image" src="https://github.com/Expensify/App/assets/42940078/a4e4e44a-d28d-49cb-9991-c966e95a76a0">

**Comment by rushatgabhane** [comment]
@makiour I like option 1 because it's more clear. 

I don't like option 2 to change the order of useEffects because it's really easy to forget the fact that order of useEffect matters and someone can cause this bug if they are refactoring this component.

Further, I think we can combine both the `useEffects` for readability.



```js
useEffect(() => {
    if (props.route.params.currency) {
        setSelectedCurrencyCode(props.route.params.currency);
        return;
    }
    setSelectedCurrencyCode(props.iou.currency);
}, [props.route.params.currency, props.iou.currency]);
```

**Comment by rushatgabhane** [comment]
C+ reviewed 🎀 👀 🎀 

https://github.com/Expensify/App/issues/23436#issuecomment-1646938220

**Comment by MariaHCD** [comment]
The proposal looks good to me too.

**Comment by rushatgabhane** [comment]
@makiour please add back the checklist and attach screenshots for all platforms

**Comment by sophiepintoraetz** [comment]
Great! Once @MariaHCD has reviewed the PR we can wait for the regression period before releasing payments.

**Comment by rushatgabhane** [comment]
@sophiepintoraetz just fyi, we fixed an additional bug that we encountered while testing. 

We fixed it in the same PR because it blocked testing of this issue.

Please confirm if you agree that we should pay an additional bounty of $2k

bug report: https://expensify.slack.com/archives/C049HHMV9SM/p1690926235865309

**Comment by sophiepintoraetz** [comment]
@makiour - I appreciate the case and the discretionary effort, I think the bonus payment is effectively captured in the fact that you are being paid for two bug reports - so it did take you a bit longer but I think you are being well compensated for it! 

Payouts due (once the regression period passes):

- Issue Reporter: $250 @makiour 

Following payments doubled for fixing two bugs inside this one issue:
- Contributor: $2000 @makiour (total $2250)
- Contributor+: $2000 @rushatgabhane 

Eligible for 50% #urgency bonus?  N

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
created a manual request here - https://staging.new.expensify.com/r/8223080099023677

**Comment by JmillsExpensify** [comment]
Reviewed the details for @rushatgabhane. Approved for payment in NewDot based on the BZ summary above.
