### ISSUE TITLE
Task does not have composer at the bottom

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the task https://staging.new.expensify.com/r/2357740427233470
## Expected Result:
Should have checkbox to complete order
## Actual Result:
doesn't have a chat box at the bottom. It also shows with a red dot.  There are no apparent console errors.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/43996225/c92b742f-08c3-4cc4-a5f0-d2d5bd06e001)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690075407703469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@dukenv0307 do you think your proposal would also fix https://github.com/Expensify/App/issues/22769?

**Comment by kadiealexander** [comment]
@thienlnam should the bottom of the page display the composer or the checkbox? The title no longer matches the expected result.

**Comment by kadiealexander** [comment]
Awesome, good find @dukenv0307!

**Comment by thienlnam** [comment]
Agreed, @dukenv0307 do you mind adding those comments on this issue? https://github.com/Expensify/App/issues/22769

Let's consolidate those since they appear to be the same RCA!
