### ISSUE TITLE
Web - Green dots suddenly appearing in LHN and it’s not clear why that’s suddenly the case or how to remove them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Certain chats appear with green dots on this latest version, even though there is no recent report activity that would have created a todo
3. Tap into the report. It’s not possible to see what’s outstanding or how to clear the GBR pattern

## Expected Result:
Old IOUs shouldn’t appear unless there is recent activity

## Actual Result:
Green dots are appearing despite lack of recent activity

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 11 12 59](https://github.com/Expensify/App/assets/93399543/97e754b1-200b-4401-82bb-dbebab7f40ee)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689959564209639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
This is happening when a money request has not been settled, we spoke about this here: https://expensify.slack.com/archives/C01GTK53T8Q/p1689990441976089

**Comment by mountiny** [comment]
Adding this to the wave3 project

**Comment by JmillsExpensify** [comment]
Agree that we should show the green dot when an IOU is settled. This is a particular case specific to older, high-value accounts, where it's not possible to find your unpaid IOUs to settle them, which in turn, removes the green dot.

**Comment by JmillsExpensify** [comment]
Separately, I think this is fundamentally related to comment linking and bi-directional scrolling, so I don't think it's a wave3 initiative though we can keep it in the project for now.

**Comment by mountiny** [comment]
This might have been resolved with some changes this deploy

**Comment by JmillsExpensify** [comment]
If it was resolved, let's close it out!
