### ISSUE TITLE
Erasing your display name doesn't show any invalid input sign

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings> Profile > Display name
2. Erase your display name and save while the space is empty
## Expected Result: 
warning should be shown and when you click your Display name (automatically it will be your email address) it should appear in the display section too
## Actual Result: 
There was no warning that you have saved the empty step and your email address will be your display name automatically. When you click the display name is remains empty still.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6b5e6dad-2546-4f8a-81bc-d6829e6556ad

https://github.com/Expensify/App/assets/43996225/74f890d1-9e1f-4642-b562-91fb5621115d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690065504146759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by KrAbhas** [comment]
Since when a user creates a new account display name is same as loginId for email based login, hence I don't think this is a bug. Still we can give warning to the user or if we want a different action we can explicitly not allow them to empty display name, by disabling the save button if the value is empty.
