### ISSUE TITLE
mWeb - Showing duplicate messages in chrome and on mobile

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Message sent once within mobile app
2. Duplicate immediately appeared
3. Checked chrome and was also showing the duplicate here

## Expected Result:
No duplicate sent/message only sent once

## Actual Result:
Showing duplicate messages in chrome and on mobile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Chrome
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 2 19 45 PM](https://github.com/Expensify/App/assets/93399543/ea626583-30bf-4cef-9c11-1d6457056e32)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Caitlin White
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689967170837339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
Not reproducible

**Comment by slafortune** [comment]
Unable to reproduce
