### ISSUE TITLE
[$1000] Web - Unable to complete payment in NewDot despite being an admin on workspace with a bank account set up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logged out
2. Cleared cache/cookies/history in Chrome
3. Signed into staging.new.expensify.com
4. Opened the chat for the payment request
5. Clicked "Pay $10,000.00 with Expensify" (in top right corner)
6. Do not enter circle appears, see video
7. Tried to then make payment from the down arrow next to "Pay $10,000.00 with Expensify"
8. Same do not enter/incomplete arrow

## Expected Result:
Click the "Pay 10k w/ Expensify" and be able to complete payment

## Actual Result:
 Arrow turns to crossed out circle/arrow combo and nothing happens to process the payment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-21 at 2 27 45 PM](https://github.com/Expensify/App/assets/93399543/d97a8125-fcc3-4350-8b61-fd802a8dffd1)

https://github.com/Expensify/App/assets/93399543/8a4a621b-ca5a-4eb7-885b-d130212b6d51

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nikihatesgh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689964259907969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dd061be424e9a81</li>
        <li>Upwork Job ID: 1683889625492779008</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
not overdue, waiting for proposals!

**Comment by isabelastisser** [comment]
Still waiting for proposals.

**Comment by sridhar02** [comment]
Contributor details
Your Expensify account email: kattasridhar02@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a20f5f5575929621?viewMode=1

**Comment by eVoloshchak** [comment]
Not overdue, still waiting for proposals

**Comment by isabelastisser** [comment]
I confirmed with Niki that this was a user error issue. Closing!
