### ISSUE TITLE
[PAY REPORTER] Dev: Web - Emails with OTP suspended see the OTP inputs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out;
2. Try to log in with a suspended email address(such as "[danut.gavrus+123@gmail.com](mailto:danut.gavrus+123@gmail.com)");
3. Verify that both OTP inputs & suspended email messages appear.

## Expected Result:
Only suspended email messages should appear.

## Actual Result:
Both OTP inputs and suspended email messages appear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  Dev 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3fef83b8-18e5-4e3e-bc6a-7acdbe4f3925

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DanutGavrus
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690186977851189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Dev - Emails with OTP suspended see the OTP inputs
### What is the root cause of that problem?
In `SignInPage`, we conditionally show the `ValidateCodeForm` using `{shouldShowValidateCodeForm && <ValidateCodeForm />}`, and the `EmailDeliveryFailurePage` using `{shouldShowEmailDeliveryFailurePage && <EmailDeliveryFailurePage />}`.
We set these bools like this:
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/signin/SignInPage.js#L65-L67
### What changes do you think we should make in order to solve the problem?
We should update the `shouldShowValidateCodeForm` bool to also check `!shouldShowEmailDeliveryFailurePage` like this:
```js
const shouldShowEmailDeliveryFailurePage = hasLogin && hasEmailDeliveryFailure;
const isUnvalidatedSecondaryLogin = hasLogin && !isPrimaryLogin && !isAccountValidated;
const shouldShowValidateCodeForm = hasAccount && (hasLogin || hasValidateCode) && !isUnvalidatedSecondaryLogin  && !shouldShowEmailDeliveryFailurePage;

**Comment by jliexpensify** [comment]
Asking internally if we want to keep this - https://expensify.slack.com/archives/C01SKUP7QR0/p1690247101560409

Will circle back once I have consensus.

**Comment by jliexpensify** [comment]
Ah, I have been told we have a PR to fix this already - https://github.com/Expensify/App/pull/23512

**Comment by jliexpensify** [comment]
Spoke to the Engineer who pushed out the PR and we agreed that although it was being fixed internally already, we'll still pay you $250 @DanutGavrus as its technically a valid bug.

I've got a job here - https://www.upwork.com/jobs/~01ce228b458badf90d

**Comment by jliexpensify** [comment]
Sorry, which bounty are you referring to?

**Comment by DanutGavrus** [comment]
The one for the Proposal/fix

**Comment by jliexpensify** [comment]
No, my understanding is that the issue was already discovered internally and a PR was already being worked on before/around the same time you reported this. We've agreed to pay out the Reporting Bonus since you did identify a valid bug.

Here is the message I received from the Engineer working on the PR in regards to timelines:

>Technically my PR was up after they reported it but I had begun fixing it before it was reported so I’m not sure. It is a valid bug, it’s just a regression from an internal PR that hasn’t been deployed yet and also already has a fix in place.

**Comment by DanutGavrus** [comment]
> [...] PR was already being worked on before/around the same time you reported this.  

> Technically my PR was up **after** they reported it but I had begun fixing it before it was reported **so I’m not sure**.

If they started before, but there is *no issue*, *no PR* & *no commit* for **~24 hours** since I've reported this, it also makes me confused. Is it possible to ask for 1 more opinion for making "sure"? 😁

**Comment by jliexpensify** [comment]
Sorry, I'm not sure what has been confusing about what I've been saying? These are the facts I'm presented with:

1. You identified an issue in this GH, and are the bug reporter: a bug report is usually eligible for a $250 payment.
2. Internally, this same issue was identified by someone in our team prior to your bug report: this is not uncommon. In these instances, we usually pay the bug reporter as a gesture of goodwill as it's a valid bug.
3. A PR was created ~1 day after your issue was reported to fix this issue: since we're fixing it internally, this then becomes an internal issue and we'll close the GH.

GIven that you are the bug reporter, you're eligible for a $250 reporting fee. 

Our team had started work on this PR when this

**Comment by DanutGavrus** [comment]
> I'm not sure what has been confusing about what I've been saying?  

I was thinking that in this cases in which there is *no evidence* of it being found internally before, it would be different, as even the internal team member was *confused* and has said *"[...] so I’m not sure."*.

But I understand the situation now, thank you very much for the explanation!

**Comment by jliexpensify** [comment]
Sorry - that part wasn't clear: the "I'm not sure" was in reference to me asking if we would pay out a reporting bonus, because technically, the internal Engineer had also identified the issue around the same time as you.

**Comment by jliexpensify** [comment]
Paid, job closed.

**Comment by DanutGavrus** [comment]
@jliexpensify ooh, ok! That was the confusion for me, so thank you for explaining!
