### ISSUE TITLE
[Hold for payment] [$1000] Web - Unable to split bills in group chat if there is a previous existing chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23470]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Create a group chat between users with no chat history or unknown users
3. Click + icon and click split bill
4. Enter amount
5. Click next

## Expected Result:
Able to split the bill since there is a previous chat between these users

## Actual Result:
Unable to split the bill since there is a previous chat between these users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/564977d4-6226-4417-b882-866a94095253

https://github.com/Expensify/App/assets/93399543/8729ab78-b22c-43eb-b54e-a44f9979d2ea

**Expensify/Expensify Issue URL:**
**Issue reported by:** Web developer | React Js | Vue Js | GH: @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687533238591329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf724daf2d526119</li>
        <li>Upwork Job ID: 1684640842357768192</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy paste does not work in the EmojiPickerMenu component

### What is the root cause of that problem?
Due to recent changes in the `Composer` component `handlePaste `method now begins with the `event.preventDefault` method:

https://github.com/Expensify/App/blob/a906877fed01ddfc32066493ba176c0863b437ab/src/components/Composer/index.js#L309-L323

This makes it work for the parent/first mounted component but preventing default behavior ends up in preventing other handlers/inputs to work as expected. Hence the expected native handler of the input does nothing.

### What changes do you think we should make in order to solve the problem?

As it was before move `event.preventDefault()` after the validations so it is indeed prevented only if the logic does apply to the current composer, something like this:

```js
 handlePaste(event) {
        const isVisible = this.props.checkComposerVisibility();
        const isFocused = this.textInput.isFocused();

        if (!(isVisible || isFocused)) {
            return;
        }

        if (this.textInput.id !== event.target.id) {
            return;
        }
        event.preventDefault();
```

Video of solution working:

[23470 solution working.webm](https://github.com/Expensify/App/assets/13544910/0deb6960-4f67-4c41-baea-552754389178)


### What alternative solutions did you explore? (Optional)
Create a new handler in the component but is just not tackling it in the root.
PS: I think this might be a regression of [23135](https://github.com/Expensify/App/pull/23135) @Santhosh-Sellavel

**Comment by NicMendonca** [comment]
@misgana96 @kbecciv I cannot reproduce this

**Comment by misgana96** [comment]
@NicMendonca it is reproducable


https://github.com/Expensify/App/assets/48551032/e57d6b2d-fd6e-4ba2-9160-7b215bbef8e8

**Comment by misgana96** [comment]
@NicMendonca after creating bill split wait for a seconds then you will see the issue

**Comment by NicMendonca** [comment]
I am not seeing that error message: 

<img width="628" alt="image" src="https://github.com/Expensify/App/assets/24947345/f84b9bfa-15db-4f4c-ae22-4deea4780ff1">

**Comment by daordonez11** [comment]
@NicMendonca  I have only seen this issue testing with "unknown" accounts,  or just people you haven't interacted with previously on NewDot

**Comment by NicMendonca** [comment]
bingo! @daordonez11 - thank you!

<img width="805" alt="image" src="https://github.com/Expensify/App/assets/24947345/721eb207-e040-41e4-8927-ae63ff3a3d98">

**Comment by NicMendonca** [comment]
asked here: 

https://expensify.slack.com/archives/C01SKUP7QR0/p1690415238521519

**Comment by NicMendonca** [comment]
@kbecciv I received the feedback that there are other bugs with issues requesting money, so this would be a dupe.

**Comment by NicMendonca** [comment]
Hmmmmm but can't find one that this open 🤔

**Comment by NicMendonca** [comment]
Okay, maybe we can use this one!

**Comment by NicMendonca** [comment]
waiting for proposals

**Comment by NicMendonca** [comment]
@aimane-chnaif thoughts on adjusting price for this one?

**Comment by pac-guerreiro** [comment]
I'm Pedro Guerreiro, an expert from Callstack, and I can take a look into this issue for you 😄

**Comment by daordonez11** [comment]
So, wanted to help a bit here. This is not an external issue, this is the resposne of the server when it fails:
```json
{
  "code": 666,
  "jsonCode": 666,
  "type": "Expensify\\Libs\\Error\\ExpError",
  "UUID": "61F4D57E-F025-4289-B7F0-483FA8EB820D",
  "message": "There is a previously existing chat between these users.",
  "title": "",
  "data": {
    "onyxData": [
      {
        "onyxMethod": "merge",
        "key": "report_38115464321979",
        "value": {
          "errorFields": {
            "createChat": {
              "1691526491040356": "There is a previously existing chat between these users."
            }
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "report_1789805569004711",
        "value": {
          "errorFields": {
            "createChat": {
              "1691526491040345": "There is a previously existing chat between these users."
            }
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "report_6637370640272364",
        "value": {
          "errorFields": {
            "createChat": {
              "1691526491040347": "There is a previously existing chat between these users."
            }
          }
        }
      }
    ]
  },
  "htmlMessage": "",
  "onyxData": [
    {
      "onyxMethod": "merge",
      "key": "report_38115464321979",
      "value": {
        "errorFields": {
          "createChat": {
            "1691526491040356": "There is a previously existing chat between these users."
          }
        }
      }
    },
    {
      "onyxMethod": "merge",
      "key": "report_1789805569004711",
      "value": {
        "errorFields": {
          "createChat": {
            "1691526491040345": "There is a previously existing chat between these users."
          }
        }
      }
    },
    {
      "onyxMethod": "merge",
      "key": "report_6637370640272364",
      "value": {
        "errorFields": {
          "createChat": {
            "1691526491040347": "There is a previously existing chat between these users."
          }
        }
      }
    }
  ],
  "requestID": "7f3a81187e4925b9-MIA"
}
```

The thing is that there is no group/chat between the 3 users I'm using for testing. Hence this should be reviewed internally and field in the backend. Probably a specific logic when a known and an unknown user are included in a split bill.

Also this is the `splits` object that is being sent:

``` json
[{"email":"dloz1996@gmail.com","accountID":14845926,"amount":20},{"email":"dloz1996+8@gmail.com","accountID":14965186,"amount":20,"iouReportID":"5328676399491147","chatReportID":"1789805569004711","transactionID":"8260801238318196639","reportActionID":"1755659752730536714","createdChatReportActionID":"5665463947453820152","createdIOUReportActionID":"8334613277377779916","reportPreviewReportActionID":"5810211507024650633"},{"email":"dloz1996+9@gmail.com","accountID":552437737,"amount":20,"iouReportID":"3799221612866612","chatReportID":"6637370640272364","transactionID":"6717224901453266037","reportActionID":"810002963011284669","createdChatReportActionID":"6078289104957976954","createdIOUReportActionID":"1182832624204545631","reportPreviewReportActionID":"2806474711423898549"}] 
```

In this case dloz and dloz+8 have chat history and dloz dloz+9 have no chat history.

Even if there is an existing chat I think it should work.

cc @mountiny

**Comment by pbkompasz** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `createSplitsAndOnyxData` methods creates the splits and 

https://github.com/Expensify/App/blob/316a54520293b636a44b1353c90ccaf461902ed6/src/libs/actions/IOU.js#L769-L785

However the `SplitBillAndOpenReport` API request returns 400.
![Screenshot from 2023-08-08 23-29-31](https://github.com/Expensify/App/assets/47194071/9b30aa91-8e30-4c3a-9b3d-b536f7b9bdad)
The splits and the reports are already created and the `report.genericCreateReportFailureMessage` is shown in every individual report.
https://github.com/Expensify/App/blob/316a54520293b636a44b1353c90ccaf461902ed6/src/libs/actions/IOU.js#L554
![Screenshot from 2023-08-08 23-39-06](https://github.com/Expensify/App/assets/47194071/ea5402b9-b820-48cd-9aec-41bf13e425ec)
![Screenshot from 2023-08-08 23-39-15](https://github.com/Expensify/App/assets/47194071/a4e48abb-bbbd-476d-ad64-00b789c62f55)

### What changes do you think we should make in order to solve the problem?


1. Fix the issue in the BE.
2.
  We should handle the case where the API request returns an error better.
  The previous operations (create individual reports, splits) should be reversed.
  We should only show the `report.genericCreateReportFailureMessage` error message in the group chat report.

### What alternative solutions did you explore? (Optional)

\-

**Comment by pbkompasz** [comment]
Another bug I discovered was that a new group chat is created even when there is existing one.
When you click on this, it redirects to Concierge and the new group is deleted.

[Screencast from 08.08.2023 23:52:43.webm](https://github.com/Expensify/App/assets/47194071/0b528e59-a5ab-483d-a49f-3b24e84e79f6)

**Comment by NicMendonca** [comment]
@mountiny vit - can you double check this? https://github.com/Expensify/App/issues/23470#issuecomment-1670272821

**Comment by r-hamid** [comment]
I have been going through the problem and it seems like the problem explained in the video is kinda not correct. I am testing this functionality on MacOS Safari, and I am unable to trigger the action while clicking on `Split EUR 100.00`.

PS: It is only happening in MacOS Safari, not in MacOS Chrome.

**Comment by mountiny** [comment]
I think this should be added to the wave3 project as a clean, this seems like another case of when the unknown and known users are used. @daordonez11 could you confirm if the bug is reproducible if all the members of the split bill are known to each other?

**Comment by mountiny** [comment]
cc @luacmartins in case you have seen this before with the split bill

**Comment by daordonez11** [comment]
@mountiny I can not reproduce this issue with known users! Only unknown

**Comment by luacmartins** [comment]
I've seen that happening for `Request money` and unknown users in the past too, not sure if that's still the case though.

**Comment by luacmartins** [comment]
@puneetlath @Beamanator did we track this as part of secure login cleanups? It seems like `Split bill` and potentially `Request money` fails the first time we request money from an unknown user.

**Comment by JmillsExpensify** [comment]
I think this is more so a wave2 consideration. Removing from wave3.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mountiny** [comment]
Waiting for another round of KI retests

**Comment by mountiny** [comment]
Waiting

**Comment by NicMendonca** [comment]
> Waiting for another round of KI retests

@mountiny sorry if this is dim - when will this retest happen?

**Comment by mountiny** [comment]
@mvtglobally Have you retested this PR?

**Comment by NicMendonca** [comment]
bump @mvtglobally

**Comment by NicMendonca** [comment]
bump bump ^  @mvtglobally

**Comment by mountiny** [comment]
bumped in slack

**Comment by mvtglobally** [comment]
No longer reprohttps://github.com/Expensify/App/assets/43995119/857136dd-1c18-4d68-b45c-4f56eb2a6b5e

**Comment by misgana96** [comment]
@mvtglobally It is still reproducible when splitting a bill between users with no chat history or unknown users
[Screencast from 01-10-2023  6:49:14 ከሰዓት.webm](https://github.com/Expensify/App/assets/48551032/a4a560cf-7390-4645-8334-d3c58bd95967)

**Comment by kbecciv** [comment]
@misgana96 Let me check between users with no chat history or unknown users, going to update shortly.

**Comment by kbecciv** [comment]
Issue is reproducible between users with no chat history or unknown users, going to update reproduction steps. @mvtglobally @mountiny 

https://github.com/Expensify/App/assets/93399543/bf5f5502-ac7d-4c6d-890d-38681d248ee9

**Comment by youssef-lr** [comment]
@mountiny I fixed this [here](https://github.com/Expensify/App/pull/28710/files#diff-17f969ae17c2a0f476494263758dbe0a535432f496b805345925e648d605915cR1405), we could do the same for `createSplitsAndOnyxData`?

**Comment by mountiny** [comment]
No update right now

**Comment by mountiny** [comment]
Still not able to prioritize

**Comment by misgana96** [comment]
@mountiny @youssef-lr 
The issue has been closed without paying for the reporter bonus. Please look it again I feel I am eligible for the reporter bonus

**Comment by youssef-lr** [comment]
Sorry about that @misgana96

**Comment by misgana96** [comment]
@youssef-lr 
No worries.

**Comment by NicMendonca** [comment]
trying to automate job creation 😬 ignore me!

**Comment by NicMendonca** [comment]
@misgana96 can you please apply to the job here: https://www.upwork.com/jobs/~0165186e4f45b91ea2

**Comment by misgana96** [comment]
@NicMendonca  Invitation accepted.

**Comment by NicMendonca** [comment]
paid!

**Comment by misgana96** [comment]
@NicMendonca You just sent me the offer but not paid. Please check it again in the upwork. The contract has started but has not paid.

**Comment by misgana96** [comment]
Accepted. Thank you
