### ISSUE TITLE
[HOLD for payment 2023-08-16][$1000] Web - App displays pointer cursor on blank spaces on PDF

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23475]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any PDF
4. Hover on empty white spaces on PDF and observe that it displays pointer cursor instead of normal cursor

## Expected Result:
App should display normal cursor on blank spaces in PDF as those areas are not clickable

## Actual Result:
App displays pointer cursor on blank spaces in PDF even though those areas are not clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8e33b89d-d82d-4af2-8419-a1b0bfc6a6bd

https://github.com/Expensify/App/assets/93399543/9d7bef26-80b5-4625-8398-71730ed49443

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690103358925329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176c574f2dce1209d</li>
        <li>Upwork Job ID: 1684765761901330432</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25868501</li>
<li>dhanashree-sawant | Reporter | 25868503</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
I can reproduce, let's polish

**Comment by krsjoseph** [comment]
I see where the problem is. The way the current setup is structured, the `PressableWithoutFeedback` component is wrapping the entire PDF view. This gives the illusion that the whole PDF, even parts that aren't intended for interaction, is clickable.

One way to fix this is by using CSS. We can create a specific class for these non-interactive parts and set the cursor to default. This way, when the cursor hovers over these areas, it won't change to a pointer.

Also, we might consider a bit of a layout reshuffle. Instead of wrapping the entire PDF view in the `PressableWithoutFeedback` component, only wrap the parts that are genuinely interactive. This would mean tweaking your render function to only wrap those interactive bits with `PressableWithoutFeedback`.

**Comment by krsjoseph** [comment]
Contributor details
Your Expensify account email: expensify@krs.dev
Upwork Profile Link: https://www.upwork.com/freelancers/~01f783a062486af74b

**Comment by AndrewGable** [comment]
LGTM!

![giphy](https://github.com/Expensify/App/assets/2838819/b685be12-ebcb-4038-b758-4aee11238f10)

**Comment by adelekennedy** [comment]
### Payouts due:

Issue Reporter: $250 @dhanashree-sawant
Contributor: $1000 @hungvu193 (Upwork)
Contributor+: $1000 @allroundexperts (NewDot)

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/jobs/~0176c574f2dce1209d).

**Comment by JmillsExpensify** [comment]
Reviewed the details for @allroundexperts. $1,500 approved for payment in NewDot based on the BZ summary above.
