### ISSUE TITLE
Web -  Request money and split money report messages change positions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from user A
2. Split money with User A
3. Notice the position change quickly from split money report being on top then goes to the bottom
4. Now go to any other chat and then return to the previous chat
5. Notice now the split bill report goes back to top.

## Expected Result:
Request money report comes after the split bill report

## Actual Result:
 Request money and split money report messages change positions

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/93399543/cc0f062d-aabd-42ac-aee7-e93045642921)

https://github.com/Expensify/App/assets/93399543/398f3e25-c54e-4097-80d9-6df79ae48c3e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690139619133119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I've tried to reproduce, but this just ends up showing a single IOU, with the request and the split in the correct order. 

### Single IOU: 

<img width="943" alt="image" src="https://github.com/Expensify/App/assets/5802477/3518da72-1b93-4302-9002-8c8b72f8dd8a">

### Request and split in the correct order

<img width="705" alt="image" src="https://github.com/Expensify/App/assets/5802477/bc2bef69-9ad3-4005-ae44-3c06e10fc13a">

**Comment by conorpendergrast** [comment]
Closing as needs reproduction steps!

**Comment by daveSeife** [comment]
This is still reproducible with the above reproduction steps. @conorpendergrast can you please share a video so I can help you in the reproduction process?
