### ISSUE TITLE
CLEANUP: Remove an unnecessary ESLint rules from `eslint-config-expensify`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#23499]
Because we changed the style guideline to use object de-structuring to assign default values, `rulesdir/onyx-props-must-have-default': 'error' is no longer relevant. Remove the rule.

**Comment by hayata-suenaga** [comment]
@spcheema unfortunately it's not but thank you for your interest

**Comment by hayata-suenaga** [comment]
will do after TS migration is over

**Comment by hayata-suenaga** [comment]
melvin, TS migration is still going

**Comment by hayata-suenaga** [comment]
melvin, TS migration is still going

**Comment by hayata-suenaga** [comment]
TS migration is still going

**Comment by hayata-suenaga** [comment]
TS migration is nearing end

**Comment by hayata-suenaga** [comment]
TS migration is nearing end

**Comment by hayata-suenaga** [comment]
TS migration is nearing end

**Comment by hayata-suenaga** [comment]
changing this issue to weekly as the TS migration finishes in the App repo! 🚀

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
> Because we changed the style guideline to use object de-structuring to assign default values, `rulesdir/onyx-props-must-have-default': 'error' is no longer relevant. Remove the rule.

@hayata-suenaga Let me know if there are any other rules that we need to remove, or maybe I should remove/adjust all rules conflicting with NewDot configuration?

**Comment by hayata-suenaga** [comment]
@blazejkustra some ESLint rules need to be removed from the Expensify ESlint, so I'll handle this 😄 🙇

**Comment by hayata-suenaga** [comment]
Removing `onyx-props-must-have-default` -> https://github.com/Expensify/eslint-config-expensify/pull/92

**Comment by blazejkustra** [comment]
> @blazejkustra some ESLint rules need to be removed from the Expensify ESlint, so I'll handle this 😄 🙇

Absolutely, all yours 😄 Let me know if there is anything I could help!

**Comment by hayata-suenaga** [comment]
The two PRs were merge and deployed. I don't know why Melvin didn't remove the reviewing label. Closing the issue now 😄
