### ISSUE TITLE
 Dev: Web - User is signed-out when adding 2FA

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Security' link
3. Click on 'Two-factor authentication' link
4. Click on 'Copy' button > click on 'Next' button
5. Enter authenticated code & verify that 2FA is added successfully
6. Close RHP
7. Click on 'Profile' avatar

## Expected Result:
User shouldn't be signed out on adding 2FA

## Actual Result:
User is signed out on adding 2FA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.44.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/778ee015-33da-4c82-828d-71aa49bb5606

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690192308790909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
@kevinksullivan This is reproducible on staging but not on prod. It might be a good idea to label this as a deploy blocker. 

https://github.com/Expensify/App/assets/57330233/7363e360-8b63-45ac-8145-4ef91de41338


https://github.com/Expensify/App/assets/57330233/959e91dd-4e20-405d-a76d-012b1d99c49b

**Comment by kevinksullivan** [comment]
@Natnael-Guchima we only pay out reporting bonus for issues that are fixed on this GH. closing out
