### ISSUE TITLE
 TextInput is overlapped when editing url preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send any url that has big preview picture (ie: fb.com)
2. Create thread with that message, while keyboard is open, long press and choose edit
3. Observer TextInput position.
## Expected Result: 
TextInput shouldn’t be overlapped
## Actual Result: 
TextInput is overlapped

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3e5e4e43-a004-4e32-b769-f75eee1f62d2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690005720959729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
@hungvu193 can you break down the repro steps further? I'm not sure I follow the path to reproduce. thanks

**Comment by laurenreidexpensify** [comment]
> Create thread with that message, while keyboard is open, long press and choose edit

Can you break these down into individual steps to follow and confirm exactly what is being long pressed. Thanks!
