### ISSUE TITLE
[HOLD for payment 2023-08-03] [HOLD for payment 2023-08-02] Web -  User is unable to paste text to 'Invite new members' & 'Members' search field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account
2. Click on 'FAB' menu
3. Click on 'Create workspace'
4. Click on 'New workspace' button
5. Copy email address
6. Click on 'Members' link
7. Paste the text to 'Find a member' search filed
8. Click on 'Invite' button & paste the text to the search field

## Expected Result:
 Text should be pasted to 'Invite new members' & 'Members' search field

## Actual Result:
Text is not pasted to the fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68ab0e12-d30b-4537-abf4-f49db88c6357

https://github.com/Expensify/App/assets/93399543/9788ff20-b277-4baa-9eaf-40fa536bac69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690270709539439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Taking this over as Yuwen just sits next to me and does not care

**Comment by mountiny** [comment]
It will be fixed by https://github.com/Expensify/App/pull/23525

**Comment by mountiny** [comment]
@flaviadefaria could you payout $250 to the bug reporter please, thank you!

**Comment by flaviadefaria** [comment]
>@flaviadefaria could you payout $250 to the bug reporter please, thank you!

Offer sent to @Natnael-Guchima

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @flaviadefaria

**Comment by flaviadefaria** [comment]
Paid! We're all done here.
