### ISSUE TITLE
Web -  Magic input showing along with delivery failure page for suspended accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Signout if you are signed in
2. Use a suspended email to sign in ([carora755@gmail.com](mailto:carora755@gmail.com))
3. Enter the email
4. Click next

## Expected Result:
Only delivery error page should be shown

## Actual Result:
Magic input showing along with delivery failure page for suspended accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45.1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/377aeef1-66c9-420f-bd80-6cc6e9df2fdb

https://github.com/Expensify/App/assets/93399543/4817dea7-00ec-4460-bbbf-475bdd6d587d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690210023703719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
magic input showing along with delivery failure page for suspended accounts
### What is the root cause of that problem?
Root cause of the issue is the wrong logic or we could say missed check in `getRenderOptions()` in SignInPage.
https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/pages/signin/SignInPage.js#L65-L67
Here when in response to api call to `/beginsignin` we receive `hasEmailDeliveryFailure` true for the suspended emails, then we are showing delivery failure page using `shouldShowEmailDeliveryFailurePage`. And for showing magic input form we have boolean `shouldShowValidateCodeForm` and as visible in the code above, it does not check for the suspended emails. That is why we see both magic input and delivery failure page together since both booleans evaluate to true in such case.
### What changes do you think we should make in order to solve the problem?
We need to check for suspended emails too before showing magic input form and for that we can add an additional boolean AND to the `shouldShowValidateCodeForm` and render the code form only when `shouldShowEmailDeliveryFailurePage` (or `hasEmailDeliveryFailure`) is false meaning the account is not suspended.
<details>
  <summary>Results</summary>
</details>
### What alternative solutions did you explore? (Optional)
Not sure if welcome header is supposed to be shown with delivery error page, if not, similar condition can be added to that too

**Comment by amyevans** [comment]
Looks like the fix for this has been CPed, I'll test on staging to confirm

**Comment by amyevans** [comment]
Looks good:

![Screenshot 2023-07-25 at 2 58 46 PM](https://github.com/Expensify/App/assets/7277067/b73bec14-a74a-4d27-9d5c-0c197b8d70e5)

Closing this out and I'll check it off the deploy checklist
