### ISSUE TITLE
[$1000] Android - Conversation - Unable to lose focus in the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19516

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any report.
3. Close the keyboard.
4. Tap on any area outside the composer.

## Expected Result:
The focus is no longer in the composer.

## Actual Result:
The focus is still in the composer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3fd90037-fecd-4e39-b34e-da6bbbae6ceb

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fed3bc57f9d46a92</li>
        <li>Upwork Job ID: 1683939326490177536</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Asked here and confirmed this is a bug: https://expensify.slack.com/archives/C01GTK53T8Q/p1690316827603909

**Comment by kbecciv** [comment]
Added comment https://expensify.slack.com/archives/C01GTK53T8Q/p1690317292376079?thread_ts=1690316827.603909&cid=C01GTK53T8Q

**Comment by rushatgabhane** [comment]
sorry for misleading, i don't think this is a bug. This is intentional on native devices

https://github.com/Expensify/App/blob/89722bf06344b2fd264af6a20ec0d0529c70b055/src/pages/home/report/ReportActionCompose.js#L139-L141

**Comment by lschurr** [comment]
Thanks! Going to close since this is intentional.
