### ISSUE TITLE
[ECard Settings] - Clean up cardList in Onyx [Step 3]

### ISSUE THREAD

**Issue by grgia** [Expensify/App#23559]
## DD Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.fg7t78w4i1po

## Step 
3. Update E/App to use only the `FUND_LIST` key

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01588700483c8cdb32</li>
        <li>Upwork Job ID: 1683863169118654464</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by slafortune** [comment]
@mananjadhav should be paid as the C+ reviewer on this for $1000 ~ did you submit a payment request in NewDot?

CC @JmillsExpensify @anmurali for payment

**Comment by mananjadhav** [comment]
@slafortune I'll submit by 08/31.

**Comment by mananjadhav** [comment]
I've raised the request on NewDot. Will let @JmillsExpensify to comment.

**Comment by JmillsExpensify** [comment]
Reviewed details for @mananjadhav. $1,000 approved for payment based on BZ summary.
