### ISSUE TITLE
Chat - Emoji Skin tone is not changing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a Chat
2. Open the emojis tab
3. Scroll down to this emoji :dancers:
4. Change the skin tone

## Expected Result:
Emoji Skin tone should be changed

## Actual Result:
 Emoji Skin tone is not changing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/862d337e-9d57-4750-8430-126d1260fcc5

![image (1)](https://github.com/Expensify/App/assets/93399543/f33673e1-3f1a-4713-b0e2-b56671656b79)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690211116461689
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
We have so many emojis without skintones. Do we have to support skintones for all emojis?
I don't think this is a bug

**Comment by s-alves10** [comment]
Emojis are unicodes. If we should support skintones for all emojis, doesn't this mean we can't use unicodes? If so, this will be a big change.

**Comment by muttmuure** [comment]
This seems like a new feature to me.

**Comment by muttmuure** [comment]
Going to close as we're focusing on bugs
