### ISSUE TITLE
[HOLD for payment 2023-08-28] [ECard Settings] Clean up cardList in Onyx [Step 4]

### ISSUE THREAD

**Issue by grgia** [Expensify/App#23560]
## DD Section
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.fg7t78w4i1po

## Step
4. Update E/App Add new Onyx key for Expensify Card data, `CORPORATE_CARD_LIST`

**Comment by grgia** [comment]
I don't have the PR up for this one yet, should be a really easy one though and could be done now

**Comment by trjExpensify** [comment]
Cool, presumably are we handling that internally? If so, I can add the `Internal` label.

**Comment by trjExpensify** [comment]
No change, Georgia is out.

**Comment by trjExpensify** [comment]
@grgia now you're back, can I confirm this needs an `internal` label and you're taking on the implementation?

**Comment by grgia** [comment]
Yes this is internal, but no C+ is required because there will be no QA or tests for this PR

**Comment by grgia** [comment]
PR merged

**Comment by trjExpensify** [comment]
So I think we can just close this, yeah @grgia? Feel free to reopen if I missed something!
