### ISSUE TITLE
New Expensify randomly logs you out

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to your account
2. Wait/use New Expensify
3. Get logged out
## Expected Result: 
You should be able to use New Expensify without being logged out.
## Actual Result: 
You randomly get logged out of New Expensify. There isn’t a set timeframe, it happens randomly.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690263927928129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I've been using NewDot all day today, and have not thus far experienced this. Discussing further[ here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1690318237635919?thread_ts=1690261679.180699&cid=C049HHMV9SM)

**Comment by jliexpensify** [comment]
@joekaufmanexpensify it's fixed now! https://expensify.slack.com/archives/C03U7DCU4/p1690273328020489
