### ISSUE TITLE
Login- The green dot accompanied by 'Link has been resent message', is not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Enter new email that doesn't have Expensify a/c
3. Tap on didn't receive a magic code
4. Toggle off internet
5. Tap on didn't receive a magic code

## Expected Result:
The green dot accompanied by 'Link has been resent message', must be displayed.

## Actual Result:
The green dot accompanied by 'Link has been resent message', is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2aeb0b29-7d2b-4b87-bd5b-91fe459603dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Not sure if I understand this one -- when does the green dot appear in the `Expected behavior` scenario? I tried reproing on iOS/Safari (unaffected platform) and it seemed to be the same behavior as the affected platforms, I didn't see a green dot 🤔

**Comment by stephanieelliott** [comment]
Ok in that case this does not seem like a bug. Gonna close for now but this may be reopened in the future.
