### ISSUE TITLE
Chat -Auth GetAccountIDsByEmails returned an error message displayed in default workspace room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Go to the default workspace room

## Expected Result:
Default workspace room displayed without any error message

## Actual Result:
"Auth GetAccountIDsByEmails returned an error" message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** .3.45-5 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2023-07-25 at 2 38 23 PM](https://github.com/Expensify/App/assets/93399543/52f7d22a-dd55-49ac-a23a-70773836cd2a)

https://github.com/Expensify/App/assets/93399543/920a7959-f34e-4877-9e13-db50974c7f0e

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by omarirfan68** [comment]
what Assignees mean ?will they only get a job

**Comment by MonilBhavsar** [comment]
PR is in review https://github.com/Expensify/Web-Expensify/pull/38313

**Comment by MonilBhavsar** [comment]
PR is deployed to prod!
