### ISSUE TITLE
Web - Contact method - App is signed out after coming from old dot and entering secondary contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.expensify.com.
2. Log in with a new account (unverified).
3. Create a new free policy.
4. After being redirected to new dot, go to Settings > Profile > Contact method.
5. Request a new magic code and enter the magic code to verify the account.
6. Enter secondary contact method.

## Expected Result:
App is not signed out

## Actual Result:
App is signed out automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3f328e46-7b01-4682-80d8-c7523b332bc7

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
okay let me do this now!

**Comment by maddylewis** [comment]
i can't actually get on staging on safari:
<img width="666" alt="image" src="https://github.com/Expensify/App/assets/38016013/1fbbfb8c-ed34-4ea3-a4e8-be4e4b656967">

**Comment by maddylewis** [comment]
i've been unable to repro this one / no proposals have come in, so im going to close this out for now.
