### ISSUE TITLE
mWeb - Chat - Autocorrect isn’t working on iOS Safari

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to new.expensify.com
2. Log in with any account
3. Select any user
4. Start typing the message

## Expected Result:
Autocorrect should be work in IOS Safari

## Actual Result:
Autocorrect isn’t working

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ec8ff0f8-c5a5-4f3f-aac2-1cc2e720393b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690204497258639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Thank you @parasharrajat i caught up on the related issues and think the best path here is to close.

**Comment by mallenexpensify** [comment]
Added to 
- [[Tracking] Safari-only bugs in NewDot](https://github.com/Expensify/App/issues/23088#top)
