### ISSUE TITLE
Desktop - Assign task - Infinite loading in the contact list when force reloading the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/22982

## Action Performed:
1. Open the testing app
2. Click on FAB > Assign task
3. Enter the title, description and go to the next step
4. Click on Assignee
5. Force reload the app

## Expected Result:
Contact list to load correctly without issues

## Actual Result:
Contact list infinitely load after a force reload of the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dc7ca854-0ed9-4691-ba47-40014d8acbfd

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@dukenv0307 I am not sure I follow here it seems Applause was able to repro in staging

**Comment by kbecciv** [comment]
@mountiny Unable to reproduce it on build 1.3.46.0

https://github.com/Expensify/App/assets/93399543/fb407da2-9b56-4c98-a1f4-41fabff489e1

**Comment by neonbhai** [comment]
@dukenv0307 @mountiny  It is reproducible, we have to *force* reload the webpage (`Ctrl + Shift + R`). Force reloading (also called Hard reloading) clears the cache before reloading the page.

**Comment by mountiny** [comment]
@thienlnam gonna let you handle this one and decide if to solve this, feels quite edge casey

**Comment by thienlnam** [comment]
Yeah I don't really think we need to address this, let's keep it closed
