### ISSUE TITLE
If we used brace sign "{}" in profile displace name it changes itself into closed bracket sign "[]"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. go to profile by clicking avatar
3. open profile
4. click display name
5. enter closed brace sing in the first name
6. click save
## Expected Result: 
display name should changed and display brace sign "{}"
## Actual Result: 
It shows a closed bracket sign "[]"
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/57c7a9e5-6677-432e-acd3-e7614a7c61ed

https://github.com/Expensify/App/assets/43996225/d703c133-deb2-4449-ae05-a28a2891fb54

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690270933445869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Closing as this is still true: https://github.com/Expensify/App/issues/14341#issuecomment-1386080994
