### ISSUE TITLE
 Avatars are cut to the side on 'Add message' page when user invites more than 12 user a time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Workspaces' link
3. Click on 'New Workspace' button
4. Click on 'Members' link
5. Click on 'Invite' button
6. Select more than 12 members & click 'Next'
## Expected Result: 
Avatars should be center aligned & shouldn't be cut off
## Actual Result: 
Avatars are cut to the left side

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5003a560-5a59-4b35-9f1a-e3cdd4c5337f

![Snip - (2) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/ca2b14b0-de25-470d-9b17-75fdadf5e3ba)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690269388882669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Looks like this was previously reported in https://github.com/Expensify/App/issues/22685 and https://github.com/Expensify/App/issues/23415 too, so closing
