### ISSUE TITLE
Enable the Workspace settings for any admin not only the policy owner

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#23624]
### Problem

As NewDot has been primarly built with Free plan in mind, that expects only one admin per policy. This means that as we are now getting to more convoluted usecases of paid plans which have multiple admins, some features were limited only for policy owners hence other admins cant take action. For example the entire workspace settings is not visible for them

### Why is it important

Any admin should be able to take actions updating the workspace settings

### Solution

Change the logic to check for policy admin instead of policy owner

cc @JmillsExpensify @Beamanator

**Comment by mountiny** [comment]
Its a role in the policy json, making a PR 🚀

**Comment by conorpendergrast** [comment]
@mountiny Need me to do anything for this so far?

**Comment by mountiny** [comment]
Nope, I think actaully there will be nothing to do here as the PR should be handled internally too

**Comment by conorpendergrast** [comment]
I am pretty sure that this is 100% done now, so I'm closing. 

@mountiny reopen if I'm wrong!
