### ISSUE TITLE
[$1000] Dev: Web - Entering Workspace settings results in console error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Profile
2. Click on Workspace
3. Create a new workspace or enter an existing one
4. Click on settings

## Expected Result:
 No console error

## Actual Result:
Error: "Warning: TextInput contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45.8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9b453a56-0303-4334-9e1a-3b7307aef268

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ygshbht
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690345216130339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019781a1059457b78c</li>
        <li>Upwork Job ID: 1684467222560501760</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
**Proposal**: @ygshbht
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690345216130339

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We are attempting to address a console error that arises when entering workspace settings.
### What is the root cause of that problem?
The root cause of this problem is that `RNTextInput `receives both `value `and `defaultValue `props. This creates ambiguity as to whether the component should behave as a controlled or uncontrolled input. React does not permit an input to be both controlled (using the `value `prop) and uncontrolled (using the `defaultValue `prop).
https://github.com/Expensify/App/blob/0fec944de6f8014f6a4586c7d4b988ffdf8ea495/src/pages/workspace/WorkspaceSettingsPage.js#L130-L138
https://github.com/Expensify/App/blob/0fec944de6f8014f6a4586c7d4b988ffdf8ea495/src/components/TextInput/BaseTextInput.js#L344-L347
### What changes do you think we should make in order to solve the problem?
To solve this issue, we need to ensure that in `BaseTextInput `, `RNTextInput `receives either a `value `or `defaultValue `prop (making it a controlled or uncontrolled component respectively), but not both. This can be implemented as follows:
`<RNTextInput {...(isControlled ? { value: props.value } : { defaultValue: props.defaultValue })} />
`
The input's controlled status can be determined based on whether `value `or `defaultValue `is passed, or whether ``onChangeText`/ `onInputChange `` are provided. Alternatively, we could explicitly pass `isControlled `from the parent. However, this might be less favorable as it introduces additional complexity and potential errors if it is not synchronized with the actual props passed.

**Comment by gadhiyamanan** [comment]
same root cause of https://github.com/Expensify/App/issues/22169

**Comment by kadiealexander** [comment]
Repro:

![image](https://github.com/Expensify/App/assets/59587260/bc33e429-1263-4596-a429-a55fa277d6fd)

**Comment by kadiealexander** [comment]
@parasharrajat could you please double check if this is the same root cause as https://github.com/Expensify/App/issues/22169 as per @gadhiyamanan's comment [here](https://github.com/Expensify/App/issues/23627#issuecomment-1651715206)?
