### ISSUE TITLE
[HOLD for payment 2023-08-17] Web - Close account – The word "continue" in Spanish is displayed with a capitalized "C" on the close account modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" menu.
2. Click on "Security".
3. Choose "Close account".
4. Enter the default contact method and click the "Close account" button.
5. Upon opening the modal, observe that the first option is displayed as "Yes, continue",  letter “c” in small.
6. Now, change the language to Spanish in the "Preferences" section.
7. Repeat steps 1 to 5.
8. Upon opening the modal again, notice that the first option is displayed as "Sí, Continuar", with the letter "C" in "Continuar" capitalized.

## Expected Result:
The letter "C" in the word "continue" should not be capitalized when the language is converted to Spanish.

## Actual Result:
 The letter "C" in the word "continue" is capitalized when the language is converted from English to Spanish.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation'

https://github.com/Expensify/App/assets/93399543/b09e4450-1ade-4d07-94f8-0c22ba8a69cd

https://github.com/Expensify/App/assets/93399543/b5b53481-f169-4871-809e-c14a0d4021ee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690357724318269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Will triage tomorrow

**Comment by sonialiap** [comment]
Confirming with the spanish translation team if there is any reason the C is capitalized

**Comment by pecanoro** [comment]
Assigning myself so I can fix this and other parts of the Spanish copy!

**Comment by pecanoro** [comment]
Closing this issue since it does not require payment. We don't pay bug reports related to Spanish copy unless it's missing copy or copy creating layout/design issues.
