### ISSUE TITLE
Web - Day is highlighted when selecting date on Bank Connection

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website on Mozilla and Chrome
2. Go to settings > Workspaces > Any workspace > Bank connection
3. Go to 2nd step of Bank Connection
4. Select "Date of birth" 's icon to open a calendar
5. Repeat this actions on both browsers (Mozilla and Chrome)
6. Here you can see Day is highlighted when opening calendar on Chrome, but on Mozilla it's not highlighted

## Expected Result:
Day shouldn't be highlighted when selecting date on Bank Connection on Chrome

## Actual Result:
Inconsistency: Day is highlighted when selecting date on Bank Connection on Chrome

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (40).webm](https://github.com/Expensify/App/assets/93399543/2b02c51d-2c2c-4035-bef6-ae76c11b456c)

https://github.com/Expensify/App/assets/93399543/7f90d277-307a-4579-ba90-a5d4b86c84ff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690352232573489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Commented in [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1690459343255259?thread_ts=1690352232.573489&cid=C049HHMV9SM), I'm inclined to close this.

**Comment by trjExpensify** [comment]
Closing!
