### ISSUE TITLE
Web - The image is reloaded when we upload an image to avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings > Avatar > Edit photo
2. Click on Avatar and upload any of your image
3. When the upload button is click ,the image is uploaded to new one. But after a bit time it's reloaded.

## Expected Result:
The image shouldn't be reloaded when we upload an image to avatar

## Actual Result:
The image is reloaded when we upload an image to avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (18).webm](https://github.com/Expensify/App/assets/93399543/5dad43fb-ea48-4804-a7ea-8d622485c06f)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690102391514009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I'm also not able to repro this, the image is uploaded as expected
