### ISSUE TITLE
Web - LHN - [Deleted message] is not being reflected on LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. on account B hover over the last message and click on reply in thread
3. Go to account A and delete the last message sent (thread originating message)
4. Go on account B and observe that [Deleted message] shows up on the originating thread reply and on header as well.
5. Compare it with the thread chat on LHN

## Expected Result:
 LHN should also reflect [Deleted message]

## Actual Result:
LHN shows the message which was deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b5544795-bd89-4980-84cd-693c0da02e57

https://github.com/Expensify/App/assets/93399543/9caa1e87-a385-411a-8d95-bea0cdd56512

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690358496233559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This looks like is related to https://github.com/Expensify/App/issues/19722#issuecomment-1649225218

**Comment by slafortune** [comment]
Closing - duplicate
