### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Split bill, request money and new chat URLs are not deep linked into native app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Paste below urls into notes or slack app
     https://new.expensify.com/split/new
     https://new.expensify.com/request/new
     https://new.expensify.com/new/chat
2. Tap the links from an iOS or Android device with NewDot installed.

## Expected Result:
The link gets opened in installed native App

## Actual Result:
 mWeb app gets opened in native browser

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/73b91f5b-41ff-430d-aa58-f6e5f3f62825

https://github.com/Expensify/App/assets/93399543/8c845ae4-d2c9-478c-be89-6a945ba725cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690357368010899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3644378786ca7b0</li>
        <li>Upwork Job ID: 1686245557430329344</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
**Proposal**: @aswin-s
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690357368010899

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Urls to split bill, request money and new chat pages are not deep linked to native app

### What is the root cause of that problem?
Path prefixes for the pages which are '/split', '/request' and '/new' are not added to apple-app-site-association and AndroidManifest files. That's the reason this URL is not recognized as a universal link by the app.

### What changes do you think we should make in order to solve the problem?
Add '/split', '/request' and '/new' URL prefixes to both apple-app-site-association file and AndroidManifest.xml

*iOS*
https://github.com/Expensify/App/blob/main/.well-known/apple-app-site-association#L10
 { "/": "/split/*", "comment": "Split Bill" }, 
 { "/": "/request/*", "comment": "Request Money" }, 
 { "/": "/new/*", "comment": "New Chat" }, 

*Android*
Add below lines to AndroidManifest.xml 

https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L65

<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/split"/> 
<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/request"/> 
<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/new"/> 

https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L78

 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/split"/> 
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/request"/> 
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/new"/> 

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by aswin-s** [comment]
Thanks @hungvu193. It got lost while copying from slack thread.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Urls to split bill, request money and new chat pages are not deep linked to native app

### What is the root cause of that problem?
Path prefixes for the pages which are '/split', '/request' and '/chat' are not added to apple-app-site-association and AndroidManifest files. That’s the reason this URL is not recognized as a universal link by the app.

### What changes do you think we should make in order to solve the problem?
Add '/split', '/request' and '/chat' URL prefixes to both apple-app-site-association file and AndroidManifest.xml

**iOS**
https://github.com/Expensify/App/blob/main/.well-known/apple-app-site-association#L10
```json
 { "/": "/split/*", "comment": "Split Bill" }, 
 { "/": "/request/*", "comment": "Request Money" }, 
 { "/": "/new/*", "comment": "New Chat" }, 
```

**Android**
Add below lines to AndroidManifest.xml 

https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L65

```xml
<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/split"/> 
<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/request"/> 
<data android:scheme="https" android:host="new.expensify.com" android:pathPrefix="/new"/> 
```

https://github.com/Expensify/App/blob/main/android/app/src/main/AndroidManifest.xml#L78

```xml
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/split"/> 
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/request"/> 
 <data android:scheme="https" android:host="staging.new.expensify.com" android:pathPrefix="/new"/> 
```
### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by JmillsExpensify** [comment]
Hmm, yeah I agree we should be deep-linking to the app if it's installed. Triaging.

**Comment by neil-marcellini** [comment]
> @aswin-s's [proposal](https://github.com/Expensify/App/issues/23643#issuecomment-1651783321) works well!

I agree! Should we also add a checklist item to update these files when new routes are added? I think we want all routes to be deep link-able.

**Comment by aswin-s** [comment]
Isn't this eligible for speed bonus? 

- PR was raised on the same day as assigned
- Approved on second day
- Just final approval took a day extra due to complications in iOS build. And no changes were requested.

**Comment by neil-marcellini** [comment]
Bump @JmillsExpensify for payment.

**Comment by aswin-s** [comment]
> Isn't this eligible for speed bonus? 
> 
> 
> 
> - PR was raised on the same day as assigned
> 
> - Approved on second day
> 
> - Just final approval took a day extra due to complications in iOS build. And no changes were requested. 
> 
> 
> 
> 

@JmillsExpensify Request you to recheck whether this PR is eligible for a speed bonus.

**Comment by neil-marcellini** [comment]
Not overdue by me

**Comment by JmillsExpensify** [comment]
@allroundexperts Coming back to the checklist not being relevant, are there any regression tests that we should put in place as a result of this new feature?

**Comment by JmillsExpensify** [comment]
I'm not sure either. We'd have to check TestRail. But you agree we should right?

**Comment by JmillsExpensify** [comment]
Can you suggest a test for this? I'll make sure one gets added.

**Comment by JmillsExpensify** [comment]
$1,500 approved for payment via NewDot based on my summary above.

**Comment by JmillsExpensify** [comment]
I'll circle back on this one after we launch a couple of things this week. Everyone should have already been paid out (though let me know if that's not the case).

**Comment by aswin-s** [comment]
@JmillsExpensify I have not received payment for this one yet.

**Comment by aswin-s** [comment]
@JmillsExpensify Gentle Reminder 👆

**Comment by neil-marcellini** [comment]
Bump @JmillsExpensify, also DMing on NewDot

**Comment by JmillsExpensify** [comment]
Apologies @aswin-s. I don't see a contract from you on the Upwork job above and it's now closed. I've created a new one and just sent you an offer.

**Comment by aswin-s** [comment]
@JmillsExpensify Accepted the offer. Do we need separate contract for reporting bonus?

**Comment by JmillsExpensify** [comment]
No need, I'll add that as a bonus on payment.

**Comment by JmillsExpensify** [comment]
All set!
