### ISSUE TITLE
Web - Remove current users from Members list if any new user added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. create workspace if not created
2. click on FAB icon and select new room option
3. enter room name , select visibility as public and click on create room button
4. go to that room
5. click on header to see details
6. go to share code and copy the code
7. click on back button to go details and go to members
7. add a member to the room using url

## Expected Result:
When second user is added, second member should be added with current room members and should not remove current members

## Actual Result:
Removes the current member and add only new member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.44-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2ce68c12-80bf-46db-b4a3-d83f0d7e8009

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690181953951299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Sorry, I missed this today. I will try to reproduce tomorrow.

**Comment by twisterdotcom** [comment]
Okay, I FINALLY got this. I kept missing the public visibility. Okay, yes. If you create a room as a user and set it to public visibility and you don't refresh the page after the sharee joins, it will show as you having been removed.

If you refresh, you see yourself as a member again.

I'm afraid though, this is a dupe: https://github.com/Expensify/App/issues/22438#issuecomment-1625824635
