### ISSUE TITLE
[WAITING ON RE-TEST] Web -  Inconsistency bug: Paypal triggers save on shift+enter

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open payment
4. If already added, then click on edit paypal.me account or click on add payment method and select paypal.me
5. Type anything and click shift+enter

## Expected Result:
App should not trigger save on shift enter for paypal.me as it does not for similar type of single line description field in request money/ split bill

## Actual Result:
 App trigger save on shift enter for paypal.me
 
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4593cc57-a942-43ed-9e47-557a86c42fe2

https://github.com/Expensify/App/assets/93399543/8db8d931-4045-4f9c-9460-df1a03e30625

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690171163554959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Is this still an issue? I just tested on Chrome on v1.3.46-0 and SHIFT+Enter does nothing for me.

@kbecciv can you retest and share a new video?

**Comment by kbecciv** [comment]
Unable to reproduce it on build 1.3.46-0

https://github.com/Expensify/App/assets/93399543/753ac3d1-5b14-4be7-89c3-3ac7796e162a

**Comment by jliexpensify** [comment]
Nice one, thanks @kbecciv!
