### ISSUE TITLE
Web - Member option in workspace members page does not show user details tooltip on name hover

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to any workspace
2. Go to members page
3. Hover over any member icon, notice it will show tooltip
4. Hover over any member name, notice it wont show tooltip

## Expected Result:
We should show tooltip on username as well like we do in other places like participants page of announce/admin rooms in a workspace

## Actual Result:
Hovering on username wont show tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/367cf9db-076a-432d-8359-b0dea9ae5466

https://github.com/Expensify/App/assets/93399543/1831a13a-6c89-4b60-bdf7-505ad1855fa2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690369921089739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
I'm not convinced this needs to be fixed
