### ISSUE TITLE
Auth GetEmailByAccountID returned an error on click of message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on FAB icon and select Split bill option
2. enter amount and click Next button
3. enter email which is not in list
4. select that user and click on Next button
5. click on that user from split bill list
6. click on Message button which will redirect to report screen
## Expected Result: 
should not show any error
## Actual Result: 
Auth GetEmailByAccountID returned an error appears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c9586650-34ab-47d9-b565-3099db4af839

https://github.com/Expensify/App/assets/43996225/a5eb38ce-4a73-4ce5-b7e5-977857a2b6c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690279806141209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0ddbbb1696d85e7</li>
        <li>Upwork Job ID: 1684323419830935552</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
I think this will need to be internal because its probably because we're not creating accounts that don't exist the first time a bill is split. Labeling Internal

**Comment by MitchExpensify** [comment]
> I think there's something to fix in frontend as well. Can we open this to contributors or add Engineering to pull up engineer?

Sounds like a plan to me! Adding the help wanted label

**Comment by MitchExpensify** [comment]
> PR 23802 disabled clicking on an optimistically generated user for profile page. So I think there is nothing required on front-end for this.

@tgolen does this sounds correct to you? (In which case we actually do not need any contributor for this)

**Comment by tgolen** [comment]
I agree. It sounds like we can simply close this out since it won't be a flow that is possible to trigger moving forward.
