### ISSUE TITLE
Back navigation not work properly in Add message screen after reload

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new Workspace
2. Choose member, then click Invite button
3. Choose any email, then click Next
4. Reload the Add message screen
5. Click on the Back button
6. Note that the Right Modal close instead of navigating back to the Invite new members screen
## Expected Result: 
Navigating back to the Invite new members screen (the previous screen)
## Actual Result: 
The right modal close immediately

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/81edb285-c01e-43e3-bbc8-f04557a16228

https://github.com/Expensify/App/assets/43996225/609827e0-e9d4-49d9-adf3-1ccfb163accc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @masha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690298949803599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## proposal from contributor: 

### Please re-state the problem that we are trying to solve in this issue.
Back navigation not work properly in Add message screen after reload
### What is the root cause of that problem?
The Navigation.goBack() is called in onBackButtonPress without any params. This lead to the problem when you reload the page, Navigation.goBack() won't work properly
https://github.com/Expensify/App/blob/4af18f632511acbbebe7c9b1e8b26f44d871d1a9/src/pages/workspace/WorkspaceInviteMessagePage.js#L175
### What changes do you think we should make in order to solve the problem?

### What alternative solutions did you explore? (Optional)
Adding this.props.route.params.policyID to the above navigation function will address the issue
So that when user reload the page, we can still navigate back correctly

**Comment by adelekennedy** [comment]
agree - we're seeing a lot of these similar bugs crop up that all go back to the same cause
