### ISSUE TITLE
[WAITING ON GEORGIA TO TEST] Desktop - User cannot drag screen if report view is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop Staging
2. Resize screen to mobile width
3. Open a chat
4. Attempt to drag the window to a different place on your screen

## Expected Result:
Window should drag

## Actual Result:
Window doesn't drag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3fc6179a-4c6b-49b9-b081-85a92f91d45a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @grgia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690379596109459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Can't repro - asking Georgia here: https://expensify.slack.com/archives/C049HHMV9SM/p1690504332431989?thread_ts=1690379596.109459&cid=C049HHMV9SM

**Comment by jliexpensify** [comment]
@grgia is this the same issue by any chance? https://github.com/Expensify/App/issues/23298

**Comment by jliexpensify** [comment]
Confirmed this is a dupe - https://expensify.slack.com/archives/C049HHMV9SM/p1690763225834529?thread_ts=1690379596.109459&cid=C049HHMV9SM

The other issue is being worked on by Rory and is a regression.
