### ISSUE TITLE
Web - No message for successful payment after adding bank account on requester end

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23680]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20821

## Action Performed:
Precondition:
As User A,
1. Create a workspace.
2. Invite User B.
3. Add Chase bank account to the workspace.
####
1. Go to staging.new.expensify.com
2. As User B, go to the workspace chat and request money.
3. As User A, click Pay on IOU preview.
4. As User A, click Pay with Expensify on IOU details page.
5. As User B, go to IOU details page and click Add Bank Account.
6. As User B, proceed with bank account page.

## Expected Result:
After saving bank account information, the payment is successful and user should see the message 'paid <amount> using Expensify'.

## Actual Result:
After saving bank account information, the message 'paid <amount> using Expensify' is not shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** unable to verify the bank flow in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ec13c724-1ee6-48a0-82ee-40cf43c355cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Adding https://github.com/Expensify/Expensify/issues/303245
Slack conversation: https://expensify.slack.com/archives/C9YU7BX5M/p1690392254893749

**Comment by luacmartins** [comment]
@kbecciv can you confirm if the personal bank account added is the same as the bank account added to the workspace? If so, the payment will fail and not seeing a message is expected.

**Comment by kbecciv** [comment]
@luacmartins When tester added a different bank as User B (checking 0000) while User A's workspace uses Saving 1111 account, PR is Pass.

https://github.com/Expensify/App/assets/93399543/80228ce9-df1e-41a6-8b68-d9b1c9c889aa

**Comment by luacmartins** [comment]
Thanks for confirming! This is not a blocker then. Closing.
