### ISSUE TITLE
Web - Display name allows html tags with spaces on either side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Click profile
2. Click Display name -> Enter "< html >"
3. Click on save -> It is not saving name and clears the value

## Expected Result:
 It should not allow html tags in name

## Actual Result:
Display name allows html tag with spaces on either sides, also not stores it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b5b3a163-905c-446b-a648-f26c8bae8cac

https://github.com/Expensify/App/assets/93399543/816b99bb-8db5-49ca-a745-3355fff55916

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690377312085029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Got it, this seems like a dupe. I'm going to close it in favour of consolidating on that issue.
