### ISSUE TITLE
When two users edit a task at the same time there is an inconsistency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) login as user A
2) tap plus sign
3) new chat
4)pick a new user B(new email)
5)now on the chat
6) tap plus sign
7) assign new task
8) add task description
9) send
10) log in with userB
11) see the chat with user A
12) user A and user B edit the title of the task with a different name and send it
13) user A can view user B's edit, and user B can see user A's edit
14 ) User A marks the task as complete (at this moment the two titles edited by user A and user B match)
## Expected Result: 
both users should see the same thing
## Actual Result: 
the two users see different titles before marking task complete
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5fdcc646-2981-49f8-a32a-3c6efa736f20

https://github.com/Expensify/App/assets/43996225/6e210256-2037-44c6-bb27-657d88345bf7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689019361341969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
@thienlnam I'm not sure what to do with this one, as I'm not entirely sure it's a valid bug, or really what the refresh expectation is.
