### ISSUE TITLE
Can’t send messages to existing chat via search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Search for chat with [@marco](https://expensify.slack.com/team/U02C0S5DUSC)
2. Open chat and send a message

## Expected Result: 
He receives the message
## Actual Result: 
Error reading Unexpected error while posting the comment, please try again laterReport no longer exists , message is not sent

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-26 at 9 20 36 PM](https://github.com/Expensify/App/assets/43996225/b749b5fe-3087-4881-93b0-234cb8d15b7b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690281284194129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Solved it with sign out sign in!
