### ISSUE TITLE
Inconsistency issue - Change currency modal is not displayed for connect bank account on reimbursements page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: Workspace default currency should be anything other than in USD
1. Click on settings > Workspace > select a workspace > Reimbursements > Connect bank account (Under "Unlock next-day reimbursements"
2. Compare it with Settings > Workspace > Select a workspace > Bank account
## Expected Result: 
Change workspace currency modal should show up for reimbursements connect bank account page as well
## Actual Result: 
Change workspace currency modal is not available for Reimbursements connect bank account page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5847e285-a50a-4a72-984e-32e2061affa7

https://github.com/Expensify/App/assets/43996225/cfd2a435-9201-4889-9952-69ad093742f4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690292407254869
https://expensify.slack.com/archives/C049HHMV9SM/p1690292407254869
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Yes this was raised before by someone else and I am not sure how much we want to focus on fixing this. if yes there should be some other reporter (older). @laurenreidexpensify up to you if you wnat to move ahead or close this

**Comment by laurenreidexpensify** [comment]
I think let's close this. Thanks folks
