### ISSUE TITLE
[HOLD on #24041] [$1000] User B's LHN is not updated with money request message sent by User A to User B

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23694]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as User A on one device.
2. Login as User B on another device.
3. With User A, request money from User B (click on FAB > Request money).
## Expected Result: 
User B's LHN should be updated with the message 'You owe $xxx'.
## Actual Result: 
Often, the LHN does not update and continues to display the previous message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needsreproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a6cc3639-5063-4a66-b185-b8aedd672fbc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ygshbht
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690024821911749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5606632d74ace94</li>
        <li>Upwork Job ID: 1684937748192702464</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal from contributor
### Please re-state the problem that we are trying to solve in this issue.
There is an inconsistency with the preview message update in the Left Hand Navigation (LHN) when money is requested between users.
### What is the root cause of that problem?
The LHN preview message is determined based on `reportActions`. However, the display message only recalculates when the report or some other data changes, not the `reportActions`. Thus, if the server sends a report update first and `reportActions `update later, the display message does not update.
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/LHNOptionsList/OptionRowLHNData.js#L72-L82
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/libs/OptionsListUtils.js#L396-L399
### What changes do you think we should make in order to solve the problem?
To resolve this, we need to recalculate the display message in LHN when `reportActions `changes as well. This can be accomplished by including `reportActions `as a dependency in the `useMemo `hook, like so:
```
const optionItem = useMemo(() => {
    // Note: ideally we'd have this as a dependent selector in Onyx!
    const item = SidebarUtils.getOptionData(fullReport, personalDetails, preferredLocale, policy);
    if (deepEqual(item, optionItemRef.current)) {
        console.log('Deep equal');
        return optionItemRef.current;
    }
    optionItemRef.current = item;
    return item;
}, [fullReport, personalDetails, preferredLocale, policy, reportActions]);
```
This adjustment ensures that whenever a change in `reportActions `occurs, the display message will be recalculated, resulting in an accurate preview message in the LHN.
### What alternative solutions did you explore? (Optional)
An alternate solution could be to pass `reportActions `as argument to the `getOptionData `function and any nested functions that require the `lastReportAction`. This way, these functions can directly access the latest `reportActions`, ensuring that they always operate on the most recent data. This change could help maintain accurate and updated preview messages in the Left Hand Navigation (LHN) section.

**Comment by ygshbht** [comment]
Thanks kavimuru. 

Here's another video demonstrating the issue. If doesn't happen always but roughly a third of the times

https://github.com/Expensify/App/assets/65986357/37fac1b6-f5db-4f5f-a812-0ffe47464392

**Comment by ygshbht** [comment]
Here's the solution video. 

https://github.com/Expensify/App/assets/65986357/72e34891-b91f-42ca-86c7-de76904a685e

**Comment by twisterdotcom** [comment]
We have some internal API updates going on right now. I'm asking if they might solve this: https://expensify.slack.com/archives/C03SDMF9YJ2/p1690475932707729

**Comment by ygshbht** [comment]
Do contributors have access to the link https://expensify.slack.com/archives/C03SDMF9YJ2/p1690475932707729? 
If you ask me, I don't think it's the backend issue here. Backend sends all the messages - if `reportActions` reaches client first, there is no issue, however if it reaches post the `report` message, you don't see the message in LHN as it depends on the `reportActions` and calculation only happens when `report` changes. That being said, **i'm really curious to see if backend tweaking is really the solution here**

**Comment by twisterdotcom** [comment]
They do not. Okay, we should open this up!

**Comment by twisterdotcom** [comment]
@parasharrajat could we just assign @ygshbht straight away on this one?

**Comment by s-alves10** [comment]
https://github.com/Expensify/App/issues/23189#issuecomment-1643844104

**Comment by s-alves10** [comment]
@hannojg 

Please share your idea here

**Comment by ygshbht** [comment]
From what i see, currently yes, issue is only for IOU

**Comment by ygshbht** [comment]
LHN already updates when report is received, so if it also updates when it receives `reportActions`, there is only one more render. If you ask me, I beleive the affect on performace is negligible. Furthermore, it does `deepEqual `test there so if the result is same, it is not going to rerender. Only when its necessary, that is during IOU type messages, which is exactly what we want

https://github.com/Expensify/App/blob/b041a2c379caf8b1fbc2df3e79468fc5a82f0a3a/src/components/LHNOptionsList/OptionRowLHNData.js#L80-L90

**Comment by hannojg** [comment]
Hey, just to add my two cents here:

We recently made a change where data from onyx is read directly from cache. This really helps with speeding up making connections to Onyx.

I'd give it a try to connect the report actions of a report to the `OptionRowLHNData.js` component, and then we can check the performance impact. I think it with the recent Onyx change it shouldn't matter too much.

@kavimuru you also said this:
> An alternate solution could be to pass reportActions as argument to the getOptionData function and any nested functions that require the lastReportAction [...]

and I would really appreciate if we can do that!

(The perfect solution IMO would be to have dependent selectors in Onyx, so that we could have a single selector for `SidebarUtils.getOptionData`, see [this proposal here](https://expensify.slack.com/archives/C01GTK53T8Q/p1689848445161859). However, this will probably take a longer time till its made its way into onyx, so I'd skip it for now)

**Comment by ygshbht** [comment]
@parasharrajat Please view some details regarding the testing here https://docs.google.com/document/d/1tQyPzWfmPlwTjrI2O9VaE0vAAETQikq0sYz6nDie-3k/edit?usp=sharing

**Comment by ygshbht** [comment]
From my observations, the **LHN** render time is relatively small compared to the time it takes to update **OptionRowLHNData**. In **OptionRowLHNData**, any subsequent render after you receive a message is fast too

**Comment by twisterdotcom** [comment]
@hannojg what do you think of @ygshbht's tests here?

Are we closer to assigning anybody, or should we HOLD on some of the larger performance changes that are ongoing?

**Comment by hannojg** [comment]
We might want to hold for:

- https://github.com/Expensify/App/pull/24041

as right now the onyx cache changes aren't part of the app code (as they have been reverted).

**Comment by twisterdotcom** [comment]
Still HELD

**Comment by twisterdotcom** [comment]
Apologies but I am finally going on Parental Leave. I am reassigning to another member of the team.

**Comment by flaviadefaria** [comment]
@parasharrajat are you able to test this and confirm next steps? Thanks!

**Comment by flaviadefaria** [comment]
I'll try and test this next week.

**Comment by flaviadefaria** [comment]
I'm struggling to test this on two separate devices. @kavimuru are you able to please re-test this? Or is anyone else able to help re-test this?

**Comment by ygshbht** [comment]
@flaviadefaria I don't think this is reproducible now as the proposed solution has already been implemented by some other unknown PR :(

**Comment by flaviadefaria** [comment]
Thanks for confirming @ygshbht so I'll close this out now.
