### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Web - Inconsistent display format for phone number contact in members page of workspace and room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Either logged in user should have primary account as phone number or logged user should have common workspace with user having primary account as phone number
1. Open the app
2. Open workspace room which has user with phone number as primary contact
3. Click on header to open details page
4. Click on members and observe the format of phone number contact displayed below display name of that user
5. Click on back and click on workspace name
6. Click on members and observe the format of phone number contact displayed below display name of that user, it is different then the one in step 4

## Expected Result:
App should display phone number contact in newer format throughout the app on details pages

## Actual Result:
App displays phone number contact in older format on room members page causing inconsistency in format between room members page and workspace members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a46055fd-3620-4794-b15b-71a135154e50

https://github.com/Expensify/App/assets/93399543/d58db0e9-992f-40ad-9afd-2122b5ce7015

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690377835176189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01584c3a7472629000</li>
        <li>Upwork Job ID: 1687057935942258688</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25991568</li>
<li>samh-nl | Contributor | 25991575</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Woot! Looks like we got proposals! cc @fedirjh

**Comment by lekhaiphtech** [comment]
For above issue, we are by default showing alternate text that's why it's showing inconsistent display format for phone number, for fixing this issue we can change alternate text to "Text" or "Search Text"

![SC](https://github.com/Expensify/App/assets/82495417/c39e01b2-757c-4ead-ba77-12666e092c38)

<img width="963" alt="Screenshot 2023-08-03 at 5 24 20 PM" src="https://github.com/Expensify/App/assets/82495417/91e08ccd-c5b3-4fff-8d9a-655c2c0bedd7">
![Expensify](https://github.com/Expensify/App/assets/82495417/84d4ba27-e476-4069-a261-07c54e32cdeb)

**Comment by dylanexpensify** [comment]
Great work here!

**Comment by dylanexpensify** [comment]
Payment summary:
- Reporter: @dhanashree-sawant $250
- Contributor: @samh-nl $1,500
- C+: @fedirjh $1,500

[Upwork job](https://www.upwork.com/jobs/~01584c3a7472629000). Please apply!

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, If possible, can you send me invite to the job?

**Comment by dylanexpensify** [comment]
Payments sent @fedirjh and @samh-nl!  @dhanashree-sawant invite to job sent!

**Comment by dylanexpensify** [comment]
Offer waiting to be accepted @dhanashree-sawant!

**Comment by dhanashree-sawant** [comment]
Thanks @dylanexpensify, I have accepted the offer.

**Comment by dylanexpensify** [comment]
Paying out!

**Comment by dylanexpensify** [comment]
all done!
