### ISSUE TITLE
[$1000] Android  - App displays broken message text without email for existing email contact on user details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on android
2. Open any report
3. Mention email only user to whom you have already chatted before (user email should not have dot in its email before @) and send the message
4. Click on mention to open details page and observe that app does not display email besides 'message' and also paritally cut the message text

## Expected Result:
App should display user email beside 'message' on user details page. If the email is too long, it should display similar to this, where `...` are on the far right of the screen
<img width="366" alt="image" src="https://github.com/Expensify/App/assets/22508304/2a88ba73-b1e6-469d-a8d8-15fde79fb37d">

## Actual Result:
 App does not display user email besides message on user details and displays truncated 'message' if we had already chatted with user and user email has no dot before @

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.43-7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cc728077-bdda-4a80-80ab-82445cb93c8f

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689956338921469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114172bcac0ccb2df</li>
        <li>Upwork Job ID: 1686155247894810624</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Was able to repro, updated the Expected behavior with
> App should display user email beside 'message' on user details page. If the email is too long, it should display similar to this, where ... are on the far right of the screen
<img width="366" alt="image" src="https://github.com/Expensify/App/assets/22508304/f766651f-aa09-482f-95ee-38ec8f9add95">

**Comment by SosenWiosen** [comment]
I think this might be a duplication of #23769. Wasn't able to reproduce on the latest main - I think it was repaired in this PR #24142 . Will check if it occurs before that.

**Comment by dhanashree-sawant** [comment]
Hi @SosenWiosen, @thesahindia, the issue is raised before #23769, if it was solved because of that issue, will it be eligible for reporting bonus?

**Comment by mallenexpensify** [comment]
Sorry for the lonnnnng delay, I was caught up in a deadline for another project. 

https://github.com/Expensify/App/issues/23769
Created on July 27th
<img width="404" alt="image" src="https://github.com/Expensify/App/assets/22508304/667fc933-4144-4849-8f29-e7d1db3f5a67">

This bug reported created on July 21
<img width="368" alt="image" src="https://github.com/Expensify/App/assets/22508304/e52f3c71-45af-4e5a-bab8-1829aa332743">

@dhanashree-sawant , it appears they are the same or similar, is there any way to 'prove' that the PR for that one fixed this?  Asking cuz it's helpful to have a link to drop in for auditing purposes if I pay this out for the reporting bonus.

**Comment by dhanashree-sawant** [comment]
From what I have seen in the PR and in that issue, root cause was 'The root cause is android use different way to break words'  (taken from [this](https://github.com/Expensify/App/issues/23769#issuecomment-1654683433) proposal) and changes was made on both details and profile page. In this issue, we had the same root cause for 'Message' text truncate on details page. Since that PR also made the changes on Details page too, the following issue seems to be fixed due that.

**Comment by mallenexpensify** [comment]
Thanks @dhanashree-sawant , it seems/sounds like, since you reported the issue first, you are due compensation for reporting the bug. (and, the other contributor was already compensated cuz that bug got fixed first so we can't/won't claw that payment back). Can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0114172bcac0ccb2df

**Comment by dhanashree-sawant** [comment]
Thanks @mallenexpensify, I have accepted the offer.

**Comment by mallenexpensify** [comment]
Issue reporter: @dhanashree-sawant paid $250 via Upwork
