### ISSUE TITLE
 Android - Lounge Access - Lounge access animation page loads with delay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/23061

## Action Performed:
1. Open the App
2. Login with any Expensifail account
3. Go to Settings -> Profile -> Lounge access

## Expected Result:
Lounge access animation page loads without delay

## Actual Result:
Lounge access animation page loads with delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/73e525fc-b566-486a-b343-c8ba709a0827

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Thanks for reporting! This is actually being addressed in the original issue where the Lounge Access page animation was added, so I'm going to close this bug report for now. In the long term, we're likely going to implement implementing DotLottie file support for iOS and Android, which should cut down animation filesizes by a huge amount. In the meantime, we're using an optimized Lottie JSON which will cut down the filesize from 4MB to 2.6MB.
