### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Web -  App displays single report in LHN for some time on login with that report link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23735]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report and pin it
3. Copy the URL
5. Logout and paste the URL and press enter
6. Login and observe that app displays report open in step 2 for some time before displaying all the results

## Expected Result:
App should load all the LHN reports together and display the URL report in focus on login with report URL

## Actual Result:
App only loads URL report for some time and displays only that report before loading all other reports on login with report URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b568650-8c03-4e19-bcae-4aa722cfd6f2

https://github.com/Expensify/App/assets/93399543/bedb449c-36d0-479e-8315-676aedf9a575

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690386361860209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018345473985202219</li>
        <li>Upwork Job ID: 1686430262619181056</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26019546</li>
<li>dhanashree-sawant | Reporter | 26019547</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
I agree, the report loads for too long upon login. Adding `External` label so we can get this worked on

**Comment by ArekChr** [comment]
> We should show the skeleton only when users login successfully and the API OpenApp returns data.

@tienifr I assume in your [proposal](https://github.com/Expensify/App/issues/23735#issuecomment-1655501796), the outcome of the solution is that the first report (from the URL) in the LHN will be hidden until the data is loaded, and instead, the skeleton will be displayed?

The first alternative solution, where the report from the URL is displayed along with the skeleton until all reports are loaded, seems interesting. What do you think, @stephanieelliott?

**Comment by stephanieelliott** [comment]
> The first alternative solution, where the report from the URL is displayed along with the skeleton until all reports are loaded, seems interesting. What do you think, @stephanieelliott?

I like it, @ArekChr ! I think that solution will feel more premium, we should show the first report as soon as it is loaded.

**Comment by ArekChr** [comment]
Great! Let's go then with the first alternative solution @tienifr
> Solution 1: We can show the single report within skeleton below if isLoading is true but the current report is loaded.

[Proposal](https://github.com/Expensify/App/issues/23735#issuecomment-1655501796) approved 👌
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by stephanieelliott** [comment]
Bump on this, @aldo-expensify

**Comment by aldo-expensify** [comment]
The proposal looks good to me too.

**Comment by aldo-expensify** [comment]
Thanks for the quick work!

**Comment by stephanieelliott** [comment]
Just noting here that this caused a regression, being worked on in https://github.com/Expensify/App/issues/24596.

**Comment by marcaaron** [comment]
I think we have a production regression for this one. See comment [here](https://github.com/Expensify/App/pull/24204#issuecomment-1682927685).

**Comment by stephanieelliott** [comment]
Hey @tienifr, can you please share the PR that addresses the regression[ mentioned above](https://github.com/Expensify/App/issues/23735#issuecomment-1682928563)? I'm not seeing that PR anywhere

**Comment by aldo-expensify** [comment]
@stephanieelliott we are considering the PR as an alternative: https://github.com/Expensify/App/pull/25159 it is in review process, it seems like it is not handling all cases 100% well yet

**Comment by aldo-expensify** [comment]
PR still under review, seems like some conflicts were incorrectly resolved.

**Comment by stephanieelliott** [comment]
Cool, thanks @aldo-expensify! Will keep an eye in https://github.com/Expensify/App/pull/25159

**Comment by stephanieelliott** [comment]
Deployed to production 8/30, updating payment date in issue title.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: @dhanashree-sawant $250, paid via Upwork 
 - Contributor: @tienifr $500, paid via Upwork ($1000 w/ 50% reduction for regression)
 - Contributor+: @ArekChr N/A (expert contrib, no payment due)
 
 Upwork job is [here](https://www.upwork.com/jobs/~018345473985202219), no speed bonus due to regression
