### ISSUE TITLE
Error message verify add contact methods disappears when opening the same page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: The account has 2FA enabled
1. Login to the account that has 2FA enabled.
2. Go to Settings > Security > Two-factor authentication.
3. Disable 2FA.
4. Wait for the email sent by the system and check its content.

## Expected Result:
Describe what you think should've happened
The path to the 2FA setting in the email's content should exactly match with the path on app

## Actual Result:
The path to the 2FA setting in the email is "Settings > Account > Account Details > Two Factor Authentication", while in the app, it's "Settings > Security > Two-factor authentication" which is confusing for the users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.45-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Emails](https://github.com/Expensify/App/assets/93399543/a9f2cb40-b6d0-405c-8b73-8341c66ac222)

![App](https://github.com/Expensify/App/assets/93399543/4010f2a4-9385-42ab-8f74-3b26c6de0e0d)

![image (5)](https://github.com/Expensify/App/assets/93399543/fda03723-8bfe-49d2-ba74-dc8be87e3fd9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690390412623969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111d4f7a3cf351cd8</li>
        <li>Upwork Job ID: 1685274752319377408</li>
        <li>Last Price Increase: 2023-07-29</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
ah, so we just need to update the automated messaging on web-e for this one it sounds like.

**Comment by maddylewis** [comment]
@mananjadhav - this should be a pretty easy one. i think all we need to do is confirm which file this automated messaging is and then update the breadcrumb path copy for the messages to NewDot users.

**Comment by mananjadhav** [comment]
Yes, this should be internal and the communication seems to be sent from the backend. Should be pretty straightforward.

**Comment by mananjadhav** [comment]
Can you assign any engineer ?

**Comment by joelbettner** [comment]
@maddylewis it is possible to get this message while using oldDot or while using newDot. The message is correct for oldDot, which is where the bulk of our customers currently are. I don't think we should change it at the moment...do you?

<img width="771" alt="image" src="https://github.com/Expensify/App/assets/13264774/6cc855c9-fe84-48bc-ab82-9d23a92de68a">

**Comment by joelbettner** [comment]
I'm going to close this issue. Feel free to re-open if you think we should change the message so it is NewDot specific or if you think we should change it so it is more vague and not specific to either platoform.
