### ISSUE TITLE
Web - Error message verify add contact methods disappears when opening the same page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
2. New New contact method
3. Add
4. Click contact just added
5. Enter wrong code
6. Copy link url
7. Open new tab and open url, Observe that the error disappears.

## Expected Result:
The error should not go away when the user is not closed

## Actual Result:
The error disappears when the user is not closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46.0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b55b0378-3d50-479d-8920-43b150bcb1ac

https://github.com/Expensify/App/assets/93399543/2da76724-0010-43b8-bae5-67663f6eae69

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690391663522399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Talha345** [comment]
This is not a bug and the intended behaviour as on refresh we require the user to enter the code again

**Comment by michaelhaxhiu** [comment]
I agree with @Talha345, this is intentional. I don't really see the use case here. I would think in the vast majority of scenarios a person won't refresh or reload the page when they are half way through the validation flow.
