### ISSUE TITLE
[HOLD # 278883] Reports don't update state until you click into them.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#23744]
This is a platform-wide issue coming from the back end, as it happens equally to messages, but whatever the case we've got to solve it. More internal discussion happening [in Slack](https://expensify.slack.com/archives/C02HWMSMZEC/p1690436052183119). 

Reproduction steps:

1. Sign into any account
2. Make sure your account have several workspace users with reports outstanding
3. Additionally, make sure that each individual has submitted reports previously, and these have been reimbursed. 
4. Click into the workspace chat 

**Actual result**: The reports don’t correctly reflect their state until you click into them – whether the report has been paid, or is still outstanding and needs to be paid. 

**Expected result**: Reports show their correct state whether or not you click into them. 

<img width="868" alt="Screenshot 2023-07-27 at 09 57 14" src="https://github.com/Expensify/App/assets/1127863/084b1352-88a9-47eb-8c70-90bff79d3634">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118840394603d0ff0</li>
        <li>Upwork Job ID: 1684594194628341760</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
Did some investigation. It seems that when we open the App the iou reports are not fetched from the backend anymore, and the report preview action in the chat doesn't contain all the info needed [here](https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/components/ReportActionItem/ReportPreview.js#L115) to properly build the report preview text. I'll open a discussion in Slack about the solution that I am thinking about, to make sure I don't break other things.

**Comment by cristipaval** [comment]
We haven't concluded the [Slack convo](https://expensify.slack.com/archives/C02HWMSMZEC/p1690550400535509?thread_ts=1690436052.183119&cid=C02HWMSMZEC) yet

**Comment by JmillsExpensify** [comment]
Our best hunch is that this is the same root cause as fetching IOU/expense reports, an initiative already being worked on. We'll keep this issue open until we confirm that's the case, though also moving this to weekly in the meantime.

**Comment by JmillsExpensify** [comment]
Still holding on #278883

**Comment by JmillsExpensify** [comment]
Closing this one, as it's now resolved since we started fetching iou/expense reports.
