### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Emoji picker closes automatically on archived task message in main thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Open any report, click plus, click assign task and assign task to any user
3. Mark task as complete, reopen the task and delete the task
4. Click on 'From' link in header and react with any default emoji
5. Click emoji picker button besides react and focus on search, observe that app closes the picker as soon as we focus on search
## Expected Result: 
App should not close the emoji picker when we focus on search while reacting on archived task message in main thread
## Actual Result: 
App closes the emoji picker when we focus on search while reacting on archived task message in main thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9cfce4d3-53b6-484b-95cb-c3226a1c5f6e

https://github.com/Expensify/App/assets/43996225/fb7be010-c8c5-4257-a749-d86a28ea776d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690440331949509
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c98ab568501035b</li>
        <li>Upwork Job ID: 1684968031861731328</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26077419</li>
<li>bernhardoj | Contributor | 26077422</li>
<li>dhanashree-sawant | Reporter | 26077423</li>
</ul></li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
@aimane-chnaif thoughts on the proposals above?

**Comment by flaviadefaria** [comment]
@aimane-chnaif can you give an update on the proposals above? Thanks!

**Comment by flaviadefaria** [comment]
@aimane-chnaif this is the 3rd issue you post "reviewing today" and nothing else. Please review it today.

**Comment by flaviadefaria** [comment]
Payment Summary:

>@bernhardoj requires payment [offer](https://www.upwork.com/nx/wm/offer/26077422) (Contributor)
@aimane-chnaif requires payment [offer](https://www.upwork.com/nx/wm/offer/26077419) (Reviewer)
@dhanashree-sawant requires payment [offer](https://www.upwork.com/nx/wm/offer/26077423) (Reporter)


@bernhardoj requires payment -  $1000 - 50% (PR merged in  more than 9 working days) = $500
@aimane-chnaif requires payment - $1000 - 50% (PR merged in  more than 9 working days) = $500
@dhanashree-sawant = $250

**Comment by flaviadefaria** [comment]
Payment Summary (updated):

@bernhardoj requires payment [offer](https://www.upwork.com/nx/wm/offer/26077422) (Contributor)
@aimane-chnaif requires payment [offer](https://www.upwork.com/nx/wm/offer/26077419) (Reviewer)
@dhanashree-sawant requires payment [offer](https://www.upwork.com/nx/wm/offer/26077423) (Reporter)

@bernhardoj requires payment =  $1000 (no bonus)
@aimane-chnaif requires payment = $1000 (no bonus)
@dhanashree-sawant = $250
