### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Web -  Emoji count and details are not dynamically updating when reactions are added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. On account A, react with :+1:
3. Right click on the reacted emoji to open the details modal
4. On account B click on the :+1: to add to the reaction
5. Go to account A and check the details modal

## Expected Result:
Details  modal should update showing the added reaction count and the account which reacted

## Actual Result:
Details modal doesn't update dynamically

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b29d133-1900-432a-a1cf-14f4ab0c5f50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690396271150109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103b055021bf558bd</li>
        <li>Upwork Job ID: 1684996447830929408</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25876690</li>
<li>tienifr | Contributor | 25876692</li>
<li>Nathan-Mulugeta | Reporter | 25876693</li>
</ul></li>
    </ul>
</details>

**Comment by s77rt** [comment]
@samh-nl Thanks for the proposal. Your RCA makes sense. The solution also makes sense but can you please explain how we will execute that? I think we used to use onyx but we changed that in this PR https://github.com/Expensify/App/pull/23371 to fix https://github.com/Expensify/App/issues/23307.

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Emoji count and details are not dynamically updating when reactions are added

### What is the root cause of that problem?
EmojiReaction is not being passed in `PopoverReactionList` dynamically component when its visible.

### What changes do you think we should make in order to solve the problem?
We need to pass `reportActionID` as a prop in `PopoverReactionList` and use `withOnyx` to get `EmojiReactions` from the `reportActionID`. EmojiReactions doesn't come from `REPORT_ACTIONS` anymore, it comes from `REPORT_ACTIONS_REACTIONS`

1. Add `reportActionID` and `emojiReactions` in `PopoverReactionList` component and add `withOnyx`
```javascript
    withOnyx({
        emojiReactions: {
            key: ({reportActionID}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS_REACTIONS}${reportActionID}`,
        },
    })
```
2. Move `PopoverReactionList` usage from [`ReportActionsView`](https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/pages/home/report/ReportActionsView.js#L357-L360) to `ReportActionsList`
```javascript
<PopoverReactionList ref={context.reactionListRef} reportActionID={reportActionID} />
```
3. Call `setReportActionID` to set `reportActionID` of the updated EmojiReactions in `ReportActionItemt`
```javascript
    useEffect(() => {
        props.setReportActionID(props.action.reportActionID);
    }, [props.emojiReactions]);
```
4. When reportActionID is updated and `PopoverReactionList` if its visible, update its content.
We can get the updated `EmojiReactions` from Onyx and reportActionID.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment]
@jfquevedol2198 Thanks for the proposal. Your RCA is correct. As for the solution, I don't see the need to move `PopoverReactionList` and couple it with `ReportActionsList` state. Also it does not make sense to change report action whenever the reaction changes. If you are viewing reactions of reportAction A then changes to reportAction B should not effect you.

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA is correct. The solution makes sense but I think it's better to avoid passing by `ReportScreen` as we will end up rendering that component whenever we open a new reaction list. I see that the main problem is on how we can pass `reportActionID`. I have an idea not sure it would work or if it's well optimised but worth the investigation, what if we split the `PopoverReactionList` into two components, one that handles the real logic and subscribes to `emojiReactions` and another which is just a wrapper that we use to render that component.

We call `showReactionList` with `reportActionID` on the wrapper -> set state to that new report action id -> render the underling component passing `reportActionID={this.state.reportActionID}`.

**Comment by s77rt** [comment]
@samh-nl Thanks for the update. I don't think we want to go with that solution, there should be only one `PopoverReactionList`.

**Comment by s77rt** [comment]
@tienifr Thanks for the update. Indeed once we have the `useOnyx` hook things will get much easier but I don't think we should block on that. The alternative solution looks good to me. Let's go with that.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/23752#issuecomment-1656700372)

**Comment by flodnv** [comment]
Sounds good 👍

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23371
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23371#discussion_r1276569286
- A discussion in #expensify-bugs has been started: Not needed as there is not much to discuss, the regression could have been caught during PR review/test 
- Determine if we should create a regression test for this bug: No

**Comment by NicMendonca** [comment]
Everyone has been paid 🎉
