### ISSUE TITLE
Dev: Web - The message "This is the beginning of your chat" is displayed in LHN when the user deletes the requested money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to user A's account.
2. Open user B's chat.
3. Go to the "Request money" section.
4. Enter an amount and send the request.
5. Open the details of the requested money.
6. Open another browser and log in with user B's account.
7. Open user A's chat and view the details of the requested money.
8. Go back to user A's account.
9. Delete the requested money.
10. Notice that the message "This is the beginning of your chat" is displayed in LHN as the last message

## Expected Result:
The message "This is the beginning of your chat" should not be displayed in LHN when the user deletes the requested money.

## Actual Result:
The message "This is the beginning of your chat" is displayed in LHN when the user deletes the requested money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.46-0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/86287890-acaa-472a-9601-188389658623

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690405933500569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Also known and being worked on in https://github.com/Expensify/Expensify/issues/302985. Closing.
