### ISSUE TITLE
Dev: Web - After user A deletes a requested money chat, Chat displayed empty for user B

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to user A's account.
2. Open user B's chat.
3. Navigate to the "Request money" section.
4. Enter an amount and send the request.
5. Open another browser and log in with user B's account.
6. Open user A's chat.
7. Go back to user A's account.
8. Delete the requested money.
9. Check chat from userB account

## Expected Result:
The chat should not be displayed as empty when user A deletes the requested money

## Actual Result:
The chat is displayed as empty for user B account after user A deletes the requested money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.46-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b65bfdc-ffaa-4a88-b246-49f35a349a89

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690403743744759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is known and we have a PR for it. Closing.
