### ISSUE TITLE
[HOLD] Website preview is shown for email addresses sent as a message in rooms

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace if you don't have one
2. Go to #admin of the WS
3. Send a message with an email address
4. Send a message with a website URL
5. Click into a different chat, then go back into the #admin of WS

Another test case
1. Create a room or open an existing one
2. In the room, send a message with an email address
4. Then send a message with a website URL
5. Click into a different chat, then go back into the room

## Expected Result:
Website previews is not should be available for email

## Actual Result:
Website preview is available for email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.46.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a850f443-9de0-47f0-8240-6a20bc401ad4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690385758858429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb6df989a6cc8739</li>
        <li>Upwork Job ID: 1684904931252207616</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Reproducible

<img width="817" alt="image" src="https://github.com/Expensify/App/assets/17131195/14ae8f83-7444-421b-b7ae-84c0a60cc04e">

**Comment by sonialiap** [comment]
I reproduced this on Desktop app, added that to the platform list

**Comment by sonialiap** [comment]
@marcaaron why is this on monthly? What are we holding for? Is this still an issue or can we close?

**Comment by marcaaron** [comment]
The feature was rolled back so technically there is "no bug". I am still tracking the issue in a list of improvements for when we bring it back (if we bring it back). I think probably we can remove your assignment here though as there's nothing actionable. Thanks!

**Comment by marcaaron** [comment]
Removing the Monthly so Melvin chills out.
