### ISSUE TITLE
Web -  User is taken to concierge instead of chat screen when IOU is deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23785]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from account A to account B
2. Open the IOU report by clicking on the report preview
3. Do the same (step 2) on account B
4. Delete the IOU request from account A
5. Observe where account B is redirected

## Expected Result:
Account B should be redirected to the chat report just as it does for account A

## Actual Result:
Account B is redirected to concierge

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0439ff79-27d7-4a5b-ba98-7a2c94aa58e7

https://github.com/Expensify/App/assets/93399543/2fa721be-1342-48d5-b27f-50fab9b51be3

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690536863093449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
This is the [PR](https://github.com/Expensify/App/pull/19095) which introduced this feature.

**Comment by flodnv** [comment]
@luacmartins if you can confirm that, can you remove the deploy blocker and unassign me? Thanks!

Discussion here: https://expensify.slack.com/archives/C049HHMV9SM/p1690546811937609?thread_ts=1690536863.093449&cid=C049HHMV9SM

**Comment by mountiny** [comment]
this is not a blocker, this issue is known and its being tracked in a follow up issues.

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/20908

**Comment by Nathan-Mulugeta** [comment]
Are those two issues related @luacmartins ?

**Comment by luacmartins** [comment]
Yes, the issue happens because we keep those chats in the navigation stack but when the reports are deleted, we default to navigating to the Concierge chat. We're creating a way to clear the navigation stack in the issue I linked above, which would also solve the issue mentioned in the current issue.

**Comment by Nathan-Mulugeta** [comment]
Okay thanks for the explanation 😊
