### ISSUE TITLE
Web - Inconsistent behavior when signing in with email "example@example.com"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access the staging Expensify.
2. Attempt to sign in using an email address with an incorrect format, such as example.example.com.
3. Receive guidelines to correct the email address and click on "Go Back".
4. Add "example" in front of the email (e.g. exampleexample.example.com) multiple times until it allows you to sign in.
5. Note that this behavior is inconsistent and confusing for users, as sometimes it redirects to the guideline page and other times it allows sign-in without following the guideline.

## Expected Result:
 The app should consistently provide guidelines for correcting the email address format and only allow sign-in after following the correct format.
 
## Actual Result:
The app inconsistently redirects to the guideline page or allows sign-in without following the correct email format, causing confusion for users. Additionally, in some cases, it allows sign-in without following the guideline at all, which is a security concern.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6cca1210-3a60-474a-adf6-e4a52719589a

https://github.com/Expensify/App/assets/93399543/83464dd5-7e6b-4e46-8088-b6a15c6a34d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690530447044859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jjcoffee** [comment]
I don't think this is a bug, but if it is, it's all coming from the BE which returns a `hasEmailDeliveryFailure` flag:

![image](https://github.com/Expensify/App/assets/27287420/5df8cbc7-38e6-40b3-a147-4ca8a09b003e)

Presumably this is for the specific email entered rather than a pattern match, so this would be expected behaviour.

**Comment by slafortune** [comment]
Yeah - I don't feel that this is a bug either, and that is an email.
