### ISSUE TITLE
Wrong amount is being shown on IOU preview after removing request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. Click on the IOU preview on both accounts
3. On account B reply inside the IOU report screen
4. Delete the IOU request from account A
5. Go back to the chat report screen on account A and account B
6. Make another request from account A to account B
7. Open the IOU report on account A
8. Delete the last IOU request
9. Observe the amount on the IOU preview on both account A and account B
## Expected Result: 
Account B's IOU preview should show the amount to be 0
## Actual Result: 
Account B's IOU preview shows the last requested amount where account A shows the amount to be 0

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9234251a-c849-4f7a-a409-fb416bc22938

https://github.com/Expensify/App/assets/43996225/6f1e22e3-da3d-4944-8a82-744c16d823bc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690538762799099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
cc @luacmartins

**Comment by mountiny** [comment]
This might be a dollow up issue we alreadey have logged and its not a blocker I think but gonna wait for Carlos to confirm

**Comment by luacmartins** [comment]
I think it's related to https://expensify.slack.com/archives/C02HWMSMZEC/p1690436052183119, where the report state is not updated
