### ISSUE TITLE
mWeb- Workspace- Uploading avatar in offline is not greyed after tapping save button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-con: Have a workspace created
1. Go to https://staging.new.expensify.com/
2. Login with credentials
3. Tap Profile icon
4. Tap workspace
5. Tap on workspace name
6. Tap on workspace avatar
7. Toggle off internet
8. Upload new avatar
9. Tap save
10. Tap save

## Expected Result:
After uploading photo and tapping second time save button, in offline mode, the avatar must be greyed out.

## Actual Result:
After uploading photo and tapping second time save button, in offline mode, the avatar is not greyed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12c504c4-de8c-4346-a0f8-02d52d885ece

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This looks like a general onyx merge issue. Though @samh-nl 's solution may solve the issue, I think that is only a workaround.
It'd be better if onyx merge have option like `deepMerge`

**Comment by NicMendonca** [comment]
> the avatar must be greyed out.

sorry, I don't understand this! Why must the avatar be greyed out?

**Comment by NicMendonca** [comment]
@kbecciv bump! I don't fully understand this bug

**Comment by NicMendonca** [comment]
Not a bug: https://github.com/Expensify/App/issues/13957

**Comment by lanitochka17** [comment]
Issue reproducible. Build 1.3.53-1

https://github.com/Expensify/App/assets/78819774/d8107664-7f2f-421a-ad24-3b320bc6a375

**Comment by NicMendonca** [comment]
Internal eng confirmed this was done on purpose. With the Offline UX patterns, that was the right call, i.e. this is not a bug. More details here: https://github.com/Expensify/App/issues/13957
