### ISSUE TITLE
[$1000] Reply in Thread page flickers when navigating from the message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to any chat
2. Send a message
3. Press Reply in Thread on the message
## Expected Result: 
The thread page directly opens with the main thread message.
## Actual Result: 
The thread page shows the chat header for a second and then shows the thread message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/81b90056-627e-45ac-912b-d8be5d0e58d7

https://github.com/Expensify/App/assets/43996225/5fa011e5-c215-414e-9d62-e21af6ec3c7f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690459548064709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6896bd2259fc866</li>
        <li>Upwork Job ID: 1684971555250601984</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
reproducible - I'm not seeing a matching issue open but I think this is known and my instinct is this is an internal issue

**Comment by s-alves10** [comment]
Same RCA as https://github.com/Expensify/App/issues/23638 and someone is working on this

**Comment by adelekennedy** [comment]
thank you @s-alves10! I think i will close this for now as it will be fixed by #23638
