### ISSUE TITLE
mWeb- Compose- When user applies bold markdown to emoji, it is not applied

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a conversation
3. Send _ emoji_
4. Send ~emoji~
5. Send *emoji*

## Expected Result:
For italic and strikethrough markdown for emoji is applied, so for bold also markdown for emoji must be applied.

## Actual Result:
For italic and strikethrough, markdown for emoji is applied. But for bold, markdown for emoji is not applied.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5e1075d1-03c6-470c-97fb-8c69100341cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
How should it be displayed with bold? Their font-weight is already bold

![image](https://github.com/Expensify/App/assets/126839717/e04cc29d-5b77-4012-b4a1-b5d1123da580)

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
fixing [here](https://github.com/Expensify/App/issues/14676)
