### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Handle mentions renderer not receiving props

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#23811]
# Problem
If for some reason the back-end doesn't return props that the mentions renderer expects, this causes the app to crash. 

# Solution
In the mentions renderer, handle the case where the expected props aren't provided. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125cc67eabd576779</li>
        <li>Upwork Job ID: 1684978455578161152</li>
        2023-07-28<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25816064</li>
<li>tienifr | Contributor | 25816067</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I'm going to assign this to @tienifr as we have already discussed this over email. @tienifr can you please post your proposal here?

**Comment by saalimzafar** [comment]
function MentionUserRenderer(props) {
    // Check if the required props exist
    if (!props.tnode || !props.currentUserPersonalDetails) {
        // Return a fallback UI or null when required props are missing
        return null;
    }

// Rest of the component's logic

**Comment by puneetlath** [comment]
@danieldoglas I'll take this since it deals with mentions and I'm already assigned here: https://github.com/Expensify/Expensify/issues/302711

**Comment by puneetlath** [comment]
@aimane-chnaif friendly bump on the checklist. 

@tienifr has been paid.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
