### ISSUE TITLE
IOU - Deleted money request is shown when returning online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23827]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Log in
3. Disable internet connection on the device
3. Open a chat and create a money request
4. Delete the money request
5. Enable internet connection on the device

## Expected Result:
The IOU is still deleted and is not displayed

## Actual Result:
The IOU is shown as active.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3e3d53d9-efb9-4636-9540-9ae64560730c

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is known and was addressed [here](https://github.com/Expensify/Web-Expensify/pull/38305/files) in the API layer, so not an App blocker. Also the attached video doesn't match the issue description.
