### ISSUE TITLE
"Hmm.. it's not here ..." message is shown while open #admin or #announce setting after changing  "Contact methods"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Go to setting
2- add a new contact method
3- make it as default
4- remove the old contact method
5- Go #admin or #announce workspace details
6- click on the workspace name ==>"Hmm.. it's not here ..."
7- works only after refreshing the page
## Expected Result: 
Clicking on the workspace name should show the setting
## Actual Result: 
Clicking on the workspace name shows the message "Hmm.. it's not here ..."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[default-contact.webm](https://github.com/Expensify/App/assets/43996225/1622e420-f4d3-438c-8342-a69bdbb3b390)

https://github.com/Expensify/App/assets/43996225/a666ab46-4a59-4c51-a31c-4bad90a7043e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690466597724349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
@mountiny @Beamanator can you confirm if this is correct https://github.com/Expensify/App/issues/23820#issuecomment-1656306799 thanks

**Comment by mountiny** [comment]
Yes, that will resolve it, I think we can close this one then with no bug report payment as the solution has already been at works
