### ISSUE TITLE
 A required field error is not shown on Zip/postcode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go profile > Personal detail > Home Address Page
2. Click on Save
## Expected Result: 
A required field error is shown on Zip/postcode
## Actual Result: 
A required field error is not shown on Zip/postcode

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/43996225/c540b006-06b6-4ded-9ae1-66b030706fe0)

![Snip - (15) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/ef7018c3-1f66-46b5-8678-0a3cf2fdd6c9)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690478015832669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
This is not a bug. Not all countries make use of a zip / postcode system so there are cases where it is optional.

**Comment by michaelhaxhiu** [comment]
Yep - agree with @akinwale, and thanks for chiming in so fast btw :)
