### ISSUE TITLE
Report Recipient Local Time appears when not DM 1-1

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23837]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open 2 account on 2 browsers
2. A create a group with B and Concierge
3. From B open group chat, observed receiver time output appearing when not DM 1-1
## Expected Result:
receiver time not appearing in a group chat
## Actual Result:
receiver time appearing in a group chat
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.47-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/85c550b5-61bf-4bd2-b651-8d6de5c33842

https://github.com/Expensify/App/assets/43996225/98f0e937-0106-48bb-a934-a56e20b32ba7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690478849291659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal
by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
Receiver time not appearing in a group chat
### What is the root cause of that problem?
Here logic shows receiver time
https://github.com/Expensify/App/blob/b50948a930edf94eb2666790875c9b0332d76359/src/pages/home/report/ReportActionCompose.js#L1026
And
https://github.com/Expensify/App/blob/b50948a930edf94eb2666790875c9b0332d76359/src/pages/home/report/ReportActionCompose.js#L986-L987
In the function `canShowReportRecipientLocalTime` we are removing EXPENSIFY_ACCOUNT_IDS to get the number of members in the report
https://github.com/Expensify/App/blob/b50948a930edf94eb2666790875c9b0332d76359/src/libs/ReportUtils.js#L745-L747
So this function will return true and show the time
### What changes do you think we should make in order to solve the problem?
We should not remove `EXPENSIFY_ACCOUNT_IDS` to check if this is a 1-1 chat or not.
```
const hasMultipleParticipants = reportParticipants.length > 1;
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User is unable to see the Recipient Local Time.

### What is the root cause of that problem?
- Recipient Local Time is not being displayed as below condition is getting `false`:
https://github.com/Expensify/App/blob/b50948a930edf94eb2666790875c9b0332d76359/src/libs/ReportUtils.js#L750
- which is an expected behavior as we don't want to show the local time if the Recipient has not sent any message to the User.

### What changes do you think we should make in order to solve the problem?
- Here we need to decide on whether we want to show the local time or not if the Recipient has not sent any message to the User. Based on that above issue should be resolved.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment]
Duplicate Issue: https://github.com/Expensify/App/issues/23836
Please remove one of the issue.

**Comment by NicMendonca** [comment]
Hmmm, I wonder if because Concierge doesn't have a local time, if its fine to show the local time of the non-Concierge person in the group? 

@kavimuru what happens when you add an additional person? 2 people + Concierge?

**Comment by NicMendonca** [comment]
>  Logic will think this is a 1-1 chat and show the local time.

Got it, and isn't that what is happening? You said the actual result is that the receiver time appearing in a group chat

**Comment by NicMendonca** [comment]
got it! I don't think this is a bug. Going to close
