### ISSUE TITLE
Task cannot be marked complete

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Have a task assigned to you
2. Rename the task
3. Get an error
4. Assign the task back to you
5. Mark the task as complete

## Expected result: 
Task should be completed and there is no error
## Actual result: 
Error appears saying I don't have permission to complete the task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5eaa9af7-ff32-4a14-bf50-b79c8f8aede3

https://github.com/Expensify/App/assets/43996225/74eb944a-7a18-4aa5-8787-d7053ccb3562

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690471361981139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01116af54c8d03f7f6</li>
        <li>Upwork Job ID: 1686043740570476544</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment]
I also found the issue to be on the back end. 

Here's the response I got after trying to mark the task as complete. 

![expensify-completing-task-backend-response](https://github.com/Expensify/App/assets/79470910/124af6a8-1478-4a2d-b7c8-53a180030a20)

On the other hand, if you follow the reproduction steps while offline, you'll be able to mark the task as complete.

**Comment by Beamanator** [comment]
@thienlnam this looks similar to some other task issues you've been working on, right? Do you have a tracker for task cleanup issues?

**Comment by thienlnam** [comment]
This should be fixed on prod now, the BE fix was deployed https://github.com/Expensify/Auth/pull/8277

**Comment by thienlnam** [comment]
I'm still working on to update permissions on the FE, but this should be good now
