### ISSUE TITLE
Expensify Website preview is generated for a video attachement

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A: send a mp4 file to User B
2. User B: open the Chat with user A
3. User B: Notice how underneath the shared video a URL preview displays that is the preview for the expensify website
## Expected Result: 
I wouldn't expect any link preview to show up when sharing a file
## Actual Result: 
A link preview is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-27 at 20 10 14](https://github.com/Expensify/App/assets/43996225/47f37feb-427b-415d-970a-3fde3fb8bff1)

![Snip - (15) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/43996225/5523b8ca-105f-4d2f-a239-06c26adb10a1)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690481404372209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
@bondydaa do you know if that's correct? https://github.com/Expensify/App/issues/23838#issuecomment-1656547895

**Comment by lschurr** [comment]
Just assigning you @bondydaa for your eyeballs

**Comment by bondydaa** [comment]
no it won't be handled on https://github.com/Expensify/App/issues/22837 that is about SVGs not videos. 

I was OOO, just seeing this. Again I don't think this is a bug and it should be polish of the Link Preview project. 

The people involved there should be handling these things IMO.

**Comment by lschurr** [comment]
Great, thanks for the thoughts @bondydaa!

**Comment by lschurr** [comment]
I'm closing this one out since the Slack thread indicates this is a dupe.
