### ISSUE TITLE
[$1000] Web - Optimistic expense request page is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23847]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A with policyExpenseChat beta permission
2. Create workspace if not exist
3. Invite user B to workspace
4. Login user B on another device
5. On B, Go to invited A's workspace chat
6. Disable network
7. Request money
8. Click ReportPreview to go to expense report
9. Click IOUPreview to go to expense request

## Expected Result:
Expense request page is correctly created optimistically

## Actual Result:
Optimistic expense request page is broken (i.e. composer hidden)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a3dce83c-b1dc-4678-bfc9-7f3e82fceadb

https://github.com/Expensify/App/assets/93399543/b90eed5f-cd77-4682-a246-291a286ae657

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690544874408279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01414f6ff1313a444f</li>
        <li>Upwork Job ID: 1687243446963855360</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by ygshbht** [comment]
All my permissions return true, yet I don't see `Request money` option. Though I do see `Split Bill` option. Or is this feature only available in a special room? It doesn't work in #announce or any other normal room. I can currently only request money in 1-1 chat

**Comment by Christinadobrzyn** [comment]
Thanks @bernhardoj! I'll watch https://github.com/Expensify/App/pull/23815 is to see if it resolves this issue

**Comment by rezkiy37** [comment]
> Thanks @bernhardoj! I'll watch #23815 is to see if it resolves this issue

FYI: https://github.com/Expensify/App/pull/23815#issuecomment-1660110273

**Comment by Christinadobrzyn** [comment]
Awesome! Thank you @rezkiy37! I'll close this as fixed based on https://github.com/Expensify/App/pull/23815#issuecomment-1660110273

**Comment by situchan** [comment]
@Christinadobrzyn I might be eligible for reporting bonus and this bug was reported on slack before that PR.

**Comment by Christinadobrzyn** [comment]
Hey @situchan can you give me the details of the timeline so I can review it? I need to remember our guidelines on reporting bonus for regressions...

**Comment by situchan** [comment]
I [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1690544874408279) on slack on Jul 28 11:47
[PR](https://github.com/Expensify/App/pull/23815) which fixes this issue was opened on Jul 28 18:13
It seems no one was aware that this happened on expense request page before [this comment](https://github.com/Expensify/App/issues/23847#issuecomment-1656737335)

**Comment by Christinadobrzyn** [comment]
Thanks @situchan our [guidelines](https://stackoverflowteams.com/c/expensify/questions/11260/11261#11261) [internal doc added for reference] do allow for me to pay you as the reporter on the regression. Would you like for me to pay you through Upwork?

**Comment by situchan** [comment]
yes upwork. thanks

**Comment by Christinadobrzyn** [comment]
Adding External label to create Upwork job to pay @situchan for reporting based on - https://github.com/Expensify/App/issues/23847#issuecomment-1662942237

Feel free to ignore @mollfpr

**Comment by Christinadobrzyn** [comment]
Upwork job here

Internal: https://www.upwork.com/ab/applicants/1687243446963855360/job-details
External: https://www.upwork.com/jobs/~01414f6ff1313a444f

Feel free to accept the offer when you can @situchan

**Comment by Christinadobrzyn** [comment]
Paid @situchan in upwork - closing this!
