### ISSUE TITLE
Contact details and local time aren't showing up for the phone number contacts.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website.
2. Go to the chat report of a Phone number user.
5. Open the User profile.
6. Observe that the phone number and local time of the user aren't showing up.
## Expected Result:
Contact details and local time should show up like they do on email contacts.
## Actual Result:
Contact details and local time aren't showing up for phone number contacts.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.47-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0705e4f3-6236-4859-b26b-92cf344e8180

https://github.com/Expensify/App/assets/43996225/5193bc67-822b-4a55-82cd-0e8e08fee05a

**Expensify/Expensify Issue URL:** 
**Issue reported by:**  @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690502729273919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
This is expected behaviour as until the `Recipient` doesn't send any message to `User` it is counted as invalid login and thus `login` key is not found in `personalDetails` of Recipient, in-turn hiding the options.

**Comment by conorpendergrast** [comment]
I agree - once the account replies, the timezone and contact details are shown 

<img width="861" alt="image" src="https://github.com/Expensify/App/assets/5802477/c6eff7d8-2c10-4bd8-9db8-355137a1acbc">
