### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Web -Pointer cursor is displayed on send button even when compose box is empty

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report and hover on send button

## Expected Result:
 'not-allowed' cursor should be displayed on send button when there is no text in compose box

## Actual Result:
Pointer cursor is displayed on send button even when there is no text in compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8ec7dd22-4e14-41c6-b426-3dbb2a18eea7

https://github.com/Expensify/App/assets/93399543/6f0b0f83-6265-4873-9d44-45780d43fe0b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690618580440309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb9c3994ff691de4</li>
        <li>Upwork Job ID: 1685975218636345344</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 25955399</li>
<li>Nodebrute | Contributor | 25990051</li>
</ul></li>
    </ul>
</details>

**Comment by Beamanator** [comment]
@c3024 that looks exactly why this is failing 👍 

Do you have a chance to put up a PR quickly?

**Comment by Beamanator** [comment]
Actually it looks like `disabled` was removed here: https://github.com/Expensify/App/issues/23848

**Comment by Beamanator** [comment]
Thanks @c3024 ! assigned!

**Comment by Beamanator** [comment]
@thesahindia FYI this is a deploy blocker and I already approved @c3024 's solution (see above) - please take a look, and once there's a PR please prioritize if you can, or let me know if you aren't able to 🙏

**Comment by rushatgabhane** [comment]
I don't think it's the correct solution, the logic for disabling send button is move here -

https://github.com/Expensify/App/blob/9e4deb5720e74e97d583303f5000adb7e72057ff/src/pages/home/report/ReportActionCompose.js#L993-L994

**Comment by rushatgabhane** [comment]
This is not a deploy blocker because only the pointer is different.
Disabling logic is still the same.

**Comment by Beamanator** [comment]
@rushatgabhane oooooooh thanks for the context & link! Good catch.

> This is not a deploy blocker because only the pointer/cursor style is different.
Disabling logic is still the same.

Fair 👍  Making not a blocker & will unassign @c3024 until we get to the best solution, thanks! 🙏

**Comment by rushatgabhane** [comment]
@c3024 maybe lookup something in react-native-reanimated for a solution :)

**Comment by PauloGasparSv** [comment]
Hey @thesahindia can you please review the latest proposals we received here? : )

**Comment by rushatgabhane** [comment]
> We can use a variable here to avoid repetition like this

where will you use this?

**Comment by rushatgabhane** [comment]
ok i haven't tested it and don't know which thread the Tap function gets executed. 

@Nodebrute could you please confirm how and which execution thread fors Tap get executed?

**Comment by rushatgabhane** [comment]
That is not what I meant 😅
Tap() is a react-native-reanimated function. It may not run on the JS thread. We just need to confirm that

**Comment by rushatgabhane** [comment]
@thesahindia no no it's okay, I got too excited 😅

**Comment by PauloGasparSv** [comment]
Hey, I'm focused here so haven't checked the updates here yet.

I'll re-assign this to @rushatgabhane as I see a 👍 in the post above!

**Comment by rushatgabhane** [comment]
https://github.com/Expensify/App/issues/23848#issuecomment-1658513794

C+ reviewed 🎀 👀 🎀

**Comment by Pujan92** [comment]
@rushatgabhane @Nodebrute @PauloGasparSv  It is taking the pressed effect which we are preventing earlier by passing the `disabled` prop for `PressableWithFeedback`. I am not sure whether that needs to be handled here but I think only disabling the cursor won't solve this issue.

https://github.com/Expensify/App/assets/14358475/3864a1a1-f1e3-47fe-81e5-ce1ac2530668

**Comment by rushatgabhane** [comment]
@Pujan92 i don't think we can do better

it was intentionally removed because the disabled state will be out of sync with the composer empty state https://github.com/Expensify/App/issues/23848#issuecomment-1661492718

**Comment by Pujan92** [comment]
Ok, somehow it gave me a little bad UX feeling so I thought to share it here.

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

-  External issue reporter - @dhanashree-sawant - $250, job accepted in Upwork
-  Contributor that fixed the issue - @Nodebrute - $1000 + $500 urgency bonus, job accepted in Upwork 
-  Contributor+ that helped on the issue and/or PR - @rushatgabhane $1000 + $500 urgency bonus, please request in newdot

**Comment by laurenreidexpensify** [comment]
Updated Payment Summary:

External issue reporter - @dhanashree-sawant - $250, paid in Upwork
Contributor that fixed the issue - @Nodebrute - $1000 + $500 urgency bonus, paid in Upwork
Contributor+ that helped on the issue and/or PR - @rushatgabhane $1000 + $500 urgency bonus, please request in newdot

@rushatgabhane please complete teh final steps above so we can close this out. Thanks

**Comment by laurenreidexpensify** [comment]
Not overdue - waiting on Rushat's payment to be approved.

**Comment by laurenreidexpensify** [comment]
Still waiting on Rushat's final payment cc @JmillsExpensify

**Comment by laurenreidexpensify** [comment]
Closing - all steps complete

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @rushatgabhane based on BZ summary.
