### ISSUE TITLE
Web - 3-dots menu popover hides the actions buttons in header for a task report and is inconsistent with other places

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace and create a task report
2. Click on task preview to go to its thread
3. In the header, click on 3-dots button and notice the popover hides the action buttons behind -- this is also inconsistent with other places like the workspace settings page

## Expected Result:
Popover menu should not hide actions buttons behind it

## Actual Result:
Popover menu is hiding the action buttons behind it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f27b1a6c-3ac5-4684-91eb-25216fbcf532

https://github.com/Expensify/App/assets/93399543/90df91b0-5ea3-498d-aff7-2abe3ab442d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690554595661139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
**Proposal**: @huzaifa-99 
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690554595661139

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We want the popover to not cover the mark-as-done, pin, and 3-dot buttons and be consistent with other places like the workspace 3-dots menu popover.
### What is the root cause of that problem?
We are not passing `anchorAlignment` to three dots menu in HeaderView [here](https://github.com/Expensify/App/blob/57a2b224e97d8ea2caff5751e51de54e97f19cf4/src/pages/home/HeaderView.js#L237-L239), so it takes the default value for `anchorAlignment` which hides the content behind the popover.
### What changes do you think we should make in order to solve the problem?
We can pass anchorAlignment to `ThreeDotsMenu` in [`HeaderView`](https://github.com/Expensify/App/blob/57a2b224e97d8ea2caff5751e51de54e97f19cf4/src/pages/home/HeaderView.js#L237-L240) like this
```
<ThreeDotsMenu
    anchorAlignment={{
        horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
        vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
    }}
```
or update [anchorAlignment.vertical](https://github.com/Expensify/App/blob/a30f5499f1703dfecaa6fd8258b3628c922ffb15/src/components/ThreeDotsMenu/index.js#L60) default prop value inside ThreeDotsmenu to
```
vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
```
<details>
<summary>Result</summary>
<img width="785" alt="image" src="https://github.com/huzaifa-99/github-expensify-bot/assets/68777211/71f2a0b0-6c9c-4226-9c99-f2325199889c">
</details>
### What alternative solutions did you explore? (Optional)
N/A (edited)

**Comment by isabelastisser** [comment]
This is a dupe: https://github.com/Expensify/App/issues/22505, closing!
