### ISSUE TITLE
[HOLD for payment 2023-08-21] Web - Inconsistency: Delete confirmation is not shown when deleting Money Request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23858]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from another user
2. Tap the report preview to navigate to the IOU report
3. Tap on the request preview to go to the details page
4. Tap the three-dot icon and click on delete
Notice that Delete confirmation is not shown

## Expected Result:
Delete confirmation is shown

## Actual Result:
Delete confirmation is not shown when deleting Money Request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.2
**Reproducible in staging?:** y
**Reproducible in production?:** "Delete" button is not functional. in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/409aa06a-d18f-459b-b30b-444971b31b53

https://github.com/Expensify/App/assets/93399543/b7661609-2dcc-481e-9c69-d933642f9e33

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690624169287459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c0a2bbb8d3512ee</li>
        <li>Upwork Job ID: 1686096957915062272</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by pecanoro** [comment]
This is not even a bug, right? This functionality has never existed 😄

**Comment by pecanoro** [comment]
@mountiny @luacmartins Should we have a delete confirmation modal for money requests?

**Comment by mountiny** [comment]
@luacmartins I am not sure how this was planned in the design doc now but it makes send to keep it consistent

**Comment by luacmartins** [comment]
Sounds good! Let's add the confirmation modal back! I can take this on if you'd like @pecanoro

**Comment by pecanoro** [comment]
@luacmartins As do you want to fix it? I can stay as the CME if we are having a contributor fix it.

**Comment by luacmartins** [comment]
Sure that works too! Just thought I'd offer to fix it myself since this is related to the functionality I worked on.

**Comment by pecanoro** [comment]
Sure! I will assign you so you can fix it, I can always review the PR 😄

**Comment by alexpensify** [comment]
@pecanoro at this point, we are waiting for proposals - right?

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/24071)

**Comment by alexpensify** [comment]
Thank you @luacmartins for the update here!

**Comment by alexpensify** [comment]
@luacmartins - it looks like the PR merged, can you share what actions are remaining here? Thanks!

**Comment by luacmartins** [comment]
@alexpensify we're just missing payment:

@daveSeife - reporting bonus
@robertKozik - PR review

**Comment by robertKozik** [comment]
@luacmartins I'm an contributor from an expert agency (Software Mansion) so I'm actually not eligible to payment

**Comment by alexpensify** [comment]
Sounds like a plan! I'll prepare accordingly for the August 21 payment day.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - @daveSeife $250 
-  Contributor that fixed the issue - Internal 
-  Contributor+ that helped on the issue and/or PR - @robertKozik payment handled by Software Mansion  

Upwork Job: https://www.upwork.com/jobs/~011c0a2bbb8d3512ee

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: N/A

**Comment by alexpensify** [comment]
@daveSeife - I've prepared the payment in Upwork. Please accept and I can complete the required process.

**Comment by daveSeife** [comment]
Accepted. Thank you!

**Comment by alexpensify** [comment]
Thanks! I've closed the job in Upwork and am going to close this GH too
