### ISSUE TITLE
Web - "Hmm you don't have access to this chat" shown for flagged threads

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot with account A
2. Open a chat with another account B and create a thread to one of the messages
3. Send a few messages in the thread using both accounts
4. From account B flag the parent message as an assault
5. Observe that the "hmm error is thrown and both accounts cant access the whole thread.

## Expected Result:
Even if parent message is flagged the rest of the thread should be accessible

## Actual Result:
Both accounts lose access to the whole thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f8f8c33a-5b7f-4c1e-bcf0-0e180508a42e

https://github.com/Expensify/App/assets/93399543/5e1548fc-e8af-4c8e-91e6-c87ba89ab7cd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690562655136619
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
dupe - https://github.com/Expensify/App/issues/23855#issuecomment-1657070809
