### ISSUE TITLE
[$1000] Web - Blank report is displayed when in recipient side when a user deletes an IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
Precondition: user A and user B should have no existing chat
1. Open a tab where user A is signed in
2. Click on FAB > click on 'Request money' > enter amount & click on 'Next' button > Search & select user B > click on 'Request' button
3. Open a tab user B is signed in
4. Open the message from user A
5. Click on 'Pay elsewhere' button
6. Open a tab where user A is signed in
7. Request money from user B again
8. Delete the IOU request
9. Switch to the tab where account B is signed in

## Expected Result:
Report shouldn't display blank page, rather should display existing chat history

## Actual Result:
Report displays blank page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3ffd6043-a649-4263-b8b0-2672c20cc06a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690532321466779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ec614b0531abef7</li>
        <li>Upwork Job ID: 1686029487292960768</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
The API fix has been merged already, should be deployed to staging soon - https://github.com/Expensify/Web-Expensify/pull/38311. Closing this issue in favor for https://github.com/Expensify/Expensify/issues/302985
