### ISSUE TITLE
[HOLD - should be fixed by #23125] Web - Flag as spam page always reloads when switching browser tabs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Hover over any message from another user
3. Click on the flag icon to open flag as spam RHN
4. Open any other browser tab
5. Return to the previous tab again
6. Notice it always reloads

## Expected Result:
Flag as spam RHN should not reload every time the tab is switched

## Actual Result:
Flag as spam RHN always reloads when tab is switched

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/74a571cd-ca6b-4acc-beb1-d0e0946c2fad

https://github.com/Expensify/App/assets/93399543/36c0770f-2761-406d-b283-1fa583d57533

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690560646136359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
Thanks for the heads up, @dukenv0307! I'll demote this to `Weekly` and keep an eye on the fix.

**Comment by johncschuster** [comment]
Looks like we're still waiting on https://github.com/Expensify/App/issues/23125 to be resolved.

**Comment by johncschuster** [comment]
Awesome. Thanks for checking!
