### ISSUE TITLE
Web - Task title arrow icon not centered

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task long title
2. Hover on the title to see the arrow icon is not centered

## Expected Result:
Center arrow icon

## Actual Result:
 Not Center arrow icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0ea3d60d-4cc8-46c3-883a-5463886ef1d5

![image (9)](https://github.com/Expensify/App/assets/93399543/c258769a-22be-4757-bb72-0782f35775a7)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690579531962749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
**Proposal by**: @namhihi237
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1690579531962749


## Proposal
 by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
 Center arrow icon in the task title
### What is the root cause of that problem?
Currently, we are arranging the component checkbox content, arrow icon on 1 row, component wrapping them, and label on 2 different rows. And we haven't centered the icon yet.
### What changes do you think we should make in order to solve the problem?
We will arrange the component like the description below
```javascript
                 <PressableWithSecondaryInteraction
                         style={({pressed}) => [styles.ph5, styles.pv2, styles.flexRow, StyleUtils.getButtonBackgroundColorStyle(getButtonState(hovered, pressed, false, disableState), true)]}
                    >
                        {({pressed}) => (
                            <>
                                <View style={[styles.flex1]}>
                                    <Text style={styles.taskTitleDescription}>{props.translate('task.title')}</Text>
                                    <View style={[styles.flexRow, styles.alignItemsTop, styles.flex1]}>
                                        <Checkbox
                                        />
                                        ....
                                </View>
                                {isOpen && (
                                    <View style={[styles.taskRightIconContainer]}>
                                             <Icon/>
                                    </View>
                                )}
                                </>
                        )}
                    </PressableWithSecondaryInteraction>
```
Update style for center icon
```javascript
    taskRightIconContainer: {
        ...
        ...flex.alignItemsCenter,
        ...flex.justifyContentCenter
    },
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by gadhiyamanan** [comment]
I think this is as per design not a bug https://github.com/Expensify/App/pull/20841#issuecomment-1604713275

**Comment by thiefvn** [comment]
Contributor details 
Your Expensify account email: trungnam23799@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a15b20f90b6a1737

**Comment by raymondchooi** [comment]
Contributor details
Your Expensify account email: raymond.chooi282@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/raychooi
