### ISSUE TITLE
[$1000] Web - Can pay IOU with PayPal even if the recipient has no PayPal payment method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User A must not have a PayPal paypal method set.
1. On User A, make a money request to User B
2. On User B, observe that the PayPal payment method is available for paying this request
3. On User B, pay the request via PayPal
3. On User B, observe that the PayPal URL is incorrect

## Expected Result:
 The PayPal payment method should not be available.

## Actual Result:
The PayPal payment method is available.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/181afbe9-f88f-4291-8892-f16ca1864c26

https://github.com/Expensify/App/assets/93399543/2cdde408-0d35-4afb-b3ff-1745156724b4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690565339451529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a86abe5b75ae6ce</li>
        <li>Upwork Job ID: 1691095540333400064</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @samh-nl
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1690565339451529


## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can pay IOU with PayPal even if the recipient has no PayPal payment method

### What is the root cause of that problem?
This affects two usages of the `SettlementButton` component.

1. **MoneyReportHeader**: The `shouldShowPayPal` prop is used to determine whether Paypal is a valid payment method. However, we are checking whether the sender has a PayPal.me account configured instead of the recipient.
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/MoneyReportHeader.js#L62

2. **ReportPreview**:  We don't show a payment options list, instead the last used payment method is taken as default.
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/SettlementButton.js#L111

But in the case that this is PayPal, we don't check if the recipient actually has it configured:
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/SettlementButton.js#L125-L128

### What changes do you think we should make in order to solve the problem?
1. We should check whether the recipient has a PayPal.me account configured in `MoneyReportHeader`:
```js
const shouldShowPaypal = Boolean(moneyRequestReport.submitterPayPalMeAddress);
```

2. In `ReportPreview`, we should also define and pass the `shouldShowPaypal` prop to the `SettlementButton`. Consequently, we should add a condition to the if-statement to ensure `shouldShowPaypal` is `true`, so that otherwise the fallback to the payment method 'elsewhere' is used.

To reduce code duplicity in declaring `shouldShowPaypal`, we can add a util function in `IOUUtils`.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by muttmuure** [comment]
I don't think this is a bug. You should be able to pay anyone with PayPal

**Comment by ArekChr** [comment]
Confirming that bug exists. NewDot redirects to `www.paypal.com/paypalme/{amount}{currency}`. This is a significant bug with potential security implications, as it could result in funds being sent to the wrong individual.

Here is an example: https://www.paypal.com/paypalme/12PLN

@muttmuure I'm in favour of removing the option if the recipient doesn't have a PayPal payment method.
any thoughts/ideas?

**Comment by muttmuure** [comment]
I don't think we should remove the option, we want to encourage users to add their PayPal account

**Comment by ArekChr** [comment]
@muttmuure, Where NewDot should redirect if user 'A' presses pay with PayPal to user 'B' in case user 'B' doesn't have a PayPal account? Right now it redirects to the wrong person.

**Comment by muttmuure** [comment]
Yeah, actually, I can see what you mean. 

Let's remove it if user B doesn't have one

**Comment by ArekChr** [comment]
Great! @samh-nl, your [proposal](https://github.com/Expensify/App/issues/23861#issuecomment-1656742112) looks good to me then.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by sophiepintoraetz** [comment]
We are deprecating paypal (decision [here](https://expensify.slack.com/archives/C057F53HR40/p1694141684236569), GH [here](https://github.com/Expensify/App/issues/26368)) so closing this out, thanks!
