### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000]  iOS/iPad - Chat - Message “User is typing” is not showing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Expensify iOS App on iPhone or iPad - User A
2. Open staging.new.expensify.com on any other device - User B
3. Open chat between user A and user B
4. Start typing message from user A to user B
5. User B sees a message in the status bar at the bottom of the chat - 'User A is typing'
6. Start typing message from user B to user A
## Expected Result: 
User A sees a message in the status bar at the bottom of the chat - 'User B is typing'
## Actual Result: 
Message “User B is typing” is not showing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native -  iPhone 14 Pro / iOS 16.5.1. iPad Pro 9.7 / 16.5.1
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9694ffd9-445d-49c1-bdb6-e38a13b036f3

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9ef6fa5815b630d</li>
        <li>Upwork Job ID: 1685927289745653760</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 25911953</li>
</ul></li>
    </ul>
</details>

**Comment by Timon0305** [comment]
Please send me backend and mobile codes

**Comment by Timon0305** [comment]
My Expensify account email: saporoman23@gmail.com
My upwork profile: https://www.upwork.com/freelancers/romans111?s=996364627857502209

**Comment by robertKozik** [comment]
Hey @Timon0305 the mobile code is the same as web/desktop and is located within [this repository](https://github.com/Expensify/App). The backend isn't open source.

**Comment by Timon0305** [comment]
Okay, got it.

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On native 'User is typing' not showing

### What is the root cause of that problem?
We haven't used `useCallback` for native to restrict the recreation of the function which we used for web.
https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/hooks/useReportScrollManager/index.native.js#L23
https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/hooks/useReportScrollManager/index.js#L25

Due to this the pusher typing event gets unsubscribed as `scrollToBottom` is in the dependency for it.
https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/pages/home/report/ReportActionsView.js#L140-L192


### What changes do you think we should make in order to solve the problem?
Seems regression from https://github.com/Expensify/App/pull/23729 cc: @hannojg 
We need to add `useCallback` for the `scrollToBottom` function in native also.

**Comment by Timon0305** [comment]
Okay, I can fix this issue.

**Comment by mehdijahani1998** [comment]
Hi. I'm willing to be amongst the contributors. Could you please guide me on this matter?

**Comment by hannojg** [comment]
oh yeah, lets add that to the native implementation as well!

**Comment by marcochavezf** [comment]
Thanks @robertKozik for the review, assigning @Pujan92 🚀

**Comment by Pujan92** [comment]
@robertKozik [PR](https://github.com/Expensify/App/pull/24108) is ready for review!

**Comment by Pujan92** [comment]
@robertKozik @marcochavezf wondering if this should be considered for a bonus or not as the PR is raised within a day of the assignment.

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

 External issue reporter - N/A 
 Contributor that fixed the issue - @Pujan92 $1000 + $500 (3 day bonus) = $1500 paid in Upwork  
 Contributor+ that helped on the issue and/or PR - @robertKozik agency C+, no manual payment

**Comment by laurenreidexpensify** [comment]
@robertKozik bump for final steps on checklist. Thanks

**Comment by robertKozik** [comment]
> * [ ]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **Seems regression from https://github.com/Expensify/App/pull/23729 as there it was only fixed for the web app, not for native.**
> * [ ]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [ ]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [ ]  [@robertKozik] Determine if we should create a regression test for this bug. **Regression test was introducted in the https://github.com/Expensify/App/pull/23729 issue. It will cover this one also.**
> * [ ]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by robertKozik** [comment]
@laurenreidexpensify sorry for keeping you waiting on that one. I've lost it in the avalanche of GitHub notifications 😅
