### ISSUE TITLE
Dev: Web - Not able to select anything in LHN after create a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go Settings > Workspaces
2. Click on new workspace button
3. Try to click on any chats or profile pic in LHN

## Expected Result:
 Chats or profile pic should be clickable

## Actual Result:
Nothing happen on click LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/43e0afd0-11d0-4c8f-9f55-63f4e5c170eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690610169591779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
closing as a duplicate

**Comment by gadhiyamanan** [comment]
@slafortune this issue repoted first , i think we can close the other issue. Here's the [slack link](https://expensify.slack.com/archives/C049HHMV9SM/p1690610169591779).
