### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Dev: Web - Edit popup menu hides the Paypal username while open first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23884]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to Settings > Payments
2. Add Paypal payment method if not added
3. Click on Paypal username to edit or delete it

## Expected Result:
Popup menu should not hide the Paypal username

## Actual Result:
Popup menu hides the Paypal username while open first time(second time it's working fine)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-2
 **Reproducible in staging?:** n/a
 **Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/85dea8ae-32b9-43fb-9dae-2bd9c984c916

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690606718500609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acb5ccd86249930e</li>
        <li>Upwork Job ID: 1686327076369784832</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 25907181</li>
</ul></li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Thanks! Triaging this now.

**Comment by zanyrenney** [comment]
Heading ooo we're still looking for proposals, thanks in advance for the help moving this along BZ team!

**Comment by mananjadhav** [comment]
@huzaifa-99's [proposal](https://github.com/Expensify/App/issues/23884#issuecomment-1657273600) looks good to me.  We need to ensure that it doesn't add extra space when the `expensifyWallet` is not enabled.

🎀 👀 🎀  C+ Reviewed

**Comment by mananjadhav** [comment]
Yeah, let's wait for @johnmlee101 to assign and then you can start with the PR.

**Comment by mananjadhav** [comment]
I am currently testing/reviewing the revised PR, which fixes this current issue, as well as popover position on the payment button, when wallet is enabled.

@zanyrenney @muttmuure @johnmlee101 I would like to point out that while @huzaifa-99 fixed this current issue, we were blocked in testing it as the Popover was overlapping the Button in the main branch/staging for the wallet enabled accounts. They investigated the issue, spent time in working out the solution , and have raised the revised PR that fixes the popover position issue in general. Considering, they had to fix the additional scope, I think we should double the price for this job.

**Comment by mananjadhav** [comment]
I've reviewed the PR. Thanks @huzaifa-99 for the patience here.

@zanyrenney @muttmuure @johnmlee101 did you folks get a chance to look at my previous comment?

**Comment by mananjadhav** [comment]
I want to make sure @muttmuure @zanyrenney @johnmlee101 got a chance to look at this [comment](https://github.com/Expensify/App/issues/23884#issuecomment-1668241483). Thanks.

**Comment by mananjadhav** [comment]
@johnmlee101 @muttmuure @zanyrenney gentle bump on the previous messages.

**Comment by zanyrenney** [comment]
@mananjadhav 

> Considering, they had to fix the additional scope, I think we should double the price for this job.
Thanks. I will take this to the team for internal discussion.

**Comment by zanyrenney** [comment]
Hi @mananjadhav we discussed this internally. This does not qualify for an increased payment based on the PR. I will proceed with the manual payment for @huzaifa-99

**Comment by mananjadhav** [comment]
Okay thanks for clarifying.

Would've appreciated if it did qualifiy. The popover was broken when we created the PR, and instead of taking a route of creating a fresh issue, we intended to fix the issue as it blocked this current PR. I think for next time would it make sense to create a fresh issue, put the current one on Hold, then revisit?

**Comment by mananjadhav** [comment]
@zanyrenney Can you post the payment summary? I need to raise a request on NewDot for this.

**Comment by JmillsExpensify** [comment]
Awaiting payment summary to get this paid out in NewDot.

**Comment by zanyrenney** [comment]
**Payment summary**

@mananjadhav $1000 as contributor+ [TO BE PAID VIA ND]
@huzaifa-99 $1000 for contributor [INVITED ON UPWORK - please accept job invite]
[no urgency bonus as merge took 6 days](https://github.com/Expensify/App/issues/23884#issuecomment-1673829327)

@gadhiyamanan $250 fore reporting bonus [PAID]

**Comment by JmillsExpensify** [comment]
Reviewed the details for @mananjadhav. $1,000 approved for payment via NewDot based on BZ summary.

**Comment by zanyrenney** [comment]
@huzaifa-99 i sent you an offer! can you accept please?

**Comment by zanyrenney** [comment]
@mananjadhav and @huzaifa-99 now paid. 

@mananjadhav $1000 as contributor+ [TO BE PAID VIA ND]

Closing!
