### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] Task Report doesn't grey out when create task offline 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Create Task
## Expected Result: 
Task Report should grey out when create task offline
## Actual Result: 
Task Report doesn't grey out when create task offline

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8f7916b8-5472-432e-a30e-67e6eedbdd74

![Snip - (3) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/f19250ae-757a-4b1f-8840-79b348346471)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ChengDzun
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690626730679279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afec56cf0d694a04</li>
        <li>Upwork Job ID: 1685971979400462336</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>ChengDzun | Contributor | 25928421</li>
<li>ChengDzun | Reporter | 25928425</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal from contributor
### Please re-state the problem that we are trying to solve in this issue.
When making any actions offline the result of this action will be greyed out. But when creating a new task, the task report isn't greyed out
### What is the root cause of that problem?
In ReportActionItem Component
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/home/report/ReportActionItem.js#L459-L465
We don't wrap TaskReport by OfflineWithFeedback Component, so the offline pattern isn't applied
### What changes do you think we should make in order to solve the problem?
We should wrap TaskReport by OfflineWithFeedback Component as we did here
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/home/report/ReportActionItem.js#L531
We also consider doing the same thing with MoneyReportView Component

**Comment by mananjadhav** [comment]
Thanks for the proposal @ChengDzun. Could you elaborate on what props will be passed to the `OfflineWithFeedback` here?

**Comment by mananjadhav** [comment]
@ChengDzun's [proposal](https://github.com/Expensify/App/issues/23893#issuecomment-1657257055) looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment]
@bfitzexpensify Can you please assign another engineer here. @grgia is OOO this week.

**Comment by stitesExpensify** [comment]
Agreed, it looks like the C+ reviewed the PR August 4, and I did not ask for any changes, so this was technically completed in 1 day. The bonus should apply @bfitzexpensify

**Comment by bfitzexpensify** [comment]
Payment is due tomorrow, but I'll be ooo for the next week — @johncschuster, appreciate you helping out with this one! Worth noting that we agreed here - https://github.com/Expensify/App/issues/23893#issuecomment-1678134957 - that this should be eligible for the #urgency bonus.

**Comment by JmillsExpensify** [comment]
Yes, I need a payment summary to get this payment approved in NewDot.

**Comment by JmillsExpensify** [comment]
Only @bfitzexpensify Can confirm for payments to be issued.

**Comment by johncschuster** [comment]
Looks like I'm taking over for @bfitzexpensify. Let me confirm the payments now.

**Comment by johncschuster** [comment]
Ah yep, it looks like @stitesExpensify believes the PR is eligible for the bonus ([comment](https://github.com/Expensify/App/issues/23893#issuecomment-1678134957)). @JmillsExpensify, I'll take care of the payments on Upwork and leave a summary for you below.

**Comment by johncschuster** [comment]
## Payment Summary:
External issue reporter @ChengDzun $250
Contributor that fixed the issue @ChengDzun $1500 (basic + urgency)
Contributor+ that helped on the issue and PR @mananjadhav $1500 (basic + urgency)

**Comment by JmillsExpensify** [comment]
Reviewed the details for @mananjadhav. $1,500 approved for payment in NewDot based on BZ summary above.

**Comment by johncschuster** [comment]
@ChengDzun thanks for your patience! I've issued the bonus payment 👍
