### ISSUE TITLE
Web - Task assigned to you doesn't show up in the LHN unless you click it in the chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into two separate accounts in Mac Chrome (one of these might need to be in an incognito window).
2. As "User B", click on "User A's" chat and then on the "+" in the composer.
3. Click on "Assign task", add a title, select "User A" as both the assignee and "Share somewhere" option, and then click on the "Confirm task" button.
4. Switch to "User A" and observe the LHN.

## Expected Result:
The created task appears in "User A's" LHN after they are assigned.

## Actual Result:
The created task doesn't appear in "User A's" LHN unless they go to the chat in which they were assigned the task and click on it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ede5d8f4-2890-4acf-9b83-dbd1c5b8b28b

https://github.com/Expensify/App/assets/93399543/e044cfb5-b182-4734-8229-ba7c08d44608

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690619152403339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
I can't reproduce this, when I click the '+' in the chat, I don't see the option to add User A as the "Share somewhere". i only see "user B" as the 'share somewhere'

<img width="1200" alt="image" src="https://github.com/Expensify/App/assets/51066321/00514b16-3b47-43be-bed3-2e3f84eb12c5">

I do see the task assigned in User A's LHN
![image](https://github.com/Expensify/App/assets/51066321/d018f3d1-719e-4a75-b936-d44cfb3dedbd)

The video created by QA doesn't match the reporters video but it does match what I'm seeing so I don't understand how to reproduce the reporter's issue. Asking in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1690619152403339

**Comment by Christinadobrzyn** [comment]
Okay digging into this more, it looks like this is expected with V1 of Tasks. 

I read over our [design doc](https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#heading=h.ns12dr1f35rx) (I don't think this is public at this time). 

It says that Tasks showing in the LHN is part of the next iteration of Tasks. 
Also chatting in Tasks is part of the next iteration. I think both of these will solve the issue you're seeing. So this wouldn't be a bug but a feature request. 

@Victor-Nyagudi If you'd like to raise this feature request feel free to do so by following the steps in our [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)
