### ISSUE TITLE
[HOLD for checklist] [$1000] Web -  Pointer cursor is displayed on deleted member of workspace when deleted in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open members
6. If only 1 member then invite few members and switch off the internet
7. On members page, remove any member
8. Hover on removed member and observe that pointer cursor is displayed (We display not-allowed cursor on deleted items throughout the app), in case member is not visible, go back and reopen members

## Expected Result:
App should display 'not-allowed' cursor on deleted item deleted in offline mode

## Actual Result:
App displays 'pointer' cursor on deleted member deleted in offline mode on workspace members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f49350ee-eedd-41bd-adc6-33a4c0f6eb3f

https://github.com/Expensify/App/assets/93399543/0762275b-2413-4d21-968f-cac0132d1f73

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690617307322089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b2a9bab227bac96</li>
        <li>Upwork Job ID: 1686036911311564800</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25901002</li>
<li>ginsuma | Contributor | 25901003</li>
<li>dhanashree-sawant | Reporter | 25901006</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Issue Participants:

Issue reported by: @dhanashree-sawant
Contributor: @ginsuma 
C+: @fedirjh

Was this issue merged in time to be eligible for the speed bonus? No ([context](https://github.com/Expensify/App/issues/23890#issuecomment-1667682531))
Were their any regressions? No

Payment summary:

Reporter: $250
Contributor: $1000
C+: $1000

**Comment by greg-schroeder** [comment]
Just awaiting checklist @fedirjh

**Comment by greg-schroeder** [comment]
I sent updated offers for that. Once the checklist is complete we can close this.

**Comment by greg-schroeder** [comment]
Paid those bonuses out. Filing regression test. Closing accordingly.
