### ISSUE TITLE
mWeb - User is directed to the wrong page when opening the app on the Android mobile browser

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisites:
Expensify app should be logged-in on mobile browser and you have marked Expensify app as bookmark
1. Open mobile browser
2. Go to bookmarks
3. Select an expensify URL from the list.

## Expected Result:
Main page of the app should be displayed

## Actual Result:
 'You don't have access to this chat' message is appearing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/14518f76-f98e-4354-8445-adeae5f6fd14

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690651701936209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
not reproducible -closing
