### ISSUE TITLE
PR marked `Internal QA` didn't get anyone assigned

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#23913]
## Action Performed:
1. New deploy checklist was created
2. 1 Internal QA PR was linked: https://github.com/Expensify/App/pull/23313

## Expected Result:
1. Internal QA PR should have been assigned to an internal employee to QA

## Actual Result:
1. Nobody got assigned

<img width="533" alt="Screenshot 2023-07-31 at 12 49 51 PM" src="https://github.com/Expensify/App/assets/3885503/650cc23b-fb02-4a75-a1d7-b925d28b9620">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01375cdf18867694f7</li>
        <li>Upwork Job ID: 1696099838846287872</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
@sophiepintoraetz unassigning b/c this is a bug in an internal workflow (for deploying) so we probably won't need to assign contribs

**Comment by narefyev91** [comment]
@Beamanator should we close this one? or we still have issues here?

**Comment by Beamanator** [comment]
Oh shit i didn't notice you got assigned @narefyev91 😅 

I think this is actually fixed, I've seen some internal QA PRs showing up on the checklist recently, so ya let's close this out :D
