### ISSUE TITLE
Emoji reaction on the message from sender "chat A" is not refelect on the recevier side "chat B"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. open any task or create a new one by assigning someone
3. mark it as complited
4. write a message "text"
4. send it
5. react for the message
6. the reaction will not reflected on the receiver side
## Expected Result: 
the reaction should be reflected
## Actual Result: 
the emoji reaction on the message is not reflected

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ec16309f-34ee-45fc-be38-0bc5fcbc112f

https://github.com/Expensify/App/assets/43996225/8bf9e05c-ca31-4dea-b8bd-5f40005dc4c9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690292461179019
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
This is a BE issue.
When a task is marked as completed, if a user who is not the task assignee reacts emoji on the message, BE responds empty data like below, and does not send push events to the task assignee side.
![screenshot2](https://github.com/Expensify/App/assets/131836113/5474e3b2-b826-448b-9ae4-f7a2ba81f0fb)

**Comment by CortneyOfstad** [comment]
I'm heading OoO until 8/14 so going to reassign BZ and also get engineering eyes on this to see if it is actually BE 👍

**Comment by CortneyOfstad** [comment]
Thanks @MelvinBot 😑

**Comment by deetergp** [comment]
I agree that this does appear to be a back end issue. When the user that is not assigned to the task attempts to add a reaction emoji to the comment, they [fail a check](https://github.com/Expensify/Auth/blob/1e7f1ec1a82240017facef375084de7dc8e434da/auth/command/AddEmojiReaction.cpp#L76-L78) to see whether or not they can write in the chat, which throws and in turn prevents the update from being written to the DB. I'll figure out why it's failing that check and fix it.

**Comment by lschurr** [comment]
Any update here @deetergp? Any action needed from bug zero?

**Comment by lschurr** [comment]
Just bumping this since it went overdue.

**Comment by deetergp** [comment]
I have a PR going for the back end that does address this issue, but I need to have another engineer sanity check it for me to make sure I'm not breaking something. I will try to get that wrapped up by tomorrow.

**Comment by lschurr** [comment]
Just bumping @deetergp to remove the overdue here.

**Comment by deetergp** [comment]
I made a minor change and put the PR out for review.

**Comment by deetergp** [comment]
Still under review, but should get approved today.

**Comment by deetergp** [comment]
The back end change has been deployed to production, so this should be done @lschurr.

**Comment by lschurr** [comment]
Great thanks @deetergp - did we have any other contributors involved besides the bug reporter: @misgana96?

**Comment by deetergp** [comment]
No @laurenreidexpensify, I don't think so.

**Comment by lschurr** [comment]
Great, @misgana96 - I've invited you to the job: https://www.upwork.com/jobs/~0114a52037d22beac7 

Please accept so that we can issue payment and close this out.

**Comment by lschurr** [comment]
Sorry for the delay - I've sent the offer in Upwork @misgana96

**Comment by misgana96** [comment]
No worries. Offer accepted! Thank you @lschurr

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: @misgana96 $250 (paid in Upwork)

This is all set. Closing.

**Comment by misgana96** [comment]
Thanks @lschurr
