### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] Feature request: Hyperlink any URLs that appear in request descriptions

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#23949]
While we hyperlink URLs that appear in chat messages, we don't do the same for URLs that appear in the description field of a request. Let's close that gap, because it's frustrating to have the hyperlink in one place but not in the other. 

<img width="876" alt="Screenshot 2023-07-31 at 13 11 46" src="https://github.com/Expensify/App/assets/1127863/0f10d9a2-5135-4743-8370-7d55bc1669e5">

Assigning myself as part of wave3 in the product roadmap. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1f1d0e52e445d5f</li>
        <li>Upwork Job ID: 1689124762759274496</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>jeet-dhandha | Contributor | 26670169</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
@shawnborton removing you as I think we're on the same page .

**Comment by JmillsExpensify** [comment]
Whoops, I just realized that I should have put an `external` label on this issue. We have one proposal above, so at least that is ready for review.

**Comment by eh2077** [comment]
@JmillsExpensify Do we just only want to add support for hyperlink in task description or support all Markdown styling features that chat supports?

**Comment by JmillsExpensify** [comment]
>Do we just only want to add support for hyperlink in task description or support all Markdown styling features that chat supports?

Great question. I think we want to keep it simple for now, and just focus on supporting hyperlinks. cc @shawnborton @trjExpensify in case ya'll are thinking about it differently.

**Comment by trjExpensify** [comment]
Yeah, I think it's cool to tackle hyperlinks as a first step and not bloat this issue.

**Comment by JmillsExpensify** [comment]
@thesahindia Mind commenting on the proposals thus far?

**Comment by JmillsExpensify** [comment]
@thesahindia Can you please prioritize reviewing these proposals?

**Comment by JmillsExpensify** [comment]
Ah sorry I missed the last comment. I'll re-assign C+ now to keep this moving.

**Comment by shawnborton** [comment]
Agree, starting with just hyperlinks works for me.

**Comment by narefyev91** [comment]
Proposal from @jeet-dhandha looks good to me https://github.com/Expensify/App/issues/23949#issuecomment-1659050879 - all steps defined correctly to make it working
🎀 👀 🎀 C+ reviewed

**Comment by jeet-dhandha** [comment]
@narefyev91 Please ping once i am assigned this issue 👍

**Comment by JmillsExpensify** [comment]
I think we're waiting on @neil-marcellini to confirm that he agrees, though as a heads up, he is OOO for the rest of the week.

**Comment by thienlnam** [comment]
I'll take this over while Neil is OOO

**Comment by thienlnam** [comment]
The proposal looks good, though this isn't limited to just task descriptions

I like the idea to add a new key called HTML for these components to render. Though as mentioned, we'll want to do this in all description locations (tasks, expense requests, distance requests)

Thinking about it, we should probably have a consistent component for these descriptions that ensure they are all consistent. Going to assign @jeet-dhandha since it's almost there - let's just go one step further to make sure these are consistent for all report types

**Comment by jeet-dhandha** [comment]
Creating PR...

**Comment by jeet-dhandha** [comment]
@JmillsExpensify @thienlnam - A small suggestion what if i move link parsing in `MenuItem` and then we pass `shouldParseTitle` as a prop and render title as html.

Draft PR has the changes:
- https://github.com/Expensify/App/pull/27462

**Comment by jeet-dhandha** [comment]
I have made PR with my suggestion if any change needed please do suggest in comments 👍

**Comment by jeet-dhandha** [comment]
Hold for payment

**Comment by thienlnam** [comment]
This is ready for payment cc @JmillsExpensify

**Comment by jeet-dhandha** [comment]
@JmillsExpensify Let's cancel the payment as its been too long for payment and also Regressions were happening due to less testing and discussion on both of our ends. 

Let's make this a learning to not implement any feature until all the cases are covered for next feature requests.

**Comment by JmillsExpensify** [comment]
To clarify, you don't wish to be paid for this issue/PR?

**Comment by jeet-dhandha** [comment]
Nothing just handle the payment as usual.

**Comment by JmillsExpensify** [comment]
Payment summary:

- Contributor: @jeet-dhandha $1,500 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment]
Offer has been sent via Upwork.

**Comment by jeet-dhandha** [comment]
@JmillsExpensify I got payment from service account for `$1000` i need just extra `$500` payment.
<img width="1440" alt="Screenshot 2023-10-08 at 7 10 13 PM" src="https://github.com/Expensify/App/assets/78416198/aa1a15dc-1f65-4776-b612-03fa7cf398f0">

**Comment by jeet-dhandha** [comment]
@JmillsExpensify Can you update the price of new contract to `$500` ?
<img width="1440" alt="Screenshot 2023-10-08 at 7 12 00 PM" src="https://github.com/Expensify/App/assets/78416198/12a8dad2-d9c2-4e21-bc1f-0052cfbcc167">

**Comment by JmillsExpensify** [comment]
Will do! Updating now.

**Comment by JmillsExpensify** [comment]
Should be all set here!
