### ISSUE TITLE
keyboard not poping when near in concierge channel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open any report and observe keyboard is getting open automatically.
2. open concierge channel and observe, keyboard is not opening automatically.
## Expected Result: 
when we open concierge channel keyboard should be pop or open automatically.
## Actual Result: 
when we open concierge channel keyboard is not poping or opening automatically, we are doing it manually byt clicking on the input.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ec47673b-67db-4c23-9b9c-65bb78f8d248

https://github.com/Expensify/App/assets/43996225/b97051a7-55b0-4fe3-a70f-b8d29bf26a61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @immadisetty-jaya-surya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690447725387549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Hm, I'm not able to replicate. I'm seeing the keyboard not being opened for all rooms and chats:

https://github.com/Expensify/App/assets/38236554/f58c91d2-6e1c-40eb-9c97-f2d76c8c446b

@immadisetty-jaya-surya @kavimuru can you still reproduce? I'm testing using Galaxy S22 Ultra v1.3.49-0

**Comment by immadisetty-jaya-surya** [comment]
yeah till I am reproducing the bug even I have updated the bug and I have followed the same steps:
1. open a workspace and see , keyboard is popped on
2. but when near the concierge, the keyboard is not popping.

**Comment by immadisetty-jaya-surya** [comment]
https://github.com/Expensify/App/assets/134204543/ad094f37-2758-42e3-b302-475ed0bb684e

**Comment by immadisetty-jaya-surya** [comment]
Contributor details
Your Expensify account email: suryaimmadisetty5252@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0126183a58ad2d5be4

**Comment by bfitzexpensify** [comment]
@immadisetty-jaya-surya what device are you using and which version of New Expensify?

**Comment by immadisetty-jaya-surya** [comment]
@bfitzexpensify redmiK20 pro and latest updated version

**Comment by bfitzexpensify** [comment]
OK, I understand the distinction now: a new/empty workspace will trigger the keyboard, while one with activity previously will not:


https://github.com/Expensify/App/assets/38236554/fa5c04c9-9d0f-48a3-9de6-c275394f3b0b


That isn't a bug. It makes sense that when there is no previous chat history, the action is to open the keyboard to start the conversation. But when there is chat history, we don't assume the user wants to send a message

**Comment by immadisetty-jaya-surya** [comment]
@bfitzexpensify but concierge channel isn't opening the keyboard, till there is no chat history

**Comment by bfitzexpensify** [comment]
There are messages in the Concierge chat, which is why the keyboard isn't automatically opening
