### ISSUE TITLE
Dev: Bank Account - Console error on Checkbox component

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23955]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND 
2. Press Avatar button to open settings page
3. Navigate to any workspace -> Navigate to bank account
4. Select Connect Manually -> Enter Routing number & account number then press on continue
5. Notice there is console error for checkbox component

## Expected Result:
There should be no console error

## Actual Result:
Console error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Simulator Screenshot - iPhone 14 - 2023-07-29 at 02 24 01](https://github.com/Expensify/App/assets/93399543/678da294-bcab-4eaf-8b9b-f48a11ff716f)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690578654439359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
https://github.com/Expensify/App/issues/22169#issuecomment-1656740244

**Comment by PauloGasparSv** [comment]
> @kbecciv - could you provide some more context to the comment you linked? let me know how that relates to this issue - thanks!

Hey @maddylewis it's a link to the original issue/PR that introduced this! 
It also leads to https://github.com/Expensify/App/issues/23909 where this warning/error is being fixed by https://github.com/Expensify/App/pull/23910 so I believe we can close this

**Comment by maddylewis** [comment]
thank you for clariying @PauloGasparSv - i'll go ahead and close this one 👍
