### ISSUE TITLE
[$1000] QA Testing Issue

### ISSUE THREAD

**Issue by deetergp** [Expensify/App#23953]
This issue is for QA testing https://github.com/Expensify/Web-Expensify/pull/38333 and it require me adding a random contributor. If you get assigned, please ignore it.

**Issue reported by:** @nathan-mulugeta

cc @thienlnam 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011364364f36c51943</li>
        <li>Upwork Job ID: 1687157287386517504</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Contributor | 25932061</li>
<li>nathan-mulugeta | Reporter | 25932062</li>
</ul></li>
    </ul>
</details>

**Comment by kassahun-asefa** [comment]
I don't see what the bug is. https://github.com/Expensify/Web-Expensify/pull/38333 This link is broken.

**Comment by deetergp** [comment]
This was for QA testing an internal issue, please disregard it, everyone. Apologies for the ping.
