### ISSUE TITLE
[$500] [HOLD for payment 2023-09-29] Follow ups to the Edit Money Request

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#23961]
Follow ups to the API PR https://github.com/Expensify/Web-Expensify/pull/38252 and App PR https://github.com/Expensify/App/pull/23703 related to https://github.com/Expensify/Expensify/issues/295091.

- [x] Update the optimistic data to re-evaluate the iou report total correctly if the currency if all the requests is same
- [x] Enable the currency edit option cc @koko57 
- [x] Discuss the messages for the various types of modifiedexpense, should we remove the previously part if comment was empty
- [x] Auto focus the description field https://github.com/Expensify/App/pull/23703#discussion_r1290423374
- Noting from internal issue - lets also translate the modified expense messages https://github.com/Expensify/App/issues/26369
- [x] Update the header styles for when editing in offline mode to give correct feedback
- [x] Update styles of the non-editable header to not look as disabled
- [x] Add the verification checks from the `EditRequestPage` which make sure that something actually changed to some helper method in the `IOU.editMoneyRequest`
- [x] Handle the red brick road better
- [x] Do not allow setting future dates
- [x] Make sure admins can edit the transactions [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22EditMoneyRequest%22%20AND%20email%3A%22contributorpayments%40expensify.com%22%20AND%20timestamp%3A%5B2023-08-15T13%3A00%20TO%202023-08-16T23%3A59%5D)
- Add tests to the jest suite for IOU when editing IOU requests and expense reports too
    - you can only edit your own transactions in case of IOU
    - admins can also edit the transactions made by employees
    - correct expense/iou report totals are computed
    - https://github.com/Expensify/App/issues/26366 will be handled here
- [x] https://github.com/Expensify/App/issues/24623
- [x] User which is not able to edit the request can access the form when directly visiting the edit url. On EditMoneyRequest page, lets evaluate on first render if the user can edit and if not, lets show `Hmmm its not here` page or close the modal, whatever is better
- [x] https://github.com/Expensify/App/issues/25931
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01778206bdcc3370d6</li>
        <li>Upwork Job ID: 1709801140497133568</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@koko57 Could you please comment here, I will assign you to help out with this.

**Comment by koko57** [comment]
@mountiny 🙌🏻

**Comment by mountiny** [comment]
Thank you! Would you be able to base on top of this PR and work on enabling the currency edit? https://github.com/Expensify/App/pull/23703

**Comment by koko57** [comment]
@mountiny PR opened: https://github.com/Expensify/App/pull/24565

**Comment by mountiny** [comment]
Will work on the other follow ups here with Agata, adding the C+ from the original PR here https://github.com/Expensify/App/pull/23703

**Comment by mountiny** [comment]
Created a PR for allowing admins to edit the money requests

**Comment by mountiny** [comment]
@allroundexperts you are already here, there will be bunch more PRs here

**Comment by mountiny** [comment]
For the messages update, if the old amount is an empty value, we should use this language:
- `Set an amount: %amount%`
- `Set an date: %created%`

And the current message is if the old value is non empty. @koko57 would you be able to incorporate it to the next PR? We can have multiple tasks in one PR

**Comment by srikarparsi** [comment]
Linking this here to add it to your radar: [Cannot edit a negative IOU request](https://github.com/Expensify/App/issues/24623), It's also formatted different since the negative sign goes before the symbol in other places but not sure how that would look in the edit preview.

**Comment by mountiny** [comment]
> Add the verification checks from the EditRequestPage which make sure that something actually changed to some helper method in the IOU.editMoneyRequest

checking this one off as I feel like its not that necessary

**Comment by mountiny** [comment]
@BeeMargarida Seems like we are on a great path with the next 2 PRs.

```
Add tests to the jest suite for IOU when editing IOU requests and expense reports too
- you can only edit your own transactions in case of IOU
- admins can also edit the transactions made by employees
- correct expense/iou report totals are computed
```

This is not exhaustive list we could add more different flows and cases to the tests.

I think the main part here left which should be addressed is to write comprehensive jest suite tests covering the Edit in the `IOUTest.js`, would you like to work on that or would you rather leave that to someone else? Not everyone likes to write tests so best to give it to seomeone who likes it :D

**Comment by mountiny** [comment]
There are volunteers I can see.

> User which is not able to edit the request can access the form when directly visiting the edit url. On EditMoneyRequest page, lets evaluate on first render if the user can edit and if not, lets show Hmmm its not here page or close the modal, whatever is better

There is this one as well to look into

**Comment by mountiny** [comment]
I have created this internal issue https://github.com/Expensify/Expensify/issues/309777 to handle the updates to the backend command to keep this issue more focused on frontend

**Comment by mountiny** [comment]
@allroundexperts Do you wanna take it on for `$500` for that PR? if so, please feel free to raise a PR, no need for a proposal here. @BeeMargarida could then on the other hand review the PR of yours :D

**Comment by mountiny** [comment]
@allroundexperts are you able to work on it today?

**Comment by mountiny** [comment]
Thank you!

**Comment by mountiny** [comment]
I have created a new separate issue for the tests https://github.com/Expensify/App/issues/26366 cc @koko57 has laready started working on it but wasnt able to finish before vacation. I have increased the scope a bit so maybe its worth to have someone who works hourly on such issue. Unless @allroundexperts would really be passionate about such issue?

**Comment by mountiny** [comment]
And I have created a separate issue for the RBR I will look into later today https://github.com/Expensify/App/issues/26367

**Comment by mountiny** [comment]
I have created those follow ups and I will aim to get this merged https://github.com/Expensify/App/pull/25498 

This concludes the main deliverables of this issue for wave3 hence I have moved it to `Done` in the project 🎉 We have almost completed the wave3 😍

**Comment by mountiny** [comment]
@allroundexperts Could you help summarize the payments here please, its been a long issue, thanks!

**Comment by mountiny** [comment]
@allroundexperts bump on the above, we can then pay this out

**Comment by kadiealexander** [comment]
BUmped @allroundexperts in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1695951796272969).

**Comment by mountiny** [comment]
LGTM

**Comment by kadiealexander** [comment]
@mountiny any thoughts on the waiver @allroundexperts has requested?

**Comment by kadiealexander** [comment]
Also, are @rushatgabhane and @koko57 due any payments?

**Comment by mountiny** [comment]
@kadiealexander waiver sounds reasonable to me in this case

**Comment by kadiealexander** [comment]
Payouts due:

Contributor: $4000 @allroundexperts 

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~01778206bdcc3370d6)

**Comment by JmillsExpensify** [comment]
$4,000 payment approved for @allroundexperts based on BZ summary.

**Comment by mountiny** [comment]
I believe we can close this one then, regression tests for edit moeny request are handled separately
