### ISSUE TITLE
Home address - "Fix the errors" doesn't set focus to "State" field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22788

## Action Performed:
Precondition - Home address is not set
1. Open Desktop app
2. Click on profile icon to invoke settings
3. Click on "Profile"
4. Click on "Personal details"
5. Click on "Home address"
6. Input address into address line 1 (Do not select suggestions)
7. Set Country to United States
8. Input City name
9. Input valid zip code
10. Click on "Save"
11. Click on "Fix the errors"

## Expected Result:
Cursor is set to "State" field after user clicks on "Fix the errors"

## Actual Result:
Nothing happens after user clicks on "Fix the errors"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS /  Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/025b1ef3-2b77-4bb8-b9c8-22de7a4cd01c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I think this is expected behavior, especially considering it is consistent across all platforms. The errors are highlighted in red so are visible to the user, there is no need to jump to them. I think this makes more sense to solve for scenarios where there is more than one error.
