### ISSUE TITLE
[$1000] Task-Missing 'From <user>' in task header for task assigned to user w/o access to group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User A has assigned a task to User D in a group chat with User B and C where User D is not a member.

1. Launch New Expensify app as User D
2. Go to chat with User A
3. Go to task thread created and assigned by User A in the precondition

## Expected Result:
The task thread header has 'From <user>' subtitle

## Actual Result:
The task thread header does not have 'From <user>' subtitle. This only occurs to task created in a group chat where assignee is not a member of the group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b9fec09e-a5e8-4358-8db9-daf8546250e1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f65ed90583f55ec4</li>
        <li>Upwork Job ID: 1686691726832185344</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is expected
