### ISSUE TITLE
[HOLD for payment 2023-08-17] [HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] Payments - App crashed when try to set default if added BA

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Navigate to Settings -> Payments -> Add Payment Method -> Bank Account
3. Click on the recently added bank account
4. Tap on "Make default payment method"

## Expected Result:
App should not crashed

## Actual Result:
App crashed when try to set default if added BA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1346fe39-6ba9-4e7b-a3d6-b6a716b00be1

![Bug6149269_crash](https://github.com/Expensify/App/assets/78819774/a0c68980-f7c0-47ab-b635-8cacae293a3a)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Yeah, looks like @NikkiWines removed it in https://github.com/Expensify/App/pull/22461/. Reassigning to Nikki.

**Comment by Beamanator** [comment]
Yep, then https://github.com/Expensify/App/pull/22412 just got to staging so we probably added it back here w/out knowing it got removed somehow

**Comment by tgolen** [comment]
Alex and I decided to just move forward with the fix since we are right here.

**Comment by rushatgabhane** [comment]
creating a cleanup PR to remove dead code

**Comment by rushatgabhane** [comment]
manual request here - https://staging.new.expensify.com/r/2267949987948189

**Comment by tgolen** [comment]
@rushatgabhane it sounds like you've requested payment already, so I think we are OK to close this. If not, please reopen and let me know what we need to do. Thanks!
