### ISSUE TITLE
LHN - Blue line is displayed on the left edge after creating a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new account and enter a magic code

## Expected Result:
No unnecessary lines are shown

## Actual Result:
The blue line on the left edge is displayed above the FAB menu options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6149358_photo_2023-08-01_09-53-19](https://github.com/Expensify/App/assets/78819774/6477bbab-d863-4db8-9aac-893dece318b1)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
I can't seem to repro this accurately on v1.3.48-4 - I don't see a blue line on my Pixel 3a.
