### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000]  Task - Second avatar of group avatar is highlighted when long pressing on Share somewhere

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any group chat
3. Click + > Assign task
4. Enter title and click Next
5. Long press on Share somewhere field

## Expected Result:
Since Share somewhere field is not selectable in group chat task assignment, it should not have any feedback when pressing on it

## Actual Result:
The second avatar of group avatar is highlighted when long pressing on Share somewhere

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/edc2a777-6364-45ab-8c6d-5deb4de12c16

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause -Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8af40e296417c50</li>
        <li>Upwork Job ID: 1686485461826138112</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>reinaldosg | Contributor | 25951887</li>
</ul></li>
    </ul>
</details>

**Comment by reinaldosg** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Second avatar of group avatar is highlighted on long press

### What is the root cause of that problem?
MultipleAvatars style ignore `props.interactive` so the element always have action

https://github.com/Expensify/App/blob/9dc5f19173aaf0cb766d2e093cc50379ef4de2c0/src/components/MenuItem.js#L155-L156


### What changes do you think we should make in order to solve the problem?
Check `props.interactive` to determine the style

``` html
pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.buttonPressedBG) : undefined,
isHovered && !pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.border) : undefined,
```

### What alternative solutions did you explore? (Optional)
-

**Comment by hanzalahsamana** [comment]
I can do this

**Comment by icarus-0520** [comment]
In components, MenuItem.js, lines 148-158:
` <MultipleAvatars
                                            isHovered={isHovered}
                                            isPressed={pressed}
                                            icons={props.icon}
                                            size={props.avatarSize}
                                            secondAvatarStyle={[
                                                StyleUtils.getBackgroundAndBorderStyle(themeColors.sidebar),
                                                pressed ? StyleUtils.getBackgroundAndBorderStyle(themeColors.buttonPressedBG) : undefined,
                                                isHovered && !pressed ? StyleUtils.getBackgroundAndBorderStyle(themeColors.border) : undefined,
                                            ]}
                                        />`

The pressable this is a child to does check for props.disabled and !props.interactive, but isHovered is passed from further up the hierarchy, so it appears that these checks are not actually diverting inherited values. The first thing I'd do is add in conditionals to isHovered and isPressed that switch to a hardcoded value pending a check to either props.disabled or !props.interactive. there are a couple of different configurations possible there, so I'd try out all of them and log values to see if this theory is correct.

**Comment by icarus-0520** [comment]
Contributor details
Expensify account email: aidan@disillusion.io
Upwork profile link: https://www.upwork.com/freelancers/~01ee97b9ff5ee5d693

**Comment by Muhammad-Saqib-980** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Second avatar of group avatar is highlighted when long pressing on Share somewhere
### What is the root cause of that problem?
MultipleAvatars style ignore props.interactive so the element always highlights the second avatar on press
### What changes do you think we should make in order to solve the problem?
props.interactive should be used to determine if the second avatar should be highlighted on press or not.

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Secondary avatar of group avatar is highlighted when hovering or long pressing on share somewhere

### What is the root cause of that problem?

When we assign a task in a group chat, props.task.parentReportID is the reportID of the group chat and props.interactive is false in order to prevent interaction
https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/pages/tasks/NewTaskPage.js#L181

But Multiple avatar ignores this props
https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/components/MenuItem.js#L153-L157

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to replace all occurrence of `isHovered` and `pressed` with `isHovered && props.interactive` and `pressed && props.interactive` in the [MenuItem](https://github.com/Expensify/App/blob/main/src/components/MenuItem.js) component

### What alternative solutions did you explore? (Optional)

**Comment by CuongXuanLe** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Second avatar of group avatar is highlighted on long press
> 
> ### What is the root cause of that problem?
> When we assign a task in a group chat, the props.task.parentReportID is id of this room. So the `!props.task.parentReportID` of `interactive` below is false.
> https://github.com/Expensify/App/blob/9dc5f19173aaf0cb766d2e093cc50379ef4de2c0/src/pages/tasks/NewTaskPage.js#L186
> 
> So MultipleAvatars ignore `props.interactive` and second avatar of group avatar is highlighted when long pressing.
> 
> https://github.com/Expensify/App/blob/9dc5f19173aaf0cb766d2e093cc50379ef4de2c0/src/components/MenuItem.js#L155-L156
> 
> ### What changes do you think we should make in order to solve the problem?
> Add `props.interactive` condition to define style
> 
> ```
>secondAvatarStyle={[
>    StyleUtils.getBackgroundAndBorderStyle(themeColors.sidebar),
>    pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.buttonPressedBG) : undefined,
>    isHovered && !pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.border) : undefined,
>]}
> ```
> 
> ### What alternative solutions did you explore? (Optional)

**Comment by CuongXuanLe** [comment]
>## Proposal
>### Please re-state the problem that we are trying to solve in this issue.
>Second avatar of group avatar is highlighted on long press
>### What is the root cause of that problem?
>When we assign a task in a group chat, the props.task.parentReportID is id of this room. So the `!props.task.parentReportID` of `interactive` below is false.
> > https://github.com/Expensify/App/blob/9dc5f19173aaf0cb766d2e093cc50379ef4de2c0/src/pages/tasks/NewTaskPage.js#L186
>
>So MultipleAvatars ignore `props.interactive` and second avatar of group avatar is highlighted when long pressing.
>https://github.com/Expensify/App/blob/9dc5f19173aaf0cb766d2e093cc50379ef4de2c0/src/components/MenuItem.js#L155-L156
> 
>### What changes do you think we should make in order to solve the problem?
> Add `props.interactive` condition to define style
> ```
>secondAvatarStyle={[
>    StyleUtils.getBackgroundAndBorderStyle(themeColors.sidebar),
>    pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.buttonPressedBG) : undefined,
>    isHovered && !pressed && props.interactive ? StyleUtils.getBackgroundAndBorderStyle(themeColors.border) : undefined,
>]}
> ``` 
>   
> ### What alternative solutions did you explore? (Optional)

**Comment by CuongXuanLe** [comment]
Contributor details
Your Expensify account email: cuong.le322002@gmail.com
Upwork Profile Link: https://www.upwork.com/o/companies/~01b575d671e4e60c51/

**Comment by CuongXuanLe** [comment]
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by CuongXuanLe** [comment]
Contributor details
Your Expensify account email: [thuy.lethithu@antbuddy.com](mailto:thuy.lethithu@antbuddy.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by CuongXuanLe** [comment]
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by ares-dev05** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Second avatar of group avatar is highlighted on long press on Share somewhere field
### What is the root cause of that problem?
When the "Share everywhere" menu is pressed, the interactive props are set to false to prevent the avatars in this menu from responding to press events. However, the MultipleAvatars component did not handle this interactive props variable.
### What changes do you think we should make in order to solve the problem?
In the MenuItem.js file, on the 148th line, you can update the use case for the MultipleAvatars component as the following.

```
<MultipleAvatars
    isHovered={isHovered}
    isPressed={pressed}
    icons={props.icon}
    size={props.avatarSize}
    secondAvatarStyle={[
        StyleUtils.getBackgroundAndBorderStyle(themeColors.sidebar),
        pressed ? StyleUtils.getBackgroundAndBorderStyle(themeColors.buttonPressedBG) : undefined,
        isHovered && !pressed ? StyleUtils.getBackgroundAndBorderStyle(themeColors.border) : undefined,
    ]}
/>
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment]
@sobitneupane could you review the proposals here?

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/24008#issuecomment-1660648725) from @reinaldosg looks good to me.

🎀👀🎀 C+ reviewed

**Comment by reinaldosg** [comment]
Hi @sobitneupane @danieldoglas ! My [PR](https://github.com/Expensify/App/pull/24172) is ready for review.

**Comment by danieldoglas** [comment]
I think this is elegible for the bonus, I was the one who took a while to review and merge. C+ and Contributor reviewed on time.

**Comment by reinaldosg** [comment]
@danieldoglas hi, am I eligible to get the 50% bonus since the PR is actually ready from few days ago ?

**Comment by lschurr** [comment]
Hi @sobitneupane - could you work on the checklist? Do we need a regression test for this?

**Comment by lschurr** [comment]
Payment summary:

- Bug report: Applause - no payment
- Contributor: @reinaldosg $1500 (to be paid in Upwork)
- Contributor+: @sobitneupane $1500 (to be paid in Newdot)

**Comment by lschurr** [comment]
@sobitneupane could you work through the checklist for this one?

**Comment by sobitneupane** [comment]
Sorry for the delay. I will try to get to it by EOD.

**Comment by lschurr** [comment]
Bump on this one @sobitneupane :)

**Comment by lschurr** [comment]
Hi @sobitneupane - would really like to get this one closed out. Could you confirm whether we need a regression test or not?

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open a group chat
2. Assign task
3. Enter title and click Next
4. Hover on Share somewhere field -> Verify that avatars are not highlighted
5. Press on Share somewhere field -> Verify that avatars are not highlighted
6. Long Press on Share somewhere field -> Verify that avatars are not highlighted

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20145
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/20145/files#r1311937536
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

https://github.com/Expensify/App/issues/24008#issuecomment-1701214348

**Comment by danieldoglas** [comment]
@lschurr I think this one is ready to pay/close!

**Comment by lschurr** [comment]
Yep, thanks! I'm going to create a QA GH and will close.

**Comment by lschurr** [comment]
All done!

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/24008#issuecomment-1687403848

**Comment by JmillsExpensify** [comment]
$1,500 approved for payment via NewDot based on BZ summary.
