### ISSUE TITLE
[HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] Home address - Page constantly crashes if insert values and quit the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24006]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22788

## Action Performed:
1. Open iOS app
2. Open "Settings"
3. Tap on "Profile"
4. Tap on "Personal details"
5. Tap on "Home address"
6. Input values in fields (address line 2 is not necessary)
7. Close the app completely
8. Proceed to "Personal details" tab
9. Tap on "Home address"

## Expected Result:
User lands in "Home address" tab

## Actual Result:
App crashes constantly when user taps on "Home address" , user needs to log out and log back in to access home address tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b39cc8f0-6dde-4a3d-8344-20c8db5aa173

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
Not reproducible on `main` iOS

**Comment by hannojg** [comment]
Error log

![Simulator Screen Shot - iPhone 14 - 2023-08-01 at 17 26 33](https://github.com/Expensify/App/assets/16821682/8c0b39e3-e7bf-41ff-9978-81c58500def2)

**Comment by hannojg** [comment]
This is a regression of:

- https://github.com/Expensify/App/pull/23749

which was reverted here:

- https://github.com/Expensify/App/pull/24003

**Comment by Beamanator** [comment]
Should be fixed now, as of https://github.com/Expensify/App/pull/24003
