### ISSUE TITLE
Dev - Lint is running on node_modules

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Project on VsCode
2. Open a terminal
3. Run: npm run lint
4. Notice multiple errors coming from node modules files

## Expected Result:
 Lint should not run on node_modules

## Actual Result:
Lint is running on node_modules

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Latest Main 
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  
![image - 2023-08-01T132951 408](https://github.com/Expensify/App/assets/43995119/1bbbf8da-31b0-42e4-b6d3-04c8df01746e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690636757149339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Proposal from Contributor 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In our current configuration of the .eslintrc.js file, we are only instructing ESLint to ignore the node_modules/.bin/ and node_modules/.cache/ directories. However, we are not ignoring the entirety of the node_modules directory. As a result, this slows down lint execution significantly and also causes ESLint to display error messages originating from the node_modules directory.
This can be verified here:
 https://github.com/Expensify/App/blob/30fc9bf74f71c2c1f9e72e924c3013a32514a840/.eslintrc.js#L5-L5
### What is the root cause of that problem?
The root cause of this problem is the missing 'node_modules/**' pattern in the ignorePatterns array of the .eslintrc.js configuration file. Without this pattern, ESLint does not know to ignore all files and directories inside node_modules, leading to slower execution and unnecessary error messages.
### What changes do you think we should make in order to solve the problem?
To solve this problem, we should add 'node_modules/**' to the ignorePatterns array in the .eslintrc.js file. This pattern tells ESLint to ignore all files and directories recursively inside the node_modules directory. By implementing this change, we can speed up ESLint execution and avoid error messages from the node_modules directory.
ignorePatterns: ['!.*', 'src/vendor', '.github/actions/**/index.js', 'desktop/dist/*.js', 'dist/*.js', 'node_modules/**', '.git/**'],
### What alternative solutions did you explore? (Optional)

**Comment by flaviadefaria** [comment]
@hayata-suenaga since you worked on the issue with the linked PR do you agree with the above?

**Comment by hayata-suenaga** [comment]
wow we actually wasn't ignoring node_module at all for linter all this time???

@flaviadefaria anyway, yes that PR should fix the issue
