### ISSUE TITLE
Error: dlopen (...node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace '_cairo_fill' when Running the project on M1

### ISSUE THREAD

**Issue by studentofcoding** [Expensify/App#24033]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Get the Repo offline
2. Follow Getting Started (successfully)
```
Install nvm then node & npm: brew install nvm && nvm install
Install watchman: brew install watchman
Install dependencies: npm install
```
3. Run `npm run web`
4. The error is shown & it breaks the WebApp.

## Expected Result:
The WebApp runs without error

## Actual Result:
The WebApp break with Error: dlopen (...node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace '_cairo_fill'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:*n*
**Reproducible in production?:*n*
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll test soon

**Comment by alexpensify** [comment]
Still on my test list

**Comment by alexpensify** [comment]
I realized that this one closed automatically. For now, I'm going to keep it closed since it should first be reported in  #expensify-open-source.
