### ISSUE TITLE
 Offline message not showing in Country and State selection screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline -> Go to settings
2. Click profile -> Click personal details
3. Click home address-> Click State/Country
## Expected Result: 
It should show offline message like other screens
## Actual Result: 
Country/State picker not showing offline message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/08f87975-9356-43d7-96c7-ddead6724d23

https://github.com/Expensify/App/assets/43996225/69859d3d-966b-4796-b7bb-ed21ca50be72

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690741191378189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
It seems like there's more to this issue than just the offline indicator not showing up on those pages when you switch to airplane mode. In the second video, you can't even load the personal details screen while offline, which I think you should be able to do.

@jasperhuangg do you think there's a chance this is also related to the recent changes around personal details?

**Comment by sakluger** [comment]
Asked Jasper in the original Slack thread.

**Comment by ahmedGaber93** [comment]
This issue is covered in this PR https://github.com/Expensify/App/pull/24164

**Comment by sakluger** [comment]
The other PR fixed this issue as well, closing 👍
