### ISSUE TITLE
Sign In - Unable to follow link. Stuck on the logo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24059]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On the log in screen, enter a new account email
2. Repeat the previous step with the same email - This is to receive 2 validation links
3. Navigate to the account email inbox and open the first email of the 2
4. Copy the magic link and change it to staging if necessary
5. Navigate to the staging link

## Expected Result:
Verify there's an error displayed indicating there was a problem with the magic link

## Actual Result:
Unable to follow link. Stuck on the logo

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cee0d63d-22b9-4712-b80a-25c3580725d8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Hmm @lanitochka17 would you mind updating the steps to reproduce to be a bit clearer? For example, in step 2, should I press the `back arrow` to repeat step 1? Your video doesn't show navigating to email either. Mind doing the video with all steps? TY!

**Comment by lanitochka17** [comment]
Issue is not reproducible on Build  1.3.50.2


https://github.com/Expensify/App/assets/78819774/b40dc495-0f03-4d91-a1a8-95220092af2c

**Comment by dylanexpensify** [comment]
Reviewing now!

**Comment by dylanexpensify** [comment]
Ok agree, closing out
