### ISSUE TITLE
[HOLD for PR #18997] Chat - Infinite loading after opening attached image a few times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any chat
3. Tap the "+" button and select "Add attachment" > "Choose from gallery"
4. Select any image and tap "Send"
5. Open the image and close it a few times

## Expected Result:
The image preview is shown every time

## Actual Result:
Infinite loading after opening the image preview a few times. The same behavior when opening images from old chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0fe353c5-d2d0-4577-8a92-a5fce6b361bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
might be same root cause https://github.com/Expensify/App/issues/22920

**Comment by garrettmknight** [comment]
@gadhiyamanan agreed, I think this looks like the same root cause. Let's put this on hold and leave this open until [this PR](https://github.com/Expensify/App/pull/18997) is deployed. I'll retest and see if that fixed it.

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/pull/18997
