### ISSUE TITLE
Bank account - Something went wrong error message when connecting to bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23915
## Action Performed:
1. Click on ‘profile’ avatar
2. Click on ‘Workspace’ link
3. Open an existing ‘Workspace’
4. Click on “Connect bank account’ link
5. Click on “Connect manually” link
6. Fill out all forms, and click submit button

## Expected Result:
Get secure link” page displayed

## Actual Result:
Something went wrong error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6150561_Screen_Shot_2023-08-02_at_11 04 57_AM](https://github.com/Expensify/App/assets/78819774/c4a0dac1-b975-4ba4-8c4f-1d07bd3f93e6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
@puneetlath This was handled here in this PR. do we need to cherry pick this?

**Comment by hayata-suenaga** [comment]
writing a request for cherry pick in deployer channel

**Comment by hayata-suenaga** [comment]
requested cherry pick [here](https://github.com/Expensify/App/issues/24063)

**Comment by hayata-suenaga** [comment]
QAed the cherry pick and tested well removeing deploy blocker label
