### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] App crashes when deleting workspace while in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND
2. Create 5 workspaces & make sure you have 5 active workspaces
3. Apply offline network mode in dev tools
4. Delete 2 workspaces in offline mode
5. Close RHN > click on 'Profile' avatar  & navigate to Settings page
6. Apply 'No throttling' in dev tools while 'Settings' page is opened
## Expected Result: 
App shouldn't crash
## Actual Result: 
App crashes
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c7b0c0ce-76bc-4563-979a-958e5d83c638

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690459285350399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab283e641a86aa39</li>
        <li>Upwork Job ID: 1688971711391633408</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26028363</li>
<li>s-alves10 | Contributor | 26028364</li>
<li>natnael-guchima | Reporter | 26028365</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
Thank you
I'll create a PR in a few hours

**Comment by s-alves10** [comment]
@fedirjh 

[PR](https://github.com/Expensify/App/pull/24318) is ready for review

**Comment by techievivek** [comment]
Not overdue, waiting for payment to be done.

**Comment by techievivek** [comment]
Regression test proposal looks good to me, let's wait for @sonialiap to get this added to the testRail.

**Comment by sonialiap** [comment]
Sorry for the delay, back from OOO and sending payments:

- @Natnael-Guchima bug report $250
- @s-alves10 fix + bonus $1500
- @fedirjh review + bonus $1500
