### ISSUE TITLE
Download - Appended time to downloaded file name is not following local time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23531
## Action Performed:
1. Launch New Expensify app
2. Go to any room
3. Tap on room header > Share code
4. Download the QR code

## Expected Result:
The appended time to downloaded file name is following the local time

## Actual Result:
The appended time to downloaded file name is not following the local time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dba2b9a1-7873-4641-94e6-1f5c9189d6f3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
@lanitochka17 This isn't a deploy blocker right, since this was just added in https://github.com/Expensify/App/pull/23531 which was just deployed to staging?

**Comment by Li357** [comment]
Is it important to have the right timezone? Right now, it produces an ISO 8601 string which we can easily change to account for timezone offset.

**Comment by Li357** [comment]
I'm going to close this since the only reason we append timestamps is to different filenames in extreme cases. Seems like [UTC is fine](https://expensify.slack.com/archives/C03TQ48KC/p1691013546366259).
