### ISSUE TITLE
Web - Downloading image from reply in thread of unavailable workspace room redirects to 404 page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. Invite user A to any workspace using user B
4. From user A, open #announce of workspace used in step 3 and send any image attachment
5. Hover on image and click on reply on thread, send few messages and pin the thread
6. From user B, remove user from the workspace used in step 3
7. From user A, in reply in thread report opened in step 5, click on download on the image and observe that it redirects to 404

## Expected Result:
App should either not allow user to download the image by removing download icon or if download icon is displayed, app should allow to download the image from the thread

## Actual Result:
App redirects to 404 page of oldDot website when we click on download icon on image in reply in thread report of unavailable workspace room

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** needs repro 
**Reproducible in production?:** needs repro
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/98009061-30fe-4554-b8cd-6f7b7dbad23c

https://github.com/Expensify/App/assets/43995119/8a0f7716-fd51-4f59-9d1c-78bf7618d582

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690795548498429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pac-guerreiro** [comment]
I'm Pedro Guerreiro, an expert from Callstack and I can look into this issue 😄

**Comment by pac-guerreiro** [comment]
@laurenreidexpensify 

I followed the steps described above but I wasn't able to reproduce this issue.

**Comment by pac-guerreiro** [comment]
The image url does point to the old dot website but it's downloadable.

One thing of concern that I did find out while trying to reproduce was that the user A is able to send messages or react in the pinned thread of the workspace that he no longer belongs to 😅
