### ISSUE TITLE
[$1000] Incorrect currency conversion from Japanese Yen to Kenyan Shilling when requesting money

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Since the default currency is determined based on a user's IP address on account creation, a VPN might need to be used to create the testing account so its default currency is the Kenyan Shilling.
Additionally, testers in other countries could replace the Kenyan Shilling with their respective currencies to see if this is reproducible for them.
1. Log into an account with the Kenyan Shilling set as the default currency.
2. Open a chat, click on the "+" sign in the composer, and then select "Request money". 
3. Click on the currency and change it to Japanese Yen i.e. JPY - Y.
4. Enter an amount in the thousands e.g. 7335.90, add an optional description (not a must), and then click the green button that says "Request 7336".
5. Keep in mind the amount in the IOU preview in the chat.
6. Google the amount you input in "Step 4" above converted to Kenyan Shillings.

## Expected Result:
The amount in the IOU preview should be somewhere in the ballpark of the converted amount you googled even given fluctuating conversion rates.

## Actual Result:
The amount in the IOU preview is vastly different from the actual converted one i.e. instead of being closer to 7,000, the number is around 70.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/7abce826-ccf9-46d2-950b-2a6d323a13b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690806631718269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7be468a643c1cf5</li>
        <li>Upwork Job ID: 1686995537756327936</li>
        <li>Last Price Increase: 2023-08-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Ah, what a weird conversion error! I tried with AUD and am seeing the same issue, where it's saying 7335 JPY = 70 cents AUD:

![image](https://github.com/Expensify/App/assets/30815269/4891e6bc-1ad5-47cb-bdeb-30398dd95054)

This is way off:

![image](https://github.com/Expensify/App/assets/30815269/0ced25b5-82c2-4804-a996-c577d96c49c0)

I wonder if it's only happening with JPY?

**Comment by alitoshmatov** [comment]
This issue is similar to https://github.com/Expensify/App/issues/19792. Where currencies with no small currency unit is being treated like they have it. 
Basically, this is happening: 
1. I have default currency `UZS` which has 2 decimals
2. If I request `USD` I am receiving `1167232`, and when showed in `UZS` it is `11672.32` (image 1)
3. If I request `JPY` I am receiving `81`, and when showed in `UZS` it is `0.81` (image 2)
**The problem** is that backend should have sent me `8100`

The this requires backend changes

image 1
<img width="743" alt="Screenshot 2023-08-03 at 12 40 46" src="https://github.com/Expensify/App/assets/59907218/65aee3f3-b5d1-44b2-b029-72de80da60da">
image 2
<img width="730" alt="Screenshot 2023-08-03 at 12 43 26" src="https://github.com/Expensify/App/assets/59907218/4e2afd38-e5ba-456f-91ec-65cf808d795d">

**Comment by nileshahir286** [comment]
It's required change in API side(backend).
Either in database side or may be stored procedure.
I need to check the table structure of database.

**Comment by nileshahir286** [comment]
It's required change in API side(backend).
Either in database side or may be stored procedure.
I need to check the table structure of database.

**Comment by nileshahir286** [comment]
Contributor details
Your Expensify account email: nileshahir286@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0126f3665fe23ff297

It's required change in API side(backend).
Either in database side or may be stored procedure.
I need to check the table structure of database.

**Comment by pradeepmdk** [comment]
@nileshahir286  We can't check the backend because that private repo. front end only open source. if we find any backend issues we need to post them here. The backend team internally takes that.

**Comment by nileshahir286** [comment]
Ok. Got it.
As I guess there are more than 2 decimal places when take currency rate from conversion API. so we need to apply multiple decimal places in backend.
Thanks

**Comment by jliexpensify** [comment]
Hi @nileshahir286 , just wanting to confirm here:

>It's required change in API side(backend).

Do you mean on the Expensify end? Sorry, I am not an Engineer.

**Comment by fitzmode** [comment]
.

**Comment by fitzmode** [comment]
Contributor details
Your Expensify account email: fitzmzuenda@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0108ca79919508296a

**Comment by fitzmode** [comment]
Contributor details
Your Expensify account email: fitzmuzenda@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~0108ca79919508296a)

**Comment by nileshahir286** [comment]
> Hi @nileshahir286 , just wanting to confirm here:
> 
> > It's required change in API side(backend).
> 
> Do you mean on the Expensify end? Sorry, I am not an Engineer.

@jliexpensify , Yes.

**Comment by aldo-expensify** [comment]
This seems related to https://github.com/Expensify/App/issues/19792, I'm pretty sure this used to be working and broke down the line. I'm going to work on this internally, as I just fixed a problem in the backend related to currencies.

**Comment by aldo-expensify** [comment]
I'm coming from this issue: https://github.com/Expensify/Expensify/issues/300539

There is another currency related issue here: https://github.com/Expensify/App/issues/23235
The backend fix: https://github.com/Expensify/Web-Expensify/pull/38411

**Comment by jliexpensify** [comment]
Not overdue

**Comment by aldo-expensify** [comment]
I'm still working on the front end fix, I'll try to finish it between today and tomorrow.

https://github.com/Expensify/App/pull/24175

**Comment by aldo-expensify** [comment]
I haven't return to this yet, I'll try to work on it tomorrow.

**Comment by aldo-expensify** [comment]
I worked on this Friday, I just have to retest and add testing steps to the PR: https://github.com/Expensify/App/pull/24175

**Comment by aldo-expensify** [comment]
PR https://github.com/Expensify/App/pull/24175 ready for review

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter: @Victor-Nyagudi $250

[Upworks Job](https://www.upwork.com/jobs/~01e7be468a643c1cf5)

Am I missing everyone? I don't think so, since it's internal.

**Comment by Victor-Nyagudi** [comment]
I've applied.

Thank you.

**Comment by jliexpensify** [comment]
@Victor-Nyagudi I'm happy to pay now as you're the bug reporter, but I don't think there is a need to ping me as the GH doesn't have a payment date.

**Comment by Victor-Nyagudi** [comment]
Sorry about that. 

I didn't know the payment protocol for issues fixed internally.

**Comment by jliexpensify** [comment]
Paid and job removed. @aldo-expensify feel free to close off this GH when you've sorted the PR!

**Comment by aldo-expensify** [comment]
I'll close this one. There is something pending in the backend for [RSD](https://github.com/Expensify/App/pull/24175#pullrequestreview-1578598195), but I'll keep track of that in this issue:

https://github.com/Expensify/Expensify/issues/300539
