### ISSUE TITLE
Chat - Action menu of " Deleted message" shows "reply in thread" option 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Tap on a conversation which has owned thread conversation with several messages
3. Long press the parent message of the thread conversation
4. Tap delete comment
5. Long press the deleted message to note action menu options

## Expected Result:
The action menu of " Deleted message" must show only " Mark as unread" option

## Actual Result:
The action menu of " Deleted message" shows two options " Mark as unread" and "reply in thread"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4f3a8003-3018-4dc9-8361-e22cef11480f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
@lanitochka17 Was this from a regression test? If so, can you link to the TestRail? If not, I'm not convinced that this is a bug, as you *can* reply in thread on a deleted message. Please reopen if there's that TestRail, thanks!
