### ISSUE TITLE
Home address- Selecting suggested address, zip and address number are not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. Tap on profile icon
3. Tap on profile
4. Tap on personal details
5. Tap on home address
6. Type "Therku" in address line 1
7. Select each of suggested addresses to see all fields auto populated
8. From, same suggested list select address " Therku Thottam Road, CHIL SEZ IT Park, Saravanampatti, Coimbatore, Tamilnadu, India

Another scenario
  9. Type address " 158 torquoy rd Paignton devon in address line 1
10. From suggested address, select " 158 Paignton Road, Stoke Gabriel, Totnes, Devon, UK

## Expected Result:
When user selects suggested addresses, all fields must be auto-populated including zip/ postcode.

Another scenario:
When user select address mentioned in 10th step, the auto populated field must show all the details of selected address including address number "158"

## Actual Result:
After typing "therku" and selecting each selected address all fields auto populated except for address mentioned in 8th step.
When user select address mentioned in 8th step, all fields are auto-populated except zip/ postcode

Another scenario:
When user select address mentioned in 10th step, the auto populated field must show all the details of selected address but the address number "158" is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b0a2ea0c-9b04-4908-bcec-4471c14107e3

https://github.com/Expensify/App/assets/78819774/375dbbe6-cc14-4e0d-872f-954a5f1c47b6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkarkachov** [comment]
It shows all the **avalaible** details of selected address. But Google does not have zip code for requested places, [1st place](https://www.google.com/maps/place/Therku+Thottam+Rd,+CHIL+SEZ+IT+Park,+Saravanampatti,+Coimbatore,+Tamil+Nadu,+India/@11.1030929,76.9785022,17z/data=!3m1!4b1!4m6!3m5!1s0x3ba8f70a06cc34f5:0xde9847592dff55ba!8m2!3d11.1030876!4d76.9810771!16s%2Fg%2F11b6jgtgdm?entry=ttu)
[2nd place](https://www.google.com/maps/place/Paignton+Rd,+Stoke+Gabriel,+Totnes,+UK/@50.4087047,-3.6186431,19z/data=!3m1!4b1!4m6!3m5!1s0x486d1baf7e823db7:0x7209cbcf235bcb0f!8m2!3d50.4087038!4d-3.6179994!16s%2Fg%2F1thlmhpn?entry=ttu)

**Comment by alexpensify** [comment]
Thank you @chiragxarora and @mkarkachov for the feedback, I need to research if there is no Zip Code for these locations. At the same time, there is going to be an upcoming update to the address fields. I'm seeing if we should close this one since Zip Codes will appear later.

**Comment by alexpensify** [comment]
I'm going to close since there will be a pretty big change to how the address fields are presented in the app. We can revisit after https://github.com/Expensify/App/issues/22018 is in production. Thanks!
