### ISSUE TITLE
Dev: Mark as unread not working when request money for workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB => request money
2. Input amount => next
3. Select a workspace => request 
4. Hover on message request money click mark as unread, Observe that the message is not marked unread.

## Expected Result:
Message is marked unread

## Actual Result:
Message is not marked unread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![bug](https://github.com/Expensify/App/assets/43996225/3566484d-6c9a-4ae7-80b0-e4ec419d4ad1)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691027823277929?thread_ts=1691027823.277929&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
@vitHoracek @Julesssss @luacmartins this is all still under beta, right? So probably NAB?

**Comment by Beamanator** [comment]
Marking NAB for now due to ^

**Comment by dangrous** [comment]
Seems like this can just be a regular external issue, I think?

**Comment by rushatgabhane** [comment]
even weired, why is there an option to "Pay" when the workspace owes you money

**Comment by maddylewis** [comment]
@dangrous - since this is happening on Dev, we will need an engineer to reproduce this one! will you lmk if it's still reproducible whenever you have a sec?

**Comment by maddylewis** [comment]
heya @isabelastisser - i am OOO until ~Aug 20. I am waiting for a response to my question here - https://github.com/Expensify/App/issues/24112#issuecomment-1666947598

depending on @dangrous's response, we can get the `External` label added and treat this like any standard bug issue 👍

**Comment by dangrous** [comment]
im not able to reproduce on latest main - I asked in Slack if the reporter is still able to reproduce

**Comment by dangrous** [comment]
@namhihi237 also cannot reproduce, so we're going to close
