### ISSUE TITLE
[HOLD for payment 2023-08-16] User can't click on header to open detail of public room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a public room from account A.
2. Copy url of that public room and paste the browser where account B is logged in
3. Notice that user B can't click on header or avatar of that room to open Detail page.
## Expected Result: 
User should be able to open detail page of that room
## Actual Result: 
User can't be able to open detail page of that room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Uploading 258138799-26e8b1db-fd4b-4357-9d2e-bbdca014bc5a.mov…

https://github.com/Expensify/App/assets/43996225/015f824f-91fa-4334-9b8b-337291bb6d5a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691038592033389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
Seems like PR https://github.com/Expensify/App/pull/23802 introduce this issue.

**Comment by sobitneupane** [comment]
We are working on the fix in [this PR](https://github.com/Expensify/App/pull/24091).

**Comment by Beamanator** [comment]
Fix is on staging!

**Comment by Julesssss** [comment]
Just noting this was marked as a regression of [this issue](https://github.com/Expensify/App/pull/23802#issuecomment-1663799998).

**Comment by deetergp** [comment]
Do we feel we need a new regression test to prevent this from occurring again in the future?

**Comment by adelekennedy** [comment]
not much traction here - I'm going to pay out @hungvu193 the reporting bonus and close this out

**Comment by adelekennedy** [comment]
Payouts due:

Issue Reporter: $250 @hungvu193 

Eligible for 50% #urgency bonus? **N**

Upwork job is [here](https://www.upwork.com/ab/applicants/1694060700840734720/job-details).
