### ISSUE TITLE
[$1000] Video Attachments Display Unrelated staging.Expensify.com Web Preview

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: Issue only with video mp4 files. No problem with images and pdf
1 Initiate a chat
2 Upload any video-mp4 files
3 Verify the  Expensify.com  web preview
4 Click on the web preview. Verify you are redirected to staging.expensify

## Expected Result:
Upload successful without web preview

## Actual Result:
Unrelated web preview of staging.expensify while uploading video files.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2023-08-03 at 10 41 57 PM](https://github.com/Expensify/App/assets/43995119/aac6a882-a92a-4ac7-8433-b276ca2bbfe2)

https://github.com/Expensify/App/assets/43995119/59c5ae7f-cfc5-4e8a-8430-c1c3a6ec1c55

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690847401009519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f88f014db6b7a31</li>
        <li>Upwork Job ID: 1687354934794571776</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by mvtglobally** [comment]
I believe there was this issue previously logged, but unable to locate. pls double check

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Link Preview is shown when a attachment other than image is uploaded.

### What is the root cause of that problem?
- The root cause is that the linkMetadata is set for the attachment other than image.

### What changes do you think we should make in order to solve the problem?
- Frontend Solution:
    - We can update the `ReportActionItem.js` code to check if reportAction is `attachment` then don't show the link preview.

<details>
<summary>Code Changes</summary>

```diff
+ const message = _.last(lodashGet(props.action, 'message', [{}]));
+ const isAttachment = _.has(props.action, 'isAttachment') ? props.action.isAttachment : ReportUtils.isReportMessageAttachment(message);
... rest code
- {!isHidden && !_.isEmpty(props.action.linkMetadata) && ( 
+ {!isHidden && !_.isEmpty(props.action.linkMetadata) && !isAttachment && (
```

</details>

- Backend Solution:
    - We can update the API to not set the linkMetadata for image or other attachments.

### What alternative solutions did you explore? (Optional)

- We can add a wrapper method in `ReportActionsUtils.js` to check if the message is attachment or not and if it is an attachment then remove the `linkMetadata` from that `reportAction`.

**Comment by stephanieelliott** [comment]
Agree that staging preview is weird, we should fix that

**Comment by saalimzafar** [comment]
Anyone here who can help me on this
I cloned the Expensify project but when I run `npm run web` I get into errors.
It's not working as expected like how it should work on `localhost` 
and even if it's open on localhost signing in leads me to the production website making me unable to do development.

Do I need to update the env files or what? I just updated the urls to localhost specially the Expensify urls.
But it's not working.
Also I send the Contributors to accept my invitation to let me join the slack channel but got no response!


Anyone from anywhere!! If you can do me a favor!!

**Comment by jeet-dhandha** [comment]
Updated issue its happening other than for pdf / image.

**Comment by LambdaLarkk** [comment]
I would like to work on this

**Comment by Tony-MK** [comment]
@saalimzafar I can help setup up your dev environment. Could you email me?

**Comment by saalimzafar** [comment]
@Tony-MK  thanks buddy
I have already forked the repo can you help me there. You can see listed repos on my profile.

**Comment by Tony-MK** [comment]
@saalimzafar I'm happy to help on Zoom, so email me (me@antonykitinzi.com) because this conversation is not appropriate here.

**Comment by stephanieelliott** [comment]
Actually, it looks like this is a dupe -- previously reported and on hold here: https://github.com/Expensify/App/issues/22837
