### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Tasks - User is unable to complete task without opening task first

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23971
## Action Performed:
1. As User A, create a group including User B &C
2. As User A, assign task to group with no assignees
3. Log out of User A and Log in to User B or C
4. Open newly created group and click box of new task to complete task(do not open task)

## Expected Result:
User is able to complete task without opening task in group

## Actual Result:
User is unable to click and complete task. The selected box is unselected automatically
"You do not have permission to do requested action" is shown after opening task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd932fae-be1a-4a14-bbc4-74067b107ae4

https://github.com/Expensify/App/assets/78819774/c5e26ff9-2016-4805-8c4d-cf1e66c6f7aa

https://github.com/Expensify/App/assets/78819774/846871b2-e7a7-47d1-b1f8-6c46da390b42

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f28e9843a6957b04</li>
        <li>Upwork Job ID: 1697329510087221248</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by thienlnam** [comment]
> Why should user B or user C be allowed to edit the task?

We updated this recently, anyone that can view the task should be able to modify the task

**Comment by thienlnam** [comment]
This might be a BE issue

**Comment by thienlnam** [comment]
Haven't looked into this yet - been focused on wave5

**Comment by thienlnam** [comment]
Same as above, focused on wave 5 so no updates here

**Comment by thienlnam** [comment]
Same as above, focused on wave 5 so no updates here - should be more free by the end of the week

**Comment by thienlnam** [comment]
Adding the External label so we get some C+ to review the existing proposals

**Comment by thienlnam** [comment]
I meant for this to be external actually, seems like the bot removed my label

**Comment by bfitzexpensify** [comment]
No proposals yet, will give it a few more days into next week before we consider changing the bounty

**Comment by bfitzexpensify** [comment]
Oh, I completely missed that, apologies @dukenv0307. Ok, @thesahindia, if you could take a look at @dukenv0307's proposal when you get a chance, that would be great — thanks!

**Comment by thienlnam** [comment]
c

**Comment by thienlnam** [comment]
> If we want to fix from BE, we should send the taskReport to shareSomeWhere when it is created.

**Comment by thienlnam** [comment]
Thanks, I think that's the ideal solution actually as opposed to the FE solution. Let's do that instead

**Comment by thienlnam** [comment]
I can take this, but won't get around to it for a while due to other priorties

**Comment by thienlnam** [comment]
Same ^

**Comment by thienlnam** [comment]
Same ^ though will have more free cycles next week

**Comment by thienlnam** [comment]
Been focused on Money2020 and so haven't gotten around to this yet. Though I have a few other task BE updates I'll make at the same time

**Comment by thienlnam** [comment]
Took a look at the code today and we allow you to modify a task if you have access to the parent report. I think we should actually do the FE fix for this - we don't necessarily want to share the task automatically unless you try to access it. 

@dukenv0307 Do you still want to take this?

**Comment by thienlnam** [comment]
Hmm dang, it seems like in any case we need to give the user has access to the task or it will break other things like this and then we'd have to add other workarounds to make it happen. I'll keep looking in the BE later this week

**Comment by thienlnam** [comment]
There's an internal thread with mentions that deals with a similar problem.

I think the approach may be on a task action, checking whether they can access it or not and then sharing it with them if so

**Comment by thienlnam** [comment]
Bumping this to a weekly since it's not that urgent and will require internal changes

The problem that we keep coming back to is that because the task report isn't shared with you immediately, there are issues that happen when you try to action it without having access to it

So on task actions, we need to check if they have access or not and pre-sharing the report with them

**Comment by thienlnam** [comment]
Was OOO and is thanksgiving weekend this week, going to bump this on a monthly since it's not urgent nor a main flow

**Comment by thienlnam** [comment]
Going back to this, let's just disable the task completion until the task is opened / shared with you

**Comment by bfitzexpensify** [comment]
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- ready for payment on 01/17
- BZ checklist needs completing (bump on that @thesahindia)

**Comment by thienlnam** [comment]
On hold for payment

**Comment by isabelastisser** [comment]
@dukenv0307 offer sent in Upwork, please accept it and I will process the payment. Thanks!

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/24169#issuecomment-1896240639).
