### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Fix require cycle from `subscribeToReportCommentPushNotifications`

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#24174]
## Action Performed:
Run the app on Android

## Expected Result:
No warnings about a require cycle

## Actual Result:
A warning for a require cycle occurs.

```
WARN  Require cycle: src/libs/actions/Session/index.js -> src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js -> src/libs/Notification/PushNotification/backgroundRefresh/index.android.js -> src/libs/actions/App.js -> src/libs/actions/Session/index.js
```

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e26d73a28da0cafc</li>
        <li>Upwork Job ID: 1687585347865071616</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26197726</li>
</ul></li>
    </ul>
</details>

**Comment by arosiclair** [comment]
@muttmuure no need to try to reproduce this atm. This is a follow up for a console warning from [this PR](https://github.com/Expensify/App/pull/24128#issuecomment-1666111075). I'll submit a PR to fix it and get it tested.

**Comment by arosiclair** [comment]
Holding until that PR is merged

**Comment by arosiclair** [comment]
My local dev builds have been broken for days and a fix is probably not coming soon enough. I'm going to open this to contributors. 

The best fix I saw is to move deep linking functions in `src/libs/actions/App.js` to it's own module `src/libs/actions/DeepLinking.js`. This should remove App.js's dependency on Session.js and break the require cycle.

**Comment by arosiclair** [comment]
Good call on your alternative solution @dukenv0307, let's go with that since it's a much smaller change.

>  All the libs are named based on a purpose, Deeplink does not serve any standalone purpose.

We're not going with the original proposal, but I'm not sure I follow your reasoning here. Handling deep linking is/was the purpose. Moreover, the separation of modules is not so strict like this in practice as a lot of modules have cross-cutting concerns (handling deep-linking in App.js is one of those examples).

> IMO, backgroundRefresh is placed in the wrong place. The main logic inside this lib does not have to do anything with Push Notifications but we are calling this function in a push notification event. So we should instead expose the backgroundRefresh from App.js lib instead of using its own exports and use it like App.backgroundRefresh() anywhere we want. Not sure of this solves the issue though but it is better this way.

Yeah let's not do that 😄. For context, this background refresh functionality is tightly coupled to push notifications and should not be called anywhere outside of that push notification handler. It wouldn't work anyway since it's an Android-only function.

**Comment by strepanier03** [comment]
@muttmuure - You're already working on this as BZ right? I got assigned as well when the external label was applied but I think it shouldn't have assigned me if you're already the BZ assigned. Let me know if you need me to handle this one otherwise I'll unassign myself this week since we don't need two BZs.

**Comment by arosiclair** [comment]
This was just a follow up issue [for another PR](https://github.com/Expensify/App/pull/24128/files) so no need for regression tests and etc. @muttmuure can you handle payment please?

**Comment by muttmuure** [comment]
$1500 - @dukenv0307 - C
$1500 - @parasharrajat  - C+

**Comment by muttmuure** [comment]
@parasharrajat is paid on NewDot, so I think we need @JmillsExpensify to pay it

**Comment by JmillsExpensify** [comment]
@muttmuure please close any issues that only lack a NewDot payment. Those payments use a separate process not tied to Github.

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @parasharrajat based on BZ summary.
