### ISSUE TITLE
Notification- Updated avatar is not shown in notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre- con: An custom avatar is set, User B can be Android app Or mweb
1. Launch app
2. From User B(secondary),Send a message to User A(main)
3. In User B account, remove custom and set to default avatar
4. Send messages to User A
5. Note the avatar displayed in User A notification
6. Set new avatar for User B
7. Send messages to User A
8. Note the avatar displayed in User A notification

## Expected Result:
Unknown

## Actual Result:
In step 5, default avatar, should be displayed
In step 8, custom avatar ie., new set avatar should be displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/02d1d6d0-0ee0-4b32-96d8-d6366a66198e

https://github.com/Expensify/App/assets/78819774/5cade183-6389-4fa9-9309-6a3ae5185daf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Asking for a second opinion here - https://expensify.slack.com/archives/C01GTK53T8Q/p1691446400675229

**Comment by lschurr** [comment]
Per Slack, this isn't a bug - Once a notification is sent, it’s content/avatar can’t be modified.
