### ISSUE TITLE
Incorrect Video File Name Displayed as "rn_image_picker_lib_temp" in Android App when Uploaded from Gallery

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Initiate a chat
2 Go to Add attachment > Upload any video > choose document > choose any video (Just remember the filename). Verify the correct file name upon add.
3 Go to Add attachment > Upload any video > Choose from gallery > choose the same video
4 Verify it is uploaded as ‘rn_image_picker_lib_temp"’filename

## Expected Result:
Accurate filename upon upload without any inconsistency between upload from choose document vs upload from gallery

## Actual Result:
When uploading video files from the Android app using the "upload from gallery" option, the video files are displayed with the name "rn_image_picker_lib_temp" instead of their actual file names. This issue occurs exclusively on Android devices and only when the video is selected from the gallery. If uploaded from chose document, it is attached accurately

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-6
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y  
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/8e70d36f-9b85-4672-97d2-067c8f5a35d8

https://github.com/Expensify/App/assets/43995119/56960af2-5ac7-4637-8e9a-13494e03d741

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690848503267109 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
Yes, thanks for identifying @ahmdshrif. This looks to be a dupe.
