### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Android/MWeb - Inconsistency bug: Android chrome does not allow vertical scroll on multiline horizontal scrollable code block

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send multiline horizontal scrollable code block eg:
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
Test
Test
1
2
3
4
5
```
4. From android chrome, try to scroll vertically over that code block, observe that it does not allow
5. From android app, try to scroll vertically over that code block and observe that it allows to scroll up to previous messages

## Expected Result:
App should not block scroll vertically to previous messages when scrolled over code block as it allows on android app

## Actual Result:
App blocks scroll vertically to previous messages when scrolled over code block on android chrome

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/10e4e3c2-4402-4120-97dd-74d3456627f8

https://github.com/Expensify/App/assets/43995119/88ef4825-33ea-499c-a317-c26fb31f8055

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690949529360049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c752c085d8a6cf1</li>
        <li>Upwork Job ID: 1689581173954527232</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26245611</li>
<li>akinwale | Contributor | 26245613</li>
<li>dhanashree-sawant | Reporter | 26245615</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Set the overscroll behaviour to auto on the BasePreRenderer scrollview.

### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment]
reviewing now!

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Didn't get an update today, will on Monday!

**Comment by dylanexpensify** [comment]
[Bumped in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1692193382629589)

**Comment by dylanexpensify** [comment]
@aimane-chnaif bump

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
@aldo-expensify what do you think?

**Comment by aldo-expensify** [comment]
@akinwale 's proposal looks good to me too. Assigning!

**Comment by akinwale** [comment]
@aimane-chnaif My [PR](https://github.com/Expensify/App/pull/25605) is ready for review. Thanks.

**Comment by dylanexpensify** [comment]
Waiting for regression period to be over!

**Comment by dylanexpensify** [comment]
reviewing now!

**Comment by akinwale** [comment]
@aimane-chnaif @dylanexpensify Just checking in here for BZ checklist update and payment. Thanks!

**Comment by akinwale** [comment]
@dylanexpensify bump

**Comment by dylanexpensify** [comment]
Sorry, was busy at a conference! Unfortunately, we've decided that we'll be adhering to the timeline unless specifically impacted by our own internal delays. I hope you all understand, and appreciate your time and amazing work! Payments inbound

**Comment by dylanexpensify** [comment]
Payment summary:

- Reporter: @dhanashree-sawant $250
- Contributor: @akinwale $1,000
- Contributor+: @aimane-chnaif $1,000

[Upwork job](https://www.upwork.com/jobs/~015c752c085d8a6cf1). Please apply!

**Comment by akinwale** [comment]
> Sorry, was busy at a conference! Unfortunately, we've decided that we'll be adhering to the timeline unless specifically impacted by our own internal delays. I hope you all understand, and appreciate your time and amazing work! Payments inbound

Isn't this rather harsh? My PR had been ready (including requested changes) since 2023-08-21 (the same day I got assigned). I also had to bump for a review 2 days later, and the timeline for the merge was only 28 minutes past the 72-hour deadline. I was only able to control what I could in this regard which was to make sure everything was ready early and bump due to delays, and it still falls within the third business day if we're considering up till the end of the day. Can an exception be made here?

Could we also at least get some sort of announcement so we'll know what the expectations are going forward?

**Comment by akinwale** [comment]
> [Upwork job](https://www.upwork.com/jobs/~015c752c085d8a6cf1). Please apply!

@dylanexpensify Looks like I already accepted the auto-offer when the issue was assigned. Has any consideration been made about the bonus here? Thanks.

**Comment by dylanexpensify** [comment]
Let me bring up - thanks for your patience! ❤️

**Comment by dylanexpensify** [comment]
Ok sorry for the back and forth - we _will_ payout the bonus here! TY for your help here!

**Comment by dylanexpensify** [comment]
Updated payment summary!

**Comment by dylanexpensify** [comment]
Done! Payments sent (with correct amount)!

**Comment by akinwale** [comment]
> Done! Payments sent (with correct amount)!

Received. Thanks!
