### ISSUE TITLE
[HOLD for payment 2023-08-21] Update App to react-native version 0.72.3 and remove patches

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#24208]
Coming from this discussion in slack https://expensify.slack.com/archives/C01GTK53T8Q/p1691377395570339

We upgraded to react-native `0.72.1`. There were still some breaking issues and we applied patch for that. Example: https://github.com/Expensify/App/pull/24203

Update react-native to `0.72.3` (latest as of today) and remove the patches

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by MonilBhavsar** [comment]
Sorry shawn, no design change is required here.

**Comment by MonilBhavsar** [comment]
Assigned @aimane-chnaif as per https://expensify.slack.com/archives/C01GTK53T8Q/p1691411675022879?thread_ts=1691377395.570339&cid=C01GTK53T8Q

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by fabioh8010** [comment]
PR is ready: https://github.com/Expensify/App/pull/24224

**Comment by MonilBhavsar** [comment]
@anmurali can we please play @aimane-chnaif for reviewing the PR

**Comment by MonilBhavsar** [comment]
HOLD on payment

**Comment by MonilBhavsar** [comment]
Bumping to weekly. cc @anmurali we need to issue payment here

**Comment by anmurali** [comment]
Offer is [here](https://www.upwork.com/nx/wm/offer/26431947) @aimane-chnaif

**Comment by MonilBhavsar** [comment]
@aimane-chnaif are you paid. If so, I think we can close this now

**Comment by MonilBhavsar** [comment]
@anmurali could you please help here to accept the contract

**Comment by MonilBhavsar** [comment]
Waiting for approval from @anmurali

**Comment by MonilBhavsar** [comment]
Same ^ cc @anmurali

**Comment by MonilBhavsar** [comment]
@anmurali 👋

**Comment by anmurali** [comment]
I am confused. I paid this a long time ago
<img width="632" alt="image" src="https://github.com/Expensify/App/assets/14225673/7b3bd936-c340-44b8-9964-4e1784d911b3">

**Comment by MonilBhavsar** [comment]
Thanks for confirming!
