### ISSUE TITLE
[$1000] App allows to start chat with 'receipts@expensify.com' and throws Hmm... its not here page error on request money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open search
3. Search ['](mailto:'receipts@expensify.com)[receipts@expensify.com](mailto:receipts@expensify.com)'
4. Click on result, send few messages and observe that app does not throw any error
5. Click on plus and request money, enter any amount and complete the request
6. In message, click on request money message and observe that it redirects to 'Hmm.. its not here' page
## Expected Result: 
App should not allow to chat with ['](mailto:'receipts@expensify.com)[receipts@expensify.com](mailto:receipts@expensify.com)' and if allowed then it shouldn't allow to request money
## Actual Result: 
App allows to chat with ['](mailto:'receipts@expensify.com)[receipts@expensify.com](mailto:receipts@expensify.com)' and also allows to request money but provides 'Hmm... its not here' page error on click on request money message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d2068c6c-7fe5-4c9f-a33f-bef22600da24

https://github.com/Expensify/App/assets/43996225/0b072a9b-1416-435c-a242-ccd50cccc8ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690888568897529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa63104761eb0936</li>
        <li>Upwork Job ID: 1691807656991072256</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I agree we should do something about this one.

**Comment by JmillsExpensify** [comment]
Internal may be required though triaging to community first.

**Comment by b4s36t4** [comment]
@JmillsExpensify What should be the expected behaviour here? Let's not allow user to open the chat with the expensify mails... or redirect the user to concierge or let's just don't show any actions menu's for this type of particular chats?

**Comment by situchan** [comment]
> App should not allow to chat with ['](mailto:'receipts@expensify.com)[receipts@expensify.com](mailto:receipts@expensify.com)' and if allowed then it shouldn't allow to request money

@JmillsExpensify what is the expected behavior? Former one?

**Comment by JmillsExpensify** [comment]
You shouldn't be able to chat with receipts@expensify.com.

**Comment by JmillsExpensify** [comment]
>@JmillsExpensify What should be the expected behaviour here? Let's not allow user to open the chat with the expensify mails... or redirect the user to concierge or let's just don't show any actions menu's for this type of particular chats?

Elaborating on my last comment, I think we want to allow chatting with Expensify emails generally, but there are very special emails where you can't. receipts@expensify.com is an example. This shouldn't show up in optionList, which means you won't be able to chat or request money from it.

**Comment by JmillsExpensify** [comment]
@Gonals This is also a related issue I was thinking about and it relevant to our internal convo.

**Comment by JmillsExpensify** [comment]
And based on that convo, maybe we actually do nothing about chatting with receipts@expensify.com, and instead add receipts to the existing list where we don't allow requesting money. That's kind of the core problem for this issue anyway.

**Comment by Gonals** [comment]
> And based on that convo, maybe we actually do nothing about chatting with [receipts@expensify.com](mailto:receipts@expensify.com), and instead add receipts to the existing list where we don't allow requesting money. That's kind of the core problem for this issue anyway.

Yep. I think that's a valid and simple approach

**Comment by JmillsExpensify** [comment]
@puneetlath I'm wondering if we should pull this into the recent internal discussion that we had in Slack?
