### ISSUE TITLE
[$1000] Offline - Number of replies on thread incorrect after remove the parent message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a message
3. Click reply on thread on above message
4. Send 4 messages
5. Go setting => Preference => Force offline
6. On the thread, hover on parent message and click delete
7. Click on header to go the parent report, Observe that the number of replies is 3 even though the thread has 4 messages
## Expected Result:
The number of replies is equal to the number of messages in the thread excluding the parent message
## Actual Result:
The number of replies is not equal to the number of messages in the thread excluding the parent message after delete parent message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a758a491-3155-448a-8f06-6f8f8d5f3fdf

https://github.com/Expensify/App/assets/43996225/9aaf67b6-1ef8-4dd9-97e4-be1cbfd7ffc8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690909313784889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013add6557c0275653</li>
        <li>Upwork Job ID: 1688988531809570816</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
Offline - number of replies is equal to the number of messages in the thread excluding the parent message
### What is the root cause of that problem?
When deleting a comment, we are building data for the parent report [here](https://github.com/Expensify/App/blob/96df82241e7f07a68f7bf681025031e128f4865c/src/libs/ReportUtils.js#L1555)
In which we will subtract 1 when deleting a comment in the thread.
https://github.com/Expensify/App/blob/96df82241e7f07a68f7bf681025031e128f4865c/src/libs/ReportUtils.js#L1571-L1574
The problem here is that when we delete the first message of the parent report in the thread, we still subtract 1. That leads when offline the result is wrong.
### What changes do you think we should make in order to solve the problem?
We should check whether we are deleting the first message of the parent report or not, to calculate the number of comments based on that.
We add a param `isParentMessage` for the function in [here](https://github.com/Expensify/App/blob/96df82241e7f07a68f7bf681025031e128f4865c/src/libs/ReportUtils.js#L1555):
```
   else if (type === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && !isParentMessage) {
```
The same [here](https://github.com/Expensify/App/blob/96df82241e7f07a68f7bf681025031e128f4865c/src/libs/ReportUtils.js#L1597) and pass params:
```
[parentReportAction.reportActionID]: updateOptimisticParentReportAction(parentReportAction, lastVisibleActionCreated, type, isParentMessage),
```
Update in a `deleteReportComment` function [here](https://github.com/namhihi237/App/blob/e2694f52ce61fa9e67ee7ab1636cc38b2ba24d48/src/libs/actions/Report.js#L967C5-L967C5)
```
    const isParentMessage = ReportUtils.isThreadFirstChat(reportAction, reportID);
    const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(reportID, optimisticReport.lastVisibleActionCreated, CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE, isParentMessage);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment]
I think this is [dupe](https://github.com/Expensify/App/issues/23365).

**Comment by abdulrahuman5196** [comment]
> I think this is [dupe](https://github.com/Expensify/App/issues/23365).

Thanks @akamefi202  for pointing out. @isabelastisser This is a dupe. we can close this one

**Comment by isabelastisser** [comment]
dupe, closing!
