### ISSUE TITLE
nconsistency bug: Mention results are not displayed when report is open from mention details

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Open any report
3. Send message with mention for same user as current report
4. Write @ to open mention results
5. Click on header to open user details
6. Click on message and observe that app opens the mention results
7. Click on mention sent in step 3, on details page again click on message
8. Observe that now even though we have focus on compose box, mention results are not displayed
## Expected Result:
App should display mention results if compose box has text that triggers the results and we open the report from mentions->user details->click on message as we display on mac chrome and other platforms
## Actual Result:
App does not display mention results even if compose box has text that triggers the results when we open the report from mentions->user details->click on message
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.50-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/16f04b8f-41d4-43f8-b1d6-a4434865b8d5

https://github.com/Expensify/App/assets/43996225/31e2e018-512d-4fd1-90a4-d4d864801440

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690905077812999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
I reproduce, onSelectionChange is not called on focus for some reason

**Comment by stephanieelliott** [comment]
I'm confused -- even after reproducing, this doesn't seem like unexpected behavior? @dhairyasenjaliya would you mind pointing to the exact timestamp in the video where the unexpected behavior is occurring?

**Comment by ShogunFire** [comment]
Usually when the composed box is focused and we the end of the text is a mention we show the suggestion box, It{s not the case here and I think the issue is this inconsistency

**Comment by stephanieelliott** [comment]
I don't think this This looks and feels like expected behavior, I don't think this is something that we necessarily need to fix.

**Comment by dhanashree-sawant** [comment]
Hi @stephanieelliott, you had marked dhariya in place of me, at 0:41, it should display the mention results. You can test the same on any other platform and it works fine. Issue is only on android chrome, that was the reason behind raising the bug.

**Comment by stephanieelliott** [comment]
@dhanashree-sawant I have raised this with the team again, and we have agreed that this is low-impact, edge case, and not something an end user would encounter during day to day use. We opting not to fix this and the issue will remain closed. Thanks. 

Internal discussion link for posterity: https://expensify.slack.com/archives/C01SKUP7QR0/p1693353209675189
