### ISSUE TITLE
Workspace settings accessible through clicks on workspace name area, and tooltip displays without hovering over workspace name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24238]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspace.
2. Select a workspace.
3. Attempt to open workspace settings by clicking anywhere within the workspace name area.
4. Observe that workspace settings are accessible through these clicks.
5. Additionally, notice that tooltips are displayed without requiring the cursor to hover over the workspace name.
## Expected Result: 
Workspace settings should only be accessible when clicking directly on the workspace name, and tooltips should appear only when hovering over the workspace name
## Actual Result: 
Workspace settings can be accessed by clicking anywhere within the workspace name area,Moreover, tooltips appear without needing the cursor to hover over the workspace name

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f1579a37-44db-4012-84b7-2e7cf79b107f

https://github.com/Expensify/App/assets/43996225/f480af2f-b4ac-497d-b71a-860cfcadccd9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691444583690069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment]
@adelekennedy Clicking on the username opens the profile settings. but workspace settings opened by clicking anywhere on workspace name area
