### ISSUE TITLE
Chat -  If editing a multiline message cursor appeared on the first line, not at the end

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Open chat with multiline message
3. Tap on edit

## Expected Result:
The cursor should appear at the end of the multiline message

## Actual Result:
If editing a multiline message cursor appeared on the first line, not at the end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/49da870a-70c2-45a3-9d50-a87ddfbdd5a2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment]
looks like same issue https://github.com/Expensify/App/issues/24157

**Comment by bondydaa** [comment]
yep I agree @pradeepmdk it seems to be the same, cursor is always just put at the beginning of the text when editing instead of the end, whether it's a single or multi-line.

I'm going to close this out in favor of https://github.com/Expensify/App/issues/24157
