### ISSUE TITLE
No spacing between header, content, and bottom in the attachment modal.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Upload attached image.
2. Open the image

## Expected Result:
There should be vertical padding for the content component in the attachment modal.

## Actual Result:
There is no vertical padding for the content component in the attachment modal.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** Y  
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/cb22ea6f-6ce0-407d-8d33-7ba0bc8884d0

![Monosnap आचार्य प्रशान्त - Acharya Prashant's YouTube Stats (Summary Profile) - Social Blade Stats 2023-08-02 13-53-15](https://github.com/Expensify/App/assets/43995119/fc3c5fec-82de-454b-bbf0-bd5300300236)
![No_Spacing_Atachment (1)](https://github.com/Expensify/App/assets/43995119/ebe30651-e262-4a06-b90a-e848bd17bc0d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690968971021189 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no padding for images in the attachment preview container.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
None

**Comment by mvtglobally** [comment]
Proposal from @Krishna2323 

Proposal:

Please re-state the problem that we are trying to solve in this issue
No padding to attachment content view

What is the root cause of that problem?
There no padding applied to the component (styles.imageModalImageCenterContainer) which shows the attachment content.

https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/components/AttachmentModal.js#L320C1-L340C24

What changes do you think we should make in order to solve the problem?
We can add padding to the component (styles.imageModalImageCenterContainer) which displays the attachment content.

**Comment by shawnborton** [comment]
Correct, this is working as intended, we can close.

**Comment by shawnborton** [comment]
This has come up before and I think it's because of the PDF viewer. Again, let's keep this closed.
