### ISSUE TITLE
Attempting to Download Deleted Video Attachment redirects to 404 page not found page of staging.expensify

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: Follow the steps exactly. You need two users: User A and User B
From Android
1 Login as User A and Initiate a chat with User B
2 Upload a video > add attachment > choose document > upload video
3 Click on reply to thread on the video (Very very important)
4 On the thread >  Go to detail and click on leave thread. You will get concierge chat
5 Click on back 4 times until the main chat page is reached
6 Attempt to delete the video by going to delete comment.
7 Verify you can still see the video file with an error- “Report does not exist”
On the web: (Login as User B)
8 Attempt to download this deleted file. Verify you are redirected to staging.expensify 404 error

## Expected Result:
Unable to even access the download button

## Actual Result:
The video preview does not delete immediately so clicking on the download button leads to staging,expensify website 404 page not found error

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/72b62e1f-3233-44dc-b23d-4a89e64dcdf4

https://github.com/Expensify/App/assets/43995119/e10cb4f7-4864-42bd-a00f-cc7356b35b15

https://github.com/Expensify/App/assets/43995119/563e9855-bc80-40fc-80a2-b2c51705586c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690851849142539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Attempting to still repro w/browserstack!

**Comment by dylanexpensify** [comment]
Didn't get an update today, will on Monday!

**Comment by dylanexpensify** [comment]
posted to get someone to repro since I'm having a hard time doing it via Browserstack

**Comment by Julesssss** [comment]
I'm unable to reproduce on `v1.3.53-1`
