### ISSUE TITLE
Privacy Inconsistency: Split Money Reveals Private Details of Unknown Users 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Start a new chat with a user with whom there was no previous chat history. (try [jha3422+99@gmail.com](mailto:jha3422+99@gmail.com))
2 Go to the profile detail page of this new user
3 Notice that the chat feature correctly conceals private details.
4 Now, proceed to use the split money feature with the same new user with whom there was no chat history using another test account.
5 Click on the split money box. This will open the detail page. Click on the profile of the new user.
6 Verify that you can see the user's gender pronouns, and timezone, which were concealed by the chat
## Expected Result: 
The profile details of first time chat users (with whom there was no chat history) should remain consistent and private in both chat and split money since they all redirect to the same profile page.
## Actual Result: 
There is an inconsistency. The chat correctly conceals the private details of a user with whom there was no prior chat history. But the split money feature reveals timezone and pronouns.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1989af91-1cb3-463e-a749-fc0d7f6013e2

https://github.com/Expensify/App/assets/43996225/28d20317-65d5-4a5a-849f-5659b03cf436

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690935192161669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
> Dupe of https://github.com/Expensify/App/issues/22074

Agreed, thanks @bernhardoj
