### ISSUE TITLE
System message for payment is different in LHN vs report

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#24250]
LHN incorrectly indicates that the report was paid by contributors, though the actual and correct payment history is featured in the report. 

<img width="760" alt="Screenshot 2023-08-07 at 22 07 56" src="https://github.com/Expensify/App/assets/1127863/64b39347-27fd-4d53-b488-8a5eede38f99">

Filing as an internal bug as part of wave3. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa04cf9614f08985</li>
        <li>Upwork Job ID: 1688749720614326272</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
Ah so if this is an internal bug - we just need @fedirjh to review your (eventual) PR, @mountiny?

**Comment by JmillsExpensify** [comment]
Yeah. Also @luacmartins @mountiny feel free to put an internal label on this if you'd like. Given the payment flow I expected backend sleuthing to be required.

**Comment by sophiepintoraetz** [comment]
Bump for either @luacmartins or @mountiny to acknowledge whether they are taking charge of this one? 🙏

**Comment by luacmartins** [comment]
It seems that @mountiny is already assigned to this, so I'll let him handle it.

**Comment by mountiny** [comment]
Hello 👋 

this is coming from here https://github.com/Expensify/App/blob/61ab4bcf100500ce49bf1e2dfaa128f9511ea941/src/libs/ReportUtils.js#L1239 in case of expense reports, we take the policy name. 

This is kind of a side effect of having multiple admins now as that was not possible before. To confirm then, the message should say the display name/ email of the admin who actually paid the request? From the payee perspective/ employee its not really relevant and its the company who paid it

**Comment by JmillsExpensify** [comment]
>To confirm then, the message should say the display name/ email of the admin who actually paid the request? From the payee perspective/ employee its not really relevant and its the company who paid it

We actually want the message to come from the display name/email of the person who paid, yes. That's the intended design because it keeps a very specific audit trail on the request. Like yes the money is coming from the company bank account, but I think that's separate from this consideration.

**Comment by JmillsExpensify** [comment]
Going to take this one as part of wave3.

**Comment by mountiny** [comment]
Will look into this this week after completing some other priorities

**Comment by JmillsExpensify** [comment]
I actually can't reproduce this one anymore, and it's not appearing on reports that were recently reimbursed. I think we should actually close this one, though I'll re-open if I see again in the next pay run. 


![Image](https://github.com/Expensify/App/assets/1127863/32f4c322-c95f-43a4-892f-63c15ff3fef5)
