### ISSUE TITLE
Split bill - Creation date is not displayed in IOU details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on the + button
3. Click on "Split bill" in the action window
4. Enter any amount
5. Click on the "Next" button
6. Select 2 or more contacts
7. Click the "Next" button
8. Click on the "Split {Currency}{Amount}" button
9. Click on the newly created Split in group chat
10. Click on "Show more" in RHP

## Expected Result:
Split bill details should include the date of creation of the IOU

## Actual Result:
Split bill details are missing the date the IOU was created in the field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6156881_Screenshot_2023-08-08_at_02 24 40](https://github.com/Expensify/App/assets/78819774/5c9e10dc-f550-4a08-aca3-f29d54e415f5)

https://github.com/Expensify/App/assets/78819774/143d11ce-47bc-405e-ad61-50de2c90e119

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by manjesh-yadav** [comment]
it seems under a development feature https://github.com/Expensify/App/issues/23245 maybe it will be fixed in upcoming PR by @lukemorawski when he implements the edit feature
