### ISSUE TITLE
Chat - Glitchy scrolling experienced when reconnecting online after being offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the staging webapp
2. Go to chat where there is a huge history where you can scroll
3. Switch off the internet and wait for a few seconds
4. Switch back on the internet
5. Scroll upwards and downwards in the chat

## Expected Result:
No issues in scrolling/ page should be scrolled up or down smoothly

## Actual Result:
Scrolling is not moving smoothly, content keep flickering, sometimes page scrolls down while user is scrolling up. Scrolling will be functioning fine after page refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS /  Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/24e35b3e-d15e-406a-9e73-988e99d7853f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
@lanitochka17 I am not noticing anything out of the ordinary: 

![2023-08-08_15-42-20 (1)](https://github.com/Expensify/App/assets/24947345/3546da6e-9f6a-4ea4-ad1c-8d0b9c6dbaa2)

**Comment by lanitochka17** [comment]
@NicMendonca Check again with the team

**Comment by lanitochka17** [comment]
Not reproducible with expensifail account. Build 1.3.51.2

https://github.com/Expensify/App/assets/78819774/4c48a00b-4a3d-4a01-8a81-ad5ad8f1875b
