### ISSUE TITLE
[Navigation Refactor] - Chat - Option `Add attachment` works only after with second try

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://24041.pr-testing.expensify.com/
2. Login with any account
3. Open any chat
4. Click on the + (action) button near the composer -> Add attachment
5. Choose the document -> Open

## Expected Result:
The attachment must be downloaded

## Actual Result:
The attachment selection window opens again.
The option is blocked in iOS app at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-3 PR:24041

**Reproducible in staging?:** No

**Reproducible in production?:** N/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bbe86171-2743-4b32-a3c5-b9eab9a09b1a

https://github.com/Expensify/App/assets/78819774/565777c6-772b-4e78-b0e4-28906f75d41c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
@mountiny do you agree that we should keep this closed in favor of https://github.com/Expensify/App/pull/24041#issuecomment-1669766060
