### ISSUE TITLE
[$1000] Profile - Deleted contacts from the "contact methods" menu reappear after some time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24276]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Navigate to account settings > Profile
3. Tap on Contact Method
4. Tap the "New contact method" button
5. Enter any valid email address
6. Tap on the "Add" button
7. Tap on the account you just added
8. Tap on the "Remove" button
9. Confirm your selection

## Expected Result:
When deleting contacts from the "contact methods" menu, the contacts should be deleted and no longer appear in the menu until the user adds them again

## Actual Result:
When you delete contacts from the "contact methods" menu, the contacts reappear in the menu after some time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d3777351-5f60-4411-a3b4-4d924f284b93

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6cd913f8585f609</li>
        <li>Upwork Job ID: 1689779922180239360</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by aditygrg2** [comment]
Agree with @ginsuma There is some issue with the API route.

**Comment by sakluger** [comment]
Adding external label. cc @Beamanator since you worked on some contact method updates a few months ago.

**Comment by Beamanator** [comment]
Hmm @cristipaval you worked on DeleteContactMethod recently, right? any idea why it could be timing out?

**Comment by cristipaval** [comment]
My change did not impact the query at all, I just added an early return which makes the command even faster in specific corner cases. I have no clue why it could time out and unfortunately, I am swamped with Saastr and don't have time to look at it this week 😢

**Comment by sakluger** [comment]
I'm going to apply the external label so we can get this fixed, but I think it's important that we check if this is a regression from a recent change.

**Comment by cristipaval** [comment]
The error comes from the backend, maybe apply the engineering issue to auto-assign an internal engineer

**Comment by sakluger** [comment]
Adding the engineering label on @cristipaval's recommendation. @yuwenmemon can you please check the error and let me know if we should make this internal?

**Comment by sakluger** [comment]
@yuwenmemon mind checking this out?

**Comment by sakluger** [comment]
@yuwenmemon is going on sabbatical soon, @madmax330 mind checking the error to see if we should make this internal?

**Comment by sakluger** [comment]
@madmax330 could you please take a look into this one to see if it should be internal?

**Comment by madmax330** [comment]
Yep will look into it

**Comment by madmax330** [comment]
Yeah I think this is internal, it looks like they're never actually deleted, so they keep coming back.

**Comment by sakluger** [comment]
Thanks! Switched to internal.

**Comment by madmax330** [comment]
Cool I'll try to get the PR up this week

**Comment by sakluger** [comment]
@madmax330 any updates?

**Comment by madmax330** [comment]
I looked into this today and I'm not able to reproduce it locally.

**Comment by madmax330** [comment]
@lanitochka17 can you try reproducing the issue?

**Comment by madmax330** [comment]
Bump @lanitochka17

**Comment by lanitochka17** [comment]
Issue is not reproducible on Build 1.3.74-2
Iphone 14 Pro Max/Safari
 

https://github.com/Expensify/App/assets/78819774/61e6a44c-5542-4d8e-8fbb-b0040507357c

**Comment by madmax330** [comment]
Cool let's close then
