### ISSUE TITLE
Web-Chat-Flagged comments reappear after getting removed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24278]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Flag the message as being an assault or harassment from account B
3. Wait for about 5 minutes

## Expected Result:
Removed contents due to being flagged should not reappear

## Actual Result:
The removed flagged content reappears after 5 minutes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-08-08 193211](https://github.com/Expensify/App/assets/115492554/4c3ce9c1-12a9-42fc-ba31-c1f268bac937)

https://github.com/Expensify/App/assets/115492554/c9bdaec8-bc19-47df-a0ac-ab79ffc32a9b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690972107681749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
bumped the thread - I still can't reproduce, want to confirm it is still happening before we move forward

**Comment by adelekennedy** [comment]
not reproducible
