### ISSUE TITLE
[Navigator Refactor] - Chat - PDF preview is not showing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24270]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: User must be logged in and in any chat
1. Click on "+" button in the compose box
2. Click on "Add attachment"
3. Upload a PDF file

## Expected Result:
PDF preview should be shown before uploading file

## Actual Result:
PDF preview is not showing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** speshial build 1.3.50.3 

**Reproducible in staging?:** No

**Reproducible in production?:**N/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7456498c-dd53-4b3f-999d-43742dcaed02

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
https://github.com/Expensify/App/pull/24041#issuecomment-1669768717
