### ISSUE TITLE
Assign Task - "User can not be found..." appears when selecting existing user to Share

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On LHN, click on the FAB button
2. Select Assign Task
3. Enter a title or description
4. Assign the task to yourself
5. On Share Somewhere, select a conversation with another user you have access to

## Expected Result:
User should be able to select conversation to share the task. The task should be created and displayed in the conversation with the other user

## Actual Result:
At first message "Invalid e-mail" is displayed. When continue to type "User can not be found..." appears when selecting existing user to Share Assign task with

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8770c21b-34fb-4eda-9ce5-478bd374d80e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Thanks @GItGudRatio! Agree this is intentional, unless you've chatted with the user before you won't be able to select them here.
