### ISSUE TITLE
Android - Chat - Go back to home page button redirects to concierge chat 

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Initiate a chat
2 Send an attachment or send any message
3 Click on reply on thread. This will open the thread
4 Open the detail page (the icon on top)
5 Click on Leave thread. Verify concierge is opened.
6 Click on the back button: Verify you get “hmm, it’s not here page‘ with a button “Go back to homepage” button
7 Click on Go back to homepage
8 Verify you to go concierge chat rather than home page

## Expected Result:
Since, it says go back to home page, I was expecting to be taken to the homepage

## Actual Result:
The button redirects to concierge chat rather than the home page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7b78fdc2-83e6-425e-8828-5bbd2c89e2d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Abhi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690851151974449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Agree with the reasoning there that this isn't a bug and we can close this.
