### ISSUE TITLE
Web - When deleting a file, there is a space between the username and the '[Deleted message]'

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24302]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Send an attachment.
3. Click on 'Reply in thread.'
4. Delete the thread file.
5. Notice the space between username and delete message
6. Now check that after deleting a text message

## Expected Result:
When deleting a file or text message, there should be consistent spacing between the username and the '[Deleted message]'

## Actual Result:
When deleting a file, there is a space between the username and the '[Deleted message]' message, causing an inconsistency in spacing compared to deleting a text message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/10efa300-8340-4e61-b6cd-d07f89a8fa80

https://github.com/Expensify/App/assets/115492554/77c26699-86f3-40df-ac41-9ebd01604bc3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Hussain
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690887871347529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment]
Dupe: https://github.com/Expensify/App/issues/24216

**Comment by kavimuru** [comment]
By mistake it has been created again, closing.
