### ISSUE TITLE
[hold for payment 2023-08-17] PDF blinks while open the PDF

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send a pdf file
2. open a pdf and scroll
## Expected Result: 
PDF blinks
## Actual Result: 
PDF should not blink

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/631f4010-fcda-4ce9-a369-d18a14ef8b47

https://github.com/Expensify/App/assets/43996225/9bf6e54f-e1c5-4db9-98c8-af8e5ac80cdb

[An_Improved_Bytewise_Approximate_Matching_Algorith.pdf](https://github.com/Expensify/App/files/12302202/An_Improved_Bytewise_Approximate_Matching_Algorith.pdf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691566749845919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d3067cf349b37a0</li>
        <li>Upwork Job ID: 1689730232530489344</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by situchan** [comment]
WIP: https://github.com/Expensify/App/pull/24308
@rezkiy37 when will it be ready for review?

**Comment by rezkiy37** [comment]
> WIP: #24308 @rezkiy37 when will it be ready for review?

Today.

**Comment by joekaufmanexpensify** [comment]
The fix is out on staging, so this no longer needs to be an hourly.

**Comment by joekaufmanexpensify** [comment]
Removed deploy blocker label, as this is out on staging now, so is all set. All we need to do here is pay the reporting bonus once this is out on prod!

**Comment by joekaufmanexpensify** [comment]
@gadhiyamanan offer sent for $250!

**Comment by gadhiyamanan** [comment]
@joekaufmanexpensify offer accepted, thanks!

**Comment by joekaufmanexpensify** [comment]
Great, ty! PR was deployed to prod on 2023-08-10, so we'll issue payment on 2023-08-17.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here!

**Comment by joekaufmanexpensify** [comment]
@gadhiyamanan $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job removed.

**Comment by joekaufmanexpensify** [comment]
This was a regression fix, so no other payment required.

**Comment by joekaufmanexpensify** [comment]
Regression is fixed, and regression reporting bonus paid. Closing as this is all set!
