### ISSUE TITLE
 In workspace, user add/remove comment is cropped

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign with account A and go to Settings -> Profile -> Display name.
2. Update first name as ">>First" and last name as "<<Last".
3. Save display name.
4. Sign with account B in another browser and go to Settings -> Workspace -> Members.
5. Click invite button and search account A with email address.
6. Invite account A and check the add comment in workspace page.
Expected Result: The full message should be displayed in grey color.
added >>First <<Last ([akamefi202+test1@gmail.com](mailto:akamefi202+test1@gmail.com)) as a user
Actual Result: The cutted message is displayed in white color.
added >>First <

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Untitled](https://github.com/Expensify/App/assets/43996225/b60e81f6-000e-4b98-96fc-7d33ae580e3a)
![Snip - (75) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/94b20ee3-2b83-4277-a1f4-6d0478757fcd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @akamefi202
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690919324047889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Is there a valid case for having `>>` and `<<` in a display name? I can't think of one, and this doesn't seem like a bug that a real-world user will ever face.

If that's incorrect, then let's reopen, but I think we should not fix this at the moment.

**Comment by akamefi202** [comment]
In that case, I think inputting escape characters in display name should be disabled.
For example, if we input '<' character in first name textfield, invalid error should be shown.
