### ISSUE TITLE
[$1000] Login - Cursor goes beyond text field boundary when moving it to the right

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the staging web link
2. Type a long email in the email/phone text field
3. Put the cursor at the middle of the email, and keep dragging it to the right side

## Expected Result:
Cursor should stop at the last character of the email and does not go beyond the text field boundary

## Actual Result:
Cursor goes beyond the text field boundary

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6159093_Screen_Shot_2023-08-09_at_7 10 53_PM](https://github.com/Expensify/App/assets/78819774/1432e98d-2f0a-417e-b231-40111b7dd792)

https://github.com/Expensify/App/assets/78819774/921e99b0-9a77-46ad-961a-38015353a003

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c0258671b32a9a1</li>
        <li>Upwork Job ID: 1691877140339490816</li>
        <li>Last Price Increase: 2023-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26182824</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
missed adding the external label but this is reproducible and should be fixed

**Comment by narefyev91** [comment]
Proposal from @bernhardoj looks good to https://github.com/Expensify/App/issues/24328#issuecomment-1672797300
Let's also double check that we will not have any scrolling issue on the small screens - when keyboard will be shown for type email
🎀 👀 🎀 C+ reviewed

**Comment by adelekennedy** [comment]
It definitely is! The title just didn't update


<img width="838" alt="Screenshot 2023-09-19 at 11 45 42 AM" src="https://github.com/Expensify/App/assets/60450566/f5378bb1-d99e-4e74-873b-089871e1038d">

**Comment by adelekennedy** [comment]
### Payouts due:

Issue Reporter: N/A
Contributor: $1000 @bernhardoj Upwork
Contributor+: NA @fedirjh 

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/jobs/~017c0258671b32a9a1).
