### ISSUE TITLE
Request money - When switching between manual input and distance, the scan option flashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click on the FAB button -> Request money
4. Click on the manual option then the Distance option

## Expected Result:
When switching between manual input and distance, the scan option doesn't flashes

## Actual Result:
When switching between manual input and distance, the scan option flashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Bug6159149_Recording__5790__1_.mp4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
A distance request is new functionality added in https://github.com/Expensify/App/pull/23048. I think we'd likely prefer to handle this as follow-up polish instead of reverting the PR, but @neil-marcellini is probably better suited to make that call!

**Comment by neil-marcellini** [comment]
This is behind a very limited beta, and a minor glitch, so I would say it's not a blocker.

**Comment by neil-marcellini** [comment]
If this is what you're talking about I wouldn't call that a bug, it seems like that's how tabs work, because we're swiping across to the distance tab. @lanitochka17 please re-open if you're talking about something different than this or if you have a reason why that's unacceptable.

https://github.com/Expensify/App/assets/26260477/6a2d227a-fd95-44a6-910e-3cf87c6f08ba
