### ISSUE TITLE
Composer is highlighted on first-time sign-up with a magic link

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-up page
2. Enter an email address you have never signed-up with before
3. Click on continue
4. Copy sign in magic link & past it into a new tab
5. Prefix the link with localhost to point to dev environment
6. Press enter

## Expected Result:
Composer shouldn't be highlighted

## Actual Result:
Composer is highlighted

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/27c53aeb-0edc-4b2b-ac2d-0a828c93fbda

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690990538566899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment]
Now that popover layout without an overlay feature is introduced on this [pr]( https://github.com/Expensify/App/pull/19011), I think this is expected behaviour

**Comment by kadiealexander** [comment]
Composer should always be highlighted when you open a chat link in any environment, IMO! Closing as expected behaviour.
