### ISSUE TITLE
BA - iOS App crashes if user tap ‘Back’ on the Onfido start screen Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start iOS App
2. Login with Expensifail account
3. Go to existing or create new workspace
4. Go to Workspace > Connect bank account
5. Follow the flow for adding a VBA using the credentials [Company - Expensify, First name - First, Last name - Last] until you reach the Onfido screen
7. Onfido first screen loads
6. Go OFFline
7. Go next screen
8. User can’t go next from this 2nd screen offline
8. Tap 'Back' 2 times while staying offline

## Expected Result:
User should return to the Personal Information page

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b65b7609-5841-4ce4-ba74-5bbeed4f71a9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
@lanitochka17 I see that you're able to reproduce it on iOS. Have you tried the same flow on other platforms and it's working on those platforms? Also, is this a brand new crash that hasn't been on previous versions of the app?

**Comment by lanitochka17** [comment]
Issue reproducible in only IOS

**Comment by situchan** [comment]
root cause: https://github.com/Expensify/App/pull/23864/files#r1289249208
I suggest to revert https://github.com/Expensify/App/pull/23864

**Comment by tgolen** [comment]
@situchan Thank you for finding that! I agree, let's revert and have the code resubmitted with proper cross-platform support. Can you please take care of doing the revert?

**Comment by situchan** [comment]
> @situchan Thank you for finding that! I agree, let's revert and have the code resubmitted with proper cross-platform support. Can you please take care of doing the revert?

Sure I can do that

**Comment by situchan** [comment]
@tgolen [PR](https://github.com/Expensify/App/pull/24373) is ready

**Comment by tgolen** [comment]
Verified that the flow works now without crashing.

**Comment by situchan** [comment]
@tgolen am I eligible for payment here? As I found the root cause and raised PR for fix and merged.

**Comment by tgolen** [comment]
Yes, you are. I'm not exactly sure what the process is in this case. I have never handled the payment side of things. @dylanexpensify do you know how to handle it in this case?

**Comment by dylanexpensify** [comment]
Ah yeah, @situchan are you paid in NewDot? @tgolen would we be paying flat $1000 here?

**Comment by situchan** [comment]
I am using upwork. As I am the PR author, I'd say this is worked externally so no "flat" concept. Also, I am not sure if this  applies timeline rule.

**Comment by dylanexpensify** [comment]
Ah perfect, yes timeline applies and you hit it! Nice one! Please apply [here](https://www.upwork.com/jobs/~01bcf7d388dc265fcb)!

**Comment by krkrishnaraj11** [comment]
I have recreated the error issue in ios. 
There is an issue error "document" doesn't exist.
Mostly due to api response and no network state

Need to console and find the error

**Comment by krkrishnaraj11** [comment]
I have recreated the error issue in ios. 
There is an issue error "document" doesn't exist.
Mostly due to api response and no network state

Need to console and find the error

Contributor details
Your Expensify account email: krkrishnaraj11@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01bc44c7d52ff7f012

**Comment by dylanexpensify** [comment]
@situchan bump on applying!

**Comment by dylanexpensify** [comment]
Not a problem!

**Comment by dylanexpensify** [comment]
Sent!

**Comment by dylanexpensify** [comment]
offer sent!

**Comment by dylanexpensify** [comment]
payment sent! Thanks again @situchan!
