### ISSUE TITLE
Assign Task- When user tap share somewhere, all activities with last message are shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Fab plus button
3. Tap assign task
4. Enter any title and description
5. Tap next
6. T ap "assignee" To assign yourself
7. Tap Share somewhere

## Expected Result:
When user tap share somewhere, he must be shown user name plus email id

## Actual Result:
When user tap share somewhere, all activities with last message are shown instead of user name plus email id

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7086cd30-df58-4b26-a210-69ec7d4774bc

https://github.com/Expensify/App/assets/78819774/ce5d1bbd-061a-48a6-889c-de09da9a4c23

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
This looks expected from this PR we just merged https://github.com/Expensify/App/pull/24019

**Comment by NikkiWines** [comment]
Cool, sounds like this isn't an issue then - closing
