### ISSUE TITLE
Web - User still can go to setting of archived room through welcome text, even other places it was disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Delete that workspace
3. Go to #admin or #announce of that archived workspace.
4. Notice that you can't open detail page by clicking header or workspace avatar but you still can click on #admin or #announce text at the welcome message to open detail page.

## Expected Result:
User shouldn't be blocked from clicking welcome text.

## Actual Result:
User still can go to setting of archived room through welcome text, even other places it was disabled.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/38cdb07b-4dc7-4e99-955a-31c5be398c35

https://github.com/Expensify/App/assets/115492554/39a5a344-f9b6-4571-bff3-fef9860458c0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691032578949149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Closing as this is fixed!
