### ISSUE TITLE
IOU - Comment in IOU report preview does not update after deleting money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23043
## Action Performed:
1. Go to staging.new.expensify.com
2. Request money two times from a user with no conversation history
3. Click on the IOU report preview
4. Delete one of the requests
5. Return to IOU report preview

## Expected Result:
The comment in IOU report preview will update

## Actual Result:
The comment in IOU report preview updates and reverts to '2 requests'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d88723e84c14ed1f</li>
        <li>Upwork Job ID: 1689633879427391488</li>
        <li>Last Price Increase: 2023-08-10</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Not a blocker, this is just a follow-up issue to Manual Requests that we need to implement.

**Comment by joekaufmanexpensify** [comment]
@Julesssss If this is a follow up to manual requests, should it have new feature label, rather than bug?

**Comment by Nathan-Mulugeta** [comment]
Hey guys, I reported this issue over on slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1691577864577929).

**Comment by Julesssss** [comment]
I updated the reporter section

**Comment by Nathan-Mulugeta** [comment]
Thanks Jules.

**Comment by mvtglobally** [comment]
Potentially related to https://github.com/Expensify/App/issues/24241

**Comment by joekaufmanexpensify** [comment]
Interesting. @Julesssss / @narefyev91 curious if you think the above bug is related to this one?

**Comment by narefyev91** [comment]
@joekaufmanexpensify seems that it's a separate issue - changes for https://github.com/Expensify/App/issues/24241 was deployed on staging in version 🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5801159442) to staging by https://github.com/srikarparsi in version: 1.3.51-2 🚀 - but issue reported in staging Version Number: 1.3.52.1

**Comment by joekaufmanexpensify** [comment]
Sounds good, thanks for confirming. @Julesssss just for my own understanding, this is one you're intending to work on, right? So we don't need to look for external volunteers?

**Comment by Julesssss** [comment]
I updated the reporter, as it was reported 5 days before the listed report.

**Comment by Julesssss** [comment]
@joekaufmanexpensify, good question. This might need both a backend and front end fix, so yeah lets keep internal for the moment.

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by joekaufmanexpensify** [comment]
@Julesssss curious if you have an estimate of when a PR might be up here?

**Comment by Julesssss** [comment]
@joekaufmanexpensify this is weeks or months away. As I have so many bugs and more important tasks assigned.

**Comment by joekaufmanexpensify** [comment]
Moving back to weekly, as doesn't sound like @Julesssss can prioritize this atm.

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Same.

**Comment by joekaufmanexpensify** [comment]
Pending internal prioritization

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
@Julesssss do you think you'll be able to raise the fix for this one anytime soon?

**Comment by joekaufmanexpensify** [comment]
Okay, all good. I will make it a monthly for now then!

**Comment by Julesssss** [comment]
Hey @joekaufmanexpensify, I just retested this bug and I don't think it is occurring anymore 🎉 

I see an updated preview. Would you mind verifying?

![Screenshot 2023-11-17 at 16 33 13](https://github.com/Expensify/App/assets/10736861/fe437e6a-ab97-4472-96a3-f785d5ae3a49)
![Screenshot 2023-11-17 at 16 33 01](https://github.com/Expensify/App/assets/10736861/4b2703b1-6886-42b3-9d8b-3fcc73ca214c)

**Comment by joekaufmanexpensify** [comment]
Sure, I'll take a look now!

**Comment by joekaufmanexpensify** [comment]
Yep, this is fixed for me as well. Closing as no action needed in this issue!

**Comment by tewodrosGirmaA** [comment]
Hey @Julesssss and @joekaufmanexpensify, am I eligible for payment?

**Comment by joekaufmanexpensify** [comment]
@tewodrosGirmaA My initial thought is I don't think any payment is due here. We did not fix anything in this issue. Generally the way we approach situations like this is you'd need to find the PR that fixed this to show that your report came first in order for this to qualify for payment. 

If this was reported before whatever caused us to change this product behavior, LMK and I'll take another look!
