### ISSUE TITLE
Request Money - First currency in the list goes blank when currency list is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Tap + > Request money
3. Tap on the currency
4. Select TWD - NT$ as currency
5. Tap on the currency again

## Expected Result:
The currency list will not turn blank

## Actual Result:
The first currency on the list when user opens the currency list turns blank for a moment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1b6e8463-4471-457b-baad-95a642d09f92

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I ran out of time to test this one yesterday but will review it on Monday.

**Comment by alexpensify** [comment]
Tomorrow, I will test more.

**Comment by alexpensify** [comment]
Closing - I tested this experience on my Android device and am unable to replicate it. Please comment if you disagree.
