### ISSUE TITLE
Web - Request money - Unable to delete request money when two users request equal amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed in
2. Request money from user B: an amount of 10 $
3. Open a tab where user B is signed in
4. Request money from user A: an amount of 10 $
5. Click on the IOU preview component
6. Hover over the IOU preview component from user B
7. Click on 'Delete' icon

## Expected Result:
IOU should be deleted

## Actual Result:
System throws an error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f30a34fb-cb0b-427b-8b80-10264d87934e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690991370654309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lukemorawski** [comment]
Hi it's Lucas from Callstack. Happy to take a look at his issue

**Comment by RolandTeslaru** [comment]
Hi! I would like to work on this issue.

**Comment by conorpendergrast** [comment]
Oh wow, sorry, I totally missed this one! 

I've tried reproducing with my test accounts 20303b@conorpendergrast.com and conor+24537aa@conorpendergrast.com, and haven't been able to reproduce (I was able to delete the request from step 4 without issue)

@Natnael-Guchima could you revise the reproduction steps to check what I may be missing here?

**Comment by Natnael-Guchima** [comment]
@conorpendergrast I am able to reproduce the issue following the steps above. Can you please share a video trying to reproduce the issue? I can check if there is a difference in the reproduction step we are following. Thanks. 


https://github.com/Expensify/App/assets/57330233/766b8fcd-c92a-4d39-bbec-aeb77d8298f9

**Comment by Natnael-Guchima** [comment]
I am able to reproduce it on the latest release
