### ISSUE TITLE
[HOLD for payment 2023-09-06] [$500]  Inconsistent bottom space between Workspace page and other pages.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with new account (that doesn't have any workspace), observe the bottom space.
2. Go to another page that has button at the bottom (ie: Close Account, Two-factor authentication), observe the bottom space.
## Expected Result: 
Bottom space should be consistent between page.
## Actual Result: 
Inconsistent bottom space between Workspace page and other pages.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2958836c-4dc6-445e-94ad-a6b191f80143

https://github.com/Expensify/App/assets/43996225/25a63c09-21e4-48e8-ad81-f96662526554

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691037065213639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7c83d3a363be677</li>
        <li>Upwork Job ID: 1691177407629623296</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 26244791</li>
<li>hungvu193 | Reporter | 26244794</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
I don't understand the issue, I asked in the Slack thread for clarification.

**Comment by sakluger** [comment]
We discussed in Slack and I understand now - The `Close Account` and `Next` button are at a consistent height from the bottom, while `New Workspace` is a bit lower down on the screen.

We are still discussing in Slack whether it makes sense to fix this now as a one-off issue.

**Comment by roryabraham** [comment]
As discussed in slack, making this external

**Comment by sakluger** [comment]
This is a pretty minor change, I'm changing the price to $500.

**Comment by sakluger** [comment]
Assigned @ahmedGaber93 - please let us know when your PR is ready for review, thanks!

**Comment by ahmedGaber93** [comment]
@0xmiroslav [PR](https://github.com/Expensify/App/pull/25654) is ready for review.

**Comment by sakluger** [comment]
I went ahead and paid out the reporter bounty to @hungvu193

@0xmiroslav could you please complete the BZ checklist before tomorrow? That way we can approve your manual payment right away after the 7-day hold.

**Comment by sakluger** [comment]
Paid @ahmedGaber93 via Upwork.

We're just waiting on the BZ checklist now.

**Comment by sakluger** [comment]
Okay sounds good @0xmiroslav. Would you like me to leave this issue open, or will you handle payment directly via NewDot?

**Comment by sakluger** [comment]
@0xmiroslav what's the status for this one? I don't want to leave it open indefinitely, could you record that you need to request payment so I can close it?

**Comment by sakluger** [comment]
No worries, and thanks for confirming!
