### ISSUE TITLE
Web - Bank account - Label of checkbox should not be highlighted as it doesn't let get the checkbox be checked in one clicking

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on Settings > Workspaces > any workspace > Bank account > Connect manually
3. Reach 2nd or 3rd step and click on checkbox's label at least 4 5 times. You can see here that Label of checkbox is highlighted and it doesn't let get the checkbox be checked in one clicking

## Expected Result:
Label of checkbox should not be highlighted as it doesn't let get the checkbox be checked in one clicking

## Actual Result:
Label of checkbox is highlighted and it doesn't let get the checkbox be checked in one clicking

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bd59f076-214a-434f-aa08-7230d4150c67

https://github.com/Expensify/App/assets/115492554/4b9a8acc-c672-4810-8a34-ae64aedc9194

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691125251472969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
potentially related to https://github.com/Expensify/App/issues/22526

**Comment by MahmudjonToraqulov** [comment]
@mvtglobally I think https://github.com/Expensify/App/issues/22526 is completely different. There the issue was about flickering text. In here the issue is about beeing highlighted.

**Comment by tjferriss** [comment]
I'm not able to reproduce and I don't really see a bug here. When I click on the text it checks the box as expected. When I click the text again it unchecks the box. I tested on both the second and third step in the process.
