### ISSUE TITLE
DEV: scan text and icon is not horizontally center

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on FAB icon and select request money option
2. click on scan option
## Expected Result: 
scan text should be horizontally center
## Actual Result: 
scan text does not horizontally center

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ffbaa76e-6b4f-447e-bc38-afadb2e2fb8b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691061630662029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3d85ecd911adee5</li>
        <li>Upwork Job ID: 1694035244967559168</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Didn't get an update today, will on Monday!

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Heyyo @srikarparsi!! Would you mind testing this DEV report to confirm it's a bug for me? 🙇‍♂️

**Comment by srikarparsi** [comment]
Hey @dylanexpensify! Yes, I can confirm that this is a bug. But I can take this internally since it seems pretty straightforward!

**Comment by dylanexpensify** [comment]
my hero!

**Comment by Santhosh-Sellavel** [comment]
@dylanexpensify or @aldo-expensify Assign me here for review thanks!

**Comment by dylanexpensify** [comment]
@Santhosh-Sellavel mind giving an update today? 🙇‍♂️

**Comment by Santhosh-Sellavel** [comment]
@dylanexpensify Please update the labels here, PR is deployed to production yesterday check [here](https://github.com/Expensify/App/pull/24587#issuecomment-1690922017)

**Comment by aldo-expensify** [comment]
Not sure if I updated that correctly 🥲

**Comment by srikarparsi** [comment]
Hey! yeah, @dylanexpensify, I believe we need to pay @Santhosh-Sellavel $1,000 for reviewing the PR and we should be good to close out this issue.

**Comment by Santhosh-Sellavel** [comment]
bump @dylanexpensify!

**Comment by Santhosh-Sellavel** [comment]
> bump @dylanexpensify!
> 
> Can you update issue title and leave a payment summary message thanks!

cc: @Expensify/bug-zero Can anyone help me here?

**Comment by mallenexpensify** [comment]
@Santhosh-Sellavel sorry for the delay, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01d3d85ecd911adee5

The `Reviewing` label keeps issues from going overdue so they can get missed.  @dylanexpensify , please finish this one up once @Santhosh-Sellavel has excepted the offer.

**Comment by gadhiyamanan** [comment]
@mallenexpensify can you help me with reporting bonus?

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @Santhosh-Sellavel $1,000
- Reporter: @gadhiyamanan $250

[Upwork Job](https://www.upwork.com/jobs/~01d3d85ecd911adee5)! Please apply!

**Comment by gadhiyamanan** [comment]
@dylanexpensify applied, thanks!

**Comment by Santhosh-Sellavel** [comment]
Will collect on ND

**Comment by dylanexpensify** [comment]
Payment sent @Santhosh-Sellavel and offer sent @gadhiyamanan!

**Comment by gadhiyamanan** [comment]
@dylanexpensify offer accepted, thanks!

**Comment by dylanexpensify** [comment]
done!
