### ISSUE TITLE
Reopening Task Causes Notification Position Swap

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign and choose "Assign Task"
2. Fill in the title, description, assignee, and location
3. Check the checkbox to mark the task as complete
4. Check the checkbox again and observe that the reopen and complete notifications swap positions briefly, with the reopen notification appearing before the completion notification before returning to its original position.
## Expected Result: 
When reopening a task, the reopen notification should not appear before the completion notification, even briefly.
## Actual Result: 
When reopening a task, the reopen notification briefly appears before the completion notification, which is not in the correct order.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1708e0ce-965a-4531-b86d-3956fcaffa37

**Expensify/Expensify Issue URL:**
**Issue reported by:** @TewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691046827248809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment]
Hi

**Comment by DanutGavrus** [comment]
hi

**Comment by DanutGavrus** [comment]
Hi

**Comment by fwx5618177** [comment]
It looks like delay rendering, please let me solve it if possible.

**Comment by fwx5618177** [comment]
> 📣 @fwx5618177! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```



Contributor details
Your Expensify account email: fwx5618177@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018360a108381c1854

**Comment by StevenKKC** [comment]
I can't reproduce this issue.

**Comment by zanyrenney** [comment]
I cannot reproduce this issue.

**Comment by tewodrosGirmaA** [comment]
@zanyrenney now it works properly , when I check now
