### ISSUE TITLE
There is flickering when opening and clicking out of the box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24401]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and any chat
2. Hover over any message and right click the mouse to open reaction box of it
3. Click out of the box and you can see flickering for a short time
## Expected Result: 
There shouldn't be any flickering when opening and clicking out of the box
## Actual Result: 
There is flickering when opening and clicking out of the box
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction (not able to reproduce by applause)
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (81) (1).webm](https://github.com/Expensify/App/assets/43996225/c290db24-dd23-442c-b853-3c35a6715ed1)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691060078469149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
I cannot reproduce this reliably at all. This also doesn't impact a user _at all_. I'm going to say this is not a bug.

https://github.com/Expensify/App/assets/9133401/2a59ecca-b7dd-4f91-87d5-84e92f75a370
