### ISSUE TITLE
[$1000]  latest message does not update in LHN after paid request money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat and click on + icon
2. from userA request money to userB
3. from userB click on pay elsewhere button to paid
4. from userB, go to other report screen
5. from userA send a message to userB
## Expected Result: 
new message should be show in LHN
## Actual Result: 
new message does not show in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c8e86b46-677d-4178-82f3-0876685a03e3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691058665029519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b830a6982d42433c</li>
        <li>Upwork Job ID: 1691851904603095040</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by ShogunFire** [comment]
I think it's back end, this is the only pusher event I see, I don't think this is enough: 
![image](https://github.com/Expensify/App/assets/19537677/f9dad8af-113a-4c56-a2e8-2f24f6c11145)

**Comment by anmurali** [comment]
Reproduced on mac- Chrome

**Comment by ShogunFire** [comment]
This was reproductible yesterday...
