### ISSUE TITLE
Status - Two "Save" buttons, making one redundant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into an expensifail account
3. Go to settings > Profile > Status
4. Click on Status > change the status and add an emoji > Click Save > Click Back

## Expected Result:
User expects that if the "save" button is tapped, then the status will save automatically the first time around

## Actual Result:
After hitting the save button for the first time then tapping back, the status is not saved. It is necessary to hit the "Save" button twice in a row for the status to be changed successfully

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/63be9076-6a0d-45b9-b4b4-5711360a89d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
Removing the deploy blocker label per https://expensify.slack.com/archives/C049HHMV9SM/p1691610130667239

**Comment by Li357** [comment]
Closing for now as well as the feature is behind beta.
