### ISSUE TITLE
Web - Request money - Delete request reopens on deleting message in it and again deleting it triggers red dot error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on request money
3. Enter any amount, select any user and complete the request
4. In the user report, click on request money message
5. Again click on request money message and send any message in the report
6. Click on 3 dot and click on delete request, it should display [deleted request] in header after it
7. Delete the message sent in step 5 and observe that request again gets reverted to active.
8. Again click on 3 dots and delete request, observe that it triggers red dot error in its parent thread

## Expected Result:
App should not activate deleted request on deleting any message inside deleted request

## Actual Result:
App activates deleted request on deleting any message inside deleted request and on again trying to delete, triggers red dot error in parent thread

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y 

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a00b5bd4-77ab-44a7-9063-936a4939069c

https://github.com/Expensify/App/assets/115492554/2bf1cc6b-06f9-4209-ab60-b7aa2ace6d32

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691058072347819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Handling after higher priorities

**Comment by muttmuure** [comment]
Will handle this week

**Comment by muttmuure** [comment]
Having trouble getting into expensifail.com 
<img width="324" alt="image" src="https://github.com/Expensify/App/assets/46995600/45713cb7-827c-4eea-ade0-d05e7b5e3cdd">

**Comment by muttmuure** [comment]
I tried this and it looks like we fixed it somewhere else. The request got zeroed out: 
<img width="1140" alt="image" src="https://github.com/Expensify/App/assets/46995600/b1a9aacc-bbc2-49f2-aab9-a3b21ef3fd2b">
