### ISSUE TITLE
[Awaiting C+ payment] [$1000] [HOLD for payment 2023-09-07] Fix the app launcher icon padding for the alternative flavours

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#24429]
### Problem

The alternative app icon padding doesn't match the production app:

![Screenshot 2023-08-11 at 15 37 46](https://github.com/Expensify/App/assets/10736861/b9656e2d-0b5e-441d-99f1-de5a927576bd)

### Solution

Reimport them with Android Studio using the correct padding. Similar for iOS but I might need to do it manually
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017188538726e905ba</li>
        <li>Upwork Job ID: 1690012465891250176</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Still in progress, I need to fix iOS. Will let you know when it's ready!

**Comment by Julesssss** [comment]
Hey @shawnborton, or maybe @dannymcclain?

![260039345-b9656e2d-0b5e-441d-99f1-de5a927576bd](https://github.com/Expensify/App/assets/10736861/e97324aa-0c0e-4964-b39d-80476d0c3503)

I have fixed the Android icon padding, but need help to create the iOS launcher icons without the excess padding. I created [this Figma file](https://www.figma.com/file/nqa2OvmvFcht5gh6jl4MQY/iOS-Icons-for-AdHoc%2FDev-builds?type=design&node-id=0%3A1&mode=design&t=329q9yz2Vo9oNOat-1) with annotations. 

All I need is copies of the 'GOOD' icons, but with the correct icon padding -- if that makes sense.

**Comment by Julesssss** [comment]
Thanks! I just added the Android icons and [added](https://www.figma.com/file/nqa2OvmvFcht5gh6jl4MQY/App-launcher-icons?type=design&node-id=0%3A1&mode=design&t=oSyUBGwjJjkfezDw-1) it to the NewDot folder under the new name: 'App launcher icons'

**Comment by Julesssss** [comment]
I generated some extra sizes as we weren't previously using the correct size for notifications, settings, ect.

**Comment by Julesssss** [comment]
[PR in review](https://github.com/Expensify/App/pull/24440)

**Comment by Julesssss** [comment]
Hey @trjExpensify (come to Bali!),

This wasn't a regression. I raised the issue and implemented the change. So I believe just @allroundexperts needs payment here (for PR review)

**Comment by Julesssss** [comment]
Also I believe the old bounty of $1000 should apply, as this was merged prior to the announcement.

**Comment by trjExpensify** [comment]
>Hey @trjExpensify (come to Bali!),

Lol, see you on Sunday! 😅 

>So I believe just @allroundexperts needs payment here (for PR review)

Perfect. So confirming payment due as $1,000 for the internal PR review at the old rates due to the issue being created before the announcement. 

@allroundexperts go ahead and request payment for it!

**Comment by trjExpensify** [comment]
Perfect, closing!

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/24429#issuecomment-1713714926).
