### ISSUE TITLE
Status - Status reverts to previous status or turns blank when going offline after saving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Set different status and erase it before running the steps

1. Launch New Expensify app
2. Go to Settings > Profile > Status
3. Add a status and save it
4. Immediately go offline

## Expected Result:
When going offline, the status remains as is

## Actual Result:
When going offline, the status either reverts to a previous status (precondition) or it becomes blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/718ee401-e575-4854-bbd1-60f608b851dc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
@lanitochka17 I don't think that's the correct video, could you check?

**Comment by amyevans** [comment]
Yeah the attached video isn't correct but I reproed with the test steps. But as @0xmiroslav pointed out (thanks!) this is a feature under active development so we won't consider them blockers. Assigning over to @stitesExpensify to handle in the context of that project!

**Comment by stitesExpensify** [comment]
Thanks @0xmiroslav @amyevans !

**Comment by perunt** [comment]
Just to be sure that you pressed save button on the Status screen(with money stack logo) as well as on StatusSetPage (where you check emoji with text)
I can't reproduce it
Could you update the video?

**Comment by lanitochka17** [comment]
Sorry for the confusion. Correct video

https://github.com/Expensify/App/assets/78819774/e14b365a-3c69-4ce3-87d3-6bf8bc8751bb

**Comment by stitesExpensify** [comment]
Are you still able to reproduce this @lanitochka17 ?

**Comment by lanitochka17** [comment]
Issue is reproducible with new Build 1.3.57-2
Detailed steps for reproduction:
1. Launch New Expensify app
2. Go to Settings > Profile > Status
3. Add a status and save it
4. Immediately go offline
5. Go to Contact methods
6. Return to previous page
7. Note that the status reverts to previous one or it goes blank

https://github.com/Expensify/App/assets/78819774/f1b09550-4b3b-4945-95bf-3d7da1112c4f

**Comment by perunt** [comment]
I'm not being able to reproduce it yet. I've tried CPU and network throttling as well. Is it reproducible each time?
Let me try to do it from the main

https://github.com/Expensify/App/assets/48593211/120e2201-efd7-406e-a2c4-9cfcde9b55be

**Comment by stitesExpensify** [comment]
Since @perunt can't reproduce I'm going to close

**Comment by stitesExpensify** [comment]
Assigned Taras since this is still reproducible

**Comment by stitesExpensify** [comment]
Any updates here?

**Comment by stitesExpensify** [comment]
bump @lanitochka17

**Comment by lanitochka17** [comment]
@perunt Hello. most likely the issue was reproduced with low Internet traffic
Issue is not reproducible on build 1.3.95-5

https://github.com/Expensify/App/assets/78819774/523b1430-e013-429b-b53e-f93e0fd5aacd

**Comment by perunt** [comment]
From what I saw, there is a problem with the queue. Also, I remember recently that the queue was changed a bit. So, it's probably related.
Do I get you right? Is it no more reproducible in newer builds?

**Comment by stitesExpensify** [comment]
bump @lanitochka17

**Comment by stitesExpensify** [comment]
Closing this for now since we haven't heard anything for a while
