### ISSUE TITLE
[$1000] Dev: console error on creating new chat or any report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24432]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on fab icon
2. Select new chat
3. Enter any new id which you haven't chat yet
4. Check inspect element and observe the console error
## Expected Result: 
Should not be any console error
## Actual Result: 
Gives error for createChat type pendingFields.createChat` of type `string` supplied to `ReportScreenWrapper`, expected an object.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a3ac2853-1424-4ef2-95bd-41133bd3ee6a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691084126708399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6ee569e662cf652</li>
        <li>Upwork Job ID: 1695192549067206656</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
I have raised it as a regression [here](https://github.com/Expensify/App/issues/23200#issuecomment-1664379718), and now it is fixed. I think I am eligible for reporting bonus.

**Comment by johncschuster** [comment]
Thanks for the heads up, @Pujan92! I'll get that taken care of.

**Comment by johncschuster** [comment]
Sorry for the ping, @cubuspl42. I made this External to create the Upwork job to pay the bug reporter.

**Comment by johncschuster** [comment]
@Pujan92 I've invited you to the job on Upwork. Can you please ping me when you've accepted that so I can issue payment? Thank you!

**Comment by Pujan92** [comment]
@johncschuster accepted, thanks!

**Comment by johncschuster** [comment]
Payment has been issued! Thanks for reporting the bug, @Pujan92!
