### ISSUE TITLE
IOU - Typed/deleted letters not shown instantly, there is a lag upto tapping "Request"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap Request money
4. Enter amount
5. Tap next
6. In cash header page, type a word and search for the user
7. Tap cross button and delete searched user
8. Select a user
9. Tap Request button

## Expected Result:
Without time lag, entering and deleting in keypad must instantly sync with the field above entered/deleted.Similarly, on tapping "request" button without time lag, user must be directed to conversation page

## Actual Result:
From searching a user/ deleting the searched name entered using cross button and on tapping "request" button, all functions with little time lag
After user entered user name, slowly only "name" displaying in the "name/email/phone number" field. Similarly, by pressing cross button in keypad, if we delete the searched user also, slowly only each letter deleted, and not sync with speed of letter deleted in keypad and even while typing also
Tapping "request" button, user is not instantly navigated to conversation page, he is directed only after a little lag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4ede7cc0-4f4e-4ff6-85a7-e7990b894e74

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
I am not able to recreate this, @lanitochka17 are you still able to?

**Comment by lanitochka17** [comment]
Issue is not reproducible with build 1.3.53-1
Samsung Galaxy A50/Chrome


https://github.com/Expensify/App/assets/78819774/92b1f78b-6a02-42ff-ac8e-97a29d577351

**Comment by slafortune** [comment]
Thanks @lanitochka17
