### ISSUE TITLE
[HOLD for payment 2023-10-10] [$1000] Web - Chat - Deleted message can be undo when in editing mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat and send a message A
2. Reply that message in a new thread
3. In the thread, edit that message but do not save it
4. Back to the main chat, delete that message
5. Go to the thread again, note that the message still in editing mode, and if we save that message, we can undo the delete action

## Expected Result:
The message should be deleted even in editing mode ( This is how chat in slack works )

## Actual Result:
The message is not deleted and can be undo

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2cff4d46-c897-43eb-843d-95166f7a9e10

https://github.com/Expensify/App/assets/115492554/08c089a3-714e-44b5-8c05-ce7f613977af

**Expensify/Expensify Issue URL:**

**Issue reported by:** @RickyMasha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691080441938489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad60e1290e36e223</li>
        <li>Upwork Job ID: 1690997103080361984</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26238747</li>
<li>namhihi237 | Contributor | 26238751</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted message can be undo when in editing mode

### What is the root cause of that problem?
We don't delete draft message on ONYX when delete the message

### What changes do you think we should make in order to solve the problem?
when deleting the message, we should add the condition to check if it is the parent message or it is the first message in child report
1. If it is the parent message we should remove the draft message of the first message in child report
2. If it is the first message in child report we should remove the draft message of the parent message in child report

Like this:
```
    if (report.parentReportActionID && lodashGet(reportAction, 'childType', '') === CONST.REPORT.TYPE.CHAT) {
        saveReportActionDraft(report.parentReportID, reportAction.reportActionID, '');
    }
    if (reportAction.childReportID) {
        saveReportActionDraft(reportAction.childReportID, reportAction.reportActionID, '');
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment]
@fedirjh any updates?

**Comment by RickyMasha** [comment]
Contributor details
Your Expensify account email: masharick2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a65378de646b8670

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @RickyMasha 
Contributor: $1000 @namhihi237
Contributor+: $1000 @fedirjh

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~014a63052d4722b668).

**Comment by kadiealexander** [comment]
@RickyMasha please apply here - https://www.upwork.com/jobs/~014a63052d4722b668
@fedirjh please complete the checklist and accept the contract I sent over
@namhihi237 please accept the contract I sent over

**Comment by RickyMasha** [comment]
@kadiealexander Sorry for the inconvenience, but all i have to do is clicking the `apply now` button or I have to do anything else
Thanks for your patience

**Comment by kadiealexander** [comment]
Just clicking "apply now" is fine :)

**Comment by RickyMasha** [comment]
@kadiealexander Thanks, applied

**Comment by kadiealexander** [comment]
@RickyMasha I haven't received your proposal in Upworks, please take a look and apply again here https://www.upwork.com/jobs/~014a63052d4722b668

**Comment by RickyMasha** [comment]
@kadiealexander I just submitted the proposal for reporting this bug. Thank for your time

**Comment by kadiealexander** [comment]
@RickyMasha Sent you an offer :)
