### ISSUE TITLE
Duplicate "Beginning of New Chat" Message and Email in LHN when Changing Assignee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign and select "Assign Task"
2. Fill in the title, description, and assignee, and share somewhere
3. Click on the assignee and change it to a new email that has not been used before
4. Observe that the "Beginning of New Chat" message and email appear twice in LHN.
## Expected Result:
 The "Beginning of New Chat" message and email should only appear once in LHN when changing the assignee with a new email.
## Actual Result: 
When changing the assignee to a new email, the "Beginning of New Chat" message and email appear twice in LHN, causing duplication.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/de928642-6829-4380-a250-3692ff4851f3

https://github.com/Expensify/App/assets/43996225/a75bdece-30ab-47b4-acba-45e38f0c578d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691065190422649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
This seems to be expected behaviour.

**Comment by muttmuure** [comment]
I only received one "Beginning of New Chat" message. Can you send a screenshot of the duplicate report so I am on the same page?

**Comment by muttmuure** [comment]
Is the issue that there are two tasks? 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/6256453f-fc3f-4043-90e0-c248ab3842d2">

**Comment by muttmuure** [comment]
I switched assignee back and forth from mmoore+2020 to mmoore+2021, and it created a second task. Is that what the issue is referring to?

**Comment by muttmuure** [comment]
No worries @allroundexperts - definitely always worth double checking.
