### ISSUE TITLE
[HOLD for payment 2023-09-21] [Wave 6: Categories] CRITICAL - Create Category MenuItem and CategoryPicker component

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#24463]
Tracking Issue: https://github.com/Expensify/Expensify/issues/282161

Design Doc: https://docs.google.com/document/d/1itXKWlhms5YHcF4-lujO6g8T5LPdLVD_7onjtZBsATQ/edit#

**HOLD ON https://github.com/Expensify/Expensify/issues/302028**

---

## (Context) Fetching and Storing Categories

Even though the `categoryObjects` map is part of the policy object, we'll store them under a new collection key in Onyx: `policyCategories_<policyID>`. This has a few benefits over storing them directly in the policy. For instance, it allows categories to be evicted independently of the policy they belong to and makes it easier to update categories via Pusher.

Thus, we'll push category Onyx updates to all the members of the policy whenever changes are made by an admin in the policy editor. This will ensure clients have the most up-to-date copy of their policies' `categoryObjects` maps without having to fetch the full list each time they need to display categories.

With #vip-reliable-updates, we'll rely on `GetMissingOnyxUpdates` to keep the list up to date if you were offline when the changes were made.

## Category Menu Item
We will build off of what will be added for the Date and Merchant fields in [Wave 4: Scan Receipt](https://docs.google.com/document/d/1Il9y1287B6tq0FB5ziXnhBcwn-Lw-n_rSmllZ-AyUVs/edit#bookmark=id.a09scprg1rg4). 
**_Note: If this is not implemented yet, refer to the Wave 4 doc to implement the Category field before the Date and Merchant fields_** cc @MariaHCD 

When creating a Money Request on a policy that has categories, we'll show a "Category" menu item that is initially empty:
![image](https://github.com/Expensify/App/assets/1371996/6025cff9-1810-4ea0-871a-b148af6e905e)
![image](https://github.com/Expensify/App/assets/1371996/08e0100d-fe3f-40d2-be37-b9e1d81786f3)

We'll show the category as part of the [`MoneyRequestConfirmationList`](https://github.com/Expensify/App/blob/main/src/components/MoneyRequestConfirmationList.js), as a [`MenuItemWithTopDescription`](https://github.com/Expensify/App/blob/6ff85948bd09c856cbc272f1904ac30abc0e6492/src/components/MoneyRequestConfirmationList.js#L281-L297), similar to what we presently do for the "amount" and "description" fields.

With the [Distance Requests](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#bookmark=id.s5zjcrt925yg) project, we'll start connecting to the workspace `policyID` in the `MoneyRequestConfirm` component. We'll only show the menu item if there's a `policyID`. Additionally, we'll use the `policyID` to connect to the corresponding `policyCategories_` Onyx key. With that, we can confirm that the policy has categories enabled and populated (we'll know this because we load categories when opening the `MoneyRequestConfirmPage` beforehand).
**_Note: If this is not implemented yet, refer to the Wave 5 doc to implement the workspace `policyID` connection in the `MoneyRequestConfirm` component_** cc @neil-marcellini 

```JS
function MoneyRequestConfirmationList(props) {

// ...

    return (
        <OptionsSelector>

            // ... Other Menu Items

            {props.policyCategories != null && (
                <MenuItemWithTopDescription
                    shouldShowRightIcon={!props.isReadOnly}
                    title={props.iouCategory}
                    description={translate('common.category')}
                    onPress={() => Navigation.navigate(ROUTES.getMoneyRequestCategoryRoute(props.iouType, props.reportID))}
                    style={[styles.moneyRequestMenuItem, styles.mb2]}
                    disabled={didConfirm || props.isReadOnly}
                />
            )}



        </OptionsSelector>
    );
```
```JS
withOnyx({

    // ... Other Onyx Connection props

    policyCategories: {
        key: ({policyID}) => `${ONYXKEYS.COLLECTION.POLICY_CATEGORIES}${policyID}`,
    },
}),
```

- We'll create a new method `ROUTES.getMoneyRequestCategoryRoute` that links to `${iouType}/new/category/${reportID}`.
- This route will take you to the [Category Picker](https://docs.google.com/document/d/1itXKWlhms5YHcF4-lujO6g8T5LPdLVD_7onjtZBsATQ/edit#heading=h.4qev1cnytpps).
- The category selector will always sit in the same section as Merchant / Date. This will ensure that it is hidden behind the "Show more" dropdown just like those fields.
- The category selector will follow the same offline patterns as the Merchant and Date fields.

## Category Picker
We'll use a single page to render both the "simple" categories selector and the more complex category selector (for when you have >= 8 categories). Both versions of the page will mainly utilize an [`OptionsList`](https://github.com/Expensify/App/blob/e8644ea69cc18d9ca4f242cd045c134c55dd3ec3/src/components/OptionsList/BaseOptionsList.js) component. This will support [sections](https://github.com/Expensify/App/blob/e8644ea69cc18d9ca4f242cd045c134c55dd3ec3/src/components/OptionsList/BaseOptionsList.js#L219), custom [container styling](https://github.com/Expensify/App/blob/e8644ea69cc18d9ca4f242cd045c134c55dd3ec3/src/components/OptionsList/BaseOptionsList.js#L226), keyboard controls, and search via [text input](https://github.com/Expensify/App/blob/804b5be014d8b733ec3f1729d4d18b72bc013ab5/src/components/OptionsSelector/BaseOptionsSelector.js#L294-L314) already.

The `CategoryPicker` will take in the following props:
- `onSubmit`: Callback function to fire the moment a category is selected.
    - For the case of creating a Money Request, this saves the selected category (or lack thereof) to the local Money Request. This will be called from the [`onSelectRow`](https://github.com/Expensify/App/blob/e13bb6460455300c71d884f0360620fab7700849/src/components/OptionsSelector/optionsSelectorPropTypes.js#L6-L7) function we pass to the `OptionsSelector`.
- `policyID`: Used so that we may fetch the corresponding policy categories from Onyx
- `categoryList` (Onyx prop): The category list from the `COLLECTION_POLICY_CATEGORIES` Onyx key.
- `recentlyUsedCategories` (Onyx prop): The `recentlyUsedCategories` NVP of the user stored in Onyx.

### Less than 8 categories
When a policy has less than 8 categories, rendering the [`sections`](https://github.com/Expensify/App/blob/e13bb6460455300c71d884f0360620fab7700849/src/components/OptionsSelector/optionsSelectorPropTypes.js#L9-L27) for the `OptionsSelector` is very simple. We'll have a single, untitled section with each of our category names passed as options. The [`shouldShowTextInput`](https://github.com/Expensify/App/blob/e13bb6460455300c71d884f0360620fab7700849/src/components/OptionsSelector/optionsSelectorPropTypes.js#L90) prop will be passed as `false`.

![image](https://github.com/Expensify/App/assets/1371996/6e0f68fe-d51d-4fde-8f63-ce0997d25d85)

### More than 8 categories
When a policy has 8 or more categories, we'll render up to three sections, as well as show the text input for search.

![image](https://github.com/Expensify/App/assets/1371996/d0adec19-68ab-4502-b93e-71c00bf0e9ef)
![image](https://github.com/Expensify/App/assets/1371996/45c669c1-be19-492f-a862-a74ce344c4fc)

The sections will be as follows, and will be returned by a method similar to what we use for the [`MoneyRequestParticipantsSelector`](https://github.com/Expensify/App/blob/2c5797cdd36bd2b9939223f3ec97c494cbddcb3d/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L90-L125):
- **Selected category:** This section will have no title and only will display if a category is already on the expense. That category will render as selected as well as be omitted from the "All" and "Recents" sections below.
- **Recents:** This section will have a title. These will be the 5 most recent categories of the policy for the user - less the selected category if applicable. It will be grabbed from the `recentlyUsedCategories` prop. We'll only display this section if the array of recently used categories for the policies is non-empty.
- **All:** This will also have a title. This will be all the categories on the policy passed as options - less the selected category if applicable.

We'll utilize some methods in `CategoryPicker` to help us display our options:

- **`getOptionTree`**: In order to format the parent sections we'll need to utilize a helper method to transform the "parent category:child category" format into a format that is easier to interpret. We can follow a similar logic to what we have with [buildOptions](https://github.com/Expensify/Web-Expensify/blob/44a9e2c6aa8b3bc42b0785fbebba8db2ce6a4e2c/site/lib/category.js#L457-L524) for the `categorySelector` in OldDot. This will still be used even if we're displaying < 8 categories.
    ![image](https://github.com/Expensify/App/assets/1371996/30d34592-99ca-40f1-b300-93c215888989)

- **`getOptions`**: When there is text in the search bar, we'll hide the **Recents** section and flatten the options (including the selected option) as one unified section. They will use their original names (i.e. in "parent: child" format). We'll filter the options using the [`getNewChatOptions`](https://github.com/Expensify/App/blob/12d54e825466f7937d717ab976f414ed2cd213d1/src/libs/OptionsListUtils.js#L914-L937) method, passing in our search term. If our search term ever goes back to an empty string, we'll change back to using the result of `getOptionTree` above, as well as re-showing all sections.
    ![image](https://github.com/Expensify/App/assets/1371996/ac248afd-047a-4c88-aa33-0964c02e46bf)

#### Other details across both cases
- If a category name is super long, it will continue onto a second line in the same OptionRow.
- If there are no results matching the search term, we'll show "No results found", which is the [default behavior](https://github.com/Expensify/App/blob/9e5d4ee9ad4b0711ddb119009d49fa872e662f14/src/libs/OptionsListUtils.js#L1015-L1026) already.

### CreateTransaction
The action to create transactions, both for distance and regular requests already exists or will exist. The updates for each are quite simple. We'll need to update [`createTransaction`](https://github.com/Expensify/App/blob/f328f4459a60cc3226836a436248b81c7deedb82/src/pages/iou/MoneyRequestModal.js#L301) to incorporate the selected category. We'll also need to update [`createDistanceRequest`](https://docs.google.com/document/d/16Q9sE-991CZ4wUcalOs_U-qyEEza_C9tZwj6G5lHUp0/edit#bookmark=id.x8tbl2tvtloo) to incorporate the category as well.

---

## Automated Tests

We'll add tests for the CategoryPicker logic, most notably around creating the list of options to be displayed. We'll test that the following criteria are satisfied:

### `getOptionTree`
- Sub-categories are properly indented when returned from `getOptionTree`.
- Multiple levels of sub-categories are indented properly when returned from `getOptionTree` - and that alphabetical order is still honored from the original parent category.
- If a parent category is not in the category list, it is disabled when returned from `getOptionTree`.
- Sub-categories are shown in "parent: child" format when:
    - Shown as the selected category in the request detailed view
    - Shown as the top selected category when there are more than 8 categories
    - Appearing in search results
    - Appearing in the recent categories section
    - Appearing in the "All" section but it's parent category is the currently selected category.

### `getOptions`
- All three sections (Selected category, Recents, All) are present when there are `recentlyUsedCategories` for the policy, a category has already been selected, and there are more than 8 categories.
- The selected category is not present in "All" when there are more than 8 categories.
- There are only two sections (Recents, All) present when there are `recentlyUsedCategories` for the policy and there are more than 8 categories, but no category is selected.
- There is only one section displayed (All) when no category is selected and `recentlyUsedCategories` for the policy are empty.
- When there are less than 8 categories:
    - Only one section is displayed with no title
    - "Recents" are not displayed even though `recentlyUsedCategories` is present and has values
    - The selected category shows within the list instead 

<hr>

## Implementation:
- [x] https://github.com/Expensify/App/pull/25470
  - Add a “Category” menu item to the Money Request screen.
  - Creates a basic Category Picker screen. It includes: title, description and simple list.
- [x] https://github.com/Expensify/App/pull/25777
  - Create `getOptionTree` function, to format the parent sections we'll need to utilize a helper method to transform the "Parent: Child" category format into a format that is easier to interpret.
  - Extend `getOptions` function, to split categories by sections.
  - Extend `getNewChatOptions` function, to filter the options using the function.
  - Implement tests for as many cases as possible.
- [ ] https://github.com/Expensify/App/pull/26501
  - Connect previously created categories simple
  - Enable categories for manual and distance requests.
  - Send a selected category among other request details

**Comment by rezkiy37** [comment]
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and I would like to take this issue as well.

**Comment by puneetlath** [comment]
@jjcoffee and @situchan have both been C+ on these PRs so far.

**Comment by rezkiy37** [comment]
The issue is not completed yet. It requires one more PR ([UI/UX](https://github.com/Expensify/App/pull/26501)) at least.

**Comment by yuwenmemon** [comment]
@rezkiy37 @waterim Just a heads up we're thinking of going this direction for the recentlyUsedCategories in Onyx:

# `recentlyUsedCategories` in Onyx
We'll store recentlyUsedCategories as a collection key in Onyx. One key for each policy stored in the NVP, like so:

"policyRecentlyUsedCategories_9AD45C92379B3114": [
    "Meals",
    "Entertainment",
    "Office Supplies",
    "Travel",
    "Utilities"
],
"policyRecentlyUsedCategories_C7F01619301AF35C":     [
    "Fringe Benefits: Remote Lunch",
    "Social Policy: Meals",
    "Social Policy: Entertainment",
    "Travel Meals",
    "Travel Airfare & Transportation"
],

This way, we can reduce the potential scope of any subscribers listening to that key.

---

What do you think?

**Comment by yuwenmemon** [comment]
Also, another development, because we want to start sending push notifications for category updates from our server before this goes live, we can no longer rely on the absence of categories to hide the selector from the `MoneyRequestConfirmationList`. We'll need to check that a user is on a beta in addition to that.

This means we'll need to add a `canUseCategories` to the [Permissions.js](https://github.com/Expensify/App/blob/50d3a09342660894d385966dc2f85e54b1853470/src/libs/Permissions.js) file, and check that before showing the selector or not. Does that make sense / sound good?

**Comment by rezkiy37** [comment]
Already working on a fix.

**Comment by rezkiy37** [comment]
[The PR](https://github.com/Expensify/App/pull/27350) already reviewing internally, public review gonna be soon.

**Comment by yuwenmemon** [comment]
@puneetlath can we close this?

**Comment by puneetlath** [comment]
I need to pay out the C+ that were involved. I'll do that tomorrow and then we can close.

**Comment by puneetlath** [comment]
Ok so it looks like we had three PRs here: 
- https://github.com/Expensify/App/pull/25470 (C+ @jjcoffee) 
- https://github.com/Expensify/App/pull/25777 (C+ @situchan) 
- https://github.com/Expensify/App/pull/26501 (C+ @abdulrahuman5196)

Does that all seem right? If so the payment summary would be: 
- C+ @jjcoffee - $500
- C+ @situchan - $500 
- C+ @abdulrahuman5196 - $500

All to be paid out via Upwork.

**Comment by jjcoffee** [comment]
@puneetlath I think @situchan and I both had our PR reviews from before the compensation was updated ([Aug 30](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649)), so I wonder if it should be $1000 instead?

**Comment by puneetlath** [comment]
Looks like you're right. I'll update that. Thanks for letting me know.

**Comment by puneetlath** [comment]
Upwork offers sent: 
https://www.upwork.com/nx/wm/offer/26812985
https://www.upwork.com/nx/wm/offer/26812987
https://www.upwork.com/nx/wm/offer/26812991

**Comment by jjcoffee** [comment]
@puneetlath Offer accepted, thanks!

**Comment by puneetlath** [comment]
@situchan and @jjcoffee have been paid. 

Now just waiting for @abdulrahuman5196 to accept the contract and we should be good to go here.

**Comment by yuwenmemon** [comment]
@puneetlath are we good to close here?

**Comment by puneetlath** [comment]
All paid now. Thanks everyone!
