### ISSUE TITLE
Group Thread- Tapping on thread name in header not showing "members" section on first visit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Fab
3. Tap new group
4. Select 3 members and tap "create group"
5. Send a message
6. Long press the sent message
7. Tap Reply in thread
8. Send a message
9. Tap header "thread name" to note in directed page you are not shown "members" section
10. Tap share code
11. Tap back button thrice to navigate to "group conversation"
12. Tap "1 reply"
13. Tap header "thread name" again and check for "members" section

## Expected Result:
In group chat, while creating thread and tapping on "thread name" in header, user must be directed to page which must show "members" section on first visit itself

## Actual Result:
In group chat, while creating thread and tapping on "thread name" in header, user directed to page which does not show "members" section. The user has to go back to group conversation and then revisits the thread page and tap on "thread name" in header to see "members" section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a01dbe70-e9fd-4760-bf1b-978a8dcbd5d4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Thanks @tienifr. Closing as a dupe.
