### ISSUE TITLE
Room - No notifications for messages sent in rooms with the "Immediately" notification setting (E.g. #admins or #announce)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into account A on the main testing device
2. Sign into account B on a secondary device or browser
3. Send some messages from account B in a room conversation were Account A and Account B are included and the notification preference is set to Immediately

## Expected Result:
Account A should receives notifications of the new messages in the room conversation

## Actual Result:
Account A should does not receive notifications of the new messages in the room conversation

## Workaround:
Unknowm

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-13

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/66230fc7-9607-476d-b387-b6f5f17c8aa7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Thanks @tienifr ! Taking a look now

**Comment by MitchExpensify** [comment]
I think I fixed my notifications and was unable to reproduce this afterward:

<img width="1447" alt="image" src="https://github.com/Expensify/App/assets/36425901/c75a31fc-ffd1-43aa-af34-5d84b2ce5ca7">

**Comment by MitchExpensify** [comment]
Ok I was able to reproduce!

**Comment by MitchExpensify** [comment]
I found another bug in the process that was stopping me reproduce orginally 😅

**Comment by MitchExpensify** [comment]
Are you able to reproduce this on Safari @tienifr ?

**Comment by MitchExpensify** [comment]
Ok thank you! I check internally and this is part of an ongoing project, we're aware of the bug, and will be fixing elsewhere. Thanks for your help @tienifr - Much appreciated
