### ISSUE TITLE
Assign task- Yellow icon user tapping from link, error shows & it goes missing on revisit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap new chat
4. Enter an email that doesn't have new dot account yet in this specific way
5. Type email [id+letters@gmail.com](mailto:id+letters@gmail.com)
and change letters after plus, until it shows yellow profile icon.
6. When yellow profile icon it displays, select that user
7. Navigate back to LHN
8. Tap fab
9. Tap assign task
10. Enter any title and tap next
11. Tap assignee
12. Select yellow profile icon user mail id which is created in step 6
13. Tap confirm task
14. Tap From link in header
15. Tao back button of "Hhm it is not here page"

## Expected Result:
When user taps "confirm task", he must be shown task page properly displayed without refreshing and tapping on "from" link in header, must be directed to conversation page which should not display any error.when user re-visit task page, the header "from link" must not disappear

## Actual Result:
When user taps "confirm task", the task page user lands and it gets refreshed after a second. Then tapping on "from" link in header, user directed to conversation page which shows error message " Hhm it's not here" and tapping on back button, the header " From link" disappears in task page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f467a23a-f40f-42ba-9786-ab232b23ce9c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
Nothing to do with yellow avatar and probably dupe https://github.com/Expensify/App/issues/24387

**Comment by tjferriss** [comment]
Agreed, this looks like a dupe.
