### ISSUE TITLE
[$1000]  uploading EPS extension file throws an error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Click on :heavy_plus_sign: icon
3. Click on Add attachment
4. Select .EPS extension file and send it
## Expected Result: 
The app should send the file or throw "This filetype is not allowed" pop-up.
## Actual Result: 
Gives an error saying "Invalid image supplied"
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c4a557de-6ed6-4915-b4b0-de2a2a34a42d

![Snip - (74) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/9cce66c1-e7ad-4505-91b2-7c96a492b0a6)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690751127702569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01441ec377d38bb1cc</li>
        <li>Upwork Job ID: 1693709065932484608</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by ishpaul777** [comment]
we are not validating dropped file extension. if there are some restricted extensions we should add a condition to validate.

```
 const {fileExtension} = FileUtils.splitExtensionFromFileName(lodashGet(file, 'name', ''));
    if (_.contains(CONST.API_ATTACHMENT_VALIDATIONS.UNALLOWED_EXTENSIONS, fileExtension.toLowerCase())) {
        setIsAttachmentInvalid(true);
            setAttachmentInvalidReasonTitle('attachmentPicker.attachmentTooSmall');
            setAttachmentInvalidReason('attachmentPicker.sizeNotMet');
            return false;
        return false;
    }
```

**Comment by DylanDylann** [comment]
I think It is BE bug. The error is threw from BE side

**Comment by jo-ui** [comment]
@strepanier03 any updates on this issue?

**Comment by jo-ui** [comment]
@strepanier03 It has been a week since this issue was posted, but there has been no response.

**Comment by strepanier03** [comment]
I was on sabbatical and am just getting back from it now. I'm working on this today and will have an update soon.

**Comment by strepanier03** [comment]
I was able to recreate this behavior using a random .eps file on my computer as well as the one shared in the Slack bug report thread. 

<img width="1052" alt="image" src="https://github.com/Expensify/App/assets/10925636/2666f248-91c7-4e37-9b4b-6921865d3409">

**Comment by strepanier03** [comment]
@burczu - If you think this is an internal issue please let me know and I can switch to an `Internal` label.

**Comment by b4s36t4** [comment]
I can upload the files without any issue on staging.

**Comment by alitoshmatov** [comment]
Similar issue was noted here - https://github.com/Expensify/App/issues/22306#issuecomment-1630209033

I tried to create slack conversation for this, but didn't get any response - https://expensify.slack.com/archives/C01GTK53T8Q/p1690348144733229

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
uploading EPS extension file throws an error
### What is the root cause of that problem?
Some files' type is empty when checking in javascript, and backend is resulting in error for those files for example: `.c` files. For above mentioned `.eps` file it is working normally for me but I am assuming sometimes it might fit above case.
<img width="791" alt="Screenshot 2023-07-11 at 11 09 15 AM" src="https://github.com/Expensify/App/assets/59907218/102221ae-f630-4d14-9ede-b036ffda891a">

if type is empty the backend also rejects this file, and sends an error.
<img width="570" alt="Screenshot 2023-07-11 at 11 11 50 AM" src="https://github.com/Expensify/App/assets/59907218/5d98a77c-05b3-441f-a5ed-91d4cde5d1bf">


### What changes do you think we should make in order to solve the problem?

So there is no point of sending files where type is empty. We can add additional condition `!lodashGet(_file, 'type')` here to check if type is empty:
https://github.com/Expensify/App/blob/acf9cede7f0f5f4c2ebd89cc48f012de6ae81b0f/src/components/AttachmentModal.js#L186

This way, we can any files which backend would respond with an error.

### What alternative solutions did you explore? (Optional)

**Comment by burczu** [comment]
@strepanier03 The `Invalid image supplied` message that is added after the `Unexpeceted error...` message comes from the BE side, so I think it means that BE has some issue processing files with this extension. That's why I believe we should we should make it internal and at least check what's happening with these files on the BE side.

**Comment by ishpaul777** [comment]
@burczu I agree that error comes from BE.
But IMO allowing uploads for all file type to backend could potentially expose the application to security vulnerabilities. What do you think?

**Comment by burczu** [comment]
@ishpaul777 from what I see the app allows to upload any type of file - if it's not an image or pdf then you can just download the file (there is no preview in the report) and I guess it is done this way by design

**Comment by ishpaul777** [comment]
Platforms like Slack, Gmail and Google Chat have implemented restrictions on certain types of file uploads (references: [Slack policy](https://slack.com/intl/en-in/help/articles/1500002249342-Restricted-file-types-in-Slack-Connect), [Gmail](https://support.google.com/mail/answer/6590?hl=en#zippy=%2Cmessages-that-have-attachments) and [Google Chat policy](https://support.google.com/chat/answer/7651457?hl=en&co=GENIE.Platform%3DAndroid#File%20types%20blocked%20in%20Google%20Chat)). Considering this, it might be prudent for us to implement similar restrictions on the types of files users can upload. I recommend that we discuss and consider implementing a file type validation mechanism that only allows safe and necessary file types for upload. 
Allowing all file types, including potentially harmful ones like executable files (e.g., ".exe") exposes vulnerabilities for users as well as backend, However, if this is intentionally part of the design, I recommend that we document the rationale behind it, along with the assessed risks.

**Comment by strepanier03** [comment]
@burczu - reading the response from @ishpaul777 [here](https://github.com/Expensify/App/issues/24497#issuecomment-1688006744), do you want to raise this for discussion at all or should I switch the labels now?

**Comment by burczu** [comment]
@strepanier03 - I think for this issue we should just switch the labels

@ishpaul777 - I can hear you and it's reasonable what you wrote, but I think it sounds more like a feature request so I believe you could raise another issue to discuss it - what do you think?

**Comment by ishpaul777** [comment]
Can you chime in slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1692691281183839

**Comment by strepanier03** [comment]
Nothing yet on the thread but it's Friday so we might have some stragglers come in Monday. Will bump then.

**Comment by strepanier03** [comment]
No new movement on the thread so I posted in another internal channel trying to get more opinions on it. We could also allow the internal engineer to move this forward more when it gets picked up as well.

**Comment by strepanier03** [comment]
I'm really struggling to get opinions weighing in here.

**Comment by strepanier03** [comment]
Discussion is ongoing on the thread, will continue to follow along.

**Comment by strepanier03** [comment]
@ishpaul777 @burczu - Based on the discussion in the thread, do we have a path forward?

**Comment by ishpaul777** [comment]
there is no discussion around the https://github.com/Expensify/App/issues/24497#issuecomment-1688006744 in the thread, i believe the unallowed extensions are removed  intentionally,
To move forward with This particular issue(not able to upload .eps file ) i think you should post issue on slack internally, to get more eyes on this from internal engineers
 @strepanier03

**Comment by burczu** [comment]
@strepanier03 I agree with @ishpaul777 - this [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1692691281183839) on slack was about his concerns on adding additional validation for file types on the frontend side. It separate thing and this issue should be still fixed on the backend side - that was the reason to change the label to `internal`.

**Comment by burczu** [comment]
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by strepanier03** [comment]
@ishpaul777 and @burczu - I will bump the internal thread I started for this previously. Thanks for the heads up about your OoO as well.

**Comment by strepanier03** [comment]
I bumped this in Slack and @Gonals had worked on this. It's on our radar for now.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment]
@mvtglobally - Thank you!

**Comment by strepanier03** [comment]
Still waiting for internal ownership, I'll bump again internally this week.

**Comment by dangrous** [comment]
Hey @strepanier03 I had a second to look into this - I'm not seeing the error, on staging or production. Are you still able to reproduce? A sample `.eps` file I used uploads and downloads fine.

Not sure what's changed since the issue was opened but we might be all set now.

**Comment by jo-ui** [comment]
@dangrous Try it with other .eps files.
[EPS files.zip](https://github.com/Expensify/App/files/12665579/EPS.files.zip)

**Comment by strepanier03** [comment]
@dangrous - I'll give it another shot.

**Comment by strepanier03** [comment]
@dangrous - Just tested again with the three .eps files that @jo-ui shared [here](https://github.com/Expensify/App/issues/24497#issuecomment-1726324122). All three repro'd the reported behavior.

<img width="1426" alt="image" src="https://github.com/Expensify/App/assets/10925636/1513a811-4eca-4f37-93fa-6b665557b898">

**Comment by dangrous** [comment]
Ah yep, tried some others. Making a PR to fix

**Comment by dangrous** [comment]
This should be fixed! @strepanier03 do you mind testing when you have a moment? I might be able to get to it later this week

**Comment by strepanier03** [comment]
Yup, I can test. Doing it now and will update shortly.

**Comment by strepanier03** [comment]
I'm able to upload the files successfully and download them, but I don't have a program on my mac to open them. When I try it opens in ATOM, which isn't a vector file program. 

The behavior looks updated and correct if I had a program to open an EPS file though.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by dangrous** [comment]
Okay I think I'm gonna close this out!

**Comment by jo-ui** [comment]
@strepanier03 It is working perfectly on both staging and production. Can you send me an offer for the reporting bonus

**Comment by dangrous** [comment]
My bad! Reopening to handle payment.

**Comment by strepanier03** [comment]
Thanks @dangrous - I'll work on the reporting payment and close out when it's wrapped.

**Comment by strepanier03** [comment]
@jo-ui - I can't figure out who you are in Upwork. Can you apply for the job [here](https://www.upwork.com/jobs/~01e2245245e745feae) or link your Upwork profile and I'll hire you?

**Comment by jo-ui** [comment]
@strepanier03 I've applied for the job on upwork

**Comment by strepanier03** [comment]
Thanks @jo-ui - I have hired you again and will keep an eye out for your acceptance so I can pay this and get this close out today.

**Comment by jo-ui** [comment]
Thank you @strepanier03 I've accepted the offer on upwork

**Comment by strepanier03** [comment]
I've payed out the contract, ended it, and left feedback. 

Thank you @jo-ui for being part of this community 🙌
