### ISSUE TITLE
Unable to clear MagicCodeInput

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open signin page
2. write email and continue
3. type some numbers om
4. try to clear the input by clicking the x on keyboard
## Expected Result: 
The input will be cleared step by step
## Actual Result: 
the input is not cleared

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9fbc25cf-8c9c-43a7-8937-aa3eddf98d79

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686598483616689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joh42** [comment]
I've run into this issue as well on Chrome/Android, but only when not using the default keyboard.

**Comment by ShogunFire** [comment]
Can someone test on real device ? I think I saw a comment in the code about a keyboard probelm on emulators

**Comment by sophiepintoraetz** [comment]
Thanks @ShogunFire, I can't replicate on an actual android.

https://github.com/Expensify/App/assets/42940078/d496c274-aaf7-48e8-a40c-dee2023662b1
