### ISSUE TITLE
MiniReportActionContextMenu is out of view for top comment of a report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and send messages till the report screen fills up
2. Hover over the top most message
## Expected Result: 
MiniReportActionContextMenu should be visible (perhaps should be shown to the bottom side of the reportAction)
## Actual Result: 
MiniReportActionContextMenu is not visible

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/886119c6-0f61-4484-b833-eb013eb5d1dd

https://github.com/Expensify/App/assets/43996225/7b0592e9-be9f-4d7e-945a-0363c766807e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691290851673459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
I don't think this is a bug. This also happens in the Slack web interface.

**Comment by zanyrenney** [comment]
Agreed! Thanks @akinwale
