### ISSUE TITLE
The requested money is reset to 0 if the account is closed and logged in again.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with User A and User B.
2. User A requests the money to User B. (Click on Request money in LHN > Enter a desired mount > Click on Next button > Select User B and Click on Request button)
3. User B closes his account and log in again.
4. User B opens a chat with User A.

## Expected Result:
 The amount requested by User A from User B is reset to 0.
## Actual Result:
 The amount requested by User A from User B should remain the previous amount.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/51480c56-6ea1-4e3a-bf07-a5f4ef8fbb1f

https://github.com/Expensify/App/assets/38435837/5d88ac22-ec98-4676-8218-777018bae362

**Expensify/Expensify Issue URL:**
**Issue reported by:** @OleksandrPantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691183323583529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This isn't a bug, we clear this data when closing an account so it makes sense to be reset to $0

**Comment by mkarkachov** [comment]
Yeah, @stephanieelliott I think you misunderstood the issue
