### ISSUE TITLE
[$1000] The assigned task does not allow the account if the account is closed and logged in again.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with User A and User B.
2. User A assigns a task to User B. (Click on Assign task in LHN > Enter a title > Select Usert B to Assignee > Click on Cofirm task)
3. User B closes his account and log in again.
4. User B opens the assigned task from User A.

## Expected Result: 
User B should call the assigned task from User A.
Or User A should remove User B from Assignee when User B is closed.
## Actual Result: 
User B cannot call the assigned task from User A.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/2561cfe0-a71d-444c-94b4-e9d0e11d72c0

https://github.com/Expensify/App/assets/38435837/0809bb59-e77b-47c4-9ba0-9fc73012ca05

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @OleksandrPantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691185415235919
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01179691a19c304dc3</li>
        <li>Upwork Job ID: 1692243157107609600</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by mkarkachov** [comment]
Maybe it's linked to this issue #24524

**Comment by kevinksullivan** [comment]
taking to slack for clarification

https://expensify.slack.com/archives/C049HHMV9SM/p1692296893913119?thread_ts=1691183323.583529&cid=C049HHMV9SM

**Comment by Thanos30** [comment]
I believe this must be a backend issue. There is no console error here, but the API response on `OpenReport` call is unauthorized (403) after the user closed and reopened the account, meaning the user is no longer authorized to access the task report that he was assigned to before he closed the account.

Something must be happening after the `CloseAccount` API call, maybe something with the user's core info, like IDs or something, that change after the reopening, or maybe something that is directly affecting tasks.

In any case, I couldn't find any relevant code on the frontend part other than the API call, please correct me if I am wrong.

**Comment by kevinksullivan** [comment]
Still awaiting / reviewing proposals.

**Comment by mkarkachov** [comment]
Agree with [Thanos30](https://github.com/Expensify/App/issues/24523#issuecomment-1683031262) and I don't understand why closed this [issue](https://github.com/Expensify/App/issues/24524) . As for me, these issues are linked

**Comment by kevinksullivan** [comment]
@abdulrahuman5196 can you provide an update on this?

**Comment by abdulrahuman5196** [comment]
There isn't any proposal here. Only we need to confirm if this is a backend issue. Will check and get back soon

**Comment by kevinksullivan** [comment]
Ok, what do we need to do to confirm that? Do we need to loop an internal engineer to review this @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment]
> I believe this must be a backend issue. There is no console error here, but the API response on `OpenReport` call is unauthorized (403) after the user closed and reopened the account, meaning the user is no longer authorized to access the task report that he was assigned to before he closed the account.
> 
> Something must be happening after the `CloseAccount` API call, maybe something with the user's core info, like IDs or something, that change after the reopening, or maybe something that is directly affecting tasks.
> 
> In any case, I couldn't find any relevant code on the frontend part other than the API call, please correct me if I am wrong.

@kevinksullivan This analysis is correct. 

I am not sure on the behaviour here. If we want to show the assigned task even after the account is closed and re-opened, then this should be fixed in backend.

**Comment by kevinksullivan** [comment]
Looping in an internal engineer

**Comment by amyevans** [comment]
Yeah this will need to be a backend fix. I'm trying to stay heads down on Wave 6 for the foreseeable future. @thienlnam any interest in taking this over since it's related to tasks?

**Comment by thienlnam** [comment]
I'm also pretty heads down right now - I can take it but I'm not going to get for it for a while. Let's just throw it on a weekly/monthly for now?

**Comment by amyevans** [comment]
Sounds good yeah it is definitely an edge case!

**Comment by thienlnam** [comment]
No update - though should be seeing some free cycles later this week

**Comment by thienlnam** [comment]
I'm going to close this - it's an edge case and not really valuable to spend time on right now
