### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] iOS - Chat - Request money - Emojis in User's name are being cut off in the report preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with user A
2. Add emoji in user A's name
3. Request money from user B
4. Login with User B > Go to the chat with User A
5. Observe that the emoji is being cut off for user B

## Expected Result:
Emoji is not being cut off

## Actual Result:
Emoji is being cut off

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Build v1.3.53-0

**Reproducible in staging?:** Y 

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_0410](https://github.com/Expensify/App/assets/115492554/3612e9c7-7f48-4b99-bd37-40e103c34cbd)

![IMG_0319](https://github.com/Expensify/App/assets/115492554/60bd56b9-6b07-45e5-bcac-e951bc5cb855)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691145299641679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b8487a46560407b</li>
        <li>Upwork Job ID: 1696183868945104896</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26413673</li>
<li>Aman-atg | Reporter | 26413675</li>
</ul></li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
I cannot reproduce this.

**Comment by isabelastisser** [comment]
Hey @burczu, can you please review the proposal above? Thanks!

**Comment by burczu** [comment]
Hey @isabelastisser! Sorry, I've missed this one - I'll review it today!

**Comment by burczu** [comment]
I've checked[ the proposal](https://github.com/Expensify/App/issues/24527#issuecomment-1677161317) from @hungvu193 and I think it's correct and we should proceed with it (just changing to use `styles.lh20` - I wouldn't change the `textLabelSupporting` class because it is responsible only for font styling and is used in other places with some other styles).

🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment]
I agree with @burczu's [assessment](https://github.com/Expensify/App/issues/24527#issuecomment-1699079287).

**Comment by isabelastisser** [comment]
Payment summary:

- @burczu does not require payment, contractor.
- @hungvu193 $1000 accepted proposal, $500 urgency bonus
- @aman-atg reported the issue, $250.

**Comment by isabelastisser** [comment]
Offers sent in Upwork, all set!
