### ISSUE TITLE
Issue to Provide Reporting Bonus for Pull/24184

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#24538]
@Natnael-guchima reported a [bug](https://expensify.slack.com/archives/C049HHMV9SM/p1691182214043129) (regression) that was fixed in https://github.com/Expensify/App/pull/24184 and so needs the $250 payment. A new issue wasn't made since we pushed the change quickly since it was on dev

cc @allroundexperts
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b5cb88cdf6f9716</li>
        <li>Upwork Job ID: 1691138704676880384</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Added `Internal` label to create an Upwork link for payment. Feel free to ignore @parasharrajat. 

Payouts due:

Issue Reporter: $250 @Natnael-Guchima 
Contributor: NA
Contributor+: NA

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/jobs/~017b5cb88cdf6f9716)

Internal job posting - https://www.upwork.com/ab/applicants/1691138704676880384/job-details

please feel free to accept the offer @Natnael-Guchima and I'll pay you!

**Comment by Natnael-Guchima** [comment]
I have accepted the offer. Thanks, @Christinadobrzyn

**Comment by Christinadobrzyn** [comment]
awesome! Paid you in Upwork @Natnael-Guchima!

Closing the Upwork job and this GH.
