### ISSUE TITLE
Android - Notifications - Tapping the notification banner or opening the app doesn't clear notifications when there are 3 or more types

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account on Mac Chrome and the Android app as "User A" and as "User B" on a separate tab on chrome (this might need to be in an incognito browser).
2. Ensure you have no unread notifications on Android and the app is closed.
3. Steps 4-8 should be done as "User B" on Mac Chrome to trigger different notification types.
4. Open the chat with "User A" and send a message (1st notification type).
5. Click on the + sign in the composer, choose "Request money", enter an amount, and then click on the green button that says, "Request [amount you input]".
6. Click on the IOU preview and then send a message in the money request thread (2nd notification type).
7. Click on the + sign in the composer, choose "Assign task", enter a title, select "User A" as the assignee, and then click on "Confirm task".
8. Send a message in the newly-created task thread (3rd notification type).
9. Go back to the main chat with "User A", hover over the message you sent in step 4, choose the "Reply in thread" option, and then send a message in the thread.
10. As "User A", send a message in the thread, switch back to "User B", and then send a second message in the thread (4th notification type).
11. Tap on the notification banner on your Android device to open the Expensify app. You can also try tapping on the app's icon to open it.

## Expected Result:
The notifications are cleared i.e. the banner isn't shown, and the app icon has no badge.

## Actual Result:
The notification banner and app badge persist after tapping the banner or opening the app.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3e256114-6613-40a9-a24f-33477cb8ee3e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Victor-nyagudi

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691155618325599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I've reproduce now: 

User A: conor+24537AA@conorpendergrast.com
User B: 20303b@conorpendergrast.com

But, to be honest, I'm not totally convinced that this is a bug. Bringing [back to Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1692092340070759?thread_ts=1691155618.325599&cid=C049HHMV9SM)

**Comment by conorpendergrast** [comment]
From discussion in Slack, it sounds like this is a combination of by-design features (that tapping one notification from the app will not clear all notifications from the app, intentionally) and [a reproduction of the unread indicator bug](https://github.com/Expensify/App/issues/17316). Thanks @Victor-Nyagudi!
