### ISSUE TITLE
[HOLD for payment 2023-08-24] Payment for #22778

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#24546]
https://github.com/Expensify/App/pull/22778 was linked to an internal E/E issue.

Creating this App issue for C+ payment since one did not get created automatically

**Comment by thienlnam** [comment]
Issue has not been deployed yet

**Comment by johncschuster** [comment]
# Payment Summary

External issue reporter - NA
Contributor that fixed the issue - NA
Contributor+ that helped on the issue and/or PR - @Santhosh-Sellavel - $1000 to be paid via NewDot

cc @JmillsExpensify

**Comment by johncschuster** [comment]
@JmillsExpensify bump on the payment above!

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
Reviewed the details for @Santhosh-Sellavel. $1,000 approved for payment via NewDot based on BZ summary.
