### ISSUE TITLE
Web - Profile - No transition animation on 'Pronouns' selector

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Profile
2. Click 'Pronouns'

## Expected Result:
There should be a transition animation when the Pronouns page is loaded

## Actual Result:
No transition animation is shown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9ebeeee9-204c-4cf6-9dc2-414779f3097d

https://github.com/Expensify/App/assets/115492554/31ac7d91-1349-48b3-ab5a-ff9dc9fc98d7

https://github.com/Expensify/App/assets/115492554/2d12d406-7047-4395-a6c6-b2d7ac3a2cf4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @PbKompasz

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691161563063259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Proposal from @pbkompasz
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No transition animation on 'Pronouns' selector
### What is the root cause of that problem?
`<SelectionListRadio />` focus animation breaks `<PronounsPage />`'s transition animation.
### What changes do you think we should make in order to solve the problem?

Assign props to `<SelectionListRadio />` component.
``` js
SelectionListRadio.propTypes = selectionListRadioPropTypes.propTypes;
SelectionListRadio.defaultProps = selectionListRadioPropTypes.defaultProps;
```
These props contain the shouldDelayFocus
Pass `shouldDelayFocus` prop to <SelectionListRadio />
and pass that prop to <BaseSelectionListRadio />
``` js
<SelectionListRadio
  headerMessage={headerMessage}
  textInputLabel={props.translate('pronounsPage.pronouns')}
  textInputPlaceholder={props.translate('pronounsPage.placeholderText')}
  textInputValue={searchValue}
  sections={[{data: filteredPronounsList, indexOffset: 0}]}
  onSelectRow={updatePronouns}
  onChangeText={onChangeText}
  shouldDelayFocus
  initiallyFocusedOptionKey={initiallyFocusedOption.keyForList}
/>
```
``` js
<BaseSelectionListRadio
  // eslint-disable-next-line react/jsx-props-no-spreading
  {...props}
  ref={ref}
  shouldDelayFocus={props.shouldDelayFocus}
  onScroll={() => {
    // Only dismiss the keyboard whenever the user scrolls the screen
    if (!isScreenTouched) {
        return;
    }
    Keyboard.dismiss();
  }}
/>
```
Additionally we should remove the selectTextOnFocus
### What alternative solutions did you explore? (Optional)
Alternatively we can remove the auto-focus from the input.

**Comment by ShogunFire** [comment]
We don't use shouldDelayFocus anymore, there have been like 4 different issues about this with different pages, it would be nice if one of them could correct every pages

**Comment by ShogunFire** [comment]
For example this one: https://github.com/Expensify/App/issues/22388

**Comment by pbkompasz** [comment]
@ShogunFire 
The other options would be:
1. Set the delay as the default
2. Check if an animation is running in the parent element and only trigger the animation in the current element when `animationend` event is triggered.

**Comment by alexpensify** [comment]
Thanks for the feedback, I'll review this GH soon.

**Comment by alexpensify** [comment]
I've started a discussion here: 

https://expensify.slack.com/archives/C049HHMV9SM/p1692390540016689?thread_ts=1691161563.063259&cid=C049HHMV9SM

I'm trying to verify if https://github.com/Expensify/App/issues/22388 will include an update for all pages or if we should keep this GH open to address a specific page.

**Comment by alexpensify** [comment]
No update, I've bumped the 🧵 again.

**Comment by ShogunFire** [comment]
@alexpensify yes they will https://github.com/Expensify/App/issues/22388#issuecomment-1688049515

**Comment by alexpensify** [comment]
Thank you for the feedback! I'm closing this GH because of the confirmation shared here and in Slack.
