### ISSUE TITLE
Web - Split bill - The bill is not split properly when splitting $0.02 to 4 users

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on plus sign in LHN.
2. Click on Split bill.
3. Enter $0.02 and Click on Next button.
4. Select 3 users.

## Expected Result:
2 users should pay $0.01 each.

## Actual Result:
One user pays -$0.01 and then 3 users pay $0.01 each. It's an invalid split.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6ba71166-4699-4bda-a169-94127308fe30

https://github.com/Expensify/App/assets/115492554/54704e26-1d43-4085-9e66-fe3feda57d89

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Oleksandr Pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691178734272449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Thanks @hungvu193 I reviewed the other [thread]([skye.bush@team.expensify.com](mailto:skye.bush@team.expensify.com)) / GH and agree this can be close for the same reason

**Comment by MitchExpensify** [comment]
Thanks for following up here @oleksandr-pantsyr . I could have been a bit clearer here, it is a bug but the consensus is that we should "acknowledge it exists but agree it’s not super practical to fix" https://expensify.slack.com/archives/C049HHMV9SM/p1673449943122609?thread_ts=1673325036.803299&cid=C049HHMV9SM
