### ISSUE TITLE
Web - Receivers details appears even if receivers didn't send any message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on FAB icon and select new chat option
2. enter email with whom user didn't have chat history and select that user
3. sender can't see receiver details because receiver didn't sent any message
4. go to  Settings > Workspaces >Members > invite
5. invite receiver
6. go back to receivers report screen and check the receivers details

## Expected Result:
sender should not able to see receivers details because receiver didn't send any message

## Actual Result:
sender able to see receivers details

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0895d01b-cfbc-4c4e-833e-14021ef483fb

https://github.com/Expensify/App/assets/115492554/bd313693-aa51-4f32-9aa2-015e8029a0b9

https://github.com/Expensify/App/assets/115492554/bad5a15b-b466-4a75-96b5-e8cdf6534645

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691386587759709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Didn't get to today, but will action this tomorrow

**Comment by dylanexpensify** [comment]
Looking now

**Comment by dylanexpensify** [comment]
checking flow [internally](https://expensify.slack.com/archives/C03U7DCU4/p1692193784103809)

**Comment by dylanexpensify** [comment]
we confirmed not a bug
