### ISSUE TITLE
Web - Assign task - Not able to assign user with whom don't have chat history

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. click on + icon and select assign task option
3. enter title and click on confirm button
4. go to task thread
5. click on Assignee
6. enter email with whom you don't have chat history
7. click on that user

## Expected Result:
user should be assignee to task

## Actual Result:
error appears on select user

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-7

**Reproducible in staging?:** v1.3.54-7

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/86fdf15f-9468-44c6-bb47-19e43ec1965a

https://github.com/Expensify/App/assets/115492554/1cb3cf40-0be6-460a-b865-62a398d3146d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @GadhiyaManan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692008476930249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
Weird, I can't reproduce on latest main but can on staging, and it looks like a backend error

That also happen for the create task not only the edit 
![image](https://github.com/Expensify/App/assets/19537677/629a6ed2-f6b5-4794-a238-7a7e6783981d)

**Comment by cristipaval** [comment]
cc @thienlnam as I know you've been doing changes related to tasks

**Comment by thienlnam** [comment]
Not a blocker and works as expected here - the user just does not exist

**Comment by ShogunFire** [comment]
If we are not able to assign task to people that are not users, shouldn't we at least show a user friendly message ? And if possible not make those users selectable in the list ?

**Comment by ShogunFire** [comment]
Or like call a method in the api to k ow if a user exist before creating the task

**Comment by ShogunFire** [comment]
Have you seen that comment @thienlnam 

https://github.com/Expensify/App/issues/24570#issuecomment-1679071752

**Comment by thienlnam** [comment]
> And if possible not make those users selectable in the list ?

This breaks offline handling - users will always have to be selectable

> If we are not able to assign task to people that are not users, shouldn't we at least show a user friendly message ? 

Can add a feature request to have this added, but this is more of an edge case
