### ISSUE TITLE
Web -  Tooltip and Detail View not Displayed for New user Mentionss in New Groups

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: This issue only occurs when the user creates a new account using their phone number, and User A and User B have not interacted before.
1) Create a new account for User B using a phone number (including country code) and complete the sign-in process.
2) Click on User B's profile avatar -> Profile -> Display Name and change the display name.
3) Sign in to User A's account.
4) Click the plus icon at the bottom of the screen and select "New group" to create a new group.
5) Search for User B in the group creation screen using their phone number (ensure to include the country code).
6) Select User B from the search results and click "create group."
7) In the newly created group, try mentioning User B by typing @phoneNumber (replace "phoneNumber" with User B's phone number) and select User B from the suggestion. (You won't find the User B if you try to search it by DisplayName which is @DisplayName)
8) Observe that there is no tooltip displayed when hovering over the mention, and clicking the mention does not open User B's details.

## Expected Result:
When hovering over the mention, a tooltip should appear displaying User B's avatar, display name, and phone number. Clicking the mention should open User B's details with a button labeled "message <User B>".

## Actual Result:
The expected tooltip containing User B's details, such as avatar, display name, and phone number, does not appear when hovering over the mention and the mention isn't clickable.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e504e8c9-cd3c-4199-946b-50893b2a5ebe

https://github.com/Expensify/App/assets/115492554/0934cb6d-7391-4885-ad34-9158de10dca7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Habben101

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691008439037539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Agreed - let's reopen if this is still an issue after https://github.com/Expensify/App/issues/18729
