### ISSUE TITLE
Assign Task - Creating task with user who doesn't have new dot account, error is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tab Assign task
4. Use valid email id and "Assign task" to user who doesn't have new dot account
5. Tap confirm task

## Expected Result:
The user should be able to create task
successfully

## Actual Result:
With valid email id, creating task with user who doesn't have new dot account, error " Hhm not here" is shown and unable to create task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1f54bcbc-aa36-4f26-aa43-6d368fe35a7e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is same as this issue and @thienlnam closed it as expected https://github.com/Expensify/App/issues/24570
