### ISSUE TITLE
[C+ Checklist Needs Completion] [$1000] Assign task- "From : user" shown incorrectly instead of parent report name in sub task page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap Fab
3. Tap assign task
4. Enter title and tap next
5. Select any assignee
6. Tap confirm task
7. Tap header "From: user" to note conversation header is shown correctly
8. Tap side arrow of assigned task
9. Tap plus to select "assign task" to create sub task
10. Enter title of sub task and tap next
11. Assign to Yourself
12. Tap confirm task
13. Tap header

## Expected Result:
In sub task page, in header, it should be " From: parent report"

## Actual Result:
"From : user" shown incorrectly instead of parent report name in sub task page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0cfb4e87-4158-4ff6-b9e6-0adb11e95c15

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c28bb7f1a7052b9</li>
        <li>Upwork Job ID: 1691738311944175616</li>
        <li>Last Price Increase: 2023-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 26416691</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Proposal review is up

**Comment by greg-schroeder** [comment]
bump @joelbettner to confirm proposal is g2g!

**Comment by greg-schroeder** [comment]
pinged the team to get a review here

**Comment by aldo-expensify** [comment]
I can help if @joelbettner doesn't mind.

The proposal looks fine to me!

**Comment by aldo-expensify** [comment]
hmm, seems like @StevenKKC 's assignment didn't trigger our automatic stuff

**Comment by greg-schroeder** [comment]
Thanks @aldo-expensify! Just movin a little slow it seems

**Comment by greg-schroeder** [comment]
Processing payments

**Comment by greg-schroeder** [comment]
Issue Participants:

Issue reported by: Applause
Contributor: @StevenKKC 
C+: @0xmiroslav 

Was this issue merged in time to be eligible for the speed bonus? ✅ 
Were their any regressions? ❌ 

Payment summary:

Reporter: n/a
Contributor: $1,500
C+: $1,500

**Comment by greg-schroeder** [comment]
Payment made to @StevenKKC, offer sent to @0xmiroslav. Now we just need the checklist to be completed

**Comment by greg-schroeder** [comment]
bump on checklist @0xmiroslav

**Comment by greg-schroeder** [comment]
thanks @0xmiroslav! filing regresstion test
