### ISSUE TITLE
Web - IOU - Despite the IOU request being marked as paid, users can still modify the amount, description, and date

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to "UserA's" account.
2. Open the chat with "UserB."
3. Navigate to the "Request Money" section.
4. Enter a specific amount and send the request.
5. Click on the IOU to open its detail.
6. Click on the amount field.
7. Open another browser and log in to "UserB's" account.
8. Open the chat with "UserA" and click "Pay elsewhere."
9. Return to "UserA's" account and edit the IOU amount.

## Expected Result:
After an IOU request has been paid, users should not be able to modify the amount, description, or date. The modal should automatically close upon payment

## Actual Result:
Despite the IOU request being marked as paid, users can still update the amount, description, and date

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-7

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9b495606-6bba-4afb-a480-a4bd981b6362

https://github.com/Expensify/App/assets/115492554/ae222889-57c8-4395-8387-0532762b4544

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazHussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692045463356459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Lets handle this one in here its similar https://github.com/Expensify/App/issues/24578
