### ISSUE TITLE
[HOLD for payment 2023-08-28] [HOLD for payment 2023-08-24] LNH - The conversation will be removed from the LHN if the last message is an attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24466
## Action Performed:
1. Open New Expensify app or https://staging.new.expensify.com/
2. Navigate to any conversation
3. Click the action menu in the conversation
4. Click on "Add attachment"
5. Add any valid attachment
6. Navigate to another conversation with another user

## Expected Result:
A conversation should not disappear from the LNH menu, even if the last message was an attachment

## Actual Result:
If the last message in a conversation is an attachment, that conversation disappears from the LNH menu when you switch to another conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.54.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c0f7ab0c-e042-499c-93cb-7275ab65098b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @namhihi237 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692015600197289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment]
@Nikhil-Vats's [proposal](https://github.com/Expensify/App/issues/24593#issuecomment-1679426245) looks good to me!

**Comment by mountiny** [comment]
@PauloGasparSv I dont think we have to wait for John for deploy blockers, as author of the original PR you have the best context, @Nikhil-Vats I think you can raise the PR with urgency as this is a deploy blcoker 🚀  thanks!

**Comment by PauloGasparSv** [comment]
> @PauloGasparSv I dont think we have to wait for John for deploy blockers, as author of the original PR you have the best context, @Nikhil-Vats I think you can raise the PR with urgency as this is a deploy blcoker 🚀 thanks!

Will keep this in mind for next time!!!

Sorry for the delay then @Nikhil-Vats

**Comment by mountiny** [comment]
No worries, with deploy blockers its better to act as fast as possible 🚤

**Comment by abdulrahuman5196** [comment]
@johnmlee101 Kindly assign me C+ for this issue for the payment processing.

**Comment by abdulrahuman5196** [comment]
@johnmlee101 Bump on this https://github.com/Expensify/App/issues/24593#issuecomment-1684109977

**Comment by johnmlee101** [comment]
Assigning bug so we have a bug-zero member to handle the issue management!

**Comment by zanyrenney** [comment]
Hm @johnmlee101 where is the upwork job? I don't know what you mean by this comment:
> Assigning bug so we have a bug-zero member to handle the issue management!

**Comment by abdulrahuman5196** [comment]
@zanyrenney This was a deployment blocker bug. Upwork link was not created(Not sure why)

>Assigning bug so we have a bug-zero member to handle the issue management!

AFAIK, This was meant to close the payments on this issue.

**Comment by johnmlee101** [comment]
Correct, we'll need to manage payments for this, which I don't have control over

**Comment by zanyrenney** [comment]
job is here - can't find the upwork profiles for the c and c+,, please instead apply to the job @Nikhil-Vats @abdulrahuman5196 

also the price is wrong and upwork isn't letting me change it. 

The payment summary is:

Reporting bonus - $0
Contributor payment $1000 [@Nikhil-Vats]
contributor plus payment $1000 [@abdulrahuman5196]

**Comment by zanyrenney** [comment]
I will pay the $1000 to each via upwork manually.

**Comment by zanyrenney** [comment]
hey @namhihi237 sorry i thought it said reported by internal team - Applause.

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~0162ff834c53cf26b5

**Comment by zanyrenney** [comment]
@abdulrahuman5196 - invited to job
@Nikhil-Vats - offer sent
@namhihi237 - need your upwork name.

**Comment by zanyrenney** [comment]
payment summary 
Reporting bonus - $250 @namhihi237
Contributor payment $1000 [@Nikhil-Vats] + $500 urgency bonus [PAID]
contributor plus payment $1000 [@abdulrahuman5196] + $500 urgency bonus

**Comment by zanyrenney** [comment]
@abdulrahuman5196 please can you confirm this is you on Upwork? 
<img width="304" alt="2023-09-01_16-51-13" src="https://github.com/Expensify/App/assets/56830058/68725ddf-d82e-491e-a32e-e289183f9f97">

**Comment by abdulrahuman5196** [comment]
@zanyrenney yes that's me

**Comment by zanyrenney** [comment]
Thanks! please accept the job so I can payout.

**Comment by zanyrenney** [comment]
Aall paid, see payment summary above: https://github.com/Expensify/App/issues/24593#issuecomment-1702962398

**Comment by zanyrenney** [comment]
Closing!
