### ISSUE TITLE
 Profile - "Choose file" is not an option while trying to upload photo as profile photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app New Expensify
2. Tap on the user avatar in the top right corner
3. Tap on the avatar again
4. Tap on the avatar once more
5. Tap "Upload photo"

## Expected Result:
There should be an option to choose a file, not only "Take photo" and "Choose from gallery"

## Actual Result:
There is no option to choose a file in the system, only "Take photo" and "Choose from gallery"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e9add4a2-21a7-497b-acf4-d034bd434e54

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
@lanitochka17 When looking at this within my app, I see different options then what is described in the problem statement:

![IMG_8674](https://github.com/Expensify/App/assets/10926327/36b00e6d-7771-45d6-a84b-d6012dc4ba7b)

**Comment by CortneyOfstad** [comment]
Oh, I just realized it could be because I have a photo in place. Let me see if I can remove it temporarily and recreate

**Comment by CortneyOfstad** [comment]
So that was the reason why I couldn't see that option, but I don't understand why we have to say "Select File" when selecting a photo from the gallery is the same thing. I don't think this is actually a bug @lanitochka17.

**Comment by CortneyOfstad** [comment]
@rayane-djouah I feel like when dealing with images, we should stick to gallery options only, as having "Select a File" could potentially confuse customers into thinking they can upload _any_ file type — pdf, doc, xls, etc. Within the Expensify product itself, we only allow you to select a photo as well, so this would be in-line with our other photo upload options.

**Comment by CortneyOfstad** [comment]
Started in a thread in Slack to open the discussion — https://expensify.slack.com/archives/C049HHMV9SM/p1692360864907199

**Comment by JmillsExpensify** [comment]
This is a feature request. I think we should close the issue.

**Comment by CortneyOfstad** [comment]
Agree. Closing!
