### ISSUE TITLE
[HOLD for payment 2023-08-30] Re-render the ReportActionItem when transaction is deleted

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#24608]
Following on this PR https://github.com/Expensify/App/pull/24590, once we are going to switch from using IOU report actions for the transaction dat to transaction objects which should be done here https://github.com/Expensify/App/pull/24345, we should stop hiding the `MoneyRequestView` as we do [here](https://github.com/Expensify/App/pull/24590/files#diff-53a3b5c2e20375a2d0d3a700bd76dab7791ddc968e942d510a9e06572dc0e26fR86-R91) but we should add `transaction` as props to the ReportActionItem and re-render when it changes. Deleted transaction is wiped from the onyx.

cc @dukenv0307 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195265ecd3403c746</li>
        <li>Upwork Job ID: 1692289426335956992</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by mountiny** [comment]
No need for design review here. sorry for the ping

**Comment by luacmartins** [comment]
I can work on this one

**Comment by luacmartins** [comment]
PR up - https://github.com/Expensify/App/pull/25435

**Comment by JmillsExpensify** [comment]
Nice, I see that PR was merged!

**Comment by luacmartins** [comment]
Yes, should go to prod in today's deploy

**Comment by Pujan92** [comment]
@luacmartins @mountiny Seems regression https://expensify.slack.com/archives/C049HHMV9SM/p1692729074593069 from this PR as comment structure inconsistency after edit money request.
For newly request money we are making the. comment structure as an object here 
https://github.com/Expensify/App/blob/1ec5bf4b0e63bc2c43575a4ad57753f40e4fdb9c/src/libs/TransactionUtils.js#L55
But on the edit money request we received the comment as a string in the api onyx response and that makes the inconsistency.

**Comment by luacmartins** [comment]
I think this has already been fixed [here](https://github.com/Expensify/Auth/pull/8535) already

**Comment by Pujan92** [comment]
Seems to reproduce with the open report response.

https://github.com/Expensify/App/assets/14358475/6f53fb82-f0c1-46e6-b555-4c824b5b54c7

**Comment by luacmartins** [comment]
We're currently refactoring this command. I'll check again once those PRs have been deployed

**Comment by luacmartins** [comment]
The App PR was deployed to prod 2 days ago. Updating the title with the payment date.

**Comment by garrettmknight** [comment]
@luacmartins could this be causing https://github.com/Expensify/App/issues/26205 as well?

**Comment by luacmartins** [comment]
No, I don't think that issue is related to this.

**Comment by CortneyOfstad** [comment]
So according to [this SO ](https://stackoverflowteams.com/c/expensify/questions/16949) @eVoloshchak gets paid via eChat. Has payment been received? If not, please let me know and we can get that bumped. TIA!

**Comment by eVoloshchak** [comment]
@CortneyOfstad, I just requested the payment via NewDot, thanks!

**Comment by CortneyOfstad** [comment]
@eVoloshchak just confirming if the payment was successful or not? If so, we can close this out 👍

**Comment by JmillsExpensify** [comment]
@CortneyOfstad This is missing a payment summary. I need that before I can pay via NewDot.

**Comment by CortneyOfstad** [comment]
From what I can see, Eugene was assigned to the issue on 8/17. It shows that the PR went into production on 8/22, but it shows that a QA delayed the PR going into production, so while they did not qualify for the bonus, they would not receive the penalty. 

**Payment due: $1000 to @eVoloshchak** 

CC @JmillsExpensify

**Comment by CortneyOfstad** [comment]
@JmillsExpensify @eVoloshchak was payment confirmed in NewDot? Just checking to see if this can be closed — thanks!

**Comment by eVoloshchak** [comment]
@CortneyOfstad, it wasn't confirmed yet, but I requested it, I think the issue can be closed (we can open it back again if needed)

**Comment by JmillsExpensify** [comment]
$1,000 payment for @eVoloshchak approved based on BZ summary.

**Comment by CortneyOfstad** [comment]
Looks good to close! Thanks everyone!
