### ISSUE TITLE
 Login - Animation is slightly jittery when redirected to the 2nd login validation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Account A has Account B as secondary login method but Account B is not verified.

1. Launch New Expensify app
2. Enter secondary login email in login page
3. Tap Continue

## Expected Result:
The animation below the login field is smooth

## Actual Result:
The animation is slightly jittery when user is redirected to the validation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/11c4ddaa-1073-4a62-9d7b-414c21f2eb52

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
This is pretty subtle, so I'd like to check with @Expensify/design to see if they feel this is worth fixing

**Comment by shawnborton** [comment]
Hmm I think we can probably ignore this one as it's a very minor detail. Curious if you have any thoughts though @grgia @roryabraham since you've been working with Lottie.

**Comment by roryabraham** [comment]
I think this it probably just happening because the animation is unmounting and remounting and when that happens it restarts the animation cycle. It's probably something we could fix by saving the progress of the animation in a parent component's state when the one page unmounts and passing it to the animation when the component remounts.

Or lift the animation up in the tree so it doesn't remount which (if possible) might be easier

**Comment by conorpendergrast** [comment]
It does seem like there's little to no impact of the current setup though. Unless any feels strongly, I'm going to close this as a don't fix. Any disagreement?

**Comment by shawnborton** [comment]
Works for me!

**Comment by conorpendergrast** [comment]
Closing without a fix in that case.
