### ISSUE TITLE
[HOLD for payment 2023-09-18] Incremental Onyx Updates are not applied in the correct order

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#24606]
cc @danieldoglas 

I was thinking about the way we've implemented the changes in App, and I wanted to know your opinion about possibly having data applied in the wrong order.

- B has a currentUpdateID = 1.
- A sends reportAction (with reportActionID = 1) to B (updateID 2)
- B doesn't receive that message through Pusher updates (so their currentUpdateID still 1)
- A then deletes that message. (updateID 3)
- B receives the pusher update deleting the message (updateID 3), notices that their currentUpdateID is out of date and calls GetMissingOnyxUpdates with `from: 1` and `to: 3`

I don't think we're currently holding on applying the pusher updates we received until GetMissingOnyxUpdates is done. So from my understanding, we would:

- Call GetMissingOnyxUpdates
- Asynchronously merge the collection with a reportActionID: 1 with `html: ''`  (updateID 3, that deleted the message)
- When we receive the response from GetMissingOnyxUpdate, we'll apply a merge again on the collection with a reportActionID: 1 with `html: 'previous text'`

**Comment by tgolen** [comment]
Coming from [this slack thread](https://expensify.slack.com/archives/C03SDMF9YJ2/p1692012808606819):

I think Option B is probably going to be the easiest. It would look like this:

- Gap is detected in update IDs
- sequential queue is paused
- call `GetMissingOnyxUpdates()` using `makeRequestWithSideEffects()`
- Apply the missing onyx updates from the response
- sequential queue is unpaused

**Comment by tgolen** [comment]
You can ignore this one @Christinadobrzyn and I'll be taking this.

**Comment by tgolen** [comment]
@danieldoglas I think you took over the PR so I am assigning this over to you and hiding some of the bug-zero comments

**Comment by danieldoglas** [comment]
No need to worry about it, Melvin, I'm back to it.

**Comment by tgolen** [comment]
Phooey... This is really a tough problem to crack. After digging through it
and stepping back a little, are you able to list the requirements of what
is needed? That will be helpful to me to try and create a different
solution.

**Comment by danieldoglas** [comment]
PR looks kind of ready? Tested well for me, waiting for C+ tests

**Comment by danieldoglas** [comment]
@dylanexpensify I think we need to pay @allroundexperts and @s77rt for the tests on this one. Can you help me out?

**Comment by dylanexpensify** [comment]
On it!

**Comment by dylanexpensify** [comment]
@danieldoglas confirm amounts please 🙇‍♂️

**Comment by dylanexpensify** [comment]
Payment Summary:

- Contributor+: @s77rt $1000
- Contributor+: @allroundexperts $1000

[Upwork job!](https://www.upwork.com/jobs/~01743973438f3559ba) Please apply!

**Comment by s77rt** [comment]
@dylanexpensify Applied! Thanks!

**Comment by dylanexpensify** [comment]
Offer sent @s77rt!!

**Comment by s77rt** [comment]
Accepted!

**Comment by dylanexpensify** [comment]
paid!

**Comment by s77rt** [comment]
@dylanexpensify @allroundexperts requires payment as well

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @allroundexperts based on BZ summary.
