### ISSUE TITLE
Clean up MapboxToken subscriptions when DistanceRequest unmounts

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#24612]
## Problem
As [described here](https://github.com/Expensify/App/pull/24306#discussion_r1294992585), we aren't cleaning up our Onxy.connect subscriptions, App state listener, and timeout from the MapboxToken library when the DistanceRequest component un-mounts. That's a bit of a waste.

## Solution
Clean up when the DistanceRequest component un-mounts.

**Comment by tgolen** [comment]
PR is up for this: https://github.com/Expensify/App/pull/25408

**Comment by tgolen** [comment]
Depending on the order of how things get merged...

If https://github.com/Expensify/App/pull/24306 is merged first, then the PR here will need to be updated to tie into the `unmount` of the DistanceRequest component.

If https://github.com/Expensify/App/pull/25408 is merged first, then https://github.com/Expensify/App/pull/24306 will need to be updated to use `Mapbox.stop()`

**Comment by hayata-suenaga** [comment]
> If https://github.com/Expensify/App/pull/25408 is merged first, then https://github.com/Expensify/App/pull/24306 will need to be updated to use Mapbox.stop()

https://github.com/Expensify/App/pull/25408 has been merged first. Updating [my PR](https://github.com/Expensify/App/pull/24306) to use the `stop` method to cleanup listeners

**Comment by tgolen** [comment]
This is done and all deployed.
