### ISSUE TITLE
[HOLD for payment 2023-08-28] Transaction objects for expense data are created with wrong amount

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#24610]
### Problem

The optimistically created transaction objects should have saved amounts as negative numbers in case of the linked report being an expense report.  Thats to mirror how the backend stores the data and what the server returns. Once we switch to using the transaction data here https://github.com/Expensify/App/pull/24345 this will cause problems https://github.com/Expensify/App/pull/24345

Additionally when paying money request we are incorrectly creating a new transaction and the original message is incorrect as well not matching to what the backend returns, not sure how this got through for so long 😄 

### Solution

Remove the redundant code and make sure transactions are created with negative amounts if they are linked to expense reports.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5302916f1fc46d7</li>
        <li>Upwork Job ID: 1691589432405168128</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I'll take this as part of wave3

**Comment by mountiny** [comment]
PR with fix is in a review

**Comment by mountiny** [comment]
@situchan has reviewed the PR so they should be eligible to $1000 reward (done before the pricing change)

**Comment by mountiny** [comment]
This is fixed, no need for checklist @JmillsExpensify could you please pay out @situchan $1000 for their work here, thanks!

**Comment by situchan** [comment]
@mountiny to help @JmillsExpensify, can I use additional 1k from #23280 to pay this issue, instead of refund?
cc: @maddylewis

**Comment by mountiny** [comment]
@maddylewis Can you please comment here, you have paid @situchan twice on the linked issue and that covers this issue too and then close it? just for auditing purposes

**Comment by maddylewis** [comment]
great idea! confirmed that i paid @situchan twice for this issue. we can use that extra payment for this issue! 
https://github.com/Expensify/App/issues/23280#issuecomment-1743488471
