### ISSUE TITLE
Web - Workspace - Error is appeared as a text at the bottom of Avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24617]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings
2. Click on Workspaces > any Workspace > Avatar > Avatar (Editor) > Upload smaller than 4096x4096 pixels

## Expected Result:
Error should be appeared as special error that contains full page

## Actual Result:
Error is appeared as a text at the bottom of Avatar

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bb55eb04-088c-4166-b9ab-191b0313f723

https://github.com/Expensify/App/assets/115492554/134774ad-ba22-40e9-8a2b-7c5c243326b2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691297148289289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Left a comment in the Slack thread, but I;'m not clear what the expected result is meant to be. I feel like this isn't a bug, so I'll be closing!
