### ISSUE TITLE
Web - Security - Inconsistent Use of Enter Key in Two-Factor Authentication Section

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Security > Two-Factor Authentication.
2. Hover over the "Copy" button and press Enter key. Note that it does not work initially.
3. Click on the "Copy" button once, then hover over it again and press Enter key. Observe that it works properly on the second attempt.

## Expected Result:
When hovering over the "Copy" button and pressing Enter key, the copied items should be copied properly on the first attempt.

## Actual Result:
Initially, the Enter key does not work when hovering over the "Copy" button. However, after clicking on the "Copy" button once and hovering over it again, the Enter key works properly on the second attempt.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1e4a43b7-bf2d-4647-8bdc-95ddca457ad1

https://github.com/Expensify/App/assets/115492554/4d978a7a-8e83-42e4-a3eb-786e498636ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @TewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691001716912119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joh42** [comment]
I agree with @ExGraviton, I do not think this is a bug. Nothing should happen when you press enter on the 2FA codes page, unless you have focused one of the buttons. Copying the codes on enter could be confusing, what if the user instead wanted to download them? If a user really wants to use their keyboard on this page, they could just tab to the correct button.

**Comment by kadiealexander** [comment]
I also agree with @exgraviton and @joh42, you should click or take an action to focus the selector before keyboard shortcuts  will interact with it. Closing as expected behaviour.
