### ISSUE TITLE
A failed AdHoc web build shows as successful 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#24631]
_AdHoc builds seem like a responsibility of the @Expensify/mobile-deployers team -- if anyone is interested in a good GH Actions first pick issue, please feel free to assign!_

### Problem

If the Web AdHoc build fails during the 'build web for testing', or 'Build docs' step the failiure is not reported to the parent job ([example](https://github.com/Expensify/App/actions/runs/5880867873/job/15948340024#step:7:574)). 

This is confusing. It also mean that we can't choose to only rerun the web build, all builds must be re-ran.

### Solution

Ensure the error is propagated to the parent job.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8e5e43a67e4d6fa</li>
        <li>Upwork Job ID: 1691840898921365504</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
@Julesssss I think this is an issue from github itself https://github.com/orgs/community/discussions/15452.

**Comment by b4s36t4** [comment]
There's an action here https://github.com/marketplace/actions/continue-on-error-comment which might be useful in this context.

**Comment by b4s36t4** [comment]
Cool.
