### ISSUE TITLE
Android - Request money - There is flickering for a really short time when opening Amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on Android
2. Click on plus icon > Request money > Type any number > Click on next > Choose any user > Click on Amount and you can see flickering

## Expected Result:
There should not be any flickering for a really short time when opening Amount

## Actual Result:
There is flickering for a really short time when opening Amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.50-0

**Reproducible in staging?:** Needs reproduction (Applause not able to reproduce)

**Reproducible in production?:** 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/01ad58ba-20c9-4258-88c3-b29ec3005ea3

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691157718716049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
I tested this on my Pixel 7 handset now and cannot reproduce on v1.3.54-7
