### ISSUE TITLE
[$1000] Settings Tooltip not shown when hovering over the edge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to the app
2. Hover over the edge of the profile avatar on the LHN
Notice that even if the cursor is still Pointer tooltip is not shown
## Expected Result:
The tooltip is shown when hovering over the edge and if the cursor is a pointer
## Actual Result:
Settings Tooltip not shown when hovering over the edge
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/72f0b86b-507c-4866-8c9e-c294f35fa161

https://github.com/Expensify/App/assets/38435837/70b5c582-18e6-4e47-90ce-5f97c26d3c9c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691462053076169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bd5ee6f0a60a046</li>
        <li>Upwork Job ID: 1692167268600717312</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Settings Tooltip not shown when hovering over the edge
### What is the root cause of that problem?
The Avatar component which has the tooltip is rounded, but it is wrapped with `PressableWithoutFeedback` and `OfflineWithFeedback` not rounded and have cursor pointer.
### What changes do you think we should make in order to solve the problem?
we need to apply the same border radius to `PressableWithoutFeedback` and `OfflineWithFeedback` like this
```javascript
<PressableWithoutFeedback style={{borderRadius : 20}}>
      
  <OfflineWithFeedback
      style={{borderRadius : 20}}
      contentContainerStyle={{borderRadius : 20}}>
      <AvatarWithIndicator />
  </OfflineWithFeedback>

</PressableWithoutFeedback>
```
we need to define new style `= {borderRadius : 20}` or use `styles.actionAvatar` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sophiepintoraetz** [comment]
cc @grgia because we were just talking about tooltips
![2023-08-16_18-16-49 (1)](https://github.com/Expensify/App/assets/42940078/9a819c23-1a07-4a75-8fd7-62503c7493d0)

**Comment by TTaro** [comment]
### PROPOSAL
Issues is related with how the tooltip is configured for settings, 

PressableWithoutFeedback is catching the over but is not displaying the tooltip
So we can use a explicit Tootip componente as we are doing for search

**FILE: SidebarLinks.js**

Solution : move tool tip as separate tag and not as property 

`                    <Tooltip text={this.props.translate('common.settings')}>
                    <PressableWithoutFeedback
                        accessibilityLabel={this.props.translate('sidebarScreen.buttonMySettings')}
                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                        onPress={Session.checkIfActionIsAllowed(this.showSettingsPage)}
                    >
                        {Session.isAnonymousUser() ? (
                            <View style={styles.signInButtonAvatar}>
                                <Button
                                    medium
                                    success
                                    text={this.props.translate('common.signIn')}
                                    onPress={() => Session.signOutAndRedirectToSignIn()}
                                />
                            </View>
                        ) : (
                            <OfflineWithFeedback pendingAction={lodashGet(this.props.currentUserPersonalDetails, 'pendingFields.avatar', null)}>
                                <AvatarWithIndicator
                                    source={UserUtils.getAvatar(this.props.currentUserPersonalDetails.avatar, this.props.currentUserPersonalDetails.accountID)}                                    
                                />
                            </OfflineWithFeedback>
                        )}
                    </PressableWithoutFeedback>
                    </Tooltip>`

**Comment by TTaro** [comment]
Contributor details
Your Expensify account email: valdettaro@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/albertovaldettaro

**Comment by TTaro** [comment]
https://github.com/Expensify/App/assets/4729957/69848385-3d5b-4cec-b9c2-6ebd2034e8ff

**Comment by carlosalmonte04** [comment]
## Proposal
There is an invisible layer surrounding the avatar. When hovering over this layer the tooltip shows. If we let that layer be a square instead of a circle (as it is now) we can achieve the expected behavior.

## Please re-state the problem that we are trying to solve in this issue.
Tooltip should show when hovering over the edge/corners of rounded avatar.

## What is the root cause of that problem?
Since the tooltip element shares the same style as the rounded avatar, there is no tooltip element on the edge to activate the tooltip on hover.

## What changes do you think we should make in order to solve the problem?
The tooltip element should be a transparent square as opposed to a circle.

```diff
// src/styles/styles.js
// ...
    sidebarAvatar: {
-       backgroundColor: themeColors.icon,
-       borderRadius: 20,
        height: variables.componentSizeNormal,
        width: variables.componentSizeNormal,
    },
// ...
```
This change is isolated to this element and should not produce any side effects.

https://github.com/Expensify/App/assets/25206487/9f78e716-0bc1-4f1e-b986-6bbd62c0cdd2

**Comment by carlosalmonte04** [comment]
Contributor details
Your Expensify account email: c.darioalmonte@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010e9950f7b5f0f0eb

**Comment by mollfpr** [comment]
Thank you guys, for the proposals!

@bernhardoj Even though you're right regarding the structure, the result of your solution is not quite right. The tip of the cursor is still can be hovering outside the avatar.

https://github.com/Expensify/App/assets/25520267/a3a6419d-d6dc-4319-b6d6-60b4223f1c78

@carlosalmonte04 The result is still not quite right too. The cursor is still active out of the avatar.

https://github.com/Expensify/App/assets/25520267/2d31d31e-d9df-4f26-a136-69cf38ee8fd2

@ahmedGaber93 The result of your proposal looks good, but I think we need to re-positioning the `PressableWithoutFeedback` settings pressable and the sign-in button.

@TTaro Hi! This is your first time contributing to this repo. We have a new template for posting a proposal. If you haven't, please go through the [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to learn what the process is and how to get started.

---

Let's go with @ahmedGaber93 [proposal](https://github.com/Expensify/App/issues/24650#issuecomment-1681288508).

🎀 👀 🎀 C+ reviewed!

**Comment by madmax330** [comment]
I don't think this is a bug, going to close per this slack thread: https://expensify.slack.com/archives/C01SKUP7QR0/p1692635629121469
