### ISSUE TITLE
[$1000] DEV: console error on remove image while receiver open image preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat and send a image to user
2. open a image from receiver side
3. delete image from sender side
## Expected Result: 
should not show any console error
## Actual Result: 
console error appears(Warning: Cannot update a component (`ForwardRef(BaseNavigationContainer)`) while rendering a different component)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bb1939ad-8a3b-4eee-9fc6-59be401e92f2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691473603940289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193f47de1533efa2c</li>
        <li>Upwork Job ID: 1692211170173747200</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by lschurr** [comment]
I'm not able to test since this is DEV bug. Could you confirm you can reproduce this @thesahindia?

**Comment by lschurr** [comment]
Thanks @dukenv0307! Are you able to help me try reproducing this bug?

**Comment by gadhiyamanan** [comment]
@thesahindia can you check Android or IOS native , App will crash on Android and IOS  

https://github.com/Expensify/App/assets/54790231/52263408-c28e-44c1-968a-eb48d6d6593e

**Comment by lschurr** [comment]
Bump @thesahindia

**Comment by lschurr** [comment]
Sounds like we can't reproduce this bug. Going to close.
