### ISSUE TITLE
Chat - Line marked as unread disappears after a period of time when deleting a non-final message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send about 4 message
3. Hover on last message and mark as unread
4. Hover on last message and delete message, Observe that the line mark unread is deleted as soon as the message disappears
5. Hover the first message and mark as unread
6. Hover on first message and delete message, Observed that the line mark unread is deleted after a period of time when the message disappears

## Expected Result:
Line mark unread is always deleted as soon as the message disappears

## Actual Result:
When deleting a non-final message, the line mark unread of that message disappears after a period of time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d7098a9c-da13-4d3f-8852-3d7c85194751

https://github.com/Expensify/App/assets/78819774/4e27f127-9698-4928-b2dd-4cc05caeb9d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691414998516269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
reproduced, but this is pretty minor 🙃

**Comment by greg-schroeder** [comment]
Team discussion led to consensus that we're not really considering this a bug, and we're redesigning unread markers anyways: https://github.com/Expensify/App/issues/15212
