### ISSUE TITLE
Workspace -  No "New Workspace" suggestion in FAB when pasting workspace URL without any existing workspaces

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new account and go to settings>workspace
2. Create a workspace and delete it to observe the "New Workspace" suggestion in the FAB
3. go to settings>workspace> Copy the URL of the workspace
4. Open a new tab and paste the URL without any existing workspaces
5. Observe that there is no "New Workspace" suggestion in the FAB, causing confusion for users

## Expected Result:
The FAB should suggest creating a new workspace if none exists, even when pasting a workspace URL

## Actual Result:
The "New Workspace" suggestion is missing when pasting a workspace URL without any existing workspaces

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Ye

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a2f930a1-6140-468f-b690-621ac2010a71

https://github.com/Expensify/App/assets/78819774/6904286f-a851-459d-89ed-e8c91a7e8b1f

https://github.com/Expensify/App/assets/78819774/d1f1795e-e618-4b99-9ac0-ed7cb0b43b8e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691411327638439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
I don't understand this bug! If in step 2 you are deleting the Workspace, what are you copying in step 3?

**Comment by tewodrosGirmaA** [comment]
> I don't understand this bug! If in step 2 you are deleting the Workspace, what are you copying in step 3? 

 If you want to send the URL of a deleted workspace to someone and they open that URL, the new URL suggestion is removed from the Floating Action Button (FAB) without creating any workspace.

**Comment by NicMendonca** [comment]
But why would we be sending the URL of a deleted workspace? I don't think this is a real customer use case. Going to close this one for now.
