### ISSUE TITLE
[$1000] Chat - Drag and drop attachments not working in iOS/Native

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Go to photos -> Drag and drop any image in Report screen

## Expected Result:
It should allow to drag and drop image like iOS/Safari

## Actual Result:
It doesn’t allow to drag and drop attachments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b3ecf93-12a4-4960-8e25-1ea91fa5736f

https://github.com/Expensify/App/assets/78819774/5700a9f1-cbbe-47e7-80d3-b5d4928c6b62

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691450710306939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff05e8bd6a04b889</li>
        <li>Upwork Job ID: 1693714615617826816</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
Hey @allroundexperts, I would love your opinion here as this doesn't seem to be a bug, but a feature request. Do we think we should move this forward? Thanks!

**Comment by isabelastisser** [comment]
Thanks @allroundexperts ! Internal discussion[ here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1692649752193719)

**Comment by isabelastisser** [comment]
We had an internal discussion and decided to close this issue to prioritize [this one ](https://github.com/Expensify/App/issues/24376) since this behavior might be fixed once that's settled. Thanks!
