### ISSUE TITLE
[$1000] Description appears for brief amount of time then shows error

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with same account on Two platforms
2. Platform A : Go to any chat -> Create task -> Click description (will redirect to add Description screen)
3. Platform B : Go to same chat -> Click the above created Task -> Mark as done
4. Platform A : Add/Change description-> Hit Save (See description)
## Expected Result:
 It should not show new description if there’s error
## Actual Result:
It shows new description for brief moment and disappears (revert to original)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/844935ea-65ee-4cce-9597-3afdfad1538c

https://github.com/Expensify/App/assets/38435837/795f41ac-1b6f-4762-a31b-a565024d1d8d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691451915894549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199a1f68645dc0afc</li>
        <li>Upwork Job ID: 1694009623686496256</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA seems correct and the solution makes sense. However I think we are not currently focusing on these types of issues. I have asked on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692747032695599?thread_ts=1688646398.596839&cid=C01GTK53T8Q) for confirmation. cc @kevinksullivan

**Comment by s77rt** [comment]
@dukenv0307 I have replied that thread.

**Comment by s77rt** [comment]
@kevinksullivan We are good to close this one.
