### ISSUE TITLE
Task - Task title page opens up on non-task page when copy/paste deeplink on browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open new dot
2. Create a task or select an existing task
3. Click on task title to open title update page
4. Copy link from browser which is like `https://new.expensify.com/r/5118261704486779/title`
5. Open any other char e.g. workspace
6. Paste the url in browser and hit enter
7. Task title update page opens up on non-task page

## Expected Result:
It should redirect to task page and then open up task title page

## Actual Result:
Task title page opens up on non-task page instead of redirecting to associated task page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/960d2150-8515-4c33-98df-0a22e0b06542

https://github.com/Expensify/App/assets/78819774/02fd0f03-96db-409f-8c86-a35ba7813e15

**Expensify/Expensify Issue URL:**

**Issue reported by:** @spcheema

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691407197518559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
This isn't a bug. This is how our deep linking behavior works app wide. You can have the right pane open even if the main chat doesn't relate. For example, if you're in a chat and click on the other person's avatar (to open the chat details), and copy the deep link. You can then go to another chat and paste that deep link, and we open the first chat's details in the right pane, while leaving the second chat in the main window. 

Further, in this specific example, once you edit the task title name and save, we do redirect you back to the actual task.

**Comment by joekaufmanexpensify** [comment]
Closing as this isn't a bug, but LMK if you have any other questions on this!
