### ISSUE TITLE
Assign task - Assignee email or disaply name does not show if there is no chat history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24676]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, Click + icon and select assign a task
2. Enter title and select userB for share somewhere
3. Click Confirm Task
4. From userA, select assign with whom userB do not have chat history
6. Check the assign on userB side

## Expected Result:
Should show assignee email

## Actual Result:
Does not show assignee email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/58d1efac-7dd7-4715-8ca9-1d03bc5550e6

https://github.com/Expensify/App/assets/78819774/8902544a-6e54-4c21-ab39-6f6ef3cbf05e

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691399383354089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
Seems to be fixed on dev..

**Comment by alexpensify** [comment]
Ok, with this feedback, I'm going to close. Please let me know if you disagree.
