### ISSUE TITLE
DEV: Unable to use dev tools for native devices

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the latest main on iOS/Android
2. In the metro session, press 'd'.
3. Click "Open Debugger" in the simulator.
4. Notice that an error is shown in the metro terminal.
## Expected Result: 
Debugger tools should open in the simulator
## Actual Result: 
An error is shown and none of the dev tools work.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/2d893bad-04da-4f9f-8957-ed76fa10d373)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @anjana
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691859250779659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Just coming back from sabbatical and finding someone to give me a hand testing this as I don't have a DEV environment to do so.

**Comment by situchan** [comment]
@strepanier03 confirmed reproducible. I can help review this as C+


https://github.com/Expensify/App/assets/108292595/b43ca097-befe-44ae-a1f9-411eabc0ca7d

**Comment by situchan** [comment]
Seems related to hermes

https://github.com/facebook/react-native/issues/34624
https://stackoverflow.com/questions/73665568/how-do-i-enable-debug-js-remotely-in-react-native

**Comment by strepanier03** [comment]
@cead22 - Can you please help me repro this on DEV? I do not have access and appreciate the assist very much.

**Comment by cead22** [comment]
@strepanier03 sorry but I didn't get a chance to look into this, and I'm going OOO tomorrow. Can you please remove and re-apply the engineering label to find another engineer? I can take this back over when I'm back if it's still open

**Comment by strepanier03** [comment]
Sure thing @cead22 - I hope your time off is for fun things!

**Comment by strepanier03** [comment]
@yuwenmemon - I had to reassign here. Can you please help me repro this on DEV? I do not have an environment. 

Thank you!

**Comment by strepanier03** [comment]
Hiya Yuwen? Will you have bandwidth to test this on DEV soon? If not should I reassign?

**Comment by yuwenmemon** [comment]
Let's just close this out. It's not affecting customers - the developer community/expensify can resolve it if it's truly something that needs resolving.
