### ISSUE TITLE
Android - App crashes when tapping on Amount in IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Request money from any user
3. Open IOU report
4. Tap on IOU preview
5. Tap on Amount

## Expected Result:
Amount page opens

## Actual Result:
App crashes

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/37d2ec16-01f6-4bf0-93b6-e9d6376444d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Looking into this, must be after this migration https://github.com/Expensify/App/pull/24345

**Comment by Skalakid** [comment]
@mountiny I think the app crashes because of the lack of `accessibilityLabel` inside `CurrencySymbolButton` when `disabled` is true. I propose improving the condition inside `accessibilityLabel` like: 
```
accessibilityLabel={disabled ? currencySymbol : translate('iOUCurrencySelection.selectCurrency')}
```

**Comment by mountiny** [comment]
@Skalakid Will work on this, thanks, just saw it in the console and trying to run android to confirm

**Comment by koko57** [comment]
if it's about disabled prop - [my PR](https://github.com/Expensify/App/pull/24565) should fix this one (we're removing disabling the button)

**Comment by mountiny** [comment]
Will CP the PR soon
