### ISSUE TITLE
Web - Chat - Message edits dont reflect in multiple devices in real time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login a single account into 2 devices (or use 2 browser tabs)
2. Go to the same chat and set the same message to edit mode
3. From device A, change the message draft
4. Notice in device B, the changed draft in not reflected
For context, message edit drafts are reflected in multiple devices in slack

## Expected Result:
Edit drafts should be reflected b/w devices

## Actual Result:
Edit drafts are not reflected b/w devices

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ddf6f7a5-9d34-4bb8-992c-820041cbb57b

https://github.com/Expensify/App/assets/115492554/fffa3eda-facf-4bc4-b8b2-90744fb79d48

**Expensify/Expensify Issue URL:**

**Issue reported by:** @huzaifa-99

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691393656563719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Proposal From: @huzaifa-99
## Proposal 
### Please re-state the problem that we are trying to solve in this issue.
We want the message edit drafts to be reflected b/w devices (just like slack)
### What is the root cause of that problem?
We set the draft once on `ReportActionItemMessageEdit` mount [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js#L88-L96). When we update the draft from device B it wont reflected in device A.
### What changes do you think we should make in order to solve the problem?
We should update the draft message whenever `props.draftMessage` or `props.action` change by using a `useEffect` and update the `draft` just like we set [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js#L88-L96)
```jsx
// this is just pseudocode
useEffect(() => {
    // the same as we do initially (setDraft initially)
    setDraft(() => {
        if (props.draftMessage === props.action.message[0].html) {
            // We only convert the report action message to markdown if the draft message is unchanged.
            const parser = new ExpensiMark();
            return parser.htmlToMarkdown(props.draftMessage).trim();
        }
        // We need to decode saved draft message because it's escaped before saving.
        return Str.htmlDecode(props.draftMessage);
    })
},[props.draftMessage, props.action])
```
<details>
<summary>Result</summary>
https://github.com/Expensify/App/assets/68777211/75aa252c-bae2-4ea5-a59d-82b46743041d
</details>
#### An important consideration
We set the draft to the original message [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js#L193) whenever we clear the draft message.
Since now we are listening to the onyx draft changes, whenever we clear the component draft (i.e draft state value), the original message will be set as the draft from the useEffect i suggested above. If we want to solve this we can do these things
- Option A- Update the useEffect i suggested above to not update the component draft state value whenever we clear the draft (which will use the original message value), but in this case we will have to set the original value.
- Option B- We can use some kind of placeholder value (maybe something like `__FAKE__`) instead of setting the draft to original message [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js#L193), and in use effect, we can check if the value is a placeholder (i.e `__FAKE__`) and if it is we will set the draft to empty string `''`.  This is necessary because we cannot set the draft [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js#L193) to empty string because it will make [this](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItem.js#L324) condition `false` and we will be out of edit mode. If we go with this option, we will have to use the placeholder and in useEffect add this condition `if(props.draftMessage === '__FAKE__') return ''`
**Optional**
We can remove the original state value setting, since we will can `useEffect`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by puneetlath** [comment]
This is not a bug. Drafts aren't stored on the back-end for now and are local to a given device-only.

**Comment by puneetlath** [comment]
We could, but I don't think it's particularly important that we do. I'm not sure if it's a real problem that a user would face, so I'd rather not treat it as a bug unnecessarily.
