### ISSUE TITLE
Split bill - Split bill preview displays $0.00 when viewed as split bill participant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. User A opens a group chat with User B and C
3. In the group chat, User A creates a split bill
4. Go to the group chat as User B

## Expected Result:
Split bill preview shows the correct amount

## Actual Result:
Split bill preview shows the $0.00 when viewed as the participants

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc917684caf844b2</li>
        <li>Upwork Job ID: 1692148657767686144</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This is related to https://github.com/Expensify/App/pull/24345 and its not an App deploy blocker, the split action in group chat has transaction whihc we are not returning right now from the backend, we will have to fix this internally.

**Comment by misgana96** [comment]
@luacmartins @mountiny  I reported this issue in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1692242726950869

**Comment by mountiny** [comment]
@misgana96 We knew about it from yestedy from the PR already so in these cases we would not be paying out report bonus
<img width="1021" alt="image" src="https://github.com/Expensify/App/assets/36083550/005450c8-6842-4e38-9779-cdad33eb04da">

**Comment by luacmartins** [comment]
I created [this issue](https://github.com/Expensify/Expensify/issues/308674) yesterday. I'm gonna close this issue in favor of https://github.com/Expensify/Expensify/issues/308674
