### ISSUE TITLE
 Request Money - Unexpected error requesting money message when send Request Money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with gmail+ email account
3. Click the FAB menu in LHN
4. Click on "Request money"

## Expected Result:
Amount should be sent without error message

## Actual Result:
Amount sent with error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d37d587f-a3e5-46ef-8848-07b92ac91da2

![Bug6168099_1](https://github.com/Expensify/App/assets/78819774/f418fae9-0f26-4dfe-b1d7-72c736461ed2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
Hmm, I can't seem to reproduce this, maybe it was a connection issue. I will check the logs.

**Comment by pecanoro** [comment]
I found the problem! Logs here: [7f81d45e8fbd2de8-KBP](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227f81d45e8fbd2de8-KBP%22)+AND+timestamp:[2023-08-17T11:13:11.103Z+TO+2023-08-17T13:13:11.103Z]&index=logs_expensify-023842)

**Comment by pecanoro** [comment]
This has been solved here! https://github.com/Expensify/Web-Expensify/pull/38528
