### ISSUE TITLE
Web -Changed the request to ETB NaN" is shown when When saving with out chaging the amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Request money from User A 
 3. Go to the money request report page 
 4. Click on The amount to edit 
 5. Without editing click on Save

## Expected Result:
A Massage like "changed the request to ETB NaN (previously ETB 100.00)" should not appear

## Actual Result:
A message like "changed the request to ETB NaN (previously ETB 100.00)" appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cb76efe0-1d82-4ff0-88c7-01379a526452

![Untitled](https://github.com/Expensify/App/assets/115492554/f6e3cd98-a2ba-4bf3-9bd4-d97cb41d9258)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692241546609289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@jliexpensify we only need to pay the reported here

**Comment by jliexpensify** [comment]
Payment summary

- Reporter: @daveSeife

[Upworks job](https://www.upwork.com/jobs/~0188e230ccbca01ff6)

**Comment by jliexpensify** [comment]
@daveseife are you Dawit S.? If so, can you please update your GH profile to reflect the same name as in Upworks? Cheers.

**Comment by daveSeife** [comment]
> @daveSeife are you Dawit S.? If so, can you please update your GH profile to reflect the same name as in Upworks? Cheers.

@jliexpensify Yes, I am Dawit S. Sure I will.

**Comment by jliexpensify** [comment]
Thanks, have invited you @daveSeife !

**Comment by jliexpensify** [comment]
Paid and job closed!

@mountiny - feel free to close this GH once the PR is all sorted.

**Comment by mountiny** [comment]
I think we can close as there are other issues linked to it
