### ISSUE TITLE
Chat - Can't find  profile message for pay with paypal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25394]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24175
## Action Performed:
1. Add Paypal as a payment method
2. Create a workspace
3. In your workspace expense chat, request money in USD (may require tweaking beta permissions to be able to do this)
4. Try to pay with paypal
5. Verify that the URL and the Paypal page shows the right amount in USD
6. Go to the workspace settings
7. Change the workspace's currency to JPY
8. In your workspace expense chat, request money in JPY (may require tweaking beta permissions to be able to do this)
9. Try to pay with paypal

## Expected Result:
Verify that the URL and the Paypal page shows the right amount in JPY

## Actual Result:
Can't find  profile message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a68056e8-ac5d-4f60-a93c-c9b5fa476e4a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
I want to dig into this a bit more, it's edge case so it's not an immediate priority

**Comment by mallenexpensify** [comment]
Also.. thanks @rayane-djouah for sharing the link above!

**Comment by mallenexpensify** [comment]
I _feel_ like the bug is on the Paypal side and not ours.  Or, it has to do with their API and potential limitations. 
Going to close for now.
