### ISSUE TITLE
Console Error appears when signing in with Google Sign In (Cross-Origin-Opener-Policy)

### ISSUE THREAD

**Issue by cdanwards** [Expensify/App#25427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Sign in with Google.
2. Console Error appears saying `Cross-Origin-Opener-Policy policy would block the window.postMessage call.

## Expected Result:
Describe what you think should've happened

User should be able to sign in with Google without encountering console error. However, this does _not_ prevent the user from signing in.

## Actual Result:
Describe what actually happened

User signs in successfully, but with a console error.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes. This is not a blocking issue. Only a console error appears.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [X] Android / Chrome
- [ ] iOS / native
- [X] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** TBD
**Reproducible in staging?:** TBD
**Reproducible in production?:** TBD
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
<img width="614" alt="Screenshot 2023-08-17 at 2 55 00 PM" src="https://github.com/Expensify/App/assets/8878532/197c80b5-076a-4a4a-aa59-d6b61d05bc43">
**Notes/Photos/Videos:** Any additional supporting documentation
This is likely to be an issue stemming from Google's GSI service. There is a way to fix it on the back end by specifying the `Cross-Origin-Opener-Policy` [like so](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#cross_origin_opener_policy). We anticipate to this to resolve on it's own, but to not have multiple issues being opened for this we preemptively opened this tracking issue.
**Expensify/Expensify Issue URL:** [Tracking Issue](https://github.com/Expensify/App/issues/7079)
**Issue reported by:** @cdanwards 
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
👋 @cdanwards are you taking this issue on as part of that project?

**Comment by trjExpensify** [comment]
@cdanwards @marcochavezf @0xmiroslav - tagging you all from the related project tracker on what we're doing with this issue and who's taking responsibility for it :)

**Comment by cdanwards** [comment]
@trjExpensify sorry for the delayed response! I thought it might be valuable to provide a bit more detail from the discussion on the original PR where @lindboe [explained:](https://github.com/Expensify/App/pull/23673#issuecomment-1678233645)

>>Would it be related to CSP? I remember we had an issue with the Apple cdn with the Apple sign-in, I wonder if we should add something similar

>No, it's an overly-eager verification error on Google's end. [What Google says in their docs](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#cross_origin_opener_policy) is to ensure you don't use same-origin as the value for the Cross-Origin-Opener-Policy header, and to instead use same-origin-allow-popups. The Expensify app isn't doing this, it isn't setting it at all, and the default value (unsafe-none) is [more permissive than all of the options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy#directives). So the client library is erroneously warning this won't work because it's not set to same-origin-allow-popups, but unsafe-none will allow everything same-origin-allow-popups does and more.

>I've looked for how to try to report this bug to Google but have not found anything.

>We could add the header and change it to same-origin-allow-popups like we did with CSP, and that would fix the warning, but it could potentially break something else.

We've also noticed that even since that discussion the Google docs have continued to change regarding [COOP](https://infinitered.slack.com/archives/D03THFALA7J/p1692731773737619). 

Ultimately, Expensify is currently set up with a policy that is less restrictive than Google suggests, but adding more restrictions might inadvertently break other features.

**Comment by trjExpensify** [comment]
Thanks, @cdanwards. 

So my read is that this is a `new feature` and the project team are keeping ahold of it. As such, I'm going to assign it to Marco and mark is as `internal`. If you are moving this on to work on, feel free to assign me back to it.

**Comment by marcochavezf** [comment]
No update, keeping it as weekly since it's not a blocker

**Comment by marcochavezf** [comment]
No update, focused on wave7

**Comment by marcochavezf** [comment]
No update, focused on wave7 and traveling back from Offshore

**Comment by marcochavezf** [comment]
No update, wrapping up other priorities for wave7

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
Closing it for now since it's not impacting the app functionality or users.
