### ISSUE TITLE
Prevent the swipe event on MapView to be bubble up to outer components

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25422]
[Fix this issue](https://github.com/Expensify/App/pull/24306#issuecomment-1681219598)

**Comment by neil-marcellini** [comment]
I'm closing this since it's a duplicate of https://github.com/Expensify/App/issues/25732

**Comment by hayata-suenaga** [comment]
@neil-marcellini These are actually separate issues 🙇

**Comment by hayata-suenaga** [comment]
external issue was created for the same bug so closing this one in favor of [this one](https://github.com/Expensify/App/issues/26435)
