### ISSUE TITLE
Split bill - Split bill details page shows inactive fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap workspaces
4. Tap new workspace
5. Edit the workspace name and save
6. Tap members
7. Invite many members
8. Tap 3 dots of newly created workspace and go to #announce room
9. Tap plus icon to select split bill
10. Enter any amount
11. Tap split bill
12. Tap on the split bill box in conversation
13. Tap show more

## Expected Result:
There should not be inactive fields in split bill details page

## Actual Result:
Split bill details page shows inactive fields like date, amount, description etc

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.55-1
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ac131587-bea3-461c-979f-8eaf92e43e25

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
I think that's intended for amount and description when you have already comfirmed the split, in the code it's disabled if didConfirm is true , in the code there is this comment though for date and merchant:

> // Note: This component is disabled until this field is editable in next PR

That was made by that PR 3 weeks ago: https://github.com/Expensify/App/pull/23648

**Comment by anmurali** [comment]
What is the expected outcome here? We want the person that split the bill to be able to come back later and add these fields they originally didn't fill out? @lanitochka17

**Comment by lanitochka17** [comment]
@anmurali At least to be able to change the Description

**Comment by anmurali** [comment]
Still waiting for a response from @lanitochka17

**Comment by lanitochka17** [comment]
@anmurali My answer was above:
At least to be able to change the Description

**Comment by anmurali** [comment]
So to clarify in this video - the split bill itself cannot be edited to add a description. But the individual IOUs created from that split bill can be edited. You are saying the split bill should be editable? 

https://github.com/Expensify/App/assets/14225673/8da7258e-7502-4514-9376-bb5f782a8386

@lanitochka17

**Comment by anmurali** [comment]
Going to close this. @lanitochka17 please open when you respond.
