### ISSUE TITLE
Android - Task - Error page shows when tap Back from task assigned to user without account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB > Assign Task > Enter title and description and navigate to next page
3. Click on Assignee
4. Enter a email that doesn't have a NewDot account yet
5. After landing on Task conversation tap Back button

## Expected Result:
User should be navigated to Home page or to page where he was before creating the Task

## Actual Result:
Error page is displayed when navigate Back from task assigned to user that doesn't have a NewDot account yet
Hmm... it's not here
You don't have access to this chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.55-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/97fda447-fbf4-4310-8a81-0f553cde7efd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01181584852e04246e</li>
        <li>Upwork Job ID: 1692575998136582144</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

**Comment by tgolen** [comment]
I can look into this, but I have other things that are higher priority so I am dropping this to weekly.

**Comment by CortneyOfstad** [comment]
Any updates @tgolen? TIA!

**Comment by CortneyOfstad** [comment]
I know @tgolen is OoO today, so no update available, but will be back Tuesday of next week (Labor Day in the US) 👍

**Comment by tgolen** [comment]
I am not able to reproduce this. When I enter an email of an account that doesn't exist, there is no option for me to select it, so I cannot trigger the error.

![image](https://github.com/Expensify/App/assets/1228807/50b23976-17a5-4723-9c60-e810eaf97274)
