### ISSUE TITLE
[HOLD 309451] Rewrite `setup-mapbox-sdk.sh` in Node for better cross-platform support

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25442]
cc: @neil-marcellini 

We have bash scripts for configuring the credentials that are needed to download Mapbox SDKs. Rewrite the scripts in node to make them platform agnostic.

**Comment by mananjadhav** [comment]
I can help with the review if needed.

**Comment by hayata-suenaga** [comment]
> I can do the conversion if needed.

nice! I'll assign you to this issue then 🚀

**Comment by hayata-suenaga** [comment]
@allroundexperts Because I'm re-writing the script to call an endpoint in our backend to obtain a temporary Mapbox token (instead of requiring each contributor to create a Mapbox account and obtain a token), I gonna go ahead and do the re-write in Node/TypeScript here [in this PR](https://github.com/Expensify/App/pull/25545).

I gonna un-assign you because we no longer need a separate PR for this 🙇

**Comment by hayata-suenaga** [comment]
@allroundexperts assigned you [here](https://github.com/Expensify/App/pull/25545)

**Comment by hayata-suenaga** [comment]
I'm closing this because this issue is taken care of by [this PR](https://github.com/Expensify/App/pull/25545).

**Comment by hayata-suenaga** [comment]
@anmurali please issue a payment of $250 to @allroundexperts for their review of [this PR](https://github.com/Expensify/App/pull/25545) (although the PR was closed, they reviewed the PR and should get a partial payment)

**Comment by JmillsExpensify** [comment]
$250 payment approved for @allroundexperts based on comment above.

**Comment by hayata-suenaga** [comment]
waiting for the payment to be accepted

**Comment by hayata-suenaga** [comment]
We're not doing this for now as there hasn't been issue from contributors on this

**Comment by hayata-suenaga** [comment]
forgot to close this one
