### ISSUE TITLE
[HOLD for payment 2023-08-30] [$1000] Date is incorrect after editing money request

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25441]
cc @mountiny 

## Action Performed:
1. Request money from another user
2. Edit the money request date
3. Verify that the selected date is incorrect after you tap `Save`

## Expected Result:
Date is correct

## Actual Result:
Date is incorrect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/22219519/0d14c8bc-a837-4d4e-beb9-6c89e2d86668

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154a57cff1cce910b</li>
        <li>Upwork Job ID: 1692296957389250560</li>
        <li>Last Price Increase: 2023-08-17</li>
<li>Automatic offers: </li>
<ul>
<li>ShogunFire | Contributor | 26196211</li>
</ul></li>
    </ul>
</details>

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After editing a money request the date is incorrect

### What is the root cause of that problem?

The root cause is that we are not subscribed to changes in the transaction in onyx so the changes don't appear immediatly

### What changes do you think we should make in order to solve the problem?

We should subscribe to the change of the transaction with withOnyx

### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment]
I don't reproduce the issue but I reproduce another one: the date not updated until refresh so that's what my proposal is about

**Comment by mountiny** [comment]
Wow nice @ShogunFire 

> We can also pass the date with a format that avoid this weird behaviour, for example we can transform our string like this yyyy/mm/dd by replacing - with /

I think this is interesting but just curios if there is anything else we can use without some special treatment. Is there some param we can pass to the Date() maybe? Or use something from the date-fns? cc @waterim

**Comment by waterim** [comment]
@ShogunFire can you please provide the string which is going to the new Date()?

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
After editing a money request the date is incorrect
### What is the root cause of that problem?
timezone issue
### What changes do you think we should make in order to solve the problem?
instead of getting hard string API we can get utc format and locally we can convert the local date
 currently we are using `modifiedCreated`
![Screenshot 2023-08-18 at 4 48 04 AM](https://github.com/Expensify/App/assets/16595846/f234a007-5831-4c00-942c-fd57646ffaa2)

**Comment by waterim** [comment]
@ShogunFire you can try date-fns format() function to format the string

**Comment by mountiny** [comment]
I think its `2023-08-18` for example, whatever the DatePicker component returns.

**Comment by pradeepmdk** [comment]
@waterim already we are formatting https://github.com/Expensify/App/blob/main/src/libs/TransactionUtils.js?#L176

**Comment by ShogunFire** [comment]
I am trying with parse from date-fns

**Comment by waterim** [comment]
@ShogunFire for timezones try date-fns-tz format

**Comment by ShogunFire** [comment]
Ok so the parse function works well for date alone but in some cases it looks like we also have the time so it doesn't work, Maybe we can try two times to parse ?

**Comment by pradeepmdk** [comment]
can any one clarify me `modifiedCreated` or `created` or any other time coming from api its converted to user localtimezone?

**Comment by ShogunFire** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/25441#issuecomment-1683061352)

Seems to work well with parseISO method

**Comment by ShogunFire** [comment]
@pradeepmdk The date that comes from the api is the date that we sent to the api so it is supposed to be local, the issue is it's not

**Comment by waterim** [comment]
@ShogunFire yes, parsoISO is nice one, to prevent any local offsets adding

**Comment by ShogunFire** [comment]
By the way there is also a problem with the refresh of the date field, should we handle it here ?

**Comment by JmillsExpensify** [comment]
Taking this one as part of wave3

**Comment by ArekChr** [comment]
The date for the money request should not include a timezone, as this might disrupt the older versions of the app. Parsing the date into an ISO format should address this concern.
The [proposal](https://github.com/Expensify/App/issues/25441#issuecomment-1683061352) by @ShogunFire looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by mountiny** [comment]
I will take this one over from Carlos, I hope he wont mind

@ShogunFire are you able to create the PR today please? thanks!

**Comment by ShogunFire** [comment]
> @ShogunFire are you able to create the PR today please? thanks!
Yes I am doing it now, I have troubles to build android though but I will try again

**Comment by luacmartins** [comment]
Just to be clear, this is not an issue with the subscriber. We're already fixing that [here](https://github.com/Expensify/App/pull/25435).

**Comment by mountiny** [comment]
Yep, mentioned in the PR

**Comment by mountiny** [comment]
Its not an issue, its design, the user says this happened on the 18th August they put it into 18th August transactions bucket. the timezone does not matter at this scenario

**Comment by mountiny** [comment]
This seems to be still failing but its backend issue not issue with the linked PR

**Comment by ShogunFire** [comment]
I think there might be some paiement to do here @JmillsExpensify

**Comment by ShogunFire** [comment]
Friendly bump @JmillsExpensify

**Comment by sophiepintoraetz** [comment]
Confirming that the payment due to @ShogunFire (Pierre M) is $1500 [here](https://www.upwork.com/nx/wm/workroom/34677103/overview), correct? @JmillsExpensify @mountiny?

**Comment by mountiny** [comment]
@sophiepintoraetz that is correct, thanks for helping

**Comment by sophiepintoraetz** [comment]
Payment done - is there anything else keeping this issue open?

**Comment by JmillsExpensify** [comment]
Ah so sorry for the delay on this one. Don't hesitate to reach out to me via New Expensify DM.

**Comment by JmillsExpensify** [comment]
In any case, @ArekChr I don't see a BZ checklist completed for this issue? Do you mind completing one, including whether a regression test is required? Thank you!

**Comment by ArekChr** [comment]
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by JmillsExpensify** [comment]
Great thank you! All done here.
