### ISSUE TITLE
[HOLD Expensify 309451] Add instruction to manually setup Mapbox SDK credentials

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25452]
In `README`, an instruction on how to setup Mapbox SDK credentials manually in case `setup-mapbox-sdks.sh` doesn't work.

Context: https://github.com/Expensify/App/pull/24306

**Comment by neil-marcellini** [comment]
I put a hold on the issue title since we're holding the PR on that issue.

**Comment by hayata-suenaga** [comment]
We're closing this as we're not deploying the Token fetching script
