### ISSUE TITLE
Web - Chat - Inconsistency: unable to react when editing a message but able to react if there is a previous reaction for the message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. open any chat room from LHN
3. hover on the message if there is a message or create a message and hover on it
4. click the edit icon
5. try to react to the message
6. repeat steps 3-5 for the previously reacted message

## Expected Result:
React for a message when editing should be consistent.

## Actual Result:
Inconsistent when reacting to a message when editing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f128957a-c048-4da8-9cfc-cb8068393d29

https://github.com/Expensify/App/assets/115492554/6dd82f23-e53f-46fe-95a2-13883410a67d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691504644603889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I'm finding the message reaction behavior to be consistent 🤔. But also, I think this is very edge case -- realistically, no one is going to be trying to simultaneously edit and reacji in rapid succession like that.
