### ISSUE TITLE
[HOLD for payment 2023-09-29] [Performance] Improve SidebarLinks by caching getOrderedReportIDs

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25467]
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690893504971379)

[Performance] Improve SidebarLinks:

### Problem
Now all the Records to show on LHN are being calculated multiple times and the logic to fill it is complex, this one is a bit trickier to solve but I think it worth it

### Solution 

Summary

getOrderedReportIDs is a complex function that would be good to re-architecture.
Applying just caching like I did, isn’t the full solution, it gives me a good number to know if worth taking the time to improve it, and even if we aim to get ~40% to ~50% of improvement will be awesome

**Comment by mountiny** [comment]
Asking in callstack room who will take these on

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this one

**Comment by mountiny** [comment]
Making this daily as the getOrderedReportIDs is one of the main offenders when it comes to performance for accounts with thousands reports

**Comment by mountiny** [comment]
@waterim What are the next steps here?

**Comment by waterim** [comment]
@mountiny will update you tomorrow, mostly performance here will be improved with caching, because just 1 filter in this function is taking 90% of the whole time and its impossible to optimize this one significantly, but caching is saving a lot of time. 
One more thing I just started: removing some unnecessary sorts, after a discussion in Slack.

**Comment by mountiny** [comment]
thanks for an update

**Comment by mountiny** [comment]
Any updates here?

**Comment by waterim** [comment]
@mountiny yes, have a progress, will open a PR today

**Comment by waterim** [comment]
@mountiny My update:
I added caching, improved the code base with removing undrescore and lodash.
But one tricky heavy thing still here, I had few calls with Eduardo and playing with a kind of "leetcode" trying to optimise the filter function which is taking another filter function and has n^2 complexity.
For now we have this filter: 
`const reportsToDisplay = Object.values(allReportsDict).filter((report) =>
        ReportUtils.shouldReportBeInOptionList(report, currentReportId, isInGSDMode, betas, policies, allReportActions, true),
    );`
And shouldReportBeInOptionList function has:
`const lastVisibleMessage = ReportActionsUtils.getLastVisibleMessage(report.reportID);`
And this lastVisibleMessage calculation is taking 0.2ms for each iteration(which is really heavy for a filtering)
And Im trying to optimise somehow the way we are getting lastVisibleMessage here

**Comment by mountiny** [comment]
thanks for the update

**Comment by mountiny** [comment]
Waterim has a PR up, @waterim do you think it will be ready for a review soon? I could make an adhoc build for testing

**Comment by waterim** [comment]
@mountiny its ready, but some random tests are failing.. Trying to find a root cause, when its ready I will ping you

**Comment by waterim** [comment]
@mountiny Hey Vit, PR is ready for a review :)

**Comment by mountiny** [comment]
Thanks for an update

**Comment by mountiny** [comment]
No checklist required, this is a performance improvement

@parasharrajat is due $500 for internal review

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - N/A 
-  Contributor+ that helped on the issue and/or PR - @parasharrajat $500 

Upwork Job: N/A 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: See the notes here - https://github.com/Expensify/App/issues/25467#issuecomment-1743782474

@parasharrajat please request a payment in Chat and then we can close this out. Thanks!

**Comment by alexpensify** [comment]
Ok, going to close out here.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on BZ summary.
