### ISSUE TITLE
[HOLD for payment 2023-09-21] [Performance] Improve translations

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25466]
[Performance] Improve translations, coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690893489960149)

### Problem

Translations uses lodashGet which adds some overhead + translations are being called multiple times (some makes sense because of rerenders)

### Proposal
We use lodashGet to get the key, so instead of

### Summary of solution 
Will remove the need of using lodashGet and its extra overhead,
We need to make sure all translations uses the HOC: withLocalize or the hook: useLocalize or at least going through: Localize.translate

**Comment by mountiny** [comment]
Asking in callstack room who will take these on

**Comment by BeeMargarida** [comment]
Hey, as mentioned in the slack, I'll be taking over this one 👋

**Comment by mountiny** [comment]
Thanks

**Comment by BeeMargarida** [comment]
PR to fix regressions is ready: https://github.com/Expensify/App/pull/27358

**Comment by mountiny** [comment]
We can close this now, thanks! The reviewer was from Callstack
