### ISSUE TITLE
mWeb - Emoji - "eye_speech_bubble" emoji has a different look on mWeb

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND on mWeb
2. Open any chat
3. Write a colon and "eye_speech_bubble" and end it with a colon and send it
4. Do step 2 and 3 on desktop and compare the emojis that show up on both

## Expected Result:
The two emoji's should be the same

## Actual Result:
The emoji on mWeb is different from the emoji on desktop or android. The emoji on mWeb is a double emoji

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4b20ef05-2b31-4e88-b334-75c64e6327bf

https://github.com/Expensify/App/assets/115492554/1b334579-fc2e-4bc3-b5b4-61421f954ef9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @NathanMulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691497957724559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
This is not a bug ig
It's just different designs for different OS
https://emojipedia.org/eye-in-speech-bubble#designs

**Comment by Nathan-Mulugeta** [comment]
It is the same OS, Android.

**Comment by shubham1206agra** [comment]
Yes but its just their renderers are different which causes them to change

**Comment by shubham1206agra** [comment]
can you check sending the same emoji from web and try to see on the native app

**Comment by anmurali** [comment]
Looks exactly the same

mWeb
<img width="516" alt="image" src="https://github.com/Expensify/App/assets/14225673/8527e732-6a39-48cb-9762-42bae279f3ef">

Desktop app
<img width="918" alt="image" src="https://github.com/Expensify/App/assets/14225673/a2074235-5b68-43b8-8346-5a70c2c97d85">
