### ISSUE TITLE
The paid message flickers with negative amount in case of expense report

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from here

## Action Performed:
Break down in numbered steps

1. User B requests money in a workspace chat.
2. As User A, open the IOU preview.
3. As User A, select Pay elsewhere.
4. Note that the amount in the paid message briefly shows negative value for a while

## Expected Result:
Describe what you think should've happened

The amount should be same as the expense report total

## Actual Result:
Describe what actually happened

The amount flickers with negative value

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43995119/dd8fb478-a800-426b-bf12-7ccf85adc523
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
PR is up

**Comment by jliexpensify** [comment]
Hi @mountiny are we paying Rajat here? He's not on the linked PR. Cheers!

**Comment by mountiny** [comment]
He is on this one https://github.com/Expensify/App/pull/25474 

$1000 to @parasharrajat is all to be paid here.

**Comment by jliexpensify** [comment]
Is this correct for Payments?

- C+: @parasharrajat $1000 + $500 (speed bonus, merged in 1 day) - to request in New.Dot

**Comment by mountiny** [comment]
yes

**Comment by jliexpensify** [comment]
Cheers, updated above for @JmillsExpensify to pay. Feel free to close this out Vit, nothing for me to do.

**Comment by jliexpensify** [comment]
@mountiny we can close this one right? Payment is completed!

**Comment by mountiny** [comment]
yes
