### ISSUE TITLE
Admins- Guide message and avatar overlaps the own message in admin sroom in landscape view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in landscape view
2. Sign In/Up
3. Create a new Control or collect policy in web
4. Open admin report (conversation) in LHN
5. Lock the device
6. Unlock the device

## Expected Result:
Report (Conversation) messages should be properly displayed in the admins room

## Actual Result:
Guide message and avatar overlaps the own message in landscape view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] IPAD / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-1

 **Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0bd849ca-17b2-403d-a4ab-83a8fc423ad4

![Bug6169133_IMG_857F40379E52-1](https://github.com/Expensify/App/assets/78819774/8fb494ac-ef79-4a1c-a8fa-dd157cd21884)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
It looks like a similar issue was reported and being worked on here https://github.com/Expensify/App/issues/25648

**Comment by tjferriss** [comment]
@lanitochka17 can you test on staging to see if this issue is still appearing?

**Comment by lanitochka17** [comment]
Issue reproducible with Build 1.3.57-2
iPad Pro 11" 2020/ iPadOS 15.7


https://github.com/Expensify/App/assets/78819774/9341add2-f0b2-413e-9e2e-97a204853d2a

**Comment by tjferriss** [comment]
It looks like the changes were just pushed to staging yesterday https://github.com/Expensify/App/issues/25648#issuecomment-1696122291

Can you test again now on staging?
