### ISSUE TITLE
[$1000] Web - On Task Details, the title Section shows hovered effect even though the cursor is on the description.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App > Press FAB > Assign Task > Create Task
2. Press the check icon on Title to complete the Task
3. Uncheck the checkbox icon to reopen the task
4. Observe the hover state of the Title section

## Expected Result:
The Title section should not show the hover effect if the cursor is on the Description section.

## Actual Result:
Clicking on uncheck will shift the hover to Description, but still, Title Section shows the hover effect(green background)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/55816fd5-4be8-4e74-89f7-f53fc6a305bb

![hovered-state-stuck](https://github.com/Expensify/App/assets/115492554/70cc2f31-3afc-4e1e-981f-c8400a53d71e)

https://github.com/Expensify/App/assets/115492554/060320be-86a5-498c-8961-bfc90f00ddb3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jayeshmangwani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691523409931269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efa6edb4c1b8dea5</li>
        <li>Upwork Job ID: 1692554827389550592</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

**Comment by getusha** [comment]
Looks like dupe https://github.com/Expensify/App/issues/16923
cc @parasharrajat

**Comment by DylanDylann** [comment]
Agree that It dupe

**Comment by jayeshmangwani** [comment]
@parasharrajat Yes it's reproducing on my side

https://github.com/Expensify/App/assets/35371050/ede23d7f-20d6-4872-b7b0-5341de6bd5b1
