### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Show all selection options when clearing a search input selection field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

https://expensify.slack.com/archives/C049HHMV9SM/p1692369698847549?thread_ts=1691489722.039289&cid=C049HHMV9SM

We have determined that all push to page inputs (except pronouns page) will follow the pattern used by the date picker:

<img src="https://github.com/Expensify/App/assets/38015950/2f75fd8f-269c-4066-8510-93df87e4932e" width="200">

This means that we will
- display all options
- search to filter options

This affects the following selections (may not be a complete list):
- Country Selection 
     - Click on settings > Profile > Personal details > Home address > Country > Clear the country
- US State Selection
     - Click on settings > Profile > Personal details > Home address > State (must have US selected as Country)

## Action Performed:
1. Open website
2. Click on settings > Profile > Personal details > Home address > Country > Clear the country that is here and you see that countries are not shown even clearing search country field
## Expected Result: 
Countries should be shown when clearing search country field
## Actual Result: 
Countries are not shown when clearing search country field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-07T151534.742.webm](https://github.com/Expensify/App/assets/43996225/75e72110-c676-4ce0-a854-1fc15acced05)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691489722039289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8624994d9a4175e</li>
        <li>Upwork Job ID: 1692558937839087616</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26364865</li>
<li>mahmudjontoraqulov | Reporter | 26364868</li>
</ul></li>
    </ul>
</details>

**Comment by grgia** [comment]
@anmurali we [discussed this bug](https://expensify.slack.com/archives/C01GTK53T8Q/p1692368313911709) this morning and determined that we will be standardizing the pattern for inputs 

https://expensify.slack.com/archives/C049HHMV9SM/p1692369698847549?thread_ts=1691489722.039289&cid=C049HHMV9SM

As a conclusion, we determined that all push to page inputs (except pronouns page) will follow the pattern used by the date picker:

This means that we will
- display all options
- search to filter options

<img src="https://github.com/Expensify/App/assets/38015950/2f75fd8f-269c-4066-8510-93df87e4932e" width="200">


I will be updating the description of this bug to include all affected inputs

**Comment by s-alves10** [comment]
@grgia 

Is this an internal issue?

**Comment by binary3oul** [comment]
@grgia  Do you mean all search input selection field not only Countries field? correct?

**Comment by anmurali** [comment]
Bumped @grgia

**Comment by grgia** [comment]
sorry for the delay, @allroundexperts 

> That means we should reset searchValue to empty whenever we open the picker again and init focus to selected option like YearPicker.

yes

> Do you mean all search input selection field not only Countries field? correct?

yes, except for the pronouns selector

**Comment by grgia** [comment]
@anmurali looks like this one's ready for payments. @allroundexperts bump on BZ checklist

**Comment by grgia** [comment]
@allroundexperts regression steps LGTM. @anmurali could you check off payment?

**Comment by grgia** [comment]
@namhihi237 yes, considering no changes, this is still eligible for payment. cc @anmurali

**Comment by grgia** [comment]
bump @anmurali

**Comment by anmurali** [comment]
Bug reporter @MahmudjonToraqulov ($250). Contributor @namhihi237 ($1000+$500 speed bonus) paid on Upwork.
Contributor plus @allroundexperts ($1000+$500 speed bonus) approved to be requested and paid on New Dot.

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @allroundexperts based on BZ summary.
