### ISSUE TITLE
Android build times are very slow

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#25501]
## Problem
If you run `npm run android` the build time is very very slow. This is because we are required to build React Native from source to support two patches:

We have two patch files which implement/fix things on Android side, NumberOfLines.patch and VerticalScrollBarPosition.patch. When we have Android patches, it’s necessary to build from source to ensure these patches take effect in the application.

**`NumberOfLines.patch`**
Related to these PRs: https://github.com/facebook/react-native/pull/35703 and https://github.com/facebook/react-native/pull/38021
It’s necessary to fix this issue: https://github.com/Expensify/App/pull/19809

**`VerticalScrollBarPosition.patch`**
Related to these PRs: https://github.com/facebook/react-native/pull/38071 and https://github.com/facebook/react-native/pull/38073
It’s necessary to fix this issue: https://github.com/Expensify/App/issues/11321

**`VerticalScrollBarPosition.patch`** is merged and are available in RN 0.72.4 :tada: -> https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0724. Once we update to this version or higher we can remove this patch.

Here’s more info about all the PRs we have and current state: https://github.com/Expensify/App/pull/18507#issuecomment-1621573098

## Solution
1. Get **`NumberOfLines.patch`** merged and deployed
2. Update to a version of React Native containing both patches which prevents needing from building from source.

**Comment by AndrewGable** [comment]
In contact with @Szymon20000 on his upstream PRs, we are specifically targeting this iOS PR for `numberOfLines` prop first: https://github.com/facebook/react-native/pull/38021

Then will be opening a new PR for Android fixes for `numberOfLines`. Once both of these PRs are merged we should be able to update to the version that includes these PRs.

**Comment by AndrewGable** [comment]
We decreased this down to ~5 minutes and sped up the build by 3x with this PR: https://github.com/Expensify/App/pull/25757

We will continue to look into the patches, but for now Android seems to be at an acceptable build time.

**Comment by jamonholmgren** [comment]
@AndrewGable Could you build custom 3rd party native components that have this behavior rather than building the whole RN from source? (I haven't looked in depth at this yet, but that's the first thing that comes to mind for me.)

**Comment by jamonholmgren** [comment]
FYI, https://github.com/facebook/react-native/pull/38021 won't be merged, per core team.

**Comment by AndrewGable** [comment]
We've been discussing alternatives internally, we will keep you updated!
