### ISSUE TITLE
Web - Both account's avatar is not being shown on the receiver side of the IOU

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request from account A to account B
2. Observe the IOU preview component from account A and compare it with the IOU preview component of account B

## Expected Result:
Both the IOU preview components should contain both account A's and account B's avatars

## Actual Result:
Only the IOU preview component on account A's side contains both avatars.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691577095714419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
I didn't have time to review this today, on my to-do list for tomorrow.

**Comment by isabelastisser** [comment]
This behavior has been raised [here](https://github.com/Expensify/App/issues/25509), and the team is currently discussing if this is a design choice that needs to be changed. Closing!

**Comment by Nathan-Mulugeta** [comment]
Bump @isabelastisser can you check the above comment? And the issue you have linked has been closed.

**Comment by isabelastisser** [comment]
Based on [this ](https://github.com/Expensify/App/issues/25509#issuecomment-1693672295) comment, this doesn't affect functionality and it seems to be a design choice that won't be fixed now. Thanks!
