### ISSUE TITLE
[$500] Assign Task - "Auth EditTask returned an error" When Changing Assignee for Completed Task in Different Tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Task"
2. Add a title, assignee, and share location, then confirm the tasks
3. Click on the assignee to open the detail page on the right side. Copy the URL and open it in a new tab
4. Check the checkboxes to mark the tasks as completed. Go to the new tab and change the assignee
5. Observe that the error message "Auth EditTask returned an error" occurs when attempting to change the assignee for a completed task in a different tab

## Expected Result:
Changing the assignee for a completed task in a different tab should not result in the error message "Auth EditTask returned an error"

## Actual Result:
When changing the assignee for a completed task in another tab, the error message "Auth EditTask returned an error" occurs, indicating an inconsistent behavior in the application

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bd0066b9-07fc-450f-8669-1553fb7eaeba

https://github.com/Expensify/App/assets/78819774/dac52c51-9d94-4510-836e-9ed94f170539

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691587156607839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c61bf34950d5e79b</li>
        <li>Upwork Job ID: 1716878857101721600</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I think we should put this on hold for https://github.com/Expensify/App/issues/24661

**Comment by JmillsExpensify** [comment]
Agreed. Doing that now.

**Comment by JmillsExpensify** [comment]
And...did that for real now

**Comment by JmillsExpensify** [comment]
Still on hold for related Auth issue.

**Comment by JmillsExpensify** [comment]
Opening this back up now that the Auth PR is out

**Comment by burczu** [comment]
@JmillsExpensify @BhuvaneshPatil I can confirm it is not reproducible anymore - after marking the task as completed, on the other tab the 404 error page (`Hmm... it's not here`) is shown in the right sidebar, which I think is correct behaviour.

**Comment by burczu** [comment]
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment]
Issue no longer reproducible. Closing.

**Comment by tewodrosGirmaA** [comment]
@JmillsExpensify  am I eligible for payment?
