### ISSUE TITLE
[$1000] IOU - Data inconsistency when reacting with an emoji to a message request for money paid elsewhere

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. First login to different accounts with two different users, one as user A and the other as user B.
2. User A start chat with user B
3. User A click plus sign and select Request money
4. User A write a number, click Next button and click Request button
5. User A and user B click on the money request message
6. User B click Pay elsewhere  button
7. User A react to the money request message with an emoji

## Expected Result:
It should show of user A's reaction to user B

## Actual Result:
 Does not show the reaction

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e9d16d78-1322-41a2-a523-4dabe39c3924

https://github.com/Expensify/App/assets/78819774/93720497-4972-4215-a985-4186ff7cdf95

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Mauri-salazar

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691599471618619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e902051fcfbfe3f</li>
        <li>Upwork Job ID: 1696692278831202304</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by ShogunFire** [comment]
I don't reproduce 

https://github.com/Expensify/App/assets/19537677/c3c247bc-a2f6-4974-ad56-2c35c5522911

**Comment by Mauri-salazar** [comment]
Excuse me, if it is reproducible in the latest version, you need to follow the steps. 


https://github.com/Expensify/App/assets/106186325/b6922a7a-2ee2-480b-8f98-b8906945270c

**Comment by Mauri-salazar** [comment]
Contributor details
Your Expensify account email: salazar.mauricio.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011516959d97dcaeaa

**Comment by ShogunFire** [comment]
@Mauri-salazar I followed the steps and staging is not the latest version. Maybe it's reproductible but for me it wasn't.

**Comment by Mauri-salazar** [comment]
Yes excuse me, to be exact, is 
reproducible in incognito of staging v1.3.55-7

**Comment by mallenexpensify** [comment]
NewDot is a lil buggy/super slow for me so I'm having trouble testing right now. I think I was able to reproduce the issue but it also took a minute for a new chat from A to show up for B :(   
Will review again soon.

**Comment by mallenexpensify** [comment]
Was able to reproduce
<img width="1423" alt="image" src="https://github.com/Expensify/App/assets/22508304/666fb5d4-8208-4992-b5a2-562db2850110">

**Comment by mallenexpensify** [comment]
Awaiting proposals, 
@slafortune  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by cubuspl42** [comment]
@slafortune I can't even get there, when I request money, the user B cannot see it, while user A gets "not found error" when I try to click it.

User A:

![image](https://github.com/Expensify/App/assets/2590174/3b5acb1c-4814-415c-ba7d-409263f4b244)

(when clicked)

![image](https://github.com/Expensify/App/assets/2590174/f955f16d-97af-4ea4-90ef-cafaf3b7c44c)

User B:

(not seeing the request at all)

![image](https://github.com/Expensify/App/assets/2590174/7d89bab8-0260-41c8-b900-02bdd5c843a1)

**Comment by slafortune** [comment]
Strange!  That seems like something else entirely, I wasn't able to recreate this or your issue.  Seems like we should close this one, do you agree @cubuspl42 ?

**Comment by cubuspl42** [comment]
@slafortune Sure. You don't reproduce it, some contributors don't reproduce it, so it's probably gone.
