### ISSUE TITLE
[HOLD #23088] Chat - Composer Keyboard not updated to Capital after message is sent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Focus composer (Keyboard will be capital for first character)
3. Type something -> Hit send button
4. Composer is cleared but Keyboard stays in lowercase (If click backspace twice it becomes Uppercase again for first character in Composer)

## Expected Result:
Keyboard should turn to uppercase once message is sent

## Actual Result:
Keyboard doesn’t show uppercase after message sent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0ba61fff-d29c-4b76-9110-9b568d623234

https://github.com/Expensify/App/assets/78819774/ca487222-1b15-4429-9672-44fdfc929d30

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691362004761279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reviewing!

**Comment by dylanexpensify** [comment]
Ah nice catch @bernhardoj! Is that expected to be worked on?

**Comment by dylanexpensify** [comment]
reviewing tomorrow! Got caught up with higher priorities today!

**Comment by dylanexpensify** [comment]
actioning today!

**Comment by dylanexpensify** [comment]
updating today!

**Comment by dylanexpensify** [comment]
Hold - @mallenexpensify any updates here?

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
Hold still on safari project cc @mallenexpensify

**Comment by mallenexpensify** [comment]
Updated title to inc. `[HOLD #23088]` so it's easy to know what the issue is held on.

**Comment by dylanexpensify** [comment]
thank you!!

**Comment by dylanexpensify** [comment]
holding

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
same

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
