### ISSUE TITLE
Graphical glitch in ellipsis in LHN on draft/pin status change

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25547]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open tha app
2. Open latest chat (chat on the top)
3. Type a long message and send it
4. Pin the chat
## Expected Result: 
Long text with ellipsis should be rendered in LHN.
## Actual Result:
 Ellipsis are missing in LHN.
If the list is resorted or the highlight is changed, ellipsis are fixed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/638ecf39-f574-41ee-8054-e7c9f1b1c440

https://github.com/Expensify/App/assets/43996225/e5c2bc42-522e-4771-92d4-930bbc20b85b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tymatein
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691600772689219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Closing, this is extreme polish not a worthwhile bug to fix, got a second opinion in the slack conversation.
