### ISSUE TITLE
'Auth UpdateReportComment returned an error' message on deleting userB's thread message in requested money detail

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to userA's account.
2. Open userB's chat.
3. Navigate to the "Request money" section.
4. Enter an amount and send a money request.
5. Click on the requested money to view its details.
6. In a separate browser, log in using userB's account.
7. Open the chat with userA, then click in requested money for detail.
8. Send a thread message in the requested money detail page.
9. Return to userA's account.
10. Delete the thread message sent by userB.
## Expected Result: 
When the thread message sent by userB is deleted, there should be no display of the error message 'Auth UpdateReportComment returned an error'
## Actual Result: 
Upon deleting the thread message from userB in the requested money detail, the error message 'Auth UpdateReportComment returned an error' is displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/51d069e3-f492-48c7-9a04-9605ba43b8e5

https://github.com/Expensify/App/assets/43996225/74327e5d-2c8a-40f0-b67e-144254793aed

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazHussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691622097169309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
This issue is fixed by this PR: https://github.com/Expensify/App/pull/24396

**Comment by lschurr** [comment]
Great, closing this one.
