### ISSUE TITLE
Web - Workspaces - Inconsistency bug: Only currency change message does not have double quotes around before after values in #admin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspaces
3. Click on 3 dots and click on go to #admins
4. Now for that workspace, change name, currency, rate in reimbursements, unit in reimbursements
5. Observe update messages for all, leaving currency, all other value change has double quotes around before value and after value

## Expected Result:
App should display double quotes around before and after values in update message of currency as it does for all other workspace value change

## Actual Result:
App does not display double quotes around before and after values in update message of currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dd43497d-064e-46cd-988e-9fb7c227db04

![image - 2023-08-19T151057 877](https://github.com/Expensify/App/assets/115492554/d6e911b9-faee-4b08-b7a8-492e939286e3)

https://github.com/Expensify/App/assets/115492554/99f865af-96ee-45de-bf2b-068590593cff

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691649214472479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
The update message is returned from BE. If this is a bug, we need to fix it from BE side

**Comment by stephanieelliott** [comment]
Given that this is a very minor text issue and our internal eng are working on higher priority issues, I am going to close this one for focus. Possible we may tackle in the future along with other polish to workspace update messaging, will reopen at that time.

**Comment by dhanashree-sawant** [comment]
Hi @stephanieelliott , if we are going to solve it in future, can we keep it on hold?
