### ISSUE TITLE
Number typing error when using Vietnamese Telex keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB, then select "Request Money" or "Split bill"
2. Input an amount (e.g., "123")
3. Switch percussion from US keyboard to Vietnamese Telex
4. Then continue to enter the amount until it can't be entered anymore
## Expected Result: 
Can enter or edit money when in Vietnamese Telex keyboard
## Actual Result: 
When enter the full amount, it will be deleted.
 Can't enter amount while in Vietnamese Telex keyboard.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[split_bill.webm](https://github.com/Expensify/App/assets/43996225/7e6c27ad-5722-4d0f-9916-1162d6581c7d)

[request money.webm](https://github.com/Expensify/App/assets/43996225/3127e4dc-64ff-48f6-94b9-f1a6c79292fb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Le Thi Thu Thuy
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691744296819669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1692655258166639?thread_ts=1691744296.819669&cid=C049HHMV9SM
