### ISSUE TITLE
[HOLD for payment 2023-09-06] Use idb-keyval in Onyx

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25566]
### Problem

While investigating performance issues on large accounts we found an issue where storing large amounts of data in onyx takes a very long time (E.g. merging the data from a OpenApp command).
Largely this was due to the underlying storage provider opening a new database transaction for every operation in a multiMerge/multiSet operation.

### Solution

The [idb-keyval](https://www.npmjs.com/package/idb-keyval) package optimises this, as it can handle multiple operations in one database transaction.
The good thing is, that idb-keyval also uses indexedDB as storage provider, so no migration is needed.

**Comment by mountiny** [comment]
No design changes required

**Comment by hannojg** [comment]
👋

**Comment by mountiny** [comment]
This does not have to be Daily I believe.

**Comment by maddylewis** [comment]
just confirming that the only payment due for this one is to @hannojg, correct? is it the standard $500?

**Comment by situchan** [comment]
@maddylewis I reviewed [PR](https://github.com/Expensify/App/pull/25565) and I am the only one due upwork payment.
@hannojg is from Margelo.

I think this applies to $1000 as PR was reviewed and merged before announcement.

**Comment by mountiny** [comment]
agreed

**Comment by maddylewis** [comment]
ok got it. thanks for clarifying. let me get that payment processed rn!

**Comment by maddylewis** [comment]
offer sent

**Comment by maddylewis** [comment]
paid!
