### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000] Web - IOU - Account email is not present in the copied content after IOU has been settled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into Account A
2. Click the '+' green button > `Request Money` > enter amount > `Next` > choose someone to pay
3. In LHN, click on the IOU > hover over the 'amount' box > right-click `Copy to Clipboard`
5. Paste the copied content and observe it contains the email of account B
6. In Account B > click the IOU in the LHN > click the green arrow in the upper right corner of the page > click `Pay Elsewhere`
8. Go back to account A > hover over the paid IOU 
9. Right-click on it and click on `copy to clipboard`
10. Paste the content elsewhere > notice the email isn't copied

## Expected Result:
Account B's email should be present like this "[Account B's email] paid [amount] elsewhere"

## Actual Result:
Account B's email is present before the request is settled but account B's email is not included in the copied content after the IOU has been settled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d1a4323c-5dc2-47e0-b8f9-1efa79abb7a3

https://github.com/Expensify/App/assets/115492554/ebdb6257-a1ca-4720-a2af-309782753b62

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691652788189659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8830daaa898904e</li>
        <li>Upwork Job ID: 1693703978305433600</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26383227</li>
<li>huzaifa-99 | Contributor | 26383228</li>
<li>Nathan-Mulugeta | Reporter | 26383231</li>
</ul></li>
    </ul>
</details>

**Comment by alphaboss1104** [comment]
This is BE issue.

**Comment by Christinadobrzyn** [comment]
I can reproduce - adding Internal label for review

**Comment by Christinadobrzyn** [comment]
Hey @Beamanator can you give this a review and let us know if this can be External or needs to be Internal?

**Comment by Beamanator** [comment]
I think a copy / paste bug is 99% likely a frontend issue - @alphaboss1104 could you explain why you think it's BE?

For now let's add `External`

**Comment by Christinadobrzyn** [comment]
@Beamanator can you confirm you're good with https://github.com/Expensify/App/issues/25567#issuecomment-1696362467?

**Comment by Christinadobrzyn** [comment]
@Ollyws is there a regression test for this? Let me know and I will pay this out. 

Payouts will be:

Issue Reporter: $50 @Nathan-Mulugeta 
Contributor: $500 @huzaifa-99
Contributor+: $500 @Ollyws 

Eligible for 50% #urgency bonus? N - https://github.com/Expensify/App/issues/25567#issuecomment-1726790878

Upwork job is [here](https://www.upwork.com/jobs/~01a8830daaa898904e).

**Comment by Nathan-Mulugeta** [comment]
Hey @Christinadobrzyn this issue was created on Aug 21, before the announcement on aug 30. I think the right amount for reporter should be 250$

**Comment by Christinadobrzyn** [comment]
Hi @Nathan-Mulugeta! Yep! Sorry, I paid $250 in Upwork, the amounts were incorrect [here](https://github.com/Expensify/App/issues/25567#issuecomment-1741376127).

**Comment by Nathan-Mulugeta** [comment]
Hey @Christinadobrzyn did you already processed payment? I didn't receive any payments.

**Comment by Christinadobrzyn** [comment]
Ah sorry for the delay everyone, I thought I paid this but I didn't. 

I've paid everyone in Upwork based on this payment structure. https://github.com/Expensify/App/issues/25567#issuecomment-1741376127

Closing this for now but please let me know if something is missing.
