### ISSUE TITLE
Web -  Profile - Dual focus on Timezone screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the timezone screen
2. You can find the search bar is focused and a result is also focused at the same time.

## Expected Result:
Only one source of focus should be there on a screen.

## Actual Result:
There is dual focus on screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3c3b89b6-d529-46e0-a7e0-8e4a636c7324

https://github.com/Expensify/App/assets/115492554/a3f770ad-4905-4ac5-88b6-98d554a1d76f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @himanshuragi456

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691658447013869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
Not a bug IMO, the option is highlighted because it's current timezone

**Comment by bfitzexpensify** [comment]
Agreed, not a bug.
