### ISSUE TITLE
Web -  Workspace - Workspace appears and disappears on LHN of invited and removed member in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace on account A go to invite member page
2. Go offline
3. Invite account B while offline
4. Remove account B while still offline
5. Go online on account A
6. Observe the LHN on account B

## Expected Result:
Workspace should not appear and then disappear on account B's LHN

## Actual Result:
Workspace appears and disappears on account B's LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/15e7c809-2eb2-4842-9259-046df6e8084c

https://github.com/Expensify/App/assets/115492554/9c7697ef-314e-4d7b-ba74-d1028c6b34d7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691743760972769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
This doesn't seem like a bug to me. When account A comes back online, we are processing the commands in order so we add and then remove account B from the workspace. This seems like a logic result of that. 

I'll close this out as a result, unless there's something to show that this is definitely a bug!
