### ISSUE TITLE
Web - Wrong error message shown when adding an optimistic account as a secondary contact

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Click on + icon and select request money
3. Enter an amount and select an account that has not been created yet ( e.g [negasofonias+112233@gmail.com](mailto:negasofonias+112233@gmail.com)) and click on request money
4. Go to setting then profile and click on contact methods
5. Enter the account used in step 2 as a secondary account
6. Observe that " The new login you are trying to add is a secondary login of another account" is displayed but the account has not even been created

## Expected Result:
Error message should be changed to something that makes sense

## Actual Result:
 The error message shown is wrong

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2ba9f1e4-3e42-47da-a3e3-c5429d6e8bcf

https://github.com/Expensify/App/assets/115492554/38b60628-82b0-4916-b16c-0df0cca1e1b6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691767202484749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc5a904b6e1063a8</li>
        <li>Upwork Job ID: 1694114458593587200</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
added to the thread in Slack - I think this is actually expected

**Comment by adelekennedy** [comment]
This is such a small change I think we should just make this internal - the correct language for this error is something like 
>“the new account you are trying to add here belongs to another account”

**Comment by adelekennedy** [comment]
@laurenreidexpensify well well well - copy review plz?

**Comment by laurenreidexpensify** [comment]
`the email you are trying to add already belongs to another account`

**Comment by adelekennedy** [comment]
Just talked to @deetergp this is a more complicated change than we originally thought (cannot just change error copy, need to create another error path to tell this apart from a secondary login) this _is_ a pretty edge case error so will close for now
