### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Add automated tests for DeleteMoneyRequest

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25601]
# Problem
We added the DeleteMoneyRequest command [here](https://github.com/Expensify/App/pull/19095), but didn't include any automated tests for it.

# Why is this important
Automated tests are the first line of defense against bugs!

# Solution
Add tests to IOUTests.js
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126b69171c61f91af</li>
        <li>Upwork Job ID: 1694018944195133440</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26306942</li>
<li>rayane-djouah | Contributor | 26306944</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@rayane-djouah thanks for the interest! Could you list the test cases you'd like to add?

**Comment by studentofcoding** [comment]
Hey @luacmartins could you share where's IOUTests.js located? or perhaps it's on the different name on the codebase? thanks!

**Comment by luacmartins** [comment]
@studentofcoding https://github.com/Expensify/App/blob/8d5ae3a22a952677f8c48ce8a9c288f51a5eb8d0/tests/actions/IOUTest.js

@rayane-djouah test cases look good. I'll assign you to the issue. Feel free to get started on a PR.

**Comment by luacmartins** [comment]
I assigned myself for review. I'll be mostly ooo for the next few days, but I'll get to it as soon as I can!

**Comment by conorpendergrast** [comment]
I'm on parental leave; re-assigning! This doesn't seem like to needs your work until payment

**Comment by bfitzexpensify** [comment]
Oops, missed that comment. Cool, ok, all paid out and we're done here. Thanks everyone

**Comment by bfitzexpensify** [comment]
We only adjust bounties in very rare cases where the issue ended up being significantly different and more complex. I don't see that in this issue, and so the payment will remain at the price it was listed at.
