### ISSUE TITLE
mWeb/Safari - Time abbreviation takes time to Show/Hide when language is changed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login same account on two Device
2. Device A: go to settings-> Click preferences-> Click language
3. Device B: Go to any chat which shows opponents time -> Observe time abbreviation
4. Device A: Switch language From English to Spanish and vice versa

## Expected Result:
Time abbreviation AM/PM should Show/Hide immediately with language change

## Actual Result:
Time abbreviation AM/PM updates after brief moment of time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c404e642-f3ba-4d75-aa79-394c1e9197d8

https://github.com/Expensify/App/assets/115492554/6bbb2d66-4068-4abb-8e99-3a213207379a

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691615957017389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
In my opinion, this is expected behavior and not a significant delay that needs to be fixed. Thanks!
