### ISSUE TITLE
Web - Workspace - Workspace chatroom is being visible on LHN when deleting a workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Delete the workspace

## Expected Result:
No extra room should be visible on LHN after deleting a workspace

## Actual Result:
An additional room becomes visible on LHN after deleting a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1c3752f9-f356-4183-a3cd-526e1c725293

https://github.com/Expensify/App/assets/115492554/152830dd-e025-4a1d-ac49-3105aae167d8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691744143149019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, it seems like at first the workspace chat isn't showing up (likely because they aren't on the beta?). But then it is showing up once archived. 

I'm guessing this should be fixed by us removing the workspace chats beta. @Beamanator what do you think?

**Comment by Beamanator** [comment]
Hmm good question... We officially got the App PR to remove that beta **Merged** so maybe you can try again now on Main and see what happens?

**Comment by Nathan-Mulugeta** [comment]
Yes I think it is because the workspace chat room is now visible all the time.

**Comment by puneetlath** [comment]
Yeah makes sense. We were actively in the process of changing that behavior. Going to go ahead and close this out.
