### ISSUE TITLE
Chat -  [Attachment] is displayed on reply in thread report header for preview link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report which has image attachment in it
3. Open attachment and copy URL when preview is open
4. Send URL to any report
5. Hover on URL message and click on reply in thread
6. Observe that in header, it displays '[Attachment]' in place of link

## Expected Result:
App should display the message as it is in reply in thread report header on reply in thread click on that message

## Actual Result:
On reply in thread click on attachment preview link, app displays [Attachment] in reply in thread report header in place of the link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2b4d896e-62e8-404a-ad4a-df7706ed967f

https://github.com/Expensify/App/assets/78819774/9104bece-860e-4313-9763-57e7e3ebfcb8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691778016763139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
IMO this is a pretty small and low value bug. I agree the behavior isn't fully consistent but this doesn't feel common or valuable to fix. closing for that reason.
