### ISSUE TITLE
Log in - Apple & Google Sign in buttons are too close and are touching outlines

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.epensify.com
2. Observe sign in methods

## Expected Result:
The two methods should be spaced correctly and the background should be the same as the Expensify page

## Actual Result:
The two sign in methods are touching the white outline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6172850_Log_in_methods_are_touching (1)" src="https://github.com/Expensify/App/assets/78819774/9dd1685b-c35c-424b-92aa-a766e2d334b3">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@marcochavezf seems related to https://github.com/Expensify/App/pull/23673

**Comment by marcochavezf** [comment]
We're already working on a solution [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692656259550869), I will close this one in favor of https://github.com/Expensify/App/issues/25638
