### ISSUE TITLE
Workspace - 'WS chat closed' message is expanded to full screen even if there were messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS App and login with any account
2. Create new workspace or open existing WS
3. Send some messages in #announce room
4. Delete this workspace
5. Open archived #announce chat

## Expected Result:
The message that the 'WS chat is closed' is at the bottom of the screen. All previously sent messages are visible

## Actual Result:
The message that the WS chat is closed is expanded to full screen even if there were messages in the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ee090382-ddc8-44de-9d0f-dd105f9b65ba

![Bug6172890_T3606025-Closed-chat-message-production](https://github.com/Expensify/App/assets/78819774/e1ac1fe9-e0a3-4810-b27b-c71e66e89bc4)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
Hey
Can you confirm that current prod behaviour is correct?

**Comment by robertjchen** [comment]
Yes, the `prod` behavior is correct, the `stg` behavior definitely is not. Though, I'm trying to find which particular change introduced the issue as observed: https://github.com/Expensify/App/issues/25625

**Comment by shubham1206agra** [comment]
Found it https://github.com/Expensify/App/pull/24235

**Comment by shubham1206agra** [comment]
See `BaseHTMLEngineProvider.js`

**Comment by robertjchen** [comment]
@shubham1206agra Thanks! If you have a proposal for a fix, I can mark as `External` and we can get it reviewed 👍

**Comment by shubham1206agra** [comment]
Wait
I will post it a little later (little busy rn)

**Comment by robertjchen** [comment]
Actually, I just saw that they were considering reverting the PR that introduced this along with the other issues. https://github.com/Expensify/App/pull/24235#issuecomment-1687652892

**Comment by shubham1206agra** [comment]
Yes
But I think most of the bug stated there can be fixed easily

**Comment by robertjchen** [comment]
ok, looks like we won't be reverting the original changes, but we'll need a quick turnaround on a fix as it's a `DeployBlocker`. Will open this up for proposals shortly, would you be available to submit a quick fix @shubham1206agra ?

**Comment by Li357** [comment]
@robertjchen @shubham1206agra How quickly do you think you can handle this? I am going to work on a PR that will fix this and https://github.com/Expensify/App/issues/25648 within the next 30.

**Comment by robertjchen** [comment]
@Li357 DeployBlockers take priority, so definitely feel free to handle this internally 👍

**Comment by shubham1206agra** [comment]
F
@Li357 Feel free to ask for help

**Comment by mountiny** [comment]
No longer repro in staging, fixed

![IMG_9E55E02F6538-1](https://github.com/Expensify/App/assets/36083550/5782c58f-d529-44d2-804b-e64717b1d9f7)

Internal reporter so closing
