### ISSUE TITLE
DEV: [mWeb] expensify logo cuts on splash screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app in mWeb and check splash screen
## Expected Result: 
expensify logo should not cut
## Actual Result: 
expensify logo cuts

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/ccf1657b-f85c-42a1-a16b-26058b91565c" width="40%" height="40%">

https://github.com/Expensify/App/assets/43996225/8a6f3eb7-d3fc-43ec-9348-118478d74be4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691823112231979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Will be handled in #25617

**Comment by gadhiyamanan** [comment]
@slafortune i think the other issue is different and they are planning to resolve after i raised the bug
