### ISSUE TITLE
Web - Inconsistent Display of Primary Email When Adding User via Secondary Email

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Navigate to any workspace
2) Open the "Members" page within the workspace
3) Click the "Invite" button to invite a new user by entering their secondary email address
4) Go back to the "Members" list
5) Observe that the secondary email displayed for the newly invited user has been changed to their primary email
6) Navigate to the #admin channel of the workspace
7) Observe the message that was generated for the user addition

## Expected Result:
Since it automatically changes the secondary email to the primary email in the members list, the message in the #admin channel should also reference the primary email. The message should say "added [Primary email] as a user."

## Actual Result:
The message in the #admin channel displays "added [Secondary email] as a user" instead of using the primary email.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-2 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/522a8ffd-813d-46f6-b849-403f5f259284

https://github.com/Expensify/App/assets/115492554/9f562c28-d2f6-497d-bc36-9a51a0c78f77

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Habben101

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691799898107469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
The new user is added as an admin, not as selected as the primary login. The behaviour is correct.
