### ISSUE TITLE
[HOLD for payment 2023-09-04] Cannot delete or edit their own request

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. User A requests X from User B
2. User B request the same X from User A
3. User B cannot delete their request from the header
4. When you navigate tot he IOU report
5. Delete the money request from the popover menu

## Expected Result:
Describe what you think should've happened

You should be able to delete requests you have made.

When deleting from the popover menu, the request is deleted

## Actual Result:
Describe what actually happened

Unable to delete the request

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691836416831359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140d2e85164cfdf25</li>
        <li>Upwork Job ID: 1694687743326535680</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @luacmartins if you are interested

**Comment by tranvantoan-qn** [comment]
I have attached a screen recording here to make it easier for you to follow.

https://github.com/Expensify/App/assets/10254571/036f8290-ca82-47cc-9313-85a8c577bed2

**Comment by mountiny** [comment]
The issue is interesting, for IOU reports the verification fails to confirm the user is owner of the transactions [here](https://github.com/Expensify/Auth/blob/main/auth/lib/Transaction.cpp#L28-L35) becuase the cardID is linked to the user who is payer and thats because we link all the transactions on the IOU report to the payer (person who owes money) [here](https://github.com/Expensify/Auth/blob/9ef70368119bbbbf07345f682d25ad8ec6867aa5/auth/lib/Report.cpp#L3900-L3906).

This is really interesting issue @luacmartins

**Comment by luacmartins** [comment]
hmm we might have to add some new logic to check for the cardID and signs of each transaction as well 🤦

**Comment by mountiny** [comment]
I am really curious why we doing this and if we have to be doing this.

**Comment by mountiny** [comment]
@tranvantoan-qn Can you please confirm this works now?

**Comment by tranvantoan-qn** [comment]
@mountiny 
It worked, there is NO error when deleting the request and the Delete option is showing correctly for each sender

But I'm wondering how the navigation flow should work to avoid the `Hm... It's not here` page since the request/report is deleted.

https://github.com/Expensify/App/assets/10254571/115b32b1-95cb-46b8-8b43-90744630e3ef

**Comment by luacmartins** [comment]
@tranvantoan-qn we're investigating that as part of https://github.com/Expensify/App/issues/25698

**Comment by mountiny** [comment]
Perfect so I think this is ready to pay out

**Comment by mananjadhav** [comment]
@mountiny Is the payout date 2023-08-30 or 2023-09-04?

**Comment by luacmartins** [comment]
Correct date should be 2023-09-04. This [PR](https://github.com/Expensify/App/pull/25669#issuecomment-1696585370) was deployed to production 3 days ago

**Comment by mananjadhav** [comment]
Okay thanks. @mountiny Is it safe to consider this a feature request? Also do we need a regression test here? I don't think we do.

**Comment by mountiny** [comment]
@mananjadhav This was a bug as there was backend issue with the permissions.

I think we need a regression test which will cover all the possible permission cases

**Comment by mananjadhav** [comment]
@mountiny Can we use the test steps from the PR?

**Comment by mountiny** [comment]
you can probably use those from the issue here yeah

**Comment by mananjadhav** [comment]
Okay thanks. Can @anmurali help here to add the regression tests? or can you take care of that @mountiny? I don't have the access to create those.

**Comment by mountiny** [comment]
Can you just write it down in the format that can be copy pasted and @anmurali will take care of that

**Comment by JmillsExpensify** [comment]
$1,000 payment approved via NewDot based on BZ summary.

**Comment by tranvantoan-qn** [comment]
@JmillsExpensify Can you send me Offer for reporter role via Upwork?

**Comment by mountiny** [comment]
@JmillsExpensify @anmurali also reporting bonus $250 to @tranvantoan-qn please, thanks!

**Comment by JmillsExpensify** [comment]
No worries, I'll take it.

**Comment by JmillsExpensify** [comment]
@tranvantoan-qn Upwork job is now public here: https://www.upwork.com/jobs/~0140d2e85164cfdf25. Can you apply for $250 and I'll issue payment?

**Comment by tranvantoan-qn** [comment]
i've applied for the job, thanks!

**Comment by mountiny** [comment]
just waiting for the payment now

**Comment by JmillsExpensify** [comment]
Hired in Upwork.

**Comment by JmillsExpensify** [comment]
All paid out and contract closed. I think we're done here.
