### ISSUE TITLE
[$1000] Web - Keyboard shortcut is not working when dropdown is open from default currency in workspace setting

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25670]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Settings > workspaces
3. select a workspace from the list
4. click setting
5. click default currency
6. try to use the keyboard shortcut (CTRL + J, CTRL + K)

## Expected Result:
keyboard shortcuts should work

## Actual Result:
keyboard shortcuts are not working

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ab270aca-6e68-4592-b8a1-9543b33d95d2

https://github.com/Expensify/App/assets/115492554/08cb378e-3326-4202-8938-ba1024e5d647

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691837136904329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd1df93448bb319c</li>
        <li>Upwork Job ID: 1696160515853365248</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
asked clarification here: https://expensify.slack.com/archives/C049HHMV9SM/p1692898031791459?thread_ts=1691837136.904329&cid=C049HHMV9SM

**Comment by WaqasIbrahim** [comment]
> I think this might be not solvable. I tried to add eventlistener to the `select` element here. Whenever we have select opened it's not listening for any event atleast for me.

This is not exactly a bug. When you have select menu focused, it captures all keyboard events to interact with the select menu. It 's a browser limitation, The select menu is rendered outside of the document boundary. Using a custom select menu like the one used in `Request money` would solve this "issue".

**Comment by NicMendonca** [comment]
@rushatgabhane any ideas here? ^^

**Comment by NicMendonca** [comment]
^ I agree!
