### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] Assign task-Tapping on any contact, user unable to select assignee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap assign task
4. Enter title
5. Tap next
6. Select any user for Share somewhere
7. Tap confirm task
8. From the Confirmed Task screen
9. Tap assignee
10. Select any user - button unresponsive = you can't add an assignee

You  can add an assignee by 

Find a Task in the LHN > tap Assignee > you can assign one

## Expected Result:
Tapping on any contact, user must be able to select assignee

## Actual Result:
Tapping on any contact, user unable to select assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6d11370e-c9b4-4d59-b613-bd3ec418152d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01198bfad5e1717772</li>
        <li>Upwork Job ID: 1694077716312887296</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 26488545</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
This looks like there is a long-running operation on the main thread which is blocking UI input for a few seconds before the tap to select a contact finally registers.

**Comment by Christinadobrzyn** [comment]
I can reproduce but this bug is inconsistent - but updated the OP to be as direct as possible on how to reproduce it. I think this can be External

**Comment by shubham1206agra** [comment]
Unable to repro on DEV

**Comment by robertKozik** [comment]
@shubham1206agra It's reproducible on the latest main. I'm also attaching a video for reference.

https://github.com/Expensify/App/assets/61146594/13d79bfb-f49f-48cc-a80d-b779c63e27eb


@saalimzafar I don't think your suggested root cause is correct, and the same applies to the solution you provided. The isLoading state controls whether the option list is visible or not, and it's set before any user interaction with the list. You can find it here:
https://github.com/Expensify/App/blob/4f412db5e26782740529eb0ef17b5db157628413/src/pages/tasks/TaskAssigneeSelectorModal.js#L202
Your proposed change would cause this screen to be stuck in the loading state, and only the skeleton of the components would be visible.

**Comment by robertKozik** [comment]
It appears that the issue is reproducible right after the task is created. If you navigate away from it and then return, it seems to work as intended.

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Assign task-Tapping on any contact, user unable to select assignee

### What is the root cause of that problem?

This is due to race condition between unmounting `NewTaskPage` (which calls to clear the contents of `Task` inside Onyx) and setting the report inside task Onyx after the API call (or optimistic onyx set of the report and maybe response too). 
This problem will occur when 
https://github.com/Expensify/App/blob/43c6f11bd59b1d83ed4cef1162610f3e34aff701/src/pages/tasks/NewTaskPage.js#L100-L108

will execute after 
https://github.com/Expensify/App/blob/43c6f11bd59b1d83ed4cef1162610f3e34aff701/src/components/ReportActionItem/TaskView.js#L44-L46

And `props.report` never changes after that in `TaskView` component.

### What changes do you think we should make in order to solve the problem?

Temporarily block the change in the task changes in Promise then mechanism when unmounting the `NewTaskPage`, and after unmounting, we can start resolving the changes (i.e. after calling of `clearOutTaskInfo`). 

Examples of similar mechanisms can be found for `Growl`
https://github.com/Expensify/App/blob/43c6f11bd59b1d83ed4cef1162610f3e34aff701/src/libs/Growl.js

### What alternative solutions did you explore? (Optional)

**Comment by robertKozik** [comment]
I cannot longer reproduce this issue on production environment, could you double-check on your end also?

**Comment by shubham1206agra** [comment]
> I cannot longer reproduce this issue on production environment, could you double-check on your end?

@robertKozik 
It's really hard to repro the issue from the start cause it's a race condition which has special case

**Comment by robertKozik** [comment]
I got it, but beforehand (two days ago) I was able to reproduce it continuously. I'll try to repro it again and again

@shubham1206agra about your proposal - Root cause is propably correct (I'll confirm it as soon as I will be able to reproduce it). But using the simmilar machanism to Growl seems like an overkill there. Maybe we can try to extend the function `Task.createTaskAndNavigate` so it will synchronously invoke the `Task.clearOutTaskInfo` before executing navigation process? So we will no longer dependant only on component recycle method (returning the function from `useEffect`)

**Comment by shubham1206agra** [comment]
> I got it, but beforehand (two days ago) I was able to reproduce it continuously. I'll try to repro it again and again
> 
> @shubham1206agra about your proposal - Root cause is propably correct (I'll confirm it as soon as I will be able to reproduce it). But using the simmilar machanism to Growl seems like an overkill there. Maybe we can try to extend the function `Task.createTaskAndNavigate` so it will synchronously invoke the `Task.clearOutTaskInfo` before executing navigation process? So we will no longer dependant only on component recycle method (returning the function from `useEffect`)

Ok
This will be easier ig

**Comment by robertKozik** [comment]
Able to reproduce - I can continuously do that on iphone se simulator. @shubham1206agra I can confirm your root cause of the issue - we indeed have some race condition here

**Comment by shubham1206agra** [comment]
> Able to reproduce - I can continuously do that on iphone se simulator. @shubham1206agra I can confirm your root cause of the issue - we indeed have some race condition here 

It's just an order of code execution that will determine the outcome of the race. That's why the repro is hard sometimes

**Comment by shubham1206agra** [comment]
@robertKozik Can I take this up in this case?

**Comment by robertKozik** [comment]
I had concerns about your solution in my [previous comment](https://github.com/Expensify/App/issues/25689#issuecomment-1693552505). I don't think we want to couple two screens with each other that way. `Growl` component is more general-use one (can be accessed from various places), here we have two separate screens which should work independently from each other.

**Comment by shubham1206agra** [comment]
> I had concerns about your solution in my [previous comment](https://github.com/Expensify/App/issues/25689#issuecomment-1693552505). I don't think we want to couple two screens with each other that way. `Growl` component is more general-use one (can be accessed from various places), here we have two separate screens which should work independently from each other.

Ok, I think we can clear task data just before the API call. This will not affect anything and will solve the issue.

**Comment by robertKozik** [comment]
Sorry for the inconvenience but I've checked out previous PR related to `clearOutTaskInfo` and it looks like we are gonna revert the changes from there https://github.com/Expensify/App/pull/23342 . Could you double check whether issues fixed by that would still occurred after this solution? I'm gonna check too

**Comment by shubham1206agra** [comment]
@robertKozik Looks like there's an easier way.
Something overwritten the changes from https://github.com/Expensify/App/issues/23556
Can you find the commit which overwritten the change from this PR?
I am also unable to find the merge commit of this PR in the file `TaskAssigneeSelectorModal.js`

**Comment by shubham1206agra** [comment]
> Sorry for the inconvenience but I've checked out previous PR related to `clearOutTaskInfo` and it looks like we are gonna revert the changes from there #23342 . Could you double check whether issues fixed by that would still occurred after this solution? I'm gonna check too

We can prevent this problem by using state for title and description just like assignee and shareDestination

**Comment by shubham1206agra** [comment]
I think we should aim for both changes

**Comment by robertKozik** [comment]
> @robertKozik Looks like there's an easier way. Something overwritten the changes from #23556 Can you find the commit which overwritten the change from this PR? I am also unable to find the merge commit of this PR in the file `TaskAssigneeSelectorModal.js`

The Issue/PR you have pointed out is not overwritten by anything. Changes are visible on latest main https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/tasks/TaskAssigneeSelectorModal.js#L117-L122

**Comment by robertKozik** [comment]
> I think we should aim for both changes

Could you update your proposal accordingly? So I can check it clearly, if we are on the same page there

**Comment by shubham1206agra** [comment]
> > @robertKozik Looks like there's an easier way. Something overwritten the changes from #23556 Can you find the commit which overwritten the change from this PR? I am also unable to find the merge commit of this PR in the file `TaskAssigneeSelectorModal.js`
> 
> The Issue/PR you have pointed out is not overwritten by anything. Changes are visible on latest main
> 
> https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/tasks/TaskAssigneeSelectorModal.js#L117-L122

Not this one
There's a line in this
`Task.setAssigneeValue(option.login,option.accountID,props.route.params.reportID,OptionsListUtils.isCurrentUser(option));`

**Comment by robertKozik** [comment]
@shubham1206agra 
That PR https://github.com/Expensify/App/pull/22778 introduces the function which overwritten the `editTaskAndNavigate`. But I'm not sure why we need to know this

**Comment by shubham1206agra** [comment]
> @shubham1206agra That PR #22778 introduces the function which overwritten the `editTaskAndNavigate`. But I'm not sure why we need to know this

Looks like it got overwritten here accidently

> edit: as I asked before, could you update your proposal and solution so it would be up-to-date?

Done

**Comment by shubham1206agra** [comment]
> i don't think we should revert this change - `editTaskAssigneeAndNavigate` introduces the optimistic creation of the asignee, so removing or changing back this method will cause regression

@robertKozik Which change??

**Comment by shubham1206agra** [comment]
@robertKozik ??

**Comment by robertKozik** [comment]
Sorry, I think I've misunderstand your suggestion from the proposal 😅 I think we are good to go, if you could only modify your proposal so the solution we are discussing would be as the main one not the alternative and expand a little section about the state variable for title and description

**Comment by shubham1206agra** [comment]
> Sorry, I think I've misunderstand your suggestion from the proposal 😅 I think we are good to go, if you could only modify your proposal so the solution we are discussing would be as the main one not the alternative and expand a little section about the state variable for title and description

Ok

**Comment by shubham1206agra** [comment]
@robertKozik Updated https://github.com/Expensify/App/issues/25689#issuecomment-1690319329

Do you want any other changes?

**Comment by shubham1206agra** [comment]
@robertKozik ?

**Comment by robertKozik** [comment]
I think we are ready with proposal :) 

chosen proposal: [Proposal](https://github.com/Expensify/App/issues/25689#issuecomment-1690319329)
contributor: @shubham1206agra 

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment]
prepping for payment... @robertKozik should there be a regression test for this?

**Comment by Christinadobrzyn** [comment]
Also @cristipaval I see a merge freeze was involved in the PR merge, this might have affected the speed bonus. Do we think a speed bonus applies here?

**Comment by cristipaval** [comment]
Good point @Christinadobrzyn! Yes the speed bonus should apply, I checked the dates. I held the issue due to that merge freeze.

**Comment by robertKozik** [comment]
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23342
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23342/files#r1335754275
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I think we don't need regression test here. It's rather edge-case scenario, which can be fixed with re-accessing the screen.
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

CC. @Christinadobrzyn

**Comment by Christinadobrzyn** [comment]
Payouts due:

Issue Reporter: NA
Contributor: $1000 +500 bonus @shubham1206agra in Upwork
Contributor+: @robertKozik payment through contract

Eligible for 50% #urgency bonus? Yes - https://github.com/Expensify/App/issues/25689#issuecomment-1732672658 

Upwork job is [here](https://www.upwork.com/jobs/~01198bfad5e1717772).

@robertKozik let us know about the regression test so we can get this closed out -thanks!

**Comment by robertKozik** [comment]
I don't think we need regression test for it  https://github.com/Expensify/App/issues/25689#issuecomment-1733481176

**Comment by Christinadobrzyn** [comment]
Ah sorry I missed that note about the regression test. Thanks for clarifying! Closing this out.
