### ISSUE TITLE
[HOLD for payment 2023-09-04] Task -App becomes unresponsive when Assign Task to user that doesn't have a NewDot account yet

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB > Assign Task > Enter title and description and navigate to next page
3. Click on Assignee
4. Enter a email that doesn't have a NewDot account yet
5. Create the task

## Expected Result:
Assignee should be added immediately and no errors should appears

## Actual Result:
App becomes unresponsive when Assign Task to user that doesn't have a NewDot account yet
Page Unresponsive
You can wait for it to become responsive or exit the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:**  1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a97b970e-a41b-4d89-a95e-91c6181c3104

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Seems we're entering an infinite loop after assigning the task

<img width="680" alt="Screenshot 2023-08-22 at 13 56 22" src="https://github.com/Expensify/App/assets/6829422/190b4971-97cf-49ed-bcaf-6f98d6fac1e9">

**Comment by marcochavezf** [comment]
We're calling multiple times `componentDidUpdate` in ReportScreen.js

https://github.com/Expensify/App/assets/6829422/0bd252d5-7047-4ee6-a84b-41b9278c5e93

I will need to step out for 1.5 hours approx, I will continue when I come back

**Comment by marcochavezf** [comment]
The `OpenReport` and `CreateTask` are failing:

<img width="681" alt="Screenshot 2023-08-22 at 19 09 20" src="https://github.com/Expensify/App/assets/6829422/289a1212-206e-4ee6-b7db-214e94d6b3bd">

<img width="675" alt="Screenshot 2023-08-22 at 19 09 28" src="https://github.com/Expensify/App/assets/6829422/b66493da-9e2b-4385-be19-97dd9859cb2e">

**Comment by marcaaron** [comment]
These three PRs are related to tasks:

https://github.com/Expensify/App/pull/24506
https://github.com/Expensify/App/pull/24412
https://github.com/Expensify/App/pull/24566

Not sure if any of them are related. @Julesssss @arosiclair @luacmartins might have a better idea.

**Comment by marcaaron** [comment]
FWIW, this flow doesn't actually work on production either cc @thienlnam 

>Assignee should be added immediately and no errors should appears

This is not what happens on production. I see this:

![2023-08-23_09-32-18](https://github.com/Expensify/App/assets/32969087/ed87d653-08b7-4af0-af53-6e74d591b94b)

And `CreateTask` throws an error about `400 Invalid accountID`

**Comment by marcaaron** [comment]
This issue appears to be resolved after applying the revert from here https://github.com/Expensify/App/pull/25785

**Comment by marcaaron** [comment]
Chatting with @thienlnam. 

Seems like if we are not going to revert the unread marker PR as per https://github.com/Expensify/App/issues/25673#issuecomment-1690617455 then we should do some other work around that prevents taking this action entirely when assigning a task.

It's not possible in the backend so I think seems like a "feature request" or polish step for Tasks.

**Comment by roryabraham** [comment]
Confirmed that this is no longer reproducible on staging and that the PR worked. Removing the deploy blocker label and checking this off.

Should we create a follow-up to enable you to assign tasks to accounts that don't exist yet? I feel like that's more inline with how other flows such as New Chat work and is a viral growth flow.

**Comment by thienlnam** [comment]
Yeah I can create a follow up PR - hasn't been a priority but a good polish item

**Comment by marcaaron** [comment]
This appears to be an internal effort (all) so I think we can close it.
