### ISSUE TITLE
Login - Can't sign in with Apple

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23673
## Action Performed:
1. Go to staging.new.expensify.com
2. Click on Apple icon logo
3. Enter valid Apple ID and password
4. If prompted, validate with 2 factor authentication
5. Select "Share my email" and click on "Continue"

## Expected Result:
he user should be able to log in with their Apple account

## Actual Result:
The user is unable to log in with their Apple account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fb440b6a-941e-45a4-8fb3-93aa64511647

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
@marcochavezf Can you take a look?

**Comment by marcochavezf** [comment]
Yeah this is weird, for some reason, the `idToken` is not included in the payload:

<img width="839" alt="Screenshot 2023-08-22 at 11 08 03" src="https://github.com/Expensify/App/assets/6829422/97d2599a-8927-44e4-ab8a-763ea8afd124">

**Comment by marcochavezf** [comment]
Looking at the bundle file, seems the param in `beginAppleSignIn` is undefined:

<img width="295" alt="Screenshot 2023-08-22 at 11 10 54" src="https://github.com/Expensify/App/assets/6829422/339d5147-7bf9-42b2-8c4d-b2072c9710ce">

**Comment by marcochavezf** [comment]
At the upper level, we're trying to get the id_token from the object `detail`, but it seems we'd need to get it from `detail.authorization.id_token` @lindboe 

<img width="332" alt="Screenshot 2023-08-22 at 11 13 16" src="https://github.com/Expensify/App/assets/6829422/10a729fa-be9e-4810-ae72-1c53e1ddd812">

**Comment by marcochavezf** [comment]
I suppose it's coming from [here](https://github.com/Expensify/App/blob/aa98b6bcd1d71f47afee043673c7c18a337b8959/src/components/SignInButtons/AppleSignIn/index.website.js#L54), would be possible that the structure of the object changes in dev mode?

I think we should create some helper function to get the `id_token`, something like:

```js
function getIDToken(event){
   return lodashGet(event.detail, 'authorization') ?  lodashGet(event.detail.authorization, 'id_token') : odashGet(event.detail, 'id_token');
}
```

At least to fix the deploy blocker and we can check out later why the structure changes, what do you think @lindboe?

**Comment by amyevans** [comment]
QA'ed the fix on staging and it passes ✅ 

Going to remove the deploy blocker label

**Comment by amyevans** [comment]
Actually I guess we are all set to close
