### ISSUE TITLE
Map not showing in `DistanceRequest` tab of `MoneyRequest` page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money
3. Go to Distance tab

## Expected Result:
Map is displayed in Distance tab

## Actual Result:
Map is not displayed in Distance tab. The site does not ask for location permission. It is not possible to set 'allow' for location permission on web browser as it reverts to 'ask' in the site settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6173422_mweb](https://github.com/Expensify/App/assets/78819774/81948153-08cf-4960-8993-e9bb01f90fcf)

![Bug6173422_Android](https://github.com/Expensify/App/assets/78819774/60aab3f9-cb35-4758-b8b5-374370de562f)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
- iOS ✅ 
- Android ✅ 
- Android Web ❌ 
- iOS Web ❌ 
- Desktop web ❌ 

@hayata-suenaga is this supposed to work on web at this point?

**Comment by hayata-suenaga** [comment]
I'm checking now

**Comment by hayata-suenaga** [comment]
that will be solved when [this PR](https://github.com/Expensify/App/pull/25161) is deployed to staging. I don't know if it's worth cherry pick though because this feature is behind beta anyway.

**Comment by hayata-suenaga** [comment]
@arosiclair I gonna assign myself to this issue and see if the PR actually gonna fix the issue. But this is not a deploy blocker so removing the label.

**Comment by hayata-suenaga** [comment]
yep the map is working on main

<img width="300" alt="Screenshot 2023-08-22 at 3 18 23 PM" src="https://github.com/Expensify/App/assets/98560306/cccfe425-5e66-46a7-93b6-a7378172bf0f">

**Comment by hayata-suenaga** [comment]
being handled here: https://github.com/Expensify/Expensify/issues/311387

**Comment by hayata-suenaga** [comment]
Opened [a PR](https://github.com/Expensify/Cloudflare-Workers/pull/82) in the `Cloudflare-Workers` repo

**Comment by hayata-suenaga** [comment]
The fix has been deployed and it's working now
