### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Desktop - Drag & drop container does not add opacity to entire height of the drawer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the money request page
2. Select Scan tab
3. Drag file to this tab
4. Notice the green opacity does not cover entire height of drawer
## Expected Result: 
Green opacity should cover entire height of drawer same as desktop
## Actual Result: 
Green opacity does not cover entire height of drawer and add space on top

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-08-12 at 2 19 43 AM](https://github.com/Expensify/App/assets/43996225/84bfa602-1c9b-4865-9ecb-fb1ca0dc11f0)

Uploading Recording #250.mp4…

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691787401646299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2b5135808f4dd46</li>
        <li>Upwork Job ID: 1696559205510832128</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26516154</li>
<li>dhairyasenjaliya | Reporter | 26516155</li>
</ul></li>
    </ul>
</details>

**Comment by muttmuure** [comment]
I consider this design polish

**Comment by muttmuure** [comment]
The solution seems pretty good though, so I will add external

**Comment by muttmuure** [comment]
Just waiting for @sobitneupane to review https://github.com/Expensify/App/issues/25709#issuecomment-1689836246

**Comment by muttmuure** [comment]
Just waiting on review

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/25709#issuecomment-1689836246) from @tienifr looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by muttmuure** [comment]
@sobitneupane - $1500
@tienifr - $1500
@dhairyasenjaliya - $250

**Comment by muttmuure** [comment]
@tienifr and @dhairyasenjaliya have been paid in Upwork. NewDot payment waiting for @sobitneupane

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/23046

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/23046#issuecomment-1732879623
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is an edge case missed while adding a new functiolity.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Go to the money request page
2. Select Scan tab
3. Drag file to this tab
4. Verify that the green opacity covers entire height of drawer

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/25709#issuecomment-1728763504

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @sobitneupane based on BZ summary.
