### ISSUE TITLE
BA - Expensify crashes when entering test transactions

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com or start Expensify App
2. Login with Expensifail account
3. Create new or go to existing workspace without BA
4. Go to Workspace > Connect bank account
5. Select the Manual method to add a bank account
6. Follow the flow to connect Pending State Bank account' until 'Test transactions' page
7. Enter any numbers in the test transaction fields

## Expected Result:
User can enter test transactions

## Actual Result:
App / Website crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

[logs.log](https://github.com/Expensify/App/files/12411661/logs.log)

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/98280ece-8f49-4381-ab57-fb9eabdacf97

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

[logs.log](https://github.com/Expensify/App/files/12411654/logs.log)

**Comment by hayata-suenaga** [comment]
well, it doesn't re-trigger auto-assignment...

anyway, [per this slack discussion](https://expensify.slack.com/archives/C05DWUDHVK7/p1692667290100579?thread_ts=1692658684.398019&cid=C05DWUDHVK7), I'm assigning myself

gonna find someone in #engineering-chat

**Comment by aldo-expensify** [comment]
I'm trying to verify that this is not already broken in production...

Meanwhile, this is the error:

<img width="473" alt="image" src="https://github.com/Expensify/App/assets/87341702/92e98d37-421f-442c-9ec9-620f4685a92c">

Apparently we call `Validation.filterInput` with all values from the form, and that include some boolean values. The function crashes when we pass `true` to it.

I think the function crashing may be because of this PR:

https://github.com/Expensify/expensify-common/pull/567

cc @Li357

**Comment by aldo-expensify** [comment]
QA passed:


https://github.com/Expensify/App/assets/87341702/1a86521a-d27d-4205-aaff-5f00c7feb36b
