### ISSUE TITLE
Login - Unable to log in manually with locked gmail but able to log in with Google

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25713]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Have a Gmail account that is locked.
To create a locked Gmail:
1. Go to Settings > Profile > Contact method > New contact method.
2. Add an invalid email address (eg, [dusjosjkposakpa@gmail.com](mailto:dusjosjkposakpa@gmail.com)
3. Save and log out.
4. Log in with primary contact method.
Steps:
1. Go to staging.new.expensify.com.
2. Log in with Google witth the locked accout.

## Expected Result:
Since user is blocked from manually logging in with the locked Gmail, login with Google should be blocked as well

## Actual Result:
User is able to login with Google when manually logging in with the locked Gmail fails

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [x] Windows / Chrome

**Version Number:** 1.3.56-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d6f61016-8314-4432-bb0e-4612464d3bdf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lindboe** [comment]
@marcochavezf, this looks like maybe a server-side issue with Google Sign-In?

**Comment by marcochavezf** [comment]
Yeah, this is a backend issue from our side. I don't know exactly how we're triggering the [suspended email message](https://github.com/Expensify/App/blob/cfe1d024580c878762812e5a263181fc1084cbd1/src/languages/en.js#L858), but I think we'd need to hook up that logic to the `SignInWithGoogle` API command. So this can only be fixed internally.

Since this is introduced with the new Google sign-in functionality, I don't think this should be a blocker.

**Comment by grgia** [comment]
@marcochavezf could you take over this issue in that case?

**Comment by roryabraham** [comment]
Since this is a back-end issue, we're not going to block NewDot deploy on this. But we'll keep it as a daily

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update, prioritizing wave7 atm

**Comment by marcochavezf** [comment]
No update, moving it to weekly until we get collect approvers done at the end of the offshore

**Comment by marcochavezf** [comment]
No update, focused on wave7 and traveling back from Offshore

**Comment by marcochavezf** [comment]
No update, wrapping other priorities for wave7

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update, focused on wave bugs

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
Focused on wave issues, no update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update, focused on wave work

**Comment by marcochavezf** [comment]
No update, posted in wave9 to ask if it should part of it https://expensify.slack.com/archives/C05NJ4SLBMF/p1707159629690479

**Comment by marcochavezf** [comment]
No update, focused on critical wave issues and older tasks

**Comment by marcochavezf** [comment]
No update, focused on critical and high wave tasks

**Comment by marcochavezf** [comment]
After some investigation, I found out this error is only shown when our email providers can't send the validation code for some reason (has the nvp `expensify_emailDeliveryFailure`). Since the user is trying to sign in via Google, we don't send a validation code. Also, we don't show this error in OldDot when the user has the nvp `expensify_emailDeliveryFailure` and sign in via SSO, so I'm going to close it out.
