### ISSUE TITLE
[$1000] IOU - Message sent from IOU details page is not shown to receiver in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Enter amount
5. Tap next
6. Select user
7. Tap Request money
8. Tap on requested money
9. In IOU details page, send a message to user X
10. Open X account
11. Tap on request money conversation to navigate to IOU details page
12. Navigate back to LHN

## Expected Result:
When X opens account, in LHN, message sent from IOU details page should be displayed

## Actual Result:
Message sent is displayed in X's LHN, only when X opens account, tap on request money conversation and navigated to IOU details page and then when he navigated back to LHN, message is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/386c4a66-03f7-4aa3-859a-ff36918e2c4b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b018e912111010f1</li>
        <li>Upwork Job ID: 1695166777631399936</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by slafortune** [comment]
Looks good

**Comment by nikhildewoolkar** [comment]
Not Re-Producible a same bug
