### ISSUE TITLE
Login - Focus remains on last digit after login with wrong link and requesting new code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS or Android App
2. On the login screen, enter a new account email
3. Open the validate email and copy the link
4. Modify the last part of the link to make 'wrong link'
5. Navigate to this 'wrong link'
6. Checked that "Magic code is incorrect" is displayed
7. Request a new magic link

## Expected Result:
Wrong magic code cleared and focus moved to first digit

## Actual Result:
Wrong magic code cleared and focus moved to last digit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-8

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/632fa611-5d8a-407b-8645-47fc3527a55b

https://github.com/Expensify/App/assets/78819774/5cedf79c-7d48-4ba9-a3f8-bd5505791f5f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Was able to reproduce this one

**Comment by roryabraham** [comment]
Not consistently reproducible. Appears to be the result of some race condition maybe?

**Comment by roryabraham** [comment]
Got a fix

**Comment by roryabraham** [comment]
PR is up and ready for review

**Comment by roryabraham** [comment]
QA'd this and it's fixed on staging by the revert
