### ISSUE TITLE
[HOLD for payment 2023-09-06] Cleanup: tabSelector translations

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#25722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

[View code for rendering `TabSelector`s](https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/TabSelector/TabSelector.js#L67)

## Expected Result:

- The translations for tab titles should be done use a `switch` statement instead of dynamically building the translation key.
- `tabSelector.distance` should be moved to `common.distance` so that it can be shared with the same label in the [MoneyRequestView](https://github.com/Expensify/App/blob/fc9378eef3691017366dbc98348f583d7f36b8ee/src/components/ReportActionItem/MoneyRequestView.js#L169)

## Actual Result:

- the translation for tab titles are built dynamically making it difficult to search later
- MoneyRequestView uses translations for the TabSelector

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106e108c600480ca5</li>
        <li>Upwork Job ID: 1694099140299124736</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Just a followup PR

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Not a regression. Just a followup PR

**Comment by anmurali** [comment]
@abdulrahuman5196 - [Offer](https://www.upwork.com/nx/wm/offer/26644129)

**Comment by arosiclair** [comment]
@abdulrahuman5196 did you receive payment? Can we close this out?

**Comment by arosiclair** [comment]
Alright I'm closing this out. Please re-open if they're any issues
