### ISSUE TITLE
[HOLD for payment 2023-09-07] Update page titles when entering start/stop/finish destinations

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#25730]
One inconsistency that's cropped up since writing the design doc is that we have incorrectly labeled the start/stop/finish pages as `Waypoint editor`. The high-level of the design doc instead stipulates that the page title should correspond to the row that the user clicked. 

So for example....

 - If you tap `Start` then we push to a new page and that page is called `Start`
 - If you tap `Finish` then we push to a new page and that page is called `Finish`
 - If you tap `Stop` then we push to a new page and that page is called `Stop`

Example screenshots from the design doc. 

![Image](https://user-images.githubusercontent.com/1127863/262501196-2d885906-a2bc-4a42-aa06-dc67bff14657.png)

![Image](https://user-images.githubusercontent.com/1127863/262501255-f913e6f5-f73e-406b-9d14-182af33090bd.png)

![Image](https://user-images.githubusercontent.com/1127863/262501319-dcd43449-d2a2-4f73-aef5-8898ef14d6d2.png)

**Comment by hayata-suenaga** [comment]
@slafortune a C+ member is going to open a PR for this. Context here: https://expensify.slack.com/archives/C02NK2DQWUX/p1692743882927849?thread_ts=1692665981.227269&cid=C02NK2DQWUX

**Comment by slafortune** [comment]
External issue reporter - NA
Contributor that fixed the issue - NA
Contributor+ that helped on the issue and/or PR - @allroundexperts Eligible for Manual Requests - $1000 + $500 bonus

**Comment by slafortune** [comment]
Ah!  Thanks for bringing that to my attention @thesahindia !  Please request that and I'll update the payment summary!

**Comment by slafortune** [comment]
External issue reporter - NA
Contributor that fixed the issue - NA
Contributor+ that helped on the issue and/or PR - @allroundexperts Eligible for Manual Requests - $1000 + $500 bonus
Contributor+ that helped on the issue and/or PR - @thesahindia  Eligible for Manual Requests - $1000 + $500 bonus
CC @anmurali @JmillsExpensify

**Comment by JmillsExpensify** [comment]
$1,500 approved for payment via NewDot based on BZ summary.

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @thesahindia based on BZ summary.
