### ISSUE TITLE
Address autofill is not giving correct suggestions based on country in the user personal details settings

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25736]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> profile -> personal details -> address
2. Select a country from the country field
3. In the address line 1 field, search a city/location of the country you selected.
4. Notice the autofill suggestion, contains other countries location
5. Repeat steps 2-3 with a different country, again verify step 4,
## Expected Result:
If a user has a selected country, the autofill show only show locations from that country, and if the user has no selected country, the autofill should show suggestions from all locations.
## Actual Result:
The autofill shows suggestions from all locations, instead of the selected country
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-14
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/2e781838-850a-4d95-9834-2d48e6a977dd

https://github.com/Expensify/App/assets/38435837/8891c595-572d-4432-85e1-a67e6f718355

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692011103310569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
I think this is a new feature. Asking here

https://expensify.slack.com/archives/C049HHMV9SM/p1692916644511909?thread_ts=1692011103.310569&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
not a bug, it's a new feature
