### ISSUE TITLE
[HOLD `react-native-x-draggable-list` #5] Implement draggable list

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

We’re going to create a draggable list component that is cross-platform in [a new React Native library](https://github.com/Expensify/react-native-x-draggable-list). The new library/component should support both mobile and web.

The new library has already been setup with the support for TypeScript. Please write the new library in TypeScript.

This component should essentially wrap [react-native-draggable-flatlist](https://github.com/computerjazz/react-native-draggable-flatlist) (a React Native library) and [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) (a React library) and to provide a consistent API.

The only features/APIs we need for the new component is the ability to take an array and display the list item for each item in the array. We also want to provide a call back? to make sure that the re-ordering behavior can be listened to.

This new library is used in the `DistanceRequest` component to replace [this part](https://github.com/Expensify/App/blob/0fb2ca40901bf334d1748a2d2b3d6c81b3eb4fb5/src/components/DistanceRequest.js#L172-L201).

**Comment by hayata-suenaga** [comment]
removing the bug label and related melvin comments. This is a new feature and is not a bug.

**Comment by pradeepmdk** [comment]
@hayata-suenaga can I work on this

**Comment by kosmydel** [comment]
Hey, I'm from Software Mansion, and I'm going to work on this.

**Comment by hayata-suenaga** [comment]
the PR is being worked on

**Comment by stephanieelliott** [comment]
Hey @hayata-suenaga, is this still on hold in some capacity, or should we remove `Hold` from the title?

**Comment by hayata-suenaga** [comment]
ah sorry this issue is a dupe of [this one](https://github.com/Expensify/App/issues/22716)

closing this now
