### ISSUE TITLE
[Awaiting C+ payment] [HOLD for payment 2023-09-06] [Performance] Composer typing is slow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25763]
### Problem

When typing in a composer, especially on desktop or web, the input has a delay and feels sluggish.

### Solution

Identify what is causing this unnecessary delay and fix it

**Comment by trjExpensify** [comment]
Haha, best solution summary eveeer Vit! 😏

**Comment by mountiny** [comment]
@trjExpensify Thanks, Tom. It just takes years of practice and self-discipline

**Comment by hannojg** [comment]
👋 @mountiny

**Comment by trjExpensify** [comment]
👋 @mountiny mind clarifying who and what is needed for payment on this one?

**Comment by trjExpensify** [comment]
Cool, so @rushatgabhane can you submit a request for reimbursement? 

@mountiny @hannojg are you guys taking the checklist, or handled limiting these performance regressions else where?

**Comment by mountiny** [comment]
Yep this will be part of the project for performance to monitor rerenders and such, thanks

**Comment by trjExpensify** [comment]
Excellent so just need to confirm $1,000 to @rushatgabhane for the C+ review. Thanks!

**Comment by trjExpensify** [comment]
No change, Melv. Waiting for @rushatgabhane to get his request in and paid.

**Comment by trjExpensify** [comment]
Cool!

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/25763#issuecomment-1711927047).
