### ISSUE TITLE
[HOLD for payment 2023-09-04] Login - Sign in with Google logo jumps after the login page is refreshed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Refresh the page

## Expected Result:
The Sign in with Google logo does not jump after the page is refreshed

## Actual Result:
The Sign in with Google logo jumps after the page is refreshed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/74501957-f8c8-4f0a-88b1-8fbbb88eb6bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
I cannot reproduce this - or maybe can't see it? I only see it on the second refresh in the video, too.

I've asked in Slack for another set of eyes, so will see and continue from there.

**Comment by dangrous** [comment]
hey @marcochavezf do you think you can take a look at this, since you handled the PR that added these? It's hard to diagnose since [we don't show the buttons on dev](https://github.com/Expensify/App/blob/4f412db5e26782740529eb0ef17b5db157628413/contributingGuides/APPLE_GOOGLE_SIGNIN.md#L107-L120) and apparently the Google one looks weird on dev anyway.

**Comment by dangrous** [comment]
By default this is from this PR - https://github.com/Expensify/App/pull/23673/ - it looks like we iframe in the Google button so I'm wondering if it's loading the styles just a fraction of a second before/after the iframe is loaded, hence the jump? Hoping to figure it out further.

**Comment by dangrous** [comment]
Getting this CPed https://expensify.slack.com/archives/C07J32337/p1692811481745669

**Comment by marcaaron** [comment]
This one seems resolved now. Gonna check it off. fwiw it looks like we needed something more like this -> https://github.com/Expensify/App/issues/25797

**Comment by situchan** [comment]
@dangrous am I eligible compensation for PR review?

**Comment by dangrous** [comment]
yep! let me grab a bz

**Comment by dangrous** [comment]
hey @dylanexpensify we need to pay @situchan for PR review, when you have a moment!

**Comment by dylanexpensify** [comment]
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry for delay!

**Comment by dylanexpensify** [comment]
Back at it after conference - completing today! Wifi was absolutely awful on flight!

**Comment by dylanexpensify** [comment]
Upwork has been a real pain with creating a new post - trying again now

**Comment by dylanexpensify** [comment]
Sent invite to job @situchan !

**Comment by dylanexpensify** [comment]
Offer sent @situchan!

**Comment by dylanexpensify** [comment]
done!
