### ISSUE TITLE
IOU Scan - Receipt is not displayed on IOU preview in chat until IOU preview is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25691
## Action Performed:
Precondition: Create a money request in Scan tab on a different device like WEB
Steps:
1. Go to the chat on mweb (or log out on web and log back in on web) where IOU is requested
2. Open the IOU preview
3. Return to chat

## Expected Result:
In Step 1, the receipt is displayed on IOU preview

## Actual Result:
In Step 1, the receipt is not displayed on IOU preview. The receipt is only displayed on IOU preview after the IOU preview is opened in Step 2

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3dc2367a-524c-4bae-81c5-f87903ee7fe6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tewodrosGirmaA** [comment]
I reported first here https://expensify.slack.com/archives/C049HHMV9SM/p1692709337584889

**Comment by arosiclair** [comment]
I've noticed this in testing distance requests as well. Referring this to the Scan Receipt team

**Comment by tewodrosGirmaA** [comment]
Hello, @arosiclair It has the same root as this one https://expensify.slack.com/archives/C049HHMV9SM/p1692709337584889 Please help.

**Comment by luacmartins** [comment]
This is not a blocker. We already have an [issue](https://github.com/Expensify/Expensify/issues/310102) for this and we're addressing it in [Fix split bill transactions](https://github.com/Expensify/Auth/pull/8520). Closing this one.
