### ISSUE TITLE
 Workspace - Incomplete message appear when add more characters to Workspace "<my workspace"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25760]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create New Workspace
3. Click on Settings
4. Change the workspace name to "<my workspace"
5. Check the notification message in #admin room history
6. Navigate back to Settings and add more characters to "<my workspace" ( <my workspace 123)
7. Check the notification message in #admin room history

## Expected Result:
Proper message that contains full names of the Workspace should be displayed, like in Step 5 - Updated the name of this workspace from "Gocemate Workspace" to "<my workspace"

## Actual Result:
Incomplete message appears - "Updated the name of this workspace from "" when change the Workspace name adding more characters to "<my workspace" name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/591f2450-5fa2-4f9a-a842-565bae9763bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013170955ac054b190</li>
        <li>Upwork Job ID: 1696548988651683840</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I think the ideal way to do this is probably to encode the HTML from the back-end.

**Comment by mananjadhav** [comment]
Just checked this. Agreed it if it comes from the backend it will be better.  We do encode the contents of the comment. 

<img width="1486" alt="Screenshot 2023-09-01 at 10 46 35 AM" src="https://github.com/Expensify/App/assets/3069065/fa431371-8f0c-4207-99a4-83edf95ee3d5">

**Comment by puneetlath** [comment]
Haven't had a chance to look into the back-end fix yet. Not super urgent, but will get to it eventually.

**Comment by puneetlath** [comment]
Haven't got to it yet. Still on the list.

**Comment by puneetlath** [comment]
@mananjadhav I'm going to go ahead and remove you since this is a back-end issue.

**Comment by puneetlath** [comment]
Still on the list. I'll get to it eventually.

**Comment by puneetlath** [comment]
Still on the list. I'll get to it eventually.

**Comment by puneetlath** [comment]
Still on the list, but not at all urgent. I'll get to it eventually.

**Comment by puneetlath** [comment]
Still on the list, but not at all urgent. I'll get to it eventually.

**Comment by puneetlath** [comment]
I'm thinking this bug isn't worth fixing at this time. If we find that users want to name workspaces like this, we can update. Going to close for now, but reopen if you disagree!
