### ISSUE TITLE
Web - Opening participant link after canceling task and reloading opens the page and also reopens the task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click assign task
3. Add any title, select any assignee and share somewhere user and confirm task
4. Click on task title and open members
5. Copy link and send to any report
6. Cancel the task and again click on header, observe that members page is not available
7. Click on link copied in step 5, observe that it shows 'Hmm its not here' page which is correct
8. Reload and observe that now links shows the members and also it has reopened the task

## Expected Result:
Members link after cancelling task should always display 'Hmm its not here' error page

## Actual Result:
Members link after cancelling task displays 'Hmm its not here' error page but on reload, displays the members and reopens the task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1da6aaa5-0b5c-48c5-bdad-200f94cd972a

https://github.com/Expensify/App/assets/115492554/8e2e9f97-5658-43c8-a74c-6c865c89947a

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692078006562579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
@michaelhaxhiu based on this https://expensify.slack.com/archives/C049HHMV9SM/p1692638091245089?thread_ts=1691652004.473889&cid=C049HHMV9SM should be on hold 
and also If we decide to proceed, reported may need to be updated to @tewodrosGirmaA pls double check before proceeding

**Comment by thienlnam** [comment]
Closing as this is flow is known to be broken as we're updating it https://github.com/Expensify/App/issues/19504
