### ISSUE TITLE
Web - New line marker on Task does not disappear when sending or receiving a message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25776]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat that have a task shared to it or create a Task on the chat.
2. Mark us unread the Task
3. Send a message on the chat / or recieve a message on the chat

## Expected Result:
New line marker should disappear when receiving a message or sending a message

## Actual Result:
New line marker does not disappear when receiving a message or sending a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-18

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1713fc81-801a-4ab4-addd-21e20e2f3a53

https://github.com/Expensify/App/assets/115492554/da3c0fc0-bce8-4574-adaf-eb66fd20d869

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692752785781209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
@dukenv0307 Thank you so much for looking into this. Were you by any chance able to find what caused this regression to happen?

**Comment by tgolen** [comment]
Ah, yes. That looks to be it. I haven't been familiar with this code in a long time. I am concerned that the solution that you propose could have other potential side-effects that we don't know about. 

What is your gauge on how risky of a change it is to do `lastReadTime <= lastVisibleActionCreated` and that it could lead to more regressions? 

I'm also considering that we should revert that refactoring PR as it seemed tied to several regressions.

**Comment by s-alves10** [comment]
I think we should revert the PR

**Comment by tgolen** [comment]
Yeah, I mostly agree with you. It sounds like there have been a couple of follow-up PRs to fix other blockers from it that would also need to be reverted, so we are evaluating now what kind of a mess we are in and how best to get out of it.

**Comment by tgolen** [comment]
All right, we have decided to revert the original PR for now. It turned out there were no other post-fixes that needed reverting.

**Comment by roryabraham** [comment]
According to @MonilBhavsar, [this is expected behavior](https://expensify.slack.com/archives/C01GTK53T8Q/p1692808647068239?thread_ts=1692806022.487569&cid=C01GTK53T8Q), not a 🐛 

Closing this out.
