### ISSUE TITLE
[$1000] Prevent potential duplication of adding the event listeners

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#25775]
https://github.com/Expensify/App/pull/19263#discussion_r1220310077
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01240734a875b0971d</li>
        <li>Upwork Job ID: 1694369600595484672</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
@johncschuster this issue was already fixed here https://github.com/Expensify/App/pull/22991 but we didn't have an issue for it. We just need to pay out @0xmiroslav for his role as C+

**Comment by MitchExpensify** [comment]
Un-assiging myself as John is on BZ too and got lucky first 😄 (Happy to take if I'm missing something though!)

**Comment by johncschuster** [comment]
# Payment Summary:
 External issue reporter - NA
 Contributor that fixed the issue - NA
Contributor+ member who reviewed the PR - @0xmiroslav - $1000 via Manual Request

cc @JmillsExpensify

**Comment by stitesExpensify** [comment]
bump @johncschuster

**Comment by johncschuster** [comment]
Thanks for the bump! I'll get payment issued now.

**Comment by johncschuster** [comment]
@0xmiroslav I've invited you to the job on Upwork. Can you ping me when you've accepted so I can complete the payment? Thank you!

**Comment by johncschuster** [comment]
Hey @0xmiroslav, I can see we've had a discussion about the Upwork profile that we can invite to jobs. I've located your profile on Upwork and have invited that to the job. Please accept that and ping me once you've done that. Thanks

**Comment by johncschuster** [comment]
Not overdue. We're just working on payment.

**Comment by stitesExpensify** [comment]
Same ^

**Comment by johncschuster** [comment]
Getting on the same page, [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694206723155449).

**Comment by stitesExpensify** [comment]
not overdue

**Comment by johncschuster** [comment]
@0xmiroslav I'm going to close this issue. Can you please reopen it and ping me as soon as you're ready to accept payment?
