### ISSUE TITLE
[$500] Workspace - An error occurs when deleting a participant if the WS name has been changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25791]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
You must be logged in under applause.expensifail.com.
Step:
1. Open a New Expensify application
2. Create a new workspace
3. Change the WS name to "230801".
4. Go to Settings -> Workspaces -> Manage members
5. Invite randomly few members
6. Select any member and delete

## Expected Result:
The member must be removed without failures or errors occurring

## Actual Result:
When deleting a member an error occurs, when reloading the application the error does not disappear and goes into a permanent reboot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-18

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/51af264e-ce91-4c2a-9e0f-1727140c5956

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f5d22eed102a827</li>
        <li>Upwork Job ID: 1697061391421444096</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
Seems a backend issue where `oldPolicyname` returns as a number when the workspace name only contains digits. It should be a string.

<img width="810" alt="Screenshot 2023-08-23 at 23 27 55" src="https://github.com/Expensify/App/assets/14358475/d658eaca-0b89-443f-a8fe-c8661ebee28c">

<img width="1223" alt="Screenshot 2023-08-23 at 23 30 11" src="https://github.com/Expensify/App/assets/14358475/3427f7c8-ec8c-44a0-828b-6fd423ab55ea">

**Comment by anmurali** [comment]
Able to reproduce on Android native

**Comment by anmurali** [comment]
Maybe @yuwenmemon can review https://github.com/Expensify/App/issues/25791#issuecomment-1705228477

**Comment by yuwenmemon** [comment]
Yeah, it's a back-end issue. Simple fix. One sec.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by yuwenmemon** [comment]
Closing this out as it's fixed.
