### ISSUE TITLE
[hold for payment 2023-08-30] [$1000] Google icon on sign in page shows overflow horizontal scrolling bars

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#25797]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to sign in page
2. See bars

![2023-08-23_09-57-01](https://github.com/Expensify/App/assets/32969087/727989e5-001f-4bcb-992a-69c2afc22372)

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (IT IS A NEW FEATURE)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150e862176e606409</li>
        <li>Upwork Job ID: 1694758363108376576</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@0xmiroslav has a solution here: https://expensify.slack.com/archives/C049HHMV9SM/p1692821650897609?thread_ts=1692820693.322909&cid=C049HHMV9SM

Sounds about right to me.

**Comment by roryabraham** [comment]
This is fixed, we just need to issue payment to @0xmiroslav

**Comment by joekaufmanexpensify** [comment]
Sounds good! We'll issue payment 7 days from when the PR was deployed to production (so on 2023-08-30).

**Comment by joekaufmanexpensify** [comment]
Date is wrong here. This was deployed to prod on 2023-08-23.

**Comment by joekaufmanexpensify** [comment]
@0xmiroslav mind completing the BZ checklist when you have a sec so we can prep to issue payment? TY!

**Comment by joekaufmanexpensify** [comment]
BZ checklist is complete!

**Comment by joekaufmanexpensify** [comment]
Only payment we need to make here is $1,500 to @0xmiroslav. $1,000 for their PR, and then $500 speed bonus since this PR was merged in less than one day!

**Comment by joekaufmanexpensify** [comment]
Sounds good! LMK once you're ready to proceed.

**Comment by joekaufmanexpensify** [comment]
@0xmiroslav is payment here still held?

**Comment by joekaufmanexpensify** [comment]
Got it, ty!

**Comment by luacmartins** [comment]
Maybe we can combine all held payment in a single tracking issue and close this one?

**Comment by joekaufmanexpensify** [comment]
@0xmiroslav Do you expect the issue to be resolved soon? If it's going to be this week, IMO it feels simpler to just wait and pay this. But if not, agree it may make sense to look into consolidating.

**Comment by joekaufmanexpensify** [comment]
@0xmiroslav any update here?

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good. TY!
