### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Web - Inconsistency bug: Incorrect Hand Cursor Displayed Throughout PDF Document in Attachment Viewer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Go to any conversation
2) Click the plus sign -> Add Attachment and select a pdf file, but do not send it yet
3) go to the PDF body within the previewer
4) Notice that the cursor behavior is correct in the previewer, with the hand cursor only displayed when hovering over hyperlinks or interactive elements
5) Send the attachment
6) Click the same attachment you sent to open it in the attachment viewer
7) In the attachment viewer, observe that the hand cursor is displayed throughout the entire PDF document, even in areas where there are no hyperlinks or interactive elements

## Expected Result:
The hand cursor should only be displayed when hovering over hyperlinks or other interactive elements within the PDF document, both in the initial attachment previewer and the attachment viewer. When the mouse cursor is not over any interactive element, it should display the default cursor.

## Actual Result:
The hand cursor is displayed throughout the entire PDF document in the attachment viewer, unlike the correct behavior observed in the initial attachment previewer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-20

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6ae3a50b-a3a0-47fd-9197-30f2c5c58e34

https://github.com/Expensify/App/assets/115492554/5e9d60b2-6cbc-4424-9827-79efb552c5ba

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Habben101

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691710745839059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103449447ce220c8a</li>
        <li>Upwork Job ID: 1696237688336969728</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26416157</li>
</ul></li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
clarifying in slack

https://expensify.slack.com/archives/C049HHMV9SM/p1692917109070339?thread_ts=1691710745.839059&cid=C049HHMV9SM

**Comment by ArekChr** [comment]
Thanks for the proposals! The [proposal](https://github.com/Expensify/App/issues/25796#issuecomment-1690537757) from @namhihi237 looks good to me!

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by srikarparsi** [comment]
Thanks @ArekChr! @namhihi237's proposal looks good to me as well.

**Comment by ArekChr** [comment]
- [x] Link to the PR: https://github.com/Expensify/App/pull/20798
- [x] Link to comment: https://github.com/Expensify/App/pull/20798/files#r1315689912
- [x] Link to discussion: no discussion.
- [x] Determine if we should create a regression test for this bug: I think we can create a simple regression test.

**Regression test proposal** 

1. Go to any conversation with a PDF attachment.
2. Open the attachment preview.
3. Ensure that cursor behaviour is not hand cursor when hovering different elements than hyperlinks.

Do we agree 👍 or 👎

**Comment by kevinksullivan** [comment]
Waiting on payment

**Comment by kevinksullivan** [comment]
Paid and closed!

**Comment by Habben101** [comment]
@kevinksullivan, I'm the reporter of the bug, and I already applied for the job on Upwork, but haven't heard from anyone since then.

**Comment by kevinksullivan** [comment]
Ah my apologies @Habben101 . Offer sent! Lmk when you accept and I'll get that paid.

**Comment by Habben101** [comment]
No worries and Thanks @kevinksullivan. I've accepted the offer.
