### ISSUE TITLE
[$1000] Web - Avatar Unresponsiveness When Starting New Chat with New Email

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences and select "Force Offline".
2. Click on the plus sign to start a new chat.
3. Enter a new email address that has not been used before.
4. Observe that the avatar is unresponsive when hovering over it.
5. Go back to Settings > Preferences and make the app online again.
6. Observe that the avatar becomes responsive.

## Expected Result:
When starting a new chat with a new email address in offline mode, the avatar should be clickable.

## Actual Result:
The avatar for a new email address is unresponsive when starting a new chat in offline mode, causing inconvenience and delays in the chat initiation process. It only becomes clickable when the app is made online again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-21

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/322e4516-5657-46bb-b6c4-41578b8bae20

https://github.com/Expensify/App/assets/115492554/470953f9-7cf2-4312-b1e8-0264cd3669c2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @TewodrosGirma

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691865229111559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e68c9c10badb847</li>
        <li>Upwork Job ID: 1695127246029086720</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
@fedirjh @stephanieelliott maybe https://github.com/Expensify/App/pull/24091 this is expected??

**Comment by kameshwarnayak** [comment]
Looks like an expected behaviour. This PR https://github.com/Expensify/App/pull/23802 disables go to profile page for optimistic user
