### ISSUE TITLE
[$500] [HOLD for payment 2023-09-04] App crashes when reciever clicking on an edited money request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account.
2. Open User B's chat.
3. Navigate to the "Request money" section.
4. Enter an amount and request it.
5. Click on the requested money for more details.
6. Click on the description and make edits.
7. Open another browser and log in with User B's account.
8. Open User A's chat and click on the requested money.
## Expected Result: 
The app should not crash when clicking on a money request
## Actual Result: 
The app sometimes crashes when clicking on an edited money request

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-20
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/94e4c80c-6819-4f37-a802-bfc418aef0ec

https://github.com/Expensify/App/assets/43996225/b37a3a70-825e-4734-9ed5-5d43ffc1a0f8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692715648838749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191301f942c66eea9</li>
        <li>Upwork Job ID: 1699462033500999680</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
I'm trying to repro this, but it's not happening for me.

Unless there is a consistent reproduction maybe we should demote it?

What account are we using to make these requests? With the email address associated with it we can check server logs to see if there's more information to go off of.

**Comment by marcaaron** [comment]
@aldo-expensify any luck in reproducing this?

**Comment by aldo-expensify** [comment]
Reproduced in staging, but I'm failing on dev

**Comment by aldo-expensify** [comment]
<img width="733" alt="image" src="https://github.com/Expensify/App/assets/87341702/1fe49c93-8754-4e00-9118-68bf4576f0bb">

**Comment by marcaaron** [comment]
Are you testing on dev with the `staging` branch or `main`?

**Comment by aldo-expensify** [comment]
> Are you testing on dev with the staging branch or main?

`main` branch

I reproduced in staging using with expensifail accounts, I had the account B already logged in when I created the money request. My steps:

1. Login both accounts in different browser sessions
2. Request money with account A without setting a description
3. Modify the description
4. With account B, click the IOU report in the LHN -> crash

**Comment by marcaaron** [comment]
Tested on web and this is working so I think we are good here. Thanks for the help everybody!

**Comment by mountiny** [comment]
reopening just for the payment for reporting to @ayazhussain79

**Comment by puneetlath** [comment]
Just marked External to generate the Upwork job. 

Looks like we just need to pay @ayazhussain79 for the bug report here. @ayazhussain79 can you please apply to it? 

Anyone else, let me know if I missed you!

**Comment by ayazhussain79** [comment]
@puneetlath Applied on upwork

**Comment by puneetlath** [comment]
Offer sent!

**Comment by ayazhussain79** [comment]
Offer accepted. Thank you!
