### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000] Web - No Transition animation for task assignee/share-somewhere modal

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB, Click Assign task
2. Enter title, click continue.
3. Click on Assignee Option, see there is no animation.
4. Click on Share somewhere, see there is no animation.

## Expected Result:
There should be animation for the 2 screen/modals

## Actual Result:
No Animation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-21

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/864ef5c8-4ab8-490a-a1a3-43aae196cb30

https://github.com/Expensify/App/assets/115492554/cb92a10c-f6fb-41e5-b6c3-8e3aa3a2f09e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @b4s36t4

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691873619811189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d36654a811c7c838</li>
        <li>Upwork Job ID: 1696763981295181824</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26515110</li>
<li>b4s36t4 | Reporter | 26515112</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
## Proposal from @b4s36t4
### Please re-state the problem that we are trying to solve in this issue.
No Transition animation for task assignee/share-somewhere modal
### What is the root cause of that problem?
RCA for this issue is with the inputs we have inside these modals which are getting instant focus causing the break in animation.
### What changes do you think we should make in order to solve the problem?
We can solve this issue with two methods
1. Using `shouldDelayFocus` prop should do that work.
2. Using the ref to access `textInput` ref inside the `BaseOptionsSelector` component and focus the input after animation done inside the `onEntryTransitionEnd` prop for `ScreenWrapper` component.
Reference: https://github.com/Expensify/App/pull/22217 Kind of same issue.

### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment]
Fair enough. I'm triaging this one.

**Comment by b4s36t4** [comment]
### Edits
Changes needed

```jsx
ref={(el) => (textRef.current = el)}
``` to be passed to `OptionsSelector` and using the ref to focus when `onEntryTransitionEnd` for `ScreenWrapper`.


https://github.com/Expensify/App/assets/59088937/e53a4cfe-9d79-4d8f-85b9-62da553fa77a

**Comment by b4s36t4** [comment]
Due to some issues I had to close first raised PR, created a new PR here #27220

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Issue reporter: @b4s36t4 $250
 - Contributor: @b4s36t4 $1,000
 - Contributor+: @rushatgabhane $1,000

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @rushatgabhane based on summary above.

**Comment by JmillsExpensify** [comment]
@b4s36t4 Upwork offer sent!

**Comment by b4s36t4** [comment]
@JmillsExpensify accepted the offer.

**Comment by JmillsExpensify** [comment]
All paid out. Thank you!
