### ISSUE TITLE
Web - There is a validation error even though all fields are filled when creating a task with two open tabs in the browser

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. copy the URL and open it in the new tab
3. Click the + Icon from each tab
4. click Assign task from each tab
5. enter the task name from each tab
6. share with someone
7. click confirm from one of the tabs
8. open the second tab and edit the name(change the old name)
9. click confirm the task

## Expected Result:
The task from the second tab should work and create a new task

## Actual Result:
There is a validation error called "Please select with whom you want to share." even though the task is shared with someone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.56-21

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/59247d52-8675-429e-89e4-6a5a8e04573a

https://github.com/Expensify/App/assets/115492554/29cc8809-b28a-4f4f-a0c9-4fcd0974c8ef

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691996230083289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I think there's a more fundamental issue here, which is that you can only create a single task across multiple NewDot tabs. If I click `+ > Assign Task` in two different tabs, that should allow me to create two separate tasks. I'm going to bring up in Slack to figure out how to move forward on this.

**Comment by sakluger** [comment]
This is no longer reproducible! Closing.
