### ISSUE TITLE
Unread "new" mark appears after request money or pay elsewhere

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as User A and User B in front of you at the same time.
2. As User A request Money from User B
3. Notice the "new" mark appears in top of the request message.
4. As User B Open the same chat and click Pay elsewhere.
5. Notice the "new" label for both users.
## Expected Result: 
Unread "new" mark shouldn't appear for User A after requesting Money, as the user still in the chat  and the unread "new" mark shouldn't appear while the chat is open unless the User mark it as unread.
And the same should happen for User B the unread "new" mark shouldn't appear after clicking Pay elsewhere.
## Actual Result: 
The unread mark appears for User A after requesting money.
It also appears for User B after clicking Pay elsewhere.
After User B Clicked Pay elsewhere the unread mark removed for User A.
if it is an intended behavior to show the unread mark after requesting money, then It shouldn't be removed for User A after User B click Payelsewhere.
And If the unread mark appears because a new reply added to the money request message, then it should appears if User B open the IOU report and reply in it, and this is not happening.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-20
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 14-08-23 18_35_32 (2).webm](https://github.com/Expensify/App/assets/43996225/4b0a1001-371b-474a-a14b-4433df3a3e27)

https://github.com/Expensify/App/assets/43996225/b81d9634-8f7a-4546-8649-21932957942f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692028939059869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
Unread "new" mark appears after request money or pay elsewhere.

### What is the cause of this issue?
We uses `ReportUtils.isUnread` function to check whether report is unread or not, and if report is unread, a new line marker is displayed.
https://github.com/Expensify/App/blob/f68755cf202eb56b0bead752ddba4d037a57032e/src/libs/ReportUtils.js#L2468-L2470

If user A requests money to user B, user A's app sends `RequestMoney` API to BE, and then BE returns a response to user A and pushes an event to user B.
These response and event contains `report` information which `lastReadTime` is smaller than `lastVisibleActionCreated`.
![pay1](https://github.com/Expensify/App/assets/131836113/dfb2a650-7ce0-4db4-aec7-df93448dd11a)
![pay2](https://github.com/Expensify/App/assets/131836113/d241fdf3-bdf2-4460-b419-80dd69d8cf96)

Hence, the new line marker is displayed on both user A and user B sides.

For `PayMoneyRequest` API, the situation is exactly the same.
![request1](https://github.com/Expensify/App/assets/131836113/c73da256-4eb7-4510-98f0-dafc26ffb85a)
![request2](https://github.com/Expensify/App/assets/131836113/5cb3eaf7-a132-4308-ac74-4ce41d7784ab)

### What changes do you think we should make to solve the problem?
The new line marker should appear on user B side, and in this case `lastReadTime < lastVisibleActionCreated` is correct.
But for user A, the new line marker should not appear.

We can add additional `onyxData` to the `RequestMoney` or `PayMoneyRequest` API request's `successData` to set report's `lastReadTime` to `null`
```
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${chatReport.reportID}`,
            value: {
                lastReadTime: null,
            },
        },
```
in [this line](https://github.com/Expensify/App/blob/74be5f627511410373f926c76e50f98c459e93e5/src/libs/actions/IOU.js#L155) and [this line](https://github.com/Expensify/App/blob/74be5f627511410373f926c76e50f98c459e93e5/src/libs/actions/IOU.js#L1570)

After API success, report's `lastReadTime` is set to `null` on user A side, so `ReportUtils.isUnread` returns `false`, and the new line marker does not appear.
Once user have read the report, the `lastReadTime` will be set to correct time, and this will be greater than `lastVisibleActionCreated`.
Therefore new line marker does not appear on user A side.

### What alternative solutions have you investigated? (Optional)
None.

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
Unread "new" mark appears after request money or pay elsewhere.

### What is the cause of this issue?
We uses `ReportUtils.isUnread` function to check whether report is unread or not, and if report is unread, a new line marker is displayed.
https://github.com/Expensify/App/blob/f68755cf202eb56b0bead752ddba4d037a57032e/src/libs/ReportUtils.js#L2468-L2470

If user A requests money to user B, user A's app sends `RequestMoney` API to BE, and then BE returns a response to user A and pushes an event to user B.
These response and event contains `report` information which `lastReadTime` is smaller than `lastVisibleActionCreated`.
![pay1](https://github.com/Expensify/App/assets/131836113/dfb2a650-7ce0-4db4-aec7-df93448dd11a)
![pay2](https://github.com/Expensify/App/assets/131836113/d241fdf3-bdf2-4460-b419-80dd69d8cf96)

Hence, the new line marker is displayed on both user A and user B sides.

For `PayMoneyRequest` API, the situation is exactly the same.
![request1](https://github.com/Expensify/App/assets/131836113/c73da256-4eb7-4510-98f0-dafc26ffb85a)
![request2](https://github.com/Expensify/App/assets/131836113/5cb3eaf7-a132-4308-ac74-4ce41d7784ab)

### What changes do you think we should make to solve the problem?
The new line marker should appear on user B side, and in this case `lastReadTime < lastVisibleActionCreated` is correct.
But for user A, the new line marker should not appear.

We can add `RequestMoney` and `PayMoneyRequest` API request's `successData` in [this line](https://github.com/Expensify/App/blob/74be5f627511410373f926c76e50f98c459e93e5/src/libs/actions/IOU.js#L155) and [this line](https://github.com/Expensify/App/blob/74be5f627511410373f926c76e50f98c459e93e5/src/libs/actions/IOU.js#L1570) to set report's `lastReadTime` to `null`.
```
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${chatReport.reportID}`,
            value: {
                lastReadTime: null,
            },
        },
```


After API success, report's `lastReadTime` is set to `null` on user A side, so `ReportUtils.isUnread` returns `false`, and the new line marker does not appear.
And then OpenReport API is called, so `lastReadTime` will be set to correct time, and this will be greater than `lastVisibleActionCreated`.
Therefore new line marker does not appear on user A side.

### What alternative solutions have you investigated? (Optional)
None.

**Comment by muttmuure** [comment]
Will take a look later this week

**Comment by muttmuure** [comment]
Going to bump down to weekly

**Comment by muttmuure** [comment]
I'm not convinced this is a bug since request money and pay elsewhere are new unreads

**Comment by Ahmed-Abdella** [comment]
@muttmuure It appears for the user who send the request, that is what this issue descripe. Please check again if you have time

**Comment by Ahmed-Abdella** [comment]
New reproducing video, because the behavior is different now after adding some features after the issue reported

- You have to request money twice like this video

[Screencast from 26-09-23 06:19:36.webm](https://github.com/Expensify/App/assets/77763699/a06eaf5a-39c3-458d-b15d-23c3dcb9f5dd)

**Comment by Ahmed-Abdella** [comment]
@muttmuure Could you plz check this again with the comments above with the steps to reproduce this in the video, I discuss this with @Julesssss and he confirms that this is a valid bug. Thanks
