### ISSUE TITLE
[HOLD for payment 2023-11-29] Bump E/App and Onyx to use NodeJS 20.9.0 LTS

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#25824]
# Problem

Both E/App and Onyx repos currently enforces developers to use NodeJS 16.15.1. [As of September, NodeJS 16.x will reach its End-of-life (EOL)](https://github.com/nodejs/release#release-schedule), meaning there will be no more updates, patches, or security fixes. Additionally, [the future React Native 0.73 version will require using NodeJS 18.x](https://github.com/reactwg/react-native-releases/discussions/64).

Using an outdated version of NodeJS not only exposes the application to potential security vulnerabilities, compatibility issues, and prevents developers from leveraging the latest features, optimizations, and improvements available in newer versions of NodeJS, but it will also block us from updating the App to RN 0.73 or higher versions.

# Solution

Upgrade both repos to require NodeJS 18.17.1 (or 18.x) and NPM 9.6.7. This will ensure that the application remains secure, compliant, in line with best practices for software development and will allows us to continue updating our app to latest RN versions.

# Plan

**For react-native-onyx:**
1. Change `package.json` to require NodeJS `18.17.1` and NPM `9.6.7`.
   1. Alternatively, since this is a open-source library we could relax the version enforcement to only `18.x`, in this way developers/companies who uses Onyx don't need to use a strict version, just the LTS release.
1. Change `.nvmrc` to require `18.17.1` (or `v18`).
1. Change `publish.yml`, `test.yml` and `lint.yml` to use the node version from `.nvmrc` file instead of hardcoded version.

**For E/App:**
1. Change `package.json` to require NodeJS `18.17.1` and NPM `9.6.7`.
1. Change `.nvmrc` to require `18.17.1`.
1. Change `TestSpec.yml` to use `.nvmrc` (if possible) or `18.17.1`.
1. Fix `build-desktop.sh` to drop `npm bin` usage [since it was removed in NPM 9.x](https://github.com/npm/cli/releases/tag/v9.0.0), and use `npx` instead.

# Tests

I forked Onyx to use `18.17.1` and used my own release in E/APP in order to test the changes and I was able to install the dependencies and build for all platforms. When running tests I got some dependency errors about node version mismatched in installed packages, was able to resolve the issues by running `npm rebuild` (probably just removing `node_modules` and reinstalling would work as well).

I also didn't have any issues with dependencies auto-updating or changing `package-lock.json`.

**Comment by fabioh8010** [comment]
@AndrewGable @roryabraham Based on this idea posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1692277812800739

**Comment by AndrewGable** [comment]
Looks great!

**Comment by Tony-MK** [comment]
Hey, I would love to work on the issue. Can I get assigned? Do I need to post proposal?

**Comment by AndrewGable** [comment]
@fabioh8010 is assigned and will be working on this one. 👍

**Comment by fabioh8010** [comment]
@AndrewGable

@pac-guerreiro Will take the issue over! Could you assign him?

**Comment by roryabraham** [comment]
On HOLD until after the merge freeze

**Comment by AndrewGable** [comment]
@fabioh8010 - Can you have him comment here? Thanks.

**Comment by pac-guerreiro** [comment]
Hi @AndrewGable, I can take this 😄

**Comment by roryabraham** [comment]
BTW, I think this issue is a bit lower urgency, so due of the backlog of issues that we have been HOLDing the last couple weeks, I suggest that we wait until a few days after the merge freeze is lifted to take this off HOLD. That way we don't have a huge amount of PRs merged all on the same day and end up with a massive release that's very hard to ship

**Comment by kevinksullivan** [comment]
What's the latest here @pac-guerreiro ?

**Comment by roryabraham** [comment]
What's the status here?

**Comment by roryabraham** [comment]
Looks like I just forgot to take this off HOLD after the merge freeze. Let's get this one finished up. co-assigning myself to help track progress

**Comment by roryabraham** [comment]
Also, I'm wondering if we should beat around the bush or should go straight to the newest LTS version. Node.js 20 just became active LTS _today_, so I'm going to update the issue title to say we should standardize on the latest LTS.

<img width="1007" alt="image" src="https://github.com/Expensify/App/assets/47436092/60fa8861-591b-49fd-8901-4b6c28e6acba">

**Comment by pac-guerreiro** [comment]
Sounds good to me, I can work on these changes. I'll have to apply the changes to onyx first.

**Comment by pac-guerreiro** [comment]
Github actions started supporting node20 last week

**Comment by pac-guerreiro** [comment]
@roryabraham I just created two draft PRs with the changes applied to both react-native-onyx and expensify-app 😄

**Comment by roryabraham** [comment]
Let us know when they're ready for review

**Comment by pac-guerreiro** [comment]
@dylanexpensify @roryabraham The PR for Onyx is now open! The one for the app will remain in draft until the Onyx one is merged because until this happens, the app will throw compatibility errors with Onyx because of node version

**Comment by pac-guerreiro** [comment]
@DylanDylann @roryabraham 

I addressed the feedback on the PR for Onyx! Let me know if there is anything else that needs to be taken care of and sorry for the time this has been taking to be merged.

**Comment by roryabraham** [comment]
This is done now, just awaiting deploy to production (even though it mostly affects dev/test environments)

**Comment by roryabraham** [comment]
Looks like none of the PRs underwent C+ review, so we can close this.

**Comment by roryabraham** [comment]
No regression tests needed

**Comment by roryabraham** [comment]
> Can you send an action required email to internal engineers on this?

I think @arosiclair sent one
