### ISSUE TITLE
Native Share Menu UI Tweaks

### ISSUE THREAD

**Issue by grgia** [Expensify/App#25823]
Coming from https://docs.google.com/document/d/1m4BZ-fhNMnTQhWiglqMk9U2VXYDSrirjeYRLPHf3SkA/edit#heading=h.ns12dr1f35rx

Infinite Red has made major progress on the design doc and has[ proposed a few tweaks to the UI](https://expensify.slack.com/archives/C04KQL2HSQ1/p1692051717733899?thread_ts=1691534718.106969&cid=C04KQL2HSQ1). 

I can handle most of these, but I'm making an issue to make sure this gets done.

Namely:
- Updated the TextField to:
  - Have a label, so that it looks more clear what it is if it's pre-filled because we're sharing text
  - Be multiline.
- Changed the label on the attachment preview to "Attachment" to distinguish it more clearly from the message.
- Change "send a message" to "send an optional message"

Current: 
![image](https://github.com/Expensify/App/assets/38015950/0465ed19-5a1d-45ae-becd-7ffb7ff1efc8)

Example of the proposed case :

<img width="611" alt="image" src="https://github.com/Expensify/App/assets/38015950/6a364b2b-a021-4b44-bb73-261484a7e0b6">

The Figma is here - https://www.figma.com/file/qZ8Ynbx2XZOlQC4prN9Nwc/Native-Share-Menu?type=design&node-id=1%3A2&mode=design&t=2ooFRbrQqTzQbZfB-1

**Comment by dannymcclain** [comment]
@grgia I think these are looking good! Do you need anything specific from me to help with this?

**Comment by grgia** [comment]
@dannymcclain
From the chat in the figma file with @shawnborton, could we create an official component for multiline input? The one from this screenshot is one that infinite red mocked up. If that design is good, then great! 

<img width="287" alt="image" src="https://github.com/Expensify/App/assets/38015950/e744a6ec-cf08-4789-90c8-8468cf599ae5">
main question, do we want the box to continue to expand similar to the composer, or do we want to cut off the text at a point like in this mock?

**Comment by shawnborton** [comment]
I think it makes sense to give it a max-height so it doesn't infinitely expand.

**Comment by dannymcclain** [comment]
I think that design looks good.

It will be tricky to make the multiline component in Figma in a way that is flexible and not borky, but I'll look into it! I don't think we absolutely have to have that completed in Figma for this to move forward though. The default state will look identical to the "regular" input, and I think what's shown in that screenshot would be a pretty good max-height to set. Looks like it's around 4.5 lines. I like that it cuts off in the middle of a line of text (this can give people an indication that there's more if they scroll).

**Comment by shawnborton** [comment]
I think with Figma's new max-height (and width) feature, we might be able to get cheeky with auto-layout and create something flexible!

**Comment by grgia** [comment]
> I think with Figma's new max-height (and width) feature, we might be able to get cheeky with auto-layout and create something flexible!
👀  any updates on this @dannymcclain @shawnborton

**Comment by dannymcclain** [comment]
I'll try to investigate today!

**Comment by dannymcclain** [comment]
@grgia Just published a first draft of the multiline component: https://expensify.slack.com/archives/C03TME82F/p1693588298231449

**Comment by dannymcclain** [comment]
@grgia You can find it here: https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Expensify-Design-System-2022?type=design&node-id=649-3979&mode=design&t=rYu5aJea7y3QvSm4-11

It's a published component so you can also pull it in via the Expensify Design System 2022 library file.

**Comment by grgia** [comment]
I still need to update the doc, have been focused on wave 8

**Comment by dannymcclain** [comment]
IT'S FINE MELVIN 🤖. @grgia should this get changed to weekly?

**Comment by grgia** [comment]
Apologies @dannymcclain I haven't been able to prioritize this project. I'll take a look before EOW and get this closed
