### ISSUE TITLE
[HOLD for payment 2023-08-25] Request money - App on recipient end crashes when receiving money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. As User A, initiate a chat with User B (no conversation history).
3. As User B, open the chat with User A.
4. As User A, click + on the composer > Request money to User B

## Expected Result:
App does not crash

## Actual Result:
App on User B's end crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2f920434-0371-4bc7-9456-6ab87a660110

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692854859950599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@spcheema can you link the PR and look into this?

**Comment by mountiny** [comment]
@Natnael-Guchima updated

PR merged

**Comment by Natnael-Guchima** [comment]
Thanks 🙌

**Comment by mountiny** [comment]
@isabelastisser we should be good to pay @Natnael-Guchima for reporting

**Comment by mountiny** [comment]
Tested on web staging and its fixed

**Comment by isabelastisser** [comment]
@Natnael-Guchima I sent you the offer in Upwork, please accept it and I will process the payment. Thanks!

**Comment by Natnael-Guchima** [comment]
I have accepted the offer. Thanks @isabelastisser
