### ISSUE TITLE
[$1000] Web - Inconsistency in the email's content when verifying the new contact method.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account.
2. Go to Settings >> Profile >> Contact method >> choose New contact method.
3. Provide the new Contact method and click Add >> check the email's content.
4. Click on the "Didn't receive a magic code?" option to get a new verification code >> check the email's content.
5. Observation: The email content in step 3 and step 4 is not consistent.

## Expected Result:
The email content sent in step #4 should be similar to the email sent in step #3, in order to avoid confusion with the magic code used for login.

## Actual Result:
There is inconsistency in the email content between step #3 and step #4. The email’s content at step #4 is confusing because it appears the same as the email used for login.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![AddNewContactMethod](https://github.com/Expensify/App/assets/115492554/a2d1d544-ec98-44a5-98ae-78c35b923f5f)

![RequestContactMethodValidateCode](https://github.com/Expensify/App/assets/115492554/e44a5907-919f-4f41-872d-a11b6a1279e6)

https://github.com/Expensify/App/assets/115492554/5967c503-30c0-455c-97be-e84a1792b23d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692036965973929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01624b023e6db373cc</li>
        <li>Upwork Job ID: 1696962559910027264</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
sorry for the delay on this one. there were some other things that i needed to prioritize over this, but let me try to repro now!

**Comment by maddylewis** [comment]
Okay, so when i add a Secondary Login, I receive an email titled `Verify secondary email for Expensify`:
<img width="1104" alt="image" src="https://github.com/Expensify/App/assets/38016013/11e999cd-2423-4ccb-aee7-7637c12a10f7">

And, if i click `Didn't receive magic code?`, I receive a new email titled `Your magic sign-in link for Expensify`: 
<img width="1105" alt="image" src="https://github.com/Expensify/App/assets/38016013/f0dca597-e49b-4710-8065-7c921623a619">

**Comment by maddylewis** [comment]
I don't think this is necessarily a bug. asking about this here.

**Comment by tranvantoan-qn** [comment]
Please note about the attached link too.
The link in the 2nd can not be used for secondary email validation too.

**Comment by b4s36t4** [comment]
Is this supposed to be external? I don't think email templates/email related triggers are related App. @maddylewis maybe this has to be internal.

**Comment by mananjadhav** [comment]
@maddylewis This would have to be internal because email content is sent from the backend.

**Comment by maddylewis** [comment]
@mountiny - my friend, Vit! i _think_ i am meant to add the `Engineering` label to internal issues. But, lmk if I'm mistaken and i will go about triaging this differently!

**Comment by mountiny** [comment]
All good

@NikkiWines Do you know if this is a regression or maybe this loophole was missed? Would you be interested in taking this one over as you go experience with these? No problem if not 😄

**Comment by mountiny** [comment]
asked in DM

**Comment by NikkiWines** [comment]
👋 sorry for the delay 

> @NikkiWines Do you know if this is a regression or maybe this loophole was missed? Would you be interested in taking this one over as you go experience with these? No problem if not 😄

I wasn't involved in this flow, but I'd guess that it was either overlooked or just not considered important when we added the `Didn't receive a magic code` link to the Add Contact Methods page. The code that the user receives still works, but I agree the copy is a little weird given the flow they're in.

This occurs because we call two different commands (`AddNewContactMethod` and `RequestContactMethodValidateCode`) which use two distinct templates (`SecondaryLoginAdd` vs. `SendValidateCode`) to send the code in the backend. 

The latter command ultimately calls [this function](https://github.com/Expensify/Auth/blob/6393fdd9d3b95c894ba4fdc0614909d5a02ea616/auth/lib/Account.cpp#L685-L743) which does support using different templates depending on a number of factors. We could adjust it to use the `SecondaryLoginAdd` template (or a new template like `SendValidateCode` but specific to secondary logins).

Ultimately though I think it's fine to leave as is. Kind of a "nice to have" fix. FWIW, expensify.com has the same behavior

**Comment by mountiny** [comment]
Ok, really appreciate this, I think I agree that this is super low priority and we can focus on this kind of polish after reunification
