### ISSUE TITLE
[$1000] Web -  Number of replies are not dynamically updating when user adds comments by editing description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make a money request from account A to account B
2. Open the IOU details page by clicking on the IOU preview component twice on account A
3. Go to account A and post something and observe the reply count on account B
4. Change the amount first then description (observe the reply count on account B)
5. Reload the page on account B and observe the reply count again

## Expected Result:
Reply count should update dynamically without manual reloading

## Actual Result:
Reply count does not update dynamically if account A updates the IOU description field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/48f8c116-7756-489c-97a8-bce11140438c

https://github.com/Expensify/App/assets/115492554/0c2cfbc1-879b-45b1-bcbc-4e13f50bc10d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692047239826689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138b43dd9b2590146</li>
        <li>Upwork Job ID: 1697702739222093824</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Similar to https://github.com/Expensify/App/issues/25704#issuecomment-1696384768, seeing as this is low-priority and more of a "nice to have", I am reducing the payscale for this one to the following: 

- **Bug reporting bonus: $50
- Contributor fix: $250
- C+ proposal/PR review: $250**

Just noting this before I add the labels to accept proposals.

**Comment by stephanieelliott** [comment]
I agree that this is something we should fix, adding `External` label

**Comment by stephanieelliott** [comment]
Labels added, not overdue

**Comment by imranaalam** [comment]
### Problem Overview:

**Action Performed**:
1. Make a money request from account A to account B over the internet.
2. Open the IOU details page by clicking on the IOU preview component twice on account A.
3. Go to account A and post something and observe the reply count on account B (it increases).
4. Change the amount first then description (observe the reply count on account B) (it doesn't change).
5. Reload the page on account B and observe the reply count again (it changes now).

**Expected Result**:
Reply count should update dynamically without manual reloading, as observed in step 3.

**Actual Result**:
Reply count does not update dynamically if account A updates the IOU description field.

**Workaround**:
Unknown.

---

### Investigation Summary:

1. **Initial Code Inspection**:
   - We examined various files in the provided source code. Specifically, we looked at the logic in `IOU.js` related to setting the money request description and amount. Both functions (`setMoneyRequestDescription` and `setMoneyRequestAmount`) use `Onyx.merge` to update their respective properties in the Onyx store.
   
2. **Diving Deeper**:
   - We inspected the `TransactionUtils.js` file and identified the `getDescription` function. This function fetches the IOU description (or comment) from a transaction. A noteworthy comment in this function highlighted that the comment does not have a "modified" counterpart (`modifiedComment`).

3. **Key Insight**:
   - Many systems maintain both an original and a "modified" version of a property to track changes and activate actions like updates or notifications. The lack of a `modifiedComment` for the IOU description suggests that the system might not be recognizing or handling changes to this description in the same manner it does for other properties with both original and modified versions.

4. **Potential Issue**:
   - The absence of a `modifiedComment` counterpart could be a factor in the observed issue. If the system relies on discerning differences between original and modified versions to trigger real-time updates, not having such a mechanism for the IOU description might explain why the reply count doesn't dynamically update.

5. **Next Steps**:
   - Our plan was to delve into:
     - The tracking and handling of changes to other transaction properties (those with original and modified counterparts).
     - The mechanisms that instigate real-time updates or notifications for these properties.
     - The reasons the IOU description lacks a `modifiedComment` counterpart and how this absence might affect real-time update mechanisms.

**Comment by imranaalam** [comment]
**Problem Statement:**
Users are facing a real-time update issue. When they modify the IOU description, the reply count doesn't refresh automatically. They have to reload the page to see the updated count.

**Root Cause:**
Upon code inspection, it's evident that while there are mechanisms in place to dynamically update certain properties (like the money request amount), the IOU description lacks this functionality. Specifically, there's no `modifiedComment` counterpart for the IOU description, which suggests that description changes might not trigger real-time updates like other properties do.

**Proposed Solution:**
1. Introduce a `modifiedComment` counterpart for the IOU description. This should help in tracking changes and triggering real-time actions in the same way as other properties.
2. Ensure that components displaying the IOU description are subscribed correctly to the relevant Onyx key and are set up for dynamic updates.
3. Ensure that the backend/API is set up to send real-time updates to all clients when the IOU description is updated. This might involve a review of real-time communication protocols like websockets.

**Alternative Solutions Explored:**
We could consider a more global solution, where we have a universal change tracking system for all properties. This would involve a deeper integration and could potentially fix similar issues in other parts of the system. However, this would also be more complex and time-consuming to implement.

**Comment by stephanieelliott** [comment]
This has been open a while without many proposals, doubling the bounty on this one.

**Comment by pradeepmdk** [comment]
could you double-check the requirements? because now any changing action is not countable (replay count) 

you can check the latest version as per the bug video now Even if you changed the amount it does not count as a replay count.

**Comment by rojiphil** [comment]
> @izarutskaya @stephanieelliott is this still a valid bug?

I too have the same question. Is this still a valid bug?

**Comment by stephanieelliott** [comment]
I don't think this is happening anymore, I just retested and the reply count is now updating without having to reload the page 🎉

Tested on Chrome and Safari
