### ISSUE TITLE
g.lafond@gordian.com not receiving magic code emails 

### ISSUE THREAD

**Issue by isabelastisser** [Expensify/App#25857]
Current User: g.lafond@gordian.com
Account ID: 3647453

NewDot chat: https://new.expensify.com/r/285709290404372

- This is my managed customer. They cannot get into Expensify because they are not receiving our emails with the magic codes.

![image](https://github.com/Expensify/App/assets/31258516/55036a34-d08b-4e45-b4a5-4e10c0c773a0)

- I checked in Supportal and it shows that we've been sending them multiple emails with the magic code, but they claim that they can't locate those in their inbox. They checked spam/filters too and no success.

![image](https://github.com/Expensify/App/assets/31258516/baaa6915-d53f-4c45-9e30-bc0b547ffc59)

- I've sent them multiple sign-in links with magic codes, but they continue to get error messages when trying to log in.

![image](https://github.com/Expensify/App/assets/31258516/f594e6a5-efe6-4676-8018-56c212bb6955)

- They've raised this with their IT department, here's the latest:

![image](https://github.com/Expensify/App/assets/31258516/56559297-42aa-4999-ad70-49d7faab9e89)

![image](https://github.com/Expensify/App/assets/31258516/9b71cf95-8c88-4571-b908-79ad36f255be)

- I cleared magic code throttles and "removed" their email from Suppression list. Here's what I got:

![image](https://github.com/Expensify/App/assets/31258516/7a43e5c7-86b3-409d-b345-28fa850fd1e6)

![image](https://github.com/Expensify/App/assets/31258516/2ee41a58-c49a-4330-b565-ab8d2f742c7e)

**Comment by grgia** [comment]
cc @NikkiWines @johnmlee101 This user is not receiving magic code emails, do you have any ideas for what might be causing this or where I should look?

**Comment by isabelastisser** [comment]
This is solved, thanks @grgia !
