### ISSUE TITLE
[HOLD for payment 2023-09-06] [HOLD for payment 2023-09-04] [$1000] cursor should display as disabled on select all checkbox even if only non removable members are present

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces
2. click on new workspace button
3. go to members
4. hover on select all checkbox
## Expected Result: 
cursor should be display as disabled because there the member is admin
## Actual Result: 
cursor does not display as disabled
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/294f4e7d-5774-4b36-ade2-013815ca372f

https://github.com/Expensify/App/assets/43996225/5ce141ae-5f2c-4731-92b0-0a6350fa53a8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692778734596109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6456f8777d856ec</li>
        <li>Upwork Job ID: 1694799760529616896</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by UsamaPLUTON** [comment]
It sounds like the issue you're describing relates to the behavior of a "select all" checkbox in the Expensify app. Specifically, the cursor should appear as disabled when the "select all" checkbox is in a certain state, even if only non-removable members are present.

Before making changes, I will ensure you fully understand the current behavior. Understand how the checkbox behaves when there are removable and non-removable members present.

If the cursor behavior is controlled by CSS, update the relevant CSS rules to change the cursor style when the appropriate conditions are met. You might need to add a class to the checkbox or its parent element to trigger the cursor style change.

**Comment by UsamaPLUTON** [comment]
![image](https://github.com/Expensify/App/assets/143106862/d90032b4-cd34-4a60-90d9-5f8a4ff5d249)

**Comment by UsamaPLUTON** [comment]
85.vendors.chunk.js:1 <Item> with non-plain text contents is unsupported by type to select for accessibility. Please add a `textValue` prop.
i.getCollectionNode @ 85.vendors.chunk.js:1
Show 1 more frame
Show less
23670.vendors.chunk.js:1 An aria-label or aria-labelledby prop is required for accessibility.
(anonymous) @ 3670.vendors.chunk.js:1
Show 1 more frame
Show less
285.vendors.chunk.js:1 <Item> with non-plain text contents is unsupported by type to select for accessibility. Please add a `textValue` prop.
i.getCollectionNode @ 85.vendors.chunk.js:1
Show 1 more frame
Show less
3670.vendors.chunk.js:1 An aria-label or aria-labelledby prop is required for accessibility.
(anonymous) @ 3670.vendors.chunk.js:1
Show 1 more frame
Show less
85.vendors.chunk.js:1 <Item> with non-plain text contents is unsupported by type to select for accessibility. Please add a `textValue` prop.
i.getCollectionNode @ 85.vendors.chunk.js:1
Show 1 more frame
Show less
33670.vendors.chunk.js:1 An aria-label or aria-labelledby prop is required for accessibility.

**Comment by joekaufmanexpensify** [comment]
@aldo-expensify could you please confirm whether this should actually be a deploy blocker?

**Comment by roryabraham** [comment]
I do kind of think that this should be a deploy blocker, seems like a legit regression that it would be better not to ship. It has a negative impact on UX if you can't click on something and it's unclear why.

IMO the UX should be:

- Allow the user to select all, no matter what
- If they select a workspace admin, disable the `Remove` button and add a tooltip over it that says "You can't remove admins from this workspace"

**Comment by UsamaPLUTON** [comment]
This issue has the potential to significantly compromise user experience, particularly when users are unable to interact with elements without a clear understanding of the underlying reasons.

In my opinion, Universal Selectability Enables the user to select all items regardless of the scenario. If a workspace admin is selected, the "Remove" button should be deactivated. Moreover, placing a tooltip over the disabled button with the message "Administrators cannot be removed from this workspace" would provide users with informative context.

**Comment by UsamaPLUTON** [comment]
This issue has the potential to significantly compromise user experience,
particularly when users are unable to interact with elements without a
clear understanding of the underlying reasons.

In my opinion, Universal Selectability Enables the user to select all items
regardless of the scenario. If a workspace admin is selected, the "Remove"
button should be deactivated. Moreover, placing a tooltip over the disabled
button with the message "Administrators cannot be removed from this
workspace" would provide users with informative context.

**Comment by aldo-expensify** [comment]
> IMO the UX should be:
> - Allow the user to select all, no matter what
> - If they select a workspace admin, disable the Remove button and add a tooltip over it that says "You can't remove admins from this workspace"

Do tooltip work for mobile? Do they appear on tap?

**Comment by aldo-expensify** [comment]
As far as I know, the usual approach for form is that we don't disable the button and we allow the user to click it, then we display an error on click.

Why are we aiming for a different approach? maybe we should do that?

**Comment by aldo-expensify** [comment]
@c3024 can you implement [your proposal](https://github.com/Expensify/App/issues/25859#issuecomment-1691864230)?

**Comment by aldo-expensify** [comment]
Thanks!

**Comment by aldo-expensify** [comment]
Thanks, merged! Requesting Cherry pick to staging.

**Comment by aldo-expensify** [comment]
@joekaufmanexpensify @c3024 proposal was accepted to fix the deploy blocker and the PR was merged

**Comment by joekaufmanexpensify** [comment]
Sounds good! We'll issue payment to them and the bug reporter 7 days after the PR is deployed to production.

**Comment by 101ammarAh** [comment]
Contributor details
Your Expensify account email: ammar.ahmad20@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011c54bb419fb61aec

I will use React Native's state to track whether the "Select All" checkbox should be disabled based on non-removable members' presence. So if admins are the only ones in the list, select all will be disabled.

**Comment by mountiny** [comment]
Confirmed this is fixed in staging

**Comment by joekaufmanexpensify** [comment]
Not out on prod yet. Payment will be issue 7 days after fix is on production.

**Comment by joekaufmanexpensify** [comment]
@aldo-expensify / @c3024 mind completing the BZ checklist here so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment]
@c3024 thanks!

**Comment by joekaufmanexpensify** [comment]
@aldo-expensify could you please complete your portion too when you have a sec?

**Comment by joekaufmanexpensify** [comment]
Once the checklist is complete, we need to issue the following payments here: 

- @c3024 - $1,500 for PR + speed bonus. 
- @gadhiyamanan - $250 for reporting.

**Comment by joekaufmanexpensify** [comment]
@c3024 offer sent for $1,000! ($500 will be issued as bonus).

**Comment by aldo-expensify** [comment]
Completed bugzero checklist

**Comment by joekaufmanexpensify** [comment]
@c3024 $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@gadhiyamanan $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!
