### ISSUE TITLE
[HOLD for payment 2023-09-06] Adhoc builds do not always apply new patch

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25863]
### Problem

As @adamgrzybowski found when testing this PR https://github.com/Expensify/App/pull/22437, when there is no change to the `package-lock.json` the adhoc build process uses cachec `node_modules` which means the new patch is not applied.

This causes the build to be incorrect, missing the fix we want to test.

### Solution

Update the build script of the adhoc builds to check for changes in patches as well and in such case, make sure to apply them

**Comment by adamgrzybowski** [comment]
commenting

**Comment by kevinksullivan** [comment]
Looks like I don't need to be on here, but let me know if that changes!

**Comment by mountiny** [comment]
This can be closed now I believe, handled with agency
