### ISSUE TITLE
[HOLD for payment 2023-09-21] Attachment - Keyboard does not reopen when tap Back button on Gallery page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23994
## Action Performed:
1. Open any chat
2. Focus the composer to open the keyboard
3. Tap plus icon in the composer, and then click Add Attachment
4. Select "Files" from Choose an action modal
5. Tap the backdrop to exit

## Expected Result:
The keyboard should reopen

## Actual Result:
Keyboard does not reopen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0b9b01d3-08bb-4395-8539-d0e4cb7a8b46

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internl Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Might be related to - https://github.com/Expensify/App/issues/13922

**Comment by Christinadobrzyn** [comment]
Might be fixed with https://github.com/Expensify/App/issues/13922#issuecomment-1693002644 so gonna Hold this one and do more testing after https://github.com/Expensify/App/issues/13922#issuecomment-1693002644 is deployed.

**Comment by Christinadobrzyn** [comment]
On hold for - https://github.com/Expensify/App/issues/13922#issuecomment-1693002644

**Comment by situchan** [comment]
@Christinadobrzyn can you please add Engineering label? No engineer assigned as reviewer in https://github.com/Expensify/App/pull/26221

**Comment by Christinadobrzyn** [comment]
Hey @aldo-expensify can you review https://github.com/Expensify/App/pull/26221

**Comment by aldo-expensify** [comment]
Is this issue not in HOLD for 13922 anymore?

**Comment by situchan** [comment]
> Is this issue not in HOLD for 13922 anymore?

correct. [PR](https://github.com/Expensify/App/pull/23994) which fixes #13922 was deployed to production on Aug 29

**Comment by Christinadobrzyn** [comment]
just prepping this for payment...

- Are we paying this or was it a regression?
- @situchan you were the C+ or contributor? 
- @aldo-expensify do you think we need a regression test on this?

**Comment by situchan** [comment]
I'd say this is follow-up of https://github.com/Expensify/App/issues/13922 rather than regression. Context: https://github.com/Expensify/App/issues/13922#issuecomment-1693002644
No payment is needed here. The work on this GH should be covered enough in https://github.com/Expensify/App/issues/13922 's payment.

**Comment by aldo-expensify** [comment]
Agree with @situchan 's assessment.

**Comment by Christinadobrzyn** [comment]
Sounds good! thanks @situchan and @aldo-expensify! I will close this without payment - payment will be in https://github.com/Expensify/App/issues/13922
