### ISSUE TITLE
Android - IOU Distance - Map does not zoom in to the selected location on Start point

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25161
## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Tap + > Request money > Distance
4. On Start point, type 88 Kearny Street and select the first result

## Expected Result:
The map zooms in to the selected location

## Actual Result:
The map does not zoom in to the selected location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7f3409f5-44cc-4ead-abd5-3d03021fb39a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Distance requests are behind a beta, so this does not need to be a blocker. I did not check if it's a dupe

**Comment by arosiclair** [comment]
> This is a duplicate of #25732. I think this was not a deploy blocker. @hayata-suenaga to confirm!

Thanks closing this out as a dupe
