### ISSUE TITLE
[$1000] Android - Notifications - Inconsistent appearing of avatar on notification when app is backgrounded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As user A, open Newdot on any platform (that's not the android device you'll be testing with for User b)
2. As user B, sign into NewDot app on Android then background app 
3. Send a message from A to B
4. Notice the push notification content
5. Repeat steps 3 and 4 until avatar doesn't show. 

## Expected Result:
User A's avatar should show on the push notification

## Actual Result:
Inconsistent appearing of avatar image on push notification when app is backgrounded.
User B's avatar sometimes appears sometimes no

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0
 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/661a85b8-0fef-4df9-a0a7-d4eec3f8a661

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01961ba65022c042e0</li>
        <li>Upwork Job ID: 1696678025675087872</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Updated reproduction steps in the OP to be a bit more clear.  Was able to reproduce via BrowserStack
<img width="455" alt="image" src="https://github.com/Expensify/App/assets/22508304/6684f427-fd48-4427-8009-1972df48f0ed">

**Comment by Elyas-Demeke** [comment]
I would like to work on this issue

**Comment by shubham1206agra** [comment]
Is this BE issue?
If not, can you help me point out where in the code the payload is created?

**Comment by mallenexpensify** [comment]
Thanks @ntdiary , do you think there's anything we can/should do about this?  

@maddylewis  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by maddylewis** [comment]
removing my assignment since it sounds like this is non-urgent/matt is back on Monday

**Comment by mallenexpensify** [comment]
Thanks @ntdiary and @maddylewis 
Thinking about this more if the behaviour is intended, then this isn't a bug but a new feature, right?
And... if so... it doesn't sound like something we can or would/could easily 'fix', right?  

I'm going to bump to monthly

**Comment by mallenexpensify** [comment]
Gonna close based on comments above, since the flow is intended, I don't foresee us doing a bunch of work to change/update it.
