### ISSUE TITLE
 Unable to delete a workspace if owner leaves a workspace chat with one of the members

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account on ND
2. Click on FAB > New workspace
3. Invite a member into the workspace
4. Go to the workspace chat room with the invited member
5. Click on header > Click on leave room
## Expected Result:
Owner should be able to delete the workspace
## Actual Result:
Owner is unable to delete the workspace if owner left a workspace chat
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/baa57bf9-7913-4841-badb-bf5dc5834991

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugata
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692877617578849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Closing this as the issue does not make any actual sense. Please feel free to create a new issue that makes sense and appropriately label it if it should block the deploy or not.
