### ISSUE TITLE
Workspace - Statement in Reimbursement Swaps Positions When Language is Changed to Spanish

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences
2. Change the language to Spanish
3. Go to Settings > Workspace > Reimbursement
4. Observe that the statement swaps positions

## Expected Result:
The statement should remain in the same position when the language is changed to Spanish.

## Actual Result:
The statement swaps positions when the language is changed to Spanish.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/afc52458-04a4-4de8-95b3-0a795201694b

https://github.com/Expensify/App/assets/115492554/3936a51c-77ec-4beb-9370-0633f10bf86f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691903737659389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tewodrosGirmaA** [comment]
@GItGudRatio this happen when you Change the language otherwise it works well

**Comment by dylanexpensify** [comment]
Reviewing monday!

**Comment by dylanexpensify** [comment]
updating today!

**Comment by dylanexpensify** [comment]
Huh I can't actually see what the bug is - @tewodrosGirmaA mind explaining a bit more to me?

**Comment by tewodrosGirmaA** [comment]
@dylanexpensify When changing the language to Spanish and opening the reimbursement section, carefully examine the word placement. The words should remain in their original position and not be swapped. Ensure that they remain stable. Thanks

**Comment by dylanexpensify** [comment]
> The words should remain in their original position and not be swapped
How are they being swapped? Thank you! 🙇‍♂️ (I mean this because I'm not seeing it not because I'm being sassy, I promise haha!)

**Comment by dylanexpensify** [comment]
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment]
I cannot for the life of me see it 😭 @tewodrosGirmaA is this still occurring?

**Comment by dylanexpensify** [comment]
Closing, as this doesn't seem like a bug
