### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] [HOLD for payment 2023-09-04] First member remains highlighted on members page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces
2. click on New workspace button
3. go to members page
## Expected Result: 
first member should not be highlighted
## Actual Result:
 first member remains highlighted
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/21975e67-f96c-4991-b16a-f5fbb729be47

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692775387117969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e5a7ab996cffd57</li>
        <li>Upwork Job ID: 1696617256853905408</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment]
this appears to be a regression from https://github.com/Expensify/App/pull/22622/files

https://github.com/Expensify/App/blob/b38181a2d567cc3cbb5b426f0585db4286747fa6/src/components/SelectionList/BaseSelectionList.js#L136-L146

we set an initially focused option index of 0, so the first focused option will always be focused by default.

**Comment by jasperhuangg** [comment]
Don't think we need to block deploy on this either, pretty minor display bug

**Comment by gadhiyamanan** [comment]
@jasperhuangg reporting bonus is pending

**Comment by jasperhuangg** [comment]
@gadhiyamanan Ah, my bad! I'll make sure to get you paid out before closing this

**Comment by michaelhaxhiu** [comment]
working on the bug bonus

**Comment by michaelhaxhiu** [comment]
damn i want it to make me an upwork job :(

**Comment by michaelhaxhiu** [comment]
you should know by now that patience isn't my strong suit 😏 

Upwork job link manually created, here - https://www.upwork.com/jobs/~0136a642e3fe1ebdaf

@mananjadhav drop a comment here after you accept please.

**Comment by gadhiyamanan** [comment]
@michaelhaxhiu offer accepted, thanks!
