### ISSUE TITLE
[HOLD for payment 2023-09-06] [HOLD for payment 2023-09-04] Web - Workspaces - Name highlights on select member on invite page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25896]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces >members
2. click on invite button
3. select any member

## Expected Result:
name should be highlighted even if member is not selected

## Actual Result:
name highlights on select member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.57-2

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ff54a790-6075-4984-962d-56301c5ac8ba

https://github.com/Expensify/App/assets/115492554/828d045d-4a9f-414a-8a54-e909cb054540

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692777018489079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by b4s36t4** [comment]
<img width="374" alt="Screenshot 2023-08-25 at 2 42 16 AM" src="https://github.com/Expensify/App/assets/59088937/ff5db5fc-1481-42eb-b42c-bca0fe84ecac">

I think this behaviour is intended, happening same on prod too.

**Comment by NikkiWines** [comment]
Behavior seems to be the same on staging and prod, just with a slightly different UI - not a blocker. Not even sure if this is really a bug. cc: @maddylewis to confirm 

https://github.com/Expensify/App/assets/16747822/d5312a16-0a6b-41e5-9c13-12ab587af5ef

**Comment by aldo-expensify** [comment]
@NikkiWines I think this is referring to the the `email` (login) not being bold anymore for elements that are unselected

<img width="349" alt="image" src="https://github.com/Expensify/App/assets/87341702/79a60bdf-5fa5-42d9-811e-3a0df25e0cfd">

**Comment by NikkiWines** [comment]
Oh hmm, yeah I definitely took "highlight" to mean that the whole row color was changed 🤔 

@shawnborton can you confirm if the new UI styles are expected here?

**Comment by maddylewis** [comment]
OIC - the top line is no longer bolded. ok ya, let's see what Shawny says.

**Comment by aldo-expensify** [comment]
It is likely that this regression was caused by this big PR: https://github.com/Expensify/App/pull/22622 which caused a few other regressions. It changed stuff in the workspace member page.

**Comment by maddylewis** [comment]
thanks for clarifying @gadhiyamanan - i will process the reporting bonus to you for this particular issue.

**Comment by maddylewis** [comment]
offer sent

**Comment by gadhiyamanan** [comment]
@maddylewis offer accepted, thanks!

**Comment by maddylewis** [comment]
paid!
