### ISSUE TITLE
[$1000] Web - Chat - Border is not disappeared even clicking on message multiple times

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and click on F11 to get any message covered with border.
2. Click on that message multiple times

## Expected Result:
Border should be disappeared after clicking on message multiple times

## Actual Result:
Border is not disappeared even clicking on message multiple times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2d42adf8-7f00-4761-8a07-c7b0111f1b6a

https://github.com/Expensify/App/assets/115492554/74f6ba4c-cf4f-4878-9ab6-9ebc4ad7ddc0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691907069089069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eccb4420f0ed49d4</li>
        <li>Upwork Job ID: 1695089450939985920</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Chatting with reporter in slack - I'm having trouble reproducing with the F11 key on my mac.

**Comment by garrettmknight** [comment]
Thanks @Krishna2323 - I got it to work.

**Comment by Talha345** [comment]
IMHO, we should not change this behaviour as this is standard behaviour.

**Comment by Talha345** [comment]
@Krishna2323 Makes sense. In that case, I think removing the tabindex from the chat message divs can also be a viable option.

**Comment by burczu** [comment]
In general, if we want to keep this behaviour, [the proposal](https://github.com/Expensify/App/issues/25904#issuecomment-1693437479) from @Krishna2323 fixes the issue and we could proceed with it.

However, let me add my insight to the discussion about maintaining this behaviour: I think ability to focus messages in the chat with keyboard make sense but should be extended with handling the Enter/Space button - pressing Enter should show the context menu (and then it should be possible to move over its options using Tab) as it does when we hover over the message using mouse - this will add the possibility to use this context menu by disabled people.

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment]
@Krishna2323 This sounds like feature request - I think you could start a discussion about it on slack (#expensify-opens-source channel), what do you think?

**Comment by garrettmknight** [comment]
Interesting - so the solution to this isn't allowing the click to remove focus since that's the standard browser handling of focusable elements. I'd agree that changing the standard here is more of a new feature in that case. @Krishna2323 if you want to propose a new feature around accessibility, feel free to reference this issue, but I'm going to close in the meantime since it's the standard behavior.
