### ISSUE TITLE
[$2000] Distance - Missing "Finish" button and "Add Stop" button does not response

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to 'Request Money' > 'Distance'
3. Tap "Start"" button and add address
4. Tap "Add Stop" button

## Expected Result:
When user navigate to Distance tap there should be "Start" and "Finish" button.
When tap on "Add Stop" button the new routes waypoint editor should be open 

## Actual Result:
"Finish" button is missing and "Add Stop" button does not response when tap on it
This issue is reproduced on iPhone 6S: 750 x 1334

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/77accb33-868c-4660-8ea3-601768ae0e63

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c51e788145a4b3</li>
        <li>Upwork Job ID: 1695739833166036992</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Heh - why was @kevinksullivan assigned here?

**Comment by laurenreidexpensify** [comment]
increased to $2000

**Comment by hayata-suenaga** [comment]
yes that's correct let me grab the issue that fixed this

but yes we can close this out

**Comment by hayata-suenaga** [comment]
this issue. PR was merged and the issue should be fixed now
