### ISSUE TITLE
[HOLD for payment 2023-09-08] Update Transaction type definition

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25909]
# Problem
We added receipt to the transaction Onyx key and we should update its type definition accordingly.

# Why is this important
Keeps data types correct

# Solution
Update the data type

**Comment by luacmartins** [comment]
@sobitneupane you reviewed the PR, do I need to add Bug label to process payment or is the process different for paying through newdot?

**Comment by sobitneupane** [comment]
For payment in newDot, payment summary will be required. So, Bug label might be required for that.

**Comment by luacmartins** [comment]
@NicMendonca could you please assist with paying @sobitneupane for the PR review?

**Comment by NicMendonca** [comment]
@sobitneupane can you please request payment via Expensify?

**Comment by NicMendonca** [comment]
closing ^^

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/25909#issuecomment-1717872568

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @sobitneupane based on BZ summary.
