### ISSUE TITLE
[$500] Split bill - Participant display name changes to email when split bill is created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go offline
3. Create split bill with a few users with display name
4. Go to + > Split bill > Enter amount > Next

## Expected Result:
The display name for users involved in the split bill in Step 3 will remain

## Actual Result:
The display name for users involved in the split bill in Step 3 changes to their contact method (email)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/effaea9c-1a10-49cb-9153-2814209a2e6d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a732bd3ce537a266</li>
        <li>Upwork Job ID: 1699233562435706880</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by anmurali** [comment]
Will get to this tomorrow.

**Comment by anmurali** [comment]
What's interesting is this seems to only happen to _some accounts_

See the video. Test User - display name shows. But for the other user (Kevin), the display name is replaced with email. 

https://github.com/Expensify/App/assets/14225673/9cedfe24-bf5e-44b6-b77c-70f7736ebbe5

**Comment by lanitochka17** [comment]
@anmurali @bernhardoj The issue is repeated with avatars as well.
Do we need to open another bug or is this related to this bug?
Thanks


https://github.com/Expensify/App/assets/78819774/face49d2-cc0e-446f-a3a9-79d1b3c0bde6

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by anmurali** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1695659246996439

**Comment by anmurali** [comment]
Cannot reproduce
