### ISSUE TITLE
 Chat - Photo sent from another user are enlarged

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open the chat as user A with user B
3. From the secondary device (user B) send a photo (not a screenshot) to user A
4. Send a screenshot to user A

## Expected Result:
Photo and screenshot have the same previews in the chat

## Actual Result:
Photo previews are enlarged

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4826a75d-0fed-46fb-aafe-d3c698970387

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
@lanitochka17 I'm not able to reproduce this, are you still?

**Comment by lanitochka17** [comment]
@slafortune  Issue is not reproducible with build 1.3.59-4

https://github.com/Expensify/App/assets/78819774/c1e52ae0-2128-4c81-a8b5-8a862dbabbe1
