### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] IOU - Not all Split bills are registered when leaving offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify application
2. Disable the internet connection in the device
3. From the global create menu +, select Split bill
4. Select any 3 participants and complete the IOU
5. Repeat steps 3-4 2 times with the same participants
6. Enable the Internet connection on your device

#### This bug also occurs in this workflow:
1. Login as User A and User B in front of you at the same time.
2. As User A requests Money from User B ( make sure it works by avoiding the bugs around the IOU feature Now )
3. As User A go offline ( go to settings > preferences > turn on the offline mode ) - don't go offline as User B.
4. As User A Send another Money request.
5. As User B, Pay the first money request elsewhere.
6. Back to User A and Go online again.
7. Notice the Money request message for both users.

## Expected Result:
All Split bills created in offline mode must be registered when you enable online mode

## Actual Result:
When creating several Split bills for the same participants in offline mode, only the first Split bill is registered when going online, all others give an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/837a0945-96cf-4b2f-a19f-df119789e5d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team /  @eusalazar

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692057275536929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010990d7cb2b15ce9f</li>
        <li>Upwork Job ID: 1696572786341081088</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
agree we need to level this up for offline<>online!

**Comment by AJV009** [comment]
could this be related as well? here too the offline<>online is a lil lost https://github.com/Expensify/App/issues/26099

**Comment by zanyrenney** [comment]
Good shout, I have asked the other BZ team member about their view on combining these.

**Comment by zanyrenney** [comment]
Maddy OOO so just waiting for her to be back to check on combining these.

**Comment by maddylewis** [comment]
updated OP with additional workflow!

**Comment by maddylewis** [comment]
combined this bug with this one https://github.com/Expensify/App/issues/25925 - closing!

**Comment by zanyrenney** [comment]
Thanks @aimane-chnaif and @maddylewis

**Comment by zanyrenney** [comment]
@aimane-chnaif please explore the proposal.

**Comment by zanyrenney** [comment]
@aimane-chnaif the proposal above looks good, can you check please so we can move ahead with this? We are close to breaking WAQ otherwise.

**Comment by zanyrenney** [comment]
That's fine to tackle separately, I reopened the other GH issue and explained that. @aimane-chnaif please can you re-review the proposal for this now? Thanks!

**Comment by zanyrenney** [comment]
@aimane-chnaif should we increase the bounty again here? How complex would you say this is?

**Comment by zanyrenney** [comment]
@aimane-chnaif seeing as @tsa321 proposal solved this, but not the related issue, i think this proposal would now be sufficient seeing as we are not combining the issues. 

please can you review their proposal again and assign them if the proposal seems sufficient.

**Comment by zanyrenney** [comment]
Bump @aimane-chnaif please can you reply to me on the above?

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1696235633005159 asked in slack for more visibility.

**Comment by zanyrenney** [comment]
Still not seeing the feedback, bumping again in slack.

**Comment by zanyrenney** [comment]
@tylerkaraszewski please can you check the timeframes for this based on this comment? https://github.com/Expensify/App/issues/25925#issuecomment-1756418223

I want to proceed with the payment but I would like a second opinion on any urgency bonus as it is not visible in this issue.

**Comment by zanyrenney** [comment]
unfortunately the original job post has closed. https://www.upwork.com/jobs/~01fc8ba64ab4045ff1

please reapply to this job for payout @aimane-chnaif @tsa321 

Thanks!

**Comment by zanyrenney** [comment]
@tsa321 especially you as i do not have any upwork details for you.

**Comment by zanyrenney** [comment]
great, just waiting on @aimane-chnaif now.

**Comment by zanyrenney** [comment]
Okay, let's hang tight for now then and see if this self-resolves. I am seeing currently on the status page they are having issues: https://status.upwork.com/

**Comment by eusalazar** [comment]
Excuse me, my payment will also be made today for   RP.?

**Comment by zanyrenney** [comment]
We need your upwork profile, not just an email @eusalazar

**Comment by eusalazar** [comment]
https://www.upwork.com/freelancers/~01b78d40a285cc88ab
eugeniasalazar745@gmail.com

**Comment by zanyrenney** [comment]
Please apply to the job @eusalazar - I am not finding you on Upwork.

**Comment by zanyrenney** [comment]
**payment summary**

C+ - @aimane-chnaif requires payment - PAID $1500 (INC. $500 urgency)
C - @tsa321 requires payment - PAID $1500 (INC. $500 urgency)
Reporter @eusalazar - **needs payment but needs to apply to job on upwork**

**Comment by eusalazar** [comment]
Hello, I already applied! thank you

**Comment by zanyrenney** [comment]
brilliant, thank you @eusalazar - please accept my offer so we can move forward!

**Comment by zanyrenney** [comment]
paid @eusalazar $250 for bug report as it was before price change. All payments complete - closing!
