### ISSUE TITLE
Workspaces - 'Find a member' text doesn't move back as a placeholder

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25938]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Open any workspace
3. Go to Members
4. Click on the 'Find a member' text input
5. Type anything
6. Click on the Invite button
7. Go back

## Expected Result:
'Find a member' text moves back as a placeholder

## Actual Result:
'Find a member' text doesn't move back as a placeholder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/61c791e8-893f-43ce-9a8e-e3df34112b6a

https://github.com/Expensify/App/assets/115492554/94279864-da29-43cc-a281-87e711867b78

**Expensify/Expensify Issue URL:**

**Issue reported by:** @adeel0202

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691940624523829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by b4s36t4** [comment]
I think we need Expected behaviour here, input needs to get focus or doesn't have to??

**Comment by JmillsExpensify** [comment]
Closing based on comments above.
