### ISSUE TITLE
[$500] [HOLD for payment 2023-09-07] Update styles for money request header user cannot edit

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#25931]
### Problem

When user cannot edit the money request, we are using the `disabled` prop which changes the cursor and greys out the fields

![image](https://github.com/Expensify/App/assets/36083550/2564fdc3-ab09-4591-8256-3a4a7c708848)

### Solution

Update the styles so in this case, the header looks exactly the same as for the user who can edit except:
- no chevron - already working
- when user hovers over the rows, they are not highlighted
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011073110a17edacf6</li>
        <li>Upwork Job ID: 1701248547715727360</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26611863</li>
</ul></li>
    </ul>
</details>

**Comment by koko57** [comment]
Hi! I'm Agata from Callstack and I'm ready to help! 🙌🏻

**Comment by mountiny** [comment]
@koko57 This should be a simple change so no need for a proposal from your side

**Comment by situchan** [comment]
> When user cannot edit the money request

@mountiny We should not use `disabled` prop in all cases?
- payee side: paid already
- payer side

**Comment by mountiny** [comment]
correct

**Comment by CortneyOfstad** [comment]
@mountiny Just following up for the payment here — was their a PR and if so, was it merged within 3 days of @koko57 being assigned?

Also for Callstack, is payment required? Or is that handled somewhere else? TIA!

**Comment by mountiny** [comment]
I believe the only payment here will be $1000 to @situchan for internal review

**Comment by CortneyOfstad** [comment]
Thanks @mountiny! Getting that tackled now!

**Comment by CortneyOfstad** [comment]
So it looks like a "job" was never created in Upwork, so going to apply the `external` label to get the job created, and I'll extend an offer/contract to @situchan ASAP 👍

**Comment by CortneyOfstad** [comment]
@burczu sorry for the false alarm! Issue is already assigned to @situchan so getting this cleared up!

**Comment by CortneyOfstad** [comment]
@situchan the payment will be $1000, but Upwork creates the issue under $500. No worries, you'll be paid under the old format (based on when this issue was created) 👍 

Please let me know once you accept, and I can get that paid right away. TIA!

**Comment by CortneyOfstad** [comment]
@situchan — payment has been completed in Upwork! You should be all set!

**Comment by CortneyOfstad** [comment]
@mountiny Any updates on [the checklist](https://github.com/Expensify/App/issues/25931#issuecomment-1701871857) above?

**Comment by mountiny** [comment]
@CortneyOfstad This was a new feature being built and design decision so no need to highlight some bugs as in the checklist here I believe

**Comment by CortneyOfstad** [comment]
Sounds good! Closing!
