### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] Re-introduce `Send Money` in anticipation of launch later this year

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#25960]
We recently removed the `Send Money` option from NewDot given that P2P wasn't slatted to become a near-term priority in the short-term. However, it's more important now that our core roadmap strategy has also changed. 

As a result, we need to:

 - Add `Send Money` back to Global Create
 - Add `Send Money` back to 1:1 DMs
 - Continue not showing `Send Money` in other group contexts, such as `policyExpenseChat` or DMs with >2 members. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014191f72362bd850e</li>
        <li>Upwork Job ID: 1699608593376403456</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I think we're going to keep this internal for now, but thanks! Adding the label for clarity.

**Comment by JmillsExpensify** [comment]
@coleaeason Do you want to take this on as part of the external commit?

**Comment by JmillsExpensify** [comment]
If so, feel free to take it over.

**Comment by techievivek** [comment]
@JmillsExpensify QQ: Do we need to bring back the docs for `send money` feature that were removed temporarily here https://github.com/Expensify/App/pull/22226?

**Comment by techievivek** [comment]
This is ready for review.

**Comment by techievivek** [comment]
Adding @eVoloshchak to the issue so we can pay them for the reviews.

**Comment by eVoloshchak** [comment]
Requested the $500 payment via NewDot

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @eVoloshchak for PR review.

**Comment by JmillsExpensify** [comment]
$500 payment approved based on summary above.
