### ISSUE TITLE
Workspace - There is no separating line for members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace settings with some members
2. Go to Members

## Expected Result:
A line separating members

## Actual Result:
 There is no line to separate members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.57-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/78819774/12dae062-f927-4fd1-94f2-3293918f855f)

![image (2)](https://github.com/Expensify/App/assets/78819774/f437e8d9-fe83-40d6-81c6-806be4e55039)

![image (3)](https://github.com/Expensify/App/assets/78819774/56424356-fd30-4b77-a45d-9cdf5e7838d6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692932540845369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is a new design, not a blocker, @cristipaval can confirm if its 100% intentional cc @thiagobrez

**Comment by thiagobrez** [comment]
Yeah, I'm on mobile so can't find the thread right now, but @shawnborton  can confirm

**Comment by cristipaval** [comment]
Couldn't find in [the issue](https://github.com/Expensify/App/issues/20353) nor in [the PR](https://github.com/Expensify/App/pull/22622) any confirmation from @shawnborton that we should have or not have the line separator. cc @Expensify/design as we now have more than 1 designer ❤️

**Comment by shawnborton** [comment]
Yup, that's right - let's get rid of the horizontal separator lines. I think it looks much cleaner without them, matches other list selections across the app, and lets the list be a bit more compact.

**Comment by cristipaval** [comment]
ah, it was in the main tracker issue. Great! I'll close this issue then. Thanks all!
