### ISSUE TITLE
Chat - Emoji picker and send button briefly appear in composer text area

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Create a draft in any chat
3. Navigate to other chat
4. Refresh the page
5. Return to the draft in Step 2

## Expected Result:
Emoji picker and send button stay where they belong, which is on the right of the composer text area

## Actual Result:
Emoji picker and send button briefly appear in composer text area and then move back to the position

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-4 PR:22437

**Reproducible in staging?:** No

**Reproducible in production?:** No
 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aa381c69-0900-45d6-92aa-2f8e8a000abf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This was fixed after the composer refactor
