### ISSUE TITLE
[HOLD for payment 2023-09-07] [W4 Scan Receipts] LOW: Report preview shows more than 3 thumbnails

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#25970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from another user using the `Scan` option
2. Repeat the process 5 times
3. Notice that the report preview shows more than 3 thumbnails

## Expected Result:
Report preview should show a maximum of 3 thumbnails

## Actual Result:
Report preview shows more than 3 thumbnails

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/22219519/e6182828-a438-481d-8111-83e5f313bd74

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d0855b65bc06680</li>
        <li>Upwork Job ID: 1695151138460545024</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
@luacmartins - how much is due here? Is this a $250 payment?

**Comment by luacmartins** [comment]
@sophiepintoraetz this is a payment for PR review - so I believe it's still $1000 given the PR was reviewed before Aug 30

**Comment by sophiepintoraetz** [comment]
Offer sent @ntdiary! I'll release payment on 07 Sep. One thing that would be helpful is if you could include your first name in your GH profile? Helps me to know who you are in Upwork ([ntdiary](https://github.com/ntdiary) doesn't return anything.)

**Comment by sophiepintoraetz** [comment]
@ntdiary - mind filling out the [regression steps](https://github.com/Expensify/App/issues/25970#issuecomment-1701873132) then I can release payment today? :D
