### ISSUE TITLE
Workspaces - Can not connect Bank account, system redirecting you to Google store

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Connect BA via Plaid

## Expected Result:
System redirected you to Plaid modal for BA connection

## Actual Result:
System redirecting you to Google Store

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1 PR:24041

**Reproducible in staging?:** No

**Reproducible in production?:** N/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6aa0cb57-bc68-41c1-9575-3e1fff0d8df7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I dont think this can be realted to the PR itself it might be some consequence of it being the Adhoc build

**Comment by mountiny** [comment]
This thread is probably related https://expensify.slack.com/archives/C01GTK53T8Q/p1693230649066309 closing
