### ISSUE TITLE
Assign Task - "Undefined" Assign Task Appears After Closing and Signing In Again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25994]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign, select "Assign Task," and fill in the title, assignee, and share location details. Confirm the task
2. Go to settings > security > Close account. Enter the email and close the account
3. Sign in again using the same email and observe that the "Undefined" Assign Task appears

## Expected Result:
After assigning a task, closing the account, and signing in again, the "Undefined" Assign Task should not appear

## Actual Result:
 After assigning a task, closing the account, and signing in again, the "Undefined" Assign Task appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7df99d50-b98a-48f2-8885-9e7bb4b97efd

https://github.com/Expensify/App/assets/78819774/181d00a8-6513-4cba-981d-a70912746b0a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @TewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692184554384749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
>After assigning a task, closing the account, and signing in again, the "Undefined" Assign Task should not appear

What are you proposing should appear instead? Should we delete the task? I'm not sure we would do that.
