### ISSUE TITLE
Assign Task - The task description is not updated for the other user viewing the task, if the first user clears the existing description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task as User A, enter a title and description, and assign User B
2. Open the created task as User B in a separate browser session
3. As User A, edit the task description, clear the text, and tap Save
4. Observe the task description as User B. No change occurs

## Expected Result:
Whenever there is an update to the task description, the task view should be updated with the new description

## Actual Result:
The view does not update with the new description if the new description is an empty string

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0265de2f-93a6-4e09-945f-8328e4c906bf

https://github.com/Expensify/App/assets/78819774/75e840e4-6259-42f1-8dce-2bf934025ef9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Akinwale Ariwodola

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692251273828169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
I think BE issue as the description field isn't passed in the pusher event for onyx merge when it sets to empty.

<img width="1440" alt="Screenshot 2023-08-27 at 00 07 51" src="https://github.com/Expensify/App/assets/14358475/bbefe7ce-4fec-4058-ad5f-52f1fa213a65">
