### ISSUE TITLE
Profile - Profile URL displays same profile even after adding more content to URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#25993]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Click on report header to open user profile
4. Add '.000' to the profile and observe that app still displays same profile
5. Try adding '.000' in report URL and observe that it provides 'Hmm its not here' page

## Expected Result:
App should display 'Hmm its not here' page if we try to modify URL by adding content in it like it does for report pages

## Actual Result:
App displays same profile even on adding '.000' in the URL (it does the same for any number of zeros)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f30588e3-3337-4d41-a02b-07c17bd44ea4

https://github.com/Expensify/App/assets/93399543/a7118a85-f6de-4fdb-8db3-21c1579237aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692248052849399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhanashree-sawant** [comment]
Still reproducible on latest staging

**Comment by puneetlath** [comment]
I'm able to reproduce it, but I don't really see it as a bug. 100.00 is technically the same number as 100, so I think we're fine here and it's not a bug. And it's not worth adding extra conditions and making the code more complicated for a case that no one is ever going to hit or be confused by.
