### ISSUE TITLE
Android - Glitch occurs when scrolling through threads on the android app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#25992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the android app
2. Scroll through the threads

## Expected Result:
Experience smooth scrolling while navigation.

## Actual Result:
The app experiences glitches when navigating.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 3.57-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/595cf6d9-9fec-459d-b3f9-31560d5bee47

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689453640673329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jo-ui** [comment]
@hungvu193 #20984 is about dissappearing messages when you scroll. [This](#25992) issue is about a glitch when you scroll not about disappearing messages.

**Comment by alexpensify** [comment]
I was assigned while I was OOO, I'll test soon.

**Comment by alexpensify** [comment]
I'm going to need to reopen the discussion and confirm if we should keep this one open.

**Comment by alexpensify** [comment]
Based on the conversation here and in Slack, I'm going to close.
