### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$1000] Bank account - Phone number field is not trimmed for spaces in connect bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25996]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account->connect manually
3. Fill in fields in step 1 and continue
4. Fill in fields in step 2, before legal name, phone number, tax ID add some spaces and continue
5. Go back to step 2 and observe that app trim spaces before value for legal name, tax ID but doesn't trim space for phone number

## Expected Result:
App should trim spaces before phone number value as it does for tax ID or legal name

## Actual Result:
App should trim spaces before phone number value as it does for tax ID or legal name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a9458e04-f657-40cb-a701-1e37730fbfc5

https://github.com/Expensify/App/assets/78819774/d31d1ade-5f60-40af-a389-9ff3ef7897fa

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692249462405549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017eadfab4995c4b33</li>
        <li>Upwork Job ID: 1696513864176926720</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment]
I think issue reporter was mistakenly marked to @dhanashree instead of @dhanashree-sawant, can we correct that if possible? It will help me to recieve emails about it

**Comment by garrettmknight** [comment]
@dhanashree-sawant updated the OP. Checking whether this is an issue for us on the backend or not before opening up.

**Comment by garrettmknight** [comment]
>It looks like we're parsing the phone number into the correct format in the App [here](https://github.com/Expensify/App/blob/fd755ee94ee9aed354e528abc0b62d19a90802c2/src/pages/ReimbursementAccount/CompanyStep.js#L132) and then sending it to the API. So the API is currently receiving and storing phone numbers in the backend without any leading spaces but I think the display of the phone number in the App isn't being updated.

**Comment by garrettmknight** [comment]
Just bumped the thread for clarification.

**Comment by garrettmknight** [comment]
@Ollyws can you check out that udpated proposal?

**Comment by garrettmknight** [comment]
Bumped in slack.

**Comment by garrettmknight** [comment]
@dukenv0307 can you update your solution when you get a chance?

**Comment by garrettmknight** [comment]
@Ollyws before we recruit internally, can you comment on @dukenv0307 alternative solution suggestion and if that's not working for you have a look at the most recent proposal? Thanks!

**Comment by garrettmknight** [comment]
PR is on Staging - will update to the awaiting payment hold when it goes to prod if Melv misses it.

**Comment by garrettmknight** [comment]
**Summary of Payments:**
- Urgency bonus: No
- Reporter: @dhanashree-sawant - $250 
- Contributor: @dukenv0307 - $1000
- Reviewer: @Ollyws - $1000 

New Upwork issue: https://www.upwork.com/en-gb/ab/applicants/1716919006499426304/job-details

New offers out since the other job went stale - I'll pay when y'all accept.

**Comment by garrettmknight** [comment]
All paid up - closing.
