### ISSUE TITLE
[HOLD for payment 2023-09-08] [$1000] Web -  Workspace's badge is not appeared when hovering over it on thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > any workspace chat
2. Hover over any message there and click reply in thread
3. Hover over workspace's avatar on top

## Expected Result:
Workspace's badge should be appeared when hovering over it on thread

## Actual Result:
 Workspace's badge is not appeared when hovering over it on thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (35).webm](https://github.com/Expensify/App/assets/93399543/624842a6-5a5a-40bc-b3a7-7d058cb6af4b)

https://github.com/Expensify/App/assets/93399543/1b849243-ad3c-4499-9e9e-2ea6c46f1a9c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692265708742049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e47ff04399a885bb</li>
        <li>Upwork Job ID: 1696248250861596672</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
I can reproduce this!

**Comment by ArekChr** [comment]
Hey, @Krishna2323, thanks for the proposal. Could you clarify if your fix keeps the hover for user avatars intact? Could you provide more details in your proposal to the section about changes to solve the problem?

**Comment by ArekChr** [comment]
@Krishna2323, thank you for the explanation. Your [proposal](https://github.com/Expensify/App/issues/26002#issuecomment-1694487049) effectively resolves the issue.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ArekChr** [comment]
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don't think we need to add a regression test here.

**Comment by MahmudjonToraqulov** [comment]
@isabelastisser I was left from payments list as my GH was written wrong when the issue is created. So I wanted to tell you that so that I'm not be left when payment is releasing. Thanks.

**Comment by isabelastisser** [comment]
@MahmudjonToraqulov no worries, I will send you the offer and complete the payment when the time comes.

**Comment by MahmudjonToraqulov** [comment]
Thanks  Isabelastisser.

**Comment by isabelastisser** [comment]
Payment summary:

- @MahmudjonToraqulov $250 for reporting the issue. Offer sent in Upwork; please accept it, and I will process the payment.
- @Krishna2323 $1000m for accepted proposal, $500 urgency bonus. Offer sent in Upwork; please accept it, and I will process the payment.
- @ArekChr Callstack, no payment is needed. Please confirm if I'm correct here. Thanks!

**Comment by MahmudjonToraqulov** [comment]
@isabelastisser, Me as well.

**Comment by isabelastisser** [comment]
Payments were processed in Upwork, all set!
