### ISSUE TITLE
 Attachment - Unable to upload a pdf file

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap the "+" button
4. Select Add attachment > Choose adocument
5. Select a pdf file

## Expected Result:
The pdf file preview is displayed, user is able to send it in chat

## Actual Result:
The "Something went wrong" screen is displayed, user is unable to send the attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.4-PR:22437

**Reproducible in staging?:** No

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7a74a39b-0e19-45a0-a164-65c33e2f3598

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@tienifr Can you please look into this?

**Comment by mountiny** [comment]
Not an issue
