### ISSUE TITLE
[HOLD #26030] Chat - 'Mark as unread' tooltip not removed when cursor quickly moves to other options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Click on the "Mark as unread" option
4. While keeping the cursor on "Mark as unread," navigate it to the "Copy to clipboard" option
5. Observe that the "Mark as unread" tooltip overlaps with the "Copy to clipboard" tooltip due to a delay in its removal

## Expected Result:
The "Mark as unread" tooltip should be promptly removed to prevent any overlapping issues with other tooltips

## Actual Result:
There is a noticeable delay in removing the "Mark as unread" tooltip, causing it to overlap with other tooltips like "Copy to clipboard"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/19396e1f-416c-4db4-800b-b8229c76964c

https://github.com/Expensify/App/assets/78819774/19301118-e4dd-4ce9-b722-d91eaf17772a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Hussain

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692304963899229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment]
@Krishna2323 It's not the same and the bug you mention has already been identified I've seen it searching it

**Comment by mallenexpensify** [comment]
It does look like https://github.com/Expensify/App/issues/26030 was reported before this so I'm going to put this issue on hold pending that one, to see if the PR for that fixes this

**Comment by mallenexpensify** [comment]
Still on hold
- https://github.com/Expensify/App/issues/26030

**Comment by mallenexpensify** [comment]
Thanks @Krishna2323 !  
Also... WOW, first time seeing comment linking!
<img width="190" alt="image" src="https://github.com/Expensify/App/assets/22508304/44f77482-5699-4deb-b09f-7aef7d38e09a">

**Comment by mallenexpensify** [comment]
I appreciate you mentioning it was fixed and could be closed, saved me a some time @Krishna2323
