### ISSUE TITLE
IOU - Uneditable and Blank Amount, Description, and Date in IOU After Closing Account and Signing In Again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26013]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money"
2. Enter the desired amount and email address for the money request
3. Go to the IOU and edit the Description
4. Go to Settings > Security > Close account, add email, and close account
5. Sign in again and go to the IOU of your first request before closing the account. Observe that uneditable and blank Amount,
Description, and Date are present in IOU.

## Expected Result:
After closing the account and signing in again, the IOU should not show the blank amount, description, and date.The delete button should Clear the amount, description, and date

## Actual Result:
After closing the account and signing in again, the IOU shows an uneditable and blank Amount, Description, and Date

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/98eb4148-a405-4efa-b2ea-6c63066ec2bb

https://github.com/Expensify/App/assets/78819774/393c8a0e-097e-44ef-8243-e52ec56496fc

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692302591048109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I don't think this is worth solving right now and may in fact be expected behavior based on what we store when you close an account
