### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] App crashes on iOS simulator on open

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26018]
## Action Performed:
Break down in numbered steps

1. Pull the latest main
2. Run `npm run ios`
3. Check that the app crashes with an unhandled promise error

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** the latest `main` branch
**Reproducible in staging?:** Nop
**Reproducible in production?:** Nop
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:**
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1693020712748639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fd401adeff84c58</li>
        <li>Upwork Job ID: 1695589561700159488</li>
        <li>Last Price Increase: 2023-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 26347760</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
@hayata-suenaga Can I take up this issue because I was the original commenter on the offending PR? And I have not raised the issue due to its being handled by SWM member at that time.
https://github.com/Expensify/App/issues/24681#issuecomment-1694334022
https://github.com/Expensify/App/issues/24681#issuecomment-1694334124

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

App crashes on iOS simulator on open

### What is the root cause of that problem?

It is a regression from this PR #25745 due to which the `getPlatform()` method always resolves to `CONST.PLATFORM.WEB` as it always refers to `index.js` file, not `index.ts` file. Due to that, it tries to access `window.localStorage` method which does not exist on iOS.

### What changes do you think we should make in order to solve the problem?

Delete the existing src/libs/getPlatform/index.js file

**Comment by shubham1206agra** [comment]
@allroundexperts @hayata-suenaga PR ready

**Comment by hayata-suenaga** [comment]
don't know why melvin assigned two bug-zero members...

anyway, @slafortune I apologize situation with this issue looks a little confusing

@allroundexperts is the C+ member who took care of this issue (they did pull request review)
@shubham1206agra is the contributor who made the pull request

### More context
- I created the issue because this was urgent problem
- I approved a proposal before C+ approved it because this issue needed to be solved urgently
- I unassigned an auto-assigned C+ and assigned another C+ @allroundexperts who was online at that time and had the context for the issue

**Comment by neil-marcellini** [comment]
Why is this part of distance requests? @JmillsExpensify

**Comment by hayata-suenaga** [comment]
> Why is this part of distance requests? JmillsExpensify

I gonna remove this issue from Distance Request project

**Comment by shubham1206agra** [comment]
@slafortune I didn't receive any bonus. Is there any particular reason for that?

**Comment by slafortune** [comment]
@shubham1206agra I did add the bonus, so it's strange if you don't see that.  Upworks has made some updates where the bonus is shown differently - 

<img width="990" alt="image" src="https://github.com/Expensify/App/assets/11725910/707ab6e2-b3ed-4e37-a33f-d95f442603e8">

Can you check again?

**Comment by slafortune** [comment]
Adding a new BZ member to monitor this, I'm out on sabbatical

**Comment by shubham1206agra** [comment]
<img width="1071" alt="Screenshot 2023-09-09 at 2 00 35 PM" src="https://github.com/Expensify/App/assets/58412969/28d203f1-8cf3-42c8-8ee1-ff241084486f">

It shows the correct balance, but the message shows only milestone completion (earlier, it shows the complete amount).

**Comment by jliexpensify** [comment]
@shubham1206agra as Stevie mentioned, it looks like the correct amount has been paid out to you: I would recommend reaching out to Upworks to gain some clarification as their newly implemented bonus system seems to be confusing.

FWIW, I never use that new bonus system for payouts - I pay the bonus directly on the job.

**Comment by jliexpensify** [comment]
Job removed, [here's the summary for JMills](https://github.com/Expensify/App/issues/26018#issuecomment-1710251947)

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @allroundexperts based on BZ summary.
