### ISSUE TITLE
"Account deleted successfully" message not showing when going online from offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with same account on 2 device
2. Device A: Go offline
3. Device B: Go to settings -> Security -> Close account
4. Device B: Enter default contact email -> Click close account
5. Device A: Go online
## Expected Result:
It should show Account deleted message like it shows when online
## Actual Result:
It does not show account deleted message when going online from offline
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/634c96e6-b92a-4339-beac-3639fcc681c7

https://github.com/Expensify/App/assets/38435837/8c57e799-4c7c-48c7-a887-cc97eefd7ca4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692435819406469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Hm, I suppose this is a bug, though I am double checking in the thread on how we'd expect this to work. 

https://expensify.slack.com/archives/C049HHMV9SM/p1693249191537479?thread_ts=1692435819.406469&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
closing per slack thread
