### ISSUE TITLE
Title and checkbox are not aligned with each other on task

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26033]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and any task
## Expected Result:
 Title and checkbox should be aligned with each other on task
## Actual Result:
Title and checkbox are not aligned with each other on task
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (44).webm](https://github.com/Expensify/App/assets/38435837/eb84f83f-5cb9-4d48-9fda-05b8a5a83737)

![title](https://github.com/Expensify/App/assets/38435837/c05eb36a-c01c-4507-9362-cfc06cbbc898)

![Window - (3) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/16e8acf8-d796-460c-9bd2-2f85088383ab)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692424070303039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
They are aligned they just don't look it because of how the checkbox is curved:

![image](https://github.com/Expensify/App/assets/59587260/0610ddea-2b89-4b77-b708-519a949abddd)
