### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Contact methods - Login with secondary contact details link displays magic code verify UI for sometime

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User will need 1 verified secondary contact
1. Open the app
2. Open settings->profile->contact methods
3. Open secondary contact method (non default contact method)
4. Copy the link
5. Logout and paste the link
6. Login and observe in RHN, it displays magic code verify UI for sometime before displaying 'set to default' UI

## Expected Result:
App should display 'Set to default' UI for verified contact method when visited on login

## Actual Result:
On visiting secondary contact method on login, app displays 'magic code' verify UI for sometime before displaying the correct 'Set to default' UI

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/05913f17-5ce5-4b88-8703-cbda2bf78de4

https://github.com/Expensify/App/assets/78819774/95f92172-d036-4885-9dce-40b478319153

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692461265442239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9dcdff3c37887c1</li>
        <li>Upwork Job ID: 1696837686746603520</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26488575</li>
<li>dhanashree-sawant | Reporter | 26488576</li>
</ul></li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment]
The current issue is raised before that issue, in case it has same RCA and solved there, will it be eligible for reporting bonus?

**Comment by narefyev91** [comment]
@hungvu193 just to clarify - does your proposal will cover both 3 cases?
- Magic Code Input if it is an unvalidated secondary contact
- "Set as default" and "Remove" options if it is a validated secondary contact.
- "Not Found Page" if the email in the url was never added as a secondary contact

**Comment by narefyev91** [comment]
@hungvu193 perfect!
Proposal from @hungvu193 looks good to me https://github.com/Expensify/App/issues/26048#issuecomment-1698944928
🎀 👀 🎀 C+ reviewed

**Comment by michaelhaxhiu** [comment]
Should we close https://github.com/Expensify/App/issues/26050 and consolidate everything into this one job?

**Comment by cristipaval** [comment]
Thanks @narefyev91!
@hungvu193, you're all set! 🚀

**Comment by dhanashree-sawant** [comment]
Hi @cristipaval, the following issue was raised on 28 August but melvin bot has provided me with 50$ offer, can you check once you are available?

**Comment by cristipaval** [comment]
> Hi @cristipaval, the following issue was raised on 28 August but melvin bot has provided me with 50$ offer, can you check once you are available?

@sonialiap, Could you please address this? 🙏

**Comment by michaelhaxhiu** [comment]
IMO the pay would be the prior amount given the timestamps. The new pricing takes effect _going forward_ (rather than retroactively)

**Comment by sonialiap** [comment]
@hungvu193 fix + bonus = $1500 - paid ✔️ 
@narefyev91 does not require payment (Contractor)

@dhanashree-sawant report = $50 - could you check if you've accepted the offer? I'm not seeing an option to pay you

**Comment by dhanashree-sawant** [comment]
Hi @sonialiap, actually the issue was opened in GH on 28 August so can you modify the offer to 250? Or if you say, will accept this offer and rest you can pay by bonus, anything is fine.

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was not coming from any regressions - just missing functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. - N/A

**Comment by sonialiap** [comment]
@dhanashree-sawant offer updated to $250 :)

**Comment by dhanashree-sawant** [comment]
Thanks @sonialiap, I have accepted the offer.

**Comment by sonialiap** [comment]
Paid!
