### ISSUE TITLE
[$500] IOU -  Incorrect Tooltip Position Displayed When Hovering over Email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26041]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money."
2. Enter the desired amount and email address for the money request
3. Navigate to the IOU section by double-clicking on the requested money, write a message, and delete the requested money
4. Go back twice and hover over the email, observing that the tooltip position is displayed at the bottom of the email

## Expected Result:
When hovering over the email, the corresponding email should be displayed in the tooltip located above the email

## Actual Result:
When hovering over our account email in the IOU, it incorrectly displays the tooltip position at the bottom of the email instead of above it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-19T034155.410.webm](https://github.com/Expensify/App/assets/78819774/76ce4bc3-b16d-4670-a8e8-c0acc02b6ff6)

https://github.com/Expensify/App/assets/78819774/12c8613b-c0d6-45c9-ac62-1533a8972410

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692441282411909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01555ca5159a05db42</li>
        <li>Upwork Job ID: 1699605757765820416</li>
        <li>Last Price Increase: 2023-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26612491</li>
<li>tienifr | Contributor | 26612495</li>
<li>tewodrosGirmaA | Reporter | 26612498</li>
</ul></li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
@JmillsExpensify I don't know if this is as much of a tooltip bug as it is just the notification acting a bit strange and the tooltip calculation responding to it, at least the tooltip behaves correctly when it shows up under the email when there is a notification border above as it shouldn't cross that and it behaves incorrectly when at first it shows over the border before leaving the report and coming back to it. can we kindly get some clarification on if the bug is the tooltip going over the new message border or going underneath it? thank you!


https://github.com/Expensify/App/assets/74202751/cc21ca80-29e2-4ac5-9ec6-9dac51583f2a

**Comment by JmillsExpensify** [comment]
Low value bug though triaging in any case for consistency.

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA makes sense but seeing that this is a regression from https://github.com/Expensify/App/pull/20240 it may be better to just revert that PR, the issue that the PR is fixing seems no longer reproducible. I asked [here](https://github.com/Expensify/App/pull/20240#discussion_r1320659336) for confirmation.

**Comment by s77rt** [comment]
After checking I think it's easier and safer to keep the overlapping logic untouched and just ignore the unread indicator as @tienifr suggested especially since it's a decoration only element.

🎀 👀 🎀 C+ reviewed
[Link to proposal ](https://github.com/Expensify/App/issues/26041#issuecomment-1711086232)

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20240
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20240#discussion_r1320659265
- A discussion in #expensify-bugs has been started: Not needed for this case
- Determine if we should create a regression test for this bug: No

**Comment by JmillsExpensify** [comment]
Thanks yes, Melvin failed to update the title. 

Payment summary: 
- Issue reporter: @tewodrosGirmaA $250 (reported before 25 Aug)
- Contributor: @tienifr $1,000 (incl. urgency bonus)
- Contributor+: @s77rt $1,000 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment]
All paid out, no regression tests needed.

**Comment by s77rt** [comment]
@JmillsExpensify The total is $750. I have refunded the $250.
