### ISSUE TITLE
[$250] [Hold on #26048] Contact methods - Delayed display of "Hmm... it's not here" message when changing email from URL

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Profile > Contact methods
2. Click on "New contact method."
3. Enter the email address and click on "Add."
4. Click on the newly added contact method
5. Change the email address from the URL and press enter

## Expected Result:
Upon refreshing the page, the "Hmm... it's not here" message should be displayed instantly without any delay

## Actual Result:
There is a delay in displaying the "Hmm... it's not here" message after changing the email from the URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c0380ba8-b579-436f-927f-0489b81c9c7f

https://github.com/Expensify/App/assets/78819774/2b5d9091-f98e-4f24-ae13-fba1cc233219

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692468860518189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01354b1630f20ce5d8</li>
        <li>Upwork Job ID: 1704532530506207232</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
@michaelhaxhiu sounds like your issue may be to the same thing underlying https://github.com/Expensify/App/issues/26048 and may be resolved once that one is fixed

**Comment by michaelhaxhiu** [comment]
Just catching up and I think you are correct! Should we consolidate these GH into 1, and make it 1 job in that case since it's the same RCA?

**Comment by michaelhaxhiu** [comment]
I just posted in #26048 to decide if we should close this or keep it open.

IMO:
- we can pay the bug bonus here, since it is a diff bug after all (that'll be addressed in one singular fix)
- we should hire @hungvu193 to deploy the fix via https://github.com/Expensify/App/issues/26048

**Comment by michaelhaxhiu** [comment]
Still held on the above ^

**Comment by michaelhaxhiu** [comment]
@ayazhussain79 let's get you hired to pay the bug bonus.

HungVu fixed this problem via https://github.com/Expensify/App/pull/26658 and was paid here https://github.com/Expensify/App/issues/26048#issuecomment-1724965767

**Comment by michaelhaxhiu** [comment]
I invited you to the job @ayazhussain79 - comment here after you accept so I can disburse payment.

**Comment by ayazhussain79** [comment]
@michaelhaxhiu offer accepted, Thank you

**Comment by michaelhaxhiu** [comment]
paid, closing.

**Comment by ayazhussain79** [comment]
@michaelhaxhiu Could you kindly end the contract related to this bug on Upwork?
