### ISSUE TITLE
Request money - On first time after login, changing amount in request money thread does not display amount, description, date

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: before starting, you will need request money thread with many updated value messages eg: Messages like: "amount has been updated to $10.00 (previously $8.00)"
1. Open the app in android chrome
2. If logged in then logout
3. Login again and open request money thread with many updated value messages
4. Scroll above and open amount
5. Update the amount, keep the keyboard open and observe that app does not display Amount, description, date fields in the top
6. Scroll below and scroll up to observe that now it displays the fields

## Expected Result:
App should display request money details fields like Amount, description and date after updating amount

## Actual Result:
App does not display request money details fields like Amount, description and date after updating amount first time after login in android chrome

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/18fc77fd-ca2d-4da3-895d-7b48183cba60

https://github.com/Expensify/App/assets/115492554/9b0eeed9-3af2-4910-bfc7-54558e2c2c18

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692336149297929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
discussed in thread ^^ we'll be closing this
