### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] IOU - Inconsistent margin between green tick and amount on right and left

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open a 'paid' report OR use another user to request money to current user, pay the request and open 'paid' report
3. Inspect the margin between green tick and amount in line of Total, it is 4px and margin between green tick and amount for IOU messages below, it is 8px

## Expected Result:
App should maintain consistent margin between amount and green tick irrespective of amount being on left or right of green tick

## Actual Result:
App maintains 4px margin between amount and green tick for amount on right of green tick and 8px margin for amount on left of green tick

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b0875dcc-9cdb-4e0a-97d9-40286f06063b

https://github.com/Expensify/App/assets/115492554/c33409d5-954c-427d-920e-3f2a429443f9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692205502357469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9f347b0a5be3236</li>
        <li>Upwork Job ID: 1699225416989421568</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26604851</li>
<li>Dhanashree-Sawant | Reporter | 26604854</li>
</ul></li>
    </ul>
</details>

**Comment by alphaboss1104** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Inconsistent margin between green tick and amount on right and left

### What is the root cause of that problem?

We use `styles.defaultCheckmarkWrapper` style that contains `marginLeft: 8px` in `IOUPreview.js`.

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/ReportActionItem/IOUPreview.js#L213-L218

But we use `styles.mh1` style that contains `marginHorizontal: 4px` in `MoneyReportView.js`.

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/ReportActionItem/MoneyReportView.js#L53-L58

This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

We can modify the  `styles.defaultCheckmarkWrapper` style like this:

```js
    defaultCheckmarkWrapper: {
        marginHorizontal: 8,
        alignSelf: 'center',
    },
```

Then remove the `styles.mh1` style from the `MoneyReportView.js`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by anmurali** [comment]
Will reproduce and slap the label on tomorrow

**Comment by anmurali** [comment]
Can reproduce but am not sure this is all that egregiously inconsistent

**Comment by ArekChr** [comment]
[Proposal](https://github.com/Expensify/App/issues/26061#issuecomment-1695300605) from @dukenv0307 Look good to me!

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by dhanashree-sawant** [comment]
Hi @anmurali, the following issue was raised on 28 August but melvin bot has provided me with 50$ offer, can you check once you are available?

**Comment by ArekChr** [comment]
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by Julesssss** [comment]
Ready for payment

**Comment by Julesssss** [comment]
I think this one is awaiting payment for: 
- @dukenv0307 -- PR with urgency bonus
- @dhanashree-sawant -- bug report

**Comment by Julesssss** [comment]
Hi @anmurali, this issue is ready for payment

**Comment by Julesssss** [comment]
> Hi @anmurali, this issue is ready for payment

Bumping for payment

**Comment by anmurali** [comment]
Paid contributor.
@dhanashree-sawant you need to accept [this offer](https://www.upwork.com/nx/wm/offer/26604854) before I can pay

**Comment by dhanashree-sawant** [comment]
Hi @anmurali, the offer is for 50$ but the issue was raised on GH on 28 August, can you modify the offer to 250 for it?

**Comment by anmurali** [comment]
https://www.upwork.com/nx/wm/offer/27131727 @dhanashree-sawant

**Comment by dhanashree-sawant** [comment]
Thanks @anmurali, I have accepted the offer.

**Comment by Julesssss** [comment]
I think this can be closed, please someone comment or re-open if I am mistaken!

**Comment by dhanashree-sawant** [comment]
Hi @anmurali, can you approve the milestone on upwork once you are available?
