### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] mWeb - Sign in page content is scrollable

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out if you are signed in
2. Try to scroll the sign-in page content

## Expected Result:
The page scrolls down to the footer section

## Actual Result:
Sometimes the sing in top content is scrolled instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v.1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1ecf6ab5-0eff-4213-9aad-7e389e67cb53

https://github.com/Expensify/App/assets/115492554/b3a46ef1-dfea-47a1-b77e-67b7f5d46098

https://github.com/Expensify/App/assets/115492554/058263f5-3699-4ae1-80b7-a19dfe3f25c2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @bernhardoj

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692332986130529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f793b0d1923b0a10</li>
        <li>Upwork Job ID: 1696174250894327808</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26382762</li>
<li>bernhardoj | Reporter | 26382764</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
## Proposal from @bernhardoj
### Please re-state the problem that we are trying to solve in this issue.
Sign in page top content is scrollable.
### What is the root cause of that problem?
In a small screen device, we wrap the sign-in page with a ScrollView.
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/pages/signin/SignInPageLayout/index.js#L126-L149
And the sign-in top content also has another ScrollView.
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/pages/signin/SignInPageLayout/SignInPageContent.js#L41-L47
When the sign-in top content does not fit on the screen (because of the google/apple sign-in options), it will start to overflow, thus we can now scroll it, and the scroll conflicts with the whole page scrolling.
### What changes do you think we should make in order to solve the problem?

Add overflowHidden to the sign-in page content if it's a small screen here.
https://github.com/Expensify/App/blob/c435734d8cf360e964e20eea1fb54c541f6fa7ea/src/pages/signin/SignInPageLayout/SignInPageContent.js#L44

**Comment by robertjchen** [comment]
Reviewed, the proposal looks good with @parasharrajat 's comment taken into account: https://github.com/Expensify/App/issues/26063#issuecomment-1696037716

**Comment by lschurr** [comment]
@parasharrajat could you work on the checklist for this one? Do we need a regression test?

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: $250 @bernhardoj (to be paid in Upwork)
- Contributor: $1500 @bernhardoj (to be paid in Upwork)
- Contributor+: $1500 @parasharrajat (to be paid in NewDot)

**Comment by lschurr** [comment]
This is complete. Closing.

**Comment by JmillsExpensify** [comment]
$1,500 payment for @parasharrajat approved based on BZ summary.
