### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Inconsistensy Bug - vertical scroll Bar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings and check every page in it whether it have a vertical scroll bar or not when the screen is minimized

## Expected Result:
Vertical scroll bar should exist in every page inside the settings pages when ever they are needed

## Actual Result:
Vertical scroll bar is not appearing in the "workspace" and "preference" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/47437a9a-cea0-4208-b70e-2aae144c3b00

https://github.com/Expensify/App/assets/115492554/867f1954-1da4-4c08-bab8-dc64d96dd831

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Yokabdk

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692400662129409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01228f2da341ad6648</li>
        <li>Upwork Job ID: 1703887623625846784</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26956698</li>
<li>samh-nl | Contributor | 26956699</li>
<li>Yokabdk | Reporter | 26956701</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
checking on a related issue here: https://github.com/Expensify/App/issues/23609#issuecomment-1696743053

**Comment by MitchExpensify** [comment]
Bumped the Q in the related issue: https://github.com/Expensify/App/issues/23609#issuecomment-1696743053

**Comment by MitchExpensify** [comment]
> @marcochavezf tagging you hear as you worked on the related issue above. Should there should be scrollbars on all pages?

Friendly bump on this question @marcochavezf 🙇

**Comment by MitchExpensify** [comment]
We should have a vertical scroll bar on every tab of the settings pages

**Comment by geniusFulldev** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistensy Bug - vertical scroll Bar

### What is the root cause of that problem?
Workspace and Preference pages are missing ScrollView component.   
Other pages inside ModalStackNavigators.js have ScrollView.
https://github.com/Expensify/App/blob/2905e6d9115522f6d4a4cd0b510dd580ccf5894e/src/pages/ShareCodePage.js#L63
### What changes do you think we should make in order to solve the problem?
We can fix this issue by inserting ScrollView Component into Workspace and Preference pages.
For example, we add scrollview into settings/workspace by wrapping _.map with ScrollView
https://github.com/Expensify/App/blob/2905e6d9115522f6d4a4cd0b510dd580ccf5894e/src/components/FeatureList.js#L35

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment]
Not overdue, some active discussion here

**Comment by MitchExpensify** [comment]
Whats the latest here @0xmiroslav ?

**Comment by roryabraham** [comment]
[@samh-nl's proposal](https://github.com/Expensify/App/issues/26098#issuecomment-1695963668) LGTM 👍🏼

**Comment by MitchExpensify** [comment]
**Payment summary:**

- $750 @0xmiroslav requires payment [offer](https://www.upwork.com/nx/wm/offer/26956698) (Reviewer)
- $750: @samh-nl requires payment [offer](https://www.upwork.com/nx/wm/offer/26956699) (Contributor)
- $50: @Yokabdk requires payment [offer](https://www.upwork.com/nx/wm/offer/26956701) (Reporter)

**Comment by MitchExpensify** [comment]
Please accept the Upwork offer @0xmiroslav, thanks!

Paid and contracts ended for @samh-nl & @Yokabdk 🚀

**Comment by MitchExpensify** [comment]
Done! Paid and ended! Thanks
