### ISSUE TITLE
[HOLD for payment 2023-09-08] [$500] SetupNode action failing when patch has been updated

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26101]
### Problem

When we modified only a patch without changes to the package-lock.json the node_modules are not reinstalled during the build process which means the patch is not applied

@adamgrzybowski Has updated the setupNode script to also listen to changes in the patch folder and if that is a case, apply the patch. 

There is however still an issue which causes the setupNode action to fail now when patch is updated https://github.com/Expensify/App/actions/runs/5983634462/job/16233978359

### Solution

Lets fix the action to apply the patch safely when there is a change in the patch file
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01373fad44757789f7</li>
        <li>Upwork Job ID: 1696191190560124928</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 26372375</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
Is this up for proposals? @mountiny or @shubham1206agra only gonna work on it?

**Comment by dylanexpensify** [comment]
@b4s36t4 we've hired for this - thank you for your interest!

**Comment by dylanexpensify** [comment]
@shubham1206agra mind giving an update? 🙏

**Comment by shubham1206agra** [comment]
Waiting for PR to be reviewed

**Comment by dylanexpensify** [comment]
payment time!

**Comment by dylanexpensify** [comment]
@ArekChr mind completing the checklist today? 🙇‍♂️

**Comment by dylanexpensify** [comment]
@shubham1206agra you've been paid btw!

**Comment by dylanexpensify** [comment]
bump @ArekChr

**Comment by dylanexpensify** [comment]
@ArekChr is sick - @sobitneupane mind stepping in here for the checklist? 🙇‍♂️

**Comment by sobitneupane** [comment]
Sure @dylanexpensify. I was mostly on leave last week. So, running quite behind. I will try to get to this issue soon.

**Comment by dylanexpensify** [comment]
nice!
