### ISSUE TITLE
[HOLD for payment 2023-09-12] [$1000] MEDIUM: Polish: Display Receipts in-Chat Design Edits

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#26111]
We've created the ability to display receipts in chat, however we need a few design elements updated to reflect our standards. See below:

- For the scanning label, can we make sure that everything is aligned to the left? There should be 12px of gap between the badge and the text:
![image](https://github.com/Expensify/App/assets/2319350/a20a95d6-512f-43ff-9c52-4f7c03b72c33)

- Also notice that we want to keep a smaller gap between the bottom of the header avatar and the badge, it should be just 12px apart

<img width="664" alt="image" src="https://github.com/Expensify/App/assets/2319350/c7ffe063-bab5-44b4-a862-eae149388418">

- The text in the `Scanning` banner shouldn't be right-aligned:

![image](https://github.com/Expensify/Expensify/assets/16232057/dc2d8ad8-b82a-4c17-9b42-a74bf26a16d2)

- The receipt thumbnail in the request view on desktop/web shouldn't be full width:
![image](https://github.com/Expensify/Expensify/assets/16232057/9096186d-b05f-4640-8eb3-5b450634f607)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce3c3935c5b256ff</li>
        <li>Upwork Job ID: 1696487150157152256</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Margelo is working on this, no more proposals please 🙇‍♂️

**Comment by lukemorawski** [comment]
Hi, it's Lucas from Callstack. Happy to have a go on that!

**Comment by studentofcoding** [comment]
Will it be opened to all contributors or via agency @dylanexpensify

**Comment by studentofcoding** [comment]
Also some of the images are broken

<img width="1440" alt="Screenshot 2023-08-29 at 20 36 40" src="https://github.com/Expensify/App/assets/20473526/86d43315-f26a-4894-b1a6-a35fa5ffdbdc">

**Comment by dylanexpensify** [comment]
thanks for everyone's interest! We have an agency hired for this, so no new proposals please - ty!

**Comment by dylanexpensify** [comment]
@lukemorawski mind giving an ETA on when you'll have a PR raised? 🙇‍♂️

**Comment by lukemorawski** [comment]
@dylanexpensify Should be today

**Comment by dylanexpensify** [comment]
@lukemorawski mind giving us an update? 🙇‍♂️

**Comment by dylanexpensify** [comment]
bump @lukemorawski 🙇‍♂️

**Comment by lukemorawski** [comment]
Hey, still working on this. Should have it today!

**Comment by dylanexpensify** [comment]
@lukemorawski any update?

**Comment by dylanexpensify** [comment]
@lukemorawski this is quite a big add on the UI front, so if we can please get this ready for merge tomorrow, that'd be great!

**Comment by trjExpensify** [comment]
@lukemorawski did you get that PR up, I can't see it linked? 

This is a very important polish issue we're looking to get completed ahead of the SaaStr conference early next week.

**Comment by lukemorawski** [comment]
Hey, I have a draft PR internally. Should be out and open today! Sorry for keeping you waiting!

**Comment by mountiny** [comment]
@lukemorawski sorry for the change here, but since this was high important @luacmartins has raised a PR internally https://github.com/Expensify/App/pull/26509 we are just waiting for a design sign off there now. I think we will take care of this now. Thanks

**Comment by lukemorawski** [comment]
@mountiny Cool and sorry for the inconvenience again.

**Comment by mountiny** [comment]
@lukemorawski no problem, let's just try more communication and updates in case previous ETA wont be met especially when the issues are pressing time-wise. Onto next one 🚀

**Comment by mountiny** [comment]
Merged 🚀 leveing it open for payment to @ntdiary

**Comment by dylanexpensify** [comment]
payment time!

**Comment by luacmartins** [comment]
I think we're just waiting on payment here

**Comment by dylanexpensify** [comment]
@ntdiary sent invite!

**Comment by dylanexpensify** [comment]
offer sent @ntdiary!

**Comment by dylanexpensify** [comment]
done!
