### ISSUE TITLE
Thread - Marking the first message in a thread with a header like ( IOU & Task reports) as unread changes the layout

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and Open any IOU room (if there is no requests, request a money and open the IOU room)
2. Please make sure to have some reply in it, to test it clearly
3. Now mark the first message in the IOU report ( the one you opened ) as unread
4. You can test it in the task report with the same steps. (Optional)

## Expected Result:
Marking any message as unread shouldn't affect on the layout of the page, every element should still in place.

## Actual Result:
The layout is changing after marking messages as unread.
- You feel  The header is moving Down and the message moving top
- The space between the header and the messages is decreased.
- In the IOU, you feel like the background image is moving
Notice:
Normal threads have similar problems, but they are usually only slightly noticeable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ffc9dfb9-7da8-484c-8e67-9bbb47976c89

https://github.com/Expensify/App/assets/115492554/037c4ab0-4872-4654-b451-4c87bad1a92f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692415875312819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm going to close this as it doesn't feel like a bug as much as a feature/improvement. You can still fully use the threads and the unread features.

**Comment by Ahmed-Abdella** [comment]
@tjferriss It is actually not reproduced this way anymore. But there are some issues around the horizontal grey line between the header and the messages. I discussed it in another report here https://expensify.slack.com/archives/C049HHMV9SM/p1693183486459189?thread_ts=1693183486.459189&cid=C049HHMV9SM.
If you have time please check it. I think it is a valid bug.
