### ISSUE TITLE
[$1000] Web - IOU - No limit for the merchant name

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Request money -> Enter the amount -> Choose the user
4. Click `Show more` and change the merchant name to very long -> Save

## Expected Result:
There is a limit for the merchant name

## Actual Result:
No limit for the merchant name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/23597957-1460-461e-aa2a-ac21cd188a73

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01475b82368a6ca68f</li>
        <li>Upwork Job ID: 1696584449221238784</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Ah cool, thanks for letting me know! Going to close this out in favor of https://github.com/Expensify/App/issues/18647 then. Thanks @dhairyasenjaliya
