### ISSUE TITLE
LHN - Status emoji is not shown next to account name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24414
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in using Account A.
3. Click on Settings.
4. Click on Profile.
5. Click on Status.
6. Click on Status again and select an emoji and enter a text.
7. Click on Save.
8. Make sure the chosen emoji appears next to avatar.
9. Log out of Account A.
10. Log in using Account B.
11. Look for the chat with Account A in LHN.

## Expected Result:
Account B should see Account A's status emoji next to their name

## Actual Result:
There is no Account A's status emoji next to their name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aef620cc-627d-4164-8463-caa0d573042d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkarkachov** [comment]
Works as expected on my side

![image](https://github.com/Expensify/App/assets/1360242/25ba094d-903e-4af5-bb76-6f20799ab844)

**Comment by garrettmknight** [comment]
@stitesExpensify can you test this one and see if it's still happening on the beta?

**Comment by stitesExpensify** [comment]
Hmm looks like it could be something to do with having a long display name vs a long email? I'll add it to the project

**Comment by stitesExpensify** [comment]
cc @perunt

**Comment by perunt** [comment]
this issue recorded 3 days ago but [mentioned](https://github.com/Expensify/App/pull/24414) feature was [deployed to staging](https://github.com/Expensify/App/pull/24414#issuecomment-1698378237) two days ago. So it was just miscommunication 😄 
I'll attach a valid screenshoot
<img width="305" alt="Screenshot 2023-09-01 at 10 36 25" src="https://github.com/Expensify/App/assets/48593211/d93b6a64-3a84-46a3-a59f-cd9551eb83c6">
