### ISSUE TITLE
[HOLD for payment 2023-09-29] [Wave 6: Tags] CRITICAL - Billable Toggle UI

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#26128]
**Reminder**: only users in the [beta](https://github.com/Expensify/Expensify/issues/311967) will have the data

## Design doc section
* https://docs.google.com/document/d/1eXGKhdUP98f6RUVYpRzxLi49El9Rizeqq-EYjrF24tU/edit#heading=h.646at3jzo9wo

**Comment by amyevans** [comment]
Convenient auto-assignment 😄 (feel free to unassign if you don't want to be assigned though)

Callstack will be helping here!

**Comment by waterim** [comment]
Hello, Im Artem from Callstack, can I help with this one?

**Comment by puneetlath** [comment]
Thanks @waterim! Could you provide an ETA on when you think you'll be able to have a PR up? 

Also, do you plan to tackle everything in one PR? Or break it up in some way?

**Comment by waterim** [comment]
Hello @puneetlath I think I will have enough capacity tomorrow and Friday to create a PR for this feature
I think 1 PR should be enough to handle a billable toggle

**Comment by puneetlath** [comment]
Ok sounds good. Looking forward to it!

**Comment by puneetlath** [comment]
hey @waterim just checking in on how this is going. Do you need any help?

**Comment by waterim** [comment]
Hey @puneetlath 
Im sorry, but I had full capacity, need to finish 2 small things today and will fully dive into the billable toggle today evening and tomorrow, is it okay?😞

**Comment by puneetlath** [comment]
Ok sounds good!

**Comment by jeet-dhandha** [comment]
Just curious @amyevans can `External` member be assigned to this type of PR's ?

**Comment by waterim** [comment]
Hello @puneetlath, I have a question regarding this `"policy.disabledFields.defaultBillable"`, from where I can get it? Because as I can see in Onyx data: 
<img width="299" alt="image" src="https://github.com/Expensify/App/assets/39777589/57d9cec4-bae4-414b-b88a-bd2ae0848fb5">
Policy doesn't have something like this at that moment on my side.
Do I need some beta or backend is not ready yet?

**Comment by amyevans** [comment]
@jeet-dhandha Not usually, but it isn't a hard and fast rule. Keep your eye out in the #expensify-open-source channel in Slack where internal engineers would likely recruit external help as needed (in addition to applying the `External` label on the issue).

@waterim, answered your question [in Slack](https://expensify.slack.com/archives/C02MW39LT9N/p1694197372925369)!

**Comment by waterim** [comment]
@puneetlath @amyevans PR is opened :)

**Comment by puneetlath** [comment]
@0xmiroslav think you'll have a chance to review today?

**Comment by puneetlath** [comment]
Awesome, thanks!

**Comment by amyevans** [comment]
@waterim I realized https://github.com/Expensify/App/pull/27172 did not include passing the billable param to `CreateDistanceRequest`.

What do you think about just including support for that in your PR for editing in https://github.com/Expensify/App/issues/26793? Or would you prefer a separate PR here?

**Comment by waterim** [comment]
@amyevans I can add to the same PR, because thats bot a lot of changes and PR will not be huge

Sorry, I didn’t know that DistanceRequest requires billable as well(in documentation it was only for money request)

**Comment by amyevans** [comment]
Sounds good, and no worries!

**Comment by puneetlath** [comment]
Looks like we just need to pay out @0xmiroslav for C+ on this. 

@0xmiroslav should I send you an Upwork contract or will you track this separately for yourself?
