### ISSUE TITLE
Payments - Paypal.me shows 2 hints/placeholder

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings-> Click payments
2. Click Add payment method -> Click PayPal

## Expected Result:
There should be only one Hint label

## Actual Result:
It displays 2 hint labels or placeholder

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_8359](https://github.com/Expensify/App/assets/115492554/89b5e05f-ceb4-4f5d-a83e-01dedd9fcf2c)

https://github.com/Expensify/App/assets/115492554/7e35bd9f-b4bf-4774-9a30-c7870d98fc34

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692540627406659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Sorry if this wasn't clear, this is intentional and we can close.
