### ISSUE TITLE
Web -  After refreshing the page, the task title and description fields do not automatically focus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Assign task" section.
3. Enter a title and create a task.
4. After creating the task, click on the task title or description field.
5. Refresh the page.
6. Notice that the task title and description fields do not automatically focus. (Note: This issue is not present in the production)

## Expected Result:
After refreshing the page, the task title and description fields should automatically focus

## Actual Result:
After refreshing the page, the task title and description fields do not automatically focus as expected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bc744b25-dfdb-4e6a-863d-980fb2760597

https://github.com/Expensify/App/assets/93399543/a9f37978-6822-407d-a47d-1fed3588d5e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693003307227389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I don't think this is a blocker and TBH I think we should do nothing here

**Comment by ayazhussain79** [comment]
it is working fine on Production but not in staging

**Comment by chiragsalian** [comment]
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.
