### ISSUE TITLE
 Share code shows wrong default avatar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26135]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account
2. if you have set profile picture remove it (Settings -> Profile -> Click profile photo -> Remove photo)
3. Go to Settings -> Click share code
## Expected Result: 
It should show same avatar as set in profile
## Actual Result: 
It shows different avatar in Share code

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/80753dc6-a7e5-40b4-a0ef-39ccd4ccc308

![Snip - (53) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/b66d57c9-2023-4c71-9f7c-d5e3e00b1314)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693258458168319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Gonna close this issue since it's a dupe
