### ISSUE TITLE
Extra space in currency:  XOF:FCFA displayed as "XOF:F CFA"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to expensify app
2. Click on + icon and select request money
3. Click on currency and scroll down to XOF
4. Observe that it is displayed as XOF:F CFA

## Expected Result: 
Extra space should be removed and currency should be displayed as XOF:FCFA
## Actual Result: 
Extra space is added between F and C
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/f088b1e0-a716-4af2-b519-fe89faa411dc" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/147c4d52-59fb-438d-b6d5-0ae6fdc56ae8" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692593147704699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
@tgolen Not sure if this would be `internal` or `external` due to the native package, so wanted to get your input — TIA!

**Comment by tgolen** [comment]
I think we just want to stick with the `Intl` implementation for it so we are at least consistent with web standards as @Krishna2323 points out. I'm going to close this for now.
