### ISSUE TITLE
[$1000] Issue in saving waypoints; no route displayed

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26147]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### This issue is present on the latest main branch

1. Go to a workspace chat (if you don't have a workspace yet, create one
2. Click the "+" icon next to the text input (i.e. composer)
3. Click Money Request
4. Click the Distance tab on the Right Hand Side panel that appears
5. Select "Start" and type any U.S. address and click a suggested option
6. Select "Finish" and type any U.S. address and click a suggested option
7. Confirm that there is no line drawn on the map to indicate a route between the start and stop points
8. Confirm that there is an error logged out in the developer console of the browser

<details>
<summary>VIDEO</summary>

https://github.com/Expensify/App/assets/98560306/709bbedf-a69e-49bf-a5ed-3d27c30efefa

</details>

## Expected Result:
A route should be drawn on the map

## Actual Result:
No route is drawn

## Workaround:
N/A

## Platforms:
Which of our officially supported platforms is this issue occurring on?

_Only tested on the web, but I suspect the issue is present on all platforms_

- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4f0ba58c25296a9</li>
        <li>Upwork Job ID: 1696388884744749056</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
@bernhardoj Were you able to reproduce this issue? if so can you explain me how you did that?

**Comment by b4s36t4** [comment]
You tried on local or prod/staging?

**Comment by b4s36t4** [comment]
Ok, thanks for the help.

**Comment by hayata-suenaga** [comment]
Using @bernhardoj 's suggestion to fix the issue on the backend

**Comment by thienlnam** [comment]
@hayata-suenaga I'm handling this in https://github.com/Expensify/App/pull/25980

**Comment by muttmuure** [comment]
Not overdue

**Comment by thienlnam** [comment]
On staging - this is linked to another issue so going to close this one
