### ISSUE TITLE
Not able to zoom default avatar pictures

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26156]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on any avatar that has default image first and has uploaded image second.

## Expected Result:
We should be able to zoom default avatar pictures

## Actual Result:
 Not able to zoom default avatar pictures

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ce36488f-d91d-48f5-a969-30bb368fb054

https://github.com/Expensify/App/assets/115492554/90212c50-d9f4-4b6b-8609-e95e90e09379

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692592936003879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
@shawnborton curious for your take here?

**Comment by shawnborton** [comment]
Hmm I think there is an existing issue right now to add a "View profile photo" to the dropdown that launches when you click on edit next to your profile picture. So I think this is a known thing and we're working on a fix.

**Comment by laurenreidexpensify** [comment]
Okay based on that feedback I am gonna close, as it will be fixed in the scope of that
