### ISSUE TITLE
[$500] Improve AdHoc build time

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#26152]
### Problem

AdHoc builds are working well, but the build times are slow and other minor improvements can be made.

### Solution

Implement further improvements: 
- We can shorten Android dev build time by adding one additional line in build.gradle where we will pass the flavors that are only for development and we can skip bundling JS and assets
- Fabric requires iOS build schemes without spaces e.g. instead New Expensify AdHoc we should rename it to NewExpensifyAdHoc
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b1f5eb0cd53791a</li>
        <li>Upwork Job ID: 1696431313907130368</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Just noting that last time our prod release CI flows broke due to the name change as the build path changed. So we'll need to be careful to watch out for this when first releasing the changes.

**Comment by Julesssss** [comment]
Hey @miljakljajic, can you pay out a C+ reviewer bonus for @sobitneupane please

**Comment by miljakljajic** [comment]
Sent contract @sobitneupane !

**Comment by sobitneupane** [comment]
@miljakljajic I will request payment in newDot. I believe a payment summary for the issue is all that's required.

**Comment by miljakljajic** [comment]
Payment summary: 500 USD for the improvements made to AdHoc build time

**Comment by sobitneupane** [comment]
Requested payment on newDot.

https://github.com/Expensify/App/issues/26152#issuecomment-1730864306

**Comment by JmillsExpensify** [comment]
$500 payment approved for @sobitneupane based on [BZ summary](https://github.com/Expensify/App/issues/26152#issuecomment-1730864306).

**Comment by miljakljajic** [comment]
Thank you!
