### ISSUE TITLE
Workspace - Infinite loading UI skeleton in invite new members after refresh

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings then workspaces open any workspace
2. Click members then Invite to open the Invite new members page
3. refresh the page

## Expected Result:
The suggested acounts should be displayed in the Invite new members page

## Actual Result:
 Infinite loading UI skeleton in invite new members after refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3786c976-c2b8-43c9-a48d-2fa6bc71d001

https://github.com/Expensify/App/assets/115492554/99e83c6b-878c-4568-93b8-ee26655255b9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693280180858769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Ahmed-Abdella** [comment]
Please note that the behavior in staging differs from production. In production the invite new members page is blank

**Comment by amyevans** [comment]
Hmm I can't reproduce (tried on both staging and local)

**Staging:**

https://github.com/Expensify/App/assets/7277067/46ed96f9-3757-406b-99d2-d2c05953dd2c

**Local:**

https://github.com/Expensify/App/assets/7277067/d358cdcb-05a4-484d-8d53-a8cd7fa23aa7

@jliexpensify could you try as well? In any event, this shouldn't block deploy.

**Comment by jliexpensify** [comment]
So this happened to me:

![image](https://github.com/Expensify/App/assets/30815269/013850d4-9f73-4a8b-aee7-441805dae6e7)

Here were my repro steps:

1. Open settings then workspaces open any workspace
2. Click out of New.Dot and into this GH
3. Click back into New.Dot tab and see it crash

So I couldn't even complete this the first time.

I tried again a second time, after refreshing, and wasn't able to reproduce. I think it's probably to do with general instability, since it's not always reproducible? cc @amyevans

**Comment by amyevans** [comment]
Okay thanks for giving it a shot. Regardless it seems pretty inconsistent and definitely an edge case. Given that, I don't think it's worth expending more effort on it at the moment, so going to close. Feel free to reopen though if you disagree @jliexpensify!
