### ISSUE TITLE
[HOLD for payment 2023-09-07] [HOLD for payment 2023-09-06] [$1000] Request money: App Crashes when clicking UP key from keyboard after requesting money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. click the + icon from LHN
3. Click request money
4. Make a request money
5. Open the IOU report of the requested money
6. Click UP key from the keyboard
7. Observe the result

## Expected Result:
The app shouldn't be crashed

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.58-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ae7117f1-4095-46a0-98a9-8c03281cb1f1

https://github.com/Expensify/App/assets/115492554/c1e6549f-e27a-475e-8e53-322d883b3509

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693307519948199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bc5b54c670a647e</li>
        <li>Upwork Job ID: 1696560199294820352</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26393982</li>
<li>hungvu193 | Contributor | 26393987</li>
<li>misgana96 | Reporter | 26393989</li>
</ul></li>
    </ul>
</details>

**Comment by bondydaa** [comment]
commented on https://github.com/Expensify/App/issues/26209 asking for guidance

**Comment by situchan** [comment]
@bondydaa I think @mountiny is on travel right now and not likely to answer soon.
As C+, I am fine to go with https://github.com/Expensify/App/issues/26209#issuecomment-1697557269.

**Comment by misgana96** [comment]
Offer accepted. Thank you

**Comment by luacmartins** [comment]
I'm gonna demote this to NAB. While it isn't great that the App crashes, I think this is enough of an edge case that it won't affect most users. Besides, we also have a PR up which will likely be merged tomorrow.

**Comment by situchan** [comment]
> I'm gonna demote this to NAB. While it isn't great that the App crashes, I think this is enough of an edge case that it won't affect most users. Besides, we also have a PR up which will likely be merged tomorrow.

But it's bad that once crash happens, always crash even after refresh, until logout and re-login.

I have [PR](https://github.com/Expensify/App/pull/26265) ready
@luacmartins it's up to you whether to merge or not

**Comment by mountiny** [comment]
Thanks for help here @hungvu193 @situchan this was quite tricky thing to discover.

**Comment by kevinksullivan** [comment]
@situchan fill out the checklist above when you get a chance. Thanks!

**Comment by kevinksullivan** [comment]
Paid out, closing.

**Comment by kevinksullivan** [comment]
Upwork giving me the blank screen contract end bug, so I'll need to come back to this for you @situchan . 

![image](https://github.com/Expensify/App/assets/22508290/c382b966-1d77-44b4-a061-1044dc117689)

**Comment by kevinksullivan** [comment]
@situchan in the meantime, can you complete the steps above?
