### ISSUE TITLE
IOU - Duplicate IOU report if the user requested an IOU immediately upon logging in via FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click the FAB button 
3. Click Request Money
4. Enter any amount 
5. Click on the next button
6. Select any user with an existing IOU history
7. Complete the IOU

## Expected Result:
The user should be redirected to the DM c user and in the conversation see one updated IOU report

## Actual Result:
The user is redirected to the DM and the conversation duplicates the IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd67d353-eecb-4811-a47f-b172d67a308a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm not able to reproduce the issue on either iOS or web Chrome. Is this only an Android bug @lanitochka17? If so, can you please make sure the report is filled out accurately?

**Comment by lanitochka17** [comment]
@tjferriss Sorry for the confusion.
macOS Ventura 13.4.1 - Chrome

Correct video:

https://github.com/Expensify/App/assets/78819774/da4dbbee-374c-4d3d-a7d5-446448689e06

**Comment by tjferriss** [comment]
I'm not able to reproduce on the latest version of Chrome.
