### ISSUE TITLE
Workspace - Specific error message which number should BA end not displayed when adding BA

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and log in
2. Navigate to a Workspace > Bank account 
3. Tap "Connect online with Plaid"
4. Select Chase and continue with the flow
5. Select the account ending 1111 
5. On the "Connect Bank account," enter the correct routing number and incorrect account number (1111222233334444)

## Expected Result:
The specific error message for entering the wrong bank account and in which number should the bank account end is displayed

## Actual Result:
The general error message "An unexpected error occurred while trying to add your bank account" is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 13.58-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/39538368-d2c9-4ee6-ac6a-08b9c995b827

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I'm unable to reproduce this
![Screenshot 2023-08-29 at 3 32 18 PM](https://github.com/Expensify/App/assets/22219519/8f7c9f5a-447c-400c-9914-3d0654854def)

**Comment by luacmartins** [comment]
This is a really small issue and we're still displaying an error to the user, so I'll demote this to NAB.

**Comment by madmax330** [comment]
Didn't dig into this yet

**Comment by madmax330** [comment]
Same, working on higher priority stuff

**Comment by madmax330** [comment]
No update

**Comment by madmax330** [comment]
I also cannot reproduce this, going to close
