### ISSUE TITLE
Chat - Unable to leave thread on IOS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify IOS app
2. Click on the + button at the bottom of the screen
3.  click on new chat or create a group
4. Start the conversation and select the message 
5. Select the reply in thread option
6. Now click on the profile picture and at the end you will see a option leave the thread
7. Click in that option 
8. The page will be redirected to concierge
9. Click Back button
10. Click 1 Reply in conversation

## Expected Result:
The page should redirect to concierge but there should be no error message

## Actual Result:
The page redirected to concierge and displayed an error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/75b029b0-31ca-4a69-8ba2-58857239be8e

https://github.com/Expensify/App/assets/78819774/51b2d44c-725a-41ac-bd98-20674d4561a7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Talha345

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692047444760739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Focusing on higher priorities. Will look at this next week.

**Comment by muttmuure** [comment]
Catching up after ooo and unable to test this yet. Will get to it tomorrow

**Comment by muttmuure** [comment]
I don't think this is a bug, the back button is taking you back to the thread.
