### ISSUE TITLE
Settings - Keyboard shortcuts list is appeared for a short time in second window after opening it when opening and closing it on first window

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website on 2 windows
2. Click on Ctrl + J to open Keyboard shortcuts list on first window
3. Close the Keyboard shortcuts list and go to second window. You can see that Keyboard shortcuts list is appeared for a short time.

## Expected Result:
Keyboard shortcuts list should not be appeared for a short time in second window after opening it , when opening and closing it on first window

## Actual Result:
Keyboard shortcuts list is appeared for a short time in second window after opening it when opening and closing it on first window

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dcee38da-9393-4930-9db7-4347bae2bba4

https://github.com/Expensify/App/assets/115492554/15d06bd1-6533-41f8-8a43-fd7f81fa6a8d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692693785661739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I asked in the original Slack post if we should consider this a bug.

**Comment by sakluger** [comment]
We're discussing moving the shortcuts modal to the RHN, so I'm going to close this issue.
