### ISSUE TITLE
Split bill - Inconsistency error when split bill

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB, then choose split bill.
2. Input amount of money and click "Next"
3. Copy the URL on the browser
4. Open a new tab -> Paste the copied URL
5. From the 2nd tab -> choose who to split the bill -> click "Next"

## Expected Result:
After selecting the bill splitter and pressing the "Next" button, both tabs are navigated according to the split bill modal

## Actual Result:
After clicking "Next" in the 2nd tab, the first tab is not synchronized but still stands in the modal to choose people to split bill.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/111f300d-f77c-4ea0-95f2-0fce87e1f608

https://github.com/Expensify/App/assets/115492554/1b59f195-f096-4265-a629-59b85feac4e8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Le Thi Thu Thuy

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692694330093219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
Looking for a reference to why this is expected, via [the Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1693388692505539?thread_ts=1692694330.093219&cid=C049HHMV9SM)

**Comment by conorpendergrast** [comment]
I haven't heard [via that Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1693388692505539?thread_ts=1692694330.093219&cid=C049HHMV9SM) why that might be expected. Closing!
