### ISSUE TITLE
Zoom in on very large image while loading displays black screen throughout and breaks the preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send very high resolution image (8k or above, example attached)
4. Click on sent image and zoom in the preview on black part of image which is not loaded
5. Scroll above and in all corners, observe that even though some part is loaded, it displays black screen
6. Zoom out and zoom in on the part that is loaded, app still displays black screen and now on closing preview and reopening, app preview either glitches or shows fully black preview
## Expected Result: 
App should not display black screen for parts of image that is loaded and should not break the preview when zooming on large resolution semi loaded image
## Actual Result: 
App displaya black screen even for parts of image that is loaded while zooming in and breaks the preview when zooming on loaded part when viewing large resolution semi loaded image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1c8409cf-abab-404b-bd82-209ec7d11666

( Attachment to be uploaded is in the slack thread size is big and unable to attach in this GH ticket)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692030874926459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Checking with engineering on this - Should we limit the size of files to be uploaded and show an error or accommodate for any size file?

**Comment by Julesssss** [comment]
> Should we limit the size of files to be uploaded and show an error

Yeah I agree this is the simpler solution (and what Slack does).

**Comment by Julesssss** [comment]
I worry we'll need a backend fix for this though. And there is no chance I can work on this in the next month. 

If this only occurs on certain platforms maybe we can just close it for now?

**Comment by slafortune** [comment]
Yes, I agree we can close this for now.
