### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] IOS - Push notification is sent to the device even though the app is logged out.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to Account A.
2. Turn OFF the network connection to enter OFFLINE mode.
3. LOG OUT
4. While the app is still in OFFLINE mode, send a message from another account to Account A (IMPORTANT STEP).
5. Turn ON the network connection.
6. Observer: Push notification appears.

## Expected Result:
Push notification should not be sent if app is logged out

## Actual Result:
Push notification is sent to the device even though the app is logged out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0 (tested on 1.3.62-3)
**Reproducible in staging?:** Yes
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/08603ed2-4535-42b6-83ae-5506a02bc61f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692691382974179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134d9932ee5c7e512</li>
        <li>Upwork Job ID: 1698485880458186752</li>
        <li>Last Price Increase: 2023-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26547257</li>
<li>tranvantoan-qn | Reporter | 26547259</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
Will test on Monday!

**Comment by sophiepintoraetz** [comment]
I'm able to reproduce this:

https://github.com/Expensify/App/assets/42940078/83d9eb62-e72f-4f37-862f-2114dee53a42

**Comment by roryabraham** [comment]
I'm actually really confused by the RCA here... it seems like we're missing something:

- When the user signs out, we actually call `Session.signOutAndRedirectToSignIn`. 
- `redirectToSignIn` clears persisted requests. So when does the `LogOut` API call factually happen? Does it actually happen at all?
- When we clear storage and redirect to sign-in (still offline), we should be triggering [PushNotification.deregister](https://github.com/Expensify/App/blob/b8925d9baa713fcd16f4f5d2bba61db59bc64b03/src/libs/Notification/PushNotification/subscribePushNotification/index.js#L22) – in fact that's the function you're leveraging in your PR. Why is [Airship.removeAllListeners](https://github.com/Expensify/App/blob/80d41d21d23887f6d6e253fe1efadecc9fbc1538/src/libs/Notification/PushNotification/index.native.js#L137-L138) insufficient to prevent the notifications from being received?

**Comment by sophiepintoraetz** [comment]
@thesahindia, please request $500 once you have completed the checklist.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/26247#issuecomment-1742251847).
