### ISSUE TITLE
Android - app crashes after deleting message from edit composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any message
3. Edit message
4. Clear edit composer and click Save icon
5. Click Delete button from Delete comment popup

## Expected Result:
Message is deleted successfully

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23b0a787-8899-470c-b491-8eb0d08d9624

**Expensify/Expensify Issue URL:**
**Issue reported by:** @0xmiroslav
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692745031849559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Not reproducible for me on android native. 

https://github.com/Expensify/App/assets/54866469/7b606167-503b-4840-8866-7d91bc9c4bd0

**Comment by joekaufmanexpensify** [comment]
Closing for now, but added a comment to the slack thread so we can discuss further.
