### ISSUE TITLE
Web - Delete Confirmation message does not disappear when requested money is payed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Using User A Request money to User B
2. From User A go to IOU Report and Click on the Delete button.
3. Notice the Delete Confirmation message is shown. Don't Confirm or close the Delete Confirmation message.
4. While the  Delete Confirmation message is still open Pay the requested money from User B.
5. Notice the  Delete Confirmation message does not disappear and Confirming the Delete Action causes an error .

## Expected Result:
 Delete Confirmation message disappears

## Actual Result:
Delete Confirmation message does not disappear and Confirming the Delete Action causes an error .

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dc37622f-844e-46b0-bfae-411f539a5569

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692754551448189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
I'm not able to reproduce

**Comment by adelekennedy** [comment]
coming back to this one, I still can't reproduce and I'm not positive that this is unexpected if the user deleteds teh request _but doe not confirm it_ the system shouldn't treat the IOU as if it's been deleted and block the payment
