### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500]  Workspace - In Invite new members the "Contacts" caption does not disappear when scrolling

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisites:
Log in to HT account.
Steps:
1. Open New Expensify app
2. Go to Settings
3. Go to WorkSpace
4. Open or create a WS
5. Go to Members
6. Tap the "Invite" button
7. Scroll up the contact list

## Expected Result:
The caption "Contacts" should be above the list of contacts and when scrolling go up and disappear

## Actual Result:
The "Contacts" caption remains in place when scrolling through the contact list and is displayed at the top of the contact list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ee887cda-87f8-47f0-bb46-6f56482abbb4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f0f40876a997e8c</li>
        <li>Upwork Job ID: 1696980437682036736</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26529846</li>
<li>mkhutornyi | Contributor | 26529849</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment]
This is not a deploy blocker. This came from #22622 which was deployed to production yesterday.

**Comment by situchan** [comment]
@hayata-suenaga for future issues, adding `External` label will do everything needed for external job. i.e. `Help Wanted` will be added automatically and auto-assign C+.
It seems C+ not auto assigned yet. I can take this if you agree.

**Comment by itvalentin19** [comment]
How can get new members list?

**Comment by hayata-suenaga** [comment]
still accepting proposals

**Comment by hayata-suenaga** [comment]
send [a message ](https://expensify.slack.com/archives/C01GTK53T8Q/p1694016894386579)in #expensify-open-source slack channel about this issue

**Comment by hayata-suenaga** [comment]
> > > @mkhutornyi's proposal looks good. I think we should disable iOS sticky behavior in SelectionList to be consistent with OptionsList.
> > 
> > 
> > Did the approach turn out to be incorrect?
> 
> I believe yes.

nop I just completely missed that comment 😓

**Comment by CortneyOfstad** [comment]
@hayata-suenaga bump on the above — thanks!

**Comment by hayata-suenaga** [comment]
ops sorry I missed this 😓 

@mkhutornyi can you provide the summary of dates so that we can check?

**Comment by CortneyOfstad** [comment]
@mkhutornyi @situchan sent you both offers in Upwork for the bonus amount. Please let me know once you accept and I can get those paid. Thanks for your patience with this!

**Comment by CortneyOfstad** [comment]
Both payments have been made! @situchan where are we at with the checklist above? Thanks!

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22622
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22622/files#r1348750497
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No need regression test as this is super minor UI bug and not affect users.

**Comment by CortneyOfstad** [comment]
Perfect! Thanks @situchan! Closing this!
