### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Leaving threads lands you in concierge chat

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#26250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
"leave" a thread via settings 

## Expected Result:
Get dropped in the parent thread. Link to the specific reportAction (even though for now that will just take you to the bottom of the report)

## Actual Result:
You will be taken to your concierge chat.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.57-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [monika.szczygiel@callstack.com](mailto:monika.szczygiel@callstack.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**
https://github.com/Expensify/App/assets/36425901/c3d741db-d2be-46f4-82f7-166cb7c308e5
**Expensify/Expensify Issue URL:**
**Issue reported by:** mitch@expensify.com
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9d7890bbfeaba17</li>
        <li>Upwork Job ID: 1701115791590625280</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26604173</li>
<li>tienifr | Contributor | 26604176</li>
</ul></li>
    </ul>
</details>

**Comment by MonikaSzczygiel** [comment]
Hi folks! Additional notes: 
1. The issue occurs when you try to leave either **thread** or **room** - inability to leave - redirecting back to thread or room

**Comment by mountiny** [comment]
@roryabraham this is fixed in staging for a while but due to the apple review process there was no production release in a while
https://github.com/Expensify/App/assets/36083550/281fc1e1-de3c-42e5-b5d5-5c759c8f1347

I think the only pending question in this issue is: should we navigate to the parent chat when leaving a thread instead of the concierge chat?

**Comment by roryabraham** [comment]
I did some testing in `1.3.61-2` and this seems to work correctly for me.

> I think the only pending question in this issue is: should we navigate to the parent chat when leaving a thread instead of the concierge chat?

Yes, this sounds like a good improvement to me 👍🏼

**Comment by MitchExpensify** [comment]
> should we navigate to the parent chat when leaving a thread instead of the concierge chat?

Agree this is desired.

**Comment by roryabraham** [comment]
I'm not sure if this can really be treated as a pre-conference priority at this point. Fortunately, landing on the concierge chat when you leave a thread is not really breaking the app, and it's not really a mainline case anyways. So I'd suggest that we create a separate follow-up to patch that and fix it after the merge freeze

**Comment by MitchExpensify** [comment]
Yes, lets add this as a follow up item

**Comment by roryabraham** [comment]
Go away overdue label

**Comment by roryabraham** [comment]
> then in ReportScreen we get the reportActionID and scroll to this action

don't worry about this for now please. Just changing the URL is enough

**Comment by MitchExpensify** [comment]
Some feedback in the PR for you [here](https://github.com/Expensify/App/pull/27127#issuecomment-1715482471) @tienifr 👀

**Comment by MitchExpensify** [comment]
Offer still pending for you @Ollyws just a heads up https://www.upwork.com/nx/wm/offer/26604173

**Comment by MitchExpensify** [comment]
Added a reminder to pay on October 2nd, please take a look at the BZ steps above when you get a chance @Ollyws

**Comment by MitchExpensify** [comment]
Sounds good to me, @Ollyws !

Issuing payment now

**Comment by MitchExpensify** [comment]
Paid and contracts ended, thanks all!
