### ISSUE TITLE
[$500] Web- Wrong path when getting back on workspace settings after reloading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > any workspace chat > open details > click on workspace name to open workspace's settings menu
2. Click on back icon to get back till chat and remeber the path
3. Repeat 1st step to reach workspace's settings menu and reload the page
4. Repeat 2nd step to check path's difference

## Expected Result:
Wrong path when getting back on workspace settings after reloading

## Actual Result:
Wrong path when getting back on workspace settings after reloading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://github.com/Expensify/App/assets/93399543/a833ff25-0d23-48d5-b29e-dfdc2e7ada58

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692266593020639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b85eaf7126eba9f</li>
        <li>Upwork Job ID: 1697618744952188928</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by lschurr** [comment]
I asked in Slack but didn't get any feedback - could you confirm whether this is a bug or intended @s77rt?

**Comment by s77rt** [comment]
@lschurr We have this similar issue https://github.com/Expensify/App/issues/22041 but it won't handle this case. This is intended for now. Let's close this.

**Comment by awesome1128** [comment]
Hi, is this issue solved or not?
I want to work on this case.
Please let me know, thanks.

**Comment by awesome1128** [comment]
Wow, do I have to share my email here?

**Comment by awesome1128** [comment]
Contributor details
Your Expensify account email: network_leader@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/sulong

**Comment by s77rt** [comment]
Not overdue. @lschurr We can close this one
