### ISSUE TITLE
Deeplinks sign you out of the desktop app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make sure you are not signed in to NewDot on web.
2. Make sure you ARE signed in to NewDot on the desktop app.
3. In your web browser, navigate to a public NewDot room, such as https://new.expensify.com/r/1580121062349999
4. When prompted, click `Open New Expensify` to open the link in the desktop app.
## Expected Result: 
You should be taken to the public room in the desktop app.
## Actual Result: 
You are signed out on desktop and have to sign back in.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/43996225/964180fd-3080-4400-8f42-3845d216b054)

![image (1)](https://github.com/Expensify/App/assets/43996225/b6d088fa-61bc-4890-b990-9b8cb82002ff)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692403037720979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I can't reproduce this following the steps in the OP, @roryabraham.

When I'm not signed in on Web, but signed in on desktop.. I'm not prompted to switch to the desktop app at all: https://recordit.co/NsdxAFCBHI

For good measure, when I'm signed in on Web and Desktop... I'm prompted to switch to the desktop app and it loads fine: https://recordit.co/vTHRuM4vzV

Feel free to reopen if there are different steps to reproduce this or something, but seems all good!
