### ISSUE TITLE
[HOLD for payment 2023-09-12] Add skeleton UI to requests and `IOU` / `expense` reports to avoid initially loading as $0.00

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26270]
While we're working on broader speed improvements for backend APIs, and same goes for the front-end, there are still plenty of cases where you land on a report or a request and you quickly see $0.00 while the appropriate data loads. That creates an awkward experience where the request initially looks broken, when instead it's just loading. Let's use skeleton UI to make that loading more clear. 

Rather that distinct skeleton UI for admins/approvers, which have a pay/approve button in addition to whatever members see, let's keep things simple to start and implement the same skeleton UI for everyone. What should that look like?

Well, as a result of upcoming changes to `IOU` and `expense` reports, every request will now have at least:
 - Type (e.g. cash)
 - Amount
 - Merchant (incl. IOUs where the default is simply `Request`
 
 As a result, that gives us the following skeleton UI for requests.
<img width="859" alt="Screenshot 2023-08-30 at 22 40 25" src="https://github.com/Expensify/App/assets/1127863/07f647d8-2a95-4c7d-af29-2ac67378153e">

We also need to apply the skeleton UI to reports (below), though it will be applied using the exact same frame above for requests. 
<img width="553" alt="Screenshot 2023-08-30 at 22 45 26" src="https://github.com/Expensify/App/assets/1127863/8c227e65-9fd2-42bd-a596-8a18726ffcc2">

**Comment by vaibhav-nayak18** [comment]
can I work on this issue:#26270

**Comment by JmillsExpensify** [comment]
Sorry, this issue is internal / contributor+. Assignees are already accounted for.

**Comment by JmillsExpensify** [comment]
cc @shawnborton @dannymcclain If ya'll think I missed anything from Danny's updates yesterday.

**Comment by shawnborton** [comment]
@dannymcclain for this one:
<img width="351" alt="image" src="https://github.com/Expensify/App/assets/2319350/098bc47a-7703-451e-9e9d-0beeb73ff512">


Thoughts on making sure the total padding remains at 20px, and instead we adjust the height of the skeleton for the amount to be an odd number?

**Comment by dannymcclain** [comment]
@shawnborton Yeah that's totally fine with me. My main goal was just to hopefully have the skeleton and the final UI be the same height so that nothing in the UI was jumping/moving around once the data is loaded.

**Comment by JmillsExpensify** [comment]
Ok so @mananjadhav I think you have everything you need here. Note the total padding on top and bottom is 20.

**Comment by mananjadhav** [comment]
Yes, I've started the work on this.

**Comment by BhuvaneshPatil** [comment]
To repro this - 
- set network throttling to Slow 3G

**Comment by JmillsExpensify** [comment]
Do we think we're going to be able to get this merged on Monday? I think it's become pretty important for both of our conference promotions coming up this week.

**Comment by hayata-suenaga** [comment]
Decided to track this issue as part of Wave 5

**Comment by mananjadhav** [comment]
I will have this ready by tomorrow afternoon IST and will be available for any feedback in PST to ensure we merge tomorrow itself.

**Comment by mananjadhav** [comment]
I am done with the changes in the `MoneyRequestPreview`. I tested on web for the Distance Request too. I will push the changes by tomorrow.

**Comment by mananjadhav** [comment]
PR is raised.

**Comment by mananjadhav** [comment]
@mountiny @JmillsExpensify Can one of you update the payment summary for this one?

**Comment by mountiny** [comment]
I believe it $1000 to @mananjadhav and same to @parasharrajat for review

**Comment by mananjadhav** [comment]
Thanks @mountiny

**Comment by mountiny** [comment]
@mananjadhav Yes I think we should create a regression test for this, can you please write it up for QA to save it?

**Comment by mountiny** [comment]
Sounds good but I am not sure how this can be tested with these steps in native platforms or mweb

**Comment by shawnborton** [comment]
What's the latest on this one?

**Comment by mountiny** [comment]
@shawnborton this is completed, just waiting for a pyament

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @mananjadhav $1,000
 - Contributor+: @parasharrajat $1,000

**Comment by JmillsExpensify** [comment]
$1,000 payment for @mananjadhav approved based on payment summary.

**Comment by mountiny** [comment]
@parasharrajat @JmillsExpensify can we close this out?

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @parasharrajat based on summary above.
