### ISSUE TITLE
[$500]  IOU Distance - Save button in waypoint editor is not responsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25984
## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money > Distance
3. Go to Start and select an address
4. Go to Start again and clear the address field
5. Click Save

## Expected Result:
User is redirected to Distance page

## Actual Result:
User is not redirected to Distance page. Save button is not responsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd8b0d31-639d-468f-8c87-67180dbb8837

**Expensify/Expensify Issue URL:**

**Issue reported by:** @b4s36t4

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b55cf7fbb4a3cad</li>
        <li>Upwork Job ID: 1706726189574373376</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26890787</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
I have reported this bug earlier. 
https://expensify.slack.com/archives/C049HHMV9SM/p1693286256793039

**Comment by neil-marcellini** [comment]
I'm taking this over since it's a distance bug. Actually maybe the person who introduced this should take it if they are online.

**Comment by neil-marcellini** [comment]
I [commented on the PR](https://github.com/Expensify/App/pull/25974#discussion_r1310473662) that caused this regression. We're discussing internally about having a contributor fix this in a PR that's in progress.

**Comment by neil-marcellini** [comment]
Also not a blocker because it's under a beta

**Comment by neil-marcellini** [comment]
This was fixed long ago. Idk where but that's ok.

**Comment by neil-marcellini** [comment]
Oh wait maybe we need to pay the reporting bonus. I'll assign BZ to do that.

**Comment by johncschuster** [comment]
@b4s36t4 can you please apply for the **Reporter Role** on Upwork? I'll take care of the reporting bonus after you've done that.

**Comment by b4s36t4** [comment]
@johncschuster above offer is for Contributor role mistakenly I have accepted it.

**Comment by b4s36t4** [comment]
What do I do?

**Comment by johncschuster** [comment]
@b4s36t4 No worries. I'll edit it on my end.

**Comment by johncschuster** [comment]
@b4s36t4 I've manually invited you to a different contract with the Bug Reporter rate. Can you accept that please?

**Comment by b4s36t4** [comment]
@johncschuster Accepted new offer. Thanks :)

**Comment by johncschuster** [comment]
Payment has been issued! Thanks, @b4s36t4!
