### ISSUE TITLE
[$1000] Web - "Fake" appears in invite list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26299]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, go to Settings > Workspaces
2. Click on new workspace button
3. Go to members
4. Invite userB to workspace
5. From userB, go to workspace chat
5. Create a thread from whisper message
6. From userA, open that thread
7. Go to  Settings > Workspaces > members > invite

## Expected Result:
Should not show fake in list

## Actual Result:
Fake appears in invite list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba7e2aa9-3c4e-4844-add6-031448e3f2a2

https://github.com/Expensify/App/assets/93399543/847a7c25-2535-400f-a065-92367f3c62c9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692735080202229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bbd884645cbfe94</li>
        <li>Upwork Job ID: 1696946162794438656</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
"Fake" appears in invite list.

### What is the cause of this issue?
If user A open thread from whisper message, BE returns `personalDetailsList` as below.
![Screenshot 2023-08-30 110640](https://github.com/Expensify/App/assets/131836113/31b7f166-c21e-4d3e-b1ea-62c4097c9f9a)

We does not filter out this account, so "__fake__" appears.
https://github.com/Expensify/App/blob/63a468ef5b47deed961abcda301f88acac7c021e/src/libs/OptionsListUtils.js#L786-L799
### What changes do you think we should make to solve the problem?
We should filter out account whom `accountID` is 0 in `OptionsListUtils.getOptions`.
```js
    if (personalDetailOption.accountID === 0) {
        return;
    }
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by kaushiktd** [comment]
### Please state again the problem we are trying to solve in this issue.
When Create a thread from whisper message From userA, open that thread Go to Settings > Workspaces > members > invite. "Fake" appears in invite list.

### What is the cause of this issue?
The reason we are getting 'fake' in our output is because somewhere in our code or data source, there are personalDetailOption objects with an alternateText property set to 'fake'.
![Capture](https://github.com/Expensify/App/assets/43398804/1b360a79-ded6-4a96-b6fc-c1726157e198)

### What changes do you think we should make to solve the problem?
In the `OptionsListUtils` component.  if we are getting 'fake' in our output, it might be due to the fact that some of the `personalDetailOption` objects have this value in their `alternateText` property.

To avoid getting 'fake' values in our output, we should add an additional condition to check for the `alternateText` property in below file:

https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L786-L799

Here is the changed code:

```
if (includePersonalDetails) {
    // Next loop over all personal details removing any that are selectedUsers or recentChats
    _.each(allPersonalDetailsOptions, (personalDetailOption) => {
        if (_.some(loginOptionsToExclude, (loginOptionToExclude) => loginOptionToExclude.login === personalDetailOption.login)) {
            return;
        }
       
        const { searchText, participantsList, isChatRoom, alternateText } = personalDetailOption;
        const participantNames = getParticipantNames(participantsList);
        if (searchValue && !isSearchStringMatch(searchValue, searchText, participantNames, isChatRoom)) {
            return;
        }

        // Add a condition to skip if alternateText is '__fake__'
        if (alternateText === '__fake__') {
            return;
        }

        personalDetailsOptions.push(personalDetailOption);
        console.log(personalDetailsOptions);
    });
}
```

Video:- https://drive.google.com/file/d/1VXUGk4KeU-PnvSdXmYXa49E_6P3pN8V3/view?usp=sharing

**Comment by sonialiap** [comment]
Thanks Fedi! Adding internal label

**Comment by sonialiap** [comment]
@cead22 what's the next step here?

**Comment by cead22** [comment]
> @cead22 what's the next step here?

Sorry, the next step is me looking into this but I'm currently focused on W9

**Comment by sonialiap** [comment]
@cead22 should we move this to weekly?

**Comment by cead22** [comment]
Yes, done

**Comment by sonialiap** [comment]
@avi-shek-jha are you still able to reproduce this?

**Comment by sonialiap** [comment]
I bumped the question in Slack

**Comment by sonialiap** [comment]
No response, I'm going to assume that this is no longer an issue and close
