### ISSUE TITLE
Save the world - Tapping "I am a teacher" user is prompted to update the email address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23063
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in to your Gmail account
3. Tap Fab
4. Tap Save the world
5. Tap " I know a teacher"
6. Enter all required fields
7. Tap Let's do this
8. Tap back button
9. Tap fab
10. Tap save the world
11. Tap " I am a Teacher"

## Expected Result:
User must be redirected to the registration screen as in expensifail account

## Actual Result:
User is prompted to update the email address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/81e5744b-fe3e-489f-8c43-ff2d90a8ff4e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
This is expected behavior, when signing up as a teacher, the email must belong to a private domain.
