### ISSUE TITLE
Web -  "Pay Elsewhere" Option Not Functional in Dropdown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings >Create Workspace.
2. Click on the plus sign and choose "Request Money."
3. Enter the desired amount and select the created workspace.
4. Click on the requested money, and the "Pay with Expensify " button will appear. Click on Chevron, to open the dropdown menu.
5. Select the "Pay Elsewhere" option from the dropdown menu.
6. Notice that the "Pay Elsewhere" option is displayed again in the dropdown menu.
7. Click on the dropdown icon and select the "Pay Elsewhere" option once more.
8. Observe that the "Pay Elsewhere" option in the dropdown menu does not function.

## Expected Result:
The "Pay Elsewhere" option in the dropdown menu should work properly after requesting money in the workspace.

## Actual Result:
The "Pay Elsewhere" option in the dropdown menu is not functional.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-30T072247.632.webm](https://github.com/Expensify/App/assets/93399543/f5d22ecf-51be-4b2f-85be-c6c2e2dc579e)

https://github.com/Expensify/App/assets/93399543/97c4cf82-5406-472c-9075-98e43235d0b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692858413891869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by reinaldosg** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Pay Elsewhere" option is not functioning in Dropdown

### What is the root cause of that problem?
OnItemSelected action in ButtonWithDropdownMenu component only hiding the Popover instead of do the action

https://github.com/Expensify/App/blob/dc85c60535cde5c55b006b77fde54491ba97504b/src/components/ButtonWithDropdownMenu.js#L157

### What changes do you think we should make in order to solve the problem?
we need to call the onPress action for each dropdown menus upon clicked

``` js
                    onItemSelected={(item, index) => {
                        setIsMenuVisible(false);
                        props.onPress(event, props.options[index].value);
                    }}
```

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
I think this is by design because we want the 'source of truth' for paying someone to be clicking on the green "Pay Elsewhere" button vs selecting it multiple times in the dropdown window.
