### ISSUE TITLE
Implement setMemoryOnlyKeys in Onyx

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#26304]
# Problem 
As seen in https://github.com/Expensify/Expensify/issues/312438 the `setMemoryOnlyKeys` functionality was removed, yet it was only half-implemented in the first place (on web only). It did not have any unit tests.

# Solution
Build a full solution for `setMemoryOnlyKeys` on all providers that includes a full set of unit tests.

cc @hannojg @marcaaron

**Comment by marcaaron** [comment]
A unit test to run every provider through might work. A TypeScript interface could also prevent similar issues since all classes would need to implement all the methods declared in the type.

**Comment by marcaaron** [comment]
I think we can close this out now that we added tests.
