### ISSUE TITLE
 Request Money - File's type preview is missing when user uploads file to request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB button to open menu
3. Select Request Money
4. Drop a .pdf/.docx and html file
5. Check the uploaded files into IOU conversation details

## Expected Result:
Every file type uploaded should be displayed in IOU detailed page

## Actual Result:
File's type preview is missing in IOU detail page when user uploads file to request money. User can only see .docx file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows/ Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4c400a01-f0af-4678-8ac5-5e14b38540fa

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is the expected behavior for now. The API seems to convert all files to PDF so the generic one shows up. Gonna close this issue.
