### ISSUE TITLE
mWeb - Blue line gets visible on the left side of the screen when the download banner shows up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out and sign in again on ND
2. After sign in do not touch the screen until the download banner shows up and observe the left side of the screen
3. Click anywhere on the screen to dismiss the banner

## Expected Result:
No blue line should show up at the left side of the screen

## Actual Result:
Blue line shows up when the download banner shows up and gets hidden when dismissing the banner

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.59.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6601ff69-f38d-4a5b-afcc-f2c32e095ebc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692867698569679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment]
Its a known bug. There is a issue to fix the blue outline - https://github.com/Expensify/App/issues/25820

**Comment by jliexpensify** [comment]
Thanks @ishpaul777 - #25820 was deployed to Staging 20 hours ago so let's close this one out.
