### ISSUE TITLE
 IOU Distance - Part of the address in the address field is removed when the address is long

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25974
## Action Performed:
1. Launch New Expensify app
2. Go to + > Request money > Distance > Start
3. Enter San Francisco and select the one with long address like San Francisco Pier 33 - Alcatraz Island, San Francisco, CA, USA
4. Click on Start again

## Expected Result:
The address selected is complete in the address field

## Actual Result:
The address selected is not complete in the address field. Part of the address is removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/64ee6b4c-9578-4486-9a3e-0e9f661ec815

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This is due to the character limitation to on the text box, rather than a bug. I don't think there is a real-life need to extend the number of characters we are showing. Whether it looks cut-off I think depends on how the font size set on the device. Using a Google Pixel 22 with default settings, it looks like this: 

<img width="338" alt="image" src="https://github.com/Expensify/App/assets/31225194/cffc94f8-6524-4671-90fb-163e92820852">
