### ISSUE TITLE
 IOU Distance - Recent address list flickers when clearing the address field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25974
## Action Performed:
Precondition: Have several address in the recent address list.
1. Launch New Expensify app
2. Go to + > Request money > Distance > Start
3. Select an address
4. Tap on Start again
5. Highlight the entire address in the address field and delete it

## Expected Result:
The recent address list does not flicker

## Actual Result:
The recent address list flickers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c84b71ba-0c3a-4825-a84c-3b921e8aa8ff

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Not a blocker since it's behind a beta and this is a very minor detail

**Comment by thienlnam** [comment]
Also I'm not totally sure this is a bug, the text input changed so it re-rendered the search results. Going to close this
