### ISSUE TITLE
[HOLD for payment 2023-09-07] IOU - Can tap multi times on "Pay elsewhere" button when offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26322]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Navigate to a conversation that the user owes money to the other participant (set one up if needed)
3. Disable the internet connection in the device
4. Click/tap on the Pay button in the IOU preview
5. In the IOU details page, select the option to "Settle up elsewhere" in the dropdown
6. Repeat step 4 2-3 times

## Expected Result:
Able only 1 times "Pay elsewhere"

## Actual Result:
Can tap multi times on "Pay elsewhere" button when offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/99c699af-8395-4c2f-b67f-0f1ae3f391e2

![Bug6183028_IMG_6051](https://github.com/Expensify/App/assets/78819774/1f329ed5-844c-421a-a187-d7abe6d1c563)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
I think I found the culprit: https://github.com/Expensify/App/pull/24639#discussion_r1310866896

**Comment by luacmartins** [comment]
Closing this issue since we CPed the fix.
