### ISSUE TITLE
[POLISH] Web - Save the world: Clicking enter key does nothing after filled all fields in the "I know a teacher"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26327]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click the Save the world
4. Click I know a teacher
5. fill all fields
6. Press or Click the Enter key from the keyboard
7. Observe the result

## Expected Result:
It should create a teacher room when the enter key is clicked

## Actual Result:
Clicking the enter key does nothing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/57fc16cf-23bc-4695-9e70-8c0f8daa278e

https://github.com/Expensify/App/assets/93399543/350cb4cc-dbf5-4e0f-9425-693540e45949

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693359981179739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
cc @dhairyasenjaliya, can you please take a look.

**Comment by isabelastisser** [comment]
I'm heading OOO now and will be back on Sept 5; I will reapply the Bug label but keep myself assigned for when I'm back. Thanks!

Summary: I haven't touched this issue yet, so all the triage steps are pending.

**Comment by maddylewis** [comment]
ya this seems intended. do we agree this isn't a bug / is intended behavior? if yes, i will close out this issue.

**Comment by StefStavri** [comment]
This is intended. users should tap the button.
