### ISSUE TITLE
Edit photo badge flickers when clicking on avatar to open Upload photo

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open website > any workspace > Details of it
2. Click on workspace's name > avatar 2 times to open Settings
3. Hover over and Click on Avatar multiple times and you can see that Edit photo badge flickers when clicking on avatar to open Upload photo
## Expected Result: 
Edit photo badge should not flicker when clicking on avatar to open upload image
## Actual Result: 
Edit photo badge flickers when clicking on avatar to open upload image
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (60).webm](https://github.com/Expensify/App/assets/43996225/2c0f48c8-3440-49d2-9d28-9613c3199f13)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692626745909129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by im-adithya** [comment]
Wouldn't that flicker because the click takes off the hover for a brief fraction of a second?

**Comment by sakluger** [comment]
I see the flickering you're talking about, but I would not consider this a bug worth fixing at this time.
