### ISSUE TITLE
Height gets changed for Welcome Message field when it's open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26335]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging
2. Open any room
3. Click on room title in header to open room details
4. Open settings
5. Open welcome message
6. Enter a long message to get scrollbar > Save
7.  Return to the welcome message page
## Expected Result: 
The height should remain consistent without any flickering
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f04ac9ee-8e70-45ad-8bbf-47fcc368c9c6

https://github.com/Expensify/App/assets/43996225/d6f4f9bd-a6c2-4c2b-8510-4a56da0b49be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692621999528769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Agree this is a dupe.
