### ISSUE TITLE
[$500] DEV: Logo Display Issue on Small Screens

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Open the web app in development mode.
2- Access the app using a device or browser with a small screen size (mobile size).
3- Observe the logo display on the splash screen.
## Expected Result: 
The logo on the splash screen should be fully displayed, without any cropping or misalignment, regardless of the screen size.
## Actual Result: 
Only around 1/4 of the logo is visible on the splash screen, indicating that the logo is not being displayed correctly on small screens.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d645eb32-c625-48b2-ae60-ab800cad9878

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692601767190289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01229788941fa6e972</li>
        <li>Upwork Job ID: 1699152564126756864</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal
by @ahmdshrif 

### Please re-state the problem that we are trying to solve in this issue.
The logo on the splash screen is not being displayed correctly on small screens. Only around 1/4 of the logo is visible, indicating that the logo is being cropped.

### What is the root cause of that problem?
The root cause of the problem is that the SVG image of the logo does not have a viewBox attribute. The viewBox attribute defines the coordinate space of the SVG image. When you resize the image, the viewBox attribute is used to scale the image proportionally. Without a viewBox attribute, the image is simply cropped to fit the new size.

### What changes do you think we should make in order to solve the problem?
To fix the problem, we need to add a viewBox attribute to the SVG image. The viewBox attribute should be set to the same dimensions as the image. For example, if the image is 80 pixels wide and 80 pixels high, the viewBox attribute would be set to:
```
<svg viewBox="0 0 80 80">
  ...
</svg>
```
This will ensure that the image is resized proportionally when it is resized.

### What alternative solutions did you explore? (Optional)
We could also use CSS to scale the image proportionally. However, this would be less efficient than using a viewBox attribute.

**Comment by tjferriss** [comment]
I don't have a dev environment to test. I'm asking for [clarification](https://expensify.slack.com/archives/C01SKUP7QR0/p1693940386179329) on whether we'd fix this.

**Comment by tjferriss** [comment]
@abdulrahuman5196 can you reproduce this one on dev?

**Comment by tjferriss** [comment]
@abdulrahuman5196 friendly bump... is this reproducible on dev?

**Comment by abdulrahuman5196** [comment]
Testing on dev now

**Comment by abdulrahuman5196** [comment]
@tjferriss I am not able to repro the issue in Dev as well as adhoc builds.
