### ISSUE TITLE
Web - Non-clickable email in "Welcome Message" when requesting money in workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to settings and select "Workspace." If no workspace exists, create one.
2. Click on the plus sign and choose "Request Money."
3. Enter the desired amount and select the created workspace.
4. Observe that the two emails associated with the "Welcome Message" appear in bold but are not clickable.

## Expected Result:
The email associated with the "Welcome Message" should be clickable when requesting money in a workspace. It should open up the details when clicked to ensure consistency and ease of use for the user.

## Actual Result:
The email associated with the "Welcome Message" is not clickable when requesting money in a workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/de60c3f0-4f60-4e69-a201-1751fba4c65d

https://github.com/Expensify/App/assets/93399543/f056475e-9e20-4c8a-8158-395c79f047d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692868781216269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
This is expected, closing.
