### ISSUE TITLE
[$500] Web -  Transfer balance popover hides the button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre conditions: Use an account that has wallet permissions.
1. Go to settings > wallet
2. Click on the transfer balance button
3. Notice the popover hides the button.

## Expected Result:
 The popover should not hide the button

## Actual Result:
The popover hides the button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c01d703d-7bfa-4670-bc5a-c022e81dabf3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692877614526099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1d949ed539aed53</li>
        <li>Upwork Job ID: 1699390162413826048</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
Added the external label.

**Comment by flaviadefaria** [comment]
Hey everyone, I just want to hit pause here for a minute as we're discussing internally if this is something we want to fix given it's under the beta and not something we're prioritizing right now.

**Comment by flaviadefaria** [comment]
Ok we decided this is a bug as the behavior on staging works as expected. So please continue to send your proposals.
