### ISSUE TITLE
Emoji reactions doesn't work on task send from workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a task from a workspace to account B
2. Add reactions from account B to task
3. Observe that replies count but reactions doesn't

## Expected Result:
 The emojis should be reflected in the account A workspace as the replies does.

## Actual Result:
The emojis is not reflected in the account A workspace as the replies does.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4c13e4f4-901d-4923-b424-00d36c0a50ce

https://github.com/Expensify/App/assets/115492554/c059d115-66b1-442b-93dd-f06784e5df59

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692593311239139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
I don't think this is a bug

**Comment by dylanexpensify** [comment]
Agree
