### ISSUE TITLE
Web - Save the world: Hmm... It's not here page displayed when creating a #teacher unit room for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click Save the world
4. Click I Know a teacher
5. Enter all field values
6. Click Save
7. Observe the result

## Expected Result:
The Hmm... It's not here page shouldn't appear

## Actual Result:
The Hmm... It's not here page appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.4
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bc0a2b41-bccf-4a21-9c21-8d309475ac8f

https://github.com/Expensify/App/assets/93399543/5de63d35-8064-4689-9161-9f2197147b52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693361285733779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Not reproducible

**Comment by misgana96** [comment]
@muttmuure Producing this issue has some inconsistency and needs multiple tests to produce it. It can be produced by reloading the page after opening the #teacher unit room. 
[Screencast from 05-09-2023  9:48:22 ከሰዓት.webm](https://github.com/Expensify/App/assets/48551032/a3799a02-f6e3-4656-853c-628451d1f935)
