### ISSUE TITLE
[$500] Pronouns loses focus on coming back from new group page or search page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26350]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->pronouns
3. Open new group page or search page using keyboard shortcut
4. Go back
## Expected Result: 
App should not lose focus on coming back to pronouns page
## Actual Result: 
App loses focus on coming back to pronouns page from new group  page or search page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/16645053-18a5-465a-84e8-2e719b24ccd5

https://github.com/Expensify/App/assets/43996225/ab9ab717-10cb-430f-94c3-0744b480a8f1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692636606892199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c665e819f5153b8</li>
        <li>Upwork Job ID: 1698565526817005568</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26511522</li>
<li>hoangzinh | Contributor | 26511523</li>
<li>dhanashree-sawant | Reporter | 26511526</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
![2023-09-04_17-15-22 (1)](https://github.com/Expensify/App/assets/42940078/1cdf98ff-1d71-4a2b-8ad4-f3ad69fdcb8b)

**Comment by tgolen** [comment]
🟢 for that proposal.

**Comment by sophiepintoraetz** [comment]
Got it - and it was reported earlier [here](https://github.com/Expensify/App/issues/25893) - I think this issue is essentially a dupe. Apologies for not catching this earlier and thanks for the efforts involved so far!

**Comment by sophiepintoraetz** [comment]
Cool - olly is paid - reclosing!

**Comment by sophiepintoraetz** [comment]
You're all set, @hoangzinh.
