### ISSUE TITLE
[HOLD for payment 2023-09-20] [$250] Translate the MODIFIEDEXPENSE messages

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26369]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

Stemming from the follow up clean up issue here https://github.com/Expensify/App/issues/23961

1. Create money request
2. Edit some of its values
3. change language to Spanish

## Expected Result:
Describe what you think should've happened

1. The modified expense messages are tranlated to Spannish

## Actual Result:
Describe what actually happened

1. The messages stay in English

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab76a73fe3e15035</li>
        <li>Upwork Job ID: 1697104195145465856</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26425879</li>
<li>hungvu193 | Contributor | 26425881</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
lets ship it

**Comment by BhuvaneshPatil** [comment]
I reported this issue way earlier but was marked as dupe
https://expensify.slack.com/archives/C049HHMV9SM/p1692079562836389

**Comment by mountiny** [comment]
@BhuvaneshPatil thanks for the link, we knew about this polish when we implemented the feature initially thats why we marked it as a dupe

**Comment by mountiny** [comment]
I have just separated it to a new one now as the follow ups issue already had many of them

**Comment by BhuvaneshPatil** [comment]
Thank you for confirmation @mountiny

**Comment by mountiny** [comment]
@ntdiary @hungvu193 Can you please finished the checklist

@garrettmknight can you please help with the payment? thanks!

**Comment by garrettmknight** [comment]
**Payment summary for this issue:**
- urgency bonus: no
- Reporter: N/A
- Contributor: @hungvu193 $250 paid via Upwork
- Contributor+: @ntdiary $250 paid via Upwork
