### ISSUE TITLE
Deprecate Paypal.me in product now that we're launching in-app payments and have `settle-up elsewhere`

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26368]
We're wasting a lot of time and money fixing Paypal related bugs, this just isn't worth it. It's also not a "real" feature so let's just deprecate it and focus on the stuff that matters. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01406c39bc77fa5134</li>
        <li>Upwork Job ID: 1699990475947565056</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
Deprecate in the sense? remove the option fully in frontend?

**Comment by JmillsExpensify** [comment]
Yes, sorry about that. I actually created this so we don't forget, as it's linked to an internal initiative. I'll put it on HOLD on now, though yes, I meant remove the remove the option and related code from the front-end.

**Comment by mountiny** [comment]
happy to help clear this up

**Comment by JmillsExpensify** [comment]
Alright, I posted internally on this issue and we agree to move forward with this. I'm removing the hold. We'll keep it internal.

**Comment by JmillsExpensify** [comment]
Noting the places that Paypal.me needs to be removed:

 - Settings > Wallet > Add payment method > Paypal.me
 - Bank accounts
 - System messages
 - `Pay` button on reports
 
 And so on. Basically let's remove it everywhere it's referenced in the code and get this cleaned up.

**Comment by burczu** [comment]
@JmillsExpensify As this is internal, can I un-assign myself from this issue?

**Comment by mountiny** [comment]
@burczu we will still need your help reviewing and testing the PR, will be coming later this week

**Comment by mountiny** [comment]
Made a draft PR

**Comment by mountiny** [comment]
I still need to clean this up in the backend

**Comment by mountiny** [comment]
The App part is done so for the rest I think I can make this weekly now.

**Comment by JmillsExpensify** [comment]
Still open for back-end clean-up

**Comment by mountiny** [comment]
Still lower priority

**Comment by mountiny** [comment]
Still lower priority

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by mountiny** [comment]
Made a PR to remove last keys, I will create others for Web and Auth

**Comment by JmillsExpensify** [comment]
Woo! Thank you.

**Comment by mountiny** [comment]
Lower priority

**Comment by JmillsExpensify** [comment]
We should wrap this one up when you're back next week.

**Comment by mountiny** [comment]
Did not get around last week, I think i should be able to look into this in next couple of days

**Comment by mountiny** [comment]
was focusing on urgent tasks given limited time and easter

**Comment by mountiny** [comment]
struggled to prioritize this over more urgent tasks, in my backlog still

**Comment by JmillsExpensify** [comment]
Wow, blast from the past. I do think it'd be good to get this one done once and for all, time permitting.

**Comment by mountiny** [comment]
All in the App is covered so we just need the web and auth.

Started drafts on this, want to avoid breaking anything related to oldDot as there was some usage of Paypal too there.

**Comment by mountiny** [comment]
When travelling I have completed the Web and Auth PRs, I will clean them up and get them reviewed

**Comment by mountiny** [comment]
Web PR is in a review

**Comment by JmillsExpensify** [comment]
Nice work. Let's get this issue closed!

**Comment by mountiny** [comment]
I have resolved merge conflicts on the auth PR, this might be more riskier change so might be fine to wait couple days

**Comment by mountiny** [comment]
Now that Auth perf is slightly better, I have cleaned up the tests and last PR is ready for final review and merge. Maxence is on it

**Comment by JmillsExpensify** [comment]
Still in the docket, looks like

**Comment by mountiny** [comment]
No, this is done 🎉
