### ISSUE TITLE
Unexpected back navigation in Bank Connect flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open main settings & navigate to the Bank connect page.
2. Refresh on this page.
3. Navigate back
Observe there's navigation happened for all settings pages like (main navigation, workspace pages, etc..)

## Expected Result: 
there should be navigation happened for all settings pages like (main navigation, workspace pages, etc..)

## Actual Result: 
navigation is taking to home page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[back navigation in add bank account.webm](https://github.com/Expensify/App/assets/43996225/593e32d4-34f6-4c5b-9163-50b583466b52)

https://github.com/Expensify/App/assets/43996225/05df96f0-bc61-4d47-ace6-9d111f0949e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kassahun-asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692664697127769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
> there should be navigation happened for all settings pages like

I am unsure what this means @kassahun-asefa, mind rephrasing?

**Comment by kassahun-asefa** [comment]
@MitchExpensify yea, It was confusing. Sorry. I meant to say that once you reload the page the navigation breaks. Or clicking back does not take you to the last stack in the navigation but to the home page. Let me know if you I have to rephrase again.

**Comment by MitchExpensify** [comment]
I'm reluctant to say this needs to be fixed right now. Refreshing on that page, and how its an external site, doesn't seem like a mainline flow to me. Closing for now
