### ISSUE TITLE
Improve the RBR when Editing money request

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26367]
### Problem

When money request is edited, there can be various errors which the request can run into in the backend. In such case we use what we call Red Brick Road to inform the user about the error and give them ability to dismiss it and revert to the previous state which reflects real state in the database. 

### Solution

Improve the errors posted from backend to be informative and allow the user to easily dismiss them in the App
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e737c4f1370d9e26</li>
        <li>Upwork Job ID: 1697097569182883840</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Not a priority right now

**Comment by kadiealexander** [comment]
@mountiny I'm going to shift this to weekly since it's not a priority, please put it back to daily if you feel like it needs to be!

**Comment by mountiny** [comment]
thanks

**Comment by kadiealexander** [comment]
NAP.

**Comment by mountiny** [comment]
Still no update here

**Comment by mountiny** [comment]
Lower priority still

**Comment by mountiny** [comment]
Actually I just saw we are going to migrate the command to more 1:1:1 logic so I dont think this issue will be so relevant and we will handle the RBR in the individual commands https://github.com/Expensify/Expensify/issues/312241

Going to close this one then
