### ISSUE TITLE
[HOLD for payment 2023-11-01] Improve the IOUTest with Edit, delete and payment with ACH

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26366]
### Problem

Stemming from https://github.com/Expensify/App/issues/23961

We are actively working on new features for the money request flows, where we have now added ability to delete the request, edit it or we have an option to pay the request with ACH payment type which puts the report into slightly different state than when paying the report with different payment type. The state of the report is `3` BILLING whereas report paid with different type has state `2`. Both reports have `status` 4.

But these new features have not been captured in [IOUTest](https://github.com/Expensify/App/blob/e232ea54b720acf57bab1dd09d9551d19b14038e/tests/actions/IOUTest.js#L1-L1374). Lets add it.

### Solution

Lets beef up our automated tests, think of many various solutions and really try to capture as much of the optimistic flow there as possible. In the end what we can se can be translated to the Onyx state so we can test if the onyx state is correctly updated during the flow and we are showing a report is settled when its settled for example.

**Comment by mountiny** [comment]
cc @koko57 or @allroundexperts might be interested.

**Comment by mountiny** [comment]
All yours

**Comment by tjferriss** [comment]
@allroundexperts how is the PR coming along?

**Comment by tjferriss** [comment]
It looks like we're waiting to resolve a [few items on the PR](https://github.com/Expensify/App/pull/27609#pullrequestreview-1630350270) then we should be good to merge it.

**Comment by mountiny** [comment]
@allroundexperts I have shared with you some tips for the next steps in the PR, we should be close to completing this

**Comment by mountiny** [comment]
Merged but I think we would actually want to add more tests for all the expense fields

**Comment by mountiny** [comment]
@tjferriss this should be $500 to @allroundexperts nothing else, thank you!

**Comment by tjferriss** [comment]
@mountiny @allroundexperts should that payment be through Upworks?

**Comment by mountiny** [comment]
@allroundexperts requested on newdot so we can close now

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/26366#issuecomment-1780098546).
