### ISSUE TITLE
Emoji pop-up list not shown when typing out emoji in edit mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Go to a chat and long press any message and select edit comment
3. Type out any emoji using e.g":smil:"
4. observe that no emoji list pops up like when u type emoji name in new message

## Expected Result: 
Emoji list with should pop up like in when you type out emojis in new message
## Actual Result: 
Emoji popup list is not shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.59-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/75431a3e-3a07-4ac9-9321-570f34fcd483

https://github.com/Expensify/App/assets/43996225/eb4379f6-31ad-4e59-9490-69f7f9a696f8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692673494094709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
Is this a bug or a new feature?

**Comment by puneetlath** [comment]
Agreed, this is a feature we haven't yet built. It is blocked on inline emoji's, which is blocked on some upstream PRs.
