### ISSUE TITLE
The up and down keys is not functioning in the profile page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > preference > use the up and down keys on the keyboard and observe that they are functional
2. Repeat the above step for the "about" page in settings
3. Repeat the above step for the "profile" page in settings
## Expected Result: 
The up and down keys on the keyboard should be functional in the profile page
## Actual Result: 
The up and down keys on the keyboard are not functional in the profile page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c3b03307-1037-479e-8684-2f4e92e5c9c7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692056740867719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Not sure I understand what the problem is or if this is needed.

**Comment by Yokabdk** [comment]
@muttmore The arrow keys are not functional in the "profile" page which is inconsistency
