### ISSUE TITLE
[$500] Assign task - Search displays 'you' on completing task with current user email in title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click assign task
3. In title, write @ and current login user email eg: @[test@test.com](mailto:test@test.com) if logged in with [test@test.com](mailto:test@test.com)
4. Mark the task as done
5. Open search and observe that search displays 'you' in place of current email in title of completed task message of task

## Expected Result:
App should display proper title in completed task title message in search

## Actual Result:
App displays 'you' in place of our email in title in completed task title message in search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/78e180fd-a3d0-470b-9160-62fbd1aedb88

https://github.com/Expensify/App/assets/115492554/65796950-d27b-4d55-821a-cc718ae1c651

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692720116346089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccad998fd855b0ab</li>
        <li>Upwork Job ID: 1697750730507382784</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by sakluger** [comment]
We had a similar issue in OldDot, where we replace the signed in user's email with "you" in all cases, and it had some funny results. For example, there were two admin accounts (let's call them expensify@example.com and intl-expensify@example.com). When logged in as expensify@example.com, anywhere the other admin account commented would show as "intl-you@example.com".

Anyways, I agree we should fix this. Let's make sure we account for any title/description text field where they might enter an email address.

**Comment by bforbiggy** [comment]
Hi, upwork dev taking a peek at this problem. It seems that it's not the Expensify app rendering the text incorrectly but the api itself sending back the incorrect text. This isn't Onyx's fault as it properly displays the text when internet connection is down, only when the actual response is received does it display the incorrect text.

As far as I can tell, we do not have access to the backend server code as I'm assuming we're not using a monorepo. If we do, any pointers for where the api is would be nice.

![image](https://github.com/Expensify/App/assets/22730639/ea0a947e-b7ed-4400-bd5b-7a20395575cb)

**Comment by bforbiggy** [comment]
Contributor details
Your Expensify account email: andyhecsp@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019842e04565eb754e

**Comment by sakluger** [comment]
@neil-marcellini mind taking a look to see if this is an internal issue? @bforbiggy seems to think this is a backend issue.

**Comment by sakluger** [comment]
I'm going to switch this to internal for now. We can always switch it back if it can be worked on by contributors.

**Comment by sakluger** [comment]
@neil-marcellini is OOO for another week, assigning a new engineer to investigate. Hey Carlos 👋

**Comment by sakluger** [comment]
Friendly bump @cead22 👋

**Comment by cead22** [comment]
Sorry, I'm currently focused on W9 and caught up with stuff I neglected last week today. I need some time before I can look into this. If it's urgent, can you please find another engineer?

**Comment by cead22** [comment]
If it's internal and doesn't need to be fixed within 4 weeks, can we switch to weekly?

**Comment by sakluger** [comment]
@cead22 just switched back to weekly, I think you have a week or two before it switches back to daily again :)

**Comment by cead22** [comment]
I think that's fine, this isn't a huge priority

**Comment by cead22** [comment]
No update

**Comment by sakluger** [comment]
@cead22, I'm wondering if you have a sense of when you'll be able to prioritize this one? If you agree that we should fix it, then I think we need to just get it over with, since it will be hard to find a time when you don't have other high priority projects. Otherwise, if you don't think it's that bad, then we should just close it. Thoughts?

**Comment by cead22** [comment]
I don't know, but I think this is fine to keep open as a monthly

**Comment by sakluger** [comment]
We are updating our bug-handling process to focus on bugs related to our roadmap. Since this issue is not related to any wave or VIP project, I am closing it. If you disagree and think that this is related to a wave or VIP project, please reopen or bring up for discussion in Slack (`#expensify-open-source`).
