### ISSUE TITLE
Web - Paypal add/edit field loses focus on coming back from new group or search page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->wallet
3. If there is existing PayPal account, click on it and click edit and if not, click on add payment method and select PayPal
4. Open new group/search using keyboard shortcut (i.e. by using CTRL+SHIFT+K or CTRL+K)
5. Come back and observe that focus is lost from PayPal field

## Expected Result:
 App should not lose focus from PayPal field on coming back from  new group or search page

## Actual Result:
 App loses focus from PayPal field on coming back from new group or search page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0650c111-f8df-4266-82ac-a6dd47b08907

https://github.com/Expensify/App/assets/93399543/d339d0bf-339b-41d2-a3db-34d3fd6565e9

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692888317278409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment]
I think PayPal going to deprecate https://github.com/Expensify/App/issues/26368

**Comment by strepanier03** [comment]
Thank you @pradeepmdk - I was already leaning towards closing this but with that GH you linked I'm confident it's the correct move. 

Thanks again!
