### ISSUE TITLE
Web - Misaligned Chevron in "Share Somewhere" Title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Tasks."
2. Add a title and assignee, then click "Share Somewhere."
3. Open the email in the header and observe that the chevron in "Share Somewhere" title is not aligned properly.
4. Note that the misalignment affects the visual appearance of the title.

## Expected Result:
The chevron in "Share Somewhere" title should be properly aligned and visually consistent with the rest of the interface.

## Actual Result:
The chevron in "Share Somewhere" title is misaligned and does not match the visual style of the interface, which may cause confusion or frustration for users.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (23)](https://github.com/Expensify/App/assets/93399543/ce707d7a-4e40-420f-9119-c4806c229b8b)

[screen-capture - 2023-08-24T122721.726.webm](https://github.com/Expensify/App/assets/93399543/68287cdc-7d46-4176-8519-76ba523919c2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692904929882189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment]
Changes:
modify styles for PressableWithoutFeedback in TaskPreview fixes the issue
                style={[styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter]}

**Comment by zanyrenney** [comment]
This is extreme polish, I am not going to accept this as a bug.
