### ISSUE TITLE
[$500] Workspace - The user invitation page does not load after closing the account of one of the members of the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap workspaces
4. Tap new/ already created workspace
5. Tap members
6. As the workspace admin invite a new user (that doesn't have a NewDot account)
7. Log out of the admin account in NewDot
8. Tap on invite email link and validate the account
9. Log in to NewDot with the recently validated user account
10. Verify you can see the workspace rooms
11. Navigate to account Settings > Security and close the account
12. Tap email link to verify account closed
13. Log in to workspace admin account
14. Tap profile icon
15. Tap workspaces
16. Tap workspace
17. Tap on the workspace which is used to invite a new member
18. Tap members

## Expected Result:
The workspace members page must display

## Actual Result:
The workspace members page keeps loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cdd649a9-29ac-4359-a856-103cb84afeba

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138bbf9846f916719</li>
        <li>Upwork Job ID: 1700101801229127680</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Reproducible. In my case I don't even need to invite and delete someone, the Members page shows the loading list when there's no one in the workspace

**Comment by DNature** [comment]
I wasn't able to replicate the issue as everything seems to work perfectly fine.

**Comment by DNature** [comment]
Contributor details
Your Expensify account email: <divine@dtdigital.nl>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01549d59fb89fb8ae2>

**Comment by DNature** [comment]
Contributor details
Your Expensify account email: divine@dtdigital.nl
Upwork Profile Link: https://www.upwork.com/freelancers/~01549d59fb89fb8ae2

**Comment by sonialiap** [comment]
I'm unable to reproduce now
