### ISSUE TITLE
[HOLD for payment 2023-09-21] Overlay when RHP is opening is not over the entire page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26390]
### Problem

When the RHP i sanimating open now, the overlay is not covering the entire page so you can see it animate too

### Solution

Make the overlay wider so users cannot see it to be animated.

https://github.com/Expensify/App/assets/36083550/529bc307-5431-463f-b0f2-1fbdd3b64927

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8489b64c7a71468</li>
        <li>Upwork Job ID: 1697225734121099264</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@mountiny can you pop an update here on this one, assume we're focused on this in https://github.com/Expensify/App/pull/26385?

**Comment by mountiny** [comment]
@laurenreidexpensify correct, pr is ready to be merged, just waiting for the merge freeze to be over

**Comment by laurenreidexpensify** [comment]
Merge freeze is over now right?

**Comment by mountiny** [comment]
yep, Adam is ooo, asking if someone can update the Pr now

**Comment by laurenreidexpensify** [comment]
@mountiny am assuming payment for this is $500 for C+ review, no reporting or C work?

**Comment by mountiny** [comment]
@laurenreidexpensify I think that is right, $500 to @rushatgabhane for review and testing

**Comment by laurenreidexpensify** [comment]
@rushatgabhane have you had a moment to complete teh steps above? Thanks!

**Comment by laurenreidexpensify** [comment]
@rushatgabhane bump ^^

**Comment by mountiny** [comment]
I will finish this for Rushat so we can close this. Its coming from this PR https://github.com/Expensify/App/pull/22437, it was a new feature from perspective of navigation, the author fixed the regression so no need to comment on the PR.

I dont think we need regression test for this.

@rushatgabhane can you please request $500 for internal review in NewDot, you can use this issue to track the payment. Closing

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/26390#issuecomment-1733098264).
