### ISSUE TITLE
Profile - Copy pasting automatic selected timezone shows no result (tested with Aisa/Calcutta)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26400]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->timezone
3. Unselect 'Automatically determine location'
4. Open timezone
5. Copy the timezone
6. Empty the search and paste, observe that no results are displayed

## Expected Result:
App should display results according to search

## Actual Result:
App displays no results if we copy automatic detected location, empty search and paste to search the location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9377ab35-19be-4c2a-97a6-32203c7c3eb8

https://github.com/Expensify/App/assets/115492554/6716600e-bf92-43b6-bf18-5274c86d0cc6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @@dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692721456621009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
holding for - https://github.com/Expensify/App/pull/26248

**Comment by maddylewis** [comment]
ok this is merged - https://github.com/Expensify/App/pull/26248

let's see if i can repro now.

**Comment by maddylewis** [comment]
will test today!

**Comment by maddylewis** [comment]
neither of the unexpected behaviors mentioned on this issue are occurring now. i think we're good to close this one out.
