### ISSUE TITLE
Chat - it is impossible to select a contact from the first click

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap new chat
4. Select a contact

## Expected Result:
You can select a contact from the first click

## Actual Result:
 It is impossible to select a contact from the first click

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2e626276-f39c-4734-becc-ba98613a55fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
This is not reproducible on 1.3.62- 3

**Comment by sophiepintoraetz** [comment]
![2023-09-04_17-21-34 (3)](https://github.com/Expensify/App/assets/42940078/def811d0-8928-460f-90a1-1bbcc88369c9)
