### ISSUE TITLE
[HOLD for payment 2023-09-08] [HOLD for payment 2023-09-07] [$500] Web - Sign in - "Abracadabra, you are signed in!" page is displayed in chat conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of the account
2. Enter the email on the email field and continue
3. Navigate to the email inbox and look for the magic link email
4. Change the link to staging if needed
5. Open a new tab and paste the link in the URL
6. Verify an "Abracadabra, you are signed in!" page is displayed in entire page

## Expected Result:
"Abracadabra, you are signed in!" page is displayed in entire page

## Actual Result:
"Abracadabra, you are signed in!" page is displayed in chat conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/469ce84d-1216-40a1-bab5-e1073485c0c9

![image (25)](https://github.com/Expensify/App/assets/93399543/0c27a00e-f05e-4f56-8d9d-1c7d0d6d857d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Automation Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af75b23e8aefa481</li>
        <li>Upwork Job ID: 1697320264137629696</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26440465</li>
<li>situchan | Contributor | 26440466</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Team is not able to reproduce in Production.

https://github.com/Expensify/App/assets/93399543/ff607a68-74f7-4620-98bd-9cbe0cd9434d

**Comment by mountiny** [comment]
@GItGudRatio I think that is fine, can you please make the PR?

**Comment by situchan** [comment]
I can do expedite review if @jjcoffee is already off work today

**Comment by luacmartins** [comment]
assigned you for review @situchan

**Comment by luacmartins** [comment]
I believe we're just missing payments

**Comment by adelekennedy** [comment]
### Payouts due:

Issue Reporter: N/A
Contributor: $500 @GItGudRatio (Upwork)
Contributor+: $500 @situchan (Upwork)

Eligible for 50% #urgency bonus? Y

Upwork job is [here](https://www.upwork.com/ab/applicants/1697320264137629696/hired).

**Comment by adelekennedy** [comment]
@GItGudRatio will you apply [here](https://www.upwork.com/jobs/~01af75b23e8aefa481)?

**Comment by luacmartins** [comment]
Still processing payments

**Comment by situchan** [comment]
I think I haven't received 50% bonus.
@adelekennedy can you check please?

**Comment by adelekennedy** [comment]
Yikes - sorry this is what happens when you try to clean up issues fast while ooo - adding the $250bonus for you both
