### ISSUE TITLE
[$500] mweb - Security - Keyboard hides on click of copy button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to settings> security> 2fa
2. copy code and click on Next button
3. click on copy button to copy secret key

## Expected Result:
 keyboard should not hide

## Actual Result:
Keyboard hides on click of copy button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/32d3c8d0-cc66-497a-84b3-2c4b78d69543

https://github.com/Expensify/App/assets/93399543/943bb207-4f0c-49fc-81cb-ece382ab9323

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693030191391459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f603b497eebdae61</li>
        <li>Upwork Job ID: 1699601948427620352</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the Copy button hides the soft keyboard.

### What is the root cause of that problem?
The click event is causing the soft keyboard to hide when the input loses focus.

### What changes do you think we should make in order to solve the problem?
Add a preventDefault call for the onPress event.

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the Copy button hides the soft keyboard.

### What is the root cause of that problem?
The click event is causing the soft keyboard to hide when the input loses focus.

### What changes do you think we should make in order to solve the problem?
Add a preventDefault call for the onPress event.

### What alternative solutions did you explore? (Optional)
None.

**Comment by AJV009** [comment]
How is this a bug?
You tell me the user journey here: User A copies the secret key, _*switches*_ to the 2FA app, registers the auth code, sees the new 2FA auth key, switches back to the Expensify App and then fills the auth key NOT copy the secret key again.

Think about the user journey too here :brain:

**Comment by JmillsExpensify** [comment]
I think I agree with this bug report so I'm going to triage.

**Comment by JmillsExpensify** [comment]
@eVoloshchak thoughts on the proposals so far?

**Comment by eVoloshchak** [comment]
@JmillsExpensify, is this a valid bug?
I think closing a keyboard when you click another element is the default behavior, the same thing happens throughout the app. 
For instance, try to pin a conversation with the keyboard open


https://github.com/Expensify/App/assets/9059945/1f88fff6-48c8-4f97-861c-40d9323881f7

**Comment by eVoloshchak** [comment]
Not overdue, waiting on @JmillsExpensify's opinion on https://github.com/Expensify/App/issues/26429#issuecomment-1720045360

**Comment by eVoloshchak** [comment]
@JmillsExpensify, gentle bump on https://github.com/Expensify/App/issues/26429#issuecomment-1720045360

**Comment by eVoloshchak** [comment]
Not overdue

**Comment by JmillsExpensify** [comment]
> @JmillsExpensify, is this a valid bug? I think closing a keyboard when you click another element is the default behavior, the same thing happens throughout the app. For instance, try to pin a conversation with the keyboard open
> 
>  screen-20230914-224450.mp4

Hmm yeah great point. I agree with you. Further, for `Save` I think the most common reason you tap save we actually dismiss the keyboard, because we're an expense management app and saving on a push to page edit has that behavior. I'm with @eVoloshchak and going to close this.
