### ISSUE TITLE
[$1000] Desktop -  User stucked on notification on the app icon even though there are no unread messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with your account A
3. Log in with account B on mobile
4. Send a message from mobile to Desktop

## Expected Result:
User able to read the message

## Actual Result:
User stucked on notification on the app icon even though there are no unread messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692904986751459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2cb438a23a5f8f3</li>
        <li>Upwork Job ID: 1701792143757332480</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by rafecolton** [comment]
Note that this has happened before and usually logging out and back in fixes it, but I have been stuck at one notification for weeks at least

**Comment by kevinksullivan** [comment]
FWIW, I've been at 99+ notifications for as long as I can remember, and I never got to the bottom of it.

![image](https://github.com/Expensify/App/assets/22508290/a54ecac8-86ab-439b-a486-945622b5c079)

I'm not sure if that is a proper reproduction, though. Taking to slack thread

**Comment by zanyrenney** [comment]
Real-life reports of this here: https://github.com/Expensify/Expensify/issues/315115

**Comment by kevinksullivan** [comment]
Moving forward per the linked GH and slack thread

**Comment by rafecolton** [comment]
It does not appear in focus, I have tried so many times

**Comment by rafecolton** [comment]
I don't think this is same as the issue you linked, what led you to conclude that it was?

**Comment by kevinksullivan** [comment]
This got `Help wanted` recently. We're still just waiting on proposals.

**Comment by rafecolton** [comment]
Just noting that the app is now stuck at three notifications for. So it has been mysteriously increasing. Still no unread messages that I can see, so no idea how to reproduce.

**Comment by kevinksullivan** [comment]
Awaiting proposals

**Comment by kevinksullivan** [comment]
doubling!

**Comment by shubham1206agra** [comment]
Can someone post a demo video here?
I am unable to repro this

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment]
Closing unless we can reproduce
