### ISSUE TITLE
No ability to add receipt when splitting a bill in the workspace chat

### ISSUE THREAD

**Issue by StefStavri** [Expensify/App#26423]
We designed Teachers Unite such that users would be able to add a receipt using the overflow menu when the confirm the split:

<img width="969" alt="image" src="https://github.com/Expensify/App/assets/22508185/41aa63d5-57b6-4134-abd7-ced632f74b87">

<img width="950" alt="image" src="https://github.com/Expensify/App/assets/22508185/a0276fa2-21ae-4962-a477-93638c970d68">

We missed this in the detailed design and currently members can only attach a receipt as a comment after the fact.

We need to add this back into the design asap.

**Comment by youssef-lr** [comment]
Closing in favor of https://github.com/Expensify/Expensify/issues/295248
