### ISSUE TITLE
[$500] Web - Money request - Workspace member is missing from the workspace when requesting money for workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2.  Settings > workspace
3. Select a workspace from the list if there is a workspace or create a new one
4. click member
5. click invite
7. Add members to invite
8. click next
9. Click invite
10. Click the + icon from LHN
11. click request money
12. Enter the amount
13. select the workspace from the list
14. Click the header from the IOU report
15. Observe the number of member

## Expected Result:
The total number of the members should be correct

## Actual Result:
The total number of the members is not correct

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3f5b962a-4072-4bbc-a2c8-8d1e67f791bc

https://github.com/Expensify/App/assets/93399543/d3bf6d36-b365-450c-ad5d-9fc6444c5583

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693028736979619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152b582c375b0403c</li>
        <li>Upwork Job ID: 1697720757871263744</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by AJV009** [comment]
This looks like quite a major bug!
I was checking it and found that not even the request for the money went through to the other end. (That's the whole point of the app right?)

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
Workspace member is missing from the workspace when requesting money for workspace.

### What is the cause of this issue?
If click header from IOU report, `ReportDetailsPage` is displayed, and in `ReportDetailsPage`, we display report's `participantAccountIDs`.
https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/ReportDetailsPage.js#L73
https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/ReportDetailsPage.js#L90-L101
But workspace expense chat report has only one participant id, so total number of the members is 1, and is different with total numbers of the workspace.
### What changes do you think we should make to solve the problem?
We can display total number of workspace members if report is workspace room.
* Add `withPolicy` HOC to `ReportDetailsPage` and `ReportParticipantsPage`.
* In `ReportDetailsPage`, if report is workspace room, we should display total number of workspace members.
```js
const isPolicyRoom = useMemo(() => ReportUtils.isAdminRoom(props.report) || ReportUtils.isAnnounceRoom(props.report) || ReportUtils.isPolicyExpenseChat(props.report), [props.report]);

const policyMembers = useMemo(() => _.keys(props.policyMembers[`${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${props.report.policyID}`]), [props.policyMembers, props.report.policyID]);
```
And change [this line](https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/ReportDetailsPage.js#L95) as below.
```js
    subtitle: isPolicyRoom ? policyMembers.length : participants.length,
```
* In `ReportParticipantsPage`, we should display workspace members.
We add `policyMembers` parameter to [`getAllParticipants`](https://github.com/Expensify/App/blob/ec95ab05e2c9d14ac91aa33946a5beeb39099e1f/src/pages/ReportParticipantsPage.js#L57), and pass `props.policyMembers`.
And in `getAllParticipants`, we check if the report is workspace room, and then add workspace members.
```js
const getAllParticipants = (report, personalDetails, translate, policyMembers = {}) => {
	...

    if (ReportUtils.isAdminRoom(report) || ReportUtils.isAnnounceRoom(report) || ReportUtils.isPolicyExpenseChat(report)) {
        participantAccountIDs = _.keys(policyMembers[`${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${report.policyID}`]);
    }

...

const participants = _.map(getAllParticipants(props.report, props.personalDetails, props.translate, props.policyMembers), (participant) => ({
	...
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by stephanieelliott** [comment]
Ah yeah, I agree with you @thesahindia. Thinking about it that way this behavior would be expected.
