### ISSUE TITLE
[$500]  IOU - Repeat group Split Bill does not merge into one in LHN offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Turn off the internet on your device
3. Click on FAB
4. Select Split Bill and complete it with any 3 participants
5. Click on FAB
6. Select Split Bill and complete it with the same participants from step 4

## Expected Result:
When you create an offline recurring Split Bill with the same members, it is merged with an existing group Split Bill in LHN

## Actual Result:
When you create an offline recurring Split Bill with the same members, it appears as a separate line in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5a6e2842-0cbe-44b8-9812-ca12d952de07

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e227db8e8f9898d</li>
        <li>Upwork Job ID: 1697671855363284992</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
I'm not able to reproduce.

**Comment by garrettmknight** [comment]
Not able to reproduce.
