### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500]  Report - Conversation history does not scroll down after sending a message and IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26432]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
Log in using a HIGH traffic account.
1. Open New Expensify app
2. Navigate to a chat that has a very long history
3. Scroll up the conversation history
4. Send any message or IOU

## Expected Result:
When you send a message or IOU in a conversation, the message history should scroll down without artifacts to the newly sent message or IOU

## Actual Result:
When sending a message or IOU in a conversation, the message history doesn't scroll down, and on Native apps the conversation history starts scrolling chaotically up to down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4b0dfdc9-e3cf-44df-bce4-2f212e230f02

**Expensify/Expensify Issue URL:**

**Issue reported by:** @rayane-djouah

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692633002201879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b9e851c8568700f</li>
        <li>Upwork Job ID: 1697745435700506624</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26624598</li>
<li>rayane-djouah | Contributor | 26624600</li>
<li>rayane-djouah | Reporter | 26624601</li>
</ul></li>
    </ul>
</details>

**Comment by mollfpr** [comment]
Thanks @rayane-djouah I'll do the review today!

**Comment by mollfpr** [comment]
Sorry for the delay @rayane-djouah 

Is there any reason why we remove the listener? Is there any related to the performance improve?

**Comment by mollfpr** [comment]
Is there any way without the listener?

**Comment by mollfpr** [comment]
@rayane-djouah I try your listener solution, but it's only sometimes working.


https://github.com/Expensify/App/assets/25520267/8709b8a9-1b2c-4c5c-b29f-4011bfd97a15

**Comment by mollfpr** [comment]
@rayane-djouah I'm okay with the proposal. To make sure, I am asking for [clarification](https://github.com/Expensify/App/pull/18637/files#r1318079323) in the PR.

**Comment by mollfpr** [comment]
@rayane-djouah Yeah, it seems we are okay to reintegrate the previous logic. Should we use `scrollToBottomAndMarkReportAsRead` instead to scroll to the bottom and mark the comment as read?

**Comment by mollfpr** [comment]
@rayane-djouah I'm testing your solution again on `scrollToBottomAndMarkReportAsRead` and `reportScrollManager.scrollToBottom`. My thoughts on `scrollToBottomAndMarkReportAsRead` seem to send an API `ReadNewestAction` when the current user sends a message, while I don't think it's necessary.

My other test is using `reportScrollManager.scrollToBottom`, to send a message while there's an unread message. There's an API call for `ReadNewestAction`, which I guess it's for the unread message.

So I think it's okay to use only `reportScrollManager.scrollToBottom`, what do you think?

**Comment by mollfpr** [comment]
Thanks @rayane-djouah 

Okay, it's indeed regression from https://github.com/Expensify/App/pull/18637 where it's refactoring the unmarked logic. We can reintegrate the report action listener to scroll to the bottom whenever the current user sends a message. Also, it's already [confirmed](https://github.com/Expensify/App/pull/18637/files/5d3edd4e881dd4fd14e64e9acc8c2df977352a25#r1318079323) that there's not performance impact from the listener usage.

So the [proposal](https://github.com/Expensify/App/issues/26432#issuecomment-1701965912) from @rayane-djouah looks good to me 👍

🎀 👀 🎀 C+ reviewed!

**Comment by sakluger** [comment]
Yes, I reviewed the PR timeline and this one qualifies for the efficiency bonus. I'm going through and writing up payments now.

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Bug reporter: @rayane-djouah $50 (paid via Upwork)
Contributor: @rayane-djouah $750 (paid via Upwork)
Contributor+: @mollfpr $750 (need to confirm preferred payment method)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~016b9e851c8568700f

**Comment by sakluger** [comment]
@mollfpr can you please confirm if you'd prefer to be paid via Upwork or NewDot? You've already accepted the Upwork contract, so if you'd like to be paid via NewDot I'd have to cancel that.

Also, can you please complete the BZ checklist? Thanks!

**Comment by mollfpr** [comment]
@sakluger I think from Upwork is okay, since we already have the contract.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18637

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:


https://github.com/Expensify/App/pull/18637/files#r1318079323

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think we can have a checklist to prevent this. The regression step should be good.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the app
2. Navigate to a chat that has a long history
3. Scroll up the conversation history
4. Send any message or IOU
5. Verify that the conversation history automatically scrolls down to the new message.
6. 👍 or 👎

**Comment by sakluger** [comment]
Thanks! Just sent the payment through Upwork @mollfpr.

Regression test steps look good, thanks!

**Comment by izarutskaya** [comment]
Issue reproducible on latest build - v1.3.96-0

Android / native

https://github.com/Expensify/App/assets/115492554/f3af869a-97f3-4af2-b4af-5162a6ca8cef

**Comment by thienlnam** [comment]
We're handling in here https://github.com/Expensify/App/issues/30947
