### ISSUE TITLE
Request money - Delay when showing money request amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1-First login to different accounts which two different users, one as user A and the other as user B
2-[user A] Start chat with user B
3-[user A] Click in plus sign and select Request money
4-[user A] Write a number, click Next button and Request button
5-[user B] Enter in chat with user A
6-[user B] Open the message of request amount

## Expected Result:
 That user B see the amount of request money in the moment.

## Actual Result:
The user B see by a moment the amount zero before the see amount correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bf3b58a9-7f5d-4914-a2e6-92bf46de808c

https://github.com/Expensify/App/assets/115492554/8c891d0c-7349-43cc-a5a2-a7f9a9e587ea

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Mauri-salazar

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692743125769409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
I think this is known and will be covered here - #26270

**Comment by sonialiap** [comment]
Closing in favor of https://github.com/Expensify/App/issues/26270
