### ISSUE TITLE
iOS - Security - Recovery code’s view height decreases when codes loaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings-> Click Security
2. Click Two factor authentication
3. See the box height in which codes are loaded

## Expected Result:
Height should stay same if codes are loading or loaded

## Actual Result:
Codes view Height decreased when codes are loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a82c46e0-df96-48bb-8bd0-b03d65deed25

https://github.com/Expensify/App/assets/115492554/34a50db7-f245-4478-8dd5-f8dcb2eea51d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692736199472949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Talha345** [comment]
Not sure if this should be treated as a bug as this is a very minor UI issue and is only noticeable if seen very carefully.Also happens on web too.

**Comment by zanyrenney** [comment]
Agree with @Talha345 incredibly minor polish UI. Closing.
