### ISSUE TITLE
Web - The Cursor displayed as enabled when hovering over the amount, description, merchant, or date for the paid request money.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26441]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click request money
4. Enter amount
5. Select Workspace from the list if there is no workspace create one before requesting a money
6. Confirm request money
7. Open the IOU report
8. Pay with "Pay Elsewhere"
9. Open edit request
10. Hover on the amount, description, merchant, and date
11. Observe the result

## Expected Result:
The Cursor should display as disabled when hovering over the amount, description, merchant, or date for the paid request money.

## Actual Result:
The Cursor displayed as enabled when hovering over the amount, description, merchant, or date for the paid request money.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3e2fc67d-6f0d-40c5-a1a2-8c4f9ee660bb

https://github.com/Expensify/App/assets/93399543/57c78167-6899-43b6-85f7-abbba0f051e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693516892936839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I don't think this is a blocker. There's no functionality impacted here.

**Comment by luacmartins** [comment]
IMO the way we have here is better, so I think we should do nothing, but I'll let @shawnborton chime in here.

**Comment by luacmartins** [comment]
Yea, I know we can. I just dislike the disabled cursor haha but then again, that's up to design

**Comment by mallenexpensify** [comment]
Bumping this to Daily per Carlo's comment
> I don't think this is a blocker. There's no functionality impacted here and it's a small cursor UI thing.

Also from Carlos
> IMO the way we have here is better, so I think we should do nothing, but I'll let @shawnborton chime in here.

I'm not sure I 100% grasp the bug. I'm assuming it's that the cursor shows like this
<img width="317" alt="image" src="https://github.com/Expensify/App/assets/22508304/a604bc26-abff-46a9-864e-e12370499087">

when it should (maybe) show like this
<img width="371" alt="image" src="https://github.com/Expensify/App/assets/22508304/254475a5-4d28-4f53-a34d-57a7b20ac7bb">

**Comment by mallenexpensify** [comment]
@kevinksullivan  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by shawnborton** [comment]
I'm a little lost on this one but cc'ing @mountiny here - I think having these rows display as disabled was a mistake, and thus we want to revert them to appear like read-only push-to-page rows (with no caret) and thus we don't need a disabled cursor.

**Comment by mountiny** [comment]
Yeah I dont understand this, we did have disabled and that was temporary and its fixed, now it looks normal, there is no hover effect, no change in cursor and no chevron so its clear you cannot clicked. This is intentional and not a bug

https://github.com/Expensify/App/assets/36083550/77f5524e-c1f2-4f28-a502-abeacec6f4f5

**Comment by mountiny** [comment]
> Should I create a separate issue for this?

@Krishna2323 yeah this issue as far as I can see from the title is not about tasks, thanks!
