### ISSUE TITLE
Chat- Delay in day translation then other translation for different day user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26475]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open report of user which has different day due to time difference
3. Open settings->preferences->language
4. Change the language and observe time stamp below for user, all the text gets translated but day text (eg: Friday, Saturday) takes few more seconds

## Expected Result:
App should translate all the text of date stamp together

## Actual Result:
App takes few seconds more to translate day text then other text in date stamp

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/74ec12ef-c3ff-4058-9146-4effa4b244d5

https://github.com/Expensify/App/assets/93399543/701c68c2-c62f-4c4b-80bd-56a42ba12d6c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693041344253879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This doesn't feel like something worth addressing. 

The time updating on a per-second interval is reasonable, and the change here is imperceptible. I'm going to close this out.
