### ISSUE TITLE
 [Distance] Distance - 'Use current location' does not invoke error message when clicked offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25990
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Go offline
5. Go to Start
5. Click Use current location

## Expected Result:
The error message 'We were unable to find your location, please try again or enter an address manually' shows up

## Actual Result:
No error message shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c6c473f1-a36f-419d-9f89-d545ad3ab87c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
Looking!

**Comment by pecanoro** [comment]
Since the same PR caused a few blockers we are discussing internally if we should revert it and polish it before deploying it again.

**Comment by pecanoro** [comment]
PR reverted [here](https://github.com/Expensify/App/pull/26493), so I am removing the deploy blocker label and I will let @huzaifa-99 handle it in the new PR.

**Comment by hayata-suenaga** [comment]
@huzaifa-99 when you create the new PR, please link this issue to your PR so that this issue can be closed when your fix is deployed

**Comment by Christinadobrzyn** [comment]
Hey @huzaifa-99 this [issue](https://github.com/Expensify/App/issues/26869) seems similar although it involves typing an address instead of "current location" but do you think the fix will be the same?

**Comment by hayata-suenaga** [comment]
@Christinadobrzyn the issue you linked is different from this one 🙇

**Comment by hayata-suenaga** [comment]
@huzaifa-99 can you confirm that this issue was fixed after your second PR was deployed?

**Comment by hayata-suenaga** [comment]
this issue was reported by applause and doesn't involve payment to any party. Closing this
