### ISSUE TITLE
Settings - Redirecting to screens with animation takes pause before redirecting to screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26476]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click Preferences or Workspaces (screens with animations on top)
3. Try clicking other options like Profile or Security it redirects instantly

## Expected Result:
User should be redirected instantly

## Actual Result:
Takes a little pause after clicking Preferences/Workspaces

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b9aa35da-9e2f-4daa-b443-c4a707b479b4

https://github.com/Expensify/App/assets/115492554/3088dcfe-0b65-4dfb-8f2e-2788a0c5e72b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692735915055619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
This is reproducible but barely noticeable and doesn't hurt user experience in my opinion. I'd lean to closing but curious for a quick buddy check cc @vitHoracek

**Comment by mountiny** [comment]
Yeah I agree, its probably the animation in the page, while this is true its slower, I think this is just handled under perfomance improvements we are working on (any page should be opening instantly) so We can close this one
