### ISSUE TITLE
Request money - Map box not zooming to current location

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26485]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25990
## Action Performed:
Prerequisite: Distance request beta must be enabled
1. Click on Fab -> Request Money -> Press Distance Tab
2. Click on any waypoint
3. On the waypoint editor page, click on the "Use current location" button
4. If location permission is enabled, verify that the address field changes text to "Your Location" and clears any errors on that page and navigates you back to distance page. There you will see the waypoint edited with text 'Your Location'

## Expected Result:
Mapbox zooming into your location

## Actual Result:
Mapbox not zooming to current location and at default location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2600d768-4556-4d4f-b2c0-b60c5ca81b54

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Sounds great. I'll keep an eye on this one in the meantime.

**Comment by hayata-suenaga** [comment]
this might have been solved [by this PR](https://github.com/Expensify/App/pull/26500)

@huzaifa-99 when you create the PR, can you make sure that you test this behavior? 🙇

**Comment by hayata-suenaga** [comment]
> Yes, this seems to have solved it. I still tested it in the PR https://github.com/Expensify/App/pull/26546

nice closing this issue now
