### ISSUE TITLE
mWeb - Workspaces - Search bar in invite members not focused after selecting an account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. login to staging new dot
2. Go to workspaces and  open members
3. Click on invite and search for a user
4. Select one user from search list
5. Observe that the search bar isnt focused after selecting the account

## Expected Result:
Search bar should be focused

## Actual Result:
Search bar is not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5c943e6d-22c1-4e54-a56a-75b47571a62b

https://github.com/Expensify/App/assets/115492554/2c0d1f4e-30c9-48ef-81e3-a767c0087307

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692765481977729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
This is expected behaviour (got a buddy check from @jliexpensify who agrees). If you think this should change, please suggest this as a feature request.
