### ISSUE TITLE
 Distance - Unable to use current location once the site location access is denied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25990
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Go to Start > Use current location
4. Allow location permission
5. Turn off location permission
5. Refresh the page
6. Click Use current location
7. Reset site permission
8. Refresh the page
9. Click Use current location
10. Click Allow

## Expected Result:
Every time location access on browser is allowed, the app is able to use current location feature

## Actual Result:
Once the location access is denied on the mobile browser, the app is unable to use current location feature when the location access is re-enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f0744e8c-9562-4766-b453-8c72639c1b17

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
I was looking into another deploy blocker linked to this, but I encountered this problem as well. The current location is super buggy lol It also does not work if you delete the current address and try to use the current location.

**Comment by pecanoro** [comment]
Since the original PR was reverted, I am removing the deploy blocker label!

**Comment by hayata-suenaga** [comment]
thank you for the detailed explanations

If this is the browser behavior, then there is nothing we can do. Let's close this issue

**Comment by hayata-suenaga** [comment]
That's a good idea

@huzaifa-99 this is a low priority task, so you can answer this when you have time. I just wanted to confirm the solution for this

- After user denies the permission if then they want to grant location permission again, what should they do?

### Memo video for myself

https://github.com/Expensify/App/assets/98560306/5b6852de-ee27-4bda-bd89-2c5c645ac6cb
