### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] [Android] User isn't prompted for Camera permission via the native Modal

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#26499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Ensure the Camera permission is denied
2) Tap FAB > Request money > Scan
3) Click the 'Give Permission' button

## Expected Result:
- We should show the native Android request permission modal
- Given that the user has tapped give permission, I don't think an initial 'We are going to ask you for permission' modal is required (it would in other cases in order to prevent the OS from blocking future permission requests)
- The solution should work exactly the same as it does for native Android/iOS apps

## Actual Result:
I am deep linked directly to the top level generic app settings page, and must manually tap 'Permissions > Camera'

## Workaround:
I must manually tap 'Permissions > Camera'. Some users might not know how to do this.

https://github.com/Expensify/App/assets/10736861/8e8c73bf-5d7b-4ca9-8082-416c4e207943

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61-1
**Reproducible in staging?:** yes
**Reproducible in production?:** yes (once deployed)
**Issue reported by:** @Julesssss 
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5f4967e2e242138</li>
        <li>Upwork Job ID: 1698645305652506624</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26488566</li>
<li>ishpaul777 | Contributor | 26488567</li>
<li>zoontek | Contributor | 26980722</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment]
This is more of a feature improvement than a bug

**Comment by ishpaul777** [comment]
@Julesssss what if we directly request permission with native pop up similar to how to request while launching camera?

**Comment by akinwale** [comment]
@Julesssss It's not possible to deep-link directly to the Camera settings page. The best option is to open the App settings page which is what is currently happening.

Also, the current implementation seems weird. I would assume that the app should try to request for the camera permission at least once (which shows a dialog to grant or deny the request), before making the user have to navigate to the device app settings.

**Comment by sakluger** [comment]
@Julesssss do you need me to triage this issue or anything, or are you going to mostly manage the issue and I can just handle any contributor payments that come up?

**Comment by Julesssss** [comment]
> It's not possible to deep-link directly to the Camera settings page. 

Ah, right. We can deep link directly to the location permission so I assumed it worked for all permissions. Oh well.

> I would assume that the app should try to request for the camera permission at least once (which shows a dialog to grant or deny the request), before making the user have to navigate to the device app settings.

100% agree with this. 

@sakluger I'll update the description and will manage it.

**Comment by ishpaul777** [comment]
## Proposal
### Problem
User isn't prompted for Camera permission via the native Modal

### Root cause
N/a , new feature/improvement

## Changes

Pseudo code
```jsx
const askForPermissions = () => {
            Camera.requestCameraPermission().then((permissionStatus) => {
                // if denied set show native alert modal 
                // alse setPermissionStatus - authorized
            });
  };

```

**Comment by Julesssss** [comment]
@ishpaul777 correct me if I'm wrong, but I think only the second part of your solution is necessary because we are already checking for permission and showing the 'Grant Permission' button. 

Why would we want to show the native modal if they deny the permission? (`showPermissionsAlert `)

**Comment by Julesssss** [comment]
Ahm, so that is NOT a native modal. Cool

**Comment by ishpaul777** [comment]
### Proposal 
[Updated](https://github.com/Expensify/App/issues/26499#issuecomment-1705042129)

**Comment by Julesssss** [comment]
I still think that's not necessary in this case though. By tapping the button we can assume they intend to grant the permission. And if they then choose to deny it, we don't need to warn them. It's pretty obvious due to the illustration and 'Grant Permission' button that they won't be able to do anything until granted.

**Comment by ishpaul777** [comment]
@Julesssss Okay I updated the proposal to ask for permission everytime 'Grant Permission' button is clicked

**Comment by Julesssss** [comment]
It's looking good, but I want to be sure there wasn't a reason for calling `Linking.openSettings();`. IIRC the library has a limitation where it can't tell the difference between an Android `denied` and `not-yet-requested` state... 

But I think the suggested fix is correct.

**Comment by Julesssss** [comment]
The change should apply to both iOS and Android. I think it will, because currently only Android is hitting the `not-determined` state.

**Comment by Julesssss** [comment]
@AndrewGable would you mind taking a look at this proposal please. I recall we talked about the permission library states not being equal for Android/iOS, and perhaps there was a reason we chose not to prompt the user for permission natively on Android?

**Comment by Julesssss** [comment]
One final thought: 

Just to be safe maybe instead of removing the [condition](https://github.com/Expensify/App/blob/4ba983c120eaef779e887fc2e4210aed127f4874/src/pages/iou/ReceiptSelector/index.native.js#L150) we switch it to `if (permissions != 'approved') {`?

**Comment by ishpaul777** [comment]
Are we waiting for Andrew's 🟢 on this, https://github.com/Expensify/App/issues/26499#issuecomment-1705118261

**Comment by Julesssss** [comment]
Pretty sure he's stuck at Burning Man currently 😅 

Given that this feature has high visibility for our conferences this week lets move forward. I'll make sure to test the Android/iOS permission cases thoroughly.

**Comment by ishpaul777** [comment]
PR will be up in few hours. 🚀

**Comment by ishpaul777** [comment]
@Julesssss 
While implementing the changes and testing I realized, Android allows app to ask for permission maximum 2 times if denied both time it blocks the request and IOS allows only first time then blocks the request (no modal shown) thats why we have the condition for not-determined, 
ref here - https://www.npmjs.com/package/react-native-permissions#understanding-permission-flow

**Comment by akinwale** [comment]
> @Julesssss While implementing the changes and testing I realized, Android allows app to ask for permission maximum 2 times if denied both time it blocks the request and IOS allows only first time then blocks the request (no modal shown) thats why we have the condition for not-determined, ref here - https://www.npmjs.com/package/react-native-permissions#understanding-permission-flow

Yeah, that's the reason for [https://github.com/Expensify/App/issues/26499#issuecomment-1703204972](my comment). I was certain that was the expected behaviour, but I was unable to find the official documentation about it at the time.

**Comment by Julesssss** [comment]
> While implementing the changes and testing I realized, Android allows app to ask for permission maximum 2 times if denied both time it blocks the request and IOS allows only first time then blocks the request 

I'm aware that the OS will block permission prompts after multiple rejections, but in this case, it's fine as the user is prewarned by the button label. It would be different if we automatically showed the permission prompt when the page is opened. Showing two prompts after the button is pressed is overkill. 

This still isn't expected behavior though, as we should show the native Android Camera permission prompt.

**Comment by Julesssss** [comment]
I recall talking with the library author, perhaps we'll need a library change in order to support the flow, but it should work like this:
- iOS: Button pressed > native permission prompt displayed
- Android: Button pressed > native permission prompt displayed
- If the permission is **denied** then we should link them to the App settings page as a fallback

**Comment by ishpaul777** [comment]
We can use "react-native-permissions"

iOS: Button pressed > native permission prompt displayed
Android: Button pressed > native permission prompt displayed
If the permission is denied (by OS) then we should link them to the App settings page as a fallback

```
 const permissionType = Platform.select({
            ios: PERMISSIONS.IOS.CAMERA,
            android: PERMISSIONS.ANDROID.CAMERA,
        });
        request(permissionType)
            .then((permission) => {
                if (permission === RESULTS.BLOCKED) {
                    Linking.openSettings();
                } else if (permission === RESULTS.GRANTED) {
                    setPermissions(CONST.RECEIPT.PERMISSION_AUTHORIZED);
                } else if (permission === RESULTS.DENIED) {
                    setPermissions(CONST.RECEIPT.PERMISSION_DENIED);
                }
            })
```

**Comment by ishpaul777** [comment]
@Julesssss can you take a look at PR, review changes

**Comment by Julesssss** [comment]
> component mounted (Permission not given) ask for permission

I don't believe weneed to do this. Only when the button is pressed do we prompt the user.

**Comment by ishpaul777** [comment]
@Julesssss permission blocked can be detected only when requesting permission ( I tried using the check method from the "react-native-permissions" library, it returns denied even though the permission is blocked asking for permission on mount is the only way we could figure out if request is blocked)

**Comment by Julesssss** [comment]
Okay, we should try to fix this upstream in the library, but maybe that can be done separately. 

So the solution would be like this: 

**Regular flow**
- iOS: Button pressed > native permission prompt displayed
- Android: Button pressed > native permission prompt displayed

**Permission blocked**
- iOS: Button pressed > take to app settings page
- Android: Button pressed > take to app settings page

**Comment by ishpaul777** [comment]
Until a upstream fix the flow is fine? https://github.com/Expensify/App/issues/26499#issuecomment-1705571378

**Comment by Julesssss** [comment]
Why do we need to request permission on Component mount? We don't want the prompt to show automatically when switching to the scan page.

**Comment by ishpaul777** [comment]
100% agree with what you are saying, there are 2 ways we can implement `askForPermissions`

1. first request everytime button is clicked if blocked open settings, issue with this if user denies request multiple times and os blocks on denial, this open settings

```jsx
 const askForPermissions = () => {
        request(permissionType).then((permission) => {
            if (permission === RESULTS.BLOCKED) {
                Linking.openSettings()
                setPermissions(CONST.RECEIPT.PERMISSION_AUTHORIZED)
            } else if (permission === RESULTS.GRANTED) {
                setPermissions(CONST.RECEIPT.PERMISSION_AUTHORIZED);
            } else if (permission === RESULTS.DENIED) {
                setPermissions(CONST.RECEIPT.PERMISSION_DENIED);
            }
        });
    };
 ```
2. first check if blocked if yes then open settings else request, issue with that when component mounts, app is not aware if permission is blocked, so button does nothing on first click, android never returns "Blocked" when check permission we have to request to get status blocked so here.

```jsx
 const askForPermissions = () => {
       if(permissisons === CONST.RECEIPT.PERMISSION_BLOCKED {
         Linking.openSettings()
         return 
       }
        request(permissionType).then((permission) => {
            if (permission === RESULTS.BLOCKED) {
                setPermissions(CONST.RECEIPT.PERMISSION_BLOCKED)
            } else if (permission === RESULTS.GRANTED) {
                setPermissions(CONST.RECEIPT.PERMISSION_AUTHORIZED);
            } else if (permission === RESULTS.DENIED) {
                setPermissions(CONST.RECEIPT.PERMISSION_DENIED);
            }
        });
    };
 ```
 
let me know, if I missed something here.

**Comment by Julesssss** [comment]
> 1) ...issue with this if user denies request multiple times and os blocks on denial, this open settings

So the only downside here is that the modal can be prevented from being shown after multiple denials? The OS blocking the modal is how it works natively, so I don't view that as a problem.  

> 2)  ...app is not aware if permission is blocked, so button does nothing on first click

This seems too broken to use.

> 3) ...In my humble Opinion, The best and consistent solution would be to Alert user

When do you suggest we would display this? When the button is pressed, or only after the native permission modal is shown/blocked?

**Comment by ishpaul777** [comment]
For changes 1. The settings will open even when the user clicks "Dont Allow".
Permission flow on android would work like this

ask permission -> not granted -> requestable for next time -> No -> status - Blocked -> Open settings
                                                                           |
                                                                         yes -> status- denies - do nothing
                                                                         
> When do you suggest we would display this? When the button is pressed, or only after the native permission modal is shown/blocked?
when request blocked (Native alert is not shown) -> show Alert 
when user clicks "Don't Allow" and permission request is blocked for next time -> Show alert.

**Comment by ishpaul777** [comment]
we need a solution for either of below:
1. return status  "Blocked" when check for permission (I dont think thats possible docs clearly states that - )
2. if denied, request blocked for next time do not return blocked, return Denied

**Comment by ishpaul777** [comment]
what would be next steps for me ? @Julesssss

**Comment by ishpaul777** [comment]
@Julesssss looks like a PR with the similar changes to 1. in https://github.com/Expensify/App/issues/26499#issuecomment-1706390033 deployed to prod causing the issue.
> button does nothing on first click

**Comment by zoontek** [comment]
This solution fixes the current logic: https://github.com/Expensify/App/issues/27442#issuecomment-1740878801

A few notes (some have been mentioned already):
- You cannot open the permission settings screen directly, only the app settings. But you can add an alert before opening it to explain to the user what he will have to do if you want.
- On Android >= 11, the `Never ask again` as indeed been replaced with the fact that you can ask twice before it's `blocked`, and you have to open settings.
- You can also pass a `rationale` (could be an `Alert`, or a custom implementation since `react-native-permissions` >= `3.9.0`) to the `request()` fn: https://github.com/zoontek/react-native-permissions#request. It will be shown on second permission request attempt (before the `blocked` switch, if the user deny a second time)

**Comment by Julesssss** [comment]
> we can add the "before redirect to settings" alert + a rationale alert if you want. This is indeed more a feature improvement than a bug fix.

Lets stick with the fix for now, and see how we feel about that further improvement during testing 👍

**Comment by Julesssss** [comment]
@ntdiary please take a look at the linked proposal above.

**Comment by Julesssss** [comment]
> Because it's actually possible to open the native Modal now

Oh did I miss this? I thought that we're still not currently prompting users and that the linked proposal will fix both issues. But please correct me if that isn't correct.

**Comment by zoontek** [comment]
@Julesssss The proposal indeed fixes both issues, as it will show the native dialog when it can perform a request, redirect to settings when it cannot.

**Comment by Julesssss** [comment]
Ah that's what I assumed. But [this message](https://github.com/Expensify/App/issues/26499#issuecomment-1742812879) makes it sound like the issue is no longer occuring on `main`. 

Anyway, happy to assign both of these issues and rewards to you and your proposal 👍

**Comment by Julesssss** [comment]
Also happy to include a 2nd modal as part of the proposal fix.

**Comment by zoontek** [comment]
@Julesssss @ntdiary said that #27442 stills need to be addressed ([`request` still might not be called on button press on `main`](https://github.com/Expensify/App/blob/main/src/pages/iou/ReceiptSelector/index.native.js#L154) - so this issue still exists)

Sure, I will add the extra alert before redirecting the user in the same PR 🙂

**Comment by Julesssss** [comment]
This is the part that sounded unviable: 

> For changes 1. The settings will open even when the user clicks "Dont Allow".
Permission flow on android would work like this

Reading through it again, perhaps you meant that the custom modal will look like the official settings?

**Comment by Julesssss** [comment]
That's fair, but as you pointed out we still needed a solution to [this](https://github.com/Expensify/App/issues/26499#issuecomment-1706808549).

In any case, I believe it's safe to say that hiring the library author is the best choice here. Also their proposal solves both issues.

**Comment by Julesssss** [comment]
Can be paid out today

**Comment by sakluger** [comment]
Looks like the offer to @ntdiary somehow expired. I sent a new offer, can you please accept?

@zoontek it also looks like you haven't accepted our offer for this job yet. Could you please accept and let me know so I can complete payment?

Thanks!

**Comment by zoontek** [comment]
@sakluger Sorry, I accepted it.

**Comment by sakluger** [comment]
Thanks @zoontek! I completed your payment.

**Comment by sakluger** [comment]
All done, thanks everyone!
