### ISSUE TITLE
Distance expense- Drag and reposition not working for way points

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: Distance request beta must be enabled
1. Click on Fab -> Request Money -> Press Distance Tab
2. Add a start and finish point
3. Click Add point and add a address
4. Click and drag the drawer menu

## Expected Result:
Able to drag and reposition the way point , start or finish location

## Actual Result:
Drag and reposition non functional

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/63c59fc3-e777-48b6-9913-b1281bcfd053

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
We have [merged a PR](https://github.com/Expensify/App/pull/26439) to remove these handles for now.
