### ISSUE TITLE
[HOLD for payment 2023-10-18] [Wave 6: Categories] Low: Shouldn't be able to select categories on split bill that doesn't involve workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the + icon in announce room
2. Select Split Bill
3. Click on "Show More"
4. Click on "Category"
5. Select any category from the dropdown menu

## Expected Result:
Selected category should be displayed after making selection

## Actual Result:
When user click on any category there is no selection made

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2fb29e5b-428d-419c-bc17-6368e0cf2092

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
How do we create categories in workspace?

**Comment by muttmuure** [comment]
Not sure I can reproduce this without categories being live for Split bills, so I asked in the Wave 6 channel

**Comment by puneetlath** [comment]
The solution here is that we should only show the Category selector if one of the people you are splitting the bill with is the workspace. Even if the split is happening in the workspace room, we shouldn't show the category selector unless the workspace itself is involved in the split.

**Comment by puneetlath** [comment]
Dropping to weekly since this is a beta feature, so it shouldn't affect anyone. We'll handle it as a wave6 polish item. 

@rezkiy37 perhaps you want to take it when you're done with the editing categories feature.

**Comment by rezkiy37** [comment]
Hello, I am Mykhailo from Callstack. I would like to work on this issue.

**Comment by rezkiy37** [comment]
Looks like the split bill flow is a little bit broken down. I am on the latest `main` and once I confirm with any kind of participants, the app has an infinity recursion. So, do we have an issue where it is already reported?

https://github.com/Expensify/App/assets/57314631/36b5ec51-bb47-47c5-8708-8acb38a84902

**Comment by puneetlath** [comment]
Huh, interesting. Does it work if you just choose two people and not a workspace as one of them?

**Comment by puneetlath** [comment]
Huh, interesting. Does it work if you just choose two people and not a workspace as one of them?

**Comment by rezkiy37** [comment]
@puneetlath, it does not work for me.

https://github.com/Expensify/App/assets/57314631/1083c871-b458-426d-95da-8bb525dbceb6

**Comment by rezkiy37** [comment]
They just fixed the loop bug - https://github.com/Expensify/App/pull/27793.

**Comment by puneetlath** [comment]
Oh nice. Good find.

**Comment by rezkiy37** [comment]
Hi, @puneetlath!
Can I ask you: is it expected that I cannot split a bill with multiple participants, when at least one workspace selected?

https://github.com/Expensify/App/assets/57314631/ca721870-8f59-4b5e-a553-d9417fc584f8

**Comment by rezkiy37** [comment]
Looks like it is expected. So, we are showing categories when selecting a workspace.

<img width="1046" alt="Screenshot 2023-09-20 at 12 39 34" src="https://github.com/Expensify/App/assets/57314631/28103799-222b-4d16-9aa1-3f45ebc017fd">

**Comment by puneetlath** [comment]
Looks like yes you're right that is on purpose.

**Comment by rezkiy37** [comment]
I am preparing a PR.

**Comment by rezkiy37** [comment]
The PR is under internal review.

**Comment by rezkiy37** [comment]
Melvin, the PR is actively being reviewed internally now.

**Comment by puneetlath** [comment]
Thanks for letting me know. Please fill out the checklist and I'll pay on Wednesday 🙂

**Comment by puneetlath** [comment]
Looks like only @hoangzinh requires payment here. Sent you an offer @hoangzinh: https://www.upwork.com/nx/wm/offer/27368549

And the back-end still needs to be updated.

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by puneetlath** [comment]
Whoops, sorry for the delay @hoangzinh. Paid!
