### ISSUE TITLE
Web - Next button while creating split bill is not at bottom

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start split bill workflow
2. After selecting members

## Expected Result:
Split bill button should be at bottom

## Actual Result:
it's not at bottom

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ea4c5d6e-1b9e-4f45-a479-5a239fe0b314

![image](https://github.com/Expensify/App/assets/93399543/610ab6f0-eb97-4a02-ad7c-b9534b079d24)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693591772083449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
Regression from #26179
### What changes do you think we should make in order to solve the problem?
We should make this flex grow
```js
<ScrollView contentContainerStyle={[styles.flexGrow1]}>
                        <ScrollView
                            horizontal
                            contentContainerStyle={[styles.flex1, styles.flexColumn]}
                        >
```

### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment]
Duplicate https://github.com/Expensify/App/issues/26418

**Comment by kbecciv** [comment]
Closing because of duplicate
