### ISSUE TITLE
Distance requests mainline flow tests

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26513]
## Creating a Distance Request

1. Global Create > Request Money
2. Select Distance option
3. When location permission is not already granted, 
4. Verify the map view is centered on San Francisco
5. Verify the user is prompted for location permissions
6. When location permission is granted, verify the map view is centered on the user’s current location
7. Select either Start or Finish waypoints to edit them
8. Verify autocomplete suggestions appear for each address
9. Enter both start and finish locations
10. Verify the map updates to display a route between the two locations
11. Use the add stop button to add another waypoint
12. Verify the map updates to display the route between all 3 locations, finishing at the newly added stop
13. Drag and drop the middle waypoint to the end to make it the finish location
14. Verify the map updates to display a new route with the new destination order
15. Select Next
16. Enter a workspace name and select an option from the list
17.  On the summary page
18.  Verify an image of the selected route displays at the top
19. Verify the amount is pre-filled and the date is set to today
20. Verify there are items to enter the description and date
21. Verify the submit button has “Request $X” text
22. Submit the request and verify it’s created successfully

## Viewing a Distance Request

1. View the workspace chat for the request
2. Verify a message from you displays with a preview of the distance request
3. Verify the request preview displays
4. An image of the selected route
5. The amount
6. The distance of the route and the distance rate
7. Login as the admin for the workspace
8. View the workspace chat
9. Verify there’s a message for the distance request and a button to pay it below
10. Select the request to view its details
11. Verify a report page displays with the 
- route image
- Amount
- Description
- Date
- Distance

## Creating an Impossible Distance Request (less important)

1. Global Create > Request Money
2. Select Distance option
3. Accept permissions for location
4. Enter a start location in San Diego, California and a finish location in Honolulu, Hawaii
5. Verify an error message displays below the map saying there is no route and instructing you to edit the waypoints

## Creating a Distance Request with Identical Start & Finish

1. Global Create > Request Money
2. Select Distance option
3. Accept permissions for location
4. Enter a start location
5. Enter the same location as the finish
6. Verify an error message displays below the map saying there is no route and instructing you to edit the waypoints

-------------------------
## Unsupported features (for now)
- Editing requests after creation
- Map automatically centering on user location

**Comment by trjExpensify** [comment]
Oh, @neil-marcellini, any reason we have this open? I created an issue for Applause last week, so you can probably just close it.
