### ISSUE TITLE
Inconsistent Avatar position in IOU report and IOU message when requesting money in a workspace chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to expensify new dot
2. Make sure there is a work space created after the last deployment if there isnt create one
3. Click on + icon and select request money
4. Enter amount and click next
5. Observe that there is a chat option listed as the workspaces name with avatars of the user and the workspace
6. Click on the workspace and click on request money
7. Observe that the avatars in the IOU message and the avatars in the IOU report message are reversed

## Expected Result: 
Avatars in message should be consistent
## Actual Result: 
Avatars are reversed'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8c187e37-4e14-48cd-acc5-a9ac94e17286

https://github.com/Expensify/App/assets/43996225/33500a9a-d5b8-4856-818e-313de0d1b97d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692945680266389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Not a bug. The requester is bigger when expanding the report to the workspace.
