### ISSUE TITLE
Chat - Blank page displayed when open non-existing chat link in web and click "Allow" btn

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Sign in with account A
3. Open desktop app
4. Sign in with account B
5. Paste the link with non-existing conversation in a new tab in web e.g. https://staging.new.expensify.com/r/1234
6. Click the "Allow" button to open the desktop app

## Expected Result:
The desktop app should opens and "you don't have access" message should be displayed

## Actual Result:
Blank page displayed
The issue is also reproducible with existing chat link (Account C), when signed in to a different accounts (A and B)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

 **Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7085dc2f-3722-4a43-a485-bd3173b05db3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
meh - I think this is really unexpected behavior going to close to keep our engineering resources focused

**Comment by chiragsalian** [comment]
> I think this is really unexpected behavior

Sorry, can you elaborate? If this bug is real it blocks users from using NewExpensify on the new phones.
I think people haven't caught it yet since not many people have the iPhone 15 but it might be something worth solving before more people get their hands on the new phones.
