### ISSUE TITLE
[Awaiting Miro payment] [HOLD for payment 2023-09-13] [Distance] Report preview does not display receipt image after creating a distance request

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#26533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log into NewDot as a workspace member
2. Global Create > Distance
3. Enter any address for start and finish
4. Submit the request to the workspace expense chat

## Expected Result:

- The policy expense plate displays with a report preview for the expense
- The report preview uses a placeholder receipt image while offline
- When going online, the report preview updates with the receipt image dynamically

## Actual Result:

The report preview displays with no receipt image for the distance request and it does not update until the report is opened

https://github.com/Expensify/App/assets/6833644/b7a2ec58-e03c-4acd-88fd-5243430c03c9

## Workaround:

Opening the report will load the receipt image

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
Came from this [slack discussion](https://expensify.slack.com/archives/C05DWUDHVK7/p1693593761395679?thread_ts=1693587579.658459&cid=C05DWUDHVK7).

**Comment by hayata-suenaga** [comment]
[per this Slack convo](https://expensify.slack.com/archives/C05DWUDHVK7/p1693673401061829), I gonna change the priority of the issue from LOW to HIGH

**Comment by trjExpensify** [comment]
I'll take over BZ on this from @puneetlath

**Comment by trjExpensify** [comment]
👋 So I think we just need to pay @0xmiroslav $500 for the internal PR review, correct?

**Comment by trjExpensify** [comment]
Cool, popped it on `weekly` and made a note in the title.

**Comment by trjExpensify** [comment]
@0xmiroslav done here yet?

**Comment by trjExpensify** [comment]
Okay, sounds good!
