### ISSUE TITLE
Fix second line in LHN once the report is paid. 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26542]
At the moment, if a report is `processing` and needs to be paid, the member and admin see this in the LHN for a workspace chat. 

<img width="1771" alt="Screenshot 2023-09-01 at 17 35 44" src="https://github.com/Expensify/App/assets/1127863/660339e7-8932-47e1-afe1-115d6a674ffd">

Most important is noticing how the second line of the workspace chat (or the same line in #focus mode; this screenshot) correctly shows the report name, e.g. `Expensify Contributors owes $10,000`. 

When a report move from `processing` to `reimbursed`, we incorrectly show the system message from within the report, instead of showing the updated report name, e.g. `Expensify Contributors paid $10,000`. 

<img width="1370" alt="Screenshot 2023-09-01 at 17 33 10" src="https://github.com/Expensify/App/assets/1127863/d79d50a5-7ddd-4154-9c5d-8705fe8bbe14">

**Comment by mountiny** [comment]
will look once I have some time mid deploys

**Comment by mountiny** [comment]
Closing in favour of https://github.com/Expensify/App/issues/26669
