### ISSUE TITLE
Web - Offline - Inconsistency when deleting request money and deleting message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26552]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to chat with any user
2. Create a request money
3. Hover on request money and reply in thread => send any message on thread
4. Click header to go the chat report
5. Send any message
6. Hover on message and reply in thread => Send message in thread
8. Click header to go chat report
9. Turn off network
10. Hover and delete 2 requests money and 2 messages created above
11. Observe that the request money has a deleted thread showing [Deleted request] which is different from the deleted message

## Expected Result:
When offline request money is deleted, it will the same with delete message has a thread.

## Actual Result:
When offline request money is deleted show [Deleted request] with request money has thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Screen Recording 2023-08-28 at 12.36.29.mov…

https://github.com/Expensify/App/assets/93399543/286ab801-8adc-41d3-b216-4a219737c4bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693200773538839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f57ac1bfcdb61c6</li>
        <li>Upwork Job ID: 1708152442920947712</li>
        <li>Last Price Increase: 2023-09-30</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
I think this is technically a feature request but I also don't agree that this needs to be fixed right now
