### ISSUE TITLE
[$500] Public Room - "Workspace chat is no longer active" displayed, unable to join public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on the link to join public room in test rail-https://staging.new.expensify.com/r/2006823258165289

## Expected Result:
The user must see options to join public room

## Actual Result:
The user sees message " Workspace chat is no longer active" and unable to join public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8a8ef6f3-fb49-402b-933c-3f0b54b97d8d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause- Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a36ef87a016e058d</li>
        <li>Upwork Job ID: 1708152439968350208</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment]
Not sure why no one from bugzero team was assigned here. Reapplying label

**Comment by MonilBhavsar** [comment]
The policy DD2E20F210C32F3A is not archived

**Comment by MonilBhavsar** [comment]
Do you think this can be handled externally?

**Comment by MonilBhavsar** [comment]
I had a look at the code and I think the default message should be displayed in this case.

**Comment by MonilBhavsar** [comment]
Waiting for proposals

**Comment by MonilBhavsar** [comment]
Same ^^

**Comment by MonilBhavsar** [comment]
Melvin, I updated above 😕

**Comment by MonilBhavsar** [comment]
In this case for Applause's room, only room is archived and not the policy. 
I wonder how we ended in this state as rhere's no way to archive a user created room. @muttmuure thoughts on this

**Comment by MonilBhavsar** [comment]
@lanitochka17 are you able to reproduce this issue using different room other than https://staging.new.expensify.com/r/2006823258165289
Also, wondering how were you able to archive the room?

---

And, @muttmuure thoughts on this https://github.com/Expensify/App/issues/26555#issuecomment-1757599464 please?

**Comment by MonilBhavsar** [comment]
I can't seem to change the visibility of the room or archive it 🤔

**Comment by muttmuure** [comment]
Is the problem that the room is behaving as if it is archived, but it actually is not?

**Comment by MonilBhavsar** [comment]
Yes, the room applause shared in Github description is archived. I can't seem to find a way to archive a room or get the room into that state. Do you have any idea?

**Comment by MonilBhavsar** [comment]
Flagged over weekend

**Comment by MonilBhavsar** [comment]
Have asked Japser as I think he recently worked with user created rooms

**Comment by muttmuure** [comment]
Sounds good to me

**Comment by MonilBhavsar** [comment]
Let's close this. Feel free to reopen if issue is seen for another room
