### ISSUE TITLE
 LHN - Only one unread DM displayed in LHN when requested split bill with two attendees

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be signed in
1. Open staging.new.expensify.com
2. Make a split bill with two attendees
3. Navigate back to LHN
4. Wait about 5-10 sec
5. Refresh the page (tap on browser's refresh button)
6. Wait about 5-10 sec

## Expected Result:
Two unread DM 1:1 between you and each attendee should be displayed

## Actual Result:
Only one unread DM displayed in LHN when requested split bill with two attendees

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fbb21126-216b-4784-a221-068ef47829c2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Will review today
