### ISSUE TITLE
Web - The Assign Task feature does not properly handle HTML character codes in the title field.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Task".
2. Enter a title that includes HTML character codes (e.g. "&#72;&#101;&#108;&#108;&#111;"), as well as a share and assignee.
3. Click on the header and go to the email view.
4. Observe that the title has been changed to regular words (e.g. "hello").

## Expected Result:
The Assign Task feature should correctly handle HTML character codes in the title field.

## Actual Result:
The Assign Task feature does not handle HTML character codes in the title field properly.

## Workaround:
Uknonwn

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f3971f75-61c8-481d-ba2b-3f5b93022669

https://github.com/Expensify/App/assets/93399543/3b7429f9-a867-4353-8e65-f3c796ef3068

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693229004601179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
asking in expensify bugs what the expected behaviour is

**Comment by zanyrenney** [comment]
confirmed with @thienlnam - there is no real world use case to support HTML characters in the task title, so the "expected behaviour" that this turns to actual alphanumeric, is correct. Closing.

**Comment by thienlnam** [comment]
I agree but I think we should fix that the task preview and the actual task title within the report show different things when alphanumeric characters are used. This can be external though!
