### ISSUE TITLE
Newly created distance requests appear as a whisper when they shouldn't (only valid for scanning receipts)

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26568]
Reproduction video

https://github.com/Expensify/App/assets/1127863/6c2d7389-95b5-4f11-9cde-f90fadcee0b6

**Comment by Pujan92** [comment]
I think this is a backend change where it should not respond with `whisperedToAccountIDs`

**Comment by JmillsExpensify** [comment]
Yes, I think that's right as well. cc @hayata-suenaga

**Comment by hayata-suenaga** [comment]
The above PR didn't solve the issue 😢 

Asking help from other engineers [here](https://expensify.slack.com/archives/C03TQ48KC/p1693885335792789?thread_ts=1693865954.073169&cid=C03TQ48KC)

**Comment by mountiny** [comment]
Last PR is ready

**Comment by mountiny** [comment]
this is done
