### ISSUE TITLE
[HOLD for payment 2023-12-06] [Distance] - Extra padding between the header and address field in waypoint editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26560]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25707
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Click Start

## Expected Result:
There is no extra padding between the header and address field in the waypoint editor

## Actual Result:
There is extra padding between the header and address field in the waypoint editor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6186228_Screenshot_2023-09-02_at_18 46 37](https://github.com/Expensify/App/assets/78819774/02bf2b58-f615-43ca-8635-78ec57272aaa)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f960fba5bc1e0680</li>
        <li>Upwork Job ID: 1700179776262045696</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27224524</li>
<li>Pujan92 | Contributor | 27224525</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra top margin for waypoint editor page

### What is the root cause of that problem?
We have provided `styles.mt4` to the address search container. 
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/WaypointEditor.js#L208

### What changes do you think we should make in order to solve the problem?
I am not sure whether it is intentional or not, otherwise we can take that margin out.

**Comment by mallenexpensify** [comment]
@lanitochka17 to ensure I'm understanding the bug correctly... 
The expected is this padding
<img width="386" alt="image" src="https://github.com/Expensify/App/assets/22508304/f0d0dff9-7c69-4c9e-aedd-b54995422cb9">

And the actual is below, where the extra padding is the red box area. 
<img width="439" alt="image" src="https://github.com/Expensify/App/assets/22508304/9981926e-1ee8-40b2-af93-29a5b0edcb65">

Is that correct? 

@CortneyOfstad  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by CortneyOfstad** [comment]
Can do @mallenexpensify!

**Comment by mallenexpensify** [comment]
hmmmmm.... for 
- https://github.com/Expensify/App/issues/23496 

@marcochavezf replied
> Sorry guys, given that from a design point of view this is not a problem and there's no general solution, I'm leaning towards closing the issue. I agree that the padding looks nicer and I don't find a reason to change it. We can re-open if someone disagrees with a counterargument.

If we decided not to fix that instance of extra padding to also want to not fix this one?  
Gonna tap in Design for feedback.

**Comment by shawnborton** [comment]
How much padding is being shown currently? I think we expect that there is just 12px of padding below the header.

**Comment by shawnborton** [comment]
Friendly bump

**Comment by mallenexpensify** [comment]
@jjcoffee can you please address the above? (I'm unsure how to get the measurement)
> How much padding is being shown currently? I think we expect that there is just 12px of padding below the header.

**Comment by mallenexpensify** [comment]
@jjcoffee can you please address the above? (I'm unsure how to get the measurement)
> How much padding is being shown currently? I think we expect that there is just 12px of padding below the header.

**Comment by jjcoffee** [comment]
That depends where you measure from! :sweat_smile: Currently it's 16px, assuming you measure like this (from the edge of the header's padding):

![Screenshot from 2023-10-04 10-41-23](https://github.com/Expensify/App/assets/27287420/565d1020-3284-4578-b55f-0fa30d380d49)

Otherwise it's 29px, from the bottom edge of the back arrow:

![Screenshot from 2023-10-04 10-37-34](https://github.com/Expensify/App/assets/27287420/6c4534b3-3a6f-4b67-ae5b-4578f16b03ce)

**Comment by shawnborton** [comment]
I think we just want 12px of padding/margin above the input.

**Comment by jjcoffee** [comment]
@shawnborton Just to clarify do you mean to reduce this gap from 16 to 12px?

![image](https://github.com/Expensify/App/assets/27287420/dc228f67-6c2e-4266-8552-8926088b5023)

**Comment by shawnborton** [comment]
Correct, that would be my vote.

**Comment by jjcoffee** [comment]
Thanks! Then we're good to go with @Pujan92's [proposal](https://github.com/Expensify/App/issues/26560#issuecomment-1703871315) here.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
I think that's probably beyond the scope of this issue, since there's no general solution. cc @mallenexpensify Are we good to just fix this one page?

**Comment by mallenexpensify** [comment]
> Let's check & fix all pages which have similar issue here as https://github.com/Expensify/App/issues/23496 was closed

I agree but... we first need to document all the instances, is there a quick/easy way to do that?
Once we have a list we can discuss potential increase in compensation.  In hindsight, I should have _paused_ to get the list of other instances then updated the deliverable in the OP.

**Comment by jjcoffee** [comment]
@mallenexpensify It doesn't look like a consensus was reached on the other issue as to which pages **needed** to be changed, but I guess it's just `any page that doesn't have the correct amount of padding` :sweat_smile: There is a list in [this](https://github.com/Expensify/App/issues/23496#issuecomment-1704919795) proposal but I don't know how authoritative it is.

I think @aimane-chnaif's summary [here](https://github.com/Expensify/App/issues/23496#issuecomment-1715481155) is on point if we want to solve on other pages (scrollable content needs to be handled a bit differently).

**Comment by jjcoffee** [comment]
@mallenexpensify Sounds like a plan! @Pujan92 are you okay with the [above](https://github.com/Expensify/App/issues/26560#issuecomment-1769233599)?

**Comment by Pujan92** [comment]
Ok @jjcoffee @mallenexpensify 

> After this change, we should remove additional top paddings/margins inside of:
> 
> * Priority mode page
> * PayPal page
> * ContactMethodsPage
> * ContactMethodDetailsPage
> * App download link
> * About page
> * WorkspaceMembersPage
> * ReimbursementAccountPage

Just to confirm, for the listed pages remove the additional margin/padding to make it consistent with `12px` which we have agreed for this issue. Right?

**Comment by mallenexpensify** [comment]
@shawnborton , can you please confirm
> Just to confirm, for the listed pages remove the additional margin/padding to make it consistent with 12px which we have agreed for this issue. Right?

If we're going to make multiple changes _at once_, I want to make sure we get it right.  Thx

**Comment by shawnborton** [comment]
That makes sense to me. Happy to help out with the PR review here.

**Comment by mallenexpensify** [comment]
Thanks @shawnborton , please move forward with the PR @Pujan92

**Comment by mallenexpensify** [comment]
@Pujan92 are we waiting on a PR from you? (can't remember where we're at, I did just remove the hold from the title though!)

**Comment by Pujan92** [comment]
Yes @mallenexpensify, sorry for the delay as I missed this somehow. PR will be up by tomorrow.

**Comment by AndrewGable** [comment]
Waiting for PR from @Pujan92 !
