### ISSUE TITLE
[$500] Pdf is not zoomed in in the preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26562]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Click on send attachment
3. Choose a pdf with a page that is big (Not A4 format)
## Expected Result: 
The preview should zoom in to be able to see the pdf like in web
## Actual Result: 
The preview does not zoom in and we don't see anything

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.362-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c27aa67a-d84c-4ce6-b392-f84d0516a975

[International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf](https://github.com/Expensify/App/files/12504403/International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf)

https://github.com/Expensify/App/assets/43996225/7aaeb2ad-0823-43dd-b352-8dad58e32c7d

https://github.com/Expensify/App/assets/43996225/7aaeb2ad-0823-43dd-b352-8dad58e32c7d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ShogunFire
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692994293796159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b9df6675ee52756</li>
        <li>Upwork Job ID: 1703878243534712832</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
Actually... this feels like more a `new feature` than a bug. We should add this in the future, but it's not a bug.

**Comment by ShogunFire** [comment]
@michaelhaxhiu on mweb and safari it's showing zoomed in. Isn't this inconsistency a bug ?

**Comment by imrancs058** [comment]
This is new feature that needs to be added in your code. So here's a technical description of how to add zoom-in and zoom-out functionality to a PDF in your app.

- Begin by installing the  package using npm or yarn.
- Import the required components.
- Create a component for displaying the PDF with zoom functionality.
- Maintain a state variable (e.g., zoom) to store the current zoom level. Initialize it to 1 for no zoom.
- Create functions (e.g., zoomIn and zoomOut) to adjust the zoom level.
- Define the source of the PDF you want to display using a URI or file path.
- Render the Pdf component from the specified PDF source. Configure properties like onLoadComplete, onPageChanged, and onError for handling PDF events.
- Use the enablePaging and fitWidth props for better viewing experience. Set the scale prop to the current zoom level (i.e., the zoom state)
- Include UI controls (e.g., buttons) for zooming in and out.Attach the zoomIn and zoomOut functions to these controls.
- Thoroughly test the PDF viewer with zoom functionality to ensure it works as expected on all devices. Handle any errors or issues that may arise during testing.



So these are my technical overview of handling this issue.  For further info you can contact me .

**Comment by imrancs058** [comment]
Contributor details
Your Expensify account email: imrancs058@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cbb2f374786dc4bd

**Comment by michaelhaxhiu** [comment]
@ShogunFire did it used to work the way you are describing in the past (on mobile)? If not, I'd argue this is more of a new feature request.
