### ISSUE TITLE
[HOLD for payment 2023-09-12] Show all options/information on the Distance Request Confirmation Page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26565]
Let's hide the "Show more" pill on the `MoneyRequestConfirmPage` and show all information if the money request confirmed is a distance request.

Internal slack conversation: https://expensify.slack.com/archives/C05DWUDHVK7/p1693664962005419

Confirmation page with the "Show more" pill
<img width="200" alt="Screenshot 2023-09-02 at 10 44 56 AM" src="https://github.com/Expensify/App/assets/98560306/28ef89aa-1d9c-4330-8272-f28b35910010">

Confirmation page with all information
<img width="200" alt="Screenshot 2023-09-02 at 10 45 07 AM" src="https://github.com/Expensify/App/assets/98560306/3c9bc73e-793f-4085-8dd1-545e893ecfbe">
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158bccb02b721b000</li>
        <li>Upwork Job ID: 1698099922060599296</li>
        <li>Last Price Increase: 2023-09-02</li>
    </ul>
</details>

**Comment by situchan** [comment]
Is this open for contributors or @mananjadhav will be (or is already) doing this?

**Comment by JmillsExpensify** [comment]
@hayata-suenaga Is someone already on this? If not, let's add the external label.

**Comment by hayata-suenaga** [comment]
I'm working on this right now myself

**Comment by JmillsExpensify** [comment]
Added myself as well depending on how reviews the PR.

**Comment by JmillsExpensify** [comment]
@s77rt I think you're owed compensation for a PR review on this issue, right? I think newly reviewed PR are eligible for $500 in compensation, though either way, do you think we need a regression test for this issue/PR. Let's start there.

**Comment by s77rt** [comment]
@JmillsExpensify Distance request is a new feature, there is no regression tests added yet, let's add one here

**Regression Test Proposal**
1. Open App
2. Press FAB
3. Press Request money
4. Select Distance
5. Type and choose any address for Start and Finish
6. Click Next
7. Choose any participant
8. Verify that all fields (Amount, Description, Date and Distance) are displayed



Yes, I think I'm eligible for $500 here

**Comment by hayata-suenaga** [comment]
waiting for payment and regression test to be added

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by JmillsExpensify** [comment]
Adding the regression test based on the recommendation above. @s77rt Do you mind applying the the Upwork job for payout: https://www.upwork.com/jobs/~0158bccb02b721b000.

**Comment by JmillsExpensify** [comment]
Regression test issue is created. @s77rt I went ahead and sent you an offer in Upwork to save you a step.

**Comment by s77rt** [comment]
@JmillsExpensify Accepted! Thanks!

**Comment by JmillsExpensify** [comment]
Awesome, all paid out. Thank you!
