### ISSUE TITLE
Web -  Mark as unread not working with deleted first message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with new user
2. Send any message
3. Hover on message and click reply in thread
4. Send any message
5. Click header to go back report
6. Hover on message and click delete
7. Hover on deleted message and click mark as unread

## Expected Result:
Mark as unread working

## Actual Result:
Mark as unread not work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/765a3a85-bdf5-4323-b596-d75e6e90df1c

https://github.com/Expensify/App/assets/93399543/d6a437e7-d10f-41fd-a1fd-5a67e53e3b86

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693245826685889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Thanks @bernhardoj. Closing as dupe.
