### ISSUE TITLE
[Awaiting Sibtain payment] [HOLD for payment 2023-09-12] [$500] When Distance Request Tab is tapped, all waypoints are lost

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26579]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a workspace chat
2. "+" button next to text composer -> Request money -> Distance request
3. "Start" -> type and choose an address (this creates one waypoint)
4. Click "Distance request" tab again

## Expected Result:
The start waypoint should remain the same

## Actual Result:
The start waypoint is cleared

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.62-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693685299726929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0d78086aa76dc15</li>
        <li>Upwork Job ID: 1698069080541106176</li>
        <li>Last Price Increase: 2023-09-02</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
> What alternative solutions did you explore? (Optional)
> We can also remove [this](https://github.com/allroundexperts/Expensify/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/MoneyRequestSelectorPage.js#L66-L69) altogether if the purpose of this bug report is that we should not reset the request when any tab is clicked.

We still want to reset the money request information because we are sharing the data for a draft money request. If we don't clear the data when a different tab/request type is selected, draft data from the previous type might be included in the new money request.

> so maybe we can also prevent the execution of [whole function](https://github.com/allroundexperts/Expensify/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/TabSelector/TabSelector.js#L100) code if isFocused is true.

I agree let's try this approach 💯

**Comment by hayata-suenaga** [comment]
@allroundexperts looking forward for your PR 😄

**Comment by b4s36t4** [comment]
Missed this 🙂🥲

**Comment by hayata-suenaga** [comment]
@trjExpensify @allroundexperts is a C+ and they made the PR
@situchan is also a C+ and they reviewed the PR

**Comment by trjExpensify** [comment]
Cool, assigning @situchan on the issue as well for tracking.

**Comment by b4s36t4** [comment]
I have reported this issue. @hayata-suenaga

**Comment by hayata-suenaga** [comment]
@b4s36t4 yep you did

<img width="300" alt="Screenshot 2023-09-04 at 11 05 18 AM" src="https://github.com/Expensify/App/assets/98560306/d7e9096a-27c9-4471-af1f-3663213c622d">

**Comment by b4s36t4** [comment]
Thanks so much Hayata. 🙌

**Comment by trjExpensify** [comment]
👋 Can we get the checklist filled out please?

**Comment by trjExpensify** [comment]
Confirming those payments due as follows, correct?

- $50 to @b4s36t4 for the bug report
- $1000 to @allroundexperts for the fix + #urgency bonus 
- $1000 to @situchan for the C+ review + #urgency bonus

**Comment by situchan** [comment]
No regression. Same tab press action was not prevented during first implementation of tab navigator.

**Regression Test Proposal**
1. Open FAB > Request money
2. Click Distance tab
3. Enter start and finish address
4. Click again Distance tab
5. Verify that entered addresses are not cleared

**Comment by trjExpensify** [comment]
Cool, thanks! I don't think we need to check for this one on every regression run, so I'm going to hold off on that test. 

[Offers sent](https://www.upwork.com/jobs/~01b0d78086aa76dc15) on this job.

**Comment by trjExpensify** [comment]
>@trjExpensify I get paid through the App.

Ah of course, I forgot you did. I can retract your offer no worries. 

>Shouldn't it be 750 instead?

Ah yes, it's 50% bonus. That's cool. I sent offers for the bounty price of $500 and then I add the bonus once accepted anyway. [Modified ](https://github.com/Expensify/App/issues/26579#issuecomment-1716665811)the above though!

**Comment by trjExpensify** [comment]
Cool, let's close it out!
