### ISSUE TITLE
 Request money - Amount is not preserved and it changes to zero when currency is changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26520
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Enter an amount
4. Change the currency

## Expected Result:
The amount is preserved and does not change

## Actual Result:
The amount is not preserved and it changes to zero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ca08e68f-36b9-4dbb-8130-2a1d238c0a4a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
This is from the issue is stemming
https://github.com/Expensify/App/pull/25707

**Comment by hayata-suenaga** [comment]
combining with https://github.com/Expensify/App/issues/26586
