### ISSUE TITLE
Make at least two waypoints visible on Distance Request page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26594]
Coming from this slack convo: https://expensify.slack.com/archives/C05DWUDHVK7/p1693712618173419

**Comment by JmillsExpensify** [comment]
Assigning myself as I'm helping with the launch

**Comment by hayata-suenaga** [comment]
@hungvu193 I'm sorry I think I got confused and created a dupe issue

Closing this in favor of [this one](https://github.com/Expensify/App/issues/26595)

**Comment by hayata-suenaga** [comment]
@hungvu193 I apologize for the oversight. Even though we're always trying to be fair, we sometimes prioritize the speed.

I really appreciate your continued contribution to Expensify, and I'm looking forward to review your proposal in the next issue 🙇
