### ISSUE TITLE
[HOLD for payment 2023-09-15] HIGH: Request money - Unable to open a scanned receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26155
## Action Performed:
1. Open the app
2. Log into expensifail account
3. Navigate to a workspace chat
4. Tap "+" and select "Request money" > "Scan"
5. Scan a receipt and submit a request
6. Open the request in the chat and tap the scanned receipt image

## Expected Result:
The scanned receipt is opened

## Actual Result:
Unable to open the scanned receipt. It prevents from complete smart scanning

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35ecb143-919e-4339-a030-82f7907d0e01

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e42c0a134392bbf</li>
        <li>Upwork Job ID: 1698776079310393344</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by mountiny** [comment]
confirming in slack if this is an actual issue to solve now

**Comment by mountiny** [comment]
Adding this to the high bucket based on https://expensify.slack.com/archives/C057F53HR40/p1693766785919719

**Comment by dylanexpensify** [comment]
@luacmartins can you take this on?

**Comment by luacmartins** [comment]
BZ checklist is complete. I think we need to pay @situchan for the PR review though

**Comment by dylanexpensify** [comment]
@situchan bump on the above! 🙇‍♂️

**Comment by situchan** [comment]
Accepted invite. Thanks

**Comment by dylanexpensify** [comment]
offer sent @situchan!

**Comment by dylanexpensify** [comment]
done!
