### ISSUE TITLE
[HOLD for payment 2023-09-04] Payment for composer refactor bugs found in main

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26599]
This is to pay for bugs found in the App composer refactor PR to improve the performance of the component. This was a big refactor bound to have some edge case errors not caught during the PR review and testing. The community helped to to clear those out while still in main 🎉 

cc @hannojg @rushatgabhane @narefyev91 

The listed issues have been reported in Slack and fixed before issues been even made, hence we are referring to them with Slack link only:

Please pay, this was before the change of pricing:
- @Natnael-guchima - $500
    - https://expensify.slack.com/archives/C049HHMV9SM/p1692989845172559
    - https://expensify.slack.com/archives/C049HHMV9SM/p1692991483808169
- @b4s36t4 - $500
    - https://expensify.slack.com/archives/C049HHMV9SM/p1692975017304079
    - https://expensify.slack.com/archives/C049HHMV9SM/p1692977320311239 
- @ayazhussain79 - $250
    - https://expensify.slack.com/archives/C049HHMV9SM/p1692980818642909  

I _think_ there was not more which we fixed

**Comment by sonialiap** [comment]
Job https://www.upwork.com/jobs/~01bb5dcb54a5d0ec80

I'm flying and the wifi is too slow for upwork, I'll send offers as soon as I'm on ground wifi

**Comment by sonialiap** [comment]
@Natnael-Guchima offer sent
@b4s36t4 offer sent
@ayazhussain79 offer sent

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks, @sonialiap

**Comment by sonialiap** [comment]
Everyone has been paid
