### ISSUE TITLE
Web - Pinned status does not reset between leaving and joining teachers unite room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Save the world > I know a teacher
2. Fill in the fields > Click on Let's do this
3. After joining the teachers unite room click on the pin icon
4. Click on the header and click on leave room
5. Click on FAB > Save the world > I know a teacher
6. Fill in the fields with different details and click on Let's do this
7. Observe the pinned status of the teachers unite room

## Expected Result:
The pinned status should reset and become un pinned when user re joins the teachers unite room

## Actual Result:
The pinned status remains the same before leaving the room and after rejoining the teachers unite room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2708b796-543c-4b17-998e-9005894ba7e1

https://github.com/Expensify/App/assets/93399543/5baf52ce-0483-4653-a0ec-97fbd61d3cef

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693383137322349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176a406bf6a78c1fa</li>
        <li>Upwork Job ID: 1699170091930390528</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
This is not exclusive to teachers room, you can repo this with any thread by sending a message, replying to thread then sending another message in the thread before pinning the thread and leaving it, when you go back to original report and click the reply and get taken back to the thread it would still be pinned. I don't know if this is intended or what.

**Comment by alifhaider** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pinned status doesn't reset on leaving room

### What is the root cause of that problem?
We are toggling pin status on clicking, which updates the session. But that status does not reset while leaving the room.

### What changes do you think we should make in order to solve the problem?
We can pass `isPinned` value to `leaveRoom` function 
https://github.com/Expensify/App/blob/91ff78db32f0284a73db13b2e2372583d71cb27f/src/pages/ReportDetailsPage.js#L121
and call the `togglePinnedState` function if the `isPinned` value is true. 
https://github.com/Expensify/App/blob/91ff78db32f0284a73db13b2e2372583d71cb27f/src/libs/actions/Report.js#L804-L824

So in `leaveRoom` fn
```
function leaveRoom(reportID, isPinned) {
    const report = lodashGet(allReports, [reportID], {});
    const reportKeys = _.keys(report);
    if (isPinned) {
        togglePinnedState(reportID, isPinned);
    }
    // .... rest
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by puneetlath** [comment]
I agree that we should have the back-end remove the chat from the list of pinned reports.

**Comment by puneetlath** [comment]
Auth PR to handle this is up. @s77rt removing you since there's not front-end component to this.

**Comment by puneetlath** [comment]
This is fixed!

**Comment by puneetlath** [comment]
Reopening as we need to pay @Nathan-Mulugeta

**Comment by puneetlath** [comment]
Offer sent: https://www.upwork.com/nx/wm/offer/26612757

**Comment by Nathan-Mulugeta** [comment]
Offer accepted

**Comment by puneetlath** [comment]
Paid!

Now we're done. 😄
