### ISSUE TITLE
Web - Error of not displaying the name and avatar of the person requesting the money in the workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. User A creates a workspace -> invites user B to the workspace
2. User B requests money for user A's workspace
3. Then user B deletes the request
4. User A enters any chat group and returns to box chat with owe requests

## Expected Result:
 The request is deleted.
After requesting money, the name and avatar of the person sending the request is still displayed.

## Actual Result:
The request is not deleted, after requesting money the name and avatar of the person sending the request is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bug#15 (1).webm](https://github.com/Expensify/App/assets/93399543/15bb9fb5-44af-4fdc-a582-f59f7d019816)

https://github.com/Expensify/App/assets/93399543/718ffd4a-ed98-4c0a-a363-9986c7ea5d70

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Le Thi Thu Thuy
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693386002150119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Can't reproduce, when I tested the deleted request automatically disappeared from the workspace.
