### ISSUE TITLE
[$500] Web - Task title stays highlited even after mouse leave

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open task report
2. Complete if not
3. Reopen and immediately move cursor slightly down

## Expected Result:
The task title should not be focused if cursor is not on it,

## Actual Result:
The task title is focused if cursor is not on it,

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a295b184-65dd-42ea-8cb7-1d7a12209651

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693389453994019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01102533c0698aa85c</li>
        <li>Upwork Job ID: 1699021940307935232</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by depak379mandal** [comment]
## Proposal
Mouse Enter event gets fired but never recognizes mouse leave because of hard scroll after unchecking checkbox of Task

### Two things we can do about this issue
1. Remove scroll behavior after unchecked checkbox 
https://github.com/Expensify/App/blob/c8dc57f100fcc1b83dcac3f4ade62d19ad226e70/src/components/ReportActionItem/TaskView.js#L70

2. instead of hard scroll, make it smooth scrolling.

**Comment by MitchExpensify** [comment]
@abdulrahuman5196 please give the existing proposals here a review 🙇

**Comment by MitchExpensify** [comment]
Awesome, thanks @Krishna2323
