### ISSUE TITLE
Web - Emojis are accepted in name fields in " I know a teachers page"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to fab button -> save the world
2. now go to I know a teacher
3. in the name fields enter emojis like :smile::sob::sob:

## Expected Result:
Name fields should not accept emojis only field.

## Actual Result:
Emojis are accepted in name fields in " I know a teachers page"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7980a09e-7539-461a-940e-f741b5f23ca0

https://github.com/Expensify/App/assets/93399543/55ed4146-40fe-4492-98e1-c36b62ee1306

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693397428120089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f2493332ae4694a</li>
        <li>Upwork Job ID: 1708434857718169600</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
Just FYI, this is same RC as this https://expensify.slack.com/archives/C049HHMV9SM/p1692198598449099 and this https://expensify.slack.com/archives/C049HHMV9SM/p1691823752102549 and a bunch of others, and it was decided to do nothing about it.

**Comment by JmillsExpensify** [comment]
I'm not really sure we need to add these controls. Do we have such a control in place for other email fields?

**Comment by JmillsExpensify** [comment]
Awesome, closing this as a dupe then!
