### ISSUE TITLE
Web - The date change from the scan is incorrectly placed in the IOU section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Clicked on the plus sign and selected "Request Money".
2. Added the recipient's photo using the scan feature.
3. Waited for a long time until the scan finished.
4. Observed that the date, which changed due to the scan, is misplaced. Instead of appearing in the detail section, it appears in the section where the total amount is displayed.

## Expected Result:
The date change notification from the scan should be placed in the IOU detail section, similar to when we manually change the date.

## Actual Result:
The date change from the scan is wrongly placed in the IOU section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/007bf353-53c2-49b1-8a7e-818f67562599

https://github.com/Expensify/App/assets/93399543/2689de54-3b93-42c9-9bd3-2e132212df5f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693397586960019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Assigning over to @dylanexpensify so that it can be handled as part of Wave4 🚀

**Comment by dylanexpensify** [comment]
Nice! TY Sasha! Reviewing soon!

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment]
clarifying behavior

**Comment by dylanexpensify** [comment]
cannot repro!

**Comment by tewodrosGirmaA** [comment]
@dylanexpensify , I am not eligible for payment?☺️
