### ISSUE TITLE
[$500] [HOLD for payment 2023-10-02] Add `filename` to Transaction.ts

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26630]
From this Auth PR: https://github.com/Expensify/Auth/pull/8623
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f24b7eee92e3a5f</li>
        <li>Upwork Job ID: 1709213888062615552</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by tgolen** [comment]
I'll do this as part of https://github.com/Expensify/App/pull/27203 so I am assigning it to myself.

**Comment by tgolen** [comment]
This was an internal issue, but @narefyev91 needs to be paid out for a PR review. I'm going to try to assign this to the bug-zero team to get that paid.

**Comment by isabelastisser** [comment]
@narefyev91, what's your Upwork profile?

@tgolen to confirm, should the payment amount be $250 or $500 for the internal review?

**Comment by narefyev91** [comment]
> @narefyev91, what's your Upwork profile?
> 
> @tgolen to confirm, should the payment amount be $250 or $500 for the internal review?

Hey @isabelastisser! I'm from expert agency - Callstack - no needs any payment in upwork, thanks!

**Comment by tgolen** [comment]
Oh, OK, I think this can just be closed then!
