### ISSUE TITLE
Web - Chat - Clicking "Esc" key to close keyboard shortcut modal doesn't bring up the emoji suggesting box

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Type ":he" inside the composer
2. Press CTRL + J to bring up the keyboard shortcut modal
3. Click on the close icon and observe the composer
4. Press CTRL + J again
5. Click outside the modal and observe the composer
6. Press CTRL + J again
7. Press "Esc"  key on the keyboard and observe the composer

## Expected Result:
The emoji suggestion box should be open again after the modal has been closed by pressing the "Esc" key

## Actual Result:
The emoji suggestion box doesn't pop up again after closing the modal using the "Esc" key, but it pops up automatically when using the other methods on step 3 and 5 to close the modal.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7043230e-f930-48df-988b-55d3c6913168

https://github.com/Expensify/App/assets/115492554/a9152328-3440-4f65-bb91-477cf39e08d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692945940448799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hm, I feel like this isn't really a bug that a user would likely to encounter. 

Also, we're probably going to move the keyboard shortcuts into the RHP instead of being a central modal as discussed [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1693502891503009?thread_ts=1693502047.704089&cid=C01SKUP7QR0) and [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1693596432761489). Which would make this moot. 

Given both of those points, I'm going to go ahead and close this.
