### ISSUE TITLE
Web - DOB – Selected year doesn’t appear in input field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open your user profile.
2. Click on the "Settings" option.
3. Select "Personal Details."
4. Select “Home address”
5. Select “Country”
6. After selection of any country, go back and return.
7. Note that upon returning, the country selected in the previous step appears in the placeholder.
8. Open your user profile.
9. Click on the "Settings" option.
10. Select "Personal Details."
11. Choose "Date of Birth."
12. Select any date and save.
13. Now click on "Year" button.
14. Notice that the chosen year does not appear in the input field, unlike other sections.

## Expected Result:
Consistency is expected in whether the previously selected item should be displayed in the input field.

## Actual Result:
The selected year does not appear in the input field as intended.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/81e02a0f-e3db-4fd9-95e4-4e4ec9da2480

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690955359134649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are setting current year as empty string here initially.

https://github.com/Expensify/App/blob/a7cba2d4406875ada5d6f5aa7984eaaf96efa9f8/src/components/NewDatePicker/CalendarPicker/YearPickerModal.js#L47-L52

### What changes do you think we should make in order to solve the problem?
We shall set the year here in useEffect using props.currentYear- 
```js
    useEffect(() => {
        if (props.isVisible) {
            setSearchText(props.currentYear.toString());
            return;
        }
        setSearchText('');
    }, [props.isVisible, props.currentYear]);
```

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment]
The "Year" setting isn't a saveable field like the address country, you need to select a specific date in that year to ensure it changes and saves. This is expected behaviour, not a bug.
