### ISSUE TITLE
Web - Scan- Able to write messages even after deleting the Receipt scan in progress chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on + > Request money > Scan > Choose file, user and continue > Reach "Receipt scan in progress…" page > Cancel it > And Write message, open details of it

## Expected Result:
Unable to write messages even after deleting the Receipt scan in progress chat

## Actual Result:
Able to write messages even after deleting the Receipt scan in progress chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-30T173845.120 (1).webm](https://github.com/Expensify/App/assets/93399543/751eb754-2052-4f19-82a8-c4dc15ed9584)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693399119719459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I think this could be expected. Commented in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1693914127410419?thread_ts=1693399119.719459&cid=C049HHMV9SM
