### ISSUE TITLE
Web - Some .bmp files does not show in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send .bmp file

## Expected Result:
Should show preview of .bmp file

## Actual Result:
Does not show preview or as an attachment do download file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ee3ff4e4-e892-4405-9525-45a8d836cbb6

https://github.com/Expensify/App/assets/93399543/0652e121-3f2c-47bc-a194-5da1e85b668d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689854452166949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184e0f8706ddb9c47</li>
        <li>Upwork Job ID: 1698989397308989440</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by AmjedNazzal** [comment]
Similar to [this](https://github.com/Expensify/App/issues/23739) issue, this is also a backend problem. what I observed is that the backend is returning an <a> tag for bmp images instead of an <img> tag like it does for jpg and png.

**Comment by flaviadefaria** [comment]
Adding the internal label since this looks like a backend issue.

**Comment by flaviadefaria** [comment]
Adding the engineer label as no engineer has been assigned.

**Comment by roryabraham** [comment]
Asking in slack if this is a file format we're supporting right now. This might be a feature request

**Comment by roryabraham** [comment]
Also going to make this a weekly – I think this should be low priority because I've never really seen this file format before.

**Comment by roryabraham** [comment]
Slack thread: https://expensify.slack.com/archives/C03TQ48KC/p1694659752399939

**Comment by youssef-lr** [comment]
I'll get a PR up for this one this week.

**Comment by youssef-lr** [comment]
Can be weekly.

**Comment by youssef-lr** [comment]
Fix coming this week.

**Comment by youssef-lr** [comment]
Couldn't get to this due to focusing on a design doc with tight deadline, I'll have a PR for this one tomorrow.

**Comment by flaviadefaria** [comment]
@youssef-lr were you able to get that PR ready?

**Comment by flaviadefaria** [comment]
@youssef-lr do you have an update here? 😬

**Comment by youssef-lr** [comment]
Creating the PR today!

**Comment by flaviadefaria** [comment]
Cool please keep us posted!

**Comment by youssef-lr** [comment]
Will do. Sorry didn't get to it yet, I will have free cycles tomorrow. I'm currently focusing on multiple PRs related to Wave7 & Money2020.

**Comment by flaviadefaria** [comment]
@adelekennedy I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by youssef-lr** [comment]
I'll get to this next week, this is a low priority bug and can be weekly.

**Comment by adelekennedy** [comment]
Youssef will be getting to this next week

**Comment by adelekennedy** [comment]
bump on this @youssef-lr

**Comment by youssef-lr** [comment]
PR ready!

**Comment by youssef-lr** [comment]
@adelekennedy can we pay the reporting bonus please?

**Comment by gadhiyamanan** [comment]
bump @adelekennedy 
@youssef-lr can we changed it to weekly or daily instead of monthly ?

**Comment by adelekennedy** [comment]
sorry! This dropped off my K2

**Comment by adelekennedy** [comment]
just created the job and hired you: https://www.upwork.com/jobs/~013a6c902148242a54

**Comment by gadhiyamanan** [comment]
@adelekennedy offer accepted, thanks!

**Comment by adelekennedy** [comment]
and paid!
