### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500]  Workspaces  - Auto select member after invite

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a WS
2. Go to members and invite some members (about 3 members)
3. Select 1 member
4. Click invite again and search new member
5. Press enter some times (important: about 3-4 times)
6. Click member to invite
7. Click next
8. Click invite, observe some members was selected.

## Expected Result:
No select member after invite

## Actual Result:
auto select member after invite

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f72e80fa-7cc4-4e87-beaf-6b8d223fd0be

https://github.com/Expensify/App/assets/115492554/adec3503-ac51-42d2-9a97-6aee4252328c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692971244708429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a838c373f60f807</li>
        <li>Upwork Job ID: 1700169777562968064</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26648637</li>
<li>namhihi237 | Reporter | 26648640</li>
</ul></li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
@sobitneupane we have 1 proposal from @bernhardoj above already ☝️ 😄

**Comment by sobitneupane** [comment]
will review the proposal shortly.

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/26667#issuecomment-1706639974) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

`BaseSelectionList` was refactored in [this PR](https://github.com/Expensify/App/pull/21048). It started the use of `useKeybaordShortcut` hook. But I believe the problem exists prior to the refactoring.
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1695617530071679
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open Settings > Workspaces > Select any workspace > Members > Invite
2. Select one user to invite and press Next
3. Press CTRL/CMD+Enter
4. Verify the text input is still focused
5. Press anywhere to blur the text input
6. Press Enter multiple times
7. Go back
8. Verify the selected user does not change

**Comment by michaelhaxhiu** [comment]
Nice job! Let's pay this now.

- Bug reporter: $250 @namhihi237 (reported aug 25 which is 5 days before the bug bounty price changed to $50)
- Contributor: $750 @bernhardoj (50% bonus)
- C+: $750 @sobitneupane (50% bonus) please request via newdot

**Comment by michaelhaxhiu** [comment]
@sobitneupane let us know after you request payment please, so I can close this GH :)

**Comment by michaelhaxhiu** [comment]
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps:**
- Wait for @sobitneupane to confirm he requested payment and received it.
- Close this GH

**Comment by joekaufmanexpensify** [comment]
@sobitneupane[ tracks these](https://expensify.slack.com/archives/C02NK2DQWUX/p1695963674123279?thread_ts=1695876628.961999&cid=C02NK2DQWUX) in his end, so no need to leave this one open for now. We just need to issue payment once he requests it!

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/26667#issuecomment-1738118445

Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @sobitneupane based on BZ summary.
