### ISSUE TITLE
[HOLD for payment 2023-09-13] Feature Request: [distance] request show address suggestions by place name or address

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26688]
## Problem
Autocomplete suggestions are only shown for addresses when entering a waypoint for a distance request. So if I want to go the the Expensify lounge in SF I need to know the address 88 Kearny in order to see a suggestion for the full address. Instead I want to be able to enter “Expensify lounge SF” and see it show up as a suggestion. We still want suggestions for addresses as well.

## Solution
We can make the work by changing the types query param to allow all place types rather than only addresses.

**Comment by sakluger** [comment]
Nobody needs to be paid for this one, closing!
