### ISSUE TITLE
[Distance] Dev: Web - Cursor changes to grabbing cursor when right clicking but not return to released hand when releasing the click

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26698]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Request money
3. Click on Distance tab
4. Hover over the map and click the right mouse click one time and stay on the same position and observe the cursor

## Expected Result:
The cursor should change to released hand when the right mouse button is released

## Actual Result:
The cursor stays to be a grabbed hand cursor even after user released clicking the right mouse button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.62-4
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eeb170be-b179-485a-9720-09b77e45a8b9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693847883533249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Sorry, catching up from OOO last week. 

I don't consider this a bug, the feature seems to be working fine.
