### ISSUE TITLE
CRITICAL: SmartScan triggers incorrectly triggers a report history action in the NewDot report

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26703]
Now that we're SmartScanning for the first time, we're incorrectly triggering a system message / history on NewDot when SmartScan fills out the details. Even worse, we're making it look like the member who scanned the receipt took the action, when actually they didn't. 

Solution: Let's not show report or request history when Expensify is the one that filled out the information. System messages track user changes, or unexpected automation. This describes neither of those scenarios. 

![Image](https://user-images.githubusercontent.com/1127863/265524400-1aab7ee6-ecc8-4bfa-b2a0-d7898f87bfad.jpeg)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac8787f5a2068103</li>
        <li>Upwork Job ID: 1698763689720827904</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Keeping internal for backward compatibility.

**Comment by MariaHCD** [comment]
Related Slack conversation: https://expensify.slack.com/archives/C057F53HR40/p1693873277606749

**Comment by JmillsExpensify** [comment]
Isn't this one fixed at this point?

**Comment by trjExpensify** [comment]
Yeah, @Gonals has a follow-up issue for the `requested $0.00` portion.

**Comment by Gonals** [comment]
Ah, yeah, this is fixed. We no longer display the "changed stuff..." messages.  The `requested $0` message is in a different issue (and with a fix in place), so closing this 😎
