### ISSUE TITLE
[$500] Web -  Incorrect zip code format shown on some default addresses in personal details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Profile -> Personal details
2. Then go to Home Address
3. In address line one type 'P' and select the first shown one i.e "Pearson Airport Terminal 1 Parking, Canada"
4. Notice that auto filled zip/postal code is "L5P"
4. Click on save
5. Notice that it throws error. Invalid zip format

## Expected Result:
 Either proper zip format should be used or the field is to be left empty. Autocompleting zip/postal code with improper formats leads confusion.

## Actual Result:
Incorrect zip code format shown on some default addresses in personal details page

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6ef450c5-5009-42e5-b965-6c2b55d93aa8

![Screenshot 2023-08-31 at 3 04 33 PM](https://github.com/Expensify/App/assets/93399543/3af9ae04-b1be-40c7-9a19-67bc9bc7de92)

https://github.com/Expensify/App/assets/93399543/31df3774-01be-48e5-a9e1-d89c3ebd44c4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693473068367439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0bf473d39971cf7</li>
        <li>Upwork Job ID: 1699279457111240704</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
![2023-09-06_16-32-05 (1)](https://github.com/Expensify/App/assets/42940078/f4fce92a-4769-45a2-8203-196fe403428d)

Reproducible!

**Comment by sophiepintoraetz** [comment]
Thanks @ntdiary!
