### ISSUE TITLE
Request money - "Category" field has empty list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26597
## Action Performed:
1. Open the staging desktop app
2. Click on the + icon
3. Click on Request Money
4. Enter an amount and click Next
5. Select a Workspace
6. Click on Show more > Category

## Expected Result:
Category field to list all possible categories

## Actual Result:
Empty list is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6188295_Screen_Shot_2023-09-04_at_9 40 15_PM](https://github.com/Expensify/App/assets/78819774/15ffa80d-a94a-4906-bf74-1864c06c359e)

https://github.com/Expensify/App/assets/78819774/0a789915-9fb9-4d8b-b382-253b6c78a83d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!
