### ISSUE TITLE
[HOLD for payment 2023-10-18] [HOLD for payment 2023-09-20] [$500] BUG: [distance] Tapping date on iOS confirmation screen crashes the app

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26719]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings> preferences> language>  choose spanish.
2. Click green plus, request money, distance
3. Enter start and finish addresses
4. Click next
5. Click the date field

## Expected Result:
You are navigated to the date selector page

## Actual Result:
The app crashes

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://github.com/Expensify/App/assets/26260477/56bf1ab4-a31a-46e8-bf02-aba3eb710674

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93 originally, and @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693773862316259 and https://expensify.slack.com/archives/C05DWUDHVK7/p1693858687755119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01410dc76d9aff99d8</li>
        <li>Upwork Job ID: 1698795084385435648</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26532576</li>
<li>ahmedGaber93 | Reporter | 26532579</li>
<li>mkhutornyi | Contributor | 26532619</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by ahmedGaber93** [comment]
I report this issue yesterday in slack expensify-bugs channel here https://expensify.slack.com/archives/C049HHMV9SM/p1693773862316259

**Comment by neil-marcellini** [comment]
Oh thanks I missed that, I'll update the description with your report.

**Comment by JmillsExpensify** [comment]
Taking this one from Anu as part of wave5.

**Comment by neil-marcellini** [comment]
@situchan jumped in as the C+ [from Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1694026686814969?thread_ts=1693988213.820559&cid=C01GTK53T8Q) and since he got this moving I'm going to have him take it over.

**Comment by neil-marcellini** [comment]
We both like the [proposal](https://github.com/Expensify/App/issues/26719#issuecomment-1708873889) from @mkhutornyi and Situ verified that it fixes the issue. Please raise a PR soon.

**Comment by neil-marcellini** [comment]
Ah ok good call out. So maybe we should consider replacing the use of moment here with some other library in line with the replacement plan on that issue?

That being said, it's most important to fix the crash now and we can always replace the use of moment.js later.

**Comment by neil-marcellini** [comment]
Bump for payment @anmurali

**Comment by neil-marcellini** [comment]
Bumping from NewDot.

**Comment by ufumerfarooq** [comment]
The issue still persists on v1.3.74-0

**Comment by anmurali** [comment]
@neil-marcellini is this fixed? The above comment is confusing to me. Is this ready to be paid or not?

**Comment by pradeepmdk** [comment]
the code revoked this PR due to remove the momentJS https://github.com/Expensify/App/pull/26248

**Comment by situchan** [comment]
Though the code was reverted, it should not affect payment as the regression came from another PR where we didn't handle anything.
cc: @anmurali

**Comment by neil-marcellini** [comment]
Yeah it looks like [this PR](https://github.com/Expensify/App/pull/26248) removed our fix, and so it needs to be added back. Is that right guys @situchan?

**Comment by situchan** [comment]
@neil-marcellini seems like moment will be fully removed soon - https://github.com/Expensify/App/issues/19810#issuecomment-1737905545

**Comment by neil-marcellini** [comment]
This is still reproducible. While we could wait for moment to be removed fully, I think we should re-implement the fix that was accidentally reverted. Having the whole app crash when using this feature in Spanish is pretty bad. @mkhutornyi would you please put up a PR today?

**Comment by neil-marcellini** [comment]
^ that's incorrect, he did that within 3 days of being requested.

**Comment by neil-marcellini** [comment]
@situchan please fill out the checklist

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26248
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26248#discussion_r1339021270
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to Settings > Preferences > Language > Choose Spanish
2. Click FAB > Request money > Select Distance tab
3. Enter start and finish addresses
4. Click Next
5. Click the date field
6. Verify that app doesn't crash and date picker shows

**Comment by neil-marcellini** [comment]
Yeah I don't think we need the regression test.

**Comment by neil-marcellini** [comment]
@anmurali if you would please pay this then I think it's done.

**Comment by anmurali** [comment]
Everyone's paid.
