### ISSUE TITLE
 [Distance] - The waypoints (Start and Finish) only show up after map appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26525
## Action Performed:
1. Launch New Expensify desktop app
2. Go to + > Request money
3. Click Distance

## Expected Result:
The waypoints and map show up together

## Actual Result:
The waypoints (Start and Finish) only show up after map appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fbe15e9e-1d01-446f-8d49-55b896fbe47e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
I don't think this is a bug, but rather just an optimization thing. For me, sometimes they appear before the map renders, and sometimes afterwards. I think the delay isn't long enough to be considered problematic, so I'm going to close this one out.
