### ISSUE TITLE
Workspace - App crashes after creating WS offline, going online and getting policy error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to Desktop App / staging.new.expensify.com with account [applausetester+disabledpolicy@applause.expensifail.com](mailto:applausetester+disabledpolicy@applause.expensifail.com)

2. Go offline
3. Click/tap on the green plus button (FAB) and create a new Workspace
4. Back online

## Expected Result:
User get an error message as a result of the account has workspace creation disabled policy

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4cb77b87-c4c7-4ee9-a02b-e63b7c37bbf4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Can't reproduce on Prod or Staging
