### ISSUE TITLE
[HOLD for payment 2023-09-15] Request money - Merchant name is not indicated as unknown merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26643
## Action Performed:
1. Create a new receipt money request from newDot by going to + -> Request Money -> receipt and sending a random image. Make sure to choose a worskpace ( Used a receipt masking the merchant details)

## Expected Result:
Merchant name indicated as unknown and error displayed

## Actual Result:
Merchant name displayed as none and no error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cf09599f-6f12-4ee1-9d0c-49b18b4484c9

![Bug6188638_receipt__2_](https://github.com/Expensify/App/assets/78819774/8eb17c5c-6eda-458e-83ab-c1ec04840395)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
@Gonals (cc @mountiny and @MariaHCD) - this is came from [one of your PRs ](https://github.com/Expensify/App/pull/26643)- shall I assign it to you to fix?

**Comment by Gonals** [comment]
I don't think this is a bug, at least, not with the described steps. The merchant is only marked as unknown after Smartscan, if the smartscanner indicates so manually, but maybe we should show an error for the merchant in this case too. Looking into it

**Comment by mountiny** [comment]
This is no t a bug, you cannot set empty Merchant @lanitochka17 can you update the test steps? For now, merchant field can never be empty

**Comment by Gonals** [comment]
There is a bug, though, @mountiny! If the merchant is `(none)` (the partial transaction one) and smartscan has stopped, we should have the user populate it with a real one

**Comment by MariaHCD** [comment]
> If the merchant is (none) (the partial transaction one) and smartscan has stopped

Wouldn't we show the RBR in that case?

https://github.com/Expensify/App/blob/1bdc5acc12f982b4f6e37bfadf9060ac3d2d3b3c/src/libs/TransactionUtils.js#L92-L100

**Comment by Gonals** [comment]
> one of your PRs



> > If the merchant is (none) (the partial transaction one) and smartscan has stopped
> 
> Wouldn't we show the RBR in that case?
> 
> https://github.com/Expensify/App/blob/1bdc5acc12f982b4f6e37bfadf9060ac3d2d3b3c/src/libs/TransactionUtils.js#L92-L100

We will if it is in the original merchant, but not if it is in the modified one.
However, we will NOT show it in the transaction. here are my changes to make sure we do: https://github.com/Expensify/App/pull/26865/files

**Comment by sophiepintoraetz** [comment]
No payments needed here as it was reported by Applause and fixed internally - @Gonals - do we need a regression test for this?

**Comment by Gonals** [comment]
Nah, this wasn't really a bug, but I did find a related bug while testing 😆
