### ISSUE TITLE
Chat - User searches "plant" , the first emoji is auto selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap emoji picker
4. Enter "plant" to search
5. Launch app
6. Repeat steps 2-4

## Expected Result:
In mweb, when user search for " plant", the results alone must be displayed and first emoji must not be auto selected

## Actual Result:
In android, when user searches " plant" , the results alone displayed and first emoji is not auto selected but in mweb, first emoji is auto selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f57fcb0b-8572-41c4-82a7-d761acdc2adc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
This seems like a small polish and not necessarily consistent with other apps
