### ISSUE TITLE
Chat -The "send" button is not responsive on first tap

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter a message
4. Tap "send" button

## Expected Result:
The "send" button must be responsive and it must work on single tap

## Actual Result:
The "send" button is not responsive on first tap and user has to tap multiple times to send a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Bug6188608_send.mp4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment]
unable to repro - @lanitochka17 to confirm

**Comment by lanitochka17** [comment]
The issue is still reproducible . Samsung A50/Chrome
Build 1.3.70-2


https://github.com/Expensify/App/assets/78819774/2bd10774-a461-4a9c-809d-4455ee1d0538

**Comment by dylanexpensify** [comment]
Ah @lanitochka17 can you confirm if this is reproducible on an android device that _isn't_ the A50?

**Comment by dylanexpensify** [comment]
@lanitochka17 bump on the above request! 🙇‍♂️

**Comment by dylanexpensify** [comment]
@lanitochka17  bump

**Comment by lanitochka17** [comment]
@dylanexpensify Sorry for delay
Issue is not reproducible on Build  1.3.74-0
SG M 52/Chrome/Android 13


https://github.com/Expensify/App/assets/78819774/8ce41fce-9db1-416c-8a3f-ef0e54e60baa

**Comment by lanitochka17** [comment]
@dylanexpensify 
Issue is not reproducible on Build 1.3.74-0
Samsung Galaxy Note 10+ / Android 12
 
https://github.com/Expensify/App/assets/78819774/59f839b9-a7b9-454f-8a53-a15b393cd0e8

**Comment by dylanexpensify** [comment]
perfect, closing!
