### ISSUE TITLE
Dev: WEb - Social media icons are missing in login page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. If you are already logged in then log out or go to the login page
3. Observe the login page

## Expected Result:
The social login icons should be present

## Actual Result:
The social login icons are missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  Dev 1.3.63.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/22ec8dbf-4b71-4445-9ca6-f90b7e748c99

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693900038461919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
I think this is intended
https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/pages/signin/LoginForm/BaseLoginForm.js#L242-L247

**Comment by sonialiap** [comment]
Agreed, that looks intended. Closing
