### ISSUE TITLE
IOUs - Only one of the IOUs appear when IOU thread with multiple IOUs is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26613
## Action Performed:
1. Go to staging.new.expensify.com
2. Set the network to slow 3G
3. Log in with a HT account with multiple manual IOUs in one IOU thread (create one by requesting money to each other from User A and B)
4. While the page is loading, navigate to the IOU thread that has two requesters (IOUs)

## Expected Result:
When the page is loading, both IOUs appear with skeleton loading

## Actual Result:
When the page is loading, only one of the IOUs appears with skeleton loading. The other one only appears after the page is completely loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8c1f0ac7-1065-443a-8274-6d7ad097cede

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I don't think this is a bug. We show only the one IOU in the skeleton because we don't know how many expenses there are until we get the data. I'm going to go ahead and close this, but feel free to comment if you disagree!
