### ISSUE TITLE
 [Distance] - Amount/Cash is not updating when editing the Merchant field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR**  https://github.com/Expensify/App/pull/26536
## Action Performed:
1. Open the staging web app
2. Click on the green + button
3. Click on Request money
4. Select Distance
5. Select a Start and Finish addresses
6. Click Next and select a Workspace
7. After request is sent, click on it to open request detail page
8. Click on the Merchant field and change the miles number of price per mile

## Expected Result:
Amount/Cash field to update accordingly once Merchant or Distance field is updated

## Actual Result:
Amount/Cash field does not update

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8be64d0d-453a-4d9e-af3f-5a6a1c53b55d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@hayata-suenaga you seem heavily involved in the [linked PR](https://github.com/Expensify/App/pull/26536), can you please take a look at this one and see if it's a bug, or maybe it's a feature request? The design doc says this about editing distance expenses:

>While these fields are editable as normal, editing the amount manually will mean that the amount for payment doesn’t necessarily match the mileage receipt. 

So it seems like this is expected behaviour.

**Comment by hayata-suenaga** [comment]
This is the expected behavior. Closing this
