### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Profile - Unable to upload .svg file as profile photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Click on profile photo > Upload photo
3. Upload a svg file

## Expected Result:
The svg file is uploaded successfully for profile photo

## Actual Result:
The svg file fails to upload
Attachment error
An error occurred while selecting a corrupted attachment, please try another file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b2819d54-9d0a-4f59-a157-18f0fc0c5504

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01daf722c26b685a79</li>
        <li>Upwork Job ID: 1699583361425006592</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 26541772</li>
<li>rmm-fl | Contributor | 26767787</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
I can't upload a .SVG file via BrowserStack for Android native as that file type isn't supported in the emulator. @s77rt don't suppose you'd mind giving this a quick go to reproduce? 

In the meantime, @lanitochka17 it might be helpful to include the specific SVG file you used in this issue for us to check as well. Thanks!

**Comment by s77rt** [comment]
@trjExpensify I can reproduce. The image looks blank in the image picker.


https://github.com/Expensify/App/assets/16493223/103c9e0f-19ea-4a14-9772-f21d4a40f117

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
@s77rt if you want the C+ on it coz' you helped, here let me know!

**Comment by s77rt** [comment]
I would assume the bug to be upstream. @fedirjh Can I take this one?

**Comment by trjExpensify** [comment]
Done!

**Comment by trjExpensify** [comment]
Waiting for proposals!

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals

**Comment by trjExpensify** [comment]
No proposals, huh. Updated the bounty to $1000.

**Comment by s77rt** [comment]
@rmm-fl Thanks for the proposal. Your RCA makes sense. The solution also makes sense but we would have to make "exceptions" for named issues 1 and 2, right? In that case can we make the conversion at an earlier phase i.e. while selecting the image (preferably to be done natively via react-native-image-picker).

Also, seeing that iOS does not show svg in the image selector, I think it would be acceptable to disallow svg selection on Android as well. Though it's not clear how to exclude svg mime type in [intent type](https://github.com/react-native-image-picker/react-native-image-picker/blob/1c7d59cb484a4a91d8829c4eeed1763f3e5d3adc/android/src/main/java/com/imagepicker/ImagePickerModuleImpl.java#L152).

**Comment by s77rt** [comment]
@rmm-fl Can you please raise a PR upstream (have the feature also available for videos). If the PR got accepted, we can probably go with that solution

**Comment by s77rt** [comment]
@rmm-fl Thanks for the update! Let's go with the alternative solution.

For future proposals please do not post code diffs.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/26768#issuecomment-1724245960)

**Comment by Julesssss** [comment]
Sounds good. I'd love to follow up this with a new bounty for getting the change merged upstream.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: N/A. This bug is in the upstream repo (react-native-image-picker)
- The offending PR has been commented on: N/A
- A discussion in #expensify-bugs has been started: N/A
- Determine if we should create a regression test for this bug: No

**Comment by Julesssss** [comment]
Ready for payment today

**Comment by trjExpensify** [comment]
Sent @s77rt an offer. Once confirmed on the above, I'll settle up with you both!

**Comment by s77rt** [comment]
@trjExpensify Accepted! Thanks!

**Comment by trjExpensify** [comment]
Perfect, settled up with you both. Closing!
