### ISSUE TITLE
Desktop - New Chats are not showing in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with your account

## Expected Result:
New Chats are showing in LHN

## Actual Result:
New Chats are not showing in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (34)](https://github.com/Expensify/App/assets/93399543/10b31260-ce4c-4ba7-9e10-ada7b4aea74f)
![image (33)](https://github.com/Expensify/App/assets/93399543/b4d44a35-5c3a-48fa-bf85-8c70ff298c4c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693336345090439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flaviadefaria** [comment]
@mallenexpensify I'm closing this for now please reopen it once you have more details to add as asked above, thanks!

**Comment by kbecciv** [comment]
Unable to reproduce it on build v1.3.77-3 @mallenexpensify 

https://github.com/Expensify/App/assets/93399543/d6b63009-4e63-4b3c-8c4e-08047a0589ef

**Comment by mallenexpensify** [comment]
Happened to me this morn in iOS ¯\_(ツ)_/¯
https://expensify.slack.com/archives/C049HHMV9SM/p1696438965730399

I'm the 👑 of reporting bugs that aren't reproducible, or easy to reproduce
