### ISSUE TITLE
[ECard Settings] - Create `getExpensifyCardDetails` (Auth) to return private card info that cannot be stored in Onyx

### ISSUE THREAD

**Issue by grgia** [Expensify/App#26776]
DD Section - https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#bookmark=id.kphf43fnpibv

Sub Step of https://github.com/Expensify/App/issues/26777

**Comment by grgia** [comment]
@luacmartins Did you volunteer to take this one?

**Comment by grgia** [comment]
WEB issue - https://github.com/Expensify/App/issues/26777

**Comment by grgia** [comment]
Bump @luacmartins

**Comment by luacmartins** [comment]
Coming back from ooo. Gonna try to work on this today

**Comment by luacmartins** [comment]
This is done.
