### ISSUE TITLE
[HOLD for payment 2023-09-21] [$500] Implement new layout for SecurityPage

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#26775]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open the security settings page

## Expected Result:
It should look like this:

<img width="170" alt="image" src="https://github.com/Expensify/App/assets/47436092/f7669866-467a-4cc6-ac1f-8a4260b14665">

and should be implemented using the `IllustratedHeaderPageLayout` component. The asset for the safe animation lottie JSON file can be found here:

[Safe.json.zip](https://github.com/Expensify/App/files/12524501/Safe.json.zip)

The correct background color is `ice500` or `#4ED7DE`

## Actual Result:
It looks like this:

<img src="https://github.com/Expensify/App/assets/47436092/be4ec6d1-9f1d-4ba4-91f9-dcf8d2fb93c1" alt="" width="200" />

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179e9954261696fde</li>
        <li>Upwork Job ID: 1699055159124353024</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26507971</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
@roryabraham I would love to do a PR for this issue

**Comment by roryabraham** [comment]
Please use our standard proposal template.

**Comment by roryabraham** [comment]
@getusha your proposal does not provide sufficient detail

**Comment by roryabraham** [comment]
@hungvu193 missing considerations for adding the lottie animation asset

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement new layout for securitypage

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
Add `IllustratedHeaderPageLayout` as the wrapper component and pass `View` of the menuItems inside it. In the `IllustratedHeaderPageLayout` set the prop values respective to the security page(considering the right animation file and bg color defined in the themecolors).
```
       <IllustratedHeaderPageLayout
            title={translate('initialSettingsPage.security')}
            onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS)}
            illustration={LottieAnimations.ExpensifyLounge}
            backgroundColor={'#4ED7DE'}
        >
            
        </IllustratedHeaderPageLayout>
```
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/settings/Security/SecuritySettingsPage.js#L56-L66

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
Also, just to set expectations here, this PR will be subject to the ongoing merge freeze

**Comment by trjExpensify** [comment]
👋 @hungvu193 @narefyev91 looks like this needs a bit of clean-up: https://github.com/Expensify/App/issues/27453

**Comment by trjExpensify** [comment]
Comparisons: 

![IMG_0356](https://github.com/Expensify/App/assets/16232057/6aa8a97c-572f-47ce-92ac-fb1b40dbc60b)
![IMG_0355](https://github.com/Expensify/App/assets/16232057/7448a6f1-1deb-4f4a-aa48-de88e9a61d5e)

**Comment by roryabraham** [comment]
Working on cleanup now

**Comment by roryabraham** [comment]
follow-up PR is ready for review [here](https://github.com/Expensify/App/pull/27482)

**Comment by maddylewis** [comment]
payment this week

**Comment by maddylewis** [comment]
is payment for this happening over here? https://github.com/Expensify/App/issues/27487

**Comment by roryabraham** [comment]
@maddylewis unless I'm missing something I think this is separate from https://github.com/Expensify/App/issues/27487 so we should be able to pay this out. However, this technically caused a regression, so we should only pay 50%.

**Comment by maddylewis** [comment]
## Payments
- [ ] @hungvu193 - $250 (Upwork)
- [ ] @narefyev91 - $250 (Upwork)

**Comment by maddylewis** [comment]
@narefyev91 - could you link your Upwork profile here? im having a tough time hiring you to this job - ty!

**Comment by narefyev91** [comment]
> @narefyev91 - could you link your Upwork profile here? im having a tough time hiring you to this job - ty!

Hey @maddylewis ! I'm from Callstack - no needs any payment with Upwork

**Comment by maddylewis** [comment]
oops! my b, thanks for clarifying!

**Comment by maddylewis** [comment]
paid!
