### ISSUE TITLE
[$500] Web - The modal flickers when the "Pay" button is pressed the 2nd time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26787]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Create a new workspace chat
3. Click on Actions > Request money > Next
4. Click on pay button twice

## Expected Result:
The modal should close when the "Pay" button is clicked the 2nd time

## Actual Result:
 It flickers and remains open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/621f2588-c41e-496a-8ffe-2c365fd7c622

https://github.com/Expensify/App/assets/93399543/bf5c3b33-fcaf-4d52-b956-ad651d469992

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693484019563759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181f1c810dafe3929</li>
        <li>Upwork Job ID: 1699171947679485952</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Reproduced.

**Comment by narefyev91** [comment]
Proposal from @ishpaul777 looks good to me https://github.com/Expensify/App/issues/26787#issuecomment-1706841720
🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment]
@jasperhuangg mind signing off on this proposal when you have a sec? TY!

**Comment by jasperhuangg** [comment]
Hey guys, sorry to swoop in here at the last minute, but I don't think we really need to be spending our time/money fixing this. It seems like there are other ways to close the popover, and this really doesn't hinder user experience at all. Closing

**Comment by ishpaul777** [comment]
@jasperhuangg If you notice the "pay with Expensify" button toggles popover and all other popovers are toggle popovers, i would say you should reconsider fixing this, as this has a very simple and straightforward fix, bounty can be adjusted

**Comment by ishpaul777** [comment]
Hey @jasperhuangg @joekaufmanexpensify, sorry for bumping again but i don't think closing a issue is fair for a contributor when a proposal is selected, contributor already has spend some effort finding a solution, I don't find reason for closing issue sufficient when the solution is perfect.

>  I don't think we really need to be spending our time/money fixing this.
