### ISSUE TITLE
 Dev: Web - CTRL + SHIFT + K, CTRL+ K and then CTRL + SHIFT + K close everything

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26782]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click CTRL + SHIFT + K
3. Click CTRL + K
4. CTRL + SHIFT + K
5. Observe the result

## Expected Result:
The new search group RHN should be opened

## Actual Result:
CTRL + SHIFT + K, CTRL+ K and then CTRL + SHIFT + K close everything

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.63.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/93fae88b-3c39-475c-b57c-2ac33362ce2c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693917418942659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Based on the Slack chat - this is no longer happening - https://expensify.slack.com/archives/C049HHMV9SM/p1693936499717209?thread_ts=1693917418.942659&cid=C049HHMV9SM

Closing without action
