### ISSUE TITLE
[$500] Web - After error in task title, typing anything results in typing in different report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click assign task
3. Enter any title, select anyone for share somewhere and complete the process
4. Visit the task message, click on title to open edit title page for task
5. Remove the text and click enter, it should display 'Please enter a title' error
6. Start typing anything and observe in LHN that app starts typing that in a random report (It will display the pencil icon on that report)
7. Visit that report to confirm that app has written the text we typed in step 6 into that report

## Expected Result:
App should not type text to any random chat when error in triggered on task title

## Actual Result:
App starts typing text to any random chat when error in triggered on task title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2d3e5658-b59b-404b-8904-bcb7a66f21e8

https://github.com/Expensify/App/assets/93399543/ad4cfa6b-eaa0-4e9f-a1f8-04384bc22074

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693482500541219
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faa5b5227d633870</li>
        <li>Upwork Job ID: 1699230848578371584</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Hmmm, this is kinda odd. 

I tested this following the steps and the first time I was able to recreate the pencil icon showing the typing in a different report. I forgot to take a screenshot of this confirming the behavior. 

Since I forgot the screenshot I marked the task as complete and then tried it again so I could document it properly and now I can't get it to happen again no matter what I do.

**Test 1**
<img width="2063" alt="image" src="https://github.com/Expensify/App/assets/10925636/6272739a-4458-4485-aca5-8d9e1df6a2a8">

**Test 2**
<img width="2500" alt="image" src="https://github.com/Expensify/App/assets/10925636/efac7390-850b-43dd-83ea-56ecc6432a82">

I've tried signing out and signing in again but I can't recreate the behavior with the dang pencil again.

**Comment by strepanier03** [comment]
I'm going to send on to External since I was initially able to recreate this. 

However, I have now tried this from three different accounts and only the very first attempt did I get the pencil icon to appear when editing the task title, otherwise I can't recreate it any longer

**Comment by strepanier03** [comment]
Aaaah, figured it out finally!

This is recreatable but you can't click into the title to start typing, you have to do it with the title field unfocused.

**Comment by strepanier03** [comment]
Okay here you go, fresh vid recreating it. It even brings up a random chat to apply the pencil to if you don't have one in your LHN. 

I don't have an onscreen keyboard visible but this is easy to repro quickly for individual testing as well. 

https://github.com/Expensify/App/assets/10925636/a295d674-7bea-4ac5-aee7-0001d39ce635





https://github.com/Expensify/App/assets/10925636/0154d2a3-b453-45fd-a54e-d5ea7d08f83c

**Comment by strepanier03** [comment]
Thanks @tienifr for the dupe find, I didn't connect the two. 

Since this is a week newer I'm going to close this dupe out.
