### ISSUE TITLE
Chat - Wrong email is entered to composer when select a user from mention list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with user A, and user B on two different windows
2. Add secondary login email C to user B account
3. Set secondary logging email C as a default contact method
4. Open a tab where user A is signed in
5. Write @, and start typing email account C
6. Click on email account C from the suggestion list

## Expected Result:
Email account C should be entered to composer

## Actual Result:
Email account B, which is the new secondary login account of C is entered to composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** https://expensify.slack.com/archives/C049HHMV9SM/p1693288464831169

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cddf1099-c4e3-4fb1-a281-4401a3d0629e

https://github.com/Expensify/App/assets/115492554/80327c7a-cada-41bf-8512-f14e4dc46619

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693288464831169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This looks like a backend issue. User A receives the pusher event for the default contact change of user B but that pusher event includes only `displayName`, doesn't include `login`

**Comment by MitchExpensify** [comment]
I don't think this is worth solving at this point. It is related to having two windows open at the same time and the timing needed for this to happen feels very edge case
