### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Chat - Parent thread disappears in LHN when deleting the thread first chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26791]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a message
3. Reply in thread of this message. Name it thread 1
4. In thread 1 send a message and reply in thread of this message. Name it thread 2
5. In thread 2 delete the thread first chat that is the parent action of thread 2

## Expected Result:
Thread 1 shouldn't disappear in LHN

## Actual Result:
Thread 1 disappears in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.63-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ca0b44db-bf00-48cc-9f80-b7ee36e4acc4

https://github.com/Expensify/App/assets/115492554/f6ac2131-5491-49ad-b149-3ef00a88af50

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dukenv0307

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693457193765209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115b0069b17fafa3d</li>
        <li>Upwork Job ID: 1701866107897614336</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26665115</li>
<li>dukenv0307 | Reporter | 26665117</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Proposal by: @dukenv0307
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693457193765209
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Parent thread disappears in LHN when deleting the thread first chat
### What is the root cause of that problem?
When we delete the thread first chat because the parent report of this thread is also a thread, `shouldReportBeInOptionList` function return `false`. And then it's hidden
https://github.com/Expensify/App/blob/a5ab459e731badcce4faea56fbce074a54f8495b/src/libs/ReportUtils.js#L2781-L2783
### What changes do you think we should make in order to solve the problem?
For the thread report, we should check if at least one child report of this report has some comments or if the currentReportId is a child of this report, we will not hide this thread report.
1. In `ReportActionsUtils`, create a function to check if at least one child report of this report has some comments
```
function isChildReportHasComment(reportID) {
    const reportActions = allReportActions[reportID];
    if (_.isEmpty(reportActions)) {
        return false;
    }
    return _.some(reportActions, (reportAction) => (reportAction.childVisibleActionCount || 0) > 0);
}
```
2. In `ReportUtils`, create a function to check whether we should hide the thread report or not
```
function shouldHideThreadReport(report, currentReportId) {
    const parentReport = getParentReport(getReport(currentReportId));
    return parentReport.reportID !== report.reportID && !ReportActionsUtils.isChildReportHasComment(report.reportID)
}
```
3. Change the condition here by useing `shouldHideThreadReport` function
```
if (isChatThread(report) && shouldHideThreadReport(report, currentReportId) && isEmptyChat) {
    return false;
}
```
https://github.com/Expensify/App/blob/a5ab459e731badcce4faea56fbce074a54f8495b/src/libs/ReportUtils.js#L2781-L2783
### What alternative solutions did you explore? (Optional)
NA

**Comment by CortneyOfstad** [comment]
I don't think this is a bug as this is standard practice in other messaging services (Slack, WhatsApp, etc). Only when you delete the comment will the full thread then disappear. 

However, I want to get additional eyes on this to confirm.

**Comment by Julesssss** [comment]
I'm a bit confused by the steps, but it sounds like the bug is that the thread **IS** dissapearing?

> The parent thread shouldn't disappear if we are open child report or child report still has the comment

**Comment by CortneyOfstad** [comment]
Yeah, I had some confusion as well as that is not how I interpreted it. @dukenv0307, can you work with @izarutskaya to update the original comment steps to make them a bit clearly? TIA!

**Comment by Julesssss** [comment]
> Expected Result: Thread 1 shouldn't disappear in LHN

I kinda of expect this actually. What's the problem here?

**Comment by Julesssss** [comment]
Still deciding whether this is a bug...

**Comment by narefyev91** [comment]
Proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/26791#issuecomment-1716867488
🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
Bump for checklist completion and payment

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - issue was not coming from regression - just missing functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by CortneyOfstad** [comment]
@dukenv0307 has been paid as both reporter and contributor 👍 

Total payment is **$550** — $50 for reporting and $500 as contributor (did not qualify for bonus)
