### ISSUE TITLE
[HOLD for payment 2023-10-09] [Wave 6: Tags] CRITICAL - Frontend: editing a tag and billable flag

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#26793]
HELD on:
* https://github.com/Expensify/App/issues/26126
* https://github.com/Expensify/App/issues/26128

## Design doc section
* https://docs.google.com/document/d/1eXGKhdUP98f6RUVYpRzxLi49El9Rizeqq-EYjrF24tU/edit#heading=h.d4r80gwxgf3r

## Implementation
- [x] https://github.com/Expensify/App/pull/27950
- [x] https://github.com/Expensify/App/pull/27875
- [x] https://github.com/Expensify/App/pull/28151
- [x] https://github.com/Expensify/App/pull/28493

**Comment by amyevans** [comment]
Not ready to be worked on yet

**Comment by waterim** [comment]
Hello, Im Artem from Callstack - expert group
And I would like to take this one

**Comment by waterim** [comment]
I have one question, do we want to have toggler in a new screen([MenuItemWithTopDescription](https://github.com/Expensify/App/blob/a87b802a09c48de7274855af56e27ab544463ef6/src/components/MenuItemWithTopDescription.js)) or as we have in create moneyRequest? 
<img width="372" alt="image" src="https://github.com/Expensify/App/assets/39777589/a79f67e2-f8e1-4c72-84ef-2d694fbca609">

cc: @amyevans @puneetlath

**Comment by puneetlath** [comment]
We want to leave it as it is in that image. No need for a new screen.

**Comment by jjcoffee** [comment]
Just noting that I [reviewed](https://github.com/Expensify/App/pull/27950#issuecomment-1731253363) https://github.com/Expensify/App/pull/27950 (wasn't sure if the automation worked).

**Comment by puneetlath** [comment]
Payment summary: 
$500 - @parasharrajat - https://github.com/Expensify/App/pull/28151 (to be paid via NewDot)
$500 - @jjcoffee - https://github.com/Expensify/App/pull/27950 (to be paid via Upwork)

@jjcoffee I've sent you an [Upwork offer](https://www.upwork.com/nx/wm/offer/26974454). Please accept it and comment here when you have. 
@parasharrajat please request via NewDot. Please comment here once you've opened the request. 

Thanks y'all!

**Comment by jjcoffee** [comment]
@puneetlath Accepted, thanks!

**Comment by jjcoffee** [comment]
Just flagging that I've reviewed another linked [PR](https://github.com/Expensify/App/pull/28493).

**Comment by puneetlath** [comment]
Updated payment summary: 
$500 - @parasharrajat - https://github.com/Expensify/App/pull/28151 (to be paid via NewDot)
$500 - @jjcoffee - https://github.com/Expensify/App/pull/27950 (paid via Upwork)
$500 - @jjcoffee - https://github.com/Expensify/App/pull/28493 (to be paid via Upwork)

@parasharrajat can you open a request in NewDot and comment here when you have? 
@jjcoffee I sent you another offer: https://www.upwork.com/nx/wm/offer/27101276

**Comment by jjcoffee** [comment]
@puneetlath Thanks, accepted!

**Comment by amyevans** [comment]
> @parasharrajat can you open a request in NewDot and comment here when you have?

Friendly bump @parasharrajat 😄

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on summary.
