### ISSUE TITLE
 Thread does not appear immediately on receiver side  in workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces
2. create a workspace if not created
3. go to members
4. add userB
5. go to workspace and userB chat
6. send any message
7. hover on message and click on reply thread option
8. send any message in thread
9. check the message on userB side

## Expected Result:
 thread should be appear immediately
## Actual Result:
 thread does not appear immediately

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/5133f9a3-1c6e-4cde-b087-d1834f538dad

https://github.com/Expensify/App/assets/38435837/800984a7-8158-40ce-abe9-c025ddbde39b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693291656010449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147d0b13d09934fa4</li>
        <li>Upwork Job ID: 1709166611672600576</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
Hm, yeah I would say that this is more of a performance issue that we will optimize for

**Comment by muttmuure** [comment]
Getting to this tomorrw. Maybe we can bundle it into performance improvements

**Comment by muttmuure** [comment]
I think that this will be handled by #reliable-updates, let's close it and reopen if it still occurs when that project is closed out
