### ISSUE TITLE
Profile - Enterd magic code is not cleared when clearing error message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Profile avatar
2. Click on 'Profile'
3. Click on 'Contact methods'
4. Click on 'New contact methods' button
5. Enter email & click on 'Add' button
6.  Open the newly added contact method
7. Enter wrong magic code
8. Click on 'Close' icon of the error message

## Expected Result:
Entered magic code should be cleared from magic code input field

## Actual Result:
Entered magic code is not cleared from magic code input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.63-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d5ea129d-32c1-457c-a6de-5bbc96b96baf

https://github.com/Expensify/App/assets/115492554/715753cc-20aa-43d5-8736-985f45a54c89

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693290501329629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment]
This doesn't feel like a candid bug to me. It is clear and functional, and there's room to argue the existing behavior is useful.
