### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] After Logout, using CMD + J only generates 2 shortcuts in the pop-up (instead of the full list)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. sign-out if you are logged in.
2. press `cmd+j` to open shortcut modal without page reload.
3. now you see list off all shortcuts in modal.
## Expected Result: 
only ESC and Shortcut(" CMD+J") keys should be shown
## Actual Result: 
All Shortcuts are shown here
Platforms: MacOS / Chrome / Safari

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/86624327-4448-4829-91a5-9ac15b28895b

![Snip - New Expensify - Google Chrome (5)](https://github.com/Expensify/App/assets/43996225/bde752c4-9f73-46a5-9331-11e2ba9bd1c0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Charan-hs
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692612279461809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124cd08463cfd5f26</li>
        <li>Upwork Job ID: 1699578589047709696</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26826364</li>
<li>Charan-hs | Contributor | 26826367</li>
<li>Charan-hs | Reporter | 26826368</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal by @Charan-hs
### Please re-state the problem that we are trying to solve in this issue.
All keyboard shortcut shows up in modal after Logout
### What is the root cause of that problem?
When we are logged in or logged out we are unsubscribing the event handlers here.
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/KeyboardShortcut/index.js#L83-L87
but When unsubscribing, we remove event listeners but not shortcuts from the variable `documentedShortcuts`. Even though I have unsubscribed, the shortcuts are still present in `documentedShortcuts`.
### What changes do you think we should make in order to solve the problem?
Here,
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/KeyboardShortcut/index.js#L83-L87
When unsubscribed we can remove the values present in `documentedShortcuts` by `displayname` (key).
```js
    lodashUnset(documentedShortcuts,displayName);
//or
    documentedShortcuts = _.omit(documentedShortcuts,displayName);
//or
   documentedShortcuts[displayName] = {} // here we can return null or {}
//We can use the delete method also based on your request.
```
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Able to repro!

**Comment by jliexpensify** [comment]
@Charan-hs @kavimuru I am confused at this issue. Here is what you've written:

>Expected Result:
>only ESC and Shortcut(" CMD+J") keys should be shown

>Actual Result:
> All Shortcuts are shown here

Should these 2 be reversed? i.e. when you're logged in, you see all the shortcuts, but when you're logged out, you only see 2 shortcuts. or are yousaying we should only ever see 2 shortcuts? (which doesn't sound right to me)

**Comment by ishpaul777** [comment]
@jliexpensify, I think there are 2 bugs here -
1. after signing out all shortcut list shows in modal, if page reloaded the then only ESC and Shortcut(" CMD+J") keys should be shown

Not reported here but i noticed, i believe can be handled with this issue.
2. when reloaded and first time open shortcut modal with CTRL + j only one option shown, closing and reopening modal shows 2 options

**Comment by jliexpensify** [comment]
@ishpaul777 thanks for reporting this one:

>2. when reloaded and first time open shortcut modal with CTRL + j only one option shown, closing and reopening modal shows 2 options.

I also noticed this in my testing!

After chatting to @kadiealexander I think I got confused initially, [so ignore this comment](https://github.com/Expensify/App/issues/26829#issuecomment-1707527444)! Going to mark this as external, and I think we should also fix the 2nd issue outlined above.

**Comment by jliexpensify** [comment]
I think this is a call for @ntdiary and @mollfpr to make!

**Comment by mollfpr** [comment]
I agree with holding this; the result will be better after merging the PR on  #26809.

**Comment by jliexpensify** [comment]
Cool, thanks! On hold now - please ping me when you want this off hold.

**Comment by jliexpensify** [comment]
Testing on v1.3.70-2 now. This is what is ee (without a page reload):

![image](https://github.com/Expensify/App/assets/30815269/a3634b19-7f8f-494e-be09-bedd8e97826f)

**Comment by jliexpensify** [comment]
@Charan-hs @ntdiary so based off the Expected Result, it doesn't seem like this is fixed?

**Comment by charan-gowda007** [comment]
Friendly bump @jasperhuangg @jliexpensify

**Comment by jliexpensify** [comment]
@Charan-hs it'll be @jasperhuangg who assigns you, not me!

**Comment by jasperhuangg** [comment]
Their proposal makes sense to me! Assigned

**Comment by hayata-suenaga** [comment]
I don't know why I was auto-assigned to the PR 🤔 

@jasperhuangg I unassigned myself and assigned you as you're assigned to this issue 🙇

**Comment by jliexpensify** [comment]
Payment Summary:

- Reporter / Contributor: @Charan-hs $50 + $500 + $250 = $800
- C+: @ntdiary $500 + $250 = $750

[Upworks Job](https://www.upwork.com/jobs/~0124cd08463cfd5f26)

**Comment by jliexpensify** [comment]
@ntdiary bump to complete the checklist please!

**Comment by jliexpensify** [comment]
@Charan-hs - paying now. For future reference, there's no need to submit work for review. Thanks!

**Comment by jliexpensify** [comment]
Everyone has been paid and job is closed!
