### ISSUE TITLE
Dev - Request money: Glitchy transition between 'Manual' and 'Distance' tab

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' menu
2. Click on 'Request money'
3. Click on 'Distance' tab

## Expected Result:
 Transition should be smooth

## Actual Result:
Glitchy transition between tabs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a3f6578c-2547-424f-b499-996f32ebd892

https://github.com/Expensify/App/assets/115492554/bc43c2ab-2035-4e5f-96a8-004afd5aa53f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693297413366559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
I think this has been fixed! I'm unable to reproduce on staging v1.3.67-1
