### ISSUE TITLE
Give UI feedback when the location is being fetched

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a workspace chat (create a workspace if you don't have one yet)
2. Click the "+" button next to the text composer
3. Click "Request money"
4. Click "Distance"
5. Click "Start"
6. Imitate a poor network condition (on chrome, for example, you can do this on the developer console)
7. Type an address
8. Click a suggested address
9. Confirm that there is no UI feedback indicating the location is being fetched. Wait for the screen to go back to the previous one (Distance Request screen with the waypoint list)

## Expected Result:
There should be some kind of UI feedback

## Actual Result:
User has no idea what's happening

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/98560306/8f29469c-6b6c-4140-b082-163976393df2

**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
@shawnborton Please check [the two choices](https://github.com/Expensify/App/pull/26546#issuecomment-1705082680) suggested by a contributor working on the "Current Location" PR.

"Use current location" button is clicked In the videos attached to the linked comment. The same issue also happens when an address suggestion is clicked under a poor network condition.

Please let me know what is the best approach to let the user know that the current location / address is being fetched?

**Comment by hayata-suenaga** [comment]
> With a loader, it would look something like this
> 
> With Loader
> With a label update, it would look something like this.
> 
> With Label update
> Label update gives us the flexibility to use the button component in other places directly, while with a loader we will have to set it up in parent components where the `UserLocationButton` is used.
> 
> Important: If the location permission is denied then, we might see the loader/label flicker. This is because there won't be any delays in response from the `getCurrentLocation`

**Comment by shawnborton** [comment]
I like the idea of just replacing the dropdown list with a small loading spinner that is horizontally and vertically centered.

I am assuming the issue is when you start typing something, yet you don't see results in the suggestions that reflect what you typed?
<img width="215" alt="image" src="https://github.com/Expensify/App/assets/2319350/8f24912b-5980-4c0d-bc09-30ea6801905a">

cc @expensify/design too

**Comment by hayata-suenaga** [comment]
> I am assuming the issue is when you start typing something, yet you don't see results in the suggestions that reflect what you typed?

The issue is that there is no UI feedback after the user clicks one of the suggestions until the coordinates of the address are fetched and the screen goes back to the distance request page.

Note that in the video I attached, after I click one of the suggested address, there is a moment that there is nothing happening until the application navigates back to the previous screen.

**Comment by shawnborton** [comment]
> The issue is that there is no UI feedback after the user clicks one of the suggestions until the coordinates of the address are fetched and the screen goes back to the distance request page.

Hmm so could we just immediately take the user back to the previous screen, but have some kind of loading spinner appear over the map image to indicate that the map is loading?

**Comment by hayata-suenaga** [comment]
I gonna close this issue so that we can do all the design related discussions over in [this PR](https://github.com/Expensify/App/pull/26546#issuecomment-1705082680).
