### ISSUE TITLE
[$1500]  Notification - Notification about inviting a user to WS redirects to an error page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Log in with account A
3. On the device with account A, close the app (Kill the app)
4. On the device with account B, create a WS
5. Invite user A
6. On user A device, open the group invitation notification

## Expected Result:
When clicking on the group invitation notification, the user should be redirected to the WS room

## Actual Result:
When clicking on the WS user invitation notifications redirects to a page with an error "Hmm.... it's not here."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3ef0481d-07cf-4bee-84b0-3d245cadc0d0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01553a3926c7c4a7d6</li>
        <li>Upwork Job ID: 1699477208086028288</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Confirmed on iOS.

**Comment by garrettmknight** [comment]
Still waiting for proposals.

**Comment by garrettmknight** [comment]
Updating the bounty!

**Comment by eVoloshchak** [comment]
Not overdue, awaiting proposals

**Comment by garrettmknight** [comment]
Let's see if this gets us anywhere.

**Comment by programmerkenzi** [comment]
I tested using version 1.3.7.0 downloaded from the app store, and this bug no longer appears. I've attached the test video. Do we still need to fix it in version 1.3.64-0?

https://github.com/Expensify/App/assets/68736908/91fe456d-2f0c-49ff-8e2d-c8dc3f1f43da

**Comment by garrettmknight** [comment]
Ah, just tested and you're right. It's fixed. Closing.
