### ISSUE TITLE
[$500] [HOLD for payment 2023-11-21] [Tracking] Start using DotLottie animation assets instead of lottie JSON

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#26857]
### Problem

We are scaling up our use of lottie animations across our app. However, lottie JSON files are large and heavy. For example, we've seen performance issues with the lounge page animation, which is about 4Mb.

### Solution
Let's adopt the new [dotlottie file format](https://dotlottie.io/) for our lottie animations to save on bundle size, make animations load faster on web, and make them more lightweight to run. It's likely that the new file format will result in files about 10% the size of the current ones.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01177ccd6f38fa029b</li>
        <li>Upwork Job ID: 1729581933567508480</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by roryabraham** [comment]
Fortunately lottie-react-native now supports dotlottie 🎉 

The next step is to just get our web implementation in place. Posted about this in slack [here](https://expensify.slack.com/archives/C04878MDF34/p1693990813096389)

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/issues/26871

**Comment by roryabraham** [comment]
Pinged for updates in https://github.com/Expensify/App/issues/26871

**Comment by roryabraham** [comment]
@kosmydel has a draft PR against the upstream but is OOO this week. I'm also working with Emilio and Matin to make sure they're paid for their work in lottie-react-native for iOS and Android

**Comment by roryabraham** [comment]
Pinged for an update in the lottie web task. Working on paying lottie-react-native maintainers for their work in adding DotLottie support.

**Comment by roryabraham** [comment]
Web support PR was approved three days ago

**Comment by roryabraham** [comment]
I see there's a draft PR, left a review on it to request that we first implement web support for lottie in one PR, then follow up with another to switch to `.lottie` files

**Comment by roryabraham** [comment]
This is done but we need to make a C+ payment to @mananjadhav, marking as `New Feature` to move arrange that.

**Comment by AndriyKas** [comment]
Actually, yes, DotLottie player should help you, but not 100%. 
There is a high probability that the person who created this Lottie file optimized it in the program in which they created it.
Let me just take a look at what your files look like and what file size they have

I am a motion designer with a skill in web development and have already solved about 10 similar problems related to lottie optimization

**Comment by mananjadhav** [comment]
I've raised a request on NewDot for the same.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.
