### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Deeplinks except chat reports are not working on web

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Log out
2. Go to any app URL (`/enable-payments`) or /concierge or some other deeplink activated route
3. Log in

## Expected Result:
Describe what you think should've happened

You are signed in and logged into that route

## Actual Result:
Describe what actually happened

You are in normal chat report/ not deeplinked to the page you wanted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/36083550/1de36497-4b8f-4eaf-920f-5531d3414db5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693478978353389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe24c8c7021a0486</li>
        <li>Upwork Job ID: 1699316717752012800</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26522318</li>
<li>tienifr | Reporter | 26522320</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
Really surprised we dont have regression tests for these, I thought concierge has regression tests

**Comment by mountiny** [comment]
I thought it might be coming from that PR thanks

**Comment by b4s36t4** [comment]
@mountiny you're going fix this? or you're looking for proposals?

**Comment by mountiny** [comment]
> A workaround can be adding a condition to skip reseting the navigation state for unauthorized route 😄

would anonymous accounts for public chats work fine? they have a session established so probably yes

**Comment by mountiny** [comment]
Feel free to make a proposal, @adamgrzybowski  for review

**Comment by mountiny** [comment]
@hungvu193 I thinnk your proposal makes sense, can you please raise a PR and we can make a test build to validate all the flows

**Comment by adamgrzybowski** [comment]
Looks good to me too

**Comment by adamgrzybowski** [comment]
@mountiny @b4s36t4  I've done some testing and it looks like `navigationRef.getRootState()` to `navigationRef.getState()` can give different results. 

In some cases, I can see that the state from `navigationRef.getState()` is lacking state for nested navigators 

I am not sure why though.

I would be cautious with switching to `getState()`

**Comment by mountiny** [comment]
@hungvu193 can we try to fix this as part of this PR, this is still malfunctioning deeplink imho

**Comment by mountiny** [comment]
I see, I think there is lots of flows related to the concierge as well as transition from oldDot when clicking the concierge widget, I think that might also be influenced by this change

In that case I think we can keep that logic separate if in this PR the chat will eventually go to the correct concirge chat

**Comment by mountiny** [comment]
@sumairq they will respond to you and the invite will be handled that way, thanks for patience

**Comment by abekkala** [comment]
### Payments for Sept. 19
* Issue reported by: @tienifr [$50] - Upwork
* Selected Proposal for fix: @hungvu193   [$1000] + [$500 PR bonus] - Upwork
* C+ Review: @eVoloshchak [$1000] + [$500 PR bonus] - Manual Request

**Comment by eVoloshchak** [comment]
@abekkala, I didn't participate in fixing this, could you unassign me please?

**Comment by abekkala** [comment]
@mountiny Hey Vit, Can you confirm who the C+ reviewer was on this? 
Melvin Bot noted Eugene several times and noted the quick PR for bonus

<img width="744" alt="Screenshot 2023-09-19 at 9 23 59 AM" src="https://github.com/Expensify/App/assets/11966460/66c547be-3e70-4c62-b38c-8ec452389ba4">
<img width="751" alt="Screenshot 2023-09-19 at 9 23 07 AM" src="https://github.com/Expensify/App/assets/11966460/27d9c6c1-98d2-435e-8aee-a69d77b345f3">

**Comment by abekkala** [comment]
Thanks!

- Issue reported by: @tienifr [$50] - Upwork
- Selected Proposal for fix: @hungvu193 [$1000] + [$500 PR bonus] - Upwork
- C+ Review: @parasharrajat  [$1000] + [$500 PR bonus] - Manual Request for payment in EChat

**Comment by abekkala** [comment]
@tienifr and @hungvu193 payments have been made and contracts ended. Thank you! 🎉 

@parasharrajat have you already requested manually payment in EChat yet?

**Comment by mountiny** [comment]
Thanks everyone!

**Comment by lcsvcn** [comment]
This issue is still a blocker for this [bug fix](https://expensify.slack.com/archives/C049HHMV9SM/p1695655428909709) to be open?

@dhanashree-sawant reported it first [here](https://expensify.slack.com/archives/C049HHMV9SM/p1693324854860599), I noticed today that it is still reproducible on latest version and I have a proposal to fix this issue.

Thanks!

**Comment by mountiny** [comment]
@lcsvcn I dont think that is related to this issue, the bug report should be created separately for a new GH ticket

**Comment by lcsvcn** [comment]
It is related because it was a blocker to create the issue, if you check the slack thread

**Comment by lcsvcn** [comment]
Oh, I see. what is the correct link, please?

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @parasharrajat based on BZ summary.
