### ISSUE TITLE
Dev: Web - When selecting the "#admins room" option, the Concierge chat opens instead of the admins room chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with new account
- Click New Workspace in bottom left
- Click 'more' (three dots in far upper right)
- Click `Go to #admin room
- Observe `Concierge` at top of chat. 

## Expected Result:
Upon selecting the "#admins room" option, the admin room should open as intended

## Actual Result:
 Instead of the admin room, the Concierge chat opens unexpectedly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev v1.3.60-3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6a5e657e-012b-49ab-b340-adc505485cff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693556457425289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Will get to soon, it's a dev bug that needs repro so I'm assuming it's not super time sensitive.

**Comment by mallenexpensify** [comment]
Unable to reproduce, see vid below. @kbecciv can you please try? @aman-atg 👋 , can you please try again too?

**Comment by kbecciv** [comment]
I cannot check the Dev, but works on staging. Video attached 
Tested build is 1.3.72.6

https://github.com/Expensify/App/assets/93399543/91df9851-a240-45f1-be21-a1c931f11f78

**Comment by mallenexpensify** [comment]
Thanks @aman-atg and @kbecciv , gonna close
