### ISSUE TITLE
[$500] Workspace - Unable to invite via Expensifail account and Members list loads infinitely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > any workspace > Members > Invite
3. Invite a new expensifail account that is not registered with ND
4. Log out and log in again
5. Go to Settings > Workspace > any workspace > Members

## Expected Result:
In Step 3, user is able to invite member via expensifail account
In Step 5, the Members list loads without issue

## Actual Result:
In Step 3, user is unable to invite member via expensifail account. An error shows up
In Step 5, the Members list loads infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3265c4a7-6082-4fae-96ae-6315df0940a3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a224c107b131b83a</li>
        <li>Upwork Job ID: 1701370863371202560</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
I agree this should be fixed, applying labels to get a contributor on it!

**Comment by stephanieelliott** [comment]
Waiting for proposals

**Comment by akamefi202** [comment]
It looks like a BE issue. API call returns 404 error(Account not found).

**Comment by stephanieelliott** [comment]
Ah ok thanks @akamefi202! That does sound like a back end issue -- applying the `Internal` label so we can get an internal eng on this

**Comment by Julesssss** [comment]
is this just occuring for `@expensifail.com` invites? Or all domain invites? 

If its the former I'm not sure it's worth spending time on this bug. The workaround is just to create the user first, which any internal employee can easily do.

**Comment by Julesssss** [comment]
Still deciding whether this is worth fixing:

> is this just occuring for @expensifail.com invites? Or all domain invites?

**Comment by sobitneupane** [comment]
@Julesssss I don't think the issue exists for other domain. I was able to invite new member without any issue.

<img width="200" alt="Screenshot 2023-09-26 at 12 24 44" src="https://github.com/Expensify/App/assets/25876548/99f479ca-5335-440b-b802-091847d8ff3a">

**Comment by Julesssss** [comment]
@stephanieelliott I'm thinking we close this. There's no chance I'll be able to work on the backend part of this PR in the next month 😞

**Comment by stephanieelliott** [comment]
Ok yeah, I agree that this is super low priority given that it only affects internal users and there is a workaround. Let's close this.
