### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] mWeb - Opening smaller profile pic from request money details causes zoom in zoom out glitch

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User should have another user in recent chats that has profile pic which does not cover full width on opening
1. Open the app in android chrome
2. Click on plus and click on request money
3. Enter any amount and click next
4. Select the user with smaller profile pic
5. Click on user profile to open user details
6. Click on profile pic and observe that it zooms in and zooms out in few seconds

## Expected Result:
App should not glitch when opening smaller profile pic from user details page

## Actual Result:
App glitches when opening smaller profile pic from user details visited from details page of request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9217e3aa-f470-4e7f-a0d6-88e931d5a352

https://github.com/Expensify/App/assets/93399543/030bc1d2-febf-4839-b94a-81692105b861

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693559822391119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01845037b08588f72c</li>
        <li>Upwork Job ID: 1702059344831913984</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26743899</li>
<li>dhanashree-sawant | Reporter | 26743903</li>
</ul></li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
asking clarification question

https://expensify.slack.com/archives/C049HHMV9SM/p1694123811151679?thread_ts=1693559822.391119&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
Bumping slack

**Comment by kevinksullivan** [comment]
confirmed reproducible and moving forward.

**Comment by kevinksullivan** [comment]
Hey @sobitneupane what do you think about the proposal above?

**Comment by sobitneupane** [comment]
Thanks for the proposal @dukenv0307 
Proposal from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reveiwed

**Comment by Li357** [comment]
@dukenv0307 Proposal looks good, thanks!

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/9279
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/9279/files#r1349952938
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is an edge case missed while introducing new feature.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/26882#issuecomment-1729022399

Since it is eligible for urgency bonus, requested $750 for payment in newDot.

**Comment by kevinksullivan** [comment]
Payment summary

Reporter: @dhanashree-sawant $50
Contributor: @dukenv0307 $750
C+: @sobitneupane $750 (in NewDot)

**Comment by kevinksullivan** [comment]
Paid out @dhairyasenjaliya and @dukenv0307

**Comment by JmillsExpensify** [comment]
$750 payment approved for @sobitneupane based on BZ summary.

**Comment by JmillsExpensify** [comment]
Also did the regression test get added? Re-opening to confirm.

**Comment by kevinksullivan** [comment]
Ah good catch, adding.
