### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web -  Editing request money while the user paid the requested money will still notify the change

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26880]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click '+' FAB from user A
2. Click on  request money and request any amount from user B
3. When the request  opens for user A go to editing page and click on the amount
4. Edit the amount from user A and leave it unsaved
5. Pay the request from USER B
6. Immediately after you paid the request save the change you made from User A in step 4

## Expected Result:
No change should be reflected

## Actual Result:
A notification that shows change will appear in the edit room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4fdc9922-33a6-4095-b42a-8b4bb6a838a1

https://github.com/Expensify/App/assets/93399543/0a3a936f-f217-4872-834f-708b2eb0f7dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693558160950359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9b7308912bc30e7</li>
        <li>Upwork Job ID: 1702482062216015872</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26743504</li>
<li>lidiyakelay | Reporter | 26743507</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment]
I've run out of time today and will test soon.

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
@ntdiary - can you please review if the proposal will fix this issue? Thanks!

**Comment by alexpensify** [comment]
@ntdiary - all good, we are in different timezones. 😄 Thanks for the quick review here.

**Comment by roryabraham** [comment]
@namhihi237's proposal LGTM, and I agree `iou.error.genericEditFailureMessage` looks like the right message to use 👍🏼

**Comment by namhihi237** [comment]
@ntdiary @roryabraham While executing the step, I found an error in addition to the above one on current main and stg.
Steps:
1. Click the FAB button from user A
2. Click on request money and request any amount from user B
3. User A turns off the network
4. User B paid the request money
5. User A Edit amount and back online, Sometimes it is observed that messages are located in the wrong position

This error will not occur when there is any message before going offline.
1. Click the FAB button from user A
2. Click on request money and request any amount from user B
3. User A edit amount and save
4. User A turns off the network
5. User B paid the request money
6. User A Edit amount and back online

I think this error is not within the scope of this PR. What do you think? If agree, I will report a bug for this error and this will fix it in another issue.

Detail video.

https://github.com/Expensify/App/assets/39086067/8a8dac03-04e2-4b26-8a48-8f04c380da5f

**Comment by roryabraham** [comment]
> I personally think we can create a separate issue to investigate it

Sure. @namhihi237 you should post it in #expensify-bugs so you can get the reporting bonus.

**Comment by alexpensify** [comment]
@ntdiary - please complete the checklist to prepare for the payment date. Thanks!

**Comment by alexpensify** [comment]
Alright, everyone has been paid here. Great work!
