### ISSUE TITLE
Request money - User can change amount before app finishes scanning receipt

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. click on '+' icon & click on 'request money'
4. Click on 'Scan' > click on 'Choose file' > Click on 'Request'
5. Click on the IOU preview component > Click on the IOU preview component again
6. Click on 'Amount' > add value & click on 'Save'

## Expected Result:
Amount field should be disabled until the system finishes scanning the receipt

## Actual Result:
Amount field is not be disabled until the system finishes scanning the receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-2 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f74f63e7-4778-43c9-b0b8-8ea40ca54548

https://github.com/Expensify/App/assets/115492554/14599b55-e6de-4210-a360-921b4c92f842

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693313485044349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by saisixthblock** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
User can change the amount before scanning is finished.

**What is the root cause of that problem?**
We're not checking if the receipt is being scanned in the MoneyRequestView.

**What changes do you think we should make in order to solve the problem?**
We should disable the menu item until receipt scanning completed.

**Comment by laurenreidexpensify** [comment]
clarifying if this expected here https://expensify.slack.com/archives/C057F53HR40/p1694078670332749

**Comment by laurenreidexpensify** [comment]
This isn't a bug, it's expected behaviour to be able to edit the expense and manually edit the amount should. you wish to do so
