### ISSUE TITLE
[$500] Web - Visiting wrong description/merchant link displays blank RHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click request money
3. Enter any amount and select any user and complete the process
4. Open the request money page by clicking twice on request money message
5. Click on description/merchant and copy the link
6. Paste it into any report and modify the report by adding or removing any character eg: if link is: https://staging.new.expensify.com/r/1758292653775719/edit/description , modify it like this https://staging.new.expensify.com/r/1758292653775719/edit/descriptions
7. Send the modified link
8. Open the link and observe that it displays blank RHN

## Expected Result:
App should not have any link which will take the user to blank RHN or any blank page

## Actual Result:
Description/merchant edit link if modified and visited then it displays blank RHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cb626325-f66a-4e00-b8b6-d6acb54e59dc

https://github.com/Expensify/App/assets/93399543/bb5e40cf-ebf1-4f8e-8c07-2c2c70489502

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693680596106879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01047be634d7f302b0</li>
        <li>Upwork Job ID: 1699809692585758721</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Able to reproduce - adding external label.

**Comment by zanyrenney** [comment]
ah great, thank you @dukenv0307  thanks @allroundexperts too.
