### ISSUE TITLE
Emoji - The last used emoji displayed in the middle of the frequently emoji list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Tap on any conversation
3. Tap on emoji button in compose box
4. Tap on any listed emoji
5. Repeat step 3-4 with different emoji until the Frequently used emoji list will be full
6. Repeat step 3-4 and observe the last used emoji position in frequently used emoji list

## Expected Result:
The last used emoji should be displayed as first or last position in the frequently used emoji list

## Actual Result:
The last used emoji displayed in the middle of the frequently emoji list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/10cd29f1-5938-4282-8137-1cb024f613b8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
This isn't necessarily a bug. The frequently used emoji list is sorted by frequency of use (so most used emojis come first), and then the time an emoji was last used.

**Comment by sophiepintoraetz** [comment]
Additionally, I'm not able to reproduce this.
