### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] [Distance] - Invalid Navigation from Edit Distance page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start Distance request
2. Complete all the waypoints & details.
3. On Confirmation page expand more and click on Distance menu item.
4. From the opened distance page, go back.
5. Observe it closes.
6. Or click next we have to go through the flow again.

## Expected Result:
Should navigate back to same page we're from.

## Actual Result:
 Different page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8848e232-3c99-4ffb-a2f0-a78a4895f6d7

https://github.com/Expensify/App/assets/93399543/5359e91f-e8b2-4305-9d69-41dfdc2cf12f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693605021864609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dccd59898cf9ed55</li>
        <li>Upwork Job ID: 1701161450830778368</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26659104</li>
<li>b4s36t4 | Reporter | 26659105</li>
</ul></li>
    </ul>
</details>

**Comment by mim1192** [comment]
hello sir

**Comment by garrettmknight** [comment]
Closed the dupe issue, we'll use this one to fix.

**Comment by narefyev91** [comment]
Proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/26909#issuecomment-1709414246
I will suggest to use alternative solution and following already existing pattern for amount page (hope that will be possible)
🎀 👀 🎀 C+ reviewed

**Comment by Li357** [comment]
Sorry for the delay here. @dukenv0307 alternative proposal looks good to me.

**Comment by mim1192** [comment]
Hello Team ,

thanks for providing such a great opportunity.
how I will be a part of a team.

please guide me.

thanks

**Comment by garrettmknight** [comment]
@mim1192 please refer to this page: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - no regressions here - it was additional functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by mim1192** [comment]
Great

**Comment by mim1192** [comment]
Your Expensify account email: ***@***.***
Upwork Profile Link: https://www.upwork.com/freelancers/muhammadirfanm
