### ISSUE TITLE
[$500] Room - Displays error message when other language fonts are entered as room name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap new room
4. Enter room name in Hindi language
5. Tap create room and note the error message
6. Navigate back to LHN
7. Note the user name is allowed to be saved in Hindi language
8. Tap Workspaces
9. Tap on a workspace
10. Tap on a workspace name
11. Enter a name in Hindi language
12. Note it gets saved without any error

## Expected Result:
Like profile user name and workspace name, the room name also if entered in Hindi language must not show any error message if user taps create room

## Actual Result:
The profile user name and workspace name user able to set in Hindi language. But room name, if user enters in Hindi and tap create room, it displays error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5ecd2713-b294-43e5-886c-cb729e85a31e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b64f1ac7992fcfb5</li>
        <li>Upwork Job ID: 1709529043489992704</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
Room name is like username, which has requirements naming it

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment]
Can you confirm @lanitochka17 if the characters being used in Hindi are within the normal rules for characters (aka no hyphens/etc)

**Comment by dylanexpensify** [comment]
@lanitochka17 bump on the above request 🙇‍♂️

**Comment by dylanexpensify** [comment]
@lanitochka17 @kbecciv can either of you confirm

**Comment by dylanexpensify** [comment]
Closing unless we get a response from @lanitochka17 today

**Comment by kbecciv** [comment]
Hello @dylanexpensify Requested for retest, will update you in the morning! Sorry for delay.

**Comment by dylanexpensify** [comment]
Thanks @kbecciv curious for findings!

**Comment by dylanexpensify** [comment]
bump @kbecciv

**Comment by dylanexpensify** [comment]
added an engineer (cc @amyevans) given breaking WAQ

**Comment by dylanexpensify** [comment]
@amyevans mind letting us know an ETA

**Comment by amyevans** [comment]
Sorry, I've been playing catch up after being mostly OOO last week.

I verified the backend doesn't return an error when using Hindi for a room name, it's only frontend validation preventing it. So this could be fixed externally. Though it's technically breaking WAQ since we're past 4 weeks, based on the history of this GH I don't think it's had a fair shot at external proposals. So in the interest of conserving internal resources I'm going to reopen it to external proposals for at least a week or so, it should be a pretty straightforward fix.

**Comment by amyevans** [comment]
@thesahindia Is there nuance to your question? Or perhaps said differently, do you have concerns around doing so or a reason why we shouldn't?

I personally think if we're allowing it for the workspace name then allowing it for a room name makes sense, but am open to other opinions.

**Comment by dylanexpensify** [comment]
@thesahindia thoughts? ^

**Comment by amyevans** [comment]
Discussing this one internally ([Slack](https://expensify.slack.com/archives/C03U7DCU4/p1697554516714989)), will come back with the conclusion

**Comment by amyevans** [comment]
Okay based on internal discussion, while there may be merit in allowing a wider range of characters in the room name, the problem should be approached more holistically with other fields in mind, too. Since this isn't stemming from a customer complaint and we have higher priorities at the moment, we'll close this out for now. Thanks everyone!
