### ISSUE TITLE
[$500]  Attachments - File previews have infinite loading sign and can't uploaded via Google Drive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open and log into staging.new.expensify.com
2. Open any chat conversation, click "+" in the compose cox and click "Add attachment"
3. Navigate to Drive and select any file to upload

## Expected Result:
File preview loads correct and file can be uploaded

Infinite loading sign is shown after picking desired file and can not be uploaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/32943014-8717-49d5-9191-fc4a0278dcae

https://github.com/Expensify/App/assets/78819774/bf917704-76eb-44f8-9861-de66309e1419

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4955641379a18f6</li>
        <li>Upwork Job ID: 1701520516712812544</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
@fedirjh I'd like your opinion on the above - since this is an unfixed bug on the chromium side is it worth it for us to try to clean it up or, because this is a known issue and it's not breaking the app should we punt?

**Comment by adelekennedy** [comment]
@fedirjh thoughts on the above?

**Comment by adelekennedy** [comment]
then let's close
