### ISSUE TITLE
Web - Expensify.org Notification Does Not Update Display Name When Changed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Save the World".
2. Choose "I know a teacher" and fill in the details.
3. When the notification appears, go to Settings > Profile > Update Display Name. Notice that the notification does not update the display name dynamically

## Expected Result:
The Expensify.org notification should update the display name when it is changed

## Actual Result:
The Expensify.org notification does not update the display name when it is changed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/204675d6-86e0-4bf1-b1b3-1c5e4769d84f

https://github.com/Expensify/App/assets/93399543/9434100a-1190-4243-825a-a81604cd71ad

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693642140451149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I think the logic is to include the displayName or fallback on primaryLogin if one isn't set right now.

@StefStavri what do you think about this one? 

We're going for a "@mention" style in the whispered welcome message, but it doesn't appear to be an actual mention (the displayName portion isn't highlighted). Should it be a real mention? If so, it would use primaryLogin as we don't use displayNames in mentions just yet until [this issue](https://github.com/Expensify/App/issues/26306) is done. 

After which, I'm not even 100% sure if we'd update all historical mentions to the updated displayName, but maybe @puneetlath can fill us in on if we'll get this bug report "for free" if we make it a real mention.

**Comment by StefStavri** [comment]
I don't really understand the problem here. In this example the member is called Apple and they are referring teachers they know to the campaign. When they do that, each time we send a whisper thank you in the TU public room with @[displayName] . I don't think there is anything to change here.

**Comment by trjExpensify** [comment]
Cool, so to expand on the bug report: 

>1. User signs-up, sets their displayName as Tom Rhys Jones. 
>2. Refers a teacher, a welcome message is sent which includes `@displayName` i.e `@TomRhysJones`
>3. User changes their displayName to Tom Jones-Shaw i.e `@TomJones-Shaw`
>4. the `@displayName` reference in the welcome message from (2) does not update to `@TomJones-Shaw` it remains as `@TomRhysJones`. 

It's not a massively egregious bug, but it does highlight that we're basically "faux" styling a mention by hardcoding an `@` before the user's firstName in this particular welcome message. So any changes to that displayName thereafter are not reflected. "Real" `@displayName` mentions don't exist yet, they are always `@primaryLogin` at the moment. 

So my suggestions are either: 

1. Drop the `@` so it's not being confused with mentions, it would just print the user's first and last name. 
2. Make it a real mention, so it would use the `@primaryLogin` for the time being until [this is built](https://github.com/Expensify/App/issues/26306) which will properly it as a `@displayName` mention when introduced.

**Comment by puneetlath** [comment]
I agree with doing either 1 or 2. 2 is probably the best solution, but will require waiting until mentions have been updated to be accountID-based

**Comment by trjExpensify** [comment]
I tend to agree with option #2. So @puneetlath if we made it a real mention now, it'll be shown as `@primaryLogin` in the welcome message. Then once mentions accommodate display names,  it'll automatically start using `@displayName` if the conditions are met, right? 

@StefStavri, what do you think?

**Comment by puneetlath** [comment]
that's correct

**Comment by trjExpensify** [comment]
@marcochavezf @youssef-lr tagging you both in this one. We're leaning in the direction of making this a proper mention, are you cool with that before I move it forward with the expected results? 

<img width="1151" alt="image" src="https://github.com/Expensify/App/assets/16232057/df7f7ec2-2e0f-4aff-9ee1-ff6fca5c004a">

**Comment by marcochavezf** [comment]
Yeah, converting it to proper mention sounds good. I will assign myself to update it tomorrow

**Comment by trjExpensify** [comment]
Cool, thanks!

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/Auth/pull/8720) up

**Comment by marcochavezf** [comment]
PR was deployed to production, I tested and received the welcome messages with the correct mentioning:

<img width="628" alt="Screenshot 2023-09-22 at 12 36 04" src="https://github.com/Expensify/App/assets/6829422/18aceee0-c2b6-47e1-a9f3-4b734f75fc38">

<img width="1150" alt="Screenshot 2023-09-22 at 12 36 32" src="https://github.com/Expensify/App/assets/6829422/d229f7c2-1a9e-4399-9c3f-7149084df53c">

**Comment by marcochavezf** [comment]
Closing it out

**Comment by tewodrosGirmaA** [comment]
Hey @trjExpensify, am I eligible for payment now that the issue has been resolved and deployed in production? Thank you

**Comment by trjExpensify** [comment]
Yup! I've sent you an offer for $50.  

@marcochavezf check the reportedBy before closing these. :)

**Comment by tewodrosGirmaA** [comment]
@trjExpensify , I accept  it thank you

**Comment by trjExpensify** [comment]
Paid!
