### ISSUE TITLE
Simplify comment action menu for most common actions.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26927]
### Problem
As we increasingly build out our chat-focused features, the amount of available comment actions has increased pretty dramatically from a couple to ten and counting. It's pretty daunting to say the least. Just as importantly, this creates a dynamic where our least common actions have equal screen real estate next to actions that are incredibly common, which introduces decide fatigue when you just want to come into New Expensify, collaborate, and generally get great stuff done. 

### Solution
In order to reduce decision-fatigue, free up precious real estate and help users find the most common things they'd like to do, let's simplify the comment action menu, as follows:

 - Reduce one-tap emojis down to three (from four). Those emojis will be thumbs up (`:+1:`), heart (`:heart:`) and joy (`:joy`)
 - Keep the emoji picker, thread, mark as unread and edit always visible
 - Move copy message, delete and flag to a three-dot overflow menu

That looks like this for large screens.
![image](https://github.com/Expensify/App/assets/1127863/ec97fd0b-73eb-4133-b0bb-1d0c4d0cb72d)

Overflow menu selected
![image](https://github.com/Expensify/App/assets/1127863/f4e78266-5964-4ef5-8d91-81696e7f32af)

And it ends up looking like this for small screens. 
![image](https://github.com/Expensify/App/assets/1127863/bf9a9c6c-650b-43dd-9d80-b56d48383cd9)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e41d6a1dad5b7475</li>
        <li>Upwork Job ID: 1699665316818046976</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Marked this as internal because we'll work with an agency or C+ on this one.

**Comment by JmillsExpensify** [comment]
cc @shawnborton @dannymcclain @trjExpensify Any other comments before I move this one forward?

**Comment by JmillsExpensify** [comment]
Actually on that note: One doubt I still have is that I currently have three quick emoji actions mocked up for large screens, but because of how we have a dedicated row for small screens, there's just a lot more space for four plus the add emoji icon. Maybe that's ok even though it's technically "inconsistent"?

**Comment by trjExpensify** [comment]
>there's just a lot more space for four plus the add emoji icon. Maybe that's ok even though it's technically "inconsistent"?

Hm, I'm not sure about that inconsistency to be honest. Is one more emoji to stay consistent really that egregious? Especially as you can also right-click on desktop to see the same menu as mobile, so there can be a visible diff on the same screen as well.

**Comment by dannymcclain** [comment]
I also don't think it's a big deal and don't really see it as an "inconsistency" as much as just adapting the UI to the viewport it's being display on. Like if we _didn't_ show emojis on one but did on the other, I would call _that_ an inconsistency.

But I don't have super duper strong feelings either way to be honest. I did want to echo what Shawn said—we should be sure we document the decision to avoid unnecessary bug reports 🐛.

**Comment by trjExpensify** [comment]
Yeah, I just can't see a super clear reason for it. For example, if the extra emoji on desktop/web causes the menu items to overlap reactions or messages to the left, that would make sense. But I don't think they do, so I would just keep the number of them consistent across all platforms personally.

**Comment by trjExpensify** [comment]
Why wouldn't we put `join thread` in the overflow menu?

**Comment by JmillsExpensify** [comment]
Just speaking for myself, I use that one a bunch.

**Comment by trjExpensify** [comment]
Same, but I think it's a power user thing. I've never been frustrated with where it is in Slack either, so I think it's fine in the overflow menu.

**Comment by JmillsExpensify** [comment]
Ok cool. Down with that approach then.

**Comment by JmillsExpensify** [comment]
We still need to get to this, though admittedly it doesn't feel like a priority right now.

**Comment by JmillsExpensify** [comment]
Still feels like low priority.

**Comment by JmillsExpensify** [comment]
Same as above. We'll come back to this later.

**Comment by JmillsExpensify** [comment]
Not a priority

**Comment by JmillsExpensify** [comment]
@dubielzyk-expensify This might be a good issue for you to lead given that you're doing quite a bit of polish and cleaning up designs through out the app. No worries though if you have a lot going on!

**Comment by dubielzyk-expensify** [comment]
Happy to take it on. I think we should stick with 3 emojis in both cases personally. Having looked through the different states etc it looks to me like this is the list of actions:

```
(Emoji’s)
Thumbs up
Heart
Joy
(Action)
Add emoji reaction
Reply in thread
Edit (Your comment only)
Download (Attachment only)
(Overflow)
Mark as unread
Subscribe to thread
Copy to clipboard
Report
Delete comment
```

With the above it'll be [Emoji 1, Emoji 2, Emoji 3, Add emoji, Action 1, Action 2, overflow]. Whatever don't fit goes in the overflow.

I also took the liberty to clean up the pixels a bit from what we have today to make it less overwhelming and make the tap targets a bit bigger. This also eliminates the space between the actions:
![CleanShot 2023-11-28 at 16 35 55](https://github.com/Expensify/App/assets/145416827/5744333c-849c-4c87-9734-a1b2ac793fff)

Putting it all together we get:
![image](https://github.com/Expensify/App/assets/145416827/1de893ad-89b8-4c03-a4bf-fa103c0ff3bf)
![CleanShot 2023-11-28 at 16 38 39@2x](https://github.com/Expensify/App/assets/145416827/425eb4bd-0492-412c-89cb-f2a125a9e2b7)

Also suggest we add a new `Mark as unread` icon to make it clearer. Here's my take:
![image](https://github.com/Expensify/App/assets/145416827/0e7889ff-c8c7-4d80-a6a2-f78443e06bfe)

Would love takes from @Expensify/design on this too

**Comment by shawnborton** [comment]
No hot takes from me, I love all of this and I agree where you landed with your exploration. Nice job!

**Comment by quinthar** [comment]
Hm, I use "mark unread" *all the time*, easily 10x more often than the sum of everything else.  Can we please not put that behind an overflow?

**Comment by quinthar** [comment]
"Subscribe to thread" can definitely go (I didn't even know it existed).

**Comment by quinthar** [comment]
Copy link also seems like a kind of poweruser thing that happens very rarely

**Comment by JmillsExpensify** [comment]
I use "subscribe to thread" and "open thread" pretty much all the time, less so "mark as unread". That said, I could live with "subscribe to thread going behind the three dot overflow menu. I think the issue we're going to face is that we all use products differently.

**Comment by JmillsExpensify** [comment]
All in all, I think Jon nailed it!

**Comment by dannymcclain** [comment]
Love what you've done Jon! 

I think both of your updated `mark as unread` icons are good, but I have a _slight_ preference for the chat bubble one. Would be totally happy with either though!

**Comment by JmillsExpensify** [comment]
Are we good to move forward with this one? Not exactly a priority but I still think it's nice polish for the chat experience.

**Comment by dubielzyk-expensify** [comment]
✅  This is ready: 
- New icon added to [Figma](https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?type=design&node-id=5445-3067&mode=design&t=eqb8ImR1YqTxEOfH-4)
- [Mocks polished](https://www.figma.com/file/ve8TXp63ME2AZ3zqxUzfjo/Comment-Action-Menu?type=design&node-id=445-12088&mode=design) and ready for eng

------

### Specced up and ready here:

**Your comment (with and without attachment)**
![CleanShot 2023-12-14 at 11 40 48@2x](https://github.com/Expensify/App/assets/145416827/5e3020ee-8c60-4e5c-b619-5d302e750c0a)


**Comment from someone (with and without attachment)**
![CleanShot 2023-12-14 at 11 39 56@2x](https://github.com/Expensify/App/assets/145416827/6f34466e-8906-4822-92f5-db4e09bdb753)


------

### New "Reply in thread" icon

I do think we'll need a new "Reply in thread" icon. I'll do that work as a separate ticket and implementation, but I suggest something like this:

![image](https://github.com/Expensify/App/assets/145416827/bfa1fe9f-dc5b-45b6-8e26-34e0c66915a7)

I've started [a thread](https://expensify.slack.com/archives/C03TME82F/p1702518915113709) in Slack for this.

**Comment by JmillsExpensify** [comment]
Great call on `Reply in thread`. This is looking super great!

**Comment by dubielzyk-expensify** [comment]
Not overdue. Think this is ready though

**Comment by JmillsExpensify** [comment]
Yes, I think we're aligned on this point. Would you mind posting a summary in #product in Slack as a final confirmation? Then we can get this assigned out.

**Comment by dubielzyk-expensify** [comment]
Done and done. [Slack link](https://expensify.slack.com/archives/C03U7DCU4/p1704167680680569)

**Comment by JmillsExpensify** [comment]
Looks like you have lots of support in the Slack thread!

**Comment by JmillsExpensify** [comment]
@quinthar Should we close this issue? I saw you created a separate one: https://github.com/Expensify/App/issues/33573.

**Comment by JmillsExpensify** [comment]
Closing since we have a duplicate issue now.
