### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web/Desktop - Request skeleton is shown grayed out instead the IOU details.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation with a request money.
2. Open the IOU details
2. Disable the internet connection on the device
3. Click Delete the request

## Expected Result:
Verify the request has been deleted and the IOU preview in conversation has been updated (the message should be still grayed out)

## Actual Result:
Request skeleton is shown grayed out instead the IOU details.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6190968_offline_delete](https://github.com/Expensify/App/assets/115492554/8bf1220c-cebf-4ce6-bc81-da4e3c829aa5)

https://github.com/Expensify/App/assets/115492554/c09bfa2b-f772-48bc-9a96-f4ba9f867acb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdce495f39748b20</li>
        <li>Upwork Job ID: 1700202090575839232</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26737448</li>
<li>ginsuma | Contributor | 26737449</li>
</ul></li>
    </ul>
</details>

**Comment by maddylewis** [comment]
@0xmiroslav - bump on proposal review - thx!

**Comment by cead22** [comment]
@0xmiroslav can you share a bit more context? What do we do with regular messages deleted while offline, strikethrough or no strikethrough? I think this is a good thing to discuss in #expensify-open-source, particularly the detail about the receipt. I think it's fine to not show it, but it'd be ideal to gray it out if it's not too difficult. Can you start that convo?

**Comment by maddylewis** [comment]
## Payments
- [ ] Reporting bonus: N/A
- [ ] Contributor: @tienifr ($250 via Upwork)
- [ ] Contributor: @ginsuma ($250 via Upwork)
- [ ] C+: @0xmiroslav ($500 via Upwork)

**Comment by maddylewis** [comment]
@0xmiroslav - can you review this checklist when you have a chance? thanks! https://github.com/Expensify/App/issues/26939#issuecomment-1733296960

**Comment by maddylewis** [comment]
kk paid both contributors! 

@0xmiroslav im kind of confused about what's going on with your payment but lmk if you need me to do anything with the offer that was sent. 

also bump on reviewing this checklist - ty! https://github.com/Expensify/App/issues/26939#issuecomment-1733296960

**Comment by maddylewis** [comment]
i will wrap this one up today

**Comment by maddylewis** [comment]
okay @0xmiroslav i sent your Upwork profile an offer for this one. once it's accepted, I'll pay it out + the bonus and close this out.

**Comment by maddylewis** [comment]
paid!
