### ISSUE TITLE
[HOLD for payment 2023-09-18] [HOLD for payment 2023-09-15] Please remove Save The World from FAB in prod

### ISSUE THREAD

**Issue by StefStavri** [Expensify/App#26930]
As discussed [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1694072573071179) we've decided to push back the Teachers unite! launch date and therefore we do not want Save The World appearing in production in the Global create menu (which allows public users to join our TU testing workspace and rooms)

<img width="1132" alt="image" src="https://github.com/Expensify/App/assets/22508185/33b4ca67-81a7-46e1-ba78-a795c02522e9">

**Comment by saisixthblock** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
remove Save The World from FAB.


**What changes do you think we should make in order to solve the problem?**
Remove the option from Popup menu list.
