### ISSUE TITLE
Android- IOU- User is allowed to select while creating distance IOU

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Fab
3. Tap request money
4. Tap distance
5. Tap Start and select an address
6. Tap Finish and select an address
7. Tap Next
8. Enter any user email address and select it

## Expected Result:
User must not be allowed to select while creating distance IOU. Only Workspace should be allowed to create distance IOU.

## Actual Result:
User is allowed to select while creating distance IOU.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e5761c63-f90d-4bb6-850f-039e19c469dd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Not worth proceeding with this issue, in light of this: https://github.com/Expensify/App/issues/23291

CC: @JmillsExpensify

**Comment by joekaufmanexpensify** [comment]
Cool, makes sense. Closing!
