### ISSUE TITLE
[HOLD for payment 2023-10-10] [$1000] Android - Request money - IOU SmartScan disappears from the history when a user is relogged

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26940]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Log in with any login
3. Navigate to the WS room, if you don't have one, create one.
4. In the Action menu select Request money
5. Select the Scan tab
6. Add any image
7. Complete the request
8. Re-login as the same user
9. Navigate to the room from step 3

## Expected Result:
The SmartScan money request should not disappear from the history when the user logs in again and should eventually complete its work and provide the user with the processed result.

## Actual Result:
Request money SmartScan disappears from the history when a user is relogged.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2a49f4d1-7d34-41db-ac05-75db9d780433

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153f8948debd26069</li>
        <li>Upwork Job ID: 1705016851186573312</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26956018</li>
<li>shubham1206agra | Contributor | 26956019</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Hm, I'm not able to repro this, the request persists after I log out and log back in. @izarutskaya can you see this is still reproducible for you? 

Here is an image from Mac/Safari: 
<img width="483" alt="image" src="https://github.com/Expensify/App/assets/31225194/ba18a256-7e27-4196-9dcd-bfe7069cc18e">

**Comment by izarutskaya** [comment]
@stephanieelliott Sorry for waiting, now I can't repro this in Chrome, but I still can repro this in Android App.
Build - v1.3.70-5

https://github.com/Expensify/App/assets/115492554/962cf9fb-5288-4f6b-bc50-22f5f6e3385e

**Comment by stephanieelliott** [comment]
Just tried reproing again, resolved on all other platforms but still happening in Android native.

**Comment by s77rt** [comment]
Not overdue. Looking for proposals

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals

**Comment by stephanieelliott** [comment]
Doubled the bounty on this one! Hopefully e get some proposals soon.

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Android - Request money - IOU SmartScan disappears from the history when a user is relogged

### What is the root cause of that problem?

When we request money in Android with a receipt, the Android uses `readFileAsync` function to upload the file for the request, but the function has a bug due to which following error occurs

` DEBUG  [hmmm] [Network] API request error: Connection interruption likely - `
```json
{
  "message": "Network request failed",
  "request": {
    "command": "RequestMoney",
    "data": {
      "debtorEmail": "work.sa1206+ga@gmail.com",
      "debtorAccountID": 15101409,
      "amount": 0,
      "currency": "INR",
      "comment": "",
      "created": "2023-09-28",
      "merchant": "",
      "iouReportID": "8419113154382148",
      "chatReportID": "1705808921226559",
      "transactionID": "2094490949556796421",
      "reportActionID": "8335409594164208405",
      "createdChatReportActionID": 0,
      "createdIOUReportActionID": "1325445640214075745",
      "reportPreviewReportActionID": "3432629471431536702",
      "receipt": {
        "_data": {
          "blobId": "3441ff11-a436-43a4-8072-9d2c3f8cd903",
          "offset": 0,
          "size": 962613,
          "type": "",
          "lastModified": 1695885390351,
          "__collector": {},
          "name": "rn_image_picker_lib_temp_70b3b9f6-2b02-4b4a-bde0-00319136e68b.jpg"
        },
        "source": "file:///data/user/0/com.expensify.chat.dev/cache/rn_image_picker_lib_temp_70b3b9f6-2b02-4b4a-bde0-00319136e68b.jpg",
        "uri": "file:///data/user/0/com.expensify.chat.dev/cache/rn_image_picker_lib_temp_70b3b9f6-2b02-4b4a-bde0-00319136e68b.jpg",
        "state": "SCANREADY"
      },
      "receiptState": "SCANREADY",
      "category": "",
      "tag": "",
      "billable": false,
      "appversion": "1.3.74-3",
      "apiRequestType": "write",
      "pusherSocketID": "548936.4902950",
      "shouldRetry": true,
      "canCancel": true
    },
    "successData": [
      {
        "onyxMethod": "merge",
        "key": "report_8419113154382148",
        "value": {
          "pendingFields": null,
          "errorFields": null
        }
      },
      {
        "onyxMethod": "merge",
        "key": "transactions_2094490949556796421",
        "value": {
          "pendingAction": null
        }
      },
      {
        "onyxMethod": "merge",
        "key": "reportActions_1705808921226559",
        "value": {
          "3432629471431536702": {
            "pendingAction": null
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "reportActions_8419113154382148",
        "value": {
          "1325445640214075745": {
            "pendingAction": null,
            "errors": null
          },
          "8335409594164208405": {
            "pendingAction": null,
            "errors": null
          }
        }
      }
    ],
    "failureData": [
      {
        "onyxMethod": "merge",
        "key": "report_1705808921226559",
        "value": {
          "hasOutstandingIOU": false,
          "iouReportID": null,
          "lastReadTime": "2023-09-28 07:16:04.278"
        }
      },
      {
        "onyxMethod": "merge",
        "key": "report_8419113154382148",
        "value": {
          "errorFields": {
            "createChat": {
              "1695885390364000": "report.genericCreateReportFailureMessage"
            }
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "transactions_2094490949556796421",
        "value": {
          "errors": {
            "1695885390364000": "iou.error.genericCreateFailureMessage"
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "reportActions_1705808921226559",
        "value": {
          "3432629471431536702": {
            "created": "2023-09-28 07:16:30.362"
          }
        }
      },
      {
        "onyxMethod": "merge",
        "key": "reportActions_8419113154382148",
        "value": {
          "1325445640214075745": {
            "errors": {
              "1695885390364000": "iou.error.genericCreateFailureMessage"
            }
          },
          "8335409594164208405": {
            "errors": {
              "1695885390364000": null
            }
          }
        }
      }
    ]
  }
}
```

Reference to the use 
https://github.com/Expensify/App/blob/bcc8a6333b5b161eb07e404228f5c62de62cb5e2/src/pages/iou/steps/MoneyRequestConfirmPage.js#L220

You can observe that under `reciept._data`, the `type` key has value `''`. In the `fetch` command, this will work for other platforms but not for Android.

We can see a similar handling of this in `AttachmentModal` for uploading attachments.

https://github.com/Expensify/App/blob/bcc8a6333b5b161eb07e404228f5c62de62cb5e2/src/components/AttachmentModal.js#L272


### What changes do you think we should make in order to solve the problem?

We need to set the mime type for the receipt using a similar method above.

Specifically, in

https://github.com/Expensify/App/blob/bcc8a6333b5b161eb07e404228f5c62de62cb5e2/src/libs/fileDownload/FileUtils.js#L160

use the below instead

```js
const file = new File([blob], cleanFileName(fileName), {type: blob.type});
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by s77rt** [comment]
@shubham1206agra Thanks for the proposal. Your RCA makes sense and the solution looks good to me.

(Not a blocker): Do you know if we have this issue reported anywhere e.g. hermes or react-native?

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/26940#issuecomment-1740445802)

**Comment by shubham1206agra** [comment]
> (Not a blocker): Do you know if we have this issue reported anywhere e.g. hermes or react-native?

@s77rt Yes there was an issue in RN but by the conversation there it looks like it is a problem with Android, not RN

**Comment by shubham1206agra** [comment]
@aimane-chnaif But this is a separate issue with the same RCA. And I didn't know about this proposal either.
And we have already done the work in the PR.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23770
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23770#discussion_r1346219645
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1696440597637729
- Determine if we should create a regression test for this bug: No

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 
 - Issue reporter: N/A
 - Contributor: @shubham1206agra $1500 ($1000 bounty + $500 bonus), paid via Upwork 
 - Contributor+: @s77rt $1500 ($1000 bounty + $500 bonus), paid via Upwork 
 
 Upwork job is here, 50% bonus is included on final payout

Everyone is paid, thanks!
