### ISSUE TITLE
Request money - Updating description/merchant offline while user approves the pay sends message but field is not updated

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user A, send request money request to user B of any amount
4. From user A, open request money message twice to open request money page
5. Switch off internet in user A device
6. From user B, approve the request money request of user A
7. Keeping internet off, update description/merchant of request from user A
8. Turn on the internet
9. Observe that app reverts the update of description/merchant value but update message is sent successfully

## Expected Result:
If user changes description/merchant offline for approved pay request, field should not be updated and not update message should be sent on coming back online

## Actual Result:
If user changes description/merchant offline for approved pay request, field is updated for some time and  reverted back and update message is also sent on coming back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/744dfb07-edaa-4956-beca-cf6d9b31e93d

https://github.com/Expensify/App/assets/115492554/9bd193c0-f990-493e-85a1-7d31cc7c63a3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693680049960609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
https://github.com/Expensify/App/issues/26880 was reported first
