### ISSUE TITLE
mWeb - Request money- Amount keyboard loses its focus when clicking on "manual" even when manual is the preselected method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Login to staging new dot
 2. Click on + icon and select request money
 3. Observe that amount keyboard is focused
 4. Click on the highlighted manual button at left top corner while still in the manual page
 5. Observe that the keyboard loses focus

## Expected Result:
Keyboard should not be focused

## Actual Result:
Keyboard loses focus

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f86e7b93-051b-47f8-bb30-f8838977c184

https://github.com/Expensify/App/assets/93399543/72df17a2-797f-45f6-811f-50fb73bed433

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693715558491699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
About to go OOO today and tomorrow so reassigning until I'm back next week! Will pick it back then 🙇

**Comment by conorpendergrast** [comment]
@MitchExpensify I'll get it started; unassign me when you're back!

**Comment by SofoniasN** [comment]
@conorpendergrast @MitchExpensify  Hey guys is there any update on this issue.

**Comment by MitchExpensify** [comment]
I don't think this is unexpected necessarily, you are clicking the Manual button unnecessarily and I'd expected focus to be wherever I just clicked versus staying on the input field. I don't think this is worth fixing as such
