### ISSUE TITLE
Web - Report is not highlighted even if context menu is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26952]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Right click on report in LHS
2. Again right click on the same report
3. Move cursor anywhere on the web app
4. Observe it is not highlighted but context menu is open

## Expected Result:
The report should be highlighted when context menu is open.

## Actual Result:
The report is not highlighted when context menu is open.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.0
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c3839a7-f90f-41ef-9449-65a58eb04826

https://github.com/Expensify/App/assets/93399543/61e97b0e-1437-4179-9388-c696fe04bbb9

**Expensify/Expensify 
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693512993104379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011686c8222a068c45</li>
        <li>Upwork Job ID: 1709891734612799488</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
I'm confused why this is a bug though. The LHN should always highlight the report that is in the main chat window.

**Comment by getusha** [comment]
>Maybe @getusha can raise follow-up PR fixing this as this is 1 line change?

Looks similar issue, i can raise the PR.

**Comment by abdulrahuman5196** [comment]
> This should have been handled in #25582 as they both have the same root cause and just happen in different places. Maybe @getusha can raise follow-up PR fixing this as this is 1 line change? cc: @abdulrahuman5196 @pecanoro

Ideally, this issue should have been marked dupe and notified on original issue initially. Since we were unaware of this issue, the other PR(https://github.com/Expensify/App/pull/28639) didn't target this place of issue and the other PR is merged. 
I am not sure how a follow up PR can pan out now since there is another contributor already raised a formal proposal.
Its fine IMO to raise a followup PR and I can C+ review the PR.
But I would let the BZ confirm/take final call here.

**Comment by getusha** [comment]
@aimane-chnaif IMO i think it should've been handled here if it is a dupe or not, which was already attempted by @bernhardoj

**Comment by JmillsExpensify** [comment]
Agree that @bernhardoj marked this issue as a dupe long ago. I was simply curious why it was a bug, though in any case, it's a dupe so we should close it.
