### ISSUE TITLE
[$500] IOU - Split bill in room of participant is shown empty in mweb& loading in android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26956]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Profile
3. Tap Workspaces
4. Select a workspace
5. Tap on top right 3 dot
6. Tap announce room
7. Tap plus icon near compose
8. Tap Split bill
9. Tap enter amount
10. Tap next
11. Tap split money
12. Open a split money participant account (mweb)
13. From LHN, Open announce room split bill to note split bill transaction is empty

Or
Pre-condition: a room created
1. Go to https://staging.new.expensify.com/
2. Open a room created
3. Repeat steps 7 - step 11
4. Open a split money participant account(android)
5. From LHN, Open announce room split bill to note split bill transaction

## Expected Result:
The split bill transaction in room of participant must be shown correctly with amount and participants details in both mweb and android. It should not be empty(mweb) and keeps loading as in android

## Actual Result:
He split bill transaction in room of participant is shown empty in mweb and keeps loading in android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b363b0fd-ddaf-4d00-aa8d-d3db64b77cd0

https://github.com/Expensify/App/assets/78819774/34727adc-48e0-424a-86f4-8988bb59f0c1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013eb2d17255ea6583</li>
        <li>Upwork Job ID: 1699828711453896704</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by ayazalavi** [comment]
@lanitochka17 @situchan is it reproducible over the desktop mac? Can you share video for that?

**Comment by ayazalavi** [comment]
@tienifr anything i can do in this ticket?

**Comment by isabelastisser** [comment]
Hey @situchan how can we move this forward?

**Comment by isabelastisser** [comment]
@situchan, can you see my comment above? Should an Expensify engineer handle this? Can you reproduce this?

**Comment by situchan** [comment]
I agree to handle this internally

**Comment by isabelastisser** [comment]
Hey @situchan, can this still be reproduced?

**Comment by situchan** [comment]
I am not able to reproduce. @lanitochka17 can you please test on latest version?
