### ISSUE TITLE
 Workspace - Error message shows up after reconnecting network and returning from Onfido

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Go to Settings > Workspaces > any workspace > Bank account > Connect online with Plaid
3. Proceed with Region bank until Step 3 (Personal information)
4. Add First to First name and Last to Last name
5. When all the details are filled in, click Save & Continue
6. On Onfido page, disable the internet connection
7. Enable internet connection
8. Close Onfido screen to return to Step 3 (Personal information)

## Expected Result:
There is no error message

An error message 'There was an error while processing this step. Please try again.' shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4df80fed-fbc1-4cfe-af66-af775b0abe8a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
@lanitochka17 I don't see why this is a bug. If the system ran into an issue, shouldn't it throw an error?
