### ISSUE TITLE
[$500] Android - Request money - Currency list scrolls to top on changing currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Close the app if running in background
2. Open the app & request money
3. Long press on currency sign to change it
4. Scroll down a little & select any other currency
5. Observe the list suddenly moves to top

## Expected Result:
The list should not scroll to top

## Actual Result:
The list scrolls to top sometimes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/11246284-e3ff-4e01-8406-d444e97a5a7e

https://github.com/Expensify/App/assets/93399543/15d836b8-2cc0-4be2-be7e-0492b3a4dea6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693765361735249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123535b252b6b3b56</li>
        <li>Upwork Job ID: 1711938111933321216</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27886152</li>
</ul></li>
    </ul>
</details>

**Comment by anmurali** [comment]
I am able to change currency just fine without any jumping to the top.

**Comment by lanitochka17** [comment]
Issue is reproducible on Build 1.3.78-2

https://github.com/Expensify/App/assets/78819774/ba414dc8-19f9-4586-9e6a-6e22273b3894

https://github.com/Expensify/App/assets/78819774/07b17ed2-baa3-4fbb-85e4-72e984ecfe82

**Comment by anmurali** [comment]
Ah yes, it seems to happen when you try to search for a specific currency

**Comment by akinwale** [comment]
I am unable to reproduce this. @anmurali Were there any extra steps you took to get the app to behave like it does in the uploaded videos?

**Comment by cubuspl42** [comment]
@anmurali Please take a look at this question:

> I am unable to reproduce this. @anmurali Were there any extra steps you took to get the app to behave like it does in the uploaded videos?

**Comment by anmurali** [comment]
@cubuspl42 - this is what I did.
1. Close the app if running in background
2. Open the app & request money
3. Long press on currency sign to change it
4. Search for a specific currency and select it
5. Observe the list suddenly moves to top

**Comment by cubuspl42** [comment]
@akinwale Would you like to give it another try, with this extra info? We're still open for proposals here!

**Comment by cubuspl42** [comment]
I advertised [this issue on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1698754641760619)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by cubuspl42** [comment]
@anmurali Could we hold on https://github.com/Expensify/App/pull/29317 and verify if our issue is reproducible after that PR is merged?

**Comment by cubuspl42** [comment]
So do I understand correctly that https://github.com/Expensify/App/pull/29317 is about to be closed?

**Comment by cubuspl42** [comment]
> * Update the reproduction steps so it's easier to reproduce.

If you know how to improve the reproduction steps, please share your thoughts

> * I will post my proposal with a [new solution](https://github.com/Expensify/App/pull/29317#issuecomment-1763915158) and we can discuss it here.

This issue so far has no proposals, so if you have an idea for one, go ahead!

**Comment by cubuspl42** [comment]
@bernhardoj Oh my. Many things are happening here! Thanks for this detailed analysis.

> But because the currency symbol button doesn't pass the `onLongPress` callback, the `onPress` callback is triggered (for the 2nd time) instead.

I'm sorry if this is a silly thought, but does adding `onLongPress={() => {}}` help in any way?

**Comment by cubuspl42** [comment]
> it will introduce some issues

Do the mentioned situations apply here? Do you _expect_ to have any actual handling of the long press for the currency item?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by cubuspl42** [comment]
@anmurali Would you re-assign this to to @eVoloshchak, as per [this Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1699876740659229)?

**Comment by cubuspl42** [comment]
@kbecciv @anmurali 

> @anmurali Would you re-assign this to to @eVoloshchak, as per [this Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1699876740659229)?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by cubuspl42** [comment]
> @kbecciv @anmurali
> 
> > @anmurali Would you re-assign this to to @eVoloshchak, as per [this Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1699876740659229)?

🎀 👀 🎀

We agreed with @eVoloshchak that they have more context to review this. I want to ask for a re-assignment.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (4th week) Are we good to close this?

**Comment by cubuspl42** [comment]
The update is that I asked for re-assignment multiple times and got ignored each time

**Comment by grgia** [comment]
@cubuspl42 not sure why the offer was triggered when I reassigned you

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (5th week)

**Comment by anmurali** [comment]
Closing as issue is reported as not reproducible.
