### ISSUE TITLE
Web -  "Uh-oh, something went wrong!" when trying to access the Receipt scan in progress…  chat  using the link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26971]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money using UserA
2. Go to scan tab
3. Upload a receipt
4. Choose UserB
5. Click request
6. Click on the receipt and copy the link
7. Connect to the app using UserB and past the link

## Expected Result:
"Hmm... it's not here" page should appear

## Actual Result:
Uh-oh, something went wrong!" page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[scan-progress.webm](https://github.com/Expensify/App/assets/93399543/ae35403f-ea98-447c-ae9d-f6c993467c9b)

https://github.com/Expensify/App/assets/93399543/4fd28139-559d-4022-b6fb-d497243ab680

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693739581173179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
I can't reproduce this one - gonna close!
