### ISSUE TITLE
Web - Mentionable list doesn't popup when download is cancel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report with a attachment.
2. Enter "@" in composer
3. Open the attachment and close
4. Observe the mentionable list pops up
5. Click on the download icon from context menu & cancel
6. Observe the mentionable list doesn't pop up

## Expected Result:
The mentionable list should pop up.

## Actual Result:
The mentionable list is not pop up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/da38bd03-bc94-48ff-bf8c-441f17de5480

https://github.com/Expensify/App/assets/93399543/c016c260-843e-485e-89db-86ce91cc76c4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1693763905573409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This issue looks like have the same RCA as https://github.com/Expensify/App/issues/22447

**Comment by sophiepintoraetz** [comment]
I would even go as far to say that this is a dupe, so closing.
