### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] warning: native module for Flipper seems unavailable

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26988]
![2023-09-07_09-54-26](https://github.com/Expensify/App/assets/32969087/f2f5436a-5260-4c92-a4fe-685658138c95)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c93e6f743127c98</li>
        <li>Upwork Job ID: 1700290971102027776</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26876532</li>
<li>bernhardoj | Contributor | 26936772</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Seems like I was accidentally double assigned here. Unassigning, but LMK if there's anything I can help with!

**Comment by abdulrahuman5196** [comment]
Sorry for the delay, I will check on this during the weekend

**Comment by greg-schroeder** [comment]
awaiting proposal review

**Comment by greg-schroeder** [comment]
Re-adjusting C+ to someone with a bit more bandwidth!

**Comment by situchan** [comment]
I agree with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/26988#issuecomment-1711097321). Flipper is only for native so it makes sense to have platform files for `useFlipper`.
🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment]
Hey @jasperhuangg can you confirm the assignment here? https://github.com/Expensify/App/issues/26988#issuecomment-1734828990

Thanks!

**Comment by jasperhuangg** [comment]
Thanks for your patience. Your proposal makes sense to me @bernhardoj, assigned!

**Comment by greg-schroeder** [comment]
processing

**Comment by greg-schroeder** [comment]
Issue Participants:

Contributor: @bernhardoj ($750)
C+: @situchan ($750)

**Comment by situchan** [comment]
We can skip BZ checklist here. It's just console warning

**Comment by greg-schroeder** [comment]
Yeah, agreed. Closing!
