### ISSUE TITLE
[HOLD] warning: setNativeProps is deprecated

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26989]
![2023-09-07_09-56-41](https://github.com/Expensify/App/assets/32969087/559e0aeb-f2b1-4640-a40c-8e5264845a18)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3301af71f9f2c5b</li>
        <li>Upwork Job ID: 1700244879840337920</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 what am I doing with this mate?

**Comment by marcaaron** [comment]
-> `External`

**Comment by trjExpensify** [comment]
Waiting for proposals.

**Comment by trjExpensify** [comment]
@marcaaron have any particular contributors been involved in knocking down setNativeProps related issues we can approach here?

**Comment by marcaaron** [comment]
Not that I know of. This looks like it's coming from an animation library though so maybe SWM can help.

**Comment by trjExpensify** [comment]
Cool, I can ask. Do you know where this shows up in the app? I don't see it in the console.

**Comment by narefyev91** [comment]
@trjExpensify just simply loading default page in web (in console last warning message)
<img width="1728" alt="Screenshot 2023-09-22 at 12 48 21" src="https://github.com/Expensify/App/assets/28352309/cbc0dc6f-6016-4165-8222-534e5ce49ef0">

**Comment by trjExpensify** [comment]
Ah, i was on the desktop app. I can see it after a refresh now, thanks!

**Comment by blazejkustra** [comment]
> Not that I know of. This looks like it's coming from an animation library though so maybe SWM can help.

@marcaaron From what I see the error comes from @expensify/react-native-web, what makes you think that it comes from an animation library?

**Comment by blazejkustra** [comment]
There are a lot of libraries that use `setNativeProps`, from node_modules search:
![image](https://github.com/Expensify/App/assets/46095609/29e19c0b-509e-4191-a5e8-80f8ec7a0161)

BTW `setNativeProps` won't be even supported in Fabric, [source](https://github.com/facebook/react-native/issues/34391). 

We can't do much about this warning other than to patch the library and comment out the console log with the warning. I guess that would be my proposal for this issue 😅 

![image](https://github.com/Expensify/App/assets/46095609/8a722ec0-acc9-414c-b7c4-31a4bbff0906)

**Comment by marcaaron** [comment]
saw references to these in the warning trace:

<img width="260" alt="2023-09-25_11-59-49" src="https://github.com/Expensify/App/assets/32969087/6566ef0c-017a-4ca6-9d50-215fb6c4c340">

**Comment by trjExpensify** [comment]
Chill Melv, @blazejkustra & @marcaaron are actively discussing.

**Comment by blazejkustra** [comment]
@marcaaron @trjExpensify These are animations from `react-native`/`react-native-web` ([Animated](https://reactnative.dev/docs/animated)). `setNativeProps` is what `Animated` uses to bypass setState. So as long as we use Animated I don't think we can do much about this warning, so either we refactor every usage of Animated to make sure it doesn't use `setNativeProps` internally or migrate animations to `react-native-reanimated`.

Is there a plan to replace `Animated` with `Reanimated` in the near future?

**Comment by marcaaron** [comment]
>Is there a plan to replace Animated with Reanimated in the near future?

Not that I know of. 

I think we can maybe keep this open though and just put it on HOLD then close whenever `react-native-web` fixes this. 

As long as we are tracking it somewhere...

**Comment by trjExpensify** [comment]
Hm, okay. Is there anything to point to as a PR or issue with RNW that would fix this? Happy to pop `[Hold]` in the title but when we do that, we should point to what it's held on, not that it's indefinitely in the ether.

**Comment by marcaaron** [comment]
Update rnw maybe? Migrating off Animated could also be an option. Sorry I mainly created this issue because we have a checklist item that asks to create the issue if there are warnings in the JS console. If we want to ignore it and close the issue we can also do that, but it might pop up again which is why I recommended leaving it open and on HOLD.

If the main issue is the `Daily` and `Bug` labels being annoying then we can just drop them as this isn't really a "bug" 🤷‍♂️
