### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26990]
![2023-09-07_09-57-35](https://github.com/Expensify/App/assets/32969087/3e10beca-21eb-4d88-b6bb-c4b28de41fcf)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180d44e7dee5aa64d</li>
        <li>Upwork Job ID: 1701421752840802304</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26646331</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by flaviadefaria** [comment]
@marcaaron can you add a bit more info here? Are you going to fix this? Should I add an internal label? Thanks!

**Comment by marcaaron** [comment]
Sorry @flaviadefaria. Sending it to `External` to fix.

**Comment by flaviadefaria** [comment]
@johncschuster I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by johncschuster** [comment]
Can we get an update on this @tienifr?

**Comment by johncschuster** [comment]
Sweet. Thank you!

**Comment by johncschuster** [comment]
### Payment Summary

@thesahindia does not require payment (Eligible for Manual Requests) - **$500** 
@tienifr requires payment [offer](https://www.upwork.com/nx/wm/offer/26646331) (Contributor) - **$500** - `PAID`

**Comment by danieldoglas** [comment]
Still waiting for react native web merge, moving to monthly until then

**Comment by johncschuster** [comment]
Same^

**Comment by johncschuster** [comment]
Still waiting

**Comment by johncschuster** [comment]
Same^

**Comment by johncschuster** [comment]
Same^

**Comment by johncschuster** [comment]
Still waiting on  PR in RNW upstream to be resolved https://github.com/Expensify/App/issues/26990#issuecomment-1778924300

**Comment by johncschuster** [comment]
@tienifr great question! I'm not really sure myself. I'll let @danieldoglas weigh in on that.

**Comment by danieldoglas** [comment]
Let's wait until we have the new version of upgraded in the app!

**Comment by bernhardoj** [comment]
FYI, this is the [PR](https://github.com/Expensify/App/pull/40960) that upgrades the rn-web that includes the upstream fix from this issue

**Comment by bernhardoj** [comment]
Hey, the PR is currently blocked with the upstream PR from this issue. Adding {passive: true} to the wheel listener broke the scrolling of an inverted list (report screen uses inverted list) and also giving lots of console errors. It's also reported in the upstream issue [here](https://www.github.com/necolas/react-native-web/issues/2658).

https://github.com/Expensify/App/assets/50919443/4cac350c-e78c-4934-bce8-4c6eddbbd12c


Can someone take a look, please?

**Comment by bernhardoj** [comment]
@tienifr I think when you open the PR, you can ask the maintainer whether it's possible to release the PR as soon as it's merged because I think it's a critical issue.

If that's not possible, maybe I can create a patch that revert it to unblock my PR?

cc: @danieldoglas

**Comment by johncschuster** [comment]
I'm having a hard time understanding where we're at with this currently. What are we waiting on?

**Comment by bernhardoj** [comment]
@johncschuster I believe we are waiting on @tienifr to raise a new upstream fix for this issue.

**Comment by johncschuster** [comment]
Awesome. Thank you, @bernhardoj!

**Comment by bernhardoj** [comment]
@danieldoglas do you think I should create a patch to revert https://github.com/necolas/react-native-web/pull/2601 to unblock https://github.com/Expensify/App/issues/33502?

**Comment by johncschuster** [comment]
Awesome. Thanks for the update and PR, @tienifr!

**Comment by bernhardoj** [comment]
Not released yet, so I'm still blocked.

**Comment by johncschuster** [comment]
Thanks for the update, @tienifr! Just so I'm clear, we can now close this issue, right? All we need how to issue payment, correct?

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia based on [this summary](https://github.com/Expensify/App/issues/26990#issuecomment-1717011750).
