### ISSUE TITLE
Scan report does not change currency in report header and sets in correct amount in exiting currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26996]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press Fab > Request Money > Scan
2. Add a receipt and fill in request details
3. Create the request (notice you are redirected to the requestee chat)
4. Click on the scan report preview message
5. Wait for the scan to complete and show requested amount
6. Now edit the request and change the currency.
7. Notice the report header does not change currency and shows incorrect amount.
## Expected Result: 
Currency should be correctly converted and correct amount should be shown or currency should not editable after requesting
## Actual Result: 
Currency is not correctly converted and incorrect amount is shown in report header

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c1e37427-64f9-4cc7-bedb-4ea35a07c660

https://github.com/Expensify/App/assets/43996225/e6b5d619-2814-4812-8a4c-8279177f5d96

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693314327904889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
> The converted amount in local currency is show in header, regardless of the currency selected in request money, which I am guessing is the expected UX.

This is what I am seeing too, I agree this is the expected behavior.
