### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Animated: `useNativeDriver` is not supported because the native animated module is missing

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26992]
![2023-09-07_10-00-14](https://github.com/Expensify/App/assets/32969087/034fe31a-e084-41e2-bd43-a149713e72d2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016259f6e7a833676a</li>
        <li>Upwork Job ID: 1701194832995864576</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26653774</li>
</ul></li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Based on a couple other similar issues, seems this needs to be sent external

**Comment by mananjadhav** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/26992#issuecomment-1711845236) here is good.

🎀 👀 🎀 C+ reviewed.

**Comment by bfitzexpensify** [comment]
Payment summary:

Contributor: @bernhardoj to be paid $750 for work completed and #urgency bonus via Upwork
C+: @mananjadhav to be paid $750 for work completed and #urgency bonus via manual request

**Comment by bfitzexpensify** [comment]
A reminder to complete the BZ checklist when you get a chance @mananjadhav - thanks!

**Comment by mananjadhav** [comment]
I couldn't exactly pinpoint a specific PR that caused this. I also don't think we need a regression test for this one.

**Comment by bfitzexpensify** [comment]
Sounds fair to me. OK, let's close this one out - thanks everyone!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mananjadhav based on BZ summary.
