### ISSUE TITLE
[$500] PR:26447 Web - Task, IOU - Reports are archived when task is completed and IOU is paid

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27012]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User has a task assigned to themselves and IOU requested from another user.

1. Go to https://26447.pr-testing.expensify.com/
2. Open task report.
3. Click Mark as done.
4. Open IOU report.
5. Click Pay elsewhere.

## Expected Result:
When task report is completed and IOU is paid, each respective report will not be archived.

## Actual Result:
When task report is completed and IOU is paid, each respective report is archived.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-2 PR:26447

**Reproducible in staging?:** N

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cc7a03bb-2a06-4f1b-b695-63f443aa0251

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df504b8b7e62cf60</li>
        <li>Upwork Job ID: 1702486310040948736</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Found when validating PR : #26447

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
Waiting for proposals here

**Comment by alexpensify** [comment]
Ok, with this feedback, I'm going to close out. I thought that the PR didn't include this fix, and was broken into it's on GH.
