### ISSUE TITLE
Web - The "Pay" button is displayed to the wrong user after sending few "Money Request" between two users.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to account A and account B on two different devices/browsers.
2. On account A: Send a Money Request to account B with an amount of $1.
      >> Observer: The "Pay" button is displayed for account B - this
      is CORRECT.
3. On account B: Send a Money Request back to account A with an amount of $2.
      >> Observer: Now, the "Pay" button is displayed for account A
      - this is CORRECT.
4. On account A: Send other Money Request to account B with an amount of $3.
      >> Observer: The "Pay" button still displays for account A - this
      is INCORRECT.

## Expected Result:
The "Pay" button should be displayed for account B, since the total amount sent by account A is greater B.

## Actual Result:
The "Pay" button continues to be displayed for account A instead of switching to account B.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be87d845-106f-41d4-ba40-400feea60ad4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693460162684569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tranvantoan-qn** [comment]
The issue was **closed** right away after it was opened. I'm wondering what the new bug creation process will b
