### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Login - /r/undefined shows in address bar after login new account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if already logged in
2. Login with new email
3. Observe browser address bar

## Expected Result:
Url shouldn't show /undefined

## Actual Result:
Url shows /undefined

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1e35f2c5-a6b0-4384-b5fb-5c3ca7144c28

https://github.com/Expensify/App/assets/115492554/4fc40d34-af48-4211-b0d3-198bd16b8272

**Expensify/Expensify Issue URL:**

**Issue reported by:** @situchan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693317302453489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b8fbd47ec15094c</li>
        <li>Upwork Job ID: 1701538687565389824</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26666941</li>
<li>situchan | Reporter | 26666943</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment]
@rmm-fl thanks for your proposal. Could you find out the offending PR? This is a recent regression (within a month or so)

**Comment by situchan** [comment]
> @situchan I don't think @rmm-fl proposal has a correct RCA because this only happen with the new account.

I didn't say their RCA is correct 😄 
Also, this happens on existing account as well

**Comment by situchan** [comment]
> > @situchan I don't think @rmm-fl proposal has a correct RCA because this only happen with the new account.
> 
> I didn't say their RCA is correct 😄 Also, this happens on existing account as well (see @izarutskaya's video)

**Comment by laurenreidexpensify** [comment]
Not overdue

**Comment by laurenreidexpensify** [comment]
Payment summary:

- Bug Reporter > @situchan $50, paid on Upwork
- Contributor > @bernhardoj $500 + 50% urgency bonus, $750, paid on Upwork
- Code Review > @thesahindia $500 + 50% urgency bonus, $750, to be requested in NewDot

**Comment by laurenreidexpensify** [comment]
@thesahindia what are you thinking for regression steps?

**Comment by laurenreidexpensify** [comment]
Sorry @bernhardoj - corrected!

**Comment by laurenreidexpensify** [comment]
Just waiting on @thesahindia for checklist + regression steps above

**Comment by laurenreidexpensify** [comment]
Closing

**Comment by JmillsExpensify** [comment]
$750 payment approved for @thesahindia based on [this summary](https://github.com/Expensify/App/issues/27024#issuecomment-1736898296).
