### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Public room - Unable to copy link as an anonymous user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27039]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new public room.
2. Send a normal message and a link in the room.
3. Open the room in incognito by copy pasting the URL.
4. Right click on the sent link
5. Click on 'copy url to clipboard'

## Expected Result:
Just like the 'copy to clipboard' option, 'copy URL to clipboard' shouldn't require the user to sign in.

## Actual Result:
 It is required to sign-in to copy a URL to clipboard.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e8c2fcde-59ca-4c43-895d-7af95af0c03e

https://github.com/Expensify/App/assets/115492554/345304ce-9721-4d11-b0c2-ce66f88e68e8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @esh-g

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693330719748079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01666b3569fccb8232</li>
        <li>Upwork Job ID: 1701195487091564544</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 26880395</li>
<li>esh-g | Reporter | 26880399</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
# Proposal from @esh-g
## Please re-state the problem
Unable to use `copy URL to clipboard` and `copy email to clipboard` as an anonymous user.
## What is the root cause of this problem?
We have not set the `isAnonymousAction` to `true` for these actions in `contextMenuAction.js`
https://github.com/Expensify/App/blob/a8e2a6a5b57c821ab508f4682ffe60c3717e3095/src/pages/home/report/ContextMenu/ContextMenuActions.js#L145-L148
https://github.com/Expensify/App/blob/a8e2a6a5b57c821ab508f4682ffe60c3717e3095/src/pages/home/report/ContextMenu/ContextMenuActions.js#L158-L160
## What changes should be made to fix this?
We should set the `isAnonymousAction` property for the listed items to be `true` since this action shouldn't require any kind of authentication. We even allow attachments to be downloaded by an anonymous user, therefore I think allowing the copying of `URLs` and `emails` is the right step.

**Comment by esh-g** [comment]
@izarutskaya I had posted a proposal in slack. Please post it here if possible.. Or let me know if I should do so

**Comment by izarutskaya** [comment]
# Proposal from @esh-g
## Please re-state the problem
Unable to use `copy URL to clipboard` and `copy email to clipboard` as an anonymous user.
## What is the root cause of this problem?
We have not set the `isAnonymousAction` to `true` for these actions in `contextMenuAction.js`
https://github.com/Expensify/App/blob/a8e2a6a5b57c821ab508f4682ffe60c3717e3095/src/pages/home/report/ContextMenu/ContextMenuActions.js#L145-L148
https://github.com/Expensify/App/blob/a8e2a6a5b57c821ab508f4682ffe60c3717e3095/src/pages/home/report/ContextMenu/ContextMenuActions.js#L158-L160
## What changes should be made to fix this?
We should set the `isAnonymousAction` property for the listed items to be `true` since this action shouldn't require any kind of authentication. We even allow attachments to be downloaded by an anonymous user, therefore I think allowing the copying of `URLs` and `emails` is the right step.

**Comment by bfitzexpensify** [comment]
Sending external

**Comment by bfitzexpensify** [comment]
Couple of proposals ready for review when you get a chance @sobitneupane - thank you!

**Comment by sobitneupane** [comment]
Thanks for proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/27039#issuecomment-1711935533) from @esh-g looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by bfitzexpensify** [comment]
How does the [proposal](https://github.com/Expensify/App/issues/27039#issuecomment-1711935533) from @esh-g look @youssef-lr?

**Comment by bfitzexpensify** [comment]
Not sure why Melv re-added the overdue label

**Comment by bfitzexpensify** [comment]
Bump for review @youssef-lr

**Comment by bfitzexpensify** [comment]
Friendly bump @youssef-lr!

**Comment by youssef-lr** [comment]
assigned @esh-g!

**Comment by esh-g** [comment]
@sobitneupane  @youssef-lr  PR is here: https://github.com/Expensify/App/pull/28261

**Comment by esh-g** [comment]
@youssef-lr @bfitzexpensify The PR has not been reviewed for almost 5 days now... Sobit seems to be out on leave... Since this is a simple PR, could you please have a look at it instead? I would also like to ask you if the urgency bonus would be reconsidered in this case...

**Comment by sobitneupane** [comment]
Sorry for the delay @esh-g. I was sick and could not review the PR. I will review the PR today.

**Comment by bfitzexpensify** [comment]
Switching this to daily so I'm aware of it and action it on 10/10

**Comment by bfitzexpensify** [comment]
@esh-g since there were no issues with the PR raised and the delay was due to illness, I am going to consider this eligible for the urgency bonus.

**Comment by bfitzexpensify** [comment]
Payment due for this on Tuesday.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/22321
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think this can be considered as regression. https://github.com/Expensify/App/pull/22321/files#r1349995627
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

N/A
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Create a new public room.
2. Send a message as a url and an email
3. Go to room details and copy the room url from QR code screen.
4. Go to a guest tab and paste the url
5. Make sure we are able to copy the link and email by right clicking on them.

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment]
Payment summary:

Reporter: @esh-g - $50 to be paid via Upwork
Contributor: @esh-g - $750 to be paid via Upwork
C+: @sobitneupane - $750 to be paid via manual request

**Comment by bfitzexpensify** [comment]
Payments complete, regression steps proposed via https://github.com/Expensify/Expensify/issues/325765, think we're all done here

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/27039#issuecomment-1756409704

Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/27039#issuecomment-1756409704).
