### ISSUE TITLE
[$500]  LHN - Сonversation is not displayed in bold when new messages are received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27038]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in using any login A
4. Navigate to the concierge conversation
5. Open https://staging.new.expensify.com/
in your browser
6. Log in using any login B
7. Send a message from user B to user A
8. Under user A in the application, navigate to Settings/Preferences
7. Activate the "Force offline" mode
8. Send a message from user B to user A
9. Deactivate the "Force offline" mode
10. Focus on the conversation with the concierge

## Expected Result:
When receiving new messages when exiting offline mode, the conversation name should become bold in the LHN

## Actual Result:
When receiving new messages when leaving offline mode, the conversation is not displayed in bold in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d745267a-7049-498f-934c-6ad2fcc0f27f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01005d8dd45f8b4890</li>
        <li>Upwork Job ID: 1700237159903662080</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26684669</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment]
@allroundexperts have you had a chance to review the proposal?

**Comment by abekkala** [comment]
@allroundexperts friendly bump on reviewing the Proposal that has been provided :)

**Comment by abekkala** [comment]
@hayata-suenaga do you agree we can just close this issue out?

**Comment by hayata-suenaga** [comment]
@allroundexperts could you double check on [this comment](https://github.com/Expensify/App/issues/27038#issuecomment-1721391738)?

**Comment by abekkala** [comment]
@allroundexperts can you please confirm the above?

**Comment by abekkala** [comment]
@allroundexperts can you please address the comment above (https://github.com/Expensify/App/issues/27038#issuecomment-1721391738?)? 

cc: @hayata-suenaga
