### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Chat - Flag as offensive page does not disappear when deleting the Message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From User A Send a message to User B.
2. From User B, Go to reply in thread on the message sent from User A. > Then Click on Flag as Offensive button from the reaction menu.
3. Now Delete the message from User A while the Flag as offensive page is still open from User B.

## Expected Result:
The opened Flag as offensive page from User B. should be closed when User A deletes the message. It should show the `Page Not Found` error message.

## Actual Result:
The Flag as offensive page remains open.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/82d93680-e12d-47c3-a59d-806cc80da380

https://github.com/Expensify/App/assets/115492554/93d87411-fd1d-47e4-b62f-b54655df9b8e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692641567668079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9ee295f5f5cd370</li>
        <li>Upwork Job ID: 1702099690396909568</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26722920</li>
<li>tienifr | Contributor | 26722922</li>
<li>daveSeife | Reporter | 26722924</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
I can repro this, but I am not convinced this is a bug - it seems like it's a delay. I'm asking the Engineer who implemented the `Flag as offensive` button for a second opinion!

**Comment by jliexpensify** [comment]
@tienifr @daveSeife - I just spoke to Daniel, who implemented the `Mark as offensive` feature, and confirmed that this behaviour is intentional (comment [here](https://github.com/Expensify/App/issues/20674#issuecomment-1614869167))

We chose not to fix it in #20674, so the same goes here.

**Comment by jliexpensify** [comment]
Spoke to Daniel again, we'll fix this for consistency's sake.

**Comment by jliexpensify** [comment]
@dangrous - my assumption is that we'd want to be consistent across the board, so we'll show `page not found` upon deletion of the offensive comment. Can I confirm this is what you're thinking too? Thanks!

**Comment by srikarparsi** [comment]
Looks good to me as well, assigning you to the issue @tienifr

**Comment by jliexpensify** [comment]
It should, I'd imagine!

**Comment by jliexpensify** [comment]
Sorry, missed this! @0xmiroslav can you complete the checklist please?

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter: @daveSeife $50
- Contributor: @tienifr $500 + $250
- C+: @0xmiroslav $500 + $250

[Upwork job](https://www.upwork.com/jobs/~01f9ee295f5f5cd370)

**Comment by jliexpensify** [comment]
All paid except for @0xmiroslav . Did you want me to close this?
