### ISSUE TITLE
Chat - Emoji suggestions are not displayed when user searches "animals"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go https://staging.new.expensify.com/
2. Tap on a report
3. Tap on emoji picker
4. Search for "animal" Or "animals"
5. Search "flower"
6. Search " Rose"

## Expected Result:
When user searches for "flower" in general or "rose" in specific, emoji suggestions are displayed. So, when user searches for "animals", emoji suggestions related to animals must be displayed

## Actual Result:
When user searches for "flower" in general or "rose" in specific, emoji suggestions are displayed. But, when user searches for "animals", emoji suggestions related to animals are not displayed. No result found message only shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/12af1c1e-d9ae-41cd-97ba-a470ba026dc8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
I don't think this is a bug

**Comment by anmurali** [comment]
Yea, this doesn't feel worth fixing.
