### ISSUE TITLE
Clicking on close on error for an invalid mobile number added to Workspace does not remove the error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to invite page of workspace
2. Invite an invalid number like +3233232432
3. After clicking next and invite the page redirects to workspace members page.
4. Click on close button on the right of the error message for this failed member
## Expected Result: 
On clicking the close on error, error and member should disappear.
## Actual Result: 
On clicking close on error, error and member does not disappear

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/94a8034e-15e3-49e0-8948-87a07dbc3d71

https://github.com/Expensify/App/assets/43996225/bd8b7d4f-f30f-4c09-a2e0-acfc0d31ef49

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693331352587509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal from @c3024
### Please re-state the problem that we are trying to solve in this issue.
When clicking close button on the error for an invalid workspace member with error, the error and the member does not disappear.
### What is the root cause of that problem?
Root cause of the problem is that we are not passing the `accountID` properly here
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/pages/workspace/WorkspaceMembersPage.js#L240
because with the new `SelectionList` and `CheckboxItem` the `item` here does not have `accountID`
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/pages/workspace/WorkspaceMembersPage.js#L308-L327
This `onClose` is triggered from here for the item
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/components/SelectionList/CheckboxListItem.js#L22
and the `item` does not have the `accountID` field.
### What changes do you think we should make in order to solve the problem?
We should change the `accountID` to the `keyForList` used here
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/pages/workspace/WorkspaceMembersPage.js#L309
in
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/pages/workspace/WorkspaceMembersPage.js#L240
to
```js
Policy.clearAddMemberError(props.route.params.policyID, item.keyForList);
```
and similarly here as well
https://github.com/Expensify/App/blob/4a632ba570271cf19c6c615b5071dc93422d8b73/src/pages/workspace/WorkspaceMembersPage.js#L238
### What alternative solutions did you explore? (Optional)
If we would like to reduce the lack of clarity of passing `keyForList` as `accountID` we can push a field called `accountID` to the `item` in the result specified above and retain the Policy functions in the `dismissError` function of `WorkspaceMembersPage` as it is.

**Comment by trjExpensify** [comment]
Closing in favour of the linked issue.
