### ISSUE TITLE
[$1000] Android - Mark as unread not working for scan receipts , request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to fab button -> request money ->scan
2. Pick a file from gallery or click an image with camera
3. Share to some user.
4. Now on the redirected page, it shows 'Receipt scan in progress..' list card.
5. Long press and click on mark as unread.

## Expected Result:
Green line above the scan receipt file, after mark as unread.

## Actual Result:
Mark as unread not working for scan receipts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2f1a179e-59df-4a95-9d13-63fc2acf3402

https://github.com/Expensify/App/assets/93399543/18a7a142-b17e-49a5-aae5-489aa5294451

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1693852651050589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ed10ac6e95fa97e</li>
        <li>Upwork Job ID: 1700215006490329088</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by robertKozik** [comment]
Waiting for proposals 👀

**Comment by ayazalavi** [comment]
@robertKozik writing my proposal.

**Comment by robertKozik** [comment]
no proposal yet

**Comment by adelekennedy** [comment]
pending proposal still

**Comment by robertKozik** [comment]
waiting for proposals

**Comment by adelekennedy** [comment]
increasing price

**Comment by shubham1206agra** [comment]
This is fixed by https://github.com/Expensify/App/pull/28533
Please recheck and close

**Comment by adelekennedy** [comment]
@robertKozik do you agree with [this](https://github.com/Expensify/App/issues/27048#issuecomment-1742366944)? If so i think we should close!

**Comment by robertKozik** [comment]
@adelekennedy I'm currently checking it!

**Comment by robertKozik** [comment]
@adelekennedy Checked on web and android - mark as unread is working on scan receipts. I think we can wait until the #28533 will be deployed to staging before we close the issue

**Comment by adelekennedy** [comment]
de-prioritizing for the issue above

**Comment by robertKozik** [comment]
Bump @adelekennedy as this issue can be closed. #28533 fixed it

**Comment by adelekennedy** [comment]
Let's close! In that case payment is still due for @ashimsharma10

**Comment by ashimsharma10** [comment]
@adelekennedy I cant find the correct link, seems the above is broken. Can you send me offer directly? 

Thanks!

**Comment by adelekennedy** [comment]
@ashimsharma10 I would but it seems we have two Ashim S contributors on Upwork 😅 can you end me a screenshot of your Upwork profile so I can match the offer to your profile?

**Comment by ashimsharma10** [comment]
<img width="654" alt="Screenshot 2023-10-09 at 9 30 16 PM" src="https://github.com/Expensify/App/assets/43598308/4c2ebc24-52d7-448a-af8f-781d77ce9df6">
I'm this guy. 😅

**Comment by adelekennedy** [comment]
Thank you! I had a 50% chance of getting it right - but didn't want to pay the wrong person

**Comment by adelekennedy** [comment]
<img width="592" alt="Screenshot 2023-10-09 at 8 50 08 AM" src="https://github.com/Expensify/App/assets/60450566/4024c8e0-26fe-4a53-a45a-f68b09960e8f">

so strange - this comment came across in my email but it seems you were able to apply afterall. Paying now!
