### ISSUE TITLE
[HOLD for payment 2023-09-21] [$500] Web - "An unexpected error occurred. Please try again." when Clicking "Pay Elsewhere"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Request money and select the newly created workspace
3. Delete the workspace
4. Click on requested money
5. select and click "Pay Elsewhere"

## Expected Result:
The error should not appear

## Actual Result:
"An unexpected error occurred. Please try again."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Error-pay-elsewhere.webm](https://github.com/Expensify/App/assets/93399543/bfaa94b4-eff9-44f8-a017-1920a699c8fe)

![image (35)](https://github.com/Expensify/App/assets/93399543/2d97566a-2e37-42d7-bb5e-db0d235b20cf)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693854830712439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hm, strange. Not sure why this auto-assigned me since @sophiepintoraetz is already assigned. Going to remove myself, but feel free to add me back if I'm missing something.

**Comment by garrettmknight** [comment]
@hichamcc did this also leave you with unread notifications you can't clear?

**Comment by hichamcc** [comment]
@garrettmknight No

**Comment by francoisl** [comment]
Looks like this is ready for payment, @allroundexperts can you fill out the checklist above please?

**Comment by sophiepintoraetz** [comment]
@dukenv0307 and @hichamcc - can you please apply for the job [here](https://www.upwork.com/jobs/~013daf9a4ab2be8102)? Thank you!

**Comment by hichamcc** [comment]
@sophiepintoraetz  done

**Comment by sophiepintoraetz** [comment]
all right, Payouts due:

Issue Reporter: $50 (done)
Contributor: $750 @@duken0307 - offer sent
Contributor+: $750 @allroundexperts - raise a ND request once the checklist is done!

Eligible for 50% #urgency bonus? Y

**Comment by sophiepintoraetz** [comment]
@dukenv0307 - can you please accept the offer?

**Comment by sophiepintoraetz** [comment]
Paid.

**Comment by JmillsExpensify** [comment]
$750 payment for @allroundexperts approved based on BZ summary.
