### ISSUE TITLE
Request money - JOD currency adds extra '0' at the end of any amount

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
step 1: click on + FAB
step 2: click on request money
step 3: choose 'JOD' currency
step 4: select a user and request money
step 5: observe amount when request page opens

## Expected Result:
there will be only two digit after . in the money amount

## Actual Result:
there are three digit after . in the money amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/48b9d95c-d7a6-41bd-bd04-be52117bada9

https://github.com/Expensify/App/assets/115492554/add92c8b-3a14-4b1e-90a5-6c6168313071

**Expensify/Expensify Issue URL:**

**Issue reported by:** @lidiyakelay

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693334339339819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
I don't think this is a bug. Subunit of JOD is 0.001

**Comment by joekaufmanexpensify** [comment]
Yep, agreed. I confirmed JOD has a sub-unit of .001, so I don't think this is a bug. Closing!
