### ISSUE TITLE
[HOLD for payment 2023-10-23] 🟡 [$500] Add stylized receipts for distance requests

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27050]
One thing I think we need to re-visit now that we shipped distance v1 is the receipt. For instance, this was recommended in the original design doc, though during the review process it was deemed unnecessary.

<img src=https://github.com/Expensify/App/assets/1127863/76977611-f54d-47e8-8b74-4b5d1a093536  width=300px>

I think in hindsight that decision hasn’t turned out to be a great one. Reason being, you have to kind of deduce what the points on the map are, so what is point A and what is point B. For SBE, it was somewhat easy since the event looks like it was close to the Burbank airport? But yeah, I think a core part of mileage is knowing where someone went, whether it’s from A to B, or A to B to C.

As a result, I think we need to:

 - Utilize the stylized receipt pattern that we've settled on for eReceipts
 - Apply the same foundational styling for distance request
 - Print the sum of a user's `Start`, `Stop`, and `Finish` way points, each on their own row
 - All while still showing the core information about the request, such as amount, date and `distance` merchant. 

I'm going to assign the `internal` label, as this is dependent on related internal initiatives and Expensify employees have the most context. We can involve `external` as soon as the scope and todos are clear. 

cc distance project team @neil-marcellini @hayata-suenaga @arosiclair @trjExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b483120a2e8ed4dd</li>
        <li>Upwork Job ID: 1700221182911156224</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
I think the waypoints are stored in Transaction that is returned from the `OpenReport` and other relevant API commands?

I think edits that need to be made are in the NewDot side. Let's make this external 🚀 

@Expensify/design could you double check the design?

**Comment by mollfpr** [comment]
@hayata-suenaga @JmillsExpensify I think this issue missing `Help Wanted` label.

**Comment by hayata-suenaga** [comment]
Thank you for pointing that out. I added the `Help Wanted` label 🙇

**Comment by trjExpensify** [comment]
Let's assign the `Design` label to this and make sure we complete getting an updated style for this in-line with the eReceipts.

**Comment by neil-marcellini** [comment]
I'm going to take this over and work on it internally because there are a lot of considerations related to internal knowledge such as design docs. I'm going to start a Slack thread to ask some questions.

**Comment by neil-marcellini** [comment]
I figured out how to get the transaction linked to the report attachment. Then I rendered an EReceipt component instead of the normal attachment view if it's a distance request transaction. I also got the receipt image rendering in that new component.

Next time I'll start building out the rough UI and displaying the data from the transaction

**Comment by JmillsExpensify** [comment]
@Expensify/design Building on @trjExpensify's comment from above, can we get all the specs for the UI, including dimensions and colors to make sure we don't accidentally make any mistakes here?

**Comment by shawnborton** [comment]
Yup, agree that we can get all of the specs together. But that being said, let's give this one a quick revisit and take a look at it alongside of the eReceipt design.

**Comment by shawnborton** [comment]
Yup, agree that we can get all of the specs together. But that being said, let's give this one a quick revisit and take a look at it alongside of the eReceipt design.

**Comment by JmillsExpensify** [comment]
Ah ok fair enough. Who's leading that? Should we update this issue and put it on hold for the time being?

**Comment by shawnborton** [comment]
Added a little scoop of jam to your thread above!

**Comment by neil-marcellini** [comment]
I ran out of time to work on this yesterday.

**Comment by neil-marcellini** [comment]
I made great progress on this today. I almost have all the UI components on the screen. I need to finish adding the logo and guaranteed eReceipt text, then add the background image and get everything moved into the right place.

**Comment by neil-marcellini** [comment]
More progress today. I will get it up for review on Monday. I [asked](https://github.com/Expensify/App/pull/27204) for an initial design review on the PR.

**Comment by neil-marcellini** [comment]
I'm starting on this again now

**Comment by neil-marcellini** [comment]
Yesterday I fixed the offline creation flow for distance requests since it was broken. I also found a few more things that need to be fixed for eReciepts to work offline.

**Comment by neil-marcellini** [comment]
I fixed the offline flow and started testing on all platforms. I think I found an android specific bug but I haven't had time to debug and fix it yet. I'm struggling to run android in a timely manner.

**Comment by shawnborton** [comment]
I think Neil is still working through this one

**Comment by neil-marcellini** [comment]
I fixed the errors on android and the styling of the background image which was missing there. Tomorrow I can hopefully record the final testing videos and put it up for review.

**Comment by neil-marcellini** [comment]
The PR was merged!

**Comment by JmillsExpensify** [comment]
@mollfpr I think we should have a regression test for this one, as it's a core flow and piece of compliance in the app. Do you agree and can you suggest a test?

**Comment by neil-marcellini** [comment]
100% we need a regression test, especially since it's already broken 🙈; I'm working on a fix.

**Comment by mollfpr** [comment]
Regression step for this issue:

**_Distance request with 2 waypoints_**

1. Click the green plus, request money, distance
2. Enter valid start and finish locations
3. Create the request
4. Open the money request report
5. Click on the distance request to open the transaction report
6. Click on the route image
7. **_Verify_** that the distance eReceipt is shown and looks good

**_Distance request with 12 waypoints_**

1. Click the green plus, request money, distance
2. Enter valid start and finish locations, plus 10 stops
3. Create the request
4. Open the money request report
5. Click on the distance request to open the transaction report
6. Click on the route image
7. **_Verify_** that the distance eReceipt is shown and that you can scroll down to see the entire eReceipt

---

Regression step for https://github.com/Expensify/App/issues/28289 and https://github.com/Expensify/App/issues/28949

1. Go offline
2. Click the green plus, request money, distance
3. Enter a valid address for start and finish waypoints
4. **_Verify_** that you can click next
5. Select a workspace
6. **_Verify_** that all information shows or is TBD
7. Click request
8. **_Verify_** that the report preview shows a pending receipt image with the amount and miles as TBD
9. Click the report preview
10. **_Verify_** that the request shows as distance, with the amount and miles as TBD
11. Click on the request
12. **_Verify_** that the request shows as distance, with the amount and miles as TBD
13. _**Verify**_ that there's not **Merchant** input in the forms
14. Go online
15. **_Verify_** that all pending data fills

**Comment by JmillsExpensify** [comment]
Those look good to me. I'll get an issue created and add them.

**Comment by JmillsExpensify** [comment]
> 100% we need a regression test, especially since it's already broken 🙈; I'm working on a fix.

@neil-marcellini for the payment, are you saying that we've already had a regression and the should be reflected in payment?

**Comment by neil-marcellini** [comment]
Yes there was already a regression but we think it was due to some weird git merging behavior, and the mistake appears to have come from another PR. I commented about the regression [here](https://github.com/Expensify/App/commit/aa07b9c77dd0e2a317327dd0502a51abc1cc2faf#r130356775). No need to reduce pay for this issue.

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @mollfpr for PR review.

**Comment by JmillsExpensify** [comment]
@mollfpr Please raise a request in NewDot, going to close this one as I've created the regression test.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mollfpr based on summary above.
