### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Address remaining design inconsistencies for distance requests

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27052]
From a post by @shawnborton (cc @dannymcclain)
![image (7)](https://github.com/Expensify/App/assets/1127863/f71052cf-7b26-4091-86b4-0689571e768e)

Changed required:
 - Each push-to-page row has margin-bottom: 8px - let’s get rid of that so it’s a bit more compact and matches existing styles
 - the map image itself has a bunch of vertical margin (20px) and thus it feels quite far away from the push row below it which also has vertical margin. Let’s make the vertical margin on the map image something like 8px or 12px
 - The “To” field above the workspace has a height of 32px. Let’s remove the height and just have some margin-top, but no need for margin below as the workspace row (avatar + name) already has vertical margin. This change should be applied everywhere we have a “To” row
 - Let’s make the map preview image use the same border radius as other receipt previews, which I think is 16px
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a22578e8f0e37d00</li>
        <li>Upwork Job ID: 1700221988509253632</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26849648</li>
<li>akinwale | Contributor | 26849649</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
> Let’s make the vertical margin on the map image something like 8px or 12px

Coming back to this one, we should decide one way or the other.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Design inconsistencies for distance requests.

### What is the root cause of that problem?
None. New feature.

### What changes do you think we should make in order to solve the problem?
> Each push-to-page row has margin-bottom: 8px - let’s get rid of that so it’s a bit more compact and matches existing styles
Update `MoneyRequestConfirmationList` and conditionally remove the `styles.mb2` style from each displayed `MenuItemWithTopDescription` if the distance request condition is true.

> The map image itself has a bunch of vertical margin (20px) and thus it feels quite far away from the push row below it which also has vertical margin. Let’s make the vertical margin on the map image something like 8px or 12px
Update `styles.mapPendingView` with the new vertical margin.

> The “To” field above the workspace has a height of 32px. Let’s remove the height and just have some margin-top, but no need for margin below as the workspace row (avatar + name) already has vertical margin. This change should be applied everywhere we have a “To” row
Update MoneyRequestConfirmationList and conditionally set the height and margins if it is a distance request.

> Let’s make the map preview image use the same border radius as other receipt previews, which I think is 16px
Change `borderRadius` for `styles.mapView` to 16.

### What alternative solutions did you explore? (Optional)
None.

**Comment by situchan** [comment]
@akinwale thanks for your proposal. Can you please share demo screenshot after applying your changes?

**Comment by akinwale** [comment]
> @akinwale thanks for your proposal. Can you please share demo screenshot after applying your changes?

@situchan Here's a screenshot with my changes applied.

![27052-screenshot1](https://github.com/Expensify/App/assets/4160319/b37b4876-d7de-431b-b38b-55212ee100aa)

**Comment by akinwale** [comment]
@situchan Some additional notes about the margins used. Everything else updated to follow the original post.

> the map image itself has a bunch of vertical margin (20px) and thus it feels quite far away from the push row below it which also has vertical margin. Let’s make the vertical margin on the map image something like 8px or 12px

* Used 8px margin here for both top and bottom.

> The “To” field above the workspace has a height of 32px. Let’s remove the height and just have some margin-top, but no need for margin below as the workspace row (avatar + name) already has vertical margin. This change should be applied everywhere we have a “To” row

* Used 8px margin for the top here.

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Distance Request has design inconsistencies like extra spacing between fields and map.

### What is the root cause of that problem?
- It was implemented this way only.

### What changes do you think we should make in order to solve the problem?
### Solution for 1st and 2nd Points
```
1. Each push-to-page row has margin-bottom: 8px - let’s get rid of that so it’s a bit more compact and matches existing styles
2 .The map image itself has a bunch of vertical margin (20px) and thus it feels quite far away from the push row below it which also has vertical margin. Let’s make the vertical margin on the map image something like 8px or 12px
```

- We will update in `MoneyRequestConfirmationList` with below styles:
1. `styles.confirmationListMapItem` (`spacing.mv3` bcoz we want to update vertical spacing only and as all the items have 24px spacing in between so this keeps the consistency )

```diff
- {...spacing.m5, height: 200, }
+ {...spacing.m5, ...spacing.mv3, height: 200, } 
```

2. Remove each `styles.mt2 / styles.mb2` which is used with `styles.moneyRequestMenuItem`.

### Solution for 3rd Point
```
3. Let’s make the map preview image use the same border radius as other receipt previews, which I think is 16px
```

- For radius of map referring `styles.reportActionItemImages` which is 16px.
1. We will update `borderRadius` in `styles.mapView` from `20` to `16`. (this will update in other places also.)

### Solution for 4th Point (I have two solutions)
```
4. The “To” field above the workspace has a height of 32px. Let’s remove the height and just have some margin-top, but no need for margin below as the workspace row (avatar + name) already has vertical margin. This change should be applied everywhere we have a “To” row
```

1. Update `styles.optionsListSectionHeader` to `{...spacing.mv1}`. (Such that it doesn't cause much UI regression in other places like below). But this will create inconsistency in UI in other places.

<img width="387" alt="Screenshot 2023-09-09 at 10 08 20 AM" src="https://github.com/Expensify/App/assets/78416198/d2a0859d-5d7c-4b7c-8445-f7b46106acb4">

>  Above issue will emerge if we only give marginTop to `styles.optionsListSectionHeader`

2. Add a `overrideHeaderStyle` to `sections`
```js
    sections.push({
        title: translate('common.to'),
        ...rest,
        overrideHeaderStyle: {...spacing.mv1},
    });
```

and in `BaseOptionsList` update

```diff
- const renderSectionHeader = ({section: {title, shouldShow}}) => {
+ const renderSectionHeader = ({section: {title, shouldShow, overrideHeaderStyle}}) => {
- <View style={[styles.optionsListSectionHeader, styles.justifyContentCenter]}>
+ <View style={[overrideHeaderStyle || styles.optionsListSectionHeader, styles.justifyContentCenter]}> // we can add additional checks if required
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by shawnborton** [comment]
> But this will create inconsistency in UI in other places.

Good catch, so maybe we do need to give it at least 4px bottom margin then.

**Comment by dannymcclain** [comment]
Not overdue. ☝️

**Comment by situchan** [comment]
As this is straightforward style fix, I think we can go with first proposal.
@akinwale's [proposal](https://github.com/Expensify/App/issues/27052#issuecomment-1712142719) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by jeet-dhandha** [comment]
@situchan any thoughts on my proposal?

**Comment by situchan** [comment]
> @situchan any thoughts on my proposal?

I checked your proposal and not found any significant difference from former proposal.

**Comment by jeet-dhandha** [comment]
Okay, just wanted to stop a regression from happening which Is mentioned in my Proposal.

**Comment by situchan** [comment]
> Okay, just wanted to stop a regression from happening which Is mentioned in my Proposal.

yeah, regression fix is one of the main factors to pick up the proposal. But not for this one as they will be easily caught during PR review and testing.

**Comment by jeet-dhandha** [comment]
I also had that confidence 😓, which broke today where i forgot to test the PR for longer sentences and reviewers also forget and it caused a regression. So saying from experience, the testing might miss this regression.

**Comment by jeet-dhandha** [comment]
You can go with @akinwale ‘s Proposal, that I don’t mind. Just that be careful while testing and try to make the Proposers PR as regression free as we can.

**Comment by akinwale** [comment]
@shawnborton Are the preview (date, description, etc) changes applicable to "only" distance requests? Trying to clarify because other money request previews share the same layout, sans the map view.

**Comment by shawnborton** [comment]
Those things are definitely applicable to all request types.

**Comment by shawnborton** [comment]
And yeah, ideally we have them as consistent as possible across all of them.

**Comment by joelbettner** [comment]
> @akinwale's https://github.com/Expensify/App/issues/27052#issuecomment-1712142719 looks good to me.

I'm good with @akinwale's proposal.

**Comment by akinwale** [comment]
@situchan My [PR](https://github.com/Expensify/App/pull/28110) is ready for review.

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Issue reporter: N/A
 - Contributor: @akinwale $500
 - Contributor+: @situchan $500

**Comment by akinwale** [comment]
> Payment summary:
> 
> * Issue reporter: N/A
> * Contributor: @akinwale $500
> * Contributor+: @situchan $500

There were a couple of days of delays during the PR review, and before the eventual PR merge action. Taking these into account, would this possibly be considered eligible for the urgency bonus? Thanks.

**Comment by situchan** [comment]
3 business days of delay was from internal review.
Here's proof:

https://github.com/Expensify/App/assets/108292595/0961e3e7-d993-4113-b839-7aa606a7c85a

**Comment by JmillsExpensify** [comment]
@joelbettner Can to confirm these more recent comments?

**Comment by joelbettner** [comment]
@JmillsExpensify Yep, it took me a while to get around to reviewing. I've been completely inundated with auto assigned issues and reviews all the while trying to get higher priority code written for other projects.

**Comment by JmillsExpensify** [comment]
> Payment summary:
> 
> * Issue reporter: N/A
> * Contributor: @akinwale $750
> * Contributor+: @situchan $750

Ok great thanks! I've updated the summary.

**Comment by JmillsExpensify** [comment]
Still waiting on the BZ checklist from @situchan though in the meantime, I've paid out @akinwale.

**Comment by situchan** [comment]
This is just design inconsistency, not bug. I don't think regression test applies here.
