### ISSUE TITLE
[$500] Request money: Changing default currency for workspace is not refelected when requesting a money if there is previous unpaid money

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#27060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click request money
4. Enter the amount and select a workspace from the list
5. Confirm the requested money
6. Observe the currency from the IOU report
7. Go to Settings > workspace
8. Select the workspace from the list which should be the same as the one money request that has been sent
9. Click setting
10. Change the default currency
11. Do the same steps from 2 to 6
12. The new default currency is not reflected in the IOU report

## Expected Result:

A report not in the same currency as the workspace should be marked as a violation

## Actual Result:

Nothing points out the different currency

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/e13f3359-5008-4f44-bde3-5228302f7284

https://github.com/Expensify/App/assets/38435837/b9fdc62f-e565-44bc-b71f-924574635390

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693845090453449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b90f99e542d09e16</li>
        <li>Upwork Job ID: 1700249522279403520</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
Seems like a backend change as mostly merging of money requests is done there.

**Comment by abekkala** [comment]
@JmillsExpensify there is an issue occurring with double assignments happening after the initial Bug label. I'm unassigning myself as the second person.

**Comment by JmillsExpensify** [comment]
I agree we should fix this one, minimally when you add the second request to the report after the workspace currency has been changed.

**Comment by JmillsExpensify** [comment]
Still awaiting proposals.

**Comment by JmillsExpensify** [comment]
Still awaiting proposals

**Comment by JmillsExpensify** [comment]
Whoops, haha by waiting proposals I mean, waiting on someone internal to take a look.

**Comment by JmillsExpensify** [comment]
Hmm, I'm actually not sure why this issue has the internal label. Opening back up for proposals.

**Comment by JmillsExpensify** [comment]
I think the price is matched with the priority of this issue.

**Comment by devrari** [comment]
this looks like a backend issue.
Message after  request money is always coming on initial default currency, even if we change the currency. 
<img width="1680" alt="Screenshot 2023-11-15 at 11 35 13" src="https://github.com/Expensify/App/assets/4333876/8344be8a-9d30-486d-80eb-d572808110e8">

**Comment by JmillsExpensify** [comment]
@aldo-expensify thoughts on that last comment?

**Comment by Tony-MK** [comment]
I did some investigation yesterday and eventually came to the conclusion that this is most likely a BE issue like @devrari 😄.

The currency of the `iouReport` is used in the BE to convert the currency of the money request to display the amount according to the default workspace currency. The `iouReport` is created on the server, and it uses the policy's currency at the time of creation. However, the currency of the IOU does not change according to the default workspace currency. The only `iouReport` parameter the `requestMoney` endpoint requires when creating a money request is the ID, which is either an existing one from the report or, if new, a generated one. There is no specific action, endpoint, or function on the FE to edit the currency of the IOU on the BE. Hence, the currency on the `ReportPreview` component can't be changed until the existing IOU is either paid or deleted.

I think the best solution is that once the workspace default currency changes, update the currency of the `iouReport` from the BE, if it exists. Also, send back updated onyx data to update the message on the `ReportPreview` component.

If it is challenging, I suppose we could also delete the IOU, create another one, and link the money requests to the IOU.

**Comment by aldo-expensify** [comment]
Sorry @JmillsExpensify  but I haven't been able to have a look here. The contributors seems to have investigated and are pointing to the backend, so it may be a good time to add `Internal` and get an engineer auto assign to investigate further?

**Comment by JmillsExpensify** [comment]
Updated the labels per [this convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1700550452209509) in Slack.

**Comment by aldo-expensify** [comment]
@JmillsExpensify I think the labels didn't work here as expected? An Expensify engineer should have been assigned with `Internal`, right?

**Comment by aldo-expensify** [comment]
@JmillsExpensify can you help me confirm that I'm understanding correctly the problem and the expected outcome?

I did this:

1. Created a workspace (default currency USD)
2. Created a money request in the policyExpenseChat
3. I see the money request's preview in USD
4. Change the currency of the workspace to CAD

Is the expectation that the UNPAID money requests update their previews to be shown in CAD?

I think the step of creating a second money request is irrelevant here.

**Comment by JmillsExpensify** [comment]
> Is the expectation that the UNPAID money requests update their previews to be shown in CAD?

Yes, correct.

**Comment by aldo-expensify** [comment]
I noticed that in OldDot we also don't update the currency for Open/Processing reports, do we want this to also apply for workspaces that are not Free? (OldDot workspaces)

**Comment by JmillsExpensify** [comment]
I think we do.

**Comment by aldo-expensify** [comment]
Started working on this here: https://github.com/Expensify/Auth/pull/9317

**Comment by aldo-expensify** [comment]
Made PR ready for review: https://github.com/Expensify/Auth/pull/9317

**Comment by aldo-expensify** [comment]
I'll have a look at the Violations design doc to decide how to implement this. Meanwhile... should create a new GH issue? or just update this one? I'm guessing the there will be a frontend and a backend part of this.

**Comment by aldo-expensify** [comment]
I still haven't read the violations design doc, I'll get to it as soon as possible

**Comment by JmillsExpensify** [comment]
All good, thanks!

**Comment by aldo-expensify** [comment]
Chatted with @JmillsExpensify about the priority of this issue, and we agreed with closing it.
