### ISSUE TITLE
[$500] Web - Delete option stays after deleting an IOU and if clicked again RBR without any way to remove it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27071]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a money request
2. Click on the IOU preview component twice to get into the transaction thread
3. Click on the merchant field and update it by adding something and saving
4. Click on the three dots at the top right corner and click on delete
5. Click on the three dots at the top right corner again and click on delete again
6. Observe the RBR on LHN

## Expected Result:
There should not be a delete option after user has already deleted the IOU and an RBR should not appear without any way to remove it

## Actual Result:
There is a delete option after user already deleted an IOU and an RBR shows up on LHN without any way to remove it if user clicks on the delete option again after deleting it the first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a806e5a2-3706-4254-8f12-dac0b404a858

https://github.com/Expensify/App/assets/93399543/ed70291e-4982-49af-a508-5462d0c55c4d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693845904666219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fcf45f4a3f7aaa3</li>
        <li>Upwork Job ID: 1700259629186359296</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
thanks @allroundexperts ! Closing.
