### ISSUE TITLE
mWeb - IOU- User is shown options to request money to Workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap request money
4. Enter amount
5. Tap next to note "Workspace" in options
6. Navigate to LHN
7. Tap fab
8. Tap Split bill
9. Enter an amount
10. Tap next and note contact options

## Expected Result:
In split bill, workspace is not shown as option to create IOU. Similarly, in request money also, workspaces must not be shown as options to create IOU.
User must not be shown options to request money to Workspace

## Actual Result:
In split bill, workspace is not shown as option to create IOU. But, in request money, workspaces are displayed as options to create IOU.
User is shown options to request money to Workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/288bcb51-31fd-4662-937e-ee9423a1c90b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
Yes, this is intended behavior.
