### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] HIGH: Add ability to `request money` from within `IOU` and `expense reports

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27075]
At the moment we allow the ability to request money via the big green plus button, aka "Global Create". We also allow you to create requests via a `policyExpenseChat` and even `DM`. Curiously, we don't allow you to request money via either an `IOU` or `expense` report, and we should, especially given that you can create a `task` in any report. Here's an example of the issue at hand. Notice there is no `request money` option. 

<img width="831" alt="Screenshot 2023-09-04 at 11 22 09" src="https://github.com/Expensify/App/assets/1127863/e21c8eba-f8b6-4b5c-8a8b-9b7dcad39e29">

Accordingly, let's add `request money` to `IOU` and `expense` reports as well, just like the `policyExpenseChat`. 

Note: One special consideration is that we shouldn't show the `Request money` button when a report reaches the `approved` or `reimbursed` state, as at that point reports become "locked" and no new requests can be added to them. 

cc @mountiny You might decide to take this one, so I'm keeping it internal until you decide one way or another. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166385e94742cacb0</li>
        <li>Upwork Job ID: 1700387490099986432</li>
        <li>Last Price Increase: 2023-09-09</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Looking for detailed proposals

There is a chance we need to update the request money actions too to ensure the correct binding to the DM or workspace chats are made.

**Comment by JmillsExpensify** [comment]
All issues require proposals, yes.

**Comment by JmillsExpensify** [comment]
All issues require proposals, yes.

**Comment by narefyev91** [comment]
I think @dukenv0307 add a good proposal and steps what should be implemented. Any additional code changes can be discussed during PR review
🎀 👀 🎀 C+ reviewed

**Comment by mountiny** [comment]
> the request will be added to the report preview of the chat report or it will be a new request?

There will be a new request/ transaction on the IOU/expense report and then we need to update the report preview (which at this point should always exist). This will be the number of the requests also meaking sure the correct number of receipts/ images shows there

**Comment by mountiny** [comment]
> Will expense report and iou report be displayed as an option when we choose participants in participant page?

Haha, great thinking! cc @JmillsExpensify 

No not in this PR, its out of scope, we will handle it elsewhere

**Comment by mountiny** [comment]
`MoneyRequestParticipantsPage ` if you are requesting from IOU or expense report, then there are no participants to choose, they are the same as in the existing report

**Comment by JmillsExpensify** [comment]
Agreed, though we'd still show the workspace on the confirmation screen, I think. Maybe eventually that confirmation screen clarifies the report name but even that's TBD

**Comment by mountiny** [comment]
Creating two new PRs to cover couple other cases for this flow:
- Auth to always return both participants of IOU report https://github.com/Expensify/Auth/pull/8827 - this fixes an odd inconsitency we had in this design for a long time where the IOU report owner is omitted from the participants array
- Cleaning up the App logic and adding more unit tests https://github.com/Expensify/App/pull/28542

**Comment by mountiny** [comment]
@dukenv0307 I believe the payment automation failed here, you should get paid $500 for this, right?

**Comment by mountiny** [comment]
@dukenv0307 I am not sure if we havent missed the case of the payer though which would be a regression. With your PR, I dont think the payer would be able to request money at the IOU report. I did not see it tested in the PR.

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @dukenv0307 for PR. 

@narefyev91 @mountiny Have we added regression test yet? If not, @narefyev91 can you suggest the right ones we should add?

**Comment by narefyev91** [comment]
Regression test:
1. Navigate to a DM with an existing User B
2. Click the composer + button
3. Verify you can see the Request Money option and no split
4.Request money from User B
5. Navigate to the IOU report which got created
6. Click the composer + button in the IOU report
7. Verify you can see the Request money option
8. Request more money from User B
9. Log in as User B in incognito window
10. Go to the DM with User A
11. Verify you can see the request money option in the composer + actions menu
12. Navigate to the IOU report where User A requested money from the User B
13. Verify you can request money from User A in the IOU report composer + actions menu too
14. As User B, in the IOU report, request more money from the User A than you owe at the moment
15. Verify the request was successful and the User A now owes money to User B
16. Verify you can still see the Request Money option as User B
17. Go back to the User A window and verify you can also still see an option to request money from User B
18. As User A, pay the money report elsewhere to settle the report
19. Verify that as User A, you cannot request money in the paid IOU report
20. Similarly, verify that as User B, you cannot request money in the paid IOU report

**Comment by mountiny** [comment]
Something tells me i have added one but happy to pass this to QA to double check too

**Comment by JmillsExpensify** [comment]
Contributor paid out. Closing.
