### ISSUE TITLE
[$500]  [Scan Receipt] - When editing merchant, the text should be auto-selected.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on + icon > Request Money >choose Scan, file and user > Click on Request btn
3. Open “Receipt scan in progress” chat
4. Click on the request
5. Click on merchant

## Expected Result:
Default message should be autoselected

## Actual Result:
Default message is not autoselected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-08 at 5 01 24 PM (1)](https://github.com/Expensify/App/assets/93399543/61594aa4-75eb-40c6-8372-6c07b0f22be3)

https://github.com/Expensify/App/assets/93399543/59232c51-000f-4d60-b96e-e4da188fadf3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694217723591499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d7645cfb13ae72d</li>
        <li>Upwork Job ID: 1700467745094049792</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 26982032</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue. 
When editing merchant that shows (none) as default, the text should be auto-selected.

### What is the root cause of that problem?
There is no prop selectTextOnFocus in TextInput for editmoney request input form page


 <TextInput
                        inputID="merchant"
                        name="merchant"
                        defaultValue={defaultMerchant}
                        label={translate('common.merchant')}
                        accessibilityLabel={translate('common.merchant')}
                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
                        ref={(e) => (merchantInputRef.current = e)}
                    />=


What changes do you think we should make in order to solve the problem?
Add prop selectTextOnFocus in members page TextInput [here]

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Default message is not autoselected

### What is the root cause of that problem?
EditRequestMerchantPage is only focusing the text input on `onEntryTransitionEnd` event: 
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/pages/EditRequestMerchantPage.js#L38-L42

### What changes do you think we should make in order to solve the problem?
Add `select()` method to the input, e.g.:
```
    const onEntryTransitionEnd = useCallback(() => {
        if (merchantInputRef.current) {
            merchantInputRef.current.focus()
            merchantInputRef.current.select()
        }
    }, [merchantInputRef.current])

    return (
        <ScreenWrapper
            includeSafeAreaPaddingBottom={false}
            shouldEnableMaxHeight
            onEntryTransitionEnd={() => onEntryTransitionEnd()}
        >
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by dylanexpensify** [comment]
in progress - @sobitneupane mind updating?

**Comment by sobitneupane** [comment]
I will review the proposal tomorrow.

**Comment by sobitneupane** [comment]
@dylanexpensify Just to confirm, we want it to be auto selected only for following default messages, right?

- DEFAULT_MERCHANT: 'Request',
- UNKNOWN_MERCHANT: 'Unknown Merchant',
- PARTIAL_TRANSACTION_MERCHANT: '(none)',

**Comment by sobitneupane** [comment]
Waiting response from @dylanexpensify on https://github.com/Expensify/App/issues/27082#issuecomment-1719101709

**Comment by dylanexpensify** [comment]
@sobitneupane sorry for delay, was OOO! So I'd think we'd want it to autoselect only when defaulting to (none), though I could see a case for having it always autoselect all. @mountiny @sobitneupane any thoughts on this?

**Comment by mountiny** [comment]
@dylanexpensify I think we should autoselect everytime

**Comment by sobitneupane** [comment]
As suggested by @mountiny, if we want to autoselect everytime, adding `selectTextOnFocus`  in the TextInput should be enough as proposed [here](https://github.com/Expensify/App/issues/27082#issuecomment-1712490365) by @ishpaul777.

@ishpaul777 Can you please confirm the solution works well in android as well? 

cc: @dylanexpensify

**Comment by ishpaul777** [comment]
@sobitneupane  yes, it works on android and IOS too.

> @sobitneupane This proposal doesn't update with the new expected.

The expected behavior remains largely unchanged; we simply no longer require passing any conditions to the selectTextOnFocus function.

**Comment by ishpaul777** [comment]
### Proposal 
[Updated](https://github.com/Expensify/App/issues/27082#issuecomment-1712490365)

**Comment by dylanexpensify** [comment]
@sobitneupane let's review @ishpaul777's updated proposal!

**Comment by sobitneupane** [comment]
@ishpaul777 You have updated your proposal to include `InteractionManager.runAfterInteractions(() => {`. What was the issue with the previous solution?

**Comment by ishpaul777** [comment]
> prevent IOS weird positioning of selection carets

I have added the videos for before and after. explained why i suggested using the `InteractionManager.runAfterInteractions(() => {` in the proposal.

| Before | after |
|--------|--------|
| <img width="815" alt="Screenshot 2023-09-26 at 3 58 15 PM" src="https://github.com/Expensify/App/assets/104348397/fa8ecf66-5a28-4757-82c3-f148d6afdbe3"> | <img width="831" alt="Screenshot 2023-09-26 at 3 58 48 PM" src="https://github.com/Expensify/App/assets/104348397/fe055fa5-f6c7-4768-baab-d14a6992aaa2"> |

**Comment by dylanexpensify** [comment]
@sobitneupane mind reviewing response please?

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/27082#issuecomment-1712490365) from @ishpaul777 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by tgolen** [comment]
Please be sure to update the issue description and title if the desired behavior changes.

**Comment by sobitneupane** [comment]
> Everytime for the merchat or comment in the edit money request flow

@mountiny Just to confirm we want both Merchant and Description to be auto-selected, right?

**Comment by mountiny** [comment]
cc @Expensify/design can you please help here.

I think that whenever we Push to page to new Form field in RHP and there is only one text input, we should autoselect it as from UX perspective it is nothing else they can do in that page.

**Comment by shawnborton** [comment]
Why should the entire thing be auto selected though? I agree that we want to auto focus that input, but I'm not sure if we should auto select the whole strong.

**Comment by dylanexpensify** [comment]
Ah interesting, @shawnborton so only autofocus/select when it is `none` and not anything else? Or am I misunderstanding?

**Comment by shawnborton** [comment]
I would think we should just focus into the input but not auto select the entire string. I am curious if others agree though!

**Comment by dannymcclain** [comment]
@shawnborton yeah I agree with that behavior. I think that's what I would expect.

**Comment by dylanexpensify** [comment]
> I would think we should just focus into the input but not auto select the entire string. I am curious if others agree though!

Ahh so our thinking here is that it'd auto select the entire string since a user will always edit it (only for the first time when it just says "merchant"

**Comment by shawnborton** [comment]
Ah, I'm saying that I actually don't know if this is a bug. I can see why we might select the entire string here, but I think this is recipe for some inconsistent behavior. Like in many cases you want to just edit the string and you don't need the whole thing selected, you just want your cursor in the text input.

**Comment by dylanexpensify** [comment]
goooot it. So basically, let's not create a rule for string selection on this one scenario, but just leave it as is. I can get behind that
