### ISSUE TITLE
[$500] Android - Cursor Appears before the text in edit box 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to any chat report
2. Type some text
3. Long press and choose edit option.
4. Notice that the cursor appears before the editable text in edit-box.

## Expected Result:
n other platforms - web, mweb, desktop, the cursor appears beside the text in edit box. However in android it appears before.

## Actual Result:
Cursor Appears before the text in edit box 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5ed49e4d-b265-48cb-9873-a091ad24844b

https://github.com/Expensify/App/assets/93399543/1d4ed62f-4c87-4ac4-a209-3b9f25251f43

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693847352660869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d231624524297556</li>
        <li>Upwork Job ID: 1700473292647878656</li>
        <li>Last Price Increase: 2023-09-09</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/24157 has contributors assigned, so closing this one
