### ISSUE TITLE
[$1000] IPAD - LHN is missing in IPAD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in to new expensify app on an iPad

## Expected Result:
Able to use NewDot in IPAD

## Actual Result:
LHN is missing in IPAD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop
- [ ] IOS / IPAD

**Version Number:** 1.3.66-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/45c984c1-0f91-4f0a-9154-b87592b66e5c

https://github.com/Expensify/App/assets/93399543/e1ee6e0d-36ab-4d21-bbd2-fb0af1e56e63

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693878764944479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f2b5dc76517b53d</li>
        <li>Upwork Job ID: 1701289201178431488</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
QA team is able to reproduce it on modal: iPad Pro11 2nd gen/iPadOS 15.7

**Comment by zanyrenney** [comment]
Thanks! I don't have an iPad nor can I test this on Browserstack, so going to add the external label to move this forward.

**Comment by zanyrenney** [comment]
@aimane-chnaif what's the latest here? have you been able to test this on iPad?

**Comment by zanyrenney** [comment]
bump @aimane-chnaif ?

**Comment by zanyrenney** [comment]
@aimane-chnaif what do we need to do to get some more propsals?

**Comment by zanyrenney** [comment]
@aimane-chnaif should we adjust the bounty here do you think?

**Comment by zanyrenney** [comment]
added additional context and details for this one - https://expensify.slack.com/archives/C049HHMV9SM/p1695610964837529?thread_ts=1695610733.526209&cid=C049HHMV9SM

**Comment by shubham1206agra** [comment]
This should be already fixed as we have disabled landscape configuration here
https://github.com/Expensify/App/pull/27016

**Comment by zanyrenney** [comment]
Thanks. @aimane-chnaif what do we need to do to move ahead here?

**Comment by zanyrenney** [comment]
bumped the slack thread - https://expensify.slack.com/archives/C049HHMV9SM/p1696236374230869?thread_ts=1695610733.526209&cid=C049HHMV9SM

**Comment by zanyrenney** [comment]
CLosing - as not supporting IPAD bugs - https://github.com/Expensify/App/issues/26421#issuecomment-1702965441

**Comment by Julesssss** [comment]
I fully support dropping iPad support, but we should officially drop iPad support in the AppStore in that case to prevent downloads, as the app looks horrendous and is totally unusable.

**Comment by Julesssss** [comment]
WOW. Apple [won't let us ](https://stackoverflow.com/a/35747810/4160784) drop iPad support. This is going to cause us problems in the future, as they have already held releases due to broken iPad functionality...

**Comment by Julesssss** [comment]
Started a Slack discussion [here](https://expensify.slack.com/archives/C03U7DCU4/p1696241167386389), as I don't think we can simply drop iPad support.
