### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Assign Task - Workspace avatar shows 'U'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on Workspace chat in LHN
3. Tap plus icon
4. Tap assign task
5. Enter title
6. Tap next
7. Select assignee and assign to myself
8. Tap confirm task
9. Note header "U" Icon and tap on it to note the details

## Expected Result:
Workspace is available, so it must not show unavailable icon and it must show workspace profile icon after assigning a task

## Actual Result:
Workspace is available, but it shows unavailable icon instead of workspace profile icon in header after assigning a task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6d5b2378-9d32-4d69-90e2-b9d45e2d749a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3f658f7ff3bedd3</li>
        <li>Upwork Job ID: 1701125975388905472</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26727093</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
reproduced

**Comment by adelekennedy** [comment]
@sobitneupane thoughts on the proposal above?

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/27092#issuecomment-1713164052) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment]
I agree that @dukenv0307's proposal is better and more detailed.

**Comment by luacmartins** [comment]
Just waiting on payment

**Comment by adelekennedy** [comment]
### Payouts due:

Contributor: $500 @dukenv0307 (Upwork)
Contributor+: $500 @sobitneupane (NewDot)

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/ab/applicants/1701125975388905472/hired).

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/17992
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/17992#issuecomment-1752468125
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a case missed while adding a new feature.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Login with any account
2. Create a workspace
3. Go to the workspace chat
4. Create a task in this chat report
5. Verify the header of the task report displays the correct workspace instead of the unavailable workspace

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/27092#issuecomment-1746809730

> Eligible for 50% #urgency bonus? Y


Since it is eligible for urgency bonus. Requested $750 for payment in newDot.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @sobitneupane based on BZ summary.

**Comment by JmillsExpensify** [comment]
Also re-opening this one for the regression test.

**Comment by adelekennedy** [comment]
pending regression test feedback

**Comment by luacmartins** [comment]
I don't think we need a specific regression test for this since it's an UI issue that's easily noticeable. I think we're good to close.
