### ISSUE TITLE
[$500] [HOLD for payment 2023-10-02] No way to create new room even from policyRoom beta enabled account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB menu while you have the beta active
2. Click on 'Send Message'
3. Notice that you don't see the option to create room

## Expected Result:
You can select Create Room

## Actual Result:
The Create Room button does not show up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0 PR:25564

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/299e5318-0ec0-4013-8474-8d1ccc18010c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2bbc554a9b89f77</li>
        <li>Upwork Job ID: 1709985526319775744</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Linked PR https://github.com/Expensify/App/pull/25564

**Comment by thienlnam** [comment]
This is just pending payment - I realize we have no BZ member on this issue though

**Comment by thienlnam** [comment]
Hey @CortneyOfstad 👋 this issue is ready for payment, just a contributor payment to @aimane-chnaif for fixing the bug. I handled the review myself and applause reported the bug

**Comment by CortneyOfstad** [comment]
No worries! Just a heads up @thienlnam, we have to add the External label in order to have the "job" created in Upwork for me to pay 👍

**Comment by CortneyOfstad** [comment]
@aimane-chnaif proposal has been sent in Upwork — please let me know as soon as you accept, as we can get that paid. Thanks!

**Comment by CortneyOfstad** [comment]
Paid $750 total ($500 + 50% bonus) — closing!
