### ISSUE TITLE
[$500] [Dstance] - distance request money allows to request 0 amount after it show route exceeds maximum limitation error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click '+' FAB
2, Click on request money and go to distance tab
3. Give start and finish that are far away and click next
4. Choose workspace and request the money
5:. You can see it has requested 0 amount

## Expected Result:
The next button won't allow user to proceed

## Actual Result:
The next button allows user to proceed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1,3,66,3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2bd12e27-9300-4898-830e-7e94d40d4562

https://github.com/Expensify/App/assets/93399543/e2558fcc-dba0-43ff-9f3f-b4572ecfa6d4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693900129869839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d2c09a29868a725</li>
        <li>Upwork Job ID: 1700775335250837504</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
It looks like Melvin assigned @sophiepintoraetz first, so I'm removing my assignment to avoid doubling up work.

**Comment by paultsimura** [comment]
Should have been fixed in the current `main` branch by this PR: https://github.com/Expensify/App/pull/26705.

**Comment by sophiepintoraetz** [comment]
Okay but I still need to pay @lidiyakelay the $50 reporting bonus. @lidiyakelay - please can you apply for the job [here](https://www.upwork.com/jobs/~019d2c09a29868a725) and let me know here once you have done so?

**Comment by lidiyakelay** [comment]
@sophiepintoraetz  I have applied  for the job
