### ISSUE TITLE
[$500] Web - Task - Can't find user email results when assigning tasks in group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27109]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group chat with several participants (new users)
2. Click "+" button and choose Assign task
3. Input title -> click "Next" -> Click "Assignee"
4. Enter the email of the member in the group

## Expected Result:
User email search results can be found

## Actual Result:
No results found

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-05T045157.755.webm](https://github.com/Expensify/App/assets/93399543/18c354e3-d105-45ae-a901-91729122abd6)

https://github.com/Expensify/App/assets/93399543/38a2e9f3-5c07-4d65-971e-404150de4abf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693917317156359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Could be a duplicate https://github.com/Expensify/App/issues/26072, please check and confirm. Thank you

**Comment by bfitzexpensify** [comment]
Checking in with the engineers working on https://github.com/Expensify/App/issues/26072 to check if the proposal there will also solve for this

**Comment by bfitzexpensify** [comment]
Suggestion in https://github.com/Expensify/App/issues/26072#issuecomment-1713797230 is that this won't be solved by that issue. Sending this external

**Comment by Christinadobrzyn** [comment]
Thanks for the input @namhihi237 - it looks like https://github.com/Expensify/App/pull/25806 issue involves not being able to assign a [task to a new user](https://github.com/Expensify/App/issues/25688). Can you tell me why you think that's the same as this issue, I might be missing something
