### ISSUE TITLE
[WAITING ON SLACK THREAD] [$500] mWeb - Holding down on the "No thanks" or "Download" buttons on the banner selects previous words

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in for the first time on a new account on mWeb
2. When a banner shows up press and hold down on either "No thanks" or "Download" buttons

## Expected Result:
 No words should be selected

## Actual Result:
The "." gets selected on the paragraph

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c8e5c55c-165b-4ff1-8815-a07996a4bac1

https://github.com/Expensify/App/assets/93399543/9c3560e3-cac4-48e2-a26e-54de98320e99

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693906785297509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013927694479c35846</li>
        <li>Upwork Job ID: 1700787122331496448</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by ishpaul777** [comment]
## Proposal 
### Problem
 Holding down on the "No thanks" or "Download" buttons on the banner selects previous words
 
### Root cause
We are not using css style `user-select: none` for disabling the selection on buttion

### Solution
User  `user-select: none` for disabling the selection on buttion

**Comment by jliexpensify** [comment]
Unassigning Kev, I'm Bug Zero. Not sure why 2 of us are assigned.

**Comment by jliexpensify** [comment]
@kbecciv were you told to add the `External` label, or is this a new process? Please note that this assigns the bug to Upworks - this is something that the Bug Zero team (i.e. me) would typically do. Some of my colleagues have also noticed you adding this label on other GH's.

**Comment by jliexpensify** [comment]
[Left my thoughts here](https://expensify.slack.com/archives/C049HHMV9SM/p1694348434042239?thread_ts=1693906785.297509&cid=C049HHMV9SM), but I'm not convinced this is a bug we'd fix - the reasoning behind this is that when faced with 2 buttons, users wouldn't be long-pressing. So while this is an inconvenience if the buttons were long-pressed, I don't think it will affect users due to the fact they wouldn't be doing this action.

**Comment by kbecciv** [comment]
Hey @jliexpensify QA team have new instructions for the Contributor's bug. Here is the link in qa channel https://expensify.slack.com/archives/C9YU7BX5M/p1694149069725469

**Comment by jliexpensify** [comment]
Thanks @kbecciv - we weren't told of this update until yesterday, and there were other Applause GH's without the label applied, so some confusion there from our side!
