### ISSUE TITLE
PR:25564 New Room - No possibility to create New Room, New Room option is upset in FAB menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27110]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://25564.pr-testing.expensify.com/
2. Login with any Expensifail account
3. Make sure that you have an existing workspace or create a new one
4. Click on FAB button

## Expected Result:
There is a possibility to create new room in the App in FAB menu or in any other way

## Actual Result:
There is no new room option and there is NO other way to create a new room in the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0 PR:25564

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2d25cab5-c4a3-478d-8566-e0d5ee1c0efc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Link PR https://github.com/Expensify/App/pull/25564
