### ISSUE TITLE
[$500] Waypoints values aren't retained while switching to manual /scan tabs.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to fab -> request money -> distance
2. put start and end waypoints.
3. now switch to manual or scan tabs. And comeback to the distance tab.
4. Notice that the values are emptied.
However, if we enter the manual amount and then switch to other tabs , amount entered in manual section is shown again or say retained.

## Expected Result: 
it would be better if the waypoint values are hold on form field, even after switching to other tabs.
## Actual Result: 
Waypoints values aren't retained while switching to manual /scan tabs.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/24e8d731-bc7f-4b98-bd2d-fd18fbd05233

https://github.com/Expensify/App/assets/43996225/6197f3e2-2795-4e98-9dad-d122a7ae032a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693973067079569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ac176c190096b15</li>
        <li>Upwork Job ID: 1701006445932236800</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by muratkorkmazz** [comment]
Hello , I can fix your issues. The solution depends on form of your current code for instance which Html tags either radio input or plain div have been used ?  What I would do is basically that I put single form and add some onchange events for inputs. Solution of this issue doesen't take more than 2 hours for me.

**Comment by muratkorkmazz** [comment]
Contributor details
Your Expensify account email: ymert8954@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01136f0eaa330ccb69

**Comment by hayata-suenaga** [comment]
Closing this

As @allroundexperts pointed out, this is expected behavior 🙇
