### ISSUE TITLE
[$500] Android - Line height is increased after pasting code block in composer.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Copy a code block
3. Paste in the composer
4. Observe the text

## Expected Result:
The line height should not change.

## Actual Result:
The line height is changed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4384b6f0-ca9e-4b7a-a5da-97a5d8059494

https://github.com/Expensify/App/assets/93399543/2d6403fe-fc91-415b-a038-c3fa7688102a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693935913441749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127b1c2305c88d4bf</li>
        <li>Upwork Job ID: 1700965156599029760</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by Sarmadkhalid1** [comment]
This issue is basically in the porps of RNTextInput. The prop textAlightVertical should contain some other value than "center:

**Comment by Sarmadkhalid1** [comment]
Contributor details
Your Expensify account email: Sarmadkhalid36@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012eb74f01f4de7f7f

**Comment by canh-ta** [comment]
Contributor details
Your Expensify account email: canh.tc98@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01bd42ba50c9112a7e

**Comment by joekaufmanexpensify** [comment]
I don't see any bug here. The text adjusts ever so slightly when you paste it in, but to me it just looks like it is loading/rendering, and it's barely perceptible. Closing as this isn't a bug.

**Comment by not-soo-cool** [comment]
Contributor details
Your Expensify account email: yashvendrasengar1111@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c9910144b0a19a02
