### ISSUE TITLE
[$500] Android - Payment input is not focused when tab changes from distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Request money
3. Click on distance button in the header
4. Get back to manual tab
5. Observe amount input is not focused

## Expected Result:
The amount input should be focused

## Actual Result:
The amount input is not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fee24dcd-b7c2-4cfe-a691-e71978fd629a

https://github.com/Expensify/App/assets/93399543/36788e7c-f3be-4d09-8dcb-6ad028530382

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693937933243989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a3b18dcf1980e91</li>
        <li>Upwork Job ID: 1700984379527847936</li>
        <li>Last Price Increase: 2023-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 26690007</li>
<li>Krishna2323 | Reporter | 26690010</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment]
@narefyev91 will the recent proposal work to resolve this issue? Thanks!

**Comment by narefyev91** [comment]
@alexpensify Yes this will work - but should we really force it for all platforms? The issue happened only for Android - also as i see there are some open issues in react-navigation which currently exists for a long time (seems no one plan to fix them - lol)
https://github.com/react-navigation/react-navigation/issues/10397
https://github.com/react-navigation/react-navigation/issues/11128
https://github.com/satya164/react-native-tab-view/issues/1181
Based on the suggestion to make it working - either remove animation or force keyboard to stay with keyboardDismissMode
In case this is the first tab navigator in app - we can resolve that issue with keyboardDismissMode as @Krishna2323 suggested
🎀 👀 🎀 C+ reviewed

**Comment by Gonals** [comment]
Closing this, then!
