### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Chat - Inconsistent "(edited)" text on styled RTL text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and type a text in a right-to-left character set, (for example مثال).
2. Edit the text to another right-to-left text, (for example مال). Examine the "(edited)" text position
3. Edit the text so it become styled (for example, *مال*). Examine the "(edited)" text position

## Expected Result:
The "(edited)" text is supposed to stay the same for right-to-left characters, regardless being edited or not

## Actual Result:
In the normal edited text, the "(edited)" text is positioned in the right of the edited message. However in the styled edited text, the "(edited)" text is positioned on the left of the edited message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ccccb6c1-8213-44dd-8cbc-ad3695ae0d7a

https://github.com/Expensify/App/assets/115492554/cf15d9cc-68c3-4790-be6d-0f11856171c7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693864715884909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01466b9797b975245b</li>
        <li>Upwork Job ID: 1701135260498452480</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26611890</li>
<li>kerupuksambel | Reporter | 26611895</li>
</ul></li>
    </ul>
</details>

**Comment by rajsixthblock** [comment]
Contributor details
Your Expensify account email: raj@sixthblock.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0104b18b5cf10d77e5

**Comment by mountiny** [comment]
is this something we actually support now @rushatgabhane this is a first time I am seeing something like that and I am not sure if this is worth spending our time on, right now. What do you think?

**Comment by mountiny** [comment]
yeah I am also in Bali 😂

**Comment by mountiny** [comment]
$50 to @kerupuksambel
$500 to @bernhardoj 
$500 to @rushatgabhane already requested in NewDot

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on summary above.

**Comment by JmillsExpensify** [comment]
All other contributors have been paid out!

**Comment by JmillsExpensify** [comment]
Regression test has also been created. Closing.
