### ISSUE TITLE
Race condition can cause big checklists

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#27123]
### Problem

Sometimes we get big checklists like [this one](https://github.com/Expensify/App/issues/26359) that include [all the PRs from the previous checklist](https://github.com/Expensify/App/issues/26359#issuecomment-1700391331).

The root cause is a race condition between:

- [createNewStagingDeployCash](https://github.com/Expensify/App/blob/d2f02a3258c1110a4f5d09fdbe2e59b53ef09fc9/.github/workflows/finishReleaseCycle.yml#L124)
- [deployStaging](https://github.com/Expensify/App/blob/d2f02a3258c1110a4f5d09fdbe2e59b53ef09fc9/.github/workflows/deploy.yml#L8-L26)

Both are triggered at the same time after [updateStaging](https://github.com/Expensify/App/blob/d2f02a3258c1110a4f5d09fdbe2e59b53ef09fc9/.github/workflows/finishReleaseCycle.yml#L97) finishes. If deployStaging finishes (i.e: the tag for the new staging version is pushed to the remote) before the checklist is created, then it works. If not, then we get a huge checklist like this will all the PRs that were deployed in the previous version.

### Solution
TBD – probably change the deploy system a bit such that staging deploys are triggered by the creation of a prerelease and production deploys by the creation of a "full" release.

That way we can push the tag as soon as it's created without triggering a deploy

**Comment by roryabraham** [comment]
No update right now

**Comment by roryabraham** [comment]
No update

**Comment by mountiny** [comment]
Looking into this one now

Noting that the createNewDeployChecklist was moved to the [platformDeploy.yml](https://github.com/Expensify/App/blob/be0d06161a3e76cb2c7bfc10fbadecad235cf82e/.github/workflows/platformDeploy.yml#L31-L52), which feels like the race condition is not happening anymore and the bug might be somewhere else. 

When the `updateStaging` finished, it [force pushes](https://github.com/Expensify/App/blob/be0d06161a3e76cb2c7bfc10fbadecad235cf82e/.github/workflows/finishReleaseCycle.yml#L116-L122) to staging branch and then the [deploy.yml](https://github.com/Expensify/App/blob/be0d06161a3e76cb2c7bfc10fbadecad235cf82e/.github/workflows/deploy.yml#L23-L27)  runs which pushes the tags and finally we trigger the [platformDeploy.yml](https://github.com/Expensify/App/blob/be0d06161a3e76cb2c7bfc10fbadecad235cf82e/.github/workflows/platformDeploy.yml#L1-L10) which would create the checklist but the correct tags should be available

Looking more into why this is failing

**Comment by mountiny** [comment]
Created a PR which should hopefully help with this

**Comment by roryabraham** [comment]
Ok, it seems like there's some way the git history can change in production that's different from what we have represented in the `CIGitLogicTest.sh`, just judging by running this command on staging w/ full git history:

<img width="604" alt="image" src="https://github.com/Expensify/App/assets/47436092/c5150a66-b699-4979-8b46-89edf174ca96">

Neither is correct, because the only version-bump that we expect to be included between `1.3.76-6` and `1.3.77-0` is `Update version to 1.3.77-0`

**Comment by roryabraham** [comment]
It looks like the last checklist that was created without being affected by this error is [this one](https://github.com/Expensify/App/issues/28412), so we should try to figure out what was different between `1.3.74-3` and `1.3.75-0` vs `1.3.76-6` and `1.3.77-0`

**Comment by Beamanator** [comment]
FYI I wrote a handy little JS script to mark off items in the new checklist that were on the old one: https://github.com/Expensify/App/issues/30560#issuecomment-1784674079

**Comment by roryabraham** [comment]
Moving this back to weekly since it's a PITA

**Comment by roryabraham** [comment]
Planning to investigate this further this week

**Comment by roryabraham** [comment]
I have a hunch that this has something to do with force-pushes.

**Comment by roryabraham** [comment]
Spent several hours trying to dig into this, but so far no success in finding a minimal reproduction. I tried something like this:

1. Create a PR A
1. Create a PR B that conflicts with A
1. Merge PR B
1. Release app
1. Merge main into pr-A branch and resolve conflicts
1. Merge PR A

That worked as expected, so I think the next variation should be something like this:

1. Create PR A
1. Create PR B that conflicts with A
1. Merge PR B
1. Release app
1. _Rebase_ pr-A branch and resolve conflicts. Force-push to PR A
1. Merge PR A

My thinking is that by rebasing onto a commit from the previous release then force-pushing we'll somehow include the commits from PR B in the new checklist

**Comment by roryabraham** [comment]
The other thing maybe worth looking into is that our tests [always checkout 1 commit on main](https://github.com/Expensify/App/blob/86b8231fb24819ed813d6eb8f7d2bf7d429d37b1/tests/unit/CIGitLogicTest.sh#L70-L71) before fetching the other tags used in the `git log` command.

Not sure if that matters, but it's a difference between our local testing setup and the production environment (this may change if/when I create a new callable workflow to create `createOrUpdateStagingDeploy`)

**Comment by roryabraham** [comment]
This should be fixed by https://github.com/Expensify/App/pull/31458

**Comment by roryabraham** [comment]
That didn't work perfectly: https://github.com/Expensify/App/actions/runs/6910552568/job/18803863115. Going to retry

**Comment by roryabraham** [comment]
Nice, that worked as expected (well, maybe not the upwork bit, that's weird).

Anyways, for context I'm marking this as a deploy blocker not because we actually need to block deploy on it, but because I think we should merge https://github.com/Expensify/App/pull/31458 before the next deploy, because it should fix this big checklist issue
