### ISSUE TITLE
[$500] Web -  Any change in description/title/assignee URL opens task report in place of 'Hmm its not here' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report with open task in it
3. Open title/description/assignee and make small modification to the URL
4. Observe that it displays task report with that URL

## Expected Result:
App should either redirect us back to task report URL or display Hmm its not here page to ensure that user understands their mistake in URL

## Actual Result:
App displays task report with same URL in browser when there is slight modification to description/title/assignee page URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9f759c55-ff32-44c0-89db-f7ac3d36c979

https://github.com/Expensify/App/assets/93399543/44999b00-fd8c-4a40-93d0-4bf2eb53b162

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693488506863869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aab6a37e55af6c15</li>
        <li>Upwork Job ID: 1701219809901121536</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by EliteDevSolution** [comment]
Hello Expensify Team
I think that it will be solve  such as bottom code.
```
import React, { Component } from 'react';

class TaskReportScreen extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isValidURL: true
    };
  }

  componentDidMount() {
    this.validateURL(this.props.route.params.taskID);
  }

  validateURL(taskID) {
    // Add your validation logic here (e.g., check if taskID exists in the database)
    // Set isValidURL to true if valid, false if not
    const isValid = this.props.validateURL(taskID); // Assuming validateURL is a prop function
    this.setState({ isValidURL: isValid });
  }

  handleGoBack = () => {
    this.props.navigation.goBack();
  };

  render() {
    const { isValidURL } = this.state;

    return (
      <div>
        {isValidURL ? (
          <div>
            {/* Render task report details */}
            <div>Task Report Details</div>
            <button onClick={this.handleModifyTask}>Modify Task</button>
          </div>
        ) : (
          <div>
            <div>Hmm, it's not here</div>
            <button onClick={this.handleGoBack}>Go Back</button>
          </div>
        )}
      </div>
    );
  }
}

export default TaskReportScreen;
```

Sure, I can help you convert the provided functional component into a class component. Here's the equivalent class component:

jsx
Copy code
import React, { Component } from 'react';

class TaskReportScreen extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isValidURL: true
    };
  }

  componentDidMount() {
    this.validateURL(this.props.route.params.taskID);
  }

  validateURL(taskID) {
    // Add your validation logic here (e.g., check if taskID exists in the database)
    // Set isValidURL to true if valid, false if not
    const isValid = this.props.validateURL(taskID); // Assuming validateURL is a prop function
    this.setState({ isValidURL: isValid });
  }

  handleGoBack = () => {
    this.props.navigation.goBack();
  };

  render() {
    const { isValidURL } = this.state;

    return (
      <div>
        {isValidURL ? (
          <div>
            {/* Render task report details */}
            <div>Task Report Details</div>
            <button onClick={this.handleModifyTask}>Modify Task</button>
          </div>
        ) : (
          <div>
            <div>Hmm, it's not here</div>
            <button onClick={this.handleGoBack}>Go Back</button>
          </div>
        )}
      </div>
    );
  }
}

export default TaskReportScreen;

The constructor is used to initialize the component's state, where isValidURL is set to true initially.
I use componentDidMount to trigger the URL validation when the component mounts.
validateURL is a method that you should define, similar to the one in the functional component. It checks if the taskID is valid and updates isValidURL accordingly.
The handleGoBack method is an arrow function to ensure that this refers to the class instance when it's called.
In the render method, we use this.state.isValidURL to conditionally render the task report details or the error message.

**Comment by Tyrese-FullStackGenius** [comment]
Contributor details
Your Expensify account email: wizardlydeveloper@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019904ef989290e55b

When redirecting to another page, save the path to the previous page and if the page does not exist, it redirects to the previous page.

**Comment by b4s36t4** [comment]
But shouldn't we show NotFoundPage if they're navigating to invalid route?

**Comment by greg-schroeder** [comment]
@JmillsExpensify looks like we were double assigned (reason [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)) - I was assigned first though so I'll take this

**Comment by b4s36t4** [comment]
Well, in my view atleast we should update the URL. It's not an ideal behaviour a user can do.. but atleast we should update the URL making sure he is in the correct page. If we don't do anything that means the action user did is correct which is not good.

**Comment by greg-schroeder** [comment]
what do you think about that comment @rushatgabhane ☝️ ?

**Comment by greg-schroeder** [comment]
Bump @rushatgabhane

**Comment by b4s36t4** [comment]
Can we get some opinions from slack, let's take other's view as well.

**Comment by greg-schroeder** [comment]
Hmm. I think I trust @rushatgabhane's judgment.
