### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Chat - Status emoji is not fully visible in conversation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27149]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: Set a status emoji and message
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Note status emoji in any sent message or send a message and note

## Expected Result:
The status emoji must be displayed fully in the conversation page

## Actual Result:
The status emoji is only half visible in conversation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/adfc0246-202d-4249-8738-f66bdf23e1b8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2a729000f5e1f1f</li>
        <li>Upwork Job ID: 1702434843606450176</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26921541</li>
</ul></li>
    </ul>
</details>

**Comment by jscardona12** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Status emoji is not fully visible in conversation page
### What is the root cause of that problem?
The root cause is because the emoji status lacks of a min height so when the page get smaller, the meesage date gets relevance and "overlaps" the emoji
### What changes do you think we should make in order to solve the problem?
In **https://github.com/Expensify/App/blob/1ae51cc025881f517451acf70d7ea383a0ed395f/src/styles/styles.js#L3918-L3922** we should add the style `minHeight: variables.fontSizeNormal`to match the default size of the emoji in case of this value changes.
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment]
I'm not able to reproduce this any longer on 1.368-15, can anyone confirm if they can still repro?

**Comment by jscardona12** [comment]
Hi @strepanier03, still reproducible on latest main.
<img width="385" alt="Screenshot 2023-09-12 at 5 02 28 PM" src="https://github.com/Expensify/App/assets/16781411/ac23f28c-4971-40b7-929e-75f0d32a05e5">

**Comment by strepanier03** [comment]
All right, I'll move it forward, thank you @jscardona12 for testing again

**Comment by strepanier03** [comment]
@parasharrajat - Friendly bump on the proposals, thank you!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment]
Thank you @mvtglobally.

**Comment by strepanier03** [comment]
Great clarification @tienifr. I'll do another round of testing and update shortly.

**Comment by stitesExpensify** [comment]
@parasharrajat can you review @tienifr proposal please?

**Comment by strepanier03** [comment]
We're all on the beta for this now as well so testing should be easy to accomplish. 

@stitesExpensify - With @parasharrajat review are we good to hire @tienifr then?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by strepanier03** [comment]
Sorry for the hold-up here everyone, I've been pretty slammed but I'm working on this now. Thanks for your patience 🙌

**Comment by strepanier03** [comment]
@tienifr - I've finished paying via UPwork and closed the contract. Thank you again!

----

@parasharrajat - Feel free to update me with the checklist stuff when you can and then submit a manual request for payment. I updated this payment [comment](https://github.com/Expensify/App/issues/27149#issuecomment-1745229430) with the amount. Thank you as well!

**Comment by strepanier03** [comment]
QA is done and checklist updated. We're all set here. 

----

@parasharrajat - I'm assigning Jason to this, if you haven't already please submit for manual payment based on [this](https://github.com/Expensify/App/issues/27149#issuecomment-1745229430) payment summary.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/27149#issuecomment-1745229430).
