### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Bank account - Bank account message redirects to an invalid page on browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26699
## Action Performed:
1. Launch New Expensify app
2. Go to Settings > Workspace > any workspace > Bank account
3. Click on the sentence 'Note: To connect with Chase, Wells Fargo, Capital One or Bank of America, please click here to complete this process in a browser'

## Expected Result:
User is redirected to bank account page

## Actual Result:
User is redirected to an invalid page - https://staging.new.expensify.com/bank-account/new?policyID=

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/66e9b316-d799-4098-94ec-33f89e3383a5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bb82aa82cce4919</li>
        <li>Upwork Job ID: 1701314698827501568</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>abdel-h66 | Contributor | 26664619</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
@abdel-h66's [proposal](https://github.com/Expensify/App/issues/27148#issuecomment-1713995113) here is good.

🎀 👀 🎀 C+ reviewed.

**Comment by pecanoro** [comment]
Sounds good! Assigning the proposal!

**Comment by abdel-h66** [comment]
It's ready for review :)

**Comment by mananjadhav** [comment]
PR review done.

**Comment by abdel-h66** [comment]
I am blocked if somoeone could help me with the a recording from iOS and Android would be much appreciates, I'm having trouble setting those up on my machine. 

The PR doesn't really affect both of these devices but just in case.

**Comment by NicMendonca** [comment]
@mananjadhav bump on BZ checklist ^^

**Comment by NicMendonca** [comment]
- reporter: n/a
- contributor: @abdel-h66: $500
- c+: @mananjadhav: $500


@abdel-h66 you've been paid via Upwork 🎉 
@mananjadhav don't forget to request payment via Expensify 🙇‍♀️

**Comment by mananjadhav** [comment]
Thanks for the bump @NicMendonca. I don't think we have an offending PR for this one. We didn't originally intend for the feature to work that way (you can correct me if I am wrong).

Neither we need a regression test here, this only applies to the desktop app.

**Comment by NicMendonca** [comment]
ok! then we're all set here - @mananjadhav don't forget tor request payment via Expensify

Payment summary: 

> reporter: n/a
> contributor: @abdel-h66: $500
> c+: @mananjadhav: $500

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on BZ summary.
