### ISSUE TITLE
[$500] Web - Opening keyboard shortcut popup when year search is open closes the year search page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open date of birth
6. Click on year to open year search
7. Use CTRL+J/CMD+J to open keyboard shortcut popup and observe that it closes year search page in background

## Expected Result:
Opening keyboard shortcut popup by CTRL+J/CMD+J should not close any page in background

## Actual Result:
Opening keyboard shortcut popup by CTRL+J/CMD+J should closes year search page in background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99e35710-5d78-4887-a470-7829b615d4f7

https://github.com/Expensify/App/assets/93399543/340098d1-dc2c-4185-835d-6c15493deaa3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691856719118529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f04df3cac9324841</li>
        <li>Upwork Job ID: 1701218301180612608</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by Lucas-Argerich** [comment]
Allow me to introduce myself - I am Lucas Argerich, a dedicated frontend developer with a strong commitment to crafting exceptional web experiences.

**Issue Description:**
The problem we've encountered is that when users open the keyboard shortcut popup using CTRL+J/CMD+J, it unintentionally closes the year search page in the background. This behavior is not expected and needs to be fixed.

**Proposal for Fix:**

- Identify Trigger: We need to start by examining the code responsible for handling the keyboard shortcut (CTRL+J/CMD+J) to understand how it triggers the closure of the year search page.

- Check Event Handling: Review the event handlers related to the keyboard shortcut popup. It's likely that there's a piece of code that handles this event.

**Comment by Lucas-Argerich** [comment]
Contributor details
Your Expensify account email: lucasargerichcoder@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/lucasargerich

**Comment by b4s36t4** [comment]
Not able to reproduce the issue on latest main local.

**Comment by puneetlath** [comment]
We're going to be moving the keyboard shortcuts to the RHP, so I don't think anything needs to be done here. 

@stephanieelliott did we open an issue for that?
