### ISSUE TITLE
[HOLD for payment 2023-09-20] Android - The updated Expensify logo has no background on Android notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27145]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue foung when executing PR** https://github.com/Expensify/App/pull/26381
## Action Performed:
1. Log in to New Expensify app as User A
2. Background the app
3. As User B from another device, send a message to User A

## Expected Result:
The updated logo has green as background color and the icon can be dark/white

## Actual Result:
The updated logo has no background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6196094_Screenshot_20230911_195513](https://github.com/Expensify/App/assets/78819774/8cdade97-b40f-4e84-9625-63d319e15842)

https://github.com/Expensify/App/assets/78819774/25447eb0-192c-41ef-bb07-4bb9999e9c57

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
I think C+ review is the only payment due here, correct @AndrewGable? Should we apply `Bug` label to have someone pay?

**Comment by AndrewGable** [comment]
@miljakljajic - @aimane-chnaif needs to get paid 🤑 - Thanks!

**Comment by miljakljajic** [comment]
Contract sent @aimane-chnaif !

**Comment by cristipaval** [comment]
Is this one paid? Could we close this issue? 👀

**Comment by miljakljajic** [comment]
I sent a contract to @aimane-chnaif in Upwork but I realise now that some of our C+ are being paid through newDot (I took a hiatus from this team). I'll get this resolved today!

**Comment by miljakljajic** [comment]
Paid and contract ended.
