### ISSUE TITLE
Chat- New message not appears on top when a new message is posted and marked as unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Send a message
4. Long press the message
5. Select " Mark as unread"
6. Scroll up to the top

## Expected Result:
New message must appears on top when a new message is posted and marked as unread

## Actual Result:
New message does not appears on top when a new message is posted and marked as unread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d431e0ba-be79-4991-8a9a-5e789c1a6354

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@lanitochka17 can you confirm , for the expected behaviour , that 'new message' means 'the green new message button'?
![IMG_0074](https://github.com/Expensify/App/assets/22508304/510d2ca8-76cb-4411-83a9-7e03ed49580f)

It's what shows on iOS native and Desktop for me when I test.  I only see a screenvid from mobile, yet I see all platform boxes checked, are you experiencing on all platforms?

**Comment by mallenexpensify** [comment]
Thanks @lanitochka17 , going to close since it's not reproducible.
