### ISSUE TITLE
Dev: Web - Closing the manual request currency selector opens the distance request tab.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the FAB button
2. Click either Request money or Split bill
3. Open the currency selector page by clicking on the currently selected currency
4. Select any currency

## Expected Result:
 You should be sent back to the manual request money tab

## Actual Result:
The distance request tab is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  Dev 1.3.67.2
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/429574ef-3184-4e0d-b6d8-52902b3482ff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @joh42
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694442122791199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joh42** [comment]
After clearing cookies it's the scan receipts tab that is opened:

https://github.com/Expensify/App/assets/138504087/b8918156-d87d-4984-8edc-7040a6ec7986

**Comment by joh42** [comment]
Okay sorry about this, I think you can disregard this issue. It seems like I had some problems with react-navigation/native. Removing the node_modules folder and reinstalling from scratch fixed it
