### ISSUE TITLE
[WAITING ON AIMANE TO COMPLETE CHECKLIST] [HOLD for payment 2023-10-02] [$500] Request money - Unread indicator doesn't appear when marking as unread in offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + -> Request money -> Scan -> Choose file -> Continue
2. Reach "Receipt scan in progress…" page
3. Go offline
4. Chang date time
5. Mark the message as unread

## Expected Result:
Unread indicator should appear

## Actual Result:
Unread indicator doesn't appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dde64c32-d46e-4a23-8e13-70fcb6d78521

https://github.com/Expensify/App/assets/115492554/8b38834d-d14e-4880-8287-59783ef2814f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dukenv0307

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693928604694079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01065ccca935909edf</li>
        <li>Upwork Job ID: 1701251311952404480</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26746297</li>
<li>dukenv0307 | Contributor | 26746298</li>
<li>dukenv0307 | Reporter | 26746300</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Not overdue

**Comment by dangrous** [comment]
Yep, looks good! Assigning.

**Comment by jliexpensify** [comment]
Payment summary:

- Bug Reporter / Contributor: @dukenv0307 $50 + $500 + $250 = $800
- C+: @aimane-chnaif $500 + $250 = $750

[Upwork job](https://www.upwork.com/jobs/~01065ccca935909edf)

@aimane-chnaif please complete the checklist!

**Comment by jliexpensify** [comment]
Bump @aimane-chnaif to complete the checklist please

**Comment by jliexpensify** [comment]
Everyone's paid and job removed, cheers!
