### ISSUE TITLE
Community Migration to HelpDot - C+ Assistance 

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#27150]
# Part of the Community Migration to HelpDot project
Main issue: https://github.com/Expensify/Expensify/issues/274365
Doc section: https://docs.google.com/document/d/1MjTYzA-uo7ShLjo8x3XLA7EkSAhx0Yc9W43PPnKV3co/edit#bookmark=id.g4dt3vbhlcro

### [Tracking Issue](https://github.com/Expensify/Expensify/issues/274365)
**Tl;dr:** There's a 9/30 deadline for this migration to be completed (more details [here](https://expensify.slack.com/archives/C05NM77EUTS/p1693099613383999)). For that to happen, I need some engineering assistance. 

To make this as easy as possible for our engineering team, I will parse out exactly what I need/what I have questions about so that those tasks can be completed whenever anyone has a spare moment! 

## Request 1 - Questions on publishing content
1. When publishing a brand new article (not editing an existing article), is it possible for a non-engineer to preview an article before publishing it? 
2. Are C+s currently reviewing these PRs? 
3. Do we always need engineering to merge these PRs? Can we lower the threshold so that Ring5 is able to merge HelpDot PRs? Or, is that too risky? 
4. Is **[this](https://stackoverflowteams.com/c/expensify/questions/15135)** the most up-to-date process for non-engineers publishing new content to the site or could this be simplified in any way? 
5. We will be publishing 100+ articles - Is there a certain cadence we should follow when publishing new articles? Can we publish everything at once? Should we go hub-by-hub? 

## Request 2 - Questions on publishing images
1. What is the best way for non-engineers to include images when publishing new content? 
2. Should we request images from Design? 
3. Is there a specific way those images should be formatted when submitting the PR? 

## Request 3 - Confirming Category/Subcategory redesign structure is feasible
**The current redesign entails:**
- Deleting the current homepage Category Hubs 
- Adding 12 new homepage Category Hubs
- Adding several Subcategory Hubs
- Moving the existing resources to the newly created Subcategory Hubs
- Publishing ~100 new resources under a corresponding Subcategory Hub

### Homepage Category Hubs:
<img width="779" alt="image" src="https://github.com/Expensify/Expensify/assets/38016013/8245538c-34ae-46c5-b71a-082cb67aca34">

### Subcategory Hubs:
<img width="1193" alt="image" src="https://github.com/Expensify/Expensify/assets/38016013/6e0a5d88-ed62-442b-9217-4c45067d6526">

#### Publishing the Content to HelpDot - Technical Details: 
- [ ] Code (or w/e is necessary) for deleting the existing four Category Hubs
- [ ] Code (or w/e is necessary) for add 12 new Category Hubs
- [ ] Code for updating Category Hub icons
- [ ] Code for adding 12 Category Hub descriptions
- [ ] Code for adding add Subcategory "Level 1" Hubs (nested within Category Hubs)
- [ ] Code for adding Subcategory "Level 2" Hubs (nested within some Subcategory Hubs)
- [ ] Manual tests
- [ ] Automated tests
- [ ] System requirements

**Comment by maddylewis** [comment]
@rushatgabhane - sent you an invite to Figma 👍

**Comment by maddylewis** [comment]
### Associated GHs / to-do items (ongoing list)
- [ ] Update the instructions for publishing content to HelpDot - https://stackoverflowteams.com/c/expensify/questions/15135
- [ ] Expensify Classic Category Hub blurbs - https://github.com/Expensify/Expensify/issues/314805
- [ ] https://github.com/Expensify/Expensify/issues/316462
- [ ] https://github.com/Expensify/Expensify/issues/316542
- [ ] https://github.com/Expensify/Expensify/issues/316544
- [ ] https://github.com/Expensify/Expensify/issues/316545
- [ ] https://github.com/Expensify/Expensify/issues/316460

**Comment by maddylewis** [comment]
@rushatgabhane yes!

**Comment by maddylewis** [comment]
## Payment due
- [ ] @rushatgabhane ($4k flat rate + $1k bonus for urgency / being so great to work with!) Pay via NewDot

**Comment by maddylewis** [comment]
i don't think there's any action for chirag on this one

**Comment by maddylewis** [comment]
updated bonus amount!

**Comment by JmillsExpensify** [comment]
@maddylewis Mind updating that summary? I think you have a typo with $5k

**Comment by maddylewis** [comment]
@JmillsExpensify - correct! updated (total = $6k -- $4k + $2k urgency bonus).

**Comment by JmillsExpensify** [comment]
$6,000 payment approved for @rushatgabhane based on BZ summary.
