### ISSUE TITLE
Chat - Suggestion list is not shown for new email and new chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on Fab
3. Tap new chat
4. Enter a new email id, a new user for a new chat
and select it
5. Enter @ in compose and enter new email of new chat just created

## Expected Result:
When user enters @ in compose and enter new email of new chat just created, the suggestion list must display the new email with avatar

## Actual Result:
When user enters @ in compose and enter new email of new chat just created, the suggestion list does not display the new email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentatio

https://github.com/Expensify/App/assets/78819774/5f4d39bd-f5b8-49cf-8a23-26e13bfa5c75

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
Checking with the team https://expensify.slack.com/archives/C049HHMV9SM/p1695028446884819

**Comment by sonialiap** [comment]
No response, I need to bump this tomorrow morning

**Comment by sonialiap** [comment]
bumped

**Comment by sonialiap** [comment]
Chatted with Kevin in person and the decision is that this is a feature, not a bug. The new email is not yet validated so they can't be tagged.
