### ISSUE TITLE
[$500]  [Distance] Web – The downward arrow of the scroll bar does not change to white as expected.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27161]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB (Plus sign).
2. Select the "Request Money" option from the menu.
3. Select the "Distance" option.
4. Repeatedly clicked the "Add stop" button until the scroll bar appeared on the right side of the section.
5. Scrolled the stop section downwards and observed that the upward arrow turned white, but when scrolled upwards, the downward arrow did not change to white.
6. Notably, the scroll bar arrows in the "Request Money" section functioned correctly when scrolling both up and down.

## Expected Result:
The downward arrow in the "Adding Stop" section should turn white when scrolling upwards.

## Actual Result:
The downward arrow does not change to white when scrolling upwards in the "Adding Stop" section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1650a8a8-5bd0-4953-864e-c9067aae5ba3

https://github.com/Expensify/App/assets/93399543/0da978bb-4a91-4fa1-a51c-511b17c78e27

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694077100312639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01812de08a76b8bf4b</li>
        <li>Upwork Job ID: 1701257550541799424</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by Tyrese-FullStackGenius** [comment]
Contributor details
Your Expensify account email: wizardlydeveloper@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019904ef989290e55b

I should check the code for the color change functionality of the downward arrow in the "Adding Stop" scroll function.
Fix the codes where the downward arrow is not correctly changing its color into white in the 'Adding Stops' section while scrolling upwards.
Test the bug fix by repeatedly adding stops until the scroll bar appears and checking whether the downward arrow changes to white when scrolled upwards.
In the end, ensuring the color contrast of the arrows in the scrollbar provides a visual cue for users, increases usability, and maintains consistency in the site interface.

**Comment by puneetlath** [comment]
I agree with closing given this only seems to happen on windows. Feel free to comment if you disagree!
