### ISSUE TITLE
[HOLD for payment 2023-09-27] Unable to send attachment and new message is not shown in LHN after sending attachment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to an existing conversation
2. Click the plus icon -> Add attachment -> Choose from gallery
3. Select any photo -> Send
4. Then send a message to this chat
## Expected Result: 
The selected photo will be sent within seconds. The message sent should show in the LHN
## Actual Result: 
The selected photo is not sent. The message sent after not showing in the LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari (@tgolen able to reproduce)
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-1
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e989f83b-a93d-40e4-a53d-c618082fd9e6

https://github.com/Expensify/App/assets/43996225/3fd780fd-a514-4d0a-abc0-b60f977a0f65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694407887187689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment]
this is fixed here https://github.com/Expensify/App/issues/24246 PR in review

**Comment by tgolen** [comment]
Yes, It needs to be a blocker. I do not think it is a duplicate and that sounds like a different issue. I am going to revert the ordered-updates PR which should solve this.

**Comment by tgolen** [comment]
We discussed in Slack and since this is related to a beta, and there is a workaround (logoff/logon), we are not going to revert, and we are just going to close this issue as `won't fix`.

**Comment by tgolen** [comment]
Daniel has a fix for this, so we are going to implement it and reopen this.

**Comment by thuyle04** [comment]
@danieldoglas Do you have any payment for bug reporter, please?

**Comment by danieldoglas** [comment]
@garrettmknight

**Comment by garrettmknight** [comment]
@thuyle04 offer sent, please accept.

**Comment by thuyle04** [comment]
@garrettmknight Hi, I can't access this url with my appropriate account. 
![Screenshot from 2023-10-09 10-13-26](https://github.com/Expensify/App/assets/63705956/ff37e40b-2df9-4e6a-b817-25bb5e6cb099)

**Comment by garrettmknight** [comment]
@thuyle04 sorry, the URL was for me!

**Summary of payments:**
- Reporter: @thuyle04 paid $50 via upwork
