### ISSUE TITLE
[$500] Chat - Can't select blockquote between text if text is greater in length.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a block quote between text with line breaks
3. Try to select block quote and text by double clicking on the empty space beside texts & block quote
4. If text is greater in length the block quote is not selectable
5. If block quote is greater in length the text is not selectable

## Expected Result:
The text/block quote should be selectable by double/triple-click.

## Actual Result:
The text/block quote is not selectable by double/triple-click.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/348f3cea-44b9-4500-8838-55ce5e8709d7

https://github.com/Expensify/App/assets/115492554/27dfcd58-8d5e-4009-a680-37562901b6d5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693936701583489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01345dccdcf5dee0ea</li>
        <li>Upwork Job ID: 1701259912023347200</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by Tyrese-FullStackGenius** [comment]
Contributor details
Your Expensify account email: wizardlydeveloper@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019904ef989290e55b

Check the CSS style of the quote message and update it.

**Comment by lschurr** [comment]
@aimane-chnaif could you review the proposal here?

**Comment by lschurr** [comment]
Bump on this @aimane-chnaif

**Comment by lschurr** [comment]
@aimane-chnaif what do you think of this last comment?

**Comment by lschurr** [comment]
Bump @aimane-chnaif

**Comment by lschurr** [comment]
Still waiting on proposals.

**Comment by lschurr** [comment]
@aimane-chnaif - could you please create a Slack thread for what we should do with this one?

**Comment by lschurr** [comment]
Bump @aimane-chnaif - what do you think we should do with this one?

**Comment by lschurr** [comment]
Closing!
