### ISSUE TITLE
Assign task - Task description disappears when changing assignee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: as admin create a workspace and invite 2 users (user A and B)
1. Open the app and log in as user A
2. Create a task in the announce room
3. Assign it to yourself
4. Log out
5. Log in as the workspace admin
6. Navigate to the room and open the task
7. Edit the description
8. Change the assignee

## Expected Result:
The description is shown every time an assignee is changed

## Actual Result:
The description disappears after the assignee is changed. The description is shown if user goes back to the chat report and opens the task again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6f3620b8-b437-416b-9753-c0a9bac98d13

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012582c5fbc0db343d</li>
        <li>Upwork Job ID: 1703711159160877056</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by ShogunFire** [comment]
This is backend I think the EditTaskAssignee returns an empty field description 

![image](https://github.com/Expensify/App/assets/19537677/bc464386-7dda-4648-ac74-15ffef70e7df)

**Comment by sakluger** [comment]
@aldo-expensify - @ShogunFire says this is backend. Could you please confirm whether this should be internal or external? Thanks!

**Comment by sakluger** [comment]
@aldo-expensify friendly bump.

**Comment by aldo-expensify** [comment]
I think @ShogunFire is correct, I see the same

**Comment by aldo-expensify** [comment]
PR up

**Comment by aldo-expensify** [comment]
The fix has been deployed.
