### ISSUE TITLE
[$500] Desktop - Login with Google leads to error page when browser is logged in with different account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
- Web is signed in with Expensifail account
- Desktop is not signed in
1. On desktop login page, click Log in with Google
2. On web browser, click Try again
3. Click Allow on open in app prompt

## Expected Result:
User is redirected to any chat report without error

## Actual Result:
User is redirected to 'Hmm... it's not here' page and the back button on the top left does not work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8403aac2-760a-46d1-a87c-d597eeb99dab

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694013501345009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d59734fb81b38852</li>
        <li>Upwork Job ID: 1701544616163762176</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Waiting for proposals

**Comment by laurenreidexpensify** [comment]
@hoangzinh are you still able to repro?

**Comment by laurenreidexpensify** [comment]
Let's close thanks everyone
