### ISSUE TITLE
[$500] Inconsistency - There is no green line at the edges of add stop button in distance tab unlike show more button in manual tab

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27191]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with any account.
2. Click FAB icon> request money> distance tab.
3. Observe that no green line at the edges of add stop button.
4. switch to manual tab, enter the amount and select a user, observe that there is green line at the edges of show more button.

## Expected Result:
Green line should be present at the edges of add stop button to maintain consistency.

## Actual Result:
There is no green line at the edges of add stop button unlike show more button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/36eac326-7934-4210-8878-04fed6298eae

https://github.com/Expensify/App/assets/115492554/3a3fa796-3aeb-49df-986e-e8f171fd2f08

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ahmedGaber93

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693936756706359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df5462c85f9df58d</li>
        <li>Upwork Job ID: 1701322811181232128</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Correct, this is not a bug. Going to close.
