### ISSUE TITLE
[$500] Request money - Distance - Keyboard is showing for brief moment of time while coming from delete waypoint

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Click on FAB icon
2. Then select request money
3. Click on distance TAB
4. Click on add stop button
5. Click on stop which is added
6. Then select three dots (top most right)
7. And delete this waypoint

## Expected Result:
Keyboard should not be show

## Actual Result:
Keyboard is showing for brief moment of time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.66-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ae9dac71-d047-417f-95b4-7970e65caad7

https://github.com/Expensify/App/assets/115492554/e37667df-bea6-491a-970a-62ac05fdd188

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693941099472519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ef807527bb44c5b</li>
        <li>Upwork Job ID: 1701342038677569536</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26874632</li>
<li>niravkakadiya25 | Reporter | 26874633</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We have the `textInput` element focus set on the load here:

https://github.com/Expensify/App/blob/89598d8793b5db05488a1358c1fd13d6da73fe1f/src/pages/iou/WaypointEditor.js#L163

### What changes do you think we should make in order to solve the problem?
Call the `textInput.current.blur()` when we open the "Delete Stop" modal (setting `isDeleteStopModalOpen`) as well as when deleting the stop – at `deleteStopAndHideModal`.



### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment]
@sobitneupane what do you think of the current proposals?

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

@hungvu193 I don't think your proposal will do the job as we see keyboard between two modals in the delete process (i.e modal with Delete waypoint menuitem and Delete waypoint modal.

**Comment by sobitneupane** [comment]
> According to https://github.com/Expensify/App/issues/20608#issuecomment-1616813839, only iOS refocuses after closing the modal, so we don't have to reopen the keyboard after the modal is dismissed, to be consistent with other platforms.

Oh yes. I think it makes sense to dismiss keyboard when we press threedotsmenu to open the first modal as it is the case in other platforms as well.

[Proposal](https://github.com/Expensify/App/issues/27201#issuecomment-1714885620) from @tienifr looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sonialiap** [comment]
@sobitneupane @hayata-suenaga looks like we have a proposal we like, what's the next step?

**Comment by sonialiap** [comment]
@sobitneupane @hayata-suenaga bumping :)

**Comment by sobitneupane** [comment]
We are waiting for response from @hayata-suenaga on https://github.com/Expensify/App/issues/27201#issuecomment-1722927165

**Comment by sobitneupane** [comment]
Yup @tienifr Let's hold this issue for now.

cc: @sonialiap

**Comment by sonialiap** [comment]
On hold for https://github.com/Expensify/App/issues/27182

might get incorporated into https://github.com/Expensify/App/issues/24452

**Comment by sonialiap** [comment]
Still on hold

**Comment by hayata-suenaga** [comment]
@tienifr can you check the issue against which we're holding this issue and check what they have decided on?

**Comment by sonialiap** [comment]
On hold for https://github.com/Expensify/App/issues/24452

FYI, I'm OOO until Oct 22

**Comment by hayata-suenaga** [comment]
changing the priority until the hold is lifted

**Comment by sonialiap** [comment]
On hold for https://github.com/Expensify/App/issues/24452

**Comment by hayata-suenaga** [comment]
on HOLD for https://github.com/Expensify/App/issues/24452

**Comment by sonialiap** [comment]
On hold for https://github.com/Expensify/App/issues/24452

**Comment by hayata-suenaga** [comment]
[Here](https://github.com/Expensify/App/issues/24452#issuecomment-1821291635) is the latest update for https://github.com/Expensify/App/issues/24452

**Comment by sonialiap** [comment]
On hold for https://github.com/Expensify/App/issues/24452, the PR for that issue is still in review

**Comment by hayata-suenaga** [comment]
on hold for #24452

**Comment by sonialiap** [comment]
on hold for https://github.com/Expensify/App/issues/24452

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/24452. Looks like the PR for that issue is still in Draft

**Comment by hayata-suenaga** [comment]
A new contributor [was assigned](https://github.com/Expensify/App/issues/24452#issuecomment-1907309947) to https://github.com/Expensify/App/issues/24452 to review the PR.

We're still on hold for that PR.

**Comment by hayata-suenaga** [comment]
The PR related to this issue was divided into segments, but progress is continuously being made.

**Comment by sonialiap** [comment]
Still on hold for the PR

**Comment by hayata-suenaga** [comment]
PR is still being reviewed

**Comment by hayata-suenaga** [comment]
[the latest comment](https://github.com/Expensify/App/issues/24452#issuecomment-1990963598)

**Comment by sonialiap** [comment]
Still on hold https://github.com/Expensify/App/issues/24452

**Comment by hayata-suenaga** [comment]
[latest update here](https://github.com/Expensify/App/issues/24452#issuecomment-2009226025)

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/24452

**Comment by hayata-suenaga** [comment]
https://github.com/Expensify/App/issues/24452 is still being worked on

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/24452

**Comment by sobitneupane** [comment]
Still on hold

**Comment by sobitneupane** [comment]
Still on hold

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/24452 but looks like we're getting closer!

**Comment by sonialiap** [comment]
PR for https://github.com/Expensify/App/issues/24452 was deployed on June 12 https://github.com/Expensify/App/pull/43041#issuecomment-2161775499. I'm asking QA to retest this to see if it's still an issue - [slack](https://expensify.slack.com/archives/C9YU7BX5M/p1718715910320699)

**Comment by kbecciv** [comment]
@sonialiap The steps are outdated; the "add stop" button is no longer present.

https://github.com/Expensify/App/assets/93399543/d8f3b04f-cd11-46e6-8865-86788494695c

**Comment by sonialiap** [comment]
Looking at this today! (completing another task and then this one's next on my list)

**Comment by sonialiap** [comment]
@tienifr chatted with the team, does 50% sound reasonable to you?

**Comment by sonialiap** [comment]
@tienifr I've adjusted the contract in upwork and issued payment ✔️ 

Payment summary:
- @tienifr $250 via upwork

**Comment by niravkakadiya25** [comment]
HI
@sonialiap can you laso adjus amount in my upwork as well.
