### ISSUE TITLE
[HOLD for payment 2023-09-29] Disable hover effect while scrolling in Report Screen on Web

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27214]
Part of https://github.com/Expensify/App/issues/26087

### Problem

As a user, scrolling the Report screen on web appears to be janky due to hover effect as components keep changing the background and Reaction bar keeps toggling based on the successive hover effect due to the scrolling and cursor stays in one place. This might not be janky in actual but as a user, we perceive it as the scroll is janky.

### Solution

We can take example of Slack and how it disables the hover effect and hides the reaction bar, when the user is scrolling through the messages. Once the user stops scrolling, the hover effect is applied to that message and reaction bar is shown. ( You can quickly give it a try in any slack channel ). So we can move forward with fixing the perceived performance here.

To implement something similar, I tried the following steps:
- Have a isScrolling state in BaseInvertedFlatList  and toggle that state in onScrollBegin  and  onScrollEnd .
    - Issue is that FlatList on Web doesn’t support these methods ( https://github.com/necolas/react-native-web/pull/1305 and https://necolas.github.io/react-native-web/docs/scroll-view/ )
- To have something similar to  onScrollEnd , I added this piece of code ( https://github.com/necolas/react-native-web/issues/1021#issuecomment-984151185 ) in BaseInvertedFlatList
    - Though this works well but we will need to test this thoroughly ( If we want to go down this path )
    - IMPORTANT: We can remove this custom onScrollEnd  once Margelo is finished developing Wishlist
- Then I added the isScrolling parameter to the renderItem call [here](https://github.com/Expensify/App/blob/db1a306659648704baf834f65cdb804f26e13aa5/src/components/InvertedFlatList/BaseInvertedFlatList.js#L123) and passed the isScrolling  as a prop to ReportActionItem .
    - In ReportActionItem , I combined isScrolling with hovered and we have something similar to Slack :tada:

The issue with this solution was that the scroll would delay for a while due to the extra re-render which happens due to isScrolling state being set in BaseInvertedFlatList . As a result, we see the re-renders of all the renderItem too. It happens when we start to scroll and once, when we stop the scroll.

To fix this, I re-structured my approach towards event driven data passing. Below are the steps:

- From BaseInvertedFlatList , I removed the isScrolling state and also removed passing this state to renderItem .
- I added the event emitter in BaseInvertedFlatList  which would fire once the scroll is started and once the scroll is ended.
- Then in Hoverable , I added the event listener and also added two refs, one to hold the event value for scrolling and second to hold the mouse hovered value, to avoid re-rendering all the items and re-render only what’s the last hovered item.
- To prevent Hoverable from misbehaving in different parts of the app, where we don’t need this behaviour, I passed in a prop handleScroll (Boolean) , if it’s true we will execute the scroll logic and add event listeners.
- With this, the scroll doesn’t delay and we have much better user experience :tada:.

Before:
See the attached video with title: recording-before

https://github.com/Expensify/App/assets/36083550/89c09686-c336-4de9-ae9f-c538ae4bd814

After:
See the attached video with title: recording-after

https://github.com/Expensify/App/assets/36083550/5fcb5bd4-0326-42e6-baad-91723a95e2b2

Testing Environment:
Macbook M1 Pro, 16GB Ram, Ventura 13.4.1

**Comment by hurali97** [comment]
Hey @mountiny !

You can assign this to me, Hur from callstack !

**Comment by mountiny** [comment]
Lies

**Comment by MitchExpensify** [comment]
**Payment Summary:**

No payment due here

**Comment by mountiny** [comment]
@MitchExpensify sorry, there should be $500 to @abdulrahuman5196 for internal review and testing

**Comment by MitchExpensify** [comment]
Ok great, thanks for confirming @mountiny 

I'll create a payment issue in Upwork here https://www.upwork.com/jobs/~018fc17964696bfa2d

Offer sent to you @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to any Report which contains some messages.
2) Start scrolling and notice that the hover and reaction bar doesn't display while you're scrolling.
3) Once you stop the scroll, the hover and reaction bar will display.

**Comment by MitchExpensify** [comment]
Paid and test request added
