### ISSUE TITLE
Implement new wallet page layout

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#27211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open `Settings` -> `Wallet`

## Expected Result:
When you don't have an Expensify Wallet configured, it should look like this:

<img width="385" alt="image" src="https://github.com/Expensify/App/assets/47436092/5e2782de-a5ce-43fb-9247-1386b1119e2d">

When you _do_ have an Expensify Wallet configured, it should look like this:

<img width="390" alt="image" src="https://github.com/Expensify/App/assets/47436092/4afe30ad-565f-4696-926d-6b53ab363c29">

## Actual Result:
It doesn't look like that

## Workaround:
n/a
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
@shawnborton I'm having difficulty finding the running money asset in DropBox. Can you help gather the assets we need here then we can make this external? Also lmk if you need help adjusting the aspect ratio on the lottie animation. Would be good to verify that before we make it external as well

**Comment by roryabraham** [comment]
I think @dukenv0307's proposal provides enough detail and LGTM, but I'm not going to make this external until we get the assets together

**Comment by shawnborton** [comment]
I think this is the correct animation: https://www.dropbox.com/scl/fi/a6l4rf8qzj29kimy3va8o/Expensify-Fast-Money-2-121322-kjs-1.json?rlkey=yi2d3pun1syf3dzaqy6j3w10x&dl=0

**Comment by shawnborton** [comment]
Also just wanted to double check with @grgia so we aren't doubling up on work here, as I think maybe this one might be being worked on as part of the Expensify Card project?

**Comment by grgia** [comment]
Yeah @roryabraham this is being done by Callstack as part of the card settings project https://github.com/Expensify/App/issues/22871. Closing this as a duplicate

**Comment by grgia** [comment]
(PR in progress here - https://github.com/Expensify/App/pull/26406/files)
