### ISSUE TITLE
[HOLD for payment 2023-09-20] Web - Bank account - App crashes when checking ToS checkbox and Continue CTA is not working

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > any workspace > Bank account.
3. Click Add manually.
4. Enter routing number and account number.
5. Check the terms of service checkbox.
6. Refresh the page.
7. Return to the page in Step 5.
8. Click Continue

## Expected Result:
In Step 5, app does not crash.
In Step 8, user is brought to the next step.

## Actual Result:
In Step 5, app crashes.
In Step 8, Continue button is not responsive.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6cb5f888-6c6d-4d20-a353-249e23f8d168

[utest-dl.s3.amazonaws.com_12102_26469_428866_6197284_bugAttachment_Bug6197284_staging.new.expensify.com-1694507081970.log_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230912T111516Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Am.txt](https://github.com/Expensify/App/files/12585730/utest-dl.s3.amazonaws.com_12102_26469_428866_6197284_bugAttachment_Bug6197284_staging.new.expensify.com-1694507081970.log_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20230912T111516Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Am.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @tewodrosGirmaA 

**Slack conversation:** (https://expensify.slack.com/archives/C049HHMV9SM/p1694492106740469)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
This was reported by @hungvu193 here https://github.com/Expensify/App/pull/26140#discussion_r1322344633

**Comment by techievivek** [comment]
@hungvu193 Did you make a bug proposal on Slack so we can issue the reporting bounty?

**Comment by trjExpensify** [comment]
Okay, so order of priority.. we have a PR up to fix this regression, yeah? @techievivek shall I switch you out for @madmax330?

**Comment by tewodrosGirmaA** [comment]
@trjExpensify , I reported first here https://expensify.slack.com/archives/C049HHMV9SM/p1694492106740469?thread_ts=1694492106.740469&cid=C049HHMV9SM, could you change the reporter name

**Comment by sourcecodedeveloper** [comment]
@robertKozik @techievivek the issue has already been resolved after merging [PR](https://github.com/Expensify/App/pull/27217)
and can be closed.

**Comment by tewodrosGirmaA** [comment]
> > @hungvu193 Did you make a bug proposal on Slack so we can issue the reporting bounty?
> 
> just checked, I think @tewodrosGirmaA reported it first.

Thank you @hungvu193 , I think  Katerina updated

**Comment by trjExpensify** [comment]
This has been fixed, once it hits prod, I'll pay out the bug report of $50 to @tewodrosGirmaA.

**Comment by trjExpensify** [comment]
This is on prod now. @tewodrosGirmaA I've sent you an offer for the bug report. 👍

**Comment by trjExpensify** [comment]
Settled up!
