### ISSUE TITLE
[$500] Android - Strong delay in getting back to chat/LHN after checking avatar full screen mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot app
2. Open any direct chat with user that has non-default avatar
3. Tap to see fullscreen avatar
4. Try to get back to chat or LHN

## Expected Result:
Chat or LHN is displayed without delays

## Actual Result:
Chat and/or LHN appear with delay. At first it appears that back arrow is not responding

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dbc24e31-d9f7-4638-8845-341e61bd603d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01338a15521c809331</li>
        <li>Upwork Job ID: 1701979352464699392</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Waiting for proposals.

**Comment by lschurr** [comment]
Still waiting on proposals

**Comment by lschurr** [comment]
@thesahindia are you still able to reproduce this one?

**Comment by lschurr** [comment]
Ok, great! Let's close.
