### ISSUE TITLE
[$1000] MEDIUM: Requestee name changes to undefined when visting requestee chat again after visiting the scan report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27251]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with someone, make sure that the person has no pending money-request/owns report with you.
2. Click on the + icon in composer > Request Money > Manual Request > and request some amount (important)
3. Click on the + icon in composer again > Request Money > Scan Request > and request some amount
4. Quickly as the scan is in progress, click on the IOUPreview message to open money request report (this will show all money requests i.e manual, scan)
5. Click on scan report that is being scanned to open the specific scan report.
6. Go back to main chat with user (make sure that the scan report is still in scanning phase)
7. Notice the last IOU message header name, it has undefined & User B in message header.
## Expected Result:
User A's name should not change to undefined
## Actual Result:
 User A's name changes to undefined
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/433ffec7-f17b-4ac4-99c2-0c8af2fdbc9a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693311668970309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a76ce0a217d8cad7</li>
        <li>Upwork Job ID: 1701948550196547584</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
Needs reproduction

**Comment by dylanexpensify** [comment]
@isabelastisser taking on as part of wave4!

**Comment by mananjadhav** [comment]
Still waiting for proposals.

**Comment by dylanexpensify** [comment]
Doubling, if no one takes it in the next week, we'll have internal

**Comment by paultsimura** [comment]
This is a BE issue. After a receipt scan fails, the OpenReport API call returns the related ActionItem with `actorAccountID: 0`

<img width="1139" alt="image" src="https://github.com/Expensify/App/assets/12595293/0277fa1e-6395-4715-a259-4131ab563191">

**Comment by dylanexpensify** [comment]
@luacmartins @Beamanator @cristipaval @MariaHCD @Gonals @Li357 any of you free to take this on/review as part of wave4?

**Comment by Gonals** [comment]
I could review the PR, but I don't really have any bandwidth at this moment

**Comment by Gonals** [comment]
> What about for next week @Gonals ?

Heh... There are lots of things waiting for me next week 😢

**Comment by dylanexpensify** [comment]
Got it - @cristipaval @MariaHCD any chance you have the bandwidth?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment]
@Gonals can you work on this this week?

**Comment by dylanexpensify** [comment]
bump @Gonals 🙇‍♂️ ❤️

**Comment by Gonals** [comment]
> Issue not reproducible during KI retests. (First week)

I can'r reproduce it in Dev either, so I'm going to go ahead and close it! @dylanexpensify, let me know if you disagree!
