### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Profile pic gets removed in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings >Profile
2.  change profile pic
3. go to offline and wait for few seconds for the profile pic to disappear
4. check the profile pic which does not have default avatar
## Expected Result:
should show profile pic
## Actual Result:
 does not show profile pic
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ae25653d-6172-4abf-aef6-b1a86720b598

https://github.com/Expensify/App/assets/43996225/66478fff-ddbb-4ff6-97cb-7108525f30c7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693284584253529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016669b07ea66a41c4</li>
        <li>Upwork Job ID: 1702222829517451264</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26747630</li>
<li>gadhiyamanan | Reporter | 26747631</li>
</ul></li>
    </ul>
</details>

**Comment by jscardona12** [comment]
Couldn't replicate on dev

**Comment by gadhiyamanan** [comment]
@hungvu193 `disable cache` is not enabled in kavi's video

**Comment by laurenreidexpensify** [comment]
@eVoloshchak what you think about proposal above?

**Comment by laurenreidexpensify** [comment]
bump @eVoloshchak

**Comment by eVoloshchak** [comment]
Was able to reproduce this, thanks @bernhardoj for the more accurate steps

@tienifr's [proposal](https://github.com/Expensify/App/issues/27252#issuecomment-1719183784) looks good to me
It's kind of an edge case and is hard to reproduce, but still worth fixing I think 

🎀👀🎀 C+ reviewed!

**Comment by srikarparsi** [comment]
Agree let's fix this, assigning you to the issue @tienifr!

**Comment by laurenreidexpensify** [comment]
payment summary: 

-  External issue reporter - @gadhiyamanan - $50, offer needs to be accepted in Upwork 
-  Contributor that fixed the issue - @tienifr - $500, payment issued in Upwork 
-  Contributor+ that helped on the issue and/or PR - @eVoloshchak  - $500 please request payment in newdot

**Comment by laurenreidexpensify** [comment]
@eVoloshchak please advise on steps above ^^

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is an edge case that is reproducible if lose connection at a specific time (after the image was uploaded, but before it can be downloaded from BE by the App)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this is an extreme edge case and we already have an item in the reviewer checklist to test for offline scenarios
- Determine if we should create a regression test for this bug. 
This is an edge case that a few users would have ever encountered, so I don't think regression test is needed here

**Comment by JmillsExpensify** [comment]
$500 payment approved for @eVoloshchak based on BZ summary.

**Comment by laurenreidexpensify** [comment]
updated payment summary:

External issue reporter - @gadhiyamanan - $50, payment issued n Upwork
Contributor that fixed the issue - @tienifr - $500, payment issued in Upwork
Contributor+ that helped on the issue and/or PR - @eVoloshchak - $500 payment approved in newdot

**Comment by laurenreidexpensify** [comment]
@gadhiyamanan updated ^^

**Comment by laurenreidexpensify** [comment]
@tienifr huge apologies for the overlook here, the payment has been issued in Upwork now
