### ISSUE TITLE
Remove ReportActionsUtils.getParentReportAction(), ReportUtils.getParentReport(), TransactionUtils.getLinkedTransaction(), ReportUtils.getPolicy(), and TransactionUtils.getTransaction()

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#27262]
# Problem
These methods are anti-patterns because they are most always used for loading data into a component without using `withOnyx()`. This breaks the data flow of a react application. (data is coming from somewhere that is not props or state and cannot be debugged in react dev tools).

# Solution
Switch all references to properly use `withOnyx()` for components and `connect()` for libs.

### Components
- [x] MoneyRequestHeader @tgolen https://github.com/Expensify/App/pull/28645
- [x] OptionRowLHNData @tgolen https://github.com/Expensify/App/pull/35975
- [x] EditRequestPage @tgolen 
- [x] ~SplitBillDetailsPage~
- [x] extractAttachmentsFromReport @tgolen https://github.com/Expensify/App/pull/30866
- [x] #32309
- [x] #32443
- [x] FlagCommentPage @tgolen https://github.com/Expensify/App/pull/33676
- [x] ReportScreen @tgolen https://github.com/Expensify/App/pull/33970
- [x] ReportActionItem @tgolen https://github.com/Expensify/App/pull/34057
- [x] ~ReportActionList~ No longer references deprecated methods
- [x] withReportAndReportActionOrNotFound @tgolen https://github.com/Expensify/App/pull/34113
- [x] ~ComposerWithSuggestions @tgolen~ already removed\
- [x] `MoneyRequestView` @tgolen  https://github.com/Expensify/App/pull/37703
- [x] `HeaderView` @tgolen https://github.com/Expensify/App/pull/37913
- [x] `ReportActionsListItemRenderer` @tgolen https://github.com/Expensify/App/pull/37449
- [x] FlagCommentPage `getParentReport()` @tgolen https://github.com/Expensify/App/pull/38356
- [x] #38355
- [x] #39091
- [x] #40316
### Libs
- [x] ~IOU~ already removed
- [x] Task @tgolen https://github.com/Expensify/App/pull/37340
- [x] TransactionUtils @tgolen https://github.com/Expensify/App/pull/38258
- [ ] ReportUtils
- [x] #38959
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156f7187832f56740</li>
        <li>Upwork Job ID: 1762552955483959296</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by techievivek** [comment]
Adding @aimane-chnaif to the GH as he helped review the PR: https://expensify.slack.com/archives/C02NK2DQWUX/p1694749699352029

**Comment by tgolen** [comment]
I'm slowly working my way through these, but I wasn't able to get to any of them this week.

**Comment by tgolen** [comment]
I wrote a new PR for the next one on the list today.

**Comment by tgolen** [comment]
I haven't had time to do any additional work on this.

**Comment by tgolen** [comment]
Thanks @bernhardoj. What do you think of this approach?

1. Create a PR that marks all those methods as deprecated (same as I did for `getParentReportAction()` and the others)
2. Start tackling these one-by-one to replace each one

**Comment by tgolen** [comment]
OK, yeah, I know what you mean now. @marcaaron and I have gone back and forth on this topic, and generally we've settled in a place where if there is no problem, then we have left it alone. However, I think it's a safer environment in general if data is usually fetched from `withOnyx` and then passed to action files. There are some performance optimizations that can be gained by having less things in `withOnyx` though, so there will always be some kind of balance we have to determine. For now, let's try to wrap up the current methods that I've marked as deprecated, and then we can tackle these one-by-one and figure out what to do with them (if anything).

**Comment by tgolen** [comment]
I've got PRs for the few remaining components 🎉

**Comment by tgolen** [comment]
@jjcoffee could you please do a C+ review on https://github.com/Expensify/App/pull/37340?

**Comment by jjcoffee** [comment]
@tgolen Sure, will get to that today!

**Comment by tgolen** [comment]
# Weekly Update
- I had [one PR](https://github.com/Expensify/App/pull/37703) merged this week
- I submitted [a new PR](https://github.com/Expensify/App/pull/37913) yesterday for another item on the list

### Next Steps
- Work on FlagCommentPage next

#### ETA
- All done by April 1 (accounts for some OOO I have coming up)

**Comment by tgolen** [comment]
# Weekly Update
- I've fixed a couple more this week
- I've found even more bad methods `ReportUtils.getPolicy()` which I've added to the list
- I'm going to try a slightly different strategy of getting contributors to fix these

### Next Steps
- Start creating contributor issues to clean up the rest of this

#### ETA
- No change

**Comment by tgolen** [comment]
# Weekly Update
- I have been created contributor issues to handle the remaining items and they are moving forward

### Next Steps
- Do a final cleanup of `ReportUtils` once all the current issues are done

#### ETA
- All done by April 9

**Comment by tgolen** [comment]
# Weekly Update
- There were three PRs created last week for most of the remaining items

### Next Steps
- Once all PRs are merged, @tgolen take one last look at `ReportUtils` and make sure it is not exporting anything "bad", then this issue can be closed

#### ETA
- This is bleeding into next week due to slow PR reviews, so updated ETA is Wednesday, April 17.

**Comment by tgolen** [comment]
# Weekly Update
- There is one final PR that is waiting to close out, then this can be closed. 
- I haven't found any more bad instances

### Next Steps
- Wait for [this PR](https://github.com/Expensify/App/issues/40316) to be merged and then close this out

#### ETA
- It looks like it might be merged next week sometime.

**Comment by tgolen** [comment]
# Weekly Update
- Same as last week

**Comment by tgolen** [comment]
# Weekly Update
- I bumped the PR that is holding this up. The contributor hasn't updated it in a couple of weeks now.

**Comment by tgolen** [comment]
`ReportUtils` is the only remaining item, but I took a look at it and I think it's mostly fine for now so I am going to close this out.
