### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web - Workspace name isn't shown in Share code/QR page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to settings -> workspace -> new workspace
2. Now a new workspace should be created with a name
2. Now go to newly created workspace chat head (on LHN) -> click details page -> share code
3. Notice under the QR, 'workspace' is written.
Note : on #admin or #announce channel, proper workspace name is shown in QR. So it's inconsistent.

## Expected Result:
QR should show the corresponding workspace's name. Not a static ' Workspace' text.

## Actual Result:
Workspace name isn't shown in Share code/QR page in workspace's detail page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b31c20d-06ee-4902-8ac8-992409616872

https://github.com/Expensify/App/assets/93399543/8753cd69-036f-4160-9e84-3b0961b52bb7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694256753873399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
Yep, that makes sense! We'll just have to make sure it doesn't cause any weirdness with other types of reports. It still looks a little weird to me that it just says "Workspace" as the subtitle, but I don't have a better suggestion for it.

**Comment by dangrous** [comment]
if we have to we can separate out the title like we do the subtitle, and do something like `if this.props.report.reportName === '' { ReportUtils.getReportName(); } `

**Comment by dangrous** [comment]
Yeah let's hold until we hear from design on this, I think I probably agree with you that getReportName gives us the most consistent results, but I'd want some confirmation. @c3024 to make it slightly easier do you think you could repost your request in text format vs the screenshots? So something like:
* Workspace
  * Old:
    * Title: [empty string]
    * Subtitle: `Workspace`
  * New:
  	* Title: [Name of workspace]
  	* Subtitle: `Workspace`

And then do that ^ for all of the options (workspace chat, archived admins, etc. etc.) you're presenting?

Thank you!

**Comment by c3024** [comment]
- Workspace chat
    - Old:
        - Title: [empty string]
        - Subtitle: `Workspace`
    - New:
        - Title: [Name of workspace]
        - Subtitle: `Workspace`

- Rooms 
    - Old:
        - Title: [Name of room]
        - Subtitle: [Name of workspace]
    - New:
        - Title: [Name of room]
        - Subtitle: [Name of workspace]

- Archived rooms 
    - Old:
        - Title: [Name of room]
        - Subtitle: [Name of workspace]
    - New:
        - Title: [Name of room(archived)]
        - Subtitle: [Name of workspace]

- Chat thread
    - Old:
        - Title: `Chat Report`
        - Subtitle: [empty string]
    - New:
        - Title: [Name of thread]
        - Subtitle: [empty string]

- Task
    - Old:
        - Title: [Name of task]
        - Subtitle: [empty string]
    - New:
        - Title: [Name of task]
        - Subtitle: [empty string]

**Comment by c3024** [comment]
@dangrous Thank you.  ^^ old and new fields in QR codes.

**Comment by sonialiap** [comment]
@0xmiroslav review + bonus $750 - offer sent
@c3024 fix + bonus $750 - offer sent
@ashimsharma10 report $50 - offer sent

**Comment by sonialiap** [comment]
@0xmiroslav please complete the [checklist](https://github.com/Expensify/App/issues/27265#issuecomment-1733255365)

**Comment by c3024** [comment]
Accepted @sonialiap thanks.

**Comment by c3024** [comment]
@sonialiap Could you please complete the payment? Thanks!

**Comment by sonialiap** [comment]
@0xmiroslav review + bonus $750 - please accept the offer 💰 
@c3024 fix + bonus $750- paid ✔️ 
@ashimsharma10 report $50 - paid ✔️
