### ISSUE TITLE
[HOLD Expensify/Expensify#314888] [User-Created Rooms Release] UI for Room Invitations/Removals [EXTERNAL]

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#27284]
# Part of the User-Created Rooms Release project
Main issue: https://github.com/Expensify/Expensify/issues/316180
Doc section: https://docs.google.com/document/d/1V4DwJjzx_Uxa47w6sjAfYTUthH8whdmMIWqp2FrsH5U/edit#bookmark=id.pk1yzb5mi082
Project: https://github.com/orgs/Expensify/projects/76

# Manual Test Steps
https://docs.google.com/document/d/1V4DwJjzx_Uxa47w6sjAfYTUthH8whdmMIWqp2FrsH5U/edit#bookmark=id.n9bbcvb7p629

# Automated Tests
N/A

**Comment by laurenreidexpensify** [comment]
@jasperhuangg can you add some more context here - I'm not really sure what action I'm meant to take?

**Comment by laurenreidexpensify** [comment]
@jasperhuangg bump

**Comment by laurenreidexpensify** [comment]
Hey @jasperhuangg please update with next expected action here. Thanks

**Comment by jasperhuangg** [comment]
Sorry for missing these pings @laurenreidexpensify!

I've been working on a bunch of PRs for this
- https://github.com/Expensify/Auth/pull/8776
- https://github.com/Expensify/Auth/pull/8937
- https://github.com/Expensify/App/pull/27966
- https://github.com/Expensify/Web-Expensify/pull/38879

We're making good progress and should hope to have everything merged/deployed by EOW.
