### ISSUE TITLE
[$500] Android - Skin tone gets separated from emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Select an emoji with any skin tome. eg: :+1::skin-tone-2:
3. Create a empty space in composer

## Expected Result:
Skin tone should not be separated from emoji.

## Actual Result:
Skin tone is separated from emoji.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6fcc342e-c533-471a-8344-70595fdda5ec

https://github.com/Expensify/App/assets/93399543/18e19023-523e-46c8-bb93-191319bd31d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694275372396219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104ec11eb1a2d30cc</li>
        <li>Upwork Job ID: 1701663844103421952</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@Christinadobrzyn un-assigning you since I was assigned first.

**Comment by puneetlath** [comment]
Sounds good, thanks y'all.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by kbecciv** [comment]
Checking, will update you shortly

**Comment by kbecciv** [comment]
Unable to reproduce it on build 1.3.86.0

https://github.com/Expensify/App/assets/93399543/b7bb024b-a813-46c5-afd2-85e743f9e0b1

**Comment by puneetlath** [comment]
Great! Seems like it's fixed 😄
