### ISSUE TITLE
[$500] Web - The group is deleted when there are no messages or the first parent message deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group
2. Send any message
3. Hover on message and reply in thread
4. Send any message on thread
5. Delete the parent message, Observed that the chat group disappeared on LHN

## Expected Result:
Group chat remains on LHN when there are no messages or messages are deleted.

## Actual Result:
Group chat disappeared on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2b09e205-470a-4e4b-b4d6-a59c5c9c8524

https://github.com/Expensify/App/assets/93399543/e7f73dd0-f582-456e-9515-71f87a9e88d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694319570718779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad723399ebef5bd6</li>
        <li>Upwork Job ID: 1701697394182508544</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
We are checking whether the report is displayed on LHN here:
https://github.com/Expensify/App/blob/6188d7b06f50e34f19c6f6f1ea8f59b2a3f412a6/src/libs/ReportUtils.js#L2847-L2850
We are checking the isEmptyChat report here
https://github.com/Expensify/App/blob/6188d7b06f50e34f19c6f6f1ea8f59b2a3f412a6/src/libs/ReportUtils.js#L2818-L2820
Here, if the report has only 1 message and that message has a thread. After deleting the parent message, the report still displays the message `[Deleted message]` and there is a thread in this message. But we are only checking `lastVisibleMessage` so the miss case message is deleted but the thread remains.
### What changes do you think we should make in order to solve the problem?
We should update the `isEmptyChat` checking logic by checking reportActions. If there is any item with `childVisibleActionCount ` > 0. That means the message still has a thread.
```js
    const lastVisibleMessage = ReportActionsUtils.getLastVisibleMessage(report.reportID);
    const reportActions = ReportActionsUtils.getAllReportActions(report.reportID);
    let isEmptyChat = false;
    if (!lastVisibleMessage.lastMessageText && !lastVisibleMessage.lastMessageTranslationKey) {
        const has thread = _.some(reportActions, (reportAction) => reportAction.childCommenterCount > 0);
        isEmptyChat = !hasThread
    }
```
Result:
https://github.com/Expensify/App/assets/39086067/ddf7244d-16ad-4bf2-bf3d-3b170de3aa8e
### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
Maybe relate to https://github.com/Expensify/App/issues/19722

**Comment by CortneyOfstad** [comment]
@zanyrenney There is known issue (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)) where it is double-assigning, so removing your assignment 👍
