### ISSUE TITLE
[$500] Chat- HTML Reserved chars in workspace name gets decoded into string

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the settings
2. Create or select a workspace and rename
3. Use encoded version of an html reserved char in the workspace name (eg. `&amp;Hello`)
4. Go to the admin room of the workspace

## Expected Result:
 Rename system message should show encoded chars as in `&amp;Hello`

## Actual Result:
Reserved chars are decoded into message string in text field from BE `&Hello`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-10 at 00 37 49](https://github.com/Expensify/App/assets/93399543/76069bca-d55d-43d2-9ab9-8c793ab2ba9d)

https://github.com/Expensify/App/assets/93399543/0847bc2f-f8b9-4db9-bfa6-e1744c3b97b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kursat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694295351896949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01128899aae73e1cfd</li>
        <li>Upwork Job ID: 1701687382510047232</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by salonikumawat28** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
HTML Reserved chars in workspace name gets decoded into string
## What is the root cause of that problem?
Server API sends incorrect decoded data for `text` but correct data for `html` which we internally use to store as `lastMessageText` and `lastMessageHtml` respectively and use `lastMessageText` to display.
Snippet of response from API:
```
{
            "onyxMethod": "merge",
            "key": "reportActions_5493783319534928",
            "value": {
                "6342252294350896925": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Saloni Kumawat"
                        }
                    ],
                    "actorAccountID": 15643995,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "updated the name of this workspace from \"Hello\" to \"&amp;Hello\"",
                            "text": "updated the name of this workspace from \"Hello\" to \"&Hello\"",
                            "isEdited": false,
                            "whisperedTo": [],
                            "isDeletedParentAction": false,
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "lastModified": "2023-09-12 21:15:55.168",
                        "newName": "&amp;Hello",
                        "oldName": "Hello",
                        "policyType": "free"
                    },
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_4.png",
                    "created": "2023-09-12 21:15:55.168",
                    "timestamp": 1694553355,
                    "reportActionTimestamp": 1694553355168,
                    "automatic": false,
                    "actionName": "POLICYCHANGELOG_UPDATE_NAME",
                    "shouldShow": true,
                    "reportActionID": "6342252294350896925",
                    "lastModified": "2023-09-12 21:15:55.168",
                    "whisperedToAccountIDs": [],
                    "sequenceNumber": null,
                    "isAttachment": false
                }
            },
            "shouldNotify": true
        },
```
In above response, check the following data:
```
"html": "updated the name of this workspace from \"Hello\" to \"&amp;Hello\"",
"text": "updated the name of this workspace from \"Hello\" to \"&Hello\"",
```
`text` received is already decoded.
## What changes do you think we should make in order to solve the problem?
We should do nothing in `App`. We should fix the bug in server and add a `test` to make sure this special case is handled.
## What alternative solutions did you explore? (Optional)

**Comment by salonikumawat28** [comment]
Contributor details
Your Expensify account email: 545saloni@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ae7c7ab48e070b98

**Comment by kursat** [comment]
This is where the bug was spotted maybe it helps someone: https://github.com/Expensify/App/issues/24427#issuecomment-1710457053

**Comment by salonikumawat28** [comment]
@kursat Thanks for the pointer.
Updated [Proposal](https://github.com/Expensify/App/issues/27291#issuecomment-1716464064)

**Comment by johncschuster** [comment]
@thesahindia can you take a look at the above proposal when you get a moment?

**Comment by anmurali** [comment]
I am not sure why two BZ team members are assigned. I am unassigning myself @johncschuster

**Comment by johncschuster** [comment]
@thesahindia I think we need to raise the bounty. Do you agree?
