### ISSUE TITLE
[$1000]  iOS17 beta - Chat - User receives only the last message sent to them while offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into iOS App on iOS 17 beta. On another device, log in to another account
2. Go OFFLINE on the main testing device.
3. On another device (can be any), send a message to the account logged in the main testing device (iOS 17 beta)
4. On the main device - Navigate to LHN
5. Go ONLINE
6. Ensure the message you sent via the other device is received in the main device
7. Verify the conversation is displayed bold in LHN
8. Go OFFLINE
9. Tap on the bold chat in LHN

## Expected Result:
All new messages are displayed in the conversation history

## Actual Result:
Only the last message is displayed in the conversation history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS 17 beta (21A329)
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-17

**Reproducible in staging?:** Y

**Reproducible in production?:** Not repro on iOS 16.6.1 / Repro on production in iOS 17 beta.

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8b126b70-4787-47d7-83e1-f742f6f973a2

https://github.com/Expensify/App/assets/115492554/f56d2d5f-29ee-4370-a198-4b2d538706fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148fba7a6dbc40f0c</li>
        <li>Upwork Job ID: 1702222570422874112</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Waiting for proposals

**Comment by laurenreidexpensify** [comment]
Doubled price

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by laurenreidexpensify** [comment]
@izarutskaya can we confirm if this one is still reproducible in regression testing? thanks

**Comment by shubham1206agra** [comment]
@laurenreidexpensify I am unable to repro this on iOS 17 (Simulator iPhone 15 Pro)

**Comment by laurenreidexpensify** [comment]
@izarutskaya bump

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
