### ISSUE TITLE
iOS17 beta - Chat - Free space appears in composer when ‘Edit comment’ if message more 1 line

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS App on iOS 17 beta
2. Login with any account
3. Open any chat
4. Tap on any message containing more than 1 line and select 'Edit comment'

## Expected Result:
Only the message is shown in the edit field

## Actual Result:
Free space appears in edit field after selecting ‘Edit comment’ if the message has more than 1 line.
This space disappears after tapping on the edit field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS 17 Beta (21A329)
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68-17

**Reproducible in staging?:** Y

**Reproducible in production?:** Not repro on iOS 16.6.1 / Repro on production in iOS 17 beta.

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/839b5a69-235c-43f0-8cc0-ecc216141dc9

https://github.com/Expensify/App/assets/115492554/90059238-7145-4845-bcc0-c516d750bb00

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm clarifying in an internal channel whether we're prioritizing iOS 17 beta specific bugs: https://expensify.slack.com/archives/C01SKUP7QR0/p1695007921712749. 

I don't have the iOS 17 beta so I'm not sure how I'd test this one.

**Comment by tjferriss** [comment]
@izarutskaya now that iOS 17 has been publicly released, can you retest and let me know if you're still able to reproduce the bug?

**Comment by tjferriss** [comment]
I'm going to close. @izarutskaya please reopen if the bug is still reproducible.

**Comment by izarutskaya** [comment]
Sorry for waighting, not repro with build 1.3.75-3 on iOS 17.0.2

https://github.com/Expensify/App/assets/115492554/28c63d6c-c6dc-4f89-8c38-22bfa43942e4
