### ISSUE TITLE
[$500]  Request money - Scan - The ongoing receipt scanning process is taking too long (High latency)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select Request money
2. Select Scan
3. Click on the image icon and select any image
4. Select email recipients and write a simple description
5. Click the Save button

## Expected Result:
The result has to happen immediately

## Actual Result:
The ongoing receipt scanning process is taking too long

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/67b9634e-58da-439c-90ac-2ec9b229b82a

https://github.com/Expensify/App/assets/115492554/1a3c0af7-39a3-40fa-a2d5-c901bf555cbe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @thuyle04

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693990078757979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe6e5aa6e60b21e0</li>
        <li>Upwork Job ID: 1701916951887294464</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Unassigning myself as I was the 2nd B0 team member assigned.

**Comment by mountiny** [comment]
This cannot be external and I think @Gonals already works on some fixes for this

**Comment by Gonals** [comment]
How is this a bug? The receipt is smartscanning. That takes a while 😕 

Am I missing something?

**Comment by mountiny** [comment]
How long should it take? I guess that is the question :D I will defer to you here, feel free to close

**Comment by Gonals** [comment]
> How long should it take?
As long as our Smartscan person takes to fill it? There is a guy doing this manually! 😆

**Comment by Ngannguyen0308** [comment]
I checked again and found that it took quite a long time for the receipt to be scanned, and most of the time I couldn't send the Request money by scan image.

**Comment by Gonals** [comment]
> it took quite a long time for the receipt to be scanned

Yes. The Scan process is not automatic in all cases. For many receipts, an agent has to get to your receipt and manually input the data. It can even take an hour (but it usually takes way less)

**Comment by thuyle04** [comment]
In reality, it's take even more. In this morning i just tested this case (at 9:55AM) but until now (15:30PM), The receipts has not been sent successfully. Here is the image 
![872d5bae2e46fb18a257](https://github.com/Expensify/App/assets/63705956/5c5424bc-b967-4a4d-9b5d-2d71c9e9166b)


> > it took quite a long time for the receipt to be scanned
> 
> Yes. The Scan process is not automatic in all cases. For many receipts, an agent has to get to your receipt and manually input the data. It can even take an hour (but it usually takes way less)

**Comment by thuyle04** [comment]
> How is this a bug? The receipt is smartscanning. That takes a while 😕
> 
> Am I missing something?

I think it's too soon to have the conclusion that we should close this one, because this feature is not working well at the moment
