### ISSUE TITLE
Clean up styles.js

### ISSUE THREAD

**Issue by grgia** [Expensify/App#27336]
Convert the static styles in styles.js into functions that take the current theme as an argument instead of a static import. The default export of styles.js will still be the styles with the defaultTheme provided, so this doesn't break anything.

Remove the need to add dynamic styles manually to providers.

**Comment by grgia** [comment]
@chrispader mind updating the description here for your open PR?

**Comment by chrispader** [comment]
I can't update the issue description because i'm not the issue owner 🥴

**Comment by grgia** [comment]
gotta love github

**Comment by grgia** [comment]
not overdue

**Comment by chrispader** [comment]
@grgia is this done? :)

**Comment by grgia** [comment]
@chrispader should we close?

**Comment by chrispader** [comment]
yes 👍
