### ISSUE TITLE
[$500] [HOLD for payment 2023-09-21] In split bill confirmation page Row stay selected even if we deselect it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Goto any group chat report
2. Click on + to open options and select Spill bill
3. Enter amount and go to next
4. In the participants list try to deselect any participant
5. Observe it stays selected with the checked icon
## Expected Result:
Participants row should gets toggled on select/deselect

## Actual Result:
 Participant row stays selected
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/85686e4f-914f-4c7c-8243-a5437124c7cc

https://github.com/Expensify/App/assets/43996225/df924169-5545-4c80-9d55-3f88fa3a9d61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694608070230219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bd3267bf049749b</li>
        <li>Upwork Job ID: 1704694115582894080</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal from @Pujan92 
### Please re-state the problem that we are trying to solve in this issue.
In Split bill participants confirmation page the participant styles stays selected even though we deselect it
### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/26501 where we applied a [new condition](https://github.com/Expensify/App/pull/26501/files#diff-c47572d3c6f54d346f66de8073837db5082c76501af076e3e80990cd25bffd9aL178) for deciding `isSelected` here `option.name === item.searchText`. For this page, both values are undefined and it makes the conditional value true.
https://github.com/Expensify/App/blob/1baf33af3ba8e603b9cdae7ae8a99cfb5ffb2e63/src/components/OptionsList/BaseOptionsList.js#L180
cc: @rezkiy37
### What changes do you think we should make in order to solve the problem?
Before comparing both values we may need to check any of the value availability so we do not end up with comparing undefined values.
`(!_.isEmpty(option.name) && option.name === item.searchText)`

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue, because I am the author of [the broken PR](https://github.com/Expensify/App/pull/26501).

**Comment by rezkiy37** [comment]
[The PR](https://github.com/Expensify/App/pull/27350) already reviewing internally, public review gonna be soon.

**Comment by zanyrenney** [comment]
Only payment due is: @Pujan92 for reporting bonus.

**Comment by zanyrenney** [comment]
no more people needed, just added `external` for upwork job

**Comment by zanyrenney** [comment]
@Pujan92 invited you for reporting bonus - https://www.upwork.com/jobs/~011bd3267bf049749b

**Comment by Pujan92** [comment]
> @Pujan92 invited you for reporting bonus - https://www.upwork.com/jobs/~011bd3267bf049749b

Thanks @zanyrenney , Accepted!

**Comment by zanyrenney** [comment]
offer is pending @Pujan92

**Comment by Pujan92** [comment]
Sorry, just accepted.

**Comment by zanyrenney** [comment]
Paid! Thanks for your work here @Pujan92

**Comment by Pujan92** [comment]
Again sorry @zanyrenney , I got paid more, it should be $50 so I refunded $200. Hope you recieved it as I am doing refund for the first time.
