### ISSUE TITLE
Home Address - Incorrect input appear in State field when input value than select US country

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Navigate to Settings -> Profile -> Personal details
3. Navigate to Home address page
4. Input any value in State/Province field
5. Click on the Country and select USA from the picker

## Expected Result:
When User navigate back to Home address page "State" field should be empty

## Actual Result:
When User navigate back to Home address page incorrect value remains in "State" section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b9218074-74ba-4f41-b9c5-4b80efac598c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This is a regression of [this PR](https://github.com/Expensify/App/pull/25846)

**Comment by Pluto0104** [comment]
It might be fixed after [this PR](https://github.com/Expensify/App/pull/27358) is merged.

**Comment by jasperhuangg** [comment]
This has been fixed!
