### ISSUE TITLE
[$500]  Android - Keyboard does not open automatically when replying to message in a task report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Create a task
3. Send any message in task report
4. Select message and press reply in thread
5. Observe keyboard does not open automatically

## Expected Result:
The keyboard should be opened automatically

## Actual Result:
 The keyboard is not opened automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/38287caf-399c-495b-a6c1-2530bf0983c9

https://github.com/Expensify/App/assets/93399543/8413e93e-35e7-4011-9ed0-cd54701bcaef

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694366917362669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cb6134fb786c7cd</li>
        <li>Upwork Job ID: 1701986170235686912</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Re-opened other GH, since it was reported first!
