### ISSUE TITLE
[$500] Android - Workspace - Unable to select members in Workspace to invite members by tapping ->key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap split bill
4. Enter an amount
5. Tap next
6. Tap ->key repeatedly to select contacts
7. Tap profile icon
8. Tap Workspaces
9. Tap any Workspace
10. Tap members
11. Tap invite
12. Tap ->key repeatedly to select contacts
13. Enter an email and try to tap ->key repeatedly to select contacts

## Expected Result:
Tapping ->key to select contacts in split bill is working. Similarly, user with same key must be able to select members in Workspace to invite members

## Actual Result:
Tapping ->key to select contacts in split bill is working but with same key unable to select members in Workspace to invite members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/720011a9-4376-4215-bd22-7340843b1d18

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b10c09c059cb764</li>
        <li>Upwork Job ID: 1702332070742261760</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Sorry, I'm a bit confused by this issue. 

The reproduction steps have a bunch of steps with split bill, before eventually going to the workspace. Is that required to experience the bug? Or does this bug exist with workspace invite no matter what? 

As for the behavior, I think we want it to be consistent. So if I'm understanding correctly, on the split bill page you are able to select people with the return key, but in workspace invite, you aren't. Is that right?

**Comment by puneetlath** [comment]
I see...interesting. Naive question: why do we have two different components that do such similar things?

**Comment by puneetlath** [comment]
Thanks @ntdiary. I think it's best to close this for now. It seems like what we have is the expected behavior, even if it is inconsistent. 

Feel free to comment if you disagree!
