### ISSUE TITLE
[$500] mWeb -  Focus is present but keyboard closes on minimize and reopen on mWeb chrome

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Focus on compose box
4. Minimize the browser
5. Open it back and observe the compose box has focus but keyboard is closed

## Expected Result:
If focus is present, app should keep the keyboard open

## Actual Result:
Even if focus is present on compose box on reopening the browser after minimize, app does not open the keyboard (works fine on android app)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1758c78b-faae-407b-bf97-d60aa1b783a7

https://github.com/Expensify/App/assets/93399543/390e3841-f7e0-4785-83d9-43ad31c40439

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694372284632519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7afebfafb3e35ee</li>
        <li>Upwork Job ID: 1701994532380684288</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment]
Yes now I checked few websites and it seems to be common issue in chrome. 

Sorry for the tagging issue, not sure how can I solve that 😅

**Comment by trjExpensify** [comment]
Perfect, thanks for working through that ya'll. Closing!
