### ISSUE TITLE
[HOLD for payment 2023-11-13] [HOLD for payment 2023-10-30] [$500] Update LHN/chat header to handle displayName not being set

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#27393]
We are going to stop sending a display name from the back-end in certain scenarios. In those scenarios, we should fall back on using "Hidden" in the LHN and Chat Header (and anywhere else that relies on display name being set). 

Let's update any place that expects a display name to fall back on the primary login. And if there is neither a displayName or a primary login, to fall back on "Hidden". 

<img width="1507" alt="Screenshot 2023-09-13 at 7 13 20 PM" src="https://github.com/Expensify/App/assets/1371996/c46d2aa2-5a34-4a18-8bc0-ce78e5c1818c">

Issue reported by: @parasharrajat
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694550580877519
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011dd93c0b122cf21f</li>
        <li>Upwork Job ID: 1715060740724056064</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by lukemorawski** [comment]
@puneetlath It's Lucas from Callstack. Happy to work on that. Just wanted to clarify one thing. By fallback to "Hidden" you mean displaying a text "Hidden" in the header and LHN?

**Comment by puneetlath** [comment]
Yes, exactly. Let's have the text "Hidden" be the final fallback text whenever we use display names and aren't able to find either a display name or a login.

**Comment by lukemorawski** [comment]
@puneetlath How can I create an account with no display name, to test that change?

**Comment by puneetlath** [comment]
We chatted in Slack, but this will only be testable by adding fake data in Onyx or removing data from an existing user.

**Comment by sakluger** [comment]
This issue was reported by @parasharrajat before @puneetlath created this issue. I've added the Slack thread where the issue was reported so that @parasharrajat can be paid out the reporting bonus.

**Comment by lukemorawski** [comment]
@puneetlath I think I have found a sultion to the problem

**Comment by puneetlath** [comment]
Great!

**Comment by puneetlath** [comment]
@lukemorawski how's the fix going? Think we can have a PR tomorrow?

**Comment by lukemorawski** [comment]
yep, will have a fix today

**Comment by lukemorawski** [comment]
@puneetlath new PR added

**Comment by puneetlath** [comment]
Does that also handle adding back the previous changes that were reverted?

**Comment by lukemorawski** [comment]
Ah, dang it, they reverted themselves after I resolved a conflict against "main" branch! Such a noob thing to do 🤦‍♂️  Give me a moment while I'll bring 'em back.

**Comment by puneetlath** [comment]
Haha all good! Git is fun 😅

**Comment by lukemorawski** [comment]
@puneetlath updated the latest PR with all the changes!

**Comment by puneetlath** [comment]
Great!

**Comment by puneetlath** [comment]
Note to self: both @mananjadhav and @allroundexperts were involved in PR review here. Will need to figure out compensation.

**Comment by puneetlath** [comment]
Payment Summary: 
- @mananjadhav C+ first PR - $500
- @allroundexperts C+ second PR - $500

Please both request on NewDot.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on summary above.

**Comment by puneetlath** [comment]
Whoops, sorry about that. Updated @parasharrajat
