### ISSUE TITLE
Android- Profile - The image is visible in mweb and displayed black in Android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap profile
4. Tap profile image
5. Tap upload photo, use below photo
6. Tap save

## Expected Result:
The image should be visible

## Actual Result:
The image is visible in mweb and displayed black in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/381f3385-f0c4-4608-a041-dd6cf293b3d2

![Bug6199547_image-2023-08-30_13_08_21 275](https://github.com/Expensify/App/assets/78819774/cc66cd19-6ffa-4d63-9d66-3cfa117f1443)

**Expensify/Expensify Issue URL:** Applause - Internal Team

**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I'm not sure this is actually a bug. This image also shows up black when I save it to my camera role. So it seems like this is just how native platforms interpret this type of image. I don't view this as a bug.

**Comment by s-alves10** [comment]
@tjferriss 

Yes, I think this is a native feature. But we store images as jpeg format and can convert those images with proper options. I still think this is worth fixing
