### ISSUE TITLE
[c+ checklist needs completion] [$500] Task - Task shared in admin-only room can be marked done in chat, but not in the task report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As user A, create a room with admin only posting permission with User B and C
2. As user B, go to the room and click on the task
3. As user B, attempt to mark the task as done in the task report
4. As user B, return to the room chat and tap on the checkbox to mark it as done

## Expected Result:
If the task edit access is denied for the other user, user should not be able to complete the task from the room chat and also the task report

## Actual Result:
User is unable to mark the task as complete in the task report, but can do so from the room chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ccd24bff-ac48-44b7-9644-c3b2e9b42d83

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a5abcdb42d5f07e</li>
        <li>Upwork Job ID: 1703725038758084608</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26848651</li>
<li>hoangzinh | Contributor | 26848653</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment]
With new implementation, Anyone who can view the task can edit it.
Please confirm, @thi

**Comment by greg-schroeder** [comment]
adding external to get a c+

**Comment by mollfpr** [comment]
The issue still reproduces, but what is weird to me is that completing tasks from the non-admin user is returned fine from the API.

>With new implementation, Anyone who can view the task can edit it.

@BhuvaneshPatil Could you attach the discussion of this?

**Comment by thienlnam** [comment]
Hmm yeah I think we may need to rethink this for an admin-only room though.

In this case actually I would think that only admins / the task assignee would be able to modify the task

**Comment by mollfpr** [comment]
We can align the check on the `TaskView` and `TaskPreview` with a unified function, so when we decide to change the behavior, we only need to change the function on each component.

Does this sound good to you?

**Comment by thienlnam** [comment]
Yeah sounds good, though I am surprised they are different - I would imagine that they would be using the same check if they can modify the task

**Comment by mollfpr** [comment]
I think the [proposal](https://github.com/Expensify/App/issues/27402#issuecomment-1719066715) from @hoangzinh looks good but with the addition of creating the function to check the disable action for both components. So let's go with that!

🎀 👀 🎀 C+ reviewed!

**Comment by greg-schroeder** [comment]
Not overdue, just assigned

**Comment by mallenexpensify** [comment]
Confirming the [hire date here](https://github.com/Expensify/App/issues/27402#issuecomment-1723178920) for @mollfpr is September 18.  Their first hire date was March 8, 2022 - [link](https://github.com/Expensify/App/issues/7965#issuecomment-1061059162)
 
 cc @greg-schroeder, as an example for when/how we denote a contributor can be paid via NewDot

**Comment by greg-schroeder** [comment]
Payments:

Contributor: @hoangzinh $500
C+: @mollfpr $500

**Comment by mollfpr** [comment]
> [@hoangzinh / @mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@hoangzinh / @mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR is causing the bug. This is an improvement to align the task action across the components.

> [@hoangzinh / @mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


The regression step should be enough.

>[@hoangzinh / @mollfpr] Determine if we should create a regression test for this bug.
 [@hoangzinh / @mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

_Precondition: As user A, create a room with admin-only posting permission with User B and C. In that room, create a Task that is assigned to user B_

1. Login as user B
2. Go to room above
3. Verify that user B can press the checkbox of updating Task status
4. Press on the task to go to Task report details
5. Verify that user B can press the checkbox of updating Task status
6. Sign out and sign in as user C
7. Go to room above
8. Verify that user C can not press the checkbox of updating Task status
9. Press on the task to go to Task report details
10. Verify that user C can not press the checkbox of updating Task status

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mollfpr based on BZ summary.

**Comment by mallenexpensify** [comment]
Created the TestRail GH cuz I happened to be reviewing this issue (for some unknown reason) so, closing meow
- https://github.com/Expensify/Expensify/issues/327078
