### ISSUE TITLE
[$500] Dev - console log error when creating a public room

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27404]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Click on 'FAB' menu
3. Click on 'New room'
4. Enter name > select the workspace you have created > choose 'Public' for visibility
5. Click on 'Create room'

## Expected Result:
There shouldn't be no console log error

## Actual Result:
Console log error displayed [TypeError: Failed to construct 'URL': Invalid URL]

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.69-0
**Reproducible in staging?:** no
**Reproducible in production?:** no 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/87365e4e-e3fb-44fd-b88c-891edbae8989

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692792825436599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163077462b5e8a5c8</li>
        <li>Upwork Job ID: 1702162396097982464</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Thanks @hungvu193 gonna close this updated the other to denote @Natnael-Guchima reported the bug first
https://github.com/Expensify/App/issues/26614#issuecomment-1719054417
