### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-25] Display company cards in Wallet

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#27417]
HELD on https://github.com/Expensify/App/issues/22872

Implement this section of the design doc - https://docs.google.com/document/d/1vnZSy0ot3Ykz7sRTw2A5Cvuj9_azjkj90ikE_iuwvF8/edit#bookmark=id.fn2ijzi5eww7

> We’ll use [PaymentMethodList](https://github.com/Expensify/App/blob/52a18912a42567fdc25cb6c64676516959a16781/src/pages/settings/Payments/PaymentMethodList.js#L136-L137) to display company cards with the following changes:
> We’ll pass () => {} to the [onPress](https://github.com/Expensify/App/blob/69ac668a3463b05734c42b894b8dd16f351f6ce4/src/pages/settings/Wallet/PaymentMethodList.js#L174) prop
> The cardName will be set to cardName
> We’ll set `props.shouldShowRightIcon={isExpensifyCard) to hide the right caret
> We’ll use BankIcons.getBankIcon to display the icon associated with the card program. Icon assets already exist in `assets/images/bankicons`
> We’ll add a new iconStyle prop to MenuItem and pass it to the Icon component [here](https://github.com/Expensify/App/blob/69ac668a3463b05734c42b894b8dd16f351f6ce4/src/components/MenuItem.js#L172).
> We’ll then pass the rounded square style as seen in the [mocks](https://docs.google.com/document/d/1vnZSy0ot3Ykz7sRTw2A5Cvuj9_azjkj90ikE_iuwvF8/edit#bookmark=id.6fvxjl2xqe41).
> We’ll add the same styles to the bank account tile icons.
> We’ll add a new prop canClose to OfflineWithFeedback, defaulting to true.
> We’ll conditionally render the [close button](https://github.com/Expensify/App/blob/69ac668a3463b05734c42b894b8dd16f351f6ce4/src/components/OfflineWithFeedback.js#L125-L134) if canClose is true
> We’ll pass () => {} as onClose callback to OfflineWithFeedback
> We’ll pass interactive={isExpensifyCard}
> We’ll pass canDismissError = isExpensifyCard in [renderItem](https://github.com/Expensify/App/blob/69ac668a3463b05734c42b894b8dd16f351f6ce4/src/pages/settings/Wallet/PaymentMethodList.js#L202)
<details><summary>Upwork Automation - Do Not Edit</summary>
<ul>
<li>Upwork Job URL: https://www.upwork.com/jobs/~01c7d9a978f64c8780</li>
<li>Upwork Job ID: 1702220961846599680</li>
<li>Last Price Increase: 2023-09-14</li>
</ul>
</details>

**Comment by luacmartins** [comment]
@shawnborton I just realized that we actually don't set any bank icon styles and they come from the SVGs. Example below:

![Screenshot 2023-10-16 at 4 17 51 PM](https://github.com/Expensify/App/assets/22219519/b4e02603-d051-4a9c-ade9-e90f1265f3eb)


Do we have bank icon SVGs that match the square with rounded borders, like we show in the design doc mocks?

![Screenshot 2023-10-16 at 3 46 20 PM](https://github.com/Expensify/App/assets/22219519/93e47642-3028-4efc-98c2-f7e985265ff8)

**Comment by shawnborton** [comment]
Here are updated card images, cc @grgia [card-icons.zip](https://github.com/Expensify/App/files/12942003/card-icons.zip)

**Comment by grgia** [comment]
hey @shawnborton a couple of these are looking a little funky -
<img width="200" alt="image" src="https://github.com/Expensify/App/assets/38015950/dce0e53e-0f50-4603-9ed3-7aff8d2d8c9d">
<img width="200" alt="image" src="https://github.com/Expensify/App/assets/38015950/7c5a461e-c4d2-4863-8258-5c67cd35f71f">
<img width="200" alt="image" src="https://github.com/Expensify/App/assets/38015950/9ff2cfe3-f404-4225-95f9-1ed0418aee06">

Also, we have two shapes- square and card shaped: 
<img width="200" alt="image" src="https://github.com/Expensify/App/assets/38015950/016241e7-dbae-4a23-ace1-11dff0179051">

is the idea to crop it for the card view?

**Comment by shawnborton** [comment]
Yeah, I basically used all of the existing bank logos (hence the funkiness) and resized them down to 40x26 so they look more like a rectangle. 

I can update the super funky ones though, will just need some time to get some new source svg logos!

**Comment by grgia** [comment]
@shawnborton could we size them as 40x40 for this shape:

![image](https://github.com/Expensify/App/assets/38015950/c73095b3-32c8-4d03-a2c0-1ba2a0659165)


 and then just crop the 40x40 to 40x26 in code for the card shape?: 
![image](https://github.com/Expensify/App/assets/38015950/fe452abb-65fe-4b60-91dc-ebbbe8e9632c)

**Comment by grgia** [comment]
![image](https://github.com/Expensify/App/assets/38015950/b38649dc-28c4-4112-9069-4d8a0692e381)

could I also get the darker green version of the ECard?

**Comment by shawnborton** [comment]
@grgia I wasn't just cropping the images, I was scaling them down a bit since some of them didn't look great at that smaller size. Hence why there is a zip of new images above.

As for the Expensify Card image, I think what you have mocked up is actually what we need to use (it has to always include the Visa logo apparently)

**Comment by grgia** [comment]
Are we using this mock or 
![image](https://github.com/Expensify/App/assets/38015950/32de311b-ee37-4565-9118-ee368fdd10e5)

![image](https://github.com/Expensify/App/assets/38015950/24fad551-cff8-407a-964b-638e29121448)

for the bank account icons?

And then for the ECard, can we get a slightly darker version with the visa logo? 
I think it should be AppBG for this view but the mock we have is this one 
<img width="74" alt="image" src="https://github.com/Expensify/App/assets/38015950/fd949faa-3980-45f0-bdd5-27e5e0b79c64">

**Comment by grgia** [comment]
I was able to use the card icons you sent for the assigned card view - i.e:
<img width="470" alt="image" src="https://github.com/Expensify/App/assets/38015950/740cbb1a-cf9f-4d24-a45d-1081a2470a4d">

just wondering if we need to update the circular icons or not

**Comment by shawnborton** [comment]
- I can get you a new small ECard svg, hang tight
- For bank accounts, I think we can use the existing SVGs but let's make them rounded squares instead of circles
- "yourmom" lol

For the card rows, can we try to make them match more like this where everything is vertically centered, and the card name and subtext is a bit closer together?
<img width="686" alt="CleanShot 2023-10-18 at 07 46 57@2x" src="https://github.com/Expensify/App/assets/2319350/502a6377-230d-4282-9bc7-24bb25b4776d">

**Comment by shawnborton** [comment]
Here's an updated card image: [card-avatar__expensify.svg.zip](https://github.com/Expensify/App/files/13023043/card-avatar__expensify.svg.zip)

**Comment by grgia** [comment]
<img width="461" alt="image" src="https://github.com/Expensify/App/assets/38015950/0e86e59a-4e52-4143-baaf-897edfa57840">

Here's an example of that. However, the spacing between the Title and description is currently 4px for all Menu Items using this pattern- should we change that?

**Comment by grgia** [comment]
ECard looking much better!
<img width="471" alt="image" src="https://github.com/Expensify/App/assets/38015950/e834d167-e25a-48f4-a816-f2e4c0d73ac8">

**Comment by shawnborton** [comment]
In terms of the spacing, when you say "all Menu Items using this pattern" - do you just mean the cards/banks/etc? Or are there more things beyond that?

**Comment by grgia** [comment]
All Menu Items with a subtitle - so anywhere we use this pattern. I.e.

<img width="490" alt="image" src="https://github.com/Expensify/App/assets/38015950/f7259553-3e39-4479-982b-b3abd40ebebb">

**Comment by grgia** [comment]
I think eventually we should separate them out, because the MenuItem file props look insane

https://github.com/Expensify/App/blob/df377f22e5820e6e524b065360e186f77a8e9625/src/components/MenuItem.js#L32-L81

**Comment by shawnborton** [comment]
Oof, yeah totally agree. One is more for push-to-page rows, and the other is more for displaying content like accounts, users, etc. Anyhoo, save it for another day!

**Comment by shawnborton** [comment]
Ah got it, I can make those perfect squares and then we can just round the edges via the code?

**Comment by grgia** [comment]
Yep, perfect!

**Comment by grgia** [comment]
<img width="368" alt="image" src="https://github.com/Expensify/App/assets/38015950/32144017-4942-4d1c-afe2-b78a2044ed17">

Should we replace the old debit card pattern to match the credit cards?

**Comment by shawnborton** [comment]
Interesting. I kinda think we'd keep them the same shape since that's the bank account section and not the card section? Though now I am kinda doubting the whole idea of making a different shape for assigned cards vs bank accounts...

**Comment by grgia** [comment]
> Interesting. I kinda think we'd keep them the same shape since that's the bank account section and not the card section?

I also think that the shape more represents the "type" and reusing the card shape here makes sense because it's still a "card" just a debit card that you can use as a fund Source?

**Comment by shawnborton** [comment]
It's a debit card but those are always tied to a bank account... so I think you could look at it both ways for sure.

**Comment by grgia** [comment]
Oh true, by use case it's really the same as a bank account. We could also default to the generic bank icon for this case?

**Comment by shawnborton** [comment]
Yeah, that makes sense. So we don't know what bank these come from if they are entered manually right?

**Comment by shawnborton** [comment]
Cool cool. Here are some new icons to try: [newicons.zip](https://github.com/Expensify/App/files/13029329/newicons.zip)

There should be perfect squares for bank accounts, and some updates for the credit card versions. I also included a generic card image to use for when we don't know the card's bank.

**Comment by shawnborton** [comment]
Oops, I messed up - here is a quick update for the generic bank account icon: [generic-bank-account.svg.zip](https://github.com/Expensify/App/files/13029564/generic-bank-account.svg.zip)

**Comment by grgia** [comment]
@shawnborton is the `expensify-background.png` in the bank icons folder intentional?

**Comment by shawnborton** [comment]
I have NO idea, those were already there when I pulled from my App repo. You can ignore?

**Comment by grgia** [comment]
<img width="286" alt="image" src="https://github.com/Expensify/App/assets/38015950/f3096ad4-f452-41f3-b6b8-71e79806581d">
@shawnborton for some reason the Capital One Bank icon is still a circle, any ideas?

**Comment by grgia** [comment]
That worked! Testing the rest

**Comment by grgia** [comment]
![image](https://github.com/Expensify/App/assets/38015950/090c96b2-e723-4fea-bee1-3419a7744cd3)

looks like theres a few more that need updating
- bank of america
- bbt
- charlesswab

**Comment by grgia** [comment]
Before I lose the script to test I'm going to send it here

```

let banks = [
    'generic', 'americanexpress', 'bank of america', 'bbt', 'capital one', 
    'chase', 'charlesschwab', 'citibank', 'citizens bank', 'discover', 
    'fidelity', 'huntington bank', 'navy federal credit union', 'pnc', 
    'regionsbank', 'suntrust', 'tdbank', 'usbank', 'usaa'
];

let key = 1;

banks.forEach((bankName) => {
    let bankData = {
        [key]:  {
    "title": `${bankName} Checking`,
    "description": "Account ending in 5087",
    "methodID": key,
    "key": `bankAccount-${key}`,
    "accountType": "bankAccount",
    "accountData": {
        "accountNumber": "XXXXX5087",
        "additionalData": {
            "acceptTerms": true,
            "addressCity": "San Francisco",
            "addressState": "CA",
            "addressStreet": "88 Kearny St #1600",
            "addressZipCode": "94041",
            "approvedBy": "Automatic",
            "bankName": `${bankName}`,
            "website": "http://toto.com"
        },
        "sharees": [
            "georgia@expensify.com"
        ],
        "state": "OPEN",
        "type": "BUSINESS"
    },
    "isDefault": false
}
    };

    Onyx.merge("bankAccountList", bankData);

    key += 1;
});

```

**Comment by shawnborton** [comment]
Updates: [UpdatedBankIcons.zip](https://github.com/Expensify/App/files/13031391/UpdatedBankIcons.zip)

**Comment by grgia** [comment]
![image](https://github.com/Expensify/App/assets/38015950/6acb1b07-6135-47a6-a0d8-314924c60b1f)
looking good!

**Comment by shawnborton** [comment]
Nice!

**Comment by s77rt** [comment]
**Regression Test Proposal**
Pre-requisites: an account with an imported bank card and an expensify card

1. Go to Settings > Payments
2. Verify that you see the expensify card first and it has a right caret
3. Verify that the company card does not have the right caret and that there's no hover style

**Comment by luacmartins** [comment]
The regression test steps above look good. We also have additional ones as part of the design doc.

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @s77rt for PR review.

**Comment by JmillsExpensify** [comment]
Offer sent. I hope you don't mind, I batch both of those into one Upwork payment for simplicity. We can circle back after the regression period passes.

**Comment by s77rt** [comment]
@JmillsExpensify Accepted! Thank you!

**Comment by JmillsExpensify** [comment]
Awesome, thanks! We'll be ready when the time comes.

**Comment by luacmartins** [comment]
I think we're just pending payment here

**Comment by JmillsExpensify** [comment]
Yes, apologies for the delay! Offer paid via Upwork.
