### ISSUE TITLE
[HOLD for payment 2023-09-27] Update CardUtils.getDomainCards to return company cards

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#27416]
Implement this section - https://docs.google.com/document/d/1vnZSy0ot3Ykz7sRTw2A5Cvuj9_azjkj90ikE_iuwvF8/edit#bookmark=id.5xcpigychr1b

> Unlike Expensify Cards, we want to list each company card in the AssignedCardTile even if they belong to the same domain. To accomplish this, we’ll create a new method`CardUtils.getCompanyCards(cardList)` method that returns an array of company cards and add the result to [combinedPaymentMethods](https://github.com/Expensify/App/blob/69ac668a3463b05734c42b894b8dd16f351f6ce4/src/pages/settings/Wallet/PaymentMethodList.js#L159) 
> 
> function getCompanyCards(cardList) {
> 	return _.filter(cardList, card => card.bank !== CONST.EXPENSIFY_CARD;
> }
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165cd97d6ea555b44</li>
        <li>Upwork Job ID: 1702220470331805697</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
@Ollyws checking in, will you be able to review this one today? TY!

**Comment by strepanier03** [comment]
Back in the office just in time for the payment date. I'll work on this now.

**Comment by strepanier03** [comment]
@Ollyws - I've hired you for the upwork job and will check tomorrow to see if I can pay it out.

**Comment by strepanier03** [comment]
This is paid out, closing. 

Thank you @Ollyws for being part of the community!
