### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Display keyboard shortcuts menu in the RHP

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/App#27449]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Click CMD + J to open the keyboard shortcuts menu 

## Expected Result:

The keyboard shortcuts menu opens in the RHP

<img width="280" alt="image" src="https://github.com/Expensify/App/assets/31225194/ee296780-8b4e-4e88-9cd0-3ec9db6946a0">

## Actual Result:

The keyboard shortcuts menu opens as a modal in the middle of the browser window like this:  

<img width="905" alt="image" src="https://github.com/Expensify/App/assets/31225194/af64cc9a-fa2b-4b5e-ab56-7d85b5121a4e">

## Workaround:
n/a

## Platforms:
- [x] Web
- [x] Desktop App
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018fa7bda44a6beb13</li>
        <li>Upwork Job ID: 1704930075112583168</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26988957</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Tagging in @shawnborton for mockup of what the shortcut menu should look like in the RHP

**Comment by shawnborton** [comment]
I think something simple like this would do the trick, cc @Expensify/design 

<img width="943" alt="image" src="https://github.com/Expensify/App/assets/2319350/1ad13cff-62a4-4a9b-8f5b-508c20487fd3">

**Comment by puneetlath** [comment]
I think it'd be like CMD+K. It opens the page, but doesn't close it.

**Comment by shawnborton** [comment]
I think we can take this off hold and start moving things forward.

**Comment by stephanieelliott** [comment]
Thanks for the mock @shawnborton! Taking this off hold and adding the `External` label

**Comment by shawnborton** [comment]
@eVoloshchak what's the latest here?

**Comment by stephanieelliott** [comment]
@eVoloshchak can you please review [this proposal](https://github.com/Expensify/App/issues/27449#issuecomment-1719649761) so we can push this one forward? We'll plan to pull in another C+ if still no update by tomorrow.

**Comment by eVoloshchak** [comment]
@samh-nl's [proposal](https://github.com/Expensify/App/issues/27449#issuecomment-1719649761) looks good to me!
We also have to make sure to open the new modal when selecting `Settings/About/View keyboard`
<img width="377" alt="image" src="https://github.com/Expensify/App/assets/9059945/d953b3b3-08fb-44f2-8172-52ea62e35f79">
 shortcuts

🎀👀🎀 C+ reviewed!

**Comment by shawnborton** [comment]
In that screenshot above, it looks like the arrow icon is not vertically centered in the row. Any idea what is going on there?

**Comment by eVoloshchak** [comment]
Ooops, my bad @shawnborton. I made the screenshot on my local build with a draft PR, staging and newDot don't have this problem
Replacing the screenshot, apologies for the confusion

**Comment by shawnborton** [comment]
All good, thanks for updating it!

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create a PR @samh-nl. One suggestion that I have would be to remove "show" in "showKeyboardShortcutsPage" and "SHOW_KEYBOARD_SHORTCUTS_PAGE" since i feel like it does not add any value.

**Comment by stephanieelliott** [comment]
Hi @samh-nl are you working on a PR for this issue?

**Comment by stephanieelliott** [comment]
PR is under review

**Comment by eVoloshchak** [comment]
Requested the payment via NewDot

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor:  @samh-nl $500 (pay via Upwork)
 - Contributor+: @eVoloshchak $500 (request via NewDot)
 
 Upwork job is [here](https://www.upwork.com/jobs/~018fa7bda44a6beb13),  [no bonus](https://github.com/Expensify/App/issues/27449#issuecomment-1758626681) is included on final payout

**Comment by JmillsExpensify** [comment]
$500 payment approved for @eVoloshchak based on summary above.

**Comment by stephanieelliott** [comment]
All paid!
