### ISSUE TITLE
[$500]  Chat - Console error shows up when receiving message in #announce room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26850
## Action Performed:
1. Go to staging.new.expensify.com
2. User A and User B stay in #announce room
3. User B sends a message (text or attachment) to User A

## Expected Result:
Console error will not show up on receiver end (User A)

## Actual Result:
Console error shows up on receiver end (User A)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/87cfbe16-c5f3-4632-b28e-8dc86a9f829a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183471120ce59aad5</li>
        <li>Upwork Job ID: 1702337125677191168</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by MuzanEDM** [comment]
May I have your code please?

**Comment by Pujan92** [comment]
Are we passing earlier `displayName` for these rooms as it is only used while making this change [here](https://github.com/Expensify/App/pull/19053/files#diff-c404cfb863b6acdcba717d81db955deb69e4b87d0f3bf353bde01d3f8a7c73d2R113-R120) in this [PR](https://github.com/Expensify/App/pull/19053), if so then we need to pass `displayName` for these reports from backend.

**Comment by puneetlath** [comment]
Thanks @hungvu193
