### ISSUE TITLE
IOU - Tapping on tag , menu picker does not appear and unable to select tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26954
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open expensifail account
3. Open a Workspace chat
4. Tap plus icon near composer
5. Tap request money
6. Enter an amount
7. Tap next
8. Tap "Show more"
9. Tap "Tag"

## Expected Result:
Tapping on tag while creating IOU, user must be able to see tag menu picker and able to select a tag

## Actual Result:
Tapping on tag while creating IOU, user cannot see tag menu picker and unable to select a tag. Instead of showing tag menu picker, the "Select a undefined to add additional organization to your money" message alone displayed when user tap tag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/16f66ed5-4675-498a-aa72-dcd05ba652e9

https://github.com/Expensify/App/assets/78819774/90e176c8-06fe-4a64-b0a1-2411c753caca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
This is not a blocker, the feature is behind a beta and development is ongoing
