### ISSUE TITLE
[$500] Android - Workspace's #announce room is opened twice after scanning shared code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to account A and create a new workspace
2. Invite account B as a workspace member.
3. Open the #announce room and select "Share code."
4. Log in to account B on another Android device.
5. Scan the shared code from step #4 (a few times).
6. Observe that the #announce room is opened twice.

## Expected Result:
The #announce room is opened once.

## Actual Result:
The #announce room is opened twice.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ccc6e9ea-fa1e-41c5-ae3f-34717b034911

https://github.com/Expensify/App/assets/93399543/91f76c1a-ea31-4601-bdd1-28484ae63283

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694534624202269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9ecb205235d0a56</li>
        <li>Upwork Job ID: 1702394544188358656</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
@MitchExpensify, there is a known issue with double assignments (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)), so unassigning you! 👍

**Comment by CortneyOfstad** [comment]
@fedirjh can you confirm if this is the same root case as described above? ^^^ 

TIA!

**Comment by CortneyOfstad** [comment]
Thanks @rayane-djouah and @fedirjh — closing in favor of the other GH!
