### ISSUE TITLE
[HOLD for payment 2023-09-29] Tests in the App repo are not passing when we use onyx version with Batched updates 

### ISSUE THREAD

**Issue by Szymon20000** [Expensify/App#27470]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Apply onyx batching feature and run `rpm run test`

## Expected Result:
All tests should be passing

## Actual Result:
Some of them are failing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Gonna take the Bug label off, but happy to help review this PR.

**Comment by marcaaron** [comment]
I believe we are waiting for a few regressions to be addressed. Margelo is traveling atm so probably this might take a couple days to close out. @tgolen has an approving review on the PR. I'm going to give the code another look now.

**Comment by marcaaron** [comment]
We merged this PR and it's on production so I think there is nothing left to do here besides pay out the C+ who got tagged in for a review / testing.

Gonna add BZ to help with this part now.

**Comment by marcaaron** [comment]
@tjferriss This one is on production already - we just need help paying out @allroundexperts for the help in testing / reviewing.

**Comment by tjferriss** [comment]
@allroundexperts I've sent you an offer via Upworks for payment: https://www.upwork.com/jobs/~01b16f58f5af83ea0b

**Comment by tjferriss** [comment]
Payment summary:

Contributor+ Review @allroundexperts $500

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on BZ summary.
