### ISSUE TITLE
Improve iOS Testflight rollout

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#2748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Testflight rollout should be improved. 

## Actual Result:
Some users have the old version 

## Action Performed:
N/A

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android
 Desktop App
 Mobile Web

**Version Number:**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/117520588-e7822580-af76-11eb-8277-160b3df5721e.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @AndrewGable https://expensify.slack.com/archives/C01GTK53T8Q/p1620321505463100?thread_ts=1620254469.441800&cid=C01GTK53T8Q
> Issue: We need to improve iOS Testflight rollout - feel free to assign me

**Comment by AndrewGable** [comment]
Sounds like there is some working error handling here that can help 👉 https://github.com/fastlane/fastlane/issues/18408#issuecomment-843423247

**Comment by AndrewGable** [comment]
We tested this and the code did not work. I do not have a ton of time to dig into this at the moment so we will revert it and I will try something else soon.

**Comment by AndrewGable** [comment]
I've been following the external issues and I haven't seen any updates.

**Comment by AndrewGable** [comment]
I'll take a look again at Fastlane again, but haven't seen any updates on this one from my notifications.

**Comment by AndrewGable** [comment]
Haven't seen any updates from Fastlane, we might want to try to see if there are any alternative solutions to this one.

**Comment by AndrewGable** [comment]
I think there are three scenarios at play here:
1. We have a new version that needs to be reviewed by Apple
2. We have an existing version that does not need to be reviewed by Apple and **do not** have a build in review
3. We have an existing version that does not need to be reviewed by Apple and **do** have a build in review

The `reject_build_waiting_for_review` is supposed to basically take the version we submitted for review, delete it, and replace it with the latest version for review. However, it looks like Apple removed the API command to delete the beta version that was in review. 

If we remove the `reject_build_waiting_for_review`, then I believe in case three we might see an error thrown by Fastlane. My PR above is to confirm that we do in fact get an error thrown in this case.

My suggestion if we do see an error thrown is to catch the error, then just do not submit the build for external testers. Once we have another build and we do not have a build in review, we will send that version to testers. This is not a perfect solution as beta testers will skip some versions, but they should get more versions then they do today.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188400020) to staging by @AndrewGable in version: 1.0.90-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1192222770) to production by @roryabraham in version: 1.0.91-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅
