### ISSUE TITLE
OpenReport is called a lot of times 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27486]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Be on the desktop app with an open report
- go to another app (slack, chrome)
- Go back to New Expensify

## Expected Result:
1 request should be made to OpenReport

## Actual Result:
In my case, it's doing scheduling 26 OpenReport requests. You can check this by looking in the Onyx data for property `networkRequestQueue`

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** 1.3.69-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

[LOG.txt](https://github.com/Expensify/App/files/12615334/Untitled.txt)

![image - 2023-09-14T233406 572](https://github.com/Expensify/App/assets/43995119/3189e56d-83ca-45cd-b5c2-12710da2652d)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas & @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694581967039559 
https://expensify.slack.com/archives/C049HHMV9SM/p1694733539747769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
This is gonna be solved by https://github.com/Expensify/App/pull/27270
