### ISSUE TITLE
[$500] [Awaiting Payment] Dev - Error shows green dot instead of red

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any screen that has protected pdf file
2. Click on it, enter wrong password and press Enter.
3. Notice the error has green dot.

## Expected Result:
Error should have red dot.

## Actual Result:
 Error shows green dot instead of red
 
## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-1 
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/b402e255-2c04-4e9e-bb8a-f0811e2b5dfa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694747013680109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c7dd5f52f199548</li>
        <li>Upwork Job ID: 1703625851002867712</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by grgia** [comment]
@eVoloshchak sorry for the ping, this issue has been completed and I need to track payment. Unassigning

**Comment by grgia** [comment]
@laurenreidexpensify  I fixed this in 
https://github.com/Expensify/App/pull/27483
C+ review payment is handled [by this issue](https://github.com/Expensify/App/issues/27487). So NO duplicate C+ payemnt required here.
For this issue, we only need to handle the reporting payment to @hungvu193

**Comment by laurenreidexpensify** [comment]
Offer sent to @hungvu193 in Upwork

**Comment by laurenreidexpensify** [comment]
Payment Issued - $50 to @hungvu193 in Upwork. 

Closing
