### ISSUE TITLE
[HOLD for payment 2023-09-27] [$1000] Payment GH for PR review #25564

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27509]
https://github.com/Expensify/App/pull/25564
For @situchan 

Setting at $1000 because this PR started before we announced the price updates
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2340042e264da70</li>
        <li>Upwork Job ID: 1702626882504908800</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Will have to be manually hired

**Comment by strepanier03** [comment]
Got it, thanks for the heads up.

**Comment by strepanier03** [comment]
We're still waiting on the deploy to prod so the timer hasn't started yet. I'll continue following along and update accordingly.

**Comment by strepanier03** [comment]
@situchan - I've hired you for the Upwork job, I'll check it tomorrow.

**Comment by strepanier03** [comment]
Hmmm, normally I don't see the checklist in this one-off payment GHs. 

@situchan does it make sense for you to do the checklist here? If not let me know and I'll hide it but if it's expected for this feel free to do it and I'll take the reg test step as needed.

**Comment by situchan** [comment]
@thienlnam do we have new regression test step of new simplified global create menu in Testrail?

**Comment by thienlnam** [comment]
I've already created an issue to get them added https://github.com/Expensify/Expensify/issues/318720

**Comment by situchan** [comment]
Thanks.
@strepanier03 we don't need another regression test here

**Comment by strepanier03** [comment]
All right, this has been paid and the contract ended. 

Thank you @situchan for being a member of this community!
