### ISSUE TITLE
[$500] Desktop - Unread count is incorrect when joining a thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Clicked on a thread made by other users that already had comments
2. Didn't add any comment
3. Left the thread
4. The thread disappeared from LHN

## Expected Result:
New messages inside those threads should not be counted on my unread indications

## Actual Result:
New messages on the threads that I can't see on my LHN are counting towards the unread counter on the app icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.67-1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n./a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694447504126939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a81e245f41f24d05</li>
        <li>Upwork Job ID: 1703973226245242880</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26746291</li>
<li>dukenv0307 | Contributor | 26746293</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This is super annoying and front-end fixable so I'm going to make it external

**Comment by roryabraham** [comment]
At a high level, I think we maybe just need to call [`Report.leaveRoom`](https://github.com/Expensify/App/blob/fa514e4364c00a0df91ced35295f70164ec9fbc4/src/libs/actions/Report.js#L1782-L1827) when you navigate away from a thread that you have not commented on

**Comment by roryabraham** [comment]
I think we should address those edge cases in the back-end – maybe in [FixAccount](https://github.com/Expensify/Web-Expensify/blob/37e8c52e000e74764c428d70b9ed19242548a96a/lib/User/FixAccount.php), which I think still runs as part of `OpenApp`?

**Comment by garrettmknight** [comment]
Bumped the PR to investigate the checks that weren't successful.

**Comment by garrettmknight** [comment]
Since plenty of work was done here and we got pretty deep into the PR I think this counts for pay.

**Summary of payments on this issue:**
- Urgency bonus: No
- Contributor: @dukenv0307 $500 paid via Upwork
- Reviewer: @fedirjh $500

**Comment by garrettmknight** [comment]
@fedirjh accept the new offer and I'll pay out.

**Comment by garrettmknight** [comment]
All paid up.
