### ISSUE TITLE
[HOLD for payment 2023-09-27] Web - search field or new group field remain focused after CTRL + K,  CTRL + J or CTRL + SHIFT + K, CTRL + J

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click CTRL + K or CTRL + SHIFT + K
3. Click CTRL + J
4. Observe the search or new group field which is focused

## Expected Result:
The search or new group field should not be focused since the keyboard shortcut modal is over the search RHN

## Actual Result:
The search or new group field is focused and we can type when the keyboard shortcut is over the search or new group RHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5d79e86b-af7b-46f1-bd67-b305bdc06dce

https://github.com/Expensify/App/assets/93399543/9b3b8418-d7ab-43b7-96ff-251a3d1641de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694731952884149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkuoch** [comment]
Probably not a deploy blocker, but definitely a regression - trying to find the culprit

**Comment by situchan** [comment]
@nkuoch I confirmed that the regression came from https://github.com/Expensify/App/pull/24316. Shall we revert this?

**Comment by nkuoch** [comment]
Yes, as the original fix isn't fixing anything major, let's revert and ask them to redo with the new bug in mind

**Comment by situchan** [comment]
I can raise PR if you want.

**Comment by situchan** [comment]
I agree to revert that PR. It also fixes another deploy blocker - https://github.com/Expensify/App/issues/27519.

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/App/pull/27559) is ready

**Comment by thienlnam** [comment]
Merged the revert

**Comment by misgana96** [comment]
@thienlnam Am I eligible for a reporter bonus?

**Comment by thienlnam** [comment]
Oh yeah, will reopen

**Comment by nkuoch** [comment]
@stephanieelliott

**Comment by stephanieelliott** [comment]
@misgana96 I extended the offer to you on Upwork, please accept when you get a chance! https://www.upwork.com/jobs/~01b782e555a9fce472

**Comment by misgana96** [comment]
Offer accepted. Thank you

**Comment by stephanieelliott** [comment]
All paid!

**Comment by misgana96** [comment]
Received. Thank you
