### ISSUE TITLE
[$500] Dev: When pressing the Enter key, rather than choosing the searched country, the user is redirected back to the Personal Details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Profile > Personal details > Home address.
2. If the home address has not been saved previously, save it first.
3. Click on the country field and search for a country, then press the Enter key.

## Expected Result:
Upon pressing the Enter key, the selected country should be chosen without returning to the Personal Details page.

## Actual Result:
 When pressing the Enter key, rather than choosing the searched country, the user is redirected back to the Personal Details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b74304db-1e64-491d-a14f-54a99389d804

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694723594610239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01905b55db4716395d</li>
        <li>Upwork Job ID: 1702647270940528640</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by zukilover** [comment]
This seems to be related to https://github.com/Expensify/App/issues/26345

**Comment by adelekennedy** [comment]
Should we close this one and combine the two?

**Comment by adelekennedy** [comment]
@eVoloshchak what do you think about closing this and combining with https://github.com/Expensify/App/issues/26345

**Comment by eVoloshchak** [comment]
@adelekennedy, yup, I agree, let's close this one
