### ISSUE TITLE
[$500] Bank account - Server side error on bank account displays red dot on all workspaces

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. To trigger server side error, open settings->workspaces->any workspace->bank account->connect manually->fill in step 1, step 2 details, in step 3, select first selectable date (23-08-1873 for current example) and click save
3. Exit the RHN and open settings again
4. Open workspaces and observe that it shows red dot to all workspaces instead of only one in which we had triggered the error

## Expected Result:
App should only display red dot next to workspace in which we have triggered the server side error

## Actual Result:
App displays red dot next to all the workspaces even though error was only triggered in one workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7af00881-8c84-4a18-babb-89026d70c38d

![Screen Shot 2023-09-14 at 5 34 48 PM](https://github.com/Expensify/App/assets/115492554/296908f6-58cb-4fab-9b1a-d2e5eccbbfef)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692808524671409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd74490d817c4df4</li>
        <li>Upwork Job ID: 1702632880312627200</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
I believe this is expected because when connecting a bank account in one workspace you can pickup where you left off in a another. So experiencing an error connecting in one workspace seems reasonable to show across all workspaces - If you went to connect in any of them you would see the error
