### ISSUE TITLE
[HOLD for payment 2023-10-05] [Payment due Oct 2 2023 $500] Search - The avatars order are different in LHN and RHN.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open search RHN.
2. Observe the avatar order in LHN and RHN.

## Expected Result:
The avatars order should not be different.

## Actual Result:
 The avatars order are different.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![2023-08-23 191124](https://github.com/Expensify/App/assets/115492554/d11eaf2c-4278-461f-8496-3c001a07976a)

https://github.com/Expensify/App/assets/115492554/a71712a4-f78c-4f60-bf13-b23bbdab676c

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @oleksandr-pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692809283563059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2234c9135bc93ec</li>
        <li>Upwork Job ID: 1702693333674766336</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 26788701</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
<img width="1690" alt="Screenshot 2023-09-15 at 8 22 47 PM" src="https://github.com/Expensify/App/assets/59088937/33491958-0039-4620-a345-ab4f2bee75b7">

Not able to repro.

**Comment by mountiny** [comment]
@michaelhaxhiu will create it for you once he is at the office.

**Comment by michaelhaxhiu** [comment]
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps:**
- Wait till 7 days after PR is merged to pay
- Then, payout the following amounts (assuming no regressions):

> Payment amounts:
> 
> Job: https://www.upwork.com/jobs/~01f2234c9135bc93ec
> - **Bug reporter** $250 @oleksandr-pantsyr
> - **Contributor:** $750 @hoangzinh 
> - **C+:** $750 @allroundexperts (should request payment via newDot)
>

**Comment by sophiepintoraetz** [comment]
@michaelhaxhiu was incorrect with his bug payment - it's $50 for reports, not $250.

**Comment by sophiepintoraetz** [comment]
@allroundexperts please request $750 once the BZ checklist is completed!
@oleksandr-pantsyr - an offer should be with you now!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on BZ summary.

**Comment by JmillsExpensify** [comment]
Re-opening for regression test.

**Comment by mountiny** [comment]
https://github.com/Expensify/Expensify/issues/326434
