### ISSUE TITLE
[$500] Setting - Profile - The contact method cannot be added again once it has been deleted before

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27530]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Setting => Profile => Contact method
2. New contact method => Input an email => Add
3. Copy the URL and open a new tab
4. Back tab 1 => click contact just created => remove
5. On tab 2 Click New contact method => Input again above account
6. Click add, Observe that cannot add

## Expected Result:
Can add a contact method again after deleting it

## Actual Result:
Can't add a contact method again after deleting it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d31e42ac-8315-45a8-aa33-08cb2a81a8b7

https://github.com/Expensify/App/assets/115492554/ff46e6ed-c0a5-4e75-916a-9b41ce316e7b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692797201580289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123f2dca6242bcda8</li>
        <li>Upwork Job ID: 1702686138263207936</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
>Problems arising from using two tabs are a won't-fix I believe? https://expensify.slack.com/archives/C049HHMV9SM/p1694086353371219?thread_ts=1693582269.464579&cid=C049HHMV9SM

Yes, agreed. Closing this one out
