### ISSUE TITLE
[$500] [Distance] - No error shows up for maximum distance limitation offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Click on FAB > Request money > Distance tab
2. Click on the start field and insert "Ethiopia" as a starting point
3. Click on The finish field and insert "USA" as the finishing point
4. Observe the Error
5. Disconnect the device from the internet
6. Do step 1 - 3 again
7. Go online

## Expected Result:
The error should show up again as the device connects to the internet

## Actual Result:
The error no longer shows up and user can proceed to the next step

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fd7e4824-df8c-47e0-a3d8-840fee83db7f

https://github.com/Expensify/App/assets/93399543/613de9ff-1c7d-41d1-887d-407e5ff8b89b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694678857397389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d5b74636b773cdd</li>
        <li>Upwork Job ID: 1702687479586590720</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Nice! In that case, let's close this one up!
