### ISSUE TITLE
[$500] Assign task - Marking the Task as Complete or incomplete does not focus the composer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27541]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any task report page
2. Click "Mark as done". Notice the composer is not focused
3. Go to the three dots and click on Mark as incomplete. Notice the composer is not focused

## Expected Result:
Marking the Task as Complete or incomplete focuses the composer

## Actual Result:
Marking the Task as Complete or incomplete does not focus the composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-5

**Reproducible in staging?:** Y

**Reproducible in production?:**Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/29518a0e-8fd4-4c70-8024-33374593f8bf

https://github.com/Expensify/App/assets/115492554/9552b16d-23b1-42d2-8b0d-5a7385738da7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694057465609589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dda7cab075cd4ea4</li>
        <li>Upwork Job ID: 1702707529787387904</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by poonam286** [comment]
Hi i want help with this

**Comment by poonam286** [comment]
Contributor details
Your Expensify account email: poonammsute@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c0d53d695396e11c

**Comment by mananjadhav** [comment]
> on the composer when Task is reopened [here](https://github.com/Expensify/App/issues/27541).

@neonbhai I didn't understand what you mean `here`, it links to the current issue itself. Can you please elaborate?

**Comment by strepanier03** [comment]
I am able to recreate this but I raised [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695073762131539) to discuss expected behavior. 

I get that we're not focusing the composer but why would we expect the composer needs to be focused after marking a task complete or incomplete?

**Comment by strepanier03** [comment]
@neonbhai - Please join the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695073762131539) if you'd like to help move this forward. Right now the plan is to close this GH as a feature request.

**Comment by strepanier03** [comment]
I'll reopen if we decide to make a change.
