### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web - App does not display tooltip on 3 dots of long IOU and ADMIN title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on request money
3. Select any currency and amount and click next
4. Select any user and click next
5. Add small description and complete the request money process
6. Click on `request` money IOU and change the description to a long text > save
8. In LHN, hover on 3 dots in `Request title` and observe that no popup is displayed
9. Hover over the 3 dots in the `chat title` and observe that the popup displayed

## Expected Result:
App should display tooltip on hover of 3 dots on IOU and ADMIN ROOM

## Actual Result:
App does not display tooltip on 3 dots of long title request money report in LHN

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f5fe1c4a-0653-47c3-94aa-6ad86407e568

https://github.com/Expensify/App/assets/93399543/ff4cf0b5-a8e4-4b7f-93df-93d3f840aa2c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694692235395759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0a0bf2479edc5c8</li>
        <li>Upwork Job ID: 1702724346197262336</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26976898</li>
<li>bernhardoj | Contributor | 26976901</li>
<li>dhanashree-sawant | Reporter | 26976904</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
Trying to test this... I'm a little confused by the steps in the OP... working on this

**Comment by Christinadobrzyn** [comment]
Sorry I haven't had time to continue testing this... I'll get to it as soon as possible.

**Comment by Christinadobrzyn** [comment]
Finally got to reproduce this - the missing tooltip is affecting the IOU and Admin Titles in LHN. I think this can be external. 

@abdulrahuman5196 can you check out this [proposal](https://github.com/Expensify/App/issues/27545#issuecomment-1722210867) when you have a moment?

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@Christinadobrzyn I don't understand the issue on first place? I don't see tooltip on any IOU LHN. Do we need to show tooltip? If so what content in tooltip?


Can we add clear steps in OP?

**Comment by Christinadobrzyn** [comment]
Hi! I'm not sure the technical term but it's that popup that shows when you hover over the three dots. 

So the difference between this tooltip showing on the Request

![image](https://github.com/Expensify/App/assets/51066321/07685efe-d539-4f95-99aa-14a04d903b25)

And the tooltip not showing on the chat: 

![image](https://github.com/Expensify/App/assets/51066321/9c05cccd-a63b-4b8c-9871-2db83ce7e6d8)

I updated the OP to hopefully outline this better. Here's a video. 

![2023-09-28_17-18-29 (4)](https://github.com/Expensify/App/assets/51066321/930f3832-59c9-4c63-a3ed-b46e204f67c6)

Maybe this is a feature request? What to you think, should we fix this?

**Comment by Christinadobrzyn** [comment]
Thanks for clarifying @bernhardoj! 

@abdulrahuman5196 let me know how this [proposal](https://github.com/Expensify/App/issues/27545#issuecomment-1722210867) looks when you have a chance!

**Comment by abdulrahuman5196** [comment]
Re-checking the issue again.

**Comment by abdulrahuman5196** [comment]
> the tooltip is on the LHN title (chat name) ellipsis.
> 
> You will only see the tooltip if the LHN title is truncated. The issue in this GH is, when the LHN title is updated (by updating the IOU description) from short to a long one until it is truncated, the tooltip won't show even if we hover over the ellipsis.

Thanks for the clarification. Got the issue.

**Comment by abdulrahuman5196** [comment]
@Christinadobrzyn Just to note: Kindly update the OP expectation as well based on the clarification provided for future reference

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/27545#issuecomment-1722210867 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20953/files

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/20953/files#r1352836052

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Not beneficial for the minor bug.

**Comment by Christinadobrzyn** [comment]
Payouts due:

Issue Reporter: $50 @dhanashree-sawant (paid in Upwork)
Contributor: $500 + $250 bonus @bernhardoj  (Paid in Upwork)
Contributor+: $500 + $250 bonus @abdulrahuman5196 (Paid in Upwork)

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/27545#issuecomment-1743018266

Upwork job is [here](https://www.upwork.com/jobs/~01f0a0bf2479edc5c8).

Closing this out - let me know if you need anything!
