### ISSUE TITLE
[$500] Web - App crash on open thread created from welcome message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27548]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, create a workspace if not created
2. Click on FAB icon and select new room option
3. Enter name and create public room
4. Go to #room and click on header
5. Go to settings and set welcome message
6. Copy the public room link
7. Open that public room in userB
8. From userB, create thread from welcome message
9. From userA, go to that thread

## Expected Result:
App should not crash

## Actual Result:
App crash on open thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/63711e22-aea7-407c-9213-a7e8d8b9fa17

https://github.com/Expensify/App/assets/93399543/60de0340-2501-413e-b0cf-01cb0cd58b36

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1694698298613389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b872165ef2e606b</li>
        <li>Upwork Job ID: 1702727863819317248</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by anmurali** [comment]
Cannot reproduce.

**Comment by gadhiyamanan** [comment]
issue is still reproducible  
cc: @anmurali @thesahindia 

https://github.com/Expensify/App/assets/54790231/5739af4e-2d04-47c5-a49f-825f63bec901

**Comment by lanitochka17** [comment]
Issue is still reproducible on build 1.3.83-1

https://github.com/Expensify/App/assets/78819774/d1889032-6a6a-4f32-b979-3434b038e7d2

**Comment by anmurali** [comment]
@applausebot - can someone try to reproduce this? I still cannot.

**Comment by gadhiyamanan** [comment]
@anmurali still able to reproduce

https://github.com/Expensify/App/assets/54790231/cbb8d3dc-f2c4-4d4a-af94-ee21b8b77742

**Comment by gadhiyamanan** [comment]
Bump @anmurali
