### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Android - Search page is not deeplinking to the mobile app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Copy the url to our search page.
2. Paste it to the note, click on it.
3. Notice that it opens browser instead of the mobile app.

## Expected Result:
It should open search page on mobile app

## Actual Result:
 It opens browser instead of the mobile app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/50ac3f29-8dfd-484f-bc26-c3c51d941ae1

https://github.com/Expensify/App/assets/115492554/0a50da6d-36f4-4c6e-8fa6-74e082e85135

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692068644809499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01499b6f14da6e86d6</li>
        <li>Upwork Job ID: 1702757056609751040</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26916276</li>
<li>hungvu193 | Contributor | 26916277</li>
<li>hungvu193 | Reporter | 26916278</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
## Proposal from @hungvu193
### Please re-state the problem that we are trying to solve in this issue.
URL to search page is not deep linked to native app
### What is the root cause of that problem?
Path prefix for the Search page is not added to the deeplinking config in our `apple-app-site-association` and `AndroidManifest` file which caused the issue.
### What changes do you think we should make in order to solve the problem?
We should add this config below to our `apple-app-site-association` components section [here](https://github.com/Expensify/App/blob/42757411e9d715ca77456242425677e47b522873/.well-known/apple-app-site-association#L66):
```javascript
{"/": "/search/*",  "comment": "Search"} // Or just /search is enough, because we don't have params for search page.
```
And also update our `AndroidManifest` in [here](https://github.com/Expensify/App/blob/42757411e9d715ca77456242425677e47b522873/android/app/src/main/AndroidManifest.xml#L70) and [here](https://github.com/Expensify/App/blob/42757411e9d715ca77456242425677e47b522873/android/app/src/main/AndroidManifest.xml#L85):
```javascript
  <data android:scheme="https" android:host="[new.expensify.com](http://new.expensify.com/)" android:pathPrefix="/search"/>
```
```javascript
 <data android:scheme="https" android:host="[staging.new.expensify.com](http://staging.new.expensify.com/)" android:pathPrefix="/search"/>
```
We can also setup this for other routes if we want (ie: /workspace)
### What alternative solutions did you explore? (Optional)
N/A
<details><summary>Result</summary>
https://github.com/Expensify/App/assets/16502320/eaf5a607-1e29-4386-90fa-1382faaa244d
</details>

**Comment by abekkala** [comment]
@Ollyws have you had a moment to review the proposal?

**Comment by abekkala** [comment]
@Ollyws a bump here: have you reviewed the proposal submitted by Hungvu193 above?

**Comment by Beamanator** [comment]
I like the proposal to fix the issue, can we make sure there's no other similar issues currently be worked on that can include this fix? And also are we sure this is the only page that's not deep linking that we want to deep link?

**Comment by abekkala** [comment]
### PAYMENTS FOR OCT 10

- @hungvu193 (Reporter) [$50]
- @hungvu193 (Contributor) [$500] + [$250 bonus, pending no regression]
- @Ollyws (Reviewer) [$500] + [$250 bonus, pending no regression] - please complete the checklist above

**Comment by abekkala** [comment]
@hungvu193 I've sent your payments through [a total of $800] and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
@Ollyws payment sent [$750] and contract ended - thank you! 🎉
