### ISSUE TITLE
[Wave 6: Categories] Category/Tag Selector Show up in DM Money Requests

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#27556]
## Action Performed:
1. Create a new account
2. Create a money request from another user
3. On the confirmation step, observe that the category and tag selectors show for the money request:
https://github.com/Expensify/App/assets/4741899/16a59421-b77a-42da-a35b-0a0e49d25822

## Expected Result:
- The Category and Tag selectors should not show for a DM Money Request because that chat report does not belong to a policy (They belong to the policy `_FAKE_`)

## Actual Result:
- The Category/Tag selector is visible for the Money Request on the confirmation page.

## Workaround:
- This feature is under a beta so real-life users can't see it yet.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** N/A
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @rezkiy37 
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1694793499639819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f9ca0cd0d1a9a22</li>
        <li>Upwork Job ID: 1702759634044727296</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26699580</li>
</ul></li>
    </ul>
</details>

**Comment by rezkiy37** [comment]
Hello, I am Mykhailo from Callstack. I would like to work on this issue.

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
@yuwenmemon, I am going to fix it in a scope of https://github.com/Expensify/App/issues/24464 (https://github.com/Expensify/App/pull/27459). Because I need a few same new helpers there. Are we okay with it?

**Comment by yuwenmemon** [comment]
Yep sounds good to me!

**Comment by puneetlath** [comment]
@situchan I see you assigned to the issue, but it doesn't look like you were involved in the PR review, is that correct?

**Comment by situchan** [comment]
> @situchan I see you assigned to the issue, but it doesn't look like you were involved in the PR review, is that correct?

correct. I wasn't aware that linked PR was in progress.
Seems like https://github.com/Expensify/App/pull/27459 wasn't reviewed by any C+.



@rezkiy37 in the future, please link issues like this so that automation would work correctly

Wrong:
```
$ https://github.com/Expensify/App/issues/24464, https://github.com/Expensify/App/issues/27556
```

Correct:
```
$ https://github.com/Expensify/App/issues/24464
$ https://github.com/Expensify/App/issues/27556
```

**Comment by puneetlath** [comment]
Ok, thanks for confirming @situchan. We're good to close this out in that case once the PR is deployed to production.

**Comment by rezkiy37** [comment]
> > @situchan I see you assigned to the issue, but it doesn't look like you were involved in the PR review, is that correct?
> 
> correct. I wasn't aware that linked PR was in progress. Seems like #27459 wasn't reviewed by any C+.
> 
> @rezkiy37 in the future, please link issues like this so that automation would work correctly
> 
> Wrong:
> 
> ```
> $ https://github.com/Expensify/App/issues/24464, https://github.com/Expensify/App/issues/27556
> ```
> 
> Correct:
> 
> ```
> $ https://github.com/Expensify/App/issues/24464
> $ https://github.com/Expensify/App/issues/27556
> ```

Sorry, my bad 😅

**Comment by rezkiy37** [comment]
The issue (https://github.com/Expensify/App/issues/24464), in which scope I fixed the bug, already closed.

**Comment by puneetlath** [comment]
@rezkiy37 just to clarify, you're saying this bug has been fixed and we can close this issue, is that correct?

**Comment by rezkiy37** [comment]
> @rezkiy37 just to clarify, you're saying this bug has been fixed and we can close this issue, is that correct?

Yes, it is correct.

**Comment by puneetlath** [comment]
Great!
