### ISSUE TITLE
[$500] Chat - Popover from emoji reaction can be move when cliking a right-click around the emoji reaction

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any chat from LHN
3. Send a message(it can any text)
4. React the message
5. Open the popover from the emoji reaction by clicking right-click
6. Start clicking the right-click when the popover is open around the reaction

## Expected Result:
The popover should be in a fixed position

## Actual Result:
The popover from the emoji reaction can be moved by clicking a right-click

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.69-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/caf0b443-20df-404a-af0d-115388ccff54

https://github.com/Expensify/App/assets/115492554/82c07edb-f967-4420-bfb9-6bc99399d0f7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694519035033399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6114b6457f74fa5</li>
        <li>Upwork Job ID: 1702754098502221824</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by s77rt** [comment]
This seems a pretty minor concern. I have asked in [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1694824288428159) if we should do anything here.

**Comment by trjExpensify** [comment]
Commented in the thread as well. I find the tooltip covering the popover to be more annoying: 

<img width="1114" alt="image" src="https://github.com/Expensify/App/assets/16232057/77b4fd51-4e8a-4a4b-99d0-56b10a5dbde1">

**Comment by trjExpensify** [comment]
Alrighty, we're going to close this one. For the bug I could see here, we have an issue for that already: https://github.com/Expensify/App/issues/24296
