### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Android - Inconsistent font weight between QR Share subtitle between Android and other platform

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings => Profile => Share Code
2. Observe the email (subtitle) between android and other platform.

## Expected Result:
Font weight of subtitle should be consistent between platform

## Actual Result:
Inconsistent font weight between QRShare subtitle between Android and other platform

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bc49949a-67cf-4350-a7d5-4128bc3b60ae

![Screenshot_20230915_164404_New Expensify](https://github.com/Expensify/App/assets/93399543/4fcceb1e-ab9b-42cb-9b40-db4a6ec915a3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694751464693409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142c4ec420bc47997</li>
        <li>Upwork Job ID: 1702786767079575552</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26985823</li>
<li>hungvu193 | Reporter | 26985825</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We're using the `EXP_NEUE_BOLD` but we didn't define the fontWeight for it which caused the issue.
https://github.com/Expensify/App/blob/e48121cb35052e958928c002d2b3a7d78a930ff3/src/components/QRShare/index.js#L79
### What changes do you think we should make in order to solve the problem?
Solution 1:
 We should add `fontWeight: fontWeightBold` to our subTitle style [here](https://github.com/Expensify/App/blob/e48121cb35052e958928c002d2b3a7d78a930ff3/src/components/QRShare/index.js#L82)

Solution 2:
Incase we dont want it bold,  we should remove  `family="EXP_NEUE_BOLD` or replace it with other regular fontFamily like `EXP_NEUE` to make it consistent with other platforms.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by fabrianibrahim** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent font weight between QRShare subtitle between Android and other platform

### What is the root cause of that problem?
Different font is used in ios
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/styles/fontFamily/bold/index.ios.js#L1-L3

Missing font weight in the component style
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/Text.js#L51-L57

### What changes do you think we should make in order to solve the problem?
1. Replace `const bold = 'ExpensifyNeue-Regular';` with `const bold = 'ExpensifyNeue-Bold';` in `src/styles/fontFamily/bold/index.ios.js#L1`
2. Add `fontWeight` conditions in the `Text componentStyle`:
```
const componentStyle = {
      color,
      fontSize,
      textAlign,
      fontFamily: fontFamily[family],
      fontWeight: family === 'EXP_NEUE_BOLD' ? fontWeightBold : 400,
      ...mergedStyles,
  };
```

**Comment by mananjadhav** [comment]
I am not sure if we should be changing the font weight across iOS. @shawnborton do you think we need that?

Otherwise I think @hungvu193's proposal is good. @shawnborton it would also be great if you can confirm whether we need bold in the QRShare.

🎀 👀 🎀 C+ reviewed.

**Comment by shawnborton** [comment]
I think the proposal is flipped, we don't want this to show in bold, we want this to be font weight 400 everywhere. Any idea why it's not that way on Android?

**Comment by fabrianibrahim** [comment]
> I think the proposal is flipped, we don't want this to show in bold, we want this to be font weight 400 everywhere. Any idea why it's not that way on Android?

currently it is using font family `EXP_NEUE_BOLD`. replacing it to `EXP_NEUE` will fix this issue

**Comment by fabrianibrahim** [comment]
Contributor details
Your Expensify account email: fabrian.ibrahim@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01311d57940876ef13

**Comment by stephanieelliott** [comment]
Hey @jasperhuangg we're looking for your input on [this proposal](https://github.com/Expensify/App/issues/27566#issuecomment-1721851009), can you take a look?

**Comment by stephanieelliott** [comment]
Hey @jasperhuangg bump on this! 

> Hey @jasperhuangg we're looking for your input on https://github.com/Expensify/App/issues/27566#issuecomment-1721851009, can you take a look?

**Comment by mananjadhav** [comment]
@jasperhuangg Can you check @shawnborton's comments and then @hungvu193's comment [here](https://github.com/Expensify/App/issues/27566#issuecomment-1722761224)?

**Comment by jasperhuangg** [comment]
Hey! Apologies for the delay here! I like @hungvu193's proposal. It seems like the most straightforward way to fix things, thanks!

**Comment by mananjadhav** [comment]
@stephanieelliott Can you please post the payout summary on this one?

**Comment by mananjadhav** [comment]
> > Based on my calculations, the pull request did not get merged within 3 working days of assignment. Please, check out my computations here:
> > 
> > * when @hungvu193 got assigned: 2023-10-02 18:46:38 Z
> > * when the PR got merged: 2023-10-11 01:47:15 UTC
> > * days elapsed: 6
> > 
> > On to the next one 🚀
> 
> Just a note. I think this issue will be eligible for urgency bonus, it got approved within 3 days and only needed to wait for final review after that.

I also agree with @hungvu193. This should be eligible for urgency bonus.

**Comment by stephanieelliott** [comment]
Thanks @mananjadhav - I agree the bonus should apply here. 

**Summarizing payment on this issue:** 

 - Issue reporter: @hungvu193 $50, paid via Upwork 
 - Contributor: @hungvu193, paid via Upwork  $750, request via Upwork 
 - Contributor+: @mananjadhav $750, request via NewDot 
 
 Upwork job is [here](https://www.upwork.com/ab/applicants/1702786767079575552/hired), 50% bonus is included on final payout

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mananjadhav based on summary above.
