### ISSUE TITLE
DEV: console error on transaction thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. click on + icon and select request money option
3. enter amount and click on Next button
4. request money
5. go to transaction thread
## Expected Result: 
should not show console error
## Actual Result: 
console error appears (Failed prop type: The prop `policy` is marked as required in `MoneyRequestHeader`, but its value is `undefined`.)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6270b154-6456-4bb1-965c-5dbcfe8f1f22

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693292429308959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
I think this issue reported first in slack

**Comment by kevinksullivan** [comment]
>I think this issue reported first in slack

@gadhiyamanan can you elaborate on what you mean?

**Comment by gadhiyamanan** [comment]
@kevinksullivan i mean i am eligible for reporting bonus because it was reported by me on slack before the other issue is created

**Comment by kevinksullivan** [comment]
I'm confused, you are set as the reporter in the original issue, so you'd get paid for this. Is there a separate problem?

**Comment by gadhiyamanan** [comment]
i am not added as reporter for the https://github.com/Expensify/App/issues/26991

**Comment by kevinksullivan** [comment]
Ok, so you're requesting the $50 reporting bonus?

**Comment by gadhiyamanan** [comment]
Correct

**Comment by kevinksullivan** [comment]
offer sent @gadhiyamanan lmk when you accept

https://www.upwork.com/jobs/~01ed7205b0f7e1362e

**Comment by gadhiyamanan** [comment]
This is eligible for $250 because it was reported in slack before 30 August
![Screenshot_20231004_221225_Slack.jpg](https://github.com/Expensify/App/assets/54790231/ef213a0f-74f7-4044-86f6-354cadd11701)

**Comment by gadhiyamanan** [comment]
@kevinksullivan offer accepted, thanks

**Comment by kevinksullivan** [comment]
all set
