### ISSUE TITLE
[$500] Web -  Background color from message is removed on second time right click for popup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Right click on message opens right click popup, keeps the message in focus even on hovering on any other message
4. Right click again on same message, closes and again opens right click popup, removes focus from message when we hover on any other message

## Expected Result:
App should maintain background on message to which we have opened right click popup even when we hover on other messages

## Actual Result:
 Background color from message is removed on second time right click for popup

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/92db96be-bc1c-4c6b-bac6-6f7f770899aa

https://github.com/Expensify/App/assets/93399543/8f2c96cb-7bbd-4d3e-b1d6-51c54d4580fb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694703212676929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170c5346215bbf83d</li>
        <li>Upwork Job ID: 1703064872242483200</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @dhanashree-sawant
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694703212676929

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We are solving the problem of app removing background color from message when we again right click on same message to open popover
### What is the root cause of that problem?
Currently we use `IsContextMenuActive` boolean value in `ReportActionItem.js` to check if any action was done on current message and it is used to also set background color for the message. We set the boolean value as true first in `showPopover` and then reset the value to false for previous message using `toggleContextMenuFromActiveReportAction` in `showContextMenu` function call in same `showPopover` function.
Because of this, if we right click on same message, we set the `IsContextMenuActive` true for that message but since previous message too was same, we set `IsContextMenuActive` false again for it causing the issue.
### What changes do you think we should make in order to solve the problem?
We will need to change the position of `setIsContextMenuActive` function to the end of `showPopover`, it will ensure that previous selected message `IsContextMenuActive` is set to false and current selected message `IsContextMenuActive` is set to true later on avoiding the current issue.
We can do that by removing this line from [here](https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/pages/home/report/ReportActionItem.js#L238)
```
setIsContextMenuActive(true);
```
and adding it below [this](https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/pages/home/report/ReportActionItem.js#L253) line
### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment]
Agreed, we should track this one at #25582 and close this one out.

**Comment by lschurr** [comment]
I reopened the other and will close this one out.
