### ISSUE TITLE
[$500] Attachment - Blue box appears around the pop over when Pressing ESC key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send an attachment and open the carousel
2. Click Esc key to close the pop over

## Expected Result:
No blue box should appear and the pop over should close normally

## Actual Result:
 Blue box appears when pop over closes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/83405f17-821d-460c-99df-72ff88edcbf0

https://github.com/Expensify/App/assets/78819774/e0a4e7e7-0fdd-4b41-b818-29e05fb16a14

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694607198827949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5ba45404785b30f</li>
        <li>Upwork Job ID: 1703108215256854528</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by TheyCallMeCheng** [comment]
Contributor details
Your Expensify account email: cheng_corp@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015be95d0c3dcab4e3?viewMode=1

**Comment by TheyCallMeCheng** [comment]
This doesn't seem to be a valid bug, as seen in https://github.com/Expensify/App/issues/21515#issuecomment-1610020392
