### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web - Hmm its not here page is displayed on visiting contact method by deep link and reload

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->contact method->open any contact method
3. Reload and observe that it works fine
4. Copy the URL and send to any report
5. Click on that URL and reload
6. Observe that now it displays 'Hmm its not here' page

## Expected Result:
App should not display 'Hmm its not here' page for existing added contact method

## Actual Result:
App displays 'Hmm its not here' page for existing added contact method when visited by deep link and reload

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/70c500c9-4eb8-473c-bb56-7a93163391ff

https://github.com/Expensify/App/assets/93399543/7794f297-68cc-4953-bcd2-51137446f378

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694768494012669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b03f9a78848d6111</li>
        <li>Upwork Job ID: 1703078653730959360</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26852019</li>
<li>dhanashree-sawant | Reporter | 26852020</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Linking issue https://github.com/Expensify/App/issues/22263 which author missed one test area

**Comment by narefyev91** [comment]
Proposal from @namhihi237 looks good to me https://github.com/Expensify/App/issues/27582#issuecomment-1722261341
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment]
@pecanoro friendly bump here

**Comment by pecanoro** [comment]
Sorry, I missed this one! Assigning @namhihi237

**Comment by strepanier03** [comment]
Hmm, I'm surprised this didn't get updated with the payment hold yet. I'll check on it tomorrow.

**Comment by strepanier03** [comment]
Sorry for the delay team, I've been a bit underwater but I'm working on updating this now. Thanks for the patience 🙌

**Comment by strepanier03** [comment]
I've paid out @dhanashree-sawant and @namhihi237, thank you both for your work and being part of our community. 

----

@narefyev91 - Feel free to update with the checklist items and then submit a manual request for payment. I left the payment summary amount in the payment comment [here](https://github.com/Expensify/App/issues/27582#issuecomment-1745229124).

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was not a regressions - just missing functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by narefyev91** [comment]
> I've paid out @dhanashree-sawant and @namhihi237, thank you both for your work and being part of our community.
> 
> @narefyev91 - Feel free to update with the checklist items and then submit a manual request for payment. I left the payment summary amount in the payment comment [here](https://github.com/Expensify/App/issues/27582#issuecomment-1745229124).

Hey @strepanier03 - I'm from expert agency Callstack - no needs to have manual payment :-)

**Comment by strepanier03** [comment]
Thanks @narefyev91 sorry for missing that.

**Comment by strepanier03** [comment]
Closing this out, all set now. 

Thank you to everyone for being part of our community.
