### ISSUE TITLE
[$500] Dev: Web - Long Text is getting overflowed when saved in Private Note

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any workspace chat
3. Click on header > Private Notes > My Notes > Notes
4. Copy and paste "http://localhost:8082/r/1728383477113241234123413413413413241324f23148/notes/15664052/edit" > Save

## Expected Result:
Text should not overflow

## Actual Result:
Text is overflowing from the container

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (44)](https://github.com/Expensify/App/assets/93399543/dbb90641-d0bf-4d23-bcf4-2d65c77be59f)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694787809318709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191b731192f6153a8</li>
        <li>Upwork Job ID: 1703125002924535808</li>
        <li>Last Price Increase: 2023-09-23</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @aman-atg
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694787809318709

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long Text is getting overflowed when saved in Private Note

### What is the root cause of that problem?
We just didn't handle it before as it was not required for the title text to be this long

### What changes do you think we should make in order to solve the problem?}

To fix this, we need to use `word-break:"break-word"` inside `src/components/MenuItem.js` for title

**Comment by anmurali** [comment]
Closing per https://expensify.slack.com/archives/C02NK2DQWUX/p1695654817536769
