### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] [iOS] - Workspace - Distance rate separator in Spanish causes errors

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make sure that iOS region is set to Spain (I also set keyboard language to Spanish as well as device language)
2. Change expensify language to Spanish
3. Go into workspace settings > reimbursements > track distance
4. Change rate to anything using comma

## Expected Result:
There should be no errors displayed

## Actual Result:
There is error displayed and only when you use "." as a separator (not ",") is it working

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/35bfee22-f795-45d0-a3a8-f9543d9151ae

https://github.com/Expensify/App/assets/115492554/b76f244c-64a7-4827-851e-33c5ab972106

**Expensify/Expensify Issue URL:**

**Issue reported by:** @BartoszGrajdek

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694604963679959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a56c81afd242643d</li>
        <li>Upwork Job ID: 1703121221956730880</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27095783</li>
<li>akinwale | Contributor | 27095785</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance rate separator in Spanish is causing a validation error

### What is the root cause of that problem?
 Spanish uses a comma as the decimal separator, while English uses a dot.

### What changes do you think we should make in order to solve the problem?
Update the rateValueRegex on WorkspaceRateAndUnitPage based on current locale.

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
@situchan Did you get a chance to review my [proposal](https://github.com/Expensify/App/issues/27595#issuecomment-1722295083) here yet? Thanks.

**Comment by anmurali** [comment]
Bumped @situchan on the linked Slack thread - https://expensify.slack.com/archives/C049HHMV9SM/p1695666036355529?thread_ts=1694604963.679959&cid=C049HHMV9SM

**Comment by situchan** [comment]
@akinwale thanks for the proposal. I think there should be pattern to parse locale based numeric values in the app.
`parseFloat(values.rate.replace(new RegExp(`\\${decimalSeparator}`, 'i'), '.')` - this is new to me.
Also, I don't suggest importing any 3rd parties for this.

**Comment by anmurali** [comment]
Bumped @situchan on slack again.

**Comment by akinwale** [comment]
@allroundexperts My [PR](https://github.com/Expensify/App/pull/29070) is ready for review. Thanks.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by akinwale** [comment]
@anmurali Just noting here that the PR was initially deployed to production on 2023-10-13, so the actual payment due date is 2023-10-20. Melvin got confused with a bunch of subsequent deployment issues which happened afterwards.

Thanks.

**Comment by JmillsExpensify** [comment]
Can I get a payment summary for this issue?

**Comment by anmurali** [comment]
- [ ] @akinwale [offer](https://www.upwork.com/nx/wm/offer/27095785) (Contributor), w bonus $500+$250
- [ ] @allroundexperts approved for payment with bonus $500+$250 (Eligible for Manual Requests)

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on summary.

**Comment by anmurali** [comment]
Done.
