### ISSUE TITLE
[$500] Chat -  Brief display of only profile picture and username when clicking "Reply in thread" on a PDF file

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Send a PDF file.
3. Click on "Reply in thread"
4. Observe that only the profile picture and username are briefly displayed for a second.

## Expected Result:
The PDF file should be displayed instantly in the thread along with the profile picture and username when clicking "Reply in thread"

## Actual Result:
When clicking "Reply in thread" on a PDF file, only the profile picture and username briefly appear for a second

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/75618940-a0f2-4e70-a70b-2785de49c591

https://github.com/Expensify/App/assets/78819774/1122732d-b061-425f-954f-5ef57bfef921

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694812222671909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128ed09b40cedeb04</li>
        <li>Upwork Job ID: 1703149742686220288</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by ArekChr** [comment]
I don't think this is a bug. This is intended behaviour, and it is the same for images. The display name and avatar are visible for all attachments on the first sent message.

**Comment by ayazhussain79** [comment]
@ArekChr can you please check the first video

**Comment by ArekChr** [comment]
I get it now; it's barely noticeable. However, there's room for improvement.  

@ZhenjaHorbach Loader is not the best solution since it will be displayed for just a fraction of a second.
Regarding reusing dimensions, could you briefly outline the required changes?

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
@ArekChr any thoughts on the latest proposal?

**Comment by ArekChr** [comment]
I can't reproduce this error due to regression when replying to attachments. I am trying to identify the PR that introduced this regression

**Comment by abekkala** [comment]
reached out to for someone to take this one on!
https://expensify.slack.com/archives/C03UK30EA1Z/p1696539576461879

**Comment by koko57** [comment]
tested on staging, I cannot reproduce it

https://github.com/Expensify/App/assets/28020445/53f25d8b-ba32-4390-a7d3-b0570ec7522a

even replaying slowly (half speed) and checking the frames, it looks like it's ok
https://github.com/Expensify/App/assets/28020445/7bdd51c4-e12d-4fc4-86d2-f6f4b34b671e
