### ISSUE TITLE
[$1000] Settings - When workspace, Preferences, Security are clicked in settings, there is no stacking over animation from left side

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27611]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

On Android:
1. Navigate to settings
2. Click Workspaces, Preferences, Security page

On the desktop/Chrome:
1. Navigate to settings
2. Click Workspaces

## Expected Result:
 Workspace list page should open with animation from leftside :arrow_left

## Actual Result:
When workspace is clicked in settings,there is no stacking over animation from left side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/78da5607-b13a-4cd7-97e6-dba1aa5fe37a

https://github.com/Expensify/App/assets/78819774/df62a8fe-8db3-4584-8a94-3d445725509c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ishpaul777

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694787860024659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9f4a64103e426aa</li>
        <li>Upwork Job ID: 1703159970954424320</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can take this @JmillsExpensify since you were the second to be assigned. 

Similar to - https://github.com/Expensify/App/issues/25860

I am able to reproduce this, it looks like the animation is also missing from the Preferences and Security settings on the Android app so updated the OP. 

On the desktop, the animation is only missing on the Workspace settings - updated the OP.

**Comment by Christinadobrzyn** [comment]
We're collecting proposals

**Comment by Christinadobrzyn** [comment]
@sobitneupane can you check this proposal? https://github.com/Expensify/App/issues/27611#issuecomment-1722322900

**Comment by sobitneupane** [comment]
@ishpaul777 On which platform is the issue occurring? Is it only mWeb/Chrome?

**Comment by sobitneupane** [comment]
@ZhenjaHorbach Thanks for your proposal. We don't prefer the use of `setTimeout`. Can we get it solved by any other way?

**Comment by ishpaul777** [comment]
@sobitneupane the issue can be noticed on chrome mobile(chrome). On desktop chrome, there is animation but it is not as smooth as other screens. 

https://github.com/Expensify/App/assets/104348397/e306e23c-3276-4927-94b9-972567170829

**Comment by Christinadobrzyn** [comment]
I think we're still reviewing proposals. @sobitneupane let me know if you'd like to see more proposals!

**Comment by ishpaul777** [comment]
### Proposal
When workspace, Preferences, Security are clicked in settings, there is no stacking over animation from left side

### Root Cause
Due to heavy lottie Illustrations, the transition animation is inturupted sometimes.

### Changes
1. We need to remove `autoplay` from Lottie component and play after all interactions.
```
useEffect(() => {
        InteractionManager.runAfterInteractions(() => {
            animation.current.play();
        });
    }, []);
```

2. We need to patch `react-native-web-lottie` to be able to pass a ref to use `play` and other methods

Alternatively we can put this on hold as we are implementing support for web in `lottie-react-native` and depricating `react-native-web-lottie`, but looks like it may take a while https://github.com/Expensify/App/issues/26871

**Comment by Christinadobrzyn** [comment]
Hey @sobitneupane can you take a peek at these proposals when you have a moment and let me know if you'd like to see more?

**Comment by sobitneupane** [comment]
@ishpaul777 Thanks for your proposal.

Where are you suggesting to make those changes?

> We need to patch react-native-web-lottie to be able to pass a ref to use play and other methods

We are already using the patch, right?

**Comment by Christinadobrzyn** [comment]
Added a HOLD to this for https://github.com/Expensify/App/pull/28267

**Comment by Christinadobrzyn** [comment]
hey @sobitneupane do you think this can be moved to weekly? Or should it remain daily?

**Comment by sobitneupane** [comment]
@Christinadobrzyn We can move it to weekly.

**Comment by Christinadobrzyn** [comment]
This is in production - https://github.com/Expensify/App/pull/28267

Testing again, I think this issue is still happening. @sobitneupane can you confirm and review proposals to see if any will work?

**Comment by Christinadobrzyn** [comment]
Hey @sobitneupane can you let me know if we should move forward with this, I think it's still happening after https://github.com/Expensify/App/pull/28267 was deployed

**Comment by sobitneupane** [comment]
Sorry for the delay. I was OOO. I will try to review the issue early next week.

**Comment by Christinadobrzyn** [comment]
Thanks @sobitneupane! Let me know if you want to see more proposals after the review. Thanks!

**Comment by Christinadobrzyn** [comment]
@sobitneupane just checking on an update, thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment]
Looks like the issue is still reproducible. @ishpaul777 @ZhenjaHorbach Any update?

**Comment by Christinadobrzyn** [comment]
Awesome, thanks @ishpaul777! I added a HOLD label to this while we wait for that PR.

**Comment by Christinadobrzyn** [comment]
This is on hold for https://github.com/Expensify/App/pull/30772 - monitoring. I'm going to move this to weekly since the PR is still being created.

**Comment by Christinadobrzyn** [comment]
looks like https://github.com/Expensify/App/pull/30772 is in production. And I think this is fixed with that PR. Going to ask QA for another review. https://expensify.slack.com/archives/C9YU7BX5M/p1699660576701059

**Comment by Christinadobrzyn** [comment]
QA [confirmed](https://expensify.slack.com/archives/C9YU7BX5M/p1699660576701059) this isn't reproducible anymore - closing!

**Comment by Christinadobrzyn** [comment]
Hi! Ah, that is a good point. I'll reopen and look into that for you @ishpaul777!

**Comment by Christinadobrzyn** [comment]
Okay, looking over the timeframe

- This bug was reported on Sept 16th. 
- The [PR](https://github.com/Expensify/App/pull/30772) that fixed it was deployed on Nov 2nd 
- So I do think compensation for reporting this bug is valid. 

Payouts due:

Issue Reporter: $250 @ishpaul777 
Contributor: NA
Contributor+: NA

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01949bd030c51d0242).

@ishpaul777 could you accept my offer and I'll pay you? Thanks!

**Comment by situchan** [comment]
Shouldn't this be $50? Bug was reported after price drop announcement

**Comment by Christinadobrzyn** [comment]
Ah yes, thank you @situchan! It looks like August 30th was the price change from $250 to $50 for reporting a bug. so the payment should be $50. Sorry I got my months wrong. Thanks for catching that!

**Comment by Christinadobrzyn** [comment]
Awesome! Paid out @ishpaul777 based on this payment structure - https://github.com/Expensify/App/issues/27611#issuecomment-1810795445

Closing as complete!
