### ISSUE TITLE
[$500] Members - Pressing Enter on the Add Message page selects Members on the Invite page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27617]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting > Workspace > Members > Invite
2. Select two members and click on next
3. On the Add Message page click on an empty field to lose the focus on the add message field
4. Press Enter a couple of times
5. Go back to the Invite page
Notice that additional members have been selected

## Expected Result:
Pressing Enter on the Add Message page does not select Members on the Invite page

## Actual Result:
Pressing Enter on the Add Message page selects Members on the Invite page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8edb5610-4809-4753-9f1d-d16e267e1975

https://github.com/Expensify/App/assets/78819774/5b8ad66f-9d6b-426c-837b-2d1df8fe6ff1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693342117293529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f117babb2375e7e0</li>
        <li>Upwork Job ID: 1703412740549677056</li>
        <li>Last Price Increase: 2023-09-17</li>
    </ul>
</details>

**Comment by JithilNCA** [comment]
Unable to replicate in MacOS Chrome and Desktop with the latest code and staging.

**Comment by geniusFulldev** [comment]
Contributor details
Your Expensify account email: kushnir.genious.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016e6add829c679449

**Comment by abdel-h66** [comment]
Can not reproduce this one.

**Comment by geniusFulldev** [comment]
I can't also reproduce this issue.

**Comment by daveSeife** [comment]
@abdel-h66 @geniusFulldev . This issue can still be reproduced. 
Can you please provide a video so I can be a help.

**Comment by muttmuure** [comment]
Not reproducible on v1.3.72-9
