### ISSUE TITLE
[$500] Dev: Web - Right clicking on the LHN no longer opens the context menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Right-click on any chat in the LHN

## Expected Result:
Right clicking on the LHN should open the context menu

## Actual Result:
Right clicking will do nothing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/701c3695-c3be-4281-864b-82cf10402632

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694870055438949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196f10e15b73d63b9</li>
        <li>Upwork Job ID: 1703473608406765568</li>
        <li>Last Price Increase: 2023-09-17</li>
    </ul>
</details>

**Comment by Pluto0104** [comment]
This [PR](https://github.com/Expensify/App/pull/25398) will fix this issue.

**Comment by abekkala** [comment]
@mananjadhav can you confirm that the PR linked above will also resolve this one?

**Comment by mananjadhav** [comment]
This seems to be fixed. @abekkala Can you check once and then we can close this one out?

**Comment by abekkala** [comment]
fixed
