### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Desktop - Monospace font for code block doesn't work on desktop

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account
2. Use monospace font for code blocks

Example: 
![Screenshot 2023-08-31 at 3 52 09 PM (1)](https://github.com/Expensify/App/assets/93399543/e69f5360-b91d-4f85-8b5a-1bc6eadf9225)

## Expected Result:
Monospace font for code blocks should work on desktop

## Actual Result:
Monospace font for code blocks doesn't work on desktop

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693522327341959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da4c270f6ad4ac3e</li>
        <li>Upwork Job ID: 1704446525579890688</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by rafecolton** [comment]
This is a regression so let's ensure it gets added to the regression checklist before it's closed 🙏

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The monospace font is not being used for code blocks on desktop and web.

### What is the root cause of that problem?
On web, the pre renderer makes use of the `<comment><pre>...</pre></comment>` tag to render. This makes use of the defined base font in the HTMLEngineRenderer.

### What changes do you think we should make in order to solve the problem?
Add a fallback font entry for the monospace font:
```
'ExpensifyMono-Regular': fontFamily.MONOSPACE
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
> This is a regression so let's ensure it gets added to the regression checklist before it's closed 🙏

It doesn't look like this is a regression. I thought I was going crazy earlier, but I tested with earlier releases, and it looks like the monospace font has never actually worked for code blocks on web and desktop platforms. The monospace did work fine on iOS / Android native, however.

I've figured out a fix.

**Comment by rafecolton** [comment]
How far back did you test? It 100% worked when we first introduced the feature

**Comment by akinwale** [comment]
> How far back did you test? It worked when we first introduced the feature. So it is 100% a regression, recent or not

Up to 1.3.50-0. I was prepared to go further back. 😅

My first [PR](https://github.com/Expensify/App/pull/25605) related to the feature was about 4 weeks ago, which is where I noticed from the desktop and web screenshots that the code block wasn't actually rendered using a monospace font.

**Comment by akinwale** [comment]
@rafecolton I think this is where the regression was introduced: https://github.com/Expensify/App/pull/19874

**Comment by bfitzexpensify** [comment]
Couple of proposals ready for you to review @mananjadhav

**Comment by mananjadhav** [comment]
Reviewing this.

**Comment by mananjadhav** [comment]
Because I wanted to implement and test the proposals, I attempted to reproduce the error. Am I missing something? I can't seem to reproduce this?

<img width="1218" alt="image" src="https://github.com/Expensify/App/assets/3069065/f4e2126d-c7f7-42cf-a947-512b7387b42e">

**Comment by mananjadhav** [comment]
No. I didn't. I just ran from the latest main.

**Comment by mananjadhav** [comment]
Can you run locally once and check?

**Comment by mananjadhav** [comment]
Okay I got confused as it said STG.

**Comment by bfitzexpensify** [comment]
I can also still reproduce this

**Comment by mananjadhav** [comment]
I just tested on latest main and I could reproduce this now. Apologies I was OOO. Based on @bernhardoj's [explanation](https://github.com/Expensify/App/issues/27626#issuecomment-1723106509) on doing it as per the docs, their proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by puneetlath** [comment]
Sorry for the delay. The proposal sounds good to me as well. 

>The simplest way is to import the fontFamily/index.native.js file and use it as systemFonts

I think we probably shouldn't import a native.js file into a non-native.js file. So I think the alternate is better. What do you think @mananjadhav?

**Comment by mananjadhav** [comment]
@bernhardoj any specific reason we chose the alternative solution?

**Comment by bfitzexpensify** [comment]
Switching this to daily so that I'm on top of it and pay it out when it's due

**Comment by bfitzexpensify** [comment]
Due 10/23

**Comment by mananjadhav** [comment]
@bfitzexpensify This is ready for payout, can you please post the payment summary?

**Comment by bfitzexpensify** [comment]
Payment summary:

Contributor: @bernhardoj - $750 for completion and urgency bonus (the automation didn't pick it up but I'm seeing assignment on 10/9 and merging on 10/10) to be paid via Upwork
C+: @mananjadhav $750 for completion and urgency bonus to be paid via manual request

**Comment by bfitzexpensify** [comment]
A reminder to complete the BZ checklist when you get a moment @mananjadhav - thanks!

**Comment by mananjadhav** [comment]
@bfitzexpensify I couldn't pinpoint to a specific PR that could've caused this. But I think it makes sense to add a regression for this one.

**Regression Test Proposal**

1. Open any chat
2.  Send a code block text to any chat, e.g.
```code block```
3.  Verify the font is a monospace font.
4. Enter a single line code block `code block`.
5. Verify the font is a monospace font.

**Comment by bfitzexpensify** [comment]
Cool, I like that test. Opened https://github.com/Expensify/Expensify/issues/330780 to get it added. We're all done here, thanks everyone.
