### ISSUE TITLE
[HOLD for payment 2023-10-30] [Polish] Update RBR behavior for failed Smartscanned receipts

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#27633]
Coming from [here](https://github.com/Expensify/App/issues/26832)

We need to make some changes so that the red dot in the LHN:

- No longer show it in the chat report row
- Show it in the IOU report row JUST for the requester
- Show it in the Transction row JUST for the requester
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019acc23cb45b6e738</li>
        <li>Upwork Job ID: 1703639849200287744</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Sounds good! Done!
