### ISSUE TITLE
[HOLD for payment 2023-10-12] 🔴 Ensure system messages are added when distance requests are edited. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#27630]
Coming from [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1694724896704719?thread_ts=1694724513.695869&cid=C05DWUDHVK7) as a follow-up to editing distance requests @tgolen is working on. 

We need to ensure that when the waypoints are edited, and the `amount` and `distance` field values are updated, we post the appropriate "change" system messages to log that action. Those being: 

1. modified `amount` = `changed the amount to %newAmount% (previously %oldAmount%)` 
  - Example: changed the amount to $150 (previously $100)
2. modified `distance` = `changed the distance to %newDistance% (previously %oldDistance%)` 
  - Example: changed the distance to 125 miles @ £0.655 / mi  (previously 120 miles @ £0.655 / mi)

CC: @JmillsExpensify @neil-marcellini

**Comment by tgolen** [comment]
I will start on this one. We only need to do this on the backend and we don't have to worry about doing this action optimistically on the front-end, which simplifies things. The reason we don't need to do it optimistically is because we have to use the MapBox API results in order to calculate the new route, which can only be done on the backend.

**Comment by Gonals** [comment]
Stealing this, @tgolen!

**Comment by Gonals** [comment]
Hey @trjExpensify!

I discussed this with @tgolen, but this is the first case where a `modifiedExpense` action modifies two fields at the same time (previously, it was physically impossible to do so). 
As such, both "edits" (distance and amount) are stored in a single action, but only one of them (the amount) gets displayed, as we only display one action (and we check the amount first).

We could have it display two messages, but we thought (thanks @marcaaron for the idea!) it would be better to simply display a single, more accurate message of what happened:

<img width="1063" alt="Screenshot 2023-09-21 at 5 22 07 PM" src="https://github.com/Expensify/App/assets/19366280/37b102d3-5827-4516-ac53-a36b1904e736">

Thoughts?

**Comment by trjExpensify** [comment]
Oh interesting, so "updating" seems like it's in the process of doing that action versus it having been done by the previous action. If we need to have these come together, and the amount is updated as a result of the recalculating the distance, how about:

table@expensify.com Today at 3.57pm
>changed the distance to 4.95 mi @0.6555 / mi (previously 4.88 mi @ $0.6.55 / mi) to update the amount to $3.24 (previously `$3.20`) 

The other thing I thought of was maybe separating them onto two lines, like sending two messages in quick succession:

**table@expensify.com Today at 3.57pm**
>changed the distance to 4.95 mi @0.6555 / mi (previously 4.88 mi @ $0.6.55 / mi)
>changed the amount to $3.24 (previously $3.20)

..but I agree that version doesn't really draw a link between the two as much.

**Comment by JmillsExpensify** [comment]
I kind of like the version with two lines.

**Comment by tgolen** [comment]
I like splitting it up into two lines in the same message.

**Comment by tgolen** [comment]
Though I would maybe change the second line to say "which updated the
amount to"

**Comment by Gonals** [comment]
I think I like it better all connected in a single line, as it let the users' know the amount was not "manually" updated.

I'm fine with whatever we decide, though. It doesn't seem like a big deal to me 🤷

**Comment by trjExpensify** [comment]
>changed the distance to 4.95 mi @0.6555 / mi (previously 4.88 mi @ $0.6.55 / mi) which updated the amount to $3.24 (previously $3.20)

OR

>changed the distance to 4.95 mi @0.6555 / mi (previously 4.88 mi @ $0.6.55 / mi) 
>which updated the amount to $3.24 (previously $3.20)

**Comment by Gonals** [comment]
#1 for me 😁

**Comment by trjExpensify** [comment]
Yeah, I probably prefer that as well if they aren't both "changed".

**Comment by JmillsExpensify** [comment]
I think one is ok, though honestly it would be even cleaner if we could just update the distance, because to be fair the rate can be updated completely independently. e.g. 

 - changed the distance to 4.95 mi (previously 4.88 mi). Based on a the rate @ $0.655 / mi (previously @ $0.55 / mi), the new amount is $3.24 (previously $3.20).

**Comment by trjExpensify** [comment]
I don't mind that variation either, but pretty impartial to it from the one above.

**Comment by Gonals** [comment]
> I think one is ok, though honestly it would be even cleaner if we could just update the distance, because to be fair the rate can be updated completely independently. e.g.
> 
> * changed the distance to 4.95 mi (previously 4.88 mi). Based on the rate @ $0.655 / mi (previously @ $0.55 / mi), the new amount is $3.24 (previously $3.20).

This is doable, but more complex. We currently store the `4.95 mi @0.6555 / mi` as the merchant, so it is easily accessible and we already handle changes to it. 
Handling changes for distance/rate separately would require further changes to our structure in Auth. We can do it, but I don't think it is worth the effort if it is just for this message 🤷

**Comment by trjExpensify** [comment]
Good point, let's stick with #1!

**Comment by Gonals** [comment]
Auth PR merged. App one on HOLD until we can actually edit distance requests 😁

**Comment by Gonals** [comment]
not overdue

**Comment by Gonals** [comment]
This should be done
