### ISSUE TITLE
Performance audit of the App by SWM

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27636]
### Problem

We are working on improving the performance of the App and in order to find the offending components, flows and bottleneck, we need to do audits. Margelo did one before, Callstack is doing one too and SWM is going to work on their own. Together we hope their different expertise and POV will bring us the best possible takeaways and improvements to make in the App.

### Solution

@kmagiera and @palys-swm are going to perform the audit and share results in Slack and here as well for tracking

**Comment by mountiny** [comment]
making this weekly

**Comment by muttmuure** [comment]
Another one coming hopefully in the next few days

**Comment by muttmuure** [comment]
This is ongoing

**Comment by muttmuure** [comment]
We're updating weekly in the room now. So going to close this out
