### ISSUE TITLE
[HOLD for payment 2023-10-30] Implement Reassure Regression Testing for SideBarLinks, LHN and ReportScreen

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#27641]
## Problem

We are implementing a range of initiatives to reduce the number of re-renders for app components, starting with LHN, SideBarLinks and ReportScreen. 

Without proper tracking of these initiatives, we will be unable to objectively track regressions.    

## Solution

We need:

- A plan for identifying the heaviest components to re-render using Reassure. 
- A process to perform ongoing tests in Reassure to ensure any regressions are monitored. 

We already have Reassure set up in the app so we could work on how to expand this in other components https://github.com/callstack/reassure/tree/main

**Comment by adhorodyski** [comment]
First tests for LHN are right around the corner, with eg. a whooping 45 rerenders just to get the list on the screen 💪
After this, together with @koko57 we'll transition to the ReportScreen to get the first tests there.

**Comment by mountiny** [comment]
We got off to a great start, thanks Adam for addressing the little bug quickly too. Lets work on adding more tests now

**Comment by mountiny** [comment]
Looking good, got some PRs to prod now

**Comment by adhorodyski** [comment]
@mountiny please see our update on this scope.

So far we have:
- **LHN** tests in place, covering the list with interactions to make sure we don't add new render commits on handlers
- **ReportActionsList** tests, where we test the list in isolation from the screen

Things to come:
- **ReportScreen** holistic tests - list + composer interactions. @OlimpiaZurek is working on it and is expecting to have a PR by the _EOW_.
- **Composer** tests targeting only the input interactions (without the chat list). @OlimpiaZurek will cover this starting next week, shouldn't take long as we can reuse the mocks from holistic ReportScreen tests.

I believe with all this in place we can close the work for this scope (core functionalities of these 2 screens will be covered) and add any new tests as separate efforts. Please let me know your thoughts on this!

**Comment by mountiny** [comment]
I think this sounds good and we should explore adding more thorough tests as a quick follow up

**Comment by adhorodyski** [comment]
**ReportScreen** tests have been merged, ones targeting **Composer** are not being internally reviewed under a draft PR. This will close the initial scope of this task.

**Comment by mountiny** [comment]
Perfect, thank you!

**Comment by adhorodyski** [comment]
@mountiny I believe we're now able to close this issue and focus on the `measureFunction()` tests/come up with any other if you think that'd add more value. Please let me know what you think 😊

**Comment by mountiny** [comment]
All LHN, SideBarLinks and ReportScreen. has been completed closing

Great job @adhorodyski @OlimpiaZurek @koko57
