### ISSUE TITLE
[$500] [HOLD for payment 2023-11-21] Explore options how to avoid lots of report screens pushed on stack in desktop layout

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27651]
Coming from https://expensify.slack.com/archives/C05LX9D6E07/p1694767889647489

### Problem:

Because of the way we chose to do navigation, every time we navigate to a new report, we're adding a new component to the navigation stack. That is bad because, overtime, we'll have so many components in the navigation stack that it will consume too much memory and make the app slow. This is a problem mainly for desktop since we don't really click on back and the app doesn't restart frequently, but can affect web too.

### Solution:

Still to be explored, but we need to keep the same navigation patterns and ideally limit the number of memory the screens even frozen would take

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb0ef201d2d160a5</li>
        <li>Upwork Job ID: 1729882695643987968</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by adamgrzybowski** [comment]
👁️ 👁️

**Comment by maddylewis** [comment]
plz let me know if i should be doing something specific on this issue - ty!

**Comment by mountiny** [comment]
Nothing specific now thanks!

**Comment by mountiny** [comment]
@adamgrzybowski should have something in store for this one, curious to see that once the wave8 hustle settles down a bit

**Comment by mountiny** [comment]
PR is up

**Comment by adamgrzybowski** [comment]
This one is done right?

**Comment by situchan** [comment]
yes, just waiting for payment.
@maddylewis is OOO until Nov 27

**Comment by mountiny** [comment]
@johncschuster could you please pay out $500 to @situchan for their review on the PR? Thank you!

**Comment by johncschuster** [comment]
Sorry I missed this! I'll get payment sorted now!

**Comment by johncschuster** [comment]
@situchan I've just invited you to the job. Can you ping me when you've accepted so I can issue payment? Thank you!

**Comment by situchan** [comment]
@johncschuster accepted. thanks

**Comment by mountiny** [comment]
@johncschuster All paid out, can we close? Thanks!

**Comment by johncschuster** [comment]
Yessir! I've just issued payment!
