### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Web - App Fails to Redirect to Announcement Page After Split Bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to settings > workspace > create new workspace > members.
2. Invite members to the workspace.
3. Click on the three dots and open the announcement room.
4. Click on the plus sign, select split bill, add the desired number, and click on split bill.
5. The app should redirect to the announcement page, but the split bill page remains open and the app does not redirect.

## Expected Result:
After splitting the bill in the workspace, the app should automatically redirect to the announcement page.

## Actual Result:
The app fails to redirect to the announcement page after splitting the bill, and the split bill page remains open.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-18T064009.572.webm](https://github.com/Expensify/App/assets/93399543/5bc78a5c-d946-4d90-b9ab-9aaecb8a36e8)

https://github.com/Expensify/App/assets/93399543/8c274d89-0bc6-49f1-a73f-e78fa7f48804

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695037437630339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment]
hmm was is `split bill` even showing up in the `+` list for an #announce room? 

From the looks of it after the split is created it creates a new report in the LHN since it is being split between 2 users (so a manual request) not with the workspace.

I haven't been following much with Manual Requests so I'm not 100% sure that option should be showing or not.

**Comment by bondydaa** [comment]
opened a discussion here to see what others think https://expensify.slack.com/archives/C01GTK53T8Q/p1695057805924489

**Comment by bondydaa** [comment]
PR to fix has been merged but not yet deployed https://github.com/Expensify/App/pull/27793

**Comment by bondydaa** [comment]
i think we can close? if there is payment owed somewhere let me know

**Comment by tewodrosGirmaA** [comment]
@bondydaa I didn't get paid for bug report

**Comment by tewodrosGirmaA** [comment]
(Reporter Role) Hello, @bondydaa I was wondering if I am eligible for payment even though my issue is marked as "Awaiting Payment" and I have not yet received any payment. The issue has been closed and I would appreciate any clarification on this matter. Thank you.

**Comment by bondydaa** [comment]
oh doh sorry yes that seems right, lets get a bug zero person involved to handled that, sorry!

**Comment by bondydaa** [comment]
@miljakljajic can you handle paying @tewodrosGirmaA for reporting the bug? thanks!

**Comment by miljakljajic** [comment]
Thank you, handling!

**Comment by miljakljajic** [comment]
sent contracts to you both

**Comment by tewodrosGirmaA** [comment]
Thank  you @miljakljajic  I accept the offer

**Comment by miljakljajic** [comment]
Paid and contracts ended

**Comment by miljakljajic** [comment]
Bonus paid, sorry @aimane-chnaif !
