### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Web - Wrong navigation after back from add-bank-account page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on your avatar to open settings
2. Click wallet > Then Add payment method > Then Bank account
3. Now Click on the browser back button

## Expected Result:
User should return to the wallet page

## Actual Result:
The user did not return to the wallet page, but instead went back to the settings page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 17-09-23 04_21_16.webm](https://github.com/Expensify/App/assets/93399543/bd1f4291-8409-4d15-a6d6-1aa056c6f3f3)

https://github.com/Expensify/App/assets/93399543/75d385cc-dd74-4a1a-b4bb-1bfbda858f67

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694914706789169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01993d4f2d40318905</li>
        <li>Upwork Job ID: 1710721784525074432</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by Ahmed-Abdella** [comment]
@thienlnam Sorry jack the reporting bonus again

**Comment by Ahmed-Abdella** [comment]
@joelbettner Could you plz help me on reporting bonus for this issue (regression) if you have time?

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Bug reporter: @Ahmed-Abdella $50 (offer sent via Upwork)
Contributor+: @aimane-chnaif $500 (offer sent via Upwork)

Upwork job: https://www.upwork.com/jobs/~01993d4f2d40318905

@Ahmed-Abdella @aimane-chnaif I'll complete the payouts once you've accepted the Upwork offers, thanks!

**Comment by Ahmed-Abdella** [comment]
@sakluger I accepted the offer, thanks

**Comment by sakluger** [comment]
Sorry for the delay everyone! All paid up now.

@aimane-chnaif we don't have a speed bonus on internal issues, only external ones.
