### ISSUE TITLE
Web -  Focus description cursor is not at the end position.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button
2. Click FAB button => Request money
3. Enter amount => Next
4. Select user or WS
5. Click description and input multiple line => Save
6. Click Request
7. Click Request preview
8. Click request item
9. Click description, Observe that the cursor is not at the last position

## Expected Result:
The cursor is at the end

## Actual Result:
 The cursor is at the beginning

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-18T064009.572.webm](https://github.com/Expensify/App/assets/93399543/42dc18f2-e43e-42bd-a67b-0fac037edd83)

https://github.com/Expensify/App/assets/93399543/ea54a62a-6156-4fea-ae95-28ed3d1b754c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695041832175819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Proposal  by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695041832175819


## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The cursor is at the beginning when opening the edit description page
### What is the root cause of that problem?
This issue comes from [PR](https://github.com/Expensify/App/pull/25512)
We are allowing multiple description lines [here](https://github.com/Expensify/App/blob/9b302c980f4dcaba08d113f47d4852dc121c7e4e/src/pages/EditRequestDescriptionPage.js#L44C1-L57C23)
But we only have the focus logic on the input
https://github.com/Expensify/App/blob/9b302c980f4dcaba08d113f47d4852dc121c7e4e/src/pages/EditRequestDescriptionPage.js#L30
### What changes do you think we should make in order to solve the problem?
We should update the logic focus using `focusAndUpdateMultilineInputRange`
```js
onEntryTransitionEnd={() => focusAndUpdateMultilineInputRange(descriptionInputRef.current)}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by daordonez11** [comment]
I agree with @namhihi237  this is the same solution used in MoneyRequestDescriptionPage.

cc @burczu

**Comment by puneetlath** [comment]
That makes sense to me. I'm going close this in favor of https://github.com/Expensify/App/issues/21654. Thanks y'all.
