### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web - Private Notes - Header is blur while the page is loading.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report.
2. Click on the Report Details => Private Notes.
3. Verify that the Header is blur while the page is loading.

## Expected Result:
The header should be clearly visible while the page is loading

## Actual Result:
he header is blur while the page is loading.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/737ccb24-c53a-4201-980d-25bd3e7c3834

https://github.com/Expensify/App/assets/93399543/685c2eef-e03d-4fb2-8e8f-f5759e7edfe6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694919130569099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa74e845c90b0078</li>
        <li>Upwork Job ID: 1703786341303091200</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26790081</li>
<li>hungvu193 | Contributor | 26790083</li>
<li>hungvu193 | Reporter | 26790085</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue reported by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694919130569099


## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private Notes - Header is blur while the page is loading which make it inconsistency  with other pages that have loading.
### What is the root cause of that problem?
We're using `FullScreenLoadingIndicator` while the page is loading here, since it use `StyleSheet.absoluteFillObject` which caused the issue.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesListPage.js#L131-L133
### What changes do you think we should make in order to solve the problem?
We should add style `style={[styles.flex1, styles.pRelative]}` for our `FullScreenLoadingIndicator`.

### What alternative solutions did you explore? (Optional)
Incase we didn't want to show the header while loading, we can make `FullScreenLoadingIndicator` as a return early:

```javascript
if (report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {}))) {
  return  <FullScreenLoadingIndicator />;
}

return (
....
);
```

**Comment by jjcoffee** [comment]
@hungvu193's [proposal](https://github.com/Expensify/App/issues/27685#issuecomment-1723628082) LGTM! The RCA is correct and the solution aligns with what we do for [other](https://github.com/Expensify/App/blob/9533031c7795567392cca0b295212b342c9acdfe/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L139) pages.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Li357** [comment]
@jjcoffee Just checking, you mean @kbecciv's proposal right?

**Comment by Li357** [comment]
Sounds good. I'll go ahead an assign you, thanks!

**Comment by anmurali** [comment]
Everyone's been paid.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** behaviour has always been there.
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** should've been caught in QA
- Determine if we should create a regression test for this bug. **No** - I don't think it's worthwhile (it could happen on any screen really)
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by jjcoffee** [comment]
@anmurali Checklist complete, you're welcome to close!

**Comment by Li357** [comment]
Closing!
