### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Dev:  Web- Console error show when open room name page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a WS
2. Create a room
3. Click the header of the room  => Settings => Room bane
4. Observe that an error appears in the console

## Expected Result:
No console error

## Actual Result:
An error appears in the console: "The prop `isFocused` is marked as required in `RoomNameInput`, but its value is `undefined`."

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.4
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/465a8992-8cf0-482e-9903-a93c0e16fc6f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1694920701405659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4b07b55c8e2063a</li>
        <li>Upwork Job ID: 1703792802906148864</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26875262</li>
<li>namhihi237 | Contributor | 26875264</li>
<li>namhihi237 | Reporter | 26875266</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694920701405659

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No console error when opening the room name page
### What is the root cause of that problem?
The `RoomNameInput` component uses the prop `withNavigationFocusPropTypes` here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/components/RoomNameInput/roomNameInputPropTypes.js#L32
We are using `RoomNameInput` at `RoomNamePage` which has `isFocused` as required
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/settings/Report/RoomNamePage.js#L99-L103
Here we don't pass `isFocused` so the console shows an error.
### What changes do you think we should make in order to solve the problem?
We should pass the `isFocused` prop [here](https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/settings/Report/RoomNamePage.js#L99-L103)
```
const isFocused = useIsFocused();
<RoomNameInput
  ref={(ref) => (roomNameInputRef.current = ref)}
  inputID="roomName"
  defaultValue={report.reportName}
  isFocused={isFocused}
/>;
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by peterdbarkerUK** [comment]
@kbecciv were you able to repro this on dev? 

(as per [this guidance](https://expensify.slack.com/archives/C01SKUP7QR0/p1694613015301869?thread_ts=1694584345.988399&cid=C01SKUP7QR0) I'm leaving it for C+)

**Comment by kbecciv** [comment]
Hello @peterdbarkerUK! QA team can only verify the bug on staging and production.

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif were you able to repro this on dev?

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif friendly bump on this one :)

**Comment by saranshbalyan-1234** [comment]
hi @aimane-chnaif instead of explicitly passing the isFocused prop, i think we should be initializing the isFocused prop's default value here
https://github.com/Expensify/App/blob/d848eabee0042afd53007bafe3f2406d9c44b210/src/components/RoomNameInput/roomNameInputPropTypes.js#L34-L46
Can you please check once?

**Comment by saranshbalyan-1234** [comment]
@aimane-chnaif i checked, and this is working fine with default props

**Comment by saranshbalyan-1234** [comment]
@namhihi237 initializing prop with default values in case isFocused as false, will use the same implementation that is being used across the project, we also want to avoid prop drilling by this.

**Comment by saranshbalyan-1234** [comment]
yes, sure

**Comment by francoisl** [comment]
Works for me, let's go with your proposal @namhihi237!

**Comment by francoisl** [comment]
Looks like this is ready for payment @peterdbarkerUK

**Comment by peterdbarkerUK** [comment]
Payments sent!

@namhihi237 $50 reporter
@namhihi237 $750 contributor + urgency bonus
@aimane-chnaif $750 reviewer + urgency bonus

Thanks folks!
