### ISSUE TITLE
[HOLD for payment 2023-09-29] FAB – STW button exists in the FAB menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27707]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27479
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Open the FAB menu

## Expected Result:
he STW button is not the FAB menu

## Actual Result:
The STW button exists in the FAB menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5d659949-4168-4e66-8786-2852813cd340

https://github.com/Expensify/App/assets/78819774/ed0694c9-0499-449b-b3ab-479fe0c29cd6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Hey @marcochavezf @grgia and @youssef-lr - we have this PR - https://github.com/Expensify/App/pull/27479

Are we expecting something different than what is happening in this GH?

**Comment by youssef-lr** [comment]
@marcochavezf seems like this is still an issue on staging?

**Comment by marcochavezf** [comment]
This is weird, it was removed but still exists in main [here](https://github.com/Expensify/App/blob/e90b043d406c94d60701aa2427a16fa3db150b83/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L202-L206) 🤔 

I suppose it was brought back in a merge conflict in a recent PR. I will create another PR to remove it again

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/App/pull/27763) up

**Comment by Christinadobrzyn** [comment]
Ready for payment, is there a regression test on this? I don't think so... 

I see @parasharrajat on the PR, are we paying you out for this?

**Comment by Christinadobrzyn** [comment]
Payment info I'm not sure if this needs to be paid. I think this is a regression and it is being fixed by the original team. So I don't think payments are needed here. 

@youssef-lr or @marcochavezf could you confirm?

**Comment by Christinadobrzyn** [comment]
Thank you @parasharrajat - closing!
