### ISSUE TITLE
Thread - In offline mode, clicking on reply thread directs to page keeps on loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26602
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tao on any admin room
3. Send a message
4. Long press the message sent, to open reply in thread
5. Send a message
6. Turn off mobile data
7. Tap on header profile icon
8. Tap Leave thread
9. Open the thread again from main report by tapping on " reply" thread

## Expected Result:
In offline, tapping on reply thread must direct to not found page

## Actual Result:
In offline, tapping on reply thread directs to page which keeps on loading showing "U" profile icon on header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dce32faa-bf8e-429f-a1be-9cee8f89f49a

https://github.com/Expensify/App/assets/78819774/058554de-912f-4f13-a81d-d24cb7a2b1b8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
So even though the user left the thread. Once they click on the thread again they should be able to get access to it. So while offline showing Page not found is not correct IMO.

The functionality should be the same as clicking into a new thread when offline which currently shows the report loader. So in this issue, if on staging we're showing a report loader then IMO that's good and consistent with regular threads so closing out this deploy blocker. 

If i have misunderstood anything feel free to correct me.
