### ISSUE TITLE
[$500] Android - Cannot search for accounts when assigning tasks

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the Search icon -> search for a new account
2. Click on Plus sign -> Assign task -> Enter the Title -> Next
3. Click on Assignee sector ->Enter the email of the account you just found

## Expected Result:
After entering an email address, similar accounts will be displayed according to that email

## Actual Result:
 After entering the email address, the result is "No result found"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f0d564b6-c38d-4884-b8b2-427402b271eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694752218277359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1b47bbc45c97e3c</li>
        <li>Upwork Job ID: 1703883600279060480</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by Thanos30** [comment]
This seems to have been intentionally done. https://github.com/Expensify/App/pull/25806

**Comment by kadiealexander** [comment]
@Thanos30 thank you! Agreed. Closing as intentional behaviour as per https://github.com/Expensify/App/pull/25806
