### ISSUE TITLE
 Web - Copied text from Invite screen contain names of the avatars when paste to Notepad

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27421
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open workspace invite page
3. Select more than 8 users to invite and press Next
4. Drag a text selection from the header to the bottom
5. Press CTRL+C and paste it to Notepad text editor

## Expected Result:
The pasted text should not contain data for avatar names

## Actual Result:
Copied text from Invite screen contain names of the avatars when paste to Notepad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b0267a0-a43e-4a84-b6b4-89a9cea1a9e3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Thanks for flagging. Based on this feedback here: 

https://github.com/Expensify/App/issues/24399#issuecomment-1710431080

I'm going to close.
