### ISSUE TITLE
[$500] Task details are not immediately removed after navigating back to a task using the back button browser

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27728]
Found as part of https://github.com/Expensify/App/pull/24137

1. Go offline
2. Create a task and open the task detail
3. Send a message
4. Right-click on the message and select reply in a thread
5. Press the browser back button
6. Cancel the task

Expected:
The task details show show [Canceled Task] without having to refresh the page

Actual:
The task details are shown, and require a refresh before [Cancel Task] is shown

Platform:
Web

<details>
<summary>OFFLINE</summary>

https://github.com/Expensify/App/assets/25520267/a9c8f56e-a73d-46e0-9a76-3330331483e6

</details>

<details>
<summary>ONLINE</summary>

https://github.com/Expensify/App/assets/25520267/de147dd3-c1d8-4021-a8f2-9d770a24e802

</summary>

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01815b4d02dffa34d6</li>
        <li>Upwork Job ID: 1703948271970603008</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by imranaalam** [comment]
@thienlnam 
what to expect?
what happened?

**Comment by imranaalam** [comment]
@thienlnam 
which platform?

**Comment by thienlnam** [comment]
Added some more details

**Comment by thienlnam** [comment]
> But I saw we have another bug: the last message in LHN of cancelled task report is different when offline and online. Do you think we should fix it here or it is in progress?

Is it that one shows cancelled and the other shows deleted? We're aligning task system messages in a different issue

**Comment by dylanexpensify** [comment]
@mollfpr mind giving a review on above proposal?

**Comment by mollfpr** [comment]
>ReportUtils.isCanceledTaskReport(prevProps.report, prevProps.parentReportAction) ===
            ReportUtils.isCanceledTaskReport(nextProps.report, nextProps.parentReportAction)

@Nodebrute Why `parentReportAction` become a prop? Why the issue is reproduced with the browser back button?

**Comment by mollfpr** [comment]
@Nodebrute I think it might work. Please update your proposal when you are ready.

**Comment by mollfpr** [comment]
The issue is not reproduced on staging and DEV.

**Comment by paultsimura** [comment]
Just reproduced on `1.3.72-9` (latest main):
https://www.loom.com/share/112ece73eeba4b1f84bc27da43a80ede?sid=87ddc97c-fc10-41c6-b47c-5aa36b6ed204

**Comment by dylanexpensify** [comment]
@mollfpr let's confirm reproducibility comment [here](https://github.com/Expensify/App/issues/27728#issuecomment-1729139755), and if valid review @DylanDylann's [proposal](https://github.com/Expensify/App/issues/27728#issuecomment-1729808570)!

**Comment by mollfpr** [comment]
I still couldn't reproduce it on `v1.3.74-1` latest main. @DylanDylann Could you confirm if this issue is still reproducible?

**Comment by DylanDylann** [comment]
Couldn't reproduce

**Comment by thienlnam** [comment]
Thank you all - I'll go ahead and close since we can't seem to reproduce anymore
