### ISSUE TITLE
[$500] Web - Request money - Console error after refreshing page and requesting money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27395
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Refresh the page
4. Click on FAB > Request money

## Expected Result:
There is no console error

## Actual Result:
There is a console error after refreshing a page and selecting "Request money". Console error does not show up if user navigates to different areas of the app before requesting money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e4fc577d-7fcc-4d5b-9123-e5419a19afa5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ab36420ceccc863</li>
        <li>Upwork Job ID: 1704804349777985536</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@lanitochka17 I see
>  Windows / Chrome

Is it only on Windows? 

I see these errors on Chrome/Mac
<img width="628" alt="image" src="https://github.com/Expensify/App/assets/22508304/a2e00d81-203f-4ebb-a880-a18725252731">

**Comment by lanitochka17** [comment]
I see the same console error in Windows/Chrome

![123](https://github.com/Expensify/App/assets/78819774/862f5ab6-b5c3-47a5-96cd-98e9de4cdf34)

**Comment by mallenexpensify** [comment]
Guessing/hoping this can be external, I'm unsure though.  @fedirjh , what do you think?

**Comment by Talha345** [comment]
This is a CSP error and needs to be fixed on the server side.

**Comment by mallenexpensify** [comment]
Thanks @fedirjh and @Talha345, made it Internal.

**Comment by mallenexpensify** [comment]
Hoping someone picks this up internally soon

**Comment by mallenexpensify** [comment]
hmm... are we treating console errors with the same level of priority as other bugs?

**Comment by mallenexpensify** [comment]
Still waiting internal pickup, since it's not high priority, I'll wait a lil bit longer then drop in #engineering-chat to get more 👀 and feedback about next steps

**Comment by mallenexpensify** [comment]
Posted internally
https://expensify.slack.com/archives/C03SSAQ7P/p1698785604286439

**Comment by mallenexpensify** [comment]
No takers in the post above, will post again next week if no one picks this up

**Comment by mallenexpensify** [comment]
Maybe post about next week, it's not a priority and it the holidays here...

**Comment by mallenexpensify** [comment]
Likely closing this soon since it's a console error and we're prioritizing working on roadmap issues
