### ISSUE TITLE
[HOLD for payment 2023-10-02] Implement ESLint rule to enforce curly braces for all if statements

### ISSUE THREAD

**Issue by cead22** [Expensify/App#27731]
- Discussed and agreed on [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1694518143922679) in #expensify-open-source 
- @blazejkustra is implementing this and already has a draft PR. Not sure why I can't assign them

**Comment by blazejkustra** [comment]
@cead22 I have to comment on the issue, then you can assign me! 😅

**Comment by blazejkustra** [comment]
[PR](https://github.com/Expensify/App/pull/27505) is ready to review!

**Comment by johnmlee101** [comment]
Removing my assignment and putting you in @cead22  since you reviewed the PR 😄
