### ISSUE TITLE
ReconnectApp is called after sending or receiving message with reliableUpdates beta

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Be on an account with `reliableUpdates` beta - internal only
2. Send, or receive a message
3. Notice a `ReconnectApp` command is called
4. Its even triggering a full OpenApp which is bad for large accounts

## Expected Result:
Describe what you think should've happened

Reconnect app should not be called

## Actual Result:
Describe what actually happened

Reconnect app is called and triggers getting all the updates

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.71-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695109019955889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Its coming from https://github.com/Expensify/App/pull/27180 and @danieldoglas si trying ot find a fix, if he cant in next hour or so we would revert it

**Comment by roryabraham** [comment]
Good to close this then?

**Comment by danieldoglas** [comment]
I think so! It's deployed to staging!

**Comment by roryabraham** [comment]
and prod
