### ISSUE TITLE
[Paid] [$500] Safely catch translation key when it's wrong/missing

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27759]
We've had several bad scenarios where the app crashes because the wrong translation key was used. We expect this to start increasing as we add "workspace violations" because these violations come directly from the API (and aren't translated). 

Some ideas discussing with @mountiny and @cead22 on how to potentially handle this:

 - Throw some error locally, and if in staging or production, add a fallback option for these keys which are expected to come from the backend
 - Show an empty string instead of crashing, and maybe overkill but we could show MISSING TRANSLATION to @expensify.com users

Or something else. While this is out of scope for the internal project, we wanted to get an agency working on this one. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da041a99d48079d8</li>
        <li>Upwork Job ID: 1704697208410533888</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26899854</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment]
@JmillsExpensify - In this case would I label this internal or should I leave it be for now? I don't want it held up because I'm not sure what to do with it. Thanks for the direction.

**Comment by mountiny** [comment]
Asking agency but if you can create a good proposal, we can go with contributor too

**Comment by mountiny** [comment]
Seems quite good, @robertKozik can you please review the proposal thoroughly?

**Comment by robertKozik** [comment]
I like your proposals as well @dukenv0307. It ticks all the boxes provided in the issue description. Moreover I would suggest that `MISSING TRANSLATION` string should be also visible when running Expensify app locally - It should help both Contributor and Contributor+ to track them while checking the PRs.

Also I'm not the huge fan of returning empty string in place of translation key. Providing some context (even as translation key) can be helpful in certain scenarios, as it informs the user that there should be additional information available.

@mountiny All in all I think we can go with this proposal

**Comment by sonialiap** [comment]
I'm seeing this error message in a weird spot. I'm guessing that's a separate issue, but sharing just in case https://expensify.slack.com/archives/C049HHMV9SM/p1696940644742429

**Comment by robertKozik** [comment]
@mountiny @strepanier03 Is BugZero Checklist applicable here? This issue got more like `new feature` vibe

**Comment by mountiny** [comment]
Not applicable

This is ready for a payout once the date is met $500 to @dukenv0307

**Comment by strepanier03** [comment]
Okay, this is ready to be paid tomorrow and be closed. Will take care of then.

**Comment by strepanier03** [comment]
All paid out and closing. Thanks everyone!
