### ISSUE TITLE
mWeb - Markdown - Different preview behavior when double paste markdown text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any conversation
3. Send a bold message two times without using space
4. Send a Italic message two times without using space
5. Send a strikethrough message two times without using space
6. Note the behavior of messages from steps 3,4 &5

## Expected Result:
All messages should be consistently displayed. Markdowns should be present in all three cases or not be present at all

## Actual Result:
Different preview behavior when double paste markdown text. Unlike bold & strikethrough message, italic message shows the markdowns

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f7527b21-b5b7-47d1-80aa-48de27865089

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I think we still have a general hold on such markdwon composer related issues so closing
