### ISSUE TITLE
[HOLD for payment 2023-10-02] [Wave 6: Categories] Empty categories in Money Request when creating it from FAB button

### ISSUE THREAD

**Issue by BeeMargarida** [Expensify/App#27768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the FAB button menu
2. Click on "Request Money"
3. Set the amount
4. Choose a workspace
5. Click on "Show more"
6. Click on the category
7. Note that the category list does not appear

## Expected Result:

Create a Money Request from the FAB button and it should allow to set a category.

## Actual Result:

When creating a Money Request from the FAB button, the category list does not appear.

## Workaround:

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.71-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

This feature was implemented in https://github.com/Expensify/App/pull/27139 but it seems to have been reverted in https://github.com/Expensify/App/pull/25564.

https://github.com/Expensify/App/assets/25725586/e04a2606-aa69-436d-9502-a607d8cec335

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BeeMargarida 
**Slack conversation:** https://callstack-hq.slack.com/archives/C02MW39LT9N/p1695119921000229?thread_ts=1695085557.219209&cid=C02MW39LT9N

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BeeMargarida** [comment]
After some investigation, it looks like the changes from https://github.com/Expensify/App/pull/26854 are causing the infinite loop when selecting a workspace (after applying the fixes from https://github.com/Expensify/App/pull/27139).
It looks like because we are changing the iou.id, it triggers the useEffect from `NewRequestAmountPage` that cleans the IOU.
I'm still investigating how to fix this without causing regressions

**Comment by Beamanator** [comment]
@amyevans do you want to be assigned here? I'm not sure how i got assigned at this step 😅

**Comment by amyevans** [comment]
Sure I can take it! It was an unrelated regression blocking our testing so Ana took it on

**Comment by Beamanator** [comment]
Fantastic, thanks! 👍  I mean I don't know why I got auto-assigned when you added this issue to a project, is that normal?

**Comment by amyevans** [comment]
Haha I think it's just cuz the PR needed an internal reviewer so Melvin assigned you there, then for completeness assigned you here too. That happens with the TypeScript migration PRs/issues too.

**Comment by Beamanator** [comment]
Ohhhhh i completely missed the linked PR & that I was assigned to review that 😳 sorry!! thanks for taking over anyway 😅

**Comment by amyevans** [comment]
No payments necessary so closing this out
