### ISSUE TITLE
Workspace - Workspace name is not updated in real time in WS settings "name" section

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27775]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #26217
## Action Performed:
Pre-condition: Workspace must be created and open same account in 2 devices
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap Workspaces
4. Tap any Workspace
5. Tap on Workspace name to navigate to workspace settings page in both devices
6. In one device, change workspace name and save it

## Expected Result:
In other device, the changed workspace name must be displayed below settings in top left and in "name" section

## Actual Result:
In other device, the changed workspace name is displayed below settings in top left but not updated in "name" section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7f9b8c2d-dadd-470b-bbe9-44fd3532e78e

https://github.com/Expensify/App/assets/78819774/155d4c05-26cf-4c31-8890-19031a9ceaea

**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
Isn't this an intended behavior?
It's the same with any other editing input: we persist only defaultValue. e.g. during updating account's display name.

**Comment by stephanieelliott** [comment]
Yeah I agree, this seems to be working as expected!
