### ISSUE TITLE
Task - Unable to scroll down when description is long

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27777]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Tap "+" > Assign task
5. Enter title and long description
6. Tap the "Next" button
7. Scroll down and select "Confirm task"

## Expected Result:
Able to scroll and create a task

## Actual Result:
Unable to scroll and confirm a task. Every time the user scrolls, the description gets highlighted

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7ff64b38-f311-42fe-acc7-bbb05ebfe942

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by s-alves10** [comment]
This issue is related to [this PR](https://github.com/Expensify/App/issues/23949)
We've added `parse as html` function to the description item and show it fully in confirm page.

I don't think we need to show the description fully in new task page. `description` item is a menu as well. Isn't it enough to show only the first 2~3 lines of the description?

Of course, https://github.com/Expensify/App/issues/27777#issuecomment-1725620045 can be a solution

**Comment by mountiny** [comment]
Discussed in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695184816334949?thread_ts=1695182982.405449&cid=C01GTK53T8Q), this should be fixed by the PR author @jeet-dhandha https://github.com/Expensify/App/pull/27462 but its so minor we can remove the deploy blocker label

**Comment by nkuoch** [comment]
https://github.com/Expensify/App/pull/27462 got deployed to prod
