### ISSUE TITLE
[HOLD for #24644] [$500] Dev: Web - New marker appears on last message instead of completed task task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select assign task
3. Enter title and create task
4. Go to task thread
5. Click on mark as done button
6. Mark as incomplete
7. Delete the task
8. Send 2-3 messages
9. Hover on complete task message and select mark as unread

## Expected Result:
Complete task should be mark as unread

## Actual Result:
New marker appears on last message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/98c5e5b6-5dbc-4b05-ac33-27a9c88dcf50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695100679262129
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f1042d95b7d75cf</li>
        <li>Upwork Job ID: 1704124775827062784</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
I'm not sure if it's a regression from https://github.com/Expensify/App/issues/25538, but the RCA is the same as @hungvu193 described here: https://github.com/Expensify/App/pull/26741/commits/037ce5f8a2b51642a293deb08fbb6ff48e05e436#r1322877664

The task report is a thread, and it doesn't fetch the reportAction of any of the "completed/deleted task" comments -> this leads to their createdTime being undefined here:

https://github.com/Expensify/App/blob/4d97719d69654cc18960bac5fd4a95965e4b4215/src/libs/actions/Report.js#L772

cc: @dukenv0307

**Comment by adelekennedy** [comment]
put on hold based on comment above

**Comment by adelekennedy** [comment]
still holding!

**Comment by adelekennedy** [comment]
holding!
