### ISSUE TITLE
[$500] Web - Top border is not removed when marking first message unread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Request payment to any chat
3. Open payment report
4. Mark the first report unread
5. Observe there is two borders at the top

## Expected Result:
 The first border should be removed.

## Actual Result:
 The first border is not removed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5919243b-5bc6-4993-a366-906394073749

https://github.com/Expensify/App/assets/93399543/9ca9d4b6-0e8e-42b1-b1eb-6c9657e10e82

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695102595090649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zukilover** [comment]
Dupe: https://github.com/Expensify/App/issues/26529

**Comment by puneetlath** [comment]
Ah thanks @zukilover. Closing.
