### ISSUE TITLE
[$500] Web - ReconnectApp is called after OpenReport when opening unvisited thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have a thread in chat report which you have not visited before
2. Navigate to it with console network tab open
3. Notice that after the OpenReport call we are calling ReconnectApp as well
4. That is most likely blocking showing the thread details as the Reconnect is taking 4s

## Expected Result:
We should not call the ReconnectApp in this case

## Actual Result:
The reconnectApp is called

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (48)](https://github.com/Expensify/App/assets/93399543/ef53c7c9-78a3-4d96-831b-200b1b6d9cfa)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695109019955889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016218096aa01853f9</li>
        <li>Upwork Job ID: 1704192145350979584</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by ayazalavi** [comment]
Can you guys share video? I think it is internet connectivity related issue but still please share video here.

**Comment by mountiny** [comment]
Sorry this was already handled in a deploy blocker issue and pr here https://github.com/Expensify/App/pull/27760
