### ISSUE TITLE
[$500] Dev: IOS - Horizontal line appearing above deleted task message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open a chat.
2. Navigate to the "Assign task" section.
3. Enter a title and create a task.
4. Cancel the task

## Expected Result:
A horizontal line should appear below the deleted thread message

## Actual Result:
The horizontal line is displayed above the deleted task message, not below it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-6 
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f4f0f8f6-0a2c-41fd-a369-abb62c96bd36

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695109294508539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015398ec0361ebae96</li>
        <li>Upwork Job ID: 1704198774990962688</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
@kbecciv What's the status of this issue? Why is it External/Help Wanted but the pricetag was removed?

**Comment by kbecciv** [comment]
@cubuspl42 Not sure why the price is removed, I used "External" label only, because QA team cannot verify the bug in Dev.

**Comment by cubuspl42** [comment]
Can it be added back manually? I think that people might intuitively think that this is a mislabeled internal issue when they see no pricetag.

**Comment by kbecciv** [comment]
I added manually

**Comment by mallenexpensify** [comment]
@ayazhussain79 I see you deleted a comment in the vid but I don't see 'delete comment' in the reproduce steps.  Can you please update them and/or provide more details? thx

**Comment by ayazhussain79** [comment]
@mallenexpensify i deleted comment to show you when i deleted message thread line is below deleted message but when i canceled task line is above the deleted thread

**Comment by ayazhussain79** [comment]
Line is not appearing now



<img width="342" alt="Screenshot 2023-09-26 at 1 18 02 AM" src="https://github.com/Expensify/App/assets/56740856/b56ff6c5-cec4-48f8-8b95-e715674ae7ff">

**Comment by cubuspl42** [comment]
@kbecciv @mallenexpensify Would you retest this?

**Comment by mallenexpensify** [comment]
I see this after deleting a task, the keyboard is still showing which is different than the screenshot-vid in the OP. So, I'm not able to reprodue, are you @cubuspl42 ?
![IMG_0244](https://github.com/Expensify/App/assets/22508304/9ffd18c1-3cf1-4cf2-86ec-7be3781ae53c)

**Comment by cubuspl42** [comment]
Also no. Let's close this one.

**Comment by mallenexpensify** [comment]
Thanks for checking @cubuspl42
