### ISSUE TITLE
Onyx not defined error appears in console when run the script

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #27180
## Action Performed:

1. Login
2. use Onyx.set('OnyxUpdatesLastUpdateIDAppliedToClient', null); in the console

## Expected Result:
There shouldn't be any error

## Actual Result:
Uncaught error appears
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Snip - (122) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/41c2c297-03bf-407f-b052-61dc70324172)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
OK, I get the same error: 

`VM64:1 Uncaught ReferenceError: Onyx is not defined
    at <anonymous>:1:1`

Adding engineering since that doesn't really mean anything to me @thienlnam, is this a BE or FE issue?

**Comment by thienlnam** [comment]
You can only do this in your local environment - so not a bug
