### ISSUE TITLE
[$500] [HOLD for payment 2023-09-20] Payment issue for reporting bug in pull 25164

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27821]
Issue created to compensate a Contributor member for their report here https://github.com/Expensify/App/pull/25164#issuecomment-1684442556 and it was fixed promptly here https://github.com/Expensify/App/pull/25516
E/E issue linked to the PR - no internal issue.
The reporter - @ayazhussain79.

This was before the pricing announcement so $250
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa3a1aa46eaee03b</li>
        <li>Upwork Job ID: 1704417489747525632</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Offer sent in Upwork to @ayazhussain79 👍

**Comment by ayazhussain79** [comment]
@laurenreidexpensify offer accepted, Thank you

**Comment by laurenreidexpensify** [comment]
Payment issued in Upwork 👍
