### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Receipt image is opened when opening any other image in the receipt scan room

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the the FAB and request money
2. Choose scan > then choose file
3. Choose where you want request the scan from - better choose a workspace to avoid the ( request from new acounts bug )  > then Click Request
4. Click on the request message to open the IOU room
5. In the IOU room  Click on the scan receipt message  to open the scan receipt page ( which contain all the information about the scan request )
6. Click on the + icon beside the composer and add attachment
7. Choose image and Click Send
8. Now click on the image to open it.

## Expected Result:
The image we sent should be opened

## Actual Result:
The Receipt image is opened. And It is opened by Clicking on any image that sent inside the Receipt scan room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.71-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695169078652869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133dc290a8df838b8</li>
        <li>Upwork Job ID: 1704393787448082432</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26981315</li>
<li>Ahmed-Abdella | Reporter | 26981319</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ArekChr</details>

**Comment by Ahmed-Abdella** [comment]
Reproduction video
[Screencast from 20-09-23 02:52:05.webm](https://github.com/Expensify/App/assets/77763699/1b0fb6bd-c4b7-4fe6-899e-04049caee282)

**Comment by Ahmed-Abdella** [comment]
IMPORTANT NOTICE:
The same behvior is happening for Distance, the map is opened by clicking on any other image in the room

**Comment by miljakljajic** [comment]
Reproducible on staging:
https://github.com/Expensify/App/assets/28715117/bcb35b7c-c4ec-4e47-a6d4-587003cebce6

**Comment by thienlnam** [comment]
I am going to remove the deploy blocker from the issue so we can move forward with deploy considering it's been delayed a couple days already. This is a bug we should fix, but doesn't seem like a major bug considering it has to be within the scan details

**Comment by ArekChr** [comment]
@dukenv0307 Why does the image preview reload after opening the receipt?

**Comment by ArekChr** [comment]
I'm not really in favour of this behaviour. I expect a solution where the proper image is opened before the preview opens.

**Comment by aldo-expensify** [comment]
> I'm not really in favour of this behaviour. I expect a solution where the proper image is opened before the preview opens.

By "proper" are you referring to the image coming from the BE? They should be the same, right? it is not great to have the image refreshing just to show the same, but  it may be unavoidable? Is it a possibility to just keep the local image instead of overriding it with the BE image?

**Comment by miljakljajic** [comment]
Bump @ArekChr

**Comment by situchan** [comment]
@ArekChr is OOO

**Comment by aldo-expensify** [comment]
Waiting on @ArekChr

**Comment by ArekChr** [comment]
> @ArekChr I think we can't do that, after uploading the image, we should show the local image first and display the uploaded image when BE returns data. Pls check the video below, the image is blink for a moment (change from local image to uploaded image)

@dukenv0307 Thanks for the explanation, that makes sense to me. The [proposal](https://github.com/Expensify/App/issues/27824#issuecomment-1727387155) looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by dylanexpensify** [comment]
@ArekChr this is blocking another high value wave 4 issue - can we get this reviewed asap please?

**Comment by miljakljajic** [comment]
offers sent to both @Ahmed-Abdella and @dukenv0307 - let me know when you accept and I'll get them paid right away!

**Comment by Ahmed-Abdella** [comment]
Hi, @miljakljajic, an offer was already sent before and I  accepted it. Should I accept the new one ?

**Comment by ArekChr** [comment]
- [x] Determine if we should create a regression test for this bug: Yes we can regression test here.

**Regression Test Proposal**

1. Click on the FAB to request money.
2. Click on request money, select 'scan', then select 'file'.
3. Select a workspace to request the scan, then click 'Request'.
4. Click on the request message to open the IOU room.
5. In the IOU room, click on the scan receipt message to view the scan receipt page.
6. Click on the '+' icon beside the message composer and add an image attachment.
7. Send the image and then click on it to open.
8. Verify that the specific image sent should open instead of the image receipt.

Do we agree :+1: or :-1:

**Comment by miljakljajic** [comment]
Apologies @Ahmed-Abdella can you link me the original offer and I'll pay it?

**Comment by Ahmed-Abdella** [comment]
Here it is @miljakljajic https://www.upwork.com/nx/wm/workroom/35012489/overview

**Comment by miljakljajic** [comment]
Paid for both of you, thank you!
