### ISSUE TITLE
PR27180- Web- Unable to use Onyx.set('OnyxUpdatesLastUpdateIDAppliedToClient', null); as error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2.use Onyx.set('OnyxUpdatesLastUpdateIDAppliedToClient', null); in the console

## Expected Result:
User able to set the status to null

## Actual Result:
Uncaught reference error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6206767_Full_Screen__2](https://github.com/Expensify/App/assets/115492554/34688b10-2f9d-44ae-8a83-e3c88d9c4525)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
This issue was found while executing PR https://github.com/Expensify/App/pull/27180

**Comment by pradeepmdk** [comment]
I think this is not a bug because in the production build onyx ref is not added in the window variable. 
![Screenshot 2023-09-20 at 2 32 14 PM](https://github.com/Expensify/App/assets/16595846/b47a9203-d105-4f01-a977-746eb0f17264)

**Comment by michaelhaxhiu** [comment]
This is strange. Can you give a little more context @izarutskaya ?
