### ISSUE TITLE
[HOLD for payment 2023-10-09] Web - Copying 'paid elsewhere' text copies the wrong text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27858]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed in
2. Request money from user B
3. Open a tab where user B is signed in
4. Open the chat with user A > Click on 'IOU preview component'
5. Click on 'Pay elsewhere' button
6. Hover over the new paid elsewhere message
7. Click on 'copy to clipboard' icon
8. Past the copied text

## Expected Result:
Pasted text should reflect what was copied from the message

## Actual Result:
Requested 0.00 is pasted

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/70c8154f-c033-4811-bb26-7ec2c91b2193

https://github.com/Expensify/App/assets/93399543/67efd5da-1059-4fb9-a73f-b443b5d8b38c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695205011947579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
Seems regression from https://github.com/Expensify/App/pull/27142 @rayane-djouah

**Comment by thienlnam** [comment]
Removing the deploy blocker on this as this is not a huge bug and doesn't need to be a deploy blocker

**Comment by mountiny** [comment]
I think this can be closed and we will handle in the original issues which you can find linked in the PR

**Comment by Natnael-Guchima** [comment]
@mountiny is this something I am eligibile for reporting bonus?

**Comment by Natnael-Guchima** [comment]
@mountiny this issue is fixed now. Can you please reopen this to handle reporting payment? Thanks.

**Comment by bfitzexpensify** [comment]
Offer sent @Natnael-Guchima

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @bfitzexpensify

**Comment by bfitzexpensify** [comment]
OK, all paid out, we're done here.

**Comment by mananjadhav** [comment]
@bfitzexpensify I am still pending to be paid out here. @mountiny Are we tracking it somewhere else?
