### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] mWeb -  Clicking back button takes user to wrong page from avatar preview page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > profile
2. Click on avatar and add a photo if you don't have any
3. Click on the avatar again
4. Click on View photo
5. Click on the system/browser back button

## Expected Result:
App should take user back to profile page

## Actual Result:
App takes user to settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fdeff154-d947-4286-b91c-ceaec073bae3

https://github.com/Expensify/App/assets/93399543/aa99b073-84d4-4b18-b920-fd653eca9bee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695198495998809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e3810eaf600caf1</li>
        <li>Upwork Job ID: 1704467134489030656</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27020346</li>
<li>dukenv0307 | Contributor | 27020347</li>
<li>Nathan-Mulugeta | Reporter | 27020348</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Was able to recreate. @aimane-chnaif, thoughts on the proposal above?

**Comment by NicMendonca** [comment]
@aimane-chnaif proposals here for you! ^

**Comment by NicMendonca** [comment]
@aimane-chnaif any updates?

**Comment by NicMendonca** [comment]
@aimane-chnaif @dukenv0307 what's the latest on this one?

**Comment by NicMendonca** [comment]
I am going on leave starting tomorrow, so just paid everyone out today!
