### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web - Receipt scan request container corners are not rounded while it is in progress

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the FAB and request money
2. Choose scan > then Choose file
3. Choose where you want to request from and click request
4. Click on the request message on the main chat to open the IOU room
5. Notice the corners of the scan request container

## Expected Result:
The corners of the scan request container should be rounded

## Actual Result:
Receipt scan request container corners are not rounded while it is in progress ( No border radius )

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 20-09-23 05_08_04.webm](https://github.com/Expensify/App/assets/93399543/652b333a-0040-46b5-b022-2e0cfb0cffbe)

https://github.com/Expensify/App/assets/93399543/81900749-f874-409f-a5a9-edc791c6d14b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695176494284799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116d11f7e44782d5a</li>
        <li>Upwork Job ID: 1704583117854482432</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26784222</li>
<li>getusha | Contributor | 26784224</li>
<li>Ahmed-Abdella | Reporter | 26784225</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
This is a regression of [this PR](https://github.com/Expensify/App/pull/27692)

**Comment by bondydaa** [comment]
doh thanks for letting us know @getusha @fedirjh can you comment so I can assign?

**Comment by getusha** [comment]
> doh thanks for letting us know @getusha @fedirjh can you comment so I can assign?

yeah we should handle this one.

**Comment by jliexpensify** [comment]
@fedirjh bump to complete the checklist - I'll pay tomorrow!

**Comment by jliexpensify** [comment]
Payment Summary:

- Reporter: @Ahmed-Abdella $50
- Contributor: @getusha $500
- C+: @fedirjh 

[Upwork job](https://www.upwork.com/jobs/~0116d11f7e44782d5a)

**Comment by jliexpensify** [comment]
Also @fedirjh and @getusha can you accept those offers? Cheers!

**Comment by jliexpensify** [comment]
BUMPING @fedirjh and @getusha to accept the offers please.

BUMPING @fedirjh to complete the checklist!

**Comment by jliexpensify** [comment]
Thank you @fedirjh ! @getusha please accept the offer so I can pay everyone, thanks!

**Comment by getusha** [comment]
@jliexpensify i don't think i should be getting paid here, this was a regression from a PR fixing a regression from another PR. i don't know how we process that 😄

**Comment by jliexpensify** [comment]
Huh ok...that's not something I have come across before...let me check in and update you both!

**Comment by jliexpensify** [comment]
Hmm ok, so - here are the Regression Guidelines:

![image](https://github.com/Expensify/App/assets/30815269/64a6d669-bf7d-4935-bb9b-06d3c0dea9a6)

If this is a regression of a regression, then I would imagine the payout would be:

- Reporter: @Ahmed-Abdella $50
- C: @getusha [$500 / 2] / 2 = $125
- C+: @fedirjh [$500 / 2] / 2 = $125

**Comment by jliexpensify** [comment]
Just confirming - no further regressions here right? If not, I'll move to paying based off [this](https://github.com/Expensify/App/issues/27869#issuecomment-1758928898)

**Comment by jliexpensify** [comment]
Everyone paid, job closed!
