### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] [$500] Web - App crash on request money with Workspace chat 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select request money option
2. Enter money and press next button
3. Select Workspace chat 

## Expected Result:
App should not crash on request money with Workspace chat 

## Actual Result:
App crash on request money with Workspace chat 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4d11dbe9-e6b9-48c6-91f7-bceaf197df59

https://github.com/Expensify/App/assets/93399543/09fcce23-2c02-45c2-9b9d-2adfa5d1058d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695199393524129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c0a28278a27071e</li>
        <li>Upwork Job ID: 1704536148374425600</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 26781104</li>
<li>gadhiyamanan | Reporter | 26781106</li>
<li>namhihi237 | Contributor | 26781279</li>
</ul></li>
    </ul>
</details>

**Comment by s77rt** [comment]
@nkuoch Please assign me & @namhihi237 as this is a regression from https://github.com/Expensify/App/pull/27729

@namhihi237 Please prepare a PR fixing this

**Comment by Pluto0104** [comment]
Hmm, I can't reproduce this on latest main.

**Comment by nkuoch** [comment]
Can't assign @namhihi237 because he didn't comment

**Comment by s77rt** [comment]
No payment is due here since it's a regression except for the bug reporter

**Comment by mountiny** [comment]
The bugzero person has been missing here, sorry for the delay

We only need to[ pay the reporter ](https://github.com/Expensify/App/issues/27864#issuecomment-1732114813)as this was a regression handled by the author of the offending PR.

@CortneyOfstad could you please pay $50 to @gadhiyamanan for reporting

**Comment by CortneyOfstad** [comment]
Sounds good @mountiny!

@gadhiyamanan I'll be sending you a payment request shortly. Unfortunately Upwork did not automatically create the job post, and keeps erroring out when I attempt to manually create it 🙃 I will keep checking and will update you ASAP. Thanks for your patience!

**Comment by CortneyOfstad** [comment]
[Job Post](https://www.upwork.com/jobs/~01606d27b31f568c17)

@gadhiyamanan I was finally able to get it to post in Upwork, so please let me know once you accept the proposal and we can get this paid ASAP. Thanks for your patience!

**Comment by gadhiyamanan** [comment]
@CortneyOfstad offer accepted, thanks!

**Comment by CortneyOfstad** [comment]
Perfect! 

## Payment Summary

@gadhiyamanan paid $50 in Upwork as the Bug-Reporter.

**Comment by CortneyOfstad** [comment]
Are we good to close @mountiny @nkuoch?
