### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Web - Focus outline for checkbox not aligned with border in TaskView

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB > Assign task. Enter title, share somewhere and create a new task.
2. In task view, click on composer and press shift + TAB 4 times (or more if there are comments in report).
3. Notice that, focus outline is not aligned with border, radius is less for outline.

## Expected Result:
Radius of outline on focus should be aligned with border like we have for TaskPreview and all other components.

## Actual Result:
Focus outline is not aligned with border.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![img2](https://github.com/Expensify/App/assets/93399543/195b4455-05bf-4554-a820-2f8a343240c7)

![img1](https://github.com/Expensify/App/assets/93399543/c766ca90-f010-4c18-aa59-0a305b66c3eb)

https://github.com/Expensify/App/assets/93399543/bd4102f4-a829-4808-9af8-24a8eae50f8d

https://github.com/Expensify/App/assets/93399543/674b011d-e442-4163-b601-bd935938eff2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695154519892849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Focus outline for checkbox is not aligned with border in TaskView. It is aligned at all other places.
### What is the root cause of that problem?
In TaskView, size of checkbox is larger than all other places so we use larger `border-radius` of `8px`. We pass it via props.
https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/components/ReportActionItem/TaskView.js#L92
In all other places, we use the default `border-radius` for checkbox that is `4px`.
https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/components/Checkbox.js#L65
In order for the outline to be aligned, the `border-radius` for `PressableWithFeedback` (ancestor of Checkbox) should be `2px` more than the `border-radius` of `Checkbox` but right now `border-radius` of `PressableWithFeedback` is fixed -
https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/styles/styles.js#L2642-L2643
So, except `TaskView`, outline is aligned for all checkboxes  since they have `4px` `border-radius`.
This was finalized in [this PR](https://github.com/Expensify/App/pull/20997) but `TaskView` component was redesigned later and the checkbox size was made larger without keeping outline in mind which created this bug.
### What changes do you think we should make in order to solve the problem?
We need to make the `border-radius` of `PressableWithFeedback` dynamic by making it `2px` more than the `border-radius` of `Checkbox`. For this, we can make a function in `StyleUtils` similar to [getCheckboxContainerStyle](https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/styles/StyleUtils.ts#L1152) which was created for dynamic `border-radius` for checkbox.
```javascript
/**
 * Returns the checkbox pressable style
 */
function getCheckboxPressableStyle(borderRadius: number): ViewStyle | CSSProperties {
    return {
        padding: 2,
        justifyContent: 'center',
        alignItems: 'center',
        // eslint-disable-next-line object-shorthand
        borderRadius: borderRadius,
    };
}
```
Then, we can remove `checkboxPressable` styles from `styles.js` [here](https://github.com/Expensify/App/blob/6d675529b2825b71c5c2bef332e7a07f0230c86f/src/styles/styles.js#L2642C1-L2643) and use the above utility function instead -
```javascript
<PressableWithFeedback
    disabled={props.disabled}
    onPress={firePressHandlerOnClick}
    onMouseDown={props.onMouseDown}
    ref={props.forwardedRef}
    style={[props.style, StyleUtils.getCheckboxPressableStyle(props.containerBorderRadius + 2)]} // to align outline, border-radius of pressable should be 2px more than Checkbox
    onKeyDown={handleSpaceKey}
    accessibilityRole={CONST.ACCESSIBILITY_ROLE.CHECKBOX}
    accessibilityState={{checked: props.isChecked}}
    accessibilityLabel={props.accessibilityLabel}
    pressDimmingValue={1}
>
```
### What alternative solutions did you explore? (Optional)
NA
Result -
https://github.com/Expensify/App/assets/31413407/48c6ec3d-c302-47ba-8d72-b2ef2c88fbad

**Comment by jliexpensify** [comment]
Removing myself as I was the 2nd B0 assigned

**Comment by jjcoffee** [comment]
Reviewing on Monday!

**Comment by jjcoffee** [comment]
@Nikhil-Vats has a really nice clear [proposal](https://github.com/Expensify/App/issues/27872#issuecomment-1728059405) with the correct RCA and the solution makes sense, so happy to go with them!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by deetergp** [comment]
Thanks for a very nicely-written proposal, @Nikhil-Vats 👍

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** root cause has existed since the beginning
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **No - too low impact**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by jjcoffee** [comment]
@sonialiap Checklist complete!

**Comment by sonialiap** [comment]
@jjcoffee review + bonus = $750 - offer sent
@Nikhil-Vats report + fix + bonus = $800 - offer sent

**Comment by jjcoffee** [comment]
@jliexpensify Offer accepted!

**Comment by jliexpensify** [comment]
Paid and job closed!
