### ISSUE TITLE
Chat - The account does not shows up in Options list when start a chat with the same account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found executing #27499
## Action Performed:
1. Sign into NewDot
2. Start a new chat with an account and don't send any message
3. Open another existing chat (like concierge), make sure the chat disappears from the LNH
4. Click on FAB > Send message

## Expected Result:
When user Start a chat again with that same account - the account should shows up in the Options list since you already had a chat with it before

## Actual Result:
The account does not shows up in Options list when start a chat with the same account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ca5a8941-2ff9-40ec-b911-0f142b8d63f3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Oh hm, I'm not sure if this is actually a bug. I agree it's confusing to the member, but @puneetlath, is this correct because until that person you started a chat with responds they aren't in your contacts list yet?

**Comment by puneetlath** [comment]
Yep, that's exactly right. Not a bug.
