### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Chat - Requests with "500" response get retried forever

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make an API request
2. Receive a "500" response
3. See the app retry forever
This has been observed most recently on Adele's app, it has retried the same request over and over more than 700 times in 18 hours. This is counterproductive for both the client and the server.

## Expected Result:
The app retries 10 times and then gives up

## Actual Result:
The app retries forever

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695192245623099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f6a45932c14b97e</li>
        <li>Upwork Job ID: 1705798204599291904</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26915936</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Adding the external label. Let's get some proposals!

**Comment by akinwale** [comment]
From which of the endpoints can we get a 500 error returned?

**Comment by puneetlath** [comment]
I think we should just assume any request can return a 500 error.

**Comment by puneetlath** [comment]
Thanks for pointing that out @bernhardoj. I brought it up in [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1695192245623099). Let's go ahead and bring the retry limit back.

**Comment by sobitneupane** [comment]
@dukenv0307's proposal looks good to me, but how can we test the scenario?

**Comment by puneetlath** [comment]
Would it work to try hitting a non-existent api command?

**Comment by flodnv** [comment]
>Would it work to try hitting a non-existent api command?

No... I'm honestly not sure how a contributor can test this (apart from making a new API that returns 500...), TBH I think the internal engineer (aka you @puneetlath 😄 ) should test using the dev VM and make the API throw a PHP Fatal

**Comment by puneetlath** [comment]
Cool, can do!

**Comment by puneetlath** [comment]
@sobitneupane bump on the checklist so that we can pay 😄

**Comment by puneetlath** [comment]
@sobitneupane bump on the checklist!

**Comment by puneetlath** [comment]
Just waiting on the checklist from @sobitneupane so we can pay 😅

**Comment by puneetlath** [comment]
@sobitneupane bump on the checklist please!

**Comment by sobitneupane** [comment]
Sorry for the delay @puneetlath. I was OOO. I will try to get to it before weekend.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/9306
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/9306#issuecomment-1784965341
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was an intended behavior back when it was introduced.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

No.

**Comment by puneetlath** [comment]
@sobitneupane can you go ahead and request payment in NewDot? 

Payment summary: 
- C - @dukenv0307 - $500 (paid via Upwork)
- C+ - @sobitneupane - $500 (to be paid via NewDot)

**Comment by sobitneupane** [comment]
Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @sobitneupane based on summary above.
