### ISSUE TITLE
[$500] mweb/Chrome - Login - Long pressing on input field does not invoke copy, paste menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Long press on email input field on login page

## Expected Result:
Text format menu like copy, paste menu will open up

## Actual Result:
There is no text menu opening up
This issue also occurs on different areas across the mweb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8fbd5fdf-737e-45c3-b724-0127e4a2b859

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01377dc6c60b09e0a7</li>
        <li>Upwork Job ID: 1704931874245771264</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by amanx123** [comment]
I would like to work on this, please assign I can solve this asap.

**Comment by DrErRasheed** [comment]
I would like to work on this ,please assign i can solve this asap.
Contributor details
Your Expensify account email: mrash660@gmail.com

Upwork Profile Link: https://www.upwork.com/freelancers/~01a30760fe9736be67

**Comment by pranabs1ngh** [comment]
@lanitochka17 Can you suggest an input box where the copy paste menu opens up? I'm trying to find it

**Comment by pranabs1ngh** [comment]
Contributor details
Your Expensify account email: iampranabb@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014008ea711e35d795

**Comment by AntonNikonov1** [comment]
I soled your problem, please contact me. Solved on pc but on mobile solution the same. Please contact me, I will send you video result. 

**Email**: beastfreelacer@gmail.com
**UpWork**: https://www.upwork.com/freelancers/~014b0b214621a8500e

**Comment by AntonNikonov1** [comment]
Contributor details
Your Expensify account email: monsterfreelacer@gmail.com.
Upwork Profile Link: https://www.upwork.com/freelancers/~014b0b214621a8500e

**Comment by AntonNikonov1** [comment]
Contributor details
Your Expensify account email: [monsterfreelacer@gmail.com](mailto:monsterfreelacer@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~014b0b214621a8500e

**Comment by DrErRasheed** [comment]
We are going to use 'Clipboard' API provided by React Native to handle the copy and paste text .In the Onlongpress event handler we are going to include the logic.. 

I would like to work on this ,please assign i can solve this asap.

Contributor details
Your Expensify account email: [mrash660@gmail.com](mailto:mrash660@gmail.com)

Upwork Profile Link: https://www.upwork.com/freelancers/~01a30760fe9736be67

**Comment by DrErRasheed** [comment]
We are going to use 'Clipboard' API provided by React Native to handle the copy and paste text .In the Onlongpress event handler we are going to include the logic..

I would like to work on this ,please assign i can solve this asap.

Contributor details
Your Expensify account email: [mrash660@gmail.com](mailto:mrash660@gmail.com)

Upwork Profile Link: https://www.upwork.com/freelancers/~01a30760fe9736be67

**Comment by DrErRasheed** [comment]
I would like to work on this ,please assign i can solve this asap.
Contributor details
Your Expensify account email: [mrash660@gmail.com](mailto:mrash660@gmail.com)

Upwork Profile Link: https://www.upwork.com/freelancers/~01a30760fe9736be67

**Comment by DrErRasheed** [comment]
I would like to work on this ,please assign i can solve this asap.
Contributor details
Your Expensify account email: [mrash660@gmail.com](mailto:mrash660@gmail.com)

Upwork Profile Link: https://www.upwork.com/freelancers/~01a30760fe9736be67

**Comment by CortneyOfstad** [comment]
> ⚠️ Missing/invalid email or upwork profile link. Please make sure you add both your Expensify email and Upwork profile link in the format specified.

CC @DrErRasheed — Thanks!

**Comment by DrErRasheed** [comment]
welcome, Could you please add me to slack channel.
Thanks, CC @CortneyOfstad 
email sent .
 email : mrash660@gmail.com

**Comment by CortneyOfstad** [comment]
@aimane-chnaif bump on @dukenv0307's comment above ^^^ TIA!

**Comment by CortneyOfstad** [comment]
@aimane-chnaif bump on the comment above ^^^ thanks!

**Comment by CortneyOfstad** [comment]
@aimane-chnaif bump again — thanks!

**Comment by CortneyOfstad** [comment]
I am not sure why, but @mkhutornyi wasn't automatically assigned based on @aimane-chnaif's comment [here](https://github.com/Expensify/App/issues/27894#issuecomment-1763499613)

**Comment by CortneyOfstad** [comment]
@mkhutornyi sorry for any confusion here. Do you or @aimane-chnaif have any updates on a potential PR?

**Comment by CortneyOfstad** [comment]
@aimane-chnaif do you have an idea in mind for compensation? We normally do it percentage based (i.e. 10%, 20%, etc). This would be based on the base pay ($50 and $500 depending on the role). We can then bring it internally for discussion with the team for approval. Thanks!

**Comment by CortneyOfstad** [comment]
I feel 25% is fine in this situation, if that is okay with you @aimane-chnaif 👍 

Unfortunately, Upwork is not allowing me to recreate the job or create proposals (based on the issue [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1697640946526269?thread_ts=1697640740.978329&cid=C01SKUP7QR0)) and I am heading OoO until Oct. 25. Reassigning the BZ label to get this tackled while I am gone 😭

**Comment by Christinadobrzyn** [comment]
Okay, catching up on payment. How does this look?

Payouts due:

Issue Reporter: NA
Contributor: $125 partial payment @mkhutornyi 
Contributor+: $125 partial payment @aimane-chnaif 

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01c30ec7d86586ecad).

**Comment by Christinadobrzyn** [comment]
Okay, paid out through Upwork based on this payment structure. https://github.com/Expensify/App/issues/27894#issuecomment-1773370446

Let me know if anything else is needed - closing for now!
