### ISSUE TITLE
Thread - Incorrect redirection from Thread to LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any conversation
4. Send a "Test" message
5. Reply in the thread of this message. Name it "Test 1"
6. In thread 1 send a message and reply in the thread of this message. Name it "Test 2"
7. In thread 2 send a message and reply in the thread of this message. Name it "Test 3"
8. Click in the header on the user account credentials 3 times to return to the main conversation
9. Click on the "Back" arrow in the header

## Expected Result:
The user must return to the LHN

## Actual Result:
The user returns to the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c7785713-f94e-4139-b754-69009a57b15d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by peterdbarkerUK** [comment]
I think this behaviour is intentional, with the back button taking you to the last room visited, rather than left-wards until you hit the LHN. Have I perhaps misunderstood?

**Comment by mountiny** [comment]
This is intentional @lanitochka17 @kavimuru can you please update your tests to make sure this is not raised in future
