### ISSUE TITLE
[$500] [HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] RM - App crashed when tap replace receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR**  https://github.com/Expensify/App/pull/26508
1. Launch App
2. Request money via Scan option
3. Tap the report preview
4. Tap the request preview
5. Tap the receipt image
6. When the modal opens, tap the three dot menu at the top
7. Select replace

## Action Performed:
Camera should be open again to replace the receipt image.

## Expected Result:
App crashed when tap replace receipt
Issue occurred on Android App as well

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1e74d8c6-22be-42ae-b88a-c698e83cc1fa

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d18ed8dd8d228a2</li>
        <li>Upwork Job ID: 1709869686165725184</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes when attempting to replace a receipt.

### What is the root cause of that problem?
When Replace Receipt option is selected, the app navigates to the `EditRequestReceiptPage` component which contains a `ReceiptSelector`. On native platforms, `ReceiptSelector` makes use of a `NavigationAwareCamera` which uses the `useTabAnimation()` hook. This hook is designed to throw an error if the component using it is not embedded within a tab. Since the `ReceiptSelector` in this scenario is not within a tab, the app crashes with this error.

### What changes do you think we should make in order to solve the problem?
Add a way to check if the component is within a tab and then update the implementation accordingly. This can be achieved with the following steps.

1. Add a `lodashGet` for a new param, `isTab` which should indicate whether or not the component is in a tab.
```
const isTab = lodashGet(route, 'params.isTab', 0);
```

2. Pass the `isTab` param as a prop to the `NavigationAwareCamera` component.  
```diff
<NavigationAwareCamera
  ref={camera}
  ...
+  isTab={isTab}
/>
```
3. Add support for the `isTab` prop to `NavigationAwareCamera`
```
function NavigationAwareCamera({cameraTabIndex, isTab, forwardedRef, ...props}) {
```

4. Conditionally set `tabPositionAnimation` based on the value of `isTab`.
```diff
+const tabPositionAnimation = isTab ? useTabAnimation() : null;
useEffect(() => {
+    if (!tabPositionAnimation) {
+        return;
+    }
    const listenerId = tabPositionAnimation.addListener(({value}) => {
        // Activate camera as soon the index is animating towards the `cameraTabIndex`
        setIsCameraActive(value > cameraTabIndex - 1 && value < cameraTabIndex + 1);
    });

    return () => {
        tabPositionAnimation.removeListener(listenerId);
    };
}, [cameraTabIndex, tabPositionAnimation]);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by Li357** [comment]
@akinwale I agree with the RCA here but is there a more elegant way to do this? This might not work, but could have a param on the `EditRequestReceiptPage` that we can directly get from the navigation context in `NavigationAwareCamera`?

**Comment by akinwale** [comment]
> @akinwale I agree with the RCA here but is there a more elegant way to do this? This might not work, but could have a param on the `EditRequestReceiptPage` that we can directly get from the navigation context in `NavigationAwareCamera`?

@Li357 Two options I can think of:
1. We can check with the `pageIndex` prop which is already being passed. If it is not set (null or undefined), then we can assume that the ReceiptSelector is not in a tab.
2. Forward the `route` prop to the `NavigationAwareCamera` from `ReceiptSelector` and use this to check, but we still need  to set a param that can be used to check.

**Comment by akinwale** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/27903#issuecomment-1728724238)

**Comment by Li357** [comment]
Going to handle this with Proposal 1

**Comment by laurenreidexpensify** [comment]
Also assigning @akinwale for a discretionary bonus here, as we used their solution.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

External issue reporter - Applause, N/A 
Contributor that fixed the issue - @Li357 internal, N/A
Contributor+ that helped on the issue and/or PR - @parasharrajat $500, please request payment in newdot
Proposal bonus - @akinwale $125, please apply in Upwork thank you!

**Comment by akinwale** [comment]
> Payment Summary:
> 
> External issue reporter - Applause, N/A Contributor that fixed the issue - @Li357 internal, N/A Contributor+ that helped on the issue and/or PR - @parasharrajat $500, please request payment in newdot Proposal bonus - @akinwale $125, please apply in Upwork thank you!

There isn't an Upwork job created for this issue.

**Comment by laurenreidexpensify** [comment]
@akinwale apols, Upwork job live now! Please apply and I will adjust payment to $125 when when we pay out the job. Thanks!

**Comment by akinwale** [comment]
> @akinwale apols, Upwork job live now! Please apply and I will adjust payment to $125 when when we pay out the job. Thanks!

@laurenreidexpensify Applied. Thanks!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on BZ summary.

**Comment by laurenreidexpensify** [comment]
Thanks for confirmation @parasharrajat 

in that case @akinwale as we didn't use your proposals in end, there won't be a discretionary bonus after all. thanks all.
