### ISSUE TITLE
[$500] mWeb- Workspace-Workspace deleted, in offline sent text, strike through message shown in bold

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile-Workspaces
3. Create a new workspace
4. Navigate to LHN
5. Tap profile- preferences- toggle on forced offline
6. Open announce room of newly created workspace
7. Enter any text message (without any markdown) and send
8. Enter a message with strike through markdown ~venkateshwara~ and send
9. Long press the strike through markdown ~venkateshwara~ sent message and delete the message
10. Open same account in other device, and delete the newly created workspace
11. In original device where workspace created, tap profile- preferences- toggle off forced offline
12. Navigate to archived announce room of deleted workspace

## Expected Result:
In archived announce room, after workspace deleted,
all messages in offline sent must be displayed in a consistent same manner.

## Actual Result:
In archived announce room, after workspace deleted, in offline, the text message (without any markdown) send is greyed and displayed. But, text with strike through markdown send and deleted is shown in bold.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6208151_me](https://github.com/Expensify/App/assets/115492554/1db15574-45ac-48c6-89dc-c5e56e07b8dc) 

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011730f868b002e69c</li>
        <li>Upwork Job ID: 1706694421839835136</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Hey @izarutskaya, can you please share a recording so I can understand this issue better and try to recreate it? Thanks!

**Comment by isabelastisser** [comment]
Bump @izarutskaya please follow up on my question above. Thanks!

**Comment by izarutskaya** [comment]
Hi @isabelastisser, sorry for the waiting. My video:
iOS- 16.6.1/Safari
Build - v1.3.74-2

https://github.com/Expensify/App/assets/115492554/7d422210-b9bf-47e3-9054-e744d8011880

**Comment by isabelastisser** [comment]
Hey @fedirjh, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment]
@fedirjh, do you mean by assigning an internal engineer? Can you please elaborate? Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment]
Bump @mvtglobally

**Comment by isabelastisser** [comment]
Thanks @fedirjh ! Closing this.
