### ISSUE TITLE
Desktop - Uninstalled Desktop app and MacOS alert is showing every few hours

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Install staging desktop app
2. Uninstall staging desktop app by deleting app
3. Use NewApp via staging web
4. I believe every time we release a new web build, this large prompt will appear

## Expected Result:
I would not expect this prompt to appear

## Actual Result:
 Large MacOS prompt appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-18 at 3 52 01 PM (3)](https://github.com/Expensify/App/assets/93399543/675ddd44-d87c-4aeb-8a83-ab78edca0432)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695084889755779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
@AndrewGable I'm unclear how to reproduce this. When you have the desktop app installed, opening web pulls up a prompt to open the app on desktop. Are you seeing this large popup this what you're seeing when the desktop app has been uninstalled too?

When I uninstalled the desktop app, the website did not prompt me to open it in the desktop app. I am not getting the large prompt that you are

**Comment by AndrewGable** [comment]
> Are you seeing this large popup this what you're seeing when the desktop app has been uninstalled too?

Yes, this is what I was seeing

**Comment by AndrewGable** [comment]
I'm honestly not sure if this is worth keeping open, I think we can reopen it in the future if more users start complaining about this. I was able to follow a work around to edit chrome to stop doing this.
