### ISSUE TITLE
[$500] Web -  Split bill is not synchronized in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Use the same account and visit https://staging.new.expensify.com/ for two tabs
2. Click on any #announce
3. Click on FAB -> Split bill -> enter any numbers -> Next button -> Split button
4. Reload and observe the newly created Split bill on 2 tabs

## Expected Result:
Split bill will be synchronized on two tabs

## Actual Result:
Unable to synchronize Split bill in chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture.webm](https://github.com/Expensify/App/assets/93399543/63087b80-be5a-4c0b-9174-dc04234ef660)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1695179666160159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Linking similar KI https://github.com/Expensify/App/issues/27154

**Comment by adelekennedy** [comment]
does [this](https://github.com/Expensify/App/issues/27154) seem related @thesahindia?

**Comment by adelekennedy** [comment]
Bump on the question above @thesahindia

**Comment by adelekennedy** [comment]
Let's close in favor of that one
