### ISSUE TITLE
web - Request money - 'Invalid source' message in the console when requesting money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when executing #27868 
## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to + > Send message > Manual.
3. Enter any amount.

## Expected Result:
There is no 'invalid source' message in the console.

## Actual Result:
There is 'invalid source' message in the console.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4855b166-34b3-4200-a644-d18fbdcd8774

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Gonna close this, I tested and it doesn't affect the actual app functionality.
