### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Chat - Can't open context menu by long press on mentions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send a mention in chat
3. Long press on mention
4. Observe context menu doesn't popup

## Expected Result:
The context menu should popup using long press on mention.

## Actual Result:
The context menu does not popup using long press on mention.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/05082fa1-cdb9-4f8c-9cbf-5f8a2c458c76

https://github.com/Expensify/App/assets/93399543/1402c452-c18d-42dd-a86f-7502201297e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695192996432379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I agree @fedirjh , I'm not sure what context menu is being referred to here. Closing!

**Comment by MitchExpensify** [comment]
Thanks for following up! I also reproduced this like you described

**Comment by MitchExpensify** [comment]
Clarifying what is expected here https://expensify.slack.com/archives/C03U7DCU4/p1696285400796969

**Comment by MitchExpensify** [comment]
Confirmed long press on mentions should open the comment action menu

**Comment by MitchExpensify** [comment]
Waiting on proposal review from @fedirjh

**Comment by MitchExpensify** [comment]
Hows the further debugging going @fedirjh?

**Comment by MitchExpensify** [comment]
**Payment summary:**

$500 @fedirjh requires payment
$550 @Krishna2323 requires payment

**Comment by MitchExpensify** [comment]
New Upwork Job created for payment: https://www.upwork.com/jobs/~01cc618434de8e0915

**Comment by MitchExpensify** [comment]
Offers sent, lemme know when you accept them! Thanks

**Comment by MitchExpensify** [comment]
Paid and contracts ended!

**Comment by MitchExpensify** [comment]
Tests added! Thanks, everyone
