### ISSUE TITLE
Chat messages are posting days after I originally sent them

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. I sent several messages in my NewDot chat with Chronos on Thursday, Sept 14 (The messages I sent included `Help`, `Ooo help`, and a few others.
2. I saw the messages show up in the chat with a timestamp, but I didn't get responses from Chronos right away
## Expected Result: 
I either should have gotten responses from Chronos right away, or if I wasn't online, the app should have shown my messages at 50% opacity.
## Actual Result: 
Looking back at the chat, I can see that the messages no longer show up on the day I originally sent them, and now they show as posting over the next few days with a later timestamp. `Ooo help` was posted on Sept 17 and `Help` was posted on Sept 18.
I noticed this same behavior a week or two ago in another chat (either a group DM or an #admins chat), but thought I may have been imagining things.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (2)](https://github.com/Expensify/App/assets/43996225/64d8de23-5546-4d3a-92ee-5c98fabe754b)

![image (1)](https://github.com/Expensify/App/assets/43996225/5290a721-c7a3-4fbc-9c88-31c762df1037)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695028984668469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Happened to me too

**Comment by anmurali** [comment]
Aren't these associated with the range of performance issues we're working on? I cannot specifically reproduce this at any given point in time so I don't think it makes sense to create a bug report for it. @sakluger do you agree?

**Comment by mallenexpensify** [comment]
> I cannot specifically reproduce this at any given point in time so I don't think it makes sense to create a bug report for it.

It happened as recently as two weeks ago and it's happened to two of us, at least. I posted in[ the Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1696266849314999?thread_ts=1695028984.668469&cid=C049HHMV9SM) and shared with the #expensify-bugs room, let's see if anyone else has experienced this more recently

**Comment by anmurali** [comment]
Ok perhaps I can assign this to you to manage then @mallenexpensify cause it keeps going overdue in my queue and I am honestly not sure how we're going to reproduce it. Ideally, you reopen when you experience it and get someone to look in short order and maybe the logs will help them then.

**Comment by mallenexpensify** [comment]
Sounds good, I'll likely keep 👀 on it, not be able to repro then ????

**Comment by mallenexpensify** [comment]
Tried to do some testing, with no luck.  ie. sending messages then backgrounding app quickly.

**Comment by mallenexpensify** [comment]
Argh, only way I can think to test this is to be out n' about and sending a bunch of messages, like during offshore.  That's not likely to happen soon so I'll close for now
