### ISSUE TITLE
[Awaiting BugZero checklist and C+ newdot payment] [$500] Chat - Emoji reactions are not being displayed in order of who reacted first

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have multiple users react to a message
2. Observe that the reactions are not ordered based on who reacted first

## Expected Result:
Emoji reactions are ordered by timestamp so it shows all reactions in the correct order

## Actual Result:
Emoji reactions don't look to be ordered by the reaction timestamp at all.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-20 at 3 32 43 PM](https://github.com/Expensify/App/assets/93399543/73c47f84-49db-401b-b4ff-ba52020dc828)

![Screenshot 2023-09-20 at 4 29 24 PM](https://github.com/Expensify/App/assets/93399543/0f3c5d99-a064-4657-98b1-ebe37085d3b5)

![image](https://github.com/Expensify/App/assets/93399543/a7c36afd-c78f-4fbe-a163-87e2fe4adabb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MariaHCD 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695198351402179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164915b9cf8bed4bf</li>
        <li>Upwork Job ID: 1704949352333058048</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 27254185</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user reactions are not sorted by the reaction timestamp

### What is the root cause of that problem?
While sorting the reaction, we only sort them by one oldest timestamp, to determine the order of the emojis in the line. But we don't sort the users of each specific reaction.

https://github.com/Expensify/App/blob/9d23ffbeee01bf47edeb93c23a6bd9b2392fa5d0/src/components/Reactions/ReportActionItemEmojiReactions.js#L49-L72

### What changes do you think we should make in order to solve the problem?

We should modify this `sortedReactions` function a little in order to sort the users as well:

```js
const sortedReactions = _.sortBy(data, (emojiReaction, emojiName) => {
  // Since the emojiName is only stored as the object key, when _.sortBy() runs, the object is converted to an array and the
  // keys are lost. To keep from losing the emojiName, it's copied to the emojiReaction object.
  // eslint-disable-next-line no-param-reassign
  emojiReaction.emojiName = emojiName;

  const sortedUsers = _.sortBy(emojiReaction.users, (user, id) => {
    if (!user) {
      return false;
    }

    user.id = id;
    user.oldestTimestamp = Object.values(user.skinTones).sort()[0]
    return user.oldestTimestamp;
  })

  const oldestUserReactionTimestamp = sortedUsers[0].oldestTimestamp;

  emojiReaction.users = _.reduce(sortedUsers, (acc, user) => {
    acc[user.id] = _.omit(user, ['id', 'oldestTimestamp']);
    return acc;
  }, {})

  // Just in case two emojis have the same timestamp, also combine the timestamp with the
  // emojiName so that the order will always be the same. Without this, the order can be pretty random
  // and shift around a little bit.
  return (oldestUserReactionTimestamp || emojiReaction.createdAt) + emojiName;
});
```

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment]
@mollfpr please check these proposals!

**Comment by mollfpr** [comment]
>The list of usernames should go according by time

@ZhenjaHorbach Isn't the issue regarding the emoji order, not the username?

@kadiealexander Could you help confirm if the order should start from the oldest or the latest reaction?

**Comment by MariaHCD** [comment]
@mollfpr We want the reactions for the same emoji to be displayed by the reaction timestamp from the oldest to the newest.

**Comment by mollfpr** [comment]
Thanks @MariaHCD! I'll get the review to continue then.

**Comment by mollfpr** [comment]
@paultsimura I think your proposal is more focused on the order of each emoji instead of the order of the one emoji reacted by many users or skin tones.

<details>
<summary>Result from your solution</summary>

![Screenshot 2023-09-28 at 22 29 43](https://github.com/Expensify/App/assets/25520267/3982dd12-43ba-45d5-b37f-e506026ac2d7)

</details>

---

>    const sortedByTimestamp = _.sortBy(emojiCodesWithTimestamps, (item) => new Date(item.timestamp));

@Krishna2323 What is this variable for? I see that you edit your code, but it's never used.

Also, it still needs to be ordered from the oldest. The `-1` skin tone should be placed first.

![Screenshot 2023-09-28 at 22 38 26](https://github.com/Expensify/App/assets/25520267/956959e7-c550-4187-9e33-a07c33f8ada3)

**Comment by paultsimura** [comment]
@mollfpr I think you got it wrong. Mu solution does both in one take: sorts the emojis by their order among each other, **and** sorts the users that reacted within each emoji by their oldest timestamp.

If you check your screenshot, you can see that the `users` lost of each emoji is already sorted by timestamp.

**Comment by mollfpr** [comment]
@paultsimura But should the other consider the timestamp from the skin tone?

**Comment by paultsimura** [comment]
> @paultsimura But should the other consider the timestamp from the skin tone?

The skin tones are the only place where we have the timestamps of users reaction, aren't they?

**Comment by paultsimura** [comment]
The only tricky part is when one user has reacted with multiple skin tones. I have implemented to take into consideration the earliest reaction among those skin tone reactions.
The same logic is currently used to sort the different emojis among each other.

**Comment by mollfpr** [comment]
I'll get this review again in the morning.

**Comment by mollfpr** [comment]
Sorry, I didn't get a chance to review this. I'll get this done by tomorrow.

**Comment by mollfpr** [comment]
>(because we don't want to show one user twice)

Do you mean we don't show the same reaction from users with multiple skin tones? After thinking again, we can ignore my feedback earlier.

I did test your solution again with multiple users reacting to a message. The `sortedReactions` seems correct, ordering the users from the oldest emoji to which they reacted. But I couldn't get a better result because you need to update `formattedReactions` to make it work.

@paultsimura

**Comment by paultsimura** [comment]
@mollfpr I mean we do show all user's skin tone reactions (multiple skin tones from one user are displayed), but we don't show the user name in the list multiple times (for each skin tone):

<img width="175" alt="image" src="https://github.com/Expensify/App/assets/12595293/90b64b9e-66ee-48e3-a3e6-b8ecfd4618c7">


As for the updated `formattedReactions` – my bad, I will update my proposal with it. Tried to keep it as laconic as possible, but apparently that's a bad practice.

**Comment by paultsimura** [comment]
@mollfpr I have updated my proposal https://github.com/Expensify/App/issues/27961#issuecomment-1730347696, tried to make it as detailed as possible.
Also, added some important notes and improvements.

**Comment by paultsimura** [comment]
> Hey @paultsimura,
> 
> 
> 
> I've reviewed the recent changes in your proposal, and I noticed the usage of `getUniqueEmojiCodes` in your updates. If I recall correctly, that function was first presented in my initial proposal.
> 
> 
> 
> From my perspective, the modifications in both `ReportActionItemEmojiReactions` and `BasePopoverReactionList` seem to revolve around reusing logic. However, I believe the core of the issue can be addressed solely by altering the getUniqueEmojiCodes function, without needing to make changes to the other components.
> 
> 
> 
> 

Modifying `getUniqueEmojiCodes` does not solve the issue of displaying the users in a correct order, only the emoji icons, which I believe is only a partial solution for this issue.

**Comment by kadiealexander** [comment]
@mollfpr any updates here?

**Comment by mollfpr** [comment]
@Krishna2323 Your solution is only sorting the skin tones, but not with the user's name.

![Screenshot 2023-10-11 at 00 04 05](https://github.com/Expensify/App/assets/25520267/6f63714d-c8fb-4aba-a535-48be83454e2a)

The last three order user's name order should be `27961 Six`, `27961 Five` , and `27961 Four`.

**Comment by mollfpr** [comment]
@paultsimura I did copy-paste your diff and follow your suggestion change, but the user name's is not sorted.

![Screenshot 2023-10-11 at 00 24 14](https://github.com/Expensify/App/assets/25520267/5e31c294-1a94-4734-a883-5e45864d7625)

Here's the report action and user details.


![Screenshot 2023-10-11 at 00 15 25](https://github.com/Expensify/App/assets/25520267/58046850-b8e6-460d-a87c-f632e727cee2)
![Screenshot 2023-10-11 at 00 15 02](https://github.com/Expensify/App/assets/25520267/5bd0496b-0842-4a2e-bbca-a79fdea462b4)


Could you try your proposal with more than four users reacting?

**Comment by paultsimura** [comment]
@mollfpr you are right!

Updated [my proposal](https://github.com/Expensify/App/issues/27961#issuecomment-1730347696) with the last extra step now and attached the screenshots of users' ordering.

To test this easier, you can just clone my branch, as it is a lot of changes to copy-paste: https://github.com/paultsimura/Expensify/tree/fix/27961-emoji-ordering

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by paultsimura** [comment]
Just reproduced in Prod:

![image](https://github.com/Expensify/App/assets/12595293/69ff4715-44f7-4abb-8290-0d102c765786)

**Comment by kadiealexander** [comment]
@mollfpr any thoughts on https://github.com/Expensify/App/issues/27961#issuecomment-1755994407?

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

I tested the latest [proposal](https://github.com/Expensify/App/issues/27961#issuecomment-1730347696) from @paultsimura, and it seems to resolve the sorting problems on the skin tones and the user names reacting. 

<details>
<summary>Before</summary>

![Screenshot 2023-10-16 at 11 42 30](https://github.com/Expensify/App/assets/25520267/bba3b19e-b998-4c21-b6ab-385810aae5b2)
</details>


<details>
<summary>After</summary>

![Screenshot 2023-10-16 at 11 40 34](https://github.com/Expensify/App/assets/25520267/f7fc63f3-919b-4ba0-a6ba-ada246372b19)

</details>

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
@kadiealexander Could you help pull the internal engineer here? I guess because I've been removed from the team, the bot won't trigger the 🎀 👀 🎀

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by paultsimura** [comment]
> Issue not reproducible during KI retests. (Second week)

Reproducible:

![image](https://github.com/Expensify/App/assets/12595293/a7b38077-c9e5-4577-a6de-e78db7289632)

**Comment by lakchote** [comment]
Issue reproducible in prod. 

See discussion [here](https://expensify.slack.com/archives/C049HHMV9SM/p1697611818412919?thread_ts=1695198351.402179&cid=C049HHMV9SM).

@paultsimura's proposal LGTM. Thanks for reviewing @mollfpr.

**Comment by paultsimura** [comment]
The PR's ready for review: https://github.com/Expensify/App/pull/29846

**Comment by mollfpr** [comment]
Whoops, sorry for the ping @hoangzinh. Because I'm not on the team, Melvin won't recognize me 😅

**Comment by paultsimura** [comment]
Hey, @hoangzinh @mollfpr are we clear on who is eventually going to review the PR? 🙂 
And if it's going to be @mollfpr – do we need to request some re-assignment action from the Team?

**Comment by MariaHCD** [comment]
@mollfpr I think if you comment on the PR, we can assign you as the PR reviewer.

**Comment by lakchote** [comment]
@mollfpr can you identify the PR that caused the bug please? Thanks

**Comment by mollfpr** [comment]
@lakchote Sure!

**Comment by kadiealexander** [comment]
Payouts due:

Contributor: $500 + $250 bonus @paultsimura
Contributor+: $500 + $250 bonus @mollfpr

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/27961#issuecomment-1772225857)

Upwork job is [here](https://www.upwork.com/ab/applicants/1704949352333058048/hired).

**Comment by kadiealexander** [comment]
@mollfpr please don't forget about the checklist!

**Comment by mollfpr** [comment]
> The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't find any offending PR accidentally causing this issue, I believe this issue is a improvement from the previous logic where we don't track it in the first place.

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open the App
2. Send a message to a group chat
3. Make multiple (6+) users react with the same emoji (make sure some skin tones are different, and some - are the same)
4. Hover on the reaction bubble (or long-press on mobile)
5. Verify the reactions emoji are ordered by who reacted first
6. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mollfpr based on [this summary](https://github.com/Expensify/App/issues/27961#issuecomment-1784460916).

**Comment by lakchote** [comment]
@paultsimura @mollfpr @kadiealexander could you please complete the BugZero checklist [here](https://github.com/Expensify/App/issues/27961#issuecomment-1774426786)? Thanks

**Comment by mollfpr** [comment]
@lakchote Here's the checklist https://github.com/Expensify/App/issues/27961#issuecomment-1784537856

**Comment by kadiealexander** [comment]
Testrail GH: https://github.com/Expensify/Expensify/issues/334720
