### ISSUE TITLE
[$250] DEV: `CMD + C` does not show in Keyboard shortcuts modal immediately after login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account
2. Immediately after login and while the LHN is still skeleton, Press `CMD + J` to toggle Keyboard shortcuts modal
3. Observe that `CMD + C` is NOT there
4. Close the modal then re-open it
5. Observe that `CMD + C` is there
## Expected Result: 
`CMD + C` shows in Keyboard shortcuts modal immediately after login
## Actual Result: 
`CMD + C` does not show in Keyboard shortcuts modal immediately after login unless we open the modal again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** Dev
**Reproducible in production?:** Dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/75ca2e06-d738-4eb8-aca8-c0af23f7672c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695026209099819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a7cfe6708754ab2</li>
        <li>Upwork Job ID: 1706173740282531840</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27030222</li>
<li>tienifr | Reporter | 27030224</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal by #tienifr
### Please re-state the problem that we are trying to solve in this issue.
`CMD + C` does not show in Keyboard shortcuts modal immediately after login unless we reopened the modal.
### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/2b2bafd862bef999cf360d17e22535d48799c49f/src/components/KeyboardShortcutsModal.js#L44), we're getting the list of shortcuts to display, but we're using the method `KeyboardShortcut.getDocumentedShortcuts` which retrieves a static value `documentedShortcuts` from another file, so when `documentedShortcuts` is updated in the other file, we don't have any knowledge of it, so the UI is not updated.
So when new shortcuts are subscribed, for example in [here](https://github.com/Expensify/App/blob/2b2bafd862bef999cf360d17e22535d48799c49f/src/components/KeyboardShortcutsModal.js#L130), the UI is not updated.
### What changes do you think we should make in order to solve the problem?
We should create a listener that subscribes to `documentedShortcuts` changes:
- Add `shortcutsUpdateCallback` in `src/libs/KeyboardShortcut/index.js`
- In listener, assign `shortcutsUpdateCallback` to the callback from the modal
- When updating the `documentedShortcuts`, call the `shortcutsUpdateCallback` as well
- Add the listener to `useEffect` of the modal
It's just a few lines of additional changes, we already use the same listener approach in various places in the app (`ReportActionComposeFocusManager`, `Notification`, ...).
### What alternative solutions did you explore? (Optional)
We can also create a `useDocumentedShortcuts` for the above implementation in [here](https://github.com/Expensify/App/blob/2b2bafd862bef999cf360d17e22535d48799c49f/src/libs/KeyboardShortcut/index.js#L15) and use it instead of the `getDocumentedShortcuts`, when the `documentedShortcuts` changes (a shortcut is subscribed, unsubscribed), we'll update the state in the hook as well. Then use the hook in `KeyboardShortcutsModal`, this will make sure `KeyboardShortcutsModal` is always updated via hook with the latest value of `documentedShortcuts`.

**Comment by robertKozik** [comment]
Thank you for your proposal @tienifr!  I like your alternative solution which involves creating the hook for keyboardShortcuts value. This way, we would make it easily reusable in different places. I think it would be better and more inline with modern functional rn standards, so I would opt for this solution.

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Bump @cead22 to approve [this](https://github.com/Expensify/App/issues/27964#issuecomment-1733448476)!

**Comment by cead22** [comment]
I'm downgrading the bounty for this issue to $250 since the solution is relatively simple, and the bug isn't incredibly high value to fix in my opinion (but open to feedback). 

FYI @jliexpensify since you're handling payment

**Comment by cead22** [comment]
@tienifr can you please comment on this issue so I can assign you?

**Comment by jliexpensify** [comment]
@tienifr assigned!

**Comment by jliexpensify** [comment]
Not overdue, being worked on!

**Comment by jliexpensify** [comment]
Just curious what we're doing here @cead22, based off this [comment](https://github.com/Expensify/App/pull/28979#issuecomment-1759147716)?

Shall we compensate @tienifr $250?

**Comment by cead22** [comment]
👍

**Comment by jliexpensify** [comment]
Paid and job closed, thanks!
