### ISSUE TITLE
[HOLD for payment 2023-10-05] Improve performance of isConsecutiveActionMadeByPreviousActor

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27971]
### Problem

When profiling hermes I found that a lot of time was spent copying an array (array.slice). This was caused by the _.drop method we use.

![image](https://github.com/Expensify/App/assets/2677334/4274f1c7-dd22-47e9-bfeb-00b4ba8c49c5)

Since this method is actually called many times and the reportActions array can be very big this is slow. We can make it a lot faster by iterating in the array from the right index instead of making a copy.

This reduces the time spent copying the array (array.slice) to nothing since we no longer copy it.

**Comment by sophiepintoraetz** [comment]
@mountiny if there's action needed from me, can you please let me know? (i.e. if there's a payment, when and how much).

**Comment by mountiny** [comment]
of course, thanks! the PR hasnt hit production and I think the automation will update the issue for payment to the C+

**Comment by sophiepintoraetz** [comment]
Hmm, hasn't updated so I understand this to be a standard $500 for the review?

**Comment by sophiepintoraetz** [comment]
@mountiny - I'm headed OOO shortly so do I need to create an upwork job here [for $500]?

**Comment by mountiny** [comment]
Correct $500 for @aimane-chnaif thats it

**Comment by sophiepintoraetz** [comment]
Offer sent - @aimane-chnaif if you could accept ASAP please because i'm actually meant to be OOO now!

**Comment by sophiepintoraetz** [comment]
Hmmkay, I'm no longer able to get to this (should have been OOO on Friday). @flaviadefaria, I just need you to approve the payment in the offer ($500) for @aimane-chnaif once he's accepted it - link below!
https://www.upwork.com/nx/wm/offer/27068583

**Comment by flaviadefaria** [comment]
@aimane-chnaif can you please accept the offer so that we can consider this as done? Thank you!

**Comment by flaviadefaria** [comment]
Thanks! I just paid you so closing this.
