### ISSUE TITLE
[HOLD for payment 2023-10-02] Memoize expensive calls in ReportActionsList renderItem

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27972]
### Problem

Some of the operations we do in ReportActionsList renderItem are pretty expensive since this function is executed for every items in the render window every time the render window changes. To improve performance of FlatList scrolling we need to move any expensive computation inside a memoized component. This way when FlatList re-renders to display new items but the data did not change only the new rendered items will need to render.

We were already memoizing ReportActionItem, but renderItem still contains some expensive calls, specifically `isConsecutiveActionMadeByPreviousActor` which has to do some date comparisons. I moved those to a new component `ReportActionsListItemRenderer` which will prevent any re-renders coming from from FlatList for items that were already rendered. This reduces the number of calls to `isConsecutiveActionMadeByPreviousActor` from the number of currently rendered item (~100 depending on the FlatList window size) to just the new items being added (usually 10 since this is the batch size).

**Comment by mountiny** [comment]
merged

**Comment by mollfpr** [comment]
@mountiny @sonialiap I think there's nothing we can add to the BZ checklist.

**Comment by mountiny** [comment]
I agree, no need here for the checklist

**Comment by mollfpr** [comment]
@sonialiap I think I can request payment in NewDot for this issue.

**Comment by JmillsExpensify** [comment]
@sonialiap Can you please add a payment summary to this issue so I can pay?

**Comment by sonialiap** [comment]
Sorry for the delay, working 50% while trying to juggle the normal work load. 

Payment:
- @mollfpr review + time bonus = $750

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mollfpr based on BZ summary.

**Comment by mollfpr** [comment]
@sonialiap @JmillsExpensify Sorry to open this up. I just noticed that the request on the ND I did was requested and approved for $500, so there's there is a shortage in payment here. Could you help confirm it? Thank you!

**Comment by mollfpr** [comment]
Friendly bump @JmillsExpensify
