### ISSUE TITLE
[HOLD for payment 2023-10-02] Avoid re-render when no iouReport

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#27970]
### Problem

When there is no iouReport for a message `getIOUReportIDFromReportActionPreview` will return undefined which then gets added to the `ONYXKEYS.COLLECTION.REPORT`which then becomes `report_`. This causes onyx to return all reports and the value is not properly cached since it returns a new map for each call. This causes basically all `ReportActionItem` to render twice, once with iouReport undefined and then with iouReport set to a map of all reports. If we don't have a report id then we should not try to get a report from onyx for it so we can return undefined for the key and use {} for the default value. Messages with no iouReport will now only render once.

Before:

You can see here 1 / 2 render is an update to iouReport.

![image](https://github.com/Expensify/App/assets/2677334/7e29c4a2-3043-4b19-9b00-07e77ed4f7de)

After:

Now all ReportActionItem only render once.

![image](https://github.com/Expensify/App/assets/2677334/ab93acca-b120-44af-8796-c4d3232047d2)

**Comment by mountiny** [comment]
The checklist is not relevant in this case, not a regression but performance improvement

The only payment here is $500 to @situchan @adelekennedy are you able to help please?

**Comment by adelekennedy** [comment]
Sent offer to @situchan

**Comment by adelekennedy** [comment]
payment made!
