### ISSUE TITLE
Tracking issue for payment of #26586 ($1500) for @napster125

### ISSUE THREAD

**Issue by sophiepintoraetz** [Expensify/App#27976]
Tracking issue for payment of https://github.com/Expensify/App/issues/26586 for @napster125

**Comment by napster125** [comment]
Hi @sophiepintoraetz,
Thanks for creating the tracking issue.

**Comment by mallenexpensify** [comment]
@napster125 , can you please continue to get verified in Upwork? If you're able to, please comment in this issue and link your verified Upwork account.  Thx

**Comment by napster125** [comment]
@mallenexpensify Thanks for the update. This is the verified profile: `https://www.upwork.com/freelancers/~01bfd69d6e1c5de05c`

**Comment by napster125** [comment]
@mallenexpensify Any updates?

**Comment by sophiepintoraetz** [comment]
@napster125 - please do not bump us - you can see that there is a monthly priority to this and this is not our main focus. Realistically, we are working around some legal nuance given that the original profile was not validated, this did create complications for us. We will reach out when we have an update.

**Comment by napster125** [comment]
@sophiepintoraetz I understand that you're currently occupied with your project. However, I believe you have the option to conclude the contract without releasing any funds on the old Upwork account and then send a new offer using the valid URL I proposed. I'm simply curious about what's causing any concerns in this situation.

**Comment by napster125** [comment]
@mallenexpensify Thanks for the update.
This is the verified profile and please send it here: https://www.upwork.com/freelancers/~01564d5fb5dd2f7ad1.
Thank you.

**Comment by napster125** [comment]
@sophiepintoraetz @mallenexpensify The month is already gone by.

**Comment by sophiepintoraetz** [comment]
@napster125 - unfortunately, we are in a legal black hole here so this will take some time. I think it would do you good to remember you created this situation by applying for a job with an unverified profile - so we are doing this as an act of generosity. We'll let you know when we have an update.

**Comment by sophiepintoraetz** [comment]
Hi @napster125 - unfortunately, we do not have good news. We've been conferring with Upwork's lawyers but a part of our contract has an anti-competitive clause in that we cannot pay contributors outside of Upwork for 18 months after their first hire. We pushed back on this, seeing as they allowed us to hire without a fully vetted profile but they have not been flexible (hence the delay). This means that we will still pay you, via New Dot, but we cannot do so until 18 months has passed.

I'm sorry we don't have better news here. Your options are:
1) Keep trying to get your profile verified to get paid sooner
2) Wait until 18 months so that we can hire you through new dot (12 March 2025)

Matt and I should still be around, so you can ping us on this issue here or email contributors@expensify.com. I'm going to set a reminder to revisit this on 12 March 2025.

**Comment by sophiepintoraetz** [comment]
![image](https://github.com/Expensify/App/assets/42940078/3e804460-14d4-48df-b675-525b95a6787e)
