### ISSUE TITLE
[$500] `chat` thread report header is incorrectly showing the "root" report in second line rather than the "parent" report. 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27986]
Reproduction steps
1. Comment in a parent report (e.g. root report)
2. Create a thread on your comment in the parent/root (e.g. thread1)
<img width="779" alt="Screenshot 2023-09-22 at 14 09 58" src="https://github.com/Expensify/App/assets/1127863/09885ba9-2e2c-4a0d-ba2a-1cf2d79e9e04">
3. Confirm that in the  header for thread1 shows the name of the parent/root report.
<img width="812" alt="Screenshot 2023-09-22 at 14 10 29" src="https://github.com/Expensify/App/assets/1127863/7fcf2791-eeb1-4e9e-a889-9b748d1e3cd4">
4. Now create another thread on your comment in thread1 (e.g. thread2)
<img width="833" alt="Screenshot 2023-09-22 at 14 14 24" src="https://github.com/Expensify/App/assets/1127863/52a392f5-b20d-4a2d-b7fd-8bcc0f171d69">
5. Notice that the header of thread2 incorrectly shows the root report in the second line of the header, which is incorrect. The second line should instead show thread1, which is the parent of thread2. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014565dfd91b80271a</li>
        <li>Upwork Job ID: 1706507483408605184</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Originally [reported internally](https://expensify.slack.com/archives/C03U7DCU4/p1695251248823359) in Slack.

**Comment by kevinksullivan** [comment]
Just checked in on the thread and moving this forward

**Comment by chiragsalian** [comment]
Jason or georgia can correct me but i think this is the current expected behavior i.e., the subheader shows root report name or parent expense/IOU report name, whichever comes first while traversing through parents. The same logic is applied for DM, group DMs and policy rooms.

If we want to change it, its a new feature request and IMO we would want to predesign it to land on a consistent design across DM, group DMs and policy rooms.

**Comment by kevinksullivan** [comment]
Agree with @chiragsalian here
