### ISSUE TITLE
[HOLD for payment 2023-10-17] Speedup getOrderedReportIDs by comparing strings instead of Dates objects

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28001]
### Problem

For some reason creating Date object is super slow on Hermes. So @janicduplessis came up with the idea to compare strings instead. It will generate a different output but the error is only under 1s. The reason for that is that milliseconds representation can has different length. 
<img width="294" alt="Screenshot 2023-09-22 at 11 41 52" src="https://github.com/Expensify/App/assets/12784455/015655ec-37ea-4637-87a7-b14bf0f4a3d2">

Using this solution:
 
the method now runs under 1s instead of 14s (when starting heavy accounts

**Comment by miljakljajic** [comment]
Payment summary: $500 to @allroundexperts for internal review and testing

@allroundexperts please request payment in newDot!
