### ISSUE TITLE
[$500] Android - Report is trimmed in report header in Android despite there is enough space

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28017]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any task report
3. Observe the From: ... field in the report header

## Expected Result:
The from link should be displayed in the entire available space and the characters that exceed the space are trimmed

## Actual Result:
The from field is trimmed despite there is available space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_2023-09-20-13-24-37-093_com expensify chat](https://github.com/Expensify/App/assets/93399543/afd7f561-3671-4294-8c77-a2c684a189fb)
![Screenshot_20230922_095429_New Expensify](https://github.com/Expensify/App/assets/93399543/e1aaccd4-7e8b-44b2-8b6b-466f45513661)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695213459270619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f049fcf2458d3984</li>
        <li>Upwork Job ID: 1705219742333894656</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment]
Dube of this https://github.com/Expensify/App/issues/24339

**Comment by NicMendonca** [comment]
thanks @pradeepmdk! closing
