### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] The phone number is displayed twice when searching for it after sending a Money Request.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to any account.
2. Send a Money Request to a phone number, for example: [+15005550006](tel:+15005550006).
3. Click on the Search icon in the header and search for that phone number - FULL SEARCH ([+15005550006](tel:+15005550006)) - IMPORTANT.

## Expected Result: 
The phone number is displayed ONCE.
## Actual Result: 
The phone number is displayed TWICE.
Note: This issue actually occurs on all types of search pages: Request Money, New Chat, and Inviting a Member to the Workspace.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b69137f0-1457-41ee-93f8-f6e85c002d21

https://github.com/Expensify/App/assets/43996225/7656adbe-df43-4af4-b2e0-b47fc65a1a72

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695047570703519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f217b41585e6a18d</li>
        <li>Upwork Job ID: 1705249513796894720</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26935042</li>
<li>tranvantoan-qn | Reporter | 26935044</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
The phone number is displayed twice when searching for it after sending a Money Request. 

### What is the root cause of that problem?
![Screenshot 2023-09-22 at 10 13 33 PM](https://github.com/Expensify/App/assets/16595846/d9446a35-0fde-4994-a4c3-1a1a703e4ba5)
personal details login don't have the domain 
but when we in the search personal details we are searching with 
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/libs/OptionsListUtils.js#L1154
`addSMSDomainIfPhoneNumber`
### What changes do you think we should make in order to solve the problem?
we need change like this
    const noOptionsMatchExactly = !_.find(personalDetailsOptions.concat(recentReportOptions), (option) => addSMSDomainIfPhoneNumber(option.login) === addSMSDomainIfPhoneNumber(searchValue).toLowerCase());
`Result`
![Screenshot 2023-09-22 at 10 19 07 PM](https://github.com/Expensify/App/assets/16595846/76762dcb-4f2c-4580-9b36-a236e3e2cee4)

**Comment by rojiphil** [comment]
Isn't this intentional behavior?

**Comment by tranvantoan-qn** [comment]
I dont think it is intended, because:
- It only happens if we had a money request to that number
- It only happens with full-keyword search - +15005550006
![26CD02F4-1BE3-4CC2-BFFC-A11C44DCE39D](https://github.com/Expensify/App/assets/10254571/8ad8d40f-6c50-486c-9593-d3c2fbe34670)

**Comment by pradeepmdk** [comment]
![Screenshot 2023-09-23 at 11 37 39 AM](https://github.com/Expensify/App/assets/16595846/5d698c2a-a94e-4944-96e1-3b63a2b69726)
![Screenshot 2023-09-23 at 11 39 17 AM](https://github.com/Expensify/App/assets/16595846/c3cb43d1-c392-4aa5-a5df-0e5e44e718b6)
![Screenshot 2023-09-23 at 11 41 00 AM](https://github.com/Expensify/App/assets/16595846/5e7a799b-e391-4f74-9195-8c016090cec9)

@dukenv0307 I think if we remove the personal details from success or failure it will create the regression.

**Comment by narefyev91** [comment]
Coming from here https://github.com/Expensify/App/issues/21706 - it was the same issue which we see here - after creating a request money - we store optimistic data in onyx - but do not clean it after getting correct data from API
Proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/28028#issuecomment-1732210716
🎀 👀 🎀 C+ reviewed

**Comment by pradeepmdk** [comment]
@narefyev91 did you able to check my comment. it will create regression if we removed the data from onyx

**Comment by pradeepmdk** [comment]
@dukenv0307 already shared the screenshot. In the failure cause we don't have personal information  from api(for all the scanrio request money, new chat, workspace invite ). And also requestmoney api not return full data of person al details here.

**Comment by pradeepmdk** [comment]
@dukenv0307 please check that https://github.com/Expensify/App/issues/21706 issue  PR https://github.com/Expensify/App/pull/24355/files they are fixing in the open report api on the account ID conflict  issue.

if you removed the personal details from Onyx how you can retrieve personal information to show the error message?
here 
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/pages/workspace/WorkspaceMembersPage.js#L271

**Comment by pradeepmdk** [comment]
> I think it's expected. The full-detail personal won't be returned until the receiver sends a message. 

then why workspace invite api return full details?

**Comment by pradeepmdk** [comment]
> Why is there no existing account store personnel in Onyx???.
if you removed from Onyx data on failure how many personal details will there? and also this issue will occur when we create a new chat with a person, not an existing one.

and this issue https://github.com/Expensify/App/issues/21706 is fixing only the conflict of accountId. not completely remove the onyx data when we stored the data on `optimistic`

**Comment by pradeepmdk** [comment]
> This issue removes optimistic personal detail data by setting it as null. Please see the PR for more details. 

in this final  PR of that ticket https://github.com/Expensify/App/pull/24355/files 
they are only setting null personal details is not there and they are doing the open report api.
` settledPersonalDetails[accountID] = allPersonalDetails[accountID] || null;`

> Invite flow has nothing to do with removing personal details when requesting money

I thought we were going to invite the scenario also because in this issue actual result is this: 
>The phone number is displayed TWICE.
Note: This issue actually occurs on all types of search pages: Request Money, New Chat, and Inviting a Member to the Workspace.


I am sharing the screenshot current scenario only. they all are working based on personal details. if we removed the personal details this will break.

Let we can wait internal team review.

**Comment by kadiealexander** [comment]
@madmax330 bump on this!

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $50 @tranvantoan-qn 
Contributor: $500 @dukenv0307

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/28028#issuecomment-1747237954)

Upwork job is [here](https://www.upwork.com/jobs/~01f217b41585e6a18d).

**Comment by kadiealexander** [comment]
@narefyev91 please don't forget the checklist!
