### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Request money flow is not proceeded to the next page

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#28022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26520
## Action Performed:

1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Change to the Distance tab.
4. Add waypoints.
5. When the submit button is enabled, Hit Enter on the keyboard.

## Expected:
Pressing Enter should submit the Distance request.

## Actual:
Enter key submission does not work on Distance Page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b26859d3-d24c-41e0-818e-41720dcadddf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126a0498c5bbce06a</li>
        <li>Upwork Job ID: 1705231943999688704</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
related https://github.com/Expensify/App/issues/26588

**Comment by dylanexpensify** [comment]
thanks @parasharrajat, updated! @eVoloshchak let's get the proposal reviewed please!

**Comment by dylanexpensify** [comment]
Bump!

**Comment by eVoloshchak** [comment]
@parasharrajat's [proposal](https://github.com/Expensify/App/issues/28022#issuecomment-1732990468) looks good to me!
I think we should also apply the same fix to [MoneyRequestConfirmationList/SettlementButton](https://github.com/Expensify/App/blob/52b1e3e9abaabdaf79c0eeafef5665292cf2ab9c/src/components/MoneyRequestConfirmationList.js#L365), it's the last step of request money flow and it also cannot be submitted by pressing enter

**Comment by eVoloshchak** [comment]
@parasharrajat's https://github.com/Expensify/App/issues/28022#issuecomment-1732990468 looks good to me!
I think we should also apply the same fix to [MoneyRequestConfirmationList/SettlementButton](https://github.com/Expensify/App/blob/52b1e3e9abaabdaf79c0eeafef5665292cf2ab9c/src/components/MoneyRequestConfirmationList.js#L365), it's the last step of request money flow and it also cannot be submitted by pressing enter

🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
Waiting for deploy!

**Comment by Victor-Nyagudi** [comment]
Including this issue, https://github.com/Expensify/App/issues/29132, here since it also arises from the <kbd>Enter</kbd> key functionality and its role in navigation.

Could be a possible regression. Could be nothing. 

Either way, I thought it good to mention it.

**Comment by dylanexpensify** [comment]
Bump @parasharrajat

**Comment by dylanexpensify** [comment]
@parasharrajat any update here? 🙇‍♂️

**Comment by dylanexpensify** [comment]
Bump @parasharrajat

**Comment by eVoloshchak** [comment]
Not overdue, PR with the regression fix was deployed to staging today

**Comment by eVoloshchak** [comment]
Not overdue, [PR is in production](https://github.com/Expensify/App/pull/30259#issuecomment-1784640750)

**Comment by dylanexpensify** [comment]
@eVoloshchak thanks for the update!

**Comment by eVoloshchak** [comment]
Not overdue, PR with the fix was deployed to prod on Oct 30

**Comment by dylanexpensify** [comment]
Should be good now?

**Comment by dylanexpensify** [comment]
@eVoloshchak to confirm

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26606. However, I don't think we can call this a regression, the PR description specifically states that `Now this means you cannot use Enter to submit the Distance request, however, its a new feature and its going to be used in mobiles right now mainly so this is fine.`
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here

**Regression Test Proposal**

1. Open the app.
2. Click on the FAB button > Request Money.
3. Select the Manual Tab.
4. Enter an amount.
5. Press Enter on the keyboard.
6. Verify that you are navigated to the next step (contact selector)

**Do we agree 👍 or 👎**

Also noting that this has caused a regression in https://github.com/Expensify/App/issues/29051

**Comment by dylanexpensify** [comment]
Payment summary: 
- Contributor: @parasharrajat $250
- Contributor+: @eVoloshchak $250

Please apply in Upwork or create a NewDot request!

**Comment by JmillsExpensify** [comment]
$250 payment approved for @eVoloshchak based on the comment above.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
