### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500]  I cursor not displayed on profile error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28030]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->upload invalid format image or more then 6mb image
3. App will display error below profile pic
4. Hover and try to select the error, observe that app displays normal cursor and does not allow to select the error
5. Similarly try on error in new contact method i.e. add a new contact method and insert wrong code
6. Hover and observe that it displays I cursor which is correct and allows to select the error (all other errors throughout app displays I cursor and allows to select the text)
## Expected Result: 
App should display I cursor over errors and allow to select and copy the text
## Actual Result: 
Profile pic error displays normal cursor and does not allow to select and copy the text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3ea900ca-ae56-400e-9b68-05246b8cbfb5

https://github.com/Expensify/App/assets/43996225/8d5fe6c8-4512-43c6-9437-e602d1196c43

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695035097969079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e242f576582d3c21</li>
        <li>Upwork Job ID: 1705250624405737472</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26936356</li>
<li>Dhanashree-Sawant | Reporter | 26936357</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
On Profile error instead of text cursor it is showing default cursor.
### What is the root cause of that problem?
We are not setting cursor style on the error message
### What changes do you think we should make in order to solve the problem?
Just need to pass this style (styles.cursorText)
https://github.com/Expensify/App/blob/f39184e371fa18c832db93071bc6a03e75bf48e2/src/components/AvatarWithImagePicker.js#L361-L368
which would look like
```javascript
   {this.state.validationError && (
                    <DotIndicatorMessage
                        style={[styles.mt6, styles.cursorText]}
                        messages={{0: this.props.translate(this.state.validationError, this.state.phraseParam)}}
                        type="error"
                    />
                )}
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment]
Unassigning TRJ as I'm the first B0 member assigned

**Comment by jliexpensify** [comment]
Hi @robertKozik can you review this one? We have a few proposals that re 5 days old. Thanks!

**Comment by robertKozik** [comment]
Hi all! Sorry for keeping you waiting! 🙇🏼 
I think the correct root cause is provided by @dukenv0307. Other solutions which constist of passing additional styles are only workarounds. The problem described in this issue can be found across every screen with ScrollView imported from `react-native-reanimated`. Changing it to `react-native` import gets rid of this problem, as suggested by @dukenv0307 proposal&solution. 

Selected Proposal: https://github.com/Expensify/App/issues/28030#issuecomment-1731786879

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Should a payment bonus be paid out to @dukenv0307 here? I looked at the PR and it was submitted on the 29th, but didn't get reviewed until the 5th. If it was reviewed same day, it would have qualified cc @thienlnam for your thoughts

**Comment by thienlnam** [comment]
I believe we should only allow exceptions if the internal engineer approved late without any changes required - in this case since it was the C+ that was delayed no bonuses would be sent out

**Comment by robertKozik** [comment]
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **Cannot determine one PR which introduced this. It was rather missed during implementation process (importing ScrollView from `reanimated` rather then `react-native`). It occurs in several places.**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think regression test is needed here**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter: @dhanashree-sawant $50
- Contributor: @dukenv0307 $500
- C+: @robertKozik invoiced payment

[Upwork job](https://www.upwork.com/jobs/~01e242f576582d3c21)

**Comment by jliexpensify** [comment]
Paid and job closed!
