### ISSUE TITLE
[HOLD for payment 2023-11-06] [$1000] Web - Profile - Atachment clip icon is displayed instead of spinner when avatar is loading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28036]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to [https://26772.pr-testing.expensify.com/.](https://26772.pr-testing.expensify.com/)
2. Go to Settings > Click on the avatar.
3. Upload an image for avatar using the image attached (any image will do actually).
4. Click on the avatar > View photo.

## Expected Result:
When the avatar is loading, a spinner will be shown.

## Actual Result:
When the avatar is loading, an attachment clip icon is displayed instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-9 PR:26772

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/89bc2ded-b962-4084-a083-39590b3e2ca9

![Bug6210425_dora-the-explorer-button-1644971517488](https://github.com/Expensify/App/assets/115492554/b130e784-7f59-450d-8baa-b3782d15ff2f)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01117548f1220d1a72</li>
        <li>Upwork Job ID: 1706703351401648128</li>
        <li>Last Price Increase: 2023-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27284678</li>
<li>mkhutornyi | Contributor | 27284682</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Issue found when testing this PR #26772

**Comment by jasperhuangg** [comment]
@izarutskaya can we verify that this bug is reproducible on staging? I don't think we should be blocking deploy on something that we haven't verified happens on staging.

**Comment by jasperhuangg** [comment]
Gonna remove the `Deploy Blocker` label until it's verified on staging.

**Comment by favourch** [comment]
Kindly assign this to me.

**Comment by favourch** [comment]
Contributor detaila
Expensify account email: fchukwuedo+1@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/favourch

**Comment by favourch** [comment]
Contributor details
Your Expensify account email: [fchukwuedo+1@gmail.com](mailto:fchukwuedo+1@gmail.com)
Upwork Profile Link: https://upwork.com/freelancers/favourch

**Comment by johncschuster** [comment]
@favourch we don't assign issues without first receiving a proposal. Can you please follow the [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) around that? Thanks!

**Comment by jasperhuangg** [comment]
Still waiting on proposals

**Comment by jasperhuangg** [comment]
@situchan Can you verify that it's reproducible on staging/production still?

**Comment by situchan** [comment]
verified still reproducible on latest staging


https://github.com/Expensify/App/assets/108292595/b90d7eeb-f2c0-4607-b49d-3886182020fe

**Comment by jasperhuangg** [comment]
@favourch If you're interested in fixing this issue, please provide a proposal with our [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md). Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
Great!

**Comment by situchan** [comment]
Still reproducible on new account

https://github.com/Expensify/App/assets/108292595/7ff69e04-4366-4cf3-89cc-dbeb4deb0488

**Comment by johncschuster** [comment]
Bumping Slack for more proposals.

**Comment by johncschuster** [comment]
Also doubling the bounty

**Comment by situchan** [comment]
That's correct. The proposal was posted on Sep 24

![Untitled](https://github.com/Expensify/App/assets/108292595/48027307-fbfe-4e23-ad93-2432e40b711c)

**Comment by situchan** [comment]
For the duplicated issue, we usually close latter one.

**Comment by situchan** [comment]
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/28036#issuecomment-1765250730) looks good to me.
`originalFileName` is just optimistic value, not saved in server.
🎀 👀 🎀 C+ reviewed

**Comment by johncschuster** [comment]
Assigned!

**Comment by johncschuster** [comment]
I agree with you @fedirjh. Let's keep this issue open and close the other one.

**Comment by johncschuster** [comment]
### Payment Summary:
_This issue is eligible for an urgency bonus. It was created before the announcement removing the urgency bonus on Oct 24._
PR created on Oct 20
PR approved on Oct 20

@mkhutornyi requires payment [offer](https://www.upwork.com/nx/wm/offer/27284682) (Contributor) - $1500 - `PAID`
@situchan requires payment [offer](https://www.upwork.com/nx/wm/offer/27284678) (Reviewer) - $1500 - `PAID`

**Comment by johncschuster** [comment]
@situchan, can you complete the BZ checklist when you get a moment? Thank you!

**Comment by johncschuster** [comment]
@situchan bump!

**Comment by situchan** [comment]
Finding offending PR. Will complete checklist by Monday

**Comment by johncschuster** [comment]
@situchan were you able to find the offending PR?

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20365
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20365/files#r1402017696
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is minor glitch and doesn't affect user previewing attachment so no need regression test. Also this was caught by Applause team

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
@situchan bump!

**Comment by situchan** [comment]
@johncschuster is there anything pending from me?

**Comment by situchan** [comment]
Here's [checklist](https://github.com/Expensify/App/issues/28036#issuecomment-1822739637)
