### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Web -  Send message screen - User navigates to Room tab when drag to select e-mail from Chat tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB button
3. Select Send message from dropdown
4. Put random e-mail in the input field
5. Try to select part of the e-mail by dragging

## Expected Result:
The e-mail address should be easily highlighted

## Actual Result:
User navigates to Room tab when drag to select e-mail from Chat tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d5af05dc-3577-4d68-86ed-a117206aecaf

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013efbb12cd17aad2f</li>
        <li>Upwork Job ID: 1705746404787040256</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26877122</li>
<li>akinwale | Contributor | 26877123</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When attempting to select the email address in the text input of the Chat tab, the tab swipes to show the Room tab.

### What is the root cause of that problem?
Attempting to swipe or drag anywhere on the tab screens results in a swipe action which will change the current tab, regardless of the focused or active control.

### What changes do you think we should make in order to solve the problem?
Add a PanResponder to the target control in order to handle the swipe action and prevent the tab from swiping. This can be added to a wrapper View for the text input control in `BaseOptionsSelector`.
```
const panResponder = PanResponder.create({
    onMoveShouldSetPanResponder: () => true,
    onPanResponderTerminationRequest: () => false,
});
...
<View {...panResponder.panHandlers}>
  <TextInput
      ...
  />
</View>
```

Since this will also affect the text input on the Room tab, we can create a lib file that defines the pan responder and then wrap each of the affected text inputs with a View that uses the pan responder's handlers.

### What alternative solutions did you explore? (Optional)
None.


https://github.com/Expensify/App/assets/4160319/8204228e-edba-459b-a07d-fb58ab125873

**Comment by mollfpr** [comment]
>Please re-state the problem that we are trying to solve in this issue.
Web - Send message screen - User navigates to Room tab when drag to select e-mail from Chat tab

@ginsuma Please don't just copy the title to re-state the problem. Your solution is not fixing this issue; we still want to be able to navigate the tab with a swipe on all platforms.

**Comment by mollfpr** [comment]
@akinwale Your proposal looks good. We already have the same pan responder in the `MapView`. For better understanding, could you explain more about the combination of `onMoveShouldSetPanResponder` and `onPanResponderTerminationRequest` fixing the issue?

**Comment by akinwale** [comment]
@mollfpr 

`onMoveShouldSetPanResponder` is triggered when there is any movement gesture on the control either horizontally or vertically. Setting it to true enables the view which has the handler set to become the responder for the move gesture. In this case, since we set the pan handler for the wrapper view, it starts to handle the move gesture, instead of the parent tab view which does the swiping.

`onPanResponderTerminationRequest` deals with the parent view intercepting or interrupting the current gesture being handled. This could happen in empty areas of the view handling the gesture. Empty areas meaning the parts of the view that don't have any text content or subviews that can be interacted with. When the movement gesture gets to this empty area, the view's gesture handling is terminated, and the parent takes over, unless we set the termination request to return `false`.

Hope that makes sense.

**Comment by mollfpr** [comment]
Thanks @akinwale!

The [proposal](https://github.com/Expensify/App/issues/28047#issuecomment-1732206570) from @akinwale looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by puneetlath** [comment]
Should we udpate our text inputs to work like this more generally? Is there ever a scenario where we want this swipe gesture to work when swiping within a text input?

**Comment by akinwale** [comment]
> Should we udpate our text inputs to work like this more generally? Is there ever a scenario where we want this swipe gesture to work when swiping within a text input?

This only really affects text inputs that are used within swipeable tabs, so maybe we could have a separate component called SwipeInterceptTextInput (or a better name?), which can be used in these scenarios. The root view of the component would have the necessary pan handlers set up.

**Comment by puneetlath** [comment]
>This only really affects text inputs that are used within swipeable tabs

That makes sense. Would there be a downside of adding this swipe intercept code to all TextInputs anyways?

**Comment by akinwale** [comment]
> > This only really affects text inputs that are used within swipeable tabs
> 
> That makes sense. Would there be a downside of adding this swipe intercept code to all TextInputs anyways?

I can't say for sure. In `BaseTextInput` there is a wrapper view around `RNTextInput`, so maybe we could (conditionally?) add the panhandlers to that instead.

https://github.com/Expensify/App/blob/3e9fdf6f70bdfd9366ffa6bbedfe80d66f683d89/src/components/TextInput/BaseTextInput.js#L282-L285

So essentially create a new prop `interceptsSwipe` and when it's true add the pan handler to the View.

**Comment by puneetlath** [comment]
I like that approach. What do you think @mollfpr?

**Comment by mollfpr** [comment]
Yup, I agree with making the component generic in case we have a similar case happen.

**Comment by puneetlath** [comment]
Great, let's do it.

**Comment by akinwale** [comment]
@mollfpr My [PR](https://github.com/Expensify/App/pull/28240) is ready for review. Thanks.

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

- External issue reporter - Applause N/A 
- Contributor that fixed the issue - @akinwale payment issued in Upwork $500
- Contributor+ that helped on the issue and/or PR - @mollfpr please accept offer in Upwork, payment owed $500

Please update the checklist steps above so we can close out. Thanks!

**Comment by akinwale** [comment]
@laurenreidexpensify Could this be considered eligible for the speed bonus? There was a delay with merging the PR. Thanks.

cc @puneetlath

**Comment by mollfpr** [comment]
> [@akinwale / @mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@akinwale / @mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. The issue arises when implementing the slide tab navigation, but we improve our `TextInput` component to ignore swiping the tab inside the text input.

> [@akinwale / @mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This should be a one time bug, the regression step should be enough.

>[@akinwale / @mollfpr] Determine if we should create a regression test for this bug.
 [@akinwale / @mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


_Precondition: the account should be in beta or at least can create a room chat._

1. Launch Expensify
2. Open the global create menu and select Send message
3. Enter an email address in the text input in the Chat tab
4. 
    - On the web and desktop, verify that attempting to select the text in the text input does result in a swipe to the Room tab.
    - On native iOS, verify that when the text is in selection mode, dragging the text selection handles does not result in a swipe to the Room tab.
    - On native Android, verify that when the text input is focused, dragging within the text input does not result in a swipe to the Room tab.
5. Switch to the Room tab.
6. Enter some text for the room name.
7. Run the same verifications for step 4 with the room name input.

**Comment by mollfpr** [comment]
@laurenreidexpensify Could you confirm if we are eligible for the speed bonus? Thanks!

**Comment by laurenreidexpensify** [comment]
@puneetlath do you agree this is eligible for the speed bonus?

**Comment by puneetlath** [comment]
Yes, that seems fair given me accidentally not merging after approving.

**Comment by laurenreidexpensify** [comment]
Updated Payment Summary:

- External issue reporter - Applause N/A
- Contributor that fixed the issue - @akinwale payment issued in Upwork $500 + 50% bonus = $750 
- Contributor+ that helped on the issue and/or PR - @mollfpr please accept offer in Upwork, payment owed $500 + 50% bonus = $750

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mollfpr based on summary above.
