### ISSUE TITLE
[$500] [Awaiting Payment]2FA login - Error message shows incorrect 2FA code when incorrect recovery code is used

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/23390

## Action Performed:
Precondition:
- User has set up 2FA and saved the recovery codes.
- User has previously used one of the recovery codes.

1. Go to login page.
2. Enter email and magic code.
3. Click Use recovery code.
4. Use the recovery code that has already been used before.
5.Click Sign in.

## Expected Result:
The error message mentions incorrect recovery code.

## Actual Result:
The error message mentions two-factor authentication code instead of recovery code.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be413281-1405-45cf-80ff-980cbbe94a4c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695308760173509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011dfd59ea4353f356</li>
        <li>Upwork Job ID: 1711516319487270912</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@alitoshmatov @abdulrahuman5196 @MonilBhavsar Seems like a regression from your PR? 

I dont think this is that important though to be a blocker, its not blocking user from logging in and also its rare to use recovery code and the one you have already used. Demoting to a bug and we should fix this probably as a regression from the PR

**Comment by alitoshmatov** [comment]
@mountiny This error message is sent from the backend for used recovery code, also the same api is used to verify 2fa code and recovery code. Noticed it in original PR but forgot to mention it.

**Comment by MonilBhavsar** [comment]
@joaniew 

In olddot, error message looks like 

<img width="369" alt="Screenshot 2023-09-27 at 10 45 07 AM" src="https://github.com/Expensify/App/assets/32012005/978efd9a-1e37-4721-96d8-56c216338915">

And in newDot, I propose to use the following - 

<img width="860" alt="Screenshot 2023-09-27 at 10 47 49 AM" src="https://github.com/Expensify/App/assets/32012005/13d91eee-9b96-4bab-9ae6-87c7d020b001">
<img width="866" alt="Screenshot 2023-09-27 at 10 48 01 AM" src="https://github.com/Expensify/App/assets/32012005/672e06e7-93fa-4e45-844a-cf7de03e4bc4">

Could you please confirm. Thank you! cc @srikarparsi

**Comment by joaniew** [comment]
@MonilBhavsar I'm a bit confused what you're proposing.. just want to double check - you're showing a version with the authenticator and one version with the recovery code?

Where it says `Please enter a valid two-factor authentication or recovery code` - do we want to specify so that when it's the authenticator, you only see the authenticator copy? eg. it says `Please enter a valid two-factor authentication code`

For recovery code: `Please enter a valid recovery code`

I think that specification is nicer

**Comment by MonilBhavsar** [comment]
> I think that specification is nicer

That's a good point 👍 
For oldDot, it was same error for both 2FA and recovery code. I think we can differentiate the error based on length of code

**Comment by MonilBhavsar** [comment]
PR is deployed to prod. @puneetlath assigning you the issue as you were assigned as a part of Bugzero team.
We need to pay bug reporter @ayazhussain79
Everything else was internal

**Comment by ayazhussain79** [comment]
@MonilBhavsar commented for reporting bonus

**Comment by puneetlath** [comment]
Upwork seems to be having issues. Will try again later.

**Comment by puneetlath** [comment]
@ayazhussain79 sent you an offer.

**Comment by ayazhussain79** [comment]
@puneetlath offer accepted, Thank you

**Comment by puneetlath** [comment]
All paid!
