### ISSUE TITLE
Android - BA - “Connect with Plaid” is always launched twice

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Android App
2. Login with Expensifail account
3. Go to existing workspace or create new one
4. Go to Workspace > Bank account > Connect online with Plaid
5. Select any bank
6. Follow the flow

## Expected Result:
At the end of the Plaid process, you will be taken to the application for further actions.

## Actual Result:
At the end of the Plaid process, it runs a second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 11.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** BA connection cannot be checked in production

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/499fea04-044e-4352-bcc7-218bd370359c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
@ginsuma are you flagging that this is a duplicate?

**Comment by alexpensify** [comment]
Ok, closing! Thanks!
