### ISSUE TITLE
Task - Assignee assigned from user A is not shown in real time in user B task page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. As User A, tap fab
3. Tap assign task
4. Enter title and share somewhere to user B
5. Confirm task
6. Open user B account
7. Open bold created task received from user A
8. Now in user A account, in task page assign a user and note user B task page, not updated in real time

## Expected Result:
Assignee assigned from user A must be shown in real time in user B task page

## Actual Result:
Assignee assigned from user A is not shown in real time in user B task page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/97d2db61-ca11-426d-9636-57e05789c205

https://github.com/Expensify/App/assets/78819774/b83cc2f1-df4a-46f4-aa8b-77bd2bf5b515

https://github.com/Expensify/App/assets/78819774/54c3d6df-26a1-4ed8-a960-5f364549800e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I don't think we are treating these "live update" issues as bugs anymore. There have been several discussions about this, most recent one I can find is [here. ](https://github.com/Expensify/App/issues/25411#issuecomment-1696712212) Closing!
