### ISSUE TITLE
mWeb- Conversation- A green line appears for a second and disappears on receiving messages

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. User A: Tap on a report
3. Send a message to user B
4. Open user B account
5. Tap the bold message received from user A
6. Send some messages and note conversation page of user A

## Expected Result:
A green line must not appears for a second and disappears on receiving messages from user B.

## Actual Result:
A green line appears for a second and disappears on receiving messages from user B.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/19cd8d85-e068-487a-beec-486aef9b9798

https://github.com/Expensify/App/assets/115492554/ca657ebc-a2ae-4b46-8f83-2939dec16b2d

https://github.com/Expensify/App/assets/115492554/8dead14e-f285-4b17-b28d-513f851b2544

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
It's happening on iOS too (but not desktop).  Asking for design feedback
https://expensify.slack.com/archives/C01GTK53T8Q/p1695792469990699


https://github.com/Expensify/App/assets/22508304/4dd5f4fc-ee5d-446d-b5ba-30805f4ccb82

**Comment by mallenexpensify** [comment]
Checking on here
https://expensify.slack.com/archives/C01GTK53T8Q/p1696247959483009?thread_ts=1695792469.990699&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Putting on hold pending
https://github.com/Expensify/App/issues/23171
and
https://github.com/Expensify/App/pull/25935

**Comment by mallenexpensify** [comment]
On hold

**Comment by mallenexpensify** [comment]
HOld, other issue is slowly moving along
https://github.com/Expensify/App/issues/23171#issuecomment-1776489537

**Comment by mallenexpensify** [comment]
STill open
- https://github.com/Expensify/App/issues/23171#issuecomment-1776489537

**Comment by mallenexpensify** [comment]
^ Still open

**Comment by mallenexpensify** [comment]
Still holding, shouldn't be long

**Comment by mallenexpensify** [comment]
Hold

**Comment by mallenexpensify** [comment]
Holding....

**Comment by mallenexpensify** [comment]
Closing, not reproducible on iOS web, latest version

https://github.com/Expensify/App/assets/22508304/7a8d277b-8795-4867-9939-c8af410d2618
