### ISSUE TITLE
 IOU Tag - Tag section does not show up in the split confirmation screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27765
## Action Performed:
Precondition: User has enabled tag and added a few tags on OldDot
1. Go to staging.new.expensify.com
2. Go to the workspace #admin where tags are enabled and added
3. Click + > Split bill
4. Enter any amount > Next > Show more

## Expected Result:
Tag section shows up in the split confirmation screen

## Actual Result:
Tag section does not show up in the split confirmation screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a9a8fdc8-536f-4087-be24-b8081546082a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Not a blocker, the functionality is behind a beta and tags need to be on the policy for the picker to be present
