### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web - App doesn't re-focus on the text input when clicking on add split button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB > Request money
2. Enter a valid amount and continue
3. Click on add split button

## Expected Result:
Text input should re-focus

## Actual Result:
Text input doesn't re-focus

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 21-09-2023 14_29_58.webm](https://github.com/Expensify/App/assets/93399543/19817af3-c99b-4b87-93c3-9c57c776720e)

https://github.com/Expensify/App/assets/93399543/71d40a2f-8e9e-4ece-bc5d-a4e7e004b4f5

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695281387919179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce294c171ac5fb3a</li>
        <li>Upwork Job ID: 1705603569935224832</li>
        <li>Last Price Increase: 2023-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26933741</li>
<li>dukenv0307 | Contributor | 26933742</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @dukenv0307
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695281387919179

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App doesn't re-focus on the text input when clicking on add split button
### What is the root cause of that problem?
We add `shouldFocusOnSelectRow` here
https://github.com/Expensify/App/blob/04215cb99373b488a07372bd6ed34378f85ca8ef/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L290
But when we click on the add split button, we only call `this.props.onAddToSelection` and don't re-focus the text input
https://github.com/Expensify/App/blob/04215cb99373b488a07372bd6ed34378f85ca8ef/src/components/OptionsSelector/BaseOptionsSelector.js#L380
### What changes do you think we should make in order to solve the problem?
In `BaseOptionsSelector`, we should create a function that will be triggered when we click on the add split button. And then in this function, we will call `this.props.onAddToSelection` function and re-focus the text input.
```
addToSelection(option) {
    if (this.props.shouldShowTextInput && this.props.shouldFocusOnSelectRow) {
        this.textInput.focus();
        if (this.textInput.isFocused()) {
            setSelection(this.textInput, 0, this.props.value.length);
        }
    }
    this.props.onAddToSelection(option);
}
onAddToSelection={addToSelection}
```
https://github.com/Expensify/App/blob/04215cb99373b488a07372bd6ed34378f85ca8ef/src/components/OptionsSelector/BaseOptionsSelector.js#L380
### What alternative solutions did you explore? (Optional)
NA
### Result
[Screencast from 21-09-2023 14:54:03.webm](https://github.com/Expensify/App/assets/129500732/4dbeea93-0af6-4a64-b92f-2cb3f7a17e53)

**Comment by jjcoffee** [comment]
Unsure if the expected behaviour here is correct, we're defocusing when selecting Split, so I'm not sure why we'd refocus on the text input :thinking:

**Comment by jjcoffee** [comment]
@dukenv0307 Fair enough, I guess it makes more sense if you click split and then want to type to search for another person. Happy to go with your [proposal](https://github.com/Expensify/App/issues/28070#issuecomment-1732341644) in that case!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - behaviour has always been there as far as I can tell
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB > Request money
2. Enter any valid amount and continue
3. Click on the split button next to any user
4. Verify that the search input is refocused

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@sophiepintoraetz Checklist complete!

**Comment by tgolen** [comment]
It looks like this issue is waiting on @sophiepintoraetz to wrap up.

**Comment by tgolen** [comment]
bump @sophiepintoraetz

**Comment by sophiepintoraetz** [comment]
Sorry, been OOO (flight cancellations has me a bit behind). Created the regression GH here https://github.com/Expensify/Expensify/issues/327015 and have paid @jjcoffee!)
