### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Web - The input is lost focus on pressing enter key after no result found

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Select any workspace and open member page
3. Click on the invite button
4. Enter the random input that will display no result found
5. Press the enter key

## Expected Result:
The text input shouldn't lose focus

## Actual Result:
 The text input loses focus

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 21-09-2023 16_54_44.webm](https://github.com/Expensify/App/assets/93399543/089cf119-c388-465d-8b54-07e707d01d9c)

https://github.com/Expensify/App/assets/93399543/046c38e5-773c-4f74-92c4-0e5dcb30521a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695290112584589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6ef58dc2b8b4afd</li>
        <li>Upwork Job ID: 1705612299507138560</li>
        <li>Last Price Increase: 2023-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26976505</li>
<li>dukenv0307 | Contributor | 26976506</li>
<li>dukenv0307 | Reporter | 26976507</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @dukenv0307
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695290112584589

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The input is lost focus on pressing enter key after no result found
### What is the root cause of that problem?
We have the behavior of not losing focus if no options found in some pages due to [this logic](https://github.com/Expensify/App/blob/b7f24809ef7eecdc1b05034105dd8767c846356d/src/components/OptionsSelector/BaseOptionsSelector.js#L365) in `BaseOptionsSelector`, so it's clear that it's intentional.
There're 2 problems:
- In screens that use the new `SelectionList`, we don't have that same `blurOnSubmit` logic. See [here](https://github.com/Expensify/App/blob/b7f24809ef7eecdc1b05034105dd8767c846356d/src/components/SelectionList/BaseSelectionList.js#L318). There must be because the `SelectionList` is functionally similar to the `OptionsSelector`
- In `EmojiPicker`, we also have search functionality but [doesn't have](https://github.com/Expensify/App/blob/b7f24809ef7eecdc1b05034105dd8767c846356d/src/components/EmojiPicker/EmojiPickerMenu/index.js#L500) the `blurOnSubmit` logic
### What changes do you think we should make in order to solve the problem?

- In [BaseSelectionList](https://github.com/Expensify/App/blob/b7f24809ef7eecdc1b05034105dd8767c846356d/src/components/SelectionList/BaseSelectionList.js#L330), add
```
blurOnSubmit={Boolean(flattenedSections.allOptions.length)}
```
(this is similar logic to the `BaseOptionsSelector`)
- In [EmojiPickerMenu](https://github.com/Expensify/App/blob/b7f24809ef7eecdc1b05034105dd8767c846356d/src/components/EmojiPicker/EmojiPickerMenu/index.js#L512), add
```
blurOnSubmit={this.state.searchTerm.length > 0 && this.state.filteredEmojis.length > 0}
```
(the `searchTerm` needs to be set to the state in `onChangeText`)
### What alternative solutions did you explore? (Optional)
Any other search input that has the issue can be fixed similarly.

**Comment by JawadSadiq01** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
The input is lost focus on pressing enter key after no result found

**What is the root cause of that problem?**
Inside the reusable component filename **"BaseSelectionList"**, there is a TextInput. The TextInput is calling a function **"selectFocusedOption"**. 

The definition of the **selectFocusedOption** function has below code that is causing the lost of focus on pressing enter.

```
 const selectFocusedOption = () => {
        const focusedOption = flattenedSections.allOptions[focusedIndex];

         if (!focusedOption || focusedOption.isDisabled) {
             // return;
        }

        selectRow(focusedOption, focusedIndex);
    };
```
If I remove or comment the **return** inside of **if block code**, then the **TextInput** won't loose its focus. In the case of the selectFocusedOption() function, all of the code that follows the return statement will not be executed. this means that the code that keeps the input field focused (the **event.target.focus()** call) will never be executed. 

**To fix** this, you can simply remove or comment the return statement **(BaseSelectionList.js#197)** from the selectFocusedOption() function.

**What alternative solutions did you explore? (Optional)**
NA

**See img**
<img width="1320" alt="image" src="https://github.com/Expensify/App/assets/135354140/c5d0e167-905d-40a0-bc68-83297aef9bd8">

**Comment by JawadSadiq01** [comment]
Contributor details
Your Expensify account email: creatorjawad@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f227068c4c3098d5

**Comment by kadiealexander** [comment]
@nkuoch bump!

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Issue Reporter: $50 @dukenv0307
- [ ] Contributor: $500 @dukenv0307
- [ ] Contributor+: $500 @0xmiroslav

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/28072#issuecomment-1746188951)

Upwork job is [here](https://www.upwork.com/jobs/~01a6ef58dc2b8b4afd).

**Comment by kadiealexander** [comment]
@0xmiroslav please don't forget about the checklist :)

**Comment by kadiealexander** [comment]
@0xmiroslav bump!
