### ISSUE TITLE
[$500] IOS -  LHN not loading after clean sign-in on iOS native

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28081]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out
2. Sign in

## Expected Result:
LHN/List of chats to load

## Actual Result:
LHN not loading after clean sign-in on iOS native

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_0136](https://github.com/Expensify/App/assets/93399543/556d7ca2-c1ce-43d9-95d0-c2be7f306b86)
![IMG_0137](https://github.com/Expensify/App/assets/93399543/09619671-8456-426b-9b83-2cfb7d2efd73)

https://github.com/Expensify/App/assets/93399543/be53334b-fa83-4ba1-b02a-b55d1e9a6a32

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695346728508729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3eaa01ee40a65c1</li>
        <li>Upwork Job ID: 1705650701865562112</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Just tested again on staging v1.3.73-1 and wasn't able to reproduce.  @CortneyOfstad @aimane-chnaif @kbecciv , can you see if you're able to reproduce on production?

**Comment by CortneyOfstad** [comment]
I was not able to recreate in production @mallenexpensify 

Added the tag @aimane-chnaif 👍 

Can you confirm this is still taking place @kbecciv?

**Comment by CortneyOfstad** [comment]
Bump @kbecciv ^^^ — TIA!

**Comment by kbecciv** [comment]
@CortneyOfstad @mallenexpensify Sorry for delay response. I was able reproduce on staging build 1.3.73.0 when I was reviewing the bug. 
But issue is not longer reproduced on build 1.3.74.1

https://github.com/Expensify/App/assets/93399543/8a04c264-fb88-4c39-8020-b256c51e43c0

**Comment by CortneyOfstad** [comment]
Thanks @kbecciv! 

Based on the fact that this cannot be recreated under the latest staging version, do you think it is safe to close @mallenexpensify @aimane-chnaif? TIA!

**Comment by mallenexpensify** [comment]
@kbecciv can you to reproduce one more time? I just had an inconsistent test, where LHN didn't load for a long while but once the screen went dark and I tapped it, LHN showed as loaded ¯\_(ツ)_/¯

**Comment by CortneyOfstad** [comment]
@kbecciv bump on @mallenexpensify's comment above — thanks!

**Comment by kbecciv** [comment]
Checking, will update you shortly

**Comment by kbecciv** [comment]
Not reproduced on build 1.3.77.5

https://github.com/Expensify/App/assets/93399543/6d0f64a3-b7aa-4360-987f-7b481784cb2d

**Comment by mallenexpensify** [comment]
Happened again to me today, forgot I had already reported
https://expensify.slack.com/archives/C049HHMV9SM/p1696438965730399

**Comment by CortneyOfstad** [comment]
@aimane-chnaif or @kbecciv are either of you able reproduce this as well?

**Comment by CortneyOfstad** [comment]
@mallenexpensify are you still able to reproduce this?

**Comment by mallenexpensify** [comment]
No, not with the new LHN/Chat setup which I just noticed for the first time. 
I removed `Help Wanted` and made it a weekly, I'll test it again next week and, if I can't repro, we can close

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
It took ~25 seconds to load LHN v1.3.84-7 but it loaded, going to close now.
