### ISSUE TITLE
Room - App navigate to Login page when tap emoji picker on announce room as anonymous user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of New Expensify
2. Navigate to this link - https://staging.new.expensify.com/r/3504895439653267
3. Tap on emoji picker under any message

## Expected Result:
The page should not respond until I press Sign in

## Actual Result:
App navigate to Login page when tap emoji picker on announce room as anonymous user

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a8265b5d-ef59-47ea-a00b-249025c338bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
This is expected behavior, we should prompt users to sign in when they try interacting with emojis on a chat.
