### ISSUE TITLE
Fab - Save the world option not displayed in global menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27750
## Action Performed:
1. Login to the Expensify app using an email address with a private domain
2,Open the global menu

## Expected Result:
Save the world option displayed to choose

## Actual Result:
Save the world option not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1cb155de-48d8-4c89-8ece-5ffb4f71a9b0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
This is intentional. https://github.com/Expensify/App/pull/27763

**Comment by michaelhaxhiu** [comment]
The Save the world menu item in global create was hidden as the launch got pushed back. This is intentional. closing :)
