### ISSUE TITLE
[$500] Security - Clicking back button takes user 2 steps back from 2FA page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Settings > Security > Two-factor authentication
2. Click on copy and next
3. Click on the system back button

## Expected Result:
App should take user only one step back

## Actual Result:
App takes user two steps back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop -did not check due to access 

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a16e4339-9952-4a3f-9124-f4540e29eb8f

https://github.com/Expensify/App/assets/93399543/9ba838ff-e361-42c9-8782-79fe5ec52d63

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695393624697049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140c704580d4276d6</li>
        <li>Upwork Job ID: 1706005013292396544</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>Nathan-Mulugeta | Reporter | 26937013</li>
</ul></li>
    </ul>
</details>

**Comment by bojangabric** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User cannot go back using browser back button from 2nd or 3rd step on 2FA.

### What is the root cause of that problem?

The root cause is no routes on 2nd and 3rd step of 2FA.

### What changes do you think we should make in order to solve the problem?

We should create new routes for 2nd and 3rd steps on 2FA.

### What alternative solutions did you explore? (Optional)

Other solution is to override back button functionality, this might be better if user is never supposed to directly access some step of 2FA.

**Comment by arsangamal** [comment]
Hi,
Coming from Upwork,

https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/settings/Security/TwoFactorAuth/StepWrapper/StepWrapper.js#L14

The issue here is whatever the `stepCounter` value is, the `onBackButtonPress` will return back to the settings, as all the 2fa steps are considered as one view 

The logic that needs to be added is:
1- on `onBackButtonPress` should run on the current behavior if and only if the counter is `1` or null.
2- otherwise, the `stepCounter` should be decremented by 1 to navigate to the previous step.

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Upon click on back button it takes us 2 step backwards from 2FA page
### What is the root cause of that problem?
We are using same route for 2 pages which is Where the code is copied and where code is entered.
### What changes do you think we should make in order to solve the problem?
Just need to create another route for the page where we enter the code to handle the back scenario.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by bojangabric** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/28094#issuecomment-1732636744)

**Comment by alexpensify** [comment]
@robertKozik - when you get a chance, can you please review the proposals? Thanks!

**Comment by robertKozik** [comment]
Sure, on it 👀 Thanks for bump @alexpensify

**Comment by robertKozik** [comment]
Hi! Thank you both for your proposals, @arsangamal and @bojangabric! I'll address them one by one:

- @arsangamal: Please follow the [Proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md). Every proposal should adhere to it. Moreover, I believe you've wrongly pinpointed the root of the problem. The `onBackButtonPress` function is overwritten on every usage of `StepWrapper`. For example, in `VerifyStep` component:https://github.com/Expensify/App/blob/f39e93f119c7bb76a56fb7df28251d84a37b65bc/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js#L75

- @bojangabric: The solution of creating additional routes for each step looks promising, but I think we need to refine this a little. First of all, if we decide to go with this, we should propagate this refactor to every step of the TwoFactorAuthSteps. As the actual step can be loaded from the `account.twoFactorAuthStep`, I think the URL should use them. It would be easier to understand. If you could refine the refactor solution and propose more details about it, I think it should be the way to go. If you don't agree with me on this, I'm happy to discuss 😉

**Comment by bojangabric** [comment]
Hey @robertKozik, I agree that we should do it for all steps.

Basically we would change these steps to seperate routes:

https://github.com/Expensify/App/blob/44568ba24c3ac00b3a43d07d81a8061f687dadba/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.js#L46-L55

And we wouldn't use `setCurrentStep` anymore, we would navigate pages with `Navigation.navigate(route)` https://github.com/Expensify/App/blob/44568ba24c3ac00b3a43d07d81a8061f687dadba/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.js#L16

Just not sure how we should handle when user directly goes to some URL, e.g. `/settings/security/two-factor-auth/success`. In this case user should be redirected to `/settings/security/two-factor-auth/codes`.

I was thinking of doing this redirection inside of each new route, to check `twoFactorAuthStep` from `ONYXKEYS.ACCOUNT`. If it doesn't match to return the user to the first route `/settings/security/two-factor-auth/codes`. What do you think?

**Comment by robertKozik** [comment]
Sounds good to me! If you could update your proposal with this additional info I think We can go forward with it.

**Comment by bojangabric** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/28094#issuecomment-1732636744)

**Comment by alexpensify** [comment]
Update: I've bumped @grgia in Chat to unlock this one.

**Comment by grgia** [comment]
Thanks for your patience, assigned!

**Comment by bojangabric** [comment]
I've just applied on Upwork. I'll have the PR ready for review in about 4 days!

**Comment by grgia** [comment]
Sounds good, thank you @bojangabric

**Comment by grgia** [comment]
@bojangabric do you have an update on this?

**Comment by bojangabric** [comment]
@grgia I've moved everything to new routes and it's working properly, but I'm having a different issue now.

When going back with browser, it will start showing steps from before, e.g. if the user goes through this path:

`/settings -> /codes -> /verify -> /success`

I think with clicking back button the user should go from `/sucess` to `/settings` route, not to `/verify` again. Is this correct?

I had to get familiar with the way navigation works, but I should be done soon.

**Comment by alexpensify** [comment]
Weekly Update: looks like the PRs are moving forward!

**Comment by alexpensify** [comment]
Weekly Update: PR is still active

**Comment by alexpensify** [comment]
Weekly Update: There has been some clean up in the PR, still moving along here.

**Comment by alexpensify** [comment]
Weekly Update: A ton of progress in the PR, we are almost there!

**Comment by alexpensify** [comment]
Weekly Update: PR is still in review.

**Comment by bojangabric** [comment]
@aimane-chnaif Alright, closing my PR then.

**Comment by alexpensify** [comment]
@robertKozik - do you agree we should close this issue? Thanks!

**Comment by alexpensify** [comment]
Thanks! I'm going to close this GH based on this feedback.

**Comment by Nathan-Mulugeta** [comment]
Hey team can we also close the upwork job? @alexpensify Thanks

**Comment by alexpensify** [comment]
The job was closed but I cleared through any remaining tasks in Upworks.
