### ISSUE TITLE
Request money - "Distance" option is missing in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on the global "+" button
3. Click on the "Request money" button
4. Click on the chat "+" button
5. Click on the "Request money" button

## Expected Result:
The "Distance" button should be available from both "+" buttons

## Actual Result:
The "Distance" button is missing when doing "Request money" from the chat. The option is there when you use the global "+" button to "Request money"

## Workaround:
Unknown?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73_0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9313ad5a-d065-4c35-8776-4b801e6a1ecc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
I think this is intentional, because distance request is only applicable in policies.

**Comment by NicMendonca** [comment]
@neil-marcellini can you confirm? ^ Thanks!

**Comment by neil-marcellini** [comment]
> I think this is intentional, because distance request is only applicable in policies.

Yes that's true. We don't support distance requests to individuals yet, it has to be sent in a workspace chat.
