### ISSUE TITLE
[HOLD for payment 2023-10-09] [HOLD for payment 2023-10-05] Members - Clicking on 'Invite' button navigates back to Workspace page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Click on 'Members'
3. Click on 'Invite' button

## Expected Result:
 User should navigate to the 'Invite members' page

## Actual Result:
User is navigated back to workspace page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f9d55f99-32ae-4c78-affd-11f1fb7e8c42

https://github.com/Expensify/App/assets/93399543/c10a85a2-5d9c-4902-96b4-cd0c039aafa6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695627542846449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment]
### Please re-state the problem that we are trying to solve in this issue.
Wrong navigation on click of 'Invite' button
### What is the root cause of that problem?
We are navigating to workspace initial page instead of invite page
### What changes do you think we should make in order to solve the problem?
Change route from WORKSPACE_INITIAL to WORKSPACE_INVITE to below code
 
https://github.com/Expensify/App/blob/f068ef142b5ebe34bc20326b09bee2e6e0c8332e/src/pages/workspace/WorkspaceMembersPage.js#L137-L140
/

**Comment by Pujan92** [comment]
Seems a regression from this [PR](https://github.com/Expensify/App/pull/28050) where by mistake `WORKSPACE_INITIAL` used instead of `WORKSPACE_INVITE` 
https://github.com/Expensify/App/pull/28050/files#diff-bbfbd221fc2e98be145adb346139ceb43a56501e1feef799db83b51ae672421eL139
cc: @tgolen

**Comment by tgolen** [comment]
Thanks! I've opened a PR to fix this.

**Comment by cristipaval** [comment]
just opened one as well @tgolen , hahah

**Comment by chiragsalian** [comment]
Staging on staging and it looks like this is resolved. Removing deployblocker label.

**Comment by tgolen** [comment]
@CortneyOfstad I believe this is waiting on @thesahindia getting paid for a C+ review on the PR. Could you please facilitate that?

**Comment by Natnael-Guchima** [comment]
I am also not paid for reporting bonus

**Comment by CortneyOfstad** [comment]
So to confirm — 

@Natnael-Guchima is paid $50 for reporting bonus
@thesahindia is paid $500 as the C+ contributor — or does this qualify for a bonus @tgolen?

Thanks and once I have this confirmed, I'll manually create the job in Upwork and send out the proposal contracts 👍

**Comment by CortneyOfstad** [comment]
Okay, so to confirm @tgolen — does only @Natnael-Guchima get paid for the reporting bonus?

**Comment by tgolen** [comment]
That looks correct, yes.

**Comment by CortneyOfstad** [comment]
@Natnael-Guchima Sent you a proposal in Upwork. Let me know once you accept and we can get this paid — thanks!
