### ISSUE TITLE
[$500] Web - Public view is displayed for signed user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28155]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app -> Log out
2. Navigate to a public room https://staging.new.expensify.com/r/5408450846930023
3. Click sign in button
4. Fill login form and sign in
5. Navigate to concierge chat or any other random chat
6. Deep link to the same room from step 2 : https://staging.new.expensify.com/r/5408450846930023

## Expected Result:
Singed in layout should be displayed for user

## Actual Result:
Public view is displayed and user can’t interact with the App , can logout or open settings modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7cfd3c15-20bf-42e1-8400-066fb00e9f32

https://github.com/Expensify/App/assets/93399543/cf5166c3-a3cf-4c8c-969e-b00f9f12d0df

**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695648071050709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I agree with you, going to close this out
