### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Web - LHN - Inconsistency bug: 3 dot text is not centered

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Hover on user with very long display name, observe that display name is centered (text overflowing on second line is centered)
3. Hover on 3 dots in the end and observe that same username text is not centered in this tooltip

## Expected Result:
App should center align 3 dot long username text in tooltip as it does on normal tooltip

## Actual Result:
App does not center align 3 dot long username text in tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9b3a8301-0d2a-4f8d-bff7-6e23e7ce0b0a

https://github.com/Expensify/App/assets/115492554/48bf9a3d-bb42-48da-a8bf-91275f7fd127

**Expensify/Expensify Issue URL:**

**Issue reported by:** [@dhanashree-sawant](https://github.com/dhanashree-sawant)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695228073831509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d3492d7d4a297ab</li>
        <li>Upwork Job ID: 1706323101730693120</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27048221</li>
<li>chiragxarora | Contributor | 27048223</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Proposals ready for you @situchan

**Comment by MitchExpensify** [comment]
Bumped @situchan 1:1

**Comment by situchan** [comment]
@chiragxarora's [proposal](https://github.com/Expensify/App/issues/28153#issuecomment-1735387538) looks good to me.
🎀 👀 🎀 C+ reviewed

https://github.com/Expensify/App/assets/108292595/85949c0c-ffab-490e-bed2-35fdd093960a

**Comment by MitchExpensify** [comment]
Paid and contracts ended for @situchan & @chiragxarora 

Sent you an offer [@dhanashree-sawant](https://github.com/dhanashree-sawant) https://www.upwork.com/ab/applicants/1706323101730693120/hired

**Comment by MitchExpensify** [comment]
Whats the latest on the BZ steps @situchan ?

**Comment by situchan** [comment]
No regression. We can skip regression test as this was super minor UI **bug** (not actually bug)

**Comment by MitchExpensify** [comment]
Great, all paid and regressions! Closing
