### ISSUE TITLE
[$500] Web - Chat -User unable to copy/paste of images from Google Docs / Sheets / Slides to NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28150]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in NewDot
2. Open Google Slides
3. Copy one of the image and paste to NewDot chat conversation

## Expected Result:
User able to copy/paste of images from Google Docs / Sheets / Slides to NewDot

## Actual Result:
User unable to copy/paste of images from Google Docs / Sheets / Slides to NewDot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/94fb281a-84bb-4b19-80da-c157cfa75f61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695429296097429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa7b4142d99618cd</li>
        <li>Upwork Job ID: 1706317384688562176</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
I think we can close this, no body can copy things from google slides :) tried on whatsapp also not working.
