### ISSUE TITLE
IOS 17 - Attachments - When you reopen the image, the preload splash screen rotates indefinitely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28168]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any conversation where there are 4-5 attached images or send them
4. Open the last image
5. Navigate to another conversation
6. Return to the conversation with the images
7. Open the last image opened in step 4

## Expected Result:
When you reopen an image in a conversation, the preload splash screen should disappear when the image is fully loaded

## Actual Result:
When reopening an image in the conversation, the prereload splash screen spins infinitely and won't go away

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ffd038e9-1a7f-452f-b159-7c98a5ebc81b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Can't repro
