### ISSUE TITLE
[HOLD for payment 2023-11-21] Migrate Lottie animations from bundle to app assets

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#28160]
# Problem 

Lottie animation resources are bundled along the main js bundle. They constitute around 5M of 29M bundle in release mode which is significant. The issue with including such resources in a bundle is that this data needs to be parsed and allocated (these objects will also be quite large and require a tons of allocations because of their structure) which slows down the startup time. 

All of that only happens such that this object can be serialized to string and parsed again by the native Lottie code. The source of the issue is the fact Lottie assets are imported using bundler `import` statement much like you do with other resources like images.

# Solution

The fix is to change the way these files are imported and allow Lottie load them directly from the app assets using resource link.

**Comment by kosmydel** [comment]
Hey, probably solving the above issue will cover this issue as well:

- https://github.com/Expensify/App/issues/26857

**Comment by kosmydel** [comment]
Hey, I am from Software Mansion. I am going to handle this issue.

**Comment by roryabraham** [comment]
This is done, but caused a few issues which maybe warranted broader discussion than they got. Namely:

- https://github.com/Expensify/App/issues/31236
- https://github.com/Expensify/App/issues/31196

I think we should consolidate those discussions into this issue and discuss potential solutions.

**Comment by roryabraham** [comment]
Copied from another issue, but some thoughts:

- We need to finish getting browser-level image caching set up in https://github.com/Expensify/App/issues/12603, and make sure it works for `.lottie` assets too.
- Maybe we could get an SVG snapshot of each animation that's inlined in the HTML and display that while the lottie animation is loading
- Or maybe we can find a way to either inline or preload `.lottie` assets. If we could preload them like we do with fonts when the page loads that could be a good way to address these problem
- Someday we could also look at setting up [service workers](https://expensify.slack.com/archives/C04CWBFE6/p1684865689862329) in our app to build better cross-session browser caching of all assets.

I think if we get good caching and potentially also preload `.lottie` assets like we do for our web fonts, we could eliminate most scenarios where a user could possibly see this type of bug or similar bugs where there's a delay before the animation loads.

**Comment by kosmydel** [comment]
Hey @muttmuure @roryabraham, the Melvin-bot is angry at me. Can we close this issue?

**Comment by roryabraham** [comment]
Yeah, I think we can close this for now
