### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] mWeb- Chat - Android chrome crashes on opening password protected PDF

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report with password protected PDF sent to it
3. Open the password protected PDF
4. Observe that app crashes

## Expected Result:
App should not crash on opening password protected PDF

## Actual Result:
App crashes on opening password protected PDF on android chrome

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![android chrome password pdf crash](https://github.com/Expensify/App/assets/115492554/3298f689-ecc2-4a35-a105-c43c7aa22b37)

![Screenshot_20230925_201210_Chrome](https://github.com/Expensify/App/assets/115492554/ddc2506a-1d01-498e-8fbc-a3dea6e43411)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695401444195489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f798c5b0834a975</li>
        <li>Upwork Job ID: 1706357780647206912</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27099989</li>
<li>ZhenjaHorbach | Contributor | 27099993</li>
<li>dhanashree-sawant | Reporter | 27099994</li>
</ul></li>
    </ul>
</details>

**Comment by joh42** [comment]
Hmm, works for me on my phone running Chrome 117

**Comment by youssef-lr** [comment]
Melvin was acting up, offers have been created now!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment]
I'm OOO Oct 16-23. Adding leave buddy

Status: waiting to issue payment https://github.com/Expensify/App/issues/28179#issuecomment-1765323839

**Comment by sonialiap** [comment]
@Ollyws review + bonus = $750 - please accept the offer 
@ZhenjaHorbach fix + bonus = $750 - paid ✔️ 
@dhanashree-sawant report = $50 - paid ✔️

**Comment by sonialiap** [comment]
Haha oh no, let me go find the one you've accepted

**Comment by sonialiap** [comment]
Paid ✔️
