### ISSUE TITLE
[$500] Mweb - Android chrome displays background chat behind emoji picker on selecting any emoji type

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Open any report
3. Click on emoji to open emoji picker
4. Click on search to open keyboard
5. Click on any emoji category below search
6. Observe that app closes keyboard fast but relocates emoji picker slow because of which it displays background chat in place of emoji picker for sometime

## Expected Result:
App should relocate emoji picker to bottom along with closing of keyboard to avoid displaying background chat in place of picker

## Actual Result:
App delays relocation of emoji picker to bottom when we click any emoji picker causing app to display background chat in place of picker for sometime

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1bec263b-411c-47c3-92ca-ebdf3e3c929a

https://github.com/Expensify/App/assets/93399543/e8613bde-8a4e-4355-807f-8be7e46a5f1d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695460599996869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5fc23956be41e7c</li>
        <li>Upwork Job ID: 1706353102412886016</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Cool, closing this one.
