### ISSUE TITLE
[HOLD for payment 2023-10-30] Optimize React Context usages in New Expensify

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#28177]
Coming from: https://expensify.slack.com/archives/C05LX9D6E07/p1695377829998599 

# Problem:

Poorly implemented React Context will lead to unnecessary re-renders of Context.Consumers.

# Solution:

Making sure that each time React Context is used, the value passed to Context.Provider will be properly memoized. Apart from fixing problem in existing files it would be nice to share the knowledge to developers (and reviewers) to pay attention to this problem.

Go through this list and optimize these context usages:

1. src/components/ScrollViewWithContext.js
2. src/components/AnimatedStep/AnimatedStepProvider.js
3. src/components/Attachments/AttachmentCarousel/Pager/index.js
4. src/components/DragAndDrop/Provider/index.js
5. src/components/PopoverProvider/index.js + index.native.js
6. src/components/withWindowDimensions/index.js + .native.js
7. src/pages/home/ReportScreen.js
8. src/pages/home/report/ReportActionItem.js
9. src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.js

**Comment by mountiny** [comment]
all done here
