### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Request Money - App crashes when invalid id entered in the url while requesting money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request Money
2. Enter any amount.
3. Select any participant.
4. Edit the url and change the id number to something invalid.

## Expected Result:
The app should show the not found page

## Actual Result:
App crashes

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0cc433b1-d9d7-4313-8b80-5aabdb30eb31

https://github.com/Expensify/App/assets/93399543/ae956091-d9cb-4510-a40f-3e10007d50a5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695485570103699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ee95879b3ee9fee</li>
        <li>Upwork Job ID: 1706367444027846656</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26873478</li>
<li>esh-g | Reporter | 26873479</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
# Proposal

## Please re-state the issue
App crashes when invalid id entered in the url while requesting money

## What is the root cause of the problem?
We actually have logic in the `MoneyRequestConfirmPage` to reset the `IOU` in case there is a mismatch between the current `iou.id` and the `reportID` here:
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L99-L104

But this crash is occurring before the above code is getting executed. Here is where the error is occurring:
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L380-L384
We are trying to get the `report.policyID` but when the `reportID` is invalid, it returns the `report` as `undefined` so we are trying to access a property on `undefined` which is causing the error.

## What changes do you think should be made to fix this problem?
**Option 1**
We have started to allow optional chaining in the codebase, so we can use `report?.policyID` to prevent this error.
```js
policy: {
     key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`,
 },
 ```
**Option 2**
 We can copy the approach how we handle this from the `EditRequestPage.js` file:
 https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/EditRequestPage.js#L226-L228

## What other alternative options did you explore? (Optional)
**Option 3**
We can use the typical `lodashGet(report, 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE)` here instead as well, if we don't want to use optional chaining.
```js
policy: {
     key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY}${lodashGet(report, 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE)}`,
 },
 ```

**Comment by s77rt** [comment]
@esh-g Thanks for the proposal. Your RCA is correct and the solutions makes sense. Given this is a regression from https://github.com/Expensify/App/pull/27172 I think the C/C+ may handle this. cc @waterim @0xmiroslav

**Comment by waterim** [comment]
Yes, I can handle this

**Comment by esh-g** [comment]
@s77rt but that PR was more than 2 weeks old... Shouldn't this be out of the regression period?

**Comment by s77rt** [comment]
@esh-g The PR was deployed to production just 3 days ago. This is still within the regression period.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/27172
- The offending PR has been commented on: https://github.com/Expensify/App/pull/27172#discussion_r1336387679
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by sophiepintoraetz** [comment]
Hi @sonialiap! Looks like this was a fortuitous double-assignment - I'm headed OOO till 17 Oct so all that needs doing here is:
1. @s77rt requires payment [offer](https://www.upwork.com/nx/wm/offer/26873478) (Reviewer) and is eligible for the urgency bonus ($750)

(I have paid the reporter already)

**Comment by sonialiap** [comment]
The offer link is not working for me so I've sent a new one - https://www.upwork.com/nx/wm/offer/27157108

**Comment by s77rt** [comment]
@sonialiap Accepted! Thanks!

**Comment by sonialiap** [comment]
Paid 🎉
