### ISSUE TITLE
[$500] Link changes from edited to normal message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Copy and paste and URL and send (eg: https://staging.new.expensify.com/settings)
4. Edit the message and add double quotes in the end of URL part eg: [https://staging.new.expensify.com/settings](https://staging.new.expensify.com/settings")
5. Save and visit the URL, it should display Hmm its not here page
6. Change chat and revisit, observe that it removes '(edited)' from the link message and also modifies the link back to normal
## Expected Result: 
App should not edit link back to original form and remove edited label
## Actual Result: 
App edits the link back to original form and removes edited label if we add double quotes in the URL part of link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1c18498f-71e4-46d9-928b-c6a12978a673

https://github.com/Expensify/App/assets/43996225/4bd90f7f-e0d5-4b34-b330-85ed2bc1d83e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694013745101109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bb491a99dd8dcfc</li>
        <li>Upwork Job ID: 1706391965087408128</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This is some super edge case. Happens only on adding the `"` at the end of the link.
As a result, BE ignores this change and does not persist updates.

Response to the `UpdateComment` API call:

```js
{
    "jsonCode": 200,
    "requestID": "80ca013b4efe3503-WAW",
    "onyxData": []
}
```

Moreover, if in one edit we change the text and append the `"` to the URL, the response contains changed text but the URL change is ignored:

```js
[
    {
        "onyxMethod": "merge",
        "key": "reportActions_3306588635446108",
        "value": {
            "5158864619950392440": {
                "message": [
                    {
                        "type": "COMMENT",
                        "html": "<a href=\"http://localhost:8082/r/3306588635446108\" target=\"_blank\" rel=\"noreferrer noopener\">http://localhost:8082/r/330658863544610</a>",
                        "text": "http://localhost:8082/r/330658863544610",
                        "isEdited": true,
                        "whisperedTo": [],
                        "isDeletedParentAction": false
                    }
                ],
                "lastModified": "2023-09-26 08:07:26.940"
            }
        }
    },
    {
        "onyxMethod": "merge",
        "key": "report_3306588635446108",
        "value": {
            "lastMessageText": "http://localhost:8082/r/330658863544610",
            "lastMessageHtml": "<a href=\"http://localhost:8082/r/3306588635446108\" target=\"_blank\" rel=\"noreferrer noopener\">http://localhost:8082/r/330658863544610</a>",
            "isEdited": false,
            "lastVisibleActionCreated": "2023-09-26 07:59:16.685",
            "lastActorAccountID": 15618012
        }
    }
]
```

**Comment by s-alves10** [comment]
This looks like a backend issue

**Comment by puneetlath** [comment]
Hmm, yes this is indeed super edge-case. I looked into the back-end and I don't think this is going to be straightforward at all to address. I think we should just close this issue as it isn't worth the effort/complication. I don't think a real user will end up in this scenario and feel it's problematic. Feel free to comment if you disagree!
