### ISSUE TITLE
[$500] iOS - Request money - Selected currency issue not consistently when navigating to iOS App from mWeb Safari Banner on iOS

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28193]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: Account A has currency setting is USD - $ (for example)
1. Log in to Account A on iOS App and mWeb iOS SAFARI
2. On mWeb SAFARI:
     - Create a Request Money and select a different currency, such as EUR - €.
      - Click the Open button located on the top banner of mWeb.
      - Observe that the user is redirected to the iOS app, and the currency is correctly set to EUR - € (which is CORRECT)
3. Back to mWeb SAFARI:
     - Click NEXT to proceed to the Select contact page (IMPORTANT step).
     - Click the Open button located on the top banner of mWeb.
     - Observe that the user is redirected to the iOS app, BUT the currency remains set as USD - $ (which is INCONSISTENT)

## Expected Result:
The selected currency should be consistent across screens.

## Actual Result:
 The selected currency is inconsistent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** iOS 16.4.1 Build v1.3.73-1/mWeb - Safari Build v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9d24caa8-5148-4080-8a69-ba24e78c3773

https://github.com/Expensify/App/assets/115492554/b33a91c6-3322-43f1-a451-d592b4c0cfa5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695492131083339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bfd24773e88ecee</li>
        <li>Upwork Job ID: 1706403856477437952</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
I'll take this one off your hands @isabelastisser , since it seems we were double assigned.

**Comment by cubuspl42** [comment]
The way the expected behavior is sketched here doesn't convince me, but if we went with what @dukenv0307 suggests in their proposal (i.e. adding _both_ the amount and the currency to the params), it would make sense.

I [started a thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1696248138767919) on Slack.
