### ISSUE TITLE
[$500] Request Money - Category edit page shown for normal money request (betweem 2 users)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28192]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a money request with user (no workspace)
2. Go to that money request page
3. Append `/edit/category` to url
4. Category is visible

## Expected Result:
Category shouldn't be shown for 1:1 money request, user should see page is not found with appropriate message

## Actual Result:
Category edit page shown for normal money request (between 2 users)

## Workaround
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/90eabbe7-1d06-4f9e-916d-d6c589938f7d

https://github.com/Expensify/App/assets/93399543/38d7c37d-af2e-4e3a-bc2d-685549d8f980

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695530860289029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01445341bcc011416f</li>
        <li>Upwork Job ID: 1706399640115785728</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by RichardPickman** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category modal opens in one-to-one money request when redirecting to /edit/category.

### What is the root cause of that problem?
Modal opens whenever path satisfies mask /edit/category

### What changes do you think we should make in order to solve the problem?
Add additional check on request type to open category list.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by RichardPickman** [comment]
## Proposal
[Updated][(link to proposal)](https://github.com/Expensify/App/issues/28192#issuecomment-1734479518)

**Comment by BhuvaneshPatil** [comment]
@kbecciv Can you please add the proposal from slack here.

**Comment by kbecciv** [comment]
Proposal by: @BhuvaneshPatil
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695530860289029

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can access edit category page using link for 1:1 request, but the category feature is only for workspace money requests
https://expensify.slack.com/archives/C01GTK53T8Q/p1695530938132669

### What is the root cause of that problem?
We don't have any check in `EditRequestCategoryPage` for allowing that page to be shown for 1:1 money requests.

### What changes do you think we should make in order to solve the problem?
we check for showing category in `MoneyRequestView`
https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/components/ReportActionItem/MoneyRequestView.js#L93

We shall have same check for `EditRequestCategoryPage`.
We shall  wrap above component using `FullPageNotFoundView` and use same logic as we are using in `MoneyRequestView`.
To access all this information we need to add some props and pass few from parent component.

### What alternative solutions did you explore? (Optional)
We can also add `FullPageNotFoundView` in https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/EditRequestPage.js#L182-L197
The advantage of this is that some information is already available and we don't need to add props for them.

**Comment by RichardPickman** [comment]
# Proposal

[UPDATE] https://github.com/Expensify/App/issues/28192#issuecomment-1734479518 , Added permalink by rushatgabhane suggestion.
