### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Make Mobile Web and Native App Scanning Consistent

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#28204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
On mobile web:
1. "+"
2. "Request money"
3. "Scan"

## Expected Result:
The camera screen should not take up the whole screen. It should be framed and embedded in the app like this (Note the ability to go back "<", choose "Manual", etc.) :
![image](https://github.com/Expensify/App/assets/36425901/ef9e416d-7415-4b5c-9131-82ba61690ee4)

## Actual Result:
The camera screen takes up the whole screen and is not embedded in the app
![image](https://github.com/Expensify/App/assets/36425901/b0bd4659-744d-4d3b-8093-b1c1841891ac)

## Workaround:
Exit the camera 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** kevin@expensify.com
**Slack conversation:** https://expensify.slack.com/archives/C03UK30EA1Z/p1695265445916999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180a713f11bf0b357</li>
        <li>Upwork Job ID: 1706499655547604992</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26896893</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Lucas from CallStack is going to be taking this on! 🚀

**Comment by laurenreidexpensify** [comment]
@MitchExpensify can you tag Lucas on this issue so he can comment and we can assign him? Thanks

**Comment by MitchExpensify** [comment]
I shared the link to the issue in GH, I'm not sure of their GH handle 😅

**Comment by lukemorawski** [comment]
@MitchExpensify will be posting PR today!

**Comment by MitchExpensify** [comment]
Awesome, still on course for the PR today?

**Comment by lukemorawski** [comment]
@MitchExpensify Sorry, had some urgent bug fixes on other tickets. PR will be landing in a moment!

**Comment by lukemorawski** [comment]
@MitchExpensify PR is out

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  This is a new feature
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - N/A
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

 External issue reporter - @kevinksullivan internal 
 Contributor that fixed the issue - @lukemorawski agency worker 
 Contributor+ that helped on the issue and/or PR - @cubuspl42 $500, payment issued in Upwork
