### ISSUE TITLE
[$500] Chat --Tapping expand button and then plus icon, the compose box becomes extra big

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter a number
4. Tap enter few times and enter other number
5. Tap plus icon near compose and close it by tapping on outside
6. Note the size of compose box
7. Tap expand button
8. Tap plus icon near compose and note background compose box become extra big
9. Tap outside and close plus icon options and note size of compose box

## Expected Result:
When user taps expand button and taps plus icon near compose, the compose box must not become extra big

## Actual Result:
When user taps expand button and taps plus icon near compose, the compose box becomes extra big

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ba29a2b5-45f0-415c-86c8-c5aa8a18c238

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170623ae497958496</li>
        <li>Upwork Job ID: 1706527705972113408</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by omergr8** [comment]
Subject: Tapping expand button and then plus icon, the compose box becomes extra big.

### Issue Overview
Currently, when a user clicks on the "stretch" button, it applies the CSS property `flex: 1 1 0%;` to the textarea div (the second sibling). However, its sibling div, the chat div, already has the same `flex: 1 1 0%` property applied. This results in both sibling divs taking equal amounts of space, which leads to the issue where the chat textarea becomes larger when the keyboard disappears.

### Proposed Solution
The proposed solution is to dynamically adjust the `flex` properties of the sibling divs when the textarea is expanded. Specifically, we can set the chat area to occupy 70% of the available space, while the text area takes up the remaining 30%. By doing so, we can ensure that the textarea's size remains consistent and does not unexpectedly change when the keyboard appears or disappears.

### Implementation Details
To implement this solution, we can employ JavaScript to toggle the `flex` properties of the sibling divs upon clicking the "stretch" button. Here's a high-level overview of the steps:

1. When the "stretch" button is clicked:
   - Remove the inherited `flex: 1 1 0%;` property from both sibling divs.
   - Apply `flex: 7` to the chat area div (occupying 70% of available space).
   - Apply `flex: 3` to the text area div (occupying 30% of available space).

This adjustment ensures that the chat area remains larger, while the text area remains smaller, creating a more consistent user experience.

### Expected Benefits
- Prevents the textarea from unexpectedly changing size when interacting with the keyboard.
- Enhances the user experience by maintaining a stable layout.
- Offers greater control over the distribution of space between the sibling divs within the flex container.

### Additional Considerations
- Compatibility with various screen sizes and devices should be thoroughly tested to ensure responsiveness.
- Accessibility and user testing should be conducted to validate the proposed solution.

**Comment by omergr8** [comment]
Contributor details
Your Expensify account email: umar.mukhtar4455@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c0eeade85c091525

**Comment by greg-schroeder** [comment]
awaiting proposal review

**Comment by omergr8** [comment]
Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping expand button and then plus icon, the compose box becomes extra big.

### What is the root cause of that problem?
The root cause of this problem is the conflicting flex properties applied to both sibling divs. This conflict causes them to share space equally, leading to the unintended resizing of the chat textarea.

### What changes do you think we should make in order to solve the problem?
To address this issue, we propose dynamically adjusting the flex properties of the sibling divs when the textarea is expanded. Specifically, I suggest setting the chat area to occupy 70% of the available space, while the text area takes up the remaining 30%. This adjustment will ensure that the textarea's size remains consistent and does not unexpectedly change when the keyboard appears or disappears.

### What alternative solutions did you explore?
In addition to the proposed solution that involves adjusting the flex properties of the sibling divs, we explored an alternative approach. Instead of relying on flex, an alternative solution would involve setting a fixed height or a maximum height (max-height) for the input group. This alternative approach simplifies the layout management by avoiding complex flex adjustments and may offer an effective way to address the issue.

**Comment by greg-schroeder** [comment]
Looking

**Comment by greg-schroeder** [comment]
@hoangzinh hmm. I see conflicting information about this as well. 🤔

**Comment by greg-schroeder** [comment]
pinging here to see if anyone can be a better sleuth: https://expensify.slack.com/archives/C01GTK53T8Q/p1696260318348419

**Comment by greg-schroeder** [comment]
from @puneetlath:

>  it’s supposed to expand to the size where there is still space for the auto-complete menu, aka the menu that shows if you type @ or :

**Comment by omergr8** [comment]
@hoangzinh 
 I believe it appears unattractive. Having a textarea with that height isn't aesthetically pleasing.

**Comment by greg-schroeder** [comment]
Sorry @hoangzinh been traveling/OOO

**Comment by greg-schroeder** [comment]
Hmm. The fact that it's the same size as when the keyboard is hidden is compelling enough to me to say this isn't worth spending our focus on.
