### ISSUE TITLE
Android - Chat -As 2rows of emojis, user unable to select the last emoji in 1st row in compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28207]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. From phone keyboard, repeatedly select any emoji to fill first row fully and stop selecting after adding few emojis in second row of compose box
4.Place cursor after first emoji and try to drag and select the entire emojis in first row

## Expected Result:
As 2rows of emojis, user must be able to select the last emoji in the 1st row in compose box

## Actual Result:
Placing cursor after first emoji and trying to drag and select the entire emojis in the first row, user unable to select the last emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/168ec758-6f76-45d4-9f1a-6e22c8b902ef

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yh-0218** [comment]
I think this is not a issue.
You can select last emoji on next line first.
