### ISSUE TITLE
[HOLD for payment 2023-10-09] Apply UI fixes to the profile status feature

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#28210]
cc @stitesExpensify - maybe this needs to be tagged with a project? LMK

### Problem

Some UI issues were noticed with the launch of the new Status UI feature:

1. 
> the clear status row should use the same exact styles as any other option row, but looks like they are using rounded corners and not the correct height?

![image (10)](https://github.com/Expensify/App/assets/10736861/56ddb754-1181-42b5-8f37-b5bf20fd703b)

2. 

> If you have no Status, the “Status” label should be vertically centered in the push-to-page row and use our normal font size. Curious why this one didn’t work out of the box, as in, shouldn’t this be a shared global component?

![image (11)](https://github.com/Expensify/App/assets/10736861/9571e8db-0448-42ee-a46a-1fc671dda40d)

### Solution

Do the things
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b059ec2ac57b545</li>
        <li>Upwork Job ID: 1706497543710756864</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Hey @Ollyws, here's the PR to review: https://github.com/Expensify/App/pull/28122

**Comment by Julesssss** [comment]
Whoops, I forgot to assign myeslf to this issue which triggered the random PR review assignment

**Comment by luacmartins** [comment]
Adding Bug label to get a BZ team member assigned to process payment. @mallenexpensify could you please assist?

**Comment by mallenexpensify** [comment]
👋 @Ollyws can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~016b059ec2ac57b545

**Comment by Julesssss** [comment]
I think this has been paid?

**Comment by mallenexpensify** [comment]
Contributor+: @Ollyws paid $500 via Upwork. 

Thanks!
