### ISSUE TITLE
SAML SSO in NewDot - Desktop UI

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#28216]
Tracking GH issue: https://github.com/Expensify/Expensify/issues/294583
Relevant design doc section: https://docs.google.com/document/d/1xa68adybahTxucjSqvPJ2MZCZvaBoP1_vtYk5hTikGU/edit#heading=h.bkhju6ro8k33

**Comment by NikkiWines** [comment]
Focusing on web / mweb first, then on platform specific logic

**Comment by sakluger** [comment]
No updates, @NikkiWines what's the ETA on this one? Would it still make sense to ask Infinite Red to help with this one?

**Comment by NikkiWines** [comment]
We're still trying to get web + mweb over the line but I'm hoping to start on it this week while I'm working 50%. I think it makes sense to open this up to contributors/agencies for all of the platform specific issues

**Comment by sakluger** [comment]
According to @NikkiWines in Slack, Desktop was lumped into https://github.com/Expensify/App/pull/28372. @NikkiWines should we add this issue's link to the PR?

**Comment by NikkiWines** [comment]
Yep!

**Comment by NikkiWines** [comment]
See update [here](https://github.com/Expensify/Expensify/issues/294583#issuecomment-1754774720)

**Comment by sakluger** [comment]
No updates on this one.

**Comment by sakluger** [comment]
This has the same PR as https://github.com/Expensify/App/issues/28215, no separate payment required.

**Comment by NikkiWines** [comment]
This is done - desktop UI is live
