### ISSUE TITLE
[HOLD for payment 2023-10-24] SAML SSO in NewDot - Web and mobile web UI

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#28215]
Tracking GH issue: https://github.com/Expensify/Expensify/issues/294583
Relevant design doc section: https://docs.google.com/document/d/1xa68adybahTxucjSqvPJ2MZCZvaBoP1_vtYk5hTikGU/edit#heading=h.dl0989ayajve

**Comment by sakluger** [comment]
@NikkiWines we just need to pay @situchan the standard rate for their C+ review on this one, right?

**Comment by situchan** [comment]
I was not able to test because I didn't have private domain email. But did enough code review.

**Comment by sakluger** [comment]
@situchan I created an Upwork job and send you an offer, let me know once you've accepted, thanks!

https://www.upwork.com/jobs/~01e0bbe223c4c2309d

**Comment by sakluger** [comment]
All paid out, thank you!
