### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Web - Room - Search list can be opened with CMD + K in public room as anonymous user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a public room as an anonymous user like https://staging.new.expensify.com/r/6874216302070473
2. Click on the search icon.
3. Close the login menu.
4. Use the shortcut CMD + K.

## Expected Result:
Login menu will open when using the shortcut CMD + K, just like when clicking on the search icon in Step 2.

## Actual Result:
The search list is opened when using CMD + K.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.74-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e89e0a30-f5e8-48b8-be03-200c3c445d27

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7ac225db079b27f</li>
        <li>Upwork Job ID: 1706839068229685248</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27126702</li>
<li>kushu7 | Contributor | 27126704</li>
</ul></li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
adding external.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- Anonymous user can access new chat page

### What is the root cause of that problem?

- Currently, when pressing "Ctrl + K" without login, we still allow the user to open the search modal https://github.com/Expensify/App/blob/7d1f5c64168d0bb70c204876a1da7ffa447e96d4/src/libs/Navigation/AppNavigator/AuthScreens.js#L167-L180

### What changes do you think we should make in order to solve the problem?

- When user pressing  "Ctrl + K", we need to redirect user to login modal like below:
```
this.unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
            searchShortcutConfig.shortcutKey,
            () => {
                interceptAnonymousUser(() => {
                    Modal.close(() => {
                        if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
                            return;
                        }
                        return Navigation.navigate(ROUTES.SEARCH);
                    });
                });
            },
            searchShortcutConfig.descriptionKey,
            searchShortcutConfig.modifiers,
            true,
        );
```
- The interceptAnonymousUser function has been used in other sections in our source code, used to check if the user is an anonymous user:
```
const isAnonymousUser = Session.isAnonymousUser();
const interceptAnonymousUser = (callback) => {
    if (isAnonymousUser) {
        Session.signOutAndRedirectToSignIn();
    } else {
        callback();
    }
};
```
### What alternative solutions did you explore? (Optional)

- We can also disable the event listener when pressing "Ctrl + K" without login like:
```
 if (!Session.isAnonymousUser()) {
            this.unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
                searchShortcutConfig.shortcutKey,
                () => {
                    Modal.close(() => {
                        if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
                            return;
                        }
                        return Navigation.navigate(ROUTES.SEARCH);
                    });
                },
                searchShortcutConfig.descriptionKey,
                searchShortcutConfig.modifiers,
                true,
            );
        }
```
### Result:

Solution 1:

[Screencast from 29-08-2023 17:31:39.webm](https://github.com/Expensify/App/assets/141406735/23f5189a-158c-464a-aef8-c89e0d2c8af0)

**Comment by pradeepmdk** [comment]
got it Thanks let me raise it separately.

**Comment by pradeepmdk** [comment]
@0xmiroslav ya yes we need to hide that as well.

**Comment by pradeepmdk** [comment]
but when you click any menu on settings it will goes to login screen

**Comment by zanyrenney** [comment]
any update on progress here @0xmiroslav ?

**Comment by zanyrenney** [comment]
Thanks, over to you @AndrewGable !

**Comment by zanyrenney** [comment]
@kushu7 requires payment [offer](https://www.upwork.com/nx/wm/offer/27126704) (Contributor) - PAID $500
@0xmiroslav requires payment [offer](https://www.upwork.com/nx/wm/offer/27126702) (Reviewer)fuow - paid $500

no urgency bonus due to 10 day merge time.
no reporting bonus due to applause report.

**Comment by AndrewGable** [comment]
Yes this was on hold for 10 days, it was reviewed/merged in 3 days after the hold. cc @zanyrenney
