### ISSUE TITLE
Bank account - Validation error disappears when invalid website like https://www.goog is entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace > Bank account > Connect manually.
3. Fill in all the information and proceed to Step 3 (Personal information).
4. Return to Step 2 (Company information).
5. Leave the Company website field with invalid website like https://./
6. Click Save & continue to make the error show up.
7. In the Company website field, change the website to https://www.goog/
and https://www.google./

## Expected Result:
When invalid websites like https://www.goog/
and https://www.google./
are entered, the error will remain

## Actual Result:
When invalid websites like https://www.goog/
and https://www.google./
are entered, the error disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2ebe4225-5f46-4267-8858-7c762d949e91

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
![2023-09-28_15-28-02 (1)](https://github.com/Expensify/App/assets/42940078/831d8f06-4a80-42da-9f23-650ab94a2ab8)

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.27-1


https://github.com/Expensify/App/assets/78819774/67f53683-22dd-46d9-938a-bc9a9b7884cd

**Comment by sophiepintoraetz** [comment]
Need to confirm the reproducibility and that the platforms are correct.

**Comment by sophiepintoraetz** [comment]
@lanitochka17 - can you please double-check the steps **before reopening?** I still cannot reproduce.
![2024-01-30_15-40-25 (1)](https://github.com/Expensify/App/assets/42940078/6c68843c-dcce-414a-b887-c47b4efbc8f3)
