### ISSUE TITLE
[$500] Web -  LHN flickers

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28287]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on a chat
3. The LHN goes crazy

## Expected Result:
LHN shouldn’t flicker

## Actual Result:
LHN flickers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-2 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0e738d17-8bd9-40b0-875d-a268d28088a5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695709224416519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017aee2928543ae2cd</li>
        <li>Upwork Job ID: 1707516523187257344</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
I cannot recreate this behavior, although I have at times experienced it myself. When testing now, I experienced a similar behavior but in the chat report window, not the LHN. It eventually went away after clicking through all the chats.

https://github.com/Expensify/App/assets/10925636/ba992db5-ddcc-4210-af1a-16f8e219a554

From @jliexpensify in the bug report chat:
<img width="402" alt="image" src="https://github.com/Expensify/App/assets/10925636/bdb6e619-08d1-41b2-b313-20db6394244d">

I had this thought while testing after reviewing your video. I can't scroll down like you can and have that gap but it is familiar to me so I am pretty sure it matches when I have experienced this in the past. 

I'll make a fresh recreation attempt tomorrow as well.

**Comment by strepanier03** [comment]
Confirmed with @jliexpensify that they're still getting the seizure treatment in the LHN.

**Comment by strepanier03** [comment]
I cannot recreate it, so marking needs repro and sending external for some ideas.

**Comment by strepanier03** [comment]
Note, I'm not sure if this is External or Internal and at this point it's a mystery how to reliably recreate this behavior.

**Comment by strepanier03** [comment]
We're okay Melvin, waiting for some input.

**Comment by jliexpensify** [comment]
Lets close this! I'm on v1.3.76-1 and it's...stopped.

Who knows...no-one but me could reproduce it last week. Perhaps lets chalk it down to the Balinese humidity destroying my laptop?
