### ISSUE TITLE
Request money - Wrong merchant was selected from the receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on the "+" button
3. Click on the "Request money" button
4. Click on the "Scan" button
5. Click on the "Choose File" button
6. Choose Receipt.pdf (attached to the issue)
7. Type in any email address
8. Click on the email address
9. Click on the "Request" button
10. Click on the receipt
11. Refresh the browser a few times to see if the process is finished
12. Click on the finished receipt

## Expected Result:
The issuer of the receipt should be the merchant, not the text in the logo

## Actual Result:
The receipt was scanned and for the merchant, the logos text was selected instead of the provider "Bemutató Cég Kft."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.74_0
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d5967c34-17ec-4bc3-a8fd-7430a3133613

[roniiiiiiiiiiiiiiiiiiii.pdf](https://github.com/Expensify/App/files/12732577/roniiiiiiiiiiiiiiiiiiii.pdf)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
So this is actually not a bug. Smartscanners are advised to take the logo as the merchant name, so this is how that receipt is processed. This is an internal process that cannot be changed, so this is not a bug 👍
