### ISSUE TITLE
Chat - Only last message is divided with green line when User mark convo in LHN as Unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28281]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. User A open staging.new.expensify.com
2. In LHN User A mark random conversation as Unread
3. User B send few messages to User A

## Expected Result:
All new messages should be divided with green line meaning that they are unread

## Actual Result:
Only the last message is divided with green line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b045e75b-623f-4e39-9278-35fccb958ced

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
I don't think this is a bug

**Comment by Christinadobrzyn** [comment]
I don't think this is a bug either... It looks like the green line is showing on the last message which is expected when you change the screen. Going to close this without action.
