### ISSUE TITLE
[$750] IOS - Opening an attachment (image) in a chat with many uploaded images takes a long time to load

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login in NewDot
2. Open the chat conversation with many uploaded images

## Expected Result:
Attachments are loaded without delay

## Actual Result:
Opening an attachment (image) in a chat with many uploaded images takes a long time to load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**1.3.74.1
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695519097466029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a247d4d8f51d5b7</li>
        <li>Upwork Job ID: 1708808579350888448</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment]
Waiting for proposals

**Comment by flaviadefaria** [comment]
Same...

**Comment by flaviadefaria** [comment]
Bumped to bounty to see if we get any proposals.

**Comment by flaviadefaria** [comment]
@zanyrenney I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by zanyrenney** [comment]
I think this is a broader issue related to performance. I don't think tackling this in this single issue is going to be productive. Looks like we have irons in the fire for this, e.g. here https://github.com/Expensify/App/issues/28157

CLosing.

**Comment by marcaaron** [comment]
I am not sure this should be closed or that it will be resolved by adding image compression. Even if you compressed the images we still try to load every single image that has ever been shared in a chat. The experience is arguably worse than just opening one image at a time (without a carousel) because it takes ages for it to finish. The more images in a chat history the slower it will be to open the carousel.

**Comment by marcaaron** [comment]
Maybe it needs a champion. Or could be deprioritized. But the existing feature sucks IMO.
