### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Dev: Request Money - The app crashes when clicking on the currency option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28317]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Request money"
3. Click on the currency option

## Expected Result:
The app should not crash

## Actual Result:
The app crashes when clicking on the currency option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native -requested
- [ ] Android / Chrome -requested
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/82471ca4-c4c5-4e3b-b2d1-23d29e936f8d

https://github.com/Expensify/App/assets/93399543/ea46c8a1-8afe-41ab-8100-a62713fa4dea

https://github.com/Expensify/App/assets/93399543/5d5458cb-50ea-4fae-a0f9-4b316ec945db

https://github.com/Expensify/App/assets/93399543/ba2202c3-f909-4384-8b8f-22c774ba08f9

**Expensify/Expensify Issue URL:**
**Issue reported by:** ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695796696023189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cb9c04584439771</li>
        <li>Upwork Job ID: 1707041619621773312</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27157044</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
I don't see any BZ member added. @bernhardoj Can you assign the original C+ here for the review? or another C+? Because I am afk right now.

**Comment by mananjadhav** [comment]
@sonialiap No payouts here as this was a regression. Also unassigning myself.

**Comment by situchan** [comment]
Please assign me here as I reviewed [PR](https://github.com/Expensify/App/pull/28319)

**Comment by sonialiap** [comment]
Due to this having been a regression, not making payments

https://github.com/Expensify/App/issues/28317#issuecomment-1743303514

**Comment by situchan** [comment]
@sonialiap I was not involved in original issue/PR which caused this regression, so I am eligible.

**Comment by situchan** [comment]
> @sonialiap I was not involved in original issue/PR which caused this regression, so I am eligible.

bump ^

**Comment by situchan** [comment]
> I was not involved in original issue/PR which caused this regression, so I am eligible.

@sonialiap bump ^

**Comment by situchan** [comment]
> @sonialiap I was not involved in original issue/PR which caused this regression, so I am eligible.

@sonialiap bump ^

**Comment by sonialiap** [comment]
Offer sent

**Comment by situchan** [comment]
I already got offer [here](https://github.com/Expensify/App/issues/28317#issuecomment-1759228746)

**Comment by sonialiap** [comment]
Payment sent ✔️

**Comment by ayazhussain79** [comment]
@sonialiap could you please check am i eligible for reporting bonus?

**Comment by sonialiap** [comment]
Checking!

**Comment by sonialiap** [comment]
@ayazhussain79 Ah yes of course! Thank you for bringing it up 👍 Offer sent

Reporting $50

**Comment by ayazhussain79** [comment]
@sonialiap offer accepted, Thank you

**Comment by sonialiap** [comment]
Paid ✔️
