### ISSUE TITLE
[$500] Dev: Request Money - The app crashes when clicking on the currency option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Request money"
3. Click on the currency option

## Expected Result:
The app should not crash.

## Actual Result:
The app crashes when clicking on the currency option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.74-2
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ab45342e-f7c6-4b74-884a-82cd38f6a91b

https://github.com/Expensify/App/assets/93399543/035819dd-8a56-4ec5-b03c-2915e0b93db2

https://github.com/Expensify/App/assets/93399543/ec2cfd92-65e0-4d3c-9bd1-47c921eeec15

https://github.com/Expensify/App/assets/93399543/28629b71-e467-4246-9742-f7e551f90451

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695796696023189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162ea1a98f3244cc9</li>
        <li>Upwork Job ID: 1707063155171962880</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
duplicate #28317
