### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Dev: Distance -  Infinite loop running set camera after select waypoint.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the app locally on native Android/iOS.
2. Go to file `src/components/MapView/MapView.tsx` and add console.log inside useFocusEffect > useCallback.
3. Go to the app, and click fab icon > request money > distance.
4. Add waypoint and notice the console.log inside useFocusEffect > useCallback is logged infinity.

## Expected Result:
The useFocusEffect > useCallback should run once.

## Actual Result:
The useFocusEffect > useCallback run Infinite.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.74-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/07b7d75c-4e53-4e8c-bfd4-f687155f7edc

https://github.com/Expensify/App/assets/93399543/93a68bad-d7cf-428d-827c-dfccada63ef1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695754900325509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3599c42c6c62223</li>
        <li>Upwork Job ID: 1707091998614892544</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27123589</li>
<li>ahmedGaber93 | Contributor | 27123590</li>
<li>ahmedGaber93 | Reporter | 27123592</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kbecciv** [comment]
Proposal by: @ahmedGaber93
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695754900325509

## Proposal
from: @ahmedGaber93
### Please re-state the problem that we are trying to solve in this issue.
[Distance] native - Infinite loop running set camera after select waypoint.
### What is the root cause of that problem?
inside useFocusEffect >  useCallback we have cleanup `setIsIdle(false)` to call after navigation blur the screen.
the root cause here is the cleanup will clean **every time dependency change** not only on blur and this what docs say  [here](https://reactnavigation.org/docs/use-focus-effect/#when-to-use-focus-and-blur-events-instead).
> The cleanup function runs whenever the effect needs to cleanup, i.e. on blur, unmount, **dependency change** etc. It's not a good place to update the state or do something that should happen on blur. You should use listen to the blur event instead:
So when the map `onMapIdle` set  `isIdle` true, the useFocusEffect will run and set the camera and in the cleanup will change `isIdle` to false, then the camera changing will trigger `onMapIdle` to set  `isIdle` true, and changing `isIdle` from false to true is a useCallback deps changes that will run the useCallback and cleanup again in infinite.
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/components/MapView/MapView.tsx#L31-L65
### What changes do you think we should make in order to solve the problem?
As docs say and linked in root because **You should use listen to the blur event instead**:
We need to run clean up only when blur by moving it out `useFocusEffect`, this will confirm after `onMapIdle` set `isIdle` true once there is no cleanup will change it false, so when `onMapIdle` set it again from true to true after camera changing it not run the callback again because it is already true and there is no any deps changes.
```javascript
const navigation = useNavigation();
useEffect(() => {
    const unsubscribe = navigation.addListener('blur', () => {
        setIsIdle(false);
    });
    return unsubscribe;
}, [navigation]);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by neil-marcellini** [comment]
I would like to review proposals and PRs for this, so assigning myself now.

**Comment by neil-marcellini** [comment]
I'll check out the proposal a bit later today.

**Comment by neil-marcellini** [comment]
@jjcoffee it would be great if you could take a look first.

**Comment by neil-marcellini** [comment]
@ahmedGaber93's [proposal](https://github.com/Expensify/App/issues/28337#issuecomment-1737845221) looks great. Awesome root cause explanation. Hired!

**Comment by neil-marcellini** [comment]
@ahmedGaber93 please comment here so I can assign you and you can raise a PR.

**Comment by ahmedGaber93** [comment]
Thanks @neil-marcellini!

**Comment by jjcoffee** [comment]
@neil-marcellini Ah apologies, I misinterpreted [your comment](https://github.com/Expensify/App/issues/28337#issuecomment-1738354965) - I thought you wanted to take over the proposal review :sweat_smile:

FWIW agree that the [proposal](https://github.com/Expensify/App/issues/28337#issuecomment-1737845221) looks good - the RCA is correct and the solution is neat 'n tidy!

**Comment by neil-marcellini** [comment]
@ahmedGaber93 again, please comment here so I can assign you

**Comment by ahmedGaber93** [comment]
@neil-marcellini I comment above 2 times. Are I understanding you well or you mean reposting the proposal?

**Comment by ahmedGaber93** [comment]
@neil-marcellini bump.

**Comment by neil-marcellini** [comment]
Sorry for the delay @ahmedGaber93 but I wasn't able to assign you in the github UI until just now. Please create a PR.

**Comment by ahmedGaber93** [comment]
@jjcoffee PR https://github.com/Expensify/App/pull/29270 is ready for review.

**Comment by neil-marcellini** [comment]
Bump @jjcoffee please fill out the checklist

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - looks like this behaviour was always there**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1698307910277279
- Determine if we should create a regression test for this bug. **No - a bit too tricky to test for, I think!**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by jjcoffee** [comment]
Apologies for the delay, checklist now complete! Over to you @anmurali!

**Comment by neil-marcellini** [comment]
Bump @anmurali

**Comment by anmurali** [comment]
Paid. @neil-marcellini do we need to add regression tests?

**Comment by neil-marcellini** [comment]
I agree with @jjcoffee that it's too hard to test and hopefully unlikely to break again. All done!
