### ISSUE TITLE
[Wave 6: Categories] Low: Allow editing the category on split bill 

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#28386]
Just like you can in a money request, if you have a split bill involving a workspace, you should be able to edit the category on it post-creation.

**Comment by rezkiy37** [comment]
Hello, I am Mykhailo from Callstack. I would like to work on this issue.

**Comment by puneetlath** [comment]
Nvm! https://expensify.slack.com/archives/C02MW39LT9N/p1695979690914259?thread_ts=1695898926.814239&cid=C02MW39LT9N
