### ISSUE TITLE
[$500] LHN - LHN scrolling has many gaps

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Have a lot of chats
2. Be in "Most recent" mode
3. Scroll down

## Expected Result:
Chats show up and fill the visible area

## Actual Result:
There are huge gaps of whitespace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6eab8e82-07d0-431c-9a49-4485435f2c77

https://github.com/Expensify/App/assets/93399543/5a17b1a8-339b-49d5-ac99-cf729938db7f

https://github.com/Expensify/App/assets/93399543/15f29afd-3be7-4bb7-9b2e-c1864bb82ce3

https://github.com/Expensify/App/assets/93399543/6d753b92-96d3-4dde-bb24-158acf75610d

https://github.com/Expensify/App/assets/93399543/404718e5-876c-4f2e-a275-06f2d77f1a1a

https://github.com/Expensify/App/assets/93399543/a1f05efe-17e6-4b4e-b91b-c168dd9232b1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695785494130129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180685b2d6f3c0078</li>
        <li>Upwork Job ID: 1707427636871266304</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Linked old issue https://github.com/Expensify/App/issues/20984#issuecomment-1653931031, have been closed by comment https://github.com/Expensify/App/issues/20984#issuecomment-1653931031

**Comment by soro-kuraima** [comment]
this issue isn't reproduced on my device

**Comment by soro-kuraima** [comment]
Contributor details
Your Expensify account email: abhi.asno1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a1badd1881be1926

**Comment by kadiealexander** [comment]
Closing as per the previous issue - this should be fixed when we switch to WishList: https://expensify.slack.com/archives/C01GTK53T8Q/p1690466983745219?thread_ts=1690460451.772389&cid=C01GTK53T8Q
