### ISSUE TITLE
DEV: Send message - Console error on create new chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select send message option
2. Enter email with whom you don't have chat history
3. Click on that user

## Expected Result:
It should not show any console error

## Actual Result:
Console error appears (Cannot set properties of undefined (setting 'preferredSkinTone'))

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev v1.3.74-3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a688b5e9-6b61-4ac8-b53f-1f30155973b9

https://github.com/Expensify/App/assets/93399543/5aa0bd0a-a62f-4592-996f-0afd386d6f8f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695877161884539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012734407620ba58bb</li>
        <li>Upwork Job ID: 1707443549372219392</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by Pluto0104** [comment]
I can't reproduce this. is there any extra step?

**Comment by cg813** [comment]
https://github.com/Expensify/App/assets/57125237/af4b2e48-6e60-4957-9622-8d4e4f423414

Follow the steps to reproduce issue, but couldn't see the console error

**Comment by getusha** [comment]
this [PR](https://github.com/Expensify/react-native-onyx/pull/368) will solve this issue its awaiting a review.

**Comment by getusha** [comment]
Not reproducible anymore.
