### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] Chat - App crashes when replying to message in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Open any chat
3. Send a message
4. Long press on the message and tap Reply in thread

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f3d885a7-b5a0-4794-abaa-63c2b345b18e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment]
Could Onyx related changes for fixing #26627 be causing this?

**Comment by pradeepmdk** [comment]
yes @rojiphil from this PR https://github.com/Expensify/react-native-onyx/pull/329/files

**Comment by mountiny** [comment]
cc @ospfranco @chrispader can you look into this

**Comment by ospfranco** [comment]
assign me plz

**Comment by kbecciv** [comment]
@mountiny Issue is not reproduced on build 1.3.75.2 

https://github.com/Expensify/App/assets/93399543/97f19298-c3dd-420f-b700-a681832cb874

**Comment by garrettmknight** [comment]
@aimane-chnaif can you complete the checklist when you get a chance so I can process payment?

**Comment by garrettmknight** [comment]
Summarizing payments:
- Contributor+: @aimane-chnaif $500

Upwork job/contract: https://www.upwork.com/en-gb/ab/applicants/1712184752085946368/suggested

**Comment by garrettmknight** [comment]
@aimane-chnaif can you accept the contract so I can pay? Thanks!

**Comment by garrettmknight** [comment]
Done
