### ISSUE TITLE
 Task - App crashes when assigning task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #28243
## Action Performed:
1. Launch New Expensify app
2. Tap + > Assign task > Enter any title > Next

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b64881f4-cacb-4930-acd1-3e8b08183b86

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment]
Could Onyx related changes for fixing #26627 be causing this?

**Comment by pradeepmdk** [comment]
due to this PR started crashing https://github.com/Expensify/react-native-onyx/pull/329/files

**Comment by kbecciv** [comment]
Issue is not reproduced on build 1.3.75.2

https://github.com/Expensify/App/assets/93399543/08268659-833d-4fb6-a279-f640c93f6d24

**Comment by mountiny** [comment]
Fixed!
