### ISSUE TITLE
[HOLD for payment 2023-10-10] 3 dot menu - "Mark as Done" appears both as a button and in the 3 dot menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27748
## Action Performed:
1. Access staging.new.expensify.com
2 Sign into a valid account
3. Assign a task to any chat
4. Go to task chat, and observe the 3 dot menu in the upper right corner

## Expected Result:
User expects all items to be within the 3 dot menu now

## Actual Result:
"Mark as complete" is both a green button and also within the 3 dot menu. Both the buttons have the same function so no reason to be repeated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6218350_1695942983600!Mark_as_complete_appears_twice" src="https://github.com/Expensify/App/assets/78819774/04b88418-a828-44ca-a15f-8bee6b6b75a8">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112dfc2656f23b7d3</li>
        <li>Upwork Job ID: 1707555311776894976</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce sounds like we want to remove the Mark As Complete green button in favour of the Mark As Complete in the three dots?

![image](https://github.com/Expensify/App/assets/51066321/eca4170e-f7f5-4b17-bb38-fa00d8eba255)

**Comment by Christinadobrzyn** [comment]
I'm not sure if I should have added the Interal label... I don't know if we need those on deploy blockers...

**Comment by MariaHCD** [comment]
@Christinadobrzyn, I think we should confirm in #expensify-open-source what the expected UI is here :)

Not a deploy blocker, tho!

**Comment by dubielzyk-expensify** [comment]
My take is that we should remove the "Mark as complete" in the overflow menu as it would be too hidden if we remove the green button. The primary action of a task would be to Mark is at complete. So it should look like this:
<img width="520" alt="CleanShot 2023-09-29 at 13 07 33@2x" src="https://github.com/Expensify/App/assets/145416827/1500d7e5-762d-46ac-98dc-da09879661d4">

But keen to hear what @shawnborton or @dannymcclain thinks.

**Comment by dannymcclain** [comment]
I feel like I agree with @dubielzyk-expensify, but am curious if there's some previous decision that's been made that I'm missing. I think about it the same way though—the primary action for a task is to complete it, so it makes sense that it would be an ever-present big green button.

Similar to how on a report/request, the primary action is to pay it, so we show that as a big green button.
<img width="642" alt="image" src="https://github.com/Expensify/App/assets/7516624/26730bf3-9b80-42db-92c3-e5114ae06242">

IMO this action is distinct from and more important than the typical actions you'd find in the 3-dot menu (ie "pin").

**Comment by MariaHCD** [comment]
Thanks for the input, @dannymcclain @dubielzyk-expensify! I agree that we should keep the big green button and remove the item from the dropdown as illustrated [here](https://github.com/Expensify/App/issues/28421#issuecomment-1740324794)

**Comment by ishpaul777** [comment]
## Proposal 

## Problem 
"Mark as Done" appears both as a button and in the 3 dot menu

## Root cause
no root cause, more like a feature improvement

## Changes
> we should keep the big green button and remove the item from the dropdown as illustrated [here](https://github.com/Expensify/App/issues/28421#issuecomment-1740324794)

Considering above to be expected We can below from [here](https://github.com/Expensify/App/blob/main/src/pages/home/HeaderView.js#L97C9-L104C10).

```jsx
if (ReportUtils.isOpenTaskReport(props.report) && canModifyTask) {
            threeDotMenuItems.push({
                icon: Expensicons.Checkmark,
                iconFill: themeColors.icon,
                text: props.translate('task.markAsComplete'),
                onSelected: () => Task.completeTask(props.report),
            });
        }
```

**Comment by MariaHCD** [comment]
Thanks, @ishpaul777 but this issue is labelled as internal and so we're not accepting proposals here.

**Comment by Christinadobrzyn** [comment]
hey @aimane-chnaif do you think a regression test is needed for this?

Payouts due:

Issue Reporter: NA
Contributor: NA
Contributor+: $500 @aimane-chnaif - can you accept my offer in Upwork? 

Eligible for 50% #urgency bonus? No since this was internal

Upwork job is [here](https://www.upwork.com/jobs/~0112dfc2656f23b7d3).

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @aimane-chnaif 

I paid you in Upwork based on this payment overview - https://github.com/Expensify/App/issues/28421#issuecomment-1755989879
