### ISSUE TITLE
[Hold - Split on scanned receipts] Don't show `merchant` and `date` greyed out on split confirmation page

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#28452]
👋 @youssef-lr adding this quick clean up issue for the split confirmation screen I noticed. 

1. Fields that aren't editable shouldn't be greyed out, the rows just don't have a right caret to be able to edit them
2. That said, we should allow someone to set the `merchant` and `date` on the split confirmation page ahead of creating a split
3. Like we do when they set a `description`, the `merchant` and `date` set should also be carried over onto the child requests that get created from the split

<img width="377" alt="image" src="https://github.com/Expensify/App/assets/16232057/634bdb02-afc3-4fe5-a05e-e6d5ea6bb3c2">

CC: @mountiny @JmillsExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182c0d2b618fb678a</li>
        <li>Upwork Job ID: 1707688960169914368</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
I've had this one in my mind and I've already implemented in my draft code!

<img width="382" alt="Screenshot 2023-09-29 at 17 21 20" src="https://github.com/Expensify/App/assets/9680864/6be94d4e-d99c-44b0-83d5-ee7930acd6e4">

**Comment by trjExpensify** [comment]
Perfect!

**Comment by trjExpensify** [comment]
I'm going to drop this to `weekly` and we can retest once split on scanned is out.

**Comment by trjExpensify** [comment]
Almost there on the PRs to retest this! :)

**Comment by trjExpensify** [comment]
This is fixed. Closing!
