### ISSUE TITLE
Send Message - App crashes when User creates new chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27912
## Action Performed:
1. Open ND app
2. Tap on FAB> Send message
3. Fulfill the e-mail field
4. Select the suggested user

## Expected Result:
New chat conversation page should open

## Actual Result:
App crashes when User creates new chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/adc39bb2-6f04-4a71-bb32-f0593a8b6946

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Issue is not reproduced on Biuld 1.3.75-3

https://github.com/Expensify/App/assets/78819774/916053c7-fa7f-4c3f-b029-0bb23912da27

**Comment by mountiny** [comment]
Fixed with the onyx fix update
