### ISSUE TITLE
[$250] Profile-Timezone title is selected when user selects the text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap profile icon
3. Tap profile--timezone--timezone
4. Enter a text and select it

## Expected Result:
Timezone title must not be selected when user selected the text

## Actual Result:
Timezone title is selected when user select the text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6218791_1695977476877!Screenshot_2023-09-29-14-19-05-331_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/958bcaf5-46a0-4ce7-b3b2-70fc9f8611a5)

https://github.com/Expensify/App/assets/78819774/74b59da9-9829-442c-b2e8-cc168a38ef28

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01933dd33bf58f3e13</li>
        <li>Upwork Job ID: 1708378379679748096</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Still reproduced 1.3.75.2
![Screenshot_2023-09-29-23-25-36-281_com android chrome](https://github.com/Expensify/App/assets/93399543/a27d9779-b626-41f1-90f4-8d8a6b5a947b)

**Comment by mountiny** [comment]
Demoting this from a deploy blocker to a normal bug, this is a minor issue which does not block user from doing anything

**Comment by shubham1206agra** [comment]
@mountiny This issue is the same as https://github.com/Expensify/App/issues/28339
I think you can close this one out

**Comment by mountiny** [comment]
Thanks!
