### ISSUE TITLE
iOS - SMS - Code is changed when select it in autofill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Enter SMS account
3. Tap on the suggestion with the code received from messages

## Expected Result:
Code fill out and sms account sign in

## Actual Result:
Code is changed when select it in autofill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b2d42997-8d2f-4b10-8ea0-354cdd586365

![Bug6219107_1695996826378!3](https://github.com/Expensify/App/assets/78819774/3788782d-24e5-47de-9c72-d3ec96992212)

![Bug6219107_1695996826378!3 (1)](https://github.com/Expensify/App/assets/78819774/659f060a-d15f-4951-965a-dd3793885197)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Issue reproduced on build 1.3.75.3 on iPhone 14 Pro/ 17.0.2

https://github.com/Expensify/App/assets/78819774/cf960cc0-af20-4281-ae4a-fe80f854fae2

**Comment by situchan** [comment]
I suspect this came from https://github.com/Expensify/App/pull/24012 as it's only the recent change related to magic code input.

**Comment by wojtus7** [comment]
Hi! I'am the creator of the Magic Code PR mentioned above and tried to repro the issue and fix it but my phone number doesn't seem to work. Do you know any workaround that would help me fix it?

![image](https://github.com/Expensify/App/assets/42337257/08d9ce00-aa86-4e07-b1f7-7b2247dbb694)

**Comment by mountiny** [comment]
@wojtus7 because this is a deploy blocker, should we consider reverting the PR given this is harder to test.

I think is the staging/ production backend env you just need to have real phone number

**Comment by mountiny** [comment]
Revert fixed this issue https://expensify.slack.com/archives/C9YU7BX5M/p1696258649574039?thread_ts=1696257638.565279&cid=C9YU7BX5M we can close it
