### ISSUE TITLE
[HOLD for payment 2023-10-13] Request money - Merchant scan error is not below the merchant field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27735
## Action Performed:
Pre-requisite: user must be logged in and set up a Smartscan where merchant is missing
1. Open chat where Smartscan request was shared
2. Open the Smartscan report

## Expected Result:
Error message for missing merchant should be below de merchant field

## Actual Result:
Error message is shown on the right side of the field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c78ed1ae-c0e0-4bb0-ab2b-7ffeb4f46dde

https://github.com/Expensify/App/assets/78819774/522ffddc-e674-45a8-b5a0-66feb0a44148

https://github.com/Expensify/App/assets/78819774/111706a4-87b8-4ac0-8871-99e60078abce

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01789730632c97595a</li>
        <li>Upwork Job ID: 1708992647321452544</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @Gonals coming from your PR I believe, you might want to handle this internally https://github.com/Expensify/App/pull/27735

**Comment by jliexpensify** [comment]
Not overdue, waiting on Alberto.

**Comment by Gonals** [comment]
Huh. Weird. I'll get to this soon. Next week at the latest, likely sooner. Something must have been overwritten during conflict merge or something, because this was totally working 🤷

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/26141
- The offending PR has been commented on: https://github.com/Expensify/App/pull/26141#discussion_r1348952448
- A discussion in #expensify-bugs has been started: I don't feel this is needed for this case
- Determine if we should create a regression test for this bug: No

**Comment by jliexpensify** [comment]
Is this payment summary correct? Doesn't look like there's a bug reporter of Contributor:

- C+: @s77rt $500

[Upworks job](https://www.upwork.com/jobs/~01789730632c97595a)

**Comment by s77rt** [comment]
@jliexpensify Seems correct

**Comment by jliexpensify** [comment]
Sorry I was out sick at the end of the week - paying now!

**Comment by jliexpensify** [comment]
Paid and post removed!
