### ISSUE TITLE
Request money - A blank page blinks when transitioning between Request money pages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Enter amount
4. Tap Next
5. Select a participant
6. Tap Next

## Expected Result:
The transition between one page to another page is smooth

When tapping Next, a blank page blinks before transitioning to the next page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [x] MacOS / Desktop
- [x] Windows / Chrome

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a221891d-520a-4eba-8882-85e3cfcab0f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Does this issue occur in all platforms? I tested it on chrome on staging and on ios safari and i don't really see the same issue.
Can you retest and confirm if the issue exists and is it on all platforms?

https://github.com/Expensify/App/assets/14356145/ac57facb-70c1-4c79-b7b0-b54ac723b6f6

**Comment by lanitochka17** [comment]
@chiragsalian 
Repro:
Web/Chrome
mWeb/Chrome
Ios
Android
Desktop

Nor repro:
Web/Safari
mWeb/Safari

**Comment by lanitochka17** [comment]
Reproducible:

Windows / Chrome

https://github.com/Expensify/App/assets/78819774/a67b0fe6-4f04-40b3-8d4a-ea35b7f5223a

Android 

https://github.com/Expensify/App/assets/78819774/ead49a6c-1297-4923-9f8b-18707c4c971c

mWeb / Chrome

https://github.com/Expensify/App/assets/78819774/14a002c7-cca7-4d79-b78e-3b3b7b77794e

IOS

https://github.com/Expensify/App/assets/78819774/45e0e499-4d4e-4d87-92f7-c1e20b4b9246

Web / Chrome


https://github.com/Expensify/App/assets/78819774/3e3f4e56-2d1d-4286-9e19-5d9f1de5751d

Desktop

https://github.com/Expensify/App/assets/78819774/4a8ac506-5901-45cb-9685-95feaa87147b

Not repro:

mWeb / Safari

https://github.com/Expensify/App/assets/78819774/cb63d4d4-461c-4fb3-85b6-007c186f6306

Web / Safari

https://github.com/Expensify/App/assets/78819774/1c86c6b7-c505-4684-9235-779ab5dedcc0

**Comment by mountiny** [comment]
cc @tienifr @eVoloshchak could you take a lok this might be regression from this PR https://github.com/Expensify/App/pull/27947

**Comment by mountiny** [comment]
I have tested production now and its not really much better, there is not animation or choppy one, this is not a blocker

https://github.com/Expensify/App/assets/36083550/2593f963-866c-47e0-9756-cf3298ee492e

I think we can close this and go back to  https://github.com/Expensify/App/issues/22388 as it seems like the transitions still not working well even after the PR
