### ISSUE TITLE
[$500] Android - Thread - Back button is not responsive in the parent report after leaving thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27748
## Action Performed:
1. Launch New Expensify app
2. Go to any chat with thread (leave the thread if you're already in one)
3. Tap on the thread > Three-dot menu > Join thread
4. Return to LHN
5. Open the thread report from LHN
6. Tap three-dot menu > Leave thread
7. Tap on the back button
8. Tap on the back button again

## Expected Result:
Back button is responsive and user is able to return to LHN

## Actual Result:
Back button is not responsive and user is stuck at at the parent report of the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9b36c6dd-33a3-4d26-8631-b5f43c2265ba

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b26c9446b581810</li>
        <li>Upwork Job ID: 1708820316584988672</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@dukenv0307 Thanks for the proposal, looks good to me but given this is a deploy blocker, can you highlight which PR caused this issue as that will be the real RCA.

**Comment by wildan-m** [comment]
Hi, I think we can't go with option 2.

Removing an optimistic case will make another tab in the same browser session not navigated to the concierge, it will show "hmmm page not found"

**Comment by wildan-m** [comment]
Agree with @allroundexperts, please revert my PR, I'm on limited availability today

**Comment by mountiny** [comment]
I like the revert approach as this is indeed tricky. @allroundexperts would you be able to make the revert pr for this?

**Comment by wildan-m** [comment]
I'm the author of https://github.com/Expensify/App/pull/24407, I don't see it as regression since the expected requirement change.

IMO the root cause is there is a redundant pop of navigation history, it uses `goBack` and also `CONST.NAVIGATION.TYPE.FORCED_UP` which will replace the navigation.

I'd recommend to make this change:

In `LeaveRoom` function, switch goBack position with goToParent

```
    Navigation.dismissModal();
    if (report.parentReportID) {
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID), CONST.NAVIGATION.TYPE.FORCED_UP);
        return;
    }
    if (Navigation.getTopmostReportId() === reportID) {
        Navigation.goBack(ROUTES.HOME);
    }
    navigateToConciergeChat();
```

For `ReportScreen` add new condition to go to parent if it's a thread

```
        // Navigate to the Concierge chat if the room was removed from another device (e.g. user leaving a room)
        if (
            // non-optimistic case
            (!prevUserLeavingStatus && userLeavingStatus) ||
            // optimistic case
            (prevOnyxReportID && prevOnyxReportID === routeReportID && !onyxReportID && prevReport.statusNum === CONST.REPORT.STATUS.OPEN && report.statusNum === CONST.REPORT.STATUS.CLOSED)
        ) {
            if (report.parentReportID) {
                Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID), CONST.NAVIGATION.TYPE.FORCED_UP);
                return;
            }

            Navigation.goBack();
            Report.navigateToConciergeChat();
            return;
        }
```

**Comment by mountiny** [comment]
Based on this conversation https://expensify.slack.com/archives/C01GTK53T8Q/p1696249324397149?thread_ts=1696016845.380819&cid=C01GTK53T8Q its reproducible in production but just a different steps as we moved the join/leave thread buttons around. The core issue is not a blocker though

https://github.com/Expensify/App/assets/36083550/4e7f44ee-d7ab-4298-a824-4b8def7a35fa

**Comment by wildan-m** [comment]
I can't reproduce it with the latest main.

Now, for expected behavior change, we'll just add this code

```
if (report.parentReportID) {
                Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID), CONST.NAVIGATION.TYPE.FORCED_UP);
                return;
            }

```
 to `ReportScreen` as suggested [here](https://github.com/Expensify/App/issues/28522#issuecomment-1742506182).

again, I feel this is not a regression but a change to the requirement, holding [this](https://github.com/Expensify/App/issues/21518#issuecomment-1741998343) for more weeks seems not to be fair.

@allroundexperts what's your opinion?

**Comment by greg-schroeder** [comment]
I don't think the linked issue should be held as a regression personally. It would be if we hadn't adjusted the behavior, but we did, so... I tend to agree as well

**Comment by greg-schroeder** [comment]
@jjcoffee @allroundexperts @mountiny are we treating this as an open proposal review then and not a regression fix that @wildan-m should take on automatically? a bit confused where to go from here

**Comment by wildan-m** [comment]
@greg-schroeder, based on [this](https://github.com/Expensify/App/issues/28522#issuecomment-1742044696) and [this](https://github.com/Expensify/App/issues/28522#issuecomment-1742921730). [My PR](https://github.com/Expensify/App/pull/24407) is not directly related to this issue. The issue persisted even after my PR reverted.

**Comment by greg-schroeder** [comment]
Yes I understand. Are you still making a proposal to resolve this issue anyway, or no?

**Comment by wildan-m** [comment]
@greg-schroeder, not yet, I'm working on another issue also r[esolve the requirement change](https://github.com/Expensify/App/issues/21518#issuecomment-1749848115) caused by this PR https://github.com/Expensify/App/pull/27127

Also, the last time I checked this issue was not reproducible with the latest main

**Comment by greg-schroeder** [comment]
👍 okay I will try again to reproduce

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
I cannot repro

**Comment by greg-schroeder** [comment]
It seems maybe this was fixed elsewhere - nobody can repro. Going to close then.
