### ISSUE TITLE
[Awaiting Checklist] [$500] Chat - Hovering menu option didn't hightlight the icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any admin or announce room
2. Click on three dot menu.
3. Hover the options
4. Observer the icon.

## Expected Result:
Icon should be highlight when hovering

## Actual Result:
 Icon is not highlight when hovering

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5c344ce9-a192-403f-830c-bc6c27072007

https://github.com/Expensify/App/assets/93399543/2940ece5-b1c5-4cbd-9a96-a69da3e08360

https://github.com/Expensify/App/assets/93399543/4d644389-0577-4848-a806-dbefcacee630

https://github.com/Expensify/App/assets/93399543/e2797bd8-8036-4dca-af51-280d6186f47c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695953603559579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afeb6d58d5ae9d6b</li>
        <li>Upwork Job ID: 1708126153549336576</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 27030886</li>
<li>hungvu193 | Reporter | 27030888</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695953603559579

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The icons from threedots menu are not highlight while hovering on it.
### What is the root cause of that problem?
We added new UI in our threedots menu and adding new property `iconFill` to each item:
https://github.com/Expensify/App/blob/609334065339613d86456f2af87f089e04353ef3/src/pages/home/HeaderView.js#L100
However, in our `MenuItem` logic, if we has `iconFill` props, our icon won't change the color when hovering:
https://github.com/Expensify/App/blob/609334065339613d86456f2af87f089e04353ef3/src/components/MenuItem.js#L198-L204
### What changes do you think we should make in order to solve the problem?
In order to keep the `iconFill` and still able to change color while hovering, we can add a new props called `shouldAcceptHoverState` to our MenuItem, if shouldAcceptHoverState is true, we will get the correct fill color for it.

```javascript

fill={ 
     StyleUtils.getIconFillColorForMenuItem(props.iconFill, shouldAcceptHoverState, props.focused || isHovered, pressed, props.success, props.disabled, props.interactive) || 
     StyleUtils.getIconFillColor( 
         getButtonState(props.focused || isHovered, pressed, props.success, props.disabled, props.interactive), 
         true, 
     ) 
 } 
```

`getIconFillColorForMenuItem` will have similar logic with  `getIconFillColor` (will need to update the color of each state to match the design) but will early return with `props.iconFill`  if `shouldAcceptHoverState` is false


### What alternative solutions did you explore? (Optional)
Remove all the `iconFill` propperty from our threedotMenus.

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Hovering menu option didn't hightlight the icon
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/52f0e3c9ec9ab5c87993672661095f81253bc00d/src/components/MenuItem.js#L198-L204
props.iconFill  is not letting other styles apply.
### What changes do you think we should make in order to solve the problem?
```javascript
fill={
  isHovered || !props.iconFill ? 
    StyleUtils.getIconFillColor(
        getButtonState(props.focused || isHovered, pressed, props.success, props.disabled, props.interactive),
        true,
    ): props.iconFill
}
``` 
This way if the icon is hovered, hovered style will be applied rest normal styles will remain same.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by eVoloshchak** [comment]
@neonbhai's [proposal](https://github.com/Expensify/App/issues/28535#issuecomment-1741788741) looks good to me!

Other proposals suggest retaining the current color of the icons and changing it only on hover, but that is inconsistent with the rest of the app
For instance, on the workspace page the icons are green by default, changing to white on hover, which is in line with @neonbhai's proposal
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/9059945/55943d84-e455-4b2f-8804-3d4600bfce26">

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment]
My bad @hungvu193, you are correct, I missed the alternative solution (I was viewing your proposal on Slack)

Let's proceed with @hungvu193's [alternative solution ](https://github.com/Expensify/App/issues/28535#issuecomment-1741777968)

🎀👀🎀 C+ reviewed!

**Comment by Beamanator** [comment]
@hungvu193 please hold off on creating a PR for this - I'm starting a discussion related to this internally, will post back here when we're ready to go

**Comment by Beamanator** [comment]
Sorry convo still going, will pick this back up very soon

**Comment by twisterdotcom** [comment]
Hey! Sorry for the late chiming in here. I'm slowly returning from parental leave, but I agree that as long as the C+ (here @eVoloshchak) agrees that the original Alternate Solution matches the later proposed on, we should assign the earliest proposer.

There are obviously grey areas here @neonbhai, I understand. One couldn't simply post:

```
Proposal: Do this
Alternate proposal: Do something else
```

And essentially cover everything feasible, but in this case at least there doesn't need to be any questioning of it. It would certainly be interesting to understand _why_ @hungvu193 chose the new `iconFill` solution over removing it, but other than that, I think we can get the PR moving now.

As always, thanks to every contributor involved here - we always hope everything shakes out fairly in the end, but ultimately we have to choose one.

**Comment by eVoloshchak** [comment]
Not overdue
@hungvu193, absolutely, let's get the PR moving along!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27748
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27748/files#r1370607807
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a purely visual bug, I don't think an additional discussion is necessary
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
While the bug isn't impactful, this is a component every user interacts with at some point, so a small regression test would be beneficial here I think

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Go to any chat
2. Click on three-dot menu at the top right
3. Hover over the options (or long press on mWeb and mobile).
4. Verify that icons are highlighted when hovering (or long pressing on mWeb and mobile).

**Do we agree 👍 or 👎**

**Comment by twisterdotcom** [comment]
Sorted.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @eVoloshchak based on [this summary](https://github.com/Expensify/App/issues/28535#issuecomment-1777622240).
