### ISSUE TITLE
[HOLD for payment 2023-10-16] Set up preview builds for HelpDot

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#28531]
Slack context: https://expensify.slack.com/archives/C01GTK53T8Q/p1695766723259829

cc @rushatgabhane 

### Problem
We can easily make mistakes when adding articles to HelpDot. And testing locally requires setup.
To ensure nothing is breaking, an engineer has to review the PR when adding articles to HelpDot. This takes our precious time!!

### Why this is important
We want HelpDot to be mostly maintained by non-engineers. They can create an adjust articles just by creating markdown files. However, they cannot actually test or preview their changes without a dev environment setup.

### Solution
Deploy helpsite PR previews to netlify. It generates a deploy preview for PRs. https://docs.netlify.com/site-deploys/deploy-previews/

**Comment by roryabraham** [comment]
Setup steps:

1. create a free Netlify account
1. deploy existing project using GitHub
1. install Netlify on Expensify/App

**Comment by roryabraham** [comment]
Might need ring0 help for the first step

**Comment by roryabraham** [comment]
Created Netflify account under reactnative@expensify.com – password is in the ring3 bucket in 1P

**Comment by roryabraham** [comment]
@fukawi2 There should be a pending request to configure Netlify with Expensify/App:

<img width="643" alt="image" src="https://github.com/Expensify/App/assets/47436092/82a426e1-7318-4941-8acc-552ca6fd82cb">

**Comment by roryabraham** [comment]
Additional infra discussion: https://expensify.slack.com/archives/C094TGUTZ/p1696058736845509

**Comment by roryabraham** [comment]
Sounds like we might use Cloudflare instead of Netlify for this.

**Comment by roryabraham** [comment]
Tagging in @coleaeason  to help set that up - sounds like it will be easy

**Comment by coleaeason** [comment]
Working on this now, should have it done today or tomorrow.

**Comment by coleaeason** [comment]
PR is up! Builds will fail until that PR is merged.
