### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] [$250] Chat - Console error "Cannot read properties of undefined (reading 'current')" on emoji picker

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Right click or long press any report and click on add reaction
4. Observe that it does nothing and throws console error: Cannot read properties of undefined (reading 'current')

## Expected Result:
App should allow users to open emoji picker for reaction

## Actual Result:
 App does not allow users to open emoji picker for reaction on right click and click on add reaction and it throws console error

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d9d62331-171e-46b5-8374-cd44a69faad0

https://github.com/Expensify/App/assets/93399543/5812dfe1-26ea-44bd-ba60-e670a3b6335f

https://github.com/Expensify/App/assets/93399543/8a6fa6ba-679c-4b33-b21a-e3723e7c4473

https://github.com/Expensify/App/assets/93399543/4f1f2cbb-2439-4980-9235-4350abaaa219

https://github.com/Expensify/App/assets/93399543/377beb57-047b-4f73-858a-093f69d87914

https://github.com/Expensify/App/assets/93399543/27860228-a4ce-4a90-b1b0-71f5ba5e4b95

https://github.com/Expensify/App/assets/93399543/82c93567-12e4-472c-9aa6-eff1edc1720f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696079858252189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103f61623015d853c</li>
        <li>Upwork Job ID: 1708383767969234944</li>
        <li>Last Price Increase: 2023-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 26964631</li>
<li>dhanashree-sawant | Reporter | 26964632</li>
<li>hungvu193 | Contributor | 26982014</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @OlimpiaZurek @gedu @thiagobrez @s-alves10 @hayata-suenaga noting this is a second blocker from the PR, keep an eye out for such regressions, thanks!

**Comment by puneetlath** [comment]
@abdulrahuman5196 friendly reminder on the checklist.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/27221

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/27221/files#r1350610872

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Its a minor bug and won't be benificial to add regression test.

cc: @puneetlath

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
