### ISSUE TITLE
[$500] Android - white border in checkbox while Offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28547]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Go to settings > workspace > members > invite
3. Invite member which is not in list
4. Go to members
5. Select that user

## Expected Result:
It should not show white border

## Actual Result:
 white border appears while Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20230930_161813_New Expensify - Copy](https://github.com/Expensify/App/assets/93399543/7e24b4f9-7831-41ca-9d76-ab46e7012133)

![Screenshot_20230930_161813_New Expensify](https://github.com/Expensify/App/assets/93399543/0b44070a-61d8-49d7-8dba-e47f8f7c6cfa)

https://github.com/Expensify/App/assets/93399543/b17ffaf2-72c1-4193-a701-12936dd9af32

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695988538728789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010099c7efd17d5ffa</li>
        <li>Upwork Job ID: 1708217388635340800</li>
        <li>Last Price Increase: 2023-09-30</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Going to triage this tomorrow.

**Comment by joekaufmanexpensify** [comment]
IMO, it's not worth doing anything to change this. I don't think this is really a bug. It's a minor design inconsistency that isn't really noticeable at all. Closing.
