### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Chat - App does not allow pasting number if numbers has comma in end for english and vice versa

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28548]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. If language is English, write any number and write full stop in the end and copy it eg: '2000.'
4. Paste text in plus->request money and observe that it allows to paste the text
5. Similarly try copy number with comma in middle and observe that app allows to paste
6. Similarly, try copy number with comma in end and observe that now app does not allow to paste the number
7. If language is Spanish, follow all the above steps just use full stop in place of comma

## Expected Result:
App should allow copy pasting number in request money with comma in end as it allows copy paste of number with comma in middle or copy paste of number with full stop in end (English language)

## Actual Result:
 App does not allow copy pasting number in request money with comma in end for English language and it doesn't allow copy paste number with full stop in end for Spanish language

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation:

https://github.com/Expensify/App/assets/78819774/6ab68c3a-2b24-4b20-bbae-497adc963c73

https://github.com/Expensify/App/assets/78819774/f41613df-6ac5-4b36-bf37-df2fe190cb29

https://github.com/Expensify/App/assets/78819774/1eda7d47-0417-4d9e-abee-8fbaf86031bc

https://github.com/Expensify/App/assets/93399543/23b5cc92-239c-4453-a82a-39fd3a187f80

https://github.com/Expensify/App/assets/93399543/66088883-b6e3-4926-a02c-c7d0561d9140

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695835603519559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fcdbf8f05309fae</li>
        <li>Upwork Job ID: 1708219578554970112</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26999991</li>
<li>c3024 | Contributor | 26999997</li>
<li>dhanashree-sawant | Reporter | 26999998</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pasting amount like 20, is not shown in the new request amount page.
### What is the root cause of that problem?
We are using this regex here
https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/libs/MoneyRequestUtils.ts#L45-L48
to validate the amount and this regex requires at least a digit to be followed by comma to be valid.
If the amount is not valid it just sets the previous amount.
### What changes do you think we should make in order to solve the problem?
I think since we are allowing 20. as valid it is reasonable to allow 20, also as valid.
Regex for this would be
```js
const decimalNumberRegex = new RegExp(/^\d+(,\d*)?(\.\d{0,2})?$/, 'i');
```
This accepts 20, but disallows 20,,, this is in line with the present regex allowing 20. but not 20...
We can change the regex if we need a different vaidation
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
, and . are interchanged in Spanish. So we can paste 20, in Spanish but not 20. @Ollyws

**Comment by c3024** [comment]
With the existing regex 20, works for Spanish but not English. 20. works for English but not for Spanish.
With the modified regex 20, and 20. work for both Spanish and English.
> why pasting a trailing comma works for when the language is set to English but not to Spanish?
Which regex does this? As far as I see, existing regex allows 20, for Spanish but not for English. New regex allows 20, allows for both.
I don't see a case where 20, works for English but not Spanish like you mentioned. @Ollyws

**Comment by c3024** [comment]
Once it passes the validity check ',' ('.') are stripped in English (Spanish) here
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/pages/iou/steps/MoneyRequestAmountForm.js#L140
So I think allowing 1,. (or for that matter 1.,) is a non-issue. Restricting regex for these cases is not necessary in my opinion.

**Comment by c3024** [comment]
This is the regex for disallowing ',.' or '.,' anywhere in the string
```js
const decimalNumberRegex = new RegExp(/^(?:(?!,\.)\d+(,\d*)?(\.\d{0,2})?)(?:(?:(?<=\d)\.)(?:(?<=\.)\d*))?$/, 'i');
```
I think since we strip the commas (or dots for Spanish) here
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/pages/iou/steps/MoneyRequestAmountForm.js#L140
better use the regex given in the initial proposal and allow `,.`

**Comment by c3024** [comment]
Once it passes the validity check ',' ('.') are stripped in English (Spanish) here
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/pages/iou/steps/MoneyRequestAmountForm.js#L140
So I think allowing (or disallowing) 1,. (or for that matter 1.,) is a non-issue. Restricting (or allowing) regex for these cases is not necessary in my opinion.

But if we want to restrict to only `,` and `.` we can use this regex
```js
const decimalNumberRegex = new RegExp(/^(\d+(,\d+)*)+(\.\d{0,2})?$|^\d+\.$|^(\d+,)+$/, 'i');
```

**Comment by luacmartins** [comment]
Thanks for reviewing the proposals @Ollyws!

**Comment by c3024** [comment]
PR #28736 ready for review @Ollyws

**Comment by sonialiap** [comment]
@Ollyws review + bonus = $750 - paid ✔️ 
@c3024 fix + bonus = $750 - paid ✔️ 
@dhanashree-sawant report = $50 - paid ✔️
