### ISSUE TITLE
[$500] Web - Cannot open chat when mentioned in nested thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28541]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In a group chat with User A, User B, User C
2. Have User A send a message
3. Have User C create a thread on User A’s message
4. Have User C create another thread within that first thread and mention User A and User B

## Expected Result:
 User B can access the nested thread they were mentioned in because they have access to the parent-most chat

## Actual Result:
User B cannot access the thread

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695954502784429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01155904021319d114</li>
        <li>Upwork Job ID: 1709265029586993152</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Link to discussion where we talked about this internally https://expensify.slack.com/archives/C03U7DCU4/p1695890957289319

**Comment by dylanexpensify** [comment]
reviewing!

**Comment by zsr2531** [comment]
I have cloned the repo (version 1.3.77-2 according to the `package.json`) and cannot repro this issue.

**Comment by paultsimura** [comment]
@dylanexpensify could you please clarify what "cannot access the thread" means here? It's a bit difficult to understand without videos and access to internal discussion context.

**Comment by dylanexpensify** [comment]
@thienlnam can you confirm @paultsimura's question?

**Comment by thienlnam** [comment]
Closing this for a duplicate issue https://github.com/Expensify/App/issues/29108
