### ISSUE TITLE
[$500] Private note - The note item has no hover effect until moving the cursor, while it works fine for back button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28546]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with any account.
2. Open any chat report and click on the header.
3. Go to private note.
4. Click the right arrow to go My notes, keep the cursor in the same place while navigating to the next page.
5. Observe that no hover effect is displayed for the note item until moving the cursor.
6. Repeat the same with back button and observe that the tooltip is appeared without moving the cursor.

## Expected Result:
App should display hover effect for the note item without moving the cursor.

## Actual Result:
The note item has no hover effect until moving the cursor, while it works fine for back button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f352f24a-36ae-4861-8716-98a3b92a1701

https://github.com/Expensify/App/assets/93399543/c7568fec-e88c-4480-83bf-856653ecc3b0

https://github.com/Expensify/App/assets/93399543/ba7d23fe-cdb6-47e4-83ae-c17963bf562a

**Expensify/Expensify Issue URL:**
**Issue reported by:**@ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695987108079269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edee5e50fa23328a</li>
        <li>Upwork Job ID: 1708213962121248768</li>
        <li>Last Price Increase: 2023-09-30</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
Working fine for me

https://github.com/Expensify/App/assets/57568571/e829ac06-a9f5-443c-9f1d-b0c9ea89cb27

**Comment by anmoluiux** [comment]
@kbecciv Looking into this issue...
Will revert in a while.

**Comment by anmoluiux** [comment]
Contributor details
Your Expensify account email: anmol.uiux@gmail.com
Upwork Profile Link: [Anmol.UIUX](https://www.upwork.com/freelancers/~01d7c3896bbdf6b35b)

**Comment by abzokhattab** [comment]
I can work on this issue

**Comment by abzokhattab** [comment]
I can work on this issue

**Comment by zanyrenney** [comment]
This seems like a small inconsistency and UI polish as opposed to an actual bug. It does not affect user performance or workflows at all. Closing.
