### ISSUE TITLE
[$1000] Notification -  Android device did not receive notifications when using the same account for two devices

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28552]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in the account A for two devices(Android and IOS apps)
2. Using account B(on other devices) -> send messages to account A
3. Observe the notifications of two devices

## Expected Result:
Both devices will receive the same notification when Account B sends the message to Account A

## Actual Result:
Only IOS receives the notification when account B sends the messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/144d7054-6a52-48ff-b316-b6b03ce17f9c

https://github.com/Expensify/App/assets/78819774/bc00ccf9-9d7b-4903-b5be-31e067fd728a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @thuyle04

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695977608036979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165c25b3d0673e3f9</li>
        <li>Upwork Job ID: 1708235210736353280</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Price increased to get more proposals.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment]
@thuyle04 could you please confirm if this is still reproducible?

**Comment by kadiealexander** [comment]
Closing as not reproducible. @thuyle04 please let us know if this is still reproducible for you.
