### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Log in - App doesn't switches to first digit on click on didn't recieved a magic code click

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If login then logout
3. Enter any contact and continue
4. Shift focus to any other digit then 1st digit and wait for some time to enable 'Didn't recieved a magic code' link
5. when enabled, click on it and observe that app doesn't reset to first digit

## Expected Result:
App should reset focus to first digit on click on 'Didn't recieved a magic code' link

## Actual Result:
App doesn't reset focus to first digit on click on 'Didn't recieved a magic code' link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d2accf7c-4dad-4ba0-8e29-21e8ec5fb780

https://github.com/Expensify/App/assets/78819774/19216eb8-a88e-4296-b94e-6b7276b4e608

https://github.com/Expensify/App/assets/78819774/e4b41fa2-65a3-43de-935f-2f7e82b7ac2b

https://github.com/Expensify/App/assets/78819774/ffded571-dd8d-4031-9103-0a85177b6379

https://github.com/Expensify/App/assets/78819774/dc6e2889-c536-436c-b93f-e22047e4e38b

https://github.com/Expensify/App/assets/78819774/3e9dcacf-eac8-4c80-be6b-9a8219ff7f7b

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695578315038989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019251bb2b1418cd16</li>
        <li>Upwork Job ID: 1708239064011689984</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26989941</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by marcaaron** [comment]
If there is a place where we are already handling this then I think the solution would be to move that logic to a central location instead of duplicate it.

Why do we have two files called `BaseValidateCodeForm`? They look very similar to me ☹️

**Comment by marcaaron** [comment]
Interesting, but what is similar about them? This code you are proposed to add is similar to some others. Can we encapsulate it somehow? Or is it not worth doing?

**Comment by marcaaron** [comment]
I don't see how either comment relates to my concern about code reuse. Things can be different and share code.

**Comment by JmillsExpensify** [comment]
Can I get a payment summary on this issue?

**Comment by anmurali** [comment]
- [ ] @allroundexperts $500 (Eligible for Manual Requests) (Contributor)
- [ ] @aimane-chnaif $500 [offer](https://www.upwork.com/nx/wm/offer/26989941) (Reviewer)
- [ ] @dhanashree-sawant $50 (Issue Reporter)

**Comment by anmurali** [comment]
Added bonus

**Comment by anmurali** [comment]
I am closing this as this is just pending @allroundexperts payment on ND.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on BZ summary.
