### ISSUE TITLE
[HOLD for payment 2023-10-20] [$500] Setting - Menu Item can not click but still show pointer cursor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Setting => Share code
2. Click "Copy URL to clipboard"
3. Observe the copied message appear, hover over it and see can not click but the pointer cursor appear

## Expected Result:
 It should be the default cursor

## Actual Result:
 Pointer cursor appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1629ab11-fb4b-4d20-9c1a-b639858cdd5a

https://github.com/Expensify/App/assets/78819774/de2e2405-5300-4dd3-930d-1b21e54b7202

https://github.com/Expensify/App/assets/78819774/1bd13b59-4ce0-43c8-a9db-68debaf6db42

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695985262272999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173c232e99dc92430</li>
        <li>Upwork Job ID: 1708571281166315520</li>
        <li>Last Price Increase: 2023-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 27046639</li>
<li>namhihi237 | Reporter | 27046641</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by aromeral98** [comment]
My proposal for fixing the issue it's
-Add the pseudo-class :disabled to buttons CSS, so if the button is disabled(Can't be clicked) the cursor will be default.

**Comment by mallenexpensify** [comment]
@thesahindia , can you please review the proposals above?  
Thx

**Comment by neil-marcellini** [comment]
> @namhihi237's [proposal](https://github.com/Expensify/App/issues/28565#issuecomment-1742250391) looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed

I agree

**Comment by neil-marcellini** [comment]
Bump @thesahindia

**Comment by mallenexpensify** [comment]
Issue reporter: @namhihi237 paid $50 via Upwork
Contributor: @namhihi237 paid $750 via Upwork, inc. urgency bonus
Contributor+: @thesahindia due $750 via NewDot

@thesahindia plz complete the BZ checklist. Thx

**Comment by JmillsExpensify** [comment]
$750 payment approved for @thesahindia based on [this summary](https://github.com/Expensify/App/issues/28565#issuecomment-1781511609).
