### ISSUE TITLE
[HOLDING on #26538][$500] Distance - Changing stop and finish causes TDB in distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click request money
3. Click distance
4. Add 3 address in distance (Start, finish and one stop) (eg: Kent, WA USA ; Kirkland, WA, USA ; Seatle, WA, USA )
5. Click next and select any workspace, observe that it properly provides us with miles and amount
6. Go back twice and exchange value of stop and finish and again continue to reach amount page
7. Observe that now it displays TBD in amount and it doesn't display route in map above amount

## Expected Result:
App should modify amount and miles and route if we exchange stop and finish values

## Actual Result:
App displays TBD in amount and in miles and also does not display route if we exchange stop and finish values

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f4d4a978-b72c-49ee-90eb-24dd41cac95c

https://github.com/Expensify/App/assets/78819774/c0a496d4-466f-4022-8b41-b15665e98692

https://github.com/Expensify/App/assets/78819774/3e886e3a-e05d-4b02-a8e2-d4f3c28e9c91

https://github.com/Expensify/App/assets/78819774/b8d5a61f-daba-40aa-bcef-21cc326af657

https://github.com/Expensify/App/assets/78819774/c6f802e1-ac06-4a97-a4a1-35cd883a86ae

https://github.com/Expensify/App/assets/78819774/314438d9-ba06-4911-9ac5-d883ca0e8dda

https://github.com/Expensify/App/assets/78819774/7f790592-ea22-4fe3-9c20-a41521efda38

https://github.com/Expensify/App/assets/78819774/43698fb8-dee9-48b3-848f-9daee9c88466

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696063336006619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce183a2973a17c45</li>
        <li>Upwork Job ID: 1708579977980162048</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mvtglobally</details>

**Comment by paultsimura** [comment]
The RCA is the same as in https://github.com/Expensify/App/issues/28129 - there was a little discussion in the original slack thread.

**Comment by DylanDylann** [comment]
ref: https://github.com/Expensify/App/issues/26946#issuecomment-1740453516

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
That's great! We'll keep this open one more week and see if the behavior is reproducible during the next KI tests.

**Comment by johncschuster** [comment]
@mvtglobally can you check to see if this behavior is still reproducible?

**Comment by johncschuster** [comment]
@mvtglobally bump!

**Comment by mvtglobally** [comment]
Updating shortly

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
