### ISSUE TITLE
[HOLD for payment 2023-10-24] [Reassure] Migrate some of the GooglePlacesUtilsTest to reassure test framework

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28585]
### Problem

We have implemented one of the GooglePlacesUtilsTests so it measures time of some function execution in a test framework which is not ideal for that. This test is repeatadly flaky as a result, for example look here https://github.com/Expensify/App/actions/runs/6377422632/job/17306058621

### Solution

First, lets skip these tests and then migrate them to Reassure framework, once we can do that. Currently this exact type of tests is not supported according to Callstack

**Comment by koko57** [comment]
Commenting for @adhorodyski as Adam is ooo. 😃

**Comment by koko57** [comment]
@mountiny could you please assign @adhorodyski instead of me? 🙂

**Comment by mountiny** [comment]
I made the PR to skip the flaky tests, no we just need to wait for Reassure to support such tests

**Comment by adhorodyski** [comment]
@mountiny i will happily pick this up after we merge https://github.com/callstack/reassure/pull/271 :)

**Comment by mountiny** [comment]
@adhorodyski is there anything we can do to help with the PR? If you need to allocate time for it or another engineer it makes sense to me to push this one ahead

**Comment by adhorodyski** [comment]
I now work 50/50 between the flashlist migration under https://github.com/Expensify/App/issues/28902 & this PR.
We should have it merged shortly (matter of days) as only docs & a simple output formatter are missing, meaning the implementation is actually there. 
I will definitely let you know if anything changes and I'll need any help with it!

**Comment by mountiny** [comment]
Thanks Adam!

**Comment by JmillsExpensify** [comment]
Are any additional PRs due for this issue? It looks like no payments are due, so I think we might be ok to close it?

**Comment by JmillsExpensify** [comment]
No payments are required on this issue, so the main question left is whether a regression is required. @koko57 / @adhorodyski thoughts?

**Comment by mountiny** [comment]
Nope this was an update to automated tests so all good here, thanks
