### ISSUE TITLE
[HOLD for payment 2023-10-18] [Wave 6: Categories] Make categories accessible on bill split after creation

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#28593]
In https://github.com/Expensify/App/pull/27936 we made categories selectable on bill split reports. Now, we also need to make that category selection visible (but not editable) on the bill split post-creation. 

cc @rezkiy37

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by puneetlath** [comment]
No payment needed. Closing. Thanks y'all!
