### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Workspaces - Cursor opacity is not reduced when checkbox is disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Settings > Workspaces > Select any workspace > Members
2. Remove all members if there are any except admin
3. Observe the opacity of checkbox on admin's profile and select all section

## Expected Result:
The opacity of select all checkbox should be reduced.

## Actual Result:
 The opacity of select all checkbox is not reduced.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d59cf880-393c-4e95-be14-ebca223c5d3f

https://github.com/Expensify/App/assets/115492554/889b3518-6aae-4d23-90f2-32473eaff8d3

https://github.com/Expensify/App/assets/115492554/667a8df7-bf42-4238-852c-eb2ac97aa83d

https://github.com/Expensify/App/assets/115492554/5616c49e-bce2-4192-9ddb-78bf8e24a544

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696154784010669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa6384e69aca5821</li>
        <li>Upwork Job ID: 1708803588818010112</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27044986</li>
<li>Krishna2323 | Contributor | 27044989</li>
<li>krishna2323 | Reporter | 27044992</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Select All option checkbox opacity is not reduced if disabled
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ab48f3f531c5aa6e36ca1a850613f827c880a320/src/components/Checkbox.js#L104-L113
We are not adding styles.buttonOpacityDisabled style while disabled the checkbox

### What changes do you think we should make in order to solve the problem?
Need to pass props.disabled && styles.buttonOpacityDisabled in the styles array of checkbox like.
```javascript
                <View
                    style={[
                        StyleUtils.getCheckboxContainerStyle(props.containerSize, props.containerBorderRadius),
                        props.containerStyle,
                        props.isChecked && styles.checkedContainer,
                        props.hasError && styles.borderColorDanger,
                        props.disabled && styles.cursorDisabled,
                        props.isChecked && styles.borderColorFocus,
                    ]}
                >

``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by saranshbalyan-1234** [comment]
##Proposal
Updated https://github.com/Expensify/App/issues/28597#issuecomment-1742834514

**Comment by laurenreidexpensify** [comment]
@hoangzinh what do you think about the proposals?

**Comment by saranshbalyan-1234** [comment]
hi @hoangzinh there is a recent change is the selected proposal, the previous proposal was pointing to a different prop, please check

**Comment by saranshbalyan-1234** [comment]
@Krishna2323 dont you think of you would have taken few seconds to fix your proposal at that time, then it would come as the second proposal?

**Comment by saranshbalyan-1234** [comment]
Ahhh I see now, you are reporter as well
Sorry for confusion

**Comment by laurenreidexpensify** [comment]
bump @chiragsalian

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @Krishna2323

**Comment by laurenreidexpensify** [comment]
Payment Summary -  

- External issue reporter - @Krishna2323 - $50, payment issued in Upwork 
-  Contributor that fixed the issue - @Krishna2323 - $500 + 50% urgency bonus = $750, payment issued in Upwork 
-  Contributor+ that helped on the issue and/or PR - @hoangzinh - $500 + 50% urgency bonus = $750, payment issued in Upwork

**Comment by laurenreidexpensify** [comment]
@Krishna2323 sorry I paid the jobs the wrong way around in Upwork, but in total you should have received $800 👍

**Comment by laurenreidexpensify** [comment]
@hoangzinh please advise on the checklist thanks
