### ISSUE TITLE
[$500] Closing attachment preview reloads chat in background

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28602]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report with image attachment in it or send any attachment to any user and open that report
3. Click on that attachment and copy preview link
4. Open private notes for that report user and paste URL in it
5. Open URL by clicking on link from My Notes
6. Click ESC or close button in preview and observe that chat reloads in background

## Expected Result:
App should not reload chat when we close any attachment preview

## Actual Result:
App reloads the chat in background on opening attachment preview chat from private notes and closing it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/669a32f0-cb3b-46d6-b689-91a191c6ae68

https://github.com/Expensify/App/assets/115492554/f1ca96dc-782b-437c-9d87-5d778ae96e7c

https://github.com/Expensify/App/assets/115492554/5f5b0c66-3966-4b8c-aeae-0bfb28f5b2f1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696180664903379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ee3d0abb6f9c5b0</li>
        <li>Upwork Job ID: 1708809058358607872</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
I think this is BE issue. BE returns the error.

**Comment by tjferriss** [comment]
I don't view this as a bug as it doesn't impact the user. It makes sense to me that the page would reload when you clickthrough on a link. I'm going to close the issue.
