### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Chat - The three-dot menu fails to close after clicking on "Pin"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "New room" section.
2. Enter a name for the room and select the workspace.
3. Set the visibility of the room to "Public"
4. Click on the "Create room" button.
5. Go to "Share code" > "Copy URL to clipboard"
6. Open another browser where you are not signed in.
7. Paste the copied URL.
8. Click on three dots for menu and click on "Pin"

## Expected Result:
Upon clicking "Pin" the three-dot menu should close

## Actual Result:
The three-dot menu remains open after clicking on "Pin"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7b610994-3b6f-4d12-a552-e8fdb054326a

https://github.com/Expensify/App/assets/93399543/da844e9b-bf54-4194-8aec-d3e5194f20ad

https://github.com/Expensify/App/assets/93399543/3b0045d4-2c67-46c0-832a-69915367f464

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695981995544409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cbad69c4c13b118</li>
        <li>Upwork Job ID: 1708815358175035392</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
@situchan let's get some reviews! 🙇‍♂️

**Comment by dylanexpensify** [comment]
@situchan can we please get some reviews in today? 🙏

**Comment by situchan** [comment]
reviewing today

**Comment by situchan** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/28606#issuecomment-1742942978) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment]
Nice! @marcochavezf let us know what you think!

**Comment by marcochavezf** [comment]
Sounds good, thanks @situchan for the review. Assigning @dukenv0307 🚀

**Comment by dylanexpensify** [comment]
Payment Summary:

- Reporter: @ayazhussain79 $50
- Contributor: @dukenv0307 $500
- Contributor+: @situchan $500

Please either request money or apply on Upwork job [here](https://www.upwork.com/jobs/~018cbad69c4c13b118)!

**Comment by situchan** [comment]
This is eligible for bonus. PR merged within 5 days including weekend

**Comment by dylanexpensify** [comment]
@situchan updated!

**Comment by dylanexpensify** [comment]
New [upwork job](https://www.upwork.com/jobs/~012ca341075dad18b2), please apply! cc @ayazhussain79 @dukenv0307 @situchan

**Comment by dylanexpensify** [comment]
bump ^

**Comment by ayazhussain79** [comment]
@dylanexpensify applied on upwork

**Comment by dylanexpensify** [comment]
Bump @situchan @dukenv0307 to apply!

**Comment by dylanexpensify** [comment]
@ayazhussain79 sent offer!

**Comment by situchan** [comment]
Applied thanks

**Comment by ayazhussain79** [comment]
Applied Thank you

**Comment by dylanexpensify** [comment]
nice! Payment now!

**Comment by marcochavezf** [comment]
Hi @dylanexpensify, I think we can close this out, correct? I will go ahead and close it, but feel free to re-open it if something is still pending :)

**Comment by situchan** [comment]
This is still waiting for payment

**Comment by situchan** [comment]
Here's payment summary: https://github.com/Expensify/App/issues/28606#issuecomment-1784822689

**Comment by lschurr** [comment]
Got it, thanks. Just reviewing the job now and seeing what happened with payments: https://www.upwork.com/ab/applicants/1721476234243555328/applicants
