### ISSUE TITLE
[$500] Request money - Unselecting split bill users displays the user as selected for sometime in recent list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28604]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on request money->manual
3. Enter any amount and click on next
4. Select few users
5. Unselect users one by one and observe that after unselect, it displays user as selected but in recent menu for sometime making UI appear glitchy

## Expected Result:
App should display users  only with split button in recent list

## Actual Result:
On unselecting users, app displays users as selected in recent list for sometime making the UI look glitchy

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/586f2262-b8bf-49d4-8249-aa3b74e91539

https://github.com/Expensify/App/assets/115492554/3495a7ee-4bcc-4d42-b597-a3ea540071f8

https://github.com/Expensify/App/assets/115492554/5ff3feac-c2eb-48e4-b23c-0334d7fdb38f

https://github.com/Expensify/App/assets/115492554/8ecfbc2e-da51-4853-903b-550ec994b75d

https://github.com/Expensify/App/assets/115492554/a2be0738-ab43-4257-947b-e42ee1cf1480

https://github.com/Expensify/App/assets/115492554/c9824645-11c2-4c31-b405-be9c23bc4283

https://github.com/Expensify/App/assets/115492554/082192ae-ecd0-4464-8cc1-0a0930959d80

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696181711297889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0dc67a4334ea429</li>
        <li>Upwork Job ID: 1708813370048184320</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by abekkala** [comment]
@neil-marcellini can you confirm the PR linked would fix this as well? 
https://github.com/Expensify/App/pull/28274

**Comment by neil-marcellini** [comment]
Yeah as I recall it does fix this issue. To be sure we can retest when https://github.com/Expensify/App/pull/28274 hits staging 🙂

**Comment by abekkala** [comment]
Confirmed that this is no longer happening. The fix on the the other PR has resolved this issue.
