### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] LHN - Incorrect backup avatar while waiting for avatar to load

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28638]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app from a fresh sign in
2. Observe your own avatar in the top right of the LHN area

## Expected Result:
I would expect this avatar to either use our fallback avatar image, or just be a solid icon fill circle like the rest of the loading avatars on the page

## Actual Result:
The app displayed one of our default avatars while waiting for the correct avatar to load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (2) (1)](https://github.com/Expensify/App/assets/78819774/d2682ce6-f433-4781-b36c-a0d4d6cb2571)

https://github.com/Expensify/App/assets/78819774/a2c61a20-919a-4abe-b889-5d09d294d37f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @shawnborton

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696240585729759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb65a5e1b63a2756</li>
        <li>Upwork Job ID: 1718973678534291456</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27439507</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Able to repro:

<img width="1260" alt="image" src="https://github.com/Expensify/App/assets/10925636/64841eb5-a4d6-4fc8-9349-e7f009a3fd0e">

**Comment by strepanier03** [comment]
All good to move forward. This was reported by one of our designers so they'd be the experts in expected behavior.

**Comment by ArekChr** [comment]
@strepanier03 Having a preview(thumbnail) image in base64 from the backend would be awesome as a fallback image.

**Comment by strepanier03** [comment]
@shawnborton is that possible?

Having a preview(thumbnail) image in base64 from the backend would be awesome as a fallback image.

I'm a little out of my depth. I can raise instead in Slack if you'd like.

**Comment by strepanier03** [comment]
Thank you @shawnborton - @ArekChr for visibility on their comment.

**Comment by ArekChr** [comment]
> right solution here is just to use the same style as the skeleton loader, and only use a fallback avatar if we can't download/access the right avatar.

@dukenv0307 could you update your proposal?

**Comment by strepanier03** [comment]
@dukenv0307 friendly bump.

**Comment by strepanier03** [comment]
Waiting on proposals atm Melvin, all good.

**Comment by strepanier03** [comment]
Proposal wait. Will discuss raising price next week.

**Comment by strepanier03** [comment]
@ArekChr - Do you think we should increase the price on this or is the urgency correct because this bug isn't something we need to rush to fix quickly?

I'm thinking we keep it at $500 since this isn't critical. What do you think

**Comment by Samueljh1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While the sidebar is loading, the fallback image for the user's avatar is incorrect.

### What is the root cause of that problem?
We are displaying a generic fallback image instead of something more appropriate -- a skeleton image.

### What changes do you think we should make in order to solve the problem?
Since the initial proposal, the avatar is now within a new component called `SignInOrAvatarWithOptionalStatus`. We can determine if the report data is loading by listening to the Onyx key: `ONYXKEYS.IS_LOADING_REPORT_DATA`. Based on this, we can conditionally render the following:
* `isLoading` = true : Display an avatar in skeleton-style (i.e., just a grey circle).
* `isLoading` = false: Display the avatar with the fallback image -- in the case of a URL load failure, the fallback image will be displayed.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Samueljh1** [comment]
@strepanier03 let me know if you are happy with this

**Comment by Samueljh1** [comment]
https://github.com/Expensify/App/assets/10816880/84d054af-0797-42af-824f-cdf575088ebe

Actually, it appears someone has already worked on this

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment]
@youssef-lr - Friendly bump for your [review](https://github.com/Expensify/App/issues/28638#issuecomment-1778861523) of the proposed solution.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by strepanier03** [comment]
Thanks all! I was OoO last week for the holiday but am working on this now, sorry for the delay!

**Comment by strepanier03** [comment]
This has been paid, regression test is proposed, and we're ready to close. 

Thank you all!
