### ISSUE TITLE
Update permission button copy after feedback from Apple App Store team

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#28633]
## Problem

The iOS app is being rejected:

> **Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage**
>
> We noticed your app encourages or directs users to allow the app to access the camera. Specifically, your app directs the user to grant permission in the following way(s):
> - A message appears before the permission request, and to proceed users press a “give “permission button. Use words like "Continue" or "Next" on the button instead.
> Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.
>
> **Next Steps**
> To resolve this issue, please revise the permission request process in your app to not display messages before the permission request with inappropriate words on buttons.
>
> If necessary, you may provide more information about why you are requesting permission before the request appears. If the user is trying to use a feature in your app that won't function without access to the camera, you may include a notification to inform the user and provide a link to the Settings app.

## Solution

Update button copy to say `Continue`

![Screenshot-0929-095600 (1)](https://github.com/Expensify/App/assets/2838819/db7d4ed4-e28e-453e-888b-a4ddb6b76269)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a47cef9baf05cc53</li>
        <li>Upwork Job ID: 1708891024463171584</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
PR merged and CP'd/ But in the meantime I think the latest release passed review somehow 😆 

<img width="574" alt="Screenshot 2023-10-03 at 09 48 29" src="https://github.com/Expensify/App/assets/10736861/ecad0f17-9be1-4c36-8009-707fba506cc7">
