### ISSUE TITLE
[HOLD for payment 2023-10-12] [HOLD for payment 2023-10-10] [$500] Web - App crash on click of back button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Click on back button

## Expected Result:
App should not crash

## Actual Result:
App crash (Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate)

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.75-8
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cda6e91d-aa22-4f3a-a14c-5ca2ee2e8df9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696231998119979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b1efa830b9ecb1c</li>
        <li>Upwork Job ID: 1708892554706366464</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment]
Potential deploy blocker when https://github.com/Expensify/App/pull/27223 is deployed

**Comment by Samueljh1** [comment]
I'm not able to reproduce this – are there any other conditions needed to trigger this crash?

**Comment by shubham1206agra** [comment]
This should be treated as a regression
@kacper-mikolajczak Can you fix this ASAP?

**Comment by situchan** [comment]
That PR caused another bad regression - https://github.com/Expensify/App/pull/27223#issuecomment-1742987647
I think better to revert as it's just function component refactor.

**Comment by situchan** [comment]
@ArekChr and @kacper-mikolajczak will handle this

**Comment by mallenexpensify** [comment]
Dropped in [here in #expensify-bugs ](https://expensify.slack.com/archives/C049HHMV9SM/p1696270877576219?thread_ts=1696268548.256909&cid=C049HHMV9SM)that it's happening in Desktop, staging, when clicking the profile pic.  It doesn't require a 'back button' action.

**Comment by saranshbalyan-1234** [comment]
I dont think there is a need to revert this PR, i have a small proposal, if someone can check

**Comment by francoisl** [comment]
Forgot to update here - fix confirmed working on staging. Removing the blocker label.

**Comment by francoisl** [comment]
This blocker was handled internally, so I believe we just need to compensate @gadhiyamanan for reporting the issue.

**Comment by mallenexpensify** [comment]
Thanks @francoisl 
@gadhiyamanan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~015b1efa830b9ecb1c

**Comment by gadhiyamanan** [comment]
@mallenexpensify offer accepted, thanks!

**Comment by mallenexpensify** [comment]
oh, I think I missed that @hoangzinh , I don't think we need the BZ checklist if we reverted the PR. Thx!
