### ISSUE TITLE
Request money - Changing the currency crashes the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on Fab button (+)
4. Click on "Request money"
5. Click on top of the currency to change the currency

## Expected Result:
User expects to be redirected to the change currency page

## Actual Result:
The app crashes
There is no crash in iOS, just a missing list of currencies

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d2f6c60b-b3d6-4e30-86ea-3d71b7c57b13

https://github.com/Expensify/App/assets/78819774/bf29d4e3-8d1b-485b-86fa-7ebc5a93cae6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This was fixed by https://github.com/Expensify/App/pull/28642
