### ISSUE TITLE
[$500] Chat - New message sent is not showing immediatelly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Type a message
2. Press enter to send it

## Expected Result:
The message should basically immediately show in the messages list

## Actual Result:
There is noticeable delay before the new message shows in chat list

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c8d38513-7119-4954-96fd-d81c742c4637

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696275413656409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9c236f03f59da21</li>
        <li>Upwork Job ID: 1708935805899952128</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Also fixed in staging

**Comment by kbecciv** [comment]
Issue is not reproducible on build v1.3.96-10

https://github.com/Expensify/App/assets/93399543/840bfb04-0e22-4dad-a395-218ceb922831

**Comment by situchan** [comment]
@kbecciv yes, it's expected not reproducible on staging. Did you also not reproduce on [this build](https://github.com/Expensify/App/pull/30605#issuecomment-1800232006)?

**Comment by kbecciv** [comment]
Checking on special build
