### ISSUE TITLE
[$500]  Attachment-No comment appears with grey text "Uploading Attachment" when upload attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in with any Gmail account
3. Navigate to a chat
4. Click on the + button in the compose box and upload an attachment
Online and offline

## Expected Result:
Comment appears with grey text "Uploading Attachment" indicating it is pending when navigate to a chat and upload an attachment

## Actual Result:
No comment appears with grey text "Uploading Attachment" indicating it is pending when navigate to a chat and upload an attachment. Online and offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1a370fa7-6a83-4972-b80a-023ed4dea12f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01080e97ce49640c83</li>
        <li>Upwork Job ID: 1708977224461635584</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This seems very much related to this blocker https://github.com/Expensify/App/issues/28654

Would reverting this PR solve it https://github.com/Expensify/App/pull/25557? cc @situchan

**Comment by marcaaron** [comment]
Oh weird. I can try test the revert to see what happens. 

IIRC that PR was just removing "dead code".

**Comment by marcaaron** [comment]
Easy to repro on `main`, but sorry doesn't seem related to that one @mountiny

**Comment by marcaaron** [comment]
I think the UX might be slightly improved by this bug :trollface: 😄

**Comment by marcaaron** [comment]
Um.. so.. it's actually working.. but we have a different problem that is not being reported

https://github.com/Expensify/App/assets/32969087/376d15eb-8325-4bbe-8619-c0613879f67a

The real bug is that the "attachment" message gets sorted to the top of the list or something - so I am looking for things that maybe messed with the sorting logic.

**Comment by marcaaron** [comment]
It's this one -> https://github.com/Expensify/App/pull/26729

**Comment by mountiny** [comment]
<img width="431" alt="image" src="https://github.com/Expensify/App/assets/36083550/8c45dfba-a06a-4c3b-896f-94e851268a53">
fixed

**Comment by MitchExpensify** [comment]
**Payment summary:**

$500 @situchan Contributor+ (Upwork) - Offer sent! https://www.upwork.com/jobs/~01080e97ce49640c83

**Comment by kbecciv** [comment]
Issue not reproduced on build v1.3.96-10

https://github.com/Expensify/App/assets/93399543/7902836b-52bd-4ce7-b965-bd3e095d92b6

**Comment by situchan** [comment]
@kbecciv yes, it's expected not reproducible on staging. Did you also not reproduce on [this build](https://github.com/Expensify/App/pull/30605#issuecomment-1800232006)?

**Comment by kbecciv** [comment]
Checking on special build, will update you shortly

**Comment by kbecciv** [comment]
Issue is not reproducible  on special build 

https://github.com/Expensify/App/assets/93399543/6f5143ca-8ceb-4a38-9ec8-ee5701005464

**Comment by kbecciv** [comment]
@situchan Noticed that url changed to /not-found, please verify if QA team need to create a separate issue for this

https://github.com/Expensify/App/assets/93399543/78c01fdb-e962-41d2-81e0-088ab50fdb2b
