### ISSUE TITLE
Chat - The emoji picker is incorrectly appearing on the LHN side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Click on the emoji picker.

## Expected Result:
The emoji picker should not be displayed on the LHN side

## Actual Result:
The emoji picker is incorrectly appearing on the LHN side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3. 76.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/73c8a612-fb51-462c-9820-de7b47221619

https://github.com/Expensify/App/assets/93399543/2822b04a-c810-4f76-8873-f63a002ff8be

https://github.com/Expensify/App/assets/93399543/f221dcc1-d4f9-44e0-b149-9794fc23b33b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696249751788399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is fixed in latest version 
<img width="425" alt="image" src="https://github.com/Expensify/App/assets/36083550/2bdc0df4-c763-46c6-9f2e-2d3b2277d2bd">
