### ISSUE TITLE
Chat - No error mesage when trying to send a corrupted file, only red dot in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25557
## Action Performed:
Pre-requisite: user must be logged in
1. Go to any chat
2. Send a corrupted file

## Expected Result:
There should be an error message saying that there was a problem sending the file

## Actual Result:
There is no error message, only the red dot appears in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/50d56732-96ba-4e18-88f9-43d39b8458a2

https://github.com/Expensify/App/assets/78819774/7a7234dd-9f60-478a-9109-f854e89237d1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I can reproduce the issue on staging and dev.

@cubuspl42 any ideas how to resolve this, or should we revert https://github.com/Expensify/App/pull/25557 for now?

**Comment by mountiny** [comment]
cc @situchan from the PR as well, if we confirm the revert fixes it, can you please handle the revert to proactively clear the deploy blockers? @cubuspl42 wont be online until EU morning. Thanks!

**Comment by marcaaron** [comment]
FWIW I tried the revert and it did not solve the issue.

**Comment by francoisl** [comment]
Same here. I'm attempting a git bisect to isolate where the regression came from but having a hard time because for some commits to test, the app just crashes. I'll try to narrow it down a bit more and then check the diff.

**Comment by francoisl** [comment]
Hmm if I revert https://github.com/Expensify/App/pull/26729 locally, it fixes the issue. Not sure what to make of this yet, as the change seems unrelated 👀

**Comment by marcaaron** [comment]
See my findings here -> https://github.com/Expensify/App/issues/28656#issuecomment-1744002751

**Comment by marcaaron** [comment]
I bet the message with error is just sorted to the top and hidden like the "Uploading attachment..." text 😄 

That was a fun one 😂

**Comment by francoisl** [comment]
Haha nice. Yeah both our blockers look related.

Happy to send you a revert PR if you haven't already one in the works, or I can review yours.

**Comment by marcaaron** [comment]
I'll check yours - I made a branch but did not raise a PR

**Comment by cubuspl42** [comment]
I'm trying to catch up. So did reverting https://github.com/Expensify/App/pull/25557 _help_ or _not_?

**Comment by mountiny** [comment]
<img width="1047" alt="image" src="https://github.com/Expensify/App/assets/36083550/0a9d912d-cc23-4c2a-a1f5-780ab90496ed">

@cubuspl42 no it was different PR

**Comment by cubuspl42** [comment]
@mountiny So will we revert-revert https://github.com/Expensify/App/pull/25557?

**Comment by mountiny** [comment]
It was not reverted https://github.com/Expensify/App/pull/28671, the PR was closed, not merged

**Comment by kbecciv** [comment]
Issue is not reproducible on build v1.3.96-10

https://github.com/Expensify/App/assets/93399543/60143657-7ce9-4a18-8deb-5633fbce2e8b

**Comment by kbecciv** [comment]
Checking special build, will update you shortly

**Comment by kbecciv** [comment]
Not reproduced on special build

Not reproduced on special build 
https://github.com/Expensify/App/assets/93399543/e135d8d7-bda1-494a-86ec-757a69310fdf
