### ISSUE TITLE
[$500] Chat - Messages sent in offline mode appear above the chat history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28125
## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Send a text in any chat

## Expected Result:
Sent messages will appear in the normal order

## Actual Result:
Sent messages in offline mode appear above the chat history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/93993d32-1267-4d03-baca-76a7fb5632a1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d91b70734ff91d84</li>
        <li>Upwork Job ID: 1708976807389507584</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This is also resolved by the revert we made before 
<img width="1051" alt="image" src="https://github.com/Expensify/App/assets/36083550/cb7fec07-3599-487d-8a7a-d175504e059d">

no payments due, closing
