### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] mWeb-Compose-Tapping emoji picker, for a million second, the message section is selected and shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28698]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap on emoji picker in compose box

## Expected Result:
When tapping on emoji picker, for a million second also, the message section must not be selected and shown. only emoji box must be displayed.

## Actual Result:
When tapping on emoji picker, for a million second, the message section is selected and shown and then only emoji box is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3 76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/28995bbd-639b-4d9d-9329-f330e5e50586

![Bug6222872_1696316673479!selected_section](https://github.com/Expensify/App/assets/115492554/00107565-11dc-4b5f-8841-d4beed007ab7)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01968cbb3d0a1ef947</li>
        <li>Upwork Job ID: 1709683408501026816</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27283894</li>
<li>tienifr | Contributor | 27283896</li>
</ul></li>
    </ul>
</details>

**Comment by johncschuster** [comment]
This isn't overdue. It was just triaged to @ntdiary

**Comment by johncschuster** [comment]
@ntdiary, can you check out @tienifr's response above? Do you feel the proposal is sufficient, or should we keep looking?

**Comment by johncschuster** [comment]
Not overdue.

**Comment by johncschuster** [comment]
Payment has been issued! 🎉
