### ISSUE TITLE
[$250] Web - LHN - When you send a message, the conversation moves to LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with any account
3. Navigate to any conversation
4. Send any message to the conversation

## Expected Result:
The conversation must remain in the same place in the LHN list when the message is sent and after it has been sent.

## Actual Result:
Conversation is moved to the end of the LHN list when a message is sent and moved back after it is sent.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a4e1ce19-65bc-4b76-aa42-e0b29e33731e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdea6cb5b1d929d9</li>
        <li>Upwork Job ID: 1709201871690252288</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I dont think I can repro anymore

**Comment by mountiny** [comment]
Cannot repro
https://github.com/Expensify/App/assets/36083550/7b9e17b3-9caf-422f-8576-03057e18652e

**Comment by mountiny** [comment]
QA confirmed this is not repro in staging anymore https://expensify.slack.com/archives/C9YU7BX5M/p1696343304289279?thread_ts=1696340542.134169&cid=C9YU7BX5M
