### ISSUE TITLE
[HOLD for payment 2023-10-12] [HOLD for payment 2023-10-10] [$500] Android- IOU-App crashes when saving the selected date & merchant/date field not shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3.Tap request money
4. Enter an amount
5. Tap next
6. Select any user
7. Tap request amount
8. Open IOU report page
9. Note date and merchant field is not shown
10. Tap date field and select any date eg:"oct 1 or oct 2"
11. Tap save

## Expected Result:
App must not crash when user saves the selected date. Merchant and date field must be shown.

## Actual Result:
App crashes when user saves the selected date. Merchant and date field is not shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2c454ccc-c1b0-4ff4-8910-fe6c1ebb5857

[utest-dl.s3.amazonaws.com_12102_26469_432782_6222780_bugAttachment_Bug6222780_1696309387236%21crash.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231003T081930Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Credential=AKIAJ.txt](https://github.com/Expensify/App/files/12790171/utest-dl.s3.amazonaws.com_12102_26469_432782_6222780_bugAttachment_Bug6222780_1696309387236.21crash.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231003T081930Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Credential.AKIAJ.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014620b7473ef96d10</li>
        <li>Upwork Job ID: 1709122266335506432</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26995484</li>
<li>namhihi237 | Contributor | 26995485</li>
<li>aimane-chnaif | Contributor | 26996114</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Production video

https://github.com/Expensify/App/assets/115492554/a302a860-9e50-4288-9ef7-129dd66b9b1e

**Comment by shubham1206agra** [comment]
@namhihi237 Since this is a deploy blocker. Please link the offending PR

**Comment by mountiny** [comment]
@namhihi237 Great!

```
const created = transaction?.modifiedCreated || transaction?.created || '';
```

I like this more, can you please raise a PR? Also this null coallescing logic might have been worng for other modified fields, lets make sure that is fixed too

Can you raise a PR now?

**Comment by mollfpr** [comment]
@namhihi237 Let me know when the PR ready, thanks!

**Comment by mountiny** [comment]
Fixed 
<img width="1069" alt="image" src="https://github.com/Expensify/App/assets/36083550/9d366edb-a1f0-43ba-91d8-043d08207b0a">

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
