### ISSUE TITLE
[$500] mWeb - Emoji - "�" symbol displayed in the compose box when write and delete an emoji with Gboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be signed in
1. Open app
2. Tp on any available conversation in LHN
3. Tap on the composer box
4. Write ":sm"
5. Select any suggested emoji
6. Tap delete button twice

## Expected Result:
Emoji should be deleted from the compose box

## Actual Result:
"�" symbol displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/178fe64a-715f-40e8-9205-6e859295f539

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137d8940b6f11a219</li>
        <li>Upwork Job ID: 1711886540253470720</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
I was not able to reproduce this one.

**Comment by JmillsExpensify** [comment]
Triaging, that's legit.

**Comment by debragail** [comment]
What android device and version?  This might be incompatible as some emojis are not available.

**Comment by MrMuzyk** [comment]
@izarutskaya 

Hey, I wasn't able to reproduce this one. Can you double check if it's still valid? I've tested it on Pixel 6 Pro emulator, see the recording.

https://github.com/Expensify/App/assets/23487612/a93117be-56ad-4ecb-b56c-ac66e2f4f432

**Comment by debragail** [comment]
Contributor details
Your Expensify account email: expensify@27c1ub.com
Upwork Profile Link: https://www.upwork.com/freelancers/debragail

**Comment by JmillsExpensify** [comment]
Given that multiple aren't able to reproduce, I'm going to close.
