### ISSUE TITLE
Desktop - IOU - "You don't have access" msg displayed when upload the .HEIC smart scan & click on it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28708]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be signed in and have a .HEIC file on the device
1. Open app
2. Click on FAB
3. Click on "Request Money"
4. Select "Scan" tab
5. Drag and drop the .HEIC file
6. Select the attendee
7. Click "Request" button
8. Click on the Scan in the conversation

## Expected Result:
User should be navigated on the smart scan details page

## Actual Result:
Error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c166f6ed-9736-4685-b5ee-a24ff2d7181a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by peterdbarkerUK** [comment]
HEIC files are not currently supported, work on supporting them is already in progress [here](https://github.com/Expensify/App/issues/12531)
