### ISSUE TITLE
[$500] Chat -  Split bill preview displays skeleton view after login again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28713]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to announce chat room
2. Create a split bill
3. Sign out and sign in again
4. Open the announce chat room again

## Expected Result:
 The split bill should be displayed

## Actual Result:
The split bill preview displays a skeleton view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/53c8ee0b-df7f-4c04-9d2a-a69350abb348

https://github.com/Expensify/App/assets/93399543/6b01c82a-82d8-4870-aa91-e5117b7527c2

https://github.com/Expensify/App/assets/93399543/2db65a89-8767-4ffe-b8f8-02d51980fcba

[untitled.webm](https://github.com/Expensify/App/assets/93399543/ce5f4f36-2a04-4f63-af49-3e243c61a607)

https://github.com/Expensify/App/assets/93399543/9a06bfef-8c05-4846-a0dc-b878898036b0

[Screencast from 02-10-2023 15_06_13.webm](https://github.com/Expensify/App/assets/93399543/0b76ddeb-122e-41e5-b937-663fd3754ad2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696234232663269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01752787251543788d</li>
        <li>Upwork Job ID: 1709177646929657856</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @dukenv0307
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696234232663269

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Split bill preview displays skeleton view after login again
### What is the root cause of that problem?
In `MoneyRequestPreview` We have the condition here to display skeleton. When we open the announce report, the `openReport` API doesn't return the transaction data of the split bill and then the skeleton is displayed
https://github.com/Expensify/App/blob/c390d5e08d38f8c4dd7f0e134b42042f5a08a7ee/src/components/ReportActionItem/MoneyRequestPreview.js#L248-L252
### What changes do you think we should make in order to solve the problem?
In `MoneyRequestPreview`, if the transaction is split bill we can get the data from `props.action` if the transaction is empty. We can do the same thing in `SplitBillDetailPage`
```
if (props.isBillSplit && _.isEmpty(props.transaction)) {
    requestAmount = parseInt(lodashGet(props.action, 'originalMessage.amount', 0), 10);
    requestCurrency = lodashGet(props.action, 'originalMessage.comment');
    requestComment = lodashGet(props.action, 'originalMessage.currency');
}
```
and we can change the conditions here by adding the check whether the preview is split bill or not
```
{_.isEmpty(props.transaction) &&
!props.isBillSplit &&
!ReportActionsUtils.isMessageDeleted(props.action) &&
lodashGet(props.action, 'pendingAction') !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ? (
```
https://github.com/Expensify/App/blob/c390d5e08d38f8c4dd7f0e134b42042f5a08a7ee/src/components/ReportActionItem/MoneyRequestPreview.js#L248-L252
### What alternative solutions did you explore? (Optional)
BE should return transaction data of the split bill in `openReport` API if this report has split bill action

**Comment by maddylewis** [comment]
@jjcoffee - bump on proposal review - ty!

**Comment by jjcoffee** [comment]
@maddylewis This is a [dupe](https://github.com/Expensify/App/issues/28713#issuecomment-1751900262), I think we're good to close!
