### ISSUE TITLE
[$250] Distance IOU - 'Recent destination' disappears first then the list in the address field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28719]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28124
## Action Performed:
Precondition: User has some destinations in recent destination list
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Click on Start
4. Click on the address field
5. Enter anything on the address field

## Expected Result:
The entire recent destination list will disappear altogether as soon as there is some value in the input field

## Actual Result:
'Recent destination' in the list disappears first, followed by the list when entering value in the input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d04943b4-3e3d-40ce-aa92-1290e0f8c1ab

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a77fcc0700929dde</li>
        <li>Upwork Job ID: 1709202698130886656</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Looking at this more, I dont think this is a blocker, the problem is that as you start typing the recent addresses do not disappear immediately and you can see them briefly before the right addresses appear. I think this should be treated as a follow up to https://github.com/Expensify/App/pull/28124 as this might have been missed during the review.

**Comment by mountiny** [comment]
Let me just move it to here https://github.com/Expensify/App/issues/27165
