### ISSUE TITLE
IOU - Header reverts from Attachment to Receipt when opening Attachment in IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Create a money request
3. Go to the IOU details view and add a receipt
4. On the same IOU details view, tap + > Add attachments > Upload an image
5. Tap on the receipt
6. Tap > button

## Expected Result:
When moving from receipt to attachment, the header will change from Receipt to Attachment

## Actual Result:
When moving from receipt to atatchment, the header changes from Receipt to Attachment, and quickly reverts to Receipt. The > arrow remains even though user is on the end of the attachment carousel

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ca775361-797a-4a01-8fa7-430e51d40dbf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
This is a regression from https://github.com/Expensify/App/issues/26828
Here's a more detailed RCA: https://github.com/Expensify/App/issues/28718#issuecomment-1744944301

**Comment by bfitzexpensify** [comment]
OK, raised this in https://github.com/Expensify/App/issues/26828. Going to close this for the moment and re-open if we need a separate issue.
