### ISSUE TITLE
[HOLD for payment 2023-10-13] [HOLD for payment 2023-10-12] [HOLD for payment 2023-10-10] [$500] Distance -  The error message for "Invalid amount" appear when the correct amount is selected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the "+" button.
2. Navigate to Request money > Distance.
3. Select start and finish points and click on "Next."
4. Choose the expense room and click on "Request."
5. Notice the display of the "Invalid amount" error message even when the correct amount is selected.

## Expected Result:
The error message for "Invalid amount" should not appear when the correct amount is selected

## Actual Result:
 Incorrectly displays an "Invalid amount" error message even when the amount is entered correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - app is down
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/47bd5fde-9ae8-4a89-9c28-9d77ef9d4013

https://github.com/Expensify/App/assets/93399543/07cdcb77-34cf-49cf-9bd6-49ded8ef2f5e

https://github.com/Expensify/App/assets/93399543/03396da1-5497-4d9e-9007-5c054389d1b0

https://github.com/Expensify/App/assets/93399543/48d20445-5efd-4acb-89f4-72ae2988b00d

https://github.com/Expensify/App/assets/93399543/0b83059e-8597-452d-af90-7e420ebb04b4

https://github.com/Expensify/App/assets/93399543/aff8ca5f-fea0-4490-b40e-7f3022183af8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696287219855449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dff800754c90792c</li>
        <li>Upwork Job ID: 1709206143119994880</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment]
I think there is another bug:

<img width="246" alt="image" src="https://github.com/Expensify/App/assets/87341702/c03c626a-8f37-46c0-b22c-87a93cf81785">

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/87341702/337813c8-df04-47e7-a04a-90f5a4da7dd7">


A precision related one. The number shown in the interface is 3.50, but the amount passed in the validation has lots of decimal

**Comment by aldo-expensify** [comment]
I think we need to fix this function so it returns exact cents:

<img width="498" alt="image" src="https://github.com/Expensify/App/assets/87341702/f9327e8c-8bab-429e-a855-d28d68398748">


https://github.com/Expensify/App/blob/fcfd2a080d7464305e2867ba3b5645f18a8c4e94/src/libs/DistanceRequestUtils.js#L86-L97

I'll prepare a PR

**Comment by aldo-expensify** [comment]
BTW, the bug mentioned here: https://github.com/Expensify/App/issues/28721#issuecomment-1745235196 is not a DeployBlocker because it is in production already

**Comment by aldo-expensify** [comment]
Prepared PR for: https://github.com/Expensify/App/issues/28721#issuecomment-1745235196

https://github.com/Expensify/App/pull/28734

**Comment by alexpensify** [comment]
Not overdue, the payment date is set for tomorrow

**Comment by alexpensify** [comment]
To prepare for payment - @ayazhussain79 can you please request to be part of this Upwork job? It will help ensure that I assign the complete process to the right account. Thanks! 

https://www.upwork.com/jobs/~01dff800754c90792c

**Comment by ayazhussain79** [comment]
@alexpensify applied on upwork

**Comment by alexpensify** [comment]
Done -- I've paid @ayazhussain79 via Upwork, thanks!

**Comment by alexpensify** [comment]
@ayazhussain79 - I'm not sure what happened in Upwork but I just noticed that the payment was not sent. It's all complete now and I see the `Paid` flag.

**Comment by ayazhussain79** [comment]
@alexpensify np Thank you
