### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Payment for reporting bug

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Bug reported here https://github.com/Expensify/App/issues/28497#issuecomment-1743316807

Created this issue to track the payment

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107325e5eda525931</li>
        <li>Upwork Job ID: 1709223003171786752</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@zanyrenney Can you please help pay @Talha345 for reporting this bug

**Comment by Talha345** [comment]
@zanyrenney Hi, this task was created to make the payment for a bug I reported! Can you kindly process it?

**Comment by zanyrenney** [comment]
Sure thing, the payment was only due today, hence me waiting for the date of 12th October.

**Comment by zanyrenney** [comment]
@Talha345 have invited you to the job on upwork, please reply :)

**Comment by Talha345** [comment]
> @Talha345 have invited you to the job on upwork, please reply :)

@zanyrenney proposal submitted to job!

**Comment by zanyrenney** [comment]
brilliant, @Talha345 - offer sent!

**Comment by zanyrenney** [comment]
still waiting on @Talha345

**Comment by Talha345** [comment]
> still waiting on @Talha345 

@zanyrenney accepted offer!

**Comment by zanyrenney** [comment]
summary of payments: 

**$50 to @Talha345**
