### ISSUE TITLE
[$500]  Profile - Scrollbar briefly appears when transitioning from the "pronouns" page to the "profile" page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging
2. Click on Settings > Profile > Pronouns
3. Select any options
4. Observe that the scrollbar briefly appears

## Expected Result:
The scrollbar should not appear

## Actual Result:
A scrollbar appears for a brief moment after returning from the pronouns page to the profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.77-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b6dc310c-cc6a-488a-81de-6949284a8c44

https://github.com/Expensify/App/assets/115492554/c4ac719d-a702-4f66-ab3c-51f76a38af5f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696152469627309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de0e35acf173359f</li>
        <li>Upwork Job ID: 1709247371083108352</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
IMO, this isn't really a "bug". It is a minor inconsistency, as the scrollbar only flashes on the screen when moving from the pronouns page back to the profile. It has no impact on the user experience whatsoever, so I'm going to close this so we can focus on higher priority changes.
