### ISSUE TITLE
[HOLD for #27665][$500] Personal detail - App not dismiss RHN when click outside

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click Setting => Profile => Personal detail
2. Click Date of birth
3. Click year to open year picker
4. Click outside RHN, Observe that RHN is not dismissed

## Expected Result:
RHN dismissed when click outside

## Actual Result:
RHN is not dismissed but it goes back one step

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** v1.3.77-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cc1a0c13-1e71-4c83-95dc-ec31e5debef9

https://github.com/Expensify/App/assets/115492554/c2aa61de-8119-429f-af0d-179bd7c69cc8

https://github.com/Expensify/App/assets/115492554/5cb375bf-e636-4d5f-bc7a-7b056f91f26d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696265759646699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119761391c95f3447</li>
        <li>Upwork Job ID: 1709254523081965568</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by cooldev900** [comment]
how about changing route when the modal is closed, not hidden?
https://github.com/Expensify/App/blob/e30dce19672085a2c8b34576d2fe33ebd8aee249/src/components/NewDatePicker/CalendarPicker/index.js#L237
```
<YearPickerModal
                    isVisible={this.state.isYearPickerVisible}
                    years={this.state.years}
                    currentYear={currentYearView}
                    onYearChange={this.onYearSelected}
                    onClose={() => Navigation.navigate()}
                    onHide={() => this.setState({isYearPickerVisible: false})}
                />
```

https://github.com/Expensify/App/blob/e30dce19672085a2c8b34576d2fe33ebd8aee249/src/components/NewDatePicker/CalendarPicker/YearPickerModal.js#L55
```
<Modal
            type={CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED}
            isVisible={props.isVisible}
            onClose={props.onClose}
            onModalHide={props.onHide}
            hideModalContentWhileAnimating
            useNativeDriver
        >
        ...
        </Modal>
```

**Comment by sonialiap** [comment]
I'm moving this to "Weekly" for now because I'll be OOO until the 22nd

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/27665

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/27665

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/27665

**Comment by sonialiap** [comment]
Still on hold for https://github.com/Expensify/App/issues/27665

**Comment by sonialiap** [comment]
Still on hold. PR up but not yet deployed

**Comment by sonialiap** [comment]
Still on hold, the PR is still in progress https://github.com/Expensify/App/pull/31729

**Comment by sonialiap** [comment]
Tested again and this issue persists

1. Setting > Profile > Personal detail > Date of birth > year picker
2. Click outside of RHN
3. Observe RHN goes back to Date of birth instead of closing completely
4. From Dote of birth if you click outside of RHN, RHN closes completely

However, I think this issue is fairly small so I'm closing it out to prioritize other issues
