### ISSUE TITLE
[HOLD for payment 2023-10-18] [Wave 6: Drafts] Add the autoreporting and submitted state as const to the App

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28759]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.xad5t0pmk5p5), we have couple of constants which will need to be added to the App to support the drafts and its functionality. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2c7ac503d38cdb4</li>
        <li>Upwork Job ID: 1709977346141700096</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@mountiny, I assume that we need to extend:
1. [Policy.ts](https://github.com/Expensify/App/blob/main/src/types/onyx/Policy.ts) with `AUTO_REPORTING_FREQUENCIES`. So, how the backend call this key in a policy object?
2. [OriginalMessage.ts](https://github.com/Expensify/App/blob/main/src/types/onyx/OriginalMessage.ts) with a new type -`OriginalMessageSubmitted`. Am I right? What properties does `OriginalMessageSubmitted` have?

**Comment by mountiny** [comment]
Those sounds correct yeah, catching up with other things now, will tyr to get back to this asap

**Comment by mountiny** [comment]
actionName of the report action is `SUBMITTED` needs to be added to report.action.type here https://github.com/Expensify/App/blob/cbb069c994f321a7a0ff77f84464e74cbbc8f773/src/CONST.ts#L476-L493

As far as the originalMessage type goes, I would keep it as unknown for now. I think there can be lots of different shapes depending on the particular policy set up

**Comment by mountiny** [comment]
For the `AUTO_REPORTING_FREQUENCIES`, not sure if I understand your question.

We will have to add these two keys to the Policy type:
```
   'autoReporting' => $policyData['autoReporting'] ?? false,
   'autoReportingFrequency' => $policyData['autoReportingFrequency'] ?? 
```

And possibly create a new autoReportingFrequency enum using the options you see in the doc

**Comment by mollfpr** [comment]
I'm not due any compensation here, so I'll un-assigning myself ✋

**Comment by mountiny** [comment]
Can be closed
