### ISSUE TITLE
[HOLD for payment 2023-10-18] [Wave 6: Drafts] Update the type declarations for Policy

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28758]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.x3684qzhih2), we are going to have to update the Policy.ts with new fields.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175cf51dad5cdbc17</li>
        <li>Upwork Job ID: 1709977113787936768</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by puneetlath** [comment]
Doesn't look like anyone needs payment here. Closing!
