### ISSUE TITLE
[HOLD for #26538] [$500] Private note - App glitches on first click on confirmation link from private notes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any user report
3. Click on plus besides composer and click request money->manual
4. Enter any amount and continue
5. Copy the URL
6. Click on user below 'To', click on private notes-> My notes and save the copied URL in private notes
7. Click on back few times to again visit confirmation page
8. Click on request
9. Click on user report header to open user details
10. Click on private notes->My notes and click on the link
11. Observe that on first click, app glitches and does not open the request money page, it works fine on clicking again

## Expected Result:
App should open request money page when we click on confirmation link in private notes

## Actual Result:
App glitches on first try when we click on confirmation link in private notes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e99eb4c3-3cd0-4692-b588-e28c4babebd7

https://github.com/Expensify/App/assets/93399543/1530637e-bb22-4f31-8af1-2f6a233e1991

https://github.com/Expensify/App/assets/93399543/f5e2ff68-fcf9-4372-a321-5a1b30832bbc

https://github.com/Expensify/App/assets/93399543/a4a16b78-ed68-44bd-9f92-f5e575cae38a

https://github.com/Expensify/App/assets/93399543/a8a51687-1099-4d17-ae29-99d8f5da1b97

https://github.com/Expensify/App/assets/93399543/e8ff14fe-83a9-40d8-95e9-9b8b025d18b5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696340371069839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c29f3d184a7857fe</li>
        <li>Upwork Job ID: 1709325629652197376</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
This issue relates to shouldReset logic so we should hold this issue until https://github.com/Expensify/App/issues/26538 is resolved. [Discussion here](https://github.com/Expensify/App/issues/26946#issuecomment-1740453516)

**Comment by johncschuster** [comment]
Thanks for the heads up, @DylanDylann!

**Comment by johncschuster** [comment]
Not overdue. Still holding.

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
Still holding

**Comment by johncschuster** [comment]
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
Per @DylanDylann's [comment above](https://github.com/Expensify/App/issues/28756#issuecomment-1746162356), we're holding on https://github.com/Expensify/App/issues/26538

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by kadiealexander** [comment]
The issue this has been held for is now on production. 

I don't think I agree that this is a bug. The request confirmation screen isn't static, it requires information from the `request/start` screen in order to show. You shouldn't be able to navigate directly to it from a link, because how does it know the amount being requested.

Closing as desired behaviour, please feel free to reopen if you disagree.
