### ISSUE TITLE
[Wave 6: Drafts] Update Auth getChats to return the draft reports too

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28760]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the Doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.hvdhzxi5t6bl), we are going to have to update the getChats query/ command to also return the open reports to newDot.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf314ce649215cb5</li>
        <li>Upwork Job ID: 1709353334210236416</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hey, Im Artem from Callstack and would like to take this one

**Comment by mountiny** [comment]
@waterim This one will have to be internal

**Comment by waterim** [comment]
Oh, okay

**Comment by mountiny** [comment]
Focusing on bottom up flow now
