### ISSUE TITLE
[Wave 6: Drafts] Update the SubmitReport API and Auth command to accept optional reportAction param

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28761]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.one3551gcxa4), we need to update the Submit report api to accept additional optional parameter with optimistc report action ID.

**Comment by waterim** [comment]
Hey, Im Artem from Callstack and would like to take this one

**Comment by mountiny** [comment]
Same as on the other one, this one has to be internal

**Comment by greg-schroeder** [comment]
Downgraded this to Medium to account for current roadmap

**Comment by mountiny** [comment]
Will be worked on soon

**Comment by mountiny** [comment]
hmm this is done
