### ISSUE TITLE
[HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-18] [Wave 6: Drafts] Add the Submit button to the Report preview component

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28766]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.iqfupenx5myi), we need to add the report submit button to the report preview in the App.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d291e7bf437cd92b</li>
        <li>Upwork Job ID: 1709582242081632256</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by BeeMargarida** [comment]
Hey @mountiny, Ana from Callstack here 👋, I'm would like to work on this issue

**Comment by mountiny** [comment]
No payment required, this is completed
