### ISSUE TITLE
[HOLD for payment 2023-10-18] [Wave 6: Drafts] Add the submitReport IOU action/ method to call the command to the App

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28763]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.7ejf0x2mcw0z), we need to add the submit report api command action to the App
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165fe7bcde4f5d219</li>
        <li>Upwork Job ID: 1709580692914237440</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from callstack - expert group
And I would like to take this feature

**Comment by puneetlath** [comment]
@anmurali I'll take BZ on this since it's for wave6.

**Comment by puneetlath** [comment]
No payments required. Closing.
