### ISSUE TITLE
[HOLD for payment 2023-10-30] [Wave 6: Drafts] Show the Next step in the MoneyReportHeader

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28767]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [here in the doc](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.wlsag064x89n), we are going to show the next steps for the report in the moneyReportHeader component.

**Comment by BeeMargarida** [comment]
Hi, I’m Ana from Callstack, is this issue ready to be worked on? I would like to help

**Comment by BeeMargarida** [comment]
> @BeeMargarida For context, the backend change was merged so there should be the next steps collection coming in OpenReport response for Expenses from monday #28762

Hey @mountiny, I was trying to use this, but I might be missing something. Open/draft reports don't appear in newdot yet, right? Is these next steps only returned for reports with that state, or for ones already in processing?
The next steps are not being returned in OpenReport, I'm using a newly created money request in newdot.

**Comment by mountiny** [comment]
Next steps are returned for any expense report and they will start after web deploy today which might be in couple hours

**Comment by BeeMargarida** [comment]
Update: almost ready, just having some struggles with the line wrap of the HTML renderer in native devices

**Comment by mountiny** [comment]
The C+ was from agency so we can actually close this too
