### ISSUE TITLE
[Wave 6: Drafts] Use GBR to show when there is next step action required from the user

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28768]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [here in the doc](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.rascpocug1m4), we are going to use the GBR pattern to show user whenever its their turn to take an action on a report in the app.

**Comment by mountiny** [comment]
Looking for a volunteer

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@mountiny, I don't have access for the [link](https://github.com/Expensify/Expensify/issues/308213), that you mentioned in the description above. Should I know something important from that?

**Comment by mountiny** [comment]
No thats just a tracking issue.

**Comment by mountiny** [comment]
should require a small change

**Comment by rezkiy37** [comment]
Preparing the PR.

**Comment by mountiny** [comment]
As noted in Slack, we are going to close this issues as this change actually is not desirable with the updated GBR approach we are taking where the attention is drawn to the parent chat in LHN and all the cases for Collect policies should actually be already covered in backend logic for the GBR. If we discover we need this logic in some other cases which are not covered, we can revisit this PR. Thanks for working on this and sorry for the outcome/ not catching this earlier

**Comment by mountiny** [comment]
Payment summary for @allroundexperts applying 25% of the reward hence $125 for work on the PR given we decided to not continue ahead but the checklist and testing has already been done.

**Comment by JmillsExpensify** [comment]
$125 payment approved for @allroundexperts based on comment above.
