### ISSUE TITLE
[Wave 6: Drafts] Add the submit button to the MoneyRequestHeader

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28765]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [the doc here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.6lx9mdynahru), we need to add a submit button to the MoneyRequestHeader in the App.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dfa18f09c1f420f</li>
        <li>Upwork Job ID: 1709975189630955520</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by BeeMargarida** [comment]
Hey, Ana from Callstack here - expert contributor group - I would like to help out with this one 👋

**Comment by mountiny** [comment]
I think this can be concluded as done

**Comment by cubuspl42** [comment]
FFR, I do not require payment
