### ISSUE TITLE
[Wave 6: Drafts] Scaffolding of optimistic next step for reports

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#28770]
Part of https://github.com/Expensify/Expensify/issues/308213

Coming from [here in the doc](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit?pli=1#bookmark=id.rykspffki8y5), we are going to set up a framework for the next steps to be optimistic so we can already build them offline when user creates a report for example.

**Comment by mountiny** [comment]
This has been deprioritised now

**Comment by waterim** [comment]
Hello, Im Artem from callstack and would like to help with this issuse!

**Comment by mountiny** [comment]
I do think we can close this one out for now and we can come back to this once we consider this needs to be tackled
