### ISSUE TITLE
[$500] Android-IOU- Below IOU transaction, "2requests" appears and then disappears within seconds.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap plus button near compose
4. Tap request money, enter an amount, select any user and complete the flow
5. Again tap plus button near compose
6. Tap request money, enter an amount, select any user and complete the flow

## Expected Result:
Below IOU transaction, "2requests" appears and then must not disappear within seconds.

## Actual Result:
Below IOU transaction, "2requests" appears and then disappears within seconds.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4cf020e5-60fa-4bd7-ba80-b4d372443e01

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121b786d1bef58fb5</li>
        <li>Upwork Job ID: 1709533301797695488</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Agreed

**Comment by lanitochka17** [comment]
Issue reproducible on Build 1.3.83-4


https://github.com/Expensify/App/assets/78819774/b604f9c9-7ce8-46de-94a2-f18f28fbe6a0

**Comment by dylanexpensify** [comment]
@Ollyws mind trying again on prod and staging?

**Comment by dylanexpensify** [comment]
Bump @Ollyws
