### ISSUE TITLE
[$500] Android-IOU-User A send first request money- In user B conversation page, iou not received

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Launch app
2.As user A, Tap fab and request money to user B
3.Open B LHN and tap bold IOU and pay it.
4.Tap header and go to conversation page and request money to user A
5. As user A, Pay the money requested by user B
6.Now send request money to User B and note user B conversation page, iou not received
7.Again send request money to user B

## Expected Result:
When user A send request money- In user B conversation page, iou must be received and shown.

## Actual Result:
When user A send first request money- In user B conversation page, iou not received
When user A send second request money- In user B conversation page, both iou received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dbc0b336-1499-4ecd-b4a5-5c42ea5e1150

https://github.com/Expensify/App/assets/115492554/42494cc3-6104-4f00-8626-a920b060fee9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cc8daf97d8cc198</li>
        <li>Upwork Job ID: 1709530314467229696</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by soro-kuraima** [comment]
the bug wasn't reproduced on staging

**Comment by MitchExpensify** [comment]
I cannot reproduce this currently
