### ISSUE TITLE
[$500] IOU - No "Recents" section in the tag selection menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #28493
## Action Performed:
Prerequisites:
Have a workstation with tag setup - https://github.com/Expensify/App/pull/28151#issuecomment-1736543304

Steps:
1. Open https://staging.new.expensify.com/
2. Sign in onto an account (log out and then sign in again just to clear Onyx)
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Manual' and add an amount
6. Click on the "Next" button
7. Select the configured WS
8. Click 'show more' and click on 'Category'
9. Select a category
7. Choose a tag
8. Save money request
9. Repeat steps 3-8

## Expected Result:
When re-creating an IOU, the "Recents" section with the previously selected tags should be displayed.

## Actual Result:
No "Recents" section in the tag selection menu when creating an IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2e7cc71f-f9cd-41ce-a6c7-0bead865b617

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a1f123eb0bd3dbe</li>
        <li>Upwork Job ID: 1709535841184526336</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Issue found when executing PR https://github.com/Expensify/App/pull/28493

**Comment by ayazalavi** [comment]
There is no tags option. How to enable it?

**Comment by abdel-h66** [comment]
To enable the tags @ayazalavi  follow these steps 

https://github.com/Expensify/App/pull/28151#issuecomment-1736543304
And make sure you have the permissions to use tags

https://github.com/Expensify/App/blob/743a041879eb451181ab32644ec3a3b3a697e1e7/src/libs/Permissions.ts#L4-L6

I personally just have 

```js
function canUseAllBetas(betas: Beta[]): boolean {
    return true;
}
```

**Comment by NicMendonca** [comment]
Waiting for proper proposals?

**Comment by NicMendonca** [comment]
@ayazalavi @abdel-h66 either of you interested in submitting proposals? 👀

**Comment by NicMendonca** [comment]
@izarutskaya is this still reproducible?

**Comment by robertKozik** [comment]
I think this can be the case @abdel-h66 described [here](https://github.com/Expensify/App/issues/28804#issuecomment-1747271361). From the issue video we see that the user has only 4 tags - where we want at least 8 to include `recents` tags in the list

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue. I was one of who introduced categories and tags for the app.

**Comment by rezkiy37** [comment]
@izarutskaya, @NicMendonca, @mvtglobally. Guys, actually, there is not any bug here. 
There are a few variants of the category/tag list:
1. When items less than 8, it is a simple list. The app does not have any special sorting or sections.
2. When items more or equal 8, it has a search bar and few sections: "Selected", "Recent" and "All". First 2 sections exist only when it has items, the last section exist always.
3. When user use the search bar, it is a simple list. Items amount does not matter. 

<details><summary>Example</summary>
<p>

https://github.com/Expensify/App/assets/57314631/2ad84857-f145-44db-9f34-26c055e3c6d9

### I've added more tags, to have more than 8
<img width="1728" alt="Screenshot 2023-10-23 at 18 41 18" src="https://github.com/Expensify/App/assets/57314631/0dafb7d1-6a4c-43c7-b1c0-432f61c5d7eb">

https://github.com/Expensify/App/assets/57314631/f772ea47-ec4b-490b-b8cd-66c550f3968a

</p>
</details>

**Comment by abdel-h66** [comment]
Yes, it's the same conclusion as the above https://github.com/Expensify/App/issues/28804#issuecomment-1747271361
