### ISSUE TITLE
[$250] BA - Personal Information form isn't filled out with information that was added while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: user must be logged in and start the process to add a bank account to workspace until the "Personal information" form
1. Disable the internet connection
2. Fill out all the fields in the form
3. Refresh the page
4. Enable internet connection
5. Refresh the page

## Expected Result:
Personal Information form should be filled out with information that was added while offline

## Actual Result:
Personal Information form isn't filled out with information that was added while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.77-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/68aa5516-6859-45ed-8738-a7960ebba71e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b6caa1544280915</li>
        <li>Upwork Job ID: 1709580621374832640</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Ah great, thanks @Ollyws. Removing the deploy blocker label in that case. I think it's fine for us to just let what is on main reach production naturally. I'll leave this open so we can test it again after the next deploy.

**Comment by puneetlath** [comment]
Thanks for checking @Ollyws!
