### ISSUE TITLE
[HOLD for payment 2023-12-18] Web - Camera border color is different

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > profile
2. Check the border color around the camera icon

## Expected Result:
 Border color should be match with background

## Actual Result:
 Border color is different

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/93399543/733fadf8-5308-42b2-aac6-87e9db13945f)

![Screenshot 2023-09-15 at 10 14 21 AM](https://github.com/Expensify/App/assets/93399543/8488b7ab-9124-440c-b10f-7e3bd3a92dab)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694753216621329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120fb4ad1be8bb18b</li>
        <li>Upwork Job ID: 1709571217501925376</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by teneeto** [comment]
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by sobitneupane** [comment]
Sorry for the delay.

I will try to review the proposals before EOD tomorrow (NPT).

**Comment by sobitneupane** [comment]
@anmurali Should we confirm with the Design team whether this is a bug or intended design?

| Actual Result             |  Expected Result |
:-------------------------:|:-------------------------:
<img width="100" alt="Screenshot 2023-10-10 at 17 41 58" src="https://github.com/Expensify/App/assets/25876548/4c4c9cb6-b383-4225-ac71-8005aa8518d1">  |  <img width="100" alt="Screenshot 2023-10-10 at 17 41 23" src="https://github.com/Expensify/App/assets/25876548/5d16fa7c-af3b-4797-8ce4-845a7002e0f3">
<img width="38" alt="Screenshot 2023-10-10 at 17 42 32" src="https://github.com/Expensify/App/assets/25876548/38c2ae35-33ae-4a34-bb2a-626805e17ab8"> | <img width="38" alt="Screenshot 2023-10-10 at 17 42 52" src="https://github.com/Expensify/App/assets/25876548/df001c71-0a88-4f38-a8ab-7a839ca4098f">

**Comment by teneeto** [comment]
> @anmurali Should we confirm with the Design team whether this is a bug or intended design?
> 
> Actual Result	Expected Result
> <img alt="Screenshot 2023-10-10 at 17 41 58" width="100" src="https://user-images.githubusercontent.com/25876548/273891706-4c4c9cb6-b383-4225-ac71-8005aa8518d1.png">	<img alt="Screenshot 2023-10-10 at 17 41 23" width="100" src="https://user-images.githubusercontent.com/25876548/273891528-5d16fa7c-af3b-4797-8ce4-845a7002e0f3.png">
> <img alt="Screenshot 2023-10-10 at 17 42 32" width="38" src="https://user-images.githubusercontent.com/25876548/273891845-38c2ae35-33ae-4a34-bb2a-626805e17ab8.png">	<img alt="Screenshot 2023-10-10 at 17 42 52" width="38" src="https://user-images.githubusercontent.com/25876548/273891921-df001c71-0a88-4f38-a8ab-7a839ca4098f.png">

@anmurali @sobitneupane Any updates ?

**Comment by anmurali** [comment]
Asked [here](https://expensify.slack.com/archives/C049HHMV9SM/p1698179533282349?thread_ts=1694753216.621329&cid=C049HHMV9SM)

**Comment by sobitneupane** [comment]
Sorry for the delay. The proposals will be reviewed by tomorrow.

**Comment by grgia** [comment]
I can handle this, I'll be finalizing the themes for them switching

**Comment by anmurali** [comment]
@grgia - any updates?

**Comment by grgia** [comment]
will fix in https://github.com/Expensify/App/pull/32512

**Comment by grgia** [comment]
@anmurali all that's required to close this one out is $500 C+ review payment to @sobitneupane

**Comment by gadhiyamanan** [comment]
@grgia reporting bonus is pending , can you reopen the issue ...

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/28817#issuecomment-1865123753). Also re-opening for BZ to settle the comment above.

**Comment by anmurali** [comment]
[Offer](https://www.upwork.com/nx/wm/offer/100942999) for @mananjadhav for reporting bonus
@mananjadhav can you please update here when you accept? I am adding a BZ backup as I will be OOO

**Comment by MitchExpensify** [comment]
[The offer](https://www.upwork.com/nx/wm/offer/100942999) is indeed for @gadhiyamanan, thanks for the heads up though @mananjadhav! Please let me know when you have accepted @gadhiyamanan 🙇

**Comment by gadhiyamanan** [comment]
@MitchExpensify offer accepted, thanks!

**Comment by MitchExpensify** [comment]
Paid! Thanks
