### ISSUE TITLE
[ECard Transactions] Create eReceipt Component

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28828]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.7owsfnx4cddt

### Overview 

![Image](https://github.com/Expensify/App/assets/38015950/c6290d9f-bf19-462e-8f80-e9171ed3d0e4)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef1756e290850bce</li>
        <li>Upwork Job ID: 1709590746262466560</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
@grgia It's the first time I've gotten such an assignment. Should I request access to the Google Docs document and review it?

**Comment by grgia** [comment]
closing

**Comment by cubuspl42** [comment]
I do not require payment
