### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [ECard Transactions] Create Receipt Preview Component for eReceipts

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28826]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.ccj1ab3m8lq

### Overview 

![Image](https://github.com/Expensify/App/assets/38015950/f5ea8cf7-6602-466d-a521-ca0fc13104a5)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b29978114cac50a6</li>
        <li>Upwork Job ID: 1709590651145330688</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
@fedirjh can you apply to the job please? https://www.upwork.com/jobs/~01b29978114cac50a6

**Comment by NicMendonca** [comment]
sent offer!

**Comment by NicMendonca** [comment]
Thanks! Paid!
