### ISSUE TITLE
[HOLD for payment 2023-10-25] [ECARD] CRITICAL: Transactions - Link eReceipt Page to Receipt Preview

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28829]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.epr31aowxop2

### Overview 

**Goal:** 
Once we have [the new eReceipt page component](https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.7owsfnx4cddt), let’s link to it from the existing Transaction Thread.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e287df581057f74</li>
        <li>Upwork Job ID: 1709590903554031616</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
This seems a little different from the typical New Feature flow in [the BZ SO](https://stackoverflowteams.com/c/expensify/questions/14418#:~:text=BugZero%20process%20steps%20for%20feature%20requests), how would you like me to handle this ideally @joekaufmanexpensify / @grgia ? 😎

**Comment by joekaufmanexpensify** [comment]
Yeah, I think it's fine if you un-assign. IDT this really needs anyone from BZ for now. Once C+ reviews the PR, I think we create a separate payment issue then. And if not, we can assign someone from BZ then to handle payment.

**Comment by Santhosh-Sellavel** [comment]
@rushatgabhane is the C+ here.

**Comment by grgia** [comment]
@MitchExpensify or @joekaufmanexpensify could you verify that @rushatgabhane received $500 C+ review payment for https://github.com/Expensify/App/pull/29474

**Comment by MitchExpensify** [comment]
@rushatgabhane payment issue created https://www.upwork.com/jobs/~01d5f78c44d5c389cc

**Comment by grgia** [comment]
bump on payment status @rushatgabhane @MitchExpensify

**Comment by MitchExpensify** [comment]
*Payment summary:*

$500 - @rushatgabhane C+

Did you receive this yet on NewDot, @rushatgabhane ?

**Comment by rushatgabhane** [comment]
request here https://staging.new.expensify.com/r/5785180555158358

we can close the issue

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on comment above.
