### ISSUE TITLE
[HOLD for payment 2023-12-06] [ECARD] CRITICAL: Transactions - Enable MoneyRequestView Edit Transactions Logic

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28836]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.qpl4zgrq5w2x

### Overview 

Goal: 
We need to Hold on [updates to EditMoneyRequest](https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.c2qtzoxdtk1p) to handle card transactions. Once that’s complete, we will add the edit logic for non reimbursable transactions to NewDot.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149be352f2615a7b7</li>
        <li>Upwork Job ID: 1709592009508114432</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by grgia** [comment]
HOLD on edit functionality
cc @luacmartins

**Comment by Christinadobrzyn** [comment]
This is on Hold still

**Comment by grgia** [comment]
still on hold

**Comment by grgia** [comment]
on hold still, but close!

**Comment by Christinadobrzyn** [comment]
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: On hold but working on https://github.com/Expensify/App/pull/31353

**Comment by Christinadobrzyn** [comment]
Looks like the blocker label has been removed from https://github.com/Expensify/App/issues/32077 and @grgia is working on a solution. 

I think we're good to continue working on this job!

**Comment by Christinadobrzyn** [comment]
prepping for payment!

Payouts due:

Issue Reporter: NA
Contributor: NA
Contributor+: $500 @akinwale (in Upwork)

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~0178d694337026c11f).

**Comment by codewithnimesh** [comment]
> ### Design Doc Section
> https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.qpl4zgrq5w2x
> 
> ### Overview
> Goal: We need to Hold on [updates to EditMoneyRequest](https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.c2qtzoxdtk1p) to handle card transactions. Once that’s complete, we will add the edit logic for non reimbursable transactions to NewDot.
> 
> Upwork Automation - Do Not Edit


I checked your job posted on Upwork https://www.upwork.com/jobs/~0178d694337026c11f , FYI its private job i.e, its details are not visible in upwork. You may need to correct the access while generating JOB via bot :) 

Hi, I'm in interested in the project, let me know when we can have a quick discussion call?

**Comment by Christinadobrzyn** [comment]
Hi @codewithnimesh! Thanks for reaching out - this job is complete but feel free to apply to any jobs that have a Help Wanted label in our Expensify/App repo - https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

**Comment by Christinadobrzyn** [comment]
@akinwale I paid you in Upwork based on the payment structure here - https://github.com/Expensify/App/issues/28836#issuecomment-1841940306

Closing this but let me know if I'm missing anything!
