### ISSUE TITLE
[ECARD] HIGH: Transactions - Update MoneyRequestPreview UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28832]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.jq7ck5iu0lr0

### Overview 

Update the MoneyRequestPreviews to display the Card State.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121433690027f2201</li>
        <li>Upwork Job ID: 1709591375954538496</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Hmmm, what's left here to do? cc @grgia
