### ISSUE TITLE
[HOLD - pending convo][ECARD] HIGH: Transactions - Update Admin Pay Button Copy in ReportPreview/MoneyReportHeader

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28837]
### Design Doc Section

HOLD - see https://expensify.slack.com/archives/C05DWUDHVK7/p1700678791026919?thread_ts=1700600632.494789&cid=C05DWUDHVK7 and https://expensify.slack.com/archives/C036QM0SLJK/p1700232942102839

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.gq501xywgfmv

### Overview 

Goal:
Update the Pay Button depending on admin view, policy type, and types of transactions on the report. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cd4005e678faab2</li>
        <li>Upwork Job ID: 1709592172256550912</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
Not overdue 👍

**Comment by joekaufmanexpensify** [comment]
@grgia going through the wave 8 project, and saw this issue. Is this a critical part of the implementation, or more of a clean up issue?

**Comment by grgia** [comment]
@joekaufmanexpensify not critical, but I can get this done by tomorrow

**Comment by joekaufmanexpensify** [comment]
Cool cool, ty! Just wanted to confirm whether to put it in the update. But I'll leave it out for now if not critical.

**Comment by CortneyOfstad** [comment]
Any action needed from me @grgia? Thanks!

**Comment by grgia** [comment]
@CortneyOfstad not currently, just for C+ payment tracking when we do work on this PR

**Comment by grgia** [comment]
Will work on this tomorrow (Fri)

**Comment by grgia** [comment]
Holding on the auth command

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
@grgia any action needed? Thanks!
