### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [ECard Transactions] Update MoneyRequestAction UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28834]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.fda6ydo2faqu

### Overview 

Update (App) to[ display [Transaction Reversed]](https://github.com/Expensify/App/blob/f04a569b0ec4c3ccc0d901fa2be4943f00114de6/src/components/ReportActionItem/MoneyRequestAction.js#L132) if the parentReportAction has isReversedTrasaction

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014aa1ec026ee97169</li>
        <li>Upwork Job ID: 1709591775537315840</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Contributor: @parasharrajat $500 (payable via Manual Request)

@parasharrajat let me know once you've requested payment, we can close the issue at that point 👍

**Comment by sakluger** [comment]
Sounds good, closing 👍

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/28834#issuecomment-1775992248).
