### ISSUE TITLE
[HOLD for payment 2023-10-23] [ECard Transactions] Update ReportPreview Title 

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28833]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.o2b39rlbvmvl

### Overview 

<img width="537" alt="image" src="https://github.com/Expensify/App/assets/38015950/d100304e-5315-4774-8551-8131dfd6e70e">

<img width="767" alt="image" src="https://github.com/Expensify/App/assets/38015950/f77cff33-ec3f-4b48-bbe5-c0b4fb72b0ca">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1c0c18a4062ce7c</li>
        <li>Upwork Job ID: 1709591688111497216</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
@mananjadhav checking in to see if you'll be able to review today?

**Comment by mananjadhav** [comment]
Yes. I will be finishing this today.

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by greg-schroeder** [comment]
@mananjadhav you're free to make a manual request for $500 for your work on this issue!
