### ISSUE TITLE
[HOLD for payment 2023-10-16] [ECard Transactions] Update Transaction and Report Typescript Shapes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28838]
### Design Doc Section 

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.hkq9vo3f7a39

### Overview 

**Goal:** 
Update Transactions.ts and Report.ts with NVPs we are adding for this project.

<img width="717" alt="image" src="https://github.com/Expensify/App/assets/38015950/cb8bfb4d-8c20-4f98-9c45-2005d865c4c5">

<img width="700" alt="image" src="https://github.com/Expensify/App/assets/38015950/84c1ebe0-066e-454c-bbeb-e3cf35cb2c05">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2ff878968001a00</li>
        <li>Upwork Job ID: 1709592433673883648</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by grgia** [comment]
@eVoloshchak unassigning since this won't require QA

**Comment by tjferriss** [comment]
@grgia do you need anything from me here?

**Comment by grgia** [comment]
no payment for this one, closing
