### ISSUE TITLE
[HOLD for payment 2023-10-25] [ECard Transactions] Update MoneyReportView UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28831]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.814c36x8plt

### Overview 

![Image](https://github.com/Expensify/App/assets/38015950/51033eab-76be-49a4-9cfc-afd5824c11bf)

**Goal:** 
Update our Money Report Headers to separate out Company and Out-Of-Pocket spend. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8c70e4db5e9b4e3</li>
        <li>Upwork Job ID: 1709591085181034496</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by grgia** [comment]
I think this is the last one I need to do for the core UI, will try to get a PR up in the morning to wrap the major FE up

**Comment by s77rt** [comment]
@grgia Do we need a regression test here? I'm not sure what would be the test steps from the user/qa perspective to reproduce this

**Comment by lschurr** [comment]
@s77rt remind me - are you paid via Newdot or Upwork?

**Comment by s77rt** [comment]
@lschurr Upwork

**Comment by lschurr** [comment]
Great! Are you able to apply here @s77rt? https://www.upwork.com/jobs/~01d8c70e4db5e9b4e3

**Comment by s77rt** [comment]
@lschurr Applied! Thanks!

**Comment by lschurr** [comment]
Offer sent @s77rt!

**Comment by s77rt** [comment]
Accepted!

**Comment by lschurr** [comment]
Great! Paid. Closing.
