### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [ECard Transactions] Update MoneyRequestView UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28835]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.jzobwvipn5il

### Overview 

**Goal:**
Update the TransactionThread Report to support Card Transactions.  This PR will only update the UI. If isExpensifyCard(transaction.cardID) then we will lock editing transactions from NewDot temporarily and handle the edit action in a follow up PR ([see next section](https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=id.qpl4zgrq5w2x)).

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1446cbf110a63d8</li>
        <li>Upwork Job ID: 1709591847916027904</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by abekkala** [comment]
@grgia I believe we're good to just close this one, correct? 

@ArekChr does not require payment via upwork as they are from callstack.
