### ISSUE TITLE
[HOLD #28710] Confirmation page shows `Date` and `Merchant` fields in the Request Money > Scan flow 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#28856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Global Create > Request Money > Scan
2. Upload a receipt 
3. Click "show more" 
4. Observe the `merchant` and `date` fields are present and editable

## Expected Result:
The `merchant` and `date` fields shouldn't be present on the confirmation page when using `Request Money` > `Scan`

Context: The merchant, date and amount fields will be automatically read from the receipt uploaded, so the user shouldn't be entering them manually in this `Scan` flow like they can in the `Request Money` > `Manual` flow. 

## Actual Result:
`merchant` and `date` fields are shown on the confirmation page after uploading a receipt. 

## Workaround:
Yes, they can ignore them. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.77-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/16232057/23e04f28-01cb-415d-bd59-f9ed5d7c0e68">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** (internal) https://expensify.slack.com/archives/C02NZ2HGJAZ/p1696442783829229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dacf3611cdc71b0c</li>
        <li>Upwork Job ID: 1709773015190081536</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
Sorry @neonbhai I'm fixing this as part of this PR https://github.com/Expensify/App/pull/28710

**Comment by youssef-lr** [comment]
Seems like a recent PR has made these show up again, I will work on this as part of a follow up PR I'm working on right now

**Comment by trjExpensify** [comment]
@youssef-lr confirming we're good to close here?

**Comment by youssef-lr** [comment]
Yup!
