### ISSUE TITLE
[$500] Private Note - The link following the hashtag is not displayed in bold on the Private Notes page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to  staging
2. Go to any chat
3. Click on the header and navigate to Private notes
4. Go to My note > Notes
5. Add "# https://xvz.com/" and save it
6. Notice that the link following the hashtag is not displayed in bold

## Expected Result:
The link following the hashtag should appear in bold

## Actual Result:
The link following the hashtag is not displayed in bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (6)](https://github.com/Expensify/App/assets/93399543/bb578f5e-2ef7-45f6-b142-a3b643cf636d)
![image (5)](https://github.com/Expensify/App/assets/93399543/2676f51e-fee0-46a7-8d6c-1f5423893a49)

https://github.com/Expensify/App/assets/93399543/c323ad9d-18cd-4ff2-b4aa-1f6a1632327d

https://github.com/Expensify/App/assets/93399543/b9e0eb22-c312-42f4-98e5-c74349345afb

https://github.com/Expensify/App/assets/93399543/864e3be7-5588-4a36-97a1-06e61cbe818c

https://github.com/Expensify/App/assets/93399543/c986e5b6-b762-44a0-ae95-3386cc639ba1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696349893541419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011597f299ef538062</li>
        <li>Upwork Job ID: 1709670524467359744</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 27032777</li>
<li>aman-atg | Reporter | 27032783</li>
</ul></li>
    </ul>
</details>

**Comment by sicarius97** [comment]
@kbecciv Is this the behavior somewhere else in the app where it does work? I can't recall

**Comment by chahedmoetaz** [comment]
Hello,

I see this error on upwork https://www.upwork.com/jobs/~011597f299ef538062


I think that I have the solution::

First Locate the Code for Rendering Private Notes: 'on javascript code'

function renderPrivateNote(noteContent) {
    // Code for rendering private notes
}
Please pay attention to how text formatting and styling are applied.
Check for Styling Rules: 'CSS code'
/* Styling for links */
a {
    color: blue; /* Default link color */
    font-weight: bold; /* Make links bold */
}

/* Styling for hashtags */
.hashtag {
    font-weight: bold; /* Make hashtags bold */
}

and Verify that the HTML tags and attributes for styling are present. Links should be enclosed in <a> tags, and hashtags can have a specific class, e.g., <span class="hashtag">#hashtag</span>


Review JavaScript Interactions
Check for Overrides or Conflicting Styles
Test Different Browsers and Platforms
 Use Developer Tools for Debugging: ' javascript code'

function renderPrivateNote(noteContent) {
    console.log('Rendering private note:', noteContent);

    // Code for rendering private notes
}

Use the browser console to view the debug output and identify any issues with rendering or styling


Hope this can help you 
Please keep me updated 'chahedmoetaz@gmail.com'

**Comment by chahedmoetaz** [comment]
Contributor details
Your Expensify account email: chahedmoetaz@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0128c8fdf4ee06daca

**Comment by maxconnectAbhi** [comment]
# Project Title

## Please re-state the problem that we are trying to solve in this issue
The link following the hashtag is not displayed in bold

## What is the root cause of that problem?
We don't use wrapper for links for MenuItem component.

## What changes do you think we should make in order to solve the problem?
Need to make a `<comment>` wrapper around MenuItem title like `convertToLTR(props.title);`
(<comment> tag add special styles for links )

## What alternative solutions did you explore? (Optional)
NA

**Comment by narefyev91** [comment]
Proposal from @ZhenjaHorbach looks good to me https://github.com/Expensify/App/issues/28862#issuecomment-1747667281
🎀 👀 🎀 C+ reviewed
