### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Dev: Search - Going to search page crashes the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to search page

## Expected Result:
App should not crash

## Actual Result:
App crashes when opening search page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - missing
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.77-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9cdf2133-a23c-4832-86fd-69e1228fd24c

![simulator_screenshot_D69B1961-45EF-45A2-9D22-11131DED299C](https://github.com/Expensify/App/assets/93399543/fc3be86b-aa9b-4708-83f5-35f9c31b4a01)

https://github.com/Expensify/App/assets/93399543/36ce030b-745c-4527-8c73-cfa4eab0671f

https://github.com/Expensify/App/assets/93399543/18b8d004-fe9a-47c1-bd52-2e96114d3338

**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696451187529939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142683ca91cfb31ee</li>
        <li>Upwork Job ID: 1709680383220293632</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes in search page
### What is the root cause of that problem?
The crash is happening because in `reportAction.originalMessage.paymentType` `reportAction` is sometimes empty and accessing its properties throwing an error
https://github.com/Expensify/App/blob/447d87e9204578ccaf5c8e3a6887b97de531457e/src/libs/ReportUtils.js#L1553
### What changes do you think we should make in order to solve the problem?
Considering the function description `reportAction` has a default value of empty object suggesting that it might be empty object and this is not a required argument we should add conditions to prevent this error
https://github.com/Expensify/App/blob/447d87e9204578ccaf5c8e3a6887b97de531457e/src/libs/ReportUtils.js#L1524
We can add conditions preventing the access of its properties if `reportAction` is empty object, like:
```javascript
reportAction&&reportAction.originalMessage&&(
            _.contains([CONST.IOU.PAYMENT_TYPE.VBBA, CONST.IOU.PAYMENT_TYPE.EXPENSIFY], reportAction.originalMessage.paymentType) ||
            reportActionMessage.match(/ (with Expensify|using Expensify)$/))
```
Or we can use lodash like this:
```javascript
lodashGet(reportAction,["originalMessage",'paymentType']))
```
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
I ran into this locally earlier today and made branch with a fix

**Comment by mountiny** [comment]
no payments needed here
