### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] [Form Provider Refactor] CloseAccountPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28870]
Coming from [here](https://github.com/Expensify/App/issues/25397#issuecomment-1743272245), we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component. 

This issue is specific to refactoring `src/pages/settings/Security/CloseAccountPage.js`

cc @kowczarz 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0b63c230cc9d136</li>
        <li>Upwork Job ID: 1709703763605139456</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by abekkala** [comment]
waiting on PR 

Payments: 
- Reporter: N/A
- C+: software mansion - no payment
- PR Reviewer: @narefyev91

**Comment by abekkala** [comment]
@luacmartins it looks like you were the reviewer on PR (https://github.com/Expensify/App/pull/28627) attached to the bug report you linked above 

Which PR did @narefyev91 review that warrants payment via this particular GH?

**Comment by luacmartins** [comment]
We still don't have a PR for this issue. I think @narefyev91 got assigned to review the upcoming PR, but we gotta wait a bit

**Comment by luacmartins** [comment]
Still waiting on the PR.

**Comment by kowczarz** [comment]
Still working on other form PRs.

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task. Kamil reassigned it to me.

**Comment by abekkala** [comment]
No payments required. 

This is a refactor - also no checklist needed.
