### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] [Form Provider Refactor] EditRequestCreatedPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28878]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/EditRequestCreatedPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132a39fb2eb89aaac</li>
        <li>Upwork Job ID: 1709706091359973376</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by kowczarz** [comment]
PR is in progress https://github.com/Expensify/App/pull/29098

**Comment by kowczarz** [comment]
It will be done with https://github.com/Expensify/App/issues/28879, because it would require big overload to provide two separate PRs

**Comment by luacmartins** [comment]
PR has been merged, waiting deploy

**Comment by zanyrenney** [comment]
**payment summary**

reporting bonus - N/A internal
@allroundexperts does not require payment (Eligible for Manual Requests) - please request on ND $500
@kowczarz does not require payment (Contractor)

Closing out as no payments for me to make!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.
