### ISSUE TITLE
[HOLD for payment 2023-12-12] [HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] RoomNamePage and WorkspaceNewRoomPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28877]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Report/RoomNamePage.js` and `src/pages/WorkspaceNewRoomPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f44006a9fb9bd1d3</li>
        <li>Upwork Job ID: 1709705843518455808</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by NicMendonca** [comment]
@kowczarz any progress on this one? Thanks!

**Comment by kowczarz** [comment]
Hey, probably tomorrow I will prepare a PR.

**Comment by kowczarz** [comment]
Since it's pretty similar case as here https://github.com/Expensify/App/issues/28879#issuecomment-1755555524, I will handle `RoomNameInput` and `WorkspaceNewRoomPage` as well in this issue.

**Comment by NicMendonca** [comment]
Waiting for this to merge: https://github.com/Expensify/App/pull/28821

**Comment by kowczarz** [comment]
Finishing, today the PR will be ready.

**Comment by kowczarz** [comment]
PR is ready

**Comment by puneetlath** [comment]
If there are that many regressions I think it's better to revert than to put up fixes.

**Comment by luacmartins** [comment]
I agree with @puneetlath. If a PR caused multiple regressions it's better to revert it since adding multiple patches might delay the deploy if one of them is tricky and then a revert is no longer possible.

**Comment by luacmartins** [comment]
The PR was reverted and we have to work on a new one that takes the blockers into account @kowczarz @cdOut

**Comment by NicMendonca** [comment]
@allroundexperts bump on BZ check list ^^

**Comment by NicMendonca** [comment]
Reporter: N/A
Contributor: @kowczarz - payment not required 
Contributor + @allroundexperts - $500 - paid via Expensify

**Comment by JmillsExpensify** [comment]
That impacts the payout summary correct? If so, can we get a new one?

**Comment by JmillsExpensify** [comment]
@NicMendonca Mind updating the payment summary?

**Comment by NicMendonca** [comment]
- Reporter: N/A
- Contributor: @kowczarz - payment not required
- Contributor + @allroundexperts - $250 - paid via Expensify

**Comment by JmillsExpensify** [comment]
$250 payment approved for @allroundexperts based on summary above.

**Comment by NicMendonca** [comment]
we're all set here!
