### ISSUE TITLE
[HOLD for payment 2023-12-06] [HOLD for payment 2023-11-09] [$500] [Form Provider Refactor] AddDebitCardPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28876]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Wallet/AddDebitCardPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b882bb5f74f3ae3b</li>
        <li>Upwork Job ID: 1709705671346003968</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by dylanexpensify** [comment]
@kowczarz when can we expect a PR?

**Comment by dylanexpensify** [comment]
bump @kowczarz

**Comment by kowczarz** [comment]
I'm going to start working on this PR till the end of the week

**Comment by luacmartins** [comment]
@kowczarz is working on other related PRs, we'll get to this soon.

**Comment by dylanexpensify** [comment]
Sounds good!

**Comment by dylanexpensify** [comment]
In progress, any updates @luacmartins

**Comment by kowczarz** [comment]
I will start working on the PR today.

**Comment by dylanexpensify** [comment]
@kowczarz mind giving us an update

**Comment by dylanexpensify** [comment]
Amazing, ty @parasharrajat

**Comment by luacmartins** [comment]
@kowczarz @cdOut while testing this PR, we uncovered this issue with FormProvider that seems to affect other forms too - https://github.com/Expensify/App/issues/30703. Would you mind taking a look at it?

**Comment by dylanexpensify** [comment]
@kowczarz @cdOut any uodates?

**Comment by kowczarz** [comment]
@dylanexpensify I'm back from OOO, I will fix it today/tomorrow.

**Comment by dylanexpensify** [comment]
thanks @kowczarz!

**Comment by dylanexpensify** [comment]
how're we looking here @kowczarz

**Comment by dylanexpensify** [comment]
payment upcoming!

**Comment by dylanexpensify** [comment]
Payment summary: 
- Contributor: @kowczarz (SWM)
- Contributor+: @parasharrajat $500

Please apply!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
