### ISSUE TITLE
[WAITING ON CHECKLIST] [HOLD for payment 2023-10-23] [$500] [Form Provider Refactor] NewDatePicker

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28879]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/components/NewDatePicker/index.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e08fcb9456de83d2</li>
        <li>Upwork Job ID: 1709706449708163072</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by kowczarz** [comment]
I will refactor this component with `DateOfBirthPage`, `EditRequestCreatedPage` and `MoneyRequestDatePage` because separating these tasks would require big overhead.

**Comment by luacmartins** [comment]
Pr for this one has been merged

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @kowczarz (Invoiced)
- C+: @mananjadhav $500 (New.Dot)

NO UPWORKS JOB NEEDED

**Comment by jliexpensify** [comment]
@mananjadhav bump to complete the checklist (if required)!

**Comment by mananjadhav** [comment]
@jliexpensify There won't be any payout for me. @aimane-chnaif reviewed the PR, and their payout will be handled in [this issue](https://github.com/Expensify/App/issues/28871).

**Comment by jliexpensify** [comment]
Thanks Manan, closing this one out!
