### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] [Form Provider Refactor] DateOfBirthPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28871]
Coming from [here](https://github.com/Expensify/App/issues/25397#issuecomment-1743272245), we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component. 

This issue is specific to refactoring `src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js`

cc @kowczarz 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109777ed46da69786</li>
        <li>Upwork Job ID: 1709704196813975552</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by abekkala** [comment]
waiting on PR

Payments: 

- Reporter: N/A
- C+: Software Mansion - no payment
- PR Reviewer: @aimane-chnaif

**Comment by kowczarz** [comment]
It will be done with https://github.com/Expensify/App/issues/28879, because it would require big overload to provide two separate PRs

**Comment by luacmartins** [comment]
Agree that we don't need the checklist for this one. Just waiting on payment.

**Comment by abekkala** [comment]
<img width="639" alt="Screenshot 2023-10-27 at 3 42 50 PM" src="https://github.com/Expensify/App/assets/11966460/4c327f6b-3989-465d-aa17-cf1dc279027a">

@aimane-chnaif I have been trying to send an payment offer but I keep getting this error from Upwork. 
I'll keep trying!

**Comment by abekkala** [comment]
Finally!!
@aimane-chnaif offer sent! https://www.upwork.com/nx/wm/offer/27437905

**Comment by abekkala** [comment]
@aimane-chnaif payment sent and contract ended - thank you! 🎉
