### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] NewContactMethodPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28874]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Profile/Contacts/NewContactMethodPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd2034b42e8f51ab</li>
        <li>Upwork Job ID: 1709705014472392704</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27262140</li>
</ul></li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by laurenreidexpensify** [comment]
Thanks @kowczarz do you have ideas for a proposal yet?

**Comment by kowczarz** [comment]
@laurenreidexpensify that's a followup for this issue https://github.com/Expensify/App/issues/25397#issuecomment-1743272245. I think it would be reasonable to skip proposal similarly as it was done in function components migration and TypeScript migration.

**Comment by luacmartins** [comment]
Yep! No proposal needed here. Assigning @kowczarz to the job! Thanks for working on it.

**Comment by laurenreidexpensify** [comment]
Is there a draft PR up for this one yet?

**Comment by kowczarz** [comment]
Hey, not yet, there are 10 similar issues and I will work on them this week. I will ping you as soon as it will be ready.

**Comment by luacmartins** [comment]
waiting on PR

**Comment by laurenreidexpensify** [comment]
Do we have a PR up yet?

**Comment by luacmartins** [comment]
Not yet, we started with the [NewDatePicker, DateOfBirthPage, EditRequestCreatedPage](https://github.com/Expensify/App/pull/29098) forms first. Should get to this one soon!

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task. Kamil reassigned it to me.

**Comment by luacmartins** [comment]
@cdOut can you please follow the instructions in [this comment](https://github.com/Expensify/App/issues/28874#issuecomment-1768561018)?

**Comment by kowczarz** [comment]
Hi @luacmartins, @mountiny has already added @cdOut to the upwork whitelist (details in slack dm), but it takes some time to be deployed.

**Comment by luacmartins** [comment]
Cool, in that case I'll assign them to the issue!

**Comment by laurenreidexpensify** [comment]
Payment Summary - 

- External issue reporter - N/A 
- Contributor that fixed the issue - @cdOut payment N/A 
- Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 $500 payment issued in Upwork
