### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] StatusSetPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28875]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Profile/CustomStatus/StatusSetPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7b1ee3b931a15e2</li>
        <li>Upwork Job ID: 1709705460667637760</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27262000</li>
</ul></li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by MitchExpensify** [comment]
BZ checklist not necessary here right, @luacmartins ?

**Comment by luacmartins** [comment]
Np! not needed

**Comment by abdulrahuman5196** [comment]
Waiting on PR

**Comment by luacmartins** [comment]
@kowczarz is working on similar form provider refactors and will get to this one soon

**Comment by luacmartins** [comment]
We're still working on other forms. Will get to this one soon!

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task. Kamil reassigned it to me.

**Comment by abdulrahuman5196** [comment]
This is a refractor issue. No checklist required.

**Comment by MitchExpensify** [comment]
Paid and contract ended!
