### ISSUE TITLE
[$500] [Form Provider Refactor] AddressPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28872]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Profile/PersonalDetails/AddressPage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012aba0c7431d96aff</li>
        <li>Upwork Job ID: 1709704418695823360</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kowczarz</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by alexpensify** [comment]
@kowczarz -- any update on the proposal for this GitHub?

**Comment by luacmartins** [comment]
Similar to the hook refactor, I don't think we need a proposal for this one since the refactors are straightforward and follow the same pattern. @kowczarz authored the original refactor PR, so I think they are best suited to work on this as well :)

**Comment by alexpensify** [comment]
Thanks @luacmartins, sounds like a plan!

**Comment by alexpensify** [comment]
Update: Waiting for the PR to fix this issue

**Comment by luacmartins** [comment]
We're still working on other forms. Will get to this one soon!

**Comment by kowczarz** [comment]
Still working on other forms.

**Comment by kowczarz** [comment]
As soon as https://github.com/Expensify/App/pull/29983 will be merged I will start working on this issue.

**Comment by alexpensify** [comment]
Perfect, thanks @kowczarz for the update!

**Comment by alexpensify** [comment]
Daily Update: It looks like the PR mentioned above has some feedback that needs review.

**Comment by alexpensify** [comment]
Daily update: The PR is moving forward now.

**Comment by luacmartins** [comment]
Holding PR is merged. We're good to work on this

**Comment by alexpensify** [comment]
@kowczarz - all set, the blocker should be clear now. Thanks for reviewing again.

**Comment by alexpensify** [comment]
@luacmartins should we make this external again? Thanks for the update!

**Comment by alexpensify** [comment]
@luacmartins bumping again, should we make this external?

**Comment by luacmartins** [comment]
It seems to be external already and we got SWM working on it

**Comment by luacmartins** [comment]
@kowczarz is still working on related issues

**Comment by alexpensify** [comment]
Thank you @kowczarz for the update!

**Comment by alexpensify** [comment]
Daily Update: PR is moving forward!

**Comment by alexpensify** [comment]
Catching up from being OOO, it looks like the PR was reverted due to deploy concerns. @cdOut and @kowczarz - can you please share the next steps here and how we can keep moving forward? Thanks!

**Comment by alexpensify** [comment]
@cdOut and @kowczarz - any update here?

**Comment by cdOut** [comment]
There was a little bit of confusion due to multiple pages being named similarly. This issue will be done alongside this one, since they both address the same component, AddressForm: https://github.com/Expensify/App/issues/32064. After that one is merged, this one will also be refactored.

**Comment by alexpensify** [comment]
Thank you @cdOut for the update!

**Comment by alexpensify** [comment]
Daily Update: The PR is in draft mode.

**Comment by alexpensify** [comment]
Daily Update: The PR is ready for review!

**Comment by alexpensify** [comment]
Ok, now we will need to wait for automation here.

**Comment by alexpensify** [comment]
@luacmartins and @thesahindia it looks like automation didn't kick in here. Is this one complete? If yes, I'll need to start the manual payment process. Thanks!

**Comment by cdOut** [comment]
It is merged and completed.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @cdOut Software Mansion
-  Contributor+ that helped on the issue and/or PR - @thesahindia $500 

Upwork Job: N/A 

--- 

**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by alexpensify** [comment]
No update, waiting for confirmation that @thesahindia has submitted a payment request in Chat.

**Comment by alexpensify** [comment]
@thesahindia can you please confirm if you submitted a payment request? After, I can close this GH - thanks!

**Comment by alexpensify** [comment]
Awesome, thank you for the update!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/28872#issuecomment-1868349811).
