### ISSUE TITLE
Move HelpDot to from GitHub Pages to Cloudflare Pages

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#28888]
Slack context: https://expensify.slack.com/archives/C094TGUTZ/p1696058736845509

### Problem

We started using Cloudflare to run test builds of the HelpDot Jekyll site. This required us to update some dependencies in our Gemfile. However, those same dependencies cannot be met by GitHub Pages.

### Solution

Start using Cloudflare to host Expensify Help. This is more consistent with how New Expensify is hosted and also gives us an easy mechanism to address https://github.com/Expensify/App/issues/28209

**Comment by roryabraham** [comment]
cc @rushatgabhane

**Comment by coleaeason** [comment]
Migrated the site in the cloudflare settings, as of now it is running on Cloudflare Pages. 

Some small cleanup items:

1. Remove Github Pages from gem file
2. Turn off github pages integration

**Comment by coleaeason** [comment]
Turned off the GH pages integration, I don't think we actually need to change the gemfile.
