### ISSUE TITLE
[HOLD for payment 2023-12-04] [SMARTSCAN] MEDIUM: Allow users to re-download receipt if upload fails

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#28884]
**PROBLEM**
If a user uploads a receipt directly from the camera and then throws away the physical receipt, that receipt is gone forever if upload fails.

**SOLUTION**
As d[escribed in the design](https://docs.google.com/document/d/1Il9y1287B6tq0FB5ziXnhBcwn-Lw-n_rSmllZ-AyUVs/edit#bookmark=id.p6dykr9oyt15), allow the user to download any failed receipts
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b654f3591a45ce6</li>
        <li>Upwork Job ID: 1709727112645718016</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 Alberto, how are you getting on here? 

@isagoico was adding a few of the manual tests from the Scan Receipt doc, and it prompted me to come here. This is pretty whack at the mo: 

<img width="932" alt="image" src="https://github.com/Expensify/App/assets/16232057/ed1ac41b-0c67-4deb-9329-82893c28e3df">
Clicking the preview goes to a full page blocking form: 

<img width="921" alt="image" src="https://github.com/Expensify/App/assets/16232057/9e430ee2-a5a0-47ff-8454-8f4d1d0eaf7e">

Compared to the doc mock: 

<img width="675" alt="image" src="https://github.com/Expensify/App/assets/16232057/d063e65e-f877-479d-8fac-d9aa609298b0">

So just a few additional questions: 

1. Can we make sure the error messages also get updated with this change to be more discerning than "unexpected"?  
2. In the original design we were told we couldn't preview, so we went with `uploading attachment...`, but it seems like we've figured out an empty state thumbnail for the report preview component instead now. I'm not adverse to keeping that as is, but wanted to double check! 
3. Can we make sure we don't run into this "hmm.. it's not there" thing that makes it feel real broken? If you can't access the request transaction view in this state (to say, detach the receipt and fill out the details manually), we should just not make it clickable. 

Thanks!

**Comment by dylanexpensify** [comment]
@Gonals mind giving us an update today? 🙇‍♂️

**Comment by Gonals** [comment]
Yep. I haven't started on this yet, as I was OOO Thursday/Friday.

Once I'm caught up and done with the dailies, this comes after 😁

**Comment by Gonals** [comment]
Code ready! I'll do cleanup and screenshots tomorrow!

**Comment by Gonals** [comment]
In review!

**Comment by trjExpensify** [comment]
Putting this back to `daily`, let's close out this PR ASAP, it's so close.

**Comment by Gonals** [comment]
Hopefully merging today!

**Comment by garrettmknight** [comment]
@Gonals you're probably aware, but this isn't working on staging/prod. Check out this issue: https://github.com/Expensify/App/issues/31845

**Comment by Gonals** [comment]
AH, I thought we had reverted it!

**Comment by trjExpensify** [comment]
Putting back on daily, awaiting a [secondary PR review](https://github.com/Expensify/App/pull/32562#issuecomment-1875147241) from @NikkiWines.

**Comment by situchan** [comment]
Please assign me here. This is ready for payment

**Comment by dylanexpensify** [comment]
@situchan assigned

**Comment by dylanexpensify** [comment]
@Gonals what's left to do here? Just payments?

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @0xmiroslav $500 
- Contributor+: @situchan $500

Please request!

**Comment by dylanexpensify** [comment]
@situchan remind me, are you paid in ND yet?

**Comment by situchan** [comment]
@dylanexpensify not yet

**Comment by mallenexpensify** [comment]
> Contributor+: @0xmiroslav $500
Contributor+: @situchan $500

@dylanexpensify for payment confirmations, can you please us a format that both includes if the contributor is paid or is owed money (paid as in Upwork, owed as in waiting for NewDot payment) and also include where they are paid and owed? Upwork or NewDot.  Below is the TextExpander I use, I leave the second blank since many C+ are paid via Newdot. 

> Contributor: @ paid $ via Upwork
Contributor+: @ 

Removed the `Reviewing` label here too

**Comment by dylanexpensify** [comment]
sounds good, thanks @mallenexpensify!

**Comment by dylanexpensify** [comment]
@situchan sent invite for [this job](https://www.upwork.com/jobs/~01ddadb8bef996a4b3)!

**Comment by dylanexpensify** [comment]
offer sent!

**Comment by dylanexpensify** [comment]
done!
