### ISSUE TITLE
[HOLD for payment 2023-11-07] Start migrating lists that are ready from FlatList to FlashList

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#28902]
## Problem

While FlatList is suitable for typical use cases, our goal is to achieve the highest level of app performance, especially when dealing with extensive lists, such as Chats, Threads, Workspaces, Reports, and specific Money Threads.

## Solution

To address this performance challenge, switch from FlatList to FlashList. By making this transition, we anticipate a significant performance improvement of approximately 2x.

## Next Steps

Some lists are ready to migrate to FlashList, some are not (e.g. ChatList)

Here is a non-exhaustive list of lists that are ready for migration. If you find more, please feel free to add more!

[LHNOptionsList](https://github.com/Expensify/App/blob/bce37385dbc60a4dcade3b357fd346ac683d5547/src/components/LHNOptionsList/LHNOptionsList.js#L76-L89)
EmojiPickerMenu ([web](https://github.com/Expensify/App/blob/4b8fc0adbfac534d53a8ad0baf209267c57a5245/src/components/EmojiPicker/EmojiPickerMenu/index.js#L527-L547) and [native](https://github.com/Expensify/App/blob/4b8fc0adbfac534d53a8ad0baf209267c57a5245/src/components/EmojiPicker/EmojiPickerMenu/index.native.js#L180-L201))
[BaseAutoCompleteSuggestions](https://github.com/Expensify/App/blob/97320a0abbc04bfdd5395db4e0ca7d0de2f5d1ff/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L95-L105)
[PaymentMethodList](https://github.com/Expensify/App/blob/0e82698cf19835bcb59b23b7c14f3abe7597c295/src/pages/settings/Wallet/PaymentMethodList.js#L223-L230)

Then let's work through the list of lists and get them migrated. Sound like a plan?

**Comment by adhorodyski** [comment]
Hi, I am Adam from Callstack, an expert contributor group. I’d like to work on this :)

**Comment by dylanexpensify** [comment]
@roryabraham to confirm: any payments due here?

**Comment by roryabraham** [comment]
Nope

**Comment by roryabraham** [comment]
This has been split up so I'm closing it out
