### ISSUE TITLE
[$500] mWeb: Settings - Page closes from right to left side if page is reloaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings, open any page, Eg- WS list page
2. click the back button Note that page closes left to right
3. Now open WS list page again and reload the page

## Expected Result:
Page closes transitioning from left to right

## Actual Result:
Page closes transitioning from right to left side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.78-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9b25277f-4407-4a88-a640-3c7e42143065

https://github.com/Expensify/App/assets/115492554/bae5456d-0eeb-4896-99c8-f08cd1a1c94e

https://github.com/Expensify/App/assets/115492554/e6e62921-ac75-4858-99b3-993e53ae1986

https://github.com/Expensify/App/assets/115492554/09c4c48d-edbd-43ae-968d-4f3faf009828

https://github.com/Expensify/App/assets/115492554/afd66b87-b37e-4a5f-a127-b4372c1f4028

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ishpaul777

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696271916082989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0a10f37348abc95</li>
        <li>Upwork Job ID: 1709899494899417088</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
This happens with every screen out there. Whenever we refresh we loose the navigation state, so when we click on Back Icon instead of pop we navigate so the animation is in reverse order. 

I already reported this issue day ago (closed).

**Comment by garrettmknight** [comment]
@b4s36t4 can you link me your report?

**Comment by garrettmknight** [comment]
@b4s36t4 bump on the request to link your report - I want to review the response to it to confirm whether it should have been considered a bug and/or whether we should consider this a bug.

**Comment by garrettmknight** [comment]
I'm going to close for now since this is the behavior everywhere, so it's not really inconsistent, but I'll reopen if my review of the other report makes me think differently.
