### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Create `setupNewDotWebForEmulators` 

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#28910]
# FOR BUG ZERO TEAM
https://github.com/Expensify/App/issues/28910#issuecomment-1754285321

## Context
> We plan to change the URL to serve the App on the development environment from localhost:8082  to [new.expensify.com.dev](http://new.expensify.com.dev/) in [this PR](https://github.com/Expensify/App/pull/28422). This can be accomplished by adding a new entry to the laptop's hosts file along with changes made in the PR.
However, we're not sure how we can access the App on Safari or Chrome on iOS or Android simulators.

# Create `setupNewDotWebForEmulators` script described below.

## Proposal
Configure iOS simulators and Android emulators to connect to new.expensify.com.dev over https for local development.

### Please re-state the problem that we are trying to solve in this issue.
We are adding https to the webpack-dev-server. Furthermore, we are configuring our dev machines to redirect requests from `https://new.expensify.com.dev` to `127.0.0.1` (aka `localhost`).

However, this is not working out-of-the-box on iOS Simulators and Android Emulators.

### What is the root cause of that problem?
The root causes are different per-platform.

#### iOS
iOS Simulators inherit the hosts file from the mac computer they're running on. However, you still won't be able to connect because the iOS Simulator does not have the certs that you set up for SSL.

#### Android
The Android emulator will not inherit the hosts file from the mac computer they're running on. It is missing the hosts file so will not know that when you go to `new.expensify.com.dev` you mean `localhost`.

#### iOS
Boot an iOS simulator then run the following command to provide the correct certs to the Simulator:

```bash
xcrun simctl keychain booted add-cert ./config/webpack/certificate.pem
```

#### Android
We need to push the `/etc/hosts` file from the workstation to the emulator with the following command:

```bash
adb root
adb remount
adb push /etc/hosts /system/etc/hosts 
```

If you see an error about the system being readonly, try the following in order:

```bash
adb root
adb disable-verity
adb reboot
adb root
adb remount
adb push /etc/hosts /system/etc/hosts
```

#### Packaging it all up
People will have to do this anytime they set up a new simulator/emulator and want to connect to `new.expensify.com.dev`. That's kind of annoying, but at least we can package it up in a script like `setupNewDotWebForEmulators`. That way – if people have forgotten or never encountered these routing / SSL problems, they can just run `npm run setupNewDotWebForEmulators`, and as long as they followed the setup steps for SSL in webpack, it should work.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016381e2cc76fceca1</li>
        <li>Upwork Job ID: 1709910071627542528</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 27048389</li>
<li>b4s36t4 | Contributor | 27141130</li>
<li>akinwale | Contributor | 27154634</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
# Please still submit a formal proposal with the high level overview of the new script

**Comment by shubham1206agra** [comment]
## Proposal

Configure iOS simulators and Android emulators to connect to new.expensify.com.dev over https for local development.

### Please re-state the problem that we are trying to solve in this issue.

We are adding https to the webpack-dev-server. Furthermore, we are configuring our dev machines to redirect requests from `https://new.expensify.com.dev` to `127.0.0.1` (aka `localhost`).

However, this is not working out-of-the-box on iOS Simulators and Android Emulators.

### What is the root cause of that problem?

@hayata-suenaga Already described the RCA here

### What changes do you think we should make in order to solve the problem?
We should create platform-dependent script, i.e., `npm run setupNewDotWebForEmulators --platform {iOS|Android|All}`
#### iOS

Boot an iOS simulator (`open -a Simulator.app`)

```shell
xcrun simctl keychain booted add-cert ./config/webpack/certificate.pem
```

#### Android

We need to push the `/etc/hosts` file from the workstation to the emulator with the following command:

```shell
adb root
adb remount
adb push /etc/hosts /system/etc/hosts 
```

We will put try-catch mechanism to catch problems with the first script and then run the second script

```shell
adb root
adb disable-verity
adb reboot
adb root
adb remount
adb push /etc/hosts /system/etc/hosts
```

**Comment by shubham1206agra** [comment]
> @shubham1206agra is it possible that in the script we can ask the user which simulator to open and configure (just like we do with iOS right now?) or is it too complicated?

I am already trying to do that.
But so far I haven't found a way cause the Simulator doesn't accept any list argument.
Lemme check the react-native scripts

**Comment by hayata-suenaga** [comment]
Hey @rayane-djouah, thanks for diving deep into the strategy! 
While you've built upon @shubham1206agra's original idea, the core concept came from them. So, I'm gonna assign this issue to @shubham1206agra.

**Comment by shubham1206agra** [comment]
@hayata-suenaga Can you provide me `certificate.pem` file for testing iOS flow?

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga Can you provide me certificate.pem file for testing iOS flow?

@shubham1206agra I believe if you pull [this PR](https://github.com/Expensify/Expensify/issues/322808#issuecomment-
1748751679) and follow the README instruction (if you can see the diff for the file), you can produce `certificate.pem` file on your machine

let me know if this answers your question 🙇

**Comment by shubham1206agra** [comment]
@hayata-suenaga This is an internal PR

**Comment by shubham1206agra** [comment]
@hayata-suenaga PR is up

**Comment by hayata-suenaga** [comment]
[Anyone who can figure out the issue @shubham1206agra is facing will receive $250 as par this post](https://expensify.slack.com/archives/C01GTK53T8Q/p1696908081857169?thread_ts=1696900731.521939&cid=C01GTK53T8Q)

**Comment by hayata-suenaga** [comment]
[Anyone who can figure out the issue @shubham1206agra is facing will receive $250 as par this post](https://expensify.slack.com/archives/C01GTK53T8Q/p1696908081857169?thread_ts=1696900731.521939&cid=C01GTK53T8Q)

**Comment by hayata-suenaga** [comment]
> [Anyone who can figure out the issue @shubham1206agra is facing will receive $250 as par this post](https://expensify.slack.com/archives/C01GTK53T8Q/p1696908081857169?thread_ts=1696900731.521939&cid=C01GTK53T8Q)

@b4s36t4 helped us [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1696989888632709?thread_ts=1696900731.521939&cid=C01GTK53T8Q)

**Comment by b4s36t4** [comment]
Commenting

**Comment by shubham1206agra** [comment]
@akinwale why have you been assigned here?

**Comment by akinwale** [comment]
> @akinwale why have you been assigned here?

@shubham1206agra I'm taking over the C+ review and testing from @mananjadhav. It looks like melvinbot got a little confused.

**Comment by shubham1206agra** [comment]
@hayata-suenaga if possible can we get the bonus cause the issue has problems which took some time to investigate?

**Comment by hayata-suenaga** [comment]
@jliexpensify this issue is an external issue that creates a new feature that developers can use when working on NewDot.

The new development feature turned out to be tricky and I agree with @shubham1206agra that the work involved turned out to be tricker than simple bug fixes.

I think we can pay:

$750 for @shubham1206agra 
$250 for @b4s36t4 for their help in figuring out a blocking issue
$250 for @mananjadhav for their partial work as a C+ (They needed to drop the issue to work on other high priority issues)
$500 for @akinwale for taking over the issue as C+ from @mananjadhav 

In the above payment summary, the payment for C+ ($750) is split between @mananjadhav and @akinwale 

Let me know if you agree

**Comment by jliexpensify** [comment]
Happy to write up the Payment Summary for J.Mills and pay based off your list @hayata-suenaga - is there a payment date though?

**Comment by hayata-suenaga** [comment]
ah did I provide payment summary too early 😓 let's wait until the PR is deployed to production and regression period ends.

> Happy to write up the Payment Summary for J.Mills.
I think J.Mills is not assigned to this issue though

**Comment by jliexpensify** [comment]
@hayata-suenaga for Manan, he needs to be paid via New.Dot, which requires a Payment Summary for J.Mills to sign off on :)

**Comment by jliexpensify** [comment]
Going off @hayata-suenaga 's summary [here](https://github.com/Expensify/App/issues/28910#issuecomment-1763536814):

Payment Summary

- Contributor: $750 for @shubham1206agra
- Contributor: @b4s36t4 $250 
- C+: @akinwale $500
- C+: @mananjadhav $250 (New.Dot)

[Upwork job](https://www.upwork.com/jobs/~016381e2cc76fceca1)

**Comment by akinwale** [comment]
These were a set of bash scripts implemented, so no need to complete a checklist here.

cc @jliexpensify

**Comment by JmillsExpensify** [comment]
$250 payment approved for @mananjadhav based on summary above.

**Comment by jliexpensify** [comment]
Everyone is paid and job has been closed, thanks!
