### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500]  mWeb / Chrome – Paste option not working in Request money BNP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with gmail+ email account
3. Click the FAB menu in LHN
4. Click on "Request money" Manual
5. Enter an amount into the BNP and press Next button
6. Long press for paste the previously copied phone number

## Expected Result:
The same behavior in Search/Send message/Assign task

## Actual Result:
The Paste menu appears

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b659a52-b795-4c9f-8b0a-e50dd7dc0f21

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a724c9953b2fbe17</li>
        <li>Upwork Job ID: 1711323897428279297</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27181189</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by flaviadefaria** [comment]
Added the external label.

**Comment by flaviadefaria** [comment]
@strepanier03  I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by s-alves10** [comment]
This was added to fix the https://github.com/Expensify/App/issues/24654
https://github.com/Expensify/App/blob/e078b4a424c1b26f4de7be868ca55afd6cb03f2a/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L138-L139

And I agree with @parasharrajat We should avoid including hacks in core components.

**Comment by strepanier03** [comment]
Working on this now, sorry I missed it yesterday.

**Comment by strepanier03** [comment]
@bernhardoj - I've paid you via Upwork and closed the contract, thank you again for your work as part of the community!

@parasharrajat - I'll keep an eye out for the checklist responses and move this forward when you have some bandwidth to post them.

**Comment by strepanier03** [comment]
Thank you @parasharrajat, working on this now.

**Comment by strepanier03** [comment]
### Payment Summary

- C+ - @parasharrajat - $500 + $250 = $750 via Manual Requests

Please put in your Manual Request @parasharrajat. I'm going to close this and assign to @JmillsExpensify for payment.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @parasharrajat based on comment above.
