### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Fix the inconsistency of not being able to create threads on all system messages in NewDot

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#28934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a request
2. Edit the amount to generate a "change" system message
3. Observe you can't start a thread on the system message
4. Pay the request to generate a "paid" system message
5. Observe that you can start a thread on the paid system message

## Expected Result:
You should be able to start a thread on all system messages in NewDot

## Actual Result:
We're inconsistent. Some you can, some you can't for no good reason. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.77-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="808" alt="image" src="https://github.com/Expensify/App/assets/16232057/b2d747c5-1cb6-4cd3-b74b-2709790155ae">

<img width="847" alt="image" src="https://github.com/Expensify/App/assets/16232057/49ab8cf4-6d55-451d-b3e9-8440ad972579">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** (Internal) https://expensify.slack.com/archives/C03U7DCU4/p1696435492003729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c13143627c2ed36</li>
        <li>Upwork Job ID: 1709972345317482496</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27163513</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@thesahindia can you review these proposals, please?

**Comment by youssef-lr** [comment]
Not overdue!

**Comment by trjExpensify** [comment]
👋 @thesahindia checklist time!

**Comment by trjExpensify** [comment]
>We weren't handling this case. I think we just have to add a test case.

I wonder if there's something we can do to try and prevent this from happening again in the future? It seems as though new report actions were added and showing `reply in thread` on them weren't considered. As a result, that introduced the inconsistency. Would something in the PR checklist help with this perhaps?

**Comment by trjExpensify** [comment]
Hm, I'm not sure. I'd imagine we're going to be adding report actions a fair bit through reunification aren't we. @tgolen is always a good sense check on this kind of stuff for me. Tim, am I being a bit overkill suggesting adding a note to the PR checklist for making sure if you add a new report action to NewDot, you don't forget to not hide the `Reply in thread` comment action menu item? 

We ran into this issue here where some were available to start threads on and others weren't just because of oversight on needing to do this. 

Thanks!

**Comment by tgolen** [comment]
This one is tricky. I don't think adding anything to the checklist is going to help, but it's also not going to hurt. People just don't read the checklist probably 95% of the time.

To have a full proof way to prevent this, it would be best to have an automated solution like:
- A custom ESLint rule
- If ^ isn't possible, then add a GH action which sees if a PR has added a new action (maybe based on file name? Are all actions stored in the same place?) and then checks to see if the logic for this line was also updated in the same PR.
- Maybe better to change the logic for `Reply in thread` which wouldn't require it to be updated for every new action (for example, rather than checking for all the actions you CAN reply to, only check for the ones you CANNOT reply to, or vice versa, whatever)
- We could have an action configuration file that lists all the actions, and whether or not they can be replied to (this makes it easier for people to understand that they have to think about this setting when they create a new action)

**Comment by trjExpensify** [comment]
Thanks, Tim! Given that being able to thread on pretty much anything is a pretty integral part of the NewDot experience, I think it's important that we ensure the consistency on starting them on report actions. @thesahindia what do you think about running with this?

**Comment by trjExpensify** [comment]
bump @thesahindia for your thoughts. :)

**Comment by trjExpensify** [comment]
Okay great, so how do we go about putting that in place?

**Comment by trjExpensify** [comment]
Created an issue here and I've added you to it for the C+ and context. @dukenv0307 if this is something you would be interested in putting together as a follow-up, do jump in.

**Comment by trjExpensify** [comment]
Confirming payments for this issue as follows:

- @dukenv0307 $750 for the fix & #urgency bonus as per [here](https://github.com/Expensify/App/issues/28934#issuecomment-1778932701).
- @thesahindia $750 for the C+ review & #urgency bonus. 

Bonus applies as the PR was created prior to the cut off for urgency bonus. 

@dukenv0307 I've paid you, @thesahindia you can request on NewDot. Closing! 👍
