### ISSUE TITLE
[$500] Android - Close Account - Secondary device users are not signed out when Main device Close account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Multiple devices that are logged in to the same account
1. Open ND Android app
2. Go to Settings > Security > Close Account

## Expected Result:
Devices that are logged in to the same account shout get closed and redirected to the Sign in page

## Actual Result:
Secondary device users are not signed out when Main device Close account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.78.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1b2a14c2-f5fc-4e60-997b-23f1fba66eb6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01084db84454adb4c7</li>
        <li>Upwork Job ID: 1711316062036361216</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Not overdue, chill out melvin

**Comment by malikfaiq** [comment]
Contributor details
Your Expensify account email: malikfaiq44@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/malikfaiq
