### ISSUE TITLE
[HOLD for payment 2023-10-16] [distance] suggested addresses don't appear for place names

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#28936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the green plus, Request money
2. Select the distance tab
3. Click start
4. Type "Expensify lounge SF"

## Expected Result:
The address for the Expensify lounge in SF should show up as a suggestion

## Actual Result:
No results are found

## Workaround:
Look up the address in another map application, which is bad because the user leaves our app.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All, based on the code
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.78-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**

https://github.com/Expensify/App/assets/26260477/f98eaa45-014a-4eb1-bf15-b7c435679a4f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696525943231939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
@abekkala please remind me to create propose a regression test for this

**Comment by abekkala** [comment]
Reminder for self: remind @neil-marcellini 😂

**Comment by neil-marcellini** [comment]
### Regression Test Proposal
1. Click the green plus, Request money
2. Select the distance tab
3. Click start
4. Type "Expensify lounge SF"
5. Verify that a suggestion for the Expensify lounge in SF shows up below the input
6. Select it
7. Verify that you are navigated back to the distance request page and the address is filled in for the start waypoint

- Do we agree 👍 or 👎

**Comment by neil-marcellini** [comment]
Looks like Melvin did a good job reminding me. All you now @abekkala 😄

**Comment by abekkala** [comment]
@neil-marcellini can I confirm that Tim Golen did your review and this particular one does not require a payment to anyone? 

I can create the Regression Test GH for Applause given your steps above.

**Comment by abekkala** [comment]
@neil-marcellini can you confirm above?

**Comment by abekkala** [comment]
From what I can tell we didn't have an external contributor involved in this. 
Closing. 

If I have that wrong and someone needs payment reopen please
