### ISSUE TITLE
[$500] [Distance] - The i(toggle attribtion) button remains focused after the options are closed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to Distance
3. Click on i(toggle attribution) button on  the map
4. Click on it again and close the options

## Expected Result:
The focus on the button should be removed when the options are closed automatically unless it is hovered

## Actual Result:
The focus remains on the button until you click elsewhere.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4ed39449-094d-4287-a374-ffef531c0a95

https://github.com/Expensify/App/assets/93399543/446bd722-4af8-44cd-94af-c9d8ea6e7888

https://github.com/Expensify/App/assets/93399543/2090f49a-6375-4544-9356-b7707fb47301

https://github.com/Expensify/App/assets/93399543/8b668dbc-0359-4b3f-a774-0e6179f5a455

https://github.com/Expensify/App/assets/93399543/f18842e4-243d-4de9-9339-174ff0a0ea2c

https://github.com/Expensify/App/assets/93399543/1a6889d1-5cbf-42f4-9fd7-9ef85a24937a

https://github.com/Expensify/App/assets/93399543/7f0ab015-0eec-4b8f-88b8-7872f7c9e8dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696276129044149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c4e73ac98f317d1</li>
        <li>Upwork Job ID: 1710000652487176192</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The i(toggle attribtion) button remains focused after the options are closed

### What is the root cause of that problem?
This is issue of Mapview.
When button is focus, that shadow is show.
So button shadow is not relative with opening alert.
### What changes do you think we should make in order to solve the problem?
We can control that shadow using css.
We can add this in css.
```
.mapboxgl-ctrl-attrib-button:focus {
    box-shadow: none;
}
.mapboxgl-compact-show button {
    box-shadow: 0 0 2px 2px #f00 !important; // Need to change color to origin color
}
```
Then result

https://github.com/Expensify/App/assets/65789015/50d1ddac-1f2b-47f3-8bb5-bf6c992bae9c

As you can see, alter and shadow appear only together.

### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment]
This is not worth fixing, and we might remove the mapbox attribution and info later, so definitely not worth it.
