### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] The "Merchant" title and page briefly appear instead of the distance title and page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the "+" button or go to the expense room
2. Navigate to Request money > Distance
3. Select Start and Finish points and proceed with the request
4. Quickly go to the distance request detail page and click on “Merchant”
## Expected Result:
 The "Merchant" title and page should not be displayed even for a brief moment when requesting money for a distance
## Actual Result: 
The "Merchant" title and page are briefly shown instead of the distance page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - Emulator not working and didn't attach video 
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop - missing since desktop is crashing

**Version Number:** 1.3.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/5b49684f-9274-4541-ae4f-e95309fe43cc

https://github.com/Expensify/App/assets/38435837/ea4292e6-1253-4d9e-bea7-5bf39b277f40

https://github.com/Expensify/App/assets/38435837/87c7d8d3-7147-40a3-b906-16a0f8961395

https://github.com/Expensify/App/assets/38435837/a4efe4da-6670-4c34-adf0-185ad1a02bc9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696452613289539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e052b456797c7dfb</li>
        <li>Upwork Job ID: 1710009572771434496</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by neil-marcellini** [comment]
I've fixed this in https://github.com/Expensify/App/pull/27204

**Comment by burczu** [comment]
Can't test it right now on current `main` - there is some issue `GooglePlacesAutocomplete`. I'll get back to it later to check again.

**Comment by neil-marcellini** [comment]
To be clear I have a fix in that PR I linked above.

**Comment by adelekennedy** [comment]
@neil-marcellini @burczu the only payout due here is the reporting bonus - is that correct?
Payouts due:

Issue Reporter: $50 @ayazhussain79 

Eligible for 50% #urgency bonus? N

Upwork job is [here]().

**Comment by adelekennedy** [comment]
@ayazhussain79 sent you an offer

**Comment by ayazhussain79** [comment]
@adelekennedy offer accepted, Thank you

**Comment by adelekennedy** [comment]
Paid! @burczu does the bugzero checklist above apply here? If not I will close the issue

**Comment by neil-marcellini** [comment]
Bump @burczu

**Comment by neil-marcellini** [comment]
@adelekennedy don't you want credit for your BZ work here? I'm re-assigning you as the issue owner.

**Comment by adelekennedy** [comment]
@burczu please reopen this issue if the checklist is needed - otherwise closing since payments have been made
