### ISSUE TITLE
Android - Compose-Paste multiline message, cursor behavior inconsistent in mweb & android when scroll

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28940]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap on a report
3. Paste on compose box -
~_*d, bhgfh, hugfg ghjgkkhhjj
g
h
h*_~
> |•||•••
```
√√√√
```
`√√√√√√√√√`
4.Scroll up and down and note cursor stays at end point
5.Launch app
6.Tap on a report
7. Paste on compose box -
~_*d, bhgfh, hugfg ghjgkkhhjj
g
h
h*_~
> |•||•••
```
√√√√
```
`√√√√√√√√√`
8.Scroll up and down

## Expected Result:
When user scrolls up and down, cursor behaviour must be consistent in both mweb and android

## Actual Result:
When we paste multiline message, cursor behavior is inconsistent in mweb and android, when we scroll up and down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5a116c7f-5b3b-4a7e-b724-3e30d170f540

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Are you saying this isn't a bug @bernhardoj ?
