### ISSUE TITLE
[Awaiting C+ offer acceptance] [$500] [MEDIUM] Distance: Improve the delay in the map image showing within the distance request preview on creation

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#28965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Global create > request money > distance 
2. Enter a start/finish address > next > request
3. Observe the empty state receipt preview
4. Wait 4-5s
5. Observe the receipt preview update to the map thumbnail

## Expected Result:
Minimal delay if any in the UI to display the map route. @neil-marcellini had a suggestion to take a snapshot of the route image, or render the route map until the response comes back.

## Actual Result:
The response takes a little while and so it's super noticeable that we're waiting on the API request to return the map image. As a result we have this less than premium experience whereby:

1. You see a thumbnail of the map pre creation on the confirmation screen
2. Click request and it turns into a green empty state preview for 4-5s
3. Then it updates and the map route is shown again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.78-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/16232057/ea51fd0a-2cc6-424f-89ba-8feb7e696974

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @JmillsExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fab7e23c87b42e3c</li>
        <li>Upwork Job ID: 1710051983554887680</li>
        <li>Last Price Increase: 2024-01-08</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28097325</li>
<li>shubham1206agra | Contributor | 28097326</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by AmjedNazzal** [comment]
I think maybe we should wait for this ongoing [refractoring](https://github.com/Expensify/App/issues/26538#issuecomment-1722050434) before we make changes to distance.

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Improve the distance request preview on the creation.

### What is the root cause of that problem?

The map route is missing cause we are waiting for the backend to give the image, which takes 4-5 seconds.

### What changes do you think we should make in order to solve the problem?

Make a snapshot of the map from Mapbox and send the temp image in an optimistic report while executing `CreateDistanceRequest` so that we can see the map (which is a little different) so that we can static map image till the API returns a response.

### What alternative solutions did you explore? (Optional)

### Result

https://github.com/Expensify/App/assets/58412969/ce5811db-8586-41c9-bace-d34837a346eb

**Comment by shubham1206agra** [comment]
@aimane-chnaif If you want a test branch to test the feature, please write it here.
I will do that.
I have chosen not to write too many details just an overview of the idea, cause there are many changes to write and will make the proposal cluttered. I have instead put the video as proof
cc @trjExpensify

**Comment by trjExpensify** [comment]
>I think maybe we should wait for this ongoing https://github.com/Expensify/App/issues/26538#issuecomment-1722050434 before we make changes to distance.

Oh hm, I don't quite see the correlation myself on this issue, but @tgolen is a smarter man than I, so I'll tag him here for vis!

**Comment by tgolen** [comment]
This is only tangentially related to my refactoring (I'm basically rewriting the entire creation flow while trying to keep all the existing behavior). So, it doesn't need to be held on my work, but will create some cleanup for one of us depending on the order the code is merged.

I think it's OK to move forward with exploring solutions, but it would really be nice to halt the actual development so that it builds off of my refactored code instead of the currently existing code.

I have a few thoughts about this issue in general:

- There are two things that we are waiting for with the MapBox API on the server: first, an image of the route. Second, the distance between the waypoints so that the `amount` can be calculated. I don't think we can do anything about the second one. We will always need to wait. That makes this issue more about the first part, the map image. If that's the case, then @trjExpensify can you please update the issue title and description to be more clear on what this issue is focusing on?

- As for doing an optimistic rendering of the map, I think it would be difficult to get an image preview of the map only from the frontend (correct me if I'm wrong... maybe the frontend MapBox API has an easy way of doing that). However, what would be very easy is to embed the actual map, using the optimistic waypoints, into the receipt preview. We would just disable all interactions with the map, and to the user, it should look almost exactly like the eventual receipt image that is returned from the server. The only case where this wouldn't work is in the offline flow, but I think that's OK and expected since the map also wouldn't have rendered in the creation steps.

**Comment by tgolen** [comment]
It functionally looks like what we are expecting, yes. How are you taking an image snapshot of the map?

**Comment by shubham1206agra** [comment]
For native, there is an inbuilt function and for the web, some manipulation of DOM elements give this (mainly canvas)

**Comment by trjExpensify** [comment]
>I think it's OK to move forward with exploring solutions, but it would really be nice to halt the actual development so that it builds off of my refactored code instead of the currently existing code.

Ah okay cool, noted. Once we're aligned on a solution I'll pop a hold in the title and link to the issue/PR. 👍 

>There are two things that we are waiting for with the MapBox API on the server: first, an image of the route. Second, the distance between the waypoints so that the amount can be calculated. I don't think we can do anything about the second one. We will always need to wait. That makes this issue more about the first part, the map image. If that's the case, then @trjExpensify can you please update the issue title and description to be more clear on what this issue is focusing on?

Yep, agreed. This issue is about the map image. Re: the `amount` on the preview component, that seems pretty good as it is now. It's the map image showing on confirmation > disappearing > reappearing which is the jarring thing. I've updated, but feel free to suggest further edits if needs be! 

>The only case where this wouldn't work is in the offline flow, but I think that's OK and expected since the map also wouldn't have rendered in the creation steps.

I agree this okay, for the same reason you mentioned. 👍

**Comment by neil-marcellini** [comment]
> * As for doing an optimistic rendering of the map, I think it would be difficult to get an image preview of the map only from the frontend (correct me if I'm wrong... maybe the frontend MapBox API has an easy way of doing that). However, what would be very easy is to embed the actual map, using the optimistic waypoints, into the receipt preview. We would just disable all interactions with the map, and to the user, it should look almost exactly like the eventual receipt image that is returned from the server. The only case where this wouldn't work is in the offline flow, but I think that's OK and expected since the map also wouldn't have rendered in the creation steps.

Although doing a snapshot is possible, I agree that rending the map component with interactions disabled is probably best, especially because we already have code to do that. If we're offline we should render the pending map view instead.

**Comment by shubham1206agra** [comment]
@neil-marcellini I think we should do snapshot as making map component in preview and view may make code a little complex to maintain. If we have showed the map on success request, then the logical way is to create map in optimistic also. But in this case, snapshot is more correct way to go.

**Comment by trjExpensify** [comment]
Not overdue, Melv. Discussing the finer details of the plan here.

**Comment by tgolen** [comment]
I think adding snapshots also adds complexity (especially with the mention of native code vs. `canvas`). We already have the map component, so let's just use that instead of a snapshot.

**Comment by shubham1206agra** [comment]
> I think adding snapshots also adds complexity (especially with the mention of native code vs. `canvas`). We already have the map component, so let's just use that instead of a snapshot.

Nope
Canvas was required in one line in the code, which is just used to take out the image.

**Comment by tgolen** [comment]
OK, I'm still going with the executive decision to use the map component though. If you are OK using that component, please update your proposal to use it. If you do not want to use that component, this GH will remain open to accept other proposals.

**Comment by shubham1206agra** [comment]
Ok
I will update it then

**Comment by neil-marcellini** [comment]
@aimane-chnaif please review the updated proposal

**Comment by neil-marcellini** [comment]
Oh yeah true. Thanks. @shubham1206agra please update it soon 🙇‍♂️

**Comment by shubham1206agra** [comment]
Sadly I have been facing some network issues right now

I will post the updated solution when the problem resolves

**Comment by shubham1206agra** [comment]
How this for Distance Request?

### Money Request View
<img width="1512" alt="Screenshot 2023-10-13 at 5 33 36 PM" src="https://github.com/Expensify/App/assets/58412969/0a434da6-c842-4429-85c7-61f7de8a932c">

### Money Request Preview
<img width="1512" alt="Screenshot 2023-10-13 at 5 33 54 PM" src="https://github.com/Expensify/App/assets/58412969/f47da3a1-1b9f-48e3-890f-ce909e87b523">

**Comment by shubham1206agra** [comment]
If you want a video for the same, please tell me

**Comment by trjExpensify** [comment]
I think a video showing the behaviour would be great, thanks.

**Comment by trjExpensify** [comment]
UI looks good from my perspective!

**Comment by trjExpensify** [comment]
@shubham1206agra just confirming, is your proposal ready for @aimane-chnaif to review?

**Comment by shubham1206agra** [comment]
Yes ig

**Comment by trjExpensify** [comment]
Cool, @aimane-chnaif can you now review the proposal please? :)

**Comment by trjExpensify** [comment]
Perfect, yes, we're going to hold doing the work on Tim's refactor but we wanted to be ready. @tgolen mind confirming the PR number I can add to the issue title?

**Comment by neil-marcellini** [comment]
I think we want to hold it on #29107 but Tim can double check that.

**Comment by trjExpensify** [comment]
Perfect, thanks for confirming. Popping this on `weekly` as we await the hold.

**Comment by trjExpensify** [comment]
Still holding on the refactor, Melv.

**Comment by trjExpensify** [comment]
No change, still held.

**Comment by shubham1206agra** [comment]
False alert here.

**Comment by trjExpensify** [comment]
Still held.

**Comment by trjExpensify** [comment]
Okay, so based on a discussion in Slack on Friday, this issue can now come off hold. @aimane-chnaif, can you confirm you green light [the proposal](https://github.com/Expensify/App/issues/28965#issuecomment-1775169164)?

**Comment by shubham1206agra** [comment]
Ok will do

**Comment by trjExpensify** [comment]
@shubham1206agra did you update that?

**Comment by shubham1206agra** [comment]
I will update it today

**Comment by trjExpensify** [comment]
Thanks!

**Comment by shubham1206agra** [comment]
Will update this today. Sorry for the delay.

**Comment by trjExpensify** [comment]
Sounds good, @shubham1206agra. Please let us know here! :)

**Comment by shubham1206agra** [comment]
@trjExpensify Can we hold this on https://github.com/Expensify/App/pull/33043?
As I was getting some problem in editing waypoint behaviour, which seems to be fixed in above

**Comment by trjExpensify** [comment]
Sure, looks like that PR only needs @hayata-suenaga's secondary approval now. :)

**Comment by hayata-suenaga** [comment]
looking at it now

**Comment by shubham1206agra** [comment]
@trjExpensify @aimane-chnaif Here's the testing branch 
https://github.com/shubham1206agra/App/tree/test-map

I haven't refined the request preview yet (mainly minor styling)

**Comment by trjExpensify** [comment]
@aimane-chnaif what's your ETA on assessing this proposal review now that it's unblocked?

**Comment by trjExpensify** [comment]
@aimane-chnaif did you get to it?

**Comment by shubham1206agra** [comment]
Looks like branch is outdated. Let me redo this branch.

**Comment by shubham1206agra** [comment]
But the current branch as a whole should work. It doesn't depend on other changes.

**Comment by shubham1206agra** [comment]
<img width="1512" alt="Screenshot 2024-01-09 at 5 58 41 PM" src="https://github.com/Expensify/App/assets/58412969/d73c46b1-c06d-4b62-aaed-f600c24b6fa5">

<img width="1512" alt="Screenshot 2024-01-09 at 5 58 55 PM" src="https://github.com/Expensify/App/assets/58412969/2ee70cf0-6eef-4094-ad73-60f8d0cb2c4c">

<img width="1512" alt="Screenshot 2024-01-09 at 5 59 14 PM" src="https://github.com/Expensify/App/assets/58412969/1c69408d-62c5-463d-b214-de5926614715">

Updated the branch, and these are the results.

**Comment by trjExpensify** [comment]
@grgia can you give this a secondary review, please? Though, @tgolen or @hayata-suenaga perhaps you would like to as you were both closer to the distance requests implementation. Thanks!

**Comment by grgia** [comment]
I think the proposal looks alright, but I agree with @trjExpensify that we should have someone from the original project check off as well

maybe @neil-marcellini ?

**Comment by tgolen** [comment]
I think that proposal is fine. I remember discussing this at some point during the creation of the V1 and we decided to do nothing for it back then. I think it's a good improvement and the method in the proposal makes sense.

**Comment by hayata-suenaga** [comment]
I agree with @tgolen

**Comment by trjExpensify** [comment]
👋 @shubham1206agra, when can we expect a PR for this? Thanks!

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
What's the latest @shubham1206agra?

**Comment by shubham1206agra** [comment]
I will try to finish the screenshot of PR today.

**Comment by trjExpensify** [comment]
@grgia can you review the PR, please? :)

**Comment by trjExpensify** [comment]
PR hit staging 15 hours ago

**Comment by trjExpensify** [comment]
Whoops! Looks like the automation failed here. This is ready to be paid. @aimane-chnaif @shubham1206agra can you guys confirm the number of regressions for the payment summary? Thanks!

**Comment by trjExpensify** [comment]
>@trjExpensify Not a regression but a follow-up feature request which is low on the priority scale right now.

Okay, payment summary as follows:

- $500 to @shubham1206agra for the fix
- $500 to @aimane-chnaif for the C+ review

**Comment by trjExpensify** [comment]
@shubham1206agra paid!

**Comment by trjExpensify** [comment]
Aimane is out of office, dropping to weekly

**Comment by trjExpensify** [comment]
Paid!
