### ISSUE TITLE
IOU - Category does not auto select when IOU created with same merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap Workspace chat
3. Tap plus icon
4. Tap request money
5. Enter an amount
6. Tap next
7. Tap show more
8. Tap category and select any category
9. Tap merchant and enter eg, "school" deleting "Request"
10. Tap Save
11. Tap request amount
12. Tap plus icon and select request money
13. Enter an amount
14. Tap next
15.  Dont select any category
16. Enter same merchant name used for first IOU " school"
17. Tap request amount
18. Tap both IOU and note category section

## Expected Result:
Category must auto select when an IOU is created with the same merchant

## Actual Result:
Category does not auto select when an IOU is created with the same merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c6d1fd82-a33e-45e1-be87-985117e36f05

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
This one isn't a bug. We realized implicit categorization hasn't been built yet, so it'll get handled here: https://github.com/Expensify/Expensify/issues/322628
