### ISSUE TITLE
[HOLD for payment 2023-11-01]  Category IOU - Admin is unable to edit Category for a paid request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User has created a workspace in OD and invited an employee
1. Log in to staging,new,expensify.com as an employee
2. As an employee, create a money request with a category from the workspace chat
3. After the request is created, disable all categories on OD as admin
4. As admin, pay the IOU request and go to IOU report
5. As admin, return to OD and enable all categories
6. As admin, go back to the paid IOU report

## Expected Result:
Admin is able to edit Category for a paid request

## Actual Result:
Admin is unable to edit Category for a paid request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f832dacd-0cd0-4d41-93f6-bf596d7f33b4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
👋 @lanitochka17 just a heads up that a request on a workspace is added to an `expense` report not an `iou` report. The repro steps state `iouReport` but the video shows an `expense` report because it's to the workspace.

**Comment by trjExpensify** [comment]
Also, the expected and actual results are the same. 

>**Expected Result:**
>Admin is able to edit Category for a paid request
>
>**Actual Result:**
>Admin is able to edit Category for a paid request

**Comment by trjExpensify** [comment]
@puneetlath @rezkiy37 @waterim @joekaufmanexpensify categories bug, who wants it? 😅

**Comment by puneetlath** [comment]
Ahh, interesting. I can take over the BZ from you @trjExpensify. 

@rezkiy37 would you want to look into it?

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
> 👋 @lanitochka17 just a heads up that a request on a workspace is added to an `expense` report not an `iou` report. The repro steps state `iouReport` but the video shows an `expenseReport` because it's to the workspace.

Just to clarify: from tech. perspective is it still an `iOU`?

<img width="1727" alt="Screenshot 2023-10-06 at 13 26 36" src="https://github.com/Expensify/App/assets/57314631/982b6c32-4bc4-4da2-a51c-5b97f18e31eb">

**Comment by rezkiy37** [comment]
Can only edit if:

  - in case of IOU report
     - the current user is the requestor **and** is not settled yet
  - in case of expense report
     - the current user is the requestor **and** is not settled yet
     - or the user is an admin on the policy the expense report is tied to
     
Guys, can you confirm that it is a correct situation?

**Comment by mountiny** [comment]
> Guys, am I right that an admin can modify any value of an expense request after it was paid, not only a category?

No, they cannot modify amount/currency and created values. Admins can modify other fields than those two after its reimbursed

> Just to clarify: from tech. perspective is it still an iOU?

The terminology is a bit intertwined and can be confusing. The IOU action type are any money request related actions. But IOU report is only between people. When its between employee and workspace is Expense report which is different report type.

Both however contain IOU type report actions (create, pay, split).

**Comment by rezkiy37** [comment]
The PR - https://github.com/Expensify/App/pull/29101 - is being review internally now.

**Comment by mart4g** [comment]
**TESTS SUMMARY**
This is retested, it is fixed now. Please see the video attached (tested platforms: Google Chrome Version 117.0.5938.149, Safari Version 17.0, Desktop v v1.3.85-0 )

https://github.com/Expensify/App/assets/147029649/5ab31845-fa5d-49c7-8244-cd3a37cdf8e5

**Comment by puneetlath** [comment]
@fedirjh was the C+ here. 

@fedirjh could you please handle the checklist?

**Comment by puneetlath** [comment]
Friendly reminder about the checklist so that we can pay on Wednesday.

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by puneetlath** [comment]
@fedirjh Upwork offer is here: https://www.upwork.com/nx/wm/offer/27475726

Please ping me on the issue when you've accepted.

**Comment by puneetlath** [comment]
All paid, thanks everyone!
