### ISSUE TITLE
Workspace IOU - Broken IOU preview is created when more than one IOU is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User has created a workspace in OD and invited an employee
1. Log in to staging,new,expensify.com as an employee
2. Go to workspace chat > + button > Request money
3. Create a money request with description and a category
4. Click on the IOU preview to go to IOU report
5. Return to 1:1 DM > + button > Request money
6. Create a second money request with description and a different category

## Expected Result:
Both IOUs now will combine in one IOU preview in 1:1 DM

## Actual Result:
There are two IOU previews in 1:1 DM
The first IOU preview comes from the second request, which leads to an error page when clicked on
The second IOU preview is the correct IOU, with both IOU requests combined in one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/250a0c3a-7318-4ed5-818b-4e141f352cf8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
https://github.com/Expensify/App/assets/14225673/e3adcf30-b85a-437b-9de4-b8c5f0831687

Cannot reproduce

**Comment by lanitochka17** [comment]
Issue reproducible on Build 1.3.83-10


https://github.com/Expensify/App/assets/78819774/bc50061c-df94-4e0b-986b-9dbc27715b33

**Comment by anmurali** [comment]
No, I still cannot reproduce this.
