### ISSUE TITLE
[HOLD for payment 2023-11-02] Category IOU - Incorrect ordering of subcategories in the category menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisites:
Account Setup https://sites.google.com/applausemail.com/applause-expensifyproject/guides/newdot-categories
Setting up categories 1) https://expensify.testrail.io/index.php?/tests/view/3767005
2) https://expensify.testrail.io/index.php?/tests/view/3767010

Steps:
1. Open https://staging.new.expensify.com/
or app
2. Log in to your Employee account
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Manual' and add an amount
6. Click on the "Next" button
7. Select the configured WS
8. Click 'show more' and click on 'Category'

## Expected Result:
Subcategories should be displayed laddered under each other with a space to the left

## Actual Result:
The subcategory for the parent subcategory is not displayed in a ladder, but is displayed at the very end of the category list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9173b717-232c-4c54-9130-1631bf2cfe61

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@rezkiy37 would you want to look into this one? It does seem like there is an issue with multiple levels of nesting. For example, this is what I'm seeing on this policy titled `Collect Policy` (which I just added you to). 

<img width="999" alt="image" src="https://github.com/Expensify/App/assets/1371996/8e781839-0244-4436-9148-03218c39573e">

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/1371996/1bb6a4aa-82fd-4b4a-9e32-907982217d43">

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
> @rezkiy37 would you want to look into this one? It does seem like there is an issue with multiple levels of nesting. For example, this is what I'm seeing on this policy titled `Collect Policy` (which I just added you to).
> 
> <img alt="image" width="999" src="https://user-images.githubusercontent.com/1371996/273589903-8e781839-0244-4436-9148-03218c39573e.png"> <img alt="image" width="376" src="https://user-images.githubusercontent.com/1371996/273589974-1bb6a4aa-82fd-4b4a-9e32-907982217d43.png">

So, I've investigated this case. We have a problem when there are 2 "same" named categories. Actually, the app checks for a duplicate and ignores duplicated names. This case I am trying to handle and fix.

<img width="588" alt="Screenshot 2023-10-10 at 16 43 33" src="https://github.com/Expensify/App/assets/57314631/7a3ac584-681e-4e95-a1b8-5332e41e1f33">

What about the attached video on a PR's description. Basically, the app does not order or re-order categories. I takes a list from the backend and iterates item by item. I want to make sure that we have a proper ordered list from the backend before. 
@lanitochka17, could you please record network responses where there are updated category lists? Can we confirm that the backend sends a correct order?

**Comment by puneetlath** [comment]
@rezkiy37 and I worked together today and were able to reproduce the issue. He's working on the fix.

**Comment by rezkiy37** [comment]
@puneetlath, I have 4 updates and a question:

1. Already working on a draft PR - https://github.com/Expensify/App/pull/29281.
2. I've fixed the bug, when the app hides a category with the same name, but one of them is nested - https://github.com/Expensify/App/issues/28964#issuecomment-1752951320.
3. I've found and fixed a bug, when the app crashes, because of 2 nested categories with the same name, but different parent.
4. I extended tests to cover more cases.

**Question:**
Actually, the app receives categories with incorrect ordering. So, is it **OldDot**, **NewDot** or **backend** work to order categories in proper way? If it is **NewDot's** work, I cannot guarantee the same order, as user has in **OldDot**. 

<img width="1728" alt="User" src="https://github.com/Expensify/App/assets/57314631/2382f303-53af-4bb7-9f75-1044794cd201">

**Comment by puneetlath** [comment]
I think we should have NewDot do the ordering, because it isn't always going to receive a full list. For example, if we add a Category, the client will only receive the new category, not the updated entire list. So the client will need to do the ordering itself. 

>I cannot guarantee the same order, as user has in OldDot.

I think this is fine. Thanks for checking though!

**Comment by rezkiy37** [comment]
Melvin, preparing a PR for the issue.

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by Christinadobrzyn** [comment]
whoops! sorry I thought I was on this GH. Well I created the regression test. Hopefully that's ok - https://github.com/Expensify/Expensify/issues/331796

**Comment by puneetlath** [comment]
All good, thanks for the help @Christinadobrzyn 😄

**Comment by puneetlath** [comment]
@Christinadobrzyn did you also issue payment or is that still needed?

**Comment by Christinadobrzyn** [comment]
Hi, no sorry I didn't issue payment, just created the regression GH. Let me know if you want me to do that and I'll be happy to!

**Comment by puneetlath** [comment]
All good, I got it! Thanks for the quick response. 

@cubuspl42 offer here: https://www.upwork.com/nx/wm/offer/27560910

Please ping me on this issue once you've accepted it.

**Comment by cubuspl42** [comment]
@puneetlath Accepted

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
