### ISSUE TITLE
IOU- "Test" parent category is not greyed out and displayed in "category" list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Old dot as Policy admin
2. Tap Policy settings-categories
3. Create a new Category called "Test"
4. Create a few subcategories under "Test"
"Test: Test 1"
"Test: Test 2"
"Test: Test 3"
5. Disable the "Test" category

1. Go to https://staging.new.expensify.com/
2. Tap workspace chat As Employee
3. Tap plus icon and select request money
4. Enter an amount
5. Tap next
6. Tap show more
7. Tap categories and scroll down to view the list

## Expected Result:
"Test" parent category must be greyed out and displayed in the "category" list

## Actual Result:
"Test" parent category is not greyed out and displayed in "category" list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/53942fa4-8cca-4f66-b5a7-3ae6164b3d44

![Bug6226554_1696543979836!Screenshot_2023-10-06-02-44-29-692_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/ab41bfef-b0bf-45e9-bb6a-245b55233466)

**Expensify/Expensify Issue URL:**
 
 **Issue reported by:** Applause - Internal Team
 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@lanitochka17 you need to make sure to add a space between the parent and child categories. So `Parent: Child` instead of `Parent:Child`. Then it should work. 

It worked for me when I tested: 

<img width="997" alt="image" src="https://github.com/Expensify/App/assets/1371996/5d2a494a-cafa-475d-87aa-a2f45e06c17a">

<img width="385" alt="image" src="https://github.com/Expensify/App/assets/1371996/b3fbce81-5fe8-4dcd-826b-5d1dd01f1b8f">

**Comment by lanitochka17** [comment]
@puneetlath Hello. Thanks for clarifying
