### ISSUE TITLE
[HOLD for payment 2023-10-20][$500] Web - IOU Category - Non-selectable parent for subcategories can be selected with arrow keys

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Admin has created a few subcategories that do not have a parent category for a workspace on OldDot.
1. Log in to https://staging.new.expensify.com/
as the workspace employee.
2. Go to the workspace chat > + button > Request money > Manual.
3. Enter any amount and click Next > Show more > Category.
4. Using keyboard arrow, navigate to the grayed-out parent.
5. Hit Enter.

## Expected Result:
The grayed-out parent is not selectable. User should not be able to navigate to it with arrow keys on keyboard.

## Actual Result:
The grayed-out parent can be selected using keyboard, although it is not visually visible. Hitting Enter results in a subcategory being selected randomly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.78-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b08f75f8-7997-4d15-85ba-4c336375e2a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139e85a909ef2f65e</li>
        <li>Upwork Job ID: 1710215405315522560</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27096010</li>
<li>tienifr | Contributor | 27096012</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by akinwale** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/28988#issuecomment-1750405992) correctly identifies the root cause and the proposed solution is adequate.

@tienifr It looks like the `optimisticPolicyRecentlyUsedCategories` list is always updated for every request, so it's feasible to also remove empty items from `uniquePolicyRecentlyUsedCategories` [here](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L481), since that already has a filter operation.

🎀 👀 🎀 C+ reviewed.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. It appears that this particular case wasn't tested during the original implementation.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**
1. Log in to Expensify as a workspace employee (account needs to be added to a Collect or Control policy with categories and subcategories created).
2. Open the global create menu and select Request money.
3. Select the Manual tab if it is not already active.
4. Enter any amount and click Next.
5. Click show more, and click Category.
6. Navigate the categories using the keyboard arrow keys.
7. Verify that the parent categories cannot be focused or highlighted when navigating with the arrow keys.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@kevinksullivan Just noting here that the PR was originally deployed to production on 2023-10-13, so the correct payment due date should be 2023-10-20. There were some deployment issues afterwards which caused the bot to update the title multiple times.

Thanks.

**Comment by Julesssss** [comment]
Lol, fixed the title

**Comment by akinwale** [comment]
@kevinksullivan bump for payment. Thanks.

**Comment by akinwale** [comment]
@kevinksullivan bump. Thanks.

**Comment by kevinksullivan** [comment]
all set
