### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500]Thread - Undefined displayed in header offline when opening left thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Navigate to a conversation
3. Start a thread and send some messages
4. Disable internet connection
5. Tap the three dots and leave the thread
6. Open the thread again and rejoin

## Expected Result:
The parent message is shown in the header or "hmm, it's not there" screen

## Actual Result:
"Undefined (archived)" is displayed in the header and there is no option to rejoin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.79-2

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a4fbd5ec-4c3a-4fa9-b467-442d0ee7012e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4c2c4838dc79392</li>
        <li>Upwork Job ID: 1710244942675664896</li>
        <li>Last Price Increase: 2023-10-27</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27059051</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by izarutskaya** [comment]
On web and mweb there is no header at all, just the "U" avatar.
On Prod, it shows not here page. No infinite loading

https://github.com/Expensify/App/assets/115492554/1faf8705-13d4-4260-b6cc-071260bcc996

**Comment by graylewis** [comment]
### Proposal
Please re-state the problem that we are trying to solve in this issue.
When offline and attempting to rejoin a thread, the app displays "undefined (archived)" as the title of the chat on iOS and Android native. Optimally, there would be a message displayed here that says something like "You are offline" instead.

What is the root cause of that problem?
In the getReportName function, archived rooms are concatenated with "(archived)" without any check to see if the name of the room is defined. Since the only data available through onyx is the stateNum and the statusNum (this is the optimistic data flow), the name of the room is undefined and you end up with "undefined (archived)" 

What changes do you think we should make in order to solve the problem?
1. Add a check to see if `formattedName` is undefined on line 1832 of ReportUtils.js. This is best practice and will prevent similar future potential errors. 
2. Since a 404 error doesn't really make sense (the thread exists after all) I would recommend either showing a "you are offline" placeholder or persisting the parent name of the thread to disk when the thread is deleted. If it's important that all left threads are not persisted to disk, then I'd recommend the "you are offline" placeholder. 

What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment]
@tienifr Please go ahead!

**Comment by graylewis** [comment]
@mountiny I agree with @bernhardoj, the solution to this problem should be local in scope. The handling for the data flow in this component is broken because of how the name is calculated. A larger solution should be implemented to handle how unloaded screens are handled in offline mode. The PR that @tienifr references corrects a previous misstep that was obfuscating this issue from being found.

**Comment by mountiny** [comment]
@tienifr Apologies, but after giving this another and deeper look, I agree this should not be a blocker really. 

I agree we should handle this better, but we need to probably decide what the expected outcome is. 

@shawnborton Would you be able to help us here to determine the expected outcode:

1. User is in a chat where there is a thread they have not visited
2. It shows there are 4 replies in the thread
3. User is offline
4. They attempt to navigate to the thread they never visited before so there is no data locally

How should we handle this? Should we show some pages as "Sorry, you are offline, to see the messages, connect to the internet". I think that blocking pattern is not what we want here, we want to allow the user to comment there but also give them feedback that there are some comments in the thread, which they know from the parent chat view, but as they navigate to the thread, they cannot read them obviously. They can however, post comments offline.

Thank you!

**Comment by shawnborton** [comment]
Hmm yeah, I don't think we want any kind of full page blocking behavior. I think we'd follow the same pattern we would as a room they accessed offline right? Basically use the skeleton place holders for the chats. cc @trjExpensify as you are my go-to guy for offline pattern questions.

**Comment by trjExpensify** [comment]
Yeah, this is an interesting one. I think the skeleton loader oover the messages is correct in the pattern. Whether that's super clear that they won't load until you're back online or not is another question really.

**Comment by peterdbarkerUK** [comment]
>Whether that's super clear that they won't load until you're back online or not is another question really.
@trjExpensify @shawnborton where's the best place to figure out an answer to this question?

**Comment by shawnborton** [comment]
What's the latest here?

**Comment by trjExpensify** [comment]
>@trjExpensify @shawnborton where's the best place to figure out an answer to this question?

When there's some tangible feedback on it probably. For now, this is correct in the established pattern: 

>I think the skeleton loader over the messages is correct in the pattern

**Comment by peterdbarkerUK** [comment]
Great, thanks - in which case it sounds like we agree on what should be happening then (Skeletons). @ArekChr could you take a look at the proposals above as well as the work by @bernhardoj ?

**Comment by peterdbarkerUK** [comment]
@ArekChr friendly bump here :)

**Comment by ArekChr** [comment]
@peterdbarkerUK Sorry for delay here, today i participated in some workshops, I plan to review the it tomorrow morning.

**Comment by ArekChr** [comment]
@bernhardoj, I understand your analysis of the root cause. However, navigating back to the previous screen before making the API.write call or delaying it would be more beneficial. This approach seems to have two main advantages:

1. It prevents blocking UI changes, ensuring a smoother user experience.
2. Instead of writing changes and potentially displaying an empty room, skeletons, or an undefined header, we would immediately return to the previous screen, providing a more seamless transition for the user.

Also, I have another question, as this could be another solution: Do we need to clear out all the data right after leaving a thread? What if we just left the thread data and set only the state of the joined thread status so we don't show an empty report and header? I’m just wondering if there’s a good reason we’re doing it this way now and if maybe there’s a smoother way to handle it. cc: @mountiny @shawnborton 

I delayed the API write call using `setTimeout`, which is not the best approach. I also moved the navigation logic to the top. UX is smoother, here are results:

https://github.com/Expensify/App/assets/24796318/e40dbbcd-d844-427e-a4e1-f08b86c8abd9

**Comment by mountiny** [comment]
>  Do we need to clear out all the data right after leaving a thread? What if we just left the report data and change only the thread joined state so we don't show an empty report and header? I’m just wondering if there’s a good reason we’re doing it this way now and if maybe there’s a smoother way to handle it. cc: @mountiny @shawnborton

Actually there is a new property since the last time I have looked into this we could use. There is a notificationPreferences hidden option which will hide it in LHN and we do not have to remove the data, I think we can use that now @ArekChr

**Comment by mountiny** [comment]
cc @srikarparsi will be best to answer, but I think we dont have to remove the data and just set this to notification preference hidden and we should avoid weird behaviour

**Comment by peterdbarkerUK** [comment]
Not overdue

**Comment by srikarparsi** [comment]
Hi! Yes, setting the notification preference of the thread to `hidden` optimistically should help avoid any unintended behavior like the thread showing up in the LHN or the leave button still showing up if the thread is re-accessed. I don't believe we need to clear the data. Does that answer your question?

**Comment by ArekChr** [comment]
@bernhardoj Could you point out where in the files your suggested code changes should go? I need to make sure we're looking at the right spots.

**Comment by mollfpr** [comment]
Tested on the @bernhardoj [proposal](https://github.com/Expensify/App/issues/28997#issuecomment-1802077161) is working well.


https://github.com/Expensify/App/assets/25520267/2aab57ec-a19d-40ca-a3ec-ede905be8714

I noticed from the action `Join thread` that we updated the notify preference to `always`. So it makes sense that we update the notify preference to `hidden` for `Leave thread`.

🎀 👀 🎀 C+ reviewed!

**Comment by mountiny** [comment]
@tienifr This makes snese to me however, could you make a Slack post describing these two options and we can discuss it there with more people

**Comment by mollfpr** [comment]
I'm still confused about the option between `Unsubscribe from thread` and `Leave thread` in our app. Both options do the same thing: not send the notification.

<details>
<summary>Unsubscribe from thread</summary>

![Screenshot 2023-11-13 at 23 41 17](https://github.com/Expensify/App/assets/25520267/0f0ef6dc-9f07-489a-b5fe-3e7c317e3c39)

</details>

- `Unsubscribe from thread` is calling API `UpdateReportNotificationPreference` and update the preference to `hidden`
- `Leave thread` is called API `LeaveRoom`. Open the report again will result in the report preference being `hidden`

Upon both actions, `Subscribe to thread` and `Join thread` calling API `UpdateReportNotificationPreference` and set the report preference to `always`.

Another issue with the `Leave thread` is that the subscribe actions from the context menu items aren't updated. After leaving the thread and navigating to the main report, the context menu and the items should show `Subscribe to thread`.

<details>

<summary>The context menu items on the report action not updating</summary>


<video src="https://github.com/Expensify/App/assets/25520267/c6d190f4-3782-4394-98a9-ffc14d86153f" />

</details>

---

I take other apps as an example.

On the Slack thread, there's no option to leave the thread.

<details>

<summary>Slack thread</summary>

![Screenshot 2023-11-13 at 23 46 32](https://github.com/Expensify/App/assets/25520267/a2c26465-7522-418e-a95c-3a393e18f3ba)

</details>

Discord does the option to `Leave thread` but doesn't remove the thread window.

<details>
<summary>Discord</summary>

<video src="https://github.com/Expensify/App/assets/25520267/589453fe-0ef9-433d-9f6a-c81ae2302564" />

</details>

**Comment by mountiny** [comment]
cc @srikarparsi you have the most context on these and background in the decisions which lead to this design

**Comment by peterdbarkerUK** [comment]
Last loose proposal is to:
- Have previously accessed threads in offline mode show skeletons, just like someone joining a new thread in offline mode
- When evicting data from onyx to prompt skeletons, retaining parent report information to keep the thread title.

**Comment by peterdbarkerUK** [comment]
@tienifr is going to throw a proposal up based on the slack discussion

**Comment by shawnborton** [comment]
Not overdue, still looking through proposals.

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/28997#issuecomment-1827800915) from @tienifr looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by peterdbarkerUK** [comment]
I'm OoO sick, will take care of payouts upon return (likely tomorrow). @ArekChr @mollfpr - could you check the [regression list? ](https://github.com/Expensify/App/issues/28997#issuecomment-1846340847)

**Comment by mollfpr** [comment]
@peterdbarkerUK I hope you feel better soon! I'll do the manual request in NewDot for payment.

---

> The PR that introduced the bug has been identified. Link to the PR:
> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the PR causing the bug, there's a lot of commit to track it down.

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
>If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open the App and open a chat
2. Start a thread and send some messages
3. Go offline
4. Click the three dots button on the thread header and select **Leave**
5. Open the thread from the main chat again
6. **_Verify_** skeleton shows in thread body, and title shows in the thread header

**Comment by peterdbarkerUK** [comment]
Thanks @mollfpr - $500 for the C+ Review, CC @anmurali while Mills is OoO. 

@tienifr please accept the [offer](https://www.upwork.com/nx/wm/offer/27059051) when you get a chance!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mollfpr based on comment above.

**Comment by peterdbarkerUK** [comment]
@tienifr I can action the final payout once you've accepted the offer!

**Comment by peterdbarkerUK** [comment]
No problem - [here it is!](https://www.upwork.com/nx/wm/offer/100226730)

**Comment by peterdbarkerUK** [comment]
@tienifr $500 paid, thanks!

**Comment by peterdbarkerUK** [comment]
Oop - will create the TR update in the morning

**Comment by peterdbarkerUK** [comment]
Done!
