### ISSUE TITLE
Web - Thread - User does not appear in the members list in thread after adding an emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: must be logged in with 2 accounts (user A and user B).

1. As user A, send a message to user B.
2. As user B, reply to that message in a thread.
3. As user A, open the thread chat, click on the 3 dots menu and select "Leave thread".
4. As user A, react with an emoji to any message.
5. Click on the header on chat.
6. Click on "Members"

## Expected Result:
User A should appears as a member in the thread.

## Actual Result:
ser A is not displayed as a member in the thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be6b50f2-34fc-460c-9b2f-a5303df8722c

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f3e9a552ab421ae</li>
        <li>Upwork Job ID: 1710271416732205056</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by kbecciv** [comment]
Created the issue by this request https://github.com/Expensify/Web-Expensify/pull/39071#issuecomment-1750393628

**Comment by cristipaval** [comment]
@maddylewis I made this internal, as I discussed this for a bit [here](https://github.com/Expensify/Web-Expensify/pull/39071#issuecomment-1750393628)

**Comment by cristipaval** [comment]
Didn't get the chance to work on this.

**Comment by cristipaval** [comment]
Making this weekly as it isn't affecting a common scenario.

**Comment by cristipaval** [comment]
I hope I can find the time to work on this one this week

**Comment by cristipaval** [comment]
Demoting since this is a corner case and I am currently working on some urgent issues that active users are facing in OldDot.

**Comment by cristipaval** [comment]
Haven't got the chance to work on this one yet.

**Comment by cristipaval** [comment]
no update

**Comment by maddylewis** [comment]
hiya - pete, i left BZ a couple of months ago, but was hanging onto this one incase there was any immediate action. since this is internal + an edge case, there hasn't been a ton of movement on the issue over the last several weeks. 

there's no immediate action on your end beyond monitoring the general progress of the internal issue.

**Comment by cristipaval** [comment]
was ooo last week, no update

**Comment by cristipaval** [comment]
I'll ask in #product channel if we want to get this one fixed.

**Comment by cristipaval** [comment]
Asked on Slack [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1706192953772349) and [here](https://expensify.slack.com/archives/C03U7DCU4/p1706192994225039) to see if we want to fix this.

**Comment by cristipaval** [comment]
Closing as per [this Slack convo](https://expensify.slack.com/archives/C066HJM2CAZ/p1706192953772349)
