### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Chat - On revisiting from room to chat, the cursor focus is lost in chat section.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28646
## Action Performed:
1. Launch app
2. Tap fab
3. Tap send message
4. Note the cursor focus is present in chat section
5. Tap Room and note the cursor focus is present
6. Again tap chat and note the cursor focus is lost
7. Tap Room and note the cursor focus is present
8. Tap chat and note the cursor focus

## Expected Result:
On revisiting chat section from chat to room and room to chat, the cursor focus must not be lost in chat section

## Actual Result:
On revisiting chat section from chat to room and room to chat, the cursor focus is lost in chat section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/04446ba8-3522-46e4-ae4a-53a841273328

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a29e7d185118a120</li>
        <li>Upwork Job ID: 1711319864114917376</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 27326383</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by laurenreidexpensify** [comment]
Not overdue Melv

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Chat - On revisiting from room to chat, the cursor focus is lost in chat section

### What is the root cause of that problem?

This is due to missing `useDelayedInputFocus(roomNameInputRef, 600);` in `NewChatPage.js`, which is present in `WorkspaceNewRoomPage.js`, which delays the focus to `600ms`.

### What changes do you think we should make in order to solve the problem?

Add `useDelayedInputFocus(optionSelectorRef, 600);` to the NewChatPage component so that it can refocus after 600 ms.

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment]
Result

https://github.com/Expensify/App/assets/58412969/75ce6e63-63fb-422d-be76-39d8e9b3eeb4

**Comment by laurenreidexpensify** [comment]
@allroundexperts bump ^^

**Comment by laurenreidexpensify** [comment]
@grgia bump for assignment ^^

**Comment by shubham1206agra** [comment]
This is still reproducible

**Comment by laurenreidexpensify** [comment]
@grgia pls assign thanks

**Comment by grgia** [comment]
All yours @shubham1206agra !

**Comment by laurenreidexpensify** [comment]
Payment Summary - 

1.  External issue reporter - Applause N/A 
2.  Contributor that fixed the issue - @shubham1206agra $500 + $250 - payment issued in Upwork
3.  Contributor+ that helped on the issue and/or PR - @allroundexperts $500 + $250 - please send a manual request in Newdot

**Comment by laurenreidexpensify** [comment]
waiting on @allroundexperts to complete check list and then we can close

**Comment by grgia** [comment]
bump on check list @allroundexperts

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/29001#issuecomment-1792284116).
