### ISSUE TITLE
[HOLD for payment 2023-11-06] Refactor EmojiPickerMenu component for web to avoid unnecessary rerenders

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29004]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1696602907705889)

### Proposal

Refactor EmojiPickerMenu component for web to avoid unnecessary rerenders

### Problem

Currently, the logic responsible for highlighting the emoji on hover is living in EmojiPickerMenu component, which contains a highlightedIndex state, keeping the index number of emoji that need to be highlighted. Since this index changes each time user hovers in/hovers out, it causes rerender of whole EmojiPickerMenu component (see video 1 - console is showing the amount of EmojiPickerMenu rerenders and the rendered components are highlighted in the browser).

### Solution

To address this issue, the logic for highlighting should be moved to EmojiPickerMenuItem component to rerender only the hovered component. This will prevent the whole EmojiPickerMenu from rerendering (see video 2 - console is showing the amount of EmojiPickerMenu rerenders and the rendered components are highlighted in the browser).
Also attaching screenshots from the profiler - you can see that originally the whole picker menu is  rerendering on each hover change, and after fixing it the only thing that gets rerendered is a single menu item.

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by TMisiukiewicz** [comment]
I’m Tomasz from Callstack, I’d like to work on this job

**Comment by TMisiukiewicz** [comment]
Hi, after further investigation I noticed that hovering is not the only way of highlighting an emoji - there is also a possibility of navigating through the list with tab & arrows. This makes the proposed solution incorrect, as `highlightedIndex` is primarily used for the keyboard navigation. While `EmojiPickerMenuItem` doesn't directly contain this state, its's behavior is closely tied with it. Introducing separate logic for highlighting items on hover would not be a good fit here, as it would break switching between mouse hover and using a keyboard navigation. In this case, looks like using a `highlightedIndex` state is reasonable and moving away from it would require a significant amount of effort and would likely complicate the component further.

Therefore, I wonder what the next steps should be?

**Comment by TMisiukiewicz** [comment]
@mountiny yeah, it's not very common but works that way now 🤷‍♂️  If there's no need of navigating from hovered emoji to it's closest elements by tab/arrows then it's doable. We can separate hover state as mentioned in the issue and then use `highlightedIndex` in the menu only to determine which element is currently focused. In that case we'll reduce rerenders of the menu when hovering, but keep in mind it will still happen when navigating with keyboard. I think if anyone use keyboard navigation after hover, we could just focus on the first item on the list. Let me know what you think

**Comment by mountiny** [comment]
Brought this up for discussion in slack btw

**Comment by TMisiukiewicz** [comment]
Coming back from Slack discussion, we decided that we can stop moving from hover to focus state on closest emoji when using keyboard. Working on creating a pull request.

**Comment by mountiny** [comment]
@TMisiukiewicz interesting, I would say we want to keep this but not if it will cost us some performance slow down

Can you handle this case please? I would consider this as a regression as we did not realize this feature was removed

**Comment by mountiny** [comment]
I think we need to pay $500 to @akinwale for the first PR testing and review and $500 to @ntdiary for the second one cc @muttmuure

**Comment by mountiny** [comment]
I think the payments would be $500 to @ntdiary and $500 to @akinwale, is that correct?

**Comment by mountiny** [comment]
Or the second was a regression from the first one essentially so I guess $250 for @akinwale?

**Comment by akinwale** [comment]
@muttmuure bump for payment. Thanks.

**Comment by muttmuure** [comment]
$500 - @ntdiary 
$250 - @akinwale 

Invited in Upwork: https://www.upwork.com/en-gb/ab/applicants/1727390644937363456/hires?filter=wentao&page=1

**Comment by muttmuure** [comment]
Contract extended

**Comment by mountiny** [comment]
Has this been paid out? @muttmuure @ntdiary ?

**Comment by muttmuure** [comment]
Paid

**Comment by mountiny** [comment]
@ntdiary @akinwale is this all sorted then?

**Comment by akinwale** [comment]
> @ntdiary @akinwale is this all sorted then?

Yes. I have also received payment, thanks.
