### ISSUE TITLE
Android - Distance - Error shows up when location access is limited to approximate location

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26546

## Action Performed:
 1. Launch New Expensify app
2. Go to + > Request money > Distance > Start
3. Tap Use current location
4. Select 'Approximate location' and 'While using the app'
5. If there is no error, go to Finish point > Use current location
6. Select 'Keep approximate location'

## Expected Result:
App should be still able to detect the location because the location access is still given

## Actual Result:
App is unable to detect user location. An error shows up
Error message - We were unable to find your location, please try again or enter an address manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/07da9388-91e9-48f4-8f39-43d38c4fdba6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I agree this is not a blocker and maybe not an issue that we can solve on our end.

**Comment by hayata-suenaga** [comment]
I agree with @huzaifa-99 that this is not an issue. I'll wait for @neil-marcellini 's confirmation before closing the isuse.

**Comment by jasperhuangg** [comment]
Agree that this shouldn't be a blocker, I don't think there's anything we can do.

Maybe we can update the error message to specify that if you're on Android you should allow precise location tracking.
