### ISSUE TITLE
Split bill - Red dot appears in the split bill from "Teachers Unite!" workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27952
## Action Performed:
1. Go to https://staging.new.expensify.com/teachersunite
2. Select I am a teacher and submit the form
3. Go to "Teachers Unite!" workspace
4. Create a split bill
5. Log in to ND using the principal account that is entered in the form in Step 2
6. Open the split bill

## Expected Result:
here is no red dot in the IOU

## Actual Result:
The split bill IOU appears with a red dot, and there is no error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d9d43985-b742-47c4-9f3b-e0fd87e1ab43

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
Seems a BE issue as it responds with "Report no longer exists"

**Comment by dylanexpensify** [comment]
@RachCHopkins @youssef-lr @marcochavezf assigning you since it's a TU issue!

**Comment by RachCHopkins** [comment]
@dylanexpensify I'm not part of the BugZero team. What is it you want me to do here?

**Comment by youssef-lr** [comment]
Investigating this one today.

**Comment by youssef-lr** [comment]
We confirmed this is working now.
