### ISSUE TITLE
[$500] Wallet - "Transfer balance" button not available

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28744
## Action Performed:
1. Log into Expensify and open any workspace chat where the user is the only member.
2. Click on "+" in the compose box and request money of any amount
3. On IOU preview, tap pay and verify popover appears
4. Enter IOU and click on caret (dropdown icon) and the main button and verify popover appears
5. Go to setting and Select Wallet

## Expected Result:
User should see "Transfer balance" button under monetary value

## Actual Result:
There is no "Transfer Balance" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/20ed4707-826e-438b-8266-3f051db4dca7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013aa8e6061ac6b8cb</li>
        <li>Upwork Job ID: 1711259593886728192</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Not overdue.
