### ISSUE TITLE
IOU - Selecting 8 maximum participants, if search a contact and tap enter, inconsistent behavior

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money -- manual
4. Enter an amount and tap Next
5. Select 8 maximum participants
6. Search for an user and tap enter in keypad and note the behaviour
7. Launch app
8. Repeat step 2- step 6

## Expected Result:
After selecting 8 maximum participants, if we search for a contact and tap enter, the search in split bill must behave in a same consistent manner in both mweb and android

## Actual Result:
After selecting 8 maximum participants, if we search for a contact and tap enter, the search in split bill behaves inconsistent in mweb and android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e39f9e80-8045-4ef7-811b-6e42c0a42acd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment]
I think we can close this one out since we're not focusing on extreme polish issues - seems like a flow that a normal user is unlikely to take. Let me know if you disagree.

**Comment by mountiny** [comment]
I think the keyboard issues are still minor so we are not focusing on these, thanks for a proposal, but we gotta focus on other issues now
