### ISSUE TITLE
Workspace - Different skeleton is displayed at the bottom of the archived workspace room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27420
## Action Performed:
Precondition: There is an archived room with long chat
1. Go to staging.new.expensify.com
2. Go to Search
3. Open the archived chat

## Expected Result:
The skeleton at the bottom is displayed correctly

## Actual Result:
The skeleton at the bottom is displayed differently than the one in PR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1011" alt="Bug6227998_1696620058295!PR" src="https://github.com/Expensify/App/assets/78819774/1c02aa12-8868-42ab-a15b-0853429ce215">

<img width="1011" alt="Bug6227998_1696620058284!staging" src="https://github.com/Expensify/App/assets/78819774/61a57328-9567-433e-9f0b-1c36341d6a41">

https://github.com/Expensify/App/assets/78819774/a0a57319-b7c1-4c5a-9313-f2d0a543f01b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I'm not familiar with the above linked PR, but unless there is a specific reason the skeleton UI needs to look like the top screenshot, this doesn't really feel like a bug to me. The skeleton UI we are showing on the archived room seems to match the UI element that eventually loads that says the room is archived. 

Personally, this feels like a :do-nothing: situation to me, but I defer to Robert.

**Comment by robertjchen** [comment]
I agree, from the discussion in the PR it seems like this was what we're expecting.
