### ISSUE TITLE
 Avatar - Inconsistent default profile Avatar in Settings page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29034]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in [applausetester+0514gm@applause.expensifail.com](mailto:applausetester+0514gm@applause.expensifail.com)
2. Go to Avatar>Settings page

## Expected Result:
Avatar image should be the same as on main page

## Actual Result:
Default profile Avatar is inconsistent in different pages.
When user navigates to Settings page - avatar logo lost original background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/37569c07-5f61-4bf4-a8b9-0df2cc73c43c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Cannot reproduce
