### ISSUE TITLE
[Pay meow] Display all SVG images on UI thread using native libraries

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#29067]
## Problem

We’re rendering SVGs using react-native-svg library which is not intended for displaying static images from web or assets. It affects our performance hugely, as rendering big SVGs might take a long time - for BackkgroundImage on Android debug build I’ve seen times like 380ms on pretty powerful Pixel 7

## Solution

We should display all SVG images on UI thread using native libraries.

Currently, we have react-native-fast-image in place for displaying PNGs. Unfortunately it does not support SVGs. 

We could either migrate to another image library (like expo-image) or add SVG support for react-native-fast-image

For the sake of benchmarking, adding basic support for SVGs in react-native-fast-image on android and comparing its performance to react-native-svg shows HUGE results!

For smaller SVGs, namely for Icons on Settings page (which are mostly one path) it also reduces render time hugely, but since base time is small (2-4 ms) it’s not that huge of a deal.

**Comment by muttmuure** [comment]
https://github.com/Expensify/App/pull/30905

**Comment by puneetlath** [comment]
@muttmuure FYI I'm assigning @akinwale to this issue since he got assigned as C+ on the PR

**Comment by mallenexpensify** [comment]
@muttmuure sorry for confusion, was going to have you do BZ on this but I'm going to do cuz I'm doing some testing. 
@akinwale I just sent you an offer but.. I can't access a link to share, please share one if you find one, and let me know when you've accepted the offer. Thx

**Comment by akinwale** [comment]
> @akinwale does this link work for you? https://www.upwork.com/nx/wm/workroom/35923673/overview

Yes, I am able to access it without issues.

**Comment by akinwale** [comment]
@akinwale I just sent you an offer but.. I can't access a link to share, please share one if you find one, and let me know when you've accepted the offer. Thx

@mallenexpensify I have also accepted the offer.

**Comment by mallenexpensify** [comment]
Contributor+: @akinwale paid $500 via Upwork. 

I think that's the only payment do, so I'm closing. 
Thx!
