### ISSUE TITLE
[$500] Dev: LHN - Border color around profile pic is different in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group
2. Click on the group and verify border color around profile pic in LHN

## Expected Result:
Border color is different

## Actual Result:
Border color should not be different

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (9)](https://github.com/Expensify/App/assets/93399543/4581cbd4-42e3-446f-9573-12ce08aba27e)
![image (8)](https://github.com/Expensify/App/assets/93399543/87543428-28e3-4528-b829-90c19aea7c72)
![image (7)](https://github.com/Expensify/App/assets/93399543/054f5703-ad51-4ee2-9345-2b9c82b22f89)

https://github.com/Expensify/App/assets/93399543/4c3af68e-4ab4-4265-a32e-512f893d021c

https://github.com/Expensify/App/assets/93399543/7e9f48a9-b6d9-4c55-b80d-c20cf70084e5

https://github.com/Expensify/App/assets/93399543/b2939d78-8364-4705-b586-d2f599f6c95d

https://github.com/Expensify/App/assets/93399543/f865d4af-06d1-47c4-bae6-bd8c37006a03

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696655745191809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01092e70102b992daf</li>
        <li>Upwork Job ID: 1711339977280749568</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment]
@saranshbalyan-1234's proposals LGTM!
C+ Reviewed
🎀 👀 🎀

**Comment by grgia** [comment]
@Santhosh-Sellavel this seems like a recent regression, have we determined if a recent PR caused this and the author should fix it?

**Comment by hayata-suenaga** [comment]
I feel like I remember we talked about this as a regression. Checking in the consolidated issue

**Comment by hayata-suenaga** [comment]
@Santhosh-Sellavel please check the linked consolidated issue and let the Bug Zero team know if we should close this issue

**Comment by Santhosh-Sellavel** [comment]
I guess we can close this one,  as it is being handled as part of #29057

**Comment by hayata-suenaga** [comment]
sorry I thought I was assigned to this issue 😓 @grgia please open the issue if you feel like it needs some more work
