### ISSUE TITLE
[$500] Dev:  Settings Background for profile details Header is changed unintentionally while refactoring LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Pull latest changes from main
2. Open App, navigate to settings.

## Expected Result:
Settings Background for profile details Header is not same as production and staging.

## Actual Result:
 Settings Background for profile details Header is same as production and staging.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:**  n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_1696710096](https://github.com/Expensify/App/assets/93399543/a9b01802-c176-41c2-a4f7-382c8f693387)
![Screenshot_2023-10-08-01-41-52-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Expensify/App/assets/93399543/32a21ff3-33c5-41da-9e0e-efb82f606b4d)
![Screenshot 2023-10-07 at 2 01 34 PM](https://github.com/Expensify/App/assets/93399543/61c9c3a8-b3fc-4e73-bde0-5566db0f53ab)
![192 168 0 1038082settings](https://github.com/Expensify/App/assets/93399543/34c7a9c2-f6a0-42ce-8894-3b3fed1fa73b)
![(1) New Expensify (1)](https://github.com/Expensify/App/assets/93399543/fd00eb28-ad9b-48b7-82a2-588e5bd8d165)
![Screenshot 2023-10-07 at 1 42 41 PM](https://github.com/Expensify/App/assets/93399543/30bf4e08-2646-474f-aaa0-d36ef9e67f13)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696666339849009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190dc27ba467ee399</li>
        <li>Upwork Job ID: 1711358815262965760</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Problem
Settings Background for profile details Header is changed unintentionally while refactoring LHN
### Root Cause
We were referencing sidebar color for the background color which was darkHighlightBackground but recently this hs been changed while refactoring New LHN layout.
### Changes
We should use highlightBG instead of sidebar color to avoid this issue in future, we should fix this for all other places where ever we reference sidebar color directly

**Comment by hayata-suenaga** [comment]
This issue is consolidated [here](https://github.com/Expensify/App/issues/29057) 🙇 

Thank you everyone for proposals and I really appreciate the time you took to write these. I'm looking forward to working with you in the next issue 🚀
