### ISSUE TITLE
[$500] Hmm.. it's not here page is displayed when opening a 'share code' link for public account only

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user A and user B should have no prior chat history **(only public accounts)**
1. Open a tab where user A is signed in
2. Click on 'Profile avatar' > Share code > Copy URL to clipboard
3. Open a tab where user B is signed in
4. Paste the URL to the address bar
5. Press enter

## Expected Result:
User A's profile should be opened

## Actual Result:
Hmm.. it's not here page is displayed when opening a 'share code' link for public account only

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9dc0cdbd-b5e6-44dd-84a2-1bb07648c67b

https://github.com/Expensify/App/assets/93399543/9d5cbece-3d67-4d8b-bdaa-d162e089c421

https://github.com/Expensify/App/assets/93399543/32593f49-06a3-460f-a7ea-1720459f671c

https://github.com/Expensify/App/assets/93399543/f9c284f3-9a42-4f1e-95aa-0421c3ffa2eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696831942996729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8af5839a345db28</li>
        <li>Upwork Job ID: 1711873748178976768</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment]
Clarified [here](https://expensify.slack.com/archives/C07J32337/p1696884510482699) that the expected behavior is that "Hidden" should show:

<img width="382" alt="Screenshot 2023-10-09 at 1 57 33 PM" src="https://github.com/Expensify/App/assets/31285285/311e9e7f-65a4-4cc0-8c8b-7397727e64aa">

**Comment by jasperhuangg** [comment]
Going to revert https://github.com/Expensify/App/pull/28812 which caused this regression

**Comment by Natnael-Guchima** [comment]
@jasperhuangg I wasn't paid for reporting bonus. Can you please open this issue to handle reporting bonus?

**Comment by mountiny** [comment]
Reopening to pay $50 to @Natnael-Guchima for reporting cc @mallenexpensify

**Comment by mallenexpensify** [comment]
@Natnael-Guchima can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01e8af5839a345db28

Sorry we missed it

**Comment by Natnael-Guchima** [comment]
@mallenexpensify I haven't received an offer. Can you please send me an offer? Thanks. 

And no worries 🙏

A link to my profile, if need: https://www.upwork.com/freelancers/nathnaelg?s=1313512633755545600

**Comment by mallenexpensify** [comment]
@Natnael-Guchima can you please accept the updated job and reply here once you have? 
https://www.upwork.com/jobs/~01e8af5839a345db28

**Comment by Natnael-Guchima** [comment]
I have accepted the offer. Thanks @mallenexpensify

**Comment by mallenexpensify** [comment]
Issue reporter: @Natnael-Guchima paid $50 via Upwork
 
@jasperhuangg, should we look into @ginsuma 's comment above about the app crashing with unknown profile URL? Should that be a separate bug report? Thx

**Comment by jasperhuangg** [comment]
Are we all sorted here to close this out? @mallenexpensify

**Comment by mallenexpensify** [comment]
I think so @jasperhuangg
