### ISSUE TITLE
[$500] Chat - User is able to chat with secondary contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29091]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: another user should already have added the contact used in below steps in contact methods but it shouldn't be verified
1. Open the app
2. Open search
3. Search for contact method which is already added by another user but it is still not verified
4. Select the result and send few messages
5. Open settings->profile->contact methods->Add
6. Add contact method used in step 3
7. Verify the contact method
8. Close RHN, observe that app still shows the chat with contact method which is now added as secondary contact
9. Send few messages and observe that app allows to send messages without triggering error

## Expected Result:
App should remove the chat with that contact from reports once we add that contact in contact methods

## Actual Result:
App does not remove the chat with that contact from reports even after we add that contact in contact methods and app also allows user to send more messages without error

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e36065cc-0994-4360-8c63-7a55e68ee5a7

https://github.com/Expensify/App/assets/93399543/f12e2647-2128-424a-85d9-c081e954f406

https://github.com/Expensify/App/assets/93399543/9826a06e-49bf-4667-b076-b4b64fa96898

https://github.com/Expensify/App/assets/93399543/5560f104-ee2e-4dd1-8bf2-43c9caa45fd2

https://github.com/Expensify/App/assets/93399543/5f20ca1d-820f-4877-bee4-c3f6e9b0cb8e

https://github.com/Expensify/App/assets/93399543/06f2a89b-e7c7-4807-8541-293946b369ee

https://github.com/Expensify/App/assets/93399543/7237a215-6047-41b2-8a6b-3c59d5f8a9e4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696678653235509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01336072c3cf146b82</li>
        <li>Upwork Job ID: 1711382718830731264</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by miljakljajic** [comment]
This isn't a bug - it's a flow that a real user wouldn't ever take, and even if they do, its expected that they'd be able to chat this way. Closing this one out.
