### ISSUE TITLE
[LOW] Distance: PHASE 2 CLEANUP - Refactor navigation among screens related to money request features

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29107]
- [ ] Held on https://github.com/Expensify/App/issues/26538

In https://github.com/Expensify/App/issues/26538 Most of the changes were made by adding new components. This eliminated a lot of conflicting headaches from people working on existing components.

Phase 2 is all about removing the original components and any of the duplicated efforts. The tasks that need to be done as part of this issue are:

- [x] Remove `iou/ReceiptSelector` and copy [any changes since Nov 27](https://github.com/Expensify/App/commits/main/src/pages/iou/ReceiptSelector) into `IOURequestStepScan/`
- [x] Remove `WaypointEditor.js` and copy [any changes since Nov 27](https://github.com/Expensify/App/commits/main/src/pages/iou/WaypointEditor.js) into `IOURequestStepWaypoint.js`
- [x] #34606
- [x] #34607
- [x] #34608
- [x] #34609
- [x] #34610
- [x] #34611
- [x] #34612
- [x] #34613
- [x] #34614
- [x] #34615
- [x] #34616
- [x] #34617
- [x] #39559
- [ ] HOLD Edit `ROUTES.ts` and remove `MONEY_REQUEST_*` routes, remove "create" from the front of the routes
- [ ] HOLD Edit `linkgingConfig.js` and remove `Money_Request*` screens
- [ ] HOLD Edit `ModalStackNavigators.js` remove old `Money_Request*` components
- [ ] HOLD Edit `IOU.js` and remove `_temporaryForRefactor` from the name of any methods
- [ ] HOLD Edit `IOU.js` and remove `startMoneyRequest()` method and rename `startMoneeRequest()` to `startMoneyRequest()`
- [ ] HOLD Edit `IOU.js` and remove `createDistanceRequest()` method and use `requestMoneyFromDistance()` everywhere
- [ ] HOLD Remove `ONYXKEYS.IOU`
- [ ] HOLD Remove `EditRequestPage`
- [ ] HOLD Remove `EditSplitBillPage`

```
git diff "tgolen-refactor-request-navigation2@{2023-11-15}..main" src/pages/iou/IOUCurrencySelection.js
```

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b453df445e7dd962</li>
        <li>Upwork Job ID: 1711432700883152896</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by tgolen** [comment]
I've been working on cleaning up the receipt selector this week

**Comment by tgolen** [comment]
I'm working on the second item. Once I have that finished and have two solid examples, I will create issues for all the remaining items and send them out to contributors to help finish the work.

**Comment by tgolen** [comment]
Today I created a bunch of issues to get the first batch of issues completed. The rest of the items in this list can only be done once all of these components are cleaned up.

**Comment by DylanDylann** [comment]
@tgolen 
Coming from: https://github.com/Expensify/App/pull/35137#discussion_r1475730296
Currently, we still use `MoneyRequestConfirmationList` in `SplitBillDetailsPage`. Do we have a plan to remove `MoneyRequestConfirmationList`  and use `MoneyTemporaryForRefactorRequestConfirmationList` instead?

**Comment by tgolen** [comment]
Yeah, we do. It's one of the checklist items in the issue description. I didn't create an issue for it yet because I was waiting for all the previous components to be finished first (which will help make the cleanup process easier).

**Comment by fabioh8010** [comment]
Hey @tgolen 👋 I was passing through the remaining JS files and I noticed these ones and this related issue, could you confirm which ones we can migrate?

<img width="270" alt="Screenshot 2024-03-18 at 22 08 18" src="https://github.com/Expensify/App/assets/20051562/ffc5a353-82b5-4f40-94eb-4025664ecc68">

**Comment by DylanDylann** [comment]
These pages will be removed soon

**Comment by fabioh8010** [comment]
@tgolen @DylanDylann I found these JS files too, can we migrate them?

- src/pages/iou/request/IOURequestStartPage.js
- src/pages/iou/request/IOURequestRedirectToStartPage.js
- src/pages/iou/request/step/StepScreenWrapper.js
- src/pages/iou/request/step/StepScreenDragAndDropWrapper.js
- src/pages/iou/request/step/IOURequestStepTaxRatePage.js
- src/pages/iou/request/step/IOURequestStepTaxAmountPage.js
- src/pages/iou/request/step/IOURequestStepTag.js
- src/pages/iou/request/step/IOURequestStepParticipants.js
- src/pages/iou/request/step/IOURequestStepMerchant.js
- src/pages/iou/request/step/IOURequestStepDistance.js
- src/pages/iou/request/step/IOURequestStepDescription.js
- src/pages/iou/request/step/IOURequestStepDate.js
- src/pages/iou/request/step/IOURequestStepCurrency.js
- src/pages/iou/request/step/IOURequestStepConfirmation.js
- src/pages/iou/request/step/IOURequestStepCategory.js
- src/pages/iou/request/step/IOURequestStepAmount.js

**Comment by DylanDylann** [comment]
IMO we should migrate all these files (there are no deprecated files in your list)

cc @tgolen

**Comment by fabioh8010** [comment]
Me again 👋 Just to confirm, these ones will be removed too, right?

- src/pages/iou/MoneyRequestMerchantPage.js
- src/pages/iou/steps/MoneyRequestConfirmPage.js
- src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js
- src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js
- src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js

**Comment by DylanDylann** [comment]
@fabioh8010 These page will be removed soon. Let's ignore it

Cc @tgolen

**Comment by tgolen** [comment]
# Weekly Update
- Looks like things are still in progress
- Half of the remaining issues are on HOLD for previous issues

### Next Steps
- Continue working through these to get things unheld and cleaned up

#### ETA
- All done by May 1

**Comment by DylanDylann** [comment]
@tgolen This is an update on the current 


Reviewing PR
+ [Remove IOUCurrencySelection.js and copy any changes since Nov 27 into IOURequestStepCurrency.js](https://github.com/Expensify/App/issues/34607)
+ [Remove MoneyRequestParticipantsPage.js and copy any changes since Nov 27 into IOURequestStepParticipants.js](https://github.com/Expensify/App/issues/34616)

On Hold 
+ [Remove MoneyRequestParticipantsSelector.js and copy any changes since Nov 27 into MoneyTemporaryForRefactorRequestParticipantsSelector](https://github.com/Expensify/App/issues/34617)


To speed up, I suggest we can handle [Remove MoneyRequestParticipantsSelector.js and copy any changes since Nov 27 into MoneyTemporaryForRefactorRequestParticipantsSelector](https://github.com/Expensify/App/issues/34617) in [Remove MoneyRequestParticipantsPage.js and copy any changes since Nov 27 into IOURequestStepParticipants.js](https://github.com/Expensify/App/issues/34616)

And we could open **a new issue** for this one: Remove MoneyRequestConfirmationList.js and copy [any changes since Nov 27](https://github.com/Expensify/App/commits/main/src/components/MoneyRequestConfirmationList.js) into MoneeRequestConfirmationList.js


After the above is done, we can create an issue to clean up the rest.

**Comment by DylanDylann** [comment]
@tgolen I think we can process this one

> Maybe create the issue for MoneyRequestConfirmationList.js

**Comment by tgolen** [comment]
Great! I created it and linked it.

**Comment by DylanDylann** [comment]
As I understand, in https://github.com/Expensify/App/issues/39559 we need to remove MoneyRequestConfirmationList.js and copy any changes since Nov 27 into MoneyTemporaryForRefactorRequestConfirmationList.js

**Comment by tgolen** [comment]
Oh, man, I think I made a mistake in writing up that issue :D Thanks for pointing it out. 

@DylanDylann is correct. I'll update the issue

**Comment by tgolen** [comment]
# Weekly Update
- All component issues have been created and assigned and are being worked on

### Next Steps
- Once all PRs are merged, @tgolen take a look around the remaining libs to see what remaining code is left to clean up

#### ETA
- Still on track to be done by May 1

**Comment by DylanDylann** [comment]
@tgolen There is only [this issue](https://github.com/Expensify/App/issues/34617) in the process (This is not a page, the change is minor), other issues were done. Currently, we can continue the next step to clean up the rest. If possible, I am happy to take over the clean-up task as contributor or contributor plus role

**Comment by brunovjk** [comment]
I would love to help as well

**Comment by DylanDylann** [comment]
-     Edit ROUTES.ts and remove MONEY_REQUEST_* routes, remove "create" from the front of the routes

-     Edit linkgingConfig.js and remove Money_Request* screens

-     Edit ModalStackNavigators.js remove old Money_Request* components

For these above checklists, we only need to remove MONEY_REQUEST_MERCHANT route (There are no pages relate this route) and remove `EditRequestReceiptPage` component and related route



-     Edit IOU.js and remove _temporaryForRefactor from the name of any methods

-     Edit IOU.js and remove startMoneyRequest() method and rename startMoneeRequest() to startMoneyRequest() 
 
(@tgolen could you help to explain this point? if we remove startMoneyRequest which method should be used instead?)

-     Edit IOU.js and remove createDistanceRequest() method and use requestMoneyFromDistance() everywhere  
(@tgolen in this point you mean that we need to rename `createDistanceRequest` to `requestMoneyFromDistance`, right?)


-     Remove ONYXKEYS.IOU (also need to remove some files that relate to IOU like src/pages/iou/propTypes/index.js)
 
-     Remove EditRequestPage (done in somewhere)
 
-     Remove EditSplitBillPage (also should remove EditRequestTagPage)

- I suggest we also should move src/pages/iou/steps/MoneyRequestAmountForm.tsx to src/pages/iou/

- We also need to remove `MoneyRequestWaypointPage`

**Comment by tgolen** [comment]
> Edit IOU.js and remove startMoneyRequest() method and rename startMoneeRequest() to startMoneyRequest()

This point is out of date and it can be ignored for now. It looks like the code only has a single `startMoneyRequest()` method and everything is using that so it should be all good. 

>  in this point you mean that we need to rename createDistanceRequest to requestMoneyFromDistance, right?

Hm, I'm not sure what happened here. It looks like `requestMoneyFromDistance` has been removed. As long as there is only a single method for creating distance requests, that's what really matters. It looks like that's the case, so I think this is all good as well.

The rest of the list looks good. Though, I think I noticed one other thing:

- MoneyTemporaryForRefactorRequestParticipantsSelector.js should be renamed (probably to `IOURequestParticipantsSelector.js`. It's also strange that it hasn't been migrated to TS yet.

**Comment by DylanDylann** [comment]
@tgolen [Updated summary](https://github.com/Expensify/App/issues/29107#issuecomment-2071732320) to cover your additional point

> Rename MoneyTemporaryForRefactorRequestParticipantsSelector.js to MoneyRequestParticipantsSelector

**Comment by DylanDylann** [comment]
@fabioh8010 Sorry about my mistake [here](https://github.com/Expensify/App/issues/29107#issuecomment-2015052392). Could you handle this point



> MoneyTemporaryForRefactorRequestParticipantsSelector.js should be renamed (probably to IOURequestParticipantsSelector.js. It's also strange that it hasn't been migrated to TS yet.

**Comment by DylanDylann** [comment]
@tgolen How I can process this issue now?

**Comment by tgolen** [comment]
You mentioned dividing it into two issues. How were you thinking of splitting them up? 

It would also really help me if you could just give me the markdown that I can copy/paste into this issue description to fix the checklist. Otherwise, I have to spend a bunch of time trying to parse each of your points above 😅

**Comment by DylanDylann** [comment]
1. **The first issue:** Rename MoneyTemporaryForRefactorRequestParticipantsSelector.js to MoneyRequestParticipantsSelector.tsx and migrate to TS
This should be handled by the TS team cc @fabioh8010 
2. **The second issue**: Clean up request flow (It is so straightforward so let's do it in one)

This is the issue description
```
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

Currently, we migrated the request flow to the new refactor and there are some deprecated things that need to clean up

- Edit ROUTES.ts and remove MONEY_REQUEST_* routes, remove "create" from the front of the routes

- Edit linkgingConfig.js and remove Money_Request* screens

- Edit ModalStackNavigators.js remove old Money_Request* components

Note: For three first checklists, we only need to remove MONEY_REQUEST_MERCHANT route (There are no pages relate this route) and remove `EditRequestReceiptPage` component and related route

- Edit IOU.js and remove _temporaryForRefactor from the name of any methods

- Remove ONYXKEYS.IOU (also need to remove some files that relate to IOU like src/pages/iou/propTypes/index.js)
 
- Remove EditSplitBillPage (also should remove EditRequestTagPage)

- I suggest we also should move src/pages/iou/steps/MoneyRequestAmountForm.tsx to src/pages/iou/

- We also need to remove `MoneyRequestWaypointPage`

```

**Comment by fabioh8010** [comment]
@DylanDylann I will pass this info to the TS team and someone will be assigned to migrate this file soon! Will keep you updated here

**Comment by tgolen** [comment]
Thanks, @DylanDylann. I've created the issue and made just a couple of minor changes to clarify what needed to happen with the routes.

**Comment by pasyukevich** [comment]
Hi,
I'm Eugene from Callstack 

I will migrate it

> Rename MoneyTemporaryForRefactorRequestParticipantsSelector.js to MoneyRequestParticipantsSelector.tsx and migrate to TS

**Comment by s77rt** [comment]
Sorry about that. The PR approval automation didn't work as expected

**Comment by amyevans** [comment]
@s77rt so @francoisl, @chiragsalian, and I should unassign? Just want to double check since I'm unclear where the trigger even came from 😅

**Comment by s77rt** [comment]
@chiragsalian should stay assigned. You and @francoisl can unassign

PS: The trigger came from PR approval

**Comment by DylanDylann** [comment]
# Weekly Update

Everything in this [checklist](https://github.com/Expensify/App/issues/29107#issue-1933500934) is done. We are waiting for https://github.com/Expensify/App/pull/41216 to be merged to close this issue. The reason why we need to wait for #41216 to be merged is that besides migrating to typescript we also changed the name of the file, which is part of this issue

**Comment by tgolen** [comment]
I was able to merge that PR this morning, so I will go ahead and close this issue out. Thanks for all the help with this!!
