### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] No margin top on zip code input

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696629077014029

## Action Performed:
1. Open settings > workspaces > select any workspace > bank account > connect manually
2. Complete step 1
3. Observe there is space above every input but not on zip code input
## Expected Result:
There should be margin top on zip code input like all other inputs.
## Actual Result:
There is no margin top on zip code input.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/68544cbe-b35d-4143-84e2-befbe4ec4670

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/975e1442-13a6-477c-9a7c-1478c1ad47b4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/a73dc504-dc23-4a9f-a8e8-47924dfd20c1

![Full Screen #1](https://github.com/Expensify/App/assets/38435837/49b6fb27-2236-4c1d-b26c-43ed66b3938a)

</details>

<details>
<summary>MacOS: Desktop</summary>

![zip_code_margin](https://github.com/Expensify/App/assets/38435837/b9b21f3a-f9eb-477b-bfcc-26047c360876)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170820d98137d62bd</li>
        <li>Upwork Job ID: 1711538110955954176</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27165311</li>
<li>Krishna2323 | Contributor | 27165313</li>
<li>Krishna2323 | Reporter | 27165317</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by s77rt** [comment]
I'm not sure whether this is a bug or intended. Asked in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1696967863302429

**Comment by MitchExpensify** [comment]
Holding on an internal discussion

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal! Your RCA is correct and the solution has been agreed on by design team. Let's get this fixed!

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29137#issuecomment-1754122188)

**Comment by s77rt** [comment]
@PiyushChandra17 Thanks for the proposal. Unfortunately it's a dupe.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/21049
- The offending PR has been commented on: https://github.com/Expensify/App/pull/21049#discussion_r1361377789
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by MitchExpensify** [comment]
**Payment summary:**

$50 - @Krishna2323 requires payment [offer](https://www.upwork.com/nx/wm/offer/27165313) (Reporter)
$750 - @Krishna2323 requires payment [offer](https://www.upwork.com/nx/wm/offer/27165313) (Contributor)
$750 - @s77rt  requires payment [offer](https://www.upwork.com/nx/wm/offer/27165313) (Contributor Plus)

Does this look correct to you all?

**Comment by s77rt** [comment]
@MitchExpensify I think the price for this one should be lowered since it was just a style adjustment. https://expensify.slack.com/archives/C01GTK53T8Q/p1696968320902849?thread_ts=1696967863.302429&cid=C01GTK53T8Q

**Comment by MitchExpensify** [comment]
Thanks, lowering to $325 which is $250 + 50% speed bonus

**Comment by MitchExpensify** [comment]
Oh lol, my mistake @Krishna2323

**Comment by amyevans** [comment]
Friendly bump @MitchExpensify for payment

**Comment by MitchExpensify** [comment]
Paid, sorry for the delay! 🙇
