### ISSUE TITLE
[$500] Mark as unread not work with room has been archived when mark on LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696845673468749

## Action Performed:
1. Create a WS
2. Go to #admin room
3. Send the message
4. Delete WS
5. On LNH, right click #admin room  and select Mark as unread, Observe that the new line indicator does not appear
## Expected Result:
new line indicator appear when mark as unread on LHN archived room
## Actual Result:
new line indicator does not appear when mark as unread on LHN archived room
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/47724898-77b5-4c4f-948e-8c224e1a6d28

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

https://github.com/Expensify/App/assets/38435837/bb8e6afc-f6fa-4715-b87a-455313c6bc34

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/e426f806-db3f-4375-946e-426c75c138ee

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/9988c235-11b1-4b62-9aef-e498b0f21942

https://github.com/Expensify/App/assets/38435837/ab4c39c0-462e-470e-a819-cccd8ea92bd5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/627dba48-8900-4941-a3ac-5d28614d7ecf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013eaec01ff14d6fcc</li>
        <li>Upwork Job ID: 1711543430491975680</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
Mark as unread not work with room has been archived when mark on LHN
### What is the root cause of that problem?
When we click mark as unread on LHN it will trigger `markCommentAsUnread` function:
https://github.com/Expensify/App/blob/619aee628a82adb85327dfb95f5f1280c6970a95/src/libs/actions/Report.js#L846-L848
In this case the param `reportActionCreated =  null`.
If no reportActionCreated is provided, use the last action's, but currently, logic we get `lastVisibleActionCreated` in the report.  But it's not really true for the archived report. Because `lastVisibleActionCreated` then receives the value when the report is archived. We have a report action when the room is archived.
### What changes do you think we should make in order to solve the problem?
We should update the logic to get the last visible action:
```js
const lastVisibleAction = ReportActionsUtils.getLastVisibleAction(reportID);
const actionCreationTime = reportActionCreated || lodashGet(lastVisibleAction, 'created', DateUtils.getDBTime(new Date(0)));
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sobitneupane** [comment]
I don't believe many users would find the 'Mark as unread' feature useful for archived reports. My suggestion is to consider removing the 'Mark as unread' option for archived reports. What do you think, @laurenreidexpensify ?

**Comment by laurenreidexpensify** [comment]
@trjExpensify can I get a buddy check on this [one](https://github.com/Expensify/App/issues/29138#issuecomment-1757449140)? Thanks

**Comment by trjExpensify** [comment]
Yeah, I don't think adding extra logic for this is worth it at all. I'm fine with leaving the menu item on the chat row of an archived room in the interest of "do nothing" and simply closing this issue. I have never once felt compelled to mark an archived chat as unread, so I suspect the reality is nobody else will either. 

If we really feel compelled to do something here, I would vote to remove the `Mark as unread` menu item from archived rooms row in the LHN, but that would mean removing the button from the comment action menu on each message within the archived room as well for completeness and consistency.

Let's move on, IMO!

**Comment by trjExpensify** [comment]
Why is that a problem though?

**Comment by laurenreidexpensify** [comment]
@trjExpensify I agree that we can close this out 👍
