### ISSUE TITLE
Rethink about the avatar and status design on the new Global Nav

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#29136]
## 🚨 This issue is for the internal design team. Please DO NOT post proposals.

The new navigation panel (Global Nav) was added to NewDot. Some components on the Global Nav turned out to be cropped because of the limited space.

Please refactor the designs of these components if necessary.

Please see:
- [this issue](https://github.com/Expensify/App/issues/29133) where a button is cropped on the new Global Nav

<img width="400" alt="Screenshot 2023-10-10 at 9 13 06 AM" src="https://github.com/Expensify/App/assets/98560306/f18974d5-8bae-47cf-b903-82a05d24efab">

- [this issue](https://github.com/Expensify/App/issues/29057) where the Avatar with a status is cropped on the new Global Nav

<img width="400" alt="Screenshot 2023-10-10 at 9 12 55 AM" src="https://github.com/Expensify/App/assets/98560306/7d59fac7-075f-4eda-99d2-7dbc583f8f0d">

**Comment by dubielzyk-expensify** [comment]
Convo happening [here](https://expensify.slack.com/archives/C05NM77EUTS/p1696918447164419?thread_ts=1696891693.386989&cid=C05NM77EUTS). This were variations for status:
![image](https://github.com/Expensify/App/assets/145416827/231a6a05-55fd-420a-91a0-7b4137ae31ef)

And for public rooms:
![image](https://github.com/Expensify/App/assets/145416827/c7ac46d6-a191-47f2-a67d-b0cf6fd79402)

**Comment by dubielzyk-expensify** [comment]
Let me know if anything is needed here. Think consensus in Slack seemed to be that the status bar with the smaller emoji was the right one rather than vertically stacked

**Comment by dubielzyk-expensify** [comment]
Not overdue, just awaiting confirmation

**Comment by hayata-suenaga** [comment]
sorry for the delay in response. yes we can close this issue for now. thank you so much for working on the high fidelity!
