### ISSUE TITLE
[Collect Approvers] Add Approve and Pay buttons by using report NextSteps

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#29145]
~On hold for https://github.com/Expensify/Expensify/issues/323548~
~On hold now for https://github.com/Expensify/Web-Expensify/pull/39328~

Coming from this [internal](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1695911387950759?thread_ts=1695891602.322289&cid=C02NZ2HGJAZ) discussion, we're going to use the report NextSteps data from OldDot to render the Approve or Pay button for collect policies according to the user.

Additionally, we want to render the "approved" message in the corresponding places listed in the [HL](https://docs.google.com/document/d/1Gv_fYjzrHzI_VXdrsUxppUS0Xn_pqWdYZ-2zlGF0jXc/edit), like in the report header, report preview and the expense report.

**Comment by marcochavezf** [comment]
Fixed more edge cases that I've found but in the frontend. Tomorrow I will run another set of local tests to prepare the PR for review.

**Comment by marcochavezf** [comment]
PR in review

**Comment by marcochavezf** [comment]
PR updated to fix https://github.com/Expensify/Expensify/issues/325515

**Comment by marcochavezf** [comment]
I'm working on the backend PRs, more details [here](https://github.com/Expensify/Expensify/issues/300633#issuecomment-1776439402).

**Comment by marcochavezf** [comment]
Updated the PR to follow the approach of checking the status and state of the report preview to show the Pay and Approver buttons in the workspace chats.

**Comment by marcochavezf** [comment]
PR is still in review. We're going to only test scenario 2 (non-admin approver), since we'd need to check if the admins have access to the VBBA.

**Comment by marcochavezf** [comment]
Fixed reported bugs, PR ready for hopefully a final review 🤞🏽

**Comment by marcochavezf** [comment]
Hi @dylanexpensify, could you handle the payment for @shubham1206agra for https://github.com/Expensify/App/pull/28976? 🙇🏽

**Comment by dylanexpensify** [comment]
Yes, will do!

**Comment by dylanexpensify** [comment]
@shubham1206agra please apply [here](https://www.upwork.com/jobs/~01173d2bf24a59463d)!

**Comment by marcochavezf** [comment]
Ok, I think we can close it out. Thanks!
