### ISSUE TITLE
[HelpDot] Environment is set to development for production

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#29154]
Coming from [slack 🧵](https://expensify.slack.com/archives/C02QSAC6BJ8/p1696904545748839)

## Problem

If no enviornment is specified, jekyll runs in development mode.
This is causing concierge URL to link to localhost.

<img width="372" alt="image" src="https://github.com/Expensify/App/assets/29673073/2bf550a0-ff91-48db-92bd-37436af7dad1">

## Solution

In cloudflare, set the value of `JEKYLL_ENV` to `production` 

Docs: https://jekyllrb.com/docs/configuration/environments/#:~:text=JEKYLL_ENV%3Dproduction%20jekyll%20build

**Comment by coleaeason** [comment]
Done!
