### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Chat - Green line only appears on the first message marked as unread until the chat is reloaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29160]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com or open iOS/Android/Desktop App
2. Login with any account
3. Open a chat with many messages
4. Mark any message as unread
5. Check that a green line "New" appears above the message
6. Mark another message as unread

## Expected Result:
Green line "New" appears above the another message

## Actual Result:
Green line still marks the previous message
===
Green line appears above another message only after the chat is reloaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/70806e5a-a85c-4e39-92b8-9b0d3462df1c

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/115492554/a9d5c3e0-5eb8-47c9-94a8-e4e984a35a4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Not repro in Prod

https://github.com/Expensify/App/assets/115492554/0c2986d2-d5ea-4098-bfd7-c73b7d02ad04

**Comment by zukilover** [comment]
I'm working on the fix.

**Comment by adelekennedy** [comment]
are these issues related? #29197 29197

**Comment by jasperhuangg** [comment]
Hmm @adelekennedy I'm not entirely sure if they're duplicates. Let's keep the other issue open. Thanks for pointing that out!

**Comment by NicMendonca** [comment]
@aimane-chnaif can you apply to the job please? https://www.upwork.com/jobs/~01de5cb06e0da1953b

**Comment by NicMendonca** [comment]
Are you sure? Melv couldn't get payment date right 😂 

<img width="650" alt="image" src="https://github.com/Expensify/App/assets/24947345/defc0914-2851-4886-b00e-19e776e6e861">

**Comment by NicMendonca** [comment]
@aimane-chnaif offer sent

**Comment by NicMendonca** [comment]
@aimane-chnaif you've been paid!
