### ISSUE TITLE
[$500] mWeb/Chrome - Login - Google logo flickers with white box when swiping between two login tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27385
## Action Performed:
1. Open login page (https://staging.new.expensify.com/
) in two tabs
2. Swipe between the login tabs
Note that the Apple and Google logos blink and Google blinks with white box when swiping between tabs

## Expected Result:
Apple and Google logos will not flicker

## Actual Result:
Apple and Google logos flicker. Google logo flicker with white box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/ca4e313c-6ecb-44d2-8293-a89f5a499f8e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120db614a63f23b8f</li>
        <li>Upwork Job ID: 1714313858027421696</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment]
Definitely don't need to be blocking deploy on something like this, removing the deploy blocker label

**Comment by kevinksullivan** [comment]
Assuming this can be external?

**Comment by situchan** [comment]
Related to #28080
