### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] IOU-In Workspace, split bill detail page, category option is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28628
## Action Performed:
1. Launch app - expensifail sccount
2. Tap fab
3. Tap request money- manual
4. Enter an amount
5. Tap next
6. Select any Workspace and tap " split"
7. Tap add to split
8. Tap show more and select a category
9. Tap split amount
10. Tap split amount transaction to open split detail page
11. Tap " show more"

## Expected Result:
In Workspace, split bill detail page, category option must be shown

## Actual Result:
In Workspace, split bill detail page, category option is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] Windows: Chrome
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/01907030-702e-4d1c-b3d7-5b263aa72eca

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/a508703e-a297-48eb-aab1-c7a291e1495c

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/f67782b4-dc7d-40e7-89ef-a289c885f05a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/b4db19f6-ae08-4da7-94d7-45ea9b071015

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de758e8c4c31ca17</li>
        <li>Upwork Job ID: 1711881725957390336</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 27258819</li>
</ul></li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Proposal in https://github.com/Expensify/App/issues/29178#issuecomment-1755750275 ready for review @mollfpr

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/29178#issuecomment-1755750275) from @Nodebrute looks good!

🎀 👀 🎀 C+ reviewed!

@bfitzexpensify Could you help with adding the Engineering label? Thank you!

**Comment by arosiclair** [comment]
> @bfitzexpensify Could you help with adding the Engineering label? Thank you!

Is the auto-assigner not working after approving a proposal anymore?

**Comment by mollfpr** [comment]
@arosiclair I think it's because I'm not on the team so Melvin won't be triggered.

**Comment by bfitzexpensify** [comment]
Offer sent for C+ work @mollfpr - also, a reminder to complete the BZ checklist when you get a moment, thank you!

**Comment by mollfpr** [comment]
> The PR that introduced the bug has been identified. Link to the PR:
> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think any PR is causing this issue. I believe we forgot to update the list when decided to add the category to the split bill.

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
>If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Note: the backend is not ready yet to add and get a category for a split bill. So, we need to mock a situation when we have a category inside a split bill.

Hack: we need to modify [getCategory of TransactionUtils.ts](https://github.com/Expensify/App/blob/fcfd2a080d7464305e2867ba3b5645f18a8c4e94/src/libs/TransactionUtils.ts#L236-L238). The function should return a hardcode string - name of a category like: return "Home".

For reference https://github.com/Expensify/App/pull/28628#issue-1922195467

1. Launch app ->Tap fab
2. Tap request money -> manual
3. Enter an amount -> Tap next
4. Select any Workspace and tap " split"
5. Tap add to split
6. Tap show more and select a category
7. Tap split amount
8. Tap the split amount transaction to open the split detail page
9. Tap "Show more"
10. Verify that you can see the category option

**Comment by mollfpr** [comment]
@bfitzexpensify I'll do manual request, could you give the payment summary? Thanks!

**Comment by JmillsExpensify** [comment]
Awaiting payment summary

**Comment by bfitzexpensify** [comment]
Payment summary:

Contributor: @Nodebrute due $750 to be paid via Upwork ✅ 
C+: @tienifr due $750 to be paid via manual request

**Comment by mollfpr** [comment]
@bfitzexpensify I think you tag the wrong C+ 😅

Friendly bump @JmillsExpensify for the approval.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mollfpr based on summary above.

**Comment by bfitzexpensify** [comment]
Regression test proposed in https://github.com/Expensify/Expensify/issues/334065

We're all done here, thanks everyone.
