### ISSUE TITLE
mweb - Profile - Unable to select text other than the introductory sentence

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Contact methods
3. Long press on the 'Add more ways...' sentence
4. Drag the select cursor to all the text in the page

## Expected Result:
The text that is dragged within the selection cursor is highlighted

## Actual Result:
Only the text in the 'Add more ways...' sentence is highlighted, although the selection curser is dragged all the way to the end of the page. The text in primary contact method row is not selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary> 

https://github.com/Expensify/App/assets/78819774/ccaf9daa-408a-4e10-b47c-5b2ed9a17b10

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/78819774/5d5ea183-8008-49b4-ad1a-77212a7c2919

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Doesn't need to be fixed imo
