### ISSUE TITLE
 LHN - 'Chats' in the LHN is not translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Preferences > Language
3. Change the language to Spanish

## Expected Result:
'Chats' in the LHN is translated to Spanish

## Actual Result:
'Chats' in the LHN is not translated to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/78819774/d4e00f68-1e73-4f84-9300-c1652fcd8030

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/78819774/6ad5c0c4-3681-44a9-8d19-93a0eb0420d8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/78819774/128deea3-3b5f-47d5-89e6-4ee534e06060

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/78819774/82ca6fba-6a38-433a-ad58-b20a88ff2290

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/78819774/5cef0ed3-cc77-4090-ad34-b5e7f51b01d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
According to [this](https://expensify.slack.com/archives/C21FRDWCV/p1696978752762729), "Chats" is accepted colloquially in Spanish, so no need to fix this!
