### ISSUE TITLE
Android-Bank-Link 0Auth integration error message shown and unable to connect Chase and Wells Fargo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile -- workspaces-- Workspace-- Bank account
3. Tap Connect with plaid--tap continue
4. Tap "Chase/Wells Fargo" and complete the flow
5. Close "continue to expensify to finish account linking" page
6. Launch app now
7. Repeat step 2- step4

## Expected Result:
Step 4 When user taps "chase/wells Fargo", there are potential problem with your Link 0Auth integration error message must not be shown
User must be able to connect the bank account

## Actual Result:
Step 4 When user taps "chase/wells Fargo", there are potential problem with your Link 0Auth integration error message is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/205c2d12-1793-481f-b641-3683536e71c2

https://github.com/Expensify/App/assets/78819774/c6270458-c205-44ea-bea8-f030081ee080

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I'm going to hold on this as there are lots of changes to this flow currently in the works so things could change

**Comment by MitchExpensify** [comment]
Not reproducible on v1.3.92-4

<img width="716" alt="image" src="https://github.com/Expensify/App/assets/36425901/728812d2-50a1-430f-8a42-b42d324e0699">

<img width="538" alt="image" src="https://github.com/Expensify/App/assets/36425901/1a0907ac-ff86-43fd-83f8-fcb83a2dcd79">
