### ISSUE TITLE
[$500] Web - Chat - Green line over the welcome message in #announce remains when user switch chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. User A set a Welcome message in #announce room
2. User A invite User B to Workspace
3. User B navigates to #announce room created by User A
4. There is a green line visible above the Welcome message in chat history
5. User B navigates to other chat or refresh the page
6. User B navigates back to #announce room

## Expected Result:
After Step 3 - green line should disappear from chat history

## Actual Result:
Green line over the welcome message in #announce remains eve when user switch chat or refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows:Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/b6fb4724-12be-4182-aaa7-4efc45f65051

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132c30688b58c9164</li>
        <li>Upwork Job ID: 1711975583342415872</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
actually I think this issue might be a dupe/similar issue to [this](https://github.com/Expensify/App/issues/29160)

**Comment by sobitneupane** [comment]
I won't be available next week. If any action is required from my end, please feel free to reassign the issue.

**Comment by adelekennedy** [comment]
closing this - small enough issue that doesn't affect workflow
