### ISSUE TITLE
Request money - After creating a Distance request offline, request will not open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open the New Expensify Desktop app
2. Sign into a valid account
3. Turn internet OFF
4. Click on Request > Distance > Complete the Distance request with valid points while offline
5. After the request is complete, turn the internet back ON
6. Click on the created Distance request

## Expected Result:
User expects the request to open with no issues

## Actual Result:
The request page does not load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/78819774/25608e33-653b-4701-abc1-9ca0d389c5b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
@lanitochka17 I couldn't reproduce on v1.3.80-3. Can you give it another try and reopen if you can reproduce/

**Comment by peterdbarkerUK** [comment]
I think[ this](https://github.com/Expensify/App/issues/29535) is the reproducible version of the same bug

**Comment by lanitochka17** [comment]
Issue is not reproducible on Build 1.3.83-11

https://github.com/Expensify/App/assets/78819774/b51f38c6-cebb-4bef-aff6-7850e96818b3
