### ISSUE TITLE
[$500] Android - Concierge Chat - When I tap the back arrow, the concierge chat doesn't go back to LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Log out of NewDot
2. Close the NewDot app
3. Go to https://staging.new.expensify.com/concierge
4. Verify that you are taken to the login screen
5. Log in to NewDot
6. Verify you're navigated to the concierge chat after login
7. Tap the back arrow

## Expected Result:
The concierge chat should go back to LHN

## Actual Result:
The concierge chat doesn't go back to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary> 

https://github.com/Expensify/App/assets/78819774/9d04a6ae-ceea-4c12-8754-1006c20658da

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019826d4fab45db3ed</li>
        <li>Upwork Job ID: 1711842451889889280</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 27227276</li>
</ul></li>
    </ul>
</details>

**Comment by lschurr** [comment]
@Santhosh-Sellavel can you review this proposal?

**Comment by lschurr** [comment]
Bump @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
Can you please assign a new C+ here, due to low bandwidth unassigning myself.

**Comment by lschurr** [comment]
Asking here: https://expensify.slack.com/archives/C01GTK53T8Q/p1697484117905529

**Comment by akinwale** [comment]
Taking over as C+ here. I will review today.

**Comment by akinwale** [comment]
@tienifr Are you still able to reproduce this on the latest main? I cannot seem to reproduce the behaviour as shown in the video.

**Comment by lschurr** [comment]
Bump @akinwale and @tienifr - is this reproducible?

**Comment by akinwale** [comment]
@lschurr Looks like this can be closed.
