### ISSUE TITLE
 Deeplink - Public room does not opens in app after Sign Out and background the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Tap on Profile picture and scroll down
3. Tap on Sign Out
4. Open the Public room deeplink https://staging.new.expensify.com/r/5408450846930023

## Expected Result:
User should be navigated to the app and public room page should be opened

## Actual Result:
User was navigated to the app but common Sign In page displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/ffe7e8ed-6d22-410a-acd5-69614b85bfd3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Still on my testing list, other GHs have taken priority.

**Comment by alexpensify** [comment]
I've run out of time and will have to test over the weekend.

**Comment by alexpensify** [comment]
Closing - I've been unable to replicate it on my android device
