### ISSUE TITLE
[HOLD] [MEDIUM] Distance: Present the option to add a waypoint by placing a marker on the map manually

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#29215]
## Problem
If you drove from point A to B for business, but had to take a large detour due to road construction, then it would be very difficult to create a distance request for that drive. If you enter waypoints A and B, the fastest route between them will be displayed. To add in your detour you would have to use another mapping app, like google maps, to find an address along your detour, then go back to Expensify and add that address as a stop.

## Solution
Present the option to add a waypoint by placing a marker on the map manually. On the waypoint editor page present a "Drop pin" menu item. When clicked it will navigate to a new page which will display a map view and a waypoint marker centered at your current location. The marker will stay centered and can be moved by dragging the map around beneath it. Once satisfied with the location you can click save and will be navigated back to the distance request page. The waypoint address with be set to "Custom" and the lat/lng will be set where the marker is located.

<img src=https://github.com/Expensify/App/assets/26260477/f5374303-5279-4c15-b525-d19e45b38d54  width=300px>

Once we get some more mockups created and lock in the UX, let's make this issue external.
The original Slack conversation is [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1696630717560679) (internal).
cc @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Retest and this is successfully fixed.

**Comment by JmillsExpensify** [comment]
Whoops wrong issue, marking that last comment as off topic.

**Comment by dannymcclain** [comment]
[Posted some initial mocks for this in Slack](https://expensify.slack.com/archives/C05DWUDHVK7/p1697126229681799?thread_ts=1696630717.560679&cid=C05DWUDHVK7)

**Comment by neil-marcellini** [comment]
We decided [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1697128319934589?thread_ts=1696630717.560679&cid=C05DWUDHVK7) to put this on HOLD until we can call wave 5 "done". This is an optional feature and we don't want to increase the scope of the wave.

**Comment by conorpendergrast** [comment]
I'll set this as Weekly, given it's on hold until wave 5 is done

**Comment by dannymcclain** [comment]
Still on hold Melvin.

**Comment by neil-marcellini** [comment]
Yep still holding, moving to monthly since wave 5 will be open for a while yet.

**Comment by dannymcclain** [comment]
I'm assuming this is still on hold. Someone please correct me if I'm wrong!

**Comment by conorpendergrast** [comment]
@dannymcclain yeah it looks like this is on hold until we get ready for release 5 (Best in case), and [not working on it yet](https://expensify.slack.com/archives/C05DWUDHVK7/p1706276250352799)

**Comment by dannymcclain** [comment]
Still on hold Melvin.

**Comment by dannymcclain** [comment]
Still holding as far as I know. Should we change this to monthly?

**Comment by dannymcclain** [comment]
@neil-marcellini I think that makes a lot of sense, and based on that, agree that we should close it.
