### ISSUE TITLE
Split bill - Split bill on workspace chat can only be created from FAB, but not the chat itself

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a workspace chat > + button > Request money
3. Attempt to create a split bill
4. Go to FAB on LHN > Request money > Manual
5. Enter amount > Next
6. Select Split on the workspace chat in Step 2

## Expected Result:
User should be able to create split bill from workspace chat and FAB

## Actual Result:
User is only able to create split bill in workspace chat from FAB menu. In workspace chat, only request money option is possible

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/f0648ddf-0237-4a3a-ae11-5fb56bd51fa6

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Ah, @youssef-lr.. isn't `Split bill` being added back as a menu item in the workspace chat create menu?

**Comment by trjExpensify** [comment]
@youssef-lr confirming we can close this one?

**Comment by trjExpensify** [comment]
The only workspace chat that has the `Split bill` option right now is the Teachers Unite one.

**Comment by youssef-lr** [comment]
@trjExpensify seems like this can be bypassed using Global Create. Should we implement a fix to not show the split pill button next to other workspaces?

**Comment by youssef-lr** [comment]
Likewise a fix to not allow requesting money from TU workspace?
