### ISSUE TITLE
[$500] Mweb/Chrome-IOU-Tapping on amount section, the amount is not visible properly for a milli second

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app as employee
2. Tap on a Workspace chat
3. Tap plus icon
4. Tap request money
5. Enter an amount
6. Tap next
7. Tap show more
8. Select any category
9. Tap request amount
10. Tap on iou transaction to open IOU detail page
11. Tap on the amount section

## Expected Result:
Tapping on amount section, the amount must displayed properly and user must be able to view the entire amount properly

## Actual Result:
Tapping on amount section, the amount is not visible properly for a milli second and then only amount is displayed and can be seen fully

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/78819774/b06dd684-8685-4d61-8a58-099c7043f069

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f0922c750ac9f2b</li>
        <li>Upwork Job ID: 1714017993685532672</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
@lanitochka17, can you provide a video of this behavior?

**Comment by lanitochka17** [comment]
@johncschuster Hello. The video has been added to the “Screenshots/Videos” tab

![image](https://github.com/Expensify/App/assets/78819774/18ba4419-bd5e-4cc2-8d73-6e60e1913311)

**Comment by johncschuster** [comment]
Thanks! Triaging!

**Comment by MrMuzyk** [comment]
@lanitochka17 
Hey, I couldn't reproduce this issue (see the recording). Can you confirm that this is still happening?

https://github.com/Expensify/App/assets/23487612/b91afb3c-4e33-457f-ac31-f08d17804706

**Comment by lanitochka17** [comment]
@MrMuzyk Hello Issue is not reproducible with latest build 1.3.87-1

https://github.com/Expensify/App/assets/78819774/e821d893-3640-4c1b-ad0a-159499d8b362

**Comment by MrMuzyk** [comment]
Greate, I guess it can be closed then
