### ISSUE TITLE
IOS - LHN - Deleted offline workspace chats do not move to the bottom

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29221]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28987
## Action Performed:
1. Open the app
2. Create a workspace and add some members
3. Turn off internet connection
4. Remove a member from the workspace
5. Navigate back to LHN

## Expected Result:
The workspace chat with a member is archived and moved to the bottom

## Actual Result:
The workspace chat gets archived, but it is not moved to the bottom. It stays in the same place in LHN

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/d376e2d2-6514-49af-adab-5ca33727fc06

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Don't really think we need to block deploy on this, but I do think @tsa321 should make sure that this flow works.

Looking through the tests for https://github.com/Expensify/App/pull/28987 iOS native we're not testing to see if the LHN item for the archived workspace chat gets sorted to the bottom.

**Comment by strepanier03** [comment]
I'm also struggling to recreate this. I'm using Browserstack since I don't have an iOS physical device. 

@lanitochka17 - Are you still able to recreate this following the steps exactly? Any advice you can offer @tsa321 or I?

**Comment by lanitochka17** [comment]
@strepanier03 Hello 
Issue reproducible on Build 1.3.86-0

https://github.com/Expensify/App/assets/78819774/83e6bb72-e657-462b-af3e-88691a32b0d3

**Comment by lanitochka17** [comment]
@tsa321 Hello
According your steps Workspace chats have moved down
Iphone 14 Pro Max/ios17


https://github.com/Expensify/App/assets/78819774/fc072a44-dfb0-4e50-998a-7c75525179f5

**Comment by strepanier03** [comment]
I'm also stuck without a physical iOS device.

**Comment by mountiny** [comment]
I think we can close this issue @cead22
