### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Show place name and address for suggestions and recent waypoints, like google and apple maps.

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#29222]
## Problem
If you create a distance request and enter a start point such as the "Expensify lounge SF", then it will pop up as a suggestion. After selecting it the corresponding address will fill in. When you go to create another distance request that address will show up as a recent waypoint, but it won't include the "Expensify lounge" label, so you might forget what place the address is for.

## Solution
Show place name and address for suggestions and recent waypoints, like google and apple maps. We'll need to display these on the front end above each suggested address and it should be stored as a new, optional field on the waypoint called 'place'. The waypoint will be stored into the recent waypoints on the backend with the 'place' field. If the distance request is created offline then we should attempt to find the 'place' corresponding to the address while geocoding it.

Here's how google maps displays places and addresses
<img src=https://github.com/Expensify/App/assets/26260477/3bcab6f6-e43b-4b91-97c9-786b366d114a  width=300px>

Here's how suggested addresses / recent waypoints currently work.

https://github.com/Expensify/App/assets/26260477/3e1a24c0-fc18-4dae-ae7c-ea894f6ae8dd

May we please have some mockups for how this should look in App? Once we finish those let's make this external. ✅  We can handle the offline case on the backend with this issue [[HOLD 22126] Handle errors with geocoding for offline distance requests](https://github.com/Expensify/App/issues/22719).

Here's the original [Slack conversation](https://expensify.slack.com/archives/C05DWUDHVK7/p1696630853946649).

Please implement this mock for the suggested addresses and recent waypoints. Please DM me and let me know if backend changes are required, and I can implement them.
![CleanShot 2023-10-11 at 21 38 35@2x](https://github.com/Expensify/App/assets/26260477/e1561db2-61d7-494e-9089-99e38cc73a42)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2be762214c68e5d</li>
        <li>Upwork Job ID: 1712857757894922240</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 27265347</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by dubielzyk-expensify** [comment]
Potential solutions. I'd probably say we should go with A. Slack discussion happening [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1697024287269619?thread_ts=1696630853.946649&cid=C05DWUDHVK7).
![CleanShot 2023-10-11 at 21 42 05@2x](https://github.com/Expensify/App/assets/145416827/6c40f81b-e985-4195-9f9b-1f463a4e5340)

**Comment by adelekennedy** [comment]
Won't make this external until we agree on the design

**Comment by neil-marcellini** [comment]
We're going for option B and can get started now.

**Comment by esh-g** [comment]
# Proposal

## Please re-state the problem we are trying to solve
Show place name and address for suggestions and recent waypoints, like google and apple maps.

## What is the root cause of this problem?
N/A (New feature)

## What changes should be made?
We should do a custom render for the rows by passing the `renderRow` prop to the autocomplete component here:
https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/components/AddressSearch/index.js#L285

The `renderRow` can look like this:
```js
renderRow={(data) => {
    return (
        <View>
            <Text style={[styles.googleSearchText, styles.h4]}>{data.structured_formatting.main_text}</Text>
            <Text style={[styles.googleSearchText]}>{data.structured_formatting.secondary_text}</Text>
        </View>
    );
}}
```

**Comment by adelekennedy** [comment]
@mananjadhav one proposal to review above

**Comment by mananjadhav** [comment]
Will review in next 1 hour or so.

**Comment by esh-g** [comment]
Well name of the property can be any... I just went with name because it was consistent with the api but it can be set as place as well if required.
@neil-marcellini and I already discussed that backend doesn't prohibit any property

**Comment by neil-marcellini** [comment]
I like @esh-g's [proposal](https://github.com/Expensify/App/issues/29222#issuecomment-1761774827). Hired!

**Comment by esh-g** [comment]
PR is here: https://github.com/Expensify/App/pull/29931

cc @mananjadhav @neil-marcellini

**Comment by neil-marcellini** [comment]
I started working on filling in the place names on the backend. However, after experimenting in the Mapbox [geocoding api playground](https://docs.mapbox.com/playground/geocoding/?search_text=tiburon%20ferry%20landing%20ca&fuzzyMatch=false&routing=false&proximity=ip&types=place%2Caddress&autocomplete=false&access_token=pk.eyJ1IjoibmVpbC1leHBlbnNpZnkiLCJhIjoiY2xnNWZ1YWNzMDJ4YTNzbzhycmtya2t6OCJ9.GZZl5s4hC6QIeTe0-I47yw), I found that the `place_name` returned isn't that great and doesn't match what we get from Google on the front end. For example `1501 Tiburon Blvd Belvedere, 1501 Tiburon Blvd, Tiburon, CA 94920` returns `Belvedere Tiburon Library, 1501 Tiburon Blvd, Tiburon, CA, USA` on the front end. Mapbox returns the exact address as the place name, which is pretty much useless to us.

It's not critical for place names to fill in for offline requests, and if people are making offline requests they will need to have the exact address anyways, so I think we can move on without filling in place names on the backend.

**Comment by esh-g** [comment]
> days elapsed: 4

So close to the bonus! But anyway the process was fun and learned a lot from this.. 😇

**Comment by neil-marcellini** [comment]
@adelekennedy I would recommend that we do pay the bonus, because this was held up on various internal decisions, especially design, for a while.

**Comment by adelekennedy** [comment]
Noted for payments we will pay out the speed bonus on this one

**Comment by mananjadhav** [comment]
**Regression Test:**

1. From the FAB (+) icon, click on Request money
2. Click on distance tab
3. Click on start and search for a location, for example `Expensify Lounge`
4. Verify the places are shown with the `name` and `address` (or should we call `name` and `description` ?)
5. Perform the same for other stops and finish stop.
6. Complete the request money flow.
7. Open the preview of the request IOU to verify that both name and address are visible.

I don't think we need a regression for the users who've got recent places without the name field. what do you think @neil-marcellini @adelekennedy ?

**Comment by mananjadhav** [comment]
Quick bump @adelekennedy for the payout summary? So that I can raise a payout request.

**Comment by mananjadhav** [comment]
@neil-marcellini @adelekennedy is OOO until Tuesday. Can we assign another BZ member here?

**Comment by neil-marcellini** [comment]
I think Adele is back now.

**Comment by mananjadhav** [comment]
@adelekennedy is OOO until today I think. Guessing this would be handled this week.

**Comment by adelekennedy** [comment]
back today - handling payments
### Payouts due:

Issue Reporter: N/A
Contributor: $750 @esh-g (Upwork)
Contributor+: $750 @mananjadhav (NewDot)

Eligible for 50% #urgency bonus? [Y](https://github.com/Expensify/App/issues/29222#issuecomment-1780150037)

Upwork job is [here](https://www.upwork.com/nx/wm/workroom/35183072/overview).

**Comment by adelekennedy** [comment]
I think we're all done here!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mananjadhav based on summary above.
