### ISSUE TITLE
[$500] Invite members - Search input is not focused after selecting option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696681734478929

## Action Performed:
1. Open settings > workspaces > any workspace > members
2. Select any member and observe the input is focused after selection
3. Go to invite page and select any user
4. Observe input is not focused after selection

## Expected Result:
The input should be focused after selection.

## Actual Result:
The input is not focused after selection.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/ffe92d9e-ebbd-44ec-8864-522b79560ab2

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/348b6135-9841-4cac-8fc5-ca0b1c972b13

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0ed7e3d3096c66f</li>
        <li>Upwork Job ID: 1711835676434518016</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Linking old KI https://github.com/Expensify/App/issues/10587

**Comment by pradeepmdk** [comment]
this dube of https://github.com/Expensify/App/issues/29076

**Comment by Christinadobrzyn** [comment]
Good catch @pradeepmdk thank you! Closing.
