### ISSUE TITLE
[HOLD for payment 2023-11-18] [$500] Deleting all workspaces does not remove red dot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696933257327709

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account->connect manually
3. Fill in step 1 and 2 details
4. In step 3, fill in details and add any character in first name eg: 'test%%' (note that we are just doing this to trigger server error, it is not compulsory to trigger error only by this method)
5. Click on Save & Continue and notice that it will trigger server side error
6. Exit back to home page
7. Click on settings->workspaces and delete all workspaces one by one
8. Observe that even after deleting all workspaces, red dot is displayed on profile and besides workspaces in settings
## Expected Result:
App should remove red dot of workspace error if  we delete all the workspaces
## Actual Result:
App displays red dot of workspace error even after we delete all the workspaces, it removes the red dot on relogin
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/8a92ba63-e48c-4858-a353-5b400e9f0a8a

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/64fbc181-5ad3-4499-a5b8-80d43fca6f73

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/f199b1a0-1b02-4039-a2bc-d0845365859f

https://github.com/Expensify/App/assets/38435837/85afc273-2f1d-4f24-b19f-e8244f892d61

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/a7c03a6e-ec08-456c-98b9-6756720c10bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013278e8038908746f</li>
        <li>Upwork Job ID: 1711854514958786560</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27222500</li>
<li>dukenv0307 | Contributor | 27222503</li>
<li>dhanashree-sawant | Reporter | 27222505</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleting all workpsaces doesnt remove the red dot from the avatar and the settings workpsace tap
### What is the root cause of that problem?

in this line we dont check if the current admin policies are empty or beside the reimbursementAccount.errors check

https://github.com/Expensify/App/blob/7f7b4245788dc0968b0f1cbed19debdb1b79a251/src/pages/settings/InitialSettingsPage.js#L180-L181


same for the avatar indicator
https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/components/Indicator.js#L82


### What changes do you think we should make in order to solve the problem?

Get the admin typed workspaces and check if they are empty or not beside reimbursementAccount.errors check

```js
        const adminPolicies = _.chain(props.policies)
            .filter((policy) => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
            .value();
```

change the check to: 

```js
            (!_.isEmpty(props.reimbursementAccount.errors) && !_.isEmpty(adminPolicies)) ||

```

also in the indicator component we do the same .. 

```js
    const adminPolicies = _.chain(cleanPolicies)
        .filter((policy) => policy && policy.type === CONST.POLICY.TYPE.FREE && policy.role === CONST.POLICY.ROLE.ADMIN)
        .value();

```

```js
        () => !_.isEmpty(adminPolicies) && !_.isEmpty(props.reimbursementAccount.errors),

```

**Comment by abzokhattab** [comment]
forgot to mention that by making [those changes](https://github.com/Expensify/App/issues/29235#issuecomment-1756355880), whenever we create a new workspace again after we delete all of them, the red dot will be back again, which i think is the expected behavior.

**Comment by abzokhattab** [comment]
What is the final verdict on here? which approach should we take?  @hoangzinh

**Comment by luacmartins** [comment]
@hoangzinh do we have a video of what that looks like? Might help with deciding if we should still fix this

**Comment by luacmartins** [comment]
Thanks for the videos @hoangzinh! Yea, I think we should still fix this.

**Comment by NicMendonca** [comment]
omg, sorry, this didn't pop open as a daily for me to pay

**Comment by NicMendonca** [comment]
Everyone has been paid via Upwork 🎉
