### ISSUE TITLE
[HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] Unhide `Save the world` from the global create menu 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#29240]
Coming from this ([internal convo](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1696970641074929)). 

We're launching Teachers Unite next Tuesday, and need to bring this menu item back into production ahead of then. As we need to navigate the deploy cycle to get this into prod in good time, we're going to do this now and not try to time it perfectly.

**Comment by mountiny** [comment]
No payment needed
