### ISSUE TITLE
[CRITICAL] Upgrade to Fabric

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#29258]
Turning on the new architecture in the Expensify App as well as changing the libraries with native components to the commits containing implementation of Fabric integration in them.

Enabling Fabric itself will not give us a speed boost, but using the concepts from React 18, which is available only with Fabric, should help.

Tracking here for the weekly update: 

https://github.com/Expensify/App/pull/13767

**Comment by muttmuure** [comment]
https://github.com/Expensify/App/pull/31558

**Comment by roryabraham** [comment]
Closing this in favor of https://github.com/Expensify/App/issues/8503
