### ISSUE TITLE
[$500] Send Money -Loading appears on other side on send money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.81.4
**Reproducible in staging?:** y
**Reproducible in production?:** no (send money flow implemented)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697005092157949

## Action Performed:
1. Click on FAB and select send money
2. Send money to userB
3. Verify paid amount on userB side

## Expected Result:
It should show paid amount

## Actual Result:
Loading appears

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/bfd6ae62-6de0-4f85-8a6d-ac33dc824c5f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/87a9aa10-eabd-48f0-8508-6d185dbbce25

</details>

<details>
<summary>iOS: Native</summary>

 
https://github.com/Expensify/App/assets/93399543/ce77bf50-6168-4b37-a316-94819c46dfe4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9d1beeef-efbc-4a5f-8fec-add7f72ba4e3

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![image](https://github.com/Expensify/App/assets/93399543/6b978936-b602-4d2c-a614-c545ebfe01d3)

https://github.com/Expensify/App/assets/93399543/7fc773ff-c5f4-4bf5-94e1-6fb2e6bf086f

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/59f5c350-fb15-4f7b-80a7-0af48d1ba6b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012046b8639b074dfc</li>
        <li>Upwork Job ID: 1712078968483549184</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Bumped @ntdiary in Slack.

**Comment by sakluger** [comment]
I asked in that Slack thread if the BE fix will fix this issue as well.

**Comment by sakluger** [comment]
This is confirmed to be fixed now! 🎉
