### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [ECard Transactions] Add ReportPreview Dog Ear Style for 3+ Receipts

### ISSUE THREAD

**Issue by grgia** [Expensify/App#29291]
### Design Doc Section

https://docs.google.com/document/d/1iELOXPOAcnuIPZJ3XbO1S8_3qHaM31Ptf8dR4LRZMyE/edit#bookmark=kix.o2b39rlbvmvl

### Overview 

![Image](https://github.com/Expensify/App/assets/38015950/8c9bb960-b4b5-4e8c-b2a0-ec25e3493af9)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f831aa52e8c9f448</li>
        <li>Upwork Job ID: 1712080359418015744</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Contributor+: @allroundexperts is due $500 via NewDot (that's the right amount.... right?)

**Comment by mallenexpensify** [comment]
DB as in Data Base?  (just want to make sure I understand for the future)
Updated the post above with the correct amount so I'm going to close

**Comment by JmillsExpensify** [comment]
@mallenexpensify mind updating your summary so that I can get this paid?

**Comment by mallenexpensify** [comment]
Double posting for clarity
 
Contributor+: @allroundexperts is due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 payment approved for @allroundexperts based on comment above.
