### ISSUE TITLE
[HOLD for payment 2023-10-23][$500]  Send money - Extra two digits are added before the decimal point when money is sent offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go offline
4. Go to + > Send money
5. Enter MYR 9
6. Complete the send money request
7. Click on the IOU preview
Note that in the report page, it shows RM900.00 instead of RM9

## Expected Result:
The sent money in report page shows the correct amount, which is RM9.00

## Actual Result:
The sent money in report page shows the incorrect amount, which is RM900.00. It shows the correct amount after going online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/78819774/dd3c18b5-5094-4c78-850a-5518f71a7724

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01227f1e2615915351</li>
        <li>Upwork Job ID: 1712128108884541440</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 27143160</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send money - Extra two digits are added before the decimal point when money is sent offline
### What is the root cause of that problem?
Turning amount into smallest unit is hardcoded here by multiplying it to `100` which is not correct for some currencies
### What changes do you think we should make in order to solve the problem?
We should use `getCurrencyUnit` from here to correctly turn amount into currency unit
https://github.com/Expensify/App/blob/42d21e22fae4ce8ee957ad090ec9019837e01efa/src/libs/CurrencyUtils.ts#L38-L40

### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment]
Taking a look at the issue and then I will review the proposal, thanks.

**Comment by amyevans** [comment]
Thanks @techievivek! ❤️

**Comment by piyushbeli** [comment]
What kind of fucking platform this is that does not have a dev team to fix the issues and post these bugs on Upwork. 
User...Please stay away from such pity platforms.

**Comment by piyushbeli** [comment]
Do you rely on Upwork to fix the deploy brokers? Rally? Someone who does not have prior knowledge about your code can fix the deploy brokers faster than your internal team. That means your internal team is not capable and that is why every bug you post on Upwork.

**Comment by alitoshmatov** [comment]
@piyushbeli I think you are overreacting without any context, please read https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md and checkout this site - https://we.are.expensify.com/freelance

**Comment by amyevans** [comment]
Retested on staging after cherry pick:
![Screenshot 2023-10-11 at 5 43 02 PM](https://github.com/Expensify/App/assets/7277067/5a316e16-c29d-4ed6-bd90-d183f6a6f3c2)

**Comment by amyevans** [comment]
Went through the BZ checklist: https://github.com/Expensify/App/issues/29318#issuecomment-1765326204

So all that's left is payments!

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: Internal
- Contributor+: @alitoshmatov $750 (paid in Upwork)

**Comment by lschurr** [comment]
All done!

**Comment by situchan** [comment]
@lschurr C+ payment is pending. Can you please reopen the issue?

**Comment by lschurr** [comment]
@situchan - @alitoshmatov was already paid in Upwork. Could you clarify what's missing?

**Comment by situchan** [comment]
@lschurr ah, @alitoshmatov was C, I was C+ for this issue
You can see author & review in https://github.com/Expensify/App/pull/29353

**Comment by lschurr** [comment]
Ah, it looks like the automation missed that! I'll update the payment summary.

**Comment by lschurr** [comment]
Are you paid in Upwork or newdot @situchan?

**Comment by situchan** [comment]
> Are you paid in Upwork or newdot @situchan?

upwork

**Comment by lschurr** [comment]
Updated: https://github.com/Expensify/App/issues/29318#issuecomment-1775541230

**Comment by lschurr** [comment]
Could you apply here @situchan? https://www.upwork.com/jobs/~01227f1e2615915351

**Comment by situchan** [comment]
Applied

**Comment by lschurr** [comment]
Payment issued. All set.
