### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] Crash when opening uknown profile URL

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ginsuma 
**Slack conversation:** https://github.com/Expensify/App/issues/29088#issuecomment-1757253173

## Action Performed:
Break down in numbered steps

Case 1:
1. Open this link in browser: https://staging.new.expensify.com/a/12345678 (http://localhost:8082/a/12345678 for dev)
2. Verify that app doesn't crash and shows hidden profile page

Case 2: (Follow repro step in #29088)

Precondition: user A and user B should have no prior chat history (only public accounts)
1. Open a tab where user A is signed in
3. Click on 'Profile avatar' > Share code > Copy URL to clipboard
4. Open a tab where user B is signed in
5. Paste the URL to the address bar
6. Press enter
7. Verify that app doesn't crash and profile page shows correctly

## Expected Result:
Describe what you think should've happened

No crash

## Actual Result:
Describe what actually happened

Crash

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
PR is merged need to cp it

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: @ginsuma (pay via Upwork)
 - Contributor: N/A [internal]
 - Contributor+: @aimane-chnaif (pay via Upwork)
 
 Upwork job is here, not eligible for bonus

**Comment by stephanieelliott** [comment]
@ginsuma can you please share your Upwork profile? I'm not able to find you there. 

@aimane-chnaif you've been paid!

**Comment by techievivek** [comment]
Not overdue, we are finishing up the payment.

**Comment by stephanieelliott** [comment]
> @ginsuma can you please share your Upwork profile? I'm not able to find you there.

Bump @ginsuma

**Comment by stephanieelliott** [comment]
All paid!
