### ISSUE TITLE
 Send money - Chat history goes blank and reloads when sending money in the chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Click + > Send money
4. Complete Send money process

## Expected Result:
Chat history will not go blank and reload

## Actual Result:
Chat history goes blank and reloads when sending money to chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/aca8ec4f-7d91-4a52-bb9c-e4ff9cb210a0

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbe74723c175d74f</li>
        <li>Upwork Job ID: 1712171235584786432</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by techievivek** [comment]
It seems to be a backend issue. Let me reproduce try to reproduce this to confirm.

**Comment by Christinadobrzyn** [comment]
Testing this, I think the bug might happen when you actually Send Money from the primary FAB button and not within a chat. 

The first test in the below video is sending money from a chat - no blinking.
The second test in the below video is sending money from FAB - blinking.

https://github.com/Expensify/App/assets/51066321/2befc0ac-3bc3-4988-9c2a-b14410166179

**Comment by techievivek** [comment]
I think it's not an issue with blinking(though we can definitely improve upon that), from the OP it looks like it is erroring out while loading the IOU report.

**Comment by techievivek** [comment]
Ok, I can confirm it is a backend issue. In some requests, we don't send the requestorEmail that's why it throws the error `New IOU report is missing an owner`. I am already working on a fix here: https://github.com/Expensify/Web-Expensify/pull/39174


https://github.com/Expensify/App/assets/35863227/8c4b24e1-8df8-460f-8abe-f0987dbb7af9

**Comment by mountiny** [comment]
I will unassign as Vivek got this, thanks!

**Comment by techievivek** [comment]
This is all done. It was worked internally.

**Comment by Christinadobrzyn** [comment]
Hi @techievivek, do we need to pay @jjcoffee for help on this or was it only internal eng?

**Comment by jjcoffee** [comment]
@Christinadobrzyn No payment needed for me!
