### ISSUE TITLE
[HOLD for payment 2023-12-12] [P2P Activation] [External] [HIGH] Update the report when a payment is refunded 

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#29319]
### **Update the report when a payment is refunded**

In [ReportActionItem.js](https://github.com/Expensify/App/blob/d61f55ac16b797f831e4cb1b9669ba326ac7b8f9/src/pages/home/report/ReportActionItem.js), add a handler for the REIMBURSEMENTDEQUEUED report action which will show: 

>Canceled the $%amount% payment, because %original recipient name% did not enable their Expensify Wallet within 30 days 

We’ll update the report preview to say “Canceled” instead of “Pending” if the cancellation reason is `CANCEL_REASON_PAYMENT_EXPIRED`

![image](https://github.com/Expensify/App/assets/22508290/6e1e0a8c-115b-4af4-a00b-bcb131cb963b)

UI Details:

- System message: canceled the $30 payment, because %original recipient name% did not enable their Expensify Wallet within 30 days 
- We’ll update the report preview to say “Canceled” instead of “Pending”
- We’ll hide the button to `Enable Wallet` in this case, since we’ve already refunded the payer.

**Comment by kevinksullivan** [comment]
@getusha here is the issue you'll be working on!

**Comment by kevinksullivan** [comment]
@MariaHCD @getusha updating this to weekly as we get closer. What's the latest here?

**Comment by MariaHCD** [comment]
We're making progress on the App PR: https://github.com/Expensify/App/pull/29344 We just need to iron out a few things and test it.

@getusha let me know what you think of my latest comment: https://github.com/Expensify/App/pull/29344#issuecomment-1807828887

**Comment by kevinksullivan** [comment]
@getusha any update here?

**Comment by rlinoz** [comment]
I am not sure why I was assigned, is there anything left to do here?

**Comment by rlinoz** [comment]
Oh, it is because of this https://github.com/Expensify/App/pull/29344#issuecomment-1834565888

**Comment by MariaHCD** [comment]
Nope, all good, @rlinoz

**Comment by MariaHCD** [comment]
App PR was merged: https://github.com/Expensify/App/pull/29344

Backend PRs:

- https://github.com/Expensify/Auth/pull/9299 (deployed to prod)
- https://github.com/Expensify/Web-Expensify/pull/39878 (deployed to staging)

**Comment by kevinksullivan** [comment]
@getusha lmk when you accept this job

https://www.upwork.com/jobs/~016bf7581475c5f395

**Comment by getusha** [comment]
@kevinksullivan accepted

**Comment by kevinksullivan** [comment]
All set
