### ISSUE TITLE
[$500] [HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] [P2P Activation] [External] [CRITICAL] Update pending Wallet state to show Enable Wallet button

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#29320]
Held on 
- https://github.com/Expensify/App/pull/26406
- https://github.com/Expensify/App/pull/26862

### **Update pending Wallet state to show `Enable Wallet` button**

Update the UI as per this mockup below. For Wallets that are in the SILVER tier. We’ll need to build off of [this PR](https://github.com/Expensify/App/pull/26862) that is adding the assigned card tile with Expensify card list to the Wallet page.

Clicking the `Enable wallet` button will redirect to the wallet KYC flow.

![image](https://github.com/Expensify/App/assets/22508290/f837515b-5ee3-4f27-9b43-db45f0a529e6)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d836dcba58f2381d</li>
        <li>Upwork Job ID: 1719513835432079360</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
@samh-nl here is your issue!

**Comment by MariaHCD** [comment]
This PR is also relevant since it is redesigning the wallet page: https://github.com/Expensify/App/pull/26406

**Comment by MariaHCD** [comment]
@samh-nl Hopefully, this PR that is this held on should be merged soon: https://github.com/Expensify/App/pull/26406

To clarify your [question](https://expensify.slack.com/archives/C01GTK53T8Q/p1697090592989959?thread_ts=1697033275.944009&cid=C01GTK53T8Q) regarding the `Enable wallet`:

We should redirect to the enable payments route. However, is it possible to redirect to the [KYCWall](https://github.com/Expensify/App/blob/6f533d6730a1fa71a4b1d7529cd7dfc53aef8e29/src/components/SettlementButton.js#L201) first? If the user clicks Enable wallet and they don't have a personal bank account, we'd want to redirect them to setup their bank account first. Once they have their bank account setup, we can direct them to the KYC flow at `ROUTES.SETTINGS_ENABLE_PAYMENTS`

Let me know what you think.

**Comment by kevinksullivan** [comment]
Let's just update the copy in all circumstances to say:

>We need to confirm the following information before you can send and transfer money from your Wallet.

**Comment by MariaHCD** [comment]
@kevinksullivan can we also get the Spanish copy 🙏🏼

**Comment by MitchExpensify** [comment]
Asked for Spanish here: https://expensify.slack.com/archives/C21FRDWCV/p1697468769301469

**Comment by kevinksullivan** [comment]
thanks!

**Comment by MariaHCD** [comment]
>  In other words: are these the right bank accounts we should check for?

Good question, we need to look for a valid deposit bank account i.e. a credit bank account. So the logic in `hasExpensifyPaymentMethod` is correct

**Comment by MariaHCD** [comment]
Okay, I think I found the issue: https://github.com/Expensify/App/issues/29714#issuecomment-1766453836

When checking if there's already a valid bank account, we should be checking if the user's wallet is linked to an existing deposit bank account, **not** if they have a default credit bank account.

@samh-nl I believe we will need the following changes:

```js
function hasExpensifyPaymentMethod(fundList: Record<string, Fund>, bankAccountList: Record<string, BankAccount>): boolean {
    const validBankAccount = Object.values(bankAccountList).some((bankAccountJSON) => {
        const bankAccount = new BankAccountModel(bankAccountJSON);
        return bankAccount.isLinkedToWallet();
    });
```

In BankAccount.js:

```js
/**
 * Is this the bank account that is linked to the user's wallet?
 *
 * @returns {Boolean}
 */
isLinkedToWallet() {
    return this.json.isDefault === true;
}
```

**Comment by MariaHCD** [comment]
> What I noticed when adding a PBA is that isDefault is not automatically set and I need to navigate away and go back to the wallet page for it to be fetched from the BE

I'll look into whether the BE is sending the isDefault prop after adding the PBA

**Comment by MariaHCD** [comment]
Yup, looks like the isDefault prop is not set after the PBA is added: 

![Screenshot 2023-10-17 at 7 20 23 PM](https://github.com/Expensify/App/assets/12268372/6a41036a-e044-4fbd-abbf-61df0d8ca4d8)


It's added only after the wallet page is opened:

![Screenshot 2023-10-17 at 7 21 00 PM](https://github.com/Expensify/App/assets/12268372/49d56fb4-94dc-4df7-a7fd-bc0661ad3cc1)

Looking into the backend fix for this.

**Comment by joelbettner** [comment]
I don't think we need to do anything in the back end to correct this. As long as there is one OPEN PBA, the user will have a bank account that is linked to the wallet. That is reflected in the PR^ above.

**Comment by MariaHCD** [comment]
Ignore ^ [the](https://github.com/Expensify/App/issues/30069) issue isn't a deploy blocker, we do not activate wallets set up with test data on staging.

**Comment by MariaHCD** [comment]
The [App PR](https://github.com/Expensify/App/pull/29573) was merged and deployed last week. @samh-nl just requires payment. Adding a BZ team member here.

**Comment by MariaHCD** [comment]
👋🏼 @alexpensify, we'll need payment to go out to @samh-nl for this [App PR](https://github.com/Expensify/App/issues/29320#issuecomment-1774424999).

cc: @kevinksullivan could you clarify what the payment amount is for this issue?

**Comment by alexpensify** [comment]
Ok, I'll wait for @kevinksullivan to share the payment summary. Thanks!

**Comment by alexpensify** [comment]
@mananjadhav please disregard this, I needed an Upwork link.

**Comment by alexpensify** [comment]
@samh-nl - can you please apply to this Upwork job and I can continue the payment process: 

https://www.upwork.com/jobs/~01d836dcba58f2381d

Thanks!

**Comment by alexpensify** [comment]
Thanks, I sent the offer in Upwork.

**Comment by alexpensify** [comment]
All set, I've completed the payment process in Upwork!
