### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] DEV : App crash when visiting Task's settings for the first time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** dev only
**Reproducible in staging?:** only in dev
**Reproducible in production?:** only in dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696933959561659

## Action Performed:
1. Go to any report.
2. Create a new task.
3. Click on task header => Choose Settings.
4. Notice app is crashed.
## Expected Result: 
App shouldn't be crashed while opening setting of Task
## Actual Result: 
App crash when visiting Task's settings for the first time

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/c670c20e-f517-44ba-a10c-60068bc4dbc8

https://github.com/Expensify/App/assets/38435837/02ea7193-202b-44ee-8d3b-07eefd6d584f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/0da8890e-84fe-4b02-b47e-61342d5a8e09

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbd96ea5f53ec4b8</li>
        <li>Upwork Job ID: 1712137881041838080</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27145434</li>
<li>hungvu193 | Contributor | 27145438</li>
<li>hungvu193 | Reporter | 27145441</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
Seems regression from https://github.com/Expensify/App/pull/28200 where we get rid of `shouldDisableSettings` which will show the settings for all report types. cc: @techievivek

**Comment by techievivek** [comment]
I see you have already added that, great.

**Comment by techievivek** [comment]
I will wait for @s77rt to officially review the proposal.

**Comment by s77rt** [comment]
@hungvu193 Thanks for the proposal! Your RCA is correct and the solution looks good to me as well 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29334#issuecomment-1758044351)

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/28200
- The offending PR has been commented on: https://github.com/Expensify/App/pull/28200#discussion_r1361302365
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by strepanier03** [comment]
Thank you, @s77rt for the checklist items. 

I was offline yesterday but I'm working on this and any needed payment steps now. Appreciate the patience everyone!

**Comment by strepanier03** [comment]
All right, everyone's been paid, contracts closed, and feedback left. 

Thanks again for working with the community and being such supportive and helpful members!
