### ISSUE TITLE
[HOLD for payment 2023-10-23] Send Money - Arrow is missing on date and merchant field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** no ( send money just implemented)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697005474290679

## Action Performed:
1. Click on FAB and select send money
2. Enter amount and select user
3. Click on show more

## Expected Result:
It should show arrow icon beside date and merchant

## Actual Result:
It does not show arrow icon

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Screenshot_20231011-123954_New Expensify Dev](https://github.com/Expensify/App/assets/93399543/dea925e4-c6b1-48b1-90e5-51ebeadc79b8)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![Screenshot_20231011_123148_Chrome](https://github.com/Expensify/App/assets/93399543/931d2d3b-753a-49ba-80f9-46c3f5f49571)

</details>

<details>
<summary>iOS: Native</summary>

 
![image (1)](https://github.com/Expensify/App/assets/93399543/889d0e1c-2884-4e9a-b31a-6fa8fccf7089)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![(10) New Expensify](https://github.com/Expensify/App/assets/93399543/dc5ab160-08a0-4f8e-b758-ee7cf5e5abed)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/32d484dc-d269-4160-abad-874f496c7d6e

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![image (2)](https://github.com/Expensify/App/assets/93399543/b44f8348-ffaf-40fe-b6ac-7ef949ac4394)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f1148f05a8f4e87</li>
        <li>Upwork Job ID: 1712176568336138240</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Taking this internally

**Comment by mountiny** [comment]
@alexpensify only $50 needed for @gadhiyamanan for reportinga

**Comment by mountiny** [comment]
No need for the checklist, deploy blocker was clear

https://github.com/Expensify/App/issues/29330#issuecomment-1763366152

**Comment by mountiny** [comment]
No need for the checklist, deploy blocker was clear

https://github.com/Expensify/App/issues/29330#issuecomment-1763366152

**Comment by mountiny** [comment]
@alexpensify only need to pay $50 to @gadhiyamanan

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter @gadhiyamanan $50  
-  Contributor that fixed the issue N/A 
-  Contributor+ that helped on the issue and/or PR N/A 

Upwork Job: https://www.upwork.com/jobs/~017f1148f05a8f4e87

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: Payment was confirmed here https://github.com/Expensify/App/issues/29330#issuecomment-1775385575

**Comment by alexpensify** [comment]
@gadhiyamanan - please accept in Upwork and I can complete the process. Thanks!

**Comment by gadhiyamanan** [comment]
@alexpensify offer accepted, thanks!

**Comment by alexpensify** [comment]
All set and paid in Upwork!
