### ISSUE TITLE
[$500] Notification emails are received immediately

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696962386748219

## Action Performed:
1. Send a message from A to B
## Expected Result:
Email notification not received for 10 min to account B
## Actual Result:
Email notification received immediately to account B
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/c77d72ff-2335-4620-bc4b-e21a0adf9699

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecc564d84e16f242</li>
        <li>Upwork Job ID: 1712164626661183488</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I would imagine this is going to need to be Internal @miljakljajic

**Comment by miljakljajic** [comment]
Apologies for the delay I was OOO Thursday and Friday last week. Making this internal and adding the engineering label.

**Comment by puneetlath** [comment]
I think @marcaaron just fixed this.

**Comment by marcaaron** [comment]
Yes it's on prod now so I think we can close it out.
