### ISSUE TITLE
[HOLD for payment 2023-10-27] [$250] Android - Send money - Send money deep link redirects to mobile browser instead of native app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No, feature is not available on production

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/request/new
from external app
2. Close New Expensify app
3. Navigate to https://staging.new.expensify.com/send/new
from external app

## Expected Result:
New Expensify app is launched and Send money page is opened

## Actual Result:
User is redirected to mobile browser

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/8ddd2655-7e38-48d9-9eff-339e9c885004

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01706f3bb756216f6d</li>
        <li>Upwork Job ID: 1712345825029959680</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27213523</li>
<li>hungvu193 | Contributor | 27213524</li>
</ul></li>
    </ul>
</details>

**Comment by jasperhuangg** [comment]
No need to block deploy on this, but we should keep it open and let people submit proposals.

**Comment by jasperhuangg** [comment]
cc @techievivek since this seems related to your recent Send Money PR

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@hungvu193 Do I need to have a different build version to test this? Atleast in android

I am using dev build ran from `npm run android` command? But none of the deeplinks is working for example `https://staging.new.expensify.com/search`

**Comment by abdulrahuman5196** [comment]
> the easiest way to test it is paste the url to message or notes then click on it. How do you test it?

@hungvu193 Doing the same not working for me. Both result in simulator and real device.


https://github.com/Expensify/App/assets/46707890/691aac28-8560-4be1-bde8-ff99403f2bbc

**Comment by abdulrahuman5196** [comment]
> hmm that weird 🤔
> 
> Can you test it with the command line?
> 
> ```js
> adb -s emulator-5554 shell am start -W -a android.intent.action.VIEW -d "new-expensify://settings" com.expensify.chat.dev
> ```
> 
> ` emulator-5554` is your device id

@hungvu193 

This command even works for `send/new` and same for `npx uri-scheme open new-expensify://send/new —android` command as well.

I am not able to reproduce the issue like, its working for other routes but not working only for the `send/new` route.

**Comment by abdulrahuman5196** [comment]
Only I am able to reproduce this issue in production builds not in dev builds. There could be something wrong with my setup.

But anyways, I did check the codes mentioned and the fix is similar to what we have done previously on new pages with deeplink. So I am fine with the proposal and can test in PRs with the builds itself.

🎀 👀 🎀
C+ Reviewed

cc: @techievivek

**Comment by techievivek** [comment]
Waiting for the payment to payment. @abdulrahuman5196 can you please fill the checklist by then, thanks.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression but a miss during send money implementation

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Navigate to https://staging.new.expensify.com/send/new from external app
2) Verify that it opens New Expensify app.

@garrettmknight

**Comment by garrettmknight** [comment]
Summary of payment for this issue:
- Urgency bonus: yes
- Contributor: @hungvu193 $375 paid via Upwork
- Reviewer: @abdulrahuman5196 $375 paid via Upwork

Upwork job: https://www.upwork.com/jobs/~01706f3bb756216f6d
