### ISSUE TITLE
[HOLD for payment 2023-10-23] Distance - The merchant is displayed on the distance request page but not on the request report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697045740106739

## Action Performed:
1. Open request money
2. Change tab to distance
3. Enter start and finish location
4. Select workspace
5. Notice the merchant value is shown
6. Send the request
7. Open the request

## Expected Result:
Merchant value should not be shown on the distance page or it should also be visible on the request report page

## Actual Result:
The Merchant value is displayed on distance request page but not on the request report page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/04f4a548-3b99-45ff-8479-8951bfbb40f4

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/2e767481-4cf8-41a6-abc6-f73e6feccd87

</details>

<details>
<summary>iOS: Native</summary>

 
![Screenshot_20231011-221159](https://github.com/Expensify/App/assets/93399543/f7e8fff9-4abc-44d0-8e76-894d8c7f0bfd)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![Screenshot_20231011-221313](https://github.com/Expensify/App/assets/93399543/40944a9d-638c-494c-a82f-f01dff61d2fe)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/f9490a27-8dee-4d30-8daf-08863f23b441

https://github.com/Expensify/App/assets/93399543/a732b6be-bd5b-4f87-8979-e63de2d6b846

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/5bdd8b6c-6b18-4ebb-b5f5-b1ff81c312b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f6b2700f396ce6a</li>
        <li>Upwork Job ID: 1712195602319327232</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
@kbecciv I think you mis-matched issue with the steps. Can you check?

**Comment by francoisl** [comment]
> @kbecciv I think you mis-matched issue with the steps. Can you check?

Yep those looked accidentally mixed up, I updated the steps.

**Comment by francoisl** [comment]
@youssef-lr I feel like this is coming from https://github.com/Expensify/App/pull/28710, it modified `MoneyRequestConfirmationList`. I'm thinking we can edit [this line](https://github.com/Expensify/App/blob/72a11ca5a45d5eb318d8ae9558f0fdc4aa3161ed/src/components/MoneyRequestConfirmationList.js#L574-L574) so it doesn't show the merchant item for distance requests. Does that sound good?

**Comment by francoisl** [comment]
These [2 elements](https://github.com/Expensify/App/blob/72a11ca5a45d5eb318d8ae9558f0fdc4aa3161ed/src/components/MoneyRequestConfirmationList.js#L563-L584) are pretty the same except for the description and route to navigate to on click, so it makes senes to hide the second one for distance requests. I'll send a PR shortly.

**Comment by mallenexpensify** [comment]
Issue reporter: @jo-ui due $50 via Upwork
Contributor: N/A 
Contributor+: @ntdiary due $500 via Upwork. 

 @jo-ui and @ntdiary , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019f6b2700f396ce6a

Also...  @jo-ui, nice suit in your profile pic!

**Comment by jo-ui** [comment]
> Issue reporter: @jo-ui due $50 via Upwork
> Contributor: N/A 
> Contributor+: @ntdiary due $500 via Upwork. 
> 
>  @jo-ui and @ntdiary , can you please accept the job and reply here once you have? 
> https://www.upwork.com/jobs/~019f6b2700f396ce6a
> 
> Also...  @jo-ui, nice suit in your profile pic!
> 
> 

@mallenexpensify thank you, I've accepted the offer on upwork

**Comment by mallenexpensify** [comment]
Thanks @ntdiary and @jo-ui , you've both been paid, updated the comment above has been updated to show payment
