### ISSUE TITLE
Chat – Duplicate emojis on reaction to message if change skin tone and press same emoji badge

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. Navigate to a conversation that already has some messages
4. Click on the button to select an emoji to react the message
5. Select any emoji from the list
6. Change the skin tone
7. Select the same emoji from the list as in step 5

## Expected Result:
The first emoji badge is dismissed

## Actual Result:
New reaction button is displayed next to the reaction badge duplicate previously emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop
- [x] Windows: Chrome

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/b3ed1c71-e6f0-4aee-a0be-31cb86cd3d81

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
<img width="452" alt="Screenshot 2023-10-12 at 2 31 49 PM" src="https://github.com/Expensify/App/assets/78416198/bd7d9c68-e633-4b07-8d03-19b08d6e9649">

Not a bug as slack also does the same thing.

**Comment by alexpensify** [comment]
I've run out of time and will have to test over the weekend.

**Comment by alexpensify** [comment]
I'm going to need to start a team discussion since I can replicate the experience. We need to discuss what's best or if we want to take a different approach.

**Comment by alexpensify** [comment]
Here is how this looks in Chat now: 

On the left is my reply and on the right is the other person who reacted months ago. 

![2023-10-17_17-03-26](https://github.com/Expensify/App/assets/8107070/8acb0ab4-1393-428b-a469-e83b057c4ffb)

**Comment by alexpensify** [comment]
I started a discussion here: 

https://expensify.slack.com/archives/C03U7DCU4/p1697751157224439
