### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500]  DEV: Console error on open avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.81.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697023503044389

## Action Performed:
1. go to any chat
2. click on header
3. open profile pic in full view

## Expected Result:
It should not show console error

## Actual Result:
Console error appears (Removing a style property during rerender (outline) when a conflicting property is set (outlineStyle) can lead to styling bugs)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/47d5b2ae-60b4-42af-821c-9cc89565bcbb

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/a1370122-1478-4d94-87af-ef07e42d1b70

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01551e5f725f11a172</li>
        <li>Upwork Job ID: 1712205642944548864</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>saranshbalyan-1234 | Contributor | 27163924</li>
<li>gadhiyamanan | Reporter | 27163926</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by peterdbarkerUK** [comment]
Summarizing payouts for this issue:

Issue reporter: @gadhiyamanan  $50 (paid)

Contributor: @saranshbalyan-1234  $750 (inc urgency bonus, paid)

Contributor+: @parasharrajat  $750 (inc urgency bonus) - please request payment via NewDot.

**Comment by peterdbarkerUK** [comment]
Will re-assign Jason once the regression checklist is complete, my mistake (and proposed [a fix](https://expensify.slack.com/archives/C01SKUP7QR0/p1698158437924539?thread_ts=1689951482.808529&cid=C01SKUP7QR0))

**Comment by peterdbarkerUK** [comment]
Thanks @parasharrajat - if you haven't already, please send a $750 payment request via NewDot

**Comment by JmillsExpensify** [comment]
$750 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/29386#issuecomment-1777306150).
