### ISSUE TITLE
[$500] All - IOU - Distance expense preview image truncates the driving route

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Open https://staging.new.expensify.com/

2. Sign in onto an account (log out and then sign in again just to clear Onyx)
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Distance'
6. Add a route from point 1 to point 2
1) 123 W Main St, Independence, KS 67301, USA
2) 321 Westminster Pl, Independence, KS 67301, USA
7. Click on the "Next" button
8. Select any WS
9. Complete the IOU
10. Go to the details of the created IOU
11. Open the preview image of the route(Receipt)

## Expected Result:
The route from the start to the final point should be displayed in the Distance Preview Expense Image

## Actual Result:
Distance expense preview image truncates the driving route.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/db2545bd-e12d-4033-a992-953e56102ffb

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2943f14ecf6a26b</li>
        <li>Upwork Job ID: 1712216297305300992</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
AFAIK, the map snapshots for the Distance Request previews are made on the BE, so this might be a BE issue.

**Comment by jliexpensify** [comment]
cc @hayata-suenaga - is this an `internal` issue?

**Comment by rakshitjain13** [comment]
In the frontend this issue was fixed by this PR (https://github.com/Expensify/App/pull/28416), the same thing has to be done on the backend side as snapshots are generated there.

**Comment by jliexpensify** [comment]
Hi @pecanoro - it looks like a few Contributors have [flagged this](https://github.com/Expensify/App/issues/29390#issuecomment-1759294638) as an `Internal` issue. Thanks!

**Comment by pecanoro** [comment]
Created a WIP PR to fix this after identifying the problem.

**Comment by pecanoro** [comment]
PR is still on review!

**Comment by pecanoro** [comment]
Oh this has been solved internally already, closing!

**Comment by jliexpensify** [comment]
Thanks Rocio, Upworks job removed!
