### ISSUE TITLE
[$500] mWeb-IOU- In distance request, merchant section shows distance@rate/mile

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon
4. Select request money --- Distance
5. Enter start and finish way points
6. Tap next and note "distance" and "merchant" section

## Expected Result:
The "distance" section must show [distance@rate/mile](mailto:distance@rate/mile)
and "merchant" section must be empty.

## Actual Result:
The "distance" and "merchant" section shows the same details [distance@rate/mile.](mailto:distance@rate/mile.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/690cbb62-6abe-46a6-a2cb-bac6c635532f

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f20eff3688173d74</li>
        <li>Upwork Job ID: 1712385069405523968</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This is fixed in staging
<img width="376" alt="image" src="https://github.com/Expensify/App/assets/36083550/8b9870cc-b78a-4d49-bbb6-e1805930e00f">
