### ISSUE TITLE
[HOLD for payment 2023-10-23][$125]  Send money - Avatars and names overlap in Send money report details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29439]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team/  @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697098677979179

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Send money
3. Send money to any user
4. Click on the IOU preview to open report page
5. Click on the avatar on the header
Note that the avatars and names overlap in Send money details page

## Expected Result:
The avatars and names do not overlap in Send money details page

## Actual Result:
The avatars and names overlap in Send money details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/86e6186a-90be-46c1-99cb-8731de3344f8

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf850787ca824440</li>
        <li>Upwork Job ID: 1712525329990500352</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27165440</li>
<li>hungvu193 | Contributor | 27165444</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
@hungvu193 It is not from my PR as it is also reproduced in the staging. My [PR](https://github.com/Expensify/App/pull/28323) is not deployed to the staging yet.

**Comment by Pujan92** [comment]
I see it is added [here](https://github.com/Expensify/App/commit/97a33071f0a8dcf071e92484f465f2f3261b1f8a#diff-e6d88edc852b55f3ee47d3c1cb04ac4db9d9f5919abdb25f557049aaa189b09aR87-R89) cc: @fedirjh 

Seems like a bad merge but not able to find out where it is missed 😅, would be great if someone helps what happened exactly in this history https://github.com/Expensify/App/commits/main/src/components/MultipleAvatars.js

**Comment by akinwale** [comment]
@hungvu193's [proposal](https://github.com/Expensify/App/issues/29439#issuecomment-1759680959) correctly identifies the source of the problem, and the recommended fix is straightforward.

🎀 👀 🎀 C+ reviewed.

**Comment by mountiny** [comment]
I can take this one @joelbettner 

@hungvu193 can you raise a PR with priority?

**Comment by Pujan92** [comment]
In case @hungvu193 is unavailable, I can raise a quick PR for this.

**Comment by Pujan92** [comment]
Sorry @fedirjh but not getting you exactly. Do you mean that the PR https://github.com/Expensify/App/pull/28323 has been already deployed to staging?

**Comment by Pujan92** [comment]
Yes, you are right. It's a bad merge main within my PR.

**Comment by Pujan92** [comment]
> > Seems like a bad merge but not able to find out where it is missed 😅, would be great if someone helps what happened exactly in this history
> 
> One possible scenario in my mind is that you created your PR branch from a previous main, and when you merged `main` you dismissed the extra change as you already have moved these changes to a new location

Exactly that happened!

**Comment by Pujan92** [comment]
As it is clear that regression comes from the [bad merge main](https://github.com/Expensify/App/issues/29439#issuecomment-1760252542) within my PR, I have raised a [PR](https://github.com/Expensify/App/pull/29483)

**Comment by mountiny** [comment]
Thanks, merging the Pr, updating the assignees here

**Comment by mountiny** [comment]
fixed 
<img width="473" alt="image" src="https://github.com/Expensify/App/assets/36083550/cef86d7a-3d7d-48c6-b353-dfefd88379d8">


I think we can proceed with payment to @aman-atg for reporting $50

**Comment by mountiny** [comment]
No other payment required on this PR @dylanexpensify

**Comment by mountiny** [comment]
Sorry @hungvu193 just cancel the offer this time. The PR author fixed it.

**Comment by mountiny** [comment]
No need for checklist i think, the pr author foxed it so where this came from is clear and it was a simple fix

**Comment by mountiny** [comment]
@dylanexpensify this was reviewed internally too so only payment needed is $50 to @aman-atg for reporting

**Comment by mountiny** [comment]
Deploy blocker, regression was clear and we have raised it above, no need for the checklist or special regression test, only payment to the bug reporter

**Comment by mountiny** [comment]
@dylanexpensify ready for payment

**Comment by dylanexpensify** [comment]
on it now!

**Comment by dylanexpensify** [comment]
done

**Comment by dylanexpensify** [comment]
ah paying now!

**Comment by dylanexpensify** [comment]
done!
