### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] Workspace - Member list does not show in Invite new members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697103282087049

## Action Performed:
1. Create new account
2. Start a chat with users
3. Create workspace
4. Go to settings > workspace >member > invite

## Expected Result:
It  should show members list

## Actual Result:
It does not show member list

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary> 

 

https://github.com/Expensify/App/assets/93399543/93a76b3a-850e-40b1-b10d-1cfb01b27903

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/36a1e9f6-aaf3-4c77-9123-ca149bbafc27

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/2e16dc89-f97a-4e8d-9862-c836edb0a65b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/01db0cbc-9478-49f3-9483-beb40fca9883

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/46a7c87d-32ff-4b3e-b48d-6db641ce8ea5

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/d2f07f4b-82a8-495e-aa30-cd4f4ab1ed35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Samueljh1** [comment]
My mistake. We can fix this with
`let emails = _.compact(
            searchTerm
                .trim()
                .replace(/\s*,\s*/g, ',')
                .split(','),
        );

        if (emails.length === 0) {
            emails = [''];
        }`

@francoisl

**Comment by mountiny** [comment]
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/36083550/7380d0a4-2da2-4cd0-b909-4a16b8cfbfd5">
 
works!

**Comment by mountiny** [comment]
We will just need to pay $50 to @gadhiyamanan for reporting otherwise this was handled as a regression

**Comment by johncschuster** [comment]
Welp, that didn't work. I'll handle the payment manually.

**Comment by johncschuster** [comment]
@mananjadhav, I've invited you to [the job](https://www.upwork.com/ab/applicants/1716930835020460032/job-details). Can you please accept that? Thank you!

**Comment by gadhiyamanan** [comment]
@johncschuster offer accepted, thanks!

**Comment by johncschuster** [comment]
Payment has been issued!
