### ISSUE TITLE
[$500] Chat - Quote in first line with empty text,side vertical line is not shown & disappear on edit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on any report
3. Enter
![image](https://github.com/Expensify/App/assets/78819774/46ff8f57-8c19-4638-ad2d-e90d51fdada9)

4. Tap Send
5. Long press the sent message and tap edit comment

## Expected Result:
When Quote markdown is added for first line with empty text, side vertical line is not shown and disappears while editing. But quote markdown added in middle of multi line quote message, side vertical line is shown and quote symbol shown while editing. The behavior must not be inconsistent. In both places, the behavior must be the same

## Actual Result:
When Quote markdown is added for first line with empty text, side vertical line is not shown and disappears while editing. But quote markdown added in middle of multi line quote message, side vertical line is shown and quote symbol shown while editing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/fb00a1e2-7ee5-4618-ad61-617b80398ccb

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faf88387c3785531</li>
        <li>Upwork Job ID: 1712539303132860416</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
I can't reproduce this on chrome staging - @lanitochka17 are you primarily seeing this with Android?

**Comment by eh2077** [comment]
This is not a bug. The starting or ending empty rows of non-empty quotes are trimmed, see https://github.com/Expensify/expensify-common/pull/521
