### ISSUE TITLE
[$250] Request/split money description preview is not truncated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696863093475949

## Action Performed:
1. Go to a chat with another person.
2. Click on request money.
3. Enter an amount.
4. Enter a very long description.
5. Go to the request preview
## Expected Result:
The request preview should be truncated to include limited text
## Actual Result:
The request preview is not truncated and can include a very big description
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/9d784762-be9c-49cd-87ae-899969d8e634

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/46700bd6-c321-4290-8cc6-b210c565ee8d

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/1194de7c-3365-4e15-86b9-aa18b55da20d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/0fd935d4-2a3f-432e-a708-b3db02cae93c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/a6347b4e-0871-4465-8c3e-cc8a146d7c5f

https://github.com/Expensify/App/assets/38435837/1c144c30-bb28-4796-96f4-1f64be4da9cc

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/84737ab3-e672-4f00-bb6b-161e9a57a249

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4eeb2d00d152256</li>
        <li>Upwork Job ID: 1712488709391478784</li>
        <li>Last Price Increase: 2024-03-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27221035</li>
<li>esh-g | Reporter | 27221037</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
# Proposal by @esh-g 

## Please re=state the problem
Request/split money description preview is not truncated

## What is the root cause of the problem?
There is no logic to truncate the description preview in request/split money.

## What changes should be made to fix this?
We should add the `numberOfLines={3}` attribute to the `Text` components for description as well as merchant in `MoneyRequestPreview.js`.
https://github.com/Expensify/App/blob/d4b0a245a4f7ab41d67bf718ea078cb7859cb748/src/components/ReportActionItem/MoneyRequestPreview.js#L310
https://github.com/Expensify/App/blob/d4b0a245a4f7ab41d67bf718ea078cb7859cb748/src/components/ReportActionItem/MoneyRequestPreview.js#L318

setting the max lines to 3 is only a suggestion, but we can set it to any desirable number

**Comment by esh-g** [comment]
This was decided as a separate bug here: https://github.com/Expensify/App/issues/28073#issuecomment-1753038928

**Comment by youssef-lr** [comment]
Closing in favor of https://github.com/Expensify/App/issues/28073

**Comment by esh-g** [comment]
@youssef-lr could you please see the comment I linked above, it was decided as a separate bug there

**Comment by esh-g** [comment]
Bump @youssef-lr Please see that bugs are different

**Comment by youssef-lr** [comment]
Ah yes. So my PR which was merged has fixed the issue I linked. We'll need to fix the preview now right?

**Comment by situchan** [comment]
Right. Can I take over C+ here as I discussed with design team and have full context in https://github.com/Expensify/App/issues/28073.

**Comment by zanyrenney** [comment]
Yes, that makes sense. I also see no comments or work from @mollfpr yet so this seems fair.

**Comment by zanyrenney** [comment]
seeing as you proactively asked to take this over @situchan please can you work on it with urgency and help review the proposals above? If none are suitable, please tell me so we can get more eyes on this.

**Comment by situchan** [comment]
@esh-g can you make sure that the solution works in all platforms?

**Comment by esh-g** [comment]
<details>
<summary>ios/safari</summary>

https://github.com/Expensify/App/assets/77237602/e10d0175-cf8f-4494-8ad2-bde356fbd276

</details>

<details>
<summary>android/chrome</summary>

https://github.com/Expensify/App/assets/77237602/d761d20b-061e-47d2-97d3-e540f76b57ca

</details>

<details>
<summary>android/native</summary>

https://github.com/Expensify/App/assets/77237602/d8886b98-672e-4dbe-8cdd-a15340c43321

</details>

**Comment by situchan** [comment]
@esh-g's [proposal](https://github.com/Expensify/App/issues/29459#issuecomment-1759825081) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by zanyrenney** [comment]
Hey team, I'm getting a buddy check on this in the end. I reeviewed the video of the bug again and it seems like a very unexpected workflow to have a description that is that long.

**Comment by zanyrenney** [comment]
Hey everyone. After reviewing this with a buddy check from fellow BZ team member, we think we should be closing this. 

- it is not s typical flow because the description being that long is not expected. there is no real life case we have seen with a description in that length
- the request doesn't fail- it's just not truncated, which feels like UI polish
- the fix from @youssef-lr solves any of the actual "technical" issues

Thanks!

**Comment by esh-g** [comment]
@zanyrenney I think if you look at this issue: https://github.com/Expensify/App/issues/28073#issuecomment-1753038928
This was based on the fact of having a long description... Moreover, I think a long description is realistic if consider a case where a contract of the payment terms or work is sent.
@youssef-lr Would like your opinion on this as well

**Comment by esh-g** [comment]
gentle bump @zanyrenney @youssef-lr @situchan

**Comment by situchan** [comment]
This issue was raised based on @shawnborton's feedback - https://github.com/Expensify/App/issues/28073#issuecomment-1752981267

**Comment by youssef-lr** [comment]
Sounds good @esh-g @situchan. Adjusting price here as this is a simple fix.

**Comment by zanyrenney** [comment]
Thanks @youssef-lr !

**Comment by esh-g** [comment]
I would once ask to reconsider the bounty on this one since it ended up taking a lot longer than expected mainly due to input delays... and it wasn't such a minor bug as expected...

**Comment by esh-g** [comment]
gentle bump @zanyrenney @situchan on the above ^

**Comment by zanyrenney** [comment]
@youssef-lr, please can you review as Joel has left, and I'd like an engineer's input. I'm assigning you to take a look, please!

**Comment by youssef-lr** [comment]
Makes sense @esh-g, adjusted.

**Comment by zanyrenney** [comment]
thanks @youssef-lr ❤️

**Comment by zanyrenney** [comment]
**payment summary**
paid @esh-g - $250
paid @situchan $250
