### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Distance -  Map initially starts from "San Francisco" even if waypoints are available

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.81-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697039744048349

## Action Performed:
1. Request money > Select distance tab
2. Select "Dhaka, Bangladesh" as start point
3. Select "Bangalore, Karnataka, India" as finish point
4. Press next & select any workspace
5. Observe map loads from "Dhaka"
6. Select "Distance" tab
7. Observe map initially loads from "San Francisco"

## Expected Result:
The available waypoint should be the initial location if available.

## Actual Result:
The initial location is always "San Francisco"

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/9b635414-be29-41dd-8610-d7aeef2490f8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a17fd81e-ef25-4bc6-a793-45c2c9a75ea8

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/3c983431-da25-472c-a01a-984ba7878cea

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/686a84a8-4f3f-4d3c-b945-cc2379c20b58

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/63404b84-77bd-44f6-aaee-b3dabace5269

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/4f965bf5-a010-4126-a2a0-43cbddadec92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6e45942a56ff196</li>
        <li>Upwork Job ID: 1712520876286824448</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27225793</li>
<li>Krishna2323 | Contributor | 27225797</li>
<li>krishna2323 | Reporter | 27225800</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Map initially starts from "San Francisco" even if waypoints are available

### What is the root cause of that problem?
The initial location is always set to `location: CONST.MAPBOX.DEFAULT_COORDINATE` in `DistanceRequestFooter`.

### What changes do you think we should make in order to solve the problem?
We should use `lodashGet` to get the location of waypoints if they are in state.

`location: lodashGet(waypointMarkers, [0, 'coordinate'], CONST.MAPBOX.DEFAULT_COORDINATE)`


### Result

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍. Please comment and tag me again so you can be assigned.

**Comment by s77rt** [comment]
https://github.com/Expensify/App/issues/29471#issuecomment-1760280379

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29471#issuecomment-1760053850)

**Comment by s77rt** [comment]
@jasperhuangg https://github.com/Expensify/App/issues/29471#issuecomment-1760333537

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/25161
- The offending PR has been commented on: https://github.com/Expensify/App/pull/25161#discussion_r1366221788
- A discussion in #expensify-bugs has been started: I don't think this is needed for this case
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Request money > Select distance tab
2. Select "Dhaka, Bangladesh" as start point
3. Select "Bangalore, Karnataka, India" as finish point
4. Press next & select any workspace
5. Verify map loads starting from "Dhaka, Bangladesh"
6. Select "Distance" tab
7. Verify map loads starting from "Dhaka, Bangladesh"

**Comment by mallenexpensify** [comment]
Issue reporter: @Krishna2323 paid $50 via Upwork
Contributor: @Krishna2323 paid $750 via Upwork, inc. urgency bonus
Contributor+: @s77rt via Upwork, inc. urgency bonus

Regression Test - https://github.com/Expensify/Expensify/issues/330239

Thanks y'all!
