### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] Inconsistency when clicking on the room avatar

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697102736759189

## Action Performed:
1. Create a public room and copy URL
2. Send a message
3. Hover on message and click reply in thread
4. Send a message in thread
5. Logout and open the room
6. Click open thread of message in the room
7. Click on avatar on header, see open room detail
8. Click on avatar on footer, see open the profile page
## Expected Result:
Open room detail when click room avatar footer
## Actual Result:
Open profile detail when click room avatar footer
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/832c0323-e8f3-43bf-b550-096fda9df647

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/aea8c460-7433-4e17-b183-5ba2f5a66e5f

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/107c6632-7a7f-48d4-bb16-61d36e1808fe

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

https://github.com/Expensify/App/assets/38435837/13ddd15a-6106-4006-8308-bd521afca10e

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/3064e3d8-ead5-4ec3-99f6-d11e39b6ef43

https://github.com/Expensify/App/assets/38435837/39a4a154-cdb9-4c7b-9422-f8d93341a42d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/7b9f94c8-dcc2-4cba-9c04-25a6b4aaf9e2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d73ef1f708111770</li>
        <li>Upwork Job ID: 1712560508209545216</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 27188871</li>
<li>namhihi237 | Reporter | 27188873</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
Open room detail when clicking the room avatar on the footer
### What is the root cause of that problem?
In `AnonymousReportFooter` we use `AvatarWithDisplayName` to show the room avatar here
https://github.com/Expensify/App/blob/6c7ee53c4d8a287cddbc7fa25afee548bf999e01/src/components/AnonymousReportFooter.js#L35-L39
In the `AvatarWithDisplayName` component we miss passing `shouldEnableDetailPageNavigation` prop to show the detail room.
### What changes do you think we should make in order to solve the problem?
We should pass `shouldEnableDetailPageNavigation` prop into `AvatarWithDisplayName`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by francoisl** [comment]
Seems pretty straightforward, let's go with that 👍

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

-  External issue reporter - @namhihi237 $50 payment issued in Upwork 
-  Contributor that fixed the issue - @namhihi237 $550 payment issued in Upwork 
-  Contributor+ that helped on the issue and/or PR - @thesahindia $500, please request in newdot

**Comment by laurenreidexpensify** [comment]
@thesahindia bump on checklist thanks

**Comment by laurenreidexpensify** [comment]
@thesahindia can we get this one wrapped up today? Thanks!

**Comment by JmillsExpensify** [comment]
$750 payment approved based on [this summary](https://github.com/Expensify/App/issues/29488#issuecomment-1777000956).
