### ISSUE TITLE
 IOU-In distance request, app crashes while tapping "Replace receipt"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money---Distance
4. Enter start and finish waypoints and tap next
5. Select a Workspace
6. Tap Request amount
7. Tap on the IOU transaction to open IOU detail page
8. Tap the receipt
9. Tap 3 dots on top right corner
10. Tap "Replace"

## Expected Result:
In receipt page, when user taps on "Replace", the app must not crash

## Actual Result:
In receipt page, when user taps on "Replace", the app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/5c1f5229-93fd-4f69-9055-f5d3777094ee

[logs.txt](https://github.com/Expensify/App/files/12887054/logs.txt)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
I was able to reproduce this on iOS native v 1.3.83.8

**Comment by jasperhuangg** [comment]
@hoangzinh were you pointing to the staging or production API when you did that test?

**Comment by mountiny** [comment]
I could not repro in latest native ios @hoangzinh can you repro in android?

**Comment by kbecciv** [comment]
Issue is not reproducible on build 1.3.83.10

https://github.com/Expensify/App/assets/93399543/ad393db3-9f56-499f-973e-99e00b089c06

**Comment by mountiny** [comment]
Appreciated, thanks!

**Comment by mountiny** [comment]
Reported internally and fixed internally, closing
