### ISSUE TITLE
[$500] Android - Login - App crashes when tapping 'Use recovery code' and 'Use 2FA code' very quickly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29195

## Action Performed:
1. Go to staging.new.expensify.com
2. Enter email of account with 2FA enabled
3. Enter magic code
4. Tap 'Use recovery code' and 'Use two-factor authentication code' repeatedly and very quickly

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/306e10ff-b681-45e8-a70d-2b9558eadb0d

[logs 2.txt](https://github.com/Expensify/App/files/12887190/logs.2.txt)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e906cb1857dd9981</li>
        <li>Upwork Job ID: 1712880291229278208</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by joelbettner** [comment]
@hoangzinh what are your thoughts here?

**Comment by jasperhuangg** [comment]
Doesn't need to block deploy, honestly doesn't really need to be fixed

**Comment by joekaufmanexpensify** [comment]
Similar to Jasper, I'm also dubious as to whether we need to do anything to fix this at all. This doesn't seem like something an actual user would ever do.

**Comment by joelbettner** [comment]
Hmm...this is weird. I don't know how the `input.current` could be `null` on line 52 given that we check for it just above on line 46.

https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L43-L53

@joekaufmanexpensify I know it is unlikely that a user will rapidly change between the two options that quickly, but this might be a good one to make external. I'm just thinking we want to make sure there isn't some sort of race condition when focusing that could cause the app to crash. 🤷‍♂️ I'll defer to your judgement.

**Comment by joelbettner** [comment]
Spoke with @tgolen about this 1:1. I believe all we need to do is put a check for `!input.current` inside the `setTimeout` callback and we will be able to avoid this race condition.

**Comment by joelbettner** [comment]
This should be a very easy fix (I've already outlined the solution in my comment above). I'm going to leble as external.

**Comment by joekaufmanexpensify** [comment]
Sounds good to me. Thanks @joelbettner !

**Comment by pradeepmdk** [comment]
> Thanks @hoangzinh! Hmm...this is weird. I don't know how the `input.current` could be `null` on line 52 given that we check for it just above on line 46.
> 
> `Cannot read property 'focus' of null` `BaseTextInput.js (52:64)`
> 
> https://github.com/Expensify/App/blob/9e19e40aef0f303ab5d5fc1c9cf8c9caf86a8098/src/components/TextInput/BaseTextInput.js#L43-L53
> 
> @joekaufmanexpensify I know it is unlikely that a user will rapidly change between the two options that quickly, but this might be a good one to make external. I'm just thinking we want to make sure there isn't some sort of race condition when focusing that could cause the app to crash. 🤷‍♂️ I'll defer to your judgement.

@joelbettner this code not yet in the staging can we wait until this PR goes to staging 
https://github.com/Expensify/App/pull/29339

**Comment by abdulrahuman5196** [comment]
>this code not yet in the staging can we wait until this PR goes to staging
https://github.com/Expensify/App/pull/29339
because this issue before this PR merged


The above mentioned PR is merged and I am unable to repro the issue in latest main. We can close this issue @joekaufmanexpensify

**Comment by joekaufmanexpensify** [comment]
Sounds good! Closing.
