### ISSUE TITLE
 Scan - Split bill - Empty merchant field does not show error message in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29064
## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to + > Request money > Scan > Upload a receipt
4. Select Split on any user
5. Create the bill split
6. Click on the bill split preview
7. Click Split
7. Edit the fields with error message which are Amount and Date
8. Click Split

## Expected Result:
In Step 7, Amount, Date and Merchant fields will show error message

## Actual Result:
In Step 7, only Amount and Date fields show error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/e9f8ea24-04ec-4632-9672-eb36c1c72535

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dcd4b4068835b24</li>
        <li>Upwork Job ID: 1712746926499971072</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Discussed here, not a blocker https://expensify.slack.com/archives/C01GTK53T8Q/p1697146393007749?thread_ts=1697144865.452089&cid=C01GTK53T8Q

Might be fixed by @youssef-lr PR

**Comment by youssef-lr** [comment]
Working on a clean up PR and will get this fixed there as well.

**Comment by trjExpensify** [comment]
Putting this one as high as the experience we're shooting for uses receipts, so merchants should be shown when scanned.

**Comment by youssef-lr** [comment]
This should be fixed now in main!

**Comment by CortneyOfstad** [comment]
@mountiny @youssef-lr are we good to close this, since the PR fixes this issue? TIA!

**Comment by youssef-lr** [comment]
Yup! But I'd wait until PR is deployed.

**Comment by youssef-lr** [comment]
We should be good now.
