### ISSUE TITLE
IOU - As admin if opens chat, money transaction is blank& in amount space only tick mark is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Login as employee
3. Tap on chat DM 1:1 with admin
4. Tap plus icon
5. Select send money
6. Enter an amount
7. Tap next
8. Tap Pay elsewhere
9. Login as admin in other device
10. Tap on 1:1 DM with employee
11. Tap on the IOU transaction (money which is sent)
12. Note blank space is shown instead of IOU amount details
13. Tap on the the skeleton IOU

## Expected Result:
User must be able to see the amount, skeleton IOU must not be shown and tapping on it, amount should be shown along with green tick mark

## Actual Result:
User can see only skeleton IOU and tapping on it, amount is not shown along with green tick mark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/891de1c2-35d5-4a14-ab80-efe4ea5dcfe6

https://github.com/Expensify/App/assets/78819774/8b682d9a-048c-4e98-a165-bf8a3f611d27

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I'm OOO Oct 16-23. Adding leave buddy

**Comment by joekaufmanexpensify** [comment]
Sounds good, I will triage!

**Comment by joekaufmanexpensify** [comment]
I just tried, and I'm unable to reproduce this, so going to close!
