### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Skeleton loader no longer has gradient animation

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697130116067009

## Action Performed:
Open up the app and wait for your chats list and chat content to load
## Expected Result:
The skeleton loader that acts as the placeholder while content loads should have a subtle gradient animation
## Actual Result:
There is no animation
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

![image (2)](https://github.com/Expensify/App/assets/38435837/871adc51-7e65-40b5-8469-f78d651bb9af)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c95171227c9c77b5</li>
        <li>Upwork Job ID: 1712587975218712576</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Nice! Do you have any idea how this bug got introduced in the first place?

**Comment by lschurr** [comment]
@thesahindia could you review the proposal?

**Comment by lschurr** [comment]
Are you able to help with this one @situchan?

**Comment by situchan** [comment]
> I think the recent changes broke the webpack config of react-content-loader.

@hungvu193 are you able to find which PR broke animation?

I think at least a few months animation didn't work.

**Comment by hungvu193** [comment]
> > I think the recent changes broke the webpack config of react-content-loader.
> 
> @hungvu193 are you able to find which PR broke animation?
> 
> I think at least a few months animation didn't work.

I checked the recent changes, the config of webpack didn't update for almost a year, so I'm little confused as well.

**Comment by situchan** [comment]
@hungvu193's [alternative solution](https://github.com/Expensify/App/issues/29508#issuecomment-1760685535) looks good to me.
I don't see the need of import alias for react-content-loader.
🎀 👀 🎀 C+ reviewed

**Comment by joelbettner** [comment]
@situchan I think that proposal from @hungvu193 looks good to me.

**Comment by lschurr** [comment]
@situchan can you work on the checklist for this one?

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: Internal (no payment needed)
- Contributor: @hungvu193 $500
- Contributor+: @situchan $500

**Comment by lschurr** [comment]
@hungvu193 @situchan - could you apply here? https://www.upwork.com/jobs/~01c95171227c9c77b5

**Comment by situchan** [comment]
I am not sure when we broke this. I think this bug existed from the beginning when we implemented skeleton in https://github.com/Expensify/App/pull/8042.

### Regression Test Proposal

1. Login any account
2. Open any chat
3. Switch to any other chat
4. Verify that the skeleton loader that acts as the placeholder while content loads has a subtle gradient animation

**Comment by lschurr** [comment]
Great! Just need @situchan and @hungvu193 to apply here: https://www.upwork.com/jobs/~01c95171227c9c77b5

**Comment by lschurr** [comment]
- Offer sent to @hungvu193 
- @situchan could you apply to the job?

**Comment by lschurr** [comment]
All paid. Closing.
