### ISSUE TITLE
[$500] All participants are displayed into the room name which doesn't get truncated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697125883138209

## Action Performed:
Go to a workspace chat and open the details panel
## Expected Result:
Room name and details are easily seen and truncated if the room name is too long
## Actual Result:
All room participants are dumped into the room name which doesn't get truncated
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![image](https://github.com/Expensify/App/assets/38435837/df875a09-634a-4647-9227-ea6a6bcd11af)
![image (1)](https://github.com/Expensify/App/assets/38435837/9d062f60-3083-499c-9f17-df11a3f10f46)

![Full Screen #13](https://github.com/Expensify/App/assets/38435837/bd07e16b-8c3a-4e2d-91a7-fafa854cdfa8)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013cba0507a16f71f7</li>
        <li>Upwork Job ID: 1712580598513602560</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by johnmlee101** [comment]
This is a regression, since its not on Prod

**Comment by akinwale** [comment]
This is supposed to be handled in https://github.com/Expensify/App/issues/29321#issuecomment-1758531013.

**Comment by jasperhuangg** [comment]
Repro on prod so I'm going to take off the deploy blocker label

**Comment by jasperhuangg** [comment]
cc @techievivek

**Comment by techievivek** [comment]
We are already handling this here: https://github.com/Expensify/App/issues/29321
