### ISSUE TITLE
[HOLD for payment 2023-11-20] [$125] Dot separator in the report preview component appears bottom aligned

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#29543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.83-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** (internal)

## Action Performed:
1. Global create > request money
2. Create a request 
3. As the payer, click Pay elsewhere to settle up 
4. Observe the "Cash - Paid elsehwere" dot separator position in the report preview component is bottom-aligned 

## Expected Result:

The dot separator should be center-aligned:

<img width="553" alt="image" src="https://github.com/Expensify/App/assets/16232057/3e1c9145-7f61-430c-9188-ce8567ae7ce3">

## Actual Result:
It looks bottom-aligned: 

<img width="582" alt="image" src="https://github.com/Expensify/App/assets/16232057/79073846-2ed8-43e6-b3dc-ca7b0baa79fd">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes, visual design bug. 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01765a32b3ae401177</li>
        <li>Upwork Job ID: 1712776284859080704</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27177642</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
@shawnborton @dannymcclain @dubielzyk-expensify for vis and confirmation!

**Comment by trjExpensify** [comment]
Also, when testing this I noticed that `Distance` has `Done` after the dot separator, but it should use the appropriate payment method like all other requests. E.g `Paid` or `Paid elsewhere`. We may as well fix that here as well. CC: @neil-marcellini @JmillsExpensify not sure when or why that happened. 

<img width="808" alt="image" src="https://github.com/Expensify/App/assets/16232057/2a3396fd-89c3-4caf-ba5a-ce94a157e84f">

**Comment by mountiny** [comment]
@tienifr nice! Can you also include the change for the `Done`? Asking @trjExpensify what should go there instead

**Comment by grgia** [comment]
@tienifr for the `Done` let's remove distance from this check - https://github.com/Expensify/App/blob/a05c3c5ed002b2e23d216bd899ff3238b0d86b20/src/components/ReportActionItem/MoneyRequestPreview.js#L178-L180

**Comment by shawnborton** [comment]
> Or we can remove styles.mb1 in both text component and add styles.mb1 to the wrapped view

This makes the most sense to me. I like the idea of making sure that entire view has the margin bottom, and making sure that entire view uses a centered vertical alignment.

Also, I would be curious to see the dot indicator icon bumped up to being 8x8.

**Comment by Pujan92** [comment]
@tienifr @rushatgabhane regression https://github.com/Expensify/App/issues/29888 from this issue [PR](https://github.com/Expensify/App/pull/29544).

**Comment by trjExpensify** [comment]
👋 @rushatgabhane can you finish the checklist, please? Also looks like we've got a regression from this PR, right?

**Comment by trjExpensify** [comment]
Removing the hold from the title and `Awaiting payment` as we need to fix the regression this caused.

**Comment by mountiny** [comment]
I believe this is ready for payment now

**Comment by trjExpensify** [comment]
We're still awaiting [the checklist](https://github.com/Expensify/App/issues/29543#issuecomment-1775522654). Also, can we confirm the number of regressions here? 

It seems like one so that takes us to $62.5 as the bounty due to @rushatgabhane & @tienifr, right?

**Comment by trjExpensify** [comment]
Bump!

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by trjExpensify** [comment]
Do we need to issue payouts as per this? https://github.com/Expensify/App/issues/29543#issuecomment-1821861202
