### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] Change variant to mode in run-android command

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29542]
### Problem 

The variant flag is going to be removed and replaced with mode for the run-android command. This PR changes it, so the command won't fail/install wrong app version when we'll have bumped react native.

### Solution

Use the `mode` flag instead

**Comment by staszekscp** [comment]
Hey! I'm going to fix it :)

**Comment by mountiny** [comment]
No need for payment here
