### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500]  IOU - The message "Only visible to you" does not disappear when editing details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29552]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29961

## Action Performed:
Action Performed:
Prerequisites:
For scanning, you can use a personal receipt file or download a test file here https://drive.google.com/file/d/1qz7afTHBUD-Shr0EeJ0pR0MYbbe2Euia/view?usp=drive_link

1. Open New Expensify app
2. Log in with the employee's login
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Scan' and add a receipt
6. Choose a workspace
7. Save money request
8. While the receipt is scanning - navigate to the request conversation
9. Manually edit the merchant field
10. Navigate to the report conversation

## Expected Result:
The message "Only visible to you" should immediately disappear after manually editing the receipt scan details

## Actual Result:
The message "Only visible to you" does not disappear when manually editing receipt scan details, or it disappears but with a long time delay
Reproduce on Desktop, Android, iOS - the message disappears within 5 to 10 minutes(Once in a while it doesn't disappear and stays.). Web, mWeb the message disappears within 5 to 10 seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/9af55a24-947c-4b8b-ad80-f8f8d7e94b64

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e02465a0adc8bf8</li>
        <li>Upwork Job ID: 1712974605700993024</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27258427</li>
<li>tienifr | Contributor | 27258430</li>
</ul></li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
How does @tienifr's [proposal](https://github.com/Expensify/App/issues/29552#issuecomment-1762630659) look @aimane-chnaif?

**Comment by bfitzexpensify** [comment]
Just noting that I'm going to consider this eligible for the #urgency bonus since the hold up was around a discussion as to whether or not we wanted to fix the back-end before fixing this. 

Payments made. 

@aimane-chnaif please complete the BZ checklist when you get a chance - thanks!
