### ISSUE TITLE
 IOU - "This" parent not shown in category list and sub category of "This" few in bold format

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to Old dot as Policy admin
2. Tap Policy settings-categories
3. Add the following categories:
A. This
B. This: is: a: subcategory: with: lots: and: lots: of: levels: needALongerWordHereToTriggerTheLines

1. As Employee, go to https://staging.new.expensify.com/

2. Tap Workspace chat
3. Tap plus icon and select request money
4. Enter an amount and tap next
5. Tap show more
6. Tap categories
7. Enter "This" in search to view parent and child "This"
8. Delete "This" and scroll down the category list

## Expected Result:
Parent "This" must be shown in category list and sub-categories in same font weight and format must be displayed

## Actual Result:
When we type "This" in search field, as entered in old dot shown correctly.In category list, parent "This" is not shown and in sub category, some words are bold and some not, the font weight format differs

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/60415fb5-1c10-4327-9cbb-ce54ecd6fc96

![Bug6226569_1696545269683!Screenshot_2023-10-06-02-56-23-246_com android chrome](https://github.com/Expensify/App/assets/78819774/28c54f2c-612c-4513-9425-41a000274bd0)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Hey @lanitochka17 - is the issue just the bolding? I'm not quite sure I uderstand what it should look like (i.e. what is the expectted behavior).

**Comment by lanitochka17** [comment]
@sakluger Hello
Expected result:
The levels of subcategories should correctly display in the list below the parents. These should be indented one space to the right with each level. A sub-category (with >10 levels) that is selected should fully display the in the categories list.

**Comment by sakluger** [comment]
I don't think I've ever seen a category with that many nested subcategories, only 3-4. I'm going to close this for now, if a user reaches out and confirms that it's a real-life issue that customers are running into, we can fix it at that point.
