### ISSUE TITLE
[Waiting for C+ payment via manual request][$500]  IOU - Category list is not shown in alphabetical order in employee WS category list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-10

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open old dot as Admin
2. Open Settings-- Workspace--policy
3. Tap on categories
4. Delete "Benefits" categories by tapping cross ❌ button
5. Scroll down and under add a category -Enter "Benefits" and add the category
6. Go to https://staging.new.expensify.com/
as Employee
7. Tap on WS chat
8. Tap Request money
9. Enter an amount
10. Tap next
11. Tap show more
12. Tap categories and scroll down the list

## Expected Result:
Category list must be shown in alphabetical order in employee WS category list. "Benefits" category must be shown on top after "A" alphabet category

## Actual Result:
"Benefits" category is shown last in the list.Category list is not shown in alphabetical order in employee WS category list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/47f7b3e6-2e8d-438f-87ba-4b70ca4a12d6

https://github.com/Expensify/App/assets/78819774/974f3fc4-f9c8-4ab2-81af-4f3890c9ad19

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014544ffc7c7e48354</li>
        <li>Upwork Job ID: 1713779294261329920</li>
        <li>Last Price Increase: 2023-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>honnamkuan | Contributor | 27308934</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by robertjchen** [comment]
@honnamkuan 's proposal sounds great to me as well 👍

**Comment by kadiealexander** [comment]
Since the PR was raised in full, we'll pay the contributor and C+ for their work. 

Payouts due:

Contributor: $500 @honnamkuan
Contributor+: $500 @rushatgabhane

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~014544ffc7c7e48354).

**Comment by rushatgabhane** [comment]
request here - https://staging.new.expensify.com/r/1352863141264669

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on summary above.
