### ISSUE TITLE
[$500] Category - Deleted category can be saved when it is selected offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-10

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. As employee, open an unpaid expense details page
3. As employee, go offline
4. As admin on OD, delete one category
5. As employee, tap on Category and select the disabled category in Step 4
6. As employee, reconnect network

## Expected Result:
Error will show up indicating that the category cannot be selected because it is disabled

## Actual Result:
The category is selected succesfully and there is no error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome /summary>

 

https://github.com/Expensify/App/assets/78819774/38dcf048-d072-4bd5-acab-2a6387abf3de

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01535f6784711bac13</li>
        <li>Upwork Job ID: 1712870217134297088</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27259027</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment]
@0xmiroslav @lanitochka17 are you still seeing this occurring?

**Comment by abekkala** [comment]
reached out in callstack for someone to take this on

**Comment by rezkiy37** [comment]
I've investigated the issue. Actually, I don't see any actions that should be done on the application side. We need to improve the backend. Before attaching a category to an expense report, it should verify that a category is active. 
If the category is inactive, the backend should return an error, the app will show it.
IMO, we need backend changes first. Then, check how the app handles the error.
