### ISSUE TITLE
[HOLD for payment 2023-11-09] [Wave 6: Categories] Design follow up to Tag and Category lists

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29574]
Here is an tracking issue to compile feedback and implement improved design for the category and tag list 
![image](https://github.com/Expensify/App/assets/36083550/3d0e6098-8d83-40a2-9d90-9fb306852057)

Slack [thread](https://expensify.slack.com/archives/C02MW39LT9N/p1697210138941739)

cc @waterim @rezkiy37 @shawnborton

**Comment by shawnborton** [comment]
I think something like this would be more ideal:
<img width="1200" alt="CleanShot 2023-10-13 at 12 42 53@2x" src="https://github.com/Expensify/App/assets/2319350/5478e302-7198-48ed-8ac6-df1f1a8cee6c">

- Each child/sub-category should get an additional 12px of left padding, and this padding is applied to the whole row so that the text has the same left edge
- There should be 20px of space between each "block" with each block meaning the Search box, the current selection, the Recents block, and then the All block

**Comment by shawnborton** [comment]
cc @Expensify/design for thoughts if you have any!

**Comment by puneetlath** [comment]
For anything that takes more than two lines, we should just overflow with elipse is that right? 

Also, just FYI, in case this wasn't known, this is how we show a sub-category when it has been selected and you re-enter the list. It's shown at the top with colons to indicate the full selection: 
<img width="782" alt="image" src="https://github.com/Expensify/App/assets/1371996/680f0110-351e-4e6f-a53e-1aa800bf60dd">
<img width="783" alt="image" src="https://github.com/Expensify/App/assets/1371996/a9e886db-19dc-44cd-89d8-e1814e87486b">

**Comment by shawnborton** [comment]
I like that - so show two lines worth of text and truncate after that? That should be plenty I think.

**Comment by JmillsExpensify** [comment]
Also like that. Great idea. Not the biggest fan of how we switch things up with the colons, as I would love to make that more look like a series of "tags" in the future, in the UI sense not what we refer to as tags in product. 

Notes does it like this, though I don't think we need the hashtags. 
<img width="193" alt="Screenshot 2023-10-13 at 14 35 09" src="https://github.com/Expensify/App/assets/1127863/6bc9643d-2b3c-40fc-a6c8-6b46e3d774a0">

This would probably be a more traditional approach.
<img width="333" alt="Screenshot 2023-10-13 at 14 36 32" src="https://github.com/Expensify/App/assets/1127863/d610cb5f-5b17-4181-9714-05d62a7a1f60">

Anyway something to consider for the future.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@shawnborton, @puneetlath and @mountiny. Guys, I think about how the app shows a selected category, when its name is too long for one line. My proposal is to allow 2 lines here as well as we have within the list.

<details><summary>One line now</summary>
<p>

<img width="1728" alt="Screenshot 2023-10-24 at 17 26 47" src="https://github.com/Expensify/App/assets/57314631/d177b5f4-8b78-4342-9bd6-9b3c3fb338bc">

</p>
</details> 

<details><summary>Two lines then</summary>
<p>

<img width="1728" alt="Screenshot 2023-10-24 at 17 30 27" src="https://github.com/Expensify/App/assets/57314631/f6d8bb36-3747-4daa-a8b0-670415afea83">

</p>
</details>

**Comment by rezkiy37** [comment]
I am preparing a [PR](https://github.com/Expensify/App/pull/30264). Planing opening tomorrow.

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by mountiny** [comment]
We will need to pay $500 to @mollfpr for testing and review

**Comment by puneetlath** [comment]
@mollfpr offer here: https://www.upwork.com/nx/wm/offer/27545426

**Comment by mollfpr** [comment]
@puneetlath I'll do a manual request in NewDot. Could you give the payment summary? Thank you!

**Comment by puneetlath** [comment]
Ah whoops. Didn't realize you were being paid there now! 

Payment summary: 
- C+ internal PR - @mollfpr - $500

**Comment by mountiny** [comment]
I think we can close now as @mollfpr is paid in Newdot
