### ISSUE TITLE
[HOLD for payment 2023-11-13] [HOLD E/E #326097] [Wave 6: Workspace Chats] Update how GBR is determined for IOU/expense reports

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#29595]
In https://github.com/Expensify/Expensify/issues/326097 we are adding a new `hasOutstandingChildIOU` field. We need to update the way [ReportUtils.isWaitingForIOUActionFromCurrentUser](https://github.com/Expensify/App/blob/b9a2f625e45a9153fe927633d86b986fbd5c1f65/src/libs/ReportUtils.js#L1210) determines which reports to show the GBR on. It should be based on the `hasOutstandingChildIOU` field. 

This is described in the workspace chats design doc [here](https://docs.google.com/document/d/1arowjiiYSu4fyu0CYrB8748UOz4oEDaWZzmXpGKwg-k/edit#heading=h.g6q9cp2p5zt8).

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this one!

**Comment by greg-schroeder** [comment]
FYI @waterim, from Slack: https://expensify.slack.com/archives/C02MW39LT9N/p1697583395704569?thread_ts=1697503628.240919&cid=C02MW39LT9N

It would be nice if we could clean up/centralize the GBR (green dot) logic while we’re doing this. To ensure that:

1. the green dot always makes the chat go to the top of the list under pinned chats (no matter how the green dot is being set, via mention, outstanding IOU or something else)
2. the green dot always makes a chat visible in focus mode

**Comment by puneetlath** [comment]
Reminder: we also need to add this new field to the typescript types for reports.

**Comment by puneetlath** [comment]
@waterim FYI we've started sending the `hasOutstandingChildRequest` field on staging. Right now it only is being sent in Most Recent mode, not in #focus mode. So you should be able to test your PR with the back-end in most recent mode to make sure things are working as expected.

**Comment by waterim** [comment]
@puneetlath nice to hear! 
testing

**Comment by puneetlath** [comment]
Also, @akinwale was the C+

**Comment by waterim** [comment]
Where to add these steps?

**Comment by puneetlath** [comment]
I'll take care of it don't worry. The automation wrongly tagged you for that.

**Comment by puneetlath** [comment]
Actually, we already have a separate issue for handling that here: https://github.com/Expensify/Expensify/issues/319016

So all that is left to happen on this issue is paying @akinwale out next week.

**Comment by akinwale** [comment]
> @akinwale offer here: https://www.upwork.com/nx/wm/offer/27646277
> 
> Ping me on this issue when you've accepted please.

@puneetlath Accepted. Thanks!

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
