### ISSUE TITLE
Multiple email threads created for the same group chat due to subject line inconsistency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697162566932439

## Action Performed:
1. Send a message to a group chat 
## Expected Result:
Only one email notification is received
## Actual Result:
Multiple emails are received
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Snip - Inbox (100,829) - applausetester@applause expensifail com - Expensi](https://github.com/Expensify/App/assets/38435837/ed51299d-06cc-4e32-9402-c7e533aa5cf8)

![image (1)](https://github.com/Expensify/App/assets/38435837/79653198-41db-4191-8c59-167e51d1f1ac)

![image](https://github.com/Expensify/App/assets/38435837/9650b47c-8825-49b8-af4a-bc89b52dbaa3)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01952eacb0f88b3f4d</li>
        <li>Upwork Job ID: 1712966728810754048</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by yakupafsin** [comment]
The issue description is somewhat unclear, but upon examining the screenshot, it appears that you've received multiple emails. The reason for this is that the users who are splitting the bills have email addresses that seem distinct but actually resolve to the same email address. For example:

1. applaudetester++0531mn@applause.expensifail.com
2. applaudetester+1011mne@applause.expensifail.com

Both of these emails, which you used for testing, essentially correspond to the same email address, applaudetester@applause.expensifail.com. However, in the application, these two emails appear as different users, resulting in the app sending emails to both email addresses, even though both emails end up in the same inbox (applaudetester@applause.expensifail.com).

Regarding the second screenshot, it's evident that you are receiving emails for different messages. Therefore, this behavior is not indicative of a bug in the system.

**Comment by puneetlath** [comment]
I think this will need to be Internal.

**Comment by trjExpensify** [comment]
Interesting, @puneetlath, we need to add `Engineering` to get it assigned internally.

**Comment by marcaaron** [comment]
Taking off @mananjadhav as this is an internal only issue.

**Comment by marcaaron** [comment]
Heads up I'm closing this in favor of https://github.com/Expensify/Expensify/issues/326099
