### ISSUE TITLE
[HOLD for payment 2023-11-16] [Wave 6: Workspace Chats] Make optimistic requests/IOUs/expense reports “hidden”

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#29593]
We want to make expense reports, IOU reports, and individual requests to use the same “hidden” setting that we use for threads so that they will be hidden from the LHN by default. Let's update the creation flows so that when these are optimistically created they have the "hidden" notification preference. This is described in the workspace chats design doc [here](https://docs.google.com/document/d/1arowjiiYSu4fyu0CYrB8748UOz4oEDaWZzmXpGKwg-k/edit#heading=h.hihjg7pw4d0h).

[Here](https://github.com/Expensify/App/blob/f2a9e9f5b086c9964cd9ebd1fbcb0406a430d1bd/src/libs/ReportUtils.js#L2089) for expense reports
[Here](https://github.com/Expensify/App/blob/f2a9e9f5b086c9964cd9ebd1fbcb0406a430d1bd/src/libs/ReportUtils.js#L2054) for IOU reports
[Here](https://github.com/Expensify/App/blob/f2a9e9f5b086c9964cd9ebd1fbcb0406a430d1bd/src/libs/ReportUtils.js#L2743) for individual requests

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by puneetlath** [comment]
I'm going to go ahead and remove the HOLD. I think it's fine for us to go ahead and implement this independent from the back-end changes. 

@mountiny is working on the back-end portion and until that is done, when the back-end responds it will overwrite the hidden value, so you'll need to test in offline mode @rezkiy37.

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by puneetlath** [comment]
This was merged.

**Comment by rezkiy37** [comment]
So, @puneetlath, can we move forward and close the issue?

**Comment by puneetlath** [comment]
We just need to keep it open to pay @situchan after the regression period. 

Upwork offer here: https://www.upwork.com/nx/wm/offer/27646351

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
