### ISSUE TITLE
[$1000] Desktop -  User locked out, can't use the app at all

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29615]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697230242487469

## Action Performed:
1. Downloaded the desktop app and sign in
2. Delete the desktop app
3. Download the desktop app again
4. Try to sign in
5. App freezes and throws a JS error
6. ReconnectApp appears to be called in a loop many times
7. Navigate back to sign in page
8. Locked out because too many magic codes requested (I only attempted to sign in once).

## Expected Result:
Just be able to sign in. No weird network stuff seemingly causing many requests for magic codes resulting in getting locked out of the account temporarily.

## Actual Result:
Got locked out. Can't use the app at all.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![2023-10-13_10-46-44 (1)](https://github.com/Expensify/App/assets/93399543/ccf4a207-0c3a-40ab-9d4e-9456f5c60f1d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01115e59ed0c307000</li>
        <li>Upwork Job ID: 1713975104877924352</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by sakluger** [comment]
This feels like it might be external, but I'm not sure. I'll start external, please let me know if we need a backend engineer to help on this one.

**Comment by sakluger** [comment]
@allroundexperts I'd love your thoughts here. Is this something that can be handled by an external contributor or do we need to take it internal?

**Comment by sakluger** [comment]
Okay, thanks! Bumping.

**Comment by b4s36t4** [comment]
I'm not able to reproduce this? When I re-install the app previously loggedin session stays same? I don't see any issues. 

> Not able to move forward past step 3.

Is there anything I'm missing? Do I need to logout after re-installing the app? Do I need to reboot my system?

cc: @marcaaron

**Comment by b4s36t4** [comment]
I tried on staging app.

**Comment by marcaaron** [comment]
It's probably not consistently reproducible. But should be documented because it happened.

**Comment by sakluger** [comment]
@marcaaron would you recommend as a next step here? If it's not easily reproduceable, any ideas on how we can fix?

**Comment by marcaaron** [comment]
Leave it open and see if anyone else reports it or catches a reproduction. If not then I guess we could assume it's been "fixed". But pretty awful bug IMO.

**Comment by marcaaron** [comment]
>any ideas on how we can fix

Not without a repro

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment]
Welp, I guess we close for now and assume it's fixed.  Hopefully, if it's not fixed, someone can figure out some consistent reproduction steps 🤷
