### ISSUE TITLE
Desktop - When uploading a receipt via the request money flow, it shows as `Pending`

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697243512619269

## Action Performed:
1. Next to the compose box, click the `+` action button and request money
2. Upload receipt as part of the Scan flow
3. Notice `Pending` shows at top, during SmartScan process and after it's done SmartScanning

## Expected Result:
`Pending` to not show

## Actual Result:
When uploading a receipt via the request money flow, it shows as `Pending`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/e12f5803-3764-4ab4-858d-d6731ad9d7dc

![image (6) (1)](https://github.com/Expensify/App/assets/93399543/9a72e486-81c5-4167-8ded-420cc610f300)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment]
It seems to be a normal behavior, the pending will disappear as stated in the message. this new behavior was added here  
https://github.com/Expensify/App/pull/29201

**Comment by mountiny** [comment]
<img width="1124" alt="image" src="https://github.com/Expensify/App/assets/36083550/3cc3827f-f2cd-4cbc-ae0c-9094e401f2b6">

also fixed

Payment for c+ handled here https://github.com/Expensify/App/issues/29626 closing
