### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Login - Site in Spanish automatically changes to English on signing out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Scroll down and change language to Spanish
3. Tap on G and login using any account
4. Now app opens in Spanish
5. Log out

## Expected Result:
Site in Spanish must remain in the same language on signing out

## Actual Result:
After log out, now page is displayed in English instead of Spanish
Site in Spanish automatically changes to English on signing out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/fb438fc9-db2a-4b50-b0a3-7e9d0b0e492e

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155ff15b3754aa4ec</li>
        <li>Upwork Job ID: 1713780600845426688</li>
        <li>Last Price Increase: 2023-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27222589</li>
<li>tienifr | Contributor | 27222590</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
Seems like the backend is not sending the correct preferred language of the user upon the reconnect. 

When `api?command=OpenApp` is called, it sets a bunch of values and one of them is this. Even if the preferred language is `ES`

```js
{onyxMethod: "merge", key: "preferredLocale", value: "en"}
```

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Contributor: $500 + $250 bonus @tienifr
- [x] Contributor+: $500 + $250 bonus @fedirjh

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/29620#issuecomment-1769116900)

Upwork job is [here](https://www.upwork.com/jobs/~0155ff15b3754aa4ec).
