### ISSUE TITLE
 Android - Sum is disappeared after pay elsewhere in row ’Total”

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29544

## Action Performed:
1. Launch App
2. Tap on FAB > request money/ or go to chat and request money
3. Create a request in this case $99
4. As the payer, click Pay elsewhere to settle up

## Expected Result:
Sum $99 should be displayed in row "Total"

## Actual Result:
Sum is disappeared after pay elsewhere in a row ’Total”

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Bug6237285_1697310826439!android](https://github.com/Expensify/App/assets/78819774/c08fe91e-9ff0-4a5a-bd4a-20766ff449e7)

https://github.com/Expensify/App/assets/78819774/f15665da-8a96-4bfd-8aab-9f20a9149ff8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I believe this should be resolved in 84-1 

<img width="997" alt="image" src="https://github.com/Expensify/App/assets/36083550/9a5b0f1c-020b-4df9-b23a-b473530f09d2">

**Comment by mountiny** [comment]
Resolved so we can close this now
