### ISSUE TITLE
[HOLD] Desktop -  User is not seeing unread messages in focus mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.81-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joaniew 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697043055545999

## Action Performed:
1. Open the app
2. Put the setting to focus mode
3. Receive the messages from user B
4. Change to most recent mode.

## Expected Result:
User is seeing unread messages in focus mode

## Actual Result:
User is not seeing unread messages in focus mode

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details> n/a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment]
I think we should hold this until https://github.com/Expensify/App/issues/28536#issuecomment-1763053137 is done because it will change the unread code

**Comment by maddylewis** [comment]
still holding - https://github.com/Expensify/App/issues/29623#issuecomment-1763328838

**Comment by maddylewis** [comment]
i'm going to close this out while we work on the fix over here https://github.com/Expensify/App/issues/28536#issue-1920280710. 

if after that's merged, we can reopen this if it's still an issue.
