### ISSUE TITLE
[$500] Task - Canceled task is not archived and is not visible in 1:1 conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29622]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. On LHN, click on the FAB button
3. Select Assign Task
4. Enter a title or description
5. Assign the task to yourself
6. On Share Somewhere, select a conversation with another user you have access to and create the Task
7. Navigate to the task report
8. Click on the 3 dot menu
9. Cancel the task

## Expected Result:
There should be message displayed in the task report - "cancelled task [task name]" and the task report should be archived

## Actual Result:
Canceled task is not archived and is not visible in 1:1 conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/53d92ff1-c0fd-44d1-8c9e-b24bf0e649d7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ed002ab3e5a7fe7</li>
        <li>Upwork Job ID: 1713906699593957376</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Perfect, thanks! So on that note, we can go ahead and close this out as expected with those items being handled on the main issue. 👍
