### ISSUE TITLE
 Split - Total group split details card does not appear in chat until the chat is revisited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29424
## Action Performed:
Precondition: User A is a workspace admin and User B is a workspace member

1. [User A] Open the workspace chat with User B
2. [User B] Go to FAB > Request money > Manual > Enter amount > Next
3. [User B] Select Split on the workspace chat in Step 1 > Create the bill split

## Expected Result:
On User A's side, the total group split details card will appear along with individual split preview

## Actual Result:
On User A's side, only the invididual split preview appears. The total group split details card does not appear until the chat is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/ad297986-2c42-4b0f-84f3-9201e4838f26

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137b2e4cc6c36c506</li>
        <li>Upwork Job ID: 1713664488466337792</li>
        <li>Last Price Increase: 2023-10-15</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This will most likely have to be internal and we need to ensure the split action is pushed to the groupchat too. I dont think it has to be a deploy blocker though so demoting cc @youssef-lr

**Comment by neil-marcellini** [comment]
Thanks Vit. @youssef-lr have you been working on this lately and would you like to take it over? That would be a big help to me.

**Comment by youssef-lr** [comment]
Sure @neil-marcellini :)

**Comment by youssef-lr** [comment]
Working on this tomorrow.

**Comment by Christinadobrzyn** [comment]
hi @youssef-lr let us know if you have a PR or update for this! Thanks!

**Comment by youssef-lr** [comment]
PR is underway @Christinadobrzyn

**Comment by youssef-lr** [comment]
This should be fixed now.

**Comment by Christinadobrzyn** [comment]
Ah okay, thanks @0xmiroslav - closed the Upwork job. Closing this as complete!
