### ISSUE TITLE
Desktop - ''Hmm... it's not here'' when navigating to 'date of birth' settings via deeplink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**   1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: User must be logged out from the desktop app
1. Open staging.new.expensify.com and sign in
2. Navigate to https://staging.new.expensify.com/settings/profile/personal-details/date-of-birth
3. In the ''Open New Expensify'' modal, click on the CTA button to open the app

## Expected Result:
There should be no errors when opening the deeplink

## Actual Result:
Desktop - The user encounters a "page not found" error when navigating date-of-birth settings via deeplink in Desktop app. (not repro in production)
Web - Error in JS console when navigating to date-of-birth settings via deeplink

Hmm... it's not here
Oops, this page cannot be found
Go back to home page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/cc49e2e2-3905-4114-b133-6bae7460d11f

https://github.com/Expensify/App/assets/78819774/a818bfec-3b42-418d-b353-fd13e1a2e9b8

[deeplink _date of.txt](https://github.com/Expensify/App/files/12908088/deeplink._date.of.txt)

[console error Web.txt](https://github.com/Expensify/App/files/12908092/console.error.Web.txt)

Production 

https://github.com/Expensify/App/assets/78819774/8490779a-e9fa-419a-a456-62055548fc00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Issue  reproducible on Production 


https://github.com/Expensify/App/assets/78819774/5753764a-3de8-46a7-9b5b-7383e8496ed5

**Comment by mountiny** [comment]
I think this is same as this deploy blocker which is more generic so I would close this in favour of that one https://github.com/Expensify/App/issues/29642
