### ISSUE TITLE
[HOLD for payment 2023-10-24] [$125]  IOU - Expense preview card is wider than the Pay button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click + > Request money > Manual
4. Complete the request flow
Note that the expense preview card is wider than the Pay button

## Expected Result:
The expense preview card and the Pay button have similar width

## Actual Result:
The expense preview card is wider than the Pay button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/6fa66f6d-7c82-4be4-b27e-ef6ead87fde8

Staging
![Screenshot 2023-10-15 at 04 26 19](https://github.com/Expensify/App/assets/78819774/ec28aa89-0c7c-4125-9242-60ead3c5432e)

Production
![Bug6237521_1697332502451!Screenshot_2023-10-15_at_04 18 39](https://github.com/Expensify/App/assets/78819774/7145098d-45b5-4c58-a56e-ad4b34ff5d27)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019741438087b10f75</li>
        <li>Upwork Job ID: 1713665637747257344</li>
        <li>Last Price Increase: 2023-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27209686</li>
<li>ishpaul777 | Contributor | 27209690</li>
<li>situchan | Contributor | 27216588</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment]
@ishpaul777 you linked wrong PR. This is regression from https://github.com/Expensify/App/pull/29431

**Comment by mountiny** [comment]
I will take this on. Thanks for the proposal @ishpaul777 Can you please raise a PR in the next 12 hours? Thanks!

**Comment by situchan** [comment]
I think it's safer for @grgia and @allroundexperts to handle this. It seemed intentional to set `reportPreviewMaxWidth` to 302, not 375.

**Comment by mountiny** [comment]
@ishpaul777 Can you hold on for @grgia to clarify whats the expected behaviour on this one, I think we can offload this work to you though so I will keep you assigned

**Comment by situchan** [comment]
Also, in this issue, let's fix [this inconsistency](https://github.com/Expensify/App/pull/29568#issuecomment-1763395246) as well. ReportPreview and MoneyRequestPreview should have same card size

**Comment by situchan** [comment]
@ntdiary if you want, please go ahead C+ review here. I was just suggesting the right direction.

**Comment by situchan** [comment]
> > @ntdiary if you want, please go ahead C+ review here. I was just suggesting the right direction.
> 
> @situchan, my task list has reached maximum capacity, and I haven't had a chance to look at this issue yet. 😂

ok, I will take it then

**Comment by grgia** [comment]
@mountiny we changed the max-width purposefully

**Comment by grgia** [comment]
> I am suggesting for pay button to have its parent container full width and not reference the reportPreviewMaxWidth at all for the SettlementButton, though i'll be waiting for their response on this.

This sounds like the best solution for pay button

> Also, in this issue, let's fix https://github.com/Expensify/App/pull/29568#issuecomment-1763395246 too as it came from same PR. ReportPreview and MoneyRequestPreview should have same card size

Agreed, can we use 335 for the max width?

going off of this [figma](https://www.figma.com/file/dmhA9UknFuGCj0BzJaMhSb/Scan-Receipts-Doc?type=design&node-id=2938%3A28442&mode=design&t=zcwu6udZczmBPYsV-1)/mocks:
![image](https://github.com/Expensify/App/assets/38015950/4ae979be-1088-4292-86e0-2f094839f494)

**Comment by mountiny** [comment]
No checklist required as this was a deploy blocker so the offending PR has been identified already, we do not need a regression test for this either

We need to pay $125 to @ishpaul777 and @situchan for this quick PR to resolve a deploy blocker I believe

**Comment by mallenexpensify** [comment]
@mountiny @ishpaul777 and @situchan should also receive the urgency bonus, right?

**Comment by mountiny** [comment]
I guess yes, it was a deploy blocker so it had to be fixed fast

**Comment by mallenexpensify** [comment]
Issue reporter: Applause
Contributor: @ishpaul777 paid $200 via Upwork
Contributor+: @situchan owed $250 via Upwork

@situchan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019741438087b10f75

**Comment by situchan** [comment]
@mallenexpensify accepted, thanks

**Comment by mallenexpensify** [comment]
@situchan paid, updated the above payment breakdown. 
Also... updated price above from $250 to $200, the correct amount. 

Thanks y'all!

**Comment by sophiepintoraetz** [comment]
>@mountiny, @ishpaul777 and @situchan should also receive the urgency bonus, right?

@mallenexpensify @mountiny - no, [reviews are a flat fee](https://expensify.slack.com/archives/C01SKUP7QR0/p1695953935912929) no bonus applies here.

**Comment by mallenexpensify** [comment]
@sophiepintoraetz in[ post that was linked](https://expensify.slack.com/archives/C01SKUP7QR0/p1693344004362289) in the link you sent it says
> The 50% urgency bonus will be remaining in place  

I think deploy blockers are some of the most important bugs to fix in a timely manner so the urgency bonus _makes sense_.   I'm unsure if we're thoroughly discussed or documented anywhere though.

**Comment by sophiepintoraetz** [comment]
Ah, I was coming from another issue which I think conflated some payment logic - my apologies! I agree we need to have a much simplified payment structure (we're doing away with urgency bonuses anyways, so kind of a moot point).
