### ISSUE TITLE
[$250]  Desktop - Deeplink - Error message when navigating to a conversation after logging in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29642]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Copy a conversation URL from ND and log out to both web and Desktop (You can also reproduce with just Desktop being signed out)
2. Navigate to the copied link
3. Login and click to open in the app

## Expected Result:
The desktop app is logged in and user is redirected to the conversation

## Actual Result:
The desktop app shows an error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

Staging

https://github.com/Expensify/App/assets/78819774/9543b16b-ffa0-4c1f-9cb7-5b8b37f44540

Production

https://github.com/Expensify/App/assets/78819774/8ae39289-0396-4f62-848d-25b214badb44

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117861c8671a2f4e7</li>
        <li>Upwork Job ID: 1713869621910880256</li>
        <li>Last Price Increase: 2023-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 27217865</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
Coming from a Slack thread, I can take this one over from Amy and @hungvu193 found a fix

**Comment by lanitochka17** [comment]
The video is located in the Screenshots/Videos tab

![image](https://github.com/Expensify/App/assets/78819774/6c540450-b097-44ff-9561-ebfbd41878c8)

**Comment by lukemorawski** [comment]
preparing a PR with a fix

**Comment by mountiny** [comment]
PR being CPed

**Comment by mountiny** [comment]
Reverted

**Comment by lukemorawski** [comment]
will start to work on this today
