### ISSUE TITLE
[$500] Desktop - Error when open the desktop app after initially signing in via a magic code link on web

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch the desktop app
2. Enter an email associated with an existing account or enter a new email to create a new account
3. Go to email inbox and locate the email containing the magic code
4. Copy the magic link and change it to "staging"
5. Open a new tab and navigate to modified staging magic link
6. On the "Here is your magic code" page, click on the "just sign in here" CTA button
7. In the "Open New Expensify" modal, click the CTA button to open the app

## Expected Result:
The user should be able to log in to the desktop app without any issues

## Actual Result:
The user receives an "incorrect magic code" error when attempting to open the desktop app after initially signing in via a magic link on web
Incorrect magic code. Please try again or request a new code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

  

https://github.com/Expensify/App/assets/78819774/0031f03f-91a4-4538-afe4-60509af074f3

[logs.txt](https://github.com/Expensify/App/files/12910320/logs.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01065915e673948ce3</li>
        <li>Upwork Job ID: 1714686947912638464</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by johncschuster** [comment]
Triaged

**Comment by sofi-a** [comment]
This is a BE issue. The following is a response from POST https://www.expensify.com/api?command=SigninUserWithLink.

![image](https://github.com/Expensify/App/assets/31987492/f70d0036-9f12-4fe3-a964-5b910a7272ed)

**Comment by johncschuster** [comment]
Thanks for surfacing that, @sofi-a. Sounds like I'll need to rope in a BE engineer.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
Thanks, @mvtglobally!

**Comment by neil-marcellini** [comment]
I'll triage today and double check for reproducibility.

**Comment by neil-marcellini** [comment]
@johncschuster I think we should reject bug reports which do things like manually changing the link to staging. That's not something real users are going to do. I tested the flow on prod and it works great. I'm closing this.


https://github.com/Expensify/App/assets/26260477/843cdc44-065e-40e4-9b28-f4b0fb35cd0c
