### ISSUE TITLE
Profile - Using \u200D as a first/last name is not treated like it’s empty but shown blank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28821
## Action Performed:
1. Launch new expensify logged in
2. Go to Settings from the LHN
3. Select Profile
4. Select Display name
5. Enter as both names unicode character \u200D (you can use http://www.unicode-symbol.com/u/200D.html
to copy it and paste in the fields)
6. Save the name

## Expected Result:
It should be saved, but the name will be treated as empty so the email of the account should be shown

## Actual Result:
The name is shown as blank as the character is saved but since it's invisible it won't appear as a name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/edfb5a87-2054-4bd1-85e2-43bdff35a7d5

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/11b39735-a953-496e-ba66-d5a8a5a841ce

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhanashree-sawant** [comment]
Similar reported issue:
https://expensify.slack.com/archives/C049HHMV9SM/p1689924356563269

**Comment by lanitochka17** [comment]
@MitchExpensify Hello
The video has been added to the Screenshots/Videos tab

![image](https://github.com/Expensify/App/assets/78819774/8f7a5ef2-d4ac-4ebd-b6cd-dc379f6805ab)

**Comment by MitchExpensify** [comment]
Sorry for missing that @lanitochka17 and thanks for pointing where to look 👀

**Comment by MitchExpensify** [comment]
I don't quite follow how this will hurt user experience so closing as such
