### ISSUE TITLE
Chat -  "Pay" button is not completely fitted in request preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697387154663989

## Action Performed:
1. Request money from a workspace chat.
2. Navigate to workspace chat.

## Expected Result:
 "Pay" button is fitted in the preview completely and no empty space on right
 
## Actual Result:
 "Pay" button is fitted in the preview completely and there is empty space.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![Screenshot 2023-10-15 at 9 56 20 PM](https://github.com/Expensify/App/assets/93399543/14070bef-f7a1-4c0c-abbc-ca0df8118f90)

https://github.com/Expensify/App/assets/93399543/9bafc023-7b29-4533-8d61-ef27ffc62167

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![Screenshot 2023-10-15 at 10 18 48 PM](https://github.com/Expensify/App/assets/93399543/c3756e46-2268-4327-b56b-2b3627ab6e99)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
nice thank you for letting us know
