### ISSUE TITLE
[HOLD for payment 2023-11-21] [HOLD for payment 2023-11-09] [HOLD for payment 2023-11-01] Improve the reliability of the E2E testing suite

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29660]
### Problem

Currently, the E2E testing suite runs the tests on one device over and over. This leads to performance degradation as runs keep on coming since the devices on AWS do not do a complete clean reboot between the runs. This is making the results less accurate and hard to make any calls based upon.

### Solution

Explore options how to structure and run these tests so they are more accurate.

**Comment by ospfranco** [comment]
.

**Comment by hannojg** [comment]
Yeah i think we nailed this now and the tests are stable 😇🎉
