### ISSUE TITLE
[$500] [HOLD for payment 2023-10-24] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] LHN - Split bill description having line breaks is not truncated in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29676]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697385230621939

## Action Performed:
1. Make a new group chat.
2. Click on split bill
3. In the description, enter characters with multiple line breaks in between (using shift + enter)

## Expected Result:
The description should be truncated in LHN

## Actual Result:
The description is not truncated in LHN

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a7906d22-9257-4876-ad4d-befa72d3863a

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/76a8808b-ae5c-436d-8f9d-2cf6fd729625

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/b81268c2-a4d4-4cf6-be81-60da2a6cfef3

https://github.com/Expensify/App/assets/93399543/2f2d2c2a-8272-4e51-a47e-ea7ee34afa29

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/0a9a6ef1-b523-4d00-8487-d02e65855ee5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103feec7f2a1def39</li>
        <li>Upwork Job ID: 1716836279877980160</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @esh-g
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1697385230621939

# Proposal

## Please re-state the problem
Split bill description having line breaks is not truncated in LHN

## What is the root cause of the problem?
The root cause is that we are using `styles.pre` in `OptionRowLHN.js`:
https://github.com/Expensify/App/blob/5ec2e8aa346ec14e935cfbf4c0785821ae9c8a30/src/components/LHNOptionsList/OptionRowLHN.js#L102

This change was made in this PR: https://github.com/Expensify/App/pull/27822
At the PR time, split bill description alternate text was broken (like it is now on prod) so it wasn't tested for it.

## What changes should be made to fix this?
In the fore-mentioned PR, [a similar problem](https://github.com/Expensify/App/pull/27822#issuecomment-1737332654) was occurring and it was fixed by adding the `ReportUtils.formatReportLastMessageText` here: 
https://github.com/Expensify/App/blob/5ec2e8aa346ec14e935cfbf4c0785821ae9c8a30/src/libs/OptionsListUtils.js#L379-L380

So, we can follow a similar approach and change the `MoneyRequestAction` condition here:
https://github.com/Expensify/App/blob/5ec2e8aa346ec14e935cfbf4c0785821ae9c8a30/src/libs/OptionsListUtils.js#L366-L367
to the following:
```js
const properSchemaForMoneyRequestMessage = ReportUtils.getReportPreviewMessage(report, lastReportAction, true);
lastMessageTextFromReport = ReportUtils.formatReportLastMessageText(properSchemaForMoneyRequestMessage);
```
this would also match the backend which currently returns only the first line before the line break for the last message text

<img width="495" alt="Screenshot 2023-10-15 at 11 00 31 PM" src="https://github.com/Expensify/App/assets/77237602/f1875876-d5a2-433f-b19d-7a63af6692f1">

## What alternate approach did you explore?
This is actually a big change in the whole approach of handling the formatting of `lastMessageText`. 

Currently we are formatting the `ReportUtils.formatReportLastMessageText()` very randomly. While adding comments, we use this function to set the `lastMessageText` property on the report itself, but for things like `Modified expense action` we are using it in `OptoinsListUtils.getLastMessageTextForReport` to just display it in LHN.
Moreover, the backend also seems to perform formatting like removing the text after one line break.

What can be done is that all the logic for the line break formatting can be removed from backend as well as while creating optimistic reports and just keep it exclusively in `OptionsUtils.getLastMessageTextForReport` and apply the `ReportUtils.formatReportLastMessageText` for every message.

Additionally,
We can copy whatsApp by replacing every line break with whitespace in the `ReportUtils.formatReportLastMessageText` method by refactoring it like this:
```js
function formatReportLastMessageText(lastMessageText,) {
    return String(lastMessageText).trim().replace(CONST.REGEX.LINE_BREAK, ' ').substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH).trim();
}
```
this would remove the need to have the "hacky" logic we use for modified expense currently:
https://github.com/Expensify/App/blob/5ec2e8aa346ec14e935cfbf4c0785821ae9c8a30/src/libs/ReportUtils.js#L927-L932

**Comment by flodnv** [comment]
Thanks for handling this @francoisl, leaving this in your hands

**Comment by esh-g** [comment]
@francoisl Yes, I'm available just doing so in 10 min

**Comment by NicMendonca** [comment]
@esh-g can you please apply to the job in Upwork?  https://www.upwork.com/jobs/~0103feec7f2a1def39

**Comment by esh-g** [comment]
@NicMendonca This is my profile: https://www.upwork.com/freelancers/~0186b1d7cc69656f22

**Comment by NicMendonca** [comment]
offer sent!

**Comment by NicMendonca** [comment]
@esh-g paid! 🎉

**Comment by esh-g** [comment]
@NicMendonca This PR was merged within the bonus period... please also consider the speed bonus..

**Comment by esh-g** [comment]
@NicMendonca the PR was merged between the bonus period... please reconsider the bonus
