### ISSUE TITLE
[HOLD for C+ manual payment] Rename CONST.IOU. MONEY_REQUEST_TYPE to CONST.IOU.TYPE

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29690]
# Problem
This constant name isn't really correct. It does not hold the type of "money request" (which is manual/scan/distance), but instead it holds the type of IOU (which is split/request/send).

# Why is this important?
It creates confusion in the code

# Solution
Rename the const to `CONST.IOU.TYPE`

**Comment by tgolen** [comment]
Oops, I did that wrong. Ignore me please, @kadiealexander :)

This was an issue handled internally so it is fine to close and no one requires payment.

**Comment by tgolen** [comment]
Oops, sorry about that! I swear I looked for a review... @kadiealexander can you get that paid out please?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor+: $500 @thesahindia (via Manual Requests)

Eligible for 50% #urgency bonus? No

**Comment by kadiealexander** [comment]
Shifting to weekly while the manual request is processed :)

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on summary above.

**Comment by tgolen** [comment]
What's the next step with this one? Can it be closed out?

**Comment by kadiealexander** [comment]
Ah, yup! Sorry I missed Jason's ping.
