### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Chat - Older message disappears on send message offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697447059271049

## Action Performed:
1. go offline
2. click FAB and select send money option
3. enter money and select user

## Expected Result:
It should show older messages

## Actual Result:
Loading appears instead of older message

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c6b924ef-81cd-4e54-8f7e-1f7b3685a6ae

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/f587590f-3ea2-46e5-bb31-36122c67b1bc

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/e6403f9c-664f-40a9-9abd-0f9e775632bf

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/73ee2231-5b9a-4cf8-b2fc-79c90b44b818

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/93399543/191f71e8-76de-49d6-92d3-9af10d7eb606

https://github.com/Expensify/App/assets/93399543/38f21d1b-b4e3-467a-8cc6-2ee6ee93946c

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/831b11a5-7fdc-423e-945e-c0a8ffbda838

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Sending money offline makes the previous report actions disappear.
### What is the root cause of that problem?
In here
https://github.com/Expensify/App/blob/febc3cf7faf80b038e5c81e07f514182fd93ed8e/src/libs/actions/IOU.js#L2513
we get the optimistic data from here
https://github.com/Expensify/App/blob/febc3cf7faf80b038e5c81e07f514182fd93ed8e/src/libs/actions/IOU.js#L2514
and we are setting the new send money report action here with `Onyx.METHOD.SET` instead of `Onyx.METHOD.MERGE`
https://github.com/Expensify/App/blob/febc3cf7faf80b038e5c81e07f514182fd93ed8e/src/libs/actions/IOU.js#L2247-L2253
### What changes do you think we should make in order to solve the problem?
We need to change it to `MERGE`
### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
@ArekChr could you take a look through the proposals?

**Comment by ArekChr** [comment]
@c3024 understood root cause first and [proposal](https://github.com/Expensify/App/issues/29695#issuecomment-1764929144) solves the problem.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ArekChr** [comment]
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: Yes, we can create a regression test here.

**Regression test porposal**

1. Go offline.
2. Open the report that already has existing messages.
3. Click FAB and select the send money option.
4. Input the amount of money, and select the same user from your previous report.
5. Verify that all previous messages remain visible and intact.

Do we agree :+1: or :-1:

**Comment by muttmuure** [comment]
Creating payment issue

**Comment by muttmuure** [comment]
Invites sent

**Comment by muttmuure** [comment]
https://www.upwork.com/en-gb/jobs/~01e10b4bb04120f31d

**Comment by gadhiyamanan** [comment]
Applied, thanks!

**Comment by c3024** [comment]
Invite accepted, thanks!!

**Comment by c3024** [comment]
Offer accepted @muttmuure 

It is not a significant performance issue. Only when we create a new chat with a user with a send money request, using of SET gives a slight benefit over MERGE. But creating a new chat with a send money is an infrequent case and the performance difference is insignificant.

**Comment by gadhiyamanan** [comment]
Offer accepted, thanks!

**Comment by muttmuure** [comment]
Everyone is paid
