### ISSUE TITLE
[$500] Workspace - Settings - Abbreviation used instead of symbol for AMD currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697480858959599

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->settings
3. Click on default currency
4. Search for AMD, observe the part after '-' in search result
5. Search for AMD symbol on google and observe that it is different then what we use
6. Cross check for different currencies like AWG, EUR, INR, USD, AUD etc. We use symbols throughout the list to display after '-'
7. Search for symbol used for AMD in our list on google and observe that we are using abbreviation instead of symbol for AMD

## Expected Result:
App should use AMD symbol for AMD currency as we use that to display before currency for all workspace money requests

## Actual Result:
App used AMD abbreviation instead of available symbol for AMD currency in workspace currency list and also for all workspace money requests

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![android native amd](https://github.com/Expensify/App/assets/93399543/6873d342-a4e4-48b1-8ae7-c09359569169)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![android chrome amd](https://github.com/Expensify/App/assets/93399543/d1e8239c-65ef-43ee-9f3a-22a762795350)

</details>

<details>
<summary>iOS: Native</summary>

 
![ios native amd](https://github.com/Expensify/App/assets/93399543/99261312-7b5c-4e1f-aca9-8babe5708ef9)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![ios safari amd](https://github.com/Expensify/App/assets/93399543/cc8afcae-5b8a-49c6-a00a-4c055127e981)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/f9c3e9cb-13f0-4924-ae06-54414539ec1d

![mac chrome amd](https://github.com/Expensify/App/assets/93399543/d0b65b1b-199d-4d4b-93e4-78a73c25af9f)

https://github.com/Expensify/App/assets/93399543/24f7acc9-d033-4c86-a2f1-c2d92119496a

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![mac desktop amd](https://github.com/Expensify/App/assets/93399543/43e68e1c-6f29-42ea-8a8d-1552d877694b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f24bbd57aff799b7</li>
        <li>Upwork Job ID: 1714021803651682304</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by cg813** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
App should use AMD symbol for AMD currency not abbreviation

**What is the root cause of that problem?**
Used abbreviation not symbol for AMD in currencyList

**What changes do you think we should make in order to solve the problem?**
Just need to change from abbreviation to symbol for AMD and check other currencies also.

<img width="1377" alt="image" src="https://github.com/Expensify/App/assets/57125237/0c8925e6-d825-4085-91c5-56b3b6e80073">

**Comment by eh2077** [comment]
It looks like not a bug, see https://www.globecountries.com/currency/amd.html

**Comment by cg813** [comment]
> It looks like not a bug, see https://www.globecountries.com/currency/amd.html

https://en.wikipedia.org/wiki/Armenian_dram

**Comment by dhanashree-sawant** [comment]
Yes please if you have any solution for it then let me know, I couldn't find a proper solution to it.

I raised it as it is inconsistent with the way we display other currencies. Not sure why are we considering it as feature, that symbol existed way back when we used dropdown for currency.

**Comment by sakluger** [comment]
According to https://www.globecountries.com/currency/amd.html, thre are two valid symbols for AMD: ֏ or դր. We are using the second valid symbol, so this is not a bug.

<img width="879" alt="image" src="https://github.com/Expensify/App/assets/5997400/bd3d2f3f-96ec-47e6-9fd7-b43b256c6cd8">
