### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] Wallet - Button to confirm bank account deletion is off-screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and must have added a BA to the wallet
1. Click on Settings
2. Click on "Wallet"
3. Click on the added BA
4. Click on "Delete" button

## Expected Result:
Button to confirm back account deletion should be on-screen, allowing the user to click on it

## Actual Result:
Button to confirm back account deletion is off-screen, so the user cannot click on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/3dd20426-c5a5-4405-9a37-e65b2017b744

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181bf24251c643efc</li>
        <li>Upwork Job ID: 1714219098497863680</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 27462333</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Santhosh-Sellavel</details>

**Comment by Victor-Nyagudi** [comment]
Judging by just how big the text is in the RHP of the attached video, I think the tester may have just been zoomed in too much. 

The button to confirm a bank account deletion appears where it should be for me (regular 100% zoom level). 

https://github.com/Expensify/App/assets/79470910/09bb94fb-a088-4af2-b986-de41af9f2b19

Maybe they could double check and share with us their zoom level to see if we can reproduce the bug.

**Comment by Santhosh-Sellavel** [comment]
@Victor-Nyagudi Try to resize the browser in a way bottom has less spacing to show the modal.

https://github.com/Expensify/App/assets/85645967/ed15896f-63b9-4dae-b091-c79f7db34ebb

**Comment by Santhosh-Sellavel** [comment]
@Expensify/design What can we do here?
Please share thoughts on this [proposal](https://github.com/Expensify/App/issues/29729#issuecomment-1765674068).

**Comment by shawnborton** [comment]
cc @pac-guerreiro can you follow up and fix this one? We shouldn't open this up as a bug, but rather it can be fixed as a follow up to the work you are doing here. cc @grgia 

In terms of how to fix, I would think we just detect how close to the bottom of the viewport we are, and if we are too close, we launch the popover above the button.

**Comment by Santhosh-Sellavel** [comment]
bump @pac-guerreiro or @grgia

**Comment by dannymcclain** [comment]
Agree with Shawn—I think they should be consistent and use the center alert modal.

**Comment by Santhosh-Sellavel** [comment]
not overdue

**Comment by laurenreidexpensify** [comment]
@pac-guerreiro just following up here - can you take on this one?

**Comment by laurenreidexpensify** [comment]
@Santhosh-Sellavel can you review pls? Thank you

**Comment by pac-guerreiro** [comment]
Sorry I missed this issue in the middle of all the notifications I get daily 😅

@laurenreidexpensify @shawnborton @grgia @Santhosh-Sellavel Am I needed here or will you accept the current proposal?

**Comment by Santhosh-Sellavel** [comment]
@pac-guerreiro 
I guess this should be handled as follow-up 

cc: @shawnborton @laurenreidexpensify

**Comment by Santhosh-Sellavel** [comment]
@grgia 
@neonbhai [proposal](https://github.com/Expensify/App/issues/29729#issuecomment-1779064176) looks good to me
🎀 👀 🎀 
C+ Reviewed

**Comment by laurenreidexpensify** [comment]
@neonbhai is there is a draft PR up yet? thanks

**Comment by dubielzyk-expensify** [comment]
Chiming in for Shawn as he's OOO. Definitely would like to see the deletion confirmation fixed as well. Agree that it should have a confirmation as it's a irreversible action.

**Comment by Santhosh-Sellavel** [comment]
@dubielzyk-expensify are you fine with this?

**Comment by dubielzyk-expensify** [comment]
When you say "this", what do you mean? It being fixed in a follow-up PR? Not a code guy so I'd rely on @laurenreidexpensify  or @grgia here :)

**Comment by Santhosh-Sellavel** [comment]
> > Chiming in for Shawn as he's OOO. Definitely would like to see the deletion confirmation fixed as well. Agree that it should have a confirmation as it's a irreversible action.
> 
> Okay @dubielzyk-expensify Thanks for replying!
> 
> Since Task flow is a different area of the app (than Bank Account/Wallet flow) and the test steps are already big for the [current PR](https://github.com/Expensify/App/pull/30882). For ease of reviewing, I will fix this in another follow-up PR.
> 

@dubielzyk-expensify About ☝️, Are we fine handling it in a separate PR, or should it be done in the [PR](https://github.com/Expensify/App/pull/30882) open for this issue?

cc: @jasperhuangg

**Comment by dubielzyk-expensify** [comment]
I'm only a designer, so I'll let the devs comment on whether it's appropriate to do it in a separate PR or not :) Sorry about that

**Comment by Santhosh-Sellavel** [comment]
cc: @jasperhuangg can you help here?

**Comment by Santhosh-Sellavel** [comment]
bump @jasperhuangg

**Comment by Santhosh-Sellavel** [comment]
@neonbhai Can you update the status please its been a week no update from you on PR

**Comment by laurenreidexpensify** [comment]
Okay so for clarity this is now being handled in https://github.com/Expensify/App/pull/30882?

**Comment by shawnborton** [comment]
Looks good to me

**Comment by Santhosh-Sellavel** [comment]
@laurenreidexpensify Can you confirm the newly added copies are good?

### En

```
 cancelTask: 'Cancel task',
 cancelConfirmation: 'Are you sure that you want to cancel this task?',
```

### Es
```
 cancelTask: 'Cancelar tarea',
 cancelConfirmation: '¿Estás seguro de que quieres cancelar esta tarea?',
```

**Comment by Santhosh-Sellavel** [comment]
bump @laurenreidexpensify

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: @neonbhai $500 payment issued in Upwork
C+: @Santhosh-Sellavel $500 please request payment in Newdot

Remaining Steps to Close: @Santhosh-Sellavel to complete checklist

**Comment by laurenreidexpensify** [comment]
Not overdue Melv

**Comment by Santhosh-Sellavel** [comment]
We can skip the checklist as it ended up as UI Polish i.e became an improvement eliminating rare bug as well., as we unified confirm actions on this page with center alert modal style following this https://github.com/Expensify/App/issues/29729#issuecomment-1775155011 

cc: @jasperhuangg @laurenreidexpensify

**Comment by jasperhuangg** [comment]
Thanks @Santhosh-Sellavel!  Does that mean we're good to close this out? Payment has been issued.

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/29729#issuecomment-1871859998).
