### ISSUE TITLE
[HOLD for payment 2023-10-27] [P2P Activation] Adding a bank account while enabling an Expensify Wallet drops you in the Wallet page rather than continuing the enablement flow

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#29726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697492929166339 

## Action Performed:
**User A:**

1. Select Request money
2. User A: enter User B as the person you're requesting from

**User B:**

1. Login
2. Navigate to the IOU report
3. Select Pay with Expensify
4. Select Bank account
5. Add a personal bank account

## Expected Result:
The user should land on the Additional details page to continue the Wallet enablement flow, which asks them for personal information.
## Actual Result:
The user lands on the wallet page , and has to go back and select Pay again.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
_Note: the first screen shows the prompt to add a bank account  or debit card when selecting Pay with Expensify  , and the second screenshot shows where you're brought after adding the account._
<img src="https://github.com/Expensify/App/assets/44479856/cf4c16fb-5879-4369-91fc-34d8c01f3aa4" width="30%"> <img src="https://github.com/Expensify/App/assets/44479856/7ac58f9b-468d-4ffd-98ce-dbf395b27711" width="30%">

https://github.com/Expensify/App/assets/44479856/26765084-871f-4349-ab32-8cf9e1b04ac7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment]
<img width="644" alt="Screenshot 2023-10-17 at 4 50 00 PM" src="https://github.com/Expensify/App/assets/75031127/1828eaea-f073-41f4-bbc5-78423e2f78cc">

@MariaHCD facing this error, is this something known?

**Comment by MariaHCD** [comment]
Ah, yes, we throttle users when adding bank accounts via Plaid 😅 I think testing with another account will work.

**Comment by MariaHCD** [comment]
Do let me know if there is overlap with https://github.com/Expensify/App/pull/29573/files#diff-186ee6dd4f2074460e09890d51b9ef7ef11bc902c32e472b58b76a060a3e4d63R367

**Comment by abdulrahuman5196** [comment]
Kindly assign me this GH for C+ review.

**Comment by getusha** [comment]
@bfitzexpensify Accepted thanks!

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression but a new expectation.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Navigate to the IOU report
2) Select Pay with Expensify
3) Select Bank account
4) Add a personal bank account
5) Choose account from drop down menu and click Save & continue > Continue
6) Verify that Additional details page is opened.


@bfitzexpensify Accepted the offer and checklist complete.

**Comment by bfitzexpensify** [comment]
Great, those steps look good to me. I opened https://github.com/Expensify/Expensify/issues/330782 for the regression test. 

All payments complete, we're all done here - thanks everyone!
