### ISSUE TITLE
[HOLD for payment 2023-12-18] [$500] RBR polish on failed split receipt scans 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#29733]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.84-4
**Reproducible in staging?:** Yes
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** (internal ref) https://expensify.slack.com/archives/C02NZ2HGJAZ/p1697493830052679?thread_ts=1697488517.137999&cid=C02NZ2HGJAZ

## Action Performed:
1. Global create > Request money > scan a picture of your receipt or a image file that will fail
2. Select 2 participants to split > confirm
3. Wait for receipt scanning to fail
4. ~Observe the split preview component in the groupDM contains a red dot that's left-aligned~ being fixed [here](https://github.com/Expensify/App/pull/30231)
5. Observe the groupDM chat in the LHN does not have a red dot on the chat row
6. Observe we're showing `Split $0.00` in the LHN preview message instead of `Receipt missing details` when a split scan fails

## Expected Result:
~The red dot for the "RBR" (red-brick-road) in a preview component should be right-aligned~ being fixed [here](https://github.com/Expensify/App/pull/30231).
The chat row in the LHN should have a RBR red dot
The LHN preview message shows `Receipt missing details` not `Split $0.00` when a split scan fails

## Actual Result:
The red dot on the preview component is left-aligned and the chat row does not have a red dot 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/090a17cd-4709-491e-91a5-4b083a851519">

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdff9c9cc073642c</li>
        <li>Upwork Job ID: 1714068202452070400</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27613990</li>
<li>dukenv0307 | Contributor | 27613993</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Same here @youssef-lr assigning this one to us for now, as I know you were working on the handling of the failure case. Equally, can you confirm if the updates coming will have `Receipt missing details` in the LHN preview message instead of `Split $0.00` when it fails or do we need to take care of that here?

**Comment by youssef-lr** [comment]
>can you confirm if the updates coming will have Receipt missing details in the LHN preview message instead of Split $0.00 when it fails or do we need to take care of that here?

Nope not included, I'll fix it as part of this issue!

**Comment by trjExpensify** [comment]
@youssef-lr are you still working on a fix for this?

**Comment by trjExpensify** [comment]
👋 @youssef-lr mind providing an update please? Thanks!

**Comment by youssef-lr** [comment]
@trjExpensify any chance we can make this external? This is just a UI polish, I'm currently prioritizing https://github.com/Expensify/App/issues/29914

**Comment by trjExpensify** [comment]
Ah actually, we might have a PR in the works for the RBR dot alignment issue: https://github.com/Expensify/App/pull/30231 (CC: @tienifr & @rushatgabhane to confirm). 

So then I think that means we need to still cover: 

1. Showing `Receipt missing details` in the LHN preview message instead of `Split $0.00` when a split scan fails
2. The chat row that contains the failed split in the LHN should have a RBR red dot for the user that created the split 

If both of those things can be worked on externally, we can ship it out.

**Comment by youssef-lr** [comment]
@trjExpensify yup I think we can have those worked on externally! Contributors can easily test failed scans by submitting an image that's not a receipt.

**Comment by trjExpensify** [comment]
Cool, let's ship it out.

**Comment by trjExpensify** [comment]
>If we want to show error even in case of 1-1 DM, we can broaden the check for that.

Can you confirm what you mean by this question? It's plausible for the split preview to be added to a groupDM (if you split with a group of people), 1:1 DM (if you split with one person) or a policyExpenseChat (the "workspace chat" in the case of splitting with Teachers Unite). So I'd say if the failed split is being previewed in the LHN of any of these chat types, it should consistently show `Receipt missing details`.

>I'm not sure if we're expecting to show Receipt missing details instead of 0.00 in case of MoneyRequestPreview as well (it's not in the 2 expectations), but if we do, we can add the same above 2nd condition [here](https://github.com/Expensify/App/blob/3db5ff4a1924156c748291d25eb9d774d82f879e/src/components/ReportActionItem/MoneyRequestPreview.js#L231)

Ah yes, good call. You're talking about here (green arrow) in the split case right? 

<img width="974" alt="image" src="https://github.com/Expensify/App/assets/16232057/19f81342-40b8-4885-abe3-017e90045a21">

**Comment by trjExpensify** [comment]
Okay cool, @Ollyws can you give this a review please? Thanks!

**Comment by trjExpensify** [comment]
@youssef-lr can you review this proposal?

**Comment by youssef-lr** [comment]
Done!

**Comment by trjExpensify** [comment]
@dukenv0307 do you have the PR up yet? Let's link it to this issue.

**Comment by trjExpensify** [comment]
Thanks, appreciate the update!

**Comment by trjExpensify** [comment]
On @youssef-lr for review.

**Comment by youssef-lr** [comment]
Merged!

**Comment by trjExpensify** [comment]
👋 checklist time please!

**Comment by trjExpensify** [comment]
>I don't think a regression test is really helpful here as it takes a long time to test for (while waiting for the recepit scan to fail) and doesn't affect the flow in any significant way.

That isn't a good reason in itself, really. A customer has the same experience and we need to make sure it works for them! We have failed scan receipt regression tests, so all good. 

As for the payments then, confirming as follows? 

- $500 to @dukenv0307 for the fix 
- $500 to @Ollyws for the C+ review

Let me know and I'll settle up tomorrow!

**Comment by trjExpensify** [comment]
Settled up, closing!
