### ISSUE TITLE
[HOLD for payment 2024-01-03] Comment doesn't update to the Merchant name in the split preview component after the receipt scan completes 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#29732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.84-4
**Reproducible in staging?:** Yes
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** (internal ref) https://expensify.slack.com/archives/C02NZ2HGJAZ/p1697490579346919?thread_ts=1697488517.137999&cid=C02NZ2HGJAZ

## Action Performed:
1. Global create > Request money > scan a receipt
2. Select 2 participants to split > add a description on the confirmation page > confirm
3. Wait for receipt scanning to complete
4. Observe the split preview component in the groupDM contains the comment
5. Observe the iouReport preview component in each of the DM's between payer:participant contains the merchant

## Expected Result:
When the receipt scanning completes, the split preview component should update with the merchant name 

## Actual Result:
When the receipt scanning completes, the split preview component remains as the `description`

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/f19a467e-b867-49cb-872e-ffbecb7fd279">

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c51bbff62b3a32f7</li>
        <li>Upwork Job ID: 1714065110591516672</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 @youssef-lr keeping this one internal and assigned to us for the time being. Maybe the work with the empty merchant has caught this one, but logging it so we have it if not.

**Comment by youssef-lr** [comment]
Working on this tomorrow.

**Comment by trjExpensify** [comment]
Same, same.. did we get a PR for this one?

**Comment by trjExpensify** [comment]
👋 [same question](https://github.com/Expensify/App/issues/29732#issuecomment-1775411451), Melv. @youssef-lr is there a PR to link to for this one yet?

**Comment by youssef-lr** [comment]
PR is ready but on HOLD until Web-E deploys!

**Comment by youssef-lr** [comment]
False alarm Melvin

**Comment by trjExpensify** [comment]
I think we're good to close this as @robertKozik payment will be handled elsewhere. Regression test for this should be covered in https://github.com/Expensify/Expensify/issues/356417 holistically.

**Comment by trjExpensify** [comment]
Oh! Sorry, I thought that was the other one!

**Comment by trjExpensify** [comment]
So @aimane-chnaif you're due $500 for the C+ review.

**Comment by trjExpensify** [comment]
Cool, offer sent.

**Comment by trjExpensify** [comment]
Paid!
