### ISSUE TITLE
[HOLD for payment 2023-10-25] [HOLD for payment 2023-10-24] [$500] Web - Chat - CreateChatReport is called (API call) even though chat is already created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue foung when executing PR https://github.com/Expensify/App/pull/29288

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in and already have a chat with '[money2020@expensify.com'.](mailto:money2020@expensify.com'.)

1. Open the console, Network tab.
2. Go to https://staging.new.expensify.com/money2020
3. Look for API call 'CreateChatReport' in the console.

## Expected Result:
CreateChatReport API should not be called, as the chat already exists.

## Actual Result:
CreateChatReport API is called.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/58a6bd2a-76ab-48b1-998e-416d7282cb29

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bb86d892414cdf5</li>
        <li>Upwork Job ID: 1714224329638465536</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27243220</li>
<li>bernhardoj | Contributor | 27243223</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Production video

https://github.com/Expensify/App/assets/115492554/f5d9133e-5eeb-4d7b-aa3c-802e2038f371

**Comment by s-alves10** [comment]
This looks like an intentional behavior by https://github.com/Expensify/App/pull/29288

**Comment by s-alves10** [comment]
I'm not able to reproduce on the latest main

**Comment by kadiealexander** [comment]
Paid!

**Comment by kadiealexander** [comment]
Bonus paid.
