### ISSUE TITLE
[$500] mWeb - IOU-Tapping download receipt opens file couldn't be accessed page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Enter amount
5. Tap next
6. Select any user
7. Tap dots and select add receipt
8. Upload any image as receipt
9. Tap request amount (After creating request perform remaining steps quickly)
10. Tap on the receipt
11. Tap on 3 dots
12. Tap download

## Expected Result:
When user taps download, he must be able to download the receipt.

## Actual Result:
When user taps download, instead of receipt download file couldn't be accessed page got opened.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/100767b6-55e7-47fc-89d6-48613a30a5a4

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b90d3669f3399384</li>
        <li>Upwork Job ID: 1714231295570866176</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This has the same RCA as https://github.com/Expensify/App/issues/27992, should be fixed by https://github.com/Expensify/App/pull/29738.

**Comment by jjcoffee** [comment]
[Confirmed](https://github.com/Expensify/App/issues/27992#issuecomment-1766547342) that https://github.com/Expensify/App/pull/29738 will fix this. I think we're good to close @CortneyOfstad!

**Comment by CortneyOfstad** [comment]
Thanks @jjcoffee!!

**Comment by lanitochka17** [comment]
Issue reproducible on latest build 1.4.8-0
mWeb/Chrome


https://github.com/Expensify/App/assets/78819774/c8341ca9-b1ec-4289-916d-4fa94f2c332d

**Comment by jjcoffee** [comment]
Interesting, thanks @lanitochka17! @CortneyOfstad can we reopen but also hold this for https://github.com/Expensify/App/pull/28618 (it's a big refactor that's hopefully gonna be merged soon)?
