### ISSUE TITLE
[$500] Compose - Pasting emoji get bit shake& full compose box shaken while pasting last emoji

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause-Internal

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on any report
3. Copy the text :heart: from any document
4. Paste it in the compose box repeatedly till the end of first row

## Expected Result:
When the user paste emoji text, it must not shaken and while pasting the last emoji in the first row, the entire compose box must not get shaken.

## Actual Result:
When the user paste emoji text, it is little bit shaken and while pasting the last emoji in the first row, the entire compose box is little bit shaken.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/3cd1e1c7-ad00-4cc2-8135-2a45e6cec8af

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3a8cc321b95f223</li>
        <li>Upwork Job ID: 1714234049242923008</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
no proposals yet

**Comment by studentofcoding** [comment]
I think the behavior is expected, as Emoji are text when pasted, and converted to Emoji only after that. Thus, space that the text (:love:) takes more than the ❤️ and make the composer expand, and shrink after the Emoji is converted

**Comment by yakupafsin** [comment]
This shouldn't be considered a bug because when we copy and paste an emoji itself, it doesn't exhibit the same issue. As @studentofcoding explained, this is because emoji codes occupy more space than the emoji itself.

**Comment by maddylewis** [comment]
noted!
