### ISSUE TITLE
[$500] Web – Chat - Unable to open chat with CTRL+Enter

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause_Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Click on the green + icon on the home screen
4. Click on Start chat
5. Use the arrow keys to highlight a chat.
6. Press CMD+Enter

## Expected Result:
The selected chat is open.

## Actual Result:
Nothing happenes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/7c713063-b812-4ad1-8d43-83d1ee4e46d4

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133f9833c7b1a9ad2</li>
        <li>Upwork Job ID: 1714258568537739264</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
Now we open the chat by pressing [Enter]. Isn't this an expected behavior?
Ctrl + Enter is used to confirm when group chat is created now

**Comment by lschurr** [comment]
Sounds good!
