### ISSUE TITLE
[$500] Chat - Strikethrough ~ is not applied when create message in different markdown combination

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29779]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Login with any account
2. Type a message *bold _italic_ bold*
3. Tap on Edit message
4. Edit a message to *bold ~_italic_ bold*~

## Expected Result:
Strikethrough text should be displayed

## Actual Result:
Strikethrough text is not displayed, only markdowns are visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/d25171d6-d416-4923-b199-c4b5bbd5361b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163a4e01015c57126</li>
        <li>Upwork Job ID: 1714286599536427008</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by AdvancedTeam100** [comment]
Hello,
My name is konno.

I'm from Japan and I'm a senior mobile developer who experience 5+ years React Native.

I'm very interested in this React Native project.

For this issue I can use some React modules for frontend edit.
this project is not expo.
I know perfect projects are all developed React CLI not expo.

please invite me on slack so that I join this project.
this is my gmail.
softfeature42@gmail.com

this is my github.
github.com/kstar0102
I focused your working on upwork for 6 months.
your working style is awesome!.
please contact me so that I start.
Thanks.

**Comment by agilejune** [comment]
@greg-schroeder @allroundexperts 
it's expected behavior. I've checked on github and discord.. 

![image](https://github.com/Expensify/App/assets/86615752/8fffa85e-58b4-46bf-9122-034dcd7c3efb)

![image](https://github.com/Expensify/App/assets/86615752/b517428c-92fc-4db8-b073-e57d9b61a85c)

**Comment by s-alves10** [comment]
I don't think this is a bug

**Comment by greg-schroeder** [comment]
I don't think it is either, I'm going to close this.
