### ISSUE TITLE
[$500] Inconsistent Usage of 'Paid' and 'Spent' in Request Money Details

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697547094539339

## Action Performed:
1. Login to any Account A
2. Click on the FAB button >> select "Send Money"
3. Send Money to any contact using the "Pay elsewhere" option.
4. Observe that on the LHN, the request is displayed as "A paid X"
5. Click on the request to view its details.
6. Observe that the request now shows as "A spent X" - which is inconsistent with the IOU preview.

## Expected Result: 
The labels 'Paid' or 'Spent' should remain the same both before and after viewing the details

## Actual Result: 
Inconsistent Usage of 'Paid' and 'Spent' in Request Money Details

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/f3216f7c-0791-4f33-a795-750f61e02a6d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/99e2fc64-30f6-4e47-94e2-f722e7918b2f

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/cf2fb50a-9682-4f00-bb05-a7fd64b33423

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/73dc6908-7446-4760-b67c-13d6cb01562e

https://github.com/Expensify/App/assets/38435837/b71c4cbf-28af-464b-9b63-825102ec3f5a

https://github.com/Expensify/App/assets/38435837/4a683e7f-89c6-4708-9d80-3aa38a16d0d9

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/62ad6ebb-6151-44cd-aa63-b0c1a32c0a1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c684e7bddef28b1a</li>
        <li>Upwork Job ID: 1714321363006427136</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent Usage of 'Paid' and 'Spent' in Request Money Details](https://github.com/Expensify/App/issues/29796#top)

### What is the root cause of that problem?
We use `iou.payerSpent` and `iou.payerSpentAmount` in `src/libs/ReportUtils.js`, `src/libs/actions/IOU.js` and `src/components/ReportActionItem/ReportPreview.js`

### What changes do you think we should make in order to solve the problem?
Change all `...Spent...` to `...Paid...` in order to standardize and make everything the same.

### What alternative solutions did you explore? (Optional)
Maybe change them all to `Spent`

**Comment by brunovjk** [comment]
Contributor details
Your Expensify account email: brunovjk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014c57bd327ebd58f4

**Comment by Tony-MK** [comment]
Not reproducible in staging or dev environments.

**Comment by tranvantoan-qn** [comment]
I think, In this context, **Paid** is more appropriate as it signifies a transaction between two accounts, while **Spent** has a broader, more general meaning

**Comment by brunovjk** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/29796#issuecomment-1767181884)

**Comment by grgia** [comment]
@Ollyws do any of the proposals look good to you?

**Comment by grgia** [comment]
Let's close out then!

**Comment by tranvantoan-qn** [comment]
There was obviously an issue with that label, I should be eligible for a reporting bonus.
So, what do you think @Ollyws  @grgia?
