### ISSUE TITLE
[HOLD for payment 2023-10-30] DRY up the logic for the backTo param in ROUTES.ts

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29799]
# Problem
There is repeated code in ROUTES.ts that adds an optional `backTo` parameter to URLs.

# Why is this important?
If it is not DRY, then is more difficult to maintain and keep consistent

# Solution
Move the code into a method called `addBackToParam()` that is used in the routes that need it
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7e63f69a8031ac1</li>
        <li>Upwork Job ID: 1714329935530221568</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by tgolen** [comment]
@kevinksullivan Can you please facilitate the payment for @Ollyws reviewing the PR?

**Comment by tgolen** [comment]
Ah phooey, I missed that regression :(

**Comment by tgolen** [comment]
I think I'll just close this out then without payment.

**Comment by tgolen** [comment]
I am so sorry about that! I needed to read up on [the payment rules for regressions](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions). I'm reopening this and @kevinksullivan can you please pay @Ollyws 50% of the original compensation.

**Comment by tgolen** [comment]
bump @kevinksullivan Can you please help with payment here?

**Comment by tgolen** [comment]
Pinged Kevin 1:1

**Comment by kevinksullivan** [comment]
offer sent @Ollyws , let me know when you accept!

**Comment by kevinksullivan** [comment]
all set!
