### ISSUE TITLE
[$500] double click copy emoji text from emoji reaction popup copies extra text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697548457443249

## Action Performed:
Precondition: user should have default avatar
1. Open the app
2. Open any report
3. React to any message
4. Right click on reaction to open reaction popup
5. Double or triple click on emoji text to select the emoji text and copy it
6. Paste the text in any other source other then composer or in private notes and observe that it has long random text copied with the emoji text
## Expected Result: 
App should only copy the emoji text when we select it and copy from emoji reaction popup
## Actual Result: 
App copies long random text after the emoji text when we select it and copy from emoji reaction popup (works only when user has default avatar)

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/e0bae0e9-aecb-4665-bc95-63ed44e29f4e

screenshots or videos here -->

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/c8b3a7b1-227f-4f8d-9c85-56846b92309d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/30f23fca-eedf-49f5-bd17-dba16700ac8c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/67d3578d-7b8e-4088-bad1-91cfb45b270a

https://github.com/Expensify/App/assets/38435837/95599e92-b48b-4c2d-bdb2-f7cfca7dc6c5

https://github.com/Expensify/App/assets/38435837/cd8b015c-af70-4e2b-8296-d8ddd27f25eb

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/351ae558-ccee-44db-ae67-6e3cf1d7c46c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c569bc02f4a737f5</li>
        <li>Upwork Job ID: 1714314373921427456</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
I agree with [the earlier reasons for closing](https://github.com/Expensify/App/issues/24399#issuecomment-1703460153), and will close again now! Thanks all
