### ISSUE TITLE
[HOLD for payment 2023-10-25] [HOLD for payment 2023-10-24] Login - User is not automatically logged in with magic link in different tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com./
2. Enter any email you have access to
3. Go to email inbox and look for the magic link
4. Go to different tab, change the link to staging and go to it
5. Abracadabra page should be displayed
6. Go to original tab

## Expected Result:
User should be automatically logged in and able to use the app on the original tab

## Actual Result:
User must refresh the page to appear logged in and use the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/86808da8-fdc6-4d1b-b69e-36a6e9c064b1

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
[This pull request](https://github.com/Expensify/App/pull/28372) just made it to staging and modified some sign-in logic. Not sure yet if it's the culprit but sounds like a possibility.
cc @NikkiWines @MonilBhavsar if you're around and have an idea.

**Comment by francoisl** [comment]
I reverted 28372 on dev and can still reproduce the issue, so I don't think it's that.

**Comment by thienlnam** [comment]
:hmm: If it's not that, it probably is related to some subscriber on the login page that is no longer prompting a refresh. I am looking at changes on that page but not seeing anything obvious

**Comment by alitoshmatov** [comment]
This issue is originating from this line: 
https://github.com/Expensify/App/blob/0a3ce767f12802d184c434efe2790dea5188af1a/src/libs/Navigation/AppNavigator/AuthScreens.js#L370-L372
If we remove retrieving `demoInfo` the issue won't happen. But I couldn't find why this is happening, I thought it was because we are accessing onyx data which is not present, but changing `key` here to any random string did not produce this issue. So the issue is only happening for `demoInfo`

**Comment by francoisl** [comment]
Yeah thanks. Just finished a `git bisect` and found that the issue comes from [this PR](https://github.com/Expensify/App/pull/29288), specifically [this commit](https://github.com/Expensify/App/commit/833cc72ba5eba533c8fafd3c11e35c81caa9ad9c), which matches what you found.

**Comment by francoisl** [comment]
@s77rt do you have any idea off the top of your head? This appears to be coming from https://github.com/Expensify/App/pull/29288.

**Comment by s77rt** [comment]
Hmm, we used same patterns for similar temporary flows. Could it be related to this https://github.com/Expensify/App/pull/29288/files#r1358416934? Can you try use `Navigation.isNavigationReady` promise and see if that fixes it?

cc @alitoshmatov if you are available to test

**Comment by alitoshmatov** [comment]
Doing this didn't work
<img width="565" alt="Screenshot 2023-10-18 at 01 31 28" src="https://github.com/Expensify/App/assets/59907218/a7a29d7a-5bfe-4765-a1f0-25ea3cf22998">

cc: @s77rt

**Comment by francoisl** [comment]
I feel like it's some sort of race condition with updating a key in Onyx? Commenting [this line](https://github.com/Expensify/App/blob/c498ab5abd8c6f2ebb5552efbaf687ea2bdd95de/src/libs/actions/DemoActions.js#L66-L66) out solves the issue.

**Comment by alitoshmatov** [comment]
Removing that line looks reasonable and is not effecting expected behavior, and it tests well.

**Comment by francoisl** [comment]
Alternatively changing it to `Onyx.set(ONYXKEYS.DEMO_INFO, {});` _seems_ to work, but I can't 100% confirm at the moment as my dev environment is in a weird half-broken state. Might be better than removing the line entirely, if we can confirm it works.

**Comment by alitoshmatov** [comment]
It is working.
https://github.com/Expensify/App/assets/59907218/069cc554-c963-4b43-9ba5-5985735f863c

**Comment by francoisl** [comment]
Nice. @thienlnam let's roll with that?

**Comment by francoisl** [comment]
I fixed my dev environment, sending a PR shortly.

**Comment by zanyrenney** [comment]
Should be all good here as the payment is being handled here - https://github.com/Expensify/App/issues/29577 !
