### ISSUE TITLE
Log in - There is no error message when trying to log in into an account with SAML required

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Pre-requisite: user must have previously configured SAML enabled and required for the account
1. Open New Expensify app
2. Enter email address
3. Tap on "Continue" button

## Expected Result:
There should be an error message indicating that you cannot log into an account with SAML required

## Actual Result:
No error message is displayed at all and the user is unable to log in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/4d91a560-0b45-40da-91a0-270ec0a1d0cc

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
cc @NikkiWines this sounds like https://github.com/Expensify/App/pull/28372. However I believe it's already not possible to sign in on production with SAML required, so it might not be a blocker.

**Comment by francoisl** [comment]
Production asks you for a magic sign-in code and you can't sign in, so we can consider this a follow-up bug for SAML implementation. Going to remove the blocker label and reassign to Nikki.

**Comment by NikkiWines** [comment]
Yes, it's true you can't currently sign in on prod with SAML required but we previously showed an error message for this so the experience is somewhat confusing. This behavior is occurring because we're trying to roll out SAML sign in to users on desktop, web, and mweb but there's [this logic](https://github.com/Expensify/Web-Expensify/blob/010530f97486d4ce08cf3ebf8b36090477cce11c/lib/UserAPI.php#L3504-L3507) in Web-E that prevents SAML required users from signing in. 

For the moment I this is better than the current alternative because the redirect logic back to newDot for SAML users isn't working - so we shouldn't be auto-initiating that flow for SAML required users right now

**Comment by NikkiWines** [comment]
So yes this isn't a deploy blocker

**Comment by NikkiWines** [comment]
This should be handled with https://github.com/Expensify/Web-Expensify/pull/39419

**Comment by NikkiWines** [comment]
Closing now that https://github.com/Expensify/Web-Expensify/pull/39419 is on production
