### ISSUE TITLE
[$500] Tooltip position shifts after closing the FAB menu.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697539954070869

## Action Performed:
1. Hover over the FAB icon.
2. Click on the FAB icon to open the menu.
3. Click on the FAB icon again to close the menu.
## Expected Result: 
The tooltip position should remain unchanged.
## Actual Result: 
The tooltip position shifts.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/069146d5-6159-498f-9a98-6673ba8985d0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/49e0a4a7-ed52-495f-86ab-ca67de6252af

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/cce10c58-950e-4e38-a82b-30e4c7c10817

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/10cde7b8-d0c0-4761-9291-42882c6393dd

https://github.com/Expensify/App/assets/38435837/18bba09f-133f-4cef-a4e6-d4b94ecd25b0

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/60bf3ba8-5b1d-441e-a726-5d1a3dfbe441

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016000d4226e1474d7</li>
        <li>Upwork Job ID: 1714349256585392128</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
Looks similar to this - https://github.com/Expensify/App/issues/29678.
And verified that my solution provided in this proposal does resolve this issue - https://github.com/Expensify/App/issues/29678#issuecomment-1764752009

**Comment by s77rt** [comment]
A dupe indeed! Thanks @alitoshmatov 

@trjExpensify Let's close this

**Comment by trjExpensify** [comment]
Sounds good!
