### ISSUE TITLE
[$500] Chat - # in between link does not break the link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697531494920739

## Action Performed:
1. Open the app
2. Open any report
3. Send any link eg: google.com
4. Edit the message
5. In the link part, add  # in between domain name and save
6. Observe that app still considers that as link instead of breaking the link before and after #

## Expected Result:
App should break the link if # is added in between the domain as it normally does when sending link with # in it normally without edit

## Actual Result:
App does not break the link if # is added in between the domain while editing (works fine if sent directly with # between the domain)

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/b3c2c8a8-08d3-425d-bbc3-d2742e35fcfc

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/f65fb83b-1e32-4636-8b40-ede5309a3ad9

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/4ea5efc8-58b4-4677-a691-1b021e188539

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/8b008efa-40a2-4c65-8449-2ca1a411d8d0

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/681e3796-709b-4601-9195-f6acbb435bd5

https://github.com/Expensify/App/assets/93399543/d2fbc8fd-3e57-4390-90de-460bacdac330

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/4144cc13-d567-415f-bbed-e721e4b3a80f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e7a9de583cc098a</li>
        <li>Upwork Job ID: 1714350935761924096</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
I'm not sure this is a bug. In slack, "https://goo#gle.com" doesn't break too.

**Comment by mallenexpensify** [comment]
Interesting, I know of `#` used in links like CONTRIBUTING.md#slack-channels to direct to that header on a page, like
- https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#slack-channels

@dhanashree-sawant, can you think of an instance anyone would ever enter a `#` inside a top-level domain?
I don't, but I also get your reasoning behind this being a bug, if we know the link doesn't lead to a real website, we shouldn't hyperlink it.    That said.... www.kdjfkdjkfldjiih.com might not be a real website either and we have no way of being certain of that, but we still link to it.   

Did a few tests and seeing the below, I'm unsure of a better way to show the links
<img width="229" alt="image" src="https://github.com/Expensify/App/assets/22508304/9e129430-b087-423b-9d6c-02cb842ed173">

**Comment by mallenexpensify** [comment]
Thanks, Fedi! Gonna close

**Comment by dhanashree-sawant** [comment]
Hi @fedirjh, @mallenexpensify the problem here is # in domain name, that is invalid URL

**Comment by dhanashree-sawant** [comment]
Slack is better in this case though. While raising the issue, I checked the URL validity with JS based URL validation regex available here:
https://www.regextester.com/94502
Not sure if that is accurate.
Currently if we add '%' in place of '#' then we properly recognize it as invalid and break the URL accordingly
