### ISSUE TITLE
[Awaiting Checklist Completion] [$500] Hovering over multiline link for few times removes message background color

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697542987624259

## Action Performed:
1. Open the app
2. Open any report
3. Send multiline link with one line space in between
4. Hover over them back and forth for few times
5. Observe that app removes background color from message and hovering over whole length of message still doesn't enable background color
## Expected Result: 
App should not remove background color from messages when we are hovering on it
## Actual Result: 
App removes background color from messages even when we are hovering on it if we hover back and forth on multline link for few times

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/1401db85-fc04-46b1-9fb7-7cb6d51550ab

https://github.com/Expensify/App/assets/38435837/b7a60fa7-b893-44a2-80ca-30f1bebafaad

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/272ed95b-7eb4-41a8-8a9a-5c8e8bfe6f00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1eee5b08ec459f3</li>
        <li>Upwork Job ID: 1714379542416052224</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27488648</li>
<li>bernhardoj | Contributor | 27488649</li>
<li>dhanashree-sawant | Reporter | 27488650</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @0xmiroslav</details>

**Comment by ashuvssut** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The `ReportActionItem` component loses focus when we hover on the tooltip of a link

### Root cause 
Here's a **Video with voiceover** explaining the Root cause
> (Please unmute video)
 
https://github.com/Expensify/App/assets/60546840/a63abf8f-7739-4619-8023-dfd8019ef341
 
This issue is caused when we hover on the tooltip of the link,

### My solution that fixes this issue:-

https://github.com/Expensify/App/blob/c585d31f71771252e82d19f4dab53cc16ddfa538/src/components/Hoverable/index.js#L123-L125

"mouseover" event is not appropriate to detect if mouse is hovered outside
We should use "mouseleave" instead

**Comment by twisterdotcom** [comment]
@0xmiroslav let me know what you think of @ashuvssut or @bernhardoj's proposals.

@ashuvssut - I do think the video is nice, but could you follow the normal template in future please?

**Comment by ashuvssut** [comment]
@ashuvssut, I had a proposal before. But when I saw at @bernhardoj's proposal, I realized that my solution was wrong. So, I removed my proposal 😅

**Comment by twisterdotcom** [comment]
Shall we get @bernhardoj on this then @0xmiroslav?

**Comment by twisterdotcom** [comment]
bump @0xmiroslav

**Comment by deetergp** [comment]
I agree with @0xmiroslav, let's go with @bernhardoj 👍

**Comment by twisterdotcom** [comment]
Ah, I was OOO yesterday. Doing this now.

**Comment by twisterdotcom** [comment]
Payment Summary:
@bernhardoj paid $500 [here](https://www.upwork.com/nx/wm/offer/27488649) (Contributor)
@0xmiroslav paid $500 [here](https://www.upwork.com/nx/wm/offer/27488648) (Reviewer)
@dhanashree-sawant paid $50 [here](https://www.upwork.com/nx/wm/offer/27488650) (Reporter)

@0xmiroslav please complete the checklist.
