### ISSUE TITLE
[$500]  iOS - BA - When minimizing the app on the Onfido page, the process is restarted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27432
## Action Performed:
Pre-requisite: user must be logged in
1. Go to Settings > Workspaces > Any workspace > Connect Bank Account > Add manually
2. Complete the process until your reach the Onfido page
3. Initiate the process
4. Minimize the app
5. Open New Expensify again

## Expected Result:
The app should resume the process already in place

## Actual Result:
The Onfido process is restarted, creating multiple processes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/fdc18183-491f-4b43-b849-b2d8a01d5b9d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dffa0a3c07ac7498</li>
        <li>Upwork Job ID: 1714359167020355584</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by studentofcoding** [comment]
I think this is in Onside part, and not the bug in our end

**Comment by Victor-Nyagudi** [comment]
I believe this is intentional. 

If a user leaves the app during the photo phase, them being redirected to the screen just before taking a picture informs them what it is they were taking a picture of.

Should a user minimizes the app and stay away for a long time, they'll probably be confused why the camera is open and will most likely navigate back to find out what it is they were doing in the first place.

**Comment by muttmuure** [comment]
Closing!
