### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Remove the selected participants from the search results in the split / group chat flow

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#29836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Version 1.3.83-1 (1.3.83-1)
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1697553482299739

## Action Performed:
Break down in numbered steps
1. From the global create menu, send a message or request money
2. Select a bunch of participants and then search for a user that is not in the list

## Expected Result:
When you start searching, the selected participants should not show up unless they are part of the search results. 
When the search text is empty, the selected participants should show up again

## Actual Result:
Selected participants are always in the option list

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, but it's confusing on smaller screens

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://files.slack.com/files-pri/T047TPA624F-F061DSHBHAS/screenshot_2023-10-17_at_3.55.35_pm.png
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fdba16a8b2fba60</li>
        <li>Upwork Job ID: 1714445993688682496</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27519943</li>
<li>dukenv0307 | Contributor | 27519945</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Waiting to add external until we confirm this is the desired functionality https://expensify.slack.com/archives/C05RECHFBEW/p1697553482299739

**Comment by abdulrahuman5196** [comment]
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/29836#issuecomment-1767485951 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by thienlnam** [comment]
Due to the urgency on this - I'm going to take the PR so we can get it merged today, since I'm using part of Dukes solution we can do a partial payment since it appears to be 1am in your time

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Implementation of new expectation.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) From the FAB, send a message or split bill
2) On the participants selector, add a couple participants to the group / split
3) Verify that you see them at the top
4) Start searching for a user and verify the selected participants are gone
5) Search for a user that you have selected and verify they show up in the search results
6) Verify that when you search for something, the selected participants disappear unless they are part of the search results

@kevinksullivan

**Comment by danielrvidal** [comment]
I think @kevinksullivan is off until next week so will get back to it then. I don't have test rail set up unfortunately so couldn't figure out where to put the tests.

**Comment by thienlnam** [comment]
Just a note here @kevinksullivan when you get back, this was a deploy blocker and required an urgent fix so I used part of @dukenv0307's solution and added it myself so that only requires a partial payment (I believe 50% is fair?)

And then full payment for the C+ that reviewed the [PR](https://github.com/Expensify/App/pull/29903) 

You may need to adjust the automated offers that were sent out

**Comment by kevinksullivan** [comment]
@abdulrahuman5196 can you accept the offer in upwork? Lmk here once you've done so!

**Comment by kevinksullivan** [comment]
Paid @dukenv0307

**Comment by abdulrahuman5196** [comment]
@kevinksullivan  accepted the offer

**Comment by kevinksullivan** [comment]
all set
