### ISSUE TITLE
[HOLD for payment 2023-10-27] [HOLD for payment 2023-10-25] [$250]  Chat - Deleting message in chat causes black screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @ayazhussain79 /Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697570868725089

## Action Performed:
1. Login in to New Expensify App
2. Go to any chat
3. Send any message
4. Hold comment and select delete message

## Expected Result:
Message is deleted and user and continue to chat

## Actual Result:
Black screen appears and user can not use app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/88c93519-530a-401c-b0f9-bef6fe058bdc

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141195528274e1c9e</li>
        <li>Upwork Job ID: 1714467113988296704</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27251966</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
Yup, I'm able to reproduce this

https://github.com/Expensify/App/assets/42940078/d5d2faf9-0c4a-4eec-93bd-fb94f6bd7b87

**Comment by youssef-lr** [comment]
Investigating

**Comment by youssef-lr** [comment]
I'm seeing this error in the console, still investigating what's causing this

<img width="858" alt="Screenshot 2023-10-18 at 10 22 16" src="https://github.com/Expensify/App/assets/9680864/dab35541-8b10-4794-8a3e-6cbc244c0748">

**Comment by youssef-lr** [comment]
Thanks @tienifr! Agreed, we need to bring back that HOC. I'll be adjusting the price if you don't mind since this is a straight revert.

**Comment by Julesssss** [comment]
^ PR is in review, then I'll CP it and remove the deploy blocker label

**Comment by blazejkustra** [comment]
@youssef-lr I agree that we should revert the PR for now, but the underlying issue still remains. Looking at the [Expensify.js](https://github.com/Expensify/App/blob/main/src/Expensify.js#L200) (almost root of the app), we can clearly see that some components are rendered outside of navigation context:
```ts
            {shouldInit && (
                <PopoverReportActionContextMenu ref={ReportActionContextMenu.contextMenuRef} />
                ... // other components
            )}

            {hasAttemptedToOpenPublicRoom && (
                <NavigationRoot
                    onReady={setNavigationReady}
                    authenticated={isAuthenticated}
                />
            )}
```

`PopoverReportActionContextMenu` is outside of navigation context -> therefore `Button` is outside as well. That's what is causing the crash.

**Proposal**:
Move `GrowlNotification`, `PopoverReportActionContextMenu`, `EmojiPicker`, `UpdateAppModal` and `ConfirmModal` inside Navigation Context and remove `withNavigationFallback` HOC.

FYI `withNavigationFallback` HOC is just a [workaround](https://github.com/software-mansion-labs/expensify-app-fork/blob/bb22e06a1cdd9b87fab7a2c1aa79bb9d9386e3b5/src/components/withNavigationFallback.js#L10), it mocks the context:
```ts
const navigationContextValue = useMemo(() => ({isFocused: () => true, addListener: () => () => {}, removeListener: () => () => {}}), []);
```

**Comment by youssef-lr** [comment]
That sounds good @blazejkustra, would you to raise the PR now?

**Comment by blazejkustra** [comment]
@VickyStash Could you do it as part of the `withNavigationFallback` migration issue?

**Comment by VickyStash** [comment]
@blazejkustra Yes, I think so

**Comment by ayazhussain79** [comment]
Could someone please confirm which one was reported first? I submitted the same bug report approximately 15 hours ago.
https://expensify.slack.com/archives/C049HHMV9SM/p1697570868725089

**Comment by sophiepintoraetz** [comment]
Okay @youssef-lr - can you confirm the payment summaries here:

- Reporter @ayazhussain79 $50
- Contributor @tienifr $250
- Reviewer/C+ @situchan $500

**Comment by youssef-lr** [comment]
I think the C+ payment is usually the same as the contributor's? Otherwise looks good!

**Comment by sophiepintoraetz** [comment]
@situchan - would you mind completing the checklist as well, please?

**Comment by situchan** [comment]
Bonus might apply for low price issues as well.
ref: https://github.com/Expensify/App/issues/29639#issuecomment-1775710362

**Comment by sophiepintoraetz** [comment]
That's a misunderstanding - no urgency bonus applies here!
