### ISSUE TITLE
[HOLD for payment 2023-10-27][$500] Manual - Attachment placeholder is shown in preview instead of receipt after adding a receipt

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR:** https://github.com/Expensify/App/pull/29474

**Version Number:** v1.3.86-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat > + > Request money > Manual.
3. Enter amount and proceed to confirmation page.
4. Click 3-dot menu > Add receipt.
5. Select a receipt.

## Expected Result:
The receipt will appear in the preview in the confirmation page.

## Actual Result:
The preview in the confirmation page shows the attachment placeholder instead of the receipt.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/71e3bdeb-90ab-4e4a-895d-702fd2bcfa18

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c60a9f52756a7c9e</li>
        <li>Upwork Job ID: 1714605323478552576</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27261363</li>
<li>c3024 | Contributor | 27261368</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not repro in production

https://github.com/Expensify/App/assets/115492554/357cdf92-398b-4259-be03-c3092dba948b

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Image is not shown in confirm page when creating a scan money request
### What is the root cause of that problem?
We get the image and thumbnail from here
https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/components/MoneyRequestConfirmationList.js#L539
but when we have not created the transaction yet there is no source or file name for the transaction and this returns this
https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/libs/ReceiptUtils.ts#L64
and the image is generic image here
https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/libs/ReceiptUtils.ts#L51
### What changes do you think we should make in order to solve the problem?
We should check if the transaction does not have a source and we should get the image and thumbnail with iou receiptPath and filename
So we change this code 
https://github.com/Expensify/App/blob/39d2a8457897439ebab57cf446fc23e90c553a8d/src/components/MoneyRequestConfirmationList.js#L539
to something like this
```js
if (!transaction.source) {
    const uris = props.receiptPath && props.receiptFilename 
        ? ReceiptUtils.getThumbnailAndImageURIsFromIOU(props.receiptPath, props.receiptFilename)
        : {};

    receiptImage = uris.image;
    receiptThumbnail = uris.thumbnail;
} else {
    const uris = props.receiptPath && props.receiptFilename 
        ? ReceiptUtils.getThumbnailAndImageURIs(transaction)
        : {};

    receiptImage = uris.image;
    
```
and add the function which we were using earlier in ReceiptUtils like this
```js
function getThumbnailAndImageURIs(path: string, filename: string): ThumbnailAndImageURI {
    const isReceiptImage = Str.isImage(filename);

    // For local files, we won't have a thumbnail yet
    if (isReceiptImage && (path.startsWith('blob:') || path.startsWith('file:'))) {
        return {thumbnail: null, image: path};
    }

    if (isReceiptImage) {
        return {thumbnail: `${path}.1024.jpg`, image: path};
    }

    const {fileExtension} = FileUtils.splitExtensionFromFileName(filename) as FileNameAndExtension;
    let image = ReceiptGeneric;
    if (fileExtension === CONST.IOU.FILE_TYPES.HTML) {
        image = ReceiptHTML;
    }

    if (fileExtension === CONST.IOU.FILE_TYPES.DOC || fileExtension === CONST.IOU.FILE_TYPES.DOCX) {
        image = ReceiptDoc;
    }

    if (fileExtension === CONST.IOU.FILE_TYPES.SVG) {
        image = ReceiptSVG;
    }

    return {thumbnail: null, image};
}
```
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
#29794 which changed the passing of receipt file and name to the getThumbnailAndImageURIs to passing transaction as parameter

**Comment by cristipaval** [comment]
[@fedirjh I think ](https://github.com/Expensify/App/pull/29474)this PR introduced this regression, and @youssef-lr reported it already [here](https://github.com/Expensify/App/pull/29474#issuecomment-1766994777)

**Comment by cristipaval** [comment]
> #29794 which changed the passing of receipt file and name to the getThumbnailAndImageURIs to passing transaction as parameter

@c3024 I think you copy-pasted the wrong PR, didn't you?

**Comment by c3024** [comment]
Yes. Sorry #29474 it is.

**Comment by c3024** [comment]
@fedirjh I think it is better to pass the params props.receiptPath and props.receiptFileName and ignore them if transaction has source and filename. I added an alternative solution with this logic.

**Comment by cristipaval** [comment]
Thank you!

**Comment by cristipaval** [comment]
> - [ ] [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@garrettmknight , could you please create a GH issue with the regression steps suggested by @fedirjh in the previous comment?

**Comment by garrettmknight** [comment]
Done!

**Summary of payments:**

- Urgency bonus: Yes
- Contributor: @c3024 750 paid via Upwork
- Reviewer: @fedirjh $750 paid via Upwork

**Comment by mallenexpensify** [comment]
Is this the same issue? 
https://expensify.slack.com/archives/C049HHMV9SM/p1705360701588059

**Comment by garrettmknight** [comment]
Planned here: https://github.com/Expensify/App/issues/31432
