### ISSUE TITLE
[$500] WS - Track distance rate is updated on device B even if device A was offline. No error message.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Login with the same account in the main testing device A and a secondary device B
2. Create workspace or go to the existing one
3. On the main testing device A navigate to Workspace settings > Reimburse expenses
4. Turn off the internet connection on the device A
5. Change the Distance rate to any number
6. Verify the field is grayed out after entering the number, indicating it's pending to be updated
7. On the Secondary device B navigate to Workspace settings > Reimburse expenses
8. Change the distance rate
9. On the main testing device A enable the internet connection
10. Verify that an error message is shown (red dot is present) and the track distance rate has changed to the one entered on device B

## Expected Result:
An error message is shown (red dot is present) and the track distance rate has changed to the one entered on device B

## Actual Result:
No error message. The track distance rate did not changed on device A but changed on device B.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/115492554/e2866a9c-2b1b-4895-a891-53dd257cb084

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6380dfee0ad4833</li>
        <li>Upwork Job ID: 1714602139599908864</li>
        <li>Last Price Increase: 2023-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28013831</li>
<li>bernhardoj | Contributor | 28013833</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @maddylewis</details>

**Comment by chiragkcodes** [comment]
Identified the PR that introduced this issue - [PR](https://github.com/Expensify/App/pull/29700)
Due to changes in the PR, we are not sending ```lastModified``` in policy update payload while updating reimbursement rate and unit when **Offline**
This is causing the queued request (after coming online) to override the latest rate and unit.

Note: Reverting PR will re-introduce [Issue](https://github.com/Expensify/App/issues/28942)

**Comment by AmjedNazzal** [comment]
@narefyev91 @mountiny I'm not sure I understand this one, can you help me understand why this is an issue and a deploy blocker? what exactly is the issue when a pending offline change overrides a change made on the same account that is online? because I knew this will obviously be the resulting behaviour and thought it was okay

**Comment by francoisl** [comment]
The idea is that we want to avoid multiple devices from overriding changes from each other while one is offline. I could be swayed either way that this is actually a bug or not, but it's an edge case so I'll remove the blocker label for now and we can have a broader discussion on whether we want to fix it later.

---

For reference, here's the error that you get with the production version

<img height="400" alt="Screenshot 2023-10-18 at 12 31 28 PM" src="https://github.com/Expensify/App/assets/2229301/447b3bf0-ae50-4b73-98fa-35521b662b49"> <img height="400" alt="Screenshot 2023-10-18 at 12 31 21 PM" src="https://github.com/Expensify/App/assets/2229301/2fa0f06e-2550-450a-b64b-b7000303f8fb">

**Comment by maddylewis** [comment]
@AmjedNazzal - let us know if you've reworked your proposal at all! https://github.com/Expensify/App/issues/29853#issuecomment-1769226632

**Comment by maddylewis** [comment]
@bernhardoj - based on your comment here, should we keep this open to review proposals for a fix? or, can we close this out as resolved? https://github.com/Expensify/App/issues/29853#issuecomment-1795687043

**Comment by narefyev91** [comment]
@maddylewis if issue should be fixed on BE side - maybe it should be go to internal BE dev to investigate?

**Comment by maddylewis** [comment]
moved to internal based on this comment here - https://github.com/Expensify/App/issues/29853#issuecomment-1802084396

**Comment by maddylewis** [comment]
@francoisl - lmk what you think we should move forward with a BE fix based on this comment - https://github.com/Expensify/App/issues/29853#issuecomment-1802084396

**Comment by maddylewis** [comment]
bump on this comment - https://github.com/Expensify/App/issues/29853#issuecomment-1808322604

**Comment by francoisl** [comment]
The backend change to include the `lastModified` in the response when we update the workspace's name is in review. I'll post another comment when it's deployed, so we can go ahead and start using it again when we update the distance rate.

**Comment by francoisl** [comment]
All right, the backend will now return a `lastModified` for the `UpdateWorkspaceGeneralSettings` API command.

<img width="1066" alt="image" src="https://github.com/Expensify/App/assets/2229301/d1023178-cb87-4e5b-980a-beb1cbbf87c1">

Going to mark this back as External so we can update NewDot now.

**Comment by francoisl** [comment]
@maddylewis small bump on payment when you a chance.

**Comment by maddylewis** [comment]
Plz move to daily when ready for payment - ty! Reviewing now :)

**Comment by maddylewis** [comment]
@bernhardoj paid / offer sent to @Ollyws

**Comment by maddylewis** [comment]
@Ollyws is also paid! 👍

**Comment by bernhardoj** [comment]
@maddylewis hi, sorry, but I just rechecked the Upwork offer and looks like it's not paid yet for me. Can you please recheck this on your end?

<img width="986" alt="image" src="https://github.com/Expensify/App/assets/50919443/63ece95b-839b-4326-a4fe-6e902d798803">

**Comment by francoisl** [comment]
@maddylewis bump on the above ^
