### ISSUE TITLE
[HOLD for payment 2023-10-27] [HOLD for payment 2023-10-25] [$500] IOU-Tapping on distance receipt, the receipt thumbnail is missing in the receipt page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money-- Distance
4. Enter start and finish waypoints
5. Tap next
6. Select a Workspace
7. Tap Request
8. Tap on the distance IOU created
9. Tap on the receipt

## Expected Result:
When user taps on receipt, the receipt thumbnail must be shown in the receipt page.

## Actual Result:
When user taps on receipt, the receipt thumbnail is missing in the receipt page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/7280c6b7-d761-4fce-b3c0-507d1e49ca5f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

![Bug6241408_1697612465759!Screenshot_2023-10-18-12-13-50-948_com android chrome](https://github.com/Expensify/App/assets/115492554/8cfa88db-477c-49bc-88a5-523d6cf9cc5b)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/f2014dd5-395c-4938-ade8-cda62207a4c7

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d1b9028b2d4c9f2</li>
        <li>Upwork Job ID: 1714584537318621184</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27259293</li>
<li>tienifr | Contributor | 27259295</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/77373eb0-f135-47a5-8903-6a395c7175b2

**Comment by AliYar-Khan** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping on distance receipt, the receipt thumbnail is missing in the receipt page

### What is the root cause of that problem?
getThumbnailAndImageURIs function gets the transaction as parameter

https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/libs/ReceiptUtils.ts#L28


but we pass the wrong params here

https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/components/DistanceEReceipt.js#L34

### What changes do you think we should make in order to solve the problem?
change this line

https://github.com/Expensify/App/blob/e8cb124e83c9ce588c1fb4402827880839ed88e9/src/components/DistanceEReceipt.js#L34

to

    const {thumbnail} = TransactionUtils.hasReceipt(transaction) ? ReceiptUtils.getThumbnailAndImageURIs(transaction) : {};

**Comment by isabelastisser** [comment]
I processed the payment in Upwork. All set!
