### ISSUE TITLE
The receipt image is not displaying on the confirmation modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697631191229619

## Action Performed:
1. Open a chat.
2. Go to Request money > Manual.
3. Enter an amount and proceed to the next step.
4. Click on the three-dot menu and upload a receipt.
5. Notice that the receipt is not showing on the confirmation modal

## Expected Result:
he receipt image should be displayed on the confirmation modal

## Actual Result:
The receipt image is not showing on the confirmation modal

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/eb75412c-64cb-4975-8ed4-ae1467007ba7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/e6c4d640-6fdd-4cfe-b1dd-b5bb3b3905d7

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/93399543/df6d0091-5084-434a-a0dd-4c748e33b1ea

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/113616c9-5607-4532-bc1e-ac9d3e1cfdd0

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/c160a41b-4146-4693-9ac7-6b0e7ac97cbc

https://github.com/Expensify/App/assets/93399543/75ac876c-a41e-4229-8420-9961ac853e05

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/66f33e3f-a312-488f-a754-0ee6879dda19

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment]
This seems a duplication of https://github.com/Expensify/App/issues/29855

**Comment by dangrous** [comment]
@cristipaval agreed - do you want to grab this issue, or should I just close it?

**Comment by cristipaval** [comment]
I think we can close this one, we already have an accepted solution for the other issue.

**Comment by dangrous** [comment]
got it, closing!
