### ISSUE TITLE
[HOLD for payment 2023-11-02] Move currency selection language to a different object

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29872]
# Problem
The language file [has an object for `iOUCurrencySelection`](https://github.com/Expensify/App/blob/main/src/languages/en.ts#L341-L344) which is a subtle indicator that the language is only used inside the `iOUCurrencySelection` component. 

Coming from large refactoring in https://github.com/Expensify/App/pull/28618

# Why this is important
It doesn't promote good reuse of the language translations

# Solution
Move the translations to the `common` object
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed21695ab711cbda</li>
        <li>Upwork Job ID: 1714668048651948032</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by tgolen** [comment]
@puneetlath Can you please pay @ntdiary for a C+ review of the PR?

**Comment by puneetlath** [comment]
@ntdiary offer is here: https://www.upwork.com/nx/wm/offer/27543527

Please ping me on this issue when you've accepted it.

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
