### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] DEV: Web - Console error on login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.86.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697633043348869

## Action Performed:
1. Logout if you already login
2. Enter email and magic code

## Expected Result:
should not show console error

## Actual Result:
console error appears

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/1c0e42ef-3a85-4be9-ba57-8bf4ed67db2c

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b8af22ad298788b</li>
        <li>Upwork Job ID: 1714664714880716800</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Contributor | 27263678</li>
<li>gadhiyamanan | Reporter | 27263681</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
@5war00p @fedirjh Seems a regression from https://github.com/Expensify/App/pull/29590 where null is replaced with an empty string [here](https://github.com/Expensify/App/pull/29590/files#diff-dd4bfa50713397aca8cb40145317936ab0affe19abc2a9c24d6c8849ed75dc9bL130). Now it returns the collection for `reportUserIsLeavingRoom_` and `reportActions_` due to an empty string which earlier returns undefined by considering `reportUserIsLeavingRoom_null` and `reportActions_null` I believe.

**Comment by 5war00p** [comment]
@fedirjh you mean changing the value to empty string?

**Comment by b4s36t4** [comment]
What is the difference between `reportActions_` and `reportActions_null` key that and that causes object to be returned? isn't it the RCA?

**Comment by 5war00p** [comment]
Both are strings with and without null has prefix are explicitly checking the suffic null or not?
@fedirjh   Here is the PR: https://github.com/Expensify/App/pull/29893

**Comment by adelekennedy** [comment]
Payouts due:

Issue Reporter: $50 @gadhiyamanan Upwork

Based on comment [here](https://github.com/Expensify/App/issues/29871#issuecomment-1768993472)

**Comment by adelekennedy** [comment]
payments made! any more steps or are we good to close @fedirjh?
