### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] [Wave 6: Referral Program] Promote referral program messaging in NewDot OptionsSelector component 

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#29881]
## Background
We're finding creative ways to inject referral program copy into NewDot flows, and agreed on [this idea](https://expensify.slack.com/archives/C02MW39LT9N/p1697732077594239?thread_ts=1697503732.459529&cid=C02MW39LT9N) as a good one to pursue. This is in preparation for the upcoming earnings call in November where it'll be a part of what we showcase. 

### Flows and CTA
We want to add a CTA and modal to the OptionsSelector component in each of the following flows:
1. Start chat (CTA: Start a chat, **get $250.**)
2. Request money (CTA: Request money, **get $250.**)
3. Send money (CTA: Send money, **get $250.**)
4. Click the magnifying glass (CTA: Refer a friend, **get $250.**)

### Modals 
When a CTA is clicked, it will bring up a modal with slightly different copy depending on which CTA is clicked. 

**ENGLISH**
When "Start a chat, **get $250.**" is clicked, open up the following modal with header and body:

> **Start a chat, get $250**
>
> Start a chat with a new Expensify account. Get $250 once they start an annual subscription with two or more active members and make the first two payments toward their Expensify bill.
>
> [Learn more](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

**SPANISH**

> **Inicia un chat y recibe $250**
>
> Inicia un chat con una cuenta nueva de Expensify. Obtiene $250 una vez que configuren una suscripción anual con dos o más miembros activos y realicen los dos primeros pagos de su factura Expensify.
> 
> [Aprende más](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

------
**ENGLISH**
When "Request money, **get $250.**" is clicked, open up the following modal with header and body:

> **Request money, get $250**
>
> Request money from a new Expensify account. Get $250 once they start an annual subscription with two or more active members and make the first two payments toward their Expensify bill.
>
> [Learn more](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

**SPANISH**

> **Pide dinero y recibe $250**
>
> Pide dinero a una cuenta nueva de Expensify. Obtiene $250 una vez que configuren una suscripción anual con dos o más miembros activos y realicen los dos primeros pagos de su factura Expensify.
> 
> [Aprende más](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

------

**ENGLISH**
When "Send money, **get $250.**" is clicked, open up the following modal with header and body:

> **Send money, get $250**
>
> Send money to a new Expensify account. Get $250 once they start an annual subscription with two or more active members and make the first two payments toward their Expensify bill.
>
> [Learn more](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

**SPANISH**

> **Envía dinero y recibe $250**
>
> Envía dinero a una cuenta nueva de Expensify. Obtiene $250 una vez que configuren una suscripción anual con dos o más miembros activos y realicen los dos primeros pagos de su factura Expensify.
> 
> [Aprende más](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

------

**ENGLISH**
When "**Refer a friend, **get $250.**" is clicked, open up the following modal with header and body:

> **Refer a friend, get $250**
>
> Send your Expensify referral link to a friend or anyone else you know who spends too much time on expenses. When they start an annual subscription, you'll get $250.
>
> [Copy referral link]
>
> [Learn more](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

**SPANISH**

> **Recomienda a un amigo y recibe $250**
>
> Envía tu enlace de invitación de Expensify a un amigo o a cualquier otra persona que conozcas que dedique demasiado tiempo a los gastos. Cuando comiencen una suscripción anual, obtendrás $250.
> 
> [Copiar enlace de invitación]
> 
> [Aprende más](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

## What it should look and act like
https://github.com/Expensify/App/assets/22160301/d81e3748-394d-4eb6-8b71-9f7d9f381e3a
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a15fd2a51390abe</li>
        <li>Upwork Job ID: 1715378596838580224</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27295919</li>
</ul></li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from callstack and can take this one

**Comment by jamesdeanexpensify** [comment]
Wait sorry, I think we're actually going to change this flow. Please hold on any work for now, thanks!

**Comment by jamesdeanexpensify** [comment]
(for internal reference: https://expensify.slack.com/archives/C02MW39LT9N/p1697685446093609?thread_ts=1697503732.459529&cid=C02MW39LT9N)

**Comment by puneetlath** [comment]
@jamesdeanexpensify we're just adding the modal right?

**Comment by jamesdeanexpensify** [comment]
@puneetlath let's chat [here](https://expensify.slack.com/archives/C02MW39LT9N/p1697732077594239?thread_ts=1697503732.459529&cid=C02MW39LT9N)?

**Comment by jamesdeanexpensify** [comment]
@puneetlath let me know if the update to the OP looks good based on internal conversations to date! Then @waterim can start work on it.

**Comment by puneetlath** [comment]
Looks good to me!

**Comment by dannymcclain** [comment]
@dubielzyk-expensify Do you wanna take this one since you're the one who designed it? Happy to be the one on it if you prefer, just figured you'd have a bit more context.

**Comment by jamesdeanexpensify** [comment]
I was just thinking that since he already put some work into, thanks @dannymcclain!

**Comment by mountiny** [comment]
We will mainly need your help with the design review in the PR itself 🙌

**Comment by dubielzyk-expensify** [comment]
@dannymcclain Yep, that makes a lot of sense. 

Happy to review when this is ready :)

**Comment by dubielzyk-expensify** [comment]
Adding here as well
![payment_hands](https://github.com/Expensify/App/assets/145416827/c22d96fd-4aca-40dd-bb6c-0367510e048e)

**Comment by jamesdeanexpensify** [comment]
Asked for Spanish translations in #espanol-translations, waiting for help there!

**Comment by jamesdeanexpensify** [comment]
Nearly there on the Spanish translations, I'm adding them to the OP up top. Will let you know when they're 100% ready!

**Comment by jamesdeanexpensify** [comment]
OK @waterim Spanish translations are in the original post above!

**Comment by jamesdeanexpensify** [comment]
@puneetlath if the earnings call is next Tuesday, Nov. 7, should we update this back to Daily?

**Comment by jamesdeanexpensify** [comment]
Working on updating the OP to match our most recent copy conversations. Also need to run this by the #espanol channel for a double-check on Spanish translations. Done soon!

**Comment by jamesdeanexpensify** [comment]
All English and Spanish copy in the top post above should be ready now!

**Comment by puneetlath** [comment]
This was merged.

**Comment by cubuspl42** [comment]
"invite link", or should it be "invitation link"?

**Comment by jamesdeanexpensify** [comment]
I think "invite link" works!

**Comment by jamesdeanexpensify** [comment]
Actually, let's hold on [these changes](https://github.com/Expensify/App/issues/29881#issuecomment-1828507110). I'm getting more feedback on copy and will reply here soon!

**Comment by cubuspl42** [comment]
@waterim Would you submit a follow-up PR with the discussed minor changes?

**Comment by waterim** [comment]
Oh, sorry, missed this conversation, will create a PR today

**Comment by waterim** [comment]
@jamesdeanexpensify Didn't find an updated Spanish copy for this:

> Invite a friend, get $250
Be the first to invite a friend (or anyone else) to Expensify and get $250 if they become an Expensify customer. Share your invite link by text, email, or post it on social media!
[Copy invite link]
Learn more

**Comment by cubuspl42** [comment]
@puneetlath Same, do we need to assign someone to process the payment?

**Comment by puneetlath** [comment]
Paid! Thanks everyone.
