### ISSUE TITLE
[SMARTSCAN] [$500] [Regression fix] LOW: Expense - Incorrect placement of the red dot in expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: There is some failed Scan requests with red dot
1. Go to staging.new.expensify.com
2. Go to the chat containg the requests in the precondition
3. Click on the request preview

## Expected Result:
The red dot in the expense in 1:1 DM, expense report and expense details page has consistent placement on the right end of the content

## Actual Result:
The red dot in the expense report is right next to the word 'Cash' instead of on the right end like it does in 1:1 DM and expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
<img width="1006" alt="Bug6242013_1697649205328!Red_dot_on_the_right_end_placement" src="https://github.com/Expensify/App/assets/78819774/f58f5757-007b-428d-b7d9-29e5ddb15551">

https://github.com/Expensify/App/assets/78819774/57aee76a-a19a-4c4b-94ca-9ec0edd35239

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f43fdbc3c0a0e63e</li>
        <li>Upwork Job ID: 1716756487011663872</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
Regression from https://github.com/Expensify/App/pull/29544 where extra `View` is removed which has the`flex1` prop to take available width.
https://github.com/Expensify/App/commit/9d04cf99a4dc291c9a97559f084f92d96e509a4f#diff-d8e6b69ad4461bebf91e940a67ddc07adf36a3f7c156d6066363c3bde06a0f8aL265

**Comment by trjExpensify** [comment]
I think this is the same as I reported here, right? https://github.com/Expensify/App/issues/29733

**Comment by trjExpensify** [comment]
Yup, makes sense!

**Comment by trjExpensify** [comment]
Niceee! @anmurali I'll just snag this from you.

**Comment by trjExpensify** [comment]
@rushatgabhane what's the ETA on reviewing the PR?

**Comment by trjExpensify** [comment]
PR is merged melv, awaiting a staging deploy.

**Comment by trjExpensify** [comment]
Going to close this as it was an issue for a regression from https://github.com/Expensify/App/issues/29543
