### ISSUE TITLE
[HOLD for payment 2023-11-09] Rename shouldDisableWriteActions to canUserPerformWriteAction

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29882]
# Problem
[This code](https://github.com/Expensify/App/blob/e34c853f1eaf76da006591ab99f373336b99fb87/src/libs/ReportUtils.js#L3665) defines a method called `shouldDisableWriteActions` which doesn't conform to our styles for using positively named things.

This is coming from [my large refactoring PR](https://github.com/Expensify/App/pull/28618) that I'm trying to break down into smaller pieces.

# Why this is important
It ensures that our code consistently follows our style guide. The positive naming of this method will make it more clear what the intention is for referencing it.

# Solution
Rename the method to `canUserPerformWriteAction` and reverse all the logic.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015de6055d0c654f99</li>
        <li>Upwork Job ID: 1714685712619388928</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by tgolen** [comment]
@laurenreidexpensify This will be ready for payment next week, so I've assigned it to BZ. It was an internal issue so there was no BZ at the beginning.

**Comment by laurenreidexpensify** [comment]
Payment Summary

- @Santhosh-Sellavel can send a  manual request in newdot for $500 after 9 Nov if there are no regressions

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

- @Santhosh-Sellavel please send a manual request for $500 for C+ review

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on comment above.
