### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] Workspace - Invite members - Tooltip does not show display name in member list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697645427249979

## Action Performed:
1. Prepare account B has display name
2. Login account A, click new chat and send message with account B
3. Create workspace
3. Go to members
4. Click invite and hover on user B on the list, Observe that the tooltip show display name
5. Select user B
6. Click next => Click invite
7. Hover on user B on the list member, Observe that the tooltip does not show display name

## Expected Result:
Tooltip should show display name in step 7 same with step 4 if user has display name

## Actual Result:
Tooltip does not show display name in member list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2ff5c454-8985-4332-a33b-90c21e3756d4

https://github.com/Expensify/App/assets/93399543/0a9528ca-f379-43df-ab38-eaa610ce3572

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/e37b845e-ce4f-4b76-a837-4091b148fd00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141d122e6e97c2984</li>
        <li>Upwork Job ID: 1714714265537466368</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 27355496</li>
<li>namhihi237 | Reporter | 27355499</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing display name on the Workspace members page. 

### What is the root cause of that problem?
For the `SubscriptAvatar` to show the user's display name, it expects an ID to be passed down within the mainAvatar object. Otherwise, it falls back to an id of -1
 

```js
<UserDetailsTooltip
   shouldRender={showTooltip}
   accountID={lodashGet(mainAvatar, 'id', -1)}
   icon={mainAvatar}
 >

```

In the Workspace members page the items are constructed inside `getMemberOptions` which returns 
```js
icons: [
                    {
                        source: UserUtils.getAvatar(details.avatar, accountID),
                        name: details.login,
                        type: CONST.ICON_TYPE_AVATAR,
                    },
                ],
```
- notice the missing `id` property that is expected by the `SubscriptAvatar`

### What changes do you think we should make in order to solve the problem?

We need to add the ID to the icons array items. 

```js
                icons: [
                    {
                        source: UserUtils.getAvatar(details.avatar, accountID),
                        name: details.login,
                        type: CONST.ICON_TYPE_AVATAR,
                        id: accountID,
                    },
                ],
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Inconsistent tooltip when hovering on account avatar with display name, it should show display name with you had display name
### What is the root cause of that problem?
In `BaseUserDetailsTooltip` component we use `accountID` to get user information.
But we didn't pass the account id to member options at `WorkspaceMembersPage`:
https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/pages/workspace/WorkspaceMembersPage.js#L360-L365
### What changes do you think we should make in order to solve the problem?
We should add `id` for icons:
```js
icons: [{
    source: UserUtils.getAvatar(details.avatar, accountID),
    name: details.login,
    type: CONST.ICON_TYPE_AVATAR,
    id: accountID
}, ],
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by robertKozik** [comment]
Thanks for your proposal @namhihi237, it solves the issue entirely. But before the assignment I'm curious whether we can find the PR which caused that issue, it would be great to include this info in the proposal as well

**Comment by robertKozik** [comment]
Great, I think that this cause it as well. Thanks for confirming it as it supports your root cause well. Let's see your [proposal](https://github.com/Expensify/App/issues/29900#issuecomment-1769124767) in action @namhihi237 

🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment]
Hi @namhihi237, were you able to raise a PR yet for this issue?

**Comment by sakluger** [comment]
@deetergp can you review @namhihi237's proposal and assign them if you agree with @robertKozik? Thanks!

**Comment by deetergp** [comment]
@namhihi237's proposal looks good to me 👍

**Comment by sakluger** [comment]
Paid out @namhihi237 for the reporting and contributor payments.

@robertKozik could you please complete the BZ checklist? Once you do we can close out the issue. Thanks!

**Comment by robertKozik** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27767
> * [ ]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27767/files#r1391726373
> * [ ]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [ ]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think we need separate regression test for it. It came from the refactor so it's rather one-time problem**
> * [ ]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by sakluger** [comment]
Thanks! We're good to close 👍
