### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] Reload on title and description of task field does not focus back

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29905]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697648537204909

## Action Performed:
1. Open the app
2. Click on green plus and click on assign task
3. Write any title and click next
4. Click on title and on title page, reload and observe that it does focus back on title field
5. Click on description and on description page, reload and observe that it does focus back on description field
## Expected Result: 
App should focus back on title and description field on reload
## Actual Result: 
App does not focus back on title and description field on reload

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/e0307ed0-87c4-4e41-913f-78c265da85e1

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/18fe243f-52a3-4b3f-88d8-8bde6f8b7440

https://github.com/Expensify/App/assets/38435837/b2c2184b-988c-4c70-b603-43796614396e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187815170d8ee20df</li>
        <li>Upwork Job ID: 1714736739040681984</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27349476</li>
<li>dhanashree-sawant | Reporter | 27349478</li>
</ul></li>
    </ul>
</details>

**Comment by cooldev900** [comment]
@abdel-h66 
I tried your solution but didn't work.
Are you sure that it works?

**Comment by alexpensify** [comment]
@robertKozik - can you review these proposals? Thanks!

**Comment by alexpensify** [comment]
@robertKozik - we need a review when you get a chance, thanks!

**Comment by robertKozik** [comment]
Thank you all for your proposals! I checked all of them and I believe we should go further with @tienifr as It consist of already used hook and standarizes the approach for all Task pages.
As for the other proposals: 
@abdel-h66 - your proposal would break the transition animations
@ZhenjaHorbach - your proposal would probably work fine, but It's more complicated than @tienifr solution

This said, I believe we should go with @tienifr [proposal](https://github.com/Expensify/App/issues/29905#issuecomment-1769816450)

🎀 👀 🎀 C+ reviewed

**Comment by robertKozik** [comment]
@aimane-chnaif do you think it should be handled by the contributor which introduced the `useAutoFocusInput` as the part of the original issue (I don't see a link to issue in your comment, so assuming that you are refering to that issue)?

**Comment by alexpensify** [comment]
Wow, that was fast! Now we will wait for automation to kick in here.

**Comment by robertKozik** [comment]
> * [x] [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [x]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [x] [@robertKozik]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [x]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't suggest regression test as this doesn't affect task flow and reload is rare case.**
> * [x]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter @dhanashree-sawant $50
-  Contributor that fixed the issue @tienifr $500 + $250
-  Contributor+ that helped on the issue and/or PR - @robertKozik paid via team 

Upwork Job: https://www.upwork.com/jobs/~0187815170d8ee20df

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is an urgency bonus since the PR was approved within the 3 business day mark. It looks like automation didn't catch it, but I confirmed the dates in the PR.

**Comment by alexpensify** [comment]
Alright, all required actions have been completed and everyone has been paid in Upwork.
