### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Update all selectors to use new format for selected participant 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#29916]
Follow up from https://github.com/Expensify/App/pull/29903

In https://github.com/Expensify/App/issues/29836, we updated the flow for the group chat / split bill flow to hide the selected participants when we are searching for a user. We'll need to update the flow for all selectors to use that same format
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5750587ffb7e229</li>
        <li>Upwork Job ID: 1714778343126532096</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27740728</li>
<li>dukenv0307 | Contributor | 27740730</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Waiting to add external until the linked PR is merged

**Comment by abzokhattab** [comment]
I can work on this asap

**Comment by thienlnam** [comment]
We're still looking for proposals in the standard format

**Comment by mallenexpensify** [comment]
@abdulrahuman5196, can review @dukenv0307 's proposal above plz?

**Comment by thienlnam** [comment]
Yup, please review the proposal and work with Duke to update if there are any issues with it and then we can move to PR

**Comment by abdulrahuman5196** [comment]
@dukenv0307 I think still we expect a formatted proposal as always even though you would get dibs here. We should still add some missing pieces in the proposal like below.

>There're some that use canSelectMultiple that already work fine (does not use getOptions) like in WorkspaceMembersPage, we can evaluate them during the PR process.

We should provide information on this. This is not a straightforward forward change in my opinion. 
Like do we make it to migrate to getOptions or like update existing functions in WorkspaceMembersPage to behave like the new selection mechanism?

>Pass the includeSelectedOptions as true in the getOptions that gets the options for those places, similar to [here](https://github.com/Expensify/App/blob/1bfd5f10ceedec1566b1a57aa08a10a8d6d5daa8/src/pages/NewChatPage.js#L152)
3. Only push the participants section if search term is empty, similar to [here](https://github.com/Expensify/App/blob/ccd2f3c858e67672e373cdadc8ec66ab14df910d/src/pages/NewChatPage.js#L75)

And we should also provide information on what pages/code are these which needs to be updated?

**Comment by abdulrahuman5196** [comment]
Melvin we had just posted update before weekend and back from weekend

**Comment by mallenexpensify** [comment]
@dukenv0307 can you please address @abdulrahuman5196 's comments in their post above?

**Comment by abdulrahuman5196** [comment]
Will review update today

**Comment by abdulrahuman5196** [comment]
> For this I mean in those places it's already working fine according to expected behavior, so no change needed. It's already filtering out the selected options if those do not match the search query. Only the pages that are using getOptions has the issue.

@dukenv0307 Workspace invite page doesn't behave the expected way. We might need to fix this in different way.

<img width="386" alt="Screenshot 2023-11-01 at 5 26 00 PM" src="https://github.com/Expensify/App/assets/46707890/b691161a-b534-4f35-bfc5-6fee07b7dbf5">

**Comment by mallenexpensify** [comment]
Being discussed above.

**Comment by abdulrahuman5196** [comment]
@dukenv0307 ? Any update on the question above?

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 , what do we need in order to hire someone here?

**Comment by abdulrahuman5196** [comment]
Let me check on the latest response and update here

**Comment by abdulrahuman5196** [comment]
Hi, Will review again today, just back from weekend

**Comment by abdulrahuman5196** [comment]
Hi, I think this issue has been held long on discussions. Since @dukenv0307 already have dibs on assignment here with proposal here https://github.com/Expensify/App/issues/29916#issuecomment-1769762909. I think its fine to move to PR phase and clarify any questions there since I think only minor concerns are pending.

🎀 👀 🎀
C+ Reviewed

**Comment by flodnv** [comment]
@thienlnam looks like you were already assigned, not sure why it assigned someone else. Leaving it to you 😁

**Comment by abdulrahuman5196** [comment]
Not overdue melvin, we just assigned the contributor

**Comment by thienlnam** [comment]
What's the update here @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment]
Hi, Will be reviewing the PR again today.

**Comment by abdulrahuman5196** [comment]
1) Go to a room/WS and open the Memember page
2) Click Invite and choose some users
3) Verify that you see them at the top
4) Start searching for a user and verify only the participants matching the selection is shown in the list, whereas the selected participants matching the search is shown at top and the rest matching the search is followed
5) When there is no search, all the selected participants should show at the top and the rest following them.

@mallenexpensify

**Comment by mallenexpensify** [comment]
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @abdulrahuman5196 paid $500 via Upwork

TestRail update steps GH created https://github.com/Expensify/Expensify/issues/359909
Thanks @abdulrahuman5196
