### ISSUE TITLE
Replace import with "styles" once the static style export from "styles.js" isn't used anymore

### ISSUE THREAD

**Issue by grgia** [Expensify/App#29910]
Replace ` import {stylesGenerator} from './styles';` with "styles" once the static style export from "styles.js" isn't used anymore

cc @chrispader

**Comment by chrispader** [comment]
Also remove export in `styles.js`

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
@chrispader I think we can do this one now yea?
