### ISSUE TITLE
[$500] Web - Card list shows the same label repeated for every card

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29912]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697655919557859

## Action Performed:
1. Open settings > Wallet
2. Assigned cards all have the same name

## Expected Result:
Card list should show deferent label repeated for every card

## Actual Result:
Card list shows the same label repeated for every card

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![Screenshot 2023-10-18 at 12 04 50 PM](https://github.com/Expensify/App/assets/93399543/334d56c9-c8b4-4085-8c30-01ab4867a4be)

![image (13)](https://github.com/Expensify/App/assets/93399543/7b7ff910-3ee1-4407-80eb-9197e9e9ec27)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed9a3119cee96a19</li>
        <li>Upwork Job ID: 1714746198232457216</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Already deployed to Staging (which is what I assume Cole uses). Also Wallets are for internal usage atm, so closing this one out.
