### ISSUE TITLE
[$500] Room - Auth OpenReport returned an error" message displayed when create reply for money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.86-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: user should be signed in
1. Open app
2. Tap on Profile icon
3. Tap on "Workspaces"
4. Create a new workspace
5. Add a photo to the workspace (optional)
6. Navigate to LHN
7. Tap on the room conversation (see the screenshot attachment)
8. Tap on plus button next to composer box
9. Tap on the request money
10. Create a manual money request
11. Hold the request money preview in chat
12. Tap on the "Reply in thread"

## Expected Result:
Thread conversation should be created and properly displayed

## Actual Result:
Thread conversation not created and error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Bug6242279_1697663781507!How_the_room_conversation_looks_like](https://github.com/Expensify/App/assets/78819774/aee1b144-26be-46c5-a818-f7d90d1765f1)

https://github.com/Expensify/App/assets/78819774/87e35566-3a3e-4749-9f5d-f56c2d17d11e

https://github.com/Expensify/App/assets/78819774/06cad06c-b527-4312-8314-7ba34cb4e025

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018fb2ca5b55d95d96</li>
        <li>Upwork Job ID: 1714764764089405440</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by chiragkcodes** [comment]
I am unable to reproduce with the given steps. Can you please provide video reproducing the issue?

**Comment by rojiphil** [comment]
Same here. Unable to reproduce.

**Comment by lanitochka17** [comment]
@chiragkcodes Hello
The video has been added to the Screenshot tab.

![image](https://github.com/Expensify/App/assets/78819774/61feb62c-87df-4d10-aab2-214ec634c5b9)

**Comment by laurenreidexpensify** [comment]
@eVoloshchak are you able to reproduce?
