### ISSUE TITLE
[$500] Wrong position of tooltip when click copy icon

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @yh-0218
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697651235103809

## Action Performed:
1. open app
2. click <+> button and select "Request money"
3. select "Scan" Tab
4. click email copy icon
## Expected Result: 
"Copied" tooltip must be shown on above of copy icon
## Actual Result:
"Copied" tooltip is shown on left-top corner

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Screenshot 2023-10-18 at 8 48 12 PM](https://github.com/Expensify/App/assets/38435837/ce5a75b2-3194-4d55-979f-65d706b055f8)

https://github.com/Expensify/App/assets/38435837/443633f6-9e10-49e2-a8f0-9fb6baaa28b0

</details>

<details>
<summary>MacOS: Desktop</summary>

![Screenshot 2023-10-18 at 8 50 53 PM](https://github.com/Expensify/App/assets/38435837/fe3dcc4e-abdd-4322-99c9-62b3c7cf5a7a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154bb9ec93fced40b</li>
        <li>Upwork Job ID: 1714763132541411328</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
I think this is the same issue as this https://github.com/Expensify/App/issues/29678
