### ISSUE TITLE
[Performance] Chat scrolling hermes profiling

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#29937]
## What performance issue do we need to solve?

Use hermes profiler to find slow JS code while scrolling a chat.

## What is the impact of this on end-users?
Scrolling in a chat should be fast and not show blanks

## List any benchmarks that show the severity of the issue

<img width="776" alt="image" src="https://github.com/Expensify/App/assets/2677334/d70dc855-8ac3-404e-ba45-604c7687f941">

## Proposed solution (if any)

Move `supportedActionTypes` outside of `shouldReportActionBeVisible` since it never changes and `shouldReportActionBeVisible` is called many times.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

<img width="786" alt="image" src="https://github.com/Expensify/App/assets/2677334/d3cc4f38-e3b8-4585-8726-979b6274dc0c">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by deetergp** [comment]
I'm not quite sure what to do with this one 😅
