### ISSUE TITLE
[HOLD for payment 2023-10-30] [Performance] Chat switching hermes profiling

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#29935]
## What performance issue do we need to solve?

Use hermes profile to find slow javascript code during chat switching.

## What is the impact of this on end-users?

Switching chat needs to be as fast as possible.

## List any benchmarks that show the severity of the issue

Here's the profile:

<img width="999" alt="image" src="https://github.com/Expensify/App/assets/2677334/e71486cf-6151-4260-8628-9c26dab8b3a1">

`getLastVisibleAction` is slow because it creates JS date objects for each messages.

## Proposed solution (if any)

Do not use date objects to sort report actions.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

<img width="1009" alt="image" src="https://github.com/Expensify/App/assets/2677334/de8b709b-6b24-4445-a437-7ce83ac43f27">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by mountiny** [comment]
I will take this one on as well from the performance room, adding it to the project

**Comment by mountiny** [comment]
will be merged soon

**Comment by mountiny** [comment]
This is ready for payment $500 to @rushatgabhane now need for checklist as this was a performance improvement

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on comment above.

**Comment by peterdbarkerUK** [comment]
Thanks guys
