### ISSUE TITLE
[Awaiting payment][SMARTSCAN] LOW: Prevent uploading invalid files as receipts.

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#29960]
**Problem**
Currently, in the backend, we only allow certain filetypes as receipts:
`$regFileTypes = '/(jpe?g|gif|png|pdf|html?|text|rtf|doc|tiff?|msword|zip|xml|message)/i';`

We don't have any frontend checks for them.

**Solution**
Add those checks on the frontend for a better user experience
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015865ac74df1824c8</li>
        <li>Upwork Job ID: 1714965684961083392</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by Gonals** [comment]
This has already been fixed. @kadiealexander, we just have payment left, right?

**Comment by situchan** [comment]
The fix was deployed to production on [Nov 9](https://github.com/Expensify/App/pull/29963#issuecomment-1804801845).
So today is due payment.
@Gonals can you please move to `Daily` and update issue title? Thanks

**Comment by kadiealexander** [comment]
Sorry team I was OOO. @situchan I've sent you an Upwork contract.

Payouts due:

Contributor+: $500 @situchan

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/ab/applicants/1727175567296065536/offers).

**Comment by AbdallaEmadEldinAbdalla** [comment]
It can be easily done by checking the mimetype of selected file
