### ISSUE TITLE
[Wave 6: Workspace Chats] Ensure we set notification preference to always when non owner comments on expense/ iou report

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#29964]
Coming from here https://github.com/Expensify/Auth/pull/8930#discussion_r1362848109

During writing a new tests for the notification preference set to Hidden for expense/ iou report, it shows that if requestor request money from a payer and payer comments on the expense report, we do not change the notification settings to always for the requestor hence the report does not show up in their LHN.

**Comment by mountiny** [comment]
Sorry  for the ping

**Comment by puneetlath** [comment]
Yeah I think this would be the same for threads. If I type a comment in a room and then you respond to it in thread, I should get notified. Similarly, if I create an expense report/IOU/transaction and you comment on it, I should get notified.

**Comment by mountiny** [comment]
Stil holding for post conference here

**Comment by mountiny** [comment]
Still not the main priority

**Comment by puneetlath** [comment]
This is being handled in https://github.com/Expensify/Auth/pull/9145

**Comment by mountiny** [comment]
Soon should be merged

**Comment by mountiny** [comment]
same same

**Comment by mountiny** [comment]
We are close to getting the PR from Jasper merged then we will follow with this one shortly after

**Comment by puneetlath** [comment]
This is done too right @mountiny?

**Comment by mountiny** [comment]
yes that was added, I think its not happening in case of transaction thread still though

**Comment by puneetlath** [comment]
Ah ok, so we need to leave this open to handle transaction threads. Got it.
