### ISSUE TITLE
[$500]  Room - User mention in the system message after inviting member to the room cannot be copied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a room
3. Click on the room header > Members > Invite > Invite anyone to the room
4. Right click on the system invitation message > Copy to clipboard
5. Paste the message in the composer

## Expected Result:
The system message along with the user mention will be copied

## Actual Result:
User mention in the system message is not copied. This is because the logic that's called when we click the "Copy" button hasn't been updated to handle accountID based mentions. It only handles login-based mentions.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/7b7c4c11-a768-4886-b359-1e1909cbc4d4

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b64b832924292d8</li>
        <li>Upwork Job ID: 1715082222817452032</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27598151</li>
</ul></li>
    </ul>
</details>

**Comment by francoisl** [comment]
Looks like the report `INVITEROOM` report action's `html` message is in the format `<muted-text>invited <mention-user accountID=XXX></mention-user></muted-text>` and it might need to be `<muted-text>invited <mention-user accountID=XXX>person@domain.com</mention-user></muted-text>`. Going to check when/where we added this.

<img width="1274" alt="image" src="https://github.com/Expensify/App/assets/2229301/124c425c-9ee2-48c9-9f0b-b2a63af357da">

**Comment by francoisl** [comment]
cc @jasperhuangg I see recent changes to InviteToRoom in https://github.com/Expensify/Auth/pull/8776/, do you have an idea if it's related?

Anyway you can still triple-click + Command+C on the message, and it will copy everything including the invitee's email address, so I don't know if this is worth being a blocker.

**Comment by francoisl** [comment]
Could be if staging uses a brand new API + Auth command, but InviteToRoom is not a new command so yeah it's probably not that :/

**Comment by jasperhuangg** [comment]
Hmmm these are accountID-based mentions, which should only include the accountID. I double-checked with @puneetlath when I created these API commands that these would be sufficient, but it seems like our copy-paste functionality hasn't been updated to account for these new types of mentions

**Comment by francoisl** [comment]
(Discussing in Slack here https://expensify.slack.com/archives/C07J32337/p1697741788107389)

**Comment by jasperhuangg** [comment]
Deemed NAB: https://expensify.slack.com/archives/C07J32337/p1697741788107389

**Comment by francoisl** [comment]
cc @samh-nl - looks like you worked on accountID-based mentions in https://github.com/Expensify/App/pull/26877. Feel free to chime in if you have any insight on this issue.

**Comment by cead22** [comment]
> Not directly related to this issue with copying, but there is also `message.text` that is lacking the name and this sounds like it would need a BE fix.

Thanks for pointing this out, I'll take a look!

@tienifr thanks for the proposal, I'll wait for @ArekChr to evaluate it. I need to read the code to understand what we do with accountID based mentions vs email based mentions, and how the copy logic works before I can assess it

**Comment by ArekChr** [comment]
@tienifr Is it possible to just copy the displayed value? While pasting it, the dropdown with the user will work as well.
 
<img width="687" alt="image" src="https://github.com/Expensify/App/assets/24796318/3b46de03-404f-41e8-9b51-dd84a485378d">

**Comment by ArekChr** [comment]
@tienifr Thanks for the explanation. After reviewing the [proposal](https://github.com/Expensify/App/issues/29978#issuecomment-1773692177) I’m confident it’s a solid plan of action.

:ribbon: :eyes: :ribbon: C+ Reviewed

**Comment by cead22** [comment]
Thanks @ArekChr @tienifr. Is it a bit odd to be passing personal details to the Expensimark, which should only know about converting plain text to html and vice versa. If so, are there any alternative approaches?

@jasperhuangg @puneetlath mind giving this proposal a look and confirming it looks good to you since you're familiar with mentions and this issue? Thanks

**Comment by ArekChr** [comment]
@cead22 @tienifr I think passing only the `accountID` value should be enough.

**Comment by puneetlath** [comment]
I agree it is a bit weird. The MentionUserRenderer is rendering a `Text` element which has the actual text that is being displayed, right? Is there any way to pass that instead of the `Mention-User` element? Or I guess we currently just pull whatever the html is in the `message` field of the reportAction? 

Hmm, it's a tricky one.

**Comment by jasperhuangg** [comment]
@puneetlath Are you suggesting this

> Is there any way to pass that instead of the Mention-User element? Or I guess we currently just pull whatever the html is in the message field of the reportAction?

over just grabbing the accountID from the mention and looking up the text that we're supposed to display again to avoid doing duplicate work? That seems like the approach that's being suggested in @tienifr's [proposal](https://github.com/Expensify/App/issues/29978#issuecomment-1773692177), which I'm currently fine with.

I feel like we could refactor whatever logic we're using to display the mention into a utility function that we can reuse in this situation. Thoughts?

**Comment by cead22** [comment]
Started a slack thread in open source to better understand this issue and get aligned on the fix

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til Nov 13. Thanks @MitchExpensify   I'll grab this back from you when I return!

**Comment by stephanieelliott** [comment]
Thanks @tienifr! Per [this internal SO](https://stackoverflowteams.com/c/expensify/questions/8719), we'll pay out as normal for this PR and review.

Summarizing payment on this issue: 

 - Issue reporter: N/A, Applause internal
 - Contributor: @tienifr, $500 paid via Upwork 
 - Contributor+: @ArekChr, no payment due (expert contrib)
 
 Upwork job is [here](https://www.upwork.com/jobs/~018b64b832924292d8), no bonus is included on payout
