### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27]  Room - Nothing happens when clicking Leave room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Start Chat > Room
3. Create a workspace with the visibility set as 'Workspace'
4. Click on the room header > Leave room
5. Go to Members
6. Go to another chat

## Expected Result:
The room page will close and user will be redirected to other chat after leaving the room

## Actual Result:
Nothing happens when clicking Leave room
- User is still on the room details page
- When going to Members list, the current user disappears from the list
- The room chat only disappears when user opens another chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/c663431f-0dd5-46b5-aceb-e984fc1e4074

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
Seems an issue in the backend, `InviteToRoom` api is updating the displayName.

<img width="634" alt="Screenshot 2023-10-19 at 19 47 30" src="https://github.com/Expensify/App/assets/14358475/d0514fc7-c820-4305-b1fa-a4f1b816ed01">

**Comment by grgia** [comment]
@Pujan92 I don't see a call to `InviteToRoom` when I replicate this flow but it does seem like this is a backend issue.

**Comment by jasperhuangg** [comment]
Investigating

**Comment by zanyrenney** [comment]
@grgia @jasperhuangg little confused who the payouts are for here - looks internal, as was also reported by applause. can you confirm if any payouts are due?

**Comment by grgia** [comment]
No payout required for this one, PR was done by @jasperhuangg and PR checklist by @francoisl

**Comment by zanyrenney** [comment]
you are the best, thank you speedy G @grgia

**Comment by zanyrenney** [comment]
No payouts, PR is merged, good to close!
