### ISSUE TITLE
Participants on a bill split are not shown in a list after searching/selecting a user

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#29982]
Bug coming from https://github.com/Expensify/App/pull/29903

___

**Version Number:** v1.3.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1697711009900939?thread_ts=1697687894.730109&cid=C05RECHFBEW

## Action Performed:
1. Request money
2. Search an email
3. Select "Split"

## Expected Result:
We should clear the entry in the input, so all previous selections are made. 

## Actual Result:
The search list is cleared, as if you didn't make a selection

## Screenshots/Videos
http://g.recordit.co/RpgD602vd7.gif

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdulrahuman5196** [comment]
cc : @thienlnam

**Comment by thienlnam** [comment]
We chatted about this in slack, and it seems like this bug is due to the new participant issue 
https://github.com/Expensify/App/issues/29917

So going to close this in favor of that
