### ISSUE TITLE
[HOLD for payment 2023-11-02] [$125] [Form Provider Refactor] NewTaskDetailsPage 

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#29997]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/tasks/NewTaskDetailsPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01624c2184cea429ec</li>
        <li>Upwork Job ID: 1715041586747879424</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by cdOut** [comment]
Hello! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment]
we have a draft PR

**Comment by s77rt** [comment]
Not a bug. I don't think checklist applies here.

**Comment by s77rt** [comment]
@luacmartins Can you please change the price here to $125 to align with the rest of form refactor issues

**Comment by luacmartins** [comment]
Updated the price. Just pending payment.

**Comment by luacmartins** [comment]
Pending payment

**Comment by muttmuure** [comment]
@s77rt invited

**Comment by s77rt** [comment]
@muttmuure Applied! Thanks!

**Comment by muttmuure** [comment]
Paid
