### ISSUE TITLE
[HOLD for payment 2023-12-26] [DISTANCE] LOW: UpdateDistanceRequest 1:1:1 - UpdateMoneyRequestDate - Split out into its own command

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#29993]
There will be three pieces to this:
- Auth: Create the new command https://github.com/Expensify/Auth/pull/8986
- Web-E: Add the new API endpoint https://github.com/Expensify/Web-Expensify/pull/39445
- App: Implement the new API command https://github.com/Expensify/App/pull/30737

This will all be done internally as they are refactored.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019eb683577f4e3784</li>
        <li>Upwork Job ID: 1715033771434577920</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by tgolen** [comment]
Got started on the auth command today and put up a [WIP](https://github.com/Expensify/Auth/pull/8986). I also [asked in Slack](https://expensify.slack.com/archives/C03TQ48KC/p1697751589540909) about how to go about a testing strategy for all these commands.

**Comment by tgolen** [comment]
I will be able to get started on this again on Monday.

**Comment by tgolen** [comment]
I am hoping to get started on this today.

**Comment by tgolen** [comment]
Yesterday I was able to write 90% of the auth PR. The only thing left I need to do is write and return the Onyx updates. I also wrote 95% of the web-e PR and 90% of the app PRs. Today, I am hoping to complete the full flow so that I can begin testing and fine-tuning the solution.

**Comment by tgolen** [comment]
Draft PRs:
https://github.com/Expensify/App/pull/30737
https://github.com/Expensify/Web-Expensify/pull/39445
https://github.com/Expensify/Auth/pull/8986

**Comment by tgolen** [comment]
I'm dropping this back down to weekly while I try to finish up [this PR](https://github.com/Expensify/App/pull/28618) that came off HOLD.

**Comment by tgolen** [comment]
I got all the changes done in the [App PR](https://github.com/Expensify/App/pull/30737) today. Now I need to revisit both Web-E and Auth and finish up those PRs. They are mainly missing code to return OnyxUpdates to the frontend. Then, testing will commence.

**Comment by tgolen** [comment]
OK, I got all the PRs done and tested. Now the review process begins.

**Comment by tgolen** [comment]
There was a pretty sizable set of changes that I need to make to the Auth PR. I've been focused on the money request creation flow in the meantime. I'm hopeful that I can turn this to my attention next week.

**Comment by tgolen** [comment]
Looks like Web-E has been merged. I'll get the App PR ready for review so that it can be merged soon after Web-E is deployed

**Comment by cubuspl42** [comment]
Reviewing 👍

**Comment by tgolen** [comment]
I think this can be closed out since it doesn't look like it requires payment.

**Comment by cubuspl42** [comment]
@tgolen I was the C+ reviewer

**Comment by tgolen** [comment]
Reopening to get the C+ reviewer paid 👍

**Comment by tgolen** [comment]
@JmillsExpensify Can you please pay @cubuspl42 for their C+ review of the PR?

**Comment by JmillsExpensify** [comment]
Do we need to add any regression tests for this? Assuming no given that it's a backend refactor.

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @cubuspl42 for PR testing and review.

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by cubuspl42** [comment]
Accepted

**Comment by JmillsExpensify** [comment]
All paid out. Thank you!
