### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] TaskDescriptionPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#29998]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/tasks/TaskDescriptionPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cc2c1cbf43ec7af</li>
        <li>Upwork Job ID: 1715041841053011968</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by cdOut** [comment]
Hello! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment]
@cdOut is working on other forms at the moment. We'll get to this one soon!

**Comment by robertKozik** [comment]
Does the BugZero Checklist apply here as well? Additionally, both @cdOut and I are contractors, so I believe there is no payment needed for this issue.

**Comment by MitchExpensify** [comment]
Do you think we should add a new regression test @robertKozik ?

**Comment by luacmartins** [comment]
Pending BZ checklist and payment

**Comment by MitchExpensify** [comment]
No payment is necessary here but I am still curious on whether we should add a new regression test @robertKozik 👀

**Comment by robertKozik** [comment]
Sorry 🙇🏼  I don't think we need regression test for it

> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug.  **I don't think we need regression test for it**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by MitchExpensify** [comment]
All good! Thanks @robertKozik
