### ISSUE TITLE
[Form Provider Refactor] MoneyRequestDatePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30007]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/iou/MoneyRequestDatePage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01284f17e441cf77de</li>
        <li>Upwork Job ID: 1715043644384673792</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by kowczarz** [comment]
It's already done https://github.com/Expensify/App/pull/29098

**Comment by luacmartins** [comment]
Cool, closing this one then.
