### ISSUE TITLE
[Form Provider Refactor] WorkspaceNewRoomPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30005]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/workspace/WorkspaceNewRoomPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01553349eeb34ec486</li>
        <li>Upwork Job ID: 1715043196587958272</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hey! It's done in this PR https://github.com/Expensify/App/pull/29771

**Comment by luacmartins** [comment]
Ah cool, closing this one then!
