### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] [Form Provider Refactor] NewTaskDescriptionPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30002]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/tasks/NewTaskDescriptionPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc3514f9adde81a5</li>
        <li>Upwork Job ID: 1715042222190276608</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by cdOut** [comment]
Hello! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment]
@cdOut is working on other forms at the moment. We'll get to this one soon!

**Comment by anmurali** [comment]
Paid
