### ISSUE TITLE
[$500] [Form Provider Refactor] WorkspaceSettingsPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30006]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/workspace/WorkspaceSettingsPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012338fed619c082d3</li>
        <li>Upwork Job ID: 1715043402126536704</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by sakluger** [comment]
@luacmartins do you still want @0xmiroslav to review this PR, or will you be reviewing yourself?

**Comment by luacmartins** [comment]
@kowczarz will you take this one too?

**Comment by kowczarz** [comment]
Yep, I will work on it on Monday

**Comment by luacmartins** [comment]
@kowczarz is working on other forms at the moment. We'll get to this one soon!

**Comment by kowczarz** [comment]
The PR was [deployed 6.11.2023](https://github.com/Expensify/App/pull/30355#issuecomment-1796930417) I think we can close the issue.

**Comment by mallenexpensify** [comment]
Contributor+: @0xmiroslav owed $500 via Upwork
