### ISSUE TITLE
[$125] [Form Provider Refactor] WaypointEditor

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30008]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/iou/WaypointEditor.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165bf01aa20db61bc</li>
        <li>Upwork Job ID: 1715043820395114496</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by kowczarz** [comment]
This one is blocked by https://github.com/Expensify/App/pull/29983 as well

**Comment by laurenreidexpensify** [comment]
Making a weekly if there is a hold on #https://github.com/Expensify/App/pull/29983

**Comment by laurenreidexpensify** [comment]
https://github.com/Expensify/App/pull/29983 is on staging

**Comment by laurenreidexpensify** [comment]
Looks like https://github.com/Expensify/App/pull/29983 is on prod since Monday, so taking this off hold and making a daily again

**Comment by laurenreidexpensify** [comment]
@kowczarz can you advise on progress here - is there a PR up yet? Thank you

**Comment by kowczarz** [comment]
Hello! Tomorrow I will start working on it

**Comment by luacmartins** [comment]
PR for this issue was merged yesterday and is in staging now.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: $125 @hoangzinh offer sent in Upwork
C+: @kowczarz Expert Contributor N/A

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: $125 @hoangzinh paid  in Upwork
C+: @kowczarz Expert Contributor N/A
