### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] TaskTitlePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30003]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/tasks/TaskTitlePage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d76744abd8849743</li>
        <li>Upwork Job ID: 1715042474232901632</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by cdOut** [comment]
Hello! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by strepanier03** [comment]
I don't think I need to do anything yet so I'll just follow along until I'm needed.

**Comment by luacmartins** [comment]
@cdOut  is working on other forms at the moment. We'll get to this one soon!

**Comment by strepanier03** [comment]
@situchan - I didn't see a job created for this so I made one and hired you to it. Once we have the checklist stuff done I'll pay it out. 

Thanks!

**Comment by luacmartins** [comment]
Still working through issues

**Comment by situchan** [comment]
> @situchan - I didn't see a job created for this so I made one and hired you to it. Once we have the checklist stuff done I'll pay it out.
> 

@strepanier03 this doesn't require BZ checklist

**Comment by strepanier03** [comment]
This is paid and ready to be closed I believe. Feel free to reopen if I closed too soon.
