### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] PrivateNotesEditPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30004]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/PrivateNotes/PrivateNotesEditPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019146cfb545848865</li>
        <li>Upwork Job ID: 1715043040782385152</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
SWM will work on this, no need for a proposal

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment]
@kowczarz is working on other forms at the moment. We'll get to this one soon!

**Comment by peterdbarkerUK** [comment]
@luacmartins would it help to bump this to weekly in the meantime?

**Comment by kowczarz** [comment]
@peterdbarkerUK I'm finishing the pr, it should be ready in following hours

**Comment by luacmartins** [comment]
Let's keep this daily for now!

**Comment by peterdbarkerUK** [comment]
No regression tests or payments needed, I'm officially a full-blown bureaucrat. I'm sure my grandparents would be proud of me. 

Thanks for the work here guys ;)
