### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] No background color displayed on emoji on search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30012]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697723567806059

## Action Performed:
1. Open the app
2. Open any report
3. Click on emoji to open emoji picker
4. Search for any emoji eg: joy
5. Observe that no background color is displayed on first emoji in search
6. Press enter and observe that first emoji is selected

## Expected Result:
 App should display background color to first emoji on search as we select first emoji on enter click after search

## Actual Result:
App does not display background color to first emoji on search

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/b5024f57-4e68-48cd-adc2-c9c5540798a1

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a6d8a3c4-3443-4557-9983-1beb2f74886d

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/beae24e8-945a-4450-bd0b-5454c489180e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6af08ac7-eee6-4266-83dc-1e08d88498b0

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/55a875a6-53a1-4d4b-8d68-c2db3fe9fd00

https://github.com/Expensify/App/assets/93399543/8b871991-ccb7-4d42-aacf-ba59c59a64a2

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/085876c6-3b70-4be9-9cb1-149f185620c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136219e9671ca8f96</li>
        <li>Upwork Job ID: 1715068000534409216</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When searching in `EmojiPicker`, the first emoji isn't highlighted

### What is the root cause of that problem?

We're showing focused emoji only when `isUsingKeyboardMovement` is true
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L440

But when the search input gets focused, this value is set to false
This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to set `isUsingKeyboardMovement` when searching emojis
Add the following code to `filterEmojis` function above this line
https://github.com/Expensify/App/blob/18acd82f40153fc1e5091aea3217c532142e500e/src/components/EmojiPicker/EmojiPickerMenu/index.js#L189

```
        setIsUsingKeyboardMovement(Boolean(searchTerm));
```

This works as expected

<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
I think we should handle it as a regression from this issue https://github.com/Expensify/App/issues/29004, we did not notice this behaviour changed and we want to keep it

**Comment by mountiny** [comment]
@dylanexpensify can you pay @dhanashree-sawant for reporting this and we will hande a fix in the linked issue

**Comment by dylanexpensify** [comment]
Yes! @dhanashree-sawant please apply https://www.upwork.com/jobs/~01bf495fd961ad294a

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, if possible, can you send me invite or offer for the job?

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
@dhanashree-sawant invited!

**Comment by dhanashree-sawant** [comment]
Thanks @dhanashree-sawant I have accepted the invite.

**Comment by dylanexpensify** [comment]
invite sent!

**Comment by dylanexpensify** [comment]
done!
