### ISSUE TITLE
[HOLD #28029] [$500] Chat -Tapping delete in offline, the message is striked and a background color behind it show

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile -- Preferences
3. Toggle on Forced offline
4. Navigate to LHN
5. Tap on any report
6. Send a message
7. Long press the message and select delete comment
8. Tap delete

## Expected Result:
When user taps delete in offline, the message is striked and a background color behind it must not be shown

## Actual Result:
When user taps delete in offline, the message is striked and a background color for message is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/18da01a3-01b3-42d7-bb38-c7c5c713dcaa

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a9592d35425c6d1</li>
        <li>Upwork Job ID: 1715101447023042560</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by burczu** [comment]
not overdue - I'll be reviewing it soon

**Comment by burczu** [comment]
@puneetlath I've checked [the issue](https://github.com/Expensify/App/issues/28029) mentioned by @bernhardoj in they [comment](https://github.com/Expensify/App/issues/30025#issuecomment-1772117513) and I agree that this issue may be fixed by the other one, so I think we should consider putting this one on hold until it's fixed and then re-evaluate it again. What do you think?

**Comment by puneetlath** [comment]
Sounds good. I've put this issue on hold for #28029.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold. Looks like https://github.com/Expensify/App/issues/28029 is getting close.

**Comment by puneetlath** [comment]
@lanitochka17 can you re-test?

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 1.4.21-1


https://github.com/Expensify/App/assets/78819774/12cefe04-137f-47ec-b0ce-a8991640a1a9

**Comment by puneetlath** [comment]
Ok great! Going to go ahead and close this out.
