### ISSUE TITLE
Workspace is not selected as participant when a manual request is created

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#30032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1697753703178409)

## Action Performed:
1. In a workspace chat, click on "Request money"
2. Select manua, enter any amount
3. Click on "Next" button

## Expected Result:
The confirmation page should show the workspace in the field "to"

## Actual Result:
Nothing is shown as a selected participant, and the "Request" button is disabled

https://github.com/Expensify/App/assets/6829422/34da6369-84bd-40f7-8937-03d251123666

## Workaround:
No workaround

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
In the thread, we found that it was related to https://github.com/Expensify/App/pull/27547

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/App/pull/27547) that introduced the regression was reverted [here](https://github.com/Expensify/App/pull/30040). @Christinadobrzyn could you handle the payment for @hoangzinh? Since help us to test another [PR](https://github.com/Expensify/App/pull/30036) and caught the original fix wasn't enough to fix the regression?

**Comment by Christinadobrzyn** [comment]
Yep! @marcochavezf and @hoangzinh does $500 or $250 sound good for payment? Not sure how much work was done on this. Thanks!

**Comment by lukemorawski** [comment]
@thienlnam @marcochavezf I think  I have the solution to this problem so https://github.com/Expensify/App/pull/27547 could be merged again.

**Comment by thienlnam** [comment]
@lukemorawski Could you create another PR with the fix and then the original reviewers can take another look at it?
