### ISSUE TITLE
[CRITICAL] [P2P Activation] Preview component and system message are out of order for pending payments

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30035]
[slack thread](https://expensify.slack.com/archives/C05RECHFBEW/p1697739357210919)

coming from https://github.com/Expensify/App/pull/29430

The system message should be the most recent message when a payment is held on a pending wallet, after the preview component for said payment.

<img width="1272" alt="image" src="https://github.com/Expensify/App/assets/22508290/8824f2b7-02d8-4c87-a665-657c94610c57">

**Comment by techievivek** [comment]
This is fixed and was worked internally.
