### ISSUE TITLE
[Awaiting C+ payment confo] Fix issues with the LHN previews and report actions surrounding iou/expenseReports when owed and paid.

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#30042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.87-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** came from [this issue](https://github.com/Expensify/App/issues/26669). 

## Action Performed:
**Create an iouReport**
1. Global Create > Request Money > $50 > choose a person > Confirm
2. Land in the DM 
3. Look at the LHN row to observe the preview

**Create an expenseReport**
1. Create a workspace if you need to
2. Global Create > Request Money > $50 > choose the workspace > confirm 
4. Land in the workspace chat
5. Look at the LHN row to observe the preview

**Pay an iouReport**
1. Navigate to the iouReport view
2. Click `Pay elsewhere` green button at the top right of the report

**Pay an expenseReport**
1. Navigate to the expenseReport view
2. Click `Pay elsewhere` green button at the top right of the report
3. Observe the system message added to the expenseReport
4. Observe the LHN preview 

## Expected Result:

When an iouReport or expenseReport is "owed" the logic is as follows: 

The logic for the LHN row when someone is owed is as follows: 
>Title: [%displayName% || %workspaceName%] owes £21.96
>Preview: %firstName%: requested %amount% for [%merchant% || %comment%]

I.e 

**IOU Report**
>Jeff Banks owes £21.96
>Tom: requested £5.00 for Thursday Lunch

**Expense Report**
>Duraflame owes £21.96
>Tom: requested £5.00 for Home Depot

When an iouReport or expenseReport is "paid" the logic is as follows: 

1. The reportAction added to the iouReport/expenseReport comes from the reimburser who paid
2. The iouReport/expenseReport LHN title updates to "%workspaceName% paid %reportTotal%"
3. The iouReport/expenseReport LHN preview shows the sys message in (1) from the reimburser. 
4. The DM/workspace chat LHN preview shows (2).

I.e 

**Report Action in the expense/iouReport**
>**%reimburser% 11:58am**
>paid $50.00 elsewhere

**expenseReport LHN**
>Duraflame paid $50.00
>Tom: paid $50.00 elsewhere

**workspace chat LHN**
>Joe Bloggs || Duraflame
>Duraflame paid $50.00

## Actual Result:
The LHN preview is incorrect when someone owes:

<img width="306" alt="image" src="https://github.com/Expensify/App/assets/16232057/692f21f9-92ea-4572-b924-8a7a339da291">

The report action added to the iou/expenseReport is incorrect when someone pays the report:

<img width="1434" alt="image" src="https://github.com/Expensify/App/assets/16232057/8b62fcfa-58e9-4aab-b210-e7dc68ed776b">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01653befc45305851e</li>
        <li>Upwork Job ID: 1715173054584414208</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by koko57** [comment]
Ready to work on this issue 😊

**Comment by trjExpensify** [comment]
Wahoo, thanks!

**Comment by koko57** [comment]
@mountiny thanks! for now - no questions 🙂

**Comment by mountiny** [comment]
hmm good question, given its a group and it could bea nyone it makes sense that we add their name there

**Comment by koko57** [comment]
@mountiny @trjExpensify sorry it takes me so long, but this logic is very confusing and I think a major refactor here is necessary. Just to make sure: do we want to make it under this ticket or should I fix the issue first (in as easy and safe way  as possible)  and then plan some bigger changes as a follow-up? WDYT?

**Comment by koko57** [comment]
and my second question here regarding the requestor: for other chats, we have a logic not to show the lastActorDisplayName when it's a current user. 
So if the IOU report looks like this:

Jeff Banks owes £21.96
Tom: requested £5.00 for Thursday Lunch

It looks like we want to display it that way for Jeff. For Tom the title will be the same. What about the last message? Should it look the 
same for Tom? Or should it just say "requested $5.00 for Thursday Lunch"?

What about the workspace?

**Comment by mountiny** [comment]
I think we can refactor it here, we do not have to rush and i agree this has been a resource of lots of issues so if we can find a better cleaner solution that will be be great

In terms of the requestor, i think this is a great question and i feel like this might be unnecessary complication we could get rid off to simplify stuff. What do you think @trjExpensify?

On the screenshots the expected results say the paid message feom the workspace in case of workspace chat lhn preview should say the workspace name paid, the name of payer is only in the expense report

**Comment by trjExpensify** [comment]
Heya! Catching up after being out for a couple of days last week.

>In terms of the requestor, i think this is a great question and i feel like this might be unnecessary complication we could get rid off to simplify stuff. What do you think @trjExpensify?

The logic for when the iou/expenseReport LHN preview line has a name proceeding it or not should be exactly the same as a "normal" message in a chat. Why wouldn't we keep that consistency? So if it's your own request, you don't see your name. If it's someone else's request, you do see the requestor's name. 

>On the screenshots the expected results say the paid message feom the workspace in case of workspace chat lhn preview should say the workspace name paid, the name of payer is only in the expense report

Correct! The workspace chat/DM LHN preview is simply the title of the iou/expenseReport being previewed. So in this case once the report being previewed has been paid it would be:

expenseReport: `Duraflame paid $50.00` 
iouReport: `Tom Rhys Jones paid $50.00`

**Comment by koko57** [comment]
Still working on it. Tomorrow I'll be ooo (bank holiday in Poland) will continue on Thursday

**Comment by koko57** [comment]
@mountiny @trjExpensify I've tried really hard to extract and simplify the logic here but ended up making it a little bit more complex because of the many conditions we have to check to get a proper message. All the logic for report preview is already in [getReportPreviewMessage](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/ReportUtils.js#L1798) and the last messages for all the action types are created with getLastMessageTextForReport. We have an additional logic for getting the lastActor name outside this function https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/SidebarUtils.ts#L396-L406. 
It's not necessary for all the LHN secondary texts (alternateText) because the lastActor is generated in some of the functions creating massages (like in getReportPreviewMessage). We have also additional logic for alternate text here: https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/SidebarUtils.ts#L418-L480. 
Moreover, we have quite similar logic here: https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/OptionsListUtils.js#L519. I wonder if we could unify it.

I was thinking of a way to do it separately - choosing the lastActor and creating the rest of the message and then creating a full message with them. I would do it for all the LHN sidebar links. For this function https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/OptionsListUtils.js#L381 I'm not sure if it could be simplified, but getting rid of the logic for getting the lastActor would simplify a bit i.e. https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/libs/ReportUtils.js#L1798.

Regarding this thread (https://callstack-hq.slack.com/archives/C02MW39LT9N/p1698798330356389) do we have a doc with all the messages for different report actions?

As I've mentioned earlier, for now, I added some logic to getReportPreviewMessage to get the messages right for money requests. Now they look like this:

admin vs member

<img width="299" alt="Screenshot 2023-11-03 at 07 48 32" src="https://github.com/Expensify/App/assets/28020445/fee2836e-7016-4241-94d0-cbd643a2f776">
<img width="301" alt="Screenshot 2023-11-03 at 07 46 31" src="https://github.com/Expensify/App/assets/28020445/9136acf9-0221-4cda-8a4c-3cc3367934de">

---

payer vs requestor

<img width="309" alt="Screenshot 2023-11-03 at 07 49 49" src="https://github.com/Expensify/App/assets/28020445/a59f2ad9-bed8-49d1-aa37-999148b13476">
<img width="298" alt="Screenshot 2023-11-03 at 07 50 55" src="https://github.com/Expensify/App/assets/28020445/ea096bc1-e213-43b1-b24c-6844b8e75d3d">

---

admin vs member

<img width="305" alt="Screenshot 2023-11-03 at 09 30 24" src="https://github.com/Expensify/App/assets/28020445/29d9e11f-eecc-4b81-ba91-d9f4a7be134b">
<img width="300" alt="Screenshot 2023-11-03 at 09 29 42" src="https://github.com/Expensify/App/assets/28020445/fcc4b000-dc8a-45ec-afb8-4d9a0012f3ed">

should it be "New Workspace owes [amount]" instead? (first line)

---

payer vs requestor

<img width="292" alt="Screenshot 2023-11-03 at 08 57 41 copy" src="https://github.com/Expensify/App/assets/28020445/8bc27638-4a62-4523-b4bc-461b4a8917b2">
<img width="292" alt="Screenshot 2023-11-03 at 08 57 41" src="https://github.com/Expensify/App/assets/28020445/f527c6c7-ba28-4710-8b75-cee256c17bde">

should it be "John Kowalsky owes [amount]" instead? (first line)


I can easily change the display name for the long one (name + last name) if necessary. Asked some additional questions under these images. Maybe those changes could be merged before making the changes for all the LHN messages?

**Comment by mountiny** [comment]
Yeah this is quite tricky and we do not have a document right now with all the messages unfortunately

> should it be "New Workspace owes [amount]" instead? (first line)

Which first line exactly, not sure, also for the second question

> Maybe those changes could be merged before making the changes for all the LHN messages?

yeah I am all for making this incremental

**Comment by koko57** [comment]
@mountiny I meant the first item (report) from each column
John Kowalsky / Anakin Sky 
should be: [John] requested [amount] or Anakin owes [amount]

and

Agata Kosior / New Workspace
[Agata] requested [amount] or New Workspace owes [amount]

the second option for each would aligned with what Tom said that the message of the chat should be the same like the title of the preview. (Should we also display a full name there? And only there?)

> Correct! The workspace chat/DM LHN preview is simply the title of the iou/expenseReport being previewed. So in this case once the report being previewed has been paid it would be:
> 
> expenseReport: `Duraflame paid $50.00` iouReport: `Tom Rhys Jones paid $50.00`

**Comment by trjExpensify** [comment]
Thanks for your continued effort here, @koko57! Looking at the screenshots, a couple of things and maybe answering your Qs as well!. 

The lastActor in the LHN message previews typically uses a `:` colon after the actor first name doesn't it? But these examples of the report action previews inside the iou/expenseReport don't seem to use that same structure for the viewer of other people's actions? I.e

_____
**EXPENSE REPORT**

**Request action preview** (admin viewer) 
>Duraflame owes $100.00
>Tom: requested $50.00

**Request action preview** (requestor viewer) 
>Duraflame owes $100.00
>requested $50.00

**Paid action preview** (admin viewer)
>Duraflame paid $100.00
>paid $100.00 elsewhere

**paid action preview** (requestor viewer)
>Duraflame paid $100.00
>Agata: paid $100.00 elsewhere

**comment preview** (comment sender viewer)
>Duraflame owes $100.00   _<--- note: this is obviously variable dependent on if the report title is `owed` or `paid`_
>blah blah, I love bananas! 

**comment preview** (comment receiver viewer)
>Duraflame owes $100.00   _<--- note: this is obviously variable dependent on if the report title is `owed` or `paid`_
>Tom: blah blah, I love bananas! 
_____

**IOU REPORT**
So that same logic will apply to iouReports as well. For brevity, the below examples are just Agata looking at a variety of actions Tom took only to highlight the `:` in use. 

**request action preview**
>Tom Rhys Jones owes $50.00
>Tom: requested 10.00

**paid action preview**
>Tom Rhys Jones paid $50.00
>Tom: paid $50.00 elsewhere

**comment preview**
>Tom Rhys Jones owes $50.00  _<--- note: this is obviously variable dependent on if the report title is `owed` or `paid`_
>Tom: blah, blah, I love apples!  

______
**DM / WORKSPACE CHAT**

As for the DM/Workspace Chat LHN preview message when the expense/iouReport is the lastMessage being previewed, those don't use a colon separator because none of the chat participants are the "author" of the report preview component being previewed. So those just use the report title of the expense/iouReport being previewed.

**owed iouReport being previewed** (Agata view - DM)
>Tom Rhys Jones
>Tom Rhys Jones owes $50.00

**owed iouReport being previewed** (Tom view - DM)
>Agata Kosior
>Tom Rhys Jones owes $50.00

**paid iouReport being previewed** (Agata view - DM)
>Tom Rhys Jones
>Tom Rhys Jones paid $50.00

**paid iouReport being previewed** (Tom view - DM)
>Agata Kosior
>Tom Rhys Jones paid $50.00

**owed expenseReport being previewed** (member view - workspace chat)
>Duraflame
>Duraflame owes $50.00

**owed expenseReport being previewed** (admin view - workspace chat)
>Tom Rhys Jones
>Duraflame owes $50.00

**paid expenseReport being previewed** (member view - workspace chat)
>Duraflame
>Duraflame paid $50.00

**paid expenseReport being previewed** (admin view - workspace chat)
>Tom Rhys Jones
>Duraflame paid $50.00


_____

Let me know if you want to go through any of that if it still isn't clickin', happy to do a quick call or something if it's helpful! 😄

**Comment by koko57** [comment]
@trjExpensify Thanks for the clarification and all the examples! Now I get it. 
For adding this colon we need to add another condition and this way we'll make the logic a little bit more complex again. 
I'll add this to the PR.

**Comment by trjExpensify** [comment]
Cool, glad that was helpful! 👍

**Comment by koko57** [comment]
I've found one issue while working on this one - the amount in the originalMessage when the request is a scan is 0.00 even after setting the amount manually (total value is updated though).
<img width="295" alt="Screenshot 2023-11-08 at 10 01 05" src="https://github.com/Expensify/App/assets/28020445/976fda68-4f4a-443a-85a4-60c84858563f">

**Comment by mountiny** [comment]
Thats probably existing issue with some optimistic update there

**Comment by trjExpensify** [comment]
Is it this perhaps? https://github.com/Expensify/App/issues/23038

**Comment by koko57** [comment]
@trjExpensify no, that looks like a different issue - the issue I've mentioned  is between two registered accounts. It's when changing [scan] request value manually before or after scan failing.

**Comment by trjExpensify** [comment]
Ah, okay. After you refresh does it update correctly? 

I think that could be related to [this issue](https://github.com/Expensify/App/issues/29828) with the delay in a receipt not being a whisper anymore upon manually editing the merchant, date or amount of request to stop the receipt scanning process. CC: @cristipaval @artus9033

**Comment by cristipaval** [comment]
It is probably related to the root cause I fixed in this [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/39523), which is merged but not deployed yet. The issue is that when a receipt is being scanned, if the user manually updates the transaction, the Pusher updates are also sent to the other report participants. However, the transaction is only whispered to the reporter, so the Pusher updates should only be sent to the reporter's devices.

**Comment by koko57** [comment]
PR ready for review https://github.com/Expensify/App/pull/31061

**Comment by trjExpensify** [comment]
Amazing!!! ❤️

**Comment by mountiny** [comment]
The PR has unfortunately caused lots of regressions because the logic it changes is used in lots of other places and it was not caught in testing of the PR, we will need to give this another go and add all the regression cases as test cases for the PR.

I am wondering how we could make this code better, because its not a first time we struggle to make changes to such a relatively small part of the code but it proves to be really hard due to how intertwined it is

**Comment by koko57** [comment]
@mountiny @trjExpensify @mananjadhav I'm sorry that this PR caused so many problems! I could possibly fix all the issues in my code and try to open the PR again, but I wonder if it would be better to find another solution for this issue. 
I know that the this function introduced I created `getReportPreviewMessageForOptionList` is the main culprit here and fixing it would fix the issues but it's still adding more complexity to already complex logic.

The only thing that comes to my mind now is to simplify somehow this function: https://github.com/Expensify/App/blob/2f9ae2d37354ce3335d16805d05c313ef3d25fa9/src/libs/OptionsListUtils.js#L380-L417 - to be able to get rid of the function I created and make it more flexible for the changes that may come. I mean, if there would be new action types introduced later, this function will grow and will require new functions to create messages for the new types.

**Comment by mountiny** [comment]
@koko57 no worries, this is indeed very complex.

I agree that we should simplify this and I am not sure how exactly, the problem is that the message is created per the report action type basis so yeah whather we do we will have some big if/else block based on the message types.

**Comment by trjExpensify** [comment]
Sounds good! I'm going to remove the payment hold from the title of this issue as we're still working on it.

**Comment by koko57** [comment]
@trjExpensify @mountiny I've been investigating recently how we could use the data we get with `report` and `reportActions` object. For the report object we have properties like `lastMessageText`, `lastMessageTranslationKey` (the latter one is only used for the messages with attachments) and for the `reportAction` we have message, `originalMessage` objects but we only use them in a few cases like task actions.

I was wondering - could we possibly have lastMessageTranslationKey for the other reports (or maybe messageTranslationKey for the reportActions)? We could use it as the main source of truth and having only additional logic for checking if the `translationKey` need some additional params or not. This way we would not have to check for the message type then to trigger all the function we have to check for some other parameters to create the `lastMessageText`. 
Now we’re doing a lot of calculation here on the frontend but maybe it would be possible to move it at least partially to the backend? We could also fallback to `message.text` if necessary and use the `translationKey` for the messages for optimisticData.

It's just an idea now, I'm trying to somehow simulate this with the data we have but I wanted to ask you what do you think of it?

**Comment by mountiny** [comment]
I think its in interesting idea, but something we would ideally do as a last resort. The complication I see with this iss that currently we send the same report action data to all participants, no matter if they are the admin or employee or whatnot. 

The format of the message for the specific user depends on who is looking at it, we would need to implement all of this logic in the backend which adds complexity there. 

I guess its just about where to move that complexity.

**Comment by mountiny** [comment]
I think exploring other solutions should be a priority still

**Comment by koko57** [comment]
@mountiny @trjExpensify I'm working on another solution - it seems pretty simple and should not affect other preview messages (I wonder why I didn't come up with it earlier 😅). I will try to test it against all the cases that showed up after merging the previous PR. 
However, it won't simplify the logic, but if it won't cause any regressions, maybe it would be good to merge it and get the messages displayed properly and then think of some improvements and refactors.

**Comment by mountiny** [comment]
Waiting for a new update

**Comment by koko57** [comment]
I need to cover one more case with displaying author for messages in the expense reports.

> comment preview (comment sender viewer)
>
> Duraflame owes $100.00 <--- note: this is obviously variable dependent on if the report title is owed or paid
> blah blah, I love bananas!
>
> comment preview (comment receiver viewer)
>
> Duraflame owes $100.00 <--- note: this is obviously variable dependent on if the report title is owed or paid
> Tom: blah blah, I love bananas!

The rest seem to be working well

**Comment by koko57** [comment]
<img width="1073" alt="Screenshot 2023-12-18 at 11 11 22" src="https://github.com/Expensify/App/assets/28020445/160ea2ef-c0ad-40b0-80e8-400ee01d7776">
<img width="997" alt="Screenshot 2023-12-18 at 11 32 36" src="https://github.com/Expensify/App/assets/28020445/eab9b1ce-b64e-4519-a912-0c9c3d24fcd1">

I wanted to continue working on this one today, but I've encountered a bug after merging with the newest main - it's also present on staging. After opening a chat with a request the data is being changed and no user name is displayed, for the paid request the amount is displayed as TBD. Before opening the chat the preview was displayed properly (paid [amount] elsewhere) and now it's "This is the beginning of...". I cannot work with this bug, I wonder if it was already reported

**Comment by trjExpensify** [comment]
It sounds like you're describing this bug, yeah? https://github.com/Expensify/App/issues/32650

**Comment by koko57** [comment]
kinda the same, but it's for manual requests - so not 100% sure if the same root cause

**Comment by koko57** [comment]
I think I'm almost ready to create the PR - I need to test it once more thoroughly. I'd also hold for the 2nd PR for this issue - https://github.com/Expensify/App/issues/31312 it's in draft. I change the method for getting the display for participant name there.

Two more questions though: shouldn't we display the name of the message's author for a multiple chat? For now we don't do it (staging)
<img width="367" alt="Screenshot 2023-12-18 at 16 09 17" src="https://github.com/Expensify/App/assets/28020445/ab0a4596-3feb-4c86-842d-3b7ca457874b">

And can we display always the first name for all the preview types that display author's name with a colon? (i.e.: Tom: Hello)

**Comment by mountiny** [comment]
I think we should do that there, but maybe we can leave it out for a separate PR just to separate the concerns

**Comment by koko57** [comment]
Before I open the PR - pasting the list of the regressions from the previous PR to be tested:

* [[HOLD for payment 2023-12-06] [$500] Web - Login - App crashes when login to HT account #31803](https://github.com/Expensify/App/issues/31803)
* [[HOLD for payment 2023-12-06] [HOLD for payment 2023-12-04] [$500] IOU - LHN for IOU report shows the local currency when a different currency is requested #31838](https://github.com/Expensify/App/issues/31838)
* [[HOLD for payment 2023-12-06] [HOLD for payment 2023-12-04] [$500] IOU - IOU report preview in LHN does not show the latest amount when the amount is updated #31840](https://github.com/Expensify/App/issues/31840)
* [[HOLD for payment 2023-12-06] [HOLD for payment 2023-12-04] Desktop - LHN is not updated on Member side after expense paid #31844](https://github.com/Expensify/App/issues/31844)
* [The app crashed when an employee requested money for the second time from the admin #31833](https://github.com/Expensify/App/issues/31833) (possible regression, but not a documented one)

**Comment by koko57** [comment]
BTW while testing found a bug (it's also on staging):

Instead of the preview only Workspace name is displayed. If it's possible I'll try to fix it in this PR

Search Page:

<img width="374" alt="Screenshot 2023-12-19 at 21 27 16" src="https://github.com/Expensify/App/assets/28020445/a7cf3d13-25ea-4a75-982c-5d892129ccd0">

LHN:

<img width="371" alt="Screenshot 2023-12-19 at 21 27 40" src="https://github.com/Expensify/App/assets/28020445/479da07c-8dba-4f10-9e97-572f347f5e3f">

**Comment by koko57** [comment]
Ok, there is another problem with the Search page previews: the name is displayed twice (also on staging). I think it would be better to solve this problem in another PR and now focus on the LHN previews

<img width="678" alt="Screenshot 2023-12-20 at 12 18 51" src="https://github.com/Expensify/App/assets/28020445/6ab29240-1322-449b-8ed3-0ac71d95891b">

**Comment by koko57** [comment]
@mountiny @trjExpensify just wanted to let you know before I go ooo. I've opened a draft PR for the LHN previews. I haven't fixed the issues with Search Page previews, I think it would be better to fix them in another issue and here focus only on the LHN previews for IOUs.

I can open the PR for your review, but as I'll be back on Wednesday maybe it would be better to open it when I'm back? WDYT? I can open the PR today if you want.

**Comment by mountiny** [comment]
> I can open the PR for your review, but as I'll be back on Wednesday maybe it would be better to open it when I'm back? WDYT? I can open the PR today if you want.

Sounds good!

I agree its better to handle this in a separate PR

**Comment by koko57** [comment]
[PR](https://github.com/Expensify/App/pull/33346) opened for review 🙂

**Comment by koko57** [comment]
@mountiny @mananjadhav thanks for the review! there is one regression from this PR - showing the colon in messages. I've already found a solution, posted a proposal in the [issue](https://github.com/Expensify/App/issues/33741) and I'm creating a draft PR for that. 

I'm going to list all the problems I've found while working on this issue, but we decided to handle it in a separate PRs. I also have some ideas on next steps that we could take if we want to simplify this logic and refactor the code.

**Comment by trjExpensify** [comment]
Looks like we're working through a follow-up PR, Melv!

**Comment by mountiny** [comment]
The follow up has been merged too

**Comment by mountiny** [comment]
I think we can pay this out to @mananjadhav @trjExpensify 

I am not sure if this should be counted as a regression or not

**Comment by trjExpensify** [comment]
If we had to revert it once, that seems like it counts as a regression to me unfortunately. Open to other thoughts on that!

**Comment by koko57** [comment]
@mountiny @trjExpensify what about the other follow-ups? Will we have another ticket for that and close this one or we'll have this one left opened? 

By the follow-ups I mean the one we discussed in doubled payer's PR https://github.com/Expensify/App/pull/33966#discussion_r1444808394 (I also mentioned this earlier)

> * unify the logic for getting alternateText for [getOptions](https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/OptionsListUtils.js#L1063) and [getOptionData](https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/SidebarUtils.ts#L234)

and what about this one?
> * [ ]  name of the user sending a message in multiple users' chat is not displayed

Let me know wdyt 🙂

**Comment by mananjadhav** [comment]
@mountiny @trjExpensify I understand about the regression but this one was a difficult PR. I was earlier going to request for the increase in the bounty but considering that we had a regression, if we can payout the standard amount that would be great.

**Comment by mountiny** [comment]
I do think we can keep this at $500 given the time this took to review and the complexity of the PR. We have reverted and did another attempt  so its not like we have paid someone else for a fix.

@koko57 Lets create new issues for these. I believe you can create issues yourself, would you mind doing so and tagging me in them to apply the correct label.

Just link to this PR and frame the issue as Problem/ Solution

**Comment by trjExpensify** [comment]
Perfect, sounds good to me. So confirming the payment is $500 to @mananjadhav for the C+ review. Feel free to go ahead and request money!

**Comment by mountiny** [comment]
@mananjadhav once requested note here and we can close, thanks!

**Comment by mananjadhav** [comment]
I've [requested](https://new.expensify.com/r/5158965919597327) the payment on NewDot.

**Comment by trjExpensify** [comment]
Closing!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/30042#issuecomment-1888024448).

**Comment by paultsimura** [comment]
Hey, just wanted to raise a little awareness: this PR likely caused a regression when an updated amount is not displayed in the LHN because of these lines:

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/ReportUtils.ts#L2254-L2263

Basically, that's because the `originalMessage` holds only the initial amount value, not `modifiedAmount`.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/f49aecae-1046-48e9-8dcd-313af095aaf5">

I haven't seen a GH for this, just noticed it while working on one of my PRs.
cc: @mountiny @koko57

**Comment by mountiny** [comment]
Pi believe this was raised internally but its true that the root cause is that the report action only has the original amount. So it might misbehave for smartscans specifically or when amount is edited

**Comment by koko57** [comment]
@paultsimura thanks for pointing this out! @mountiny yes, the last action for this type of chat doesn't have the updated value - we only have CREATED and IOU actions for this type of report and later we don't have the MODIFIEDEXPENSE action. If we go to the details we have the MODIFIEDEXPENSE action, so the preview is displaying a proper amount.
<img width="1475" alt="Screenshot 2024-01-22 at 10 44 29" src="https://github.com/Expensify/App/assets/28020445/7b84725d-e7db-4074-8b15-5b1c521f6b35">
<img width="1476" alt="Screenshot 2024-01-22 at 10 45 15" src="https://github.com/Expensify/App/assets/28020445/45e64495-337b-4862-868e-5cbca7d1a927">
<img width="1467" alt="Screenshot 2024-01-22 at 10 37 05" src="https://github.com/Expensify/App/assets/28020445/6460df49-d6e9-4684-a968-019d69ef3ad0">
<img width="1469" alt="Screenshot 2024-01-22 at 10 37 22" src="https://github.com/Expensify/App/assets/28020445/9a5cf529-c6dc-46e1-9c5d-da5d2c7898fc">

**Comment by mountiny** [comment]
@koko57 Correct, but I believe we need to connect with Transaction collection in this case to make it work correctly.

the report action has the IOUTransactionID and that transaction object holds the correct amount
