### ISSUE TITLE
[$500] Wallet - Unable completed the wallet connection  without receiving correct test data. Connecting BA via Wallet not showing transfer balance onle enable wallet displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**This issue was found when executing PR:** https://github.com/Expensify/App/pull/29573

**Version Number:** v1.3.87-8

**Reproducible in staging?:** Y

**Reproducible in production?:** N
Unable to verify Alberta Charleson account in production

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Preconditions: The user must not have enabled the wallet yet and must have no payment method.

1. Go to https://staging.new.expensify.com/
2. Go to Settings
3. Go to Wallet
4. Press 'Add payment method'
5. Press 'Bank account'
6. Select the Bank "Chase"
7. Enter credentials and continue the flow selecting Plaid 0000
8. Press save and Continue
9. Press continue
10. Press back and tap Wallet again

## Expected Result:
Steps completed successfully. The enable wallet button is must not be shown and transfer balance as a link must be shown.

## Actual Result:
If I enter test data for Alberta Charleson, then Onfido verification follows. The enable wallet button is shown instead of showing transfer balance as a link.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/d57f6996-af93-4c8b-8c3e-09af97c59a28

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/a072b979-bf97-43c4-a3fa-4925aac29492

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/e7f898d6-437a-4d00-9026-3b4e6b69b5f2

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/115492554/b75189e8-7ea0-45f3-ba45-84561512d96d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e955090352dc810f</li>
        <li>Upwork Job ID: 1715325463617654784</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by MariaHCD** [comment]
Not a blocker, we do not currently allow test wallets to be activated on staging. I think we can close for now.

Internal conversation here: https://expensify.slack.com/archives/C05RECHFBEW/p1697779547303629

**Comment by MariaHCD** [comment]
@izarutskaya when testing https://github.com/Expensify/App/pull/29573, only execute steps 1 - 8. Thank you!

**Comment by MariaHCD** [comment]
Yes, please 🙏🏼
