### ISSUE TITLE
[HOLD for payment 2023-11-01] [HOLD for payment 2023-10-31] Fix the double message on the iou report when we pay a money request using wallet

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#30075]
Coming from : https://expensify.slack.com/archives/C01GTK53T8Q/p1697796531033319?thread_ts=1697788964.150409&cid=C01GTK53T8Q
![Screenshot 2023-10-20 at 3 38 06 PM](https://github.com/Expensify/App/assets/35863227/db1c815b-cd8c-4c3c-a6ba-7e3e5bd8b8cd)

## Action Performed:
Pre-requisite
- UserA needs to be on the silver wallet.
- UserB needs to be on the gold wallet.
1. As userA request money from userB.
2. As userB pay userA.
3. Check the IOU report from both users end and confirm we only see a single system message.

## Expected Result:
We should see a single message that the user needs to update their wallet.

## Actual Result:
We're seeing two system messages asking the user to update their wallet and bank account.

CC @trjExpensify @kevinksullivan

**Comment by trjExpensify** [comment]
@techievivek you're putting a PR up for this yeah?

**Comment by techievivek** [comment]
Yes, I have added the PR, I have a quick question for @situchan

**Comment by trjExpensify** [comment]
Perfect!

**Comment by techievivek** [comment]
This is the updated PR for fixing the settled message behaviour: https://github.com/Expensify/App/pull/30112

**Comment by trjExpensify** [comment]
Checklist time! Bump, @situchan.

**Comment by trjExpensify** [comment]
Same, awaiting the checklist from @situchan Melv.

**Comment by situchan** [comment]
As wallet feature is in beta, yet to add regression test case.

**Comment by trjExpensify** [comment]
So payment here is $500 to @situchan for the C+ review of the internal PR.

**Comment by trjExpensify** [comment]
Q on the regression for wallet on another issue.

**Comment by trjExpensify** [comment]
Sent you an offer :)

**Comment by trjExpensify** [comment]
Paid!
