### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] [$500] Workspace - Crash when deleting a workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697777999060829

## Action Performed:
Prerequisite: have a workspace
1. Open the workspace #admins or #announce chat
2. Press the chat header to open the details
3. Press the workspace name below the chat name. You will be navigated to the workspace page.
4. Delete the workspace. You will be navigated back to the chat details.

## Expected Result:
 No crash happens

## Actual Result:
After the user is navigated back to the chat details, the app crashed

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/cff89ba0-21f1-4b03-9879-c4406c9d6cc2

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/8e25c363-b5df-41ad-a060-e73d8cc000fa

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/cac1e05b-fc6b-4fbd-aba0-d63a1772a2b7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/8e6818b8-58af-43dc-8937-bc950a0fe9bd

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/330686a1-ecf0-4cb8-8991-77a91f330add

https://github.com/Expensify/App/assets/93399543/a3530377-f3ea-4999-9748-de55d9d47329

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/b40ae90a-5410-4b35-9162-822441567e8b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da3b9ed2ccdd9252</li>
        <li>Upwork Job ID: 1715358049654792192</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27294854</li>
<li>bernhardoj | Contributor | 27294856</li>
<li>bernhardoj | Reporter | 27294858</li>
</ul></li>
    </ul>
</details>

**Comment by dangrous** [comment]
added you @zanyrenney to handle payment when it's needed! (10/30)

**Comment by zanyrenney** [comment]
sounds good ! I have ensured alll the contributors are already hired on the issue.

**Comment by dangrous** [comment]
I like the test, I think it's worth adding the regression test since this would probably be somewhat common (and that way it would get caught sooner).

**Comment by zanyrenney** [comment]
From Oct 20 so urgency bonus was still "live"

**Comment by zanyrenney** [comment]
**Payment summary**

@fedirjh requires payment [offer](https://www.upwork.com/nx/wm/offer/27294854) (Reviewer) - paid $500 + $250 urgency
@bernhardoj requires payment [offer](https://www.upwork.com/nx/wm/offer/27294856) (Contributor) paid $500 + $250 urgency
@bernhardoj requires payment [offer](https://www.upwork.com/nx/wm/offer/27294856) (Contributor) paid $50 reporting

regression test requested, all other actions complete.
