### ISSUE TITLE
[HOLD for payment 2023-10-31] [HOLD for payment 2023-10-30] [CRITICAL] [P2P Activation] Improve KYC delay handling

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30088]
Coming from https://expensify.slack.com/archives/C05RECHFBEW/p1697779604794959

# Problem

When KYC is delayed during the wallet upgrade flow, a user lands on a loading page without any guidance. This can take a very long time, or potentially forever, if they hit certain errors.

![image](https://github.com/Expensify/App/assets/22508290/c0b4cf47-b158-41a7-b6cb-f0d7c972981b)

# Solution

To start, let's provide better guidance when KYC is delayed. If the wallet is still pending when the user completes KYC:
1. Land them back on the Wallet page
2. Hide the `Enable wallet` button while KYC is delayed and 
3. Show the following message in the wallet tile: `We're reviewing your information and will be in touch shortly`

![image](https://github.com/Expensify/App/assets/22508290/c3880252-dbd0-4a40-9798-52da7351ffe8)

**Comment by puneetlath** [comment]
@kevinksullivan gonna reassign you as BZ since this is for wave8. Feel free to re-assign to whoever you think is best.

**Comment by MariaHCD** [comment]
BE PR that adds a new prop `isPendingOnfidoResult` to the wallet information is here: https://github.com/Expensify/Auth/pull/8991

The App will use this new prop to determine if we need to show the `We're reviewing your information and will be in touch shortly` message

**Comment by marcaaron** [comment]
Coming from https://github.com/Expensify/App/issues/30093 

I am wondering if we can combine the changes here with the case where Onfido fails. It might be better to have just one App PR and do a big E2E test to get it all out at once.

**Comment by marcaaron** [comment]
The App changes are [here](https://github.com/Expensify/App/pull/30114/files) (not quite finished) but the redirect logic from @allroundexperts' PR is something I think we will also need when the delayed Onfido check comes back and the user can't proceed at all.

**Comment by MariaHCD** [comment]
I'm inclined to merge https://github.com/Expensify/App/pull/30103 first (with No QA). Then we can follow it up with https://github.com/Expensify/App/pull/30114/ with a full E2E test. Although I think it's a bit tricky to simulate the different flows with Onfido...

**Comment by marcaaron** [comment]
Either work for me. And yeah not really sure how to properly QA this on prod since we need Onfido to fail in two different ways 🙃

**Comment by kevinksullivan** [comment]
Payment summary:
- @allroundexperts $500

**Comment by JmillsExpensify** [comment]
$500 payment for @allroundexperts based on comment above.
