### ISSUE TITLE
[HOLD for payment 2023-10-31] [HOLD for payment 2023-10-30] [$500]   Concierge not highlights on login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.87.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697780051399049

## Action Performed:
1. logout if you already logged in
2. enter email and magic code

## Expected Result:
Concierge should be highlights in LHN and should show chats

## Actual Result:
Concierge not highlights

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/26a91145-d760-4e5b-98c4-b00c80bf0d56

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/330c5a07-cd89-45a1-9d4b-a660a9d5fe42

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/b3390360-adc5-4a69-bd5e-4ecdd0ca1510

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/52d89df7-e123-484b-b982-680fc9e8e283

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

  

https://github.com/Expensify/App/assets/93399543/c1301d6b-a1b8-4842-9c1f-19687f5fd1b4

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/a93066a8-e23f-4378-886e-18edff0ba3dc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2ea61367ef9c991</li>
        <li>Upwork Job ID: 1715357740561367040</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by spectreintegrated** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Concierge should be highlighted/selected after login

### What is the root cause of that problem?
`currentReportID` is empty in `OptionRowLHNDataWithFocus` and thus doesn't highlight. It also gets cleared when clicking the "back" arrow to go back to LHN. Not sure if that is intentional.
### What changes do you think we should make in order to solve the problem?
if `currentReportID` is empty choose first item in list. If it being cleared by navigation is not intentional should last id be highlighted or just select top item?

### What alternative solutions did you explore? (Optional)

**Comment by spectreintegrated** [comment]
Contributor details
Your Expensify account email: info@spctr.ltd
Upwork Profile Link: https://upwork.com/freelancers/~01e0f115879dbdd44f

**Comment by luacmartins** [comment]
@bernhardoj's solution looks good. I went ahead and created a PR since we might CP it this weekend to fix it before Money2020 on Monday. We should compensate @bernhardoj accordingly.

**Comment by mountiny** [comment]
@dylanexpensify not written down but we usually use a rule of 25% so $125 to @bernhardoj for the help

**Comment by mountiny** [comment]
<img width="1264" alt="image" src="https://github.com/Expensify/App/assets/36083550/a8d70438-182e-4494-960e-eb2cf68cb426">

**Comment by dylanexpensify** [comment]
payment upcoming!

**Comment by dylanexpensify** [comment]
tomorrow, tomorrow, and tomorrow

**Comment by luacmartins** [comment]
just pending payment

**Comment by dylanexpensify** [comment]
@bernhardoj mind applying: https://www.upwork.com/jobs/~01a2ea61367ef9c991 🙇‍♂️

**Comment by dylanexpensify** [comment]
offer sent!

**Comment by dylanexpensify** [comment]
done!

**Comment by gadhiyamanan** [comment]
@dylanexpensify reporting bonus is pending

**Comment by gadhiyamanan** [comment]
Payment done for this issue, thanks!
