### ISSUE TITLE
[Hold #26031] [$500] iouReport report preview missing title

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#30089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.87-8
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** [internal ref](https://expensify.slack.com/archives/C05RECHFBEW/p1697804787113119?thread_ts=1697799956.598159&cid=C05RECHFBEW)

## Action Performed:

1. send a message from userB to userA, such that a message from userB is the first thing in the DM
2. Now as userA, send a request with a receipt to UserB
3. Observe that the title preview component appears correctly while it’s scanning i.e “UserA & UserB”
4. Wait for SS to complete (might need to navigate to another chat and back to force a refresh)
5. Observe that the title of the preview component disappears, making it appear as though the report preview is coming from userB who sent the message in (1) above.

## Expected Result:
The iouReport report preview component should have the title "PayerName & PayeeName" 

## Actual Result:
The title of the preview component disappears, making it appear as though the report preview is coming from userB who sent the message in (1) above.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/c1a6b946-eda2-45f1-8333-dcc668772823">

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/72c0ca5f-179e-41fe-a808-9d91bc935cd7">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @kevinksullivan 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3f572cd882bbdde</li>
        <li>Upwork Job ID: 1715391860029861888</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 You don't strictly have to go through the scan flow either for this, you can use a manual request and get the same result. It seems to be whenever there is a message before the preview component. 

Also, if you then go ahead and pay the request, the header of the preview component comes back. 

<img width="1166" alt="image" src="https://github.com/Expensify/App/assets/16232057/2f70540b-9ae9-46d7-8436-8fd790c3932b">

**Comment by paultsimura** [comment]
The root cause is the same as in https://github.com/Expensify/App/issues/26031

**Comment by abdel-h66** [comment]
I added a proposal over there https://github.com/Expensify/App/issues/26031#issuecomment-1773107234

**Comment by trjExpensify** [comment]
PR for the linked issue which will fix this is in review: https://github.com/Expensify/App/pull/30553

**Comment by trjExpensify** [comment]
Linked PR we're held on awaiting a re-review! Dropped to `weekly` while we wait that out.

**Comment by kevinksullivan** [comment]
going to drop this from the p2p project since we're held on another GH at this time and we're past the date.

**Comment by trjExpensify** [comment]
Deployed to prod! We should be good to go here. @aimane-chnaif did you test both cases with the linked PR, and can we close this now?

**Comment by trjExpensify** [comment]
Cool, done!
