### ISSUE TITLE
[HOLD for payment 2023-11-02] [HOLD for payment 2023-11-01] [CRITICAL] [P2P Activation] Improve wallet enablement error handling and allow someone to retry their info once

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30093]
context - https://expensify.slack.com/archives/C05RECHFBEW/p1697819082622369?thread_ts=1697779604.794959&cid=C05RECHFBEW

# Problem

When a user fails certain checks during the wallet upgrade flow, they can sit on this page forever with no guidance on how to fix it.

![image](https://github.com/Expensify/App/assets/22508290/8721db71-7b3f-40b1-8056-eef1224f54ee)

# Solution

In combination with [this ](https://github.com/Expensify/App/issues/30088), let's improve error handling.

Once KYC is delayed, we will do this https://github.com/Expensify/App/issues/30088

Then, for this GH, lets add:
1. **If KYC / enablement is successful** - update the Wallet UI to reflect wallet is activated, and send a notification from concierge so they are aware their wallet was activated.

- Copy: `Thanks for your patience! Your [wallet](https://new.expensify.com/settings/wallet) has been enabled! You can now send and receive money on Expensify.

2. **If KYC or some check fails after KYC was delayed** - update the UI to show a non-enabled wallet, and send a notification from concierge that explains it failed but tells them they can try again one time.

- Copy: `There was an error when enabling your Expensify Wallet. You can try again [here](https://new.expensify.com/settings/wallet)

**3. If they fail KYC twice** - hide the `Enable wallet` button, and add a message to the Wallet tile explaining they cannot move forward. 

- Copy: Unfortunately your wallet cannot be enabled at this time. Please chat with Concierge for further assistance.

![image](https://github.com/Expensify/App/assets/22508290/6ceced59-3ae0-4770-84b7-66976bb1b5ab)

**Comment by marcaaron** [comment]
>If KYC / enablement is successful - update the Wallet UI to reflect wallet is activated, and send a notification from concierge so they are aware their wallet was activated.

This one is easy.

>If KYC or some check fails after KYC was delayed - update the UI to show a non-enabled wallet, and send a notification from concierge that explains it failed but tells them they can try again one time.

This one is _less easy_ 😄 

We handle the delayed check that happens [here](https://github.com/Expensify/Web-Secure/blob/4c50401cc1fc31ebb54951aa26f4dedc03c2b433/lib/BankAccountAPI.php#L1509-L1515) in Web-Secure. There is no error handling at all yet (nbd we can add that). But the catch is that we need to send the error via Pusher. A lot has changed about how we do updates so we will have to hack this together unless we want to move the Onfido webhook out of web-secure (I'd prefer not to do that if we can avoid it).

>3. If they fail KYC twice - hide the Enable wallet button, and add a message to the Wallet tile explaining they cannot move forward.

Do we count attempts for this yet? Or is that something we want to add here? I would guess that some user level nvp called `onfidoAttemptsCount` would work for this.

**Comment by MariaHCD** [comment]
> Do we count attempts for this yet? Or is that something we want to add here? I would guess that some user level nvp called `onfidoAttemptsCount` would work for this.

We don't count attempt just yet. But we can probably add that field in the wallet's additionalData instead of a user-level NVP?

**Comment by marcaaron** [comment]
We are down to just one more PR in Web-Secure here to close this one out and an App deploy (hopefully later today). 
Web-E PR has been deployed to production and App PR has be CP'd to staging.

**Comment by marcaaron** [comment]
>We don't count attempts just yet. But we can probably add that field in the wallet's additionalData instead of a user-level NVP?

Oh yeah that could work too! Great idea.

**Comment by marcaaron** [comment]
Hey @kevinksullivan can we create a new issue for "allow someone to retry their info once". I need an Onfido break 🥺

**Comment by kevinksullivan** [comment]
>can we create a new issue for "allow someone to retry their info once". I need an Onfido break 🥺

Will do!
