### ISSUE TITLE
[HOLD for payment 2023-11-01] Stop saving receipt in IOU action

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30096]
# Problem
We're unnecessarily saving the receipt object in the IOU reportAction object

# Why is this important
Keeps data format consistent with what's expected

# Solution
Stop saving the receipt in the IOU action
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013916d2c5796f424f</li>
        <li>Upwork Job ID: 1715425653755682816</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
@akinwale offer sent

**Comment by akinwale** [comment]
> @akinwale offer sent

Accepted. Thanks!

**Comment by garrettmknight** [comment]
Nope - just had to pay you. Done!
