### ISSUE TITLE
[HOLD for payment 2023-10-31] Staging is crashing when opening a chat

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#30109]
Coming from [this Slack post](https://expensify.slack.com/archives/C049HHMV9SM/p1697838755135299?thread_ts=1697694190.199399&cid=C049HHMV9SM)

I'm getting a crash on login on staging and the PR for/from here already hit staging.

It's mostly happening after logging in with [mallen@expensifail.com](mailto:mallen@expensifail.com) account and trying to open my existing chat with  [mallen@expensify.com](mailto:mallen@expensify.com)  
ReportID: https://new.expensify.com/r/2545867663703719

Happening on Mac - Chrome and Windows - Chrome (via browserstack) and iOS - chrome. 

@situchan thinks it's likely a regression from
https://github.com/Expensify/App/pull/28798

Gonna hold off on the bottom stuff for a min....

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@situchan , wanna propose a solution?

**Comment by mallenexpensify** [comment]
@francoisl , I think/hope @situchan is working on a proposal/PR now

**Comment by situchan** [comment]
on it now

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when open IOU report with pay button

### What is the root cause of that problem?
Regression from https://github.com/Expensify/App/pull/28798. Bad fix of merge conflict
They missed to remove below line which was removed in https://github.com/Expensify/App/pull/29573
https://github.com/Expensify/App/blob/15aee9d588866754047fa946e470f79704411e4a/src/components/KYCWall/BaseKYCWall.js#L103

### What changes do you think we should make in order to solve the problem?
remove that line

**Comment by francoisl** [comment]
The proposal makes sense as that function no longer exists, though I can't reproduce the crash so I can't 100% tell if it will 100% fix everything.

**Comment by situchan** [comment]
crash log:

![image (1)](https://github.com/Expensify/App/assets/108292595/934a8e2e-bc3b-478e-b1fc-ae6b377fa16e)

**Comment by situchan** [comment]
I can reproduce this constantly:


https://github.com/Expensify/App/assets/108292595/b127e900-90a4-465e-9485-3acf06973778

**Comment by francoisl** [comment]
Got it, I think I must be hitting a flow where we're not rendering the `KYCWall`.

Let's go with your fix @situchan, can you submit a PR please?

**Comment by francoisl** [comment]
Nevermind, we're going to revert https://github.com/Expensify/App/pull/28798 instead.

**Comment by francoisl** [comment]
Tested on staging, removing blocker label

**Comment by mallenexpensify** [comment]
Compensating @situchan for discovering and reporting this deploy blocker, I chose $100 because it's 2x the bug report amount which seems fair for quick work finding a deploy blocker. 

Issue reporter: @situchan due $100 via Upwork.  

@situchan can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ef31182c5942b1de

**Comment by mallenexpensify** [comment]
Updated the above to reflect
> Issue reporter: @situchan paid $100 via Upwork.

Closing
