### ISSUE TITLE
[CRITICAL] [P2P Activation] IOUs and DMs aren't showing in the LHN when splitting a scanned receipt

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** kevin+4@expensifail.com

**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1697839451418869?thread_ts=1697836503.799519&cid=C05RECHFBEW

## Action Performed:
1. open global create
2. Select request money
3. Scan a receipt
4. Split with multiple users
5. Complete the split

## Expected Result:
The group DM, DMs with each person split with, and IOUs created from the split should all be shown in the LHN

## Actual Result:
Only the group DM is shown in the DM

Then additionally:
- The users I split with weren't at the top of my search list, but they did show up as if I had searched them before
- Selecting one of them brought me to the DM with the split
- When i backed out of that DM, all the IOUs/chats were showing correctly

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Shows only group DM in LHN:

![image](https://github.com/Expensify/App/assets/22508290/49608cbb-8218-42fb-bab5-85238d5fd138)

Searching for a user I split with show them, and tapping into them shows the the DM with the IOU created from the split

![image](https://github.com/Expensify/App/assets/22508290/133f7313-0033-4db7-b27c-5486b4b54ed5)

![image](https://github.com/Expensify/App/assets/22508290/3c7ce9d9-9596-48f2-a4a8-7304760cc3dd)

Then they're all shown in the LHN

![image](https://github.com/Expensify/App/assets/22508290/ca6ea69d-dd35-4c7f-9a7a-e08f543499e4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Confirming we just needed the Auth PR here?

**Comment by youssef-lr** [comment]
Correct @trjExpensify

**Comment by youssef-lr** [comment]
This should be fixed now!
