### ISSUE TITLE
 IOU - Total with amount line is misaligned in IOU report page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from user with no pending IOU
3. Go to the IOU report page

## Expected Result:
The Total with amount line is not misaligned

## Actual Result:
The Total with amount line is misaligned. It is way above the line separating the Total and IOU previews

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/69023c66-37c1-46d1-95fc-870f8e2a6ef8

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112b927d467996161</li>
        <li>Upwork Job ID: 1726739973694226432</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by mountiny** [comment]
![IMG_276664FE91C3-1](https://github.com/Expensify/App/assets/36083550/e03c9b84-14c0-4204-964a-cd5ab08aa224)

**Comment by srikarparsi** [comment]
Hey! Is there anything left that needs to be done for this issue?

**Comment by sakluger** [comment]
Reopening for payment to @aimane-chnaif for their PR review.

**Comment by sakluger** [comment]
@aimane-chnaif here's the Upwork job: https://www.upwork.com/jobs/~0112b927d467996161

**Comment by sakluger** [comment]
All paid out, thanks again!
