### ISSUE TITLE
[$500]  IOU - User B can see the red dot but don't see the error message in the empty fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/issues/30124#issue-1955580025
## Action Performed:
Pre-requisite: user must have sent a scan money request from user A to user B with missing merchant
1. With user A, confirm there is a red dot in LHN row for the transaction and the row for the IOU/money request report
2. With user A, go to IOU report details and confirm you see an error for missing merchant
3. With user B, confirm there is NO red dot in LHN row for the transaction and the row for the IOU/money request report
4. With user B, go to IOU report details

## Expected Result:
For user B, there should be an error message in the empty field in the IOU report details

## Actual Result:
For user B, there are no error messages in the empty fields in the IOU report details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/29e4677a-800f-4743-a9e6-11c2a8c5ecb0

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162d660f3d381d8a3</li>
        <li>Upwork Job ID: 1715775125819928576</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
User B is not the owner of the request, therefor User B can not edit that field. What should the error message say if we are willing to show some kind of indication. ?

**Comment by narefyev91** [comment]
> User B is not the owner of the request, therefor User B can not edit that field. What should the error message say if we are willing to show some kind of indication. ?

@adelekennedy Hey! Can you please clarify this?

**Comment by abdel-h66** [comment]
I think you mean to tag me @narefyev91  😄 , Well I was thinking if User B has no edit rights, why should we expect to see an error message that asks it to fill the empty field, that's why I asked what should the error message say.

**Comment by narefyev91** [comment]
If user B does not have edit rights - i think we should not show any error message - does not make any sense

**Comment by adelekennedy** [comment]
Yeah I don't think this is a bug - looks like applause made this external so let's close?
