### ISSUE TITLE
[$500]  Web - When command is run, error message appears (Onyx is not defined)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27547
## Action Performed:
Pre-requisite: user must be logged in and have some chats
1. Open JS console
2. Go to Application tab
3. In "personalDetailsList" key, look for the object that represents personal details of a contact you already have a chat with
4. Copy the ID
5. In console, run the following command: "Onyx.merge('personalDetailsList', {<account id you want to change>: {accountID: <account id you want to change>, avatar: "[https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png",](https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png%22,)
displayName: "", firstName: "", lastName: "", login: "", phoneNumber: "", validated: true}​})", replacing the ID you copied before

## Expected Result:
The name of the contact should be replaced by "Hidden" in LHN

## Actual Result:
An error message is displayed on console
Uncaught ReferenceError: Onyx is not defined at <anonymous>:1:1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/7b474c93-a41e-49f2-a5da-c2fad985804f

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b32cf134f5949260</li>
        <li>Upwork Job ID: 1715776405695508480</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
I think it's normal that Onyx is not exposed in a staging env. works fine on local .

**Comment by mountiny** [comment]
Yeah closing you cant do this in staging or prod
