### ISSUE TITLE
[$500] Currency - Dot (.) cannot be added into amount field if MRO currency selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB> Request money> Manual
3. Click Currency
4. Select MRO
5. Type any number and dot in amount field

## Expected Result:
Dot (.) should be entered and seen into amount field

## Actual Result:
Dot (.) cannot be added into amount field if MRO currency selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/73697018-98cb-4850-9d97-1b6a729fd321

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d5909ed29d6d625</li>
        <li>Upwork Job ID: 1715845386362593280</li>
        <li>Last Price Increase: 2023-10-28</li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
Seems like this currency does not have decimals allowed. `"decimals": 0,`

```
{
    "symbol": "UM",
    "name": "Mauritania Ougulya",
    "decimals": 0,
    "retired": true,
    "retirementDate": "2018-07-11",
    "ISO4217": "478"
}
```

**Comment by peymancyb** [comment]
I do also confirm and agree with @abdel-h66, based on the current config, the currency does not accept decimals which is the reason of not being able to use (.).

=> View [currencyList.json](https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/tests/unit/currencyList.json#L497-L503)

https://github.com/Expensify/App/assets/18486930/78656eba-6845-4019-b596-56d0e8593db0

**Comment by peymancyb** [comment]
Contributor details
Your Expensify account email: paymanghazvini@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015502e3fbe636dad6

**Comment by shubham1206agra** [comment]
This is what I got

The Mauritanian Ouguiya (MRO) is the official currency of Mauritania. In the context of currency, you typically cannot have less than 1 unit of the currency in a monetary transaction. The Ouguiya is subdivided into smaller units, with the most common denominations being the ouguiya and the khoums. One ouguiya is equivalent to 5 khoums.

So, for practical purposes, in monetary transactions, you would typically deal with whole numbers of ouguiyas or khoums, and amounts are not expressed as fractions of an ouguiya. For example, you might have 10 ouguiyas or 50 khoums, but you wouldn't typically have something like "0.5 MRO" in a standard transaction.

**Comment by burczu** [comment]
@dylanexpensify I've just checked what @shubham1206agra wrote in their comment and it seems to be kinda correct - in Mauritania there is only one coin that is less than 1 Ouguiya called Khoum which is 1/5 of Ouguiya. That's why, I guess, we have decimals disabled in the App for MRO currency, because it would hard to deal with it. 

So I think this may not be a bug, actually.

**Comment by dylanexpensify** [comment]
agree! thank you!
