### ISSUE TITLE
[$500] Android-IOU-Tapping IOU created and quickly tapping plus icon, its options displayed in IOU page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap plus icon near compose
3. Tap request money---manual
4. Enter an amount
5. Tap next
6. Tap request amount
7. Tap on IOU and quickly tap on plus icon near compose

## Expected Result:
The plus options of 1:1 page like request money, send money, assign task and add attachments must not be displayed in IOU page when user taps IOU created and quickly taps on plus icon near compose

## Actual Result:
The plus options of 1:1 page like request money, send money, assign task and add attachments are displayed in IOU page when user taps IOU created and quickly taps on plus icon near compose

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/7dae9876-98e0-4a69-a687-ab828f61caf3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e2e379d759da321</li>
        <li>Upwork Job ID: 1715851865875951616</li>
        <li>Last Price Increase: 2023-10-28</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Where is the screen recording or link to slack @lanitochka17 ?

**Comment by lanitochka17** [comment]
@zanyrenney Hello

The screen recording is located in the Screenshots/Videos tab


![image](https://github.com/Expensify/App/assets/78819774/7e1aff18-292c-42bc-83a5-8550ce4deaab)

**Comment by zanyrenney** [comment]
oh eek, thanks!

**Comment by zanyrenney** [comment]
@lanitochka17 I feel like I can't see any bug, how fast is "fast" here?

**Comment by lanitochka17** [comment]
@zanyrenney Hello
Issue reproducible in latest build 

https://github.com/Expensify/App/assets/78819774/b9b1585f-54cb-45f4-9113-4f362e2e9348

Compared to IOS, there is no way to open menu and IOU pages at the same time: 


https://github.com/Expensify/App/assets/78819774/36ac3b5c-d625-4456-b031-1a075e9e7744

**Comment by zanyrenney** [comment]
adding external.

**Comment by zanyrenney** [comment]
@mananjadhav what do you think of @ishpaul777 proposal above?

**Comment by mananjadhav** [comment]
I have a question on whether we should be fixing this one. I've raised it [here](https://expensify.slack.com/archives/C05LX9D6E07/p1698868457466129) internally. Will update once I get a response.

**Comment by zanyrenney** [comment]
Vit reviewed, said to close!
