### ISSUE TITLE
[HOLD for payment 2023-11-01] [HOLD for payment 2023-10-31] Change copy for wallet pending onfido

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30155]
coming from https://github.com/Expensify/App/pull/30103

Let's update the copy so people know they need to check back in, and we're not actually going to reach out to them (sunce that GH likely won't be live for Money2020)

<img width="382" alt="image" src="https://github.com/Expensify/App/assets/22508290/d978c822-e4f5-4ca1-bb36-61b552c5e04f">

Copy: We're reviewing your information, please check back in a few minutes!

**Comment by techievivek** [comment]
This was worked internally so no payment is needed here.
