### ISSUE TITLE
[$500] The main composer in the request report page is focused when closing the three dot menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697902847726839

## Action Performed:
1. Go to a request report page
2. Blur the main composer.
3. Tap the three dots icon.
4. Tap outside the menu to exit. Notice that the main composer is focused.

## Expected Result:
The main composer in the request report page is unfocused

## Actual Result:
The main composer in the request report page is focused

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/44710799-a3bc-4c97-9833-90332c0a79fd

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/5e555991-bede-4bc0-b266-ed8d432344e8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b32eafb37ff001e</li>
        <li>Upwork Job ID: 1716452642189750272</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

**Comment by abekkala** [comment]
not overdue, on hold

**Comment by abekkala** [comment]
still on hold

**Comment by abekkala** [comment]
still on hold

**Comment by abekkala** [comment]
https://github.com/Expensify/App/issues/15992 is still on hold

**Comment by abekkala** [comment]
still on hold

**Comment by abekkala** [comment]
still on hold

**Comment by abekkala** [comment]
@kbecciv can you recreate this and provide an updated video?
