### ISSUE TITLE
[$500] [Wave 6: Categories] IOU - Newly added category in old dot in real time not shown in category page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to Workspace chat as employee
3. Tap manual request
4. Enter an amount
5. Tap next
6. Tap show more
7. Tap category and stay in category page
8. In old dot as admin go to policy settings---Workspace---categories(Check image attached)
9. Scroll down and enter "realtime" and add a category(Check image attached)
10. Scroll down the category page which is kept opened already to note newly added category in old dot is not displayed in real time
11. Tap app back button
12. Tap category again and scroll down the page to note newly added category in old dot is not displayed in real time
13. Navigate back to Workspace chat page
14. Tap plus icon near compose box
15. Tap request money--- manual
16. Enter an amount
17. Tap next
18. Tap show more
19. Tap category and scroll down the page and note the newly added category in old dot is shown

## Expected Result:
When employee user is in category page, and admin adds new category(Realtime) , it must be reflected in real time and newly added category must be displayed

## Actual Result:
The category(Realtime) is not shown in real time, even after opening category page again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/3cafddf6-36d0-4607-823f-399594e1cace

![Bug6247598_1698077981803!iMarkup_20231023_214939](https://github.com/Expensify/App/assets/78819774/f20473e3-6561-4994-bb6e-c7aa6d357916)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5b26dbe71181657</li>
        <li>Upwork Job ID: 1716522065860767744</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
From my test, I see that category only be updated if we reload page

**Comment by mallenexpensify** [comment]
Thanks @parasharrajat , makes sense. 
Also.. should this be party of 'dynamically updating'?  I haven't seen Old <> New Dot referenced for 'dynamically updating' before but I'm unsure if it makes a difference (vs NewDot <> NewDot not dynamically updating)

**Comment by mallenexpensify** [comment]
Thanks for the context and detail Rajat!

**Comment by mallenexpensify** [comment]
From internal post
> category updates should be getting sent out via pusher. If they aren’t, that sounds like a bug

Added `Engineering` to get 👀 on it since, I think, Categories are live now (and tags soon too)

**Comment by puneetlath** [comment]
@mallenexpensify since this deals with Categories, let's add it to the wave6 project and we can have someone from the wave6 project team handle it.

**Comment by mallenexpensify** [comment]
I bumped to `Weekly` because there's not much I, as BZ, can/should do on a daily basis since this is now part of the wave6 project (and labeled as Medium).  Update/revert if ya disagree. 
- https://github.com/orgs/Expensify/projects/73

**Comment by puneetlath** [comment]
I'm going to un-assign @youssef-lr and @parasharrajat. This is a back-end issue and we'll handle it with the wave6 team.

**Comment by mallenexpensify** [comment]
> This is a back-end issue and we'll handle it with the wave6 team.
Bumped to weekly since this is on the Wave 6 radar/project board.

**Comment by mallenexpensify** [comment]
It's a medium on the [wave 6 project](https://github.com/orgs/Expensify/projects/73/views/1) tab, unsure when it's going to get worked on.

**Comment by mallenexpensify** [comment]
Discussing [here](https://expensify.slack.com/archives/C02MW39LT9N/p1700588092030279?thread_ts=1700518364.815229&cid=C02MW39LT9N) cuz it was tagged as 🔥

**Comment by aldo-expensify** [comment]
I started investigating and I see that:

- Updating the categories in OldDot DOES send an onyx update through the pusher with the new categories
- The categories in the workspace do get updated in Onyx

Considering this, I think this is just the UI not updating when the data in Onyx changes

Onyx update received:

```
{
    "id": "6560ffc80ae08",
    "chunk": "{\"updates\":[{\"data\":[{\"key\":\"policyCategories_86DE9484952328FF\",\"onyxMethod\":\"merge\",\"value\":{\"test2\":{\"name\":\"test2\"}}}],\"eventType\":\"onyxApiUpdate\"}],\"lastUpdateID\":\"7961\",\"previousUpdateID\":\"7958\"}",
    "index": 0,
    "final": true
}
```

Onyx:

<img width="659" alt="image" src="https://github.com/Expensify/App/assets/87341702/9da822fb-b73f-4a31-ba7a-7cee4e28ec9e">

**Comment by aldo-expensify** [comment]
hmnm I'm wrong, I think the backend is not pushing the category with all the information:

<img width="549" alt="image" src="https://github.com/Expensify/App/assets/87341702/1d445bb4-7d95-4f95-817f-1db126b97e02">

It is missing the `enabled` property for example

**Comment by aldo-expensify** [comment]
PR up: https://github.com/Expensify/Web-Expensify/pull/39835

**Comment by aldo-expensify** [comment]
Should we close this or is there anything else remaining?

**Comment by mallenexpensify** [comment]
I think we're good to close, there's no bug reporter nor a C+ who reviewed the PR. Rajat provided a couple comments above but I don't think they're valuable enough to warrant compensation, comment if anyone disagrees.
