### ISSUE TITLE
[HOLD for payment 2023-11-02] [Performance] Optimize setting initial state in functional components

### ISSUE THREAD

**Issue by sebryu** [Expensify/App#30209]
## What performance issue do we need to solve?
Setting initial state in functional components in a way that is running calculation only once

## What is the impact of this on end-users?
Slightly more loading time/memory usage of multiple components (e.g parsing HTML multiple times)

## List any benchmarks that show the severity of the issue
Gains may be minor, but new approach is following best practices (also discussed on slack with [Expensify team](https://swmansion.slack.com/archives/C05LX9D6E07/p1697319192043789) )

## Proposed solution (if any)
Using initializer function to `useState` calls. That will ensure calculations are run only once.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
It's not optimal to collect those benchmark in this case.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Comment by sebryu** [comment]
Issue created for tracking purposes.
PR already open for review (proposal approved by engineers on slack) : https://github.com/Expensify/App/pull/29630

**Comment by mountiny** [comment]
Adding this to the performance project and assigning myself

**Comment by mountiny** [comment]
PR merged! thanks @sebryu
