### ISSUE TITLE
[$500]  Inconsistency - Emoji suggestions doesn't appear after "@"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698024313967699

## Action Performed:
1. Open any report
2. Type "#:jo" or ":jo" with any special character before ":jo"
3. Observe the suggestions appear
4. Type "@:jo"
5. Observe the suggestions deosn't appear

## Expected Result: 
Suggestion should appear when "@:jo" is typed like any other special character at the start.

## Actual Result: 
Suggestions doesn't appear when "@:jo"  is typed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/0ecffc6d-bbf8-4098-817c-a7e5857a594c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/6470f1ed-6a81-4d5e-85f2-76833d142693

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/b4ffda8a-b55f-4bce-a3f9-3545cc8a0e4a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/edf2e339-24de-49ef-9311-d232c986c9cc

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/be680b08-a4ad-4132-aa83-08f6b80af2fc

https://github.com/Expensify/App/assets/38435837/84a8d9d1-97e1-418e-96bc-09c07535c32e

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/5ee161fe-76ac-4f6b-a457-6ebd2c086768

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132b0a190e276b033</li>
        <li>Upwork Job ID: 1716531713297076224</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
### Proposal from @Krishna2323

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency - Emoji suggestions doesn't appear after "@"

### What is the root cause of that problem?
We haven't added "@" in special chars regex here:
https://github.com/Expensify/App/blob/e73cd31a567c5f026f3a9f1435ecb6f99b2fae82/src/CONST.ts#L1325

### What changes do you think we should make in order to solve the problem?
We just need to add "@" between [] brackets.

Updated Regex: `SPECIAL_CHAR: /[,/?"{}[\]()&^%;`$=#<>!@*]/g`

### Result

**Comment by alitoshmatov** [comment]
I don't think showing emoji suggestion in this situation is a good idea, it will be confusing. Just checked slack and they don't show it too

**Comment by sakluger** [comment]
I agree with @alitoshmatov and think we should treat `@` differently here, since we use the `@` for mentions in NewDot. No other special characters have special uses like that. I'm going to close this one, but thanks for raising for discussion!
