### ISSUE TITLE
[HOLD for payment 2023-11-06] [Performance] Optimize setting initial ref in functional components

### ISSUE THREAD

**Issue by sebryu** [Expensify/App#30208]
## What performance issue do we need to solve?
Setting initial ref in functional components in a way that is running calculation only once

## What is the impact of this on end-users?
Slightly more loading time/memory usage of multiple components

## List any benchmarks that show the severity of the issue
Gains may be minor, but new approach is following best practices (also discussed on slack with [Expensify team](https://swmansion.slack.com/archives/C05LX9D6E07/p1697365027676319) )

## Proposed solution (if any)
Changing not optimal `useRefs` to other hooks (or setting initial value to useRef if applicable).

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
It's not optimal to collect those benchmark in this case.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Comment by sebryu** [comment]
Issue created for tracking purposes.
PR already open for review (proposal approved by engineers on slack) : https://github.com/Expensify/App/pull/29643

**Comment by mountiny** [comment]
We only need to pay $250 to @allroundexperts, there was a regression from the PR

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by trjExpensify** [comment]
Waiting out the regression period still, Melv.

**Comment by mountiny** [comment]
This is ready @allroundexperts can you make a request on NewDot and we can close this one

**Comment by mountiny** [comment]
@allroundexperts have you made the request?

**Comment by JmillsExpensify** [comment]
$250 payment approved for @allroundexperts
