### ISSUE TITLE
[Wave 6: VBA Refactor] useSubStep hook: Used by the main screen to manage the navigation between steps

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30239]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [useSubStep](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.cmqjrf1nnw5q) of the design doc to:

This hook will be used for the main component step to keep track of the current sub-steps.

# Feature Description

At initialization, you pass the list of sub-steps to show, where to start and a callback to know when reaches the last step.

Will return an array with the next item:

-  function `nextStep`, which should check if can move forward or if it was in edit mode go to the last screen (in general will be the confirmation step) 
- function `moveAndEdit`, which will take you to a specific step in edit mode
- the component to render
- the `isEditMode` to enable the edition on that step

**Comment by greg-schroeder** [comment]
This is merged

**Comment by mountiny** [comment]
This is merged, we can track the payments to @shubham1206agra in some tracking issue
