### ISSUE TITLE
[Wave 6: VBA Refactor] ReimbursementAccountPage: Main component to handle the different navigation steps

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30235]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [ReimbursementAccountPage](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.1slwjr85v595) of the design doc to:
- This is the main page where the logic to decide which step to send the user is.

- [ ] Create the Routes
- [x] Connect Bank Account
- [x] Personal Info Step
- [x] Business Info Step
- [x] Onfido Verification Step
- [ ] Beneficial Owner Step

# Manual Test Steps
N/A

# Automated Tests
N/A

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/Expensify/App/issues/30235#issue-1958796858)

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
in progress

**Comment by gedu** [comment]
This issue was mainly created to create a new route path for each step, but we will keep the current pattern and not do a new path per step, I think we can close this issue, @mountiny is it ok?

**Comment by mountiny** [comment]
Yes
