### ISSUE TITLE
[Wave 6: VBA Refactor] InteractiveStepSubHeader: Header showing the current step where the user is at

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30237]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [InteractiveStepSubHeader](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.53e8nk5kb539) of the design doc to:

<img width="395" alt="Screenshot 2023-10-24 at 11 28 50" src="https://github.com/Expensify/App/assets/1676818/cf8c2497-0910-4bf7-b580-2ddf624666cf">

# Feature Description

- Current step
<img width="63" alt="Screenshot 2023-10-24 at 11 39 42" src="https://github.com/Expensify/App/assets/1676818/a4aed8fe-d8d7-4cc7-ac83-60e8c4d9551e">

- Completed step: The user can go back
<img width="49" alt="Screenshot 2023-10-24 at 11 40 48" src="https://github.com/Expensify/App/assets/1676818/f822d437-0c0e-4fd7-a6bb-eaac3a7d57c0">

- Uncompleted step: The user can not move to that step
<img width="58" alt="Screenshot 2023-10-24 at 11 46 37" src="https://github.com/Expensify/App/assets/1676818/331ef119-dddd-40be-98c3-40020b6d7c03">

# Manual Test Steps
- Added into Storybook

**Comment by gedu** [comment]
@mountiny 
I am Edu from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
This was merged to the feature branch
