### ISSUE TITLE
[Wave 6: VBA Refactor] BankInfoScreen: Will highlight the options to connect to a bank

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30244]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [BankInfo](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.ijqwlgvym2s) of the design doc to:

This Screen will show the Plaid and Manually add a bank option, after any of those options is selected, will take the user to the right flow.

# Feature Description

Will use the `useSubStep` Hook to handle the moving between steps

If the user is the first time or wanna start over, will be presented with 2 options, 
- Plaid
- Manually

Selecting Plaid: 
- Will take you to the Plaid flow, using their SDK 

Selecting Manually:
- Will take you to add the Routing and Account numbers

Both will have at the end the Confirmation Screen to make sure everything is ok.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
PR in draft

**Comment by mountiny** [comment]
The PR was merged so we can close this out, the payments will be handled separately than, @shubham1206agra please track them somewhere so we can complete it later on once the project is done. thanks
