### ISSUE TITLE
[$500] Chat - Unable to unfocus the Composer by clicking on the message body

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697868649924679

## Action Performed:
1. Go to any chat when message
2. Click on the composer to focus
3. Click on a message body to unfocus

## Expected Result:
 Able to unfocus the Composer by clicking on the message body

## Actual Result:
Unable to unfocus the Composer by clicking on the message body

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a11a51ec-9ed1-4275-b7a3-8009412c161c

https://github.com/Expensify/App/assets/93399543/ee9beb3b-b905-4b6a-9096-51f65db518f0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/475bc6cc-f3f2-49d5-b6f2-311a323a970a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment]
This is not a bug. It's intentional.

**Comment by shubham1206agra** [comment]
If this is intentional for mobile devices, then same behavior should be there for mweb.
Please someone confirm this.

**Comment by NicMendonca** [comment]
@shubham1206agra do you want to bring up for discussion in Slack? Thanks!
