### ISSUE TITLE
[$500] Distance IOU- Selected suggested address is not shown in address field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30255]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money----Distance
4. Tap start
5. Enter "Chandigarh"
6. Select a suggested address "Chandigarh Airport, Sahibzada Ajit Singh Nagar, Punjab, India"
7. Tap on start

## Expected Result:
The selected suggested address "Chandigarh Airport, Sahibzada Ajit Singh Nagar, Punjab, India" must be shown in the address field
When user taps start again, the full address is displayed in suggested address and it must be shown while user searched also

## Actual Result:
The selected suggested address "Chandigarh Airport, Sahibzada Ajit Singh Nagar, Punjab, India" is not shown in address field. The address "New Civil Air Terminal Chandigarh International Airport, Sahibzada Ajit Singh Nagar, Punjab 140..." is displayed
When user taps start again, the full address is displayed in suggested address but not shown while user searched

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/ef358681-a7d1-44e1-92a9-24d1f80de8dc

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151d4c495c667e327</li>
        <li>Upwork Job ID: 1716820017057878016</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Thanks for that! I've linked this issue in the "Fixed Issues" section of your PR and will close this now.
