### ISSUE TITLE
[Wave 6: VBA Refactor] PersonalInfoPage: Will handle the steps to collect the User information

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30253]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [PersonalInfoPage](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.gf43uvkr94jd) of the design doc to:

Create the 4 sub-steps needed to collect the user information + confirmation screen

# Feature Description

The steps are:
- First and last name step
- Date of Birth
- Enter the SSN
- Address
- Confirmation Step

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by shubham1206agra** [comment]
We need to open another PR here to migrate to RNW v19 here (mainly warning fix and keyboard).
cc @mountiny @MrMuzyk

**Comment by mountiny** [comment]
No problem @MrMuzyk will you handle that PR?

**Comment by MrMuzyk** [comment]
@mountiny Hey, sorry, I haven't seen that ping. I believe it was changed while working on the other tickets. When we have the whole process ready I'll will double check if there is anything left there

**Comment by mountiny** [comment]
@MrMuzyk @gedu What are the next steps on this one?
