### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Chat  - Composer is not focused when message user from Profile page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30254]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to New Dot app
2. Select any chat from LHN or Search
3. Tap on chat header to open user's profile page
4. Tap on Message User

## Expected Result:
Message composer should be focused on the newly opened chat page

## Actual Result:
Composer is not focused when message user from Profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/2901785f-fa71-4b97-82fe-627fb4ab9b3e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d38d60dda089078</li>
        <li>Upwork Job ID: 1716817713447391232</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27541807</li>
<li>tienifr | Contributor | 27541810</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Composer is not focused when message user from Profile page

### What is the root cause of that problem?
There is not any code to support this functional

### What changes do you think we should make in order to solve the problem?
Send one more route param ( autoFocus ) besides "reportID" to the ReportScreen from the  navigateToAndOpenReportWithAccountIDs function . And then pass  this param in props of ReportFooter -> ReportActionCompose  and then call composerRef.focuse() .

### What alternative solutions did you explore? (Optional)
Alternatively we can use event emitter to emit an event from Profile page and in ReportActionCompose component handle this event and again call composerRef.focuse()

**Comment by shahinyan11** [comment]
> Contributor details Your Expensify account email: [shahe.shahinyan@gmail.com](mailto:shahe.shahinyan@gmail.com) Upwork Profile Link: https://www.upwork.com/freelancers/~0165e2bf9704312352
> 
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Chat - Composer is not focused when message user from Profile page
> 
> ### What is the root cause of that problem?
> There is not any code to support this functional
> 
> ### What changes do you think we should make in order to solve the problem?
> Send one more route parameter (e.g `autoFocus` ) besides `reportID` to the `ReportScreen` from the `navigateToAndOpenReportWithAccountIDs` function . And then pass this param in props of `ReportFooter -> ReportActionCompose ` and then call `focus() ` if the `autoFocus` is true.
> 
> ### What alternative solutions did you explore? (Optional)
> Alternatively we can use event emitter to emit an event from `Profile` page and in `ReportActionCompose` component handle this event and again call `focuse()`

I think we need to send the route parameter because as far as I understand it needs to be focused especially in case when we go to the reports `ReportScreen` from the user's profile page by clicking `message <user>` and not always in all cases

**Comment by mallenexpensify** [comment]
@hoangzinh 👀 please on the above proposals thx

**Comment by shahinyan11** [comment]
Contributor details
Your Expensify account email: shahe.shahinyan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0165e2bf9704312352

**Comment by mallenexpensify** [comment]
@Gonals , can you please review the proposal above, thx

**Comment by mallenexpensify** [comment]
👀 please @Gonals , gonna ping you in NewDot too (but... it's Friday late afternoon.....)

**Comment by mallenexpensify** [comment]
Bumping to weekly since @tienifr 's been hired (not sure why it didn't auto-update)

**Comment by mallenexpensify** [comment]
Thanks @hoangzinh , that's what it looks like (strange I didn't know that... or forgot)

**Comment by mallenexpensify** [comment]
Deployed to Staging 11 hours ago

**Comment by mallenexpensify** [comment]
Contributor: @tienifr paid $500 via Upwork
Contributor+: @hoangzinh paid $500 via Upwork

@hoangzinh can you please fill out the BZ checklist above, thx

**Comment by mallenexpensify** [comment]
Thanks @hoangzinh , I think I agree with you, I already started creating a GH so I stated it's likely an edge case but asked for bonus 👀, just in case
https://github.com/Expensify/Expensify/issues/351497
