### ISSUE TITLE
[HOLD for payment 2023-11-02] [HOLD for payment 2023-11-01]  Room - Room name in LHN shows room participants instead of room name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28991

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace and invite a few members to the workspace
3. Go to the #announce room

## Expected Result:
#announce room in LHN shows the room name - #announce

## Actual Result:
#announce room name in LHN shows room participants instead of room name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/d27fdf62-a629-4e92-9ec6-c9e73f2125ef

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment]
This is a regression from https://github.com/Expensify/App/pull/28991. Creating a follow-up PR.

**Comment by MitchExpensify** [comment]
Reminder set to pay on the 2nd

**Comment by MitchExpensify** [comment]
@akinwale is there any payment due here seeing as it was a regression?

**Comment by akinwale** [comment]
> @akinwale is there any payment due here seeing as it was a regression?

No.

**Comment by MitchExpensify** [comment]
Seeing as Applause caught this I assume we don't need new regression tests here, closing!
