### ISSUE TITLE
[HOLD] [ECARD] HIGH: Create "Mark as Done" button for non-refundable Expense reports in NewDot

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#30258]
Coming from [this issue](https://github.com/Expensify/App/issues/28837). 

In the "Mark as Done" case, we'll need more than just a copy change, as we'll need to update the behavior to set the report to "Closed" (Not "Reimbursed") and will need to update NewDot to handle these closed reports correctly (it currently doesn't load them).

Full slack convo [here](https://expensify.slack.com/archives/C057F53HR40/p1698070219954479), but the plan is to:

- Change copy to Mark as done following the design
- When that’s the case, change behavior to call a new ’MarkAsDone” command. Basically Pay elsewhere, but setting the State and Status to 2
- Update Newdot in general to not explode with “Closed” Expense reports
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e6a3dc0eb317b11</li>
        <li>Upwork Job ID: 1716828437684563968</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Gonals</details>

**Comment by alexpensify** [comment]
To confirm, @Gonals are you working on the update and @shubham1206agra would be the reviewer? Thanks for confirming the next steps!

**Comment by Gonals** [comment]
Yep! This goes across our stack, though, so it'll be 3 PR (plus, probably, extras to fix what I forget 😆)

**Comment by Gonals** [comment]
Update:
I'm close to done, but something is broken with Money requests (they are created for twice the amount and the behavior is wonky). 
I'l re-tackle this after I come back from OOO

**Comment by alexpensify** [comment]
I think @Gonals is still OOO

**Comment by Gonals** [comment]
> I think @Gonals is still OOO

Nope! I'm back!

**Comment by alexpensify** [comment]
@dylanexpensify - it looks like @Gonals has everything under control here. Flagging that I will be OOO until Tuesday. If anything is urgent on the BZ side, I maybe need to tap you in for help. Thanks!

**Comment by dylanexpensify** [comment]
You got it @alexpensify! 👀 on it!

**Comment by alexpensify** [comment]
Thank you @dylanexpensify!

**Comment by alexpensify** [comment]
@Gonals any update here?

**Comment by dylanexpensify** [comment]
bump @Gonals

**Comment by Gonals** [comment]
Yep, moving to HOLD. This functionality is likely going to be removed for free plans

**Comment by alexpensify** [comment]
Thanks for the update!

**Comment by kevinksullivan** [comment]
closing in favor of https://github.com/Expensify/Expensify/issues/340874
