### ISSUE TITLE
[$500] The keyboard closes after a moment when tapping back button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** [@makievans](https://github.com/makievans)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698079567043719

## Action Performed:
1. Open the app
2. Open any chat
3. Click the input field to open the keyboard
4. Click the go back arrow
## Expected Result: 
The keyboard should close before going back
## Actual Result: 
The keyboard persists and it closes after going back

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/f9dd2c23-c27f-4e04-8888-7508a85a618d

https://github.com/Expensify/App/assets/38435837/62455a49-7888-4bff-9ac6-6cd0f1855004

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/89e5624b-c4c2-41bf-a001-17258d698223

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/bc814b0a-80f5-4efb-9fd1-bcb87228dbd0

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/f9347d58-cce1-4fa7-a19f-56a02b7a6841

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f12941ee08ff92e</li>
        <li>Upwork Job ID: 1716845606976106496</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by puneetlath** [comment]
What's the story with this issue? Are we going forward?

**Comment by puneetlath** [comment]
Ah ok cool. So this is done and @garrettmknight just needs to pay out, is that right? Asking because we have some other issues blocked on this one.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Bug Report - [@makievans](https://github.com/makievans) - $50 offer sent in Upwork 
Contributor - @tienifr $500, offer sent in Upwork
C+ Review - @allroundexperts $500, please request payment in newdot

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Bug Report - [@makievans](https://github.com/makievans) - $50 payment issued in Upwork
Contributor - @tienifr $500, payment issued in Upwork
C+ Review - @allroundexperts $500, please request payment in newdot

**Comment by laurenreidexpensify** [comment]
@allroundexperts can you please complete checklist / confirm if this requires a regression test thanks

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/28454
2. https://github.com/Expensify/App/pull/28454/files#r1405484233
3. N/A
4. A checklist would be helpful here. The steps mentioned in the OP look simple and clear enough to me!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/30268#issuecomment-1825640958).
