### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Inconsistency in the request money preview text size

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698087869176119

## Action Performed:
1. Open a chat
2. Go to the request money
3. Enter a specific amount and send the request money
4. Click on the requested money
5. Check the preview text size
## Expected Result: 
The request money preview text size should be the same in both the chat and the review sections
## Actual Result: 
There is an inconsistency in the request money preview text size

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/6a595c70-9408-4c4a-9536-aed19774eb92

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/9c127523-8704-4cf5-9500-c0dac67bd9e8

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/a4bc9422-a3ac-40f7-93da-1f66bd48281f

https://github.com/Expensify/App/assets/38435837/3c0981bd-0159-48c6-ab68-0c4f48efa5f7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/e5f86736-305c-4fae-be26-f88c3e603800

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/cf339ede-83d4-41f5-901c-28cfc1a2fdea

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/f2b17973-f01a-4872-8773-efd2c5a994d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a260f6acb4caa392</li>
        <li>Upwork Job ID: 1716855328239075328</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27543446</li>
<li>dukenv0307 | Contributor | 27543447</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency in the request money preview text size
### What is the root cause of that problem?
We have different style between two.
https://github.com/Expensify/App/blob/f8fc21d373be18e645f4d93099256721914c16f5/src/components/ReportActionItem/ReportPreview.js#L221
https://github.com/Expensify/App/blob/f8fc21d373be18e645f4d93099256721914c16f5/src/components/ReportActionItem/MoneyRequestPreview.js#L277-L279
### What changes do you think we should make in order to solve the problem?
We can make 2 styles as same.
### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment]
I agree, these should be consistent. @JmillsExpensify @trjExpensify is this a regression from somewhere?

**Comment by shawnborton** [comment]
I think the preview card should have a consistent max-width (so they all look the same width on desktop), but it's okay if it goes 100% width on smaller screens

**Comment by shawnborton** [comment]
Interesting, I don't know how we ended up with a responsive text size like that but I think we should revert that to stay static. I guess the idea might have been to make the text dynamically smaller in case there were a lot of avatars? @youssef-lr any ideas here?

**Comment by youssef-lr** [comment]
@shawnborton looks like this change came from this [PR](https://github.com/Expensify/App/pull/26280) to fix the large amounts being cut off in the split preview..

**Comment by trjExpensify** [comment]
I think they should all be consistent, personally.

**Comment by dubielzyk-expensify** [comment]
Covering for Shawn while he's OOO: Agree that they should all be consistent. If the numbers can't fit, we should shrink to make them fit (but also this is quite rare), but otherwise keep the same static size.

**Comment by wlegolas** [comment]
Hi @fedirjh, after the discussion, my solution is the same one that @dukenv0307 proposed, as @dukenv0307 already has a proposal, I think there is no reason to update mine.

**Comment by yh-0218** [comment]
hi, @fedirjh I just update [proposal](https://github.com/Expensify/App/issues/30275#issuecomment-1777685280)

**Comment by youssef-lr** [comment]
Would love to have @shawnborton and @trjExpensify on the proposed solution

> I think this challenging, but we can make it as follows:
> 
> Set a static font size for all money previews.
> For split preview, we can implement the following changes:
> The size of the split preview should be determined based on the length of the text.
> By default, it should have the same size as the other money previews.
> If the amount length is too big, then we can make the split preview size adjustable.

**Comment by dubielzyk-expensify** [comment]
Shawn in OOO for a bit longer, but I'd say [that proposed solution](https://github.com/Expensify/App/issues/30275#issuecomment-1790942970) is great. That way most people get the same size and experience, but if the number is too large, we adjust. Good stuff!

**Comment by lschurr** [comment]
Alrighty, I've assigned @dukenv0307

**Comment by lschurr** [comment]
@fedirjh could you work through the checklist for this one?

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: @ayazalavi $50
- Contributor: @dukenv0307 $500
- Contributor+: @fedirjh $500

**Comment by lschurr** [comment]
@ayazalavi could you apply to the job in Upwork? https://www.upwork.com/jobs/~01a260f6acb4caa392

**Comment by ayazhussain79** [comment]
@lschurr You've mentioned the wrong person. I've applied on Upwork. Thank you.

**Comment by lschurr** [comment]
Sorry about that! GH auto-populated. Thanks!

**Comment by lschurr** [comment]
Updated the payment summary with the correct GH handle.

**Comment by ayazhussain79** [comment]
Offer accept, Thank you
