### ISSUE TITLE
LHN - Avatar for 1:1 DM report disappears from requestee view when IOU request is received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29101
## Action Performed:
1. Go to staging.new.expensify.com
2. User A sends a few messages to User B.
3. User B opens chat report with User A.
4. User A creates a money request in 1:1 DM with User B

## Expected Result:
The avatar for 1:1 DM report will not disappear from User B's view

## Actual Result:
The avatar for 1:1 DM report disappears from User B's view for a moment when the IOU request is received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/cb0122ff-5da6-4b7d-a22d-1458e19bd45c

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012491fd05ba5481ac</li>
        <li>Upwork Job ID: 1716993014805659648</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
This is a deploy blocker for Web-Expensify but not App cc @deetergp

**Comment by marcaaron** [comment]
Not an App issue so gonna unassign @narefyev91

**Comment by marcaaron** [comment]
This should be fixed now.
