### ISSUE TITLE
[$500] Chat - "Copy To Clipboard show "requested" for split action."

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698130953409749

## Action Performed:
1. Try to split with 3,4 users.
2. Hover on that split action, click copy to clipboard.
3. Paste the text to browser.
4. The text shows "Requested...." instead of "Split...."

## Expected Result:
The clipboard text should be "split ...." instead of "requested..."

## Actual Result:
 The clipboard text shows "requested..." for split action.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/456635d6-6db5-496f-a97b-5b5aa1e12d08

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/b49db4be-84b2-44dc-8367-62ac5974ac32

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/93399543/3d6757f4-3dea-4318-9de5-fd24716bed98

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/4c2ada02-f110-4ac9-8e19-2a4f1e4b90fb

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3236e966-8c96-4648-b606-c7d27d510631

https://github.com/Expensify/App/assets/93399543/c264b1bd-db69-4a96-b41a-814c5c09a4fb

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/555ed4ae-e085-4b54-85a1-7d951fb16630

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f01b7930e0979a6</li>
        <li>Upwork Job ID: 1716869694506221568</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy To Clipboard show "requested" for instead of "Split" for split action.
### What is the root cause of that problem?
When getting message of MoneyRequestAction, we didn't have a check for split action here, so even it's split action, it still showed the `requested amount`  text.
https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/libs/ReportUtils.js#L4058-L4061
### What changes do you think we should make in order to solve the problem?
Add a second param called `isSplitAction` for `getIOUReportActionDisplayMessage`.
Add a check in [here](https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/libs/ReportUtils.js#L4058-L4061) if it's split action we should use `split` text instead.

```javascript
 displayMessage = Localize.translateLocal(isSplitAction ? 'iou.didSplitAmount' : 'iou.requestedAmount', {
            formattedAmount,
            comment,
        });

```

Also add the second params of `getIOUReportActionDisplayMessage` inside `onPress` of report action menu:
```javascript
const displayMessage = ReportUtils.getIOUReportActionDisplayMessage(reportAction, ReportActionsUtils.isSplitBillAction(reportAction));
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by hungvu193** [comment]
> Proposal by: @hungvu193 Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1698130953409749
> 
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Copy To Clipboard show "requested" for instead of "Split" for split action.
> 
> ### What is the root cause of that problem?
> When getting message of MoneyRequestAction, we didn't have a check for split action here, so even it's split action, it still showed the `requested amount` text.
> 
> https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/libs/ReportUtils.js#L4058-L4061
> 
> ### What changes do you think we should make in order to solve the problem?
> Add a second param called `isSplitAction` for `getIOUReportActionDisplayMessage`. Add a check in [here](https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/libs/ReportUtils.js#L4058-L4061) if it's split action we should use `split` text instead.
> 
> ```js
>  displayMessage = Localize.translateLocal(isSplitAction ? 'iou.didSplitAmount' : 'iou.requestedAmount', {
>             formattedAmount,
>             comment,
>         });
> ```
> 
> Also add the second params of `getIOUReportActionDisplayMessage` inside `onPress` of report action menu:
> 
> ```js
> const displayMessage = ReportUtils.getIOUReportActionDisplayMessage(reportAction, ReportActionsUtils.isSplitBillAction(reportAction));
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> N/A

**Comment by sophiepintoraetz** [comment]
Just waiting on @ntdiary to review the proposals!

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - "Copy To Clipboard show "requested" for split action."

### What is the root cause of that problem?
- Currently, with money request action, we always display it as below:
https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/ReportUtils.js#L4067-L4070
without checking if it split or not.
### What changes do you think we should make in order to solve the problem?
- Just need to update the above to
```
   const isSplitBillAction = ReportActionsUtils.isSplitBillAction(reportAction)
            displayMessage = Localize.translateLocal(isSplitBillAction ? 'iou.didSplitAmount': 'iou.requestedAmount', {
                formattedAmount,
                comment,
            });
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by hungvu193** [comment]
> This issue is simple and straightforward, @hungvu193 has already pointed out the RC (`translationKey` matches incorrectly.).
> 
> Personally, I don't feel whether to add the param or not is a very important improvement.
> 
> https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/libs/ReportUtils.js#L4049
> 
> 
> Also, we can promote the `translationKey` variable, then use
> ```js
> translationKey = ReportActionsUtils.isSplitBillAction(reportAction) ? 'iou.didSplitAmount' : 'iou.requestedAmount';
> ```
> 
> If @hungvu193 doesn't have other reasons to add the parameter (`isSplitAction`), we can assign this issue to them, then they can raise a PR in the way I described above.
> 
> 🎀 👀 🎀 C+ reviewed

Yeah, agree. Thanks for pointing that out 😄

**Comment by DylanDylann** [comment]
@ntdiary  my proposal is very simple and does not use the additional param. Please help take a look with it. Thanks

**Comment by DylanDylann** [comment]
Many thanks !, @ntdiary

**Comment by sophiepintoraetz** [comment]
Waiting on a review from @deetergp on @DylanDylann's [proposal](https://github.com/Expensify/App/issues/30286#issuecomment-1782310258)

**Comment by deetergp** [comment]
Oh, are engineers not assigning contributors anymore? I agree with @ntdiary that @hungvu193's proposal sounds good.

**Comment by sophiepintoraetz** [comment]
@deetergp - hmm, I think you're good - something might not have worked though from this pR https://github.com/Expensify/Web-Expensify/pull/39434

**Comment by DylanDylann** [comment]
@deetergp please help check my comment here https://github.com/Expensify/App/issues/30286#issuecomment-1782313135

**Comment by DylanDylann** [comment]
@ntdiary Thanks for your information

**Comment by hungvu193** [comment]
I think this issue is ready for payment @sophiepintoraetz

**Comment by hungvu193** [comment]
Bump for the payment @sophiepintoraetz

**Comment by sophiepintoraetz** [comment]
hmmm @hungvu193?
<img width="1494" alt="image" src="https://github.com/Expensify/App/assets/42940078/0e02e0bf-5e45-48ba-92f2-a7912512a531">

**Comment by sophiepintoraetz** [comment]
Yeah, it's likely to be Upwork but here's the job if you want to try to apply that way? https://www.upwork.com/jobs/~01d0017ef3939cb736

**Comment by hungvu193** [comment]
> Yeah, it's likely to be Upwork but here's the job if you want to try to apply that way? https://www.upwork.com/jobs/~01d0017ef3939cb736

Cool. I've just applied!

**Comment by sophiepintoraetz** [comment]
Lol, I just managed to get an offer to you - I hate upwork

**Comment by sophiepintoraetz** [comment]
Offers out!

**Comment by hungvu193** [comment]
Thank you Sophie 💪
