### ISSUE TITLE
[$500] Receipt - The border green line on top and bottom is shown in mweb but not displayed in android.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money-----manual
4. Enter an amount
5. Tap next
6. Select any user
7. Tap 3 dots on top right to select "add receipt"
8. Note the border green line on top and bottom as border in Receipt page
9. Launch app
10. Repeat step 2 to step 7
11. Note no green border in top and bottom in Receipt page

## Expected Result:
In receipt page, the border green line on top and bottom is shown in mweb but not displayed in android. The behavior must not be inconsistent in mweb and android.

## Actual Result:
In receipt page, the border green line on top and bottom is shown in mweb but not displayed in android. The behavior is inconsistent in mweb and android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/ff9c1770-1a38-43fe-a43c-54033b43a711

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01181ed80e74e0488e</li>
        <li>Upwork Job ID: 1716867465539047424</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27440828</li>
<li>Krishna2323 | Contributor | 27440830</li>
</ul></li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Hey @situchan, can you please review the proposal above? Thanks!

**Comment by situchan** [comment]
@neonbhai can you please share screenshot on android/ios/mWeb?

**Comment by isabelastisser** [comment]
Bump @situchan. Thanks!

**Comment by situchan** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/30284#issuecomment-1783868531) looks good to me.
I tested @neonbhai's solution but bottom border radius didn't work
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
@Julesssss sorry but I think we should open this back to proposals because accepted solution doesn't work on iOS.
The contributor **must** have iPhone on which newDot dev app is installable because camera doesn't work on simulator.

**Comment by situchan** [comment]
cc: @allroundexperts if you're interested

**Comment by situchan** [comment]
@Krishna2323 sure, we can wait until next Monday

**Comment by situchan** [comment]
This is ready for payment. PR deployed to production on Nov 21 - https://github.com/Expensify/App/pull/31519#issuecomment-1821921240

**Comment by situchan** [comment]
This was not a regression but design inconsistency.
This was reported by QA team so I don't think we need regression test.

**Comment by isabelastisser** [comment]
Offers sent in Upwork. All set!
