### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] [Wave 6: Referral Program] Promote referral program messaging in NewDot Settings > Share code

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#30283]
## Background
We're finding creative ways to inject referral program copy into NewDot flows, and agreed on (a version of) [this idea](https://expensify.slack.com/archives/C02MW39LT9N/p1698102583204449?thread_ts=1697748137.206079&cid=C02MW39LT9N) as a good one to pursue. This is in preparation for the upcoming earnings call in November where it'll be a part of what we showcase. 

## What to add and where to add it
- [ ] In Settings > Share code > under the QR code and just above "Copy URL to clipboard," we want it to say "Get $250"
- [ ] When clicked, it should bring up a modal with the following text:

**ENGLISH**
> **Get $250 for every referral**
> If you know anyone who’s spending too much time on expenses (literally anyone – your neighbor, your boss, your friend in accounting), send them your Expensify referral link:
> 
> [Copy referral link]
> 
> When they start an annual subscription, you’ll get **$250**. Easy as that.
> 
> [Learn more](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program#gsc.tab=0)

-----

**SPANISH**

> **Recibe $250 por cada recomendación**
> Si conoces a alguien que dedique demasiado tiempo a los gastos (literalmente cualquiera: tu vecino, tu jefe, tu amigo de contabilidad), envíale tu enlace de invitación de Expensify:
>
> [Copiar enlace de invitación]
>
> Cuando comiencen una suscripción anual, obtendrás $250. Así de fácil.
>
> Aprende más

## What it should look like
**Screen 1**
<img width="311" alt="image" src="https://github.com/Expensify/App/assets/22160301/a7523115-1d97-41a8-abd4-e2a98237ef7d">

**Screen 2**
<img width="324" alt="image" src="https://github.com/Expensify/App/assets/22160301/a1289d08-60c4-43ef-9fe5-4df602ce6cef">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8b6bf76bcc6fd5d</li>
        <li>Upwork Job ID: 1717291493509500928</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@jamesdeanexpensify we could have an external contributor take this one. You could post in #wave6 to see if someone wants it. Maybe it makes sense for @waterim to take after his current one.

**Comment by jamesdeanexpensify** [comment]
Posted [here](https://expensify.slack.com/archives/C02MW39LT9N/p1698254703384809).

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by waterim** [comment]
Do we need to start it concurrently with my issue?
Cause Im doing exact same page for showing a message

**Comment by rezkiy37** [comment]
No update.

**Comment by rezkiy37** [comment]
No pudate.

**Comment by rezkiy37** [comment]
Waiting on this PR - https://github.com/Expensify/App/pull/30372.

**Comment by jamesdeanexpensify** [comment]
OK so coming back to this, there have been a lot of copy and formatting updates that I've consolidated into the top comment [here](https://github.com/Expensify/App/issues/29881#issue-1950214951) to make sure everything is accurate. Let me know what questions you still have, please!

**Comment by rezkiy37** [comment]
Still waiting on this PR - https://github.com/Expensify/App/pull/30372.

**Comment by rezkiy37** [comment]
Still waiting on this PR - https://github.com/Expensify/App/pull/30372.

**Comment by rezkiy37** [comment]
No updates.

**Comment by rezkiy37** [comment]
@jamesdeanexpensify, could you please provide me strings in Spanish?

**Comment by rezkiy37** [comment]
Also, please confirm that the attached design is still relevant.

**Comment by rezkiy37** [comment]
https://github.com/Expensify/App/assets/57314631/7b21357d-dffe-4583-839c-a891175b9e91

**Comment by jamesdeanexpensify** [comment]
Yep, I like the design. I'll get Spanish translations now!

**Comment by jamesdeanexpensify** [comment]
Spanish translation check in progress [here](https://expensify.slack.com/archives/C21FRDWCV/p1700273177882679).

**Comment by rezkiy37** [comment]
Okay. So please let me know when it is done, because I cannot open the link.

<img width="608" alt="Screenshot 2023-11-18 at 13 23 08" src="https://github.com/Expensify/App/assets/57314631/2ec8ee9f-449f-4b4c-849d-ed70e8c2fc5e">

**Comment by rezkiy37** [comment]
Sorry, forgot about translations. Still a draft.

**Comment by jamesdeanexpensify** [comment]
Spanish translation added into the top comment above!

**Comment by rezkiy37** [comment]
Added: https://github.com/Expensify/App/pull/30436#issuecomment-1819612288.

**Comment by puneetlath** [comment]
@hoangzinh offer here: https://www.upwork.com/nx/wm/offer/27953826

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
