### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Android - IOU-In a address, one word in Hindi and other text in English are shown.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30298]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab---request money--Distance
3. Tap start
4. Enter Chandigarh railway
5. Select suggested address "Chandigarh Railway Station Ticket Counter, Gali Number 2, Daria, Chandigarh, India"
6. Tap Start

## Expected Result:
The address in address field and suggested addresses with text in Hindi language must not be shown.The entire address must only be in English language. In a address, one word in Hindi and other text in English must not be shown

## Actual Result:
The address in address field and suggested addresses showing address with text in Hindi language. In a address, one word in Hindi and other text in English are shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/b4cb5f04-7d37-42f3-947f-e0a7dcc0c6e0

![Bug6249418_1698181740250!Screenshot_2023-10-25-02-38-14-262_com Slack-edit](https://github.com/Expensify/App/assets/78819774/a53805bb-966b-4c75-9a2b-ff655b6a28d4)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ca2087437191a6c</li>
        <li>Upwork Job ID: 1716936389696782336</li>
        <li>Last Price Increase: 2023-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27999208</li>
<li>tienifr | Contributor | 27999210</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Waiting for proposals

**Comment by esh-g** [comment]
Will be changed here: https://github.com/Expensify/App/pull/29931

**Comment by JmillsExpensify** [comment]
@0xmiroslav thoughts on the proposal above?

**Comment by esh-g** [comment]
@0xmiroslav I just added it as a a heads up that it may 'change' the behaviour here I didn't say it would get fixed...

**Comment by JmillsExpensify** [comment]
Still waiting on proposals

**Comment by JmillsExpensify** [comment]
I think we're still waiting for proposal feedback, is that right?

**Comment by JmillsExpensify** [comment]
Thanks!

**Comment by amyevans** [comment]
Makes sense to me 👍

**Comment by JmillsExpensify** [comment]
PR still in review

**Comment by JmillsExpensify** [comment]
Thanks for that @0xmiroslav. Adding a payment summary and issuing payments via Upwork:

 - Issuer reporter: QA
 - Contributor: @tienifr $500
 - Contributor+: @0xmiroslav $500

**Comment by JmillsExpensify** [comment]
All contracts paid out. Closing!
