### ISSUE TITLE
[Wave 6: Referral Program] Promote referral program messaging in the NewDot Left-Hand Bar (LHB)

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#30294]
## Background
We're finding creative ways to inject referral program copy into NewDot flows, and agreed on [this idea](https://expensify.slack.com/archives/C02MW39LT9N/p1698175480327949?thread_ts=1697748137.206079&cid=C02MW39LT9N) as a good one to pursue. This is in preparation for the upcoming earnings call in November where it'll be a part of what we showcase. 

## What to add and where to add it
- [ ] In the Left-Hand Bar (LHB), add "Get $250"
- [ ] When clicked, it should bring up the same modal suggested [here](https://github.com/Expensify/App/issues/30283#issue-1959724680).

## What it should look like
Here's where we want to add "Get $250":
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/22160301/2b37fe62-c4de-487e-94d5-0a59fe9b4063">

**Comment by puneetlath** [comment]
@jamesdeanexpensify we could have an external contributor take this one. You could post in #wave6 to see if someone wants it. Maybe it makes sense for @waterim to take after his current one.

**Comment by esh-g** [comment]
@puneetlath @jamesdeanexpensify Could this be opened to non-agency contributors as well? I would love to draft a proposal for this, if I could access the the modal design (can't access it because the image is an internal link currently)

**Comment by jamesdeanexpensify** [comment]
Just a note that I still have this in "Planning" for now because we're working on putting this through our #whatsnext process. @puneetlath [here's](https://expensify.slack.com/archives/C02MW39LT9N/p1698181820375419?thread_ts=1697748137.206079&cid=C02MW39LT9N) a reference for you to check out.

**Comment by jamesdeanexpensify** [comment]
Posted in #whatsnext [here](https://expensify.slack.com/archives/CC7NECV4L/p1698257392152459).

**Comment by jamesdeanexpensify** [comment]
Closing this one out per the discussion linked above.
