### ISSUE TITLE
[$500] [Wave 6: Tags] IOU Report - Auto-tagging is not working

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create an account in OldDot (OD) that will act as the workspace admin
2. With the admin in OD:
    3. Create a collect policy and enable workspace expense chats on it (see https://github.com/Expensify/App/issues/30291#issuecomment-1789854294)
    4. Create a custom tag "Test tag"
    5. Invite another account as employee to the policy
1. As the employee, login to staging OD.
6. Navigate to Account Settings > Expense Rules.
7. Create a new expense rule, if the Expense merchant name is "Test" the tag should be "Test Tag".
8. As the employee, login to staging ND.
9. Click on the "+" button.
10. Select "Request Money".
11. Create a money request where the name of the merchant is "Test", select the same collect workspace.
12. Go to the IOU details report.

## Expected Result:
The tag of the IOU should be auto-tagged as "Test Tag"

## Actual Result:
The IOU has no tag

## Workaround:
Unknown1

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/75e65cef-265d-4e6e-803e-7e37f05c4832

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d09daeb9a0bf9e58</li>
        <li>Upwork Job ID: 1716915293840683008</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by jaymerut** [comment]
### **Proposal**
### Please re-state the problem that we are trying to solve in this issue.
The IOU report isn't getting autotagged

### What is the root cause of that problem?
The root of the problem is that `IOU.resetMoneyRequestTag()` gets called everytime after we navigate backwards from the MoneyRequestTagPage

<img width="517" alt="image" src="https://github.com/Expensify/App/assets/36806191/4fc145cb-95b4-4fe9-8aa3-f2794d24fef2">

<img width="330" alt="image" src="https://github.com/Expensify/App/assets/36806191/84207f09-7353-430e-8418-b9621c94ea9c">

### What changes do you think we should make in order to solve the problem?
We should check if `reportID.current` is empty before resetting the values on every render so that we don't clear it unintentionally.

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
@hoangzinh one proposal to review

**Comment by adelekennedy** [comment]
@MelvinBot chill it was the weekend

**Comment by Victor-Nyagudi** [comment]
I would also like to know the answer to the above. 

I don't see the workspace in the LHN.

**Comment by lanitochka17** [comment]
@jaymerut Hello 
Here are the instructions: https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?pli=1&authuser=3

![image](https://github.com/Expensify/App/assets/78819774/ed104fef-ef6d-4c79-805c-0da85c9402af)

![image](https://github.com/Expensify/App/assets/78819774/4687814e-545a-4907-8478-97366634ff2e)

**Comment by adelekennedy** [comment]
@hoangzinh you think we should make this internal?

**Comment by adelekennedy** [comment]
@aldo-expensify for feedback

**Comment by greg-schroeder** [comment]
Bump @aldo-expensify this one is `Critical`

**Comment by aldo-expensify** [comment]
Sorry, was OOO yesterday, Investigating this now...

**Comment by aldo-expensify** [comment]
There is something I'm missing to reproduce this. In step 7, when it says: "select the same collect workspace.", I don't see anywhere where I can select a workspace.

**Comment by aldo-expensify** [comment]
I found my answer here: https://github.com/Expensify/App/issues/30291#issuecomment-1789854294
I'll update the testing steps to show this

**Comment by aldo-expensify** [comment]
PR up: https://github.com/Expensify/Web-Expensify/pull/39702

**Comment by aldo-expensify** [comment]
PR is in staging

**Comment by aldo-expensify** [comment]
@adelekennedy I think we need to handle payment if there is anyone to pay, otherwise we can close

**Comment by adelekennedy** [comment]
@hoangzinh - though you didn't review the internal PR for this one we appreciate the work you put in reviewing proposals and guiding this issue along

**Payouts due:**
Contributor+: $100 @hoangzinh 
Upwork job is [here](https://www.upwork.com/jobs/~01bc276845f34d36ac).
