### ISSUE TITLE
[HOLD for payment 2023-12-08] [HOLD for payment 2023-12-06] [$125] [Form Provider Refactor] IdologyQuestions

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30313]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/EnablePayments/IdologyQuestions.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e0b2b5e81ad4761</li>
        <li>Upwork Job ID: 1716963167990067200</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@cdOut will you be working on this issue too?

**Comment by cdOut** [comment]
@luacmartins yes, I will be working on this issue.

**Comment by s77rt** [comment]
Not overdue. @cdOut Will work on this

**Comment by sonialiap** [comment]
@cdOut any updates? :)

**Comment by cdOut** [comment]
I will put up a draft PR soon, was working on the form refactor with Kamil but since he's OOO now I took all of the task so the work might be a little slower

**Comment by s77rt** [comment]
Not overdue. @cdOut is still working on this

**Comment by luacmartins** [comment]
We're still working on this

**Comment by kowczarz** [comment]
Hello, I'm back from OOO and I will help @cdOut with that task

**Comment by s77rt** [comment]
@kowczarz Any updates?

**Comment by s77rt** [comment]
Still working on it

**Comment by s77rt** [comment]
Ignore above message ^ The linked PR is not merged yet. It's fixing the deploy blocker not causing it.

**Comment by s77rt** [comment]
Checklist ^ not due yet. PR is reverted.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: n/a Not a bug but a code refactor
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: n/a

**Comment by sonialiap** [comment]
@s77rt $125 - offer sent

[New upwork post](https://www.upwork.com/jobs/~012dcaf1a673eaac6a)

**Comment by s77rt** [comment]
Accepted! Please note that the payment due here is $62.5 (since there was a regression)

**Comment by sonialiap** [comment]
@s77rt thanks for the correction. $62.50 has been paid out to you
