### ISSUE TITLE
[HOLD for payment 2023-12-04] [HOLD for payment 2023-11-29] [$125] [Form Provider Refactor] BankAccountManualStep

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30316]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/ReimbursementAccount/BankAccountManualStep.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d24f22fcaf598dd6</li>
        <li>Upwork Job ID: 1716963666355748865</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@cdOut will you be working on this issue too?

**Comment by cdOut** [comment]
@luacmartins yes, I will be working on this issue.

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by mananjadhav** [comment]
@luacmartins Does this need C+ review? I can see the PR is in draft since a few days.

**Comment by luacmartins** [comment]
Yes please! We're still working through other migration PRs, but we'll need C+ review once the PR is ready!

**Comment by greg-schroeder** [comment]
Work continues on linked PR

**Comment by cdOut** [comment]
This is pretty much finished, currently waiting for review.

**Comment by greg-schroeder** [comment]
@mananjadhav you're free to make a manual request for $125 in NewDot for the reviewer role to be paid out 11/29

**Comment by mananjadhav** [comment]
@luacmartins I didn't realize until today that the price was set to $125. Can we please up the price to normal payout? It wasn't a drop-in replacement, had to review the draftValues logic as well.

**Comment by luacmartins** [comment]
@mananjadhav thanks for raising this. I understand that not issues are made equal and this one involved more than just a simple drop-in replacement, but we decided to price these at $125 regardless of the level of involvement needed. I hope that you understand that.

**Comment by mananjadhav** [comment]
Okay thanks for clarifying.

**Comment by JmillsExpensify** [comment]
$125 payment approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/30316#issuecomment-1826884929).
