### ISSUE TITLE
[HOLD for payment 2023-11-29] [$125] [Form Provider Refactor] AdditionalDetailsStep

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30311]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/EnablePayments/AdditionalDetailsStep.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152d37170bf8aab5d</li>
        <li>Upwork Job ID: 1716962802055196672</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cdOut</details>

**Comment by cdOut** [comment]
@luacmartins yes, I will be working on this issue.

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task.

**Comment by alexpensify** [comment]
Thank you for these updates!

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by luacmartins** [comment]
Same as above

**Comment by alexpensify** [comment]
Daily Update: The PR is still in draft mode.

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by cubuspl42** [comment]
FFR, [this is the mentioned PR](https://github.com/Expensify/App/pull/30568)

**Comment by alexpensify** [comment]
Thanks @cdOut for the update!

**Comment by cdOut** [comment]
Still working on it, this along with another issue is intertwined and I have to fix issues with both before proceeding further with it, it should be this week

**Comment by alexpensify** [comment]
Daily Update: The PR is under review!

**Comment by alexpensify** [comment]
Looks like the PR has been merged, so now we wait for automation.

**Comment by alexpensify** [comment]
@cubuspl42 - to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @cdOut payment handled via vendor 
-  Contributor+ that helped on the issue and/or PR - @cubuspl42 

Upwork Job: https://www.upwork.com/jobs/~01af73ad283fbbe4ff

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: Payment was updated here - https://github.com/Expensify/App/issues/30311#issuecomment-1781498690

--- 

@cubuspl42 - I've sent an offer in Upwork, please accept and I can complete the payment process there. Thanks!

**Comment by cubuspl42** [comment]
@alexpensify Done

**Comment by alexpensify** [comment]
Awesome-- I've completed the payment process in Upwork.
