### ISSUE TITLE
IUO- Email contains a colon between the user and the amount.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Request money to an account that you have access to the email inbox

## Expected Result:
Verify a email is received with the subject IOU
Verify the email contains the details of the IOU in the following format "[user] requested [amount]" (should not include a colon between the user an amount)

## Actual Result:
The email contains the details of the IOU in the following format "[user] requested [amount]" with include a colon between the user an amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Bug6250229_1698238493068!Screenshot_2023-10-24_at_12 21 30_PM](https://github.com/Expensify/App/assets/78819774/0e099747-6868-40e2-8d17-e4e9cd0285ae)

Production 

![viber_image_2023-10-25_10-24-29-151](https://github.com/Expensify/App/assets/78819774/1578b5ad-a6f2-4316-8e27-ac3d08e77ed7)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Li357** [comment]
Looks like a backend issue. Taking a look

**Comment by Li357** [comment]
This is an intended change to our IOU report notification system. Leaving these here as reference: https://github.com/Expensify/Web-Expensify/pull/39124 and https://github.com/Expensify/Expensify/issues/313899
