### ISSUE TITLE
Benchmark: End-to-End Encryption Library

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#30341]
Coming on the heels of: https://github.com/Expensify/App/issues/21144 cc: @roryabraham @chrispader 

Now for the fun part! Using the new library, could we perform a quick benchmark of average times of the functionality running in the App (on a various Mobile hardware if that's available).

- Generating a RSA/Kyber keypair for a user
- Generating (Kyber) the AES shared key to encrypt a message
- AES encryption of a typical message, say of 255 characters
- Decryption (RSA) and Derivation (Kyber) to get the shared AES key
- AES decryption of the above typical message

Any other timings that would be useful! 😄 

After that we can explore a quick in-UI MVP, but we'll draft up the details for that after we get some numbers 🙌

**Comment by chrispader** [comment]
I have to comment so you can assign me :)

**Comment by chrispader** [comment]
Just finished the fist round of benchmarks and gave an update [in this comment](https://github.com/Expensify/App/pull/30523#issuecomment-1798482810)

cc @robertjchen @roryabraham

**Comment by robertjchen** [comment]
perfect, thanks!! Can't wait to see how those figures look on actual hardware ✨

**Comment by robertjchen** [comment]
We got the numbers, closing this out for now!
