### ISSUE TITLE
[HOLD for #29428] - [$500] Login - Settings page has no skeleton placeholder when the page is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Log in with a high traffic account
3. When the page is loading, open Settings

## Expected Result:
Settings page has skeleton placeholder when the page is loading

## Actual Result:
Settings page has no skeleton placeholder when the page is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/5b224d09-0893-4e8d-ac1e-2d25b525d897

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc78993cd9ce2750</li>
        <li>Upwork Job ID: 1717214985723400192</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27699378</li>
</ul></li>
    </ul>
</details>

**Comment by robertKozik** [comment]
Yeah I confirm, it should be resolved by the linked PR. Maybe we can put this issue on hod until the PR will be merged? After that we can retest this scenario to be sure it's fixed

**Comment by CortneyOfstad** [comment]
Sounds good! Updating the title now 👍

**Comment by CortneyOfstad** [comment]
@thesahindia looks like the PR was closed — can you confirm if anything else is needed here? Thanks!

**Comment by CortneyOfstad** [comment]
@thesahindia any update on the PR above? Thanks!

**Comment by CortneyOfstad** [comment]
Sorry for missing this! @thesahindia in the future, please make sure to remove the "Reviewing" label and add the "awaiting payment" labels, as this will trigger the payment process to begin 👍

**Comment by situchan** [comment]
> Sorry for missing this! @thesahindia in the future, please make sure to remove the "Reviewing" label and add the "awaiting payment" labels, as this will trigger the payment process to begin 👍

FYI: C+ team doesn't have permission to add/remove labels. It should be done by BZ or engineer

**Comment by CortneyOfstad** [comment]
Weird, I was under the impression they could — odd. But thanks for the heads up!

@bernhardoj I've sent you an offer in Upwork as the previous one expired. Please let me know as soon as that is accepted and I can get that paid to you ASAP 👍

**Comment by CortneyOfstad** [comment]
## Payment Summary

@thesahindia to be paid $500 via NewDot
@bernhardoj was paid $500 via Upwork

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on comment above.
