### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02] Request Money- Unable to cature image with camera button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app and login
2. Tap the green fab > Request money > Scan
3. Tap the camera button to capture image

## Expected Result:
Image captured by tapping the green camera button

## Actual Result:
Button non functional and Camera error message displayed on native apps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Bug6250651_1698256015501!IMG_7714](https://github.com/Expensify/App/assets/78819774/18565db4-8250-4c4f-829e-a0e95bc5d7d3)

https://github.com/Expensify/App/assets/78819774/e728f555-29d1-4c6c-8995-336457dc93e1

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
@ishpaul777 it's [intentional](https://expensify.slack.com/archives/C01GTK53T8Q/p1695110739750909) to use new `forwardRef` pattern introduced in https://github.com/Expensify/App/pull/28411.
This should be correct change:

<img width="1381" alt="Screenshot 2023-10-26 at 1 24 10 AM" src="https://github.com/Expensify/App/assets/108292595/5aaa1e00-339a-4b92-84a5-c4897126a3ba">

**Comment by situchan** [comment]
Ah, I see that option 1 is what I suggested

**Comment by amyevans** [comment]
Thanks for the RCA @ishpaul777! @roryabraham do you have a preference whether we revert https://github.com/Expensify/App/pull/28813, or cherry pick a fix? (Either from @ikevin127 if available, or @ishpaul777). cc @mananjadhav as well

**Comment by ikevin127** [comment]
Indeed I introduced this regression and I am creating a PR  to fix it as we speak.

**Comment by amyevans** [comment]
Thanks!

**Comment by ikevin127** [comment]
Created PR https://github.com/Expensify/App/pull/30397

**Comment by marcaaron** [comment]
This should be resolved now.

**Comment by ikevin127** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> - [ ] [@amyevans / @roryabraham] The PR that introduced the bug has been identified. Link to the PR:
> - [ ] [@amyevans / @roryabraham] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> - [ ] [@amyevans / @roryabraham] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> - [x] [@ikevin127] Determine if we should create a regression test for this bug.
> - [x] [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> - [ ] [@NicMendonca] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:


No need for any regression tests here.

**Comment by roryabraham** [comment]
Oh, whoops I spoke too soon, this was a regression so no separate payment should be issued for the fix
