### ISSUE TITLE
[$500] Login - 2FA code does not automatically submit after entering the code for the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Enter the email of an account with 2FA enabled and enter the magic code
3. Enter the 2FA code > Hit Enter
4. Log out
5. Log in again with the account with 2FA enabled
6. On 2FA entry page, navigate to the magic link from email
7. Go to staging.new.expensify.com
8. Enter 2FA code

## Expected Result:
In Step 3, the 2FA code will submit automatically after user enters the code for the first time

## Actual Result:
In Step 3, the 2FA code does not submit automatically after user enters the code for the first time. It only submits the code automatically when user navigates to staging.new.expensify.com after opening the magic link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/899e6e1e-8c81-44af-ad8c-2f84ffcc8793

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175fc8dd3183c7aea</li>
        <li>Upwork Job ID: 1717236379934355456</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27549944</li>
<li>dukenv0307 | Contributor | 27549945</li>
</ul></li>
    </ul>
</details>

**Comment by syedsaroshfarrukhdot** [comment]
I am unable to reproduce it

**Comment by brandond98** [comment]
Looks like this is expected behaviour in `ValidateLoginPage/index.website.js` when going to the email link

```
 {autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN && is2FARequired && !isSignedIn && <JustSignedInModal is2FARequired />}`
 
 ```

**Comment by situchan** [comment]
I think this should be handled as regression as the bug was caught during regression period (7th day). Came from https://github.com/Expensify/App/issues/28019.
cc: @zanyrenney @saranshbalyan-1234 @cubuspl42

**Comment by cubuspl42** [comment]
@situchan It wasn't classified as such in this period. The mentioned issue is practically closed, it was held on payments, which already happened.

**Comment by situchan** [comment]
I didn't mean that payment is cut (as paid already) but should fix this as follow-up. This GH was created 6 days 18 hrs after deployed to production.

**Comment by kadiealexander** [comment]
@zanyrenney @joelbettner any thoughts on this being a regression and having @saranshbalyan-1234 work on it?

**Comment by srikarparsi** [comment]
Hey! My thoughts are this is a regression even though the issue didn't contribute directly but it should have been made sure that no new issues are caused. @joelbettner what do you think? I'm also good with going with @dukenv0307's proposal since it makes sense.

**Comment by srikarparsi** [comment]
It seems like the solution is in this thread and it makes sense so I'm going to move forward with solving it here instead of treating it as a regression for this case.

**Comment by srikarparsi** [comment]
Hey @kadiealexander! Was payment taken care of for this issue?

**Comment by kadiealexander** [comment]
Ah no I totally missed this sorry team!

**Comment by kadiealexander** [comment]
Everyone is paid 🎉
