### ISSUE TITLE
[$500] Chat–Approaching the beginning of the conversation, the " skeleton loader " does not appear

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/26166
## Action Performed:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log in with any user
3. Navigate to 1:1 conversation
4. Scroll to the top of the chat list

## Expected Result:
As you approach the top, you should see a "skeleton loader"

## Actual Result:
Approaching the beginning of the conversation, the " skeleton loader " does not appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/28e62bf7-593e-45d6-b47f-3fc310975b40

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016977264e77e19b4a</li>
        <li>Upwork Job ID: 1717265961042673664</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by abeebridwan** [comment]
@sakluger @aimane-chnaif 
I can't reprodue this locally on the main branch
even the bottom skeleton is not working locally

**Comment by abeebridwan** [comment]
@aimane-chnaif 
the bottom skeleton is still working on the staging ... not the top

**Comment by sakluger** [comment]
@lanitochka17 can you confirm if this is still reproduceable? None of us can reproduce it.

**Comment by lanitochka17** [comment]
Issue not reproducible on latest build 1.3.93-1
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/df84c9d9-0611-4e35-aa4a-63d6e346fff8
