### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02]  IOU - After making manual &distance request, user is directed to request money BNP& Scan page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money---Manual
4. Enter an amount
5. Tap next
6. Select an user
7. Tap request amount and note user directed to Request money BNP page
8. Navigate back to LHN
9. Tap fab
10. Tap request money--Scan
11. Tap choose document
12. Select an image
13. Select an user
14. Tap request and note user directed to scan page

## Expected Result:
After making manual &distance request, user must not be directed to request money BNP page and Scan page

## Actual Result:
After making manual &distance request, user is directed to request money BNP page and Scan page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/c5305748-2e96-44cd-abe4-36c89bc85d6e

https://github.com/Expensify/App/assets/78819774/8ff28daa-3f0c-4386-b1c9-a3f6f06ce179

Production

https://github.com/Expensify/App/assets/78819774/d29cb092-4cde-4155-9221-160cae025c58

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by marcaaron** [comment]
>Reproducible in production?: Yes

Sorry @lanitochka17 can you confirm that this is or is not repro in production?

**Comment by neil-marcellini** [comment]
> Sorry @lanitochka17 can you confirm that this is or is not repro in production?

I just confirmed that it's reproducible on staging and not production. I tested on android chrome.

**Comment by marcochavezf** [comment]
Not sure if it’s related, but something’s up with the `report` object in [navigateToNextPage](https://github.com/Expensify/App/blob/348c010b440730c7e9271c48ba76832d9d61d0a9/src/libs/actions/IOU.js#L2890)

<img width="434" alt="Screenshot 2023-10-25 at 4 53 22 p m" src="https://github.com/Expensify/App/assets/6829422/02915b45-2c52-4f56-96f4-333bf946ba05">

**Comment by marcochavezf** [comment]
> reverting #29654 solves the issue, still investigation RC

I see that we're returning all the reports [here](https://github.com/Expensify/App/blob/0e660626beae07c3b8f8778000983596e0e391ba/src/pages/iou/steps/NewRequestAmountPage.js#L188) when `params.reportID` is an empty string and I think that's expected because we're requesting money from the FAB. I noticed in that PR ^ we're checking if `report.reportID` exists, but doesn't work for the case where `params.reportID` is empty.

**Comment by marcochavezf** [comment]
Thank you @ishpaul777 for detecting the offending PR. I think it will be better to revert to fix the deploy blocker and then figure out later why we're passing the reports instead of just one report

**Comment by marcochavezf** [comment]
Oh thanks @ishpaul777, I already did [here](https://github.com/Expensify/App/pull/30403)

**Comment by marcaaron** [comment]
I think we can remove the blocker here now.
