### ISSUE TITLE
Request money - All currencies not displayed in search results

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29876
## Action Performed:
1. Click global green +
2. Select Request Money
3. Go to Manual tab
4. On desktop and on desktop-web, hover over the currency symbol and verify the tooltip says "Select a currency"
5. Click on the currency symbol
6. Start typing in the search field

## Expected Result:
At the top of the search results, the text "All currencies" is translated and displayed properly

## Actual Result:
All Currencies not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 
![Bug6250762_1698260854059!Screen_Shot_2023-10-25_at_2 08 32_PM](https://github.com/Expensify/App/assets/78819774/49d7f5c5-94d4-46e8-9e91-9c7db6bc9a62)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
I'm not entirely sure what the bug is - is the problem that the text 'All currencies' is not there?

**Comment by joekaufmanexpensify** [comment]
Agreed.

**Comment by thienlnam** [comment]
@tgolen It doesn't look like the text 'All currencies' is displayed in the results from this PR as expected https://github.com/Expensify/App/pull/29876

![image](https://github.com/Expensify/App/assets/30609178/93795c56-c234-4786-ae87-e400f473d0f8)

Though I don't think this needs to be a blocker so removing that label for now

**Comment by tgolen** [comment]
Sorry! At the last minute before that PR was merged, another PR was merged that removes the "all currencies" text. I forgot to update the QA steps before it got merged. This can be closed since it's working as expected.
