### ISSUE TITLE
mac12.5 - Unable to install the staging app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch the url https://staging.new.expensify.com/NewExpensify.dmg
2. Download and open the application

## Expected Result:
App installed on device

## Actual Result:
Unable to install the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/9a50eed0-2888-4963-b9ff-e34cde762413

![Bug6250899_1698268161309!Screen_Shot_2023-10-25_at_4 59 03_PM](https://github.com/Expensify/App/assets/78819774/c7f5bbaa-fc18-4745-becf-ae47a1cae3fa)

![Bug6250899_1698268161300!Screen_Shot_2023-10-25_at_4 58 25_PM](https://github.com/Expensify/App/assets/78819774/3c61da61-db33-4c4f-8981-d24bb45a6b88)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I think I might have broke this with: https://github.com/Expensify/App/pull/30299 Looking into it

**Comment by AndrewGable** [comment]
Confirmed there is a difference in `arch` when building on an M1 runner:

![Screenshot 2023-10-25 at 3 55 31 PM](https://github.com/Expensify/App/assets/2838819/fe567f33-94e2-426c-96ec-0eff4bb68294)

![Screenshot 2023-10-25 at 3 55 18 PM](https://github.com/Expensify/App/assets/2838819/af2b6389-3d28-4ff7-9cc1-ba7f9caaa78a)

**Comment by marcaaron** [comment]
@lanitochka17 can you try to install again? This should be fixed now I think.

**Comment by AndrewGable** [comment]
Applause confirmed here: https://expensify.slack.com/archives/C9YU7BX5M/p1698284083405129?thread_ts=1698270511.559109&cid=C9YU7BX5M

Closing
