### ISSUE TITLE
[HOLD for payment 2023-11-06] [HOLD for payment 2023-11-02] Android - Attachments- uploaded attachments can be seen only after scrolling up the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap on plus icon near compose box
4. Tap attachments
5. Upload any attachment pdf, or image
6. Tap send
7. Scroll up the page

## Expected Result:
The attachment file uploaded must be fully visible
The uploaded attachments must be visible without scrolling up the page

## Actual Result:
The attachment file uploaded - pdf(up.mp4) not fully visible and image(attacks.mp4) only partially visible. The uploaded attachments can be seen only after scrolling up the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/c2bf87c6-9a59-4872-98c1-6ad3221f7e09

https://github.com/Expensify/App/assets/78819774/bb332f6e-a85b-4a84-bfb0-eab7cd16011d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by marcaaron** [comment]
I have a feeling this is related to the bidirectional pagination PR changes. Unfortunately, I am having trouble building the Android app in any capacity. It is completely broken for me.

**Comment by marcaaron** [comment]
Testing Android build with AdHoc https://github.com/Expensify/App/pull/30409

**Comment by marcaaron** [comment]
Confirmed the issue does not happen after revert. Maybe we can get a quick fix out though instead of actually reverting as the changes look great otherwise.

**Comment by marcaaron** [comment]
@janicduplessis may be able to help?

**Comment by janicduplessis** [comment]
👍 I'll have a look tomorrow

**Comment by roryabraham** [comment]
Going to see if I can get this one fixed quickly

**Comment by roryabraham** [comment]
Thinking about an `autoScrollToTopThreshold` of at least 56, to account for the full height of the `uploading attachment...` message: 

<img width="366" alt="image" src="https://github.com/Expensify/App/assets/47436092/50be7832-e0af-496d-910b-b1bad069a271">

May need to go a bit higher to also fix https://github.com/Expensify/App/issues/30423

**Comment by janicduplessis** [comment]
Looks like a good solution, thx @roryabraham

**Comment by roryabraham** [comment]
BZ checklist complete, no payments due
