### ISSUE TITLE
[Wave 6: VBA Refactor] Business Info Page: Will show the steps to collect the business information

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30418]
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [BusinessInfoPage](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.ml4s3vsoboeu) of the design doc to:

It will be 8 sub-steps + a confirmation sub-step

# Feature Description

The sub-steps are:
- Business name
- Tax ID Number
- Company website
- Company phone number
- Company address
- Company type
- Company incorporation date
- The State Company when it was incorporated in

# Manual Test Steps
N/A

# Automated Tests
N/A

**Comment by Swor71** [comment]
Hey, I'm Marcin from Callstack - expert contributor group - I would like to work on this issue
