### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] [Due November 1, 2023] MacOS Desktop switch to the `notarytool` system

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#30411]
## Problem
We are receiving this warning on all MacOS Desktop builds:

```
Notarizing using the legacy altool system. The altool system will be disabled on November 1 2023. Please switch to the notarytool system before then.
You can do this by setting "tool: notarytool" in your "@electron/notarize" options. Please note that the credentials options may be slightly different between tools.
```

## Solution
Use `notarytool` system tool in `@electron/notarize` 

cc @Expensify/mobile-deployers 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aaa4dddd4145fd7d</li>
        <li>Upwork Job ID: 1717388083552153600</li>
        <li>Last Price Increase: 2023-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27465891</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @AndrewGable</details>

**Comment by AndrewGable** [comment]
> We might need to additionally set some environment variables to make it work with the `notarytool`.

Which ones and where?

**Comment by AndrewGable** [comment]
To be honest this will be pretty complex to set up with external as it will require a lot of internal work, but if we find a good proposal we can try it!

**Comment by burczu** [comment]
@AndrewGable Is there a way I can test it locally? I've tried to build for desktop but it fails on signing step.

**Comment by AndrewGable** [comment]
Not unless you set up your own Apple developer account, but we can test this using AdHoc builds.

**Comment by kadiealexander** [comment]
@AndrewGable is this supposed to be internal or external?

**Comment by AndrewGable** [comment]
@kadiealexander - Currently set to external, but might need to switch to internal to hit deadline.

**Comment by AndrewGable** [comment]
@tienifr - Still seeing same warning

https://github.com/Expensify/App/actions/runs/6696472036/job/18194338484

https://github.com/Expensify/App/pull/30599

**Comment by AndrewGable** [comment]
Made some additional changes that @tienifr suggested and now seeing a successful build using the correct tool. I'll submit the PR, we can pay @tienifr half.

**Comment by burczu** [comment]
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by kadiealexander** [comment]
@AndrewGable any thoughts on the checklist?

**Comment by AndrewGable** [comment]
This was not a bug in the traditional sense, just something that needed to be updated to keep up with maintenance from Apple.

**Comment by kadiealexander** [comment]
Easy! @tienifr has been paid, closing this one out.
