### ISSUE TITLE
[Wave 6: VBA Refactor] Verify Identity Page: Onfido flow to validate your Identity

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30421]
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [VerifyIdentityPage](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.flp4gnfat1pe) of the design doc to:

# Feature Description

You will use the `Onfido` SDK

- Choose your document
- Message to follow the Onfido flow on their SDK
- Scan QR code
- Get Secure link
- Final step which marks the document were uploaded

# Manual Test Steps

N/A

# Automated Tests

N/A

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
Thanks, lets get this over the finish line!

**Comment by mountiny** [comment]
PR done
