### ISSUE TITLE
[Wave 6: VBA Refactor] Bank Owner Verification Page: Grab information about the Company Owners 

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30435]
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [this section](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.733zz3z5c9ut) of the design doc to:

It has 2 flows, when no Owner and when there is 

# Feature Description

[No beneficial owners](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.y221w4ppyw7d)
- you own page
- individuals own page

[Beneficial Owner](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.y221w4ppyw7d)  - you own page
- individuals own page (YES)
- First and Last name
- DOB
- SSN owner
- Owner Address
- First Confirmation 
- Checking Individual Owner (NO)
- Final Confirmation

# Flow

**General Flow**

- Click the back button: 
   - if in the first sub-steps, it will take you to the previous step or the initial screen if no previous step
   - if it is clicked in any other sub-steps, it takes you to the previous sub-step
- User drop in the middle of the step: it will start from scratch the step it drops
- User can not skip steps clicking the Interactive step header
- In the confirmation step, clicking on the items it sends the user to the right sub-step so the user can edit it, after clicking the Confirm button (The Next button changes to Confirm in edit mode), the user is taken back to the confirmation step
- All the data collected from the sub-steps are sent in the confirmation step
- The user can click on any previous completed steps to navigate back
- Clicking the `X` will take the user out of the whole flow

Checkboxes -> Default: NO

<img width="651" alt="Screenshot 2023-11-28 at 13 16 38" src="https://github.com/Expensify/App/assets/1676818/ae48a2a4-7531-472b-ad44-ec9c6667a6e2">

- If the user selects in the first screen YES, it will show the next one (the user will be shown in the confirmation step)
- If the user selects in the second screen NO, It will take the user to the confirmation step
   - It will show the user information, and you can't edit it (the MenuItem won't show the arrow)

---
<img width="1066" alt="Screenshot 2023-11-28 at 13 19 48" src="https://github.com/Expensify/App/assets/1676818/ef9e79ff-40f1-4c08-8f6d-4950598d1889">

- If first and second screen are marked as NO, it will take the user to the confirmation step

---

<img width="582" alt="Screenshot 2023-11-28 at 13 25 38" src="https://github.com/Expensify/App/assets/1676818/a8672093-dbcd-4238-afeb-b439c8cb7b65">

- If the second screen is marked as YES, the flow starts (the user will be shown in the confirmation step)
- Every time the second screen is marked as YES, the flow keeps going, until you reach 4 owners. For owners is the max amount and you stop asking for more owners and send the user to the confirmation step

---

<img width="802" alt="Screenshot 2023-11-28 at 13 36 50" src="https://github.com/Expensify/App/assets/1676818/ec254bfa-94e0-41c6-970d-a6ae3e4cf114">

- If the user selects in the first screen NO, it will show the next question
- If the user selects in the second screen YES, it will start the flow

---

<img width="767" alt="Screenshot 2023-11-28 at 13 47 22" src="https://github.com/Expensify/App/assets/1676818/2e48941b-0afe-4ed7-9e75-3fac0c6982a5">

- After filling and reaching the confirmation page, you ask if the user want to add more owners, clicking NO will take you to the Owner list to confirm it.
- Clicking YES, will take you to the Enter the legal first and last name screen, and the flow starts again to collect all the data

--- 
Removing UBO

We have the code in place but not in the design yet, we can continue without it

# Manual Test Steps
N/A

# Automated Tests
N/A

**Comment by syedsaroshfarrukhdot** [comment]
Is it open for proposals ?

**Comment by Swor71** [comment]
Hey, I'm Marcin from Callstack - expert contributor group - I would like to work on this issue

**Comment by mountiny** [comment]
Still being worked on steadily

**Comment by mountiny** [comment]
PR is being at works

**Comment by mountiny** [comment]
I think this can be closed now
