### ISSUE TITLE
[$500] Workspace - Workspace created from OD does not show up on ND unless app is refreshed or relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30447]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Log in to NewDot and OldDot with the same account
2. On OldDot, create a Control or Collect policy

## Expected Result:
The workspace room from the policy on OldDot will show up on NewDot immediately

## Actual Result:
The workspace room from the policy on OldDot does not show up on NewDot unless the page is refreshed and sometimes relogin is required

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/f1041d1b-823c-4bdd-8b17-0b853f98182f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144d2123bedb8f01a</li>
        <li>Upwork Job ID: 1717555161296072704</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by kramiusmaximus** [comment]
What is OldDot and NewDot?

**Comment by kramiusmaximus** [comment]
Contributor details
Your Expensify account email: markartyukh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ea1bc6a72aada3a6

**Comment by joekaufmanexpensify** [comment]
Not sure if we really need to treat this as a bug. We have typically said these "live update" issues are not bugs. So I am inclined to close. Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1698414957509239).

**Comment by joekaufmanexpensify** [comment]
We decided no action is needed with this. Closing!
