### ISSUE TITLE
[Tracking] VBA Refactor: Bank Transaction Validation Page: final round where agreements and transaction happens

### ISSUE THREAD

**Issue by gedu** [Expensify/App#30442]
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc.

Implement [BankValidationPage](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.s9uuwoni6qcu) of the design doc to:

The user has to check all the Agreements and validate the account with a transaction

# Feature Description

[Design](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.eielepeprivn)
There is an error, so manual fix is requery 
- Agreements step
- Chat and error message step

All good
- Agreements step
- Chat & fraud prevention message
- Transaction validation

# Flow

**General Flow**

- Click the back button: 
   - if in the first sub-steps, it will take you to the previous step or the initial screen if no previous step
   - if it is clicked in any other sub-steps, it takes you to the previous sub-step
- User drop in the middle of the step: it will start from scratch the step it drops
- User can not skip steps clicking the Interactive step header
- In the confirmation step, clicking on the items it sends the user to the right sub-step so the user can edit it, after clicking the Confirm button (The Next button changes to Confirm in edit mode), the user is taken back to the confirmation step
- All the data collected from the sub-steps are sent in the confirmation step
- The user can click on any previous completed steps to navigate back
- Clicking the `X` will take the user out of the whole flow

---
When reaching this Step, all the 5 steps in the Interactive header should be marked as completed

---
<img width="595" alt="Screenshot 2023-11-28 at 13 49 50" src="https://github.com/Expensify/App/assets/1676818/d8c96c6b-9606-492b-b826-ac3952493abe">

- The user must click all the checkboxes before moving to the Next Screen
- If the user click the Confirm button and none of the checkboxes or some of them are marked, it will show an error under the uncheckboxes 
- If there is no error, all the information from the User is CORRECT, after clicking the confirm button, they will see the next screen with the button to Validate the account.
- Clicking on Validate Account button, will take the user to performing a transaction as validation 

`ValidationStep component`

---
<img width="440" alt="Screenshot 2023-11-28 at 13 50 52" src="https://github.com/Expensify/App/assets/1676818/26ff18b1-8d85-4b35-a2d2-fd4d402f3bb6">

- The user must click all the checkboxes before moving to the Next Screen
- If the user click the Confirm button and none of the checkboxes or some of them are marked, it will show an error under the uncheckboxes 
- If there is an error, some of the information from the User or a validation is INCORRECT, after clicking the confirm button, they will see the next screen with 2 buttons to chat and to start over.

`ValidationStep component`

# Manual Test Steps
N/A

# Automated Tests
N/A

**Comment by barttom** [comment]
Hey, I'm Bartek from Callstack - an expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
Thanks!

**Comment by mountiny** [comment]
I am using this for tracking so not closing

**Comment by mountiny** [comment]
will merge the PR this week

**Comment by barttom** [comment]
@mountiny Do You think we can close this issue? :)

**Comment by mountiny** [comment]
Pleasure
