### ISSUE TITLE
[HOLD #30707][$500] iOS - Unable to scroll task description when adding a line break

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any conversation
3. Tap "+" icon and select "Assign task"
4. Enter a title
5. Enter a long description > 7 or copy a text with a line break
6. Add a line break

## Expected Result:
User is able to scroll down and view all entered text with a line break, the cursor is in focus

## Actual Result:
User is unable to scroll until a new line of text is entered, the cursor is out of focus. With copied text with a line break user is unable to view the text after a line break

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/b560b0ab-3778-48fa-85ad-5067920bde34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2f4496c506e6196</li>
        <li>Upwork Job ID: 1717553437746229248</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

**Comment by manlaig** [comment]
Previously investigated in #20836 
This bug on iOS is already mentioned in the code:
https://github.com/Expensify/App/blob/8c76d2aff5ebbaa11a951e4cdf85d1cadb6d6548/src/libs/UpdateMultilineInputRange/index.ios.js#L7-L8

**Comment by manlaig** [comment]
Contributor details
Your Expensify account email: manlai1025@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01846a9cb226f097f4

**Comment by sakluger** [comment]
@cubuspl42 what do you think of @Krishna2323's proposal?

**Comment by cubuspl42** [comment]
@Krishna2323 While I get the general idea to use `updateMultilineInputRange`, I'm not sure how should I read your code snippet. Do you have a Git branch at hand?

**Comment by sakluger** [comment]
@Krishna2323 bump on the [question for you above](https://github.com/Expensify/App/issues/30445#issuecomment-1787278558).

**Comment by sakluger** [comment]
I'm OOO all next week, going to assign another BZ member to manage while I'm out.

**Comment by cubuspl42** [comment]
@Krishna2323 bump

**Comment by isabelastisser** [comment]
Waiting for an updated proposal.

@Krishna2323, did you make progress on yours? Thanks!

**Comment by cubuspl42** [comment]
@isabelastisser Could we hold on https://github.com/Expensify/App/issues/30707? We'll be working with precisely the mentioned code part there, and I wouldn't like to go in two different directions here.

**Comment by sakluger** [comment]
@cubuspl42 we can hold for that issue. Just to make sure I understand, do you think the fix for that issue will fix this as well, or are the changes there a prerequisite to any changes we make here?

**Comment by cubuspl42** [comment]
Depending on the specific proposal (as we don't have an acceptable one, for now), it can be either

**Comment by sakluger** [comment]
Added the hold and changed the priority to weekly to match the hold issue.

**Comment by sakluger** [comment]
I see that https://github.com/Expensify/App/issues/30707 (the issue we were holding this for) was closed yesterday as not reproduceable. @cubuspl42 @lanitochka17 do you mind checking if this one is still reproduceable? Switching back to daily.

**Comment by sakluger** [comment]
Okay thanks, let's close.
