### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500]  IOU - Edit request option is present for paid message and error shows up when editing paid IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29934
## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from a workspace chat
3. Click on the expense preview to open expense report
4. Click Pay elsewhere
5. Hover over the system message for paid request
6. Click Edit request
7. Return to IOU report
8. Hover over IOU preview and click Edit request
9. Edit any field

## Expected Result:
- "Edit request" option should not be available for the system message for paid request
- When clicking on "Edit request" on IOU preview, user should be able to edit the IOU details

## Actual Result:
"Edit request" option is available for the system message for paid request. Clicking on it does not allow user to edit the request
- When clicking on "Edit request" on IOU preview and user edits IOU details, error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/78819774/87139de8-a9e0-42e8-ac19-5a28db67891a

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4085c4ba07d24d8</li>
        <li>Upwork Job ID: 1727671655146373120</li>
        <li>Last Price Increase: 2023-11-23</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Edit request option is present for paid message and error shows up when editing paid IOU
### What is the root cause of that problem?
We're showing edit option for even the system message:
https://github.com/Expensify/App/blob/a67253b715bc30fc5f024d103fedf8f5adb43a54/src/pages/home/report/ContextMenu/ContextMenuActions.js#L283-L284
### What changes do you think we should make in order to solve the problem?

I think we shouldn't show the edit option for system message like that, so we need to update the condition [here](https://github.com/Expensify/App/blob/a67253b715bc30fc5f024d103fedf8f5adb43a54/src/pages/home/report/ContextMenu/ContextMenuActions.js#L283-L284) to:
```javascript
const isSystemMessage = reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.IOU && reportAction.originalMessage.type === CONST.IOU.REPORT_ACTION_TYPE.PAY;

return type === CONTEXT_MENU_TYPES.REPORT_ACTION && ReportUtils.canEditReportAction(reportAction) && !isArchivedRoom && !isChronosReport && !isSystemMessage;
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mananjadhav** [comment]
Will test this and review this by tomorrow.

**Comment by garrettmknight** [comment]
@mananjadhav did you get a chance to test/review?

**Comment by garrettmknight** [comment]
@mananjadhav can you give this one a look when you get a chance?

**Comment by mananjadhav** [comment]
I was stuck with less internet. I'll finish this by tomorrow.

**Comment by mananjadhav** [comment]
I was able to reproduce and I am evaluating multiple proposals.

**Comment by garrettmknight** [comment]
Hope you're feeling better! Can you respond to the proposals today? This one has been open for a little while now.

**Comment by mananjadhav** [comment]
Yes better and I'lll decide on the proposals today. Thanks for the patience.

**Comment by mananjadhav** [comment]
Taking a look now.

**Comment by mananjadhav** [comment]
Overall all the proposals identified the root cause, but I prefer @tienifr's [proposal](https://github.com/Expensify/App/issues/30448#issuecomment-1782275616) as it is looks cleaner.

🎀 👀 🎀 C+ reviewed.

**Comment by puneetlath** [comment]
Hmm, will that solution prevent them from editing the money request in general? Or just the system message? 

I believe an admin should still be able to edit the request itself, even after payment. But they should never be able to edit a system message.

**Comment by puneetlath** [comment]
Ok got it! Did something change? I'm not seeing that option: 

<img width="1119" alt="image" src="https://github.com/Expensify/App/assets/1371996/3c368bd9-a2d8-415c-94fa-540fd9312763">

**Comment by puneetlath** [comment]
@garrettmknight I'm no longer seeing the bug, are you? If not, let's close.

**Comment by garrettmknight** [comment]
@puneetlath I was able to reproduce it with @tienifr's instructions - When I click the edit button, it doesn't let me edit, but it's there.

**Comment by garrettmknight** [comment]
<img width="800" alt="Screenshot 2023-11-28 at 9 40 13 PM" src="https://github.com/Expensify/App/assets/1529980/90074417-3d50-4f39-9396-102b459184c3">

**Comment by mananjadhav** [comment]
I can reproduce it as well!

**Comment by puneetlath** [comment]
Let's do it. Sorry for the delay!

**Comment by garrettmknight** [comment]
Offer sent to @tienifr https://www.upwork.com/nx/wm/offer/100202927

**Comment by mananjadhav** [comment]
I couldn't pinpoint to an exact PR for this one. Because we have canEditMoneyRequest since long. I also don't think we need a regression test for this one. @puneetlath @garrettmknight wdyt?


@garrettmknight Can you please post a payout summary for me to raise a request?

**Comment by garrettmknight** [comment]
**Summary of payments:**
- Contributor: @tienifr $500 paid via Upwork
- Reviewer: @mananjadhav $500

**Comment by garrettmknight** [comment]
Dropping to weekly for payment

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.
