### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Chat - Attachment view is not closed when opening notification and cannot reopen attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User B] Open an image attachment from any chat except User A
2. [User B] Background the app
3. [User A] Send a message to User B
4. [User B] Click on the notification
5. [User B] Close the attachment modal
6. [User B] Navigate to the same chat in Step 1 and open the attachment again

## Expected Result:
In Step 4, the attachment full screen view will be closed
In Step 6, user can open the attachment in full screen view

## Actual Result:
In Step 4, the attachment modal is not closed and the chat from the notification is opened in the background
In Step 6, user cannot open the attachment at all. It reopens on its own after the app is refreshed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/4f54e446-a0f5-4be5-99b8-5b480287c74c

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b55cf9761f95eb16</li>
        <li>Upwork Job ID: 1717554157530738688</li>
        <li>Last Price Increase: 2023-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27507413</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by mananjadhav** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/30446#issuecomment-1781374714) looks good to me.

We'll have to check if this needs to be handled any other place. I am also not sure what happens on the notification if the message itself is an attachment. Does it open the attachment, we'll have to check this test case too.

🎀 👀 🎀 C+ reviewed.

**Comment by laurenreidexpensify** [comment]
Not overdue, Joel will review later today

**Comment by laurenreidexpensify** [comment]
@joelbettner bump for review pls

**Comment by joelbettner** [comment]
@mananjadhav I agree that @tienifr's proposal looks good. Will assign.

**Comment by laurenreidexpensify** [comment]
PR looks like we're close to merging

**Comment by mananjadhav** [comment]
@laurenreidexpensify This is ready for payout. I couldn't find any offending PR for this. But I do feel we should a regression test for this one. wdyt @joelbettner?

Adding test steps from the PR as regression test.
1. Login with 2 accounts (A & B) on different browsers/apps
2. [A] Open an image attachment in any chat EXCEPT the one with B
3. Put the app in background
4. [B] Send a message to A
5. [A] Press the message notification
6. Verify that the attachment modal closes and A gets navigated to the chat with B
7. Open the chat from Step 2 >> Open an image attachment
8. Verify that the attachment modal opens

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

Contributor: @tienifr $500 payment issued in Upwork
C+ review: @mananjadhav $500 please request payment in Newdot

**Comment by mananjadhav** [comment]
Thanks @laurenreidexpensify. Was the regression test added as per the comment [here](https://github.com/Expensify/App/issues/30446#issuecomment-1924572756)?

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary above.
