### ISSUE TITLE
[$500] Web - Whisper message displayed in public room only after page refresh

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Whisper message from concierge displayed only after page refresh

## Expected Result:
Whisper message from concierge displayed

## Actual Result:
1. Create a public room as an admin and copy the report URL that looks like http:staging.new.expensify.comr/2119824243178364
2. Sign out of admin and paste the URL
3. Create a very new account and go to public room

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9df1bad1-d82d-4073-a03e-a16912644bae

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Created issue per request https://github.com/Expensify/Web-Expensify/pull/38486#issuecomment-1765699411

**Comment by WhiteStone-Mac1** [comment]
Hi all I am new here so please pardon me if I am asking a silly question but can anyone tell me how to get the option to create a public room from a new Expensify account? I have created the workspace, but the create room option is still not showing in my account. 

![Screenshot 2023-10-30 at 10 07 51 AM](https://github.com/Expensify/App/assets/145188381/267d8da2-c59b-4e10-8722-aa739303f872)

**Comment by sophiepintoraetz** [comment]
@thesahindia - waiting on you here!

**Comment by dhruvin-rv** [comment]
> I created a new account and followed the steps shown in the video. However, when I logged out and tried to access the room using the URL, it redirected me to the login page instead of allowing me to enter the room as an anonymous user. I'm not sure how to achieve the desired behavior. Can someone please assist me with this issue? I have also attached video of how it is working in my system. https://drive.google.com/file/d/1BJ689DMy0XmBH7JpkTkBBp52mcHRmfQr/view?usp=sharing
> 
> Also posted this in slack group but so far no response there.

in src>libs>Permissions.ts

// function canUseAllBetas(betas: Beta[]): boolean {
//     return betas?.includes(CONST.BETAS.ALL);
// }

function canUseAllBetas(betas: Beta[]): boolean {
    return true;
}

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on comment above.
