### ISSUE TITLE
[$500] Web - I cursor displayed for one of the error message in Connect bank account page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.2.91.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with any account
2. Navigate to Setting - Workspace - Connect Bank Account
3. Select Connect Manually
4. Don't put anything in fields, just click Next button
5. Hover over the error messages

## Expected Result:
No I cursor displayed for one of the error message in Connect bank account page

## Actual Result:
I cursor displayed for one of the error message in Connect bank account page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/1104a77d-c056-4999-a536-d9e1ae21d242

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019084b0c372df24ce</li>
        <li>Upwork Job ID: 1717646634300739584</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
hi @Krishna2323 can you provide a link to the Slack chat? I don't see it attached to this GH

**Comment by Christinadobrzyn** [comment]
Ah sorry, I don't see any recent reports in the Expensify-Bugs channel from Krishna2323 - Is your Slack handle different?

**Comment by Christinadobrzyn** [comment]
Okay thanks, I see these recent topics related to cursor

- BUG: Text cursor is not shown on address input error
- BUG: Wallet feature text doesn't display I cursor, and the text is not fully visible.
- BUG: IOS - Cursor moves at random position while entering amount

Are any of these the one you're thinking of?

**Comment by Christinadobrzyn** [comment]
Ah okay, I do see a conversation in the Bug post that @Krishna2323 made here - https://expensify.slack.com/archives/C049HHMV9SM/p1697711096201529

Reading over that convo, Vit [mentions](https://expensify.slack.com/archives/C049HHMV9SM/p1698057682936979?thread_ts=1697711096.201529&cid=C049HHMV9SM) that he thinks this might be too minor to fix. I agree - it's not great that the cursor is inconsistent but I don't know if it's worth prioritising over other bug issues. 

So I think we should close this for the time being without action. Feel free to let me know if you feel otherwise!
