### ISSUE TITLE
[$500] Request Money - Billable toggle is not enabled by default after setting it up for that

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in with a collect workspace admin on OD and an employee of the same workspace on ND.

1. As the admin on OD, go to workspace settings.
2. Go to "Expenses" tab and change "Re-bill expenses to clients" to "Default to Billable"
3. As the employee on ND, go to workspace chat.
4. Initiate a manual money request.
5. Enter the amount and click on "Next".
6. Click on "Show more".

## Expected Result:
The billable toggle should be enabled by default.

## Actual Result:
The billable toggle is disabled by default.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/6619aa13-57b2-4d6a-97a3-750c2b118ef6

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194bef3b8abca9d9f</li>
        <li>Upwork Job ID: 1717639196460920832</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Yup, a dupe. Closing this one.
