### ISSUE TITLE
[$500] Chat - No gradient between the solid color and the image in the background

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.92-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any new chat.

## Expected Result:
There is color gradient between the solid color and the image in the background.

## Actual Result:
There is no gradient between the solid color and the image in the background.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Bug6252996_1698394601345!Screenshot_2023-10-27_at_14 22 20](https://github.com/Expensify/App/assets/115492554/f9dc3e55-a8a3-4b95-854e-1d23d3ccec31)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f667fedc8bac5732</li>
        <li>Upwork Job ID: 1717871053320433664</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @justinpersaud</details>

**Comment by izarutskaya** [comment]
Not reproducible in production
![Screenshot 2023-10-27 at 14 23 47](https://github.com/Expensify/App/assets/115492554/271fe5f0-97b2-45ed-9aea-10809bef9750)

**Comment by jayeshmangwani** [comment]
It seems like a regression from the [ImgBot github action](https://github.com/Expensify/App/issues/28157), if we manually use this [original image](https://github.com/Expensify/App/blob/38a3f937cc81a3e1c67a9973c9dbb01948a0b8eb/assets/images/empty-state_background-fade.png) then it works fine but when we use using optimised image then it will remove the fade effect, 
cc: @roryabraham @justinpersaud

**Comment by justinpersaud** [comment]
Yeah I see the same issue. It's from this PR the bot made.

https://github.com/Expensify/App/pull/30383

It's supposed to compress with lossless compression, so I wonder why it affects colour gradients.

**Comment by justinpersaud** [comment]
Submitted the fix https://github.com/Expensify/App/pull/30512

**Comment by cristipaval** [comment]
Thanks for jumping into this one @justinpersaud !

**Comment by Julesssss** [comment]
Removing the blocker label, it's now Cpd and on the [checklist](https://github.com/Expensify/App/issues/30469#issuecomment-1783066084)

**Comment by justinpersaud** [comment]
Closing this of then as resolved

**Comment by kbecciv** [comment]
Issue is reproduced on build 1.4.7.0, re-opening 
![bandicam 2023-12-02 12-09-57-433](https://github.com/Expensify/App/assets/93399543/a3797c78-7759-47f8-ac25-9969c2d1e3b3)
