### ISSUE TITLE
[Payment 2023-11-27][$500] Workspace-In offline invited members are not shown in announce room members list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap preferences
4. Toggle on forced offline
5. Tap back button
6. Tap workspaces
7. Tap new Workspace
8. Tap members
9. Tap invite
10. Invite a member to Workspace
11. Tap back button
12. Tap in 3 dot on top right and open announce room
13. Tap on header
14. Tap on members

## Expected Result:
In offline invited members must be shown in announce room members list

## Actual Result:
In offline invited members are not shown in announce room members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/6edfae09-66cf-4dc8-b68c-c072282b7e1e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01309bef3b2d9e5ae5</li>
        <li>Upwork Job ID: 1717865694923780096</li>
        <li>Last Price Increase: 2023-10-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27438367</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mallenexpensify** [comment]
@allroundexperts can you please review @dukenv0307 's proposal above?

**Comment by cristipaval** [comment]
You're right, @dukenv0307! Changed the labels on the issues, @mallenexpensify could you please take care of this one?

**Comment by mallenexpensify** [comment]
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @allroundexperts due $500 via NewDot

Thanks!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.
