### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] iOS - Chat - Screen flickers after second double tap on large PDF file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Send a large PDF file.
3. Tap on the PDF preview.
4. Double tap on it to zoom in.
5. Double tap again.

## Expected Result:
With the second double tap, the view should zoom in without any visual issues.

## Actual Result:
After the second double tap, the screen flickers.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/115492554/e6420fb2-7cad-47f1-be35-dbb4ad4af60e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01088b41c7fad72c6c</li>
        <li>Upwork Job ID: 1717856931582775296</li>
        <li>Last Price Increase: 2023-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27742246</li>
</ul></li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
@situchan can you please review the proposal above? Thanks!

**Comment by situchan** [comment]
@alex2bc can you please provide the followings?
- test pdf
- video before fix
- video after fix
- method for "empty double tap gesture handler"

**Comment by situchan** [comment]
@alex2bc thanks for providing details. Have you tried to find any open issue in react-native-pdf?
It's ideal to fix this in upstream. We can try that first before applying patch.

**Comment by isabelastisser** [comment]
Hey @situchan, can you please follow up? Thanks!

**Comment by situchan** [comment]
Was expecting ideal fix.

@alex2bc can you please try to raise issue/PR in upstream repo?
We can give that a try first.

**Comment by situchan** [comment]
Waiting for upstream fix

**Comment by isabelastisser** [comment]
@situchan @alex2bc, when should we expect to have the new version released? Should I change this issue to `weekly`?

**Comment by situchan** [comment]
waiting for version bump on upstream

**Comment by situchan** [comment]
Not overdue

**Comment by situchan** [comment]
Let's go with @alex2bc's [proposal](https://github.com/Expensify/App/issues/30492#issuecomment-1783856351).
@alex2bc's upstream [PR](https://github.com/wonday/react-native-pdf/pull/781) was merged and published. So the remaining work here is to bump react-native-pdf version 6.7.1 > 6.7.2
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
@alex2bc I didn't ask you to create PR. Should be approved by engineer.
Btw, android build is failing for me

<img width="1149" alt="android pdf build error" src="https://github.com/Expensify/App/assets/108292595/f0f91c74-f354-4a76-bf3b-83043f9ffb90">

**Comment by luacmartins** [comment]
Assigning @alex2bc to the issue.

**Comment by isabelastisser** [comment]
@situchan can you please complete the list above? Thanks!

**Comment by isabelastisser** [comment]
Payments are processed in Upwork.
