### ISSUE TITLE
[$500]  Web - Thread - Thread disappears from the LHN when Delete the message in the thread.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. On LHN, click on any chat and send a message.
4. Create a thread and comment.
5. Delete a comment.
6. Look on to LHN not navigate away from the thread conversation.

## Expected Result:
Created thread remains in LHN.

## Actual Result:
The thread disappears from the LHN when Delete the message in the thread and not navigate away from the thread conversation.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/2e8e35ee-3e5a-4f00-b931-cf3de828f8b6

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5dff96428521da3</li>
        <li>Upwork Job ID: 1717868047921123328</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertjchen</details>

**Comment by getusha** [comment]
I start a discussion in `expensify-open-source` about the expected result
https://expensify.slack.com/archives/C01GTK53T8Q/p1698408127981499

**Comment by getusha** [comment]
>We need to fix the back-end following the same logic as well.

@dukenv0307 I'm not sure how the back-end fix will work, could you add more explanation on this and the alternative solution?

**Comment by getusha** [comment]
🎀 👀 🎀
to get more eyes on the backend fix from internal engineer.

**Comment by getusha** [comment]
@robertjchen could you check if you can fix `DeleteComment` to return the correct `lastVisibleActionCreated` value?
check this https://github.com/Expensify/App/issues/30498#issuecomment-1782786628 and this proposal for more detail https://github.com/Expensify/App/issues/30498#issuecomment-1783718781

**Comment by johncschuster** [comment]
@robertjchen can you take a look when you get a moment?

**Comment by getusha** [comment]
Friendly bump @robertjchen https://github.com/Expensify/App/issues/30498#issuecomment-1784531439

**Comment by johncschuster** [comment]
Hmm... Melvin seems to be suffering from amnesia.

**Comment by robertjchen** [comment]
Didn't get to it last week, still need to look in the backend.

**Comment by robertjchen** [comment]
Still a backend issue

**Comment by getusha** [comment]
Waiting for @robertjchen, to take a look at this on the backend.

**Comment by robertjchen** [comment]
Will look into this on the backend 👍

**Comment by johncschuster** [comment]
How's this going, @robertjchen?

**Comment by robertjchen** [comment]
Full focus is on the waves at the moment, will try to get to this soon

**Comment by johncschuster** [comment]
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
This is a backend issue. Robert's had his focus tied up with higher urgency wave items. We're waiting for him to dig into this one.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by getusha** [comment]
Waiting for backend fix @robertjchen.

**Comment by robertjchen** [comment]
Still pending BE fix

**Comment by johncschuster** [comment]
I'm back from OOO @trjExpensify. I'll take this off your plate.

**Comment by robertjchen** [comment]
Won't be able to get to this given current wave priorities. @johncschuster could you please see if another engineer is available to investigate the backend solution as laid out here? Thanks! https://github.com/Expensify/App/issues/30498#issuecomment-1783718781

**Comment by getusha** [comment]
Friendly bump @johncschuster on https://github.com/Expensify/App/issues/30498#issuecomment-1882780242

**Comment by johncschuster** [comment]
Asked for help in [#engineering](https://expensify.slack.com/archives/C03SSAQ7P/p1706039994071419).

**Comment by johncschuster** [comment]
I've bumped the thread in #engineering. Will get noisier next week if need be.

**Comment by johncschuster** [comment]
Bumped it again. I kinda wonder if this is related to #vip-vsb. I've asked @zsgreenwald to take a look.
