### ISSUE TITLE
[$500] Android-App crashes while viewing applause.expensifail.com chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing:** PR https://github.com/Expensify/App/pull/28596
**Version Number:** 1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on #applause.expensifail.com report
3. Scroll the page up and down and wait

## Expected Result:
Tapping on #applause.expensifail.com, the page must load properly and user must be able to scroll and view all chat and app must not crash.

## Actual Result:
Tapping on #applause.expensifail.com, behaves like non responsive and then takes long time to open, becomes black and then load and it's is very slow. When user scrolls the page up and down and wait for the page to load, app shows message not responding and crashes. Link to chat - https://staging.new.expensify.com/r/5324367938904284.
Crashes on all expensifail account.

When user opens expensifail chat and view chat it shows "New expensify isn't responding", tapping on "wait", shows same error message again and again. If tap " Ok" app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/660b9055-89ac-49d8-a6d3-42f7c04bf009

https://github.com/Expensify/App/assets/115492554/570060d8-854e-40ce-b7a0-d61276d17219

https://github.com/Expensify/App/assets/115492554/c4ccbb06-8ed4-4bde-bec0-3104ed0d575c

[expensifail_crash.txt](https://github.com/Expensify/App/files/13188150/expensifail_crash.txt)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e387eb00370bb06</li>
        <li>Upwork Job ID: 1717859238627438592</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by getusha** [comment]
@adelekennedy I don't think external contributors have access to `#applause.expensifail.com` report, @izarutskaya is there any other way to reproduce this?

**Comment by adelekennedy** [comment]
@izarutskaya same question as the above - if this is a problem specifically with an expensifail account on adroid then i would move to close this unless we have reason to believe this would happen on other genuine accounts

**Comment by izarutskaya** [comment]
@getusha @adelekennedy I can still reproduce this with `#applause.expensifail.com` but with old `gmail` account no.

https://github.com/Expensify/App/assets/115492554/cd4bcedf-6dc3-4fbf-98d7-4a72ab1fa2bc

https://github.com/Expensify/App/assets/115492554/87ad3476-6622-4610-a3e7-59fa3bd64344

**Comment by getusha** [comment]
@izarutskaya we can't access that room, is there a general way of reproducing this?

**Comment by izarutskaya** [comment]
@getusha Can you please ask in the open-source channel to gain access to the room?

**Comment by adelekennedy** [comment]
sorry all I was ooo for a few days - @izarutskaya is there a way for contributors to test and reproduce this?

**Comment by izarutskaya** [comment]
Hello @adelekennedy Maybe you can ask in the open-source channel to gain access to the room, can you try please?
