### ISSUE TITLE
[$500] Login - "Phone or email" placeholder does not have a smooth transition when field is focused

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on the phone or email field

## Expected Result:
"Phone or email" placeholder should have a smooth transition when field is focused or defocused

## Actual Result:
"Phone or email" placeholder does not have a smooth transition when field is focused or defocused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/115492554/704506b8-4757-447a-9c9a-1df42dcc3c1b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8f6abe649ee72bc</li>
        <li>Upwork Job ID: 1717874317558493184</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@Ollyws how about this proposal?

**Comment by laurenreidexpensify** [comment]
@Ollyws bump for review thanks

**Comment by laurenreidexpensify** [comment]
I'm gonna close this on the premise we can't repro
