### ISSUE TITLE
[$500] Android - Room - Unable to refocus on the room name field after defocusing it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing:** PR https://github.com/Expensify/App/pull/29771

**Version Number:** v1.3.92-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch New Expensify app.
2. Go to Start chat > Room.
3. Enter a room name.
4. Remove focus from the room name field by tapping on the blank space.
5. Tap on the room name field.

## Expected Result:
User is able to focus on the room name field with no issue.

## Actual Result:
User is unable to focus on the room name field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/fc7e4f03-d377-40a3-9057-e3299b125fe6

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdcda8d4b7dff0de</li>
        <li>Upwork Job ID: 1717883933922177024</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment]
I think team is planned to revert the issue PR - https://github.com/Expensify/App/issues/28877#issuecomment-1782952190

**Comment by pecanoro** [comment]
Thank you for letting me know! I am going to keep an eye to see if we revert it

**Comment by luacmartins** [comment]
We're reverting the offending PR

**Comment by luacmartins** [comment]
We can close this issue since we're CPing the revert and it'll be tested again in staging.
