### ISSUE TITLE
[HOLD for payment 2023-11-07] [HOLD for payment 2023-11-06] [$500] Contact methods - Fix the errors CTA in Add new contact method page crashes the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29869

**Note:** Crash is reproducible on Android and iOS app.
On web and desktop, console error shows up.

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Profile > Contact methods.
3. Click New contact method.
4. Enter an invalid email.
5. Click Save.
6. Click Fix the errors.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a775b4a2-27df-4337-8d9d-0ee527d0aebd

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131fa74ee0414e807</li>
        <li>Upwork Job ID: 1717976360459390976</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
cc @luacmartins 

I think we should accept both object or function (alternative solution).

**Comment by luacmartins** [comment]
Agreed that it should accept both.

**Comment by luacmartins** [comment]
@ishpaul777 are you available to work on the alternate solution fix in the next few minutes?

**Comment by luacmartins** [comment]
It's yours! Please tag me for review

**Comment by luacmartins** [comment]
Fix is being CPed. Keeping this issue open to process payment.

**Comment by abdulrahuman5196** [comment]
I didn't review the PR actually. It was reviewed internally.

**Comment by luacmartins** [comment]
Just pending payment

**Comment by maddylewis** [comment]
### Payments
- [ ] Reporter: N/A
- [ ] Contributor: @ishpaul777 ($500 paid via Upwork)
- [ ] C+: @abdulrahuman5196 ($500 paid via Upwork)

Contributor hired on / PR merged on Oct 27

**Comment by maddylewis** [comment]
offers sent ($500 via Upwork)

**Comment by maddylewis** [comment]
paid
