### ISSUE TITLE
[$500] Android - Profile-After selecting pronoun, keypad remains open and shown in profile page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Profile
4. Tap pronoun
5. Type "The"
6. Select a pronoun from the suggested list

## Expected Result:
In pronoun page, after selecting pronoun, keypad must not be shown in profile page

## Actual Result:
In pronoun page, after selecting pronoun, keypad remains open and shown in profile page until selected pronoun is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/9a326f38-5aed-4c11-9145-fa64b688869c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff1fb12e6fe58887</li>
        <li>Upwork Job ID: 1717948058125668352</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Looks like this is no longer blocked actually. I asked QA to re-test it.

**Comment by puneetlath** [comment]
Looks like https://github.com/Expensify/App/issues/30268 fixed it. Closing!
