### ISSUE TITLE
[Wave 6: Workspace Chats] Workspace chat disappears from LHN for requestor after request is paid

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#30535]
Coming from [Slack](https://expensify.slack.com/archives/C02MW39LT9N/p1698430330390489), the workspace chat disappears from the LHN for the requester after their request is paid.

**Reproduction Steps:**
1. As user A, request money in a workspace chat
2. As the workspace admin in an incognito window, reimburse the request

**Actual behavior:**
Notice the workspace chat has disappeared from the LHN for user A

**Expected behavior:**
The workspace chat should stay visible in the LHN

https://github.com/Expensify/App/assets/7277067/35f74e4e-7f67-495e-8a71-f1fe46f13ff2

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@amyevans, @puneetlath, I've finished with the investigation. Seems like it is a backend bug. 

Basically, the app checks if a report has participants (_last 2 lines below_). 
https://github.com/Expensify/App/blob/b321b0a178f93300ba52d278f31cf0723018b88b/src/libs/ReportUtils.js#L3265-L3278

So, we expect to see only reports with participants - logical.

Once another user (**_B_**) has been paid an expense report, the **Pusher** sends a message to a requestor (_**A**_). Inside the message there is an update for a particular workspace chat. On a screenshot below we can see, it is saying that `participantAccountIDs` is empty now.

<img width="1708" alt="Pusher updates" src="https://github.com/Expensify/App/assets/57314631/2c1f0aa3-e662-455f-bcfb-3deec50d8369">

Just after next page refresh, the app fetches the same report with correct `participantAccountIDs` data.

<img width="1329" alt="Refresh" src="https://github.com/Expensify/App/assets/57314631/2c84ee45-120d-46ca-9542-3b8c44693b80">

I don't see any actions that we need on the app side. WDYT?

**Comment by puneetlath** [comment]
Ahhh ok good find. So we need to correct the back-end to not send the participantAccountIDs as empty in that scenario.

**Comment by rezkiy37** [comment]
Yes, correct.

**Comment by amyevans** [comment]
Got it, thanks for digging into that @rezkiy37! Backend fix it is 😄

**Comment by rezkiy37** [comment]
I have to inform that starting tomorrow I have a short vocation until next Monday (_6.11.2023_). Feel free to left any comments, I will address them. See you soon 😉

**Comment by amyevans** [comment]
PR up: https://github.com/Expensify/Web-Expensify/pull/39488

**Comment by amyevans** [comment]
Fix is live!
