### ISSUE TITLE
Unable to clone the repository on windows. [npm install error]

### ISSUE THREAD

**Issue by Nirbhay007** [Expensify/App#30549]
Hi, i am trying to clone the repo in my windows laptop but its throwing error after running the shellcheck script, i am thinking it might be the issue related to path but i tried changing that as well still not working. I have attached the screenshot for the same. Any work around with this or someone who has encountered the same?

![Screenshot (134)](https://github.com/Expensify/App/assets/41774166/56d6fa96-83c6-437e-81c6-aea1cb4d97a1)

**Comment by Nirbhay007** [comment]
Hello @grgia  @lanitochka17  @kbecciv  @AndrewGable 

I'm encountering an issue that I've been trying to resolve, and it seems others are facing the same problem. I also sent a Slack invite request three days ago but haven't received a response yet. Any help would be greatly appreciated. Thanks in advance!

**Comment by Balogh08** [comment]
I have similar issue. I can avoid it by using WSL, but some other similar issues arise for me by using WSL. 

Waiting for slack invite, but no response yet.

**Comment by Balogh08** [comment]
Contributor details
Your Expensify account email: balogh.botond8@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019fc0ae261ec3c655

**Comment by Balogh08** [comment]
Contributor details
Your Expensify account email: [balogh.botond8@gmail.com](mailto:balogh.botond8@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~019fc0ae261ec3c655

**Comment by Balogh08** [comment]
Contributor details
Your Expensify account email: balogh.botond8@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019fc0ae261ec3c655

**Comment by yousefalaqra** [comment]
I'm also facing this issue. did anyone manage to resolve the issue?

**Comment by yousefalaqra** [comment]
Contributor details
Your Expensify account email: yousif.aqra@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012ad88b7b6cb5fc98

**Comment by insub** [comment]
Contributor details
Your Expensify account email: insuber@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0161295c84b484bd5d

**Comment by github-eliyas** [comment]
Contributor details
Your Expensify account email: saifeliyas@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0113346825dc76d349

**Comment by mzainulabideen96** [comment]
Contributor details
Your Expensify account email: mzainulabideen1996@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019f9543157a2cfd28

**Comment by dddingnan** [comment]
Contributor details
Your Expensify account email: [silenceapple1027@gmail.com](mailto:silenceapple1027@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01dad179698d0d5998

**Comment by dddingnan** [comment]
Contributor details
Your Expensify account email: [silenceapple1027@gmail.com](mailto:silenceapple1027@gmail.com)
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~01dad179698d0d5998)

**Comment by dddingnan** [comment]
Contributor details
Your Expensify account email: [silenceapple1027@gmail.com](mailto:silenceapple1027@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01dad179698d0d5998

**Comment by dddingnan** [comment]
Contributor details
Your Expensify account email: [silenceapple1027@gmail.com](mailto:silenceapple1027@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01dad179698d0d5998

**Comment by alimohyudin14** [comment]
Contributor details
Your Expensify account email: [mzainulabideen1996@gmail.com](mailto:mzainulabideen1996@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~019f9543157a2cfd28

**Comment by alimohyudin14** [comment]
Contributor details
Your Expensify account email: mohyudin12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a76b30b541654cde
