### ISSUE TITLE
[HOLD for payment 2023-12-20] [HOLD for payment 2023-12-12] [Tracking] Use measureFunction from reassure to cover performance testing of important functions

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30569]
Coming from here https://expensify.slack.com/archives/C05LX9D6E07/p1698193710179789

We have set up the reassure in the App with new option to use `measureFunction` to test performance of methods. Lets use this to cover the most crucial method in the app to ensure changes do not introduce big regressions in these methods which might already take long and are called often.

Let's focus on methods in `ReportActionsUtils`, `SidebarUtils` (`getOptionData` specifically) and `ReportUtils`

- [ ] getLastVisibleAction https://github.com/Expensify/App/pull/30482

**Comment by mountiny** [comment]
this is being worked on

**Comment by mountiny** [comment]
@OlimpiaZurek @adhorodyski This is all done, right?

**Comment by OlimpiaZurek** [comment]
Hey @mountiny perf tests for methods from `SidebarUtils` and `ReportActionUtils` have already been done. Now I’m working on adding tests to `ReportUtils`.   This will be the last part of this scope.  PR should be ready by the EOD.

**Comment by OlimpiaZurek** [comment]
@mountiny PR is ready for review

**Comment by mountiny** [comment]
Seems like we are all done here!
