### ISSUE TITLE
[HOLD for payment 2023-11-09] Can't write some symbols in newDot

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#30578]
Steps:
- Try to write `(`, `)`, `[` (also `*` but seems like sometimes you can write it)
- Check it does not get written

Happening on web staging but not on web production, so must be something we deployed to staging, thus we need to block deploy.

**Comment by Beamanator** [comment]
Fix was CP'd 👍

**Comment by lschurr** [comment]
Payment for this is happening over here: https://github.com/Expensify/App/issues/28149

**Comment by lschurr** [comment]
Thanks! Can you apply here @aimane-chnaif - https://www.upwork.com/jobs/~01cfb8e70d95e95640

**Comment by lschurr** [comment]
Paid and closed.
