### ISSUE TITLE
[$500] Distance-All available workspaces are not shown while making distance request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login as [applausetester+d1@applause.expensifail.com](mailto:applausetester+d1@applause.expensifail.com)
3. Tap profile
4. Tap Workspaces
5. Note the number of workspaces are displayed
6. Navigate back to LHN
7. Tap fab
8. Tap request money
9. Tap distance request
10. Enter start and finish waypoints
11. Tap next and note the number of workspaces are displayed

## Expected Result:
All available workspaces should be shown while making distance request

## Actual Result:
All available workspaces are not shown while making distance request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/461f9ec1-f04f-4b22-badd-a6b3fa650e65

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e33e6730e7c176a8</li>
        <li>Upwork Job ID: 1719017322423808000</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
@neil-marcellini I saw [your proposal](https://expensify.slack.com/archives/CC7NECV4L/p1698164341635109). Given the available list is going to be changing here soon anyway, I'm thinking no action needed on this one and we can close it. But curious if you agree?

**Comment by joekaufmanexpensify** [comment]
[Brought to Slack](https://expensify.slack.com/archives/C05DWUDHVK7/p1698786813976989)

**Comment by joekaufmanexpensify** [comment]
We discussed and are going to close this, since we are planning some changes to this form that will obviate this issue.
