### ISSUE TITLE
[$500] [HOLD for payment 2023-11-09] Error thrown when left and right arrow keys pressed

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#30593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0 
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:**

## Action Performed:
Break down in numbered steps
1. Go to a conversation in ND
2. Open the web console
3. Type a few things
4. Move the cursor using the arrow keys (left and right)

## Expected Result:
The console should have no errors associated with using the arrow keys

## Actual Result:
The error `Uncaught TypeError: Cannot convert undefined or null to object` appears.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>

https://github.com/Expensify/App/assets/5201282/0e168d35-3f2f-4365-99a9-00f18235d1ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd1222fab2da90a5</li>
        <li>Upwork Job ID: 1722643867637014528</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by rlinoz** [comment]
Hey @zanyrenney I will be working on this

**Comment by situchan** [comment]
Happy to review as C+ if needed

**Comment by rlinoz** [comment]
That would be great

**Comment by situchan** [comment]
@rlinoz thanks. Can you please assign me to the issue so that correct C+ is assigned as reviewer in PR?

**Comment by NikkiWines** [comment]
Adding the deploy blocker label since this is currently on staging only

**Comment by zanyrenney** [comment]
thanks everyone!

**Comment by situchan** [comment]
@ZhenjaHorbach this is not open for proposals

**Comment by Julesssss** [comment]
Removing the deploy blocker label as this is purely a console error and not important enough to block the deploy.  cc @rlinoz

**Comment by zanyrenney** [comment]
@situchan i have invited you to the job as reviewer - will also add bug report to payout.

**Comment by zanyrenney** [comment]
waiting for @situchan - offer has been sent.

**Comment by zanyrenney** [comment]
payment summary

@situchan $500 review + $50 report. closing.
