### ISSUE TITLE
[HOLD for payment 2023-11-17] Connect bank account - "You're all set!" message appears for a moment when deleting BA

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30592]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS (or create it) -> Connect bank account -> Connect online with Plaid
4. Choose any bank and complete the process
5. When BA is connected, tap on "Disconnect bank account" -> Confirm it

## Expected Result:
The bank account is deleted without any additional message

## Actual Result:
"You're all set!" message appears for a moment when deleting BA

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 
![Bug6256889_1698678262410!image__173_](https://github.com/Expensify/App/assets/78819774/fcb90b30-0b15-495b-a537-502f79cdb4b3)

https://github.com/Expensify/App/assets/78819774/eda6012e-286e-4f5c-b657-1820a63b5827

Production:

https://github.com/Expensify/App/assets/78819774/4815605b-efc7-48e9-9afa-7cf3e826a639

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I don't think this is a blocker. It doesn't impact any functionality and it's just a temporary UI that's shown while the request loads. I put up a PR with a fix, but I don't think we need to CP this.

**Comment by garrettmknight** [comment]
No payments, closing.

**Comment by situchan** [comment]
@garrettmknight can you please help with C+ payment for reviewing [PR](https://github.com/Expensify/App/pull/30597)?

**Comment by garrettmknight** [comment]
Reopening for C+ payment

**Comment by garrettmknight** [comment]
https://www.upwork.com/en-gb/ab/applicants/1732122584354410496/job-details

**Comment by garrettmknight** [comment]
Paid, closing
