### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Scan receipt - Crash when trying to download a receipt while in scanning process

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify or the mobile app
2. Navigate to the workspace chat as an employee
3. Select "Request money" > "Scan receipt"
4. Upload a receipt file from your device
5. Click "Request"
6. Navigate to the request conversation
7. Open the request preview and the attached receipt
8. Click "More" > "Download"

## Expected Result:
When attempting to download a receipt while in scanning process, Expensify crashes

## Actual Result:
It should be possible to download the receipt in all viable scenarios
Extra info: Crash occasionally happens with any type of request (Manual, Scan and Distance)
Uh-oh, something went wrong!
Please try closing and reopening the app or switching to web.
If the problem persists, reach out to [concierge@expensify.com](mailto:concierge@expensify.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/28850b1e-11b6-4033-b97f-53d6fad41501

[logs.txt](https://github.com/Expensify/App/files/13210615/logs.txt)

https://github.com/Expensify/App/assets/78819774/0c94f411-4b9f-4054-911d-2af272a15007

![Bug6257345_1698699484426!Uh-oh__something_went_wrong_](https://github.com/Expensify/App/assets/78819774/0da1e2fc-c33a-49c4-b0a5-95916cba6648)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128ad4c7b2932ce1f</li>
        <li>Upwork Job ID: 1719139466680426496</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27512074</li>
<li>mkhutornyi | Contributor | 27512075</li>
</ul></li>
    </ul>
</details>

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan receipt - Crash when trying to download a receipt while in scanning process

### What is the root cause of that problem?

The `AttachmentModal` component doesn't receive the file name by the property "**originalFileName**" by default its value is an empty string.

https://github.com/Expensify/App/blob/ec7fb3ccb73a274cd275b75b8599cfc1d663ebfa/src/pages/home/report/ReportAttachments.js#L35-L43

### What changes do you think we should make in order to solve the problem?

We should change the `ReportAttachments` component to extract the file name from the `source` property and passing this value to the `AttachmentModal` component.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kidroca** [comment]
It strikes me as counterintuitive and potentially problematic that users are able to initiate a download of an attachment before the upload process to the server is even finalized. Consider the following inconsistencies:

1. **Premature Download Option**: The current functionality presents the download button even before the upload is completed. This is technically paradoxical; how can one download an attachment that hasn't fully reached the server yet? Are users downloading the very data they're in the process of uploading?
   
2. **Processing State Ambiguity**: Additionally, the button remains active while the attachment is flagged as 'processing'. I'm very familiar with the Receipt feature but if the end state of a receipt can morph post-processing, say from a simple image to a structured PDF, shouldn't the download only be permissible post this transformation to ensure consistency and integrity of the document?

In my opinion, the download feature should be context-sensitive and only become available when the upload is conclusively complete and the file is in a stable, fully processed form.

**Comment by maddylewis** [comment]
### Payment Summary
- [ ] @aimane-chnaif requires payment [offer](https://www.upwork.com/nx/wm/offer/27512074) (Reviewer)
- [ ] @mkhutornyi requires payment [offer](https://www.upwork.com/nx/wm/offer/27512075) (Contributor)

**Comment by maddylewis** [comment]
both C+ and Contributor paid via Upwork!
