### ISSUE TITLE
[$500] Android - App freezes for many seconds quite often, system UI not responding

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30630]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @keisyrzk
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1698141617432959

## Action Performed:
1. Log into the app
2. Walk through the app into different places

## Expected Result:
App works clearly without lags. 

## Actual Result:
The app freezes for many seconds quite often

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/7c40c771-a3b9-48de-be8c-1f1a4eff7a22

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01400c5c5b8030073a</li>
        <li>Upwork Job ID: 1719338729605570560</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by burczu** [comment]
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th. I'll be able to start reviewing proposals then, of course if we receive any.

**Comment by samilabud** [comment]
I can't reproduce this, except in an Android emulator with few resources (1GB RAM).

**Comment by peterdbarkerUK** [comment]
ya this is performance issues and not reproducible
