### ISSUE TITLE
[$500] Distance - RBR is not followed when editing distance offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698078050501159

## Action Performed:
1. Create a new distance request.
2. Go to the distance request.
3. After it has loaded, go offline.
4. Edit the distance to something invalid.
5. Go back online.
6. Click on the distance
7. Notice that there is no red dot on the distance or report even though there is error in distance

## Expected Result:
We should see the the red dot on the distance menu item in the request view itself.

## Actual Result:
There is not red dot to indicate that there was an error (other than the distance page itself)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/f5298de3-e314-4157-b154-29adc980a848

https://github.com/Expensify/App/assets/93399543/b91aeed9-9c29-4166-b5f3-8224c6948498

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146d60cdfb61c0db0</li>
        <li>Upwork Job ID: 1719425008905248768</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
# Proposal

## Please re-state the problem we are trying to solve
RBR is not followed when editing distance offline.

## What is the root cause of this problem?
When there is an error with a distance edit request, it is set on the transaction itself but it is only displayed in the `DistanceRequest` component. We are not displaying error on the menu item here:
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/components/ReportActionItem/MoneyRequestView.js#L205-L215

There are basically two errors that are set on the `transaction` when we update the distance request. 
One is `waypoints: [error]` which is set in the `failureData` here:
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/IOU.js#L789-L797

The other error is `route: [error]` which is set by the backend.

The changes I propose below will set the `waypoints` error because the `route error` is already shown on the `DistanceRequest` page, but they can be interchanged anyway preferred.

## What changes should be made?
**Option 1:**
Since the menu item is wrapped with `OfflineWithFeedback` the route errors can be passed to it like this:
```js
<OfflineWithFeedback 
    errorRowStyles={styles.mh5} 
    errors={ErrorUtils.getLatestErrorField(transaction, 'waypoints')} // or 'route'
    pendingAction={lodashGet(transaction, 'pendingFields.waypoints') || lodashGet(transaction, 'pendingAction')}
>
```
This is the result that this will yeild:
<img width="694" alt="Screenshot 2023-10-24 at 6 30 35 PM" src="https://github.com/Expensify/App/assets/77237602/8ea909fb-a788-4e4c-a415-1ef009662e87">

**Option 2:**
Instead of setting the errors on `OfflineWithFeedback`, we can set them on the `MenuItemWithTopDescription` itself:
```js
<MenuItemWithTopDescription
    description={translate('common.distance')}
    ...
    brickRoadIndicator={!!transaction.errorFields?.waypoints && CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR}
    error={!!transaction.errorFields?.waypoints && getDistanceError(transaction)}
/>
```

Here is the definition for `getDistanceError(transaction)` used above (can be defined in the component body):
```js
const getDistanceError = (transaction) => {
    const errorField = ErrorUtils.getLatestErrorField(transaction, 'waypoints');
    const key = Object.keys(errorField)[0];
    return errorField[key];
}
```

Here is how it looks:
<img width="559" alt="Screenshot 2023-10-24 at 7 47 26 PM" src="https://github.com/Expensify/App/assets/77237602/476058e4-65e4-42a3-8b71-8280d5420e63">


**Additional change (Optional)**
If we also want the red dot on LHN, like in the following image, we can add this change as well.

<img width="284" alt="Screenshot 2023-10-24 at 7 48 20 PM" src="https://github.com/Expensify/App/assets/77237602/be4833af-1c61-47e1-a0a3-672c900d8e6c">

In the `failureData` here:
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/IOU.js#L789-L797

We can also add the error to the `transactionReport` by adding this method:
```js
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT}${transactionThreadReportID}`,
    value: {errorFields}
}
```

Then we can also reset this in the `successData` here:
https://github.com/Expensify/App/blob/cc3c51c1d58ce013e444b59bd06c87e4b750e550/src/libs/actions/IOU.js#L769

By adding this method:
```js
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT}${transactionThreadReportID}`,
    value: {errorFields: null}
}
```

**Comment by alexpensify** [comment]
Thanks for flagging, closing in favor of the GH above.
