### ISSUE TITLE
[$500] Thread - Admin lands in [Delete message] after login when employee subscribes to welcome message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.93-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N, the feature is not available on production.
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. [Admin] Invite employee to a workspace.
2. [Admin] Log out.
3. [Employee] Open the workspace chat > right-click on the welcome message > Subscribe to thread.
4. [Admin] Log in.

## Expected Result:
Admin lands on valid chat report.

## Actual Result:
Admin is redirected to [Delete message] from the welcome message thread. Sometimes 'welcome message' thread. opens without [Deleted message].

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/c5a494b7-7166-4de9-b9df-8d2765d5a68a

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f25e6251bf23ca02</li>
        <li>Upwork Job ID: 1719482053696036864</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
I'm 99% sure we already have an almost exact same issue for this that was called a deploy blocker yesterday, and we decided it didn't need to be - i'll look for it very soon

**Comment by Beamanator** [comment]
Yeah this one - https://github.com/Expensify/App/issues/30644 - closing this issue & removing blocker
