### ISSUE TITLE
[$500] [Wave 6: Workspace Chats] Refactor ReportUtils.requiresAttentionFromCurrentUser

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#30668]
Right now, ReportUtils.requiresAttentionFromCurrentUser can take either an option item or a report. This leads to some confusing to follow logic which is dependent on what type of argument its taking. Ideally we can clean this up to either: 

1. take a specific type, not both 
2. use clearer logic depending on the type
3. something else
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b604f4627d28c77</li>
        <li>Upwork Job ID: 1724144016716673024</li>
        <li>Last Price Increase: 2023-11-13</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by puneetlath** [comment]
@waterim can you please post a proposal with your general planned approach for us to agree on before starting the PR? Thanks!

**Comment by waterim** [comment]
Sure, thank you, one question 
2. use clearer logic depending on the type
3. something else

Do we have some specific requirements for these steps?

**Comment by puneetlath** [comment]
Nothing thought through. Just that right now the function is confusing because it is in ReportUtils, but is technically called with both reports and optionItems. And reports and optionItems don't have all the same properties and that makes the code both more confusing and more likely to have a bug introduced. And we seem to already have run into at least one bug as a result.

**Comment by puneetlath** [comment]
Ah no it isn't currently, sorry.

**Comment by waterim** [comment]
I have two ideas for this issue: 
1. We can create two different functions to handle reports and options 
```javascript
function requiresAttentionForOption(option, parentReportAction = {}) {
    if (!option || isArchivedRoom(option) || isArchivedRoom(getReport(option.parentReportID))) {
        return false;
    }
....Rest of the code
}

function requiresAttentionForReport(report) {
    if (!report || isArchivedRoom(report)) {
        return false;
    }
....Rest of the code
}
``` 
With this solution we will be protected from random regressions in the future related to neither `OptionItem` nor `Report` fields.

2. We can create some variable like `isOption` or `isReport` and use it as a verification for some `Option` or `Report` specific checks. for this variables we can use some specific fields, for example `parentReportAction` only exists in `Option`, and `Report` doesn't have it
With this solution we can still use one function for both `Option` and `Report` since only few things are different here, but if needed we can add a specific verification, like for example we need to do for `isWaitingForAssigneeToCompleteTask` function

3. Third solution will be to use Type guards from Typescript together with union types to define isReport or isOption , but we don't know when this file will be migrated

**Comment by ckuhn** [comment]
I propose to follow a simple three step process to refactor this method. I will add any tests necessary as I go.

1: Create duplicate functions for optionItems and reports and call those for the corresponding type. Ensure tests pass.

2: Methodically remove logic from each function that is unrelated to the type it is handling. Ensure tests pass.

3: Check for unused fields, especially in optionItem that are populated from report, to reduce type cross-contamination. Ensure tests pass.

**Comment by ckuhn** [comment]
Contributor details
Your Expensify account email: connor.kuhn@kuhnclan.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012fc16b2d65479dcc

**Comment by waterim** [comment]
@puneetlath Yes, ReportUtils and with TS we can check which type we are using with Type guards and make some option/report specific conditions.
Same can be done with getting option/report specific object field like: `parentReportAction`. 

```javascript
const isOption = !!option.parentReportAction
``` 
Or just to split this function for reports and options

**Comment by puneetlath** [comment]
@sobitneupane what do you think?

**Comment by sobitneupane** [comment]
@waterim Which logics are shared between optionItem and report? What are the distinct logics for each?

> const isOption = !!option.parentReportAction

I believe relying on a field such as `parentReportAction` to ascertain `isOption` is not ideal. Instead, I would prefer passing isOption as a function argument if its value can be determined in advance.

To get rid of confusing logic, the best way to go will be splitting the function.

**Comment by puneetlath** [comment]
The downside of two separate functions is that they need to use the same logic and have the potential to get out of sync. So I think I like the typescript types approach and we do it once https://github.com/Expensify/App/pull/29012/files is done. What do y'all think about that?

**Comment by sobitneupane** [comment]
@puneetlath I agree. We can just wait for https://github.com/Expensify/App/pull/29012 to get merged. It is being actively worked on.

**Comment by puneetlath** [comment]
Still holding on #29012

**Comment by puneetlath** [comment]
ReportUtils to TS was merged, so you're unblocked from going forward here @waterim

**Comment by puneetlath** [comment]
How's this going @waterim?

**Comment by waterim** [comment]
@puneetlath Updated today, waiting for C+ answers

**Comment by puneetlath** [comment]
Ok great.

**Comment by puneetlath** [comment]
@sobitneupane @waterim everything is done here right? If so, all that is left is to pay @sobitneupane for C+?

**Comment by sobitneupane** [comment]
Yep @puneetlath.

**Comment by puneetlath** [comment]
Great. Please request on NewDot. 

Payment summary: 
- [sobitneupane](https://github.com/sobitneupane) C+ - $500

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on comment above.
