### ISSUE TITLE
[ECard Settings] 🐛 Fraud is missing RBR on Settings Page + Update Banner UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#30677]
### 1) Update Fraud UI

**Before / After**
<img src="https://github.com/Expensify/App/assets/38015950/3df5a786-f6ab-42b1-a9d9-b3b31afea9dd" width="400">

**Larger Version of Individual/Domain Fraud UI**
<img src="https://github.com/Expensify/App/assets/38015950/0f8ec0c7-101b-46a9-8d82-7fa34ab87351" width="250">  <img src="https://github.com/Expensify/App/assets/38015950/af6aa74c-08f6-4fbc-b9a5-1922323fe790" width="250">

[figma](https://www.figma.com/file/SXK8nOKQZqVd8pE67fKeOL/Wave-5%3A-Expensify-Card?type=design&node-id=3373-3923&mode=design&t=WdkNoC8kk6nH72LQ-0)

### 2) Add Red Brick Road Indicator to Settings Page as Well

<img width="543" alt="image" src="https://github.com/Expensify/App/assets/38015950/5a1ddcf4-93e2-4cf4-b97e-319bbaf586ae">

### Original Report

Coming from https://expensify.slack.com/archives/C03U7DCU4/p1698775268026679

![Image](https://github.com/Expensify/App/assets/38015950/c45df134-e051-400f-a864-a0acba89e525)

- There's no RBR leading to it, just that red dot there

**Comment by grgia** [comment]
@pasyukevich could you please take a look into this one as a follow up to your PR?

**Comment by pasyukevich** [comment]
@grgia Could you share test data with which I can reproduce this?

**Comment by grgia** [comment]
@pasyukevich yep, here's example data - could you test with this cardList?

```
{
  "1": {
    "availableSpend": 1000000,
    "bank": "Expensify Card",
    "cardID": 1,
    "cardholderFirstName": "FirstName",
    "cardholderLastName": "LastName",
    "domainName": "expensify.com",
    "fraud": "individual",
    "isVirtual": false,
    "lastFourPAN": "1234",
    "state": 3
  },
}
```

**Comment by pasyukevich** [comment]
I'm looking at it. Tomorrow I will post an update

**Comment by pasyukevich** [comment]
@grgia Could you describe expected behavior? (According to the doc: 

> For each card with detectedIndividualFraud, we will display a suspicious transaction banner and “Review transaction”

) From the point that I understand, we need to show a banner in this case, since one of the cards has individual fraud

**Comment by grgia** [comment]
PR merged

**Comment by grgia** [comment]
@pasyukevich apologies for the confusion.
the expected behavior is that there will also be a red dot on the card in the `assigned cards` section leading to this page

**Comment by pasyukevich** [comment]
@grgia  I've checked with the test data - I see the red dot on the card in the `assigned cards section`

https://github.com/Expensify/App/assets/23215729/76fe6380-e2d8-40c2-afe2-27eb86f3f772

**Comment by grgia** [comment]
@pasyukevich I've started a slack convo here- https://expensify.slack.com/archives/C05DWUDHVK7/p1700490527549039

I think the original conversation may be referring to a red dot indicator on the settings page as well. 

![image](https://github.com/Expensify/App/assets/38015950/f2657f25-ec97-45b6-a93d-574c2083b60a)

versus

![image](https://github.com/Expensify/App/assets/38015950/6587de3d-8ec8-4c8e-9bee-1265562a3edf)


I will update if we decide to add it to the wallet menuitem

**Comment by grgia** [comment]
@pasyukevich I've updated the description for what needs to be updated for this flow. We've decided to change the UI of the banner/button as well. Given the scope are you still able to take this one on?

**Comment by pasyukevich** [comment]
@grgia Yes, I will take it

**Comment by grgia** [comment]
@pasyukevich fantastic, please let me know if you have any questions

**Comment by pasyukevich** [comment]
No overdue, work in progress

**Comment by grgia** [comment]
@pasyukevich do you have an update on this issue?

**Comment by pasyukevich** [comment]
@grgia preparing the PR

**Comment by eVoloshchak** [comment]
The [PR](https://github.com/Expensify/App/pull/32106) for this was [deployed to production on Dec 14](https://github.com/Expensify/App/pull/32106#issuecomment-1856051429), this is ready for payments and we can close this out

**Comment by eVoloshchak** [comment]
@grgia, could you post a payment summary please?

**Comment by grgia** [comment]
@CortneyOfstad would you mind helping out with $500 C+ review payment to @eVoloshchak for the review of https://github.com/Expensify/App/pull/32106

**Comment by CortneyOfstad** [comment]
Sorry for the delay here! So it shows that @eVoloshchak gets paid via NewDot, so sharing the payment summary below!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@eVoloshchak (reviewer) — to be paid $500 via NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.

**Comment by grgia** [comment]
Closing as completed
