### ISSUE TITLE
[Awaiting Payment][$500] [Wave 6: Categories] Category is not selected when refreshing category selection page and selecting it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat > + > Request money > Manual.
3. On the confirmation page, click Category.
4. Refresh the page.
5. Select a category.

## Expected Result:
The category is selected.

## Actual Result:
The category is not selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3a0102f6-765b-4ef4-9235-f2dd3a3a119f

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d27ff5e9974105ea</li>
        <li>Upwork Job ID: 1719688099307413504</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27679337</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by erquhart** [comment]
@kbecciv I'm not able to reproduce this, are there any other requirements beyond what's in the steps?


https://github.com/Expensify/App/assets/2112202/e46e6314-df67-440d-90fa-225bad714317

**Comment by DrLoopFall** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Category is not selected after refreshing the category selection page

### What is the root cause of that problem?

We are clearing the category when the request confirmation page is mounted, so when the category selection is refreshed and used goes back to the confirmation page, it is mounted as a new page, and the selected category is cleared.
https://github.com/Expensify/App/blob/c8e7ee5718730aef7eaeec052ee5c97e4284ff53/src/pages/iou/steps/MoneyRequestConfirmPage.js#L84

### What changes do you think we should make in order to solve the problem?

Clearing the selected category only on navigation, instead of on mount would solve the issue.

**Comment by zanyrenney** [comment]
readding the labels to get a new c+

**Comment by zanyrenney** [comment]
bump @Gonals @parasharrajat

**Comment by zanyrenney** [comment]
bumping here - https://expensify.slack.com/archives/C01GTK53T8Q/p1700048654257029

**Comment by zanyrenney** [comment]
**Payment summary**

@dukenv0307 - paid $500 via Upwork.
@parasharrajat to request $500 on NewDot.

Thanks for the patience here!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
