### ISSUE TITLE
[HOLD for payment 2023-12-21] [$500]  [Wave 6: Categories] - Unexpected error when requesting money with a very long category in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30264

## Action Performed:
Precondition:
The following long category is set up on OldDot.

Meals: Level 2 nesting and a category name that could span two lines: Level 3 nesting and a category name that could span two lines: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

1. Go to workspace chat > + Request money > Manual.
2. Create a money request with no category.
3. Note that the request is successful.
4. Repeat Step 2 with a very long category name from the precondition.

## Expected Result:
The request is successful.

## Actual Result:
The request is not successful. It shows an unexpected error message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a02cdb5f-5a93-4c53-a8b1-2aa27c20eee2

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cfdce1c85555976</li>
        <li>Upwork Job ID: 1719689005334507520</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27576838</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment]
I was able to reproduce this and I confirm that the `RequestMoney` call fails with the following error:
<img width="305" alt="Screenshot 2023-11-01 at 21 53 58" src="https://github.com/Expensify/App/assets/56457735/d487125a-9a4f-4a42-8350-e9ffc2600ad5">

Which means that the long category created on OldDot turns out to be exceeding maximum size when the NewDot's `RequestMoney` is called with that category. I think this is a BE related issue.

**Comment by NisargDeveloper** [comment]
Hey there shouldn't be any proper handling for requesting money with category. We can use if and AND condition to solve this issue. Let me know if you need a help. 

Contributor details
Your Expensify account email: nisarg.k.amin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01149c9659573bccce

**Comment by stephanieelliott** [comment]
Hey @NisargDeveloper if you'd like to work on this, can you please post a proposal per the instructions in https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?

**Comment by NisargDeveloper** [comment]
hey! @stephanieelliott I tried to reproduce it. I thinking I'm missing step. May I know how can I setup Old Dot?.

**Comment by stephanieelliott** [comment]
@NisargDeveloper can you clarify which step you are getting hung up on? Perhapd @kbecciv can help clarify

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by kbecciv** [comment]
@NisargDeveloper Here is instruction how to set up Category in Olddot 
![image](https://github.com/Expensify/App/assets/93399543/84886a42-4943-4bde-ac76-deb52d64fe6a)

**Comment by NisargDeveloper** [comment]
Hey I cannot see the Create Policy on the left side? Please see the attached ss.

![image](https://github.com/Expensify/App/assets/76931098/4bde9c9a-b126-4123-948c-e00926b2c00f)

**Comment by mountiny** [comment]
Assigning @rezkiy37 as they worked on these features and will handle this update too

**Comment by rezkiy37** [comment]
So, guys, looks like we have a collision regarding the maximum length of name for a category.

We can add a category up to 256 symbols on the **OD**, 257 symbols are too long. However, when we create a money request on **ND**, the backend does not accept a category with 256 symbols name.

<img width="1082" alt="ND" src="https://github.com/Expensify/App/assets/57314631/90a35b17-8dea-4c1d-8f4f-8c5249108b90">

https://github.com/Expensify/App/assets/57314631/bfe18c07-d07e-4f78-ae66-c1582fdac8f1

Based on this, looks like we need to unify backend restrictions for name's length.

cc @mountiny

**Comment by mountiny** [comment]
Sounds like we can then just lower the length allowed in new dot right?

**Comment by rezkiy37** [comment]
@mountiny, can we decide what's exactly the maximum length for names? After, we can add a FE validation for the input.

**Comment by mountiny** [comment]
>  can we decide what's exactly the maximum length for names? After, we can add a FE validation for the input.

Maximum for categories? Is there any in OldDot? If yes, lets use that one and add FE validation for it.

**Comment by rezkiy37** [comment]
What? I don't understand. One hour ago I could set a category with 256 symbols.

<img width="1496" alt="Screenshot 2023-11-08 at 19 16 55" src="https://github.com/Expensify/App/assets/57314631/c2f3674e-bf2d-46f2-9bc4-11f253ecc057">

**Comment by rezkiy37** [comment]
Ah, OD restricts 255 for one category. I mean for example there is "Parent: Child" and "Parent" **OR** "Child" shouldn't be longer than 255, but together they could be longer 🤯 😅

**Comment by mountiny** [comment]
there was inconsistency with how we handle these in the backend and I have created a PR which shoul update that however weirdly enough the correct request param size is smaller than what we had there in a first place :D 

Lets see if this will help but could you also share whats the payload of the category when you are editing this?

**Comment by rezkiy37** [comment]
@mountiny, that's a screenshoot how the app sends a request to update a category.

<img width="1722" alt="Screenshot 2023-11-13 at 13 52 45" src="https://github.com/Expensify/App/assets/57314631/9e9d93c2-a693-412a-af95-17e1130841bd">

**Comment by rezkiy37** [comment]
Melvin, we are waiting on backend changes to verify that the bug has been fixed.

**Comment by mountiny** [comment]
Seems like the passed data is fine, lets see how this works after the deploy

**Comment by rezkiy37** [comment]
Melvin, no "overdue" 😅

**Comment by mountiny** [comment]
@rezkiy37 coul dyou test this out? the backend change has been deployed

The overdue now only reacts and counts to @Ollyws

**Comment by rezkiy37** [comment]
@mountiny, I've tested on the staging and production. Unfortunately, the bug is still here. I reset cache, no luck.

https://github.com/Expensify/App/assets/57314631/a60eeb81-622f-4ffc-b699-4c825e8c9cff

<img width="916" alt="Request" src="https://github.com/Expensify/App/assets/57314631/8057b823-9a82-446f-aa9b-55af34e5e4b7">

<img width="1728" alt="Response" src="https://github.com/Expensify/App/assets/57314631/d79b893d-deba-4a78-a8b4-d14435d3fac5">

**Comment by rezkiy37** [comment]
@mountiny, just a friendly reminder about - https://github.com/Expensify/App/issues/30683#issuecomment-1812556566.

**Comment by mountiny** [comment]
Posted in [Slack](https://expensify.slack.com/archives/C02MW39LT9N/p1700156766753289?thread_ts=1699666699.788659&cid=C02MW39LT9N) to get some volunteers to fix this one, we will have to do some debugging

**Comment by rezkiy37** [comment]
Waiting on some volunteers to fix this on the backend side.

**Comment by aldo-expensify** [comment]
> Re-pinging for volunteers on this today

I can work on this

**Comment by aldo-expensify** [comment]
> Meals: Level 2 nesting and a category name that could span two lines: Level 3 nesting and a category name that could span two lines: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

I don't really understand these instructions, in Old dot, when I add a new category, I just see one input:

<img width="378" alt="image" src="https://github.com/Expensify/App/assets/87341702/267fb677-d0be-49ad-a20b-4e4c3a92ac3e">

Is this saying I should add 2 categories:

- Meals
- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
?

**Comment by puneetlath** [comment]
Every time you add a colon it makes it a sub-category. This: 

<img width="1001" alt="image" src="https://github.com/Expensify/App/assets/1371996/185a8ed0-6b2c-4f09-9e6c-7584286aa120">

Becomes this on OldDot: 
<img width="533" alt="image" src="https://github.com/Expensify/App/assets/1371996/231b038f-08bb-428d-847f-88ed529d0f46">

This on NewDot: 
<img width="397" alt="image" src="https://github.com/Expensify/App/assets/1371996/579c23ad-7cfb-43ab-bf81-adbcf4701cde">

**Comment by aldo-expensify** [comment]
> Every time you add a colon it makes it a sub-category. This:

🤯 that is new to me, thanks for explaining!

**Comment by rezkiy37** [comment]
Melvin, waiting on some news from the backend side by @aldo-expensify.

**Comment by rezkiy37** [comment]
No update.

**Comment by aldo-expensify** [comment]
Sorry, I haven't been able to check again on this, I'll try to come back as soon as possible!

**Comment by aldo-expensify** [comment]
I noticed that this is also broken for OldDot. I'm asking in slack to confirm the path we want to take to fix this: https://expensify.slack.com/archives/C02MW39LT9N/p1701396084292819

**Comment by aldo-expensify** [comment]
We can't increase the category max length beyond 255, so we are going with the solution of improving the error feedback.

Working on improving the error returned by the backend, it feels a bit junky the experience because the modal closes and then an error appears in the chat. I think a better and less confusing UX is to have the limit as a form validation that won't allow you to submit the expense.

**Comment by aldo-expensify** [comment]
I put up a [draft PR.](https://github.com/Expensify/App/pull/32394) The solution looks like this:

https://github.com/Expensify/App/assets/87341702/ef51e164-6c43-4e0b-a0f6-3cab99663d8f

Please let me know if you think that is fine to finish the PR (description/videos).

**Comment by aldo-expensify** [comment]
> isn't there a way to align the limitation on the backend side?

I'm guessing you are referring to rejecting in the backend (and frontend) a user creating a category longer than 255 because they won't be able to use it anyway.

I think both things can be done independently: the validation [proposed above](https://github.com/Expensify/App/issues/30683#issuecomment-1836971159) and disallow creating long categories.

The problem with implementing the second part is that categories can be added manually and also automatically from integrations with external services. The part of the integrations can get complicated if we want to provide some feedback about why some categories didn't load. Also, we would have to think about what would we do with long categories that are already in the database.

Considering the complexity of that second part, and that this is an edge case (someone very very very rarely will add such long category), I don't think it is worth it to try the second part and we should only do the proposed front end validation when using the category.

**Comment by aldo-expensify** [comment]
Made PR ready for review: https://github.com/Expensify/App/pull/32394

**Comment by rezkiy37** [comment]
Got you, makes sense.

**Comment by stephanieelliott** [comment]
This issue didn't update but the PR was pushed to prod on 12/14. Adjusting title to remember to issue payment after 7 day hold.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor:  no payment, @rezkiy37 with Callstack
 - Contributor+:  $500, to pay via Upwork - @Ollyws I've extended the offer to you on Upwork, can you please accept?
 
 Upwork job is here: https://www.upwork.com/jobs/~018cfdce1c85555976

**Comment by stephanieelliott** [comment]
All paid, thank you!
