### ISSUE TITLE
[$500] Room- Room name changed is not updated in admin comment section

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab--start chat
3. Tap Room
4. Enter all details and tap Create Room
5. Tap on the header
6. Tap Members---Invite
7. Invite any user to the room
8. Tap settings
9. Tap room name and change it
10. Go to Workspace admin room in which "Room" was created
11. Note the comment of user invited to room
12. Note the room name in LHN

## Expected Result:
Room name changed must be updated in admin comment section and LHN

## Actual Result:
Room name changed is not updated in admin comment section and LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a6183027-5614-46a1-9395-1187e4b92f9e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e512ffd790127318</li>
        <li>Upwork Job ID: 1719698370951098368</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27554495</li>
<li>dukenv0307 | Contributor | 27554496</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @techievivek</details>

**Comment by dhruvin-rv** [comment]
@dukenv0307 we are getting updated room name report and invite report in different api calls and both are being stored in different keys in onyx. i have doubts if it will be possible to handle this only from frontend.

**Comment by kadiealexander** [comment]
@hoangzinh any thoughts on the proposal above?

**Comment by kadiealexander** [comment]
Ooh good catch @hoangzinh, yes we should!

**Comment by kadiealexander** [comment]
@hoangzinh any updates? Looks like the PR hasn't had any action for a month.

**Comment by kadiealexander** [comment]
Thanks @hoangzinh!

**Comment by kadiealexander** [comment]
Noting that I'm on leave from tomorrow until Jan 8th and will check in on my return.

**Comment by jasperhuangg** [comment]
I don't think this is worth fixing to be honest. It makes sense that the change log for the room matches the name of the room when the person was invited.

We have other change logs that reflect the name of the room being updated.

**Comment by techievivek** [comment]
Thanks for your input, @jasperhuangg. I agree with your thoughts. This should be fine as long as it links correctly to the room and the changes are recorded.

**Comment by techievivek** [comment]
@kadiealexander, Can we please review the compensation here since a PR was already raised and reviewed?

**Comment by kadiealexander** [comment]
[Guidelines](https://stackoverflowteams.com/c/expensify/questions/8590) say they're paid in full! 

Payouts due:

Contributor: $500 @dukenv0307
Contributor+: $500 @hoangzinh

Upwork job is [here](https://www.upwork.com/jobs/~01e512ffd790127318).
