### ISSUE TITLE
[$500] Chat - Unable to scroll up to see chat history when sending 30 messages in a new chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
2. Open chat with user that has no prior chat
3. Send 30 messages
4. Scroll up

## Expected Result:
User is able to scroll up to see the entire chat history without issue, because it is a small chat with 30 messages

## Actual Result:
User is unable to scroll up to see the entire chat history

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6a60efee-23d7-4507-9fe2-0df9aa7023d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6570b10d3793a25</li>
        <li>Upwork Job ID: 1719697237956702208</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
^^ Good catch!

**Comment by strepanier03** [comment]
Okay, since this is a dupe I'll close this out. Nice catch @bernhardoj and thanks for confirming @fedirjh.
