### ISSUE TITLE
[HOLD for payment 2023-12-04] [Wave 6: Bottom Up] Implement bottom up flow creating collect workspace and converting IOU to Expense report

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30702]
As part of https://github.com/Expensify/Expensify/issues/324914 and [Basic Bottom up flow for Collect plan](https://docs.google.com/document/d/1pFEepu3ih7_NxPxudIXMa5KMF8POp4IM-ZIcANS8srY/edit) design doc, implement a following section of the doc:

https://docs.google.com/document/d/1pFEepu3ih7_NxPxudIXMa5KMF8POp4IM-ZIcANS8srY/edit#bookmark=id.303ggp6g7vfv

Will required Auth, Web and App PRs.

- Auth https://github.com/Expensify/Auth/pull/9075
- Web https://github.com/Expensify/Web-Expensify/pull/39470
- App https://github.com/Expensify/App/pull/30582
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018902f39814caa07e</li>
        <li>Upwork Job ID: 1719722776161996800</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by mountiny** [comment]
Working on this one as we reevalate the priorities

**Comment by CortneyOfstad** [comment]
Paid! Thanks @akinwale!

## Payment Summary

- @akinwale paid $500 via Upwork as Reviewer
