### ISSUE TITLE
[HOLD for payment 2023-11-28][$500] Chat - New user should not be suggested when add @ into 1:1 message composer offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.94-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB icon and select new chat
3. Enter new email and create new chat with User A
4. Into chat composer type @ and start typing User's A e-mail

## Expected Result:
The suggestion list shows User A e-mail

## Actual Result:
User A is not suggested when add @ into 1:1 message composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d957e2fc-6441-42ef-81e3-9accde3a621d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ce070dae84873af</li>
        <li>Upwork Job ID: 1719758999805837312</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27671110</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
@Santhosh-Sellavel I think we have some proposals above to review!

**Comment by adelekennedy** [comment]
@Santhosh-Sellavel bump on the proposals above

**Comment by Santhosh-Sellavel** [comment]
@adelekennedy 

Can you check and confirm the following what should we do here?

1. Seems like the current behavior is expected. 
2. @dukenv0307 is pointing out that the behavior is inconsistent when the user is in offline mode.

Can you confirm what's expected behaviour for the both case?

**Comment by adelekennedy** [comment]
hmm I think this is expected (i didn't make this one external so to be honest was just pushing this forward) I agree we should make them consistent and default to the online mode

**Comment by Santhosh-Sellavel** [comment]
>  I agree we should make them consistent and default to the online mode

Then @dukenv0307's [proposal](https://github.com/Expensify/App/issues/30720#issuecomment-1789340454) here LGTM!

C+ Reviewed
🎀 👀 🎀 

@adelekennedy Can you update the issue description also please to match the expected OP, thanks!

**Comment by dangrous** [comment]
If this is expected behavior (seems weird to me?) then this solution works to make it more consistent!

Shouldn't we show the new user as a mention? I guess we don't really need it since it's a 1:1 chat... Okay I've talked myself out of it, I guess it's fine though I'm not 100% confident haha

**Comment by dangrous** [comment]
Aw shoot I messed that up by accidentally clicking "Clear Assignees" - let me see if I can get that fixed

**Comment by dangrous** [comment]
okay i think that worked

**Comment by dangrous** [comment]
This hit production on 11/21 (Eastern time), so we should expect payment on 11/28. Not sure why the automation didn't trigger, I'll give it a little time and we can update the issue title manually if needed if it never pings

**Comment by adelekennedy** [comment]
### Payouts due:

Contributor: $500 @dukenv0307 
Contributor+: $500 @Santhosh-Sellavel 


Upwork job is [here](https://www.upwork.com/jobs/~018ce070dae84873af).

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on comment above.
