### ISSUE TITLE
[Wave 6: Workspace Chats] GBR shown on chats that shouldn't have them

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#30775]
Context https://expensify.slack.com/archives/C049HHMV9SM/p1698924304893529

Happening on staging web, but not on prod.
I have 2 chats with GBR and nothing to do on them.
@vitHoracek  pointed out it is probably due to this change https://github.com/Expensify/App/pull/30655/files#diff-3258457b3b73b3f6fde322dfd4d925501f57daeee25e2ae30e671a53460aa06cR249 in App, but that the real bug is probably in the backend.

**Comment by iwiznia** [comment]
The PR we could revert is this one https://github.com/Expensify/App/pull/30655/ but waiting on @puneetlath to chime in

**Comment by puneetlath** [comment]
Two problems: 
1. We set `hasOutstandingChildRequest` for IOU reports with a total of $0 
2. There exist old IOU reports that don't have a parentReportActionID so they don't show up in the DM even though they exist

**Comment by puneetlath** [comment]
I'm removing the deploy blocker label since this is actually an Auth issue.

**Comment by puneetlath** [comment]
https://github.com/Expensify/Auth/pull/9110 is merged. I'll look into the ghost IOUs tomorrow!

**Comment by puneetlath** [comment]
Auth PR got deployed. Will look into the orphans next.

**Comment by puneetlath** [comment]
For the orphan IOUs, I want to first just determine the scale of the problem. Query request here: https://github.com/Expensify/Expensify/issues/333810

**Comment by puneetlath** [comment]
There are 31762 distinct reports that have a parentReportID but no parentReportActionID 🤦🏾

**Comment by puneetlath** [comment]
It doesn't seem like anyone is experiencing this anymore since we made the update to ignore $0 reports. So I think we can close this out. Feel free to reopen if I'm mistaken!
