### ISSUE TITLE
[HOLD for payment 2023-11-13] Assign task – Unable to assign subtask in task report when create task in 1:1 DM.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. Open a 1:1 chat
4. Navigate to the "Assign Task" section
5. Enter the task title and assigned it
6. Click "Confirm Task" to create the task
7. In the task report - Click + and select "Assign Task" again to create a sub-task

## Expected Result:
"Assign Task" option appears to create a sub-task

## Actual Result:
"Assign Task" option is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7d41d93-bb13-4c3f-b26d-05384d67d94c

Production:

https://github.com/Expensify/App/assets/78819774/329954c1-e5d4-4996-b741-7cbb295f8c87

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
@bernhardoj that fix looks great! Are you able to spin up a PR in the next hour or two if I assign you now?

**Comment by Beamanator** [comment]
@bernhardoj Iff you are up for submitting a PR soon please do - I'll assign you when I get back online in a few hours

**Comment by Beamanator** [comment]
Great, thanks!! Please let me know when videos on all platforms are ready,
then I will review 🙏

**Comment by Beamanator** [comment]
@hoangzinh thanks for asking, I think I'm good here since it's a nice and small PR 🙏

**Comment by Beamanator** [comment]
CPing fix

**Comment by Beamanator** [comment]
Fix should be working in staging, NAB

**Comment by dylanexpensify** [comment]
Nice! Waiting for prod

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment Summary: 
- Contributor: @bernhardoj $750 

[Upwork job invite sent](https://www.upwork.com/jobs/~01e7d390f961d9f7bb)! Please apply!

**Comment by chiragsalian** [comment]
Anything pending here @dylanexpensify or can we close this out?

**Comment by dylanexpensify** [comment]
paying out @bernhardoj! Offer sent!

**Comment by chiragsalian** [comment]
@dylanexpensify, anything pending here or can we close this out?

**Comment by dylanexpensify** [comment]
all done!
