### ISSUE TITLE
Request Money - Selected date is correct but another one is highlighted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29984

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Tap on "+" button.
3. Tap on "Request money".
4. Select "Manual".
5. Enter any amount and tap "Next".
6. Tap on "Show more".
7. Tap on the date field.
8. Tap on any enabled day.

## Expected Result:
The selected day should be highlighted.

## Actual Result:
The day highlighted is the day before the user is actually selecting.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/20886f88-1897-4436-b7f2-18e0f09eadf1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
This happens on web too

**Comment by jasperhuangg** [comment]
This was caused by this change

https://github.com/Expensify/App/commit/9d1cd9d436023ac07fde031abc93a3f2eecb54d3#diff-2ac6406c05e8211dc37aed33a99f9bf84f37db429e9c242950397d160b07bc1bR208
