### ISSUE TITLE
[$500] Workspace- Workspace chat disappears from LHN after creating a workspace expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > Create a new workspace.
3. Go to workspace chat > + > Request money
4. Create a manual request

## Expected Result:
The workspace chat will not disappear in LHN

## Actual Result:
The workspace chat disappears from LHN after creating a workspace expense until the page is refreshed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00b18b76-3bee-460d-86cc-6628d7cb9156

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4a63bcd5b8e2425</li>
        <li>Upwork Job ID: 1720187611058442240</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by amyevans** [comment]
Seems quite similar to https://github.com/Expensify/Web-Expensify/pull/39488, I can take a look

**Comment by amyevans** [comment]
PR is up: https://github.com/Expensify/Web-Expensify/pull/39529

**Comment by eVoloshchak** [comment]
Not overdue, looks like this is being worked on in https://github.com/Expensify/Web-Expensify/pull/39529 (don't have access to the repo, but based on my tests on staging the bug is still present)

**Comment by strepanier03** [comment]
Thank you @eVoloshchak!

**Comment by strepanier03** [comment]
Since https://github.com/Expensify/Web-Expensify/pull/39529 is still open, I'm going to put this on HOLD and move to weekly. Next week I'll check it and we can put it back to daily if the PR is deployed and the issue continues.

**Comment by amyevans** [comment]
The PR has deployed, we should be all set to close!
