### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] LHN - Green dot for money request is still displayed in spite of having deleted the workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user must have created a workspace and have made a money request from another account (account B) to that workspace.

1. Go to Settings.
2. Tap on "Workspaces".
3. Select the workspace where the money request have been made.
4. Tap on the three dots menu.
5. Tap on "Delete workspace" and confirm.
6. Return to LHN.

## Expected Result:
The green dot on the workspace chat with account B should disappear.

## Actual Result:
The green dot on the workspace chat with account B is still displayed in spite of having deleted the workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/23c9e7c8-6d92-44ed-b085-43554873708d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101e78cc19704d3a6</li>
        <li>Upwork Job ID: 1720360448725458944</li>
        <li>Last Price Increase: 2023-11-03</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27502261</li>
</ul></li>
    </ul>
</details>

**Comment by Beamanator** [comment]
Thanks for your two very quick proposals! @tienifr since you submitted first, let's go with your fix please - can you please submit a PR & test ASAP? 🙏

**Comment by Beamanator** [comment]
@thesahindia FYI i think this is going to be a small enough PR that we shouldn't need a C+ to review 🙏

**Comment by Beamanator** [comment]
Fix should be working in staging, NAB

**Comment by cristipaval** [comment]
This was a deploy blocker found by running the regression tests, so there's no need to create/update anything. Melvin already automatically commented on the offending PR.

**Comment by peterdbarkerUK** [comment]
Paid and job closed, thanks @tienifr 

- Paid @tienifr $500 for contributor role.
