### ISSUE TITLE
[ECard Transactions] Fix EReceipt Hash

### ISSUE THREAD

**Issue by grgia** [Expensify/App#30825]
Fix the logic for defaulting when ""

**Comment by jjcoffee** [comment]
@grgia Mind adding the `Bug` label here so payment automation works? Thanks!

**Comment by sonialiap** [comment]
Joel asked to add the `awaiting payment` label [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1699866656160269). Looks like the PR has hit prod on Nov 10 so it should be ready for payment on the 17th. But I'll let @MitchExpensify confirm and add labels as appropriate 🥳

**Comment by MitchExpensify** [comment]
This is paid! https://github.com/Expensify/App/issues/24946

**Comment by jjcoffee** [comment]
@MitchExpensify I think that's a different issue, this is [the PR](https://github.com/Expensify/App/pull/30822) for this one.

**Comment by MitchExpensify** [comment]
Ok, sorry about that! So the idea is to use this issue to track payment of $250 for [this PR](https://github.com/Expensify/App/pull/30822), is that right?

**Comment by jjcoffee** [comment]
No worries, thanks for reopening! Yeah I wasn't sure what to do otherwise when the automation fails as it did here :sweat_smile:  I think the payment would be $500 as that's the default price for an internal PR review, as far as I understand.

**Comment by MitchExpensify** [comment]
Cool, offer sent here! https://www.upwork.com/jobs/~0134f81a81ffe31846

**Comment by jjcoffee** [comment]
@MitchExpensify Thanks, offer accepted! :bow:

**Comment by grgia** [comment]
closing as completed! 

(@grgia testing something)
