### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] [Wave 6: Tags] Billable and Tag category are not spaced enough like other sections

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-condition: In employee account, must have enabled category, tag and billable option
1. Go to https://staging.new.expensify.com/
2. Tap on Employee Workspace
3. Tap plus icon and select request money
4. Tap Scan
5. Upload an image
6. Tap request
7. Tap on scan request created to open scan request details page
8. Tap on amount, description, merchant, date, category, tag (while tapping on each section, note the gap between the selected and next section)

## Expected Result:
There should be enough spacing between Tags (custom name-shahrukh khan) and Billable section.

## Actual Result:
While tapping on tag(custom name-shahrukh khan) section, there is no enough spacing between selected Tag(shahrukh khan) and Billable section. The selected tag section and Billable toggle box appears too close. There is no enough spacing like other sections.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/0312632f-dc49-45a9-a402-999327868793

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed40e13d720ed9c6</li>
        <li>Upwork Job ID: 1720351887160328192</li>
        <li>Last Price Increase: 2023-11-03</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27544000</li>
</ul></li>
    </ul>
</details>

**Comment by Li357** [comment]
Let's go with @tienifr here since I also prefer the consistency and it's part of the proposal already.

**Comment by bfitzexpensify** [comment]
Payment summary:

Contributor: @tienifr to be paid $500 via Upwork - ✅ 
C+: @parasharrajat to be paid $500 via manual request

BZ checklist complete, so we're all done here. Closing this one out.
