### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] IOU - Green dot in 1:1 DM in LHN does not disappear after paying the IOU offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. [User B] Request money from User A.
3. [User A] Go offline.
4. [User A] Pay the IOU requested by User B.
5. [User A] Go to LHN.

## Expected Result:
The green dot in 1:1 DM in LHN will disappear after paying the IOU.

## Actual Result:
The green dot in 1:1 DM in LHN does not disappear after paying the IOU offline. It only disappears after returning online.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/32e76d49-418f-4d4c-a3b2-fc8628d18704

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01310266fc6c713472</li>
        <li>Upwork Job ID: 1721559941023154176</li>
        <li>Last Price Increase: 2023-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 27548566</li>
<li>DylanDylann | Contributor | 27548568</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green dot in 1:1 DM in LHN does not disappear after paying the IOU offline

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/libs/actions/IOU.js#L2445

We don't reset hasOutstandingChildRequest to false in optimisticdata
### What changes do you think we should make in order to solve the problem?
We need to add hasOutstandingChildRequest to false in optimisticdata


### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
@DylanDylann that sounds good. Are you able to raise a PR asap?

**Comment by DylanDylann** [comment]
Oke I can raise now

**Comment by puneetlath** [comment]
How's it going @DylanDylann?

**Comment by DylanDylann** [comment]
@puneetlath I am completing screenshot test

**Comment by puneetlath** [comment]
Ah yeah, sorry for any confusion. I'm moving a little quicker here since this is a deploy blocker.

**Comment by DylanDylann** [comment]
@puneetlath @cubuspl42 The PR is ready for review https://github.com/Expensify/App/pull/30918

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
