### ISSUE TITLE
[HOLD for payment 2023-11-13] Expense - Workspace avatar and name change after creating a workspace expense

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30846]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Click + > Request money.
5. Create a manual request.

## Expected Result:
The workspace avatar and name in the expense preview match the actual workspace avatar and name.

## Actual Result:
The workspace avatar and name in the expense preview change. The name is changed to the requester name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/6de5cea6-d905-43a7-97a1-f5e8e491ea73

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
I'm guessing it might be related to https://github.com/Expensify/App/pull/30591 but I'm confirming (running into a crash prior to creating a money request on dev so haven't been able to test yet)

**Comment by dangrous** [comment]
nope, not #30591. Although the optimistic data IS weird, it's not related to this bug. Looking more.

**Comment by s-alves10** [comment]
Looks like a regression of [this PR](https://github.com/Expensify/App/pull/30342)

**Comment by s-alves10** [comment]
[This change](https://github.com/Expensify/App/pull/30342/files#diff-c7cedf6bd1e6af4654c7eb3d6ab6179f7a2ee5eb1c483a78d491674472cfeb4fR111) is the source of this issue

**Comment by dangrous** [comment]
Nicely found, @s-alves10 . Looks like changing that to:

```
    const primaryDisplayName = isWorkspaceActor ? displayName : ReportUtils.getDisplayNameForParticipant(actorAccountID);
```
works well, though I need to see if there are any unexpected consequences there

**Comment by lukemorawski** [comment]
@dangrous are you creating a PR for this, or should I prepare that quick fix PR?

**Comment by dangrous** [comment]
Yep, I grabbed it here - https://github.com/Expensify/App/pull/30342

**Comment by dangrous** [comment]
@joekaufmanexpensify - adding bug zero to assist with payment for reviewer of linked PR!

**Comment by joekaufmanexpensify** [comment]
Sure, happy to help!

**Comment by joekaufmanexpensify** [comment]
Only payment due here is $500 to @0xmiroslav for review of the internal PR. Paid via NewDot.

**Comment by joekaufmanexpensify** [comment]
@0xmiroslav could you please request $500 and confirm here once complete?
