### ISSUE TITLE
[$500]  IOU - The last member is focused when I remove members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.95.0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/r/8468866637847294
2. Log in
3. Click on the "2FAB" button
4. Click on the "Start chat" button
5. Add 4 different members to the group
6. Click on the "Create chat" button
7. Click on the "+" button in the Composer
8. Click on the "Split bill" button
9. Type any amount
10. Click on the "Next" button
11. De-select members

## Expected Result:
The first member should be focused

## Actual Result:
The last member is focused when I remove members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd999b36-6d48-4852-9bbc-a7224b3c5f57

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146fa688808f8044c</li>
        <li>Upwork Job ID: 1720449825686327296</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Sorry the same issue exported here https://github.com/Expensify/App/issues/30851
