### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Expense - Copy to clipboard on the system message for paid expense copies negative amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go offline
3. Create a workspace
4. Go to workspace chat > + > Request money
5. Create a manual request
6. Click Pay elsewhere
7. On the expense report, right click on the system message for paid expense
8. Click Copy to clipboard
9. Paste it on the composer

## Expected Result:
The correct paid amount is copied

## Actual Result:
The negative paid amountn is copied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e67e23b-3d0d-417a-98af-f84ffc5c2ad7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca92a3fdee611a1f</li>
        <li>Upwork Job ID: 1720467002745327616</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Copy to clipboard on the system message for paid expense copies negative amount 

### What is the root cause of that problem?
When paying money, we will create new optimistic data for new report action 
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/libs/actions/IOU.js#L2423-L2433

And we assigning iouReport.total to originalMessage.amount field. It causes this bug because iouReport.total is negative. Note that this bug doesn't happen online because BE overwrite reportActions.originalMessage.amount field to positive
### What changes do you think we should make in order to solve the problem?
We need to update optimistic data like BE reponse

https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/libs/actions/IOU.js#L2423-L2433

we should update 
```
        iouReport.total * -1,


```

### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment]
@dukenv0307 @DylanDylann Why is the message showing correctly but not with the copied text?

**Comment by DylanDylann** [comment]
@mollfpr When displaying the message. We manually convert negative value to positive value here
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/libs/ReportUtils.js#L1473

**Comment by DylanDylann** [comment]
@mollfpr Currently we have 2 places to save amount
1. iouReport.total (this field is nagative value, if we use this field we need to convert it to positive value)
2. reportActions.originalMessage.amount (the BE return this field is positive value but in the optimistic data we are setting a negative value for it. It caused this bug)

**Comment by mollfpr** [comment]
Sorry for the delay.

I just tested the issue again and confirmed that the cause explained by @DylanDylann is correct. API `PayMoneyRequest` response on the `reportActions_` is returning a positive value on the amount. Aligning the optimistic data seems the correct solution for me. So the [proposal](https://github.com/Expensify/App/issues/30856#issuecomment-1792736782) from @DylanDylann looks good!

🎀 👀 🎀 C+ reviewed!

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @mollfpr 

@Li357 can you confirm if this decision looks good? https://github.com/Expensify/App/issues/30856#issuecomment-1803743436

**Comment by Li357** [comment]
Taking a look now!

**Comment by Li357** [comment]
Agree with @DylanDylann's approach here, assigned! Thanks!

**Comment by DylanDylann** [comment]
@mollfpr The PR is ready for review https://github.com/Expensify/App/pull/31292

**Comment by Christinadobrzyn** [comment]
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

status - reviewing [PR](https://github.com/Expensify/App/issues/30856#issuecomment-1812030172)

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think we have an offending PR. This might be related to how the BE handles the params and returns it to FE with a negative value on request money.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the App and sign in
2. Go offline
3. Go to workspace chat > + > Request money
4. Create a manual request
5. Click Pay elsewhere
6. On the expense report, right-click on the system message for paid expense
7. Click Copy to the clipboard
8. Paste it on the composer
9. Verify that the correct paid amount is copied
10. 👍 or 👎 

@Christinadobrzyn Could you give the payment summary so I can do the manual request? Thank you!

**Comment by Christinadobrzyn** [comment]
Payouts due:

Issue Reporter: NA
Contributor: $500 @DylanDylann (in Upwork)
Contributor+: $500 @mollfpr (in NewExpensify)

Upwork job is [here](https://www.upwork.com/jobs/~01ca92a3fdee611a1f). Internal posting - https://www.upwork.com/ab/applicants/1720467002745327616/job-details

**Comment by Christinadobrzyn** [comment]
Paid @DylanDylann in Upwork based on this [payment structure](https://github.com/Expensify/App/issues/30856#issuecomment-1834667730)!  I think this can be closed!
