### ISSUE TITLE
iOS - Request money - Green CTA button in BNP and confirmation page has different placement

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat > + > Request money.
3. Enter amount and click Next.

## Expected Result:
The green button at the bottom should have a consistent placement in both BNP and confirmation page

## Actual Result:
The green button at the bottom does not have a consistent placement in BNP and confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/71f32e30-62d4-48d7-a7cd-9008eb81a325

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment]
I'm not seeing problem here...those two button LOOK consistent to me. @shawnborton are you seeing anything here? @lanitochka17 can you state a little more clearly what is not consistent and perhaps show the difference in the way the button looks on staging vs production?

**Comment by dannymcclain** [comment]
Posted this [in Slack](https://expensify.slack.com/archives/C07J32337/p1699289138861119?thread_ts=1699287046.249719&cid=C07J32337) but might as well post it here as well: it looks like the numpad + button on the amount screen got shifted down somehow and is now too close to the bottom, which is then causing it to be in a different spot than the request button.

Screenshots for reference: `Current` is as of today, `Previous` (how it should be I believe) is from a few weeks ago (iPhone 14).

![image](https://github.com/Expensify/App/assets/7516624/f8145beb-fae1-4118-8db7-5a7df06db868)

**Comment by joelbettner** [comment]
Very nice @ishpaul777! I see that the changes in that PR were tested for Android. Were they tested for iOS as well?

**Comment by joelbettner** [comment]
The changes got deployed to staging. I just tested it. All is good. I'm going to close this issue.
