### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Chat - The Emoji search field is focused when clicking on Modifier keys

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698154419378969

## Action Performed:
1. Go to any Chat
2. Blur the main composer(Unfocus the main composer)
3. Click on Modifier keys like 'cmd'. Notice that the composer is not focused
4. Click on the emoji in the composer to open the emoji section. 5. unfocus the emoji search field.
6. Click on Modifier keys like 'cmd'. Notice that the composer is focused

## Expected Result:
The Emoji search field is not focused when clicking on Modifier keys

## Actual Result:
The Emoji search field is focused when clicking on Modifier keys

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/e0369b18-6f5a-4563-865d-20b1836a1804

https://github.com/Expensify/App/assets/93399543/e871ded1-cd91-44ec-ad3b-5db07a5fe012

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a4c2fb2e41d1f1c</li>
        <li>Upwork Job ID: 1720501550008877056</li>
        <li>Last Price Increase: 2023-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27820697</li>
<li>daveSeife | Reporter | 27820699</li>
</ul></li>
    </ul>
</details>

**Comment by DrLoopFall** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Emoji search field is focused when clicking on Modifier keys

### What is the root cause of that problem?
 
We are currently focusing emoji picker's search input whenever a key is pressed, 
https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/EmojiPicker/EmojiPickerMenu/index.js#L325-L327

### What changes do you think we should make in order to solve the problem?

Only focus the search input if the user presses the keys which would add text to the input.

**Comment by dylanexpensify** [comment]
@robertKozik can we review these proposals today, please?

**Comment by robertKozik** [comment]
@dukenv0307  
> This should also be used:
> 
> ```
> // If a key is pressed in combination with Meta, Control or Alt do not focus
> if (keyBoardEvent.metaKey || keyBoardEvent.ctrlKey || keyBoardEvent.altKey) {
>     return;
> }
> ```
won't it prevent focus for typing special characters? f.e `€` is `option + 3`. I think this should focus both composer and picker as we cannot assume what user wanted to type exactly

**Comment by DrLoopFall** [comment]
@robertKozik 

Also preventing the Control key would break many things that are currently working when the input is not focused, like paste (`ctrl+v`), select all (`ctrl+a`), undo (`ctrl+z`), and others.

I think the best option would be not to focus the input if the user presses only the modifier keys (maybe also `keyBoardEvent.metaKey`), something like
```js
if (keyBoardEvent.metaKey || keyBoardEvent.key === 'Control' || keyBoardEvent.key === 'Shift' || keyBoardEvent.key === 'Alt') {
    return;
}

// or

if (keyBoardEvent.metaKey || keyBoardEvent.key.length > 1) {
    return;
}
```

But this would also focus the input for browser action like `ctrl+d` (bookmark) or `alt+d` (focus address bar), to prevent this we can add another event listener without [`useCapture`](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L342C62-L342C66), but then it would focus for keys with modifier and without browser action like `ctrl+alt+a` (which won't trigger any action or input), so I think it would be best to prevent focusing on inputs with just modifier keys.

**Comment by dylanexpensify** [comment]
Thanks for the follow up, @dukenv0307! @robertKozik thoughts?

**Comment by dylanexpensify** [comment]
Mind giving next steps here @robertKozik?

**Comment by dylanexpensify** [comment]
bump @robertKozik

**Comment by robertKozik** [comment]
Sorry for delay on my end. I've checked once again the proposals and discussion and I believe the go to should be to unify composer and picker focus conditions. Also, we should use production-tested composer conditions as there is no related issues with that lately.
It aligns with your [proposal](https://github.com/Expensify/App/issues/30867#issuecomment-1792919904) @dukenv0307 
🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment]
Agree it would be good to centralize this logic somewhere. Proposal LGTM!

**Comment by dylanexpensify** [comment]
bump @robertKozik!

**Comment by dylanexpensify** [comment]
payment upcoming! 🤑

**Comment by robertKozik** [comment]
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **It's not a regression introduced but any particular PR - rather inconsistency in handling focus of the input**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think we need new regression test here**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by dylanexpensify** [comment]
paying out today!

**Comment by dylanexpensify** [comment]
done!
