### ISSUE TITLE
[$500] IOU - Not here page shows up instead of red dot when paying a deleted IOU offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User A and B have no prior chat
1. [User B] Request money from User A
2. [User A] Go offline
3. [User A] Open the IOU report and tap Pay elsewhere
4. [User B] Delete the IOU
5. [User A] Go online
6. [User A] When the page is refreshed and redirected to not here page, go back to LHN
7. [User A] Open the chat with User B

## Expected Result:
In Step 6 and 7, user should be presented with a red dot error that the payment is not successful

## Actual Result:
In Step 6, user is redirected to not here page
In Step 7, the IOU preview remains with no red dot and the requester and requestee name is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/717c0984-8bdf-405e-ad22-94eb4f7fb65a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fddd5336c150011d</li>
        <li>Upwork Job ID: 1720477298038755328</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by rojiphil** [comment]
Not sure if the expected result should be as mentioned.

**Comment by strepanier03** [comment]
Thanks @ntdiary - I'll work on that.

**Comment by strepanier03** [comment]
Will have an update next week.

**Comment by strepanier03** [comment]
Raised [here](https://expensify.slack.com/archives/C03U7DCU4/p1700508338321969), just waiting for consensus to move this forward.

**Comment by strepanier03** [comment]
After discussion, the expected behavior is:

> I think the most graceful way to handle this when coming back online would be to:
> 
> - Navigate back to the parent chat if they’re already in the report view (i.e the workspace chat or DM)
> - Add the RBR to the parent workspace chat/DM row in the LHN
> - Add the RBR error message in-line the strikethrough’d report preview component i.e “Payment unsuccessful because this request has been deleted.”
> - Dismiss the error message and the report preview component disappears from the UI

Would it be a lot of work to achieve this @ntdiary? Do we have any proposals above that are close that could be tweaked?

We're mostly wanting to consider if this is an edge case that is worth correcting the expected behavior for or not.

**Comment by strepanier03** [comment]
@ntdiary -friendly bump when you have a chance to review my last comment.
