### ISSUE TITLE
[HOLD][$500] Feature request: Unable to add multiple emails at once as members to a room #26242

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#30874]
Coming from the below, which should be very similar
- https://github.com/Expensify/App/issues/26242 

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Add multiple emails at once as members to a room

## Expected Result:
Allow for multiple emails addresses to be added at once via a comma-separated list when inviting new members to a room.

## Actual Result:
Unable to add multiple emails at once as members to a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.95-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (20)](https://github.com/Expensify/App/assets/93399543/fc320073-5da1-4f2d-920d-9c4bb856ab72)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1692837155454539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b2a4652d665e512</li>
        <li>Upwork Job ID: 1699456983730249728</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@Samueljh1  would you like to work on this since you worked on the other? If so, the job price is $500.

**Comment by mananjadhav** [comment]
@mallenexpensify in this gets worked upon, can I work as C+? Helped with the previous issue too.

**Comment by mallenexpensify** [comment]
Yes, good 👀 Manan, I didn't think about the benefit of having the same C+ too

**Comment by Samueljh1** [comment]
> @Samueljh1  would you like to work on this since you worked on the other? If so, the job price is $500. 
> 
> 

Yes, happy to work on this

**Comment by mananjadhav** [comment]
@Samueljh1 Can you post a proposal so that we're aligned on the approach and the changes?

**Comment by Samueljh1** [comment]
> * [HOLD for payment 2023-10-23] [$1000] Feature request: Unable to add multiple emails at once as members to a workspace #26242

The code changes are basically the same.

# Proposal 
## Please re-state the problem that we are trying to solve in this issue.
When adding new members to a room, we can only invite one at a time.

## What is the root cause of that problem?
The handlers and code in RoomInvitePage.js only have logic that support inviting one member at a time (e.g., userToInvite is a single value, instead of an array).

## What changes do you think we should make in order to solve the problem?
Update single-user state variable userToInvite to an array, and update all handling logic to support multiple users (e.g., iterate through the invited emails when updating the list view instead of updating a single item). When handling updates to searchTerm, we can parse the string with the same parsing logic from `WorkspaceInvitePage`.

## What alternative solutions did you explore? (Optional)
N/A.

**Comment by Samueljh1** [comment]
https://github.com/Expensify/App/assets/10816880/f77d99a2-29f1-4dc4-a08e-99b6d8cd5343

Any reason why this is happening? I cannot work on the task until this is resolved. I hope this will be considered in the timing as well of the fix?

Thanks

**Comment by mallenexpensify** [comment]
I have no idea @Samueljh1 , what platform and version are you on?

**Comment by Samueljh1** [comment]
> I have no idea @Samueljh1 , what platform and version are you on?  

Chrome MacOS new.expensive.com. Same issue on iOS Safari.

**Comment by mallenexpensify** [comment]
@Samueljh1 , I wasn't able to reproduce the issue you're encountering, I tried a few times/ways on staging on MacOS / Chrome.  
@DylanDylann I've already assigned @Samueljh1 to the issue, they worked on [a similar issue](https://github.com/Expensify/App/issues/26242) so they'll be working on this.  I'll tag you if things don't work out and we want to consider your proposal

**Comment by DylanDylann** [comment]
Many thanks @mallenexpensify

**Comment by Samueljh1** [comment]
> @Samueljh1 , I wasn't able to reproduce the issue you're encountering, I tried a few times/ways on staging on MacOS / Chrome. @DylanDylann I've already assigned @Samueljh1 to the issue, they worked on [a similar issue](https://github.com/Expensify/App/issues/26242) so they'll be working on this. I'll tag you if things don't work out and we want to consider your proposal

Still unable to get it working. Do you mind sending a screen recording so I can see what you are doing? Thanks.

I have the code ready, I am just unable to test it because I can't get the drawer to open.

**Comment by Samueljh1** [comment]
<img width="498" alt="Screenshot 2023-11-09 at 14 50 08" src="https://github.com/Expensify/App/assets/10816880/27b226c8-6774-4f37-9a8d-b387708394bc">

This is the console message that appears when I click the invite button.

**Comment by mallenexpensify** [comment]
@mananjadhav do you have any idea what might be going on with/for @Samueljh1 ?

**Comment by mananjadhav** [comment]
@Samueljh1 Can you try creating a new room and checking? Are you sure you were able to add the members earlier?

**Comment by mallenexpensify** [comment]
I just checked and this is what I see for a private room in a workspace
<img width="393" alt="image" src="https://github.com/Expensify/App/assets/22508304/e3d624a5-1af9-4824-b956-2bf24d3bde4a">

**Comment by Samueljh1** [comment]
> @Samueljh1 Can you try creating a new room and checking? Are you sure you were able to add the members earlier?

I can't even see the 'New room' option in the FAB. How can I do this? I own a workspace.

**Comment by Samueljh1** [comment]
This thread seems to explain why I can't add my own room: https://expensify.slack.com/archives/C01GTK53T8Q/p1641598356166900. Any way to get access to this feature so I can work on this issue @mallenexpensify?

Thanks

**Comment by mallenexpensify** [comment]
@Samueljh1 , I added [sam@sjdevs.com](mailto:sam@sjdevs.com) to the below betas, can you test/try now?
- policyRooms
-  defaultRooms

**Comment by Samueljh1** [comment]
> @Samueljh1 , I added [sam@sjdevs.com](mailto:sam@sjdevs.com) to the below betas, can you test/try now?
> 
> * policyRooms
> * defaultRooms

Thank you, I can test it now.

**Comment by Samueljh1** [comment]
PR Created @mallenexpensify @mananjadhav https://github.com/Expensify/App/pull/31285

**Comment by mananjadhav** [comment]
Will review this by tomorrow.

**Comment by mananjadhav** [comment]
Confirming the expected behavior from the comment [here](https://github.com/Expensify/App/pull/31285#issuecomment-1823534630).

@mallenexpensify What will be the expected behavior when we have some of the emails already a part of the room.

**Comment by mallenexpensify** [comment]
@mananjadhav and @Samueljh1 , before answering
> What will be the expected behavior when we have some of the emails already a part of the room.

I was checking the flow for adding multiple users to a workspace via a comma-separated list and it didn't appear to be working, do either of you know why? 
<img width="405" alt="image" src="https://github.com/Expensify/App/assets/22508304/d82a97a2-4687-4d3b-a705-da0253d6fc06">

**Comment by DylanDylann** [comment]
@mallenexpensify I `ve commented in my [proposal](https://github.com/Expensify/App/issues/30874#issuecomment-1801417108) 

> But the https://github.com/Expensify/App/pull/30859 removed this feature in WorkspaceInvitePage.

**Comment by Samueljh1** [comment]
> @mananjadhav and @Samueljh1 , before answering
> 
> > What will be the expected behavior when we have some of the emails already a part of the room.
> 
> I was checking the flow for adding multiple users to a workspace via a comma-separated list and it didn't appear to be working, do either of you know why? <img alt="image" width="405" src="https://private-user-images.githubusercontent.com/22508304/286048982-d82a97a2-4687-4d3b-a705-da0253d6fc06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTA4ODUsIm5iZiI6MTcwMTE1MDU4NSwicGF0aCI6Ii8yMjUwODMwNC8yODYwNDg5ODItZDgyYTk3YTItNDY4Ny00ZDNiLWE3MDUtZGEwMjUzZDZmYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA1NDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZDZkNjc3YWEwM2YwZDg0NDExMzJiYjljOWY5MDFkNmZlMzQzZjY2NWZjMTRkMTJhYTFhM2NiM2E3NzcxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uYTsgOIwj_N6Y1DHGN2ZH9Ln5kSjtRm4Bq5bnLpUznw">

@mallenexpensify It was removed due to uncertainty about how to handle error messages, so I guess a similar thing here. IMO there should have just been a discussion about how to best present the message but instead it was removed entirely. https://github.com/Expensify/App/pull/30859

**Comment by mallenexpensify** [comment]
Well.... shoot.  That's def not ideal.  Should we put this on Hold til we discuss and/or fix the workspace flow?  

One concern I have is that we might not want to invest a lot into trying to perfect this instance, in case it'll be changed in the future.  I do think that adding multiple users via a comma-separated list is a useful feature for both workspaces and rooms, so maybe it's best to _go back to the drawing board_ to ensure we're aligned.  What do y'all think?  

Here's a couple screenshoted examples I tested, to see how they worked
<img width="558" alt="image" src="https://github.com/Expensify/App/assets/22508304/1badd2cd-800c-4294-b035-05d3dfe57a8a">

For gmail, `bob` got _pushed_ to the end of the list (it was originally was third of four), which I thought was interesting.  
<img width="754" alt="image" src="https://github.com/Expensify/App/assets/22508304/211800e4-0ea0-4dc7-a904-a2e2525ef4d5">

**Comment by Samueljh1** [comment]
@mallenexpensify let's just copy the Google approach then? We give an error message for the first 'wrong' entry. Then, when they try again, they will see the next problematic one (if there is one). This prevents the message being too large.

**Comment by mallenexpensify** [comment]
> We give an error message for the first 'wrong' entry. Then, when they try again, they will see the next problematic one (if there is one)

This makes sense to me, @mananjadhav what do you think?

**Comment by mananjadhav** [comment]
I think let's start this conversation on slack?

**Comment by Samueljh1** [comment]
> I think let's start this conversation on slack?

Please send the link once created, thanks

**Comment by mallenexpensify** [comment]
Shared here https://expensify.slack.com/archives/C01GTK53T8Q/p1702927833552709?thread_ts=1692837155.454539&cid=C01GTK53T8Q

For the proposed solution, how does the error show if someone were to paste in a comma-separated list of emails and two of the addresses are correct? (I'm guessing we'd throw and error code for the first and, once the first is fixed then we'd show an error code for the second?

**Comment by mallenexpensify** [comment]
We 3 👍 on the post (all us, hahahahaha).   Let's move forward with
> We give an error message for the first 'wrong' entry. Then, when they try again, they will see the next problematic one (if there is one)

*BUT* can we implement it first for workspaces, then rooms?  
I can either reopen the issue below or create a new one, which do you prefer @Samueljh1 and @mananjadhav ? (either way, job price would be $500 and it's be a high-priority issue). 

Also, I think we should err on the side of sharing examples as the PR is being worked on, in the PR and the GH issue, to ensure we're aligned.

**Comment by Samueljh1** [comment]
> We 3 👍 on the post (all us, hahahahaha). Let's move forward with
> 
> > We give an error message for the first 'wrong' entry. Then, when they try again, they will see the next problematic one (if there is one)
> 
> _BUT_ can we implement it first for workspaces, then rooms? I can either reopen the issue below or create a new one, which do you prefer @Samueljh1 and @mananjadhav ? (either way, job price would be $500 and it's be a high-priority issue).
> 
> Also, I think we should err on the side of sharing examples as the PR is being worked on, in the PR and the GH issue, to ensure we're aligned.

Let's create a new issue.

**Comment by quinthar** [comment]
Let's pause work on this until we settle having a unified design here: https://expensify.slack.com/archives/C01GTK53T8Q/p1703557793897069?thread_ts=1703360093.158969&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Put on hold, removed `reviewing` label, left as a weekly

**Comment by mallenexpensify** [comment]
Still held

**Comment by mallenexpensify** [comment]
on hold

**Comment by mallenexpensify** [comment]
Holding on a unified design proposal, bumping to monthly til we prioritize.

**Comment by mallenexpensify** [comment]
Added to #vip-vsb because it doesn't haven't to do with money.

**Comment by mallenexpensify** [comment]
From the other similar issue
- https://github.com/Expensify/App/issues/26242

> This is actively being redesigned with Groups so I'm going to close. We can reopen if it's still behaving unexpectedly once we update.

Temped to close but I'm going to wait one more 'overdue' round then I'll retest and see if it makes sense to keep open or close.

**Comment by mallenexpensify** [comment]
Closing, will reopen if/when needed.

**Comment by mallenexpensify** [comment]
fwiw... this was partially fixed/built.  The only way to add multiple users to a workspace is via a spreadsheet.  

<img width="497" height="429" alt="Image" src="https://github.com/user-attachments/assets/0c20b2a9-d8a6-4043-a003-b29b1aa7ac61" />

<img width="472" height="157" alt="Image" src="https://github.com/user-attachments/assets/bfc88e98-28fd-4898-8187-3d45557cec79" />

I don't think it's ideal to ask people to use another tool in order to add emails.  When I paste a list into Slack (albeit into a room vs workspace) I instantly get this

<img width="784" height="258" alt="Image" src="https://github.com/user-attachments/assets/d03f4b28-e689-4e2d-ad90-92d939cf991f" />
