### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] IOS - Chat - Autocorrect replaces the text without user interaction before going to the next page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?: **Y
**Reproducible in production?: **Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Log in
3. Tap on any conversation
4. Tap on the "+" button
5. Tap on the "Assign task" button
6. For the "Title", type in any words that triggers an auto correction / suggestion
7. Tap on the "Next" button
8. Tap on the "Back" button

## Expected Result:
Auto correction / suggestion shouldn't change the word without user interaction

## Actual Result:
When I tap on the "Next" button, I can see that the Title changes to the suggested word without my interaction. On the confirmation window, the title is the one I typed in. When I go back, the title is the suggested word

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4024099d-23a4-4746-983c-75b8afecb5a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109790a432df0e00d</li>
        <li>Upwork Job ID: 1720505814489313280</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27757486</li>
</ul></li>
    </ul>
</details>

**Comment by NisargDeveloper** [comment]
@dukenv0307 you are right. Let me know if you are not solving this issue. I can help you to solve this issue

**Comment by Victor-Nyagudi** [comment]
I'm conflicted on this one. 

Autocorrect changing the text when the user navigates to the next screen may be undesired, but the user __*is*__ shown a tooltip of what the text will be changed to along with an "X" to ignore it, so they still have control over what happens next. 

It's also very likely the user may have encountered this kind of behavior before after having autocorrect enabled and should be familiar with its behavior, so the blame wouldn't fall on Expensify for the altered text but rather on the user for not choosing to ignore autocorrect's changes in addition to enabling it in the first place. 

I'm leaning towards doing nothing here, but if a fix is warranted, then that would work too.

**Comment by mananjadhav** [comment]
Will review this today.

**Comment by mananjadhav** [comment]
@dukenv0307's proposal looks fine to me. But I have one discussion point. Why not just disable the `autoCorrect` for iOS only? Why disable it for all platforms (especially Android, and mobile web)?

🎀 👀 🎀 C+ reviewed.

**Comment by JmillsExpensify** [comment]
@jasperhuangg Any thoughts on that last comment from @mananjadhav or @dukenv0307?

**Comment by jasperhuangg** [comment]
@mananjadhav 

> Why disable it for all platforms (especially Android, and mobile web)?

That's a good point, were we not aware of this issue on other platforms?

**Comment by JmillsExpensify** [comment]
PR still in review

**Comment by JmillsExpensify** [comment]
Same

**Comment by mananjadhav** [comment]
I am not sure if we have any offending PR for this one. We disabled auto-correct here and by default we don't have any rules related to auto-correct.

@jasperhuangg @JmillsExpensify do we want to document this somewhere? or add a checklist item? I can't come up with a pattern, and more inclined to solve this case by case. what are your thoughts?

I do think we need a regression test here as we'd want this to be covered in case we revert this change in any future issue.

**Regression Test Proposal**
1. Go to `FAB` > `Assign task`
2. Enter a task title that triggers an auto correction / suggestion such as `takk`
3. Click on the Next button
4. Click on the Back button in header
5. Verify that the task title in both pages are the same.

**Comment by JmillsExpensify** [comment]
Payment summary: 

- Issue reporter: QA
- Contributor: $500 @dukenv0307 
- Contributor+: $500 @mananjadhav

**Comment by JmillsExpensify** [comment]
Contributor paid out, C+ is paid via NewDot, and regression test created. Closing this issue.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on comment above.
