### ISSUE TITLE
[$500] Android - An error message appears after coming back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.2.95.0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with any account
2. Turn off internet connection
3. Click on the avatar - click on "Profile" in the panel/modal that appears.
4. Click on "Contact method" and then click on the green pill button at the bottom that says "New contact method".
5. Enter a valid email e.g. another test account you have access to, and then click on the green pill button at the bottom that says "Add". You'll be redirected to the previous screen.
6. You can add a contact method while offline, but you won't be able to click it (step 11) to navigate to the screen with the green dot and light-greyish green text.
7. Turn ON internet connection

## Expected Result:
NO error message appears after coming back online

## Actual Result:
An error message appears after coming back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/235c2c11-141e-4ada-be0d-4484b84b2a9c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e3d3034acb2c160</li>
        <li>Upwork Job ID: 1720943807416238080</li>
        <li>Last Price Increase: 2023-11-04</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
I think this is not issue. That error message is shown because you have account already.
If you add new email, then that error message will not be shown.

**Comment by zanyrenney** [comment]
That's helpful perspective, thank you. Will close this out then!
