### ISSUE TITLE
[$500] Web - Avatar - Unable to upload an avatar image using FireFox browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/ in Mozilla Firefox browser
2. Navigate to settings by clicking on the user avatar over LHN
3. Click on Profile
4. Click on the avatar
5. Upload a valid photo

## Expected Result:
Expected to be able to upload a valid photo using FireFox desktop

## Actual Result:
An error appears when trying to upload a valid jpg as avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] Windows: Firefox
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83b12f19-747b-4417-bc93-21112a5a6a7e

![Bug6251745_1698324788286!pexels-stein-egil-liland-3408744 (3)](https://github.com/Expensify/App/assets/78819774/2a0353b9-8153-4fba-950d-2dbac136eaa3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01193223a78453c031</li>
        <li>Upwork Job ID: 1721303944673562624</li>
        <li>Last Price Increase: 2023-11-05</li>
    </ul>
</details>

**Comment by Allan-1** [comment]
Contributor details
Your Expensify account email: amuturi01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a803392c1c56b8f5

**Comment by Allan-1** [comment]
I believe the image dimensions are greater than the required dimensions that's why it is not uploading the avatar

**Comment by laurenreidexpensify** [comment]
@lanitochka17 can you please upload a smaller image and confirm that this is still reproducible. Thank you

**Comment by NisargDeveloper** [comment]
Yes this is an expected result. Please try using specified dimensions image.

**Comment by laurenreidexpensify** [comment]
I'm going to close this as it doesn't appear to be a bug but an expected outcome.
