### ISSUE TITLE
[HOLD for payment 2023-11-30] [CRITICAL] Migrate the BaseAutoCompleteSuggestions to Flashlist

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30912]
Part of https://github.com/Expensify/App/issues/28902

Let's migrate [BaseAutoCompleteSuggestions](https://github.com/Expensify/App/blob/97320a0abbc04bfdd5395db4e0ca7d0de2f5d1ff/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L95-L105) to use Flashlist component instead of FlatList

Callstack is working on the migration right now.

Lets use this issue for daily updates on this migration

<details><summary>Issue Owner</summary>Current Issue Owner: @adhorodyski</details>

**Comment by adhorodyski** [comment]
Hi, I'm Adam from Callstack. I'd like to work on this :)

**Comment by roryabraham** [comment]
I will await a PR. Do you expect to make daily progress on this issue?

**Comment by adhorodyski** [comment]
Not really, imo this could be set to `weekly`. Linking an android issue that I'd have to work around for reference (with nesting gesture scopes): https://github.com/software-mansion/react-native-gesture-handler/issues/2582

**Comment by mountiny** [comment]
@adhorodyski if there is anything you need to help with the gesture handler, we can bring it up in slack and hook in SWM people to work on the issue

**Comment by adhorodyski** [comment]
Oh sure, let me open up a PR which works I think everywhere except for Android.

**Comment by mountiny** [comment]
thread is here https://expensify.slack.com/archives/C05LX9D6E07/p1699460749625439

**Comment by adhorodyski** [comment]
Now awaiting a C+ review in https://github.com/Expensify/App/pull/31057 :)

**Comment by Christinadobrzyn** [comment]
I'm going ooo until Monday Nov 27th so going to assign another BZ teammate to monitor this until I'm back. Thanks!

Status: reviewing [PR](https://github.com/Expensify/App/issues/30912#issuecomment-1809838764)

**Comment by roryabraham** [comment]
@robertKozik was C+ so will invoice us separately. Same  for @adhorodyski 

So we can close this
