### ISSUE TITLE
Chat - Participants screen briefly shown and distance page opens few times after opening link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28308

## Action Performed:
1. Open the app
2. Tap FAB > Request money > Distance
3. Navigate to https://staging.new.expensify.com/request/new/participants

## Expected Result:
User is navigated to the distance request page

## Actual Result:
Participants screen briefly shown and distance page opens few times after opening link

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![1](https://github.com/Expensify/App/assets/93399543/2150dcb5-7b6e-4787-98e0-6be3c394281a)

https://github.com/Expensify/App/assets/93399543/aee67024-7db1-43d4-b700-4aa0943f9e49

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
This is the only PR that obviously looks related to deep linking: 

https://github.com/Expensify/App/pull/29636/files

**Comment by marcaaron** [comment]
It doesn't really seem like it would be touching this distance request code flow though.

**Comment by marcaaron** [comment]
I'm gonna demote this one for the following reasons:

1. The problem is only affecting native apps
2. The bug is only reproducible if you do something "weird" 
3. Deep linking to the participants page is kind of "holding it wrong". I can't think of a clear reason why someone would actually do that.

**Comment by muttmuure** [comment]
Going to close and we can reopen if a real user hits this
