### ISSUE TITLE
 Chat - Default avatars are shown in LHN instead of custom ones

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App
2. Login with any account
3. Check user avatars in LHN

## Expected Result:
Custom avatars are shown in LHN for users who have them

## Actual Result:
Default avatars are shown in LHN for all users, even if custom ones are loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/b5732a89-dc0e-468c-bf4b-fbf8ff8354cc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Discussed [in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1699314085349979), but I think we can fix this by removing the call to `_.values` [here](https://github.com/Expensify/App/blob/9f7b8865e6043f0558d8ff2045aa5b014067fed0/src/components/LHNOptionsList/LHNOptionsList.js#L147)

**Comment by cead22** [comment]
I pushed a draft PR with another potential solution, in case we wanna go that route

**Comment by TMisiukiewicz** [comment]
Hi, I'm Tomasz from Callstack, seems like a regression from #30242 I've been working on together with @adhorodyski. I think solution proposed by @roryabraham is correct - I'll take care of creating the PR

**Comment by mountiny** [comment]
gonna push this forwards now

**Comment by mountiny** [comment]
Fixed, we will have to pay @rushatgabhane for review

**Comment by rushatgabhane** [comment]
@mountiny what amount should I request on new dot?

**Comment by mountiny** [comment]
I guess this would be $500 based on the classic rules

**Comment by rushatgabhane** [comment]
request here- https://staging.new.expensify.com/r/8616790277990951

**Comment by mountiny** [comment]
I believe we can close this one now and the payer will come back here to confirm once request has been  paid.
