### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] The app crashes when taping on link https://staging.new.expensify.com/request/new/participants

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on https://staging.new.expensify.com/request/new/participants

## Expected Result:
App is not crashed

## Actual Result:
The app crashes when taping on link https://staging.new.expensify.com/request/new/participants

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/401d260d-3541-49b2-9bd0-4b820ed06482

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b97b835cfc1fe6d6</li>
        <li>Upwork Job ID: 1721768998901219328</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27552830</li>
<li>dukenv0307 | Contributor | 27552832</li>
<li>situchan | Contributor | 27553607</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue is not reproducible in production 

https://github.com/Expensify/App/assets/93399543/b33e0d56-391e-41d6-8274-4ee19642da01

**Comment by robertjchen** [comment]
@dukenv0307 that makes sense! Let's go with that proposal 👍

**Comment by robertjchen** [comment]
accelerating this due to deploy blocker status

**Comment by situchan** [comment]
Not able to reproduce on latest main

**Comment by situchan** [comment]
Regression from https://github.com/Expensify/App/pull/28308

**Comment by robertjchen** [comment]
Ah was this issue addressed already? 🤔

**Comment by situchan** [comment]
@dukenv0307 are you able to reproduce on main?
I definitely reproduced on staging but not on main

**Comment by situchan** [comment]
@robertjchen I reproduced on main after logout and re-login. Bug is still valid. So happens when `iou` data doesn't exist in Onyx.

> iou?.transactionID || ''

@dukenv0307 we should not return empty string. It will pull all transactions.
Please use [this](https://github.com/Expensify/App/pull/28866/files#diff-4d250e15a111e699febadcdfc7f4f2c962fbdac79e4009df0414ea658985c04bR157-R167) as solution

**Comment by situchan** [comment]
@robertjchen I can do C+ review in PR if you agree

**Comment by robertjchen** [comment]
Great catch @situchan , happy for you to do the C+ review 🙇

**Comment by robertjchen** [comment]
Thanks! Let me know if you're able to test this now 🙏

**Comment by robertjchen** [comment]
Looks like this feel through the cracks, let me find someone here to handle the next steps. Thanks for your patience!

**Comment by peterdbarkerUK** [comment]
Payment summary:

$500 to @dukenv0307 (contributor)
$500 to @situchan (C+ / reviewer)

Job closed on UpWork. Thanks guys!
