### ISSUE TITLE
Chat - Scrolling does not work if the user adds a message or clicks 'New messages' button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop App
2. Login with any account and go to chat with long history
3. Scroll to the beginning of the chat
4. Post new messages > Check the result
5. Mark any message as unread and scroll up the chat until the "New messages" button appears
6. Click the "New messages" button > Check the result

## Expected Result:
4. Message added and chat scrolled to new messages
6. Chat scrolled to new messages

## Actual Result:
4. Message added and chat did not scroll to new messages
6. Chat did not scroll to new messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/27f30d24-d4d6-4ff8-a427-ca71d1552163

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Hmm yeah, the 'New Message' indicator doesn't scroll me anymore

**Comment by situchan** [comment]
This came from https://github.com/Expensify/App/pull/28793
cc: @perunt @janicduplessis @thienlnam

**Comment by perunt** [comment]
If you press this button without navigating to thread would it scroll you down?

**Comment by situchan** [comment]
> If you press this button without navigating to thread would it scroll you down?

Nope. Seems like ref of MVCPFlatList is not forwarded correctly

**Comment by situchan** [comment]
https://github.com/Expensify/App/blob/a1a0f3897995a0992f38a885412af723174c7be2/src/hooks/useReportScrollManager/index.ts#L12-L18

Early returned because flatListRef.current is not set

**Comment by thienlnam** [comment]
@perunt You around to get a PR up for this? Ideally we can just fix the ref forwarding and then we won't have to revert the PR

**Comment by situchan** [comment]
There's another similar regression: #30935

**Comment by situchan** [comment]
Confirmed https://github.com/Expensify/App/pull/30962 fixes this issue as well

**Comment by thienlnam** [comment]
Great - we'll link that one there then. Thanks for the help here!

**Comment by thienlnam** [comment]
This was taken care of in https://github.com/Expensify/App/pull/30962
