### ISSUE TITLE
Chat - Emoji picker and send buttons appear on the left of composer briefly when opening chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29755

## Action Performed:
1. Launch New Expensify app.
2. Open any chat.

## Expected Result:
The composer layout is the same when opening the chat.

## Actual Result:
The emoji picker and send buttons appear on the left of composer briefly when opening chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/30551262-a9f0-4315-8987-6dc996d98bb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This issue looks like the recent change of react-native-onyx version in this PR https://github.com/Expensify/App/pull/29169
@ospfranco might have some context

**Comment by bondydaa** [comment]
https://github.com/Expensify/App/issues/23658#issuecomment-1799029415

we're going to revert the PR that caused this

**Comment by bondydaa** [comment]
revert pr is up https://github.com/Expensify/App/pull/31011

**Comment by bondydaa** [comment]
revert PR was CP'd to staging, can you please retest to confirm it's fixed?

**Comment by robertjchen** [comment]
Confirm that this was resolved after the revert 👍
