### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] mWeb/Chrome - Start Chat- #Rooms creation menu is misaligned

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap start chat
4. Tap chat---room--chat (navigate to and fro)

## Expected Result:
The room page left margin must show enough space and alignment of page must be correct.

## Actual Result:
After tapping chat, if user taps room, by navigating to and fro, left margin no space is shown and alignment is not fine.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/785760ef-aa13-4e93-b265-348f2789dcc5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9e9cfdca0e3fa3a</li>
        <li>Upwork Job ID: 1721845296933953536</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27576928</li>
<li>tienifr | Contributor | 27576931</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproduced in production

https://github.com/Expensify/App/assets/115492554/a01dafb0-871e-47a6-9e77-de17452114c3

**Comment by s-alves10** [comment]
I am not able to reproduce this on the latest main. Please help me if I missed something

**Comment by peterdbarkerUK** [comment]
Yep I can reproduce this. It's not quite as extreme as the video, but switching to room seems to jogglingly over/undershoot and eventually settle slightly off in the margin.

**Comment by peterdbarkerUK** [comment]
![image](https://github.com/Expensify/App/assets/16888060/7a8cddbc-86de-4a6b-8e2b-8a2a62c6f5b5)

**Comment by madmax330** [comment]
@peterdbarkerUK is this on staging or production?

**Comment by madmax330** [comment]
It's known that it's broken on staging, but it works on main/dev. So that means it's already fixed, we're just not sure by which PR so we would need to CP that is my guess

**Comment by peterdbarkerUK** [comment]
Ah, I failed to find that it was known, thanks for clarifying. Will you investigate that?

**Comment by madmax330** [comment]
Nice find @tienifr can you make a PR for this quickly?

**Comment by peterdbarkerUK** [comment]
Noice. @situchan I'm on the fence about this needing specific regression testing, what do you think?

Payments sent:
- @tienifr $500 Contributor
- @situchan $500 Reviewer

Job closed

**Comment by situchan** [comment]
The root cause is performance degrade. Handling that in https://github.com/Expensify/App/issues/31190
This was caught by Applause team so no need specific regression testing.
