### ISSUE TITLE
[HOLD FOR PAYMENT] [$500] mWeb/Chrome - Compose-After pasting emoji, cursor moving single space away

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Search emoji by typing :depa and select it from suggestions
4. Select and copy the emoji and paste it

## Expected Result:
After pasting emoji, cursor must not move single space away.

## Actual Result:
After pasting emoji, cursor moving single space away.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/2b1699d0-a2ee-4ef8-a6a4-0c49fdce7218

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f8946b141752346</li>
        <li>Upwork Job ID: 1721857426065879040</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Issue is not reproducible in production

https://github.com/Expensify/App/assets/115492554/410e1793-1630-4d69-a907-2e93d5c8f293

**Comment by MariaHCD** [comment]
I don't think this should block the deploy. But we can certainly get this fixed.

Thoughts, @alitoshmatov?

**Comment by alitoshmatov** [comment]
@MariaHCD agree, I think this issue can handled as a regression from https://github.com/Expensify/App/pull/30412

**Comment by bondydaa** [comment]
https://github.com/Expensify/App/issues/23658#issuecomment-1799029415

we're going to revert the PR that caused this

**Comment by bondydaa** [comment]
revert pr is up https://github.com/Expensify/App/pull/31011

**Comment by bondydaa** [comment]
revert PR was CP'd to staging, can you please retest to confirm it's fixed?

**Comment by MariaHCD** [comment]
Retested on staging mWeb Chrome and looks good!

https://github.com/Expensify/App/assets/12268372/42cd7c7a-867d-4550-a4ca-3449aa2aec34

**Comment by puneetlath** [comment]
Reopening as we need to pay @alitoshmatov for C+ review

**Comment by alitoshmatov** [comment]
PR was deployed to [production ](https://github.com/Expensify/App/pull/31011#issuecomment-1805964670)in 10th November, tomorrow it will be ready for payment

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by alitoshmatov** [comment]
We can proceed with payment

**Comment by NicMendonca** [comment]
@alitoshmatov are you paid via Upwork, or Expensify? If Upwork, can you apply to the job? https://www.upwork.com/jobs/~015f8946b141752346

**Comment by alitoshmatov** [comment]
Upwork, applied

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by alitoshmatov** [comment]
@NicMendonca Friendly bump for payment

**Comment by NicMendonca** [comment]
paid!
