### ISSUE TITLE
[$500] Chat - Scrolling down on edit composer with multi lines scrolls up the chat history

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30987]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30857

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Open chat with chat history that is enough to fill a page.
3. Send a message with 8 multilines.
4. Hover the cursor over the edit composer.
5. Scroll down on the edit composer (swipe down on the touchpad).
5. Keep scrolling down.

## Expected Result:
When scrolling down on the edit composer, the chat view will not be scrolled.

## Actual Result:
When scrolling down on the edit composer, the chat view scrolls up. When scrolled to the top of the chat, user is unable to reach the latest message with the edit view as it is scrolling back up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/f631d4e8-8372-46de-ba7d-3f30d8ad5897

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014595e5e6d6d7b727</li>
        <li>Upwork Job ID: 1721862626579214336</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by akinwale** [comment]
@bernhardoj Thanks. I retested and it works as expected.

@bernhardoj's [proposal](https://github.com/Expensify/App/issues/30987#issuecomment-1798428141) correctly identifies the root cause and the proposed solution is simple and adequate. Since it is the first proposal that fixes the problem, we can move forward with it.

🎀 👀 🎀 C+ reviewed.

**Comment by akinwale** [comment]
@zanyrenney Automation seems to have missed this issue.

The [PR](https://github.com/Expensify/App/pull/31271) was deployed to production on [2023-11-22](https://github.com/Expensify/App/pull/31271#issuecomment-1821920028), so payment should have been due on 2023-11-29. It's now overdue by 1 week.

Thanks.

**Comment by tgolen** [comment]
bump @zanyrenney for the above ^

**Comment by zanyrenney** [comment]
**payment summary**

$0 reporting bonus - done by applause
$500 - c @bernhardoj 
$500 - c+ @akinwale

**Comment by zanyrenney** [comment]
Ugh yep now its closed. I'll recreate for you @bernhardoj please apply ASAP, I am OOO from tomorrow.

**Comment by zanyrenney** [comment]
@bernhardoj 
<img width="922" alt="2023-12-21_18-11-16" src="https://github.com/Expensify/App/assets/56830058/a492e4cb-87ea-44bd-8f69-d8a00f0eb409">
offer is here, please accept.

**Comment by zanyrenney** [comment]
$500 - c @bernhardoj PAID
