### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500] Workspace - User is scrolled down in Workspace invite page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30999]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces
4. Tap on a Workspace
5. Tap Members
6. Tap on Invite
7. When keypad is open, scroll up the page after contacts are displayed

## Expected Result:
When user scrolls up the contacts, the Workspace invite page must not scroll down

## Actual Result:
When user scrolls up the contacts, the workspace invite page scrolls down and top of contacts section is shown instead of showing mid section where user stops scrolling the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/16772a7e-851a-41c3-ab42-fe200822e797

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173287fc1604c0e73</li>
        <li>Upwork Job ID: 1721905199058337792</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 28091046</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
I just tried to reproduce this, and it's working fine for me on both Mac chrome, and Android mobile web. Closing, as I don't think there's anything we need to fix here.

**Comment by joekaufmanexpensify** [comment]
Is what you're saying you can reproduce that if you try and scroll down with the keyboard open, we begin scrolling belatedly close the keyboard, and then navigate back to the top of the list?

**Comment by kbecciv** [comment]
Issue is reproducible in QA side on build 1.4.18.2

https://github.com/Expensify/App/assets/93399543/8c5987d8-eaff-4228-af71-bc039be94649

**Comment by joekaufmanexpensify** [comment]
Got it, I'll take a look.

**Comment by joekaufmanexpensify** [comment]
Hm, yeah I can reproduce now too. Probably worth fixing, as the member invite flow is pretty important. 

https://github.com/Expensify/App/assets/54866469/2fc6fd31-2d1e-48ed-b1fb-94da08993f32

**Comment by joekaufmanexpensify** [comment]
@mananjadhav feel free to go ahead with reviewing proposals

**Comment by mananjadhav** [comment]
I'll review the proposals by tomorrow.

**Comment by mananjadhav** [comment]
Reviewed the proposals. Both the proposals are on the similar lines, and hence shortlisting @Krishna2323's [proposal](https://github.com/Expensify/App/issues/30999#issuecomment-1799033625).

@Krishna2323 Please note:

1. I saw the first version of the proposal didn't have quality content, and then you made several edits. 
2. You've pasted the whole code, which isn't necessary.

I would strongly advise against both the things. It makes it difficult for us to review.
🎀 👀 🎀 C+ reviewed.

**Comment by rlinoz** [comment]
@Krishna2323 if you can help me with the above comment 😄

**Comment by joekaufmanexpensify** [comment]
Proposal still pending discussion

**Comment by rlinoz** [comment]
Going with @Krishna2323's selected proposal.

Thanks!

**Comment by joekaufmanexpensify** [comment]
Great. @Krishna2323 let us know once a PR is up!

**Comment by joekaufmanexpensify** [comment]
Pending review from @mananjadhav

**Comment by mananjadhav** [comment]
I had some issues with build yesterday. I'll review it tomorrow.

**Comment by joekaufmanexpensify** [comment]
@mananjadhav could you please handle the BZ checklist so we can prep to issue payments?

**Comment by joekaufmanexpensify** [comment]
BZ checklist all set! All good to issue payment. We need to make the following payments: 

- @Krishna2323 $500 for PR. Paid via Upwork. 
- @mananjadhav $500 for C+ review. Paid via NewDot.

**Comment by joekaufmanexpensify** [comment]
@Krishna2323 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@mananjadhav please request $500 via NewDot, and confirm here once done.

**Comment by joekaufmanexpensify** [comment]
Great. TY! Closing as this is all set.
