### ISSUE TITLE
[$500] Android - Chat - Keyboard does not pull up when editing the message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR :** https://github.com/Expensify/App/pull/30669

**Version Number:** v1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any chat.
3. Send a message.
4. Long press on the message.
5. Tap Edit message.

## Expected Result:
The keyboard will pull up.

## Actual Result:
The edit composer is focused but the keyboard does not pull up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/6df53751-2f4a-4b25-8595-a556dc904afb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011928df9e6f1e55ee</li>
        <li>Upwork Job ID: 1721869358457446400</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by izarutskaya** [comment]
Not reproducible in production

https://github.com/Expensify/App/assets/115492554/f9133237-7e16-45c3-a6b8-86284841a57d

**Comment by cristipaval** [comment]
Thanks, @dukenv0307 for the proposal. What happens if the user taps again on the input field? Does the keyboard show up? I would like to know if removing the deploy blocker label and fixing it without rushing makes sense.

**Comment by cristipaval** [comment]
Alright, thanks @dukenv0307!

Given that the keyboard shows up if the user explicitly taps on the input field, I'll consider this a minor issue that shouldn't block the deployment. I just removed `DeployBlockerCash` label.

**Comment by cristipaval** [comment]
@mananjadhav could you please check if the proposed solution works?

**Comment by mananjadhav** [comment]
I think @dukenv0307's proposal will work. Will have to make sure `scrollTop` shouldn't impact the composer.

🎀 👀 🎀 C+ reviewed.

**Comment by cristipaval** [comment]
> The follow up PR #31041 is already merged to fix the keyboard issue in android...

Thanks @tsa321 , I'll close the issue then.

**Comment by alexpensify** [comment]
Thanks for your help @cristipaval!
