### ISSUE TITLE
[HOLD for payment 2023-11-21] Unified testing utilities for mocks using a fake data generation library

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30994]
### Problem

Mocking data with confidence is crucial when developing tests, especially for an offline-first data-driven app. What I saw myself was a lack of predefined mocking strategies, which combined with the poor type-safety led me to a lot of errors and frustration. Each test file (when written by different people over time) had to reinvent the wheel when it comes to working with reports, reportActions, policies and so on.

### Solution
By introducing a fake data library (my pick was [ngneat/falso](https://ngneat.github.io/falso/) - it’s more lightweight and composable than the popular faker module) as a dev dependency we can unify our mocks across the whole project and improve the DX of our teams when testing.

The example below shows whole entities being mocked, but with composition we can also generate useful partials.

**Comment by mountiny** [comment]
@adhorodyski can you please comment on this issue?

@lschurr nothing required for this one right now

**Comment by adhorodyski** [comment]
@mountiny sure thing, I'd like to work on this.

**Comment by mountiny** [comment]
This is completed, nothing to pay out
