### ISSUE TITLE
Web - Public Room - Two console errors show up when navigating to public room anonymously

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30751
## Action Performed:
1. Log out if logged in.
2. Navigate to https://staging.new.expensify.com/r/2376199970894587
3. Refresh the page

## Expected Result:
No console error shows up

## Actual Result:
In Step 2, console error shows up.
In Step 3, another console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/02477f23-ecef-4501-95cb-7b283995b752

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I still see the console error: https://dev.new.expensify.com:8082/r/2376199970894587

![Screenshot 2023-11-07 at 10 18 15 AM](https://github.com/Expensify/App/assets/2838819/7cb11aa9-71e2-439c-bdbc-4b4ecca3a3d6)

**Comment by AndrewGable** [comment]
Hmm actually now I am unable to reproduce on latest `main`. Since it's hard to reproduce I would suggest we close until we figure out the exact steps to reproduce.
