### ISSUE TITLE
Chat - Default emoji skin tone works only for yellow color

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31006]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to any chat
3. Open the emoji picker and select color ( white, black..) for the default skin color
4. Type :+1 into compose box and select the suggestion

## Expected Result:
Emoji with selected skin color should be displayed

## Actual Result:
Default emoji skin tone works only for yellow color

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a94b078-caa8-4351-8bc0-316622f1754f

Production 

https://github.com/Expensify/App/assets/78819774/206a7a72-3226-40c1-a025-01bf4c3c693e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
Regression from https://github.com/Expensify/App/pull/30412

**Comment by esh-g** [comment]
I think the PR is going to get reverted as it caused a lot of regressions...

**Comment by bondydaa** [comment]
nice thank you all, I was looking through the deploy checklist and going to say these are the only 2 that touched emojis as best I can tell from PR names https://github.com/Expensify/App/pull/30412/ & https://github.com/Expensify/App/pull/30201/ the one for the windows emoji text seems very unlikely so appreciate ya figuring out https://github.com/Expensify/App/pull/30412/ was the issue.

**Comment by bondydaa** [comment]
https://github.com/Expensify/App/issues/23658#issuecomment-1799029415

we're going to revert the PR that caused this

**Comment by bondydaa** [comment]
revert PR was CP'd to staging, can you please retest to confirm it's fixed?

**Comment by bondydaa** [comment]
closing this out, tested it just now and it's not reproducible so the revert fixed it.
