### ISSUE TITLE
[$500] Android/Chrome - The keyboard consistently pops up when the user is scrolling the list of users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31019]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.2.96.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Tap on Fab menu - Start Chat
4. Tap on " Add to group"
5. Scroll the list of users

## Expected Result:
The keyboard does not consistently pops up when the user is scrolling the list of users

## Actual Result:
The keyboard consistently pops up when the user is scrolling the list of users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2ee5c0e6-e08f-477f-a7be-73880d4cf8ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012867fdcc25c3c082</li>
        <li>Upwork Job ID: 1721954668787851264</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by getusha** [comment]
@dylanexpensify i think this issue has been resolved.

**Comment by dylanexpensify** [comment]
ah agree, ty!
