### ISSUE TITLE
[$500]  Profile - Unknown email address as contact method if I log in with Apple ID

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with Apple ID
3. Tap on your profile picture
4. Tap on the "Profile" button

## Expected Result:
Your email and primary contact should be your original email address

## Actual Result:
If you log in with Apple ID, your email and primary contact changes to an unknown address. If you log in with the same gmail address (without the Apple ID login) the mail is the same Gmail one you expect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76b396e2-5960-4f34-85ae-76ccea9e3d19

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f6afd9ebc2bf85c</li>
        <li>Upwork Job ID: 1721959740780179456</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by barttom** [comment]
Hi, I'm Bartek from Callstack and I would like to take a look at this issue. I will debug it and back with a proposal ASAP ;)

**Comment by barttom** [comment]
Long story short: it's not a bug, it's a feature 😄 

This is one of Apple's private policies - you can decide if You share your email from AppleID.
When You log in the first time You should see a prompt to choose privacy level. It never shows again. If You want to change that, You need to remove the app from the Apple ID management panel https://support.apple.com/en-us/HT210426 

When you set the privacy level to show our email - it will be shown in the app, take a look at the record
cc: @lanitochka17 


Uploading Screen Recording 2023-11-08 at 14.00.40.mp4…

**Comment by barttom** [comment]
Uploading 31020_whole_process.mp4…
