### ISSUE TITLE
[HybridApp] CRITICAL: Align native dependencies between Old and New App

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#31023]
## Problem
We have iOS cocoapod and Android gradle dependencies that do not match up between the old and new app, we need to align them to make sure we can combine all the native code.

## Solution
Align the dependency versions between:
1. Airship
2. Google sign in (this uses two different dependencies)

cc @WoLewicki

**Comment by WoLewicki** [comment]
🚀

**Comment by WoLewicki** [comment]
Pr with the changes: https://github.com/Expensify/Mobile-Expensify/pull/12439
