### ISSUE TITLE
[$250] Payment issue #16145

### ISSUE THREAD

**Issue by johncschuster** [Expensify/App#31032]
### This is a payment issue for https://github.com/Expensify/App/issues/16145

**@ashuvssut requires payment via Upwork**

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f166c2ef54aa53dd</li>
        <li>Upwork Job ID: 1722010296877969408</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>ashuvssut | Contributor | 27566189</li>
</ul></li>
    </ul>
</details>

**Comment by ashuvssut** [comment]
Hi

**Comment by ashuvssut** [comment]
@johncschuster I have accepted the offer on upwork

**Comment by ashuvssut** [comment]
@johncschuster Thankyou. I have submitted for review on upwork

![image](https://github.com/Expensify/App/assets/60546840/aca99c52-7fc5-475b-b170-4cf305408db2)

**Comment by johncschuster** [comment]
Payment has been issued! 🎉 Thanks, @ashuvssut!
