### ISSUE TITLE
[ECARD] MEDIUM: App, allow users to edit certain fields of ECard / Company Credit Card transactions

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31054]
Also, prevent editing the amount for both ECard and CC transactions.

Coming from this slack convo: https://expensify.slack.com/archives/C05DWUDHVK7/p1699394971637599?thread_ts=1699300115.470319&cid=C05DWUDHVK7

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/MoneyRequestView.js#L111

Update this check to include any transaction that has a cardID (both ECard transactions and Company Card transactions).

**Comment by dylanexpensify** [comment]
Off hold!

**Comment by grgia** [comment]
Closing as part of my PR for https://github.com/Expensify/App/issues/28836
