### ISSUE TITLE
Update MoneyRequestView.js

### ISSUE THREAD

**Issue by cead22** [Expensify/App#31084]
- [Design Doc](https://docs.google.com/document/d/1iGvpCoQ6Wt-i2wcpvaMKsWZRNs-oAsWoaS_nLue7_E0/edit)
- Let's update MoneyRequestView.js
   - The following should only apply to users in the violations beta
   - Let's add a connection to the transactionViolations and policyCategories Onyx collections as shown in the code snippet below, which will go in the `withOnyx` section of the code at the bottom
   - Let's add the new onyx key for the transaction violation collection
   - Add a new transactionViolation prop
   - Pass the transactionViolation to the MoneyRequestView function 
   - For each field that can have a violation, Inside OfflineWithFeedback and below MenuItemWithTopDescription let's add a View that wraps a Text component to show the violation text, as shown in the snippet below
       - The fields are merchant, amount, category, date, tag, comment, billable, receipt, and tax
   - Fields with violations that go into a new page, like a list page for the cate of category and description for instance, should show a RBR circle to the right, in front of the caret `>`. Screenshots below

```js
withOnyx({
    …
    policyCategories: {
        key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY_CATEGORIES}${report.policyID}`,
    },
    transactionViolation: {
        key: ({report}) => {
            const parentReportAction = ReportActionsUtils.getParentReportAction(report);
            const transactionID = lodashGet(parentReportAction, ['originalMessage', 'IOUTransactionID'], 0);
            return `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transactionID}`;
        },
    },
...
```
```js
{Boolean(ViolationUtils.getViolationForField(transactionViolation, 'amount')) && (
    <View>
        <Text style={[styles.ph5, styles.textLabelError]}>{ViolationUtils.getViolationForField(transactionViolation, 'amount')}</Text>
    </View>
)}
```

![image](https://github.com/Expensify/App/assets/165133/3c9a024a-b926-4279-b828-81b90773eb2e)
![image](https://github.com/Expensify/App/assets/165133/ad577ccd-b681-4916-b5f8-a7433fe702df)

**Comment by cead22** [comment]
@lindboe @cdanwards can you please comment here so I can assign you?

(@NicMendonca sorry about that ping, that was a mistake)

**Comment by cdanwards** [comment]
@cead22 I'm unable to see the 2 images listed at the end of the ticket description, do you mind providing screenshots?

**Comment by cead22** [comment]
Can you try refreshing the page? GH adds a token to the image URLs and if you had this tab open before or you opened a cached version of this page, the token may not work. Let me know if that still doesn't work

**Comment by lindboe** [comment]
@cead22 Refreshing doesn't seem to work.

I'm not familiar with this token idea? The URL that I see that it is opening in my browser is `https://github.com/Expensify/Expensify/assets/165133/557c3ea2-a268-4415-8331-0e5963b20a2c`, if it helps.

**Comment by trevor-coleman** [comment]
@cead22 -- In you description you list:

> For each field that can have a violation, Inside OfflineWithFeedback and below MenuItemWithTopDescription let's add a  View that wraps a Text component to show the violation text, as shown in the snippet below
> * The fields are **merchant, amount, category, date, tag, comment, billable, receipt, and tax**

There doesn't appear to be a `tax` field in this view. Should the tax warning go on the amount?

**Comment by cead22** [comment]
> There doesn't appear to be a `tax` field in this view. Should the tax warning go on the amount?

No the tax ones will go into the tax field once we have it. You can ignore that field for now

**Comment by trevor-coleman** [comment]
As we [discussed here](https://github.com/Expensify/App/issues/31083#issuecomment-1820059778) it's possible to have multiple violations per field.

How should we handle that.

We could (where`violations` is the array of translated violations) :

#### 1. Iterate over the array and map to individual text components :
```ts
{violations && (
    <View>
        {violations.map((violation) =>(
               <Text ... >{violation}</Text>
    </View>
)}
```

#### 2. Join the members of the array with a comma in the text field:

```ts
        <Text ... >{violations.join(', ')}</Text>
)}

**Comment by cead22** [comment]
Let's go with 1. Every field except for receipt will only have 1 violation, and for the receipt ones, we want to show them one below the other, not separated by commas. Does that make sense?

**Comment by trevor-coleman** [comment]
Perfect thanks.

**Comment by cead22** [comment]
Off hold

**Comment by cdanwards** [comment]
@trevor-coleman is working on this.

**Comment by trevor-coleman** [comment]
Yeah it's done just need to update to match the changes from ViolationUtils and the PR will be up today.

**Comment by trevor-coleman** [comment]
Sorry this will take a bit longer, I'm used to being able to make PRs when the code is ready, but completing the checklist will take some time -- probably the rest of today at least.

**Comment by trevor-coleman** [comment]
PR is up: https://github.com/Expensify/App/pull/32594

**Comment by MitchExpensify** [comment]
**Payment summary**:

C+: $500 @aimane-chnaif (Upwork job here)

**Comment by MitchExpensify** [comment]
Paid, contract ended, sorry for the delay!
