### ISSUE TITLE
[HOLD for payment 2023-11-21] [HOLD for payment 2023-11-17] Chat - Concierge Avatar is not centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to ND
2. Log in with any account
3. Select Concierge
4. Click on avatar

## Expected Result:
Avatars is centered

## Actual Result:
Avatars is not centered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/a389ba0b-c814-493a-a828-c9280d762666

![Bug6269292_1699481837407!image__19_](https://github.com/Expensify/App/assets/78819774/1f75e912-40dd-48d8-adc4-e6d37813c4dd)

Production 

![image (4)](https://github.com/Expensify/App/assets/78819774/4872ea6a-e141-41d1-8971-66c7c1894c38)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
If putting `alignItems:'center'` in  `styles.attachmentCarouselContainer` would fix this issue but introduce a regression elsewhere, the I'm inclined to go with @ZhenjaHorbach's proposal.

**Comment by garrettmknight** [comment]
I don't think this needs to stop us deploying. @deetergp you reckon?

**Comment by Beamanator** [comment]
@ZhenjaHorbach you mentioned that putting `alignItems: 'center'` in `attachmentCarouselContainer` style would cause a regression. Can you explain please? I tested briefly and haven't seen any regressions

**Comment by Beamanator** [comment]
@ZhenjaHorbach I can reproduce, thanks!

**Comment by Beamanator** [comment]
@ZhenjaHorbach it looks like your fix works very well, can you please submit a PR quickly & test on all platforms? 🙏

**Comment by Beamanator** [comment]
@ZhenjaHorbach so sorry, it looks like we have another idea for solving the regression which would be better, mentioned by the PR author [here](https://github.com/Expensify/App/pull/30995#issuecomment-1803979079)

**Comment by Beamanator** [comment]
CPing [fix PR](https://github.com/Expensify/App/pull/31130)

**Comment by garrettmknight** [comment]
Since we didn't implement @ZhenjaHorbach's proposal so no payments on this one.
