### ISSUE TITLE
 Workspace - Process is looped when attempting to split Distance request in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31025

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Request money > Distance.
4. Enter addresses and click Next.

## Expected Result:
User is able to proceed beyond Split bill - Distance.

## Actual Result:
User is unable to proceed beyond Split bill - Distance. The process is looped.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 

https://github.com/Expensify/App/assets/93399543/e41638e8-e1a0-4326-83e6-a7698b0abfb9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@neil-marcellini any ideas?

**Comment by marcaaron** [comment]
These two seem related to distance:

https://github.com/Expensify/App/pull/30754
https://github.com/Expensify/App/pull/30881

I can try reverting both.

**Comment by marcaaron** [comment]
I am pretty lost. This option doesn't seem to exist locally so I can't test why it's broken.

**Comment by marcaaron** [comment]
Ah you can split a distance request in a workspace chat. Did not realize this 👀

**Comment by marcaaron** [comment]
Pretty sure this was introduced here https://github.com/Expensify/App/pull/31025

**Comment by marcaaron** [comment]
I could not test this on production because the option didn't exist.

**Comment by puneetlath** [comment]
Ok so what happened here is: 
- before the option to split a bill was only available on Control workspaces
- now the split bill option is available on all workspaces

On workspaces where you can split a bill, we've always had the distance option, so that bug exists on production. What is new is the ability to split a bill work all workspaces. 

So I'm going to treat this not as a deploy blocker. I started a discussion about what the ideal behavior should be here: https://expensify.slack.com/archives/C02NZ2HGJAZ/p1699533520918679

**Comment by marcaaron** [comment]
Sounds good. Thanks for looking at that @puneetlath 🙇

**Comment by puneetlath** [comment]
@kevinksullivan FYI based on this thread it sounds like this will be solved by the distance P2P project that @neil-marcellini is working on. https://expensify.slack.com/archives/C02NZ2HGJAZ/p1699533520918679

**Comment by kevinksullivan** [comment]
Just read up on that thread, looks like we'll close this out then!
