### ISSUE TITLE
[HOLD for payment 2024-01-28] Implement and use ReportUtils.transactionThreadHasViolations(report)

### ISSUE THREAD

**Issue by cead22** [Expensify/App#31095]
- [Design Doc](https://docs.google.com/document/d/1iGvpCoQ6Wt-i2wcpvaMKsWZRNs-oAsWoaS_nLue7_E0/edit)
- Implementation should look like code snippet below
    - Which probably means we should connect ReportUtils to the BETAS onyx collection
    - Let's also connect it to the TRANSACTION_VIOLATIONS and REPORT_ACTIONS Onyx collections as shown below
    - And let's also add as shown below `ReportUtils.reportHasViolations`
- Then let's use `ReportUtils.transactionThreadHasViolations`
    - In `SidebarUtils.ts` Let's update [this](https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/libs/SidebarUtils.ts#L363)
        - From: `result.brickRoadIndicator = Object.keys(result.allReportErrors ?? {}).length !== 0 ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : '';`
        - To: `result.brickRoadIndicator = Object.keys(result.allReportErrors ?? {}).length !== 0 || ReportUtils.transactionThreadHasViolations(report) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : '';`
        - That way src/components/LHNOptionsList/OptionRowLHN.js should show the RBR
    - In ReportUtils.shouldReportBeInOptionList above [if (isInGSDMode) {](https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/libs/ReportUtils.js#L3359-L3361) we’ll add the if in the snippet below to surface the iou reports with violations on the LHN
- And let's use `ReportUtils.reportHasViolations`
    - In `src/components/ReportActionItem/ReportPreview.js` let's update the code so the [hasErrors](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportPreview.js#L128) value takes into account the report violations `const hasErrors = (hasReceipts && ReportUtils.hasMissingSmartscanFields(props.iouReportID)) || ReportUtils.reportHasViolations(props.iouReportID);`

```js
const transactionViolations = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS,
    callback: (violations, key) => {
        if (!key || !violations) {
            return;
        }

        const transactionID = CollectionUtils.extractCollectionItemID(key);
        transactionViolations[transactionID] = violations;
    },
});

const reportActions = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.REPORT_ACTIONS,
    callback: (actions, key) => {
        if (!key || !actions) {
            return;
        }

        const reportID = CollectionUtils.extractCollectionItemID(key);
        reportActions[reportID] = actions;
    },
});
```
```js
function transactionThreadHasViolations(report) {
    if (!permissions.canUseViolations()) {
        return false;
    }
    if (!report.parentReportActionID ?? 0) {
        return false;
    }
    const parentReportAction = lodashGet(reportActions, `${report.parentReportID}.${report.parentReportActionID}`);
    if (!parentReportAction) {
        return false;
    }
    const transactionID = parentReportAction['originalMessage']['IOUTransactionID'] ?? 0;
    if (!transactionID) {
        return false;
    }
    const reportID = parentReportAction['originalMessage']['IOUReportID'] ?? 0;
    if (!reportID) {
        return false;
    }
    if (!isCurrentUserSubmitter(reportID)) {
        return false;
    }
    return transactionHasViolation(transactionID);
}
```
```js
function transactionHasViolation(transactionID) {
    const violations = lodashGet(transactionViolations, transactionID, []);
    return _.some(violations, violation => violation.type === 'violation');
}
```
```js
function reportHasViolations(reportID) {
    let transactions = TransactionUtils.getAllReportTransactions(reportID);
    return _.some(transactions, (transaction) => transactionHasViolation(transaction.transactionID));
}

```
```js
// Always show IOU reports with violations
if (isExpenseRequest(report) && transactionThreadHasViolations(report)) {
    return true;
}
```

**Comment by cead22** [comment]
@lindboe @cdanwards can you please comment here so I can assign you?

**Comment by cead22** [comment]
Awesome! @cdanwards can you add another condition to transactionThreadHasViolations to return false if the report is on a state that isn't open or processing? We only wanna show RBR on the left hand nav to the report submitter, and only if the report is open or processing

**Comment by cdanwards** [comment]
@cead22 Definitely! I'll add that in.

**Comment by cead22** [comment]
Work in progress

**Comment by cead22** [comment]
Still a work in progress

**Comment by cead22** [comment]
@trevor-coleman can you comment here so I can assign you please?

**Comment by cead22** [comment]
This is a WIP, and Trevor is coming back tomorrow

**Comment by trevor-coleman** [comment]
Ok resolved the error-- it looks like the report action propType was defined incorrectly.

**Comment by cead22** [comment]
WIP

**Comment by cead22** [comment]
Work in progress

**Comment by cead22** [comment]
Still WIP

**Comment by cead22** [comment]
PR was merged and is on staging. We found a bug that we're fixing now

**Comment by cead22** [comment]
@strepanier03 can you please handle payment to @situchan for the [PR](https://github.com/Expensify/App/pull/31448) review, and please make it **double** the standard amount we pay for these. This was was a pretty complex review and this is something I offered @situchan last month to put the review at the top of the priority list. Thanks

**Comment by strepanier03** [comment]
Will do @cead22!

**Comment by strepanier03** [comment]
@situchan - An offer has been sent. I'll check later today to finish paying out and closing up.

**Comment by strepanier03** [comment]
Paid and contract closed. Thanks everyone!
