### ISSUE TITLE
[HOLD for payment 2023-11-30] Add Required fields to MoneyRequestConfirmationList 

### ISSUE THREAD

**Issue by cead22** [Expensify/App#31090]
- [Design Doc](https://docs.google.com/document/d/1iGvpCoQ6Wt-i2wcpvaMKsWZRNs-oAsWoaS_nLue7_E0/edit)
- Update MenuItem.js
    - Let's add a prop `rightLabel` 
    - Let's add code similar to the snippet below above the line [`{Boolean(props.shouldShowRightIcon) &&`](https://github.com/Expensify/App/blob/b5a0a746a82d64104c6d9400d86acc83a7d312a5/src/components/MenuItem.js#L367)
- Update MoneyRequestConfirmationList.js where we’ll show the category/tag/tax menu items 
   - Let's pass the new prop `rightLabel={permissions.canUseViolations() && Boolean(props.policy.requiresCategory) ? translate('required') : ''}` to the MenuItem used for categories
   - Let's do the same for tags `rightLabel={permissions.canUseViolations() && Boolean(props.policy.requiresTag) ? translate('required') : ''}`
   - `permissions.canUseViolations` will be implemented in https://github.com/Expensify/App/issues/30663

```js
{Boolean(props.rightLabel) && (
    <View style={[styles.popoverMenuIcon, styles.pointerEventsAuto]}>
        <Text>{props.rightLabel}</Text>
    </View>
)}
```

<img width="393" alt="image" src="https://github.com/Expensify/App/assets/165133/33140911-4b6c-4ef3-b382-2a57cc704788">

**Comment by cead22** [comment]
@lindboe @cdanwards can you comment here so I can assign you?

**Comment by cdanwards** [comment]
Commenting for assignment

**Comment by cdanwards** [comment]
Getting PR up now.

**Comment by cdanwards** [comment]
This PR was merged!

**Comment by cead22** [comment]
Wohoo 🎉

**Comment by cead22** [comment]
Looks like this wasn't the cause of the blocker (thanks @luacmartins). It was the fact that policy wasn't available when splitting a bill with a Workspace

**Comment by situchan** [comment]
@cead22 can you please reopen & add `New feature` label for payment? Thanks

**Comment by cead22** [comment]
Do I need to close it again?

**Comment by adelekennedy** [comment]
payment made
