### ISSUE TITLE
Implement Client-side Violations when creating money requests

### ISSUE THREAD

**Issue by cead22** [Expensify/App#31092]
- [Design Doc](https://docs.google.com/document/d/1iGvpCoQ6Wt-i2wcpvaMKsWZRNs-oAsWoaS_nLue7_E0/edit#heading=h.j9rtpat4lr14)
- The following should only apply to users in the violations beta
- Let's connect MoneyRequestConfirmPage to the POLICY, POLICY_CATEGORIES, and POLICY_TAGS Onyx collections so we can get
    - `requiresTag`, `requiresCategory`, `hasMultipleTagLists`, and `isTaxTrackingEnabled` from the policy
    - The policy categories, and
    - The policy tags
- In `src/pages/iou/steps/MoneyRequestConfirmPage.js` let's pass `props.policy.policyID` to `IOU.requestMoney` > from there to `getMoneyRequestInformation` > and from there to `buildOnyxDataForMoneyRequest`
- In `buildOnyxDataForMoneyRequest` 
    - We’ll check If policyID is not available, like for the case of P2P, and return early in that case
    - Then call `ViolationUtils.getViolationsOnyxData(transaction, [], policyRequiresTags, policyTags, policyRequiresCategories, policyCategories)` and push the return value to optimisticData
     - Note: we're not gonna block users from submitting a money request with violations
     - Refer https://github.com/Expensify/App/issues/31083 to see the data returned by `getViolationsOnyxData`
     - We can set the value of failure data to an object like the snippet below, to remove the violations if the request isn't created
- The idea here is that when requests are created, the transactions calculated on the client by `ViolationUtils.getViolationsOnyxData` should show right away (eg, missing tag, missing category, category out of policy,...)

```js
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transactionID}`,
    value: [],
}
```

**Comment by cead22** [comment]
@lindboe @cdanwards can you comment here so I can assign you?

**Comment by cdanwards** [comment]
Commenting for assignment

**Comment by cdanwards** [comment]
Beginning work on this

**Comment by cdanwards** [comment]
Hey @cead22 I've been working on this and had a question about approach.

Right now, we're connecting `POLICY_CATEGORIES` and `POLICY_TAGS` collections in the `MoneyRequestPage` but not using them, nor passing them down to the subsequent function calls. Will we be using them in another step in this file?

I had a thought that maybe we could update the [policy PropTypes](https://github.com/infinitered/ExpensifyApp/blob/ccb4206ff8e635e566fb632670f7f9e6fc6018f1/src/pages/workspace/withPolicy.tsx#L17) to include `requiresTag`, `requiresCategory`, `hasMultipleTagLists`, and `isTaxTrackingEnabled` and subsequently in `IOU.buildOnyxDataForMoneyRequest` we could call [ReportUtils.getPolicy](https://github.com/infinitered/ExpensifyApp/blob/ccb4206ff8e635e566fb632670f7f9e6fc6018f1/src/libs/ReportUtils.js#L115) to get those policy properties.

Similarly we could call `ReportUtils.getPolicyTags` and `ReportUtils.getPolicyCategories` in the same manner so that we have access to pass those into the `ViolationsUtils.getViolationsOnyxData`

Here's the gist of what it would look like:
```
    if (!policyID) {
        return [optimisticData, successData, failureData];
    }
    const policy = ReportUtils.getPolicy(policyID);
    const policyTags = ReportUtils.getPolicyTags(policyID);
    const policyCategories = ReportUtils.getPolicyCategories(policyID);


    const violationsOnyxData = ViolationsUtils.getViolationsOnyxData(transaction, [], policy.requiresTags, policyTags, policy.requiresCategory, policyCategories);

    if (violationsOnyxData) {
        optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transaction.transactionID}`,
            value: violationsOnyxData,
        });
        failureData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS}${transaction.transactionID}`,
            value: [],
        });
    }
```

Let me know what your thoughts are!

**Comment by cead22** [comment]
> Right now, we're connecting `POLICY_CATEGORIES` and `POLICY_TAGS` collections in the `MoneyRequestPage`

You mean MoneyRequestConfirmPage?

> but not using them, nor passing them down to the subsequent function calls. Will we be using them in another step in this file?

You mean as part of this PR you're working on? I don't see the connection to those collection in main. If that's the case, 


> had a thought that maybe we could update the [policy PropTypes](https://github.com/infinitered/ExpensifyApp/blob/ccb4206ff8e635e566fb632670f7f9e6fc6018f1/src/pages/workspace/withPolicy.tsx#L17) to include `requiresTag`, `requiresCategory`...

I don't see the benefit of this, but I'm kind of a react noob, can you perhaps spell it out?

> Similarly we could call `ReportUtils.getPolicyTags` and `ReportUtils.getPolicyCategories`

I don't see why it's better to have these getters, instead of accessing them like `policy.requiresCategory` & `policy.requiresTag` since we already have the policy object with those properties. If we had a policy object and were returning it from `ReportUtils.getPolicy(policyID);`, it'd make sense to have `policy.requiresCategory()` & `policy.requiresTag()` methods on the policy object itself

**Comment by cdanwards** [comment]
@cead22

> You mean MoneyRequestConfirmPage?

Yes! Sorry, I thought I was referring to the correct component.

> You mean as part of this PR you're working on? I don't see the connection to those collection in main. If that's the case, let me know and I'll check the design doc to see if we're going to use them somewhere else, and we just haven't added the code for it yet

I think this was just me making an assumption. Those properties weren't listed as being passed down through the functions but they are needed in the subsequent `ViolationsUtils.getViolationsOnyxData` call. And after looking through how those getter methods are working I think the point I was getting to was a bit of a moot point 😅 So we can do as you specified originally.

>>had a thought that maybe we could update the [policy PropTypes](https://github.com/infinitered/ExpensifyApp/blob/ccb4206ff8e635e566fb632670f7f9e6fc6018f1/src/pages/workspace/withPolicy.tsx#L17) to include requiresTag, requiresCategory...

>I don't see the benefit of this, but I'm kind of a react noob, can you perhaps spell it out?

While originally I was thinking this would be most useful when using the getter `getPolicy` (which we won't do), I do still think this would be valuable to document in the type that a policy can have these properties.

**Comment by cead22** [comment]
> While originally I was thinking this would be most useful when using the getter `getPolicy` (which we won't do), I do still think this would be valuable to document in the type that a policy can have these properties.

Thanks for clarifying, that makes sense to me, so long as it doesn't break anything (and let's not block on it)

**Comment by cdanwards** [comment]
@cead22 Great! This is mostly finished, just making sure [31656](https://github.com/Expensify/App/pull/31656) doesn't have any last changes then I'll get this up to a PR.

**Comment by cead22** [comment]
Off hold

**Comment by lindboe** [comment]
Commenting for assignment

**Comment by cead22** [comment]
@trevor-coleman can you comment here so I can assign you please?

**Comment by lindboe** [comment]
The PR is done, @cead22 can this be closed?

**Comment by cead22** [comment]
Yes
