### ISSUE TITLE
[$500] Compose- New user is not shown in user suggestion list in online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31107]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap Preferences
4. Toggle on forced offline
5. Navigate to LHN
6. Tap fab
7. Tap start chat
8. Enter a new user and select the user
9. Enter @ and new user id in compose box
10. Note new user id is displayed with avatar in user suggestions
11. Navigate back to LHN
12. Tap Profile icon
13. Tap preferences
14. Toggle off forced offline
15. Navigate to LHN
16. Tap fab
17. Tap start chat
18. Enter a new user and select it
19. Enter @and new user id in compose box

## Expected Result:
The user suggestions list must display new user id in suggestion list in online.

## Actual Result:
The user suggestions list does not display new user id in suggestion list in online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/202d7139-d15b-487a-bf36-d28f1c54b17e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3e42538d92e0cdb</li>
        <li>Upwork Job ID: 1722564586353926144</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by anmurali** [comment]
https://github.com/Expensify/App/issues/30720 is on production. @aimane-chnaif can we work on this now or is this resolved by the fix in 30720?
