### ISSUE TITLE
[Awaiting Checklist Completion] [$500] Compose-User suggestions displays all number contacts with suffix @ expensify.sms

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-condition: Have many phone number contacts
1. Go to https://staging.new.expensify.com/

2. Tap on a group chat
3. Enter @
4. Scroll user suggestions and search for numbers contacts
5. Note the suffix part of number contacts
6. Tap on any number contact

## Expected Result:
The user suggestions must not display number contacts with suffix @ expensify.sms.

## Actual Result:
The user suggestions displays all number contacts with suffix @ expensify.sms.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/e5aa8e88-8995-4dbf-a47c-57288579775f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011be12bd2a89d07fc</li>
        <li>Upwork Job ID: 1722543126423429120</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27806332</li>
<li>dukenv0307 | Contributor | 27806334</li>
</ul></li>
    </ul>
</details>

**Comment by 5war00p** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user mention suggestions are displaying suffix(@expensify.com) for numbers
### What is the root cause of that problem?
If user doesn't set the displayname then we are fallbacking to `details.login` which can be email or phone.

https://github.com/5war00p/App/blob/197d6c1481d902cf1a7f5264f166c8818ea1f5dd/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L166-178

In here it's becoming an phone and adding the suffix without a check
### What changes do you think we should make in order to solve the problem?


We can have a check at the `alternativeText`, if it is email then add suffix if not we not we can show the phone number
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by twisterdotcom** [comment]
@shubham1206agra how are these proposals looking to you?

**Comment by shubham1206agra** [comment]
Give me some time. I will give my review tomorrow first thing.

**Comment by shubham1206agra** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/31100#issuecomment-1803450271) seems good to me.

🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment]
> @shubham1206agra Issue here is to show alternate text as same as text, why do we need to handle this logic instead we can call `getDisplayName` directly right by passing specific personal details?

Why do we need to show the same text and alternative text? It doesn't make sense.

**Comment by iwiznia** [comment]
> We can have a check at the alternateText, if it is email then add suffix if not we not we can show the phone number which can be handled by getDisplayName function from PersonalDetails.js

I am not sure I follow, login will ALWAYS be an email. 
Also, what is the correct behavior for a user that only has set a phone number? Show the phone number twice?

**Comment by shubham1206agra** [comment]
> > We can have a check at the alternateText, if it is email then add suffix if not we not we can show the phone number which can be handled by getDisplayName function from PersonalDetails.js
> 
> I am not sure I follow, login will ALWAYS be an email. Also, what is the correct behavior for a user that only has set a phone number? Show the phone number twice?

Show phone number once ig. There is a condition for that.

<img width="1123" alt="Screenshot 2023-11-15 at 3 15 50 PM" src="https://github.com/Expensify/App/assets/58412969/63721252-36b5-4620-93b2-88b200032db1">

But looks like the text (display name) and alternative text are not exactly the same, so the condition is failing for now. This may require a fix from the backend.

**Comment by 5war00p** [comment]
Also, please do change the property name, it should be called as subtitle or subtext. The name `alternate_text` is misleading though.

**Comment by iwiznia** [comment]
> Show phone number once ig. There is a condition for that.

What does `ig` mean? Where's that condition?

**Comment by shubham1206agra** [comment]
> Where's that condition?
In `MentionSuggestions`, this line is present
```js
const styledHandle = item.text === item.alternateText ? '' : getStyledTextArray(item.alternateText, props.prefix);
```

**Comment by iwiznia** [comment]
Ah ok, so why are the texts not the same?

**Comment by shubham1206agra** [comment]
> Ah ok, so why are the texts not the same?

I don't know. I think it comes from the backend itself.

**Comment by shubham1206agra** [comment]
@dukenv0307 can you send a screenshot with this?

**Comment by shubham1206agra** [comment]
@iwiznia Can you assign @dukenv0307 here?

**Comment by iwiznia** [comment]
I want to understand the problem better. If there's already code to handle this, but it is not working, I want to know why. What exactly is the backend call that returns this data and what data it is returning in the text and alternateText and why are they different?

**Comment by shubham1206agra** [comment]
> I want to understand the problem better. If there's already code to handle this, but it is not working, I want to know why. What exactly is the backend call that returns this data and what data it is returning in the text and alternateText and why are they different?

@dukenv0307 Would you like to comment on this?

**Comment by iwiznia** [comment]
Ah I see, thanks for explaining!

**Comment by twisterdotcom** [comment]
Payment Summary:

@shubham1206agra paid $500 [here](https://www.upwork.com/nx/wm/offer/27806332) (Reviewer)
@dukenv0307 paid $500 [here](https://www.upwork.com/nx/wm/offer/27806334) (Contributor)

Awaiting Checklist Completion

**Comment by shubham1206agra** [comment]
@twisterdotcom I think this is more of a UI improvement. If we agree on this, checklist is not required in that case.
