### ISSUE TITLE
[$500]  IOU - Unauthenticated user can view a receipt directly via URL

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31109]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Login to ND Expensify
2. Click FAB button
3. Click Request Money
4. In Scan tab- click Choose file&Upload a receipt
5. Enter an email address
6. Click Split and click Request
7. Click on the uploaded receipt till preview is opened
8. Right click on the preview
9. Click Open image in new tab->Copy the url (or Right click->Copy image address)
10. In new Incognito window, Paste and go to the url copied in the step 9

## Expected Result:
The uploaded receipts should be confidential and can not be viewed by unauthenticated users via URL

## Actual Result:
The uploaded receipts can be viewed by unauthenticated users via URL

Note:The issue does not reproduce in Old Dot Expensify!

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/74ddd522-9e5a-4481-971b-42805e133ac5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121298d809b694199</li>
        <li>Upwork Job ID: 1722569203168522240</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tgolen</details>

**Comment by shubham1206agra** [comment]
This should not be an issue. It passes encryptedAuthToken, which should not be known to the third party. So the user is authenticated.

**Comment by lschurr** [comment]
Any update on that discussion @fedirjh?

**Comment by lschurr** [comment]
Adding Eng for this comment - https://github.com/Expensify/App/issues/31109#issuecomment-1819078974

Not sure what next steps are.

**Comment by tgolen** [comment]
I have opened up an internal issue for this to be discussed: https://github.com/Expensify/Expensify/issues/337959

**Comment by tgolen** [comment]
We discussed this and feel like this is working as intended for the most part.

It would be nice to update react-native-web to be able to pass the token as a header, but this in and of itself won't provide that much extra security.

# Conclusion
If you copy the URL of a receipt and send it to someone else:
- It's virtually the same as sharing the receipt image directly so you are only hurting yourself
- No one else can access the link to the receipt image without permission (and if they could, then you are really in trouble because they can access a whole lot things worse than a receipt image URL)
- The token expires in 2 hours so any exposure would be minimal
