### ISSUE TITLE
[$500] iOS - App - The name of the app is truncated and it's missing a space

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31108]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Look at the name of the app on your phone

## Expected Result:
Tha name should be "New Expensify".

## Actual Result:
The name of the app is truncated and it's missing a space.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6269756_1699524516794!NewExpen](https://github.com/Expensify/App/assets/115492554/2e5e0e94-3e90-4451-8d82-8550a66e9495)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b4b8d3a4a4cdf8e</li>
        <li>Upwork Job ID: 1722566283877715968</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproducible in production

![IMG_0686](https://github.com/Expensify/App/assets/115492554/0e5e8f6f-bf9f-4dc6-bff9-5629e765cddf)

**Comment by erquhart** [comment]
Betting this is because of the yellow dot from TestFlight. It seems to take up space that the title would take up. Curious if the blue dot that shows up when the app was updated since last open would cause this in production, guessing so.

Won't be an issue when the app fully replaces OD, it'll just say Expensify.

**Comment by erquhart** [comment]
@fedirjh but that's the dev app, it's name is "New Expensify Dev" - I'm guessing it's always truncated with that many characters.

**Comment by erquhart** [comment]
iOS removes spaces when it's truncating a name that's too large. The dev app has a red "DEV" badge in the lower right, as seen in your screenshot.

**Comment by benyboariu** [comment]
Running locally on simulator, I manually changed the Product Name for Debug Development, and I put the name like in production, and the name fits, so it's not because the name would be too large.
<img width="453" alt="Screenshot 2023-11-09 at 5 43 34 PM" src="https://github.com/Expensify/App/assets/958322/03602335-4d6f-485d-9803-7c2b4f56a090">

**Comment by erquhart** [comment]
@benyboariu OP screenshot has a yellow dot from TestFlight - I believe that's inline with the app name and causes the truncation.

**Comment by AndriiSenyourit** [comment]
Be honest, has anyone received money for solving the problem, or is it just a scam to get solutions for free?

**Comment by erquhart** [comment]
@AndriiSenyourit Expensify has spent over $8 million on Upwork. Not a scam.

**Comment by puneetlath** [comment]
I agree that it seems that it's getting truncated due to the yellow dot and this isn't a bug. Thanks for the discussion everyone.
