### ISSUE TITLE
[HOLD for payment 2023-11-21] [HOLD for payment 2023-11-17] [$500] Android-IOU-Description entered cannot be seen but displayed in IOU details page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Tap manual
5. Enter an amount
6. Tap next
7. Select an user
8. Tap 3 dots and tap "add receipt"
9. Tap Request
10. Tap IOU to open IOU details page
11. Tap description
12. Enter any text
13. Tap save

## Expected Result:
User must be able to see description entered.

## Actual Result:
Description entered cannot be seen but displayed in IOU details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/e83a288d-fa66-49cc-a5bc-f335928610ef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018aa91dfca07b2ed6</li>
        <li>Upwork Job ID: 1722580951529140224</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 27594134</li>
<li>akinwale | Contributor | 27594656</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment]
Not reproduced in production

https://github.com/Expensify/App/assets/115492554/5a04d10c-03bf-43de-89ff-8002b28aa20f

**Comment by esh-g** [comment]
# Proposal

## Root cause
`verticalAlign` is passed like this in `MoneyRequestDescription`:
```js
                            containerStyles={[styles.autoGrowHeightMultilineInput, styles.verticalAlignTop]}
```

## Changes
We should pass it as 
```js
containerStyles={[styles.autoGrowHeightMultilineInput]}
                            inputStyle={[styles.verticalAlignTop]}
```

**Comment by esh-g** [comment]
I'm available to raise a PR quickly... @Santhosh-Sellavel @mountiny

**Comment by esh-g** [comment]
I'm available to raise a PR quickly

**Comment by mountiny** [comment]
@esh-g can you please raise the PR as quickly as possbile? thanks!

**Comment by esh-g** [comment]
Yes @mountiny Just working on it now

**Comment by mountiny** [comment]
Requesting a CP, @esh-g could you please identify which PR caused this regression?

**Comment by esh-g** [comment]
Yes, the PR that caused this issue is this: https://github.com/Expensify/App/pull/24482
(don't think a regression test is needed for this)

**Comment by mountiny** [comment]
Ok thanks!

**Comment by puneetlath** [comment]
Fix was CP'd. Removing the blocker label.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The issue here was as a result of the react-native-web update done in https://github.com/Expensify/App/pull/24482, not due to a feature implementation nor code changes.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test**
1. Launch the Expensify app.
2. Navigate to an existing money request or create a new one, ensuring that a description is provided before saving.
3. Tap on the description to edit.
4. Verify that the description text is visible in the text input field.
5. Verify that the description text is editable.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@mallenexpensify Just noting here that the correct payment date here should be 2013-11-17, since the PR was initially deployed to production on [2023-11-10](https://github.com/Expensify/App/issues/31114#issuecomment-1805951854). Thanks.

**Comment by mallenexpensify** [comment]
Contributor: @esh-g paid $500 via Upwork
Contributor+: @akinwale paid $500 via Upwork

Regression test update
- https://github.com/Expensify/Expensify/issues/337591 

Thanks!
