### ISSUE TITLE
[$500] Report - The welcome system message in a group conversation is duplicated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in to the main window under any account
3. Log in to a secondary account that is gmail and is not HT(in incognito mode)
4. Under the primary account, create a group with the secondary gmail account
5. Send a message to the created group
6. Check the system message in the group under the secondary login

## Expected Result:
The welcome system message in a group conversation should not be duplicated and should only be displayed as a single message

## Actual Result:
The welcome system message in a group conversation is duplicated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/876ef4b0-7e57-4598-89f1-363573369221

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd8efbc76cffb550</li>
        <li>Upwork Job ID: 1722625764066914304</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by ankushjamdagani** [comment]
## Issue

<img width="1129" alt="image" src="https://github.com/Expensify/App/assets/13179262/f26163e5-78a6-4543-8ecc-3b31c710579f">


## Reason

There are multiple `reportActions` with same message in `https://staging.expensify.com/api?command=OpenReport`.

<img width="740" alt="image" src="https://github.com/Expensify/App/assets/13179262/25844ea8-1feb-4247-ae70-79bde3c37576">

## Fix

1. This should ideally be fixed from the backend to prevent multiple messages
2. From the front-end, we can put checks for `actorAccountID` and `timestamp` and remove duplicates based on this pair. But there is a concern in this - `timestamp` is the same in all 4 messages, but `created` is different for all. A possible reason is that it is based on `reportActionTimestamp`. Then that will make sense.

**Comment by ankushjamdagani** [comment]
Contributor details
Your Expensify account email: jamdaganiankush@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b70d1cf6526c7f68

## Issue

<img width="1129" alt="image" src="https://github.com/Expensify/App/assets/13179262/f26163e5-78a6-4543-8ecc-3b31c710579f">


## Reason

There are multiple `reportActions` with same message in `https://staging.expensify.com/api?command=OpenReport`.

<img width="740" alt="image" src="https://github.com/Expensify/App/assets/13179262/25844ea8-1feb-4247-ae70-79bde3c37576">

## Fix

1. This should ideally be fixed from the backend to prevent multiple messages
2. From the front-end, we can put checks for `actorAccountID` and `timestamp` and remove duplicates based on this pair. But there is a concern in this - `timestamp` is the same in all 4 messages, but `created` is different for all. A possible reason is that it is based on `reportActionTimestamp`. Then that will make sense.

**Comment by joekaufmanexpensify** [comment]
Reproduced. 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/f89432ba-f279-4af3-b516-e211a99b13ae">

**Comment by ankushjamdagani** [comment]
@joekaufmanexpensify Should I create a PR for the frontend fix?

**Comment by joekaufmanexpensify** [comment]
@ankushjamdagani Not yet. Our team will review your proposal, and let you know if we want to proceed with hiring you. If we do, we'll assign you to the issue, at which point you can proceed with creating a PR. This is outlined in our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). I recommend thoroughly reviewing them.

**Comment by joekaufmanexpensify** [comment]
Sure, will do!

**Comment by joekaufmanexpensify** [comment]
@madmax330 it [sounds like](https://github.com/Expensify/App/issues/31125#issuecomment-1807253220) this issue might need a backend fix. Curious if you agree?

**Comment by joekaufmanexpensify** [comment]
Pending internal input

**Comment by madmax330** [comment]
Hmm yeah might be internal, will investigate tomorrow

**Comment by joekaufmanexpensify** [comment]
Sounds great. TY!

**Comment by joekaufmanexpensify** [comment]
Not overdue

**Comment by joekaufmanexpensify** [comment]
Making this weekly since I am OOO the rest of the week.

**Comment by joekaufmanexpensify** [comment]
Next step is for Max to investigate further.

**Comment by joekaufmanexpensify** [comment]
Pending internal prioritization

**Comment by joekaufmanexpensify** [comment]
Still pending internal review/PR

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by madmax330** [comment]
I'm not able to repro this locally so going to just close
