### ISSUE TITLE
Web - Chat - BackHandler console error shows up when refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Iternal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in.
3. Refresh the page.

## Expected Result:
No console error shows up.

## Actual Result:
BackHandler console error shows up when refreshing the page.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-11-09 at 09 34 10](https://github.com/Expensify/App/assets/93399543/f73a5be6-ee00-46d1-897e-25d947447913)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
This is an issue in `react-navigation/native` that is fixed in [this version](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%407.0.0-alpha.5)

It should go away when we update `react-navigation/native`

**Comment by grgia** [comment]
closing this out in that case
