### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Distance - The title 'Distance' changing to 'Merchant' when toggling on Billable

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
**Pre-condition:** 
1. Go to old dot as admin
2. Navigate to collect Workspace settings--Expenses
3. Set "re-bill expenses to clients" to "default to Billable "
**Steps:**
1. Launch app
2. Open employee WS
3. Tap plus icon -- Request money
4. Tap distance request
5. Select start and finish waypoints
6. Tap next
7. Tap distance
8. Tap on distance request created to open distance request detail page
9. Note under distance heading, distance mentioned
10. Tapping on distance, user can add/change waypoints
11. Toggle on Billable
12. Note "distance" heading changed to "merchant "
13. Tap on merchant
14. Edit waypoints option not shown

## Expected Result:
The title 'Distance' shouldn't change to 'Merchant' when toggling on Billable

## Actual Result:
The title 'Distance' changing to 'Merchant' when toggling on Billable

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/076bbb79-2843-495c-ad5c-3cb2788cda13

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01629522855183a4d0</li>
        <li>Upwork Job ID: 1722629339378032640</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27653359</li>
<li>Krishna2323 | Contributor | 27653361</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-Title "Distance" changed to "merchant" when toggle on Billable
### What is the root cause of that problem?
When toggle on Billable, isDistanceRequest will be false. It cause that we display merchant instead of distance
### What changes do you think we should make in order to solve the problem?
We should update the TransactionUtils.isDistanceRequest function return true even when toggle on Billable

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@DylanDylann Thanks for the proposal. Your RCA is correct but not complete. isDistanceRequest is being false indeed but that should not happen in the first place.

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/31128#issuecomment-1804110716)

**Comment by situchan** [comment]
🎀 👀 🎀

**Comment by s77rt** [comment]
🎀 👀 🎀 C+ reviewed

**Comment by s77rt** [comment]
Not overdue. @iwiznia https://github.com/Expensify/App/issues/31128#issuecomment-1804776485

**Comment by iwiznia** [comment]
Proposal looks good, but it is kind of brittle to have to add that logic everywhere... like we already have it [here](https://github.com/Expensify/App/blob/29a510bab771c45285930e31507fe101f0fedb29/src/pages/EditRequestPage.js#L126-L130).
Maybe we should expose just one method in JS that would have this logic in it then all callers would call that method and never call the updateDistanceRequest/editMoneyRequest directly.

Thoughts?

**Comment by s77rt** [comment]
@iwiznia I agree! That would be better.

**Comment by iwiznia** [comment]
Cool @Krishna2323 can you update your proposal to do that please?

**Comment by iwiznia** [comment]
I think it would be better to:
- Do not export the 2 methods we are using now
- Instead, only export the new method
- Update all existing usages of the 2 methods to use the new method

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/27875
- The offending PR has been commented on: https://github.com/Expensify/App/pull/27875#discussion_r1405001562
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: I don't think this is needed. It's seems like a one time bug.

**Comment by garrettmknight** [comment]
Summary of payments:
- Contributor: @Krishna2323 $500 paid via Upwork
- Reviewer: @s77rt $500 paid via Upwork

All paid up
