### ISSUE TITLE
[$500] Distance-Title "Distance" changed to "merchant" when toggle on Billable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Open employee WS
3. Tap plus icon -- Request money
4. Tap distance request
5. Select start and finish waypoints
6. Tap next
7. Tap distance
8. Tap on distance request created to open distance request detail page
9. Note under distance heading, distance mentioned
10. Tapping on distance, user can add/change waypoints
11. Toggle on Billable
12. Note "distance" heading changed to "merchant "
13. Tap on merchant
14. Edit waypoints option not shown

## Expected Result:
In employee Workspace, in distance request detail page, Title "Distance" must not change to "merchant" when toggle on Billable

## Actual Result:
In employee Workspace, in distance request detail page, Title "Distance" changed to "merchant" when toggle on Billable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00f0e3c3-2a28-4026-b9a7-837b5d89f170

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef05e0c3265ef1c9</li>
        <li>Upwork Job ID: 1722627022118227968</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
The same issue reported https://github.com/Expensify/App/issues/31128

**Comment by erquhart** [comment]
@kbecciv this was opened first

**Comment by erquhart** [comment]
Ah nevermind, the other issue has the preconditions, I was wondering why I couldn't repro

**Comment by kbecciv** [comment]
@erquhart Here is TR link https://expensify.testrail.io/index.php?/tests/view/3953249
