### ISSUE TITLE
Web - Distance - The app starts flashing when any changes are made as the admin.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
Create IOU with the receipt as employee

1. Log in as the workspace admin
2. Navigate to the workspace chat with the employee
3. Navigate to the request conversation and fix the errors as the admin

## Expected Result:
The admin can edit the missing information, and everything should work normally

## Actual Result:
The app starts flashing when any changes are made as the admin

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6d50bfdc-445a-4484-8936-636ac70fa107

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is not reproducible in production 

https://github.com/Expensify/App/assets/93399543/70098366-a8f2-492f-add2-358b0dbd779e

**Comment by puneetlath** [comment]
The PR that caused this got reverted. Closing out.
