### ISSUE TITLE
Android - Distance request - Cursor and preview are missing in description field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31132]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on the FAB button > Request Money
3. Start a distance expense
4. Enter any Start and Finish
5. Select the collect workspace
6. Tap on description
7. Start typing

## Expected Result:
Inputted text and cursors should be visible while user type text

## Actual Result:
Cursor and preview are missing in description field.
User can successfully add a description, but still can not see what text is entered in description field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d8412b88-5551-47ed-996b-87a243edd7b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment]
dupe https://github.com/Expensify/App/issues/31114
