### ISSUE TITLE
[$500] Distance - Distance request created is not deleted on tapping delete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login as Employee
3. Tap employee Workspace chat
4. Tap plus icon near compose
5. Select Request money----Distance
6. Enter start and finish waypoints
7. Tap next
8. Tap Distance
9. Tap distance request created to open distance request detail page
10. Tap distance
11. Include "Add stop" waypoint
12. Tap save
13. Tap 3 dots on top right
14. Tap delete request and confirm delete

## Expected Result:
In employee Workspace, the distance request created must be deleted on tapping "delete request"

## Actual Result:
In employee Workspace, the distance request created is not deleted on tapping "delete request"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e94518fd-37d6-4488-9579-1d837536b9d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae5e8a442886691b</li>
        <li>Upwork Job ID: 1722674040702275584</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Okay, let's close.
