### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Group chat - Cursor appears disabled briefly when opening user profile from group member view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31147]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a group chat
3. Click on the group chat header
4. Click Members
5. Click on any user

## Expected Result:
The cursor will not appear disabled during the transition from group member view to user profile

## Actual Result:
The cursor appears disabled briefly when transitioning from group member view to user profile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc0905f3-7f8a-4875-9663-6ea183d5a011

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fd8ea15744b4845</li>
        <li>Upwork Job ID: 1729917653839990784</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
I can reproduce - this seems small though so I wouldn't make this a  deploy blocker

**Comment by adelekennedy** [comment]
@Li357 I don't see an obvious cause for this when I'm looking through the list [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) Am I missing an obvious connection here?

**Comment by getusha** [comment]
We should not revert the change for `useSingleExecution` it was removed for web because it was causing a lot of bugs due to it's usage of InteractionManager.

**Comment by Li357** [comment]
Taking a look now!

**Comment by Li357** [comment]
I agree we shouldn't do a revert here @dukenv0307. Are there other ways to ensure certain actions that have immediate results to not show as disabled?

**Comment by adelekennedy** [comment]
chill Melvin - we're just back from the weekend

**Comment by Li357** [comment]
@dukenv0307 I'm not a huge fan of the new prop, does adding `!props.isDisabled && styles.cursorPointer` cause other regressions?

**Comment by Li357** [comment]
Ok, let's go with that then. I'll go ahead an assign you!

**Comment by getusha** [comment]
@Li357 i am interested in reviewing this

**Comment by situchan** [comment]
I see @thesahindia was assigned as C+ reviewer in PR. I think he can go ahead.

**Comment by Li357** [comment]
Sorry about the delay! @allroundexperts I've selected @dukenv0307's revised proposal. Let me know if you agree

**Comment by getusha** [comment]
@Li357 Since @thesahindia reviewed the [PR](https://github.com/Expensify/App/pull/31773) they should be assigned as a C+ here.

**Comment by allroundexperts** [comment]
@Li357 @dukenv0307's revised [proposal](https://github.com/Expensify/App/issues/31147#issuecomment-1808465023) looks good to me as well. I can help with the review as well if needed.

**Comment by Li357** [comment]
Got it, I'll remove you @allroundexperts and assign @thesahindia -- sorry about the confusion.

**Comment by adelekennedy** [comment]
### Payouts due:

Contributor: $500 @dukenv0307 (Upwork)
Contributor+: $500 @thesahindia (NewDot)

@dukenv0307 jusy hired you for the job in Upwork - @thesahindia will you check the checklist to see if there are any next steps here?

**Comment by adelekennedy** [comment]
@thesahindia bump on the checklist

**Comment by adelekennedy** [comment]
Also removing Andrew as he's no longer handling issues and re-adding the engineering label

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/31147#issuecomment-1846335703).
