### ISSUE TITLE
[$500] Web - IOU - App start flashing when any changes as the admin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition:
Create IOU with the receipt as employee
1. Log in as the workspace admin
2. Navigate to the workspace chat with the employee
3. Navigate to the request conversation and fix the errors as the admin

## Expected Result:
The admin is able to edit the missing information. Nothing strange doesn't happen.

## Actual Result:
The admin is able to edit the missing information. Nothing strange doesn't happen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/d15d429b-9e95-447b-a774-28bc1f9a1ed3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196a9e3104ad62434</li>
        <li>Upwork Job ID: 1722653994643566592</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by dangrous** [comment]
git bisect weirdly did not help here, trying some other ways

**Comment by dangrous** [comment]
It feels like this might be related? https://github.com/Expensify/App/pull/28793

I coudl replicate this on local for a moment and now I can't anymore so weird stuff is happening

**Comment by dangrous** [comment]
okay confirmed, removing `src/components/FlatList/index.web.js` (which was added in #28793) fixes this. The PR mentions that there will be "glitches" until an upstream PR is fixed, I think we might want to revert until that time? Will copy this on the PR.

**Comment by puneetlath** [comment]
Yes, I agree. I think we need to revert as these glitches are not minor.

**Comment by puneetlath** [comment]
The PR that caused this ended up getting reverted. Removing the deploy blocker label.

**Comment by dangrous** [comment]
Closing, will handle on the updated PR for https://github.com/Expensify/App/issues/23220
