### ISSUE TITLE
[$125] Avatars row position is not correct on Add message page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31151]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697851215849069

## Action Performed:
1. Open settings > workspace > select workspace > members > invite
2. Select 8+ members to invite > Click next button
3. Observe the remaining users number appears on the last avatar of the first column

## Expected Result:
The row order should be opposite of the current implementation.

## Actual Result:
The row order is incorrect.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2e596bc2-520e-412a-8daa-665904a43866

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e9eff1827319e87</li>
        <li>Upwork Job ID: 1722680083573006336</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27647680</li>
<li>Krishna2323 | Contributor | 27647684</li>
<li>Krishna2323 | Reporter | 27647687</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatars row position is not correct on Add message page.

### What is the root cause of that problem?
We are incorrectly ordering the `firstRow` & `secondRow` in `MultipleAvatars`.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/components/MultipleAvatars.js#L114-L116

### What changes do you think we should make in order to solve the problem?
We should slice icons with `props.icons.slice(0, rowSize)` for the first row & `props.icons.slice(rowSize)` for the second row.

### Result

**Comment by MitchExpensify** [comment]
Agree its a bug

**Comment by mollfpr** [comment]
Sorry for the delay, reviewing now!

**Comment by mollfpr** [comment]
I tested the [proposal](https://github.com/Expensify/App/issues/31151#issuecomment-1804329484) from @Krishna2323, and it looks good. I agree it's wrong on the slice position.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
The PR has been in production since last week.

![Screenshot 2023-11-29 at 15 03 24](https://github.com/Expensify/App/assets/25520267/66c9f8b2-7381-4a50-be49-beb6a62b7a5e)

I'll get the checklist ASAP.

Meanwhile, @MitchExpensify could you confirm the comment [here](https://github.com/Expensify/App/issues/31151#issuecomment-1807541593)? Thanks!

**Comment by MitchExpensify** [comment]
I can't speak to the technical lift here so curious if @hayata-suenaga agrees this is worth raising the price to $500 🙇

**Comment by hayata-suenaga** [comment]
[The change in the PR is just one line](https://github.com/Expensify/App/pull/31399/files)

Although I agree that it must have been tricky to figure out the bug, I don't 100% agree if this grants the bounty increase.

@mollfpr let me know what do you think

**Comment by mollfpr** [comment]
I agree it is a pretty minor issue, and there is no need to adjust the bounty since the bounty was decided before created.

**Comment by MitchExpensify** [comment]
Do we need a new regression test @mollfpr ?

**Comment by mollfpr** [comment]
@MitchExpensify yes, I'll complete the checklist soon.

**Comment by JmillsExpensify** [comment]
$125 payment approved for @mollfpr based on [this comment](https://github.com/Expensify/App/issues/31151#issuecomment-1850537413).

**Comment by mollfpr** [comment]
Sorry, I completely missed adding the checklist.

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/21402

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/21402/files#r1440569627

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open settings > workspace > select workspace > members > invite
2. Select 8+ members to invite > Click next button
3. Verify the remaining users number appears on the last avatar of the last column
