### ISSUE TITLE
Web - Invite member -  Inviting someone to a workspace is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699489541534729

## Action Performed:
1. Go to staging.new.expensify
2. Set the account to “focus” mode
3. Go to Setting - Workspace - Members
4. Invite someone who does not have an account yet

## Expected Result:
User gets invited.

## Actual Result:
Nothing happens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Broken](https://github.com/Expensify/App/assets/93399543/94f244a1-7554-45c1-acac-96134e993bde)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@francoisl I used my expensifail.com account to do this. And invited a public gmail account that doesn't exist yet to a workspace. If you can't repro though - maybe it doesn't need to be a blocker. I didn't have time to look into why it happens.

**Comment by francoisl** [comment]
Sorry, got assigned as I was jumping into a meeting. Looking now.

**Comment by francoisl** [comment]
I can't repro either on 1.3.97-6, testing from my expensifail account and inviting a brand new gmail.com account.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/58f7e484-244d-4443-bf57-e690de47f885">


I'm going to test from a new account for good measure, but yes if it works  I think we can close.

**Comment by francoisl** [comment]
Also works from a brand new account, inviting a new account, focus and Most Recent modes. Going to close for now, feel free to reopen if you can reproduce!
