### ISSUE TITLE
ExpensiMark: allow leading spaces in blockquote in edit mode

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31179]
Required by #27977.

**Problem**
Currently, ExpensiMark accepts an arbitary number of spaces between `>` and the contents of the blockquote and gives the same output in each case. However, when typing a new message, we want to persist the original whitespacing of the message. Given only the HTML output, we cannot revert it to the original Markdown string. Also, removing the trailing spaces affects the position of text cursor and we would need to compensate for the changes by manually moving the cursor accordingly.
```
Input 1: ">Hello world"
Input 2: "> Hello world"
Input 3: ">       Hello world"
Output 1 & 2 & 3: "<blockquote>Hello world</blockquote>"
```

**Solution**
Add a flag named `shouldKeepWhitespace` (disabled by default) to `replace` method and persist trailing whitespace in blockquote when the flag is enabled.

Alternatively, we could pass the number of trailing spaces as an attribute in `<blockquote>` HTML tag, for instance `<blockquote data-trailing-spaces="5">Hello world</blockquote>`.

Note that the problem doesn't occur for `<h1>` tags becuase they can be created only with `# ` prefix (there must be exactly one space character after `#`).

**Test cases**

1. One space
```diff
 Input: "> Hello world "
-Current output: "<blockquote>Hello world</blockquote>"
+Desired output: "<blockquote> Hello world</blockquote>"
```
2. More spaces
```diff
 Input: ">     Hello world "
-Current output: "<blockquote>Hello world</blockquote>"
+Desired output: "<blockquote>     Hello world</blockquote>"
```

https://github.com/Expensify/App/assets/20516055/1f2e4eeb-bffc-4955-9e65-61447a34f6b5

<details><summary>Issue Owner</summary>Current Issue Owner: @Skalakid</details>

**Comment by roryabraham** [comment]
Co-assigning myself to supervise, but this will be worked on by Michał Skałka from SWM

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by roryabraham** [comment]
Posted a thought about potentially reassigning this: https://expensify.slack.com/archives/C04878MDF34/p1703718815187329
