### ISSUE TITLE
ExpensiMark: allow trailing whitespace in blockquote in edit mode

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31178]
Required by #27977.

**Problem**
Currently, ExpensiMark trims all trailing spaces and newlines in blockquote. However, when typing a new message, we want to persist trailing whitespace characters so that the user is able to write new words and proceed to the next line.

**Solution**
Add a flag named `shouldKeepWhitespace` (disabled by default) to `replace` method and persist trailing whitespace when the flag is enabled.

**Test cases**

1. Trailing space
```diff
 Input: "> Hello world "
-Current output: "<blockquote>Hello world</blockquote>"
+Desired output: "<blockquote>Hello world </blockquote>"
```
2. Trailing newline
```diff
 Input: "> Hello world\n"
-Current output: "<blockquote>Hello world</blockquote>"
+Desired output: "<blockquote>Hello world</blockquote><br />"
```

https://github.com/Expensify/App/assets/20516055/48ea3919-342a-450c-991d-849aec063df4

<details><summary>Issue Owner</summary>Current Issue Owner: @Skalakid</details>

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by roryabraham** [comment]
Posted a thought about potentially reassigning this: https://expensify.slack.com/archives/C04878MDF34/p1703718815187329

**Comment by robertKozik** [comment]
@roryabraham, this issue was addressed by https://github.com/Expensify/expensify-common/pull/602. I can't track the following PR for expensify/App, but based on the last version bump in `package.json` (DEC 15th), I think we can assume that the change from https://github.com/Expensify/expensify-common/pull/602 is already deployed.
