### ISSUE TITLE
ExpensiMark: potential problem with parsing links containing `mailto:` prefix followed by an email

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31181]
Required by https://github.com/Expensify/App/issues/27977.

**Problem**
Currently, ExpensiMark tries to parse emails even if they are located inside another link, for instance in the following case:

```diff
 Input: "[someone@example.com](mailto:someone@example.com)"
-Current output: "[<a href=\"mailto:someone@example.com\">someone@example.com</a>](mailto:<a href=\"mailto:someone@example.com\">someone@example.com</a>)"
+Desired output: "<a href=\"mailto:someone@example.com\">someone@example.com</a>"
```

**Solution**
Disable parsing Markdown (including emails) in round brackets of a labeled link, i.e. `[...](<here>)`.

**Comment by roryabraham** [comment]
Co-assigning myself to supervise, but this will be worked on by Michał Skałka from SWM

**Comment by roryabraham** [comment]
It looks like this may have been fixed by https://github.com/Expensify/expensify-common/pull/604. @Skalakid can you please create a follow-up PR to upgrade the version of expensify-common used in E/App so that we can close this issue out?

**Comment by roryabraham** [comment]
Posted a thought about potentially reassigning this: https://expensify.slack.com/archives/C04878MDF34/p1703718815187329

**Comment by tomekzaw** [comment]
Should be fixed with https://github.com/Expensify/expensify-common/pull/626

**Comment by robertKozik** [comment]
Can confirm - this issue for live markdown preview use is solved by https://github.com/Expensify/expensify-common/pull/626
