### ISSUE TITLE
ExpensiMark: potential bug with highlighting `@here` followed by a single letter

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31180]
Currently, ExpensiMark highlights `@here` even if the trailing character is not a punctuation character, for instance in `@herea`, but doesn't highlight it when there's two or more characters, e.g. `@hereab`.

```
Input 1: "@here"
Output 1: "<mention-here>@here</mention-here>"

Input 2: "@herea"
Output 2: "<mention-here>@here</mention-here>a"

Input 3: "@hereab"
Output 3: "@hereab"
```

The correct expected behavior would be not to highlight `@here` if the trailing character is a letter but still highlight it if it's a punctuation character like comma or exclamation mark.

```diff
Input: "@herea"
-Current output: "<mention-here>@here</mention-here>a"
+Desired output: "@herea"
```

```
Input: "@here!"
Output: "<mention-here>@here</mention-here>!"
```

<details><summary>Issue Owner</summary>Current Issue Owner: @Skalakid</details>

**Comment by roryabraham** [comment]
Co-assigning myself to supervise, but this will be worked on by Michał Skałka from SWM

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by roryabraham** [comment]
Posted a thought about potentially reassigning this: https://expensify.slack.com/archives/C04878MDF34/p1703718815187329

**Comment by robertKozik** [comment]
This issue was addressed by https://github.com/Expensify/expensify-common/pull/603. I can't track the following PR for expensify/App, but based on the last version bump in `package.json` (DEC 15th), I think we can assume that the change from https://github.com/Expensify/expensify-common/pull/603 is already deployed.
