### ISSUE TITLE
[$500] Android - Notes - Cursor is not shown in "Notes" field and text entered is also not displayed.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a 1:1 report
3. Tap header
4. Tap private notes
5. Tap My note
6. Tap notes
7. Type any text

## Expected Result:
Cursor must be shown in "Notes" field and text entered must be displayed

## Actual Result:
Cursor is not shown in "Notes" field and text entered is also not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dcf2dfd8-3e84-42f9-b7f7-5a3ddfdb6cba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c83f6aa2bc7c60c2</li>
        <li>Upwork Job ID: 1723042800626786304</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27789824</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/31197#issuecomment-1806216157) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by dylanexpensify** [comment]
@mananjadhav can we get 👀 please 🙇‍♂️

**Comment by mananjadhav** [comment]
I'll have this reviewed again by tomorrow. Finishing up some PRs.

**Comment by mananjadhav** [comment]
@dukenv0307 Atleast based on what I saw the comment was updated 12:14AM IST and your proposal was posted by 12:16 AM IST. I think we should be fixing this case by case, but I'll leave this decision to @aldo-expensify.

**Comment by aldo-expensify** [comment]
Sorry, I was planning to look into this today, but I couldn't find the time. I'll check tomorrow morning!

**Comment by aldo-expensify** [comment]
@mananjadhav why do you think we should fix this case by case? do you think we may break something if we include `styles.verticalAlignTop` automatically if `BaseTextInput` if it has `autoGrowHeight`?

If it doesn't break anything, it does sound better to me to do the change in `BaseTextInput` so we don't keep causing this bug.

**Comment by mananjadhav** [comment]
Yes because it could break and that issue is not being reported? Both the proposals are almost the same about adding the style, but yeah if we are good with `BaseTextInput`, let's do that.

**Comment by aldo-expensify** [comment]
From searching in our code, I see each usage of `autoGrowHeight` paired with `inputStyle={[styles.verticalAlignTop]}` or some similar looking version of it (`textAlignVertical="top"` `inputStyle={[this.props.themeStyles.verticalAlignTop]}`)

Do you know if `textAlignVertical="top"` is equivalent to `inputStyle={[styles.verticalAlignTop]}`? I see that in [WorkspaceNewRoomPage](https://github.com/Expensify/App/blob/8c9925d29c8f51349c742b0203a2d35ef6a651c2/src/pages/workspace/WorkspaceNewRoomPage.js#L208-L218) we only have the first


Having looked at these it does pretty safe to include `verticalAlignTop` automatically if `autoGrowHeight` is true.

**Comment by aldo-expensify** [comment]
@mananjadhav I think I prefer to solve this at the base component instead of case by case. I'm going to assign @dukenv0307  unless you got some more concerns?

**Comment by dylanexpensify** [comment]
Nice! @dukenv0307 let's get it!

**Comment by dylanexpensify** [comment]
Payment upcoming!

**Comment by mananjadhav** [comment]
@dylanexpensify this is ready for payout. I don't think we have an offending PR for this one. Considering we've updated the base component, and it's a small UI issue, I don't think we need a regression test here.

@dylanexpensify Can you please post the payment summary?

**Comment by dylanexpensify** [comment]
Yes, apologies! Doing today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dukenv0307 $500
- Contributor+: @mananjadhav $500

Please apply!

**Comment by dylanexpensify** [comment]
Done!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.
