### ISSUE TITLE
[$500] Chat -  If there is a previous money request on chat, the last message is not visible in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29939
## Action Performed:
Pre-requisite: must be logged in and have a chat where you have previously requested money
1. Open a chat where you have a previous money request
2. Send any message (note that it appears in LHN)
3. Create a new money request
4. Disable internet connection
5. Delete the last money request

## Expected Result:
The last sent message should be visible in LHN

## Actual Result:
The previous money request is visible in LHN, not the last message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/4e52ec0a-4fba-4090-9a63-2c6eee25dcab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170cc5bfea21c8189</li>
        <li>Upwork Job ID: 1723039479388102656</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by s77rt** [comment]
This seems to be working as expected.

**Comment by s77rt** [comment]
@Christinadobrzyn Can we close this?

**Comment by Christinadobrzyn** [comment]
Awesome, thanks @s77rt and @tienifr! I'll close!
