### ISSUE TITLE
[$500] mWeb/Chrome - Task-Search page is not opened when long pressing on Assignee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap plus icon near compose
4. Tap assign task
5. Enter title
6. Tap next
7. Tap Confirm task
8. Long press the assignee

## Expected Result:
Search page must be opened and cursor focus in compose box must not be lost when long pressing on Assignee

## Actual Result:
Search page is not opened and cursor focus is lost in compose box when long pressing on Assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4e76a1f-42f9-4bea-a775-51992a147d29

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017674a510353532ed</li>
        <li>Upwork Job ID: 1723063391010938880</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@parasharrajat because it works on other platforms but not on mWeb/Chrome


https://github.com/Expensify/App/assets/78819774/26954c0f-7972-4dc2-b32e-1f4308658249

https://github.com/Expensify/App/assets/78819774/f1c865d8-e6f0-485c-b2d1-5f73d68c3e3d

**Comment by bfitzexpensify** [comment]
I tend to agree that in isolation this seems fine, but yeah, we should have consistency across platforms.

**Comment by bfitzexpensify** [comment]
@parasharrajat how are things looking here?

**Comment by roryabraham** [comment]
Agree with @parasharrajat and @marcaaron that we should close this as expected behavior.

The explanation for the platform difference is that longPress is only a distinct gesture on touchscreens. Furthermore, the pattern we've done our best to establish consistently across the codebase for "secondary interactions" is:

- longPress on touch screens
- right-click with a mouse/trackpad

For the most part, longPress === rightClick

You wouldn't expect a right-click on assignees to open the search page, so it shouldn't for a longPress.
