### ISSUE TITLE
[$500] Report - User is not redirected to the attachment when clicking on the link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under the @applause.expensifail.com account
3. Send an attachment to any conversation
4. Send 10+ messages to the same conversation
5. Copy the link to the attachment and send it to another conversation
6. Navigate to the link in a conversation

## Expected Result:
When clicking on a link, the user should go directly to the message with the attachment, not to the last message in the conversation.

## Actual Result:
When clicking on a link to an attachment, the user is redirected to the conversation, not to the message with the attachment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/49cb8255-8951-480b-b824-6a16e282f4eb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015de557b0aff1a6b2</li>
        <li>Upwork Job ID: 1723068488915767296</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by akinwale** [comment]
@dukenv0307 If it's not too much trouble, could you attach a video of your working solution?

**Comment by peterdbarkerUK** [comment]
+1 to @bernhardoj - isn't this expected until comment linking is deployed?

**Comment by peterdbarkerUK** [comment]
Heyo, as @bernhardoj pointed out, this is expected behaviour until we [implement comment linking](https://github.com/Expensify/App/issues/23229). Closing, please re-open if you disagree!
