### ISSUE TITLE
[$500] Workspace - Bank account setup page appears briefly when opening BA when BA is already set up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31207]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace.
3. Click Bank account.
4. Click Connect online with Plaid.
5. Continue bank account setup with Plaid until it is successful.
6. Return to workspace settings.
7. Click Bank account again.

## Expected Result:
User is redirected to disconnect bank account screen.

## Actual Result:
Bank account setup page shows up briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/4a455894-2f06-4dbc-8392-0effa37d1a7f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6c09018ece00b54</li>
        <li>Upwork Job ID: 1723072485931921408</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by erquhart** [comment]
@izarutskaya completing this flow requires successful Onfido verification, which it doesn't seem is possible without submitting my real ID and biometric data. Your steps to reproduce don't include Onfido - is there a way to reproduce this without going through these extra verified bank account steps?

**Comment by jliexpensify** [comment]
Great question @erquhart - in Old Dot, there's a method to bypass Onfido to manually add an account but I can't see that option in New Dot. Have asked our team [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1699906656642599) re: Onfido.

**Comment by roryabraham** [comment]
This appears to be a legitimate bug, but I don't think we should block deploy on it.

**Comment by jliexpensify** [comment]
So apparently Contributors can't troubleshoot banking bugs since we don't provide Onfido test credentials publicly. If they are US-based, they can use their own details, otherwise it's a no-go.

Instead, it's been advised to make this `Internal` ([Slack thread](https://expensify.slack.com/archives/C01SKUP7QR0/p1646166723334799))

**Comment by jliexpensify** [comment]
I don't think this is a deploy blocker but bumping @tylerkaraszewski as the assigned engineer

**Comment by tylerkaraszewski** [comment]
I'm not really sure what the course of action here is, either. I guess I need to fix this now?

**Comment by jliexpensify** [comment]
Yep I think so @tylerkaraszewski - I'll drop this down to `Weekly` since it's not an actual deploy blocker, but I believe you'll need to push out a PR.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by tylerkaraszewski** [comment]
I have not worked on this. What's the priority of stuff like this with a waves focus?

**Comment by jliexpensify** [comment]
Thanks @aldo-expensify - can you link the PR, or unassign Tyler/re-assign the C+ from the PR?

**Comment by aldo-expensify** [comment]
I tried to find it, but the file's [history](https://github.com/Expensify/App/commits/10310d874b5dac972293f2ecb131d67c98ad5cf0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js) is a bit messy because of a few reverts that have happen in the last couple of months.

**Comment by jliexpensify** [comment]
@aldo-expensify would you recommend posting in #bug-zero and asking who worked on the PR and linking this job?

**Comment by jliexpensify** [comment]
[Asked here](https://expensify.slack.com/archives/C01SKUP7QR0/p1701728969386179)

**Comment by jliexpensify** [comment]
Ooh nice, thanks so much @ntdiary - @izarutskaya do you mind confirming this is fixed?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
