### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Web - Chat - 'Uh-oh, something went wrong!' is displayed after clicking Chat bubble

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Logout out of NewDot
2. Login to OD Expensify
3. Click the message bubble in the bottom right
4. Verify a new tab opens and you are brought to the NewDot concierge chat

## Expected Result:
NewDot concierge chat is displayed without error

## Actual Result:
A new tab opens and user is brought to the NewDot Expensify, but 'Uh-oh, something went wrong!' page is displayed
Uh-oh, something went wrong!
If the problem persists, reach out to [concierge@expensify.com](mailto:concierge@expensify.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3f42a0aa-57f1-495c-954d-dc23b4af343c

![Bug6271744_1699646941414!after_click_Bubble](https://github.com/Expensify/App/assets/78819774/7ed0dedc-a33c-4523-9678-b394c86c9d66)

[log.txt](https://github.com/Expensify/App/files/13322922/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b417e0df7589f4a</li>
        <li>Upwork Job ID: 1723074016090570752</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Something went wrong when transitioning from OldDot to NewDot

### What is the root cause of that problem?
App is trying to execute a filter operation on array that does not exist:

https://github.com/Expensify/App/blob/4f345f8463731803872e5972df67fa22fbeeaef2/src/libs/ReportActionsUtils.ts#L463-L465

This results in: `ReportActionsUtils.ts:458 Uncaught TypeError: sortedReportActions.filter is not a function` error.

### What changes do you think we should make in order to solve the problem?
Add default value for the `sortedReportActions` argument:

```javascript
function getFirstVisibleReportActionID(sortedReportActions: ReportAction[] = [], isOffline: boolean): string {
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by deetergp** [comment]
Another solid proposal, @zukilover. Thanks!

**Comment by zukilover** [comment]
PR is ready https://github.com/Expensify/App/pull/31294

**Comment by MitchExpensify** [comment]
**Payment summary:**

- $500 @allroundexperts C+ NewDot
- $500 @zukilover C Upwork

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/25554
2. https://github.com/Expensify/App/pull/25554/files#r1405479473
3. I don't think a Slack discussion is needed here. Thorough testing would have prevented this.
4. A regression test would be helpful. The steps mentioned in the OP look clear enough to me!

**Comment by deetergp** [comment]
Thank you for the update @allroundexperts 👍 @lanitochka17 Can we add your reproduction steps to the regression tests?

**Comment by MitchExpensify** [comment]
Upwork offer sent for payment, @zukilover. Lemme know when you accept 👍 

Added QA test update request here https://github.com/Expensify/Expensify/issues/343043

**Comment by zukilover** [comment]
@MitchExpensify accepted, thank you.

**Comment by MitchExpensify** [comment]
Paid and contract ended!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31208#issuecomment-1824852186).
