### ISSUE TITLE
[Payment due meow] Task - Description - When strikethrough is entered, the markdown is displayed incorrectly in the task description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on fab
3. Tap assign task
4. Enter title and tap next
5. Select share somewhere
6. Tap confirm task
7. Tap description
8. Enter # 456
~fgjjjh~
9. Tap save

## Expected Result:
When strikethrough markdown is entered, same strikethrough markdown must be displayed in task description.

## Actual Result:
When strikethrough is entered, the markdown is displayed incorrectly in the task description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/138a0634-b8fb-441c-bc60-8629b0d5bbf5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproduce in production

https://github.com/Expensify/App/assets/93399543/598f7cca-eae4-4350-9cb2-b3811bf5d6de

**Comment by chiragsalian** [comment]
thank you for that @aimane-chnaif.
Yeah i think a revert would be nice because i don't want to rush a quick fix and break more things. I'll test and prepare a revert PR.

**Comment by chiragsalian** [comment]
The revert PR to review is here - https://github.com/Expensify/App/pull/31219. I'll clean it up in the meantime.

**Comment by chiragsalian** [comment]
oops this is resolved.

**Comment by mallenexpensify** [comment]
Reopened so I can resolve payment. Give me a min to do so @aimane-chnaif

**Comment by mallenexpensify** [comment]
@aimane-chnaif, can you please accept the job and reply here once you have?  
 https://www.upwork.com/jobs/~0118c655b415acc399

Pay is $500 for C+ review on deploy blockers
<img width="697" alt="image" src="https://github.com/Expensify/App/assets/22508304/d6908a9f-2a63-4a38-97a7-31d266eed2b0">

**Comment by mallenexpensify** [comment]
Contributor+: @aimane-chnaif paid $500 via Upwork.  
Thanks!
