### ISSUE TITLE
[$500] Desktop - Deeplinks - Concierge chat opens when paste other chat link in web and click "allow"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in on desktop and web to the same account
1. Paste any deeplink conversation with other user on your account
2. Click "Allow"

## Expected Result:
Desktop app should opens and lands on the same conversation as web

## Actual Result:
User redirected to the concierge conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c4884770-fa47-4266-a125-4e06698a94ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01febb654d868b11de</li>
        <li>Upwork Job ID: 1723100216748978176</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by beodw** [comment]
Can't reproduce. Seems to be working when I copy the link from a conversation in my browser to another tab and opening the desktop app. I have included a video of the steps I took.

https://github.com/Expensify/App/assets/48998844/2f483a78-783c-454a-b074-a4c271a3829b

**Comment by narefyev91** [comment]
Not able to reproduce on latest main

**Comment by narefyev91** [comment]
> @kbecciv @narefyev91 the issue is not reproducible as is but while investigating it I see we have a crash when deeplinking to Concierge via `/concierge` route, in both desktop and web.
> 
> Should we update this issue to address that or create another issue? I can post a proposal to fix it, it's a pretty bad crash

I think we need to follow the same process for specify bugs (which we already have) - we need a new one bug ticket - maybe someone already flagged that issue somewhere - just to be sure we will not make duplications.
@tienifr you can sync with @kbecciv and check if we do not have already any equal bug tickets. Thanks!

**Comment by kbecciv** [comment]
@tienifr Can you please share reproduction steps and video for the crash?

**Comment by conorpendergrast** [comment]
Ok, sounds like this is no longer an issue. Comment if I'm wrong!
