### ISSUE TITLE
[$500] Task-From assignee page return back to task page, compose focus is lost

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap icon near compose
4. Select Assign task
5. Enter title
6. Tap next
7. Tap confirm task
8. Tap on Assignee
9. Tap app's back button and return to task page

## Expected Result:
From assignee page return back to task page, compose focus must not be lost.

## Actual Result:
From assignee page return back to task page, compose focus is lost.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/2fe25507-b040-41c8-b132-987989e1ac58

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014494eed39ef9bfb5</li>
        <li>Upwork Job ID: 1723075804876656640</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Open the same issue twice, closing https://github.com/Expensify/App/issues/31213
