### ISSUE TITLE
[$500] Task - When returning from the assignee page back to the task page, the compose focus is lost

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap icon near compose
4. Select Assign task
5. Enter title
6. Tap next
7. Tap confirm task
8. Tap on Assignee
9. Tap app's back button and return to task page

## Expected Result:
When returning from the assignee page to the task page, the compose focus should not be lost.

## Actual Result:
When returning from the assignee page back to the task page, the compose focus is lost

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/186192cd-b248-4a29-869f-b91e6afc22e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad405e0798cfa725</li>
        <li>Upwork Job ID: 1723080481074606080</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - When returning from the assignee page back to the task page, the compose focus is lost

### What is the root cause of that problem?
When the user navigates back the focus event is not called.

### What changes do you think we should make in order to solve the problem?
We should use the hook useFocusEffect when using navigates back, something like:
```
useFocusEffect(() => {
        if (_.has(props.session, 'authToken')) {
            // Pop the concierge loading page before opening the concierge report.
            Navigation.isNavigationReady().then(() => {
                Navigation.goBack(ROUTES.HOME);
                Report.navigateToConciergeChat();
            });
        } else {
            Navigation.navigate();
        }
    });
```

**Comment by samilabud** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/31213#issuecomment-1806425526)

Just in case the [PR](https://github.com/Expensify/App/pull/30973) doesn't fix this (or if they want to use something like this in that PR) I've updated my proposal with an actual use of what I said.

**Comment by CortneyOfstad** [comment]
Alright, holding for https://github.com/Expensify/App/pull/30973, as that will fix the issue

**Comment by CortneyOfstad** [comment]
PR is still open, so not overdue

**Comment by CortneyOfstad** [comment]
PR is still open

**Comment by CortneyOfstad** [comment]
Deployed to production yesterday! Adjusting title for the 7-day hold 👍

**Comment by CortneyOfstad** [comment]
@tienifr bump on the above ^^^ Thanks!

**Comment by CortneyOfstad** [comment]
@tienifr bump please!

**Comment by CortneyOfstad** [comment]
@parasharrajat any update on the test? Thanks!

**Comment by CortneyOfstad** [comment]
Sorry, was OoO — resetting the title now!

**Comment by CortneyOfstad** [comment]
Price is correct 👍

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by CortneyOfstad** [comment]
I also can't recreated. @kbecciv we're not able to recreate this, so going to close 👍
