### ISSUE TITLE
Money Request - Green dot doesn't appear after Money Request in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31222]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch App
2. Create new workspace
3. Request money on that workspace
4. Return to LHN

## Expected Result:
Verify that green dot shows in LHN for the money request report row

## Actual Result:
The green dot doesn't appear after Money Request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9dc76cc6-050e-4c0e-953a-1a07b841d1bb

![Bug6271923_1699656146317!1](https://github.com/Expensify/App/assets/78819774/c40e120f-d114-4adf-800f-9d75bf378a77)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jasperhuangg</details>

**Comment by miljakljajic** [comment]
This wasn't assigned til 11pm my time on Friday, sorry to get to it so late - @jasperhuangg do you agree this is a deploy blocker?

**Comment by miljakljajic** [comment]
Not reproducible on staging:

<img width="328" alt="image" src="https://github.com/Expensify/App/assets/28715117/6b581331-2533-402b-8674-0f4231eea451">

**Comment by roryabraham** [comment]
I was able to reproduce this on staging, but I was requesting money from a workspace I owned:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/47436092/4985a7e5-8126-4e6a-a7a0-b67320ecde15">

**Comment by jasperhuangg** [comment]
Hey sorry for the delay on this, I just tried it out and was also able to reproduce it.

The GBR appears on the workspace chat, but not on the actual expense report it seems. This was also with a workspace that I owned.

I'm going to be OOO today, so I’m going to unassign this, @roryabraham do you think you could take this off my hands please?

**Comment by mountiny** [comment]
Its expected to show on the workspace chat now, this is part of the wave6 changes we are making

**Comment by mountiny** [comment]
I cannot reproduce this either 
<img width="1128" alt="image" src="https://github.com/Expensify/App/assets/36083550/ba438035-9623-42a2-a0b9-13888ffe28fa">


The green dot is showing correctly on the LHN for the parent chat

**Comment by mountiny** [comment]
QA unable to repro either https://expensify.slack.com/archives/C9YU7BX5M/p1699964880903419
