### ISSUE TITLE
[$500] Thread - The header "from" section displays 1:1 user id instead of parent message.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report with task and sub-task thread reply messages
3. Tap "Reply" in thread page and note header
" From" section displaying parent message
8. Again tap "Reply" of sub task and note header
" From" section displaying parent message
9. Tap on a IOU report with thread and sub-thread created with reply messages
10. Tap "Reply" in IOU detail page and note header
" From" section displaying 1:1 user id instead of parent message
11. Tap sub thread "reply" again and note header
" From" section displaying 1:1 user id instead of parent message

## Expected Result:
Tap IOU report page created thread and sub thread "reply" messages, the header "from" section must display parent message.

## Actual Result:
Tap 1:1 DM created thread and sub thread "reply" messages, the header "from" section displays parent message.

But, tapping on IOU report page created thread and sub thread "reply" messages, the header "from" section displays 1:1 user id instead of parent message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/b58435f8-aeed-46c3-918f-bc420bff2a31

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137d75b6662be1ce6</li>
        <li>Upwork Job ID: 1723304254956363776</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread - The header "from" section displays 1:1 user id instead of parent message

### What is the root cause of that problem?
In. the currently logic 
```
if (isChildReport(report) && !isMoneyRequestReport(report) && !isTaskReport(report)) {
   

        const parentReport = lodashGet(allReports, [`${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID}`]);
        return getRootReportAndWorkspaceName(parentReport);
    }
```
If it is transaction thread we are getting root report name not parent report name
### What changes do you think we should make in order to solve the problem?
we should add condition like this
```
    if (isChildReport(report) && !isMoneyRequestReport(report) && !isTaskReport(report) && !isIOURequest(report)) {

```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@kadiealexander Could you help to confirm the expected?
Currently:
1. If the parent report is a task report or IOU report, we will display the parent report name in the 'From' section
2. If the parent report is an IOU Request, we will display the grandparent report name (IOU report name) in the 'From' section
3. If the parent report is a normal report, we will display the most recent task report or IOU report 
cc @shawnborton ping you here to get more opinions from UX perspective

**Comment by rushatgabhane** [comment]
This looks intentional. I don't think this is a bug.

**Comment by kadiealexander** [comment]
Yeah I agree, I believe this is intentional as well.
