### ISSUE TITLE
[$500] Android - Search - "Not found" search result returned when write first names of several users

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open app
2. Create a group chat with [applausetester+omd2@applause.expensifail.com](mailto:applausetester+omd2@applause.expensifail.com)
and [applausetester+omd4@applause.expensifail.com](mailto:applausetester+omd4@applause.expensifail.com)
3. Tap on Search icon in LHN
4. Write "JoJo Jonny"

## Expected Result:
Group conversation should be returned as a search result

## Actual Result:
"Not found" search result returned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/bb460820-ad6e-4448-bdea-384093be2bbf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188909b6ed1473b44</li>
        <li>Upwork Job ID: 1723305471195238400</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

**Comment by Akhilesh0947** [comment]
please guide me 

1. I am not able to run in the local environment
2. I'm not sure how to join Slack. I sent an email but haven't received any response.

**Comment by twisterdotcom** [comment]
I'm also unable to reproduce this. ([Internal vid](https://drive.google.com/file/d/1vfslh_-DTXyWEQ5-cKIkXaQgvPRoTnm-/view?usp=sharing) as I forgot to redact some customer names).

Going to close.
