### ISSUE TITLE
[HOLD #12603] mWeb - The animation is not loading at all when use is offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30901

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Disable the internet
4. Tab on Fab menu
5. Tap Save the world
6. Noticed - no animation is loaded
7. Tap on avatar
8. Tap on WS
9. Noticed - no animation is loaded
10. Go to Setting - Security
11. Noticed - no animation is loaded

## Expected Result:
The animation is loading when user is offline

## Actual Result:
The animation is not loading at all when use is offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3497f402-be99-4150-b9ab-8b7ed8b4346b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is not reproducible on production 

https://github.com/Expensify/App/assets/93399543/74fcd2d6-ac82-4c33-adeb-60557fcff745

**Comment by kosmydel** [comment]
Hey,

it is related to [this PR](https://github.com/Expensify/App/pull/29975). As the animations were moved from the bundle to the assets, we don't load them on the app initialization to reduce TTI and bundle size. The animations are loaded as soon as the network is available. It is similar behavior to displaying an image.

**Comment by AndrewGable** [comment]
So @roryabraham - Is this expected now?

**Comment by roryabraham** [comment]
I _think_ so, but TBH we didn't really discuss it broadly. I don't think we need to block deploy on this but should probably have a conversation about it. _Maybe_ we can inline the `.lottie` assets using `asset/inline` instead of `asset/resource`?

**Comment by roryabraham** [comment]
Just changing `asset/resource` to `asset/inline` doesn't work out-of-the-box, so more research will be needed to try to preload / inline lottie assets.

**Comment by roryabraham** [comment]
I'd say this is a weekly, TBD if it's really a problem we need to solve or not. Some thoughts:

- It might be even less of a problem when we get offline browser-level image caching set up
- Maybe we could get an SVG snapshot of each animation that's inlined in the HTML and display that while the lottie animation is loading
- Or maybe we can find a way to either inline or preload `.lottie` assets. If we could preload them like fonts when the page loads that could be a good way to address the problem
- Someday we could also look at setting up [service workers](https://expensify.slack.com/archives/C04CWBFE6/p1684865689862329) in our app to build better cross-session browser caching of all assets.

I think if we get good caching and potentially also preload `.lottie` assets like we do for our web fonts, we could eliminate most scenarios where a user could possibly see this type of bug or similar bugs where there's a delay before the animation loads.

**Comment by roryabraham** [comment]
I also think maybe we should put this on HOLD, consolidate discussion in https://github.com/Expensify/App/issues/28160, and treat that as a tracking issue

**Comment by AndrewGable** [comment]
On hold

**Comment by roryabraham** [comment]
#28160 is closed, but I think we can reasonably put this on HOLD for offline image caching, namely https://github.com/Expensify/App/issues/11425

**Comment by roryabraham** [comment]
I think it would also be good to get @kosmydel to look into this to see if it can be fixed independently of https://github.com/necolas/react-native-web/pull/2442

**Comment by roryabraham** [comment]
Brought this up in slack: https://expensify.slack.com/archives/C04878MDF34/p1701305502798839

**Comment by roryabraham** [comment]
We've got a WIP PR for this [here](https://github.com/Expensify/App/pull/32789)

**Comment by roryabraham** [comment]
Prefetching is not working, but for me image caching is not working in production at all. That's still being tracked over [here](https://github.com/Expensify/App/issues/12603), so I'm putting this on HOLD for that

**Comment by kosmydel** [comment]
> Prefetching is not working, but for me image caching is not working in production at all. That's still being tracked over [here](https://github.com/Expensify/App/issues/12603), so I'm putting this on HOLD for that

@roryabraham I'm sorry to hear that. I've quickly tested it on the production, and both prefetching and caching work for me:

https://github.com/Expensify/App/assets/104823336/53964522-0df0-4aec-8681-925278d497d9

Can you please give me additional information about the method you use to test it?

**Comment by kosmydel** [comment]
Ok, I probably found out the reason for that. I assume you use Safari, not Chrome. And prefetching [is not supported by Safari](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/prefetch#browser_compatibility). It is hidden behind the feature flag.

![Screenshot 2024-01-02 at 09 35 38](https://github.com/Expensify/App/assets/104823336/b9c7ea78-788a-4380-baed-e592493ec97e)

**Comment by kosmydel** [comment]
> Oh, sorry for the typo @kosmydel – I meant to say that prefetching _is now_ working but online caching was not. Bad mistake to make...
> 
> and nope, I'm using Chrome.

Oh, thanks for the clarification! Good to know that everything is working!
