### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] #gsc.tab=0 appears at the end of help links

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699660021286779

## Action Performed:
1. Go to help.expensify.com
2. Click on "expensify classic"

## Expected Result:
Redirects to https://help.expensify.com/expensify-classic/hubs/  

## Actual Result:
At the end "#gsc.tab=0" appends

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring ![4](https://github.com/Expensify/App/assets/38435837/f8b09e75-7466-4269-8ccb-fbd2b625edb5)
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be9da36f7e51b34b</li>
        <li>Upwork Job ID: 1723686062041632768</li>
        <li>Last Price Increase: 2023-11-12</li>
    </ul>
</details>

**Comment by eh2077** [comment]
It seems need to update the setting of [Custom Google Search Engine](https://support.google.com/programmable-search/thread/99389005/can-you-remove-gsc-tab-0-from-the-webpage?hl=en#:~:text=Please%20access%20your%20Programmable%20Search,Disable'%20and%20save%20the%20settings).

**Comment by gamescation** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
#gsc.tab=0 appears at the end of help links

What is the root cause of that problem?

The root cause is that the help links have #gsc.tab=0 attached to them in the redirects.csv.

What changes do you think we should make in order to solve the problem?

Change redirects.csv to read:

```
sourceURL,targetURL
https://community.expensify.com/discussion/5634/deep-dive-how-long-will-it-take-for-me-to-receive-my-reimbursement,https://help.expensify.com/articles/expensify-classic/get-paid-back/reports/Reimbursements
https://community.expensify.com/discussion/4925/how-to-dispute-an-expensify-card-transaction,https://help.expensify.com/articles/expensify-classic/expensify-card/Dispute-A-Transaction
https://community.expensify.com/discussion/5184/faq-how-am-i-protected-from-fraud-using-the-expensify-card,https://help.expensify.com/articles/expensify-classic/expensify-card/Dispute-A-Transaction
https://community.expensify.com/discussion/4887/deep-dive-understanding-your-expensify-card-statement,https://help.expensify.com/articles/expensify-classic/expensify-card/Statements
https://community.expensify.com/discussion/4883/how-to-export-your-expensify-card-statement,https://help.expensify.com/articles/expensify-classic/expensify-card/Statements
https://community.expensify.com/discussion/9528/how-to-understand-the-amount-owed-figure,https://help.expensify.com/articles/expensify-classic/expensify-card/Statements
https://community.expensify.com/discussion/4806/how-to-pay-your-expensify-card-balance,https://help.expensify.com/articles/expensify-classic/expensify-card/Statements
https://community.expensify.com/discussion/7303/how-to-track-and-report-on-fringe-benefits-tax-fbt,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Fringe-Benefits
https://community.expensify.com/discussion/8984/how-to-display-report-ids-or-transactionids-correctly-in-excel,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Other-Export-Options
https://community.expensify.com/discussion/5799/deep-dive-date-formatting-for-formulas,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5795/deep-dive-expense-level-formula,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5798/deep-dive-gl-code-formula,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5797/deep-dive-report-level-formula,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5794/deep-dive-understanding-custom-export-templates-and-formulas,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5802/deep-dive-understanding-math-and-substring-formula-for-custom-exports,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/5796/deep-dive-user-level-formula,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/4750/how-to-create-a-custom-export,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
https://community.expensify.com/discussion/4642/how-to-export-reports-to-a-custom-template,https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates
```

**Comment by rushatgabhane** [comment]
sorry, this is helpdot related. no need for proposals here

**Comment by dylanexpensify** [comment]
Nice work, @rushatgabhane!

**Comment by dylanexpensify** [comment]
payment day!

**Comment by dylanexpensify** [comment]
@rushatgabhane anything needed here?
