### ISSUE TITLE
IOU-In employee WS, the billable option in manual expense is auto moving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1.In old dot admin account, set re-bill expenses to client as "default to billable"
2. Launch app as employe login
3. Tap fab-- request money
4. Enter amount and tap next
5. Select employee WS
6. Tap show more and wait for a second and note billable option auto moving

## Expected Result:
In employee workspace, the Billable option in manual expense must not auto move

## Actual Result:
In employee workspace, the Billable option in manual expense is auto moving

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a8dd2ed-0ece-4ead-bf99-355e469c4532

![Bug6272816_1699731986790!screenshot_2023-11-11-09-13-42-833_com android chrome](https://github.com/Expensify/App/assets/78819774/ebffc5a0-221a-49b0-80be-2c24ae44f49f)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1dd6ea56238a2de</li>
        <li>Upwork Job ID: 1729851295336857600</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertjchen</details>

**Comment by robertjchen** [comment]
It sounds like the correct behavior here should be that the billable option should already be properly set upon initial entry to this page 🤔

**Comment by robertjchen** [comment]
Doesn't seem like a `DeployBlocker` per se. Removing the label for now- we need to figure out if it's a backend issue or if it's a frontend behavior issue (suspecting the latter).

**Comment by sophiepintoraetz** [comment]
Adding the `Help Wanted` label as they might be able to help figure out front/back end!

**Comment by sophiepintoraetz** [comment]
@robertjchen - would you maybe be able to confirm here?

**Comment by sophiepintoraetz** [comment]
Waiting on @robertjchen to confirm here.

**Comment by robertjchen** [comment]
Marking as `Internal` for now for additional investigation.

**Comment by robertjchen** [comment]
Given that this is purely in the backend, let's re-create this as an internal issue and go from there.
