### ISSUE TITLE
[$500] Chat - Link in Code block is broken

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open any report
3. Send link in following format: 
![image](https://github.com/Expensify/App/assets/93399543/81794626-72c5-49a1-a8aa-4bf0444e0b2b)

4. Observe that format is broken

## Expected Result:
Link in Code block should display correctly

## Actual Result:
Link in Code block is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/67ddb69f-ed03-43e9-b969-12f4c472755f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d375f943b53855b</li>
        <li>Upwork Job ID: 1724409048072474624</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue found when executing Monthly Edge TC https://github.com/Expensify/App/issues/22492

**Comment by paultsimura** [comment]
According to the original issue (https://github.com/Expensify/App/issues/22492), this is the expected behavior, isn't it?

**Comment by SamanKT** [comment]
Contributor details
Your Expensify account email: [saman.khataei@hotmail.com](mailto:saman.khataei@hotmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d45dab5b311d5e84

**Comment by SamanKT** [comment]
Contributor details
Your Expensify account email: saman.khataei@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d45dab5b311d5e84

**Comment by ikevin127** [comment]
> // We don't want to apply link rule if match[1] contains the code block inside the [] of the markdown e.g. `[```example```](https://example.com)` or if match[1] is multiline text preceeded by markdown heading, e.g., `# [example\nexample\nexample](https://example.com)`

from:
https://github.com/Expensify/expensify-common/blob/04e6315adc870127b281de2ad16a1db5b325d065/lib/ExpensiMark.js#L522-L523

This is the expected behaviour according to [this](https://github.com/Expensify/App/pull/23247) merged PR, as seen in one of the videos:

https://github.com/Expensify/App/assets/56457735/703350bc-632b-49b1-8351-e52534b6d77b

**Comment by rchrdschfr** [comment]
Contributor details
Your Expensify account email: [rchrdschfr@gmail.com](mailto:rchrdschfr@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0170400e57082f5461

**Comment by rchrdschfr** [comment]
It seems possible that this is the expected behaviour as others have pointed out. However, if it's not expected behaviour, then how should the link be formatted?

**Comment by rchrdschfr** [comment]
Contributor details
Your Expensify account email: rchrdschfr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0170400e57082f5461

**Comment by laurenreidexpensify** [comment]
@Ollyws can you review links and confirm if this expected behaviour as the others have suggested? Thanks
