### ISSUE TITLE
[Wave 6: Workspace Chats] DM/Workspace Chat should be unread when receiving IOU/expense report

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#31318]
When someone requests money via an IOU or expense report, we put a green dot on the DM or workspace chat. We should also be marking the DM or workspace chat as unread in the LHN, but that doesn't appear to be happening. 

LHN: 
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/1371996/bc393551-1b75-4263-8072-874679a4bf20">

Workspace chat: 
<img width="1126" alt="Screenshot 2023-11-14 at 3 05 15 PM" src="https://github.com/Expensify/App/assets/1371996/7f4ec1be-dbe3-41f9-b8e4-8bd909769bf2">

I believe this is a front-end issue because we are showing the green "new" line within the chat itself. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019619f7d4b8cd8171</li>
        <li>Upwork Job ID: 1726662331671265280</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like ti help with this issue!

**Comment by waterim** [comment]
My update:
Found a root of this issue, but still trying to find the place where its happening.
The issue is because of the Optimistic Onyx data for some reason when user B requests money and user A receives this information, onyx locally updates lastReadTime and  lastVisibleActionCreated to Date.now() and thats why isUnread = false

**Comment by waterim** [comment]
cc @puneetlath 

After my additional research I realized that Pusher is sending the wrong lastReadTime to the App.
It updates the lastReadTime to the lastVisibleActionCreated (or to new Date()) and thats why isUnread will be false.
<img width="584" alt="image" src="https://github.com/Expensify/App/assets/39777589/4d09f2c1-0650-422b-8a5f-f0d091a12d0b">

But data which coming from "openApp" is correct. 
Inside of the mergeCollections -> '_report' you can see on the screenshot
<img width="739" alt="image" src="https://github.com/Expensify/App/assets/39777589/6c1e6dff-f2d5-402f-a636-12c80b24127f">

**Comment by puneetlath** [comment]
Great research, thanks @waterim! I'll go ahead and mark this as an internal issue for someone on the team to take.

**Comment by greg-schroeder** [comment]
I'm going to put this one with @amyevans for next week per our discussion in Slack

**Comment by amyevans** [comment]
Alright I see the _why_: we're getting the `lastReadTime` of the chat for the user who made the request and assuming that's the `lastReadTime` for all participants within the report, so the chat gets marked read for everyone. I should be able to get a PR up tomorrow

**Comment by amyevans** [comment]
Draft up: https://github.com/Expensify/Web-Expensify/pull/39884. Asked a question in it though to make sure one of the changes isn't problematic

**Comment by amyevans** [comment]
PR to fix this deployed to production today!

However, @puneetlath raised a question in the PR:
> One thing I noticed is that it is unread in the LHN, but it doesn't have the green line above the IOU in the chat itself.

We agreed that sounds like a frontend issue. @waterim would you have bandwidth to investigate further? (I can open a new GH if it'd be easier for tracking purposes too.)

**Comment by amyevans** [comment]
@waterim new GH here: https://github.com/Expensify/App/issues/32732
