### ISSUE TITLE
[HOLD for payment 2024-01-17] Hold Requests: Educational Interstitial

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#31347]
### Educational interstitial when holding for the first time

Depends on some of the changes in: https://github.com/Expensify/App/issues/31300 but can be done independently.

When "Hold" is tapped for the first time in our `<MoneyRequestOverflowMenu`  we'll perform a check to see if it's the first time they've used the feature.

We'll attempt to load a `private_holdUseExplained` NVP from the user's account. If this flag is false or does not exist, then we will show a new interstitial that explains the Hold feature.

Under `src/components` create a new `<ProcessMoneyRequestHoldMenu` for the Hold popover.

This will be composed of rows three blocks, followed by the "Got it, thanks!" button to close it out. Each block consists of:
1 graphic
1 title text
1 explanation text

So, we have:
- `Expensicons.Hourglass, iou.whatIsHoldTitle, iou.whatIsHoldExplain`
- `Expensicons.ChatBubble, iou.holdIsTemporaryTitle, iou.holdIsTemporaryExplain`
- `Expensicons.TrashCan, iou.deleteHoldTitle, iou.deleteHoldExplain`

<img width="409" alt="Screenshot 2023-09-23 at 5 41 09 PM" src="https://github.com/Expensify/App/assets/2438855/ddc6616c-25eb-442b-9b41-3be5a5a03685">

<img width="410" alt="Screenshot 2023-09-23 at 5 41 30 PM" src="https://github.com/Expensify/App/assets/2438855/a545441a-eea4-451d-a9ec-7281b9c308ba">

Text and translations:
- Add 'What is hold?' under `iou.whatIsHoldTitle`
- Add 'Hold is our way of streamlining financial collaboration by promoting conversation ahead of approval or payment.' under `iou.whatIsHoldExplain`
- Add 'Hold is usually temporary' under `iou.holdIsTemporaryTitle`
- Add 'Because hold is used to clear up confusion or clarify an important detail before payment, it's not permanent.' under `iou.holdIsTemporaryExplain`
- Add 'Delete whatever won't be paid' under `iou.deleteHoldTitle`
- Add 'In the rare case where something is put on hold and won't be paid, it's on the person requesting payment to delete it.' under `iou.deleteHoldExplain`

You may also consider adding the other required resources at this time:
- Add a new Clock icon in Expensicons.js (and the corresponding svg in assets/images/)
- Add 'Hold' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.hold
- Add 'Hold Request' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.holdRequest
- Add 'Un-Hold Request' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.unholdRequest
- Add 'Explain why you're holding this request.' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.explainHold
- Add 'Reason' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.reason
- Add 'A reason is required when holding.' and associated translation(s) in [src/languages](https://github.com/Expensify/App/tree/main/src/languages) under iou.holdReasonRequired
- Add 'This request was put on hold. Review the comments for next steps.' under iou.requestOnHold
- Add 'Confirm what to approve' under iou.confirmApproval
- Add 'Approve the entire report total or only the amount not on hold.' under iou.confirmApprovalAmount
- Add 'Confirm what to pay' under iou.confirmPay
- Add 'Pay all out-of-pocket spend or only the amount not on hold.' under iou.confirmPayAmount
- Add 'Pay only' under iou.REPORT_ACTION_TYPE.payOnly
- Add 'What is hold?' under iou.whatIsHoldTitle
- Add 'Hold is our way of streamlining financial collaboration by promoting conversation ahead of approval or payment.' under iou.whatIsHoldExplain
- Add 'Hold is usually temporary' under iou.holdIsTemporaryTitle
- Add 'Because hold is used to clear up confusion or clarify an important detail before payment, it's not permanent.' under iou.holdIsTemporaryExplain
- Add 'Delete whatever won't be paid' under iou.deleteHoldTitle
- Add 'In the rare case where something is put on hold and won't be paid, it's on the person requesting payment to delete it.' under iou.deleteHoldExplain

#### Consts
- In [src/CONST.ts](https://github.com/Expensify/App/blob/main/src/CONST.ts) add a new CONST.MONEY_REQUEST.HOLD entry defined as 'hold'
- In [src/CONST.ts](https://github.com/Expensify/App/blob/main/src/CONST.ts) add a new CONST.MONEY_REQUEST.UNHOLD entry defined as 'unhold'

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task.

**Comment by robertjchen** [comment]
thanks @cdOut ! Let me know if you have any questions 🙇

**Comment by robertjchen** [comment]
@Expensify/design Would appreciate your input here! @cdOut Realized that while the educational interstitial in this mockup looks great on Mobile, we weren't sure how it would scale up to larger screen sizes. What would be the best approach here in displaying this? 🙏 

![image](https://github.com/Expensify/App/assets/2438855/e6a9e7b4-6c2c-4f51-9cd8-a248ad7b4482)

**Comment by shawnborton** [comment]
For desktop, let's just put it in the RHP. Thoughts on that approach? We already have similar style modals in the RHP on desktop for things like the Workspace empty state.

**Comment by JmillsExpensify** [comment]
I agree with putting it in the RHP.

**Comment by cdOut** [comment]
Alright, I'll implement it for desktop / wider screens.

**Comment by shawnborton** [comment]
I think we still want to use the right hand pane pattern here since we have the illustration + icons.

**Comment by JmillsExpensify** [comment]
Agreed

**Comment by robertjchen** [comment]
As expected, the changes in this PR necessarily have a bit of overlap with the work ongoing in https://github.com/Expensify/App/issues/31300, so we'll need to get both reconciled before this can go out.

**Comment by robertjchen** [comment]
Unification work ongoing: https://expensify.slack.com/archives/C02NZ2HGJAZ/p1703740799526829?thread_ts=1703630366.111029&cid=C02NZ2HGJAZ

**Comment by robertjchen** [comment]
Tests changes were removed 👍 I have reviewed and merged!

The changes/interstitials here aren't visible once this is deployed and will not affect existing behavior. This will happen with the other task/PR which will tie everything together: https://github.com/Expensify/App/issues/31300 https://github.com/Expensify/App/pull/33124

**Comment by robertjchen** [comment]
Please see main issue for a full-picture update: https://github.com/Expensify/Expensify/issues/274076

**Comment by robertjchen** [comment]
This has been completed!
