### ISSUE TITLE
[$500] Web - User get redirected to NewDot Expensify when logging in from OldDot Expensify

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31350]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to NewDot Expensify
2. Log in with any account
3. Navigate to OldDot Expensify
4. Log in with a different existing account

## Expected Result:
User should be logged in and OldDot Expensify Inbox page should be displayed.

## Actual Result:
User is logged in but gets redirected to NewDot Expensify.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/dd7dcc56-e002-4346-96eb-3e4890ac4c8b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6fee6bfbbf208c5</li>
        <li>Upwork Job ID: 1724731698215972864</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This is our only/last blocker today, so I'm going to see if I can take care of it and then deploy

**Comment by roryabraham** [comment]
Pretty sure this is expected behavior for new logins now – big change we made this week to push new customers into NewDot

**Comment by roryabraham** [comment]
ok, per [this message](https://expensify.slack.com/archives/C05NJ4SLBMF/p1700017314409359?thread_ts=1699923204.458699&cid=C05NJ4SLBMF) this is forsure expected behavior, starting today. It's also an OldDot change, not a NewDot one, so not a NewDot deploy blocker, and indeed not a bug at all

**Comment by roryabraham** [comment]
No payments due
