### ISSUE TITLE
[$500] Android-Workspace-In reimbursement page, WS name truncated in different way compared to other pages

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces--Workspace
4. Tap New Workspace
5. Tap Workspace
6. Enter name - Test Workspace testingtestingtestingtestingtestingtesting)
7. Tap Save
8. Tap card/Members/Bills/Travels/Members
9. Note Workspace name in header is truncated in same format (Test Workspac...)
10. Tap reimbursements
11. Note the truncated format of Workspace name in header is different from other pages (Test Workspace testingtesti...)

## Expected Result:
In all pages, Workspace name in header must be truncated and displayed in the same manner.

## Actual Result:
In card/Members/Bills/Travels/Members page, Workspace name in header is truncated in same format (Test Workspac...). But in reimbursements page, the truncated format of Workspace name in header is different from other pages (Test Workspace testingtesti...).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/8b1cecdc-8a0a-452c-b988-5044df38fa50

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ab700b1fc46d0d1</li>
        <li>Upwork Job ID: 1724762358824095744</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27705715</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
Bug is straightforward @dukenv0307's [proposal](https://github.com/Expensify/App/issues/31359#issuecomment-1812446508) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by deetergp** [comment]
Agreed! Adding @dukenv0307…

**Comment by mananjadhav** [comment]
@deetergp Accidentally closed this?

**Comment by deetergp** [comment]
Nice catch @mananjadhav — I'm not sure how that happened 😅 I think everything looks in order now. Thanks!

**Comment by mananjadhav** [comment]
@izarutskaya @dukenv0307 @isabelastisser Are you folks able to reproduce this in the latest version. I can't.


https://github.com/Expensify/App/assets/3069065/727a577a-f1ac-494e-8428-1700bd60ae44

**Comment by mananjadhav** [comment]
@isabelastisser @izarutskaya Did you folks get a chance to look at my previous comment? Are you able to reproduce this?

And @dukenv0307 I raised a comment on the PR.

**Comment by isabelastisser** [comment]
Hey @deetergp, can you please see my comment above? Thanks!

**Comment by isabelastisser** [comment]
Thanks, Scott! I sent the offers in Upwork now. All set!

**Comment by mananjadhav** [comment]
@isabelastisser I raise my request on NewDot. Can you please rescind the Upwork offer for me and instead post a payment summary here?

**Comment by isabelastisser** [comment]
Payment summary:

@mananjadhav $500 - C+ review (NewDot payment)
@dukenv0307 $500 - Accepted proposal (paid in Upwork)

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.
