### ISSUE TITLE
[$500] Compose-When editing comment without making any changes, hbhvv.com is shown as text.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31351]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Paste the link https://hbhvv.com/ 3  times
4. Send the message and note hbhvv.com is shown as text instead of url link
5. Long press the message sent and select edit comment
6. Without making any changes, tap green tick
7. Note hbhvv.com is shown as text instead of url link
8. Long press the message sent and select edit comment
9. Add any text and tap green tick

## Expected Result:
hbhvv.com must be shown as url link.

## Actual Result:
The middle url(hbhvv.com) is shown as text and not linked. It is shown as link only when you add text when editing.

When editing comment without making any changes, hbhvv.com is shown as text.

When editing comment by making changes like adding text, hbhvv.com is shown as url link.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/72627d44-6dbf-46b2-87be-14ab081db263

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f464768385734ffb</li>
        <li>Upwork Job ID: 1724733178025144320</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by sobitneupane** [comment]
Will review it shortly.

**Comment by sobitneupane** [comment]
@tienifr @suneox Thanks for your proposals.

At first let's be clear on the expected output. 

I don't think the real issue here is when user entered three different links, our system could not detect it. IMO, after user edited the link, the change in output is the issue.

When user entered or pasted link `https://hbhvv.com` three times, the resulting `https://hbhvv.comhttps://hbhvv.comhttps://hbhvv.com` doesn't look like a valid url. But after user edits the message, output changes.

@tienifr @suneox What should be the output when user pastes https://hbhvv.com link three times?

cc: @muttmuure

**Comment by muttmuure** [comment]
I'm not sure this strikes me as something important to fix right now.
