### ISSUE TITLE
[MEDIUM] VBA Refactor: Update the order of Bank Account flow steps for NewDot flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#31357]
# Part of the <Project Name> project
Coming from [Update the VBBA setup flow to new design system](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) design doc ([parent issue](https://github.com/Expensify/Expensify/issues/289050)).

Update the BE flow of the bank account flow to support the new order of steps.

The new flow can be visually seen in the design section of the design doc https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#bookmark=id.3slfop5gy3im

# Feature Description

The steps are:
1. Connect bank account - BankAccountStep
1. Personal Info step
1. Business info step
1. Onfido verification
2. Beneficial Owner step
3. Complete verification

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102ed6ddd4ffeda88</li>
        <li>Upwork Job ID: 1724757479449100288</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by shubham1206agra** [comment]
@mountiny Can you assign me here?

**Comment by mountiny** [comment]
This will be only backend change I dont think there will be anything requried here, but I will assign you

**Comment by adelekennedy** [comment]
@nkuoch any updates here?

**Comment by nkuoch** [comment]
Had to focus on [KYC docs](https://github.com/Expensify/Expensify/issues/333184) last week. Working back on vba refactor this week.

**Comment by nkuoch** [comment]
Still in progress, getting there.
All substeps have been implemented and merged in the feature branch.
All my back end refactoring to allow 1:1:1 architecture and other step ordering and saving in db at each step has been deployed.
Holding on some TS refactoring and then will merge my https://github.com/Expensify/App/pull/33838.

**Comment by mountiny** [comment]
I believe this one was done
