### ISSUE TITLE
[$500] Login – Doesn't redirect to Login page with an error message when reusing email link.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Signout of NewDot.
3. Log into staging.expensify.com with any account.
4. Add a Secondary Login from Account Settings.
5. Open "validate secondary log in" email .
6. Copy the link under "Click here to validate that login, like magic!" (e.g. https://staging.expensify.com/v/3431989/123456).
7. Paste the URL into new tab (don't enter it yet).
8. Add "new" after staging (e.g. https://staging.new.expensify.com/v/3431989/123456).
9. Navigate to the compiled link.
10. Click on “just sign in here”.
11. Complete login to NewDot.
12. Sign out of NewDot.
13. Reuse the link created in step 9. 

## Expected Result:
Verify you're redirected to Login page with an error message displayed below the password field stating: "This set password link is invalid or has expired..."

## Actual Result:
"Here is your magic code" page opens.
Does not redirect to the Login page with an error message when reusing a link created via OldDot's secondary login email verification.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/d48dec6f-84de-47c5-b75d-b2372e9c8b28

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01758ec553a03ac819</li>
        <li>Upwork Job ID: 1724765802065883136</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by cooldev900** [comment]
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
The ValidateLoginPage does show "Here is your magic code" instead of "This set password link is invalid or has expired..." after used login code.
### What is the root cause of that problem?
The root cause is that session.authAuthoState is null so autoAuthState will be CONST.AUTO_AUTH_STATE.NOT_STARTED.
https://github.com/Expensify/App/blob/9d79fd12ce8f5d1dcb8870b61a8bc4513f55c935/src/pages/ValidateLoginPage/index.website.js#L52
### What changes do you think we should make in order to solve the problem?

**Comment by shubham1206agra** [comment]
@cooldev900 Can you send the API params and response here?

**Comment by shubham1206agra** [comment]
In this case can QA confirm the reproducibility of this issue?

**Comment by cooldev900** [comment]
Let me check again

**Comment by cooldev900** [comment]
It works properly for now so QA can't reproduce it anymore, I think.

![image](https://github.com/Expensify/App/assets/13826499/7be2e94d-6123-4433-90b0-1bad08dcfa69)

**Comment by peterdbarkerUK** [comment]
I can reproduce this, clarified the repro steps. 

Clicking "just sign in here" goes to the correct destination of "Magic Code Expired".

**Comment by peterdbarkerUK** [comment]
@cooldev900 @shubham1206agra - I've updated the reproduction steps since you last commented, and could reproduce. Could you see if the updated steps work for you?

**Comment by cooldev900** [comment]
@peterdbarkerUK 
let me check now

**Comment by cooldev900** [comment]
@peterdbarkerUK 
so step 14, do we need to click `just sign in here` or not for getting expected result?
![image](https://github.com/Expensify/App/assets/13826499/d5008d91-a5ed-460f-bcfc-df509cb2d3de)

**Comment by cooldev900** [comment]
when we click `just sign in here`, that shows this page.

![image](https://github.com/Expensify/App/assets/13826499/ba90e0a7-bd58-47cd-9097-8cd8d6077475)

**Comment by cooldev900** [comment]
I have one question.
Which one does the login page means in expected result `Verify you're redirected to Login page with an error message displayed below the password field stating: "This set password link is invalid or has expired..."`?

 
![image](https://github.com/Expensify/App/assets/13826499/1ffb9ff6-4603-4f5c-bb6d-a04f9fedc54a)

![image](https://github.com/Expensify/App/assets/13826499/155748c2-6b25-4b73-87c0-7e5947ff9a26)

**Comment by peterdbarkerUK** [comment]
Yes, I think the expected is to go directly to the expired page; essentially pre-checking the magic code. TBH though I'm not sure this is a use case worth investing time in resolving. It's already an edgy case, and doesn't result in any vulnerabilities or actual dead ends.

 @vitHoracek I'd love your opinion here - is this correct, and if not, is it worth fixing?

**Comment by cooldev900** [comment]
I am about to understand the requirement now.
@peterdbarkerUK, you are right. essense is pre-checking the magic code.
let me fix it.

**Comment by cooldev900** [comment]
@peterdbarkerUK @shubham1206agra 
[Proposal](https://github.com/Expensify/App/issues/31361#issuecomment-1814027058) updated.

**Comment by peterdbarkerUK** [comment]
Thanks @cooldev900 

@shubham1206agra could you take a looksee?

**Comment by shubham1206agra** [comment]
@cooldev900 Can you just put a video showing https://github.com/Expensify/App/pull/15505 cases passed? And can you correct the video shown in your proposal?

**Comment by cooldev900** [comment]
@shubham1206agra 
let me check the [#15505](https://github.com/Expensify/App/pull/15505) and update the video

**Comment by cooldev900** [comment]
Here is the video showing [#1550](https://github.com/Expensify/App/pull/15505)5 cases passed.

https://github.com/Expensify/App/assets/13826499/67ee1f4f-8ab0-4501-be56-95badaacbb45

**Comment by shubham1206agra** [comment]
@cooldev900 [proposal](https://github.com/Expensify/App/issues/31361#issuecomment-1812508356) looks satisfactory to me.
🎀 👀 🎀 C+ Reviewed

@mountiny Can you please reply to this comment https://github.com/Expensify/App/issues/31361#issuecomment-1825918369 to confirm?

**Comment by shubham1206agra** [comment]
So should we proceed or close this?

**Comment by mountiny** [comment]
I would like to verify if this is just checking some equivalent real flow or if this is indeed a case that you need to copy the oldDot to newDot verification shot lived token to experience this.

If yes then we should close this I think

@izarutskaya @kavimuru would you know how this issue got reported/ how they got this error?

**Comment by arosiclair** [comment]
The repro steps seem a bit convoluted. You can reproduce this by just using any old validate link. Eg:

1. Sign out of New Dot staging
2. Go to https://staging.new.expensify.com/v/123456/123456 (random expired link)

> Yes, I think the expected is to go directly to the expired page; essentially pre-checking the magic code. 

It seems like this is only true if you're logging in on the same device (in another tab). In that case, the ValidateLoginPage does try to log you in automatically and does correctly show the expired message. 

However, these repro steps have you open just the validate link directly. In that case, there's no automatic login (since you're not logging in on that device) and just the code is displayed. This sounds like correct behavior to me. If the code is expired you'll notice pretty quickly when you try it and it doesn't work 😄. So I think we should close this out.

**Comment by kavimuru** [comment]
@mountiny This is the actions followed 

- In OldDot add a Secondary Login from Account Settings and open "validate secondary log in" email.
- Copy the link for validation and add to it “new” for redirection to NewDot.
- I use the same link twice and there are no mistake in second time

**Comment by mountiny** [comment]
I agree with @arosiclair sounds like we should close this

> In OldDot add a Secondary Login from Account Settings and open "validate secondary log in" email.
> Copy the link for validation and add to it “new” for redirection to NewDot.

this is the step I dont understand, nobody will do that

**Comment by arosiclair** [comment]
Cool closing this out. Re-open if you disagree!
