### ISSUE TITLE
[$500] Bank Account - Cursor in Routing number shown in "Account number"switching background to foreground

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces----Workspace
4. Tap Bank account---Update to USD currency
5. Tap connect manually
6. Paste routing number
7. Keep cursor in Account number
8. Background the app
9. Copy the account number
10. Foreground the app

## Expected Result:
When cursor placed in account number, and kept app in background and again bringing foreground, app cursor must be in the same "Account number" field.

## Actual Result:
When cursor placed in "account number", and kept app in background and again bringing foreground, app cursor is in "routing number" field instead of "Account number".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/2f7fa501-d079-46db-811e-bff6e69090f7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a1de3bb375306db</li>
        <li>Upwork Job ID: 1724770607844880384</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27951576</li>
<li>dukenv0307 | Contributor | 27951578</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Hm, I'm not sure it's worth making a change here. @nkuoch @MariaHCD I assume there's a pretty good reason why we show the loader here on the bank account page?

**Comment by nkuoch** [comment]
I think it makes sense to fix it.

**Comment by trjExpensify** [comment]
Okay, if we don't have a reason for it, let's fix it. 👍 @getusha this is ready for a proposal review, please. :)

**Comment by getusha** [comment]
@tienifr is there any explanation why this is happening on native and not on web?

**Comment by getusha** [comment]
Thanks for clarifying that!
@tienifr do you happen to remember the exact difference between `IS_LOADING_APP` and `IS_LOADING_REPORT_DATA` the comment is the same and you have more context on whether it should be used instead of IS_LOADING_REPORT_DATA. https://github.com/expensify/App/commit/ce354b0826919adf1c7cc582a8148e1360dddce1#diff-facfc70b32eba19ccaeeadd16b51faf6dbf2ceb919373565e7322c86047886cdR178-R180

**Comment by trjExpensify** [comment]
@getusha does that clear up your question?

**Comment by getusha** [comment]
it makes sense to use `IS_LOADING_APP` and it's improbable that we will call `OpenApp` again. it works and i am testing the solution as much as possible to avoid possible regression like https://github.com/Expensify/App/pull/18574

**Comment by getusha** [comment]
Thanks for the proposal @tienifr the solution works and the RCA is also correct.
But i like @dukenv0307's solution, i think it is better to use `IS_LOADING_APP` instead of having a new state. it works well and didn't find any issues with it, so let's go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/31363#issuecomment-1812558962).

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment]
Just need a proposal review from Joel Melv, then we're good to proceed!

**Comment by trjExpensify** [comment]
@joelbettner can you review this proposal please so we can move to a PR? Thanks!

**Comment by getusha** [comment]
@trjExpensify PR was deployed to production 2 weeks a go, seems like automation failed.

**Comment by trjExpensify** [comment]
Hey, back from the festive break! Confirming payments as follows: 

$500 - @getusha for the C+ review
$500 - @dukenv0307 for the fix. 

Settled up, closing!
