### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Android - Chat - Chat does not scroll down to the latest message after requesting money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to chat with long history
3. Scroll up
4. Tap + > Request money
5. Send a manual request

## Expected Result:
The chat will scroll down to the latest message after requesting money

## Actual Result:
The chat does not scroll down to the latest message after requesting money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5206561-99dc-4dfd-b5b6-939a6f8ed400

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010af8faa2a71dafad</li>
        <li>Upwork Job ID: 1724805443248058368</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 27756377</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## Root cause
Root cause is that in `requestMoney` while sending the event, we send it incorrectly for the report:
```js
Report.notifyNewAction(report.reportID, payeeAccountID);
```

## Changes
```js
    Report.notifyNewAction(currentChatReport.reportID, payeeAccountID);
```

**Comment by narefyev91** [comment]
Proposal from @esh-g looks good to me https://github.com/Expensify/App/issues/31373#issuecomment-1812740606
Let's also try to avoid using setTimeout - (maybe we can find some other solution to make scroll working) - but in any case we can iterate inside PR
🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment]
@marcochavezf what do you think about @esh-g's proposal?

**Comment by marcochavezf** [comment]
Thanks @narefyev91 for the review, the proposal also looks good to me and I agree that we should avoid setTimeout, or at least justify why it's necessary for Android. Assigning @esh-g 🚀

**Comment by sakluger** [comment]
@narefyev91 mind finishing the BZ checklist when you have a chance?

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - that was missing functionality for android only - we did not fetch scroll position at all - not a regression from anywhere
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by sakluger** [comment]
Thanks! This one is all paid out and good to close.
