### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500]  Room - Inconsistency in room member list when it is created offline and after returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Have a workspace with a few members
1. Go offline
2. Click + > New chat > Room
3. Create a room under the workspace in the precondition and set the visibility to Workspace
4. Click on the room header > Members
6. Go online

## Expected Result:
Member list in the room when created offline should only show the admin themselves

## Actual Result:
Member list in the room when created offline shows all the workspace members. It shows only the admin after returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/411e479b-16db-4a78-a2fc-82b7b662c2e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124f1a665a95a6c6e</li>
        <li>Upwork Job ID: 1724807139956674560</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27723102</li>
</ul></li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @dukenv0307

**Comment by chiragsalian** [comment]
regression test LGTM 👍

**Comment by kadiealexander** [comment]
Nice! Payouts due:

- [ ] Contributor: $X @dukenv0307
- [ ] Contributor+: $X @parasharrajat

Upwork job is [here](https://www.upwork.com/nx/wm/offer/27723102).

**Comment by kadiealexander** [comment]
Adding a teammate to sort payment while I'm OOO.

**Comment by kadiealexander** [comment]
Thanks for sorting payment @bfitzexpensify, the BugZero Checklist is complete [here](https://github.com/Expensify/App/issues/31375#issuecomment-1824717144).

**Comment by bfitzexpensify** [comment]
Payout complete, BZ checklist is done so we're all wrapped up here. Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/31375#issuecomment-1831241059).
