### ISSUE TITLE
[HOLD for payment 2024-01-17] [HOLD for payment 2023-12-15] [$500] Bank account - Fields with emojis are not turned red and general error message is shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:** https://github.com/Expensify/App/pull/31259
**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Navigate to Workspace > Bank account > Connect manually
3. Enter routing and account number
4. Enter emojis in Legal name, address and city fields
5. Fill out the rest with test data and tap "Continue"

## Expected Result:
The fields with emojis are highlighted in red and the error message to enter valid info is displayed

## Actual Result:
The general error message "Auth SetupWithdrawalAccount returned an error" is displayed, and the fields are not turned red.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/8f8e819c-0aee-47f3-9913-03b781eabec0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01087f0962c58f5f4a</li>
        <li>Upwork Job ID: 1724828495604215808</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27782542</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment]
Some related issues which can be combined together:
- https://github.com/Expensify/App/issues/31387
- https://github.com/Expensify/App/issues/31389
- https://github.com/Expensify/App/issues/31393

**Comment by yakupafsin** [comment]
@situchan https://github.com/Expensify/App/issues/31393 

This issue is related to numeric inputs accepting various types of characters, such as letters or Unicode.

**Comment by aldo-expensify** [comment]
Just passing some information in case it is useful:

I noticed that this doesn't happen only with emojis, it also happens if you use Cyrillic letters. The address is "sanitized" by the backend and converted to ascii, but in a poor way, so `Гвгв` or an emoji is converted to `''` and then it causes a crash.

**Comment by grgia** [comment]
> About the company address street we show the error Please enter a valid street address that is not a PO box (The one we already define). It's quite confusing for users IMO, should we show sth like Please enter a valid legal street address that is not a PO box?

@parasharrajat @tienifr Personally, I think we can leave the error messages as is for this

**Comment by grgia** [comment]
Yep all yours @tienifr ! Thank you

**Comment by garrettmknight** [comment]
**Summarizing payments:**
- Contributor: @tienifr $500 paid via upwork
- Reveiwer: @parasharrajat $500

**Comment by garrettmknight** [comment]
Dropping to weekly to complete the checklist and request payment.

**Comment by garrettmknight** [comment]
@tienifr can you take look at the above comment?

**Comment by garrettmknight** [comment]
@tienifr bump

**Comment by garrettmknight** [comment]
Thanks for the reminder, request payment on the 17th!

**Comment by garrettmknight** [comment]
Summary of payments is above: https://github.com/Expensify/App/issues/31385#issuecomment-1858234722

@parasharrajat when you're ready, request payment!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat based on [this summary](https://github.com/Expensify/App/issues/31385#issuecomment-1858234722).
