### ISSUE TITLE
[$500] Chat - No suggestions of users with whom you have not chatted are displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue was found when executing PR:** https://github.com/Expensify/App/pull/30930

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Pre-requisite: user must be logged in with a gmail account.
1. Go to any chat.
2. Enter "@" into the compose box.
3. Type in the whole email of a user that you haven't chatted with before.

## Expected Result:
A user suggestion should appear.

## Actual Result:
There is no suggestions of users with whom you have not chatted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/0cee91c2-1d8a-4e28-ad89-34a70d316638

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f66e6263dc3b7f0f</li>
        <li>Upwork Job ID: 1724824342692425728</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment]
@zanyrenney Could you kindly check internally if the OP is the proper expected way or not?

**Comment by zanyrenney** [comment]
Pretty sure this is working as expected. We want to ensure this behaviour when searching in 🔍  which we do:
![2023-11-20_17-30-35](https://github.com/Expensify/App/assets/56830058/5dbd5375-2b1e-4728-afaf-3e946c40d4e1)

But pretty sure in chat, this shouldn't be appearing anyway.
