### ISSUE TITLE
[$500] Split Bill - Green dot is missing for Admin when create Split Bill from group chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Preconditions:
User A and User B should not have existing conversation

Steps:
1. User B creates Group chat
2. User B Send a Split Bill in the group

## Expected Result:
Green dot should be displayed in the 1:1 conversation in LHN

## Actual Result:
Green dot is missing for Admin when create Split Bill from group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/280b8ea9-1656-4aaa-ad44-92c7c9d0ff65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133bb0b95d40a556a</li>
        <li>Upwork Job ID: 1724822672378744832</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This doesn't look like a bug.
The green dot is displayed only if the report requires an action from the user. If the Admin requests a split bill, the other users owe money to the Admin, but the Admin doesn't owe the money. So the green dot should be displayed for the other users, but not for the Admin.

**Comment by lschurr** [comment]
Closing this one out.
