### ISSUE TITLE
Updates to HelpDot - New Expensify

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#31390]
## Add the following category hub:
- [x] `Chat` - @allroundexperts - https://github.com/Expensify/App/pull/31398

## Remove the following category hubs:
- [x] `Getting Started` - @allroundexperts 
- [x] `Expense & Report Features` - @allroundexperts 
- [x] `Insights & Custom Reporting` - @allroundexperts 
- [x] `Integrations` - @allroundexperts 
- [x] `Manage Employees & Report Approvals` - @allroundexperts 

## Rename the following category hubs:
- [x] `Bank Accounts & Credit Cards` to `Bank Accounts` - @allroundexperts 

## Move the following articles
- [x] [Expensify Chat For Admins ](https://help.expensify.com/articles/new-expensify/getting-started/chat/Expensify-Chat-For-Admins)to `Chat`
- [x] [Expensify Chat For Conference Attendees](https://help.expensify.com/articles/new-expensify/getting-started/chat/Expensify-Chat-For-Conference-Attendees) to `Chat`
- [x] [Expensify Chat For Conference Speakers](https://help.expensify.com/articles/new-expensify/getting-started/chat/Expensify-Chat-For-Conference-Speakers) to `Chat`
- [x] [Expensify Chat Playbook For Conferences](https://help.expensify.com/articles/new-expensify/getting-started/chat/Expensify-Chat-Playbook-For-Conferences) to `Chat`
- [x] [Get to know Expensify Chat](https://help.expensify.com/articles/new-expensify/getting-started/chat/Get-to-know-Expensify-Chat) to `Chat`
- [x] [Security](https://help.expensify.com/articles/new-expensify/getting-started/Security) to `Account Settings`
- [x] [Referral Program](https://help.expensify.com/articles/new-expensify/getting-started/Referral-Program) to `Billing & Plan Types`

## Rename the following articles
- [x] `Get to know Expensify Chat` to `Introducing Expensify Chat`

## Delete the following articles
- [x] Expensify Lounge - https://github.com/Expensify/App/pull/31392

**Comment by maddylewis** [comment]
### Description for `Chat` hub
> Enhance your financial experience using Expensify's chat feature, offering quick and secure communication for personalized support and payment transfers.

**Comment by maddylewis** [comment]
this is complete!

**Comment by maddylewis** [comment]
### Payment Summary
- @allroundexperts $500 (paid via NewDot)

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.
