### ISSUE TITLE
Create icon to use for Chat hub on helpdot

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#31400]
Tracking issue - https://github.com/Expensify/App/issues/31390
______

Can you create an icon for the `Chat` category hub that we're adding to the [New Expensify helpdot homepage](https://help.expensify.com/new-expensify/hubs/)? 

cc @allroundexperts

**Comment by dannymcclain** [comment]
@maddylewis I think we can use this image: https://github.com/Expensify/Web-Static/blob/main/images/illustrations/simple-illustration__commentbubbles.svg

The engineer should be able to literally just copy that SVG file into wherever it needs to go for helpdot and use it as is. Let me know if that's unclear or if y'all need anything else!

**Comment by dannymcclain** [comment]
@maddylewis Are we good with this one?
