### ISSUE TITLE
Delete receipt - App crashed if Delete receipt form IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch App navigate to UIO request with receipt
2. Tap on receipt > tap on 3 dots > Delete receipt

## Expected Result:
App should delete receipt

## Actual Result:
App crashed if delete receipt form IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4638fff7-cfe8-4911-a8ac-4093fee7db81

![Bug6278508_1700102999431!crashed](https://github.com/Expensify/App/assets/78819774/cb5eb105-778e-4e52-be78-d177b3590ee4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
Maybe related to https://github.com/Expensify/App/issues/31407

**Comment by roryabraham** [comment]
Fix verified on staging
