### ISSUE TITLE
[$500]  Profile - Secondary logins are not deleted on the new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop App
2. Create and verify new account (gmail or expensifail)
3. Go to Settings > Profile > Contact Method
4. Tap / Click "New contact method" button
5. Enter email or phone number
6. Select the new secondary login and delete it without verifying
7. Create and verify new secondary login and then try to delete it

## Expected Result:
6-7. Secondary login deleted

## Actual Result:
6-7. Secondary logins are not deleted. User receives an error message
Auth DeleteLogin returned an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f192d7ad-6d24-4c9b-8a1e-2e2e7c99ba46

https://github.com/Expensify/App/assets/78819774/5cbbd8b7-8c54-4a5f-b4d9-f6f21767c8bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cfc0f96c68757aaa</li>
        <li>Upwork Job ID: 1724984792484872192</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

**Comment by saikoaizen** [comment]
This sounds like a backend issue

**Comment by newtome8888** [comment]
Can't reproduce it.

**Comment by adelekennedy** [comment]
Can't reproduce either on staging or desktop - going to close
