### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Web - Login–Auto-fill list appears if click on "Sign in here" in Incognito window via email link.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out of NewDot and request a new magic link
3. Navigate to email and locate the magic link - change to staging if needed
4. Open an new INCOGNITO window and navigate to the staging link
5. Verify the "Here's your magic code" page is displayed
6. Verify there's a link to "Sign In here"
7. Click on the link to "Sign in here"

## Expected Result:
The user is logged in without auto-fill list.

## Actual Result:
Auto-fill list appears when click on the link to "Sign in here" in Incognito window via email link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8f3ea7d6-5a8a-4875-adf7-0fc9c07a4b16

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e92a3a92b9ab41a7</li>
        <li>Upwork Job ID: 1725122083404705792</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27777252</li>
<li>ZhenjaHorbach | Contributor | 27777253</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Auto-fill list appears when click on the link to "Sign in here" in Incognito window via email link
### What is the root cause of that problem?
The root cause is this line.
https://github.com/Expensify/App/blob/48782c700e6abd56c73d317ac1c5bc9462547cfc/src/pages/ValidateLoginPage/index.website.js#L68
### What changes do you think we should make in order to solve the problem?
```
if (isSignedIn) {
            return;
        }
```
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by situchan** [comment]
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/31436#issuecomment-1814715875) looks good to me. I don't recommend changing current visibility logic of LoginForm which is working well. We can just avoid auto focus when screen is not focused.
🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment]
@situchan we're waiting for you here, thanks

**Comment by johncschuster** [comment]
Issuing payment today

**Comment by johncschuster** [comment]
Payment has been issued! 

@situchan, do we require regression test steps?

**Comment by situchan** [comment]
No regression. Not worth adding regression test for this super minor issue

**Comment by johncschuster** [comment]
Great! Thanks, @situchan!
