### ISSUE TITLE
[$500] Login - Validation errors appears when cursor lost focus, a number or a letter is entered

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31434]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the testing desktop app
2. Make the login field to lose cursor focus (click outside the login field)
3. Observe error
4. Enter any letter/number

## Expected Result:
Validation error should not appear once field is lost focus, also validation errors for email or number should not appear immediately once a letter or a number is typed. Ideally the validation error should appear after user clicks on continue button.

## Actual Result:
Validation error appears once cursor focus is lost and when a user types any letter or number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c62c01d5-78db-4b4b-84c3-03d2601de56b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b9e73562a30f5b</li>
        <li>Upwork Job ID: 1725116807168163840</li>
        <li>Last Price Increase: 2023-11-16</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproduce in prod

https://github.com/Expensify/App/assets/115492554/9211cda7-ccf4-4465-8902-e9572362fc0b

**Comment by esh-g** [comment]
Regression from https://github.com/Expensify/App/pull/30563

**Comment by esh-g** [comment]
I think it may be expected... @dukenv0307

**Comment by mallenexpensify** [comment]
Thanks, going to close. 
Thanks too to @HardikChoudhary24  for your proposal, even though we're deciding not to move forward with an update here.
