### ISSUE TITLE
ExpensiMark: prevent parsing triple backtick as inline code

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31493]
**Problem**
Currently, ExpensiMark parses three backticks (` ``` `) like inline code containing a single backtick. However, when typing a message that contains triple backticks, the user usually wants to start a codeblock.

<img width="484" alt="Zrzut ekranu 2023-11-17 o 18 14 58" src="https://github.com/Expensify/App/assets/20516055/41582687-8e09-4cc1-a3a8-50ab7ea7aa9e">

**Solution**
Parse three or more backticks as regular text instead of inline code.

**Test cases**

1. Three backticks
```diff
 Input: "```"
-Current output: "<code>`</code>`<code>`</code>"
+Desired output: "```"
```

2. More backticks
```diff
 Input: "`````"
-Current output: "<code>`</code>```<code>`</code>"
+Desired output: "`````"
```

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by thienlnam** [comment]
@Skalakid Do you have any update on this issue?

**Comment by thienlnam** [comment]
Bump for when you see this @Skalakid

**Comment by thienlnam** [comment]
Bump for when you see this @Skalakid

**Comment by robertKozik** [comment]
Hey @thienlnam 👋 I'll take over this task

**Comment by thienlnam** [comment]
Changes merged, we just need to the expensify-common version bumped in App (if it hasn't happened already)
