### ISSUE TITLE
[HybridApp] Changes required to build the HybridApp

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#31508]
Implement [the "Changes required to build the HybridApp" section of the design doc](https://docs.google.com/document/d/1Mw_YtYql2L4mwyGT_QHQx7mFqDVUc6mOCNIAZh-oWo4/edit#heading=h.ea6rj1guaiwv)

cc @staszekscp @mczernek @WoLewicki - Please comment if you are going to work on this one and I will assign you 😄 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd273da16abe7a45</li>
        <li>Upwork Job ID: 1725660472360333312</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by staszekscp** [comment]
This will be covered in [this PR](https://github.com/Expensify/Mobile-Expensify/pull/12379)

**Comment by AndrewGable** [comment]
Draft PR is up

**Comment by staszekscp** [comment]
The [NewDot PR](https://github.com/Expensify/App/pull/32471) is already on the repo

**Comment by AndrewGable** [comment]
Closed via https://github.com/Expensify/App/pull/32471
