### ISSUE TITLE
[Awaiting Payment] [HybridApp] Recognizing which app is being run

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#31509]
Implement [the "Recognizing which app is being run" section of the design doc](https://docs.google.com/document/d/1Mw_YtYql2L4mwyGT_QHQx7mFqDVUc6mOCNIAZh-oWo4/edit#heading=h.o1cureqrnt7j)

cc @staszekscp @mczernek @WoLewicki - Please comment if you are going to work on this one and I will assign you 😄 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176f29a1c850e2630</li>
        <li>Upwork Job ID: 1725660909896237056</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by AndrewGable** [comment]
Working on this soon ™️

**Comment by staszekscp** [comment]
The [NewDot PR](https://github.com/Expensify/App/pull/32471) is already on the repo

**Comment by dylanexpensify** [comment]
@AndrewGable now that the above PR is on prod (as of 5 days ago) is anything left here?

**Comment by situchan** [comment]
C+ review payment is pending

**Comment by AndrewGable** [comment]
@dylanexpensify - Can you pay out @situchan the standard here? Thanks

**Comment by dylanexpensify** [comment]
Yes! @situchan sent invite to apply!

**Comment by dylanexpensify** [comment]
Bump @situchan!

**Comment by dylanexpensify** [comment]
@situchan bump 🙇‍♂️

**Comment by dylanexpensify** [comment]
@situchan sure can!

**Comment by dylanexpensify** [comment]
@situchan [here](https://www.upwork.com/jobs/~01bbb7ededcd0c8238) you go!

**Comment by situchan** [comment]
Applied job

**Comment by dylanexpensify** [comment]
offer sent @situchan!

**Comment by situchan** [comment]
Not received yet.
@AndrewGable can you please reopen?

**Comment by dylanexpensify** [comment]
reviewing

**Comment by dylanexpensify** [comment]
Paid!
