### ISSUE TITLE
[HybridApp] Authentication and deep linking

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#31511]
Implement [the "Authentication and deep linking" section of the design doc](https://docs.google.com/document/d/1Mw_YtYql2L4mwyGT_QHQx7mFqDVUc6mOCNIAZh-oWo4/edit#heading=h.8fbamj1ic6ki)

cc @staszekscp @mczernek @WoLewicki - Please comment if you are going to work on this one and I will assign you 😄 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb39262456992f7a</li>
        <li>Upwork Job ID: 1725665017987461120</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by AndrewGable** [comment]
Update here: https://expensify.slack.com/archives/C05G14REJRY/p1700494124226729

**Comment by AndrewGable** [comment]
Draft PR is up!

**Comment by staszekscp** [comment]
The [NewDot PR](https://github.com/Expensify/App/pull/32471) is already on the repo

**Comment by AndrewGable** [comment]
Closed via https://github.com/Expensify/App/pull/32471
