### ISSUE TITLE
[HybridApp] Returning Back to Expensify Classic

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#31512]
Implement [the "Returning Back to Expensify Classic" section of the design doc](https://docs.google.com/document/d/1Mw_YtYql2L4mwyGT_QHQx7mFqDVUc6mOCNIAZh-oWo4/edit#heading=h.ic4qxswyzhce)

cc @staszekscp @mczernek @WoLewicki - Please comment if you are going to work on this one and I will assign you 😄 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adfa7fcc44647d85</li>
        <li>Upwork Job ID: 1725665467608625152</li>
        <li>Last Price Increase: 2023-11-18</li>
    </ul>
</details>

**Comment by AndrewGable** [comment]
Working on this!

**Comment by AndrewGable** [comment]
Still working on getting the first PR merged for this one

**Comment by AndrewGable** [comment]
Will be fixed in https://github.com/Expensify/App/pull/32471

**Comment by dylanexpensify** [comment]
@AndrewGable now that the above PR is on prod (as of 5 days ago) is anything left here?
