### ISSUE TITLE
[HOLD for payment 2023-12-07] [ECARD] 🐛 HIGH: Zeros are stripped from ActivatePhysicalCard API params

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31540]
When testing the `ActivatePhysicalCard` flow, testing with `0000` results in sending only `0` or `0011` -> `11` . This only applies to leading zeros 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135500aca531de691</li>
        <li>Upwork Job ID: 1726628554501017600</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by pasyukevich** [comment]
Hi,
I'm Eugene from Callstack - an expert contributor group
I’d like to work on this issue

**Comment by cooldev900** [comment]
I'd like to work to implement this feature.

**Comment by pasyukevich** [comment]
Preparing PR with a fix to be opened

**Comment by grgia** [comment]
not overdue!

**Comment by bfitzexpensify** [comment]
Payment summary:

C+: @parasharrajat to be paid $500 via manual request

BZ checklist done, so we're all finished here, thanks everyone

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
