### ISSUE TITLE
Crash when trying to select address from dropdown menu

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#31542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Email or phone of affected tester (no customers):**
**Issue reported by:** @situchan 

## Action Performed:
- Start adding a bank account
- Get to the 3rd page 'Personal Information'
- Tap personal address and enter some characters
- Select a suggestion from the drop-down menu

## Expected Result:
- The option is pre-filled

## Actual Result:
- App crashes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/10736861/c959bfdf-9f36-400a-9175-d2c1c7103eda

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
@situchan pointed out [here](https://github.com/Expensify/App/pull/30679#discussion_r1399062699) that this is the PR that introduced the crash.

**Comment by situchan** [comment]
No need to add `DeplyBlockerCash` yet until deploy to staging

**Comment by Julesssss** [comment]
Ah thanks, I assumed this was already on staging. We'll still need to fix this ASAP

**Comment by Julesssss** [comment]
Thanks, but for now this isn't open for proposals. We might revert the PR and apply a new solution instead.

**Comment by Julesssss** [comment]
Issues resolved by this revert PR: https://github.com/Expensify/App/pull/31547
