### ISSUE TITLE
[HOLD for payment 2023-12-29] [ECARD] HIGH: Request Physical Card Follow Up

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31557]
https://github.com/Expensify/App/pull/28453#issuecomment-1819197236

cc @pac-guerreiro @allroundexperts

**Comment by pac-guerreiro** [comment]
@grgia You can assign me to this! 😄

**Comment by grgia** [comment]
Assigning @allroundexperts for C+ as you have context on this one!

**Comment by pac-guerreiro** [comment]
@grgia @allroundexperts just created a PR with the fixes for this

**Comment by grgia** [comment]
@MitchExpensify could you help me out with the $500 C+ review payment to @allroundexperts

**Comment by MitchExpensify** [comment]
@allroundexperts please request payment on NewDot, thanks!

**Payment summary:** 

- $500 C+ - @allroundexperts

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on comment above.
