### ISSUE TITLE
[Form Provider Refactor] WorkspaceNewRoomPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#31566]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/workspace/WorkspaceNewRoomPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1cb8a688a4d78ae</li>
        <li>Upwork Job ID: 1726653570514927616</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kowczarz</details>

**Comment by luacmartins** [comment]
@cdOut @kowczarz are either of you available to work on this one?

**Comment by luacmartins** [comment]
bump @cdOut @kowczarz

**Comment by kowczarz** [comment]
It's in reveiw already https://github.com/Expensify/App/pull/30996

**Comment by luacmartins** [comment]
Ah thanks for linking that one. I consolidated both components into https://github.com/Expensify/App/issues/28877, so we can close this issue.
