### ISSUE TITLE
[HOLD for payment 2023-12-28] [$125] [Form Provider Refactor] WorkspaceRateAndUnitPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#31563]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js`

cc @kowczarz @cdOut

Note: this component also needs to be migrated to a functional component!
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154bcb8f849df37e0</li>
        <li>Upwork Job ID: 1726652102251675648</li>
        <li>Last Price Increase: 2023-11-23</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@cdOut @kowczarz are either of you available to work on this one?

**Comment by cdOut** [comment]
Yes! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by cooldev900** [comment]
I would like to work on this task.

**Comment by luacmartins** [comment]
Thanks for the interested @cooldev900! However, we already assigned a contributor to work on it.

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by luacmartins** [comment]
Still working on the draft PR

**Comment by luacmartins** [comment]
Still working on the PR

**Comment by anmurali** [comment]
Payment summary

- [ ] $125 to @akinwale

**Comment by akinwale** [comment]
@mallenexpensify I have accepted the offer. I cannot find a direct to the job but here's a link to the workroom if you can try to access that: https://www.upwork.com/nx/wm/workroom/35923566/overview

**Comment by mallenexpensify** [comment]
Contributor+: @akinwale paid $125 via Upwork. 

ah ha! That link does work, thanks for sharing.
