### ISSUE TITLE
[HOLD for Payment] [$125] [Form Provider Refactor] ReportWelcomeMessagePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#31560]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring src/pages/ReportWelcomeMessagePage.js

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7c99c61efa281a3</li>
        <li>Upwork Job ID: 1726650931727286272</li>
        <li>Last Price Increase: 2023-11-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by luacmartins** [comment]
@cdOut @kowczarz are either of you available to work on this one?

**Comment by cdOut** [comment]
Yes! I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment]
waiting on draft PR

**Comment by getusha** [comment]
@luacmartins Friendly bump for payment.

**Comment by luacmartins** [comment]
@sakluger can you assist with payment?

**Comment by getusha** [comment]
Friendly bump @sakluger

**Comment by sakluger** [comment]
Sorry all, I should have noticed this one, I missed it I think because the automations failed.

@getusha I sent you an offer via Upwork, please let me know once you've accepted. Thanks!

**Comment by getusha** [comment]
@sakluger accepted

**Comment by sakluger** [comment]
Thanks! All paid.
