### ISSUE TITLE
[HOLD for payment 2023-12-06] [$125] [Form Provider Refactor] EditRequestMerchantPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#31561]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/EditRequestMerchantPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9a2a4f759bbdc3f</li>
        <li>Upwork Job ID: 1726651177853239296</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task.

**Comment by stephanieelliott** [comment]
PR was deployed to staging a few hours ago!

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @cdOut N/A
 - Contributor+: $125 @allroundexperts -- can you please complete the BZ checklist? 
 
 Upwork job is [here](https://www.upwork.com/jobs/~01b9a2a4f759bbdc3f)

**Comment by luacmartins** [comment]
Just pending payment

**Comment by stephanieelliott** [comment]
> Contributor+: $125 @allroundexperts -- can you please complete the BZ checklist?

Bump @allroundexperts

**Comment by allroundexperts** [comment]
@stephanieelliott There is no checklist needed here. This was a component refactoring ticket.

**Comment by JmillsExpensify** [comment]
$125 approved for @allroundexperts based on comments above.

**Comment by luacmartins** [comment]
Just pending payment

**Comment by stephanieelliott** [comment]
All paid here!
