### ISSUE TITLE
Connect bank account - Can't enter/correct the date manually in Company information page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Connect bank account
4. Process to Company information page
5. Open section: Incorporate date

## Expected Result:
The date can be entered either directly or by choosing from the calendar. The calendar can be hidden

## Actual Result:
Entering the date is possible only by selecting a date from the calendar, entering the date manually is not possible. The calendar always remains open, it cannot be closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8c0af944-67d4-4831-9584-c3fb7e2071a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
It seems to be with any date picker, I can also reproduce with the Date of Birth picker. 

<img width="200" alt="image" src="https://github.com/Expensify/App/assets/2229301/6afdb9b0-a25b-4211-af35-377e40a80d94">

**Comment by francoisl** [comment]
Ah yes that's right, we started using `NewDatePicker` instead of `DatePicker` recently in this PR https://github.com/Expensify/App/pull/30568. Going to remove the blocker label and close.
