### ISSUE TITLE
[$500] Chat - A single line code block becomes multiline in edit mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open any 1:1 chat
3. Send a single line code block in any chat (```single line```)
4. Edit the message

## Expected Result:
A single line code block should be single line in the edit mode too

## Actual Result:
A single line code block becomes multiline in edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8aa090b2-a1fe-4296-aad2-8efcad16e1e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013245aeb07eeecaf4</li>
        <li>Upwork Job ID: 1726686053268701184</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by erquhart** [comment]
This isn't a bug, code fences are block content and putting them back inline for editing purposes doesn't server a purpose when the output will always be block level and never inline.

**Comment by zanyrenney** [comment]
Thank you @erquhart
