### ISSUE TITLE
Bank account - Error returns when input is entered in phone number, Tax ID and SSN fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30568
## Action Performed:
Bug 1: Phone number and Tax ID field
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace
3. Go to Bank account
4. Click Connect manually
5. Proceed to Company information
6. Click Phone number field and enter a phone number
7. Click on the Tax ID field

Bug 2: SSN field
Precondition: Have a bank account added
1. Navigate to staging.new.expensify.com
2. Go to Settings > Wallet
3. Click Enable Wallet
4. Click on the SSN field
5. Enter a value

## Expected Result:
The field will not return validation error when the input is not completed

## Actual Result:
The phone number field returns validation error as soon as value is entered.
Tax ID and SSN fields show error as soon as the input field is focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/80998a5c-e155-4835-aa47-1e820b70a4ff

https://github.com/Expensify/App/assets/78819774/ffefa611-9e50-4308-9aab-0066a87620c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - Error returns when input is entered in phone number, Tax ID and SSN fields 

### What is the root cause of that problem?
We are validating Form when input change
### What changes do you think we should make in order to solve the problem?

Should pass shouldValidateOnChange: false to FormProvider in CompanyStep Page
### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
I don't think this is a bug

**Comment by situchan** [comment]
I think this is against Form guideline.
cc: @luacmartins 

https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#validate-on-blur-on-change-and-submit

> Once a user has “touched” an input, i.e. blurred the input, we will also start validating that input on change when the user goes back to editing it.

But input is not "touched" yet.
