### ISSUE TITLE
[HOLD for payment 2023-12-04] Login - Background color of chat list is different from the header in LHN when it is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Log in

## Expected Result:
The background color of the chat list matches the background color of the header in LHN when it is loading

## Actual Result:
The background color of the chat list is different from the header in LHN when it is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 
<img width="407" alt="Bug6284412_1700510021128!Screenshot_2023-11-21_at_03 47 25" src="https://github.com/Expensify/App/assets/78819774/f54b271d-7077-41ea-a028-390862e2c0bf">

https://github.com/Expensify/App/assets/78819774/d100a0f9-36ed-4a86-af38-456ecbe30b05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can work on this

**Comment by luacmartins** [comment]
I'm gonna demote this to NAB since it's a very minor UI issue. We already have a fix up for it but I don't think it's worth CPing it.

**Comment by Julesssss** [comment]
@luacmartins -- @situchan pointed out [here](https://github.com/Expensify/App/pull/31052#issuecomment-1820936621) that [this](https://github.com/Expensify/App/pull/31052#issuecomment-1820936621) is possibly the PR that introduced the regression

**Comment by luacmartins** [comment]
We reverted the offending PR so this is fixed!
