### ISSUE TITLE
[HOLD for payment 2024-01-09] [$250] Ensure newly added report actions allow threads being created on them

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#31582]
👋 Coming from [here](url), we'd like someone to look into an automated solution to avoid running into this again.

We've added a bunch of report actions in recent months, and we'll be continuing to do that as we bring more functionality over into NewDot. As we've built these report actions we've intermittently shown the `reply in thread` button in the comment action menu on them. That created a situation where some report actions allowed threads while others didn't, leading to an inconsistent and confusing experience with no rhyme and reason to it. 

@tgolen outlined some options [here](https://github.com/Expensify/App/issues/28934#issuecomment-1797035494) on how we can better catch that in development going forward to make sure we uphold this consistency for threads. That's a good place to start and we'd like someone to explore the options further to put this safeguard in place. 

Thanks!
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014617a7e47bd69ebb</li>
        <li>Upwork Job ID: 1726698548887613440</li>
        <li>Last Price Increase: 2023-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 27807672</li>
<li>dukenv0307 | Contributor | 28065176</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Switching out the `Bug` label now this has an Upwork job.

**Comment by s77rt** [comment]
Taking this as C+

**Comment by trjExpensify** [comment]
Done!

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA is correct. However the suggested solution will not prevent similar bugs from occurring but only reduce them.

> When we have a new action, if this action can have Reply in Thread option, no need to change anything. **If not we only need to add this to shouldReplyInThread**.

We could be adding a new action that should not have the reply in thread option without adding it to the `shouldReplyInThread` function since there is no enforcement.

**Comment by s77rt** [comment]
@dukenv0307 This is not looking any different. 

> In the further when a new action is added, we only need to add this to NOT_ALLOWED_THREAD const if it doesn't has thread option

We can still add a new action and forget it to `NOT_ALLOWED_THREAD`

**Comment by trjExpensify** [comment]
@s77rt is working through proposals, Melv.

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by s77rt** [comment]
Same ^

**Comment by trjExpensify** [comment]
@dukenv0307 any thoughts?

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by trjExpensify** [comment]
So what's the plan here? One of Tim's suggestions was this: 

>Maybe better to change the logic for Reply in thread which wouldn't require it to be updated for every new action (for example, rather than checking for all the actions you CAN reply to, only check for the ones you CANNOT reply to, or vice versa, whatever)

I do feel like checking for ones you can't reply to are better than needing to remember to add a check for the ones you can reply to. I think the ones you can't reply to should be super minimal.

**Comment by s77rt** [comment]
@trjExpensify That's what @dukenv0307 proposed as well however it's not full proof as it only "inverses" the bug. The full proof solution is to use a configuration file (the 4th suggestion from Tim's list).

> I think the ones you can't reply to should be super minimal

They are not, but the new report actions that we may add are more likely to be thread-enabled.

cc @tgolen for visibility

**Comment by trjExpensify** [comment]
Yeah, but I think given that by and large almost all reportActions should be thread-enabled we vastly reduce the likelihood of introducing the inconsistency again. You have to be explicit to make it not threadable, and for that, you need to have a reason to consider doing it.

**Comment by s77rt** [comment]
Makes sense. Let's go with @dukenv0307's proposal.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/31582#issuecomment-1820149800)

**Comment by pecanoro** [comment]
Sounds good! Assigning @dukenv0307

**Comment by trjExpensify** [comment]
Woof, good question! I can think of these two off the top of my head for the `[Deleted message]` parent comment and the split action preview. Perhaps the "uploading attachment..." action as well?

<img width="833" alt="image" src="https://github.com/Expensify/App/assets/16232057/6e30e388-bc8d-4909-9fcc-416340111149">

<img width="828" alt="image" src="https://github.com/Expensify/App/assets/16232057/0d4c4f69-4294-4687-b0c3-4dddd9c35417">

**Comment by trjExpensify** [comment]
Err.. no idea why Melv did that. Dropping @anmurali off!

**Comment by trjExpensify** [comment]
Okay, so no regression checklist for this. It's a follow-up improvement in the code so we can hopefully minimise the amount of non-threadable report actions that get added.

Confirming payments as follows: 

@s77rt - $250 for the C+ review
@dukenv0307 - $250 for the fix

**Comment by trjExpensify** [comment]
@dukenv0307 - paid! 
@s77rt - looks like you denied the offer. Anything to note there, or should I send you a fresh one?

**Comment by s77rt** [comment]
@trjExpensify Can you please send a new offer. I thought Melvin would send two offers when @dukenv0307 got assigned. I declined the first one as it had the wrong role.

**Comment by trjExpensify** [comment]
Sent!

**Comment by s77rt** [comment]
Accepted! Thanks!

**Comment by trjExpensify** [comment]
Paid!
