### ISSUE TITLE
mWeb/Safari - Chat - The top part of the UI is enlarged when posting bold text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new account
3. Open a new conversation
4. Type in "*Text*"

## Expected Result:
The top UI shouldn't be enlarged

## Actual Result:
The top part of the UI is enlarged when posting bold text. The UI is blocking a big portion of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/79e7f175-09af-47b8-a253-bd3067a64009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Reproduced on staging on my physical device, need to figure out how to access local web on a simulator to make more progress though

**Comment by amyevans** [comment]
Got access to mweb solved with https://stackoverflowteams.com/c/expensify/questions/137 (and then used [this workaround](https://expensify.slack.com/archives/C01GTK53T8Q/p1699955573768969?thread_ts=1699953732.397189&cid=C01GTK53T8Q) to get dev working on my physical device).

However I haven't been able to reproduce (on `main`) 🤔 . I'll try on the `staging` branch.

**Comment by amyevans** [comment]
Okay nevermind, I can reproduce on `main`, you just have to do it twice in a row and it's reproducible the second time

**Comment by amyevans** [comment]
Not reproducible when I revert https://github.com/Expensify/App/pull/21298 locally, so I'm going to open a PR to revert that.

**Comment by amyevans** [comment]
Getting
> Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged.

when trying to do that via the web interface, so I'll do it manually (there was a merge conflict when doing it locally so I guess that's it)

**Comment by lukemorawski** [comment]
Interesting one. Looks like it happens on newly created chats, on first message regardless if it's a bold text or not. Having a look.

**Comment by amyevans** [comment]
Confirmed on staging this issue is no longer present following the CP, going to close!
