### ISSUE TITLE
[$500] Web - User It is not redirected to New dot after logging in in Old dot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31522

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Sign into NewDot with UserA
3. Now go to OldDot and sign with some other UserB on public domain (like gmail)

## Expected Result:
1. Verify you have been redirected to NewDot
2. Verify you are signed in as UserA

## Actual Result:
User should directed  to NewDot after sign with UserB in Olddot

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a670dd3c-c499-4c8c-ac60-98dcaeef2dbf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by erquhart** [comment]
Is OldDot open source? Not sure this is something contributors can fix.

**Comment by jliexpensify** [comment]
@allroundexperts just going to assign you as @kbecciv is saying it's related to https://github.com/Expensify/App/pull/31522

**Comment by jliexpensify** [comment]
I'm also a bit confused by this issue's `Actual Result` - is the expectation that you should be redirected to New.Dot as User B? @kbecciv can you clarify this? The video doesn't seem to illustrate the bug.

**Comment by kbecciv** [comment]
@jliexpensify Correct, user should be diredirected to ND as a UserB, updated the video!

**Comment by jliexpensify** [comment]
Bump @allroundexperts - might be related to your PR?

**Comment by allroundexperts** [comment]
@jliexpensify @kbecciv I just checked and the reason why you're not being redirected is that you don't have the redirect beta enabled for your account. In order to make sure that redirect happens, you need to be logged in to OldDot using an email that ends with `+classicredirect`.

**Comment by allroundexperts** [comment]
I think this issue can be safely closed.

**Comment by jliexpensify** [comment]
Thanks for the context Sibtain!
