### ISSUE TITLE
[HOLD for payment 2023-12-04] [HOLD for payment 2023-11-30] [$500] iOS - LHN - Skeleton appears instead of LHN if user go offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31610]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open iOS / iPad App
2. Login with any account
3. Go offline while in LHN and without opening any chats

## Expected Result:
LHN is shown correctly if the user goes offline

## Actual Result:
Skeleton appears instead of LHN if user go offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native/ iPad Pro 9.7 / 16.6
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4ac7a9a3-2861-4980-a1b1-23ae17e66e36

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac90ec7e5e193317</li>
        <li>Upwork Job ID: 1726911947115495424</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27815806</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
Not reproduced on production

https://github.com/Expensify/App/assets/115492554/c638908a-0d0c-44a6-8e9d-d09629540b1c

**Comment by Julesssss** [comment]
I can reproduce on staging `v1.4.1-7`. I was on the fence about this being a blocker as it only occurs for new sign-ins... but lets see if we can locate the issue before it gets deployed to prod. 

https://github.com/Expensify/App/assets/10736861/71b7bbe2-be92-4744-aa07-df81739c9897

**Comment by Julesssss** [comment]
I reviewed the prod...staging diff and recent changes to [OptionRowLHN](https://github.com/Expensify/App/commits/main/src/components/LHNOptionsList/OptionRowLHN.js) & [LHNOptionsList](https://github.com/Expensify/App/commits/main/src/components/LHNOptionsList/LHNOptionsList.js).

[This one](https://github.com/Expensify/App/pull/31052/files) which migrated LHNOptionsList seems the likely cause as it moved the isLoading condition that wraps `OptionsListSkeletonView`. Commenting on the issue to see if we can fix or will need to revert.

**Comment by TMisiukiewicz** [comment]
@Julesssss unfortunately I cannot reproduce it on the simulator, could you provide me the exact steps to follow?

I am not sure if this is related to FlashList migration, since skeleton in `SidebarLinks` is rendered based on the `isLoading` value coming from props. There were no changes made to this prop itself. 

The styles of displaying the list and skeleton had to change because of the FlashList requirements, but the logic behind displaying the skeleton remained the same. Maybe the bug is in the `isLoading` logic?
```const isLoading = SessionUtils.didUserLogInDuringSession() && isLoadingReportData;```

https://github.com/Expensify/App/assets/13985840/b1471c8e-f6d2-4825-abf9-6812b487517d

**Comment by Julesssss** [comment]
Hey @TMisiukiewicz, I'm[ pretty convinced ](https://github.com/Expensify/App/pull/31052#issuecomment-1821193139)that this PR introduced the bug. As testing/reproducing is difficult I think the best path forward is to revert the PR. Does anyone dissagree?

**Comment by Julesssss** [comment]
@TMisiukiewicz I'm building to a physical device, which is going to be tricky/impossible for you unfortunately

**Comment by situchan** [comment]
I just double confirmed on my iPhone that https://github.com/Expensify/App/pull/31052 caused this regression.

On latest main:

https://github.com/Expensify/App/assets/108292595/e9e9b53a-56c0-422d-96d1-630dc404fa21



After revert (draft PR: https://github.com/Expensify/App/pull/31642):

https://github.com/Expensify/App/assets/108292595/b4ce5571-099d-4307-affa-0e20a8323ea1


@Julesssss I think we can proceed with revert as it will not likely to be fixed before next deploy.

**Comment by TMisiukiewicz** [comment]
Yeah since we cannot reproduce it let's revert it to have more time for investigation. @mountiny is there any way we could run the app on the physical devices? The bug is not reproducible on simulators

**Comment by situchan** [comment]
@TMisiukiewicz here's tip: https://github.com/Expensify/App/pull/30374#issuecomment-1789680607 I am using this approach.

**Comment by Julesssss** [comment]
Thanks both, we'll revert [here](https://github.com/Expensify/App/pull/31642)

**Comment by luacmartins** [comment]
Removing the blocker label since we CPed a revert that fixes the issue.

**Comment by TMisiukiewicz** [comment]
@Julesssss I can confirm I was able to reproduce it on the device, working on a fix

**Comment by getusha** [comment]
Unsigned myself based on https://github.com/Expensify/App/pull/31711#issuecomment-1823234683, @Julesssss lets assign @situchan instead.

**Comment by situchan** [comment]
BZ Checklist:

1. This regression came from FlatList > FlashList migration
2. https://github.com/Expensify/App/pull/31052#issuecomment-1821193139
3. N/A
4. N/A as caught by Applause

**Comment by Julesssss** [comment]
Can be paid out tomorrow

**Comment by kevinksullivan** [comment]
Figure we're close enough given it's nighttime on the west coast. Paid out.
