### ISSUE TITLE
[HOLD for #27392] [$500] iOS - Profile - Local time does not show the hour after GMT for users in GMT+n time zone

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch New Expensify app.
2. Tap Search.
3. Search for a user in GMT+n time zone ([applausetester+kh271007@applause.expensifail.com](mailto:applausetester+kh271007@applause.expensifail.com)
)
4. Tap on the chat header.

## Expected Result:
The local time shows the correct time zone.

## Actual Result:
The local time shows only GMT and it is missing the hours behind GMT (GMT+n).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/247c0849-d3f4-4a27-91c4-cd089b8a6f42

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143fc4857e82b1840</li>
        <li>Upwork Job ID: 1726939891316756480</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 27793675</li>
</ul></li>
    </ul>
</details>

**Comment by erquhart** [comment]
`date-fns-tz` already handles this for us: https://github.com/Expensify/App/blob/281a940cfa1fd0c4286d3f1cb95acadc4ec736fc/src/libs/DateUtils.ts#L204-L206

I'm seeing the user in question doesn't have a timezone set, so it defaults to my local time. Maybe a backend issue with returning automatic timezones?

I manually set a test account to Europe/Paris and it works as expected:
<img width="460" alt="Screenshot 2023-11-21 at 9 30 40 AM" src="https://github.com/Expensify/App/assets/2112202/3e0666c3-ffb0-4fe2-98fb-1d5cc4c7146c">

**Comment by s77rt** [comment]
Taking this as C+

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA is correct. However the solution does not seem to be the best to do here.

**Comment by s77rt** [comment]
@ZhenjaHorbach Thanks for the proposal. Your RCA is not complete.

**Comment by s77rt** [comment]
I have been checking this and it's indeed related to `Intl.DateTimeFormat` poor support on Native (especially iOS for this case). The easiest solution is to use a polyfill. That's also the [library](https://github.com/marnusw/date-fns-tz/) suggestion 

> Modern browsers and Node.js all support the [necessary features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Browser_compatibility), and for those that don't a [polyfill](https://formatjs.io/docs/polyfills/intl-datetimeformat) can be used.


I have also found that we have a related issue https://github.com/Expensify/App/issues/27392 and @tienifr's [solution](https://github.com/Expensify/App/issues/27392#issuecomment-1791126160) includes the polyfill solution (step 1).

**Comment by s77rt** [comment]
We that ^ being said I think we should put this one on hold for https://github.com/Expensify/App/issues/27392. cc @sakluger

**Comment by sakluger** [comment]
Thanks @s77rt! I'll put this one on hold, hopefully https://github.com/Expensify/App/issues/27392 fixes it.

**Comment by s77rt** [comment]
@dukenv0307 Indeed the passed datetime is useless since we are only extracting the time zone, any datetime will work just fine. But the current way we are doing it is still the correct way, although it seems that the timezone abbreviation is a 1:1 map it could be complex to maintain. More importantly the list you are suggesting to add is already available in the js engines so it would be a waste to add it again as it will just increase the App bundle size. iOS is the only affected platform where a polyfill is needed but I can see this getting fixed in the future to remove that polyfill and relay only on the Intl API.

**Comment by s77rt** [comment]
Still on hold

**Comment by s77rt** [comment]
Still on hold

**Comment by sakluger** [comment]
Still on hold for https://github.com/Expensify/App/issues/27392. That issue's PR is in review, we'll see soon if that one fixes this as well.

**Comment by s77rt** [comment]
Same ^

**Comment by sakluger** [comment]
The PR for the hold issue (https://github.com/Expensify/App/issues/27392) is still in review.

**Comment by sakluger** [comment]
The hold issue was deployed. I tested and this is working correctly now! Thanks everyone 🙇
