### ISSUE TITLE
[Wave 6: Tags] Support Tag in Bill Split

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#31631]
Just like we did in https://github.com/Expensify/App/pull/27936 we should add Tag support for the bill split flow. Meaning: 
- tag can be selected
- tag is optimistically set for the bill split and resulting expense 
- tag is sent to the API as part of the splitBill API call

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
@puneetlath, can I implement viewing/editing a tag in the scope of this issue? Like it was for categories here - https://github.com/Expensify/App/pull/28628.

**Comment by puneetlath** [comment]
Yes please. Let's use this issue to bring feature parity for tags on bill split to whatever we do for categories.

**Comment by rezkiy37** [comment]
The PR - https://github.com/Expensify/App/pull/31647 - is being reviewed internally now. Opening soon 🙂

**Comment by yuwenmemon** [comment]
I _believe_ I have a fix for the aforementioned deploy blocker, please see: https://github.com/Expensify/App/pull/32541

**Comment by puneetlath** [comment]
Looks like we need to pay out @cubuspl42 for C+ on [this](https://github.com/Expensify/App/pull/31647). Is that right?

**Comment by cubuspl42** [comment]
@puneetlath Yes, sounds right

**Comment by puneetlath** [comment]
@cubuspl42 offer here: https://www.upwork.com/nx/wm/offer/100143026

Please ping me on this issue once you've accepted.

**Comment by cubuspl42** [comment]
@puneetlath Thank you, done

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
