### ISSUE TITLE
[$250] Code blocks of only spaces don't render

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat
2. Send a text wrapped in two spaced backticks(Eg. ` ` Hello ` ` ). i.e Have a space between the backticks

## Expected Result:
he backtick should be in the code block

## Actual Result:
One Backtick is out of the code block

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/594496a1-8de3-460d-ada7-f2ad8051b361

![Bug6285284_1700561421464!image](https://github.com/Expensify/App/assets/78819774/9d2e47b7-61dd-4519-bfc7-6b37c2f533fc)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01369e16f895581dbb</li>
        <li>Upwork Job ID: 1726984904265334784</li>
        <li>Last Price Increase: 2024-04-17</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

One backtick is outside the code block when we send ` ` hello ` `

### What is the root cause of that problem?

Here is the regex for the inline code block
```
        regex: /(\B|_|)&#x60;(.*?\S.*?)&#x60;(\B|_|)(?!&#x60;|[^<]*<\/pre>)/g,
```

As you can see, we add negative lookahead assertion `?!&#x60;` to take the last backtick but didn't take care of the space characters before it. 

This is the root cause



### What changes do you think we should make in order to solve the problem?

We need to consider the cases where spaces exist before the backtick
Update the above regex to
```
        regex: /(\B|_|)&#x60;(.*?\S.*?)&#x60;(\B|_|)(?!(\s*&#x60;)|[^<]*<\/pre>)/g,
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
Surely this is a regression from somewhere right? cc @parasharrajat or @allroundexperts might know. I feel like we test markdown endlessly.

**Comment by s-alves10** [comment]
Inline code regex was changed 3 months ago but that change didn't cause this issue.
I don't think this is a recent regression

**Comment by s-alves10** [comment]
@hoangzinh 

```
` ` hello ` `
``` ```
```

Comparing the above two cases, the first case needs to extend the inline code block content as possible including the space character, and the second case needs to extend the content as possible not including the space.

We need to set clear expectation here

Note: I've found that there are some differences in inline code block parsing between GitHub and Expensify. I'd like to know what the Expensify rule is based on

**Comment by twisterdotcom** [comment]
FWIW, I think it should render like GitHub: ` ` hello ` `.

We are also doing _a lot_ of ExpensiMark updates here: https://github.com/Expensify/App/issues/27977#issuecomment-1809820659. Perhaps we should hold Markdown issues on that larger project @parasharrajat / @tomekzaw / @thienlnam?

**Comment by tomekzaw** [comment]
I believe this is related to https://github.com/Expensify/App/issues/31493 but other issues seem to be independent.

**Comment by thienlnam** [comment]
> We are also doing a lot of ExpensiMark updates here: https://github.com/Expensify/App/issues/27977#issuecomment-1809820659. Perhaps we should hold Markdown issues on that larger project @parasharrajat / @tomekzaw / @thienlnam?

I think we should keep track of all these markdown changes to make sure the expected outcome is correct. Not sure how many of these there are though.

Though since this looks related to https://github.com/Expensify/App/issues/31493, let's just hold this issue on that

**Comment by twisterdotcom** [comment]
Still held on https://github.com/Expensify/App/issues/31493

**Comment by twisterdotcom** [comment]
Still held.

**Comment by twisterdotcom** [comment]
Will test this with new markdown when it hits prod.

**Comment by twisterdotcom** [comment]
Oh, it's still not on web yet: https://expensify.slack.com/archives/C06BDSWLDPB/p1706897366549169.

Making weekly again.

**Comment by twisterdotcom** [comment]
Still waiting on markdown hitting web.

**Comment by twisterdotcom** [comment]
Waiting on https://github.com/Expensify/App/issues/36071#issue-2123827690

**Comment by twisterdotcom** [comment]
Still going to wait on live markdown being everywhere.

**Comment by twisterdotcom** [comment]
This is still a weird little thing:
<img width="221" alt="image" src="https://github.com/Expensify/App/assets/9133401/223a02e2-4331-4829-b69f-0e4b32437e41">

<img width="578" alt="image" src="https://github.com/Expensify/App/assets/9133401/917258e7-4d2d-4863-9bf7-3c1df9330305">

**Comment by tomekzaw** [comment]
@hoangzinh It looks like the root cause of this issue is located in ExpensiMark.

Let's ask @robertKozik from the Live Markdown team at SWM if he wants to come up with a fix or rather make it external.

**Comment by twisterdotcom** [comment]
@robertKozik can we assign you or somebody from the Live Markdown team here?

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM `react-native-live-markdown` team, I'll be handling this issue together with https://github.com/Expensify/App/issues/39518 you can assign me to this issue 😄

**Comment by BartoszGrajdek** [comment]
@thienlnam this issue was due to expensify-common inconsistency between live markdown & expensify. Can we get it closed since it's now working the same way both in composer & chat?
