### ISSUE TITLE
[HOLD for payment 2023-12-07] [Theme Switching Migration] SelectionList Batch

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31678]
As part of the Theme Switching Project, we need to migrate the following files:

- [ ] MultipleAvatars.tsx
- [ ] SelectCircle.tsx
- [ ] BaseOptionsSelector.js
- [ ] OfflineWithFeedback.js
- [ ] Icon/index.tsx
- [ ] src/styles/optionRowStyles/index.ts
- [ ] src/styles/optionRowStyles/index.native.ts

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5eccec63c7d507e</li>
        <li>Upwork Job ID: 1727266939969630208</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by grgia** [comment]
Part of https://github.com/Expensify/App/issues/31677

**Comment by grgia** [comment]
We may not require C+ review for this, just a heads up @alitoshmatov

**Comment by alitoshmatov** [comment]
Got it!

**Comment by koko57** [comment]
leaving a comment to be assigned :)

**Comment by koko57** [comment]
I think we can add these files to this batch:

src/components/OptionsList/optionsListPropTypes.js
src/components/OptionsSelector/optionsSelectorPropTypes.js
src/styles/optionRowStyles/index.ts
src/styles/optionRowStyles/index.native.ts

**Comment by grgia** [comment]
updated!

**Comment by koko57** [comment]
@grgia sorry, I went too far with these ones:
src/components/OptionsList/optionsListPropTypes.js
src/components/OptionsSelector/optionsSelectorPropTypes.js
they won't use the hook anyway and will be removed after migration to typescript. I think we can remove them from the list.

**Comment by grgia** [comment]
@koko57 done! no worries

**Comment by koko57** [comment]
@grgia PR in draft

**Comment by koko57** [comment]
PR opened for the review https://github.com/Expensify/App/pull/31774

**Comment by johncschuster** [comment]
Thanks for calling that out, @alitoshmatov!

**Comment by johncschuster** [comment]
I've reviewed the PR and it looks like I don't need to issue payment here. Please reopen if I've misunderstood!
