### ISSUE TITLE
[HOLD for payment 2023-12-08] [Theme Switching Migration] MoneyRequest Batch

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31683]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] ConfirmedRoute.js
- [ ] TabSelector.js
- [ ] PendingMapView.tsx

**Comment by koko57** [comment]
leaving a comment to be assigned :)

**Comment by keisyrzk** [comment]
Hello! I'm Krzysztof from Callstack - an expert contributor group and I would like to work on this one.
