### ISSUE TITLE
[HOLD for payment 2023-12-08] [Theme Switching Migration] Navigation + SignIn + WholeApp Batch

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31684]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] ModalStackNavigators.js,
- [ ] NavigationRoot.js,
- [ ] Terms.js
- [ ] GrowlNotification/index.js
- [ ] getRootNavigatorScreenOptions.js
- [ ] src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
- [ ] src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.js
- [ ] src/libs/Navigation/AppNavigator/RHPScreenOptions.js
- [ ] src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
- [ ] src/pages/signin/SignInPageLayout/signInPageStyles/index.native.js
- [ ] src/pages/signin/SignInPageLayout/signInPageStyles/index.js
- [ ] src/components/ScreenWrapper/index.js

**Comment by koko57** [comment]
leaving a comment to be assigned :)

**Comment by lukemorawski** [comment]
taking care of this one

**Comment by koko57** [comment]
We can add these files to this batch:
getRootNavigatorScreenOptions.js
src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.js
src/libs/Navigation/AppNavigator/RHPScreenOptions.js
src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.js
src/pages/signin/SignInPageLayout/signInPageStyles/index.native.js
src/pages/signin/SignInPageLayout/signInPageStyles/index.js
src/components/ScreenWrapper/index.js

**Comment by grgia** [comment]
updated description and assigned @lukemorawski
