### ISSUE TITLE
[HOLD for payment 2023-12-07] [Theme Switching Migration] Auth2FA Batch

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31680]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] AnimatedStep/index.js
- [ ] OfflineIndicator.js
- [ ] PressableWithDelayToggle.tsx
- [ ] GenericPressable/BaseGenericPressable.tsx (is used in PressableWithDelayToggle)

**Comment by koko57** [comment]
leaving a comment to be assigned :)

**Comment by keisyrzk** [comment]
Hello! I'm Krzysztof from Callstack - an expert contributor group and I would like to work on this one.

**Comment by s77rt** [comment]
@grgia Can you please assign me here?

**Comment by koko57** [comment]
@mountiny please add @keisyrzk to the Contractors list 🙂 Melvin doesn't know yet he's from Callstack

**Comment by mountiny** [comment]
Made a PR for that

**Comment by grgia** [comment]
hey @miljakljajic  could you help me out with the $500 C+ review payment to @s77rt?

**Comment by miljakljajic** [comment]
contract sent @s77rt !

**Comment by s77rt** [comment]
@miljakljajic Accepted! Thanks!

**Comment by miljakljajic** [comment]
Paid! Thank you for your work @s77rt 

Seems like @keisyrzk and @koko57 are both from callstack, so are we good to close - no further payments?
