### ISSUE TITLE
[HOLD for payment 2023-12-08] [Theme Switching Migration] EnablePayments Batch

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31681]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] LongTermsForm.js
- [ ] CollapsibleSection/index.tsx
- [ ] BaseOnfidoWeb.js
- [ ] Picker/BasePicker.js
- [ ] src/pages/ReimbursementAccount/RequestorStep.js
- [ ] src/components/Icon/BankIcons.ts

**Comment by koko57** [comment]
leaving a comment to be assigned :)

**Comment by koko57** [comment]
We can sdd these files to this batch:
src/pages/ReimbursementAccount/RequestorStep.js
src/components/Icon/BankIcons.ts

**Comment by grgia** [comment]
updated description!

**Comment by koko57** [comment]
@grgia I'll be working on this one

**Comment by koko57** [comment]
@grgia fontFamily imports should be left as they are now? `import fontFamily from '@styles/fontFamily';`

**Comment by grgia** [comment]
cc @chrispader on https://github.com/Expensify/App/issues/31681#issuecomment-1825870656

**Comment by chrispader** [comment]
> @grgia fontFamily imports should be left as they are now? `import fontFamily from '@styles/fontFamily';`

As far as i see it, nothing changes for the fonts based on the theme :)

**Comment by chrispader** [comment]
> @grgia @chrispader - similar question for getBankIcon (from BankIcons.ts) - should we also use the styles from the hook? It looks like these styles are not theme-dependent. To use the styles from the hook we would have to pass the styles object to the getBankIcon function (which is used in another util function, so we would have to pass the styles object to it as well). WDYT of this one? Is it worth changing?

Let's pass the `themeStyles` to the hook anyway. Right now, all of the styles are defined in one big theme-dependent `styles` object in `styles.js`. For now, we want to aim for consistency so we only "allow" using styles though `useThemeStyles`.
