### ISSUE TITLE
[$500] IOU - Blue box surrounding the currency after the currency selection

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Click FAB > Request money.
3. Click on the currency.
4. Choose any currency and hit ENTER to select.

## Expected Result:
There will be no blue box surrounding the currency after the selection.

## Actual Result:
There is a blue box surrounding the currency after the selection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1222a7ad-d5ae-449a-af76-ec2174b17719

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4bb2613eb2f6256</li>
        <li>Upwork Job ID: 1727292856284299264</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproducible on production

https://github.com/Expensify/App/assets/115492554/e301cee8-2053-4a01-a60d-ed8b0edee6bd

**Comment by luacmartins** [comment]
@kosmydel can you please add this issue to your list when you work on v3 of https://github.com/Expensify/App/pull/27670?

**Comment by lakchote** [comment]
Waiting for @kosmydel working on the fix. He's currently working on the ideal nav ([link](https://github.com/Expensify/App/pull/27670#issuecomment-1827342787))

**Comment by lakchote** [comment]
Closing this issue as it's no longer happening since the PR was reverted. @kosmydel will create a new PR to address this issue.
