### ISSUE TITLE
[HOLD for payment 2023-12-07] [Theme Switching Migration] Settings

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31694]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] src/components/AddressForm.js
- [ ] src/pages/settings/Wallet/Card/BaseGetPhysicalCard.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardConfirm.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardName.js
- [ ] src/pages/settings/Wallet/Card/GetPhysicalCardPhone.js
- [ ] src/components/AvatarWithImagePicker.js
- [ ] src/pages/ReferralDetailsPage.js

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
A draft PR has been opened.
