### ISSUE TITLE
[HOLD for payment 2023-12-08] [Theme Switching Migration] Composer

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31695]
Part of https://github.com/Expensify/App/issues/31677

As part of the Theme Switching Project, we need to migrate the following:

- [ ] src/components/Composer/index.ios.js
- [ ] src/components/Composer/index.android.js
- [ ] src/components/EmojiPicker/EmojiPickerMenu/index.js
- [ ] src/styles/containerComposeStyles/index.native.ts
- [ ] src/styles/containerComposeStyles/index.ts
- [ ] src/libs/ComposerUtils/updateNumberOfLines/index.native.ts

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by grgia** [comment]
PR in progress
