### ISSUE TITLE
[HOLD for payment 2023-12-14] [$500] Web - Emojis - Flags category is missing on Emoji picker screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to stsaging.new.expensify.com
2. Navigate to any conversation
3. Open emoji picker and check emoji categories

## Expected Result:
Flags category should be ordered in the list of emoji categories

## Actual Result:
Flags category is missing on Emoji picker screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (26)](https://github.com/Expensify/App/assets/93399543/8af82681-b5db-418c-a95d-8615b04b101d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Flags category is missing in EmojiPicker on Windows web

### What is the root cause of that problem?

We intentionally disabled the flags category in [this PR](https://github.com/Expensify/App/pull/15416) since Windows doesn't support them.

### What changes do you think we should make in order to solve the problem?

Now that we have new emoji fonts for Windows, flags are shown as below
![image](https://github.com/Expensify/App/assets/126839717/2fda2500-81e8-4824-bfe8-c0ddcb716ea9)

If this is acceptable, we can update the code
https://github.com/Expensify/App/blob/704f3f7f4d39e0a155b6d29bdbb18a380d726e0a/src/components/EmojiPicker/EmojiPickerMenu/index.js#L76-L79
to
```
        const filteredEmojis = EmojiUtils.mergeEmojisWithFrequentlyUsedEmojis(emojiAssets);
```

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
@aimane-chnaif 

When a iphone user sends a flags emoji to a Windows user, the Windows user is still able to see the flags emoji(as in the screenshot in my proposal).

_A user can receive flags emoji, but can't send flags emoji_. I think this is worth fixing

cc @c3024 @puneetlath

**Comment by puneetlath** [comment]
> Now that we have new emoji fonts for Windows

What do you mean by this @s-alves10?

**Comment by s-alves10** [comment]
I mean we recently introduced a new emoji fonts for Windows
https://github.com/Expensify/App/blob/main/assets/fonts/web/seguiemj.ttf

**Comment by c3024** [comment]
Emoji picker missing the section for flags.

**Comment by shawnborton** [comment]
Got it. I don't feel too strongly, we already have a flag icon in our library as I thought we already had this section in place. So if we do decide to add it, we at least already have the icon for that section. Might need to make the picker wider on desktop though to account for the extra tab item. 

Curious if @puneetlath thinks this is worth fixing or not though.

**Comment by puneetlath** [comment]
I think I'm cool re-adding support for it. It removes some platform specific code and just makes things more consistent, so I say we go for it.

**Comment by s-alves10** [comment]
Pay day here would be 14 Dec. @puneetlath

**Comment by puneetlath** [comment]
Ah thanks. Not sure why the automation didn't work. 

@s-alves10 @c3024 sent you both offers.

**Comment by s-alves10** [comment]
@puneetlath Accepted. Thanks

**Comment by puneetlath** [comment]
All paid.
