### ISSUE TITLE
[Payment Due 2023-12-21][$500] Web – Chat – Tooltip is out if hover the cursor on the mentioned user you have no conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Go to any chat
4. Mention any user you have no conversation yet by typing @ in the composer and selecting from the list.
5. Hover the cursor on the mentioned user.

## Expected Result:
The user detail displayed inside the tooltip.

## Actual Result:
Tooltip is out if hover the cursor on the mentioned user you have no conversation yet.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/91bb2652-7190-4c84-9395-bc311f4dc8ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd8d4190c3d5d7a0</li>
        <li>Upwork Job ID: 1727358226516967424</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27989202</li>
<li>bernhardoj | Contributor | 27989203</li>
</ul></li>
    </ul>
</details>

**Comment by mingybopeep** [comment]
When tagging a non-existent user, the userinfo tool tip fails to render. 

This is caused by the tooltip expecting user details to exist - a hard dependency. 

Solution: When retrieving user data to populate the tooltip, users for whom no user data is returned ought to fall back to placeholder user info. This would solve the issue.

**Comment by laurenreidexpensify** [comment]
@ntdiary just so I follow, are we waiting on @puneetlath's comment on the above before moving ahead? Thanks

**Comment by laurenreidexpensify** [comment]
This has been on prod since 14 Dec https://github.com/Expensify/App/pull/32632#issuecomment-1856053636

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

Contributor; $500 @bernhardoj paid in Upwork
C+ review: $500 @ntdiary paid in Upwork

@ntdiary can you please complete a checklist and confirm if we need a regression test? Thanks
