### ISSUE TITLE
BA - Error message doesn't stop displaying instantly after valid data is entered in date field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31734]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** not able to check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in.
1. Go to Settings > Workspaces > Select Workspace > Bank Account.
2. Go trough the add bank account flow until you reach a page that you have to enter any date, like Company information or Personal Information.
3. Trigger the enter valid data error message on the date field (select the filed but do not select any date and move to another field).
4. Select a valid date.

## Expected Result:
The error message should disappear instantly, like the other fields do.

## Actual Result:
The error message doesn't stop displaying instantly after valid data is entered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/819caa3b-0b96-4b30-b44b-a99df0bb8f78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Looks like this is fixed when reverting https://github.com/Expensify/App/pull/27670

**Comment by luacmartins** [comment]
Removing blocker label since we reverted the offending PR

**Comment by kowczarz** [comment]
I think as soon as https://github.com/Expensify/App/issues/31612 will be fixed, this issue can disappear as well.

**Comment by kosmydel** [comment]
As @kowczarz said, this issue is resolved by [this PR](https://github.com/Expensify/App/issues/31734) and probably was not related to reverting the focus trap.
