### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Compose - Pop up box shows contrast, heading as url and below mailto text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a chat
3. Paste [D@45.comGGgghbbbbbbv:vhjjbbvbbnnn.comhttps://expensify.testrail.io/index.php?/tests/view/4004034](mailto:D@45.comGGgghbbbbbbv:vhjjbbvbbnnn.comhttps://expensify.testrail.io/index.php?/tests/view/4004034)
4. Long press "[D@45.comGGgghbbbbbbv"](mailto:D@45.comGGgghbbbbbbv%22)
part

## Expected Result:
The pop up box must not show contrast message.

## Actual Result:
The pop up box shows contrast message, heading as "copy URL to clipboard" and below "mailto" text when long pressing "[D@45.comGGgghbbbbbbv"](mailto:D@45.comGGgghbbbbbbv%22)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/19f6890c-f7a1-45dc-a12b-9d6c6c35bc47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d7f48875a265e48</li>
        <li>Upwork Job ID: 1727382831137755136</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by sukach318** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pop up box shows contrast, heading as url and below mailto text(https://github.com/Expensify/App/issues/31731#top)

### What is the root cause of that problem?
The string "d@45.comGGgghbbbbbbv" would also be recognized as a valid email address, even though it contains an uppercase "G" in the domain name in using isValidEmailMarkdown function.
### What changes do you think we should make in order to solve the problem?


To address this concern, it might be more appropriate to implement a more sophisticated email validation scheme that considers both the structure and content of the email address.
```
const isValidEmail = (href) => {
  const emailRegex = new RegExp(EMAIL_BASE_REGEX, 'i');
  const [localPart, domain] = href.split('@');

  if (!localPart.match(/^[a-z0-9.+_-]+$/)) {
    return false;
  }

  try {
    dns.lookup(domain, (err) => {
      if (err) {
        return false;
      }
    });
  } catch (err) {
    return false;
  }

  return emailRegex.test(href);
};
```

### **What alternative solutions did you explore? (Optional)**

**Comment by lakchote** [comment]
@bernhardoj's proposal LGTM 👍

**Comment by lakchote** [comment]
@Ollyws could you please complete the BugZero checklist?

**Comment by peterdbarkerUK** [comment]
Offers sent to you both!

**Comment by peterdbarkerUK** [comment]
@bernhardoj $500 Contributor paid, thanks my dude!

**Comment by peterdbarkerUK** [comment]
Paid $500 to @Ollyws 

Looks like we're all done here!
