### ISSUE TITLE
[$500] LHN -Chat preview does not follow the order of texts received when multiple texts are received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. [User A] On iOS app, log in with a HT account and go to LHN
3. [User B] Send messages, from 0 to 10 to User A

## Expected Result:
On User A side, the order of message in the preview should follow from 0 to 10

## Actual Result:
On User A side, the order of message in the preview does not follow from 0 to 10. The order appears randomly, Sometimes, the preview is not the latest message after all the messages are received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c8d45c92-ef46-48cd-8570-a5e9ce42a98e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4ec7faf659698c6</li>
        <li>Upwork Job ID: 1727426440922943488</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by keisyrzk** [comment]
I tried:
- user A present on the conversations list view
- user A present on the conversation with user B view
In both cases I tried:
- sending messages slowly
- sending messages as fast as possible one after another
Tried multiple times above combinations with both dev and staging servers and could not reproduce the issue.

**Comment by anmurali** [comment]
Will work on reproducing this tomorrow.

**Comment by anmurali** [comment]
Yep, I cannot reproduce either.
