### ISSUE TITLE
[Wave 6: Bottom Up] Admin does not get workspace chat created on collect policy

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#31754]
### Problem

In the Bottom up flow, when the admin created the Collect workspace from the IOU report, the workspace chat is not created for them https://github.com/Expensify/App/pull/30582#issuecomment-1823492944

### Why is it important

Every workspace member should have their dedicate workspace chat, even admins

### Solution

Debug this flow and verify where in Backend we are not creating this chat. It might be because the workspace is Collect and in this flow the workspace chat creation is skipped for the admin
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c2edbdbcc1de2e6</li>
        <li>Upwork Job ID: 1727436696398794752</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@laurenreidexpensify Yes I think this still needs to be debugged, but it should be internal. As part of wave6 I assume @greg-schroeder will call it out in next sync but I might take this on once I clear out my other wave tasks later in a week

**Comment by mountiny** [comment]
I believe @greg-schroeder is calling these out in the wave6 room in weekly update for volunteers

**Comment by laurenreidexpensify** [comment]
Still looking for internal volunteer - @greg-schroeder is flagging this in the updates in Slack

**Comment by laurenreidexpensify** [comment]
Bumped in resync - https://expensify.slack.com/archives/CC7NECV4L/p1702488543520599?thread_ts=1702417170.002649&cid=CC7NECV4L

**Comment by amyevans** [comment]
PR up: https://github.com/Expensify/Auth/pull/9461

**Comment by amyevans** [comment]
The PR is now deployed to production
