### ISSUE TITLE
[$500]  Chat - New user on the same private domain is displayed as "Hidden" after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User and the new user are sharing the same private domain (applause.expensifail.com)
1. Launch New Expensify app
2. Tap + > New chat
3. Enter a new user contact and select
4. Send a message to the new user. Note that the email address is shown
5. Log out
6. Log in

## Expected Result:
Since the new user is sharing the same private domain as the sender, the new user will not be displayed as "Hidden" after relogin

## Actual Result:
The new user is displayed as "Hidden" after relogin, and reveals the contact method as display name after opening the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31f3df1d-6dae-4337-8e32-901c47760452

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faec325e171a4fb4</li>
        <li>Upwork Job ID: 1727431753084375040</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by situchan** [comment]
Related to https://github.com/Expensify/App/issues/31746

**Comment by puneetlath** [comment]
This is a back-end thing that we are already working on. Going to close this out.
