### ISSUE TITLE
[HOLD on #31771] [$500] Web -The user is unable to locate the 'Get Physical Card' button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
**Issue found when executing PR** https://github.com/Expensify/App/pull/28453
## Action Performed:
1. Go to staging.new.expensify.com
2. Log in [tester@applause.expensifail.com](mailto:tester@applause.expensifail.com)
3. Go to Settings - Wallet
4. Check for Get Physical Card button

## Expected Result:
The user is able to locate the 'Get Physical Card' button

## Actual Result:
The user is unable to locate the 'Get Physical Card' button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/df59c466-6fcf-45e7-aff9-5dcc54210945

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a24984e3e44fd84d</li>
        <li>Upwork Job ID: 1727438771200491520</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
@ lanitochka17 Can you share the Onyx data of the card? Otherwise, state values would be fine.

**Comment by grgia** [comment]
I think this issue may be linked to another bug where if a user has multiple expensify cards, all card pages link to the same card https://github.com/Expensify/App/issues/31771

**Comment by grgia** [comment]
cc @pac-guerreiro

**Comment by lanitochka17** [comment]
@shubham1206agra The credit card was added via PR https://github.com/Expensify/App/pull/28453

**Comment by garrettmknight** [comment]
Holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/31771

**Comment by garrettmknight** [comment]
Closing since this will get solved by the held issue - it's a near duplicate.
