### ISSUE TITLE
Tag field shows required, but user allowed to create expense without selecting it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, no feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. In old dot, as admin login
2. Tap Workspace---Tags
3. Enable "People must tag expenses"

1. Go to https://staging.new.expensify.com/
as employee
2. Tap on employee Workspace
3. Tap plus near compose
4. Tap Request money----Manual
5. Enter an amount
6. Tap next
7. Tap show more and note "required" mentioned in tag (custom name:shahrukh khan) field
8. Tap request amount
9. Tap the manual expense created to open expense detail page

## Expected Result:
Tag field shows required, so user must not be allowed to create expense without selecting it

## Actual Result:
Tag field shows required, but user is allowed to create expense without selecting it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/90401414-0878-49a6-aadd-fca606f8da7c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
This new feature is WIP and should not be blocker.
cc: @cdanwards

**Comment by luacmartins** [comment]
@situchan do you have a PR?

**Comment by situchan** [comment]
> @situchan do you have a PR?

#31380

**Comment by luacmartins** [comment]
Discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1700687647091809). This is not a blocker and we can close the issue!
