### ISSUE TITLE
Web - User can not navigate to upload photo option while using Tab key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27670
## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Profile
4. Use Tab Key and navigate to default avatar
5. Press Enter Key
6. Use Tab Key to navigate to upload photo option
## Expected Result:
Describe what you think should've happened

## Actual Result:
User can navigate to upload photo option while using Tab key

## Workaround:
User can not navigate to upload photo option while using Tab key

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e948f42-db1f-4585-b456-a33dc9f13d2d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
We reverted the mentioned PR so the test steps no longer apply. Closing this issue.
