### ISSUE TITLE
[MEDIUM] Expensify Cards: All card pages link to the same Expensify Card

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31771]
When a user has Multiple Physical Expensify Cards in their cardList, all menuItems open the first card. This was originally designed with the incorrect assumption that a user would have max 2 cards, a physical and virtual card. 

**Solution**
Let's use the cardIDs of the card we're opening. We may need to discuss displaying "linked" virtual cards as part of this issue or tackle that as a separate issue.

You can see an example of this in this video - 

https://user-images.githubusercontent.com/78819774/285047055-df59c466-6fcf-45e7-aff9-5dcc54210945.mp4

**Comment by grgia** [comment]
@kevinksullivan for this issue I think the root cause is mainly the incorrect card data in the DB (i.e. multiple active cards).  https://github.com/Expensify/App/issues/33515#issuecomment-1875710545

I don't think we can update the query to filter those out, so this might be a case where having an edge case like the current design of showing multiple cards with last four pan in newdot. Sorry for the confusion with this one! 

For now I think we can:
- condense everything into one eCard slot
- if there are multiple active physical or virtual cards, show them all on the card page for now
- work on fixing the DB in the linked issue to clear any cards that are deactivated in marqeta and not in our DB

How does that sound?

**Comment by kevinksullivan** [comment]
Let's hold on doing anyhting here for now and see where we land on the admin side of card management. Convo:

https://expensify.slack.com/archives/C05DWUDHVK7/p1704927942434149?thread_ts=1704920930.824409&cid=C05DWUDHVK7

**Comment by grgia** [comment]
sounds good holding !

**Comment by grgia** [comment]
still holding

**Comment by grgia** [comment]
still on HOLD

**Comment by grgia** [comment]
closing in favor of https://github.com/Expensify/App/issues/38468
