### ISSUE TITLE
[HOLD for payment 2023-12-12] [CRITICAL] Optimize App Start Up Time with Lazy Loading

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#31787]
## Problem
 
App is currently designed to load almost all of its code and resources in an eager manner, regardless of whether or not they are immediately needed. This results in unnecessary overhead and contributes to the slow boot time. 

## Solution

Implement lazy initialization techniques for resources like regular expressions that are not immediately required.

Lazy loading for large JSON files, notably emoji data, optimizes imports across the application.

https://github.com/Expensify/App/pull/31776

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mountiny** [comment]
The regression is being handled

**Comment by mountiny** [comment]
This is ready for payment $500 to @situchan

**Comment by trjExpensify** [comment]
Cool, do we need a checklist?

**Comment by situchan** [comment]
> Cool, do we need a checklist?

I don't think so

**Comment by trjExpensify** [comment]
Sent an offer [here](https://www.upwork.com/en-gb/nx/wm/offer/100057869).

**Comment by trjExpensify** [comment]
Paid!
