### ISSUE TITLE
[$500] IOU-After changing amount, tapping on distance showing "select unique waypoints" error.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on Workspace chat
3. Tap plus icon near compose
4. Tap request money----Distance
5. Enter same start and finish waypoints
6. Enter different add stop and tap next
7. Tap request
8. Tap distance request created to open distance request detail page
9. Tap distance and note no error message is displayed
10. Tap amount and change it and tap save
11. Tap distance and now error message is shown for same waypoints.

## Expected Result:
After changing amount, tapping on distance must not show any error message.

## Actual Result:
After changing amount, tapping on distance showing "please select unique waypoints" error message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3def3680-4a90-4c70-926f-ae959e21065f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e0a7ef860c5a34f</li>
        <li>Upwork Job ID: 1728014911716667392</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This should be fixed in https://github.com/Expensify/App/issues/29895
It's not actually related to updating the amount,but to the incorrect handling of duplicate consecutive waypoints.

**Comment by anmurali** [comment]
Closing based on https://github.com/Expensify/App/issues/31819#issuecomment-1825551677
