### ISSUE TITLE
[$500] IOU - In online split bill, merchant "split bill with (participants)id" turned to "request"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a group chat
3. Tap plus icon---Split bill
4. Enter an amount
5. Tap show more and note "request" is shown under "merchant"
6. Tap split amount
7. Tap split bill created
8. Tap show more and note "request" is shown under "merchant"
9. Navigate to group chat
10. Turn off mobile data
11. Perform step 3-step 7
12. Tap show more and note "split bill with (participants) mail id " is shown under "merchant"section
13. Turn on mobile data
14. Note the merchant section

## Expected Result:
In both offline and online, the merchant section in split bill detail page must show the same message.

## Actual Result:
In offline, under group chat split bill detail page, the merchant section displays "split bill with (participants) mail id " and it is changed to "request" when user turns on mobile data.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f110054a-fd8d-452f-b357-7a2624e40232

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124dadd69db8eb9e9</li>
        <li>Upwork Job ID: 1728036099791814656</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by chamysoftware** [comment]
Could be related to https://github.com/Expensify/App/issues/31781
