### ISSUE TITLE
Expense - Bank account option is absent in Pay with Expensify dropdown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31837]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go to workspace chat > + > Request money.
3. Create a Manual request.
4. Click Pay with Expensify.

## Expected Result:
Bank account option will be present.

## Actual Result:
Bank account option is absent in Pay with Expensify dropdown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b4eaead3-0b51-4f60-a2ee-2f12fddc0081

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Put up a PR with a fix - https://github.com/Expensify/App/pull/31858

**Comment by mountiny** [comment]
fixed 
<img width="1127" alt="image" src="https://github.com/Expensify/App/assets/36083550/128195aa-0414-4d4d-894f-dddde3bb0039">
 we can close this

Thankseveryone ans sorry for the regression, should have tested this case 🙇
