### ISSUE TITLE
Desktop - LHN is not updated on Member side after expense paid

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.4.2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31061

## Action Performed:
1. Create a workspace in admin and invite a member
2. In member account , Global Create > Request Money > $50 > choose the workspace > confirm
3. As a admin navigate to the expenseReport view
4. Click Pay elsewhere green button at the top right of the report
5. Observe the system message added to the expenseReport
6. Login to member account and observe the LHN preview

## Expected Result:
paid action preview (requestor viewer)
"Workspace" paid $50.00
"Admin" : paid $50.00 elsewhere

## Actual Result:
LHN preview is
"Workspace" paid $50.00
Requested $50.00 until clicking on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/29eb7ef4-b7b9-429b-a2e5-bf857a39882e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Likely a regression from https://github.com/Expensify/App/pull/31061. cc @koko57

**Comment by luacmartins** [comment]
We CPed a revert. Closing.
