### ISSUE TITLE
[Wave 6: Drafts] Show the GBR on draft report for submitter only in case of manual submission 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#31849]
## Problem

When draft report is created in NewDot, the person who is supposed to take next action, ie submit the report should have GBR shown on that report in LHN.

However, only in case of policy submission settings such that there is no scheduled submit set up.

## Why is this important?

We should not be calling out the submitter to take action in case the report will get autosubmitted

## Solution

Handle the logic [here](https://github.com/Expensify/Auth/blob/085f5b81dd971b2e0fd664f75b9ef8d995a20015/auth/lib/Transaction.cpp#L1769) in auth to only add the GBR to the submitter if no autosubmission is set up on the policy.

Same goes for optimistic data in the App.

**Comment by puneetlath** [comment]
>Handle the logic [here](https://github.com/Expensify/Auth/blob/085f5b81dd971b2e0fd664f75b9ef8d995a20015/auth/lib/Transaction.cpp#L1769) in auth to only add the GBR to the submitter if no autosubmission is set up on the policy.

Will also need to update this in GetChats.

**Comment by mountiny** [comment]
Discussing with @flodnv if he is interested in working on this one, I have added better description in the doc [here](https://docs.google.com/document/d/1vZtGpW_Fy-Wq_R6gvnjdmWVA86FnR42y3LtnNA--vcY/edit#bookmark=id.xhyhhzq416fy)

**Comment by flodnv** [comment]
Self assigned. I understand the task but can't seem to setup a testing environment: https://expensify.slack.com/archives/C02MW39LT9N/p1701270515881309?thread_ts=1701115094.319939&cid=C02MW39LT9N

**Comment by flodnv** [comment]
I sent a working PR and now I'm spending a lot of time fighting with auth tests, as usual

**Comment by flodnv** [comment]
PR merged, but I still need to write automated tests so I'm keeping this open

**Comment by flodnv** [comment]
Last PR is awaiting a deploy.

**Comment by flodnv** [comment]
Tests are merged, closing.
