### ISSUE TITLE
Workspace - Workspace name misalignment below room name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces > New Workspace > Settings
2. Change the workspace name and save it
3. Now go to the "announce" or "admin" room
4. Click on the room header
5. Notice the workspace name is not centered below the room name

## Expected Result:
The workspace name should be centered, as it is in production

## Actual Result:
The workspace name is not centered below the room name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

Uploading Bug6289372_1700822031565!2023-11-24_15-21-05.mp4…

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/79824fe7-7d1d-417b-984d-a99c5345bda7

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Workspace name misalignment below room name 

### What is the root cause of that problem?
We don't set styles.textAlignCenter in the subtitle of DetailPage
### What changes do you think we should make in order to solve the problem?
Add styles.textAlignCenter to chatRoomSubtitleText

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment]
Regression from https://github.com/Expensify/App/pull/31516
cc: @saranshbalyan-1234

**Comment by mountiny** [comment]
Fixed 
<img width="376" alt="image" src="https://github.com/Expensify/App/assets/36083550/2e1bef9a-6342-48bd-b370-4b4ce9c202c8">
