### ISSUE TITLE
[$500] Thread - Deletion Message Appears for User A After User B Replies to Invite Message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to User A's account
2. Navigate to Settings > Workspace > New workspace
3. Change the workspace name if needed
4. Go to the Members section > Invite
5. Select User B and invite
6. Go to User B’s account in a different browser
7. Go to the expense room of User A’s workspace
8. Hover over the invite message and click “Reply in thread.
9. Send a message in the thread
10. Go back to User A’s account
11. Notice "[Delete message]" is displayed in the LHN

## Expected Result:
"[Delete message]" should not be displayed for the Invite message thread in the LHN

## Actual Result:
When User B replies to the Invite message in the workspace expense room, a deleted message indication is displayed for User A in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/669c02c8-5254-42c7-8cf7-78d1a64d45a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e03f9d397a3fba1</li>
        <li>Upwork Job ID: 1728451127020748800</li>
        <li>Last Price Increase: 2023-11-25</li>
    </ul>
</details>

**Comment by rojiphil** [comment]
Looks like a BE issue as pusher updates for parent Report Action do not contain the entire content. 

![Screenshot 2023-11-25 at 10 25 59 PM](https://github.com/Expensify/App/assets/3004659/4c1ba272-4aa1-47e9-b4c6-d750a1f8de40)
