### ISSUE TITLE
[$500] Web - Detail - Temporary display of disabled mouse when clicking on group users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Start chat
2. Create a group by selecting 2 users
3. Click on the group header > Members
4. Click on any user
5. Notice the disabled mouse is displayed for a while

## Expected Result:
When clicking on a user, the disabled mouse should not be displayed

## Actual Result:
A disabled mouse is displayed for a while when clicking on group users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c5403462-bc88-4e2d-81a7-6317142552c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6cf2dec869b9678</li>
        <li>Upwork Job ID: 1728469209108860928</li>
        <li>Last Price Increase: 2023-11-25</li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
Thanks @ZhenjaHorbach agree this is a dupe. Let's close this out @joekaufmanexpensify :pray:
