### ISSUE TITLE
[HOLD for payment 2024-01-22] Check for the presence of reports that require attention and reports with errors in a given workspace.

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#31878]
Implement a utility function that, given a workspace id, figures out if a workspace has any unread chats or chats with reports.

Find a best, existing file or create one to write this utility function.

[Relevant design doc section](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.1e0gdvo4vyn2)

<details><summary>Issue Owner</summary>Current Issue Owner: @WojtekBoman</details>

**Comment by twisterdotcom** [comment]
Going to ⭐ you @hayata-suenaga.

**Comment by hayata-suenaga** [comment]
wait that's the star ⭐ ?

<img width="200" alt="Screenshot 2023-12-04 at 8 41 37 AM" src="https://github.com/Expensify/App/assets/98560306/54dbd048-f1d5-46b7-9649-18f71506f17c">

**Comment by twisterdotcom** [comment]
Yeah!

**Comment by hayata-suenaga** [comment]
[We are waiting for SWM to decide which engineer to assign to this issue.](https://expensify.slack.com/archives/C036QM0SLJK/p1702406623780179)

**Comment by WojtekBoman** [comment]
@hayata-suenaga You can assign me to this :)

**Comment by hayata-suenaga** [comment]
Copy from [a Slack message](https://expensify.slack.com/archives/C036QM0SLJK/p1702535622302519?thread_ts=1702437733.878949&cid=C036QM0SLJK)

> [@wojciech.boman](https://expensify.slack.com/team/U05V2UTRR09)
 please assume that there is a backend API that returns the list of members of a given workspace while you work on the GH issue. (you need to iterate over reports belonging for a given workspace to figure out if we need to display RBR/GBR. To do this, we first need to get the list of all reports that belong to the given workspace. For reports that has the policyId attribute, this is easy because we can just look at it to figure out if the report belongs to the given workspace (i.e. policy). However, for DM and Group DM reports, we consider a report as belonging to a workspace if at least one of the participants of the report is a member of the given workspace. To figure out this, you need the member list of the workspace. This is the piece of information we lack currently on the front end. That's why we have to create a new backend API to fetch it.

**Comment by aldo-expensify** [comment]
Prepared draft PR with changes https://github.com/Expensify/Web-Expensify/pull/40429

**Comment by hayata-suenaga** [comment]
The PR was merged and deployed to staging. I'll close this issue once the code is deployed to production.

also, I unassigned myself as Aldo worked on the PR

**Comment by mountiny** [comment]
This is completed and merged to the feature branch, great work!
