### ISSUE TITLE
Filter out reports based on the active workspace

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#31877]
Filter out reports based on the active workspace with the following criteria. Display only the filtered reports in LHN.

- Reports that belong to the active workspace
- DMs and GroupDMs from members on the active workspace (there is a caveat on this requirements. See [this part](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.flpsrymnx2iq) and [this part](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.p6azsk4i6lla) of the design doc for detailed requirements)

The list of reports that are displayed on the current LHN (we're changing the design of LHN) are generated in [this part of the code](https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/home/sidebar/SidebarLinksData.js#L90-L95). Filter out reports based on the active workspace.

When the active workspace is Expensify/All, all reports across workspaces should be displayed.

[Relevant design doc section](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.v253hbgx14pm)

<details><summary>Issue Owner</summary>Current Issue Owner: @WojtekBoman</details>

**Comment by hayata-suenaga** [comment]
Yes because this issue is related to Wave 8 Ideal Nav, which is still in detailed design doc phase. We'll probably delegate this task to an expert agency. When it's time to pay for C+ review, I gonna assign a Bug Zero team back to this issue 🙇

**Comment by alexpensify** [comment]
Weekly Update: No update yet.

**Comment by alexpensify** [comment]
Weekly Update: Thank you @hayata-suenaga!

**Comment by WojtekBoman** [comment]
I'm going to work on this task

**Comment by hayata-suenaga** [comment]
Because of the requirement change (instead of storing the active workspace ID, we decided to store the URL of the last visited path), we need some adjustment in term of implementation for this issue.

@WojtekBoman, are you working on this right now?

**Comment by hayata-suenaga** [comment]
The new backend API has been deployed to the staging environment. @WojtekBoman can use the new API to test their PR.

I also commented about the new API in the [PR](https://github.com/Expensify/App/pull/33302).

**Comment by mountiny** [comment]
This is completed and merged to the feature branch, great work!
