### ISSUE TITLE
Add a new Onyx entry for `LAST_VISITED_PATH`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#31886]
We need to keep track of the last visited route/URL to make it possible to navigate back to the place in the app where the user was last active.

To implement this feature, we will store the last visited path/URL as a new entry in Onyx. Please follow this section of the design doc.

You can read the further details on it in [this section of the design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.5q7gqbwlyw70).

**Comment by joekaufmanexpensify** [comment]
Looks like this is an internal new feature, so going to unassign myself for now. If anything related to hiring/paying contributors comes up in the issue, feel free to reassign me, and happy to handle it!

**Comment by hayata-suenaga** [comment]
design doc review still going on

**Comment by mateuuszzzzz** [comment]
Hi, I'll handle this issue 🚀

**Comment by hayata-suenaga** [comment]
@mateuuszzzzz what is the progress for this one?

**Comment by hayata-suenaga** [comment]
@mateuuszzzzz I'd appreciate if you could give an update on this one once you're back at the office

**Comment by hayata-suenaga** [comment]
the work is on progress

**Comment by mountiny** [comment]
this is now kinda the main tracking issue

**Comment by mountiny** [comment]
Actually i think this is better issue to track it https://github.com/Expensify/App/issues/32941

**Comment by dinamoCoder** [comment]
hy Can you add me as a personal developer in this project
