### ISSUE TITLE
[HOLD for payment 2023-12-12] [Theme Switching] Enable theme switching for status and scrollbar colors

### ISSUE THREAD

**Issue by grgia** [Expensify/App#31915]
We need to ensure that the status bar and scrollbar both change when the theme is changed cc @chrispader

**Comment by chrispader** [comment]
comment for assigning :)

**Comment by anmurali** [comment]
Sent offer [here](https://www.upwork.com/nx/wm/offer/28061248)

**Comment by mallenexpensify** [comment]
Contributor+: @fedirjh paid $500 via Upwork.  



Apologies @fedirjh
