### ISSUE TITLE
Ensure that workspace settings pages are displayed correctly on Main Pane

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32067]
In the following screenshots, you can find some of the pages that relate to the workspace settings. These pages are currently displayed on the RHP (Right Hand Panel) when [one of the menu items](https://github.com/Expensify/App/blob/10310d874b5dac972293f2ecb131d67c98ad5cf0/src/pages/workspace/WorkspaceInitialPage.js#L311-L323) on the `WorkspaceInitialPage` is clicked.

<img width="100" alt="Screenshot 2023-11-27 at 11 27 16 AM" src="https://github.com/Expensify/App/assets/98560306/adca2671-24ee-4d60-99f9-1e08a5f65182">
<img width="100" alt="Screenshot 2023-11-27 at 11 28 24 AM" src="https://github.com/Expensify/App/assets/98560306/b3366804-4e7c-4494-b989-cb4732bfe0ce">
<img width="100" alt="Screenshot 2023-11-27 at 11 28 56 AM" src="https://github.com/Expensify/App/assets/98560306/7fa2221e-9a3a-479a-b2dc-866ff4d90418">

You can find the complete list of the pages related to the workspace settings. As part of Ideal Nav project, these pages are displayed inside the Main Pane (the part highlighted in red in the screenshot below). Make sure that they're displayed correctly when the page size increases as the result of being displayed inside the Main Pane.

- [Cards](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L179)
[Reimbursements](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L180)
- [Bills](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L182)
- [Invoice](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L183)
- [Travel](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L184)
- [Members](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L185)
- [Bank account](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L188)
 **Exception: The Bank Account page should be displayed on the RHP instead of the Main Pane. The reasoning for this convo can be found in [this Slack convo](https://expensify.slack.com/archives/C036QM0SLJK/p1702399653355749)**
- For [the Settings page](https://github.com/Expensify/App/blob/bb82910029ff13a4831f9d837207aa37f25f693c/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L177) (which we will rename as `Overview`), add an option (prop) to the `WorkspaceSettingsPage` to make all inputs read only. ([Relevant design doc section](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.euwgduy15dta)).

<img width="400" alt="Screenshot 2023-11-27 at 11 25 40 AM" src="https://github.com/Expensify/App/assets/98560306/e25b7ab1-1e63-4b7f-bfce-165d28a24cbd">

**Comment by hayata-suenaga** [comment]
I'll assign a Bug Zero member if there is payment needed in the future.

**Comment by hayata-suenaga** [comment]
design doc review still going on

**Comment by adamgrzybowski** [comment]
Hey @hayata-suenaga you can assign me

**Comment by hayata-suenaga** [comment]
@adamgrzybowski is working on this as part of the navigation overhaul

**Comment by hayata-suenaga** [comment]
@adamgrzybowski might be OOO. @adamgrzybowski let me know if you're working on this in the internal branch of Software Mansion

**Comment by hayata-suenaga** [comment]
the feature branch is very close to be merged

**Comment by hayata-suenaga** [comment]
The feature branch was merged. We're handing the regressions. Closing this issue
