### ISSUE TITLE
[$125] [Form Provider Refactor] AddressForm

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#32064]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring [src/components/AddressForm.js](https://github.com/Expensify/App/blob/42455cefe10117c74533d75f2ce6b517eb36cfe0/src/components/AddressForm.js)

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9d14f0105c78b4c</li>
        <li>Upwork Job ID: 1729190075497373696</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cdOut</details>

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency and I would like to work on this task.

**Comment by devstar1014** [comment]
Hello, I can finish this work within a short period

**Comment by devstar1014** [comment]
> Dibs

Good.

**Comment by luacmartins** [comment]
@devstar1014 @AnshuAgarwal24 thanks for the interest, but we already assigned someone to this issue. Also, please make sure to get familiar with our [contributing guidelines](https://github.com/Expensify/App/blob/d2a9f810ca6af5fe44fe585745eea2c74acc9bc7/contributingGuides/CONTRIBUTING.md) before posting.

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by zanyrenney** [comment]
@cdOut as the main assignee, please give updates on the GH issue.

**Comment by zanyrenney** [comment]
bump @cdOut

**Comment by cdOut** [comment]
@zanyrenney PR currently waiting for review

**Comment by cdOut** [comment]
This is completed and merged.

**Comment by zanyrenney** [comment]
As SWM contributor, closing as payment not handled here! Thanks.
