### ISSUE TITLE
[$500] All - Split Bill - Employee can successfully access IOU detail page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31291
## Action Performed:
1. Navigate to staging.new.epxpensify.com
2.. Create a workspace
3. Open the #announce room
4. Do a split bill in the room
5. Log in on another device (with the same/different account, if you use a different account, make sure invite it to the workspace)
6. Visit the #announce room

## Expected Result:
The split bill preview should show as a skeleton and a not found page should be shown when enter preview details

## Actual Result:
Employee can successfully access IOU detail page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/067446e3-4342-4b2a-876f-3a0c639d69a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013577bb1c6b9e9765</li>
        <li>Upwork Job ID: 1729293708655165440</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
@lanitochka17 I think based on @bernhardoj's comment, we can close this?
