### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Web - "Bank account" option does not appear in "Wallet"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/issues/32079
## Action Performed:
1. Go to settings > wallet
2. Add bank account

## Expected Result:
Bank account option appears

## Actual Result:
Only debit card option appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6292436_1701124545430!Wallet](https://github.com/Expensify/App/assets/78819774/ca9a808a-7d45-4c16-9620-c1ffbc251a01)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea0db427c9d793c6</li>
        <li>Upwork Job ID: 1729294846848581632</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by jgd8542** [comment]
Is there a reason why this error doesn't occur in dev, but does occur in staging?

**Comment by 007-dot-programmer** [comment]
Contributor details
Your Expensify account email: semenovihor95@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0132b61da48807943c

**Comment by it-education-md** [comment]
I cannot find this bug on dev
![image](https://github.com/Expensify/App/assets/128720033/914c56f4-c963-4d9f-afad-885b2b80c433)

**Comment by it-education-md** [comment]
I cannot find this bug on dev
![image](https://github.com/Expensify/App/assets/128720033/85b27d25-9ef4-40a0-bf94-7e7c233f44cb)

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.

Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

According to below condition, Bussiness Bank Account option is showing only when iouReport is not empty and return true. but if iouReport is empty it will always return false, So only debit option is showing in wallet.
```
const canUseBusinessBankAccount =
        ReportUtils.isExpenseReport(iouReport) ||
        (ReportUtils.isIOUReport(iouReport) && !ReportActionsUtils.hasRequestFromCurrentAccount(lodashGet(iouReport, 'reportID', 0), lodashGet(session, 'accountID', 0)));
```

### What changes do you think we should make in order to solve the problem?

You need to check iouReport is empty or not in below mention file with updated code values.
https://github.com/Expensify/App/blob/main/src/components/AddPaymentMethodMenu.js#L69

```
const canUseBusinessBankAccount =
        _.isEmpty(iouReport) ||
        ReportUtils.isExpenseReport(iouReport) ||
        (ReportUtils.isIOUReport(iouReport) && !ReportActionsUtils.hasRequestFromCurrentAccount(lodashGet(iouReport, 'reportID', 0), lodashGet(session, 'accountID', 0)));
```

### Video

https://github.com/Expensify/App/assets/43398804/4ac8c5bd-fcb2-4557-be8e-f296443ab97e

**Comment by muttmuure** [comment]
Asked about the expected behavior in wave 5: https://expensify.slack.com/archives/C05DWUDHVK7/p1702309201106189

**Comment by muttmuure** [comment]
Clarified the expected behavior and Bank Account should be an option in the list

**Comment by muttmuure** [comment]
@aimane-chnaif could you take a look at the proposals when you get a chance?

**Comment by muttmuure** [comment]
It should be a personal bank account

**Comment by kaushiktd** [comment]
@Gonals @aimane-chnaif 
Adding a new props to the wallet page is not working on my end. 
Could you kindly re-evaluate my proposal? I solved the issue without adding props. It will show Business bank account option.

**Comment by Gonals** [comment]
Making this external again, as we have proposals already. Taking a look at them

**Comment by Gonals** [comment]
I think I'm with @tienifr on this one. He proposed a valid fix, pending verification on whether it should be personal or business, but effectively the same, so I think we should go with their proposal, as it was there earlier.

**Comment by Gonals** [comment]
@muttmuure Seems like we had some errors assigning the jobs ⬆️

**Comment by muttmuure** [comment]
@aimane-chnaif - $500
@tienifr - $500

**Comment by muttmuure** [comment]
Created a payment issue

**Comment by muttmuure** [comment]
So sorry @tienifr! I must have not completed the full payment steps or hit an error. I have sent you a new offer

**Comment by muttmuure** [comment]
Sorry, not sure what happened there. Anyway, everyone has been paid.
