### ISSUE TITLE
[HOLD for payment 2023-12-07] [HOLD for payment 2023-12-06]  IOU - Clicking on card and amount does not cause any action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on 1:1 report
3. Tap plus icon near compose
4. Tap request money
5. Enter an amount
6. Tap next
7. Tap show more and note "card" option is not displayed
8. Tap request
9. Tap on manual request created to open iou detail page
10. Tap card option

## Expected Result:
Tapping on card must trigger an action or card option should not be displayed

## Actual Result:
In manual request IOU detail page, tapping on "card" does not trigger any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a01c1edc-3acb-40a9-8608-bdd70033d1aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by marcaaron** [comment]
>Tap show more and note "card" option is not displayed

Was this a new feature? What is the "card" option?

**Comment by marcaaron** [comment]
>Tapping on card must trigger an action or card option should not be displayed

also, what is "action"?

**Comment by marcaaron** [comment]
Ohhh you are saying that this should not be here? Got it. 

![2023-11-27_14-08-55](https://github.com/Expensify/App/assets/32969087/bd47c587-c5b3-4c5a-99e3-f6f54c0776e0)

I'd probably phrase this like: 

>"Card" option row appears in request detail for regular non-Card expense

**Comment by marcaaron** [comment]
cc @luacmartins I think probably we want to check if the card is "cash" in Auth at some point

We can revert @grgia's PR [here](https://github.com/Expensify/App/pull/31353) for now to fix the blocker.

Unless there are any other ideas?

**Comment by luacmartins** [comment]
This is a new feature, so I think it'd be ok to demote that to NAB since it doesn't really break any functionality (the option just shouldn't be there) and we can work on an Auth PR to filter those cards out. What do you think?

**Comment by marcaaron** [comment]
It's a core flow so I'll raise a PR to hide the row for everyone temporarily. My preference would be to not willfully ship broken code.

**Comment by grgia** [comment]
I think we can use this method instead - https://github.com/Expensify/App/pull/32097 we can just check the cardID exists in the cardList.

**Comment by luacmartins** [comment]
Removing blocker label since we CPed a fix and it tests well in staging.

**Comment by marcaaron** [comment]
Nice! Great solution @grgia. I doubt we would ever return the "cash cards" in that list for any reason (🤞 😂 )

**Comment by alitoshmatov** [comment]
Looks like this is ready for payment

**Comment by grgia** [comment]
@anmurali could you help with $500 C+ review payment to @alitoshmatov

**Comment by grgia** [comment]
@anmurali this one's ready for payment- let me know if you need anything else from me!

**Comment by grgia** [comment]
bump @anmurali

**Comment by anmurali** [comment]
Offer is https://www.upwork.com/nx/wm/offer/100368742
Pls let me know if the amount is right.

**Comment by alitoshmatov** [comment]
Can't access upwork job

**Comment by anmurali** [comment]
Try - https://www.upwork.com/nx/wm/offer/100382852

**Comment by anmurali** [comment]
Paid!
