### ISSUE TITLE
Request money - Unable to edit money request from IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31772

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Request money from any user
4. After finishing the request, tap on the IOU
5. Attempt to edit the Request from the IOU

## Expected Result:
User should be able to edit the amount from the IOU

## Actual Result:
The user can’t edit the IOU, the chevron appears for one second then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/83e1e030-f920-4772-882a-10a7e67bed7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
It is intentional as [this comment](https://github.com/Expensify/App/issues/28836#issuecomment-1762213693)

**Comment by grgia** [comment]
closing as dupe

**Comment by MonilBhavsar** [comment]
@grgia could you please link a PR that fixes this issue.

**Comment by MonilBhavsar** [comment]
Thanks! Issue is fixed by that PR 👍
