### ISSUE TITLE
 Wallet - SSN field is not filled after user hits back button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:**  1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** cannot check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31401

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with an expensifail account.
3. Go to Settings > Wallet > Enable Wallet.
4. Follow the flow until you reach Additional details page.
5. Fill the form with following data: First name: Alberta, Last name: Bobbeth, SSN: 3333, Any other information for the rest of the fields.
6. Tap "Save & continue".
7. Tap on the back button.
8 Scroll down.

## Expected Result:
SSN field should be filled with the information previously entered.

## Actual Result:
SSN field is empty.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/540cb8f3-a1a9-497e-b2bc-07eda77f457b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment]
It looks like this is happening because we don't have the `shouldSaveDraft` enabled on the ssn input field.

**Comment by techievivek** [comment]
This doesn't need to be a blocker, and it looks like this could also be happening on the PROD. Also, the issue seems to have existed for quite some time now.

**Comment by techievivek** [comment]
Interesting, thanks for the context. Closing it.
