### ISSUE TITLE
Web - Wallet - Cannot proceed with add bank account flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31050

## Action Performed:
1. Go to staging.new.expensify.com
2. Create new account.
3. Navigate to https://staging.new.expensify.com/send/new/enable-payments
4. Fill the form with following data: First name: Alberta, Last name: Bobbeth, SSN: 3333, Any other information for the rest of the fields.
5. Tap on "Save & continue".s

## Expected Result:
The user should be able to proceed with the testing credentials.

## Actual Result:
An error appears and the user is not able to proceed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0d9b7234-0a6c-4e3c-8760-f4bab75877a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I think the wrong details are being used? We need to try with:

**First name:** Alberta
**Last name:** Charleson

Tested on `main` and it works fine. I will try on staging just to be sure...

**Comment by marcaaron** [comment]
Works on staging as well. Going to close/remove the blocker as I think this is just a mistake on the tester's part.


https://github.com/Expensify/App/assets/32969087/746b1480-5739-4615-b30c-945a356fcb67
