### ISSUE TITLE
[HOLD for payment 2023-12-07] [HOLD for payment 2023-12-06] Wallet - On first try, SSN is verified after second attempt to submit the form

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31401

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with an expensifail account.
3. Go to Settings > Wallet > Enable Wallet.
4. Follow the flow until your reach the "Additional details" page.
5. Fill the form with following data: First name: Alberta, Last name: Bobbeth, SSN: 3333, Any other information for the rest of the fields.
6. Tap on "Save & continue".

## Expected Result:
The user should be taken to the nest step without any issues.

## Actual Result:
An error message appears the first time the user hits the "Save & continue" button. If the user taps on it again without any change on the fields, then the SSN is verified.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dbd0c478-d1ce-4e92-8804-ae064ee9b3be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
We CPed a revert. Closing.

**Comment by s77rt** [comment]
This does not seem to be a regression from https://github.com/Expensify/App/pull/31401. It just happen that it was found during its QA

**Comment by mountiny** [comment]
@luacmartins Apparently this failed on the latest staging https://github.com/Expensify/App/issues/32266#issuecomment-1834427850 maybe there is some misunderstanding with expected resutlts, but I am reopning just so we can check if this is fine.

Feel free to close again if all if expected

**Comment by luacmartins** [comment]
This is expected. Closing!
