### ISSUE TITLE
[HOLD for payment 2023-12-12] [$250] Remove the DatePicker component and rename the NewDatePicker component to it

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32099]
We are not using the DatePicker component anywhere anymore and we have substituted all its usecases with the NewDatePicker component.

Lets clear this up and remove the DatePicker component in one PR and then in second PR lets rename the existing NewDatePicker component to DatePicker component.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178ce9af230e7f619</li>
        <li>Upwork Job ID: 1729456904406032384</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1701168151042009 @shubham1206agra will handle this

**Comment by mountiny** [comment]
Closed these migrations https://github.com/Expensify/App/issues/25343
https://github.com/Expensify/App/issues/25140

**Comment by shubham1206agra** [comment]
This is not open for proposal, just putting here.

**Comment by shubham1206agra** [comment]
@ishpaul777 I don't think it's needed.
But let me finish the first part. Then, we will decide.

**Comment by Shaharyar-saleem** [comment]
Hi,
I can resolve the issue therefore I am submitting my bid in the upwork.

**Comment by greg-schroeder** [comment]
Offert sent @shubham1206agra

**Comment by shubham1206agra** [comment]
Accepted
