### ISSUE TITLE
[HOLD for payment 2024-01-18] [HIGH] Clean up Hoverable component

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32096]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1700572497547219)

### Problem
Hoverable definition contains mixed logic of a few states (disabled , scrolling, hasHoverSupport), which makes it harder to understand and maintain.

### Solution
Here is a list of issues with potential improvements that could help with that:
1. Logic responsible for internal updates is interleaved with logic responsible for disabled and hoveredEnabled states of the component. This may lead to hard-to-spot bugs.
    - Split the component into two distinct paths, InactiveHoverable and ActiveHoverable (see linked PR). This way we don't care about handling the disabled logic inside actual Hoverable
2. Component children definition is not strict enough causing complicated logic for child retrieval
    - Component should only accept single ReactElement child or callback that returns such single child - if more than one element is needed to have a hovered mechanism, then wrap them into a mutual parent
3. Component subscribes to unnecessary events, such as onBlur - if Hoverable should be responsible for focus effects as well, it should be taken into account explicitly
    - Let’s discuss if we could safely remove the subscription to onBlur
4. There are two pairs of callbacks onHover* and onMouse* which distinction and role are not clearly visible (they are not the same but I am not sure if we need the distinction, e.g. onMouse* event can be taken directly from children passed to Hoverable)
    - Discuss if we could simplify it, so only one pair is needed (see linked PR)
5. There are a lot of Hoverable components on the page (lists’ items etc.) and each of them subscribes to scrolling event
    - Is there an alternative way for what we currently have?

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by mountiny** [comment]
cc @kacper-mikolajczak can you please comment here

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny , I would like to work on this issue

**Comment by mountiny** [comment]
PR is in a review

**Comment by cubuspl42** [comment]
> * Logic responsible for internal updates is interleaved with logic responsible for disabled and hoveredEnabled states of the component. This may lead to hard-to-spot bugs.
>   
>   * Split the component into two distinct paths, InactiveHoverable and ActiveHoverable (see linked PR). This way we don't care about handling the disabled logic inside actual Hoverable

✅

> * Component children definition is not strict enough causing complicated logic for child retrieval

@kacper-mikolajczak Would you say a word or two about how this requirement was met?

>   * Component should only accept single ReactElement child or callback that returns such single child - if more than one element is needed to have a hovered mechanism, then wrap them into a mutual parent

✅

> * Component subscribes to unnecessary events, such as onBlur - if Hoverable should be responsible for focus effects as well, it should be taken into account explicitly
>   * Let’s discuss if we could safely remove the subscription to onBlur

@kacper-mikolajczak Analogically

> * There are two pairs of callbacks onHover* and onMouse* which distinction and role are not clearly visible (they are not the same but I am not sure if we need the distinction, e.g. onMouse* event can be taken directly from children passed to Hoverable)
>   
>   * Discuss if we could simplify it, so only one pair is needed (see linked PR)

@kacper-mikolajczak Analogically

> * There are a lot of Hoverable components on the page (lists’ items etc.) and each of them subscribes to scrolling event
>   
>   * Is there an alternative way for what we currently have?

@kacper-mikolajczak Analogically

**Comment by kacper-mikolajczak** [comment]
> Component children definition is not strict enough causing complicated logic for child retrieval
> @kacper-mikolajczak Would you say a word or two about how this requirement was met?

The requirement has been already met after refactoring the component to TS. In this PR we simply removed unnecessary `mapChildren` function which indicated that the component can receive multiple children. Also, the TS typings for child was corrected.

> Analogically. Could we safely remove the subscription to onBlur?
[After the discussion](https://callstack-hq.slack.com/archives/C05LX9D6E07/p1700596090511109?thread_ts=1700572497.547219&cid=C05LX9D6E07), we decided not to remove the `onBlur` handler as it might revive old issues.

> Analogically. Is there an alternative way for what we currently have?
Unfortunately, no findings on this one.

Let me know if that answered your concerns 👍

**Comment by cubuspl42** [comment]
Great, thanks!

**Comment by cubuspl42** [comment]
The PR was reverted, we'll need to regroup 🙁

**Comment by kacper-mikolajczak** [comment]
Hi @cubuspl42, definitely! I am going to work on the solution as soon as I am done with current stuff 👍

**Comment by cubuspl42** [comment]
> * 💡 keep the solution suggested in this PR and refactor all the components so we always have single child passed into `Hoverable`. That way user knows what element `Hoverable` hooks into. On the flip side, we would not need to make any workarounds but it would require deep understanding of current behaviour and testing against regression.

Sounds clean, but I'm aware of the risk. How many uses are we talking about?

**Comment by kacper-mikolajczak** [comment]
Thanks a lot for the insight @bernhardoj! 👍 

In this case, if we want to keep the single child approach but also have possibility to provide single child wrapped in the array (e.g. `OfflineWithFeedback` example), then we would need to add a mapper for that. 

I've added this functionality here: 76a200fa020e162fa6cb9da8acd0cfe6e2dd8fe4, but it was not enough to solve the issue.

While debugging, I came to the point where I tracked down what is causing that and it seems that the problem lies in this change: 87d8979687fd19a16eb685a342231ca60a006728. After I reverted the changes to `BaseTooltip` (it did clone the React element to pass the mouse event handler), it looked okay.

Question is, if we want to go back to previous approach, where we can pass `onMouse*` events through `Hoverable` props (thus avoiding cloning there) or shall we find different approach.

I am open to suggestions ^^

**Comment by cubuspl42** [comment]
I'm not sure. I liked the idea with ensuring a single child is passed to `Hoverable`.

**Comment by kacper-mikolajczak** [comment]
I've had a second more on this and it turned out that what was crashing the app is `React.cloneElement` inside `BaseTooltip` to acquire array as a children which resulted in an error. 

I've posted the fix that we can use [here ](https://github.com/Expensify/App/pull/32636/files). 

It basically parse children in order to extract single child. Let me know what you guys think @cubuspl42 @bernhardoj

**Comment by cubuspl42** [comment]
I left a comment in that PR and stand by [what I said earlier](https://github.com/Expensify/App/issues/32096#issuecomment-1845068586).

**Comment by mountiny** [comment]
Kacper is out of office but pr review continues

**Comment by mountiny** [comment]
@kacper-mikolajczak has been out the PR is moving along though, whats your ETA?

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny, I am going to complete the PR today and hand it off to the reviewer 👍

**Comment by mountiny** [comment]
@roryabraham Assigning you here too since you have helped a lot with the issue and reviews

**Comment by mountiny** [comment]
@500 to @cubuspl42 I believe

**Comment by MitchExpensify** [comment]
Automation didn't seem to create an Upwork offer - Created one here for you @cubuspl42 : https://www.upwork.com/nx/wm/offer/100533857

**Comment by cubuspl42** [comment]
Accepted 👍

**Comment by MitchExpensify** [comment]
Paid and contract ended, thanks @cubuspl42
