### ISSUE TITLE
[$500] Chat – The emoji is not added to Frequently Used when react the message.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to a conversation that already has some messages.
4. Hover over any message
5. Verify there's a button to select an emoji to react the message
6. Click on the button
7. Verify the emoji picker opens
8. Select any emoji from the list
9. Hover over any message one more time.
10. Click on the button to select an emoji to react the message one more time.

## Expected Result:
The emoji is added to Frequently Used when react the message

## Actual Result:
The emoji is not added to Frequently Used when react the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/eb903738-0dc6-4ed1-9e7d-c9ece37ad5e8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b94505876eacdb3</li>
        <li>Upwork Job ID: 1729457945037398016</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Related - https://github.com/Expensify/App/issues/31802

**Comment by allroundexperts** [comment]
Seem to be related but not exactly the same. In the linked ticket, we're talking about the emoji picker in the status selector in user profile settings. I like the idea of moving this logic to the emoji picker itself by @DylanDylann [here](https://github.com/Expensify/App/issues/31802#issuecomment-1825061164). Let's see what @0xmiroslav decides.

**Comment by strepanier03** [comment]
Sounds good, I'll check that GH Monday to see if a decision has been made.

**Comment by strepanier03** [comment]
Nothing yet, I'll check again tomorrow.

**Comment by strepanier03** [comment]
Still paused for an update on https://github.com/Expensify/App/issues/31802#issuecomment-1825061164

**Comment by strepanier03** [comment]
Sorry for the hold-up, I've been OoO. 

I reviewed the comment linked and reviewed against our waves and agree this can be closed for focus as it's not a required part of any waves.
