### ISSUE TITLE
Split bill - Does nothing when clicking on "Split bill preview"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32122]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** no (crash on production)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31291

## Action Performed:
1. Create a workspace if you don't have one
2. Open the #announce room
3. Do a split bill in the room
4. Log in on another device (with the same/different account, if you use a different account, make sure invite it to the workspace)
5. Visit the #announce room
6. The split bill preview should show as a skeleton
7. Press the preview

## Expected Result:
Verify a not found page is shown and that no crash happens.

## Actual Result:
Does nothing when clicking on "Split bill preview"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/41e60e65-81f2-4e9e-a7b2-eeba26f1cd21

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Seems [expected](https://github.com/Expensify/App/pull/31291#issuecomment-1818793459) but there should have been UX discussion with design team

**Comment by iwiznia** [comment]
Ah ok, so not a blocker and expected it seems. I am not sure what other thing we could do to improve UX... tagging @Expensify/design to get their opinions.

**Comment by shawnborton** [comment]
Hmm but the mouse is just a standard mouse cursor and not a pointer cursor, so from a visual feedback perspective, the user would know there is nothing to click on right?

**Comment by iwiznia** [comment]
Yep, that's right. So close it?

**Comment by shawnborton** [comment]
That's my vote, yup.
