### ISSUE TITLE
[HOLD for payment 2023-12-18] Rename primitive level colors in App

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32131]
define the primitive colors as 100-800 so that it's a little cleaner to map them to theme colors

![image](https://github.com/Expensify/App/assets/38015950/2c4cd255-f674-4384-8e38-50ac6f17b4a2)

**Comment by grgia** [comment]
cc @shawnborton

**Comment by shawnborton** [comment]
I like doing something like `productDark100` or `productLight800` or something to that effect? cc @Expensify/design for thoughts too

Basically we use the names of colors for the other color columns... like green100, blue100, etc. So for product colors, I think it makes sense to call them productLight or productDark. In the future, maybe we have productLightHighContrast and productDarkHighContrast or even productDarkOrange if we had an all orange theme

**Comment by grgia** [comment]
```
    // Dark Mode Theme Colors
    productDark100: '#061B09',
    productDark200: '#072419',
    productDark300: '#0A2E25',
    productDark400: '#1A3D32',
    productDark500: '#2C6755',
    productDark600: '#8B9C8F',
    productDark700: '#AFBBB0',
    productDark800: '#E7ECE9',

    // Light Mode Theme Colors
    productLight100: '#FCFBF9',
    productLight200: '#F8F4F0',
    productLight300: '#F2EDE8',
    productLight400: '#E5E1DB',
    productLight500: '#D7D1C8',
    productLight600: '#A3A9A3',
    productLight700: '#78837E',
    productLight800: '#0B2D23',
    ```

**Comment by grgia** [comment]
@conorpendergrast could you help with $500 C+ review payment to @sobitneupane

**Comment by grgia** [comment]
Actually this PR fixed multiple issues. we can handle payment in https://github.com/Expensify/App/issues/28817. Please disregard @conorpendergrast !
