### ISSUE TITLE
Handle notification

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32144]
Implement a logic that handles notification according to the following two new requirements (part of Wave 8 Ideal Nav).

1. When a notification is clicked/tapped, make sure that the currently-selected bottom tab item is "Chats".
2. If the notification is about a report that doesn't belong to the currently-active workspace, the active workspace should change to the Expensify/All (which displays all reports across workspaces in addition to off-workspace reports that doesn't belong to any workspace).

Relevant section of [the design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit?pli=1#bookmark=id.w8ps72d36ytu).

**Comment by hayata-suenaga** [comment]
I gonna reassigned a Bug Zero member when it's time for C+ review payment.

**Comment by hayata-suenaga** [comment]
design doc review still going on

**Comment by adamgrzybowski** [comment]
@hayata-suenaga Is it still in review?

**Comment by adamgrzybowski** [comment]
You can assign me here anyway

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga Is it still in review?

Nop it's ready to be worked on. Let me know if you have any questions 👍

**Comment by hayata-suenaga** [comment]
forgot to assign you here @adamgrzybowski sorry about that

**Comment by hayata-suenaga** [comment]
@adamgrzybowski is working on this as part of the navigation overhaul

**Comment by hayata-suenaga** [comment]
@adamgrzybowski let me know if you're working on this in the Software Mansions'  internal branch

**Comment by hayata-suenaga** [comment]
[Asked on slack if SWM is working on this](https://expensify.slack.com/archives/C036QM0SLJK/p1705515505428899). Nevertheless, this will come later as the navigation structure is built.

**Comment by hayata-suenaga** [comment]
@mateuuszzzzz could you confirm that we're handling notification outside [the feature branch](https://github.com/Expensify/App/pull/33280) or does the feature branch already contains code to handle notifications?

**Comment by hayata-suenaga** [comment]
tested and it works 🎉 
https://github.com/Expensify/App/assets/98560306/5e5da165-b15e-4524-94f8-6a8beaa7c69b
