### ISSUE TITLE
[HOLD for payment 2023-12-20] [$250][Cleanup] Always use constants for screen names

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#32141]
Coming from https://github.com/Expensify/App/pull/31543#discussion_r1405425034...

### Problem
We have two patterns for adding screens in E/App, and we aren't consistent about when a constant should be used for a screen name in `SCREENS.ts` or not. This leads to unnecessary confusion and inconsistency. The developer has to decide which pattern to follow, and if a constant needs to be added must adjust the navigation stack accordingly in a PR that does not add a new screen.

### Solution
Let's clean this up to always use constants for screen names in E/App (from `SCREENS.ts`).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe00e0d9ee39b022</li>
        <li>Upwork Job ID: 1729552664025485312</li>
        <li>Last Price Increase: 2023-11-28</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27871796</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
Marking this as external but not help wanted as @blazejkustra is going to work on this.

**Comment by roryabraham** [comment]
Adjusting the C+ review payment for this from $500 to $250

**Comment by blazejkustra** [comment]
Hey! I’m Blazej from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
@cubuspl42 @roryabraham PR is ready for review, I didn't post a proposal as this was pretty straight forward change.

**Comment by cubuspl42** [comment]
@puneetlath Do we need to assign someone to process the payment?

**Comment by puneetlath** [comment]
Whoops, I got it. All paid!
