### ISSUE TITLE
[$250] [Cleanup] Utility URL type for getURLWithBackParam, etc...

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#32143]
Coming from https://github.com/Expensify/App/pull/31543#discussion_r1405420130...

### Problem
We've got some types that look like this:

```ts
function getUrlWithBackToParam<TUrl extends string>(url: TUrl, backTo?: string): `${TUrl}` | `${TUrl}?backTo=${string}` | `${TUrl}&backTo=${string}` {
    ...
}
```

and while that works it's a pretty verbose way to express a pretty common format for something.

### Solution
This is a rich representation of what this string could / should look like, instead of just being `string`, but let's clean this up to make it more extensible/reusable. We should make a utility type for URLs that takes:

- A base URL
- an object type representing a series of optional or required query params (which of course can be in any order)

Then the resultant type would be any string matching the pattern of a valid URL with the correct base and query params.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab405b1ad68ca814</li>
        <li>Upwork Job ID: 1729557018701299712</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
Removing `Help Wanted` as @blazejkustra is going to work on this

**Comment by blazejkustra** [comment]
Hey! I’m Blazej from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by hamzasaleem2** [comment]
Contributor details
Your Expensify account email: hamzasaleembusiness@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/hamzasaleem

**Comment by hamzasaleem2** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Making URLs in code is complex and hard to read with the current getUrlWithBackToParam function.
> 
> ### What is the root cause of that problem?
> The existing function is too detailed and prone to mistakes.
> 
> ### What changes do you think we should make in order to solve the problem?
> Introduce a new tool, UrlWithParams, and a simpler function, getUrlWithParams, for easier and clearer URL construction.
> 
> Will just need to add a `stringify` function with object entries to be mapped together.
> 
> only this piece of code will be replaced with two functions.
> 
> ```
> function getUrlWithBackToParam(url: string, backTo?: string): string {
>     const backToParam = backTo ? `${url.includes("?") ? "&" : "?"}backTo=${encodeURIComponent(backTo)}` : '';
>     return url + backToParam;
> }
> ```

just in case, this wasn't notified as last message.

**Comment by blazejkustra** [comment]
@hamzasaleem2 I'll work on this, as Rory mentioned [here](https://github.com/Expensify/App/issues/32143#issuecomment-1830376846). Just need a little more time as I have some other priorities atm.

**Comment by roryabraham** [comment]
Not accepting other proposals as this issue was deferred feedback from a PR review

**Comment by blazejkustra** [comment]
Not overdue, taking a look today 😄

**Comment by fabioh8010** [comment]
@blazejkustra I think your solution is enough for our use cases, I don't see too much value in being super explicit about the query params in the string type, just `${TUrl}?${string}` seems to be sufficient.

**Comment by roryabraham** [comment]
I personally think that it would be more valuable to be explicit about which URL params, specifically, are expected/allowed for a specific route, and what specifically their type should be.

@blazejkustra The first code snippet you showed looked best to me, though I wonder if there's a way to DRY it up / generalize it a bit rather than having to manually list out all possible arrangements when we have potentially `N` query params.

**Comment by blazejkustra** [comment]
> I personally think that it would be more valuable to be explicit about which URL params

@roryabraham Maybe I'm missing something, what would be the benefit of such strictness? 🤔 

> it would be more valuable to be explicit about which URL params specifically, are expected/allowed for a specific route, and what specifically their type should be.

Isn't this already ensured in each `getRoute` function? 

```ts
    EXAMPLE: 'example', // no query params for example route
    DETAILS: {
        route: 'details',
        getRoute: (login: string) => getUrlWithQueryParams('details', {login}),
    }, // details route requires a login query param
    PROFILE: {
        route: 'a/:accountID',
        getRoute: (accountID: string | number, backTo?: string) => getUrlWithQueryParams(`a/${accountID}`, {backTo}),
    }, // profile route has an optional backTo query param
```

> The first code snippet you showed looked best to me, though I wonder if there's a way to DRY it up / generalize it a bit rather than having to manually list out all possible arrangements when we have potentially N query params.

Listing all the possible combinations of query parameters in a template-literal string won't be done manually by listing all possibilities. I just wanted to show what would be the resulting type. I didn't code it as it's not trivial 😅

**Comment by roryabraham** [comment]
> what would be the benefit of such strictness?

My thinking is that you'd be unable to pass unexpected params or miss required params when navigating to a screen. But it sounds like I'm alone in thinking this would bring any additional value, so I'll trust you guys and close this out.
