### ISSUE TITLE
Standardize `themeStyles` to `styles` in App

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32169]
We are using two different names, let's only use one
cc @chrispader

**Comment by grgia** [comment]
@chrispader maybe we combine this change with these?
https://github.com/Expensify/App/issues/29911
https://github.com/Expensify/App/issues/29910

**Comment by chrispader** [comment]
> @chrispader maybe we combine this change with these? #29911 #29910

yes 👍

**Comment by chrispader** [comment]
@grgia can we merge this one? :)

**Comment by grgia** [comment]
closing!
