### ISSUE TITLE
[HOLD for payment 2023-12-08] [Drafts] Allow draft creation in App

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32174]
### Problem

The App code currently only creates processing reports, lets update the code so that if the policy is paid, we create expense report in OPEN state, which is also name drafts

Additionally now the NextSteps are only showing for draft reports, lets update it so they show for any expense reports on Paid policies

### Solution

Implement the necessary changes

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mountiny** [comment]
@sonialiap $500 to @akinwale for their testing and review on the PR

**Comment by akinwale** [comment]
> @akinwale $500 offer has been sent Please confirm if we should create a regression test for this

Accepted. Thanks!

This is a new feature, so no regression test required here.

**Comment by situchan** [comment]
We started creating regression test for new features 3 months ago
https://expensify.slack.com/archives/C02NK2DQWUX/p1694591231219059

**Comment by mountiny** [comment]
We should be creating new issues but for the drafts project, we will handle it in a separate issue

@sonialiap feel free to close once ready

**Comment by sonialiap** [comment]
Payment completed ✔️
