### ISSUE TITLE
[HOLD for payment 2023-12-08] [HOLD for payment 2023-12-07] Workspace - Workspace in the workspace list is misaligned when deleted offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to Settings > Workspaces > Create a new workspace.
4. Click on the three-dot menu > Delete workspace > Delete.

## Expected Result:
The deleted workspace in the workspace list will not be misaligned.

## Actual Result:
The deleted workspace in the workspace list is misaligned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6d16d6b2-43c7-4557-b99c-023ba46e6b61

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ZhenjaHorbach** [comment]
Problem related with this PR

https://github.com/Expensify/App/pull/31728

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue, because I am author of the broken [PR](https://github.com/Expensify/App/pull/31728).

**Comment by situchan** [comment]
Commented with root cause and solution on offending [PR](https://github.com/Expensify/App/pull/31728)

**Comment by rezkiy37** [comment]
I am preparing a [PR](https://github.com/Expensify/App/pull/32185), will open it soon.

**Comment by situchan** [comment]
Happy to review PR if @puneetlath agrees

**Comment by rezkiy37** [comment]
I've opened the PR for review.
