### ISSUE TITLE
[HOLD for payment 2023-12-18] Finalize Light Mode Theme

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32188]
Let's find everything that's broken with light mode and track it here so we can finalize the light theme

**Comment by grgia** [comment]
<img width="602" alt="image" src="https://github.com/Expensify/App/assets/38015950/23fdfa11-38a7-4e2e-80a8-2289be1ecb82">

**Comment by grgia** [comment]
**Chat Row Hover**
<img width="626" alt="image" src="https://github.com/Expensify/App/assets/38015950/16a274f3-c4e2-4129-8a50-1b4c4e033b21">

**Comment by grgia** [comment]
**emoji reactions / overlay**

<img width="599" alt="image" src="https://github.com/Expensify/App/assets/38015950/34a54a64-3d20-4eb8-a9ee-85f93b531141">

**Comment by grgia** [comment]
**header banner text**

![Image](https://github.com/Expensify/App/assets/38015950/3dd041ed-ba55-4ac8-a3e0-c0613e0f229c)

**Comment by grgia** [comment]
**Font colors for description??**
![Image](https://github.com/Expensify/App/assets/38015950/5bb852f6-8169-4ffe-8ed8-929a834a5333)

**Comment by grgia** [comment]
**concierge message**

![Image](https://github.com/Expensify/App/assets/38015950/f5492a2e-4d60-4b2a-8eca-f4c9bdfce701)

**Comment by grgia** [comment]
We need to replace themeColor default theme import for these files:

- [ ] https://github.com/Expensify/App/blob/9c095833c924e564b6488a693c7eddd87e32f0b1/src/components/Icon/index.tsx#L5
- [ ] https://github.com/Expensify/App/blob/3b02565ea9df14b93ca3c1f2ce3de2ef4c8f4c1d/src/styles/getTooltipStyles.ts
- [ ] https://github.com/Expensify/App/blob/68233f4b7b7e2fae3f8031c0e3727e5f7c63ae94/src/components/MapView/MapView.web.tsx#L13
- [ ] https://github.com/Expensify/App/blob/1080ca04fb28754b8f115a996943b37259bfa9d7/src/components/ShowMoreButton/index.js#L11
- [ ] https://github.com/Expensify/App/blob/86767e1eda45e738c0335cbcaa1e3060d1ece82a/src/pages/home/report/ReportActionItem.js#L50
- [ ] https://github.com/Expensify/App/blob/1d44d68e0d66ac69a032d119f2ca70ccf48e60f9/src/pages/home/report/ReportActionItemSingle.js#L24
- [ ] https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/stories/Composer.stories.js#L10
- [ ] https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/styles/getModalStyles.ts#L6
- [ ] https://github.com/Expensify/App/blob/05a58d8ecbbea76e1b21a9f989d72e0bc278906f/src/styles/getReportActionContextMenuStyles.ts#L3
- [ ] https://github.com/Expensify/App/blob/3b02565ea9df14b93ca3c1f2ce3de2ef4c8f4c1d/src/styles/getTooltipStyles.ts#L6
- [ ] https://github.com/Expensify/App/blob/1b22f59fd874fcc4297ee8f4350ae34d02f74aeb/src/styles/styles.ts#L23
- [ ] https://github.com/Expensify/App/blob/8537b739f520d3eba39958575d176b12f149b12a/src/styles/StyleUtils.ts#L12

**Comment by grgia** [comment]
**Ereceipt merchant text**
<img width="467" alt="image" src="https://github.com/Expensify/App/assets/38015950/8aaf189f-cf41-43d8-842f-0527d0538076">

**Comment by grgia** [comment]
<img width="381" alt="image" src="https://github.com/Expensify/App/assets/38015950/957320fe-0f03-457c-937f-82e84446c49e">

**Comment by grgia** [comment]
Light hover colors not changing


https://github.com/Expensify/App/assets/38015950/d6f22961-c867-4434-b947-42a664e186d7

**Comment by chrispader** [comment]
> Light hover colors not changing

this is working. Might be due to my PR here: https://github.com/Expensify/App/pull/32259

**Comment by grgia** [comment]
@chrispader nah it was due to my local changes 😂

**Comment by grgia** [comment]
![image](https://github.com/Expensify/App/assets/38015950/667484a2-d1aa-41dd-bd77-a5fdc8fa2a24)
