### ISSUE TITLE
[Wave 6: Referral Program] Promote referral program messaging in NewDot Redesign the Referral page

### ISSUE THREAD

**Issue by rezkiy37** [Expensify/App#32187]
## Background
We already implemented the referral program. However, there is a request to change UI.

## What to add and where to add it
Redesign [ReferralDetailsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReferralDetailsPage.js)

## What it should look and act like

![image](https://github.com/Expensify/App/assets/57314631/911d166f-c2e9-4b44-b711-93a55164f806)

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by jamesdeanexpensify** [comment]
Is it also possible to update the copy slightly at the same time?

**Comment by rezkiy37** [comment]
Actively working on the issue. Also, I have a question how to place additional content that was implemented [here](https://github.com/Expensify/App/issues/30283)?

https://staging.new.expensify.com/referral/shareCode

<img width="417" alt="Screenshot 2023-11-30 at 16 57 40" src="https://github.com/Expensify/App/assets/57314631/8b7286b4-2de5-4a47-a7b2-bf888e2924b9">

**Comment by rezkiy37** [comment]
Discussing internally - https://expensify.slack.com/archives/C02MW39LT9N/p1701715850199929?thread_ts=1701178690.263509&cid=C02MW39LT9N.

**Comment by CortneyOfstad** [comment]
Any updates on the PR? TIA!

**Comment by rezkiy37** [comment]
It was merged.

**Comment by rezkiy37** [comment]
Guys, I am having a vacation till the 4th January. So, I will be OOO within this period.

**Comment by CortneyOfstad** [comment]
Sorry, was OoO for the holidays — getting the payment summary together now!

**Comment by CortneyOfstad** [comment]
Needed clarification on payment amount, so asked internally [here](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1704213310691389). Will follow-up ASAP

**Comment by CortneyOfstad** [comment]
Alright, got confirmation! Breakdown below:

## Payment Summary

@parasharrajat to be paid $500 via NewDot as C+
@rezkiy37 is from CallStack, so no payment details needed at this time

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
