### ISSUE TITLE
[Wave 6: Drafts] Incorrect violation NextStep

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32207]
### Problem

Coming from [here](https://expensify.slack.com/archives/C02MW39LT9N/p1701276679216529). On Draft report, the "Next Steps" say "This expense belongs to a report that has violations. To ensure its submission, please review the violations. Go To Report" -- but the "Go to report" link doesn't do anything.

### Solution

Figure out why we are showing these next steps if they are not visible in OldDot and fix where the button links to if possible

**Comment by mountiny** [comment]
Noting: coming from here https://github.com/Expensify/Web-Expensify/blob/048bcb0cc9e88a00c8795392da7b5440a4d450e7/lib/Report/NextStep.php#L312-L322

**Comment by mountiny** [comment]
PR is up for this one https://github.com/Expensify/App/pull/32219

**Comment by greg-schroeder** [comment]
this is on prod
