### ISSUE TITLE
[$500] Web - Unable to save a new date receipt, and a console error appears for pending report status

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31353

## Action Performed:
Precondition:
1. Go to staging.expensify.com (Olddot) and login to tester@applausecard.expensifail.com
2. Create a new report and add the expense
4. Submit the report

1. Go to staging.new.expensify.com (NewDot)
2. Login into [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
3. Navigate to ttps://staging.new.expensify.com/r/316035362735270 - pending report
4. Select Date field
5. Than select month and date
6. Click on Year and Save it

## Expected Result:
Date field should be disable for pending report

## Actual Result:
Unable to save a new date receipt, and a console error appears for pending report status

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (31)](https://github.com/Expensify/App/assets/93399543/a5de66af-d546-4082-9115-0d37902b7106)

https://github.com/Expensify/App/assets/93399543/10825c99-ae77-40b7-875d-0b461f2306aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153ec5db1057e0d7a</li>
        <li>Upwork Job ID: 1729909147579199488</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by 70shakeel** [comment]
It seems to be a type error, the date is probably a string or should be a string and the variable it is being saved to accepts a different data type.

**Comment by abdel-h66** [comment]
Could you please update the steps to create a pending report ? thank you

**Comment by stephanieelliott** [comment]
bump @kbecciv

> Could you please update the steps to create a pending report ? thank you

**Comment by stephanieelliott** [comment]
bump @kbecciv, can you help us with [this ](https://github.com/Expensify/App/issues/32201#issuecomment-1838154464)

> Could you please update the steps to create a pending report ? thank you

**Comment by kbecciv** [comment]
@thesahindia and @stephanieelliott Added precondition in OP:
1. Go to staging.expensify.com (Olddot) and login to [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
2. Create a new report and add the expense
3. Submit the report


https://github.com/Expensify/App/assets/93399543/d53413f9-9d17-4f8b-b377-3d3357a04059

**Comment by stephanieelliott** [comment]
> Could you please update the steps to create a pending report ? thank you

Hey @abdel-h66 this has been updated if you would like to make a proposal

**Comment by stephanieelliott** [comment]
Hm, I'm not able to repro this anymore, I am able to change the date just fine now: 

<img width="551" alt="image" src="https://github.com/Expensify/App/assets/31225194/0f2824b9-17d8-434d-a9e1-27cf7cce63de">

Seems like this is fixed!
