### ISSUE TITLE
[HOLD for payment 2024-04-25] `macos-12-xlarge` runners are being canceled at a high rate

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#32212]
## Problem
About 50% of our iOS builds that use the `macos-13-xlarge` runner are being canceled with the error:

```
[Build and deploy iOS](https://github.com/Expensify/App/actions/runs/7032789006/job/19137288520)
The hosted runner encountered an error while running your job. (Error Type: Disconnect).
```

![Screenshot 2023-11-29 at 11 37 14 AM](https://github.com/Expensify/App/assets/2838819/dd3ea956-1cc6-4c39-b17d-77e5653da697)

## Solution
Fix it

**Comment by AndrewGable** [comment]
Looks related: https://github.com/actions/runner-images/issues/7754

**Comment by AndrewGable** [comment]
GitHub confirmed this was something on their side and they are looking into it

**Comment by AndrewGable** [comment]
Been pretty quiet from GitHub support, I will bump them

**Comment by AndrewGable** [comment]
No update from GitHub support

**Comment by AndrewGable** [comment]
We got a work around from GitHub support, but I am not sure we are seeing the error anymore. Looking into it today.

**Comment by AndrewGable** [comment]
GitHub says if we set `--maxsockets` on `npm install` it should help, but I am not sure we want to do so with all the runners not failing.

**Comment by AndrewGable** [comment]
I'll look back into this

**Comment by AndrewGable** [comment]
I think GitHub must have fixed it on their side, I haven't seen this happen in 2+ weeks.

**Comment by kgantchev** [comment]
Hi, not to be intrusive here, but it seems that this is a recurring issue here... have you considered [giving FlyCI a try](https://www.flyci.net/)?

**Comment by AndrewGable** [comment]
@kgantchev - Feel free to follow the [proposal process](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md), but no we haven't.

**Comment by AndrewGable** [comment]
Going to see if `macos-13-large` helps, I believe `xl` might have been depreciated. This will still use `intel` CPUs as we don't want to use arm64.
