### ISSUE TITLE
[HOLD for payment 2023-12-15] Update RenderHTML to Support Themes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32215]
see https://github.com/Expensify/App/issues/32188

https://github.com/Expensify/App/blob/1b22f59fd874fcc4297ee8f4350ae34d02f74aeb/src/styles/styles.ts#L207

This line is not affected by theme switching? You can see an example with the concierge messages

**Comment by grgia** [comment]
cc @chrispader

**Comment by grgia** [comment]
A few examples of renderHTML for easier QA:

- archived chat message
<img width="670" alt="image" src="https://github.com/Expensify/App/assets/38015950/df835554-cb75-4b01-9743-863e464f9f6a">

- transaction description
<img width="690" alt="image" src="https://github.com/Expensify/App/assets/38015950/b9c8a5d8-4384-4e55-9713-62e6295b8c50">

**Comment by koko57** [comment]
@grgia it seems that the reason that some colors weren't displayed correctly was that HTMLEngineProvider was passed earlier in the components array for ComposeProviders. After moving it after ThemeProvider and ThemeStylesProvider looks like the colors are correct 

before
<img width="1185" alt="Screenshot 2023-12-01 at 16 58 23" src="https://github.com/Expensify/App/assets/28020445/c6a440df-68c4-487f-9066-d10d0a9e6ee1">
after
<img width="275" alt="Screenshot 2023-12-01 at 16 30 02" src="https://github.com/Expensify/App/assets/28020445/2fc5dca2-4d52-4fc6-a0a7-d73f81652f8e">

<img width="363" alt="Screenshot 2023-12-01 at 17 01 45" src="https://github.com/Expensify/App/assets/28020445/39f57156-41f3-4058-990a-f61f78e04664">
<img width="946" alt="Screenshot 2023-12-01 at 17 02 41" src="https://github.com/Expensify/App/assets/28020445/5613d2e9-78d8-440e-8965-7b45fe6aafb0">

but I'm not really familiar with the reason why these providers were in such order and if we can move the HTMLEngineProvider just simply like that without any regressions?

**Comment by grgia** [comment]
@koko57 thank you so much! I wonder if we should just create a PR and move the style providers instead?

``` bash
diff --git a/src/App.js b/src/App.js
index 2caa6b9ffc..ef5b778189 100644
--- a/src/App.js
+++ b/src/App.js
@@ -53,6 +53,10 @@ function App() {
             <ComposeProviders
                 components={[
                     OnyxProvider,
+                    ThemeProvider,
+                    ThemeStylesProvider,
+                    ThemeIllustrationsProvider,
+                    CustomStatusBarContextProvider,
                     SafeAreaProvider,
                     PortalProvider,
                     SafeArea,
@@ -65,10 +69,6 @@ function App() {
                     ReportAttachmentsProvider,
                     PickerStateProvider,
                     EnvironmentProvider,
-                    ThemeProvider,
-                    ThemeStylesProvider,
-                    ThemeIllustrationsProvider,
-                    CustomStatusBarContextProvider,
                 ]}
             >
```

**Comment by koko57** [comment]
@grgia if we can change the order freely, I think we can move them up

**Comment by grgia** [comment]
@koko57 I think that works, I've been testing locally and it seems to work

**Comment by grgia** [comment]
I think this may be no QA. As for testing, so long as the App is rendering on all platforms without error, I think we can assume that the remaining providers are working as normal.

**Comment by chrispader** [comment]
yea, no problem moving the theme switching providers up 👍🏼

**Comment by grgia** [comment]
@adelekennedy could you help make sure that the $500 C+ review payment is paid to @fedirjh for https://github.com/Expensify/App/pull/32366

**Comment by adelekennedy** [comment]
@fedirjh hired you [here](https://www.upwork.com/jobs/~01b098069872319253)

**Comment by adelekennedy** [comment]
paid!

**Comment by grgia** [comment]
closing as complete!
