### ISSUE TITLE
[$500] Server-side search changes the selected row

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701212653310919

## Action Performed:
1. Click on the search icon
2. Enter a user’s display name
3. Select a result in the search query

## Expected Result: 
Selected result doesn’t change

## Actual Result: 
Selected result changes when server-side querying completes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/fd2f7868-3b27-42cd-8452-ec85edd69f59

https://github.com/Expensify/App/assets/38435837/fd13a0ab-ddaf-4031-8fc1-0523c76c0544

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01848f1946d98c21d7</li>
        <li>Upwork Job ID: 1729979719481249792</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Server-side search changes the selected row

### What is the root cause of that problem?
First, let's see this logic
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/components/OptionsSelector/BaseOptionsSelector.js#L152-L161

In the search page, we don't allow multiple selection so that with above logic we always set `focusedIndex` is 0 in `componentDidUpdate` (Note that: in search page `this.props.focusedIndex` is undefined and `newFocusedIndex` is 0)

### What changes do you think we should make in order to solve the problem?


we only should set `focusedIndex` in here
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/components/OptionsSelector/BaseOptionsSelector.js#L160

When that page allow multiple selection by checking `this.props.canSelectMultipleOptions`
### What alternative solutions did you explore? (Optional)

**Comment by peterdbarkerUK** [comment]
@situchan would you mind taking a look at these proposals?

**Comment by situchan** [comment]
@DylanDylann I am not quite following your solution.

> In the single selection case, it is redundant, so we only should set `focusedIndex` in here

Can you share permalink to remove as redundant?

**Comment by DylanDylann** [comment]
@situchan 

I mean In the single selection case, updating focusedIndex in here is redundant 
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/components/OptionsSelector/BaseOptionsSelector.js#L160

**Comment by situchan** [comment]
> @situchan
> 
> I mean In the single selection case, updating focusedIndex in here is redundant
> 
> https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/components/OptionsSelector/BaseOptionsSelector.js#L160

Imagine you focused any row and then it was removed (action done in another device).
It should reset to first index

**Comment by DylanDylann** [comment]
@situchan 
> it was removed (action done in another device)

Do you mean that we also need to sync the focused index between all devices at the same time

**Comment by situchan** [comment]
No. Let me take example:
- user searches for something and filter results are: A, B, C
- Focus on 2nd row - B
- B is excluded from results for some reason
- Focus should reset to A

**Comment by situchan** [comment]
> @situchan I don't think the result is sync between 2 devices as the below video
> 
>  Screen.Recording.2023-12-14.at.00.36.24.mov 
> Please correct me if I am wrong

@DylanDylann Is that same account? Can you logout and re-login on both accounts and try again?
If still happens, then it's another bug

**Comment by DylanDylann** [comment]
@situchan Yes, it is the same account. It still happens. Could you help to attach a video about this bug?

**Comment by peterdbarkerUK** [comment]
proposals are still under review - @situchan could you respond to [this](https://github.com/Expensify/App/issues/32226#issuecomment-1864011095)?

**Comment by peterdbarkerUK** [comment]
@situchan friendly bump!

**Comment by situchan** [comment]
@DylanDylann your solution causes regression. Focus should be reset whenever data changes


https://github.com/Expensify/App/assets/108292595/3b9c2c10-dd2b-4284-b199-c70e808679ae

**Comment by situchan** [comment]
@tienifr does your proposal resolve [this concern](https://github.com/Expensify/App/issues/32226#issuecomment-1878117977)?

**Comment by situchan** [comment]
Awaiting proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by peterdbarkerUK** [comment]
@tienifr [nudge on this one](https://github.com/Expensify/App/issues/32226#issuecomment-1892536502) :)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by zanyrenney** [comment]
This is now resolved, closing.
