### ISSUE TITLE
[HOLD for payment 2024-01-09] [Wave 6: Drafts] Make Merchant field required for requests on group policies

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32222]
### Problem

The Merchant field is required value for expenses in database, thats why we have been always setting the `Request` name for all IOU or Expense requests for now. This however does not scale well for more business usecases so we should copy what we do in OldDot and make sure the merchant is required to be filled out by the user on group policies. (Free, Collect, Corporate) ie any expense report

### Solution

- Show a form error if you try to create a manual request without a merchant on Group plans, remove the default
    - ie users should not be able to create new requests on Group policies without supplying Merchant 
    - this holds for manual requests, receipts get smartscanned and distance requests have predefined merchant fields 
    - Splitting a manual bill with Group policy is also cannot be done without supplying merchant
- Show all required fields above the show more pill

**Comment by abekkala** [comment]
@sophiepintoraetz 
### STATUS:
I'm going ooo though Jan 02

The only payout for this will be to the PR Review which I believe is to [eVoloshchak]
Can you confirm @mountiny 
and would this be for $250 or $500

**Comment by mountiny** [comment]
I think this can be closed now
