### ISSUE TITLE
[$500] "No results found" message appears when opening a chat with own secondary login

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701135752002059

## Action Performed:
Precondition: Account A has set up secondary login
1. Login as Account
2. click on search
3. Enter secondary login email address

## Expected Result:
Should open up a "self chat"

## Actual Result:
No results found message appears

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/afaf4297-c309-4337-bbb2-5946ddf7cf33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b0e8103a53a4fd7</li>
        <li>Upwork Job ID: 1729974532789776384</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
@MitchExpensify @shawnborton What do you think about implementing self-chat in our App? And please help to confirm 
> We need to decide which functionality should be displayed in self-chat chat like sending messages, assigning tasks,... and which pages we allow display self-chat

**Comment by shawnborton** [comment]
Hmm, I would bring that up in the open source room for further discussion. I do think we've kicked around the idea before but haven't made any progress there.

**Comment by MitchExpensify** [comment]
We are looking into "Self-Chat", closing this for now
