### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Send money - Bank account option is not present in Pay with Expensify menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Click + > Send money
4. Select USD currency and enter an amount > Click Next
5. Click Pay with Expensify

## Expected Result:
Bank account option will be present in Pay with Expensify menu

## Actual Result:
Bank account option is not present in Pay with Expensify menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/28fbecb5-b6e8-462a-979f-0b02f7eaabcb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01782e16325ea5e0f2</li>
        <li>Upwork Job ID: 1729983421600763904</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27911758</li>
<li>dukenv0307 | Contributor | 27911760</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Hm, @kevinksullivan @joekaufmanexpensify can you guys chime in on this one? 

1. My personal workspace currency is USD 
2. I don't have a wallet enabled 
3. I send money in USD 
4. I tap `Pay with Expensify` on the confirmation screen
5. I see a debit card option?

<img width="374" alt="image" src="https://github.com/Expensify/App/assets/16232057/f6e10c57-c520-451c-a13f-b51ac792cccd">

Why aren't I prompted here to go through the flow and enable the wallet?

**Comment by joekaufmanexpensify** [comment]
>Why aren't I prompted here to go through the flow and enable the wallet?

@trjExpensify If you add a debit card, are you prompted to then set up your wallet? I'd expect you would be. We just prompt to you to add payment method as the first step of the wallet enable flow.

**Comment by trjExpensify** [comment]
>@trjExpensify If you add a debit card, are you prompted to then set up your wallet?

I only have a UK debit card unfortunately, so I didn't attempt to go further through the flow at the time.  

>I'd expect you would be. We just prompt to you to add payment method as the first step of the wallet enable flow.

But why would we only show the option for `Debit card` and not connecting a bank account to enable the wallet? The screenshot from [here](https://github.com/Expensify/App/issues/32228#issuecomment-1834341551) is the first thing I see.

**Comment by joekaufmanexpensify** [comment]
>But why would we only show the option for Debit card and not connecting a bank account to enable the wallet? The screenshot from https://github.com/Expensify/App/issues/32228#issuecomment-1834341551 is the first thing I see.

This I'm not sure of. I would expect that we'd show bank account in every scenario too.

**Comment by trjExpensify** [comment]
Cool, so that's being addressed in this issue hopefully. Pretty strange bug to slip through though!

**Comment by kevinksullivan** [comment]
Hmm sorry totally missed this, but yeah I'm not sure why you're only seeing debit card here. That ain't right.

**Comment by kevinksullivan** [comment]
Hi @aimane-chnaif please complete the checklist above when you get a chance!

**Comment by trjExpensify** [comment]
@aimane-chnaif awaiting the checklist. What's your ETA on completing that, please?

**Comment by trjExpensify** [comment]
Thanks! Confirming payments due are: 

$500 to @aimane-chnaif for the C+ review
$500 to @dukenv0307 for the fix 

Settled up!
