### ISSUE TITLE
[$500] Expense - Console error on expense report and Go To Report button is not working in violation info

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace created from OD
- The Collect workspace has `People must categorize expenses` toggled on

1. Log in as employee
2. Go to the workspace chat > + > Request money
3. Create a manual expense without selecting a category
4. Click on the expense preview to open expense report page
5. Click Go To Report in expense violation message

## Expected Result:
In Step 4, no console error will appear
In Step 5, 'Go to report' button redirects user to the relevant site

## Actual Result:
In Step 4, no console error shows up
In Step 5, 'Go to report' button is not responsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/92665b01-3508-4f21-90f6-76a0508b1d95

[logs.txt](https://github.com/Expensify/App/files/13505886/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a06964dab9f6099</li>
        <li>Upwork Job ID: 1729984461656281088</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by junsupark94** [comment]
I tried reproducing the bug. I went to OldDot, created a Workspace with the Collect plan, added a member as employee, enabled "People must categorize expenses." I'm not having this workspace show up in NewDot. Its #admin and #announce chatrooms appear but not the workspace itself.

![Created workspace in OldDot](https://github.com/Expensify/App/assets/97586064/2c7de3db-8e25-4557-9380-29a12a056625)

![Selected Collect plan](https://github.com/Expensify/App/assets/97586064/3a8016b6-5a86-4c98-a64a-b516c6cfca85)

![Enabled "People must categorize expenses"](https://github.com/Expensify/App/assets/97586064/281f3d35-ed4b-4fe4-83a3-a8174e31d06a)

![Added members as employees](https://github.com/Expensify/App/assets/97586064/1433ddfc-399b-43f8-9572-ff6f99d3fca9)

![Only #admins and #announce shows up in NewDot](https://github.com/Expensify/App/assets/97586064/83cc1adf-eed3-4abc-8006-7b3410368e76)

Did I do something incorrectly?

**Comment by conorpendergrast** [comment]
@mkhutornyi Thanks! Could you share some context for why>

**Comment by conorpendergrast** [comment]
Ok, given that https://github.com/Expensify/App/issues/26614 was closed, I will also close this one!
