### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] Expense-In "recents",category selected while creating expense is displayed instead of altered.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32230]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap employee WS chat
3. Tap plus icon near compose
4. Tap request money ----- Manual
5. Enter an amount
6. Tap next
7. Tap show more
8.  Select a category
9. Tap request
10. Open newly created expense
11. Tap category and select a new category
12. Navigate back to employee Workspace chat
13. Tap plus icon near compose
14. Tap request money ----- Manual
15. Enter an amount
16. Tap next
17. Tap show more
18. Tap category
19. Note, the category selected while creating expense is displayed in "recents" on top
20. Refresh the page
21. Note, the category altered after expense created is displayed in "recents" now

## Expected Result:
The category altered after expense created must be displayed in "recents" on top

## Actual Result:
The category selected while creating expense is displayed in "recents" on top. The altered category is shown in "recents" only after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bc954949-95af-4fde-927f-5c45632ad794

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8b6f650f2e88ed5</li>
        <li>Upwork Job ID: 1729985911471767552</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27916699</li>
<li>DylanDylann | Contributor | 27916700</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense-In "recents",category selected while creating expense is displayed instead of altered

### What is the root cause of that problem?
Currently, we only update `policyRecentlyUsedCategories` when creating new request. We don't update `policyRecentlyUsedCategories` when editing a request
### What changes do you think we should make in order to solve the problem?
We need to add logic to update `policyRecentlyUsedCategories` when editing `category` field

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
I am working on PR

**Comment by DylanDylann** [comment]
> It's better if you can point out why the altered category is shown in "recents" only after refreshing the page.

@hoangzinh After reloading page, the BE return correct POLICY_RECENTLY_USED_CATEGORIES so the data is updated correctly

**Comment by anmurali** [comment]
All done.
