### ISSUE TITLE
[$500] Report deleted from OldDot stays visible in the NewDot workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701281289145229

## Action Performed:
1. Create a request in NewDot
2. Visit OldDot and delete the report

## Expected Result:
The report is not longer visible in either OldDot or NewDot
## Actual Result:
The report remains visible in NewDot, even though it’s gone in OldDot. Clicking into the report preview gives a Hmm it's not here error
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/144f5173-5cec-4b70-a014-c80a15953f8e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2cf14ae2fceaf7a</li>
        <li>Upwork Job ID: 1730018871236292608</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by keisyrzk** [comment]
Neither do I. All tries with Old Dot ends with a redirection to the New one.

**Comment by laurenreidexpensify** [comment]
I'm asking internally about access to olddot - https://expensify.slack.com/archives/C05NJ4SLBMF/p1701684128003329

**Comment by francoisl** [comment]
We now automatically redirect to NewDot unless you're trying to access a specific page on OldDot. Try opening https://www.expensify.com/reports for example, it shouldn't redirect you to NewDot.

**Comment by keisyrzk** [comment]
@m-natarajan could you please update the steps for reproduction please? Those provided and the video are insufficient. There are many factors that might affect the final result.
Please provide detailed steps to show how do you
- enter and navigate in the Old Dot and New Dot
- create the request exactly (so we could reproduce the exact same state you had)
- delete it
- verify the result

Please ensure there are no doubts about the steps, and what you do exactly to reproduce the issue.

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by keisyrzk** [comment]
@laurenreidexpensify the issue needs reproduction steps update and a video showing the whole process from the very beginning. At the moment the provided information is insufficient to reproduce the case.

**Comment by laurenreidexpensify** [comment]
@m-natarajan Please can you review the reproduction steps on this? Thanks

**Comment by Victor-Nyagudi** [comment]
I can reproduce this. 

I suspect a back end issue because: 

1. The report created in ND doesn't show up on OD until the OD page is refreshed (I tested with the two tabs open side by side).
2. I didn't see any network activity in ND when the report is deleted in OD. When you try opening the report, you're looking for a report with an ID that no longer exists, hence the "Hmm...it's not here" page. 

Also, I'm not sure if it's intended, but this is what the report preview looks like when the request is deleted on OD (below are 2 different reports). 

![expensify-report-deleted-in-OD](https://github.com/Expensify/App/assets/79470910/735e04d1-fabf-4040-9556-6e6fa09d0fb4)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
