### ISSUE TITLE
[HOLD for payment 2023-12-12] [Theme Switching Migration] - remove remaining default theme imports from Utils

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32255]
https://github.com/Expensify/App/issues/31677#issuecomment-1833367171

**Comment by koko57** [comment]
draft opened: https://github.com/Expensify/App/pull/32264 It's a big one

**Comment by koko57** [comment]
https://github.com/Expensify/App/pull/32250 and the one @rezkiy37 opened

**Comment by koko57** [comment]
@grgia @chrispader ready for review https://github.com/Expensify/App/pull/32264

**Comment by grgia** [comment]
Closing as complete

**Comment by allroundexperts** [comment]
@grgia Can I have a payment summary please?

**Comment by grgia** [comment]
@allroundexperts 

$500 C+ Review payment for https://github.com/Expensify/App/pull/32264

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on comment above.
