### ISSUE TITLE
[HOLD for payment 2023-12-15] [Theme Switching Migration] - finalize theme hook migration for App

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32257]
@chrispader 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by chrispader** [comment]
comment for assignment :)

**Comment by chrispader** [comment]
@grgia can we close this out?

**Comment by grgia** [comment]
@strepanier03 could you help ensure that the $500 C+ review payment for https://github.com/Expensify/App/pull/32259 is made to @parasharrajat

**Comment by strepanier03** [comment]
@grgia - Yes I can start working on this and see if I can get it all finished today. Otherwise I'm out until the 28th when I'll pick it back up.

**Comment by strepanier03** [comment]
@parasharrajat - I've hired you to the job in Upwork, accept as soon as you can and I'll pay it out. I'm offline after today until the 28th.

**Comment by strepanier03** [comment]
@parasharrajat - Oops, sorry about that!

I have canceled the contract in Upwork and will post a payment summary directly after this.

**Comment by strepanier03** [comment]
### Payment summary

- [x] Reporter - N/A
- [x] Contributor - N/A
- [ ] C+ - @parasharrajat = $500 payment due via Manual Requests

@JmillsExpensify - A request should be coming in shortly from Rajat, thank you!
