### ISSUE TITLE
[HOLD for payment 2024-01-02] [$500] mWeb - Expense - Red dot in preview does not disappear after filling in Amount and Merchant manually

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.5-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to workspace chat > + > Request money > Scan.
3. Create a scan request with a receipt that will fail smartscanning.
4. Open expense report page while waiting for scanning to fail. (Can switch between expense report and request details page to check if it has failed).
5. When the scanning fails, go to expense details page.
6. Manually enter Amount and Merchant.
7. Tap on the back button on the top right twice to return to workspace chat.

## Expected Result:
The red dot on the expense preview in the main workspace chat will disappear because amount and merchant are filled manually.

## Actual Result:
The red dot on the expense preview in the main workspace chat does not disappear unless the workspace chat is refreshed or revisited.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b258d763-2e75-4ada-9717-bf0b4adb8e4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175e10e5dd361820c</li>
        <li>Upwork Job ID: 1730195296934002688</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27959389</li>
<li>dukenv0307 | Contributor | 27959390</li>
</ul></li>
    </ul>
</details>

**Comment by jasperhuangg** [comment]
Thanks for the proposal! @dukenv0307 seems straightforward, nice job!

**Comment by alexpensify** [comment]
Daily Update: The PR is in the review process!

**Comment by alexpensify** [comment]
Daily Update: The PR is moving along

**Comment by alexpensify** [comment]
The PR is still under review.

**Comment by rlinoz** [comment]
https://github.com/Expensify/App/pull/32469/files#diff-90dbf92cac79a4d1c6199362686c19700554305c62fbbeadcaa509c3abe7e5a9R219

Missed passing `props.action` to `areAllRequestsBeingSmartScanned`

**Comment by alexpensify** [comment]
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @dukenv0307 
-  Contributor+ that helped on the issue and/or PR - @hoangzinh 

Upwork Job: https://www.upwork.com/jobs/~0175e10e5dd361820c

Extra Notes regarding payment: Heads up, I'm OOO until January 4, but I will log in on Wednesday, January 3, to complete this payment process pending no regression. I've confirmed that everyone here is a pending hire, so all set here for the payment date.

**Comment by alexpensify** [comment]
Closing - everyone has been paid via Upwork and I closed the job there. The only remaining action is to add the regression test.
