### ISSUE TITLE
[$500] [HOLD for payment 2023-12-28] [Wave 6: Referral Program] Move "Download" above "Get $250" on "Share code" screen

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#32282]
## Background
Based on [this conversation](https://expensify.slack.com/archives/C02MW39LT9N/p1701364185999299), we'd like to adjust the order of the options on the "Share code" screen. More specifically, let's:

- Keep "Copy URL to clipboard" in first position
- Move "Download" to second position
- Move "Get $250" to third position

![image](https://github.com/Expensify/App/assets/22160301/fed261d6-9f1c-40c1-9e3d-071f5d2273ef)
 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146d9e7fec0e7dec0</li>
        <li>Upwork Job ID: 1742049375416360960</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hey, Im Artem from Callstack and would like to help with this issue

**Comment by sakluger** [comment]
Thanks @waterim!

**Comment by jamesdeanexpensify** [comment]
In this same issue, is it also possible to update "Copy URL to clipboard" to just say "Copy"? Thanks!

**Comment by dangrous** [comment]
@waterim since we already merged your PR, can you raise another to update the text as above ^ ? Thank you!

**Comment by dangrous** [comment]
bump @waterim if you think you might have time! If not I can grab this quickly later this week

**Comment by waterim** [comment]
@dangrous I can take it today!

**Comment by sakluger** [comment]
@aimane-chnaif I've sent you an offer via Upwork. Could you please let me know once you've accepted the offer? Thanks!

**Comment by sakluger** [comment]
@aimane-chnaif friendly bump.

**Comment by sakluger** [comment]
All paid, thanks!
