### ISSUE TITLE
[HOLD for payment 2024-01-30] [HIGH] Workspace Chats: Submitting report offline causes errors in the report and red dot w/o error message in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32157
## Action Performed:
Precondition:
- User is an employee of a Collect workspace
1. Log in to ND as the employee
2. Go offline
3. Go to the workspace chat > + > Request money
4. Create a manual request with currency different than the workspace default currency
5. Open expense report and submit the expense
6. Return online

## Expected Result:
The report will be submitted without issue when returning online

## Actual Result:
Three issues show up
1. The report submission message moves above the report chat view
2. Submit button appears again when returning online
3. In LHN, the expense report shows a red dot but there is no error message in the report. The red dot remains after clicking Submit button again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/e642d272-ee75-4227-b436-41d4471fcae8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by jasperhuangg** [comment]
Clarified that this isn't a deploy blocker [here](https://expensify.slack.com/archives/C07J32337/p1701371446655199?thread_ts=1701371328.322759&cid=C07J32337)

Reasoning is that it's behind a beta and we are still going to work on this so it should just be added to the wave6 project

**Comment by jasperhuangg** [comment]
Assigning @mountiny since this was related to his PR

**Comment by mountiny** [comment]
So this is a known limitation right now, we do not know the `managerID` on the open expense report when its created optimistically.

**Comment by mountiny** [comment]
thats why the submission offline fails because we "did not submit to anyone". Was discussed in slack in previous days and we will have to pass down who we need to submit to as part of the Policy data

**Comment by mountiny** [comment]
Discussin gin Slack, we will probably update the nedpoint to not require the manager Account Id as that is not needed for the submitter to know

**Comment by mountiny** [comment]
I will create a new SubmitExpenseReport command for this and that will not require passing the accountID

**Comment by mountiny** [comment]
Continuing to work on this today

**Comment by mountiny** [comment]
I got a draft going but I think we might want to discuss this further a bit

**Comment by mountiny** [comment]
We were discussing how to approach this, I will make a PR to return the submitsTo in this case

**Comment by mountiny** [comment]
Still working on this one

**Comment by mountiny** [comment]
The discussions concluded saying its fine to get the submitsTo into the policy object so I am preparing a PR for it

**Comment by mountiny** [comment]
We got the `submitsTo` ready so going to use that

**Comment by mountiny** [comment]
PR is up

**Comment by sobitneupane** [comment]
@aimane-chnaif reviewed the PR.

**Comment by mountiny** [comment]
$500 to @aimane-chnaif for review and testing

**Comment by kadiealexander** [comment]
Please request your payment via NewDot @aimane-chnaif.

**Comment by kadiealexander** [comment]
Ah sorry @aimane-chnaif I misunderstood. I've sent you a contract :)

**Comment by kadiealexander** [comment]
@aimane-chnaif please let me know when you've accepted the offer!

**Comment by kadiealexander** [comment]
Paid!
