### ISSUE TITLE
[Wave 6: Workspace Chats] Expense - Report header shows 'owes' instead of 'paid' after submitting the expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32281]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32157
## Action Performed:
Precondition:
- User is an employee of a Collect workspace
1. Log in to ND as the employee
2. Go to the workspace chat > + > Request money
3. Create a manual request
4. Click on the expense preview
5. Click Submit
6. Take note of the content on the header
7. Click on the header subtitle to return to workspace main chat
8. Click on the expense preview

## Expected Result:
In Step 6, the header should show 'owes'

## Actual Result:
In Step 6, the header shows 'paid' after submitting the expense.
It becomes 'owes' after the report is revisited in Step 8

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5fc9fe0f-5181-4cc0-9acc-b0bcf36eba95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010068d3d052c3afed</li>
        <li>Upwork Job ID: 1730282956105023488</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27910611</li>
<li>cubuspl42 | Contributor | 28065391</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by amyevans** [comment]
I think @mountiny fixed this recently but I don't have the PR link on hand to confirm

**Comment by mountiny** [comment]
I have only fixed this for draft report but did not know this turns to `paid` after submission so one more thing to fix, added to the wave6 project. I will remove the Help Wanted label and we can handle it internally

**Comment by mountiny** [comment]
This will be because of the Submit & Close settings for the policy so after submitting the report is considered closed

**Comment by rezkiy37** [comment]
@mountiny, so, after investigation, I've found a field of a `report` that takes responsibility for this behaviour. It is `hasOutstandingIOU`. When the app submits a report optimistically, it passes `hasOutstandingIOU` as `false`, but the backend always returns `true`. 

Once, I added `hasOutstandingIOU: true,` explicitly, everything works smoothly. Unfortunately, I am not familiar with the value yet. Could you please explain me whether it can be used in this way or not?

<img width="815" alt="Screenshot 2023-12-01 at 15 38 55" src="https://github.com/Expensify/App/assets/57314631/a2a948ac-6e04-4257-a640-e96be4fc045c">


https://github.com/Expensify/App/assets/57314631/8c83a907-453a-4a07-ae29-85afca82f939

**Comment by rezkiy37** [comment]
Melvin, no overdue here. Waiting for answer on a [comment](https://github.com/Expensify/App/issues/32281#issuecomment-1836231370).

**Comment by mountiny** [comment]
@rezkiy37 I see I think it makes sense, in general I think this field is just more confusing now as we are moving hte GBR to the parent chat with the `hasOutstandingChildRequest` key. 

Could you raise a PR with this change please?

**Comment by mountiny** [comment]
I think we can deprecate this prop, discussing [internally](https://github.com/Expensify/App/issues/32565) yet to make sure I have not missed anything

**Comment by rezkiy37** [comment]
This issue is gonna be fixed in a scope of https://github.com/Expensify/App/issues/32565.

**Comment by mountiny** [comment]
$500 for a review to @cubuspl42

**Comment by slafortune** [comment]
Paid!
