### ISSUE TITLE
[$500] mWeb/Safari - Profile - Cursor not displayed in country field on tapping country option in address form

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Tap settings icon in LHN
3. Select Profile >> Personal details
4. Tap Address option
5. Tap on Country option

## Expected Result:
Cursor should be displayed in country field to highlight the field is focused

## Actual Result:
Cursor not displayed in country field on tapping country option in address form

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/79eaec88-51ab-43ed-b8c7-61d919dcde8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01208951412ab720ab</li>
        <li>Upwork Job ID: 1730285832120459264</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by sobitneupane** [comment]
I can reproduce the issue. It is reproducible for all the text inputs (single inputs) that are supposed to autofocus after the screen navigation. I believe those issues are quite old and were reported many times.

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/26312 is a similar issue. [This](https://github.com/Expensify/App/issues/26312#issuecomment-1733515567) is the list of similar issue. 

Some of those issues were closed with this [reasoning](https://github.com/Expensify/App/issues/7064#issuecomment-1009428344).

> I couldn't reproduce this on the emulator, but it's reproducible on a physical device. This is a browser limitation for mobile Safari. Apple blocks any programmatic focus that was not invoked in response to a user gesture.
>
> Not sure if there is anything that we can do here.

**Comment by puneetlath** [comment]
Ok let's close it for the same reason as that issue then. Thanks @sobitneupane
