### ISSUE TITLE
[Awaiting checklist completion] [$500] Android-BA-Tapping connect online with plaid shows 2 spin circles loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32298]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces
4. Tap on a Workspace
5. Tap Bank account
6. Tap "connect online with plaid"

## Expected Result:
When user taps "connect online with plaid", single spinner loading in the page must be shown

## Actual Result:
When user taps "connect online with plaid", double spinner can be seen in the page loading for few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b346c674-f510-4bd8-8f77-3044fe45c8be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196db5598b3527ce7</li>
        <li>Upwork Job ID: 1730310951315976192</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27980936</li>
<li>ZhenjaHorbach | Contributor | 27980939</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Android-BA-Tapping connect online with plaid shows 2 spin circles loading

## What is the root cause of that problem?

The problem is related to the display of components
Since they are displayed in parallel
There are cases when the condition for the loader and the condition for PlaidLink are fulfilled simultaneously

https://github.com/Expensify/App/blob/ee7d5dc8d8c6d8706564e1dee685b093f9f4baa3/src/components/AddPlaidBankAccount.js#L188-L227

And that's why we see 2 loaders

## What changes do you think we should make in order to solve the problem?

Instead of using `&&` for each condition
We can refactor this component
To use if / else 
So that when we have PlaidLink available, we will disable the loader

## What alternative solutions did you explore? (Optional)
NA

**Comment by twisterdotcom** [comment]
@akinwale would love your thoughts on the proposals.

**Comment by akinwale** [comment]
I suggest going with @ZhenjaHorbach's proposal since a refactor will result in clearer, more readable code making it easier to understand return paths.

🎀 👀 🎀 C+ reviewed.

**Comment by ZhenjaHorbach** [comment]
> 📣 @ZhenjaHorbach 🎉 An offer has been automatically sent to your Upwork account for the Contributor role 🎉 Thanks for contributing to the Expensify app!
> 
> [Offer link](https://www.upwork.com/nx/wm/offer/27980939) [Upwork job](https://www.upwork.com/jobs/~0196db5598b3527ce7) Please accept the offer and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

PR will be ready today or tomorrow

**Comment by mountiny** [comment]
@akinwale @ZhenjaHorbach Based on the comment from the QA [here](https://github.com/Expensify/App/issues/33480#issuecomment-1868536553) the issue did not get resolved on Desktop. Would you be able to take a look into this one?

**Comment by mountiny** [comment]
That is apparently it so we are good

**Comment by twisterdotcom** [comment]
@Beamanator and @akinwale - is this correct? If so, I can pay out once https://github.com/Expensify/App/issues/33890 is deployed at $250 instead.

**Comment by twisterdotcom** [comment]
Hmm actually, @marcaaron removed the deployblocker. I'm going to pay this out as normal.

Payment Summary:
@akinwale paid $500 [here](https://www.upwork.com/nx/wm/offer/27980936) (Reviewer)
@ZhenjaHorbach paid $500 [here](https://www.upwork.com/nx/wm/offer/27980939) (Contributor)

**Comment by twisterdotcom** [comment]
Just waiting on @akinwale to complete the checklist.

**Comment by akinwale** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is a specific case that was not handled in the code.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test steps**
* Launch the Expensify app on Android
* Tap on the profile picture and navigate to Workspaces
* Select any workspace without a bank account, or create a new workspace if none exist
* Select Bank account
* Tap "Connect online with Plaid"
* Verify that only one loading indicator is displayed during the loading process

Do we agree 👍 or 👎?
