### ISSUE TITLE
[$500] BA - No validation error when emoji and certain symbols are entered in name field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30674
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace
3. Go to Bank account > Connect manually
4. Proceed to Step 3
5. Add @, +, (), [] and emoji in the name field
6. Submit the form

## Expected Result:
Error will show up on the name field with invalid symbols and emoji

## Actual Result:
Error does not show up on the name field with invalid symbols and emoji. Only certain symbols pass the validation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/000cad5a-1288-4bd5-9e8e-7a6f1e068be8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdad690a07b3c07f</li>
        <li>Upwork Job ID: 1740328309374783488</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28109979</li>
<li>Krishna2323 | Contributor | 28109980</li>
</ul></li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
If we want to add `@` or `+` we can, but I'm not aware of any full list of forbidden characters that we have anywhere

**Comment by stitesExpensify** [comment]
Oh, you can't submit? My understanding was that you could submit but would get an error message

**Comment by trjExpensify** [comment]
Nah, look at the screenie below of the video: 

<img width="1186" alt="image" src="https://github.com/Expensify/App/assets/16232057/95f885bd-be11-4e98-86ae-246b99143ae2">

Imagine you filled out everything apart from the first name field correctly. That would be weird, right?

**Comment by stitesExpensify** [comment]
Right, so that screenshot shows that you _can_ submit with the first name wrong, and then you would get an error afterwards which isn't really a big deal if you're putting things like @ and emojis in the first name.

Regardless, it should probably be fixed to match the rest of them.

**Comment by stitesExpensify** [comment]
@0xmiroslav feel free to check out proposals here

**Comment by trjExpensify** [comment]
>Right, so that screenshot shows that you can submit with the first name wrong

Right, our forms design never prevents you from clicking the `submit` button on a form.

>and then you would get an error afterwards which isn't really a big deal if you're putting things like @ and emojis in the first name.

There's no error being shown on the first name field, that's the problem.

**Comment by trjExpensify** [comment]
@0xmiroslav over to you for the proposal review, please!

**Comment by trjExpensify** [comment]
Do we allow them in https://github.com/Expensify/App/pull/30674?

**Comment by trjExpensify** [comment]
Then it makes sense to be consistent here then I think :)

**Comment by trjExpensify** [comment]
Same, Melv.

**Comment by trjExpensify** [comment]
I might be being dense, but I'm not sure that answered my question really. Why can't we use the same validation logic for the name field in connect bank account and legal name pages?

**Comment by trjExpensify** [comment]
Got it, @0xmiroslav what do you want to do here?

**Comment by trjExpensify** [comment]
@0xmiroslav what's your ETA on this proposal review?

**Comment by trjExpensify** [comment]
@0xmiroslav any luck today?

**Comment by trjExpensify** [comment]
@0xmiroslav next steps here?

**Comment by shubham1206agra** [comment]
Hello @0xmiroslav can you hold this on VBBA refactor? The refactor should be completed in a week probably.

**Comment by trjExpensify** [comment]
Alright, cool.

**Comment by trjExpensify** [comment]
I think you both could have been a bit more forthcoming with updates to the proposals, as per here in the guidelines: 

```
- Do not make extensive changes to your current proposal until after it has been reviewed.
-  If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:
- ## Proposal
-[Updated](link to proposal)
```

@dukenv0307 - you updated your proposal like 5 times on Dec 7th, which suggests you still had some things to work through to arrive at what you wanted to propose. 

@Krishna2323 - you updated your proposal like 6 times on Dec 3rd suggesting the same as the above. You also moved away from `isValidLegalName` and didn't note your reasoning for the 180 when updating and kept it as an alternative solution you explored as the template allows. 

So all that is to say, maybe this is a good learning curve for all of us on that step of the process when it comes to putting together proposals, updating them, and communicating alts you explored! :) 

>I saw few issues that considers proposals as dupe if the solution has already been in the edit history of any existing proposal.

I haven't seen it myself, nor the added context on those. Perhaps @0xmiroslav you have a point of reference of similar scenarios, given the direction you went here on selection based on the first draft of the proposed solution? 

The way I see it is that the "final" versions ahead of review (or any other proposal to influence it) is what someone intends to propose. Anything before that I'd consider a draft really, and it's not encouraged to post and iterate a ton before input.

**Comment by trjExpensify** [comment]
Given the failures on both sides here with presenting initial proposals and edits, @0xmiroslav can you look at the "final" proposals put forward from both on Dec 3rd and Dec 7th to decide which one is more aligned with where we ended up landing? 

There's plenty of work to go around for everyone, I'd love to not get too hung up on quibbling over this one. Thanks!

**Comment by trjExpensify** [comment]
Okay cool, let's move on!

**Comment by trjExpensify** [comment]
Still held, Melv.

**Comment by mallenexpensify** [comment]
@Ollyws reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by trjExpensify** [comment]
Yep!

**Comment by stitesExpensify** [comment]
On hold, moving this to weekly while we wait.

**Comment by trjExpensify** [comment]
Ah sorry, forgot to drop it to `weekly`. Thanks! 

Still held on https://github.com/Expensify/App/pull/34498

**Comment by trjExpensify** [comment]
Okay so #34498 has merged. Taking this off hold. We should be good to proceed here now @Krishna2323.

**Comment by trjExpensify** [comment]
PR hit staging 15 hours ago.

**Comment by NikkiWines** [comment]
@trjExpensify can you issue payment, please? Thank you 🙇

**Comment by trjExpensify** [comment]
Payment summary: 

@Krishna2323 paid $500 for the fix 
@Ollyws offer sent for $500 for the review

**Comment by trjExpensify** [comment]
Paid, closing. Thanks, everyone!
