### ISSUE TITLE
Android - Composer - Area below composer flickers when collapsing composer that has long paragraph

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31298
## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Paste the following paragraph into the composer:
Ever since Google took away free unlimited storage on Google Photos, I knew I’d have to figure out a way to keep my ever-growing photo library slim and lean. Google’s existing tools are a passable point to get started, but they lack important context. That’s why I’m very excited to get my hands on Google Photos’ new photo stacks, which are supposed to group similar photos taken at roughly the same time in a stack much like Top Shot does. While this is primarily intended to make it easier to scroll through your library, it will also make it much easier to pick a single great shot and discard the rest.Ever since Google took away free unlimited storage on Google Photos, I knew I’d have to figure out a way to keep my ever-growing photo library slim and lean. Google’s existing tools are a passable point to get started, but they lack important context. That’s why I’m very excited to get my hands on Google Photos’ new photo stacks, which are supposed to group similar photos taken at roughly the same time in a stack much like Top Shot does. While this is primarily intended to make it easier to scroll through your library, it will also make it much easier to pick a single great shot and discard the rest
4. Expand the composer
5. Collapse the composer

## Expected Result:
There will be no flickering issue when collapsing the composer

## Actual Result:
The area below the composer flickers when it is collapsing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/006a1387-feb6-4261-bef4-1a0624b35a8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by situchan** [comment]
No one assigned here?
🎀 👀 🎀 to get engineer to handle this

**Comment by situchan** [comment]
Happy to take this as C+

**Comment by greg-schroeder** [comment]
Okay sure, assigning @situchan

**Comment by dangrous** [comment]
@greg-schroeder are you able to see if you can reproduce and if so get this out as `Help Wanted`? Let me know if you need anything from me.

**Comment by greg-schroeder** [comment]
Actually I don't think this necessarily fits into any of our current waves, so I'm going to close this.
