### ISSUE TITLE
 IOU - App crashes when Employee click "Show more" on created Split expense details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32299]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB> Request money
2. Enter an amount and continue
3. On the participant selection - Click split next to a workspace
4. Click on "Show more"
5. Select a category
6. Create the expense
7. Click on created expense to open details
8. Click on "Show more"

## Expected Result:
Details page should be open with no errors and crashes

## Actual Result:
App crashes when Employee click "Show more" on created Split expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4967ab5-2a13-4aa8-aa6d-99951077c3c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Looking at this now

**Comment by luacmartins** [comment]
I think that came from [this PR](https://github.com/Expensify/App/pull/31380), but that's already in production

**Comment by luacmartins** [comment]
Yea, crash also happens in production. Gonna remove the blocker label and work on a fix:

<img width="1442" alt="Screenshot 2023-11-30 at 3 43 43 PM" src="https://github.com/Expensify/App/assets/22219519/9cf8f178-797b-4066-affe-2a5780d8d134">

**Comment by luacmartins** [comment]
hmm I can't reproduce in dev

**Comment by luacmartins** [comment]
Yea, categories are not saving for split transactions with a workspace in dev. Not sure why.

**Comment by jjcoffee** [comment]
@bfitzexpensify I reviewed the PR for this issue. It should be due for payment as the PR [hit production](https://github.com/Expensify/App/pull/32323#issuecomment-1843658069) Dec 6. Thanks! :bow:

**Comment by bfitzexpensify** [comment]
Cool, offer sent.

**Comment by jjcoffee** [comment]
@bfitzexpensify Accepted, thanks!

**Comment by bfitzexpensify** [comment]
All paid out
