### ISSUE TITLE
[$500] Personal details - Invalid "Zip / Postcode" for Devonshire Square

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Navigate to Profile -> Personal details -> Address
4. Type "Devonshire" in the "Address line 1" field
5. Tap on the suggested "Devonshire Square"
6. Tap on the "Save" button

## Expected Result:
"Zip / Postcode" for Devonshire Square or the field validation for "Address line 1" should be corrected to allow the flow.

## Actual Result:
Invalid "Zip / Postcode" for Devonshire Square. I'm not able to proceed with the suggested data.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/63467b6d-b8f1-4c38-bf92-4030393b9fd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f66af36a9900f34</li>
        <li>Upwork Job ID: 1730337352559480832</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
Actually, this bug is easy to reproduce
Just write the name of any city district
As a result, we will only receive part of the postcode
Which is logical

Currently we use `address` as the type
Which, in addition to specific addresses, also supports the name of districts for which there is no specific building
As a result, we get only part of the postcode which is typical for this district

https://developers.google.com/maps/documentation/places/web-service/supported_types

**Comment by nikosamofa** [comment]
@isabelastisser I meant [here](https://github.com/Expensify/App/issues/32306#issuecomment-1834625495) that we cannot fix this on the app side.

**Comment by isabelastisser** [comment]
@nikosamofa can you please clarify what you recommend? Do we need to close it or assign an Expensify engineer?

**Comment by isabelastisser** [comment]
Thanks! Closing!
