### ISSUE TITLE
[$500] mWeb - Chat - User can't upload PDF files (unexpected error)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Navigate to any chat
4. Tap on the composers "+" button
5. Tap on the "Add attachment" button
6. Tap on the "Media" button
7. Select any PDF from your Google Drive

## Expected Result:
User should be able to upload a PDF from Google Drive.

## Actual Result:
User can't upload PDF files (unexpected error)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ad3ddd2e-4b1f-4f04-82c5-ef62ce0723be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff5e8b515fb793e2</li>
        <li>Upwork Job ID: 1730339324558475264</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by irtza46** [comment]
To address the PDF file upload issue, the solution involves a systematic approach. After analyzing the problem and setting up a mirrored React Native environment, I will conduct a thorough code review, utilizing debugging tools to pinpoint the error source. The solution includes rigorous platform-specific testing, robust error-handling implementation, and code optimization for enhanced performance.

Documentation updates will ensure transparency and integration into Expensify's staging environment will facilitate comprehensive testing. Continuous post-implementation monitoring will allow for prompt issue resolution, aligning with Expensify's development guidelines for a comprehensive and effective solution.

**Comment by irtza46** [comment]
To address the PDF file upload issue, the solution involves a systematic approach. After analyzing the problem and setting up a mirrored React Native environment, I will conduct a thorough code review, utilizing debugging tools to pinpoint the error source. The solution includes rigorous platform-specific testing, robust error-handling implementation, and code optimization for enhanced performance.

Documentation updates will ensure transparency and integration into Expensify's staging environment will facilitate comprehensive testing. Continuous post-implementation monitoring will allow for prompt issue resolution, aligning with Expensify's development guidelines for a comprehensive and effective solution.

Your Expensify account email: irtza46@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017513a3a2f63a0236

**Comment by giltron** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On Android in the Chrome browser,  Android's native file chooser is shown and the google drive files are selectable.  
However when selecting a file an error occurs.


### What is the root cause of that problem?

The google drive files are not accessbile.  The JS receives a file object but will throw an error ERR_UPLOAD_FILE_CHANGED when trying to read the file.

This is a google chromium bug: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1063576


### What changes do you think we should make in order to solve the problem?

We cannot solve the google drive file upload error but can offer a more informative and helpful error message to the user before they upload a file or after the specific error is thrown.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by lschurr** [comment]
Could you review the proposals @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment]
Hi, Yes. Will review the proposals in my morning

**Comment by abdulrahuman5196** [comment]
@lschurr There isn't any proposals to review actually. 
The only proposal here https://github.com/Expensify/App/issues/32308#issuecomment-1835362947 suggests this is issue is a known chromium bug which is unsolvable.

Was this actually working previously at some time?

**Comment by irtza46** [comment]
### Proposal
Hello @abdulrahuman5196 @lschurr,

I propose to resolve this issue and join your amazing team. Please consider my proposal and give me a chance. The solution involves a systematic approach to address the PDF file upload issue. After analyzing the problem and setting up a mirrored React Native environment, I will conduct a thorough code review, utilizing debugging tools to pinpoint the error source. The solution includes rigorous platform-specific testing, robust error-handling implementation, and code optimization for enhanced performance.

Documentation updates will ensure transparency and integration into Expensify's staging environment will facilitate comprehensive testing. Continuous post-implementation monitoring will allow for prompt issue resolution, aligning with Expensify's development guidelines for a comprehensive and effective solution.

My Expensify account email: [irtza46@yahoo.com](mailto:irtza46@yahoo.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~017513a3a2f63a0236

**Comment by lschurr** [comment]
Just clarifying @abdulrahuman5196 - are you saying that this isn't a bug with our app so we should close?

**Comment by lschurr** [comment]
Bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
@lschurr As far as the only proposal mentioned its not solvable. So I wanted to check if the issue was working sometime before in the app or if the mentioned issue was never working?

**Comment by lschurr** [comment]
I'm not sure @abdulrahuman5196 - could you start a conversation in Slack about this?

**Comment by abdulrahuman5196** [comment]
Got it will start a slack thread today

**Comment by abdulrahuman5196** [comment]
Created a slack thread here - https://expensify.slack.com/archives/C01GTK53T8Q/p1702977819646559

**Comment by AmjedNazzal** [comment]
I don't think we can do anything about this, you can try uploading pdf from drive to outlook new message or even an online pdf viewer, as long as it's from Android mweb, it will fail as well.

**Comment by lschurr** [comment]
Alright, going to close since this doesn't seem like a solvable issue for our end.
