### ISSUE TITLE
[$500] Private notes - Note editor opens instead of list for user with existing private notes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32302]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31344
## Action Performed:
Precondition: There is a chat with some content in the Privates notes and the note is not visited before. If visited, please log out and log in again
1. Go to staging.new.expensify.com
2. Open the chat from the precondition
3. Click on the header
4. Click Private notes

## Expected Result:
User is navigated to private note list screen

## Actual Result:
User is navigated to private note editor instead of private note list screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f5c6ab80-2132-417a-b48d-9f54941681c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1540c07c23a34c8</li>
        <li>Upwork Job ID: 1730368222515441664</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
@lanitochka17, can you elaborate what you mean by this,
> Open the chat from the precondition

whats do you mean by precondition?

Also i tested the private notes on a DM and a group chat and it seemed to work fine for me on staging chrome. Can you double check?
Meanwhile I'll ping the authors of https://github.com/Expensify/App/pull/31344 to double check as well.

**Comment by chiragsalian** [comment]
Asked authors in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1701379988966789?thread_ts=1701378635.293939&cid=C01GTK53T8Q)
Asked QA [here](https://expensify.slack.com/archives/C9YU7BX5M/p1701382945660829).

![image](https://github.com/Expensify/App/assets/14356145/291cf24c-198c-45f9-a346-165906c5518b)

I don't see any issue so I've asked others to confirm. If the issue does infact persist we can revert https://github.com/Expensify/App/pull/31344 but i'd like to confirm it first before reverting.

**Comment by chiragsalian** [comment]
i removed the job posting from upwork because it was created by accident, this issue is about fixing a logic with a very recent PR.

**Comment by DylanDylann** [comment]
I am working on it

**Comment by jjcoffee** [comment]
Found a possible regression whilst [testing](https://github.com/Expensify/App/pull/31257#issuecomment-1855876502) for https://github.com/Expensify/App/pull/31257. If you go offline before the `GetReportPrivateNote` request completes, the notes page still loads but is always empty (even when there are notes saved).

**Comment by DylanDylann** [comment]
@jjcoffee 
> the notes page still loads but is always empty

- What is the "notes page" that you mentioned? (Currently, we have two  page, "notes list" page and "notes edit" page

**Comment by jjcoffee** [comment]
Apologies, forgot to attach a video. It's the notes list page (I think), but we get navigated to the edit page (incorrectly):

https://github.com/Expensify/App/assets/27287420/280c3991-4896-467c-9810-8a7dd5a1bcc7

**Comment by DylanDylann** [comment]
@jjcoffee 
- Do you have any suggestions in this case? Because if the getReportPrivateNote is not called successfully, we will navigate user to edit note page as expected.
- My suggestion is that, BE will return the private note data when in the OpenReport API.

**Comment by DylanDylann** [comment]
@jjcoffee Can you help check this one https://github.com/Expensify/App/issues/32302#issuecomment-1857599642 once you have a chance

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by jjcoffee** [comment]
@DylanDylann I'm not sure I fully understand your comment or if you are proposing a particular solution, but I think it's up to the C+ on this issue to handle regressions. cc @ArekChr

**Comment by DylanDylann** [comment]
@jjcoffee Maybe @ArekChr is not available

**Comment by mallenexpensify** [comment]
QA, for retesting, here's a vid example
https://github.com/Expensify/App/issues/32302#issuecomment-1857581195

@shubham1206agra , yes, I'll assign you as C+ if the bug persists after more testing.  Did you try to reproduce?
