### ISSUE TITLE
[payment due 2023-12-13] [$500] Remove sideloading of Onyx data for avatar with display name

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32309]
Coming from https://github.com/Expensify/App/issues/27262

# Problem
These methods are anti-patterns because they are most always used for loading data into a component without using `withOnyx()`. This breaks the data flow of a react application. (data is coming from somewhere that is not props or state and cannot be debugged in react dev tools).

# Solution
Switch all references to properly use `withOnyx()` for components and `connect()` for libs.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c108d0b3568a69c3</li>
        <li>Upwork Job ID: 1730343269382967296</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
PR is in review.

**Comment by joekaufmanexpensify** [comment]
PR went to prod on 2023-12-06, so payment due on 2023-12-13 (assuming no regressions)

**Comment by joekaufmanexpensify** [comment]
@cubuspl42 offer sent for $500!

**Comment by cubuspl42** [comment]
@joekaufmanexpensify Thanks, accepted

**Comment by joekaufmanexpensify** [comment]
All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
@cubuspl42 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
Closing as this is all set!
