### ISSUE TITLE
[HOLD for payment 2024-01-18] [DISTANCE] LOW: UpdateDistanceRequest 1:1:1 - UpdateMoneyRequestBillable - Split out into its own command

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32310]
There will be three pieces to this:
- Auth: Using the logic from `EditMoneyRequest`, create a new command called `UpdateMoneyRequestBillabe` following the example in https://github.com/Expensify/Auth/pull/8986
- Web-E: Add a new API endpoint called `UpdateMoneyRequestBillabe` following the example in https://github.com/Expensify/Web-Expensify/pull/39445
- App: Implement the new API command following the example in https://github.com/Expensify/App/pull/30737
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01384414fb594d70a3</li>
        <li>Upwork Job ID: 1730347404278726656</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I started on a draft PR. Will continue tomorrow.

**Comment by luacmartins** [comment]
Auth and Web-E PRs in review

**Comment by luacmartins** [comment]
Back from ooo. Will work on it this week.

**Comment by twisterdotcom** [comment]
@luacmartins and @tgolen this is $500 is it? Issue doesn't say.

Also @c3024 - see no name on your GitHub account. Could you share your profile for me please?

**Comment by c3024** [comment]
@twisterdotcom 

Here is my Upwork profile

https://www.upwork.com/freelancers/~0105555e2f227dbf47

**Comment by luacmartins** [comment]
>@luacmartins and @tgolen this is $500 is it? Issue doesn't say.

Yea, I think this is the standard amount

**Comment by twisterdotcom** [comment]
Payment Summary:

@c3024 paid $500 via Upwork [here](https://www.upwork.com/nx/wm/offer/100520754) (C+)
