### ISSUE TITLE
[HOLD] [MEDIUM] [Groups] Frontend: Remove Group DMs from the App code

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#32319]
[Group Chats Design Doc](https://docs.google.com/document/d/1NcklRh6NogUWhKL0J5udTE8bok3_9ZoZ57JTllP-QJg/edit)

Once we completely migrate all Group DMs in the db we can stop supporting them in the App code. This is largely a clean up task and whoever picks it up will need to check for outdated code related to or mentioning group DMs.

**Comment by arielgreen** [comment]
Moving to weekly just so Melvin doesn't keep closing.
