### ISSUE TITLE
[HOLD for payment 2024-02-01] [DISTANCE] LOW: UpdateDistanceRequest 1:1:1 - UpdateMoneyRequestCategory - Split out into its own command

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32313]
There will be three pieces to this:
- Auth: Using the logic from `EditMoneyRequest`, create a new command called `UpdateMoneyRequestCategory` following the example in https://github.com/Expensify/Auth/pull/8986
- Web-E: Add a new API endpoint called `UpdateMoneyRequestCategory` following the example in https://github.com/Expensify/Web-Expensify/pull/39445
- App: Implement the new API command following the example in https://github.com/Expensify/App/pull/30737
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4f5d787ed69a0f1</li>
        <li>Upwork Job ID: 1730346834719158272</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
I wasnt able to get to this but discussed with nikki and she is interested in moving this forward so reassigning to her.

**Comment by NikkiWines** [comment]
Planning on tackling this during the week

**Comment by NikkiWines** [comment]
Working on UpdateMoneyRequestDescription but tackling this tomorrow!

**Comment by NikkiWines** [comment]
- [ ] Auth PR: https://github.com/Expensify/Auth/pull/9601 in review
- [ ] Web PR: https://github.com/Expensify/Web-Expensify/pull/40414 HELD on auth PR 
- [ ] App PR: https://github.com/Expensify/App/pull/34073 HELD on web PR

**Comment by slafortune** [comment]
Offer sent @jjcoffee  - https://www.upwork.com/nx/wm/offer/100724377

**Comment by jjcoffee** [comment]
@slafortune Offer accepted, thanks!

**Comment by slafortune** [comment]
Paid out to @jjcoffee - no other payments needed 👍
