### ISSUE TITLE
[HOLD for payment 2024-01-17] [DISTANCE] LOW: UpdateDistanceRequest 1:1:1 - UpdateMoneyRequestTag - Split out into its own command

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32312]
There will be three pieces to this:
- Auth: Using the logic from `EditMoneyRequest`, create a new command called `UpdateMoneyRequestTag` following the example in https://github.com/Expensify/Auth/pull/8986
- Web-E: Add a new API endpoint called `UpdateMoneyRequestTag` following the example in https://github.com/Expensify/Web-Expensify/pull/39445
- App: Implement the new API command following the example in https://github.com/Expensify/App/pull/30737
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01307ca29530c2a1a3</li>
        <li>Upwork Job ID: 1730347003188379648</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by aldo-expensify** [comment]
@tgolen 👋 , I'm guessing that for the Auth part we want to reuse this `MoneyRequest` class and add the `tag` when we load the transaction here:

https://github.com/Expensify/Auth/blob/0c3ae5c2ee23daf8aada8a4c4c13eba896544a75/auth/lib/MoneyRequest.cpp#L30-L50

does that sound correct?

**Comment by aldo-expensify** [comment]
Made the [Web-E](https://github.com/Expensify/Web-Expensify/pull/40007) and [Auth PR](https://github.com/Expensify/Auth/pull/9399) ready for review. I'm going to work on finishing the [App PR](https://github.com/Expensify/App/pull/32769) now

**Comment by Santhosh-Sellavel** [comment]
@aldo-expensify Can you help with BZ Checklist here? 

Also can you assign a BZ here?

**Comment by aldo-expensify** [comment]
Added `Bug` to get a `BugZero` member

**Comment by aldo-expensify** [comment]
Not overdue, payment period still open

**Comment by anmurali** [comment]
@Santhosh-Sellavel I have run through the payment checklist https://github.com/Expensify/App/issues/32312#issuecomment-1896237423. You can request via ND.

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/32312#issuecomment-1896237423).
