### ISSUE TITLE
[HOLD for payment 2024-01-03] [DISTANCE] LOW: UpdateDistanceRequest 1:1:1 - UpdateMoneyRequestAmount - Split out into its own command

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32316]
There will be three pieces to this:
- Auth: Using the logic from `EditMoneyRequest`, create a new command called `UpdateMoneyRequestAmount` following the example in https://github.com/Expensify/Auth/pull/8986
- Web-E: Add a new API endpoint called `UpdateMoneyRequestAmount` following the example in https://github.com/Expensify/Web-Expensify/pull/39445
- App: Implement the new API command following the example in https://github.com/Expensify/App/pull/30737
 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ac3360c28900621</li>
        <li>Upwork Job ID: 1730344637166800896</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by luacmartins** [comment]
Gonna continue to work on this today

**Comment by situchan** [comment]
There was [regression](https://github.com/Expensify/App/issues/33587)

**Comment by miljakljajic** [comment]
Seems like the seven day hold for the regression is up - am I good to issue the 50% payment?

**Comment by miljakljajic** [comment]
Payment summary:

@akinwale is owed $250 for their role reviewing this issue. Please request payment in NewDot.

**Comment by akinwale** [comment]
> Payment summary:
> 
> @akinwale is owed $250 for their role reviewing this issue. Please request payment in NewDot.

@miljakljajic I am not yet eligible for payment on NewDot. I still receive payments through Upwork.

**Comment by miljakljajic** [comment]
Apologies @akinwale - please accept the offer I just sent in Upwork.

**Comment by akinwale** [comment]
@miljakljajic Accepted. Thanks!

**Comment by miljakljajic** [comment]
Paid :)
