### ISSUE TITLE
"Post a Slack message when any platform fails to build or deploy" job is broken

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#32321]
## Problem

https://github.com/Expensify/App/actions/runs/7046660590/job/19179846343#logs

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/App/App/.github/actions/composite/announceFailedWorkflowInSlack'. Did you forget to run actions/checkout before running your local action?
```

### Solution

Add a checkout before calling local action
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba00b8e0fcb72b86</li>
        <li>Upwork Job ID: 1730362093700648960</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Hey @AndrewGable, seems like this one was all internal (including a review) -- is there anything to do here or can we close this out once it hits production?

**Comment by AndrewGable** [comment]
All good, we can close now
