### ISSUE TITLE
[$500] [HOLD for payment 2023-12-12] [Theme Switching Migration] 🐛 - Android Status Bar Insets is 0

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32343]
![Image](https://github.com/Expensify/App/assets/38015950/f70afe69-b391-49db-acf4-01d68bf6062c)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018740b40d87d64654</li>
        <li>Upwork Job ID: 1742256415787405312</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by grgia** [comment]
hey @muttmuure could you help me out with the $500 C+ review payment to @fedirjh?

**Comment by muttmuure** [comment]
Invited @fedirjh  to job

**Comment by muttmuure** [comment]
Offer sent

**Comment by muttmuure** [comment]
Paid
