### ISSUE TITLE
[$500] iOS - IOU - Request money interrupted and user get redirected to LHN when camera permission granted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user was denied camera permission
1. Open app
2. Sign In
3. Tap on FAB
4. Tap on Request Money
5. Select Scan tab
6. Tap on on Continue > Settings
7. Grant camera permission
8. Switch back to the app

## Expected Result:
Scan tab should be displayed

## Actual Result:
Request money interrupted and user get redirected to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/70d58eab-387c-4605-b504-28bc45b039be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197578b3b3b2b6e06</li>
        <li>Upwork Job ID: 1730599416486178816</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by fcrmlk** [comment]
I have a solution for this problem want to share proposal is the process is to submit solution in the comments ?

**Comment by fcrmlk** [comment]
Contributor details 
Your expensify account email: calistaring@gmail.com
Upwork profile link: https://www.upwork.com/freelancers/~01c17cdef240e56875

**Comment by adelekennedy** [comment]
@rushatgabhane what do you think of @ishpaul777 comment [here](https://github.com/Expensify/App/issues/32357#issuecomment-1836251612)? I think I agree that it's not a bug today but would be more of a feature request/larger change?
