### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Personal details - "State / Province" isn't filled for the suggested Hungarian address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Navigate to Profile -> Personal details -> Address
4. Type any Hungarian street name for Address line 1 ("Arany János utca" or "Galamb utca")
5. Tap on the suggested street
6. Tap on Save

## Expected Result:
"State / Province" should be filled

## Actual Result:
"State / Province" isn't filled for the suggested Hungarian address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2626a4ec-ae79-4dcf-a406-59caecea99b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fbe3afc2abfb075</li>
        <li>Upwork Job ID: 1730597469143244800</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28052709</li>
<li>abzokhattab | Contributor | 28052710</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
"State / Province" isn't filled for the suggested Hungarian address
### What is the root cause of that problem?
The root cause is that Galamb utca doesn't have state(administrative_area_level_1).
So longStateName will be empty string.
### What changes do you think we should make in order to solve the problem?
we need to check if the address has state or not

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by puneetlath** [comment]
@aimane-chnaif thoughts on this issue?

**Comment by puneetlath** [comment]
We discussed internally and it'll be challenging to make it optional depending on location as it's not easy to know which regions it should/shouldn't be optional in. So given that it should be very rare to have a region like this, let's go with the solution of filling the city in the state/province field when there is no state.

**Comment by abzokhattab** [comment]
The PR is ready.

**Comment by puneetlath** [comment]
I think it's fine to leave it as-is. I don't think we need to make the logic more complicated for this rare case.

**Comment by puneetlath** [comment]
All paid. I don't think we need to do the checklist for this. It's just a scenario that no one previously considered. Thanks everyone!
