### ISSUE TITLE
[$500] Room - Copy to clipboard and pasting specific email id in compose displays hidden

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a room
3. Enter @[applausetester+kh29082@applause.expensifail.com](mailto:applausetester+kh29082@applause.expensifail.com)
4. Send the message
5. Long press the email id under invited
6. Select copy to clipboard
7. Paste it in compose

## Expected Result:
When user copy to clipboard the specific email id @[applausetester+kh29082@applause.expensifail.com](mailto:applausetester+kh29082@applause.expensifail.com)
and paste in compose, the email id must be displayed and hidden must not be shown

## Actual Result:
When user copy to clipboard the specific email id @[applausetester+kh29082@applause.expensifail.com](mailto:applausetester+kh29082@applause.expensifail.com)
and paste in compose, instead of email id, (invited @Hidden)hidden is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b2cbd98-d6e3-44f9-b166-81cdb447a062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f515a586c761272</li>
        <li>Upwork Job ID: 1730600808644747264</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by narefyev91** [comment]
@anmurali can we put this on hold until https://github.com/Expensify/App/pull/32161 will be done?

**Comment by anmurali** [comment]
Held on https://github.com/Expensify/App/pull/32161

**Comment by anmurali** [comment]
Held on https://github.com/Expensify/App/pull/32161

**Comment by anmurali** [comment]
@narefyev91 - https://github.com/Expensify/App/pull/32161 is on production. I am taking this off hold.

**Comment by anmurali** [comment]
Bumped @narefyev91 on Slack for this issue.
