### ISSUE TITLE
[$500] Expense rule - Tags can not be selected when Employee create Expense rule

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
1. On Old dot Admin should create a tag called "Test Tag"
Steps:
1. On OldDot - Login as the employee
2. Navigate to Account Settings > Expense Rules
3. Try to select "Test Tag"
admin: [applausetester+gmcategory1@applause.expensifail.com](mailto:applausetester+gmcategory1@applause.expensifail.com)
employee: [applausetester+gmcategory1@applause.expensifail.com](mailto:applausetester+gmcategory1@applause.expensifail.com)

## Expected Result:
Tag dropdown should be selectable

## Actual Result:
When click on Tag field - empty dropdown list opens. User can not see "Test Tag"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddde5a6eeb482175</li>
        <li>Upwork Job ID: 1730596418626617344</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by SpLouk** [comment]
Can external contributors access the Expensify Stackoverflow? I have not seen anything in the contributing guidelines about how to gain access.

**Comment by p-hitesh** [comment]
Contributor details
Your Expensify account email: hitesh44111@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0143cbafce457c37fd

**Comment by slafortune** [comment]
@lanitochka17 I am not able to recreate this - 

<img width="981" alt="image" src="https://github.com/Expensify/App/assets/11725910/dc83be36-dcee-4e3c-aad0-f3f14fda1734">


Logging into [applausetester+gmcategory1@applause.expensifail.com](https://www.expensify.com/_support/?supportEmail=applausetester%2Bgmcategory1%40applause.expensifail.com&comment=better%20supportal%20issue%20nubmer%3A%2032354&location=_support/) there isn't a tag called test at this time.
