### ISSUE TITLE
Standardize on type-only imports

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#32368]
Slack context: https://expensify.slack.com/archives/C01GTK53T8Q/p1701371123201489

### Problem
We are inconsistent about how we import types. Type-only imports are preferred because they disappear at runtime, making the program more lightweight. It also improves code clarity because it's obvious that a type is being imported and not some other value.

### Solution
Enable the [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md) lint rule w/ `prefer: type-imports`

<details><summary>Issue Owner</summary>Current Issue Owner: @chrispader</details>

**Comment by chrispader** [comment]
@blazejkustra you wanted to take this one? Otherwise i can also open a PR :)

**Comment by blazejkustra** [comment]
@chrispader Sure, you can take it 😄

**Comment by chrispader** [comment]
Created the PR here: https://github.com/Expensify/App/pull/32475

**Comment by roryabraham** [comment]
We're waiting on an upstream PR from @chrispader here. This isn't very high priority, so I'm not opposed to just closing this out for now so it's not a distraction. Up to you @chrispader

**Comment by chrispader** [comment]
Starting to work on this now! Got some spare cycles..

cc @roryabraham @blazejkustra @fabioh8010

**Comment by chrispader** [comment]
Created an upstream issue: https://github.com/typescript-eslint/typescript-eslint/issues/8163

Once it is approved, i'm gonna start working on the implementation

**Comment by chrispader** [comment]
Turns out, we don't need an upstream change 🎉 There's a rule for enforcing type specifier style:

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/consistent-type-specifier-style.md

**Comment by chrispader** [comment]
@roryabraham i think we can merge this one :)

**Comment by roryabraham** [comment]
@chrispader what one? 😄 I already merged https://github.com/Expensify/App/pull/32475 last week.

That said, I think we can close this issue out since it was a compile-time-only change and we didn't use a C+ so no additional payments are due
