### ISSUE TITLE
[$500] Bank account - Auth SetupWithdrawalAccount returned an error when adding bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace
3. Go to Bank account > Connect online with Plaid
4. Proceed with Chase bank account
5. Enter all the information in Step 2 (Company information) and proceed to the next page

## Expected Result:
User is able to proceed to Step 3 of adding bank account

## Actual Result:
Auth SetupWithdrawalAccount returned an error when adding bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18165f6c-d440-4d30-84a5-b6cad6e8bcb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142f12197c340b838</li>
        <li>Upwork Job ID: 1731666235543633920</li>
        <li>Last Price Increase: 2023-12-04</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Nice, thanks closing this in favour of https://github.com/Expensify/App/issues/32386
