### ISSUE TITLE
 Workspace - Deleting a Workspace while offline crashes the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any account
3. Turn off internet
4. Go to Profile > Workspace > 3 dot menu in top right corner > Delete

## Expected Result:
User expects to be able to delete a WS while offline and the WS be crossed out

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb23f4d1-0d24-4cb1-8183-cd9289074a29

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
@tylerkaraszewski I think it's better to revert #31518 and let them rework considering this regression as it was just component refactor, neither bug nor feature.

**Comment by yuwenmemon** [comment]
Revert was CP'ed to staging. Closing this out!
