### ISSUE TITLE
[HOLD for payment 2023-12-15] Stub for Expensify/Expensify/issues/329101 / Auto-switch to #focus mode App changes

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#32372]
See https://github.com/Expensify/Expensify/issues/329101
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b91e885c3489a3ea</li>
        <li>Upwork Job ID: 1730673965042880512</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Assigning a BZ to help with payment eventually.

**Comment by miljakljajic** [comment]
Weird - @laurenreidexpensify is already assigned, is this a Melvin bug?

**Comment by miljakljajic** [comment]
Sent you a contract @hoangzinh - accept it and I'll get you paid right away!

**Comment by miljakljajic** [comment]
Lovely, paid! Thank you for your work.

Do we need regression test steps for this one @marcaaron or are we good?

**Comment by marcaaron** [comment]
Yeah! Probably a good idea. I haven't added any to test rail yet.
