### ISSUE TITLE
[HOLD for 31909][$500] Task – Impossible click the checkbox to Complete the task as user B in 1:1 DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to a 1:1 conversation with a user
4. Click on the + in the compose box and select "Assign task"
5. Enter a Title and press Next/ Confirm task
6. Login as user B of this conversation
7. Find newly created task and click the checkbox to Complete the task

## Expected Result:
It is possible click the checkbox to Complete the task as user B in 1:1 DM

## Actual Result:
Impossible click the checkbox to Complete the task as user B in 1:1 DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec7d7481-66f6-40a5-9856-6d6e63fcdcde

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cd4de2ef7be60b7</li>
        <li>Upwork Job ID: 1730710175306096640</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
Related to https://github.com/Expensify/App/issues/31909

**Comment by lschurr** [comment]
Could you review the proposal here @c3024?

**Comment by c3024** [comment]
[This](https://github.com/Expensify/App/issues/31909#issuecomment-1828339553) from #31909 might fix this as well.

The proposal suggestion is fine for toggling the checkmark but does not fix the bug of task completion. This needs to be fixed from backend. I think we should hold this till #31909 gets fixed.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by c3024** [comment]
#31909 is closed. This is fixed as well. The other user should not be able to check the task. This is expected behaviour.


https://github.com/Expensify/App/assets/102477862/0489188b-7cbb-4526-bebe-746d2803e4d6

This issue can be closed.

@lschurr
