### ISSUE TITLE
Android - Chat - Input can be seen when emoji picker is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Tap the input and then emoji picker
4. Select any emoji
5. Open the emoji picker again

## Expected Result:
The input is not seen

## Actual Result:
The input can be seen on the bottom overlapped by the emoji picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Android 0112](https://github.com/Expensify/App/assets/78819774/f191fb5a-ef5a-485f-9cb9-65c9853d8d78)

https://github.com/Expensify/App/assets/78819774/3991e9c3-bf7c-4acc-9770-8c1ef2eeff94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Fixed by #32335

![Screenshot (Dec 4, 2023 12_08_14 PM)](https://github.com/Expensify/App/assets/2838819/026d51ba-117e-4bda-81f7-fc29ceb91ae9)
