### ISSUE TITLE
[$500] Wallet - No feature list is displayed in Wallet page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32152
## Action Performed:
Pre-requisite: user must be logged in and no accounts or wallet should have been connected
1. Go to Settings > Wallet

## Expected Result:
If no BA or wallet has been connected, the feature list should be displayed

## Actual Result:
No feature list is displayed in Wallet page even if no account or wallet has been connected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b67f289-f540-4ba4-b3ea-d4d264a05055

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f8c06a2b5c9f051</li>
        <li>Upwork Job ID: 1730706873964122112</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by grgia** [comment]
> If no BA or wallet has been connected, the feature list should be displayed

Now that all users have wallets, we will no longer show the empty state.  This is not a bug but by design @burczu @Krishna2323

**Comment by Christinadobrzyn** [comment]
awesome! Thanks @burczu! I'll close without action based on https://github.com/Expensify/App/issues/32385#issuecomment-1837404836
