### ISSUE TITLE
[$500] Chat  - 'Next step' appears when there is no more action to perform after paying request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace
- Employee has requested money in the workspace chat
1. Log in to ND as the admin
2. Go to the workspace chat with the employee from the precondition
3. Click on the preview
4. Pay the request

## Expected Result:
'Next step' will not appear when there is no more action to perform after paying the request

## Actual Result:
'Next step' still shows up when there is no more action to perform after paying the request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/28949715-a0d3-4120-93e4-74a5434cf181

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a66a3a5d4d7d0ba9</li>
        <li>Upwork Job ID: 1730704419654553600</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
@parasharrajat @miljakljajic This will be fixed with https://github.com/Expensify/App/pull/28976.
I think you can close this one out

**Comment by miljakljajic** [comment]
Thank you, closing!
