### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Room - Error shows up when saving existing and valid room name with any changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Start chat > Room.
3. Create a room with a valid name.
4. Go to the room > Click header > Settings.
5. Click Room name.
6. Click Save without any edit.

## Expected Result:
Room name is saved successfully as the existing room name is valid.

## Actual Result:
Error shows up when saving existing valid room name with any changes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/81e05d4a-e78d-4c94-8c6c-d30064cbddd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106db335debd1ea53</li>
        <li>Upwork Job ID: 1731637112209268736</li>
        <li>Last Price Increase: 2023-12-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue is not reproduced on production

https://github.com/Expensify/App/assets/93399543/2a3c4d6d-e079-4f05-8002-c824ecaf4f90

**Comment by nkuoch** [comment]
Privileging @kowczarz to do the fix as he is the author of the [original PR](https://github.com/Expensify/App/pull/30996). 
If he can't do it in time, we can go with @ishpaul777. 
If @kowczarz ends up using @ishpaul777 's [proposal](https://github.com/Expensify/App/issues/32398#issuecomment-1837192947), we can pay @ishpaul777 25% (so $125).

**Comment by kowczarz** [comment]
Hello, I'm working on fix right now.

**Comment by nkuoch** [comment]
Yes!

**Comment by luacmartins** [comment]
@kowczarz we'll revert the PR since it caused multiple blockers. Merging small fixes will make it harder to revert if we need to. That way we can also go on with the deploy and fix the issues without rushing it.

**Comment by yuwenmemon** [comment]
Revert deployed so removing the blocker label.

**Comment by Santhosh-Sellavel** [comment]
No payments due as this was a regression & the PR caused this got reverted. We are good to close!

**Comment by luacmartins** [comment]
Sounds good. Thanks everyone!

**Comment by nkuoch** [comment]
I think so, but let's wait for the new PR to be ready to be reviewed, tested and approved first. So we can make sure the solution worked.
