### ISSUE TITLE
Room - Inconsistent error message when entering [[<<> in the room name field 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team_
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Start chat > Room.
3. Click Create room without entering room name.
4. Type [[<<> (don't copy paste) in the name field.

## Expected Result:
The error message for invalid room name should be consistent.

## Actual Result:
The error message for invalid room name is not consistent.
The error message changes from "Room names can only include lowercase letters, numbers and hyphens" to "Invalid characters" when typing [[<<>.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/842c4f1f-e183-438a-8bb4-167e6c0d41c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproduced on Production

https://github.com/Expensify/App/assets/93399543/f30b571d-5518-45bb-b074-e917950b9df1

**Comment by shubham1206agra** [comment]
Offending PR https://github.com/Expensify/App/pull/30996
But I think the implementation of PR is correct
This is a problem with the validation of `Form` and `FormProvider`

**Comment by kowczarz** [comment]
There were some changes in form validation in old `Form` component during the migration and not all changes were included in the new `FormProvider`. It is fixed in this commit https://github.com/Expensify/App/pull/32432/commits/b9fc2f4b464f81c286f2e8ab9905625a8b8797fd

**Comment by yuwenmemon** [comment]
Revert deployed so closing this out!
