### ISSUE TITLE
[$500]  Web - Error message when adding the following snippet in consol

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32063
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Add the following snippet to the render function of Expensify.js
useEffect(() => {
let theme = 'dark';
setInterval(() => {
const newTheme = theme === 'dark' ? 'light' : 'dark';
theme = newTheme;
// eslint-disable-next-line rulesdir/prefer-actions-set-data
Onyx.set(ONYXKEYS.PREFERRED_THEME, newTheme);
}, 3000);
}, []);

## Expected Result:
No error message when adding the following snippet in consol

## Actual Result:
Error message when adding the following snippet in consol

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  
![Bug6298049_1701471148454!image__185_](https://github.com/Expensify/App/assets/78819774/c6874732-8748-46ea-99a3-05cdd2152de4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199201fc753179511</li>
        <li>Upwork Job ID: 1730730531051917312</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by grgia** [comment]
Not a bug, the code was not a console snippet.
