### ISSUE TITLE
[HOLD Expensify 308026][$500] Offline messages will still post to archived workspace chat when coming online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Same account is logged in on two devices.
- There is a workspace in the account.
1. [Device A] Go offline.
2. [Device A] Send a few messages to the workspace chat.
3. [Device B] Delete the workspace.
4. [Device A] Go online.

## Expected Result:
The offline changes made in the workspace will not be saved.
The changes made in offline will have a red dot next to them with a message below saying ""This chat room has been deleted"".

## Actual Result:
The messages are still sent despite the workspace is deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fdd2a1bb-0426-4153-9c76-85c83e3afc6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01479c44876cd0c3db</li>
        <li>Upwork Job ID: 1730979601000124416</li>
        <li>Last Price Increase: 2023-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by junsupark94** [comment]
I think this should be fixed in the backend. 

From what I can see from the frontend codebase, when a Workspace (Report) is deleted/archived, it simply changes its Status to 2. Doing this will hide the interface for sending, editing, and deleting messages (ie. create more ReportActions). But I'm guessing there's no check on the status in the backend.

Looking at the Report type, it doesn't seem to log when its status changes. If it did, then we could filter out ReportActions that was created after the Report status was changed to 2.

**Comment by shubham1206agra** [comment]
This looks like a backend issue. Let's get an engineer for this.
🎀 👀 🎀 C+ reviewed

**Comment by kpadmanabhan** [comment]
> This looks like a backend issue. Let's get an engineer for this. 🎀 👀 🎀 C+ reviewed

@MelvinBot : please point me to the backend repo.

**Comment by strepanier03** [comment]
Thanks for the [heads](https://github.com/Expensify/App/issues/32409#issuecomment-1837457541) up @shubham1206agra - I'll move this internal now.

**Comment by strepanier03** [comment]
On pause until this is picked up internally.

**Comment by puneetlath** [comment]
Going to un-assign myself from this as I already have other wave/vip work assigned.

**Comment by strepanier03** [comment]
Moving this to weekly since it's Low priority. Please feel free to update labels as needed when priority changes.

**Comment by strepanier03** [comment]
Moved to Medium priority but no other update at this time.

**Comment by strepanier03** [comment]
Back to Low so I'll update the title.

**Comment by strepanier03** [comment]
No update yet.

**Comment by strepanier03** [comment]
Low priority for the time being, no update.

**Comment by strepanier03** [comment]
Low priority - I'm changing this to weekly so I don't have to update it every day.

**Comment by strepanier03** [comment]
Low priority, waiting for pickup once higher priority items are finished or someone has a proposal.

**Comment by quinthar** [comment]
Great find.  I'm reassigning this to Wave5 as this relates to workspace chats.

**Comment by neil-marcellini** [comment]
That PR is going to solve this already, so I'm going to take this over so we don't duplicate effort. I let @rlinoz know via DM too.

**Comment by neil-marcellini** [comment]
Moving to weekly since it's on hold

**Comment by neil-marcellini** [comment]
The backend fix was deployed, and it looks like it's working well. The error messages aren't great, but this is an edge case, so it's fine.


https://github.com/Expensify/App/assets/26260477/241d97d4-7687-416a-9c4b-02cdbc89f97a
