### ISSUE TITLE
Android - Profile -The title text and time displayed on phone overlapped and looks misaligned.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a 1:1 report
3. Tap on header
4. Tap on profile image

## Expected Result:
The title text and time displayed on phone must be clearly visible and aligned properly without any overlapping.

## Actual Result:
he title text and time displayed on phone overlapped and looks misaligned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f8c92003-b4dc-43c7-9fcc-e78c87140f31

![Screenshot_20231202-021844_New Expensify](https://github.com/Expensify/App/assets/93399543/ff68ce9e-5632-4fac-a913-680fb560f046)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproduced on production

![IMG_20231202_122824](https://github.com/Expensify/App/assets/93399543/14f40a6e-2651-4808-966b-04225a54e84d)

**Comment by AndrewGable** [comment]
Fixed by https://github.com/Expensify/App/pull/32335

![Screenshot (Dec 4, 2023 11_58_26 AM)](https://github.com/Expensify/App/assets/2838819/810e391c-3ec5-424d-9077-401a9c999fed)
