### ISSUE TITLE
[$500] LHN shows "paid $20.00 elsewhere" when payment was made using Expensify

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction (blocked adding bank account)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701478696189209

## Action Performed:
1. Split charge with many users, where each owe me $20
2. User pays me money using Expensify
3. LHN shows user "paid $20.00 elsewhere"
4. Once clicked the message in LHN the text updates to "paid $20.00 using Expensify"

## Expected Result: 
Original text to show "paid $20.00 using Expensify"

## Actual Result: 
Original text in LHN shows "paid $20.00 elsewhere"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/26aee255-d66c-4639-92b6-f9b0abfcbcb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdadadda11763ce7</li>
        <li>Upwork Job ID: 1731728629187862528</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Was able to recreate so getting eyes on this!

**Comment by junsupark94** [comment]
Is there a way to simulate paying with Expensify without using a real bank account?

**Comment by mallenexpensify** [comment]
@junsupark94 , can you check #expensify-open-source to see if there's info in there?  If not, can you ask your question there?  Thx

**Comment by CortneyOfstad** [comment]
Still not overdue, just waiting on proposals

**Comment by trjExpensify** [comment]
Why would this bug not be considered part of the P2P VIP? I think it's necessary we ensure that the payment method is accurately reflected wherever it's displayed. It looks like that might have regressed in a couple of places. Here we can see the reverse where the request preview component reads `Paid elsewhere` when the iouReport was `paid using Expensify` 

<img width="970" alt="image" src="https://github.com/Expensify/App/assets/16232057/d73b1e9d-608e-4d2c-8689-ab5894e67e8d">

**Comment by mallenexpensify** [comment]
Posted about here https://expensify.slack.com/archives/C01SKUP7QR0/p1702429240032229
But was thinking it might be wave 5.  I think you're recommendation is better @trjExpensify , thanks for chiming in

**Comment by mountiny** [comment]
In the PR above, I am updating the money request copy to just say `Paid`. The other issue here is that it seems the pusher updates do not reflect in time/ or not at all until fetched in the LHN

**Comment by CortneyOfstad** [comment]
Sounds good @mountiny — thank you!

**Comment by mountiny** [comment]
This can be closed now
