### ISSUE TITLE
[HOLD for payment 2024-01-02] Create new command for Payment cancelling in "Paid in Expensify" reports

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#32427]
**Problem**
Currently, we have no way to revert an existing payment in NewDot. This is part of our core functionality and something we should be able to do.

**Solution**
Let's add that functionality as discussed [here](https://github.com/Expensify/Expensify/issues/327308). Once we have it for "Paid Elsewhere" we need to expand it for "Paid in Expensify" reports.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f33337b0d8b040ed</li>
        <li>Upwork Job ID: 1731662547311939584</li>
        <li>Last Price Increase: 2023-12-04</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@Gonals is there any front-end aspect to this or is this purely back-end?

**Comment by puneetlath** [comment]
It looks like @Ollyws wasn't involved in the PR, so no payment is needed for anyone here. Let me know if I'm mistaken in that. Otherwise, @Gonals I think you can just go ahead and close the issue.
