### ISSUE TITLE
Feature Request: Custom welcome message should appear replacing the default one

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701632059593009

## Action Performed:
1. Create a room in workspace 
2. Open the settings of the room and set a welcome message

## Expected Result:
Should replace the default welcome message and custom message is sent to anyone who joins the first time in a whisper

## Actual Result:
Custom message didn't appear in the actual description

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (3)](https://github.com/Expensify/App/assets/38435837/a47d0f57-0b51-456b-b0cd-072477ee85f5)

![image (2)](https://github.com/Expensify/App/assets/38435837/43e62bf8-9544-4056-9677-9ec8dc645a83)

https://github.com/Expensify/App/assets/38435837/ba331962-fd36-44ef-9f56-2bbc3e418f65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
This is currently being scoped out [in an internal Slack channel](https://expensify.slack.com/archives/C066HJM2CAZ/p1701743812576919).

**Comment by conorpendergrast** [comment]
The problems and solution have now been proposed in [another internal channel](https://expensify.slack.com/archives/CC7NECV4L/p1702001845470919)

**Comment by conorpendergrast** [comment]
Ok, looks like this has been replaced with https://github.com/Expensify/App/issues/32954 and https://github.com/Expensify/App/issues/32953. Closing out!
