### ISSUE TITLE
[HOLD for payment 2023-12-18] Remove sideloading of Onyx data forMoneyRequestView.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#32443]
Coming from https://github.com/Expensify/App/issues/27262

# Problem
These methods are anti-patterns because they are most always used for loading data into a component without using `withOnyx()`. This breaks the data flow of a react application. (data is coming from somewhere that is not props or state and cannot be debugged in react dev tools).

# Solution
Switch all references to properly use `withOnyx()` for components and `connect()` for libs.

**Comment by tgolen** [comment]
@trjExpensify Can you please help here with the payouts?

@Santhosh-Sellavel needs to be paid for [a C+ review](https://github.com/Expensify/App/pull/32446#issuecomment-1843461593)

**Comment by trjExpensify** [comment]
Bump @Santhosh-Sellavel have you requested?

**Comment by tgolen** [comment]
Bump @Santhosh-Sellavel to accept request.

**Comment by Santhosh-Sellavel** [comment]
Feel free close this one, I'll request on ND later this week!

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/32443#issuecomment-1861579084).
