### ISSUE TITLE
Unsubmitted expense report is missing the empty state image

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Needs reproduction 
**Reproducible in production?:** Needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701700778110689

## Action Performed:
Create an expense on a workspace that is not submitted yet
## Expected Result:
 The expense report should have the empty state at the top of the chat
## Actual Result:
No empty state
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2023-12-04 at 09 38 35@2x](https://github.com/Expensify/App/assets/38435837/d42de1c1-cf20-4f40-867e-5f30d500557f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
@shawnborton I'm not able to reproduce this one, so let me know if you're still seeing it.

**Comment by shawnborton** [comment]
Cool, can't seem to reproduce either but will keep an eye out for it.
