### ISSUE TITLE
[HOLD PR #32124] Spinner appears at the bottom when scroll up 1/2 of the page and scroll back down

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698623055435299

## Action Performed:
1. Open a chat with lots of messages
2. Scroll up like 1/2 of a page then scroll back down

## Expected Result:
There should not be a spinner at the bottom 

## Actual Result:
There is a spinner at the bottom. Getting tons of log lines of API activity. Plus it seems to make the chat "jump around" a bit when the spinner appears/disappears.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

[api call activity.txt](https://github.com/Expensify/App/files/13554040/api.call.activity.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
@janicduplessis is this related to the below? 
- https://github.com/Expensify/App/pull/31288
or
- https://github.com/Expensify/App/issues/30895

**Comment by janicduplessis** [comment]
@mallenexpensify I don't think so, @perunt I think this would be fixed by https://github.com/Expensify/App/pull/32124 right?

**Comment by mallenexpensify** [comment]
Thanks @janicduplessis and @perunt .  I put this on hold pending PR #32124 .   @stephanieelliott , once that PR has hit production, can you retest to confirm the bug is still reproducible?

**Comment by stephanieelliott** [comment]
> https://github.com/Expensify/App/pull/32124 has hit production! @m-natarajan, can you restest this to see if it is still reproducible?

bump @m-natarajan

**Comment by stephanieelliott** [comment]
Tested this myself, this is no longer reproducible!

**Comment by mallenexpensify** [comment]
Also just tried to reproduce in Chrome on production, in #social room and BIG chat I have with Deeter and wasn't able to
