### ISSUE TITLE
[HOLD for payment 2023-12-18] [Theme Switching] create hook for StyleUtils

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32472]
@chrispader

**Comment by shubham1206agra** [comment]
Commenting here as reviewer

**Comment by grgia** [comment]
@stephanieelliott  could you help make sure that the $500 C+ review payment is paid to both @shubham1206agra and @allroundexperts  for https://github.com/Expensify/App/pull/32498

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor+: $500, extended job on Upwork, @allroundexperts can you please accept it?
 - Contributor+: $500, extended job on Upwork, @shubham1206agra  can you please accept it?
 
 Upwork job is here: https://www.upwork.com/jobs/~1737876297360310272

**Comment by allroundexperts** [comment]
I get paid through the App @stephanieelliott. The summary you've written above should be enough for my payment!

**Comment by shubham1206agra** [comment]
Accepted

**Comment by stephanieelliott** [comment]
Oops, thanks @allroundexperts! 

@shubham1206agra you've been paid!

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on summary above.
