### ISSUE TITLE
[HOLD for payment 2023-12-15] [Theme Switching] CLEAN UP: Use consistent variable names for styles/themes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32476]
@chrispader

**Comment by grgia** [comment]
@laurenreidexpensify could you help ensure that the $500 C+ review payment is made to @parasharrajat for https://github.com/Expensify/App/pull/32287

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

C+ Review @parasharrajat $500 please request payment in NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
