### ISSUE TITLE
Room - Error "You can't rename the report of a free plan" when renaming the room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any room
3. Click on the room header > Settings
4. Click Room name
5. Rename the room and save it

## Expected Result:
User is able to rename the room

## Actual Result:
User is able to rename the room. The error "You can't rename the report of a free plan" shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4412b1d6-9b3a-4b2d-9c15-8ac323f26806

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
I think this is expected. @chiragsalian made the change here: https://github.com/Expensify/Web-Expensify/pull/39888

**Comment by johnmlee101** [comment]
Or at least to some degree, checking in if its necessary to have it apply to chats, otherwise should be an easy fix

**Comment by johnmlee101** [comment]
Have a easy fix ready if need be, but will wait on confirmation

**Comment by chiragsalian** [comment]
So here is the recent discussion - slack [post](https://expensify.slack.com/archives/C05DWUDHVK7/p1701284631084899?thread_ts=1701284451.710189&cid=C05DWUDHVK7).
> if the report is under a free policy then don’t allow report name edits in oldDot
> We should not support custom report naming on the Free plan.

But with that said in your video it looks like you are editing a policy room and its not allowing you to edit it. Thats odd. I guess we should update the code so that it allows chats room names to be updated. Do you have the fix ready @johnmlee101, i can review it if you send it my way?

**Comment by chiragsalian** [comment]
Btw this is not a blocker since the code effecting this is on web-e and its on production too.

**Comment by johnmlee101** [comment]
Working on a fire but will send you it

**Comment by johnmlee101** [comment]
sent!

**Comment by johnmlee101** [comment]
oh this is fixed.
