### ISSUE TITLE
[$500] The payment popup appears after refreshing the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#32483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:

1. Create an account, and add a free workspace
2. Add a reimbursement account to that workspace in NewDot
3. Add another reimbursement bank account via OldDot
4. In OldDot, create a report - it should show up as Processing, on the free workspace
5. Add a reimbursable expense
6. Reimburse (via ACH), selecting the bank account that you did NOT set up in NewDot

## Expected Result:
The payment popup appears without refreshing the page

## Actual Result:
The payment popup appears after refreshing the page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d0bf7683-c0f5-455b-b42e-0463293496f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd38f0c978e98f27</li>
        <li>Upwork Job ID: 1732056632125218816</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Hm, interesting! 

>Reimburse (via ACH), selecting the bank account that you did NOT set up in NewDot

@kavimuru - looking at the video repro, isn't this a moot point? You just select ACH and the pop up appears, there wasn't a choice either way. 

@luacmartins I have a feeling this might be pusher/ related to the freePlan bank account NVP. A newly added bank account via NewDot requires a refresh of the report screen on OldDot to be "recognised" to use for reimbursement it seems. 

With the changes to unravel that NVP; 1) do you think this issue will be resolved? 2) if not, is it worth moving this along now or after?

**Comment by luacmartins** [comment]
This seems pusher related. OldDot doesn't handle these updates so we need a refresh to pull the latest data. I don't think the NVP is an issue since we don't really use it in OldDot.

**Comment by luacmartins** [comment]
Yea, I think we can close it.
