### ISSUE TITLE
[HOLD on pull/32516] [$500] IOU - Receipt shows attachment icon when it is opened right after uploading a receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Click + > Request money > Manual
4. Create a manual receipt without receipt
5. Click on the IOU preview twice to open IOU details page
6. Click on the upload receipt window and upload a receipt
7. Right after uploading the receipt, click on the receipt
Note that it shows attachment icon while the receipt is loading

## Expected Result:
The receipt will show a spinner when it is loading

## Actual Result:
The receipt attachment icon while it is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7b47782-8820-43ba-9309-b209b8586cd4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2f18a17342b1055</li>
        <li>Upwork Job ID: 1732060054439260160</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by situchan** [comment]
Seems like regression from https://github.com/Expensify/App/pull/31467

**Comment by situchan** [comment]
Confirmed regression came from https://github.com/Expensify/App/pull/31467.
cc: @dukenv0307 @mananjadhav @mountiny 

Not happening on 0e3a005

<img width="1133" alt="regression" src="https://github.com/Expensify/App/assets/108292595/f717751e-0eb1-4cd8-90f0-0f616d8495e6">

**Comment by twisterdotcom** [comment]
Should we assign to @dukenv0307 to fix?

**Comment by situchan** [comment]
being reverted [here](https://github.com/Expensify/App/pull/32516) so I think we can close this after deploy to staging and verify fix
