### ISSUE TITLE
[$500] Chat - No gradient between the solid color and the image in the background

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32480]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/issues/32441
## Action Performed:
1. Go to staging.new.expensify.com
2. Open empty chat

## Expected Result:
There is color gradient between the solid color and the image in the background

## Actual Result:
There is no gradient between the solid color and the image in the background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![Bug6301423_1701754188129!287796215-1b50fda1-c13b-46e8-8d81-6932d003466b](https://github.com/Expensify/App/assets/78819774/b2395a6f-7f8a-436c-96e2-2b42df881b5c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dfe4315862c6710</li>
        <li>Upwork Job ID: 1732054463514398720</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
dupe https://github.com/Expensify/App/issues/32441

**Comment by allroundexperts** [comment]
🥲
