### ISSUE TITLE
Request–Replace receipt field appears again after finishing receipt replace, open/close receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in as the WS employee
2. Navigate to expense request conversation that has a receipt
3. Click on the receipt thumbnail
4. Verify there's a 3 dot menu on the top right
5. Click on replace
6. Upload a new receipt
7. Verify the new receipt is displayed in the request
8. Click on the receipt thumbnail
9. Click close the receipt thumbnail

## Expected Result:
The receipt thumbnail is closed and the new receipt is displayed in the request

## Actual Result:
Replace receipt field appears again after finishing receipt replace, open/close new receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d33b1a76-665f-4f79-8b84-fed6d1b2c9ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Closing this out then!
