### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Web - Conversation - Green line appear and remains when mark chat as unread and than mark it as read

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32509]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
While repro steps 2 & 3 User should navigate to other conversation
1. Navigate to staging.new.expensify.com
2. Right click on any conversation from LHN> Mark as unread
3. Right click on the same conversation from LHN> Mark as read
4. Open the conversation
5. Navigate to any other conversation
6. Come back to the conversation from step 2

## Expected Result:
Green line should no appear since User mark the conversation as Read

## Actual Result:
Green line appears when user mark conversation as Read, plus the green line does not disappear when user navigate to other conversations and came back to conversation mark as read, until refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8245977b-1c8c-4b68-bfe2-7ebc4f56cb55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01058d0b253ae5aa76</li>
        <li>Upwork Job ID: 1732115046498811904</li>
        <li>Last Price Increase: 2023-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28036172</li>
<li>tienifr | Contributor | 28036173</li>
</ul></li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
I'm catching up 👍

**Comment by cubuspl42** [comment]
@dukenv0307 Thank you for your proposal. It has a solid root cause analysis and a solution that would likely work

**Comment by cubuspl42** [comment]
I approve the proposal by @tienifr, as it makes the logic for handling "mark as read" and "mark as unread" consistent and symmetric

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
We're very close to merging!

**Comment by sonialiap** [comment]
@cubuspl4 please complete the checklist 🙏 https://github.com/Expensify/App/issues/32509#issuecomment-1884240856
