### ISSUE TITLE
Details - Instead of user name, incorrect title "Attachment" is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a group chat
3. Tap header display names
4. Tap on a profile icon

## Expected Result:
In profile page, user name / mail id must be displayed as title

## Actual Result:
In profile page, instead of user name, incorrect title "Attachment" is shown
This issue occurs in individual chat, room chat, group chat, workspace in all profile pages, incorrect title "attachment" displayed instead of user name/mail id

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/8e6ac07f-3a81-4659-8ef5-3916e226912b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
looking at this right now

**Comment by situchan** [comment]
The revert [PR](https://github.com/Expensify/App/pull/32516) was merged. Now fixed on main

**Comment by hayata-suenaga** [comment]
ah nice thanks for the info! 🙇
