### ISSUE TITLE
[$500] Login - Infinite loading when logging in to a specific account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with [applausetester+khcategory@applause.expensifail.com.](mailto:applausetester+khcategory@applause.expensifail.com.)

## Expected Result:
User is able to log in with the account

## Actual Result:
The page loads infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 
<img width="1440" alt="Bug6302289_1701804660848!Screenshot_2023-12-06_at_01 18 48" src="https://github.com/Expensify/App/assets/78819774/ea3cb7df-4677-4ebf-9aa0-240b793654d1">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197534925b6d26716</li>
        <li>Upwork Job ID: 1732124120979623936</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by mahesh-redwoods** [comment]
How would an external contributor was able to login with the specified mail? any support or replication of what that account is having. @lanitochka17 if possible can you share a recording of what is happening?

**Comment by miljakljajic** [comment]
Going to close this out unless anyone feels strongly otherwise.
