### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Desktop - WS Settings - Red dot appears after uploading a Workspace avatar when offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the testing app
2. Switch off the internet for the device
3. Click on your avatar > Workspaces
4. Select a workspace to upload an avatar
5. Click on the avatar and upload a picture
6. Click on Save

## Expected Result:
No error should appear after uploading the WS avatar

## Actual Result:
Red dot appears on the user avatar after uploading the workspace avatar when offline, though photo is uploaded successfully. No clear information given on the reason for the error
Red dot and error will be removed when user clicks on the 2nd Save button on WS settings modal. Issue does not happen when user is connected to internet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/69257bcc-eef7-4121-bf70-7fff1b299c90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165681605c06818ea</li>
        <li>Upwork Job ID: 1732118554945167360</li>
        <li>Last Price Increase: 2023-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28054418</li>
<li>bernhardoj | Contributor | 28054419</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@aimane-chnaif I can repro on Staging:

![image](https://github.com/Expensify/App/assets/30815269/cc268e1f-73a6-4834-a892-ded636633e6b)

>Red dot and error will be removed when user clicks on the 2nd Save button on WS settings modal.

@lanitochka17 I don't think this is clearly written. From what I see, when you go back online, the red dot doesn't disappear, so you have to then re-save the WS image to have it disappear.

I'd personally expect the `Save` to apply automatically when you go back online, therefore making the red dot disappear (i.e. no need to re-save)

**Comment by jliexpensify** [comment]
I'm on v1.4.10-0 and can't repro anymore. Please comment with a video if you can repro on this version @bernhardoj

**Comment by mallenexpensify** [comment]
Reopening for 👀 since @bernhardoj can reproduce and I might have reported a similar issue. 
https://github.com/Expensify/App/issues/32418#issuecomment-1847582175

**Comment by jliexpensify** [comment]
Thanks @mallenexpensify - we can handle in this GH and you can close yours as a dupe? 

@stitesExpensify bump for proposal review!

**Comment by mallenexpensify** [comment]
I'll put mine on hold to ensure that the fix here fixes mine too. Thx

**Comment by stitesExpensify** [comment]
@bernhardoj proposal lgtm

**Comment by jliexpensify** [comment]
Hi @fedirjh can you complete the checklist before payment is issued tomorrow? Thanks in advance!

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @bernhardoj $500
- C+: @fedirjh $500

[Upwork job](https://www.upwork.com/jobs/~0165681605c06818ea)

**Comment by jliexpensify** [comment]
Paid and job closed!
