### ISSUE TITLE
[$500] Chat - Account tester@applausecard.expensifail.com content is not loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Expensify App or go to staging.new.expensify.com
2. Login with account [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)

## Expected Result:
User can successfully log in with account [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)

## Actual Result:
Account [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
content is not loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cef8c81d-d69a-41f5-a82d-c4938b6a61d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196a53f9e45552d18</li>
        <li>Upwork Job ID: 1732143301462745088</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
Dupe 
https://github.com/Expensify/App/issues/32518

**Comment by joekaufmanexpensify** [comment]
Ah, yep. Closing in favor of that one. TY!
