### ISSUE TITLE
[$500] Move two "Referral Program" articles to new locations

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#32523]
## Background
Coming from [this conversation](https://expensify.slack.com/archives/C02QSAC6BJ8/p1701802815663259), we'd like to:

- [ ] Move [this article](https://help.expensify.com/articles/expensify-classic/getting-started/Referral-Program) to [this section](https://help.expensify.com/expensify-classic/hubs/get-paid-back/)
- [ ] Move [this article](https://help.expensify.com/articles/new-expensify/billing-and-plan-types/Referral-Program) to [this section ](https://help.expensify.com/new-expensify/hubs/get-paid-back/)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01606d8447f3213c9c</li>
        <li>Upwork Job ID: 1732131468667183104</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by maddylewis** [comment]
closed the upwork job

**Comment by rushatgabhane** [comment]
@maddylewis i don't think this should be paid. It didn't take me any time 😅
But I think we should document a HOW-TO guide for helpdot. What do you think?

**Comment by francoisl** [comment]
@jamesdeanexpensify friendly reminder for next time that some of these pages can be linked to from the backend or OldDot, so we also need to check if there are updates to make in our private repos too.

**Comment by jamesdeanexpensify** [comment]
Ah, I had no idea. Thank you for that!

**Comment by jamesdeanexpensify** [comment]
Are we OK to close this? The help articles ended up in slightly different areas by platform, but I think that's fine.

Expensify Classic: https://help.expensify.com/articles/expensify-classic/get-paid-back/Referral-Program
New Expensify: https://help.expensify.com/articles/new-expensify/payments/Referral-Program

**Comment by rushatgabhane** [comment]
Yes close the issue.
