### ISSUE TITLE
Desktop - Receipt - Receipt is downloaded with a broken file

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Create a Scan IOU
3. Open the IOU details view
4. Tap on the receipt > overflow menu > Download

## Expected Result:
The receipt should load as an image and the user should be able to open it

## Actual Result:
Receipt is downloaded with a broken file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ccd73219-d15e-4b37-af09-ce121a32c842

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production: 


https://github.com/Expensify/App/assets/78819774/78235ada-b227-4060-9524-8ef8a44949f0

**Comment by shubham1206agra** [comment]
Please CP this to fix https://github.com/Expensify/App/pull/31791

**Comment by shubham1206agra** [comment]
> you mean that this happens on staging but not happen on main thanks to #31791? 
Yes

> What's offending PR?
Unable to find. But still trying to find the offending PR

**Comment by robertjchen** [comment]
Since it's coming from https://github.com/Expensify/App/pull/31791, does that mean we need to revert it instead?

**Comment by robertjchen** [comment]
Got it, thanks for the clarification- I think we can CP #31791 for now 👍
