### ISSUE TITLE
[$500] Bank account - After adding VB account, tapping on card shows locked feature page for a second

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition : Must have a verified BA
1. Launch app
2. Tap profile icon
3. Tap Workspaces---Workspace
4. Tap Bank account and note added verified bank account
5. Tap back arrow in app
6. Tap card

## Expected Result:
After adding Verified Bank account, tapping on card must not show locked feature page for a second also

## Actual Result:
After adding Verified Bank account, tapping on card shows locked feature page for a second

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2fd18656-54dd-4f5d-8705-10c5e34b08be

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3a966505364f4b0</li>
        <li>Upwork Job ID: 1732203633096806400</li>
        <li>Last Price Increase: 2023-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28033542</li>
<li>dukenv0307 | Contributor | 28033543</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
Thanks for the proposal @dukenv0307 
Would you please add a video for the same?

**Comment by shubham1206agra** [comment]
I have thought about this. Let us go for @dukenv0307's [proposal](https://github.com/Expensify/App/issues/32539#issuecomment-1841983690) as `ReimbursementAccountPage` also has loading spinner, and it will be nice to have the same here too.

🎀 👀 🎀 C+ reviewed

**Comment by michaelhaxhiu** [comment]
Awaiting final approval from @techievivek

**Comment by techievivek** [comment]
Sorry for the delay, assigend the GH to @dukenv0307

**Comment by greg-schroeder** [comment]
Okay taking this from @michaelhaxhiu, lemme catch up

**Comment by greg-schroeder** [comment]
Looks like this wasn't paid but the Upwork job is closed. I'll create a payment issue to get that generated and pay you two out ASAP, apologies for the delay.

**Comment by greg-schroeder** [comment]
@dukenv0307 you already accepted your original offer so I just paid that. @shubham1206agra you can accept the new one and I'll pay that, then we're g2g. 👍
