### ISSUE TITLE
Deprecate the hasOutstandingIOU key on reports

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32565]
### Problem

We have been using the `hasOutstandingIOU` key to indicate that there is some active (ie processing or open) report linked to chat report or as a property on the money request report to indicate the same.

In case of IOU/expense report its however redundant as we know the state and status and total so we can derive if the report is active

In case of the parent chat reports (DM in case of IOU and workspace chat in case of expense report) we now have the `hasChildOutstandingRequest` property which indicates there is action required from the user.

The `hasOutstandingIOU` property now became redundant so we can remove it

### Solution

Lets remove this key from the App

- MoneyRequestAction [here](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/components/ReportActionItem/MoneyRequestAction.js#L125) on the parent chat report whether to show pending report action, I think we can change this to chatReport?.iouReportID instead because the report should only be linked if its outstanding
- [updateIOUReportOwner](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/IOUUtils.ts#L61) - can be removed
- in [optionsListUtils](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/OptionsListUtils.js#L501) - can be removed
- [getMoneyRequestReimburseableTotal](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/ReportUtils.ts#L1600) - can be removed
- [getMoneyRequestSpendBreakdown](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/ReportUtils.ts#L1622) - can be removed
- [getMoneyRequestReportName](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/ReportUtils.ts#L1716) - we can substitute it with checking for the report state and status to be 1, 1
    - I think will be updating this to handle the approved case to say approved  cc @marcochavezf 
- [SidebarUtils](https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/src/libs/SidebarUtils.ts#L306), can be removed
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ccb3eb4568689c3</li>
        <li>Upwork Job ID: 1732700650759397376</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by mountiny** [comment]
PRs to deprecate this in backend are ready and on hold for the app changes first

**Comment by rezkiy37** [comment]
Gut!
I am preparing a PR today.

**Comment by rezkiy37** [comment]
Still testing, just resolved unit tests. Going to open the PR tomorrow.

**Comment by cubuspl42** [comment]
Review in progress

**Comment by mountiny** [comment]
Payment handled here https://github.com/Expensify/App/issues/32281

**Comment by cubuspl42** [comment]
@mountiny Do we hold on anything in such case, or are we good to close this one?

**Comment by mountiny** [comment]
I need to clean this up in the backend but your payment can be handled already

**Comment by rezkiy37** [comment]
@mountiny, just carious any updates on this issue?

**Comment by mountiny** [comment]
I need to follow through on the PRs which were created in the backend as HOLD now

**Comment by mountiny** [comment]
This was done already
