### ISSUE TITLE
[Theme Switching] 🐛 Reupload background images that were compressed

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32563]
The background images were compressed, now that the path is ignored, we should reupload them. 

- [ ] `assets/images/empty-state_background-fade-dark.png`
- [ ] `assets/images/empty-state_background-fade-light.png`

**Comment by grgia** [comment]
@dannymcclain do you mind resending both light and dark mode versions of the background image?

**Comment by grgia** [comment]
@dannymcclain these two:
https://github.com/Expensify/App/blob/main/assets/images/empty-state_background-fade-light.png
https://github.com/Expensify/App/blob/main/assets/images/empty-state_background-fade-dark.png

**Comment by dannymcclain** [comment]
Sure! What's wrong with the current ones? Do these need to be PNGs or could they be SVGs? Sorry for all the questions. Here's a zip with everything (PNGs are at 4x to try to match the dimensions of the current ones as close as possible.)

[Chat Empty State Imgs.zip](https://github.com/Expensify/App/files/13587213/Chat.Empty.State.Imgs.zip)

Let me know if these do/don't work for ya!

**Comment by dannymcclain** [comment]
Ah dangit, I goofed these up ☝️. Forgot these need to have the transparent background. Please hold!

**Comment by dannymcclain** [comment]
Alright let's try again, sorry for the GH spam!

[Chat Empty State Images Transparent BG.zip](https://github.com/Expensify/App/files/13587303/Chat.Empty.State.Images.Transparent.BG.zip)

**Comment by grgia** [comment]
HAHA i was just grabbing these, thanks!!!

**Comment by dannymcclain** [comment]
[UPDATED chat background images.zip](https://github.com/Expensify/App/files/13588261/UPDATED.chat.background.images.zip)

Ok these should be correct. Latest color swatches. Transparent backgrounds. Goodness gracious. Let me know if these don't work!

**Comment by dannymcclain** [comment]
🫣 Can we call this one done? 😅
