### ISSUE TITLE
HelpDot - Clicking `Expensify Classic` brings you to main homepage instead of Expensify Classic category homepage

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#32579]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/337748
**Issue reported by:** @maddylewis 
**Slack conversation:** N/A

## Action Performed:
1. Head to https://help.expensify.com/
2. Click into `Expensify Classic` - https://help.expensify.com/expensify-classic/hubs/
3. Click any homepage category (ex: `Bank Accounts & Credit Cards`)
4. Click `Expensify Classic` in the LHN to return to the main, Expensify Classic homepage

## Expected Result:
When clicking `Expensify Classic` from a category page, I would expect to be returned to the Expensify Classic category homepage - https://help.expensify.com/expensify-classic/hubs/: 
<img width="1284" alt="image" src="https://github.com/Expensify/App/assets/38016013/55affa8e-a51f-435b-9e23-aece78ebc0be">

## Actual Result:
When clicking `Expensify Classic` from a category page, you're brought back to the main homepage where you're prompted to click `Expensify Classic` or `New Expensify` - https://help.expensify.com/:
<img width="1280" alt="image" src="https://github.com/Expensify/App/assets/38016013/370f92d7-fd01-4c24-835c-1e7c1cc84bce">

To get back to the Expensify Classic category homepage, you must click `Bank Accounts & Company Cards`, which to me, is unintuitive. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38016013/1f19d3c9-7e7d-448f-8336-e9e68df42b2f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
oh @MitchExpensify - kinda the perfect person to review this. 

while the current design is intentional, i think this is an area that could be improved to help navigate the site more intuitive overall. 

lmk your thoughts and then we can cc rushat to have a look if we want to move forward with a fix :)

**Comment by MitchExpensify** [comment]
Checking in on what you think about my take above, @maddylewis

**Comment by maddylewis** [comment]
chatting more with our tech writer, Ren, and he made the good point that the LHN that shows on the homepage menu is redundant since the categories are listed as icons on the homepage. this makes me think we should maybe eliminate the LHN altogether and only have a back button. 

the LHN should still exist once you're in an article so that you can click through the headings and subheadings easily. but the LHN when you're on the homepage and/or subcategory list seems redundant/not useful.

**Comment by maddylewis** [comment]
okok im going to move to weekly for now since we're not totally sure if this is a "bug" worth fixing atm.

**Comment by maddylewis** [comment]
im gonna close this for now
