### ISSUE TITLE
Update MoneyRequestPreview.js for violations

### ISSUE THREAD

**Issue by cead22** [Expensify/App#32571]
- [Design Doc](https://docs.google.com/document/d/1iGvpCoQ6Wt-i2wcpvaMKsWZRNs-oAsWoaS_nLue7_E0/edit)
- We need to update src/components/ReportActionItem/MoneyRequestPreview.js
    - Update the value of hasFieldErrors to check for props.transactions.violations in order to show the RBR
        - `const hasFieldErrors = TransactionUtils.hasMissingSmartscanFields(props.transaction) || TransactionUtils.hasViolations(props.transaction.transactionID);`
    - In getPreviewHeaderText we check for violations on the transactions, and display it using the dot separator
        - `violations = TransactionUtils.hasViolations(props.transaction.transactionID)`
```js
if (violations) {
    message += violations.length > 1 || props.translate(violations[0]).length > 15 ? (' • ' + translate('violations.reviewRequired') : `• ${props.translate(props.transaction.violations[0])}`;
}
```
    - Note: “Review Required” will be translated
        - EN: Review Required
        - ES: Necesita Revisión

UI Examples

Missing Category (Violation Name) | Review Required
---|---
<img width="495" alt="image" src="https://github.com/Expensify/App/assets/165133/029bb3b2-7412-416d-951d-1a8e9002cbe8">|<img width="395" alt="image" src="https://github.com/Expensify/App/assets/165133/5249c88a-802f-4463-bedc-1eef71c619a3">

@cdanwards @lindboe @trevor-coleman please comment so I can assign you

**Comment by cead22** [comment]
This is one is in the queue but Trevor is finishing other issues first

**Comment by cead22** [comment]
Same ^

**Comment by cead22** [comment]
Same update ^

**Comment by cead22** [comment]
Still a WIP, and Trevor is back tomorrow

**Comment by cead22** [comment]
WIP

**Comment by trevor-coleman** [comment]
Code is complete, beginning work on the PR.

**Comment by cdanwards** [comment]
Currently in review

**Comment by cead22** [comment]
@lschurr Can you please handle payment for @akinwale 's review of the [PR](https://github.com/Expensify/App/pull/33969)? Thanks

**Comment by akinwale** [comment]
@lschurr Automation seems to have missed this one. The [PR](https://github.com/Expensify/App/pull/33969) was deployed to production on [2024-02-26](https://github.com/Expensify/App/pull/33969#issuecomment-1965246526), so the payment due date is 2024-03-04, and it's currently one week overdue.

**Comment by lschurr** [comment]
Ah, thanks! I missed this one as well. I'll update and get this done today.

**Comment by lschurr** [comment]
[Offer sent](https://www.upwork.com/nx/wm/offer/101323441) @akinwale

**Comment by akinwale** [comment]
> [Offer sent](https://www.upwork.com/nx/wm/offer/101323441) @akinwale

Accepted. Thanks!

**Comment by lschurr** [comment]
Sorry about the delay on that one. Should be all good now. Closing this one out.
