### ISSUE TITLE
Bank account - The user is not seeing the connection flow view when selecting 'Connect online with Plaid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32596]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Set your avatar to custom avatar
4. Set your WS to custom avatar
5. Go to Expense report
6. Request Money

## Expected Result:
The user is seeing the connection flow view when selecting 'Connect online with Plaid like in production

## Actual Result:
The user is not seeing the connection flow view when selecting 'Connect online with Plaid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d4c3394b-44f7-46e8-b050-4ddacc926ef9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/ca7f10ce-2978-4a88-9bf3-e699d13570d1

**Comment by shubham1206agra** [comment]
This is not a deploy blocker.
This is happening as the staging server uses sandbox token and production uses production token for plaid.
If you want the same UI, maybe check the plaid configuration from your side.

**Comment by hayata-suenaga** [comment]
[confirming that Plaid flow doesn't work on the staging environment](https://expensify.slack.com/archives/C01GTK53T8Q/p1701967907873459). After confirmation, we can close this issue.

**Comment by hayata-suenaga** [comment]
I think this is expected. closing the issue
