### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500][Dupe Detection] Surfacing Potential Duplicates

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#32607]
## Part of the <Project Name> project
Main issue: https://github.com/Expensify/Expensify/issues/307591
Doc section: Surfacing Potential Duplicates
Project: [Wave: Collect Approvers] Dupe Detection

## UI

![image](https://github.com/Expensify/App/assets/6474442/a5385392-9d8f-4ded-8976-0a0ad194f41e)

## Feature Description

Update the comment type [here](https://github.com/Expensify/App/blob/main/src/types/onyx/Transaction.ts#L43) since this can be a single string or a full array containing different transactions NVPs. In this case, it looks like this:

![image-2024-04-08 10_51_27 803](https://github.com/Expensify/App/assets/6474442/e6c8348a-84fc-4d1f-afeb-c1d4c06f21ad)

The HOLD doc implemented the logic to display the HOLD notification for each expense. You can see the details [here](https://github.com/Expensify/App/issues/31300). However, we need to make the following changes to update the HOLD notification in case it is duplicated.

- Add a new function called `TransactionUtils.isDuplicate(transactionID, checkDismissed)` that will check if there is an existing duplicate violation for the given transactionID and has been dismissed:

    - Listen to the transactionViolations_* Onyx key. Remember the key looks like this:
    ![image](https://github.com/Expensify/App/assets/6474442/bd787302-ab90-4392-8490-f2742b2fd137)

    - Check if the duplicatedTransaction key is set in the above Onyx key for the transaction and return true only if the following condition is not met: 

        - Since the violation could have been dismissed, check if the corresponding transactions_* key contains an entry for the current user:
        ![image-2024-04-08 10_51_27 803](https://github.com/Expensify/App/assets/6474442/e6c8348a-84fc-4d1f-afeb-c1d4c06f21ad)

- Add a new condition to `ReportUtils.isOnHold` to see if the transaction is a duplicate by calling TransactionUtils.isDuplicate(transactionID, true).

- In `components/ReportActionItem/MoneyRequestView.js` in the View for the HOLD banner:

    - Check if the transaction has any duplicates by checking the corresponding Onyx key transactionViolations_*. If so, replace the `props.translate('iou.requestOnHold')` for `props.translate('iou.requestDuplicate')` that contains the message defined in the screenshot at the beginning of the issue (asked me for the Spanish translations).

    - If there are duplicates, add a new `<Button>` to review duplicates. Don't navigate anywhere for now but eventually it will do the following:

        - Navigate the user to the route for a new page ReviewDuplicate

        - Pass the threadReportID of the transaction in the route to the new page.

# Manual Test Steps

![image](https://github.com/Expensify/App/assets/6474442/de11f585-e088-4c39-bd9f-fd96f0bc3f51)

![image](https://github.com/Expensify/App/assets/6474442/80e707c3-ddef-403c-8a96-01ddba08cfc3)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dc734e5d5fc1a3f</li>
        <li>Upwork Job ID: 1778425579213647872</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by pecanoro** [comment]
@MelvinBot Well Melvin, we are prioritizing this again, so reopening!

**Comment by MitchExpensify** [comment]
Will this ultimately be internal or external @pecanoro ?

**Comment by pecanoro** [comment]
@MitchExpensify Ideally external, but I am trying to wrap up the back-end first.

**Comment by pecanoro** [comment]
@MitchExpensify Assigning you back as BZ member since we are opening this one to contributors

**Comment by EzraEllette** [comment]
I'd want to submit a proposal, but I would like more context beforehand. Do you have a working link for the main issue?  https://github.com/Expensify/Expensify/issues/307591 is broken.

**Comment by EzraEllette** [comment]
This feature will update transaction holding functionality to include duplicate transactions. If a report is a potential duplicate, display a button to review the duplicate reports.


## What is the root cause of that problem?
Some people send in multiple reports for the same expense.

## What changes do you think we should make in order to solve the problem?
use the transactionViolations_* Onyx key for a report and see if it is contained as a duplicate and violation is not dismissed.
Display the UI if it is a duplicate report.

**Comment by pecanoro** [comment]
https://github.com/Expensify/Expensify/issues/307591 is an internal issue and sadly I can't share the design doc. However, I can answer any questions you might have. I just noticed you are working on a PR already and new contributors are only allowed to be assigned to one issue until it’s merged. After that, you can apply to different open issues, not restricted to one at a time.

**Comment by pecanoro** [comment]
Because of the above, assigning @gijoe0295, please don't hesitate to let me know if anything was unclear!

**Comment by pecanoro** [comment]
Done! You should have access now

**Comment by pecanoro** [comment]
Two transactions on the same expense report that have the same date, currency, amount and merchant should trigger it. Does it show in the violations key in Onyx?

**Comment by MitchExpensify** [comment]
not overdue, actively being worked on

**Comment by pecanoro** [comment]
I will check what's going on tomorrow with the violations, I ran out of time today

**Comment by pecanoro** [comment]
Great question! Let me ask internally in Slack!

**Comment by pecanoro** [comment]
@gijoe0295 They were still discussing yesterday, but let me bump the conversation! Thanks for the reminder

**Comment by pecanoro** [comment]
It seems we want to say `Cash [dot] Duplicate [dot] Hold` for when we hold due to violations!

**Comment by pecanoro** [comment]
Hmm, I need you can remove that part since it's not supported in the back-end either

**Comment by pecanoro** [comment]
> @pecanoro One more question, should this view be shown to other workspace members (including admins, auditors) or just exclusive to the IOU creator?

Admins and the the creator of the expense should be able to review duplicates

**Comment by MitchExpensify** [comment]
Reminder set to pay, do we need BZ steps here @akinwale ?

**Comment by akinwale** [comment]
> Reminder set to pay, do we need BZ steps here @akinwale ?

@MitchExpensify Yes, we do. I'll post them shortly. Also, please note the PR was initially deployed to production 2024-06-11, so the correct payment due date should be 2024-06-18.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure  the new feature will work correctly on production in further releases.

**Regression Test Steps**
_Prerequisites_
* Control workspace with `Expense Violations` enabled
* Account is an employee member of Control workspace and violations are enabled for the account
* `Use staging server` on if testing on dev

1. Launch the Expensify app.
2. Login as a member of the Control workspace.
3. Submit 2 expenses with the same amount (avoiding limit violations), currency, merchant and date to the workspace.
4. Navigate to the workspace chat where the expense was created.
5. Open the expense report.
6. Verify that each expense preview has a red dot indicator and `Cash · Duplicate · Hold` at the top
7. Open any one of the transactions in the expense report.
8. Verify that the `HOLD` banner is displayed at the top.
9. Verify that the text, `This expense has the same details as another one. Review the duplicates to remove the hold.` is displayed.
10. Verify that a `Review duplicates` button is displayed. Clicking or tapping the button does nothing at the moment.

Do we agree 👍 or 👎?

**Comment by MitchExpensify** [comment]
Paid and contracts ended!
