### ISSUE TITLE
[HOLD for payment 2024-03-26] [Actionable System Messages] [HOLD on E/E #347391] [$500] [MEDIUM] Pay a report on OldDot, the system message for payment never appears in NewDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32602]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701876923291429

## Action Performed:
1.  Make sure you’re on a Collect or Control policy
2. Create a report with several requests on NewDot
3. Go to OldDot, pay the report

## Expected Result:
The system message for payment appears no matter where payment is mad.

## Actual Result:
No system message every appears on the NewDot report.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/70dc5fd5-4504-46b2-9074-9e66ede6f090

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183dc4f8cde297006</li>
        <li>Upwork Job ID: 1732552019063586816</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Not overdue. Awaiting proposals.

**Comment by twisterdotcom** [comment]
Asking about the related Wave here: https://expensify.slack.com/archives/C05DWUDHVK7/p1702593632408119

**Comment by twisterdotcom** [comment]
Still awaiting proposals. Adding to wave5-free-submitters following Slack outcome. @dylanexpensify I put this in MEDIUM.

**Comment by Victor-Nyagudi** [comment]
I can't interact with reports in OD because of outdated billing information. What should I update it to?

For context, I tried submitting the report below and got this message. 

![Screenshot 2023-12-19 at 13 56 48](https://github.com/Expensify/App/assets/79470910/d9135554-df15-48c3-bc30-bc1817b0c22b)

**Comment by Victor-Nyagudi** [comment]
I suspect a back end issue. 

I'm not seeing any network activity on ND when a money request is reimbursed on OD. No change in Onyx either. 

The system message does appear below the header, though, after refreshing the page. It's just not the standard system message that appears along with other messages. 

![expensify-reimbursed-system-messgae](https://github.com/Expensify/App/assets/79470910/138ac988-eeb7-4198-9c33-57f9ba18d2ac)

**Comment by twisterdotcom** [comment]
@thesahindia is @Victor-Nyagudi right and should this be internal?

**Comment by Beamanator** [comment]
I'm jumping in to help with this one

**Comment by Beamanator** [comment]
> Make sure you’re on a Collect or Control policy

This should actually go in wave6 most likely

**Comment by Beamanator** [comment]
Ok so problems to fix:
1. When reimbursing via OldDot, the system message doesn't show up immediately (it needs a refresh)
2. The system message shows "**<admin>** has marked these expenses as **reimbursed** outside of Expensify. Reach out to them with any questions." but when you "pay elsewhere" via NewDot, you see "**You** have marked these expenses as **paid** outside of Expensify." as the system message
3. The `MARKEDREIMBURSED` report action doesn't show in NewDot

**Comment by Beamanator** [comment]
PR 1 merged! Next PR = sending the report action LIVE

**Comment by Beamanator** [comment]
2nd PR is live, but we're still technically discussing a follow-up issue here: https://github.com/Expensify/App/issues/34051

**Comment by sophiepintoraetz** [comment]
@Beamanator - does this solution only cover this specific reportaction or is it more general?

**Comment by Beamanator** [comment]
Hmm do you have any other examples I can look into? It shoulddd cover all of these cases - https://github.com/Expensify/App/issues/32602#issuecomment-1871592082

**Comment by sophiepintoraetz** [comment]
This one here https://github.com/Expensify/App/issues/34783 @Beamanator!

**Comment by Beamanator** [comment]
Aah ok @sophiepintoraetz , yeah no that case won't be solved by my changes here

**Comment by Beamanator** [comment]
Ok I guess we need to reset to figure out where this is at, I lost track of it b/c it had been on `Reviewing` for a while so didn't look overdue in my k2 😳

**Comment by twisterdotcom** [comment]
Discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1708705771011849

**Comment by twisterdotcom** [comment]
Hopefully get this PR in this week and we can start on the actionable framework and reportAction migration plan after that.

**Comment by twisterdotcom** [comment]
No payments or tests required for this one. Handling all in https://github.com/Expensify/App/issues/36023#issuecomment-2008308732
