### ISSUE TITLE
Connect BA - An error message appears if the entered address contains a digit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32604]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Connect bank account -> Plaid or manually
4. Continue the process to the Company information page
5. In the company address field enter some address that contains any digit or choose it from drop-down -> Save

## Expected Result:
The input field allows you to enter both letters and digits

## Actual Result:
An error message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32512408-71ad-414e-bbcd-d2f1d90ed217

![Bug6303811_1701906763641!image__187_](https://github.com/Expensify/App/assets/78819774/59f73466-dea0-48dc-a070-65650ce79ae7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
https://github.com/Expensify/App/pull/32609
