### ISSUE TITLE
Endless spinner after creating a new Collect workspace in OldDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701739580190259

## Action Performed:

1. Log into test account, ie. expensifail.com
2. Settings > Workspaces > click "Workspace" button in upper right
3. Click `Select` button under "Collect"

## Expected Result:
New workspace to be created and page to navigate to it (or to the list of workspaces)
## Actual Result:
Endless spinner shows, have to refresh page to get back to list of workspaces
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (5)](https://github.com/Expensify/App/assets/38435837/de818945-09b3-45c1-b75c-feea6f866ec7)

https://github.com/Expensify/App/assets/38435837/2b7b7014-7d4c-4c89-b0f7-3bb66bbd175f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Left a comment in the thread but I cannot repro @mallenexpensify.

I'm assuming you've tried a clean sign out and cleared cache/cookies etc?

**Comment by mallenexpensify** [comment]
Can't repro
