### ISSUE TITLE
Paying an invoice on OldDot, the “Expensify Wallet” option appears twice cc

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction ( I don't have account with expensify wallet)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701886466885259

## Action Performed:
Precondition: should have an Expensify Wallet, 
1.  Find an invoice to pay
2. When you get to the payment options screen, you’ll see two “Expensify Wallet” options and should only see one.
## Expected Result:
 You should only see one “Expensify Wallet” option

## Actual Result:
You see two “Expensify Wallet” options

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (6)](https://github.com/Expensify/App/assets/38435837/6506a38d-1f01-4057-ace5-73a1cf84285e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
Also discussed here: https://github.com/Expensify/Expensify/issues/335366

**Comment by Beamanator** [comment]
Fix should be up, can you check again @miljakljajic ? 🙏

**Comment by miljakljajic** [comment]
@jamesdeanexpensify can you check this is working correctly now? We can't access functioning wallets in the UK

**Comment by jamesdeanexpensify** [comment]
Damn, I don't have an invoice to pay any more. @HaleyJacobson this is a long shot but do you know of any invoices that might have recently been sent by accountspayable@expensify.com to an Expensify employee based in the US (but not paid yet)?

We just need someone to confirm that [this bug](https://github.com/Expensify/App/issues/32603#issue-2029621415) is no longer. Thank you!

**Comment by HaleyJacobson** [comment]
like an invoice to be paid by the concierge team or like an accidental employee charge on their cc that we have to invoice them for to pay us back?

**Comment by jamesdeanexpensify** [comment]
I think the latter should work. We just want a US employee to click into an unpaid invoice and show us the payment options to make sure their Expensify Wallet doesn't appear twice as an option. Does that make sense? That's the bug!

**Comment by HaleyJacobson** [comment]
ok try R00bFRP2MBgl which is an invoice to @greg-schroeder

**Comment by HaleyJacobson** [comment]
oh he JUST paid it - let me find another

**Comment by HaleyJacobson** [comment]
R00Fp4KpwnC5 for Monte

**Comment by greg-schroeder** [comment]
Oh hi - I just did this and I didn't see anything showing twice

**Comment by jamesdeanexpensify** [comment]
OK sweet - maybe we can use @MonteExpensify as the final test case. 

Monte - it sounds like you have an invoice to pay to Expensify (of course, I don't know the details and don't need to). We're just testing if there's still a bug when you go to pay the invoice. Are you able to screenshot the options you have to pay your invoice when you get a chance? Specifically, we're looking to see if the Expensify Wallet option shows up twice. Thanks!

**Comment by Beamanator** [comment]
Anyone able to test? 😅 \

**Comment by jamesdeanexpensify** [comment]
Just DM'd Monte to see if he can take a screenshot for us!

**Comment by MonteExpensify** [comment]
I already paid the invoice :/ so sorry!

I checked on both mobile and web.

**Comment by jamesdeanexpensify** [comment]
@HaleyJacobson anyone else for this? We just want a US employee to click into an unpaid invoice and show us the payment options to make sure their Expensify Wallet doesn't appear twice as an option.

**Comment by HaleyJacobson** [comment]
Try @grgia R00a1rOxbZUN

**Comment by HaleyJacobson** [comment]
and/or @arielgreen R00M5o5eAAf6

**Comment by grgia** [comment]
<img width="489" alt="image" src="https://github.com/Expensify/App/assets/38015950/38eacddf-5d74-460b-a676-71183261474b">

I don't have a wallet option at all @Beamanator

**Comment by arielgreen** [comment]
Only showing once for me!

![77590](https://github.com/Expensify/App/assets/37308300/eea4288d-90a5-452e-a2fd-f0d86ad6f4e7)

**Comment by Beamanator** [comment]
Hmm that's interesting you don't see it @grgia - you have an Expensify wallet set up & everything, right? Does it have to be Gold or something?

**Comment by Beamanator** [comment]
I think we're good to close this out
