### ISSUE TITLE
[$500] [HOLD for payment 2023-12-18] Web/mWeb - Chat - Clicking pasted link to another conversation does not to redirect user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with any account
2. Navigate to any chat > copy its URL
3. Navigate to another chat > send the URL in conversation
4. Click on the link in chat

## Expected Result:
User should be redirected to the chat from step 2

## Actual Result:
User does not get redirected, console errors are thrown each time user clicks on the link
Android and IOS apps are crashing after taping on the link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native - app crashed
- [ ] Android: mWeb Chrome
- [x] iOS: Native -app crashed
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b3090bba-c0a1-4479-b8a1-7c34ac897f8f

![Bug6303853_1701910731289!chrome_0WtygraxWy](https://github.com/Expensify/App/assets/78819774/7a99afc9-f042-4a10-96ea-92c355dc4a5d)

[logs.txt](https://github.com/Expensify/App/files/13593435/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbe4cb61f9d20674</li>
        <li>Upwork Job ID: 1737832815130214400</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
I think this was me 😄  fix incoming

**Comment by situchan** [comment]
@marcaaron you were assigned in https://github.com/Expensify/App/pull/32553 as well 😄  Shall I close?

**Comment by marcaaron** [comment]
I closed yours, yes. Thanks! Reviewing would be helpful - should be easy since I think we wrote the exact same code 🙃

**Comment by situchan** [comment]
@yuwenmemon can you please keep open for C+ payment?

**Comment by yuwenmemon** [comment]
Sounds good. Removing the label then!

**Comment by marcaaron** [comment]
Thanks yall

**Comment by marcaaron** [comment]
Added Bug label to get some help paying out @situchan

**Comment by CortneyOfstad** [comment]
@situchan I sent the job proposal to you in Upwork — please let me know as soon as you accept 👍

**Comment by CortneyOfstad** [comment]
Payment completed! Closing!
