### ISSUE TITLE
MEDIUM: Comment linking

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32619]
Tracking issue for the [Comment linking](https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#) design doc.

**Comment by quinthar** [comment]
Looks like this PR does it?  https://github.com/Expensify/App/pull/32098

**Comment by roryabraham** [comment]
Going to close this in favor of https://github.com/Expensify/App/issues/20282
