### ISSUE TITLE
MEDIUM: Complete "push to parent" & link previews

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32616]
@JmillsExpensify can you flesh out this issue with a P/S?

**Comment by JmillsExpensify** [comment]
Sure will do. Aiming to get a discussion going this week.

**Comment by quinthar** [comment]
Continuing the discussion here: https://expensify.slack.com/archives/C0671JDRKQW/p1703747091970109?thread_ts=1703746238.011989&cid=C0671JDRKQW

**Comment by JmillsExpensify** [comment]
I'm going to move this one to weekly as I'm now prioritizing it on that timeframe.

**Comment by JmillsExpensify** [comment]
I have had trouble prioritizing this one so far this week. Still keeping the weekly label in place, though I don't expect to ship the design doc this week.

**Comment by JmillsExpensify** [comment]
I've got a couple of wave-related projects in front of this one, which are:

 - Details / three dot overflow simplification
 - 7-day hold
 - Simplified Collect implementation
 - Money pre-designs
 
 My plan is to post discussions on the first two today, which leaves the `Money` pre-design in front of this one. I'd like to get the first Money discussion posted by Friday. As soon as Money gets kicked off, I can post a better ETA of when I think I'll be able to prioritize this. 
 
 Additionally, I will start to look for someone that can help push this forward. I won't be able to lead this for a couple of weeks, though I can help out with it now.

**Comment by JmillsExpensify** [comment]
Alright, the main and last thing standing in the way of this initiative is now `Money` / `Search`. As soon as that HL doc goes out, I will circle back on this initiative and put it to paper.

**Comment by JmillsExpensify** [comment]
Still below `Money` / `Search`. That design doc started this week.

**Comment by JmillsExpensify** [comment]
Same as above. Still below search.

**Comment by JmillsExpensify** [comment]
Pretty far down in the priority queue at the moment.

**Comment by JmillsExpensify** [comment]
This is super far down in my queue at the moment. Currently above it: 

 - Search v2
 - Search v3
 - Workspace rules
 
 I'll prioritize it as it becomes more of a priority in vip-vsb.

**Comment by JmillsExpensify** [comment]
Not going to be a priority anytime soon, so making this a monthly

**Comment by JmillsExpensify** [comment]
vip-vsb is on pause.

**Comment by JmillsExpensify** [comment]
Not a priority so I'm going to close this issue.
