### ISSUE TITLE
HIGH: Add actionable same-workspace room mentions

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32622]
Problem:
===
New Expensify allows creating an unlimited number of workspace chat rooms named like `#chat-room-name`.  However, the only way to notify someone that a room exists today is to manually link to it by embedding the URL of the new room.  If you don't already know that URL, you need to switch to that room, get its link, switch back, and post.  This is very cumbersome.

A second problem is that creating a new room takes a number of steps: `Global Create > Start chat > Room`.  Currently there's no way to do that with the keyboard alone.

Solution:
===
Let's allow anyone to *create a new room* or *link to an existing room* purely using markdown, by modeling room mentions as follows:

Step 1: Create the room mention
---
1. Auto complete anything matching the "room pattern" (eg, starts with `#`, followed by lowercase alphanumeric with dashes and underscores) against the list of known rooms in this workspace
2. Anything that matches the pattern, whether it's an existing room or an unknown room, record the mention in the HTML just like a user mention:
    * User: `<mention-user>@bob@bagels.com</mention-user>`
    * Room: `<mention-room>#bobs-bagels</mention-room>`
3. This will render in the HTML as a "mention", whether or not there is actually a room with that name.
4. That HTML will be sent to the server in `CreateReportAction`

Step 2: Show an actionable mention if it's a new room
---
1. The server currently parses the HTML to find `<mention-user>` to determine if we need to create the actionable whisper.
2. If it's a new room, the server returns an "actionable whisper" that is modeled off of the "Do you want to invite Bob to this room?" user mention whisper, but this one will ask "#new-room doesn't yet exist, do you want to create it?"
3. Regardless of which you click, the whisper is deleted
4. If you pick "Yes", then a room with that name is created on the same workspace as the current room, with `workspace` visibility, and anyone else who is mentioned in that same comment is automatically invited to it (in addition to the author of the comment).

Step 3: Make the mention work
---
1. Any comment with a `<mention-room>#bobs-bagels</mention-room>` HTML element will show it in "mention" formatting
2. If you click on it, we navigate to that room
    * Question: How do we know if the room exists; how do we get its `reportID`?  How do we currently do this for `<mention-user>`? ([Slack](https://expensify.slack.com/archives/C0671JDRKQW/p1706772114484549?thread_ts=1703822896.107649&cid=C0671JDRKQW))

Step 4: Knock on a room that you can't access
----
1. If you click on a mention to a room you aren't in and can't freely join, currently it'll show a 404 page.
2. Let's change that to show a page that allows you to request access to that room
3. When you request access, show a message in the room indicating that someone is asking to be let in, with options to `Admit` or `Deny` entry
4. Either way it deletes the message
5. If you choose `Admit` it invites them to the room, exactly as if you had mentioned them.  Because they don't have the ability to freely join, the @blimpich's code will show `Alice added Bob`.

**Comment by jasperhuangg** [comment]
>  How does the server know whether to respond with an actionable mention whisper?

The server checks a few things:
- If the comment sent has mentions in it.
- If any of the mentions in the comment are for people who aren't already participants of the report.
- If the report is eligible for actionable mention whispers. DMs/default rooms/policy expense chats are not eligible, but threads within them are.

That's basically it. If all those checks succeed, then we know to create an actionable mention whisper in the report, and return it back to the client.

**Comment by quinthar** [comment]
Upgrading this one to HIGH as it's really core functionality with painful workarounds.
