### ISSUE TITLE
LOW: Make copy/paste work well

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32625]
Great ideas from [@gabi](https://expensify.enterprise.slack.com/team/U1678RXL7), going to work on defining a MVP once VIP scope is defined.

**Comment by GabiHExpensify** [comment]
I'll dig into this next week, but jotting down ideas off the top of my head:
- Formatting is broken when you copy/paste -- bold, italics, paragraph breaks, etc. 
- Ideal flow should be that you can copy/paste something from somewhere else into newdot, and maintain the formatting, and then copy/paste from newdot into somewhere else, and also maintain the formatting.

**Comment by GabiHExpensify** [comment]
haven't gotten to this yet, i'm trying to #focus on #vip-split right now. let me know if this bumps up priority.

**Comment by kevinksullivan** [comment]
@arielgreen just putting this on your radar, though I'm not sure there is any immediate action to take.
