### ISSUE TITLE
LOW: Finish tasks

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32627]
There are some [remainnig cleanup items](https://expensify.slack.com/archives/CC7NECV4L/p1701108820953339?thread_ts=1700873656.712789&cid=CC7NECV4L), but they aren’t a big priority

**Comment by thienlnam** [comment]
We've finished
- Allowing assigning to a user that doesn’t exist (creating the account in a closed state)
- Creating a task via markdown syntax

We did not get to adding edit history by EOY
