### ISSUE TITLE
HIGH: [Live Markdown] Finish live Markdown preview

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32626]
Good progress here, looking for better update: https://expensify.slack.com/archives/C04878MDF34/p1700667141477359

**Comment by tomekzaw** [comment]
Working on this

**Comment by tomekzaw** [comment]
Latest update [here](https://swmansion.slack.com/archives/C04878MDF34/p1703760495279219?thread_ts=1703271354.871729&cid=C04878MDF34)

**Comment by quinthar** [comment]
Upgrading to Medium as we are so close

**Comment by quinthar** [comment]
@thienlnam says we are targeting EOW for it to be on staging!!

**Comment by tomekzaw** [comment]
Working on it
* Android and iOS already working on production
* Web support is tracked in #36071

**Comment by quinthar** [comment]
It's live!!  Now going into bugfixing mode.
