### ISSUE TITLE
[$500] LHN - IOU report disappears from the LHN when clicking on another chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in as a new Gmail account
3. Send message to another Gmail account
4. Reply from the secondary account
5. Send a manual IOU
6. Click on the IOU report
7. Click on any other chat in the LHN

## Expected Result:
The IOU report should still be visible.

## Actual Result:
IOU report disappears from the LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1c6be2a6-cade-4f94-a0f7-b627027c7cc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bb625ce80a441fe</li>
        <li>Upwork Job ID: 1732721091542790144</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
According to https://github.com/Expensify/App/issues/29593, this is the expected behaviour and should not be changed.

**Comment by sobitneupane** [comment]
Thanks @paultsimura 

@greg-schroeder As per https://github.com/Expensify/App/issues/29593, it is an expected behavior.
