### ISSUE TITLE
[HOLD for payment 2023-12-18] [HOLD for payment 2023-12-15] [$500] Chat - Focus is lost after deleting letter in a word in the emoji search bar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com on desktop browser or open Desktop App
2. Login with any account
3. Go to any chat
4. Select Emoji Picker
5. Type any word in Search bar
6. Delete by Backspace last letter in this word

## Expected Result:
The letter is removed and focus remains in the search bar

## Actual Result:
The letter is removed but the focus is lost in the search bar and moved to the first emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b8488575-2f11-4e9c-83f2-a99a3b0110cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168e5e4d901d26abc</li>
        <li>Upwork Job ID: 1732716256100392960</li>
        <li>Last Price Increase: 2023-12-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27997975</li>
</ul></li>
    </ul>
</details>

**Comment by MariaHCD** [comment]
I think this is a regression from https://github.com/Expensify/App/pull/31899#discussion_r1416951908

cc: @TMisiukiewicz @robertKozik

**Comment by mariosant** [comment]
@MariaHCD I would like to contribute here, is this issue still open for takes?

**Comment by yuwenmemon** [comment]
Reviewing this

**Comment by yuwenmemon** [comment]
Fix was CP'ed to staging so removing blocker label.

**Comment by TMisiukiewicz** [comment]
The issue still occurs when:
1. user filters the emoji list by typing in the input
2. uses down arrow key to focus on the emoji
3. uses arrow up key to focus on the input again
4. uses backspace to delete a letter in the input

https://github.com/Expensify/App/assets/13985840/5e43b013-3e49-428a-99f0-003559194634

**Comment by rushatgabhane** [comment]
Hi everyone, I didn't review proposals or any PR linked to the issue here.

**Comment by MariaHCD** [comment]
@dukenv0307 what are your thoughts on https://github.com/Expensify/App/issues/32644#issuecomment-1850048088?

**Comment by muttmuure** [comment]
I can't reproduce [this](https://github.com/Expensify/App/issues/32644#issuecomment-1850048088) in staging

**Comment by muttmuure** [comment]
Ah OK, I can reproduce this if the following steps are taken: 

1. Open the emoji selector
2. Add text (I chose "laugh")
3. Press down then up on the keyboard
4. Delete some text
5. Focus is lost

https://github.com/Expensify/App/assets/46995600/c8b6ed3f-0751-4f46-9848-b59f2315ea26

**Comment by muttmuure** [comment]
@dukenv0307 can you reproduce using the steps above?

**Comment by muttmuure** [comment]
Still reproducible - waiting on proposals

**Comment by TMisiukiewicz** [comment]
@muttmuure I'm currently working on #30911 where I am refactoring keyboard navigation in the emoji picker. It might solve the existing issue - I'll let you know when I finish

**Comment by TMisiukiewicz** [comment]
@muttmuure I can confirm my solution in #34581 fixes that issue

**Comment by muttmuure** [comment]
Thanks @TMisiukiewicz!

**Comment by muttmuure** [comment]
Waiting on fix

**Comment by muttmuure** [comment]
Looks like the linked PR caused a regression, but we might be all good now
