### ISSUE TITLE
[Wave 6: Drafts] When report is created as a draft the expense report details are not correctly processed

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32640]
### Problem

When the submitter created their draft report and the admin is looking into the workspace chat with the employee, the report preview is showing TBD as there must be some details missing of the report.

https://github.com/Expensify/App/assets/36083550/62aca687-65b7-40d3-b007-d69782eec777

### Solution

Ensure the report preview is rendering correctly for the admin and approver upon expense report creation and submission.

**Comment by marcochavezf** [comment]
Update:
- Included the Auth part
- Returned the response from `SubmitReport` to send the onyx updates

Pending items:
- Fix integration tests in Web-E
- Add automated tests

**Comment by marcochavezf** [comment]
Auth PR merged, Web-E in review

**Comment by marcochavezf** [comment]
The PRs were already deployed to production, I will close it out.
