### ISSUE TITLE
[Wave 6: Drafts] Report submission is not reflecting real time for admin 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32642]
### Problem

When draft report is submitted by the employee, the admin view does not reflect that in the UI.

https://github.com/Expensify/App/assets/36083550/6ea992af-14fe-4818-ab05-2883d9ecb726

### Solution

Ensure all the necessary updates are sent from the API when report is submitted. 

That would be update to the expense report with its state and status changing as well as update report preview action
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ab22e1ebff399ab</li>
        <li>Upwork Job ID: 1734571062109163520</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
@mountiny would we consider this an `internal` or `external` bug? Just making sure I am applying the correct labels 👍

**Comment by mountiny** [comment]
This needs to be internal and i believe @marcochavezf might have a fix ip for this, maybe

**Comment by marcochavezf** [comment]
I noticed that in the last PR, we only send the updated expense report data to the approver (manager) and not to other admins in the workspace, so I created this [PR](https://github.com/Expensify/Auth/pull/9450) to also send the updated data to all admins in the workspace chat.

**Comment by CortneyOfstad** [comment]
Any updates on this? TIA!

**Comment by marcochavezf** [comment]
The PR was already deployed to production two weeks ago. I will close this GH issue manually.
