### ISSUE TITLE
[$500] [HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [Theme Switching] 🐛 Fix Status Bar Colors on Native

### ISSUE THREAD

**Issue by grgia** [Expensify/App#32657]
https://github.com/Expensify/App/pull/32512#pullrequestreview-1770099218

> Few issues that I noticed so far:
> 
> - Sometimes in mWeb/Safari the color of status bar (in light mode) changes back to dark. One way to reproduce is:
> 
> 1. Go to any chat.
> 2. Press on the header to open the users profile page.
> <img width="485" alt="Screenshot 2023-12-07 at 18 31 30" src="https://github.com/Expensify/App/assets/25876548/962f725a-6175-4eba-812f-a54e6d685de2">
> 
> - In IOS/native, Color of text in status bar is dark in dark mode
> <img width="485" alt="Screenshot 2023-12-07 at 18 37 33" src="https://github.com/Expensify/App/assets/25876548/f3116954-784d-4c75-b9b8-21f95cdbac63">
> 
> - Similarly, in Android/native, Color of text in status bar is white in light mode.
> <img width="449" alt="Screenshot 2023-12-07 at 18 38 51" src="https://github.com/Expensify/App/assets/25876548/4d628492-1504-4ec8-865a-12dc8de56914">
> 

Also related to this issue
https://github.com/Expensify/App/issues/32591
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167754a76c4f5604c</li>
        <li>Upwork Job ID: 1744511657386971136</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by grgia** [comment]
https://github.com/Expensify/App/pull/32512#pullrequestreview-1770099218

@chrispader

**Comment by chrispader** [comment]
> > * In IOS/native, Color of text in status bar is dark in dark mode

also can't reproduce this

![Simulator Screenshot - iPhone 15 Pro - 2023-12-07 at 16 00 49](https://github.com/Expensify/App/assets/20173411/09d226ac-8800-4c59-b9a6-a11dceb8dda7)

**Comment by chrispader** [comment]
> > * Similarly, in Android/native, Color of text in status bar is white in light mode.

@sobitneupane also can't reproduce Android/native:

![Screenshot_1701961749](https://github.com/Expensify/App/assets/20173411/580f3b32-70c9-481c-ab76-e6a48362f238)

![Screenshot_1701961758](https://github.com/Expensify/App/assets/20173411/2320a102-a695-4a11-b3f0-e35a11b3cdb3)

**Comment by chrispader** [comment]
note to myself: https://github.com/Expensify/App/issues/32695

**Comment by grgia** [comment]
in progress

**Comment by chrispader** [comment]
Ok this should have been fixed in this PR: https://github.com/Expensify/App/pull/32672

**Comment by grgia** [comment]
@kevinksullivan could you help ensure that @situchan receives the $500 C+ review payment for review of https://github.com/Expensify/App/pull/32672

**Comment by situchan** [comment]
offer accepted already

**Comment by situchan** [comment]
@kevinksullivan payment not processed yet

**Comment by kevinksullivan** [comment]
All set @situchan
