### ISSUE TITLE
[$500] IOU - IOU reports with draft are not shown in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to chat > + > Request money.
3. Create a money request.
4. Go to IOU report.
5. Create a draft.
6. Go to IOU details page.
7. Create a draft.
8. Return to LHN.

## Expected Result:
Both IOU reports will be present in LHN as there is draft in each of them.

## Actual Result:
Both IOU reports are not present in LHN despite having draft.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/673be90f-190e-46ca-8d36-6d2591c7b43b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c72df490550ca13a</li>
        <li>Upwork Job ID: 1732766596597559296</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
Same as https://github.com/Expensify/App/issues/32648#issuecomment-1845372059: the IOU reports are now hidden from LHN

**Comment by peterdbarkerUK** [comment]
Closing as expected behaviour!
