### ISSUE TITLE
[Hold for payment 2024-02-12] [$1500] Implement a new navigator for the Ideal Nav overhaul

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32689]
Implement the new navigation system for the Ideal Nav project.

The detailed requirements for the new navigation structure are stipulated in [this design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg).

@adamgrzybowski from Software Mansion will do the implementation work. We will keep track of the progress using this issue.

[Potential new requirement that hasn't made it to the design doc yet.](https://expensify.slack.com/archives/C036QM0SLJK/p1701975105241769)

## Child issues
- #32939
- #32940
- #32941

**Comment by adamgrzybowski** [comment]
👋

**Comment by adamgrzybowski** [comment]
Hey @hayata-suenaga this issue seems quite general. We divided our work on the structure of navigation into three separate task

Left hand navigator - @WojtekBoman 
Full screen settings page - @kosmydel 
Bottom tab navigator - @adamgrzybowski 

Maybe we could create these issues to track progress more accurately?

**Comment by hayata-suenaga** [comment]
Is @kosmydel working on the full screen settings page for the account for workspace or both?

**Comment by hayata-suenaga** [comment]
I am assigning myself to this tracking issue for three navigation-related issues.

@adamgrzybowski if you need a feature branch to which to merge navigation-related branches, please use https://github.com/Expensify/App/tree/ideal-nav that Vit created.

**Comment by s77rt** [comment]
@hayata-suenaga Can you assign me here?

**Comment by hayata-suenaga** [comment]
the feature branch is very close to be merged

**Comment by s77rt** [comment]
@hayata-suenaga Can you please assign a BZ member for payment processing?

**Comment by hayata-suenaga** [comment]
An expert agency engineer authored the PR, so the only payment we need is for C+.

@lschurr The PR @s77rt (C+) reviewed was super huge. They deserve at least twice the usual payment. I'd say 3x.

**Comment by lschurr** [comment]
Sounds good @hayata-suenaga! Can you link me to the specific PR so I can see when it's merged for payment?

**Comment by hayata-suenaga** [comment]
ah sorry about that

[here is the PR](https://github.com/Expensify/App/pull/33280)

**Comment by lschurr** [comment]
Thanks! Looks like it was deployed to prod on Feb 5th, so we'll pay on Feb 12th.

**Comment by hayata-suenaga** [comment]
by the way, there are multiple regressions that stemmed from the PR, but all these regressions were expected. They should not reduce the payout to @s77rt

**Comment by s77rt** [comment]
Thank you! But I'm good with the standard $500. No counting those regression is enough

**Comment by lschurr** [comment]
We discussed internally and decided $1500 is a fair price for the amount of work you put into this one @s77rt :)

**Comment by lschurr** [comment]
Sent offer in Upwork: https://www.upwork.com/nx/wm/offer/100843971

**Comment by s77rt** [comment]
Accepted! Thank you!

**Comment by lschurr** [comment]
Paid in Upwork :)

**Comment by hayata-suenaga** [comment]
thank you so much and great work @s77rt !
