### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Member - Gmail account cannot invite members to WS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites: Use [workprofiletestuser@gmail.com](mailto:workprofiletestuser@gmail.com)
account or other gmail account with existing WS
1. Open New Expensify app
2. Navigate to the settings of the existing WS
3. Invite any member

## Expected Result:
The Gmail account should be able to invite members to any WS that exist in your account

## Actual Result:
Gmail account cannot invite users to existing WS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f5069217-63bf-431e-b085-efed8d9c61ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3f67ec9f72b91ef</li>
        <li>Upwork Job ID: 1732794719410888704</li>
        <li>Last Price Increase: 2023-12-28</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28071914</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment]
I cannot reproduce it on my end but based on the console error from the video looks like for whoever can reproduce it `this.props.route.params.policyID` seems to be `undefined`.

https://github.com/Expensify/App/blob/8fa65ec4de74f22f7c700eb78b4ee83eda96de58/src/pages/workspace/WorkspaceInviteMessagePage.js#L127

I was able to reproduce it by setting `this.props.route.params.policyID` to `undefined` from within the codebase.

**Comment by puneetlath** [comment]
I was able to reproduce it by: 
1. Logging into an account
2. Creating a workspace
3. Logging out and back in
4. Attempting to invite someone

**Comment by vikssevishnu** [comment]
Contributor details
Your Expensify account email: vishnu.vikas19@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a59961216a1ee633

**Comment by vikssevishnu** [comment]
Getting error when trying to access the stackoverflow url 

![Screenshot 2023-12-25 125506](https://github.com/Expensify/App/assets/24762559/67c9c661-542e-4be9-984c-62f8db4f9708)

**Comment by deetergp** [comment]
@bernhardoj's proposal sounds good. Let's go with it!

**Comment by bernhardoj** [comment]
PR is ready

cc: @parasharrajat

**Comment by puneetlath** [comment]
@parasharrajat friendly reminder about the checklist so that we can pay in a couple of days.

**Comment by puneetlath** [comment]
Payment summary: 
$500 - @bernhardoj - paid via upwork
$500 - @parasharrajat - to be paid via NewDot (please request) 

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
