### ISSUE TITLE
[$500] Desktop - Nontification - No notifications when app has Closed via Quit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32180
## Action Performed:
1. Login to New Expensify and make sure notifications are enabled
2. Quit the app
3. Send messages from another device

## Expected Result:
Notifications are received while the app is launched or not currently active (like the iOS app)

## Actual Result:
Notifications are not working unless the app is open on the Mac

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dbc89f5f-3ad1-4454-97f8-16880b42025a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115f6923151845f76</li>
        <li>Upwork Job ID: 1732827134253973504</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
I don't think this is an issue! @lanitochka17 did we have any instance that was working earlier?

**Comment by zanyrenney** [comment]
I agree, this doesn't seem like this is occuring.
