### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [Theme Switching] 🐛 Navigation - App background is shown as white instead of black (desktop, ios)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Open the keyboard to sign in (Observe the background)
---
1. Open the Desktop app
2. Resize the window (Observe the background)
(These are just different ways to focus solely on the background color)

## Expected Result:
User expects the apps native background color to be black to match the "Dark" theme of the app and match the PROD black background

## Actual Result:
On Staging, the apps background has been changed to white and is now very noticeable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ea74228-33a2-4f98-b3f7-a47fad27f2f0

![Bug6304818_1701974177265!Background_color_](https://github.com/Expensify/App/assets/78819774/e84fd22d-8a32-4565-aad4-f1c551845516)

https://github.com/Expensify/App/assets/93399543/b53a8ba3-5752-465a-bd19-f98f80761f03

https://github.com/Expensify/App/assets/93399543/cae4b6d5-00c8-4a8a-8f83-5e4a7435d70c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
Removing deploy blocker

**Comment by grgia** [comment]
@tylerkaraszewski I can take this one, it's from the theme switching changes 
cc @chrispader

**Comment by grgia** [comment]
This is related to the forced dark mode change

**Comment by chrispader** [comment]
Fixed in this PR: https://github.com/Expensify/App/issues/32657

cc @grgia

**Comment by grgia** [comment]
@bfitzexpensify could you help me out with the $500 C+ review payment to @situchan for review of https://github.com/Expensify/App/pull/32672

**Comment by bfitzexpensify** [comment]
Sure, offer sent @situchan

**Comment by bfitzexpensify** [comment]
All done here.
