### ISSUE TITLE
`/receipts/` endpoint encounters CORS errors when using custom header for attachment authentication

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#32703]
## Summary: 
We have a goal to shift attachment authentication to a custom header, eliminating the need to append a token to the URL. This change allows for more efficient caching since the URL remains consistent. However, in doing this we encounter CORS errors. See [this comment](https://github.com/Expensify/App/issues/14991#issuecomment-1760088270) for more details.

We had this same problem with the `/chat-attachment/` which was solved by these two PRs ([1](https://github.com/Expensify/Expensidev/pull/809) & [2](https://github.com/Expensify/Salt/pull/12887)). We need to do the same for the receipts endpoint. This caused [this deploy blocker](https://github.com/Expensify/App/issues/32593) recently.

## Solution:

Configure our CORS settings in the backend so that the `/receipts/` endpoint is like the `/chat-attachment/` endpoint and allows these custom headers.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d594876a09efc2c</li>
        <li>Upwork Job ID: 1732925899350822912</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by blimpich** [comment]
@burczu not sure if you need to be assigned to this issue. This issue has to be completed internally, but I created the issue in Expensify/App so that my progress on it could be visible to those interested in it.

**Comment by blimpich** [comment]
Haven't had time to work on this yet. Hoping to get to it this week.

**Comment by blimpich** [comment]
Making this weekly until I can prioritize it over other tickets. This will be high on my list once I deal with more urgent issues since it is blocking other people's work.

**Comment by blimpich** [comment]
Not prioritized, swamped with other chore / auto-assigned work.

**Comment by roryabraham** [comment]
I think this should be treated as a top priority. Image caching is blocking a whole suite of other issues and has been in-progress for years now (since Spain OffShore IIRC).

**Comment by blimpich** [comment]
I agree that this is high priority work, but it wasn't part of a commitment for EOY so I did not prioritize it. Now that it is the new year I hope that I can work on this soon, though I still consider it less important than regressions that are actively hurting customer experience, which is what I'm currently prioritizing.

**Comment by blimpich** [comment]
Taking another crack at this today.

**Comment by blimpich** [comment]
Success! Was able to verify locally after looking at this with fresh eyes. Will update PR's and add reviewers shortly
