### ISSUE TITLE
[$500] IOU- App crashes on deleting distance request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap Request money ---- Distance
4. Enter start and finish waypoints
5.Tap next
6.Tap request
7.Tap on distance request created to open distance request details page
8.Tap 3 dots on top and select delete request and confirm delete

## Expected Result:
When user taps on delete request, the created distance request must be deleted and app must not crash

## Actual Result:
In distance request, when user taps on delete request app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6120c732-f70a-4f3a-b408-de3acdb41d11

[logs.txt](https://github.com/Expensify/App/files/13615046/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b000b1269fb4693</li>
        <li>Upwork Job ID: 1737236433193459712</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by danieldoglas** [comment]
Ok, I was able to run main on my iOS simulator, but I can't even see the screen to create a distance request
![image](https://github.com/Expensify/App/assets/5818999/62cab34d-4943-41dc-b80d-b26d836b0126)

**Comment by yuwenmemon** [comment]
Able to reproduce on staging in iOS

**Comment by yuwenmemon** [comment]
Can't reproduce on dev anymore. This was after merging https://github.com/Expensify/App/pull/32746 to get the distance flow to work again, but I'm not sure if it's related or not.

**Comment by yuwenmemon** [comment]
Plus it's not like I can test a version before cause the app was crashing then 😅. So I'm going to remove the blocker and close since this seems to have been resolved.

**Comment by danieldoglas** [comment]
@joekaufmanexpensify this was already finished and deployed, I'm reopening the issue so we can track payment for @situchan

**Comment by joekaufmanexpensify** [comment]
Adding external label to create upwork job.

**Comment by joekaufmanexpensify** [comment]
@situchan offer sent for $500!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set!
