### ISSUE TITLE
CRITICAL: [$500] Inviting a member to a user created room does not add them until page is refreshed

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#32712]
## Problem

Originally reported by @quinthar [here](https://expensify.slack.com/archives/C049HHMV9SM/p1701633038717359)

**Reproduction steps:**

- Navigate to expensify.com/new/room
- Invite a member (must be a new account and not someone who you have a personal detail for yet)
- See that the member is not included in the list
- Refresh the page
- See that the member is included in the list

## Why is this important?

Ideally the member would be displayed immediately. 

## Solution

@jasperhuangg I think maybe we need to add an optimistic personal detail for the user being added? Or something is wrong with the `accountID` logic in the front end. When we add a new member to a room we are using an optimistic accountID generated in the options. But we do not add optimistic personal details for them [here](https://github.com/Expensify/App/blob/52a6383349ef705b04e2d26233ab68c0a1c91124/src/libs/actions/Report.js#L2090-L2126). So [this logic](https://github.com/Expensify/App/blob/52a6383349ef705b04e2d26233ab68c0a1c91124/src/pages/RoomMembersPage.js#L179-L182) here is hit.

Confirmed with this log:

![2023-12-05_12-01-28](https://github.com/Expensify/Expensify/assets/32969087/0049812e-582d-46e8-9877-5f198fb8440d)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b17b3e302b4beccb</li>
        <li>Upwork Job ID: 1733076588418981888</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28027117</li>
<li>dukenv0307 | Contributor | 28027118</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
bump @hoangzinh 🙏

**Comment by dylanexpensify** [comment]
@hoangzinh any update?

**Comment by quinthar** [comment]
Am I blind?  What is the PR for this?  Why is this issue still open if this was merged last week?

**Comment by dylanexpensify** [comment]
Lame! Will update today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dukenv0307 $500
- Contributor+: @hoangzinh $500
Please apply!

**Comment by dylanexpensify** [comment]
paid! @hoangzinh can you propose Regression Test steps please?

**Comment by roryabraham** [comment]
Hmmm ... that's not right.

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/Expensify/issues/356696 to update regression tests, closing this out
