### ISSUE TITLE
[$500] LOW: Deleted workspace report cannot be accessed but shows on reports list page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32714]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @slafortune 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701984616024609

## Action Performed:

1. Create a report in a free workspace
2. Submit the report so it’s processing
3. Delete the workspace
4. Click on the report in the OD

## Expected Result:
Able to access the report in the OD

## Actual Result:
Observe report shows in the reports list page, policy "not shared", report not accessible

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/1a9e7245-4125-459d-a00b-03185232f07f)

https://github.com/Expensify/App/assets/38435837/cd4283db-9b2c-410a-a161-195e2b1dc6b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011aef5d187618c937</li>
        <li>Upwork Job ID: 1733111766749040640</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Waiting on proposals

**Comment by brunovjk** [comment]
Until yesterday I managed to reproduce the error completely.
Today I can access the report after deleting the workspace, the 'not shared' remains.

https://github.com/Expensify/App/assets/95647348/71ff1663-ab1d-49b6-9c18-24b0d422ae0a

**Comment by bfitzexpensify** [comment]
@dylanexpensify do you think we should keep this open? The flow is a hybrid ND/OD one, so I'm not sure that this is worthwhile to address
