### ISSUE TITLE
[HOLD for payment 2023-12-20] [HOLD for payment 2023-12-18] Chat - Skeleton has no animation in the LHN and in the report at the time the user logs in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32719]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32328
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under any account

## Expected Result:
he skeleton must have animation in the LHN and in the report at the time the user logs in

## Actual Result:
Skeleton has no animation in the LHN and in the report at the time the user logs in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e153433c-ab24-4287-b256-7e1162d57043

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
[Commented](https://github.com/Expensify/App/pull/32512/files#r1420627205) in offending PR with the root cause.
cc: @grgia

**Comment by grgia** [comment]
I'll add to this PR - https://github.com/Expensify/App/pull/32721

**Comment by yuwenmemon** [comment]
Cp'ed, removing blocker
