### ISSUE TITLE
FAB - "Add to group" and "Split" buttons have the same color as the highlighted row color

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click + > Start chat
3. Click + > Request money > Manual
4. Enter amount > Next

## Expected Result:
"Add to group" and "Split" buttons will have distinctive color compared to the color of the highlighted row

## Actual Result:
"Add to group" and "Split" buttons have the same color as the color of the highlighted row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 
<img width="1440" alt="Bug6305640_1702040301727!Screenshot_2023-12-08_at_20 53 47" src="https://github.com/Expensify/App/assets/78819774/194d9777-a81d-4b8c-bf88-094087e19ef6">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
cc @grgia for https://github.com/Expensify/App/issues/32688

**Comment by grgia** [comment]
Closing as dupe
