### ISSUE TITLE
[$500] [HOLD for payment 2023-12-20] [HOLD for payment 2023-12-18] LHN - Applausecard account is crashing after clicking on any Request in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
3. Click on any Request in LHN

## Expected Result:
Applausecard account is not crashing after clicking on any Request in LHN

## Actual Result:
Applausecard account is crashing after clicking on any Request in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/38384d04-b6eb-4f15-9e7b-2d22ecda8866

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163fa2ca7f62b144d</li>
        <li>Upwork Job ID: 1738223765809868800</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Not reproduced on production 

https://github.com/Expensify/App/assets/93399543/0fa917f2-40c1-41fa-9b4a-6db54917ee1a

**Comment by kbecciv** [comment]
@situchan Please attached!

![image](https://github.com/Expensify/App/assets/93399543/26e833e5-8922-40b6-a7a1-49b669d63908)

**Comment by ZhenjaHorbach** [comment]
https://github.com/Expensify/App/commit/9b3ed5e8d821392b8e2ccedb942b06ef8be56e4b#diff-7472918ae174ded3ed9ce8b5fa05c744d77074207fb84f1fce28d1bfd2ba1e56

Looks like a regression from this PR
https://github.com/Expensify/App/pull/32498

**Comment by situchan** [comment]
@grgia can you please add this fix to [PR](https://github.com/Expensify/App/pull/32721) as well?

**Comment by grgia** [comment]
On it @situchan

**Comment by yuwenmemon** [comment]
CP'ed! Removing blocker.

**Comment by CortneyOfstad** [comment]
@situchan I just sent you a proposal in Upwork — please let me know as soon as you accept and I'll get that paid ASAP. Thanks!
