### ISSUE TITLE
[$500] Web – Attachment – Unable to clicking on "eye" icon in protected PDF using Tab/Enter keys

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Open 1:1 conversation
4. Send a password protected PDF
5. Open the PDF
6. Click on enter password
7. Enter the password (Test12345)
8. Clicking on the "eye" icon to review the entered password using Tab/Enter keys

## Expected Result:
The password is opened

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7df2ce8-d2ab-455b-88db-0f152fe509a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0d1d7387aaf5566</li>
        <li>Upwork Job ID: 1733135076074393600</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by geekycoder28** [comment]
**What is the problem?**
The `Checkbox` component has the logic to block triggering the `onPress` event when `Enter` key is pressed.
https://github.com/Expensify/App/blob/269e8668c3ced74b6e7fc32b74e4c133fad1df78/src/components/Checkbox.tsx#L76C33-L76C33
As long as you wrap the eye icon with `Checkbox` component, it doesn't trigger the onPress event of `Checkbox` and toggle the Icon.

**Possible Solution**
Add one more usecase in `Checkbox` component, perhaps adding a new Prop to optionally check the `Enter` keyboard.

**Comment by ArekChr** [comment]
@alexpensify, I've reviewed the issue regarding the behaviour of checkboxes being toggled with the Spacebar instead of the Enter key. This is an intentional design choice aligned with web accessibility standards. We should leave the `Spacebar` as the activation key of the checkboxes. I think we should close this issue.

For more information on these practices, please refer to [WebAIM Keyboard Accessibility](https://webaim.org/techniques/keyboard/) or [Developer Mozilla - ARIA: checkbox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role)

**Comment by alexpensify** [comment]
All good, I wanted to make sure. Based on this feedback, I'm going to close this one.
