### ISSUE TITLE
[$500] Android-Workspace-Custom profile image changed to default avatar on tapping update to USD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces ------ Workspace
4. Create a new Workspace
5. Set WS name and custom profile image
6. Save it
7. Tap Bank account
8. Tap update to USD
9. Tap app back button

## Expected Result:
The custom profile image for WS must not disappear after tapping update to USD

## Actual Result:
The custom profile image for workspace changed to default avatar after tapping update to USD and revisiting page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72490210-5644-4d27-b828-5dff47ffc6bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b2d415ba6d57dc4</li>
        <li>Upwork Job ID: 1733193131676172288</li>
        <li>Last Price Increase: 2023-12-08</li>
    </ul>
</details>

**Comment by LFMAKER** [comment]
Heys guys, 
I can't reproduce the bug on android. The test passes successfully.

**Comment by LFMAKER** [comment]
Contributor details
Your Expensify account email: leonardofsoliveira@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d3d4a0dc9e865b50

**Comment by AmjedNazzal** [comment]
Can't reproduce on latest main

**Comment by dylanexpensify** [comment]
reviewing now!

**Comment by dylanexpensify** [comment]
not producible!
