### ISSUE TITLE
[Wave 6: Tags] Restore tags UI to be non-hierarchical 

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#32735]
## Problem
In https://github.com/Expensify/App/issues/31753 we modified the display of tags in the tags selector to match the display of categories, e.g. a `Parent: Child` option would be split on the colon and displayed indented like
```
Parent
    Child
```

However, this is a departure from the behavior of tags on OldDot, and we need to revert the change on NewDot so that it matches OldDot.

Additional context [in Slack](https://expensify.slack.com/archives/C02MW39LT9N/p1702051493931239)

## Solution
Revert https://github.com/Expensify/App/pull/32337 and retest to verify tags of the format `Parent: Child` display on one line.

Once deployed, we need to also ensure a regression test is added to TestRail to cover the behavior.

**Comment by amyevans** [comment]
Regression test requested in https://github.com/Expensify/Expensify/issues/345784

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and can take this issue!

**Comment by amyevans** [comment]
How's this coming @waterim?

**Comment by waterim** [comment]
Will create a Draft today/tomorrow

**Comment by waterim** [comment]
@amyevans created a PR with revert, will open it tomorrow after internal review

**Comment by amyevans** [comment]
perfect

**Comment by waterim** [comment]
@amyevans Opened a PR

**Comment by amyevans** [comment]
Closing this out now since there's nothing left to do and no payments required, and I'm headed OOO!
