### ISSUE TITLE
[Wave 6: Workspace Chats] Unread marker missing for payer after money request in DM

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#32732]
## Reproduction steps

1. On NewDot, log in to accounts for user A and user B (in separate browsers or incognito)
2. Request money as user A from user B

## Expected result
User B (the payer) sees the DM bolded in the LHN to indicate unread, and upon clicking the chat, **sees a green line above the unread message**

## Actual result
User B (the payer) sees the DM bolded in the LHN to indicate unread, and upon clicking the chat, **does not see a green line above the unread message**

## Video

https://github.com/Expensify/App/assets/7277067/17732b67-af3a-4828-afd7-e2bd6611bad7

**Comment by amyevans** [comment]
@waterim as a first step can you try just reproducing? The video in the OP is a few days old, and I'm trying to repro again now and am having difficulty doing so. I'm updating all my repos to the latest `main` though and will try again.

**Comment by amyevans** [comment]
Test on latest `main` everywhere, not reproducible:

https://github.com/Expensify/App/assets/7277067/ca7fe86b-2402-458f-9816-f6516dc9893d

**Comment by waterim** [comment]
@amyevans 
I was able to reproduce, but it seems to work randomly sometimes
<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/39777589/1ff8e728-477f-47c0-afe8-246d2e7c4e3a">

**Comment by amyevans** [comment]
Were the repro steps the same as what's currently written?

**Comment by waterim** [comment]
@amyevans Yes, it looks like I can reproduce it 70/30, 70% reproducible, 30% not

**Comment by amyevans** [comment]
Any patterns noticed or leads here?

**Comment by waterim** [comment]
@amyevans No, but looking more precisely now, will try to fix today

**Comment by waterim** [comment]
After pulling main again, cant reproduce anymore :D


<img width="444" alt="image" src="https://github.com/Expensify/App/assets/39777589/2fe4cb4e-9cec-4fe5-bcb5-5782b9092182">
<img width="444" alt="image" src="https://github.com/Expensify/App/assets/39777589/b71f7686-d4bf-423d-8590-555c974d429a">

**Comment by waterim** [comment]
<img width="539" alt="image" src="https://github.com/Expensify/App/assets/39777589/61238568-0a1d-43d7-bbc0-44df7cfc1692">

**Comment by amyevans** [comment]
Okay thanks, I tested again and am always seeing the green line, so let's close this out

**Comment by puneetlath** [comment]
Thanks y'all!
