### ISSUE TITLE
[$500] Request - Request money amount disappears if tap Next&Back and then switching between tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32739]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify
2. Tap FAB button
3. Tap Request money
4. Select Manual tab
5. Select a currency and enter any amount
6. Tap Next
7. Tap Back
8. Switch between tabs Scan or Distance and return to Manual tab

## Expected Result:
The amount previously entered is remembered and displayed on the BNP

## Actual Result:
If user proceeds until attendee selector and then returns back, switching between tabs make the amount disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f35a3892-f150-44ed-b1d7-ed2cd5f35e97

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017941ed9191037a56</li>
        <li>Upwork Job ID: 1733194841222483968</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28037175</li>
<li>FitseTLT | Contributor | 28037178</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money amount disappears if tap Next&Back and then switching between tabs
### What is the root cause of that problem?
When we enter first tap(manual), we reset iou.
so amount reset as 0
### What changes do you think we should make in order to solve the problem?
We need to remove this.
https://github.com/Expensify/App/blob/0a8ad473e71c18adb3d299f0562057177de09e2a/src/pages/iou/MoneyRequestSelectorPage.js#L87-L87
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
[Proposal](https://github.com/Expensify/App/issues/32739#issuecomment-1847670424) by @FitseTLT identifies the root cause correctly and the solution suggested works well.

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment]
Yes, the expected behavior changed since this proposal was approved. Now, the suggested changes are not required. The issue may be closed.

@kadiealexander @stitesExpensify 

Since, the issue proceeded to the point of making a PR, some compensation might be due.

**Comment by stitesExpensify** [comment]
Great, thanks @FitseTLT !

**Comment by c3024** [comment]
Please close the PR @FitseTLT .
