### ISSUE TITLE
Finalize the reportFields data format

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32758]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.vc9g68afuwfz

Finalize the format of the reportFields object to rename / remove the items we are not using

**Comment by allroundexperts** [comment]
Suggested the changes. Waiting for them to be reviewed / accepted.

**Comment by thienlnam** [comment]
This is what we landed on 

'fieldId' => [
        'defaultValue' => "2023-11-19",
        'fieldID' => "field_id_DATE_FIELD",
        'name' => "Date field",
        'orderWeight' => 3,
        'type' => "date",
	   'deletable' => '1'
   ],
