### ISSUE TITLE
[HOLD for payment 2023-12-26] Create beta for newDotReportFields

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32756]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.lljtlvbi9j7c

**Comment by thienlnam** [comment]
Now we're creating the beta on the FE only

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/32957

**Comment by thienlnam** [comment]
Merged - now pending deploy

**Comment by mallenexpensify** [comment]
Contributor: @allroundexperts due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
