### ISSUE TITLE
[$500] Chat  - Screen blinks when open conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in expensifail account
3. Click FAB
4. Click Start Chat
5. Select any chat with conversations

## Expected Result:
Conversation screen should open

## Actual Result:
Conversation screen blinks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f5a85396-1547-4094-9eaa-62b6e914aa71

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b99b5f769ac6ad6a</li>
        <li>Upwork Job ID: 1733230914660085760</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
I this issue exclusive to expensifail accounts? if that's the case, shouldn't this be internal?

**Comment by lanitochka17** [comment]
Issue reproducible on gmail account too. I used an account with a lot of conversations
Build 1.4.13-5


https://github.com/Expensify/App/assets/78819774/3ecad0aa-0936-47d2-b0c6-31a13b854486

**Comment by keisyrzk** [comment]
Do you mean this "loading" view state?
![Simulator Screenshot - iPhone 15 Pro - 2023-12-18 at 08 28 13](https://github.com/Expensify/App/assets/18525360/ce6e01c3-6cbe-4506-9dda-a4c6df150851)

If so it happens on dev and all platforms as well.

**Comment by MitchExpensify** [comment]
Not overdue, being actively worked on

**Comment by MitchExpensify** [comment]
I think the "blink" is referring to this screen:

<img width="1387" alt="image" src="https://github.com/Expensify/App/assets/36425901/f20e8d62-8bcf-4029-b0a6-b7350d02f42c">


Is that right @lanitochka17 ?

**Comment by keisyrzk** [comment]
If so, I do not experience such a behavior.

**Comment by MitchExpensify** [comment]
Let's close this in that case. Its so minor and doesn't block any wave
