### ISSUE TITLE
[New Lib] Add expo-image to E/App

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#32751]
In order to properly evaluate if a new library can be added to `package.json`, please fill out this request form. It will be automatically assigned someone from our review team that will go through and vet the library.

Note: This is only for production dependencies. While we don't want people to add packages to dev-dependencies willy-nilly, we recognize that there isn't as great of a need there to secure them.

# Name of library:
expo-image

## Details
- Link to package: https://www.npmjs.com/package/expo-image
- Problem solved by using this package:
   - It provides a _major_ boost in performance for the loading of svg assets (i.e: most images in NewDot). See [PR](https://github.com/Expensify/App/pull/30905).
   - It allows HEIC images to be displayed on Android
   - It allows us to stop use of [our "deeply nested fork"](https://expensify.slack.com/archives/C03UK30EA1Z/p1687468717427929?thread_ts=1687450843.601829&cid=C03UK30EA1Z) of react-native-image-manipulator. This is a fork 8 times removed from the original source code
   - It's more actively maintained than react-native-fast-image (another 3rd party library we're currently using which this will replace)
   - Supports caching headers for images across platforms (like react-native-fast-image)
- Number of stars in GH: It's in the [expo monorepo](https://github.com/expo/expo), which has 25k stars. expo-image comes strongly recommended by all our expert partners.
- Number of monthly downloads: ~300,000
- Number of releases in the last year: ~50, 26 stable versions
- Level of activity in the repo: [high](https://github.com/expo/expo/commits/main)
- Alternatives: [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image)
- Are security concerns brought up and addressed in the library's repo?

    difficult to answer as it's in a monorepo. Here's an example of a security-related issue, but I don't think it's really related to expo-image: https://github.com/expo/expo/issues/22404

- How many dependencies does this lib use that will be brought into our code?

    The major dependency that will be added into our code by expo-image is the expo-modules core. It's a small (178kb unbundled) shim that wraps the app's main activity and app delegate to provide:
    
    - standard support for swift and kotlin in React Native
    - cross-compatibility between React Native New Arch and OldArch
    - Consistent interface for web support

- What will the effect be on the bundle size of our code?
    
    We can test to double-check, but I think it will be about +715kb

**Comment by roryabraham** [comment]
Didn't know how this would work. Removing @mountiny as he's already advocated for the additon of expo-image, and will re-add the label for a more impartial reviewer

**Comment by roryabraham** [comment]
@AndrewGable pointed out @mrousavy's recent post on X: https://x.com/mrousavy/status/1733467869109768275?s=20

Definitely a relevant opinion from a developer we know and respect

**Comment by roryabraham** [comment]
Also worth pointing out that the current plan in [Video Player](https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit) design doc is to use expo-av, which will have to wrap the app with the Expo Module core anyways.

I think we can agree that is the main, if not the only downside to using Expo image. To me that suggests that the main downside of expo-image is a moot point / going to happen anyways. So let's push this forward and start reaping the performance benefits

**Comment by roryabraham** [comment]
We can give it 24 hours to make sure every app deployer has a chance to look and react, but it looks like we have a majority 👍🏼 on [the slack post](https://expensify.slack.com/archives/C03TQ48KC/p1702328783639809) with 9 out of the 17 [app deployers](https://github.com/orgs/Expensify/teams/mobile-deployers) giving a 👍🏼

Also, point of clarification for next time - it's unclear to me whether the vote is meant to include the few ring0 people from the GitHub team that don't actively participate in the chore. If no, then the threshold for a majority would be 8 people instead of 9.

**Comment by mrousavy** [comment]
Hey - thanks for linking that tweet (was a bit controversal) - my opinion is that expo-image is great for displaying web images, as it uses the native SDWebImage library under the hood, which is really good at caching. That's the same lib that react-native-fast-image uses. 

expo-image is however well maintained, which react-native-fast-image currently is not. It also has better recycling/virtualization support when displaying a lot of images.

I'd say expo-image is the way to go if the expo-modules setup code isn't a problem for you guys! 👍

**Comment by roryabraham** [comment]
It looks like we have a clear consensus in slack to add expo-image to E/App, so I'm going to close this. Thanks for leading the discussion @AndrewGable and to everyone for participating.
