### ISSUE TITLE
[$500]  Expensifiy Card - Issue with card connection error message on tester@applausecard Wallet

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
2. Navigate to Wallet

## Expected Result:
No error message should be displayed

## Actual Result:
"Issue with card connection|" error message is displayed on [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
Wallet screen
There's an issue with this card connection, which may result in you my not seeing transactions. Please contact your administrator to resolve

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3e38331e-6d08-443a-90ea-10326f1c1763

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013dc1a1ba0f45eb6a</li>
        <li>Upwork Job ID: 1733272514115284992</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by abeebridwan** [comment]
where do we get the password for [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)

**Comment by lanitochka17** [comment]
@abeebridwan aBa9)KMdJ9PmoJzc

**Comment by abeebridwan** [comment]
@lanitochka17 
![image](https://github.com/Expensify/App/assets/66317334/13cca9ba-b0ca-49b4-8c71-b78bdd8ef42e)

**Comment by aoneahsan** [comment]
@lanitochka17 
i tried logging into "[tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)"
using this password "aBa9)KMdJ9PmoJzc" you shared here 
> @abeebridwan aBa9)KMdJ9PmoJzc

Here is a short video showing the whole process

trying to log in to the tester@applausecard.expensifail.com account to reproduce the issue
https://www.awesomescreenshot.com/video/23145996?key=18e6f687a0abb02570f505c8ecd9e652

Please share working details to log into the tester@applausecard.expensifail.com account so I can continue and submit a proposal for the issue.

Thanks,

Regards,
Ahsan Mahmood
Freelancer @ Upwork

**Comment by bfitzexpensify** [comment]
Awaiting proposals

**Comment by bfitzexpensify** [comment]
Hey @aoneahsan @abeebridwan were you able to request the details to continue testing?

**Comment by abeebridwan** [comment]
@bfitzexpensify  no weren't ... I did requested but no response

**Comment by aoneahsan** [comment]
can you please let us know if we need to mention someone specific?

**Comment by bfitzexpensify** [comment]
I'm going to close this as it's only specific to a single account, rather than broadly reproducible
