### ISSUE TITLE
Push reportField changes to all clients

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32760]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.9apixsbb8574

When we make any updates to the reportfields, ensure that those changes are populated to clients via pusher

**Comment by yuwenmemon** [comment]
Sorry - I'm going to unassign this to not block this on me. I'm having some unexpected OOO times come up this month.

**Comment by thienlnam** [comment]
This is done!
