### ISSUE TITLE
[HOLD for payment 2024-01-31] Add report field picker component

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32763]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.dskf2ijadiu4

**Comment by allroundexperts** [comment]
Not overdue Melv. Working on the PR!

**Comment by allroundexperts** [comment]
Updating today!

**Comment by allroundexperts** [comment]
Taking longer than expected but I'm almost there!

**Comment by allroundexperts** [comment]
Finally [PR](https://github.com/Expensify/App/pull/34157) created!

**Comment by thienlnam** [comment]
Assigning myself so I get assigned after the C+ reviews

**Comment by thienlnam** [comment]
Pending payment

**Comment by jjcoffee** [comment]
@trjExpensify Just noting that I'm due payment for the PR review here. Thanks!

**Comment by allroundexperts** [comment]
I have noted it down. Feel free to close after writing a payment summary.

**Comment by trjExpensify** [comment]
It's here, and I updated it to include @jjcoffee: https://github.com/Expensify/App/issues/32763#issuecomment-1919289382

Waiting to pay @jjcoffee either way.

**Comment by jjcoffee** [comment]
@trjExpensify Thanks, accepted!

**Comment by trjExpensify** [comment]
Perfect, paid!

**Comment by JmillsExpensify** [comment]
$1,000 approved for @allroundexperts
