### ISSUE TITLE
[HOLD for payment 2024-01-25] Add reportField menu items in the Expense Report View

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32762]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit?disco=AAAA83rYsHk

**Comment by VenusWhisperer** [comment]
Hello, Sir.
I can help you with your problem and please contact me.

**Comment by allroundexperts** [comment]
Not overdue Melv. Working on the PR!

**Comment by allroundexperts** [comment]
Updating today!

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/33392

**Comment by allroundexperts** [comment]
PR still in review!

**Comment by twisterdotcom** [comment]
Damn sorry for missing this, I filter issues where the payment date is more than 2 days in the past, but always get notified about Overdue. Obv I wasn't assigned then. I'll handle the Upwork job now.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @getusha paid $500 [here](https://www.upwork.com/nx/wm/offer/100808724) C+
- @allroundexperts requires payment through NewDot Manual Requests $500 (Contributor this time)

**Comment by getusha** [comment]
@twisterdotcom accepted the offer, could you please close it?

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
