### ISSUE TITLE
[CRITICAL] Implement new Video Player components

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#32770]
### Part of the NewDot Video Player project
Main issue: https://github.com/Expensify/App/issues/20471
Doc section: https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit#heading=h.py28s16nvvga
Project: https://github.com/orgs/Expensify/projects/109

### Feature Description
1. Implement the new components that will be used to play videos in NewDot:
- [x] `<ProgressBar />`
- [x] `<VolumeButton />`
- [x] `<VideoPlayerControls />`
- [x] `<VideoPlayer />`
- [x] `<VideoRenderer />`
- [x] `<AttachmentViewVideo />`

2. Introduce Context to manage player state
- [x] `PlaybackContext` ([doc](https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit#heading=h.95hp8u5px4hx))
- [x] `VideoVolumeContext` ([doc](https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit#heading=h.4wnuoc84qix9))

3. Maintain accessibility
- Add keyboard <kbd>tab</kbd> support for switching focus between elements ([doc](https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit#heading=h.nblylrd24ht5))
- Add accessibilityLabels and accessibilityRoles for components

cc @Skalakid

**Comment by JmillsExpensify** [comment]
Updates in Slack

**Comment by francoisl** [comment]
Latest Slack update available [here](https://expensify.slack.com/archives/C05NTGSDSF2/p1704510626583899).

**Comment by kowczarz** [comment]
Hey, since Michał will have to focus on different issues I'm taking over this task.

**Comment by francoisl** [comment]
Not overdue, the main PR is still in review. We just merged https://github.com/Expensify/App/pull/35249 which was also needed for the video player PR.

**Comment by francoisl** [comment]
The video player is on staging now.
We're centralizing issues and follow-up tasks [here](https://github.com/Expensify/App/issues/36625).

**Comment by trjExpensify** [comment]
👋 As discussed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1709654347737109?thread_ts=1709585792.438189&cid=C036QM0SLJK), moving this into #vip-vsb as wave9 gets deprecated. Not entirely sure there's a bunch left to do here, but given that wave9 is closing, I didn't want to leave it nowhere in limbo. Thanks!

**Comment by francoisl** [comment]
Ah, this is all done and deployed, the automation didn't work at closing the issue.
