### ISSUE TITLE
[HOLD for payment 2023-12-29] [CRITICAL] Update `HTMLEngineProvider` to use `VideoRenderer`

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#32771]
### Part of the NewDot Video Player project
Main issue: https://github.com/Expensify/App/issues/20471
Doc section: https://docs.google.com/document/d/1Fh5Nu3D0-VW7xuV9Qc-OWWZl3-W5azx7Rr1lzNw4UGo/edit#heading=h.3iq5gzws08j5
Project: https://github.com/orgs/Expensify/projects/109

### Feature Description
Update `HTMLEngineProvider` so we can render the video component on messages whose `html` value is a `<video>` tag

cc @Skalakid

**Comment by VenusWhisperer** [comment]
Hello, Sir. As a skilled developer in this field, I can help you.

**Comment by francoisl** [comment]
@Skalakid this is the first part that would not require all the components to be implemented, right? I'm trying to get a sense of whether this is something we can aim to finish next week, for the weekly update I'm preparing for tomorrow.

**Comment by Skalakid** [comment]
@francoisl No video player component need to be implemented to update HTMLEngineProvider. I think we can start by rendering `<video>` tags like current `<a>` tags. I created draft PR with the required changes

**Comment by francoisl** [comment]
This is on production, closing the issue.

**Comment by mallenexpensify** [comment]
Wowza, sorry @Ollyws .  can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013ee0d8a7106d964d

**Comment by mallenexpensify** [comment]
Contributor+: @Ollyws paid $500 via Upwork.  

Sorry again for missing this.
