### ISSUE TITLE
Modal to switch to "Focus mode" appears in abracadabra page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32778]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702060707773979

## Action Performed:

1. go to staging.new.expensify.com
2. enter an email address does not have an expensify account
3. clicked the link which landed me on the abracadabara page

## Expected Result:
 abracadabara page without any modal 

## Actual Result:
saw the modal atop the abracadabara page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/620df110-c465-4a0c-8c07-aec9e53bcd56

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
Why is the link in the video a report ID, but I get a link like this in my email: `https://new.expensify.com/v/16118621/606561`.

When I follow those steps, I just get this:

https://github.com/Expensify/App/assets/9133401/b761916b-2176-4431-9d0b-adecaf0b23d3



No #focus modal at all. Closing.
