### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] [Wave 6: Workspace Chats] IOU-The request created is not displayed in the manual expense created page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap employee Workspace chat
3. Tap on a exsisting manual expense which is created and submitted.( if not create a manual expense and submit it)
4. Tap plus icon near compose
5. Tap request money
6. Enter amount
7. Tap next
8. Tap request

## Expected Result:

On paid policy, if the expense report is not in open state, do not show the `Request Money` option in the menu on the expense report. Only in case the expense report is open.

This is only the case for paid policies

## Actual Result:
The request created is not displayed in the manual expense created page.Request created is shown only in Worspace chat page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f6227074-d6a6-4fb0-aca7-f8f1c7a8d8b9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ae27c329f45f3a6</li>
        <li>Upwork Job ID: 1734161470412218368</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28062552</li>
<li>bernhardoj | Contributor | 28062553</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by mountiny** [comment]
Ah good point, if this is paid policy, then we create open reports, once submitted new requests should go to a new open report.

So I think the solution would be that on the + icon in the non-open expense report on paid policy, we should hide the Request money option, you cannot request money from there but either from the workspace chat or from the Global create

**Comment by mountiny** [comment]
If the expense report is not a [draft report](https://github.com/Expensify/App/blob/5c0f3e49129ed3a839523aeab1464e898a02535d/src/libs/ReportUtils.ts#L563-L568). so the stateNum and statusNum are not 0.

Free policies, cannot have open reports so there we have logic that if the expense report is padi, you cannot request more money there

**Comment by mountiny** [comment]
```
function canRequestMoneyOnThisExpenseReport() {
  if (isExpenseReport) {
    if (policyType == free) {
      if (report.state ==1 && report.status ==1 ) {
        return true;
      }
    } else if (policyType == 'team' OR policyType == 'corporate') {
       if (report.state ==0 && report.status ==0 ) {
         return true;
       }
    }
  }
  if (isIOUReport) {
    if (state ==1 && status ==1 ) {
      return true;
     }
   }
   return false;
}
```

**Comment by mountiny** [comment]
Looking swell lets go

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @hoangzinh $500, paid via Upwork 
 - Contributor+: @bernhardoj, paid via Upwork 
 
 Upwork job is here: https://www.upwork.com/jobs/~010ae27c329f45f3a6
