### ISSUE TITLE
[$500] Android - Split scan - Unable to select workspace as recipient when creating split scan in WS chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat > + > Request money.
3. Tap Split bill > Scan.
4. Upload a photo.
Note that we cannot select a workspace in participant page although we are now in the workspace chat.

## Expected Result:
User will be redirected to the confirmation page without the need to select a workspace since user is already in the workspace chat.

## Actual Result:
User is redirected to participant selection page and there is no way to select a workspace since workspace is not in the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dde0c749-96d8-4bb5-b204-9316dc3cc675

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135d3b2a39137f316</li>
        <li>Upwork Job ID: 1734225777714790400</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28035664</li>
<li>mkhutornyi | Contributor | 28035665</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by tgolen** [comment]
I'll take this and look into it.

**Comment by VenusWhisperer** [comment]
Hello, I can do it.
Plz share more detailed requirements.

**Comment by tgolen** [comment]
@mkhutornyi thanks. I think your proposal is close, but I think what I actually missed was using both `withWritableReportOrNotFound` and `withFullTransactionOrNotFound` for `IOURequestStartPage`. Could you look at updating your proposal to update `IOURequestStartPage` with those two HOCs instead?

**Comment by tgolen** [comment]
Ah, you're right... because those tabs can be opened directly sometimes, so they each need to be wrapped in those HOCs. I just noticed that `IOURequestStartPage` is also connecting to the same report and transaction in `withOnyx`, but it's probably overkill to wrap `IOURequestStartPage` as well as all the tabs.

**Comment by mallenexpensify** [comment]
Contributor: @mkhutornyi paid $500 via Upwork
Contributor+: @0xmiroslav owed $500 via Upwork 

I saw another contributor was hired, Volodymry L, but I don't see a reference here for work they've completed so I didn't pay. 

- https://github.com/Expensify/App/pull/32830#issuecomment-1856055144

PR hit production over a month ago, automation wasn't working so the `Reviewing` label wasn't removed and this hasn't gone overdue. 

Think we're good to close this
