### ISSUE TITLE
[HOLD for payment 2023-12-20] IOU - Incorrect animation display when selecting Split bill members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:

**First scenario:**
1. Open a New Expensify app
2. Log in with any account
3. Click on the green plus button (FAB)
4. Select Split bill
5. Select any currency and amount
6. Click next
7. Select any 10 users
8. Unselect all users one by one

**Second scenario:**
1. Open a New Expensify app
2. Log in with any account
3. Click on the green plus button (FAB)
4. Select Split bill
5. Select any currency and amount
6. Click next
7. In the search RHP, enter the address of any member
8. Select the member
9. Deselect the member
10. Repeat steps 8-9 several times

## Expected Result:
1. Selected members should move up without delay and not disappear from the menu, the animation should be smooth, and when canceling the selection of a user, he should return to his place without backing up in the list.
2. When selecting and deleting a group member in RHP via search, the contact list should not appear.

## Actual Result:
1. Incorrect animation when selecting and de-selecting group members in RHP. When selecting a member disappears from the list for 1 second and then appears, when de-selecting a member is first doubled, then moved.
2. When selecting and removing a group member in RHP via search, the contact list appears for a second and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f404c118-4294-4800-b252-9a967c332496

https://github.com/Expensify/App/assets/93399543/de2d781e-68a1-47c3-8023-92dc7bf3a54f

![image](https://github.com/Expensify/App/assets/93399543/90517f84-a5ca-4216-814f-1999f472ab39)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Looking into this now

**Comment by luacmartins** [comment]
Can't reproduce in prod, so this seems like a blocker.. Checking staging and dev next

**Comment by luacmartins** [comment]
Most likely coming from https://github.com/Expensify/App/pull/28618. I can't cleanly revert that PR to test if it solves the issues anymore though

**Comment by sophiepintoraetz** [comment]
Offer sent @situchan - will release payment once checklist has been completed.

**Comment by situchan** [comment]
1. https://github.com/Expensify/App/pull/28618
2. https://github.com/Expensify/App/pull/28618/files#r1432632018
3. N/A The regression came from huge money request refactor so this minor issue could be easily missed
4. No need another regression test as this was caught by QA team

**Comment by sophiepintoraetz** [comment]
paid!
