### ISSUE TITLE
[HOLD for payment 2024-01-17] [HOLD for payment 2024-01-03] [HOLD for payment 2024-01-02] HelpDot Migration / Improvements - Round 2! 

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#32825]
### Overview 
- We'll continue to assign all helpdot-related PRs to @rushatgabhane 
- @rushatgabhane works with the Design Team to make design changes to helpdot
- @rushatgabhane writes a how to guide in GitHub for how to make changes to helpdot

### Payment details
$4k for the entire job (end date March 1) with potential for bonus 👍

**Comment by maddylewis** [comment]
### Existing StackOverflows
#### Publishing/updating articles
- [How to: Publish an article on HelpDot (the file/subcategory already exists)](https://stackoverflowteams.com/c/expensify/questions/18032)
- [How to: Add a new article to HelpDot when the file doesn't exist](https://stackoverflowteams.com/c/expensify/questions/15135)
- [Edit the body of an article](https://stackoverflowteams.com/c/expensify/questions/15140)
- [Update the title of an article](https://stackoverflowteams.com/c/expensify/questions/15142)
- [Delete an article](https://stackoverflowteams.com/c/expensify/questions/15144)

#### Site structure
- [Create a new hub within the Help Site](https://stackoverflowteams.com/c/expensify/questions/15131)
- [Move an article from one hub to another](https://stackoverflowteams.com/c/expensify/questions/15138)

#### Images
- [How-to: add an Image to an ExpensifyHelp article](https://stackoverflowteams.com/c/expensify/questions/17454)

#### Markdown
- [ExpensifyHelp: How do I correctly format my article using markdown?](https://stackoverflowteams.com/c/expensify/questions/17353)

**Comment by maddylewis** [comment]
### Improvement request
- [ ] Clean up FAQ sections in each article by ensuring it's listed as `FAQ` and the section is collapsible - ADD GH HERE

**Comment by rushatgabhane** [comment]
issue here - https://github.com/Expensify/App/issues/33109
ETA for PR - today

**Comment by rushatgabhane** [comment]
Icon PR here https://github.com/Expensify/App/pull/33262

**Comment by francoisl** [comment]
Do we need to do anything for payment here or is it part of the HelpDot migration project?

**Comment by francoisl** [comment]
Ok I think payments for this project are handled separately so I'm going to close this, but feel free to reopen if that's wrong and we need to do something else here.

**Comment by maddylewis** [comment]
### Payment Details
- Ongoing Project: Improve HelpDot (Dec 1 - March 31) 
- Payment amount: $4k

cc @rushatgabhane - you're good to request payment via NewDot 👍

**Comment by JmillsExpensify** [comment]
$4,000 approved for @rushatgabhane based on summary.

**Comment by rushatgabhane** [comment]
this is paid and can be closed @maddylewis

**Comment by francoisl** [comment]
Closing based on the last message just above ^
