### ISSUE TITLE
Split - Adding a receipt to a manual split request turns it into a scan split request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click FAB button > + > Request money.
3. Enter amount > Next.
4. Click Split next to a few users > Next.
5. On the confirmation page, click 3-dot menu > Add a receipt.
6. Upload a photo and create the request.

## Expected Result:
The manual split request will remain as a manual split request.

## Actual Result:
The manual split request becomes a Scan split request after adding a receipt.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8b6adf27-9851-42cb-b9db-c685628e1851

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I can reproduce this, but it seems like we don't have the option to add a receipt to a split request in prod at all.
