### ISSUE TITLE
[LOW] Tags: Support independent, multi-level tags on workspace requests

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#32828]
It is possible for Collect policies to be configured to have independent multi-level tags if they are connected to QBO. As such, let's add support for creating/editing requests with independent multi-level tags. 

I'm guessing there will need to be both front-end and back-end components to this, but I'll leave it to @yuwenmemon to figure out the details. 

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by yuwenmemon** [comment]
I think this will be relatively simple, we already import all levels of tags into NewDot when you have them turned on:
![Screenshot 2023-12-18 at 7 48 43 PM](https://github.com/Expensify/App/assets/4741899/901b19c9-8c3f-4f1f-9bc9-b44194f187a9)

cc @amyevans in case you can think of any gotchas that might be out there.

**Comment by yuwenmemon** [comment]
Onyx updates from auth are already supported as well.

**Comment by yuwenmemon** [comment]
One thing to consider will be how to manage routes. The current setup is agnostic to any sort of "level" - we just show `${iouType}/new/tag/${reportID}` or `create/${iouType}/tag/${transactionID}/${reportID}/` or `r/:threadReportID/edit/:field`

**Comment by yuwenmemon** [comment]
One backend change we'll need to make is to start sending the tag level in the `MODIFIEDEXPENSE` system message. [Right now it ignores tag level](https://github.com/Expensify/App/blob/4aa6b03f973ac6bdb797dbe0a2b3748a55a07f98/src/libs/ReportUtils.ts#L2151-L2160), and we just assume the tag name is the first tag in the `tagLists`

**Comment by yuwenmemon** [comment]
I'll post some questions in the #wave6 room in the morning but so far this looks like it could be 3 GHs, with the main front-end one being able to be worked on by a Contributor.

**Comment by amyevans** [comment]
> one thing to consider will be how to manage routes

Yeah this was the biggest "gotcha" we saw going into the initial tags implementation in NewDot. We initially wrote in the doc that we'd use the tag list name in the route, "slug-ifying" the name (spaces to dashes, lowercase all letters, etc), and then decided to punt that to be a future problem (now 😄). Your idea of using the index is interesting though, could definitely side step some of the edge cases I was dreaming up with weird tag list names!

Being careful around the splitting on colon and edge cases with that is another potential gotcha (for example this code probably needs to be ported to NewDot: https://github.com/Expensify/Web-Expensify/blob/main/site/lib/expenseUtils.jsx#L10-L39).

But yeah overall I agree the lift isn't too bad here really!

**Comment by yuwenmemon** [comment]
Discussion about the route here: https://expensify.slack.com/archives/C01GTK53T8Q/p1703100843219419

Seems like we're leaning towards using an index-based route. Going to create an issue to fix the renaming bug with `policyRecentlyUsedTags_` and work on it, as that's a pre-existing bug that's a prerequisite to this feature anyway.

**Comment by garrettmknight** [comment]
Yuwen's out till 1/3

**Comment by yuwenmemon** [comment]
Created the front-end issue above and tagged @rezkiy37 and @waterim

**Comment by rezkiy37** [comment]
Sounds interesting, I would like to work on the issue. Posting a comment...

**Comment by yuwenmemon** [comment]
@rezkiy37 asked a few questions in the issue linked above - answered them coming back from OOO

**Comment by greg-schroeder** [comment]
Where do we stand on this one? Are you still taking this @rezkiy37?

**Comment by rezkiy37** [comment]
> Where do we stand on this one? Are you still taking this @rezkiy37?

I am actively working on this sub-issue: https://github.com/Expensify/App/issues/33983.

**Comment by yuwenmemon** [comment]
@rezkiy37's PR is awaiting further review from @allroundexperts

**Comment by yuwenmemon** [comment]
This is done. One follow up bug to fix here: https://github.com/Expensify/App/issues/37054
