### ISSUE TITLE
[$500] Assign task – Task checkbox is not marked when the task was completed by the assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to a 1:1 conversation
4. As user A Create a task
5. Navigate to the task conversation
6. Send message
7. Click the checkbox to Complete the task
8. Log in as the user that the task was shared with (User B)

## Expected Result:
ask checkbox is marked as the task was completed by the assignee

## Actual Result:
Task checkbox is not marked as the task was completed by the assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0f23e61f-3e5f-4811-8a61-ff369a64fb46

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b87e04522b9871b</li>
        <li>Upwork Job ID: 1734256413621731328</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
I think this should be fixed in one ticket
https://github.com/Expensify/App/issues/32389
https://github.com/Expensify/App/issues/31909

**Comment by c3024** [comment]
Correct. We should hold this till they get fixed.

**Comment by JmillsExpensify** [comment]
Moved to weekly while on hold.

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
#31909 is closed now, so removing the hold.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment]
Not reproducible anymore.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment]
Closing based on last two comments.
