### ISSUE TITLE
[HOLD for payment 2023-12-20] Android - IOU - Unable to capture receipt photo, the camera error displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28618

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Tap on FAB
3. Select Scan tab
4. Tap on Continue button and grant the camera permission
5. Tap on shot camera button

## Expected Result:
Receipt photo should be captured and user should be navigated on the attendee screen

## Actual Result:
Camera error displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4702a20e-fd5b-4d2a-9e24-1cb2f8349bb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
@mkhutornyi do you know what PR caused this regression? Looks like this part of the code didn't change recently.

**Comment by francoisl** [comment]
Ah ok got it, thanks. Still trying to confirm your solution but I'm getting an (unrelated) error trying to build android at the moment, looking into it.

**Comment by francoisl** [comment]
Ah ok great. Let's go with your solution then @mkhutornyi!

**Comment by situchan** [comment]
I can help with iOS testing. Confirmed fix on my iPhone


https://github.com/Expensify/App/assets/108292595/1a191519-34ee-422c-98bd-cd23ff0dfa3d

**Comment by francoisl** [comment]
Assigning a BZ to handle payment to @mkhutornyi.

**Comment by puneetlath** [comment]
@mkhutornyi can you send me your Upwork profile and I'll send you an offer?

**Comment by puneetlath** [comment]
Offer sent. Will play on Dec 20. 

https://www.upwork.com/nx/wm/offer/28060876

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
