### ISSUE TITLE
[$500] [HOLD for payment 2023-12-20] IOU - Currency is reverted to the original currency after switching between tabs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click FAB > Request money > Manual.
3. Select a different currency and change the amount.
4. Go to Scan tab.
5. Go to Manual tab.
The currency is not preserved.

## Expected Result:
The currency and amount will be preserved.

## Actual Result:
The currency is reverted to the original currency.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b88f50f4-88a9-4bae-8f27-8976aa3da796

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1265bf119a76d4b</li>
        <li>Upwork Job ID: 1734989360105709568</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Contributor | 28066539</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I have a fix up

**Comment by Julesssss** [comment]
PR merged and is being CP'd

**Comment by Julesssss** [comment]
@luacmartins this still seems to occur 😕 

![Screenshot 2023-12-12 at 17 36 48](https://github.com/Expensify/App/assets/10736861/fa1db1f1-88ac-4a71-b583-99a9ae22b422)


https://github.com/Expensify/App/assets/10736861/cee716f2-c0e1-4c58-a1c9-7894cdc6d685

**Comment by luacmartins** [comment]
Correct. We changed the behavior and both amount and currency should be reset.

**Comment by Julesssss** [comment]
Oh my bad, I need to stop working. Thank you

**Comment by Julesssss** [comment]
Ah, thank you

**Comment by michaelhaxhiu** [comment]
Ok looks like we owe C+ payment here:

>@0xmiroslav requires payment (Needs manual offer from BZ)

**Comment by michaelhaxhiu** [comment]
Payment due 12-20, so waiting

But here's the job - https://www.upwork.com/jobs/~01e1265bf119a76d4b

@0xmiroslav

**Comment by luacmartins** [comment]
Just pending payment

**Comment by michaelhaxhiu** [comment]
Waiting for job offer to be accepted

**Comment by michaelhaxhiu** [comment]
paid.
