### ISSUE TITLE
[WAITING ON CHECKLIST] Android - Request Money - A black area appears in the receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Tap + > Request money > Manual.
2. Enter amount and select a participant.
3. On the confirmation page, tap 3-dot menu > Add receipt.
4. Add a receipt.
5. Tap Continue and enable the camera while using the app
6. Take a picture

## Expected Result:
No black area appears in the receipt

## Actual Result:
A black area appears in the receipt

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/55aef52b-01ed-42c6-ac8e-bf6d13dfde8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111dc7857515d0314</li>
        <li>Upwork Job ID: 1734362601456140288</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 28039255</li>
</ul></li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
Most likely related to [this pr](https://github.com/Expensify/App/pull/28618). There are already another android scan issue linked as well, so it is likely the same issue

**Comment by stitesExpensify** [comment]
I'm also unable to test this because I don't have a physical android device

**Comment by jliexpensify** [comment]
Who's got 2 thumbs and a Pixel 3a? This guy.

**Comment by jliexpensify** [comment]
I'm on version 1.4.11-4. Can repro - the black screen is temporary, it appears for ~5 seconds.

**Comment by stitesExpensify** [comment]
@jliexpensify can you try scanning this QR code and testing again? https://github.com/Expensify/App/pull/32854#issuecomment-1850918421

**Comment by stitesExpensify** [comment]
Good to know! Have you identified the root cause?

**Comment by luacmartins** [comment]
Tested in staging. This is a pass.

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @mkhutornyi $500

[Upworks job here](https://www.upwork.com/jobs/~0111dc7857515d0314)

**Comment by jliexpensify** [comment]
Bump @parasharrajat to complete checklist.

Paid and job closed!

**Comment by luacmartins** [comment]
We already have steps covering this flow and QA caught this issue. So I think we're good without new steps.

**Comment by jliexpensify** [comment]
Thanks Rajat, test added!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat based on [this summary](https://github.com/Expensify/App/issues/32844#issuecomment-1853147946).
