### ISSUE TITLE
[HOLD for payment 2023-12-20] IOU - An error occurs when creating a Split Bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in with any account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Add multiple users to the Split Bill
8. Complete the Split Bill

## Expected Result:
No errors should occur when creating a Split Bill

## Actual Result:
When creating Split Bill, the error "Unexpected error creating this chat, please try again later" appears and when it's removed, the IOU disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4ded490e-6f3c-42e2-b891-8160704840bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by tgolen** [comment]
I'll take this. It's related to my recent refactoring

**Comment by abzokhattab** [comment]
I think this one fixes the current issue: https://github.com/Expensify/App/issues/32855#issuecomment-1850857612 i get no errors on creating a split request

**Comment by Julesssss** [comment]
@tgolen I believe it was [this PR](https://github.com/Expensify/App/pull/32896). I just added the link

**Comment by adelekennedy** [comment]
Just tested on staging - no errors for me

**Comment by tgolen** [comment]
@JmillsExpensify could you please pay @shubham1206agra for [their review](https://github.com/Expensify/App/pull/32896#issuecomment-1851890305) of the PR?

**Comment by JmillsExpensify** [comment]
Do we need a regression test on this one?

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @shubham1206agra for PR testing and review.

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by shubham1206agra** [comment]
Accepted

**Comment by JmillsExpensify** [comment]
Thanks! All paid out.
