### ISSUE TITLE
[$500] New message does not appear at the top in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701899637321999

## Action Performed:
1. Login to app as A
2. Receive a message from another account B
3. Look at the LHN of A

## Expected Result:
New message bumped to top 

## Actual Result:
Appears at the bottom and had to scroll all the way down to see the new message in LHN

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3a10fe54-4541-4b93-9015-1eefe892e434

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102f48fc205c1acfd</li>
        <li>Upwork Job ID: 1734315460365197312</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
Can't reproduce

https://github.com/Expensify/App/assets/74202751/e7176cd3-92da-44e2-bf91-55d8f691cc7b

**Comment by kaushiktd** [comment]
In this you can see the chat is below the deleted task. Here is the only one task which is deleted

https://drive.google.com/file/d/17bKCsJeg1TWsoIpLk2Iq79rk-T92ZMVQ/view?usp=sharing

Here is my another account chat where no deleted task so here chat appear in top

https://drive.google.com/file/d/1nSJYLM9qiKC1ZuyeleAxNVrgVmOHlrhS/view?usp=sharing

now in this account 3 task are deleted and chat appear after deleted task

https://drive.google.com/file/d/1eQWv1i-PdpoivOgclRXetyCZS2T3LCOi/view?usp=sharing

and in this account i have multiple task deleted task and chat appear after them here is the video

https://drive.google.com/file/d/1v4UcAoeNaLxWdeu2xdDEBNvTMLdVclxo/view?usp=sharing

so all in one conclusion , i can't reproduce the issue
