### ISSUE TITLE
[$500] Keyboard doesn't switch to number when creation Distance expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702063698355009

## Action Performed:

1. • Click FAB button
2. • Request Money > Distance
3. • Notice the keyboard open to alphabet keys not numbers keys

## Expected Result:
keyboard open to numbers keys

## Actual Result:
keyboard opens to alphabet keys

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![IMG_8317 1](https://github.com/Expensify/App/assets/38435837/0ce64b9c-f4b0-4046-9346-2419205e1637)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f3c4c158008fb99</li>
        <li>Upwork Job ID: 1734324950191570944</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

**Comment by samilabud** [comment]
This seems to be the expected result because you need to type the address using the alphabet key, e.g:

<img width="415" alt="image" src="https://github.com/Expensify/App/assets/5216036/4a93eb78-a2ea-48f2-a69f-ebaca109cc3e">

**Comment by neonbhai** [comment]
NAB, we need the full alphabet keyboard to enter address.
