### ISSUE TITLE
[$500] Android - Workspace - App crashes when add second member after killing the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to New dot App
2. Go to Settings> Workspace> Members> Invite
3. Invite any user and tap Next
4. Add custom invite message and tap Invite
5. Kill the app
6. Open the app
7, Go to Settings> Workspace> Members> Invite
8, Invite any user and tap Next

## Expected Result:
"Add message" screen should remain the previous message and user should be able to finish the flow

## Actual Result:
App crashes when add second user to workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c4405419-7bc8-4d90-a794-631b2f4df18b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195d5d4886bc42022</li>
        <li>Upwork Job ID: 1734325799100907520</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@situchan can you review this proposal, please? Thanks!

**Comment by situchan** [comment]
@ZhenjaHorbach are you able to reproduce constantly?

**Comment by trjExpensify** [comment]
@situchan what do you think about this proposal?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment]
@situchan can we get an update here, please?

**Comment by situchan** [comment]
I am back from holidays. Catching up today

**Comment by trjExpensify** [comment]
@situchan bump please, thanks!

**Comment by situchan** [comment]
@ZhenjaHorbach please update proposal based on latest codebase. That component was fully refactored in https://github.com/Expensify/App/pull/32139

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by situchan** [comment]
We can close this for now.
I will bump to reopen when reproducible again

**Comment by trjExpensify** [comment]
Sounds good!
