### ISSUE TITLE
[$500] Unable to add a debit card from transfer balance page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction (Requires gold wallet for transfer balance to appear)
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kadiealexander 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702271767885649

## Action Performed:
1. Head to Settings > Wallet > Balance Transfer in an account without a debit card linked
2. Click on "Instant (Debit card)"

## Expected Result:
You are taken to the page to add a debit card

## Actual Result:
You can highlight the button but clicking it does nothing.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (8)](https://github.com/Expensify/App/assets/38435837/772e3668-e685-489e-bf57-26bb91f97ad5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01247d064eb0f27081</li>
        <li>Upwork Job ID: 1737639325669695488</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
@michaelhaxhiu context [here](https://expensify.slack.com/archives/C049HHMV9SM/p1702271767885649)!

**Comment by michaelhaxhiu** [comment]
Sorry!!

**Comment by michaelhaxhiu** [comment]
Let's see if this is still reproducible by @m-natarajan! If so, I can double price to get more attention on it.

@akinwale you agree this is `external` right?

**Comment by michaelhaxhiu** [comment]
cant reproduce
