### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] Chat/Search – "Hmm it's not here" page displayed on tapping Learn more link in Referral page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log in with gmail account
3. Tap FAB button >> Start Chat >> Start a chat, get $250 banner >> learn more link
OR Tap search icon in LHN >> Invite/Refer a friend banner >> Learn More link

## Expected Result:
Relevant information page opens on tapping learn more link in referral page

## Actual Result:
"Hmm it's not here" page displayed on tapping Learn more link in Referral page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e739facb-0676-49a0-91db-5753294751c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a99efc46bd3c79d</li>
        <li>Upwork Job ID: 1734339151804612608</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28042576</li>
<li>neonbhai | Contributor | 28042578</li>
</ul></li>
    </ul>
</details>

**Comment by johncschuster** [comment]
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
Offers have been sent. We're waiting on a PR

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by johncschuster** [comment]
Ok! I'm back from OOO and will take this back over.

**Comment by johncschuster** [comment]
# Payment Summary:

- [x] @neonbhai - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/28042578) (Contributor)
- [x] @0xmiroslav - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/28042576) (Reviewer)

**Comment by johncschuster** [comment]
@0xmiroslav can you complete the BZ checklist above when you get a moment? Do we require any regression test steps?

**Comment by johncschuster** [comment]
Sounds good! In that case, we should be good to go!

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.29-1


https://github.com/Expensify/App/assets/78819774/040e032b-b66b-4b3f-922b-e4fb5e42a06b

Do we need to reopen this bug?
