### ISSUE TITLE
[$500] LHN - Admin's workspace chat with employee shows "User owes 0.00" while scan is in progress

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. As the employee, navigate to the workspace chat
3. Select Request money> Scan and finish the flow
4. While scan is still in progress check Admin's account

## Expected Result:
Admin should not see Request in LHN since is still in progress

## Actual Result:
Admins workspace chat with employee on LHN shows "User owes .... 0.00" while recipes have "still scan in progress" status

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6309682_1702331055946!Capture](https://github.com/Expensify/App/assets/78819774/1786aed2-d07c-4d73-be81-821ab22dbab9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dc9753e1dfc4205</li>
        <li>Upwork Job ID: 1734337603183050752</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment]
@dylanexpensify is this intended as part of drafts?

**Comment by peterdbarkerUK** [comment]
@dylanexpensify [friendly bump](https://github.com/Expensify/App/issues/32871#issuecomment-1870267165) for when you're back!

**Comment by peterdbarkerUK** [comment]
Bumped @dylanexpensify via DM

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by lanitochka17** [comment]
Issue  is still reproducible on the latest build 1.4.29-0


https://github.com/Expensify/App/assets/78819774/1f057775-5323-479d-8875-95f1fc753228

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Can't reproduce, @lanitochka17 can you try one more time? ty!!

**Comment by lanitochka17** [comment]
Issue is not reproducible with new build 1.4.36-2


https://github.com/Expensify/App/assets/78819774/041921db-751a-4887-805d-69c3eea05535

**Comment by dylanexpensify** [comment]
perf!

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.60-2

![image (9)](https://github.com/Expensify/App/assets/78819774/fa38f583-f7dd-48ad-9d45-e3e128c6f82f)

**Comment by dylanexpensify** [comment]
ah fun, must be a regression! Will investigate

**Comment by dylanexpensify** [comment]
@akinwale any initial ideas?

**Comment by akinwale** [comment]
@dylanexpensify I'll have another look, but it may actually require a backend fix based on this [earlier comment](https://github.com/Expensify/App/issues/32871#issuecomment-1852546871).

**Comment by dylanexpensify** [comment]
@akinwale anything found?

**Comment by dylanexpensify** [comment]
bump @akinwale

**Comment by akinwale** [comment]
Checking this today.
