### ISSUE TITLE
Web - Notification - Notification does not come when user switch back to online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32881]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign into account A on the main testing device
2. Sign into account B on a secondary device or browser
3. Go offline with account A
4. Account B send some messages to account A
5. Account A switch to online mode

## Expected Result:
Since user is online notification should appear when send message

## Actual Result:
Notification does not come when user switch back to online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c8bf0b7a-f8d2-4b35-afde-0c6479b78827

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
Not sure if this a deploy blocker per se, I think it might be delayed notifications? 🤔

**Comment by robertjchen** [comment]
Can we please test to see if this is still an issue? Thanks!
