### ISSUE TITLE
[$500] IOU-Employe's Expense request is displayed for Admin while the receipt is still in scan process

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. As the employee, navigate to the workspace chat
2. Upload a image of a blurry receipt
3. Complete the money request
4. Login as the workspace admin
5. Navigate to the workspace chat with the employee

## Expected Result:
Expense requests that have the scan in progress status should not be displayed for the other members of the workspace. These should only display after the scan is successful and complete

## Actual Result:
Request is displayed for Admin while the receipt is still in scan process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6309744_1702336401252!Capture1](https://github.com/Expensify/App/assets/78819774/dc0447ef-f86f-45a3-a5bf-6bd00819eb52)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194f854fd163d1685</li>
        <li>Upwork Job ID: 1734363175696928768</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
This is a back-end issue, a dupe and it was posted and closed before as it's being handled somewhere else. More details here https://github.com/Expensify/App/issues/29859#issuecomment-1811655770

**Comment by narefyev91** [comment]
@zanyrenney based on this https://github.com/Expensify/App/issues/32883#issuecomment-1851170228 we can close this one

**Comment by narefyev91** [comment]
Friendly ping @zanyrenney

**Comment by zanyrenney** [comment]
CLOSING, apologies for the delay!
