### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Distance- Request created offline does not show TBD in many areas and unable to open distance editor

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#32891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.11-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to a workspace chat > + > Request money > Distance.
4. Create a distance request.
5. Click on the distance request preview twice to open the details page.

## Expected Result:
- The header of expense details page, Amount row, and receipt show TBD.
- Distance row will remain as "Distance" and user is able to open distance editor when the distance request is created offline.

## Actual Result:
The distance request created in offline mode behaves like a Scan request.

- The header of expense details page shwos "Receipt missing details".
- Receipt shows attachment thumbnail rather than the e-receipt.
- There is a red dot next to Amount row instead of TBD.
- Distance row is displayed as Merchant and user cannot open distance editor page when the request is created offline.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/e38a56ed-3367-49d7-bf61-13d820ee1da9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01366049b9ef5743ae</li>
        <li>Upwork Job ID: 1734441817651273728</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28045822</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by techievivek** [comment]
@dukenv0307 Is this linked to a recent change? Do you mind linking the PR? Thanks

**Comment by techievivek** [comment]
Also, adding the external label so a C+ can review the above proposal.

**Comment by Julesssss** [comment]
> @ArekChr Any thought on my proposal?

I'm reassigning to @allroundexperts

**Comment by luacmartins** [comment]
@dukenv0307 your proposal looks good. Are you available to work on a PR within the next hour?

**Comment by allroundexperts** [comment]
@luacmartins Have you seen @bernhardoj's proposal?

**Comment by luacmartins** [comment]
Yes, we discussed it internally and we think @dukenv0307's proposal is more in line with the new logic we want to move to

**Comment by luacmartins** [comment]
All yours!

**Comment by luacmartins** [comment]
Tested in staging. This is a pass.

**Comment by MitchExpensify** [comment]
Added a reminder to pay, please review the BZ list in the meantime @allroundexperts - Thanks!

Payment summary:

- $500 @allroundexperts requires payment through NewDot Manual Requests
- $500 @dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28045822) (Contributor)

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/28618
2. N/A
3. N/A
4. For regression test, the steps mentioned in the OP seem pretty clear to me!

**Comment by MitchExpensify** [comment]
Paid and contract ended!

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/32891#issuecomment-1858421818).
