### ISSUE TITLE
Web - Split - Scan bill split is created in one of the participants' chat instead of new group chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#32895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click FAB > Request money > Scan.
3. Enter amount > Next.
4. Select two users that have existing IOUs > Click Split.
5. Create the bill split.

## Expected Result:
The bill split is created in a new group chat with the selected users.
## Actual Result:
The bill split is created in one of the participants' 1:1 DM instead of a new group chat.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x ] iOS: mWeb Safari
- [x ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a15b98fa-f575-4485-9ecd-f26f4259d487

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment]
same as https://github.com/Expensify/App/issues/32855

**Comment by MariaHCD** [comment]
This does look to be similar to #32855. Closing in favor of that issue.

**Comment by shubham1206agra** [comment]
@Julesssss @MariaHCD The fix does not seem to fix this issue. Please reopen this

**Comment by Julesssss** [comment]
Hey @shubham1206agra just to confirm, even with the changes from the [linked PR](https://github.com/Expensify/App/pull/32896) (which haven't yet been merged)?

**Comment by shubham1206agra** [comment]
Yes
It just opens the wrong report (more specific, of first participant)

**Comment by shubham1206agra** [comment]
Fix seems to be relatively easy. I will fix this in another PR

**Comment by Julesssss** [comment]
Thanks, reopening.  I will assign you now @shubham1206agra. 

@MariaHCD I'll try to keep an eye on this one but we have about 20+ blockers so it would be great if you could also keep on eye on any developments here. Thanks

**Comment by Julesssss** [comment]
> Fix seems to be relatively easy. I will fix this in another PR

Hey @shubham1206agra just checking which PR you fixed this in?

**Comment by shubham1206agra** [comment]
https://github.com/Expensify/App/pull/32918

**Comment by Julesssss** [comment]
Thanks, I just merged that fix. We'll test it on staging
