### ISSUE TITLE
[$500] Wallet-Tapping "Enable wallet",add bank account page with select Chase is displayed.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces ---- Workspace
4. Tap bank account
5. Tap Connect online with plaid
6. Select Chase
7. Select Plaid saving 1111 and complete the flow
8. Note the Bank account is added
9. Navigate back to Wallet
10. Tap Enable Wallet

## Expected Result:
After adding BA using chase, if user taps enable wallet, add bank account page with select Chase must not be displayed.

## Actual Result:
After adding BA using chase, if user taps "Enable wallet", add bank account page with select Chase is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/32c752d9-a68a-4945-a9d6-373795880aae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4b60b3ea27982ee</li>
        <li>Upwork Job ID: 1734518482870845440</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
Hmm.. I could reproduce it, and it seems this happens only once after the setup. There must be something remaining in the cache. I'll continue looking.

**Comment by cristipaval** [comment]
I think this is reproducible in production as well. I couldn't find a PR that could have introduced this regression. But I found the reason why this happens. It's because the `plaidLinkToken` Onyx key is not cleared when the user goes to `WalletPage` and [this code flow](https://github.com/Expensify/App/blob/ee6bde5d66ecdae34cb9692c22100280a09c1624/src/components/AddPlaidBankAccount.js#L202) opens the `PlaidBankAccountSelector`

**Comment by luacmartins** [comment]
Nice! @cristipaval can you work on a PR to fix this?

**Comment by nkuoch** [comment]
What is called when clicking on enabled wallet?
I thought it would call this:
<img width="1023" alt="image" src="https://github.com/Expensify/App/assets/2463975/fb9d90e8-9bec-4c6d-9346-79a8bed182b3">

but maybe not as Plaid is not cleared.
So just follow what is called in this flow and make sure `clearPlaid()` is called before Plaid view gets rendered

**Comment by luacmartins** [comment]
We navigate straight to the add bank account page: [BaseKYCWall > continueAction > selectPaymentMethod](https://github.com/Expensify/App/blob/292ad52549b0d6fc6f5bbb9fa73a9eb4ead72c2e/src/components/KYCWall/BaseKYCWall.js#L121)

**Comment by luacmartins** [comment]
Put up fix PR

**Comment by cristipaval** [comment]
Thanks @luacmartins for fixing this one for me! 🙏

**Comment by JmillsExpensify** [comment]
@fedirjh Mind kicking off the BZ checklist above?

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor+: $500 for PR review

**Comment by cristipaval** [comment]
Thank you @fedirjh!

**Comment by JmillsExpensify** [comment]
Thanks @fedirjh! Sent you an offer via Upwork just now.

**Comment by JmillsExpensify** [comment]
All paid out and regression test created. Thank you!
