### ISSUE TITLE
[$500] Web - IOU-After refreshing page green dot disappears in LHN chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32917]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/ as user A
2. Tab fab
3. Tap request money--- manual
4. Enter an amount
5. Tap next
6. Select user B
7. Tap request
8. Login as user B
9. Note green dot on 1:1 chat
10. Refresh the page

## Expected Result:
The green dot on chat in LHN must not disappear after refreshing the page.

## Actual Result:
The green dot on chat in LHN must not disappear after refreshing the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6d21e918-c41f-4d23-931f-2f6db422ab49

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b698715da7076ac6</li>
        <li>Upwork Job ID: 1734544059387871232</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
@izarutskaya 
The actual result and expected result are same.

**Comment by laurenreidexpensify** [comment]
hold on #32590

**Comment by laurenreidexpensify** [comment]
#32590 will be on prod for 7 days tomorrow

**Comment by laurenreidexpensify** [comment]
@situchan @bernhardoj can you confirm if this is still reproducible now that https://github.com/Expensify/App/issues/32590 is fixed?

**Comment by laurenreidexpensify** [comment]
@Expensify/applauseleads can you confirm if this is reproducible in KI testing this week thanks

**Comment by laurenreidexpensify** [comment]
@applausebot @Expensify/applauseleads can you confirm if this is reproducible in KI testing this week thanks
