### ISSUE TITLE
[$500] IOU - IOU report remains in LHN instead of hidden after sending and deleting message in the report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Click FAB > Request money > Manual.
2. Create a manual request.
3. Cllick on the IOU preview.
4. Return to 1:1 DM.
5. Note that IOU report is hidden from LHN when it is not opened.
6. Click on the IOU preview and send a message in IOU report.
7. Delete the message.
8. Return to 1:1 DM.
Note that IOU report is still not hidden when the message is deleted.

## Expected Result:
The IOU report will be hidden from LHN when it is not opened since the message added in Step 6 is deleted.

## Actual Result:
The IOU report remains in LHN when it is not opened after the message is deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fc329b1a-a6d1-48fc-a79b-d22ef2b4dedf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec6c59ffd1ee613d</li>
        <li>Upwork Job ID: 1734541675468886016</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This happens because by default, the notificationPreference of an IOU report is set to hidden. However, after sending a message, it's changed to "always" and is not changed back on deleting the messages.

### What changes do you think we should make in order to solve the problem?
When deleting messages from IoU Report, we should check if there are any non-IOU actions left. If not – set the `notificationPreference` back to `hidden`.

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment]
Reviewing today

**Comment by alitoshmatov** [comment]
@dukenv0307 Can you elaborate and show where exactly are you going to apply those changes

**Comment by miljakljajic** [comment]
@dukenv0307 - friendly bump!

**Comment by alitoshmatov** [comment]
It looks like we might have backend issue here. 

When we go to money request thread backend is sending `notificationPreference` as `hidden`

<img width="829" alt="Screenshot 2023-12-30 at 01 15 45" src="https://github.com/Expensify/App/assets/59907218/6ba4bfc6-106a-4169-a344-de99d6596f7c">

When we add comment `notificationPreference` is set to `always`

<img width="923" alt="Screenshot 2023-12-30 at 01 16 31" src="https://github.com/Expensify/App/assets/59907218/80dc2fc7-84cf-45b2-8973-f9a7975518bb">

But when we delete notification preference is not reversed

<img width="1077" alt="Screenshot 2023-12-30 at 01 16 57" src="https://github.com/Expensify/App/assets/59907218/7ff0f919-4a3c-4c08-b7d2-b296102ee770">

And everytime we open request money thread, backend is sending notification pre
<img width="630" alt="Screenshot 2023-12-30 at 01 18 35" src="https://github.com/Expensify/App/assets/59907218/25c36ed3-15e3-4a48-8583-479bb182a06f">
ference as `always`

**Comment by alitoshmatov** [comment]
@miljakljajic Can we get internal engineer to have a look at this, since it might be a backend issue

**Comment by alitoshmatov** [comment]
@dukenv0307 I agree with you, but we should wait for internal engineers take on it

**Comment by miljakljajic** [comment]
Hey @nkuoch - do you think this needs to be worked on by an internal engineer?

**Comment by nkuoch** [comment]
I think so yes

**Comment by nkuoch** [comment]
cc @jasperhuangg as I see you worked on this (https://github.com/Expensify/Auth/pull/9145)

**Comment by miljakljajic** [comment]
@jasperhuangg any thoughts?

**Comment by jasperhuangg** [comment]
Sorry was OOO! Taking a look

**Comment by mountiny** [comment]
> So I feel like this behavior is actually fine–I don't think we really need to be updating the user's notification preference back to hidden when they delete a comment that they posted that updated their notification preference to always.

I agree

**Comment by miljakljajic** [comment]
Thank you guys, I'll close!
