### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Compose-Tapping on request money deep link app crashes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. From slack tap on the link https://staging.new.expensify.com/request/new/manual

## Expected Result:
Tapping on request money deep link app must not crash.

## Actual Result:
Tapping on request money deep link app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7f7fb742-8f96-448d-a486-42deb573dda2

[Bug6309943_1702351647217!cras.txt](https://github.com/Expensify/App/files/13647320/Bug6309943_1702351647217.cras.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138e42333faa67e02</li>
        <li>Upwork Job ID: 1734531208461672448</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28042311</li>
<li>Pujan92 | Contributor | 28042312</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Crash on request money link opening

### What is the root cause of that problem?
We are using an invalid const variable for the TopTab.Screen name
https://github.com/Expensify/App/commit/094cc2e79687467603fac2b7d44a9c234b5e7384
https://github.com/Expensify/App/blob/2d8523ae3fd8a5b692700a91efb90adac7f1175f/src/pages/iou/MoneyRequestSelectorPage.js#L123-L125

### What changes do you think we should make in order to solve the problem?
Correct the CONST variables for the screens name with `CONST.TAB_REQUEST` instead of `CONST.TAB`

**Comment by lakchote** [comment]
@Pujan92 as it's a time-sensitive issue, please do a PR in a timely manner, thank you.

**Comment by Pujan92** [comment]
> @Pujan92 as it's a time-sensitive issue, please do a PR in a timely manner, thank you.

Sure, will raise it soon.

**Comment by Pujan92** [comment]
@jjcoffee @lakchote [PR](https://github.com/Expensify/App/pull/32916) is ready!

**Comment by kavimuru** [comment]
@Pujan92 Now we get app crash when tapping on the request money in the Fab in Android and iOS. Should the above mentioned PR will fix that too?

Uploading Crash.mp4…

**Comment by jjcoffee** [comment]
@kavimuru Sounds unrelated, can you share repro steps?

**Comment by kavimuru** [comment]
1. Open app
2. Tap on FAB > Request Money

**Comment by Julesssss** [comment]
Hey @kavimuru I caused that issue and I fixed it [here](https://github.com/Expensify/App/pull/32925), staging should work again very soon

**Comment by stephanieelliott** [comment]
I'm working on testing this one

**Comment by joekaufmanexpensify** [comment]
@stephanieelliott I actually just re-tested this one [here](https://expensify.slack.com/archives/C07J32337/p1702403198790669?thread_ts=1702401544.262399&cid=C07J32337)!

**Comment by NicMendonca** [comment]
@jjcoffee @Pujan92 you've both been paid

**Comment by NicMendonca** [comment]
all set here!
