### ISSUE TITLE
[HOLD for payment 2024-01-11] [Wave 6: Drafts] Make GBR optimistically reflect if harvesting is enabled

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#32920]
### Problem

When draft report is created, the GBR on the report should depend on the policy settings called `harvesting` which means if the Scheduled submit is turned on. If harvesting is enabled hence true, then we do not have to show the GBR because the report should submit on its own. 

Now we do not have this logic in App

### Solution

Pass this policy property to the app and optimistically set the GBR if not enabled

**Comment by mountiny** [comment]
WEP draft out there but I will have to create a App PR too

**Comment by mountiny** [comment]
PRs are up, i need to test the App one too

**Comment by johncschuster** [comment]
@mountiny do you need anything from me on this, or am I just along for the ride? (I ask because I'm going OOO, and need to know if I should reassign while I'm out)

**Comment by mountiny** [comment]
We might need to handle payments for C+ but no need to worry for now

**Comment by johncschuster** [comment]
Ok great! Thanks for the heads up! I'll be OOO until January 2. If payment needs to be issued before that date, please reassign so this isn't held on me! 🙏

**Comment by mountiny** [comment]
Payment handled here https://github.com/Expensify/App/issues/33443 so we can close this issue now

Regression tests will be added in general for drafts
