### ISSUE TITLE
[HOLD for payment 2024-01-02] [$500] IOU -Admin is unable to add receipt on Employee's expense request but the placeholder displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32923]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in as the employee
2. Navigate to a expense request conversation that has a receipt
3. Click on the receipt thumbnail
4. Click on Delete Receipt from 3 dot menu on the top right
5. Log in as admin
6. Navigate to the expense from Step 2
7. Click on "+" button from deleted receipt ( click once and click few times)

## Expected Result:
Since placeholder shows up, admin should be able to add receipt

## Actual Result:
Admin is unable to add receipt on Employee's expense request but the placeholder still shows up.
Clicking on it fast enough will redirect admin to report page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b64ad6fb-5602-4f3c-9429-7e375838cb8d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1dbb186e5ac4d8c</li>
        <li>Upwork Job ID: 1734583185483804672</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28064656</li>
</ul></li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
@sobitneupane can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment]
Bump @sobitneupane for urgency. Thanks!

**Comment by sobitneupane** [comment]
Thanks for the proposal @bernhardoj 

Proposal from @bernhardoj looks good.

🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment]
Payment summary:

@sobitneupane $500 for C+ review / Requires payment through NewDot Manual Requests.
@bernhardoj, $500 for fixing the issue. Payment processed in Upwork.

**Comment by isabelastisser** [comment]
@sobitneupane Please complete the checklist so I can close this issue. Thanks!

**Comment by isabelastisser** [comment]
Bump @sobitneupane

**Comment by isabelastisser** [comment]
@sobitneupane, please provide an update!

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/31024
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/31024#issuecomment-1878801482
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was missed during the testing of linked PR.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
Regression Test Proposal:

- As an employee, request money on the policy expense chat or open an existing money request detail
- (If there is a receipt, delete/remove it) Verify there is an add receipt thumbnail.
- As an admin, open the money request detail
- Verify add receipt thumbnail is hidden

Do we agree 👍 or 👎

**Comment by isabelastisser** [comment]
>  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

https://github.com/Expensify/Expensify/issues/357292

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/32923#issuecomment-1874431183).
