### ISSUE TITLE
Implement the full Screen Settings page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32940]
As part of the Ideal Nav overhaul, implement the Full Screen settings according to the requirements specified in [the design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit).

Parent Issue: #32689

**Comment by kosmydel** [comment]
Hey, I’m from Software Mansion and I will work on this issue.

**Comment by twisterdotcom** [comment]
Still in draft.

**Comment by hayata-suenaga** [comment]
@kosmydel feel free to mark the PR ready for review so that you can get feedbacks early in the progress 🙇

**Comment by kosmydel** [comment]
> @kosmydel feel free to mark the PR ready for review so that you can get feedbacks early in the progress 🙇

Hey, sorry for not posting an update here. 
This change will be included in our [internal feature branch](https://github.com/software-mansion-labs/expensify-app-fork/tree/ideal-nav-merge). We did it, as we had to glue Bottom Tab Navigator with Full Screen Settings, and it was easier to maintain it that way. So to sum up, it will be one PR with navigation changes.

**Comment by kosmydel** [comment]
Hey, the PR including full-screen account settings is available [here](https://github.com/Expensify/App/pull/33280).

**Comment by twisterdotcom** [comment]
@hayata-suenaga do we need a C+ assigned here for payment too. That PR has @blazejkustra reviewing - should I assign them here too?

**Comment by twisterdotcom** [comment]
Bump on my Q @hayata-suenaga.

**Comment by twisterdotcom** [comment]
@s77rt you're testing it seems in the PR. Are you assigned somewhere else for this? Or do you need assigning for payment for that here? Otherwise, I think this issue can be closed given this is being resolved by the larger PR for ideal nav.

**Comment by hayata-suenaga** [comment]
@twisterdotcom I apologize I was OOO

I don't think we don't need payment for @s77rt because we don't even have a PR for this issue (the code change was done in the Software Mansion's internal branch.

**Comment by s77rt** [comment]
I'm not sure where I'm supposed to be assigned. Maybe it should be in the parent issue https://github.com/Expensify/App/issues/32689

**Comment by hayata-suenaga** [comment]
@s77rt did you review any PR for this issue?

**Comment by s77rt** [comment]
No but those 2 PRs (full screen navigator and bottom tabs navigator) are being handled in one PR here https://github.com/Expensify/App/pull/33280

**Comment by s77rt** [comment]
So technically yes 😅 I'm reviewing those PRs

**Comment by hayata-suenaga** [comment]
ah I see they didn't link the issue to their PR... can you ask in the PR to be assigned to any of the relevant issues? I'm sorry for the confusion 🙇

**Comment by s77rt** [comment]
Should we close this and https://github.com/Expensify/App/issues/32941? The relevant issue is the parent issue
