### ISSUE TITLE
Implement Bottom Tab Navigator

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32941]
As part of the Ideal Nav overhaul, implement the Bottom Tab Navigator according to the requirements specified in [the design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit).

Parent Issue: https://github.com/Expensify/App/issues/32689

**Comment by hayata-suenaga** [comment]
@adamgrzybowski from Software Mansion is going to work on this issue 🎉

**Comment by adamgrzybowski** [comment]
👋

**Comment by joekaufmanexpensify** [comment]
Going to unassign myself for now, since this we already have someone assigned for this, and it's a new feature rather than a bug. If any BZ work (like issuing payment) is required at any point, please re-assign me, and I'll handle it!

**Comment by hayata-suenaga** [comment]
I remember @adamgrzybowski is taking OOO. I'll change the priority of this issue to `weekly` until he's back.

**Comment by trjExpensify** [comment]
Critical priority, putting this back on `Daily` now we're all back.

**Comment by hayata-suenaga** [comment]
@adamgrzybowski let me know if you're working on this one in the internal branch of Software Mansion's

**Comment by flaviadefaria** [comment]
This implementation is also important for Travel V1 so excited to see that this is a critical priority again!

**Comment by hayata-suenaga** [comment]
The work is being down in [this PR](https://github.com/Expensify/App/pull/33280).

Vit made an ad hoc build out of that branch. You can access the build at this URL: https://33280.pr-testing.expensify.com/

**Comment by hayata-suenaga** [comment]
I'll change the priority of this issue to weekly as the PR is actively being worked on.

we just need this issue to figure out when the work is done

**Comment by luacmartins** [comment]
assigning myself to help review and get this merged asap since it's a blocker for simplified collect

**Comment by s77rt** [comment]
Can someone assign me here?

**Comment by luacmartins** [comment]
Done!

**Comment by hayata-suenaga** [comment]
@s77rt were you assigned here for the big feature branch you reviewed? I feel like I assigned you somewhere else 🤔

**Comment by hayata-suenaga** [comment]
@s77rt you were assigned to [this issue](https://github.com/Expensify/App/issues/32689?notification_referrer_id=NT_kwDOBd_pMrM4Njg1NzY2NjkyOjk4NTYwMzA2&notifications_before=Y3Vyc29yOjI2&notifications_query=org%3AExpensify#issuecomment-1932608295)

**Comment by s77rt** [comment]
@hayata-suenaga Maybe deja-vu? 😅 Yeah I'm assigned there too. That's the main issue. This one is only part of it. I thought it makes sense to be assigned on both.

**Comment by hayata-suenaga** [comment]
I made you're paid more than the standard amount for the PR you reviewed in the other issue.

I'll keep you assigned to this issue, but payment is not needed here

also, closing this issue as the PR has been deployed to production
