### ISSUE TITLE
[HOLD for payment 2024-01-04] Implement Workspace List Item

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32956]
Implement the new Workspace List Item displayed on the Settings page of the Expensify/All workspace.

This is a sub-issue of this parent issue #31766

**Comment by hayata-suenaga** [comment]
@MaciejSWM, this is a sub-issue of the parent issue #31766. I created this for the PR #32817. Please comment in this issue so that I can assign you here.

**Comment by MaciejSWM** [comment]
✅

**Comment by cead22** [comment]
I think Melvin is drunk because I'm not sure why it assigned me to this issue

**Comment by trjExpensify** [comment]
Okay, payment is due! That's $500 to @aimane-chnaif for the C+ review of the PR, corect?

WRT to the regression test, this isn't live yet as it's part of the ideal nav skeleton rollout. We'll be handing the regression test script over to Applause once its live.

**Comment by trjExpensify** [comment]
Yep, that's the plan as part of the rollout of the project! We have them written from the design doc.

**Comment by trjExpensify** [comment]
Cool, I'll pay this one separate as it has a different issue. :)

**Comment by trjExpensify** [comment]
Alright, sent an offer for this!

**Comment by trjExpensify** [comment]
Paid!
