### ISSUE TITLE
[$500] Web, Desktop - Message actions - Limited action items displayed on reply in thread hover

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Hover and click on reply in thread on message sent in step 3
5. Keep the hover on reply in thread message, observe that for sometime, it displays correct action item before changing to only 2 items
6. Go back to parent report
7. Again hover and click on reply in thread on same message as used in step 3 and 4
8. Observe that now it displays all the action items

## Expected Result:
App should display all available action items on reply in thread on any message even on first time click on reply in thread and hover on the message

## Actual Result:
App displays limited action items on hover on reply in thread message after first time click on reply in thread button on new message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb2af1e4-a0cc-4fa9-bc29-6d31821b710d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01471e600d6f5d0940</li>
        <li>Upwork Job ID: 1734943767131348992</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by c3024** [comment]
Yes, this can be closed. @kevinksullivan
