### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] Distance - App crash on start finish change

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Click on plus and click on request money
3. Click on distance
4. Interchange 'Start' and 'Finish' by drag and observe that app crashes

## Expected Result:
App should not crash on interchanging 'Start' and 'Finish' in distance

## Actual Result:
App crashes on interchanging 'Start' and 'Finish' in distance

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d1885dbf-0477-46a8-81ed-4a79fd4ffc4a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573f0c0196ba5533</li>
        <li>Upwork Job ID: 1734923373233876992</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28052012</li>
<li>bernhardoj | Contributor | 28052013</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
@0xmiroslav any updates on the PR? Thank you!

**Comment by CortneyOfstad** [comment]
Payments have been completed! 

Any update on the checklist @0xmiroslav? Thanks!

**Comment by CortneyOfstad** [comment]
Sounds good! Closing!
