### ISSUE TITLE
[$500]  Web - Chat - Incorrect URL of opened image

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open https://staging.new.expensify.com/

2. Open any conversation
3. On a conversation, click on the + button in the compose box
4. Click on 'Add Attachment' > Select .jpeg or .png image
5. Click on Send
6. Click on the image
7. Right click on the image and click on open image in new tab

## Expected Result:
The URL of opened image starts with "[https://staging.new.expensify.com/chat-attachments/"](https://staging.new.expensify.com/chat-attachments/%22)

## Actual Result:
The URL of opened image starts with "[https://staging.expensify.com/chat-attachments/"](https://staging.expensify.com/chat-attachments/%22)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8cd83c25-e6cf-4674-b83d-636ec62ef748

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179f950acd49cf5b3</li>
        <li>Upwork Job ID: 1734958993007403008</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
I can reproduce but this is such a small issue that's not breaking usability - closing for now
