### ISSUE TITLE
HIGH - Report is marked as unread in the LHN on own approval

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32995]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701213078389819

## Action Performed:
1. Navigate to a report that requires approval in NewDot
2. Approve the report

## Expected Result:
The report is not marked as unread

## Actual Result:
The report is marked as unread in your LHN, despite you having just taken that action

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/40cf869a-7ef5-47c1-a746-2a3cd65fdee6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Issue not reproducible locally https://expensify.slack.com/archives/C02NZ2HGJAZ/p1702605423025179?thread_ts=1702482424.223549&cid=C02NZ2HGJAZ, probably because of the latest changes that we've been working on

**Comment by sonialiap** [comment]
@marcochavezf since you can't reproduce, should we close?

**Comment by marcochavezf** [comment]
Yup, I tested locally and wasn't able to reproduce it:

https://github.com/Expensify/App/assets/6829422/f56f86b1-caf8-4401-ad3f-c0b734f0f8ab

https://github.com/Expensify/App/assets/6829422/c9f14073-b8b1-4573-936d-a3dfc2b3993e
