### ISSUE TITLE
Expensify shows that I paid someone but the payment failed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @saracouto 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702072130270899

## Action Performed:
1. Receive a IOU request from Account B to Account A
2. Pay the request using  "Pay with expensify"
3. Open the details

## Expected Result:
There should be no error as it was a successful payment

## Actual Result:
Unexpected error please try again later message appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![2023-12-08_16-46-50 (2)](https://github.com/Expensify/App/assets/38435837/5ea1a70c-83e7-498e-bcb2-7d1871291b40)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3e2585a0eb0025d</li>
        <li>Upwork Job ID: 1745129246455173120</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Getting clarification on platforms impacted via Slack

**Comment by bfitzexpensify** [comment]
@Beamanator any thoughts on this one? I see it referenced in https://github.com/Expensify/Expensify/issues/335366 - looks like the wallet is 'Pending' which is throwing the error, even though the payment was successful?

**Comment by Beamanator** [comment]
Yeah that seems to be the problem, though I haven't looked into _why_ this is happening, @robertjchen not sure if you've looked into this since this seems to be between you & sara?

**Comment by bfitzexpensify** [comment]
@Beamanator lemme know if I should assign someone else or if you can take a look at this one

**Comment by Beamanator** [comment]
Sorry I'm hoping to have more free time to look into this next week when I'm back in cairo after the holidays - if this currently only affects sara, i think we can lower the priority maybe? Unless it's a huge paid and delaying her a ton from important things

**Comment by bfitzexpensify** [comment]
I think that it's fair to lower the priority on this

**Comment by getusha** [comment]
Not overdue, low priority.

**Comment by bfitzexpensify** [comment]
@Beamanator what do you think here? Since there have been no other reports, should we close this?

**Comment by Beamanator** [comment]
@bfitzexpensify I was just thinking that, yeah I like that plan

**Comment by bfitzexpensify** [comment]
Cool, let's close this out and re-investigate if we get more reports.
