### ISSUE TITLE
[HOLD for payment 2023-12-29] Adding onyx keys and types for policy report fields and recently used report fields

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32994]
https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.dbp78kbhqu10

https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit#bookmark=id.vc9g68afuwfz

**Comment by allroundexperts** [comment]
PR https://github.com/Expensify/App/pull/33034

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
