### ISSUE TITLE
[$500]  IOU - Expense rule for category selection continues to have an effect even after deletion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: User must be an employee of a workspace.
1. On OD, create an Expense rule for category selection (e.g. if the name of the merchant contains "Test", auto-assign "Equipment" as the category)
2. On ND, create an expense on workspace where the merchant contains "Test", so the category should be auto-assigned to "Equipment"
3. Go back to OD and delete the expense rule
4. Go to ND and create a new expense where the merchant contains "Test" once more

## Expected Result:
There should be no category selected

## Actual Result:
Category is auto-assigned again as if the expense rule is active

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3c8d8f40-48c9-4fe3-adfc-88067f590512

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1ae3ab6c8e778ca</li>
        <li>Upwork Job ID: 1735036077123293184</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
This is OD and BE bug, not ND bug, that's because BE is actually returning the `category` as `equipment` after the rule is removed so the rule must be remaining in the BE for some reason.

**Comment by samilabud** [comment]
Confirmed, this is a BE bug, this is the request and the response from API:
We are not sending the category:
<img width="614" alt="Screenshot 2023-12-13 at 6 32 17 PM" src="https://github.com/Expensify/App/assets/5216036/8991cf99-0829-42fa-a97b-d2c5835f98d3">
We receive the category from API:
<img width="554" alt="Screenshot 2023-12-13 at 6 35 48 PM" src="https://github.com/Expensify/App/assets/5216036/0f117ef6-7856-46bb-a332-e831fef7ac4b">

**Comment by jjcoffee** [comment]
Agree this looks like a BE issue, let's make this internal @muttmuure.

**Comment by muttmuure** [comment]
This is likely [implicit categorization](https://community.expensify.com/discussion/5688/deep-dive-implicit-categorization#:~:text=Implicit%20categorization%20will%20only%20apply,an%20explicit%20category%20already%20assigned.), which means it is not a bug.
