### ISSUE TITLE
[Wave 6: Bottom Up] Email is missing in membersData

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33018]
### Problem

The bottom up flow stopped working because we do not store the IOU requestor email the same way as when implemented. We are migrating away to use accountIDs and we should do the same here.

Logs [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22CreateWorkspaceFromIOUPayment%22%20AND%20email%3A%22admin%2B882023%40tulacostarica.com%22%20AND%20timestamp%3A%5B2023-12-13T00%3A00%20TO%202023-12-14T23%3A59%5D)

```
An error occurred when calling CreateWorkspaceFromIOUPayment ExpException - 6bc79773e08d73bba81f392baa33f372 ~~ message: '402 Missing field in memberData: email' exceptionMessage: 'Auth CreatePolicy returned an error'
```

### Solution

Update the membersData to accept the employee accountID instead of email.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a02aafb1f82feaf</li>
        <li>Upwork Job ID: 1735041279567687680</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by francoisl** [comment]
This is fixed.
