### ISSUE TITLE
[Wave 6: Workspace Chats] Clear the next steps everytime user takes some IOU action

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33019]
### Problem

Coming from [here](https://expensify.slack.com/archives/C02MW39LT9N/p1702394622575989?thread_ts=1702083902.380889&cid=C02MW39LT9N), given we do not have fully optimistic next steps, there can be moments they are showin out of date when user takes some iou action:

- submit
- approve
- pay

All of those will change the next steps and we need to wait for the updated version to come from the server to avoid showing stale information.

### Solution

To prevent showing incorrect information, lets always clear the appropriate next steps when user Submits, Approves or Pays an expense report. 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
Is this one we could have a contributor take?

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by mountiny** [comment]
This is merged and no c+ so we can close this issue!
