### ISSUE TITLE
[$500] Expensimark: Expose not-formatted href value in links HTML elements

### ISSUE THREAD

**Issue by robertKozik** [Expensify/App#33026]
Required by https://github.com/Expensify/App/issues/27977.

Problem
Currently, ExpensiMark automatically sanitises links and modifies values typed by user. However when typing we need to have access for unmodified value in order to prevent unwanted changes inside input.

Solution
Expose both unmodified value and the link variant (labeled or not) as separate attributes inside parsed links elements

Example:
```
Input: www.example.com
Desired output: <a href="https://www.example.com" data-raw-href="www.example.com" data-link-variant="auto" target="_blank" rel="noreferrer noopener">www.example.com</a>
```
```
Input: [www.example.com](www.example.com)
Desired output: <a href="https://www.example.com" data-raw-href="www.example.com" data-link-variant="labeled" target="_blank" rel="noreferrer noopener">www.example.com</a>
```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ec6580f23b26fdb</li>
        <li>Upwork Job ID: 1737161604818329600</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28115362</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
@robertKozik for this, would it be `internal` or `external`? Thanks!

**Comment by robertKozik** [comment]
@CortneyOfstad  I'll take care of it as an employee of external agency (software mansion)

**Comment by CortneyOfstad** [comment]
Sounds good @robertKozik!

**Comment by CortneyOfstad** [comment]
Any updates @robertKozik? Thanks!

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/expensify-common/pull/626) is in review

**Comment by robertKozik** [comment]
PR is approved by C+, waiting for merge

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/expensify-common/pull/626) was merged. Please assign me here

**Comment by CortneyOfstad** [comment]
Not overdue — @robertKozik, I just assigned @situchan based on the comment [here](https://github.com/Expensify/App/issues/33026#issuecomment-1887616049)

**Comment by situchan** [comment]
This is just awaiting payment

**Comment by CortneyOfstad** [comment]
## Payment Summary

- @situchan (reviewer) — paid $500 via Upwork
