### ISSUE TITLE
[$500] Assign task -After creating a task user is navigated back to the 1:1 conversation

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** @

## Action Performed:
Preconditions: User is logged in.

1. Open https://staging.new.expensify.com/
2. Navigate to a 1:1 conversation with a user
3. Click on the + in the compose box
4. Select "Assign task"
5. Enter a Title and a Description
6. Press Next
7. Assign the task to yourself
8. VShare the task (Share somewhere)
9. Click "Create the task"

## Expected Result:
The task is created and the user is navigated to the task "conversation"/Report

## Actual Result:
The task is created and the user is navigated to the 1:1 conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/99872d1b-ed28-4bd1-935b-95d0c495397c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01261dbcad1b761a40</li>
        <li>Upwork Job ID: 1735054584368058368</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After creating a task user is navigated back to the 1:1

### What is the root cause of that problem?
Here we navigate the user to the parent report not the created one 
https://github.com/Expensify/App/blob/63a53805e65c17767c4328eab817415147a56cfa/src/libs/actions/Task.js#L224
### What changes do you think we should make in order to solve the problem?



change it to: 

    Navigation.dismissModal(taskReportID );

**Comment by thienlnam** [comment]
I actually think this is the preferred outcome - we just end up in the same chat where we created the task (@kadiealexander if you agree, can we get the testrail updated for this?)

**Comment by kadiealexander** [comment]
Ooh, I agree! Yes, I'll raise a GH to get testrail updated.

**Comment by kadiealexander** [comment]
https://github.com/Expensify/Expensify/issues/349515
