### ISSUE TITLE
[$500] Chat-Email id is not shown as link and directed to profile page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap fab
3. Tap start chat
4. Enter a new contact eg: [y@c.com](mailto:y@c.com)
5. Select the contact
6. Tap on the email id displayed in start of page
7. Note it directs to profile page
8. Navigate back to LHN
9. Tap profile icon --- preferences
10. Toggle on forced offline
11. Repeat step 2-- step6

## Expected Result:
Email id must be shown as link and directed to profile page.

## Actual Result:
Tapping on email id, displays it as text and not link. Email id is not shown as link and directed to profile page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/91bef6fd-2325-460f-8f20-d3a7e66aff9e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c805ba2ca605e54</li>
        <li>Upwork Job ID: 1735232276090773504</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by situchan** [comment]
@paultsimura's [proposal](https://github.com/Expensify/App/issues/33044#issuecomment-1855514580) looks good to me.
It makes sense to go details page when accountID is optimistic or doesn't exist.
Also aligned with user mention logic [here](https://github.com/Expensify/App/blob/5c0f3e49129ed3a839523aeab1464e898a02535d/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L51).

🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
@bernhardoj I don't think we should apply your solution.
We should not show user optimistic accountID which will become invalid (kind of another user) when online

https://github.com/Expensify/App/assets/108292595/693ba1e3-a925-436e-b53d-1a018c048f91

**Comment by situchan** [comment]
Also please check this comment in the PR you linked:

> However, we aren't removing the DetailsPage yet since it is still needed for mentions.

**Comment by dangrous** [comment]
Yeah I think I'd also prefer not to add links to the details page if it's being removed soon - thank you for the context! @situchan can you take another look at the new proposals? I don't really love having a forever loading state (assuming a user is not returning online anytime soon) but if that matches what happens already with profile pages that might be okay.

**Comment by situchan** [comment]
I think we can just close. No one proposed right solution

**Comment by situchan** [comment]
I am not sure it's worth but not against it.
@dangrous what do you think?

**Comment by dangrous** [comment]
@johncschuster what do you think? I think the loader is the best option here (vs. doing nothing, or redirecting), but would love to hear your thoughts!

**Comment by dangrous** [comment]
@johncschuster is out for the holidays, I think we can close this for now as low priority and if we decide to bring it back at some point we can look at these proposals!
