### ISSUE TITLE
[$500] LHN - Chat in LHN bolds and unbolds briefly after requesting money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Click + > Request money.
4. Create a manual request.
5. Repeat Step 3-4.

## Expected Result:
The workspace chat in LHN will not bold and unbold.

## Actual Result:
The workspace chat in LHN bolds and unbolds briefly after creating each request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a97bb477-a0eb-4238-a44f-41547d1770a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012952ee87595dcbbe</li>
        <li>Upwork Job ID: 1735237903368962048</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
Hmmmm this is normal behaviour, no? IOU actions will result in the BE returning a new `lastVisibleActionCreated` stamp which after detecting that we call `readNewestAction`, so it's expected there would be some delay.

**Comment by MitchExpensify** [comment]
What are our next steps here @aimane-chnaif ?

**Comment by MitchExpensify** [comment]
I'm not sure this fits into any wave, closing
