### ISSUE TITLE
[$500] IOU - If SmartScan is successful, the "Uncategorized" category is created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33057]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Preconditions:
As a policy administrator in OldDot, add an employee and disable all categories.

Steps:
1. Open New Expensify app
2. Log in as an employee
3. Tap on the green plus button (FAB)
4. Select Request money - Scan
5. Add a receipt that will pass scanning without errors
6. Select a WS room
7. Complete the request
8. When the scan is complete, navigate to the IOU details

## Expected Result:
A successful SmartScan should not create an "Uncategorized" category.

## Actual Result:
If the SmartScan is successful, an "Uncategorized" category is created, even if all categories in OldDot are disabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/60285eaa-3af2-412d-9c08-70f4a7eb1723

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce9996c5f21ef67e</li>
        <li>Upwork Job ID: 1735268635424256000</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
@izarutskaya can you point me to the test case for this one? I'm trying to figure out what the expected behavior is.

**Comment by garrettmknight** [comment]
@izarutskaya Bump on which test case this came from, thanks!

**Comment by garrettmknight** [comment]
@izarutskaya Bump on which test case this came from, thanks!

**Comment by garrettmknight** [comment]
@izarutskaya Can you let me know which test created this? I think it's expected so I'm going to close, but feel free to reopen if you think differently.
