### ISSUE TITLE
[$500] Chat - Two messages are displayed after deleting a task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a task in any 1:1 conversation
3. Delete the task

## Expected Result:
Only one message should appear.

## Actual Result:
Two messages are displayed after deleting a task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ff49cc45-16d9-41fb-9139-12baa1efd1b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5f9145d1324e773</li>
        <li>Upwork Job ID: 1735270481758244864</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?

When canceling a task, in `Task.cancelTask` we should check if the task thread has any actions besides `CREATED`. If not – do not create a `TASKCANCELLED` report action.

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
That is intended - the second one is the system message on the task itself but the first one is the reportAction that you would see in the parent report. @sonialiap Could you please create an issue to get the testrail updated?

**Comment by quinthar** [comment]
I'm not sure I understand the steps.  (Also, why does the overflow message say "Cancel", but the system message says "Deleted")  Even watching the video, I'm still not sure.  Is the issue that when you cancel a task *while on the task report* we show it as "deleted", even though you're still looking at it?

**Comment by sonialiap** [comment]
@thienlnam bumping Tienifr's question ☝️

**Comment by thienlnam** [comment]
> @thienlnam what do you think about this? We're doing the same when deleting a money request.

I agree that's how it should work, it already deletes the parent report action so maybe the only thing that we need to update is navigating back and removing it from onyx if there are no additional comments

**Comment by thienlnam** [comment]
That's a separate issue though and a small change so I'm going to handle that in https://github.com/Expensify/App/pull/29730 which also addresses renaming 'Cancel' to 'Delete'

**Comment by thienlnam** [comment]
Yo, I don't think this would be eligible for any compensation since we are aligning functionality with another flow and the PR that implemented did not use the same solution.

**Comment by thienlnam** [comment]
Hey 👋 Each issue is taken in a case by case basis - that was different as it was to fix a deploy blocker whereas this was not necessarily a bug that we were aiming to fix. I added it to my list of changes which set out to consolidate some task flows, but it wasn't something that we were going to fix at this time anyways. 

I know you're very capable and can find other momentary compensation for other issues you fix, but I retain that this issue doesn't really constitute payment out to anyone. The bug pipeline is still full of issues that we're looking to have fixed. Thanks!
