### ISSUE TITLE
[HOLD for payment 2023-12-29] Update HelpDot Icons

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#33069]
Below you can find the the appropriate details you'll need for creating and submitting this PR

**Details**: Within the [Expensify Classic home page](https://help.expensify.com/expensify-classic/hubs/) linked we need replace two of the icons:

Icon 1: Billing & Subscriptions
Icon to replace with:

- Web-static file: https://github.com/Expensify/Web-Static/blob/main/images/illustrations/simple-illustration__subscription-annual.svg
- SVG: [simple-illustration__subscription-annual.svg.zip](https://github.com/Expensify/Expensify/files/13551038/simple-illustration__subscription-annual.svg.zip)

Icon 2: Send Payments
Icon to replace with: 
- Web-static file: https://github.com/Expensify/Web-Static/blob/main/images/illustrations/simple-illustration__sendmoney.svg
- SVG: [simple-illustration__sendmoney.svg.zip](https://github.com/Expensify/Expensify/files/13551047/simple-illustration__sendmoney.svg.zip)

**Comment by dannymcclain** [comment]
If it's helpful, I posted a quick mockup of these icons in context [here](https://github.com/Expensify/Expensify/issues/342992#issuecomment-1839436843).

![image](https://github.com/Expensify/App/assets/7516624/6f7eade3-0fb6-40e9-88ea-1caf3de604f4)

**Comment by rushatgabhane** [comment]
PR raised ^

**Comment by Beamanator** [comment]
Huh, PR was merged 2 weeks ago - Seems we need a BugZero person to help pay this out

**Comment by Beamanator** [comment]
asked in slack!

**Comment by rushatgabhane** [comment]
hi, no separate pay here. this is under help dot migration

we can close this issue

**Comment by Beamanator** [comment]
Ohh ok thank you kind sir!
