### ISSUE TITLE
[$500] Connect BA - No limit for entering amount in transition field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS or create it -> Bank account -> Connect manually
4. Use the "Pending State Withdrawal Account" credentials
5. When you finish the flow - the modal asks for 3 amounts of test transactions

## Expected Result:
Limit for entering an amount in the transition field presents

## Actual Result:
No limit for entering amount in transition field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a7618594-5188-4064-ab24-da01f4e1fc75

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01693243fe87e17333</li>
        <li>Upwork Job ID: 1735305219980148736</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Sorry, opened by mistake.

**Comment by cocoa-1012** [comment]
https://www.upwork.com/jobs/500-Connect-limit-for-entering-amount-transition-field-33066-Expensify_~01693243fe87e17333/?referrer_url_path=find_work_home
This job is canceled?
