### ISSUE TITLE
[HOLD for payment 2023-12-28] [Theme Switching] 🎨🐛 Draft Card Preview Hover Color Is Incorrect in Both Themes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#33078]
https://expensify.slack.com/archives/C049HHMV9SM/p1702569789849209

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by grgia** [comment]
@JmillsExpensify could you help me out with ensuring that @fedirjh receives the $500 C+ review payment for review of https://github.com/Expensify/App/pull/33097

**Comment by grgia** [comment]
awaiting payment verification

**Comment by grgia** [comment]
@JmillsExpensify could you verify payments / close this one out 🙏

**Comment by JmillsExpensify** [comment]
Whoops, sorry for the delay. Payment summary: $500 @fedirjh for PR review and testing.

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by JmillsExpensify** [comment]
Contract paid out! Thanks @fedirjh.
