### ISSUE TITLE
[$500] Split - Header in participant selection page still shows "Manual" after adding member to split

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click FAB > Request money > Manual.
3. Enter amount > Next.
4. Click Split on some users.

## Expected Result:
The header will show "Split" after adding members to split.

## Actual Result:
The header still shows "Manual" after adding members to split.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1cfdd3bc-f660-45a5-94c4-738abc580f91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01731ed1b64212aa1a</li>
        <li>Upwork Job ID: 1735321372817346560</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28065643</li>
</ul></li>
    </ul>
</details>

**Comment by ArekChr** [comment]
Hey @stephanieelliott, I've left the c+team and joined Waves. Could you assign a new C+ here to handle this issue?

**Comment by situchan** [comment]
I can take over

**Comment by stephanieelliott** [comment]
Thanks @situchan! Assigning

**Comment by stephanieelliott** [comment]
Oh, actually retesting this myself I think it is expected behavior -- `Manual` refers to the type of request it is, so `Split` should never show in the header. Just like a `Scan` type request continues to show `Scan`, even if you split it. Closing this as I don't think we should change it
