### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Wallet - "Enable Wallet" card flashes briefly when returning from card details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Log in as [tester@applausecard.expensifail.com.](mailto:tester@applausecard.expensifail.com.)
3. Go to Settings > Wallet.
4. Scroll down so that "Enable Wallet" section is hidden.
5. Click on any card under "Assigned cards".
6. Click back button.

## Expected Result:
No visual issue will occur when returning from card details page.

## Actual Result:
"Enable Wallet" card flashes briefly when returning from card details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/22aafaef-2b4a-4345-b542-aedd6597caee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f34b0983fb03250</li>
        <li>Upwork Job ID: 1735322288680189952</li>
        <li>Last Price Increase: 2023-12-28</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28078552</li>
<li>tienifr | Contributor | 28078553</li>
</ul></li>
    </ul>
</details>

**Comment by sfurqan2** [comment]
I think this issue is same as https://github.com/Expensify/App/issues/33068.

**Comment by mumincelal** [comment]
Hi,

I look at this issue and try to add debit card but debit card number is not accepted. It says always **Make sure you've entered a valid debit card.**. I tried PayPal, Stripe, Adyen, and other debit card number that I can find.

Is there any test debit card numbers? How can I pass this problem?

**Comment by mumincelal** [comment]
Contributor details
Your Expensify account email: mumincelalpinar@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f0f28edf2a156eab

**Comment by mumincelal** [comment]
So how can I solve my problem mention in [here](https://github.com/Expensify/App/issues/33075#issuecomment-1856512570)

**Comment by jjcoffee** [comment]
@mumincelal These are the instructions I usually use:

- **Add Bank Account** (Make sure to enable Settings > Preferences > Use Secure staging server to use the sandbox):
	- Click “Log into your bank”
	- _Plaid modal_ - Choose **Wells Fargo**
	- _Plaid modal_ - User Id: `user_good`
	- _Plaid modal_ - Password: `pass_good`
	- _Plaid modal_ - Submit
	- _Plaid modal -_ If they request a verification code via mobile sms, enter: `credential_good`
	- Choose an account: Plaid Saving11122XXXXXX111
	- Save & Continue

**Comment by mumincelal** [comment]
Thank you.

**Comment by mumincelal** [comment]
One more question. How can I add assigned card? I created a workspace, selected created workspace > Cards. Followed instructions but nothing happened. Is there any way to add assigned card easily?

**Comment by jjcoffee** [comment]
Not overdue, awaiting proposals.

**Comment by mumincelal** [comment]
@jjcoffee  I will take it but there is one obstacle. I mentioned here:

https://github.com/Expensify/App/issues/33075#issuecomment-1857808265

How can I solve it?

**Comment by jjcoffee** [comment]
@mumincelal I recommend taking advantage of the wider open source community by reaching out on Slack for help on questions like that.

**Comment by mumincelal** [comment]
I have already asked but no one answered. Because of that I am using this channel

**Comment by greg-schroeder** [comment]
New proposal to review above

**Comment by greg-schroeder** [comment]
Awaiting proposal review @jjcoffee

**Comment by jjcoffee** [comment]
Reviewing today!

**Comment by jjcoffee** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/33075#issuecomment-1864227016) LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by greg-schroeder** [comment]
@jjcoffee @tienifr paid. All that's left is the checklist @jjcoffee!

**Comment by greg-schroeder** [comment]
filed
