### ISSUE TITLE
Status - The status tab doesn't change the theme in Light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Preferences -> Theme -> Light
4. Then go to Settings -> Profile -> Status
5. Notice that tab doesn't change the theme in Light mode

## Expected Result:
The status tab change the theme in Light mode

## Actual Result:
The status tab doesn't change the theme in Light mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 
![Bug6313338_1702573564797!image__196_](https://github.com/Expensify/App/assets/78819774/15e13173-e5b9-4e6f-96d9-6ca58d284542)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Asked [here](https://github.com/Expensify/App/issues/33087)

**Comment by grgia** [comment]
Closing as dupe. PR is already up
