### ISSUE TITLE
Desktop - Distorted LHN when using the back button in an IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing Pr** https://github.com/Expensify/App/pull/32592
## Action Performed:
1. Open the app
2. Navigate to any 1:1 conversation
3. Create a Money Request manually
4. Go offline by either turning off your internet connection or navigating to Settings > Preferences > Force offline
5. Navigate to the IOU details page and click on the created money request
6. Resize the screen so that the details page covers full screen
7. Tap on the back button in the header and observe the functionality of the back button

## Expected Result:
LHN should properly fit the screen when using back button in an IOU details page

## Actual Result:
LHN gets distorted when using the back button in an IOU details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/051dda31-b726-48d4-81e0-fa7abc4c3f86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Asked about this [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1702608269645339).

**Comment by kadiealexander** [comment]
Bumped the thread!

**Comment by kadiealexander** [comment]
Agreed [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1702948664790919) to close this.
