### ISSUE TITLE
[$500] Mobile apps render an empty screen once logged in

### ISSUE THREAD

**Issue by lindboe** [Expensify/App#33096]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** latest on main
**Reproducible in staging?:** unknown
**Reproducible in production?:** unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @lindboe 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1702512728991509

## Action Performed:

1. Open the app on iOS or Android and sign in if necessary

## Expected Result:

The list of chats should be rendered on the screen under the "Expensify" header

## Actual Result:

No content is rendered on the screen under the header.

<img width="396" alt="Screenshot 2023-12-14 at 9 41 43 AM" src="https://github.com/Expensify/App/assets/5252268/6178a4ab-1495-4e9b-b5bb-c9d14bcc0965">

## Workaround:

Not as far as I'm aware.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/5252268/58cfa282-0691-474c-adbc-88875a6fd3bf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e5b09fb52c1523a</li>
        <li>Upwork Job ID: 1735672510488264704</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Wasn't able to recreate, but going to see if someone else can 👍

**Comment by CortneyOfstad** [comment]
@mollfpr when you have a chance, can you try recreating this issue?

**Comment by neonbhai** [comment]
cannot reproduce!

**Comment by mollfpr** [comment]
I can't reproduce it on `v1.4.13-6 Develop`.

**Comment by lindboe** [comment]
It looks like it was a bug specific to accounts that were part of a specific workspace, where there was a reference to a receipt file that couldn't be found. @cead22 was able to fix it by removing the bad data. Not sure if this ticket is worth keeping to prevent such an issue from breaking the entire app in the future?

**Comment by cead22** [comment]
Yeah I think we can close
