### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [Theme Switching] 🎨🐛 Status Page Color Is Incorrect in Both Themes

### ISSUE THREAD

**Issue by grgia** [Expensify/App#33091]
https://expensify.slack.com/archives/C03TME82F/p1702572893347079?thread_ts=1702568492.702179&cid=C03TME82F

![Image](https://github.com/Expensify/App/assets/38015950/ac00d049-3e14-4ac6-8cc8-eea3bcdd7034)

Should be AppBG

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a92f5e573321b5c2</li>
        <li>Upwork Job ID: 1735359468152483840</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by situchan** [comment]
Same issue created here - #33087

**Comment by getusha** [comment]
I don't think this needs regression test steps, it doesn't seem a bug that'll occur on this specific page in the future.
what do you think @grgia?

**Comment by grgia** [comment]
@getusha I agree on regression steps. @zanyrenney I think this one can be closed once paid for!

**Comment by getusha** [comment]
@zanyrenney applied

**Comment by zanyrenney** [comment]
offer sent @getusha

**Comment by zanyrenney** [comment]
from the comment:

> For reference, here are some details about the assignees on this issue:
> 
> @getusha requires payment (Needs manual offer from BZ)

Payment sent. 

Payment summary $500. Thanks, closing!
