### ISSUE TITLE
Status - Error when saving the custom time at 00:00 am

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile
3. Go to Status
4. Click Clear after > Custom > Time
5. Select a date later than today
6. Set the time to 00:00 am and save it

## Expected Result:
User is able to save the custom time when the time is 00:00 am

## Actual Result:
User is unable to save the custom time when the time is 00:00 am
Error shows up - Please choose a time at least one minute ahead
Although it says 'choose a time at least one minute ahead', user is still unable to set the time at 00:01, 00:02 etc

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/94afa469-223a-4792-8a17-494b452771ce

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
See https://expensify.slack.com/archives/C01GTK53T8Q/p1702577037928319
Not a blocker, 0 is not a valid hour, it should be 12. We will change the error message to be better.
