### ISSUE TITLE
[Theme Switching] 🐛 🎨 Light theme - "Splash Page" animation is in dark theme

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Put the Site to "Light mode" in preferences
4. Refresh the page

## Expected Result:
User expects the Splash page to be in light theme

## Actual Result:
The Splash page is in dark theme

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/96de4ff5-bd22-455e-8014-1ea7240318d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
We need to fix it, but not a deploy blocker.

**Comment by grgia** [comment]
slack convo here - https://expensify.slack.com/archives/C03TME82F/p1702590977311999?thread_ts=1702568492.702179&cid=C03TME82F

**Comment by grgia** [comment]
We most likely will not need to fix this right now

**Comment by rlinoz** [comment]
Should we close it?

**Comment by grgia** [comment]
Closing!
