### ISSUE TITLE
[HOLD for payment 2023-12-28] [Theme Switching] 🐛 Light theme - Transition icon in Add bank account flow is showing as Dark theme

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Access Light theme
4. Follow the Bank account flow and note the "Loading" transition pages

## Expected Result:
User expects the icons to have a white background when in light theme

## Actual Result:
The icons are showing with a dark green background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6313405_1702576636094!Icon_is_showin_with_a_dark_background_" src="https://github.com/Expensify/App/assets/78819774/e3d1fc52-e580-42d6-ae92-91dd96f2c654">

https://github.com/Expensify/App/assets/78819774/74cee9f0-b1d6-4b55-9e4f-e53cbae32563

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
I wonder if the lottie animation had a colored background here

**Comment by grgia** [comment]
@shawnborton could we get a transparent BG version of the ReviewingBankInfo animation?

**Comment by grgia** [comment]
@shawnborton looks like we're going to need a bunch of the lottie animations with transparent BGs

**Comment by grgia** [comment]
- bank 
- 2FA fireworks

**Comment by shawnborton** [comment]
Started a thread for updated assets [here](https://expensify.slack.com/archives/C03KN50J0PM/p1702594768429739).

**Comment by shawnborton** [comment]
Left a comment on the PR about sizing!

**Comment by peterdbarkerUK** [comment]
No payment required, 500 Melvin coins to @grgia of course. 

Rushat reviewed it, under review [here](https://github.com/Expensify/App/pull/33189#issuecomment-1871535471)

**Comment by peterdbarkerUK** [comment]
[Rushat has been paid](https://github.com/Expensify/App/pull/33189#issuecomment-1874173603)
