### ISSUE TITLE
[$500] [HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [Theme Switching] 🐛 - App is still in dark mode when device dark mode is off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Device dark mode is on
- App dark mode settings is set to "Use device settings"
1. Launch New Expensify app
2. Turn off dark mode

## Expected Result:
App will switch to light mode

## Actual Result:
The app is still in dark mode, even after relaunching the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a5a95b6f-9e74-4b6d-b04a-fa4f9796cbc9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01325de77e255acbec</li>
        <li>Upwork Job ID: 1743285192238567424</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by artus9033** [comment]
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by aldo-expensify** [comment]
cc @grgia since you are the Theme expert I believe

**Comment by aldo-expensify** [comment]
This worked fine for me in Macos / Web. I'll try to test in Android

**Comment by aldo-expensify** [comment]
Reproduced in Android

**Comment by grgia** [comment]
Yes I believe we are hard coding this, I'm looking into it right now

**Comment by aldo-expensify** [comment]
> Yes I believe we are hard coding this, I'm looking into it right now

Thanks, meanwhile I'm trying to install the latest version in the emulator to start debugging

**Comment by grgia** [comment]
https://github.com/Expensify/App/issues/33090 here's some more context, but the PR up is not the full picture it still defaults to one theme currently

**Comment by grgia** [comment]
https://github.com/Expensify/App/pull/13874/files#diff-bc1549da6355f7f82f324af9c667b78ff60672b6b80219062629fe4184e8fa93R69-R70 

Gonna test reverting these

**Comment by grgia** [comment]
> It is important to note that remote debugging should be turned off, as when on it will always return "light". To turn on or off remote debugging type "m" on CLI to open the menu on your device and then turn on/off remote debugging.

**Comment by aldo-expensify** [comment]
Still trying to test in emulators, android is getting stuck forever with `info Starting JS server...` and IOS is just giving the errors

```
error Error: Command failed with exit code 1: xcodebuild -list -json
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance.
Error: Error: Command failed with exit code 1: xcodebuild -list -json
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
    at getProjectInfo (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli-platform-ios/build/tools/getProjectInfo.js:29:11)
    at Object.runIOS [as func] (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:88:58)
    at Command.handleAction (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/build/index.js:111:23)
    at Command.listener [as _actionHandler] (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:482:17)
    at /Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:27)
    at /Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)
    at Command._dispatchSubcommand (/Users/aldocanepa/Expensidev/App/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1077:23)
```

**Comment by aldo-expensify** [comment]
Oops, seems like I put xcode in the trash a month ago without realizing 🤦

**Comment by aldo-expensify** [comment]
Assigning @grgia since you fixed it! great work there :)

**Comment by grgia** [comment]
@michaelhaxhiu I think this one is just waiting on C+ review payment

**Comment by michaelhaxhiu** [comment]
Looking!

**Comment by michaelhaxhiu** [comment]
Offer sent - waiting to pay!
