### ISSUE TITLE
[HOLD for payment 2023-12-29] HelpDot Improvements - Make FAQ section of collapsiable

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#33109]
Deliverables:

Make the FAQ section within each article page collapsiable to minimize unnessary text for the reader.
For example, [this page](https://help.expensify.com/articles/expensify-classic/account-settings/Account-Details) has FAQ and they may not be applicable to every reader.

To Do's:

- [ ] Use Markdown to organzie the structure of the FAQ content - Caitlin
- [ ] find a way to implement the opening/closing of FAQ - sounds like this would be in CSS

@rushatgabhane I can handle the organzation using Markdown, but if you could help with the open/close functionality of the FAQ pages, that would be great!

**Comment by rushatgabhane** [comment]
PR raised ^

**Comment by caitlinwhite1** [comment]
@rushatgabhane closing this one since the PR merged. Let me know if I'm missing anything here.
