### ISSUE TITLE
[$500]  When doing Start chat, and someone is added to a group, clicking on a person should add them to the group, not discard the group

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702580397915479

## Action Performed:

1. Alice clicks Start chat
2. Alice clicks Add to group next to Bob
3. Alice then clicks Cathy's name direct

## Expected Result:
 It opens a DM with Cathy (ignoring the group with Bob)

## Actual Result:
Should open a group with Bob and Cathy

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/24bc0b8f-93dc-40fb-b68b-3d156fd47c52

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b26e760299069d66</li>
        <li>Upwork Job ID: 1735411019486609408</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When doing Start chat, and someone is added to a group, clicking on a person should add them to the group, not discard the group

### What is the root cause of that problem?
This happens as in `NewChatPage` on selecting a row always opens a DM. 
https://github.com/Expensify/App/blob/83a89fbabc0a550993e5e4d6b9f8904aee9ff1ca/src/pages/NewChatPage.js#L248
There is no logic to check if user has started adding participants to groups.

### What changes do you think we should make in order to solve the problem?
We should add logic to add to group if there are participants selected already.


```js
onSelectRow={(option) => {
	selectedOptions.length >= 1 ? toggleOption(option) : createChat(option)
}
```

**Comment by neonbhai** [comment]
## Proposal 
### [Updated](https://github.com/Expensify/App/issues/33119#issuecomment-1856662447)
Added result video demonstrating the solution.

**Comment by burczu** [comment]
I tend to agree with @bernhardoj's [comment](https://github.com/Expensify/App/issues/33119#issuecomment-1857296423) that this may not be a bug - group is created once we click on `Create group` button and clicking on the email just opens a chat with this person. Also, as @bernhardoj pointed out - it works the same with requesting money: when we select with few people to split bill, and then click on one of the selected emails, it choose only this person and moves to the next step.

What do you think @adelekennedy?

**Comment by adelekennedy** [comment]
let's close - this may be something we decide to change in the future but we can leave that to the split group to decide
