### ISSUE TITLE
[$500] Codeblocks does not wrap

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702572793589809

## Action Performed:
1. Open any chat
2. Send a lengthy codeblock message

## Expected Result:
Should wrap themessage

## Actual Result:
Message does not wrap

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (13)](https://github.com/Expensify/App/assets/38435837/a5e9609b-0ffb-4fd8-bcc2-790fb36f5a2d)

![image (12)](https://github.com/Expensify/App/assets/38435837/05380a98-b3d8-4a96-acb1-27ad0b184ce4)

![Snip - (4) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/c4a555f2-22d2-4ba0-b363-f738af1ddf9b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128f71c5292f13b05</li>
        <li>Upwork Job ID: 1735401155881005056</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28067470</li>
<li>Krishna2323 | Contributor | 28067471</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
What do you mean by `wrap the message`? the attached example's message is already in a code block

**Comment by sakluger** [comment]
@abzokhattab In the example provided, you can see that when the user enters a long text string in code blocks, they must scroll right and left to see the full message. In the screenshot from Slack, the text in the code block wraps and the user doesn't need to scroll right and left.

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Codeblocks does not wrap
### What is the root cause of that problem?
This is issue `RenderHTMLSource` of `react-native-render-html`
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/RenderHTML.tsx#L17

`pre` tag is covered by `flex-direction: row`. so content has x-scroll.
I am not sure this is correct. because some app(ChatGPT) use x-scroll for codeblock.
### What changes do you think we should make in order to solve the problem?
But we can fix this easily using custom css.
`flex-direction: inherit`
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/27a859cf-a9ef-491f-81a8-b8df6fcb68f6

**Comment by cubuspl42** [comment]
For future reference, this seems unrelated to https://github.com/Expensify/App/issues/27913

**Comment by cubuspl42** [comment]
This seems like an intended behavior. [I asked on Slack](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q).

**Comment by yh-0218** [comment]
hi, @cubuspl42 what is opinion about [proposal](https://github.com/Expensify/App/issues/33115#issuecomment-1857333944)

**Comment by cubuspl42** [comment]
> This seems like an intended behavior. [I asked on Slack](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q).

It seems that we decided that this is a new expected behavior to wrap the long lines in the non-inline code blocks.

**Comment by cubuspl42** [comment]
@Krishna2323 Would you add some more context to your proposal? Maybe pointers to specific places in the codebase where you suggest to remove the mentioned properties?

**Comment by sakluger** [comment]
I do think this behavior is fine, it's how GH handles long code blocks. I'm going to close since it's not clear that wrapping is expected.

**Comment by cubuspl42** [comment]
I [asked on the mentioned thread](https://expensify.slack.com/archives/C049HHMV9SM/p1702980360564849?thread_ts=1702572793.589809&cid=C049HHMV9SM) whether we want to discuss the expected behavior

**Comment by quinthar** [comment]
That's interesting that GitHub works one way and slack works a different way.

**Comment by quinthar** [comment]
There seems to be strong support for adding wrapping. Is this easy to add?

**Comment by quinthar** [comment]
https://expensify.enterprise.slack.com/archives/C049HHMV9SM/p1702998520244309?thread_ts=1702572793.589809&cid=C049HHMV9SM

**Comment by yh-0218** [comment]
yes it is easy

**Comment by sakluger** [comment]
Looks like we've settled on wrapping. Let's do it! @cubuspl42 does @Krishna2323's proposal look good to you or should we wait for more?

**Comment by cubuspl42** [comment]
@Krishna2323 

> we would also need to cleanup some code related to scrolling if we decide to remove the horizontal prop.

How does the app behave after just removing the `horizontal` prop? In other words, is the mentioned cleanup necessary to fix the issues that arise when `horizontal` is removed, or is it just a clean-up of no longer necessary logic?

**Comment by cubuspl42** [comment]
The proposal by @Krishna2323 sounds good; we can work out any necessary details during the PR review 👍

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
@Krishna2323 Ping me once you create the PR

**Comment by cubuspl42** [comment]
[Asked on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1706085558929869)

**Comment by sakluger** [comment]
Thanks for the bump, all paid out!
