### ISSUE TITLE
Cannot complete payment request in Expensify

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#33113]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** No
**Email or phone of affected tester (no customers):** mlewis@expensify.com
**Issue reported by:** Margaret Madelyn Lewis
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1702400726797869

## Action Performed:
1. Puneet sends payment request 
2. Open chat with Puneet
3. Click `Pay with Expensify`
4. Right-hand nav menu opens with options to pay with Wallet, Expensify Card, bank account
5. Clicked Chase Checking
6. That gives me the option to delete the bank account and that's all (not use it to send a payment)
7. My wallet cannot be enabled at this time 

## Expected Result:
Describe what you think should've happened - i should be able to pay the payment request using my bank account or my wallet

## Actual Result:
Describe what actually happened - i could not complete the payment in Expensify 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38016013/b8406dcd-943e-4ffa-85d2-f536a0d54266

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e10d05edd3cf9881</li>
        <li>Upwork Job ID: 1736965034688700416</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by mallenexpensify** [comment]
Def seems like a [#vip-split-p2p-chat-groups](https://expensify.slack.com/archives/C05RECHFBEW) issue, asking there
https://expensify.slack.com/archives/C05RECHFBEW/p1702959659719479

I imagine most of the work is backend related, would you aggree @Ollyws ?

**Comment by mallenexpensify** [comment]
@neil-marcellini added `Engineering` because this is part of with #vip-split-p2p-chat-groups and it seems like a significant bug we want to fix.  cc @joelbettner and @rafecolton , if either of you want to work on it, since you're working on P2P.

**Comment by youssef-lr** [comment]
@maddylewis from the code I think the only way this could happen is if the bank account you added does not have the state OPEN, when you're back from OOO can you please ping me so we can debug this together?

**Comment by maddylewis** [comment]
sure, i will try to get to this before eod

**Comment by youssef-lr** [comment]
@maddylewis just needs to upgrade her wallet to Gold. I think we can close this!

**Comment by GabiHExpensify** [comment]
@youssef-lr mind clarifying why you re-opened this? is there anything else to do here, or is it all done?

**Comment by youssef-lr** [comment]
It seems like @maddylewis should have their wallet upgraded automatically but something prevented it, I will check the backend logs today to find out if there are any KYC errors.

**Comment by maddylewis** [comment]
kk, let me know if i need to action something on my end :)

**Comment by maddylewis** [comment]
kk, let me know if i need to action something on my end :)

**Comment by GabiHExpensify** [comment]
friendly bump @youssef-lr, any update here?

**Comment by youssef-lr** [comment]
I tried searching for some logs, but I don't see anything related to when Maddy tried to activate the wallet, I think this should run from a webhook called by Onfido, so it might have happened a while ago and logs are deleted. @coleaeason is there any way to trigger `ActivateWallet` again?

<img width="1798" alt="Screenshot 2024-01-13 at 03 35 09" src="https://github.com/Expensify/App/assets/9680864/78bac329-5702-44c7-a062-9fd03449b977">

**Comment by maddylewis** [comment]
assigning cole for vis

**Comment by coleaeason** [comment]
I'm reasonably sure if you go to https://new.expensify.com/enable-payments it should route you through the KYC flow again and trigger `ActivateWallet`

**Comment by youssef-lr** [comment]
@maddylewis can you try navigating to the link above please? ping me whenever you get to it and I'll check the logs. Thanks!

**Comment by MariaHCD** [comment]
I think we'll need to reset the Onfido verification similar to what we did [here](https://github.com/Expensify/Expensify/issues/330797#issuecomment-1803834936). The status for Onfido for Maddy's wallet is `consider` (perhaps because the name scanned from the uploaded document didn't match what was entered?)

```
maria@db2.rno:~$ getemail.sh 5801774
mlewis@expensify.com
maria@db2.rno:~$ sudo readdb.sh -line "select json_extract(additionalData, '$.verifications.externalApiResponses.requestorIdentityOnfido.status') from bankaccounts where type = 0 and accountid = 5801774"
json_extract(additionalData, '$.verifications.externalApiResponses.requestorIdentityOnfido.status') = consider
maria@db2.rno:~$ 
```

Onfido applicant link [here](https://dashboard.onfido.com/applicant/df333a61-1597-4218-a0a8-88cf945282d0/details):

<img width="1232" alt="Screenshot 2024-01-17 at 3 15 14 PM" src="https://github.com/Expensify/App/assets/12268372/bc5852e6-6bbe-4177-a4b0-408ad4a1a60d">

**Comment by MariaHCD** [comment]
This is the query we can use to reset the Onfido verification and set the current step back to the Onfido step. Buddy check please:

```sql
UPDATE bankAccounts SET additionalData = JSON_SET(JSON_REMOVE(additionalData, '$.verifications.externalApiResponses.requestorIdentityOnfido'), '$.currentStep', 'OnfidoStep') WHERE bankAccountID = 1242416;
```

**Comment by techievivek** [comment]
Looks good to me. 👍

**Comment by MariaHCD** [comment]
Done! @maddylewis, in NewDot, if you navigate to https://new.expensify.com/enable-payments (or Profile > Wallet > Enable wallet), you will be able to retry Onfido. Then if it still doesn't work, we can investigate further!

**Comment by maddylewis** [comment]
ok! i will give this a try now

**Comment by maddylewis** [comment]
it looks like i can add a debit card but i get a blank screen when clicking add a bank account: 

https://github.com/Expensify/App/assets/38016013/19df0fbf-f0d6-4f28-bb2d-1bad2118b07d

**Comment by maddylewis** [comment]
Okay, it looks like i am routed to Plaid on staging:
<img width="1076" alt="image" src="https://github.com/Expensify/App/assets/38016013/d633d932-2785-49b2-94cd-45ae39ef6542">

is that expected?

**Comment by MariaHCD** [comment]
Hmm, if you're on prod, you should be routed to Plaid on production 🤔

https://github.com/Expensify/App/assets/12268372/5f9e02d3-860a-4c94-b9e2-cdf275cba139

And then after adding a PBA via Plaid, you will be able to proceed with KYC.

**Comment by maddylewis** [comment]
should i go through the KYC flow on staging? or are we trying to confirm why im unable to get to the Plaid dialogue box on prod?

**Comment by youssef-lr** [comment]
_sorry don't mind me just calming Melvin_ 

not overdue

**Comment by MariaHCD** [comment]
@maddylewis mind sending a screen recording? It's definitely weird that you can't get the Plaid flow in prod.

**Comment by maddylewis** [comment]
ok let me try!

**Comment by maddylewis** [comment]
Okay, i was able to get to the Plaid flow in prod after the recent update. Now, when i try to connect my checking account, Chase is saying it's already connected: 
<img width="771" alt="image" src="https://github.com/Expensify/App/assets/38016013/7075dcb4-6797-4cb9-8908-c8c86a114582">
<img width="1334" alt="image" src="https://github.com/Expensify/App/assets/38016013/5ba299a8-6287-4e84-b954-afa32ae5be07">

i will do some local troubleshooting steps to see if i can get that sorted.

**Comment by mallenexpensify** [comment]
Maddy's working on

**Comment by youssef-lr** [comment]
Not overdue.

**Comment by mallenexpensify** [comment]
Maddy's working on

**Comment by maddylewis** [comment]
ok what happened through this is my deposit bank account was removed so my paycheck isn't able to process: 
<img width="617" alt="image" src="https://github.com/Expensify/App/assets/38016013/434f157a-929c-44d9-9d8e-861936cc3f07">

now when i try to add a bank account: 
<img width="829" alt="image" src="https://github.com/Expensify/App/assets/38016013/945fa380-9105-421f-b20e-8f474b5907b1">
<img width="1390" alt="image" src="https://github.com/Expensify/App/assets/38016013/5fb345bb-0267-4357-a90a-c769be87ccbe">

**Comment by maddylewis** [comment]
trying to add bank account via NewDot -- i click `add bank account` > `chase` > and im taken to a screen called First Platypus Bank??? 


https://github.com/Expensify/App/assets/38016013/bb38628d-ab13-4137-9f70-45006438d212

**Comment by mallenexpensify** [comment]
> First Platypus Bank??? 

That's our test account we use.   Did you ever use your real Expensify account to setup or test BA?  That could be the issue.  I have NO idea how to unlink them if so, I don't think clearing cache will help.  

Sorry I can help more here Maddy, ping me in NewDot if you need me to help or test anything

**Comment by maddylewis** [comment]
okay, here's what happened -- 
When i tried adding my Chase account to NewDot 3 weeks ago ([here](https://github.com/Expensify/App/issues/33113#issuecomment-1910430967)), I saw this message and thought that meant the platform thought my bank was already added: 
<img width="702" alt="image" src="https://github.com/Expensify/App/assets/38016013/761931ac-0b15-44d0-b49c-2ccb362276ad">

so instead of just clicking `Next` i deleted my bank account entirely to try and create a fresh connection. but kept running into that message so i thought something was wrong...but nothing was wrong and i just needed to click NEXT 🙄

**Comment by maddylewis** [comment]
since that "kind of confusing messaging" comes from Chase, we don't have a way to make it less confusing. so i think we're actually good to close this out 👍

**Comment by mallenexpensify** [comment]
Thanks for the deets Maddy, happy to know it's sorted
