### ISSUE TITLE
Concierge compose tool not using the custom subject logic when sending message in NewDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702573610539439

## Action Performed:
1. Open the concierge compose tool and observe

## Expected Result:
Customizes the "Subject" and sending the ND message immediately
It SHOULD do this by sending a NewDot message formatted like this:
```
# <custom subject>
<body>
```
## Actual Result:
Uses the logic
```
*<custom subject>*

<body>
```
So it's not actually triggering the custom subject logic at all.  It's just sending a normal message, with the first line in bold.  This would trigger the regular UnreadMessageSummary job a day later, with the subject line Expensify chat from <me> to <you>

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (14)](https://github.com/Expensify/App/assets/38435837/12a56915-dfbf-4cbe-8593-e6cf4b8f37ed)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Reproduced 
<img width="472" alt="image" src="https://github.com/Expensify/App/assets/36425901/9611bb45-72a7-4f97-800b-f96b06d7fe0d">

**Comment by chiragsalian** [comment]
Hey @cristipaval, sorry to snatch this from you. I was pinged about this on slack and had some free time today so i went ahead and tackled it. 

I've placed a PR for review.

**Comment by cristipaval** [comment]
Thanks @chiragsalian!

**Comment by MitchExpensify** [comment]
The PR is on production, this was reopened by mistake
