### ISSUE TITLE
[Theme Switching] 🐛 Android - After applying light theme and opening IOU or task device status bar barely seen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Set any theme and log out
3. Log in with the account that has chats with IOU or task
4. After logging in, apply the light theme in Preference
5. Navigate to a chat with IOU or task
6. Open the IOU report or task

## Expected Result:
The device status bar is still seen

## Actual Result:
The device status bar is barely seen, and it flickers when navigating to different screens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313621_1702587828606!photo_2023-12-14_16-01-06](https://github.com/Expensify/App/assets/78819774/f608c3fe-232f-4d54-bd92-6be8912ef863)

https://github.com/Expensify/App/assets/78819774/a290032f-083e-4aca-838f-3d2ff1640a53

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Appears to be a theme issue - cc @grgia Though I'm not sure what we can do here, seems intended

**Comment by grgia** [comment]
@chrispader

**Comment by grgia** [comment]
Oh actually I think we need to CP a PR

**Comment by grgia** [comment]
may be fixed by https://github.com/Expensify/App/pull/32672

**Comment by grgia** [comment]
Closing as fixed!
