### ISSUE TITLE
[$500] Chat – Green image appears in IOU as Admin when delete receipt as employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In the workspace chat create a Manual request (i.e with no receipt)
3. Once created > navigate to the request conversation
4. Click on the three dot menu in the header > Add receipt
5. Select/take a picture
6. As admin view this IOU with a receipt.
7. When the manual expense has a receipt as employee attached delete it
8. As admin view this IOU

## Expected Result:
Receipt is deleted from the request

## Actual Result:
Green image appears in IOU as Admin when delete receipt as employee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce42471e-021a-4681-9dc9-0f3007ad36a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9b3bfb36be58b04</li>
        <li>Upwork Job ID: 1735422521644609536</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by samilabud** [comment]
How can we test as an employee or as an admin?

**Comment by cheapestorderconcept** [comment]
Looking at this issues.  It looks like a default image has been used when uploaded images is null or other value.

I will carefully look into the codebase, look into the condition that is rendering this images, if a default is used upon deletion, I will remove this default image and display the normal Request card has appropriate only. 

This will be my technical approach to this issue

**Comment by cheapestorderconcept** [comment]
Contributor details
Your Expensify account email: bolexguy@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011458797003438c4f

**Comment by sonialiap** [comment]
@samilabud 
> How can we test as an employee or as an admin?

You can create two test accounts, one will be the employee account and the other will be the admin. Create your test workspace under the admin account and invite the employee to it.

**Comment by sonialiap** [comment]
Closing as low priority
