### ISSUE TITLE
Handle template formulas in the report title field

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#33131]
When loading report fields, on app init we load the report fields for the primary policy

However for report titles, which can have a formula which contain things from [here](https://help.expensify.com/articles/expensify-classic/insights-and-custom-reporting/Custom-Templates). There can be items that would only be known from the BE and so there is not a good way to handle this entirely optimistically on the FE.

Once the report is created, the changed report title should already be handled (as it pulls the report name from the BE on OpenReport) but the issue is in the draft report state.

In the draft report,
- If the report formula is required, we can just add text denoting that this is required and cannot be changed (we'll just grab it when we open the report)
- If the report formula is not required but does exist, we will pass the current formula value in OpenWorkspaceRequest and that will be used in the draft but can be modified to whatever the user expects

**Comment by thienlnam** [comment]
Still need to investigate

**Comment by thienlnam** [comment]
Convo here: https://expensify.slack.com/archives/C02MW39LT9N/p1704235992446369

**Comment by thienlnam** [comment]
No update: Going to pass this back with the OpenDraftWorspaceRequest call

**Comment by thienlnam** [comment]
Will work on this today

**Comment by thienlnam** [comment]
As I look into this, I am thinking of just passing back the formula title as the defaultValue on the reportField text_title. That should make it the most straightforward implementation. The only drawback is if we are offline, it will pull the last stored value which would be inaccurate (we could probably negate this with some offline UI handling)

What do you think?

**Comment by thienlnam** [comment]
Alternatively, I could store the value in another NVP policyDefaultTitle_<policyID>

**Comment by allroundexperts** [comment]
> As I look into this, I am thinking of just passing back the formula title as the defaultValue on the reportField text_title. That should make it the most straightforward implementation. The only drawback is if we are offline, it will pull the last stored value which would be inaccurate (we could probably negate this with some offline UI handling that we would need to add in the offline required case anyways)
> 
> What do you think?

I think adding it in `defaultValue` field should be fine. However, I'm curious about where would you be saving the formula entered by the user then?

My recommendation here would be to let the `defaultValue` of the `policyReportField` be the raw formula that user entered and the value that is attached to the report, let that be the result after applying the formula.

**Comment by thienlnam** [comment]
> However, I'm curious about where would you be saving the formula entered by the user then?

Are you thinking in the future scenario where we allow the user to update the formula via NewDot? I was thinking the formula is not actually necessary in the FE because we aren't adding the ability to decode all formula values optimistically.

> My recommendation here would be to let the defaultValue of the policyReportField be the raw formula that user entered and the value that is attached to the report, let that be the result after applying the formula.

I think this is ideal - and should happen automatically once openReport is called (should pull down the report title). The main issue is what happens with this draft report. OpenDraftWorkspace doesn't currently pass a reportID. Perhaps we can add the optimistic reportID to that and have the API send a pusher request to set the report title in onyx?

**Comment by thienlnam** [comment]
Hmm actually, it's not like you set the report title during the creation of an IOU. Maybe we can do nothing here - if we're offline and the report title is enforced, we will make the field non-editable. Otherwise, it will default to the formula but can be updated, then once the user comes back online it will automatically update to the report field unless it was modified

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/34877

**Comment by thienlnam** [comment]
We decided to do nothing here - https://github.com/Expensify/App/issues/33131#issuecomment-1903483529
