### ISSUE TITLE
[Theme Switching] 🐛 Android - Distance - Mapbox remains in dark mode when the app is in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App is in light mode
1. Launch New Expensify app
2. Tap FAB icon > Request money
3. Go to Distance
4. Tap on the mapbox info icon

## Expected Result:
The mapbox info pop-up is in light mode

## Actual Result:
The mapbox info pop-up remains in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313913_1702605188405!Mapbox](https://github.com/Expensify/App/assets/78819774/c49f3544-0044-4c0b-96cf-6a537befa9a8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
I don't think we need to block deploy on this, gonna remove the label

**Comment by jasperhuangg** [comment]
Looping in `Design`, are we expecting this modal to also be in a light theme? cc @dannymcclain

**Comment by jasperhuangg** [comment]
This seems like a similar design problem to https://github.com/Expensify/App/issues/33120#issuecomment-1857082112

cc @dubielzyk-expensify

**Comment by dannymcclain** [comment]
@jasperhuangg definitely feels similar to that issue you linked. I think if we can update this for light mode, that would be ideal. But if for some reason we can't/won't/don't want to, I don't think it's the end of the world since this feels almost more like "mapbox modal" than it does Expensify UI.

**Comment by dubielzyk-expensify** [comment]
Yeah, if not, I think we should just revert to using system defaults here so that the OS can take care of the colors. Given this is a mapbox specific thing, I think that's fine

**Comment by dannymcclain** [comment]
[Based on this thread in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1702657731582819), it looks like we've reached a decision to not add any custom styling to native popups and let the OS handle the theming. @grgia that sound right to you?

**Comment by jasperhuangg** [comment]
Bump @grgia on [this comment](https://github.com/Expensify/App/issues/33137#issuecomment-1860803412)

**Comment by jasperhuangg** [comment]
Bumped @grgia via DM

**Comment by grgia** [comment]
Yes that sounds correct, we can close this as I have a master issue for this here https://github.com/Expensify/App/issues/33235

**Comment by dannymcclain** [comment]
Closing per [Georgia's comment](https://github.com/Expensify/App/issues/33137#issuecomment-1881869555)! 🌂
