### ISSUE TITLE
[Theme Switching] 🐛 Android - Scan - Capture error and camera access pop-ups are not in dark mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- App is in light mode
- Camera settings permission is not allowed
1. Launch New Expensify app
2. Go to FAB > Request money > Scan
3. Tap on the capture button
4. Tap Continue button

## Expected Result:
The pop-ups in Step 3 and 4 are in light mode

## Actual Result:
The capture error and camera access pop-ups in Step 3 and 4 respectively remain in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d1c68b5-60d7-47a0-9d1a-fe2b065ace3f

![Bug6313917_1702605474660!Screenshot_2023-12-15_095617](https://github.com/Expensify/App/assets/78819774/89768e37-0a10-4d67-ad5d-2167f4a53f3b)

![Bug6313917_1702605474612!Screenshot_2023-12-15_095634](https://github.com/Expensify/App/assets/78819774/fbe86209-0f97-4ff9-980c-07aee4cafffa)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
This seems to be the same issue as https://github.com/Expensify/App/issues/33120 (the same component), and we're not blocking deploy on that one so I don't think we should block deploy here either.

**Comment by grgia** [comment]
Closing this in favor of https://github.com/Expensify/App/issues/33235
