### ISSUE TITLE
 Status - Inappropriate error message when setting custom time in the past

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Status
3. Click Clear after
4. Click Custom > Time
5. Enter a time in the past
6. Save it

## Expected Result:
The error message shows "Please choose a time in the future"

## Actual Result:
The error message shows "Please choose a time at least one minute ahead." when it should have been "Please choose a time in the future" because the current error message will still result in failure when choosing time one minute ahead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e082b438-4dc2-4a14-b2fc-fe031ba6f180

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
I see nothing wrong with this error message "Please choose a time at least one minute ahead" means to choose a time one minute ahead of the current time, not the time inputted in the form.

We could make it clearer by updating the error message to say "Please choose a time at least one minute in the future".

Regardless, there's no need to block deploy on this.
