### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Theme - Workspace counter in Settings is white and has low legibility

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition:
- User has created at least 5 workspaces.
- App is in light mode.

1. Go to staging.new.expensify.com.
2. Click Settings.

## Expected Result:
The workspace counter on top of workspace avatar should be black for better legibility in light mode.

## Actual Result:
The workspace counter on top of workspace avatar is white and is difficult to notice.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6314248_1702631948446!bandicam_2023-12-15_17-15-47-743](https://github.com/Expensify/App/assets/115492554/42c10db4-8376-45eb-8efe-0c2d5276fa11)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bd4c88cc24f905a</li>
        <li>Upwork Job ID: 1735599612788625408</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by MariaHCD** [comment]
I don't think we should block the deploy on this.

**Comment by MariaHCD** [comment]
@grgia would you be able to clarify what the design should be for the workspace counter when in light mode?

**Comment by MariaHCD** [comment]
👋🏼 @dannymcclain, we'd like some input on the expected design of the workspace counter in light mode.

**Comment by dannymcclain** [comment]
> We should use `theme.text` instead of `theme.textLight`

Totally agree with this. [This proposal](https://github.com/Expensify/App/issues/33146#issuecomment-1857897790) is looking pretty good to me, but I'd love for @grgia and @Expensify/design to double-check to make sure that overlay looks correct.

**Comment by shawnborton** [comment]
Yup, that makes sense to me too!

**Comment by dubielzyk-expensify** [comment]
Agreed

**Comment by MariaHCD** [comment]
Thanks for the input on the design! @thesahindia could you review the two existing proposals and recommend which one we should go with?

**Comment by MariaHCD** [comment]
Thanks for all the proposals here! Although we prioritize the first correct proposal, I believe we also want to find a balance to ensure the most complete proposal is selected. I am not sure the other instances that need to be fixed would have been spotted during implementation and I think it's generally better to determine scope before starting a PR.

I agree with @thesahindia's recommendation to select @gijoe0295's  proposal.

**Comment by dannymcclain** [comment]
I think the avatar camera button should follow our standard primary button styles (the background should be `button`, and the icon should be `icons`). @shawnborton and @dubielzyk-expensify what do you think? That's how we've been styling it in our more recent mocks (even though I guess it is different from what's actually in the product).

![image](https://github.com/Expensify/App/assets/7516624/3cf9c744-ae6b-4fe3-984e-cffebe555833)

**Comment by shawnborton** [comment]
Totally agree with you Danny!

**Comment by dubielzyk-expensify** [comment]
Agreed. I made a comment saying we could do text on the icon to make it stand out, but I think the using button + icon color combo is the right!

**Comment by slafortune** [comment]
@gijoe0295 your offer was sent [here](https://www.upwork.com/nx/wm/offer/100518258), once you accept that I can pay that out.

**Comment by slafortune** [comment]
@thesahindia can you complete the above checklist?

**Comment by slafortune** [comment]
Thanks @thesahindia 👍 

@gijoe0295 has been paid $500 via upworks

@thesahindia is owed $500 via new dot

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
