### ISSUE TITLE
[$500] IOU- With a larger IOU counter-request, the payment button appears for user B instead of user A

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Steps 1:
1. Open New Expensify app
2. Log in on any devices under account A and B
3. From account A, send a manual IOU to user B in the currency KZT
4 From user B, send a manual IOU to user A for 1 KZT or 2 KZT more than user A IOU.

Steps 2:
1. Open New Expensify app
2. Log in on any devices under accounts A and B
3. From account A, send a manual IOU to user B in the currency AED
4. From user B, send a manual IOU to user A for 0.01 AED more than user A IOU.

## Expected Result:
If user B requests an IOU amount greater than the request from user A, a green payment button should appear for user A.

## Actual Result:
User B has a "Pay elsewhere" button if he has increased the amount of counter-requested money by 1 or 2 and the amount is greater than user A request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c7148ecb-2b1e-48a0-b9f4-79715473e5ae

https://github.com/Expensify/App/assets/115492554/ce950db7-d274-411d-8e2b-3ebd8f5cf338

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019842436de443b827</li>
        <li>Upwork Job ID: 1735628649878507520</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
This is BE error. The backend returns wrong `managerID` . We can save correct `managerID` for current user which will help us to achieve a desired behavior only for current user, because the backend will send wrong data to second user via pusher  anyway

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 Agree agree! This is a backend bug

**Comment by rushatgabhane** [comment]
@Beamanator steps
1. As user `A`, request $100 to user `B` 
2. As user `B`, request $100.01 to user `A`

Expected: user `A` is shown the pay $0.01 button
Actual: user `B` is shown the pay button

**Comment by Beamanator** [comment]
planning to get back to this this week - making internal

**Comment by Beamanator** [comment]
argg, probs won't get to this till next week

**Comment by muttmuure** [comment]
Think you'll get to this issue this week @Beamanator? I can reapply the label

**Comment by muttmuure** [comment]
Just waiting on @Beamanator to fit this into a cycle

**Comment by Beamanator** [comment]
Oof ya haven't had time for this yet, mind reapplying the label / asking for volunteers in slack? 🙏

**Comment by muttmuure** [comment]
posted to Slack

**Comment by muttmuure** [comment]
Asked in Wave 5 https://expensify.slack.com/archives/C05DWUDHVK7/p1705337760385459?thread_ts=1702890176.663399&cid=C05DWUDHVK7

**Comment by muttmuure** [comment]
Bumped Wave 5

**Comment by cristipaval** [comment]
handing this over to @tgolen as per [this convo](https://expensify.slack.com/archives/C05DWUDHVK7/p1705574914639919?thread_ts=1702890176.663399&cid=C05DWUDHVK7)

**Comment by tgolen** [comment]
@izarutskaya @rushatgabhane I am not able to reproduce this. I verified I am on the latest branches for both the frontend and our backend. Is it possible it's already been fixed? Are you still able to reproduce it? I've followed the instructions and tried it several different ways:

1. From global create
2. From composer + menu
3. Using different currencies

Please see this video of me reproducing it and seeing the expected behavior.


https://github.com/Expensify/App/assets/1228807/f46b3d15-2280-466a-827d-eb760caddc9b
