### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] Theme - "Join the discussion" is illegible and inconsistency in sign-in modal theme in public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Device is in light mode.
1. Log out.
2. Go to a public room (eg: https://staging.new.expensify.com/r/5408450846930023).
3. Click Sign in.

## Expected Result:
- Content will be legible.
- The sign-in component will be displayed entirely in dark mode because sign-in interface will always be in dark mode.

## Actual Result:
- "Join the discussion" sentence is not legible because the font is white on a white background.
- The header on sign-in modal is in light mode, while the rest is in dark mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/369da4b6-9771-4ad9-a1e1-8ecbdc2ba5bf)

![image](https://github.com/Expensify/App/assets/93399543/1e5cb8aa-0ca5-4bed-a159-aac02d44fe99)

https://github.com/Expensify/App/assets/93399543/e257218d-a1ba-47a3-a624-20771824fac6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
👋 @grgia @chrispader Got a new one for you here! 🙇‍♀️

**Comment by chrispader** [comment]
working on it! :)

**Comment by situchan** [comment]
@abzokhattab have you tested your proposal? After applying your solution, it looks more ugly.
We should use fixed dark theme for signin page for now.


<img width="374" alt="Screenshot 2023-12-15" src="https://github.com/Expensify/App/assets/108292595/f1098206-9603-4239-9e22-a1b9e2652a7d">

What we should fix here is just header color:
<img width="375" alt="Screenshot 2023-12-15" src="https://github.com/Expensify/App/assets/108292595/8c87e104-f2e8-404e-82fa-33fdab62f280">

**Comment by amyevans** [comment]
Not open for proposals, thanks for checking!

**Comment by grgia** [comment]
For the bottom "join the discussion" text, lets use theme.text @chrispader

**Comment by grgia** [comment]
https://github.com/Expensify/App/blob/ce75f7cab99b3df83fcde07ae0e4999add9d95a2/src/styles/index.ts#L2375

**Comment by shubham1206agra** [comment]
Commenting here

**Comment by grgia** [comment]
@sonialiap would you mind helping to ensure that @shubham1206agra receives $500 C+ review payment for https://github.com/Expensify/App/pull/33181

**Comment by sonialiap** [comment]
@shubham1206agra offer sent

[Upwork job post](https://www.upwork.com/jobs/~014e2cab8fec73fb00)

**Comment by shubham1206agra** [comment]
Accepted

**Comment by sonialiap** [comment]
Paid ✔️
