### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Wallet - Extra top padding on each field in Additional details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33154]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/enable-payments

## Expected Result:
Each field is spaced adequately.

## Actual Result:
Each field has excess top padding, making each field look wide apart from one another.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Bug6314446_1702641030388!Screenshot_2023-12-15_at_18 35 02" src="https://github.com/Expensify/App/assets/115492554/7e2f4991-4f18-49b9-bb1f-928d44dd7cfc">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a9a9a0a9a660619</li>
        <li>Upwork Job ID: 1735630071530536960</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 28062309</li>
</ul></li>
    </ul>
</details>

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra top padding on each field in Additional details page
### What is the root cause of that problem?
Currently we have a margin-top: 16px
```
containerStyles={[styles.mt4]}
```
### What changes do you think we should make in order to solve the problem?
we should remove margin-top
```js
containerStyles={[styles.mt4]} // remove
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by FitseTLT** [comment]
But why is it not reproducible in production @namhihi237? Because the line of code you're referring to is an old one. 😕

**Comment by mountiny** [comment]
I think this is minor issue so it does not have to be a blocker, but also I think that should be handled with the PR authors @perunt @allroundexperts @jjcoffee

**Comment by perunt** [comment]
I'll fix it now

**Comment by mountiny** [comment]
Bumped in slack

**Comment by perunt** [comment]
I made a PR for that. It's a duplication of the style's name. I don't know why it wasn't a thing on merge conflicts.
![image](https://github.com/Expensify/App/assets/48593211/757eeaaa-69a0-4451-81b4-129ac5d9f058)

**Comment by stephanieelliott** [comment]
Hey @perunt @allroundexperts @jjcoffee is there a PR for this? I don't see one linked.

**Comment by perunt** [comment]
@stephanieelliott, here's the PR that resolved the issue: https://github.com/Expensify/App/pull/33221

**Comment by stephanieelliott** [comment]
All reviews completed, PR is undergoing QA

**Comment by stephanieelliott** [comment]
This is a followup PR to resolve a regression from a PR that the contributor/C+ reviewed, so no payment is due here! Payment will be handled on the original issue.
