### ISSUE TITLE
[Theme Switching] 🐛 Android - Scan - "Wrong attachment" pop-up is not in light mode and incorrect 'filetype' spelling

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App is in light mode.
1. Launch New Expensify app.
2. Tap + > Request money > Scan.
3. Upload an unsupported file.

## Expected Result:
The pop-up for "wrong attachment type" is in light mode. No spelling issue in the error message.

## Actual Result:
The pop-up for "wrong attachment type" remains in dark mode. Also, 'filetype' is written instead of 'file type'.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/d9dbf4e2-9496-4fd0-af7d-8999d98ca323)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Not worth blocking the deploy. Will likely be resolved along with [other Modal theme issues](https://github.com/Expensify/App/issues/33136#issuecomment-1857624895)

**Comment by arosiclair** [comment]
This deployed to prod [a while ago](https://github.com/Expensify/App/pull/33167#issuecomment-1865493557).
