### ISSUE TITLE
Status - In the time section, pressing button 2 displays 8

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Status
3. Click Clear after
4. Click Custom > Time
5. Place the cursor before the first zero
6. Press button 2

## Expected Result:
When entering number 2, the cursor should remain 0

## Actual Result:
In the time section, pressing button 2 displays 8

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/74f0e5cc-8ca5-428e-896f-6df0f059ac36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
This is expected behaviour as App assumes the input 20, which will be converted to 8:00 PM

**Comment by NikkiWines** [comment]
Yep, since the clock is in 12hr time it's expected, this isn't a bug
