### ISSUE TITLE
[$500] Workspace - required validation not cleared on date select

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace-> bank account
3. Select connect manually
4. Fill in details in step 1 and continue, eg details: routing no = 210021002, acc no = 349483948
5. In step 2, without filling in any details, click on Save & continue, it will trigger validation error for all fields
6. Select any date in Incorporation date, observe that even on selecting date, required field validation is not removed
7. Make changes to any other field and observe that now required field validation for date is removed

## Expected Result:
App should remove required field validation as soon as we fill in the details in that field

## Actual Result:
App does not remove required field validation error from date field even after selecting date in workspace connect bank account step 2/ step 3

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/107ca2ee-81ac-4b7f-8beb-81d72d7096aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdbdb554b6c6aa23</li>
        <li>Upwork Job ID: 1735691867126185984</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I am going to close this one, its not worth putting this on hold I think
