### ISSUE TITLE
[hold for payment 2024-04-17] - Avatar placeholder remains in dark mode when app is in light mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33161]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: App is in light mode.
1. Launch New Expensify app.
2. Go offline.
3. Tap Search.
4. Look for user with placeholder avatar.

## Expected Result:
The avatar placeholder will be displayed in light mode.

## Actual Result:
The avatar placeholder remains in dark mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/0fb62a07-5d2f-45e9-bb30-01c13642e45a)

https://github.com/Expensify/App/assets/93399543/06a07529-e630-452e-b530-aec5c6be75aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b86fc7d9a009aa8d</li>
        <li>Upwork Job ID: 1737654517482057728</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by Julesssss** [comment]
This isn't worth blocking the deploy, so I removed the label.

**Comment by grgia** [comment]
This is just the image we use for the fallback avatar, so it's not technically a bug. @dubielzyk-expensify do you think we should use a theme-specific image here?

**Comment by dubielzyk-expensify** [comment]
Sure can. Do you have a link to the original so I can check the export settings?

**Comment by dubielzyk-expensify** [comment]
Think I found this [here](https://github.com/Expensify/App/blob/main/assets/images/avatars/fallback-avatar.svg) and it seems to use outdated colors as well, so uploading both new dark and light version of our `fallback avatar`:

[svgs.zip](https://github.com/Expensify/App/files/13698149/svgs.zip)

![fallback-avatar-dark](https://github.com/Expensify/App/assets/145416827/bde9eb24-ecf8-42ad-8ac0-b0ed3eee3ebf)
![fallback-avatar-light](https://github.com/Expensify/App/assets/145416827/437b5fb1-b4a9-460b-a673-66e81b1f4195)


cc @Expensify/design

**Comment by shawnborton** [comment]
Nice! What color are you using for the fallback avatar BG color? We _might_ want to use something like the icon color as the BG here so that we never have any worry about the icon getting lost in the LHN depending on active or hover states. Actually that being said, I think our border color (same BG as buttons) would be a good BG color as it won't collide with rowHover or the active/press state?

**Comment by dubielzyk-expensify** [comment]
It's currently the background is using `borders` and the icon uses `icon` color:
![CleanShot 2023-12-19 at 09 44 57@2x](https://github.com/Expensify/App/assets/145416827/7bd7b335-7d04-40c4-8ba0-ebd0dd17b5e8)

**Comment by shawnborton** [comment]
Lovely! Let's do it then!

**Comment by dannymcclain** [comment]
`:chef-kiss:`

**Comment by grgia** [comment]
On it!

**Comment by grgia** [comment]
Some of these are definitely unused

**Comment by grgia** [comment]
I think we can delete all the room avatars. But we do need the workspace version @dubielzyk-expensify

**Comment by dubielzyk-expensify** [comment]
Ask and you shall receive. Workspace default avatar for both light and dark mode:
[avatar-workspace.zip](https://github.com/Expensify/App/files/13733713/avatar-workspace.zip)

Let me know if others are needed.

**Comment by grgia** [comment]
@dubielzyk-expensify could I get the original fallback avatar ones with the same bounding box as those two as well? They look different on preview 

<img width="300" alt="image" src="https://github.com/Expensify/App/assets/38015950/cb2dabda-051c-4f96-97c3-7a17cbdd4860"><img width="300" alt="image" src="https://github.com/Expensify/App/assets/38015950/e8a2f318-8fc6-4613-be41-ebceaadb70b5">

**Comment by dubielzyk-expensify** [comment]
>could I get the original fallback avatar ones with the same bounding box as those two as well? 

Here ya go.
[avatar-fallback.zip](https://github.com/Expensify/App/files/13734387/avatar-fallback.zip)

**Comment by dubielzyk-expensify** [comment]
Let me know if there's anything else needed from my side

**Comment by dubielzyk-expensify** [comment]
Not overdue Melvz

**Comment by dubielzyk-expensify** [comment]
Any updates here?

**Comment by joekaufmanexpensify** [comment]
@grgia is weekly still the right prioritization for this one, or should I bump to monthly?

**Comment by joekaufmanexpensify** [comment]
Gonna bump this one to monthly. There's a [WIP PR](https://github.com/Expensify/App/pull/33390), but no recent progress. @grgia LMK if we plan to prioritize this one sooner than that and happy to adjust it

**Comment by dubielzyk-expensify** [comment]
Any updates on this one?

**Comment by joekaufmanexpensify** [comment]
I think the next step is to continue with the draft PR.

**Comment by grgia** [comment]
Yeah going to get this one updated this week as it relates to another bug

**Comment by grgia** [comment]
Found a much easier way to do this, going to create a new PR

**Comment by joekaufmanexpensify** [comment]
PR out on staging

**Comment by joekaufmanexpensify** [comment]
PR is on prod. Payment due on 2024-04-17

**Comment by joekaufmanexpensify** [comment]
@s77rt do you think a regression test would be helpful here?

**Comment by s77rt** [comment]
It's unlikely that this bug would resurface again. Let's not add a specific test case here. The generic one should be enough https://expensify.testrail.io/index.php?/cases/view/2990277

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here. Only payment is $250 to @s77rt via upwork for C+ review. (Would've normally been $500 based on when the issue was created, but this one [had a regression](https://github.com/Expensify/App/issues/33161#issuecomment-2044765027)).

**Comment by joekaufmanexpensify** [comment]
OG upwork job is closed, so I opened [a new one](https://www.upwork.com/ab/applicants/1782414237384433664/job-details).

**Comment by joekaufmanexpensify** [comment]
@s77rt offer sent for $250!

**Comment by s77rt** [comment]
@joekaufmanexpensify Accepted! Thanks!

**Comment by joekaufmanexpensify** [comment]
@s77rt $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
