### ISSUE TITLE
[CRITICAL] Backwards Compatibility - Changing report type from Expense to Invoice or Paycheck

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33178]
Problem
As part of the workspace chats for https://github.com/Expensify/Expensify/issues/309695, we need to make sure actions possible to take in OldDot are correctly reflected in NewDot.

One of them is changing report types and how that influences the reports in NewDot view.

The high level details are explained in the Design doc section [here](https://docs.google.com/document/d/1arowjiiYSu4fyu0CYrB8748UOz4oEDaWZzmXpGKwg-k/edit#bookmark=id.hfvnia8ov1vs) in terms of what we need to do.

Please bring any questions to the wave6 room, the design doc is not written in a lot of detail but the things we need to do are captured there is plain English

---

## Solution

Because other OldDot report types other than Expense are not supported in NewDot we do not plan to support them as part of wave6, we need to make sure we handle them gracefully when a user decides to change the type of already existing open report.

When a user changes from the expense type to another report type, we are going to:

- [x] Remove the parent report rNVP and parent report action rNVPs from the report so it's not a thread anymore.
- [x] Likewise, we are going to delete the REPORTPREVIEW report action which was on the workspace chat.

This should be enough to “clean-up” the expense report.

If a user changes an Invoice report type into an expense report type, we are going to have to do the opposite, hence:

- [ ] Create report preview report action tying the report with employee’s workspace chat
- [ ] Link the new expense report with the report preview action as parent report action
- [ ] Set the workspace chat as the parent report ID

This should ensure the expense report will be discoverable in the NewDot.

Note: We will have to verify if we can leave access to the threads from the unsupported report types in NewDot. Currently we do not plan to remove access to such threads when we change type from expense to invoice report for example.

**Comment by iwiznia** [comment]
Isn't this quite similar to https://github.com/Expensify/App/issues/33177 and as such most probably better to do one and then the other reusing the same code? Or work on them together given they are quite similar?

**Comment by yuwenmemon** [comment]
I'm working on that similar issue so will pick this one up too while the other is in review.

**Comment by yuwenmemon** [comment]
This has been complete for some time. Closing!
