### ISSUE TITLE
[HOLD for payment 2024-01-02] [$500] Settings - Focus shifts to first digit on shortcut & back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33170]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings->profile->contact methods
3. Open pending contact method or add new and open that contact method
4. Type in few digits in the code and use any of the keyboard shortcuts eg: CTRL+K, CTRL+J etc
5. Click on back and observe that app refocuses back to first magic code input instead on focusing on next empty magic code input OR the magic code input which was focused before opening keyboard shortcut

## Expected Result:
App should focus back to next empty magic code input OR magic code input which was focused before opening keyboard shortcut on back from any keyboard shortcut

## Actual Result:
App focuses on first magic code input on back from keyboard shortcut even though focus was on other magic code input before opening any keyboard shortcut

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7293e50c-0b84-48a5-95ad-b05053310739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143f494715bf21dfc</li>
        <li>Upwork Job ID: 1735693221598715904</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28065220</li>
<li>Krishna2323 | Contributor | 28065221</li>
</ul></li>
    </ul>
</details>

**Comment by artus9033** [comment]
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by lschurr** [comment]
Could you review the proposal @alitoshmatov?

**Comment by alitoshmatov** [comment]
Reviewing

**Comment by alitoshmatov** [comment]
@Krishna2323 Your RCA is correct. Your solution solves a problem and straightforward

We can go with @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/33170#issuecomment-1858170050)

C+ reviewed 🎀 👀 🎀

**Comment by lschurr** [comment]
@alitoshmatov could you work through the checklist on this one?

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: @Krishna2323 $500
- Contributor+: @alitoshmatov $500

**Comment by lschurr** [comment]
Payments sent in Upwork. Closing this one out.
