### ISSUE TITLE
[$500] Assign task -Previous user(not task creator) can reassign task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
Preconditions : User is a group member (not task creator) and was previously assigned a task.
1. Log in to a Staging.new.expensify.com
2. Navigate to task report
3. Reassign the task to a different user.

## Expected Result:
The previous assignee cannot reassign the task.

## Actual Result:
The previous assignee can reassign the task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/81341156-e366-4852-8ea3-5d279acb3dc7

![Bug6313074_1702561178125!bugreas1](https://github.com/Expensify/App/assets/115492554/76833c24-f089-4807-92db-22b426e5df9a)

![Bug6313074_1702561178116!bugreas2](https://github.com/Expensify/App/assets/115492554/e7e85bdf-2cb1-4947-a9c8-d6560d6cf7ab)

![Bug6313074_1702561178102!bugreas3](https://github.com/Expensify/App/assets/115492554/1cd71e83-b499-47de-9e3e-5fa5cdcfc662)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112f58408ed913c98</li>
        <li>Upwork Job ID: 1735729310659461120</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
will be dealt [here](https://github.com/Expensify/App/issues/33183)

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/issues/33183#issuecomment-1858355490
