### ISSUE TITLE
[$500] Message - Deleted message report created in admin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user A, invite user B to any workspace
4. From user B, in the newly created workspace chat, reply in thread to only visible to you message and send any message
5. Check in user A, new report will popup in LHN with [deleted message] title, on opening the report, it displays red dot error

## Expected Result:
App should either not allow reply in thread on 'only visible to you' messages or should not create [Deleted message] report in admin login

## Actual Result:
App creates new [Deleted message] report for admin when invited user reply in thread on 'only visible to you' message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/113970f2-07d5-4894-8d56-a907bf214e66

https://github.com/Expensify/App/assets/115492554/12771833-4706-4b65-8a22-673927154b7d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f63d7fc4058f34</li>
        <li>Upwork Job ID: 1735742544369840128</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @izarutskaya</details>

**Comment by razvanb96** [comment]
seems like it's not reproducible. The `only visible to me` doesn't have an action for replying in thread. @izarutskaya can you confirm this and  if it's till reproducible provide some more details on User B interactions?

**Comment by razvanb96** [comment]
Contributor details
Your Expensify account email: razvanb96@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010b468438ff4cc09d

**Comment by sonialiap** [comment]
@izarutskaya like Razvan I am confused by this report
>From user B, in the newly created workspace chat, reply in thread to only visible to you message and send any message

I don't believe this is possible and I don't see it shown in your recordings. Can you please confirm what steps you are taking?

**Comment by sonialiap** [comment]
@izarutskaya bumping the question above :)

**Comment by izarutskaya** [comment]
I cannot reproduce it anymore.  Now "Only visible to you" message don't have "reply in thread" button.
Build v1.4.17-1

https://github.com/Expensify/App/assets/115492554/6dcca024-912b-4769-b7b8-82dd5bc8895d

**Comment by sonialiap** [comment]
Nice, closing
