### ISSUE TITLE
[HOLD for payment 2024-03-14] HIGH: Onyx updates from push notifications can get applied out of order

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#33191]
~*Note: Waiting for #34082 to build the troubleshooting tools*~

- Coming from [this slack convo](https://expensify.slack.com/archives/C03SDMF9YJ2/p1702645265570599) cc @iwiznia 

## Problem

When a user receives a report comment, we send them a push notification for it. The notification payload contains Onyx updates for the report and the new report action. We apply those onyx updates [here](https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts#L15) and call `ReconnectApp` in the background using [backgroundRefresh](https://github.com/Expensify/App/blob/arosiclair-ios-comms-notifications/src/libs/Notification/PushNotification/backgroundRefresh/index.android.ts#L42). 

There is a chance this update gets applied out of order eg:

1. User A sends a message and edits it quickly
2. User B applies updates for the new message and edit from Pusher
3. User B receives a delayed push notification for the message and applies the update for the original un-edited message

## Why is this important?

If this happens, the report and report action data will stay out of date until the next updates are received

## Solution

Start including `lastUpdateID` and `previousUpdateID` in the notification payload and use those to apply the update like we do for reliable updates [here](https://github.com/Expensify/App/blob/4707abaf0a9181aa1991dfb425cd62078217a471/src/libs/actions/User.js#L504-L517) so those updates always get applied in order.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a77e81664929acf</li>
        <li>Upwork Job ID: 1735753015692898304</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by arosiclair** [comment]
No progress on this yet. I'm heads down on Notification Polish and then OOO for a couple days. I should be able to get to this next week.

**Comment by mallenexpensify** [comment]
@allroundexperts can you review the PR?
https://github.com/Expensify/App/pull/33371

I think you might not have been auto-assigned cuz of the formatting here? (reallly don't know, just trying to expedite a fix here)
> Related to https://github.com/Expensify/App/issues/33191 and https://expensify.slack.com/archives/C049HHMV9SM/p1703005526338499

**Comment by allroundexperts** [comment]
Sure, thanks for the reminder!

**Comment by quinthar** [comment]
If this is real it sounds more serious than #vip-vsb, can you put this into a wave?

**Comment by arosiclair** [comment]
Discussed this [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1703580938624779).

Getting the `previousUpdateID` and `lastUpdateID` for the report action and report onyx updates is not trivial since we don't create those in Auth currently. So it looks like the best approach is to start doing that in Auth.

Specifically, we'd have to build and queue the updates for all participants in the report as we do in [ReportUtils::notifyParticipantsForActions](https://github.com/Expensify/Web-Expensify/blob/d9722d8b802aa7c68776894a7a5c9ca436230fac/lib/ReportUtils.php#L2181). We can start with just `ADDCOMMENT` actions since there's some extra complexity for others (eg: [IOU Actions](https://github.com/Expensify/Web-Expensify/blob/d9722d8b802aa7c68776894a7a5c9ca436230fac/lib/ReportUtils.php#L1930-L1979)). 

The bulk of this logic is in [ReportUtils::buildOnyxDataForNewAction](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportUtils.php#L1873) and [Report_Action_Item::getDisplayInformation](https://github.com/Expensify/Web-Expensify/blob/d9722d8b802aa7c68776894a7a5c9ca436230fac/lib/Report/Action/Item.php#L597).

Once we're queueing these updates in Auth, the `previousUpdateID` and `lastUpdateID` will be included in the [CreateReportAction response](https://github.com/Expensify/Auth/blob/main/auth/command/CreateReportAction.cpp#L302) and we can put those in the push notification payload.

**Comment by arosiclair** [comment]
Started this yesterday and continuing today. I'll post an (incomplete) draft PR with some of the changes soon.

**Comment by roryabraham** [comment]
I see @iwiznia mentioned [in slack](https://expensify.slack.com/archives/C03SDMF9YJ2/p1703868963534609):

> We still can't put everyone in the beta because report actions are sent in PHP and with different data for each user. We need to refactor that and ideally move the logic to auth. 
[@Andrew Rosiclair](https://expensify.slack.com/team/U036UNTL8A1)
 is going to work on a first step of that in https://github.com/Expensify/App/issues/33191

Meanwhile, I have a [potentially related issue](https://github.com/Expensify/App/issues/33461#issuecomment-1867039429) where the `participantAccountIDs` are different per-user and sometimes wrong due to a bug. While I [proposed a potential fix to the bug](https://github.com/Expensify/App/issues/33461#issuecomment-1867121135). @thienlnam made a good point that maybe a better solution would be to refactor it so that the `participantAccountIDs` are always the same for a given report.

i.e: reportActions are sent with different data for each user, which seems like an anti-pattern.

@arosiclair Is this something you'll be working on in this issue?

**Comment by iwiznia** [comment]
Correct, given we want to be able to take advantage of the new report channel type for updates, we need to ensure that the update we send is the same to all users of the report.
Of course the only exception would be whispers that will  be queued in the user(s) channel.

**Comment by arosiclair** [comment]
> @thienlnam made a good point that maybe a better solution would be to refactor it so that the participantAccountIDs are always the same for a given report.

This makes sense to me too. If we push that change, nothing major will break in NewDot?

> Of course the only exception would be whispers that will be queued in the user(s) channel.

Yeah I believe the per-user exceptions are just whispers and mentions. For mentions, it looks like the only user-specific part of the update is the `lastMentionedTime` on the report. I think we can just put that part in a separate onyx update in the user's channel.

**Comment by iwiznia** [comment]
> Yeah I believe the per-user exceptions are just whispers and mentions. For mentions, it looks like the only user-specific part of the update is the lastMentionedTime on the report. I think we can just put that part in a separate onyx update in the user's channel.

Either that or we send the lastMentionTime of every user... anyway it is similar to the lastRead time, whatever we decide for one should be good for the other

**Comment by roryabraham** [comment]
> If we push that change, nothing major will break in NewDot?

No, I assume that front-end changes will be needed to prevent this change from breaking shit

**Comment by JmillsExpensify** [comment]
Discussions immediately above. Looks like they are still on-going.

**Comment by arosiclair** [comment]
ETA for this is next week. I've made some progress focusing on writing tests first.

**Comment by arosiclair** [comment]
Spent the last couple days addressing a mini-fire with report exports. Managed to finish initial version of Auth tests. I'll move forward with the real implementation next week.

**Comment by arosiclair** [comment]
Was testing onyx updates with basic report comments (no mentions or whisper). I can continue working on this but asking if I should pause [in slack](https://expensify.slack.com/archives/C066HJM2CAZ/p1704992433561179).

**Comment by arosiclair** [comment]
Started to implement basic comment onyx updates however verifying them in tests are a pain so far. Many type issues that I figured out so far but the biggest one is some kind of flakey-ness with the `previousReportActionID`.

I pushed some changes to sort report actions consistently [here](https://github.com/Expensify/Auth/pull/9656), but that hasn't completely fixed the issue. I'll continue work next week

**Comment by arosiclair** [comment]
Major items to address:

1. `person` object
    - This is used for showing the user's display name
2. `message.text`
    - This should be the same as `reportAction.message.html`, but with html tags stripped
3. `lastMentionedTime`
    - We need to send another onyx update with this property to the person that was mentioned
4. Thread replies
    - All of these [thread specific properties](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/Item.php#L708-L755)

**Comment by arosiclair** [comment]
Made good progress last week. Here's the remaining items to address with ETAs

1. [reportAction.avatar](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/Item.php#L692) (1 day)
2. Thread replies (2 days)
    - All of these [thread specific properties](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/Item.php#L708-L755)
3. Moving push notifications to [SendFetchableOnyxUpdates](https://github.com/Expensify/Web-Expensify/blob/main/script/bwm/SendFetchableOnyxUpdates.php) job and updating NewDot (2-3 days)

**Comment by arosiclair** [comment]
@roryabraham just an FYI, I realized while chatting with Ionatan that we won't actually be fixing the `report.participantAccountIDs` problem with this issue since the Onyx updates for adding report comments don't affect that data. I think that would be fixed by a change to `OpenReport`, but not sure.

**Comment by roryabraham** [comment]
Thanks for the heads-up, I've been planning to tackle that problem in https://github.com/Expensify/App/issues/33461

**Comment by arosiclair** [comment]
Alright all data for these Onyx updates should be good and Auth tests are now passing consistently. Remaining steps:

1. Fix some Web-E tests that were affected (0.5 days)
2. Moving push notifications to [SendFetchableOnyxUpdates](https://github.com/Expensify/Web-Expensify/blob/main/script/bwm/SendFetchableOnyxUpdates.php) job and updating NewDot (2-3 days)

**Comment by arosiclair** [comment]
Making good progress on this. Initial testing is going well

- DMs ✅ 
- Group DMs ✅ 
- Mentions ✅ 
- Attachments ✅ 
- Web notifications ✅ 

I also handled users that are _not_ using reliable updates ([slack convo](https://expensify.slack.com/archives/C03SDMF9YJ2/p1706709615200799)).

I still have to 

1. Fix Web-E integration tests
2. Send push notifications in [SendFetchableOnyxUpdates](https://github.com/Expensify/Web-Expensify/blob/main/script/bwm/SendFetchableOnyxUpdates.php).
3. Update NewDot to apply the updates reliably

**Comment by arosiclair** [comment]
Fixed a couple Web-E tests since the last update but never finished (had to prioritize a mini-fire with push notifications). 

Continuing work on this:

1. Fix remaining Web-E integration tests (1-2 days)
2. Send push notifications in [SendFetchableOnyxUpdates](https://github.com/Expensify/Web-Expensify/blob/main/script/bwm/SendFetchableOnyxUpdates.php). (1 day)
3. Update NewDot to apply the updates reliably (1 day)

I'll open the Auth PR for review since that's stable at this point

**Comment by arosiclair** [comment]
In the final stretch for this. Each PR is code complete. Just need to address some concerns from @iwiznia on the Auth PR and get reviews for the Web-E and App PRs.

- [Auth](https://github.com/Expensify/Auth/pull/9575)
- [Web-E](https://github.com/Expensify/Web-Expensify/pull/40706)
- [App](https://github.com/Expensify/App/pull/36047)

**Comment by arosiclair** [comment]
Realized I still had to handle whisper messages. Just finished handling that case. Now I have a test failing in CI but not locally 🙃. I'm going to reach out in #engi-chat on how to get that fixed.

**Comment by arosiclair** [comment]
- Auth PR is deployed
- Web-E PR is ready for review & merge
- App PR will be ready for testing once the Web-E is deployed

**Comment by iwiznia** [comment]
Nice, super excited for this to go out. Thanks for the hard work on it! ❤️

**Comment by arosiclair** [comment]
All PR's are now merged. Just waiting for the App PR to hit staging so I can QA. ETA is EOW.

**Comment by arosiclair** [comment]
QA on staging passed! This should be out on prod in the next deploy. ETA is today/tomorrow.

**Comment by arosiclair** [comment]
This wasn't really a regression just new functionality for reliable updates.

**Comment by JmillsExpensify** [comment]
The payment summary above is correct, so @allroundexperts please add this one to your next round of Expensify requests. Closing in the meantime.

**Comment by joekaufmanexpensify** [comment]
Stepping in for payment summary for Jason. Only payment is $500 to @allroundexperts for PR review. Paid via NewDot.

**Comment by JmillsExpensify** [comment]
Thanks! $500 approved for @allroundexperts
