### ISSUE TITLE
[$500] Assign task -Inconsistent name for button(Test Rail vs Expensify)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33192]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
Preconditions : User is a group member and was previously assigned a task.
1. Log in to a Staging.new.expensify.com
2. Navigate to task report
3. Delete the task

## Expected Result:
"cancelled task [task name]" is displayed in the task report

## Actual Result:
"deleted task" is displayed in the task report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2619240b-62ba-46b8-bf9e-e64730c948e0

![Bug6313301_1702571502602!deltask](https://github.com/Expensify/App/assets/115492554/89df70b1-41e8-4e7b-b836-6bc5dec5c840)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c357d97ea979298a</li>
        <li>Upwork Job ID: 1735756559976394752</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Agreed. Let's close this out.
