### ISSUE TITLE
[$500] SMS - Grammar error in the sent SMS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a new account with your phone number
3. Open the SMS on your phone

## Expected Result:
It should be "sign-in link"

## Actual Result:
Grammar error in the sent SMS "signin link"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6315651_1702708145040!screenshot_20231214_193828_messages (1)](https://github.com/Expensify/App/assets/78819774/b9776bb2-7a30-434b-9265-9c4bf4bbc2b6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ef281b02c82452c</li>
        <li>Upwork Job ID: 1736433456983932928</li>
        <li>Last Price Increase: 2023-12-17</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SMS - Grammar error in the sent SMS
### What is the root cause of that problem?
The text is written wrong in translation
### What changes do you think we should make in order to solve the problem?
Write correct text in translations

### What alternative solutions did you explore? (Optional)

**Comment by karimiBadr** [comment]
Contributor details
Your Expensify account email: karimi.badr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019e38b1e23b4aab51

**Comment by KipngetichTowett** [comment]
Just add a whitespace. Not a big deal😂

**Comment by sobitneupane** [comment]
@twisterdotcom I think this should be `Internal`. The message is generated in the backend.

**Comment by KipngetichTowett** [comment]
Contributor details
Your Expensify account email: <manukipngetichtowett@gmail.com >
Upwork Profile Link: <https://www.upwork.com/freelancers/~013760c31f48a9567a>

**Comment by KipngetichTowett** [comment]
Contributor details
Your Expensify account email: manukipngetichtowett@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~013760c31f48a9567a

**Comment by twisterdotcom** [comment]
Okay, making this `Internal`

**Comment by twisterdotcom** [comment]
I think this is here: https://github.com/Expensify/Web-Expensify/blob/main/notifications/SendValidateCode.txt

Tests here too perhaps: https://github.com/Expensify/Web-Expensify/blob/cd4465a1094c5424d31162be86a80cb73671a0f5/_tests/unit/lib/LogTest.php#L65-L74

We did vet this copy here though: https://github.com/Expensify/Expensify/issues/265298

**Comment by twisterdotcom** [comment]
@danielrvidal do we care about this wording? `signin` vs `sign-in`? Note that we did use `signin` in our April newsletter:

<img width="943" alt="image" src="https://github.com/Expensify/App/assets/9133401/7dd12ce7-ab2f-49c1-9aa8-8a733c5166d2">

**Comment by danielrvidal** [comment]
I do think we care, it looks like we got it wrong in that newsletter, but let's get it right here. Here is from our[ copy guide](https://stackoverflowteams.com/c/expensify/questions/7025/).
>"sign in" (verb: Ex. "I need to sign in.") vs "sign-in" (adjective: Ex. "Those are my sign-in details.", and never "signin" More info [here.](https://grammarhow.com/sign-in-signin-or-sign-in/)

So I think this should be "sign-in" as a noun comes after it in this context.

**Comment by twisterdotcom** [comment]
Perfect, thanks for the help @danielrvidal. I am _pretty sure_ I can just do this.

**Comment by twisterdotcom** [comment]
Oh my, @jamesdeanexpensify did it already: https://github.com/Expensify/Web-Expensify/pull/40230

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.28-0

![Screenshot_20240119_194140_Messages](https://github.com/Expensify/App/assets/78819774/6f5e0fc7-92cb-44b8-b8c1-d434b489d5e8)

**Comment by jamesdeanexpensify** [comment]
We really need to tone down the "magic" of this message and make it shorter/more concise in general. I'd suggest almost exactly what we've updated the email copy to recently. Something like:

`Use [CODE] to sign into Expensify or just tap here: [LINK]
`

**Comment by twisterdotcom** [comment]
@jamesdeanexpensify you did fix that in the above PR. It was tested to an email, but not SMS.

<img width="1048" alt="image" src="https://github.com/Expensify/App/assets/9133401/4549adb7-ebb2-41c6-8247-c9ea631038d5">

I'm not sure how we make sure this works via SMS tbh. I can't find any code that references `signin` left.

**Comment by twisterdotcom** [comment]
@NikkiWines any idea why this might not have propagated to SMS as well?

**Comment by NikkiWines** [comment]
Yes, the SMS copy is set elsewhere because we use Twilio Verify for OTP codes sent via text. [Here's](https://stackoverflowteams.com/c/expensify/questions/16667) the SO post about how to update that copy.

**Comment by jamesdeanexpensify** [comment]
Let me see if I can do this. Thanks, @NikkiWines !

**Comment by jamesdeanexpensify** [comment]
OK, submitted a ticket to Twilio. Put Nikki on cc just in case!

**Comment by twisterdotcom** [comment]
Pa pow!

**Comment by twisterdotcom** [comment]
Is there any way to have Melvin post that in any PR's for the email versions being edited?

**Comment by jamesdeanexpensify** [comment]
I'm not sure. Sounds like a nice to have?

**Comment by jamesdeanexpensify** [comment]
@lanitochka17 do you still have [this screenshot](https://github.com/Expensify/App/issues/33206#issuecomment-1900932007), but of the **full** text? Thanks!
