### ISSUE TITLE
[HOLD for payment 2023-12-29] Fix require cycle from clearReportNotifications.ts

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#33204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** N/A
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Action Performed:
Run NewDot in dev on Android/iOS

## Expected Result:
No warnings about require cycles appear in logs

## Actual Result:

```
 WARN  Require cycle: src/libs/actions/Report.ts -> src/libs/Notification/clearReportNotifications/index.native.ts -> src/libs/Notification/PushNotification/index.native.ts -> src/libs/Notification/PushNotification/ForegroundNotifications/index.ios.ts -> src/libs/Notification/PushNotification/shouldShowPushNotification.ts -> src/libs/actions/Report.ts
```

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2023-12-17 at 11 08 51 AM](https://github.com/Expensify/App/assets/6833644/8f5c4804-d820-490d-b73f-24bda98e2071)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e8796edd86cd329</li>
        <li>Upwork Job ID: 1736418796306968576</li>
        <li>Last Price Increase: 2023-12-17</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
@conorpendergrast no triage needed for this atm. This is a dev issue.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/31762
- The offending PR has been commented on: Not needed since I reviewed the offending PR
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by arosiclair** [comment]
This was just a follow up to [this PR](https://github.com/Expensify/App/pull/31762) for an issue we missed. I implemented both and the same C+ (@s77rt) reviewed so this shouldn't need any extra payment. Closing this out
