### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] Opening a chat crashes due to formatToDayOfWeek throws "Invalid time value"

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#33219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:v1.4.13-6**
**Reproducible in staging?:no**
**Reproducible in production?:no**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

This is a bit hard to reproduce as it will only happen on specific android devices.

1. Open a report

## Expected Result:

It doesn't crash and the report opens

## Actual Result:

The app crashes with an error

## Workaround:
/

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot_20231218_122133_com expensify chat dev](https://github.com/Expensify/App/assets/16821682/67528208-97ed-4b1b-ab4f-dfb78caa77de)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Note:** I am a developer who experienced this issue during working with a specific tool in the expensify app. Will open a PR in a moment.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee495a90613eb0ab</li>
        <li>Upwork Job ID: 1736737609095274496</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by hannojg** [comment]
PR with a fix is here: https://github.com/Expensify/App/pull/33223

**Comment by garrettmknight** [comment]
Offer sent.

**Comment by mountiny** [comment]
PR got merged so it will be $500 to @abdulrahuman5196 for testing and review after prod deploy

**Comment by abdulrahuman5196** [comment]
The PR has already been merged melvin

**Comment by garrettmknight** [comment]
**Summary of payments:**

- Reviewer: @abdulrahuman5196 $500

**Comment by garrettmknight** [comment]
Dropping to weekly for payment request

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. Implementation have the same logic from before.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Regression test for this inconsistent bug doesn't seem appropriate.

@garrettmknight

**Comment by abdulrahuman5196** [comment]
@garrettmknight Gentle ping on payment processing for this issue?

**Comment by garrettmknight** [comment]
Paid - sorry about that!
