### ISSUE TITLE
[HOLD for payment 2023-12-29] [HIGH] Unknown merchant from Smartscan should not be treated as an error

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#33212]
**Problem**
Currently, if the Smartscnner marks "Unknown merchant", it is treated as an error by NewDto (displaying the red dot and encouraging the user to fix it).

**Solution**
"Unknown Merchant" should be considered a valid value for the field and no error should be displayed
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151ed01b669153bd8</li>
        <li>Upwork Job ID: 1736695539657338880</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Removing C+, as this requires access to Smartscan to test/review

**Comment by Gonals** [comment]
Readding @sobitneupane, since the PR is going to assign a C+ reviewer anyways 🤷

**Comment by bfitzexpensify** [comment]
BZ payment review complete

**Comment by JmillsExpensify** [comment]
Missing a payment summary. Re-opening for that to be added.

**Comment by sobitneupane** [comment]
@JmillsExpensify https://github.com/Expensify/App/issues/33212#issuecomment-1871954201 is the payment summary.

**Comment by JmillsExpensify** [comment]
Oh thanks! I missed that. $500 approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/33212#issuecomment-1871954201).
