### ISSUE TITLE
[HOLD for payment 2024-01-02] [$500] App unusable on Safari 16.3

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#33215]
CC @rojiphil @jjcoffee 

___

**Version Number:** ?
**Reproducible in staging?:** 
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1702869444870729

## Action Performed:
- Open app 
- Should not see error
![Screenshot 2023-12-18 at 8 37 44 AM](https://github.com/Expensify/App/assets/10736861/9157a1f4-7712-43b0-b926-143db63dcec0)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2023-12-18 at 8 37 44 AM](https://github.com/Expensify/App/assets/10736861/9157a1f4-7712-43b0-b926-143db63dcec0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9ae6039965bf1b0</li>
        <li>Upwork Job ID: 1736762561116237824</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 28064568</li>
<li>situchan | Contributor | 28065190</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment]
@anmurali we might already know the fix. Let's not make it external just yet.

**Comment by jjcoffee** [comment]
@anyongjitiger Tagging you in here as you worked on [the PR](https://github.com/Expensify/App/pull/32090) that (probably) caused this.

**Comment by Julesssss** [comment]
Not going to count this as a regression, as it's impossible to test old safari versions... so we'll treat it as a new issue, with a regular bounty

**Comment by Julesssss** [comment]
@rojiphil are you interested in working on this bug?

**Comment by rojiphil** [comment]
> @rojiphil are you interested in working on this bug?

@Julesssss 
Yes. Would be interested.
I think we can do this using capture groups
Let me look at the issue. 
Will get back within an hour.

**Comment by rojiphil** [comment]
## Proposal


### Please re-state the problem that we are trying to solve in this issue.

In older versions of Safari (i.e. 16.3) , the app does not load.

### What is the root cause of that problem?

Older versions of Safari do not support lookbehind regex. So, [here](https://github.com/Expensify/App/blob/37d34e81504248d1fcde7c2e0b8b7ce75dd00a07/src/libs/UserUtils.ts#L108), the regex uses lookbehind regex. This is the root cause.

### What changes do you think we should make in order to solve the problem?

We can solve the problem using capture groups as follows [here](https://github.com/Expensify/App/blob/37d34e81504248d1fcde7c2e0b8b7ce75dd00a07/src/libs/UserUtils.ts#L108C1-L109C59)

        const match = avatarURL.match(/(default-avatar_)(\d+)(?=\.)/);
        const lastDigit = match && parseInt(match[2], 10);

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
@Julesssss 
Have sent a proposal. 
I can raise a PR immediately.

**Comment by Julesssss** [comment]
Thank you, I'll assign a C+ for the PR review.

**Comment by situchan** [comment]
I have very old macOS 12.6 so if assigned C+ is not able to test (because they don't have old version), I can help

**Comment by rojiphil** [comment]
The [PR](https://github.com/Expensify/App/pull/33238) is ready for review.

**Comment by situchan** [comment]
I can review but giving priority to assigned reviewers first

**Comment by Julesssss** [comment]
Bumping @Santhosh-Sellavel, which Safari version are you running?

**Comment by Santhosh-Sellavel** [comment]
Feel free to review this one @situchan, I'm not sure how to test this one!

**Comment by situchan** [comment]
Just to rephrase this issue:


<img width="1371" alt="bug" src="https://github.com/Expensify/App/assets/108292595/52d84dac-e74e-41ac-bbdb-952bbca4cc8c">

**Comment by Julesssss** [comment]
PR merged awaiting deployment

**Comment by rojiphil** [comment]
> If no regressions arise, payment will be issued on 2024-01-02.

@anmurali 
Gentle bump on processing payment here
