### ISSUE TITLE
[Performance] Implement more reassure tests  

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33229]
### Problem
In the first phase of the Reassure implementation, we focused on creating performance tests to ensure that important part of the app were working properly. We looked at the LHN (SidebarLinks), ReportScreen and Composer to monitor any potential regressions in the app. We also added performance tests using measureFunction API to the methods from SidebarUtils, ReportActionsUtils and ReportUtils .

Now we can also test other parts of the application as our overall goal is to have a robust system for checking for regression issues.

### Solution
As part of our solution for regression monitoring, we are actively identifying the additional components and methods to add to our tracking list. This involves adding them to Reassure tests, which will allow us to monitor their performance and catch any potential issues early on.

Here is the updated list of components and functions to export to the community:

Components:
- [ ] components/OptionsList/BaseOptionsList - https://github.com/Expensify/App/issues/38168 
- [ ] components/InvertedFlatList/BaseInvertedFlatList
- [ ] components/Attachments/AttachmentCarousel
- [ ] components/EmojiPicker/EmojiPickerMenu
- [ ] components/Composer
- [ ] pages/workspaces/WorkspacesListPage
- [ ] pages/settings/Wallet/PaymentMethodList

Functions: 
- [ ] getOptions(OptionsListUtils) - https://github.com/Expensify/App/issues/38165 @OlimpiaZurek
- [ ] formatSectionsFromSearchTerm(OptionsListUtils) - https://github.com/Expensify/App/issues/38166
- [ ] getMemberAccountIDsForWorkspace(PolicyUtils)  - https://github.com/Expensify/App/issues/38167
- [ ] getAvatarsForAccountIDs (OptionsListUtils)
- [ ] getPersonalDetailsForAccountIDs(OptionsListUtils)
- [ ] getLastMessageTextForReport(OptionsListUtils)
- [ ] createOption(OptionsListUtils)
- [ ] getActivePolicies(PolicyUtils)
- [ ] getIneligibleInvitees(PolicyUtils)
- [ ] getPersonalDetailsByIDs (PersonalDetailsUtils)
- [ ] getAccountIDsByLogins(PersonalDetailsUtils)
- [ ] getLoginsByAccountIDs(PersonalDetailsUtils)
- [ ] getNewPersonalDetailsOnyxData(PersonalDetailsUtils)

Next components for which we want to add Reassure tests:
- [x] SignInPage
- [x] SearchPage
- [ ] NewChatPage
- [ ] MoneyRequestConfirmationList
- [ ] TaskAssignSelectorModal
- [ ] ReportParticipantPage
- [ ] RoomInvitePage
- [ ] RoomMembersPage
- [ ] EmojiPicker

The main scope of testing above components:
- rendering lists with multiple items (we try to add as much data as possible to get a more reliable result when it comes to potential regressions)
- scrolling performance
- onPress/onSelect action list item
- interactions with text input
- pressing the button

Additionally we'll use the measureFunction API to test and track the performance of methods from:
- [ ] EmojiPickerUtils
- [ ] OptionsListUtils
- [ ] PaymentUtils
- [ ] PersonalDetailsUtils
- [ ] PolicyUtils

Our goal is to focus on functions from the above list that contain heavy computations and are frequently used in the application.
We will continuously expand this tracking list by adding new components and methods that we identify during our daily work. This proactive approach allows us to catch any performance regressions early on, maintaining a fast and efficient user experience.
If you have any suggestions for further components/scope that we want to add performance tests for, or if you have already identified methods involving heavy calculations that are worth adding to the list, please feel free to contribute.

____

We should prioritize the list components first
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010343afd21b08bf6e</li>
        <li>Upwork Job ID: 1736750358470123520</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by mountiny** [comment]
c+ or BZ not needed for now

**Comment by OlimpiaZurek** [comment]
Hi, I'm Olimpia from Callstack - expert contributor group. I'd like to work on this.

**Comment by OlimpiaZurek** [comment]
@mountiny Here are the components/functions we should test first (marked  as `*` those for which we could ask the community to add tests):

Lists :
- [ ] components/OptionSelector/BaseOptionsSelector.js
- [ ] components/OptionsList/BaseOptionsList.js `*`
- [ ] components/InvertedFlatList/BaseInvertedFlatList.js`*`

Components:
- [ ]  pages/SearchPage.js
- [ ] pages/NewChatPage.js `*`
- [ ] pages/RoomInvitePage.js `*`
- [ ] pages/ReportParticipantsPage.js `*`
- [ ] pages/workspaces/WorkspacesListPage

Functions: 
- [ ] getOptions(OptionsListUtils)
- [ ] formatSectionsFromSearchTerm(OptionsListUtils) `*`
- [ ] getMemberAccountIDsForWorkspace(PolicyUtils) `*`


At a later stage, we can add the test to the remaining components from initial list and these functions: 

- [ ] getAvatarsForAccountIDs (OptionsListUtils)
- [ ] getPersonalDetailsForAccountIDs(OptionsListUtils)
- [ ] getLastMessageTextForReport(OptionsListUtils)
- [ ] createOption(OptionsListUtils)
- [ ] getActivePolicies(PolicyUtils)
- [ ] getIneligibleInvitees(PolicyUtils)
- [ ] getPersonalDetailsByIDs (PersonalDetailsUtils)
- [ ] getAccountIDsByLogins(PersonalDetailsUtils)
- [ ] getLoginsByAccountIDs(PersonalDetailsUtils)
- [ ] getNewPersonalDetailsOnyxData(PersonalDetailsUtils)


I'm also considering adding some quick instructions/tips related to testing with Reassure to README.md that could help the community implement these tests. I will prepare a separate PR for this.

**Comment by mountiny** [comment]
Thank you! That sounds great! @OlimpiaZurek 

> I'm also considering adding some quick instructions/tips related to testing with Reassure to README.md that could help the community implement these tests. I will prepare a separate PR for this.

Could you try to make these before holidays and we could export the issues for community over the holidays?

**Comment by OlimpiaZurek** [comment]
Sure, I'm working on it now.

**Comment by OlimpiaZurek** [comment]
@mountiny The [PR ](https://github.com/Expensify/App/pull/33400) with instructions is ready. I also opened a [PR](https://github.com/Expensify/App/pull/33491) with Reassure tests for `OptionsSelector`. 
The component we would like to test next is `SearchPage`. 

Since I will be on vacation for the next two weeks, one of the developer from Callstack will take over this part.

**Comment by mountiny** [comment]
Thanks!

**Comment by mountiny** [comment]
Back at it after the holidays.

Next main things are:
- look into why ReportScreen tests were timing out
- Look into ways to speed up the tests so we do not run them for more than 20-30 minutes

**Comment by mountiny** [comment]
@OlimpiaZurek How is the progress looking on this one?

**Comment by OlimpiaZurek** [comment]
Hey @mountiny! Sorry, I've been on sick leave for the last few days, so I'll be continuing my investigation into this matter this week.

I've already created a [PR draft](https://github.com/Expensify/App/pull/34217) with a small refactor to speed up testing. Locally the result is:
before:
<img width="487" alt="before" src="https://github.com/Expensify/App/assets/19835085/0ea7cb98-0ba7-40e0-aeb9-63806bee6746">
after:
<img width="326" alt="after" src="https://github.com/Expensify/App/assets/19835085/85d2ef07-6b73-4e34-949c-af8b78e625f2">


Basically, I've found that there's no need to mock Onyx before every test that uses `measureFunction()` because it doesn't need to be reset between each test case and we can just configure it once before running the tests. 

I was checking the idea of limiting the tests to the most important ones. I tested this approach locally using `jest -t @critical`, but the execution time for just a few tests marked with @cricital is still quite high. 

This week I plan to investigate using `jest —shard` or other  tools that could help run tests faster.

**Comment by mountiny** [comment]
Thanks @OlimpiaZurek! Appreciated, I hope you feel better now

**Comment by cubuspl42** [comment]
We've got a new PR for this issue, covering part of its scope:
- https://github.com/Expensify/App/pull/34228

I was pulled to review it; I'm gonna start today.

**Comment by OlimpiaZurek** [comment]
Hey @mountiny .  I checked GH Actions and noticed that after the changes from this [PR](https://github.com/Expensify/App/pull/34217) , Reassure tests take about 20 minutes instead of 35/40 minutes. I think it's a great result so far.

I also checked if splitting the tests with `jest -shard` could speed them up, but honestly it doesn't make much difference to the execution time. 

So I added some additional improvements to the tests themselves to speed them up ([draft PR](https://github.com/Expensify/App/pull/34641)).

**Comment by mountiny** [comment]
> I checked GH Actions and noticed that after the changes from this https://github.com/Expensify/App/pull/34217 , Reassure tests take about 20 minutes instead of 35/40 minutes. I think it's a great result so far.

Yes its great!

**Comment by mountiny** [comment]
Great to see these improvements, we will have to stay on top of these things as more tests are added so the time does not get too long. Thank you!

**Comment by OlimpiaZurek** [comment]
Hey @mountiny. Thanks to the improvements introduced so far, tests take ~10 mins. So I think we can go ahead and start adding more tests to the scope I proposed. 
Please let me know if you would like to ask the community to create these tests, or our team should continue to do so.

Do we want to create separate issues for each test?

**Comment by mountiny** [comment]
@OlimpiaZurek that sounds good! What are missing pieces we should do to export some of those tasks? Do you think just pointing to the readme will be enough for the contributors/ c+ and internal engineers to follow what is needed?

**Comment by mountiny** [comment]
> Do we want to create separate issues for each test?

Yep we would, lets first agree if we should handle them by agency or externally

**Comment by OlimpiaZurek** [comment]
I think the tips from the readme will be enough.

**Comment by mountiny** [comment]
Started a discussion in Slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1706786201784049)

**Comment by OlimpiaZurek** [comment]
Here is the updated list of components and functions to export to the community:

Components:
- [ ] components/OptionsList/BaseOptionsList.
- [ ] components/InvertedFlatList/BaseInvertedFlatList
- [ ] components/Attachments/AttachmentCarousel
- [ ] components/EmojiPicker/EmojiPickerMenu
- [ ] components/Composer
- [ ] pages/workspaces/WorkspacesListPage
- [ ] pages/settings/Wallet/PaymentMethodList

Functions: 
- [ ] getOptions(OptionsListUtils)
- [ ] formatSectionsFromSearchTerm(OptionsListUtils) `*`
- [ ] getMemberAccountIDsForWorkspace(PolicyUtils) `*`


- [ ] getAvatarsForAccountIDs (OptionsListUtils)
- [ ] getPersonalDetailsForAccountIDs(OptionsListUtils)
- [ ] getLastMessageTextForReport(OptionsListUtils)
- [ ] createOption(OptionsListUtils)
- [ ] getActivePolicies(PolicyUtils)
- [ ] getIneligibleInvitees(PolicyUtils)
- [ ] getPersonalDetailsByIDs (PersonalDetailsUtils)
- [ ] getAccountIDsByLogins(PersonalDetailsUtils)
- [ ] getLoginsByAccountIDs(PersonalDetailsUtils)
- [ ] getNewPersonalDetailsOnyxData(PersonalDetailsUtils)

**Comment by mountiny** [comment]
@OlimpiaZurek do you think it would be better if Callstack as experts in this field already created the scenarios for the components? I think it might be better to avoid confusion/ much discussion in the issues

**Comment by muttmuure** [comment]
Sorry, I've been a little too swamped this week to split these out into separate issues for the community to take. I will work on it early next week

**Comment by mountiny** [comment]
This is underway, we got 4 issues branched off

**Comment by mountiny** [comment]
I will create more issues

**Comment by mountiny** [comment]
We are still looking into some flakiness which is being worked on here https://github.com/Expensify/App/issues/39913 so we would only create new tests after that is resolved.

**Comment by mountiny** [comment]
Lets close this one for now and I will look into creating more issues for functions in future
