### ISSUE TITLE
[HOLD for payment 2024-01-04] Chat - Extra space before '(Until tomorrow)' in tooltip for status

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings -> profile -> status
3. Select any emoji and without any message or change in clear after, save the status
4. Open any report in which you have sent message before or send a new message in it
5. Hover on status besides your username and observe that app displays extra space before '(Until tomorrow)' text in tooltip even though message field was kept empty

## Expected Result:
App should display '(Until tomorrow)' in center in tooltip when status is saved with empty message

## Actual Result:
App displays '(Until tomorrow)' slightly towards right due to extra space before the text in tooltip when status is saved with empty message

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ee555fce-64f4-4366-9bff-89433b3dc2fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment]
@mkhutornyi thanks for your proposal but given the simplicity of the fix, I've decided to make a PR.

**Comment by NicMendonca** [comment]
no payment required

**Comment by shubham1206agra** [comment]
@NicMendonca Can you recheck payment here? I have reviewed the PR linked to this issue.

**Comment by NicMendonca** [comment]
@shubham1206agra sorry - you should have been assigned!

**Comment by NicMendonca** [comment]
@mkhutornyi you are not eligible for payment here

**Comment by shubham1206agra** [comment]
Accepted

**Comment by NicMendonca** [comment]
paid!
